### ISSUE TITLE
mongodb support directConnection typeorm@0.3.15 still not working properly

### ISSUE THREAD

**Issue by fatihaziz** [typeorm/typeorm#10023]
### Issue description

Follow up from this issue https://github.com/typeorm/typeorm/issues/9116, directConnection still not working for me 

### Expected Behavior

It should connect to the mongo database using directConnection 

### Actual Behavior

I have spent hours attempting to resolve the problem of TypeORM failing to connect to a custom MongoDB server. Specifically, the error message "ReplicaSetNoPrimary" was being thrown, which I have previously encountered due to the `directConnection` value not being set to true. While investigating this issue, I came across a related issue which purported to have been resolved. Unfortunately, despite trying numerous option combinations, including the one suggested in the related issue, I was unable to connect to the server using TypeORM.

I attempted to use the MongoDB driver directly by injecting it into the `driver` option, using `driver: new MongoClient(clientUrl)`. However, this resulted in an error message indicating that `connect was not a function`. As a result, I decided to investigate the TypeORM code itself, logging the generated connection string and options to try to identify the problem. 

![typeorm-1](https://user-images.githubusercontent.com/23287658/236707941-af761973-3135-465c-bcea-acb4dbb6ef86.png)
As we see here, direct connection is omitted on `buildConnectionOptionsResult`
![typeorm-2](https://user-images.githubusercontent.com/23287658/236707791-3e5bbd69-ad9c-46e6-85d5-68ac20a687b2.png)

Upon doing so, I noticed that `directConnection` was not included in the `validOptionNames` array in `MongoDriver.js`.
![typeorm-3](https://user-images.githubusercontent.com/23287658/236707796-562da53d-f910-4f9b-84f4-4ea7ee9bec53.png)

After hardcoding the missing `directConnection` option, the issue was finally resolved.
![typeorm-4](https://user-images.githubusercontent.com/23287658/236707974-c96d4c69-392d-4d13-9e42-f871115987ea.png)

Also I make sure its not only on my side, I try to check the generated code that pushed to npm,
![image](https://user-images.githubusercontent.com/23287658/236708385-eacb9474-8247-42c6-a184-553dd7a5bbd9.png)
and the `directConnection` options really not there

### Steps to reproduce

1. Install mongodb@5 and typeorm@0.3.15 using `pnpm i -D mongodb@5 typeorm@0.3.15
2. Write minimal test code like this:
```typescript
import { DataSource } from "typeorm"
import myEntities from './myEntities'

const connect = async () => {
   const myUrl = "mongodb....."
   const _client = new DataSource({
     url: myUrl,
     directConnection:true,
     entities: myEntities,
   })
   await _client.initialize()
   return _client
}
connect()
```
3. Getting error `ReplicaSetNoPrimary`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    windows 11      |
| Node.js version     | 16.17.0  |
| Typescript version  | 5.0.4  |
| TypeORM version     | 0.3.15  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [X] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by fatihaziz** [comment]
I will close this issue, since its my ignorance that the solution not published yet

**Comment by almcaffee** [comment]
@fatihaziz  did you find a solution for this error? I am seeing similar while using the exact connection string from Mongo, so it has to be a typeorm issue.

**Comment by fatihaziz** [comment]
yes, just use the newer version of typeorm

**Comment by fatihaziz** [comment]
since my issue was the missing directt connection option, it was 2 years ago.
and its fixed.

-
your issue, i think its different and you should open new issue i think.
