### ISSUE TITLE
PrimaryGeneratedColumn('uuid') is not working

### ISSUE THREAD

**Issue by maddindeiss** [typeorm/typeorm#1002]
If I mark my id property in my entity as a `@PrimaryGeneratedColumn('uuid')`  it is set to `AUTOINCREMENT`. 
This will result in a SQLError:
```
query failed:  CREATE TABLE "project" ("id" varchar NOT NULL PRIMARY KEY AUTOINCREMENT, ...
```
```
SQLError {code: 5, message: "could not prepare statement (1 AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY)"}
```

But my id is type `string` because of the UUID.

```javascript
@Entity()
export class Project {
    @PrimaryGeneratedColumn('uuid')
    id: string;
}
```

So the example in the Documentation won't work: 
[http://typeorm.io/#/decorator-reference/primarygeneratedcolumn](http://typeorm.io/#/decorator-reference/primarygeneratedcolumn)

Am I doing something wrong or is this a bug?

And thanks for the great work!

**Comment by daniel-lang** [comment]
Hey, what database system are you using?

**Comment by pleerock** [comment]
I guess its something related to sqlite since "AUTOINCREMENT" is sqlite-specific keyword.

**Comment by daniel-lang** [comment]
@maddindeiss I created a [test case](https://github.com/daniel-lang/typeorm/tree/issue-1002/test/github-issues/1002) which works on postgres, mariadb, sqlite and mysql. It simply inserts a an entity with a uuid primary column.

Is your use-case more complex? What are the steps to reproduce this error?

**Comment by maddindeiss** [comment]
@daniel-lang You are right. I was using the `websql` driver and got that SQLError.
I switched over to the `cordova` driver and everything works fine now.

So maybe this is just a `websql` problem.

**Comment by daniel-lang** [comment]
Maybe, I will have to check

**Comment by daniel-lang** [comment]
Yes, it's a problem with the websql driver, #1003 contains a fix

**Comment by pleerock** [comment]
thanks to @daniel-lang this can be closed now

**Comment by maddindeiss** [comment]
@daniel-lang thanks for fixing the issue
