### ISSUE TITLE
Numbers loose their decimals when reading from the database

### ISSUE THREAD

**Issue by effective-giggle** [typeorm/typeorm#10026]
### Issue description

Numbers loose their decimals when reading from the database

### Expected Behavior

Numbers with decimals, e.g. (0.1234) are correctly read from the database (sqlite | oracle) for a numeric column.

### Actual Behavior

The numbers are saved correctly in the database.
The numbers loose their decimals when being read from the database.
E.g. the value 0.1234 is read as 0.

This was working until (incl.) 0.3.10, from 0.3.11 - 0.3.15 the behavior is broken.

### Steps to reproduce

Test Entity:

@Entity()
export class MyTestEntity {
  @PrimaryGeneratedColumn()
  @ApiResponseProperty()
  id: number;

  @Column()
  @ApiResponseProperty()
  data: number;
}

const data: MyTestEntity = { id: 1, data: 0.123 };
const entity = await this.repository.save(data);

const storedEntity = await this.repository.findOne({ where: { id: 1 } });

==> storedEntity.data is 0, in the database the value is setcorrectly

Created a Stackblitz:
https://stackblitz.com/edit/nestjs-starter-jrar2c?file=src%2Fapp.service.ts

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  windows 10       |
| Node.js version     | v16.19.1  |
| Typescript version  | 4.9.5  |
| TypeORM version     | 0.3.11 - 0.3.15  |

### Additional Context

See example in stackblitz:
https://stackblitz.com/edit/nestjs-starter-jrar2c?file=package.json

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [X] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [X] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by effective-giggle** [comment]
I think I found the root cause of this issue for oracle:
[src/driver/oracle/OracleDriver.ts](https://github.com/typeorm/typeorm/compare/0.3.10...0.3.11?diff=unified#diff-6528f3b2035bc541369d7ee80f64db46ec10b502c7d2195807c7ccffe4526601R550)

shouldn't be casted to int but a number instead

**Comment by pleerock** [comment]
Closing, reason is explained in #10027
