### ISSUE TITLE
TypeORM synchronize database even if it is up to date

### ISSUE THREAD

**Issue by juliengbt** [typeorm/typeorm#10040]
### Issue description

With synchronize set to true, typeorm tries to synchronize the database even if it is already up to date

### Expected Behavior

When the database is up to date the schemaBuilder should return an empty array for the upQueries

### Actual Behavior

The schema builder returns a bunch of queries

### Steps to reproduce

https://github.com/juliengbt/typeorm_synchronize

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     MacOS     |
| Node.js version     | 18.16.0  |
| Typescript version  | 5.0.4  |
| TypeORM version     | 0.3.16  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by juliengbt** [comment]
After some investigation, typeorm has detected a change in column length for the primary key generated uuid.
The function `getColumnLength` in MysqlDriver returns an empty string. This is because the condition below is false but it should be true. 

```typescript
if (column.generationStrategy === "uuid" && column.type === "varchar") return "36"
```

It is false because column.type is "uuid" and not "varchar".
We could update the condition like this.

```typescript
if (column.generationStrategy === "uuid" &&  (column.type === "varchar" || column.type === "uuid")) return "36"
```

 But I think there's something wrong because the type should be varchar when using mysql right ? Why is it uuid ?

**Comment by frynt** [comment]
Sam G loves that
