### ISSUE TITLE
Error: Entity … using single-table inheritance, it should also have a discriminator column

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#1004]
Hello!

After updating to `0.1.0-alpha.50` I'm getting the following error: `Entity … using single-table inheritance, it should also have a discriminator column. Did you forget to put @DiscriminatorColumn decorator?`

However, I have `@DiscriminatorColumn` and it was working in the past.

Here's my entity:

```typescript
import {Entity} from 'typeorm/decorator/entity/Entity';
import {TableInheritance} from 'typeorm/decorator/entity/TableInheritance';
import {Column, DiscriminatorColumn, JoinColumn, ManyToOne, PrimaryGeneratedColumn} from 'typeorm';

@Entity('account_operations')
@TableInheritance('single-table')
@DiscriminatorColumn({ name: 'type', type: 'text'})
export class AccountOperation {

  @PrimaryGeneratedColumn()
  id?: number;

  @Column()
  type: string;

  // …

}
```

Do you know what could be causing this? Thanks.

---

Also, for some reason, `Entity` and `TableInheritance` decorators couldn't be imported from the root namespace (at least IDE is not allowing to do so).

**Comment by slavafomin** [comment]
Actually, removing `@Column` decorator from `type` property helps to remove the error, but property is not loaded from the database then.

**Comment by pleerock** [comment]
There are lot of problems with single/class table inheritance patterns, and they all are quite complex and require complete refactoring of those areas. Something that can be done in the future.

**Comment by pleerock** [comment]
I made changes trying to restore class table inheritance functionality. Please check it in `0.2.0-alpha.11` and let me know if still not works.

**Comment by MohsinGhani** [comment]
Hello @pleerock , I did single-table inheritance and it's working fine but is there any way to do It without an additional discriminator column?
