### ISSUE TITLE
Raw operator params cannot as json path

### ISSUE THREAD

**Issue by shulandmimi** [typeorm/typeorm#10059]
### Issue description

Raw operator params cannot as json path

### Expected Behavior

```ts
const labels = {
    foo: 'bar'
}
repository.find({
    where: {
        labels: And(...entries(labels).map(([key, val]) => Raw(alias => ` JSON_EXTRACT(${alias}, '$.:key') = :val`, { key, val }))),
    },
});
```
```sql
select column from repository where ( JSON_EXTRACT(`repository`.`labels`, '$."foo"') = 'bar')
```
or 
```sql
select column from repository where ( JSON_EXTRACT(`repository`.`labels`, '$.foo') = 'bar')
```

### Actual Behavior

```sql
select column from repository where ( JSON_EXTRACT(`repository`.`labels`, '$.'foo'') = 'bar')
```

### Steps to reproduce

```ts
// typeorm.ts
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export default class RepositorySchema {
    @PrimaryGeneratedColumn('uuid')
    id!: string;

    @Column({ type: 'json' })
    labels!: Record<string, string>;
}

// index.ts

const datasource = new DataSource({
    username: 'root',
    password: 'password',
    database: 'database',
    type: 'mysql',
    host: '127.0.0.1',
    port: 3306,
    entities: [RepositorySchema],
    synchronize: true,
});

async function main() {
    await datasource.initialize();
    const repository = datasource.getRepository(RepositorySchema);

    const labels = {
        foo: 'bar',
    };
    await repository.find({
        where: {
            labels: And(...Object.entries(labels).map(([key, val]) => Raw(alias => ` JSON_EXTRACT(${alias}, '$.:key') = :val`, { key, val }))),
        },
    });
}

main();
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Linux 6.1 Arch Linux  |
| Node.js version     | v18.12.1  |
| Typescript version  | 5.0.4 |
| TypeORM version     | 0.3.16  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by iJhefe** [comment]
you can try `Raw(alias => ` JSON_EXTRACT(${alias}, ':key') = :val`, { key: `$.${key}`, val }))

**Comment by shulandmimi** [comment]
> you can try
> 
> ```
> Raw(alias => ` JSON_EXTRACT(${alias}, ':key') = :val`, { key: `$.${key}`, val }))
> ```

it works, thanks
