### ISSUE TITLE
Nested "OR" Condition/Operation Support in Repository Where condition

### ISSUE THREAD

**Issue by sthanase** [typeorm/typeorm#10054]
### Feature Description

I would like to achieve the below using repository.where method

Select * from user where (firstName like "%Mike% **OR** firstName IN ("King", "Kong")) AND (lastName like "%Mike% **OR** lastName IN ("King", "Kong"))

I am aware this can be acheived through query builder and raw queries but currently there seems to no way to achieve this using the repository.where method.  Is it a good idea to introduce a OR operator similar to the existing AND operator to achieve the above. 

### The Solution

Introduce OR operator similar to the AND operator to do something similar like below. 

await repository.find( 
  where: {
    firstName: **OR**(Like('%Mike%'), In('King','Kong')),
    lastName: **OR**(Like('%Mike%'), In('King','Kong')),
 },
})

### Considered Alternatives

This can be achieved through query builder and raw queries.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [X] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by iJhefe** [comment]
"OR" are handled with array in `where`, so you can do: 
```
await repository.find(
  where: [{
    firstName: Like('%Mike%'),
    lastName: Like('%Mike%'),
  }, 
  {
    firstName: In('King','Kong')
    lastName: In('King','Kong')
  }
],
})
```
but also I agree that we should have an OR operator

**Comment by sthanase** [comment]
> "OR" are handled with array in `where`, so you can do:
> 
> ```ts
> await repository.find(
>   where: [{
>     firstName: Like('%Mike%'),
>     lastName: Like('%Mike%'),
>   }, 
>   {
>     firstName: In('King','Kong')
>     lastName: In('King','Kong')
>   }
> ],
> })
> ```
> 
> but also I agree that we should have an OR operator

Your suggestion will not work for all scenarios. Your solution mixes "OR" and "AND" and may not yield the results we are expecting.

**Comment by Lqvrent** [comment]
> "OR" are handled with array in `where`, so you can do:
> 
> ```ts
> await repository.find(
>   where: [{
>     firstName: Like('%Mike%'),
>     lastName: Like('%Mike%'),
>   }, 
>   {
>     firstName: In('King','Kong')
>     lastName: In('King','Kong')
>   }
> ],
> })
> ```
> 
> but also I agree that we should have an OR operator



I have something like this (using MySQL):

where = [
  {
    field1:  Like("%...%"),
    field2:  Like("%...%"),
    field3:  Like("%...%"),
    field4:  Like("%...%"),
    field5  Like("%...%"),
  },
  {
    field1: {
      relation: { id: X }
    }
  }
]

But it seems like the first part is completely ignored. Whatever I search, he is returning all element with field1->relation-id == X

+1 for this issue.
