### ISSUE TITLE
uuid Duplicate entry '' for key PRIMARY

### ISSUE THREAD

**Issue by kumv-net** [typeorm/typeorm#10053]
### Issue description

 using generated uuid, the automatically generated field length is 36, 

### Expected Behavior

 using generated uuid, the automatically generated field length is 36, 

### Actual Behavior

 using generated uuid, the automatically generated field length is 36, 

### Steps to reproduce

 using generated uuid, the automatically generated field length is 36, 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  |
| Typescript version  | x.y.zzz  |
| TypeORM version     | 0.3.16  |

### Additional Context

![image](https://github.com/typeorm/typeorm/assets/70076074/eff25356-73f1-4e4f-9718-29ac24d24311)

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`room\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`room\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`room\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
    }

query failed: ALTER TABLE `room` ADD `id` varchar(36) NOT NULL PRIMARY KEY
error: Error: Duplicate entry '' for key 'room.PRIMARY'

![image](https://github.com/typeorm/typeorm/assets/70076074/e508e7f7-eeeb-4d5c-9fa8-81d522c4d610)

When using generated uuid, the automatically generated field length is 36, but when migration: generate performs field comparison, the string length is 255, resulting in my primary key field being regenerated every time. The current solution is to specify length: 255. The above are all my guesses, I hope they can be helpful to you

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by wudiyugi** [comment]
same error and now I'am using 0.3.15

**Comment by okanwyl** [comment]
same error

**Comment by ReneZeidler** [comment]
I'm getting the same error using simply a `@PrimaryGeneratedColumn('uuid')` and MySQL as the database.

With `synchronize: true`, TypeORM drops the column and recreates it on every start. It detects that the column has changed, even though it was a `VARCHAR(36)` before and it just creates the same `VARCHAR(36)` column again.

This issue was introduced in 0.3.16. Downgrading to 0.3.15 fixes this problem.

**Comment by smith-xyz** [comment]
@ReneZeidler yes I think this is correct - this was an oversight on my part for not testing a synchronizing scenario.

**Comment by ReneZeidler** [comment]
I also just saw that this is a duplicate of #10040, which already has a PR with the same proposed fix attached to it: #10041

**Comment by N-Andronopoulos** [comment]
Duplicated of mine too #10090

**Comment by Fengjing95** [comment]
+1! same problem

**Comment by kumv-net** [comment]
length 36
