### ISSUE TITLE
Incorrect table name used for entity insertion with single table inheritance

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#1005]
Hello!

After updating to `0.1.0-alpha.50` I'm getting an error when trying to create new entity using subclass and single table inheritance.

Here's the parent:

```typescript
import {Entity} from 'typeorm/decorator/entity/Entity';
import {TableInheritance} from 'typeorm/decorator/entity/TableInheritance';
import {Column, DiscriminatorColumn, JoinColumn, ManyToOne, PrimaryGeneratedColumn} from 'typeorm';

@Entity('account_operations')
@TableInheritance('single-table')
@DiscriminatorColumn({ name: 'type', type: 'text'})
export class AccountOperation {

  @PrimaryGeneratedColumn()
  id?: number;

  // …

}
```

And here's the subclass:

```typescript

import {SingleEntityChild} from 'typeorm/decorator/entity/SingleEntityChild';
import {Column, JoinColumn, ManyToOne} from 'typeorm';

import {AccountOperation} from './account-operation.model';


@SingleEntityChild()
export class PurchaseAccountOperation extends AccountOperation {

  @Column()
  orderId: number;

  // …

}

```

When I try to save the new instance of `PurchaseAccountOperation`, it generates the following insert statement: `INSERT INTO "purchase_account_operation" …`, however, it should use the name of the parent class, i.e. `account_operations`.

**Comment by slavafomin** [comment]
After further investigation, it looks like it was broken in `0.1.0-alpha.48`.

**Comment by pleerock** [comment]
Right now table inheritance is a problematic topic to talk about, it needs deep refactoring and we are going to fix all table-inheritance related issues in 0.2.0 or even 0.3.0 versions

**Comment by slavafomin** [comment]
The problem is that I'm using it in production already, and the behavior degraded in version `0.1.0-alpha.48`, so I'm effectively blocked and can't upgrade past this version. Could you at least take a look at what could have happened in that version? I'm afraid I don't have enough understanding of TypeORM internals to effectively handle this problem on my own. And I would really like to be able to incrementally upgrade and refactor my project in parallel with TypeORM progressing. Otherwise, if I will wait for `0.3.0` the changes I would have to make in order to migrate would be too dramatic.

**Comment by pleerock** [comment]
I made changes trying to restore class table inheritance functionality. Please check it in `0.2.0-alpha.11` and let me know if still not works.
