### ISSUE TITLE
I am trying to build the following query using query builder:

### ISSUE THREAD

**Issue by veerareddy123** [typeorm/typeorm#1008]
I am trying to build the following query using query builder:

const QueryBuilder = this.dao.createQueryBuilder("attendance");
QueryBuilder.select("sum(attendance.mins)", "mins")
QueryBuilder.addSelect("attendance.user_id", "user");
QueryBuilder.where("attendance.user_id = :id", {id: "J7IZ3YXX"});
QueryBuilder.andWhere("updated_date BETWEEN :startDate AND :endDate", {startDate: '2017/09/18', endDate: '2017/09/20'});
const users= await QueryBuilder.getRawMany();

and my attendance service looks like this 

    async userdate(reqData: any){
        try{
             console.log(reqData);
             let data:any = await this.attendanceDao.findAll(reqData)
             console.log(data);
             
             return Promise.resolve(data)
        }catch (error) {
            return Promise.reject(error);
        }
    }
after npm start and once i check with the swagger i am passing userid and i am getting the response of data as undefined.can you anyone please help me out this service

**Comment by daniel-lang** [comment]
Please comment on your original issue #1006!
