### ISSUE TITLE
findOne has wrong return type

### ISSUE THREAD

**Issue by lmexo** [typeorm/typeorm#10089]
### Issue description

Return Type of findOne is actually `MyEntity | null` but is defined as `MyEntity`

### Expected Behavior

Considering TypeScript is in strict mode (esp. strict null checks)

```typescript
const user = userRepository.findOne(...);
console.log(user.name); // <- TS should complain here
```

TS should complain as `user` could be `null`, but the return type is defined as `User` (or the entity the repositor is made for) instead of `User | null`

### Actual Behavior

The return type is defined as `User` (or the entity the repositor is made for) instead of `User | null`, thus TS does not complain

### Steps to reproduce

Create a repository and type the code above.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Win 11 / WSL2 (Ubuntu 22.04) |
| Node.js version     | 18.16.0  |
| Typescript version  | 5.0.4  |
| TypeORM version     | 0.3.15  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by iJhefe** [comment]
`findOne` can return `null` so the type is right! I think you are looking for `findOneOrFail`, that ensure the value.

**Comment by lmexo** [comment]
That is exactly what I am talking about: TypeORM may return `null` but the return type is not `User | null` but `User`

**Comment by lmexo** [comment]
I had a look into the src file and appearently the code return type is defined correctly. For some reason VS code did not show me.... 🤷

https://github.com/typeorm/typeorm/blob/d4607a86723eef07e62e6d7321a07f3ae5ed1f90/src/repository/Repository.ts#L576
