### ISSUE TITLE
findAndCount fetches weird number of results.

### ISSUE THREAD

**Issue by N-Andronopoulos** [typeorm/typeorm#10091]
### Issue description

findAndCount breaks when ordering relations.

### Expected Behavior

To fetch like 5 results, not one.

```
this.orderRepo.findAndCount({
          relations: {
            items: true
          },
          order: {
            created: "DESC",
            // This is the issue:
            // When I add the ordering of relation it behaves
            // weirdly and I think It should not....
            items: {
              created: "DESC"
            }
          },
          skip: 0,
          take: 5,
        })
```

### Actual Behavior

Fetch (in this sample) 1 result...

```
this.orderRepo.findAndCount({
          relations: {
            items: true
          },
          order: {
            created: "DESC",
            // This is the issue:
            // When I add the ordering of relation it behaves
            // weirdly and I think It should not....
            items: {
              created: "DESC"
            }
          },
          skip: 0,
          take: 5,
        })
```

I get back 1 out of 25 when I asked for 5...
But when I remove the relation ordering it works just fine.

```
this.orderRepo.findAndCount({
          relations: {
            items: true
          },
          order: {
            created: "DESC",
          },
          skip: 0,
          take: 5,
        })
```

I get 5 results, correct.

### Steps to reproduce

====> see [sample project](https://github.com/N-Andronopoulos/typeorm-issue-schema-creation)
(its used for two issues :P )

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v18.16.0  |
| Typescript version  | ^5.0.0  |
| TypeORM version     | 0.3.16  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by iJhefe** [comment]
`count` method does not consider `take` and `skip`, its returns the count only applying the conditions

**Comment by N-Andronopoulos** [comment]
I'm not talking about the the count number, I'm talking about the length of the return array. The count is always correct the items returned are not. Please checkout the sample repo.

**Comment by Pressidentt** [comment]
I spent a few hours figuring out what was problem in that case...
So as I understood, the problem is not in TypeORM per say, as it is in MySQL. Nested ordering seems to work if you use postgres. The SQL query that TypeORM generates looks right and it is similar for both mysql and postgres.
**So in order to fix that**, you will need to do nested **queries** instead of nested ordering. Here is an example:
`const itemQuery = this.itemRepo
      .createQueryBuilder('item')
      .select('item.*')
      .orderBy('item.created', 'DESC')
      .limit(1);

    const orderQuery = this.orderRepo
      .createQueryBuilder('order')
      .leftJoinAndSelect('(' + itemQuery.getQuery() + ')', 'item', 'item.orderId = order.id')
      .orderBy('order.created', 'DESC')
      .take(5);

    const result = await orderQuery.getMany();
`

**Comment by N-Andronopoulos** [comment]
Can be bypassed by doing something like this:
```
@Entity('foobar', {
  orderBy: {
    created: 'DESC'
  }
})
```
