### ISSUE TITLE
Update peerDependencies for oracledb to allow install the latest version

### ISSUE THREAD

**Issue by hanc2006** [typeorm/typeorm#10094]
### Feature Description

Oracle has released version 6 of oracledb, a pure javascript thin driver that don't require oraclient. This mean that now oracle driver works on mac M1/M2 processor without using rosetta. 

### The Solution

update peerDependencies constraint for oracledb.

### Considered Alternatives

A workaround is `npm install --legacy-peer-deps` that ignore the dependency constraint.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [X] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by ertl** [comment]
Would be greate if we could get rid of the instant client libs. I triedintegrating the new version, but tests are failing. I'm not sure if functions like _dbms_lob.compare_ work with the Thin Client.

Any Experiences using the Thin Client?

**Comment by AlexMesser** [comment]
fixed in #10285
