### ISSUE TITLE
DriverPackageNotInstalledError: SQLite package has not been found installed (NPM Workspaces)

### ISSUE THREAD

**Issue by frbuceta** [typeorm/typeorm#10095]
### Issue description

Migrating to NPM Workspaces and typeorm complains that he doesn't have sqlite3 installed.

### Expected Behavior

Continue to operate normally

### Actual Behavior

Failure to detect sqlite3 when using NPM Workspaces

### Steps to reproduce

https://github.com/loopbackio/loopback-next/pull/9562

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Arch Linux |
| Node.js version     | 18.15.0  |
| NPM version     | v9  |
| Typescript version  | 4.9.5  |
| TypeORM version     | 0.3.16  |

> In tests, it is failing on all operating systems.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [X] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by bakhtarov** [comment]
same to me for sqlserver after update to v0.3.16

**Comment by frbuceta** [comment]
SQLite is catching the --ignore-scripts from my npm ci and not running the install script. So it is an NPM error.
