### ISSUE TITLE
Is it possible to create a false connection? 

### ISSUE THREAD

**Issue by netchiarelli** [typeorm/typeorm#101]
Is it possible to create a false connection (eg to sqlite)? I just needed to do a dump of the final sql code of a transaction, but without executing the transaction itself (actually the database will not even exist, I just need the final result of an sqlite transaction).

**Comment by pleerock** [comment]
No, you can't. Schema generation is based on the schema of the current database. It compares current database schema with entities and creates corresponding queries. If there is no connection, there is no database to synchronize with. However you can make a fork and change things the way you need and implement functionality you need (creating new schema without database connection). I think it wont be so hard.
