### ISSUE TITLE
Ionic websql driver

### ISSUE THREAD

**Issue by bolivir** [typeorm/typeorm#1010]
Hi, 

I just updated to `0.1.0-alpha.50`, is there a way to get websql working in this version?
There is a problem with the version number that should be a string, but it expects a integer.

Before i used websql to quickly develop things in browser before running on a actual device.
It would be really nice if websql would work.

Maybe someone got a working example ?

**Comment by daniel-lang** [comment]
This issue is fixed but not released. You should be able to specify the websql specific option in "extra" and get it working. Like this:
```json
{
   type: "websql",
   extra: {
      version: "1.0"
      description: "",
      size: 1024 * 1024 // or something else
      database: "name"
}
```
I think, this still works, but I'm not sure

**Comment by bolivir** [comment]
It still works, but the websql synchronize functionality will fail if enabled.
It throws an sql error about the temp table that gets created, is there any solution for this? 
Or is the only way to enable/disable synchronize functionality so that the app will work in development?

**Comment by daniel-lang** [comment]
Synchronization is not not fully supported with websql. So you will have to disable it.
