### ISSUE TITLE
Not reading TYPEORM_DROP_SCHEMA from .env file

### ISSUE THREAD

**Issue by mzygmunt** [typeorm/typeorm#1011]
Typeorm not reading TYPEORM_DROP_SCHEMA from .env file.

**Comment by pleerock** [comment]
This enhancement will be released in `0.1.1`

**Comment by mzygmunt** [comment]
Thank you!

**Comment by krzkaczor** [comment]
@pleerock thanks for fixing the issue! Could you tell me when do you want to release next version? Or is there any simple way to use current master?

**Comment by pleerock** [comment]
You can pull, do `npm i` then `gulp package` and copy contents of `build/package` into your app's `node_modules`.

Alternatively, you can apply my changes from my commit above into your node_modules/typeorm js files.

Or you simply need to wait, Im going to release next version early next week.
