### ISSUE TITLE
Its not allow me to build the application and given me TS1005 error

### ISSUE THREAD

**Issue by amperera** [typeorm/typeorm#10113]
### Issue description

I'm creating backend application using aws cdk, rds(postgress) and tyescript. Later i have installed typeORM and when I try to build the application its given me errors. 

### Expected Behavior

Should work without giving an error 

### Actual Behavior

lib/layers/typo/node_modules/typeorm/common/PickKeysByType.d.ts(5,19): error TS1005: ']' expected.
lib/layers/typo/node_modules/typeorm/common/PickKeysByType.d.ts(5,22): error TS1005: ';' expected.
lib/layers/typo/node_modules/typeorm/common/PickKeysByType.d.ts(5,27): error TS1005: ';' expected.
lib/layers/typo/node_modules/typeorm/common/PickKeysByType.d.ts(5,48): error TS1005: ';' expected.
lib/layers/typo/node_modules/typeorm/common/PickKeysByType.d.ts(5,49): error TS1128: Declaration or statement expected.
lib/layers/typo/node_modules/typeorm/common/PickKeysByType.d.ts(6,1): error TS1128: Declaration or statement expected.
lib/layers/typo/node_modules/typeorm/driver/mongodb/typings.d.ts(3331,117): error TS1005: '?' expected.
lib/layers/typo/node_modules/typeorm/driver/mongodb/typings.d.ts(3331,127): error TS1005: ';' expected.
lib/layers/typo/node_modules/typeorm/driver/mongodb/typings.d.ts(3331,131): error TS1005: ';' expected.
lib/layers/typo/node_modules/typeorm/driver/mongodb/typings.d.ts(3331,166): error TS1005: ',' expected.

### Steps to reproduce

npm run build

### My Environment

  "typescript": "~3.9.7"
  "typeorm": "^0.3.16"

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [X] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by klynchkurzawa** [comment]
Also experiencing this issue when attempting to build typescript applications with typeorm as a dependency:
* typeorm version: `0.3.15`
* node version: `16.19.1`

**Comment by amperera** [comment]
@klynchkurzawa I have fixed this issue by updating the typescript version to the latest. Please try
