### ISSUE TITLE
`migration:generate` ignores DataSource's `schema` value

### ISSUE THREAD

**Issue by luke-lacroix-healthy** [typeorm/typeorm#10119]
### Issue description

When the data source sets the schema.

### Expected Behavior

Setting the schema in the DataSource should appropriately use that schema name in the generated migration.

### Actual Behavior

The schema used in the migration is ALWAYS the directory name, as seen in the code:
https://github.com/typeorm/typeorm/blob/d4607a86723eef07e62e6d7321a07f3ae5ed1f90/src/commands/MigrationGenerateCommand.ts#L161

### Steps to reproduce

Example project structure:
```
services/
    send-results/
       ormconfig.js
       package.json
       src/entities/
       src/migrations/
```
1. Create a datasource in `ormconfig.js` with a `schema` property of 'fubar-zipzap'.
2. Create an entity in the entities folder
3. Run `npx typeorm-ts-node-commonjs migration:generate src/migrations/initial`
4. Look at the generated migration and notice that the migration does not reference the `fubar-zipzap` schema but, instead, references 'send-results'.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.15.1 |
| Typescript version  | 5.0.4 |
| TypeORM version     | 0.3.16 |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by luke-lacroix-healthy** [comment]
I found that the issue was, in my case, that I was explicitly setting the schema on the entity and that was overring the DataSource.

**Comment by forrestwilkins** [comment]
I'm experiencing the same issue but I haven't even set the schema on the entity itself. I have multiple schemas for local development, but it only applies to just one of them regardless of what I have in my data source.
