### ISSUE TITLE
[Bug] RelationCount cannot be used with default OrderBy

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#1012]
For some reason using a `RelationCount` with a relation that has a default `OrderBy` generates an invalid query for count:
```sql
SELECT 
	"MON_ROUTE_LINE"."routeId" AS "parentId", 
        COUNT(*) AS "cnt" 
FROM 
	"adempiere"."MON_ROUTE_LINE" "MON_ROUTE_LINE" 
WHERE 
	"MON_ROUTE_LINE"."routeId" IN (1) 
GROUP BY 
	"MON_ROUTE_LINE"."routeId" 
ORDER BY 
	"MON_ROUTE_LINE"."MON_ROUTE_LINE_ID" DESC
```
Check that last `ORDER BY`, if it is just a count operation, why in the world would it need to order?

Ping @pleerock.

**Comment by luchillo17** [comment]
Confirmed, if i remove the default `OrderBy` config in the `Entity` decorator the query goes all right.

**Comment by pleerock** [comment]
`@RelationCount` is considered experimental, it does not work properly and I even plan to remove this functionality.

**Comment by luchillo17** [comment]
Really? then if i rely on it how would i replace it? raw SQL?

**Comment by pleerock** [comment]
nope you can build sql query you need using query builder, execute it and get raw results.

**Comment by luchillo17** [comment]
Yeah but i would have to make 2 separate queries, one just for counting? is there a way to embed that sql query in a column so i don't have to use the query builder whenever i want to count the relations?

**Comment by pleerock** [comment]
If relation count makes it in a single request then you can make it in a single request as well. Relation count is a bit tricky and huge functionality with relative high maintenance cost to value it brings. So, for now decision is to remove it. If one day we'll bring ORM into ideal condition with everything polished and all features implemented we'll think about bring this feature back.

**Comment by luchillo17** [comment]
So if i wanted to get both the count and the relations in single query i would have to use `QueryBuilder` to get the count in the same query i have for an entity, while still getting those relations at the same time with joins, indeed sounds tricky.
