### ISSUE TITLE
Querying relations

### ISSUE THREAD

**Issue by nehalist** [typeorm/typeorm#1013]
I'm either too stupid or didn't find anything about: how to query by the related table? E.g.:

```
const author = await Author.findOne({ name: "bob" });
const books = await Book.findOne({ author: author.id });
```

**Comment by pleerock** [comment]
Using [find options](http://typeorm.io/#/find-options): 

```ts
const author = await Author.findOne({ where: { name: "bob" }, relations: ["books"] });
```

**Comment by pleerock** [comment]
Let me know if this solution won't work for you.

**Comment by nehalist** [comment]
Works, thank you @pleerock. But there's no way to do it the other way round (query books by searching author id)?

**Comment by pleerock** [comment]
This code should work:

```ts
const books = await Book.createQueryBuilder("book")
   .where("book.author = :author", { author: author.id })
   .getMany();
```

**Comment by mattdamon108** [comment]
I guess it's been a while and recently I've tried to implement the same thing with the latest version of typeORM. I did like this. I hope this might be helpful to future researchers.

```javascript
const books = await Book.createQueryBuilder("book")
  .leftJoinAndSelect("book.author", "author")
  .where("author.id = :id", { id: author.id })
  .getMany();
```

or

```javascript
const books = await Book.createQueryBuilder("book")
  .innerJoin("booke.author", "author", "author.id = :id", { id: author.id })
  .getMany();
```

**Comment by jakobrosenberg** [comment]
Is there really no way to do a basic query like below in recent versions?

```javascript
myPets = await Pets.find({ owner_id: 123 })
```

**Comment by mustafahafidi** [comment]
> Is there really no way to do a basic query like below in recent versions?
> 
> ```js
> myPets = await Pets.find({ owner_id: 123 })
> ```

Yes you can just do

> ```js
> myPets = await Pets.find({ owner: {id: 123} })
> ```

**Comment by jakobrosenberg** [comment]
@mustafahafidi 

Thanks that's what I'd been using. Unfortunately it requires unnecessary normalizing, extra DTOs and unwanted Typescript hickups.

I've since added the relational field to the entity manually. It's working so far, but I don't know if there are any unforeseen consequences.

**Comment by brinzi** [comment]
@jakobrosenberg I am facing the same challenge right now. Can you briefly explain what did you mean by "I've since added the relational field to the entity manually. It's working so far, but I don't know if there are any unforeseen consequences."

**Comment by JarvisPrestidge** [comment]
> @jakobrosenberg
> 
> > Is there really no way to do a basic query like below in recent versions?
> > ```js
> > myPets = await Pets.find({ owner_id: 123 })
> > ```
> 
> Yes you can just do
> 
> > ```js
> > myPets = await Pets.find({ owner: {id: 123} })
> > ```

@mustafahafidi Do you know where this is documented, can't find it in find options docs :cry:

**Comment by mustafahafidi** [comment]
@jakobrosenberg  [here](https://github.com/typeorm/typeorm/blob/master/docs/find-options.md) it's somehow mentioned (very little tho)

**Comment by jakobrosenberg** [comment]
@brinzi Sorry about the very slow reply.

Here's approximately what I'm using
```typescript
  //existing code
  @ManyToOne(type => owner, owner => owner.pets, {
    nullable: false,
    onDelete: 'CASCADE',
  })

  //the fix
  @Column('integer')
  owner_id: number;
  @RelationId((ent: pet) => ent.owner)
  ownerId: number
```

As I recall, owner_id is used for creating a new entity and ownerId is for querying. I could easily be wrong though.

**Comment by omidh28** [comment]
What if it is an array of authors rather than just one author?
