### ISSUE TITLE
timestamp type column doesn't work when using sqlite

### ISSUE THREAD

**Issue by bejewel-kyoungmin** [typeorm/typeorm#10140]
### Issue description

timestamp type column doesn't work when using sqlite

### Expected Behavior

``` 
@Entity()
export class Photo {
    @PrimaryGeneratedColumn({
        type: 'int',
    })
    id: number

    @Column('varchar')
    name: string;

    @Column('timestamp')
    publishedAt: Date
}
```
both mysql-family and sqlite, entity works correctly.

### Actual Behavior

DataTypeNotSupportedError: Data type "timestamp" in "table.column" is not supported by "sqlite" database.

### Steps to reproduce

``` 
@Entity()
export class Photo {
    @PrimaryGeneratedColumn({
        type: 'int',
    })
    id: number

    @Column('varchar')
    name: string;

    @Column('timestamp')
    publishedAt: Date
}
```
just use column decorator using timestamp type.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | mac         |
| Node.js version     | 16.x  |
| Typescript version  | 5.x  |
| TypeORM version     | 0.3.4  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [X] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by nmsohn** [comment]
I am experiencing the same issue here. I tried with sqlite, sqlite3 and better-sqlite3

**Comment by MartyOfMCA** [comment]
@nmsohn @murilobd I'm using better-sqlite3 and I figured writing a `ValueTransformer` could be useful
