### ISSUE TITLE
postgres timestamp: storing null causes an error

### ISSUE THREAD

**Issue by icepeng** [typeorm/typeorm#1015]
UPDATE "xxx" SET "time"=$1 -- PARAMETERS: [null]
error:  { error: invalid input syntax for type timestamp: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN"

time column is defined as:
```
@Column('timestamp', { nullable: true })
time: string | null;
```

**Comment by icepeng** [comment]
Just my mistake, sorry.

**Comment by michalhorcic** [comment]
Can you please describe what was the mistake? It seems I did exactly the same mistake right now.

**Comment by NikolayKantur** [comment]
I hope I also do not forget to write a solution to the problem here when I find it.
T______T

**Comment by wesleymonaro** [comment]
This error happens when you declare a @Column as a "Date" field, and the migration/DB expect a varchar.

**Comment by MartinMtandi** [comment]
So what is the solution? I keep seeing why the issue occured, but nothing about how to resolve it.

**Comment by HwangTaehyun** [comment]
It happens when using `undefined` or `empty string` variable instead of Date type in an SQL query. In my case, some env variable is undefined and SQL query that uses env throws `invalid input syntax` error occurred.
