### ISSUE TITLE
How to I omit certain columns in a relation?

### ISSUE THREAD

**Issue by juanjalvarez** [typeorm/typeorm#1016]
So I have a `Restaurant` entity that has a relation to `User` that represents it's owner, I'm currently trying to find a restaurant and including the owner information but I can't find out how omit certain fields in relations, in this case a password field.

```
const [findErr, restaurant] = await to(Restaurant.find({
       relations: ['logo', 'owner'],
       skip: page * limit,
       take: limit
   }));
```

**Comment by pleerock** [comment]
The easiest you can do is to use `select: false` option in column of your password:

```ts
@Column({ select: false })
password: string
```

Other options are involving using of QueryBuilder.

**Comment by mkamranhamid** [comment]
> The easiest you can do is to use `select: false` option in column of your password:
> 
> ```ts
> @Column({ select: false })
> password: string
> ```
> 
> Other options are involving using of QueryBuilder.

how do you login with 
 ```ts
@Column({ select: false })   
password: string
```
how do you compare hash ?

**Comment by faddi** [comment]
@mkamranhamid You can select the columns you need with the FindOneOptions select property which overrides `@Column({ select: false })`:

`const user = await userRepository.findOne({ where: { email }, select: ['id', 'password'] });`

**Comment by sebamomann** [comment]
How does this work with relations? `select: false` does not apply on a OneToMany relation

**Comment by martinsotirov** [comment]
> @mkamranhamid You can select the columns you need with the select property which overrides `@Column({ select: false })`:
> 
> `const user = await userRepository.findOne({ where: { email }, select: ['id', 'password'] });`

@faddi how does this help in a relation? This way you have to fire a separate query for the related entity.
