### ISSUE TITLE
Multi-tenancy support with different schema in single database

### ISSUE THREAD

**Issue by Abdallah-khalil** [typeorm/typeorm#1019]
Hello there , i'am in a situation where i need to create a sql server database with same tables but different table schema or tenant like schema1.table1 ,  schema2.table1  
 --- any ideas or thoughts of  doing so with typeORM 
a use case i have in mind is that i will create different entity for each table and when a user logged in i will see which tenant he belongs too and pass that down to the service ( Component ) and then  upon that tenant i will choose which entity he should use ... is that possible or any other ideas will be appreciated 
--- found somthing which may describe what i am looking for  
https://github.com/westmark/sequelize-multi-tenant-enhancer

**Comment by pleerock** [comment]
Working with multiple schemas and databases are completely supporting. Take a look on [this example](https://github.com/typeorm/typeorm/tree/master/test/functional/database-schema/custom-table-schema-and-database). Example of defining entity in a different schema:

```ts
@Entity({schema: "guest"})
export class Category {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToOne(type => Post)
    post: Post;

}
```

**Comment by Abdallah-khalil** [comment]
cool so if i have now the same table with different schema how to call each entity for dealing with in a repository 
`
@Entity({schema: "guest"})
export class Category {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToOne(type => Post)
    post: Post;
}

@Entity({schema: "admin"})
export class Category {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToOne(type => Post)
    post: Post;
}

import { Connection, Repository } from 'typeorm';
import { Category} from './category.entity';

export const CategoryProviders = [
    {
        provide:'RepoToken',
        useFactory:(connection:Connection) => connection.getRepository(Category), 
/*  how to distinguish between them */
        inject:['DbConToken']
    }
];
`

**Comment by pleerock** [comment]
PLEASE FORMAT YOUR CODE PROPERLY BEFORE POSTING.

What is your question? What do you mean by "distinguish between them"? Who are they?

**Comment by Abdallah-khalil** [comment]
Sorry for the bad format my first time to post an issue on github :) 
the last block of code is using nestjs to create a repository for the category entity so what i mean by distinguish between them is how to create one for each entity

**Comment by pleerock** [comment]
Create one what? Sorry I don't know nestjs

**Comment by Abdallah-khalil** [comment]
it is not about nestjs .. i mean i just wondering how to create a repository for each entity given that the two entites has the same name but different schema ..  
another way to ask the question how to do the crud operation against the two entites with the same name but different schema ?

**Comment by pleerock** [comment]
ah, okay, so try to do this:

```ts
import { Category as GuestCategory } from './category.guest.entity';
import { Category as AdminCategory } from './category.admin.entity';

const guestCategoryRepository = connection.getRepository(GuestCategory);
const adminCategoryRepository = connection.getRepository(AdminCategory);
```

But I really suggest you to rename your two entities, like `GuestCategory` and `AdminCategory`. You can specify them a common table name: `@Entity({ name: "category", schema: "guest" }) export class GuestCategory {}`

**Comment by Abdallah-khalil** [comment]
thanks a lot #pleerock :blush:
I think the seond soltution is the way to go by renaming the entities and specify a table name
