### ISSUE TITLE
persist with cascade false try to save sub relationship 

### ISSUE THREAD

**Issue by apezel** [typeorm/typeorm#102]
Hi,

It seems there's a problem when saving an object A that has one B that has many C : despite the cascades set to false, typeorm tries to cascade on C (but not on properties of B).

Example : 

```javascript
@Table("stat")
class Stat {
  @PrimaryColumn("int", { generated: true }) id: number;
  @ManyToOne(type => User)
  user: User;
};

@Table("user")
class User {
  @PrimaryColumn("int", { generated: true }) id: number;
  @ManyToMany(type => LexRight) @JoinTable({ name: "user_right" }) roles:LexRight[];
}
```

When i do : 

```javascript
  stat.user = myConnectedUser; // <-- loaded from db, with typeorm
  return await conn.getRepository(Model).persist(stat);
```
It fails with : 

```
executing query: START TRANSACTION
executing query: INSERT INTO stat(user) VALUES (?)
executing query: INSERT INTO user_right(userId, lexRightId) VALUES (?,?) -- PARAMETERS: [1,2]
executing query: INSERT INTO user_right(userId, lexRightId) VALUES (?,?) -- PARAMETERS: [1,3]
executing query: INSERT INTO user_right(userId, lexRightId) VALUES (?,?) -- PARAMETERS: [1,4]
query failed: INSERT INTO user_right(userId, lexRightId) VALUES (?,?) -- PARAMETERS: [1,2]
executing query: ROLLBACK
```

because this relations already exist. The problem exist with delete too : it doesn't delete stat.user but deletes every stat.user.roles. This is a blocking issue.

**Comment by pleerock** [comment]
Hi,

Dont use PrimaryColumn/Column decorator in conjunction with relational decorators. If you want to make relation a primary you need to do:

```typescript
@Table("stat")
class Stat {
  @ManyToOne(type => User, { primary: true })
  user: User;
}
```

Regarding to your issue, can you try to reproduce it with `npm i typeorm@next` ? Because I have significantly refactored persistent mechanizm and save by cascades  there

**Comment by apezel** [comment]
Thank. I think you misendurstood my example : the primary column of the stat table is ```id:number```

Ok i'll try with @next but can you confirm first that my skipSchemaSync option will be available in this release ? Because for now i'm using a custom build based on my commit, i need this option for my code to run.

**Comment by pleerock** [comment]
> I think you misendurstood my example : the primary column of the stat table is id:number

yes, sorry because `@PrimaryColumn` and `id: number` was inlined I missed `id`.

>  you confirm first that my skipSchemaSync option will be available in this release  

yes it should be there because I did a merge of master branch before releasing

**Comment by apezel** [comment]
I tried with ```npm i typeorm@next``` but i can't get my project to compile : 

```message: 'Property 'setParameters' does not exist on type 'QueryBuilder<Site>' ```
```message: 'Property 'getResults' does not exist on type 'QueryBuilder<Site>'```

I can't find an equivalent for setParameters or getResults / getSingleResults. Is it normal ?

**Comment by pleerock** [comment]
here is most [notable breaking changes](https://github.com/typeorm/typeorm/blob/persistance-refactoring/CHANGELOG.md#003)

**Comment by apezel** [comment]
Works like a charm with @next, thank you !

**Comment by apezel** [comment]
Still works but there's a problem with the dates returned by @next : ```2016-5-22 20:0:0``` The format differ from the master version and is not parsable as is by moment.js (for example). Is it a bug ?

**Comment by apezel** [comment]
To be more explicit about the Date problem : 

Date attributes are returned as String ```console.log(m.birth instanceof Date, typeof m.birth)``` gives me ```false, 'string'```

m is an instance of model loaded from db and defined with property : 
```javascript
@Column({ nullable: true })
birth: Date;
```

Maybe a problem with the mysql driver ?

**Comment by apezel** [comment]
Closed. Resolved by #104

**Comment by pleerock** [comment]
fixed

**Comment by pleerock** [comment]
released in `@next`
