### ISSUE TITLE
Version 0.3.17 is missing in the changelog

### ISSUE THREAD

**Issue by zWaR** [typeorm/typeorm#10201]
### What was unclear or otherwise insufficient?

Typically CHANGELOG.md includes documented changes per released version and is accessible in this two places:

* https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md
* https://typeorm.io/changelog

However, the changes for version 0.3.17 are missing.

### Recommended Fix

Adding release notes published here: https://github.com/typeorm/typeorm/releases/tag/0.3.17 to CHANGELOG.md.

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
thanks for the report, I pushed the changes.
