### ISSUE TITLE
Nested transactions (transactionDepth > 1) can attempt to create and release multiple `SAVEPOINT`s with the same name

### ISSUE THREAD

**Issue by gmahomarf** [typeorm/typeorm#10209]
### Issue description

Nested transactions (transactionDepth > 1) can attempt to create and release multiple `SAVEPOINT`s with the same name

### Expected Behavior

When running nested transactions, each transaction should successfully start and end without issues

### Actual Behavior

When running nested transactions, the `transactionDepth` counter is incremented/decremented incorrectly, leading to `SAVEPOINT`s with the same name. This eventually throws an exception when trying to release a `SAVEPOINT` that was released by another transaction.

### Steps to reproduce
The test at `test/github-issues/10209/issue-10209.ts` in #10210, when run without the patches to the multiple `QueryRunner`s, should reproduce the issue successfully

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| macOS    |  13.4.1   |
| Node.js version     | 18.16.0  |
| Typescript version  | 5.1.6  |
| TypeORM version     | 0.3.17 |

### Relevant Database Driver(s)

- [X] aurora-mysql
- [X] aurora-postgres
- [ ] better-sqlite3
- [X] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [X] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [X] sqlite-abstract
- [ ] sqljs
- [X] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by alumni** [comment]
@gmahomarf Could you explain what was the issue here?

The test in PR #10210 does not look like a valid use case of transactions (I'm talking about SQL in general, not just TypeORM). You cannot run transactions in parallel in the same connection.

**Comment by gmahomarf** [comment]
Not sure what I can say that wasn't already explained in the PR. I don't even remember what the original issue was.
