### ISSUE TITLE
I can't connect to an oracle database with typeorm

### ISSUE THREAD

**Issue by glauber000** [typeorm/typeorm#10204]
### Issue description

Connection with the oracle database generating the error: Error: NJS-116: password verifier type 0x939 is not supported by node-oracledb in Thin mode

### Expected Behavior

Connect with the oracle database, to execute the queries successfully.

### Actual Behavior

When trying to connect with the oracle database, I get the following error message:

**Error: NJS-116: password verifier type 0x939 is not supported by node-oracledb in Thin mode**

I tested with different versions of typeorm but the error remains, I changed the password to one with only letters and the same problem occurs.
I tried to make a connection in THICK mode and the problem also occurs, I apologize if I am opening a topic in error here, in case the problem comes from the database.
However, I already got in touch with my infra team and I was informed that everything was correct with the database configuration, I can connect to this base in other ways, such as via sqltools, but with the typeorm I always get the aforementioned error.

Below is my typeorm configuration:

```
export const connectionSource = new DataSource({
   type: 'oracle',
   synchronize: false,
   host: process.env.HOST_ORACLE_MVCROSS_DATABASE,
   port: Number(process.env.PORT_ORACLE_MVCROSS_DATABASE),
   username: process.env.USER_ORACLE_MVCROSS_DATABASE,
   password: String(process.env.PASSWORD_ORACLE_MVCROSS_DATABASE),
   serviceName: process.env.ORACLE_MVCROSS_DATABASE_SERVICE_NAME,
   logging: true,
   migrations: [],
   subscribers: [],
});
```
The way I try to start the connection is by executing the createConnection method shown in the class below:

```
import { injectable } from 'inversify';
import { Repository, EntityTarget, DataSource } from 'typeorm';

import { connectionSource } from './ormconfig';
import { IConnection } from 'src/infra/database/oracle/interfaces/IConnection.interface';

@injectable()
export class OracleDatabase implements IConnection {
   public getConnection(): DataSource {
     return connectionSource;
   }

   public async createConnection(): Promise<DataSource> {
     return connectionSource.initialize();
   }

   public async closeConnection(): Promise<void> {
     return connectionSource.destroy();
   }

   public getRepository(entity: EntityTarget<any>): Repository<any> {
     return connectionSource.getRepository(entity);
   }
}
```

### Steps to reproduce

As shown earlier, I try to start the connection to the database by calling the createConnection() function in my index file, as follows:

```
import { inject, injectable, LazyServiceIdentifer } from 'inversify';

import { HttpServer } from 'src/presentations/HttpServer';
import { OracleDatabase } from 'src/infra/database/oracle/Connection';

@injectable()
export class Bootstrap {
   constructor(
     @inject(OracleDatabase)
     private readonly oracleDatabase: OracleDatabase,
     @inject(new LazyServiceIdentifer(() => HttpServer))
     private readonly httpServer: HttpServer,
   ) {}

   public async start(): Promise<void> {
     await this.oracleDatabase.createConnection();

     await this.httpServer.start();
   }
}
```

After that I get the above mentioned error

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Linux    |          |
| Node.js version     | lts-alpine  |
| Typescript version  | ^4.9.4  |
| TypeORM version     | ^0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by ertl** [comment]
@glauber000 May I ask how you connected with the thin mode? As far as I know, it's only available under the oracledb driver version 6, and it's currently not defined in the peer dependencies. Did you override the peer dependency version here? Does everything work as usual with version 6?

**Comment by ertl** [comment]
It appears that the tests were failing with version 6.
