### ISSUE TITLE
Integrate dmdb driver

### ISSUE THREAD

**Issue by qianfeiqianlan** [typeorm/typeorm#10208]
### Feature Description

1. dmdb is a "localization" database in China, is greatly benefit developers in China
2. for java support dmdb at https://central.sonatype.com/artifact/com.dameng/DmJdbcDriver18/8.1.2.192
3. for nodejs driver at https://www.npmjs.com/package/dmdb

### The Solution

1. Create a dedicated driver for dmdb, providing the necessary functionality to establish connections and execute queries specific to dmdb's SQL dialect.
2. Implement schema generation and migration capabilities tailored to dmdb's schema management system.
3. Incorporate appropriate unit tests to ensure the reliability and compatibility of the integration.
4. Update the TypeORM documentation to include guidance and examples for working with dmdb

### Considered Alternatives

dmdb support MySQL mode，but I don't know if it can be used directly, have a try

### Additional Context

If it is possible to add the dmdb in feature roadmap, I have some experience to try.

I customized a typeorm (two years ago version) to adapt to dmdb in our product.

If have any ideas, please let me know

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by NextThread** [comment]
hi, can I work on this

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
