### ISSUE TITLE
TypeORM doesn't work after "n" requests

### ISSUE THREAD

**Issue by iamaliybi** [typeorm/typeorm#10239]
### Expected Behavior

It should work after "n" times.

### Actual Behavior

It doesn't work after "n" times.

### Steps to reproduce

Please watch this video:

https://github.com/typeorm/typeorm/assets/31594561/958962df-9dd1-46bc-bf52-5c130b26ef6e

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Widnows 11 |
| Node.js version     | 18.17.0  |
| Typescript version  | 5.1.3  |
| TypeORM version     | 0.3.17  |

### Additional Context

**Start script**
`nodemon --watch`

**index.tsx**
```javascript
import app from './app';
import '@env';
import { Category, Customer, Inventory, InventoryLocation, Item, Location, Organization, Stock, Supplier, Order, User, LoginHistory, ForgetPassword } from '@src/entity';
import { DataSource } from 'typeorm';

// Check .env
if (!process.env.DB_DATABASE) console.log('\x1b[31m%s\x1b[0m', 'Couldn\'t find environments variables.\n');

export const AppDataSource = new DataSource({
	name: 'default',
	type: 'mysql',
	host: process.env.DB_HOST,
	port: Number(process.env.DB_PORT),
	username: process.env.DB_USERNAME,
	password: process.env.DB_PASSWORD,
	database: process.env.DB_DATABASE,
	synchronize: false,
	charset: 'utf8mb4_unicode_ci',
	connectTimeout: 10000,
	logging: false,
	subscribers: [],
	entities: [
		User,
		ForgetPassword,
		Order,
		Category,
		Customer,
		Inventory,
		LoginHistory,
		Item,
		Location,
		Organization,
		Stock,
		InventoryLocation,
		Supplier
	]
});

AppDataSource
	.initialize()
	.then(() => {
		console.log('\x1b[32m%s\x1b[0m', 'Connected to database successfully!');
	})
	.catch((err) => {
		console.log('\x1b[31m%s\x1b[0m', err.message);
	});

// Start application
const appUrl = new URL(process.env.APP_URL ?? '');
const PORT = Number(appUrl.port || 5000);
app.listen(PORT, () => {
	console.clear();
	console.log('\x1b[32m%s\x1b[0m', `\nServer running at ${appUrl.href}`);
});
```

**app.tsx**
```javascript
import cors from 'cors';
import express from 'express';
import {
	authRouter,
	userRouter,
	stockRouter,
	categoryRouter,
	customerRouter,
	locationRouter,
	orderRouter,
	supplierRouter,
	reportRouter,
	sellRouter,
	organizationRouter
} from './routes';
import ServerResponse from './classes/ServerResponse';

const app = express();

// Global middleware
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(`${__dirname}/public`));
app.use(cors());

// Routes
app.use('...', authRouter);

app.use((req, res, next) => {
	res.status(404).send(ServerResponse.error('ERR_NOT_FOUND'));
	return;
});

export default app;
```

**authMiddleware**
```javascript
const authMiddleware = async (req: Request, res: Response, next: NextFunction) => {
	try {
		// Bearer xxxxxx
		const authorizationHeader = req.headers['authorization'];
		if (!authorizationHeader) throw new Error('');

		const [bearer, token] = authorizationHeader.split(' ');
		if (bearer !== 'Bearer' || typeof token !== 'string') throw new Error('');

		const decoded = await JWT.verify(
			token,
			process.env.SECRET_TOKEN,
			{
				algorithms: ['HS512']
			}
		);

		const user_id = ((typeof decoded === 'string')
			? JSON.parse(decoded).id
			: decoded.id);

		if (process.env.APP_DEBUG) console.log('[Finding]');

		const user = await User.findOne({
			where: {
				id: user_id,
			},
			select: [
				'id',
				'organization_id',
				'role_id',
				'first_name',
				'last_name',
				'address',
				'phone',
				'email',
			],
		});

		if (process.env.APP_DEBUG) console.log('[Found!]');

		req.body.user = user;

		next();
	} catch (e) {
		res.status(401).send(ServerResponse.error('You do not have permission.'));
		return;
	}
};
```

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

**Comment by mnguyen081002** [comment]
can you add more information about typeorm logging?

**Comment by iamaliybi** [comment]
It doesn't create a log.

Uploading bandicam 2023-07-30 00-32-50-525.mp4…

**Comment by iamaliybi** [comment]
It doesn't create a log.

https://github.com/typeorm/typeorm/assets/31594561/8375158b-5212-4793-9913-46259f9a1ed7

**Comment by sceccotti89** [comment]
@iamaliybi Just set the `logging` attribute to `true` in the database DataSource configuration.

**Comment by iamaliybi** [comment]
> @iamaliybi Just set the `logging` attribute to `true` in the database DataSource configuration.

I did it 🤔 See the last video again. My problem was fixed.
I add `poolSize: 100`

But I'm sure that typeORM has some bugs in handling database connections. like open and close

**Comment by taotto** [comment]
same here!
<img width="516" alt="image" src="https://github.com/typeorm/typeorm/assets/132739444/16974582-bc89-401f-a51d-2f5b832f728e">


work again!

**Comment by taotto** [comment]
how ever， isn't a bug here? typeorm will deny all db query even just select query.

**Comment by taotto** [comment]
It seems just the `mysql2` connectionLimit:

If the "connectionLimit" in MySQL is set too low, it may cause the following problems:

New connections cannot be established: If the "connectionLimit" is lower than "max_connections", new connection requests will be rejected when the connection pool reaches the "connectionLimit", and new connections cannot be established, which may cause application connection errors or inability to function properly.
The peak number of connections exceeds "max_connections": If the application establishes more connections than the "connectionLimit" at a certain time, the exceeding connections will not be able to provide effective service, which may cause abnormal or unpredictable behavior in the application.
Impact on database performance: If the number of connections exceeds "max_connections", the database may not efficiently handle all connections, resulting in performance degradation, slower response times, and even database crashes.
To avoid these problems, it is recommended to set the "connectionLimit" appropriately based on the needs of the application and the performance of the database to ensure that the number of connections in the connection pool does not exceed "max_connections".

**Comment by iamaliybi** [comment]
Thank you!
