### ISSUE TITLE
Batch insert for relations `@ManyToMany` or `@OneToMany`?

### ISSUE THREAD

**Issue by leandrogehlen** [typeorm/typeorm#1025]
Is it possible to create batch insert for relations `@ManyToMany` or `@OneToMany`?
If no, is it possible add this feature?

**Comment by pleerock** [comment]
Yes, its possible using [relational query builder functionality](http://typeorm.io/#/relational-query-builder).

**Comment by leandrogehlen** [comment]
I understood, but by default like: 

```typescript
post.categories.push(categ1);
post.categories.push(categ2);
post.categories.push(categ3);

getRepository(Post).save(post);
```

**Comment by pleerock** [comment]
Right now its already adds all categories into post, by creating multiple insert queries. What is your request? Do you want to merge everything it does right now into single insert query?

**Comment by leandrogehlen** [comment]
Yes! exacly!

```typescript
post.categories.push(categ1);
post.categories.push(categ2);
post.categories.push(categ3);

getRepository(Post).save(post); //this will generate:
//insert into post_category (postId, categoryId) values (?,?),(?,?),(?,?)

```

**Comment by pleerock** [comment]
Persistence mechanizm is very complex and won't touch it right now. Maybe in the future we will implement this small improvement, but definitely not now, since its not in a priority.

**Comment by leandrogehlen** [comment]
Ok, thanks! The framework is excellent, this is just a small enhancement

**Comment by pleerock** [comment]
Okay I implemented it in the first alpha version of 0.2.0. Now following code:

```ts

        const category1 = new Category();
        category1.name = "cat#1";

        const category2 = new Category();
        category2.name = "cat#2";

        const post = new Post();
        post.title = "about post";
        post.categories = [category1, category2];

        await connection.manager.save(post);
```

produces following queries:

```sql
START TRANSACTION
INSERT INTO `post`(`title`) VALUES (?) -- PARAMETERS: ["about post"]
INSERT INTO `category`(`name`) VALUES (?) -- PARAMETERS: ["cat#1"]
INSERT INTO `category`(`name`) VALUES (?) -- PARAMETERS: ["cat#2"]
INSERT INTO `post_categories_category`(`postId`, `categoryId`) VALUES (?, ?), (?, ?) -- PARAMETERS: [1,1,1,2]
COMMIT
```

On platforms which support returning/output statements like postgres and sql server even non-junction insertions are grouped now:

```sql
START TRANSACTION
INSERT INTO "post"("title") VALUES ($1) RETURNING "id" -- PARAMETERS: ["about post"]
INSERT INTO "category"("name") VALUES ($1), ($2) RETURNING "id" -- PARAMETERS: ["cat#1","cat#2"]
INSERT INTO "post_categories_category"("postId", "categoryId") VALUES ($1, $2), ($3, $4) -- PARAMETERS: [1,1,1,2]
COMMIT
```

You can install it via `npm i typeorm@next`

**Comment by leandrogehlen** [comment]
Excellent solution, thanks

**Comment by kenberkeley** [comment]
Same with v0.2.24

**Comment by sapabg** [comment]
Not inserting the relation at all for me!

const saleMeta = new SaleMeta();
saleMeta.patient_id = this.sale.sale_meta.patient_id;

const sale = new Sale();
sale.sale_meta = saleMeta;

this.connection 
            .manager
            .save(sale);
            
The result is just one query for sales, no query for sale_meta
In saes.entity I have:
@OneToOne(type => SaleMeta, sale_meta => sale_meta.sale)
sale_meta: SaleMeta;

and in SaleMeta:
@OneToOne(type => Sale, sale => sale.sale_meta)
@JoinColumn({ name: "sale_id" })
sale: Sale;

@Column()
sale_id: number;

"@nestjs/typeorm": "^7.1.5"
