### ISSUE TITLE
Connection is not established with MySQL database

### ISSUE THREAD

**Issue by nmquaan** [typeorm/typeorm#10262]
### Issue description

"TypeORMError: Connection is not established with mysql database

### Expected Behavior

App can connect to MySQL database.

### Actual Behavior

I’m facing an error when querying data to MySQL with TypeORM.

`{
    "level": "error",
    "message": "Connection is not established with MySQL database Connection is not established with mysql database",
    "stack": "TypeORMError: Connection is not established with mysql database\n    at /app/node_modules/typeorm/driver/mysql/MysqlDriver.js:710:22\n    at new Promise (<anonymous>)\n    at MysqlDriver.obtainMasterConnection (/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:696:16)\n    at MysqlQueryRunner.connect (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:59:18)\n    at /app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:145:55\n    at new Promise (<anonymous>)\n    at MysqlQueryRunner.query (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:143:16)\n    at SelectQueryBuilder.loadRawResults (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2028:43)\n    at SelectQueryBuilder.executeEntitiesAndRawResults (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1888:37)\n    at SelectQueryBuilder.getManyAndCount (/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:764:47)\n    at GetMemberListHandler.execute (/app/main.js:64818:78)\n    at QueryBus.<anonymous> (/app/node_modules/@nestjs/cqrs/dist/query-bus.js:51:42)\n    at Generator.next (<anonymous>)\n    at /app/node_modules/@nestjs/cqrs/dist/query-bus.js:17:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/@nestjs/cqrs/dist/query-bus.js:13:12)"
}`

### Steps to reproduce

- The issue sometimes occurred when querying data. Currently, I don't know the reason.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  AWS K8S         |
| Node.js version     | v18.15.0 |
| Typescript version  | 4.2.3  |
| TypeORM version     |0.3.7|
| mysql2 version     |2.3.3|
|@nestjs/typeorm    |8.1.4|

### Additional Context

- When the Application is starting, connection to database MYSQL is connected but sometimes the app gets the error as above.

```ts
import { registerAs } from '@nestjs/config';

export default registerAs('db', () => ({
  type: process.env.ORM_CONNECTION,
  host: process.env.ORM_HOST,
  port:process.env.ORM_PORT,
  username: process.env.ORM_USERNAME,
  password: process.env.ORM_PASSWORD,
  database: process.env.ORM_DB,
  timezone: 'Z',
  logging: process.env.ORM_LOGGING === 'true'? true : ['error'],
  autoLoadEntities: true,
  keepConnectionAlive: true,
  entities: [`${__dirname}/**/*.entity{.ts,.js}`],
  extra: {
    connectionLimit: parseInt(process.env.ORM_CONNECTION_LIMIT || '50', 10),
  },
}));

```

I checked the error throw at this method.
```ts
    obtainMasterConnection(): Promise<any> {
        return new Promise<any>((ok, fail) => {
            if (this.poolCluster) {
                this.poolCluster.getConnection(
                    "MASTER",
                    (err: any, dbConnection: any) => {
                        err
                            ? fail(err)
                            : ok(this.prepareDbConnection(dbConnection))
                    },
                )
            } else if (this.pool) {
                this.pool.getConnection((err: any, dbConnection: any) => {
                    err ? fail(err) : ok(this.prepareDbConnection(dbConnection))
                })
            } else {
                fail(
                    new TypeORMError(
                        `Connection is not established with mysql database`,
                    ),
                )
            }
        })
    }
```

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by nguyenminhtiend** [comment]
I faced the same issue. Really appreciate any feedback or advice on this

**Comment by 10Bude10** [comment]
I faced the same error:
```
TypeORMError2: Connection is not established with mysql database
    at new Promise
    at MysqlDriver.obtainMasterConnection
    at MysqlQueryRunner.connect
    at new Promise
    at MysqlQueryRunner.query
    at SelectQueryBuilder2.loadRawResults
    at SelectQueryBuilder2.executeEntitiesAndRawResults
    at SelectQueryBuilder2.getRawAndEntities
```

Environment:
Dependency | Version
-- | --
Operating System | Mac OS 13.5.2
Node.js version | v18.18.0
Typescript version | 5.1.3
TypeORM version | 0.3.17
mysql2 version | 2.3.3
