### ISSUE TITLE
How to use pessimistic locking in sqlite3?

### ISSUE THREAD

**Issue by Deilan** [typeorm/typeorm#1026]
How to use pessimistic locking in sqlite3?

**Comment by pleerock** [comment]
You can find locking usage examples [here](https://github.com/pleerock/typeorm/blob/f919ded6733efee00c71bfe4e558c61aba3c5c07/test/functional/query-builder/locking/query-builder-locking.ts#L31).

**Comment by Deilan** [comment]
@pleerock Thanks! As it seems it doesn't apply to sqlite3:
```ts
        if (connection.driver instanceof SqliteDriver || connection.driver instanceof OracleDriver)
            return;
```

**Comment by pleerock** [comment]
Then it means sqlite does not support locking. You probably don't need locking with sqlite at all since only one client can  write into sqlite file in one time
