### ISSUE TITLE
Property isModified function?

### ISSUE THREAD

**Issue by Christilut** [typeorm/typeorm#1028]
Mongoose has the `isModified` function to see if a property has been modified. This is really helpful in a pre-save hook (or for typeorm, when extending save()) to make sure a password always gets hashed. 

Is there something like that for typeorm? I couldn't find it in the docs.

**Comment by pleerock** [comment]
typeorm follows a bit different strategy and does not store object loaded from the database in the model. So if you want to check if its modified or not by explicitly load an object from the database

**Comment by Christilut** [comment]
I guess the mongoose way is not the typescript way (I'm still adjusting).

I made the password property private and changing the password must go through the setPassword function. 👍

**Comment by pleerock** [comment]
Don't forget you can use accessors, e.g. `get password`, `set password`

**Comment by Christilut** [comment]
Thanks, great point.

**Comment by upendra-web** [comment]
Hello @Christilut, Can you post an example of your implementation?
Thank you!

**Comment by Christilut** [comment]
Sorry, this was a long time ago. I'm on Typegoose now.
