### ISSUE TITLE
Reduce node_modules package size for AWS Lambda deployments

### ISSUE THREAD

**Issue by julienmunio** [typeorm/typeorm#10283]
### Feature Description

I'm facing build issues on my serverless cloud stack due to the weight of the TypeORM dependency package. This is because TypeORM depends on the date-fns library, which is quite large. This feature proposal outlines a plan to reduce the size of the TypeORM dependency package by switching to the dayjs library, which is much smaller. This will make it easier to add other dependencies to my project and reduce the risk of build failures.

### The Solution

The solution to this problem is to switch to the dayjs library. Dayjs is a lightweight alternative to date-fns that is much smaller in size. To switch to dayjs, we will need to update a single method DateUtils.mixedDateToDate()

### Considered Alternatives

As mentioned in the code comments, an alternative solution is not to use an external lib. But this generates additional code that is not useful to maintain.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by NextThread** [comment]
@julienmunio , hey are you working on this?

**Comment by julienmunio** [comment]
This PR is a suggestion to switch from Date-fns to DayJs. As remember this lib is used in a single method.

**Comment by htakemoto** [comment]
It is true that date-fns file size is roughly 24M which is so huge. I also use NestJS + TypeORM in Lambda and everything worked fine up to NestJS v8, but I currently face Lambda layer size issue with NestJS v10. One big culprit is date-fns being depended by typeorm. Please remove/replace date-fns library.
