### ISSUE TITLE
cockroachdb: ENUM type not supported 

### ISSUE THREAD

**Issue by Xiang-Gu** [typeorm/typeorm#10287]
### Issue description

Cockroachdb has previously requested typeorm to support its ENUM data type (https://github.com/typeorm/typeorm/issues/8039). It was claimed to be implemented in this PR (https://github.com/typeorm/typeorm/pull/9128). However, we observe that it's not working and it throws DataTypeNotSupportedError.

### Expected Behavior

I expect to not see such a dataTypeNotSupported error.

### Actual Behavior

I checked out our `cockroachdb-example` repo and attempted to add a ENUM type column to table `Catagory`:
```
➜  cockroachdb-example git:(master) ✗ less src/entity/Category.ts
import {Column, PrimaryGeneratedColumn, Entity} from "typeorm";

export enum Typ {
  TYPEA = 'type_a',
  TYPEB = 'type_b',
}

@Entity()
export class Category {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column({ type: 'enum', enum: Typ })
    purpose: Typ;

}
```
I also started a cockroachdb cluster locally, and then I run `npm start`
```
➜  cockroachdb-example git:(master) ✗ npm start

> typeorm-cockroachdb-example@0.0.1 start
> tsc && node dist/index.js

Error:  DataTypeNotSupportedError: Data type "enum" in "Category.purpose" is not supported by "cockroachdb" database.
    at new DataTypeNotSupportedError (/Users/xiangu/Desktop/cockroachdb-example/node_modules/typeorm/error/DataTypeNotSupportedError.js:7:28)
    at /Users/xiangu/Desktop/cockroachdb-example/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:74:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/Users/xiangu/Desktop/cockroachdb-example/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:71:36)
    at /Users/xiangu/Desktop/cockroachdb-example/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:42:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/Users/xiangu/Desktop/cockroachdb-example/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:42:25)
    at Connection.buildMetadatas (/Users/xiangu/Desktop/cockroachdb-example/node_modules/typeorm/connection/Connection.js:521:33)
    at Connection.<anonymous> (/Users/xiangu/Desktop/cockroachdb-example/node_modules/typeorm/connection/Connection.js:127:30)
    at step (/Users/xiangu/Desktop/cockroachdb-example/node_modules/tslib/tslib.js:141:27)
```

### Steps to reproduce

listed in "Actual Behavior" section already

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | MacOS 13.5 |
| Node.js version     | v20.5.1  |
| Typescript version  | Version 5.1.6 |
| TypeORM version     | 0.3.17 |

### Additional Context

This error is easily reproducible. I tried to look at some typeORM code and at least it seems the error is thrown out from [here](https://github.com/typeorm/typeorm/blob/master/src/metadata-builder/EntityMetadataValidator.ts#L129C59-L140). It did seem like a typeORM bug.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [X] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Xiang-Gu** [comment]
cc @simplenotezy

**Comment by AlexMesser** [comment]
I tested your example and it is working as expected

```ts
const category1 = new Category();
category1.name = "TypeScript";
category1.purpose = Typ.TYPEA;
await connection.manager.save(category1);

const category2 = new Category();
category2.name = "Programming";
category2.purpose = Typ.TYPEB;
await connection.manager.save(category2);
```

```
[
  Category { id: 1, name: 'TypeScript', purpose: 'type_a' },
  Category { id: 2, name: 'Programming', purpose: 'type_b' }
]
```

Please make sure you are using the latest TypeORM version - `0.3.17`.

If the issue persists please create a reproduction repository.

**Comment by Xiang-Gu** [comment]
Thanks! If I follow the [quick start](https://github.com/typeorm/typeorm#quick-start) from the typeorm repo then I am able to use ENUM type too.

If possible, it would be great if you can update the cockroachdb-example [repo](https://github.com/typeorm/cockroachdb-example), which is a few years old.

**Comment by pleerock** [comment]
Sure @Xiang-Gu we'll update the repo.
