### ISSUE TITLE
Parse Error on Update Query

### ISSUE THREAD

**Issue by AmaVic** [typeorm/typeorm#103]
Hello everybody,
I'm here because I have an issue using TypeORM (which I really like by the way). I am trying to make an update query as shown in the examples with the pictures, but id doesn't work. I get a parse error when trying to execute the query.

Here is my code:
**Notification Model**
```typescript
@Table()
export class Notification {
    @PrimaryGeneratedColumn()
    id: number
    @ManyToOne(type => User, user => user.notifications)
    user: User
    @Column()
    date: Date
    @Column()
    read: boolean
    @Column()
    data: string
}
```
**Update Query**
```typescript
try {
    let notif = await DBInstance
        .getConnection()
        .getRepository(Notification)
        .findOneById(req.params.id)
        
    notif.read = true
         
    await DBInstance
        .getConnection()
        .getRepository(Notification)
        .persist(notif)
} catch(error) {
    console.log(error)
}
```

When the update is asked for the Notification which has '1' as id, I get the following error:

Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'read=1  WHERE id=1' at line 1

The id exists and the notification to update is well retrieved.

Any idea what could be the problem or how to solve this ?
Thanks in advance for your help!

**Comment by pleerock** [comment]
try to repduce your issue without any extra code, as simpler as possible. What is `DBInstance`?  Are you sure it always returns you a single connection? check your connection in terms of a single connection? Also error you specified isnt complete, please provide more information.

**Comment by pleerock** [comment]
feel free to reopen it if you still have something to add here
