### ISSUE TITLE
many-to-many schema

### ISSUE THREAD

**Issue by mkzaker** [typeorm/typeorm#1030]
how i can set schema for many-to-many relation?

**Comment by pleerock** [comment]
There are lot of definitions of `schema` word in ORM. What exactly do you call schema? Are you talking about having entity schema inside json files?

**Comment by mkzaker** [comment]
i talking about postgresql schema.

@Entity({schema: 'security'})
export class User {
    @PrimaryGeneratedColumn()
    id: number;
    @ManyToMany(type => Role, role => role.users)
    @JoinTable()
    roles: Role[];
}

@Entity({schema: 'security'})
export class Role {
    @PrimaryGeneratedColumn()
    id: number;
    @ManyToMany(type => User, user => user.roles)
    users: User[];
}

how i can set users_roles table schema?

**Comment by pleerock** [comment]
Oops looks like we missed this functionality. This looks like a major must have feature and will be implemented in `0.1.1` this week.

**Comment by yavarnia** [comment]
This feature is really awesome and necessary. it's can solve my problem.

**Comment by yavarnia** [comment]
This feature is really awesome and necessary.

**Comment by m-yazdani** [comment]
hello everybody, your problem is exactly mine, i also need this feature, please take it into consideration, thanks a lot

**Comment by pleerock** [comment]
Please try it in `0.1.1`. Now many-to-many table accepts its parent entity's schema. But you can define it by yourself as well:

```ts
@ManyToMany(type => User, user => user.roles)
@JoinTable({ schema: "guest" })
users: User[];
```
