### ISSUE TITLE
Question - How to deal with physical relationship in large scale application

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#1031]
Large-scale application of the database I/O performance is very sensitive. So that is usually the case is not to create foreign keys. 

The task of ORM is to map the tables in the database as objects and to maintain the relationships between them.

Usually we are faced with such a problem, is to have a highly object-oriented data structure, or have a high-performance database.

We can manually delete all the foreign keys after the ORM has created the database. So that you can get the advantages of both. But I think this operation may not be very good.

So the question is, in order to make full use of the object-oriented, but also to keep the database write performance, is to manually delete the foreign key or wait for TypeORM later to provide a configuration to create an index instead of creating foreign keys?

**Comment by pleerock** [comment]
?

**Comment by Diluka** [comment]
Sorry. Accidentally pressed to the keyboard. I'll ask a question for instead.

**Comment by pleerock** [comment]
np 😆

**Comment by Diluka** [comment]
updated

**Comment by pleerock** [comment]
When you google "when not to use foreign keys" 95% of answers will give you answer that you should always use foreign keys when they can be used, there are few respectable people who advices same. Some people tell that it adds a very small write overhead, but its not reasonable and pros of using foreign key are much more valuable then not using them. So, Im really doubt about feature you are suggesting

**Comment by Diluka** [comment]
Actually, I often use foreign keys like you. ;)

But I see it is not **95%**, half and half perhaps. Both have pros and cons.

Like Alibaba, they don't use foreign keys. (specified in their development manual)
> 6. [Mandatory] Do not use foreign keys and cascading, all foreign key concepts must be resolved at the application layer. Note: The relationship between students and grades, for example, student table student_id is the primary key, then the student table in the score table is foreign key. If you update the student_id in the student table and trigger the student_id update in the grade table, it is a cascading update. Foreign key and cascade update for stand-alone low concurrent, not suitable for distributed, high concurrent clusters; cascade update is strong blocking, there is the risk of database updates storm; foreign key affect the database insertion speed.

And this https://stackoverflow.com/questions/83147/whats-wrong-with-foreign-keys still no best answer

**Comment by pleerock** [comment]
> But I see it is not 95%, half and half perhaps. Both have pros and cons.

I don't think so.

> Like Alibaba, they don't use foreign keys. (specified in their development manual)

is it public? If yes, then can you provide a link? Also, what are other use cases? Anyone else doing that except Alibaba?

> And this https://stackoverflow.com/questions/83147/whats-wrong-with-foreign-keys still no best answer

but if you read them carefully and analyze answers, you'll there are always pros in using foreign keys, and always cons in not using them, even if they both has its own pros and cons. Also read answers on quora.

**Comment by Diluka** [comment]
It's public but in Chinese only. 
https://yq.aliyun.com/articles/69327 a pdf download link in this article, on page 27

**Comment by pleerock** [comment]
I'll close and postpone it until it gets more attention from users (more people requesting this feature). Until that people can make manual relations.

**Comment by powerfulyang** [comment]
> It's public but in Chinese only.
> https://yq.aliyun.com/articles/69327 a pdf download link in this article, on page 27

How was it finally solved? 
最后这个问题有啥眉目？
