### ISSUE TITLE
Objectivity in description

### ISSUE THREAD

**Issue by Christilut** [typeorm/typeorm#1033]
I really like TypeORM and I'm building a cool boilerplate with it right now.

There's just one tiny tiny thing that bothers me. The word "amazing" in the short description (and typeorm.io title). It comes off as click baity and since it is self described, a bit arrogant.
I would prefer that descriptions and documentation are objective.

I usually ignore anything that is click baity, but TypeORM is actually quite amazing so let users figure that out themselves. Plus I'm pretty sure that programmers are extra sensitive to click bait (negatively) and that is your main audience.

**Comment by pleerock** [comment]
haha yeah its to add to TypeORM a bit of hype 😆  Please make your suggestions about new title

**Comment by Christilut** [comment]
I'd just remove the word "amazing", less is more ;)

**Comment by pleerock** [comment]
Okay, done =)
