### ISSUE TITLE
No content available

### ISSUE THREAD

**Issue by sandesh-bhoir** [typeorm/typeorm#10335]
### What was unclear or otherwise insufficient?

The [documentation](https://typeorm.io) has no content available, only we can see left menu section but on click of it there is a blank page visible.

![image](https://github.com/typeorm/typeorm/assets/78721039/e0e90bec-2d99-49ed-a8db-3c31c89f59d4)

### Recommended Fix

As this is something which can be handled from your en, kindly look into it.

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment]
see #9705
