### ISSUE TITLE
Issues using setter with promises

### ISSUE THREAD

**Issue by nijellab** [typeorm/typeorm#1034]
I am having issues with my setter being ignored when I try to update an entity. From what I understood through testing, I have this issue because I am using promises.

I know you don't recommend using private attributes but I am not in charge of project architecture nor coding convention.

Here is the interesting part of my entity : 

```
/**
     * Circle's user
     *
     * You have to use getter and setter
     */
    @ManyToMany((type) => User, (user) => "circles")
    @JoinTable({name: "circle_users_user" })
    private users: Promise<User[]>;

/**
     * Setter user
     *
     * @param {Promise<User[]>} users
     */
    public setUsers(users: Promise<User[]>): void {
        this.users = users;
    }

    /**
     * Getter user
     *
     * @returns {User[]}
     */
    public getUsers(): Promise<User[]> {
        return this.users;
    }
```

I also added a code abstract of my setter call : 

```
let members: User[] = [];
// Setter is ignored, members are not added in my circle's users array
circle.setUsers(Promise.resolve(members));
```

The way I used to overcome this issue was to directly push the members in my array like this : 

```
for (const id of command.getMembers()) {
        members.push(await this.userDao.findById(id));
        }

```

I want to understand why it doesn't work with my setter and if I have a way to fix it.

Thanks for considering my issue.

**Comment by pleerock** [comment]
what do you think @luchillo17

**Comment by luchillo17** [comment]
This is an interesting one, at first i thought he was trying to get too much out of TypeScript, then i realized what utilities could this have, like custom formatting or maybe validation in the setters, and at that point i got excited with the possibilities.

However i think he's just trying to get around stiff management rules or managers not accepting proposals, may be his opinions aren't being considered or were rejected with justified reasons, that depends on the context.

From the technical side i don't see why it doesn't work, you use the `setUsers` to set the property that supposedly has the `ManyToMany` relations, @nijellab what kind of error you get? does it just don't set or is there any kind of error output when you try?

@pleerock i don't remember right now but is this the right way? should he wrap the relation array in a promise or instead an array of promises that resolve to each relation?

**Comment by nijellab** [comment]
I don't get any error coming from using the setter. However my Array is not empty test fails and send a message warning me my Array is empty, thus my assumption about setter being ignored.

Tell me if you need more code or anything else.

**Comment by pleerock** [comment]
I also don't see why it should not work.. @nijellab would be really great if you create a failing test for the issue you have

**Comment by nijellab** [comment]
I created a test so you can reproduce the issue i get.

```
TypeORM.createConnection({
            ...
        }).then((connection: TypeORM.Connection) => {
            getRepository(Circle).findOneById(id).then((circle) => {
                getRepository(User).findOneById(id).then((user) => {
                   const users: User[] = [];
                   users.push(user);
                   circle.setUsers(Promise.resolve(users));
                   circle.getUsers().then((usersCircle) => console.log(usersCircle));
                   console.log(circle);
                });
            });
       })
```
**Simplified Circle entity** : 
```
@Entity()
export class Circle {

/**
     * Circle's identifier
     */
 @PrimaryGeneratedColumn({type: "bigint"})
    private id: number;

/**
     * Circle's user
     *
     * You have to use getter and setter
     */
 @ManyToMany((type) => User, (user) => "circles")
    @JoinTable({name: "circle_users_user" })
    private users: Promise<User[]>;

/**
     * Getter identifier
     *
     * @returns {number}
     */
    public getId(): number {
        return this.id;
    }

    /**
     * Setter identifier
     *
     * @param id new identifier value
     */
    public setId(id: number): void {
        this.id = id;
    }

/**
     * Setter user
     *
     * @param {Promise<User[]>} users
     */
    public setUsers(users: Promise<User[]>): void {
        this.users = users;
    }
}

    /**
     * Getter user
     *
     * @returns {User[]}
     */
    public getUsers(): Promise<User[]> {
        return this.users;
    }
```
**Simplified User entity** : 
```
@Entity()
export class User {

    /**
     * User's identifier
     */
    @PrimaryGeneratedColumn({type: "bigint"})
    private id: number;

@ManyToMany((type) => Circle, (circle) => "users")
    private circles: Promise<Circle[]>;

 /**
     * Getter identifier
     *
     * @returns {number}
     */
    public getId(): number {
        return this.id;
    }

    /**
     * Setter identifier
     *
     * @param id new identifier value
     */
    public setId(id: number): void {
        this.id = id;
    }
}
```
Tell me if you need more.

**Comment by pleerock** [comment]
By test I meant a PR that adds a failing test into `test` directory of the typeorm repository...

**Comment by nijellab** [comment]
Oh ok, I will work on that this afternoon.

**Comment by nijellab** [comment]
Any thought about the PR @pleerock @luchillo17 ?

**Comment by pleerock** [comment]
Okay so Ive investigated your problem. And to fix your code you need to replace:

```ts
        // Setting users with setter
        circleFromDB!.setUsers(Promise.resolve(users));
        console.log("before assert");
        expect(users).deep.equal(await circleFromDB!.getUsers());
```

with

```ts
        // Setting users with setter
        circleFromDB!.setUsers(Promise.resolve(users));
        await Promise.resolve();
        console.log("before assert");
        expect(users).deep.equal(await circleFromDB!.getUsers());
```

That's how promises work. When you do `Promise.resolve(users)` it not resolving a promise until a next "tick" occurs, so this code is basically the same if you did ` circleFromDB!.setUsers(loadUsersFromDatabase());`. In this case you won't have users loaded from the database instantly too, right? You'll have them only when your database return them. Same with `circleFromDB!.setUsers(Promise.resolve(users));` - it does not give you users instantly. It gives you users once next "async tick" happens. You can make such tick by simply calling `await Promise.resolve();`. Yeah its not looking good, however there is no choice. Lazy relations are very specific due to node.js async nature. If you don't like such specifics then better not to use lazy relations.

Personally I never use lazy relations (even with other ORMs on other platforms) because sometimes they are performance bottlenecks. I prefer to load everything I need in a single request and work with loaded data.

Also I see from the test that you use java-style getters and setters. I can recommend you to remove them. You don't need them in TypeScript. TypeScript has its own getter/setters mechanizm which you can use when you really need (java does not have thats why it uses always-getters/setters pattern just to make a safety net).

**Comment by nijellab** [comment]
Thank you very much for your feedbacks and fix, I'll implement it in the upcoming days.
