### ISSUE TITLE
Timezone conversion

### ISSUE THREAD

**Issue by sergey-shablenko** [typeorm/typeorm#10358]
### Issue description

timestamptz type converts any given timestamp to UTC

### Expected Behavior

should preserve given timezone

### Actual Behavior

converts any timestamp to UTC

### Steps to reproduce

Data
```json
[
  {
    "fromDateTime": "2023-09-15T00:00:00.000+03:00",
    "toDateTime": "2023-09-15T23:59:59.999+03:00"
  },
  {
    "fromDateTime": "2023-09-11T00:00:00.000+03:00",
    "toDateTime": "2023-09-11T23:59:59.999+03:00"
  },
  {
    "fromDateTime": "2023-09-13T00:00:00.000+03:00",
    "toDateTime": "2023-09-13T23:59:59.999+03:00"
  }
]
```

Entity

```typescript
@Entity({
  name: 'someEntity',
})
class SomeEntity {
  @Column({ type: 'timestamptz' })
  fromDateTime: Date;

  @Column({ type: 'timestamptz' })
  toDateTime: Date;
}
```

Code

```typescript
await this.someEntityRepository.manager.transaction(async (t) => {
      await t.save(
        SomeEntity,
        data.map((x) => ({
          fromDateTime: x.fromDateTime,
          toDateTime: x.toDateTime,
        }))
      );
    });
```

What is stored in database
<img width="853" alt="image" src="https://github.com/typeorm/typeorm/assets/37369710/0ff86145-04de-4902-9ffa-0e92a3b9a1ed">

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 18.16.0  |
| Typescript version  | 5.1.6 |
| TypeORM version     | 0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by elegantcoder** [comment]
I don't think this is an issue. When you provide a timestamp with a time zone to TIMESTAMPTZ, it converts the timestamp to UTC for storage. When retrieved, the timestamp is displayed in the session's time zone.

**Comment by sergey-shablenko** [comment]
> I don't think this is an issue. When you provide a timestamp with a time zone to TIMESTAMPTZ, it converts the timestamp to UTC for storage. When retrieved, the timestamp is displayed in the session's time zone.

this is exactly the issue, I need to preserve timezone, if I wanted to store in UTC I would just use TIMESTAMP
whole purpose of TZ is to hold given timezone and not just 00

**Comment by sergey-shablenko** [comment]
Closing the issue, I miss interpreted postgres documentation on timestamptz type
It works as it should, there is no other way (at least I have not found) to preserve given timezone other than to store it as a separate column.
My bad
