### ISSUE TITLE
proper use of custom repositories

### ISSUE THREAD

**Issue by theigor** [typeorm/typeorm#1036]
This is more of a question than an issue but I wanted to make sure I am doing this right and I didn't see a better forum for questions.

The docs say not to use custom repositories as a service - http://typeorm.io/#custom-repository/using-custom-repositories-in-transactions-or-why-custom-repositories-cannot-be-services. Is this what you mean _not_ to do:

in `repo/somemodel`:
```
import { EntityRepository, Repository, getCustomRepository } from 'typeorm';
import { SomeModel } from '../models/SomeModel';

@EntityRepository(SomeModel)
class SomeModelRepository extends Repository<SomeModel> {

}

export default getCustomRepository(SomeModelRepository);
```

and then use it like so in some other file:
```
import repo from '../repo/somemodel';

repo.findOneById(id)
  .then(r => dosomething)
  .catch(err => dosomething);
```

If I understand correctly, you're saying don't do the above, but instead export SomeModelRepository in `repo/somemodel` and do the `getCustomRepository` in the modules you're actually using it in? If that's true, does that also mean that if I have multiple functions in the other file, I shouldn't just have a module level `const repo = getCustomRepository(SomeModelRepository)` but instead get a new repo in every function I need it (or for every transaction)?

Thanks!

**Comment by pleerock** [comment]
You actually can do that. Just remember that in transactions you should not use `import repo from '../repo/somemodel';`, instead you should use `transactionalEntityManager. getCustomRepository(SomeModelRepository)` where `transactionalEntityManager` is `EntityManager` provided by a transaction.

**Comment by theigor** [comment]
Perfect. Thanks!
