### ISSUE TITLE
Cockroach support

### ISSUE THREAD

**Issue by aequasi** [typeorm/typeorm#1040]
https://www.cockroachlabs.com

Its supposed to work with postgres clients, but there are some irregularities.

Example: `information_schema.table_constraints` does not have a `table_catalog` column.

**Comment by pleerock** [comment]
so, its not 100% postgres compatible?... Is this database free and can be installed on local machine?

**Comment by aequasi** [comment]
Correct. There are apparently a couple idiosyncrasies

https://www.cockroachlabs.com/docs/stable/porting-postgres.html

**Comment by pleerock** [comment]
Understood. Right now there are bunch of other more prioritable tasks I have and I cannot do it on my own. If you are interested in Cockroach then maybe its a good idea to contribute a new driver to TypeORM. Since changes aren't dramatic, it may be not a hard PR to implement.

**Comment by ThomasLohmann** [comment]
Hi there,

does anyone have running CockroachDB with TypeORM so far? And when how? It would be really good to hear!

**Comment by ThomasLohmann** [comment]
I have just posted it in the CockroachDB forum and opened an issue in the Cockroach/Github repo. 

Here are the links:

https://forum.cockroachlabs.com/t/typeorm-support-for-node-js-apps/1332/9

https://github.com/cockroachdb/cockroach/issues/22298

Maybe we will find together a solution :).

**Comment by pleerock** [comment]
as @aequasi told  CockroachDB is different on some schema synchronization features. Maybe temporary solution will be to disable schema sync and do it manually? (`synchronize: false` in connection options). But better of course if someone can contribute, find all differences between postgres and CockroachDB and provide a pr with fixes. Its not hard task Im sure.

**Comment by pleerock** [comment]
Im going to close this issue since resolution is on cockroach side (cockroachdb/cockroach#22298)

**Comment by pleerock** [comment]
released in `0.2.14`

**Comment by pungggi** [comment]
any examples?

**Comment by pleerock** [comment]
https://github.com/typeorm/cockroachdb-example

**Comment by pungggi** [comment]
Nice
