### ISSUE TITLE
ManyToMany onDelete = "CASCADE" for a junction table

### ISSUE THREAD

**Issue by makamekm** [typeorm/typeorm#1041]
Is it possible to add onDelete = "CASCADE" for a junction table (ManyToMany)? Because I can't remove an entity with ManyToMany relations.

Example:
```
ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`test`.`department_users_user`, CONSTRAINT `fk_05d6eb113b25d9be938a6e11d8d` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`))
```

My code:
```
@ORM.Entity("department")
export class Department {

    @ORM.PrimaryGeneratedColumn()
    id: number;

    @ORM.ManyToMany(type => User)
    @ORM.JoinTable()
    users: User[];
}

@ORM.Entity('user')
export class User {
    @ORM.PrimaryGeneratedColumn()
    id: number;
}
```

```
let connection = await ORM.Manager.Connect();
let departmentRepository = connection.getRepository(Department);
departmentRepository.removeByIds(ids);
```

In mysql I see: onDelete: RESTRICT.

**Comment by pleerock** [comment]
No, there is no such option. We will consider adding it

**Comment by makamekm** [comment]
Is there another way to remove it?

**Comment by makamekm** [comment]
I'm sorry for the annoying question. But this is a very critical issue. Can you help me, please?

**Comment by pleerock** [comment]
`removeByIds` (now its called `deleteById`) executes a DELETE query and does not execute all special operations `remove` does. You shall use `remove` method and pass all your entities in there, e.g. `await departmentRepository.remove(departments)`

**Comment by makamekm** [comment]
It works. Tank you!
```
    for (let id of ids) {
      let department = await departmentRepository.findOneById(id);      
      await departmentRepository.remove(department);
    }
```

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.

**Comment by lorefnon** [comment]
I am unable to get this to work with typeorm@next and postgresql: 

```typescript
@Entity()
export class Issue  {

    @ManyToMany(
        type => User,
        user => user.assignedIssues,
        {
            onDelete: "SET NULL"
        }
    )
    @JoinTable()
    assignees: Promise<User>
}
```

However I don't see the `ON DELETE` constraint in the join table. 

In table `issue_assignees_user`: 

```
PRIMARY KEY ("issueId", "userId")
--
FOREIGN KEY ("issueId") REFERENCES issue(id)
FOREIGN KEY ("userId") REFERENCES "user"(id)
```

Am I missing something here ?

**Comment by pleerock** [comment]
We are planning to do `onDelete: CASCADE` for junction tables by default. And we'll remove ability to set `onDelete` for junction table. It does not make sense to do `onDelete: SET NULL` for a junction table.

**Comment by lorefnon** [comment]
>  It does not make sense to do onDelete: SET NULL for a junction table.

What is the recommended pattern for a ManyToMany relationship with an intermediate model.

I intended to have a combination of OneToMany and ManyToMany on both sides.

**Comment by pleerock** [comment]
create a separate model which contain one to many relations + extra things you need.

**Comment by lorefnon** [comment]
That is fine. I already have that. 

In many ORMs (eg. Rails ActiveRecord) you can define ManyToMany relations over a model. That model is there when you need the extra fields, but in most cases when you don't, the rest of application doesn't have to worry about it. 

So for instance if I have both OneToMany and ManyToMany, I can already do things like : 

```
issueRepository.find({ relations: ['assignees'] })
```

without needing to join over the intermediate model explicitly. 

I had (incorrectly) assumed that it was something supported because some aspects (like the above) seemed to work out of the box. But then schema synchronization broke badly because the schema sync code strongly assumes that the joinTable I provide to ManyToMany will not be used by any other model.

In any case, thanks for taking the time to reply.

**Comment by pleerock** [comment]
CASCADE are now by default in many-to-many tables in the latest release.

@lorefnon if you want to create a many-to-many relation with additional fields you just need to create a separate relation with two many-to-one relations inside - that's what many-to-many is on its own. Yes you'll need to specify all relations you join inside "relations" and its natural and fits overall design.

**Comment by lucas-coelho** [comment]
@pleerock 
How can i disable the default many-to-many cascade delete in the latest release?
I already try to set the the following config:

 ```
@JoinTable()
  @ManyToMany(_ => Segmentation, segmentation => segmentation.cards,  {
    cascade: false,
    onDelete: 'NO ACTION',
  })
  segmentations: Segmentation[];
```
 
The relation constraint is always being created with `ON DELETE CASCADE`

Thanks!

**Comment by pleerock** [comment]
its pointless to have rows in many to many table for not exist data.

**Comment by lucas-coelho** [comment]
Agree. 
But the data will exist because the constraint will prevent the deletion and an error will raise.

**Comment by pleerock** [comment]
okay maybe we can make that onDelete in many to many decorator options to work. Feel free to contribute!

**Comment by marano** [comment]
Was this ever changed? I want to prevent removal of an entity in case it is reference from a ManyToMany relation.

**Comment by MajidJafari** [comment]
```
// Many-to-Many relationship with 'ips' table

  @ManyToMany(() => Ips, {
    cascade: true,
    onDelete: "CASCADE"
  })

  @JoinTable({
    name: "ip_groups_ips",
    joinColumns: [
      {
        name: "group_id"
      }
    ],
    inverseJoinColumns: [
      {
        name: "ip_id"
      }
    ]
  })

  ips: Ips[];`
```
