### ISSUE TITLE
EntityManagerFactory TypeError when using Next.js middleware and instrumentation

### ISSUE THREAD

**Issue by matejfalat** [typeorm/typeorm#10438]
### Issue description

When using TypeORM in the Next.js app with app router, middleware and instrumentation hook, EntityManagerFactory.js is throwing a TypeError, causing the app to crash.

### Expected Behavior

Not to throw error

### Actual Behavior

If TypeORM `DataSource` is used inside the `instrumentation.ts` file and the app is using Next.js middleware, the following error is thrown:
```
TypeError: Cannot read properties of undefined (reading 'type')
    at EntityManagerFactory.create (webpack-internal:///./node_modules/typeorm/browser/entity-manager/EntityManagerFactory.js:19:39)
    at DataSource.createEntityManager (webpack-internal:///./node_modules/typeorm/browser/data-source/DataSource.js:417:109)
    at new DataSource (webpack-internal:///./node_modules/typeorm/browser/data-source/DataSource.js:70:29)
    at getDataSource (webpack-internal:///./database/config.ts:13:25)
    at Module.register (webpack-internal:///./instrumentation.ts:8:68)
    at registerInstrumentation (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/globals.js:8:55)
    at ensureInstrumentationRegistered (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/globals.js:18:42)
    at enhanceGlobals (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/globals.js:64:10)
    at eval (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/globals.js:66:1)
    at (middleware)/./node_modules/next/dist/esm/server/web/globals.js (/workspace/.next/server/middleware.js:173:1)
```
A couple of `Module not found` errors are shown as well:
```
 ⚠ ./node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js
Module not found: Can't resolve 'react-native-sqlite-storage' in '/workspace/node_modules/typeorm/browser/driver/react-native'

Import trace for requested module:
./node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js
./node_modules/typeorm/browser/driver/DriverFactory.js
./node_modules/typeorm/browser/data-source/DataSource.js
./node_modules/typeorm/browser/index.js
./database/config.ts
```

- not using Next.js middleware or instrumentation hook will get rid of the error.
- using a singleton pattern for `AppDataSource` will prevent the app from crashing, but the errors are still there.

Btw, is there a way to patch the library to disallow importing the browser code?

### Steps to reproduce

https://codesandbox.io/p/sandbox/crimson-cloud-pjl222

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  WSL2    |
| Node.js version     |  20.7.0  |
| Typescript version  | 5.2.2  |
| TypeORM version     | 0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by disserlin** [comment]
I've hit this exact same error. I've got both middleware and instrumentation set up and not keen on removing either.

Can you elaborate on how you would implement a `singleton` pattern to get past this error?

**Comment by matejfalat** [comment]
The best I could do was this https://codesandbox.io/p/sandbox/cranky-stallman-sqsnjc?file=%2Fdatabase%2Fconfig.ts%3A1%2C1. 

It still throws the errors, but at least the errors are caught (and optionally hidden from the console) and not causing the app to crash 😕

**Comment by disserlin** [comment]
That's great. Thanks for sharing. 

Is the intention to call `getDataSource` anytime you need to interact with the database? Or is there a way to persist it `server-side` so it is always available.

Following your example, it is initialized properly in the `instrumentation`, but if I try access it later within an API call from the client it is always null.

**Comment by austenstrine** [comment]
I had a very similar exception when using this for Postgres, and the workaround that worked for me for me was to pass the driver directly into the options for to the DataSource like this:

    import { DataSource, DataSourceOptions } from "typeorm"
    import pg from "pg";//ATTN: This is the driver for postgres

    const postgresOptions: DataSourceOptions = {
        type: "postgres",
        host: "localhost",
        port: 5432,
        username: "postgres",
        password: "DerrierreDev#1",
        database: "postgres",
        entities: ["./entity/*.ts", "./entity/**/*.ts"],
        driver: pg, //ATTN: I pass the driver object in directly here.
        synchronize: true
    };
    const PostgresDB = new DataSource(postgresOptions);
    export {
        PostgresDB
    }

**Comment by matejfalat** [comment]
As described [here](https://github.com/vercel/next.js/issues/51450#issuecomment-1854290988), the instrumentation runs once in each environment. The solution is to use dynamic import to only import TypeORM DataSource code in the nodejs environment. Updated [code sandbox](https://codesandbox.io/p/devbox/loving-cdn-64vp9l?file=%2Finstrumentation.ts%3A1%2C1-6%2C1).

Closing the issue.

**Comment by gladykov** [comment]
Middleware and typeORM is a tricky :/ 

I was able to get rid of issue ` Can't resolve 'react-native-sqlite-storage'` by adding in package.json:

```
  "browser": {
    "typeorm": false
  },
```
