### ISSUE TITLE
Eager loading relation that has a `@VirtualColumn` results in an empty Entity in the relation

### ISSUE THREAD

**Issue by tolgap** [typeorm/typeorm#10431]
### Issue description

See title

### Expected Behavior

I would expect that if the `@ManyToMany` relation results in no results in SQL, that the relation would be empty as well.

### Actual Behavior

But the relation is an array with 1 element in it that has all fields `null` but the `@VirtualColumn` field is set to `0` (its a virtual column to sum something).

### Steps to reproduce

I've added a test reproduction to `typeorm/typeorm` in PR #10432 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | MacOS 13.3.1 |
| Node.js version     | 18.12  |
| Typescript version  | 4.9.5  |
| TypeORM version     | 0.3.14  |

### Additional Context

The behavior is the same as in #7450, but the `@VirtualColumn` adds a field that results in `0`, and so its not `null`. The fix for #7450 does not catch this.

If you remove the `@VirtualColumn` definition from `Category.ts`, the fix for #7450 work well again, but that just proves that #7450 has not fixed the root cause of this.

### Relevant Database Driver(s)

- [X] aurora-mysql
- [X] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by ragrag** [comment]
is this in any way related to https://github.com/typeorm/typeorm/issues/10412?

**Comment by ropotvs** [comment]
For me the fix was this:

**Before**
` @VirtualColumn({
    query: (alias) => // here was my query
  })
  public count!: number;
  `
  
  **Solution:**
` @VirtualColumn({
    query: (alias) => safeVirtualColumnQuery(alias, // here is my query)
  })
  public count!: number;
  `
  
function safeVirtualColumnQuery(alias: string, query: string): string {
  return `SELECT CASE WHEN ${alias}.id IS NULL THEN NULL ELSE (${query}) END`;
}

**Comment by tolgap** [comment]
@ropotvs that's not a fix. That's a workaround!
