### ISSUE TITLE
Support for libSQL/Turso

### ISSUE THREAD

**Issue by torbenraab** [typeorm/typeorm#10451]
### Feature Description

Possibility to use libSQL or Turso as a database

### The Solution

Build support for libSQL extending the functionality of sqlite

### Considered Alternatives

None other than using another database type

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time, but I can support (using donations) development.

**Comment by fl0wo** [comment]
Please 🙏🏻

**Comment by cryptosebek** [comment]
+1

**Comment by TamerAlbouz** [comment]
+1

**Comment by invisal** [comment]
Have you tried

```
npm install sqlite3@npm:@libsql/sqlite3 --force
```

Then

```
export const AppDataSource = new DataSource({
  type: "sqlite",
  flags: 0x00000040, // this is required to make it work in TypeORM
  database:
    "libsql://example.turso.io?authToken=...",
  // ....
});
```

**Comment by javiercr** [comment]
> flags: 0x00000040, // this is required to make it work in TypeORM

@invisal what does that flag do? Is it documented anywhere? Thanks!

**Comment by hieuht-htv** [comment]
> > flags: 0x00000040, // this is required to make it work in TypeORM
> 
> @invisal what does that flag do? Is it documented anywhere? Thanks!

here
https://www.sqlite.org/c3ref/c_open_autoproxy.html

**Comment by hieuht-htv** [comment]
+1

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
