### ISSUE TITLE
type "enum" does not exist

### ISSUE THREAD

**Issue by mkzaker** [typeorm/typeorm#1045]
Hi,
my database is postgres and i have this error 
QueryFailedError: type "enum" does not exist

**Comment by pleerock** [comment]
enums are only supported in [mysql](https://github.com/typeorm/typeorm/blob/e7c516e7f4f162e1411d65a8aa30c43ef8b9220e/test/functional/database-schema/column-types/mysql/entity/Post.ts#L83). We are planning to add postgres enum support in 0.2.0 . Duplicate of #671

**Comment by pleerock** [comment]
I expect it in December

**Comment by RDeluxe** [comment]
Hello, any news about this ? i'm currently starting a new project with TypeORM and I would like to avoid hacking around if the new version is not far away

**Comment by pleerock** [comment]
Work is in progress, we are expecting to land 0.2.0 in the beginning of January

**Comment by RDeluxe** [comment]
Hi,

Any news about this ? :)

**Comment by pleerock** [comment]
Hey Ive been very busy last two months, so 0.2.0 milestone is moved to March.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.
