### ISSUE TITLE
npm test failed

### ISSUE THREAD

**Issue by jiak94** [typeorm/typeorm#10455]
### Issue description

npm test exit early

### Expected Behavior

`npm test` should run all the tests and all the tests should pass.

### Actual Behavior

`npm test` existed earlier after commands - generate.

The bug was probably introduced by this PR: https://github.com/typeorm/typeorm/pull/9288

### Steps to reproduce

If you check all the circle CI logs, all tests exit early.

If you disabled the `commands - generate` test, all other test cases will be executed and fail at `database schema > enums`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      MacOS    |
| Node.js version     | 20.8.0  |
| Typescript version  | 5.2.2  |
| TypeORM version     | 0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by edosrecki** [comment]
@jiak94 there's already my open PR for this issue:

https://github.com/typeorm/typeorm/pull/10361

**Comment by edosrecki** [comment]
And the bug is already tracked in #10360
