### ISSUE TITLE
Property name with setter

### ISSUE THREAD

**Issue by Christilut** [typeorm/typeorm#1048]
I have a property like this:
```ts
  @IsEmail()
  @Column({
    unique: true,
    name: 'email'
  })
  _email: string
  set email(email: string) {
    this._email = email.toLowerCase()
  }
```

Now if I want to find a user by email, I have to do this:
```ts
      return User.findOne({
        _email: email
      })
```

But I don't want to use `_email`, but `email` instead. 

How do I do that?

Edit: If i do `findOne({ email })` then I get the following error: `QueryFailedError: syntax error at or near "."`

**Comment by pleerock** [comment]
its not possible. Find method can find results by your entity columns, not by your entity methods.

**Comment by Christilut** [comment]
Okay.

But shouldn't it work when a getter is set like this: `get email() { return this._email }` ?

I mean, that would make sense to me.

It's too bad that when adding a setter that you have to choose between a suboptimal variable name (eg `_email`) or that you have to name the setter `_email` (or `setEmail`).

Perhaps this can be added to the backlog as an improvement?

**Comment by Christilut** [comment]
Actually, now that I changed to model property to be private, it doesn't work at all anymore...

```ts
  // Email
  @IsEmail()
  @Column({
    unique: true,
    name: 'email'
  })
  private _email: string
  get email() { return this._email }
  set email(email: string) {
    this._email = email.toLowerCase()
  }
```

This gives me a Typescript error:
```ts
  const user: User = await User.findOne({
    _email: email
  })
```

and this gives me the `QueryFailedError: syntax error at or near "."` :
```ts
  const user: User = await User.findOne({
    email: email
  })
```

**Comment by pleerock** [comment]
getters and setters are `functions`. So, when you do:

```ts
const user: User = await User.findOne({
    email: email
  })
```

"email" is function (method) here, not a column to lookup by. Your actual column is "_email". So your query sounds like "find me a user where its email function is equal to given email"

**Comment by pleerock** [comment]
If we want to support this feature we need a really good and *simple* proposal, currently I don't have ideas about really good way to implement it. Right now you can use getters this way:

```ts
@Entity()
export class Post {

    private _title: string;

    @PrimaryGeneratedColumn()
    id: number;

    set title(title: string) {
        // this._title = "!" + title + "!"; // if you'll do "append" like this, you won't get expected results, because setter is called multiple times
        if (title === "hello") {
            this._title = "bye";
        } else {
            this._title = title;
        }
    }

    @Column()
    get title(): string {
        return this._title;
    }

}
```

But this way has its own limitations as well.

**Comment by Christilut** [comment]
I'm still a bit confused how to do a `findOne` operation in this scenario.

If my model has a setter and a private property, eg:
```ts
  @Column({
    name: 'email'
  })
  private _email: string
  set email(email: string) {
    this._email = email.toLowerCase()
  }
```

Then I can't do
```ts
  const user: User = await User.findOne({
    _email: email
  })
```
Because _email is private. I get this Typescript error:
```
[ts]
Argument of type '{ _email: any; }' is not assignable to parameter of type 'DeepPartial<User>'.
  Object literal may only specify known properties, and '_email' does not exist in type 'DeepPartial<User>'.
```

How should I get this user from the database based on his email?

**Comment by pleerock** [comment]
Why are confused? Your property is private thats why you have an error, find one method expects public properties of User model. Columns shouldn't be private if you want to work with them. Btw if you want to change something before saving to the database there are other options like entity listeners and value transformers.

**Comment by Christilut** [comment]
Ahh okay. So the right solution to put the lowerCase email into the db is to use a value transformer. 

Works like a charm now 👍

**Comment by pleerock** [comment]
Depend on what do you call encapsulation. From my experience most people coming from OOP world even don't know what exactly encapsulation means. Just dummy users of private properties + getters/setter for them without even having knowledge of why they do use such pattern.

**Comment by carlos-cubas** [comment]
@pleerock regardless of the tone that @jhonatanTeixeira  is using, the idea of supporting private properties is a good one.  Is there an issue/proposal that's tracking this idea?

**Comment by bsommardahl** [comment]
> If we want to support this feature we need a really good and _simple_ proposal, currently I don't have ideas about really good way to implement it. Right now you can use getters this way:
> 
> ```ts
> @Entity()
> export class Post {
> 
>     private _title: string;
> 
>     @PrimaryGeneratedColumn()
>     id: number;
> 
>     set title(title: string) {
>         if (title === "hello") {
>             this._title = "bye";
>         } else {
>             this._title = title;
>         }
>     }
> 
>     @Column()
>     get title(): string {
>         return this._title;
>     }
> 
> }
> ```
> 
> But this way has its own limitations as well.

Can you explain some of the limitations? From my perspective, this solves my problem. I'm fine with getters on properties that map to columns. I'm not okay with pubic setters.

**Comment by SylvainEstevez** [comment]
One solution could be to accept an additional (and optional) generic on the `Repository`. It does feel a bit hacky but would give the desired behavior.

```typescript
@Entity()
export class Post {
  @Column('string')
  private title: string; // <- Private members

  public setTitle(title: string) {
    this.title = title;
  }
}

export type PostAttributes {
  title: string;
}

@EntityRepository(Post)
export class PostRepository extends Repository<Post, PostAttributes> {
}

const foo = await postRepository.findOne({ select: ['title'] }); // <- Refers to the PostAttribute type
foo.setTitle('Vive TypeORM!'); // <- Refers to the Post entity
```

The base `Repository` class would look something like this (simplified):
```typescript
export class Repository<Entity extends ObjectLiteral, Attributes extends ObjectLiteral = Entity> {
  findOne(options?: { select: (keyof Attributes)[] }): Entity | undefined { ... }
}
```

This would also have the positive side effect of not counting methods as valid attributes (`await postRepository.findOne({ select: ['setTitle'] });` is considered valid currently for example).

**Comment by riyadshauk** [comment]
I'm relatively new to back-end development, but, even though this may not be a perfect solution, this library still seems to work well, if you don't want to get into hairier libraries or just default to using plain SQL (I was experimenting with these concepts for a few hours today before circling back to the following conclusion).

If you want to do encapsulation (have a notion of getters and setters, though not necessarily using the syntax), the custom repository pattern seems to currently be the best way to go (while keeping the code pretty simple), as described in the library docs: https://typeorm.io/#/custom-repository . Just make sure to only deal with the repository methods that you expose, rather than with the actual entity (which would result in breaking the design pattern meant to encourage encapsulation).

I wonder if there's a way to prevent such direct usage of an entity from outside of a repository by using a linter or other tool?

**Comment by amirh715** [comment]
I have multiple associated entities each having a `published` column. When the `published` property of some of these entities change the `published` property of other entities should change as well. I prefer to do this inside my model (not using subscribers). How can I do that?

**Comment by Bezlepkin** [comment]
> So, because there's people who doesnt know how to encapsulate, we break it so people who actualy knows how to use it, cant use it either.
> And what you mean with "people coming from OO world"? This library is a ORM an Object Relational Mapper, writen for typescript a strong static typed language mantained by microsoft. This os the OO world

For this reason, I am rewriting my pet project in PHP with Doctrine 😃
