### ISSUE TITLE
If TypeORM failed to do anything then why it offers so many APIs

### ISSUE THREAD

**Issue by RyanLiu0235** [typeorm/typeorm#10491]
### Issue description

TypeORM SUCKS

### Expected Behavior

TypeORM should do as the APIs tell.

### Actual Behavior

```ts
const user = await createQueryBuilder("user")
    .leftJoinAndSelect("user.photos", "photo")
    .where("user.name = :name", { name: "Timber" })
    .getOne()
```

As the doc tell, it should return something like this
```
{
    id: 1,
    name: "Timber",
    photos: [{
        id: 1,
        url: "me-with-chakram.jpg"
    }, {
        id: 2,
        url: "me-with-trees.jpg"
    }]
}
```

Instead, it returns 
```
{
    id: 1,
    name: "Timber",
    photo_id: 1,
    photo_url:  "me-with-chakram.jpg"
}
```

Actually I've had it enough of the weakness of TypeORM, it doesn't work out as expected, like 
1. `update()` should update a relation but throws an error say can't query cross on-to-many relation,
2.  like `unique`, 
3. like `CreateDateColumn` should automatically insert create timestamp like this decorator designed but did nothing but threw errors and errors and I really wanna remove this liar modules out of my package.json.

### Steps to reproduce

try it yourself, YOU SUCK

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  |
| Typescript version  | x.y.zzz  |
| TypeORM version     | x.y.zzz  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by RyanLiu0235** [comment]
typeorm is fucking rubbish.

**Comment by pleerock** [comment]
I guess non sucking brain can't figure out different puzzles in the documentation.
