### ISSUE TITLE
Incorrect documentation on length

### ISSUE THREAD

**Issue by andrew-w-ross** [typeorm/typeorm#105]
[The length property on the documentaion](https://typeorm.github.io/index.html#example-column-data-types) takes a number type on the documentation but actually takes a string.

**Comment by pleerock** [comment]
yes, thats a mistake, thanks I'll fix it. Im actually thinking if length should be a number, not a string in implementation too...

**Comment by andrew-w-ross** [comment]
@pleerock yeah I'm not entirely sure when you would need the value to be a string.

**Comment by pleerock** [comment]
Made it to support numbers too in 17d7df41f6778ad0589f2de39d0e5ac079c09a3a will be available in next release
