### ISSUE TITLE
Async transformer saves empty object

### ISSUE THREAD

**Issue by Christilut** [typeorm/typeorm#1050]
```ts
  @Column({
    transformer: {
      async to(password: string): Promise<string> {
        const SALT_FACTOR = 5

        const salt: string = await bcrypt.genSalt(SALT_FACTOR)

        const hash: string = await bcrypt.hash(password, salt)

        return hash
      },
      from(hash: string): string {
        return hash
      }
    }
  })
  password: string
```

The to() function is saving `'{}'` to the database (it should be saving the password hash). If I change it to be synchronous with a hard coded string, it will save properly.

**Comment by pleerock** [comment]
I wasn't implementator of transformers, so maybe async transformation isn't supported. I recommend to use entity listeners instead - they should work well with async

**Comment by Christilut** [comment]
Okay, I'll add it to the transformer PR, maybe the author wants to add async support.
