### ISSUE TITLE
broken slack link in `docs/support.md`

### ISSUE THREAD

**Issue by ayaankhan98** [typeorm/typeorm#10504]
### What was unclear or otherwise insufficient?

Link to slack community is not working

### Recommended Fix

Please update the link.

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by juherr** [comment]
Duplicate of #10111

**Comment by ayaankhan98** [comment]
closing because it's duplicate.
