### ISSUE TITLE
No type:json anymore?

### ISSUE THREAD

**Issue by mattposch** [typeorm/typeorm#1052]
Just upgraded from 0.0.11 to 0.1.1 and having a lot breaking changes, one of them is, that I can't use  
`@Column({type: 'json'})` anymore, with the following error message:

<img width="1198" alt="screen shot 2017-10-19 at 15 22 23" src="https://user-images.githubusercontent.com/2116286/31773009-ae383848-b4e1-11e7-8b42-18702d6bb162.png">

Model is called "template" and has a property "presetAdvancedSettings" with the mentioned Column decorator.

Any idea why it doesn't work? o.O

**Comment by pleerock** [comment]
it must work, there are tests [confirming it](https://github.com/typeorm/typeorm/blob/ecb050141f2766c1cc320d0d606128be1e26fd86/test/functional/database-schema/column-types/mysql/entity/Post.ts#L91). Try to create a new (empty) model with json column type and check if it works

**Comment by mattposch** [comment]
hmm, interesting, created a new model and still got this error :(

I'm using MySQL 5.6.27 with InnoDB engine and UTF-8, if that makes a difference.

![screen shot 2017-10-19 at 15 41 03](https://user-images.githubusercontent.com/2116286/31773739-f15299e6-b4e3-11e7-8967-0dd4586ca3ac.png)
<img width="1167" alt="screen shot 2017-10-19 at 15 38 41" src="https://user-images.githubusercontent.com/2116286/31773741-f16dc7d4-b4e3-11e7-8249-87d6f3c4f3e3.png">

**Comment by mrkmg** [comment]
I found that it only works if your database natively supports it now. It no longer does any magic for you to convert from/to a json object. If you use postgre, you will see it works.

I used a getter/setter for my use case.

```
@Entity()
class Todo {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    public name: string;

    @Column("text")
    public dataJson?: string;

    public get data(): any {
        if (this.dataJson) return JSON.parse(this.dataJson);
        else return null;
    }

    public set data(data: any) {
        if (data) this.dataJson = JSON.stringify(data);
        else this.data = null;
    }

    // Only needed if you want the json to included when you stringify 
    // the whole object.
    // e.g request.json(obj)
    public toJSON() {
        return {
            id: this.id,
            name: this.name,
            data: this.data
        };
    }
}
```

You may want to use a library for your json parsing, or wrap it in a try/catch as it can throw a fatal error.

**Comment by mattposch** [comment]
Thanks for the hint. Seems like MySQL 5.7 supports JSON as datatype, will try to update!

**Comment by pleerock** [comment]
@mrkmg you are right, thanks

**Comment by pleerock** [comment]
I guess this can be closed.
