### ISSUE TITLE
new typeorm version that is compatible with the mongodb driver package version 6.x.x

### ISSUE THREAD

**Issue by alifakoor** [typeorm/typeorm#10527]
### Feature Description

Hi guys
in the mongodb dirver version 6.x.x, they fixed a bug about memory leak in `findOne` query, but the last version of typeorm package just compatible with mongodb driver version 5.x.x and is cause a dependency conflict.Mongodb

### The Solution

a new version of typeorm that is compatible with mongodb driver version 6.x.x

### Considered Alternatives

we can use `--force` in the install command, but it's risky that causes other issues

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [X] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time, but I can support (using donations) development.

**Comment by aleccool213** [comment]
I created a pull request as I am getting the same peer dep error in a library I am using. Feel free to review.
