### ISSUE TITLE
Adding an entity with relation not working as expected

### ISSUE THREAD

**Issue by mrkmg** [typeorm/typeorm#1054]
Given the following models:

```
@Entity()
class Parent {
  @PrimaryGeneratedColumn()
   public id: number;

   @Column()
   name: string;

  @OneToMany(target => Child, child => child.parent)
  children: Child[];
}

@Entity()
class Child {
  @PrimaryGeneratedColumn()
  public id: number;

  @Column()
  name: string
  
  @ManyToOne(target => Parent, parent => parent.id)
  parent: Parent;
}
```

Given the following code:

```
const child = new Child();
child.name = "test";
child.parent = await Parent.findById(1);
await child.save();
```

I expect that a row would be created in the child table with the column parentId equal to 1. But instead it's null.

Now, if I do it as follows:

```
const parent = await Parent.findById(1);
const child = new Child();
child.name = "test";
await child.save();

parent.children.push(child);
await parent.save();
```

Then I get the correct result. 

It appears that in order to add an entity to a OneToMany or ManyToOne relations, it has to be done from the OneToMany side.

Also, I am doing this inside a transaction, using the format `entityManager.save(entity)`.

My apologies if this has already been reported.

**Comment by mrkmg** [comment]
Okay, so I found the issue.

Because I do not have `eager: true`, I have to assign the parent as follows:

```
const child = new Child();
child.name = "test";
child.parent = Parent.findOneById(1);
await child.save();
```

The following works as well:

```
const parent = await Parent.findOneById(1);
const child = new Child();
child.name = "test";
child.parent = Promise.resolve(parent);
await child.save();
```

**Comment by pleerock** [comment]
> It appears that in order to add an entity to a OneToMany or ManyToOne relations, it has to be done from the OneToMany side.

no, it MUST work from both sides

> const child = new Child();
child.name = "test";
child.parent = Parent.findOneById(1);
await child.save();

waaaaat, you don't need a promise to store in "parent" until you don't have lazy relations. Can you please create a failing test for your case, so I can take a look and quickly fix it?

**Comment by mrkmg** [comment]
Tests added

**Comment by daniel-lang** [comment]
Maybe I'm missing something, but I pulled your tests into the current master and the inserts are fine. I had to change your tests a bit, because, as far as I know, `await` doesn't work when the relation is not eager and no promise is used. So instead of
```typescript
const loadedChild = await connection.manager.findOneById(Child, 1);
expect(loadedChild).not.to.be.empty;

if (!loadedChild) return false;
const childsParent = await loadedChild.parent;
```
it would be
```typescript
const loadedChild = await connection.manager.findOneById(Child, 1, {relations: ["parent"]});
expect(loadedChild).not.to.be.empty;
if (!loadedChild) return false;

const childsParent = loadedChild.parent;
```
After that change to the tests that don't use promises, everything is fine for drivers that we test with CI.
Maybe your issue was resolved in the meantime?

**Comment by mrkmg** [comment]
I am not sure, but I have since used some work arounds. If I get time, I will revisit this issue.

**Comment by daniel-lang** [comment]
@mrkmg Did you have time to revisit this?

**Comment by mrkmg** [comment]
I am going to just close this, as I have long left this in the past in my development. 

Also, I believe it was not an issue in `next`.

If something like this happens again, and its really not just be being dumb, I will come back and re-open this or make a new issue.
