### ISSUE TITLE
official document went like s**t

### ISSUE THREAD

**Issue by kaiwenxiao** [typeorm/typeorm#10544]
### What was unclear or otherwise insufficient?

![image](https://github.com/typeorm/typeorm/assets/31737119/24d75665-bf0a-4efc-aac0-2c1329901d6f)

### Recommended Fix

not content display

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by kaiwenxiao** [comment]
> slow network, maybe official has not enough resources to run this website, so THERE NEED U & I TO DONATE。

Thanks your info, So had you saw this issue either?

**Comment by AlexMesser** [comment]
see #9705

**Comment by kaiwenxiao** [comment]
> see #9705

Very upset for neglect the specific region people for access your website.
