### ISSUE TITLE
Is it possible to set `cache: true` flag from repository methods

### ISSUE THREAD

**Issue by pie6k** [typeorm/typeorm#1057]
eg 
```
getDbConnection().getRepository(Task).find({cache: true})
```

Looking at docs - I see it's possible via query builder (I prefer to use repository)

**Comment by pleerock** [comment]
not yet, but its easy implementable, you can do it on your own in a PR very quickly

**Comment by pleerock** [comment]
thanks to @aj-liptak this feature is implemented and will be released in `0.1.2`
