### ISSUE TITLE
Redis as primary database

### ISSUE THREAD

**Issue by aceonics-team** [typeorm/typeorm#10570]
### Feature Description

If TypeORM supports Redis as the primary database it would make life much easier for those who need to use an in-memory database with an existing project or a new one.

### The Solution

TypeORM would support Redis to be used as primary database just like other databases.

### Considered Alternatives

There is a https://github.com/redis/redis-om-node package that allows Redis to be used as the primary database.

### Additional Context

Maybe redis-om-node can be used with TypeORM to support Redis as the primary db.

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
