### ISSUE TITLE
Error on test Connection replication > before each in replication.ts

### ISSUE THREAD

**Issue by alenap93** [typeorm/typeorm#10582]
### Issue description

If we run npm test, test fail on replication.ts

### Expected Behavior

test has to pass if test use postgres, otherwise skip it

### Actual Behavior

If we run npm test without postgres, test fail on replication.ts:

1) Connection replication
       after connection is established successfully
         "before each" hook for "connection.isInitialized should be true":
     TypeError: Cannot read properties of undefined (reading 'createQueryBuilder')
      at Context.<anonymous> (test/functional/connection/replication.ts:56:18)

### Steps to reproduce

run npm test

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Windows 11     |
| Node.js version     | 16  |
| Typescript version  | 4.9.5  |
| TypeORM version     | 0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by alenap93** [comment]
Pr: #10540

**Comment by AlexMesser** [comment]
fixed in #10590
