### ISSUE TITLE
UpdateValuesMissingError: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.

### ISSUE THREAD

**Issue by AaronNGray** [typeorm/typeorm#10594]
### Issue description

Problems adding Comment Array to Post

### Expected Behavior

Comments get automatically added to a Post as an Array.

### Actual Behavior

I get the following error on writing an array of Posts each with zero or more Comments in an array.

### Steps to reproduce

Example project to show the issue using a src/seed.ts script running using a sqlite3 database.

```
git clone https://github.com/AaronNGray/typeorm-0.3.17-test.git
cd typeorm-0.3.17-test
npm install
npm run db:make
npm run seed
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 11         |
| Node.js version     | 21.5.0  |
| Typescript version  | 5.3.3  |
| TypeORM version     | 0.3.17  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [X] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by alenap93** [comment]
your code has problems on async/await, i made a fast fix here on seed.ts file
[seed.txt](https://github.com/typeorm/typeorm/files/13834210/seed.txt)

**Comment by AaronNGray** [comment]
@alenap93 Oh what, I thought the typescript compiler would have caught those. Many thanks for catching those !
