### ISSUE TITLE
Error with 'createConnection' building with Webpack and Jasmine

### ISSUE THREAD

**Issue by CodingMadeEasy** [typeorm/typeorm#106]
Hello, 

Whenever I call the createConnection() function inside my test file I get the following error: 
```
ERROR in ./~/app-root-path/lib/resolve.js
Module not found: Error: Cannot resolve module 'module' in /Users/profile/Documents/node_modules/app-root-path/lib
 @ ./~/app-root-path/lib/resolve.js 7:18-35
```

with a bunch of warnings that look like the following:
```
WARNING in ./~/app-root-path/lib/resolve.js
Critical dependencies:
31:15-32 the request of a dependency is an expression
 @ ./~/app-root-path/lib/resolve.js 31:15-32
```

Here's my current webpack configuration: 
```
var path = require('path');
var webpack = require('webpack');

module.exports =
{
    entry : {
        bundle: [ 'webpack-hot-middleware/client?timeout=20000&reload=true', './src/client/client.tsx' ],
        test:   [ 'webpack-hot-middleware/client?timeout=20000&reload=true', './specRoot.js' ]
    },
    output :
    {
        publicPath : '/',
        path: path.join(__dirname, '/public/'),
        filename : '[name].js',
        hotUpdateChunkFilename: 'hot/[id].[hash].hot-update.js',
        hotUpdateMainFilename: 'hot/[hash].hot-update.json',
        devtoolModuleFilenameTemplate: function(info) {
            return "file:///"+encodeURI(info.absoluteResourcePath);
        }
    },
    plugins : [
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
    ],
    devtool : "source-map",
    resolve:
    {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: ["", ".webpack.js", ".web.js", ".ts", ".tsx", ".js"]
    },
    module :
    {
        loaders :
        [
            { test : /\.tsx?$/, loaders : [ 'ts-loader'] },
            { test: /\.js$/, exclude: [/node_modules/, /Documentation/], loaders: [ 'react-hot-loader/webpack' ] }
        ]
    },
    externals:
    {
        "react": "React",
        "react-dom": "ReactDOM",
        'jsdom': 'window',
        'cheerio': 'window',
        'react/addons': true,
        'react/lib/ExecutionEnvironment': true,
        'react/lib/ReactContext': true
    },
    node: {
        fs: "empty",
        tls: "empty",
        net: "empty"
    }
};
```

Here is me calling the createConnection method inside my test file: 
```
it ('testing connection', () =>
    {
        // jasmine.createSpy('testSpy', createConnection).and.callThrough();
        createConnection();
    });
```

Do you know what I can do to resolve this issue?

Ps. I'm using the latest version.

**Comment by pleerock** [comment]
are you trying to use typeorm on the frontend?

**Comment by CodingMadeEasy** [comment]
Yes

**Comment by CodingMadeEasy** [comment]
If that's not possible. Is there a way to mock it for testing purposes?

**Comment by pleerock** [comment]
you should use TypeORM on the backend, frontend is not supported yet. I didnt understand what you are doing? Are you using typeorm on the backend, but share models between frontend and backend or what?

**Comment by CodingMadeEasy** [comment]
I'm using Jasmine to create unit tests. So in my describe block I'm calling createConnection and I'm getting the error I stated above. 

I'm using webpack to build my test file that will then be used on the frontend.

**Comment by CodingMadeEasy** [comment]
Basically I want to test a method which calls createConnection, but I can't test the method because it fails when it gets to createConnection

**Comment by pleerock** [comment]
> I'm using webpack to build my test file that will then be used on the frontend.

you are using typeorm on the backend, right? if so then you should write your tests for the backend too. I dont understand why you are using webpack here, you should not use it

**Comment by CodingMadeEasy** [comment]
But how am I supposed to see the results of my tests? The reason why I'm using webpack is so that I can reference the bundled file in the fronted. To make things more clear here is what my test page looks like: 

```
<html>
            <head>
                <title>Test</title>

                <link rel="stylesheet" href="js/jasmine.css" />

                <script src="js/jasmine.js"></script>
                <script src="js/jasmine-html.js"></script>
                <script src="js/boot.js"></script>
            </head>

            <body>
                <script src="js/react.js"></script>
                <script src="js/react-dom.js"></script>

                <script src="test.js"></script>
            </body>
</html>
```

test.js is the name of the bundled file.

**Comment by pleerock** [comment]
Sorry but I still cant understand your use case. @m19majkel94 can you take a look on this issue once?

**Comment by 19majkel94** [comment]
I also have no idea about the purpose of testing backend ORM on frontend using webpack 😜
> But how am I supposed to see the results of my tests?

If you are testing your backend, you just run `npm test` in console and see the results reported by mocha/jasmine in console too!

> Are you using typeorm on the backend, but share models between frontend and backend or what?

It is a great use case. But it would need a fake/mock library just to satisfy TS compiler and decorators evaluation (decorator functions that do nothing) - we could then configure webpack to intercept all `require('typeorm')` to `typeorm-mock` (or maybe an other npm trick like `npm install typeorm@mock`?) and share model definitions between rest api and client in browser 👍 

I could even do this one day, after my graduation... when I will be changing my frontend to Angular2 😉

**Comment by pleerock** [comment]
@19majkel94 for this purposes I created this file here 68aa138e408297a21b41754de154a9e6354ba8e0 I think this can be used to configure weback to use these fake decorators instead

**Comment by CodingMadeEasy** [comment]
@19majkel94 Thanks for the response. I have hot reloading setup with webpack so that whenever I make changes to my test file, the test webpage will refresh. It's less tedious than having to run npm test, plus I love the Gui. 

Also I'm going feature driven tests so frontend code and backend code can end up in the spec file. So if there's a way to bundle using webpack that would be awesome.

**Comment by 19majkel94** [comment]
In mocha/jasmine run from console, you can use `--watch` flag - it will listen for changes in test files and re-run the tests.
For TDD you should also use the `min` reporter - it will show only "all test ok" single line or the error from failed test :wink:

**Comment by CodingMadeEasy** [comment]
Thanks for the tip! But what about the Gui? I find it very helpful and pleasant to use. Is that simply not an option?

**Comment by 19majkel94** [comment]
I am using [wallaby.js](https://wallabyjs.com/) for feedback while TDD:

![image](https://wallabyjs.com/assets/img/vscode_inline.gif)

You should look for GUI for Jasmine by yourself - this thread is not a helpdesk.

**Comment by pleerock** [comment]
I guess we can close it. @19majkel94 thank you for help!
