### ISSUE TITLE
How To Export DataSource

### ISSUE THREAD

**Issue by devaku** [typeorm/typeorm#10623]
### What was unclear or otherwise insufficient?

It's established in the documentation: https://typeorm.io/data-source

That good practice in using the DataSource is to export it as it'll allow you to use it across the entirety of your application.

But no example is given how exactly you are to accomplish this.

### Recommended Fix

A simple code snippet on how to properly do this would alleviate this issue.

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by jorenvandeweyer** [comment]
This is basic JS/TS. I don't feel like this should be documented. See the [docs](https://www.typescriptlang.org/docs/handbook/modules/theory.html)

**Comment by papaiatis** [comment]
This SHOULD be documented. 
- How exactly to export the data source? Should it be a default export or should it have a name? 
- How to export multiple data sources and use with the `-d` option of `typeorm`?
- The `initialize` call returns a promise, should I await it or will `typeorm migration:run` will do it for me?

We NEED an example.

**Comment by vardana-bh** [comment]
Hi,

Yes, this needs a proper documentation in case of multiple tenant based data sources, where it can be multiple based on the number of tenants. And passing the dataSource.config to migration:run might not be possible in such scenario.

**Comment by devaku** [comment]
Hi!

I was able to figure out how to export the data source and have it play nice with the CLI. It took some time because the stuff wasn't unfortunately covered in the documentation.

I can do a write up of it if but I'm not sure how to do so. Where do I add the stuff that I was able to find out?
