### ISSUE TITLE
Postgres CREATE INDEX CONCURRENTLY bug

### ISSUE THREAD

**Issue by alexblack** [typeorm/typeorm#10626]
### Issue description

Wrong SQL generated for migration

### Expected Behavior

Migration SQL for a concurrent index should look like:

`CREATE INDEX CONCURRENTLY "IDX_394bb7197c59f2b0924382db09" ON "connection" ("lastAttemptedAt") `
`DROP INDEX CONCURRENTLY "public"."IDX_394bb7197c59f2b0924382db09"`

### Actual Behavior

Incorrect SQL generated

`CREATE CONCURRENTLY INDEX "IDX_394bb7197c59f2b0924382db09" ON "connection" ("lastAttemptedAt") `
`DROP INDEX CONCURRENTLY"public"."IDX_394bb7197c59f2b0924382db09"`

(both statements are invalid)

eg `query failed: CREATE CONCURRENTLY INDEX "IDX_394bb7197c59f2b0924382db09" ON "connection" ("lastAttemptedAt")`

### Steps to reproduce

class Connection {
  @Index({ concurrent: true})
    @Column({ type: 'timestamp with time zone', nullable: true })
  lastAttemptedAt!: Date | null;
}

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   OSX 14.1.1 (23B81)       |
| Node.js version     | 18.18.2  |
| Typescript version  | 5.3.3  |
| TypeORM version     | 0.3.19  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by alenap93** [comment]
@alexblack another problem of concurrent index is that is cannot be created/dropped in transaction, this is a big problem for migration...i can fix the sql statements, but how can we handle this problem?

**Comment by alexblack** [comment]
Hi @alenap93 I was able to resolve that by setting `transaction = false` in the migration itself, and `migrationTransactionMode: 'each'` in data source options

**Comment by alenap93** [comment]
do you want to force `transaction = false` if exist at least one concurrency index?

**Comment by alexblack** [comment]
That is what I'm doing. It won't work otherwise, as far as I know. But the
first step is to generate working SQL I think.
