### ISSUE TITLE
Applying migrations automatically through code

### ISSUE THREAD

**Issue by XT3RM1NATOR** [typeorm/typeorm#10635]
### What was unclear or otherwise insufficient?

Before getting deprecated getConnection method made it possible to get all the migrations and apply them to teh database on startup of the server. However now that datasource is used nowhere in the documentation i could find how to apply migrations with datasource with code. 

### Recommended Fix

Can you either explain to me how to implement automatic migration application with datasource or add it to the documentation 

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by jorenvandeweyer** [comment]
This is clearly documented [here](https://typeorm.io/data-source-options) and [here](https://typeorm.io/data-source-api). 

You're looking for `runMigrations`.

**Comment by alenap93** [comment]
or you can use `synchronize: true` in data source options.

**Comment by jorenvandeweyer** [comment]
You should never use `synchronize: true` in production.

> Indicates if database schema should be auto created on every application launch. Be careful with this option and don't use this in production - otherwise you can lose production data. This option is useful during debug and development. As an alternative to it, you can use CLI and run schema:sync command. Note that for MongoDB database it does not create schema, because MongoDB is schemaless. Instead, it syncs just by creating indices.
