### ISSUE TITLE
Creating two OneToMany relationships onto the same entity

### ISSUE THREAD

**Issue by MahBoy** [typeorm/typeorm#1066]
I want to depict a customer and his/her respective billing and/or shipping addresses as follows:

Currently, my customer entity looks like this
```js
@Entity()
export class Customer {
    @PrimaryGeneratedColumn()
    public id: number;
    @Column()
    public name: string;
    @OneToMany(type => Address, address => address.customer, {cascadeInsert: true, eager: true})
    public billingAddresses: Address[];
    @OneToMany(type => Address, address => address.customer, {cascadeInsert: true, eager: true})
    public shippingAddresses: Address[];
}
```
while my Address entity is
```js
@Entity()
export class Address {
    @PrimaryGeneratedColumn()
    public id: number;
    @Column()
    public street: string;
    @Column()
    public zip: string;
    @Column()
    public city: string;
    @Column()
    public country: string;
    @ManyToOne(type => Customer, customer => customer.billingAddresses)
    @ManyToOne(type => Customer, customer => customer.shippingAddresses)
    public customer: Customer;
}
```

I realize that the method used in my Address entity, where two relationship decorators are bound to one attribute, is likely not the intended implementation. 
Is there any way to implement these relations in this fashion or should I just add another attribute `type` to Address, signaling if it is a billing or an shipping address?

**Comment by pleerock** [comment]
Right, you cannot define models this way, because following code:

```ts
    @ManyToOne(type => Customer, customer => customer.shippingAddresses)
    public customer: Customer;
```

Then ORM does not know what customers need to be set into `billingAddresses: Address[]` property and what customers need to be set into  `shippingAddresses: Address[];` property. Best solution as you said is to create a "type" in the address model.

**Comment by samifall** [comment]
Hi,
I did not get it.
how will you fix this if you introduce type?

**Comment by doub1ejack** [comment]
I just ran into this and mentally stumbled over the same thing.  The trick is just to use different names for both the `billingAddresses` and the `shippingAddresses` relations in the `Address` entity. 

This seems to work fine for me in an analogous scenario:

```javascript
@Entity()
export class Company extends BaseEntity {
  @OneToMany( () => Group, group => group.friendlyCo )
  friendlyGroups: Group;
  @OneToMany( () => Group, group => group.rivalCo )
  rivalGroups: Group;
```

...and in the other relation:

```javascript
@Entity()
export class Group extends BaseEntity {
  @ManyToOne( () => Company, friendlyCo => friendlyCo.friendlyGroups )
  friendlyCo: Company;
  @ManyToOne( () => Company, rivalCo => rivalCo.rivalGroups )
  rivalCo: Company;
```

So I think you would want to do something like this

```javascript
    @ManyToOne(type => Customer, customer => customer.billingAddresses)
    public billingCustomer: Customer;
    @ManyToOne(type => Customer, customer => customer.shippingAddresses)
    public shippingCustomer: Customer;
```

**Comment by iljab** [comment]
I'm facing the same problem, the example of @doub1ejack helped me with the structure. But is it possible to get the relations using Query Builder?

I tried the following based on the example of @doub1ejack:
```js
... .createQueryBuilder('groups')
.leftJoinAndSelect("groups.friendlyCo", "friendlyCo", "friendlyCo.isActive = true")
.leftJoinAndSelect("groups. rivalCo", "rivalCo", "rivalCo.isActive = true")
```
This works as long as i'm not using where statements, if i use where the last join only seems to work (rivalCo).
