### ISSUE TITLE
Couldn't run with db PostgreSQL

### ISSUE THREAD

**Issue by celestale** [typeorm/typeorm#1068]
Hi, I new here. Went through the Quickstart tutorial and trying to test it out with sqlite and PostgreSQL. sqlite works fine but i cant get PostgreSQL to work. Help is appreciated. Thank you!

ormconfig.json
```
{
    "type": "postgres",
    "host": "localhost",
    "port": 5432,
    "username": "test",
    "password": "test",
    "database": "test",
    "synchronize": true,
    "logging": false,
    "entities": [
        "src/entity/**/*.ts"
    ],
    "migrations": [
        "src/migration/**/*.ts"
    ],
    "subscribers": [
        "src/subscriber/**/*.ts"
    ]
}
```

npm start
> { Error: connect ECONNREFUSED 127.0.0.1:5432
>     at Object._errnoException (util.js:1019:11)
>     at _exceptionWithHostPort (util.js:1041:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
>   code: 'ECONNREFUSED',
>   errno: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 5432 }

package.json
```
{
   "name": "MyProject",
   "version": "0.0.1",
   "description": "Awesome project developed with TypeORM.",
   "devDependencies": {
      "ts-node": "3.3.0",
      "@types/node": "^8.0.29",
      "typescript": "2.5.2"
   },
   "dependencies": {
      "pg": "^7.3.0",
      "reflect-metadata": "^0.1.10",
      "typeorm": "0.1.1"
   },
   "scripts": {
      "start": "ts-node src/index.ts"
   }
}
```

**Comment by pleerock** [comment]
`Error: connect ECONNREFUSED 127.0.0.1:5432` error tells only one thing - you don't have postgres installed, or its not running, or its not running on `5432`. Please make sure its running and uses port you have specified.

**Comment by celestale** [comment]
Hi @pleerock, great to receive your reply. I have it installed in my node_modules folder
```
"dependencies": {
      "pg": "^7.3.0",
```
how do I check if its running on `5432`? Because what I did was to install typeorm and npm install then start.

**Comment by pleerock** [comment]
no, I mean `postgres` application. Did you install [postgres application](https://www.postgresql.org/) ? Do you have experience working with databases at all?

**Comment by celestale** [comment]
No, I have not. thanks bro, i will look into the postgres application.

**Comment by liketurbo** [comment]
Check which port runs
https://stackoverflow.com/questions/4421633/who-is-listening-on-a-given-tcp-port-on-mac-os-x

**Comment by kiocosta** [comment]
Since Docker is a virtual machine, you have to use its ip to connect to your database.

If you're using Windows, try the following command in Docker's terminal:
`docker-machine ip`
Use this ip in HOST (in whatever GUI you're using, in my case, postbird) instead of using localhost.

**Comment by FelipeMolinari** [comment]
@kiocosta Valews cara, você salvou meu dia

**Comment by peidrao** [comment]
thank you very much man

**Comment by rtavaresramos** [comment]
Omg, you're amazing! Thanks, I looked so much for a solution, but until now didn't find it anywhere! Thanks, bro!

**Comment by GFBorelli** [comment]
salvou aqui valendo @kiocosta !

**Comment by endepointe** [comment]
> no, I mean `postgres` application. Did you install [postgres application](https://www.postgresql.org/) ? Do you have experience working with databases at all?

Although this is a bit of a rough answer, it tells you what you need to do to fix this issue.

**Comment by mateushnsoares** [comment]
I'm with Postgres running and have the same problem. My ormconfig.json is the same and Postgres is running on docker (docker desktop)
