### ISSUE TITLE
Use Active Record Pattern in JS

### ISSUE THREAD

**Issue by frbender** [typeorm/typeorm#1069]
Hi!
Is there a way to use the active record pattern in JavaScript? I didn't have luck trying to explore that topic by myself...
Best,
Farnz

**Comment by frbender** [comment]
As always: I found the answer right after posting the question.
In case someone else has wondered how to implement the ar-pattern in plain js check out this example: https://github.com/typeorm/javascript-example/tree/master/src/app3-es6

**Comment by lb091188** [comment]
but this example is Data Mapper ~
