### ISSUE TITLE
BUG? - Set default value of enum column produce an error

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#1070]
Enum:
```ts
export enum GiftType {
    NORMAL,
    UNLIMITED,
}
```
Entity definition:
```ts
    @Column("enum", {
        enum: GiftType,
        default: GiftType.NORMAL,
    })
    type: GiftType;
```

error database create sql
```sql
`type` enum('NORMAL', 'UNLIMITED', '0', '1') NOT NULL DEFAULT 0
```

error message
```
Error: Invalid default value for 'type'
```

default value of `enum` must be `string`

**Comment by pleerock** [comment]
No, its not a bug. `default` value isn't always a string - there are cases when you want make it number, boolean, string or function. In your case you are specifying it a number, thats why it generates a number in a default. Of course we can add extra check kinda `if its an enum then always cast to string if its a number but not a function, but Im not really sure if we really need it...`

We'll think about it with @AlexMesser how it will affect things we have, but for now use `default: String(GiftType.NORMAL)`

**Comment by Diluka** [comment]
There has `enum` property in `ColumnOption`. So it can do `String(GiftType.NORMAL)` inner like `options.enum ? String(options.default) : options.default` or other way.

Now I will use `default: String(GiftType.NORMAL)`, thx.
