### ISSUE TITLE
Feature request: @IgnoreColumn decorator

### ISSUE THREAD

**Issue by asvetliakov** [typeorm/typeorm#1071]
Is it possible to introduce property decorator to completely ignore database column in ORM requests (i.e. don't alias it) but don't delete it right now from the schema (by both schema sync/migrations generation)? This is needed for backward compatible schema changes when renaming/deleting column takes 2 release iterations and both staging/production servers are using same DB instance (thus previous version must be able to work with new schema).

Right now, the ORM is aliasing all entity fields in request, so the previous app version will be broken if some column has been gone in the new DB schema, either if it was deprecated and not used in the app.

**Comment by pleerock** [comment]
you can skip column selection this way: `@Column({ select: false })` - does this approach work for you?

**Comment by asvetliakov** [comment]
Yes, this works. Thanks!
