### ISSUE TITLE
[Issue] How to link supabase table using typeorm?

### ISSUE THREAD

**Issue by daydayfish** [typeorm/typeorm#10738]
### Feature Description

-

### The Solution

-

### Considered Alternatives

-

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by jorenvandeweyer** [comment]
Hi @daydayfish 

Besides that I think this is not a good idea to mess with the data coming from another platform. You could theoretically create the entities your self by using the exact same fields that are used by supabase. Make sure to turn off migrations.
