### ISSUE TITLE
passing InstanceName as part of the connection options for MSSQL 

### ISSUE THREAD

**Issue by Ygilany** [typeorm/typeorm#1073]
mssql uses tedious as the default driver for SQL Server. 
tedious uses some extra options than what you're providing such as the instanceName
Which would be required in cases where the instance name isn't SQLEXPRESS

https://github.com/patriksimek/node-mssql#drivers-1

**Comment by pleerock** [comment]
Looks like we don't have this option in the root of connection options, for now you can simply do following:

```ts
{
   type: "mssql",
   host: "...",
   username: "...",
   password: "...",
   extra: { "instanceName": "..." }
}
```

**Comment by Ygilany** [comment]
@pleerock Thanks
