### ISSUE TITLE
How to translate this query into find options?

### ISSUE THREAD

**Issue by GabrielHK97** [typeorm/typeorm#10741]
### What was unclear or otherwise insufficient?

In this [documentation](https://orkhan.gitbook.io/typeorm/docs/find-options), I have an interesting example:
`userRepository.find({
    where: [
        { firstName: "Timber", lastName: "Saw" },
        { firstName: "Stan", lastName: "Lee" },
    ],
})`
equals to
`SELECT * FROM "user" WHERE ("firstName" = 'Timber' AND "lastName" = 'Saw') OR ("firstName" = 'Stan' AND "lastName" = 'Lee')`

but how can i do the following:
`SELECT * FROM "user" WHERE ("firstName" = 'Timber' OR "lastName" = 'Saw') AND ("firstName" = 'Stan' OR "lastName" = 'Lee')`

### Recommended Fix

add another example

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by jorenvandeweyer** [comment]
Hi @GabrielHK97 

I'm not sure why you would want to do that query. But you should look into [the query builder](https://typeorm.io/select-query-builder). 

```ts
createQueryBuilder("user")
    .where("user.registered = :registered", { registered: true })
    .andWhere(
        new Brackets((qb) => {
            qb.where("user.firstName = :firstName", {
                firstName: "Timber",
            }).orWhere("user.lastName = :lastName", { lastName: "Saw" })
        }),
    )
```

**Comment by GabrielHK97** [comment]
Thanks but I dont want to use the query builder. I specifically want to use the find options, because im building a plugin that relies on it. Can you take a second look?
