### ISSUE TITLE
BugFix: cascade: true => Duplicate entry for key 'inventory.PRIMARY' on Update using .save()

### ISSUE THREAD

**Issue by franklinz-pluriza** [typeorm/typeorm#10755]
## Issue Description:

**Description:**
When attempting to update a child entity with a one-to-one relationship set to `cascade=true` using TypeORM, an exception occurs: `"Duplicate entry for key 'inventory.PRIMARY'"`, it's important to mention that the insert (cascade) is working ok, the issue starts when trying to update existing entities.

**Example Code:**
```typescript
// Parent Entity
@PrimaryColumn()
@OneToOne(() => InventoryEntity, inventory => inventory.variant_id, { cascade: true, eager: true })

// Child Entity
@PrimaryColumn()
@OneToOne(() => ProductVariantEntity)
@JoinColumn({ name: 'variant_id' })

*This also happens with @OneToMany() and other types of relations*
```

**Issue Analysis:**
Upon reviewing the codebase, it was discovered that the exception arises due to a mismatch in entity mapping during the update process. This occurs because the ORM package attempts to match the subjects with the fetched entities but fails to do so. The root cause lies in the handling of the entity's relation ID, where the disableMixMap field is correctly configured as true. However, a negation condition prevents the ID from being flattened, leading to the failed matching process. Consequently, the ORM erroneously attempts to insert a new entry instead of performing an update, triggering the mentioned error.

**Proposed Solution:**
To resolve this issue, the condition in the `RawSqlResultsToEntityTransformer.ts` file at `src/query-builder/transformer` needs to be updated. Specifically, modify the condition on line `619/620` from:

```typescript
if (
    columns.length === 1 &&
    !rawRelationIdResult.relationIdAttribute.disableMixedMap
) {
```

to:

```typescript
if (
    columns.length === 1 &&
    rawRelationIdResult.relationIdAttribute.disableMixedMap
) {
```
(Note the removed `!`)

This adjustment ensures proper handling of entity matching and resolves the error. This solution has been tested successfully.

(Note: The fix could not be directly submitted due to insufficient permissions on the repository.)

> If the identified behavior is intentional and I am using the ORM incorrectly, I would appreciate guidance on how to solve this problem correctly.

**Comment by jcrben** [comment]
@franklinz-pluriza curious as to what you originally learned here to decide on not planned??

**Comment by franklinz-pluriza** [comment]
> @franklinz-pluriza curious as to what you originally learned here to decide on not planned??

I created a new issue documenting the problem in a better and attached the PR with the fix. See [#10758](https://github.com/typeorm/typeorm/issues/10758)
