### ISSUE TITLE
Unhandled promise rejection, (rejection id: 2): DriverPackageNotInstalledError

### ISSUE THREAD

**Issue by celestale** [typeorm/typeorm#1077]
```
(node:4164) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
(node:4164) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Electron/index.ts
```
import 'reflect-metadata';
import { User } from './entity/User';
import { createConnections } from 'typeorm';
import { getConnection } from 'typeorm';

...
...
...

async function start() {
  const connections = await createConnections([{
    name: 'lite',
    type: 'sqlite',
    host: 'localhost',
    port: 3306,
    username: 'test',
    password: 'test',
    database: 'test',
    synchronize: true,
    logging: false,
    entities: [
      'src/entity/**/*.ts'
    ],
    migrations: [
      'src/migration/**/*.ts'
    ],
    subscribers: [
      'src/subscriber/**/*.ts'
    ]
...
...
  }]);
...
...
```

I tried to run this code inside my Electron application. Installed `npm install sqlite3 --save`. Checked that `sqlite3 `folder is inside `node_modules`. I have no idea on why the application is complaining SQLite package not installed? I tested the same code with TypeORM CLI commands to generate a starter project and it works fine. Is running TypeORM in an Electron app supported?

**Comment by ericdesa** [comment]
Hello @celestale, I have the same issue.
I think i've missed a point on the driver setup. 
Did you manage to use TypeORM with Electron?

**Comment by celestale** [comment]
@ericdesa unfortunately, no resolution. Hence I am not working on this anymore.

**Comment by pleerock** [comment]
We will need to create an example repo how to use electron + typeorm

**Comment by ericdesa** [comment]
In my case, the problem was with webpack / ionic, not typeorm.
I'm not really sure about this workaround, but i hope it can help whoever finds this issue :

- add sqlite3 in the dependencies
- override the webpack config with this :

```
const webpackConfig = require('../node_modules/@ionic/app-scripts/config/webpack.config');

externals = ['sqlite3', 'fs', 'path', 'mkdirp']

webpackConfig.dev.externals = externals;
webpackConfig.prod.externals = externals;
```
- load the webpack config with this key in the package.json:
```
"config": {
    "ionic_webpack": "./config/webpack.config.js"
}
```
- in index.html, add this script :
```
<script>
    const sqlite3 = require("sqlite3");
    const fs = require("fs");
    const path = require("path");
    const mkdirp = require("mkdirp");
</script>
```
