### ISSUE TITLE
I have never seen one doc sucks like fucking typeorm.io（我从来没见过比typeorm更烂的文档）

### ISSUE THREAD

**Issue by milobluebell** [typeorm/typeorm#10782]
💩💩💩

### What was unclear or otherwise insufficient?

I even cannot search any api on `https://typeorm.io/`，for a very long time.I had a bad enough!

You just try search "upsert" on algolia, Changelog was the top one, and a keyword matched on "Documentation" part because of it matched "rowid - only for [CockroachDB](https://www.cockroachlabs.com/docs/stable/serial.html). Value is automatically generated using the unique_rowid() function. This produces a 64-bit integer from the current timestamp and ID of the node executing the INSERT or `UPSERT` operation. > Note: property with a rowid generation strategy must be a string data type"

What the fuck is that??

### Recommended Fix

Search 'upsert' (for example), it should lead to here: `https://typeorm.io/entity-manager-api` , instead of `https://typeorm.io/changelog#features-6`

### Additional Context

Nope

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by pleerock** [comment]
That's sad. No need to swear, dear.
