### ISSUE TITLE
Transactions on WebSql

### ISSUE THREAD

**Issue by jondediego** [typeorm/typeorm#1081]
Should transactions on WebSql work? We are making a test with an Ionic app. Transactions work on Android device and SQlite database but don't work for browser and WebSQL. On WebSQL when there is an error, no rollback is done.
Example of code: 
```typescript
await maintenanceRepository.entityManager.transaction(async entityManagerTx => {
    entityManagerTx.save(currentMaintenance); // Insert OK
    entityManagerTx.save(maintenanceFormValues); // This should fail and rollback
});
```

The maintenanceFormValue.save is modified in order to generate an error. Despite of that, current maintenance is persisted and maintenances are inserted in database for WebSQL.

**Comment by jondediego** [comment]
I don't understand deeply the code of typeorm, but after looking to websql driver code, perhaps, in order to manage transactions for websql, it could be a good idea to integrate this plugin:https://github.com/brodybits/sql-promise-helper, that let you create transactions in a promise structure. What do you think?

**Comment by pleerock** [comment]
```ts
await maintenanceRepository.entityManager.transaction(async entityManagerTx => { 
    await entityManagerTx.save(currentMaintenance); // Insert OK 
    await entityManagerTx.save(maintenanceFormValues); // This should fail and rollback
});
```

"This should fail and rollback" MUST BE executed. You forgot to await operations in your callback.

**Comment by jondediego** [comment]
I forgot await while writing the issue, but in the tests I made, await was used. Despite of that, no rollback was done.

**Comment by pleerock** [comment]
can you please create a failing test with reproduction of this problem?

**Comment by jondediego** [comment]
Hi, here is an Ionic example test using WebSql. In order to test it, you have to install ionic cli and execute "ionic serve" command. As I am using syncrhonize:true option, each time you reload the page you need to delete websql database through chrome developer tools.
[transactionsfail.zip](https://github.com/typeorm/typeorm/files/1435257/transactionsfail.zip)

On the other hand, I think WebSqlQueryRunner.ts file, doesn't initialize transactions neither rollback them. There are also some todo comments about that in the file. I think that could be because it is difficult to addapt websql api to typeorm websqlqueryrunner. WebSql API needs something like this code in order to execute some sql:
 `db.transaction((tx: any) => {
        tx.executeSql(query, parameters, (tx: any, result: any) => {....},}, (tx: any, err: any) => {});
  });
`               
So, ussually, sqls executed must be inside a callback function at the function that creates the transaction. If I am right the transaction created object (tx in this case) is destroyed once callback function is finnished. I think that is difficult to addapt to typeorm code, where transactions are created at some point and query/insert function is called at some other point.

I tried to implement this cordova plugin: https://github.com/brodybits/sql-promise-helper, at WebSQLQueryRunner.ts. This cordova plugin allows to create a transaction in a promise based way, and then make sqls for this transaction whenever you want. The problem is that sqls are actually executed once you call commit method, so I wasn't able to return results from "query" or "insert" WebsqlQueryRunner methods, because results were obtained at commitTransaction.
 Here is my attempt in case you think it could be useful:
[websqlAttempt.zip](https://github.com/typeorm/typeorm/files/1435325/websqlAttempt.zip)

On the other hand I think that if we could achieve a way to manage transactions for websql, instead of creating a new transaction for each query or insert, performance would be greatly increased. The same performance improvement would be present for cordova driver, because, if I am not wrong, currently it also creates a new transaction for each query/insert.

**Comment by pleerock** [comment]
@daniel-lang can you please help on this topic

**Comment by pleerock** [comment]
@jondediego  did you find solution for your issue?

**Comment by daniel-lang** [comment]
I guess, that if we want to keep the websql driver, we have to improve it. The current status isn't really helping anyone.

**Comment by pleerock** [comment]
Agree.

**Comment by jondediego** [comment]
I think it would be great if you could keep websql driver in order to test Ionic/cordova applications on browser (even if transactions don’t work). Otherwise, Ionic applications would only run on device.

**Comment by pleerock** [comment]
as discussed in #1923 we drop websql support in favour of sql.js
