### ISSUE TITLE
BUG? - Update using Repository.createQueryBuilder

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#1084]
`Repository.createQueryBuilder` must pass a string as alias but update sql doesn't declare alias.

```ts
        await giftRepository.createQueryBuilder("g")
            .update()
            .set({"used": () => "used + 1"})
            .where("g.id = :id", {id: gift.id})
            .execute();
```

```sql
UPDATE `G0002_Gift` SET `used` = used + 1 WHERE g.id = ?
```

`Error: Unknown column 'g.id' in 'where clause'`

**Comment by pleerock** [comment]
in delete/update/insert query builders you don't need to use aliases, e.g. replace `g.id` to simply `id`

**Comment by Diluka** [comment]
If `await giftRepository.createQueryBuilder()` compiler tells me there must be 1 parameter

**Comment by Diluka** [comment]
Any update? @pleerock 
Is there a typing error or I should not use `Repository.createQueryBuilder` to update?

`Repository.createQueryBuilder` need at least 1 parameter

**Comment by pleerock** [comment]
maybe we can make alias argument optional in repository too
