### ISSUE TITLE
Add support for ParadeDB Postgres

### ISSUE THREAD

**Issue by philippemnoel** [typeorm/typeorm#10841]
### Feature Description

ParadeDB offers full-text search in Postgres via a Postgres extension called `pg_search` and offers real-time analytics via an extension called `pg_analytics`: https://github.com/paradedb/paradedb

Adding support for creating pg_search indexes, for example, via TypeORM would allow users who use those extensions to continue building their applications with TypeORM.

### The Solution

I am not fully familiar with how TypeORM to propose a direct solution, but I know the folks at Drizzle are implementing an "extension API".

### Considered Alternatives

N/A

### Additional Context

My team and I at ParadeDB are happy to be of help in the implementation

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time, but I can support (using donations) development.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
