### ISSUE TITLE
format code

### ISSUE THREAD

**Issue by sinkhaha** [typeorm/typeorm#10899]
### Feature Description

 run the `npm run format` to format the code

### The Solution

npm run format

### Considered Alternatives

no

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by stim371** [comment]
It looks like this got cleaned up. When I run `npm run format` locally, no changes are generated. Thanks for reporting and helping clean up the repo!
