### ISSUE TITLE
findByIds is missing aliases in where clause

### ISSUE THREAD

**Issue by apezel** [typeorm/typeorm#109]
findByIds seems to ignore provided alias in findOptions : 

```
(id=? OR id=? OR id=? OR id=? OR id=? OR id=?)
```

```
 Error: ER_NON_UNIQ_ERROR: Column id in where clause is ambiguous
```

This is a problem when there is a joined table.

I'm using @next

**Comment by pleerock** [comment]
I remember I already fixed that. Maybe not published... Just published `0.0.3-alpha.17` in the `next`. Can you try again there?

**Comment by apezel** [comment]
It works perfectly, thanks

**Comment by S1ri0S** [comment]
The same thing seems to be happening with single-table inheritance entities.
I have 2 single-table inheritance entities with several subclasses for each one and they use the same DiscriminatorColumn name ('dtype'). When i fetch-join entities of one type that are contained in the other I get the followiing error:
`ER_NON_UNIQ_ERROR: Column 'dtype' in where clause is ambiguous`

P.S This ORM is great work. Keep up!
