### ISSUE TITLE
Simple-array column type for numbers.

### ISSUE THREAD

**Issue by jcudzich** [typeorm/typeorm#1092]
Hi,

in my case, I found an use for simple-array but I need an array of numbers insted of a strings.
What do you think stored simple-array type in JSON format? It would help to distinguish string from numbers. Maybe the metadata reflection would help here.

**Comment by pleerock** [comment]
metadata reflection won't help - it does not reflect types of arrays. So we would need to add an extra property where we specify type of simple array. Not really sure if we need to complicate things with simple-array

**Comment by jcudzich** [comment]
@pleerock I design my api to make the resources predictable, so I will use another mechanism. I think about listeners but I don't want hacks that just parse string to numbers in request.

Thanks a lot for quick reply.
