### ISSUE TITLE
EntityMetadataNotFoundError: No metadata for "Entity" was found.

### ISSUE THREAD

**Issue by MyNameIsNeXTSTEP** [typeorm/typeorm#10942]
### Issue description

Connecting typeorm entities to the dataSource with ESbuild and typescript

### Expected Behavior

The connected entities to a DataSource are treated  correctly and has appropriate metadata in builded classes.

### Actual Behavior

When building with ESbuild, **esbuildPluginTsc** from "esbuild-plugin-tsc", enabled decorators flags in the server tsconfig.json for the entity:
```javascript
import 'reflect-metadata';
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
} from 'typeorm';

@Entity()
export class Common {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'varchar', nullable: false })
  name: string;
}
```

Got builded server code:
```javascript
...
    Object.defineProperty(exports2, "__esModule", { value: true }); exports2.Common = void 0;
    require("reflect-metadata");
    var typeorm_1 = require("typeorm");
    var Common2 = class Common {
    };
    __decorate([
      (0, typeorm_1.PrimaryGeneratedColumn)("uuid")
    ], Common2.prototype, "id", void 0);
    __decorate([
      (0, typeorm_1.Column)({ type: "varchar", nullable: false })
    ], Common2.prototype, "name", void 0);
    Common2 = __decorate([
      (0, typeorm_1.Entity)()
    ], Common2);
    exports2.Common = Common2;
```

The build has been processed correctly, the entity class is created and wrapped with decorator, but after the DB initialization the actual problem is that the created "Common" named entity does not have metadata, which the typeorm code need for something:
```
EntityMetadataNotFoundError: No metadata for "Common" was found. at DataSource.getMetadata (/node_modules/typeorm/data-source/DataSource.js:304:19) although the exports2.Common class is present and log shows it.
```

### Steps to reproduce

1. Have ESbuild as the build tool
2. Installed packages:
- "reflect-metadata"
- "typeorm"
- "esbuild-plugin-tsc"
3. Installed and configured connection to the working database *(in the case of the author its PostgreSQL 16)*
DB init file:
```javascript
import 'reflect-metadata';
import { Common } from '@entity/common-entity'; // my alias for entity, imported correctly though
import { DataSource } from 'typeorm';

const myDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST,
  port: parseInt(process.env.DB_PORT || '5432'),
  username: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  entities: [Common],
  logging: true,
  synchronize: true,
});

export const init = async () => {
  myDataSource
    .initialize()
    .then(async () => {
      logger.info('Data Source has been initialized!');
    })
    .catch((err) => {
      logger.error(
        'Error during Data Source initialization:\n',
        err.message,
        err.stack
      );
    });

  const commonRepository = myDataSource.getRepository(Common);
  const newCommon = new Common();
  newCommon.name = 'new user';
  await commonRepository.save(newCommon);
  await myDataSource.destroy();
};
```
4. Have the ESbuild ocnfig like so:
```javascript
import * as esbuild from 'esbuild';

const config = {
    entryPoints: ['server.js'],
    bundle: true,
    outdir,
    platform: 'node',
    packages: 'external',
    external: ['uuid'],
    plugins: [
      esbuildPluginTsc({
        force: true
      }),
   ...], // other static files configs
  ...options,
}

await esbuild.build(config);
```
5. Also the tsconfig.json configured right, meaning it has enabled decorators flags:
- "emitDecoratorMetadata": true,
- "experimentalDecorators": true,
6. Have the testing entity:
```javascript
import 'reflect-metadata';
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
} from 'typeorm';

@Entity()
export class Common {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'varchar', nullable: false })
  name: string;
}
```
7. Make a build, check the builded server file for the presence of "Common" testing entity to be initialized and decorated as class with necessary fields *(in the case of the author its: id, name)*
8. Run the server

### My Environment

| reflect-metadata          | ^0.2.2 |
| esbuild-plugin-tsc                | ^0.4.0      |
| MacOS (OSX) Sonoma  | 14.4.1          |
| Node.js version     | 18  |
| Typescript version  | 4.7.4  |
| TypeORM version     | ^0.3.20  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by MyNameIsNeXTSTEP** [comment]
Also doubled the issue on the [stackoverflow](https://stackoverflow.com/questions/78652553/esbuild-with-typescript-connecting-typeorm-entities-to-the-datasource)

**Comment by MyNameIsNeXTSTEP** [comment]
Running the actual Entity creation and DB init straight with ts-node also give that error, so i assume it's not the build problem, but actual ts + typeorm + ts-node issue

**Comment by Enough7** [comment]
For people who do not have the ability for a top level await, you can use this.

Fix (Thanks to MyNameIsNeXTSTEP):
```TypeScript

export const init = async () => {
   await AppDataSource
        .initialize()
        .then(async () => {
            console.info('Data Source has been initialized!');
        })
        .catch((err) => {
            console.error(
                'Error during Data Source initialization:\n',
                err.message,
                err.stack
            );
        });

    console.log("Starting Database initialisation ...!")
    const userRepo: Repository<User> = AppDataSource.getRepository(User)
    const user: User = new User();
    user.nickname = "TestUser";
    user.tag = "123";
    await userRepo.insert(user);
    console.log("Data Source has been initialized!")
};
```

Call `init` in `app.ts` like this:
```TypeScript
[...]
import {AppDataSource, init} from "./Database/data-source";
[...]
(async () => await init())()
[...]
```
