### ISSUE TITLE
Does anyone want to refactor the repository?

### ISSUE THREAD

**Issue by 0x0bit** [typeorm/typeorm#10981]
Does anyone want to refactor the repository?

**Comment by giosueDelgado** [comment]
Hi  @MrYbo this is a very importat task that I think we will discuss all together with the team:
https://github.com/typeorm/typeorm/issues/3267#issuecomment-2228099642

**Comment by stim371** [comment]
Discussions moving forward in the Discord. https://discord.gg/cC9hkmUgNa
