### ISSUE TITLE
BUG - QueryBuilder MySQL skip sql is wrong

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#1099]
I set `skip(20)` then generate a wrong sql
```sql
SELECT DISTINCT `distinctAlias`.`ta_id` as "ids_ta_id"  FROM (SELECT `ta`.`id` AS `ta_id` FROM `TourArticle` `ta`) `distinctAlias` ORDER BY `ta_id` ASC OFFSET 20
```
Error:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OFFSET 20' at line 1
```

**Comment by pleerock** [comment]
can you please create a PR with a test for this issue?

**Comment by pleerock** [comment]
Okay so answer to this issue is [here](https://stackoverflow.com/questions/255517/mysql-offset-infinite-rows). You cannot have offset in the mysql without limit applied. And as I remember its not only mysql limitation. So you have to use `take` in conjunction with `skip`.

**Comment by pleerock** [comment]
I made a small change - now query runner will throw `OffsetWithoutLimitNotSupportedError` error for mysql driver when user uses skip without offset and updated your test.
