### ISSUE TITLE
Feature Request - simple condition support operators

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#1101]
Now simple condition can only use **equivalence match**(`=`), but in actual situation, often use operators like `>`, `<`,`<>`,`LIKE`,`NOT LIKE`, `BETWEEN` and `IN`.

Makes repository methods like `findOne` be more useful in actual situation.

`TypeORM` may be can learn from `Sequlize` http://docs.sequelizejs.com/manual/tutorial/querying.html#operators

**Comment by pleerock** [comment]
Here is what I have in mind for basic implementation of this feature:

```
repository.find({
      count1: LessThen(5), // < operator
      count2: MoreThen(10), // > operator
      name: Equal("Hello"),
      title: Not(Equal("Buy")),
      description1: Like("%AAA%BBB%"),
      description2: Not(Like("%ADAD_A")),
      date1: Between("yesterday", "today"),
      date2: Not(Between("yesterday", "today")),
      type1: In("a", "b", "c", d"),
      type1: Not(In("a", "b", "c", d")),
      array1: Any(["a", "b", "c", d"]),
      type1: Not(In("a", "b", "c", d")),
});
```

**Comment by EreckGordon** [comment]
Sorry to be a sticker -- you want to use `LessThan` and `MoreThan` (or `GreaterThan`) with an a rather than then with an e.

**Comment by pleerock** [comment]
Thanks for the correction, I always confuse `then` and than` :confused:

**Comment by pleerock** [comment]
guys please don't hesitate to add more requests

**Comment by 19majkel94** [comment]
>Here is what I have in mind for basic implementation of this feature:
```ts
repository.find({
      count1: LessThen(5), // < operator
      count2: MoreThen(10), // > operator
      name: Equal("Hello"),
      title: Not(Equal("Buy")),
      description1: Like("%AAA%BBB%"),
      description2: Not(Like("%ADAD_A")),
      date1: Between("yesterday", "today"),
      date2: Not(Between("yesterday", "today")),
      type1: In("a", "b", "c", d"),
      type1: Not(In("a", "b", "c", d")),
      array1: Any(["a", "b", "c", d"]),
      type1: Not(In("a", "b", "c", d")),
});
```
For me it looks awfull 😖 SQL is nice language but for object-like queries the mongo operators are much better than `Not(Equal("Buy")),`:

```ts
repository.find({
    count1: { $lt: 5 }, // < operator
    count2: { $gt: 10 }, // > operator
    count4: { $lte: 5, $gte: 10 }, // multiple conditions, eg. ranges
    name: { $eq: "Hello" },
    title: { $ne: "Buy" },
    type1: { $in: ["a", "b", "c", "d"] },
    type2: { $nin: ["a", "b", "c", "d"] },
});
```
Of course for sql keywords we have  to define new shortcut operators like `$like` instead of mongo `$regex` but the idea is to use object instead of calling(calling(calling(functions(witArgs)))) 😉

**Comment by pleerock** [comment]
thanks @19majkel94 for your contribution on this question. Few of my honest points: 

* personally I really dislike `count1: { $lt: 5 } ` syntax despite being javascript-ish. I prefer `count1: LessThen(5)` syntax much more.
* i really don't like mongodb-style querying. For all the time working with complex mongodb queries I really started to hate them because more they complex much more harder to read and maintain them. Thats why I would like to avoid this { $and: { $or } } form and left complex queries to be build by query builder instead. I would like to keep `find` methods as simple as possible.
* `calling(calling(calling(functions(withArgs)))) ` - no we won't have it. Not is the only operator I think about. Also we can avoid using Not at all - we can create more classes for all operators which support not, e.g. instead of `Not(Equal())` create a single `NotEqual()` which look much better.

**Comment by EreckGordon** [comment]
+1 to real words, -1 to abbreviations

**Comment by soncodi** [comment]
To me, it's personal preference; abbreviated forms like `$lt`, `$gt` are less verbose and make it easier to visually parse nested `and`/`or` conditionals.

Perhaps the strongest argument in their favor is they translate more naturally to Mongo queries, and make transitioning from e.g. Sequelize easier, which may help TypeORM gain more market share.

That being said, perhaps both syntaxes could be supported.

**Comment by pleerock** [comment]
@soncodi thank you for the feedback. Few points

* no nested and/or conditions are planned to support
* to make transitioning from e.g. Sequelize I could make hundred of awkward things Sequelize has and their users adapted to, but I won't do it
* both syntaxes isn't a good idea, it just brings more confusion

More community feedback is appreciated!

**Comment by soncodi** [comment]
Are you referring to not supporting queries with nested predicates of the form `(A && B) || (C && D)`? Will you also not support those in Mongodb queries?

**Comment by pleerock** [comment]
mongodb has such support, you can pass "query" whatever mongodb itself supports. Im talking about building sql query.

**Comment by soncodi** [comment]
What is the preferred approach for building nested query conditions (also interested in type inference support), such as
```sql
SELECT id
FROM Users 
WHERE (age > 21 && age <= 35) || (age > 35 && age <= 50);
```

**Comment by pleerock** [comment]
right query builder is preferred approach especially for complex queries and yes its string-based, it I don't think it will be ever possible to make it type-safe due to sql flexibility and complexity

**Comment by pleerock** [comment]
Contributions are welcomed on this feature request btw.

**Comment by 19majkel94** [comment]
@pleerock 
Functions like `LessThan(5)` need to return some token that the `find()` method will understand and translate to sql query string. So we might have both syntax supported - calling `LessThen(5)` will be translated to `{ $lt: 5 }`. $-based tokens are easy to parse so in this way people can build simple queries by
```ts
repository.find({
  prop: LessThen(5),
}
```
And by:
```ts
repository.find({
  prop: { $lt: 5 },
}
```
> +1 to real words, -1 to abbreviations

The tokens might be real world, maybe it would be better to support `$lessThan` to don't confuse with mongo query-like support.

**Comment by pleerock** [comment]
> The tokens might be real world, maybe it would be better to support $lessThan to don't confuse with mongo query-like support.

mongo in a aways is different then rdbms drivers so this won't really change things. And btw its not rdbms drivers confuses things, but mongo does.

I don't think we'll have both ways of doing things, only one way.

> $-based tokens are easy to parse so in this way people can build simple queries by

its not true especially having fact that we can do following queries:

```ts
repository.find({
  author: { id: 1 } // or real author object where author is a relation
}
```

and 

```ts
repository.find({
  counters: { likes: 5 } // where counters is an embedded object
}
```

**Comment by keyiis** [comment]
It's a question worth considering.
1、for simple select/update/delete, I would like to support `$in,$lt,$le,$and,$or...`.because query condtion can saved as json,it's very important for my project!
2、for complex select/update/delete,raw sql query always best choice.

**Comment by 19majkel94** [comment]
> its not true especially having fact that we can do following queries:

Yes, and that's why the operators have `$` prefix to cope with this situation 😉 So you can distinguish whether it's a nested field or operator and throw error that you can do `lessThan` on object/relation, only on the leaf field.

**Comment by pleerock** [comment]
this feature is opened for contributions btw

**Comment by exports** [comment]
Any update on this?

**Comment by muyu66** [comment]
When can our community implement this milestones ?

**Comment by pleerock** [comment]
you are part of community 😆

**Comment by spacemeowx2** [comment]
What about this
```js
function LessThen(p) {
  return { '$lt': p }
}
function Not(p) {
  ... // do something like change '$lt' to '$ge'
}
```

**Comment by mscharley** [comment]
Also worth thinking about how to tackle `IS NOT NULL` (i assume `IS NULL` is tackled by `null` in the property, if not then that could also fit into this.

**Comment by pleerock** [comment]
Added `IsNull` AND `Not(IsNull())` examples

**Comment by pleerock** [comment]
Feature is finally released in `typeorm@0.2.0-alpha.37`, examples are in #1846

**Comment by darkbasic** [comment]
Mongo driver v3 and simple condition support operators in just one day, wow :)

**Comment by pleerock** [comment]
Lot of features were fixed in last few days actually 💯

**Comment by oussaki** [comment]
why it's difficult to implement a '  like ' operator for mongoDB ? couldn't find something like that.
