### ISSUE TITLE
add pglite as datasource

### ISSUE THREAD

**Issue by karlismelderis-mckinsey** [typeorm/typeorm#11026]
### Feature Description

Please consider adding [pglite](pglite.dev) as valid data source

it would be great addition and would help to run test against real postgres like DB

### The Solution

add new datasource, not sure if there is anything else to add ;)

### Considered Alternatives

I'm not sure there is any option to work around missing data source 🤔

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
