### ISSUE TITLE
Bug in CLI SQLite Starter project

### ISSUE THREAD

**Issue by VRspace4** [typeorm/typeorm#1102]
The `ormconfig.json ` file generated from a CLI SQLite Starter project, `typeorm init --name MyProject --database sqlite`, is missing the `type: "sqlite"` field. I had to add it in manually otherwise it would produce the following error message:

> name: 'MissingDriverError',
> message: 'Wrong driver undefined given. Supported drivers are: "cordova", "mysql", "postgres", "mssql", "oracle", "mariadb", "sqlite"

**Comment by pleerock** [comment]
thank you for your report, it was already fixed and will be released in `0.1.2` very soon
