### ISSUE TITLE
Subscriber don't work with builder insert

### ISSUE THREAD

**Issue by VagnerSilva** [typeorm/typeorm#1104]
When I use ... 
```ts
getConnection()
                .createQueryBuilder()
                .insert()
                .into(User)
                .values(user)
                .execute()

```
inserts but the subscriber is not called

But when I use save () there are no problems

**Comment by pleerock** [comment]
I have released a first alpha version of 0.2.0, you can install it via `npm i typeorm@next` and try if it fixes your issue. Please let me know if its not.
