### ISSUE TITLE
Commercial support for adding a new database

### ISSUE THREAD

**Issue by eyallotanRegatta** [typeorm/typeorm#11053]
### Feature Description

I am reaching out because we are interested in adding support for TypeORM as part of our connectivity options for our database. We would like to explore the option of joining the TypeORM project with the help of the community. 
eyal.lotan@regatta.dev

### The Solution

An integration of a new database with the TypeORM project.

### Considered Alternatives

Not relevant for this matter

### Additional Context

We would be happy to explore the commercial support options

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time, but I can support (using donations) development.

**Comment by stim371** [comment]
Thank you for the request, @eyallotanRegatta.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
