### ISSUE TITLE
Is TypeORM project ALIVE? Or DEAD / STALE? It's been stale for ~8 months, and last few years very slow! Lets discuss

### ISSUE THREAD

**Issue by anodynos** [typeorm/typeorm#11079]
Unfortunately, it seems that this amazing project is stale, or even dead in the water (in terms of future development).

Lets discuss, politely and constructively. 

Background: https://github.com/typeorm/typeorm/issues/3267

## Question 1: is TypeORM Project Alive & Kicking?

It's been stale for ~8 months (0 commits), and last few years have been very slow. 
There are many serious issues & PRs that are unsolved, unlooked even, and no roadmap AFAIK.
The current holders, including Relybytes and @pleerock seem distant... the Discord channel looks deserted. 
What's gonna happen? Can we trust TypeORM or should we look elsewhere for new projects?

https://github.com/typeorm/typeorm/graphs/contributors?from=9%2F23%2F2023

![image](https://github.com/user-attachments/assets/549c6144-38d7-4ce2-9f23-717550696200)

![image](https://github.com/user-attachments/assets/4e983feb-a2c4-4d29-b48a-d924e4ceb8cf)

## Question 2: Since it is probably dead (or stale), any takers? 

Does anybody want to take this project on? Adopt it? Any company with same spare good devs? All it takes is a handful (or even 1) great main contributors, to work semi-or-full time, and also harvest the community's contributions.

**Comment by peteAhn** [comment]
FYI.
https://github.com/typeorm/typeorm/issues/3267#issuecomment-2228099642

**Comment by perfringis** [comment]
Any update @pleerock @AlexMesser & @giosueDelgado ?

**Comment by pleerock** [comment]
everything was discussed in #3267. Since Relybytes took initiative to improve TypeORM maintenance state, let's  wait @giosueDelgado to answer.

**Comment by pleerock** [comment]
Closing in favor of #3267
