### ISSUE TITLE
Ionic performance  on WebSQL and Cordova

### ISSUE THREAD

**Issue by jondediego** [typeorm/typeorm#1109]
I am making a test inserting 1000 rows in a simple table in database with no relations. When I insert this rows in database through rough SQL it takes about 1.5 seconds. If I insert 1000 rows using save typeorm method, it takes about 50 seconds.
Performance is similar if  I use WebSQL on browser or SQLite on an Android device.
Is there a reason for this performance?
I attach a sample project so you can test it.
[testPerformance.zip](https://github.com/typeorm/typeorm/files/1423732/testPerformance.zip)

**Comment by jondediego** [comment]
I think the reason for this slow performance could be due to the fact that a new transaction is created for each save method instead of creating a unique transaction for saving each entity. Do you know if there is a way to solve that? I know that cordova sqlite plugin doesn't recommend using it's deprecated methods  db.transaction(function(tx) {
    tx.executeSql();
});
But I don't know if there is a way to use new method db.executeSql() with an existing transaction instead of creating a new one, or if typeorm cordova driver could be addapted in order to use db.sqlBatch().

**Comment by pleerock** [comment]
Im working on persistence refactoring and implemented lot of improvements. Once I release first 0.2.0 beta version we can check your app performance again.

**Comment by pleerock** [comment]
if you track #1115 I made lot of enhacements in recent 0.2.0 alpha versions of typeorm. Are you able to check your issues with newer versions?

**Comment by pleerock** [comment]
Closing as no answer from reporter.
