### ISSUE TITLE
Mongo: Storying refs inside document

### ISSUE THREAD

**Issue by 19majkel94** [typeorm/typeorm#1112]
Since we don't have support for relations in mongo (#1038), is there an option to story refs (ObjectIDs) to other documents inside a document?

For single refs there is a workaround using `@ManyToOne` which stores `ObjectID` inside `xxxId` document's property. 

But what about array of refs? This is a common case in mongo world as this pattern allow you to easily query and filter documents without many-to-many relations and joins.

I've tried:
```ts
@Column()
posts: ObjectID[]
```
And it works but I miss the lack of opportunity to save relation with standard API:
```ts
const posts = await Post.find({ name: "19majkel94" });
user.posts = posts;
await User.save(user);
```
rather than mapping the object array to ids. It helps with typesafe because you can't assign id of object from wrong collection.

I've even tried using entity listeners to dynamically map it but it won't save it in db when I use `type` option:
```ts
@Column(type => ObjectId)
posts: Post[]
```

Mongoose and TS overlays like Typegoose support this pattern:
https://github.com/szokodiakos/typegoose#arraypropoptions

And it would be nice to have something like `@Ref()` and `@Refs()` until we have full support for relations in mongo. But even if, the array of refs pattern is also needed for mongo devs:
```ts
type Ref<T> = T | string | ObjectId;

class User {
    
    @Ref(type => UserType)
    type: Ref<UserType>

    @Refs(type => Post)
    posts: Ref<Post>[]
    
}
```
When we have support for relations in mongo, it would be nice to have `@RelationId()` decorator functionality implemented too since the refs are stored inside documents.
I know, the usage of `@ManyToMany` is weird but this might be implementation of `@JoinTable()` decorator 😜 

```ts
class User {

    @ManyToOne(/*...*/)
    type: UserType
    
    @ManyToMany(/*...*/)
    @JoinTable()
    posts: Post[]

    @RelationId((user: User) => user.type)
    typeId: ObjectId

    @RelationIds((user: User) => user.posts)
    postsIds: ObjectId[]

}
```

So the id and array of ids would be stored inside of document and always returned but we have an api to insert/update the relation by object not by ids. And we could populate the relations by `relations` find options.

**Comment by 19majkel94** [comment]
Ok, I think that all what I need for now is to make it works:
```ts
@Column(type => ObjectId)
posts: Post[]
```
So with `@BeforeInsert()` I could map the ids from objects and store the array of ObjectIds inside `posts` property. I don't need cascade insert now, it might be implemented later 😉 

@pleerock Are you able to make this quick fix of storying something in array when `type` decorator option is used?

**Comment by pleerock** [comment]
It does not make sense to implement temporary "refs" functionality when we can implement real relations. Both are hard to implement and I guess only I can handle it. However I don't think I'll be able to implement it soon. I'll schedule it after 1.0.0 is released. And I plan to release 1.0.0 summer-autumn next year. Closing in favour of #1038

**Comment by 19majkel94** [comment]
> Both are hard to implement and I guess only I can handle it. 

Simple relations are not a problem if we are talking about direct operations on db. Mongo has a kind of join support by "$lookup" which is equivalent for "left outer join". Yes, this kind of query building might be hard but we can implement it for now like the other ODMs like mongoose - just by additional query for documents from the related collection by their ids. Saving already works for ManyToOne, only some tuning needed for OneToMany and implementation for ManyToMany without join table (only array of objectids on the owner side). I wish I would be able to help 😞

**Comment by MurtuzaSrashtaSoft** [comment]
what about one to one?

**Comment by MurtuzaSrashtaSoft** [comment]
How I achive one-to-one relationship using typeorm mongodb.

I m try to join two document using agrigation but not achive success.

Please provide one solution.

Entity details
1.counrty :- _id,name
2.state :- _id,name, countryid
