### ISSUE TITLE
Problem with typeorm after updating expo to sdk 52

### ISSUE THREAD

**Issue by kamreo** [typeorm/typeorm#11138]
### Issue description

I have issues with typeorm after upgrading to newest version of expo-sqlite

### Expected Behavior

It should be possible to use typeorm with newest version of expo-sqlite.  

### Actual Behavior

After the update it turns out that expo-sqlite introduced two functions openDatabaseSync and openDatabaseAsync, instead of openDatabase which is used in typeorm package. Current version of typeorm will be causing error, when trying to initialize database. The logic is inside `typeorm/src/driver/expo/ExpoDriver.ts`

### Steps to reproduce

Set up project with expo-sqlite and typeorm and try to establish connection to db with typeorm. 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows   |
| Node.js version     | 20.18.0 |
| Typescript version  |  5.3.3 |
| TypeORM version     |  0.3.20  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [X] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time, but I can support (using donations) development.

**Comment by pedrocf1** [comment]
Same issue here

**Comment by kamreo** [comment]
Currently the solution is using this patch https://github.com/typeorm/typeorm/pull/11107, which hopefully will be a part of new typeorm update.

**Comment by macksal** [comment]
why close this before a solution is in-tree 👀
