### ISSUE TITLE
Limit the size of the SQL statement generated

### ISSUE THREAD

**Issue by alper** [typeorm/typeorm#11133]
### Feature Description

We don't get visibility in Datadog if SQL statements are too long and we think queries that are that long are an anti-pattern in general.

### The Solution

A setting that would limit the size of queries that people make (so they don't go into absurd territory) would be useful.

### Considered Alternatives

We can check the length of queries everywhere but then we'd have to wrap typeorm with a library and we don't think that's a good practice.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by stim371** [comment]
@alper Thanks for submitting your request. This is out of scope this repo unless long queries are causing execution issues in the underlying drivers.

If you want to write your own, you could use the `getSql()` function on your QueryBuilders and write a little `assertLengthAndExecute()` function to wrap around the queries you're worried about (there's likely a better idea, just an idea).
