### ISSUE TITLE
@CreatedBy / @UpdatedBy / @DeletedBy special columns

### ISSUE THREAD

**Issue by sumbricht** [typeorm/typeorm#11169]
### Feature Description

A recurring pattern in applications is that the user id of the person creating / updating / (soft-)deleting a record needs to be captured in addition to the timestamps which are already covered by the special column @CreateDate / @UpdateDate / @DeleteDate.
This user id could be a string / number / UUID with or without foreign key relation to a User table and is NOT the DB user.

For this situation it'd be great to have additional special columns @CreatedBy / @UpdatedBy / @DeletedBy.

### The Solution

Add additional special columns @CreatedBy / @UpdatedBy / @DeletedBy and provide a means to specify which user is executing the current action, e.g.

```typescript
const userId: string | number = ... // however the application determines the current user
await manager.save(person, { userId })
await createQueryBuilder(Person, 'p').asUser(userId).update().execute()
await manager.transaction(manager => { ... }, { userId, isolationLevel })
```

This this make sense from your architectural vision? :-)

### Considered Alternatives

What I've been considering is to create an EventSubscriber with beforeInsert, beforeUpdate and beforeSoftRemove hooks to set the corresponding values and that would probably work, although I haven't tried and I'm not 100% sure it would correctly treat related entities that are saved together. The one thing I don't like about this though is that it could lead to unnecessary updates if user2 re-saves a record last modified by user1 without making any changes. Setting some "updatedBy" property on the record would in that case lead to an UPDATE on the DB even though it'd be unnecessary.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time, but I can support (using donations) development.

**Comment by stim371** [comment]
@sumbricht Thanks for the detailed request. This is currently outside of the scope for the project.

Your Subscriber idea might work or create a new method/overload the create/save/etc to pass the additional param.
