### ISSUE TITLE
Entity create method does not convert date strings to Date object

### ISSUE THREAD

**Issue by tonybentley** [typeorm/typeorm#11162]
### Issue description

When using TypeORM entity create method, date properties are not converted to Date object

### Expected Behavior

When declaring a date field for an entity, the create method should attempt to convert the value into a Date object
```
 @IsOptional()
    @IsDate()
    @Column({
        name: 'my_date_field',
        type: 'datetime',
   
        nullable: true,
    })
    myDateField?: Date | null;
```

### Actual Behavior

When the datetime value is string `2024-12-03T16:00:04.479Z`, the value is not automatically converted to Date object. The result is IsDate decorator throws invalid date validation error

### Steps to reproduce

const myEntity: Entity = {
myDateField: '2024-12-03T16:00:04.479Z'
}
Entity.create(myEntity)
EntityRepository.save(myEntity)

..throws IsDate class-validator validation error

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System  MacOS
| Node.js version   20.16.0
| Typescript version "typescript": "^4.9.0",
| TypeORM version     "@nestjs/typeorm": "^10.0.2",

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by markusm7** [comment]
To my knowledge typeorm does no value transformations on entity creation, but only when writing to or reading from the DB.
`Entity.create(data)` will only create a new `Entity` instance (like `new Entity()` would) and then copies the properties from `data` to the newly created instance, but only properties existing on `Entity`, but without touching the values.

If you wan't to transform the data first and validate it with `class-validator` (which seems you are using) you should look into `class-transformer`
