### ISSUE TITLE
Common Table Expressions

### ISSUE THREAD

**Issue by sylvainlap** [typeorm/typeorm#1116]
Hello,

This is more a question than an issue, but how can I build a CTE (`with`) with TypeORM ? Is there a built in feature to do this, or should I use the raw sql query builder ?

Thanks.

**Comment by pleerock** [comment]
Hi, no, there is no, you probably need to execute raw sql query using `query` method. But if orm would have such functionality, how do you see it there?

**Comment by sylvainlap** [comment]
Knex, for example, allows to build CTE thanks to `.with()`: http://knexjs.org/#Builder-with

**Comment by pleerock** [comment]
Sorry but I can't imagine how this can be integrated into typeorm's query builder semantics. TypeORM's QueryBuilder purpose is to select some model and return it. Can you create a feature proposal on how this can be implemented in our QueryBuilder and how it will work.

**Comment by pleerock** [comment]
@sylvainlap did you have a chance to take a look on this issue deeply?

**Comment by sylvainlap** [comment]
Actually, it was more a question than a feature request. I can close the issue.

**Comment by jtmthf** [comment]
I have a use case where a `with` CTE would be useful and I think it could work with the existing API. What I'm trying to do is get a list of items by ids and return the results in the order of the ids. The following raw query works with postgres 9.6+.

```sql
with x (id_list) as (
  values (array[42,48,43])
)
select c.*
from comments c, x
where id = any (x.id_list)
order by array_position(x.id_list, c.id);
```

However I'd ideally want to avoid using raw queries due to the lack of type-safety and the difficulty in mapping the results back to entities. What I'd like to do is to use an API similar to below.

```ts
const comments = await getRepository(Comment)
    .createQueryBuilder('comment')
    .with('x(id_list)', 'values(:ids)')
    .addFrom('x', 'x')
    .where('comment.id = any(x.id_list)')
    .orderBy('array_position(x.id_list, comment.id)')
    .setParameter('ids', [42, 48, 43])
    .getMany();
```

Understandably this is also possible with the following simpler query builder expression:

```ts
const ids = [42, 48, 43];
const comments = await getRepository(Comment)
    .createQueryBuilder('comment')
    .whereInIds(ids)
    .orderBy('array_position(:ids, comment.id)')
    .setParameter({ids})
    .getMany()
```

However I'd like not to send the array of ids twice especially if there is a large number of them. A possible API for `with` could be similar to Knex and be `with(alias: string, query: ((qb: this) => string) | string): this`. Some other examples from Knex would be written as:

Knex
```js
knex.with('with_alias', knex.raw('select * from "books" where "author" = ?', 'Test')).select('*').from('with_alias')
```

TypeORM
```ts
const books = await getRepository(Book)
    .createQueryBuilder()
    .with('with_alias', 'select * from "books" where "author" = :author')
    .select()
    .from('with_alias')
    .setParameter('author', 'Test')
    .getMany();
```

Knex
```js
knex.with('with_alias', (qb) => {
  qb.select('*').from('books').where('author', 'Test')
}).select('*').from('with_alias') 
```

TypeORM
```ts
const books = await getRepository(Book)
    .createQueryBuilder()
    .with('with_alias', qb => qb.select().from('books').where('author', 'Test').getQuery())
    .select()
    .from('with_alias')
    .getMany();
```

**Comment by Neo-Zhixing** [comment]
I know it's a bit hacky but here's a workaround:

```js
const originalQuery = qb.getQuery
const originalParams = qb.getParameters
qb.getQuery = () => {
  const a = originalQuery.call(qb)
  return `WITH lb AS (${a}) SELECT * FROM lb WHERE abs(rank - (${rankQuery})) <= 3`
}
qb.getParameters = () => {
  const a = originalParams.call(qb)
  a.user = user
  return a
}
```

**Comment by tvoloshyn** [comment]
@jtmthf Will the proposed API support `WITH RECURSIVE` as well ?

**Comment by jtmthf** [comment]
@tvoloshyn I'm not sure if it's the best way, but I can implement it the same way as Knex's API as `.withRecursive(alias, function|raw)` where `withRecursive` operates identically to `with`, but appends `RECURSIVE` after `WITH`.

**Comment by jtmthf** [comment]
After further review, I don't think that syntax will work for recursive CTE's as it doesn't support parameters. That feature may need to be a separate discussion and PR.

**Comment by ejose19** [comment]
@jtmthf Do you have any work on this feature I can contribute? Your proposed api seems very useful and way better than dealing with raw queries.

**Comment by ejose19** [comment]
@jtmthf Do you have any work on this feature I can contribute? Your proposed api seems very useful and way better than dealing with raw queries.

**Comment by jtmthf** [comment]
@ejose19 I still need to get around to working on this. I've been spending more time lately adding keyset pagination support as implemented by [JOOQ](https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/seek-clause/)

**Comment by fullofcaffeine** [comment]
> I know it's a bit hacky but here's a workaround:
> 
> ```js
> const originalQuery = qb.getQuery
> const originalParams = qb.getParameters
> qb.getQuery = () => {
>   const a = originalQuery.call(qb)
>   return `WITH lb AS (${a}) SELECT * FROM lb WHERE abs(rank - (${rankQuery})) <= 3`
> }
> qb.getParameters = () => {
>   const a = originalParams.call(qb)
>   a.user = user
>   return a
> }
> ```

Thanks a bunch for sharing the workaround! I managed to succesfully use your technique to implement the recursive tree querying described here: https://schinckel.net/2014/09/13/long-live-adjacency-lists/.

**Comment by ameinhardt** [comment]
I tried to overwrite a queryBuilders `getQueryAndParameters()` and also its `clone()`. If the CTE has parameter, it also needs a way of rewriting params (and nativeParameters!). I guess at least for cockroachdb, postgres ($...) and mssql (@...).
Eventually, paging with relations still doesn't work, because it uses a more complex mechanism

**Comment by ahsan-babar** [comment]
> I know it's a bit hacky but here's a workaround:
> 
> ```js
> const originalQuery = qb.getQuery
> const originalParams = qb.getParameters
> qb.getQuery = () => {
>   const a = originalQuery.call(qb)
>   return `WITH lb AS (${a}) SELECT * FROM lb WHERE abs(rank - (${rankQuery})) <= 3`
> }
> qb.getParameters = () => {
>   const a = originalParams.call(qb)
>   a.user = user
>   return a
> }
> ```

@Neo-Zhixing Could you please describe how can I use this snippet for WITH clause of Query Builder?

**Comment by dustin-rcg** [comment]
Can we have a querybuilder that takes at a top level, any `WITH`s and then an array of `UNION` or `UNION ALL` subqueries? That can be a SuperSelectQueryBuilder that has like `with`, `addWith`, `union`, `addUnion` or similar. Then redesign SelecQueryBuilder to take a `unionIndex` parameter, such that the param names become (in mssql for example) `@<unionIndex>_<paramIndex>`. Then we have a model that includes a way to combine multiple queries and their parameters as UNION or UNION ALL, plus the WITHs. Having SelectQueryBuilder not aware that its parameters need to be scoped is too limiting. Thanks.

**Comment by dustin-rcg** [comment]
Here's an implementation I have working. Subclassing SelectQueryBuilder works fine it seems.
```
import { Connection, QueryRunner, SelectQueryBuilder } from "typeorm";

export class CteSelectQueryBuilder<T> extends SelectQueryBuilder<T> {
  protected commonTableExprs: Record<string, string> = {};

  constructor(connection: Connection, queryRunner?: QueryRunner) {
    super(connection, queryRunner);
  }

  addCommonTableExpr(
    name: string,
    expr: string | ((qb: SelectQueryBuilder<any>) => SelectQueryBuilder<any>)
  ) {
    if (typeof expr == "function") {
      const subQueryBuilder = expr(this.subQuery());
      this.setParameters(subQueryBuilder.getParameters());
      this.commonTableExprs[name] = subQueryBuilder.getQuery();
    } else {
      this.commonTableExprs[name] = expr;
    }
  }

  getQuery() {
    const ctes = Object.entries(this.commonTableExprs);
    if (ctes.length) {
      return [
        "WITH",
        ctes.map(([name, expr]) => `${name} AS ${expr}`).join(", "),
        super.getQuery(),
      ].join(" ");
    }
    return super.getQuery();
  }
}
```

**Comment by davebot9000** [comment]
> Here's an implementation I have working. Subclassing SelectQueryBuilder works fine it seems.
> 
> ```
> import { Connection, QueryRunner, SelectQueryBuilder } from "typeorm";
> 
> export class CteSelectQueryBuilder<T> extends SelectQueryBuilder<T> {
>   protected commonTableExprs: Record<string, string> = {};
> 
>   constructor(connection: Connection, queryRunner?: QueryRunner) {
>     super(connection, queryRunner);
>   }
> 
>   addCommonTableExpr(
>     name: string,
>     expr: string | ((qb: SelectQueryBuilder<any>) => SelectQueryBuilder<any>)
>   ) {
>     if (typeof expr == "function") {
>       const subQueryBuilder = expr(this.subQuery());
>       this.setParameters(subQueryBuilder.getParameters());
>       this.commonTableExprs[name] = subQueryBuilder.getQuery();
>     } else {
>       this.commonTableExprs[name] = expr;
>     }
>   }
> 
>   getQuery() {
>     const ctes = Object.entries(this.commonTableExprs);
>     if (ctes.length) {
>       return [
>         "WITH",
>         ctes.map(([name, expr]) => `${name} AS ${expr}`).join(", "),
>         super.getQuery(),
>       ].join(" ");
>     }
>     return super.getQuery();
>   }
> }
> ```

Should the `addCommonTableExpr` be returning the instance of the query builder so it can be chained?

**Comment by timfrans** [comment]
@Ginden 
Are there any plans to make this available for 0.2.x versions?

**Comment by Ginden** [comment]
@timfrans No.

**Comment by mopcweb** [comment]
> 

@dustin-rcg thx so much for your approach.

To make it work properly with native TypeORM's queryBuilder for all methods (which may call `getQuery` deeply nested) i found out that it is necessary to patch it.

__Note__ Since `typeorm@0.3.3` it is already implemented ability to use CTE, still for other versions this will be useful.

So the solution which works for me for all native methods such as `getManyAndCount` etc:

```ts
// patchTypeOrmQueryBuilderAddCommonTableExpressionsSupport.ts
import { SelectQueryBuilder } from 'typeorm';

export function patchTypeOrmQueryBuilderAddCommonTableExpressionsSupport(
  queryBuilderToPatch: Function | Object = require('typeorm').SelectQueryBuilder,
): void {
  const qb = (queryBuilderToPatch as Function).prototype ?? queryBuilderToPatch as SelectQueryBuilder<unknown>;
  const originalGetQuery = qb.getQuery;

  Object.defineProperty(qb, 'commonTableExpressions', { value: { } });

  Object.defineProperty(qb, 'getQuery', {
    value: function getQuery(): string {
      const context = this as SelectQueryBuilder<unknown>; // For typization only
      const ctes = Object.entries(context.commonTableExpressions);

      if (ctes.length && !context.expressionMap.subQuery) {
        return [
          'WITH',
          ctes.map(([name, expression]) => `${context.escape(name)} AS (${expression})`).join(', '),
          originalGetQuery.call(context),
        ].join(' ');
      }
      return originalGetQuery.call(context);
    },
  });

  Object.defineProperty(qb, 'addCommonTableExpression', {
    value: function addCommonTableExpression<T>(expression: CommonTableExpression<T>, name: string) {
      const context = this as SelectQueryBuilder<unknown>; // For typization only

      if (typeof expression === 'function') {
        const subQueryBuilder = expression(context.subQuery());
        context.setParameters(subQueryBuilder.getParameters());
        context.commonTableExpressions[name] = subQueryBuilder.getQuery();
      } else {
        context.commonTableExpressions[name] = expression;
      }
    },
  });
}

type CommonTableExpression<T> = string | ((qb: SelectQueryBuilder<T>) => SelectQueryBuilder<T>);

export interface IQueryBuilderWithCommonTableExpressions<Entity> {
  commonTableExpressions: Record<string, string>;
  addCommonTableExpression<T = Entity>(expression: CommonTableExpression<T>, name: string): void;
  getQuery(): string;
}

// Optionally to infer types for TypeORM's SelectQueryBuilder.
declare module 'typeorm' {
  export class SelectQueryBuilder<Entity> implements IQueryBuilderWithCommonTableExpressions<Entity> {
    public commonTableExpressions: Record<string, string>;
    public addCommonTableExpression<T = Entity>(expression: CommonTableExpression<T>, name: string): this;
  }
}
```

### Usage
call `patchTypeOrmQueryBuilderAddCommonTableExpressionsSupport` some where at application startUp, to fully patch TypeORM's SelectQueryBuilder.

```ts
patchTypeOrmQueryBuilderAddCommonTableExpressionsSupport();
```

Use someWhere/at/some/repository.ts
```ts
qb
  .addCommonTableExpression(`SELECT * FROM some_table`, 'some_cte')
  .addSelect(/* ... */)
```

Optionaly could be used to patch any custom class, so it is possible to mimic class from original example
```ts
class CteSelectQueryBuilder {}
patchTypeOrmQueryBuilderAddCommonTableExpressionsSupport(CteSelectQueryBuilder);
```

**Comment by mopcweb** [comment]
@timfrans u could try to use solution above

**Comment by 67726e** [comment]
@mopcweb What version is this meant to work against? I've tried on `0.2.x` and `0.3.x` and in all cases it results in an error.

**Comment by ab958** [comment]
any update on that?

**Comment by Ginden** [comment]
https://typeorm.io/select-query-builder#common-table-expressions

**Comment by revskill10** [comment]
@Ginden How do we know if it supports a driver ? 
I'm using SQL server.
