### ISSUE TITLE
Support for GaussDB

### ISSUE THREAD

**Issue by CodeYHJ** [typeorm/typeorm#11160]
### Feature Description

We need an GaussDB for our projects

### The Solution

I'm guessing that this should be fairly easy as the api is similar to the postgres api?

### Considered Alternatives

n/a

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
