### ISSUE TITLE
Unclear that UpdateDateColumn is not updated when using Entity.update()

### ISSUE THREAD

**Issue by mattbasta** [typeorm/typeorm#11204]
### What was unclear or otherwise insufficient?

Perhaps my understanding is incorrect, but after reviewing the source code, it seems to be the case that when calling `Entity.update(...)`, columns that are `@UpdateDateColumn()` are not updated. This is unexpected, and is only mentioned indirectly here:

https://typeorm.io/decorator-reference#updatedatecolumn

> Special column that is automatically set to the entity's update time each time you call save from entity manager or repository.

This indirectly implies that it _only_ gets set when calling `save()`.

### Recommended Fix

The docs should explicitly mention when `UpdateDateColumn`s are updated. For instance:

1. When calling `increment()` or `decrement()`
2. When calling `.update(...)`
3. When calling `.upsert(...)`
4. etc.

### Additional Context

I'm glad to update the docs if this is a documentation issue, but I also am not sure of the complete current/expected behavior.

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by jorenvandeweyer** [comment]
@mattbasta The updatedDateColumn is being updated in the database when using these functions. 

Do you mean that it is not being updated on the entity itself? (in the example below it's very clear why it is not being updated in the entity.)

```typescript
const roleRepository = dataSource.getRepository(Role)

const role = roleRepository.create({
  name: 'test',
  permissions: []
})

await roleRepository.insert(role)

await roleRepository.update({
  uuid: role.uuid
}, {
  permissions: [
    'user:read' as Permission
  ]
})

const foundRole = await roleRepository.findOneByOrFail({
  uuid: role.uuid
})

console.log(role.updatedAt)
console.log(foundRole.updatedAt)
```

result:
```bash
2024-12-29T22:36:53.778Z 
2024-12-29T22:36:53.793Z
```

**Comment by jorenvandeweyer** [comment]
@mattbasta The query builder will set these fields it self. So any operation except a raw query would set the updatedAt field.

logs of the code snippet above:
```
query: INSERT INTO "role"("uuid", "created_at", "updated_at", "name", "permissions") VALUES (DEFAULT, DEFAULT, DEFAULT, $1, $2) RETURNING "uuid", "created_at", "updated_at", "permissions" -- PARAMETERS: ["testtt",[]]
query: UPDATE "role" SET "permissions" = $1, "updated_at" = CURRENT_TIMESTAMP WHERE "uuid" = $2 -- PARAMETERS: [["user:read"],"488cd002-385e-4766-a9d9-79893c5b2a6f"]
query: SELECT "Role"."uuid" AS "Role_uuid", "Role"."created_at" AS "Role_created_at", "Role"."updated_at" AS "Role_updated_at", "Role"."name" AS "Role_name", "Role"."permissions" AS "Role_permissions" FROM "role" "Role" WHERE (("Role"."uuid" = $1)) LIMIT 1 -- PARAMETERS: ["488cd002-385e-4766-a9d9-79893c5b2a6f"]
```
