### ISSUE TITLE
@Transaction()

### ISSUE THREAD

**Issue by 11000100111000** [typeorm/typeorm#1120]
Do nested calls of functions with the transaction decorator work as one should expect?
For example like this:
```js
@Transaction()
save(user: User, @TransactionRepository(User) userRepository: Repository<User>) {
    return userRepository.save(user);    
}

@Transaction()
create(user: User, @TransactionRepository(User) userRepository: Repository<User>) {
    console.log(user);
    return this.save(user);    
}
```
or do i have to change something in the code in order to make it work

**Comment by pleerock** [comment]
What do you mean? I don't see "nested calls of functions" in your code example? Do you mean something like calling `create` method in a `save` method? If yes, then yes it shall work, but you need to pass a userRepository instance from save method into create method.

**Comment by 11000100111000** [comment]
yeah i meant that, i messed up the example
