### ISSUE TITLE
New hook that intercepts the SQL to be executed and modifies it.

### ISSUE THREAD

**Issue by JanYork** [typeorm/typeorm#11201]
### Feature Description

Can Typeorm add a new hook to intercept the SQL to be executed, change the original SQL, and then execute the modified SQL.

### The Solution

AOP extension for executing SQL procedures.

### Considered Alternatives

No.

### Relevant Database Driver(s)

- [X] aurora-mysql
- [X] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by jorenvandeweyer** [comment]
Hi @JanYork Currently, new features are not really being picked up (so I'm going to close this issue).

But you can achieve this functionality yourself by using the query builder. You can put everything in a handy wrapper.

```ts
const [query, params] = queryBuilder.getQueryAndParameters()

const updatedQuery = query.replace(/uuid/g, 'uid')

await dataSource.query(updatedQuery, params)
```

Another alternative is overwriting the `.query` function of the queryRunner of your preferred database, everything eventually passes through this.

```ts
const originalQueryFunction = PostgresQueryRunner.prototype.query 

PostgresQueryRunner.prototype.query = async function(
    query: string,
    parameters?: any[],
    useStructuredResult: boolean = false
) {
    // do stuff here

    return originalQueryFunction.call(this, query, parameters, useStructuredResult)
}
```
