### ISSUE TITLE
Non-usable migrations

### ISSUE THREAD

**Issue by MrOxMasTer** [typeorm/typeorm#11210]
### Issue description

Non-usable migrations 

### Expected Behavior

Migration generation

### Actual Behavior

Endless errors

### Steps to reproduce

I've tried everything I can think of to turn it on:
1. Swap between commonjs/esm
2. `npm run` / without `npm run`
3. Rearrange arguments a thousand times
4. Move files / folders themselves
5. Import entities with import / specify paths with glob string

Problems:
Is forever complaining that <path> is missing. I have specified this <path> in every way possible, both relatively and absolutely and without slashes, nothing helps.

I have already reread your documentation ten times. I read different articles and watched videos. You have the migration functionality changing every 2 seconds and it's different for everyone.

None of these helped. One of the most useless commands worked, but the generation of migrations did not, even an empty migration can not run normally.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 22.12.0  |
| Typescript version  | 5.7.2 |
| TypeORM version     | 0.3.2  |

It's only now that I realized that this library doesn't even have a major version....

### Additional Context

Okay, I sincerely apologize. I didn't realize this lib was still in conception. I'm switching to Sequalize

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time, but I can support (using donations) development.

**Comment by jorenvandeweyer** [comment]
@MrOxMasTer 

- create a datasource file (export it)
- add a command in your package.json
  - `"typeorm": "node ./node_modules/typeorm/cli -d ./path/to/datasource.js"`
- run `npm run typeorm migration:generate your-migration.ts`
