### ISSUE TITLE
Could you give an example of use "Eager and Lazy Relations" in JavaScript(es5, es6)? Is this possible?

### ISSUE THREAD

**Issue by YGolikov** [typeorm/typeorm#1123]

**Comment by pleerock** [comment]
Yes, its possible. You just add corresponding flags in entity schemas. Unfortunately I don't have a time right now to create docs for this and fix related issues if they exist since Im busy with more priority tasks. I need some help from contributors who are using typeorm with vanilla javascript.

**Comment by afmelsaidy** [comment]
The eager property can not be set from the entity schema, only the lazy property using isLazy.

**Comment by afmelsaidy** [comment]
I submitted pull request #1821 to allow setting the eager property from the entity schema.

**Comment by pleerock** [comment]
thanks to @afmelsaidy will be released in next `@next`.
