### ISSUE TITLE
PostgresDriver assumes hydrated dates are always a Date object

### ISSUE THREAD

**Issue by shousper** [typeorm/typeorm#1124]
Given a model field definition like so:

```
@Column('timestamp', { transformer: new CustomTimestampTransformer() })
myTimestamp: ZonedDateTime
```

The `PostgresDriver` method `prepareHydratedValue` tries to "normalize" columns of type "timestamp", but assumes the `transformer` is returning a JavaScript Date object.
This prevents users from easily using other libraries such as `moment` or `js-joda` as the field type.

I would suggest the `DateUtils.normalizeHydratedDate` method checks `mixedDate instanceof Date` before trying to "correct" the `Date` object.

The workaround for now is to tell TypeORM that the column type is `varchar` or another type that isn't touched by `prepareHydratedValue` in the `@Column` decorator.

**Comment by pleerock** [comment]
This was already fixed by @brendan-roche
