### ISSUE TITLE
create from plain object when use Active Record 

### ISSUE THREAD

**Issue by xujif** [typeorm/typeorm#1125]
The repository object  create function recieve entityLike: DeepPartial<Entity> params
 but   BaseEntity not implements this method.

**Comment by pleerock** [comment]
Feel free to create a PR for this feature.

**Comment by pleerock** [comment]
what typeorm version are you using? I see `BaseEntity` already has a create method with entityLike: DeepPartial parameter. Looks like this was already fixed.
