### ISSUE TITLE
Typeorm removes the parentId when the mysql gives it

### ISSUE THREAD

**Issue by Flexiink** [typeorm/typeorm#1126]
<pre>
class Categories {

    @PrimaryGeneratedColumn()
    id: number;

    @Column('int', { default: 0 })
    position: number = 0;

    @TreeParent({ cascadeInsert: true, cascadeUpdate: true })
    parent: Categories;

    @OneToOne(type => L10nCategories, l10n => l10n.categories, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    @JoinTable()
    l10nCat: L10nCategories[];
}
</pre>

Query:
<pre>
 const sqlConditions = {
            relations: [ 'parent' ],
 };

 const category = await repository.findOneById(id, sqlConditions);
</pre>
Result:
<pre>
{"position":0,"id":58,"parent":{"position":0,"id":57}}
</pre>

but if you do not specify the relations
query:
<pre>
SELECT `Categories`.`id` AS `Categories_id`, `Categories`.`position` AS `Categories_position`, `Categories`.`parentId` AS `Categories_parentId` FROM `categories` `Categories` WHERE `Categories`.`id` = 58 ORDER BY `Categories`.`id` DESC
</pre>
Result:
<pre>
{"position":0,"id":58}
</pre>

How can I get **parentId** without relations?

**Comment by pleerock** [comment]
try to add:

```ts
    @Column({ nullable: true })
    parentId: number;

    @TreeParent({ cascadeInsert: true, cascadeUpdate: true })
    parent: Categories;
```
