### ISSUE TITLE
Many to Many relationship has some problem.

### ISSUE THREAD

**Issue by yunseop-kim** [typeorm/typeorm#1130]
Good morning. I have found a bug in many-to-many relationships.

My entities are:

```

@Entity()
export class Gift {
    @PrimaryGeneratedColumn()
    idx: number;

    @Column()
    name: string;

    @ManyToMany(type => Box, box => box.gifts, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    boxes: Box[] = [];
}


@Entity()
export class Box {
    @PrimaryGeneratedColumn()
    idx: number;

    @Column()
    name: string;

    @ManyToMany(type => Gift, gift => gift.boxes, {
        cascadeInsert: true,
        cascadeUpdate: true,
    })
    @JoinTable()
    gifts: Gift[] = [];
}
```

The order of execution is as follows.

1. Generate gifts 1, 2, 3.
2. Create box 1 and enter the gift 1. => Box 1: Gift 1 relationship created on the database
3. Create box 2 and enter gift 2. => Box 2: Gift 2 relationship created on the database.
4. Create the box 3 and enter the gifts 1 and 2 => The relationship in box 3: gifts 1 and 2 is created in the database, but the relationship in the order 2 and 3 disappears.

What I expected was
Box 1: Gift 1
Box 2: Gift 2
Box 3: Gifts 1, 2

But the result is Box 3: Gifts 1,2 only.

Is it an intended problem? Or is it a bug?

I used a translator because I was not accustomed to English. hope you understand.

**Comment by pleerock** [comment]
Remove initialization from your arrays, .e.g remove `= [];`, this may lead to unexpected behaviour. More info [here](http://typeorm.io/#/relations-faq/avoid-relation-property-initializers) and check if you have same issue you have

**Comment by pleerock** [comment]
@yunseop-kim did you solve problem?

**Comment by yunseop-kim** [comment]
@pleerock yes. i solved. I had some misunderstand about queries. thanks.
