### ISSUE TITLE
Memory consumption in Chrome

### ISSUE THREAD

**Issue by flacidsnake** [typeorm/typeorm#1131]
Hi,

basically, the Ionic-app sends some SOAP requests to a server and the saves the data in a WebSQL database (using Chrome browser). After the process, I see this:

![imagen](https://user-images.githubusercontent.com/11427271/32329145-65464386-bfdc-11e7-87a3-043ef7bd028a.png)

The stored data in the WebSQL database weights just 722 KB, but the memory consumption of the Chrome tab is over 1'8 GB. 
 Do you know a workaround to get rid of this? (Besides refreshing the tab...)

Thank you!
Regards

**Comment by daniel-lang** [comment]
Is this a TypeORM specific problem?
Could you give more information on how you handle and store your data?
Is the increased memory usage just after loading your requests or also when using the database without sending requests?

**Comment by flacidsnake** [comment]
It must be TypeORM related, since when I read/write at the database the memory grows and grows.
The requests are done at the beginning. When they are done, memory is under 600 MB and it starts growing when I read/write from/to the database.

**Comment by daniel-lang** [comment]
Could you share some code?

**Comment by flacidsnake** [comment]
`
// I do this many times to fill an array
let _myField: FieldEntry = await this.entityManager.getRepository(FieldEntry).findOne({ where: { IdWeb: idWeb } });
// get a connection and create a new query runner
let connection = getConnection();
let queryRunner = connection.createQueryRunner();
// establish real database connection using our new query runner
await queryRunner.connect();
// lets now open a new transaction:
await queryRunner.startTransaction();
for(let element of elementsArray)
{
                try {
                    
                    // execute some operations on this transaction:
                    await queryRunner.manager.save(element);
                   // Results are the same if I insert the whole array instead of looping it
                    
                } catch (err) {
                    console.log(err);
                    // since we have errors lets rollback changes we made
                    await queryRunner.rollbackTransaction();
                }
            }
            // commit transaction now:
            await queryRunner.commitTransaction();
`

**Comment by daniel-lang** [comment]
This will generate an insert statement by element. Which might not be the most efficient way if you have a lot of elements.
Also this line concerns me:
```typescript
// I do this many times to fill an array
let _myField: FieldEntry = await this.entityManager.getRepository(FieldEntry).findOne({ where: { IdWeb: idWeb } });
```
Why do you have to do this multiple times? Can you combine them to one find?

Generally it might be interesting to turn on logging by setting `logging: true` in your connection options and see how many queries are generated. But 1,8GB is still to much for a queries.

**Comment by NoNameProvided** [comment]
An another option can be that your JS have a memory leak. Have you tried to profile your code in the dev tools? Do you clean up all references?

**Comment by flacidsnake** [comment]
Any clue? =)

**Comment by daniel-lang** [comment]
I was able to somewhat see the memory consumation (500MB for insert and selects).
Some points I would change from your code:

**Use batch inserts**
```typescript
await this.connection.createQueryBuilder().insert().into(User).values(users2).execute();
```
This will insert all your users with one query instead of generating 1000 queries and inserting them one by one. This currently doesn't work in browser with webpack when using SystemJS as loaded but should work with ionic and webpack.

**Improve selects**
If you only select every user to see if it was inserted successfully I would either use `count` (`userRepository.count({where: {login: "user" + i}})`) which doesn't acually select the user but returns 1 if a user was found, otherwise 0. Or use a transaction which fails if an error occures and automatically undoes all inserts that happened up to the error. As far as I know transactions aren't yet fully supported in WebSQL but work in Sqlite.

This should bring your memory usage down a bit.

**Comment by daniel-lang** [comment]
Any news on this?

**Comment by pleerock** [comment]
ping @flacidsnake

**Comment by pleerock** [comment]
btw if you keep track of #1115 I made a good progress on performance in recent alpha versions.

**Comment by flacidsnake** [comment]
Memory consumption is still too high even improving my code the way you suggested. I'll try to run my code with the new version.

Thank you!

**Comment by daniel-lang** [comment]
@flacidsnake How are your results on `next`? Can I close this issue?

**Comment by daniel-lang** [comment]
@flacidsnake I'm going to close this now. If you have any updates on this feel free to reopen it.
