### ISSUE TITLE
how to create a view entity without an primary column

### ISSUE THREAD

**Issue by xujif** [typeorm/typeorm#1135]

**Comment by pleerock** [comment]
its required for entities to have a primary column in terms of ORM because most of ORM operations are heavily rely on entity primary ids.

**Comment by xujif** [comment]
Is there any way to create a readonly entity without primary?

**Comment by pleerock** [comment]
no, you can't even use `find` operations without having a primary columns. I don't think orm needs this feature at the moment.

**Comment by miltonhowe** [comment]
This would be massively useful. I understand that it might be challenging to implement considering the design assumptions of every entity having a primary column, however this is a feature of other ORMs, notably Entity Framework being the one I am particularly familiar with.

My project relies heavily on views for reporting. A the OP said, even if it were limited to read only it would still be very helpful.
