### ISSUE TITLE
Ability to create connection with query runner

### ISSUE THREAD

**Issue by doomsower** [typeorm/typeorm#1138]
I'm writing integration tests for my API. I use handcrafted seeded database and test API requests with `supertest`. To ensure that tests do not mess with each other I start transaction in `beforeEach` and rollback transaction in `afterEach`. This way each test starts with the same database state. This approach works for me with `knex` in my other project. 

Now I'm trying to follow the same approach with `typeorm`.  I want to obtain `queryRunner` instance in `beforeAll` and then call `await queryRunner.startTransaction();` in `beforEach` and `await queryRunner.rollbackTransaction();` in `afterEach`. The problem is that the code that I test is outside the transaction and still uses different entity manager. I could't find any simple way to provide my repositories with entity manager that runs within transaction.

It seems that the problem can be solved by adding the ability to create connection with query runner straight away. I.e. somehow provide `queryRunner` to `Connection` constructor and change manager creation in constructor to:

```
this.manager = new EntityManagerFactory().create(this, queryRunner);
```

This way in my tests I can obtain the same queryRunner that is used by entity managers inside my code.

If this sounds reasonable, I can make a PR with this feature added to `ConnectionManager` and/or connection config.

Or maybe someone can suggest different solution to my problem?

**Comment by pleerock** [comment]
can you please provide a sample code example of how are you are designing your test and point problems on it?

**Comment by pleerock** [comment]
Closing as no answer from reporter.
