### ISSUE TITLE
@PrimaryGeneratedColumn("uuid") doesn't work with mysql driver

### ISSUE THREAD

**Issue by enemyofthedawn** [typeorm/typeorm#1139]
I use MySQL driver.  I get some exception after running my app.

> Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
  code: 'ER_TOO_LONG_KEY',
  errno: 1071,
  sqlMessage: 'Specified key was too long; max key length is 767 bytes',

The logger says the serial is VARCHAR(255). Is this a bug or something? Also this is not optimal for uuid.

**Comment by pleerock** [comment]
> Also this is not optimal for uuid.

what is your suggestions? 

can you provide a code example that breaks for you?

**Comment by fmj02** [comment]
Use varchar(36) or binary(16)

Just simple entity with `@PrimaryGeneratedColumn("uuid")` and one `@Column("varchar")`. I dealt with it by directly using `@PrimaryColumn("varchar", { size: 36 })` or something like that but I have to generate it myself.

**Comment by pleerock** [comment]
We would not use binary for uuid, users will have to do manually if they want to use some extended uuid functionality. 

Regarding to reducing varchar length, we are going to do that.

Regarding to your original error:

> ER_TOO_LONG_KEY

how this is possible when we already have a long varchar length plus there are tests passing with uuid functionality, can you please provide additional information?

**Comment by hiroqn** [comment]
same error
i use aws aurora(mysql 5.6.10)

and configuration is
character_set_* is utf8mb4

so, 255 * 4 = 1000 > 767 bytes

i add config and resolve this problem

```
innodb_large_prefix
innodb_file_per_table
innodb_file_format=Barracuda
```

**Comment by kallaspriit** [comment]
Is this something that could be fixed in the current version. 255 length primary keys is really rather sub-optimal for 36 character UUID and I'm also getting the too long index issue with utf8_general_ci collation. Would a pull request speed this up?

**Comment by pleerock** [comment]
you can make a PR against `next` because its a breaking change.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.

**Comment by kallaspriit** [comment]
Did some investigation and in `MysqlDriver.normalizeType` the type is normalized from `uuid` to `varchar` and in the same file `getColumnLength` uses the `column.type` (which was normalized to `varchar`) to decide the length of 255. I think `column.generationStrategy` could be used in `getColumnLength` to determine the correct length.

Something like this:
*MysqlDriver.ts*
```typescript
/**
 * Returns default column lengths, which is required on column creation.
 */
getColumnLength(column: ColumnMetadata|TableColumn): string {
    if (column.length)
        return column.length.toString();

    if (column.generationStrategy === "uuid") {
      return "36";
    }

    switch (column.type) {
        case String:
        case "varchar":
        case "nvarchar":
            return "255";
        case "varbinary":
            return "255";
        default:
            return "";
    }
}
```

I tried creating a pull request but the master branch without any changes does not compile.
```
yarn test
yarn run v1.7.0
$ tsc && mocha --file ./build/compiled/test/utils/test-setup.js --bail --recursive --timeout 30000  ./build/compiled/test
src/find-options/FindOptionsUtils.ts:92:58 - error TS2345: Argument of type 'keyof T' is not assignable to parameter of type 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

92                 if (!metadata.findColumnWithPropertyPath(select))
                                                            ~~~~~~


test/github-issues/1576/issue-1576.ts:24:13 - error TS2345: Argument of type '{ categories: ({ id: null; name2: string; name?: undefined; } | { id: null; name: string; name2: ...' is not assignable to parameter of type 'DeepPartial<Post>[]'.
  Object literal may only specify known properties, and 'categories' does not exist in type 'DeepPartial<Post>[]'.

24             categories: cats
               ~~~~~~~~~~~~~~~~


test/github-issues/953/issue-953.ts:19:32 - error TS2345: Argument of type '{ username: string; password: string; roles: "ADMIN"[]; lastLoginAt: Date; }' is not assignable to parameter of type 'DeepPartial<User>'.
  Types of property 'roles' are incompatible.
    Type '"ADMIN"[]' is not assignable to type 'DeepPartial<Role[]> | undefined'.
      Type '"ADMIN"[]' is not assignable to type 'DeepPartial<Role[]>'.
        Index signatures are incompatible.
          Type '"ADMIN"' is not assignable to type '"admin" | "user" | "sa" | "server" | undefined'.

 19         let user = repo.create({
                                   ~
 20             username: "admin",
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 23             lastLoginAt: new Date()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 24         });
    ~~~~~~~~~


error Command failed with exit code 2.
```

**Comment by kallaspriit** [comment]
Any update on this? Still broken in 0.2.7 :(

**Comment by vinpac** [comment]
```
  // @ts-ignore
  @PrimaryGeneratedColumn('uuid', { length: 36 })
  public id: string
```

Solves it for me. Sure it should be 36 by default and length is not a valid option, thus `@ts-ignore`

**Comment by kallaspriit** [comment]
Could we get a proper fix for this or at least make the length parameter legal?

**Comment by havenchyk** [comment]
@pleerock seems it's still broken, can it be reopened?

**Comment by UrosNikolic** [comment]
Hi
Any news on this issue, it still seems to be broken. 

`@Column()
  @Generated("uuid")
  uuid: string`

This fails for me ☝️

**Comment by AnthonySendra** [comment]
> We would not use binary for uuid, users will have to do manually if they want to use some extended uuid functionality.

Seems legit, but can we have an example or documentation about the default UUID behaviour please?

**Comment by hoonoh** [comment]
Came across this issue today, figured workaround with:
```
@PrimaryColumn()
@Generated('uuid')
id: string;
```

**Comment by touilfarouk** [comment]
Recreate database from scratch with utf8
CREATE DATABASE mydatabase CHARACTER SET utf8;

Thats all.

**Comment by RArielVillalobos** [comment]
> @PrimaryColumn()
> @Generated('uuid')

this code worked for me
