### ISSUE TITLE
Support for using postgreSQL function to generate custom id

### ISSUE THREAD

**Issue by varHarrie** [typeorm/typeorm#1142]
```typescript
import {PrimaryColumn} from 'typeorm'

function generatedId () {
  return `pseudo_encrypt(nextval('custom_id_seq'))`
}

export default abstract class Base {
  @PrimaryColumn({default: generatedId, type: 'varchar'})
  id: string
}

```

The code above can successfully generate id, but cannot return it during the insertion process.

**Comment by pleerock** [comment]
Yeah we can do it. Would be great if you'll be able to provide a failing test for this use case

**Comment by pleerock** [comment]
I have released a first alpha version of 0.2.0, you can install it via `npm i typeorm@next` and try if it fixes your issue. Please let me know if its not.

**Comment by varHarrie** [comment]
It was perfect. 👍

**Comment by aequasi** [comment]
Does this only work on postgres? 

Potential use case: Using snowflakes as IDs. Would need to fire off an async request to get a snowflake, but they are highly unique.
