### ISSUE TITLE
How do I 'order by' the results of A DIV B.

### ISSUE THREAD

**Issue by fanzkday** [typeorm/typeorm#1145]
```
this.rep.createQueryBuilder('user')
  .orderBy('score DIV count', 'DESC')
  .getMany();
```
Error: ...'databaseName'...not exist.
How do I do that?
Thanks.

**Comment by pleerock** [comment]
Currently you can order only by a column, e.g. `.orderBy("user.score")`

**Comment by fanzkday** [comment]
ok.

**Comment by pleerock** [comment]
@fanzkday sorry I was wrong. It is actually supported, I added test to confirm it. Your actual issue was that you did not use aliases. Correct code is:

```ts
this.rep.createQueryBuilder('user')
  .orderBy('user.score DIV user.count', 'DESC')
  .getMany();
```
