### ISSUE TITLE
How to use LIKE in findAndCount

### ISSUE THREAD

**Issue by Flexiink** [typeorm/typeorm#1147]
<pre>
 const sqlConditions = {
            take: limit,
            skip: offset,
            where: 'name LIKE "%1323%"'
 };
 const [ items, count ] = await this._getRepository().findAndCount(sqlConditions);
</pre>

The code works correctly, but Webpack generates an error

<pre>
ERROR in ../categories.ts (96,75): Type '{ take: any; skip: number; where: string; }' has no properties in common with type 'DeepPartial<Categories>'
</pre>

Began to receive after update **Typescript** the top up to **2.4.2**

**Comment by pleerock** [comment]
right now `where` accepts object, not a string.

so what you are attempting to do is not by a design. But we probably can change this behaviour and support a string as well.

For now you must use query builder instead.

**Comment by Flexiink** [comment]
How can I extend this class so that I do not get an error?

<pre>
export interface FindOneOptions<Entity> {
    where?: Partial<Entity> | ObjectLiteral;
}
</pre>
to <code> where?: Partial<Entity> | ObjectLiteral **| string**; </code>

**Comment by pleerock** [comment]
Just change this interface and create a PR and I'll merge it.

**Comment by pleerock** [comment]
this must be already released in 0.1.3

**Comment by brendan-roche** [comment]
@pleerock this fix was never applied. Please see
https://github.com/typeorm/typeorm/pull/1307

**Comment by mantiqh** [comment]
We can doing it something like this.

```
async findAll(
    query: FindAllCategoriesQueryDto,
  ): Promise<Paginated<EcostoreCategory>> {
    const [result, total] = await this.categoryRepo.findAndCount({
      take: query.limit,
      skip: query.limit * (query.page - 1),
      select: ['id', 'image', 'description', 'name', 'active'],
      where: {
        active: query.active,
        name: query.name && ILike(`%${query.name}%`),
      },
    });

    return new Paginated<EcostoreCategory>({
      page: query.page,
      result,
      total,
    });
  }
```
