### ISSUE TITLE
Can't use .insert on an entity that contains @CreateDateColumn

### ISSUE THREAD

**Issue by ruimgoncalves** [typeorm/typeorm#1148]
I'm unable to use `insert` in an entity that has a column marked `@CreateDateColumn`, because the insert functions send this columns has a null value, causing a constraint error on the database.
The `save` functions does not have this issue.

```typescript
@Entity()
export class User {

    public name: string

    @CreateDateColumn({name : 'date_created'})
    public dateCreated?: string

}
```

```typescript

const uRepo = await getRepository(User)
const newUser = new User()
newUser.name = name

try {
    await uRepo.insert(newUser)
} catch (err) {
    console.error('User add error', err)   <--- Constraint Error date_created is send as NULL
}
```

**Comment by pleerock** [comment]
`insert` method does not support `@CreateDateColumn` updation. You need to use `save` method instead. This will be fixed in `0.2.0` version.

**Comment by pleerock** [comment]
I have released a first alpha version of 0.2.0, you can install it via `npm i typeorm@next` and try if it fixes your issue. Please let me know if its not.

But please note - `insert` method still has limited `save` functionality. Its purpose to quickly and efficiently insert data rows into the database. If you want to have all features provided by orm use `save` method instead.

**Comment by ruimgoncalves** [comment]
I updated to version 0.2.0 alpha1 and the problem described above seems to be solved, but now if I try to insert a record that has an OneToOne relation it fails with an undefined [affected column name]

```javascript
    @OneToOne(type => Test, test => test.id)
    @JoinColumn({name: 'test_id', referencedColumnName: 'id'})
    @PrimaryColumn({name: 'test_id', type : 'integer'})
    public test: Test
```

**Comment by pleerock** [comment]
can you show code you tried, your entity and what error you have
