### ISSUE TITLE
Feature: findOneOrFail

### ISSUE THREAD

**Issue by hmil** [typeorm/typeorm#1149]
Continuing on the discussion started in #122 .
Add a method `findOneOrFail` which returns a `Promise<T>` instead of a `Promise<T|undefined>` which is what `findOne` returns. The promise is rejected in case no result was found.

**motivation**: Helps to focus on the happy path when writing controller code (rejected promises naturally tend to trickle down into a single or a few error handlers which is less cumbersome than manually handling undefined values).

**additional consideration**: Expose a conventional error format to help users distinguish this kind of error from other errors. For instance, an HTTP framework could recognize the error and spit out a 404 instead of a 500 which it would normally produce.

I'll try to come up with a PR some time soon.

**Comment by pleerock** [comment]
Sounds good, except for additional consideration

> Expose a conventional error format to help users distinguish this kind of error from other errors. For instance, an HTTP framework could recognize the error and spit out a 404 instead of a 500 which it would normally produce.

I don't see any good design applied to typeorm to implement this. Instead, probably framework itself should be able to handle it. Routing-controllers has undocumented functionality called `errorOverridingMap ` which can be used to accomplish this behaviour in a simple way, something like this:

```ts
{
    errorOverridingMap: {
        "EntityNotFoundError": 404 // map any error with "EntityNotFoundError" name into 404 http error code
    }
}
```

Its quite old functionality I used few years ago, not sure if it works now, but I think you got an idea

**Comment by pleerock** [comment]
@hmil hope you don't forget about this feature 😉

**Comment by hmil** [comment]
I didn't, i am currently waiting for the big refactoring you are working on to get merged so I don't risk any conflict.  No rush here since  this issue is not a blocker. Just lmk when you are done ;)

**Comment by pleerock** [comment]
Oh you'll wait few month. Don't worry about conflicts, just do a minimal code you need against master, and I'll merge it to `next` branch by my own. We don't really have a reason to delay this feature.

**Comment by pleerock** [comment]
I'll close it since its already available in next.

**Comment by cojack** [comment]
@pleerock where its? I can not find it in `next`

**Comment by hmil** [comment]
It's [right there](https://github.com/typeorm/typeorm/blob/next/src/repository/Repository.ts#L293).
