### ISSUE TITLE
Response with an inexistant route or no result

### ISSUE THREAD

**Issue by Paul75** [typeorm/typeorm#1150]
Hello,

I use the defautl script generated in CLI by typeorm commande.

in the controller have :
`async all(request: Request, response: Response, next: NextFunction) {
        return this.userRepository.find();
    }

    async one(request: Request, response: Response, next: NextFunction) {
        return this.userRepository.findOneById(request.params.id);
    }

    async save(request: Request, response: Response, next: NextFunction) {
        return this.userRepository.save(request.body);
    }

    async remove(request: Request, response: Response, next: NextFunction) {
        await this.userRepository.removeById(request.params.id);
    }`

and routes : 
`export const Routes = [{
    method: "get",
    route: "/users",
    controller: UserController,
    action: "all"
}, {
    method: "get",
    route: "/users/:id",
    controller: UserController,
    action: "one"
}, {
    method: "post",
    route: "/users",
    controller: UserController,
    action: "save"
}, {
    method: "delete",
    route: "/users",
    controller: UserController,
    action: "remove"
}];`

And I do this in index.ts :
`// register express routes from defined application routes
    Routes.forEach(route => {
        (app as any)[route.method](route.route, (req: Request, res: Response, next: Function) => {
            const result = (new (route.controller as any))[route.action](req, res, next);
            if (result instanceof Promise) {
                result.then(result => result !== null && result !== undefined ? res.send(result) : undefined);

            } else if (result !== null && result !== undefined) {
                res.json(result);
            }
        });
    });`

But exemple if i do a localhost:3000/users/13 and the user 13 not defined, it not make a error but wait wait and long time say me not appear the page.

When I can return message error ?

Thanks

**Comment by pleerock** [comment]
What cli generates you is just a simple example of how you can use typeorm with express, you need to append extra logic on your own, everything else is just your imagination =)

What you can do it to add extract check like this:

```ts
} else if (result !== null && result !== undefined) {
            res.json(result);
} else if (result === undefined) {
            res.status(404);
            res.json({ error: "Object not found" });
}
```

**Comment by Paul75** [comment]
For me not works but solve it  when i get url with invalide user id or another search like :
in my repository :
`const user = await this.userRepository.findOneById(request.params.id);
        if (user) {
            response.status(200).json({success: true, user: user});
        } else {
            response.status(401).json('Unauthorized');
        }`

it now not wait and return 401 code directly ....

**Comment by pleerock** [comment]
Again, as I told its just a demo how you can use it with express. If you want a better experience use [routing-controllers](https://github.com/pleerock/routing-controllers) library - it works quite well with typeorm.

**Comment by Paul75** [comment]
Thanks :)
