### ISSUE TITLE
repository.save(entity) not returning columns

### ISSUE THREAD

**Issue by CocaColaBear** [typeorm/typeorm#1151]
Hi. I have problem with auto-generated id column (database generate value).
AccountEntity.ts:
```typescript
import { Column, Entity, Index } from "typeorm";

@Entity()
export default class Account extends BaseEntity {
	@Column({
		length: 128
	})
	@Index({
		unique: true
	})
	public email: string;

	@Column({
		length: 64
	})
	@Index()
	public password: string;
}
```
BaseEntity.ts:
```typescript
import { Column, CreateDateColumn, PrimaryColumn, UpdateDateColumn } from "typeorm";

export default abstract class BaseEntity {
	@PrimaryColumn({
		default: () => "new_id()",
		type: "bigint"
	})
	public id: string;

	@CreateDateColumn({
		default: () => "utcnow()",
		type: "timestamp"
	})
	public created: Date;

	@UpdateDateColumn({
		default: () => "utcnow()",
		type: "timestamp"
	})
	public updated: Date;
}
```
And then, when i'm use the code:
```typescript
const repository = connection.getRepository(Account);
const account = await repository.create({
	email: "test",
	password: "test"
});

repository.save(account).then((acc) => {
	console.log(acc);
});
```
```sql
executing query:  START TRANSACTION
executing query:  INSERT INTO "account"("email", "password", "created", "updated") VALUES ($1,$2,$3,$4)  -- PARAMETERS: ["test","test","2017-11-07T08:14:45.808Z","2017-11-07T08:14:45.808Z"]
executing query:  COMMIT
Account {
  email: 'test',
  password: 'test',
  updated: 2017-11-07T11:14:45.808Z,
  created: 2017-11-07T11:14:45.808Z }
```
id property not returned. 
TypeORM version: **0.1.2**

**Comment by pleerock** [comment]
its because only auto-generated values are returned, like auto-increment. But in 0.2.0 all default values also will be updated in entity, so this will be fixed in 0.2.0.

**Comment by pleerock** [comment]
I have released a first alpha version of 0.2.0, you can install it via `npm i typeorm@next` and try if it fixes your issue. Please let me know if its not.

**Comment by CocaColaBear** [comment]
@pleerock Thank you! All works fine :)

**Comment by CocaColaBear** [comment]
@pleerock but now, i get another issue. My entity contains lazy-load (not null) field:
`Promise<Account> account;`
But i can save entity. I know accountId and i try:
```
repository.create({ account: accountRepository.findOneById(accountId) });
repository.create({ account: Promise.resolve(accountId));
```
But they generate this query:
`INSERT INTO table ("accountId") VALUES (DEFAULT);`

**Comment by nolazybits** [comment]
I would like to give an update.
Really new to this library but it seems that save and create don't return the same object.
create won't add the id, whereas save will.
I'm using typeorm@next
`
"typeorm": "^0.2.0-alpha.7",
`

Thanks

**Comment by pleerock** [comment]
>  Really new to this library but it seems that save and create don't return the same object.

correct, `save` just returns the same object, and `create` creates a new object.

**Comment by nolazybits** [comment]
Thank you @pleerock , 
Well here my object is a new one so save actually create the object too isn't it?

My main question is why using this entity
`
import {Column, Entity, PrimaryColumn} from "typeorm";

@Entity("companies")
export class CompanyEntity
{
    @PrimaryColumn(
        {
            default: () => "gen_random_uuid()",
            type: "uuid",
        })
    public guid: string;

    @Column("text")
    public name: string;

    @Column("text")
    public description: string;

    @Column("text")
    public image_url: string;

    @Column("text")
    public website: string;
}
`
using `save` will return also the guid property whereas `create` won't.
In both case I do not provide the guid (as autogenerated, and it is a new item)

Thanks anyhow for this great library and really fast answers :) 👍

**Comment by pleerock** [comment]
* `create` DOES **NOT** SAVE YOUR ENTITY IN THE DATABASE.
* `save` DOES SAVE YOUR ENTITY IN THE DATABASE.

Create simply creates instance of your object from the given plain javascript object, it does not save your object in the database thus database does not return any generated uuid for you.

**Comment by nolazybits** [comment]
Thanks for the answer @pleerock.

**Comment by avantjustus** [comment]
This still doesn't seem to work in version `0.2.7`

**Comment by mendrik** [comment]
@avantjustus I had the same issue and found out that I was using  `@PrimaryColumn` instead of `@PrimaryGeneratedColumn`. After I switched, it worked just fine.

**Comment by lemadane** [comment]
@mendrik why did it did not worked for me, i am using the latest version?
