### ISSUE TITLE
findOneById : discrepancy between docs and code

### ISSUE THREAD

**Issue by hmil** [typeorm/typeorm#1153]
According to [this comment](https://github.com/typeorm/typeorm/issues/122#issuecomment-342369081), findOneById should be deprecated.
[The doc](http://typeorm.io/#/repository-api) is ambiguous here and the code doesn't seem to expose the api `findOne(id)`.

There seems to be an inconsitency between (1) the doc, (2) the comment above, (3) the code.
(1) and (2) can be reconciliated by doing something along [those lines](https://github.com/typeorm/typeorm/compare/master...hmil:find-one-id?expand=1) but I don't know about (3). It looks to me as if this was never actually implemented.

**Comment by pleerock** [comment]
Hmm maybe I replaced docs not on the master branch... feel free to create a PR, as I already told findOneById is deprecated and must be replaced with findOne

**Comment by hmil** [comment]
I'll wait until #1049 gets merged and see if this issue persists.

**Comment by pleerock** [comment]
I think it wont be merged this month for sure

**Comment by pleerock** [comment]
Okay so let me clean things here. `findOneById` isn't deprecated on master (0.1.x) right now. But its already removed in next (0.2.x). So, you'll need to use `findOneById` until you upgrade to 0.2.x and once you upgrade you need to fix all breaking changes. I think this issue can be closed now.
