### ISSUE TITLE
Question : have option to do a unique column ? not null ? with mysql ?

### ISSUE THREAD

**Issue by Paul75** [typeorm/typeorm#1155]
Hello,

Have a question it have a option to do a unique column ? not null ? with mysql ?

Thanks

**Comment by pleerock** [comment]
```ts
@Column({ nullable: false, unique: true })
```

**Comment by Paul75** [comment]
Thanks but when I do this and start server it do error : 'sqlMessage: 'Specified key was too long; max key length is 767 bytes','

Defien like : 
@Column({ nullable: false, unique: true })
idrh: string

Why ?

**Comment by pleerock** [comment]
check what sql it generates you by enabling logging and see why it fails

**Comment by Paul75** [comment]
Dit say thar column have 255 caracters ans too long... 

But if generate autoatically with string property

⁣Envoyé par TypeApp ​

Le 9 nov. 2017 à 06:51, à 06:51, Umed Khudoiberdiev <notifications@github.com> a écrit:
