### ISSUE TITLE
QueryFailedError: null value after delete and adding column on entity

### ISSUE THREAD

**Issue by dee-el** [typeorm/typeorm#1156]
I want asking something about synchronize on template using typeorm cli, after the sync happen
i am deleting some columns and adding new columns (not using migration),
but old columns still created on synchronize even after i delete the table, how to handle this?
EDIT:
im using postgres.
What am i do just `typeorm -n typeorm --db postgres`
then install packages then i try running it.
After that i deleting column (firstName, lastName) on entity `User` and add `fullName`
still synchronize value still `true`. i'm hoping it will be create new table (yes it happened but old deleted column still created)
please help me

**Comment by pleerock** [comment]
> i'm hoping it will be create new table

"new table" or "new column"? It must create a new column and delete old columns. Are you sure you re-compiled your project?

**Comment by pleerock** [comment]
Closing as no answer from reporter.
