### ISSUE TITLE
Getting error while writing many to many relation in my entity model

### ISSUE THREAD

**Issue by vipswelt** [typeorm/typeorm#1158]
I am creating an entity as below

    import { Entity, Column, PrimaryGeneratedColumn, ManyToMany } from 'typeorm';
    
    import { UserRoleEntity } from './user-roles.entity';
    
    @Entity('Users')
    export class UserEntity {
    
        @PrimaryGeneratedColumn()
        UserId: number;
    
        @Column()
        FirstName: string;
    
        @Column()
        LastName: string;
    
        @Column()
        MobileNo: string;
    
        @ManyToMany(userRole => UserRoleEntity, userRole =>userRole.userRoles)
        userRoles: UserRoleEntity[];
    }

when i am running my application getting an error as below

> [0]
[1] [0] ERROR in server/models/entities/user.entity.ts(44,17): error TS6133: 'type' is declared but its value is never read.
[1] [0]
> 
> ERROR in Error: TypeError: Cannot read property 'kind' of undefined
> [1] [0]     at nodeCanBeDecorated
> (D:\Projects\MEAN\finception\node_modules\typescript\lib\typescript.js:8344:36)
> [1] [0]     at nodeIsDecorated
> (D:\Projects\MEAN\finception\node_modules\typescript\lib\typescript.js:8364:16)
> [1] [0]     at Object.nodeOrChildIsDecorated
> (D:\Projects\MEAN\finception\node_modules\typescript\lib\typescript.js:8368:16)

how can i ignore this behavior?

**Comment by pleerock** [comment]
Can you remove peaces of functionality and check where exactly problem is? Test a minimal entity example first. Error you have is generated by typescript compiler and does not look like its related to typeorm somehow, make sure you have latest typescript compiler

**Comment by vipswelt** [comment]
i am saving my records as below
`return this._userRepository.save(_user, { relations: ['userRoles'] });`
and getting an error

> QueryFailedError: RequestInvalid object name 'users_roles__user_roles'.

**Comment by pleerock** [comment]
@vipswelt did you solve your issue?

**Comment by pleerock** [comment]
Closing as no answer from reporter.

**Comment by kthffmn** [comment]
If anyone is still encountering this issue, removing `noUnusedParameters: true` from my `tsconfig.json` file fixed it for me.

**Comment by pengstrom** [comment]
@kthffmn Well yeah, but it also disables a useful warning project-wide. I'd suggest renaming it with an underscore e.g.
```typescript
@ManyToOne(_type => TempUser, tempUser => tempUser.tokens)
```
or even using the unit type-ish:
```typescript
@ManyToOne(() => TempUser, tempUser => tempUser.tokens)
```
which signals that the parameter is known to be unused.

On the other hand I don't know why the parameter is needed. Why can't we just do
```typescript
@ManyToOne(TempUser, tempUser => tempUser.tokens)
```
or is there som TypeScript details getting in the way?

**Comment by jakobwgnr** [comment]
Changing this as it would provide an lint-error (no unused variables).
