### ISSUE TITLE
Unique primary columns fails to error on duplicate

### ISSUE THREAD

**Issue by SamuelMarks** [typeorm/typeorm#1159]
My model is like this:

```typescript
import { Entity, PrimaryColumn } from 'typeorm';

@Entity('foo_tbl')
export class Foo {
    @PrimaryColumn({ type: 'varchar', length: 10 })
    can: string;

    @PrimaryColumn({ type: 'varchar', length: 10 })
    bar: string;
}
```

```typescript
const foo = new Foo();
foo.bar = 'haz'
foo.can = 'bzr'
o.typeorm.connection.manager
 .save(foo)
 .then((foo_obj: Foo) => {})
 .catch(console.error.bind(console))
o.typeorm.connection.manager
 .save(foo)
 .then((foo_obj: Foo) => {})
 .catch(console.error.bind(console))
```
But I get no errors (Postgres. Checking the table in Postgres it is correct with: `Indexes:
    "foo_tbl_pkey" PRIMARY KEY, btree (bar, can)`

From your docs it appears that this functionality is to be expected: http://typeorm.io/#/entities/primary-columns

How do I disable it, or somehow check that it doesn't exist (without running my own `.find` within a transaction)?

**Comment by pleerock** [comment]
Im not sure if I completely understand your problem. Your problem is that you DON'T have an error, am I right?

**Comment by SamuelMarks** [comment]
Correct, I should get a unique error or something. But here both work and the database only has 1 row.

So functionally it's fine, but it's not what I'm expecting and I would prefer to throw an error

**Comment by pleerock** [comment]
But don't you find it strange that database itself does not give any error to you?

**Comment by pleerock** [comment]
Oh wait probably now I completely got your request

**Comment by pleerock** [comment]
```ts
const foo = new Foo();
foo.bar = 'haz'
foo.can = 'bzr'
o.typeorm.connection.manager
 .save(foo)
 .then((foo_obj: Foo) => {})
 .catch(console.error.bind(console))
o.typeorm.connection.manager
 .save(foo)
 .then((foo_obj: Foo) => {})
 .catch(console.error.bind(console))
```

This will never give you error, just like this code:

```ts
const foo = new Foo(); // foo has only one primary key and its auto-generated (identity)
o.typeorm.connection.manager
 .save(foo)
 .then((foo_obj: Foo) => {})
 .catch(console.error.bind(console))
o.typeorm.connection.manager
 .save(foo)
 .then((foo_obj: Foo) => {})
 .catch(console.error.bind(console))
```

Because `save` method's purpose is to synchronise your model, its not dummy "insert" process. It updates model in the database if it sees changes in it second time you call `save` method.

**Comment by SamuelMarks** [comment]
Hmm, so how am I meant to do this? - DB inserts such that second inserts fail?

**Comment by pleerock** [comment]
Use `find` and check if your record already exist. Alternatively, you can use insert query builder which does not check anything and does raw insertion.

**Comment by SamuelMarks** [comment]
That's weird, I need to use query builder just for a normal insert?

Wouldn't it be more sense to have this configurable, similar to:
```typescript
o.typeorm.connection.manager
 .save(foo, {findFirst: false})
 .then((foo_obj: Foo) => {})
 .catch(console.error.bind(console))
```

**Comment by pleerock** [comment]
try to use o.typeorm.connection.manager.insert method

**Comment by SamuelMarks** [comment]
Hmm, this syntax? - http://typeorm.io/#/insert-query-builder

**Comment by pbrickell** [comment]
I think there should be some king of option here. If I have a one to many relationship a->b and someone tries the save c->b b is now related to c. This, in most cases, is surely unintended. I don't know of any (not exhaustive) ORM that does this. Surely a constraint violation is more normal?

**Comment by 1valdis** [comment]
I can confirm that this was unexpected behaviour for me. I expected to get duplicate primary key error or something. But on the other hand now I understand why it's done this way and have nothing against that.
