### ISSUE TITLE
TYPEORM : QueryFailedError: Request Invalid object name 'user_roles user_roles'

### ISSUE THREAD

**Issue by vipswelt** [typeorm/typeorm#1163]
@pleerock My UserEntity as below

```
import { Entity, Column, PrimaryGeneratedColumn, ManyToMany, JoinTable } from 'typeorm';

import { UserRoleEntity } from './user-roles.entity';

@Entity('Users')
export class UserEntity {

    @PrimaryGeneratedColumn()
    UserId: number;

    @Column()
    FirstName: string;

    @Column()
    LastName: string;

    @ManyToMany(_type => UserRoleEntity, roles => roles.users, {
        cascadeInsert: true
    })
    @JoinTable()
    roles: UserRoleEntity[];
}
```

and my role entity as below
```
import { Entity, Column, PrimaryGeneratedColumn, ManyToMany } from 'typeorm';

import { UserEntity } from './user.entity';

@Entity('UserRoles')
export class UserRoleEntity {

    @PrimaryGeneratedColumn()
    UserRoleId: number;

    @Column()
    UserId: number;

    @ManyToMany(_type => UserEntity, user => user.roles, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    users: UserEntity[];
}
```

and my find and save code as below

```
GetAllUsers() {
        return this._userRepository.find({ relations: ['roles'] });
    }

    CreateUser(_user: UserEntity) {
        console.log('usersRepository', JSON.stringify(_user));
        return this._userRepository.save(_user, { relations: ['roles'] });
    }

```

please help me to find the solution, its urgent. 
should i have to create relations in my mssql  db

my tables as below

![image](https://user-images.githubusercontent.com/28600288/32648000-ec36f3b6-c619-11e7-8359-6d7945a3200c.png)

**Comment by pleerock** [comment]
I don't see what you are saving. Can you save your user separately and your user roles separately as well and check if you have issue? Also, can you create a failing test for your issue?

**Comment by vipswelt** [comment]
when i am saving them separately by keeping UserRoles = [] in Usesr entity its working good, but with roles it is not saving the records.. 

i am doing this as below

```
> public _userRepository: any;
>     public _userRoleRepository: any;
> 
>     constructor() {
>         this._userRepository = getManager().getRepository(UserEntity);
>         this._userRoleRepository = getManager().getRepository(UserRoleEntity);
>     }
```
its working if i am doing as below
```
const roles = await this._userRoleRepository.save(user.roles);
        user.roles = [];
        const savedUsers = await this._userRepository.save(user);
        savedUsers.roles = roles;
        return await savedUsers;
```

and will not work if i do this as below

`const savedUsers = await this._userRepository.save(user);`

even getting error when i am finding records as below
`const users = await this._userRepository.find({relations : ['roles']}); `

error is as below

> > query failed: SELECT "e"."id" AS "e_id", "e"."CreatedByUserUId" AS "e_CreatedByUserUId", "e"."UpdatedByUserUId" AS "e_UpdatedByUserUId", "e"."CreatedOn" A
> S "e_CreatedOn", "e"."UpdatedOn" AS "e_UpdatedOn", "e"."IsActive" AS "e_IsActive", "e"."IsDeleted" AS "e_IsDeleted", "e"."FirstName" AS "e_FirstName", "e"."LastNa
> me" AS "e_LastName", "e"."MobileNo" AS "e_MobileNo", "e"."EmailAddress" AS "e_EmailAddress", "e"."UserUId" AS "e_UserUId", "roles"."id" AS "roles_id", "roles"."Cr
> eatedByUserUId" AS "roles_CreatedByUserUId", "roles"."UpdatedByUserUId" AS "roles_UpdatedByUserUId", "roles"."CreatedOn" AS "roles_CreatedOn", "roles"."UpdatedOn"
>  AS "roles_UpdatedOn", "roles"."IsActive" AS "roles_IsActive", "roles"."IsDeleted" AS "roles_IsDeleted", "roles"."UserId" AS "roles_UserId", "roles"."UserUId" AS
> "roles_UserUId", "roles"."RoleType" AS "roles_RoleType" FROM "Users" "e" LEFT JOIN "users_roles__user_roles" "e_roles" ON "e_roles"."usersId"="e"."id" LEFT JOIN "
> UserRoles" "roles" ON "roles"."id"="e_roles"."userRolesId"
> [0] [1] error: { RequestError: Invalid object name 'users_roles__user_roles'.
> [0] [1]     at handleError (D:\Projects\MEAN\finception\node_modules\mssql\lib\tedious.js:519:15)
> [0] [1]     at emitOne (events.js:115:13)
> [0] [1]     at Connection.emit (events.js:210:7)
> [0] [1]     at Parser.<anonymous> (D:\Projects\MEAN\finception\node_modules\tedious\lib\connection.js:489:16)
> [0] [1]     at emitOne (events.js:115:13)
> [0] [1]     at Parser.emit (events.js:210:7)
> [0] [1]     at Parser.<anonymous> (D:\Projects\MEAN\finception\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
> [0] [1]     at emitOne (events.js:115:13)
> [0] [1]     at Parser.emit (events.js:210:7)
> [0] [1]     at addChunk (D:\Projects\MEAN\finception\node_modules\readable-stream\lib\_stream_readable.js:284:12)
> [0] [1]   code: 'EREQUEST',
> [0] [1]   number: 208,
> [0] [1]   lineNumber: 1,
> [0] [1]   state: 1,
> [0] [1]   class: 16,
> [0] [1]   serverName: 'CSHARP\\LOCALHOST',
> [0] [1]   procName: '',
> [0] [1]   originalError:
> [0] [1]    { Error: Invalid object name 'users_roles__user_roles'.
> [0] [1]     at handleError (D:\Projects\MEAN\finception\node_modules\mssql\lib\tedious.js:517:19)
> [0] [1]     at emitOne (events.js:115:13)
> [0] [1]     at Connection.emit (events.js:210:7)
> [0] [1]     at Parser.<anonymous> (D:\Projects\MEAN\finception\node_modules\tedious\lib\connection.js:489:16)
> [0] [1]     at emitOne (events.js:115:13)
> [0] [1]     at Parser.emit (events.js:210:7)
> [0] [1]     at Parser.<anonymous> (D:\Projects\MEAN\finception\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
> [0] [1]     at emitOne (events.js:115:13)
> [0] [1]     at Parser.emit (events.js:210:7)
> [0] [1]     at addChunk (D:\Projects\MEAN\finception\node_modules\readable-stream\lib\_stream_readable.js:284:12)
> [0] [1]      info:
> [0] [1]       { number: 208,
> [0] [1]         state: 1,
> [0] [1]         class: 16,
> [0] [1]         message: 'Invalid object name \'users_roles__user_roles\'.',
> [0] [1]         serverName: 'CSHARP\\LOCALHOST',
> [0] [1]         procName: '',
> [0] [1]         lineNumber: 1,
> [0] [1]         name: 'ERROR',
> [0] [1]         event: 'errorMessage' } },
> [0] [1]   name: 'RequestError',
> [0] [1]   precedingErrors: [] }
> [0] [1] error: GetAllUsers:: QueryFailedError: Error: Invalid object name 'users_roles__user_roles'.

**Comment by pleerock** [comment]
can you tell me typeorm version are you using?

**Comment by vipswelt** [comment]
0.1.x

**Comment by vipswelt** [comment]
Also tested it on 0.2.x beta

**Comment by vipswelt** [comment]
can you please take a team viewer session, i need just 10 minutes of your...

**Comment by vipswelt** [comment]
can you please take a team viewer session, i need just 10 minutes of your...

**Comment by vipswelt** [comment]
I told you everything as much as i could ... still didn't get the solution..:(.. @pleerock

**Comment by pleerock** [comment]
Create a failing test, just like others do. Take a look how other tests are organized and create your own with failing test functionality, and I won't have other choice other then help and resolve your issue 😉

**Comment by pleerock** [comment]
Closing as no answer from reporter.
