### ISSUE TITLE
@CreateDateColumn and @UpdateDateColumn problem with timestamp type

### ISSUE THREAD

**Issue by kronodevcom** [typeorm/typeorm#1166]
I use postgre, for my entity:   

@Column({ type: 'timestamp with time zone'})  works fine, I created the column with this data type.

But when I use: @CreateDateColumn({ type: 'timestamp with time zone'}) create the column with the data type: 'timestamp without time zone'.

It's the same problem with the @UpdateDateColumn.

Thanks, for your time and this excellent ORM.

<img width="1009" alt="screen shot 2017-11-10 at 9 42 11 pm" src="https://user-images.githubusercontent.com/17317721/32684218-53679f22-c660-11e7-9d80-4835b7fb5868.png">

**Comment by NoNameProvided** [comment]
Related to #838

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.25`. You can try it via `npm i typeorm@next`.

**Comment by kronodevcom** [comment]
Thanks!

**Comment by neumartin** [comment]
Can I configure a global session timezone with pg at driver level?
