### ISSUE TITLE
PostgreSQL migrations ALTER TYPE ADD VALUE transaction error

### ISSUE THREAD

**Issue by romanszedzielorz** [typeorm/typeorm#1169]
PostgreSQL 9.4 - migrations (typeorm@0.1.2) - ALTER TYPE ADD VALUE - is not working because it can't be done in transaction:
> ALTER TYPE ... ADD VALUE (the form that adds a new value to an enum type) cannot be executed inside a transaction block.

source: https://www.postgresql.org/docs/9.4/static/sql-altertype.html

Do you have any idea, if there is a solution for it?

Maybe this transaction can be disabled in general or just for one migration?
For example Liquibase is not putting all new migration requests into one transaction, so when 4th of 10 query will fail, first 3 will be executed. 

Console dump:
```
executing query:  SELECT * FROM "migrations" "migrations"
13 migrations are already loaded in the database.
(...)
1 migrations are new migrations that needs to be executed.
executing query:  START TRANSACTION
executing query:
            ALTER TYPE public.item_type
                ADD VALUE 'b' AFTER 'a';

query failed:
            ALTER TYPE public.item_type
                ADD VALUE 'b' AFTER 'a';

error:  { error: ALTER TYPE ... ADD nie można wykonać wewnątrz bloku transakcji // error:  { error: ALTER TYPE ... ADD can't be executed inside transaction block
    at Connection.parseE (xxx\node_modules\pg\lib\connection.js:546:11)
    at Connection.parseMessage (xxx\node_modules\pg\lib\connection.js:371:19)
    at Socket.<anonymous> (xxx\node_modules\pg\lib\connection.js:114:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'error',
  length: 133,
  severity: 'BŁĄD', // ERROR
  code: '25001',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'xact.c',
  line: '3156',
  routine: 'PreventTransactionChain' }
executing query:  ROLLBACK
```

**Comment by pleerock** [comment]
you can use `queryRunner.connection.query(`...`)` which will be executed out of the current transaction.

**Comment by pleerock** [comment]
@romanszedzielorz is your problem solved?

**Comment by romanszedzielorz** [comment]
@pleerock I didn't forgot about this task/issue, but I'm working in another project now. I should be able to test it tomorrow. I will write comment here after tests...

**Comment by romanszedzielorz** [comment]
`queryRunner.connection.query(...)` is working correct, so **it is a solution** for this problem.

But be careful, because when you have few such request and some will fail, success querys will be executed, but no inserts will be done in 'migrations' table. So running migration next time, the same prevoius success executed querys will be executed again. This is the down side of skipping transaction.

@pleerock Thanks for help. Sorry, for such long answer time.
