### ISSUE TITLE
ManyToMany is not possible as in 0.0.11 version

### ISSUE THREAD

**Issue by szymonskirgajllo** [typeorm/typeorm#1170]
Hi,

`typeorm@0.1.2`
`node@6.9.2`

i have two claasses

```
@Entity()
export class Module {

    @PrimaryColumn('varchar') // "string" will be available in 0.2.0
    public name: string;

    @ManyToMany(type => Service, service => service.modules)
    @JoinTable()
    public services: Array<Service> = [];
```

and

```
@Entity()
export class Service {

    @PrimaryColumn('varchar') // "string" will be available in 0.2.0
    public name: string;

    @ManyToMany(type => Module, module => module.services)
    modules: Array<Module>;
```

and everything would be fine but it generates tables like "module_service_service" instead of "module_service_service_name"

can you help me or it is some bug in typeorm@0.1.2 and i have to wait for fix?

**Comment by romanszedzielorz** [comment]
Hi, 
"it generates tables" - what does it mean?
1) TypeORM generate table and you don't like it name?
2) SQL query generated by TypeORM is using other table name that you wanted/that was generated on previous version?

If you create tables by your own (point 2) from above), you can pass your table name into JoinTable:

> @ManyToMany(type => Service, service => service.modules)
> @JoinTable({
> &nbsp;&nbsp;&nbsp; name: 'module_service_service_name'
> })
> public services: Array<Service> = [];

**Comment by szymonskirgajllo** [comment]
@romanszedzielorz thanks for reply

i tried to generate tables via auto synchronize

in 0.0.11 version it generates module_service_service_name
but in 0.1.2 module_service_service

i'll try to use JoinTable with name parameter

**Comment by szymonskirgajllo** [comment]
@romanszedzielorz looks ok, thanks :)
