### ISSUE TITLE
CreateDateColumn and UpdateDateColumn error

### ISSUE THREAD

**Issue by aspandolfi** [typeorm/typeorm#1172]
CreateDateColumn and UpdateDateColumn are not working in MySQL. The syntax when the tabela is creating is not correct. Therefore, MySQL throws exception.

**Comment by pleerock** [comment]
can you show me error you have and code you are running? Also mysql version. There are tests which completely cover this functionality and it cannot be broken.

**Comment by pleerock** [comment]
duplicate of #609
