### ISSUE TITLE
`repository.updateById` won't trigger `BeforeUpdate` or `AfterUpdate`

### ISSUE THREAD

**Issue by mmiszy** [typeorm/typeorm#1173]
`repository.updateById` won't trigger `BeforeUpdate` or `AfterUpdate`. When you updated entities using `updatedById` `BeforeUpdate` never get called `AfterUpdate`.

Tested on typeorm@0.1.2 and typeorm@next.

**Comment by pleerock** [comment]
subscribers and listeners are very tricky. Lets say we have a post model with listeners applied:

```ts
@Entity()
export class Post {
     ....
     @BeforeUpdate()
     beforeUpdate() {
           this.counter += 1;
     }
}
```

When you are calling `updateById(id, updateMap)` by id it does roughly following:

```ts
updateById(id, updateMap) {
   return createQueryBuilder()
     .update()
     .set(updateMap)
     .where({ id: id })
     .execute();
}
```

What this query builder does - it builds `UPDATE post SET ... WHERE id = :id` and executes it. That's all. There is no entity which method can be called, e.g. to call this listener we need to do `post.beforeUpdate()` but there is no `post` instance anywhere in this method.

Those methods (delete, update, query builders) must be used when you want to execute quick query without extra checks and queries. `save` and `remove` methods do much more, but they cover all functionality typeorm has. So, you must use them instead.

**Comment by pleerock** [comment]
Let me know if I did not answer your question.
