### ISSUE TITLE
Lazy loading entities not save

### ISSUE THREAD

**Issue by CocaColaBear** [typeorm/typeorm#1180]
I'm using **TypeORM 0.2.0-alpha.1**
My entity contains lazy-load (not null, without default value) entity:
`account: Promise<Account>;`
But i cannot save entity. I know accountId and i try:
``` ts
repository.create({ account: accountRepository.findOneById(accountId) });
// or
repository.create({ account: Promise.resolve(accountId));
// or
repository.create({ account: Promise.resolve({ id: accountId }));
```
But they generate this query:
`INSERT INTO table ("accountId") VALUES (DEFAULT);`
Any suggestions?

**Comment by pleerock** [comment]
Do you have this issue only when `create` method is used?

**Comment by CocaColaBear** [comment]
@pleerock, yes, create. After create i use save method

**Comment by pleerock** [comment]
Create wasn't supposed to work with promises, at least it was't designed so. I'll investigate this issue.

**Comment by pleerock** [comment]
Lazy relations are very specific. To make this case work you need to use special `PromiseUtils.create` method:

```ts
        const child = connection.manager.create(Child, {
            name: "Child",
            parent: PromiseUtils.create(parent)
        });
```

This fix will be available in `alpha.7`

**Comment by svicalifornia** [comment]
Has this fix been released yet?

**Comment by seawatts** [comment]
I am having this same issue with version `0.2.31`
