### ISSUE TITLE
Issue with ionic and IOS

### ISSUE THREAD

**Issue by jondediego** [typeorm/typeorm#1181]
Trying to deploy an ionic project that uses typeorm on a IOS8 device is failling.
File vendor.js contains this code:
```js
"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const typeorm_1 = __webpack_require__(1);
const typedi_1 = __webpack_require__(3);

/**
 * Allows to inject an Connection using typedi's Container.
 */
function OrmConnection(connectionName = "default") {
    return function (object, propertyName, index) {
        typedi_1.Container.registerHandler({ object, index, propertyName, value: () => {
                const connectionManager = typedi_1.Container.get(typeorm_1.ConnectionManager);
                if (!connectionManager.has(connectionName))
                    throw new Error(`Cannot get connection "${connectionName}" from the connection manager. ` +
                        `Make sure you have created such connection. Also make sure you have called useContainer(Container) ` +
                        `in your application before you established a connection and importing any entity.`);
                return connectionManager.get(connectionName);
            } });
    };
}
exports.OrmConnection = OrmConnection;
//# sourceMappingURL=OrmConnection.js.map
```

Safari 8 fails as it doesn't unserstand es6 const. Should I use a customizes tsconfig file?
After looking at code, this code is on typeorm-typedi extension. It is transpiled to ES6. Could it be transpiled to ES5 instead?

**Comment by daniel-lang** [comment]
Could you explain why your ionic project depends on typedi? I don't have that dependenccy in the demo project. Typedi has it's own [repo](https://github.com/pleerock/typedi), maybe create an issue there about ES6

**Comment by pleerock** [comment]
Looks like `typeorm-typedi-extensions` is compiled into `es6`. We can compile it into `es5` and it should solve the issue

**Comment by pleerock** [comment]
@jondediego can you please try to update version to `0.1.1` ?

**Comment by jondediego** [comment]
If you could do it, it would be great! I am using typorm-typdi-extensions in order to inject customized repositories.

**Comment by daniel-lang** [comment]
@jondediego Did you checkout `typeorm-typedi-extensions@0.1.1`?

**Comment by jondediego** [comment]
I am on holidays and I won't be able to test this until 5th of december.

**Comment by pleerock** [comment]
Okay thats quite a lot of time so let me close this issue and let me know if that wont work for you. But Im sure it will =)
