### ISSUE TITLE
Can not use alias in find()

### ISSUE THREAD

**Issue by szymonskirgajllo** [typeorm/typeorm#1185]
Hi,

typeorm:0.0.11

when i use 
```
...find({alias: 'test'});
```

then typeorm throws unhandled rejections: 
```
Unhandled rejection Error: ER_BAD_FIELD_ERROR: Unknown column 'test.alias' in 'where clause'
```

is it fixed in newest version? i.e. typeorm@0.1.2?

**Comment by pleerock** [comment]
Yes new version find syntax is simplified and does not have an `alias` parameter. Find now accepts set of typeorm-specific options or conditions, e.g. entity column - value set. See updated find options docs on site.

**Comment by szymonskirgajllo** [comment]
@pleerock thanks, so we need to update typeorm ;)
