### ISSUE TITLE
Error if compiled with "compilerOptions" - "target": "es6"

### ISSUE THREAD

**Issue by extart** [typeorm/typeorm#1187]
Project on Ionic 3. Compilation is successful, but when starting on the device, an error occurs - "main.js: 7 Uncaught ReferenceError: Author is not defined"
How to compile the project under ECMAScript 6?

**Comment by extart** [comment]
Exactly the same error in the example project - https://github.com/typeorm/ionic-example

**Comment by daniel-lang** [comment]
@pleerock you can see what I had to say about this issue over at typeorm/ionic-example#1.

**Comment by pleerock** [comment]
closing as duplicate.
