### ISSUE TITLE
Failed to connect to tcp:server.windows.net:1433 - getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by vipswelt** [typeorm/typeorm#1188]
how can i connect to my server database 'MSSQL'

here is my config file
```
import 'reflect-metadata';
import { ConnectionOptions } from 'typeorm';

import { UserEntity } from '../models/entities/user.entity';
import { UserRoleEntity } from '../models/entities/user-roles.entity';

export let dbOptions: ConnectionOptions = {
    type: 'mssql',
    host: 'tcp:server.windows.net',
    port: 1433,
    username: 'user@sqlserver.database.windows.net',
    password: 'password',
    database: 'TestDB',
    entities: [
        UserEntity,
        UserRoleEntity
    ],
    synchronize: true,
    logging: ['error', 'warn', 'schema'],
    maxQueryExecutionTime: 1000,
    logger: 'file'
};
```

here is error i got

> TypeORM connection error:  { ConnectionError: Failed to connect to tcp:server.windows.net:1433 - getaddrinfo ENOTFOUND tcp:server.windows.net:1433
>     at Connection.tedious.once.err (D:\Projects\Finception\dev\node_modules\mssql\lib\tedious.js:216:17)
>     at Object.onceWrapper (events.js:316:30)
>     at emitOne (events.js:115:13)
>     at Connection.emit (events.js:210:7)
>     at Connection.socketError (D:\Projects\Finception\dev\node_modules\tedious\lib\connection.js:869:14)
>     at D:\Projects\Finception\dev\node_modules\tedious\lib\connection.js:739:25
>     at GetAddrInfoReqWrap.callback (D:\Projects\Finception\dev\node_modules\tedious\lib\connector.js:68:18)
>     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:107:17)
>   code: 'ESOCKET',
>   originalError:
>    { ConnectionError: Failed to connect to tcp:server.windows.net:1433 - getaddrinfo ENOTFOUND tcp:server.windows.net:1433
>     at ConnectionError (D:\Projects\Finception\dev\node_modules\tedious\lib\errors.js:12:12)
>     at Connection.socketError (D:\Projects\Finception\dev\node_modules\tedious\lib\connection.js:869:30)
>     at D:\Projects\Finception\dev\node_modules\tedious\lib\connection.js:739:25
>     at GetAddrInfoReqWrap.callback (D:\Projects\Finception\dev\node_modules\tedious\lib\connector.js:68:18)
>     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:107:17)
>      message: 'Failed to connect to tcp:server.windows.net:1433 - getaddrinfo ENOTFOUND tcp:server.windows.net:1433',
>      code: 'ESOCKET' },
>   name: 'ConnectionError' }

please tell what to change in my config for connecting to server database...

**Comment by pleerock** [comment]
its not related to typeorm somehow. Check your connection credentials, server settings, etc.

**Comment by pleerock** [comment]
also you have a strange username

**Comment by vipswelt** [comment]
this is my connection string... 
```
<databases>
      <add name="defaultConnection" connectionString="Data Source=tcp:testdevsqlserver.database.windows.net,1433;Initial Catalog=TestCoreDb;User Id=testadmin@testdevsqlserver.database.windows.net;Password=Test123;" providerName="System.Data.SqlClient" type="Sql" targetDatabaseEngineType="sqlazuredatabase" targetServerVersion="Version100" />
    </databases>
```

**Comment by vipswelt** [comment]
is there any support for azure database...?

**Comment by vipswelt** [comment]
please reply... #urgent

**Comment by pleerock** [comment]
yeah there are were people who were using typeorm with azure. Try to ask people on gitter

**Comment by vipswelt** [comment]
thanks... its connected i used

`options: {encrypt: true}, in my config file`

but getting a warning now, help me if it could be solved

> (node:73628) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.Socket instead.

**Comment by pleerock** [comment]
I guess its a question to underlying driver - node-mssql

**Comment by mehtanilay10** [comment]
I face the same issue and found below config as a solution.
Posting here so it can help someone else.

> **Note**: I have not included tcp or port in `host` as well as db-server name in `username` configs.

```
{
    "type": "mssql",
    "host": "<db-server-name>.database.windows.net",
    "username": "<just-username>",
    "password": "<your-db-server-password>",
    "database": "<your-db-name>",
    "extra": {
        "options": {
            "encrypt": true
        }
    },
    ...
}
```
