### ISSUE TITLE
My table does not have PrimaryColumn, but MissingPrimaryColumnError

### ISSUE THREAD

**Issue by ErikSchults** [typeorm/typeorm#1190]
These tables don't have primary columns and they don't need any, yet I see this in console: 
`(node:8518) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MissingPrimaryColumnError: Entity "EcbFxRate" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.
`
```
import { Entity, Column, CreateDateColumn, Index } from 'typeorm';

@Entity('ecb_fx_rates', { skipSync: true })
@Index('date_currency', (rate: EcbFxRate) => [rate.date, rate.currency], { unique: true })
export default class EcbFxRate {
	@Column({ type: 'date' })
	public date: Date;

	@Column({ type: 'varchar', length: 3 })
	public currency: string;

	@Column({ type: 'decimal', length: '18,6' })
	public rate: number;

	@CreateDateColumn({ name: 'created_at' })
	public createdAt: Date;
}
```
```
import { Entity, PrimaryGeneratedColumn, JoinColumn, ManyToOne, Column } from 'typeorm';
import Subscription from './Subscription';
import CrmUser from './CrmUser';

@Entity('subscription_users', { skipSync: true })
export default class SubscriptionUser {
	@ManyToOne(() => CrmUser, crmUser => crmUser.subscriptionUsers)
	@JoinColumn({ name: 'crm_user_id' })
	public crmUser: CrmUser;

	@Column({ name: 'crm_user_id', type: 'int' })
	public crmUserId: number;

	@ManyToOne(() => Subscription, subscription => subscription.users, { cascadeRemove: true })
	@JoinColumn({ name: 'subscription_id' })
	public subscription: Subscription;

	@Column({ name: 'subscription_id', type: 'int' })
	public subscriptionId: number;
}

```
Why?

**Comment by pleerock** [comment]
Because typeorm needs some entity identifier when it loads, saves, etc. does all operations for you - without entity having a primary column most of typeorm features won't work. Thats why it is required.

**Comment by ErikSchults** [comment]
Thank you for your fast response.

**Comment by ShreyasIrestoreapp** [comment]
Is there any alternative for not using primary column?  The thing is my entity is nested one! i dont want multiple IDs for my entity.

**Comment by doublejosh** [comment]
Certainly computed primary keys should be available to reference as primary key column.

Cross-linking...
https://github.com/typeorm/typeorm/issues/3704
https://github.com/typeorm/typeorm/issues/2629
https://github.com/typeorm/typeorm/issues/5317
