### ISSUE TITLE
QueryBuilder does not format query like: "ALIAS"."COLUMN" when use andWhere() function.

### ISSUE THREAD

**Issue by Junbong** [typeorm/typeorm#1193]
Hi. I'm trying to query with `SelectQueryBuilder` but the QueryBuilder does not make query like: `"ALIAS"."COLUMN"` when use `andWhere()` function.

For example:
```typescript
createConnection({
  type: "postgres",
  entities: [ __dirname + "/models/*.js" ],
  namingStrategy: new WiNamingStrategy(),
  ...
}).then(async connection => {
  const qp = connection
    .getRepository("shops")
    .createQueryBuilder("SHOP")
    .innerJoin("SHOP.taggings", "TAGGINGS")
    .where("SHOP.id > 1")
    .andWhere("SHOP.brand_id = 69")
    .andWhere("TAGGINGS.taggable_type = 'Shop'")
    .getQueryAndParameters();
  console.log(qp);
}).catch(error => console.log(error));
```

Result of `console.log(qp)` is:
```sql
SELECT "SHOP"."id" AS "SHOP_id",
       "SHOP"."name" AS "SHOP_name",
       "SHOP"."brand_id" AS "SHOP_brand_id",
       ...
FROM "shops" "SHOP"
INNER JOIN "taggings" "TAGGINGS" ON "TAGGINGS"."taggable_id"="SHOP"."id"
WHERE "SHOP"."id" > 1
  AND SHOP.brand_id = 69
  AND TAGGINGS.taggable_type = 'Shop'
```

* `WHERE` clause created from `.where("SHOP.id > 1")` is proper as `WHERE "SHOP"."id" > 1`.
* `WHERE-AND` clause after WHERE created from `.andWhere("SHOP.brand_id = 69")` causes **missing FROM-clause** error. The query should be `AND "SHOP"."brand_id" = 69`.
* `WHERE-AND` clause for inner join table after AND created from `.andWhere("TAGGINGS.taggable_type = 'Shop'")` causes **missing FROM-clause** error. The query also should be `AND "TAGGINGS"."taggable_type" = 'Shop'`.

This query causes error on PostgresQL shell. Error message is following:
```
ERROR:  missing FROM-clause entry for table "shop"
LINE 7:   AND SHOP.brand_id = 69
              ^
```

Is this really what you meant? or is this bug?

**Comment by Junbong** [comment]
FYI: I got same result from `QueryBuilder.getQuery()` function.

**Comment by pleerock** [comment]
can you please show me your entity?

**Comment by pleerock** [comment]
I guess you are using database column names in your query instead of entity column names. To make escaping to work you must use entity column names instead of database column names.

**Comment by Junbong** [comment]
Thanks @pleerock , It works!
