### ISSUE TITLE
Problem pagination with getRawMany() : either skip or offset don't work

### ISSUE THREAD

**Issue by CFA-Wisolv** [typeorm/typeorm#1195]
Hi.

I'm creating a query with QueryBuilder created from an entity repository.

`q = this.appsRepository.createQueryBuilder('apps');`

I'm adding multiple options depending on multiple conditions. One of those is to add a "from - to" pagination like :

`this.oResult.limit = {
    from: (limitFrom < 1) ? 1 : limitFrom,
    to: limitTo ? limitTo : ((limitFrom > 0) ? limitFrom - 1 : 0) + 100,
    previous_element: (limitFrom > 0) ? limitFrom - 1 : 0,
    returned_element: 0,
    remaining_element : 0,
    total_element: 0,
    next: '',
};

q.limit(this.oResult.limit.to - this.oResult.limit.previous_element)
  .offset(this.oResult.limit.previous_element);`

This work well while using .getMany() function but when I try with .getRawMany() only limit option works.
I also tried using skip & take, but none of those works on .getRawMany()

I didn't found many documentation on using getRawMany function, is there a way to make the offset (or skip, or any other working same way) to work on getRawMany ?

Thanks for your time and answer.

**Comment by pleerock** [comment]
with `getRawMany` both `offset` and `limit` must work. `skip` and `take` don't work for raw queries. Can you provide a minimal reproduction code of your issue and what SQL it generates for you? (you can enable query logging by setting `logging: true` in connection options)

**Comment by CFA-Wisolv** [comment]
Sorry, looks like the problem came from something different than I was thinking. Offset works great thanks.
