### ISSUE TITLE
CROSS Database query

### ISSUE THREAD

**Issue by EvilNOP** [typeorm/typeorm#1196]
Consider the following QueryBuilder:

```js
course_repo.createQueryBuilder('course')
  .select('course.name')
  .addSelect('student.name')
  .innerJoin(Student, 'student', 'student.id = course.student_id')
  .getRawMany()
```

It only works when table `Course` and table `Student` within the same database.
What if they are not ?
**So, is there any way to query cross database ?**

**Comment by pleerock** [comment]
Yes, its supported, you can find examples [here](https://github.com/typeorm/typeorm/blob/master/test/functional/multi-schema-and-database/multi-schema-and-database-basic-functionality/multi-schema-and-database-basic-functionality.ts).

You can define your database on a Student entity, or if you don't have an entity you can define it this way:

```ts
course_repo.createQueryBuilder('course')
  .select('course.name')
  .addSelect('student.name')
  .innerJoin("someDatabase.student", 'student', 'student.id = course.student_id')
  .getRawMany()
```

**Comment by EvilNOP** [comment]
> Define your database on a Student entity

What does it mean?

Let's I have a database name `students_db`, and the following entity:
```js
@Entity('tbl_students')
export class Student {
....
}
```

So, I can construct QueyBuilder like:
```js
course_repo.createQueryBuilder('course')
  .select('course.name')
  .addSelect('student.name')
  .innerJoin("students_db.Student", 'student', 'student.id = course.student_id')
  .getRawMany()
```

Is that correct ?

I've got an error Alias `studentsdb` was not found.

Assuming that table `tbl_students` is on database students_db, and table `tbl_ courses` is on database `courses_db`

**Comment by pleerock** [comment]
@EvilNOP did you check link Ive send to you? Also check entities this test uses.

**Comment by EvilNOP** [comment]
Sorry, I haven't yet. I'll read it in short.

**Comment by niveo** [comment]
```

@Entity('tbl_courses', { database: 'db_courses', schema: 'sch_courses' })
export class CoursesEntity {
    @PrimaryColumn({ name: 'ID' })
    id: number;
}
```

```
@Entity('tbl_students', { database: 'db_students', schema: 'sch_student' })
export class StudentsEntity {
     @PrimaryColumn({ name: 'ID' })
    id: number;

    @OneToOne(type => CoursesEntity, { eager: true, nullable: true })
    @JoinColumn({ name: 'ID' })
    coursesEntity: CoursesEntity;
}
```

and createQueryBuilder

**Comment by EvilNOP** [comment]
I've seen the code

```js
const queryRunner = connection.createQueryRunner();
const table = await queryRunner.getTable("guest.category");
await queryRunner.release();

const post = new Post();
post.name = "Post #1";
await connection.getRepository(Post).save(post);

const category = new Category();
category.name = "Category #1";
category.post = post;
await connection.getRepository(Category).save(category);

const loadedCategory = await connection.createQueryBuilder(Category, "category")
    .innerJoinAndSelect("category.post", "post")
    .where("category.id = :id", {id: 1})
    .getOne();
```

It is because the `connection.createQueryRunner()` such that it can perform cross-database query ?

I am using the TypeORM version **0.0.11** which don't have the API `createQueryBuilder`, so is there any chance to achieve cross-database query ?

**Comment by pleerock** [comment]
no, cross-database queries were implemented in 0.1.0. I strongly recommend you to update typeorm version since 0.0.11 is a very old version and lot of fixes were made since that.

**Comment by EvilNOP** [comment]
Fair enough.
So, the latest TypeORM verison is using MySQL engine or MySQL2？

**Comment by pleerock** [comment]
you can use any of them - just install whatever you want

**Comment by EvilNOP** [comment]
You mean TypeORM both mysql and mysql2 driver, I can install either of them as TypeORM's dependency ?

**Comment by pleerock** [comment]
yes
