### ISSUE TITLE
Entity.find with relations returns whole table and ignores conditions

### ISSUE THREAD

**Issue by arielweinberger** [typeorm/typeorm#1199]
In order to receive an entity with its relations (let's say, Photo and Author as in the example).
```
Author.find({ name: 'Author name', relations: ['photos']);
```

I would expect this to return only authors who's name is "Author name", and return them with the photos. Instead, this returns all authors. My way around this is to first get the author (without the `relations: ['photos']` part), and then use `Photo.find({ authorId: author.id })`.

Unless I'm missing something, as long as I add the relations part to the object, the "name" criteria is ignored?

Thanks

**Comment by pleerock** [comment]
`find` accepts either `FindOptions` either column names to search by. You need to change it this way:

```ts
Author.find({ where: { name: "Author name" }, relations: ['photos']);
```
