### ISSUE TITLE
How to use relation ids without joining relation?

### ISSUE THREAD

**Issue by YGolikov** [typeorm/typeorm#1203]
Is this possible to get eager/lazy array of relation ids?

**Comment by pleerock** [comment]
yes there is an experimental decorator called `@RelationId`. See examples [here](https://github.com/pleerock/typeorm/blob/77cc40bbe53d2c692a82938a5f969ecb492af1d7/test/functional/decorators/relation-id).

**Comment by YGolikov** [comment]
@pleerock Thank you very much! That's what I needed.
