### ISSUE TITLE
Retrieving result data from Stored Procedure (mysql) ?

### ISSUE THREAD

**Issue by arimus** [typeorm/typeorm#1207]
NOTE: I'm using 0.0.11 atm in this particular test, but I didn't see anything in the release notes about fixes related to this, so figure I should be fine on that count.

When using the query() method on the entity manager like so:

```
let results = await this.database.getConnection().entityManager.query('CALL MyFunction(?)', [5086]));

console.log(results);
```

This nets me the following result, but no actual row data:

```
[[],{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":34,"warningCount":0,"message":"","protocol41":true,"changedRows":0}]
```

I can create a raw MySQL connection and get the results, but was wondering if there's a way to do this within the context of Typeorm. Ideally, I'd like to be able to create an object which these results could be automatically map into as well, but I'd settle for not having to make a separate connection with the MySQL module. For example:

```
    var connection = mysql.createConnection({...<omitted>...});

    connection.connect();

    return new Promise<Shift[]>((resolve, reject) => {
      connection.query(`CALL MyFunction(5086);`,
        function (error, results, fields)
        {
          if (error) {
            throw reject(error);
          }
          console.log('result is: ', results);
          resolve(results);
        }
      );
    });
```

returns with something like:

```
[[{id: 1}, {id: 2}], {"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":34,"warningCount":0,"message":"","protocol41":true,"changedRows":0}]
```

Thanks in advance.

**Comment by pleerock** [comment]
> [[],{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":34,"warningCount":0,"message":"","protocol41":true,"changedRows":0}]

I have to stay that... it should not be possible. `query` method has been always returning results of the query without changing them. Here is source code:

```ts
query(query: string, parameters?: any[]): Promise<any> {
        if (this.isReleased)
            throw new QueryRunnerAlreadyReleasedError();

        return new Promise(async (ok, fail) => {
            try {
                const databaseConnection = await this.connect();
                this.driver.connection.logger.logQuery(query, parameters, this);
                const queryStartTime = +new Date();
                databaseConnection.query(query, parameters, (err: any, result: any) => {

                    // log slow queries if maxQueryExecution time is set
                    const maxQueryExecutionTime = this.driver.connection.options.maxQueryExecutionTime;
                    const queryEndTime = +new Date();
                    const queryExecutionTime = queryEndTime - queryStartTime;
                    if (maxQueryExecutionTime && queryExecutionTime > maxQueryExecutionTime)
                        this.driver.connection.logger.logQuerySlow(queryExecutionTime, query, parameters, this);

                    if (err) {
                        this.driver.connection.logger.logQueryError(err, query, parameters, this);
                        return fail(new QueryFailedError(query, parameters, err));
                    }

                    ok(result);
                });

            } catch (err) {
                fail(err);
            }
        });
    }
```

As you can see it does execute the query pretty much same was as you did, nothing more then that. I have to ask you to check everything once again, and if needed to check with latest version as well.

> Ideally, I'd like to be able to create an object which these results could be automatically map into as well

This will not be possible since your custom function can return you anything and orm cannot know what and how to map.

**Comment by asingh3886** [comment]
Hi, 
How can I call stored  Stored Procedures or Views from SQL

**Comment by pleerock** [comment]
@asingh3886 using `query` method, e.g.:

```ts
const result = await manager.query(`YOUR PROCEDURE CALL`);
```

**Comment by pleerock** [comment]
I'll close this issue since looks like there is no additional info from original poster.

**Comment by PawanKr2feb** [comment]
@arimus Could you please help me on this.
[https://github.com/typeorm/typeorm/issues/2161](Not able to Pass Parameter for Stored Procedure)
