### ISSUE TITLE
[queestion] Raw query

### ISSUE THREAD

**Issue by szkumorowski** [typeorm/typeorm#1209]
I went through documentation and issues. How to make raw query with parameters ?
driver: mysql

`this.repository.query(`SELECT * FROM table_name where ID = $1`, [1]);`
`this.repository.query(`SELECT * FROM table_name where ID = :1`, [1]);`
`this.repository.query(`SELECT * FROM table_name where ID = :id`, [{id: 1]);`

All cominations result in `Error: ER_BAD_FIELD_ERROR: Unknown column '$1' in 'where clause'` or query parsing

**Comment by pleerock** [comment]
See [mysql docs](https://github.com/mysqljs/mysql#performing-queries).

```ts
this.repository.query(`SELECT * FROM table_name where ID = ?, [1]`);
```
