### ISSUE TITLE
Electron platform support

### ISSUE THREAD

**Issue by morki** [typeorm/typeorm#121]
I can't use this awesome library in Electron application with Angular2 and SystemJS.
SystemJS and NodeJS has colliding require function, so I had to edit PlatformTools class like below.

**Application startup**

```
window.nodeRequire = require;
delete window.require;
delete window.exports;
delete window.module;

System.config({ /* conf */ })';
System.import('app');

```
**Usage later in application**

```
PlatformTools.require = nodeRequire;
let connection = await createConnection({  /* conf */ });

```
**TypeORM - PlatformTools.ts**

```
// no imports

export class PlatformTools {
    static type: "browser"|"node"|"electron" = "electron";
    static require: (name: string) => any;

    static load(name: string): any {
        return PlatformTools.require(name);
    }

    static pathNormilize(pathStr: string): string {
        return PlatformTools.load('path').normalize(pathStr);
    }

    static getEnvVariable(name: string): any {
        return PlatformTools.load('process')..env[name];
    }

   // etc...
}
```

Is it possible to have typeorm-electron package similar to typeorm-browser in NPM?
Or can it be merged to node PlatformTools.ts? I can do a PR if I'm not missing anything.

**Comment by pleerock** [comment]
so you want to use typeorm on the frontend of your electron app? If yes, then with which database you want to work there?

**Comment by morki** [comment]
Yes, with MySQL, but in my opinion it does not matter, because Electron expose NodeJS APIs to browser context and I can use any require functionality. I already use it with MySQL right now, but with changes that I described above. 

Two problems in existing PlatformTools are:
- imports of NodeJS modules (need to require() in Electron)
- hard coded require function (problem with SystemJS, need to pass custom)

**Comment by pleerock** [comment]
The problem is that I havent worked with electron. If you could make it working, can you stay with this your implementation for now? I need some time to play with electron to get know how things are working there. Also will be great if you can create a repo where you setup your project (minimal repduction) with electron and angular2, so I can see a problem you have

**Comment by nadavten** [comment]
any progress ?

**Comment by pleerock** [comment]
community contributions are welcomed :)

**Comment by morki** [comment]
I resolved it by using webpack and:

**Before application startup**
```
window.nodeRequire = require;
```

**Before creating connection**
```
import {PlatformTools} from "typeorm/platform/PlatformTools";

PlatformTools.load = function(name) { return nodeRequire(name); };
```

**Comment by nadavten** [comment]
@morki can u please provide source code ?

**Comment by morki** [comment]
The project si bundled by webpack with angular-cli (its angular project) and here are sample files:

**index.html**
```
<head>
    <script>window.nodeRequire = require;</script>
    <!-- here are placed webpack bundles -->
</head>
```

**database.ts**
```
import {createConnection} from "typeorm";
import {PlatformTools} from "typeorm/platform/PlatformTools";

declare var nodeRequire: any;
PlatformTools.load = function(name) { return nodeRequire(name); };

var connectionPromise = createConnection({
    entities: [ /* entities */ ],
    driver: { /* config */ }
});
```

**Comment by nadavten** [comment]
database.ts is on server side ?

**Comment by shilpi-verma-izap** [comment]
@morki how to change webpack for making it require("typeorm") working?

**Comment by JeongJun-Lee** [comment]
Is there any method to use typeorm in Angular Framework of the renderer process in Electron, not main process? Because the renderer process can understand Node'js APIs, I think it could be possible.
