### ISSUE TITLE
MongoDB: Only single entity created properly (others aren't)

### ISSUE THREAD

**Issue by VovanSuper** [typeorm/typeorm#1210]
Once (trying to ) creating (`insertOne` by one, `insertMany`, `save` ) several entities, only one persisted in db with all fields, as for others - only their `_id`s ase persisted, i.e (version: 0.1.4): 

https://gist.github.com/VovanSuper/e5de4941f7a6401c66ac0767b5fb93ac

In the mongolab objs are: 
Users:
```{
    "_id": {
        "$oid": "5a143c2d519f2a1ff4f6bc67"
    },
    "firstName": "Alex1",
    "lastName": "Coola1",
    "age": 71,
    "events": [
        {
            "_id": {
                "$oid": "5a143c2d519f2a1ff4f6bc64"
            }
        },
        {
            "_id": {
                "$oid": "5a143c2d519f2a1ff4f6bc65"
            }
        },
        {
            "_id": {
                "$oid": "5a143c2d519f2a1ff4f6bc66"
            }
        }
    ]
}
{
    "_id": {
        "$oid": "5a143c2d519f2a1ff4f6bc68"
    }
}

Events:

```
{
    "_id": {
        "$oid": "5a143c2d519f2a1ff4f6bc63"
    },
    "name": "Continue with the development of My Partners in Sports App",
    "at_date": {
        "$date": "2018-11-05T21:00:00.000Z"
    }
}
{
    "_id": {
        "$oid": "5a143c2d519f2a1ff4f6bc64"
    }
}
{
    "_id": {
        "$oid": "5a143c2d519f2a1ff4f6bc65"
    }
}
{
    "_id": {
        "$oid": "5a143c2d519f2a1ff4f6bc66"
    }
}

**Comment by pleerock** [comment]
You have a wrong code. You use `user1` where you need to use `user2`, you user `event1` everywhere, etc. Please be careful, I spend an hour trying to figure out this scary bug!
