### ISSUE TITLE
PrimaryGeneratedColumn not increment in postgres

### ISSUE THREAD

**Issue by andresdenis** [typeorm/typeorm#1217]
I attach screenshots for the entity, table and data. The data was saved with Id = 0.
 I use the typeorm 0.1.6.

<img width="1058" alt="primarygeneratedcolumn - entity" src="https://user-images.githubusercontent.com/20642435/33147963-b9b16ad2-cfa8-11e7-8d47-a7692764c329.png">

<img width="1337" alt="primarygeneratedcolumn - postgress db" src="https://user-images.githubusercontent.com/20642435/33147989-c3acf4c0-cfa8-11e7-996b-a37b977d2607.png">

<img width="1074" alt="primarygeneratedcolumn - data" src="https://user-images.githubusercontent.com/20642435/33147994-ca4148ea-cfa8-11e7-989d-4ad707f66e58.png">

**Comment by pleerock** [comment]
hm. There are hundred of tests which use primary generated column and there are no problems with them. 

Can you try to remove `{ type: 'integer' }` from decorator and try again?

**Comment by andresdenis** [comment]
I removed the decorator and continue saved id=0.
I attach my code and console logs.

<img width="737" alt="1217 code" src="https://user-images.githubusercontent.com/20642435/33168871-40714088-d021-11e7-96b0-6f67338835f5.png">

<img width="739" alt="1217 console" src="https://user-images.githubusercontent.com/20642435/33168875-454868f2-d021-11e7-9f09-601610935446.png">

**Comment by pleerock** [comment]
you need to create a **minimal** reproduction code example (which i can `git clone; npm i; npm start`) to reproduce this issue, because it looks too strange and simply cannot be possible because there are tests and users who use this and never complain.

**Comment by andresdenis** [comment]
ok, I will create the example.

**Comment by MaikelH** [comment]
> I see the problem, when the entity use PrimaryGeneratedColumn the save must omit the value of the corresponding field if zero (to Save).

0 is still a valid id as far as Typeorm and Postgres is concerned. If you want to auto generate a new ID for the entity, you should make sure the id value is undefined. This will make sure that the id column is not added to the `INSERT` query and a value for it will be auto-generated.

**Comment by andresdenis** [comment]
Yes, thank you very much for your explanation.

**Comment by pleerock** [comment]
@MaikelH thanks 💯
