### ISSUE TITLE
Patreon Link?

### ISSUE THREAD

**Issue by recurrence** [typeorm/typeorm#1220]
Hey guys,

This is a really awesome project, one that I think should be supported financially.  Is there a Patreon Link for the people working on this EG: @pleerock?

It's exceptional, I've worked with many ORMs and this one works so well with TypeScript I'm somewhat in awe :)

**Comment by pleerock** [comment]
thanks, you can donate on [open collective](https://opencollective.com/typeorm)

**Comment by recurrence** [comment]
Thanks!  Somehow it donated as an organization.  I asked them to fix that :)

Y'all should put that link in the Github README.

**Comment by pleerock** [comment]
Thank you!
