### ISSUE TITLE
Many-to-Many with custom fields

### ISSUE THREAD

**Issue by freis** [typeorm/typeorm#1224]
Hi guys I was wandering if its possible to have a many-to-many relationship where I can add some custom fields to the created table. I was looking at previous issues and someone told to create the other table and use one-to-many relationship. However I'm not understanding how I would acomplish that where then I would do something like: `const user = await this.userRepository.findOne(id)` and get the result as a many-to-many.

Something on this lines:
User: n------ n :Group

And get the output as:

`
{
    "id": 1,
    "firstName": "firstname",
    "lastName": "lastname",
    "groups": [
        {
            "id": 1,
            "name": "Group1"
        }
    ]
}
`
Behind this there is the table user_group that makes this connection between User and Groups and has for example a field called isDeleted that helps me to know is this was soft deleted and not show this entry.

Could you guys help me on the right path?

**Comment by pleerock** [comment]
any many-to-many relation with custom fields is just separate entity with proper relations set between A and B entities plus additional columns

**Comment by freis** [comment]
Yup I get that part, I do not get it on how to have an output like the generated output when using the default many-to-many. because by using it as one-to-many what I get is 
`[
        {
            "id": 1,
            "isActive": true
        }
    ]`

and not the full groups fields.

I know what it would look as an SQL query. Just thinking on how to accomplish this using typeorm.

**Comment by pleerock** [comment]
Something like this is to implement "additional columns in many-to-many table"

```ts
@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number;
    @Column()
    name: string;
    @OneToMany(type => UserGroup, userGroup => userGroup.user)
    userGroups: UserGroup[];
}
@Entity()
export class UserGroup {
    @Column()
    isActive: boolean;
    @ManyToOne(type => User, user => user.userGroups, { primary: true })
    user: User;
    @ManyToOne(type => Group, group => group.userGroups, { primary: true })
    group: Group;
}
@Entity()
export class Group {
    @PrimaryGeneratedColumn()
    id: number;
    @Column()
    name: string;
    @OneToMany(type => UserGroup, userGroup => userGroup.group)
    userGroups: UserGroup[];
}
```

Not sure if I understood your other requests

**Comment by freis** [comment]
Yeah that part I understood, not using the primary: true because I do a soft delete. that means I don't delete just put a flag, deleted: true.
My question is how to make such a query when using the userRepository show all the groups where that user is. When I used the relationships the output I got was all the objects from UserGroup and not Group.

**Comment by pleerock** [comment]
Depend on what you want to load, for example to load user with only specific group you use following code:

```ts
const users = createQueryBuilder("user")
     .innerJoin("user.userGroups", "userGroup")
     .innerJoin("userGroup.group", "group", "group.id = :groupId", { groupId })
     .getMany();
```

**Comment by pleerock** [comment]
Looks like the issue was resolved. Reopen if needed.

**Comment by johannchen** [comment]
Thanks for the implementation on the activerecord like has_many :through association. You may want to put it in the doc since it's a common use case.  How would you do with insert into the join table?

I tried
`getConnection().createQueryBuilder().relation(User, "userGoups").of(1).add({userId: 1, groupId: 2});`

which does not work.

**Comment by johannchen** [comment]
Nevermind, I figured out to use insert query directly to the join table.

**Comment by johannchen** [comment]
How would you load users with only specific group and display the additional column "isActive"?

**Comment by johannchen** [comment]
Is it possible to map "isActive" from UserGroup to User as User's attribute?

**Comment by Schavras** [comment]
> Nevermind, I figured out to use insert query directly to the join table.

Hello @johannchen , how do you insert the query directly into the join table? I tried both with save and raw query, but although the entry is created, i got undefinied on both foreign keys

**Comment by josephbuchma** [comment]
This also should work

```ts
import { JoinColumn } from 'typeorm';

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  name: string

  @OneToMany(type => UserGroup, userGroup => userGroup.user)
  userGroups: UserGroup[];

  @ManyToMany(type => Group, group => group.users)
  @JoinTable({
    name: 'user_groups',
    joinColumn: {
      name: 'user_id',
      referencedColumnName: 'id',
    },
    inverseJoinColumn: {
      name: 'group_id',
      referencedColumnName: 'id',
    },
  })
  groups: Group[]
}

@Entity('user_groups')
export class UserGroup {
  @Column()
  isActive: boolean

  @JoinColumn("user_id")
  @ManyToOne(type => User, user => user.userGroups, { primary: true })
  user: User

  @JoinColumn("group_id")
  @ManyToOne(type => Group, group => group.userGroups, { primary: true })
  group: Group
}

@Entity()
export class Group {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  name: string

  @ManyToMany(type => User, user => user.groups)
  users: UserGroup[]

  @OneToMany(type => UserGroup, userGroup => userGroup.group)
  userGroups: UserGroup[];
}

```

**Comment by Bnaya** [comment]
I'm trying to implement @josephbuchma solution,
But seems like it makes typeorm to get crazy.

give these entities
https://gist.github.com/Bnaya/b228369df108379b95be468a30548f6d#file-myentities-ts

I'm getting the additional fields being created and dropped and them again created in the initial typeorm sync, and on every sync, even without any change to the entities.

example of the SQL:
https://gist.github.com/Bnaya/b228369df108379b95be468a30548f6d#file-sync-sql

**Comment by barofi** [comment]
> Something like this is to implement "additional columns in many-to-many table"
> 
> ```ts
> @Entity()
> export class User {
>     @PrimaryGeneratedColumn()
>     id: number;
>     @Column()
>     name: string;
>     @OneToMany(type => UserGroup, userGroup => userGroup.user)
>     userGroups: UserGroup[];
> }
> @Entity()
> export class UserGroup {
>     @Column()
>     isActive: boolean;
>     @ManyToOne(type => User, user => user.userGroups, { primary: true })
>     user: User;
>     @ManyToOne(type => Group, group => group.userGroups, { primary: true })
>     group: Group;
> }
> @Entity()
> export class Group {
>     @PrimaryGeneratedColumn()
>     id: number;
>     @Column()
>     name: string;
>     @OneToMany(type => UserGroup, userGroup => userGroup.group)
>     userGroups: UserGroup[];
> }
> ```
> 
> Not sure if I understood your other requests

Hey, I've tried this example but it doesnt work well.
Only the last ManyToOne property column generated as FK (in this example only group_id)

![image](https://user-images.githubusercontent.com/18580735/61184821-9f379c00-a65a-11e9-8bd2-3af246cc6c02.png)

**Comment by scott-ho** [comment]
Hi @pleerock, I want to follow your solution. However, it's kind of blurry to map the indirect relationship using query builder.

```ts
@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number;
    @Column()
    name: string;
    @OneToMany(type => UserGroup, userGroup => userGroup.user)
    userGroups: UserGroup[];
	
	groups: Groups[]; // <==== here how can i map the data to here?
}

@Entity()
export class UserGroup {
    @Column()
    isActive: boolean;
    @ManyToOne(type => User, user => user.userGroups, { primary: true })
    user: User;
    @ManyToOne(type => Group, group => group.userGroups, { primary: true })
    group: Group;
}

@Entity()
export class Group {
    @PrimaryGeneratedColumn()
    id: number;
    @Column()
    name: string;
    @OneToMany(type => UserGroup, userGroup => userGroup.group)
    userGroups: UserGroup[];
}


// ...
const users = createQueryBuilder("user")
     .innerJoin("user.userGroups", "userGroup")
     .innerJoin("userGroup.group", "group", "group.id = :groupId", { groupId })
	 // **** what should i do here ****
     .getMany();
```

**Comment by scott-ho** [comment]
BTW, for @josephbuchma 's solution, indeed it will keep generating meaningless **foreign keys** and **extra column** update each I run `typeorm migration:generate`.

![image](https://user-images.githubusercontent.com/35443789/65222141-0ce7c480-daf1-11e9-9f33-dde6610bae2c.png)

Is there any way to prevent this kind of stupid change? Or some guidance to allow me make some PRs?

**Comment by ctilley83** [comment]
> Something like this is to implement "additional columns in many-to-many table"
> 
> ```ts
> @Entity()
> export class User {
>     @PrimaryGeneratedColumn()
>     id: number;
>     @Column()
>     name: string;
>     @OneToMany(type => UserGroup, userGroup => userGroup.user)
>     userGroups: UserGroup[];
> }
> @Entity()
> export class UserGroup {
>     @Column()
>     isActive: boolean;
>     @ManyToOne(type => User, user => user.userGroups, { primary: true })
>     user: User;
>     @ManyToOne(type => Group, group => group.userGroups, { primary: true })
>     group: Group;
> }
> @Entity()
> export class Group {
>     @PrimaryGeneratedColumn()
>     id: number;
>     @Column()
>     name: string;
>     @OneToMany(type => UserGroup, userGroup => userGroup.group)
>     userGroups: UserGroup[];
> }
> ```
> 
> Not sure if I understood your other requests

I implemented a relationship identical to this but can't save the data to the junction table. Can you give an example on accomplishing that. Here's a link that explains my issue. https://stackoverflow.com/questions/60978591/nestjs-typeorm-post-request-for-a-has-many-through-type-relationship

**Comment by awHamer** [comment]
> BTW, for @josephbuchma 's solution, indeed it will keep generating meaningless **foreign keys** and **extra column** update each I run `typeorm migration:generate`.
> 
> ![image](https://user-images.githubusercontent.com/35443789/65222141-0ce7c480-daf1-11e9-9f33-dde6610bae2c.png)
> 
> Is there any way to prevent this kind of stupid change? Or some guidance to allow me make some PRs?

@scott-ho  Hey! Did you figured out how to get rid of this?
 The only one possible **workaround** I found is to replace ManyToMany with ManyToOne to interim Entity...

**Comment by scott-ho** [comment]
@awHamer unfortunately, nope.

**Comment by LuisCarrilloR** [comment]
> Hi @pleerock, I want to follow your solution. However, it's kind of blurry to map the indirect relationship using query builder.
> 
> ```ts
> @Entity()
> export class User {
>     @PrimaryGeneratedColumn()
>     id: number;
>     @Column()
>     name: string;
>     @OneToMany(type => UserGroup, userGroup => userGroup.user)
>     userGroups: UserGroup[];
> 	
> 	groups: Groups[]; // <==== here how can i map the data to here?
> }
> 
> @Entity()
> export class UserGroup {
>     @Column()
>     isActive: boolean;
>     @ManyToOne(type => User, user => user.userGroups, { primary: true })
>     user: User;
>     @ManyToOne(type => Group, group => group.userGroups, { primary: true })
>     group: Group;
> }
> 
> @Entity()
> export class Group {
>     @PrimaryGeneratedColumn()
>     id: number;
>     @Column()
>     name: string;
>     @OneToMany(type => UserGroup, userGroup => userGroup.group)
>     userGroups: UserGroup[];
> }
> 
> 
> // ...
> const users = createQueryBuilder("user")
>      .innerJoin("user.userGroups", "userGroup")
>      .innerJoin("userGroup.group", "group", "group.id = :groupId", { groupId })
> 	 // **** what should i do here ****
>      .getMany();
> ```

Hello @scott-ho! Did you find something on how to solve this?

**Comment by carlocorradini** [comment]
> > Hi @pleerock, I want to follow your solution. However, it's kind of blurry to map the indirect relationship using query builder.
> > ```ts
> > @Entity()
> > export class User {
> >     @PrimaryGeneratedColumn()
> >     id: number;
> >     @Column()
> >     name: string;
> >     @OneToMany(type => UserGroup, userGroup => userGroup.user)
> >     userGroups: UserGroup[];
> > 	
> > 	groups: Groups[]; // <==== here how can i map the data to here?
> > }
> > 
> > @Entity()
> > export class UserGroup {
> >     @Column()
> >     isActive: boolean;
> >     @ManyToOne(type => User, user => user.userGroups, { primary: true })
> >     user: User;
> >     @ManyToOne(type => Group, group => group.userGroups, { primary: true })
> >     group: Group;
> > }
> > 
> > @Entity()
> > export class Group {
> >     @PrimaryGeneratedColumn()
> >     id: number;
> >     @Column()
> >     name: string;
> >     @OneToMany(type => UserGroup, userGroup => userGroup.group)
> >     userGroups: UserGroup[];
> > }
> > 
> > 
> > // ...
> > const users = createQueryBuilder("user")
> >      .innerJoin("user.userGroups", "userGroup")
> >      .innerJoin("userGroup.group", "group", "group.id = :groupId", { groupId })
> > 	 // **** what should i do here ****
> >      .getMany();
> > ```
> 
> Hello @scott-ho and @pleerock! Did you find something on how to solve this?.
> I am stuck on the exact same situation :(

Same, any solution?

**Comment by AlashaHonore** [comment]
> Hi @pleerock, I want to follow your solution. However, it's kind of blurry to map the indirect relationship using query builder.
> 
> ```ts
> @Entity()
> export class User {
>     @PrimaryGeneratedColumn()
>     id: number;
>     @Column()
>     name: string;
>     @OneToMany(type => UserGroup, userGroup => userGroup.user)
>     userGroups: UserGroup[];
> 	
> 	groups: Groups[]; // <==== here how can i map the data to here?
> }
> 
> @Entity()
> export class UserGroup {
>     @Column()
>     isActive: boolean;
>     @ManyToOne(type => User, user => user.userGroups, { primary: true })
>     user: User;
>     @ManyToOne(type => Group, group => group.userGroups, { primary: true })
>     group: Group;
> }
> 
> @Entity()
> export class Group {
>     @PrimaryGeneratedColumn()
>     id: number;
>     @Column()
>     name: string;
>     @OneToMany(type => UserGroup, userGroup => userGroup.group)
>     userGroups: UserGroup[];
> }
> 
> 
> // ...
> const users = createQueryBuilder("user")
>      .innerJoin("user.userGroups", "userGroup")
>      .innerJoin("userGroup.group", "group", "group.id = :groupId", { groupId })
> 	 // **** what should i do here ****
>      .getMany();
> ```

Need this too !

**Comment by martinsantibanez** [comment]
Hello! here's my workaround:
```typescript
export class User {
  //...
  @OneToMany(type => UserGroup, userGroup => userGroup.user)
  userGroups: UserGroup[];

  get groups(): Group[] {
    return this.userGroups?.map(userGroup => userGroup.group)
  }
```
It works only for reading. I had another idea that may work for reading and saving, but I'm not sure if it's a good thing to do and it's not necessary for my use case:
```typescript
export class User {
  //...
  @OneToMany(type => UserGroup, userGroup => userGroup.user)
  userGroups: UserGroup[];

  groups?: Group[]

  @AfterLoad()
  @AfterInsert()
  @AfterUpdate()
  setGroups() {
    this.groups = this.userGroups?.map(userGroup => userGroup.passenger)
  }

  @BeforeInsert()
  @BeforeUpdate()
  setUserGroups() {
    if (this.groups) {
      this.userGroups = this.groups.map(group => ({
        user: this,
        group
      }))
    }
  }
```

Then when finding you need to make sure to include `userGroups` and `userGroups.group` in the `relations` array.

Feedback appreciated! hope it helps

**Comment by tomasreimers** [comment]
Writing in case this is helpful to others. When I originally took the approach of using a composite key, I was seeing some errors on update. 

Specifically, I had a table "membership" with foreign keys to "user" and "group" tables (and the composite key of the two was the primary key). The problem was when I ran findOne against membership, it wouldn't load user and group, and so updates would become inserts (b/c there was no primary key). 

My solution was to add a auto-generated ID and just make the composite key a unique index instead.

**Comment by errol59** [comment]
Any updates on this issue? It is pretty ridiculous that adding extra columns to a junction table while retaining the simple functions of manipulating the relationships between objects can't be easily done in an ORM. Why even use Typeorm in the first place then?

**Comment by nebkat** [comment]
@errol59 comments like these are just counter productive. The feature is not missing because it lacked your complaints - it is one of many things that require work and aren't the easiest to implement. You are welcome to submit a pull request or donate to the project. Reducing the entire ORM to the lack of one feature is rather ignorant...

**Comment by doruxan** [comment]
> Hello! here's my workaround:
> 
> ```ts
> export class User {
>   //...
>   @OneToMany(type => UserGroup, userGroup => userGroup.user)
>   userGroups: UserGroup[];
> 
>   get groups(): Group[] {
>     return this.userGroups?.map(userGroup => userGroup.group)
>   }
> ```
> 
> It works only for reading. When finding you need to make sure to include userGroups and userGroups.group in the relations array.
> I had another idea that may work for reading and saving, but I'm not sure if it's a good thing to do and it's not necessary for my use case. Here it is in case it helps someone:
> 
> ```ts
> export class User {
>   //...
>   @OneToMany(type => UserGroup, userGroup => userGroup.user)
>   userGroups: UserGroup[];
> 
>   groups?: Group[]
> 
>   @AfterLoad()
>   @AfterInsert()
>   @AfterUpdate()
>   setGroups() {
>     this.groups = this.userGroups?.map(userGroup => userGroup.group)
>   }
> 
>   @BeforeInsert()
>   @BeforeUpdate()
>   setUserGroups() {
>     if (this.groups) {
>       this.userGroups = this.groups.map(group => ({
>         user: this,
>         group
>       }))
>     }
>   }
> ```
> 
> Feedback appreciated! hope it helps

Thanks for this. 

But it causes circular dependency for me.  Below is the result;

`err.message Converting circular structure to JSON
[0]     --> starting at object with constructor 'GkClient'
[0]     |     property 'userClients' -> object with constructor 'Array'
[0]     |     index 0 -> object with constructor 'Object'
[0]     --- property 'client' closes the circle
[0] POST /client/create-client 500 335.315 ms - 1254
[0] RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
[0]     at ServerResponse.writeHead (_http_server.js:255:11)
[0]     at ServerResponse.writeHead (C:\Users\doruk.san\Desktop\gkCredit\nodebank\backend\node_modules\on-headers\index.js:44:26)
[0]     at ServerResponse._implicitHeader (_http_server.js:246:8)
[0]     at write_ (_http_outgoing.js:685:9)
[0]     at ServerResponse.end (_http_outgoing.js:799:5)
[0]     at ServerResponse.send (C:\Users\doruk.san\Desktop\gkCredit\nodebank\backend\node_modules\express\lib\response.js:221:10)
[0]     at ServerResponse.json (C:\Users\doruk.san\Desktop\gkCredit\nodebank\backend\node_modules\express\lib\response.js:267:15)
[0]     at C:\Users\doruk.san\Desktop\gkCredit\nodebank\backend\src\routes\index.ts:20:26
[0]     at Layer.handle_error (C:\Users\doruk.san\Desktop\gkCredit\nodebank\backend\node_modules\express\lib\router\layer.js:71:5)
[0]     at trim_prefix (C:\Users\doruk.san\Desktop\gkCredit\nodebank\backend\node_modules\express\lib\router\index.js:315:13)`

**Comment by mohsinamjad** [comment]
Can anyone help me on this. I've used sequelize for a long time and now I'm exploring typeorm.
I've created three tables with custom field in custom jointable just like @josephbuchma explained.

now I want to create entry in all of these table in one single save call, is it doable ? 
there are very basic examples in docs, it should address the more advance concepts.

here is an example of sequelize
```
await User.create({
  username: 'p4dm3',
  points: 1000,
  profiles: [{
    name: 'Queen',
    User_Profile: {
      selfGranted: true
    }
  }]
}, {
  include: Profile
});
```

**Comment by smacker** [comment]
> osephbuchma

> BTW, for @josephbuchma 's solution, indeed it will keep generating meaningless **foreign keys** and **extra column** update each I run `typeorm migration:generate`.
> 
> ![image](https://user-images.githubusercontent.com/35443789/65222141-0ce7c480-daf1-11e9-9f33-dde6610bae2c.png)
> 
> Is there any way to prevent this kind of stupid change? Or some guidance to allow me make some PRs?

I debugged it a little and here is the necessary change that prevents incorrect migration: https://github.com/smacker/typeorm/commit/7fcc82c0ce8f0ebd5f33d86c8f1474b33d624e3d

Though I'm not sure if it should be part of typeorm.

If we allow entities to access each other directly while the relation contains custom fields, we essentially break the existing API.
Consider the following example:
```
@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  name: string

  @ManyToMany(type => Group, group => group.users)
  @JoinTable({
    name: 'user_groups',
    joinColumn: {
      name: 'user_id',
      referencedColumnName: 'id',
    },
    inverseJoinColumn: {
      name: 'group_id',
      referencedColumnName: 'id',
    },
  })
  groups: Group[]
}

@Entity('user_groups')
export class UserGroup {
  @Column({ null: false })
  order: number

  @JoinColumn("user_id")
  @ManyToOne(type => User, user => user.userGroups, { primary: true })
  user: User

  @JoinColumn("group_id")
  @ManyToOne(type => Group, group => group.userGroups, { primary: true })
  group: Group
}

@Entity()
export class Group {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  name: string

  @ManyToMany(type => User, user => user.groups)
  users: UserGroup[]
}

// this doesn't work because we need to pass `order` value which we can not with such API
connection.getRepository(User).findOne(id).groups.add(group);
```

**Comment by StetHD** [comment]
> Depend on what you want to load, for example to load user with only specific group you use following code:
> 
> ```ts
> const users = createQueryBuilder("user")
>      .innerJoin("user.userGroups", "userGroup")
>      .innerJoin("userGroup.group", "group", "group.id = :groupId", { groupId })
>      .getMany();
> ```

@pleerock How about using custom entity with ```@JoinTable({synchronize: false})``` no need to write queries by myself, is it fine?

**Comment by punit1108** [comment]
> hi. I've been here since 2023. has anyone solved this problem?


Does this solve your problem?
https://typeorm.io/many-to-many-relations#many-to-many-relations-with-custom-properties

**Comment by Tokiham** [comment]
> > Hi @pleerock, I want to follow your solution. However, it's kind of blurry to map the indirect relationship using query builder.
> > ```ts
> > @Entity()
> > export class User {
> >     @PrimaryGeneratedColumn()
> >     id: number;
> >     @Column()
> >     name: string;
> >     @OneToMany(type => UserGroup, userGroup => userGroup.user)
> >     userGroups: UserGroup[];
> > 	
> > 	groups: Groups[]; // <==== here how can i map the data to here?
> > }
> > 
> > @Entity()
> > export class UserGroup {
> >     @Column()
> >     isActive: boolean;
> >     @ManyToOne(type => User, user => user.userGroups, { primary: true })
> >     user: User;
> >     @ManyToOne(type => Group, group => group.userGroups, { primary: true })
> >     group: Group;
> > }
> > 
> > @Entity()
> > export class Group {
> >     @PrimaryGeneratedColumn()
> >     id: number;
> >     @Column()
> >     name: string;
> >     @OneToMany(type => UserGroup, userGroup => userGroup.group)
> >     userGroups: UserGroup[];
> > }
> > 
> > 
> > // ...
> > const users = createQueryBuilder("user")
> >      .innerJoin("user.userGroups", "userGroup")
> >      .innerJoin("userGroup.group", "group", "group.id = :groupId", { groupId })
> > 	 // **** what should i do here ****
> >      .getMany();
> > ```
> 
> Hello @scott-ho and @pleerock! Did you find something on how to solve this?. I am stuck on the exact same situation :(
it works to me
```typescript
import {
    Entity,
    Column,
    PrimaryGeneratedColumn,
    OneToMany,
  } from 'typeorm';
  import { DeviceAdmin } from './deviceAdmin.entity';
  @Entity()
  export class Device {

    @PrimaryGeneratedColumn()
    device_id: number;

    @Column()
    device_name:string;
  
    // many-to-many custom fields
    @OneToMany(() => DeviceAdmin, deviceAdmin => deviceAdmin.device)
    public deviceAdmin: DeviceAdmin[];
  }
```

```typescript
import {
    Entity,
    Column,
    PrimaryGeneratedColumn,
    OneToMany,
  } from 'typeorm';
  import { DeviceAdmin } from './deviceAdmin.entity';
  @Entity()
  export class People {
    
    @PrimaryGeneratedColumn()
    people_id: number;

    @Column()
    people_name:string;
  
    // many-to-many custom fields
    @OneToMany(() => DeviceAdmin, deviceAdmin => deviceAdmin.people)
    public deviceAdmin: DeviceAdmin[];
  }
  
```

```typescript
import {
    Entity,
    Column,
    PrimaryGeneratedColumn,
    ManyToOne,
    JoinColumn,
  } from 'typeorm';
  import { Device } from './device.entity';
  import { People } from './people.entity';
  
  @Entity()
  export class DeviceAdmin {

    @PrimaryGeneratedColumn()
    device_admin_id: number;
  
    @Column()
    device_id: number;
  
    @Column()
    people_id: number;
  
    // many-to-many custom fields
    @ManyToOne(() => Device, device => device.device_id, {
      createForeignKeyConstraints: false,
      cascade: true,
      nullable: false,
    })
    @JoinColumn({
      name: 'device_id',
      referencedColumnName: 'device_id',
    })
    public device: Device;
  
    // many-to-many custom fields
    @ManyToOne(() => People, people => people.people_id, {
      createForeignKeyConstraints: false,
      cascade: true,
      nullable: false,
    })
    @JoinColumn({
      name: 'people_id',
      referencedColumnName: 'people_id',
    })
    public people: People;
  }
  
```


```typescript
  async getPage() {
    const builder = this.deviceEntity
      .createQueryBuilder('d_')
      .leftJoin('d_.deviceAdmin', 'deA')
      .leftJoinAndMapMany(
        'd_.admins',//==>Replace with any porperty you want
        People,
        'p_',
        'deA.people_id = p_.people_id'
      )
      .where('1=1')
      .skip(
        0
      )
      .take(10);
    const rows = await builder.getMany();
    const total = await builder.getCount();
    return {
      rows,
      total,
    };
  }
```
the result:
```json
{
    "rows": [
        {
            "device_id": 1,
            "device_name": "Freeze dryer",
            "admins": [
                {
                    "people_id": 1,
                    "people_name": "Mike"
                },
                {
                    "people_id": 2,
                    "people_name": "Marry"
                }
            ]
        }
    ],
    "total": 1
}
```

**Comment by Tokiham** [comment]
> > > osephbuchma
> > 
> > 
> > > BTW, for @josephbuchma 's solution, indeed it will keep generating meaningless **foreign keys** and **extra column** update each I run `typeorm migration:generate`.
> > > ![image](https://user-images.githubusercontent.com/35443789/65222141-0ce7c480-daf1-11e9-9f33-dde6610bae2c.png)
> > > Is there any way to prevent this kind of stupid change? Or some guidance to allow me make some PRs?
> > 
> > 
> > I debugged it a little and here is the necessary change that prevents incorrect migration: [smacker@7fcc82c](https://github.com/smacker/typeorm/commit/7fcc82c0ce8f0ebd5f33d86c8f1474b33d624e3d)
> > Though I'm not sure if it should be part of typeorm.
> > If we allow entities to access each other directly while the relation contains custom fields, we essentially break the existing API. Consider the following example:
> > ```
> > @Entity()
> > export class User {
> >   @PrimaryGeneratedColumn()
> >   id: number
> > 
> >   @Column()
> >   name: string
> > 
> >   @ManyToMany(type => Group, group => group.users)
> >   @JoinTable({
> >     name: 'user_groups',
> >     joinColumn: {
> >       name: 'user_id',
> >       referencedColumnName: 'id',
> >     },
> >     inverseJoinColumn: {
> >       name: 'group_id',
> >       referencedColumnName: 'id',
> >     },
> >   })
> >   groups: Group[]
> > }
> > 
> > @Entity('user_groups')
> > export class UserGroup {
> >   @Column({ null: false })
> >   order: number
> > 
> >   @JoinColumn("user_id")
> >   @ManyToOne(type => User, user => user.userGroups, { primary: true })
> >   user: User
> > 
> >   @JoinColumn("group_id")
> >   @ManyToOne(type => Group, group => group.userGroups, { primary: true })
> >   group: Group
> > }
> > 
> > @Entity()
> > export class Group {
> >   @PrimaryGeneratedColumn()
> >   id: number
> > 
> >   @Column()
> >   name: string
> > 
> >   @ManyToMany(type => User, user => user.groups)
> >   users: UserGroup[]
> > }
> > 
> > // this doesn't work because we need to pass `order` value which we can not with such API
> > connection.getRepository(User).findOne(id).groups.add(group);
> > ```
> 
> hi. I've been here since 2023. has anyone solved this problem?

try this:https://github.com/typeorm/typeorm/issues/1224#issuecomment-1914574449
