### ISSUE TITLE
Exception for empty array is required

### ISSUE THREAD

**Issue by icepeng** [typeorm/typeorm#1226]
related to #1118 

`entityManager.remove([])`
This code is not expected to delete anything, but actually deletes all entities.
In previous issues, it was reported that an empty array did not create a `WHERE` clause.
Should not empty arrays in `QueryBuilder.createWhereIdsExpression` throw exceptions?

**Comment by pleerock** [comment]
It should just ignore it. Ive fixed it, will be released in `0.1.7` next week.

**Comment by icepeng** [comment]
Great.

**Comment by masonsha** [comment]
just encountered. thanks @pleerock for fixing this.
