### ISSUE TITLE
feature: config table default charset

### ISSUE THREAD

**Issue by youwi** [typeorm/typeorm#1227]
typeorm gen create scripts like this
default --->
```
CREATE TABLE `swagger_cache` (
  `id` varchar(255) NOT NULL,
  `projectId` varchar(255) NOT NULL,
  `key` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```
i want this --->
```
CREATE TABLE `swagger_cache` (
  `id` varchar(255) NOT NULL,
  `projectId` varchar(255) NOT NULL,
  `key` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

# table charset utf8

**Comment by breath103** [comment]
any update on this?

**Comment by pleerock** [comment]
No, the issue is closed. @youwi why did you closed this issue?

**Comment by breath103** [comment]
well just to let you guys know, i think this would save a lot of time. you can just Database charset setting, but this would be much more flexible in any given case

**Comment by youwi** [comment]
example code 🔢 
 createConnection({ 
       host:   Setting.instance.db.host,
        port: Setting.instance.db.port,
        username:   Setting.instance.db.username,
        database:   Setting.instance.db.database,
        password:   Setting.instance.db.password,
        type: 'mysql',
        charset:"utf8mb4",  🔢 
        autoSchemaSync: true,
    })
i forget that how to fix it....

**Comment by TakanashiOuken** [comment]
Does `charset:"utf8mb4",` really works?
I still get latin1

**Comment by youwi** [comment]
@TakanashiOuken  on first connect, it works.  (before table created).

**Comment by TakanashiOuken** [comment]
Seems like it didn’t specify utf8 when db creation so it keeps on using latin1
How do I create DB with typeorm

**Comment by youwi** [comment]
sorry,i forgot that... too long .that...

**Comment by TakanashiOuken** [comment]
No problem
I will just create DB by query

**Comment by Zach-Ma** [comment]
If all answer above doesn't help you, you can change the database manually by doing:

`ALTER DATABASE dbname CHARACTER SET utf8 COLLATE utf8_general_ci;`

`ALTER TABLE tbl_name CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

link:
[How to convert an entire MySQL database characterset and collation to UTF-8?
](https://stackoverflow.com/questions/6115612/how-to-convert-an-entire-mysql-database-characterset-and-collation-to-utf-8)

**Comment by lukaszniemkiewicz** [comment]
For me charset option didin't work - If you dockerize your app here is  My solution:

 change default Mysql encoding on docker-compose.yaml
`version: "2"
services:
  app:
    container_name: express-server
    restart: always
    build: .
    networks:
      - internal
      - external

    ports:
      - "3000:3000"
    links:
      - mysql
    volumes:
    - ./:/usr/src/app
    command: nest start --watch
  mysql:
    networks:
      - internal
    image: "mysql:5.7.24"
    container_name: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "xxx"
      MYSQL_USER: "xxx"
      MYSQL_PASSWORD: "xxx"
      MYSQL_DATABASE: "xxx"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']   #<---- this line 
networks:
  internal:
    internal: true
  external:
    external: true
`
