### ISSUE TITLE
Could getConnection return Promise as well?

### ISSUE THREAD

**Issue by risa** [typeorm/typeorm#1228]
May be I am missing something but it would be helpful if getConnection() could be async/return Promise too. 

I was trying to implement lazy connection initialisation. My code:
```typescript
export async function orm(): Promise<Connection> {
  try {
    let connection = getConnection('default')
    if (connection.isConnected == false) {
      await connection.connect();
    }
    return connection
  } catch (ex) {
    
    let connection = await createConnection({
      name: 'default',
      type: 'mysql',
      host: 'db',
      port: 3306,
      username: 'db_user',
      password: 'db_password',
      database: 'db',
      entities: [ClientApplicationModel, UserModel],
    })
    return connection
  }
}
```

This code worked fine until I deployed tests in mocha which obviously uses concurrency heavily. The problem was that the first orm() function was called, getConnection() raised exception and ran createConnection in the catch block.  Before it finished a second call to orm() came which also raised exception, but the second call to createConnection failed with the error: _'Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.'_

The error was really difficult to find, because it happened only under certain circumstances (in docker container with slower connection to database) and it took me quite some time to figure out what was happening.  

It would make things easier if *getConnection* could be async and return Promise in case the createConnection was in progress. Does it make sense? I could try to make a change but I am not sure if I am not missing something here. Thanks.

**Comment by pleerock** [comment]
no, it will not be a promise, it will become much harder to work with connection if we make it to return a promise. Since creating connection is a single-time process established in your application startup you'll never need a connection in promise anywhere in your app, so its really pointless

**Comment by risa** [comment]
OK
