### ISSUE TITLE
Decorators for JavaScript too

### ISSUE THREAD

**Issue by guzgarcia** [typeorm/typeorm#123]
I think is fairly better use decorators than inline code for models. You can add [JavaScript decorators](https://github.com/tc39/proposal-decorators) support too, so, there will be no major differences between modeling with JavaScript and Typescript. As JavaScript decorators is a proposal for now (stage 2), once it reaches stage 3 or 4 (high chances to be part of the standard) you can add it as default feature.

**Comment by pleerock** [comment]
If current typescript's decorators implementation differs from what this proposal is suggesting then it will be implemented by typescript in a near future. Maybe this is what their [roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap) says by "Implement new ES Decorator proposal". Once it will be implemented there should not be difference on how to use decorators in TypeScript or JavaScript.

**Comment by guzgarcia** [comment]
Great, I didn't seen the roadmap until now.
