### ISSUE TITLE
Wrong query parameter for relations

### ISSUE THREAD

**Issue by angexis** [typeorm/typeorm#1232]
When running a query such as
```
const org: Organisation = ...
const found = await connection.manager.findOne(User, { organisation: org });
```
`found` is always `undefined` because the WHERE clause in the run query is:
```
WHERE "User"."organisationId"=$1 -- PARAMETERS: [{"name":"The Fancy Team","id":2}]
```
when it should be:
```
WHERE "User"."organisationId"=$1 -- PARAMETERS: [2]
```
See test case here:  https://gist.github.com/angexis/ec9014a9d7a45ebb14dc5e3feea9e118

**Comment by angexis** [comment]
I have a fix for this... but reading the contributions guidelines and given that I don't have Oracle...
Let me know if you want a PR or if this simple code suffices:

In `src/metadata/EntityMetadataUtils.ts` change the `createPropertyPath` function to:
```ts
   /**
    * Creates a property paths for a given entity.
    */
    static createPropertyPath(metadata: EntityMetadata, entity: ObjectLiteral, prefix: string = "") {
        const paths: string[] = [];
        Object.keys(entity).forEach(key => {
 
            const columnMetaData = metadata.findColumnWithPropertyName(key);
            // check for function is needed in the cases when createPropertyPath used on values containg a function as a value
            // example: .update().set({ name: () => `SUBSTR('', 1, 2)` })
            const parentPath = prefix ? prefix + "." + key : key;
            if (metadata.hasEmbeddedWithPropertyPath(parentPath)) {
                const subPaths = this.createPropertyPath(metadata, entity[key], key);
                paths.push(...subPaths);
            }
            else if (columnMetaData) {
                paths.push(columnMetaData.propertyPath);
            }
            else {
                const path = prefix ? prefix + "." + key : key;
                paths.push(path);
            }
        });
        return paths;
    }
```

**Comment by pleerock** [comment]
Can you please check if this bug exist in `next` version of typeorm? Because this part was significantly changed in there

**Comment by pleerock** [comment]
And btw don't worry to contribute, you don't need to have oracle, if you able to run test for at least one driver its okay for you already (you can disable any drivers in ormconfig), tests for other drivers CI will run for you once you push and create a PR

**Comment by angexis** [comment]
Hello @pleerock 

Indeed, this is working in the `next` branch (hadn't noticed that branch until you mentioned) and using typeorm@next (0.2.0-alpha.10).

So I guess I can close this bug now. Thanks!

**Comment by angexis** [comment]
(and OK, I will do a PR if I find another fix)
