### ISSUE TITLE
Primary keys on relations do not allow for read-modify-write cycles

### ISSUE THREAD

**Issue by angexis** [typeorm/typeorm#1235]
I have a model where the primary key is a composite key on two fields: a simple int and a foreign key on another table:
```ts
@Entity()
@Index("pk_team_member", ["bibSubnum", "team"], { unique: true })
export class TeamMember {
    @ManyToOne(type => Team, team => team.teamMembers, {
        primary: true,
        nullable: false
    })
    team: Team;

    @Column("int", {
        nullable: false, primary: true
    })
    bibSubnum: number;
```

The problem is that by doing that, a find-modify-save cycle on `TeamMember` does not work because the `find` does not fetch the team and the subsequent `save` will therefore insert a new `TeamMember` line in the table (with team_id being NULL - although I specified nullable: false BTW)

The workaround I have is to declare all primary-relations as eager but this is error prone
```ts
    @ManyToOne(type => Team, team => team.teamMembers, {
        primary: true,
        eager: true /* eager because primary */,
        nullable: false
    })
    team: Team;
```

IMHO it should be automatic (typeorm should decide to use eager fetching when the relation is primary) or better, some kind of a private property should keep the team ID (which is available without any performance penalty).

**Comment by pleerock** [comment]
> some kind of a private property should keep the team ID

there is no "private property" thing in javascript, property will be public anyway which may be unexpected to have a property in the model which is not present in the model.

You should be able to do following:

```ts
export class TeamMember {
     
    @Column()
     teamId: number;

    @ManyToOne(type => Team, team => team.teamMembers, {
        primary: true,
        nullable: false
    })
    team: Team;

    @Column("int", {
        nullable: false, primary: true
    })
    bibSubnum: number;
```

and you'll have teamId automatically set. Not sure, maybe you'll need to set a primary column to it

```ts
    @PrimaryColumn()
     teamId: number;
```

and remove primary identifier from the relation.

Regarding to automatically load primary relations, Im not sure if its correct design since it will produce extra query which may be unexpected, joins always may bring expected results because of how rdbms database return results (in rows, duplication).

Having to set `eager: true` looks a good solution, why is it not working for you?

**Comment by angexis** [comment]
Thanks for your answers (and BTW kudos for this lib!)

The `eager: true` actually works pretty well. It certainly involves a performance penalty as you stated above as there is a need for an additional request or at least a join.

Your workaround seems a much better idea. I will give it a try and let you know.

However, from a usage perspective, this seems odd that a feature (setting `primary: true` in a relation) would actually not work out of the box. So IMHO, either it should *just work* or you should consider removing it before it bites other users as it bit me. It is BTW much easier to add it later if you find a perfect solution than to live with it or break the API if you eventually decide to drop it.

Finally, regarding my previous suggestion, the wording  _private_ was not to be taken literally... I did not think much about it, and I was thinking about some meta-data fields piggy-backed onto each entity, but you are right, it can be odd to have such fields especially if the entity is serialized to JSON.

**Comment by angexis** [comment]
@pleerock your solution of double-binding of the relation (once with the ID and once with the actual type) works. However, looking at the outcome I feel uncomfortable to have the same information twice.

Therefore, my decision will be to keep the eager flag as I had it working yesterday. It's obviously your decision what you do with typeorm but my take on this is that following options are the best:

1. find a way to piggyback the ID in some kind of hidden structure w/o causing issues - I really don't know how to do this but it would be the dream solution

2. automatically turn on the `eager` flag when the `primary` is set in the relation. This has a performance penalty of course but remember the 80/20 rule... and it potentially prevents bugs and headaches. In the 20% case (where performance proves to be more important than readability/maintainability), users can always revert to your solution with the double-binding... and so removing the `primary` flag would remove the `eager` one as well.

What is your thought?

**Comment by angexis** [comment]
FWIW, I added the modified code with your suggestion:
```ts
@Entity()
@Index("pk_team_member", ["bibSubnum", "teamId"], { unique: true })
export class TeamMember {
    @ManyToOne(type => Team, team => team.teamMembers)
    team: Team;

    @PrimaryColumn({type: 'int'})
    teamId: number;

    @PrimaryColumn({type: 'int'})
    bibSubnum: number;
```

and elsewhere

```ts
    let tm = this.em.create(TeamMember, {
        teamId: team.id,
        bibSubnum: i + 1
    });
    tm = await this.em.findOne(TeamMember, tm) || tm;
....
// hack with tm
....
    await this.em.save(tm);
```
Here, if I inadvertently put `team` rather than `team.id` the code fails! :( Hence my preference !

**Comment by pleerock** [comment]
> What is your thought?

first isn't an option. Second is option, but Im not yet sure if we really need to automatically mark then as eager when users can do it on their own and decide which is better for them. But I completely got your point, and its valuable for me. But I'll wait and see if other users will have same issues and maybe implement what you told later.

> Here, if I inadvertently put team rather than team.id the code fails! :( Hence my preference !

put where? Do you mean `teamId: team` ?

**Comment by angexis** [comment]
>> it would be the dream solution

> first isn't an option

Are you not a dreamer? :))

> put where? Do you mean teamId: team ?

No. With the proposal you made above to double-bind the foreign key column both as a relation and as a number, this works:
```ts
    let tm = this.em.create(TeamMember, {
        teamId: team.id,
        bibSubnum: i + 1
    });
    tm = await this.em.findOne(TeamMember, tm) || tm;
....
// hack with tm
....
    await this.em.save(tm);
```
while this doesn't:
```ts
    let tm = this.em.create(TeamMember, {
        team: team,
        bibSubnum: i + 1
    });
    tm = await this.em.findOne(TeamMember, tm) || tm;
....
// hack with tm
....
    await this.em.save(tm);
```
Both compile happily but one does not work, which violates the _principle of least astonishment_. Hence my choice to force `eager=true`.

I may well be one of the first to use foreign keys this way... see my other issue #1232 which tends to demonstrate it.

**Comment by pleerock** [comment]
I'll left current behaviour as it is for now. Lets see if other people will face same issue and we continue discussion after that.
