### ISSUE TITLE
Create nested object from plain JS object

### ISSUE THREAD

**Issue by mindjuice** [typeorm/typeorm#1238]
What is the recommended way to take a nested plain JS object and convert it into the corresponding entities and save it?  For example, I have `User` and `Address` entities, and then receive a plain JS user object like:

```
{ "first": "Nigel", "last": "Oglethorpe", "email": "nigel@oglethorpe.com", "addresses":[
	{
		"street1": "777 Main Street",
		"city": "Las Vegas",
		"stateProv": "Nevada",
		"country": "United States",
		"zipPostal": "12345"
	}]
}
```

I've written code to create a new `User` and iterate the `addresses` array and create corresponding `Address` entities, and that works, but doing this manually doesn't seem right when we have the schema available.  I have a dozen more entities to create and would rather not write this type of boilerplate code.

The `User` entity starts like this:

```
@Entity()
export class User {
  constructor(other?: User) {
    if (other) {
      this.first = other.first
      this.last = other.last
      this.email = other.email
      this.backupEmail = other.backupEmail
      this.phone = other.phone
      this.addresses = []
      if (other.addresses) {
        for (const address of other.addresses) {
          this.addresses.push(new Address(address))
        }
      }
    }
  // ...
}
```

The `createUser()` function looks like this:

```
async createUser(plainUser: User): Promise<number | undefined> {
    const user: User = new User(plainUser)

    const { manager } = this.connection
    // If I don't add the code below, the addresses don't get created.
    if (user.addresses) {
      for (const address of user.addresses) {
        await manager.save(address)
      }
    }

    await manager.save(user)
    return user.userId
  }
```

I found `preload()` in the code, but that just crashed for some non-obvious reason.

How do you normally handle this situation?

Thanks!

**Comment by pleerock** [comment]
`create` and `preload` are what is used in those scenarios. 

`create` just creates entity from the given plain javascript object while `preload` also loads all missing properties from the database

**Comment by mindjuice** [comment]
Thanks.  Finally got back around to this.

The `create()` seems to work when I give it a plain JS object with a nested address relation, but when I call `manager.save()` I get the error: `"SQLITE_CONSTRAINT: NOT NULL constraint failed: address_users_user.addressAddressId`, because both the user and the address are new and need to be added to the database.

This is how I'm creating and saving the user:

```
  async createUser(rawUser: User): Promise<number | undefined> {
    const { manager } = this.connection

    const user: User = manager.create(User, rawUser)
    await user.validate()

    await manager.save(user)
    this.log.info('Saved a new user with id=' + user.userId)
    return user.userId
  }
```
These are my Entity definitions (truncated):

```
@Entity()
export class User {
  @PrimaryGeneratedColumn() userId?: number
  @Column() first: string
  @Column() last: string
  @ManyToMany(type => Address, address => address.users)
  addresses?: Address[]
}

@Entity()
export class Address {
  @PrimaryGeneratedColumn() addressId?: number
  @Column() street1: string
  @Column({ nullable: true })
  street2: string
  @Column() city: string
  @Column() stateProv: string
  @Column() country: string
  @Column() zipPostal: string
  @ManyToMany(type => User, user => user.addresses)
  @JoinTable()
  users: User[]
}
```

Do you see something I'm doing wrong?

Thanks.

**Comment by mindjuice** [comment]
So it seems that my use case of recursively creating any missing objects on save isn't directly supported.  Is it something that's you think could be added or do you consider it out of scope? @pleerock

For now, I'm just writing the code to do the creation myself for each type, which is rather tedious, but it works.

Thanks!

**Comment by pleerock** [comment]
its supported if you use cascade options in the relations

**Comment by mindjuice** [comment]
Oh man...I missed that completely.  Trying that tonight.  Thanks!

**Comment by mindjuice** [comment]
Both `preload()` and `create()` are working great now that I'm using cascade!

Thanks!

**Comment by dinana** [comment]
Would like to add to this issue that if the nested object is not an instance of Object (instanceof Object === false) it won't be created. For example this happens when the input is coming from GraphQL in Nest.js.
