### ISSUE TITLE
[Question] How to query IN Array with Typeorm's repository API?

### ISSUE THREAD

**Issue by thohoh** [typeorm/typeorm#1239]
Here's my case:

I got an array of author IDs, for example :  [3, 7, 9]

I want to get all posts where **authorId** field is one of the guys in the array. And they should be ordered by **createDate**.

How do you do this with Typeorm's repository API? What method is more appropriate for this task?

**Comment by pleerock** [comment]
```ts
const posts = await manager.createQueryBuilder(Post, "post")
    .where("post.authorId IN (:authors)", { authors: [3, 7, 9] })
    .orderBy("post.createDate")
    .getMany();
```

**Comment by pleerock** [comment]
since `0.2.0-alpha.19` the new way is:


```ts
const posts = await manager.createQueryBuilder(Post, "post")
    .where("post.authorId IN (:...authors)", { authors: [3, 7, 9] })
    .orderBy("post.createDate")
    .getMany();
```

**Comment by mscharley** [comment]
@pleerock is there any way to possibly support something like `repo.find({ where: { authorId: [3, 7, 9] } })`?

**Comment by pleerock** [comment]
there is a separate issue for this feature request already exist. It will be implemented in future versions.

**Comment by eladmoshe** [comment]
@pleerock will this be a breaking change?

**Comment by pleerock** [comment]
@eladmoshe for what? for new feature or thing I added in `0.2.0-alpha.19` ?

**Comment by eladmoshe** [comment]
I meant to ask if the [current query syntax](https://github.com/typeorm/typeorm/issues/1239#issuecomment-347074706) will break when upgrading to 0.2.x.

**Comment by pleerock** [comment]
@eladmoshe correct. You'll need to apply "..." to all your parameters used in `IN`- like expressions.

**Comment by BehindTheMath** [comment]
>there is a separate issue for this feature request already exist. It will be implemented in future versions.

@pleerock Which issue is tracking that feature request?

**Comment by daggett206** [comment]
how to properly use WHERE IN syntax using getConnection().query('... where in ($1)', [ how to pass parameter here? ])?

**Comment by vlapo** [comment]
Hey @daggett206. `query()` method will call native query method of driver specific client. So for example for `postgres` you can find example with `IN` (or better `ANY`) [here](https://github.com/brianc/node-postgres/wiki/FAQ#11-how-do-i-build-a-where-foo-in--query-to-find-rows-matching-an-array-of-values).

```typescript
getConnection().query('... WHERE id = ANY($1)', [ 1, 2, 3 ]);
```

**Comment by richban** [comment]
My query looks like this:

sellers is ```number[]```

  ``` .andWhere('sc.seller_id IN :sellers_id', { sellers_id: sellers })```

with params:
``` -- PARAMETERS: [1,[["4","54"]]]```
the query works.

But if I pass a list of one element:

```"parameters":[1,["4"]]}```

it always fails. Is this a bug? I don't understand why the list got wrapped into one more list if the size is more than 1.

**Comment by iamlothian** [comment]
As a note for mongodb users, I had trouble with: 
```
return taskRepository.find({ where:
    { langCode: In(langCodes) }
});
```
but found that the following works:
```
return taskRepository.find({ where:
    { langCode: { $in: langCodes } }
});
```

**Comment by nitin1259** [comment]
> sellers

how did you fixed this ?

**Comment by dennbagas** [comment]
> ```ts
> const posts = await manager.getRepository(Post)
>     .find({
>         where: { authorId: In([3, 7, 9]) },
>         order: { createDate: "ASC" },
>     });
> ```

I use this and receive an error like this:
```
name: 'error',
length: 145,
severity: 'ERROR',
code: '22P02',
detail: 'Array value must start with "{" or dimension information.',
```
I use postgresql, and this is my entity:
```
@Column({ type: 'text', array: true, nullable: true })
recipient: number[];
```

I can save the data, but in postgres it is saved like this : `{1,2,3}`
How i fix this?

**Comment by JohnnyB9991** [comment]
Has there been any progress on this? Is there any way to use a NotIn([]) function?

**Comment by nouman-mpayg** [comment]
Hey,
What if you want to query for multiple columns for the same table. How can we achieve this with In?

I have a table where i stored `user_id` and `role_id`, now what I want is to query all the data that exists.
For a single record the query would be something like this: `userRoleEntity,find({ where: { user_id: 1, role_id: 2 });`
But to do this with array of userRoles (`[{user_id: 1, role_id: 2}, {user_id:1, role_id:4}`) what should be the best approch.

I know we can use forEach or map to make it work, but what I am looking is for a simple, one query solution.

**Comment by diegoonia** [comment]
I'm having the same trouble as nouman-mpayg, I have a product with multiple photos, and with queryBuilder I'm getting [{product_id: 1, photo_id: 1}. {product_id: 1, photo_id: 2}]. Is there any solution to make it simpler? I couldn't find anything.

**Comment by hvqzao** [comment]
When trying:
```
.find({ where: { id: In([1, 2]) }})
```
I was getting similar error message (Postgres backend):
```
UnhandledPromiseRejectionWarning: QueryFailedError: invalid input syntax for integer: "{"_type":"in","_value":[1,2],"_useParameter":true,"_multipleParameters":true}"
```
To stay with single query and not to switch to queryBuilder I solved it using OR syntax:
```
.find({ where: [{ id: 1 }, { id: 2 }] })
```
Its not perfect but does its job.

**Comment by hamzamumtaz007** [comment]
Is there something like NOT IN? I want to exclude the values for given id's in array. 
Can someone help me with that?

**Comment by molaeiali** [comment]
> Is there something like NOT IN? I want to exclude the values for given id's in array.
> Can someone help me with that?

@hamzamumtaz007 I think `Not(In([]))` will work

**Comment by ahmedsmae** [comment]
> @pleerock is there any way to possibly support something like `repo.find({ where: { authorId: [3, 7, 9] } })`?

{ where: { authorId: In([3, 7, 9]) } }

**Comment by 201RichK** [comment]
you can have this error also in case you register the services in the import statment
like this 
```
imports: [
    TypeOrmModule.forFeature([
      LevelService
    ])
  ],
```

this will throw the same error
