### ISSUE TITLE
Maybe project can be merged with https://github.com/sweetiq/schemats

### ISSUE THREAD

**Issue by born2net** [typeorm/typeorm#124]
Maybe project can be merged with https://github.com/sweetiq/schemats
combined efforts,

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by pleerock** [comment]
Hi, yeah Ive seen this project, and it looks cool, however what this project does is a bit different. Maybe as an idea it maybe possible to create classes and decorate them with decorators, but this maybe a complete different implementation.  Maybe if you are interested you can create an issue there and write them what they think about it ? Thanks

**Comment by born2net** [comment]
yep did that :)
regards

**Comment by pleerock** [comment]
thank you
