### ISSUE TITLE
Tests Failing on Node 4 - Problem with `cli-highlight`

### ISSUE THREAD

**Issue by mrkmg** [typeorm/typeorm#1242]
It appears that `cli-highlight` is causing the builds for `next` to fail.

The problem is `cli-highlight` is targeting es6, so it had the following in the outputted code:

```
function colorizeNode(node, theme = {}) {
```
Node 4 does not support default option params.

I am going to create a PR which pin's `cli-highlight` to version 1.1.4. Maybe we can ask `cli-highlight` to change the "target" to es5, to support node 4.

**Comment by mrkmg** [comment]
Updated PR to reflect cli-highlights fix

**Comment by pleerock** [comment]
Thanks for the fix
