### ISSUE TITLE
MySQL datatypes are missing in CREATE TABLE query

### ISSUE THREAD

**Issue by T-Specht** [typeorm/typeorm#1244]
When creating an entity as described in the step-by-step guide in the README, the generated query misses datatypes and therefore raises an error.

Given this model...

```typescript
@Entity()
export class Photo {
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column({
        length: 100
    })
    name: string;

    @Column()
    description: string;

    @Column()
    filename: string;

    @Column("double")
    views: number;

    @Column()
    isPublished: boolean;

    @OneToOne(type => PhotoMetadata, photoMetadata => photoMetadata.photo)
    metadata: PhotoMetadata;
}
```

...the following query is generated and raising a `QueryFailedError` error: 

```sql
CREATE TABLE `photo` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` (100) NOT NULL, `description`  NOT NULL, `filename`  NOT NULL, `views` double NOT NULL, `isPublished`  NOT NULL) ENGINE=InnoDB
```

Please notice that almost all of the datatypes are missing. This error could be easily fixed by just specifying datatypes in the `@Column()` decorator, e.g. `@Column("text")` for `description` or `filename`. 

Is this behaviour expected and is the explicit declaration of the datatypes mandatory? If that is the case, a hint in the documentation and step-by-step guide should be included.

If this, however, is a bug I would really appreciate some help troubleshooting this issue.

**Comment by pleerock** [comment]
You must setup reflect-metadata and enable tsconfig options as specified in documentation. You must import reflect-metadata before everything else in your app, before any entity imported.

**Comment by T-Specht** [comment]
Thank you, that solved the issue!
