### ISSUE TITLE
Retry connection after disconnect/error - is there event to catch?

### ISSUE THREAD

**Issue by snirs90** [typeorm/typeorm#1247]
Hi,

Is there an event emitter when MySQL disconnect/error?
Like in the library: https://github.com/mysqljs/mysql#error-handling

Thanks!

**Comment by pleerock** [comment]
This was already implemented in `@next`.

**Comment by llwt** [comment]
@pleerock Is this documented anywhere or could you point me to where I should look? I can't seem to find an event emitter I can subscribe to or a callback I can define.

**Comment by pleerock** [comment]
we use it internally to prevent orm fail when connection fail. TypeORM gives you direct access to underlying driver, so you can do anything with it, including subscription to events it sends

**Comment by llwt** [comment]
ahh gotcha. Thanks, I misread that as Typeorm exposes the functionally.
