### ISSUE TITLE
Select of Person with wrong index-name

### ISSUE THREAD

**Issue by Joniras** [typeorm/typeorm#1253]
When i try to Select a Person with .find() it does a select as it should. But the Select has several fields in it i did not declare like like this. Example:
Field: 
```typescript
...
@Index("mail_blog_yn",["mail_blog_yn",])
...
export class person {
...
    @ManyToOne(type=>lov_jn_kz, mail_blog_yn=>mail_blog_yn.persons4)
    @JoinColumn()
    mail_blog_yn:lov_jn_kz;
...
}
```
Info: The Entity was generated with [TypeOrm-Model-Generator ](https://github.com/Kononnable/typeorm-model-generator)

The Select looks like this in the log: 
```sql
...
`person`.`mailBlogYnKeyTypKz` AS `person_mailBlogYnKeyTypKz`
...
```

Here the code and the Connection setup:

```typescript
typeorm.createConnection({
  type: "mysql",
  host: "localhost",
  port: 3306,
  username: Configuration.Database.user,
  password: Configuration.Database.password,
  database: Configuration.Database.database,
  entities: [
   ...
    person,
   ....
  ],
  synchronize: false,
  logging: true
}).then(connection => {
  const modelRepository: typeorm.Repository<person> = connection.getRepository(person);
  modelRepository.find({
    "username" : 'x'
  }).then(( persons: person[]) => {
    console.log(JSON.stringify(persons));


  });
}).catch(error => console.log(error));

```

Here the Person.ts and the complete sql statement and some data about my table persons.
[Select-Problem.zip](https://github.com/typeorm/typeorm/files/1510672/Select-Problem.zip)

**Comment by pleerock** [comment]
Its not really pleasure to figure out things when you have `mail_blog_yn` namings. Please create a minimal reproduction **git repo** with clean models without any generator applied and make a concrete indication of the problem you have.

**Comment by Joniras** [comment]
But i have to use the generator, if i would not use the generator in my project, i would have to create over 30 Models by Hand. Thats not very convenient for me.

But I have a **Workaround** for now:

Using the [QueryBuilder][1] allows me to only select the values i really need and prevents the orm from selecting all values. 

*Still waiting for a real solution approach*


  [1]: http://typeorm.io/#/select-query-builder

**Comment by pleerock** [comment]
Its still not clear for me what issue you have.

**Comment by Joniras** [comment]
I assume the issue is that the select is wrong done.
As seen here: 
``` sql
...
`person`.`mailBlogYnKeyTypKz` AS `person_mailBlogYnKeyTypKz`
...
```
The attribute name is different here:
``` typescript
    @ManyToOne(type=>lov_jn_kz, mail_blog_yn=>mail_blog_yn.persons4)
    @JoinColumn()
    mail_blog_yn:lov_jn_kz;
```

Dosnt make sense for me at all.
Where does this name: `person`.`mailBlogYnKeyTypKz` come from and why is it generated like this ?

**Comment by pleerock** [comment]
okay, lets me ask you one thing, how your column is called in the database? If its called `mail_blog_yn` then you need to provide a custom column name inside `@JoinColumn` this way:

```ts
    @ManyToOne(type=>lov_jn_kz, mail_blog_yn=>mail_blog_yn.persons4)
    @JoinColumn({ name: "mail_blog_yn" })
    mail_blog_yn:lov_jn_kz;
```

And if that solves your issue then report issue in generator, because its generator issue.

**Comment by Joniras** [comment]
Yes, appearently its a issue of the generator. 

**Thanks for the help**, i will create an issue there.
