### ISSUE TITLE
Constructor dependency injection

### ISSUE THREAD

**Issue by ToonvanStrijp** [typeorm/typeorm#1257]
When I'm using typedi, the constructor dependency injection doesn't work, don't know if applying this correctly but here is my sample project with minimal setup (configuration set to mongodb):
[typedi-constructor-bug.zip](https://github.com/typeorm/typeorm/files/1512942/typedi-constructor-bug.zip)

I can do a work around by using this:
`Container.get(SchoolRepository);`

**Comment by pleerock** [comment]
why you guys don't use `git`, we are on github!

**Comment by ToonvanStrijp** [comment]
I can put it on git if you want? :) @pleerock

**Comment by ToonvanStrijp** [comment]
Fixed it, the error occurs cause I'm using the routing-controllers and typeorm together but I only defined the useContainer the typeorm and not for routing-controllers so if you do, use this:

```
import {Connection, createConnection, useContainer as typeormUseContainer} from 'typeorm';
import {useExpressServer, useContainer as routingUseContainer} from 'routing-controllers';
typeormUseContainer(Container);
routingUseContainer(Container);
```

**Comment by pleerock** [comment]
Good :)
