### ISSUE TITLE
run migrations:generate several times before run migrations:run will throw error!

### ISSUE THREAD

**Issue by GuoYingxu** [typeorm/typeorm#1265]
I have an entity User.ts like that:

        ` @Entity()
           export class User {
             @PrimaryGeneratedColumn()
             id: number;

            @Column()
            firstName: string;

            @Column()
            userName: string;

            @Column()
            age: number;
        }`

first , removed property firstname, then run command:   typeorm migrations:generate -n UserRemoveFirstName . This will  create a migration file like this: 

    `import {MigrationInterface, QueryRunner} from "typeorm";
     export class User1511963547242 implements MigrationInterface {
        public async up(queryRunner: QueryRunner): Promise<any> {
            await queryRunner.query("ALTER TABLE `guoyingxu`.`user` DROP `firstName`");  
        } 
        public async down(queryRunner: QueryRunner): Promise<any> { 
            await queryRunner.query("ALTER TABLE `guoyingxu`.`user` ADD `firstName` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL");
        }
    }`
then, add a property email, then run generate, makes file like this:

       ` public async up(queryRunner: QueryRunner): Promise<any> {
            await queryRunner.query("ALTER TABLE `guoyingxu`.`user` DROP `firstName`"); 
            await queryRunner.query("ALTER TABLE `guoyingxu`.`user` ADD `email` varchar(255) NOT NULL");
         }
        public async down(queryRunner: QueryRunner): Promise<any> {
             await queryRunner.query("ALTER TABLE `guoyingxu`.`user` DROP `email`"); 
            await queryRunner.query("ALTER TABLE `guoyingxu`.`user` ADD `firstName` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL");
       }`

Note that I generate this two files  use different options  -n {filename},  this time I run typeorm migrations:run ,it will throw error like:
`Error during migration run:
      { QueryFailedError: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'firstName'; check that 
    column/key exists
        at new QueryFailedError 
    (/Users/atail/nodespace/Guoyingxu/com_guoyingxu/src/error/QueryFailedError.ts:7:9)
        at Query._callback (/Users/atail/nodespace/Guoyingxu/com_guoyingxu/src/driver/mysql/MysqlQueryRunner.ts:202:37)
       at Query.Sequence.end ( 
/Users/atail/nodespace/Guoyingxu/com_guoyingxu/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
       at Query.ErrorPacket (/Users/atail/nodespace/Guoyingxu/com_guoyingxu/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
       at Protocol._parsePacket (/Users/atail/nodespace/Guoyingxu/com_guoyingxu/node_modules/mysql/lib/protocol/Protocol.js:279:23)
       at Parser.write (/Users/atail/nodespace/Guoyingxu/com_guoyingxu/node_modules/mysql/lib/protocol/Parser.js:76:12)
       at Protocol.write (/Users/atail/nodespace/Guoyingxu/com_guoyingxu/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/Users/atail/nodespace/Guoyingxu/com_guoyingxu/node_modules/mysql/lib/Connection.js:103:28)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:191:7)
    code: 'ER_CANT_DROP_FIELD_OR_KEY',
    errno: 1091,
    sqlMessage: 'Can\'t DROP \'firstName\'; check that column/key exists',
    sqlState: '42000',
    index: 0,
    sql: 'ALTER TABLE `guoyingxu`.`user` DROP `firstName`',
    name: 'QueryFailedError',
    query: 'ALTER TABLE `guoyingxu`.`user` DROP `firstName`',
    parameters: [] }`

I guess that means I have to  use migrations:run after each migrations:generate  command.
Is that true?

I used Ruby On Rails for a long time. In Rails, the migration files only concerned changes rather than sql.
Can typeorm do this just like rails in the future?

**Comment by pleerock** [comment]
> I guess that means I have to use migrations:run after each migrations:generate command.
Is that true?

yes, its true. 

> In Rails, the migration files only concerned changes rather than sql.

Im not familiar with ror, can you please provide more details?

**Comment by GuoYingxu** [comment]
@pleerock 
In rails ，
usually run command  

`$rails g migration change_products_price`

to create a file like named "{timestamp}-change-products-price",you can edit  it as 
`class ChangeProductsPrice < ActiveRecord::Migration[5.0]
  def change
    reversible do |dir|
      change_table :products do |t|
        dir.up   { t.change :price, :string }
        dir.down { t.change :price, :integer }
      end
    end
  end
end`

or 

`class ChangeProductsPrice < ActiveRecord::Migration[5.0]
  def up
    change_table :products do |t|
      t.change :price, :string
    end
  end
  def down
    change_table :products do |t|
      t.change :price, :integer
    end
  end
end`

more features see : 
[http://guides.rubyonrails.org/active_record_migrations.html](http://guides.rubyonrails.org/active_record_migrations.html)

Rails will create a table named 'schema_migrations' in database. It records migrations which have been excuted .And when you run command `rails db:migrate` (same as `typeorm migrations:run` in typeorm) , Rails will find new migrate file which have not been  excuted.

And ,Rails will excute migrations by created times.  so, when deploy a rails project. Just run `rails db:migrate` will be ok. It change the database on production ENV automatically.

**Comment by pleerock** [comment]
> Rails will create a table named 'schema_migrations' in database. It records migrations which have been excuted .And when you run command rails db:migrate (same as typeorm migrations:run in typeorm) , Rails will find new migrate file which have not been excuted.

but typeorm workflow is the same, right? If no, they what is different in typeorm?

The only difference I see is that it generates you code with api instead of sql, right? Is migration you showed automatically generated by ror?

**Comment by GuoYingxu** [comment]
Ror can not genearte migration files by change model's properties. That the typeorm do better than ror. 
What I want to say is  ror's migration did not conflict between different migrations.

Ror kowns every changes in the history. So it is easy to deploy form develop EVN to production's.

 Typeorm is very great  !
Rails is also very populer , maybe there is something we can learn from it.

**Comment by pleerock** [comment]
> Ror kowns every changes in the history.

what do you call history? Are you talking about "table named 'schema_migrations' in database" ? Because typeorm also has a "migrations" table in the database where it stores all run migrations and does not run them next time
