### ISSUE TITLE
SQLite: INSERT with columns that have default values

### ISSUE THREAD

**Issue by daniel-lang** [typeorm/typeorm#1268]
When `repository.insert()` is used on an entity that includes columns with default values, the insert will fail.

**Example code**
Entity
```typescript
@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column({default: true})
    isAdmin: boolean;
}
```
Insert
```typescript
const repository = connection.getRepository(User);

let user1 = new User();
user1.name = "Daniel Lang";

let user2 = new User();
 user2.name = "Daniel Kurz";
user2.isAdmin = false;

let user3 = new User();
user3.name = "Daniel Lang3";
user3.isAdmin = true;

await repository.insert([user1, user2, user3]);
```

This will generate the following statement
```sql
INSERT INTO "user"("name", "isAdmin") VALUES ($1,NULL), ($2,$3), ($4,$5)
-- PARAMETERS: ["Daniel Lang","Daniel Kurz",0,"Daniel Lang3",1]
-- SQLITE_CONSTRAINT: NOT NULL constraint failed: user.isAdmin
```

When using `.save()` each entity is saved seperately and there the default column is left with default is left out:
```sql
INSERT INTO "user"("name") VALUES ($1) -- PARAMETERS: ["Daniel Lang"]
INSERT INTO "user"("name", "isAdmin") VALUES ($1,$2) -- PARAMETERS: ["Daniel Kurz",0]
INSERT INTO "user"("name", "isAdmin") VALUES ($1,$2) -- PARAMETERS: ["Daniel Lang3",1]
```
Fixing this won't be easy because entities have to be seperated into those that have the default value set and those that don't.

**Comment by daniel-lang** [comment]
One possibility would be to insert them individually in a transaction. This should  be nearly identical when it comes to speed.

**Comment by pleerock** [comment]
> This should be nearly identical when it comes to speed.

no, its not, especially when you have ten thousands entities. 

What exact version are you checking? I thought I fixed this issue in `next`, can you try latest `next`?

**Comment by daniel-lang** [comment]
I tested this in typeorm@0.1.6
I will have a look at next

**Comment by daniel-lang** [comment]
You are right, it works in `next`. Do you want me to add my testcase to `next` branch or do you already have a test for that?

**Comment by pleerock** [comment]
I remember if we have test case for this purpose... If you want, you can add :)
