### ISSUE TITLE
[Question] Is it possible to include Nth-level relationship data using find options?

### ISSUE THREAD

**Issue by kenpederson** [typeorm/typeorm#1270]
If I have a Person entity with a one-to-many relationship with a Home entity, and then the Home entity has a many-to-one relationship with a HomeType entity, is there a way to get the Home entities to include their HomeType data when selecting Person's and including their Home relations?

`let personsWithHomes = await Person.find({ where: { id: id }, relations: ["homes"] })`

This would return my Person records with their associated Home records, but the Home records do not include their associated HomeType. I tried adding the type as an eager loaded relationship, but it still does not get included.

Is there a way to specify the sub relations to include?

`let personsWithHomes = await Person.find({ where: { id: id }, relations: ["homes", "homes.homeType"] })`

**Comment by daniel-lang** [comment]
You can create your query by using the query builder

```typescript
let personsWithHomesAndTypes = await repository.createQueryBuilder("person")
   .innerJoinAndSelect("person.homes", "home")
   .innerJoinAndSelect("homes.homeType", "homeType")
   .getMany()
```

**Comment by kenpederson** [comment]
Since you are suggesting using a different method, is it safe to assume that the answer to my question is "no", that I cannot accomplish what I am trying to do using the find options?

**Comment by kenpederson** [comment]
@daniel-lang  your comment combine with a more thorough reading of the doc has provided me with the answer to my question. It is in fact possible using the find options, I just needed to use the "join" option instead of the relations.

```
let personsWithHomes = await Person.find({
    where: {
        id: id
    },
    join: {
        alias: "person",
        leftJoinAndSelect: {
            "homes": "person.homes",
            "homeType": "homes.homeType"
        }
    }
});
```

Thank you for the assistance.

**Comment by daniel-lang** [comment]
You are right, sorry, I missed that

**Comment by pleerock** [comment]
I added more advanced support to `relations` of the find options, e.g.

```ts
const posts = await connection.getRepository(Post).find({ relations: ["photos", "user", "photos.user", "counters.author"] });
```

It was a hard feature to implement, because sub-relations can be joined via embeds, but I did it ;)
This feature will be available in `0.1.7`. Contributions to docs are welcomed.

**Comment by recurrence** [comment]
OH WOW, excellent work @pleerock .  Great to see that added!

**Comment by theigor** [comment]
@pleerock, just to confirm, when using find options, is it limited to 2 levels? I don't see any examples anywhere of using more than 2 levels of relations and I am getting errors locally using `0.1.12` like
```json
{
    "message": "Relation \"level1.level2.level3\" was not found, please check if it is correct and really exist in your entity."
}
```
even though I can get to level 3 if I start at level 2 so I know the relationships are configured correctly.

Thanks!

**Comment by theigor** [comment]
And nevermind - I just came across https://github.com/typeorm/typeorm/issues/1504 and updated to `0.1.14` and everything works. Great job!

**Comment by jboothe** [comment]
@pleerock Just started using typeorm with graphql in this weekend. Amazing library and Super Kudos 🚀  👍 🎉 on the nested `relations` feature! It's a must have with graphql. 

If `Medium-like-clapping` was available here, you'd get several hundred claps 👏 from yours truly. Nice job.

**Comment by pleerock** [comment]
@jboothe thanks. If you want to use typeorm with graphql [there is a framework](https://github.com/graphframework/graphstack) Im currently working on - you can try it.

**Comment by jboothe** [comment]
Good to know. I'll check it out.

**Comment by biels** [comment]
This feature is super nice, but I can't find it in the documentation. Are the docs updated? Or am I missing something?

**Comment by pleerock** [comment]
@biels what docs are you talking about? I provided an example code above.

**Comment by biels** [comment]
Yes, thank you for that. But I shouldn't have to come to a github issue to learn about a feature, right?

**Comment by pleerock** [comment]
No, if you read all [parts of the documentation](http://typeorm.io/#/find-options/basic-options).

**Comment by svegalopez** [comment]
@pleerock Thanks for creating this library! We are starting to use it in a production environment. 
Regarding this issue, thanks for implementign this:

`const posts = await connection.getRepository(Post).find({ relations: ["photos", "user", "photos.user", "counters.author"] });`

It is very helpful to be able to fetch nth level relationships. However, it would be great if we could filter (maybe using .where)  based on properties of the related objects. I have seen other issues where you mention that the queryBuilder is the tool for this case. But the problem with the query builder is that we wont have typed queries. Im assuming is a very hard feature to implement. Let me know if you have any plans on doing something like I mention.

**Comment by Alex0007** [comment]
@pleerock 
Nested props don't work in current `alpha` version published on npm. But working at `0.2.8`

**Comment by adesege** [comment]
I don't think this works anymore. Currently getting a typescript error when using sub-relations

```
Argument of type '{ relations: string[]; }' is not assignable to parameter of type 'FindOptionsWhere<User>'.
  Object literal may only specify known properties, and 'relations' does not exist in type 'FindOptionsWhere<User>'.```

even though the property exists

**Comment by Evilart86** [comment]
It's very cool!)
But. You have more specific topics for relations such as whole section "Relations" or topic "Working with Relations", but you put this example to "Find Options". I'd never look for it there... As result I have spent too much time to find this solution((

Yes, I know that this is my problem, but maybe can you put few examples in this section/topic

**Comment by Kononnable** [comment]
@Evilart86 Contributions to make documentation better are always welcomed.

**Comment by mbret** [comment]
I tried to load nested relations as the doc suggest but no matter what I do I always get an error.
The message looks usually like this
`Relation with property path title in entity was not found.` with title being my property.
Is the current version of the package broken ?

**Comment by MarkJAmes1217** [comment]
> I added more advanced support to `relations` of the find options, e.g.
> 
> ```ts
> const posts = await connection.getRepository(Post).find({ relations: ["photos", "user", "photos.user", "counters.author"] });
> ```
> 
> It was a hard feature to implement, because sub-relations can be joined via embeds, but I did it ;)
> This feature will be available in `0.1.7`. Contributions to docs are welcomed.

i try this code and got an error relation * was not found, so i change my code with this :

const posts = await connection.getRepository(Post).find({ relations: ["photos", "photos.user", "counters.author"] })

**Comment by midhunadarvin** [comment]
I am getting this feature. I have used it like this 
```
const response = await getManager().find(Post, {
    relations: ["user", "user.company"]
});
```

These are my entities 

```
@Entity()
export class Post {
    @PrimaryGeneratedColumn("uuid")
    public id: string;

    @ManyToOne(() => User, (user) => user.id, { nullable: false })
    @JoinColumn({ name: "user_id" })
    public user: User;
}
```

```
@Entity()
export class User {

  @PrimaryGeneratedColumn("uuid")
  public id: string;

  @ManyToOne(() => Company, (company) => company.id)
  public company: Company;
}
```

```
@Entity()
export class Company {

  @PrimaryGeneratedColumn()
  public id!: number;

  @Column({ nullable: false })
  public name!: string;

}
```

**Comment by romcok** [comment]
It's in the documentation but it's not working nor in the @next.
https://typeorm.io/#/find-options/basic-options
```
userRepository.find({ relations: ["profile", "photos", "videos", "videos.video_attributes"] });
```

**Comment by kastudillo** [comment]
thanks @pleerock !

**Comment by iamchathu** [comment]
I tired with relations with dot notation approch on version `^0.2.22` but it return null

**Comment by iamchathu** [comment]
Does this works for next level too? like `video.video_attributes.uploadedBy`

**Comment by ItsWendell** [comment]
Hi, I wanna do something similar but then for mapping.

I have a company entity, a reviews entity and an industry entity, I wanna get a company by Id with all the linked industries to it's linked reviews. I managed to get all the reviews with their industry using the following query:

```
      const company = await this.companyRepository
        .createQueryBuilder('company')
        .where({
          'company.id': companyId
        })
        .leftJoinAndSelect("company.agency", "agency")
        .leftJoinAndSelect('company.reviews', 'review')
        .leftJoinAndSelect('review.industry', 'industry')
        .loadRelationCountAndMap('company.like_count', 'company.like')
        .loadRelationCountAndMap('company.review_count', 'company.reviews')
        .getOne();
```

Now what I actually want is to add a industries property to company that links all the industries linked to the review, any tips?

**Comment by t-heu** [comment]
FindRelationsNotFoundError: Relation "photos.url" was not found, please check if it is correct and really exist in your entity

const users = await repoUser.find({
    select: ['email', 'username'],
    relations: ["photos", "photos.url"],
})

Entitys
- Photo
@Entity()
export class Photo {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  url: string;

  @ManyToOne(type => User, user => user.photos)
  user: User;
}

- User
@Entity('User')
export class User {
    @PrimaryGeneratedColumn('uuid')
    id: string

    @Column()
    username: string;

    @Column()
    email: string;

    @Column()
    password: string;

    @CreateDateColumn({ type: 'timestamp' })
    createdAt: Date;

    @UpdateDateColumn({ type: 'timestamp' })
    updatedAt: Date;

    @OneToMany(type => Photo, photo => photo.user)
    photos: Photo[];

    @BeforeInsert()
    async hashPassword(): Promise<void> {
      const hash = await bcrypt.hash(this.password, 8)
      this.password = hash
    }
}

**Comment by ovichowdhury** [comment]
Excellent feature. using like this and worked well.
`findOne(id,{
    relations: ["nominees", "nominees.guardain"]
});`

**Comment by backciro** [comment]
> I added more advanced support to `relations` of the find options, e.g.
> 
> ```ts
> const posts = await connection.getRepository(Post).find({ relations: ["photos", "user", "photos.user", "counters.author"] });
> ```
> 
> It was a hard feature to implement, because sub-relations can be joined via embeds, but I did it ;)
> This feature will be available in `0.1.7`. Contributions to docs are welcomed.

you the best m8

**Comment by tooleks** [comment]
Is there a way to use a relation to filter a query results?

```
const posts = await connection
    .getRepository(Post)
    .find({
      relations: ['photos', 'user', 'photos.user', 'counters.author'],
      where: {
        'photos.name': 'Nature',
      },
    });
```

**Comment by bennyn** [comment]
I am getting:

> error TS2769: No overload matches this call

When switchting from:

```ts
return StrategyEntity.findOne({
  relations: ['account'],
  where: {
    id: strategyId,
    account: {
      owner: {
        userId: query.userId,
        platform: query.platform,
      },
    },
  },
});
```

to:

```ts
return StrategyEntity.findOne({
  relations: ['account', 'account.owner'],
  where: {
    id: strategyId,
    account: {
      owner: {
        userId: query.userId,
        platform: query.platform,
      },
    },
  },
});
```

**Comment by backciro** [comment]
still so inefficient... :(

**Comment by guitexa** [comment]
Hi,

Does everyone know how to find in a sub-relations?

On the image below you can see...
 1. on top, I search for `status_order` on the main object and it works fine, look that I bring the `clients` object with `relations` options;
 2. at bottom, I search for `company_name` on the sub-relation object, and nothing returns.

![search1-2](https://user-images.githubusercontent.com/34251231/98711962-7580a900-2364-11eb-928f-27cfd8e7298f.png)

**Comment by Dr-Phone** [comment]
> I added more advanced support to `relations` of the find options, e.g.
> 
> ```ts
> const posts = await connection.getRepository(Post).find({ relations: ["photos", "user", "photos.user", "counters.author"] });
> ```
> 
> It was a hard feature to implement, because sub-relations can be joined via embeds, but I did it ;)
> This feature will be available in `0.1.7`. Contributions to docs are welcomed.

Hi,

I'm trying to achieve the same result using query builder but couldn't quite get it. Can anybody help how to do the same using querybuilder?

**Comment by alkema** [comment]
@pleerock FTW.

**Comment by rojanawi-droople** [comment]
On my side it didn't work if the relationship was already eagerly loaded. That is, if in `Post` you have `eager: true` on the `photos` field, then having `relations: ["photos.user"]` didn't work (error: `Relation "photos.user" was not found`) and if you try to add again `photos` like `relations: ["photos", "photos.user"]` then you get another error (table name specified more than once) so I really needed to remove the `eager: true` and specify both relations and it worked.

Note: I am using typeorm version ^0.2.32

**Comment by ddpana** [comment]
How about many to many relations? Does this work? 

Users have many groups, groups have many roles.
When trying this:
```
return await this.usersRepository.find({
  relations: ['groups', 'groups.roles']
});
```

Does not work: 
If I leave only "groups" as a relation, it works.
Also Both Users and Groups only with one single level, it works.
I tried with eager true and false and nothing.

the code below:

Users:
``` 
@ManyToMany(() => UserEntity, user => user.groups, { createForeignKeyConstraints: false, eager: false })
  @JoinTable({
    name: "group_users",
    joinColumn: {
      name: "userId",
      referencedColumnName: "id"
    },
    inverseJoinColumn: {
      name: "groupId",
      referencedColumnName: "id"
    }
  })
  groups: GroupEntity[];
```

Groups: 
``` 
@ManyToMany(() => GroupEntity, group => group.roles, { eager: false })
  @JoinTable({
    name: "role_groups",
    joinColumn: {
      name: "groupId",
      referencedColumnName: "id"
    },
    inverseJoinColumn: {
      name: "roleId",
      referencedColumnName: "id"
    }
  })
  roles: RoleEntity[];
```

**Comment by edster9** [comment]
> I added more advanced support to `relations` of the find options, e.g.
> 
> ```ts
> const posts = await connection.getRepository(Post).find({ relations: ["photos", "user", "photos.user", "counters.author"] });
> ```
> 
> It was a hard feature to implement, because sub-relations can be joined via embeds, but I did it ;) This feature will be available in `0.1.7`. Contributions to docs are welcomed.

Is it possible to do the same with load loadRelationIds? Example loadRelationIds: { relations: ['photos.user'] } to just load the ids also in a nested way?

**Comment by Gleb-Gaiduk** [comment]
Doesn't work for me in a situation with "entity.relation.relation" case:
```
 const [results, total] = await queryBuilder
        .leftJoinAndSelect(`order.products.product`, `product`)
        .take(limit)
        .skip((page - 1) * limit)
        .orderBy(`${alias}.${sortField}`, sortOrder)
        .getManyAndCount();
        ```
Getting: **Relation with property path products.product in entity was not found."**

But in the case of "entity.relation" nesting works as expected.
Any ideas?

**Comment by PetrShchukin** [comment]
I have an issue when filtering by nested relationships.
Let's say I have "OneToMany" with the following tables Persons -> Addresses -> Cities tables.
This code doesn't work
```
const persons = await this.personsRepository.find({
  relations: ['address', 'address.city'],
  where: {
    address: { city: { name: 'My City' } },
  },
});
`````
In logs I can see it uses "Persons__addresses"."name" instead of "Persons__addresses__cities"."name"

**Comment by 2020-JAUG** [comment]
> I added more advanced support to `relations` of the find options, e.g.
> 
> ```ts
> const posts = await connection.getRepository(Post).find({ relations: ["photos", "user", "photos.user", "counters.author"] });
> ```
> 
> It was a hard feature to implement, because sub-relations can be joined via embeds, but I did it ;) This feature will be available in `0.1.7`. Contributions to docs are welcomed.



> I added more advanced support to `relations` of the find options, e.g.
> 
> ```ts
> const posts = await connection.getRepository(Post).find({ relations: ["photos", "user", "photos.user", "counters.author"] });
> ```
> 
> It was a hard feature to implement, because sub-relations can be joined via embeds, but I did it ;) This feature will be available in `0.1.7`. Contributions to docs are welcomed.

Thank you very much! in 2022 this answer helps me to know how to access nested relations. And this issues too ;)

**Comment by macksal** [comment]
> On my side it didn't work if the relationship was already eagerly loaded. That is, if in `Post` you have `eager: true` on the `photos` field, then having `relations: ["photos.user"]` didn't work (error: `Relation "photos.user" was not found`) and if you try to add again `photos` like `relations: ["photos", "photos.user"]` then you get another error (table name specified more than once) so I really needed to remove the `eager: true` and specify both relations and it worked.
> 
> Note: I am using typeorm version ^0.2.32

I'm finding this is still true in 0.3.22. I think it can be considered a bug.

**Comment by alumni** [comment]
@macksal if you think something doesn't work as expected, please open a separate issue with a minimal reproducible example.

These old tickets are often difficult to reproduce as described, so some fresh example is always good to have 🙂
