### ISSUE TITLE
Cordova driver does not support additional options to `openDatabase`

### ISSUE THREAD

**Issue by jessehon** [typeorm/typeorm#1271]
It seems the only options passed into `window.sqlitePlugin.openDatabase` is `name` and `location` (see below)

https://github.com/typeorm/typeorm/blob/e834336730b1af923509480a3b847ead2e1e083b/src/driver/cordova/CordovaDriver.ts#L75

This is fine for the basic https://github.com/litehelpers/Cordova-sqlite-storage but would not support advanced usage or any plugins that have additional params.

e.g. 
 - https://github.com/litehelpers/Cordova-sqlcipher-adapter

**Comment by pleerock** [comment]
@daniel-lang to support this feature we can use `extra` property of connection options and merge it into the connection options passed to the `openDatabase` function

**Comment by daniel-lang** [comment]
I created a PR for it
