### ISSUE TITLE
Version 0.2.0: Disable updateEntity globally

### ISSUE THREAD

**Issue by daniel-lang** [typeorm/typeorm#1273]
It would be great if `updateEntity` could be set globally (maybe per connection) instead of only on query builder.
Reason: When a driver like SQLite is used, where a seperate query is generated to update the query, it might be useful to disable this feature by default and only enable it when needed.
Maybe this is already possible and I just missed it.

**Comment by pleerock** [comment]
separate query for updateEntity is required, its by design and makes all typeorm features to work properly, why do you want to disable this feature?

**Comment by pleerock** [comment]
btw you can disable this but some features may not work as they intended:

* create column will not be updated in the entity
* update column will not be updated in the entity
* version column will not be updated in the entity
* generated default values will not be updated the entity

To disable it you can pass an option to the `save` method:

```ts
repository.save(entity, { reload: false });
```

**Comment by daniel-lang** [comment]
> separate query for updateEntity is required, its by design and makes all typeorm features to work properly

I understand that and it's an awesome feature. I'm just asking if there is an easier way to disable it when needed.

**Example** 
I have an app where I load a lot of entities from an API. They all have an id and no column what would be set on insert. Therefore there is no reason to check if it changed. I can use `updateEntity`  or `reload` to disable it every time, but maybe it would be nice to have a global possible.
I don't know how easy this would be. It's just an idea.

**Comment by pleerock** [comment]
I don't think its a good idea to add such global thing. Disabling this actually breaks functionality orm supposed to bring, which is not good. If in some cases you need to disable to improve query - you can do it by disabling it via reload or updateEntity, but this should be used in specific cases, not every time.

**Comment by daniel-lang** [comment]
Okay, that makes sense
