### ISSUE TITLE
Conflicting columns?

### ISSUE THREAD

**Issue by leebenson** [typeorm/typeorm#1274]
I noticed this in the docs:

```js
// example how to load DM entities
const users = await userRepository.find({ skip: 2, take: 5 });
const newUsers = await userRepository.find({ isActive: true });
const timber = await userRepository.findOne({ firstName: "Timber", lastName: "Saw" });
```

What happens if there are columns named `skip` or `take`?

**Comment by pleerock** [comment]
ORM kinda reserves these property names and it will use `skip` and `take` for pagination instead of column criteria. To use column criteria you'll need to do:

```ts
const users = await userRepository.find({ where: { skip: 2, take: 5 } });
```

Yes, its a bit tricky, but its a small downside compared with benefits find options bring.

**Comment by leebenson** [comment]
Np. I've literally just started using TypeORM, so this wasn't a use-case I'd run up against- just something I spotted in the docs that wasn't explained.

**Comment by pleerock** [comment]
I did not add note in the docs because possibility of having such conflicts is very low, and I did not want to confuse users. But this totally should be documented somewhere, in kinda "secondary place" for user eyes.
