### ISSUE TITLE
[Question] One-To-Many on itself with ES6

### ISSUE THREAD

**Issue by FlorianDewulf** [typeorm/typeorm#1275]
Hi,

I have a very specific problem, and I don't know if I'm doing something wrong and the lack of ES6 doc/example makes it difficult to resolve.
I have a model with a "parentId", to build a simple tree. I have a many-to-one relation (to get the parent) and it works well, but when I want to create the relation for the opposite (to get the childrens), I have an error : 
```
TypeError: Cannot read property 'joinColumns' of undefined
    at /os/build/node_modules/typeorm/query-builder/SelectQueryBuilder.js:942:57
    at Array.map (<anonymous>)
    at SelectQueryBuilder.createJoinExpression (/os/build/node_modules/typeorm/query-builder/SelectQueryBuilder.js:918:55)
    at SelectQueryBuilder.getQuery (/os/build/node_modules/typeorm/query-builder/SelectQueryBuilder.js:85:21)
    at SelectQueryBuilder.QueryBuilder.getQueryAndParameters (/os/build/node_modules/typeorm/query-builder/QueryBuilder.js:234:70)
    at SelectQueryBuilder.<anonymous> (/os/build/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1348:35)
    at step (/os/build/node_modules/typeorm/query-builder/SelectQueryBuilder.js:42:23)
    at Object.next (/os/build/node_modules/typeorm/query-builder/SelectQueryBuilder.js:23:53)
    at /os/build/node_modules/typeorm/query-builder/SelectQueryBuilder.js:17:71
    at Promise (<anonymous>)
```

I tried a lot of thing but never found a solution. Here is the code of the schema entity : 
```const Page = require('../entities/Page')

module.exports = {
  target: Page,
  table: {
    name: 'pages'
  },
  columns: {
    id: {
      primary: true,
      type: 'integer',
      generated: true
    },
    url: {
      type: 'varchar',
      unique: true
    },
    page_title: {
      type: 'varchar',
      nullable: true
    }
  },
  relations: {
    parent: {
      target: () => Page,
      type: 'many-to-one',
      joinColumn: true
    },
    childrens: {
      target: () => Page,
      type: 'one-to-many',
      joinColumn: {
        name: 'parentId'
      }
    }
  }
}
```

And the error occured when I try to do the join : `getRepository(Page).createQueryBuilder('pages').leftJoinAndSelect('pages.childrens', 'childrens').where('pages.id = :id', { id: 1 }).getOne()`

I tried the set joinColumn in childrens as `true`, to add in the parent relation the flag `inverseJoinColumn: true`, and other several things but I never got something working :(

**Comment by pleerock** [comment]
Can you create a github repo with minimal code needs to reproduce your issue - this way I'll  be able to help you quickly

**Comment by FlorianDewulf** [comment]
Here is the repo : https://github.com/FlorianDewulf/debug-typeorm
- Set your mysql credentials in `connection.js`
- `node index.js`
- Init your database with this : 
```insert into pages (url, page_title) values('Parent page', 'title');
insert into pages (url, page_title, parentId) values('Child page', 'title', 1);
insert into link_pages(reference_page_id, linked_page_id) values(1, 2);
```
- And then you can test : 
http://localhost:3000/parent
http://localhost:3000/child

As you can see, the many to one relation works (it shows the parent in the child) and the many many works too (you can see the linked pages in the parent).

But now, uncomment the childrens relation in `/models/schemas/Page.js` and uncomment the line in `/controller/defaultController.js` in the parent function.
Now if you try the route for the parent, the error is displayed in your terminal.

Apparently, it doesn't find the joinColumn key of the relation (the order between the name and referencedColumnName can be wrong, I tried too much things)


Thanks for your help :)

**Comment by pleerock** [comment]
When you are creating inverse side of the same relation you need to specify sides. Code to fix your issue:
```js
    parent: {
      target: () => Page,
      type: 'many-to-one',
      joinColumn: true,
      inverseSide: "childrens"
    },
    childrens: {
      target: () => Page,
      type: 'one-to-many',
      inverseSide: "parent"
    },
```

**Comment by FlorianDewulf** [comment]
Hi,

Oh ok, I didn't know I had to use it this way, I tested this flag but I thought it was a boolean (to enable automatically the inverse side). Thanks !
I wish I could get some spare time to contribute to the repo with some ES6 example, because it's clearly missing.
Thanks for your answer !

**Comment by pleerock** [comment]
We are really seeking for a community support in terms of es6/es5. There are lot of tasks right now and I cannot handle them all. Feel free to contribute!

**Comment by Romstar** [comment]
@pleerock How can I contribute to the ES6/ES7 documentation? I am currently running into landmines and solving them and I would like to share my findings.

**Comment by TotallWAR** [comment]
@pleerock do you have examples of project with es6/es7 typeorm?
I can't realise relationships between tables. Typeorm doesn't create columns for foreign keys...

**Comment by Mystilund** [comment]
@TotallWAR Hi, I have some examples for you on one of my unfinished project : https://github.com/Lund-Org/livedeck-server/tree/master/src/database/schemas
There is a many-many relation and a many-to-one (it's the same format for the one-to-one)

I hope it will help you :)

**Comment by TotallWAR** [comment]
@Mystilund thank you!

**Comment by TotallWAR** [comment]
@Mystilund Did you try to use "class-validator" with es7 syntax? How do you validate fields?

**Comment by renilbabu03** [comment]
@pleerock : Man. You saved my day. Thanks
