### ISSUE TITLE
about couchbase(couchdb) driver

### ISSUE THREAD

**Issue by zhuangpeng** [typeorm/typeorm#1276]
hello

     I use couchbase server, It's like Mongodb, a json database.  typeorm haven't the driver supports.
Can I define driver myself? or offical can provide the driver?

    thanks!

**Comment by pleerock** [comment]
Official support is not planned and unlikely will be. Yes you can implement your own driver, take a look how mongodb driver is implemented. But tbh its not a trivial task because of difference you may have with rdbms drivers.

**Comment by marc0s** [comment]
@zhuangpeng did you start any development on this?  I'd be interested in a couchbase driver, willing to develop it myself if needed.  I'm in an evaluation phase, but chances to have the resources to work on this are high.

Any other advice/tip apart from studying the mongodb driver, @pleerock ?

Thanks!

**Comment by pleerock** [comment]
source code is place of studying, just take a look on mongodb driver and start digging things

**Comment by zi9o** [comment]
Hi guys, I hope everyone is doing good. @zhuangpeng and @marc0s would it be rude when asking if you worked on this driver for couchbase?

**Comment by corbinu** [comment]
@zi9o I have been working on a fork for Couchbase. It is a little complicated as the MongoDB driver really is missing a lot of features Couchbase supports due to N1QL. I will update when I am getting closer to having something to release.

**Comment by dzcpy** [comment]
Any progress?

**Comment by corbinu** [comment]
@dzcpy Sorry I am no longer using typeORM

**Comment by dzcpy** [comment]
Is there any one interested in developing one?
