### ISSUE TITLE
Sync entities etc by hand (angular SSR, webpack)

### ISSUE THREAD

**Issue by FriOne** [typeorm/typeorm#1277]
I'm making express server with angular and typeorm. I made [ugly hack](https://github.com/FriOne/ng-universal-with-socket-io/blob/461ac5c31f3ec1fff54602df151b1da1fb0f3e1d/webpack.server.config.js#L54) with `PlatformTools` in webpack to make it work. I have problems with synchronization (I disable it for now) - PlatformTools imports entities `ts` files by name.
Is there a way to make sync y hand?

And one more thing, is there a way to make migration from entity? I thought that when I enable sync and start server with ts-node I will get `User` entity migration.

**Comment by daniel-lang** [comment]
I guess the problem with your `PlatformTools` is, that it doesn't use version intended for Node.js but rather the one browser usage. This is something that will probably change in the next release (because of this PR #1280).

I'm not quiet sure I understand why you want to sync your entities by hand and what the problem is. You can call `connection.synchronize()` to trigger the synchronization process but that will be the same as the one at startup.

Use can use TypeORM's CLI to generate a migration from your entities. You can find an example on how in the [docs](http://typeorm.io/#/using-cli/generate-a-migration-from-exist-table-schema).

**Comment by FriOne** [comment]
@daniel-lang Thanks, great work!
Sync are trying to get ts files by `require` by `load` method dynamically, but it should not get them at all because I importing them inside main file. And then webpack bundle them.
Sorry about migration, yeah now I see that it is creates table in database, I thought it creates migration file which can be used in future.

**Comment by daniel-lang** [comment]
Did you specify your entities like this
```typescript
entities: [
   __dirname + "/entity/*.js"
]
```
or 
```typescript
entities: [
     Photo
],
```
With the second option you should be able to package and use the entities without addtional requires.

TypeORM is able to create a migration file from your entities. It uses an internal table to keep track of which migrations already ran.

**Comment by FriOne** [comment]
@daniel-lang entities import works, thanks.

There is version mismatch, [this exmaple](https://github.com/typeorm/ionic-example#typeorm--018) tells that version should be >= 0.1.8, but you already added changes in 0.1.7.

Actually my problem with PlatformTools is because of webpack. It cannot parse `require` with expressions like this `require(name)`. It would be nice if PlatformTools imports only static modules, like `pg` or `pg-native`, modules that is not needed, can be ignored by webpack config.
I see that PlatformTools is used for requiring `app-root-path` module by name only. So why not simply require it like `require('app-root-path')` instead of `PlatformTools.load('app-root-path)`?

**Comment by daniel-lang** [comment]
Thanks for pointing out the version mismatch. I was confused by our package.json.

The reason for using `PlatformTools.load('sqlite')` for example is, that TypeORM can also be used for browser based projects where we swap out the PlatformTools class for one, that doesn't use require. As are as I know, thanks to #1143, require() statements are already explicit to make them work with server webpack projects.
But where we just started supporting Node.js webpack projects, so any input is welcome.

**Comment by FriOne** [comment]
@daniel-lang well, actually it doesn't. Or maybe a missed something in my config?

I'm not webpack expert, but I guess it cannot bundle [this](https://github.com/typeorm/typeorm/blob/1303fa91fb5f51839f940b669c6e2b43bb6b431b/src/platform/PlatformTools.ts#L107) and [this](https://github.com/typeorm/typeorm/blob/1303fa91fb5f51839f940b669c6e2b43bb6b431b/src/platform/PlatformTools.ts#L113). It doesn't run code it simply searches for `require` and replace them with modules. 
So the problem is with loading, for example, `app-root-path` [here](https://github.com/typeorm/typeorm/blob/2758aec2a15745ec653bb107677bf33e7007afdb/src/logger/FileLogger.ts#L100), we could replace it with simple require. And then remove requiring with expressions from `PlatformTools`. I will try to make PR later if you want to.

You can reproduce problem [here](https://github.com/FriOne/ng-universal-with-socket-io/tree/typeorm-test) - `npm run build:ssr` anf then `npm run serve:ssr`.

**Comment by daniel-lang** [comment]
@EreckGordon You got TypeORM with webpack working on the server, right? How did you go about the mentioned require statements?

@FriOne I personally haven't tried it yet, sorry. Maybe I will find the time to check it out myself

**Comment by EreckGordon** [comment]
The explicit require statements added to PlatformTools allowed me to bundle an angular universal project with webpack. I was able to get postgres to bundle and run properly. That being said, once you add more nodejs packages, you are sure to run into more problems. I ran into an issue with argon2 (for salting passwords) as well as with nestjs (it would start loading, but fail and exit without an error message). At that point I threw webpack away and just used good ol tsc for the backend.. https://github.com/EreckGordon/angular-universal-pwa-starter has angular cli + universal + typeorm + nestjs (an expressjs based server written in typescript)

**Comment by pleerock** [comment]
what is resolution on this issue?

**Comment by ajaygangarde** [comment]
@daniel-lang  
for this
entities: [
     Photo
],
i am unable to import my User.ts entity 
Like
import User from './server/entities/User';
Throwing me an error like 

Unhandled Promise rejection: Unexpected identifier ; Zone: <root> ; Task: Promise.then ; Value: C:\Users\user\dev\platform\ormconfig.js:3
import User from './server/entities/User';
       ^^^^

SyntaxError: Unexpected identifier 

I think ts import not allowing me inside ormconfig file.

Can you please help me in this as i am doing for angular SSR Build .
