### ISSUE TITLE
CLI: migration:run and migration:generate name difference between code and docs

### ISSUE THREAD

**Issue by daniel-lang** [typeorm/typeorm#1281]
The command to create a new migration is `migrations:create` but docs states `migration:create`. Same goes for `migrations:generate` and `migration:generate` (docs).
It seems that the commands where renamed for 0.0.5
What should change? Do we update docs or change the name back?
I don't know the original reason for the rename but, just looking at the name, it would make more sense to call them `migration:create` and `migration:generate` as only one file/migration is created.

TypeORM version: 0.1.7
Doc page: [Using CLI](http://typeorm.io/#/using-cli/generate-a-migration-from-exist-table-schema)

**Comment by pleerock** [comment]
So are you suggesting to replace all "migrations:" prefix to "migration:" ?

**Comment by daniel-lang** [comment]
No, it might make sense to keep `migrations:create`, `migrations:generate` and `migrations:run` but if we leave it at the versions with "s", the docs should be correct.
So if you want to keep the "migrations:" prefix, I would update docs.

**Comment by pleerock** [comment]
The only thing I don't like about "migrations:" is difference between "migrations:create" and "entity:create" and "subscriber:create" (second and third do not have "-s" ending). And yes, of course docs must be correct even if we don't decide yet what naming to choose.

**Comment by daniel-lang** [comment]
okay, so it would make sense to have `migration:create`, right? Would you change `migrations:run` as well?

**Comment by pleerock** [comment]
Looks like yes

**Comment by daniel-lang** [comment]
Do you want me to create a PR for it?

**Comment by pleerock** [comment]
yes, would be great, against `next`. We shall also update docs

**Comment by pleerock** [comment]
Resolved.
