### ISSUE TITLE
FEATURE REQUEST - Naming strategy joinTableColumnName has to know if it is called from the owning or owned (inverse) context

### ISSUE THREAD

**Issue by risa** [typeorm/typeorm#1282]
Hello,

I have a legacy database I need to work with that uses slightly odd naming conventions for M:N relation. Example:

```shell
+-------------+--------------+----------------------------+
|                prefix__Question                         |
+-------------+--------------+----------------------------+
| id          | int(11)      | PRIMARY KEY AUTO_INCREMENT |
| title       | varchar(255) |                            |
+-------------+--------------+----------------------------+

+-------------+--------------+----------------------------+
|                prefix__Category                         |
+-------------+--------------+----------------------------+
| id          | int(11)      | PRIMARY KEY AUTO_INCREMENT |
| name        | varchar(255) |                            |
+-------------+--------------+----------------------------+

+-------------+--------------+----------------------------+
|           prefix__Question__categories                  |
+-------------+--------------+----------------------------+
| slot        | int(11)      | PRIMARY KEY FOREIGN KEY    |
| col         | int(11)      | PRIMARY KEY FOREIGN KEY    |
| item        | int(11)      | PRIMARY KEY FOREIGN KEY    |
+-------------+--------------+----------------------------+
```
The ```slot``` is autogenerated ID, ```col``` refers to ```Category.id``` and ```item``` refers to ```Question.id```

I do not need to insert data (yet). I am trying to build a custom naming strategy for these join tables.
For the ```joinTableColumnName``` I need to know if it is called in the junctionColumns context (i.e. the owning part
of the relationship) or the inverseJunctionColumns (i.e. the owned part of the relationship).

I have prepared a small fix which adds the fourth parameter to the joinTableColumnName called inverse. If it is called
from the owned part its value is false, if from the inverse part it is true. This allowed me to prepare a naming strategy
which works also with my legacy database structure.

Trivial tests are included too.

Please let me know if this PR is sane and even possibly acceptable.

Thank you

Richard

**Comment by pleerock** [comment]
Closing since feature was already merged.
