### ISSUE TITLE
Relate two completely seperate entities with a junction table

### ISSUE THREAD

**Issue by vados-p7e** [typeorm/typeorm#1285]
Is it possible to relate two completely separate entities with a `@JoinTable` annotation? When I try with `@ManyToMany`, `typeorm` produces sql that has one `.id` too many.

```js
@Entity('movie')
export default class Movie exends BaseEntity {
@PrimaryGeneratedColumn()
id: number;

@Relation??? // I can't find a relation annotation that makes this work properly
@JoinTable({
  name: "movie_tags",
  joinColumn: {name: "tag_id", referencedColumn: "id"},
  inverseJoinColumn: {name: "movie", referencedColumn: "id"}
})
tags: Tag[];

}
```

```js
@Entity('tag')
export default class Tag extends BaseEntity {
@PrimaryGeneratedColumn()
id: number;

@Column()
name: string;
}
```
In the database, I have a table called `movie_tags` which looks like this:

```sql
CREATE TABLE movie_tags (
  movie_id integer REFERENCES a(id),
  tag_id integer REFERENCES a(id)
);
```
What I *think* I want is a `@Relation` decorator that just tells type orm to try and look up a completely separate entity USING the junction table that exists.

I could use `@OneToMany`, but that forces me to make the relation `Movie -> RowInRelationTable`, when what I really want is the `Tag`s on the other side of the junction table to be resolved.

I could also solve this problem by making a more specific `movie_tags` table that stores all the fields that an individual `Tag` would have, but that means I can't use a `Tag` for anything other than a `Movie`.

I get really close using a `@ManyToMany` and `@JoinTable`, but the SQL generated by `typeorm` is wrong:

```sql
SELECT subject_tags_relation_id.tag_id.id AS "tag_id", subject_tags_relation_id.movie_id.id AS "movie_id" FROM "tags" "tags" INNER JOIN "movie_tags" "subject_tags_relation_id" ON (subject_tags_relation_id.movie_id.id = 112 AND                                                                                                                               
 subject_tags_relation_id.tag_id.id = "tags"."id") ORDER BY subject_tags_relation_id.tag_id.id ASC, subject_tags_relation_id.movie_id.id ASC;
```

Basically, the problem with this query is that there is an extra ".id" property being put onsomewhere inside `typeorm` and I'm not sure why/where. it already has the column it should want (`subject_tags_relation_id.tag_id`) then it tries to get the ID of that `subject_tags_relation_id.tag_id**.id**`), and the error is:

```
ERROR:  missing FROM-clause entry for table "movie_id"
```

Which makes perfect sense because `movie_id` is not a table.

**I feel really close, but also maybe think that maybe this is something that `typeorm` just doesn't support yet (arbitrary relations between entities using a junction table).**

BTW, I did try using JUST a `@JoinTable` by itself but that's not a thing, it seems -- the relation just never gets loaded, and if I try to force it, it says relation with property path `tags` wasn't found. Do I have no choice but to just use something like `@AfterLoad` or write my own `@Relation` that does what I want?

**Comment by vados-p7e** [comment]
Every time I look at the documentation `@ManyToMany` looks like exactly what I want, but I just can't figure out why this extra `.id` is getting in there and ruining everything.

**Comment by pleerock** [comment]
`subject_tags_relation_id.tag_id.id`looks wrong, it shall be just `subject_tags_relation_id.tag_id` I think. What typeorm version are you using? Can you check `next` version if this issue is fixed there? Are you able to contribute and create a failing test with this issue?

**Comment by vados-p7e** [comment]
Hey @pleerock thanks for taking a look -- I agree that it looks wrong, I will try `next` version and see if the problem is fixed -- if not I'll contribute a failing test case

**Comment by vados-p7e** [comment]
So it turns out this problem does not exist on `next` -- I don't know what changeset fixed it (I didn't deep dive to see what code caused the bug), but thanks for maintaining this wonderful library.

I'll close this ticket, I'll make the necessary changes to move my codebase to `next`
