### ISSUE TITLE
feature or question: how can I write some calculated column?

### ISSUE THREAD

**Issue by cybermerlin** [typeorm/typeorm#1288]
Hi, I need help with this:
```SQL
select
    birthday, sex,
    concat( lastname, '  ', firstname) as name
from person
where
    name like '%pupi%'
```
but I try use typeorm like a big trueman:
```javascript
class Person {
    @Column({type: 'text'})
    firstname;
    @Column({type: 'text'})
    lastname;
    @Column({type: 'datetime'})
    birthday;
    @Column({type: 'tinyint'})
    sex = 1;

    //                           what do I need to write here?
    name;
}

let persona = new Person();
persona.find({name: 'pupi', limit: 1});

console.info(persona.name);
```

**Comment by pleerock** [comment]
I'll close it since its tracked by #296

**Comment by cybermerlin** [comment]
as u wish
in any case, I finished this work
and started working on a next my task (look lateral_join in my repo)

**Comment by thatisuday** [comment]
I am following below apporach

```ts
@Column( 'varchar', { length: 200, nullable: false, unique: true } )
name: string;

// readonly url
private url: String;
    
@AfterLoad()
getUrl() {
    this.url = 'https://domain.com' + this.name;
}
```

**Comment by DJ-Icebear** [comment]
This doesn't work when referencing a related entity --> like:
```
@AfterLoad()
getUrl() {
    this.url = 'https://domain.com' + this.employer.name + '.jpg';
}
```
Anyone know how I would solve that?

**Comment by jbjhjm** [comment]
> This doesn't work when referencing a related entity --> like:
> 
> ```
> @AfterLoad()
> getUrl() {
>     this.url = 'https://domain.com' + this.employer.name + '.jpg';
> }
> ```
> 
> Anyone know you would solve that?

It works fine for me. Did you possibly forget to join the employer in your query?

**Comment by iandoe** [comment]
Hello, it is much simpler than this actually: 

```ts
  @Field(() => String, {
    description: 'Description of the item in plain text.',
  })
  public get descriptionPlain(): string {
    return stripMarkdown(this.description')
  }
```

does the job.

**Comment by phil294** [comment]
```js
class Person {
    //                           what do I need to write here?
    name;
}
```
You need to write `@Column({ select: false, readonly: true, insert: false })` and then in your query builder, select the field `person_name`. Also explained [here](https://github.com/typeorm/typeorm/issues/1822#issuecomment-573492291) (more of a workaround).

**Comment by pietrzakadrian** [comment]
I wrote an article on my blog about it.
I have presented all possible solutions, including one very well-functioning solution to this problem. (v0.2.37)

https://pietrzakadrian.com/blog/virtual-column-solutions-for-typeorm ✌️

**Comment by royeradames** [comment]
https://pietrzakadrian.com/blog/virtual-column-solutions-for-typeorm#5-decorator-method

**Comment by royeradames** [comment]
> I wrote an article on my blog about it. I have presented all possible solutions, including one very well-functioning solution to this problem. (v0.2.37)
> 
> https://pietrzakadrian.com/blog/virtual-column-solutions-for-typeorm ✌️

I read it, good solution. #5 it's exactly what I'm looking for.

**Comment by LuisOfCourse** [comment]
> I wrote an article on my blog about it. I have presented all possible solutions, including one very well-functioning solution to this problem. (v0.2.37)
> 
> https://pietrzakadrian.com/blog/virtual-column-solutions-for-typeorm ✌️

Hi @pietrzakadrian,
i get a strange empty error when getOne/getMany returns empty on NestJS.
I did some debug and I noticed that `Reflect.getMetadata` gives an error on `entities[0]` because it's undefined (when query returns null).

Something like this should solve the problem:   
`const metaInfo =Reflect.getMetadata(VIRTUAL_COLUMN_KEY, entities[0] || {}) || {};`

**Comment by nodegin** [comment]
You can do it like
```
  @Field()
  @Transform(({ obj }) => {
    return obj.id === 1
  })
  isAdmin: boolean;
```

**Comment by FrameMuse** [comment]
Not sure if this is related, but here's what works for me

```ts
@Column({ type: "number" })
someEntry: number

@Expose() // From `class-transformer` library.
protected get metrics() { // "Visible" only in response.
  return { one: this.someEntry + 3 }
}
```
