### ISSUE TITLE
TIME is converted to 'HH-mm' instead of 'HH:mm'

### ISSUE THREAD

**Issue by cserron** [typeorm/typeorm#129]
I've noticed the following bug when creating a column of type TIME. In my case, when I'm trying to insert the Date object, the time is converted into "HH-mm" instead of "HH:mm" and that causes the query to fail.

**Comment by eduardoweiland** [comment]
Caused by [this line](https://github.com/typeorm/typeorm/blob/95164dcbbdb8b23b7e4399d92dd13affa4f6d8ac/src/util/DataTransformationUtils.ts#L21). I think that changing it should be fine, as most databases (if not all) support "HH:mm" format.

**Comment by pleerock** [comment]
if its easy fix can someone create a PR? (if no I'll do it at the end of the week)

**Comment by cserron** [comment]
@pleerock @eduardoweiland I just sent that PR to be merged. Thank you both.

**Comment by pleerock** [comment]
released in `0.0.6`
