### ISSUE TITLE
.save() does not apply value Transformer when reading back from the db

### ISSUE THREAD

**Issue by CaptJakk** [typeorm/typeorm#1291]
In the alpha version 0.2.0, theres a bug where if you .save(obj) when it reads the object back out with the database defaults, it doesn't apply the value transformers so a lot of bigint's come back as strings even if you've set up a transformer.

**Comment by pleerock** [comment]
can you please provide a minimal reproduction code example?

**Comment by pleerock** [comment]
Closing as no answer from reporter.
