### ISSUE TITLE
IF NOT EXISTS while creating schema is not supported in all versions of Postgres

### ISSUE THREAD

**Issue by remojansen** [typeorm/typeorm#1292]
I want to suggest an improvement in the error reporting and explain what happened to me in case it may help others. 

## The issue

I'm working on a project and I wrote some tests. The tests were working perfectly on my local machine. In the CI server (Travis) I was getting the following error:

```
...
{ QueryFailedError: syntax error at or near "NOT"
    at new QueryFailedError (/home/travis/build/remojansen/zafiro/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query.<anonymous> (/home/travis/build/remojansen/zafiro/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:38)
    at bound (domain.js:280:14)
    at Query.runBound [as callback] (domain.js:293:12)
    at Query.handleError (/home/travis/build/remojansen/zafiro/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/home/travis/build/remojansen/zafiro/node_modules/pg/lib/client.js:132:26)
    at Connection.emit (events.js:159:13)
    at Socket.<anonymous> (/home/travis/build/remojansen/zafiro/node_modules/pg/lib/connection.js:118:12)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
  message: 'syntax error at or near "NOT"',
  name: 'QueryFailedError',
  length: 85,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '18',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1006',
  routine: 'scanner_yyerror',
  query: 'CREATE SCHEMA IF NOT EXISTS "demo"',
  parameters: [] }
    3) Should be able to perform POST and GET http requests
(node:3401) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
...
```

The entire log is [here](https://travis-ci.org/remojansen/zafiro/builds/311055797#L1727-L1760).

I spent a few hours investigating. First I thought that for some reasons the database was not ready for queries. I thought this because I saw the error:

> Cannot execute operation on "default" connection **because connection is not yet established**.

But I finally realized that the issue really was `syntax error at or near "NOT"` in `CREATE SCHEMA IF NOT EXISTS "demo"`.

## My solution

I was able to fix the issue by removing `@Entity({ schema: 'demo' })` from my code. The error was caused because in Travis CI the Postgres was `9.5` but on my local machine it was `10`.

## Suggested improvements

I would like to suggest some potential solutions so others don't waste as much time as I did while trying to figure out what was wrong:

- You could automatically remove `IF NOT EXISTS` if the version of Postgres is too old.

- You could decide that only some versions of Postgres are supported and document this. Also please document how to use the supported version on popular CI platforms.

- If there is an error during the schema creation the error `because the connection is not yet established` should be avoided. In this case, it should have been something like one of the following:

    > QueryFailedError: syntax error at or near "NOT" in command "CREATE SCHEMA IF NOT EXISTS demo". Please ensure that the version of Postgres that you are using is compatible with the preceding query.

    > QueryFailedError: syntax error at or near "NOT" in command "CREATE SCHEMA IF NOT EXISTS demo". Please ensure that the version of Postgres that you are using is compatible with `IF NOT EXISTS` in `CREATE SCHEMA` statements.

I hope you find this feedback useful. 

Thanks for all the great work done on this project 👍

**Comment by pleerock** [comment]
> CREATE SCHEMA IF NOT EXISTS

this statement is supported since [postgres 9.3](https://www.postgresql.org/docs/9.3/static/sql-createschema.html), probably you have different reason why it not worked for you. Not sure why you have this error, are you able to run plain query on CI (using cli or code at least) and check if query is successful without orm?

So, first and second suggestions are not valid in this case I guess.

Regarding to third suggestion, I need to reproduce error you have, because actual error you should have must be failed query, not failed connection.

I tried to reproduce your issue but failed. (what I did is changed [this line](https://github.com/pleerock/typeorm/blob/8cfc1392db9555e71ac23ba215082545bcebd640/src/driver/postgres/PostgresQueryRunner.ts#L504) and provided a wrong query):

```ts
        return Promise.all(schemas.map(schema => this.query(`CREATE SCHEMA IF NOTTT EXISTS "${schema}"`)));
```

And here is what error I have after running a test with custom schemas:

```
 1) multi-schema-and-database > basic-functionality custom-table-schema "before each" hook for "should correctly create tables when custom table schema used":
     QueryFailedError: syntax error at or near "NOTTT"
      at new QueryFailedError (src/error/QueryFailedError.ts:7:9)
      at Query.<anonymous> (src/driver/postgres/PostgresQueryRunner.ts:216:26)
      at bound (domain.js:301:14)
      at Query.runBound (domain.js:314:12)
      at Query.handleError (node_modules/pg/lib/query.js:143:17)
      at Connection.connectedErrorHandler (node_modules/pg/lib/client.js:132:26)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:118:12)
```

**Comment by remojansen** [comment]
@pleerock thanks for taking a look. I will try to do more testing and find a way to reproduce the issue. Please don't close the issue for now.

**Comment by pleerock** [comment]
Okay, thanks

**Comment by pleerock** [comment]
@remojansen  any updates?

**Comment by remojansen** [comment]
@pleerock I have done some tests and I was able to reproduce it:

Used docker to run 9.2:

```sh
export DATABASE_USER=postgres \
export DATABASE_PASSWORD=secret \
export DATABASE_HOST=localhost \
export DATABASE_PORT=5432 \
export DATABASE_DB=demo

docker run --name POSTGRES_USER -p "$DATABASE_PORT":"$DATABASE_PORT"  \
-e POSTGRES_PASSWORD="$DATABASE_PASSWORD"  \
-e POSTGRES_USER="$DATABASE_USER"  \
-e POSTGRES_DB="$DATABASE_DB" \
-d postgres:9.1
```
I tried to create the schema:

```sh
psql -c 'CREATE SCHEMA IF NOT EXISTS demo;' -U postgres -W -h localhost -p 5432 -d "demo"
```

And I got the error:

```
ERROR:  syntax error at or near "NOT"
LINE 1: CREATE SCHEMA IF NOT EXISTS demo;
```

The problem was that Travis CI uses 9.1 by default.
