### ISSUE TITLE
`deleteExecutedMigration` attempting to delete migration row from "query-result-cache" instead of "migrations"

### ISSUE THREAD

**Issue by vados-p7e** [typeorm/typeorm#1293]
https://github.com/typeorm/typeorm/blob/16794be9d92e2c9c375a76cacf6fc08714795410/src/migration/MigrationExecutor.ts#L291

The simple fix is pretty easy (`"query-result-cache"` -> `"migrations"`), but maybe those values shouldn't be hardcoded at all, and should come from some configuration?

**Comment by vados-p7e** [comment]
I've added a PR for this issue: https://github.com/typeorm/typeorm/pull/1294

**Comment by pleerock** [comment]
Thanks for the fix, it will be published in the next `next` version.
