### ISSUE TITLE
JSONB not de-serialized into javascript objects on `next` (0.2.0-alpha.10)

### ISSUE THREAD

**Issue by vados-p7e** [typeorm/typeorm#1295]
I'm not sure if this is a feature or a bug, but as I'm using `next`, I find that `"jsonb"` type columns are not being being deserialized properly into javascript objects. I noticed this when tests for my application broken so I don't think it's always been this way.

**Comment by pleerock** [comment]
Can you please provide a code with reproduction of this problem? (or better a PR with a failing test)

**Comment by vados-p7e** [comment]
Absolutely can, will do so in roughly ~24hrs

**Comment by pleerock** [comment]
Nice, thanks

**Comment by vados-p7e** [comment]
Hi @pleerock I actually can't reproduce the problem -- I wrote a test case, added the sample, but on `next` it seems to work just fine, (the property that is returned is of type `object`). When I try it in my own project things come back as JSON strings -- it must be an issue with the postgres class I'm giving the object or something.

After I finally tracked down the problem, it turns out that [if you mistakenly put a string into a postgres JSONB column it will remember (thanks to StackOverflow)](https://stackoverflow.com/questions/35372396/accidentally-stored-string-instead-of-object-in-postgres-jsonb-column). In an earlier migration I made some changes and fell into this pitfall -- when I would check the data in my tables, they were strings (surrounded by `""`s, and NOT regular `JSONB` according to postgres, though postgres did the needed conversions automatically).

I had to do 
```sql
db=# UPDATE <table> SET bad_data_column=(bad_data_column->>0)::JSONB;
```
Which was mentioned in that SO post liked earlier.

This was my fault, NOT the fault of `typeorm` -- sorry for the false alarm.

**Comment by vados-p7e** [comment]
Along the way though, I rewrote some of the test utility code in a way you might like, since I noticed that bad JSON in `ormconfig.json` was being conflated with `ormconfig.json` being missing alltogether.

https://github.com/typeorm/typeorm/pull/1300 is where I put that code

**Comment by icepeng** [comment]
I am also having this problem. json type is not de-serialized into objects.
using 0.2.0-alpha.10

**Comment by icepeng** [comment]
More precisely, the insert query does not cause problems, only the update problem.
parameters are shown as
insert - "{\"date\":\"2017-12-31T14:59:59.999Z\",\"dateFormat\":\"yyyy-MM-dd\"}"
update - "\"{\\\"dateFormat\\\":\\\"yyyy-MM-dd\\\",\\\"date\\\":\\\"2000-12-04T15:00:00.000Z\\\"}\""

**Comment by icepeng** [comment]
repository.update() method does not cause double stringify on object. Only repository.save() has issue.

**Comment by vados-p7e** [comment]
I can semi-confirm that the problem is likely from updating -- in my testing, I would find that the first time after I saved an internal object is when it would turn into a string.

I will try again to make a failing test case, though I'm traveling over the next few days 

@icepeng , here is the code I hacked up that will "fix" it for now:

```js
  @AfterLoad()
  fixJSONB() {
    // TODO: remove once typeorm version (currently '0.2.0-alpha.10') properly handles `jsonb`
    // At present, it returns a string, not a parsed object.
    if (typeof this.property === 'string') {
      Object.assign(this, {property: JSON.parse((this.property as string).toString())});
    }
  }
```

I put this method in all the objects (and duplicated that `if` statement) for all affected fields

**Comment by icepeng** [comment]
Maybe we have to open an issue with the correct title?
The fix may fix the output value, but the stored value will still be a string. How about using `@BeforeSave()` to transform value, or execute raw query in `@AfterSave()`?

**Comment by vados-p7e** [comment]
I think you're right about both things -- It would be better to create
another ticket (since this one has been closed), with a proper test case,
and `@BeforeSave` would also be the better place to make sure the value
wasn't a string.

I haven't tested whether the issue is observable in `@BeforeSave` yet, but
it might be

2017-12-07 12:12 GMT+09:00 icepeng <notifications@github.com>:

**Comment by pleerock** [comment]
@icepeng can you please provide a code example / git repo / failing test with reproduction of your problem?

**Comment by icepeng** [comment]
@pleerock I uploaded new issue and repo.
