### ISSUE TITLE
Perf drop on inactivity (postgres)

### ISSUE THREAD

**Issue by adrianhara** [typeorm/typeorm#1299]
Hi,

I'm experiencing a performance issue if no DB calls are made for around 10 seconds on a Postgresql DB. The query is a dead simple `findOne(id)`.

Scenario:
1. Do the query every second or some seconds, ~250msec.
2. Wait 10+ seconds, do the query again: ~1000msec

Using the pg library, without typeorm, the exact same query takes ~150msec all the time.

My code (in a custom repository which extends AbstractRepository<T>):
```
 console.time('repo')
 const data = await this.repository.findOne(options.id);
 console.timeEnd('repo')
```

Ideas?

**Comment by pleerock** [comment]
can you please provide a pg code snippet as well? (please use connection pool with `pg`)

**Comment by adrianhara** [comment]
Update: it turns out it's the same with pg. So it's probably a db problem (it's hosted on Heroku on the free tier, i'll try to upgrade it and see if that solves it).
