### ISSUE TITLE
Truly reactive repositories with postgres pub/sub

### ISSUE THREAD

**Issue by zakhenry** [typeorm/typeorm#13]
Ok this is a pretty difficult feature request, so bear with me, but postgres has pub/sub capabilities where it can subscribe to table events, and emit them back to the connection.

See this article for a good rundown - https://blog.andyet.com/2015/04/06/postgres-pubsub-with-json

With this integrated into the `ReactiveRespository`, an observable could be `subscribe`d to, and bound to a websocket in a controller making the backend app effectively a dumb pub/sub proxy to the database.

Now unfortunately there doesn't appear to be equivalent capabilities in MySQL, so that may put a damper on the idea.

**Comment by pleerock** [comment]
Im not against implementing platform-specific features, if they will be designed and implemented transparently. So I'll think about this and maybe later we will have this feature. But right now I have different priorities - all general, commonly used features, more database drivers and core stabilization, so I will not be able to take case of this issue right now. Maybe in the future, or until someone will take care of this feature

**Comment by zakhenry** [comment]
Yea I agree, there is a huge amount of work in this feature I think, especially when considering the implications it has on migrations. 

I'll think on it, I can probably implement a class that extends reactive repository and use it in the IOC container, so it should be fairly simple to create a PR once/if I get that working

**Comment by pleerock** [comment]
closing it as non-relevant at the moment.

**Comment by kuncevic** [comment]
I just discovered the article on that matter https://medium.com/@seonixx/postgres-publish-subscribe-with-nodejs-996a7e45f88 seems like useing `pg` package it is quite easy to achieve

**Comment by pleerock** [comment]
We are not planning this feature because there are plenty of other things need to be done at the moment. If you are interested in this feature implementation you can contribute and start discussion.

Or you can use underlying `pg` package for this purpose since typeorm uses `pg` package inside.

**Comment by kuncevic** [comment]
@pleerock yeah I notised that `pg` is something `typeorm` is relying on in case of posgress use case.
I am quite new with typeorm, had to play with that and with `pg` and come back if I will see if I can help to make that feature happen..

And again thanks for creating such a great library.
