### ISSUE TITLE
Export schema-builder classes to be used in migrations

### ISSUE THREAD

**Issue by eduardoweiland** [typeorm/typeorm#130]
Nice work with the migrations feature :)

I am trying to use it to create tables. I see that `queryRunner` has a method `createTable()` that takes a `TableSchema` argument, but I can't find a way to import `TableSchema` in my migrations file, as it is not exported in `src/index.ts`.

The only way I found to create table in migrations is using raw SQL queries, which is hard to read and prone to errors.

**Comment by pleerock** [comment]
easy fix. You just need to add exports all `*Schema` ts files in the `index.ts`. Can you create a PR? (if you can't I'll do it later on this week)

**Comment by pleerock** [comment]
released in `0.0.6`
