### ISSUE TITLE
Ionic + Active Record: ConnectionNotFoundError: Connection "default" was not found.

### ISSUE THREAD

**Issue by vhb56** [typeorm/typeorm#1301]
Using your ionic example code 'Data Mapper' pattern works.
But when i try 'Active Record' pattern, on user.save() i get this error:
```
ERROR Error: Uncaught (in promise): ConnectionNotFoundError: Connection "default" was not found.
Error
    at new ConnectionNotFoundError (vendor.js:220633)
    at ConnectionManager.get (vendor.js:109631)
    at Object.getConnection (vendor.js:18166)
    at Function.BaseEntity.getRepository (vendor.js:72744)
    at User.BaseEntity.save (vendor.js:72723)
    at MyApp.<anonymous> (main.js:319)
    at step (main.js:228)
    at Object.next (main.js:209)
    at main.js:203
    at new t (polyfills.js:3)
    at new ConnectionNotFoundError (vendor.js:220633)
    at ConnectionManager.get (vendor.js:109631)
    at Object.getConnection (vendor.js:18166)
    at Function.BaseEntity.getRepository (vendor.js:72744)
    at User.BaseEntity.save (vendor.js:72723)
    at MyApp.<anonymous> (main.js:319)
    at step (main.js:228)
    at Object.next (main.js:209)
    at main.js:203
    at new t (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at polyfills.js:3
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4983)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4974)
```

Also in your ionic example you didn't install 'reflect-metadata' & indeed everything works without it.
But in your documentation you say to install & import it, why so?

**Comment by pleerock** [comment]
> Also in your ionic example you didn't install 'reflect-metadata' & indeed everything works without it.
But in your documentation you say to install & import it, why so?

@daniel-lang can you please help me here

> But when i try 'Active Record' pattern, on user.save() i get this error:

can you provide your connection configuration?

**Comment by vhb56** [comment]
this?

```
        connOpts = {
          type       : 'sqljs',    
          autoSave   : true,
          location   : 'test',
          logging    : ['error', 'query', 'schema'],
          synchronize: true,
          entities   : [
            User,
            Favourites
          ]
        } as SqljsConnectionOptions;
```

**Comment by pleerock** [comment]
hmm I don't see anything that can lead to this problem...

**Comment by daniel-lang** [comment]
You don't need to install reflect-metadata because ionic does it for you ([changelog](https://github.com/ionic-team/ionic-app-scripts/blob/master/CHANGELOG.md#312-2017-11-13)). It is already included in the aot compiler.

I created a new branch for active record with the ionic example [here](https://github.com/typeorm/ionic-example/tree/active-record). These check that out and see where it differs from your approach

**Comment by vhb56** [comment]
sorry, i got this error using type 'sqljs' not 'cordova'

**Comment by daniel-lang** [comment]
Okay, but I still can't reproduce your error. How did you include sql.js?

**Comment by vhb56** [comment]
It is not about import, did the same in your example and it works.
I've no idea where is the problem, must investigate.

**Comment by vhb56** [comment]
hell, it was not about sql.js import, it was about how i've imported 'BaseEntity' in entity file,

VSC has automatically imported it for me like this:
`import { BaseEntity } from "typeorm/repository/BaseEntity";`

Instead in your example:
`import { BaseEntity } from "typeorm";`

And seems this was the problem, dumb error,  sorry about that, thx for help!

**Comment by daniel-lang** [comment]
This is something that I noticed as well and might be a problem because of the way I had to write the `NormalModuleReplacementPlugin`. It will only replace `typeorm` with `typeorm/browser`  if the path ends with `typeorm`. But I can't just replace every occurence of `typeorm`.

**Comment by vhb56** [comment]
Sorry for possibly dumb suggestion.
But maybe if it's possible replace things not based on the path end, but on what specifically was imported, like the class itself, like a list of classes that are used in specified context must be imported from 'typeorm/browser' so if they have different path -> change it.

**Comment by daniel-lang** [comment]
That would be great, but it has to be a regex that the import statement has to match. I could still change that to be `/typeorm/` instead of `/typeorm$/` but that would create a problem if other import would include "typeorm".
I only noticed that because I have the ionic example locally in a path like `/typeorm-org/ionic-example/` and ionic/webpack imports `main.js` with the full path. Therefore I got an error that the file `/typeorm/browser-org/ionic-example/src/app/main.js` doesn't exist. I haven't yet found a way to only filter the correct imports.

**Comment by vhb56** [comment]
btw, don't know if i should open an issue.
everything works but i'm getting this warning: 
`Invalid asm.js: Undefined global variable 0.js:461 `

Is this something i should worrying about?

**Comment by AliSnowaroma** [comment]
I get the same problem by using like this

`import { Module, forwardRef } from '@nestjs/common';
import { AppController } from './app.controller';
import IndexModule from './controllers/index.module'
import { AppService } from './app.service';
import { TypeOrmModule } from '@nestjs/typeorm';
import config from '@/config'
const { host, port, username, password, database } = config.mysqlConfig

@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'mysql',
      host,
      port,
      username,
      password,
      database,
      synchronize: true,
      logging: process.env.API_ENV !== 'real',
      autoLoadEntities: true
    }),
    forwardRef(() => IndexModule)
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}`

I haven't found a solution yet
