### ISSUE TITLE
Migrations from empty database to up and running.

### ISSUE THREAD

**Issue by utrolig** [typeorm/typeorm#1305]
Hello everyone!

In other frameworks like Sequelize and Knex, it's usually best practice to have your whole database-setup be done via migrations. That way you can easily go from a fresh database to one that is ready through migrations and seeds.

From what I've been able to find out from the documentation, the preferred way with TypeORM is to sync once, then use migrations for changes after syncing? 
This seems brittle, but maybe I'm misunderstanding how this works?

Another thing is, I export my database config as a constant from a typescript file which depends on environment variables. Is there any way I can use that same config with the CLI?

If anyone could shed some light on how this is usually done for a production application, please let me know.

**Comment by pleerock** [comment]
> From what I've been able to find out from the documentation, the preferred way with TypeORM is to sync once, then use migrations for changes after syncing?

no, sync is mostly for development, in production you can always use migrations without sync, you can also mix just like you want or you are sure about

> Another thing is, I export my database config as a constant from a typescript file which depends on environment variables. Is there any way I can use that same config with the CLI?

yes you can use environment variables instead of config file. More info [here](http://typeorm.io/#/using-ormconfig).

**Comment by utrolig** [comment]
Thank you for the quick response!

So would you recommend I write migrations for all tables then? I am rewriting an existing application where the database model is almost 100% set.

Being able to use ormconfig.js solves my second problem nicely.

**Comment by pleerock** [comment]
> So would you recommend I write migrations for all tables then? I am rewriting an existing application where the database model is almost 100% set.

*write manually* or *generate* ? If generate then yes, go ahead, if write manually then you don't need to do it since typeorm can generate migration for you (mysql at the moment)

**Comment by keenondrums** [comment]
@preelock can it generate for sqlite? I tried to feed an empty db to cli the other day, it said there was nothing to syncronize

**Comment by pleerock** [comment]
no it works only in mysql right now, but this feature (generation for all drivers) is under development currently and we are planning to release it next month in `0.2.0`

**Comment by keenondrums** [comment]
@pleerock is it already there at typeorm@next ?

**Comment by timc13** [comment]
eagerly looking forward to creating my postgres schema via an initial migration file...

**Comment by pleerock** [comment]
@keenondrums not yet, its under `schema-builder-refactoring` branch, you can compile and try, however there are some things broken on that branch yet, thus its not released in `next` yet

**Comment by pleerock** [comment]
Original author's question was answered. Closing.

**Comment by nolazybits** [comment]
@pleerock I am super keen to be able to create the schema with migrations :)
The `schema-builder-refactoring` doesn't look it exists anymore.
has the functionality been merged?

Thanks :)
