### ISSUE TITLE
Trying calculate distance with latitude and longitude

### ISSUE THREAD

**Issue by rbrose** [typeorm/typeorm#1306]
Hello,

i have to calculate the distance by latitude and longitude. With sql it works fine like:

`SELECT *,  (
                    6371 * acos(
                        cos(
                            radians( 52.490498333333335 )
                        ) * cos(
                            radians( latitude )
                        ) * cos(
                            radians( longitude ) - radians( 13.3498 )
                        ) + sin(
                          radians( 52.490498333333335 )
	                    ) * sin(
	                    radians( latitude )))
	          ) AS distance FROM event;
	          `

And i have this queryBuilder code that i get all events:

`        const events = eventRepository.createQueryBuilder("event")    
        .leftJoinAndSelect("event.user", "user")
        .leftJoinAndSelect("event.eventRequests", "eventReqest")
        .leftJoinAndSelect("eventReqest.requestedUser", "requestedUser")
        .where("event.deleted=0")
        .andWhere('event.datetime > :date', { date: new Date()})
        .orderBy("event.datetime", "DESC")
        .getMany();`

So i must add a select() method with the string:

`(6371 * acos(cos(radians( 52.490498333333335 )) * cos(radians( event.latitude )) * cos(radians( event.longitude ) - radians( 13.3498 )) + sin(radians( 52.490498333333335 )) * sin(radians( event.latitude )))`

But i not work. Can somebody provide a example how i can get all my result + distance?

**Comment by pleerock** [comment]
first try to build exactly same query you wrote in sql, without joins and everything else, then if it will not work for you, provide a code snippet of what you are doing and provide an error you have, including failing sql query

**Comment by pleerock** [comment]
Closing as no answer from reporter.
