### ISSUE TITLE
Raw Postgresql Update query result is always an empty array

### ISSUE THREAD

**Issue by barczaG** [typeorm/typeorm#1308]
The query result of a raw postgresql update should be `UPDATE n` where `n` is the number of rows but it always returns an empty array.

**Comment by barczaG** [comment]
@pleerock If you give me some hint I can start developing/fixing it myself.

**Comment by pleerock** [comment]
it will be implemented in `0.2.0` (`npm i typeorm@next`) , `next` branch. We already have an `UpdateResult` object returned by query builder which we can use and add `affectedRows` or something like that property into it. You can investigate and implement this feature on your own, this will be a very nice contribution

**Comment by kodayashi** [comment]
@pleerock - Is this something community needs to do? I see it was pulled from `0.2.0`.

**Comment by pleerock** [comment]
@kodayashi yes I marked this since it can be implemented by a community. 0.2.0 has a `UpdateResult` object we just need to populate needed info for each database after update operation.

**Comment by barczaG** [comment]
So the main issue here is that we return `result.rows` instead of `result` here: https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresQueryRunner.ts#L173
By returning the `result` object we could access the `rowCount` property - https://node-postgres.com/api/result#-code-result-rowcount-int-code- then which could be added to `UpdateResult` object

I ended up using a fork because wasn't sure If I would break something by changing the return value of the `query` function. 

I can fix it if you think it's safe to alter the return value

**Comment by pleerock** [comment]
Probably we'll need to refactor things a bit... We can create a `QueryResult` and let `query` method to return that, and make sure to update all query method usages. Then we can map QueryResult into UpdateResult and InsertResult where needed. This change should be in the `next` branch since its a breaking change.

**Comment by kodayashi** [comment]
@barczaG - Happy to test this out in `next` if you need.

**Comment by shaunc** [comment]
@pleerock - ... also DeleteResult (?)

**Comment by PachowStudios** [comment]
Any update on this?

**Comment by mkonicek** [comment]
Hi, just to double check - the fix for this hasn't landed, correct?

I'm using typeorm `0.2.16` and just did `console.log(updateResult)`.

I get an empty result:

```
UpdateResult { generatedMaps: [], raw: [] }
```

**Comment by saarw** [comment]
Using a fork with this fix/workaround, but the rows end up at position raw[1], I'm guessing a real fix would have an object with an affectedRows field?
https://github.com/saarw/typeorm/commit/7749a644f256a0d8ad13f9b8e2971c8cad46c0d5

**Comment by j6lim** [comment]
I made a pull request adding the 'affected' field in `UpdateResult`, and setting it in `UpdateQueryBuilder` to return the updated rows properly.

**Comment by vladimirmoushkov** [comment]
@j6lim link to the pull request?

To the maintainers - this is an essential feature, when is the pull request expected to be reviewed and eventually merged in a release?

**Comment by j6lim** [comment]
I love the elegant design of typeorm, but this issue is the deal breaker. We can’t use optimistic locking on a single row without this feature.
