### ISSUE TITLE
How to custom mongodb collection name when saving data?

### ISSUE THREAD

**Issue by sirius1024** [typeorm/typeorm#1309]
I've define this class in my typescript project.
```js
@Entity()
export class CronJob {
  @ObjectIdColumn() id: ObjectID;

  @Column() name: string;

  @Column() projectName: string;

  @Column() timeZone: string;

  @Column() cron: string;
}
```

And when I add data with **save()** method, the collection name show me "cron_job" in mongodb.
How can I custom a collection name with typeorm please? (mongo/typescript/express)

current version is: 
    "typeorm": "^0.1.7",
    "typescript": "^2.6.2"

**Comment by pleerock** [comment]
Did you try to set it in entity decorator?:

```ts
@Entity({ name: "CronJob" })
```

**Comment by sirius1024** [comment]
@pleerock Thank you so mush!
Any documents I can read for this? I checked docs in typeorm.io and nothing found. only options for column.

**Comment by pleerock** [comment]
don't forget to star a library ;)
