### ISSUE TITLE
in Tree entity, TreeChildren doesn't need to be of type Category[] ?

### ISSUE THREAD

**Issue by kaveh981** [typeorm/typeorm#1312]
in the example provided in doc:
https://github.com/typeorm/typeorm/blob/master/docs/tree-entities.md

@TreeChildren()
    children: Category;

children is of type Category
Doesn't need to be of type Category[] ?

**Comment by pleerock** [comment]
Correct, are you able to provide a PR?

**Comment by kaveh981** [comment]
Sure I'll do,
Thanks for the great job!
