### ISSUE TITLE
UpdateDateColumn default value on the database level

### ISSUE THREAD

**Issue by CocaColaBear** [typeorm/typeorm#1317]
Hi all, i have a problem with default value of **UpdateDateColumn** and **CreateDateColumn**.
TypeORM version: **0.2.0-alpha.10**
When entity created, or updated, TypeORM generate SQL with **CURRENT_TIMESTAMP** default value.
My base entity looks something like this:
```typescript
export default abstract class BaseEntity {
	@CreateDateColumn({
		default: () => "utcnow()",
		type: "timestamp"
	})
	public created: Date;

	@UpdateDateColumn({
		default: () => "utcnow()",
		type: "timestamp"
	})
	public updated: Date;
}
```

**Comment by pleerock** [comment]
try on latest `@next`, it should accept the default value you specify and let us know if it does not work for you.

**Comment by dukuo** [comment]
I'm trying this snippet in `^0.3.0-alpha.22` but it does not work. Any idea on how to auto-generate timestamps ?
