### ISSUE TITLE
TO JEST USERS: Do not use the "resetModules" option.

### ISSUE THREAD

**Issue by hmil** [typeorm/typeorm#1318]
I'll just leave this note here in the hope that it saves people time as well as their sanity.

### **typeorm is not compatible with jest's "resetModules" option. Turn it off!!!**

You might get this error for instance:
```
TypeError: this.connection.hasMetadata is not a function
```

### Why is it happening?

This is due to a couple things which, combined, break compatibility with resetModules.

1. Some classes are required at run-time (ie. not using `import` but rather using node's `require` function) [source](https://github.com/typeorm/typeorm/blob/a15dbfb7c22b5dd9bab47f5cf4a09ff350d03d97/src/query-builder/QueryBuilder.ts#L168)
2. The classes involved in this dynamic require game are compared with `instanceof` [source](https://github.com/typeorm/typeorm/blob/a15dbfb7c22b5dd9bab47f5cf4a09ff350d03d97/src/query-builder/QueryBuilder.ts#L84)

With `resetModules` enabled, the require cache is flushed. If you use `createConnection` in your code it will contain references to the old modules, but then new instances of those modules are created at run time because the `require` cache was flushed. You end up with conflicting versions of the `QueryBuilder` constructor which are not strictly equal and hence some `instanceof` check will start giving wrong results.

--- 

I just lost half a day figuring this one out. Hopefully this issue is visible enough that affected people will find it.

### To the package maintainers: Can this be avoided?
This bug might be avoidable by doing some lazy loading instead of loading a module **each** time it is needed.  Let me know if this looks reasonable to you.

example:
```typescript
const InsertQueryBuilderCls: null | typeof InsertQueryBuilder = null;

function getInsertQueryBuilder(): typeof InsertQueryBuilder {
  if (InsertQueryBuilderCls === null) {
    InsertQueryBuilderCls = require(...).InsertQueryBuilderCls;
  }
}
```

**Comment by pleerock** [comment]
try to provide a PR and let see how many places it affects

**Comment by hmil** [comment]
It seems to be limited to the QueryBuilder module only. However I don't know if what I suggested above would work.

I won't have time to tinker more on this. If someone else runs into this bug and really wants to use fancy black magic jest flags then they can go ahead and figure out a fix... or be careful as to how they use typeorm (the bug could be avoided by being cautious when importing typeorm stuff in the test file itself). This kind of oddities are to be expected when you start manipulating node's require cache.

I just wanted to leave a trace so people find a solution to this bug more easily.

**Comment by ekzyis** [comment]
Thank you for mentioning this!!! You most likely just spared me a lot of time debugging why this is happening!
