### ISSUE TITLE
queryBuilder parameters: duplicated parameters name

### ISSUE THREAD

**Issue by dvh312** [typeorm/typeorm#1322]
const tokens = s.split(' ');
        for (const token of tokens) {
          queryBuilder.andWhere(new Brackets(tokenQb => {
            tokenQb.where('person.name ILIKE :token');
            tokenQb.orWhere('person.lastName ILIKE :token');
          })).setParameters({token: token});
        }

When s = "foo bar", I should get the query ... WHERE (person.firstName ILIKE 'foo' OR person.lastName ILIKE 'foo') AND (person.firstName ILIKE 'bar' OR person.lastName ILIKE 'bar').

However, I got ... WHERE (person.firstName ILIKE 'bar' OR person.lastName ILIKE 'bar') AND (person.firstName ILIKE 'bar' OR person.lastName ILIKE 'bar') instead.

How can I achieve this?

**Comment by pleerock** [comment]
Parameters must be unique. The way you can change your code:

```ts
s.split(' ').forEach((token, index) => {
      const parameterName = "token" + index;
      queryBuilder.andWhere(new Brackets(tokenQb => {
        tokenQb.where('person.name ILIKE :' + parameterName);
        tokenQb.orWhere('person.lastName ILIKE :' + parameterName);
      })).setParameter(parameterName, token);
    });
```

**Comment by dvh312** [comment]
Thanks!

**Comment by pimplibence** [comment]
> Parameters must be unique. The way you can change your code:
> 
> ```ts
> s.split(' ').forEach((token, index) => {
>       const parameterName = "token" + index;
>       queryBuilder.andWhere(new Brackets(tokenQb => {
>         tokenQb.where('person.name ILIKE :' + parameterName);
>         tokenQb.orWhere('person.lastName ILIKE :' + parameterName);
>       })).setParameter(parameterName, token);
>     });
> ```

@pleerock why should be the parameters unique? Programatically the parameter naming belongs to the it own 'where' function scope. If you would like to use a huge parameter bag you have to use query level naming despite of function scope level.

**Comment by lovinu99** [comment]
for someone looking the way to combine conditions into your queryBuilder, u r right to come here ✌️ this answer saved my life 💯
