### ISSUE TITLE
Subquery question

### ISSUE THREAD

**Issue by kronodevcom** [typeorm/typeorm#1323]
Hi, I Like add a subquery to my current query, but I need pass a query field to the subquery parameter.

it's possible this?

_SQL Query Example:_
SELECT com.id, com.status, (select count(*) from public."Devices" dev where "companyId" = **com.id**) as deviceCount
FROM public."Companies" **com**;

_My current query:_
const list = await this.companyRepository.createQueryBuilder('company')
            .select('company.*')
            .orderBy('company.status', 'DESC')
            .addOrderBy('company.name', 'ASC').printSql().getRawMany();

_Entities:_
**@Entity('Companies')**
export class Company {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({ type: 'varchar', length: 200 })
    name: string;

    @Column({ type: 'smallint', default: 1, comment: '0-Disabled, 1-Active' })
    status: number;

@Entity('Devices')
export class Device {

    @PrimaryGeneratedColumn({ type: 'bigint' })
    id: number;

    @Column({ type: 'varchar', length: 200, nullable: false })
    name: string;

    @ManyToOne(type => Company, { eager: true })
    company: Company;

Thanks,
Andres

**Comment by pleerock** [comment]
Did you check [docs](http://typeorm.io/#/select-query-builder/using-subqueries) on sub queries?

**Comment by forvy** [comment]
Hi, I'm sorry for lifting up an old issue but is it possible to add an explanation of the SQL version for the subqueries? I believe many people having a tough time understanding query inside query for createquerybuilder.
