### ISSUE TITLE
Getting "missing FROM-clause entry for table" when trying find by relation id in postgres

### ISSUE THREAD

**Issue by satellink** [typeorm/typeorm#1324]
typeorm version: 
**0.1.7**

node.js version: 
**8.9.3**

operating system:
**OS X**

database:
**postgres 9.6**

I have a model defined like this:

```typescript
@Entity()
export default class TeamPlayer {

  @ManyToOne(type => Team, team => team.players, { nullable: false, primary: true })
  team: Team;

  @ManyToOne(type => User, user => user.teams, { nullable: false, primary: true })
  user: User;

  @Column("int")
  number: number;
}
```

Trying to fetch for TeamPlayer objects with teamId=5 on empty table:
```typescript
const count = await getRepository(TeamPlayer).findAndCount({where: { number: 5 }})
console.log(count)
```

Getting the following error (relevant part)
```
QueryFailedError: missing FROM-clause entry for table "teamplayer"
```

Full stacktrace and unit test that presents the issue can be found here: https://github.com/satellink/typeorm-find-example

Not really familiar with the framework to guess the issue, and am not even sure if this is how I am supposed to query for these. (This might be good to mention in tutorials)

However it is weird that while the table created in postgres is **team_player**, the error mentions table **teamplayer**.

**Comment by satellink** [comment]
Oh, noticed you have **typeorm@next**, and updating into that seems to solve the issue.

**Comment by pleerock** [comment]
I'll close this issue if its already fixed.
