### ISSUE TITLE
Wrong behavior w/ the same table names in different databases

### ISSUE THREAD

**Issue by jsmonkey** [typeorm/typeorm#1326]
Hi guys,

I got a problem if I have single connection to the `mysql` server and the same table names in different databases.

Example:

```
@Entity({ database: 'db_1' })
class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    user_from_db_2_id: number;
}
```
```
@Entity('user', { database: 'db_2' })
class SpecificUser {
    @PrimaryGeneratedColumn()
    userid: number;

    @Column()
    username: string;
}
```

Then If I use `@OrmRepository` for `SpecificUser` entity and  `findOne` method I got smth like this:

```
SELECT `SpecificUser`.`userid` AS `SpecificUser_userid`, `SpecificUser`.`username` AS `SpecificUser_username` FROM `db_1`.`user` `SpecificUser` WHERE `SpecificUser`.`username`=? [ 'somename' ]
```

I debugged the appand got the point which triggers the issue:
`typeorm\query-builder\QueryBuilder.js` method `getTableName`

In 319 line:
```
 var metadata = this.connection.hasMetadata(tableName) ? this.connection.getMetadata(tableName) : undefined;
```

`getMetadata` method uses `typeorm\connection\Connection.js` `findMetadata` which checks and compares only `target`, `name`, `tablePath` and `tableName` props of metadata and returns metadata for the first Entity with `User` classname instead of `SpecificUser`, cuz tablename for such entity was generated `user`, the same as for the second entity where it was configured.

After the fix I expect query like this:
```
SELECT `SpecificUser`.`userid` AS `SpecificUser_userid`, `SpecificUser`.`username` AS `SpecificUser_username` FROM `db_2`.`user`  WHERE `SpecificUser`.`username`=? [ 'somename' ]
```

Fix asap,
Thanks

**Comment by pleerock** [comment]
This bug is fixed and will be released in `0.1.8`

**Comment by jsmonkey** [comment]
Hi, thanks for such quick reply and fix.
When will release arrive?

Cuz I have one more [issue](https://github.com/typeorm/typeorm/issues/1333) due to the workaround with multiple connections of this one

Thanks

**Comment by pleerock** [comment]
I'll publish new version today or tomorrow

**Comment by pleerock** [comment]
published.

**Comment by jsmonkey** [comment]
Thanks a lot.
