### ISSUE TITLE
{ EntityMetadataNotFound: No metadata for "User" was found.

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#1327]
Hello,
I'm trying to setup a new project using the latest release and the ormconfig.yml options.

I'm following the documentation and pointing it to the `src/entity/*.js` location, but i keep getting the following error when running my server.spec.ts file through mocha:

```
{ EntityMetadataNotFound: No metadata for "User" was found.
    at EntityMetadataNotFound.Error (native)
    at new EntityMetadataNotFound (/Users/paco/projects/mezcal/server/src/error/EntityMetadataNotFound.ts:7:9)
    at Connection.getMetadata (/Users/paco/projects/mezcal/server/src/connection/Connection.ts:297:19)
    at EntityManager.<anonymous> (/Users/paco/projects/mezcal/server/src/entity-manager/EntityManager.ts:310:54)
    at step (/Users/paco/projects/mezcal/server/node_modules/typeorm/entity-manager/EntityManager.js:32:23)
    at Object.next (/Users/paco/projects/mezcal/server/node_modules/typeorm/entity-manager/EntityManager.js:13:53)
    at /Users/paco/projects/mezcal/server/node_modules/typeorm/entity-manager/EntityManager.js:7:71
    at __awaiter (/Users/paco/projects/mezcal/server/node_modules/typeorm/entity-manager/EntityManager.js:3:12)
    at /Users/paco/projects/mezcal/server/src/entity-manager/EntityManager.ts:280:39
  name: 'EntityMetadataNotFound',
  message: 'No metadata for "User" was found.' }
```

I've posted a sample repo here:
https://github.com/rightisleft/public-error
https://github.com/rightisleft/public-error/blob/master/server/test/server.spec.ts#L29

I've been reading the documentation at https://github.com/typeorm/typeorm/issues/420 but have been unable to resolve the problem.

Please advise. 

**Checklist:**
Using reflect-metadata in spec
Using "emitDecoratorMetadata": true, "experimentalDecorators": true in tsconfig.json
Using 'entries' delcaration in ormconfig.yml

**Comment by mindjuice** [comment]
Your code is gone now so not sure if this was your issue, but in my case my classes were not exported.  Adding `export` in front of them allows the metadata to be found.

**Comment by nidheeshdas** [comment]
In my case, I just had to "await" till the application creation was complete. I was previously using the service before `create()` application was complete.

**Comment by jelling** [comment]
@nidheeshdas can you explain what you mean by waiting for the application to complete?

**Comment by tenuki** [comment]
For the record, I've just ran into what I think was the same error (at least the exception is the same) and my problem was I was not specifying the model's entity classes in the create connection call! (check how it is done here: http://typeorm.io/#/entities/what-is-entity ).

**Comment by mlaopane** [comment]
In my case, I just needed to change this :

```javascript
entities: [
    __dirname + "/entity/*.js"
],
```

Into this :
```javascript
entities: [
    __dirname + "/entity/*.ts"
],
```

**Comment by Ventzy** [comment]
One more reason - I had loaded entities by ormconfig.json like so
```
    "entities": [
      "model/entities/**/*.ts"
    ],
```
and also imported Entity classes in app's code, in my custom repo normally
```
import { Product } from '../../entities/product/Product';
```
Not sure if it is related to the issue or not, but I also have default exports like
```
import { Product } from "./Product";

export default {
    'Product': Product,
}
```
At the end I got EntityMetadataNotFound: No metadata for "Product" was found. My debugging shown that Connection had loaded entity objects and containts Product class, however in Connection.findMetadata method loaded Product does not match with target parameter, even if both looks exactly the same and in fact are loaded from one and the same place. 
```
    protected findMetadata(target: Function|EntitySchema<any>|string): EntityMetadata|undefined {
        return this.entityMetadatas.find(metadata => {
            if (metadata.target === target)      <------------ does not match
```
Obliviously, they are copies and don't have the same identity.

Solution: removed ormconfig.json and loaded entities like so
```
        this.conn = await createConnection({
            ...
            entities: [Product]
        });
```

**Comment by pleerock** [comment]
another reason why I proposed changes in #2358

**Comment by armanfatahi** [comment]
> In my case, I just needed to change this :
> 
> ```js
> entities: [
>     __dirname + "/entity/*.js"
> ],
> ```
> 
> Into this :
> 
> ```js
> entities: [
>     __dirname + "/entity/*.ts"
> ],
> ```

I changed from .ts to .js to fix this issue:

(function (exports, require, module, __filename, __dirname) { import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

**Comment by cjfigueiras** [comment]
> > In my case, I just needed to change this :
> > ```js
> > entities: [
> >     __dirname + "/entity/*.js"
> > ],
> > ```
> > 
> > 
> > Into this :
> > ```js
> > entities: [
> >     __dirname + "/entity/*.ts"
> > ],
> > ```
> 
> I changed from .ts to .js to fix this issue:
> 
> (function (exports, require, module, __filename, __dirname) { import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

same problem here, how you fix?

**Comment by tenuki** [comment]
In my case, I've workarounded it by giving the connect function the actual entities, like this:

     import {User } from ".../user.ts";
     ..
     entities: [ User, ..],
     ..

Hope this helps.

**Comment by cjfigueiras** [comment]
@tenuki thanks for respond, I try some similar, I have this class for manage connection

```
import { injectable } from 'inversify';
import { Connection, ConnectionManager, getConnectionOptions, createConnection, getConnectionManager, ConnectionOptions } from 'typeorm'
import { SnakeNamingStrategy } from 'typeorm-naming-strategies'
import 'reflect-metadata'
import { User } from '../src/entity/User';

/**
 * Database manager class
 */
@injectable()
export class Database {
    private connectionManager: ConnectionManager

    constructor() {
        this.connectionManager = getConnectionManager()
    }

    public async getConnection(): Promise<Connection> {
        const CONNECTION_NAME = `default`

        let connection: Connection

        if (this.connectionManager.has(CONNECTION_NAME)) {
            connection = await this.connectionManager.get(CONNECTION_NAME)

            if (!connection.isConnected) {
                console.log('reconnect');
                connection = await connection.connect()
            }
        }
        else {

            const connectionOptions = await getConnectionOptions(); // default connection options in ormconfig.json
            
            Object.assign(connectionOptions, { 
                 namingStrategy: new SnakeNamingStrategy(), 
                 entities: [User, ...]
            });
            
            connection = await createConnection(connectionOptions)
        }

        return connection
    }
}
```

In this way, error dissapear when I request first time, that is when I create connection, but when I request again and I get connection created previously error show again, is like get entities from ormconfig.json again

**Comment by armanfatahi** [comment]
In my case, I was saving an instance of User, which was "user = new User()" but instead of passing user to "connection.manager.save(user);" I was passing the entity itself "connection.manager.save(User);".

**Comment by oscar-corredor** [comment]
In my case, I was passing a wrong path to the ormconfig.json file, once corrected the path it worked properly.

**Comment by Rina2001** [comment]
HI i have the issue too, please help.

**Comment by phvictorino** [comment]
i change the path of entities from dynamic:
`import { User } from "../src/entitys/user.entity";`

to static: 
`import { User } from "src/entitys/user.entity";`

it worked for me

**Comment by gauravsaluja2006** [comment]
I had to change

`entities: [__dirname + '/**/*.entity.ts'],`

to

`entities: [__dirname + '/**/*.entity.{js,ts}'],`

**Comment by kateile** [comment]
My problem was fixed by just renaming file from **user** to **User**, I don't understand why this was causing problem.

**Comment by volkerchartier** [comment]
> In my case, I just needed to change this :
> 
> ```js
> entities: [
>     __dirname + "/entity/*.js"
> ],
> ```
> 
> Into this :
> 
> ```js
> entities: [
>     __dirname + "/entity/*.ts"
> ],
> ```
turn it into 
[__dirname + '/../**/*.entity.{js,ts}'],

**Comment by natasha-robarge** [comment]
In my case, I had to change:

`['/entity/*.ts']`
to
`['./entity/*.ts']`

**Comment by mohsanabbas** [comment]
entities: [__dirname + '/../**/*.entity.{js,ts}']

**Comment by Shivank-Dev** [comment]
> [__dirname + '/../**/*.entity.{js,ts}']

life saver XD

**Comment by LuisTejeda99** [comment]
Make sure that your class's decorators has '@' at the beginning haha... It appers joke but it's an anecdote ✌️

**Comment by kaniaalterra** [comment]
> `entities: [__dirname + '/../**/*.entity.{js,ts}']`

in my case doesn't work

i have to do this
`import { join} from "path";

...
entities:[join(__dirname,'../**/*.entity.{ts,js}')]
`

**Comment by khushbooY** [comment]
In my case replace this 
entities:[__dirname+'/../**/*.entity.ts']
into entities: [__dirname + '/../**/*.entity.{js,ts}'], in config.ts

**Comment by nirajkvinit** [comment]
> I had to change
> 
> `entities: [__dirname + '/**/*.entity.ts'],`
> 
> to
> 
> `entities: [__dirname + '/**/*.entity.{js,ts}'],`

Strangely, it worked

**Comment by Tequelequeteque** [comment]
I have same problem, someone can help ?
I can using Entity but repository doesn't work =(
dbConfig
```JS
import 'dotenv/config';
import 'reflect-metadata';
import { resolve } from 'path';
import { PostgresConnectionOptions } from 'typeorm/driver/postgres/PostgresConnectionOptions';

interface IENV{
  [key:string]: any,
}

const {
  DB_TYPE,
  DB_PORT,
  DB_USER,
  DB_PASS,
  DB_NAME,
} = process.env as unknown as IENV;

const entitiesPath = resolve(__dirname, '..', 'entities');
const migrationsPath = resolve(__dirname, 'migrations');

// behavior diferent
const entitiesCliPath = entitiesPath.split('/').slice(-2).join('/');

const dbConfig = {
  name: 'default',
  type: DB_TYPE,
  host: '0.0.0.0',
  port: DB_PORT,
  username: DB_USER,
  password: DB_PASS,
  database: DB_NAME,
  migrationsRun: true,
  entities: [entitiesPath.concat('/**/*{t,j}s')],
  migrations: [migrationsPath.concat('/**/*{t,j}s')],
  cli: {
    entitiesDir: entitiesCliPath,
    migrationsDir: migrationsPath,
  },
  dropSchema: true,
  logging: true,
} as PostgresConnectionOptions;

export { dbConfig };
```
entity
```JS 
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  BaseEntity,
} from 'typeorm';

@Entity('users')
class User extends BaseEntity {
    @PrimaryGeneratedColumn('uuid')
    id?: string;

    @Column({ name: 'email', type: 'varchar' })
    email!:string;

    @Column({ name: 'name', type: 'varchar' })
    name!:string;

    @Column({ name: 'password', type: 'varchar' })
    password!:string;

    @CreateDateColumn({ name: 'created_at', default: new Date() })
    createdAt?: Date;

    @UpdateDateColumn({ name: 'updated_at', default: new Date() })
    updatedAt?: Date;
}

export { User };
```
repository
```JS
import {
  EntityRepository, Repository, getCustomRepository,
} from 'typeorm';
import { IUsers } from './users.interface.repository';
import { User } from '../../entities/user.entity';

@EntityRepository(User)
class UserRepository extends Repository<User> implements IUsers {
  findByEmail(email:string) {
    return this.findOne({ where: { email } });
  }
}

const userRepository = getCustomRepository(UserRepository);
export { userRepository };
```

**Comment by brianpooe** [comment]
> In my case, I've workarounded it by giving the connect function the actual entities, like this:
> 
> ```
>  import {User } from ".../user.ts";
>  ..
>  entities: [ User, ..],
>  ..
> ```
> 
> Hope this helps.

This helped me with a nestjs and aws serveless.

**Comment by kasec** [comment]
> I have same problem, someone can help ?
> I can using Entity but repository doesn't work =(
> dbConfig
> 
> ```js
> import 'dotenv/config';
> import 'reflect-metadata';
> import { resolve } from 'path';
> import { PostgresConnectionOptions } from 'typeorm/driver/postgres/PostgresConnectionOptions';
> 
> interface IENV{
>   [key:string]: any,
> }
> 
> const {
>   DB_TYPE,
>   DB_PORT,
>   DB_USER,
>   DB_PASS,
>   DB_NAME,
> } = process.env as unknown as IENV;
> 
> const entitiesPath = resolve(__dirname, '..', 'entities');
> const migrationsPath = resolve(__dirname, 'migrations');
> 
> // behavior diferent
> const entitiesCliPath = entitiesPath.split('/').slice(-2).join('/');
> 
> const dbConfig = {
>   name: 'default',
>   type: DB_TYPE,
>   host: '0.0.0.0',
>   port: DB_PORT,
>   username: DB_USER,
>   password: DB_PASS,
>   database: DB_NAME,
>   migrationsRun: true,
>   entities: [entitiesPath.concat('/**/*{t,j}s')],
>   migrations: [migrationsPath.concat('/**/*{t,j}s')],
>   cli: {
>     entitiesDir: entitiesCliPath,
>     migrationsDir: migrationsPath,
>   },
>   dropSchema: true,
>   logging: true,
> } as PostgresConnectionOptions;
> 
> export { dbConfig };
> ```
> 
> entity
> 
> ```js
> import {
>   Entity,
>   PrimaryGeneratedColumn,
>   Column,
>   CreateDateColumn,
>   UpdateDateColumn,
>   BaseEntity,
> } from 'typeorm';
> 
> @Entity('users')
> class User extends BaseEntity {
>     @PrimaryGeneratedColumn('uuid')
>     id?: string;
> 
>     @Column({ name: 'email', type: 'varchar' })
>     email!:string;
> 
>     @Column({ name: 'name', type: 'varchar' })
>     name!:string;
> 
>     @Column({ name: 'password', type: 'varchar' })
>     password!:string;
> 
>     @CreateDateColumn({ name: 'created_at', default: new Date() })
>     createdAt?: Date;
> 
>     @UpdateDateColumn({ name: 'updated_at', default: new Date() })
>     updatedAt?: Date;
> }
> 
> export { User };
> ```
> 
> repository
> 
> ```js
> import {
>   EntityRepository, Repository, getCustomRepository,
> } from 'typeorm';
> import { IUsers } from './users.interface.repository';
> import { User } from '../../entities/user.entity';
> 
> @EntityRepository(User)
> class UserRepository extends Repository<User> implements IUsers {
>   findByEmail(email:string) {
>     return this.findOne({ where: { email } });
>   }
> }
> 
> const userRepository = getCustomRepository(UserRepository);
> export { userRepository };
> ```
> 
> service with error
> 
> ```js
> import { connection } from '../../database/db.connection';
> import { User } from '../../entities/user.entity';
> import { ICreateUserDTO } from './user.validators';
> import { userRepository } from '../../repositories/users/users.repository';
> 
> export class CreateUserService {
>   async execute(createUserRequest:ICreateUserDTO):Promise<User> {
>     userRepository.create(); // error actions
>     const repo = connection.manager.getRepository(User);
>     const user = repo.create(createUserRequest as User);
>     return repo.save(user);
>   }
> }
> 
> const createUserService = new CreateUserService();
> 
> export { createUserService };
> ```
> 
> error output
> 
> ```js
> [INFO] 09:44:05 Restarting: /Users/user/Desktop/eworld_6d/src/useActions/users/user.services.ts has been modified
> EntityMetadataNotFound: No metadata for "User" was found.
>     at new EntityMetadataNotFoundError (/Users/user/Desktop/eworld_6d/src/error/EntityMetadataNotFoundError.ts:9:9)
>     at Connection.getMetadata (/Users/user/Desktop/eworld_6d/src/connection/Connection.ts:333:19)
>     at EntityManager.getCustomRepository (/Users/user/Desktop/eworld_6d/src/entity-manager/EntityManager.ts:1244:86)
>     at Connection.getCustomRepository (/Users/user/Desktop/eworld_6d/src/connection/Connection.ts:368:29)
>     at Object.getCustomRepository (/Users/user/Desktop/eworld_6d/src/index.ts:301:55)
>     at Object.<anonymous> (/Users/user/Desktop/eworld_6d/src/repositories/users/users.repository.ts:14:24)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Module._compile (/Users/user/Desktop/eworld_6d/node_modules/source-map-support/source-map-support.js:547:25)
>     at Module.m._compile (/private/var/folders/q2/6bl4p3qx7vbdwl0bl0nv74840000gn/T/ts-node-dev-hook-05985270979107882.js:57:33)
>     at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> [ERROR] 09:44:10 EntityMetadataNotFound: No metadata for "User" was found.
> ```

I had the some problem in my controller similar to your service, I add a connection instance and use this object to get my custom repo.

```ts
import * as express from 'express'
import { BaseController } from '../../../core/BaseController'
import { Connection } from "typeorm";
import db from '../../persistence/connection'

import { UserRepo, IUserRepo } from '../../../domain/repository/user-repo';
import { Result } from '../../../core/Result';
import { User } from '../../../domain/entity/user'
import { UserMap } from '../../../domain/map/user-map'

class CreateUserController extends BaseController {
  private userRepo: IUserRepo;

  constructor(userRepo: IUserRepo) {
    super();
    this.userRepo = userRepo;
  }

  protected async executeImpl(req: express.Request, res: express.Response): Promise<void | any> {
    try {
      console.log('Create User');
      
      const dataTransferObject = UserMap.toPersistence(req.body);

      const userOrError: Result<User> = await User.create(dataTransferObject);
      
      if (userOrError.isFailure) {
        // Send back a 400 client error
        return this.clientError(res, userOrError.error);
      }

      const user: User = userOrError.getValue();

      // Create the user
      const rawData = await this.userRepo.save(user);

      // Return a 200
      return this.ok<any>(res, rawData);

    } catch (err) {
      return this.fail(res, err.toString())
    }
  }
}

let createUserController: CreateUserController

(async function() {
  const connection: Connection = await db as Connection
  let userRepo = connection.getCustomRepository(UserRepo)
  createUserController = new CreateUserController(userRepo);
})()


  

export {
  createUserController
}
```

**Comment by akashlama1998** [comment]
In [NestJS](https://docs.nestjs.com/) adding `.js` along side `.ts` worked for me

`typeorm.config.ts`

Before

```
import { TypeOrmModuleOptions } from '@nestjs/typeorm';

export const TypeORMConfig: TypeOrmModuleOptions = {
  type: 'postgres',
  url: process.env.DATABASE_URL,
  synchronize: true,
  entities: [__dirname + '/../**/*.entity.ts'],
  migrationsTableName: 'Migrations_History',
};
```

After

```

import { TypeOrmModuleOptions } from '@nestjs/typeorm';

export const TypeORMConfig: TypeOrmModuleOptions = {
  type: 'postgres',
  url: process.env.DATABASE_URL,
  synchronize: true,
  entities: [__dirname + '/../**/*.entity{.ts,.js}'],
  migrationsTableName: 'Migrations_History',
};
```

**Comment by Abhishekbharti** [comment]
> I had to change
> 
> `entities: [__dirname + '/**/*.entity.ts'],`
> 
> to
> 
> `entities: [__dirname + '/**/*.entity.{js,ts}'],`

This worked for me

**Comment by KimleangSama** [comment]
In my case, I just remove it and add autoLoadEntities: true.
Note: I use in NestJS.

**Comment by nicholasscabral** [comment]
I got this err message, but i solved in a different way, it could also happen when you already have a table called "users" for example, and your model User is not with the same columns and configs as your table, in my case my table had a column called posts with a default value, and my model hadn't that default value set up, so before you check the entities directory on the ormconfig.json i highly recommend you check if your models are with the same properties and configs as your database table

**Comment by luisgurmendezMLabs** [comment]
I had this error using `ts-node` to run a quick thing, and was using node version 14~. I use `nvm` to switch to node version 12 and the error was fixed 🤷🏼‍♂️

**Comment by wsdt** [comment]
For me the string path `entities: ['dist/entity/**/*.entity.js'],` works in production code, but for the integration tests this and all above solutions fail. I always need to define the entities explictly by adding them one by one. 

This can't be the solution as that's not scalable, you always need to manually add the entities. Did anyone have the same problem for integration tests only?

**Comment by AmanDeqode** [comment]
`EntityMetadataNotFoundError: No metadata for "Users" was found` while working with **serverless and nestjs typeorm**
I have tried almost every approach as mentioned But nothing worked for me

**Comment by AliAj95** [comment]
Hi @AmanDeqode 
did you find any solution for your problem because I'm facing the same issue on my project?

**Comment by AmanDeqode** [comment]
Hello @AliAj95 
yes just add `--allowCache` flag 
`sls offline --allowCache start`
It works for me

**Comment by pr7prashant** [comment]
Make sure you have established a connection with the database before using the entities. In my case, I was using the `AppDataSource` before it was initialized. Here is how I fixed it:

```
import "reflect-metadata";
import { DataSource } from "typeorm";
import { Season } from "src/models/Season";

const AppDataSource = new DataSource({
  type: "postgres",
  host: "localhost",
  port: 5432,
  username: "postgres",
  password: "postgres",
  database: "test-db",
  synchronize: false,
  logging: false,
  entities: [Season],
  migrations: [],
  subscribers: [],
});

AppDataSource.initialize()
  .then(async () => {
    console.log("Connection initialized with database...");
  })
  .catch((error) => console.log(error));

export const getDataSource = (delay = 3000): Promise<DataSource> => {
  if (AppDataSource.isInitialized) return Promise.resolve(AppDataSource);

  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (AppDataSource.isInitialized) resolve(AppDataSource);
      else reject("Failed to create connection with database");
    }, delay);
  });
};
```

And in your services where you want to use the DataSource:
```
import { getDataSource } from "src/config/data-source";
import { Season } from "src/models/Season";

const init = async (event) => {
  const AppDataSource = await getDataSource();
  const seasonRepo = AppDataSource.getRepository(Season);
  // Your business logic
};
```

You can also extend my function to add retry logic if required :)

**Comment by pr7prashant** [comment]
> ```
> import { DataSource } from "typeorm";
> import { Exercise } from "./entities/Exercise";
> import "reflect-metadata";
> async function connect() {
>     await AppDataSource.initialize()
>         .then(() => {
>             console.log("Data Source has been initialized");
>             asyncDBTest();
>         })
>         .catch(() => console.error("Error during data source init."));
> }
> const AppDataSource = new DataSource({
>     type: "expo",
>     database: "GymTracker",
>     driver: require("expo-sqlite"),
>     entities: ["entities/*.{tsx,js}"],
>     migrations: ["migrations/preloadData.sql"]
> });
> 
> async function asyncDBTest() {
>     console.log("entered asynDBTest");
>     await AppDataSource.runMigrations()
>         .then(() => extractText())
>         .catch((err) => console.log(err));
> }
> 
> async function extractText() {
>     console.log("entered extractText");
>     const exercise = await AppDataSource
>         .getRepository(Exercise)
>         .createQueryBuilder("exercise")
>         .where("exercise.id = :id", { id: 1 })
>         .getOne()
>         .then(() =>
>             console.log(exercise.name)
>         );
> 
> }
> 
> export { AppDataSource, connect };
> ```
> 
> I thought I have established a connection before doing `runMigrations()` but I still have `EntityMetaDataNotFoundError`.
> 
> I also though this is something to do with `babel-plugin-transform-typescript-metadata` and [this stackoverflow question](https://stackoverflow.com/questions/53015862/metadata-retention-with-typescript-babel-7-decorators) but they did not seem to work

You need to import `reflect-metadata` before you import `entities`.

**Comment by themissingCRAM** [comment]
> 
> You need to import `reflect-metadata` before you import `entities`.

I just did this but the error still persist but thanks for the suggestion.

**Comment by mp54214** [comment]
> In my case, I just remove it and add autoLoadEntities: true. Note: I use in NestJS.

In NestJs on production, this was the only way to solve the issue.  

 In my case the string path has been all the time: 
     entities: ['dist/**/*.entity.{ts,js}'],
And this works both locally and in production.

**Comment by HucklJS** [comment]
In my case I just forgot to add 'Entity' decorator before class with entity :expressionless:
```
@Entity()
export class User {
...
}
```

**Comment by CaCaBlocker** [comment]
> For me the string path `entities: ['dist/entity/**/*.entity.js'],` works in production code, but for the integration tests this and all above solutions fail. I always need to define the entities explictly by adding them one by one.
> 
> This can't be the solution as that's not scalable, you always need to manually add the entities. Did anyone have the same problem for integration tests only?

I also got this same issue. Is there any fulfilled solution for both development and production? 🤔

**Comment by qq2250526295** [comment]
db password correct  or can connect

**Comment by Merdin** [comment]
In my project, I created:
```
@Entity()
export class User { }
```

But that `@Entity` decorator didn't import the correct way or something. So what I did:
1. Removed the `@Entity` decorator
2. Made sure my cursor was in front of 'export'
3. Did a back space and enter
4. Went one line up
5. Added the decorator again.
6. It worked!

**Comment by Gabriel-Aquino** [comment]
I had the same issue. Solved adding:
 await dataSource.initialize(); 

it was added on my index.ts file and I'm using "typeorm": "^0.3.7"

**Comment by Abid-08** [comment]
I had the same error which I resolved by adding autoLoadEntities: true in TypeOrmModule.forRoot() in the imports section in app.module.ts file

**Comment by ullalaaron** [comment]
The only configuration that works for me for NestJS + TypeOrm v 0.3.11

```
const typeOrmConfig: TypeOrmModuleOptions = {
  type: 'postgres',
  host: process.env.DB_HOST,
  port: parseInt(process.env.DB_PORT, 10),
  name: process.env.DB_NAME,
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  migrations: ['dist/migrations/*.{ts,js}', 'src/migrations/*.{ts,js}'],
  entities: ['dist/entities/*.entity.{ts,js}', 'src/entities/*.entity.{ts,js}'],
  synchronize: true,
  migrationsRun: true,
  logging: true,
  autoLoadEntities: true,
};
```

**Comment by bangsyir** [comment]
> I had the same issue. Solved adding: await dataSource.initialize();
> 
> it was added on my index.ts file and I'm using "typeorm": "^0.3.7"

you save my day, just add "await"

**Comment by leanCoder2128** [comment]
In my case I missed to add the Entity name dataSource. Here is the example

```
const Entities = [NewCustomer, NewKarat];

export const appSource = new DataSource({
  type: "mssql",
  host: process.env.DB_SERVER_HOST,
  port:  parseInt(process.env.DB_PORT as string),
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  entities: Entities,
  synchronize: true,
  logging: false,
  options: {
cryptoCredentialsDetails:{
  minVersion: "TLSv1"
}
  },
  extra: {
    trustServerCertificate: true
    
  }
});
```


Refer : https://typeorm.io/entities#what-is-entity

**Comment by i-sarokin-madkhol** [comment]
It can be very very stupid mistake....

Check also if you have initialised the DS.

```typescript
 await AppDataSource.initialize()
        .then(() => {
            console.log("Data Source has been initialized");
        })
        .catch(() => console.error("Error during data source init."));
```

**Comment by dtgcsl** [comment]
https://github.com/typeorm/typeorm/issues/9766 same Issue and explain in there because of typeOrm 0.3.12 Downgrade to 0.3.11 fix this bug for windown

**Comment by fabio-barboza** [comment]
Running the Express application with the datasource bellow everything works fine:

```
export const appDataSource = new DataSource({
  type: 'postgres',
  host: 'localhost',
  port: 5432,
  username: 'postgres',
  password: 'postgres',
  database: 'js_ecommerce',
  synchronize: false,
  logging: true,
  entities: [User],
  migrations: [],
  subscribers: []
})
```
But when I try to run the unit tests using jest with the data source bellow I get the error : EntityMetadataNotFoundError: No metadata for "User" was found.
```
let dataSource = new DataSource({
  type: 'better-sqlite3',
  database: ':memory:',
  dropSchema: true,
  entities: [User],
  synchronize: true,
  logging: true,
  migrations: [path.join(__dirname, '../migration/*.ts')],
  migrationsRun: true,
  subscribers: []
})
```
Can someone please help me?

**Comment by Pawel-Dlugosz** [comment]
In my case, it was not adding the `UserRepository` to the list of `providers` in `Module`
```ts
@Module({
  imports: [TypeOrmModule.forFeature([UserRepository])],
  controllers: [AuthController],
  providers: [AuthService, UserRepository],
})
export class AuthModule {}
```

**Comment by jhhtaylor** [comment]
In my case,
I was writing this (incorrect):
`entities: [join(__dirname), "./entities/*.*"],`
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀^^^
When it should be this (correct):
`entities: [join(__dirname, "./entities/*.*")],`
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀^^^

i.e. the right parenthesis was in the wrong place.

**Comment by VladimirFilipovic** [comment]
In my case i didn't register entity in module
@Module({

  imports: [TypeOrmModule.forFeature([User])],
                                                                    ^^^here
  controllers: [AuthController],
  providers: [AuthService, UserRepository],
})
export class AuthModule {}

**Comment by mauriciocrecencio** [comment]
In my case I was having this trouble 'No metadata for "x"...' when running tests.

So my solution is: `beforeEach(done => setTimeout(done, 500));`

**Comment by Godinson1** [comment]
> In my case I was having this trouble 'No metadata for "x"...' when running tests.
> 
> So my solution is: `beforeEach(done => setTimeout(done, 500));`

Please can you elaborate on this solution. Have same trouble when running tests also.

**Comment by sergeyjsg** [comment]
> It can be very very stupid mistake....
> 
> Check also if you have initialised the DS.
> 
> ```ts
>  await AppDataSource.initialize()
>     .then(() => {
>         console.log("Data Source has been initialized");
>     })
>     .catch(() => console.error("Error during data source init."));
> ```

This helped to me as well. I was running into this issue when tried to create a lambda function. After seeing this comment realized that I initialized the DB provider in the express app, but never in the lambda function. Basically adding `await dataSource.initialize();` in the beginning of the lambda solved this issue.

**Comment by alexander-dobrin** [comment]
> Running the Express application with the datasource bellow everything works fine:
> 
> ```
> export const appDataSource = new DataSource({
>   type: 'postgres',
>   host: 'localhost',
>   port: 5432,
>   username: 'postgres',
>   password: 'postgres',
>   database: 'js_ecommerce',
>   synchronize: false,
>   logging: true,
>   entities: [User],
>   migrations: [],
>   subscribers: []
> })
> ```
> 
> But when I try to run the unit tests using jest with the data source bellow I get the error : EntityMetadataNotFoundError: No metadata for "User" was found.
> 
> ```
> let dataSource = new DataSource({
>   type: 'better-sqlite3',
>   database: ':memory:',
>   dropSchema: true,
>   entities: [User],
>   synchronize: true,
>   logging: true,
>   migrations: [path.join(__dirname, '../migration/*.ts')],
>   migrationsRun: true,
>   subscribers: []
> })
> ```
> 
> Can someone please help me?

Did you find the solution?

**Comment by Alan-Graton** [comment]
> > In my case, I've workarounded it by giving the connect function the actual entities, like this:
> > ```
> >  import {User } from ".../user.ts";
> >  ..
> >  entities: [ User, ..],
> >  ..
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this helps.
> 
> This helped me with a nestjs and aws serveless application.

This was slowing down my application. By using: `entities: [__dirname + "/**/*.entity.{js,ts}"],` worked and was wayyy faster

**Comment by maisnamraju** [comment]
@Alan-Graton your tricked saved me a lot of misery

**Comment by hiaggomaciel** [comment]
I had similar error, but i my case i have two databases like that

data-source.ts
`import { TypeOrmModuleOptions } from '@nestjs/typeorm';
import { usn } from 'src/usn/entity/usn.entity';
import { a_client } from './client/entity/client.entity';
import { a_usuari } from './user/entity/user.entity';

export function dbReady(): TypeOrmModuleOptions  {
    return {
        type: 'postgres',
        host: process.env.DB_HOST,
        port: Number(process.env.DB_PORT),
        username: process.env.DB_USERNAME,
        password: String(process.env.DB_PASSWORD),
        database: process.env.DB_DATABASE_READY,
        entities: [a_usuari, a_client],
        synchronize: false
    }
};

export function dbInvoicing(): TypeOrmModuleOptions  {
    return {
        autoLoadEntities: false,
        type: 'postgres',
        host: process.env.DB_HOST,
        port: Number(process.env.DB_PORT),
        username: process.env.DB_USERNAME,
        password: String(process.env.DB_PASSWORD),
        database: process.env.DB_DATABASE_INVOICING,
        entities: [usn],
        synchronize: process.env.ENV === "development",
        migrationsRun: true,
    }
};`

app.module.ts

`import { Module, forwardRef } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { AuthModule } from './auth/auth.module';
import { ClientModule } from './client/client.module';
import { dbInvoicing, dbReady } from './data-source';
import { UserModule } from './user/user.module';
import { UsnModule } from './usn/usn.module';

@Module({
  imports: [
    forwardRef(() => UserModule),
    forwardRef(() => AuthModule),
    forwardRef(() => ClientModule),
    forwardRef(() => UsnModule),
    ConfigModule.forRoot({
      envFilePath: '.env',
    }),
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: dbReady
    }),
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: dbInvoicing
    })
  ],
  controllers: [AppController],
  providers: [AppService],
  exports: [AppService]
})

export class AppModule {}`


the first database works fine, i can use with no problem, but the second i make the migrations and apply them but when i try make a post in USN object not works and i had this error

![Captura de tela 2024-03-25 165612](https://github.com/typeorm/typeorm/assets/101148286/31590305-ca58-4f74-89e5-61c346052850)

some one help me.

**Comment by oracis** [comment]
`import 'reflect-metadata';
import { DataSource } from 'typeorm';
import { Users, UserAuths } from './entity/';

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: process.env.DATABASE_HOST!,
  port: parseInt(process.env.DATABASE_PORT!) || 3306,
  username: process.env.DATABASE_USERNAME!,
  password: process.env.DATABASE_PASSWORD!,
  database: process.env.DATABASE_NAME!,
  entities: [Users, UserAuths],
  synchronize: false,
  logging: true,
});

await (async function init() {
  try {
    await AppDataSource.initialize();
    console.log('Db initialized');
  } catch (error) {
    console.log(error);
  }
})();`
