### ISSUE TITLE
Where value IN

### ISSUE THREAD

**Issue by szkumorowski** [typeorm/typeorm#1329]
How is possible to use values different than primary keys with IN clause ?

`const values= [1,2,3];

repository.createQueryBuilder("entity")
.andWhere(() => "entity.otherField IN (:values)", {values})`

**Comment by pleerock** [comment]
it is possible, it does not matter if your column is primary or not

**Comment by szkumorowski** [comment]
Ok I was not clear with above.

`.andWhere(() => "entity.otherField IN (:values)", {values})`
Simply doesn't work - :values is not resolved and throw syntax error.

There is `.andWhereInIds` but it simply doesn't work with other fields (no primary) and there is no clear information how it should be used. As I don't see this in documentation.
http://typeorm.io/#/select-query-builder/adding-where-expression

Could you provide example how to use `where field IN (values)` query with queryBuilder where `field` is not primary key ?

**Comment by pleerock** [comment]
`andWhereInIds` is used only for primary keys, its purpose to be used with them and its used mostly internally that's why there is no docs for it.


```sql
.andWhere("entity.otherField IN (:values)", {values})
```

Is correct way of using this functionality and it MUST work. What database are you using? Can you create a PR with a failing test so I can quickly debug and fix if there is an issue?

**Comment by szkumorowski** [comment]
Yes you're right - works totally correctly, syntax error comes from different place and I didn't realize this because somehow `:values` was not resolved.
Sorry.

**Comment by twilroad** [comment]
after upgrade to version 0.2.*, these codes no longer work?

**Comment by pleerock** [comment]
in 0.2.0 syntax is `"entity.otherField IN (:...values)"`

**Comment by binki** [comment]
Would be nice if this were in the docs.

**Comment by danipralea** [comment]
I actually got it working with 
```typescript
.where("patient.id IN (:...ids)", {ids: connectedUsersIds})
```

**Comment by endurance** [comment]
PR for adding to docs

https://github.com/typeorm/typeorm/pull/5440

**Comment by rubiin** [comment]
how to do this with mssql query
