### ISSUE TITLE
Expose column names (for batch processing from CSVs, for example)

### ISSUE THREAD

**Issue by maxcan** [typeorm/typeorm#133]
I'm trying to batch upload from a CSV that doesn't have column titles.  I can verify that the columns are in the correct order so the best solution I've come up with is to create an object for each item in the array and pass it to `repo.create()`.  However, this requires knowing the fields for each object.  If they don't have default values, there isn't really a good way to find out the fields.  This was the best that I came up with, but note that it requires violating the types to use what's essentially a private API.  

```typescript
async function parseCsvEntities<T>(rawData: string, repo: Repository<T>): Promise<Array<T>> {
    return new Promise<Array<T>>((resolve, reject) => {
        parse(rawData, { auto_parse: true }, (csvErr: any, csvData: any) => {
            if (csvErr) { return reject(csvErr) }
            if (csvData.length === 0) { return reject("No CSV Data") }
            resolve(_.map(csvData as Array<Array<any>>, (entry) => entityFromArray(entry, repo)))
        })
    })
}

function entityFromArray<T>(vals: Array<any>, repo: Repository<T>):T {
    let propNames = _.map((repo as any).metadata._columns,"propertyName")
    let obj = _.zipObject(propNames, vals)
    return repo.create(obj)
}
```

**Comment by maxcan** [comment]
Sorry..  should have been more clear.  This is the problematic line:
```
let propNames = _.map((repo as any).metadata._columns,"propertyName")
```

**Comment by pleerock** [comment]
You can get `EntityMetadata` using connection:

`typescript
const entityMetadata = connection.getMetadata(Entity);
const columns = entityMetadata.columns;
const columnPropertyNames = columns.map(column => column.propertyName);
```

This all valid type-safe code.

**Comment by maxcan** [comment]
Perfect.  Thanks!
