### ISSUE TITLE
tstzrange

### ISSUE THREAD

**Issue by jamiewinder** [typeorm/typeorm#1330]
I have a PostgreSQL column using the 'tstzrange' type. If I specify this in typeorm:

```
@Column("tstzrange")
public interval: any;
```
Then I get an warning:

`DataTypeNotSupportedError: Data type "tstzrange" in "MyModel.interval" is
not supported by "postgres" database.`

The value I get back is also a string. Incidentally if I change the column type to `text`, the warning goes away and I get the normal postgres representation of the range as a string. This the only working around I have (and have to do this for custom types I've created in Postgres too). Is there a better way?

**Comment by pleerock** [comment]
We'll investigate adding this data type to the list of the supported database types in 0.2.0. Feel free to contribute if you want to get it earlier.

**Comment by AlexMesser** [comment]
All Postgres range types now supported from  `typeorm@0.2.0-alpha.28`. You can try it via `npm i typeorm@next`.
