### ISSUE TITLE
typeorm with pure SQL output

### ISSUE THREAD

**Issue by calebeaires** [typeorm/typeorm#1331]
I have been using knex for a while and I know it is totally different from typeorm, but I didnt found one feature that is present there. The `.toString()` method that returns an array of query strings filled out with the correct values based on bindings, etc.

Ex.: 
```javascript
var toStringQuery = knex.select('*').from('users').where('id', 1).toString();

// Outputs: console.log(toStringQuery); 
// select * from "users" where "id" = 1

```

Is there some similar feature on typeorm?

**Comment by pleerock** [comment]
Yes you can use `getSql` method or `printSql` to instantly print sql query to console:

```ts
const sql = connection.createQueryBuilder()
    .select("user")
    .from(User, "user")
    .where("user.id = :id", { id: 1 })
    .getSql();
```

or

```ts
const users = await connection.createQueryBuilder()
    .select("user")
    .from(User, "user")
    .where("user.id = :id", { id: 1 })
    .printSql()
    .getMany();
```

**Comment by calebeaires** [comment]
Awesome

**Comment by guotie** [comment]
why printSql() did not print sql to console

version: 0.2.5

**Comment by muamichali** [comment]
When I turn on logging in the database connection, I get ALL of the queries not just the ones with printSql

**Comment by sanderboom** [comment]
Is there a handy way to print raw SQL with integrated parameters when I'm using not using the QueryBuilder but e.g. `this.connection.query(sql, parameters)`?

I know when using mysql/mariadb the extra `debug: ['ComQueryPacket']` option will give me the query and a lot more, but something like `getSql()` would be extremely handy :)

**Comment by havenchyk** [comment]
@darkyelox could you please create a new issue for this?

**Comment by werts** [comment]
> > why printSql() did not print sql to console
> > version: 0.2.5
> 
> Make sure you have logging enabled (in the database connection or the ormconfig.json file):
> "logging": true,

Aha, you save my life

**Comment by kuklei** [comment]
And now it prints it twice. Once by the logger in the ormconfig and once by the directive

**Comment by awHamer** [comment]
> > why printSql() did not print sql to console
> > version: 0.2.5
> 
> Make sure you have logging enabled (in the database connection or the ormconfig.json file):
> "logging": true,

In this case it will turn logging any query (including the one we want to print - it will print it twice) 
+ it prints with an array of parameters instead of print a RAW sql in the way it will go to db...

I want to log exactly what goes to db w/o having manually put data replacing each `?` mark.
Any progress ? It's very important thing :( Enabling all query log creates a lot of mess and it's hard to get a correct one + it also doesn't print RAW sql.

**Comment by royalcala** [comment]
printSql and getSql it's only avaible for print queries?, I didn't see in jsDoc how to print from table definitions. 
like 
knex.schema.createTable('users', function (table) {
  table.increments();
  table.string('name');
  table.timestamps();
}).toQuery()
regards.

**Comment by mimoid-prog** [comment]
`printSql` still doesn't work in 2021. The only way I can see the sql queries right now is by setting `logging: true`, which is not good because it prints every possible query.
