### ISSUE TITLE
Unable to run migrations with several db connections config

### ISSUE THREAD

**Issue by jsmonkey** [typeorm/typeorm#1333]
Hi, 

I'm using `ormconfig.json` with multiple connections config: 
```
[{
    "name": "db1",
    "type": "mysql",
    "host": "localhost",
    "port": 3306,
    "username": "root",
    "password": "root",
    "database": "db1",
    "migrations": ["/migrations/*.js"],
    "entities": ["/entities/*.js"]
}, {
    "name": "db2",
    "type": "mysql",
    "host": "localhost",
    "port": 3307,
    "username": "root",
    "password": "root",
    "database": "db2",
    "entities": ["/entities/*.js"]
}]
```
After  `typeorm migrations:run` I got `Cannot find connection default because its not defined in any orm configuration files.`.
So need somehow provide the first connection config for migrations running.

Thanks

**Comment by pleerock** [comment]
you need to specify a connection name:

```
typeorm migrations:run -c db1
```

**Comment by jsmonkey** [comment]
Thanks

**Comment by blakerego** [comment]
Has the `-c` flag been deprecated? When I try this I get: 

`Unknown arguments: c, migrations:run`

**Comment by pleerock** [comment]
@blakerego no, its not. Maybe you are passing it wrong?

**Comment by blakerego** [comment]
@pleerock Does this syntax look correct?

`typeorm migrations:run -c test`

**Comment by pleerock** [comment]
what `typeorm migrations:run -h` shows you? (or --help)

**Comment by jasonmendes** [comment]
@pleerock I'm working with @blakerego and we got `typeorm migration:run -c test` to work locally, however it fails on CircleCI with `Error: Cannot find connection test because its not defined in any orm configuration files.` Have you or anyone ever come across that?

**Comment by pleerock** [comment]
is circle ci able to read ormconfig file? Looks like app can't find it. I can recommend you try it via travis ci and if it won't work try to specify connection options explicitly into `createConnection()` method (instead of using ormconfig)

**Comment by mateusppereira** [comment]
https://github.com/typeorm/typeorm/pull/6080
