### ISSUE TITLE
Can't synchronize schema with the 'typeorm schema:sync' command

### ISSUE THREAD

**Issue by MatxBerg** [typeorm/typeorm#1334]
1. I **can** get my schema to sync with the `synchronize:true` feature when I run my app

2. I **can't** sync my schema with the `typeorm schema:sync` command. It always return `Schema syncronization finished successfully.` without any changes applied to the db schema. I run the command while being in the root of the NodeApp2 folder.

Here's my folder structure and config file. I though it was an issue with the [entitiesDir] params, but it seems fine to me

```
Project
    NodeApp1
        node_modules
        build
            entitities
        ormconfig.json
    NodeApp2
        node_modules
        build
            entitities
        ormconfig.json

```
```
{
    "type": "mssql",
    "host": "localhost",
    "username": "sa",
    "password": "mypasssword!",
    "database": "mydb",
    "extra": {
        "options": {
            "encrypt": true
        }
    },
    "synchronize": true,
    "logging": true,
    "encrypt": true,
    "entities": [
        "NodeApp2/build/entity/**/*.js"
    ],
    "migrations": [
        "NodeApp2/build/migration/**/*.js"
    ],
    "subscribers": [
        "NodeApp2/build/subscriber/**/*.js"
    ],
    "cli": {
        "entitiesDir": "build/entity"
    }
}
```

**Comment by pleerock** [comment]
where is your node_modules directory?

**Comment by MatxBerg** [comment]
I have updated the folder structure, thanks for your quick response

**Comment by pleerock** [comment]
I can't see any issues this way... Can you create a demo git repo with issue reproduction which I can pull and check your issue?

**Comment by pleerock** [comment]
Closing as no answer from reporter.
