### ISSUE TITLE
Connection "default" was not found on browser tab reload ( Ionic )

### ISSUE THREAD

**Issue by vhb56** [typeorm/typeorm#1335]
Hi, not sure if it's an real issue or issue you should think about(i'm almost sure it's something i should think about), but while using ionic in browser you get this error while reloading the browser tab with the browser refresh button, it seems that resets everything & connection instatiated in app.component.ts (for example) resets too and if you were on some page that is using this connection you will get this error, because page reloads faster than connection in app.component.ts reinstatiates.

So i think i can find some road with ionic events or i've seen you have some listener/subscribe stuff, so i'll create a separate provider to manage all DB stuff from it, checking if connection is ready.

But since  you say in docs: 

>Avoid creating extra classes / services to store and manager your connections. This functionality is already embedded into TypeORM - you don't need to overengineer and create useless abstractions.

I'm curious - is there any way to listen if connection was instantiated from different place than the place where `createConnection()` was invoked, ideally would be if `getConnection()` method would return a promise/observable or maybe it will create a default connection if optional param is specified, instead of throwing immediatly `'Connection "default" was not found'`, maybe connection 'Default' is initializing right now (it's async after all).

Sorry if i'm wrong in anything, in that case point me please to what i should use, now i am thinking that creating a separate provider/service, that will reinstatiate connection on demand in case its for some reason was reset(or some combination between ionic events and/or some boolean parameter in my service that will indicate about readyness) or i should use (if they are applicable in this case) 'Entity Listeners and Subscribers' in conjuction with Ionic Page(i've tried to implement `EntitySubscriberInterface` by page & listen `afterLoad()` & `afterInsert()` ? Couldn't get it work, maybe because its not common class, but Ionic page class, maybe because i'm using 'Active Record' & createConnection() instead of manager, maybe because i'm just too dumb.

Using ionic, 'sqljs', Chrome & 'Active Record' pattern. All updated.
As i've said almost sure it's not your problem and i must manage it with a service, but who knows, maybe i'm wrong, thanks.

**Comment by daniel-lang** [comment]
This is a design/usage question and I'm not sure, there is a perfect solution to it. If you look the [ionic-example](https://github.com/typeorm/ionic-example) we have, you can see, that the rootPage is only set after the database connection is established ([app.components.ts](https://github.com/typeorm/ionic-example/blob/master/src/app/app.component.ts#L39)).
This is one way to do it without an extra provider, but it would mean, that the user is presented with a blank page until the connection is ready. Using Android and the `cordova` driver I didn't notice a delay, but it might be a concern.
A different approach is, as you suggested, to create a provider that returns a promise and will create the connection if none is open. You can look at an [older version of the example](https://github.com/typeorm/ionic-example/tree/58264e4e02abd34ae92430faa153df93e3437456) where a seperate provider existed.
`getConnection()` won't be changed to return a Promise ([question about it over at typeorm/typeorm](https://github.com/typeorm/typeorm/issues/1228))

**Comment by vhb56** [comment]
Ok, thx.
