### ISSUE TITLE
Browsersupport broken in 0.1.8

### ISSUE THREAD

**Issue by Prior99** [typeorm/typeorm#1336]
Typeorm broke support for usage in the browser with webpack as bundler, even with using the `NormalModuleReplacementPlugin`.

The following error is displayed:

```
Uncaught Error: This option/function is not supported in the browser environment. Failed operation: require("debug").
    at Function.PlatformTools.load (PlatformTools.js:23)
    at Object.<anonymous> (DebugLogger.js:2)
    at __webpack_require__ (bootstrap 3533b48…:19)
    at Object.<anonymous> (OffsetWithoutLimitNotSupportedError.js:26)
    at __webpack_require__ (bootstrap 3533b48…:19)
    at Object.<anonymous> (ConnectionManager.js:62)
    at __webpack_require__ (bootstrap 3533b48…:19)
    at Object.<anonymous> (bundle.js:51464)
    at __webpack_require__ (bootstrap 3533b48…:19)
    at Object.<anonymous> (inherits_browser.js:23)
```

My guess is that this has to do with introducing the new DebugLogger in 7b98e216.

I think the relevant line leading to this problem is 

```
const debug = PlatformTools.load("debug");
```

from commit 717e6540.

It was working fine in version 0.1.7.

**Comment by pleerock** [comment]
Looks like we need to do something each time we add external dependency? adding @daniel-lang

**Comment by extart** [comment]
In Ionic (Angulsr), this error does not allow the use of a version older than 0.1.7 ...

**Comment by daniel-lang** [comment]
#1344 should fix this

**Comment by daniel-lang** [comment]
A fix for this problem will be released with 0.1.10

**Comment by Golem765** [comment]
Encountered same error in 0.2.0-alpha.13, using ionic 3.9.2, am I doing something wrong?

**Comment by pleerock** [comment]
Because latest alpha didn't have latest master changes. I released `0.2.0-alpha.15` with those changes, please check

**Comment by davidmpaz** [comment]
thank you @pleerock!. For me is working release: `0.2.0-alpha.15` i started to have same error with latest stable `0.1.11`

**Comment by davidmpaz** [comment]
Hi @pleerock, @Golem765,
I though a change in version would solved the issue. For me was not, I still have it when in browser.
```
$ ionic info         

cli packages:
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1
global packages:
    cordova (Cordova CLI) : 7.1.0 
local packages:
    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0
System:
    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : Linux 4.13
```

the error I receive is:
```log
Error: This option/function is not supported in the browser environment. Failed operation: require("glob").
    at Function.PlatformTools.load (http://localhost:8100/build/vendor.js:25039:19)
    at http://localhost:8100/build/vendor.js:181618:110
    at Array.reduce (<anonymous>)
    at importClassesFromDirectories (http://localhost:8100/build/vendor.js:181617:32)
    at ConnectionMetadataBuilder.buildEntityMetadatas (http://localhost:8100/build/vendor.js:181576:167)
    at Connection.buildMetadatas (http://localhost:8100/build/vendor.js:94260:57)
    at Connection.<anonymous> (http://localhost:8100/build/vendor.js:93920:30)
    at step (http://localhost:8100/build/vendor.js:93796:23)
    at Object.next (http://localhost:8100/build/vendor.js:93777:53)
    at fulfilled (http://localhost:8100/build/vendor.js:93768:58)
```
This time error is thrown when PlatformTools tries to load `glob`. The code I try to use is:
```typescript
let dbOptions: CordovaConnectionOptions | WebSqlConnectionOptions = {
    type: 'cordova',
    database: 'products.db',
    location: 'default',
} as CordovaConnectionOptions;

if (isBrowser(this.platform)) {
    dbOptions = {
        type: 'websql',
        database: 'products',
        version: '1',
        description: 'Product database supported in browser',
        size: 5 * 1024 * 1024, // 5MB
    } as WebSqlConnectionOptions;
}

return createConnection(Object.assign(dbOptions, {
    entities: [__dirname + '/../models/*.ts'],
    synchronize: true,
    logging: false,
}));
```
Troubleshooting:

if I log the path used to load entities `console.log(__dirname + '/../models/*.ts');`, this is given: `//../models/*.ts`. This gives me some hints on models not found, maybe?

Giving imported classes to `entities: [ModelClass]` array settings, solved the issue. I did change back my version to latest stable: `0.1.11` and solution seems to be consistent. I am getting other errors but not related to this issue.

Sorry the long post. I just tried to troubleshoot as much as possible.

cheers,
David

**Comment by daniel-lang** [comment]
@davidmpaz You can't use `entities: [__dirname + '/../models/*.ts']` in the browser as this will try to load files from the filesystem which you obviously can't do in the browser.
As you mentioned at end you will have to specify every entity as `entities: [ModelClass]`
