### ISSUE TITLE
EntityMetadata.findColumnWithPropertyPath doesn't work right with ManyToMany JoinTables

### ISSUE THREAD

**Issue by mrosack** [typeorm/typeorm#1339]
I was trying to use querybuilder update to update an entity with a ManyToMany association that looks like this:

```
@ManyToMany(type` => TouchpointEntity, tp => tp.programs)
@JoinTable({
  name: "programs_to_touchpoints",
  joinColumn: { name: "programId", referencedColumnName: "programId" },
  inverseJoinColumn: { name: "touchpointId", referencedColumnName: "touchpointId" }
})
touchpoints: TouchpointEntity[];
```

I kept getting errors from postgres like `error: multiple assignments to same column "programId"` - programId is the primary key of this table, and findColumnWithPropertyPath was resolving the touchpoints relation to programId as well, duplicating it.

I'm not sure if this is the best way to fix it, but I worked around the issue by monkey patching EntityMetadata.findColumnWithPropertyPath to look like this (adding the check to make sure the relation doesn't have a joinTableName):

```
EntityMetadata.prototype.findColumnWithPropertyPath = function(propertyPath) {
  const column = this.columns.find(column => column.propertyPath === propertyPath);
  if (column)
      return column;

  // in the case if column with property path was not found, try to find a relation with such property path
  // if we find relation and it has a single join column then its the column user was seeking
  const relation = this.relations.find(relation => relation.propertyPath === propertyPath);
  if (relation && relation.joinColumns.length === 1 && !relation.joinTableName)
      return relation.joinColumns[0];

  return undefined;
}
```

**Comment by pleerock** [comment]
> I was trying to use querybuilder update to update an entity with a ManyToMany association that looks like this:

can you please provide a code of your query builder usage. Also please provide minimal reproduction entities code

**Comment by pleerock** [comment]
Closing as no answer from reporter.
