### ISSUE TITLE
Left-joining single table multiple time with different conditions

### ISSUE THREAD

**Issue by bytely** [typeorm/typeorm#1342]
When trying to join a single table multiple times with different conditions, parameter values don't seem to be updated:

```js
        this.createQueryBuilder('claim')
            .select('claim.id')
            .leftJoin(ClaimHistory, 'repairerDelivery',
                '"repairerDelivery"."claimId" = claim.id AND "repairerDelivery".status = :status',
                { status: 80 })
            .leftJoin(ClaimHistory, 'buyerDelivery',
                '"buyerDelivery"."claimId" = claim.id AND "buyerDelivery".status = :status',
                { status: 100 })
            .where('claim."repairerId" = :id', { id: "1" })
            .getRawMany();
```

Gives this query

```sql
executing query:  SELECT "claim"."id" AS "claim_id" FROM "claim" "claim"
LEFT JOIN "claim_history" "repairerDelivery" ON "repairerDelivery"."claimId" = "claim"."id" AND "repairerDelivery".status = $1 
LEFT JOIN "claim_history" "buyerDelivery" ON "buyerDelivery"."claimId" = "claim"."id" AND "buyerDelivery".status = $2
WHERE claim."repairerId" = $3 -- PARAMETERS: [80,80,"1"] <---
```
Is this expected?

**Comment by pleerock** [comment]
yes, parameter names must be unique across single query, you need to provide `status1` and `status2` variable names instead of single `status`

**Comment by bytely** [comment]
I see, thank you.

**Comment by pookdeveloper** [comment]
Example:

````javascript
  var manager = getManager().getRepository("usuarios").createQueryBuilder("usuarios");
        manager
            .innerJoinAndSelect("usuarios.persona", "persona")
            .innerJoinAndSelect("usuarios.empleado", "empleado")
            .where("1 = 1")
            .andWhere("usuarios.id_categoria = :id_categoria", { id_categoria: 1 })
            .andWhere("persona.dni = :dni", { dni: "5399522a" })
            .andWhere("empleado.dni = :dni2", { dni2: "5399522d" })

        const datos = await manager.getMany();
````

**Comment by matispf84** [comment]
> Example:
> 
> ```js
>   var manager = getManager().getRepository("usuarios").createQueryBuilder("usuarios");
>         manager
>             .innerJoinAndSelect("usuarios.persona", "persona")
>             .innerJoinAndSelect("usuarios.empleado", "empleado")
>             .where("1 = 1")
>             .andWhere("usuarios.id_categoria = :id_categoria", { id_categoria: 1 })
>             .andWhere("persona.dni = :dni", { dni: "5399522a" })
>             .andWhere("empleado.dni = :dni2", { dni2: "5399522d" })
> 
>         const datos = await manager.getMany();
> ```

Sabes si se pueden usar mas de una condición en el inner join? o si o si se tiene que agregar en el where?
