### ISSUE TITLE
[Question] Is there a way to connect remote MySQL via SSH?

### ISSUE THREAD

**Issue by dinfer** [typeorm/typeorm#1343]
Some MySQL client supports connect remote mysql host via SSH, Is there a way to use `typeorm` in the same way?

**Comment by pleerock** [comment]
I think this is not related to typeorm. Checkout [this stackoverflow answer](https://stackoverflow.com/questions/24687932/node-js-connecting-through-ssh/24688265), maybe it will help you to connect to your mysql instance via ssh.

**Comment by dinfer** [comment]
Thanks, it works for me. : )

**Comment by andreanta** [comment]
I have a similar problem using createConnection(), we have to change node express configuration?
i'm using nestjs with typeorm

**Comment by Diluka** [comment]
# for example
## assume
- `10.164.172.204` is db
- `106.2.32.177` is gateway
## use like this
`ssh -fCPN –L 3307:10.164.172.204:3306 -p1046 rds-user@106.2.32.177`
