### ISSUE TITLE
Is it possible to define (A | B)[] relation?

### ISSUE THREAD

**Issue by dempfi** [typeorm/typeorm#1345]
First of all, thank you all for this great package – it's a breeze 🙇🏻‍♂️

Question I have is this.

```ts
@Entity()
class A {
  @Column()
  a: string
}

@Entity()
class B {
  @Column()
  b: number
}
```

**how to make such `C`?**

```ts
@Entity()
class C {
  @Column(/* ??? */)
  entries: (A | B)[]
}
```

**Comment by pleerock** [comment]
no, its not possible. If you want to bind C with A and B you need to create two relations in C with A and with B

**Comment by dempfi** [comment]
I somehow missed simple fact – I can do whatever I want with the `C` class (like define entries aggregated getter). Thank you @pleerock.
