### ISSUE TITLE
How to migration to typeorm form sequelize?

### ISSUE THREAD

**Issue by keyiis** [typeorm/typeorm#1350]
I used sequelize 3 years,now typescript is very popular,i want migration to typeorm,but i defined many model and relationship use sequelize.so how to simply migrate to typeorm?

**Comment by pleerock** [comment]
It should not be hard, but you'll need to change mindset in some places because typeorm design is different then sequelize. There is a small guide how to migrate to typeorm from sequelize [here](http://typeorm.io/#/sequelize-migration).

**Comment by keyiis** [comment]
@pleerock  thanks reply!

**Comment by keyiis** [comment]
@pleerock I've read the document,but I didn't find some about queryOperator(like` $in,$lt,$eq...` in sequelize),do I have to `Query Builder`?

**Comment by pleerock** [comment]
as you already seen this feature request is tracked by #1101 We'll need to implement this feature.
