### ISSUE TITLE
EntityManager.create and Repository.create do not set relations

### ISSUE THREAD

**Issue by keenondrums** [typeorm/typeorm#1352]
Consider the following setup
```
@Entity()
class A {
  @ManyToOne((type) => B)
   rels: B[]
}

@Entity()
class B {
   @Column()
   name: string

  @OneToMany((type) => A)
   rels: A[]
}
```
With .create API there's no followup UPDATE to update relations
```
const rels = entityManager.find(A)
const newB = entityManager.create(B, { name: 'lalala', rels }) // this does not work
```
Yet this does
```
const rels = entityManager.find(A)
const newB = entityManager.create(B, { name: 'lalala' })
newB.rels = rels
```

**Comment by pleerock** [comment]
Can you please check `next` version? Because `create` method is completely refactored there

**Comment by keenondrums** [comment]
@pleerock it's working with typeorm@next
I created a small [repo](https://github.com/keenondrums/typeorm-issue152) trying to reproduce the issue. Feel free to use its content to create a test for this issue in the upcoming release.

**Comment by pleerock** [comment]
If its working then I'll close this issue. If you want to contribute then you can create a PR with your test into typeorm repository, but please follow typeorm conventions.
