### ISSUE TITLE
TypeORM v0.1.9 SQLite One-To-One/PrimaryGeneratedColumn Bug

### ISSUE THREAD

**Issue by rmuchall** [typeorm/typeorm#1353]
Hi there,

Many thanks for TypeORM + associated libs. You guys rock :)
I'm experiencing a bug in TypeORM details are as follows:

TypeORM version: 0.1.9
Description: When using a one-to-one relationship in SQLite (v3.1.13) on a table with a PrimaryGeneratedColumn() (integer). TypeORM throws an error on startup if the table contains any data.

I've created a Github repository with minimal code to show this issue. You can find it here:
https://github.com/rmuchall/sqlite-one2one-bug

Instructions to recreate the issue:
Run the application twice.
The first time migrations are ran and test data is inserted.
The second time TypeORM will throw an error.

The error that is thrown on startup is:
`QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
    at new QueryFailedError (C:\Work\TypeScript\sqlite-one2one-bug\src\error\QueryFailedError.ts:7:9)
    at Statement.<anonymous> (C:\Work\TypeScript\sqlite-one2one-bug\src\driver\sqlite\SqliteQueryRunner.ts:54:26)
    at Statement.replacement (C:\Work\TypeScript\sqlite-one2one-bug\node_modules\sqlite3\lib\trace.js:19:31)
    at Statement.replacement (C:\Work\TypeScript\sqlite-one2one-bug\node_modules\sqlite3\lib\trace.js:19:31)
  message: 'SQLITE_CONSTRAINT: FOREIGN KEY constraint failed',
  errno: 19,
  code: 'SQLITE_CONSTRAINT',
  name: 'QueryFailedError',
  query: 'DROP TABLE "user"',
  parameters: []
`

Thanks for your assistance.

**Comment by rmuchall** [comment]
Further information:
This bug does not occur in TypeORM v0.1.8
This bug does not occur in TypeORM v0.1.9 if using uuid primary generated columns. It seems only occur if using integer primary generated columns.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.
