### ISSUE TITLE
MongoDB Transactions

### ISSUE THREAD

**Issue by jselesan** [typeorm/typeorm#1356]
Hi there. Knowing that MongoDB does not have native support for transactions, I'm wondering if you saw this project: https://github.com/e-oj/Fawn, wich provides transactions to Mongoose using the two-phase commit pattern.

Do you think it is possible to implement something like that on the MongoRepository in order to support transactions?

**Comment by pleerock** [comment]
Yes, you probably can mock things and implement it, I do not have plans to implement this in typeorm core yet.
