### ISSUE TITLE
Data type "Object" in "xx.xx" is not supported by "sqlite" database.

### ISSUE THREAD

**Issue by raaay0608** [typeorm/typeorm#1358]
SQLite, got something like
```
DataTypeNotSupportedError: Data type "Object" in "Post.publishDate" is not supported by "sqlite" database.
```
when some columns are `Date` or `Buffer` type.

If I do something like`@Column('datetime')` or `@Column('blob')`, it seems everything is fine, but I  can't dev with sqlite and product with postgres (datetime -> timestamp, blob -> bytea), and I must handle different version of my app if it's required to work with different DBs... which I think is, just not very perfect.

```js
@Entity
export class SomeEntity {

  @Column()
  someString: string; // ok
  // thus no problem with "reflect-metadata" or "tsconfig.json"

  @Column()
  someDate: Date; // error

  @Column('datetime')
  anotherDate: Date; // ok

  @Column()
  someBinary: Buffer; // error

  @Column('blob')
  anotherBinary: Buffer; // ok

}
```

**Comment by pleerock** [comment]
What typeorm version are you using and what reflect-metadata package are you using? Just checked this functionality and it works fine in sqlite in latest 0.1.9 version. Are you able to provide a failing test with reproduction of this issue in a PR?

**Comment by raaay0608** [comment]
```
"reflect-metadata": "^0.1.10",
"sqlite3": "^3.1.13",
"typeorm": "^0.1.9"
```
I'm using macOS, and
```
$ node --version
v9.3.0
```

Sorry I'm not familiar with the test framework, but I created a very simple example repo, that may helps.

https://github.com/raaay0608/typeorm-demo

just define a model with `Date` and `Buffer`, and then `createConnection()`

**Comment by raaay0608** [comment]
I removed the old project and created a new one, then nothing wrong with sqlite3 anymore.
Maybe it's just something wrong of my `node_modules`

Sorry for bringing noises here.

**Comment by aimed** [comment]
For anyone else running into that error when using ts-node: using the --type-check flag ```tsnode --type-check``` fixes the problem for me. As far as I understand this is due to ts-node using a faster compile process, which doesn't check types and thus doesn't emit metadata.

**Comment by mindjuice** [comment]
@aimed Thank you for that!  Only started happening when I tried going to production on short notice of course!

**Comment by bennyn** [comment]
I received the following error:

> DataTypeNotSupportedError: Data type "Object" in "Test.text" is not supported by "sqlite" database.

I have been able to fix it in `Test.ts` with changing from:

```ts
@Column() text: string | undefined;
```

To:

```ts
@Column() text: string;
```

**Comment by pleerock** [comment]
@bennyn its a correct behaviour since `string | undefined` type cannot we inferred (we cannot understand if its a string)

**Comment by avantjustus** [comment]
`string | null` or `string | undefined` is just `varchar null`. That cannot be inferred?

**Comment by pleerock** [comment]
@avantjustus no typescript does not emit such type information.

**Comment by pmoleri** [comment]
Hi @pleerock, I just hit this issue.
Is there any recommendation for working with `strictNullChecks`?

If I define like this:
```
@Entity()
export class Project extends Element {
    @Column({ nullable: true })
    publishedOn: Date;
    ...
```

The `Date` type means that that property isn't nullable, so for TS I should define it as `Date | null` but then typeorm fails.

**Comment by pleerock** [comment]
declaring the type explicitly is the only thing you can do.

**Comment by indera-shsp** [comment]
I am getting a similar issue:
- "sqlite3": "^4.0.6",
- "typeorm": "^0.2.16",
- "typescript": "^3.4.1"

```
DataTypeNotSupportedError: Data type "timestamp" in "Endpoint.createTimestamp" is not supported by "sqlite" database.

      at new DataTypeNotSupportedError (src/error/DataTypeNotSupportedError.ts:9:9)
      at src/metadata-builder/EntityMetadataValidator.ts:83:27
          at Array.forEach (<anonymous>)
      at EntityMetadataValidator.Object.<anonymous>.EntityMetadataValidator.validate (src/metadata-builder/EntityMetadataValidator.ts:80:36)
      at src/metadata-builder/EntityMetadataValidator.ts:44:56
          at Array.forEach (<anonymous>)
      at EntityMetadataValidator.Object.<anonymous>.EntityMetadataValidator.validateMany (src/metadata-builder/EntityMetadataValidator.ts:44:25)
      at Connection.Object.<anonymous>.Connection.buildMetadatas (src/connection/Connection.ts:508:33)
      at Connection.<anonymous> (src/connection/Connection.ts:189:18)
      at step (node_modules/tslib/tslib.js:133:27)
      at Object.next (node_modules/tslib/tslib.js:114:57)
      at fulfilled (node_modules/tslib/tslib.js:104:62)
```

Entity column
```

  @Column('timestamp', {
    default: () => 'CURRENT_TIMESTAMP',
    name: 'createTimestamp',
    nullable: false,
  })
  public createTimestamp: Date = new Date();
```

The code is executed using jest 

$ ./node_modules/.bin/jest unit.test.ts

**Comment by dan-klasson** [comment]
@indera-shsp One way is to create your own decorator for column types not supported by sqlite:

https://stackoverflow.com/a/61472440/538471

**Comment by pang0103** [comment]
@indera-shsp I ran into the same "timestamp" not support in Sqlite exception. Did you found a solution ?
