### ISSUE TITLE
relation "TABLE_NAME" does not exist

### ISSUE THREAD

**Issue by eyalhakim** [typeorm/typeorm#1361]
Happens when trying to persist a SingleEntityChild entity.

**Comment by pleerock** [comment]
what typeorm version are you using? STI works only in `next` version currently (`npm i typeorm@next`). Make sure you are using it. 

If you have this issue on n`next` then provide a code to reproduce the issue.

**Comment by eyalhakim** [comment]
on `next` i get `Module '"./node_modules/typeorm/index"' has no exported member 'SingeEntityChild'.`

**Comment by pleerock** [comment]
yes because it was renamed to `@ChildEntity`, see changelog on next branch for details, and updated tests and examples

**Comment by eyalhakim** [comment]
after migrating to the latest version i'm getting `Entity XXXX using single-table inheritance, it should also have a discriminator column. Did you forget to put @DiscriminatorColumn decorator?`

**Comment by eyalhakim** [comment]
@pleerock any idea why?

**Comment by pleerock** [comment]
You need to add it as well: 

```ts
@Entity()
@TableInheritance("single-table")
@DiscriminatorColumn({ name: "type", type: "varchar" })
export class Person {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

}
```

**Comment by eyalhakim** [comment]
@pleerock in the `next` version `DiscriminatorColumn` doesn't exist anymore, nor does it appear on the docs.

**Comment by pleerock** [comment]
oh, sorry I was checking tests on master branch instead of next. So in next following code:

```ts

@Entity()
@TableInheritance({ column: { name: "type", type: "varchar" } })
export class Person {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

}
```

**Comment by eyalhakim** [comment]
seems like it works, now i get `relation "migrations" does not exist`, from the other bug i submitted

**Comment by pleerock** [comment]
Okay then I'll close it and lets take a look on another issue.

**Comment by eyalhakim** [comment]
Great, thank you!
