### ISSUE TITLE
How to share models server/client with Angular CLI

### ISSUE THREAD

**Issue by Toxicable** [typeorm/typeorm#1362]
Since the Angular CLI does not give you direct access to the webpack config we are not able to follow the instructions found here https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js#L16-L21
Instead we are able to use the `paths` config under the tsconfig so I attempted with 
```
//src/tsconfig.app.json
"paths": {
      "typeorm": ["../node_modules/typeorm/typeorm-model-shim"]
    }
```
However I still get errors such as
>Error: Can't resolve 'pg-native' in /home/fabian/Documents/test-proj/node_modules/pg/lib/native

Which I assumes means the shim isn't working

Just to confirm that im not importing from some other part of typeorm I have this file here
```
import { Entity} from 'typeorm';
@Entity()
export class TestModel{
  name: string;
}
```
which throws the error, if I remove the `@Entity` then the error goes away

**Comment by pleerock** [comment]
> Since the Angular CLI does not give you direct access to the webpack config we are not able to follow the instructions found here https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js#L16-L21
Instead we are able to use the paths config under the tsconfig so I attempted with

Looks like angular CLI issue

> Error: Can't resolve 'pg-native' in /home/fabian/Documents/test-proj/node_modules/pg/lib/native

no, it will work if you properly setup webpack, typeorm will never be loaded in your frontend thus pg will not be loaded as well. So, make sure what you are doing with angular CLI really works and maybe try to setup angular project without angular cli and check if it works

**Comment by Cuel** [comment]
The CLI team said they'll never expose the webpack configuration. I got around this by having a postinstall script rewrite [a file](https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/tasks/serve.ts#L262) in angular-cli node_modules to expose the webpack configuration for my app. It's a ugly hack for sure but until the CLI team decides differently, that's your only option besides using [ng eject](https://github.com/angular/angular-cli/wiki/eject)

**Comment by Toxicable** [comment]
With a bit of help it turns out I had my config a little misconfigured. You can achieve the same behaviour by adding this under `compilerOptions` in your `tsconfig.app.json`
```
    "paths": {
      "typeorm": ["../node_modules/typeorm/typeorm-model-shim.js"]
    }
```

**Comment by nextlevelshit** [comment]
Just for the sake of completeness:

```
{
  ...
  "compilerOptions": {
    ...
    "paths": {
      "typeorm": ["../node_modules/typeorm/typeorm-model-shim.js"]
    }
  }
}
```

**Comment by pleerock** [comment]
@nextlevelshit thats a better way actually. We'll need to update docs and use the method you have suggested

**Comment by SerkanSipahi** [comment]
@Toxicable as far as i understood the shim allow us to use only the model itself (class) without any `Typeorm` features like `OneToMany`, `Entity`, etc,! right?
