### ISSUE TITLE
UnhandledPromiseRejection Warning

### ISSUE THREAD

**Issue by jacks821** [typeorm/typeorm#1363]
I'm having trouble getting TypeORM to save a relation. Specifically, I get the following error: 
(node:5764) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'matchId' doesn't have a default value

My code goes like this 

`connection.createQueryBuilder()
    .relation(Profile, "matches")
    .of(args.email1).add(match);`

And my entity is as follows: 

` @Entity()
export default class Match {

  @PrimaryGeneratedColumn("uuid")
  public id: string;

  @ManyToMany(type => Profile, profile => profile.matches)
  public profiles: Profile[]

  @OneToOne(type => Chat, chat => chat.match)
  @JoinTable()
  public chat: Chat;

} `

Please help. I don't understand why it's not auto-creating an Id.  Thank you.

**Comment by pleerock** [comment]
```ts
@OnetoOne(type => Chat, chat => chat.match)
@jointable()
public chat: Chat;
```

you should use `@JoinColumn`, not `@JoinTable`. 
Fix this and provide more details. What is `args.email`? Try to explicitly provide match id. Why "Profile" calls "matches"? Why are you using this functionality instead of relying on `save` method? 
Also, please format your code properly.

**Comment by jacks821** [comment]
Thanks for the input. I'm trying to edit the format. args.email is from a GraphQL call, and is an object Graph is passing. I am using this functionality because that's the pattern that they say to use on typeorm.io for relations.

**Comment by pleerock** [comment]
Closing as no answer from reporter.
