### ISSUE TITLE
No api to use sql files in migrations and migrations fail with string template literals

### ISSUE THREAD

**Issue by jsmonkey** [typeorm/typeorm#1366]
Hi,

I use typeorm migrations. There is no any api to load sql queries from sql files.
So I have to use js string template literals. But it converts formatted sql with `\n` new line symbols.

Even after replacing `\n` symbols result sql triggers syntax errors and queries fail.

Fix asap.

Thanks

**Comment by jsmonkey** [comment]
OMG,

guys, when I use several times `CREATE TABLE` command in my initial migration it fails cuz all migrations are covered with transactions. In mysql for ddl it's restricted to use several creations in single transaction.

Fix this case in your library pls.

**Comment by pleerock** [comment]
you can use `queryRunner.connection.manager.query()` and execute query without migration

**Comment by jsmonkey** [comment]
That's it, I want to use migration api, cuz it's right way to make changes for the database structure and default data.
Btw this part of code also fails on multiple insertions:
```ts
 async up(queryRunner: QueryRunner): Promise<any> {
    const defaultValues = `
        INSERT INTO sometable (val) VALUES ('val1');
        INSERT INTO sometable (val) VALUES ('val2');
        INSERT INTO sometable (val) VALUES ('val3');
     `;
    await queryRunner.query(defaultValues);
  }
```

That's weird cuz evenv with `START TRANSACTION` and `COMMIT` commands such sequence of insert command runs well from the editor of sql client.

**Comment by pleerock** [comment]
> That's it, I want to use migration api, 

You can commit your opened transaction, do what you want, then open transaction again in your code. There are multiple ways to resolve your issue.

> Btw this part of code also fails on multiple insertions:

fails with errors or what? What if you execute each query separately?

**Comment by jsmonkey** [comment]
If I commit several times in one migration, and smth goes wrong after first transaction then I won't be able to rollback the all changes of migration step. That's the point why I don't want to use several transactions in one migration step.  

`INSERT` queries fail with syntax error at the beginning of the second `INSERT` instruction. btw the same query with multiple insertions works great from sql client editor, even with covered with transaction.

**Comment by jsmonkey** [comment]
I think that's mb cuz of lack of `multipleStatements: true` property in init of the mysql connection.

**Comment by pleerock** [comment]
You can set this option in connection options.

**Comment by jsmonkey** [comment]
Yeah, but I don't have any interceptor for connection creation in scope of migrations api. `QueryRunner` object which is passed to `up` or `down` handlers already has inside constructed `Connection` property.

**Comment by pleerock** [comment]
that's okay if you set it per-global-connection. For specific use cases you need to write specific code.

**Comment by jsmonkey** [comment]
ok, thanks

**Comment by Halynsky** [comment]
This library can help in this case
'Specific code' is wrapped into npm lib
https://www.npmjs.com/package/node-sql-reader

**Comment by acao** [comment]
@jsmonkey was correct! 

> I think that's mb cuz of lack of multipleStatements: true property in init of the mysql connection.

we tried `node-sql-reader` but it was too slow for our 200mb-6GB files.

another issue people might be stumbling over is that `readFile` defaults to reading out a memory buffer, but you want to give `queryRunner.query()` a string.

so this works with typeorm directly:

```ts
export const AppDataSource = new DataSource({
   source: 'postgres', // or `mysql`
   multipleStatements: true,
   ....
})
```

(with `@nestjs/typeorm`):

```ts
export const TypeOrm = TypeOrmModule.forRootAsync({
  imports: [Env],
  useFactory(env: Config) {
    return {
      type: 'postgres',
      ...
      multipleStatements: true,
    };
  },
});

```

and then in the migrations:

```ts
import fs from 'node:fs/promises'

export class ExampleMigration implements MigrationInterface {
   public async up(queryRunner: QueryRunner): Promise<void> {
      let queries = await fs.readFile('./data/sql/ipcc-zones.sql', { encoding: 'utf-8' });
      await queryRunner.query(queries);
  }
}
```

a migration importing SQL files over http:

```ts
import { MigrationInterface, QueryRunner } from 'typeorm';
import fs from 'node:fs/promises';
import os from 'node:os';
import {resolve} from 'node:path';
import fetch from 'node-fetch';

export class ExampleNetworkMigration implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const destPath = resolve(os.tmpdir(), 'sqldumps')
    await fetch('https://ourbucket/migration_file.sql')
    .then(res => res.arrayBuffer())
    .then(buf => fs.writeFile(destPath, Buffer.from(buf)))

    let queries = await fs.readFile(destPath, {  encoding: 'utf-8' });
    await queryRunner.query(queries);
    }
 }
 ```
 
notes:
- using `utf8` encoding or applicable is required for `readFile()`, `readFileSync()` and `fs/promises` `await readFile()` here. by default, fs.readFile() reads to a `Buffer`, so an `encoding` of some kind is required for a string output
- using `ArrayBuffer` still requires lots of memory, so a streaming approach with batch of n statement executions is recommended if you run out of memory
- `writeFile()` and similar defaults to `utf-8` encoding in the http example, thus why no configuration is needed.
- my sql files contain `\n` newline symbols and I have no issues like the original reporting user.

I considered creating a PR to add a method for this, but instead I think I will just open a PR to add this to the docs, and to add more information

**Comment by art1c0** [comment]
Hi @acao and thanks for the provided solution, however when I try to use it I get an error saying that there is no property `multipleStatements` in `PostgresConnectionOptions`. I've checked `typeorm` [repo](https://github.com/typeorm/typeorm/commits/master/src/driver/postgres/PostgresConnectionOptions.ts) and it seems it never was there...
Could you please tell how did you make it work with postgres?
