### ISSUE TITLE
[Feat] Normalized data results for pagination

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#1367]
If you've seen [Normalizr](https://github.com/paularmstrong/normalizr) for data state in apps, you'll notice it has some nice properties like nested entities referred by it's `Id` instead of nesting the entity, this approach fits very well with Redux-like state management, would like to open discussion for this kind of feature.

Though it could be done in the client side at receiving end of the data, like a service that performs map operation over the query result, it could also be done from server side, the question is which is better?

Would it be good if the database provided this all already set up and just be able to turn it 'on' on demand?

**Comment by pleerock** [comment]
Functionality of integration normalizr and typeorm cannot be inside typeorm, it shall be a separate plugin created by community.

**Comment by luchillo17** [comment]
Has typeorm any support for plugins? or is like overriding the code when loaded? or just a layer over the library?

**Comment by pleerock** [comment]
Plugins can be different and different plugins require different functionality. Some may use exist functionality, some may need to override things, some may need changes in typeorm.

**Comment by luchillo17** [comment]
What i meant is, does TypeORM has any support for plugins? like the way Webpack exposes it's event chain to every loader or plugin?, or are we hacking our way in the library for any plugin?

**Comment by pleerock** [comment]
Webpack is supposed to work with plugins because it organizes flow in which you can execute given plugins. We can some flow-based logic when its needed, however typeorm is very complex and we need to exactly know were we need it and design a plugin system. Its all about community initiative they just need to start writing plugins and we'll see how we can improve typeorm to make better support for plugins.

**Comment by luchillo17** [comment]
So for now hacking it is.

**Comment by pleerock** [comment]
Feel free to create a plugin and send requests regarding to plugin system.
