### ISSUE TITLE
Sourcemaps break error reporting in Jest

### ISSUE THREAD

**Issue by TimonVS** [typeorm/typeorm#1372]
Sourcemaps seem to break error reporting in Jest. Every time TypeORM throw an error while running tests with Jest I get something like this:

```
ENOENT: no such file or directory, open '/Users/timon/Projects/typeorm-jest-bug/src/metadata-builder/EntityMetadataValidator.ts'
```

Removing the sourcemap for `EntityMetadataValidator.ts` seems to fix the problem. It also only happens in Jest, when I run the code in Node it works perfectly fine.

I made a repository as to easily reproduce the bug: https://github.com/TimonVS/typeorm-jest-bug

**Comment by pleerock** [comment]
Im not familiar with jest and don't know how it works. And its not clear to me why it uses your project path, e.g. 

`
'/Users/.../www/clonned/typeorm-jest-bug/src/error/DataTypeNotSupportedError.ts'
`

Can you try to debug and find a source of problem?

**Comment by pleerock** [comment]
Adding jest expert @hmil

**Comment by hmil** [comment]
I'm no Jest expert but your test repo gets fixed by downgrading `jest` and `ts-jest` to versions `21.x.x`

```
--- a/package.json
+++ b/package.json
@@ -5,8 +5,8 @@
   "devDependencies": {
     "@types/jest": "^21.1.8",
     "@types/node": "^8.0.29",
-    "jest": "^22.0.3",
-    "ts-jest": "^22.0.0",
+    "jest": "^21.0.0",
+    "ts-jest": "^21.0.0",
     "ts-node": "3.3.0",
     "typescript": "2.5.2"
   },
```

Try to isolate whether it's due to `ts-jest` or `jest` and file an issue over there.

**Comment by TimonVS** [comment]
Yep, it seems to be an issue with Jest itself. I'll dive deeper and file an issue in the Jest repo. Thanks for the help!

**Comment by pleerock** [comment]
thank you for your help @hmil

**Comment by lightsofapollo** [comment]
Fairly sure this is related to https://github.com/facebook/jest/issues/5121

**Comment by 91debug** [comment]
thank you @hmil  bro!

**Comment by canhnht** [comment]
Thank you @hmil !
