### ISSUE TITLE
mysql2 not `require`d properly in jest

### ISSUE THREAD

**Issue by hmil** [typeorm/typeorm#1373]
Yet another issue with using typeorm x Jest!

It appears that Jest is creating a mock for `mysql` when I did not install `mysql` and want to use `mysql2` instead. Not only that but it waits until **after** the first attempt to require `mysql` to create the mock! This leads to a crazy heisenbug where the first time one calls `createConnection`, typeorm uses the `mysql2` driver, and the second time it uses the bogus `mysql` driver and crashes!

This issue can be worked around by adding an additional check to make sure we don't get garbage in return of the call to `require('mysql')`.

**Comment by pleerock** [comment]
Closing since PR was already merged.
