### ISSUE TITLE
Unable to catch exception when working with transactions

### ISSUE THREAD

**Issue by govorov** [typeorm/typeorm#1376]
Hey!

I'm experiencing unhandled promise rejection when working with transactions in an app based on Koa and TypeORM.
I have an error handling middleware with a code like this:
```
export const errorHandlerMiddlewareCreator = ({ logger }) => {
    return async (ctx, next) => {
        try {
            await next();
        }
        catch (error) {
            //... logging-related functionality
            throw error;
        }
    };
}
```

And a GraphQL mutation resolver with this logic inside:
```
export const updateCardsMutation = {
    async updateCards(_, { patches }: { patches: Array<CardPatchWithId> }) {

        inputValidator.assertValid(patches);

        // throw new Error('this error will be catched by middleware');

        getManager().transaction(async (entityManager) => {
            throw new Error('But this will not');
        });
    }
};
```

Errors thrown from transaction callback body are never catched, and I can't understand why. A related typeorm piece of code is (I suppose) https://github.com/typeorm/typeorm/blob/8cd8710bc0535e8c12eef6994bf4fc92d1d80b60/src/entity-manager/EntityManager.ts#L103-L107

Hope you can help. Thank you!

**Comment by pleerock** [comment]
Can you please create a minimal possible reproduction example without third party dependencies like koa and graphql?

**Comment by govorov** [comment]
Hi Umed,
Thank you for the response.
I've just tried to create a repo with reproduction. And while coding I've noticed that I've accidentally missed `await` before `getManager().transaction` call. Maybe I was too tired yesterday and didn't notice that. Expection gets succesfully catched with `await` keyword. Hence there's no issue for me anymore. Thanks.
