### ISSUE TITLE
feature request: CLI specify ormconfig

### ISSUE THREAD

**Issue by timc13** [typeorm/typeorm#1378]
Allow us to specify a `ormconfig.js` or `ormconfig.json` for the CLI.

This is necessary because i have specified different `entities` for migrations (typescript) vs running in production mode (transpiled js).

**Comment by pleerock** [comment]
You can specify a config name, e.g.: `typeorm schema:sync --config prodconfig`. Using different name for config file will solve your issue. I don't think there is a need to specify filetype as well.

Also, don't forget you can use glob in your entities configuration, and following may work for you for both dev and prod by doing following: `entities: ["src/entities/*{.ts,.js}"]`

**Comment by Maks1988** [comment]
Can i work with the CLI and .env configuration ?

**Comment by rustamwin** [comment]
@Maks1988 Yeah.

**Comment by Maks1988** [comment]
Please tell where i can find examples of .env variables for configuring migrations and .env file ?
