### ISSUE TITLE
typescript operator `keyof` will be helpful to make exact code completion for `Entity`

### ISSUE THREAD

**Issue by wanganjun** [typeorm/typeorm#1382]
These following declarations are just quick demo.

// src/find-options/FindOneOptions.ts
```
+ export interface FindOneOptionsSelect<Entity, K extends keyof Entity> extends FindOneOptions<Entity> {
+     select: K[];
+ }
```

// src/find-options/FindManyOptions.ts
```
+ export interface FindManyOptionsSelect<Entity, K extends keyof Entity> extends FindOneOptionsSelect<Entity, K> {
+     skip?: number;
+     take?: number;
+ }
```

// src/repository/Repository.ts
// ensure following overload above `find(options?: FindManyOptions<Entity>): Promise<Entity[]>;`
```
+ find<K extends keyof Entity>(options?: FindManyOptionsSelect<Entity, K>): Promise<Pick<Entity, K>[]>;
```

// sample/sample1-simple-entity/app.ts
```
+ const posts = await postRepository.find({
+     select: ['id', 'text'],
+ })
+ // After dot entered, only `id` and `text` will show
+ posts[0].
```

**Comment by pleerock** [comment]
but its already a `keyof` of entity:

```ts
export interface FindOneOptions<Entity> {

    /**
     * Specifies what columns should be retrieved.
     */
    select?: (keyof Entity)[];

     // ....
}
```

**Comment by wanganjun** [comment]
yeah, `keyof` in `FindOneOptions` is good enough for retrieve data from database, but it is not type safe, we can see that in following image.
<img width="550" alt="current-implementation" src="https://user-images.githubusercontent.com/7713237/34339451-26fbc644-e9af-11e7-950e-5e4d5c6a4996.png">
in my demo, the type of query result will be exact the same as you want.
<img width="548" alt="improved-type" src="https://user-images.githubusercontent.com/7713237/34339526-400a5c8a-e9b0-11e7-8e08-16cbfd8929ab.png">

**Comment by pleerock** [comment]
Ah, okay. Sounds like an idea. Let's see if it won't bring any other issues.

**Comment by pleerock** [comment]
No, I don't think this will be implemented. The main reason is that find returns you instance of classes which may contain methods which you'll not be able to use. Also it may bring you issues because it will limit you on how you can use this pick-type instead of real class type.
