### ISSUE TITLE
MyProject error:EntityMetadataNotFound

### ISSUE THREAD

**Issue by face08** [typeorm/typeorm#1383]
I test the demo MyProject
there is no problem with NPM start,
But if I use webstorm, it will be wrong.
My setting is like this
![2017-12-26 2 24 21](https://user-images.githubusercontent.com/402000/34349039-a36459cc-ea49-11e7-9aee-948e05478565.png)

**Comment by pleerock** [comment]
How this issue is related to typeorm?

**Comment by pleerock** [comment]
error:EntityMetadataNotFound means entity is not found, make sure path you used in ormconfig really match entities, e.g. it loads all entities from the given path and path is really correct in runtime.
