### ISSUE TITLE
Is class-table inheritance working?

### ISSUE THREAD

**Issue by eeyang92** [typeorm/typeorm#1384]
Hi,

I just discovered this project today and it's been pretty awesome!

Sort of related to https://github.com/typeorm/typeorm/issues/596, I've tried single-table inheritance on 0.2.0-alpha.11 and can confirm (at least in my limited testing) it is working.

However, I noticed that class-table inheritance creates a schema much more to my liking. The only issue is that I always get a foreign key constraint failure in MySQL.

For example (untested, but very similar to my situation):

```
@TableInheritance('class-table')
@DiscriminatorColumn({ name: 'type', type: 'varchar' })
@Entity()
class Person {
    test: string

    @ManyToOne(type => Company, company => company.person)
    company: Company
}

@ClassEntityChild()
class Employee extends Person {
   test2: number
}

@ClassEntityChild()
class Contractor extends Person {
   test3: number
}

@Entity()
class Company {
    @oneToMany(type => Person, person => person.company)
    person: Person[]
}
```

If I attempt to assign an Employee or Contractor to a Company, I will get a Foreign Key constraint error (since Employee and Contractor are not a Person, as far as MySQL understands it). My impression is that `typeorm` should figure out that Employee is a child class of Person and take care of that behind the scenes?

That sounds pretty difficult - again awesome work so far! 👍

**Comment by pleerock** [comment]
no, class table inheritance is not supported and we are not planning to support it yet. There was a support of CTI however it was coming with a high cost - lot of code and lot of confusion to typeorm codebase, lot of bugs and issues, lot of limitations to other functionality and bad user experience. So we decided to remove its support, for people who really need it and ready to pay for its cost I suggest to implement CTI on their own.

**Comment by eeyang92** [comment]
Gotcha, appreciate the quick response!
