### ISSUE TITLE
Passing array object in find Method (TypeORM)

### ISSUE THREAD

**Issue by PawanKr2feb** [typeorm/typeorm#1385]
I am migrating the API to TypeORM from mongoose. I have an array(conversationIds) containing list of id to be searched from the Database and it should return me the available id. Below are the query which i have tried.

`const conversationMessagesWithDuplicates = await consversationRepository.createQueryBuilder("conversation").where("conversation.channel_message_ID = :channel_message_ID",{channel_message_ID : conversationIds}).getMany();`

OR

`const conversationMessagesWithDuplicates = await consversationRepository.find({channel_message_ID: conversationIds});`

But i am getting below issue:
`(node:11548) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): QueryFailedError: Error: Incorrect syntax near ','.`

Below is the MoongoseAPI which is working fine:

`Conversation.find( { channel_message_ID: { $in: conversationMessageIdArray } } ).exec(function(err, conversationMessagesDuplicatesArray) {}`

**Comment by daniel-lang** [comment]
you can do the following:

```typescript
const conversationMessagesWithDuplicates = await consversationRepository
   .createQueryBuilder("conversation")
   .where("conversation.channel_message_ID IN (:channel_message_IDs)",{channel_message_ID : conversationIds})
   .getMany()
```

Which should be the equivalent of your moongose query.

**Comment by daniel-lang** [comment]
@PawanKr2feb I'm going to close this. If you have more questions about the find method or TypeORM in general, feel free to reopen it.

**Comment by mentos1386** [comment]
@daniel-lang it would be nice if it would work with arrays, without using query builder. I think this is quite common use case.

**Comment by daniel-lang** [comment]
@pleerock what are your thoughts on this?

**Comment by pleerock** [comment]
Yes we have this feature request already in #1101
