### ISSUE TITLE
How to make custom error handler?

### ISSUE THREAD

**Issue by rohmanhm** [typeorm/typeorm#1386]
I have an entity like below.

```ts
import {
  Entity,
  PrimaryGeneratedColumn,
  Column
} from 'typeorm'

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number

  @Column({
    length: 30,
    unique: true,
    nullable: true
  })
  username: string

  @Column({
    length: 255,
    unique: true
  })
  @IsEmail()
  email: string
}
```

As you can see, I have 2 unique columns (`username` and `email`). When I insert a new data `username` and `email` that existed on the database, it will throw an error something like this.

```json
	{
        "message": "ER_DUP_ENTRY: Duplicate entry 'lodddrem@ipsumemail.com' for key 'email'",
        "code": "ER_DUP_ENTRY",
        "errno": 1062,
        "sqlMessage": "Duplicate entry 'lodddrem@ipsum.com' for key 'email'",
        "name": "QueryFailedError",
        "parameters": [
          "lodddrem_username",
          "lodddrem@ipsumemail.com"
        ]
    }
```

My problem is, the error message is not good enough for reporting the errors. It just says that the error just in `email` field.
What I want to achieve is error message something like this.

```json
[
    {
		"column": "email",
        "message": "ER_DUP_ENTRY: Duplicate entry 'lodddrem@ipsumemail.com' for key 'email'",
        "code": "ER_DUP_ENTRY",
        "errno": 1062,
        "sqlMessage": "Duplicate entry 'lodddrem@ipsum.com' for key 'email'"
    },
   {
		"column": "username",
        "message": "ER_DUP_ENTRY: Duplicate entry 'loremusernme' for key 'username'",
        "code": "ER_DUP_ENTRY",
        "errno": 1062,
        "sqlMessage": "Duplicate entry 'loremusernme' for key 'username'"
    }
]
```
It looks more obvious for error reporting which you get the `column` name of error data.

The question is, how can I achieve that? Any good solution for it?

**Comment by pleerock** [comment]
Its not possible. 

The error you have (`Duplicate entry 'lodddrem@ipsum.com' for key 'email'`) is given by a database. Database returns you only ONE (first) error, it does not return you what you want. 

Solution is not to use database errors, but use validation library instead (like class-validator), create a separate validation logic and provide a good messages.

**Comment by rohmanhm** [comment]
Thanks for the solution, I thought your library already doing checking for the unique column.

**Comment by deepchudasama** [comment]
**Problem:** I want the key which is Duplicate.
**Technical Specs:**
nodejs: 10
typeorm: ^0.2.7

It's kind of weird but I got error differently like,
`ER_DUP_ENTRY: Duplicate entry '1234567891' for key 'IDX_94885a1050f3e1d57a431de011'`

Thanks in advance

**Comment by visualcookie** [comment]
@rohmanhm Did you figure out how to do it with `class-validator`? I'm struggling at it right now.

**Comment by AnechaS** [comment]
replacing message.
example case unique
```js
if (error instanceof QueryFailedError && error['code'] === '23505') {
      const message = error.detail..replace(
        /^Key \((.*)\)=\((.*)\) (.*)/,
        'This $1 $2 already exists.',
      )
     // => This COLUMN VALUE already exists.
}
```
