### ISSUE TITLE
Is repository.transaction() deprecated?

### ISSUE THREAD

**Issue by icepeng** [typeorm/typeorm#1387]
Typeorm module for Nest (https://github.com/nestjs/typeorm)

The module provides `@InjectRepository(Entity)` decorator for injecting repository to service.

However, there are no such feature like `@InjectManager()`, there are no way to use transaction.

Seems like `repository.transaction()` is deprecated since 0.1.0, but this feature is still needed for some situation.

Of course, I can use `import { getManager } from 'typeorm'`, but I want to find solution inside Nest.

If `repository.transaction()` is totally deprecated for design, I will work for `@InjectManager()` for Nest-Typeorm module. If not, I think `repository.transaction()` will be useful, find out way to add `repository.transaction()` feature.

**Comment by pleerock** [comment]
repository.transaction is deprecated because it brings confusion - user thinks like it is a transaction in terms of repository which is not true. If nest provides you `InjectRepository` decorator then it should provide `InjectManager` decorator as well.

**Comment by icepeng** [comment]
Yes, it seems possible to implement InjectManager. Thank you.
