### ISSUE TITLE
Typo in Connection error message.

### ISSUE THREAD

**Issue by sandokanelcojo** [typeorm/typeorm#139]
There is a little typo in the text.

Cannot create connection, because connection options are missing. You either need to explicitly pass connection options, either create a ormconfig.json **with with** connection options and "default" connection name, either to set proper environment variables. Also, if you are using environment-specific configurations in your ormconfig.json make sure your are running under correct NODE_ENV.

CannotDetermineConnectionOptionsError.js line 17

Nice work so far! ;)

**Comment by pleerock** [comment]
Thanks, I'll fix it
