### ISSUE TITLE
@JoinTable name is ignored

### ISSUE THREAD

**Issue by horvatb** [typeorm/typeorm#1390]
[0.2.0-alpha.13] [mssql 2017] Error: Referenced column ContentItemId was not found in entity **ContentTag**. Actually, in @JointTable **ContentItemTag** is specified. Error occurs on establishing a connection.

I couldn't do the many to many relationship with existent joint table. Portion of the code of my ContentTag class namely looks like following:

    @ManyToMany(type => ContentItem, contentItem => contentItem.tags, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    @JoinTable({name: "ContentItemTag",
        joinColumn: {
            name: "contentItem",
            referencedColumnName: "ContentItemId"
        },
        inverseJoinColumn: {
            name: "contentTag",
            referencedColumnName: "ContentTagId"
        }})
    contentItems: ContentItem[];

**Comment by horvatb** [comment]
We could establish many-to-many relationship via explicit (joint) Entity. In @JointTable, we used those names. In DB we used tables written with lower Caps (item, tag, item_tag). Also attributes are all lower-caps.

**Comment by pleerock** [comment]
Can you please provide more details on this? I just tried to reproduce this issue with no success - table `ContentItemTag` is created with `contentItem` and `contentTag` column names inside. Everything works as expected.

**Comment by pleerock** [comment]
Closing as no answer from reportee. Please let me know if you still have this issue.

**Comment by marianomoretti** [comment]
Hi all, just to let you know that this is still happening to me. I'm using this version: `"typeorm": "^0.2.11"`. I'm not adding code example because it's exactly the same issue. But let me know if you need me to add it. 

Thanks!

**Comment by marianomoretti** [comment]
@pleerock Hi all, just to let you know that this is still happening to me. I'm using this version: `"typeorm": "^0.2.11"`. I'm not adding code example because it's exactly the same issue. But let me know if you need me to add it.

Thanks!
