### ISSUE TITLE
Does TypeORM support polymorphic associations (Joined Subclass Strategy)?

### ISSUE THREAD

**Issue by YGolikov** [typeorm/typeorm#1393]
Does it support this decision or do it plan to support? 
Like this https://docs.oracle.com/javaee/6/tutorial/doc/bnbqn.html#bnbqu
thanks

**Comment by pleerock** [comment]
I guess Joined Subclass Strategy is a synonym for class table inheritance. No, we are not planning t support CTI. We had this pattern implemented before in earlier versions of typeorm, however we removed its support in latest versions. This pattern brings too much problems and restrictions to orm and for those users who really really want to have this complexity I recommend to implement this strategy manually.

**Comment by YGolikov** [comment]
Thank you!

**Comment by flisboac** [comment]
@pleerock Are there any examples of how such a strategy can be implemented in TypeORM? It's a very common inheritance pattern in relational-DB-based projects, or at least that has been my experience. It makes no sense for the library NOT to have support for this pattern.

Also, I came into TypeORM expecting it to be reasonably feature-complete, but now I discovered that it doesn't support the most common of patterns, and I'm way into development.

I understand that you may not like joined table, and you may have your reasons for that (which you didn't specify), but at the very least this should be documented front and center in the documentation. Either that, or give people some tips on how to proceed, if they decide to stick with TypeORM and roll out their own strategy.
