### ISSUE TITLE
How use MySQL datetime with TypeOrm?

### ISSUE THREAD

**Issue by Giancarlo1974** [typeorm/typeorm#1394]
Hi, your project is very well
I have some problems using MySQL DateTime coloumn in TypeORM

This is my Entity Persone.ts

    @Entity()
    export class Persone {
      @PrimaryGeneratedColumn() PERCOD: number;
      @Column({
        length: 100
      })
      @Column('text') EMAIL: string;
      @Column('text') PASSWORD: string;
      @Column('datetime') PASSWORD_RESET_EXPIRES: Date;
    }

I try to save in this mode:
import { getConnection } from 'typeorm';
import { Persone } from '../entity/Persone';

        const myConnection = getConnection('db');
        const userRepository = myConnection.getRepository(Persone);
		user = new Persone();
		user.EMAIL = 'bla bla bla';
		user.PASSWORD = 'bla bla bla';
		user.PASSWORD_RESET_EXPIRES = Date.now();
		myConnection.manager
		.save(user)
		.then(user => {
		  console.log('OK');
		})
		.catch(err => {
		  console.log('KO');
		});

I got this error:

    Connect
    500 TypeError: date.getUTCFullYear is not a function
       at Function.DateUtils.mixedDateToDate (....\node_modules\typeorm\util\DateUtils.js:45:34)
       at MysqlDriver.preparePersistentValue (....\node_modules\typeorm\driver\mysql\MysqlDriver.js:289:42)
       at ....\node_modules\typeorm\persistence\SubjectOperationExecutor.js:676:92
       at Array.forEach (<anonymous>)
       at SubjectOperationExecutor.<anonymous> (....\node_modules\typeorm\persistence\SubjectOperationExecutor.js:668:45)
       at step (....\node_modules\typeorm\persistence\SubjectOperationExecutor.js:32:23)
       at Object.next (....\node_modules\typeorm\persistence\SubjectOperationExecutor.js:13:53)
       at ....\node_modules\typeorm\persistence\SubjectOperationExecutor.js:7:71
       at Promise (<anonymous>)
       at __awaiter (....\node_modules\typeorm\persistence\SubjectOperationExecutor.js:3:12)

If i try to change Column definition

    @Column('integer') PASSWORD_RESET_EXPIRES: Date;

i see in the logs that typeorm save in this mode:

UPDATE `persone` SET `PASSWORD_RESET_TOKEN`=1514544351642

the application doesn't crash, but in MySQL i see that the column remains 0000-00-00 00:00:00

Can you help me?
It's a bug?
Where can I find a complete example to use MySQL and TypeORM?

**Comment by Giancarlo1974** [comment]
If i try to change into

    @Column() PASSWORD_RESET_EXPIRES: Date;

i got this error:

        [Node] (node:6248) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DataTypeNotSupportedError: Data type "" in "Persone.PASSWORD_RESET_EXPIRES" is not supported by "mysql" database.


If i try to change into

    @Column({ localTimezone: true }) PASSWORD_RESET_EXPIRES: Date;

i got this TSC compiling error:

    error TS2322: Type 'number' is not assignable to type 'Date'.
    src/entity/speedy/Persone.ts(24,13): error TS2345: Argument of type '{ localTimezone: boolean; }' is not assignable to parameter of type '(type?: any) => Function'.
      Object literal may only specify known properties, and 'localTimezone' does not exist in type '(type?: any) => Function'.

**Comment by Giancarlo1974** [comment]
If i try in this way:

    @Column('datetime') PASSWORD_RESET_EXPIRES: Date;

    user.PASSWORD_RESET_EXPIRES = new Date();

it works!!

Perhaps you should create some more examples in the documentation
However, the project is really beautiful
Compliments

**Comment by pleerock** [comment]
You need to setup reflect-metadata properly and tsconfig properly. There are docs how to setup them. If you do it properly you'll only need to do `@Column() PASSWORD_RESET_EXPIRES: Date;` without specifying a column type manually.
