### ISSUE TITLE
Mocha Test Failed - Cannot read property 'connect' of undefined

### ISSUE THREAD

**Issue by jmaicaaan** [typeorm/typeorm#1398]
Sample repository: https://github.com/jmaicaaan/typeorm-test-suite

I have two running tests, the first one is for the `GetUserController` and `PostUserController`, the first one executes successfully but on the `PostUserController` it fails and returns this error:

`(node:3168) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'connect' of undefined`

Actually the tests is successful when I removed the `before` hook inside the `getUser.controller.test.ts` which is to `POST` a user.
When I removed that hook, the tests run fine. What could be wrong?

Here are my test suites:

getUser.controller.test.ts

    import 'reflect-metadata';

    import { expect } from 'chai';
    import { httpMethods, setupTest, useChakramTo } from '../../lib/test-util';
    import { GetUserController, PostUserController } from './index';

    describe('getUserController', () => {

      setupTest([ GetUserController, PostUserController ]);

      describe('list of users', () => {
        before(async () => {
          console.log('3', 3);
          await useChakramTo(httpMethods.POST, 'users', {
            email: 'test-user-' + Date.now(),
            password: 'password123'
          });
          console.log('4', 4);
        });
        it('should get the list of users', async () => {
          let response = await useChakramTo(httpMethods.GET, 'users', {});
          // console.log('response', response);
          expect(response.statusCode).to.be.equal(200);
          expect(response.body).to.be.an('array');
          expect(response.body.length).to.not.equal(0);
        });
      });
    });

postUser.controller.test.ts

    import 'reflect-metadata';

    import { expect } from 'chai';
    import { httpMethods, setupTest, useChakramTo } from '../../lib/test-util';
    import { GetUserController, PostUserController } from './index';

    describe('postUserController', () => {

      setupTest([ GetUserController, PostUserController ]);

      describe('add user', () => {
        it('should add a user', async () => {
          let response = await useChakramTo(httpMethods.POST, 'users', {
            email: 'test-user-' + Date.now(),
            password: 'password123'
          });
          console.log('response', response.body);
          expect(response.statusCode).to.be.equal(200);
        });
      });
    });

test-util.ts

    import * as chakram from 'chakram';
    import { createExpressServer } from 'routing-controllers';
    import { Connection, createConnection } from 'typeorm';
    import { bootstrapContainers } from '../lib/bootstrap-containers';
    import { bootstrapDB } from '../lib/bootstrap-db';
    import { bootstrapServer } from '../lib/bootstrap-server';

    export enum httpMethods {
      GET = 'get',
      POST = 'post',
      PUT = 'put'
    }

    export async function useChakramTo(method: httpMethods, route: string, data?: any) {
      const port = process.env.PORT;
      try {
        let result = await chakram[method](`http://127.0.0.1:${port}/${route}`, data);
        if (result && result.response) {
          if (result.response.statusCode) {
            result.statusCode = result.response.statusCode;
          }
        }
        return result;
      } catch (error) {
        console.log('error while using chakram request');
        throw error;
      }
    }

    /**
    * Start up the connection on the API and to the database using the `before` and `after` 
    * hook of Mocha Unit Test API
    * @param controllers An array of controllers to be registered for the specific test suite
    */
    export function setupTest(controllers: any[]) {
      let expressServer: any;
      let databaseConnection: Connection;

      bootstrapContainers();

      /**
      * Todos: 
      *  - use a different config (eg: NODE_ENV=test) x
      *  - reset the database on every test suite x
      *  - add data before running a test suite to be less dependent on the database initial seed x
      *  - change also the PORT, make it dynamic or have a config base also x
      */

      // tslint:disable-next-line:arrow-parens
      before(async () => {
        console.log('1', 1);
        databaseConnection = await bootstrapDB();
        const express = bootstrapServer(controllers);
        expressServer = express.server;
      });

      after(async () => {
        if (databaseConnection && databaseConnection.isConnected) {
          await databaseConnection.close();
        }
        await expressServer.close();
      });
    }

**Comment by jmaicaaan** [comment]
Adding into that, this is happening inside the `PostgresDriver.js`. What instances is `_this.master` being undefined?
 
 ```
  /**
     * Obtains a new database connection to a master server.
     * Used for replication.
     * If replication is not setup then returns default connection's database connection.
     */
    PostgresDriver.prototype.obtainMasterConnection = function () {
        var _this = this;
        return new Promise(function (ok, fail) {
            _this.master.connect(function (err, connection, release) {
                err ? fail(err) : ok([connection, release]);
            });
        });
    };
```

**Comment by pleerock** [comment]
Spent an hour try to figure out what is going on in your repository. Please provide a small few files reproduction code repo.

**Comment by jmaicaaan** [comment]
@pleerock, I've removed few files which are not needed. Can you please take a look on it? Thank you very much.

**Comment by pleerock** [comment]
I dont see any changes in complexity reduction. Sorry but I cannot afford myself spending time figuring out what is going on in your codebases. Please create a single file reproduction without third party dependencies or a PR with a failing test.

**Comment by jmaicaaan** [comment]
Hi @pleerock, I've followed your comment to reduce the files and I think I can lead you into the issue. 
When I was moving everything into a single file I run my test to make sure I hit the "checkpoint" where I can see if something will fix while moving into single file. 

The problem I am encountering is in `getUserController.test.ts`, when I used the created controller <b> instead of imported controllers </b> it works. Both tests but when I use the imported controllers, it fails and can throws the error of ` Cannot read property 'connect' of undefined` already. What seems wrong with that?

`getUserController.test.ts`

    import 'reflect-metadata';

    import { expect } from 'chai';
    import { Body, createExpressServer, Get, JsonController, Post,
      useContainer as routingUseContainer } from 'routing-controllers';
    import { Container, Service } from 'typedi';
    import { Connection, createConnection, useContainer as ormUseContainer } from 'typeorm';
    import { OrmRepository } from 'typeorm-typedi-extensions';
    import { User } from './user.entity';
    import { UserRepository } from './user.repository';

    // Use the imported controller and the error will persist

    // import { GetUserController } from './controllers/getUser.controller'; 
    // import { PostUserController } from './controllers/postUser.controller';

    import * as chakram from 'chakram';

    @JsonController('/users')
    class GetUserController {

      constructor(
        @OrmRepository() private userRepository: UserRepository
      ) {}

      @Get()
      async execute() {
        const users = await this.userRepository.getUsers();
        return users;
      }
    }

    // tslint:disable-next-line:max-classes-per-file
    @JsonController('/users')
    class PostUserController {

      constructor(
        @OrmRepository() private userRepository: UserRepository
      ) {}

      @Post()
      async execute(
        @Body() user: User
      ) {
        try {
          const createdUser = await this.userRepository.save(user);
          return createdUser;
        } catch (error) {
          console.log('error', error);
          throw error;
        }
      }
    }

    /** UNIT TEST */

    describe('getUserController', () => {

      const port = 3001;
      let expressServer: any;
      let databaseConnection: Connection;
      let databaseConfig: any = {
        type: 'postgres',
        host: 'localhost',
        port: 5432,
        username: 'postgres',
        password: 'jmsantos17',
        database: 'sample-test',
        synchronize: true,
        logging: true,
        entities: [
          User
        ]
      };

      ormUseContainer(Container);
      routingUseContainer(Container);

      // tslint:disable-next-line:arrow-parens
      before(async () => {
        // create database connection
        databaseConnection = await createConnection(databaseConfig);

        // create express server
        const app = createExpressServer({
          controllers: [ GetUserController, PostUserController ]
        });

        const server = app.listen(port, () => {
          console.log(`The server is listening at http://localhost:${port}`);
        });
        expressServer = server;
      });

      after(async () => {
        if (databaseConnection && databaseConnection.isConnected) {
          await databaseConnection.close();
        }
        await expressServer.close();
      });

      describe('list of users', () => {
        before(async () => {
          await chakram.post(`http://127.0.0.1:${port}/users`, {
            email: 'test-user-' + Date.now(),
            password: 'password123'
          });
        });
        it('should get the list of users', async () => {
          let result = await chakram.get(`http://127.0.0.1:${port}/users`);
          expect(result.response.statusCode).to.be.equal(200);
          expect(result.body).to.be.an('array');
          expect(result.body.length).to.not.equal(0);
        });
      });
    });

`getUserController.ts - The imported controller`

    import 'reflect-metadata';

    import { Get, JsonController, useContainer as routingUseContainer } from 'routing-controllers';
    import { OrmRepository } from 'typeorm-typedi-extensions';
    import { UserRepository } from '../user.repository';

    @JsonController('/users')
    export class GetUserController {

      constructor(
        @OrmRepository() private userRepository: UserRepository
      ) {}

      @Get()
      async execute() {
        const users = await this.userRepository.getUsers();
        return users;
      }
    }

**Comment by pleerock** [comment]
did you resolve your issue?

**Comment by jmaicaaan** [comment]
Hi @pleerock , yes I have resolved the issue. My main issue was the `before` hook in my unit test where I am calling `createConnection` and closing it in the `after` hook. 

I had a problem with `Container` whereas I'm getting undefined from it. I think I'm getting the last value still.

**Comment by abcd-ca** [comment]
@jmaicaaan Do you remember what did you do to fix your problem?

**Comment by jmaicaaan** [comment]
@abcd-ca , I remember it was because of the wrong usage of the typeDI container. I was resetting it every after hooks of my unit tests. Therefore, the connection/s were cleared. 
I solved it by not clearing the typeDI container every after hooks of my tests rather by the start and end of **all the unit tests**. 
Let me know if that made sense.

**Comment by abcd-ca** [comment]
@jmaicaaan Thank you, I understand. In my case I solved it within my reset script which is only called in a global `beforeEach`. My steps are to,
1. init db
2. drop all known tables 
```
await connection.manager.query(`DROP TABLE IF EXISTS ${tableNamesCSV} CASCADE`);
```
3. close the connection, 
```
  const connection = getConnection();
  await connection.close();
  // creates the tables again
  await createConnection();
```
4. seed the db with new data

Another key was to rely on TypeORM's `getConnection()` function. You can check to see if it doesn't have a connection and conditionally call `await createConnection()` if not – after which `getConnection()` will have a connection.

**Comment by jmaicaaan** [comment]
No problem @abcd-ca ! The global hooks also work fine with me rather than on each hook of the test suite. 
Since the User is a reserved word, some people named their database table to Account instead. 
Glad you solved your problem. Thanks for sharing 👍👍👍
