### ISSUE TITLE
Does not save the object in the relationship

### ISSUE THREAD

**Issue by borzovplus** [typeorm/typeorm#1399]
I created relations objects one-to-one
![image](https://user-images.githubusercontent.com/17339900/34455351-7efbfa66-ed8e-11e7-8f23-d451a1c9654a.png)

![image](https://user-images.githubusercontent.com/17339900/34455353-87866720-ed8e-11e7-841f-1d07d852fc1c.png)

And I try to save user with existing promocode 
![image](https://user-images.githubusercontent.com/17339900/34455360-a2c14e38-ed8e-11e7-8174-2014780f5311.png)

But in DB there are not this data, only other fileds user saved. 
Database - mongodb

**Comment by pleerock** [comment]
Relations currently are rdbms-only feature, it does not work in mongodb.

**Comment by pablocarreraest** [comment]
@borzovplus  for this we need to make aggregation $lookup and use relationships in our entities as simple field without specify relationship.

**Comment by pablocarreraest** [comment]
@pleerock all relationship don't work for now in typeorm? also in entity declaration? for not embedded relationship.

Can you please explain what is the current status of mongodb in typeorm?

thanks. ✌️

**Comment by pleerock** [comment]
Current status of mongodb is basic support. Most of basic mongodb functionality is supported. Relations is an advanced topic, and in mongo it can be implemented, but implementation is quite complex since mongo is not a relational database. That's why relations are only supported in the rdbms right now.

**Comment by pleerock** [comment]
Closing. Relations support in mongodb is tracked in another issue.
