### ISSUE TITLE
Route to "ormconfig.json" malformed in Windows.

### ISSUE THREAD

**Issue by sandokanelcojo** [typeorm/typeorm#140]
Hi there

When trying to run the migs, if I use the default _ormconfig.json_ location, the route where typeORM looks for the file is: 
`'D:\Work\project\server/node_modules/D:\Work\project\server/ormconfig.json'`

It happens the same if I use the -cf flag, whatever I pass as the route is added to the node_modlues path, but it seems it's an **absolute** path, not **relative** one.

For example: `typeorm migrations:run --config '../config/ormconfig.json'`
Results in:  `'D:\Work\project\server/node_modules/D:\Work\project\server/../config/ormconfig.json'`

If you need me to test anything in particular just shout!
Cheers!

**Comment by eduardoweiland** [comment]
Seems to be hardcoded as `process.cwd() + "/" + argv.config` in all [command files](https://github.com/typeorm/typeorm/tree/master/src/commands). Maybe using [path.resolve()](https://nodejs.org/dist/latest-v6.x/docs/api/path.html#path_path_resolve_paths) solves this? It automatically preprends the current working dir, but only if it is not already an absolute path.

**Comment by sandokanelcojo** [comment]
Sure, I'll let you know ASAP.

**Comment by sandokanelcojo** [comment]
Hi again.

Thanks @eduardoweiland, unfortunely the problem is not in the path creation.

The require function expects (by default) a relative path, begining in the route of the project, or an absolute one, which must start with '/', in windows an absolute path starts with a drive letter (D in my case), so require interprets it to be relative and that's why I'm having troble.

As typeORM is generally installed as a global module it needs to access ormconfig.json in the actual project, so it must be an absolute route. require has only one param, a string, no flags or any way to tell it how to handle it.

I'm sure this can be done, but haven't succeeded yet
I'd appreciate any sugestions.

I'll let you know if I make any progress.

PS: "PlatformTools.load" is where the require is called.
PS2: That's what I get for using Windows! :P

**Comment by pleerock** [comment]
tested on my friend's windows machine and fixed in `0.0.6-alpha.3` 💃  . Please check it

**Comment by pleerock** [comment]
fixed in `0.0.6`

**Comment by sandokanelcojo** [comment]
I've tried it just now.
It works like a charm.
Thanks a lot.
