### ISSUE TITLE
Lost database connection crashes node app

### ISSUE THREAD

**Issue by xipheCom** [typeorm/typeorm#1400]
**Reproduction (just tried it with postgres only):**

start postgres server
start your typeorm application
stop postgres server ( (/etc/init.d/postgres stop)
--> app crashes

**Expected behavior:**

App do not crash but give us a way to react on this, e.g. try a reconnect after some time.

**Comment by xipheCom** [comment]
There is an error event in node-pg like this: pool.on('error', someErrorFunc). But i do not a way how it can be implemented within my own source code, because there is no way to access the pool object outside the postgres driver as far as I know. Is this correct?

The guys from knex.js had the same issue, perhaps it helps.

[knexjs issue](https://github.com/tgriesser/knex/issues/178)

Would be great if we can react on errors like this. E.g. subscribe to an connection observer like this

```typescript
createConnection().then(connection => {
    connection.connectionState.subscribe(isConnected => console.log(isConnected));
}
```

**Comment by xipheCom** [comment]
Was playing around with it and have it look what happens. I think someone have to add error handling into the driver. IsConnected is true, but should not be true on connection error:

```typescript
       //catch all node errors (in fact the error when stopping postgres)
       process.on('uncaughtException', function (err: any) {
            console.log("isConnected  ",  getConnection().isConnected) // -->this gives true here, should be false 
        });
```

**Comment by pleerock** [comment]
You can access connection pool from typeorm using following method:

```ts
const pool = (connection.driver as PostgresDriver).master;
// now you can do pool.on('error', ...)
```

Check if that helps you.

**Comment by xipheCom** [comment]
Works like a charm. Thank you @pleerock!

Just for completion for others: The PostgresDriver comes from pg:

```typescript
import { Driver as PostgresDriver } from "pg";
```

**Comment by xipheCom** [comment]
Just a hint for others: you have to close the connection with connection.close() within the error function.

**Comment by iamvsaini** [comment]
Hello @pleerock and @xipheCom, i am facing similar issue with my api in node connection is getting deactivated for first call after some inactivity like 30 min +, and it started working on immediate next call and works fine further, i am not able to resolve this issue... kindly please help me out of this issue

my connection is as below

```
createConnection(creteCon).then(async (connection: Connection) => {
  console.log('Connected to db :: ' + connection.isConnected);
}).catch((error: any) => console.log('TypeORM connection error: ', error));
```

and here is my node api code

```
CreateSession = async (req: Request, res: Response) => {
        const _session: any = req.body.session;

        await this._userService.CreateSession(_session).then((result: any) => {
            res.send(result);
        }).catch((error: any) => {
            console.log(`${this.TAG} CreateSession: ${error}`);
            res.send(error);
        });
    }
```

and here is my repository method

```
async CreateSession(session: SessionEntity) {
        const _sessionRepository = getRepository(SessionEntity);
        return await _sessionRepository.save(session)
            .then(async (_session: SessionEntity) => {
                await this.DestroySession({ UserGuid: _session.UserGuid }, _session.UserGuid);
                return await _sessionRepository
                    .createQueryBuilder('Session')
                    .where({ UserId: _session.UserId, IsActive: false })
                    .getOne()
                    .then(async (_lastSessionEntity: SessionEntity | undefined) => {
                        _session.LastSessionEndTime = _lastSessionEntity ? _lastSessionEntity.SessionEndTime : '';
                        return _session;
                    });
            })
            .catch((_error: any) => {
                console.log(`${this.TAG} CreateSession: ${JSON.stringify(_error)}`);
            });
    }
```
