### ISSUE TITLE
How to search an array in postgress using querybuilder

### ISSUE THREAD

**Issue by lalith26** [typeorm/typeorm#1401]
In one of my entity, I have the following type:
@Column({ type: 'uuid', array: true })
  problemIds: string[]

I am trying to save an array of uuids. It is getting saved as:
{e6bafc1f-e363-4476-af45-68e14b9bc97f,5818f621-7de3-4d28-83be-1b602adb7366}

Now I want to search this column using a specific value.
How can i achieve this using query builder? Please help

**Comment by pleerock** [comment]
it will be something like this:

```ts
const parameter = new ArrayParameter(["e6bafc1f-e363-4476-af45-68e14b9bc97f", "5818f621-7de3-4d28-83be-1b602adb7366");

queryBuilder.where("problemIds = ANY(:param)", { param: parameter });
```

**Comment by lalith26** [comment]
@pleerock From where do I import ArrayParameter?
I tried something like this:
const param = ["978cfb22-cd52-43e9-98e6-80190189fd36"]

it did not work..

**Comment by SergeyCherman** [comment]
Looks like it was added in next so hasn't hit master yet:
https://github.com/typeorm/typeorm/blob/next/src/query-builder/ArrayParameter.ts

**Comment by lalith26** [comment]
@pleerock when will next get merged with master..

**Comment by SergeyCherman** [comment]
You can follow the roadmap and instructions for using the next branch here: http://typeorm.io/#/roadmap

**Comment by lalith26** [comment]
@pleerock Even though ArrayParameter is added in next branch, it is not being exported.
https://github.com/typeorm/typeorm/blob/next/src/index.ts

How do we use this?

**Comment by pleerock** [comment]
`ArrayParameter` is a functionality which we are planning to refactor soon. It will probably be removed and instead some other simplified technique will be introduced. I suggest you to use `ArrayParameter` as a temporary solution and you can import it directly from its place:

```ts
import {ArrayParameter} from "typeorm/query-builder/ArrayParameter";
```

**Comment by pleerock** [comment]
As of `0.2.0-alpha.19` there is a proper array support in postgres, you don't need to use `ArrayParameter` anymore.
