### ISSUE TITLE
Slow queries

### ISSUE THREAD

**Issue by eyalhakim** [typeorm/typeorm#1402]
I have a query with many joins and on the `next` version it takes 3x more to execute.

**Comment by pleerock** [comment]
any real benchmarks and results?

**Comment by eyalhakim** [comment]
I can measure, how would you suggest doing it?

**Comment by eyalhakim** [comment]
@pleerock Do you have a suggestion?

**Comment by pleerock** [comment]
see #1115 as an example of amazing performance report from the community where we made a huge improvements on saving entities

**Comment by pleerock** [comment]
Closing as no answer from reporter.
