### ISSUE TITLE
Not created index in mongo

### ISSUE THREAD

**Issue by borzovplus** [typeorm/typeorm#1404]
I'm trying to create an index and a unique field for Mongo

![image](https://user-images.githubusercontent.com/17339900/34569973-789a70ee-f17b-11e7-9f25-02952c98c762.png)

But the index is not created, and the uniqueness is not working

![image](https://user-images.githubusercontent.com/17339900/34570022-9c5cdc1a-f17b-11e7-9a04-b1f89138262d.png)

typeorm version: 0.1.9

**Comment by thomaspons** [comment]
Same thing here, the index is not created. 

How can we create unique indexes for MongoDB using typeORM ? 

typeorm version: 0.2.1

**Comment by pleerock** [comment]
Can somebody provide a reproduction?

I just checked [this test](https://github.com/pleerock/typeorm/blob/03ceaeade0d93c0884d1a85910e1bdc3ae461761/test/functional/mongodb/basic/mongo-index/mongo-index.ts#L8-L7) and unique indices seems to work

![screenshot 2018-04-26 15 04 30](https://user-images.githubusercontent.com/1753397/39299835-25630680-4963-11e8-8474-54528af6a705.png)

**Comment by admosity** [comment]
Happening in 

node 9.10.0
typeorm 0.2.6
MongoDB server version: 3.6.5
nestjs 5

![image](https://user-images.githubusercontent.com/4655972/40564676-8cd2fca4-6037-11e8-848f-cc4577f41769.png)

![image](https://user-images.githubusercontent.com/4655972/40564683-93704eea-6037-11e8-9508-7952bd2f6913.png)

![image](https://user-images.githubusercontent.com/4655972/40564710-b3729428-6037-11e8-9db9-b30e4b4647af.png)

**Comment by pleerock** [comment]
To make indices to work you must have `synchronize: true` in your connection options.
