### ISSUE TITLE
Enhancement: CREATE DATABASE

### ISSUE THREAD

**Issue by Vandivier** [typeorm/typeorm#1406]
Today TypeORM can connect to an existing database, but afaik it does not allow you to create a database. This means we cannot have a full lifecycle DB which is configured-as-code. Is this feature request consistent with or out of scope for the vision of this library?

**Comment by pleerock** [comment]
I don't think we are going to implement this. Why? Because CREATE DATABASE needs privileges which usually absent in proper setup environments.

**Comment by Vandivier** [comment]
Obviously you could make it optional and fall back to the current assumption that it's already there

**Comment by pleerock** [comment]
what do you mean by "optional"? Add some flag in connection options for user that automatically creates it?

**Comment by Vandivier** [comment]
Let there be some method app.dataSources.makeDB(config)

If this method is called with a valid config object, drop specified DB if it exists and create the specified DB.

If this method is not called then proceed as currently implemented: assume datasources.json refers to a valid DB and if that is not the case then throw.

**Comment by pleerock** [comment]
If you are asking about "create database method", then it already exist in `QueryRunner` and its called `createDatabase`. But its not called inside ORM, you shall call it on your own.

**Comment by pleerock** [comment]
I think answer to original question was already given.
