### ISSUE TITLE
Create extension query fails in Postrges connection for any users w/o superuser rights

### ISSUE THREAD

**Issue by maxmalov** [typeorm/typeorm#1407]
I've found these little helpers to work with UUID and citext column types: 
https://github.com/typeorm/typeorm/blob/b96fc776cc37896b85cd3c21c2bc68655cc29bd9/src/driver/postgres/PostgresDriver.ts#L234
https://github.com/typeorm/typeorm/blob/b96fc776cc37896b85cd3c21c2bc68655cc29bd9/src/driver/postgres/PostgresDriver.ts#L236
 But in production database user doesn't have superuser rights to create any extensions in the database, so `executeQuery` will eventually fail. I'm wondering can these `executeQuery` calls be wrapped into a try-catch block and print some kind of warning message about required extensions in such situation?

**Comment by pleerock** [comment]
Yes, I think we can ignore this query. This is an easy fix and you can contribute on this issue.

**Comment by maxmalov** [comment]
Sure 👌, right after I return to my working environment
