### ISSUE TITLE
What kind of inheritance should I use?

### ISSUE THREAD

**Issue by pawlusmall** [typeorm/typeorm#1409]
I have the following entities:

- Event (id, type, action_id)
- Action (id, type, parameters...)

For that Action entity I will have many action types, each one with many different number of parameters. For example:

- ActionShow(id, element_id)
- ActionHide(id, element_id)
- ActionAnimate(id, element_id, loop, start_at) ...

I think the natural approach would be using Class-type inheritance using the Action type as discriminator column and sharing the id of the Action class to the specific actions.

But I've read typeorm has some issues with this kind of inheritance, what should I use then?

Thanks.

**Comment by pawlusmall** [comment]
I think the best approach would be STI (Single Table Inheritance). I will break normalization but at least I don't have to deal with null values.

One question, If I use this kind of inheritance, can I use as JoinColumn a base class? i.e the Action above.

**Comment by pawlusmall** [comment]
Ok, I see in other issues that both CTI and STI are not supported and we should implement that functionality ourselves.

You can close this.

**Comment by pleerock** [comment]
STI is supported in `next` branch (`npm i typeorm@next`). See example [here](https://github.com/typeorm/typeorm/tree/next/sample/sample28-single-table-inheritance).

Previously we had CTI supported but it bring too much issues and limitations and we decided to remove CTI support.

**Comment by pawlusmall** [comment]
Would you recommend it or its better to develop my own. I will use it in a production environment.

Thanks.

**Comment by pleerock** [comment]
Personally I use `next` in a production environment. Of course using ORM's provided STI mechanism is better for you until you don't have something not supported by ORM. Implementing your own STI may become a bit complicated.

**Comment by pawlusmall** [comment]
Whats the difference of the next branch? in addition to the STI ...

**Comment by pleerock** [comment]
lot of changes and improvements, you can read [changelog here.](https://github.com/typeorm/typeorm/blob/next/CHANGELOG.md)
