### ISSUE TITLE
Loading a relation should load that relations eager relations

### ISSUE THREAD

**Issue by BrainMaestro** [typeorm/typeorm#1416]
I have a case where there is a relationship between two entities (`User` and `Photo`). `Photo` meanwhile has an eager relationship with `PhotoMetadata`. If I run this query,  
```js
const user = userRepository.find({ where: { id: 1}, relations: ['photo'] })

// I should be able to access this
user.photo.photoMetadata
```

shouldn't the `Photo` that gets joined with `User` have `PhotoMetadata` eagerly loaded? Currently, the eager relations for the relation are ignored

**Comment by pleerock** [comment]
If `PhotoMetadata` in `Photo` is set by { eager: true } then it should be loaded as well. Looks like not a hard fix, are you able to implement it?

**Comment by BrainMaestro** [comment]
I'll try to implement it. 

From a quick glance, It looks like I would need to move [`joinEagerRelations`](https://github.com/typeorm/typeorm/blob/master/src/entity-manager/EntityManager.ts#L869) to FindOptionUtils so that I can call it in the `[applyRelationsRecursively]`(https://github.com/typeorm/typeorm/blob/master/src/find-options/FindOptionsUtils.ts#L186) function.

Is that ok?

**Comment by pleerock** [comment]
Looks so

**Comment by BrainMaestro** [comment]
Alright, should this be going against the `next` branch?

**Comment by pleerock** [comment]
this can be master as well since its not a breaking change

**Comment by BrainMaestro** [comment]
Oh and btw @pleerock I just noticed that the tests on the next branch seem to be broken. A cascade issue, but gulp isn't reporting a failure correctly for some reason. The tests for this issue are fine, but it's pretty strange. See the [logs](https://travis-ci.org/typeorm/typeorm/jobs/327138773#L2054). It should fail, but as you can, the build succeeded

**Comment by pleerock** [comment]
ooups yes. We'll need to investigate why gulp does not report failture correctly. Looks like your PR break things, can you please fix them?

**Comment by BrainMaestro** [comment]
No, the break is not actually from my PR. It's there in the [version bump commit](https://travis-ci.org/typeorm/typeorm/jobs/324103326#L2042), so it must've been introduced before

**Comment by matgott** [comment]
Sorry, I'am having this problem right now. I have:

`@Entity()
export class User extends IEntity {
  @ApiResponseProperty()
  @OneToOne(() => CompanyBranch, { eager: true })
  @JoinColumn({ name: 'company_branch_id' })
  companyBranch: CompanyBranch;
}`

`@Entity()
@Unique('unique_branch_company', ['name', 'company.id'])
export class CompanyBranch implements IEntity {
  @ManyToOne(() => Company, { eager: true })
  @JoinColumn({
    name: 'companyId',
  })
  company: Company;
}`

If I do a .find on CompanyBranch, I receive the company data. But when I do a .find over User, its only getting companyBranch data and not company. It not triggering the eager on company.
