### ISSUE TITLE
createConnection() option aliases to match MySQL connection options

### ISSUE THREAD

**Issue by Ionaru** [typeorm/typeorm#1417]
For my project I'm creating two MySQL connections: one for Express sessions and one for TypeORM. Currently I have to define the connection options twice because the MySQL options and TypeORM options are not compatible with each other.

My suggestion is to add aliases to the TypeORM connection option keys so when I pass the MySQL connection options to TypeORM it works, but without breaking the current key name.

Currently these fields are incompatible:

TypeORM | MySQL
------------ | -------------
`username` | `user`
`type` | `dialect`

I'm not sure about the other Database types and what fields they use, but as a MySQL user this would really help with the amount of code I need in my database configuration.

**Comment by pleerock** [comment]
No, of course not. This is your own use case and such transformation needs to be in your codebase. Plus as you guess different databases have different connection signatures.
