### ISSUE TITLE
innerJoinAndSelect with no matching rows results in rejected promise

### ISSUE THREAD

**Issue by royibernthal** [typeorm/typeorm#142]
Hi,

There's a OneToMany relation between "ent" (one) and "some_stuff" (many).

I'm doing something similar to this:

```
entRepository.createQueryBuilder('ent')
	.innerJoinAndSelect('ent.some_stuff', 'some_stuff')
	.getOne();
```

Whenever some_stuff has corresponding rows for ent, it works.
Whenever there're no corresponding rows for ent, the promise is rejected.

How can I simply have some_stuff set to an empty array in ent whenever there're no corresponding rows instead of having the promise rejected?

**Comment by eduardoweiland** [comment]
If you want to get the result for `ent` when it does not have any `some_stuff`, you should use a `LEFT JOIN`. When doing an `INNER JOIN`, the database will not return the `ent` row if it does not have corresponding rows in the joined table.

@royibernthal can you try using `leftJoinAndSelect` and see if it works?

```typescript
entRepository.createQueryBuilder('ent')
	.leftJoinAndSelect('ent.some_stuff', 'some_stuff')
	.getOne();
```

**Comment by royibernthal** [comment]
True, works.

Is that the only difference between innerJoinAndSelect and leftJoinAndSelect?
Is there a reason not to always use leftJoinAndSelect?

**Comment by pleerock** [comment]
yes. same applies for `INNER JOIN` vs `LEFT JOIN` in SQL.

**Comment by royibernthal** [comment]
Thanks
