### ISSUE TITLE
Delete from manytomany relation

### ISSUE THREAD

**Issue by jondediego** [typeorm/typeorm#1420]
Hi,
I want to remove some elements from a manytomany relation.I have read that cascadeRemove isn't available for manytomany relations. So I want to access the repository of the table that represents the manytomany relation in order to remove them. Is that possible? Or should I use entityManager raw query?

**Comment by pleerock** [comment]
do you mean remove from many-to-many table or remove entities which are bind to the relation?

**Comment by jondediego** [comment]
I want to remove them from the many to many table

**Comment by pleerock** [comment]
rows are automatically removed from the many to many table when you detach them and save object.

**Comment by jondediego** [comment]
You are right. I tested yesterday and I thought it didn't work autommatically, but I have tested it today and it does, so my test yesterday was probably wrong

**Comment by kaveh981** [comment]
I have the same question but would you please tell me how do you detach the relations?

**Comment by zhenwenc** [comment]
Its been a while, but in case any newcomers are searching for the same problem. I have found the solution from this test case: [query-builder-relational-add-remove-many-to-many](https://github.com/typeorm/typeorm/blob/master/test/functional/query-builder/relational/with-many/query-builder-relational-add-remove-many-to-many.ts#L214).

Another solution would be (I haven't test this):
- Query the entity with `relations`, like [here](https://github.com/typeorm/typeorm/blob/master/test/functional/query-builder/relational/with-many/query-builder-relational-add-remove-many-to-many.ts#L49)
- Remove (aka detach) the relations from the array (in application)
- `save` the entity, typeorm knows what to do (hopefully).

**Comment by MOIN-AKHTAR** [comment]
Hello devs, i need help in case of many to many it's become difficult  as you may knew that we can use cascade option on one side where we use JoinTable decorator  so if i delete that side where i do have cascade property it will work but if i delete that side where i wasn't able to set property cascade it will mess up.This is where i am being stcuk.
