### ISSUE TITLE
.save() modifies the object that is passed. It should return a copy.

### ISSUE THREAD

**Issue by CaptJakk** [typeorm/typeorm#1421]
This seriously messes with anyone who is trying to program with pure functions. If people wanted to an actual modification, it wouldn't be hard to simulate that behavior if the function returned a copy.

**Comment by pleerock** [comment]
It could also mess anyone who is using object-oriented approach. 

Copying instances is **hard** and its a **highly expensive operation**. ORM is about object relations, and it suppose a circular references which are very very problematic to copy.

I would stay with current approach and suggest to manually copy object before passing it to save function.

**Comment by hesxenon** [comment]
@pleerock you cannot be serious, copying instances is hard and highly expensive?
```typescript
function deepClone<T extends ObjectLiteral>(o: T): T {
  const copy = {...o}
  for(let key in copy) {
    if(typeof copy[key] === "object") {
      copy[key] = deepClone(copy[key])
    }
  }
  return copy
}
```

As for the highly expensive part, see below and keep in mind we're talking about a save operation here. Do you save 200k objects per second?

> It could also mess anyone who is using object-oriented approach.

If anyone relies on a mutation inside a function that is not even prefixed with "enrich" and the likes, they really deserve to be broken by minor changes inside the implementation.

> ORM is about object relations

so? Object relations aren't necessarily tied to OOP?

related infos:
[why this is a bad idea](https://softwareengineering.stackexchange.com/questions/245767/is-modifying-an-incoming-parameter-an-antipattern)
[it's not performance expensive](https://github.com/davidmarkclements/v8-perf)
[it's not performance expensive](https://jsperf.com/deep-copy-vs-json-stringify-json-parse/5) (close to 200k ops/second)

**Comment by CaptJakk** [comment]
I actually just stopped using this library altogether because of this issue.

**Comment by hesxenon** [comment]
understandable and will probably do the same
