### ISSUE TITLE
Invalid UPDATE query when using Partial and isArray

### ISSUE THREAD

**Issue by felipesabino** [typeorm/typeorm#1430]
Query parameters are parsed wrongly when using `Partial<Entity>` in field with `isArray` option.

I managed to isolate part of my current code base that replicates the issue:

```typescript
// Entity

@Entity()
export class MyEntity {

  @PrimaryGeneratedColumn()
  id: number;

  @Column('varchar', { isArray: true, nullable: true })
  phones: string[];

}

@Service() // from typedi
class MyEntityDataSource  {

  constructor(
    @OrmRepository(MyEntity) ormRepository: Repository<MyEntity>,
  )

  patch(id: number, data: Partial<MyEntity>): Promise<void> {
    return await this.ormRepository.manager.transaction(async transaction => {
	  // ...
      return await transaction.updateById(this.ormRepository.target, id, data);
    });
  }
}

const datasource: MyEntityDataSource = ... // get MyEntityDataSource instance via typedi

const id = 1;
const phones = ['x', 'y'];

datasource.patch(id, { phones: phones });
// Error with query: 
// UPDATE "my_entity" SET "phones" = $1, $2 WHERE "id"=$3 -- PARAMETERS: ["x","y",1]

```

I suspect that the parameters are being flattened somewhere. 

It seems that the flattening is being done only for the first array level and a possible workaround is to send the array parameter inside another array, example:

```

// Versus:

datasource.patch(id, { phones: ([phones] as any) }); // Works as expected

```

---

Database: PostgreSQL `9.6`
TypeORM version:  `0.1.11`

**Comment by pleerock** [comment]
Thats because of how we handled array parameters before for drivers which do not support arrays like mysql and others. This does not have easy fix in `0.1.x` and will not have since proper fix will bring a breaking change. In `0.2.0-alpha` there is a class called `ArrayParameter` which may fix your problem. If you can upgrade to `next` try following code:

```ts
datasource.patch(id, { addresses: new ArrayParameter(phones) });
```

**Comment by pleerock** [comment]
This was fixed in `0.2.0-alpha.19`. `ArrayParameter` was removed, now simply pass an array.

**Comment by Aupajo** [comment]
@pleerock Is `@Column('text', { isArray: true })` no longer supported?

**Comment by Aupajo** [comment]
Ah, never mind. It should be `@Column('text', { array: true })`.

**Comment by odykyi** [comment]
node_modules/typeorm/decorator/options/ColumnOptions.d.ts

    /**
     * Indicates if this column is an array.
     * Can be simply set to true or array length can be specified.
     * Supported only by postgres.
     */
    array?: boolean;
