### ISSUE TITLE
Data type "" in "User.firstName" is not supported by "sqlite" database.

### ISSUE THREAD

**Issue by JeongJun-Lee** [typeorm/typeorm#1434]
typeorm: 0.1.9
electron: 1.7.9
sqlite3: 3.1.13

I generated a sample code by typeorm init command of typeorm cli and merged to electron code to test if it works well with electron. 
I can see the warning on the console but the User data will insert into the sqlite database normally. Why does this warning is shown to me? Thanks.

executing query:  BEGIN TRANSACTION
**(node:33723) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DataTypeNotSupportedError: Data type "" in "User.firstName" is not supported by "sqlite" database.
(node:33723) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**
executing query:  SELECT * FROM sqlite_master WHERE type = 'table' AND name IN ('user')
executing query:  PRAGMA table_info("user")
executing query:  PRAGMA index_list("user")
executing query:  PRAGMA foreign_key_list("user")
executing query:  COMMIT
Inserting a new user into the database...
executing query:  BEGIN TRANSACTION
executing query:  INSERT INTO "user"("firstName", "lastName", "age") VALUES ($1,$2,$3) -- PARAMETERS: ["Timber","Saw",25]
executing query:  COMMIT

**Comment by pleerock** [comment]
Where is your CREATE TABLE "user" query in the log? Does it create a table for you or do you already have such table in the database? Can you remove user table rerun and show query with create table?

**Comment by JeongJun-Lee** [comment]
I am reusing sqlite database file, not from new. And I removed user table in the database as your request and have got the new log like below:

executing query:  BEGIN TRANSACTION
(node:33930) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DataTypeNotSupportedError: Data type "" in "User.firstName" is not supported by "sqlite" database.
(node:33930) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
executing query:  SELECT * FROM sqlite_master WHERE type = 'table' AND name IN ('user')
creating a new table: user
executing query:  CREATE TABLE "user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "firstName"  NOT NULL, "lastName"  NOT NULL, "age"  NOT NULL)
executing query:  COMMIT
Inserting a new user into the database...
executing query:  BEGIN TRANSACTION
executing query:  INSERT INTO "user"("firstName", "lastName", "age") VALUES ($1,$2,$3) -- PARAMETERS: ["Timber","Saw",25]
executing query:  COMMIT

**Comment by pleerock** [comment]
can you show your entity?

**Comment by JeongJun-Lee** [comment]
in User.ts:

import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

@Entity('user')
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    age: number;

}

After being transpiled, in User.js:

"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
var typeorm_1 = require("typeorm");
var User = /** @class */ (function () {
    function User() {
    }
    __decorate([
        typeorm_1.PrimaryGeneratedColumn(),
        __metadata("design:type", Number)
    ], User.prototype, "id", void 0);
    __decorate([
        typeorm_1.Column(),
        __metadata("design:type", String)
    ], User.prototype, "firstName", void 0);
    __decorate([
        typeorm_1.Column(),
        __metadata("design:type", String)
    ], User.prototype, "lastName", void 0);
    __decorate([
        typeorm_1.Column(),
        __metadata("design:type", Number)
    ], User.prototype, "age", void 0);
    User = __decorate([
        typeorm_1.Entity('user')
    ], User);
    return User;
}());
exports.User = User;
//# sourceMappingURL=User.js.map

**Comment by pleerock** [comment]
Can you try implicitly set column types:

```
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

@entity('user')
export class User {

@PrimaryGeneratedColumn()
id: number;

@Column("varchar")
firstName: string;

@Column("varchar")
lastName: string;

@Column("integer")
age: number;
}
```

**Comment by JeongJun-Lee** [comment]
Good! Disappeared warning. What's the reason?

**Comment by pleerock** [comment]
two reasons: you did not enable options specified in README or you did not include `reflect-metadata` properly. You need to put `import "reflect-metadata";` before everything else in your app, before any entity loaded.

**Comment by JeongJun-Lee** [comment]
right. I missed including 'reflect-metadata'. Thanks a lot. I'll close this issue.
