### ISSUE TITLE
[Feature Request] Could you give me a chance to utilize a encrypted sqlite databases?

### ISSUE THREAD

**Issue by JeongJun-Lee** [typeorm/typeorm#1437]
I am making a Electron App with TypeORM, but we need to protect the sqlite database file by being encrypted with SQLCipher library(https://github.com/sqlcipher/sqlcipher). Is it possible to work with TypeORM in near future? Very thanks.

**Comment by pleerock** [comment]
As I understood `sqlcipher` is alternative to `sqlite` package. We already support both `mysql2` and `mysql` packages at the same time for mysql support. We can do same for `sqlcipher`. Feel free to contribute, its easy feature to implement.

**Comment by pleerock** [comment]
Closing as no answer from reporter.
