### ISSUE TITLE
error at relaunch the app with relations many to one / one to many (ionic 2)

### ISSUE THREAD

**Issue by isadev** [typeorm/typeorm#1440]
Hi.
Im having a issue with the typeorm with ionic and the relation many to one.
Im doing this
1.- create table user and photo
1.1.- launch the app with
ionic cordova run android --emulator --debug
-> Result : all ok

2.- relaunch the app with the same tables with no change in anywhere
-> Result : not ok (vendor.js:25828 query failed: DROP TABLE "user")
3.- rename the table user to usr
-> Result : all ok

The relations are : 
```
import {Entity, PrimaryGeneratedColumn, Column, ManyToOne} from "typeorm";
import {User} from "./User";

@Entity('photo')
export class Photo {
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    url: string;
    
    @ManyToOne(type => User, user => user.photos)
    user: User;
}
```
and 

```
import {Entity, PrimaryGeneratedColumn, Column, OneToMany} from "typeorm";
import {Photo} from "./Photo";

@Entity('user')
export class User {
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    name: string;
    
    @OneToMany(type => Photo, photo => photo.user)
    photos: Photo[];    
}
```
this is the output 

```
executing query:  CREATE TABLE "temporary_user" ()
vendor.js:25828 query failed:  CREATE TABLE "temporary_user" ()PlatformTools.logError @ vendor.js:25828AdvancedConsoleLogger.logQueryError @ vendor.js:115145(anonymous function) @ vendor.js:175177myerror @ SQLitePlugin.js:257SQLitePluginTransaction.handleStatementFailure @ SQLitePlugin.js:402(anonymous function) @ SQLitePlugin.js:423mycb @ SQLitePlugin.js:466callbackFromNative @ cordova.js:294(anonymous function) @ VM326:1
vendor.js:25828 error:  Object {message: "sqlite3_prepare_v2 failure: near ")": syntax error", code: 5}PlatformTools.logError @ vendor.js:25828AdvancedConsoleLogger.logQueryError @ vendor.js:115146(anonymous function) @ vendor.js:175177myerror @ SQLitePlugin.js:257SQLitePluginTransaction.handleStatementFailure @ SQLitePlugin.js:402(anonymous function) @ SQLitePlugin.js:423mycb @ SQLitePlugin.js:466callbackFromNative @ cordova.js:294(anonymous function) @ VM326:1
vendor.js:25825 executing query:  ROLLBACK
SQLitePlugin.js:226 CLOSE database: test
SQLitePlugin.js:229 closing db with transaction queue length: 0
vendor.js:1703 ERROR Error: Uncaught (in promise): QueryFailedError: sqlite3_prepare_v2 failure: near ")": syntax error(…)defaultErrorLogger @ vendor.js:1703ErrorHandler.handleError @ vendor.js:1764IonicErrorHandler.handleError @ vendor.js:163941next @ vendor.js:5729schedulerFn @ vendor.js:4576SafeSubscriber.__tryOrUnsub @ vendor.js:39604SafeSubscriber.next @ vendor.js:39551Subscriber._next @ vendor.js:39491Subscriber.next @ vendor.js:39455Subject.next @ vendor.js:55721EventEmitter.emit @ vendor.js:4556(anonymous function) @ vendor.js:5004t.invoke @ polyfills.js:3r.run @ polyfills.js:3NgZone.runOutsideAngular @ vendor.js:4930onHandleError @ vendor.js:5004t.handleError @ polyfills.js:3r.runGuarded @ polyfills.js:3(anonymous function) @ polyfills.js:3n.microtaskDrainDone @ polyfills.js:3o @ polyfills.js:3
SQLitePlugin.js:136 cannot start next transaction: database not open
```

im with 
ionic 2, 
angular 2,
typeorm 0.1.10,
cordova 7.1.0,

Is some kind of bug?

ill be waiting

**Comment by kadupenido** [comment]
Are you using websql?
From what I've been reading, the synchronization option with websql is still not stable, you have to mark it as false and create the tables manually.

Correct me if I'm wrong...

```
      const runner = connection.createQueryRunner();

      const userTable = new Table(
        'user',
        [
          { name: 'id', type: 'integer', isNullable: false, isPrimary: true, isGenerated: true },
          { name: 'name', type: 'varchar(128)', isNullable: false },
          { name: 'active', type: 'boolean', isNullable: false }
        ]
      )

      if (!(await runner.hasTable('user'))) {
        await runner.createTable(userTable);
      }
```

**Comment by daniel-lang** [comment]
@kadupenido is right about websql but looking at the output you provided you are using the `cordova` driver and one of the plugins, right?
Could yo provide the part of your code where you make your connection to the database?

**Comment by isadev** [comment]
Hi. Sorry the late response
Im using the conection in the app.components.js like the documentation says, and inside of any js,like home.js
im using this code 
```
const user = new User();
user.name = "my new name in 2018";

const user_Repo = getRepository('user') as Repository<User>;
await user_Repo.save(city);
```
I solve the issue erasing the data of the app everytime i launch it, but is a little weir to do that

**Comment by daniel-lang** [comment]
Did you use the `app.component.ts` from the ionic example or which file are you refering to?
Could you provide your `app.component.js`? Because the ionic example doesn't have that issue.

**Comment by isadev** [comment]
my app.components.js
```
import { createConnection } from 'typeorm'
import { Photo } from '../entities/Photo';
import { User } from '../entities/User';
....

constructor(){
this.initializeApp();
}

initializeApp() {
    this.platform.ready().then(async () => {
      await createConnection({
        type: 'cordova',
        database: 'test',
        location: 'default',
        logging: ['error', 'query', 'schema'],
        synchronize: true,
        entities: [
           Photo, User
        ]
      });
   });
  }
```

and inside home.js

```
import { getRepository, Repository } from 'typeorm';
import { User } from '../../entities/User';
....
async create(){
  const user = new User();
  user.name = "user 1";

  const user_Repo = getRepository('user') as Repository<User>;

  await user_Repo.save(user);
}
```

**Comment by daniel-lang** [comment]
Could you put together a small repo for me to reproduce your issue? Because the current cordova driver shouldn't produce `CREATE TABLE` statements without columns like yours.
Are you actually using Ionic 2.x and Angular 2.x or just the version after 1.x (ionic 3.x and angular 4.x)?

**Comment by aluco100** [comment]
I'm using the following method and it's works for me:

```
const options: ConnectionOptions = {
  type: 'cordova',
  database: 'data',
  location: 'default',
  logging: ['error', 'query', 'schema'],
  synchronize: true,
  entities: [
    Post,
    Tag
  ]
}

/.../

async createScheme(connectionOptions: ConnectionOptions = options) {
    await createConnection(connectionOptions).then(connection => {
      this.connection = connection;
    }).catch(async error => {
      console.log("ERROR in SCHEME: "+error);
      this.connection = await createConnection({
        type: 'cordova',
        database: 'data',
        location: 'default',
        logging: ['error', 'query', 'schema'],
        synchronize: false,
        entities: [
          Post,
          Tag
        ]
      })
    });
  }
```

**Comment by isadev** [comment]
Hi again, sorry the late response.
A friend has detected what was the problem, it seems that the version 0.1.7 works perfectly, but in the later versions 0.1.11 something have been left behind because the behavior that i describe here, isnt present in the version 0.1.7 ... this afternon ill up a repo with the latest version and some example.

**Comment by daniel-lang** [comment]
@isadev I'm not able to reproduce your issue. Running typeorm@0.1.11 with the entity you have and the cordova-sqlite-storage@2.2.0 everything works.
What database type/driver are you using? Cordova?

**Comment by isadev** [comment]
Hi @daniel-lang , sorry the late response.
Here are the repo with the same issue.
Additional to that, the option of "cascade*" cant use it, so i have to erased the relation the old way.
Hope you can help me =(

Here the repo -> https://github.com/isadev/ionic_typeorm_test/tree/master

**Comment by isadev** [comment]
Hi.
So with a friend we figured out how to solve this issue. Exist an option called 

```onDelete : "CASCADE" ```

with only that option the schema works just fine.
Im gonna close this. 
Thanks in advance =)

**Comment by MoustafaElkady** [comment]
@aluco100 could you please provide simple explanation of that code ?

**Comment by alfredolucomav** [comment]
Hi @MoustafaElkady ,

You can saw the full code here:  https://github.com/aluco100/TypeORMIONICMigrationSample
