### ISSUE TITLE
Columns without specified types throws promise rejections for postgres

### ISSUE THREAD

**Issue by crutchcorn** [typeorm/typeorm#1448]
If I'm understanding correctly, I should be able to do something like this:
```
    @Column()
    text: string;
```

In a model definition and still have the type be infered by TypeORM (stop me dead in my tracks if I'm wrong). However, when I do this, I get the following errors from Node:
```
(node:540) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DataTypeNotSupportedError: Data type "undefined" in "Post.text" is not supported by "postgres" database.
```

**Comment by mscharley** [comment]
I've noticed this seems to happen if your connection is misconfigured. More worryingly though, these unhandled rejections seem to come from inside TypeORM and there's no way to get at them to actually assert an error in the application even though TypeORM is probably in an undefined state after running into one of these.

**Comment by mscharley** [comment]
Similar issue:

```
(node:3329) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): DataTypeNotSupportedError: Data type "" in"NotificationStream.active" is not supported by "sqlite" database.
```

In my case, `active` is a boolean type which is indeed unsupported by `sqlite` and hence doesn't have a sane default type column type.

**Comment by crutchcorn** [comment]
@mscharley perhaps you could take a quick look and see if there is something wrong with the config that I didn't catch? 
https://github.com/crutchcorn/PET-Template/tree/auth?files=1

Additionally, the default for string could easily be many things for Postgres, so it's difficult to hear that there wouldn't be a sane default type (for my use case anyway)

**Comment by mscharley** [comment]
```
     DataTypeNotSupportedError: Data type "" in "NotificationStream.active" is not supported by "sqlite" database.
      at DataTypeNotSupportedError.Error (native)
      at new DataTypeNotSupportedError (src/error/DataTypeNotSupportedError.ts:9:9)
      at src/metadata-builder/EntityMetadataValidator.ts:78:27
      at Array.forEach (native)
      at EntityMetadataValidator.validate (src/metadata-builder/EntityMetadataValidator.ts:75:36)
      at src/metadata-builder/EntityMetadataValidator.ts:39:56
      at Array.forEach (native)
      at EntityMetadataValidator.<anonymous> (src/metadata-builder/EntityMetadataValidator.ts:39:25)
      at step (node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:32:23)
      at Object.next (node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:13:53)
      at node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:7:71
      at __awaiter (node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:3:12)
      at EntityMetadataValidator.validateMany (node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:70:16)
      at Connection.buildMetadatas (src/connection/Connection.ts:474:33)
      at Connection.<anonymous> (src/connection/Connection.ts:171:18)
      at step (node_modules/typeorm/connection/Connection.js:32:23)
      at Object.next (node_modules/typeorm/connection/Connection.js:13:53)
      at fulfilled (node_modules/typeorm/connection/Connection.js:4:58)
```

This is the stacktrace from my error that wasn't being handled correctly by TypeORM.

@crutchcorn I use strings with `postgres` without specifying types - so that should definitely work. The only thing that looks out of place is that I'm not sure if `ormconfig.json` should have an array as the top level element.

For reference, here's my configuration:

```typescript
import { ConnectionOptions } from "typeorm";
import { entities } from "../entities/typeorm";

// tslint:disable:object-literal-sort-keys
// tslint:disable:strict-boolean-expressions

const localConfiguration: ConnectionOptions = {
  type: "postgres",
  database: "postgres",
  host: "db",
  port: 5432,
  username: "postgres",
  password: "mobile-api",
  logger: "advanced-console",
  logging: "all",
  maxQueryExecutionTime: 100,
  entities,
  migrations: ["migrations/*.ts"],
  migrationsRun: false,
  synchronize: false,
};
```

**Comment by crutchcorn** [comment]
@mscharley According to the docs, an array should work fine:
http://typeorm.io/#/using-ormconfig/loading-from-ormconfigjson

**Comment by pleerock** [comment]
> DataTypeNotSupportedError: Data type "" in "NotificationStream.active" is not supported by "sqlite" database

this error means reflect-metadata is not setup correctly

**Comment by mscharley** [comment]
Hi @pleerock, this is definitely one cause, but not the cause in this case. When I am using the `postgres` database driver it doesn't complain about this with the same mocha setup, which includes the following `mocha.opts`:

```
--ui mocha-typescript
--require ts-node/register
--require source-map-support/register
--require dotenv/config
--watch-extensions ts
src/**/*.spec.ts
```

Also, the fact that this is an unhandled promise rejection is also really bad as a client of your library. There is a fundamental error in the metadata of the database connection layer but I have no way of detecting or handling this currently.

**Comment by mscharley** [comment]
Hmm, I just realised that `reflect-metadata` isn't in that list. But the postgres version is working fine, so I'm not sure if that's actually the issue or not. Regardless, the metadata being missing shouldn't cause an unhandled promise rejection - this is a crash bug in the latest versions of node.

**Comment by pleerock** [comment]
if you want me to help create a git repo with **minimal** reproduction of your issue, I'll clone and test it.

**Comment by mscharley** [comment]
https://github.com/mscharley/typeorm-unhandled-promise-error

**Comment by pleerock** [comment]
its a bug, it was already fixed in `next`. I'll also publish a 0.1.12 with this fix

**Comment by mscharley** [comment]
@pleerock when will this hit a production release>

**Comment by pleerock** [comment]
I plan in March.

**Comment by mscharley** [comment]
That is over a month away - what should we do in the meantime to help deal with this bug which causes our application to do strange things if we make a small mistake in our entity declarations? Is this any particular reason to hold off for so long?

**Comment by pleerock** [comment]
ah wait, I thought you are talking about `next` branch. I'll release 0.1.12 with this change today.

**Comment by mscharley** [comment]
Thanks! That'd be much appreciated.

**Comment by pleerock** [comment]
0.1.12 is released btw

**Comment by crutchcorn** [comment]
0.1.12 made my program go from thowing warnings and continuing to hard exiting. My issue has not been resolved.
Once again, in the model:
```typescript
@Entity()
export class Category {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;
}
```

Category.name is being described as `undefined`

**Comment by crutchcorn** [comment]
This behavior is still found in `0.2.0-alpha.15` as well

**Comment by pleerock** [comment]
```
Category.name is being described as undefined
```

Do you mean you must specify type in `Column` decorator? If yes, then as I already told you need to properly setup reflect-metadata and typescript options.

**Comment by crutchcorn** [comment]
Ahh, sorry! Adding reflect-metadata fixed the issue 😅 Thanks a million
