### ISSUE TITLE
Relation update failing during normal table update

### ISSUE THREAD

**Issue by MattJeanes** [typeorm/typeorm#145]
Hi, I've been trying to do a simple update on a table with a one-to-many, but it's failing with the following SQLite error: `SQLITE_CONSTRAINT: NOT NULL constraint failed: comments.ticket_id`

Dumping relevant stripped down code...

```typescript
// Ticket

import { Table, Column, PrimaryGeneratedColumn, ManyToOne, OneToMany } from 'typeorm';
import { User } from './User';
import { Comment } from './Comment';

@Table("tickets")
export class Ticket {
    @PrimaryGeneratedColumn()
    id: number;

    @OneToMany(type => Comment, comment => comment.ticket)
    comments: Comment[] = [];

    @Column("int", { name: "c_vsts" })
    vsts: number;
}
```

```typescript
// Comment

import { Table, Column, PrimaryGeneratedColumn, ManyToOne, JoinColumn } from 'typeorm';
import { Ticket } from './Ticket';
import { User } from './User';

@Table("comments")
export class Comment {
    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(type => Ticket, ticket => ticket.comments)
    @JoinColumn({ name: "ticket_id" })
    ticket: Ticket;

    @Column("text")
    body: string;
}
```

```typescript
// In this case, key is 'vsts' and value is '5335'
public async edit<K extends keyof Ticket>(id: number, key: K, value: Ticket[K]) {
    var conn = await this.db.getConnection();
    var ticketRepo = conn.getRepository(Ticket);
    var ticket = await ticketRepo.findOneById(id);
    if (!ticket) { throw "Invalid ticket" };

    ticket[key] = value;
    await ticketRepo.persist(ticket);
};
```

```typescript
// https://github.com/typeorm/typeorm/blob/fc37ca1262e6bc22c9e55083330af43360f9f9ed/src/persistence/SubjectBuilder.ts#L664-L668
} else if (relation.isOneToMany && relation.inverseRelation) {
	relatedEntitySubject.relationUpdates.push({
		relation: relation.inverseRelation,
		value: null
	}); // todo: implement same for one-to-one
}
```

So basically after crawling around the code it looks like the above code from the SubjectBuilder appears to be pushing a null relation update into it. This results in the following query being attempted during `SubjectOperationExecutor.executeUpdateRelations`, resulting in the SQLite error at the top:

`UPDATE "comments" SET "ticket_id"=null WHERE "id"=81220`

I've followed the code right through and I can't work out why it has this behaviour, am I setting up my tables wrong or is this an actual bug? Thanks

**Update**: It works if I join and select ticket.comments, like so:
```typescript
public async edit<K extends keyof Ticket>(id: number, key: K, value: Ticket[K]) {
    var conn = await this.db.getConnection();
    var ticketRepo = conn.getRepository(Ticket);
    var ticket = await ticketRepo.findOneById(id, { alias: "ticket", innerJoinAndSelect: { "comment": "ticket.comments" } });
    if (!ticket) { throw "Invalid ticket" };

    ticket[key] = value;
    await ticketRepo.persist(ticket);
};
```

I'm using this as a workaround for now but ideally I don't want to have to select the comments if I'm not updating them.

**Comment by pleerock** [comment]
Can you please strip down your code even more? No need to strip down entities, but there is need to strip down edit. I need code that I can execute and test the result, e.g. full deproduction from a clean database including persist operation that is being executed before `ticketRepo.findOneById`.

You have this query executed: `UPDATE "comments" SET "ticket_id"=null WHERE "id"=81220` and this query fails because `ticket_id` can't be set to NULL. Am I right? If yes, then its strange because ticket_id should be nullable by default

**Comment by MattJeanes** [comment]
Sure, I'll try and get you some example code to replicate the problem. I'm assuming you basically want a little typescript app that completely replicates the issue on it's own. The database is a Spiceworks SQLite one, so the schema isn't generated by TypeORM and I can't edit it.

And yes, you are right - comments are associated to tickets as many-to-one and the comment.ticket_id cannot be null or it would be associated with no ticket.

**Comment by pleerock** [comment]
> I'm assuming you basically want a little typescript app that completely replicates the issue on it's own

peace of code there is enough

> The database is a Spiceworks SQLite one, so the schema isn't generated by TypeORM and I can't edit it.

This maybe a root cause of the problem. Check if `comments. ticket_id` nullable is set to true in your table. If its not set to true then TypeORM cant make all operations properly, because it needs the referenced side to be nullable.

There is alternative fix of your problem. In your entity you are initializing your comments:

```typescript
    @OneToMany(type => Comment, comment => comment.ticket)
    comments: Comment[] = [];
```

there is part which brings you problems: ` = []`. Don't initialize class properties if you want correct behaviour. When you are persisting your entity again and its comments are empty (because they are not loaded, and comments are just empty array because of initialization) ORM thinks that all comments were actually removed from OneToMany side, and detaches all relations.

**Comment by MattJeanes** [comment]
Oh I see, that makes a lot of sense actually, I thought you had to initialise the array if you wanted to join and select them in though - would that still work if I were to remove the initialiser?

**Comment by pleerock** [comment]
yes, sure. I don't recommend to initialize arrays at all to prevent such problems, even if that may be convinient sometimes

**Comment by MattJeanes** [comment]
Oh okay, alright - I added it because you have it in your many-to-many photo/album example but I can see that I don't need it here. Thanks for the help really appreciate it. 😄

**Comment by guscastro** [comment]
@pleerock 
Hi, would you consider removing references to self-initialised arrays from the documentation?
The section I'm referring to is:
```
export class Photo {
    /// ... other columns

    @ManyToMany(type => Album, album => album.photos, {
        cascadeInsert: true, // Allow to insert a new album on photo save
        cascadeUpdate: true // Allow to update an album on photo save
    })
    albums: Album[] = []; // We initialize array for convinience here
}
```

**Comment by pleerock** [comment]
You are right, we shall do it. PRs are welcomed ;)

**Comment by MattJeanes** [comment]
Definitely agree, this issue caused me a lot of headache so hopefully we can prevent others from running into such trouble.
