### ISSUE TITLE
query builder orderBy using columnDatabaseName

### ISSUE THREAD

**Issue by zxlwbi199101** [typeorm/typeorm#1453]
When I am using queryBuilder.orderBy to a Embedded Entity, the builder only use `findColumnWithPropertyName`, as:  https://github.com/typeorm/typeorm/blob/db4d86efeebae78db04ddd843a760a8a65661876/src/query-builder/SelectQueryBuilder.ts#L1741

Is it better to fall back to databaseName if cannot find the propertyName ?

**Comment by pleerock** [comment]
This error should have been fixed in `next`, can you please try it? (`npm i typeorm@next`)

**Comment by zxlwbi199101** [comment]
Thanks for the fix, it's working in the next version. I think the issue can be closed.

Thank you very much
