### ISSUE TITLE
Cannot assign to read only property'type'of object'#<Banner>'`

### ISSUE THREAD

**Issue by qualc** [typeorm/typeorm#1458]
In the JavaScript grammar. After an instance of the @Entity () modified new object, the attribute value of the instance can not be changed
`TypeError: Cannot assign to read only property'type'of object'#<Banner>'`
I try to add `descriptor.writable = true` in Column and so on.
```
function Column(typeOrOptions, options) {
    return function(object, propertyName, descriptor) {
        descriptor.writable = true;
    };
}
```
Did I make a mistake?

**Comment by pleerock** [comment]
Sorry, but I do not understand what you mean and what you are trying to do

**Comment by qualc** [comment]
Example：
/entity/banner.js
```
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
@Entity('banner')
export class Banner {
    @PrimaryGeneratedColumn()
    id;
    @Column()
    type;
}
```

app.js
```
import "reflect-metadata";
import { Banner } from './entity/banner';
typeorm.createConnection({
     ...,
   entities: ['./entity/*.js'  ]
}).then(async function(connection) {
    let banner = new Banner();
    banner.type = 1;  // **TypeError: Cannot assign to read only property 'type' of object '#<Banner>'**
}).catch(e => {
    console.log(e)
});
```

**Comment by pleerock** [comment]
Looks like an issue of the transpiler plugin you are using.  Does using `descriptor.writable = true` in decorators solve the problem?

**Comment by qualc** [comment]
Yes, it does.

**Comment by pleerock** [comment]
okay, are you able to create a pull request for this change and make sure its not breaking anything else in typescript infrastructure?

**Comment by qualc** [comment]
Emm,I need time to make sure it.

**Comment by qualc** [comment]
Emm,I need time to test it.I'll give you a reply later.

**Comment by yhpark** [comment]
I also went through this issue. Apparently the babel class-properties proposal plugin in loose mode transpiles class properties without pre-assigned value non-writable. Not sure if this is a bug or intended.. 

Right now one solution is to assign any default values as below (`undefined` works as well):

```js
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
@Entity('banner')
export class Banner {
    @PrimaryGeneratedColumn()
    id = undefined;
    @Column()
    type = 1;
}
```

**Comment by pleerock** [comment]
After certain tests I found that it does not work in typescript. I think problem is in babel plugin and it should be resolved there. I remember I was already reporting to them this issue year ago. Closing.

**Comment by qualc** [comment]
Yes, I also found that the porblem was due to the inconsistency of bable plugin and typescript to the interpretation of decorator.
