### ISSUE TITLE
See previous object in subscriber decorator

### ISSUE THREAD

**Issue by crutchcorn** [typeorm/typeorm#1459]
I want a way to see what the object is before saving new information to the model using `BeforeInsert` and `BeforeUpdate`

Looking into the decorator, I see there are two properties that seem to do what I want to do:
`export declare function BeforeInsert(): (object: Object, propertyName: string) => void;`

However when I use them:
```
  @BeforeInsert()
  @BeforeUpdate()
  preSave(object: Object, propertyName: string) {
    console.log(object);
    console.log(propertyName);
    console.log(this.lastName);
  }
```

I get `undefined` for the two properties and the new information for the last `console.log`.

**Comment by pleerock** [comment]
Your `preSave` does not accept such arguments, there is no such functionality. And there is no "previous object" definition. Only model in the database, but to get it you need to load it from the database.

**Comment by crutchcorn** [comment]
Wouldn't that be a performance nightmare if I were qeurying for an object twice every time I modified one?
