### ISSUE TITLE
How do you set up cascade delete?

### ISSUE THREAD

**Issue by IRCraziestTaxi** [typeorm/typeorm#1460]
I saw the unfortunate comment that cascade delete support is no longer supported, but I saw some people say they're using some database cascade delete option, something along the lines of onDelete: "CASCADE"? I can't find that anywhere.

What is the proper way to set up cascade deletes?

**Comment by pleerock** [comment]
`onDelete: "CASCADE"` is database-level cascades. You setup then on relations. This directive tells what database shall do with rows with related values in join columns when related object is being deleted.

**Comment by otroboe** [comment]
I put this on my entity, and it worked with MySQL.

```javascript
@Entity()
export class Schedule {
  @PrimaryGeneratedColumn()
  id: number;
  @ManyToOne(() => Location, location => location.schedules, { onDelete: 'CASCADE' })
  location: Location;

  @ManyToOne(() => Movie, movie => movie.schedules, { onDelete: 'CASCADE' })
  movie: Movie;
}
```

**Comment by IRCraziestTaxi** [comment]
@pleerock @otroboe Thanks, guys. I swear I tried that and it wasn't an available option, but I'll try it again.

**Comment by IRCraziestTaxi** [comment]
I just verified that I can add the onDelete option to a relationship. Thanks again.

**Comment by josel82** [comment]
Hi, I hope you can help me with this issue. I'm trying to delete a row in the Link table, and I am getting the following error: 

**update or delete on table \"link\" violates foreign key constraint \"fk_d32f766f20cbee0d7f543df6719\" on table \"vote\"**

But only when a Link holds a Vote. I will allow me to delete if a Link doesn't have any Votes yet.

This is how these tables are related:

A user can have many links
A Link can only belong to one user
A Link can be voted many times
A Vote can only belong to a link
A Vote can only belong to a User

```TypeScript
@Entity()
export class Link {
    @PrimaryGeneratedColumn()
    public id: number;
    @ManyToOne(type => User, user => user.id)
    public user: User;
    @OneToMany(type => Vote, vote => vote.link)
    public votes: Vote[];
    @Column({type: 'varchar'})
    public url: string;
    @Column({type: 'varchar'})
    public title: string;
}
```
```TypeScript
@Entity()
export class Vote {
    @PrimaryGeneratedColumn()
    public id: number;
    @ManyToOne(type => User, user => user.id, {onDelete:'CASCADE'})
    public user: User;
    @ManyToOne(type => Link, link => link.id, {onDelete:'CASCADE'})
    public link: Link;
    @Column({type: 'boolean'}) 
    public isUpvote: boolean;
}
```
```TypeScript
@Entity()
export class User {
    @PrimaryGeneratedColumn()
    public id: number;
    @Column({type: 'varchar'})
    public email: string;
    @Column({type: 'varchar'})
    public password: string;
}
```
I would appreciate any help. Thanks.

**Comment by havenchyk** [comment]
@josel82 how did you solve this problem?

@pleerock could you please clarify the last question?

**Comment by josel82** [comment]
@havenchyk  try adding `{onDelete:'CASCADE'}` to the `@ManyToOne` Decorators. It should work.

**Comment by havenchyk** [comment]
thanks, it turned out that I have such problem with one-to-one relation even with `onDelete: 'CASCADE'`

**Comment by feimosi** [comment]
`onDelete: 'CASCADE'` with `@OneToOne` doesn't work for me either

**Comment by nick-fytros** [comment]
I've got the same issue with `onDelete: 'CASCADE'` with `@OneToOne`. Doesn't remove the entry.

**Comment by havenchyk** [comment]
@nick-fytros @feimosi could you please create a new issue with an example?

**Comment by jalooc** [comment]
@nick-fytros @feimosi same for me, though cascade works for the inverse side of the relationship. @havenchyk here's the ticket with details: #3218

**Comment by pleerock** [comment]
guys, typeorm doesn't remove anything by cascades on its own. The only thing it does is it sets `onDelete: "CASCADE"`. The actually removal is database responsibility, so please make sure you got it right how onDelete in your database works.

**Comment by Kaminto** [comment]
`onDelete: "CASCADE"` works best when set in the migrations at the table setup

```
foreignKeys: [
                {
                    referencedTableName: 'User',
                    referencedColumnNames: ['id'],
                    columnNames: ['user'],
                    onDelete: 'CASCADE',

                }]
```

**Comment by itsandreramon** [comment]
How does this work when I also want to set cascade: true to insert entities?

**Comment by dduft** [comment]
> `onDelete: "CASCADE"` works best when set in the migrations at the table setup
> 
> ```
> foreignKeys: [
>                 {
>                     referencedTableName: 'User',
>                     referencedColumnNames: ['id'],
>                     columnNames: ['user'],
>                     onDelete: 'CASCADE',
> 
>                 }]
> ```

When you work with migrations, I think this is the only way it works!

**Comment by darushHamidi** [comment]
> thanks, it turned out that I have such problem with one-to-one relation even with `onDelete: 'CASCADE'`

You can see this  https://github.com/typeorm/typeorm/issues/9124

**Comment by darushHamidi** [comment]
> @nick-fytros @feimosi could you please create a new issue with an example?

@havenchyk
You can see this  https://github.com/typeorm/typeorm/issues/9124

**Comment by stefanwille** [comment]
I have made an example showing the solution: https://github.com/stefanwille/typeorm-onetomany-remove/

**Comment by bacloud23** [comment]
Hi @pleerock ,
excuse me this is old, but I have a remaining question, What is the purpose of declaring delete on cascade if it is already taken care of in database ? 
Thanks a lot
