### ISSUE TITLE
[Question] How to define ON DUPLICATE KEY UPDATE behavior?

### ISSUE THREAD

**Issue by kikar** [typeorm/typeorm#1463]
I have a table with:
- an auto-increased INT id
- a few string fields that define a unique key
- a bunch of int fields.

I would like to insert a new row with all the values defined, but if that unique key already exists, i just would like to sum all the int fields.

I perform this operation a few times per second, so checking for existence before would actually slow me down.

Is there a way to define the SQL statement so I can speed up my app?

**Comment by pleerock** [comment]
no, there is no such functionality inside insert query builder, you have to execute raw query. We already have a `ON CONFLICT` support in typeorm@next for postgres, I think we can add similar  functionality to mysql. Feel free to contribute.

**Comment by kikar** [comment]
Could you please help me with an example query done this way? I can't seem to find anything about this in the docs.

The query would start like this, and then? How do I specify a `DUPLICATE KEY` condition?
```javascript
import {getConnection} from "typeorm";

await getConnection()
    .createQueryBuilder()
    .insert()
    .into(User)
    .values([
        { firstName: "Timber", lastName: "Saw" }, 
        { firstName: "Phantom", lastName: "Lancer" }
     ])
    ...
```

**Comment by pleerock** [comment]
as I told its not supported, you'll need to implement this functionality (contribution) or use native query, e.g. `connection.query("INSERT INTO ... ON DUPLICATE KEY ...")`

**Comment by kikar** [comment]
Sorry, read wrongly your first reply, and thank you for the response.
I'll see if I can find some time to contribute, could you help find the code for the postgres integration?

**Comment by pleerock** [comment]
checkout `next` branch and `InsertQueryBuilder` which contains postgres code.

**Comment by kikar** [comment]
Found it thanks!
Another related question: if I wanted to update a User field, by using the current value, how could I do that?

```javascript
await getConnection()
    .createQueryBuilder()
    .update(User)
    .set({
        firstName: user.firstName.trim(), // Something like this?
        count: (user.count + 5) / 2 // Or this?
    })
    .where("id = :id", { id: 1 })
    .execute();
```

**Comment by pleerock** [comment]
```ts
    .update(User)
    .set({
        count: () => "(count + 5) / 2" // raw sql statement
    })
```

**Comment by kikar** [comment]
Cool, thanks.
I'm gonna have a crack in the weekend.

**Comment by imnotjames** [comment]
Believe we have implemented this via `.orUpdate()`

**Comment by franco-roura** [comment]
@imnotjames is the `.orUpdate()` documented somewhere? I can't seem to find any examples or documentation pointing to it.

**Comment by dattp** [comment]
> @imnotjames is the `.orUpdate()` documented somewhere? I can't seem to find any examples or documentation pointing to it.

@franco-roura you can use `orUpdate()` with `createQueryBuilder()` like pipeline.
`orUpdate()` recevice `string[]`, that `uniqued` field in DB.
