### ISSUE TITLE
Error when comparing Entities on Connection.prototype.findMetada

### ISSUE THREAD

**Issue by FlyingDonkeyDev** [typeorm/typeorm#1467]
Error: 
metadata.target == target are not equal when really if they are

Example:
<img width="1345" alt="captura de pantalla 2018-01-18 a las 14 40 43" src="https://user-images.githubusercontent.com/19708092/35100913-d71cf0f0-fc5d-11e7-9837-acca18b433f8.png">

Temporary solution:
I have solved it temporarily by comparing metadata.target.toString() == target.toString()

**Comment by daniel-lang** [comment]
Could you provide the code you are running that leads to your problem?

**Comment by pleerock** [comment]
Closing as no answer from reporter.
