### ISSUE TITLE
Typeorm does not see and register entity specified within ormconfig

### ISSUE THREAD

**Issue by johnbendi** [typeorm/typeorm#147]
I have specified the `entities:` key within `ormconfig.json` and yet I still get a `RepositoryNotFoundError` for an `Entity` . Is there a particular way of specifying this value within `ormconfig.json`

**Comment by johnbendi** [comment]
Thanks to @pleerock [typescript-example](https://github.com/typeorm/typescript-example/blob/master/ormconfig.json) I was able to point the `entities:` key to the right path. In this case to my `dist/model/entities/*.js` . I don't know if there is a better way of doing it. I was previously pointing to `src/model/entities/{*.ts, *.js}`

**Comment by johnbendi** [comment]
@pleerock btw is there somewhere we can ask questions like on stackoverflow. Do you monitor stackoverflow?

**Comment by pleerock** [comment]
@johnbendi yes, I do. BTW you can use ts-node if you dont want to point your js from dist folder.

**Comment by johnbendi** [comment]
@pleerock okay. I have seen ts-node but have not really given it a try. Will check it out soonest. Thanks a lot.
