### ISSUE TITLE
EntityManager.find should support `conditions` and `options`

### ISSUE THREAD

**Issue by brendan-roche** [typeorm/typeorm#1473]
At the moment EntityManager.find (and related methods) supports providing either `conditions` as an object literal, or `options` as `FindManyOptions`, but not both at the same time. This would be helpful when you have a query with simple conditions using `conditions` and custom conditions or joins when providing `options`.

`findOne` does seem to support it, but is currently broken too.

This PR adds support for allowing `conditions` and `options` for EntityManager `find`, `findByIds`, `findAndCount`, `count` and fixes `findOne`:
https://github.com/typeorm/typeorm/pull/1475

**Comment by brendan-roche** [comment]
If I were just to use the `where` condition and I have mixed conditional types, then I have to construct all the conditionals myself, and I lose the benefits of the type checking.
```
function find(findConditions: FindConditions)
    const { fromDate, toDate, productId, categoryId, keywords } = findConditions;
    const where = [];
    if (fromDate) {
      where.push(`date >= '${fromDate}'`);
    }
    if (toDate) {
      where.push(`date <= '${toDate}'`);
    }
    if (keywords) {
      where.push(`title LIKE '%${keywords}%'`);
    }
    if (productId) {
      where.push(`productId = '${productId}'`);
    }
    if (categoryId) {
      where.push(`categoryId = '${categoryId}'`);
    }
```
Also for consistency `findOne` currently does seem to support using both (though is broken), so I had assumed it hadn't yet been implemented?

Additionally passing `params` for the `where` condition doesn't seem to be supported yet.

**Comment by pleerock** [comment]
> If I were just to use the where condition and I have mixed conditional types, then I have to construct all the conditionals myself, and I lose the benefits of the type checking.

sorry I don't understand what you mean. From the code I see looks like you need to use `where` string. 

> Additionally passing params for the where condition doesn't seem to be supported yet.

Correct, probably something we shall add.

**Comment by pleerock** [comment]
Looks like resolved conversion, let me know if you want to add something.

**Comment by PeymanKhodadust** [comment]
Hi, I just upgraded to version 0.1.18 and for me none of the above options/conditions seem to work. entityManager.findOne (and also find) just ignores it and returns the first record in the table. I tried the variant with the costumRepository as in your documentation (typeorm.io) too, with the same unsatisfying result. When I do the same with a queryBuilder it works! But refactoring all the find/findOne methods with conditions/options to queryBuilder is no option as I would have to do it several hundred times manually. this is an example code:
`` let last = await entityManager.findOne(Task, {
            where: {
                "successor": null,
            },
        }); ``
With the version 0.0.11 it used to work with a conditions object literal...

**Comment by pleerock** [comment]
@PeymanKhodadust following

```
let last = await entityManager.findOne(Task, { where: { "successor": null, }, });
``` 

Is working fine, you should not have any issues with it. If you have please create a PR with a failing test and I'll resolve your issue.
