### ISSUE TITLE
Inconsistent documentation on `eager` option

### ISSUE THREAD

**Issue by HillTravis** [typeorm/typeorm#1478]
The docs regarding how the `eager` option works are contradictory regarding use with `QueryBuilder`.

On [the **What are Relations?** page, under the section **Relation Options**](http://typeorm.io/#/relations/relation-options), the first option is `eager`, and it says:

> If set to true, the relation will always be loaded with the main entity when using find* methods **or QueryBuilder** on this entity

Then, on [the **Eager and Lazy Relations** page, at the bottom of the **Eager Relations** section](http://typeorm.io/#/eager-and-lazy-relations/eager-relations), it says:

> Eager relations only work when you use find* methods. If you use QueryBuilder eager relations are disabled and have to use leftJoinAndSelect to load the relation.

**Comment by pleerock** [comment]
Right, its a mistake. Eager relations are only working with find* methods currently. I'll be really grateful if you create a PR with those changes.
