### ISSUE TITLE
Using custom naming strategy in migrations:generate

### ISSUE THREAD

**Issue by yoz** [typeorm/typeorm#1482]
Running `typeorm migrations:generate` generates a migration using the default naming strategy for table and column names. Is it possible to generate the migration using a different naming strategy? I can't find documentation on it.

**Comment by pleerock** [comment]
no, there is no such possibility yet. You can contribute btw.

**Comment by yoz** [comment]
Do you think it makes sense to add an ormconfig option that specifies a file to use for naming strategy with a default export? Something like

`"namingStrategy": "dist/some_path/naming_strategy.js"` (it would have to point to the tsc-compiled js)

Alternatively perhaps

```
"namingStrategy": {
  "path": "dist/some_path/naming_strategy.js",
  "export": "MyNamingStrategy"
}
```

for specifying a different export than the default from `naming_strategy.js`.

**Comment by pleerock** [comment]
yoz we can do that, but wouldn't it be a weird solution?

**Comment by yoz** [comment]
Yes, it would be unusual to say the least. I'm asking before I start writing code (I'm happy to contribute) in case you have a suggested approach.

**Comment by pleerock** [comment]
Alternative approach currently is to manually load file with configuration and append naming strategy. This approach sounds better, maybe we can implement it, since its better and we can't find any better ways yet.

Do you think its worth to do complicate things and support "export" as well? Maybe simply load `default` from the provided file?

**Comment by yoz** [comment]
The default export is fine, I think. It's always possible to use it, even if the naming strategy is not already a default export, by defining a new file like

```
import { SomeNamingStrategy } from './some/path';
export default SomeNamingStrategy;
```

**Comment by pleerock** [comment]
correct, even in the same file. So yes, I think you can implement this functionality if you want.

**Comment by yoz** [comment]
It turns out this is possible when using `ormconfig.js` (https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#loading-from-ormconfigjs) - we can `require()` the naming strategy, e.g.

```
const SomeNamingStrategy = require('./some/path').SomeNamingStrategy;
module.exports = {
  ...
  namingStrategy: new SomeNamingStrategy(),
};
```

**Comment by yoz** [comment]
I think it's ok to close this.
