### ISSUE TITLE
Proposal: json-array similar to simple-array, using "text" in various databases

### ISSUE THREAD

**Issue by idchlife** [typeorm/typeorm#1484]
I found lack of this functionality I used in doctrine: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#json

It could not be named "json" since type named exactly like that exists in several databases. If you think there is better name than "json-array" (since json can be not only an array) - I would love to know!

If you @pleerock @19majkel94 are ok with this idea, I would like to write code and make a PR.

**Comment by 19majkel94** [comment]
AFAIK, TypeORM have good support for json columns. I tested it with MySQL, where I could easily save array of objects in db and TypeORM has automatically serialized and deserialized it 😉 

If some databases doesn't support json type columns, we could emulate it and just store it as text.

**Comment by idchlife** [comment]
@19majkel94 yes, exactly! My case was born when I started writing field with object for SQLite.

I honestly did not try to execute it but learning through documentation and asking a question in gitter gave me understanding that there is no such thing as auto converting to "text" field in databases without json types.

e.g. this won't work:

```typescript
@Column("text")
private obj: { key: number } = {};
```

proposal is for 

```typescript
@Column("json-array") // will be serialized and stored in "text" type, also deserialized on AfterLoad
private obj: { key: number } = {};
```

**Comment by 19majkel94** [comment]
I would leave it as `@Column("json")`, just with fallback to `text` type on not supported DBMS.

**Comment by idchlife** [comment]
Ah, this one will be much better! Also, can be there any case where
developer would want a choice, use JSON.stringify or something over json in
mysql/postgres?

20 янв. 2018 г. 12:47 пользователь "Michał Lytek" <notifications@github.com>
написал:

**Comment by pleerock** [comment]
If it will be implemented it should be just `json-array`. Introducing `json` flag in column options specially for text does not seems a good design. Replacing exist `json` functionality for some drivers may confuse users - they can think other types cross-platform as well which is not truth. Adding new json-array type should be easy to implement, so I left this feature to the community.

**Comment by 19majkel94** [comment]
> If it will be implemented it should be just json-array

`json-array` name is more confusing than `{ json: true }` because `array` means array, not a single object with e.g. two properties 😉 
Explicit type is good, but `json-array` name isn't. We need something better - `syntethic-json` or an poll with community votes 😆 ( 👍 👎 )

**Comment by pleerock** [comment]
@19majkel94 ahh correct, thanks for the correction. I was thinking `json-array` is written like `simple-json`, just like `simple-array`. It shall be called `simple-json`.

**Comment by idchlife** [comment]
@pleerock @19majkel94 I vote for "simple-json"

**Comment by pleerock** [comment]
vote is accepted just like PR could be 😉

**Comment by idchlife** [comment]
@pleerock @19majkel94 https://github.com/typeorm/typeorm/pull/1488

**Comment by pleerock** [comment]
I'll close it since it was already implemented.
