### ISSUE TITLE
can't suppose option column  character, when i create a table.

### ISSUE THREAD

**Issue by o70078** [typeorm/typeorm#1485]
i want use "character set utf8",when i create a table , but i can't found any params to do it,

**Comment by pleerock** [comment]
its better if you set your database to a correct encoding

**Comment by o70078** [comment]
sometimes i want to create table,multi column use diffrent character,such as:
`	/**
	 * use GBK
	 */
	@Column("varchar") data1: string

	/**
	 * use ASCII
	 */
	@Column("varchar") data2: string

	/**
	 * use UTF8
	 */
	@Column("varchar") data3: string

	//And More..`

**Comment by pmoleri** [comment]
For future reference, I'm using `typeorm@0.2.6` with `MySQL` and both `charset` and `collation` work in a per-column basis.

E.g.
```
    @Column({ type: "varchar", charset: "ascii") data2: string
    @Column({ type: "varchar", charset: "utf8mb4", collation: "utf8mb4_unicode_ci") data3: string
```
