### ISSUE TITLE
EntityManager.merge BUG (PlainObjectToNewEntityTransformer)

### ISSUE THREAD

**Issue by 1tu** [typeorm/typeorm#1487]
Hello!
In PlainObjectToNewEntityTransformer::49
```
if (entity[relation.propertyName] instanceof Array) {
  const existRelation = entity[relation.propertyName].find((subEntity: any) => {
    return subEntity[relation.propertyName] === subObject[relation.propertyName];
  });
if (existRelation)
   this.groupAndTransform(subEntity, existRelation, relationMetadata);
}
```
you can see a comparison of child entity by the relation key of the parent entity, and it will always be true, because `undefined === undefined`.
instead, it would be correct (or perhaps here we need to compare all primary columns)
```
if (entity[relation.propertyName] instanceof Array) {
  const subPrimaryKey = relation.inverseEntityMetadata.primaryColumns[0].propertyName;
  const existRelation = entity[relation.propertyName].find((subEntity: any) => {
    return subEntity[subPrimaryKey] === subObject[subPrimaryKey];
  });
if (existRelation)
   this.groupAndTransform(subEntity, existRelation, relationMetadata);
}
```
in this case, all the nested entities correctly created (if no exist primary key) or updated (if PK exist).

**Comment by pleerock** [comment]
can you please provide a minimal reproduction code sample which shows the real issue? (or better a failing test if possible).

**Comment by 1tu** [comment]
Before merge
![2018-01-23_19-01-39](https://user-images.githubusercontent.com/11233069/35286510-416a100c-0071-11e8-9848-ce03fcc6d258.png)
After merge
![2018-01-23_19-03-09](https://user-images.githubusercontent.com/11233069/35286530-4f1a21a6-0071-11e8-98e7-3ec01e7cfbb7.png)

in this place `return subEntity[subPrimaryKey] === subObject[subPrimaryKey];`
runtime looked like `return OrderProductEntityInstance['productList'] === OrderProductEntityInstance['productList']`
coz its `true` (`undefined === undefined`), method `this.groupAndTransform(subEntity, existRelation, relationMetadata)` was performed

**Comment by pleerock** [comment]
Okay I see that something is wrong is going on from your screenshots, however I don't have enough information. I need a minimal possible reproduction code. It would be great if you can contribute and create a PR with failing test like others do, I'll be able to fix this issue much quicker this way. Also please make sure to make all checks on `@next`.

**Comment by pleerock** [comment]
Closing because of no response from reportee.
