### ISSUE TITLE
don't persist relationships

### ISSUE THREAD

**Issue by thomasengels** [typeorm/typeorm#1491]
I have an object B that has a reference to an object A.

Object A has sensitive data, so when adding an instance of object A to B, we delete the sensitive data that can be visible by api calls. But when persisting it B, the existing row of object A gets overwritten.

**Comment by pleerock** [comment]
Can you please provide more info with examples?

**Comment by thomasengels** [comment]
had to add cascadeUpdate = false to the attribute

**Comment by pleerock** [comment]
You can try updated cascades functionality in `@next`, npm i typeorm@next. Let me know if you have issues with it.

**Comment by pleerock** [comment]
try in `next` and provide more details if it wont work there
