### ISSUE TITLE
Error parsing pg connection string

### ISSUE THREAD

**Issue by andrewdhazlett** [typeorm/typeorm#1493]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
attempt to establish a connection with a username or password containing the `@` character
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
[x] `mysql`
[ ] `postgres`
!>

**Comment by pleerock** [comment]
@andrewdhazlett Im very sorry but accidentally removed your message content, really sorry about that, but can you write it again

**Comment by andrewdhazlett** [comment]
this can be fixed by using a mature package to parse the url https://github.com/typeorm/typeorm/blob/feada9a3dd06b12c38b9f021bb3bd3dc72fd0094/src/driver/DriverUtils.ts#L56

**Comment by pleerock** [comment]
@andrewdhazlett if its an easy fix, do you want to send a PR with the fix?

**Comment by pleerock** [comment]
We cannot use third-party package btw because typeorm must work in browsers without requiring third-party libs. I'll left this issue for the community to fix.

**Comment by Rhymmor** [comment]
I guess it can be appropriate to just split be last `@` character. There is something similar in [node-url](https://github.com/defunctzombie/node-url):
https://github.com/defunctzombie/node-url/blob/13a35bd35a2cdf3fbfa7ee9c6ed5b927a48d6821/url.js#L200-L210
If it is, I can create PR.

**Comment by pleerock** [comment]
No, I don't think so `username@password` where password can contain `@` can break. Im not sure how people handle such except for having to backslash this character. And Im not even sure if postgres really allows such symbols in username and password.

**Comment by Rhymmor** [comment]
Couldn't find anything in postgres docs but I was able to set password contains `@` locally.

Actually, [pg](https://www.npmjs.com/package/pg) can parse connection url by himself with [pg-connection-string](https://www.npmjs.com/package/pg-connection-string) package [if you pass connectionString parameter](https://github.com/brianc/node-postgres/blob/ecab41c3f3d07230b24253e804971367cd04fb53/lib/connection-parameters.js#L47-L51). So maybe this is an easier option?

**Comment by pleerock** [comment]
Looks so, but we need to figure out what to do with other drivers, most of them need this functionality as well

**Comment by Rhymmor** [comment]
> No, I don't think so username@password where password can contain @ can break

Wait, but connection url have a form: `postgresql://[user[:password]@][netloc][:port][,...][/dbname][?param1=value1&...]` so last `@` character will always be after user:password

**Comment by pleerock** [comment]
ah, then okay, for some reason I thought it has user@password form

**Comment by Aupajo** [comment]
I can't submit a patch, as I don't have permission to do so from the client I'm working on, but I can confirm that the Node URL module handles this appropriately:

```typescript
function suggestedParseConnectionUrl(url: string) {
  const parsed = new URL(url);
  return {
    host: parsed.hostname,
    username: decodeURIComponent(parsed.username),
    password: decodeURIComponent(parsed.password),
    port: parseInt(parsed.port, 10),
    database: parsed.pathname.substring(1)
  };
}
```

Which will produce:

```typescript
suggestedParseConnectionUrl('postgres://username@host:1234/database')

{ host: 'host',
  username: 'username',
  password: '',
  port: 1234,
  database: 'database' }
```

As opposed to the current `parseConnectionURL`, which will produce:

```
{ host: 'host',
  username: '',
  password: 'username',
  port: 1234,
  database: 'database' }
```

As far as the password containing an `@` symbol: we're accepting a URI as defined by [RFC3986](https://tools.ietf.org/html/rfc3986), and so you could make the argument that this character should be escaped:

```typescript
suggestedParseConnectionUrl('postgres://username:passwordwith%40symbol@host:1234/database')
```

which produces

```typescript
{ host: 'host',
  username: 'username',
  password: 'passwordwith@symbol',
  port: 1234,
  database: 'database' }
```

However, `URL` will happily parse a non-escaped `@` as well:

```typescript
suggestedParseConnectionUrl('postgres://username:passwordwith@symbol@host:1234/database')
```

which will produce

```typescript
{ host: 'host',
  username: 'username',
  password: 'passwordwith@symbol',
  port: 1234,
  database: 'database' }
```

The only thing to be wary of is `%<Number>` appearing in your password, as this would be parsed as the equivalent entity (e.g. `%40` in my password would be translated into `@`). However, again, if this is a URI, you should be encoding those characters (i.e. `%2540` in that example).

**Comment by pleerock** [comment]
@Rhymmor can this issue be closed now?

**Comment by Rhymmor** [comment]
@pleerock yes, i think so.

**Comment by pleerock** [comment]
Thanks @Rhymmor
