### ISSUE TITLE
Relation not persisted

### ISSUE THREAD

**Issue by lverledens** [typeorm/typeorm#1495]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a simple scenario with a ManyToOne,OneToMany relation: A User can have many UserClients but a UserClient is linked to only one User.

```ts
@Entity()
export class User {

  @PrimaryGeneratedColumn()
  id: number;

  @OneToMany(type => UserClient, async userClient => userClient.id, {cascadeInsert: true})
  userClients: Promise<UserClient[]>;
}

@Entity()
export class UserClient {
    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(type => User, async user => user.userClients)
    user: Promise<User>;
}
```

When I create a new User and add a UserClient to this user, the relation is not persisted in the db.

```ts
const userRepository = getManager().getRepository(User);
const userClientRepository = getManager().getRepository(UserClient);
const user = new User();
const userClient = new UserClient();
userClient.user = Promise.resolve(user)
user.userClients = Promise.resolve([userClient]);
const savedUser = await userRepository.save(user);
```

When i save, i get the following error:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'joinColumns' of undefined.

What am I doing wrong?

**Comment by cserron** [comment]
@lverledens I have exactly the same problem. Did you get to solve it? 

Thanks.

**Comment by lverledens** [comment]
@cserron Unfortunately not. Switched to https://github.com/RobinBuschmann/sequelize-typescript and have no issues with that one.

**Comment by pleerock** [comment]
He has a wrong code:

```ts
  @OneToMany(type => UserClient, async userClient => userClient.id, {cascadeInsert: true})
  userClients: Promise<UserClient[]>;
```

This `async userClient =>` should be just `userClient =>`, there are no places in documentation which say to use async functions in there. Same from inverse side.
