### ISSUE TITLE
Relation One-To-One seemed that It does not check uniqueness.

### ISSUE THREAD

**Issue by xkguq007** [typeorm/typeorm#1497]
**Issue type:**

[ ] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Sorry for bad English.
I proceed very simple testing before use production level our companies production.
I find it looks one-to-one relationship can not check duplication.

For example,
User - Profile Table (1:1)
User makes two profiles -> it should occur error, but success.
after inserting, Find User -> profile is null
And, Find all profile -> 2 profiles found. (at same user)

**Comment by daniel-lang** [comment]
**Saving/Check for duplicate:** This depends on how you defined your entities for user and profile.
You can use the user id as the primary id for the profile which would mean, that only one profile per user can be inserted.

**Loading:** Relations are not automatically loaded when you use `find()` on the user repository. You will either have to use `await userRepository.find({ relations: ["profile"] });` to load the user with his profile or use eager relations which would mean, that the profile gets loaded automatically when you load the user.
You can read more about `find` with One-to-One [here](http://typeorm.io/#/one-to-one-relations) and on eager relations [here](http://typeorm.io/#/eager-and-lazy-relations) (links are from our docs).

**Comment by xkguq007** [comment]
Thanks for you reply. I did exactly same thing, however source was disappeared, might deleted. I check again thank you.
