### ISSUE TITLE
Multi-column primary key

### ISSUE THREAD

**Issue by andreasrueedlinger** [typeorm/typeorm#15]
Hi, I really like the idea behind your project and your effort you put in.
A question about primary keys (since they are required by your framework): are multi-column primary keys supported?
Do you just annotate two or more columns with the @PrimaryKey decorator?

**Comment by pleerock** [comment]
Hey, yeap I have it in plans in my long todos list [here](https://github.com/typeorm/typeorm/issues/2), but not sure when I can push it since there are lot of other work right now

**Comment by dkirchhof** [comment]
Hello,  
i came accross a problem when using inheritance. It seems that a composite primary key is not generated if one column is defined in a parent and one in a child class.  
Example:
```ts
// no decorator
export abstract class RatingBase
{
    @PrimaryColumn()
    public userId: string;

    @Column()
    public value: number;
}

@Entity("course_ratings")
export class CourseRating extends RatingBase
{
    @PrimaryColumn()
    public courseId: string;
}
```

**Comment by Kononnable** [comment]
@dkirchhof Please create separate issue if there isn't one already. Not many people will look in old, closed issues and it's easier to maintenance if different problems(they're connected, but are not the same) are kept in different issues.
