### ISSUE TITLE
Cannot specify order of columns in composite primary key with ManyToOne

### ISSUE THREAD

**Issue by yoz** [typeorm/typeorm#1500]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

```
@Entity()
export class Name {
  @OneToMany(type => NameYear, nameYear => nameYear.name)
  years: NameYear[];
}

@Entity()
export class NameYear {
  @ManyToOne(type => Name, name => name.years, {
    primary: true
  })
  name: Name;

  @PrimaryColumn({
    type: "integer"
  })
  year: number;
}

```

Running `migrations:generate` results in a line like

`ALTER TABLE "public"."name_year" ADD PRIMARY KEY ("year", "nameId")`

(NB. I already created this table so it might look slightly different if creating it the first time)

However, I would expect that since `name` appears before `year` in the entity definition, the primary key order would be `("nameId", "year")`; this is the behavior we would see if we had multiple `@PrimaryColumn`.

There doesn't appear to be a way to get the schema builder to generate the key in the `("nameId", "year")` order.

**Comment by yoz** [comment]
I also discovered that the column for the `@ManyToOne` (`nameId` in this example) is nullable by default. This is surprising (and I could not find documentation on it), because `@Column` is non-nullable by default. Furthermore, the schema generator is confused - when the database has a NOT NULL constraint on `nameId`, running `migrations:generate` attempts to drop that constraint, which fails because it is part of a primary key.

The workaround here is to ad `nullable: false` to the `@ManyToOne` definition.

So (at least for postgres) it appears that `primary: true` should imply `nullable: false`.

**Comment by pleerock** [comment]
all `@ManyToOne`  relations are nullable by default, that's why its nullable. Maybe we should add extra check there and check if relation is primary then make it non nullable.

Regarding to your column ordering issue... I'll take a look later on it, however currently typeorm does not care about order of columns inside tables.

**Comment by yoz** [comment]
looks related to https://github.com/typeorm/typeorm/issues/587#issuecomment-312837573

**Comment by pleerock** [comment]
> all @ManyToOne relations are nullable by default, that's why its nullable. Maybe we should add extra check there and check if relation is primary then make it non nullable.

its already working in `@next`

> Regarding to your column ordering issue

This is not so valuable to be in priority.

Closing for now.

**Comment by jkl1337** [comment]
> This is not so valuable to be in priority.

I'll point out that this column ordering may seem a mere aesthetic nuisance, but it has a negative performance implication. A common case is that part of the composite primary key will be a foreign key, and you almost certainly want that to the be the first column. The creation of the primary key implicitly creates an index. If the FK column is the first column in the index then this can be used to speed up cascading operations. If the order is reversed, this will break in most cases.
