### ISSUE TITLE
Sharing a connection with a utility package

### ISSUE THREAD

**Issue by malbertSC** [typeorm/typeorm#1501]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have my project set up where one of the services consumes a utility package (via a private npm package), both of which use typeorm.  The service creates the typeorm connection using configurations in environment variables, and **I'd like to have the utility package use the same connection to query my database**.

If I try simply calling `getManager()` from the utility package, I get a `ConnectionNotFoundError`.  

If I try passing the connection from the main service to the utility functions in the utility package, and using that connection to getRepository() with an entity, I get a `RepositoryNotFoundError`.  I can, however, call getRepository with the table name as a string, and that "works", except doesn't have typings.  I'm guessing that the connection is retaining its configurations here, but the entities path is now wrong.  However, I'm defining the entities path using node_modules/my_package/*.js, which should be exactly the same for the service and the utility package (the entities live in a separate package and both the service and the utility package consume that package).  I also couldn't figure out if it was possible to change the "entities" path of an active connection, or add new paths.

Here's a minimal example of my main service:
```
import "reflect-metadata"
import { createConnection, getManager } from "typeorm";
import * as dotenv from "dotenv";
dotenv.config();

import { ApiUser } from "@gather/entities"; // entities defined here
import { utilities } from "@gather/permissions"; // utility functions here

createConnection() // defined in .env
    .then(async (connection) => {
        // works
        const test = await getManager().getRepository(ApiUser);
        console.log(await test.find());

        // Error: Postgres connection not initialized.  If I pass in the connection then it can't find my entities
        const apiUserPermissions = new utilities.ApiUserPermissions(10); // try also passing connection as a param
        const companiesWithPermission = await apiUserPermissions.getApiUser();
        console.log("listening");
    })
    .catch((err) => {
        console.error(err);
    })
```

and here's a minimal version of that utility class (get rid of this.connection to test with the default connection):
```
import { ApiUser } from "@gather/entities";
import { getManager, Connection } from "typeorm";

export class ApiUserPermissions {
    private apiUser: ApiUser;

    constructor(private apiUserID: number, private connection: Connection) {}

    public async getApiUser(): Promise<ApiUser> {
        let ApiUserRepository;
        try {
            ApiUserRepository = this.connection.getRepository(ApiUser);
        } catch (err) {
            if (err.name === "ConnectionNotFoundError") {
                throw new Error("Postgres connection not initialized");
            }
            throw err;
        }
        return ApiUserRepository.findOneById(this.apiUserID);
    }
}
```

in my env file, I have `TYPEORM_ENTITIES = node_modules/@gather/entities/dist/entities/*.js`

Am I doing something wrong here, or if not, what's the recommended approach?

**Comment by pleerock** [comment]
you need to load configuration from your `.env` (and transform them into connection options object) and append entities from your package. Something like this:

```ts
const connectionOptions = new ConnectionOptionsEnvReader().read();
connectionOptions.entities.push(...entitiesFromDifferentPackage);
```

**Comment by pleerock** [comment]
Looks like the issue was resolved. Reopen if needed.
