### ISSUE TITLE
How to achieve Polymorphic Relations?

### ISSUE THREAD

**Issue by dogscar** [typeorm/typeorm#1502]
the typeorm does't support Polymorphic Relations, so how can i do to achieve Polymorphic Relations like laravel?
@daniel-lang @pleerock 
https://laravel.com/docs/5.5/eloquent-relationships#polymorphic-relations

**Comment by pleerock** [comment]
so you basically do the same, you create a "type" column and "type id" column and just handle saving / hydration manually using query builder.

**Comment by pleerock** [comment]
Looks like the issue was resolved. Reopen if needed.

**Comment by kmccarth** [comment]
Hey @dogscar, 

I'd love to know what solution you eventually came to....We are porting from Laravel 5.7 to node as well, and we're evaluating how to handle polymorphism in TypeORM or sequelize-typescript. We've come to rely-on in a lot of situations, and we'd love to keep the paradigm. Thanks for any input in advanced.

K

**Comment by jtushman** [comment]
@pleerock would love to know if I am handling the "rehydration" the way your would.  And in general if this is how you would set up these relations.
