### ISSUE TITLE
Cannot eagerly query Entity with relation more than 3 levels deep

### ISSUE THREAD

**Issue by Toxicable** [typeorm/typeorm#1504]
**Issue type:**
[x] bug report

**Database system/driver:**
[x] `postgres`

**TypeORM version:**

[x] `latest`
[x] `@next`

**Steps to reproduce or a small repository showing the problem:**
Take a look in src/index.ts
https://github.com/Toxicable/issue-typeorm-nested-query

If you remove `'Entity2.Entity3.Entity4',` then the first query will pass. 
The second query is there to verify that the relationship is valid

**Comment by pleerock** [comment]
Fixed and will be released in next version.
