### ISSUE TITLE
'Order by' by few column product.

### ISSUE THREAD

**Issue by arnas** [typeorm/typeorm#1506]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Is it possible to `order by` by few columns product? 
For example  orderBy(`tablea.price * tableb.price`)
I tried variety of combination, but nothing worked.

**Comment by arnas** [comment]
It seems that it's possible to do that on general queries. But it fails in some combinations. I will provide sample code later.

**Comment by pleerock** [comment]
Any updates?

**Comment by pleerock** [comment]
Closing as no answer from reporter.
