### ISSUE TITLE
How to use SELECT FIND_IN_SET in typeorm?

### ISSUE THREAD

**Issue by imhari213** [typeorm/typeorm#1507]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
Can you please update your issue (looks like message is missing)

**Comment by pleerock** [comment]
Closing as no answer from reporter.

**Comment by yunfengsay** [comment]
so how to use FIND_IN_SET funciton in typeorm?

**Comment by JohnnyB9991** [comment]
Would like to know as well

**Comment by CrazyWood007** [comment]
I got it!
Just use `Raw`.
```
where: {
    someField: Raw((columnAlias) => `find_in_set(:value, ${columnAlias})`, { value: 'someValue' }),
}
```
