### ISSUE TITLE
MongoDB operators are detected as syntax error in `update`

### ISSUE THREAD

**Issue by dotansimha** [typeorm/typeorm#1509]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Using `next` version and MongoDB driver, I'm trying to use `$set` / `$push` / `$addToSet` with `repository.update` method.
TypeScript compiler detects it as error, since the partial object it expects is `DeepPartial<Entity>`, so the MongoDB operators are detected as invalid.

Maybe the signature of `update` should be something like:
```ts
export declare type DeepPartialWithMongoOperators<T> = {
    [P in keyof T]?: DeepPartial<T[P]>;
    $set?: { [P in keyof T]?: DeepPartial<T[P]>; }
    $push?: { [P in keyof T]?: DeepPartial<T[P]>; }
    $addToSet?: { [P in keyof T]?: DeepPartial<T[P]>; }
    // other MongoDB operators
};

update(criteria: string | string[] | number | number[] | Date | Date[] | ObjectID | ObjectID[] | DeepPartial<Entity>, partialEntity: DeepPartial<Entity> | DeepPartialWithMongoOperators<Entity>, options?: SaveOptions): Promise<UpdateResult>;

```

**Comment by pleerock** [comment]
`update` in repository is generic for all databases, thats why what you are talking about is not supported. Try to use `updateOne` or `updateMany` methods instead.

**Comment by dotansimha** [comment]
I see, thanks @pleerock .
My problem with using `updateOne` and `updateMany` is that my code now is coupled to MongoDB. 
When using any other DB with TypeORM, the code looks the same, and only the driver is different... Any plan to support a more generic API for MongoDB?

**Comment by pleerock** [comment]
Database systems are too much different. If you want to have generic api for all databases you'll be very limited (basically only general CRUD). Its not possible to make a good abstraction to support both mongodb and rdbms. I already told that its quite meaningless to abstract your application from the database you use, so Im strongly not recommend doing that.

**Comment by darkbasic** [comment]
The same problem applies with `find`: it doesn't accept a Mongo query. I would be fine to use something Mongo-specific like `findMany`, but there is nothing like that in `mongoManager`.

**Comment by pleerock** [comment]
darkbasic use mongo repository like this `mongoManager.getMongoRepository(X).findMany`

**Comment by darkbasic** [comment]
Don't you think that we should have a Mongo specific method for `find` without having to manually access the db? I mean, we already have `findOne`, so why not having `findMany` as well?

**Comment by pleerock** [comment]
@darkbasic from what I see from mongo documentation there is no findMany anymore, there is only `find` which does the same. And if we take a look on its signature it looks like this:

```ts

    /**
     * Creates a cursor for a query that can be used to iterate over results from MongoDB.
     *
     * @param query The cursor query object.
     * @see http://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html#find
     */
    find(query?: Object): Cursor<any>;
```

So, it creates a cursor. We already have a method that does the same:

```ts
mongoEntityManager.createCursor();
```

I checked the sources, it calls `find` method inside.

**Comment by darkbasic** [comment]
Yeah I know there is no `findMany` in mongo, I called it that way to dinguish the mongo-specific `find` from the db-agnostic `find`. I didn't know of `createCursor`, that's basically what I was searching for.

**Comment by darkbasic** [comment]
Also, how do I get the `ObjectId` function from in typeorm?
In Mongo driver I simply do `var ObjectId = require('mongodb').ObjectId`

It's required for queries like:
`connection.mongoManager.createCursor(User,{ _id: { $ne: ObjectId('5a719a62d8efb11fc82df741') }})`

**Comment by pleerock** [comment]
you probably need to do same, e.g. var ObjectId = require('mongodb').ObjectId
