### ISSUE TITLE
Remove entity using cascade options

### ISSUE THREAD

**Issue by royibernthal** [typeorm/typeorm#151]
I have 2 entities - EntityA and EntityB, they have a OneToOne relation with cascade options:

**EntityA.ts**

```
@OneToOne(type => EntityB, entityB => entityB.entityA, {
        cascadeInsert: true,
        cascadeUpdate: true,
        cascadeRemove: true
    })
entityB: EntityB;
```

Cascade options work for insert and update so far, but how do I make it work for remove?

For instance, I have:

`var entityA: EntityA = *finding in repo, inner join and select entityB*;`

entityA.entityB exists.

I tried to then null it like that:

`entityA.entityB = null;`

When I persist entityA, it simply breaks the connection between the entities (makes sense).
I'd like it to remove entityB, similarly to:

`entityBRepository.remove(entityB);`

How do I do that?

**Comment by pleerock** [comment]
There is one small bug I know with cascade remove in one-to-one relations. It should work fine with many-to-one/one-to-many relation, but does not in one-to-one relation. Maybe its because of that. I'll try to fix it this week. Would be great if you provide a minimum code that produces your error

**Comment by royibernthal** [comment]
Sure, I reproduced it with minimum code.
For some reason Github doesn't let me upload this ZIP, so I uploaded it to DropBox:
https://www.dropbox.com/s/3jrjzxed011ah95/typeorm_repr.zip?dl=1

Naturally, you'll need to change the db connection details in app.ts and recompile, and execute npm install to install the required dependencies.

Notice the rows in the db tables once you run node.

**Comment by royibernthal** [comment]
Hey, any news about this?

**Comment by pleerock** [comment]
fixed and released in `typeorm@0.0.7-alpha.18`

**Comment by royibernthal** [comment]
Is it fixed or did you simply remove the ability to have cascade options for these things?

**Comment by royibernthal** [comment]
Would it be possible to allow having remove cascade options on both sides of the relation (since both can be needed under different circumstances) and break circular removals when they happen?

**Comment by pleerock** [comment]
cascade removes are real pain. if you set cascade remove from both sides it will be logically incorrect. If you just set `post.category = null;` and between them circular cascade removes, then logically category should be removed and since category.post relation exist and there is cascade remove between them post in this case also should be removed, but this wasn't expected by user when he did just  `post.category = null;`

**Comment by royibernthal** [comment]
I understand the circular issue, but what I'm suggesting is that you track which relation caused the removal of an entity, and if that removal causes further removals that contain the removing entity, stop the function.
It might be a real pain to implement though depending on how your current implementation looks.

**Comment by pleerock** [comment]
I don't think that preventing it from removing is correct behaviour either.

**Comment by royibernthal** [comment]
For me it'd feel intuitive, but I guess that's very subjective. Wouldn't it be better than not allowing it altogether?

**Comment by royibernthal** [comment]
Anyhow, it doesn't work for me also when there's no circular issue and it's defined only on one side of the relation.
Here's another reproduction:
https://www.dropbox.com/s/xculrkptrjyatb1/typeorm_repr_cascade_remove.zip?dl=1

**Comment by pleerock** [comment]
this issue is not completely resolved, I'll return back to it in the near future

**Comment by joshuamking** [comment]
I am having the original issue on `0.1.0-alpha.8`. 

The only difference is that I have the following:

```
@Entity()
class EntityA extends EntityB { 
        @OneToOne(type => EntityC, {
		cascadeAll: true
	})
	@JoinColumn()
	entityC: EntityC;
}
@Entity()
class EntityD extends EntityB { }

@Entity()
class EntityC  { }
```

And so I don't have `EntityC` referencing `EntityA` at all because `EntityD` exists, but it still works on `cascadeUpdate` and `cascadeInsert`, **just not** `cascadeRemove`.

**Comment by pleerock** [comment]
per our discussion with @AlexMesser we are removing cascade remove functionality from ORM scope. You must use `onDelete` relation option and setup a database-level cascades to resolve your issue.
