### ISSUE TITLE
Unable to set mode="objectId" using entity schema JSON

### ISSUE THREAD

**Issue by dotansimha** [typeorm/typeorm#1510]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Using the `next` version, I'm trying to create a field for `_id` and mark it as `objectId` field. Without this field, I'm getting an exception here while trying to run `insert`, because `metadata.objectIdColumn` is undefined:
https://github.com/typeorm/typeorm/blob/next/src/driver/mongodb/MongoDriver.ts#L297

The relevant source code is here: 
https://github.com/typeorm/typeorm/blob/next/src/entity-schema/EntitySchemaTransformer.ts#L45-L55

Maybe this line: https://github.com/typeorm/typeorm/blob/next/src/entity-schema/EntitySchemaTransformer.ts#L59 should be `mode: tableColumn.mode || mode,`? 

Or maybe is there another way to declare the `id` field with the entity schema?

**Comment by dotansimha** [comment]
@pleerock 
I created a PR with a fix here: https://github.com/typeorm/typeorm/pull/1522

**Comment by pleerock** [comment]
thanks for the fix. Schemas were developed a long time age, before mongodb integration, that's why it was missing this functionality.
