### ISSUE TITLE
Self many-to-many relation for followers system

### ISSUE THREAD

**Issue by lewyuburi** [typeorm/typeorm#1511]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
`0.1.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi all, I need to create a basic followers system like Twitter or Instagram; I have the following entity:

```
@Entity()
class User {

  // columns
  @PrimaryGeneratedColumn()
  id: number;

  @Column('varchar', { length: 30 })
  firstName: string;

  @Column('varchar', { length: 30 })
  lastName: string;

  @Column('varchar')
  description: string;

  @Column('varchar')
  profileImgUrl: string;

  // Works!
  @ManyToMany(type => User, user => user.following)
  @JoinTable()
  followers: User[];

  // This not works as expected
  @ManyToMany(type => User)
  following: User[];

  // Works like a charm!
  @RelationCount((user: User) => user.followers)
  followersCount: number;
  
  // Then, this not works
  @RelationCount((user: User) => user.following)
  followingCount: number;
}
```

This creates two pivot tables in my database; not the best way. I only need the the `user` table and the `user_followers_user` that contains the columns `userId_1` and `userId_2` (user `userId_1` follows `userId_2`, then `userId_2`is followeb by ``userId_1)

**Comment by daniel-lang** [comment]
I modified your entity so that the second `@ManyToMany` (following) is complete.

```ts
@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("varchar", { length: 30 })
  firstName: string;

  @Column("varchar", { length: 30 })
  lastName: string;

  @Column("varchar")
  description: string;

  @Column("varchar")
  profileImgUrl: string;

  @ManyToMany(type => User, user => user.following)
  @JoinTable()
  followers: User[];

  @ManyToMany(type => User, user => user.followers)
  following: User[];

  @RelationCount((user: User) => user.followers)
  followersCount: number;
  
  @RelationCount((user: User) => user.following)
  followingCount: number;
}
```

With this change, I can load both `following` and `followers` and check `followersCount` and `followingCount`.
Can you try if that would do the trick for you?

**Comment by pleerock** [comment]
Closing as no answer from reporter. Looks like issue was resolved.

**Comment by arthur-mts** [comment]
@lewyuburi can you post the migration of this relation?

**Comment by santina** [comment]
For some reason when I try something similar, the migration doesn't contain that relation. The migration script just ignores all those relation, and only create the columns and the primary key. :(

**Comment by aitchkhan** [comment]
RelationCount is getting deprecated soon!
