### ISSUE TITLE
SelectQueryBuilder.getMany() time increases exponantially as row count increases

### ISSUE THREAD

**Issue by borremosch** [typeorm/typeorm#1515]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am trying to execute a relatively simple query that fetchets approximately 30.000 rows. It seems, however, that the query time increases exponentially with the number of rows. After some debugging, I found that the raw query is taking approximately 40 ms. The transform then takes 17 s, but the application takes ages (I have not waited tot see how long) in `SelectQueryBuilder.ts` at line 1723:

`await broadcaster.broadcastLoadEventsForAll(this.expressionMap.mainAlias.target, entities);`

Is the broadcaster perhaps notifying all loaded entities that all entities have been loaded? This would explain the exponential increase in query time. If this is the case, why is it doing this? And how do I turn of this functionality?

**Comment by pleerock** [comment]
this should be fixed in `next` (as well as other perf issues), can you please check it?

**Comment by borremosch** [comment]
You are right, it is fixed in `next`. Thanks a lot!
