### ISSUE TITLE
Error: Timeout of 15000ms exceeded. on ubuntu + docker + ci-test

### ISSUE THREAD

**Issue by cybermerlin** [typeorm/typeorm#1518]
after runed docker-compose up I run npm test
and noone test wasn't completed. How to fix that?

ubuntu latest
npm latest
nodejs latest
docker latest
source origin/master now latest
brain latest

**Comment by cybermerlin** [comment]
![image](https://user-images.githubusercontent.com/1460479/35486287-ff05b5f8-047c-11e8-82cf-99019caae31f.png)

**Comment by cybermerlin** [comment]
all trouble with 'mysql' using

How u use `npm test` in github?

**Comment by daniel-lang** [comment]
The gulp test task should run with docker without any extra setup needed. Your setup might be slow. Can you increase the maximum timeout and check if it will pass eventually.
https://github.com/typeorm/typeorm/blob/master/gulpfile.ts#L347

**Comment by cybermerlin** [comment]
up to 30.000 - not helped.
tonight I'm try again with 90.000

**Comment by daniel-lang** [comment]
Is it still failing on the second test?

**Comment by cybermerlin** [comment]
hello, yeah. If set 90.000 then will be ok.
thx

**Comment by pleerock** [comment]
hmm this is strange single test should not take 90 seconds to pass even on the slowest machine
