### ISSUE TITLE
Can I change the (postgresql) default schema?

### ISSUE THREAD

**Issue by mingyang91** [typeorm/typeorm#152]
I would like to design a SaaS multi-tenant software, the need to segregate tenant data. But I found `table_schema` can not be amended in `PostgresQueryRunner.ts`.
Can you add a way to modify `table_schema`?

**Comment by pleerock** [comment]
no, there is no. However you can contribute here and make a `schemaName` extra option in `DriverOptions` and use this option in a `PostgresQueryRunner` class. It should be easy.
