### ISSUE TITLE
Transactions with custom repositories

### ISSUE THREAD

**Issue by bilby91** [typeorm/typeorm#1521]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm just starting to look at typeorm as a replacement for sequelize. 

I'm wondering if it's possible to use transactions using custom repositories. Our code base uses that structure at the moment and we heavily rely on transactions. 

Thanks!

**Comment by pleerock** [comment]
yes:

```ts
connection.transaction(async entityManager => {
   await entityManager.getCustomRepository(YourRepository).someMethod();
});

**Comment by pleerock** [comment]
Looks like the issue was resolved. Reopen if needed.

**Comment by natikos** [comment]
@pleerock, should it work with two custom repositories? 
because in my case I have a record in the database, credentialsRepository throw Exception though.
```
await getConnection().transaction(async (manager) => {
      const adminEntity = await manager.getCustomRepository(WorkerRepository)
        .createWorker({ ...admin, position: WorkerPosition.ADMIN, phoneNumber: null });
      await manager.getCustomRepository(CredentialsRepository).savePassword(admin.password, adminEntity.id);
});
```

**Comment by sumeet-bansal** [comment]
@natikos did you figure out a solution for your issue? I'm running into the same problem.
