### ISSUE TITLE
Incorrect behavior with timestamp columns and custom type transformers

### ISSUE THREAD

**Issue by govorov** [typeorm/typeorm#1525]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.0-alpha.50`

Hi!
I've found a bug in how PostgresDriver works with custom date types.
Steps to reproduce:

1. Create `@Entity` where one of the columns is defined as this:
```ts
    @Column({
        type: 'timestamp',
        name: 'valid_till',
        transformer: {
                from(raw: Date): DateTime {                      
                        return DateTime.fromJSDate(raw);
                },
                to (date: DateTime): Date {
                        return date.toJSDate();
                },
        },
    })
    validTill: DateTime;
```
where `DateTime` is `import { DateTime } from 'luxon';`

2. PostgresDriver.prepareHydratedValue has an error in condition there https://github.com/typeorm/typeorm/blob/82b1410f0e4d7e481f596874fa5c303e3c50019c/src/driver/postgres/PostgresDriver.ts#L302

So `normalizeHydratedDate` gets called and due to https://github.com/typeorm/typeorm/blob/82b1410f0e4d7e481f596874fa5c303e3c50019c/src/util/DateUtils.ts#L23 there's no way to get anything but vanilla js `Date`

Next typeorm attempts to create `Date` instance even if a `DateTime` object is returned from transformer.
Thereby every time I try to fetch models from a database typeorm tries to call js-native Date methods on custom DateTime object and errors like this occur:
```
TypeError: date.getFullYear is not a function
```

Thank you!

**Comment by tmstieff** [comment]
This also affects @next release.

**Comment by pleerock** [comment]
@govorov is it related to #1140 ?

**Comment by govorov** [comment]
Yes. And that's really awesome that #1547 has been merged :)
Thank you!
