### ISSUE TITLE
Set CreateDateColumn programmatically

### ISSUE THREAD

**Issue by timojokinen** [typeorm/typeorm#1529]
Is there a way to set a CreateDateColumn in the code?
I'm on version two of an app and i want to import the data of the old application which is in another format. Normally the behavior of CreateDateColumn is what I need but not when importing the old data.

**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] `^0.1.7` (or put your version here)

**Comment by pleerock** [comment]
no, there is no. If your data does not fit CreateDateColumn requirements then you just need to create a regular column and implement creation / updation functionality manually. Its easy to implement having subscribers and listeners functionality.

**Comment by pleerock** [comment]
Looks like the issue was resolved. Reopen if needed.

**Comment by EduardsE** [comment]
@pleerock We tried to upgrade to 0.2 but it had some other issues, so we had to rollback previous version. I'll check it out later.

**Comment by EduardsE** [comment]
@pleerock The issue previously was that the **CreateDateColumn** and **UpdateDateColumn** decorators stopped working and I couldn't figure out why. Now I know that you have to take care of the timestamp saving in the database yourself.
