### ISSUE TITLE
ormconfig.json relative path?

### ISSUE THREAD

**Issue by CocaColaBear** [typeorm/typeorm#153]
Can I put in ormconfig.json relative path? Absolute path is working fine, but relative - not :(
```
"entities" : [
    "../compiled/core/entities/*.js"
]
```
Project structure:
project
```
__complied
____core
______entities
__app.js
__src
____core
______entities
__app.ts
tsconfig.json
ormconfig.json
```
I'm trying:
```
"./compiled/core/entities/*.js",
"./compiled/core/entities/*.js",
"/compiled/core/entities/*.js",
"compiled/core/entities/*.js"
```
And many-many other))

**Comment by eduardoweiland** [comment]
I use relative paths and it works. I use:

```
"entities": ["build/entity/*.js"]
```

This should be relative to the _current working directory_. So, you should `cd` into your project root before running it.

**Comment by CocaColaBear** [comment]
@eduardoweiland im run from project root:
npm ./compiled/app.js
