### ISSUE TITLE
Array type default value doesnt work. PostgreSQL

### ISSUE THREAD

**Issue by CocaColaBear** [typeorm/typeorm#1532]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
My entity column:
``` ts
@Column("float4", {
	array: true,
	default: [ 0.0, 0.0, 0.0 ],
	nullable: false
})
public testFloatArray: number[];
```
This generate query:
``` sql
ALTER TABLE "public"."test" ADD "testFloatArray" real array NOT NULL DEFAULT '[0,0,0]'
```
And i got an error: ``error: malformed array literal: "[0,0,0]``
The PostgresSQL syntax should be:
``` sql
ALTER TABLE "public"."test" ADD "testFloatArray" real array NOT NULL DEFAULT '{0,0,0}'
```

**Comment by pleerock** [comment]
You can do:

```ts
@Column("float4", {
	array: true,
	default: () => [ 0.0, 0.0, 0.0 ],
	nullable: false
})
public testFloatArray: number[];
```

**Comment by CocaColaBear** [comment]
@pleerock your decision gives an error.
Error: 
```
error: syntax error at or near "0"
```
Query: 
``` sql
ALTER TABLE "public"."test" ADD "testFloatArray" real array NOT NULL DEFAULT 0,0,0
```

**Comment by CocaColaBear** [comment]
``` ts
default: "{0.0, 0.0, 0.0}",
```
Works fine

**Comment by pleerock** [comment]
👍

**Comment by thematan** [comment]
If someone comes here to search for initializing empty array
this works:

 default: ()=>'array[]::integer[]'

**Comment by thematan** [comment]
the '::' is cast syntax in postgres.
It might be redundant

**Comment by vlapo** [comment]
Hi @thematan. Typeorm from version 0.2.12 support define default enum array as array of typescript enum https://github.com/typeorm/typeorm/pull/3414:
```typescript
@Column({
    type: "enum",
    enum: StringEnum,
    array: true,
    default: [StringEnum.ADMIN]
})
stringEnums: StringEnum[];
```

**Comment by joekendal** [comment]
@thematan what about for an array of type string? 'array[]::string[]' doesn't work 🤨

**Comment by jtrein** [comment]
@joekendal Try this:

```js
default: () => 'array[]::text[]'
```

**Comment by LyricL-Gitster** [comment]
While it's nice to have a workaround, it still feels like `default: []` should work and this should be open.

**Comment by fr1sk** [comment]
@pleerock please reopen this. I agree that `default: []` should work, it's super intuitive.

**Comment by gabimor** [comment]
any update on this ?
We have a thing with our migrations regarding this.
Our column:
```
@Column({ type: 'text', nullable: false, array: true, default: 'array[]' })
someColumnName: string[]
```
and although the column is creted on the DB just fine, the migrations are keep being generated for this column like so:

```
await queryRunner.query(`COMMENT ON COLUMN "event"."someColumnName" IS NULL`);
await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "someColumnName" SET DEFAULT 'array[]'::text[]`);
```

we have to manually delete them from the migration file each time, it's frustrating.

We tried also `default: '{}'`, `default: 'ARRAY[]'` nothing works. the column migration keep being generated each time

**Comment by nebkat** [comment]
I will try to incorporate this into #7282, but could someone give me a few examples of the expected inputs/outputs? What happens if the array contains mixed types, nulls, etc?

@gabimor default values defined as strings are treated as string values. You must use the `() => 'array[]'` syntax if you want it to be treated as a raw value.

**Comment by edeesis** [comment]
I have submitted a PR with a couple of test cases that I would expect would work. If anyone has any others they'd like to add, I can add them to my PR.

**Comment by c1moore** [comment]
Has this reverted?  I'm seeing this issue in v0.2.34

**Comment by edeesis** [comment]
https://github.com/typeorm/typeorm/commit/724d80bf1aacedfc139ad09fe5842cad8fdb2893 this commit was added to the method that i changed, and there's also a couple of commits tagged against this ticket. We're still using 0.2.32, so haven't seen the issue yet.

**Comment by mashirozx** [comment]
> Hi @thematan. Typeorm from version 0.2.12 support define default enum array as array of typescript enum #3414:
> 
> ```ts
> @Column({
>     type: "enum",
>     enum: StringEnum,
>     array: true,
>     default: [StringEnum.ADMIN]
> })
> stringEnums: StringEnum[];
> ```

Not working now:

```
[Nest] 4856  - 12/30/2021, 2:08:13 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'array ('user', 'admin') NOT NULL DEFAULT 'user'' at line 1
```

**Comment by jonfreeland** [comment]
For a text array default value, I had to account for whether a value in the array had any spaces.
```javascript
`'{${defaultValues.map((value) => (value.includes(" ") ? `"${value}"` : value)).join(",")}}'`;
```

PostgreSQL will strip unnecessary `"`s, which will cause the migration to be continually generated if you don't account for this.
