### ISSUE TITLE
how to update an array column ? 

### ISSUE THREAD

**Issue by qballer** [typeorm/typeorm#1538]
**Issue type:**
[x ] question
**Database system/driver:**
[x ] `postgres`
**TypeORM version:**
[x ] `0.1.11` (or put your version here)

```
@Entity()
export class SomeEntity {
    @PrimaryGeneratedColumn() id: number;
 // ...
    @Column("simple-array") values: string[] = [];
}
```

Is there any way to push a value to the array with ```queryBuilder```. Technically there can be a race condition (right?) if I do this:  get the entity push to ```values``` and then save. 

any suggestions?

**Comment by pleerock** [comment]
That's why its "simple-array". Just treat it like you are concatenating a string and saving a model. If you need advanced functionality then maybe native postgres arrays can solve your issues.

**Comment by pleerock** [comment]
Looks like the issue was resolved. Feel free to reopen.
