### ISSUE TITLE
Unable to use BaseEntity-based access when using serverless-offline

### ISSUE THREAD

**Issue by mellocello2003** [typeorm/typeorm#1540]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Stepping through the code, it looks like `Connection.findMetadata` is comparing metadata by reference to the entityMetadatas.  On the first request, this works fine.  For some reason, on the second request, the comparison fails.  I feel like I could fix this if I could override this behavior so that it uses string comparisons.

As a result, on the first request, things work, but after that I get:
"No repository for * was found. Looks like this entity is not registered in current "default" connection?'"

I am importing reflect-metadata.

I'm not entirely sure why this is happening but a workaround is to use the repository pattern.

**Comment by mellocello2003** [comment]
For reference.  Let me know if you need more detail:

```
import { graphqlLambda, graphiqlLambda } from 'apollo-server-lambda';
import { makeExecutableSchema } from 'graphql-tools';
import { GraphQLUtility } from 'xxx';
import { GraphQLString, GraphQLInt } from 'graphql/type/scalars';
const GraphQLDate = require('graphql-iso-date').GraphQLDate;
const GraphQLDateTime = require('graphql-iso-date').GraphQLDateTime;
import { FARMS, FIELDS, ZONES } from './mocks';
import 'reflect-metadata';
import { User } from './entity/User';
import { createConnection, getConnection, getConnectionManager } from 'typeorm';
import { ConnectionManager } from 'typeorm/connection/ConnectionManager';
import { Connection } from 'typeorm/connection/Connection';
const schema = GraphQLUtility.readSchema('farm');

export const initialize = function(): Promise<Connection> {
  const manager: ConnectionManager = getConnectionManager();
  if (manager.has('default')) {
    return Promise.resolve(manager.get());
  } else {
    console.log('Initializing...');
    return createConnection();
  }
};

const resolvers = {
  Year: GraphQLInt,
  WKT: GraphQLString,
  Date: GraphQLDate,
  DateTime: GraphQLDateTime,
  Query: {
    farm: () => {
      return FARMS.farmId1;
    },
    farms: async () => {
      const connection = await initialize();
      // This works:
      // const repository = connection.getRepository<User>('User');
      // const users = await repository.find();
      //
      // This doesn't:
      const users = User.find();
      //
      console.info(JSON.stringify(users, null, 2));
      return Object.keys(FARMS).map(key => FARMS[key]);
    },
    field: () => {
      return FIELDS.fieldId1;
    },
    fields: () => {
      return Object.keys(FIELDS).map(key => FIELDS[key]);
    },
    zone: () => {
      return ZONES.zoneId1;
    }
  }
};

const myGraphQLSchema = makeExecutableSchema({
  typeDefs: schema,
  resolvers,
  logger: console
});

export const graphqlHandler = async function graphqlHandler(event: any, context: any, callback: any) {
  function callbackFilter(error: any, output: any) {
    output.headers['Access-Control-Allow-Origin'] = '*';
    callback(error, output);
  }

  const handler = graphqlLambda({ schema: myGraphQLSchema, tracing: true });
  return handler(event, context, callbackFilter);
};

export const graphiqlHandler = graphiqlLambda({
  endpointURL: process.env.IA_FARMAPI_ENDPOINT
    ? process.env.IA_FARMAPI_ENDPOINT
    : `/${process.env.IA_FARMAPI_ENV}/graphql`
});
```

**Comment by mellocello2003** [comment]
Looks I can get this to fail by simply changing:
```
const repository = connection.getRepository<User>('User');
```
to
```
const repository = connection.getRepository<User>(User);
```

**Comment by Bnaya** [comment]
@mellocello2003 there's a thing with lambdas (and also sls offline) with the function is "hot"
means some stuff are shared with the previous run of the function. usually state inside imported modules

**Comment by pleerock** [comment]
Sounds strange, can it be related somehow to lambdas, sever architecture? Can you test your issue on regular server?

**Comment by mellocello2003** [comment]
@pleerock, it's definitely related to using lambda/serverless architecture - it works fine in other cases.  But I'm not sure what's causing it.  I'm using serverless-offline, and I haven't tested it *in* lambda - so maybe it's just serverless-offline that's causing it.

Does it make sense to use a string-based comparison under the covers, or allow for overriding of the behavior that matches a class with an entity?  Let me know what you think about that.  (Not sure if it's worth it, but I figured I'd throw it out there).

For now, I can move forward without BaseEntities, but it's unfortunate that we can't standardize (other teams are using BaseEntity-based CRUD at my company).

**Comment by pleerock** [comment]
yes, its okay to use string name as well, if you don't have classes with duplicate names, e.g. two entities called `User`.

**Comment by pleerock** [comment]
I think this issue was resolved.

**Comment by chanlito** [comment]
Also getting `Serverless: Failure: No metadata for "User" was found.` anyone found a solution?

**Comment by jkomorek** [comment]
For anyone else who may find this, I was getting this same error when testing a lambda function locally using serverless offline. However, the issue was not happening when running my lambda in AWS.

A workaround which is so far working for me is rather than passing an object into my entity manager I pass a string as mentioned above. The only difference is that I am using Entity.name in an effort to avoid magic string.

ex: 
`let account = await connection.manager.findOne(Account.name, myAccountName);`

**Comment by eltonio450** [comment]
@jkomorek but in this case, the typing is wrong no ? it loses the track of the second argument type ?

In your case, the inferred type of account is the one of myAccountName ?

Thanks
