### ISSUE TITLE
Creating Custom Generated Column Value

### ISSUE THREAD

**Issue by PawanKr2feb** [typeorm/typeorm#1542]
I am looking for a way to create some custom value for my Column in entity.

Ex:

```ts
@Entity("DemandRecord")
   export class DemandRecord {

    @CustomColumn()
     demandRecordNumber: number;
```

Ex:- demandRecordNumber values should be like YYYYMMDD001,YYYYMMDD002..like this where YYYYMMDD is year,month and date.

Am i not able to find any approach for this. In Hibernate we have ways to this but in TypeORM..i am not able to find any documents regarding this

**Comment by pleerock** [comment]
Its not clear what you are requesting - please provide a detailed description of your feature request.

**Comment by pleerock** [comment]
Closing as no answer from reporter.

**Comment by PawanKr2feb** [comment]
Added the extra information

**Comment by sevenryze** [comment]
I find that i need the same feature.

For now, when use `@PrimaryGeneratedColumn()` decorator, we get only two types of generation strategy - increment and uuid.  What i need is the ability to set a custom value to the generated column, maybe the option object could add a property - value - which could get a function to call to return the value we need. 

if you think this feature is useful, i think i could give a PR.

**Comment by pleerock** [comment]
there is no need to create a new decorator, simply use `@PrimaryColumn` decorator and generate its value anywhere - in the class itself, in the listeners, simply by assigning your value to class property.

**Comment by PawanKr2feb** [comment]
Can you please give a small code snippet for the above requirement..not able to get what you are trying to say

**Comment by pleerock** [comment]
```ts
@Entity()
export class Post {

   @PrimaryColumn()
   id: string;

}
```

You want to have a manually generated value for id, right? Then Just Do It.

```ts
const post = new Post();
post.id = "your-value";
manager.save(post);
```

**Comment by PawanKr2feb** [comment]
What we are trying to say that in hibernate, there is a special way to achieve the scenario mentioned above..since typeorm is almost similar to hibernate so why don't we can achieve that in typeorm..what u mention above will help but it will time consuming for a developer if they have to autogenreate a value which is dependent on a DB column

**Comment by pleerock** [comment]
There is no need for additional functionality in there.

Alternative to that approach you can do:

```ts
@Entity()
export class Post {

   @PrimaryColumn()
   id: string;

  @BeforeInsert()
  private beforeInsert() {
         this.id = generateAnything();
  }

}
```

**Comment by sevenryze** [comment]
@pleerock Wow, that's great. Sorry for that i just didn't notice this listener api. 😄

**Comment by webleaf** [comment]
@pleerock what about async query inside `@BeforeInsert` or `@AfterInsert`? What if I need to make query inside these methods to generate id...

**Comment by webleaf** [comment]
@pleerock for example if I try to do something like this (saving multiply objects at once)
```
@Entity()
class SomeClass {

    @PrimaryColumn()
    public id: number;

    @AfterInsert()
    private async afterInsert() {
        const result = await getRepository(OMomentType).query("SELECT last_insert_rowid() last_id");
        this.id = result[0]["last_id"]
    }

    constructor(id?: number) {
        if (this.id == null && typeof id === "number") {
            this.id = id
        }
    }
}

getRepository(SomeClass).save([
    new SomeClass(-3),
    new SomeClass(-2),
    new SomeClass(), // -1
    new SomeClass(), // 0
    new SomeClass(), // 1
    new SomeClass(), // 2
]);
```
Such log will be produced:
```
JS: query: BEGIN TRANSACTION
JS: query: INSERT INTO "some_class"("id") VALUES (?) -- PARAMETERS: [-3]
JS: query: INSERT INTO "some_class"("id") VALUES (?) -- PARAMETERS: [-2]
JS: query: INSERT INTO "some_class"("id") VALUES (NULL) -- PARAMETERS: []
JS: query: INSERT INTO "some_class"("id") VALUES (NULL) -- PARAMETERS: []
JS: query: INSERT INTO "some_class"("id") VALUES (NULL) -- PARAMETERS: []
JS: query: INSERT INTO "some_class"("id") VALUES (NULL) -- PARAMETERS: []
JS: query: SELECT last_insert_rowid() last_id
JS: query: SELECT last_insert_rowid() last_id
JS: query: SELECT last_insert_rowid() last_id
JS: query: SELECT last_insert_rowid() last_id
JS: query: SELECT last_insert_rowid() last_id
JS: query: COMMIT
```
And all objects with undefined `id` will get id `2`, because all `@AfterInsert` executes after all insert queries.

**Comment by charmstead** [comment]
I think what you seek @PawanKr2feb  is here [https://stackoverflow.com/questions/52157791/how-do-you-set-a-custom-default-unique-id-string-for-the-primarygeneratedcolumn](url)

**Comment by muhammadullah1** [comment]
here you can generate custom id in typeorm

export function generateId(pre: string, length: number) {
    const randomId = Math.floor(Math.random() * 10000).toString().padStart(length, '0');
    return `${pre}-${randomId}`;
}

 @PrimaryColumn('varchar', { default: () => `'${generateId('PR', 4)}'` })
    id: string;

**Comment by chrisk8er** [comment]
If you using Postgres, you can use this technique. First, create an ID column like this:
```
@PrimaryColumn({
    generatedType: 'STORED',
    asExpression: `generate_ticket_id()`,
  })
  code: string;
```

then add this code inside the migration file to create a Postgres function:
```
public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
CREATE OR REPLACE FUNCTION generate_ticket_id() RETURNS text AS $$
BEGIN
  RETURN 'TIC-' || TO_CHAR(CURRENT_DATE, 'YYYYMMDD') || LPAD(nextval('ticket_id_seq')::text, 4, '0');
END;
$$ LANGUAGE plpgsql IMMUTABLE;
`);

public async down(queryRunner: QueryRunner): Promise<void> {
  await queryRunner.query(`DROP FUNCTION generate_ticket_id()`);
  }
```

Hope it helps.

**Comment by maks-rafalko** [comment]
@chrisk8er am I right that in this case you can't create schema by running `typeorm schema:sync`? It will fail because of non-existining `generate_ticket_id()`

What I don't get is how to create sequences from TypeORM mapping
