### ISSUE TITLE
Support any column type for SQL.js?

### ISSUE THREAD

**Issue by VinceOPS** [typeorm/typeorm#1543]
Hi there! We're using `sql.js` to run our unit tests against our code, and this is actually very convenient (as it allows us doing this even if PgSQL is not available/running on the machine). **The best approach would actually be to mock the Connection and its repositories (instead of using an in-mem db), but I did not look for a clean way to do it yet...**

# However...

**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[x] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Connect to a database with `type` being "sql.js" and with `entities` containing an entity with a @Column of `type` "timestamp".

We can see in many places that SQLite should be able to support any type (including [timestamp](https://stackoverflow.com/a/20627380/4365807), also [here](http://www.numericalexpert.com/blog/sqlite_blob_time/sqlite_time_etc.html)), as stated in the [documentation](https://www.sqlite.org/datatypes.html) of the v2),
If SQL.js is a port of SQLite, and SQLite is "typeless", should TypeORM accepts any type for the columns of the entities given to a sql.js database?

At the current time, this is what we get when running our unit tests:

> DataTypeNotSupportedError: Data type "timestamp" in "EntityName.createdAt" is not supported by "sqljs" database.

Thanks for this beautiful project!

**Comment by pleerock** [comment]
@daniel-lang what do you think about it?

**Comment by VinceOPS** [comment]
Hi @pleerock!
Thanks for your interest in this issue. 

Just to keep you posted, I started working on a proposal two days ago, using the same condition than [this one](https://github.com/typeorm/typeorm/blob/master/src/metadata-builder/EntityMetadataValidator.ts#L74) in order to skip metadata validation for SqljsDriver... But it might be a too hard cut. Thus, I started implement an optional option in the configuration of SqljsDriver, as a [connection option](https://github.com/typeorm/typeorm/blob/master/src/driver/sqljs/SqljsConnectionOptions.ts), but it might be a too personal/custom change...

At the present time, I'd rather wait for your opinion before changing anything :). I tried mocking everything (connection, entity manager, etc) but it's a lot of boilerplate code and could not get something fully working. Thus, at the present time, we just keep running our unit tests against a real database (pgsql).

**Comment by pleerock** [comment]
Maybe its a better idea to create a separate driver type specially for testing purpose? Which can be based on sqljs

**Comment by VinceOPS** [comment]
That sounds great!

**Comment by pleerock** [comment]
@VinceOPS I think it would be great to have a page in our documentation about "How to do testing" with TypeORM, where we provide information about all user cases and what tools we provide to solve their testing problems. It can be a good start point for us to provide all necessary testing infrastructure for users if we start with list of problems user face when he write test for apps using typeorm.

**Comment by VinceOPS** [comment]
@pleerock 

In this very specific case, this is about unit-testing a service handling our business logic. The service depends on a custom repository (which is injected using DI) and we want to tests the business code and spy the custom repository (make sure that proper requests are made when no error is thrown, for instance). However, creating a custom repository requires a valid connection to the database.
This is the most common case (for us) in unit testing, with or without a custom repository (sometimes the default one is enough). I can provide a code sample if required (NestJs project).

For the other most common case (e2e testing), I will _personally_ always stick to my real database system.

**Comment by pleerock** [comment]
It would be great if someone can take initiative on this question and implement all the tools people need do easy and proper testing using typeorm for both e2e and unit testing. 

We have similar discussion in #1267 and #171

**Comment by VinceOPS** [comment]
I'd be glad to help if a few directions are given. I'm pretty new to TypeORM but the code is clear and documented so this is not an issue.
Shall we create a dedicated module/repository as a library or integrate the tools/classes in the existing codebase? Do you have any clues regarding the best approach to mock the connection and all its dependencies? If it helps a lot, would you be ready to add a few helpers/methods in the codebase (simple hypothesis)?

Thanks

**Comment by pleerock** [comment]
First we shall start with the list of all possible problems user face during writing unit/functional/e2e tests. Second we'll think what tools we shall provide to resolve those problems. Third we'll start implementation. First and second steps what we shall start with.

**Comment by pleerock** [comment]
Let's keep discussion in a single thread. Closing in favour of #1267.
