### ISSUE TITLE
Synchronize option triggers errors with Postgres extensions tables

### ISSUE THREAD

**Issue by RDeluxe** [typeorm/typeorm#1552]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

To reproduce, simply `CREATE EXTENSION postgis;` as a superuser in your database, then launch your server with the dropSchema option set to true. 
While trying to delete all the tables in the database, it will fail to delete the postgis table (as it should). I'm not 100% sure it is supposed to drop tables not linked to entities ?

**Comment by pleerock** [comment]
yes, currently it removes all tables in your database. Does `CREATE EXTENSION postgis;` create new tables in the database?

**Comment by RDeluxe** [comment]
Yes, it does, and they belong to a superuser (because extensions need to be installed via a superuser).

**Comment by pleerock** [comment]
Okay we'll take a look on those issues closer in 0.2.0

**Comment by AlexMesser** [comment]
I will return to this issue when i will work on #370

**Comment by AlexMesser** [comment]
#2423
