### ISSUE TITLE
Add support for specifying javascript type (boolean)

### ISSUE THREAD

**Issue by BrendanBall** [typeorm/typeorm#1557]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x` (or put your version here) ^0.1.11

I need a boolean column type in mysql, and currently you need to specify the column type to be `tinyint`. This however results in my boolean column being `1` or `0` instead of `true` or `false`. I use javascript (which typeorm supposedly supports) so I cannot explicitly specify the type to be `boolean` like in typescript (eg. `isPublished: boolean;`). I need an extra `ColumnOptions` that specifies the javascript type so that I can do:
```js
  @Column({
    type: 'tinyint',
    jsType: 'boolean'
    name: 'enabled'
  })
  enabled = null
```
I would think that if you support javascript and mysql there should be a way to use booleans without any extra effort like creating my own custom `ValueTransformer`.

**Comment by pleerock** [comment]
try 

```ts
@Column({
    type: Boolean
  })
  enabled = null
```

**Comment by BrendanBall** [comment]
@pleerock that seems to work... . I think we need some documentation around this. All the docs I read basically say the `type` option must be a string and is the database type, not the javascript type. So why does 
```js
@Column({
    type: Boolean
  })
  enabled = null
``` 
work differently to
```js
@Column({
    type: "boolean"
  })
  enabled = null
``` 
which throws an error saying mysql doesn't support boolean. In particular I read the issue https://github.com/typeorm/typeorm/issues/642 where you say "if you define column type explicitly then you must use tinyint because explicitly defined types are now only database-supported types". So using `type: Boolean` is very confusing and undocumented behaviour.

Thanks anyway for responding so quickly :)
