### ISSUE TITLE
Getting id of relation without joining the whole table

### ISSUE THREAD

**Issue by royibernthal** [typeorm/typeorm#156]
Let's say I have a OneToOne relation between two entities.

I'd like to be able to fetch from each of them (even from the one that's not the owning side of the relation) - the id of the other entity in the relation, as a number, without having to join the whole entity.

In other words, I'd like to only join the id column of the joined table (/entity).

For example:

EntityA has a OneToOne relation with EntityB.

I'd like to fetch EntityA and innerJoinAndSelect EntityB, but EntityB (entityA.entityB) will only contain its id, instead of all is columns.

Is there a way to do it?

**Comment by pleerock** [comment]
Lets say you have two entities:

```typescript
export class Post {
    id: number;

    @ManyToOne(type => Category, category => category.posts)
    category: Category;
}
```

```typescript
export class Category {
    id: number;

    @OneToMany(type => Post, post => post.category)
    posts: Post[];
}
```

If you want to have relation in on the `Post` side you can add extra column:


```typescript
export class Post {
    id: number;

    @ManyToOne(type => Category, category => category.posts)
    @JoinColumn({ name: "categoryId" })
    category: Category;
 
    categoryId: number;
}
```

And this will make a trick - you'll not have need to join category, and in categoryId will always have a category id number.

However if you want to have array of post ids on the Category side, its problematic because we need to perform extra query to load data from inverse table. But I have in plans to implement such feature in the future.

Same rules applies to one-to-one relation. This trick will only work on owner side of relationship.

There is also a `@RelationId` decorator usage of which you can find in samples and tests, however there are few noticeable bugs with it that I need to fix, before I can tell that it works well.

**Comment by mingyang91** [comment]
```@RelationId``` is exactly what I need, and I will use it and feed back the issues that may arise.
thank you!

**Comment by royibernthal** [comment]
Thanks :)
Will that trick also work on the not owning side of a OneToOne relation?
@RelationId seems like a great idea, any ETA for when it'll be stabilized?

**Comment by pleerock** [comment]
its not in priority, but I guess it will be somewhere in end-jan, mid-feb

**Comment by royibernthal** [comment]
I see, thanks for the info.
Can you please also answer my question:
Will that trick also work on the not owning side of a OneToOne relation?

**Comment by pleerock** [comment]
Im not sure to be honest... Working with non owning side is a real mess... Try it, if it will not work, then wait until I'll implement `@RelationId`. Or contribute there if you want.

**Comment by pleerock** [comment]
again, use relation id for this functionality. Its support is now much better in 0.1.0 releases.

**Comment by RobertWacker** [comment]
> Lets say you have two entities:
> 
> ```ts
> export class Post {
>     id: number;
> 
>     @ManyToOne(type => Category, category => category.posts)
>     category: Category;
> }
> ```
> 
> ```ts
> export class Category {
>     id: number;
> 
>     @OneToMany(type => Post, post => post.category)
>     posts: Post[];
> }
> ```
> 
> If you want to have relation in on the `Post` side you can add extra column:
> 
> ```ts
> export class Post {
>     id: number;
> 
>     @ManyToOne(type => Category, category => category.posts)
>     @JoinColumn({ name: "categoryId" })
>     category: Category;
>  
>     @Column({ nullable: false })
>     categoryId: number;
> }
> ```
> 
> And this will make a trick - you'll not have need to join category, and in categoryId will always have a category id number.
> 
> However if you want to have array of post ids on the Category side, its problematic because we need to perform extra query to load data from inverse table. But I have in plans to implement such feature in the future.
> 
> Same rules applies to one-to-one relation. This trick will only work on owner side of relationship.
> 
> There is also a `@RelationId` decorator usage of which you can find in samples and tests, however there are few noticeable bugs with it that I need to fix, before I can tell that it works well.

you save me!

**Comment by JaosnHsieh** [comment]
it works!!
https://github.com/typeorm/typeorm/blob/master/docs/decorator-reference.md#relationid

**Comment by shaniqwa** [comment]
I am using RelationId which is a really nice idea, but it has terrible performance issues. BEWARE!

**Comment by Beloin** [comment]
I do want to use it. We could use the other trick as @pleerock  said earlier. But using ```@RelationId``` seems more right.

**Comment by googlicius** [comment]
@pleerock Actually you can add extra field without `@Column`:
```javascript
@ManyToOne(type => Category)
@JoinColumn({ name: "category_id" })
category: Category;

category_id: number;
```

**Comment by mlarabi** [comment]
The other solution using the QueryBuilder is to add `.loadAllRelationIds()`.
It will add the id of the relations to the property instead of loading the entire object into it.

**Comment by qstyler** [comment]
I'd really love to see an option to have it this way:
```
{
  "relationEntity": {
    "id": 1
  }
}
```

`@RelationID()` decorator and seems to be a very hacky solution.
I'm using interfaces and implementing them as entities. 
And I have to create extra properties to work with relations.
```
export interface Entity {
  relationEntity: RelationEntity;
  relationEneityId: number;
}
```

This is ugly and hacky.

**Comment by stouch** [comment]
It's 2024 and we still need to create an ugly property with "Id" suffix to get the column value without joining the table..?

**Comment by stouch** [comment]
Are we supposed to use https://github.com/typeorm/typeorm/blob/master/docs/decorator-reference.md#relationid ? or is it correct to set another property wtih "Id" suffix like this suggestion : https://github.com/typeorm/typeorm/issues/156#issuecomment-269579837

Is there any official recommendation about this?
