### ISSUE TITLE
Error during migration generation: Unexpected token import 

### ISSUE THREAD

**Issue by sinner** [typeorm/typeorm#1561]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ x ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following orm configuration json file:

```json
{
   "type": "mysql",
   "host": "localhost",
   "port": 13306,
   "username": "root",
   "password": "acclink",
   "database": "ts_test",
   "synchronize": true,
   "logging": false,
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migrations/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migrations",
      "subscribersDir": "src/subscriber"
   }
}
```

I have this ***User*** entity class:

```typescript

import {Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, ManyToOne} from "typeorm";

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        type: "varchar",
        length: 150,
        unique: true
    })
    uuid: string;

    @Column({
        type: "varchar",
        length: 180,
        unique: true
    })
    email: string;

    @Column({
        type: "varchar",
        length: 20,
        unique: true
    })
    username: string;

    @Column({
        type: "varchar",
        length: 150
    })
    password: string;

    @Column({
        type: "varchar",
        length: 150
    })
    salt: string;

    @Column({
        type: "varchar",
        length: 150
    })
    displayName: string;

    @Column({
        type: "varchar",
        length: 150
    })
    activationCode: string;

    @Column({type: "json"})
    role: string;

    @CreateDateColumn()
    createdAt: Date;

    @ManyToOne(type => User)
    userCreator: User;

    @UpdateDateColumn()
    updatedAt: Date;

    @ManyToOne(type => User)
    userUpdater: User;

    @Column({type: "boolean"})
    isActive: boolean;

}

```

And my UserRepository class is the following:

```typescript

import {EntityRepository, Repository} from "typeorm";
import {User} from "../User";

@EntityRepository(User)
export class UserRepository extends Repository<User> {

    public findByName(displayName: string) {
        return this.findOne({ displayName });
    }

}

```

If I execute the command to generate a migration, it gives me the following error:

```sh

$ typeorm migrations:generate -n
Error during migration generation:
/var/www/javascript/api-coins/src/entity/repository/UserRepository.ts:1
(function (exports, require, module, __filename, __dirname) { import {EntityRepository, Repository} from "typeorm";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Function.PlatformTools.load (/opt/node/lib/node_modules/typeorm/platform/PlatformTools.js:124:28)

```
I've removed the content of my UserRepository class, I receive the following error:

```sh
$ typeorm migrations:generate -n
Error during migration generation:
/var/www/javascript/api-coins/src/entity/repository/UserRepository.ts:1
(function (exports, require, module, __filename, __dirname) { import {EntityRepository, Repository} from "typeorm";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Function.PlatformTools.load (/opt/node/lib/node_modules/typeorm/platform/PlatformTools.js:124:28)
```

Notes: That's my first migration and my database was created but it's empty

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [ x ] `mysql`
    [ x ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by sinner** [comment]
I've solved this following these steps:

1.- Install ts-node and typescript globally:
```sh
$ npm install -g ts-node typescript
```

2.- Execute the typeorm command with ts-node:
```sh
$ ts-node ./node_modules/.bin/typeorm migrations:generate -n
```

I hope it could be useful :)

**Comment by nicogreenarry** [comment]
If you use Windows, @sinner's advice ([here](https://github.com/typeorm/typeorm/issues/1561#issuecomment-363562251)) probably won't work for you, per [this issue](https://github.com/typeorm/typeorm/issues/2316). Read that issue for the full explanation, but the short version is you'll probably want to run this command instead, after installing `ts-node`:

```
ts-node node_modules\typeorm\cli.js <command>
```

**Comment by onionhammer** [comment]
Yeah this still doesnt work on Windows (at the very least) so it should probably be re-opened

**Comment by HusDev** [comment]
Thanks, it works for me. 
`$ npm install -g ts-node typescript`
`ts-node node_modules\typeorm\cli.js migration:generate -n`

**Comment by ankur20us** [comment]
This worked for me:
$ npm install -g ts-node typescript
$ ts-node node_modules\typeorm\cli.js migration:generate -n

**Comment by loginov-rocks** [comment]
Getting the following:

```
mac:... danila$ ts-node ./node_modules/.bin/typeorm migration:generate -n
Error during migration generation:
TypeError: str.replace is not a function
    at Object.camelCase (/.../src/util/StringUtils.ts:7:16)
    at Function.MigrationGenerateCommand.getTemplate (/.../src/commands/MigrationGenerateCommand.ts:132:16)
    at Object.<anonymous> (/.../src/commands/MigrationGenerateCommand.ts:100:66)
    at step (/.../node_modules/tslib/tslib.js:136:27)
    at Object.next (/.../node_modules/tslib/tslib.js:117:57)
    at fulfilled (/.../node_modules/tslib/tslib.js:107:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by etrex** [comment]
> Getting the following:
> 
> ```
> mac:... danila$ ts-node ./node_modules/.bin/typeorm migration:generate -n
> Error during migration generation:
> TypeError: str.replace is not a function
>     at Object.camelCase (/.../src/util/StringUtils.ts:7:16)
>     at Function.MigrationGenerateCommand.getTemplate (/.../src/commands/MigrationGenerateCommand.ts:132:16)
>     at Object.<anonymous> (/.../src/commands/MigrationGenerateCommand.ts:100:66)
>     at step (/.../node_modules/tslib/tslib.js:136:27)
>     at Object.next (/.../node_modules/tslib/tslib.js:117:57)
>     at fulfilled (/.../node_modules/tslib/tslib.js:107:62)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> ```

you should type the migration file name after `-n` like this:

`ts-node ./node_modules/.bin/typeorm migration:generate -n kamigo`

**Comment by juniorpaiva95** [comment]
> I've solved this following these steps:
> 
> 1.- Install ts-node and typescript globally:
> 
> ```shell
> $ npm install -g ts-node typescript
> ```
> 
> 2.- Execute the typeorm command with ts-node:
> 
> ```shell
> $ ts-node ./node_modules/.bin/typeorm migrations:generate -n
> ```
> 
> I hope it could be useful :)


I have a problem when my entities extend from another. For example, a baseEntity:

```js
//base.entity.ts
import {PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn, DeleteDateColumn} from 'typeorm';

export class BaseEntity {
    @PrimaryGeneratedColumn ('uuid') id: string;
    @CreateDateColumn () createdAt: Date;
    @UpdateDateColumn () updatedAt: Date;
    @DeleteDateColumn () deletedAt: Date;
}

//natureza-juridica.entity.ts
import { Entity, Column, ManyToOne } from 'typeorm';
import { GrupoNaturezaJuridica } from './grupo-natureza-juridica.entity';
import { BaseEntity } from 'src/infrastructure/entity/base-entity';

@Entity()
export class NaturezaJuridica extends BaseEntity {
  
  @Column({ type: 'varchar', nullable: false, unique: true }) codigo?: string;
  
  @Column({ type: 'varchar', nullable: false }) name?: string;

  @Column({ type: 'varchar', length: '6', comment: "Determina a versão do registro de acordo com o IBGE. Ex: 2018.1" }) version: string;

  @ManyToOne(type => GrupoNaturezaJuridica) grupo?: GrupoNaturezaJuridica;

}
```


I have the following error when I run the command:
```shell
ts-node ./node_modules/.bin/typeorm migration: generate -n "InitialMigrate"
```
Error during migration generation:
{Error: Cannot find module 'src / infrastructure / entity / base-entity' ...
**Do you have any idea how I can get around it?**

**Comment by noureddineammar** [comment]
ts-node ./node_modules/typeorm/cli.js migration:generate -n migrationName

**Comment by Sara-skandari** [comment]
hhh
