### ISSUE TITLE
How to fetch few columns from a table

### ISSUE THREAD

**Issue by KrishnaAnanhti** [typeorm/typeorm#1565]
**Issue type:**  I have a table having 20 columns say. I want to fetch 5 columns of that table using typeorm. How can i achieve this functionality? how do i write a query for the same..

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**
 
[ x] `mssql` 

**TypeORM version:**
 
    "typeorm": "^0.1.2",
    "typescript": "2.4.0",

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by daniel-lang** [comment]
This
```ts
const entities = await repository.createQueryBuilder("entity")
   .select(["entity.column1", "entity.column2", "entity.column3",...])
   .getRawMany();
```

would be a way to only select specific columns. This will return an array of objects like this:
```ts
[
   {
      column1: 1,
      column2: 2,
      column3: 3
   },
   {
      column1: 2,
      column2: 3,
      column3: 4
   },
]
```
More information on query builders can be found here: [http://typeorm.io/#/select-query-builder](http://typeorm.io/#/select-query-builder).

If you want to hide it for every select statement on that entity you can specify `select: false` in the column options like this
```ts
@Column({
   select: false
})
column1: string;
```
More on columns options here: [http://typeorm.io/#/entities/column-options](http://typeorm.io/#/entities/column-options)

**Comment by pleerock** [comment]
No need to get raw data, he can select entities as well:

```ts
const entities = await repository.createQueryBuilder("entity")
   .select(["entity.column1", "entity.column2", "entity.column3",...])
   .getMany();
```

**Comment by pleerock** [comment]
I think this can be closed.

**Comment by copsbehindme** [comment]
i wonder how can we do this using the find-options. i tried doing this with find-options 
`repository.find({
           select : ["column1","column2"]} , 
           where: {column1:value1, column2: value2} 
      })`

and it still returns the array of objects with all columns and not just what is specified.

**Comment by atejadac** [comment]
Any progress on @copsbehindme 's question? I'd like to do this using MongoDB so using .find() is the only option.

**Comment by webmobiles** [comment]
can I select  with join, using * for one table, and specific fields for fields from join tables?

.select(["entity.*", "entity2.column2", "entity2.column3",...])

**Comment by pookdeveloper** [comment]
@webmobiles it dosent work

**Comment by pookdeveloper** [comment]
Yo can use that:

.select(["entity", "entity2.column2", "entity2.column3",...])

**Comment by sandeshgb** [comment]
it didn't allowed me!!

**Comment by mandros1** [comment]
Is there a way to introduce alias on the select, something like this:

.select(["entity.id as entityId"]) OR .select(["entity.id" as entityId])

**Comment by flexelektro** [comment]
> Is there a way to introduce alias on the select, something like this:
> 
> .select(["entity.id as entityId"]) OR .select(["entity.id" as entityId])

this should just work already :
.select(['swap.id as swapId', 'user.id as myuserid'])

**Comment by mossa-Sammer** [comment]
can we get it in find options?

**Comment by gitsome** [comment]
I setup some simple decorators and util methods I use on a project that work as filters that provide `views`.  Note, this approach isn't efficient as it pulls all the data for an entity and then filters it based on the required view. Possibly okay for some applications?

The User Entity with properties decorated with @ClassView
```typescript
@Entity("user")
export class User {

  @PrimaryGeneratedColumn({ type: "bigint" })
  @ClassView(['ui', 'session'])
  id: number;

  @Column({ length: 255, unique: true })
  @IsEmail()
  @Length(1, 255)
  @ClassView(['ui', 'session'])
  email_address: string;

  @Column({ length: 32 })
  @Length(1, 32)
  password_salt: string;

  @Column({ length: 128 })
  @Length(1, 128)
  password_hash: string;
}
```

The use of the utility methods as demonstrated in setting session and return values to the UI for the same User entity:

```tyepscript
router.post("/api/login", async (ctx) => {

  const { email_address, password } = ctx.request.body;
  const connection = await getConnection();

  try {
    // find user by email_address
    const userRepository = connection.getRepository(User);
    const existingUser = await userRepository.findOne({ email_address });

    if (!existingUser) {
      return ctx.badRequest(USERNAME_OR_PASSWORD_ERROR);
    }

    // validate the hash of the password with the salt matches
    const password_salt = existingUser.password_salt;
    const password_hash = crypto.pbkdf2Sync(password, password_salt, PASSWORD_HASH_ITERATIONS, PASSWORD_HASH_LENGTH, "sha512").toString("hex");

    if (password_hash !== existingUser.password_hash) {
      return ctx.badRequest(USERNAME_OR_PASSWORD_ERROR);
    } 

    // LOG THE USER IN BY SETTING THE USER ON THE SESSION AND RETURN THE USER OBJECT
    ctx.session.user = getClassView(existingUser, "session");

    // RETURN A SUBSET OF USER PROPERTIES FOR USE IN THE UI
    ctx.ok(getClassView(existingUser, "ui"));

  } finally {
    await connection.close();
  }
});
```

Notice the `getClassView` being used to filter the `existingUser` properties for setting user session data and the final login return value with User data relevant to the UI. 

Here is the gist:
https://gist.github.com/gitsome/c4eac89ae0002ca23697afdaedbde3a7

**Comment by muhammadsalmanafzal** [comment]
> i wonder how can we do this using the find-options. i tried doing this with find-options `repository.find({ select : ["column1","column2"]} , where: {column1:value1, column2: value2} })`
> 
> and it still returns the array of objects with all columns and not just what is specified.

@rohit-gh did you find any way to get only the required field because as of today in 2022, it still gives all the other columns as undefined.

**Comment by rohit-gh** [comment]
@muhammadsalmanafzal I've converted most of my code to query builder now. Using custom typescript Interfaces to refer return types.
