### ISSUE TITLE
No changes in database schema were found

### ISSUE THREAD

**Issue by ljjb** [typeorm/typeorm#1567]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.12`

**Steps to reproduce or a small repository showing the problem:**

I can't find information on how to initialize a database, generate migrations based on the models I've written and then run them. I have two models and the application works with `"synchronize": true`. However, I can't get migrations working based on what's in the [documentation](http://typeorm.io/#/migrations/generating-migrations).

If I delete my sqlite database, have no migrations, and then run
`ts-node ./node_modules/.bin/typeorm migrations:generate -n InitialMigration`
I get the following message:
`No changes in database schema were found - cannot generate a migration. To create a new empty migration use "typeorm migrations:create" command`

I have tried using the `schema:drop` and `schema:sync` commands in conjunction with `migrations:generate` in every possible combination, to no avail. What am I missing?

**Update**: I read in another issue that migration generation only works in MySQL. If this is the case, it should be stated in the docs. I can submit a PR if someone confirms this to be true.

**Update 2**: No problems now that I've migrated to PostgreSQL.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.
