### ISSUE TITLE
PrimaryGeneratedColumn with prefix

### ISSUE THREAD

**Issue by daggett206** [typeorm/typeorm#1571]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

The question is how to create PrimaryGeneratedColumn with a prefix, like PR000001?
Thanks in advance!

**Comment by daggett206** [comment]
if anybody curious about, I found a hacky-solution, so please correct me

@EventSubscriber()
export class MyEntitySubscriber implements EntitySubscriberInterface {
    public afterInsert(event: InsertEvent<any>) {
        const repo = event.manager.connection.getRepository(MyEntity);
        event.entity.reorderId = `PR${zerofill(6, event.entity.id)}`;
        repo.save(event.entity);
    }
}

**Comment by pleerock** [comment]
you cannot change it on the database level, databases does not support this functionality. You need to use a regular primary column and implement generation strategy manually. Or use different hacks like you did and hope that they won't bring you problems.

**Comment by devodii** [comment]
Any other decorator from typorm we can use?
I found @BeforeEntity(), this lets me declare it at the entity level. but I'm struggling to make it work :)
