### ISSUE TITLE
Support the associate/attach method

### ISSUE THREAD

**Issue by dogscar** [typeorm/typeorm#1572]
how to set the foreign key on the child model When updating a one-many or many-many relationship?
the laravel or the adonisjs use the associate/attach method. 
so does the typeorm has a convenient method to  resolve this problem?

**Comment by pleerock** [comment]
You just do for example `user.profile = profile` and its attached in the database. Please read docs about relations, try to implement and write me what exact issues you have.

**Comment by pleerock** [comment]
Closing as no answer from reporter. Looks like the issue was resolved.
