### ISSUE TITLE
Postgres, Eager and Maximum call stack size exceeded

### ISSUE THREAD

**Issue by alekseymakhankov** [typeorm/typeorm#1573]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello, how can I get data recursively. For example, I have tree-structure with children. I tried to use eager, but it says Maximum call stack size exceeded.

Node entity

```
@PrimaryGeneratedColumn()
_id: number;

@Column('varchar', { length: 255, default: '' })
name?: string;

@OneToMany(type => Node, node => layer.child, {
   eager: true,
})
@JoinColumn()
children?: Node[];

@ManyToOne(type => Node, node => node.children)
child?: Node;
```

**Comment by bartlomiej-korpus** [comment]
Take a look at closure table [http://typeorm.io/#/tree-entities](Tree Entities)

**Comment by alekseymakhankov** [comment]
@bartlomiej-korpus Thanks!

**Comment by alekseymakhankov** [comment]
@bartlomiej-korpus But how can I auto resolve children references? Because structure can be endless

**Comment by alekseymakhankov** [comment]
@pleerock Yes, I want to get all references by one call find(), I use eager: true, but it not works with self-references

**Comment by pleerock** [comment]
You can't use eager: true with tree entities. You need to use methods from tree repository. Its not that easy to work with tree data in rdbms

**Comment by alekseymakhankov** [comment]
@pleerock Now I just get all nodes and build tree myself, thanks

**Comment by pleerock** [comment]
There are methods in tree repository which build you a tree as well.

**Comment by pleerock** [comment]
Looks like the issue was resolved. Reopen if needed.
