### ISSUE TITLE
Resolution of ormconfig.js/ormconfig.json does not work in AWS Lambda/API Gateway

### ISSUE THREAD

**Issue by mellocello2003** [typeorm/typeorm#1575]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Simply call `createConnection` from within a Node.JS lambda function - it won't be able to find ormconfig.js.  I can fix this by explicitly specifying a root of the current working directory (`process.cwd()`) and loading the configuration from there.

Ideally, typeorm should be able to figure this out.  It's unclear why it's not - in AWS lambda, the current directory is `/var/task`, and all files from your package are loose in that directory (including `ormconfig.js`, etc...)

**Comment by pleerock** [comment]
Where do you face this issue? When you start your app, or when using cmd commands?

**Comment by mellocello2003** [comment]
Start up the app.

**Comment by pleerock** [comment]
its not a trivial task to find your application root, and looks like aws lambda has very specific way how they run node app, thats why you have such issues. Currently ORM uses "app-root-path" package to determine your app root path. I don't know the way how we should determine aws labmda specifics. Let me know if you know.

But there is a way how to handle it properly using a slightly different api:

```ts
async function createAwsConnection(): Promise<Connection> {
    const options = await ConnectionOptionsReader({ root: "/path/to/orm-config/directory" }).get("default");
    return getConnectionManager().create(options).connect();
}
```

**Comment by mellocello2003** [comment]
Yep that's what I've been doing as a fallback.  Perhaps this is just a documentation issue then.

Just to clarify because I haven't tried this... there's no way to just traverse the directory structure up until you hit your package.json?

**Comment by mellocello2003** [comment]
Honestly, @pleerock, this is a pretty minor issue.

**Comment by pleerock** [comment]
Okay, you know the solution.
