### ISSUE TITLE
Querybuilder: Partially selecting columns from related table

### ISSUE THREAD

**Issue by phusar** [typeorm/typeorm#1578]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.1.10 (or put your version here)

I'm trying to get a couple of columns from **table1** and a column position from **related_table**. Here is some example code:
 ```ts 
let result = await db.getRepository(Table1Entity)
      .createQueryBuilder('table1')
      .select(['table1.id', 'table2.position'])
      .leftJoin('related_table', 'table2', 'table2.relatedId=table1.id')
      .where('table1.id in (:ids)', {ids})
      .getMany();
```
Problem is when I do this, I only get id in the mapped entity, position is filtered out. Is there any way around it?

**Comment by pleerock** [comment]
you should use real relations, e.g.:

```ts
.leftJoin('table1.relation'
```

**Comment by pleerock** [comment]
Closing as no answer from reporter. Let me know if you have something to add.

**Comment by pookdeveloper** [comment]
> you should use real relations, e.g.:
> 
> ```ts
> .leftJoin('table1.relation'
> ```

@pleerock this dosen't work
