### ISSUE TITLE
Update SET with column reference

### ISSUE THREAD

**Issue by CocaColaBear** [typeorm/typeorm#1580]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello everybody. How I can make query like this:
```sql
UPDATE table SET value = value + 2 WHERE id = 123 RETURINING value;
```
This is my current version, but without "value + :value"
```ts
this.createQueryBuilder()
	.update(TestTable)
	.set({ value: ":value" })
	.setParameter("value", 2)
	.where("id = :id", { id: 123 })
	.returning("value")
	
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
when you are using se this way you don't need to use parameters, they are created automatically, e.g. replace to:

```ts
this.createQueryBuilder()
	.update(TestTable)
	.set({ value: 2 })
	.where("id = :id", { id: 123 })
	.returning("value")
```

**Comment by CocaColaBear** [comment]
@plerock. Thanks. But i need:
```sql
SET value = value + 2
```
Instead of:
```sql
SET value = 2
```

**Comment by pleerock** [comment]
```ts
this.createQueryBuilder()
	.update(TestTable)
	.set({ value: () => "value + 2" })
	.where("id = :id", { id: 123 })
	.returning("value")
```

**Comment by CocaColaBear** [comment]
Oh) thank you)

**Comment by tenuki** [comment]
I'm running into the same problem and:

 1.  using: 
    tx_mgr.createQueryBuilder()
	    .update(entityClass)	    
	    .set({ column: () => 'entitytable."column" + 2' })
	    .where("id = :id", { id: 123 })
	    .returning('entitytable."column"').execute()

fails with:
(node:9375) UnhandledPromiseRejectionWarning: QueryFailedError: invalid input syntax for type numeric: "() => 'entitytable.column"'"
 
2.  adding execute() was required.

**Comment by fabian-perez** [comment]
```this.createQueryBuilder()
	.update(Entity)
	.set({ column: () => `column + ${param}` })
	.where("id = :id", { id: 1 })
	.execute()```

**Comment by J-Ibarra** [comment]
`"typeorm": "^0.2.24",`

How i can use the update query to raw i have this

![image](https://user-images.githubusercontent.com/4218738/82390096-c5ad2d00-9a0b-11ea-8221-90ff23836316.png)

in database create fine
![image](https://user-images.githubusercontent.com/4218738/82390164-f725f880-9a0b-11ea-8a6a-9ebb5c7debf1.png)

if I run this command 

```sql
update app_info set faq = array['{"name":"peter"}','{"name":"alex"}']::json[];
```

this update fine in the column
![image](https://user-images.githubusercontent.com/4218738/82390261-3fddb180-9a0c-11ea-98f2-6a60c69f69ba.png)

but in nodejs
![image](https://user-images.githubusercontent.com/4218738/82390745-88499f00-9a0d-11ea-8d62-0cee5c6d7995.png)

or 

![image](https://user-images.githubusercontent.com/4218738/82390764-95668e00-9a0d-11ea-947f-023cbeb97593.png)

**Comment by LKTPD** [comment]
> ```ts
> this.createQueryBuilder()
> 	.update(TestTable)
> 	.set({ value: () => "value + 2" })
> 	.where("id = :id", { id: 123 })
> 	.returning("value")
> ```

if plus with string, it should be like this.
value:abc + xyz ---> abcxyz

this.createQueryBuilder()
	.update(TestTable)
	.set({ value: () =>CONCAT(value,'xyz')})
	.where("id = :id", { id: 123 })
	.returning("value")

**Comment by talski** [comment]
you can also use typeorm params, it looks better and is useful for arrays

```JS
const attachmentsToDelete = [
  'f407ffb5-7dcb-4ada-940e-bffa3e153a3f',
  '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed'
];

this.createQueryBuilder()
      .update(Post)
      .set({
        attachments: () => `
        (
          select jsonb_agg(e)
          from jsonb_array_elements(attachments) as t(e)
          where t.e->>'id' NOT IN (:...attachmentsToDelete)
        )
      `
      })
      .setParameter('attachmentsToDelete', attachmentsToDelete)
      .where({ id })
      .execute();
```

**Comment by kuangshp** [comment]
What if I want to use this feature in a transaction
eg.
```typescript
await entityManager.query(`update ticket SET number=number - 1, pay_number=pay_number - 1  where id = ${orderListInfo.ticketId};`);
```
