### ISSUE TITLE
`updateById` does not return an object of the new model

### ISSUE THREAD

**Issue by crutchcorn** [typeorm/typeorm#1582]
**Issue type:**

[ ] question
[x] bug report?
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
If you use a repository to do `updateById(object.id, newObj)`, I would usually expect the function to return a promise of the newObj that's stored in the database, but instead have gotten `void`. It would be very nice to have it return a copy of the new object

**Comment by pleerock** [comment]
`updateById` performs raw sql UPDATE query and does not select anything. It omits 90% of the `save` method functionality. Use `save` method instead.

**Comment by sslgeorge** [comment]
@pleerock Has updateById been removed from typeorm?

I get the error **Property 'updateById' does not exist on type**

**Comment by sslgeorge** [comment]
![screen shot 2018-04-25 at 2 33 35 pm 2](https://user-images.githubusercontent.com/16083791/39240696-a70cd23e-4895-11e8-826c-2cccc78f587e.png)
