### ISSUE TITLE
Cannot read property 'createValueMap' of undefined

### ISSUE THREAD

**Issue by Duskfall** [typeorm/typeorm#1584]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

````
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: ObjectID;

    @Column()
    name: string;
}

````

If using PrimaryGeneratedColumn instead of ObjectIdColumn, I get an error :
````
Error:  TypeError: Cannot read property 'createValueMap' of undefined
    at MongoQueryRunner.<anonymous> (C:\Users\atro\Work\typeorm-typescript-mongo-example\node_modules\typeorm\driver\mongodb\MongoQueryRunner.js:573:98)
    at step (C:\Users\atro\Work\typeorm-typescript-mongo-example\node_modules\typeorm\driver\mongodb\MongoQueryRunner.js:32:23)
    at Object.next (C:\Users\atro\Work\typeorm-typescript-mongo-example\node_modules\typeorm\driver\mongodb\MongoQueryRunner.js:13:53)
    at fulfilled (C:\Users\atro\Work\typeorm-typescript-mongo-example\node_modules\typeorm\driver\mongodb\MongoQueryRunner.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
````

The data is stored normally in the database. I just use the generated example:

````
// insert new users for test
    await connection.manager.save(connection.manager.create(User, {
        name: "Timber",
        email: "Saw",
        password: "test"
    }));

**Comment by pleerock** [comment]
I added test which confirms that functionality you are talking about is working. Please take a look on my commit, fork and apply your changes that breaks this test.

I also tried project generated by typeorm init and it works fine:

```bash
$ typeorm init -n mongotest --db mongodb
Project created inside /Users/pleerock/www/clonned/mongotest directory.
$ cd mongotest/
$ ls
README.md       ormconfig.json  package.json    src             tsconfig.json
$ npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN mongotest@0.0.1 No repository field.
npm WARN mongotest@0.0.1 No license field.
added 156 packages in 22.011s
$ ls
README.md               node_modules            ormconfig.json          package-lock.json       package.json            src                     tsconfig.json

$ npm start

> mongotest@0.0.1 start /Users/pleerock/www/clonned/mongotest
> ts-node src/index.ts

Inserting a new user into the database...
Saved a new user with id: 5a82cdc15c22664c0ac0ca34
Loading users from the database...
Loaded users:  [ User { id: 5a82ccaab814e74ba73982c1 },
  User {
    id: 5a82cdc15c22664c0ac0ca34,
    firstName: 'Timber',
    lastName: 'Saw',
    age: 25 } ]
Here you can setup and run express/koa/any other framework.
```

**Comment by Duskfall** [comment]
Thanks for taking the time to look into this! You missed the point where I changed the id to match the RDBMS database type ( or this is my thought at least ).
If you change it the User id to use PrimaryGeneratedColumn decorator instead, we get this problem
![image](https://user-images.githubusercontent.com/2528125/36176328-e6c2d7e6-111a-11e8-8a3d-656b139251d7.png)

**Comment by Duskfall** [comment]
As the documentation suggests, we can't be completely generic when declaring ids so with mongo we must specifically declare objectId

**Comment by wilfredlopez** [comment]
using @ObjectIdColumn instead of PrimaryGeneratedColumn works for me.

`ts
import { Entity, PrimaryGeneratedColumn, Column, ObjectID, ObjectIdColumn } from "typeorm"

@Entity()
export class User {

    @ObjectIdColumn()
    id: ObjectID

    @Column()
    firstName: string

    @Column()
    lastName: string

    @Column()
    age: number

}`

**Comment by xenoterracide** [comment]
mongo can use Id's other than object id though, why can't `@PrimaryGeneratedColumn('uuid')` work? mongo supports uuid based ids

**Comment by AbdelrahmanAbounida** [comment]
This worked fine for me 


```
import { Exclude } from 'class-transformer';
import {
  AfterInsert,
  AfterLoad,
  AfterRemove,
  AfterUpdate,
  Entity,
  ObjectIdColumn,
  PrimaryColumn,
} from 'typeorm';

@Entity()
export class AbstractEnttiy<T> {
  @ObjectIdColumn({ name: '_id' })
  @Exclude()
  _id: string;

  @PrimaryColumn()
  @ObjectIdColumn()
  id: string;

  constructor(entity: Partial<T>) {
    Object.assign(this, entity);
  }

  @AfterLoad()
  @AfterInsert()
  @AfterUpdate()
  @AfterRemove()
  assingIdFromObjectId() {
    this.id = this._id.toString();
  }
}
```
