### ISSUE TITLE
Resolve endless references

### ISSUE THREAD

**Issue by alekseymakhankov** [typeorm/typeorm#1585]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello, how can I auto resolve all references in endless structure, for example, tree structure?

**Comment by pleerock** [comment]
Tree structures is functionality which is under development, but some features are already available in `next` (npm i typeorm@next). See docs [here](https://github.com/typeorm/typeorm/blob/next/docs/tree-entities.md).

**Comment by pleerock** [comment]
Looks like the issue was resolved. Reopen if needed.
