### ISSUE TITLE
nullable column/relation option set to false only works on undefined

### ISSUE THREAD

**Issue by anigenero** [typeorm/typeorm#1586]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have two fields within my entity that have _nullable_ set to _false_, which will set the field null during an update (both in the relation and column).

```ts
@Entity('Account')
export class AccountEntity {

    @ManyToOne(type => RecordTypeEntity, {
        nullable: false
    })
    @JoinColumn({ name: 'RecordTypeId' })
    recordType: RecordTypeEntity;

    @Column({
        name: 'Phone',
        type: 'varchar',
        nullable: false
    })
    phone: string;
}
```

However, when running (I'm showing the Jest test I have it in), setting the fields to null will set them null in the database during the update, and the test will fail. **This does happen in the running server, I'm just showing the test because it's more concise.**

```ts
return AccountEntity.save(account).then(() => {
    return AccountEntity.findOneById(account.sfid, {
        join: {
            alias: 'account',
            innerJoinAndSelect: {
                'recordType': 'account.recordType'
            }
        }
    }).then(result => {

        result.phone = null;
        result.recordType = null;

        return AccountEntity.save(result).then(() => {
            return AccountEntity.findOneById(account.sfid, {
                join: {
                    alias: 'account',
                    innerJoinAndSelect: {
                        'recordType': 'account.recordType'
                    }
                }
            }).then(result => {

                expect(result).toBeDefined();

                expect(result.recordType).toEqual(account.recordType);
                expect(result.phone).toEqual(account.phone);

            });
        });

    });

});
```

This is spit out in the logs during the test - so you can see that it's updating the field.

```console
console.log node_modules/typeorm/platform/PlatformTools.js:207
executing query:  START TRANSACTION

console.log node_modules/typeorm/platform/PlatformTools.js:207
executing query:  UPDATE `Account` SET `Phone`=?, `RecordTypeId`=?  WHERE `Id`=? -- PARAMETERS: [null,null,"1e6ecbc2-6890-44bd"]

console.log node_modules/typeorm/platform/PlatformTools.js:207
executing query:  COMMIT
```

The only way I can get it to work is to set the fields to undefined instead of null

```ts
result.phone = undefined;
result.recordType = undefined;
```

**Comment by pleerock** [comment]
`nullable: false` means it will set your column `NOT NULL` constraint in the database, it does not mean it will skip your columns from the updation. So, behaviour you are getting is expected.

**Comment by anigenero** [comment]
Ok. Was expecting that the behavior on that would be similar to how JPA deals with non-nullable columns, and the way the documentation is worded, it seemed that it would. Is this something you would consider putting in as a feature for instances like this? Or is that not within the scope of the project?

**Comment by pleerock** [comment]
We could add a check and throw an exception if some of the values are null. The only difference will be that instead of database throwing error orm will be doing that. Im not sure if its a good design because it is only one database constraint we'll check. But there are other constraints that database has besides NOT NULL checks and its not possible for orm to check them all (even half of them). So, Im not really sure about "validate some constraints, left others for database to check" design.

**Comment by anigenero** [comment]
Ok. Not optimal, but I understand your overall reasoning why not to include it. So, in my case I just need to do the check for the null values I'm validating. Thanks for your help.
