### ISSUE TITLE
TypeORM attempts to create tables that already exist when its user is not the owner of that table, regardless of privilege settings

### ISSUE THREAD

**Issue by CaptJakk** [typeorm/typeorm#1588]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. create postgres table as `user1`
2. grant all privileges on table to `user2`
3. configure typeorm to log into this db and table under login `user2`
4. use typeorm to query table
Expected behavior: query should execute as expected without new table creation
Actual behavior: query attempts to create the table as if it didn't exist but fails because postgres returns an error stating the table already exists
5. alter the table's owner to be `user2`
6. use typeorm to query table
Actual behavior: query does not attempt to create table, as it recognizes it already exists.

Speculation: I suspect that this is due to TypeORM only detects tables of which its configured user is the owner.

**Comment by pleerock** [comment]
No, typeorm does not use username elsewhere rather then during connection. The issue you are reporting is very strange.

**Comment by pleerock** [comment]
Im not sure if this issue related to typeorm. Please provide more info trying latest `@next`.

**Comment by eparizzi** [comment]
I'm experiencing the same issue.  Any ideas?

**Comment by kausar2697** [comment]
you should use only the lower case name

**Comment by JulianH99** [comment]
Using only lowercase naming is not always an option. In my case all the tables have to camelCase naming. I already configured the `lower_case_tables_name` in `my.cnf` but that does not seem to work at all, typescritps still throws an error saying `table systemversion already exists` (with systemversion being one of my tables)
