### ISSUE TITLE
Issues in Migration while using schema in Postgres

### ISSUE THREAD

**Issue by Seshagiri25** [typeorm/typeorm#1589]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X ] `0.1.12` -- I have installed couple of days back with npm. Although the latest version I see in Changelog is 0.1.13, I get 0.1.12 when I run command "typeorm --version" in cmd.

**Steps to reproduce or a small repository showing the problem:**
I have multiple issues when I use non-default Schema in Postgres. Listed in order below

**Current Configuration:** I have added three files. 
1. ormjson.config: For Connection. Notice, the schema is not "public". I have created another schema with name "private". 
2. User Entity and Roles Entity: These are simple classes with appropriate properties. These two entities are mapped with Many-To-Many Relationship.
 
```ormConfig.Json
{
    "type": "postgres",
    "name": "master",
    "host": "localhost",
    "port": 5432,
    "username": "test",
    "password": "test",
    "database": "master",
    "synchronize": false,
    "logging": false,
    "schema": "private",
    "entities": [
       "./dist/admin/entity/**/*.js"
    ],
    "migrations": [
       "./dist/admin/migration/**/*.js"
    ],
    "subscribers": [
       "./dist/admin/subscriber/**/*.js"
    ],
    "cli": {
        "migrationsDir": "./src/admin/migration"
    }
 }
```

Entities
User Entity:
```@Entity()
export class Users extends BaseEntity {
    @Column("text",{
        name:"first_name"
    })
    public firstName: string;

    @Column("text",{
        name:"last_name"
    })
    public lastName: string;
    
    @Column("text",{
        name:"email"
    })
    public email: string;
    
    @Column("text",{
        name:"password"
    })
    public password: string;
}
```

Roles Entity:

```@Entity()
export class AdminRoles extends AdminBaseEntity {
    @Column("text",{
        name:"role_name"
    })
    public roleName:string;
    
    @ManyToMany(type=>AdminUsers, users => users.roles )
    public users: AdminUsers[]
}
```

With this background I am facing following issues with migrations.
**I) Query runner down method does not use schema name with Drop table name.**

Steps to reproduce: When I type command
```
typeorm migrations:generate -n initial -c master
```
It generates a file with following up and down methods. If you look at down method, schema name is not used with Drop table.
_Up method_
```
    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "private"."admin_roles" ("id" SERIAL NOT NULL, "create_by" text NOT NULL, "last_updated_by" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "last_updated_at" TIMESTAMP NOT NULL DEFAULT now(), "version" integer NOT NULL, "client_ip" text, "user_agent" text, "role_name" text NOT NULL, PRIMARY KEY("id"))`);
        await queryRunner.query(`CREATE TABLE "private"."admin_users" ("id" SERIAL NOT NULL, "create_by" text NOT NULL, "last_updated_by" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "last_updated_at" TIMESTAMP NOT NULL DEFAULT now(), "version" integer NOT NULL, "client_ip" text, "user_agent" text, "first_name" text NOT NULL, "last_name" text NOT NULL, "email" text NOT NULL, "password" text NOT NULL, PRIMARY KEY("id"))`);
        await queryRunner.query(`CREATE TABLE "private"."admin_user_roles" ("adminUsersId" integer NOT NULL, "adminRolesId" integer NOT NULL, PRIMARY KEY("adminUsersId", "adminRolesId"))`);
        await queryRunner.query(`ALTER TABLE "private"."admin_user_roles" ADD CONSTRAINT "fk_d72efa726bc71ec729833edc441" FOREIGN KEY ("adminUsersId") REFERENCES "private"."admin_users"("id")`);
        await queryRunner.query(`ALTER TABLE "private"."admin_user_roles" ADD CONSTRAINT "fk_58658eda68c0c78c178e33599ca" FOREIGN KEY ("adminRolesId") REFERENCES "private"."admin_roles"("id")`);
    }
```
_Down Method_
```
    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "private"."admin_user_roles" DROP CONSTRAINT "fk_58658eda68c0c78c178e33599ca"`);
        await queryRunner.query(`ALTER TABLE "private"."admin_user_roles" DROP CONSTRAINT "fk_d72efa726bc71ec729833edc441"`);
        await queryRunner.query(`DROP TABLE "admin_user_roles"`);**
        await queryRunner.query(`DROP TABLE "admin_users"`);
        await queryRunner.query(`DROP TABLE "admin_roles"`);
    }
```
**II) Migrations table is required in public schema although it is not used.**

`typeorm migrations:generate` command generates `migration` table in `private` schema. But When I use `typeorm migrations:run`, I am getting error `'relation "migrations" does not exist'`. 

When I create `migrations` table manually in public schema, it works well and the tables are created in `private` schema as expected.

_a)Steps to reproduce error:_
1. run `typeorm migrations:run -c master` in cmd.

_b)Steps to bypass error:_
1. create `migrations` table in public schema manually.
2. run `typeorm migrations:run -c master` in cmd.

**III) Revert is not working, since Migration data is not inserted in public.migrations***

When the point II) is run successfully, the migrations data is inserted in `private.migrations` table. 
In this situation, If I try to run `typeorm migrations:revert -c master`, I am getting below message
**No migrations was found in the database. Nothing to revert!**
I think, `revert` command is searching migration data in `public` schema. 
_c) Steps to reproduce error:_

Run below command in continuation to point b) above.
`typeorm migrations:revert -c master`

**Comment by AlexMesser** [comment]
would be great if you can test it on `@next` (npm i typeorm@next). It should be fixed

**Comment by pleerock** [comment]
I'll close it since there is still no answer from reporter. Please let us know if it does not work in latest next.
