### ISSUE TITLE
TypeError: Issues in constructor

### ISSUE THREAD

**Issue by cedrickmandocdoc** [typeorm/typeorm#1590]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Clone this repo https://github.com/cedrickmandocdoc/typeorm-bug
2. Create PG Database with name test, edit what roles you will used
3. Install packages
4. Compile run tsc
5. Run index.js
Result:
1. You will notice that there is a TypeError.

I guess this is because of the constructor. I believe there is workaround here, but I want to preserve also the types and have strictnullchecks set to true. Though if I edit the constructor parameters and isolate it one by one. It will works. I just want to know why this sample repo didn't work. I guess this is a bug.

**Comment by pleerock** [comment]
You have two issues. `create` does not save entity in the database and it does not return you a promise, and it does not accepts constructor arguments, you are using it completely wrong (I guess you are confusing methods of sequelize library, create in typeorm serves different purpose). Your correct code for saving entity is:

```ts
  await userRepository.save(new User({
    firstName: 'test',
    lastName: 'test',
    age: 1
  }));
```

Second, your entity constructor arguments **must be optional**, its a requirement, since when loading entities from the database ORM creates instances of the classes, and it does not aware of your constructor arguments and what it shall provide there. How it should be in your code:

```ts

  public constructor(data?: User) {
    if (data) {
      this.firstName = data.firstName;
      this.lastName = data.lastName;
      this.age = data.age;
    }
  }
```

**Comment by cedrickmandocdoc** [comment]
Thanks @pleerock on your response.
> your entity constructor arguments must be optional
That is why it cannot read the property. Just one last thing, is the constructor parameter optional thing is on documentation? I think it is good if this is also on documentation. Anyway, thanks again we can close this now.

**Comment by pleerock** [comment]
>  I think it is good if this is also on documentation.

You are right, feel free to create a PR in documentation in the place where you think its a good fit to mention this behaviour.

> because it breaks the strictNullChecks of the tsconfig.

its a tricky question. Having to enforce all your properties to be always defined can limit you in some use cases (partial updation, partial selection), but from the other side having to define all properties as optional can bring you lot of boilerplate code in the places where you gonna use it.
Possible solution for you might be:

```ts
public constructor(data?: User) {
    if (!data) data = { firstName: "", lastName: "lastName", age: 0 };
      this.firstName = data.firstName;
      this.lastName = data.lastName;
      this.age = data.age;
  }
```

But for me it does not look like a good solution :)

**Comment by cedrickmandocdoc** [comment]
I see. I think all questions here have been answered. Thanks @pleerock. We can close this issue.

**Comment by nitzantomer** [comment]
I'd do things a bit differently.
You can use optional members, and then use the non-null assertion operator when using the members.
This solution doesn't add much code (a single `!` character).
Also, I'd use `Object.assign` to fill in the values in this.

So, basically:
```
class User {
    id?: number;
    firstName?: string;
    lastName?: string;
    age?: number;

    constructor(obj?: User) {
        if (obj) {
            Object.assign(this, obj);
        }
    }

    public getFirstName(): string {
        return this.firstName!;
    }
}
```

**Comment by pleerock** [comment]
Features (like typescript's strict properties) are created to improve your code and experience. Make sure to use them wisely, and if you feel are doing some hacks or monkey patches then it can be a good sign that you don't really need this feature.

**Comment by nitzantomer** [comment]
That's exactly what this feature is created for, so I think it's using it wisely.
There are no "hacks" here, in fact, your solution is the hack as it actually translates into the javascript output.
My solution keeps the js code clean and simple.

**Comment by pleerock** [comment]
`!` simply disables what you enabled and can be treated as a hack in many cases, just like when you are casing things using `as` or `<T>` operators. And having `getFirstName` method that does what you did is quite ugly. But anyway, its your opinion and your willing on how you do things.

**Comment by CanKattwinkel** [comment]
I partially agree with @nitzantomer. TypeScript has the `!` operator so that we can tell the compiler where to trust us. But also typings shouldn't be too verbose and shouldn't create a security that does not exist.

It is just pseudo code, but this might do the trick without any constructor requried - take a look at the `!` after the attribute. The developer now has to pay a lot of attention that no nullable values are prefixed with `!`.

**I am not sure if I'd use this.** But if you want to use it with strict null checks, this is probably the version with the **least boilerplate**. 

```
@Entity()
export class Example {

    @PrimaryGeneratedColumn()
    id!: number;

    @Column({length: 500})
    name!: string;
}

```

**Comment by bennycode** [comment]
The fact that TypeORM doesn't run the constructor hit me hard. The sentence: "[When using an entity constructor its arguments must be optional](https://typeorm.io/#/entities)" should be more prominent on the TypeORM website.

My workaround is to use an `init` function in the constructor which is decorated with [@AfterLoad()](https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md#afterload):

```ts
@Entity()
export class Example {

  @PrimaryGeneratedColumn()
  id!: number;

  @Column({length: 500})
  name!: string;

  isInitialized!: boolean;

  constructor() {
    init();
  }

  @AfterLoad()
  init() {
    this.isInitialized = true;
  }

}
```
