### ISSUE TITLE
Define order of relation data when querying on the main entity

### ISSUE THREAD

**Issue by EikeLueders** [typeorm/typeorm#1591]
**Issue type:**

[X ] feature request

**Database system/driver:**

[X ] `mssql`
[X ] `postgres`

**TypeORM version:**

[X ] `latest`

Is it possible to define the order of relation data when querying with QueryBuilder?

I have two entities, lets call them User and Photos as in the examples. A user can have multiple photos. Each photo has an upload date and each user has a last login date (just examples).

I'd like to query all users and theirs photos in the following order: Users by last login date ASC and photos by upload date DESC

**Steps to reproduce or a small repository showing the problem:**
My query looks like this on the UserEntitiy with ActiveRecord-style
```
public getUserByLastLogin(take: number, skip: number) {
    return this.createQueryBuilder("user")
            .leftJoinAndSelect("user.photos", "photos")
            .orderBy("user.last_login_date", "ASC")
            .addOrderBy("photos.upload_date", "DESC")
            .take(take)
            .skip(skip)
            .getMany()
}
```

TypeORM creates two queries for me as I can see in the logs. One distinct query on the user data and another to get the relation data (photos). Both orderBy clauses are attached to both queries. Because the upload_date column of the photos is also attached to the select criteria from the first query SQL gives me the following (lets say take = 8, skip = 0):

user_id | last_login_date | upload_date
------------ | ------------- | -------------
1 | 2018-02-13T08:00:00 | 2018-02-12T09:12:00
1 | 2018-02-13T08:00:00 | 2018-02-12T09:10:00
1 | 2018-02-13T08:00:00 | 2018-02-12T09:00:00
2 | 2018-02-14T08:30:00 | 2018-02-11T12:00:00
2 | 2018-02-14T08:30:00 | 2018-02-11T11:00:00
3 | 2018-02-14T08:30:00 | 2018-02-11T11:50:00
3 | 2018-02-14T09:00:00 | 2018-02-11T11:40:00
3 | 2018-02-14T09:00:00 | 2018-02-11T11:30:00

So I just get 3 different users in total, but I expect to have 8.

What I want is:

user_id | last_login_date
------------ | -------------
1 | 2018-02-13T08:00:00
2 | 2018-02-13T09:00:00
3 | 2018-02-13T10:00:00
4 | 2018-02-14T08:30:00
5 | 2018-02-14T08:50:00
6 | 2018-02-14T08:55:00
7 | 2018-02-14T09:00:00
8 | 2018-02-14T10:00:00

On the second query however, that is now performed with the Ids of the first query result in a WHERE IN () clause the upload_date of the photos should be considered and used for ordering.

When I remove the order ```.addOrderBy("photos.upload_date", "DESC")``` from the query builder the query works fine, but my relation data (photos) are not ordered correctly. 

Is there a way to separate these two cases using the query builder (or any other method in typeorm)?
Currently I have to use it without ```.addOrderBy("photos.upload_date", "DESC")``` and order the photos manually using a customer getter for them, but I like to have this done by the database.

**Comment by pleerock** [comment]
Let's take a look closer on a problem.

First, why two requests are executed? Because standard SQL LIMIT only limits **number of rows returned by your database**, but this number grows when you have data joined, and it *breaks* on the concept of what you usually want to do - select only limited number of top-level data.

What is the solution to this problem? Make two queries - first we take only ids of the data we want to get and apply desired limit (without selecting joined data, so we don't have multiplicated rows), then we create a second query to get the data we wanted with ids equal to loaded ids.

Problem with orderby-s of joined data that it multiplies number of rows in a first query because of data from the joins and applies limit. I don't think this issue is resolvable, please provide some ideas if you have.

```sql
SELECT DISTINCT `distinctAlias`.`user_id` as "ids_user_id", `distinctAlias`.`user_name`, `distinctAlias`.`photo_date` FROM (SELECT `user`.`id` AS `user_id`, `user`.`name` AS `user_name`, `photo`.`id` AS `photo_id`, `photo`.`name` AS `photo_name`, `photo`.`date` AS `photo_date` FROM `user` `user` LEFT JOIN `user_photos_photo` `user_photo` ON `user_photo`.`userId`=`user`.`id` LEFT JOIN `photo` `photo` ON `photo`.`id`=`user_photo`.`photoId`) `distinctAlias` ORDER BY `distinctAlias`.`user_name` ASC, `distinctAlias`.`photo_date` ASC, `user_id` ASC LIMIT 5
```

Unfortunately we cannot remove selection of ordered data because everything we order by needs to be selected, its SQL database requirement.

**Comment by EikeLueders** [comment]
Thanks for you thoughts. Two queries are perfectly fine and I know there is no way around this because of the concept of SQL in a RDB. 

What would solve the problem? If it's possible to attach an orderBy clause to the second executed query only. As far as I understand I have no option to control the query behavior of typeorm, because its build in. And this is what I want, of course - not to have to deal with the SQL directly. 

A solution for my issue would be as well, if I execute the two queries manually. Remove the join and do another select with the result ids from the first query. However, I don't know how to attach the results of the second query to the returned Entities of the first one without having to loop over them. In my opinion this would ruin  the advantages typeorm gives me. Is there any way to do this automatically with typeorm?

**Comment by pleerock** [comment]
> What would solve the problem? If it's possible to attach an orderBy clause to the second executed query only. 

It won't work. It will give you wrong results. It will limit your results unordered. Solution could be to add order in subquery itself but unfortunatelly `The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions`.

So your real solution is to query data manually. In fact in most cases separate queries are better then joined selections in terms of performance. The only downside is that you need to loop over data and bind them to each other. I don't see good way to provide this functionality by ORM. Let me know if you have ideas.

**Comment by EikeLueders** [comment]
OK, thanks for your assistance. I'll handle it as you suggested with two manual queries. 

It should be possible to integrate this functionality into typeorm by having a function I can hand over the queries and a callback (or some kind of definition) that is executed then and defines how to connect the data from the two (or n) queries to return valid entities. But I believe this would be too specific case to integrate it into a general ORM layer.
