### ISSUE TITLE
How to store timestamp without @Create/UpdateDateColumn?

### ISSUE THREAD

**Issue by darkbasic** [typeorm/typeorm#1593]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
@Entity()
export class Recipient {
  @ManyToOne(type => User, user => user.recipients, { primary: true })
  user: User;

  @ManyToOne(type => Message, message => message.recipients, { primary: true })
  message: Message;

  @Column({nullable: true})
  receivedAt;

  @Column({nullable: true})
  readAt;
}
```

I want to store a server-generated timestamp into the db. When the recipient gets inserted into the db `receivedAt` and `readAt` must be initiallty `null`, but once I'll later update them I want them to be the actual date. How do I achieve it?

**Comment by DirkDeVisser** [comment]
In one of my projects I have used the following method:

BaseEntity.ts
```ts
export abstract class BaseEntity {
  ...

  @Column({name: "updated_at", nullable: true })
  public updatedAt: number;
  
  ...

  @BeforeUpdate()
  public setUpdatedAt() {
    this.updatedAt = Math.floor(Date.now() / 1000);
  }
}
```

OtherEntity.ts
```ts
@Entity()
export class OtherEntity extends BaseEntity {

}
```

When the save method on an EntityManager / Repository is called, it will look for the methods with the `BeforeUpdate` decorator and others, see [listeners](https://github.com/typeorm/typeorm/blob/next/docs/listeners-and-subscribers.md)

**Comment by darkbasic** [comment]
I would like the date to be set by the db itself using something like `now()`.

```
@Column({ type: "time without time zone", nullable: true})
  receivedAt: string;
```

But I would like something a little bit more db-agnostic.

Something like `@DateColumn()`.

**Comment by pleerock** [comment]
Its solvable using DEFAULT constraint on a column:

```ts
@Column({ default: () => `now()` })
  receivedAt
```

**Comment by darkbasic** [comment]
Is there any way to specify the `time without time zone` type in a db agnostic way? I would like to specify a generic date type which would work with any backend, not only postgresql.
That's why I was thinking about a generic `@DateColumn()` decorator which basically does `@Column({ type: "time without time zone"})`

**Comment by pleerock** [comment]
> specify a generic date type which would work with any backend, not only postgresq

typeorm follows YAGNI principle in such questions. But you can create your own decorator easily if you really need it.

**Comment by darkbasic** [comment]
Why do you think that I'm not gonna need it? Do you think that using the same entity as is onto another SQL database would not be possible anyway?

**Comment by pleerock** [comment]
I dont think you aren't gonna need it, but most people think they'll need when reality that they does not. Again, this functionality does not fit orm design and if you need it simply create your own decorator. I think this issue can be closed.

**Comment by darkbasic** [comment]
> most people think they'll need when reality that they do not

I'm open to alternatives. For each message I need a list of users who received the message, and for each of those users I need the receiving date (a timestamp of when they received the message) and the reading date (a timestamp of when they first read the message). I thought about a `Recipient` entity where I store the user id and the message id, as well as the receiving date and the reading date. The first time that I insert the recipient both the receiving and reading dates must be null, then once the server will send the message to the client it must set the receiving date to `now()`, later when the client will open that message it must ask the server to set the reading date to `now()`. Do you suggest me to make 3 different tables and just use `CreateDateColumn` instead?

Really, I'm truly open to alternatives. I'm working on a GraphQL tutorial and I want to showcase realtime capabilities. The whole tutorial has been designed around Mongodb and I'm trying to make a SQL version.

**Comment by pleerock** [comment]
> Really, I'm truly open to alternatives. I'm working on a GraphQL tutorial and I want to showcase realtime capabilities. The whole tutorial has been designed around Mongodb and I'm trying to make a SQL version.

For simple tutorial you can do it, but in real apps you can't ever simply change mongodb to sql without rewriting half of code.

**Comment by darkbasic** [comment]
> For simple tutorial you can do it, but in real apps you can't ever simply change mongodb to sql without rewriting half of code.

If necessary I am willing to rewrite half the code because the tutorial will have a big audience and I don't want to teach anti-patterns. What's your suggestion, should I store these informations into 3 separate tables?

**Comment by pleerock** [comment]
> anti-patterns

anti-patterns? I would call creating an abstraction over two completely different things is an anti-pattern.

> What's your suggestion, should I store these informations into 3 separate tables?

I did not completely understood your task and all your requirements to answer.

**Comment by darkbasic** [comment]
> anti-patterns? I would call creating an abstraction over two completely different things is an anti-pattern.

What I called an anti-pattern is my current implementation: since you said I was not going to need that feature I thought I was doing something wrong.

> I did not completely understood your task and all your requirements to answer.

For each message I need to store a list of all the users that are going to receive it (the recipients).
For each recipient I also need to store a timestamp of when that user received the message (which does not equal to the date when the message has been sent).
For each recipient I also need to store a timestamp of when that user read the message (which is surely going to happen after the receiving date).

I thought about two different ways to implement it.
The first one is to make a single table called Recipient with the following fields:

Recipient:
```
@ManyToOne({ primary: true })
user,
@ManyToOne({ primary: true })
message,
@Column({ type: "time without time zone", nullable: true })
receivingDate,
@Column({ type: "time without time zone", nullable: true })
readingDate,
```

When you first insert the row you leave both `receivingDate` and `readingDate` set to null. Later you update the row to set `receivingDate` to `now()`. Even more later you update it once again to set `readingDate` to `now()`.

That is the solution that I called 'a possible anti-pattern' because it would need a new feature (let's call it `@DateColumn()`) to set the `time without time zone` type in a db-agnostic way.

The other only solution I thought about is to create three different tables:

Recipient:
```
@ManyToOne({ primary: true })
user,
@ManyToOne({ primary: true })
message,
```

receivingDate:
```
@ManyToOne({ primary: true })
user,
@ManyToOne({ primary: true })
message,
@CreateDateColumn()
receivingDate,
```

readingDate:
```
@ManyToOne({ primary: true })
user,
@ManyToOne({ primary: true })
message,
@CreateDateColumn()
readingDate,
```

I don't like that solution either.

What would be the advised approach instead?

**Comment by pleerock** [comment]
First solution of course, you don't need 3 tables. And I still don't see what you call "anti-pattern". There are no "anti-patterns" and you can create your own decorator and you can not do it - its up to you, there is no anything wrong in it. Wrong when you create 3 tables when you need only one.

**Comment by darkbasic** [comment]
What I absolutely don't like of the first solution is that it is not portable across different engines, because "time without time zone" is postgresql specific. The second solution is even worse, of course.
I find strange that in an ORM there is no way to set db-agnostic types. Of course there is type inference, but this only works for the basic types and I can't do something like
```
@Column({ nullable: true })
receivingDate: Date,
```

You said that typeorm follows YAGNI principle and that we are not going to need generic types, I disagree in that regard. This is one example but there could be many more. Of course I could create my own decorator, but I will have to specify a type for all the existing engines and if you will later introduce support for a new engine it will not work with that.

IMHO the best solution would be adding "db-agnostic" types to the Column decorator, something like that:
```
@Column({ agnosticType: "time", nullable: true })
receivingDate: Date,
```
which translates to `time without time zone` if you use postgresql, etc.

**Comment by pleerock** [comment]
```
@Column({ nullable: true })
receivingDate: Date
```

the following code is already "db-agnostic". If you don't specify a type "Date" automatically will find its database related type.

**Comment by darkbasic** [comment]
Uhm.. I already tried it and it didn't work for some reason. I'll try again, thanks.

**Comment by et** [comment]
Hi, just following in here. Does `UpdateDateColumn` and `CreateDateColumn` no longer work now in the latest 0.2.x release?
