### ISSUE TITLE
Many-to-Many Relations. Issue in Updating existing entity.

### ISSUE THREAD

**Issue by babbarankit** [typeorm/typeorm#1595]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
@Entity('group_message')
export class GroupMessage extends InstitutionBaseEntity implements IGroupMessage {

  @Column({ type: 'text', default: 'default' })
  channel: string;
 
  @JoinTable()
  @ManyToMany(type => Group)
  group: { id: number }[];

  @RelationId((content:GroupMessage) => content.group)
  groupIds: number[];

}
```

When I am trying to update existing message, it is saying  "duplicate key value violates unique constraint \"group_message_group_group_pkey\". I am updating an entity with group = [{ id: 4}];
with entity.group = [{ id: 4}, { id: 5}]. If I remove the group '4'. It get removed from table.
Please help.

**Comment by pleerock** [comment]
Code you are providing is not enough - it does not show the problem, since many to many works in the way you describe. Please provide a **minimal** reproduction git repository or a PR with a failing test.

**Comment by babbarankit** [comment]
Thanks a lot.
Since you have mentioned that ManyToMany works like this, please let me understand a simple thing, how do I solve this thing, else, I shall provide a git repo
I have an entity called Group Message with Many-to-Many relation.
I save a Group Message, with a group=[{id:4}] and later I wish to update the message 
```` const entity = await repository.save({ channel: 'default', group: [{ id: 4}] }); ```
Suppose this saves an entity with Id =1 of Group Message.
Later while I wish to update the entity that my Group Message now be visible to both groups with id 4 and 5.
So I will do something like
```const entity = repositor.findOneById(1);
    entity.group = [{id: 4, id: 5}]
repository.save(entity);```
Here is the problem that I get of duplicate keys in table. Am I doing something wrong. What approach you suggest.
Thanks you again!

**Comment by pleerock** [comment]
you shall not have duplicate keys error. Please provide a minimal reproduction git repository or BETTER a PR with a failing test.

**Comment by babbarankit** [comment]
My mistake. Some other code was creating problem.

**Comment by vanderleymaia** [comment]
I had the same problem, in my case I was trying to **UPDATE** this relationship:

`@ManyToMany(type => UserTypeOrm, integrante => integrante.integrante, {cascade:true, onUpdate:"CASCADE"})  
    @JoinTable()  
    integrantes: UserTypeOrm[];`

using this:

`  async modify(id:string, update:any): Promise<CreateKaizenDto>{



        const original = await this.kaizenRepository.findOne({id}, {
            relations:['integrantes']
        })
       
        if(original){
            await this.kaizenRepository.update({id}, update)
        }   
        const updated = await this.kaizenRepository.findOne({id})     
        return updated
    }`

**doesnt work at all,** then I changed for this:


`    async modify(id:string, update:any): Promise<CreateKaizenDto>{


        const original = await this.kaizenRepository.findOne({id}, {
            relations:['integrantes']
        })

        
        if(original){
            
            await this.kaizenRepository.save(update)//This was the only way to garantee that a MANYTOMANY relationship was saved!
        }   
        const updated = await this.kaizenRepository.findOne({id})     
        return updated
    }
`

Now is updating perfectly.
Hope this help someone.
bye

**Comment by zicaboom** [comment]
```
const repository = getRepository(GroupMessage)
const groupMessage = await repository.findOne({
    where: { id },
    relations: ["groupIds"]
})

groupMessage.groupIds.push({id: 4}, {id: 5})

repository.save(groupMessage)
```

This solve my problem, my english are in work 

for array of groupMessages use forEach
```
const repository = getRepository(GroupMessage)
const groupMessage = await repository.find({
    where: { chanell },
    relations: ["groupIds"]
})

groupsMessage.forEach((groupMessage) => {
groupMessage.groupIds.push({id: 4}, {id: 5})
})
repository.save(groupMessage)
```
