### ISSUE TITLE
SubDocument doesn't get generated ObjectId in MongoDB

### ISSUE THREAD

**Issue by Duskfall** [typeorm/typeorm#1597]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello, I would like to ask you how do you define in Entities models whether a model is a subdocument of another in mongo. If it is, then when we save/update the parent model I want to also add a unique ObjectId in the inner collection when I update the main Entity.

Example taken from docs:
````
export class Photo {

    @ObjectIdColumn() // <---- this is added by me
    id: ObjectID;

    @Column()
    url: string;

    @Column()
    description: string;

    @Column()
    size: number;
}

@Entity()
export class User {

    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column(type => Photo)
    photos: Photo[];

}
````

If I save a User afterwards, I want the photos that are included in the user to also get an object id. This is not happening currently. Any suggestions why?

**Comment by pleerock** [comment]
In mongodb documents object id are generated only on top level, right? I think this answers your question.

**Comment by Duskfall** [comment]
Before the refactoring to typeorm I had a mongoose schema like so

````
let layer = new mongoose.Schema( {
	name: String,
	html: String,
	type: String,
} );

let project = new mongoose.Schema( {
	name: String,
	layers: [ layer ],
} );

````
That way the schema generated object ids for the subdocument. Is this somehow supported in typeorm?

**Comment by Duskfall** [comment]
Thanks for confirmation.
