### ISSUE TITLE
VersionColumn

### ISSUE THREAD

**Issue by alekseymakhankov** [typeorm/typeorm#1598]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Hello, how version column works? Could I get old versions of entity or this is just a number which incremets when entitity update?

**Comment by pleerock** [comment]
> this is just a number which incremets when entitity update?

correct, its not revision control functionality.
