### ISSUE TITLE
Column name in relations

### ISSUE THREAD

**Issue by andreasrueedlinger** [typeorm/typeorm#16]
Is it somehow possible to set the column name for a relation on the owning side?
Example:
books and chapters, one book has many chapters. In code I want the property be named "book" in the chapter class, but in database I usually set "book_id".
Is that possible to configure?

**Comment by pleerock** [comment]
it is possible, if you have a many-to-many relation you need to use `@JoinTable` decorator. For other relations you can use `@JoinColumn` decorator.

**Comment by pleerock** [comment]
See examples [here](https://github.com/typeorm/typeorm/blob/master/sample/sample21-custom-join-table-column/entity/Post.ts) and [here](https://github.com/typeorm/typeorm/blob/master/test/functional/persistence/custom-column-names/entity/Post.ts)

**Comment by andreasrueedlinger** [comment]
Thanks for your fast help!
