### ISSUE TITLE
Is there a way to use typeorm in browser with webpack?

### ISSUE THREAD

**Issue by YagoLopez** [typeorm/typeorm#1602]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello. I would like to use create-react-app (reactjs and webpack) + sql.js + typeorm to keep a database in memory in browser. At this moment when I include typeorm in my create-react-app get something related to "platform()" errors. Could you provide any direction to acomplish this? Thank you.

**Comment by daniel-lang** [comment]
You will need to either change your webpack configuration or import typeorm from `typeorm/browser` as the normal version is node only.
You can find more information [here](https://github.com/typeorm/ionic-example) - this is taken from the ionic example but it will be the same.

**Comment by YagoLopez** [comment]
Thank you @daniel-lang but it seems i need systemjs to run typeorm in browser or cordova as requirement. None of that is an apropiated solution for me. I'm creating my own ORM for using a sql database in the browser. By the way it would be much more easier manage state (with a sqlite database for example) than Redux. In my opinion Redux reinvent the wheel and is complicated. Databases in server have solved the problem of state management much more time ago. My intention is to use something like that in client. Also, it would be very easy to query and filter related data using SQL. If you have any comment or idea about it I would like to know it. Cheers.

**Comment by daniel-lang** [comment]
I pointed you to the ionic example because it uses webpack. The documentation for webpack is [here](http://typeorm.io/#/supported-platforms/browser), you don't want to work with the example.
TypeORM in the browser supports every driver/database type that can be run in the browser. Currently we support sql.js, cordova and websql (not fully supported).

**Comment by YagoLopez** [comment]
The issue is I want to use create-react-app for typescript and If I'm not wrong I would have to eject to customize webpack configuration, what I want to avoid. Tried a couple of times but couldn't get typeorm working with that setup.

**Comment by daniel-lang** [comment]
If you import from `typeorm/browser` instead of `typeorm` you don't have to use the custom webpack config.
This means, that you can't share you entities and repositories that you may have with a nodejs project.

**Comment by YagoLopez** [comment]
I think I tried that before but I'll try again. Now I'm a little busy but in a few days I'll report it here for anyone interested.

**Comment by pleerock** [comment]
I'll close this issue. @YagoLopez please provide more info once you test it.
