### ISSUE TITLE
Should @PrimaryGeneratedColumn id be updateable?

### ISSUE THREAD

**Issue by lujakob** [typeorm/typeorm#1605]
**Issue type:**

[x] question

How can I prevent the entity id, which is marked as primary key with decorator 'PrimaryGeneratedColumn', of being able to be updated? I want to prevent this being done from my REST API.

**Database system/driver:**

[x] `mysql`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**
My user entity:

`import {Entity, PrimaryGeneratedColumn, Column, BeforeInsert} from "typeorm";
import * as crypto from 'crypto';

@Entity()
export class User {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  username: string;

}`

In my service class:

`
    const updated = {id: 999};
    await this.userRepository.save(updated);
`

**Comment by pleerock** [comment]
if you pass entity to `save` method with *new* id, nothing will be updated, just new entity will be inserted instead. I don't understand what is your issue

**Comment by lujakob** [comment]
Pleerock you're right. A new entity is being created and it doesn't affect the old. I was sitting at the computer for too long I guess. Sorry and thanks.
