### ISSUE TITLE
Create from nested object with lazy relation

### ISSUE THREAD

**Issue by gutenye** [typeorm/typeorm#1608]
**Issue type:**

[] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Given
```ts
import { BaseEntity, ManyToOne, OneToMany } from 'typeorm'

class Author extends BaseEntity {
  @Column()
  name: string

  @OneToMany(() => Post)
  posts: Promise<Post[]>
}

class Post extends BaseEntity {
  @ManyToOne(() => Author, 'posts', { cascadeInsert: true })
  author: Promise<Author>
}

await Post.create({author: Promise.resolve({name: 'author1'})}).save
```

Got
```
START TRANSACTION
executing query:  INSERT INTO "author" DEFAULT VALUES  RETURNING "id"
query failed:  INSERT INTO "author" DEFAULT VALUES  RETURNING "id"
error:  { error: null value in column "name" violates not-null constraint
...
```

But eager relation works:  `Post.create({author: {name: 'author1'}})`

**Comment by pleerock** [comment]
You need to use following syntax:

```ts
await Post.create({author: PromiseUtils.create({name: 'author1'})}).save
```

Lazy relations aren't what people usually need to use. Just be aware.

**Comment by gutenye** [comment]
@pleerock
 It works, thanks.

I use `typeorm` with `GraphQL`. If I understand it right, Lazy relations are the only way to use inside `GraphQL` resolvers. 

But lazy relations are more complex than eager relations in many cases, is there a way to use eager relations with `GraphQL`?

**Comment by pleerock** [comment]
I don't use lazy relations with graphql. Instead I created abstraction and use `connection.relationIdLoader` (can be found in latest `@next`) to find related entities for relation resolvers. I'll publish a framework with concrete implementation in the near future.

**Comment by gutenye** [comment]
That's great news! Looking forward to the framework.
