### ISSUE TITLE
show before/after save values in typeorm

### ISSUE THREAD

**Issue by cometta** [typeorm/typeorm#1609]
**Issue type:**

[✓  ] question
[ ] bug report
[ ✓ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[✓  ] `mongodb`
[ ] `mssql`
[✓  ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ✓ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Is typeorm has a  built in feature to print before/after save values in database? We would like to have a feature for audit trail purpose.

**Comment by yhpark** [comment]
Are you looking for these? http://typeorm.io/#/listeners-and-subscribers/beforeinsert http://typeorm.io/#/listeners-and-subscribers/afterinsert

**Comment by pleerock** [comment]
right, he needs to use subscribers.

**Comment by cometta** [comment]
in order to get before value, i would need to do one query call inside @BeforeInsert ? and compared with the current value ? Is the the only way?

**Comment by pleerock** [comment]
its the most reliable way

**Comment by cometta** [comment]
would add up burden to database for making too many call. Seems that is the only way.

**Comment by pleerock** [comment]
you can save old data before you make modifications, then read this data where you need it, if you want to avoid extra query. But its not related to typeorm, its your specific task.

**Comment by nelsonec87** [comment]
From the docs: If you run save without modifying anything from the model, @BeforeUpdate and @AfterUpdate will not run.

From that I assume typeorm somehow already knows what/if something has changed, Can't it just make this info available in the event listener?

**Comment by Veetaha** [comment]
@nelsonec87 Totally agree with you, @pleerock what prevents you from exposing previous value?

**Comment by gkniazkov** [comment]
Hi, for my case AfterLoad decorator helped to save the initial value in private variable

**Comment by fullofcaffeine** [comment]
@pleerock Is there an API for getting the previous values, as @nelsonec87 mentioned? I'd be interested.

**Comment by dlipeles** [comment]
@nelsonec87 @fullofcaffeine , I created an item for this request -> #4792
