### ISSUE TITLE
joinAndSelect can't find entity from inverse side of relation

### ISSUE THREAD

**Issue by royibernthal** [typeorm/typeorm#161]
I hvae a OneToOne relation between Request and Ticket (owning side).
In my testings I also removed the cascade options in both entities, they didn't seem to be the source of the problem.

**Request**

```
@OneToOne(type => Ticket, ticket => ticket.request, {
        cascadeInsert: true,
        cascadeUpdate: true,
        cascadeRemove: true
    })
    ticket: Ticket;
```

**Ticket**

```
@OneToOne(type => Request, {
        cascadeInsert: true,
        cascadeUpdate: true,
        cascadeRemove: true
    })
    @JoinColumn()
    request: Request;
```

Whenever I try to innerJoinAndSelect ticket when fetching a request, it fails and nothing is returned:

```
var entity: Request = await this.connection.entityManager.findOneById(Request, 1, {
				alias: 'request',
				innerJoinAndSelect: { ticket: 'request.ticket' }
			});
```

However when doing the opposite from the owning side of the relation, it works as expected:

```
var entity: Ticket = await this.connection.entityManager.findOneById(Ticket, 1, {
				alias: 'ticket',
				innerJoinAndSelect: { request: 'ticket.request' }
			});
```

It's obvious that it should work from the owning side of the relation as the foreign key is fetched from the table of the owning side (latter example), but I thought typeorm has some magic under the hood to make it work for the side that doesn't own the relation as well.

Is it a bug or am I missing something?

**Comment by pleerock** [comment]
yes it should work. I added tests which confirm that it does work. Please compare with your local stuff.

**Comment by royibernthal** [comment]
It works in most cases, but I have 1 case where it clearly doesn't.

I'm having problems reproducing with minimal code this and a few other bugs in typeorm.
There are pieces of code that can work under simple circumstances, but when the entities relations get more complex, bugs start to appear.

Would you be willing to do a remote control session to see if you can understand the issues in my project?
I'll be able to highlight for you very simple pieces of code that exist in a project with complex entities relations. It should help you patch some bugs in the typeorm repo, and help me have a working project :)

**Comment by pleerock** [comment]
Im supporting a project that uses typeorm with hundred of entities and 300 tables and there are lot of relations, so I know about complex entity relations ;) I afraid remote control session can take too much time. I'm sure you can reproduce your issue with smaller examples, just need more effort and time from your side.

**Comment by royibernthal** [comment]
I guess you're right :) I reproduced this issue as well in a smaller example.

Most likely not all the code in app is absolutely necessary, but it's pretty straightforward and concise as it is, so I expect you shouldn't have problems with it.

https://www.dropbox.com/s/jp83cz2kasr2kr9/typeorm_repr_request.zip?dl=0

Hopefully I'll be able to reproduce more issues soon.

**Comment by pleerock** [comment]
Its not working because logic in your code is not correct. First you are persisting `authRequest` WITHOUT ticket. Then you are loading it (`authRequest`, because its id = 1) using INNER JOIN ticket. And since inner join does not return you ticket the whole request is not returning because its inner join, not left join.

**Comment by royibernthal** [comment]
Noob mistake, thanks for pointing it out.
