### ISSUE TITLE
right way to have typed WHERE statements

### ISSUE THREAD

**Issue by theigor** [typeorm/typeorm#1610]
**Issue type:**

[x] question

**Database system/driver:**

[x] `mysql` / `mariadb`

**TypeORM version:**

[x] `0.1.12`

**Steps to reproduce or a small repository showing the problem:**

Hi,

I just want to make sure I am following best practices. I am finding myself using a lot of strings where I _feel_ there should be typed references. For example, in the following snippet,

```ts
repo.createQueryBuilder("u")
    .where(`u.auth_user_id = ${authid}`)
    .leftJoin(UserApproval, "ua", "u.user_id = ua.user_id")
```

both "auth_user_id" and "user_id" are not typed to anything. If I rename them in the model, I won't get any compilation errors. Is there something I am missing? Is there a better way to reference types? I can't find anything in the docs or any examples.

Thanks!

Igor

**Comment by pleerock** [comment]
No there is no other way. Its simply not possible because you are building sql query and sql queries are too much dynamic and string is required to build such dynamic. There is a discussion regarding alternative query builder in #128

**Comment by theigor** [comment]
Thanks!

**Comment by dgreene1** [comment]
Just a fun idea here: It would be possible to use the `keyof` operator to at least make sure that the user is not making spelling mistakes. Here's some scratch ideas:

If we're trying to replicate this:
```
     .where("photo.isPublished = true")
```

It could be constructed like this:
```
var myPhoto = new Photo();

type ComparisonOperators = "<" | ">" | "<=" | ">=" | "=";

function whereBuildOne<T, K>(baseObj: T, baseObjName: string, attributeName: keyof T, valueToCompareTo: string | number | boolean, comparisonOperator: ComparisonOperators){
    return `${baseObjName}.${attributeName} ${comparisonOperator} ${valueToCompareTo}`
}

var builtValue = whereBuildOne(myPhoto, "photo", "isPublished", true, "=");
console.log(builtValue); // Successfully prints out: photo.isPublished = true
```

The cool part is that if the developer accidentally spelled "isPublishedZ", then TypeScript will prevent compilation and we'll say: "Did you mean isPublished?"
