### ISSUE TITLE
Add LIMIT 1 to findOne to make sure that only a single record is fetched from the database

### ISSUE THREAD

**Issue by DMW007** [typeorm/typeorm#1613]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Having the following entity
```
@Entity()
export class TestEntity {
    @PrimaryColumn() id: number
    @Column() test: string
}
```

I want to get the latest added entity. So I used `findOne()` with a descending order on `id` attribute like this:

```
let latestIdEntry = await dbCon.getRepository(TestEntity).findOne({ 
        order: { id: 'DESC' } 
})
```
According to the return value, I would expect to always get only a *single* entity. But the following SQL query is generated:

```
SELECT `TestEntity`.`id` AS `TestEntity_id`, `TestEntity`.`test` AS `TestEntity_test` FROM `test_entity` `TestEntity` ORDER BY `TestEntity`.`id` DESC
```
The `TestEntity ` table has about 1 million rows. So this entry would cause my programm to hang for a long time, since TypeORM loads ALL of the entities from the database and serialize them. 

### Solution
Simply add a `LIMIT 1` at the end of every generated query from `findOne`. This make sure, that only one row is fetched from the database, as expected. This is at least required when no filter condition is specified. And it even doesn't hurt when it's there, although the filter condition only return one result (eg when we filter on a unique attribute like `findOne({ userId: 1 })`.

Currently, I've to do something like this to avoid the described issue:
```
let latestList = await dbCon.getRepository(TestEntity).find({
    order: {
       id: 'DESC'
    },
    take: 1
})
let latestEntry = latestList[0]
```
Now I got a SQL query with limit clause, but it blows the code up. For good quality code it would also required to check if `latestList` has any elements, so that we don't get any kind of NullReferenceException when the requested entity doesn't exist in the database.

**Comment by pleerock** [comment]
We can't simply add LIMIT we also need to make sure that user do not have anything joined, otherwise joined data will be truncated. I don't see much value in using `findOne` without arguments - if you need "first" or "last" probably better if you write such query explicitly.

**Comment by ph55** [comment]
Indeed misleading.

I had issue with `findOne` and cache.

When using cache with `findOne` I've expected only one row being cached, but since query have no LIMIT, thousands of rows might be cached - witch is wrong IMO.

**Comment by jenyayel** [comment]
I have to agree that this unexpected behavior. From my experience with other ORMs similar method will fetch only one record. It took us a while to figure out why the method timeouts on large tables, until will looked into raw query log.

**Comment by pleerock** [comment]
This functionality (fetch only one record) should be implemented in the latest versions.
