### ISSUE TITLE
Datetime2 with any precision result in datetime2(7) in database

### ISSUE THREAD

**Issue by Zihark17** [typeorm/typeorm#1615]
I have an entity with a datetime2 with precision 0. When the schema is synchronized the column type is set to datetime(7) in the datebase instead of datetime(0).

**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```ts
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity('Foo')
export class FooEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column('datetime2', { precision: 0 })
    date: Date;
}
```
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.25`. You can try it via `npm i typeorm@next`.
