### ISSUE TITLE
How to create composite UNIQUE constraint?

### ISSUE THREAD

**Issue by misticwonder** [typeorm/typeorm#1616]
Is there a way to create composite UNIQUE constraint (not INDEX, exactly CONSTRAINT)? 
I use postgres.

**Comment by pleerock** [comment]
Currently only unique index. In some databases unique constraints and unique indices are the same. Complete support for unique constraints expect in 0.2.0. Consider executing sql if you need exactly constraints.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.

**Comment by pleerock** [comment]
@AlexMesser  can you update docs on how to create unique constraints?

**Comment by PavanBahuguni** [comment]
Is it possible to have composite unique keys? If yes how do we do that?

**Comment by pleerock** [comment]
yes, use `@Unique` decorator

**Comment by AlexMesser** [comment]
@PavanBahuguni http://typeorm.io/#/decorator-reference/unique

**Comment by PavanBahuguni** [comment]
@pleerock @AlexMesser  @Unique for the entity is what i was looking for. Thanks.

**Comment by tobyhinloopen** [comment]
For the really lazy readers (like me), use:

```ts
@Entity()
@Unique(["fieldName"])
export class MyEntity {
// ...
```
