### ISSUE TITLE
Question: Repository.save(...) sets `nullable` property to `null`. Intended?

### ISSUE THREAD

**Issue by geropl** [typeorm/typeorm#1617]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I got a simple class `User`. The user may or may not have a `avatarUrl`, the later case being denoted by `undefined` (the contract of `User`). I try to map it to `NULL` as follows:
```ts
class User {
    @PrimaryColumn()
    id: string;

    @Column({
        nullable: true,
        transformer: {
            to(value: any): any {
                return value;
            },
            from(value: any): any {
                if (value === null) {
                    return undefined;
                }
                return value;
            }
        }
    })
    avatarUrl?: string;
```

This works great for reads (I suspect the `ValueTransformer` gets called then).

```ts
const existingUser = {
    id: '1234'
};
repository.save(existingUser);
```
After running the above, however, `existingUser.avatarUrl` is `null`, violating the TS contract for `User`.

How is this supposed to be used? Am I supposed to copy my objects before sending them to `save(..)`? Or should I read them back before using them? Or am I wrong trying to map `undefined` to `NULL`?

**Comment by pleerock** [comment]
yes, it sets null to your **nullable** columns and it is by design. If it can be null then your "typescript contract" must reflect it, right? Personally I don't see any value in transforming null to undefined.

**Comment by geropl** [comment]
How would you handle optional values then? The first thing I tried was `@Column({ default: undefined })`, which did not work. Do you have a custom value denoting `default: undefined`?

I achieved the desired result using
```ts
    @Column({
        default: '',
        transformer: {
            to(value: any): any {
                if (value === undefined) {
                    return '';
                }
                return value;
            },
            from(value: any): any {
                if (value === '') {
                    return undefined;
                }
                return value;
            }
        }
    })
    avatarUrl?: string;
```

If there is a more easier or idiomatic way of doing this please let me know.

**Comment by pleerock** [comment]
> @Column({ default: undefined })

its a **database** default value, databases do not have "undefined" type.

Properties in your entity can have 3 states:

* actual value - when actual value is stored 
* null - when no value is stored, its a special state called "null"
* undefined - just nothing. Value does not exist in your model, it does not affect database somehow

I don't know what you are trying to do but looks like you misunderstood concepts of null and undefined and their role.

**Comment by geropl** [comment]
I understand that the library provides a direct mapping between null and `NULL`. The interesting bit here:

> - undefined - [...] it does not affect database somehow

I'd like to do exactly that. But then typeorm complains about my column having 'no default value', that's the where my journey started, and I came to the solution above, mapping `undefined` to empty string.

**Comment by pleerock** [comment]
> But then typeorm complains about my column having 'no default value', 

can you explain with examples what cause you this?

**Comment by geropl** [comment]
Sorry for the long delay. If still relevant, here is an example repo: https://github.com/geropl/typeorm_issue_1617

**Comment by pleerock** [comment]
Everything works as expected. Columns are NOT NULLABLE by default. If you want to have a nullable value in the database you need change this:

```ts
    @Column()
    avatarUrl?: string;
```

To this:

```ts
    @Column({ nullable: true })
    avatarUrl?: string;
```

**Comment by pleerock** [comment]
Does not look like an issue. Let me know if you need more info.
