### ISSUE TITLE
DeepPartial not exported?

### ISSUE THREAD

**Issue by cojack** [typeorm/typeorm#1618]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `not related`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Why `DeepPartial` is not exported? Any purpose?

**Comment by pleerock** [comment]
no, there is no purpose, we can export it. Feel free to provide a PR.

**Comment by cojack** [comment]
@pleerock here you are #1619 ;)
