### ISSUE TITLE
OneToOne relation with both sides "owning" the relation

### ISSUE THREAD

**Issue by royibernthal** [typeorm/typeorm#162]
Since typeorm is still not yet entirely stable, I'm experiencing problems with entities whose side don't own the relation. (more than 1 issue)

Would it make sense to do a JoinColumn() in both entities so that they will both own a foreign key of the other side of the OneToOne relation?

Doing so is likely to solve the issues as well as obviate some queries, correct?

**Comment by pleerock** [comment]
> Would it make sense to do a JoinColumn() in both entities

No, its not possible, and probably it wont ever support it

> Since typeorm is still not yet entirely stable, I'm experiencing problems with entities whose side don't own the relation

Please report corresponding issues and I'll try to fix them as soon as I can. You can attend in the process too by sending a PRs with fixes.

**Comment by royibernthal** [comment]
I see. I'll report any issues I find.
