### ISSUE TITLE
How can one add new driver for database not yet supported?

### ISSUE THREAD

**Issue by D054981** [typeorm/typeorm#1621]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi there, is there any option to add custom/additional driver for databases not yet supported by the package?

Thx in advance.

**Comment by pleerock** [comment]
yes just take a look how other drivers are implemented, create a new driver and start implementing it. Source code is available

**Comment by D054981** [comment]
well, this would have been my approach, but to plugin the new driver I would need to change the factory classes etc. as well as there is fixed coding which will throw an exception if the database type passed in the options does not match the supported list. Or am I mistaken?

**Comment by pleerock** [comment]
Its not clear to me what you mean. Probably best way is to start and come back with more specific questions with real problems you'll face.

**Comment by D054981** [comment]
Well, thanks for your time.
I plan to use typeorm in our project. However, the database we are currently using does not have any driver implemented.
Therefore I started to implement my own driver. However, when I  call this:
`createConnection({
    type: "newDB",
    host: "localhost",
    port: 3306,
    username: "user",
    password: "pwd",
    database: "test",
    entities: [
        Photo
    ],
    synchronize: true,
    logging: false
})`

it is throwing an error, as the factory method creating the connection calls the DriverFactory which does a switch on known drivers:
`export class DriverFactory {

    /**
     * Creates a new driver depend on a given connection's driver type.
     */
    create(connection: Connection): Driver {
        const type = connection.options.type;
        switch (type) {
            case "mysql":
                return new MysqlDriver(connection);
            case "postgres":
                return new PostgresDriver(connection);
            case "mariadb":
                return new MysqlDriver(connection);
            case "sqlite":
                return new SqliteDriver(connection);
            case "cordova":
                return new CordovaDriver(connection);
            case "sqljs":
                return new SqljsDriver(connection);
            case "oracle":
                return new OracleDriver(connection);
            case "mssql":
                return new SqlServerDriver(connection);
            case "websql":
                return new WebsqlDriver(connection);
            case "mongodb":
                return new MongoDriver(connection);
            default:
                throw new MissingDriverError(type);
        }
    }

}`

and will raise "MissingDriverError" in my scenario. I know I could just change the source code of the DriverFactory, but I'm looking for a way to "plugin" my driver without the need to enhance/modify the source code of this packed. This would enable a proper and clean deployment of our application using the npm package of typeorm + our custom driver on top.
I'm somehow new to typescript and do not have a real idea how to extend the DriverFactory or plugin my driver.

I hope my explanations help you to help me ;)

BR

**Comment by pleerock** [comment]
Can I ask you what database are you using?

**Comment by D054981** [comment]
well sure ... HANA ;)

**Comment by pleerock** [comment]
so if its something you would like to make open source then you just need to fork typeorm and start changing things, including that factory. There is also an option to make additional api to factory if you want your additional driver to be as an extension.

If its something not public and for your own needs, then easiest thing for you is to change prototype and do some hacking.

**Comment by D054981** [comment]
hi, thanks for your efforts. I would go for the option of having an API to plugin into the factory for the time being. The process in my company to get the approval to contribute to this project may take longer than this.

Thx in advance.

**Comment by pleerock** [comment]
For now you can simply override method which is quite natural way in JavaScript. I'll think in the future how we can add extra api for this purpose.

**Comment by sassman** [comment]
> well sure ... HANA ;)

did you found a solution how to integrate with HANA? ..having the same issue.. and not sure if typeorm is a possible solution.

**Comment by D054981** [comment]
Hi there,
due to project constraints I've not further investigated. However, other colleagues of mine are looking into this. However, I'm not able to give any insights into their activities....

**Comment by jprules321** [comment]
How would you go about getting typeorm to load sql3cipher instead of sql3 ?

**Comment by brainafesoh** [comment]
> For now you can simply override prototype method which is quite natural way in JavaScript. I'll think in the future how we can add extra api for this purpose.

Hey @pleerock, please any hints on how this can be done?? What classes should I be extending? Which methods to overide? e.t.c...

**Comment by pleerock** [comment]
@brainafesoh you have to figure out it by yourself... I could document it or improve API to better to support this integration, however it requires more time than I have. There are bunch of PRs by users who integrated many new drivers into TypeORM, you can see them as a reference.

If you are talking about sqlite-based driver - it's quite easy to add and integrate, but if you are talking about completely new driver - it's a big challenge to implement correct schema synchronization.
