### ISSUE TITLE
NOT NULL constraint failed after a new column is added (SQLite)

### ISSUE THREAD

**Issue by SeanConnelly** [typeorm/typeorm#1623]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Apologies if this is not a bug, this is literally my first couple of hours reading through the documentation and using the CLI tool.

**1. Create a new project with sqlite...**

	C:\Temp>typeorm init --name foobar --database sqlite
	Project created inside C:\Temp/foobar directory.

	C:\Temp>cd foobar

	C:\Temp\foobar>npm update

	> sqlite3@3.1.13 install C:\Temp\foobar\node_modules\sqlite3
	> node-pre-gyp install --fallback-to-build

	[sqlite3] Success: "C:\Temp\foobar\node_modules\sqlite3\lib\binding\node-v57-win
	32-x64\node_sqlite3.node" is installed via remote
	foobar@0.0.1 C:\Temp\foobar
	+-- @types/node@8.9.4
	+-- reflect-metadata@0.1.12
	+-- sqlite3@3.1.13
	+-- ts-node@3.3.0
	+-- typeorm@0.1.12
	`-- typescript@2.5.2

	npm WARN foobar@0.0.1 No repository field.
	npm WARN foobar@0.0.1 No license field.

**2. Run the project, all is ok...**

	C:\Temp\foobar>npm start

	> foobar@0.0.1 start C:\Temp\foobar
	> ts-node src/index.ts

	Inserting a new user into the database...
	Saved a new user with id: 1
	Loading users from the database...
	Loaded users:  [ User { id: 1, firstName: 'Timber', lastName: 'Saw', age: 25 } ]

	Here you can setup and run express/koa/any other framework.

**3. Here is the original User entity**

	C:\Temp\foobar>more "src/entity/User.ts"
	import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

	@Entity()
	export class User {

		@PrimaryGeneratedColumn()
		id: number;

		@Column()
		firstName: string;

		@Column()
		lastName: string;

		@Column()
		age: number;

	}

**4. I now edit the Entity and add an additional property called userName...**

	C:\Temp\foobar>more "src/entity/User.ts"
	import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

	@Entity()
	export class User {

		@PrimaryGeneratedColumn()
		id: number;

		@Column()
		firstName: string;

		@Column()
		lastName: string;

		@Column()
		age: number;

		@Column()
		userName: string;

	}

**5. I have enabled logging in the generated ormconfig.json file, and can confirm that syncornize is set to true**

**6. I now start the project again** and get a NOT NULL error on the new userName column....

	C:\Temp\foobar>npm start

	> foobar@0.0.1 start C:\Temp\foobar
	> ts-node src/index.ts

	executing query:  BEGIN TRANSACTION
	executing query:  SELECT * FROM sqlite_master WHERE type = 'table' AND name IN ('user')
	executing query:  PRAGMA table_info("user")
	executing query:  PRAGMA index_list("user")
	executing query:  PRAGMA foreign_key_list("user")

	executing query:  CREATE TABLE "temporary_user" ("id" integer NOT NULL PRIMARY K
	EY AUTOINCREMENT, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "ag
	e" integer NOT NULL, "userName" varchar NOT NULL)

	executing query:  INSERT INTO "temporary_user"("id", "firstName", "lastName", "a
	ge") SELECT "id", "firstName", "lastName", "age" FROM "user"
	query failed:  INSERT INTO "temporary_user"("id", "firstName", "lastName", "age"
	) SELECT "id", "firstName", "lastName", "age" FROM "user"

	error:  { Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: temporary_user.u
	serName errno: 19, code: 'SQLITE_CONSTRAINT' }
	executing query:  ROLLBACK
	{ QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: temporary_use
	r.userName
		at new QueryFailedError (C:\Temp\foobar\src\error\QueryFailedError.ts:7:9)
		at Statement.<anonymous> (C:\Temp\foobar\src\driver\sqlite\SqliteQueryRunner
	.ts:54:26)
		at Statement.replacement (C:\Temp\foobar\node_modules\sqlite3\lib\trace.js:1
	9:31)
		at Statement.replacement (C:\Temp\foobar\node_modules\sqlite3\lib\trace.js:1
	9:31)
	  message: 'SQLITE_CONSTRAINT: NOT NULL constraint failed: temporary_user.userNa
	me',
	  errno: 19,
	  code: 'SQLITE_CONSTRAINT',
	  name: 'QueryFailedError',
	  query: 'INSERT INTO "temporary_user"("id", "firstName", "lastName", "age") SEL
	ECT "id", "firstName", "lastName", "age" FROM "user"',
	  parameters: [] }

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.
