### ISSUE TITLE
CLI command entity:create overrides existing files

### ISSUE THREAD

**Issue by Pedrock** [typeorm/typeorm#1624]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
* ```typeorm entity:create -n Test```
* Edit the Test.ts entity file
* ```typeorm entity:create -n Test```
* Test.ts has been overriden with an empty entity

**Comment by pleerock** [comment]
It should probably throw an error that such file already exist.

**Comment by Rhymmor** [comment]
@pleerock, I got this one but I'm not sure about the right way to test CLI. Should CLI be run with exec/spawn in the test?

**Comment by pleerock** [comment]
We don't have CLI commands test covered yet, unfortunately. I think best is to extract logic inside CLI commands and test that classes separately probably. For now fix without test is acceptable.

**Comment by pleerock** [comment]
thanks @Rhymmor for the fix.
