### ISSUE TITLE
Cassandra Support

### ISSUE THREAD

**Issue by weeco** [typeorm/typeorm#1626]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

I'd be happy to see **Cassandra support** in typeorm. Currently there are a couple unmaintained ORMs. Express-cassandra is the most promosing one of them, but typeorm would be my preferred choice.

**Comment by pleerock** [comment]
Feel free to contribute :) I currently do not have plans to work on a new driver, so Im going to left this initiative to the community.

**Comment by WonderPanda** [comment]
@weeco I've been working on a TypeScript library for Cassandra over the last week or so (very early days) but progress is coming along really quickly. https://github.com/WonderPanda/NoSequel

Should be ready for some beta testing within the next week which will cover functionality for table schema generation, intelligent querying, automatic mapping between db rows and entities, deletion, etc.

If you feel like popping over and opening up some issues for the "need to have" functionality you're looking for in a library I'd definitely take a look at bringing that in.

**Comment by 1gluk** [comment]
> Не стесняйтесь вносить свой вклад :) В настоящее время у меня нет планов по разработке нового драйвера, поэтому я собираюсь оставить эту инициативу сообществу.

https://www.npmjs.com/package/cassandra-driver

**Comment by 1gluk** [comment]
> Feel free to contribute :) I currently do not have plans to work on a new driver, so Im going to left this initiative to the community.

https://www.npmjs.com/package/cassandra-driver

**Comment by tskweres** [comment]
> > Feel free to contribute :) I currently do not have plans to work on a new driver, so Im going to left this initiative to the community.
> 
> https://www.npmjs.com/package/cassandra-driver

Is there a good example of this with Typescript / NestJS?

**Comment by SpartanX1** [comment]
> 
> 
> > > Feel free to contribute :) I currently do not have plans to work on a new driver, so Im going to left this initiative to the community.
> > 
> > 
> > https://www.npmjs.com/package/cassandra-driver
> 
> Is there a good example of this with Typescript / NestJS?

Hi @tskweres and @weeco , I just wrote an article on that. Hope it's helpful !
https://medium.com/@basakabhijoy/nestjs-with-cassandra-243f584bb6ec

**Comment by chamerling** [comment]
Hello all,

Do you still have no plans to add new driver in typeorm? If not, maybe adding an API to be able to add third party drivers will do the job. WDYT?

**Comment by SirBr4him** [comment]
Hi everyone,

Can we have updates on this? i'm using nestjs and i'd like to use TypeORM with cassandra if it's possibile.
Can someone help if there is no plans for this new drive?

thnx

**Comment by emanu7478** [comment]
Is there any plan to integrate Cassandra DB with Type ORM in Nest JS ? @Ginden

**Comment by Ginden** [comment]
@emanu7478 Well, it's marked as "accepting PRs" since 2018. No work is being done currently.

**Comment by dkbhadeshiya** [comment]
Looks like a long shot would someone be interested on working on this with me?

**Comment by stevenlafl** [comment]
@imnotjames Is there any chance you know anyone who has integrated another DBMS that could take questions, and give me some pointers? I started doing this for Prisma but I hit a dead end because they use Rust now.
