### ISSUE TITLE
This operation is not supported by Mongodb driver.     at MongoDriver.escapeQueryWithParameters

### ISSUE THREAD

**Issue by ovr** [typeorm/typeorm#1628]
**Issue type:**

[ ] question
[X] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```typescript
await connection.createQueryBuilder()
    .update(SmsCode)
    .set({ used: true })
    .where('phone = :phone', { phone })
    .execute();
```

**Comment by ovr** [comment]
latest (master)
https://github.com/typeorm/typeorm/blob/master/src/driver/mongodb/MongoDriver.ts#L210

next
https://github.com/typeorm/typeorm/blob/next/src/driver/mongodb/MongoDriver.ts#L211

![image](https://user-images.githubusercontent.com/572096/36526717-b2b03ec4-17f2-11e8-85b1-2d1e96a67824.png)

Looks likes, it's not implemented, possible We can copy/paste from MySQL driver?)

@pleerock @AlexMesser @daniel-lang

**Comment by pleerock** [comment]
`createQueryBuilder()` is rdbms-only functionality. Its not available in mongo. For mongo use mongoRepository/mongoManager update methods.

**Comment by ovr** [comment]
@pleerock Thank you for explanation!
