### ISSUE TITLE
update query in oracle

### ISSUE THREAD

**Issue by bmackiewicz** [typeorm/typeorm#1629]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ x] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ x] `latest`

**Steps to reproduce or a small repository showing the problem:**

await getConnection()
    .createQueryBuilder()
    .update(Offer)
    .set({ policyId: '123', guid: '567' })
    .where('id = :id', { id: 1 })
    .execute();
in log I see this query:
UPDATE "offer" SET "policyId" = :_updated_policyId, "guid" = :_updated_guid WHERE "id" = :id -- PARAMETERS: ["123","567",1]

In in this query parameters are in double quote but oracle need parameter in single quote, is solution to change double to single ?

**Comment by pleerock** [comment]
We are planning to ship next week `@next` version with oracle problems resolved

**Comment by bmackiewicz** [comment]
ok and @next version will be resolve problem with returning last inserted id to ?

**Comment by pleerock** [comment]
yeah it should resolve that issue as well.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.
