### ISSUE TITLE
Custom condition in leftJoinAndSelect()

### ISSUE THREAD

**Issue by ponanin** [typeorm/typeorm#1630]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello! I had tried to use a custom condition in leftJoinAndSelect method:
```
this.createQueryBuilder('d')
            .where('d.id = :id')
            .leftJoinAndSelect('d.comments', 'c', '"c"."documentId"="d"."id" OR "c"."sourceDocumentId" = "d"."sourceFileId"')
            .setParameters({id: documentId, userId: userId})
```
But it becomes 
```
LEFT JOIN "comment" "c" ON "c"."documentId"="d"."id" AND ("c"."documentId"="d"."id" OR "c"."sourceDocumentId" = "d"."sourceFileId")
```
Also I had tried to replace property to Entity and it works, but I can not get it with getOne(). Is it real to do what I want? thanks.

**Comment by pleerock** [comment]
when you use relations, it means it will return you **related** entities, not just any entities that match given condition. The functionality you want can be implemented using `leftJoinAndMap` function and you shall use Entity instead of relation.

**Comment by ponanin** [comment]
Yes, I agree, that makes sense. I just hoped that there was an opportunity to do it.
