### ISSUE TITLE
Turn logging on for a single operation / toggle after connection creation

### ISSUE THREAD

**Issue by tonyxiao** [typeorm/typeorm#1633]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

In my test I have a bunch of database setup code followed by the actual code I'm testing. sometimes when things go wrong I want to see the raw query. The default logging looks amazing esp. with syntax highlighting - however it can be super verbose as the # of tables grow because all the setup queries / seed queries are just noise.

Is there a way to turn logging on for a single operation? Or say `connection.setLogging(true/false)` after the connection has already been created?

**Comment by pleerock** [comment]
what do you call a "single operation?" And as I understood you only do not like setup queries, right?

**Comment by tonyxiao** [comment]
As in query resulting from a single `find` or `save`, `createQueryBuilder`. 

The operation aspect probably doesn't worth putting too much attention on, as long as there is a way to toggle logging on / off after the initial connection setup I think it's sufficient.

**Comment by tonyxiao** [comment]
and @pleerock sometimes it's setup query, other times it can be just queries from other functions that I don't care about.

**Comment by pleerock** [comment]
Does not really look like something generic what we shall add, including the fact that its hard to do a good design for this feature. If you need to print queries per-query builder then there is a method called `printSql()` in query builder which you can use to get your current query builder's query.

**Comment by tonyxiao** [comment]
Actually it seems that it can be accomplished by passing say extending the `AdvancedConsoleLogger` and add a field called `enabled`, then call override the various `log*` methods to only fire if true. Then pass that class instance into typeorm as the `logger`. Then as I need to turn logging on / off for debugging I can just toggle the `enabled` boolean on the logger that I create. 

So it seems that the use case can be accomplished in user-land, I guess maybe it does not need to be part of core?

**Comment by pleerock** [comment]
Looks so.

**Comment by tonyxiao** [comment]
For anyone needing this capability in the future, this is what I came up with and tested working. 

```ts
import { AdvancedConsoleLogger, QueryRunner } from 'typeorm'

export default class DebuggableLogger extends AdvancedConsoleLogger {
  enabled: boolean = false

  logQuery(query: string, parameters?: any[], queryRunner?: QueryRunner): void {
    if (this.enabled) {
      return super.logQuery(query, parameters, queryRunner)
    }
  }

  logQueryError(
    error: string,
    query: string,
    parameters?: any[],
    queryRunner?: QueryRunner,
  ): void {
    if (this.enabled) {
      return super.logQueryError(error, query, parameters, queryRunner)
    }
  }

  logQuerySlow(
    time: number,
    query: string,
    parameters?: any[],
    queryRunner?: QueryRunner,
  ): void {
    if (this.enabled) {
      return super.logQuerySlow(time, query, parameters, queryRunner)
    }
  }

  logSchemaBuild(message: string, queryRunner?: QueryRunner): void {
    if (this.enabled) {
      return super.logSchemaBuild(message, queryRunner)
    }
  }

  logMigration(message: string, queryRunner?: QueryRunner): void {
    if (this.enabled) {
      return super.logMigration(message, queryRunner)
    }
  }

  log(
    level: 'log' | 'info' | 'warn',
    message: any,
    queryRunner?: QueryRunner,
  ): void {
    if (this.enabled) {
      return super.log(level, message, queryRunner)
    }
  }
}
```

**Comment by artysidorenko** [comment]
slightly different use case here (I was looking to suppress an error for a particular statement), but I found I could also control the logging at individual statement level by taking advantage of the `queryRunner.data` object that's accessible by the logger, if it's helpful:

```
class ConfigurableTypeormLogger extends TypeOrmLogger {
    constructor(
      options: ConstructorParameters<typeof TypeOrmLogger> = ['all']
    ) {
      super(!options)
    }

    async logQueryError(
      error: string,
      query: string,
      parameters?: any[],
      queryRunner?: QueryRunner
    ): Promise<void> {
      if (queryRunner?.data?.suppressLogQueryError) {
        return;
      }
      await super.logQueryError(error, query, parameters, queryRunner)
    }
}
```

```
await entityManager
  .getRepository(MyRepository)
  .save(myObject, {
    data: {
      suppressLogQueryError: true
    }
  })
```
