### ISSUE TITLE
partial select works for left join?

### ISSUE THREAD

**Issue by cometta** [typeorm/typeorm#1635]
**Issue type:**

[✔ ] question
[ ✔] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[✔ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[✔ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
May i know is partial select work when using query builder to do left join? queryBuilder.select(['entity1.id', 'entity2.id'])  I get this error [Duplicate column name 'entity2_id'] when id exist in entity1 that left join with entity2.  However, If i just put partial select for ['entity1.id'], then no issue.

**Comment by pleerock** [comment]
It shall work. Can you please provide a reproduction repo / failing test with reproduction of your issue?

**Comment by pleerock** [comment]
Closing as no answer from reporter.
