### ISSUE TITLE
not return expected entities when select with "alias.*"

### ISSUE THREAD

**Issue by xujif** [typeorm/typeorm#1636]
**Issue type:**

[ ] question
[*] bug report
[*] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[*] `mssql`
[*] `mysql` / `mariadb`
[*] `oracle`
[*] `postgres`
[*] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

select with alias and start not return expected entities result.
example:
```typescript
xxxResp.createQueryBuilder('n')
             .innerJoinAndSelect('n.user', 'user')
            .select(['n.*', 'user.id'])
            .where('n.id = :id', { id: id })
            .getOne()
```
will return 
```
{
    // no entity attributes
    "user": {
        "id": 12
    }
}
```

**Comment by xujif** [comment]
I have found the solution from the source file: "query-builder/transformer/RawSqlResultsToEntityTransformer.ts".
just select with only alias without '.*' then can return expected entities, like
```typescript
xxxResp.createQueryBuilder('n')
             .innerJoinAndSelect('n.user', 'user')
            .select(['n', 'user.id'])   //diffrent
            .where('n.id = :id', { id: id })
            .getOne()
```
but I still think it should compat with select n.*

**Comment by pleerock** [comment]
Closing as no answer from reporter.
