### ISSUE TITLE
Embeddeds not being merged in 0.1.12

### ISSUE THREAD

**Issue by bartlomiej-korpus** [typeorm/typeorm#1638]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.1.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

https://github.com/bartlomiej-korpus/typeorm-embedded-merge-bug-demo

This works fine on next branch.

**Comment by pleerock** [comment]
Consider upgrading to `@next`. Its not worth putting efforts of fixing it in latest.
