### ISSUE TITLE
beforeUpdate subscriber, check updated field

### ISSUE THREAD

**Issue by MardariG** [typeorm/typeorm#1639]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to hash user.password in beforeUpdate subscriber.

Is there any way to know that password field has been updated? So I will hash password only then.

```
beforeUpdate(event: InsertEvent<User>) {
    event.entity.password = 'new hashed password';
  }
```

**Comment by pleerock** [comment]
for now only option you have is to query your entity from the database and compare with your current entity value.
