### ISSUE TITLE
Date Column Timezone

### ISSUE THREAD

**Issue by royibernthal** [typeorm/typeorm#164]
How do I change the timezone for a date column?
I'm using the @CreateDateColumn() for the date column in an entity.

I see in the ColumnOptions interface 3 booleans related to timezone:
timezone?: boolean; (only postgres for now)
storeInLocalTimezone?: boolean;
loadInLocalTimezone?: boolean;

How is a local timezone determined?

Regardless, how do I specify a timezone dynamically?

**Comment by pleerock** [comment]
What database are you using? Postgres? In postgres right now its just delegated to underlaying driver without any modifications. I guess timezone is being extracted from the date object and saved into the database.

**Comment by royibernthal** [comment]
I'm using mysql, forgot to mention that. Is there (or will there be) any solution for that?

**Comment by pleerock** [comment]
AFAIK mysql does not have timezone column data type.

**Comment by pleerock** [comment]
you should not worry about timezone if you just want to store a date. Store dates in utc - thats best approach. But if you need timezones probably you need to store it manually. Or just google how others do it with mysql itself.

**Comment by royibernthal** [comment]
I don't know about a timezone column data type, but some kind of way to change the datetime before you store it in a datetime column, similarly to what you can do in PHP for instance:
http://php.net/manual/en/datetime.settimezone.php

There's probably a node module out there, something like:
https://www.npmjs.com/package/timezone

I'm not entirely sure if this specific module is good/relevant but maybe integrating something like that into typeorm could be a good idea?

But until typeorm supports such a thing, should I simply create a normal number column instead of a date column with typeorm and have full control of the date number I'm storing? (probably using an available module that handles timezones like I suggested above)

**Comment by pleerock** [comment]
> http://php.net/manual/en/datetime.settimezone.php

This just sets timezone for the given Date object. You can do same in javascript. It does not relate to orm.

What I can see from your messages is that you don't really know what you need. Start to work with dates and you'll understand how they work and how orm handles them. After that you can create tickets with description of what exactly you want orm to have.

Just use date columns and store your dates in utc. retrieve utc dates from the database and return them to the client. Client should convert your utc dates to client date time.

**Comment by royibernthal** [comment]
True, I'll probably convert the dates on the client side. This question is purely out of curiosity.

Assuming I would try to store different timezones, what I'm referring to is that for instance @CreateDateColumn() / @UpdateDateColumn create a date automatically (or are they not even created by typeorm?), and there's no way for me to change the timezone if I'd like to use these "events" (create/update). I'd have to create a normal @DateColumn and store the date manually after modifying the timezone, whenever I'm creating or updating a column. Correct me if I'm wrong, I probably don't understand how things work as you say.

**Comment by pleerock** [comment]
`@CreateDateColumn() / @UpdateDateColumn` are columns created by orm. They store a date. Since there is no timezone support in mysql, there is NOTHING to store by them. So, dates should be in utc.

> and there's no way for me to change the timezone if I'd like to use these 

again, if there is no support of timezones by database, there is nothing you can change to be stored.

and again, `@CreateDateColumn() / @UpdateDateColumn` should store dates in utc. Let me know if its not so. On the client side you can then transform this date into client time.

**Comment by royibernthal** [comment]
I understand, thank you.
