### ISSUE TITLE
dynamic entity

### ISSUE THREAD

**Issue by TripleMap** [typeorm/typeorm#1646]
**Issue type:**
[x] feature request

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x ] `latest`

I have dynamic schemes in the form of json models. The system administrator can add or remove some columns in the table. I just can not find a way to implement such opportunities.
1) load entity from json model
2) update entitiy when changing json model
3) use the updated entity

**Comment by pleerock** [comment]
Let me know if you still have questions.
