### ISSUE TITLE
How do I create a connection from ormconfig.json by name?

### ISSUE THREAD

**Issue by HillTravis** [typeorm/typeorm#1648]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have multiple connections outlined in my ormconfig.json file. I now want to create one of those connections (not all of them). How can I create a specific connection from my ormconfig.json file by name?

I don't see anywhere in the documentation or on Google where it says how to do this. It sounds like my options for creating a connection are:

1. Use `createConnection()` with no parameters. This creates the connection using options in ormconfig.json, but this will always create the connection with no name, or the one named 'default'.
2. Use `createConnection()` and pass in all of the connection options, but this does not use ormconfig.json.
3. Use `createConnections()` with no parameters. This creates all of the connections in ormconfig.json, and then I would have to find the one I need. I don't want to do this, because most of the time I don't need all of the connections for a particular process.

I suppose this may turn into a feature request if this functionality doesn't already exist, but I'm very surprised to not find this question asked before now.

**Comment by pleerock** [comment]
This sounds like a specific request. You need to use third method to create all connections. If you don't need some of connections, you can parse ormconfig (take a look on `createConnections` source code) and filter out what you don't need and call `createConnection` for each of filtered connection.
