### ISSUE TITLE
cannot truncate a table referenced in a foreign key constraint (postgres)

### ISSUE THREAD

**Issue by MardariG** [typeorm/typeorm#1649]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**I have simple OneToOne relation like this:**

```
@Entity({name: 'user'})
export class User extends BaseEntity {

  @PrimaryGeneratedColumn()
  id: number;

  @Column({length: '50', nullable: true})
  firstName: string;

  @Column({length: '50', nullable: true})
  lastName: string;

}
```
**and:**

```
@Entity({name: 'account'})
export class Account extends BaseEntity {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  balance: number;

  @OneToOne(type => User, {})
  @JoinColumn()
  user: User;
}
```
**Delete all users and create new one with following code:** 
```
createConnection().then(async (connection) => {
  console.log('Inserting a new user into the database...');
  await connection.getRepository(User).clear(); // remove all users 
  const user = new User();
  user.email = 'admin@admin.com';
  user.role = Role.BORROWER;
  user.password = 'admin';
  user.idnp = '2342332342300';
  await connection.manager.save(user);
  console.log('Saved a new user with id: ' + user.id);

  console.log('Loading users from the database...');
  const users = await connection.manager.find(User);
  console.log('Loaded users: ', users);

  console.log('Here you can setup and run express/koa/any other framework.');

  debug('postgres database connected successfully...');
}).catch((err) => error(err));
```

**Witch produces the following error (error with postgres, with sqlite this error is not pesent.):** 

_
Inserting a new user into the database...
executing query:  TRUNCATE TABLE "user"
query failed:  TRUNCATE TABLE "user"
error:  { error: cannot truncate a table referenced in a foreign key constraint
    at Connection.parseE { ... }backend\node_modules\pg\lib\connection.js:113:22)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:602:20)
  name: 'error',
  length: 238,
  severity: 'ERROR',
  code: '0A000',
  detail: 'Table "account" references "user".',
  hint: 'Truncate table "account" at the same time, or use TRUNCATE ... CASCADE.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'heap.c',
  line: '2983',
  routine: 'heap_truncate_check_FKs' }
error: { QueryFailedError: cannot truncate a table referenced in a foreign key constraint
   .... 
backend\node_modules\pg\lib\connection.js:117:12)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
  message: 'cannot truncate a table referenced in a foreign key constraint',
  name: 'QueryFailedError',
  length: 238,
  severity: 'ERROR',
  code: '0A000',
  detail: 'Table "account" references "user".',
  hint: 'Truncate table "account" at the same time, or use TRUNCATE ... CASCADE.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'heap.c',
  line: '2983',
  routine: 'heap_truncate_check_FKs',
  query: 'TRUNCATE TABLE "user"',
  parameters: [] }
internal/child_process.js:409
      throw errnoException(err, 'kill');
      ^
_

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
This error is not related to typeorm. `clear` calls SQL truncate and it has limitations. More info [here](https://stackoverflow.com/questions/5452760/how-to-truncate-a-foreign-key-constrained-table).

**Comment by MardariG** [comment]
It was suspicious to me because error occurred with postgres, with sqlite this error is not present. Thanks.

**Comment by MardariG** [comment]
with SQLITE the code above result looks like this: 

```
executing query:  DELETE FROM "user"
executing query:  BEGIN TRANSACTION
executing query:  INSERT INTO "user"("email", "idnp", "password", "role") VALUES ($1,$2,$3,$4) -- PARAMETERS: ["admin@admin.com","2342332342300","$2a$10$AQdBAeHBdPpSUSRdNIZyneH22di0daPC1q2IC75U1v6kw.Z
EUf3qS","borrower"]
executing query:  COMMIT

```

And it seems that everything is working as expected.

**Comment by pleerock** [comment]
sqlite is limited and can be less strict in some cases

**Comment by MardariG** [comment]
Apparently ```clear``` is implemented differently on POSTGRES and SQLITE. 
with SQLITE it calse ```DELETE FROM "user"```
with POSTGRES it cals ```TRUNCATE TABLE "user"```

If I use SQLITE _query_  on POSTGRES,
for example ```await User.query('DELETE FROM "user"');``` works with POSTGRES too.  

Or maybe I don't really understand how it works, in this case just ignore it. Thanks.

**Comment by danielatcloudware** [comment]
Actually, Postgres allows truncation of tables linked to by foreign keys relations if CASCADE flag is specified i.e. 

`TRUNCATE TABLE "user" CASCADE `

would work. However, it means that dependent tables will also be truncated.

**Comment by nolazybits** [comment]
@pleerock I got bitten by the same error.
What is the recommended way then to remove all records from a table?
Thanks

**Comment by MardariG** [comment]
I've ended up with this solution: 
```
createConnection().then(async (connection) => {
  if (process.env.NODE_ENV === 'development') {
    await connection.dropDatabase();
    await connection.synchronize();
  }
}).catch((err) => console.error(err));
```

**Comment by nolazybits** [comment]
@MardariG thanks.
Otherwise I haven't tried yet but would .delete({}) work?

**Comment by et** [comment]
I tried `.delete({})` and it works a lot better. Great tip @nolazybits!

**Comment by mikesparr** [comment]
Perhaps add option to `{cascade: true}` on `clear()` and then add the `CASCADE` constraint to query to solve... it does work if you add that and query Postgres directly.
