### ISSUE TITLE
Accept yaml for ormconfig.json

### ISSUE THREAD

**Issue by maxcan** [typeorm/typeorm#165]
In my projects, I vastly prefer yaml for configuration as its much more human readable amongst other reasons.  If the owners are open to that, I'm happy to make a pull request, I just don't want ot go through the work if it there feature wouldn't be acceptable.

**Comment by pleerock** [comment]
yes sure, thats a good new feature, go ahead and create a PR.

**Comment by pleerock** [comment]
Let keep it open maybe someone else including me find a time for this useful feature.

**Comment by pleerock** [comment]
Implemented and available in `0.1.0-alpha.8`.
