### ISSUE TITLE
Facebook flow

### ISSUE THREAD

**Issue by inunotaisho** [typeorm/typeorm#1650]
**Issue type:**
Issue type:

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

I am not a facebook user, I am a typescript user like a good chunk of us, but I am thinking it would be a good idea to add Facebook Flow support to TypeORM. 

**Database system/driver:**
[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**
[ ] latest
[x] @next
[ ] 0.x.x (or put your version here)

Reference:
@eXon

**Comment by pleerock** [comment]
This can only be a community initiative. Im not familiar with Flow and don't think I can afford learning and maintaining huge flow definitions. Someone who is interested in using flow orm needs to take a responsibility to develop flow typings and maintain them.

Thanks for the support btw 🙏

**Comment by inunotaisho26** [comment]
@pleerock Of course and no problem. Would you be willing to put a community tag on this issue and see what happens over the next month?

**Comment by TotallWAR** [comment]
Did anybody create flow definitions?
Don't you know?)

**Comment by pleerock** [comment]
Is flow still alive? 🤣

**Comment by kgrosvenor** [comment]
I like flow!

**Comment by imnotjames** [comment]
If someone would like to create a mechanism to automatically generate flow definitions from typescript as part of our build process, we're always accepting pull requests.

It does seem like flow momentum has slowed down a little bit - facebook moved away from it for yarn & jest. 

While I'll be closing this to help us clean up the backlog a bit don't take that as us refusing to accept pull requests related to it - it's just not something we'll be entertaining as part of the project at this point in time.

But if ya implement it, it will happen.
