### ISSUE TITLE
Plans for typed joins/includes (like Entity Framework)? 

### ISSUE THREAD

**Issue by welkie** [typeorm/typeorm#1651]
**Issue type:**

[ ] question
[ ] bug report
[*] feature request
[ ] documentation issue

I was wondering if there were plans to develop a method performing joins where the compiler is able to catch errors caused by the table names or key names changing. For example, in Entity Framework we can perform joins with LINQ expressions, where we use the class for the joined table. If the class name changes, the compiler can warn us that this query is now broken:

```csharp
var users = await context.Users.Include(u => u.Posts);
```

With TypeORM, according to my understanding after reading the documentation, the same query would be performed like this, where the name of the relation is stringly-typed. A change to the relation name would mean the TypeScript compiler would not be able to warn us that this query is now broken:

```typescript
const users = await userRepository.find({ relations: ["posts"] });
```

Is such a change even technically possible with TypeScript? I understand it has reflective properties, but I don't know how far this goes. Is the team behind TypeORM open to exploring TypeScript features to find out if this is possible?

**Comment by welkie** [comment]
I guess I should have included the closed issues when searching through them. It looks like https://github.com/typeorm/typeorm/issues/128 is already tracking this feature request. If that's the case, feel free to close this one.

**Comment by pleerock** [comment]
Correct, its a duplicate, please join discussion in there.
