### ISSUE TITLE
Exclude pattern in ormconfig

### ISSUE THREAD

**Issue by am17torres** [typeorm/typeorm#1654]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.13` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In general, I store my tests in the same directory as the class itself. E.g.
```
src 
  entity
    Document.ts
    Document.test.ts
```

_ormconfig.js_
```js
const defaults = {
  type: 'postgres',
  host: config.get('db.host'),
  port: config.get('db.port'),
  username: config.get('db.user'),
  password: config.get('db.password'),
  database: 'config.get('db.database')',
  logging: false
};

function getConnectionOptions(environment) {
  var options = {
    local: {
      ...defaults,
      entities: ['src/entity/**/*.ts'],
      migrations: ['db/migration/**/*.ts'],
      logging: true,
      cli: {
        entitiesDir: 'src/entity',
        migrationsDir: 'db/migration'
      }
    },
    test: { ...snip... },
    development: { ...snip... },
    staging: { ...snip... },
    production: { ...snip... },
  };
  return options[environment];
}

module.exports = getConnectionOptions(config.get('env'));
```
The issue is `entities: ['src/entity/**/*.ts']` also matches `*.test.ts` and then throws `describe is not defined`. 

**Is it possible to specify an exclude pattern?** I tried adding `'!src/entity/**/*.test.ts'` to the list of entities but as I'm sure you guess, it doesn't help. 

Any protips are much appreciated.

Thanks!

**Comment by pleerock** [comment]
No this probably not supported. For now you can specify list of entities explicitly. Or implement this functionality in a PR.

**Comment by am17torres** [comment]
@pleerock, thanks for the quick answer. Can you point to the relevant bits of source code where one could start looking if they were interested in submitting a PR?

**Comment by pleerock** [comment]
take a look where [this function](https://github.com/typeorm/typeorm/blob/master/src/util/DirectoryExportedClassesLoader.ts#L6) is used and probably you'll need to change it.

**Comment by am17torres** [comment]
Looks like [node-glob](https://github.com/isaacs/node-glob) supports an `ignore` option.

**Comment by am17torres** [comment]
I was able to get it working by without requiring any code changes.

```js
{
    entities: ['src/entity/**/!(*.test.ts)']
}
```

**Comment by pleerock** [comment]
Cool 👍

**Comment by am17torres** [comment]
It would probably be good to add that info to the docs so other folks don't have to go digging. I was going to add it to https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md but there is nothing in there about either the `entities` or `migrations` options.

**Comment by Nico-Guyon** [comment]
This was causing a strange issue on my project.

After updating jest and ts-jest from v26 to v27, some test suites that were running fine suddenly failed with this message :
Cannot add a test after tests have started running. Tests must be defined synchronously.

I'm not sure why this was working before but I was configuring typeorm with the following glob
`entities; ['src/Domain/Entities/**/*.ts'],`

So after the jest / ts-jest update my test files .test.ts which are located alongside their entities module got included as well on some integrations tests that use an in memory sqlite db to test database specific code.

Changing the entities config solved the problem.
`entities: ['src/Domain/**/!(*.test).ts'],`

I lost quite some time to find this issue, so I'll leave this here in case it helps someone.

**Comment by jackofsometrade** [comment]
Thanks @Nico-Guyon, you saved me some time!  ❤️
