### ISSUE TITLE
Wrong repository order with multiple TransactionRepository inside a Transaction decorator.

### ISSUE THREAD

**Issue by nokutu** [typeorm/typeorm#1656]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.12`

**Steps to reproduce or a small repository showing the problem:**

There is a bug in [Transaction.ts](https://github.com/typeorm/typeorm/blob/master/src/decorator/transaction/Transaction.ts). A commit on the 27th of October[1] changed index accessing to splices, which breaks the order of the TransactionRepository parameters. For example, having this method:

```ts
@Transaction()
    public async deleteMap(a: A,
                           @TransactionRepository(B) bRepository?: Repository<B>,
                           @TransactionRepository(C) cRepository?: Repository<C>,
                           @TransactionRepository(D) dRepository?: Repository<D>,
                           @TransactionRepository(E) eRepository?: Repository<E>) {
        ...
    }
```

The repositories arrive in the following order: 

```Repository<B>, Repository <E>, Repository<C> and Repository<D>```

I looked at the test cases and at least this one[2] passes because there are only 2 TransactionRepository parameters.

[1] https://github.com/typeorm/typeorm/commit/61bc5a2d607c560dcc3518a2fed52ee832d014bb#diff-2e94f8fff0f0f1eb1beb5a00cca526be
[2] https://github.com/typeorm/typeorm/tree/master/test/functional/transaction/transaction-decorator

**Comment by pleerock** [comment]
Are able to contribute and fix it?

**Comment by nokutu** [comment]
Sure, I'll create a pull request reverting those changes. Although the commit was called "fixed bug in transaction decorator", so maybe there was a bug I am unaware of.

**Comment by nokutu** [comment]
Should I extend the test case to take this into account? Just adding 1-2 more repositories.

**Comment by pleerock** [comment]
> Sure, I'll create a pull request reverting those changes. Although the commit was called "fixed bug in transaction decorator", so maybe there was a bug I am unaware of.

It definitely fixes some bug and should not be reverted. I remember that I faced some bug but unfortunately now I don't remember what exactly it fixes. It is related to parameters, probably it does not cover cases when there are other parameters in the method before and/or after transactional parameters. 

> Should I extend the test case to take this into account? Just adding 1-2 more repositories.

what do you mean?

**Comment by nokutu** [comment]
In this case, the error is caused because the metadata fields are in reverse order, which makes the splice call not work as expected. Reversing transactionRepositoryMetadatas should fix it.

> what do you mean?

```ts
@Transaction("mysql") // "mysql" is a connection name. you can not pass it if you are using default connection.
    async saveWithRepository(
        post: Post,
        category: Category,
        @TransactionRepository(Post) postRepository: Repository<Post>,
        @TransactionRepository() categoryRepository: CategoryRepository,
    ) {
        await postRepository.save(post);
        await categoryRepository.save(category);

        return categoryRepository.findByName(category.name);
    }
```
The test has only 2 TransactionRepositories, which doesn't trigger this bug. I can extend it to have 4 of them.

**Comment by pleerock** [comment]
> The test has only 2 TransactionRepositories, which doesn't trigger this bug. I can extend it to have 4 of them.

yes

**Comment by nokutu** [comment]
> probably better if you create a separate test case?

Ok. I'll make the PR later today or tomorrow.

**Comment by fabiooshiro** [comment]
Im trying this lib:
https://github.com/odavid/typeorm-transactional-cls-hooked
seems to work
