### ISSUE TITLE
findOneById without relations option does not return promise for lazyloading 

### ISSUE THREAD

**Issue by hkjeffchan** [typeorm/typeorm#1658]
**Issue type:**

[x] question
[] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```ts 

@Entity()
export class Author {
    @PrimaryGeneratedColumn()
    id: number;

    @OneToMany(type => Post, post => post.author)
    posts: Promise<Post[]>;
}

@Entity()
export class Post {
    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(type => Author, author => author.posts)
    author: Promise<Author>;    
}

// author1 works
        const author1 = await this.authorRepo.findOneById(author.id, { relations: ['posts'] });
        console.log(author1); // already contains all the posts
        const posts1 = await author1.posts;
        console.log(posts); // ok to get all posts

// author2 does not work
        const author2 = await this.authorRepo.findOneById(author.id);
        console.log(author2); // no posts property, shouldn't author2.posts return as a promise here?
        const posts2 = await author2.posts;
        console.log(posts2); // undefined

```
Shouldn't author2.posts return a promise? Is this a bug or do I misunderstand the lazyloading? Thanks!

**Comment by mindonline** [comment]
Confirm. 
Also use lazyload with mariadb and `@OneToOne` relation:
**Entities**
```
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @OneToOne(type => UserRole)
    @JoinColumn()
    role: Promise<UserRole>;

}

@Entity()
export class UserRole {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        unique: true
    })
    roleName: string; 
}
```
**Code:**
```
let u:User = await connection.getRepository(User).findOneById(1);
    console.log(u.id); // Ok. Return => 1
    console.log(await u.role); // FAIL! Return undefined, also u.role => undefined. Why??
```

**Comment by mindonline** [comment]
Seems that automatic lazy detection not work sometimes.
I've overcome this issue with setting lazy flag manually:

`@OneToOne(type => UserRole, {lazy: true})`

**Comment by mindonline** [comment]
Finally, after some digging that look like a ts-node issue due to invalid metadata type generation.
If it compile with tsc from console then automatic lazy detection works. With ts-node metadata type sets to Object instead of Promise, that cause of broken automatic lazy detection. Moreover, TypeORM tests doesnt meet this bug because not use ts-node.

[Related problem in TS repo](https://github.com/TypeStrong/ts-node/issues/511)

Another soulution is to use type-check  argument with ts-node:
`ts-node  --type-check index.ts`

Hope it helps.

**Comment by pleerock** [comment]
Looks like resolved, let me know if no.

@mindonline thanks for investigations.
