### ISSUE TITLE
about MysqlDriver.prototype.escapeQueryWithParameters

### ISSUE THREAD

**Issue by shengxq** [typeorm/typeorm#1659]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

In MysqlDriver, if you add'\\b'when you use regular expressions, you can't match the word boundary of a Unicode character. Why do you do this here?

```
MysqlDriver.prototype.escapeQueryWithParameters = function (sql, parameters) {
        if (!parameters || !Object.keys(parameters).length)
            return [sql, []]; 
        var escapedParameters = [];
        var keys = Object.keys(parameters).map(function (parameter) { return "(:" + parameter + "\\b)"; }).join("|");
        sql = sql.replace(new RegExp(keys, "g"), function (key) {
            var value = parameters[key.substr(1)];
            if (value instanceof Function) {
                return value();
            }
            else {
                escapedParameters.push(parameters[key.substr(1)]);
                return "?";
            }
        }); // todo: make replace only in value statements, otherwise problems
        return [sql, escapedParameters];
    };
```

**Comment by shengxq** [comment]
如果不加'\b',是否有什么影响呢?
If you don't add'\b', is there any effect?

**Comment by pleerock** [comment]
because I want a single word, better to ask what issue you have with it?

**Comment by shengxq** [comment]
you can't match the word boundary of a Unicode character.

不支持使用中文做字段名了
Do not support the use of Chinese to make field names

**Comment by shengxq** [comment]
比如下面这样的代码
For example, the following code
```
await trans.getRepository("s_公司表").createQueryBuilder().insert()
                    .values([{
                        I_公司编号: maxgsbh,
                        C_公司名称: json_in.data.gsmc,
                        C_数据库配置: {
                            host: config.mainDBconfig.host,
                            database: config.mainDBconfig.database,
                            password: config.mainDBconfig.password,
                            username: config.mainDBconfig.username
                        }
                    }]).execute();
```

**Comment by pleerock** [comment]
removing it will bring problems. Probably you need to use english names instead

**Comment by shengxq** [comment]
Modify the regular expression so that the Chinese field name can be supported
What do you think
(?=[.,() ]|$)

**Comment by shengxq** [comment]
@pleerock

**Comment by pleerock** [comment]
Does not look like a proper regexp. Im not string in regexp, so please provide a proper regexp with explanation and lets take a look if it works. Also `escapeQueryWithParameters` is a very sensitive place so make sure this new regexp is efficient.

**Comment by shengxq** [comment]
I replaced the \\b in the code with (?=[.,() ]|$)
\b Only to support the search for English word boundaries,
This is mainly the replacement of the variables in the SQL statement. It may be enough to use such an expression, and please confirm it.
```
 var keys = Object.keys(parameters).map(function (parameter) { return "(:" + parameter + "(?=[.,() ]|$))"; }).join("|");
```

**Comment by pleerock** [comment]
Can you provide a working example on https://regexr.com/ ?

**Comment by pleerock** [comment]
Closing as no answer from reporter.

**Comment by shengxq** [comment]
https://regexr.com/3n2ne

**Comment by yudaming** [comment]
mssql 
CREATE TABLE [dbo].[history_bug_info]
(
[id] [int] NOT NULL IDENTITY(244, 1),
[bug_id] [int] NOT NULL,
[title] [nvarchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[customer] [nvarchar] (255) COLLATE Chinese_PRC_CI_AS NOT NULL,
[description] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NOT NULL,
[status] [tinyint] NOT NULL CONSTRAINT [DF__history_b__statu__32E0915F] DEFAULT ((0)),
[bug_type] [tinyint] NOT NULL CONSTRAINT [DF__history_b__bug_t__33D4B598] DEFAULT ((0)),
[reason] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[source] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__sourc__34C8D9D1] DEFAULT (NULL),
[register_time] [datetime2] (0) NULL CONSTRAINT [DF__history_b__regis__35BCFE0A] DEFAULT (NULL),
[register_code] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__regis__36B12243] DEFAULT (NULL),
[register] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__regis__37A5467C] DEFAULT (NULL),
[solved_time] [datetime2] (0) NULL CONSTRAINT [DF__history_b__solve__38996AB5] DEFAULT (NULL),
[developer_code] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__devel__398D8EEE] DEFAULT (NULL),
[developer] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__devel__3A81B327] DEFAULT (NULL),
[tester_code] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__teste__3B75D760] DEFAULT (NULL),
[tester] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__teste__3C69FB99] DEFAULT (NULL),
[owner_code] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__owner__3D5E1FD2] DEFAULT (NULL),
[owner] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__owner__3E52440B] DEFAULT (NULL),
[is_solved] [smallint] NOT NULL CONSTRAINT [DF__history_b__is_so__3F466844] DEFAULT ((0)),
[operate_time] [datetime2] (0) NOT NULL CONSTRAINT [DF__history_b__opera__403A8C7D] DEFAULT (getdate()),
[operator_code] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__opera__412EB0B6] DEFAULT (NULL),
[operator] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__opera__4222D4EF] DEFAULT (NULL),
[operation_type] [tinyint] NOT NULL CONSTRAINT [DF__history_b__opera__4316F928] DEFAULT ((0)),
[demand_number] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF__history_b__deman__440B1D61] DEFAULT (NULL)
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[history_bug_info] ADD CONSTRAINT [PK_history_bug_info_id] PRIMARY KEY CLUSTERED ([id]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'bug_system.history_bug_info', 'SCHEMA', N'dbo', 'TABLE', N'history_bug_info', NULL, NULL
GO
用的是中文数据库 为啥保存的时候会乱码呢

**Comment by pleerock** [comment]
okay please provide a PR for this improvement. I hope it cover all edge SQL cases.

**Comment by yudaming** [comment]
const query = bugRepository.save(bugInfo);

Why do I use sqlserver to save random code.
Mysql is normal.

**Comment by shengxq** [comment]
```
await connection.getRepository('b_测试').createQueryBuilder().insert().values([{
            I_测试编号: 1,
            C_测试名称: 'aaaa'
        }]).execute();
```
```
executing query:  INSERT INTO `b_测试`(`I_测试编号`, `C_测试名称`) VALUES (:_inserted_0_I_测试编号,:_inserted_0_C_测试名称)
PlatformTools.ts:201
query failed:  INSERT INTO `b_测试`(`I_测试编号`, `C_测试名称`) VALUES (:_inserted_0_I_测试编号,:_inserted_0_C_测试名称)
```

**Comment by shengxq** [comment]
"typeorm": "^0.1.21"

**Comment by shengxq** [comment]
typeorm/src/driver/mysql/MysqlDriver.ts

```
escapeQueryWithParameters(sql: string, parameters: ObjectLiteral, nativeParameters: ObjectLiteral): [string, any[]] {
        const escapedParameters: any[] = Object.keys(nativeParameters).map(key => nativeParameters[key]);
        if (!parameters || !Object.keys(parameters).length)
            return [sql, escapedParameters];

        const keys = Object.keys(parameters).map(parameter => "(:(\\.\\.\\.)?" + parameter + "\\b)").join("|");
        sql = sql.replace(new RegExp(keys, "g"), (key: string) => {
            let value: any;
            if (key.substr(0, 4) === ":...") {
                value = parameters[key.substr(4)];
            } else {
                value = parameters[key.substr(1)];
            }

            if (value instanceof Function) {
                return value();

            } else {
                escapedParameters.push(value);
                return "?";
            }
        }); // todo: make replace only in value statements, otherwise problems
        return [sql, escapedParameters];
    }
```

```
const keys = Object.keys(parameters).map(parameter => "(:(\\.\\.\\.)?" + parameter + "(?=[.,() ]|$))").join("|");
```

代码修改成这样就可以支持中文字段了
The code is modified so that Chinese fields can be supported.
