### ISSUE TITLE
TypeScript validate type fails on Column constructors

### ISSUE THREAD

**Issue by emilianosantucci** [typeorm/typeorm#166]
Hi guys,
I'm starting to use TypeORM on my project and have a tedious message from IDE checks.

When using _Column_ metadata with _ColumnOptions_ is (ex.  _@Column({ name: 'MY_FIELD', type: ColumnTypes.INT, length: 11 })_ ), receive check error: **Invalid number of parameters, expected 0**.

Anyway, all works correctly.

To resolve it, I've tried to change Column type definition from existing one to this:
```ts
import { ColumnOptions } from "../options/ColumnOptions";
import { ColumnType } from "../../metadata/types/ColumnTypes";

/**
 * Column decorator is used to mark a specific class property as a table column.
 * Only properties decorated with this decorator will be persisted to the database when entity be saved.
 */
export declare function Column(type?: ColumnType, options?: ColumnOptions): Function;
```

Any suggestions?
Thanks

**Comment by pleerock** [comment]
hmm thats strange, maybe some bug with your typescript version? What version are you using? Also, try to checkout [typescript-example](https://github.com/typeorm/typescript-example). It should work without any problems.

**Comment by emilianosantucci** [comment]
@pleerock my mistake, in `tsconfig.json` I had **files** sections which was not contains typeorm files. 
I have removed it and now all its fine :).

Thanks
