### ISSUE TITLE
Not able to connect to MSSQL with msnodesqlv8 driver

### ISSUE THREAD

**Issue by blablameh** [typeorm/typeorm#1660]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I was trying to connect to SQL Server 2014 using integrated windows authentication using msnodesqlv8 driver.

I have tried following but no luck in index.ts:

```ts
import {createConnection, Connection} from "typeorm";
import windowsDriver = require('mssql/msnodesqlv8');

createConnection({
    type: "mssql",
    host: "localhost",
    port: 1433,
    database: "NodeTypeOrm",
    extra: {
        driver: windowsDriver,
        trustedConnection: true
    },
    options: {
        useUTC: true,
        trustedConnection: true
    }
}).then(connection => {
    console.log('Connected');
}).catch(error => {
    console.log(error);
});
```

I also tried following code to check mssql package compatibility with msnodesqlv8 and it worked just fine

```ts
const sql = require('mssql');
const windowsDriver = require('mssql/msnodesqlv8');
const config = {
    driver: windowsDriver,
    server: 'localhost',
    port: 63667,
    database: 'NodeTypeORM',
    options: {
        trustedConnection: true,
        useUTC: true
    }
}
sql.connect(config).then((pool) => {
    console.log('cnnected');
    return pool.request().query('select firstname, lastname from Users').then(res => {
        console.log(res);
    })
}).catch(error=> console.log('cant connect\n'+error));
```

**Comment by pleerock** [comment]
it shall work the same, the only difference is that `options` must be in `extra` section.

**Comment by blablameh** [comment]
I tried your suggestion (nesting `options` in `extra` section) but still wasn't able to connect and had following error:
`ConnectionError: Login failed for user ''.`
It seems that issue is linked to following `node-mssql` issue
#https://github.com/tediousjs/node-mssql/issues/618

**Comment by nbrink91** [comment]
@blablameh Did you ever have any luck with this? I'm in the same boat. Windows authentication is a requirement unfortunately and if I cannot figure out a way to use it in TypeORM I'm going to have to shift directions.

Thanks!

**Comment by blablameh** [comment]
I was successfully able to connect to SQL Server using Windows Auth via Integrated security.
For this although,
I had to fork following two repositories using my GitHub account:
[tediousjs/tedious](https://github.com/tediousjs/tedious)
[tediousjs/node-mssql](https://github.com/tediousjs/node-mssql)

I then merged the Windows-authentication changes from this [PR ](https://github.com/tediousjs/tedious/pull/497) in the [forked repository of tedious](https://github.com/blablameh/tedious).
I then made changes to package.json in the [forked repository of node-mssql](https://github.com/blablameh/node-mssql) to refer to the forked version of tedious as a dependency 
( as "tedious": "git+RepoURL", so that the command executed during build process is "npm install git+ RepoURL").

I also removed the references to tedious's deprecated datatypes in node-mssql (which otherwise would have emitted warnings while querying the database).

(Following is what needs to be done to utilize forked mssql driver)
I then made changes to actual node project's **package.json** so that it refers to the [forked version of node-mssql](https://github.com/blablameh/node-mssql) as a dependency ( as "mssql": "git+https://github.com/blablameh/node-mssql").

I have tested the changes using all three modes:
SQL Server Authentication **via username + password keys in ORMConfig  connection details**
Windows Auth via AD **via username + password + domain keys in ORMConfig connection details**
Windows Auth via Integrated security (only domain needs to be mentioned in config per the changes from PR) **via domain keys in ORMConfig connection details**

Following are the three limitations of using this forked version of tedious :
•	the node.js server needs to be hosted on Windows (as it uses a SSPI client which uses Win32 API)
•	the node.js server needs to be started with **a user account that has access to SQL server for Windows Auth via Integrated security**
•	build machine needs to have Python 2.x installed and accessible on PATH (as the SSPI client is built on the machine using node-gyp) along with Visual C++ runtime

In my case, above were not limiting factors. I hope this helps.

**Comment by nbrink91** [comment]
@blablameh, thanks for all the great information. I'll follow those two PR's and see if anything become of them.

**Comment by KeonPaul** [comment]
Is this still the only solution?
