### ISSUE TITLE
Insert returning *

### ISSUE THREAD

**Issue by tonyxiao** [typeorm/typeorm#1663]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Often after insertion I immediately execute a select query to get the newly inserted row back from db (certain fields are db generated for example). Is it possible to do a `INSERT ... RETURNING *` query via the typesafe repo / manager methods without resorting to raw SQL?

**Comment by pleerock** [comment]
`save` method does everything for you. What is missing in `save` method that you need?

**Comment by ShadowManu** [comment]
I have a similar issue (PostgreSQL). I have an entity seizure:

```
@Entity({ name: 'seizures' })
export class Seizure {
  @PrimaryColumn('uuid') uuid: string;

  @Column('enum', { enum: SEIZURE_TYPES }) type: string;

  @Column('timestamp with time zone') ocurredAt: string;

  // Number of seconds of the seizure duration
  @Column('int') duration: number;

  @Column('text') preictalSymptoms: string;

  @Column('text') postictalSymptoms: string;

  @Column('bool') medicated: boolean;

  // Relations

  @Column() userId: number;
  @ManyToOne(type => User, user => user.seizures) user: User;
}
```

The primary column is an `uuid`, which in the migrations has a default of `uuid_generate_v4()`. So when I do `userRepository.save(seizure)` and the seizure does not provide the uuid, this is not returned in the query, as in the actually executed query being

```
INSERT INTO "seizures"("type", "ocurredAt", "duration", "preictalSymptoms", "postictalSymptoms", "medicated", "userId") VALUES ($1,$2,$3,$4,$5,$6,$7) 
```

How can I make it return the uuid (primary key)?

**Comment by tonyxiao** [comment]
@ShadowManu for your specific issue, you can use this to declare your primary key instead
```ts
@PrimaryGeneratedColumn('uuid') uuid?: string
```
Then it will actually generate `insert returning uuid`, and set the `uuid` field on your object. 

That's a bit of a one-time workaround though. The general case of not having database-generated fields being returned back after the insertion query still remains an issue. For example

```
@Column('uuid', { default: () => 'uuid_generate_v4()' })
  serial: string
```

After saving an object with the above column, `serial` property will be undefined, even though it was created in the database -> forcing another "findOneById" call to be made to get the value from db.

**Comment by ShadowManu** [comment]
> After saving an object with the above column, serial property will be undefined, even though it was created in the database -> forcing another "findOneById" call to be made to get the value from db.

Exactly. Although there is even the problem that you don't have the actual ID (it was auto-created) to make the query.

**Comment by pleerock** [comment]
ah okay, this issue is already fixed and available in `@next`. In next we are returning all values with "default" and updating original entity with values returned by database.

**Comment by avantjustus** [comment]
This still doesn't seem to work in version `0.2.7`

**Comment by edevil** [comment]
@avantjustus what doesn't work, exactly? I've just inserted a new entity, and after the insert the db generated fields (id, dates) were populated in the object I passed to insert().

**Comment by mendrik** [comment]
My `save(entities)` call doesn't populate my id columns in `0.2.7`. My current work-around in typescript is:
```
const insertEntities: <T>(entities: Partial<T>[], into: ObjectType<T>) => Promise<T[]> =
  async <T>(entities: Partial<T>[], into: ObjectType<T>) =>
    (await getRepository(into)
        .createQueryBuilder().insert().into(into)
        .values(entities).returning('*')
        .execute()
    ).generatedMaps as T[];
```

and then call it via:
```
const createdPersons: Person[] = await insertEntities(partialPersons, Person);
```

`.save(partialPersons, {reload: true}) ` doesn't work either.

**Comment by tonyxiao** [comment]
This is my approach 
```
async insertReturning(entity: Partial<T>) {
    const res = await this.createQueryBuilder()
      .insert()
      .values(entity)
      .returning('*')
      .execute()
    return this.create(res.generatedMaps[0] as DeepPartial<T>)
  }
```

@pleerock do you see any problems with it?

**Comment by alfaproject** [comment]
@edevil I believe @avantjustus stumbled upon this issue: https://github.com/typeorm/typeorm/issues/3125

@mendrik and @tonyxiao if that issue gets fixed, you probably don't need those workarounds. Feel free to subscribe to it (;

**Comment by mendrik** [comment]
I'm not 100% sure anymore, but i think my issue was eventually tracked back to using `@PrimaryColumn' instead of `@PrimaryGeneratedColumn`. The latter fixed it for me on postgres.

**Comment by alfaproject** [comment]
Yes, that's what the issue I linked is all about. (;

**Comment by dberardo-com** [comment]
is it possible to use the repository API to return an entity and not just raw stuff ?

i want to create entities using insert but i need the returned entity back and would like to avoid using save(), which does 2 queries under the hood ... is this possible ?
