### ISSUE TITLE
ManyToOne does not allow ColumnOptions

### ISSUE THREAD

**Issue by dbkaplun** [typeorm/typeorm#1669]
**Issue type:**
[x] bug report

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x] `0.1.12`

Current [ManyToOne](https://github.com/typeorm/typeorm/blob/a49ce0a5362491288bb54802349a575b01cc95fd/src/decorator/relations/ManyToOne.ts#L11) [RelationOptions](https://github.com/typeorm/typeorm/blob/a49ce0a5362491288bb54802349a575b01cc95fd/src/decorator/options/RelationOptions.ts) is inflexible for some [ColumnOptions](https://github.com/typeorm/typeorm/blob/a49ce0a5362491288bb54802349a575b01cc95fd/src/decorator/options/ColumnOptions.ts#L37-L41) like `select` or `readonly`.

Thanks for considering!

**Comment by pleerock** [comment]
What exact your need? Can you please provide real examples?

**Comment by dbkaplun** [comment]
It is hard to answer your question, as I think this is something that should be possible not just for my use case.

It is useful to provide the same functionality to FK columns as to non-FK columns where it makes sense.

Here I have a UserToken that represents a user's session. I'd like to avoid querying for the user by default whenever I get or create a token.
```ts
@Entity()
export class UserToken {
  @PrimaryColumn()
  @MinLength(userTokenMinLength)
  token: string;

  // @Column({ select: false })
  @ManyToOne(type => User)
  user: User;

  @CreateDateColumn()
  issuedAt: Date;
}
```

**Comment by pleerock** [comment]
> It is hard to answer your question,

if its hard to answer then probably its hard for such use case to be..

 > Here I have a UserToken that represents a user's session. I'd like to avoid querying for the user by default whenever I get or create a token.

user will never be selected until you join it, so select: false won't add here anything.

I'll close this issue, if you have something more concrete please let me know.
