### ISSUE TITLE
"TypeError: User is not a constructor" after add Many-To-Many decorators

### ISSUE THREAD

**Issue by 4nxiety** [typeorm/typeorm#167]
Hello,

```
@Table('project')
export class Project {

    @PrimaryGeneratedColumn()
    id: number;

    @Column('string', { name: 'name' })
    name: string;

    @Column('string', { name: 'path' })
    path: string;

    @ManyToMany(type => User, user => user.projects, {
        cascadeInsert: true,
        cascadeUpdate: true,
        cascadeRemove: true

    })
    @JoinTable()
    users: User[] = [];
}


@Table('user')
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column('string', { name: 'name' })
    name: string;

    @Column('string', { name: 'email' })
    email: string;

    @ManyToMany(type => Project, project => project.users, {
        cascadeInsert: true,
        cascadeUpdate: true,
        cascadeRemove: true

    })
    projects: Project[] = [];
}
```

And now if I try `const user = new User()` its fail with the Error.  But creating a project works.

**Comment by pleerock** [comment]
can you provide more details including error you have?

**Comment by 4nxiety** [comment]
what exactly more? I write `new User()` in my code and its comes with the error "User is not a constructor". But `new Project()` works without any problem.

**Comment by pleerock** [comment]
you are sure your error related to typeorm? Remove everything related to orm and I guess you'll have same error. I guess you are using User class before its defined.

**Comment by pleerock** [comment]
try to extract both your classes into separate files and use your construction `const user = new User()` in third file.

**Comment by 4nxiety** [comment]
I removed all related and add step by step. After adding the Many-To-Many the error comes.

**Comment by pleerock** [comment]
are your classes in separate files? Where exactly `const user = new User()` your line is?

**Comment by 4nxiety** [comment]
For testing, I tried to create the User in multiple files. Yes, the classes are in seperate files. And normally include. If not, TS would not transpile

**Comment by pleerock** [comment]
> Where exactly const user = new User() your line is?

**Comment by 4nxiety** [comment]
For an example here:

`
    async addUser(req: Request, res: Response) {
        let connection;
        try {
            let userToPersist = new User();
            userToPersist.name = req.body.name;
            userToPersist.email = req.body.email;

            connection = await DatabaseConnection.create();
            const repo = connection.getRepository(User);

            let userSameName = await repo.findOne({ name: userToPersist.name });

            if (userSameName !== undefined) {
                //respons
            }

            await repo.persist(userToPersist);
            //response
        } catch (err) {
            // response
            console.error(err);
        } finally {
            if (connection !== undefined) {
                connection.close();
            }
        }
    }
`

**Comment by pleerock** [comment]
its really unclear what problem you have. My think that is not related to orm. Try to create a git repository with your code which I can easily clone and run and I'll try to debug your app.

**Comment by 4nxiety** [comment]
I think i found the problem. But I dont really know why it doesn't work. 
I watched the created .js files and found this.

Project.js 
```
const User_1 = require("./User");
const typeorm_1 = require("typeorm");
let Project = class Project {
    constructor() {
        this.users = [];
    }
};
```

User.js
```
const _1 = require("./");
const typeorm_1 = require("typeorm");
let User = class User {
    constructor() {
        this.projects = [];
    }
};
```
after I change it in the User.js to `const _1 = require("./Project");` it works. But why? I have normally a indes.js in the models folder which export the single files.
```
export * from './Project';
export * from './User';
```

So I changed the import in User.ts to `import { Project } from './Project';` and now it works.

Greetz
