### ISSUE TITLE
New Documentation Section: Cookbook?

### ISSUE THREAD

**Issue by vados-p7e** [typeorm/typeorm#1670]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

I think it'd be good to have a cookbook section in the documentation with how to do more advanced queries for certain databases. While putting queries there is a bit of a liability (though tests could be added to back them up), I think it would have helped me today (and maybe others). 

For an example, here's **how I used to order by a `jsonb` property**:

```ts
    return this.dbConn
      .getRepository(Thing)
      .createQueryBuilder('t')
      .leftJoinAndSelect("t.creator", "creator")
      .leftJoinAndSelect("t.tags", "tags")
      .skip(skip)
      .take(take)
      .orderBy(`thing_stats->>'${statKey}'`, sortOrder)
      .getManyAndCount()
      .then(([results, totalCount]: [T[], number]) => new SearchResults(results, {paginated: true, totalCount}));
```

After updating `next` versions, that code broke (due to the addition (?) of `SELECT DISTINCT` at the top level of the request, I believe), so **what works now is**:

```ts
    return this.dbConn
      .getRepository(Thing)
      .createQueryBuilder('t')
      .leftJoinAndSelect("t.creator", "creator")
      .leftJoinAndSelect("t.tags", "tags")
      .addSelect(`t.thing_stats->>'${statKey}'`, `stat`)
      .skip(skip)
      .take(take)
      .orderBy("stat", sortOrder)
      .getManyAndCount()
      .then(([results, totalCount]: [T[], number]) => new SearchResults(results, {paginated: true, totalCount}));
```
From what I can understand the reason that the old code didn't work was because the `jsonb` column that I was ordering on isn't included in the `SELECT DISTINCT` that now happens (whereas before all the columns were selected in the top level query).

It took me a while to figure this out -- most of the time was spent feeling around where typeorm would try to replace and where it wouldn't. I think this case in particular, ordering by a `jsonb` column's member is a pretty common case for databases that support it.

**Comment by vados-p7e** [comment]
Also, when I first ran into this, I thought the issue was the aliasing not taking into account `jsonb` type

So in `createOrderByCombinedWithSelectExpression` I added:

```js
// ... other code
        var selectString = Object.keys(orderBys)
            .map(function (orderCriteria) {
            if (orderCriteria.indexOf(".") !== -1) {
                var _a = orderCriteria.split("."), aliasName = _a[0], propertyPath = _a[1];
                var alias = _this.expressionMap.findAliasByName(aliasName);
                var column = alias.metadata.findColumnWithPropertyName(propertyPath);

              // If the column type is jsonb, there are likely one or more sub properties coming
              if (column.type.includes("jsonb")) {
                var subProps = _a.slice(2);
                var path = _this.escape(parentAlias) + "." + _this.escape(aliasName + "_" + column.databaseName);

                path = path + "->>" + subProps.map(function(p) { return "'" + p + "'";}).join("->>");
                return path;
              }
```

Maybe this belongs in another ticket (and I'm not even sure how it should be done, since it's so postgres specific), but maybe the assumption of `<table>.<column>` for naming is not enough? in this case the value I wanted was `<name>.<column>->><subproperty>`.

**Comment by pleerock** [comment]
Thanks for your suggestion, but I think such topics are a bit specific and quite complex to bring them in the cookbook (btw there is a place called "FAQ" which basically the same as cookbook).

Using `skip` and `take` does too much magic for you for the cost of flexibility of the queries you can run. I would recommend you to avoid using them and implement same functionality manually if you needed with all needed custom sql applied.

**Comment by vados-p7e** [comment]
Hey @pleerock Thanks for the consideration! I'll go ahead and close this ticket :)

`skip` and `take` have been working wonderfully though, should we really be attaching `LIMIT` and `OFFSET` manually? The interesting with that request wasn't actually the `skip` and `take` but the `orderBy` (since it was using a JSON member)
