### ISSUE TITLE
Explanation on when to use getRepository(Entity), Connection#getRepository, vs EntityManager#getRepository

### ISSUE THREAD

**Issue by bschlenk** [typeorm/typeorm#1671]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Question**

In [this](https://github.com/typeorm/typeorm/blob/master/docs/working-with-repository.md) section of the documentation, it mentions 3 ways to get a repository object: `getRepository(Entity)`, `Connection#getRepository`, and `EntityManager#getRepository`. Can this also include situations where each method would be the right method to use? Or perhaps any tradeoffs of using one method over another.

**Comment by pleerock** [comment]
no, they all are same, just aliases for the same functionality. Use what is convenient for you.

**Comment by bschlenk** [comment]
Cool, thank you!

**Comment by giabeni** [comment]
So there is no difference regarding  to the number of connections that are opened in database, right?

Do these options work exactly the same in the database?

Option 1:
```
const manager = getManager();
manager.find(Methodology);
manager.find(Infrastructure);
manager.find(Safety);
```
Option 2:
```
getRepository(Methodology).find();
getRepository(Infrastructure).find();
getRepository(Safety).find();
```

Thanks!
