### ISSUE TITLE
How to wirte 'decimal(5,2)' in entity?

### ISSUE THREAD

**Issue by kaimiyang** [typeorm/typeorm#1673]
**Issue type:**

[ ] question

**Database system/driver:**

[ ] `mysql` / `mariadb`

**TypeORM version:**

[ ] `latest`

**How to wirte 'decimal(5,2)' in entity?:**

I want to set the field in the table. the field type is decimal, store like data: $123.23.

In entity, how to wirte?

**Comment by AlexMesser** [comment]
```typescript
@Column("decimal", { precision: 5, scale: 2 })
value: number;
```

**Comment by kaimiyang** [comment]
@AlexMesser thank you!
many times I write like this : 
`@Column({
    type: 'decimal',
    precision: 5,
    scale: 2,
    default: 0,
  })
`
and then `desc tablename`, result in:
`
decimal(5,2)
`

now is okey!

**Comment by rinoymjoseph** [comment]
For me below one worked..
` @Column({ name: "R1ContentWidth", type: "decimal", precision: 2, scale: 2, nullable: true })
    r1ContentWidth: number`
