### ISSUE TITLE
BaseEntity should have reload method

### ISSUE THREAD

**Issue by svicalifornia** [typeorm/typeorm#1674]
**Issue type:** Feature request
**TypeORM version:** `latest`

ActiveRecord (Rails) supports a `reload` method to fetch the latest state of the record from the database and set the ActiveRecord object's state to match:

http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-reload

This reload functionality is missing from TypeORM, and this omission forces us to jump through hoops like:

    book = await Book.findOneById(book.id)

This is especially sad when using typeorm-routing-controllers-extensions, which selects objects for us using params — we shouldn't have to add the above object selection logic back in.

Please add the `reload` method to the BaseEntity class as it behaves in Rails ActiveRecord. (Of course this will return a Promise and generally be used with `await`.)

**Comment by pleerock** [comment]
can you please provide a method signature with usages example - how you think it should look like?

**Comment by svicalifornia** [comment]
public reload(): Promise<BaseEntity> {…}

The returned Promise should resolve to a reference to the original entity, so that it can be chained to further methods:

    return (await book.reload()).currentBorrower;

**Comment by svicalifornia** [comment]
Example use cases:

* When saving a new BaseEntity object, the default values of columns not specified are not currently loaded from the database and added to the entity object, so the entity object is missing any default values. Calling `myEntity.reload()` would load any values that are missing from the entity object.
* After updating one or more records via `manager` or `queryBuilder`, if you have a reference to a BaseEntity, you can easily get its new values by calling `myEntity.reload()`.
* Currently a `manager` update is required to set a timestamp (other than create/update timestamps) to the current time. Calling `myEntity.reload()` afterward will get the actual timestamp and put it in the entity object:

    await manager.query('UPDATE project SET "submittedAt" = CURRENT_TIMESTAMP WHERE id = $1', [project.id]);
    await project.reload();

**Comment by pleerock** [comment]
okay, we can do that. Are you able to create a PR for this feature?

**Comment by svicalifornia** [comment]
Sorry, I'd like to help with that, but at the moment I don't have time to dive into the code.

**Comment by pleerock** [comment]
Then I'll left this open. If you really need it then you can do it very quickly, its very trivial feature to implement.

**Comment by svicalifornia** [comment]
Just a note that this method should mutate the original entity object in place. It should **not** simply load and return a second instance of the record.

If I knew more about how BaseEntity objects managed their internal state, then I might contribute a PR, but I haven’t had time to look into that yet.

**Comment by meel-io** [comment]
I'll give this a try, I might need some feedback from both of you

**Comment by pleerock** [comment]
Closing since its already implemented.

**Comment by svicalifornia** [comment]
Thanks!

**Comment by slavafomin** [comment]
Hey! Shouldn't we have the same functionality in EntityManager/Repository?

E.g: `freshEntity = (entityManager || repository).reload(staleEntity);`
