### ISSUE TITLE
Array type default for Postgres always shows update needed in schema:log

### ISSUE THREAD

**Issue by jdforsythe** [typeorm/typeorm#1677]
Related to #1532 
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When using an array column in Postgres, using the array literal as a string works to set the default value in the database:

```js
@Column({
  nullable: false,
  type: 'smallint',
  array: true,
  default: '{5}',
})
```

However, when running `schema:log` or `schema:sync` with the cli, it always reports that it needs to update the default value of this column:

```sh
ALTER TABLE "public"."user" ALTER COLUMN "roles" SET DEFAULT '{5}';
```

This is because the actual default value in postgres is `'{5}'::smallint[]`. In other words, the default value needs to be the literal string, wrapped in single quotes, with `::column.type[]` appended to the end.

**Comment by pleerock** [comment]
Will be published in next versions next week. Thank you very much for the contribution!
