### ISSUE TITLE
Delete & Update applies to all entities in table if criteria is undefined or empty 

### ISSUE THREAD

**Issue by alex-red** [typeorm/typeorm#1680]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Using the repository API and calling any of the following:

`await repository.delete(null)`
`await repository.delete(undefined)`
`await repository.delete([])`

Will drop the entire table.

I don't think this is the intended functionality, or if it is, the documentation should make it very clear that it will delete everything. Also may be related to #1226.

**Comment by pleerock** [comment]
Correct. Since its easy to implement, do you want to contribute?

**Comment by alex-red** [comment]
Sure, sounds good to me, I'll make a PR soon then :)

**Comment by alex-red** [comment]
Hey @pleerock some questions for you:

1) What should the return value look like in this case? Should I return an empty DeleteResult?

2) I see that the same issue occurs with repository.update, ex: `repository.update(null, { someColumn: "test" }` will update the entire table, should I apply the same checks here?

**Comment by pleerock** [comment]
> I see that the same issue occurs with repository.update, ex: repository.update(null, { someColumn: "test" } will update the entire table, should I apply the same checks here?

yes, please

> What should the return value look like in this case? Should I return an empty DeleteResult?

Probably returning empty delete result is a bad idea. Maybe its better to throw an error?

**Comment by MajidJafari** [comment]
How we can remove all entries of a table at once, now? Surely we can use `QueryBuilder`, but I'm sure `TypeORM` needs a simple way to do that, too.

**Comment by andreasblueher** [comment]
Hey @pleerock did you see this question? I can't find a way to delete all data for a specific entity either. Could you please help us?

**Comment by nebkat** [comment]
> How we can remove all entries of a table at once, now? Surely we can use QueryBuilder, but I'm sure TypeORM needs a simple way to do that, too.

`repository.delete(() => "")` should work, although it is a workaround.

**Comment by NenadJovicic** [comment]
@MajidJafari @andreasblueher you can use `repository.clear()` it will delete everything from that table

**Comment by vtgn** [comment]
> @MajidJafari @andreasblueher you can use `repository.clear()` it will delete everything from that table

clear() uses TRUNCATE and delete() uses DELETE : these are absolutely not the same functionalities with the same constraints. Plus TRUNCATE doesn't work correctly with the transactions, contrary to DELETE.

**Comment by vtgn** [comment]
> > How we can remove all entries of a table at once, now? Surely we can use QueryBuilder, but I'm sure TypeORM needs a simple way to do that, too.
> 
> `repository.delete(() => "")` should work, although it is a workaround.

This workaround is not beautiful. :/
Why not simply allow to call the delete() function without argument to delete all entries in the table? This would be the same way the find() method get all the entries.

**Comment by forrestwilkins** [comment]
@vtgn Perhaps it's for safety?

**Comment by vtgn** [comment]
> @vtgn Perhaps it's for safety?

It would be a huge error by the developer if no parameter is given by accident compared to:
 repository.delete(null)
 repository.delete(undefined)
 repository.delete([])
which are most dangerous by far.

Or else if you want even more safety, they can just create a specific method for that, for example: Repository.deleteAll().
