### ISSUE TITLE
Bulk Update with typeorm

### ISSUE THREAD

**Issue by muamichali** [typeorm/typeorm#1684]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Is is possible to perform bulk updates using typeorm? I mean use data from a different table to update my table based a JOIN. Currently, I am bumping up against the fact that an update query builder does not support inner joins

```
UPDATE TableOne
SET TableOne.TotalNumber = TableTwo.FirstNumber+TableTwo.SecondNumber
FROM TableOne JOIN TableTwo
ON TableOne.PrimaryKey = TableTwo.PrimaryKey
```

**Comment by pleerock** [comment]
no, joins are not supported by query builder, you'll need to execute raw query.
