### ISSUE TITLE
JoinColumn from JoinColum is not considered when inserting new value

### ISSUE THREAD

**Issue by zenoxs** [typeorm/typeorm#1685]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x ] `sqlite`
[ ] `sqljs`
[x ] `websql`

**TypeORM version:**

[x] `latest`
[x ] `@next`
[ ] `0.x.x` (or put your version here)

**Problem:**
I get `query failed:  INSERT INTO "mois_intervenant"("MOINoMois", "INTNom") VALUES ($1,$2) -- PARAMETERS: [2,"bobs"]` and excepted `INSERT INTO "mois_intervenant"("MOINoAnnee","MOINoMois", "INTNom") VALUES ($1,$2,$3) -- PARAMETERS: [2018, 2,"bobs"]`.

TypeORM is not able to retrieve a PK from a JoinColum that is generated also by JoinColum. In my example i have a Entity `Annee`  (mean year in english), `Mois` (month) wish retrieve by a JoinColumn the column `MOINoAnnee`. So `Mois` is characterised by the pair (  `MOINoAnnee`, `MOINoMois`). 
I also have an Entity `Intervenant` (user) and the Entity `MoisIntervenant` wish retrieve by a JoinColumn the pair (  `MOINoAnnee`, `MOINoMois`) from `Mois` and retrieve `INTNom` from `Intervenant`.
Currently TypeORM will not retrieve the `MOINoAnnee`.

**Steps to reproduce or a small repository showing the problem:**
Here my code :

**index.ts**
``` ts
createConnection({
    type: "websql",
    database: "test",
    version: "1",
    description: "test database",
    size: 2 * 1024 * 1024,
    entities: [
        Annee,
        Intervenant,
        Mois,
        MoisIntervenant
    ],
    logging: true,
    synchronize: true
}).then(async connection => {

    const annee = new Annee();
    annee.MOINoAnnee = 2018;
    await connection.manager.save(annee);

    const mois = new Mois();
    mois.annee = Promise.resolve(annee);
    mois.MOINoMois = 2;
    await connection.manager.save(mois);

    const intervenant = new Intervenant();
    intervenant.INTNom = "bobs";
    intervenant.INTNomFamille = "smith";
    intervenant.INTPrenom = "bob";
    await connection.manager.save(intervenant);

    const moisIntervenant = new MoisIntervenant();
    moisIntervenant.intervenant = Promise.resolve(intervenant);
    moisIntervenant.mois = Promise.resolve(mois);
    await connection.manager.save(moisIntervenant);


}).catch(error => console.log("Error: ", error));
```
**annee.ts**
``` ts
@Entity()
export class Annee {

  @PrimaryColumn()
  public MOINoAnnee: number;

  @OneToMany(type => Mois, mois => mois.annee)
  public mois: Promise<Mois[]>;
}
``` 

**intervenant.ts**
``` ts
@Entity()
export class Intervenant{

  @PrimaryColumn()
  public INTNom: string;

  @Column()
  public INTPrenom: string;

  @Column()
  public INTNomFamille: string;

  @Column({nullable:true})
  public PAYSCode: string;

  @OneToMany(type => MoisIntervenant, moisIntervenant => moisIntervenant.intervenant)
  public moisIntervenant: Promise<MoisIntervenant[]>;
}

``` 

**mois.ts**
``` ts
@Entity()
export class Mois {

  @PrimaryColumn()
  public MOINoAnnee: number;

  @PrimaryColumn()
  public MOINoMois: number;

  @ManyToOne(type => Annee, annee => annee.mois)
  @JoinColumn({name: "MOINoAnnee"})
  public annee: Promise<Annee>;

  @OneToMany(type => MoisIntervenant, moisIntervenant => moisIntervenant.mois)
  public moisIntervenant: Promise<MoisIntervenant[]>;

}
``` 

**mois-intervenant.ts**
``` ts
@Entity()
export class MoisIntervenant  {

  @PrimaryColumn()
  public MOINoMois: number;

  @PrimaryColumn()
  public MOINoAnnee: number;

  @PrimaryColumn()
  public INTNom: string;

  @ManyToOne(type => Mois, mois => mois.moisIntervenant)
  @JoinColumn([
    {name: "MOINoAnnee", referencedColumnName: "MOINoAnnee"},
    {name: "MOINoMois", referencedColumnName: "MOINoMois"}
  ])
  public mois: Promise<Mois>;

  @ManyToOne(type => Intervenant, intervenant => intervenant.moisIntervenant)
  @JoinColumn({name: "INTNom", referencedColumnName: "INTNom"})
  public intervenant: Promise<Intervenant>;

}
``` 
EDIT: I think that the Entity `Intervenant` has no influence for the issue.

Thank you for your support, you're currently the best ORM for typescript but this is blocking issue for my project :s.

Best regards.

**Comment by pleerock** [comment]
please create a PR with a failing test with reproduction of the problem (please do not use non-english names and don't use lazy relations).

**Comment by zenoxs** [comment]
Done 👍

**Comment by pleerock** [comment]
Please upgrade to `next` (npm i typeorm@next) I just merged your test into `next` branch and it passes.
