### ISSUE TITLE
Postgresql: Migration generate won't add indices to existing tables

### ISSUE THREAD

**Issue by ProTip** [typeorm/typeorm#1687]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

If I generate a migration on an empty database it will create the SQL commands for all the indices. However if I run generate on a database with the tables already created it will not generate the commands to generate the databases.

**Comment by ProTip** [comment]
I'm still digging into this, but the schema builder appears to only create table indices inside ```createCompositeIndices```. At first I thought it was just miss-named, however it does appear to only create indices with 2 or more columns!

https://github.com/typeorm/typeorm/blob/next/src/schema-builder/RdbmsSchemaBuilder.ts#L429

If I flip that to ```> 0``` it will generate the same create index statements as if the table were first being created...

**Comment by pleerock** [comment]
It does it in separate block, inside changeColumn method. what @next version are you using?

**Comment by ProTip** [comment]
I'm currently using ```0.2.0-alpha.24```.

It appears that the ```changeColumn``` method on the postgresql query runner does not call ```createIndexSql```. ```addColumn``` and ```dropColumn``` do call this.

**Comment by pleerock** [comment]
adding @AlexMesser

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.27`. You can try it via `npm i typeorm@next`.
