### ISSUE TITLE
Using TypeORM with SQLite and Ionic2

### ISSUE THREAD

**Issue by dalezak** [typeorm/typeorm#169]
I'm struggling to get [TypeORM](https://github.com/typeorm/typeorm/) working with [Ionic2](http://ionicframework.com/docs/v2), getting `DriverPackageNotInstalledError` when trying to `createConnection` using `sqlite`.

```
let options: ConnectionOptions = {
    driver: {
      type: "sqlite",
      storage: "temp/sqlitedb.db"
    },
    logging: {
      logQueries: true,
      logSchemaCreation: true,
      logFailedQueryError: true,
      logOnlyFailedQueries: true
    },
    autoSchemaSync: true,
    entities: [ Post ]
};
createConnection(options)
  .then((connection) => {
    console.log(`Connected Created ${connection}`);
  })
  .catch((error) => {
    console.error(`Connection Error ${JSON.stringify(error)}`);
  });
});
```

```
DriverPackageNotInstalledError
SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
```

Both the `cordova-sqlite-storage` and `sqlite3` modules have been included in my `package.json`.

I've also tried to use the [ionic-orm](https://github.com/BradyLiles/ionic-orm) but no luck on that fork either.

Any ideas?

**Comment by pleerock** [comment]
> Both the cordova-sqlite-storage and sqlite3 modules have been included in my package.json.

You have them in package.json, but are they installed and present in your `node_modules`? You should not have this error if your module is installed.

> I've also tried to use the ionic-orm but no luck on that fork either.

Unfortunately author of that fork temporary stopped working on it... But that looked promising. I hope someone like you will contribute in this direction.

**Comment by dalezak** [comment]
Thanks for the reply @pleerock. 

I removed the `node_modules` directory`, did a fresh `npm install`, but still getting `SQLite package has not been found installed. Try to install it: npm install sqlite3 --save`.

```
├── @angular/common@2.1.1
├── @angular/compiler@2.1.1
├── @angular/compiler-cli@2.1.1
├── @angular/core@2.1.1
├── @angular/forms@2.1.1
├── @angular/http@2.1.1
├── @angular/platform-browser@2.1.1
├── @angular/platform-browser-dynamic@2.1.1
├── @angular/platform-server@2.1.1
├── @ionic/app-scripts@0.0.47-201612091817
├── @ionic/storage@1.1.7
├── cordova-sqlite-storage@1.5.1
├── ionic-angular@2.0.0-rc.3
├── ionic-native@2.2.11
├── ionicons@3.0.0
├── moment@2.17.1
├── ng2-lazyload-image@2.2.2
├── reflect-metadata@0.1.9
├── rxjs@5.0.0-beta.12
├── sqlite3@3.1.8
├── typeorm@0.0.6
├── typescript@2.1.4
└── zone.js@0.6.26
```

![sqlite3](https://cloud.githubusercontent.com/assets/91811/21620030/fdf58f9c-d1b7-11e6-98a3-37252a77da67.png)

**Comment by dalezak** [comment]
Noticed `DriverPackageNotInstalledError` is being thrown at https://github.com/typeorm/typeorm/blob/ad009bb1dffe4d8adad07252334dd95d026967b8/src/driver/sqlite/SqliteDriver.ts#L271.

If I call `PlatformTools.load("sqlite3")` directly, I get `Cannot find module "."`, does this provide any insight into my issue?

```
let sqlite3 = PlatformTools.load("sqlite3").verbose();
```
```
Error: Cannot find module "."
```

**Comment by dalezak** [comment]
@pleerock I created a new Ionic2 project using `2.0.0-rc.4` to help diagnose the problem but still the same issue.
```
ionic start typeorm_test blank --v2 --ts
cd typeorm_test
```
```
npm install typeorm --save
```
```
npm install reflect-metadata --save
```
```
npm install sqlite3 --save
```
```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';

import 'reflect-metadata';
import * as sqlite3 from 'sqlite3';
import { createConnection, Connection, ConnectionOptions } from "typeorm";

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  constructor(public platform:Platform) {
  }

  ionViewWillEnter() {
    console.log("Home ionViewWillEnter");
    this.platform.ready().then(() => {
    let options: ConnectionOptions = {
      //entities: [ Post ],
      autoSchemaSync: true,
      driver: {
        type: "sqlite",
        storage: "temp/sqlitedb.db"
      },
      logging: {
        logQueries: true,
        logSchemaCreation: true,
        logFailedQueryError: true,
        logOnlyFailedQueries: true
      }
    };
    createConnection(options)
      .then((connection) => {
        console.log(`Connected Created ${connection}`);
      })
      .catch((error) => {
        console.error(`Connection Error ${JSON.stringify(error)}`);
      });
    });
  }
}
```
```
ionic run ios --livereload --consolelogs --serverlogs --address localhost --port 3000
```
```
SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
```

**Comment by pleerock** [comment]
I havent work with ionic and dont know how it works inside. Is `require` function working fine there? Can you do `require('sqlite3')` without having any issues? If you replace `PlatformTools.load("sqlite3")` with just `require("sqlite3")` will it work in ionic?

**Comment by Luchillo** [comment]
@dalezak Why are you installing a node package aimed for Node.js?

In order to use Sqlite in ionic (be it 1 or 2), you need to install the `cordova-sqlite-storage` plugin.

Be aware that you'll not be able to use sqlite in web browsers, only in emulators or in actual device (in case you need sqlite like support in web browsers, you'll need to support the opening of the database to be Sqlite in mobile, and WebSql in browser).

**Comment by josh-m-sharpe** [comment]
I was just attempting to use typeorm in a ionic 2 project as well.

@Luchillo my use case was leveraging TypeORM's migrations. https://typeorm.github.io/migrations.html

I figured everything else would be sugar.

**Comment by Luchillo** [comment]
@josh-m-sharpe As said above, to use SQLite you'll need to install the cordova package, and acomodate for WebSQL in browser, your job will be to integrate those migrations with that plugin.

**Comment by joostlawerman** [comment]
Getting the same issue here. And @Luchillo You can run migrations in your code, the `Connection` class has a `runMigrations` method

**Comment by Luchillo** [comment]
@joostlawerman Nice to know, i have not yet messed around with that feature, as for the error, did you make sure to run it with cordova's SQLite plugin installed and using their api?, are you running on device or emulator?

**Comment by prolink007** [comment]
Also seeing the same issue. Just using Angular and not ionic.

**Comment by madCoder24** [comment]
Was there a solution found to this problem? I am currently hitting this issue with an Angular/electron project that is using Webpack for bundling.

**Comment by Luchillo** [comment]
@madCoder24 What a coincidence, i'm doing the same, though not yet using TypeOrm.

Is it a public project or privated? i would like to compare development methods if u don't mind.

**Comment by madCoder24** [comment]
@Luchillo It is currently private, but that is just personal preference and it's stored on BitBucket. I would be more than willing to share specific files with you to help debug this issue. I thought maybe it was happening because I needed to install the sqlite3 package globally. Anyways let me know what I can do to help.

**Comment by Luchillo** [comment]
I see, well i will not need any db features in my app, so i think i'll be of no help when it comes to this issue.

If you want to look at mine is this one (still dealing with the `main.js` compilation step): https://github.com/Luchillo/Electron-Webpack

**Comment by jairoalonsoarroyave** [comment]
Hi Guys , actually i am having the same issue but in this case i am using SqlLite in this case "SqlLite package has not been found…" i want to know if that issue was fixed and how to solve?

**Comment by luchillo17** [comment]
@jairoalonsoarroyave Did you run it in the browser or in an actual device? if you are indeed running an Ionic 2 app, how did you installed the SqLite plugin? did you use `ionic-native`?

@madCoder24 Did you manage to put it to work? my app ended up using Redux architecture with backup save to LocalStorage, i'm making a task scheduler with GUI.

**Comment by jairoalonsoarroyave** [comment]
@luchillo17 actually i am runing in my PC and chrome with "ionic serve" 

i used  

npm install sqlite3 --save

this is my code, but really i dont know what i can do , 


import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { TabsPage } from '../pages/tabs/tabs';
import { createConnection } from 'typeorm'
import { myTabla } from "./myTabla";
//import "reflect-metadata";

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = TabsPage;

   constructor(platform: Platform) {
 //   platform.ready().then(() => {
 console.log("IN");

      createConnection({
        driver: {
       
       type: "sqlite",
       host: "localhost",
       storage: "hapi.db"     
            },
        entities: [
          myTabla
        ],
        logging: {
          logFailedQueryError: true,
          logQueries: true,
          logSchemaCreation: true,
          logOnlyFailedQueries: true
        },        
        autoSchemaSync: true
      }).then( connection => {
      console.log("IN");
       
      }).catch((error) => {
         console.error('Error: ', error) ;  
    });
  }
}

**Comment by luchillo17** [comment]
@jairoalonsoarroyave the npm package `sqlite3` is for node, not for Ionic 2, check the Ionic 2 docs for the `ionic-native` part on sqlite, you'll notice it shows install steps and usage:
https://ionicframework.com/docs/native/sqlite/

**Comment by jairoalonsoarroyave** [comment]
@luchillo17 yes man i installed but isnot working, the same issue

**Comment by luchillo17** [comment]
Most likely is the way `ionic-native` is declared and the way TypeORM ask for it.

I have yet to analyze the TypeORM code base to see how it asks the window for SqLite, but if you notice from the link i put in the last message, the way `ionic-native` creates the database is by importing an angular 2 service.

I don't think the original TypeORM `SqLite` driver would expect either the need to import such service, nor the need to access the `cordova-sqlite` plugin directly from the `window.plugins` object.

I think most likely there'll be a need to make a new driver that searches the SqLite plugin in such places when using Ionic 2 or more general in Cordova-like projects.

**Comment by jairoalonsoarroyave** [comment]
luchillo17 , man actually i am trying to create a CRUD with ionic2  using SQLite, really there is not much examples that i can follow , do you have some links or some examples that i can use it,  i was trying to use this ORM(TypeORM ) doesnt matter if there are another way to do it.thanks

**Comment by madCoder24** [comment]
@luchillo17 I haven't had much time to dig back into this problem. No, I still haven't gotten it to work. It is kind of a frustrating issue.

**Comment by nadavten** [comment]
having same error

**Comment by luchillo17** [comment]
Ok idk if i haven't been cristal clear about this but:

TypeOrm's SqLite 3 driver doesn't work with Ionic 2's (or cordova altogether) because the way such driver access the SqLite database is different from the way (or path or whatever) the cordova plugin for SqLite makes available both the code and the database.

In order to make it work we need a new driver, it may be necessary for such driver to extend the current SqLite driver changing path for properties, or it may need to be a completely new one (idk, i haven't looked to the actual driver implementation).

So for Ionic 2 or Cordova users, don't expect it to work with the SqLite 3 driver, ask for a new driver that works in cordova.

**Comment by mobidev111** [comment]
[cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) is the underlying plugin of the mentioned ionic native wrapper. 

[cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) is very much a wrapper to trigger sqlite queries from the browser towards a native sqlite implementation in each of the platforms android, iOS & windows, see https://github.com/litehelpers/Cordova-sqlite-storage#a-quick-tour for sample code.

so the way to invoke sql queries towards the sqlite database is very similar to how typeorm today triggers the websql queries

**Comment by pleerock** [comment]
all discussion should be moved into #548

**Comment by exequielc** [comment]
same error here.

**Comment by redplane** [comment]
@luchillo17 , how was your project of electron - webpack - typeorm + sqlite ? Have you made your app work with sqlite ? I'm having the same issue as you had

**Comment by luchillo17** [comment]
@redplane I've done nothing with SqLite + TypeORM, i was doing a project with PostgresSQL, i just took a look at this because i've used SqLite in the past for Ionic.

**Comment by pleerock** [comment]
For those who don't know there is an [example electron repository](https://github.com/typeorm/electron-typescript-example).
