### ISSUE TITLE
Modifications made to relations in @BeforeInsert w/ cascadeInsert: true aren't saved to DB

### ISSUE THREAD

**Issue by bschlenk** [typeorm/typeorm#1692]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Here's a [gist](https://gist.github.com/bschlenk/bbc3b701f117b6a82c49e580fbed934e) demonstrating the issue.

I have two entities, pictures and colors. A picture can have many colors, and a color can belong to many pictures. Within a `@BeforeInsert` method on the picture, I figure out the color palette of the image and store the colors on the picture's colors field. This field is marked as `@ManyToMany` and `@JoinTable`, and has `cascadeInsert` set to true. I would expect the picture along with all the colors that were added in the `@BeforeInsert` method to be saved to the DB, but only the picture is saved.

**Comment by pleerock** [comment]
too much expensive operation. @BeforeInsert is for more simple operations. If you need to do something more you'll need to do it in a different place.

**Comment by bschlenk** [comment]
Can you explain what exactly is heavy about that operation? It only stores 5 objects in an array on the Picture record. That's all that is happening in `@BeforeInsert`. The "heavy" part comes after that method is run, when it is actually saving the Picture.

If it is totally fine to manually add those 5 colors to the picture before calling save, I don't see why it can't also be done from within `@BeforeInsert`.

**Comment by pleerock** [comment]
Expensiveness in recomputing all changed data sets (they are computed before "before listeners" are executed)

**Comment by pleerock** [comment]
Looks like discussion has ended.
