### ISSUE TITLE
Allow transaction nesting

### ISSUE THREAD

**Issue by errorx666** [typeorm/typeorm#170]
(I'm currently using the SQLite driver and I'm not sure if this is a driver-specific limitation.)

I'm writing code where a number of functions accept an `EntityManager` instance, begin a transaction, and perform operations.  Some of these functions call each other, passing the current transaction as the entityManager.

This fails, though, because whenever the innermost transaction finishes, the flag for "transaction in progress" is cleared, and the next commit or rollback throws a `TransactionNotStartedError`.

Per [the SQLite documentation](https://www.sqlite.org/lang_savepoint.html) nested transactions _are_ supported in SQLite using `SAVEPOINT`...`RELEASE` (in place of `BEGIN`...`COMMIT`).

I'm not sure what the level of effort for this would be, but nested transactions would be extremely useful to me.

**Comment by pleerock** [comment]
I don't think implementing of nesting transactions will work in the current orm design. You probably should go low-level with it if you want use it. Describe what you are trying to achieve in a simple example and maybe I can help you to achieve it without having to use nested transactions.

**Comment by dcworldwide** [comment]
@errorx666 can you not just pass an EntityManager through your api somehow to ensure all db queries are wrapped in a single transaction?

**Comment by errorx666** [comment]
@dcworldwide I could resolve this issue many ways by changing the API; I was hoping to avoid that.
More likely I will write some piece of code that does a ref count and closes the transaction when it reaches 0, C++ RAII-style.

**Comment by pleerock** [comment]
@errorx666 I think you have problems because underlying sqlite does not support connection pools. We need to implement connection pooling for sqlite by ourself. Do you want to run multiple operations on a single transaction? If yes, then you start your persist code with 

```typescript
entityManager.transaction(tranctionalEntityManager => {
  // and here call everything else who now uses your current entityManager, replace its usage with tranctionalEntityManager, maybe by passing it to them
});
```

**Comment by pleerock** [comment]
@errorx666 are you still interested in resolving of this issue?
