### ISSUE TITLE
Many to Many with association table returns odd values.

### ISSUE THREAD

**Issue by creadicted** [typeorm/typeorm#1703]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the many to many with custom columns setup. Like presented in #800 
So I set up a OneToMany -> ManyToOne + ManyToOne <- OneToMany relationship. In this example a user has access to multiple organizations and a organization has multiple users with a column of `role`

A user entity example: 
```typescript
@Entity('user')
export class UserEntity {

	@PrimaryGeneratedColumn()
	id?: number;

	@OneToMany(type => UserToOrganizationEntity, userToOrganization => userToOrganization.organization)
	organizations: OrganizationEntity[];
```

A organization entity example: 
```typescript
@Entity('organizations')
export class OrganizationEntity {

	@PrimaryGeneratedColumn()
	id?: number;

	@OneToMany(type => UserToOrganizationEntity, userToOrganization => userToOrganization.user)
	users: UserEntity[];
```

And the table that combines both: 
```typescript
@Entity('user_organization')
export class UserToOrganizationEntity {

	@PrimaryGeneratedColumn()
	id: number;

	@Column({
		type: 'enum',
		enum: [
			'owner',
			'editor',
			'viewer'
		]
	})
	role: 'owner' | 'editor' | 'viewer';

	@ManyToOne(type => UserEntity, user => user.organizations)
	user: UserEntity;

	@ManyToOne(type => OrganizationEntity, organization => organization.users)
	organization: OrganizationEntity;
}
```
I created two users and three organizations and updated the association table: 
id|   role   | user | organization
1 | owner |    1   |          1
2 | owner |    2   |          2
3 | owner |    2   |          3

Now after the setup, I tried to create queries to get all organizations of a user. Or check if a user is in a organization.  It looks like I am missing something. I created a request: 
```typescript
const entityManager = getManager(); 
const organizations: OrganizationEntity[] = await entityManager.createQueryBuilder(
OrganizationEntity, 'organization')
.leftJoinAndSelect('organization.users', 'users')
```

The result I got was fairly odd. 
I expected the following: 
```json
{
  "id": 1,
  "users": [
	{
	  "id": 1,
	  "role": "owner"
	}
  ]
},
{
  "id": 2,
  "users": [
	{
	  "id": 2,
	  "role": "owner"
	},
  ]
},
{
  "id": 3,
  "users": [
	{
	  "id": 1,
	  "role": "owner"
	}]
}
```

but got the following: 

```json
{
  "id": 1,
  "users": [
	{
	  "id": 1,
	  "role": "owner"
	}
  ]
},
{
  "id": 2,
  "users": [
	{
	  "id": 2,
	  "role": "owner"
	},
	{
	  "id": 3,
	  "role": "owner"
	}
  ]
},
{
  "id": 3,
  "users": []
}

```
Like the ids are mixed up when combining the tables. Is my setup wrong or just the request? 
Sorry for the long post.

**Comment by pleerock** [comment]
You have a mistake:

```ts
    @OneToMany(type => UserToOrganizationEntity, userToOrganization => userToOrganization.organization)
    organizations: OrganizationEntity[];
```

must be 

```ts
    @OneToMany(type => UserToOrganizationEntity, userToOrganization => userToOrganization.organization)
    organizations: UserToOrganizationEntity[]; // mistake in type
```

Another mistakes are wrong inverse side references:

```ts
    @OneToMany(type => UserToOrganizationEntity, userToOrganization => userToOrganization.organization) // inverse side must be organization (you have user)
    users: UserToOrganizationEntity[];
```

and 

```ts
    @OneToMany(type => UserToOrganizationEntity, userToOrganization => userToOrganization.user) // inverse side must be user (you have organization)
    organizations: UserToOrganizationEntity[];
```

**Comment by pleerock** [comment]
It took me an hour to debug and find your problems =)

**Comment by creadicted** [comment]
Did I screwed up the implementation? :(

**Comment by creadicted** [comment]
Thank you fro the help and I am sorry for the inconvenience! I will write a example for the docs.
