### ISSUE TITLE
Amazon redshift integration

### ISSUE THREAD

**Issue by daggett206** [typeorm/typeorm#1704]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

Has Typeorm integration with Amazon Redshift? if no, is there a workaround to use it?

**Comment by pleerock** [comment]
Im not familiar with Amazon Redshift. Is it a platform that supports mysq/postgres or other sql databases, or is it a separate database system?

**Comment by daggett206** [comment]
This is separate database system based on PostgreSQL designed for online analytic processing and business intelligence. Therefore I am able to successfully connect to Redshift using postgres driver via typeorm, but other things don't work at all. Here is small article about [diffs](https://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html).
