### ISSUE TITLE
When you do an update with an alias, alias is not in the generated SQL

### ISSUE THREAD

**Issue by swilliams-a3digital** [typeorm/typeorm#1706]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.1.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When we have an alias in create query builder, for selects it correctly adds the alias in the SQL Statement.  For updates however the alias is left out:

UpdateQueryBuilder {connection: Connection, queryRunner: undefined, expressionMap: QueryExpressionMap}
alias:"Transfer"
connection:Connection {isConnected: true, migrations: Array(0), subscribers: Array(0), …}

Generated SQL for an update:
"UPDATE `transfer` SET  ....

Here the name of the table is provided, but not the alias with the upper case T.

We created the query builder like this:
let myquery = this.dbConnection
                .getRepository(Transfer)
                .createQueryBuilder()

If we use this syntax for selects it creates a select statement with an alias with a capital T.
However on updates the alias is missing and it goes to the table name which is lowercase T.

The behavior between selects and updates should be consitent.

**Comment by pleerock** [comment]
> The behavior between selects and updates should be consitent.

only some databases support aliases in update statements, that's why they are being cut out in the update query builder.
