### ISSUE TITLE
save() doesn't return autogenerated columns

### ISSUE THREAD

**Issue by kunalgrover05** [typeorm/typeorm#1708]
Possibly similar to: https://github.com/typeorm/typeorm/issues/1151

Updated to typeorm@next and it does not return autogenerated columns from SQLLite anymore on calling save()
When the same objects are checked using list() then it loads the object with the ID.

**Comment by pleerock** [comment]
should not be possible, there are tests and they confirm this functionality works. Please provide a PR with a failing test or reproduction git repo.

**Comment by kunalgrover05** [comment]
You are right, it seems to work with a simple test. 

I am using it with an Ionic 2 app and it has an issue there. The code is exactly same for both @latest and @next but it doesn't work anymore with @next 

Could you help me find what should be the steps which can be used to debug what's wrong?

```
Observable.fromPromise(this.userRepository.save(user);
```

**Comment by pleerock** [comment]
so, you want to say that this issue occurs only with ionic + `@next` even in simplest app? adding @daniel-lang

**Comment by pleerock** [comment]
@kunalgrover05 did you find a resolution for your issue?

**Comment by kunalgrover05** [comment]
This seems to fix the bug. Thanks you for your support!
