### ISSUE TITLE
There is no mention about the "lazy" param of decorator in docs

### ISSUE THREAD

**Issue by brunobuddy** [typeorm/typeorm#1713]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ X] documentation issue

http://typeorm.io/#/eager-and-lazy-relations

Paragraph "Lazy relations"

 @ManyToMany(type => Question, question => question.categories)
    questions: Promise<Question[]>;

should be

 @ManyToMany(type => Question, question => question.categories, {lazy: true })
    questions: Promise<Question[]>;

Unlike eager relations there is no mention about the "lazy" param in options

**Comment by 19majkel94** [comment]
Lazy param is not needed in this case, when `TypeORM` sees the `Promise` prop type, it automatically turn on lazy loading, right @pleerock? 😉

**Comment by pleerock** [comment]
Correct. Issue can only present if user used typeorm with JavaScript or he did not properly configured reflect-metadata or tsconfig options.

**Comment by brunobuddy** [comment]
Ok, I will check about reflect-metadata.

FYI this is the code that NEEDED to pass the lazy param in order to work :

tank.entity.ts
`
@OneToMany(type => Batch, batch => batch.tank, {
        lazy: true
    })
    batches: Promise<Batch[]>
`
tsconfig.json
`{
    "compilerOptions": {
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es6",
        "lib": ["ES5", "ES6", "ES2015"],
        "sourceMap": true,
        "allowJs": true,
        "outDir": "./dist"
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules", "**/*.spec.ts"]
}
`
package.json dependencies
`    "dependencies": {
        "@nestjs/common": "^4.6.4",
        "@nestjs/core": "^4.6.4",
        "@nestjs/microservices": "^4.6.4",
        "@nestjs/mongoose": "^3.0.1",
        "@nestjs/testing": "^4.6.1",
        "@nestjs/typeorm": "^2.0.0",
        "@nestjs/websockets": "^4.5.8",
        "crypto-js": "^3.1.9-1",
        "dotenv": "^5.0.0",
        "json2csv": "^3.11.5",
        "jsonwebtoken": "^8.1.1",
        "redis": "^2.7.1",
        "reflect-metadata": "0.1.10",
        "rxjs": "^5.5.6",
        "shortid": "^2.2.8",
        "string.prototype.padstart": "^3.0.0",
        "typeorm": "^0.1.11",
        "typescript": "^2.6.2"
    }
,`

**Comment by pleerock** [comment]
As documentation says you need to do `import "reflect-metadata";` before everything else in your application, then you can avoid using `lazy: true` flag.
