### ISSUE TITLE
Calling procedures and fetching raise notice from procedure

### ISSUE THREAD

**Issue by harishajdarevic** [typeorm/typeorm#1714]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

Hello,

Is it possible to fetch raise notices on a NodeJS server using typeorm?

I'm calling procedure on the following way:
```

> 
> 
> projectRepo.query(`SELECT ${getSchema()}.my_procedure(${firstId},${SecondId})`)
>             .then((result: object  ) => {
>                 console.log("DONE");
>             }, (err: {}) => {
>                 console.log(err);
>             });

```

**Comment by pleerock** [comment]
Your issue is empty. Please report a new issue with content.
