### ISSUE TITLE
Proper handling of timestamps with timezone information  

### ISSUE THREAD

**Issue by chriskalmar** [typeorm/typeorm#1716]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Timestamps should not be converted by the ORM to UTC as the database is perfectly capable of handling these inputs. It should be the developers responsibility/choice how timezones and offsets are handled correctly.
I do agree that at the end of the day timestamps should be stored in UTC so that any client can later derive the correct date/time from it based on the local timezone.
This means it should be possible to send in timestamps with timezone information as well.
Right now the ORM strips away that important information.

Imagine having the app server with typeorm and the database at UTC+1.
If I want to update a timestamp (with timezone) with:
```
2018-03-07 14:00:00+05
```
I expect to see the following value stored in the database:
```
2018-03-07 10:00:00+01
```
which is basically the same as:
```
2018-03-07 09:00:00+00
```
But unfortunately I end up having an offset of 1 hour in the database due to my server's timezone:
```
2018-03-07 09:00:00+01
```
In a different timezone the deviation would be even worse.

This issue obviously has a huge impact on time-driven applications in a global market. The solution is quite simple though: Let the developer decide how to apply timezones.

btw, great module 🙌 , I appreciate the work you've put into this project @pleerock (and all the others).

**Comment by AlexMesser** [comment]
Dates behavior changed in `typeorm@0.2.0-alpha.29`. Please check it via `npm i typeorm@next`

**Comment by neumartin** [comment]
Can I configure a global session timezone with pg at driver level?
