### ISSUE TITLE
Listener not invoked when relation loaded through getter

### ISSUE THREAD

**Issue by BrettHoutz** [typeorm/typeorm#1720]
**Issue type:**

[ ] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When loading an entity's relation through a getter function, the listener `@AfterLoad` is never invoked. To demonstrate this issue, i first modified the [TypeScript example](https://github.com/typeorm/typescript-example) by adding a listener to Category.

```ts
/* src/entity/Category.ts */

@AfterLoad()
printMessage() {
    console.log("AfterLoad invoked for", this.name);
}
```

```ts
/* src/index.ts */

let post = await connection.manager.findOne(Post, {relations: ["categories"]});
console.log("Found post:", post);
```

The listener is invoked as expected:

```
AfterLoad invoked for TypeScript
AfterLoad invoked for Programming
Found post: Post {
  id: 1,
  title: 'Control flow based type analysis',
  text: 'TypeScript 2.0 implements a control flow-based type analysis for local variables and parameters.',
  categories: 
   [ Category { id: 1, name: 'TypeScript' },
     Category { id: 2, name: 'Programming' } ] }
```

Then, i changed Post to use a setter/getter for categories.

```ts
/* src/entity/Post.ts */

@ManyToMany(type => Category)
@JoinTable()
get categories() {
    return this._categories;
}
set categories(arr) {
    if(uniqBy(arr, "name").length != arr.length) throw "Duplicate categories found";
    this._categories = arr;
}
private _categories: Category[];
```

After this change, the listeners are not invoked:

```
Found post: Post {
  id: 1,
  title: 'Control flow based type analysis',
  text: 'TypeScript 2.0 implements a control flow-based type analysis for local variables and parameters.',
  _categories: 
   [ Category { id: 1, name: 'TypeScript' },
     Category { id: 2, name: 'Programming' } ] }
```

**Comment by pleerock** [comment]
This was a bug, fixed and will be released in 0.1.17
