### ISSUE TITLE
how to catch DB error which stops the application

### ISSUE THREAD

**Issue by KrishnaAnanthi** [typeorm/typeorm#1721]
Hi,

When using typeorm with express application, whenever db error occurs (Say some constraint in DB) the application just stops. How can we catch the error and send that to front end ? How to achieve this? 

Also if we want to fetch a record by id, how to get the id from url ? how to get these path params ? 
eg) api/person/21 - to fetch person with id 21

**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
> When using typeorm with express application, whenever db error occurs (Say some constraint in DB) the application just stops.

this question needs investigation on what we shall do when it happens. 

> Also if we want to fetch a record by id, how to get the id from url ? how to get these path params ? eg) api/person/21 - to fetch person with id 21

you simply get id from request, e.g. `const person = await getManager().find(Person, req.params.id)`

**Comment by Deviad** [comment]
I am experiencing kind of the same situation.
I tried this approach:
```
  @httpPut('/:id')
  public async updateUser(@request() req: express.Request, @response() res: express.Response): Promise<any> {
    try {
      const isExisting = await this.isExisting(req.params.id);
      if (isExisting) {
        return await this.userService.update(req.params.id, req.body)
          .then(async () => {
            const result = await this.userService.findOneById(req.params.id);
            res.status(200).json({ status: 'success', data: result });
          });
      }
    } catch (err) {
      res.status(400).json({ error: err.message });
    }
  }
```
The problem is that I don't have anywhere to implement a strategy in case of a status 204, when it does not find an entity.
This situation does not trigger a catch block so I cannot return the error with the error code in a json like
```
{
  "status": "error"
 " message: "Entity not found"
}
```
In order to be compliant and consistent with Jsend
https://labs.omniti.com/labs/jsend

My repo is here:

https://github.com/Deviad/virtual-life

Thank you.

**Comment by Deviad** [comment]
This is a solution that I think it's ok-ish.

```
  @httpDelete('/:id')
  public async deleteUser(@request() req: express.Request, @response() res: express.Response): Promise<any> {
    try {
      const isExisting = await this.isExisting(req.params.id);
      if (isExisting) {
        return await this.userService.deleteById(req.params.id)
          .then(() => {
              res.status(200).json({ status: 'success', data: null });
          });
      }
    } catch (err) {
      res.status(err.code).json({ status: 'error', message: err.message });
    }
  }

  private async isExisting(id) {
    return await this.userService.findOneById(id)
      .then(value => {
        if (!value) {
         throw new NoEntityFoundWithId(id);
        }
      });
  }
```
```
export class TypeORMError extends Error {
  constructor(public code: 400, public message: string, ) {
    super(message);
  }
}

export class NoEntityFoundWithId extends TypeORMError {
  constructor(id) {
    super(400, 'No Entity Found with id ' + id);
  }
}
```

If you have better ones, at the moment, let me know.

**Comment by pleerock** [comment]
you can use `findOneOrFail` method

**Comment by Deviad** [comment]
Thank you.

**Comment by Deviad** [comment]
Hello,
thank you. I found it here: https://github.com/typeorm/typeorm/pull/1222
Do you plan to change the API quite often on the way to the final release? 
I might find it handful to refactor in the end when this becomes stable. 
However I am going to create also a generic controller so I won't have to refactor everything.

**Comment by Deviad** [comment]
Well, in the end I can just set the version to this one and update it in the end.

**Comment by pleerock** [comment]
I think original question got its answer.
