### ISSUE TITLE
new feature: leftJoinAndMapCount

### ISSUE THREAD

**Issue by theigor** [typeorm/typeorm#1722]
**Issue type:**
[x] feature request

**Database system/driver:**
[x] `mysql` / `mariadb`

**TypeORM version:**
[x] `0.1.14` (or put your version here)

## Scenario

Given an entity with a `OneToMany ` relation, I almost never want to load the whole relation when I am displaying a list of these entities on the client side. For example, if I have an entity `Organization` and it has a relationship `people` defined like this

```ts
  @OneToMany(type => OrganizationUser, person => person.organization)
  @JoinColumn({ name: "organization_id", referencedColumnName: "organization_id" })
  people?: OrganizationUser[];
```

an `OrganizationUser` may have 20 fields and an `Organization` may have 1000 users.
Instead, I want to have a virtual property on my entity like `people_count` and populate _that_ most of the time.

I can do that today like so
```ts
.loadRelationCountAndMap("o.people_count", "o.people", "p")
```

But as it turns out, this makes a _separate_ db call for each relation.

```sql
executing query:  SELECT `o`.`organization_id` AS `o_organization_id`, `o`.`name` AS `o_name` FROM `organizations` `o`
executing query:  SELECT `p`.`organization_id` AS `parentId`, COUNT(*) AS `cnt` FROM `organization_users` `p` WHERE `p`.`organization_id` IN (?) GROUP BY `p`.`organization_id` -- PARAMETERS: [["2552e557-e24e-4531-a5d7-9bd1a463fe4e","a89ee8aa-bfdd-40b1-8d45-9301bd6a1d91"]]
executing query:  SELECT `d`.`organization_id` AS `parentId`, COUNT(*) AS `cnt` FROM `organization_departments` `d` WHERE `d`.`organization_id` IN (?) GROUP BY `d`.`organization_id` -- PARAMETERS: [["2552e557-e24e-4531-a5d7-9bd1a463fe4e","a89ee8aa-bfdd-40b1-8d45-9301bd6a1d91"]]
```

This is problematic for two reasons that I can see but possibly more:

1. 3 calls instead of 1 (or more than 3 if I have more relations).
2. At some point, this will hit a parameter limit for the relation calls (arguably, my app architecture shouldn't get me to that point, but still).

## Workaround

Because `people_count` is not a `Column`, I can't select it like this
```ts
  getRepository(Organization).createQueryBuilder("o")
    .leftJoin("o.people", "p")
    .addSelect("COUNT(p.user_id) as people_count")
```
I even tried tricking it with `COUNT(p.user_id) as o_people_count`.

So the only way you can really do something like this _today_, that I've found, is to do a raw query and then cast it to my entity class.

## Proposal

Add `leftJoinAndMapCount` to the query builder. It can have the same signature as `leftJoinAndMapOne` and could be used like this
```ts
  getRepository(Organization).createQueryBuilder("o")
    .leftJoinAndMapCount("o.people_count", OrganizationUser, "ou", "ou.organization_id = o.organization_id")
```

There are likely other ways of doing this

- `@RelationCount` decorator seems to work similarly to `loadRelationCountAndMap` and executes a separate query... but maybe it can be reworked so it doesn't and just selects a count of the relation into the property. But I saw in another ticket that it is likely to be deprecated anyway.
- try to map selected fields into virtual properties so that `.addSelect("COUNT(p.user_id) as o.people_count")` works
- etc

But my suggestion seems to be inline with typeorm convention regarding virtual entity properties.

**Comment by pleerock** [comment]
Proposal sounds like what relation count currently does and we want to deprecated and remove it because of price complexity/value it brings.

What we would like to implement is `selectAndMap`, so you can do following:

```ts
.addSelectAndMap("entity.property", "COUNT(p.user_id) as o.people_count"))
```

But we already have an issue opened for this feature request.

**Comment by theigor** [comment]
That would work. I don't see the issue you mention, but it would also be useful to be able to select the fields you actually want from a relation when you do a `leftJoinAndSelect` instead of getting _all_ fields.

I'll close this issue.

**Comment by pleerock** [comment]
duplicate of #296
