### ISSUE TITLE
TS-Node is bad with VSCode debugging

### ISSUE THREAD

**Issue by pontino** [typeorm/typeorm#1723]
The cli generated starting project didn't works with VS Code debugging (because of ts-node)

To help people, after one hour of configuration, i created a skeleton app generated from the typeorm cli and configured to work well with Visual Studio Code Debugging!
With async await constructs and the magic of Type Orm!
Make your breakpoints on TS files (only on your code), hit F5 and use TypeOrm like a charme!
https://github.com/pontino/vstorm

bye

**Comment by pleerock** [comment]
Thank you! Sure this will help to some people.
