### ISSUE TITLE
Isomprhic compilation by morphi tool

### ISSUE THREAD

**Issue by darekf77** [typeorm/typeorm#1725]
**Issue type:**

[x] feature request

Hi @pleerock,

I wrote framework [moprhi](https://github.com/darekf77/morphi ) to somehow easier
create isomorphic libraries just like yours **TypeOrm**.  

I am just thinking maybe this could be better for you to keep 
backend and frontend TypeOrm code together and compile everything 
in via morphi in the future... 

I know that I need to put some more work into my project (for example 
to generate es2015 version... ) but... I am very interesing what do you think about it :-)

Cheers.

**Comment by pleerock** [comment]
Looks very cool. The approach of calling controllers directly without having to deal with rest apis is something that any dev can dream about. However it must be implemented properly without any major drawbacks in development. I mean development process should be smooth, without any limitations applied. Also make sure to keep frontend bundles without extra backend-related code

**Comment by pleerock** [comment]
Closing as not related to typeorm. Continue your awesome idea, I would like this be something more then just library
