### ISSUE TITLE
Unable to use Paging while Joining Entities with Id of Related Entity

### ISSUE THREAD

**Issue by kjaenicke** [typeorm/typeorm#1726]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Using `.findAndCount` or `getManyAndCount` and joining on related entities that also have a property with the same name as a property defined in the source entity WHILE also using skip and take (or offset and limit).  For example:

Location.accountId
Program.accountId

The following error is returned when attempting to do so:

`The column 'Location_accountId' was specified multiple times for 'distinctAlias'`

I have a PR that addresses the issue by removing duplicate columns in the select builder.

**Comment by pleerock** [comment]
ping @kjaenicke (waiting for response in PR)

**Comment by kjaenicke** [comment]
Sorry for the delayed response on this. Turns out that the issues were related to our implementation and incorrectly setting up entity relationship. Thanks for the great project!

**Comment by kevinsproles** [comment]
For anyone else that runs into this like I did, here's how to fix. It's a case sensitivity issue.

If you look at the reporter's error:
`The column 'Location_accountId' was specified multiple times for 'distinctAlias'`

And you look at the query being executed, you'll likely notice that `Location_accountId` does appear multiple times in the query. But the 2nd time will be a different case.

For me the error was for column `foo_productId`, and it was because I had this in the entity column definition:

````typescript
@Column('int', { name: 'ProductID' })
  productId: number;
````
And I had this in the entity relation definition:

````typescript
@JoinColumn({ name: 'productId', referencedColumnName: 'productId' })
````
The **solution** was to change @Column definition name 'ProductID' to be camel case 'productId' to match the @JoinColumn.

With that change, I assume typeorm can deduplicate properly and not cause error.

Btw this error would only surface in when I was using `limit` or `maxLimit`, and invoking the joins.

**Comment by CRdeGraaf** [comment]
I had the same problem, similar solution, different cause when adding MSSQL support to our application. I happened to have named my foreign keys the same way TypeORM likes to internally name the reverse relation.

I had the error:
`'Person_insurerContracts_insurer_id' was specified multiple times for 'distinctAlias'`

Which it was, see arrows below. The naming and caps was correct. Just the odd chance that my naming choice collided with TypeORM's internal working.

Solution at bottom.

```SQL
SELECT DISTINCT "distinctAlias"."Person_id" AS "ids_Person_id"
FROM (
    SELECT "Person"."id" AS "Person_id",
      "Person"."localId" AS "Person_localId",
      "Person"."createdOn" AS "Person_createdOn",
      "Person"."firstname" AS "Person_firstname",
      "Person"."lastname" AS "Person_lastname",
      "Person"."initials" AS "Person_initials",
      ...
      "Person_addresses"."id" AS "Person_addresses_id",
      "Person_addresses"."localId" AS "Person_addresses_localId",
      "Person_addresses"."createdOn" AS "Person_addresses_createdOn",
      "Person_addresses"."streetname" AS "Person_addresses_streetname",
      ...
      "Person_insurerContracts"."id" AS "Person_insurerContracts_id",
      "Person_insurerContracts"."localId" AS "Person_insurerContracts_localId",
      "Person_insurerContracts"."createdOn" AS "Person_insurerContracts_createdOn",
      "Person_insurerContracts"."priority" AS "Person_insurerContracts_priority",
      "Person_insurerContracts"."codeClientInsurerHealthNl" AS "Person_insurerContracts_codeClientInsurerHealthNl",
      "Person_insurerContracts"."startdate" AS "Person_insurerContracts_startdate",
      "Person_insurerContracts"."stopdate" AS "Person_insurerContracts_stopdate",
      "Person_insurerContracts"."type" AS "Person_insurerContracts_type",
      "Person_insurerContracts"."source" AS "Person_insurerContracts_source",
->    "Person_insurerContracts"."insurer_id" AS "Person_insurerContracts_insurer_id",
      "Person_insurerContracts"."consumer_id" AS "Person_insurerContracts_consumer_id",
->    "Person_insurerContracts_insurer"."id" AS "Person_insurerContracts_insurer_id",
      "Person_insurerContracts_insurer"."localId" AS "Person_insurerContracts_insurer_localId",
      "Person_insurerContracts_insurer"."createdOn" AS "Person_insurerContracts_insurer_createdOn",
      "Person_insurerContracts_insurer"."tradename" AS "Person_insurerContracts_insurer_tradename",
      ...
      "Person_insurerContracts_insurer"."type" AS "Person_insurerContracts_insurer_type"
    FROM "Person" "Person"
      LEFT JOIN "Address" "Person_addresses" ON "Person_addresses"."person_id" = "Person"."id"
      LEFT JOIN "InsurerContract" "Person_insurerContracts" ON "Person_insurerContracts"."consumer_id" = "Person"."id"
      LEFT JOIN "Insurer" "Person_insurerContracts_insurer" ON "Person_insurerContracts_insurer"."id" = "Person_insurerContracts"."insurer_id"
    WHERE ("Person"."codeNlBsn" = @0)
  ) "distinctAlias"
ORDER BY "Person_id" ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
```
and InsurerContract model:
```Typescript

  @Expose()
  @Type(() => Insurer)
  @ManyToOne(
    'Insurer',
    'contracts',
    {
      onDelete: 'CASCADE',
      nullable: true,
      eager: true,
      cascade: ['insert', 'update']
    }
  )
  @JoinColumn({ name: 'insurer_id' })
  insurer?: Insurer
```

I fixed it by adding a prefix to all JoinColumns, as to not mess up my naming scheme. i chose 'fk_':
```Typescript

  @Expose()
  @Type(() => Insurer)
  @ManyToOne(
    'Insurer',
    'contracts',
    {
      onDelete: 'CASCADE',
      nullable: true,
      eager: true,
      cascade: ['insert', 'update']
    }
  )
  @JoinColumn({ name: 'fk_insurer_id' }) // <- changed name here
  insurer?: Insurer
```
