### ISSUE TITLE
create of ConnectionManager and createConnection work differently

### ISSUE THREAD

**Issue by worudso** [typeorm/typeorm#1728]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.1.16` 

**Steps to reproduce or a small repository showing the problem:**

```typescript
const connectionString = "your connection string";
(async () => {
    const c = new ConnectionManager();
    try {
        // It doesn't work!!!
        // const db = await c.create({type: "mysql", url: connectionString});

        // But it works!!!
        const db = await createConnection({type: "mysql", url: connectionString});
        console.log(await db.query(`SELECT 1`));
    } catch (ex) {
        console.error(ex);
    }
    // console.log(a);
})();
```

I think they both have to show the same behavior, but they don't.
What's the difference between `create` of ConnectionManager and `createConnection`?

**Comment by pleerock** [comment]
Just take a look on source. `create` does not return you a promise, it simply return you instance of `Connection`. Basically create is equal to `new Connection(options)` and registering this connection inside connection manager.
