### ISSUE TITLE
Query cache does not use parameter values in identifier

### ISSUE THREAD

**Issue by p3v9d5ui** [typeorm/typeorm#1730]
**Issue type:**

x question
x bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
x `sqlite`
x `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
x `0.1.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

By default, the query cache uses the query itself as a cache identifier. I'm caching a query that includes this where clause:

query.andWhere("project_id = :id", { id: projectId });

But what I've found is that the value 'projectId' is not used in the identifier, so that whenever I make this query with different projectId's, I only get the one cached entry as a result. Is this the case?

I would expect the query cache to use the fully resolved query as the identifier.

**Comment by p3v9d5ui** [comment]
It seems that `getSql()` is used as the cache ID, which is defined like this:

`getSql(): string {
        return this.connection.driver.escapeQueryWithParameters(this.getQuery(), this.getParameters())[0];
    }`

Even though the function `escapeQueryWithParameters` is used, the above only utilises the first element of that array, which is just he raw query, with no parameters applied.

To solve this for myself, I'm now creating a cache ID this way:

`let cacheId = md5(JSON.stringify(query.getQueryAndParameters()))`

I would suggest something similar.

**Comment by pleerock** [comment]
Are you able to create a PR? Im not sure if we need to md5 things

**Comment by pleerock** [comment]
Fixed in `@next`. You can try it via `npm i typeorm@next`. Now we store parameters in query as well.

**Comment by VitalyEmelyanov** [comment]
@pleerock
I experience the same problem with current version 0.2.13 when running something like this (ActiveRecord pattern):
```typescript
User.findAndCount({
  where: {name: userName},
  cache: {id: `users-cache`, milliseconds: CACHE_LIFETIME}
});
```
I'm using a temporary workaround with `id: 'users-cache' + userName`, but it's fairly ugly.

Maybe there's a same problem in other place?

**Comment by VitalyEmelyanov** [comment]
It seems, that cached query result for findAndCount does not store count param to cache
