### ISSUE TITLE
Globbing does not work for entitySchemas option

### ISSUE THREAD

**Issue by grsmvg** [typeorm/typeorm#1731]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This does **not** work:
```
entitySchemas: ['src/schemas/*.js'],
```

This does work:
```
entitySchemas: [require('./src/schemas/ProductSchema.js')],
```

Or at least that's the only way to get the schemas to automatically sync with the database.

**Comment by pleerock** [comment]
this won't be fixed since entity schemas are deprecated in newer versions - now entity schemas must be defined in a bit different way - [see this example](https://github.com/typeorm/typeorm/blob/next/sample/sample24-schemas/app.ts).

**Comment by grsmvg** [comment]
Ok! It keeps working with .js files I assume? So the only change is that you have to manually initialize them with `EntitySchema(require('path/to/schema'))` ?

**Comment by pleerock** [comment]
yes, for sure it does work for js files.
