### ISSUE TITLE
Postgresql driver does not detect/support varying without length specified

### ISSUE THREAD

**Issue by ProTip** [typeorm/typeorm#1733]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Postgresql supports ```character varying``` without specifying a length: https://www.postgresql.org/docs/9.1/static/datatype-character.html .

Unfortunately the driver does not currently support this, and does not appear to detect the difference when generating schema migrations.

If a table has varchar columns that do not specify length a column alteration command will not be generated to modify it.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.29`. You can try it via `npm i typeorm@next`.
