### ISSUE TITLE
Missing usage for findOneById/updateById in doc

### ISSUE THREAD

**Issue by billyjov** [typeorm/typeorm#1734]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.11` 

**Steps to reproduce or a small repository showing the problem:**

It's missing here [Typeorm doc](http://typeorm.io/#/find-options) usage option/ explanations for things like findOneById/updateById. It will be nice if we can add it.

**Comment by daniel-lang** [comment]
The page you linked to lists the options for the `find` method.
There is a seperate [page in the docs](http://typeorm.io/#/repository-api) that lists all the methods a repository has, including `findOneById` and `updateById`. Please let me know, if that's what you were looking for.

**Comment by billyjov** [comment]
@daniel-lang yeah it's that what i was looking for. It was a bit confuse.
