### ISSUE TITLE
setting onDelete on existing foreign key won't trigger migration

### ISSUE THREAD

**Issue by atheros** [typeorm/typeorm#1735]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Add @ManyToOne column
2. run the code to create the releation in database
3. Add { onDelete: 'CASCADE' }
4. run the code to update the releation

With logging enabled, there won't be any SQL executed to update onDelete strategy. This might be a big issue if you want to change CASCADE to SET NULL for example.

**Comment by pleerock** [comment]
thank you for the report, but this is fixed in `@next`
