### ISSUE TITLE
Milliseconds are parsed incorrectly from datetime string

### ISSUE THREAD

**Issue by andreasrueedlinger** [typeorm/typeorm#1736]
Thanks to unit testing if found the following bug: datetime strings like `"2018-03-10T16:13:08.002Z"` (milliseconds below 10) are parsed as `"2018-03-10T16:13:08.020Z"` since the follwing code adds only one leading zero:
https://github.com/typeorm/typeorm/blob/82b1410f0e4d7e481f596874fa5c303e3c50019c/src/util/DateUtils.ts#L202

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.36`. You can try it via `npm i typeorm@next`.
