### ISSUE TITLE
Cannot define SSL connection options for MongoDB in environment variables

### ISSUE THREAD

**Issue by PRo25** [typeorm/typeorm#1741]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.1.11`

**Steps to reproduce or a small repository showing the problem:**

It isn't possible to configure a connection to a MongoDB server that uses SSL by using the environment variables. I tried, without success, to use the variable "TYPEORM_DRIVER_EXTRA" by defining it in the ".env" file like this: "TYPEORM_DRIVER_EXTRA={ "ssl": true, "sslValidate": false }". But after checking the MongoDB driver code (https://github.com/typeorm/typeorm/blob/master/src/driver/mongodb/MongoDriver.ts) I noticed it doesn't use the extra property of the options object for anything so it's normal that it doesn't work.
If I configure the connection options with SSL directly in the code then it works fine.

**Comment by pleerock** [comment]
Thank you for the report. PR will be accepted for this feature request.

**Comment by osdiab** [comment]
I'm using postgres, but I believe my pr should fix this? #3409 at least for setting it to `true`.
