### ISSUE TITLE
TypeORM generates queries with too long identifiers for PostgreSQL

### ISSUE THREAD

**Issue by poolik** [typeorm/typeorm#1742]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x ] `latest` (0.1.16)
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
When you have long entity names and long property names when defining relations then TypeORM can generate too long identifiers in SQL query and silently fail to fetch the relation.

The following example repository shows the problem:
https://github.com/poolik/typescript-example/tree/broken

There I have the following entities:
```typescript
@Entity()
export class BlogPostFromIntegration {

    @ManyToOne((_type) => BlogIntegrationSource)
    @JoinColumn({ name: 'blogpost_integration_id' })
    integrationSource: BlogIntegrationSource;

    @Column()
    blogpost_integration_id: number;

}

@Entity()
export class BlogIntegrationSource {

    @PrimaryGeneratedColumn()
    blog_integration_source_id: number;

    @OneToMany((_type) => BlogPostFromIntegration, 'integrationSource')
    posts: BlogPostFromIntegration[];

}
```

When querying for `BlogPostFromIntegration` with the repository like so:
```typescript
    const fromDBPost = await connection.getRepository(BlogPostFromIntegration).findOne({
      where: {
        id: savedPost.id
      },
      relations: ['integrationSource'],
    });
```

Then `fromDBPost.integrationSource` relation will silently fail to be fetched and is undefined on the resulting object. This happens because the executed query is:
```SQL
SELECT "BlogPostFromIntegration"."id" AS "BlogPostFromIntegration_id", "BlogPostFromIntegration"."text" AS "BlogPostFromIntegration_text", 
"BlogPostFromIntegration"."blogpost_integration_id" AS "BlogPostFromIntegration_blogpost_integration_id", 
"BlogPostFromIntegration_integrationSource"."blog_integration_source_id" AS "BlogPostFromIntegration_integrationSource_blog_integration_source_id", 
"BlogPostFromIntegration_integrationSource"."url" AS "BlogPostFromIntegration_integrationSource_url"
 FROM "blog_post_from_integration" "BlogPostFromIntegration" 
LEFT JOIN "blog_integration_source" "BlogPostFromIntegration_integrationSource" 
ON "BlogPostFromIntegration_integrationSource"."blog_integration_source_id"="BlogPostFromIntegration"."blogpost_integration_id" 
WHERE "BlogPostFromIntegration"."id"=$1 -- PARAMETERS: [2]
```

where "BlogPostFromIntegration_integrationSource_blog_integration_source_id" alias is 68 characters. By default PostgreSQL supports identifiers up to 63 characters ([link](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS))
From that doc:
> longer names can be written in commands, but they will be truncated

Thus TypeORM will silently fail to fetch the relation. Ideally TypeORM should automatically detect this situation and truncate the alias to shorter length and appending the hash of the long alias for uniqueness. I looked briefly into achieving this with a PostgreSQL specific naming strategy but as far as I could see no naming strategy option controlled the alias generated when using the `relations:` find option.

At least this issue shouldn't silently fail to fetch the relation (leading the user to think that their data is incorrect and no relation exists).

**Note** this issue can be worked around by using explicit alias names with the `join` property of FindOptions (the "[extended version of relations](https://github.com/typeorm/typeorm/blob/master/docs/find-options.md)") as demonstrated here:
https://github.com/poolik/typescript-example/commit/75446c214ae729ebba5aa1b206c2c2a754316058

**Comment by pleerock** [comment]
would be great if you can test it on `@next` (npm i typeorm@next) we added logic that make aliases shorter if they are too long.

**Comment by poolik** [comment]
@pleerock on `@next` (0.2.0-alpha.28) it works, the SQL query executed is:
```SQL
SELECT "BlogPostFromIntegration"."id" AS "BlogPostFromIntegration_id", "BlogPostFromIntegration"."text" AS "BlogPostFromIntegration_text", "BlogPostFromIntegration"."blogpost_integration_id" AS "BlogPostFromIntegration_bl", "BlogPostFromIntegration_integrationSource"."blog_integration_source_id" AS "BlogPostFromIntegration_integrationSource_bl", "BlogPostFromIntegration_integrationSource"."url" AS "BlogPostFromIntegration_integrationSource_ur" FROM "blog_post_from_integration" "BlogPostFromIntegration" LEFT JOIN "blog_integration_source" "BlogPostFromIntegration_integrationSource" ON "BlogPostFromIntegration_integrationSource"."blog_integration_source_id"="BlogPostFromIntegration"."blogpost_integration_id" WHERE "BlogPostFromIntegration"."id" = $1 -- PARAMETERS: [5]
```

**Comment by pleerock** [comment]
@poolik  thanks for the confirmation, then I'll close it. Please use `next` version.

**Comment by ajxs** [comment]
This issue seems to still exist in `typeorm@0.3.0-alpha.22` when eager loading entities. It still appears to be creating alias names longer than 63 chars and silently failing in entities that are eagerly loaded.

**Comment by ErannaEru** [comment]
identifier is too long still not working after "npm i typeorm@next" 

Actually i am trying to save record using typeorm, which is internally generating alias parameter name as below, and got error identifier too long.

INSERT INTO "DNA_ACCESS"("DNASDHPDH", "DNAINSTALLATIONCOSTDISCOUNTPER", "CREATEDDATE", "TIMESTAMP", "DNAISACTIVE") 
VALUES(:i0_DNASDHPDH, :i0_DNAINSTALLATIONCOSTDISCOUNTPER,:i0_CREATEDDATE, :i0_TIMESTAMP, :i0_DNAISACTIVE) 
-- PARAMETERS: [0,0,  "2007-09-27T06:56:09.000Z","195659468",1]

**Comment by planet4us** [comment]
I have a bunch of long entity names and trying to load sub entities and their sub- entities and so forth. It turns out that 63 characters in the generated table name aliases are not unique any longer.

```
error: error: table name "Product__contents__productionCriterias_Product__contents__produ" specified more than once
    at Connection.parseE (***/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (***/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (***/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:219:5)
    at addChunk (_stream_readable.js:332:12)
    at readableAddChunk (_stream_readable.js:307:11)
    at Socket.Readable.push (_stream_readable.js:241:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:185:23) {
  name: 'error',
  length: 177,
  severity: 'ERROR',
  code: '42712',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '420',
  routine: 'checkNameSpaceConflicts'
}
```

Workaround would be to not use as long property names, nor as long entity names as I understand it?

Is there a plan for resolving this, for instance as mentioned earlier with some hash function capping the generated name to 63 characters?

**Comment by iruizmar** [comment]
This is not fixed in `0.2.29` when using `eager`. Any news on this topic?

**Comment by cprodescu** [comment]
Building up on the work-around from https://github.com/typeorm/typeorm/issues/2661#issuecomment-513523877, for us this has worked very well:

```
import { createConnection, DefaultNamingStrategy, getConnectionOptions } from 'typeorm';

class NamingStrategy extends DefaultNamingStrategy {
  eagerJoinRelationAlias(alias: string, propertyPath: string): string {
    const out = super.eagerJoinRelationAlias(alias, propertyPath);

    if (out.length > 63) {
      return out.slice(0, 30) + '___' + out.slice(-31);
    } else {
      return out;
    }
  }
}

const ormConfigOptions = await getConnectionOptions();
await createConnection({
  ...ormConfigOptions,
  namingStrategy: new NamingStrategy(),
});
```

**Comment by johncmunson** [comment]
This should not be closed. It's definitely still an issue.

**Comment by jeromeSH26** [comment]
the error is raised whatever the value of eager (false or true)
