### ISSUE TITLE
Misleading Error "RepositoryNotFoundError" when you omit "Entity" decorator from class

### ISSUE THREAD

**Issue by mcMickJuice** [typeorm/typeorm#1746]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Repo with error message - https://github.com/mcMickJuice/typeorm-entity-repo-error-message

If I forget the `Entity` decorator on a class and create a repository from that class, the error I receive is a bit misleading:

```
{ Error
    at new RepositoryNotFoundError (/Users/z002s72/dev/examples/typeorm-entity-bug/src/error/RepositoryNotFoundError.ts:12:22)
    at MongoEntityManager.EntityManager.getRepository (/Users/z002s72/dev/examples/typeorm-entity-bug/src/entity-manager/EntityManager.ts:769:19)
    at Connection.getMongoRepository (/Users/z002s72/dev/examples/typeorm-entity-bug/src/connection/Connection.ts:325:29)
    at Object.<anonymous> (/Users/z002s72/dev/examples/typeorm-entity-bug/src/index.ts:18:39)
    at step (/Users/z002s72/dev/examples/typeorm-entity-bug/src/index.ts:32:23)
    at Object.next (/Users/z002s72/dev/examples/typeorm-entity-bug/src/index.ts:13:53)
    at /Users/z002s72/dev/examples/typeorm-entity-bug/src/index.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/z002s72/dev/examples/typeorm-entity-bug/src/index.ts:3:12)
    at /Users/z002s72/dev/examples/typeorm-entity-bug/src/index.ts:8:25
  name: 'RepositoryNotFoundError',
  message: 'No repository for "User" was found. Looks like this entity is not registered in current "default" connection?' }
```

It would be great if the error returned was something along the lines of `"Entity" decorator is missing from the "User" class`.  Really, anything that points the user to them forgetting the `Entity` decorator.

Looking through the code, I noticed that the source of this could be here:

https://github.com/typeorm/typeorm/blob/master/src/metadata-args/MetadataArgsStorage.ts#L175

**Comment by pleerock** [comment]
The problem is that `"Entity" decorator is missing from the "User" class` is only one of 4-5 possible reasons. 

Error simply means that entity cannot be found.

You could have entity decorator but your entity is not specified in the connection, or your entity is not matched by glob pattern, or you simply forgot to add `export` to the entity class. 

Also decorators aren't the only source of entities in typeorm, entities can be defined in schemas, so such message can mislead users who don't use decorators.

**Comment by mcMickJuice** [comment]
Well, then i'll close this...

**Comment by pleerock** [comment]
Sorry about that and thank you for suggestion :)

**Comment by SizweP** [comment]
> The problem is that `"Entity" decorator is missing from the "User" class` is only one of 4-5 possible reasons.
> 
> Error simply means that entity cannot be found.
> 
> You could have entity decorator but your entity is not specified in the connection, or your entity is not matched by glob pattern, or you simply forgot to add `export` to the entity class.
> 
> Also decorators aren't the only source of entities in typeorm, entities can be defined in schemas, so such message can mislead users who don't use decorators.

@pleerock thanks for mentioning that its 1 of 4-5 reason. I checked my code even closer and realized that I had incorrectly named my file. its was `xxx.enity.ts` as opposed to `xxx.entity.ts`, so after renaming it...everything worked fine
