### ISSUE TITLE
PrimaryColumn combined with transformer leads to error on save

### ISSUE THREAD

**Issue by pepakriz** [typeorm/typeorm#1748]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[x] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[x] `sqlite`
[x] `sqljs`
[x] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When primary column is used together with transformer, `repository.save()` leads to error, because method `loadOperateSubjectsDatabaseEntities` is using "object-like" values for getting existing entities from db.

Check failing test: https://github.com/typeorm/typeorm/pull/1747

**Comment by pleerock** [comment]
This issue was fixed in latest `@next`.

**Comment by pepakriz** [comment]
@pleerock Thanks!
