### ISSUE TITLE
numeric/decimals (float) numbers inserted to MSSQL are rounded to int

### ISSUE THREAD

**Issue by tr0p5** [typeorm/typeorm#1752]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.0-alpha.31`

**Steps to reproduce or a small repository showing the problem:**

So I think I found the same problem that i have at this thread:
https://github.com/typeorm/typeorm/issues/352

But I don't use QueryBuilders, i use getRepository:

> getConnectionManager().get('default').getRepository(User).find();

At the issue 352 the example shows:

> createQueryBuilder("post")
   .where("post.someRealNumber = :someRealNumber", { someRealNumber: new MssqlParameter(1.234567789, "float") })
   .getMany();

So my question is how to use the MssqlParameter without using queryBuilders?
Maybe calling it on the Entity creation itself? Is there any other way?

I'm not sure how to use MssqlParameter with getRepository and only to the specific types needed of all the columns I have on each table.

The system is working for every other type I use, from date to bit(boolean). But decimals and numerics are getting rounded. Don't know why and what to do to solve it.

Any help is appreciated.

**Comment by edyrkaj** [comment]
Hi, 
what was the solution for this case? I am also interested to solve this bug.
