### ISSUE TITLE
Repository.save() always updating ManyToOne relation

### ISSUE THREAD

**Issue by kirliam** [typeorm/typeorm#1754]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an entity `Cliente` having a single ManyToOne `TipoCliente` relation like below:

```
@Entity('cliente_tabela')
export class Cliente {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    nome: string;

    @Column({name: "nomeUsual"})
    nomeFantasia: string;

    @Column({name: "fisica_juridica"})
    tipoPessoa: string;

    @ManyToOne(() => TipoCliente, tc => tc.clientes)
    @JoinColumn({name: "tipoCliente"})
    tipo: TipoCliente;

}

@Entity("tipocliente")
export class TipoCliente {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({name: "tipo"})
    descricao: string;

    @OneToMany(() => Cliente, c => c.tipo)
    clientes: Cliente[];

}

```

  No matter what change I make on my cliente entity, the save() method is always updating the `tipoCliente` column. I was expecting TypeORM updates just the changed columns. Or this is a design choice? I couldn't find it in the docs!
  Example: I change the name to "John", the generated query is:

`UPDATE cliente_tabela SET nome = ?, tipoCliente = ? WHERE id = ? -- PARAMETERS: ["John",1,4]`

  I'm just calling `await repository.save(item)`

  I also tried with the @latest version, and the behavior is the same.
  Thanks!

**Comment by pleerock** [comment]
it changes it only if you changed tipoCliente before save. Are you sure tipoCliente did not change? (If yes then it would be great to have a PR with a failing test for this issue so I can quickly fix it).

**Comment by kirliam** [comment]
Yes, I'm sure. I'll write the test and create the PR.

**Comment by pleerock** [comment]
thank you very much for failing test. Not sure when it got introduced, but fixed it in `@next`

**Comment by kirliam** [comment]
Hi @pleerock ! Thanks for fixing it.
However, there is a test case still failing. When the relation (tipoCliente) is null, typeorm thinks it has changed and updates the entity.

**Comment by pleerock** [comment]
What "test case" are you talking about?

**Comment by kirliam** [comment]
The test case is when the ManyToOne relation is null.

**Comment by pleerock** [comment]
better if you create another test case or another "it" section. Also please create a PR against `next` branch.

**Comment by kirliam** [comment]
Thansk, will create a new test case and a new PR!

**Comment by btxtiger** [comment]
Is there any update on this? I'm getting exactly the same error.
When trying to leave a nullable FK column free or set it to NULL, typeorm performs the insert, then select, and finally a mysterious update with invalid SQL code, which fails of course.
Seems like it's forbidden to set a FK column to NULL. When im passing a value for that column everything works normal.

**Comment by kirliam** [comment]
@btxtiger , as a workaround while they don't fix it, try to change typeorm code at  <node_modules>/typeorm/metadata/ColumnMetadata, line 255, to:

`var returnNulls = options && options.skipNulls === false ? false : true;`

  The current code is simply `const returnNulls = false;` and the expression above is commented out!
  This workaround also fixed a severe issue for me: #1993

**Comment by btxtiger** [comment]
thanks @kirliam 
@pleerock shouldn't this be reopened as long as the issue still exists?
Seems a bit strange to me that most people seem never to use NULL for FK columns, or in other words: optional FK columns. This is an essential feature.

**Comment by kirliam** [comment]
Hi @pleerock , this issue is partially fixed.
  When I opened it, typeOrm was always updating a ManyToOne column no matter if the value had changed or not.
  You partially fixed it on March 2018, however there is still a test case failing: when the column is null, typeOrm always execute the update. I added a test case on April.
  Thanks!
