### ISSUE TITLE
Version-Based Optimistic Concurrency Control

### ISSUE THREAD

**Issue by kirliam** [typeorm/typeorm#1755]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

  I just saw you have implemented a @VersionColumn, not sure in what version of typeOrm, but it is new for me.
  I had manually implemented such feature in my framework, but I always check the database version with the entity to update version to ensure changes are not override, a known strategy for concurrency control (I used to use with JPA).
  My question is if you have plans to implement such concurrency strategy based on version field, or I'm  missing something and maybe it has been implemented already?
  Thanks.

**Comment by pleerock** [comment]
it does already work if you use `@VersionColumn` or `@UpdateDateColumn`. Query builder has setLock](http://typeorm.io/#/select-query-builder/set-locking) method to work with version.

**Comment by kirliam** [comment]
Thank you!
