### ISSUE TITLE
How to exclude certain columns for while saving?

### ISSUE THREAD

**Issue by asingh3886** [typeorm/typeorm#1756]
**Issue type:**

[ ] question

**Database system/driver:**

[ ] `mssql`

**TypeORM version:**

[ ] `latest`

Example:

  @Column('CreatedDate')
    createdDate: string;

    @Column('ModifiedDate')
    modifiedDate: string;

**Comment by pleerock** [comment]
Please provide more details, what exactly you want to do. To exclude columns while saving you simply pass a model without those properties into the `save` method.

**Comment by pleerock** [comment]
Closing as no answer from reporter.
