### ISSUE TITLE
Synchronization bug in PostgreSQL

### ISSUE THREAD

**Issue by bartlomiej-korpus** [typeorm/typeorm#1758]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The bug occurs when we explicitly state the default schema as 
` schema: 'public'`
in ormconfig.json
This will cause TypeORM to not recognize previously created tables and try to create them every time the app starts.

Repository: https://github.com/bartlomiej-korpus/typeorm-synchronize-bug

Just run "npm start" twice to see what happens.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.29`. You can try it via `npm i typeorm@next`.
