### ISSUE TITLE
@CreateDateColumn and @UpdateDateColumn does not read back in UTC

### ISSUE THREAD

**Issue by ykim** [typeorm/typeorm#176]
I'm currently using TypeORM 0.0.5, which is persisting into a Postgres 9.6 instance. When I create an entity with CreateDateColumn and UpdateDateColumn, it persists the date as an UTC timestamp correctly. However, when I used findOneById to get the entity, the corresponding fields are being parsed in local time. I have set both storeInLocalTimezone and loadInLocalTimezone to false. Is this supposed to be the expected behavior?

**Comment by pleerock** [comment]
It looks like dates this is how underlaying drivers work. In [mysql](https://github.com/mysqljs/mysql#connection-options) there is  `timezone: "utc"` that can be used to make it work correctly. in postgres [here is issue](https://github.com/brianc/node-postgres/issues/783), somebody suggest to set machine time to timezone and problem will be resolved

**Comment by pleerock** [comment]
I made a fix, it should work now as expected. Released in `0.0.7-alpha.6`. Please let me know if something is still wrong there
