### ISSUE TITLE
Get all properties from a entity

### ISSUE THREAD

**Issue by adriankott** [typeorm/typeorm#1764]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x ] `@next`
[ ] `0.x.x` (or put your version here)

What i am trying to achive is to get all propreties from a class
For example from this class 

```
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

 @Entity("user")
export class User{

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    age: number;

 }
```

I would like to get` ["id" , "firstName", "lastName","age"]`

Realy sorry if it's a stupid question but everithing i tried to get them seems to fail 
The only method that would seem to work would be sample24-schemas I would like not to use schemas if at all posible

**Comment by vados-p7e** [comment]
You can obtain metadata from an entity if you take the class function and use the `getMetadata` method on the DB connection.

```ts
connection.getMetadata(MyEntity);
```
I find myself writing methods like:
```ts
doNonStandardDBThing<T>(cls: any, options...): Promise<T> {
  const metadata = this.db.conn.getMetadata(cls);
  return this.db.conn.query(` ... command on  ${metadata.tableName} ...`);
}
```
I think you can do better than the type `any` for `cls` (maybe to `() => T`? I think there's also a proper type you can use for constructors) but I just leave it `any` because lazy.

I'm not sure if that's an idiomatic use of `typeorm` but it works for me.

**Comment by pleerock** [comment]
as @vados-p7e answered you need to use `connection.getMetadata(User).columns`

**Comment by adriankott** [comment]
@vados-p7e @pleerock 
Thanks allot guys must have been blind missed that part of that documentation.
As a side note since I am using serverless 
`connection.getMetadata(User).columns` does not work
instead I am using 
`connection.getMetadata("User").columns`
Same thing with getting the repository
Saw this problesms while browsing the issues for solutions leaving it here if anyone else is having a similar problem

**Comment by dpmott** [comment]
In 2019, this now works for me:

`getConnection().getMetadata(Organization).ownColumns.map(column => column.propertyName)`

**Comment by dengnan123** [comment]
> In 2019, this now works for me:
> 
> `getConnection().getMetadata(Organization).ownColumns.map(column => column.propertyName)`

how can i get columns no Organization entity

**Comment by jayarjo** [comment]
Is there a way to grab metadata by table name instead of entity instance?

**Comment by stuisme** [comment]
> Is there a way to grab metadata by table name instead of entity instance?

```
entityManager.connection.entityMetadatas.find(x => x.tableName === 'table_name')
```

**Comment by djfm** [comment]
> I think you can do better than the type `any` for `cls` (maybe to `() => T`? I think there's also a proper type you can use for constructors) but I just leave it `any` because lazy (also `ObjectType<Entity>` gets used in the `typeorm` code so that would probably do it).

I think you are (or were ;)) looking for something like:

```TypeScript
type Constructor<T> = new (...args: any[]) => T;
```

(stole if from [there](https://www.simonholywell.com/post/typescript-constructor-type/))
