### ISSUE TITLE
take is ignored when adding leftJoin to SelectQueryBuilder

### ISSUE THREAD

**Issue by theigor** [typeorm/typeorm#1768]
**Issue type:**
[x] bug report

**Database system/driver:**
[x] `mysql` / `mariadb`

**TypeORM version:**
[x] `0.1.16`

**Steps to reproduce or a small repository showing the problem:**

It seems that `.take(take?:number)` gets completely ignored if you add a `leftJoin ` to a query builder.

As an example, I have a custom repository like so (in case this being a custom repo makes a difference)
```ts
@EntityRepository(SomeModel)
export class SomeModelRepository extends Repository<SomeModel> {
}
```

In there, I have a function that works fine with this query:
```ts
    let q = this.createQueryBuilder("m")
      .where(`m.somekey = '${somekey}'`)
      //.leftJoin(AnotherModel, "l", "m.somekey = l.somekey")
      .take(2)

    return q.printSql().getRawMany()
```

and outputs (from `printSql`) - notice the `LIMIT 2`
```sql
SELECT ... ` FROM `somemodel` `m` WHERE `m`.`somekey` = 'someuuid' LIMIT 2
```

If I uncomment the left join above...
```ts
    let q = this.createQueryBuilder("m")
      .where(`m.somekey = '${somekey}'`)
      .leftJoin(AnotherModel, "l", "m.somekey = l.somekey")
      .take(2)

    return q.printSql().getRawMany()
```

Then I get the following output - notice that there is **no** `LIMIT 2`  
```sql
SELECT ... FROM `somemodel` `m` LEFT JOIN `anothermodel` `l` ON `m`.`somekey` = `l`.`somekey` WHERE `m`.`somekey` = 'someuuid'
```

Thanks!

Igor

**Comment by pleerock** [comment]
correct, take and skip functionality does not work with raw data since its internal ORM functionality.

**Comment by theigor** [comment]
Ok I switched the `getRawMany` for `getMany` and `take` works again, but I am still unsure why `skip` and `take` wouldn't work for `getRawMany`? Can't it just stick a `LIMIT` and `OFFSET` on the end of the executing query? Can you expand a little? Thanks!

**Comment by theigor** [comment]
I realized you provide a `limit` and `offset` function in the API. If I understand your previous statement correctly
> its internal ORM functionality

and the comment here - https://github.com/typeorm/typeorm/blob/d46c8b0e6c0db56bb5976a4917e9f67a43715111/src/query-builder/SelectQueryBuilder.ts#L1674

It seems you're doing two queries when there's a `skip` and `take` defined. Admittedly, I am not a mysql expert and I did see a couple of posts about LIMITS and OFFSETS being slow in some situations, but I don't understand the warning about not getting the data you expect. Can you point me to a resource that explains that?

Thanks!

**Comment by pleerock** [comment]
it will bring confusion. If you need `limit` and `offset` there are separate methods for this purpose: `.limit`, `.offset`
