### ISSUE TITLE
Date columns loses zeroes in sqlite

### ISSUE THREAD

**Issue by Luke265** [typeorm/typeorm#177]
When saving column with a date or when using `@CreateDateColumn` or `@UpdateDateColumn`, it saves in this format: `2017-1-8 00:57:4` and sqlite doesn't like that (`DATETIME('2017-1-8 00:57:4')` returns null). Not sure how about other databases.

TypeORM: v0.0.6
NodeJS: v7.2.0

**Comment by pleerock** [comment]
because resolving all conflicts and removing moment by reimplementing everything could take a lot of time I made a quick fix by myself. Can you please try it in `0.0.7-alpha.10`?
Really appreciate what you did in your PR btw, sorry that its merging has delayed.

**Comment by pleerock** [comment]
I think this issue is already resolved, please check it and let me know if its not if you are still interested in this issue.
