### ISSUE TITLE
invalid reference to FROM-clause entry for table

### ISSUE THREAD

**Issue by shalomsam** [typeorm/typeorm#1771]
**Issue type:**

[ ] question
[ X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X ] `0.1.14`

**Steps to reproduce or a small repository showing the problem:**

Error - 
```
error  reason:  { QueryFailedError: invalid reference to FROM-clause entry for table "story"
    at new QueryFailedError (/Users/shalom.s/Sites/node-blogger/src/error/QueryFailedError.ts:7:9)
    at Query.callback (/Users/shalom.s/Sites/node-blogger/src/driver/postgres/PostgresQueryRunner.ts:216:26)
    at Query.handleError (/Users/shalom.s/Sites/node-blogger/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/Users/shalom.s/Sites/node-blogger/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/Users/shalom.s/Sites/node-blogger/node_modules/pg/lib/connection.js:117:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
  message: 'invalid reference to FROM-clause entry for table "story"',
  name: 'QueryFailedError',
  length: 187,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: 'Perhaps you meant to reference the table alias "Story".',
  position: '562',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3123',
  routine: 'errorMissingRTE',
  query: 'SELECT "Story"."id" AS "Story_id", "Story"."uuid" AS "Story_uuid", "Story"."title" AS "Story_title", "Story"."slug" AS "Story_slug", "Story"."isFeatured" AS "Story_isFeatured", "Story"."status" AS "Story_status", "Story"."language" AS "Story_language", "Story"."metas" AS "Story_metas", "Story"."text" AS "Story_text", "Story"."publishedAt" AS "Story_publishedAt", "Story"."createdAt" AS "Story_createdAt", "Story"."updatedAt" AS "Story_updatedAt", "Story"."authorId" AS "Story_authorId", "Story"."publisherId" AS "Story_publisherId" FROM "story" "Story" WHERE Story.relation=$1',
  parameters: [ 'user' ] }
```

Code usage: 
```ts
protected getStories(): Promise<any> {
        return this.dbConnected.then((connection) => {
            return connection.getRepository("Story").find({relation: "User"});
        });
}
```

Model:
```ts
/**
 * @readonly
 * @enum { string } - Valid Story statuses.
 */
enum States {
    published = "published",
    private = "private",
    reviewed = "reviewed",
    editing = "editing",
}

@typeOrm.Entity("story")
export class Story extends BaseModel {

    /**
     * @static
     * @property {States} - Valid story statuses.
     */
    public static states = States;

    /**
     * @property {string} html - The story content as html.
     *
     * * This field is auto-generated *
     */
    public html: string;

    /**
     * @property {string} id - Auto generated Table Id.
     *
     * * This field is auto-generated *
     */
    @typeOrm.PrimaryColumn()
    public id: string;

    /**
     * @property {string} uuid - Universaly Unique ID.
     *
     * * This field is auto-generated *
     */
    @typeOrm.Column()
    public uuid: string;

    /**
     * @property {string} title - The story title.
     */
    @typeOrm.Column()
    public title: string;

    /**
     * @property {string} slug - The story title (or a part of it) as URL slug.
     *
     * * This field is auto-generated *
     */
    @typeOrm.Column()
    public slug: string;

    /**
     * @property {boolean} isFeatured - True if this story is marked as featured.
     */
    @typeOrm.Column("boolean", { default: false })
    public isFeatured: boolean = false;

    /**
     * @property {States} status - The current status of the story.
     */
    @typeOrm.Column({ default: Story.states.editing })
    public status: States = Story.states.editing;

    /**
     * @property {string} launguage - The language used for the story content.
     */
    @typeOrm.Column({ length: 2, default: "en" })
    public language: string = "en";

    /**
     * @property {object[]} metas - An array of objects as key=>value pairs, that
     *                              are to be set as the sites meta (key=>values).
     */
    @typeOrm.Column("json", { default: [] })
    public metas: object[] = [];

    // /**
    //  * @property {string} authorId - The author of the story.
    //  */
    // @typeOrm.Column()
    // public authorId: string;

    @typeOrm.ManyToOne((type) => User)
    public author: User;

    // /**
    //  * @property {string} publisherId - The publisher of the story.
    //  */
    // @typeOrm.Column({ nullable: true })
    // public publisherId: string;

    @typeOrm.ManyToOne((type) => User)
    public publisher: User;

    /**
     * @property {string} text - The story content as plain text.
     */
    @typeOrm.Column("text")
    public text: string;

    /**
     * @property {Date} publishedAt - Time and date when the story was published.
     */
    @typeOrm.Column("date", { nullable: true })
    public publishedAt: Date;

    /**
     * @property {Date} createdAt - Time and date when the story was created.
     */
    @typeOrm.CreateDateColumn()
    public createdAt: Date;

    /**
     * @property {Date} updatedAt - Time and date when the story was updated.
     */
    @typeOrm.UpdateDateColumn()
    public updatedAt: Date;

    /**
     * Before save actions.
     *
     * The UUID is generated first and then the Id from the given UUID as a short Id.
     * The title is then converted to a URL friendly slug.
     */
    @typeOrm.BeforeInsert()
    public beforeInsert(): void {
        this.uuid = this.generateUUID();
        this.id = this.generateShortId(this.uuid);
        this.slug = this.generateUrlSlug(this.title);
    }

    /**
     * The URL friendly slug has to be re-generated to account for title updates.
     */
    @typeOrm.BeforeUpdate()
    public beforeUpdate(): void {
        this.slug = this.generateUrlSlug(this.title);
    }

    /**
     * The html is read from cache if exists. Else it is regenerated from the text
     * stored in the db and cached.
     */
    @typeOrm.AfterLoad()
    public loadHtmlFromCacheIfExists(): void {

        const storiesDir = Config.instance
            .get("storyFilePath", serverPath("/storage/stories"));

        const storyHtml = storiesDir + "/" + this.id + ".html";

        if (fs.existsSync(storyHtml)) {
            this.html = fs.readFileSync(storyHtml).toString();
        } else {
            this.html = marked(this.text);
            fs.writeFileSync(storyHtml, this.html);
        }
    }

    /**
     * The HTML cache has to be (re)generated (to account for updates).
     */
    @typeOrm.AfterInsert()
    @typeOrm.AfterUpdate()
    public createHtmlCacheFiles(): void {

        const storiesDir = Config.instance
            .get("storyFilePath", serverPath("/storage/stories"));
        const storyHtml = storiesDir + "/" + this.id + ".html";

        this.html = marked(this.text);
        fs.writeFileSync(storyHtml, this.html);
    }

    /**
     * The HTML cache files are deleted on deletion of a story.
     */
    @typeOrm.BeforeRemove()
    public deleteHtmlCache(): void {

        const storiesDir = Config.instance
            .get("storyFilePath", serverPath("/storage/stories"));

        const storyHtml = storiesDir + "/" + this.id + ".html";
        fs.unlinkSync(storyHtml);
    }
}
```

**Comment by pleerock** [comment]
What is `relation` in `{relation: "User"}` ? You must have such column if you search for strories where you have a relation column and you match it to User.

**Comment by pleerock** [comment]
Will re-open once you provide more details.

**Comment by samcole1992** [comment]
@shalomsam What did you do here? Experiencing the same thing

**Comment by samcole1992** [comment]
I've got two entities

Teacher
`@Entity()
@Unique('teacher_email_account', ['email', 'account_id'])
export class Teacher {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  email: string;

  @Column()
  account_id: string;

  @ManyToOne(() => Account)
  @JoinColumn([{ name: 'account_id', referencedColumnName: 'id' }])
  account: Account;
`

Account
`@Entity()
export class Account {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @OneToMany(
    () => Team,
    team => team.account,
  )
  teams: Team[];

  @OneToMany(
    () => Subject,
    subject => subject.account,
  )
  subjects: Subject[];

  @OneToMany(
    () => Teacher,
    teacher => teacher.account,
  )
  teachers: Teacher[];

  @OneToMany(
    () => User,
    user => user.account,
  )
  users: User[];

  @OneToMany(
    () => Schedule,
    schedule => schedule.account,
  )
  schedules: Schedule[];
}`

And this call in the service
`  public findOne(id: string): Promise<Account | undefined> {
    return this.accountsRepository.findOne(
      { id },
      { relations: ['subjects', 'teams', 'users', 'teachers'] },
    );
  }`

Fails on `teachers`, but not any of the other relations.

The error is:

`api_1       | error: error: invalid reference to FROM-clause entry for table "account"
api_1       |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:278:15)
api_1       |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
api_1       |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
api_1       |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:10:42)
api_1       |     at Socket.emit (events.js:315:20)
api_1       |     at addChunk (_stream_readable.js:295:12)
api_1       |     at readableAddChunk (_stream_readable.js:271:9)
api_1       |     at Socket.Readable.push (_stream_readable.js:212:10)
api_1       |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
api_1       |   length: 192,
api_1       |   severity: 'ERROR',
api_1       |   code: '42P01',
api_1       |   detail: undefined,
api_1       |   hint: 'Perhaps you meant to reference the table alias "Account".',
api_1       |   position: '1365',
api_1       |   internalPosition: undefined,
api_1       |   internalQuery: undefined,
api_1       |   where: undefined,
api_1       |   schema: undefined,
api_1       |   table: undefined,
api_1       |   column: undefined,
api_1       |   dataType: undefined,
api_1       |   constraint: undefined,
api_1       |   file: 'parse_relation.c',
api_1       |   line: '3299',
api_1       |   routine: 'errorMissingRTE'
api_1       | }
api_1       | [Nest] 603   - 12/09/2020, 1:24:44 AM   [ExceptionsHandler] invalid reference to FROM-clause entry for table "account" +3500ms
api_1       | QueryFailedError: invalid reference to FROM-clause entry for table "account"
api_1       |     at new QueryFailedError (/usr/src/app/node_modules/typeorm/error/QueryFailedError.js:11:28)
api_1       |     at Query.callback (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:235:38)
api_1       |     at Query.handleError (/usr/src/app/node_modules/pg/lib/query.js:128:19)
api_1       |     at Client._handleErrorMessage (/usr/src/app/node_modules/pg/lib/client.js:335:17)
api_1       |     at Connection.emit (events.js:315:20)
api_1       |     at /usr/src/app/node_modules/pg/lib/connection.js:115:12
api_1       |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:40:17)
api_1       |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:10:42)
api_1       |     at Socket.emit (events.js:315:20)
api_1       |     at addChunk (_stream_readable.js:295:12)`

And interestingly/strangely/wtfly the join looks like this
`LEFT JOIN "user" "Account__users" ON "Account__users"."account_id"="Account"."id"  LEFT JOIN "teacher" "Account__teachers" ON "Account__teachers"."account_id"=Account.account_id`

You'll see that the left join on Users joins users.account_id to Account.id, but on Teacher the join is teachers.account_id to Account.account_id

If it's a typo, then I'll happily hang my head and move on. But I can't find any

**Comment by shalomsam** [comment]
I'm not a 100% sure since its been a while. Try - 
`.findOneById(userId, {
  relations: ["role"],
})`
