### ISSUE TITLE
Unit Test for a Query Builder

### ISSUE THREAD

**Issue by BrunnerLivio** [typeorm/typeorm#1774]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

How can you add a unit test for the Query Builder? 
I'm having the following code I wanna test:

```TypeScript

@EntityRepository(Image)
export class ImageRepository extends Repository<Image> {
    async findAll(pagination: PaginationOptionsDto): Promise<[Image[], number]> {
        return await this
            .createQueryBuilder('image')
            .offset(pagination.offset)
            .limit(pagination.limit)
            .getManyAndCount();
    }
}
```

Mocking `createQueryBuilder` seems to be quite a big effort to me and does not really make sense. 
Does TypeOrm provide any feature, to do this easier?

**Comment by bartlomiej-korpus** [comment]
This method looks to me like a good candidate for integration testing rather than unit testing which would cause implementation details to leak into the test.

**Comment by aaronstaves** [comment]
Keep in mind there are already tests in typeorm for all of the QueryBuilder code, so you'd just want to mock out the specific result for what you would *expect* typeorm to return.  Probably creating an array of new Entities in this case.

Assuming you're not opposed to mocks, here's one way to do it in jest.  This example is just for reference, not sure if this will actually work for your use case.

```
    const mockRepository = jest.fn(() => ({
      createQueryBuilder: jest.fn(() => ({
        offset: jest.fn().mockReturnThis(),
        limit: jest.fn().mockReturnThis(),
        getManyAndCount: jest.fn().mockReturnValueOnce(<expected response>),
      })),
    }));
```

If you'd prefer to make sure each chained call was called with the appropriate elements, you'd make a spy for each.  Again, this is just jest.

```

    const offsetSpy = jest.fn().mockReturnThis();
    const limitSpy = jest.fn().mockReturnThis();
    const getManyAndCountSpy = jest.fn().mockReturnValueOnce(<expected response>);

    const mockRepository = jest.fn(() => ({
      createQueryBuilder: jest.fn(() => ({
        offset: offsetSpy,
        limit: limitSpy,
        getManyAndCount: getManyAndCountSpy,
      })),
    }));

    // obviously fill in with testing values
    expect(offsetSpy).toHaveBeenCalledWith(5);
    expect(offsetSpy).toHaveBeenCalledWith(10);

```

**Comment by BrunnerLivio** [comment]
@aaronstaves Thanks for the examples.
This seems simpler than I actually thought!

**Comment by acamargo2017** [comment]
@aaronstaves you would have an example of
Unit Test for a Query Builder called methods Delete

 const Query = await qb.createQueryBuilder('item')
      .delete()
      .from(ItemTable)
      .where('item_uid = :item_uid', { item_uid: Item.id })
      .execute();
