### ISSUE TITLE
leftJoinAndMapMany not working without entity to correctly map data.

### ISSUE THREAD

**Issue by chrisstpierre** [typeorm/typeorm#1775]
**Issue type:**

[ ] question
[ X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Some background. I have an `AuditTrailRecord` entity, with a OneToMany relationship with `Customer`
```ts   
@OneToMany(type => Customer, customer => customer.auditTrailRecord)
  customers: Customer[]; 
```

Then I also have a view table: customers_with_history.  I want to use this view to join customers, like in this example:
```ts
        let auditTrailRecord = await getManager()
        .createQueryBuilder(AuditTrailRecord, 'auditTrailRecord')
        .where('auditTrailRecord.id = :id', { id: id })
        .leftJoinAndMapMany('auditTrailRecord.customers', 'customer_with_history', 'customers', 'customers."auditTrailRecordId"=auditTrailRecord.id')
        .getOne();
```

unlike in other examples I've seen 'customer_with_history' here is the name of a view. I am expecting auditTrailRecord to have a key `customer` from the `customer_with_history` table, but it does not.

Resulting query is missing the `AS` query syntax that exists when joining an entity, such as
```"customers"."auditTrailRecordId" AS "customers_auditTrailRecordId" FROM "audit_trail_record" "auditTrailRecord" LEFT JOIN "customer"...```

If this difference is intended behavior of how to handle join statements with a table name instead of an entity, this should be included in the documentation.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
Aliases are not generated for non-entities because of multiple issues with them. I really recommend you to execute a separate query and map data manually - this approach is much effective.
