### ISSUE TITLE
SQL math operations apply to string ids in tree entity with closure table

### ISSUE THREAD

**Issue by PisaJan** [typeorm/typeorm#1779]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

There is a problem with string IDs in case of tree entity with closure table. 
If id is formed like "1/2" mysql transforms the value to 0.5 and therefore for example insert for new entity fails.

Entity example:
```ts
import { PrimaryColumn, TreeChildren, TreeParent, ClosureEntity} from 'typeorm';

@ClosureEntity()
export class Group {

    @PrimaryColumn({ type: 'varchar' })
    public id: string;

    @TreeChildren()
    public children: Group[];

    @TreeParent()
    public parent: Group;

}
```

**Comment by PisaJan** [comment]
Posted PR fixes just MySQL driver, maybe some other drivers would also similar fix.

**Comment by pleerock** [comment]
This was already fixed in `@next` together with other related changes. Can you use `@next` version instead (it will be released in 0.2.0 soon)?

**Comment by PisaJan** [comment]
Okey I will switch to @next for a while. Is there any date set for 0.2.0? Just for the idea. 

Thanks :)

**Comment by pleerock** [comment]
first two weeks of april

**Comment by PisaJan** [comment]
Great, thanks!
