### ISSUE TITLE
Support for insertion ignore on duplicate error

### ISSUE THREAD

**Issue by dimiork** [typeorm/typeorm#1780]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[x] `sqlite`
[x] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

There is special syntax for ignoring insertion on duplicate error in most RDBMS engines.
Here is some research about it:

> MySQL: INSERT **IGNORE** INTO test (x, y) VALUES (1,1);
> SQLite: INSERT **OR IGNORE** INTO test (x, y) VALUES (1,1);
> OracleDB: INSERT /*+ ignore_row_on_dupkey_index(test,unique-idx) */ INTO test (x, y) VALUES (1,1);
> PostgreSQL: INSERT INTO test (x, y) VALUES (1,1) **ON CONFLICT DO NOTHING**;

SQLServer is not support this feature in query request at all (You can only set parameter _ignore_dup_key_ during creation index).

So we have two patterns: exception at end of query for Postgres and between INSERT and INTO keywords for others. 
Additionally there is already implemented QueryBuilder's method "onConflict" that's why ignore syntax can be easy implemented by having changed way to generate insert sql query for all of above cases.

I'll try to provide solution in PR soon.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by benfavre** [comment]
Would also need this for Many-to-many relations and relation().of().add()

**Comment by EvanDarwin** [comment]
What's the status of this issue?

**Comment by josephbuchma** [comment]
Looks like Mysql and Postgres are supported ( #2983 )
Meanwhile, here is generic workaround I use for **sqlite** (ActiveRecord pattern):
```ts
function insertOrIgnore<
  Model extends typeof BaseEntity,
  Instance = InstanceType<Model>
>(
  model: Model,
  values: Array<{ [key in keyof Instance]: Instance[key] }>,
) {
  const q = model
    .createQueryBuilder()
    .insert()
    .into(model)
    .values(values)

  const [sql, args] = q.getQueryAndParameters()
  const nsql = sql.replace('INSERT INTO', 'INSERT OR IGNORE INTO')

  return getConnection().manager.query(nsql, args)
}
```

**Comment by imnotjames** [comment]
SQLite is now supported as well.
