### ISSUE TITLE
Cascade delete not working as expected

### ISSUE THREAD

**Issue by yusuf-khamis** [typeorm/typeorm#1782]
Here is partial entities codes
```
@ManyToOne(type => Comment, comment => comment.replies, {
    onDelete: "CASCADE"
})
parent: Comment;
```
```
@OneToMany(type => Comment, comment => comment.parent)
replies: Comment[];
```
and when i try doing this
```
await manager
    .createQueryBuilder()
    .delete()
    .from(Comment)
    .where("id = :id", { id: comment.id })
    .execute();
```
or this
`manager.remove(comment)`
i get this
`UnhandledPromiseRejectionWarning: QueryFailedError: ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails`
though i expect it run okay, is there something am doing wrong or is this a known issue, seriously need help here

**Comment by yusuf-khamis** [comment]
a fresh migration did the trick for onDelete: "CASCADE" to take effect, can't you have things like this be in the documentation, it would be really helpful in saving time

**Comment by devmuhammad** [comment]
> a fresh migration did the trick for onDelete: "CASCADE" to take effect, can't you have things like this be in the documentation, it would be really helpful in saving time

Hi, What do you mean fresh migration please. Having similar issues

**Comment by grodriguezVS** [comment]
Apparently, a fresh migration is completely deleting the DB. 
https://stackoverflow.com/questions/49363308/typeorm-cascade-delete

**Comment by gmbwa** [comment]
Adding the cascade to both sides (OneToMany and ManyToOne) works. 
If you put it on one side it will not work

**Comment by dduft** [comment]
> Adding the cascade to both sides (OneToMany and ManyToOne) works.
> If you put it on one side it will not work

`Relation WorkerTask#task and Task#workerTasks both has cascade remove set. This may lead to unexpected circular removals. Please set cascade remove only from one side of relationship.`

**Comment by Neo-Ciber94** [comment]
I think your relation is incorrect, should be:

```One``` parent comment have ```Many``` replies ```(OneToMany)```
```Many``` replies belongs to ```One``` comment ```(ManyToOne)```

**Comment by rluncasu** [comment]
> Adding the cascade to both sides (OneToMany and ManyToOne) works. If you put it on one side it will not work

This is partially correct, indeed you need to set the onCascade on the **child** not the parent.

Even if typeorm side this may not make sense, it does make sense database side: you set the `ON DELETE CASCADE` option on the foreign key constraint which is defined on the **child** table.

This is an example of the migration generated when you set onDelete: "CASCADE" on the ManyToOne side, notice the ON DELETE CASCADE option on the foreign key constraint.

Setting it to the OneToMany side actually does nothing.

```
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "asset_images" DROP CONSTRAINT "FK_8f79f4e8e3852a454ce0c50e937"`);
        await queryRunner.query(`ALTER TABLE "asset_documents" DROP CONSTRAINT "FK_8801ab6416187bbafb217a4594d"`);
        await queryRunner.query(`ALTER TABLE "asset_images" ADD CONSTRAINT "FK_8f79f4e8e3852a454ce0c50e937" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_documents" ADD CONSTRAINT "FK_8801ab6416187bbafb217a4594d" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }
```

**Comment by NicholasTavares** [comment]
It is working ok but when **soft** delete not. Is there some way to cascade soft delete?

**Comment by ar-work-acc** [comment]
> you need to set the onCascade on the **child** not the parent.

Yes, verified.
