### ISSUE TITLE
Unexpected behavior when fetching OneToOne relation

### ISSUE THREAD

**Issue by tasugo** [typeorm/typeorm#1788]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have a problem with OneToOne relationship fetching. I have the following relationship:

```ts
import { Column, Entity, JoinColumn, OneToOne, PrimaryGeneratedColumn } from 'typeorm';
import { ProviderPersonalization } from './ProviderPersonalization';

@Entity()
export class Provider {
  @PrimaryGeneratedColumn('uuid') public id: string;

  @Column() public name: string;

  @Column() public description: string;

  @OneToOne((_) => ProviderPersonalization)
  @JoinColumn()
  public personalization: ProviderPersonalization;
}
```

```ts
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class ProviderPersonalization {
  @PrimaryGeneratedColumn('uuid') public id: number;

  @Column() public logo: string;
}
```

But I can never retrieve the personalization from a provider:

```ts
const providerRepo: Repository<Provider> = getRepository(Provider);

const provider: Provider = await providerRepo.findOneById(id);
console.log(provider); // Only the provider
console.log(provider.personalization); // undefined
```

Also not working: 
```ts
const provider: Provider = await providerRepo.findOneById(id, { relations: ['personalization'] });
console.log(provider.personalization); // undefined
```

For completion - Also nope:
```ts
const provider = await providerRepo
      .createQueryBuilder('provider')
      .where({ id })
      .leftJoinAndSelect('provider.personalization', 'personalization')
      .getOne();

console.log(provider.personalization); // undefined
```

Am I missing something obvious here? Shouldn't this be straightforward?

Thanks.

---------------
edited with more examples

**Comment by pleerock** [comment]
2nd and 3rd example must work. Are you sure you have all the data needed in the database? First, check if database content all needed data, make sure relation is established between them. If data is okay, turn on logging and check what sql it generates you. It should be a proper sql.

**Comment by tasugo** [comment]
There's data in the database and the SQL is proper and working.

Take the last example, with a printSql() call:
```ts
const provider = providerRepo
      .createQueryBuilder('provider')
      .leftJoinAndSelect('provider.personalization', 'personalization')
      .printSql()
      .getOne();
```

The generated SQL works:
```sql
mysql> SELECT `provider`.`id` AS `provider_id`, `provider`.`name` AS `provider_name`, `provider`.`description` AS `provider_description`, `provider`.`personalizationId` AS `provider_personalizationId`, `personalization`.`id` AS `personalization_id`, `personalization`.`logo` AS `personalization_logo`, `personalization`.`background` AS `personalization_background` FROM `provider` `provider` LEFT JOIN `provider_personalization` `personalization` ON `personalization`.`id`=`provider`.`personalizationId` WHERE `provider`.`id`='2bf076e7-152d-4ed3-a999-d872d2bc2207'\G
*************************** 1. row ***************************
               provider_id: 2bf076e7-152d-4ed3-a999-d872d2bc2207
             provider_name: *REDACTED*
      provider_description: *REDACTED*
provider_personalizationId: c335f278-e31b-4cfe-bd63-394c4bbe9bf1
        personalization_id: c335f278-e31b-4cfe-bd63-394c4bbe9bf1
      personalization_logo: *REDACTED*
personalization_background: *REDACTED*
1 row in set (0.00 sec)
```

I think there's a bug with the relations between entities in OneToOne relationships (checked ManyToOne and this is not a problem).

**Comment by tasugo** [comment]
Created a PR with a failing spec :)

https://github.com/typeorm/typeorm/pull/1796

**Comment by pleerock** [comment]
I merged your issue into next and checked there.

Your issue in using `create` method. Create tries to "copy" objects, it does not use references. That's why when you do 

```ts
create({
          name: "Provider",
          description: "Desc",
          personalization
        })
```

before saving personalization creating object has a new personalization instance without uuid inside. And after you save personalization original object is updated with uuid, not copied object is not. Solution is to move `await personalizationRepository.save(personalization);` before create method, or don't use create method and use Object assign instead: 

```ts
Object.assign(repository.create(), {
          name: "Provider",
          description: "Desc",
          personalization
        });
```
