### ISSUE TITLE
QueryBuilder UPDATE function is inserting new record instead

### ISSUE THREAD

**Issue by futbotism** [typeorm/typeorm#1790]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[x] `0.1.0` (or put your version here)

When updating using the querybuilder a new record is being created in the DB, for example when i call the `update` function below with the given 'updatePattern', a new record is added instead of the passed record being updated
```typescript
updatePattern = {
    title: 'new title',
    id: 4 //number,
    ...otherProps
}
```

function to update a "pattern"
```typescript
async update(updatePattern: IPattern, tokenData: ITokenData) {
    return this.patternRepository
        .createQueryBuilder()
       .update(Pattern)
       .set(updatePattern)
       .where('id = :id', { id: updatePattern.id }) // have tried casting id .toString()
       .execute();
  }
```
The entity being updated
```typescript
@Entity()
export class Pattern {
  @PrimaryGeneratedColumn()
  id: string; // have tried number

  @CreateDateColumn()
  created_at: Date;

  @ManyToOne(type => User, user => user.patterns)
  user: User;

  @Column()
  title: string;
```

**Comment by pleerock** [comment]
Please provide a **minimal** reproduction git repo. Update cannot execute INSERT query in no way, Im sure you did something wrong.

**Comment by futbotism** [comment]
Hey there i resolved the issue - had the wrong type of data being fed into the id field
