### ISSUE TITLE
Mongo return nothing with use id to query

### ISSUE THREAD

**Issue by dapaer** [typeorm/typeorm#1792]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.12`

when i use find function with the options which has id field it always return nothing;
````node
return this.userRepository.find({ // return []
      where: {
        id: {
          $in: ids
        }
      }
    });
````

**Comment by Rhymmor** [comment]
@dapaer Actually, I was able to return objects by id field. Do you use ObjectID class as id?

**Comment by Rhymmor** [comment]
@pleerock how do you think, maybe finding by ids as strings can be a feature? The string can be wrapped to ObjectID instance inside.

**Comment by Rhymmor** [comment]
I can add tests checking this behavior. If they will pass then I think issue can be closed (if @dapaer won't add anything)
