### ISSUE TITLE
MSSQL Stored Procedure execution error

### ISSUE THREAD

**Issue by phanikmr** [typeorm/typeorm#1797]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

I'm calling the stored procedure by getConnection and preparing request but executing request giving 
error
code:"ECONNCLOSED"
message:"Connection is closed."
name:"ConnectionError"
stack:"ConnectionError: Connection is closed

import * as sql from 'mssql';
 const connection:any = await getConnection();
        let request = new sql.Request(connection);
        request.input("PINProjectID",info.projectId);
        request.input("DocumentName",info.fileName);
        request.input("SessionID",info.SessionId);
        request.input("ProjectFolderID", info.folderId);
        request.input("Discipline", "");
        request.input("StorageID", info.storageId);
        request.input("UploadStatus", info.UploadStatus);
        request.input("OriginalFileName", info.S3FileName);
        request.input("OriginalExtension", info.fileExtension);
        request.input("FileSize", info.fileSize);
        request.input("PickUpStatus", info.PickUpStatus);
        request.input("ProcessorID", "0");
        request.input("CreateBy", info.userId);
        request.input("PublishingOption","0");
        request.input("OrdinalNum","0");
        request.input("CreateDate",null);
        request.output("TMPDocumentUploadID", sql.Int);
        request.input("KloudlessPath",info.kloudlessPath);
        request.input("FilePublishingOption", info.FilePublishingOption);
        request.input("PublishingSource", info.PublishingSource);
        request.input("Priority", info.Priority);
        return new Promise<ProjectsFileUploadInformation>(async (resolve, reject) => {
            await request.execute("usp_PR_TMPProjectDocumentUpload_i", (err, recordSets, returnValue)=>{
                if(err){
                    this.log.error(err, "usp_PR_TMPProjectDocumentUpload_i insertion failed");
                    info.projectDocumentTMPId = 0;
                    reject(err);
                }else{
                    if(returnValue != null){
                        info.projectDocumentTMPId = returnValue;
                    }else{
                        info.projectDocumentTMPId = 0;
                    }
                    resolve(info);
                }
            });
        });

**Comment by phanikmr** [comment]
I'm calling the stored procedure by getConnection and preparing request but executing request giving 
error
code:"ECONNCLOSED"
message:"Connection is closed."
name:"ConnectionError"
stack:"ConnectionError: Connection is closed

import * as sql from 'mssql';
 const connection:any = await getConnection();
        let request = new sql.Request(connection);
        request.input("PINProjectID",info.projectId);
        request.input("DocumentName",info.fileName);
        request.input("SessionID",info.SessionId);
        request.input("ProjectFolderID", info.folderId);
        request.input("Discipline", "");
        request.input("StorageID", info.storageId);
        request.input("UploadStatus", info.UploadStatus);
        request.input("OriginalFileName", info.S3FileName);
        request.input("OriginalExtension", info.fileExtension);
        request.input("FileSize", info.fileSize);
        request.input("PickUpStatus", info.PickUpStatus);
        request.input("ProcessorID", "0");
        request.input("CreateBy", info.userId);
        request.input("PublishingOption","0");
        request.input("OrdinalNum","0");
        request.input("CreateDate",null);
        request.output("TMPDocumentUploadID", sql.Int);
        request.input("KloudlessPath",info.kloudlessPath);
        request.input("FilePublishingOption", info.FilePublishingOption);
        request.input("PublishingSource", info.PublishingSource);
        request.input("Priority", info.Priority);
        return new Promise<ProjectsFileUploadInformation>(async (resolve, reject) => {
            await request.execute("usp_PR_TMPProjectDocumentUpload_i", (err, recordSets, returnValue)=>{
                if(err){
                    this.log.error(err, "usp_PR_TMPProjectDocumentUpload_i insertion failed");
                    info.projectDocumentTMPId = 0;
                    reject(err);
                }else{
                    if(returnValue != null){
                        info.projectDocumentTMPId = returnValue;
                    }else{
                        info.projectDocumentTMPId = 0;
                    }
                    resolve(info);
                }
            });
        });

**Comment by pleerock** [comment]
Please format your code properly or issue automatically will be closed.

sql.Request does not accept TypeORM's connection object. I guess you need to pass into it `connection.driver.master` instance.
