### ISSUE TITLE
update with alias

### ISSUE THREAD

**Issue by xujif** [typeorm/typeorm#1798]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

update QueryBuilder ignore the alias parameter.
when run with 
```typescript
resp.createQueryBuilder('q')
            .update({
                aBc: 1
            })
            .where('q.aBc = 2')
            .getQuery()
```
will got 
`UPDATE "table" SET "aBc" = :_updated_aBc WHERE q.aBc = $1`

but expect sql string is:
`UPDATE "table" as q SET "aBc" = :_updated_aBc WHERE q."aBc" = $1`

**Comment by pleerock** [comment]
Im not planning to implement it since only few databases support aliases in update queries.

**Comment by xujif** [comment]
under the impression，the databases not support alias in update left value. but not in right value or where condition.

**Comment by notaphplover** [comment]
> Im not planning to implement it since only few databases support aliases in update queries.

@pleerock please is there any way you could reconsider it? Keep in mind we typeorm users are often strongly coupled to a certain db driver and not having that feature is not convenient to us. Those "few" databases are `oracle`, `mysql` and  `postgresql` which are by far the SQL mainstream ones.
