### ISSUE TITLE
mongodb@3.0.4 throw error this.databaseConnection.collection is not a function.

### ISSUE THREAD

**Issue by czd890** [typeorm/typeorm#1801]
**Issue type:**

[ ] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[*] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

mongodb@3.0.4
throw error this.databaseConnection.collection is not a function.
must be mongodb@2.* version

**Comment by pleerock** [comment]
Duplicate. Waiting for #1537 to be finished.
