### ISSUE TITLE
Type check during persist (mongodb)

### ISSUE THREAD

**Issue by thonythony** [typeorm/typeorm#1802]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have an entity :
```
@Entity()
export class Bench implements IBench {
    @ObjectIdColumn() id: ObjectID;

    @Column() name: string;

    @Column('json') location: any;
}
```

My test is :
```
const bad_bench: IBench = {
        name: [42],
        location: {
            type: 'Point',
            coordinates: [3, 4]
        }
    };

describe('Test BenchService#create', () => {
        it('should not create a bench', async () => {
            await expect(this.service.create(bad_bench)).rejects.toBeFalsy();
        });
    });

```

My BenchService create method :
```
async create(payload: T): Promise<T> {
        try {
            const entity: T = this._repository.create(payload);

            await this._repository.save(entity);

            return Promise.resolve(entity);
        } catch (error) {
            return Promise.reject(error);
        }
    }
```

My test fails because bench is created despite the wrong type of attribute name. Is it normal ?

**Comment by thonythony** [comment]
For reply to my own question, I think I have to use the class-validator package for validate my entities. Is it correct ?

**Comment by pleerock** [comment]
it is correct behaviour, create does not perform validation. As you told you need to use third-party package.
