### ISSUE TITLE
bigint PK incorrectly returning as a number (expecting a string)

### ISSUE THREAD

**Issue by Slessi** [typeorm/typeorm#1805]
# Type

[x] `mysql`
[x] bug report
[x] `0.1.16`

# Description

I insert the string `"76561198016705746"` for a `bigint` column, and data is correctly inserted and correctly reflected on the object I just saved.

I later query the same table for an entry with `id: "76561198016705746"` and my item is found *but* the `id` is displayed as the number `76561198016705740`.

Note how the last digit (`6`) is now a `0`. I am aware of the integer limitations of JavaScript and was expecting to see a string here.

The number conversion is contrary to the behaviour described in #1127 

# Reproducing

Simply edit the connection details in the below code to point to an empty mysql database and run it in an environment with `TypeORM` available. I used `ts-node` to run if that makes any difference.

```ts
import { BaseEntity, Connection, createConnection, Entity, PrimaryColumn } from "typeorm";

@Entity("accounts")
class Account extends BaseEntity {
    @PrimaryColumn("bigint")
    public id: string;
}

(async () => {
    let dbConn: Connection;

    try {
        dbConn = await createConnection({
            type: "mysql",
            host: "127.0.0.1",
            port: 3306,

            database: "database",
            password: "password",
            username: "username",

            synchronize: true,
            entities: [Account],
        });

        const bigIntId = "76561198016705746";

        let account: Account;

        console.log(`Querying ${bigIntId}`);

        account = await Account.findOneById(bigIntId);

        if (!account) {
            console.log(`Inserting ${bigIntId}`);

            account = new Account();
            account.id = bigIntId;
            await account.save();

            // Re-query required to emulate receiving incorrect type
            account = await Account.findOneById(bigIntId);
        }

        console.log(`Received ${account.id}`);
    } catch (error) {
        console.error(error.message);
    } finally {
        if (dbConn) {
            dbConn.close();
        }
    }
})();
```

The above gives me the following output:

```
$ ts-node src/test.ts 
Querying 76561198016705746
Inserting 76561198016705746
Received 76561198016705740
```

**Comment by pleerock** [comment]
Looks like this is how underlying node-mysql package works. Probably it has some options to fix this behaviour and return strings instead. Easy feature, feel free to contribute.

**Comment by Slessi** [comment]
@pleerock Thanks, adding the following options to my ORM config resolved my problem

```
{ "supportBigNumbers": true, "bigNumberStrings": true }
```

Not sure why wouldn't be the default behaviour

**Comment by pleerock** [comment]
We probably can add them by default. Not sure why they are not by default in node-mysql.

**Comment by Slessi** [comment]
Yeah, I blame `node-mysql` not you :p

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.37`. You can try it via `npm i typeorm@next`.

**Comment by Slessi** [comment]
Just as an FYI... this sets `decimal` to strings as well, noticed today

**Comment by pleerock** [comment]
@Slessi yeah we noticed it, thank you.
