### ISSUE TITLE
Strategy for managing ts-node extensions

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#1806]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Given that a developer wants to run ts-node to execute their code during development AND uses `ormconfig.env` to assign a `**/*.ts` glob pattern

When they switch to run the post-transpiled `.js` files via the node vm

Then there should be a generic way to change the extension from '.ts' to 'js' AND change the 'entitiesDir / subscribersDir / migrationsDir' 

```
TYPEORM_EXTENSIONS=.ts
TYPEORM_EXTENSIONS=.js
```

Right now im using https://www.npmjs.com/package/dotenv to preload separate ENV configs up during 'npm run start' && 'npm run dev' - but this results in duplicate code. 

I'm also open to alternatives approach to being able to run in dev mode and production mode, and maybe we can outline that in the docs.

**Comment by pleerock** [comment]
Having separate env variables for different platforms is natural, I don't see what is the issue here.
