### ISSUE TITLE
Cannot read property 'insert' of undefined

### ISSUE THREAD

**Issue by snaquaye** [typeorm/typeorm#1807]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. Run typeorm init
2. install dependencies
3. run application

**Result**
```
TypeError: Cannot read property 'insert' of undefined
server.ts:21
message:"Cannot read property 'insert' of undefined"
```

**Comment by snaquaye** [comment]
Investigating the issue further, I noticed `this.queryRunner` has no property `manager`, but it has a `connection property` which in turns contains the `manager` object.

```
options:Object {type: "mongodb", host: "localhost", port: 27017, …}
queryResultCache:undefined
relationIdLoader:RelationIdLoader {connection: Connection}
relationLoader:RelationLoader {connection: Connection}
sqljsManager:Error: SqljsEntityManager is only available for Sqljs databases.
subscribers:Array(0) []
__proto__:Object {mongoManager: <accessor>, sqljsManager: <accessor>, connect: , …}
data:Object {}
databaseConnection:MongoClient {domain: null, _events: Object, _eventsCount: 0, …}
isReleased:false
isTransactionActive:false
__proto__:Object {cursor: , aggregate: , bulkWrite: , …}
```

**Comment by pleerock** [comment]
@snaquaye I remember I was fixing similar issue few days ago, can you please try latest `@next` ?

**Comment by snaquaye** [comment]
@pleerock I now get "Cannot read property 'createValueMap' of undefined"
The exception is thrown on 306 MongoDriver.ts

**Comment by pleerock** [comment]
then provide a failing test and let's investigate this issue together

**Comment by jonathan-casarrubias** [comment]
@pleerock I just installed the @next version to fix another issue and got the same issue that @pleerock is stating

![image](https://user-images.githubusercontent.com/1533239/38071779-7a041a2e-32e0-11e8-94ac-4a08aa0cf45d.png)

**Comment by pleerock** [comment]
please provide a minimal reproduction code sample

**Comment by pleerock** [comment]
Closing as no answer from reporter.
