### ISSUE TITLE
Generated migrations include schema name which should not be the case

### ISSUE THREAD

**Issue by N0ps32** [typeorm/typeorm#1808]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.1.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
 - Generate migrations with CLI.

**Why this is a problem**
I program with my dev setup and have my database configured like this:
```TYPEORM_DATABASE=myproject_dev```
Now I generate my migrations locally.

My configuration for production is:
```TYPEORM_DATABASE=myproject_prod```
Now typeorm accesses "myproject_prod".  
So far so good.
   
But now I cannot execute the locally generated and tested migrations because those still point to "myproject_dev".

Example:
```await queryRunner.query("ALTER TABLE `myproject_dev`.`shipping_label` DROP FOREIGN KEY `fk_0b44f6c88e2852adb1c2ca677f5`");```

Typeorm is the only ORM I know of that has this weird behavior. This makes it very difficult to have a shared DB server with staging, and dev environment on it since both need to share the same DB name as prod.
  
For example Doctrine another very big ORM generates its migrations like this, which makes much more sense: ```$this->addSql('ALTER TABLE User DROP FOREIGN KEY FK_2DA17977B08FA272');```

**Comment by bartlomiej-korpus** [comment]
This behaviour changed in @next and works as expected now.

**Comment by pleerock** [comment]
@N0ps32 please try this on `@next` (npm i typeorm@next) and let us know.
