### ISSUE TITLE
ES Modules (ES2015/ES6)

### ISSUE THREAD

**Issue by nicomouss** [typeorm/typeorm#1809]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Steps to reproduce or a small repository showing the problem:**

When installing the latest version of typeorm through npm (npm install typeorm --save), the version installed is compiled in CommonJS (ES5).
Is a typeorm version compiled in ES Modules (ES2015/ES6) using .mjs extensions, also published along the CommonJS one ?

**Comment by pleerock** [comment]
No. Let's wait until this experimental modules adopt into ecosystem more then it is right now. For now using `.mjs` format bring me only frustrations.

**Comment by nicomouss** [comment]
You are absolutely right, frustration is the right word.

For now, I ended up compiling my projects with "commonjs" module option in typescript compiler. That way no problem with "import" statements at runtime. Works fine.

```javascript
{
    ...
    "compilerOptions": {
        ...
        "module": "commonjs",
        "moduleResolution": "node"
        "lib": ["ES2015"],
        "target": "ES2015",
        ...
    }
    ...
}
```

**Comment by pleerock** [comment]
I'll close this issue but Im sure we will return back to it in a near future.

**Comment by RobertSandiford** [comment]
Revisit?

**Comment by SpBills** [comment]
Revisit (again)?

**Comment by niekcandaele** [comment]
Ran into this issue myself, temporary workaround was to change my typeorm imports to

```js
import typeorm from 'typeorm';

const { Connection, ConnectionOptions, createConnection } = typeorm;
```

**Comment by RobertSandiford** [comment]
It's not really necessary for TypeORM to be published in ESM format.

The issue that remains is that TypeORM uses the esInterop format in commonJS which isn't supported in node, but is used in the typescript community, making support for node + JS (not TS) poor.
