### ISSUE TITLE
TreeChildren is not exported

### ISSUE THREAD

**Issue by szepeshazi** [typeorm/typeorm#181]
Trying to use ClosureTable and TreeRepository as per [documentation](https://typeorm.github.io/tables-and-columns.html#closure-table), but tsc complains that `typeorm/index has no exported member TreeChildren`. Indeed, in the index.ts file I could only find export declarations for TreeLevelColumn and TreeParent, but not for TreeChildren.

**Comment by pleerock** [comment]
fixed and released in `0.0.7-alpha.5`
