### ISSUE TITLE
Choosing MongoDB Authentication Method

### ISSUE THREAD

**Issue by mdebord1** [typeorm/typeorm#1810]
**Issue type:**

[ X ] question
[ ] bug report
[ ] feature request
[ X ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ X ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm reviewing https://github.com/typeorm/typeorm/blob/master/src/driver/mongodb/MongoConnectionOptions.ts to see the connection options for TypeORM however I don't see the authentication mechanism options. 

In comparison, here are 3x different examples of how I can connect to my db via shell, python, and GUI clients: 

**Here is how I succesfully connect via Shell (mongo client):**
`mongo --host myhost.example.com --port 27017 --username myuser --password mypass --authenticationMechanism SCRAM-SHA-1 --authenticationDatabase mydb`

**Here is how I succesfully connect via Python:** 
```
>>> from pymongo import MongoClient
>>> client = MongoClient('myhost.example.com',
...                      username='myuser',
...                      password='mypass',
...                      authSource='mydb',
...                      authMechanism='SCRAM-SHA-1')
```
**Here is how I successfully connect via Robo 3T Mongo GUI Client:** 
![screen shot 2018-03-22 at 2 09 02 pm](https://user-images.githubusercontent.com/31278712/37798721-cf3c2744-2dda-11e8-863a-5f9349889aba.png)

**How can I do this with TypeORM?** 

Info on Mongo's default authentication types: https://docs.mongodb.com/manual/reference/parameters/#param.authenticationMechanisms

Thanks!!

**Comment by pleerock** [comment]
Opened for contributions. Feel free to add any option you need, its easy to do.

**Comment by Rhymmor** [comment]
PR here: #1850

**Comment by pleerock** [comment]
Thanks @Rhymmor will be released in next version.

**Comment by Rhymmor** [comment]
Forgot to correct option description. Sorry for that( PR #1852
