### ISSUE TITLE
Can I give @Entity() a name to match existing table in the database?

### ISSUE THREAD

**Issue by chj-damon** [typeorm/typeorm#1812]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I already have some tables in my database, now I want to use nextjs Entity to match them. 
for example, in my database one table is named as 'Departs', but I want to declare my class name as 'Department':
```js
@Entity()
class Department {
...
}
```
so, my question is: can I pass a string to `@Entity()` to relate my table with my class like this：
```js
@Entity('Departs')
class Department {
...
}
```

**Comment by nicomouss** [comment]
Use this syntax :

```javascript
@Entity({name: "Departs"})
class Department {
...
}
```

**Comment by chj-damon** [comment]
@nicomouss Thanks.

**Comment by sardaryanhrant** [comment]
Thanks

**Comment by inmogr** [comment]
@nicomouss i have already used your way as it is described in the documentation but TypeORM still using the Class name. Can you advice me pls?

**Comment by amhed** [comment]
I'm getting the same. Did you ever solve this @inmogr ?

**Comment by joturako** [comment]
@amhed if you still have problem, try clear the dist folder, sometime the file there get stuck and not updated even though you have updated ts file. I wasted 1 hour to realize that...

**Comment by amhed** [comment]
@joturako typeorm was translating correctly. I saw a different class name because it generates an alias automatically. The error was not within the table name, but elsewhere.

Thanks for the follow up either way :)

**Comment by maxzod** [comment]
/** @deprecated */
declare const name: void;

but how to use another name for the table now ?

**Comment by nebkat** [comment]
`@Entity('tablename')` or `@Entity({name: 'tablename'})`, neither of which is deprecated.

**Comment by amateraaasuuu** [comment]
> ```js
> Departs'
> ```

It's work

**Comment by SaintPepsi** [comment]
> `@Entity('tablename')` or `@Entity({name: 'tablename'})`, neither of which is deprecated.

This is not working for me, it's still using the automatically generated name for me. Any suggestions?

**Comment by zhandos200103201** [comment]
If the problem does not solved yet, then you can write all info with UPPERCASE. table name and the columns

**Comment by SaintPepsi** [comment]
> If the problem does not solved yet, then you can write all info with UPPERCASE. table name and the columns

This doesn't work for me either, it seems to just use the class name. 

Are you able to provide a minimum reproduction where it works for you?
