### ISSUE TITLE
how to migrate When using multiple connections?

### ISSUE THREAD

**Issue by kaimiyang** [typeorm/typeorm#1813]
[x ] question
[x] documentation issue
[x] `mysql` / `mariadb`
[x] `latest`

 In section [migrations](http://typeorm.io/#/migrations), when using multiple connections, use cli:
```
typeorm migrations:run
```
it's error report:

> Error: Cannot find connection default because its not defined in any orm configuratio
> n files.

In ormconfig.json file, how to config it?

**Comment by adriankott** [comment]
try typeorm migrations:run -c  migrationName

**Comment by kaimiyang** [comment]
I'm tried, it's errors too, and there is not `-c` parameter in `typeorm ` cli

**Comment by pleerock** [comment]
```
typeorm migrations:run

Options:
  -h, --help        Show help                                          [boolean]
  --connection, -c  Name of the connection on which run a query.
                                                            [default: "default"]
  --config, -f      Name of the file with connection configuration.
                                                          [default: "ormconfig"]
  -v, --version     Show version number                                [boolean]

```

`-c` option works, just checked.
