### ISSUE TITLE
Bad error message when pg is not part of package.json

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#1816]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I got the following error when running a express/typeorm setup.

The root cause was i was missing package: `pg`
```

api_1  | { Error
api_1  |     at new ConnectionNotFoundError (/app/src/error/ConnectionNotFoundError.ts:10:22)
api_1  |     at ConnectionManager.get (/app/src/connection/ConnectionManager.ts:40:19)
api_1  |     at DatabaseManager.<anonymous> (/app/src/app/injectables/database.injectable.ts:40:50)
api_1  |     at Generator.throw (<anonymous>)
api_1  |     at rejected (/app/src/app/injectables/database.injectable.ts:5:65)
api_1  |     at <anonymous>
api_1  |   name: 'ConnectionNotFoundError',
api_1  |   message: 'Connection "default" was not found.' } Promise {
api_1  |   <rejected> { Error
api_1  |     at new ConnectionNotFoundError (/app/src/error/ConnectionNotFoundError.ts:10:22)
api_1  |     at ConnectionManager.get (/app/src/connection/ConnectionManager.ts:40:19)
api_1  |     at DatabaseManager.<anonymous> (/app/src/app/injectables/database.injectable.ts:40:50)
api_1  |     at Generator.throw (<anonymous>)
api_1  |     at rejected (/app/src/app/injectables/database.injectable.ts:5:65)
api_1  |     at <anonymous>
api_1  |   name: 'ConnectionNotFoundError',
api_1  |   message: 'Connection "default" was not found.' } }
```

Should check dependencies and throw meaningful error

**Comment by pleerock** [comment]
thats strange. Can you test a clean setup? I guess something is called before database connection is established or something like that.

**Comment by pleerock** [comment]
Closing as no answer from reporter.
