### ISSUE TITLE
postgres migrations table name becomes 'undefined'

### ISSUE THREAD

**Issue by josephktcheung** [typeorm/typeorm#1819]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I'm using `0.2.0-alpha.30` to run migration. Here's my ormconfig:
```json
{
  "name": "default",
  "type": "postgres",
  "host": "localhost",
  "port": 1200,
  "username": "test",
  "password": "test",
  "database": "test",
  "schema": "public",
  "entities": ["src/database/entity/**/*.ts"],
  "migrations": ["src/database/migration/**/*.ts"],
  "cli": {
    "entitiesDir": "src/database/entity",
    "migrationsDir": "src/database/migration"
  }
}

```

And here's my migration script:
```ts
import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddUser1521966747987 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(
      `CREATE TABLE "public"."user" ("id" SERIAL NOT NULL, "firstName" character varying(100), "lastName" character varying(100), "facebookPSID" character varying, "email" character varying(100), "pictureId" character varying NOT NULL, CONSTRAINT "PK_03b91d2b8321aa7ba32257dc321" PRIMARY KEY ("id"))`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(`DROP TABLE "public"."user"`);
  }
}
```

After migration, from pgAdmin I see 2 table, `undefined` and `user`, which `undefined` should be `migrations` instead.
![screen shot 2018-03-25 at 4 33 03 pm](https://user-images.githubusercontent.com/4270232/37873218-460a9e8e-304a-11e8-8c0e-fc98053e7d47.png)

I tried older version of `typeorm` (0.1.16) and the table name is `migrations` which is correct.
![image](https://user-images.githubusercontent.com/4270232/37873235-a0d2ae38-304a-11e8-8433-a6d555e29cf4.png)

**Comment by pleerock** [comment]
Thanks for the report, fixed in `0.2.0-alpha.31`
