### ISSUE TITLE
BeforeInsert it work ? 

### ISSUE THREAD

**Issue by GinFoB** [typeorm/typeorm#1823]
I want to know if BeforeInsert work or i have some problem with my code

>  @Column()
>     password: string;
> 
>    @BeforeInsert()
>     updatePassword() {
>         console.log("debug",this.password);
>         this.password = bcrypt.hashSync(this.password, 8);
>     }

**Comment by pleerock** [comment]
yes, it works, you do something wrong thats why it does not work for you.

**Comment by GinFoB** [comment]
Ok, i want to thank you for the great ORM 👍 , and i plan to use it in all future projects.

**Comment by pleerock** [comment]
thank you

**Comment by JamesCoonce** [comment]
This does not work.

**Comment by alirezapaydar** [comment]
> 
> 
> I want to know if BeforeInsert work or i have some problem with my code
> 
> > @column()
> > password: string;
> > @BeforeInsert()
> > updatePassword() {
> > console.log("debug",this.password);
> > this.password = bcrypt.hashSync(this.password, 8);
> > }

You must use async instead of Sync.
