### ISSUE TITLE
CreateDateColumn error

### ISSUE THREAD

**Issue by Daley** [typeorm/typeorm#1824]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x ] `latest`
[ ] `@next`

`@CreateDateColumn()`
`ctime`

mysql@5.5
`[SQL]ALTER TABLE `zjh`.`im_user` ADD `ctime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`
`[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)' at line 1`

**Comment by AlexMesser** [comment]
#609

**Comment by pleerock** [comment]
Closing as duplicate, this should be fixed soon.
