### ISSUE TITLE
Question on query building to select a single column of the original table

### ISSUE THREAD

**Issue by Tyler-V** [typeorm/typeorm#1827]
```
@Entity()
export class Script {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @OneToMany(type => Session, session => session.script)
    sessions: Session[];

    @ManyToMany(type => User)
    @JoinTable()
    users: User[];
}
```

```
@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    username: string;

    @OneToMany(type => Session, session => session.user)
    sessions: Session[];
}
```

I am trying to select the Script.name of users who have Script.

```
    async findScripts(username: string): Promise<Script[]> {
        return await this.scriptRepository
            .createQueryBuilder('script')
            .select('script.name')
            .leftJoin('script.users', 'user')
            .where('user.username = :name', { name: username })
            .getMany();
    }
```

```
[
  {
    "name": "Script A",
    "users": [
      
    ]
  },
  {
    "name": "Script B",
    "users": [
      
    ]
  }
]
```

It works, only issue is my left join is also adding an unwanted empty users array, I'm sure it is something dumb I overlooked. Any tips?

Been playing around with NestJS / TypeORM today overall very pleased and happy with this library, hats off to the contributors this is absolutely fantastic.

Thanks.

**Comment by pleerock** [comment]
First, you must select primary columns, its a requirement. Second, you need to use `leftJoinAndSelect` if you want users to be returned in the array

**Comment by Tyler-V** [comment]
Hey thanks for the reply @pleerock 

I should clarify, I am trying to only get the name and not the users array.

This is what I am trying to achieve, how would I write this in typeorm?

```
SELECT DISTINCT name FROM script
LEFT JOIN script_users_user ON script_users_user.scriptId
LEFT JOIN user ON script_users_user.userId
WHERE username = 'User A'
```

```
[
  {
    "name": "Script A",
  },
  {
    "name": "Script B",
  }
]
```

**Comment by pleerock** [comment]
I don't understand why you need two joins when you don't use them. Is `username` part of `script` ?

Something like this shall work:

```ts
this.scriptRepository
            .createQueryBuilder('script')
            .select('script.name', 'name')
// add joins and wheres here
            .groupBy("user.name")
            .getRawMany();
 ```

**Comment by Tyler-V** [comment]
@pleerock the difference in all of this was using getMany() vs getRawMany()

This indeed returns what I am looking for, returning the entities returned from getMany() adds the unwanted empty array 'users'.

```
        return await this.scriptRepository
            .createQueryBuilder('script')
            .select('script.name')
            .leftJoin('script.users', 'user')
            .where('user.username = :name', { name: username })
            .getRawMany();
```
```
[
  {
    "script_name": "USA Agility"
  },
  {
    "script_name": "USA Lava Dragons"
  }
]
```

**Comment by Tyler-V** [comment]
Thanks!

**Comment by pleerock** [comment]
btw, can you try it on `@next`? On `@next` for sure it should not return empty users array if you are not using `leftJoinAndSelect`

**Comment by Tyler-V** [comment]
Sorry I'm not familiar enough with the library yet, what is @next I don't see that referenced in http://typeorm.io/#/select-query-builder

**Comment by pleerock** [comment]
`@next` is the latest version (0.2.0 final will be released soon) that contains lot of changes and fixed we have made in past 6 month. Try it via `npm i typeorm@next`

**Comment by Tyler-V** [comment]
```
        return await this.scriptRepository
            .createQueryBuilder('script')
            .select('name')
            .leftJoinAndSelect('script.users', 'user')
            .where('user.username = :name', { name: username })
            .getMany();
```
Using the following returns just an empty array

```
[

]
```

**Comment by pleerock** [comment]
Something is definitely wrong, can you please show your script and user entities?

**Comment by Tyler-V** [comment]
They're in the first post @pleerock

**Comment by Tyler-V** [comment]
```
@Entity()
export class Script {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({ unique: true })
    name: string;

    @OneToMany(type => Session, session => session.script)
    sessions: Session[];

    @ManyToMany(type => User)
    @JoinTable()
    users: User[];
}
```

```
@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({ unique: true })
    email: string;

    @Column({ unique: true })
    username: string;

    @Column()
    password: string;

    @OneToMany(type => Session, session => session.user)
    sessions: Session[];
}
```

**Comment by pleerock** [comment]
strange, what if you do so:

```ts
        return await this.scriptRepository
            .createQueryBuilder('script')
            .select('id')
            .addSelect('name')
            .leftJoinAndSelect('script.users', 'user')
            .where('user.username = :name', { name: username })
            .getMany();
```

What is returning result?

**Comment by pleerock** [comment]
ah, wait. QueryBuilder code is not correct. Correct is:

```ts
        return await this.scriptRepository
            .createQueryBuilder('script')
            .select('script.name')
            .leftJoinAndSelect('script.users', 'user')
            .where('user.username = :name', { name: username })
            .getMany();
```

Also, try 

```ts
        return await this.scriptRepository
            .createQueryBuilder('script')
            .select('script.name')
            .leftJoin('script.users', 'user')
            .where('user.username = :name', { name: username })
            .getMany();
```

**Comment by Tyler-V** [comment]
1. Returns the script name and full user entity, instead of just the script.name as desired.

```
[
  {
    "name": "Script A",
    "users": [
      {
        "id": 1,
        "email": "email1",
        "username": "user1",
        "password": "password1"
      }
    ]
  },
  {
    "name": "Script B",
    "users": [
      {
        "id": 1,
        "email": "email1",
        "username": "user1",
        "password": "password1"
      }
    ]
  }
]
```

2. Returns the desired result, just the script names.

```
[
  {
    "name": "USA Agility"
  },
  {
    "name": "USA Lava Dragons"
  }
]
```

**Comment by pleerock** [comment]
okay so everything as expected

**Comment by Tyler-V** [comment]
Yes looks good! Let me know if I can help with anything else @pleerock

**Comment by webmobiles** [comment]
@Tyler-V what about select only the field users.email ? where use '.select()' ?
is not working with me, only select direct fields from the join table. thanks

**Comment by jaimedeverall** [comment]
Hi there, is there any follow up on @webmobiles question. I can select fields of `script` just fine but can't select the fields of the relation table, `user`

**Comment by elle86a** [comment]
I Have the same issues, can't select the leftjoin column in version 0.2.25

**Comment by webmobiles** [comment]
try to do:

      .select([
        'secondtable.name as name2',
        'SUM(investments.amount) as startup_amount_invested_in',
        'COUNT(lists) as startup_list_count'
      ])

**Comment by lakhandeshpande** [comment]
return await this.scriptRepository
            .createQueryBuilder('script')
            .select('script.name')
            .leftJoin('script.users', 'user')
            .where('user.username = :name', { name: username })
            .getMany();

I would like to know how this get executed or called? In which file I should write this code to execute?
