### ISSUE TITLE
@Transaction, @TransactionRepository() and @TransactionManager() poorly documented.

### ISSUE THREAD

**Issue by chrisstpierre** [typeorm/typeorm#1828]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ X ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The TypeORM documentation for transaction decorators appears to be slightly incorrect:
```ts
@Transaction()
save(user: User, @TransactionRepository(User) userRepository: Repository<User>) {
    return userRepository.save(user);    
}
```
The problem with this is [this Typescript issue](https://github.com/Microsoft/TypeScript/issues/4881) which prevents typing from working correctly when decorators are used. In this case, the above function cannot be called with a single parameter `save(user)` without a typescript error stating that the parameters do not match (since save is really expecting 2 parameters).

In this case, it has to be written with a type guard. There are probably other solutions as well:

```ts
@Transaction()
save(user: User, @TransactionRepository(User) userRepository?: Repository<User>) {
    if ( userRepository === undefined) { return; }
    return userRepository.save(user);    
}
```

This should be documented.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
You are right, its a bit tricky. Overall those decorators are useful mostly in cases when someone else calls those methods (save), for example some framework. Im still not sure if transaction decorators must be part of typeorm core. Feel free to PR with changes you think must be applied to documentation.
