### ISSUE TITLE
@<*>DateColumn() decorated columns should respect input

### ISSUE THREAD

**Issue by b-mck** [typeorm/typeorm#1829]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

For testing purposes, I need the ability to set the created date on an object to something other than the current instant. Use case is testing a periodic email reminder function in a web app that needs to select groups of objects around (e.g.) 48 hours old.

There's currently no good way to create and return test data with a manually-set date. `createQueryBuilder()` allows me to insert the data as I need, with arbitrary dates, but does not even return IDs to select the newly created rows, let alone the hydrated objects like the `BaseEntity.save` method. Since my objects are backdated, I also can't easily select the most recently created objects.

QueryBuilder support for returning the IDs of created objects on MariaDB would also solve my problem; let me know if I'm just missing that in the documentation.

**Comment by pleerock** [comment]
Switch to `@next`. In `@next` save method returns you every column with DEFAULT value set and updates your model. Also there is a `returning` method in query builder, but that works only in postgres and mssql since mysql does not support returning expression.

**Comment by pleerock** [comment]
Please let me know if you still have questions.

**Comment by pleerock** [comment]
@dcworldwide `@next` is more stable then latest already.
