### ISSUE TITLE
Selecting one column only from a table by query builder.

### ISSUE THREAD

**Issue by MURDEREDBEAR** [typeorm/typeorm#1832]
Issue type:

[x ] question
or
[x] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[x] postgres
[ ] sqlite
[ ] sqljs
[ ] websql

TypeORM version:

[ ] latest
[x] @next
[ ] 0.x.x (or put your version here)

Hello!

I trying to select only one column in my table but in response in JSON I got chosen the column and all fields were created by "Column" decorator (in this example is varchar and boolean fields).

There is my select query:

```
getConnection().getRepository(Object)
      .createQueryBuilder("object")
      .where("object.id = :id", { id: params.payload.id })
      .select(["object.column1"])
      .getMany()
```

And there are fields defined in the model with this what I need in response (I omit the rest of fields I have defined here, including id):

```
@CreateDateColumn()
column1 = undefined;

@Column('varchar')
column2 = ''

@Column('varchar')
column3 = ''

@Column({ type: 'boolean', default: false })
column4 = false;

```
At last, this is response JSON:

```
{
    "column1": "2018-03-27T00:00:00.000Z",
    "column2": "",
    "column3": "",
    "column4": false
}
```

Is this a bug or just I doing something wrong? I don't need redundant fields in response JSON in this case 😃

**Comment by pleerock** [comment]
are you able to create a PR with a failing test, so I can quickly take a look and fix if it is a real issue? Btw primary columns are required for selection since ORM makes lot of decisions based on them.

**Comment by MURDEREDBEAR** [comment]
Hello @pleerock !
I didn't have more free time to look at it and I'm sorry that I didn't continue our discussion for so long. 😞 

Recently without checking if you have responded to my post, I managed to solve the problem by replacing getMany() with execute() on end of a query.

After I got response like this:
```
{
    "column1": "2018-03-27T00:00:00.000Z",
    "column4": false,
}
```

So just my fault, I haven't checked all the possibilities before.
We can close issue at this moment.
If there is a more elegant solution to resolve it, I can prepare the whole test project in my free time, then you can analyze what happens. 😄

**Comment by pleerock** [comment]
Thanks for your kind answer.

**Comment by cshelpucla** [comment]
I can concur with the above - I spent an entire day trying to figure out what is wrong with my query only to find out that getMany and getOne DO NOT work on it BUT execute DOES.

Here's the query:

  const playersStandings = await connection.getRepository("game").createQueryBuilder("game")
                .select([ "user_alliance.alliance_id AS clubId",  
                          "player.user_id AS slgUserId",  
                          "game_stats_rollup.pSName AS summonerName", 
                          "COUNT(game_stats_rollup.game_id) AS gameCounts",
                        ])
                .leftJoin( game_stats_rollup, 'game_stats_rollup', 'game.external_game_id = game_stats_rollup.tournament_code COLLATE utf8mb4_0900_ai_ci')
                .leftJoin( user_alliance, 'user_alliance', 'game.series_id = user_alliance.series_id ')
                .leftJoin( player, 'player', 'player.external_player_id = game_stats_rollup.pSId COLLATE utf8mb4_0900_ai_ci ')
                .where(" game.series_id IN (" + seriesInClause + ") ")
                .andWhere(" player.user_id = user_alliance.user_id" )
                /// .andWhere("game.series_id = :seriesId ", { seriesId: series_id })
                .groupBy("user_alliance.alliance_id")
                .addGroupBy("player.user_id")
                .addGroupBy("game_stats_rollup.pSName")
                .execute() 

Above returns no data with getMany but returns data with execute

Please address it if you can.   Much appreciated.

**Comment by thuan-gempage** [comment]
I got the same problem with @cshelpucla. My database is `PostgreSQL` and here is my query

``` javascript
  const queryResult = await getConnection()
    .createQueryBuilder('user', 'u')
    .innerJoinAndSelect('user_film', 'uf', 'uf.user_id = u.id')
    .innerJoinAndSelect('film', 'f', 'uf.film_id = f.id')
    .innerJoinAndSelect('dubbing', 'd', 'd.film_id = f.id')
    .where(`d.id = ${dubbingId}`)
    .select(['socket_ids'])
    .getOne();
```
Change from `getOne` to `getMany` work.

**Comment by kasir-barati** [comment]
TypeORM official doc is really lacking tons of aspects and this is not really good. IDK if someone just wanted to start use this library how much time they had to google to land to this page to understand what they should do and TBF now I am not sure if we should say something like "Working software over comprehensive documentation" anymore since this kind of docs lead a lot of resources to go to waste. But maybe it is not also that extreme.

**Comment by kasir-barati** [comment]
In my experience, it does not matter if you wanna use `getRawMany`, `getRawOne`, or `execute`, or other methods. You need to keep in mind that for some reason you need to chain your select at the end of the methods:

```ts
createQueryBuilder("tb")
  .leftJoinAndSelect("tb.tb2", "tb2")
  .otherMethods()
  .select([/* fields */])
  .getOne(); // getRawOne(), or other methods
```
