### ISSUE TITLE
get CustomRepository with dependency resolve

### ISSUE THREAD

**Issue by xujif** [typeorm/typeorm#1837]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:*

It's a feture request. 
I found that typeorm use "new" when create a  "CustomRepository",
so can not use typedi or other Container in CustomRepository.

**Comment by pleerock** [comment]
It is by design. Repositories can't be global because they have specific dependencies, e.g. multiple instances of `CustomRepositoryX` class which may have their own managers, connection instances,  transactional query runners.
