### ISSUE TITLE
Charset and collation not being carried to JoinTable when generating migration

### ISSUE THREAD

**Issue by hillin** [typeorm/typeorm#1839]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Repro steps:
 - create two entities
 - set the charset and/or collation for either or both entities' primary columns
 - create a many-to-many relationship between them, and place a `@JoinTable` decorator on either side
 - generate migration

In the generated migration, the columns in the join table, corresponding to the primary columns of both entities, won't have the specified charset/collation.

**Comment by pleerock** [comment]
Can you please check this functionality in `@next` ? (npm i typeorm@next)

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.43`. You can try it via `npm i typeorm@next`.
