### ISSUE TITLE
[Single Table Inheritance] Can't use Base Class Repository operations

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#184]
I receive an error when using Single-Inheritance with Postgres 9.5 and 0.0.6 or 0.0.7-alpha.5.

**Model** 

```
@Table()
@TableInheritance("single-table")
@DiscriminatorColumn({ name: "type", type: "int" })
export class Promotion {

    @PrimaryColumn("string")
    id: string

    constructor() {
        this.id = uuid.v4()
    }

    type: number  // I was using an enum (PromotionType) but same issue 
}

@SingleTableChild()
@DiscriminatorValue(PromotionType.Percentage)
export class PromotionPc extends Promotion {

    @Column()
    cDiscountPc: number

    constructor() {
        super()
        this.type = PromotionType.Percentage
    }
}

@SingleTableChild()
@DiscriminatorValue(PromotionType.FixedPrice)
export class PromotionFixed extends Promotion {

    @Column()
    cValue: number

    constructor() {
        super()
        this.type = PromotionType.FixedPrice
    }
}
```

**Test**

Table creates ok. 
Error on inserting the below PromotionPc object 

{
id: '1774',
createdAt: 2017-01-10T04:37:34.152Z,
type: 100,
cDiscountPc: 15,
}

**Error**

```
[1] query failed: SELECT "operateSubject"."id" AS "operateSubject_id", "operateSubject"."createdAt" AS "operateSubject_createdAt", "ope
rateSubject"."updatedAt" AS "operateSubject_updatedAt", "operateSubject"."sId" AS "operateSubject_sId", "operateSubject"."isBase" AS "o
perateSubject_isBase", "operateSubject"."startAt" AS "operateSubject_startAt", "operateSubject"."endAt" AS "operateSubject_endAt", "ope
rateSubject"."type" AS "operateSubject_type", "operateSubject"."cDiscountPc" AS "operateSubject_cDiscountPc", "operateSubject"."aCommis
sionPc" AS "operateSubject_aCommissionPc", "operateSubject"."cValue" AS "operateSubject_cValue", "operateSubject"."cMinOrderAmount" AS
"operateSubject_cMinOrderAmount", "operateSubject"."aCommission" AS "operateSubject_aCommission" FROM "promotion" "operateSubject" WHER
E ("operateSubject"."id"=$1) AND type=$2 -- PARAMETERS: ["1774","Promotion"]
[1] { error: invalid input syntax for integer: "Promotion"
[1]     at Connection.parseE (/Users/Danijel/projects/am/am-api/node_modules/pg/lib/connection.js:554:11)
[1]     at Connection.parseMessage (/Users/Danijel/projects/am/am-api/node_modules/pg/lib/connection.js:381:17)
[1]     at Socket.<anonymous> (/Users/Danijel/projects/am/am-api/node_modules/pg/lib/connection.js:117:22)
[1]     at emitOne (events.js:96:13)
[1]     at Socket.emit (events.js:188:7)
[1]     at readableAddChunk (_stream_readable.js:176:18)
[1]     at Socket.Readable.push (_stream_readable.js:134:10)
[1]     at TCP.onread (net.js:551:20)
[1]   name: 'error',
[1]   length: 91,
[1]   severity: 'ERROR',
[1]   code: '22P02',
[1]   detail: undefined,
[1]   hint: undefined,
[1]   position: undefined,
[1]   internalPosition: undefined,
[1]   internalQuery: undefined,
[1]   where: undefined,
[1]   schema: undefined,
[1]   table: undefined,
[1]   column: undefined,
[1]   dataType: undefined,
[1]   constraint: undefined,
[1]   file: 'numutils.c',
[1]   line: '62',
[1]   routine: 'pg_atoi' }

```

Error that instead of passing the correct Promotion type (100 in this case), it is passing "Promotion". I.e. from the stack above

WHERE ("operateSubject"."id"=$1) AND type=$2 -- PARAMETERS: ["1774",**"Promotion"**]

A few extra questions:

- Are numbers supported? i.e. @DiscriminatorColumn({ name: "type", type: "int" })
- Is a @DiscriminatorValue(PromotionType.Percentage) decorator required for each sub-class?

**Comment by dcworldwide** [comment]
Once we get a working version of this I'd like to submit a PR to improve the documentation with my findings.

**Comment by dcworldwide** [comment]
I can confirm that switching my @DiscriminatorColumn type to a string resolves the issue.

This isn't a workaround for me, I have an existing database that can't be altered.

**Comment by dcworldwide** [comment]
@pleerock I've cloned the repo and setup a test for this issue. See it here https://github.com/dcworldwide/typeorm/blob/single-table-inheritance-184/test/github-issues/184/issue-184.ts. I can submit a PR for it if needed.

Basically I've found my issue.

**Integers are supported**.

The issue is that I was trying to persist @SingleEntityChild() classes using the base Entity repository. I expected polymorphism to apply which is what happened in my case. As per my test above, once I switch to using the sub class repository persistence worked.

I think we need to do something here, either enable persistence from the base class (person in my case) or, have the persistence logic throw an error when the user tries to do this. Otherwise someone else will probably trip on this.

**Comment by pleerock** [comment]
>  I can submit a PR for it if needed.

yeah you can submit a PR for your test if it does a good testing of some functionality.

> I think we need to do something here

yeah probably we can organize such kind of persistence correctly without issues.

**Comment by dcworldwide** [comment]
Here is a major reason why not being able to use the base class as the repository is an issue.

     Person = Base
     Student, Employee = Sub Types 

     getRepository(Person).findOneById(id)

With the current issue, you can't do the above. It will error. Most apps won't care about the sub type, they just want to get a Person.  It's an issue when you have lots of types.

**Comment by pleerock** [comment]
You are right. Looks like only persist and remove operations can work with repository for base class. So what shall we do here? We can just deny usage of repository for base class with corresponding error, or figure out some solution here.

**Comment by dcworldwide** [comment]
For my use case, this issue meant that I couldn't use a STI solution, I ended up embedding the sub type table content into a JSON column (which isn't great as the STI solution was much more concise for me). 

I don't know too much about the code base design just yet... but I'd like to find a solution. Off the top of your head, would getting findX to work using the base class be feasible?

**Comment by pleerock** [comment]
> would getting findX to work using the base class be feasible

no, it would not. find method returns you instance of the base class, but base class is abstract and I dont think find method should return you abstract class instance.

**Comment by dcworldwide** [comment]
With result parsing, I think we could use the type attribute of the DiscriminatorColumn decorator and the value of the DiscriminatorValue decorator on each sub class,  to determine the correct subclass to use per record. We would then need to change the record prototype accordingly. That way base.find() returns records of the correct sub type.

**Comment by pleerock** [comment]
probably that will work. But this is complex. STI and CTI are very complex features. Also need to think what other problems this can cause.

**Comment by pleerock** [comment]
This is working already, checked in `0.2.0-alpha.11`.
