### ISSUE TITLE
Error using ActiveRecord style, but not using Data Mapper

### ISSUE THREAD

**Issue by natew** [typeorm/typeorm#1840]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Just got the cordova driver set up. After a bit of work I have data mapper style queries inserting and selecting, which is awesome.

But for some reason doing `Model.find()` (extending BaseEntity), it fails with ConnectionNotFoundError.

ConnectionNotFoundError
![image](https://user-images.githubusercontent.com/12100/38011125-fea09972-3210-11e8-9d62-8031b5a7a76e.png)

This is running in the Chrome 65.

The connection code:

```js
createConnection({
  type: 'cordova',
  database: 'database',
  location: 'default',
  entities: [Job],
  logging: true,
  synchronize: true,
})
```

To be honest I'm confused as to what the `location` prop is. It's not documented in sqlite, or in cordova that I see, or in Typeorm very much.

Thanks for making some amazing software though, look forward to using this!

**Comment by pleerock** [comment]
I think you are using connection that is not initialized yet. `createConnection` is async method and you need to await it before any operations you do with connection, e.g.

```ts
createConnection({
  type: 'cordova',
  database: 'database',
  location: 'default',
  entities: [Job],
  logging: true,
  synchronize: true,
}).then(connection => {

    // Job.find()

});
```

**Comment by natew** [comment]
Don't think so, I'm doing this in the console after connection is called... using a weird cordova adapter setup, could that be it?

**Comment by pleerock** [comment]
I don't know, but Im sure something is wrong in your setup, since this functionality is basic and it must work without issues. Adding @daniel-lang

**Comment by natew** [comment]
Ah, ok so discovered `Job.useConnection` and that fixes it, which is enough to get me rolling.

I am using [a forked version of this](https://github.com/MetaMemoryT/websql-server) for `window.sqlitePlugin`, as a clue. Will look into it a bit more.

**Comment by natew** [comment]
This is still broken for me, updated to `0.1.20` just in case. Here's the node code:

![image](https://user-images.githubusercontent.com/12100/38223490-0a10a7c8-36a0-11e8-9543-8e3d6c7c8c9a.png)

I've tried including `location` and not including it. Anything you can see here?

I have to include the useConnection or nothing works, including queryBuilder. For example running getConnection() returns:

```
index error Error: Connection "default" was not found.
    at new ConnectionNotFoundError (/Users/nw/projects/motion/orbit/apps/models/src/error/ConnectionNotFoundError.ts:10:22)
    at ConnectionManager.get (/Users/nw/projects/motion/orbit/apps/models/src/connection/ConnectionManager.ts:40:19)
    at Object.getConnection
```

But the connection comes back fine and if I do `useConnection` it works just fine.

**Comment by natew** [comment]
Adding `name: 'default'` doesn't seem to help either.

**Comment by natew** [comment]
Ah ok, think this is a multiple copies issue. Need to de-dupe it from a sub-module... Mobx detects stuff like this, worth re-opening this to track that as a feature request?

**Comment by daniel-lang** [comment]
So you are saying, that you have multiple copies of your `connection`? You shouldn't need to call `useConnection` if you only have one connection and don't change its name.

`location` is [a cordova specific option that tells the plugin where to store the database](http://typeorm.io/#/connection-options/cordova-connection-options).

**Comment by natew** [comment]
No loading multiple copies of typeorm is what broke it. One copy wasn’t
connected, one was.

You could force copies to share state (see mobx useSharedGlobalStats that
was deprecated but could be useful for typeorm to make it always seem like
a singleton. Or just adding a warning could be helpful.

**Comment by daniel-lang** [comment]
This is something @pleerock would have to decide.

Could you explain how you managed to load multiple copies of typeorm?

**Comment by pleerock** [comment]
@natew using multiple connections won't work in active record - active record uses static methods and does not have instances which could have different connections. That's downside of active record, you have to use data mapper to resolve this issue.

**Comment by natew** [comment]
Yea, it was accidental product of two nested packages linked in a monorepo
both with it as a dependency. Hoisted the package and that fixed it.

**Comment by Skydev0h** [comment]
@pleerock, it may not be completely true, that multiple connections wont work with AR.

Maybe a little late, but you actually can use multiple connections with Active Record easily.
You just need to iterate entity metadata of connections, resolve "target" (class function) of each of entities, and explicitly call useConnection on that target (effectively invoking that static function).
And it is actually hassle-free to do that with some kind of similar to following code (tested with Node):
```typescript
createConnections([{
    // connection 1 params
}, {
    // connection 2 params
} /* ...  others */ ]).then(
async connections => {
    // Register entity connections explicitly
    for (const conn of connections)
        for (const em of conn.entityMetadatas)
            if ((em.target as any).useConnection) // AR check
                (em.target as any).useConnection(conn);
    // All other initialization
}).catch(error => {
    // Error handling
});
```
This works for any amount of connections and entities, explicitly defined or pattern-loaded.
May not work or require ts-ignore (or some clutch interface) if "any" usage is prohibited by linter.

_At least works for me. Want to share this simple solution because stumbled upon this issue while googling for "typeorm active record multiple databases"_
