### ISSUE TITLE
Changes in enum type not reflected in generated migration

### ISSUE THREAD

**Issue by hillin** [typeorm/typeorm#1841]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When a column of `enum` type with its `ColumnEnumOptions.enum` set to a Typescript enum type, if the Typescript enum type has been changed, it won't be reflected in the next migration generation.

**Comment by pleerock** [comment]
Can you please check this functionality in `@next` ? (npm i typeorm@next)

**Comment by pleerock** [comment]
Closing as no answer from reporter. It must work in latest `@next`.

**Comment by philippfo9** [comment]
Hey,
I got his issue too with the newest typeorm 0.2.8. I have got an enum like this: `enum EBusinessProcessType {
        BPT_UNKNOWN = 0,
        BPT_FIAT_PAYOUT = 1,
        BPT_FIAT_DEBIT = 2,
        BPT_SEND_TO_EXTERNAL = 3,
        BPT_PAYMENT = 10,
        BPT_PAYMENT_WITH_FIAT_SELL = 11,
        BPT_RETURN = 20,
        BPT_FINE = 21,
        BPT_SUBSCRIPTION = 30
    }` in a .d.ts file. 

Now I when I do the first migration it all works fine. I get this line: ``type` enum ('RT_UNKNOWN', 'RT_REF_TO_PAYMENT', 'RT_REF_TO_SUBSCRIPTION', 'RT_REF_TO_TAX', 'RT_REF_TO_STORAGE', 'RT_SUBSCRIPTION_TO_PAYMENT', 'RT_SUBSCRIPTION_TO_TAX', 'RT_SUBSCRIPTION_TO_STORAGE', 'RT_PAYMENT_TO_STORAGE', 'RT_PAYMENT_TO_SUBSCRIPTION', 'RT_PAYMENT_TO_TAX', 'RT_PAYMENT_TO_REF', 'RT_STORAGE_TO_PAYMENT', 'RT_STORAGE_TO_TAX', '0', '10', '11', '12', '13', '20', '21', '22', '30', '31', '32', '33', '40', '41') NULL`

But if I change one of these values e.g. BPT_SUBSCRIPTION to BPT_SUB and then I generate a new migration it won't be reflected.

I generate migrations like this: `ts-node ./node_modules/.bin/typeorm migration:generate -n CC`

**Comment by havenchyk** [comment]
@philippfo9 please create a new issue :)
