### ISSUE TITLE
Do not generate enum values in enum columns

### ISSUE THREAD

**Issue by hillin** [typeorm/typeorm#1842]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When generating a migration, a column of `enum` type will emit an `enum` clause in the generated SQL, where both the enum keys and values are included. For instance,

```typescript
enum Colors {
  Red,
  Green,
  Blue
}

@Column("enum", { enum: Colors })
public color: Colors;
```

will emit
```sql
`color` enum('Red', 'Green', 'Blue', '0', '1', '2') NOT NULL
```
where I believe `'0', '1', '2'` is not desired in most scenarios. I hope there is at least an option to allow only generating the keys, but omitting the values.

**Comment by hillin** [comment]
Thanks, this works.

**Comment by RDeluxe** [comment]
Well, in several cases you do not want to use string enums in typescript, to reverse-select an enum value (as you can see above in the emit, `Colors[0]` will give `Red` and `Colors["Red"]` will return 0). 

I think that TypoeORM should handle non-string enums.

**Comment by gremo** [comment]
I have the same problem, using `numeric` enum: how to store only values in the column definition? Storing also the keys doesn't make any sense.

**Comment by vladimirmoushkov** [comment]
I have the same problem and I agree with @gremo - storing enum keys does not makes much sense.

**Comment by frozenex** [comment]
+1

**Comment by dilame** [comment]
+1

**Comment by pleerock** [comment]
`+1` for what? As I told this is how TypeScript behaves (read my first comment)

**Comment by havenchyk** [comment]
@frozenex @dilame it's enough to put 👍 to the first message, your comments with +1 are useless, everybody understands there is an issue, if you have any point to share, please do it, but please stop posting +1 comments.

**Comment by Hongdeshuai** [comment]
`enum UserGroupName {
  Strata = "Strata",
  Insurer = "Insurer",
  Customer = "Customer",
  Contractor = "Contractor"
}

@Entity()
export class UserGroups {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column("enum", { enum: UserGroupName })
    public name: UserGroupName;

    @OneToMany(type => Users, user => user.userGroup)
    users: Users[];

}`

This worked for me.
MySQL TypeORM, enum created in DB
