### ISSUE TITLE
[Question] Raw NOW() in repository

### ISSUE THREAD

**Issue by aschmois** [typeorm/typeorm#1848]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Is it possible to rewrite the bottom query builder using a repository? More specifically, can I do something like 
```ts
/* ... */.findOne({USER_SESSION_EXPIRE: RAW("NOW()")});
```
```ts
const userSession: UserSession = await getRepository(UserSession)
                    .createQueryBuilder("us")
                    .innerJoinAndSelect("us.USER_ID", "user")
                    .innerJoinAndSelect("user.USER_TYPE_ID", "userType")
                    .where("us.USER_SESSION_TOKEN = :token")
                    .andWhere("us.USER_SESSION_EXPIRE > NOW()")
                    .andWhere("us.DEVICE_ID = :deviceId")
                    .setParameters({ token: userToken, deviceId: res.locals.device.ID })
                    .getOne();
```

**Comment by pleerock** [comment]
Implemented it `0.2.0-alpha.38`

```ts
const loadedPosts = await connection.getRepository(Post).find({
            likes: Raw("12")
});
```

Now produces following SQL:

```sql
SELECT `Post`.`id` AS `Post_id`, `Post`.`title` AS `Post_title`, `Post`.`likes` AS `Post_likes` FROM `post` `Post` WHERE `Post`.`likes` = 12
```

Also following syntax is available for full control:

```sql
const loadedPosts = await connection.getRepository(Post).find({
            likes: Raw(columnAlias => "1 + " + columnAlias + " = 4")
});
```

which produces following query:

```sql
SELECT `Post`.`id` AS `Post_id`, `Post`.`title` AS `Post_title`, `Post`.`likes` AS `Post_likes` FROM `post` `Post` WHERE 1 + `Post`.`likes` = 4
```

Try it via `npm i typeorm@next`

**Comment by aschmois** [comment]
Awesome thanks, I hope these new features will be documented somewhere, looked around the docs for a long time with no success, but thanks again!

**Comment by pleerock** [comment]
I just implemented it, after your report. But yeah we need to document them. Feel free to contribute!

**Comment by aschmois** [comment]
Great! One question is columnAlias interpreted as likes or is that a variable defined in the scope?
