### ISSUE TITLE
simple-json default values should take Object

### ISSUE THREAD

**Issue by natew** [typeorm/typeorm#1849]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

This should work, to map to creation syntax:

```
@Entity()
export class Model {
  @Column('simple-json', { default: {} })
  values: {}
}
```

**Comment by pleerock** [comment]
`simple-json` maps to string in the database and default is sql's DEFAULT value, so you need to set a string, e.g.  `default: "{}"`

**Comment by natew** [comment]
Yea I understand, this was to open discussion of having it do a JSON.stringify if it sees an object for default, to match the way it does it when you set the value in a model.

**Comment by pleerock** [comment]
no, default is for SQL default, adding additional logic will only bring confusion.

**Comment by natew** [comment]
Ok. I felt the current state was more confusing. Because it doesn’t match
the pattern of insert type being the same as default type.

**Comment by violettomsk** [comment]
> `simple-json` maps to string in the database and default is sql's DEFAULT value, so you need to set a string, e.g. `default: "{}"`

In fact, the issue ER_BLOB_CANT_HAVE_DEFAULT is raised when I try to set default value for Json field `ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column can't have a default value`

**Comment by shinux** [comment]
Any response for this MySQL limitation ? ⤴️

**Comment by kapookchang** [comment]
It's work!!!!, Add default to "null".
```
@Entity()
export class Model {
  @Column('simple-json', { default: null })
  values: {}
}
```

**Comment by noisy** [comment]
I was able to specify empty object as default value, by modyfing manually generated migration, to have:

```
await queryRunner.query("ALTER TABLE `mytable` ADD `metadata` text NOT NULL DEFAULT ('{}')")
```

what is important, `'{}'` should be in parenthesis `('{}')`

https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html

> The default value specified in a DEFAULT clause can be a literal constant or an expression. With one exception, enclose expression default values within parentheses to distinguish them from literal constant default values. Examples:

**Comment by noisy** [comment]
Actually, definition of a column like:

```
@Column('simple-json', { default: () => "('{}')" })
metadata: {}
```

seems to generate correct migration, however what is strange, despite the fact that this migration is later applied, next make typeorm detect changes, and generate new migration, with CHANGE COLUMN, which actually produce the same definition.

**Comment by karladler** [comment]
>seems to generate correct migration, however what is strange, despite the fact that this migration is later applied, next make typeorm detect changes, and generate new migration, with CHANGE COLUMN, which actually produce the same definition.

Have the same problem here using `jsonb` type.

**Comment by ky0615** [comment]
> Actually, definition of a column like:
> 
> ```
> @Column('simple-json', { default: () => "('{}')" })
> metadata: {}
> ```
> 
> seems to generate correct migration, however what is strange, despite the fact that this migration is later applied, next make typeorm detect changes, and generate new migration, with CHANGE COLUMN, which actually produce the same definition.


TypeORM calculates the difference from the value retrieved from INFORMATION_SCHEMA.
The value of INFORMATION_SCHEMA.COLUMN_DEFAULT was retrieved and set to `_utf8mb4\'{}\'`.

```sql
SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` where TABLE_SCHEMA = 'example_db' AND TABLE_NAME = 'table';
```

Therefore, if you change the value to the following, the difference will no longer be detected

```ts
@Column({ type: 'json', default: () => "_utf8mb4\\'{}\\'" })
metadata: {}
```
