### ISSUE TITLE
Transactions across tables

### ISSUE THREAD

**Issue by laurence-myers** [typeorm/typeorm#185]
I see that you can create a transaction, which returns a single repository. What happens when I want to run a single transaction across multiple repositories? Do I just call .transaction() on each repository, and they will re-use a currently open transaction, created on the first call to .transaction()?

**Comment by dcworldwide** [comment]
I'm also unsure about how this works. I'd like to see the doco clear this up. 

I need to do something like the following:

transaction(() => {
   create X
   create Y
   update Z
})

**Comment by pleerock** [comment]
Just use `connection.entityManager.transaction(async entityManager => { ... });` and use `entityManager` passed into the function and all operations used with it will be wrapped into single transaction

**Comment by pleerock** [comment]
Example is [here](https://github.com/typeorm/typeorm/blob/master/test/functional/transaction/transaction-in-entity-manager/transaction-in-entity-manager.ts)

**Comment by dcworldwide** [comment]
Would be nice to put the example into the docs at https://typeorm.github.io/entity-manager.html#api.entityManager.transaction or possibly in it's own sub-category. I've noticed this has been a common question on reddit / github. Happy to make a PR if you can document how to manage the docs site.

**Comment by pleerock** [comment]
ya, that will be great. Just need to find a good place where it should be put in the docs

**Comment by laurence-myers** [comment]
Thanks very much! Good to know there's support. I'm also happy to help contribute documentation, even if it's documentation on "how to contribute". 😉 

As well as in the API docs, I'd recommend putting this info somewhere prominent in the README; transactions are a deciding factor when I'm looking at database/ORM libraries.

**Comment by pleerock** [comment]
any contribution is welcomed :) yeah I think docs about transactions should be added somewhere in the site

**Comment by pleerock** [comment]
I guess this topic can be closed

**Comment by pleerock** [comment]
another solution added recently is [here](https://github.com/typeorm/typeorm/tree/master/test/functional/transaction/transaction-decorator) - also needs documentation

**Comment by dcworldwide** [comment]
Clean apI nice.

**Comment by JamieCorkhill** [comment]
@pleerock 

While the `Transaction` decorator makes for a nice API, aren't we now leaking infrastructural concerns into Controller and Service Layers which should be completely DB and ORM agnostic? With that example for the Decorator, your Controllers now have a direct dependency on a TypeORM Decorator and are required to know the name of the persistence mechanism being employed.

I much prefer the approach having the domain/service/controller layer operate as if entities are stored in some in-memory collection.

**Comment by jameshmread** [comment]
If the plan for 0.4.0 (#3251 )  is to remove decorators. Shouldn't they be labelled as deprecated (or removed entirely) in documentation?
Just makes me nervous about using them.
https://typeorm.io/#/transactions/transaction-decorators
