### ISSUE TITLE
lazy loading returns NULL

### ISSUE THREAD

**Issue by hershko765** [typeorm/typeorm#1851]
**Issue type:**

[] question
[ ] bug report
[ ] feature request
[*] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
i have those entities:

**Customer**
```
@Entity('customers')
export class Customer {

    @PrimaryGeneratedColumn()
    id: number;

    @OneToMany(type => PaypersOrder, paypers_orders => paypers_orders.customer)
    paypers_orders: Promise<PaypersOrder[]>;
}
```

**Paypers Orders**
```
export class PaypersOrder {

    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(type => Customer, customer => customer.paypers_orders)
    customer: Promise<Customer>;
}
```

Following this docs:
https://github.com/typeorm/typeorm/blob/master/docs/eager-and-lazy-relations.md
(scroll down its the last lines)
i can do the following:
```
        const customers = await this.customerRepository.findOneById(1); // Verified, the entity is not empty
        const paypersOrders = await customers.paypers_orders; 
        console.log(paypersOrders); // prints null
```
according to the docs the "paypersOrders" variable should contain an array of entities, but instead it prints NULL to the console, did  i missed something? or its doc issue?

**Comment by pleerock** [comment]
Just to make sure that your issue is not related to reflect-metadata, can you please add `lazy: true` from both sides of relation:

```ts
    @ManyToOne(type => Customer, customer => customer.paypers_orders, { lazy: true })
    customer: Promise<Customer>;
```

And check it again? If issue is still reproducible then please create a minimal possible reproduction git repo which I can check. This functionality must work and test-covered.

**Comment by pleerock** [comment]
yes, in the case if you did not properly setup `reflect-metadata`. Try avoid using this option and avoid other problems you need to properly setup it (see readme). Basically you need to add 

```ts
import "reflect-metadata";
```

before anything else in your application.
