### ISSUE TITLE
Check Status of existing connection?

### ISSUE THREAD

**Issue by DR-BoneZ** [typeorm/typeorm#1853]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Question:**

Is it possible to check the status of an existing connection? I've found that getManager() works fine even of the db is down. If I try running some random query, the exception thrown isn't caught by a try catch.

**Comment by CRdeGraaf** [comment]
I believe this issue shouldnt be closed. Still no proper support for this. Even if you do con.connect() on a database that used to be online, but got killed later, i get a 'CannotConnectAlreadyConnectedError' Which is simply the wrong error thrown. Sure, TypeORM might not want to try connecting when it thinks it is still connected, but that doesnt solve the issue and doesnt make it elegant or clear.

I cant close and reopen the connection to test as it would kill running processes and i dont want to create useless superfluous testconnections with random names so all I an do now is to test live connections by running some test select query in a random interval, which is far from an elegant solution.

**Comment by CRdeGraaf** [comment]
for those looking for a solution now, like me, i wrote a typescript wrapper function for sqlite/mssql/postgres that needs minimal editing
``` TypeScript
/**
 * Connect to a database using the TypeORM ConnectionManager. Adds database to the manager if it is new. Tests database connection after connecting.
 * Reports the true current connection state regardless of:
 * - whether the connection already existed
 * - whether the database connection was lost silently after connecting previously.
 * @param database Database configuration model to try and create
 * @param stayConnected Will disconnect after testing by default. Change to true to keep the connection alive
 * @returns Whether the connection was successful
 */
export async function connect(database: ConnectionOptions, stayConnected = false): Promise<boolean> {
  let canConnect = false

  const conMan = getConnectionManager()

  try {
    let con
    if (conMan.has(database.name)) {
      // If database already exists, get it
      con = conMan.get(database.name)
    } else {
      // If connection doesnst exist, add it
      con = conMan.create(database)
    }
    // Try to connect
    if (!con.isConnected) await con.connect()
    // Store connection result
    canConnect = con.isConnected
    if (!canConnect) return false

    // If TypeORM claims a connection, test it on the test table
    try {
      const conTest = (await con.getRepository(ConnectionTest).findOne()) || new ConnectionTest(0)
      conTest.i++
      conTest.save()
    } catch (e) {
      canConnect = false
    }

    // Disconnect if it was only a test. Is default
    if (!stayConnected) await con.close()
  } catch (e) {
    console.error(e)
  }

  return canConnect
}
```

_ConnectionTest.ts model
``` TypeScript
import 'reflect-metadata'
import { Entity, PrimaryGeneratedColumn, BaseEntity, Column } from 'typeorm'

@Entity()
export class ConnectionTest extends BaseEntity {
  constructor(i: number) {
    super()
    this.i = i
  }

  @PrimaryGeneratedColumn({
    type: 'bigint',
  })
  id!: number

  @Column({
    type: 'bigint',
  })
  i!: number
}

```

**Comment by Maxvien** [comment]
This is my solution when I was working with NextJS. You can check it out!

```ts
import { createConnection, getConnection, ConnectionOptions } from 'typeorm';

import { UserEntity } from './entities/user.entity';

export async function connect() {
  const options: ConnectionOptions = {
    name: 'default',
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'test',
    password: 'test',
    database: 'test',
    synchronize: true,
    logging: false,
    entities: [UserEntity],
  };

  if (process.env.NODE_ENV === 'production') {
    try {
      return getConnection(options.name);
    } catch (error) {
      return createConnection(options);
    }
  } else {
    try {
      await getConnection(options.name).close();
      return createConnection(options);
    } catch (error) {
      return createConnection(options);
    }
  }
}
```

**Comment by segovia-no** [comment]
This was my solution to repurpose the default connection after closing it. 
```

const connName = 'default'

//set your connection options here

try {
  await getConnection(connName)
  await getConnection(connName).connect()
} catch (error) {
  await createConnection(options)
}
```

By the way, the .isConnected property shows if a connection **is initialized, not if its connected to the database**. If you use it, it might show you a TypeORM error if you try to reconnect to the database, because it has no real connection to the database.

**Comment by jlapier** [comment]
Hmm, according to [the Connection API](https://github.com/typeorm/typeorm/blob/ef209e7d9997d301b4481ee0e6a00b2b50c2c2f9/docs/connection-api.md#connection-api) isConnected tells you if there's a real connection to the database.

I have found that if the connection fails, the next time something like `connectionManager.has('default')` is called, it is true. In the scenario with something serverless like AWS Lambda, where the connection may already exist in the lambda container and you want to reuse it, "has" needs to do more than tell you the Connection _object_ exists, you need to know if it's truly connected.

Even if I call `.close()` on the connection (related: #7028), this doesn't remove it. I am using isConnected to close only if necessary. Something along the lines of:

```typescript
  connectDatabase = async (attempt: number = 1): Promise<Connection> => {
    let connection: Connection | undefined
    try {
      const connectionManager = getConnectionManager()

      // calling connection.close() doesn't actually delete it from the map, so "has" will still be true;
      // so if this is anything but the first attempt, try to create the connection again
      if (connectionManager.has('default') && attempt === 1) {
        // using a connection already connected (note this is a simplified version for lambda environment ...
        // see also: https://github.com/typeorm/typeorm/issues/3427
        connection = connectionManager.get()
        if (!connection.isConnected) throw new Error("Existing connection found but is not really connected")
      } else {
        connection = connectionManager.create(this.connectionOptions)
        await connection.connect()
      }
      return connection
    } catch (e) {
      if (attempt >= 5) {
        console.error("Giving up after too many connection attempts, throwing error")
        throw e
      }
      
      connection && connection.isConnected && connection.close()
      await sleep(100 * attempt) // back off and retry - "sleep" is just a timeout wrapped in a promise
      return await this.connectDatabase(callback, attempt + 1)
    }
  }
```
