### ISSUE TITLE
Missing import in README

### ISSUE THREAD

**Issue by MarkAdell** [typeorm/typeorm#1854]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[*] documentation issue

**Steps to reproduce or a small repository showing the problem:**

Code example in README.md: Creating and inserting a photo into the database 

this import is missing

 ```ts 
import {Photo} from "./entity/Photo"; 
```

**Comment by pleerock** [comment]
Thanks for the report! Please feel free to PR! Its much easier then creating an issue!
