### ISSUE TITLE
[Suggestion] Deprecate functions rather than delete them

### ISSUE THREAD

**Issue by aschmois** [typeorm/typeorm#1855]
**Issue type:**
[X] feature request

**TypeORM version:**
[X] `@next`

I just tried to update to @next to use a new feature that was requested and found out that findOneById no longer exists. I get that the module is alpha but it doesn't hurt to leave old methods there and redirect to a new one. Even a simple console.log("method deprecated, use X"); would be enough so that when you upgrade you can check your stuff works before changing code to the new one.

**Comment by pleerock** [comment]
yes, of course. We are planning to do so once 1.0.0 is out. `@next` is 0.2.0 in our roadmap, next we are planning 0.3.0 and then 1.0.0. We expect minimal number of changes after 0.2.0.

**Comment by pleerock** [comment]
Thanks for the suggestion.
