### ISSUE TITLE
[BUG] CURRENT_TIMESTAMP in single quotes

### ISSUE THREAD

**Issue by aschmois** [typeorm/typeorm#1857]
**Issue type:**
[X] bug report

**Database system/driver:**
[X] `mysql` / `mariadb`

**TypeORM version:**
[X] `@next`

**Steps to reproduce or a small repository showing the problem:**

Trying to create a CREATED_TIME field but when synchronizing the query is incorrect.
```js
 @CreateDateColumn({ name: "CREATED_TIME", default: () => "CURRENT_TIMESTAMP" })
    CREATED_TIME: Date;
```

```mysql
query: CREATE TABLE `transaction` (`ID` int NOT NULL, `CREATED_TIME` timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP',  /* ... */;
```

As you can see the default is 'CURRENT_TIMESTAMP' instead of just CURRENT_TIMESTAMP without quotes.

**Comment by pleerock** [comment]
We are not able to reproduce this issue. Are you sure you are using latest `@next`? If yes, then please create a minimal reproduction git repo that shows this problem.

**Comment by AlexMesser** [comment]
closed due to inactivity

**Comment by ishwar-kshirsagar** [comment]
Issue still present in 0.2.24 version.

**Comment by ishwar-kshirsagar** [comment]
Issue type:
[X] bug report

Database system/driver:
[X] mysql

TypeORM version:
[X] 0.2.24

From *.entity.ts class -

`@Column('timestamp', { name: 'created_on', default: 'CURRENT_TIMESTAMP' })
  createdOn: Date;`

This is causing same issue OP is facing even after changing syntax near default.

**Comment by haloboy777** [comment]
@ishwar-kshirsagar 
try 
`@Column('timestamp', { name: 'created_on', default: () => 'CURRENT_TIMESTAMP' }) createdOn: Date;`

**Comment by RickCole21** [comment]
maybe there is the problem.

![image](https://user-images.githubusercontent.com/19327810/147209863-6254ce88-b0b5-40cf-8cd4-434addbc38c2.png)

https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlDriver.ts#L668
