### ISSUE TITLE
Logging queries while running migrations

### ISSUE THREAD

**Issue by tonyxiao** [typeorm/typeorm#1860]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm not quite sure if this is a feature request or a question - but is there a way to get the typeorm cli to output the raw SQL queries while running migration? This seems to be the default when doing schem:sync but no logs output when running migration, even when my config has `logging` set to `true`

**Comment by pleerock** [comment]
yes I already enabled logging in `next`.
