### ISSUE TITLE
createTable.uniques doesn't work when the columnNames only has one item.

### ISSUE THREAD

**Issue by fwh1990** [typeorm/typeorm#1863]
**Issue type:**

bug report

**Database system/driver:**

`mysql`

**TypeORM version:**

`@next`

**Steps to reproduce or a small repository showing the problem:**

````js
public async up(queryRunner: QueryRunner): Promise<void> {
  const table = new Table({
    uniques: [
        {
          name: 'xx',
          columnNames: ['xx'],
        },
      ],
  });
}
````

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.44`. You can try it via `npm i typeorm@next`.
