### ISSUE TITLE
Support for de-serialization using arguments constructor or factory method

### ISSUE THREAD

**Issue by julianosam** [typeorm/typeorm#1864]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Question**
Hi. I have an entity with an arguments constructor. The constructor enforces some validation by calling the setter method for the required fields. This tries to prevent having instances of this entity in inavalid states at any given point of the execution. Problem is, during de-serialization Typeorm invokes my constructor ignoring the required arguments, causing the assertion to fail and the loading process ends unsuccessful.

So my question is: Is there a way to work around this? I would like to either register a custom Factory Method that Typeorm should use during deserialization or instruct Typeorm how to invoke my constructor passing the required arguments.

Thanks!

Here's a snippet to contextualize:

```typescript
@Entity()
class Person {

  @Column()
  private _name: string

  constructor ( name: string ) {
    this.name = name;
  }

  set name(name: string) {
    assert.ok(name, 'Persons name cannot be empty!');
    this._name = name;
  }

}

```

**Comment by pleerock** [comment]
Change your constructor to:

```ts
constructor ( name: string ) {
    this._name = name;
  }
```

and you should not get the assertion error.

**Comment by julianosam** [comment]
@pleerock Thanks for your suggestion. However, I want to have the assertion at instantiation time so to avoid creating invalid instances. If I do as you suggest, instantiations like the one below are valid:

```typescript
const p = new Person(null); // invalid, all persons should have a name
```
Looking at your suggestion, is there a way I can instruct Typeorm to invoke my constructor passing the persons name as the argument? Or alternatively, is there a way to configure a factory method that Typeorm could use during data loading?

Thanks!

**Comment by pleerock** [comment]
>  Or alternatively, is there a way to configure a factory method that Typeorm could use during data loading?

No, and I don't think there will be.

Looks like your problems with language and understanding of types with a bit of overengineering applied. 

> const p = new Person(null); // invalid, all persons should have a name

This WON'T be possible since `name: string` in your constructor does not allow you `null` values.

**Comment by julianosam** [comment]
> This WON'T be possible since name: string in your constructor does not allow you null values.
Not sure what you mean here. Just like in any other language, TS accepts null as a valid value of any type, including string. I want to prevent that by asserting a valid string was passed.

If you are talking about enabling ``strictNullChecks``, I guess that could help. However, this still:

1. Won’t prevent instantiating Person with the empty string. (also not a valid name)
2. Disables nullable fields everywhere, even for the ones that may make sense (ie non required)

Also, enabling strictNullChecks does not prevent typeorm to continue ignoring the required name argument of the constructor of my Person class anyways. Do you have any suggestions for this?

I am really trying to follow the DDD entity concept, keeping all my invariants within the entity. Having a way to customize the desserialization would be a great addition to the framework in my opinion.

**Comment by pleerock** [comment]
See it as a requirement to have constructor-less entities or a entities with optional constructor arguments. Of course we can add this feature, but it looks redundant to me in most designs. If you want to implement this functionality, im okay with it.

DDD does not enforce you to define models the way you do it. If you want a class OOP-design then I suggest you to use factory class or factory method. The fact that TypeORM won't use them isn't an issue - your model is stored the way user initialize them using factories, so mismatch is not possible.

**Comment by pleerock** [comment]
I think this can be closed.
