### ISSUE TITLE
Save method does not return column that is set with a default value

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#1869]
**Issue type:**

[ ] question
[ X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X ] `latest` (1.2.0)
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I just found that when the column is set with a default value, the `save` method does not return that column in the new object. If I set it to `nullable`, the column is included. For example, the `status` in `Post` table is defaulted to 1. After running `this.repository.save(post)`, the returned data doesn't include the status property.

````
@Entity()
export class Post {

    @IsInt()
    @Min(0)
    @Max(1)
    @Column({type: 'smallint', length: 1, default:1})
    status: number;

}
````
````
export class PostResolver {
    public constructor(
        @OrmRepository(Post) private repository: Repository<Post>) {
    }

    public upsert(post:Post){
           /..../
          let newPost = this.repository.save(post);
          // newPost.status is undefined
    }

}
````

**Comment by pleerock** [comment]
This behaviour was re-implemented in `@next` and next now returns you values from the database column DEFAULTs in the model, just like you are requesting.

**Comment by stonecold123** [comment]
@pleerock 
when will this feature be reintroduced in the stable version?

**Comment by HACHIMIam** [comment]
i still have the same issues even with @next please @pleerock  did you figure a way to make it work

**Comment by havenchyk** [comment]
@HACHIMIam if you have a similar problem, please, create another issue with an example
