### ISSUE TITLE
EntitySubscriber not firing callbacks when inserting records

### ISSUE THREAD

**Issue by madshargreave** [typeorm/typeorm#1871]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have implemented a entitysubscriber for a given entity, but when I insert records, the subscriber is not triggered

**Steps to reproduce or a small repository showing the problem:**

```ts

@EntityRepository(Trigger)
export class TriggerRepository extends Repository<Trigger> {

    async createTrigger (sourceId: string, params: Trigger) {
        return this.save({ sourceId, ...params })
    }

}


@EventSubscriber()
export class TriggerDispatcher implements EntitySubscriberInterface<Trigger> {

    listenTo () {
        return Trigger
    }

    afterInsert (event: InsertEvent<Trigger>) {
        console.log('I was triggered!')
    }

}

const sourceId = '123
const params = { ... }
getCustomRepository(TriggerRepository).createTrigger(sourceId, params) // afterInsert is not triggered
```

**Comment by madshargreave** [comment]
Scratch that. Turned out my typeorm.config was not pointing at the correct directory. My bad

**Comment by errawn** [comment]
Hello, Can I have a look how do you define your subscription property on yout typeormconfig?
