### ISSUE TITLE
Postgres - how to configure min connection & pool settings at extra option for Postgres

### ISSUE THREAD

**Issue by AlexSun98** [typeorm/typeorm#1873]
**Issue type:**

[x ] question

**Database system/driver:**
[ x] `postgres`

**TypeORM version:**
[x ] `^0.2.0-alpha.18` (  "typeorm": "^0.2.0-alpha.18",)

**Can anyone confirm if the below code is the correct one? I need to set up restriction for total number of connection per pool. so after service is up, it should only have one connection and one pool. if slave mode is enabled, I assume it should only have up to 2 connections and one pool. Thank you!**

`
  connection = createConnection({
      type: "postgres",
      synchronize: false,
      logging: true,
      extra: {
        max: 2,
        min: 1
      },
      replication: {
        master: {
          host: process.env.DatabaseMasterHost,
          port: parseInt(process.env.DatabaseMasterPort),
          username: process.env.DatabaseMasterUserName,
          password: process.env.DatabaseMasterPassword,
          database: process.env.DatabaseMasterDatabaseName
        },
        slaves: [{
          host: process.env.DatabaseSlaveHost,
          port: parseInt(process.env.DatabaseSlavePort),
          username: process.env.DatabaseSlaveUserName,
          password: process.env.DatabaseSlavePassword,
          database: process.env.DatabaseSlaveDatabaseName
        }]
      },
      entities: [
        Company,
        Product,
        Intermediary,
        Payrun,
      ]
    })
    return connection;
  }
`

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
Looks correct.

**Comment by AlexSun98** [comment]
so I will just need to add extra: { max: 2, min: 1 } as a brother of replication. My friend, I need your solid answer, haha. thanks a lot!

**Comment by dev-esakki** [comment]
I'm also facing the same issue. pool connection doesn't exist with mysql. if any suggestions please tell me how to connect or configure.

**Comment by GP4cK** [comment]
Just as a note, there's no `min` option.
Here are the docs: https://node-postgres.com/api/pool
And the [code](https://github.com/brianc/node-postgres/blob/6121bd3bb0e0e8ef8ec8ad5d02f59fef86b2f992/packages/pg-pool/index.js#L62)

However, there is a `idleTimeoutMillis` (default to 10s) after which the connection is dropped. You can set it to 0 to disable auto-disconnection.
