### ISSUE TITLE
CreateDateColumn MSSQL

### ISSUE THREAD

**Issue by ponanin** [typeorm/typeorm#1874]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

I have an entity with 
```
export class Comment {
...
@CreateDateColumn()
createdDate: Date;
}
```
And after any changes in code of this entity I get this:

```
RequestError: Column already has a DEFAULT bound to it.
...
  query: 'ALTER TABLE "comment" ADD CONSTRAINT "DF_28afb8210adb339c5d0c1935dc8" DEFAULT (getdate()) FOR "createdDate"',
  parameters: [] }
```

**Comment by pleerock** [comment]
hmm strange, can you please provide a minimal reproduction repo?

**Comment by pleerock** [comment]
Closing as no answer from reporter.
