### ISSUE TITLE
Columns Expressions are always being returned as strings by using Repository.query() method

### ISSUE THREAD

**Issue by kirliam** [typeorm/typeorm#1875]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Call Repository.query() method and with a column expression in SELECT clause. No matter what's the sql result type for the expression column, the matching JSON property will return as a string.

Example:

`repository.query("SELECT id, ID*ID AS square FROM CLIENT");`

On 0.2.0-alpha.28 version, the result was:

`[{id: 1, square: 1}, {id: 2, square: 4}]`

Now, on next version (0.2.0-alpha.42 today), the result is:

`[{id: 1, square: "1"}, {id: 2, square: "4"}]`

**Comment by pleerock** [comment]
This behaviour is caused by enabling `bigNumberStrings` option in [node-mysql](https://github.com/mysqljs/mysql#connection-options) package. Without this option set mysql returned us wrong numbers for big ints. But for some reason this option also returns string number for different operations like id*id you did. Probably it will be better if you open issue in their repo and ask them why do you have strings in there instead of numbers, Im sure they have an explanation.

**Comment by kirliam** [comment]
Hello @pleerock !
  They answered the [issue](https://github.com/mysqljs/mysql/issues/1988) I opened in [node-mysql](https://github.com/mysqljs/mysql#connection-options) package, and it's working as expected, since MySql returns BIGINT's for any expressions like the one in my example.
  IMHO, I think [bigNumberStrings](https://github.com/mysqljs/mysql#connection-options) shouldn't be enabled by default. I know you said node-mysql  package was returning wrong numbers for BIGINT's, but that should be fixed just enabling [supportBigNumbers](https://github.com/mysqljs/mysql#connection-options) option. And if that's not the case, then the issue is definitively on node-mysql package.
  If you need help, I can try to get it fixed with node-mysql guys, but I need to know the failing scenario when bigNumberStrings is not enabled.
  Thanks.

**Comment by pleerock** [comment]
> IMHO, I think bigNumberStrings shouldn't be enabled by default.

if we disable bigNumberStrings then node-mysql will return a "mixed" type - it will simply try to convert value to number - if its success - it will return a number, if its not - it will return a string. Do you understand how much confusion it will bring. 

Looks like root of issue is mysql itself - it returns bigint as results for such expressions.

**Comment by pleerock** [comment]
I think this can be closed. Feel free to continue discussion.

**Comment by sagic** [comment]
working with postgres, disabled bigNumberStrings/supportBigNumbers and still getting strings, forcing me to map all rows and convert numbers to strings. any workaround out there?

**Comment by Tyler-V** [comment]
Did any of you come up with a solution for this?

I'm experiencing this now with:

`.addSelect('COUNT(DISTINCT(users.id)) as users')`

returning

`"users": "1",`

**Comment by kirliam** [comment]
Hi @Tyler-V 
I just disabled bigNumberStrings in my project. Just put in ormconfig.json:

```
{
   "type": "mysql",
   "host": "localhost",
   ....
   "bigNumberStrings": false,
   ....
}
```

  I have a lot of complex queries, and none of them has returned number as string until now!

**Comment by Tyler-V** [comment]
Hey @kirliam thanks for that, have you noticed any unwanted side effects? I'm gonna give it a shot

**Comment by kirliam** [comment]
No, nothing!
  According to @pleerock, the problem happens when you work with very big numbers. I didn't get any use case where mysql were returning a wrong value yet, but maybe I don't have numbers big enough on my system.
  MySQL has another option if you work with big numbers: "supportBigNumbers". The "bigNumberStrings" options simply returns BIGINT and DECIMAL columns as string always! Take a look here: https://github.com/mysqljs/mysql#connection-options

**Comment by Tyler-V** [comment]
Very helpful, thanks for the resource!

**Comment by mdawsondev** [comment]
In case anyone ends up here after upgrading their typeorm package, `supportBigNumbers` and `bigNumberStrings` were both set to false by default in an older version but are now set to true (see connection-options.md [old](https://github.com/typeorm/typeorm/blob/08be75d7d5015f396cba3319f73bedf41f317991/docs/connection-options.md) vs [new](https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md)).

Setting `bigNumberStrings: false` in your `ormconfig` should correct broken code. My team found this error because `.toFixed()` was broken everywhere a decimal was being called from our MySQL database.

**Comment by deeptechuz** [comment]
> If I set `"bigNumberStrings": false,` alongside with `"synchronize": true,`, TypeORM is trying to drop some indexes, God knows why, on application start, and fails, because of foreign key constraint.
> 
> ```
> query failed: DROP INDEX `REL_04df451e741dd8172ad0f7eae8` ON `Content`
> error: { Error: ER_DROP_INDEX_FK: Cannot drop index 'REL_04df451e741dd8172ad0f7eae8': needed in a foreign key constraint
>     at Query.Sequence._packetToError (.../node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
>     at Query.ErrorPacket (.../node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
>     at Protocol._parsePacket (.../node_modules/mysql/lib/protocol/Protocol.js:278:23)
>     at Parser.write (.../node_modules/mysql/lib/protocol/Parser.js:76:12)
>     at Protocol.write (.../node_modules/mysql/lib/protocol/Protocol.js:38:16)
>     at Socket.<anonymous> (.../node_modules/mysql/lib/Connection.js:91:28)
>     at Socket.<anonymous> (.../node_modules/mysql/lib/Connection.js:502:10)
>     at Socket.emit (events.js:182:13)
>     at Socket.EventEmitter.emit (domain.js:442:20)
>     at addChunk (_stream_readable.js:283:12)
>     --------------------
>     at Protocol._enqueue (.../node_modules/mysql/lib/protocol/Protocol.js:144:48)
>     at PoolConnection.query (.../node_modules/mysql/lib/Connection.js:200:25)
>     at MysqlQueryRunner.<anonymous> (.../src/driver/mysql/MysqlQueryRunner.ts:146:36)
>     at step (.../node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:42:23)
>     at Object.next (.../node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:23:53)
>     at fulfilled (.../node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:14:58)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   code: 'ER_DROP_INDEX_FK',
>   errno: 1553,
>   sqlMessage:
>    'Cannot drop index \'REL_04df451e741dd8172ad0f7eae8\': needed in a foreign key constraint',
>   sqlState: 'HY000',
>   index: 0,
>   sql: 'DROP INDEX `REL_04df451e741dd8172ad0f7eae8` ON `Content`' }
> query: ROLLBACK
> ```

Same here is there any solution for this issue?

**Comment by brt-han-mai** [comment]
is there any way to fix this for postgres?

**Comment by wodka** [comment]
@brt-han-mai yes, you an overwrite the type parser (https://github.com/brianc/node-postgres/issues/811#issuecomment-488374261)

```
import { types } from 'pg'

types.setTypeParser(types.builtins.NUMERIC, (value: string): number => parseFloat(value))
```

**Comment by Juraj-Masiar** [comment]
Thanks @wodka , this is a great workaround! 
It wasn't working for my by BIGINT columns though, now I see I need to change the target type:
```javascript
types.setTypeParser(types.builtins.INT8, value => parseInt(value));
```

**Comment by JemarJones** [comment]
Thank you @wodka. I lost a truly ungodly amount of time debugging an issue relating to this.. oh how i wish 20 + '1' in javascript was an error instead of '201' 🤦‍♂️ ...

**Comment by dhruvv90** [comment]
Is there any solution for using with Postgresql ?
