### ISSUE TITLE
Cannot inherit Many-to-many relation from parent abstract Class on child Entities

### ISSUE THREAD

**Issue by 2xAA** [typeorm/typeorm#1876]
**Issue type:**

[*] bug report
[?] documentation issue

**Database system/driver:**

[*] `postgres`

**TypeORM version:**

[*] `latest`
Node version: 9.3.0
TypeORM version: 0.1.11

**Steps to reproduce or a small repository showing the problem:**

In the[ Entity inheritance documentation](http://typeorm.io/#/entity-inheritance) there is a line stating:
>All columns (*relations*, embeds, etc.) from parent entities (parent can extend other entity as well) will be inherited and created in final entities.

I can't get a parent entity (abstract class) to create a Many-to-many relationship on the child entity when importing the parent.

<details><summary>Example Entities (click to expand):</summary><p>

Parent Content Class
```TypeScript
import { PrimaryGeneratedColumn, Column, ManyToMany, JoinTable } from 'typeorm';
import { Favorite } from '../Favorite';

export abstract class Content {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column()
  description: string;

  @ManyToMany(type => Favorite)
  @JoinTable()
  favorites: Favorite[];
}
```

Child Audio Entity
```TypeScript
import { Entity, Column, ManyToOne } from 'typeorm';
import { Content } from './abstracts/Content';
import { User } from './User';

@Entity()
export class Audio extends Content {
  @Column({ default: 0 })
  plays: number;

  @Column({ default: false })
  frontpage: boolean;

  @ManyToOne(() => User, user => user.audios)
  user: User;
}
```

Child Visual Entity
```TypeScript
import { Entity, Column, ManyToOne } from 'typeorm';
import { Content } from './abstracts/Content';
import { User } from './User';

@Entity()
export class Visual extends Content {
  @Column({ default: 0 })
  views: number;

  @Column({ default: false })
  frontpage: boolean;

  @ManyToOne(() => User, user => user.visuals)
  user: User;
}
```

User Entity
```TypeScript
import { Entity, PrimaryGeneratedColumn, Column, OneToMany } from 'typeorm';
import { Visual } from './Visual';
import { Audio } from './Audio';
import { Favorite } from './Favorite';

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToMany(type => Visual, visual => visual.user)
  visuals: Visual[];

  @OneToMany(type => Audio, audio => audio.user)
  audios: Audio[];

  @OneToMany(type => Favorite, favorite => favorite.user)
  favorites: Favorite[];
}
```

</p></details>
<br>

Using these Entities produces this error:
```
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (/Users/***/projects/EntityInheritanceTest/src/entity/Visual.ts:7:9)
    at /Users/***/projects/EntityInheritanceTest/src/entity/Visual.ts:7:29
    at Object.<anonymous> (/Users/***/projects/EntityInheritanceTest/src/entity/Visual.ts:7:1)
    at Module._compile (module.js:660:30)
    at Module.m._compile (/Users/***/projects/EntityInheritanceTest/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/***/projects/EntityInheritanceTest/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

**Comment by pleerock** [comment]
looks like a javascript issue with circular references. Try to setup same entity structure without typeorm at all, just import same entities inside files using `import "Entity"` syntax and Im sure you'll have same error.

**Comment by 2xAA** [comment]
Okay thanks pleerock.
Do you have any suggestions on how I can refactor so I'm able to use a base Content class as an import (without cyclic imports)?

The examples in the Documentation for an abstract class seem to all be in one file, which is undesirable.

**Comment by pleerock** [comment]
The examples in the Documentation are just shortest way to show you examples, they are not suppose to be in a single file. I recommend you to use separate file for each your entity class.

**Comment by pleerock** [comment]
Looks like the issue was resolved.
