### ISSUE TITLE
Constraint unique for relations problem

### ISSUE THREAD

**Issue by vecheslav** [typeorm/typeorm#1877]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[ ] `latest`
[x] `@next`

**Description:**

I have an entity
```
@OneToOne(type => Ent, ent => ent.auction, {
    cascade: ['insert', 'update']
  })
  @JoinColumn()
  ent: Ent;
```
and i got `error QueryFailedError: duplicate key value violates unique constraint "REL_daf24ebe8d9c365f317d5f1983"` because relation column is unique.

Why did you begin to add `unique` for relation columns?
How can i remove `unique` option?

**Comment by pleerock** [comment]
Correct, we added unique since one-to-one means that this entity has a relation with only ONE another relation, which means both sides of relations are unique. Im sure you have this issue because you should use many-to-one for your use case.

**Comment by vecheslav** [comment]
@pleerock thank you. but i still have problem with save my entities.
i have two entities:
```
@Entity()
export class Auction {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(type => Ent, ent => ent.auction, {
    cascade: ['insert', 'update']
  })
  @JoinColumn()
  ent: Ent;

  @Column()
  start_price: string;

  @Column()
  end_price: string;

  @Column({
    nullable: true
  })
  status: number;

  @Column()
  type: number;

  @ManyToOne(type => User)
  @JoinColumn()
  seller: User;
}
```
```
@Entity()
export class Ent {
  @PrimaryColumn()
  id: number;

  @ManyToOne(type => User)
  @JoinColumn()
  owner: User;

  @Column({
    nullable: true
  })
  name: string;

  @OneToOne(type => Auction, auction => auction.ent, {
    nullable: true
  })
  auction: Auction;

  // Dates
  @CreateDateColumn()
  created_at: Date;
}
```

and i can't save their in the same time.
code of save auction:
```
let ent = await this.entsService.findById(entId);
if (!ent) {
  ent = Object.assign({}, {
    id: entId,
    owner: seller
  });
}
const newAuction = Object.assign({}, {
  ent,
  ...
  seller
});
const auction = await this.auctionsService.save(newAuction);

const savedEnt = await this.entsService.findById(entId);
savedEnt.auction = auction;
await this.entsService.save(savedEnt)
```
and code of save ent:
```
const newEnt = Object.assign({}, {
  id,
  owner,
  ...
});
const ent = await this.entsService.save(newEnt);
```

As a result, I get an error:
```
ERROR:  duplicate key value violates unique constraint "PK_13dfc272b5d9ba4fc2efa1b7ecc"
DETAIL:  Key (id)=(103) already exists.
```

**Comment by pleerock** [comment]
Inverse side must be one-to-many. Please read more about relations.

**Comment by vecheslav** [comment]
@pleerock Can there be a problem with saving call (cascades & just ent save) at one time? one-to-many not resolve this problem.
```
auctionsService.save(newAuction) ---check exist---->save ent------>save auction
this.entsService.save(newEnt) ------check exist--------->(error)-->not update ent
```

**Comment by pleerock** [comment]
Please create a PR with a failing test and I'll review it and fix the issue if there is an issue.

**Comment by robbyemmert** [comment]
I'm getting a similar issue--may be related.

Here are my entities:
```
@Entity()
export class ServiceForm extends BaseModel {
    @OneToOne(type => Service)
    @JoinColumn()
    service: Service

    @ManyToOne(type => Form)
    form: Form

    @OneToMany(type => ServiceField, field => field.form)
    fieldOverrides: ServiceField[]
}

import { BaseModel } from "models/base";
import { Column, Entity, ManyToOne, OneToOne, JoinColumn, OneToMany, JoinTable } from "typeorm";
import { ServiceType } from "./service-type";
import { Country } from "app/country/models/country";
import { ServicePricing } from "./service-pricing";
import { ServiceForm } from "./service-form";

@Entity()
export class Service extends BaseModel {
    @ManyToOne(type => ServiceType, serviceType => serviceType.services, {
        eager: true
    })
    type: ServiceType

    @Column(type => Country)
    country: Country

    @Column({
        type: 'text',
        default: ''
    })
    notes: string

    @Column({
        type: 'boolean',
        default: false
    })
    active: boolean

    @Column(type => ServicePricing)
    pricing: ServicePricing

    @OneToOne(type => ServiceForm, serviceForm => serviceForm.service)
    intakeForm?: ServiceForm
}
```

Here's the error I'm getting:
```
query failed: CREATE TABLE "service_form" ("id" SERIAL NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "serviceId" integer, "formId" integer, CONSTRAINT "REL_27d27dca0e7c48ff691f44d861" UNIQUE ("serviceId", "serviceId"), CONSTRAINT "PK_5fc7ce95ffcc2fec0e109bfcda6" PRIMARY KEY ("id"))
error: { error: column "serviceId" appears twice in unique constraint
```

Notice the `UNIQUE ("serviceId", "serviceId")` clause in the SQL. Why is the column getting entered twice?

Thanks in advance!

**Comment by P0oOOOo0YA** [comment]
I'm using TypeORM with SQLite and cascade doesn't work when UPDATING. Have not test DELETING but INSERTING works as expected. In my case it throws UNIQUE Constraint error when i want to update using cascade which means TypeORM is inserting when it should update.

**Comment by leonardofalk** [comment]
I ran into this one, the problem was `Object.assign`, it overrides nested relations instance with Object class. At first glance I thought I should use ObjectUtils.assign from `typeorm/util/ObjectUtil`, but it doesn't look for nested record attributes either. Using ActiveRecord pattern, I was able to create a method to safely assign attributes, it's pretty much error prone and can be optimized, but it works.

```tsx
import { BaseEntity } from 'typeorm'
import _ from 'lodash'

class AbstractModel extends BaseEntity {
  /**
   * Safely assign attributes for the model instance
   */
  public assignAttributes(props: any) {
    const constructors = _.keyBy(this.constructor.getCascadeRelations(), 'propertyName')

    for (const prop of Object.getOwnPropertyNames(props)) {
      const relation = constructors[prop]

      if (relation && this[prop]) {
        if (_.isArrayLike(this[prop])) {
          const pks = relation.entityMetadata.primaryColumns.map(c => c.propertyName)

          for (const nestedProps of props[prop]) {
            const childIndex = _.findIndex(this[prop], object =>
              _.every(pks.map(pk => nestedProps[pk].toString() === object[pk].toString()))
            )

            if (childIndex >= 0) {
              this[prop][childIndex].assignAttributes(_.omit(nestedProps, pks))
            } else {
              this[prop].push(nestedProps)
            }
          }
        } else {
          this[prop].assignAttributes(props[prop])
        }
      } else {
        this[prop] = props[prop]
      }
    }
  }
}

AbstractModel.getRelations = function() {
  return this.getRepository().metadata.relations
}

AbstractModel.getCascadeRelations = function() {
  return this.getRelations().filter((rel: any) => rel.isCascadeInsert || rel.isCascadeUpdate || rel.isCascadeRemove)
}

```

Then

```tsx
class Model extends AbstractModel {
  ...
}

const record = new Model()
record.assignAttributes({ ... })
record.save()
```

Notice that I'm not doing anything for ManyToOne relations in this scenario, so it could break for other scenarios.

I'm not sure about other JS libraries but Rails' ActiveRecord does this check and updates newly objects that have a primary key attribute.

**Comment by aldarund** [comment]
What about onetoone situation with nullable column e.g. its optional onetoone? It still endsup with unique contstraint, which wont work since there can be many columns on which relation not set. How to deal with this ?

**Comment by csgruenebe** [comment]
So I ran into this issue as well and it really bugged me out.
I came to the realization, that the **JoinColumn annoation was at the wrong side** in my case.

I had

```
class User {
  @OneToOne(type => Photo, p => p.user })
  @JoinColumn() // <------- produced the error
  photo: Photo;
}
class Photo {
  @OneToOne(type => User, u => u.photo })
  user: User;
}
```

And that helped:

I had

```
class User {
  @OneToOne(type => Photo, p => p.user })
  photo: Photo;
}
class Photo {
  @OneToOne(type => User, u => u.photo })
  @JoinColumn() // <------- works
  user: User;
}
```

But It might be a different case but in our case the `userId` was a column in the photo table.
So that worked for us :)

**Comment by abbbel2** [comment]
> So I ran into this issue as well and it really bugged me out.
> I came to the realization, that the **JoinColumn annoation was at the wrong side** in my case.
> 
> I had
> 
> ```
> class User {
>   @OneToOne(type => Photo, p => p.user })
>   @JoinColumn() // <------- produced the error
>   photo: Photo;
> }
> class Photo {
>   @OneToOne(type => User, u => u.photo })
>   user: User;
> }
> ```
> 
> And that helped:
> 
> ```
> class User {
>   @OneToOne(type => Photo, p => p.user })
>   photo: Photo;
> }
> class Photo {
>   @OneToOne(type => User, u => u.photo })
>   @JoinColumn() // <------- works
>   user: User;
> }
> ```
> 
> But It might be a different case but in our case the `userId` was a column in the photo table.
> So that worked for us :)

Thanks man, this works for me

**Comment by abbbel2** [comment]
> So I ran into this issue as well and it really bugged me out.
> I came to the realization, that the **JoinColumn annoation was at the wrong side** in my case.
> 
> I had
> 
> ```
> class User {
>   @OneToOne(type => Photo, p => p.user })
>   @JoinColumn() // <------- produced the error
>   photo: Photo;
> }
> class Photo {
>   @OneToOne(type => User, u => u.photo })
>   user: User;
> }
> ```
> 
> And that helped:
> 
> ```
> class User {
>   @OneToOne(type => Photo, p => p.user })
>   photo: Photo;
> }
> class Photo {
>   @OneToOne(type => User, u => u.photo })
>   @JoinColumn() // <------- works
>   user: User;
> }
> ```
> 
> But It might be a different case but in our case the `userId` was a column in the photo table.
> So that worked for us :)

Thanks man, this works for me

**Comment by AlexMesser** [comment]
Closing as answered.

**Comment by andyslack** [comment]
I had the same problem and this helped me realise it should have been a @ManyToOne not @OneToOne

**Comment by ayaankhan98** [comment]
> Correct, we added unique since one-to-one means that this entity has a relation with only ONE another relation, which means both sides of relations are unique. Im sure you have this issue because you should use many-to-one for your use case.


How can we handle a situation like where I want one side as oneToOne and other side as oneToMany?
Suppose I have two entities `User` and `Role` and I want to have a relationship - a user can have only one role but a role can belong to multiple users.

**Comment by sitoftonic** [comment]
@ayaankhan98 You don't need to have 2 different relation cardinalities. You are describing a 1:N relationship between roles and users. 1 role might have N users, but N users only can have 1 role. In this case, the PK of role should then go as an FK to user. This way, a User can only have 1 role (specified by the FK role_id) and N users can have this same role associated without problems.

In the User entity you should put ManyToOne relation referencing role and keep OneToMany in Role entity referencing users.
