### ISSUE TITLE
removeConnection or disconnect functionality

### ISSUE THREAD

**Issue by natew** [typeorm/typeorm#1879]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Feature**

Basically, want to be able to disconnect. Seems like this isn't exposed by connection manager. Use case is using the cordova driver, sometimes the server side will go down and come back up causing the database list to be reset. That returns an error to the client (no dbname found). At that point I'd want to reconnect from the client, but I can't because client says "connection already open for name default".

**Comment by pleerock** [comment]
Try `connection.close()` method
