### ISSUE TITLE
Foreign key without relation

### ISSUE THREAD

**Issue by CocaColaBear** [typeorm/typeorm#188]
How I can create entity with foreign key without relation?
Sample entity:
```
@Table("post")
export class Post {
	@PrimaryGeneratedColumn()
	id: number;

	@Column("bigint")
	authorFk: number; // this field should be foreign key

	author: Author;
}
```
It needs, because I'm know authorId, but I do not want to do 'SELECT' for get Author entity for create Post. Example:
```
...
let newPost = new Post();
newPost.authorFk = authorId;
...
this.Repository.persist(newPost);
...
```
In database authorFk isn't foreign key.

P.S. Entities are invented for the example

**Comment by pleerock** [comment]
as I understood you don't want to execute extra "SELECT" queries when entity is persisted.

This should happen only on inverse side of relation, right? (e.g. `@OneToOne` WITHOUT join column or `@OneToMany` side).

No, there is no way no make a column a foreign key but don't without relation.

However if you are worrying about extra query - don't worry. Im planning to introduce extra option to relation decorators that will make this relation prevent for updating, e.g.  something like this:


```typescript
@OneToMany(type => Post, { skipPersistment: true })
post: Post;
```

**Comment by vuonghv** [comment]
I'm implement Restful APIs using TypeORM for my project. And I have to directly handle many Foreign IDs in create/update actions. So I think it is awesome to support a way to directly manipulate foreign keys in the TypeORM. I agree with @CocaColaBear .

And thank you for your hard works.

**Comment by pleerock** [comment]
As I promised new flag in relation options was introduced: `{ persistence: false }`. You can use it to prevent any extra queries for relations checks. This is avalible from 0.2.0-alpha versions. You can try it in `npm i typeorm@next`. I think I'll close this issue now.
