### ISSUE TITLE
SQLITE_CONSTRAINT: NOT NULL constraint failed: temporary_*

### ISSUE THREAD

**Issue by natew** [typeorm/typeorm#1880]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Need to figure out whats causing it, as it comes up 2-3 times a day during some sort of restart or interrupt scenario. We restart the server on save, and sometimes coming back online this error comes up.

It must be a data corruption issue as well as once it happens it doesn't go away. Happy to try and number of queries to debug it.

Not sure if this could be the case, but we connect to the same database from the browser via cordova plugin. Perhaps it's not finishing some transaction and leaving database in bad state?

**Comment by pleerock** [comment]
Its a duplicate that was already fixed. Please use `@next` where this issue is already resolved.

**Comment by natew** [comment]
@pleerock Cool, thanks for the help & love what you're doing w this.

Not sure if you care for bug reports on @next, but ran into a couple on `0.2.0-alpha.42`. Basically seems like simple-json is breaking. This line:

![image](https://user-images.githubusercontent.com/12100/38320873-a52ddd34-37ea-11e8-90ab-e8ded558d56d.png)

Gets an actual JSON object sometimes, and then breaks trying to parse it. Seeing if I can replicate on master.

**Comment by pleerock** [comment]
> Not sure if you care for bug reports on @next

of course I do care. Please report those issues and feel free to contribute, contributions are very valuable.
