### ISSUE TITLE
leftJoinAndMapOne does not add target property to entity

### ISSUE THREAD

**Issue by madshargreave** [typeorm/typeorm#1882]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a Source model which can have many Job models

I want to fetch a given source, and together with the most recently created job.

I use this query:

```ts
this
            .createQueryBuilder('source')
            .leftJoinAndMapOne('lastJob', subQuery => {
                return subQuery
                    .select()
                    .from(Job, 'job')
                    .orderBy('"createdAt"', 'DESC')
            }, 'job', 'job."sourceId" = source.id')
            .where('source.id = :id', { id })
            .getOne()
```

The above will return the Source, but without the `lastJob` property

If I you `getRawOne`

It returns the source properties together with the job properties, but they're not scoped under `lastJob`

Any ideas?

**Comment by pleerock** [comment]
Looks like the issue was resolved. Reopen if needed.

**Comment by FFsim** [comment]
same problem with code:

const users = await this.repository.createQueryBuilder("user")
      .leftJoinAndMapOne("user.lastPurchase", (subQuery) => {
        return subQuery
          .select()
          .from(Purchase, "purchase")
          .orderBy("created", "DESC");
      }, "purchase", "purchase.userId = user.id")
      .leftJoinAndSelect("user.merchant", "merchant")
      .where("user.role IN (:userRoles)", {userRoles: roles})
      .getManyAndCount();

any idea?

**Comment by Rishav78** [comment]
I'm facing the same problem any idea how to resolve this?

```
const user = await getManager()
      .getRepository(User)
      .createQueryBuilder("user")
      .leftJoinAndMapOne(
        "user.image",
        qb => qb.from(File, "files"),
        "files",
        '"user"."uid" = "files"."owenerId"'
      )
      .where("user.uid = :uid", {uid})
      .getOne()
```

**Comment by ICEDLEE337** [comment]
@Rishav78 can't u do something like this instead (provided that the two tables are related)
```
      const user = await getRepository(User).findOne({
        where: { uid },
        relations: ['files'], // one to many assumption here mera dost ;)
      })
```

**Comment by wi-ski** [comment]
Still an issue in 2021

**Comment by nlucero** [comment]
@pleerock Can we reopen this issue? This is still a problem. `leftJoinAndMapOne` generates a correct query but won't map the result to the entity when using the signature that [accepts a subquery](https://github.com/typeorm/typeorm/blob/b0c1cc6d6820e93bc7b986d4f18db4020195e170/src/query-builder/SelectQueryBuilder.ts#L560).

**Comment by zhepa** [comment]
Found a workaround, let's assume that you have join like this
```js
.leftJoinAndMapOne('order.firstOrderId',
  qb => qb.select('created_by, min(id) as first_order_id')
    .from(Order, 'n2')
    .groupBy('created_by'),
  'fo', 'fo.created_by = order.created_by'
)
```

So you need to get raw results and mapped entities via `.getRawAndEntities()` and map custom properties manually:
```js
const { entities, raw } = await query.getRawAndEntities();

return entities.map((entity, index) => {
  entity.firstOrderId = raw[index].first_order_id;
  return entity;
});
```

The solution is not clean, you still can't combine it with count query, but this is the less painful way to achieve a result

Don't forget to add your custom properties in `@Entity()`

**Comment by prateekkathal** [comment]
@pleerock @AlexMesser @imnotjames @daniel-lang Tagging you guys cause this was closed by mistake I feel. Not sure who else to tag to get this issue to re-open. The issue still exists I feel. When we use subQuery, it doesn't map and resolve. There is no mention of this in the documentation as well. 

I am trying to do something like

```ts
const [venues, venuesCount] = this.venuesRepository
  .createQueryBuilder("Venue")
  .leftJoinAndSelect("Venue.city", "city")
  .leftJoinAndMapOne(
    "Venue.eventStats",
    (qb) =>
      qb
        .from("events", "Event")
        .select('"venueId"')
        .addSelect(`MAX("capacity")`, "maxVenueCapacity")
        .addSelect(`COUNT("venueId")`, "eventsCount")
        .groupBy('"venueId"'),
    "Event",
    "Venue.id = Event.venueId"
  )
  .where(`Venue.cityId = :cityId`, { cityId: "someCityId" })
  .orderBy(`eventCount`, `DESC`)
  .getManyAndCount();
```

And my model has 

```
interface EventStats {
  maxVenueCapacity: number;
  eventsCount: number;
}

@Entity()
class Venue {
  eventStats: EventStats;
}
```

Can this issue please be looked into?

**Comment by imnotjames** [comment]
Looks like a slightly different issue.  Try opening a new issue instead.
