### ISSUE TITLE
Doubt about 2 cascades simultaneously

### ISSUE THREAD

**Issue by jondediego** [typeorm/typeorm#1885]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.1.20` (or put your version here)

Hi, we are experiencing some problems saving on a table A that inserts or updates with cascade to another table B, that also inserts or updates by cascade into another table C. ¿Should this situation work?
When table C is empty it works properly, but when it has some data, save finnishes correctly, but data stored in table C is not the expected. Because the relations between C and B are wrong.
Table A:
 ```ts
@Entity("MaintenanceForm")
export class MaintenanceForm  {

    @PrimaryGeneratedColumn()
    public id: number;

    @Column("varchar")
    public name: string


    @OneToMany(type => MaintenanceFormSelectionField, maintenanceFormSelectionField => maintenanceFormSelectionField.maintenanceForm, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    public maintenanceFormSelectionField: MaintenanceFormSelectionField[];

} ```

Table B:
 ```ts 
@Entity("MaintenanceFormSelectionField")
export class MaintenanceFormSelectionField  {
    @PrimaryGeneratedColumn()
    public id: number;

    
    //Relations
    @ManyToOne(type => MaintenanceForm, maintenanceForm => maintenanceForm.maintenanceFormSelectionField)
    public maintenanceForm: MaintenanceForm;


    @OneToMany(type => SelectionFieldEntry, selectionFieldEntry => selectionFieldEntry.maintenanceFormSelectionField, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    public selectionFieldEntries: SelectionFieldEntry[];
} ```
Table C:
```ts 

@Entity("SelectionFieldEntry")
export class SelectionFieldEntry  {
    @PrimaryGeneratedColumn()
    public id: number;

    @ManyToOne(type => MaintenanceFormSelectionField, maintenanceFormSelectionField => maintenanceFormSelectionField.selectionFieldEntries, { nullable: false })
    public maintenanceFormSelectionField: MaintenanceFormSelectionField;

} ```

**Comment by pleerock** [comment]
Try your issue on `@next` (npm i typeorm@next) - lot of fixes regarding to cascades in there.

**Comment by Kononnable** [comment]
Closing as no response from the author.
