### ISSUE TITLE
how to use method findDescendantsTree in treerepository-api

### ISSUE THREAD

**Issue by kaimiyang** [typeorm/typeorm#1888]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

[doc link](http://typeorm.io/#/repository-api/treerepository-api), below code, is `parentCategory` an entity ? how to use?
```
const childrensTree = await repository.findDescendantsTree(parentCategory)
```

**Comment by pleerock** [comment]
Get entity you need (using find methods lets say). Then get all its descendants using this method.

**Comment by pleerock** [comment]
Answer was given. Let me know if you still have questions.
