### ISSUE TITLE
MySql - Transaction rollback not work with QueryRunner.query

### ISSUE THREAD

**Issue by Giancarlo1974** [typeorm/typeorm#1891]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

i'm using Node js and MySql

Given

`
		// get a connection and create a new query runner

	const runner: QueryRunner = await getConnection('testdb').createQueryRunner();

	// establish real database connection using our new query runner

	await runner.connect();

	// lets now open a new transaction:

	await runner.startTransaction();

	await runner.query(`SET autocommit=0;`);

	const sql = '

	   insert into test (
		   a
	   ) values(
		   ?
	   )

	';
	
	const param = ['hi'];
	// it inserts the record
	const res = await runner.query(sql, param);
	// it doesn,'t cancel :-(
	await runner.rollbackTransaction();
`

I have created the table in this mode:

CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `a` char(6) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

Got

`
	[Node] [17:16:30] executing query:  START TRANSACTION

	[Node] [17:16:30] executing query:  SET autocommit=0;

	[Node] [17:16:30] executing query:

	[Node]            insert into test (

	[Node]                a

	[Node]            ) values(

	[Node]                ?

	[Node]            )

	[Node]         -- PARAMETERS: ["hi"]

	[Node] [17:16:30] executing query:  ROLLBACK

`

apparently everything was done to perfection, but when I check that the table is empty, I see that the record has been recorded

**Comment by Giancarlo1974** [comment]
[MyISAM doesn't support rollback](https://stackoverflow.com/questions/8036005/myisam-engine-transaction-support)

**Comment by pleerock** [comment]
Not sure if I completely got your problem, but looks like you resolved it?

**Comment by Kononnable** [comment]
Closing as no response from the author.
