### ISSUE TITLE
Postgres creating stored procedures from migrations and calling them?

### ISSUE THREAD

**Issue by jkirkby91-2** [typeorm/typeorm#1893]
**Issue type:**

[ X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Not a bug, but I am using postgres and cant see any documentation on postgres stored procedures/ functions. I'm looking for, how to call them and create the procedures during a migration.

I have a procedure that creates a timestamptz (timestamp with timezone) for when a entity is created and updated, any example on how to do this?

**Comment by pleerock** [comment]
Its a specific functionality and specific functionality must be used... specific way. To create a procedure you need to use a `query` method that executes raw queries. To insert or update can try to use `insert` and `update` methods of repository which are able to do following:

```ts
repository.insert({
      ...,
      myDate: () => `` // RAW SQL, you'll be able to use your procedure
})
```

It should work in most scenarios, but for some you'll still need to use `query` method.

**Comment by pleerock** [comment]
Let me know if you still have questions.

**Comment by hypeofpipe** [comment]
Is there any way to create stored procedures right in the migrations with TypeORM?
