### ISSUE TITLE
Unable to create schema on startup for postgres

### ISSUE THREAD

**Issue by james-love** [typeorm/typeorm#1894]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Upgraded project to 0.2.0-alpha.42 in order to fix an issue that typeorm had with handling timestamps. 

Our development process involves dropping our schema before anything else. With the version we were using (0.1.20) it was able to create the schema on startup. 

However, after the upgrade it logs an error on startup saying that the schema does not exist when attempting to add tables to the schema; which it had previously created before attempting to add the tables.

[Here's a sample of the issue occurring.](https://github.com/james-love/typeorm-upgrade-issue) You can use the same repo and change the typeorm version back to 0.1.20 and it will work correctly.

Has something changed for this version that I will need to change in the code? 

For clarity on what I mean by all of this, here are the situations and results of those situations:

| Typeorm Version | Schema Status On Startup |    Result    |
|:---------------:|:------------------------:|:------------:|
|      0.1.20     |          exists          |     works    |
|      0.1.20     |       doesn't exist      |     works    |
|  0.2.0-alpha.42 |          exists          |     works    |
|  0.2.0-alpha.42 |       doesn't exist      | doesn't work |

**Comment by james-love** [comment]
After more testing it seems the change that is causing this issue was implemented by version 0.2.0-alpha.25. Unfortunately the fix we need for timestamps was implemented by 0.2.0-alpha.29.

It appears to have been caused by [this](https://github.com/typeorm/typeorm/commit/20c5552c0444c9ae29f4ff1416b6bc09e35dec18#diff-7d3099dfa30069700ce352382d82ce88) commit (I think.) 

Is there a reason why the createNewSchemas function has been removed from the RdbmsSchemaBuilder? Is creating the schema at the start when synchronize is enabled no longer a feature of typeorm? Or perhaps it is implemented now in a different way?

**Comment by pleerock** [comment]
It was design decision. Schema creation is not ORM responsibility, its a database administrator responsibility. If we return it back users who don't have a schema creation privileges will face a critical issue of impossibility of running application using TypeORM even if schema exist for them.

**Comment by wiltonpolesca** [comment]
I agree that this responsibility is from DBA, but, a lot of times, we are working on a project that doesn't have DBA or a TI to take care the data, sometimes the project will be run at  AWS and the possibility to create the schema help us a lot.

Please, think about put available the possibility to enable or not this option, by config files or a parameter at connection manager...

Thanks!

**Comment by rsercano** [comment]
+1

> I agree that this responsibility is from DBA, but, a lot of times, we are working on a project that doesn't have DBA or a TI to take care the data, sometimes the project will be run at AWS and the possibility to create the schema help us a lot.
> 
> Please, think about put available the possibility to enable or not this option, by config files or a parameter at connection manager...
> 
> Thanks!
