### ISSUE TITLE
Transaction Management using CLS (Continuation Local Storage)

### ISSUE THREAD

**Issue by nicomouss** [typeorm/typeorm#1895]
Please find below an implementation of transaction management using CLS (Continuation Local Storage). This implementation uses [cls-hooked](http://github.com/jeff-lewis/cls-hooked) library.

This is the approach I use to manage transactions using a DDD (Domain Driven Design) architecture, where we organise our code through Application, Domain, and Infrastructure layers.

Suppose you are writing an app using Express:

```javascript
// Index.ts
import { createNamespace, getNamespace } from "cls-hooked";
import * as express from "express";
import {createConnection} from "typeorm";

// Create CLS namespace
let context = createNamespace("__cls__context");

// ...

// create typeorm connection
createConnection().then(connection => {
    // create and setup express app
    const app = express();

    // Wrapping up things with run() function to set up a specific
    // context for each incoming HTTP request
    app.use(function(req, res, next) {
	context.run(() => next());
    });
    
    // An example route calling an application service
    app.post("/CreatePhotos", async function(req: Request, res: Response) {

        // Let's says you manage your app components (or services depending on how you
        // name them) through an IoC Container you had set up at application bootstrap.
        // All your components (services) are singletons in memory.

        // You then request your application service from your IoC Container
        let managePhotosService = 
             Container.get<ManagePhotosService>("Application.ManagePhotosService");

        // You call a method on your service. This method has to be transactional.
        await managePhotosService.CreatePhotos();

        // ...

    });

    // start express server
    app.listen(3000);
});
```

In an Transaction.ts file, declare a custom Transaction decorator:

```javascript
import { getConnection, getManager } from "typeorm";
import { getNamespace } from "cls-hooked";

export function Transaction(connectionName: string = "default"): MethodDecorator {
    return function (target: Object, methodName: string, descriptor: PropertyDescriptor) {

        // save original method - we gonna need it
        const originalMethod = descriptor.value;

        // override method descriptor with proxy method
        descriptor.value = function(...args: any[]) {
            return getConnection(connectionName).transaction(async entityManager => {
                    
                    let context = getNamespace("__cls__context");

                    if (!context) {
                        // This will happen if no CLS namespace has been initialied in your app.
                        // At application startup, you need to create a CLS namespace using createNamespace(...) function.
                        throw new Error("No CLS namespace defined in your app ... Cannot use CLS transaction management.");
                    }

                    if (!context.active) {
                        // This will happen if your code has not been executed using the run(...) function of your CLS
                        // namespace.
                        // Example: the code triggered in your app by an entry HTTP request (or whatever other entry event, 
                        // like one triggered by a message dropped in a queue your app is listening at), should be wrapped 
                        // using the run(...) function of your CLS namespace.
                        // Using run(...) ensures that an active context is set, where you can safely store and retrieve
                        // things.
                        throw new Error("No CLS active context detected ... Cannot use CLS transaction management.")
                    }

                    // From here everything is OK to use CLS to manage our transaction.

                    // We store the EntityManager managing our current transaction.
                    context.set("__typeOrm__transactionalEntityManager", entityManager);

                    // We can now call the function that had been decorated with the Transaction decorator.
                    var result = await originalMethod.apply(this, [...args]);

                    // We just finished working with the EntityManager managing our transaction: we remove it
                    // from the current context.
                    context.set("__typeOrm__transactionalEntityManager", null);

                    return result;

                });
        };

    };
}

```

Now your service will look like:

```javascript
// Application/ManagePhotosService.ts
export class ManagePhotosService {

    private _photoRepository: IPhotoRepository;

    // Repository automatically injected by IoC Container here when the service
    // is requested. Our repository is a singleton in memory.
    constructor(
        @Inject("Repositories.PhotoRepository") photoRepository: IPhotoRepository
    ) {
        this._photoRepository = photoRepository;
    }

    @Transaction()
    public async CreatePhotos() {
        
        let photo1 = new Photo(
           "Photo_1", "Bla bla bla", "Photo1.jpg", false);
        
        let photo2 = new Photo(
            "Photo_2", "Bla bla bla", "Photo2.jpg", false);
        
        let photo3 = new Photo(
            "Photo_3", "Bla bla bla", "Photo3.jpg", false);
        
        // Saving the photos
        await this._photoRepository.SavePhoto(photo1);
        await this._photoRepository.SavePhoto(photo2);
        await this._photoRepository.SavePhoto(photo3);
        
    }

}

```

Your PhotoRepository will be implemented that way:

```javascript
// Domain/Repositories/IPhotoRepository.ts
export interface IPhotoRepository {
    
    SavePhoto(photo: Photo): Promise<Photo>;

}

// Infrastructure/Repositories/PhotoRepository.ts
export class PhotoRepository extends BaseRepository implements IPhotoRepository {

    public async SavePhoto(photo: Photo): Promise<Photo> {

        // Persisting the photo ...
        return await this.EntityManager.save(photo);

    }

}
```

Your BaseRepository class that all your repositories must extend:

```javascript
// Infrastructure/Repositories/BaseRepository.ts
import { EntityManager, getManager } from "typeorm";
import { getNamespace } from "cls-hooked";

export abstract class BaseRepository {

    protected get EntityManager(): EntityManager {

        let context = getNamespace("__cls__context");

        if (context && context.active) {

            let transactionalEntityManager = context.get("__typeOrm__transactionalEntityManager");

            if (transactionalEntityManager) {
                
                // At this point here we have successfully found a transactional EntityManager 
                // that was previously saved within the current context.
            
                // We now use this EntityManager to work.
                return transactionalEntityManager;

            }

        }

        // No specific transactional EntityManager has been found : we use the global EntityManager to work.
        return getManager();

    }

}
```

This implementation could be easily integrated within typeorm core. Using CLS storage internally, typeorm would make any call to getManager() transparently return the proper EntityManager to use in the repositories. Had a transaction been started upstream or not.

That way no need to deal with repositories turning non-singletons when they are used in a transaction, or no need to pass the transactionnalEntityManager down the road to repositories.

**Comment by pleerock** [comment]
I think you should consider creating a separate lib for this purpose. I don't really like Transaction decorators being in typeorm core currently and have plans to remove it. Those decorators are very specific and does fit only some architectures and should not be in the core.

**Comment by nicomouss** [comment]
My point was actually not regarding Transaction decorators to be stored in TypeOrm core.
It was about TypeOrm to use CLS to internally store the current EntityManager (ie. the global one or a transactionnal one). So that any call to getManager() would return the proper EntityManager to use.
This way of doing could be enabled or not by config.
That way we can create custom repositories that are singletons, as shown in the example above. These repositories just call getManager() to work, and TypeOrm gives them the proper EntityManager to work with.

**Comment by pleerock** [comment]
I don't see a place for this inside typeorm.

What I can suggest you is to use `scoped services` of typedi. With scoped services you can create a transaction-per-request and use same transaction manager instance across all services without having to pass it around. I implemented this approach in [vesper framework](https://github.com/vesper-framework/vesper).

**Comment by nicomouss** [comment]
Sure Umed, my post here regarding transaction management using CLS was following #404. It works well for me so far and leads to clean code, so am happy with that.
Will check your implementation using typedi and scoped services within Vesper. Thanks for info.

**Comment by pleerock** [comment]
Its great if you already use it and it works fine. I'll close this issue and if it gets more attention from the community we will return back to this question.

**Comment by nolazybits** [comment]
nice implementation @nicomouss !
Thanks for sharing and a big gotcha when using typeorm with DI.
Maybe adding a link in the doc to this issue and example would be great :)

**Comment by nicomouss** [comment]
@nolazybits your are welcome, glad it helped !

**Comment by nicomouss** [comment]
@alexplacinta yes it makes things easier.

Transaction management that way is pretty cool, but that is only one tiny part of what makes building/maintaining a product easier.

I'd say the combination of an ORM (ie. typeOrm here), an easy-to-use dependency injection container (ie. typeDI here), and an overall layered architectural design following Domain-Driven-Design principles (Application, Domain and Infrastructure layers) is what really makes things more easy, maintainable and evolutive.

There are good practice to follow also, like designing a "rich" domain model (not an anemic one where all you business code is put on services) using proper object-oriented design, or properly assigning responsibilities to components throughout your layered architecture.

What is good here is that, like hibernate or NHibernate, TypeOrm is non-intrusive, meaning it enables you to set up a domain model which is clean of any technical code (and using TypeOrm declarative files instead of decorators on domain objects to set up your mapping rules make things even more clean).

So I guess an overall open source project providing best-practice and examples using these concepts would be the best (not only one lib providing transaction management facilities). I will try to work on it in the coming months.

Thanks for your feedback.

**Comment by alexplacinta** [comment]
@nicomouss "So I guess an overall open source project providing best-practice and examples using these concepts would be the best" would be awesome, because currently we are working on this stack(typeorm/typestack libs(typeDI, routing controllers,..)), we moved from Spring stack about year ago using its transaction management, and now we are trying to build on the same layered architecture(Controller-Service-DAO) having on every method last parameter entityManager for transaction wrapping(passing through layers), but this looks ugly and sometimes does not make sense logically, example: i try to unit test service by mocking dao interface(looks like its low coupled without any logic references to DB), but wait, here is a parameter entityManager which i should always set as null to ignore which does not have any purpose in context of unit test, can you recommend some temporary tricks to make it better or just keep this way because it's not critical? thnx

**Comment by nicomouss** [comment]
@alexplacinta you need components that encapsulate everything, and a loosely-coupled architectural design.

If you look at the PhotoRepository in the example above (PhotoDAO in your case). This component internally retrieves the entityManager to work with, there is no parameter entityManager anywhere. Passing the EntityManager to every method of a DAO/Repository is not a good design in my opinion. Besides being ugly, it leads to difficulties when you want to test things and mock your components. As you have already noticed.

Define all your DAO/Repository operations with an interface that the DAO/Repository implements (the IPhotoRepository in the example above). Then inject the DAO/Repository in your service using this interface (see the constructor of the ManagePhotosService above). This will setup a loosely-coupled architectural design.

Then in the context of unit testing: code specific DAOs/Repositories (for example here you would have a PhotoRepositoryTest implementing the IPhotoRepository). Here internally these specific DAOs/Repositories will not use any EntityManager, they will only return objects you need for your unit testing. Keep your services as they are, and use a specific injection container in the context of your unit testing to inject the specific DAOs/Repositories you have created.

**Comment by alexplacinta** [comment]
@nicomouss yeap, more specifically my question is about how to wrap a method from service of controller into a transaction as currently its not possible to use decorator like in spring and without passing entitymanager through all layers as suggested @pleerock(by creating adding for every method entitymanager for every component in layers)?

**Comment by alexplacinta** [comment]
i would use your code,  practically it does all what need, but would be nice this to be a maintanable project and as you said its not just about this feature, maybe to create a Spring like ecosystem:), starting from one feature and adding incrementally

**Comment by nicomouss** [comment]
Well for now it is basically just two files you need to add to your architecture:
- Transaction.ts for the decorator.
- BaseRepository.ts for the base class your repositories/Dao should inherit from.

Not much work to do to bring up the things you want.

Then having a full ecosystem is another big step. Here I gave a sample code, that's already something people can use and customise to their needs.

**Comment by geersch** [comment]
Nice work @nicomouss. I use InversifyJS and InversifyJS Express Utils to run my express app. I implemented a mediator and using your technique I can nicely wrap the handle() method of a handle inside a transaction. Nice job!

**Comment by nicomouss** [comment]
@geersch, you are welcome, nice to see this design helped make things easier.

**Comment by pleerock** [comment]
@nicomouss maybe you should create a separate package for what you did?

**Comment by nicomouss** [comment]
@pleerock yes it will be good to have a specific package, will try to do that at some point

**Comment by Diluka** [comment]
I find it's hard to use transactions with typeorm in real-world business.

An example
There are 3 jobs `jobA`, `jobB` and `jobC`.
`jobA` has transaction and it calls `jobB` and `jobC`.
`jobB` can use transaction but not required.
`jobC` has shared transaction if no one exists it will create one.

With annotation like:
```ts
@Transaction()
jobA(){
  jobB();
  jobC();
}

jobB(){}

@Transaction()
jobC(){}
```

**Comment by nicomouss** [comment]
@Diluka the provided implementation of the Transaction decorator does not work in case of nested transactional function. Usually this is not an issue if you only decorate the top-level functions (entry points) of your application with the Transaction decorator. In your case you would need to refactor your code a bit in order to have something like this:

```javascript
@Transaction()
jobA(){
  executeJobB();
  executeJobC();
}

jobB(){
  executeJobB();
}

@Transaction()
jobC() {
   executeJobC();
}

executeJobB() {
   // Here the implementation of job B
}

executeJobC() {
   // Here the implementation of job C
}
```

Now if you want to keep your code as it is, you need to change the Transaction decorator implementation and make it "smarter" (ie. by opening a Transaction only on the first transactional function in your function calls).

Use this new version, it should work fine:

```javascript
// Transaction.ts file
import { getConnection, getManager } from "typeorm";
import { getNamespace } from "cls-hooked";

export function Transaction(connectionName: string = "default"): MethodDecorator {
    return function (target: Object, methodName: string, descriptor: PropertyDescriptor) {

        // save original method - we gonna need it
        const originalMethod = descriptor.value;

        // override method descriptor with proxy method
        descriptor.value = async function(...args: any[]) {

            let context = getNamespace("__cls__context");

            if (!context) {
                // This will happen if no CLS namespace has been initialied in your app.
                // At application startup, you need to create a CLS namespace using createNamespace(...) function.
                throw new Error("No CLS namespace defined in your app ... Cannot use CLS transaction management.");
            }

            if (!context.active) {
                // This will happen if your code has not been executed using the run(...) function of your CLS
                // namespace.
                // Example: the code triggered in your app by an entry HTTP request (or whatever other entry event, 
                // like one triggered by a message dropped in a queue your app is listening at), should be wrapped 
                // using the run(...) function of your CLS namespace.
                // Using run(...) ensures that an active context is set, where you can safely store and retrieve
                // things.
                throw new Error("No CLS active context detected ... Cannot use CLS transaction management.")
            }

            // From here everything is OK to use CLS to manage our transaction.

            // We check if a transaction has already been started
            let transactionalEntityManager = context.get("__typeOrm__transactionalEntityManager");

            if (!transactionalEntityManager) {

                // No existing transaction. We now use one ...

                return await getConnection(connectionName).transaction(async entityManager => {
                    
                    // We store the EntityManager managing our current transaction.
                    context.set("__typeOrm__transactionalEntityManager", entityManager);

                    // We can now call the function that had been decorated with the Transaction decorator.
                    let result = await originalMethod.apply(this, [...args]);

                    // We just finished working with the EntityManager managing our transaction: we remove it
                    // from the current context.
                    context.set("__typeOrm__transactionalEntityManager", null);

                    return result;

                });
            }
            else {

                // A transaction has already been started. We just call the function.

                return await originalMethod.apply(this, [...args]);
            }

        };

    };
}
```

Hope this helps.

**Comment by irissoftworks** [comment]
I am looking at something here ...
```
// We can now call the function that had been decorated with the Transaction decorator.
let result = await originalMethod.apply(this, [...args]);
context.set("__typeOrm__transactionalEntityManager", null);
```
What happens if the original method fails with an exception ? 

Am I missing something or the last instruction clearing the context won't run and this manager would stay in the context ?

**Comment by geersch** [comment]
@irissoftworks : It won't be cleaned up. You can always put a `try...finally...` around the invocation of the original method to make sure it's cleaned up regardless of the outcome. PS: I won't suggest using `continuation-local-storage`. It works nicely locally for small demo projects / prototype, but it has too many issues.

This issue on the its repository sums it up pretty well.

https://github.com/othiym23/node-continuation-local-storage/issues/59

Personally I'm running an ExpressJS app. I just created some middleware which creates the transactional entity manager and stores that on the request (express.Request). Which is basically the only reliable way to pass around contextual information.

CLS is a nice concept and hopefully something similar will once be implemented in Node.

**Comment by irissoftworks** [comment]
Yeah I got it that I can implement a try catch mechanism to fix the issue. 

The goal here was just to point out for anyone out there using this code without looking at it that their entity manager is left in a bad state for the next request if there are exceptions.

Also your point about cls is invalid. The decorator above uses cls-hooked not the package you mentioned.

**Comment by geersch** [comment]
It was phrased as a question. Good luck with CLS, hooked or not.

**Comment by irissoftworks** [comment]
My question is do you understand what's being discussed here or just spreading FUD about something you don't fully understand, which may impact other people as well ? 

This issue https://github.com/othiym23/node-continuation-local-storage/issues/59 is all about the patching issues which obviously plague node-continuation-local storage due to it not being able to hook into async functions (such as bluebird's or mongoose's) properly.

CLS-hooked uses async hooks which provides a way to hook up into async functions, removes the need for patching consumers and even though is an experimental feature, is there since node v8.x and working well with no major issues. 

CLS hooked is working in production for a good while without any major issues.

**Comment by nicomouss** [comment]
> I am looking at something here ...
> 
> ```
> // We can now call the function that had been decorated with the Transaction decorator.
> let result = await originalMethod.apply(this, [...args]);
> context.set("__typeOrm__transactionalEntityManager", null);
> ```
> What happens if the original method fails with an exception ?
> 
> Am I missing something or the last instruction clearing the context won't run and this manager will stay in the context ?

Here what is happening when an exception is raised within the original method.

First TypeOrm will automatically ROLLBACK the transaction:

```ts
return await getConnection(connectionName).transaction(async entityManager => {
     
     // ...

     // An exception is raised within the original method:
     // TypeOrm's transaction(...) method will catch the exception, 
     // ROLLBACK the transaction, and throw the error again
     let result = await originalMethod.apply(this, [...args]);
     
});
```

Then up the function calls, the exception will reach CLS-hooked's run(...) method:

```ts
context.run(
     // CLS-hooked's run(...) method will catch the exception, do its 
     // own internal logic, then re-throw the exception
);
```

Now our exception have reached outside of the CLS-hooked run(...) function. Outside of this function, there is no more context, it has been freed by CLS-hooked. Thus the manager is not here anymore, as the context is itself not existing anymore.

At this point, up to you to catch the exception at a higher level to return a generic error message to the end-user.

The only scenario that could cause problem here would be to have an incoming HTTP POST triggering more than one transactional operation, and one of these operation is failing, as in this example:

```ts
app.post("/CreateSomethingInTheSystem", async function(req: Request, res: Response) {

     try { 
          await jobA();
     } catch { 
          // ...
     }

     try { 
          await jobB();
     } catch { 
          // ...
     }

});

@Transaction()
jobA(){
     // An exception is raised here ...
     // -> The Transaction is rolled back (that's what we want ...)
     // -> The transactional manager stays in the context (that's what we don't want ...)
}
@Transaction()
jobB(){
     // There is a manager in the context (this manager should not be there anymore ...)
     // -> The app tries to use that manager to execute jobB (which is wrong ...)
}
```

**Comment by nicomouss** [comment]
So below an updated version of the Transaction decorator that should take care of all of the scenarios:

```ts
// Transaction.ts file
import { getConnection, getManager } from "typeorm";
import { getNamespace } from "cls-hooked";

export function Transaction(connectionName: string = "default"): MethodDecorator {
    return function (target: Object, methodName: string, descriptor: PropertyDescriptor) {

        // save original method - we gonna need it
        const originalMethod = descriptor.value;

        // override method descriptor with proxy method
        descriptor.value = async function(...args: any[]) {

            let context = getNamespace("__cls__context");

            if (!context) {
                // This will happen if no CLS namespace has been initialied in your app.
                // At application startup, you need to create a CLS namespace using createNamespace(...) function.
                throw new Error("No CLS namespace defined in your app ... Cannot use CLS transaction management.");
            }

            if (!context.active) {
                // This will happen if your code has not been executed using the run(...) function of your CLS
                // namespace.
                // Example: the code triggered in your app by an entry HTTP request (or whatever other entry event, 
                // like one triggered by a message dropped in a queue your app is listening at), should be wrapped 
                // using the run(...) function of your CLS namespace.
                // Using run(...) ensures that an active context is set, where you can safely store and retrieve
                // things.
                throw new Error("No CLS active context detected ... Cannot use CLS transaction management.")
            }

            // From here everything is OK to use CLS to manage our transaction.

            // We check if a transaction has already been started
            let transactionalEntityManager = context.get("__typeOrm__transactionalEntityManager");

            if (!transactionalEntityManager) {

                // No existing transaction. We now use one ...

                return await getConnection(connectionName).transaction(async entityManager => {
                    
                    // We store the EntityManager managing our current transaction.
                    context.set("__typeOrm__transactionalEntityManager", entityManager);

                    try {
                        
                        // We can now call the function that had been decorated with the Transaction decorator.
                        let result = await originalMethod.apply(this, [...args]);

                        return result;
                    
                    } finally {

                        // We just finished working with the EntityManager managing our transaction: we remove it
                        // from the current context.
                        context.set("__typeOrm__transactionalEntityManager", null);

                    }

                });
            }
            else {

                // A transaction has already been started. We just call the function.

                return await originalMethod.apply(this, [...args]);
            }

        };

    };
}

```

Thank you guys for your feedbacks.

**Comment by irissoftworks** [comment]
Awesome and thanks for providing this code @nicomouss. The issue u pointed out is exactly what I had in mind. I think it would only happen if you rethrow inside the catch block though:
```
try { 
          await jobA();
     } catch { 
          // if this is not rethrowing then the decorator won't blow up and it will still clear up context
     }

``` 

I know it's an edge case but could still hit someone and cause some weirdness. Now it's perfect I believe.

**Comment by nicomouss** [comment]
> The issue u pointed out is exactly what I had in mind. I think it would only happen if you rethrow inside the catch block though:
> 
> ```
> try { 
>           await jobA();
>      } catch { 
>           // if this is not rethrowing then the decorator won't blow up and it will still clear up context
>      }
> ```

No, in the example I provided with jobA and JobB: if you re-threw in the jobA catch block then you would have reached out of the run(...) function, thus the context would have been freed. But JobB() would not have been executed (and you wanted it to execute in order to trigger the error within the Transaction decorator).

So the only non-working scenario was the following: inside the same execution context (same HTTP POST for example), we have a first transaction which fails, and we try to open a new transaction. Because the context was not cleaned after the first transaction failed, things were not working properly while trying to open the new transaction.

This was an edge case indeed.
Thanks to have pointed this problem out.

**Comment by Diluka** [comment]
I am using lib [`typeorm-transactional-cls-hooked`](https://github.com/odavid/typeorm-transactional-cls-hooked)

And I turn it into a patch, can support both `DataMapper` and `ActivieRecord`
https://gist.github.com/Diluka/87efbd9169cae96a012a43d1e5695667

**Comment by nicomouss** [comment]
> I am using lib [`typeorm-transactional-cls-hooked`](https://github.com/odavid/typeorm-transactional-cls-hooked)

@Diluka thanks for your feedback. Good news that someone already took the lead to create a npm package.

This package provides Transaction propagation and Isolation levels functionnalities, and integrates well with native TypeOrm repositories, which is very good.

So let's not re-invent the wheel then. Let's keep the discussion here and the Transaction decorator provided as general information around transactions and Continuous Local Storage. I encourage people to use the [typeorm-transactional-cls-hooked](url) library for the accepted solution.

**Comment by plourenco** [comment]
Even though this issue has been sleeping for quite a while, I felt like I had to share an opinion coming from someone who's currently using typeorm as a first-choice ORM in the NodeJS ecosystem. At the present date, it does not feel natural for a developer or team to spend hours or days coming up with a solution for transactions that should in the first place be abstracted by the ORM. Being transactions something fundamental, it hurts both the library and the Node ecosystem.

Sharing the transaction context is something critical, which can't right now be achieved without tons of boilerplate code or using a third-party library such as [typeorm-transactional-cls-hooked](https://github.com/odavid/typeorm-transactional-cls-hooked) that is not only unmaintained but also extremely unsafe. It relies on patching the repository manager and assumes the library will indefinitely rely on that. If for any reason something goes wrong, or a breaking change, suddenly all transactions are gone, they get committed immediately.

While `async_hooks` is still experimental, the `AsyncLocalStorage` is stable, used since Node 14 and even backported to Node 12 if I recall correctly. I don't see any reason to not use this method nowadays. Third-party ORMs [are also using it](https://sequelize.org/docs/v7/other-topics/transactions/#automatically-pass-transactions-to-all-queries) and even spring implement a similar solution relying on the thread local storage. I think it's about time TypeORM could consider a similar solution that does not affect the current structure but allows an alternative to dynamically use a query runner (or its manager) across all existing repositories in the same context.

**Comment by sunjoong85** [comment]
> Even though this issue has been sleeping for quite a while, I felt like I had to share an opinion coming from someone who's currently using typeorm as a first-choice ORM in the NodeJS ecosystem. At the present date, it does not feel natural for a developer or team to spend hours or days coming up with a solution for transactions that should in the first place be abstracted by the ORM. Being transactions something fundamental, it hurts both the library and the Node ecosystem.
> 
> Sharing the transaction context is something **critical**, which can't right now be achieved without tons of boilerplate code or using a third-party library such as [typeorm-transactional-cls-hooked](https://github.com/odavid/typeorm-transactional-cls-hooked) that is not only **unmaintained** but also extremely **unsafe**. It relies on patching the repository manager and assumes the library will indefinitely rely on that. If for any reason something goes wrong, or a breaking change, suddenly all transactions are gone, they get committed immediately.
> 
> While `async_hooks` is still experimental, the `AsyncLocalStorage` is **stable**, used since Node 14 and even backported to Node 12 if I recall correctly. I don't see any reason to not use this method nowadays. Third-party ORMs [such as sequelize are also using it](https://sequelize.org/docs/v7/other-topics/transactions/#automatically-pass-transactions-to-all-queries) and even spring implements a similar solution relying on the thread local storage. I think it's about time TypeORM could consider a similar solution that does not affect the current structure but allows an alternative to dynamically use a query runner (or its manager) across all existing repositories in the same context.

Totally agree with that. I have been using NestJS and Typeorm for years. And I found out that solid transaction management is required to expand Node's territory in Web Application fields and so on. A layered architecture has been proven that it is easy to understand and easy to be maintained. Using Typeorm and other NodeJS ORM libraries don't satisfy reusing service layer business logic cause its connection object should be passed down as a parameter. Declarative transaction management under AOP concept gives tons of advantages for developers to focus on their domain logic, not boilerplate transaction codes.
