### ISSUE TITLE
Application fails on restart as typeorm attempts to change column type

### ISSUE THREAD

**Issue by Coly010** [typeorm/typeorm#1896]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `mysql` / `mariadb`

**TypeORM version:**

[ ] `latest`
[x ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have two entities User and UserMonster.

User has a monsters property which is a Many-To-Many relation with UserMonster entity.

When I attempt to restart my application I encounter the following error:

```QueryFailedError: ER_FK_COLUMN_CANNOT_CHANGE_CHILD: Cannot change column 'userId': used in a foreign key constraint 'FK_8601d2c5587d0af01cf58f5e050' of table 'gamedev.user_monsters_user_monster'```

This is without changing the entities at all.

**Comment by Avejack** [comment]
Same problem for me!
I tried every version after alpha.42 and found that this error was introduced in alpha.23!

Maybe the Syntax has changed?

**Comment by chanlito** [comment]
same problem here, did you guys find a workaround?

**Comment by Coly010** [comment]
In that case it may be a problem with ormconfig as I have synchronize: true in that.

I'll fork the repo and see if I can find what's causing this issue.

Using the information @Avejack mentioned I'll diff the changes in alpha.23 to alpha.22

**Comment by Coly010** [comment]
@Avejack brilliant! 

Closing this as resolved.
