### ISSUE TITLE
The correct way of adding `ON UPDATE CURRENT_TIMESTAMP` clause to timestamp column

### ISSUE THREAD

**Issue by d-yokoi** [typeorm/typeorm#1901]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to add a column like this
```
`updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
```
Although I could not find any document written about this (my apologies if there is), I managed to generate such a column by
```
@Column('timestamp', { name: 'updated_at', precision: 3, default: () => 'CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)' })
updatedAt?: string;
```
However, I think it's a little tricky way for adding `ON UPDATE CURRENT_TIMESTAMP(3)` because it's not a part of `DEFAULT` clause.
Is there any recommended way?

Thanks

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.44`. You can try it via `npm i typeorm@next`.

Usage: 

```typescript
@Entity()
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column("timestamp", { precision: 3, default: () => "CURRENT_TIMESTAMP(3)", onUpdate: "CURRENT_TIMESTAMP(3)"})
    updateAt: Date;
}
```
