### ISSUE TITLE
Ionic v1 App Startup Memory High. But when back home screen and back to app its back to normal memory

### ISSUE THREAD

**Issue by iChuaNz** [typeorm/typeorm#1902]
: Current
My app react very weird, as when startup from splashscreen to the first page, the memory was arise until 500MB++ and when I click home button and open back to the app it is now 16MB. 

Just wonder what plugin did i install wrongly to have such crazy memory arise at startup

: Ionic Info

Your system information:
Cordova CLI: 6.5.0
Ionic Framework Version: 1.3.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS High Sierra
Node Version: v6.11.4
Xcode version: Xcode 9.2 Build version 9C40b

Plugins
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.3.0 "AppRate"
cordova-plugin-badge 0.7.4 "Badges"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.7.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.2 "Network Information"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2-dev "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.7 "SocialSharing"
cordova-plugin-x-toast 2.6.0 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.2 "PushPlugin"

**Comment by daniel-lang** [comment]
You are using a number of plugins that might need to do something on startup. Are you sure, that your memory usage has something to do with TypeORM? I don't see a database related plugin on your list.

**Comment by pleerock** [comment]
Closing as no answer from reporter.
