### ISSUE TITLE
Cordova/Sqlite maximum depth 1000

### ISSUE THREAD

**Issue by jondediego** [typeorm/typeorm#1903]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.1.20` (or put your version here)

I am getting this error when saving a table A that cascade updates to a table B: "could not prepare statement (1 Expression tree is too large (maximum depth 1000))". I think this error is present in sqlite whe more than 1000 params are used. If I print sql, only 999 are used.

**Comment by pleerock** [comment]
Use `@next` where persistence is optimized A LOT. Try it via `npm i typeorm@next`. This issue must be fixed in there.

**Comment by MasseElch** [comment]
@pleerock I have the same isseu with `npm i typeorm@next`. Should i open a new issue?

**Comment by pleerock** [comment]
yes please, with details and reproduction example please
