### ISSUE TITLE
Entity dynamic table names

### ISSUE THREAD

**Issue by brunozoric** [typeorm/typeorm#1904]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi,
is there a way to use dynamic table names on the Entity?

The use case would be:
we have an Entity that has id, name, numberValue, identifierOne, identifierTwo
so we would like for our entity to be saved into table named "my_entity_table_$identifierOne_$identifierTwo" which is modified by identifierOne and identifierTwo so if identifierOne is A and identifierTwo is B table would look like "my_entity_table_A_B"

**Comment by pleerock** [comment]
To name entity specifically you can pass name in decorator `@Entity("your_entity_name")`

**Comment by daniel-lang** [comment]
As far as I know, the table name has to be known when the connection is established to generate Metadata and other data about the table. Your approach would mean, that the table name gets generated at runtime.

If I understood you correctly you would like to
* Create new tables after the connection was established based on parameters
* Have TypeORM pick the database based on entity parameters when using a repository or the query builder

@pleerock can correct me if I'm wrong, but as far as I know, TypeORM does not support this.

I don't know your concrete use case but I to me, having "dynamic" table names doesn't sound like a good database design, as the number of tables will grow and grow over time.

**Comment by pleerock** [comment]
@brunozoric for specific tasks like this you need to come to specific solutions. You need to create entities array using entity schemas and pass them into "entities" array of connection options. Checkout samples regarding to "entity schemas". But you won't be able to use classes and decorators for your purpose.

**Comment by pleerock** [comment]
Let me know if you still have questions.

**Comment by NathanLi** [comment]
I want this function too. Beacuse we have a hundred million row in a table. It is too slow. So we want to divide this table to many tables according to `id`. Then dynamic table names is good.

**Comment by PaulMest** [comment]
@NathanLi Not sure what RDBMS you're using, but have you considered using partitioned tables?

Here are some examples for how to do it with the top vendors:

- [Postgres](https://www.postgresql.org/docs/current/ddl-partitioning.html)
- [MySQL](https://dev.mysql.com/doc/refman/8.0/en/partitioning-overview.html)
- [SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/partitions/partitioned-tables-and-indexes?view=sql-server-ver15)
- [MariaDB](https://mariadb.com/kb/en/partitioning-overview/)

**Comment by wesleyfebarretos** [comment]
I found a way to effiecent to do that in typeorm 2024 cause getRepository is deprecated.

const repository = dataSource.createQueryBuilder().connection.getRepository(Entity);
repository.metadata.tablePath = ${scheme}.${partition_table_name}

await repository.find() // Like a normal entity

if your table is in public scheme, u dont need the scheme identifier.
