### ISSUE TITLE
Support a prefix option for caching keys

### ISSUE THREAD

**Issue by agubler** [typeorm/typeorm#1905]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Currently it is possible to supply an `identifier` in the caching options that is used as the `key` in the cache store, this is fine when caching on a query by query basis as you could supply a unique identifier for each. However when configuring the caching at a connection level the identifier doesn't seem to be very useful as it would be the same for every query. It would be really useful to be able to provide a `prefix` to the default key (the parsed sql as far as I can tell). Such that when working with multiple connections that are using the same cache, the cached queries can be differentiated per connection (based on the prefix) when the parsed SQL is the same.

**Comment by pleerock** [comment]
Can you provide an example? I don't understand how multiple connections affect caching. When using multiple connections it is fine that second connection returns same data as first connection, since its the same database and the same query, right?

**Comment by agubler** [comment]
Hey @pleerock, thanks for the response - If it was the same database then it would be absolutely fine but if are working with multiple databases so caching by query doesn't help as presumably would return the cached data from a different database if the query matched. 

The prefix I would probably supply would be the name of the database to provide the differentiator.

**Comment by agubler** [comment]
@pleerock Yup we were looking to use redis for the cache. Absolutely I'm happy to contribute the changes.

**Comment by pleerock** [comment]
Cool, changes must be against `next` branch and shall be covered with tests when possible. I was thinking what to use - connection name or database name - but it seems both solutions may lead to issues, so probably best solution is to add "prefix" option to "cache" section in connection options just like you suggested.

**Comment by agubler** [comment]
@pleerock Do you want me to raise this against `next` or `master`?

**Comment by pleerock** [comment]
Both are okay since its not breaking, do against whatever branch u use, `next` will be released soon anyway.

**Comment by agubler** [comment]
@pleerock pull request raised here https://github.com/typeorm/typeorm/pull/1915, thanks!

**Comment by imnotjames** [comment]
As the PR was closed and we've not seen much activity here I'm gonna close this out.
