### ISSUE TITLE
@CreateDateColumn inserts DEFAULT in typeorm@next

### ISSUE THREAD

**Issue by ibox4real** [typeorm/typeorm#1907]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`CreateDateColumn` breaks when going from 0.1.20 => @next 

```
//In 0.1.20
INSERT INTO `test`( `created_at`, `updated_at`) VALUES (?,?) -- PARAMETERS: ["2018-04-10T18:05:32.927Z","2018-04-10T18:05:32.927Z"]

//In @next
INSERT INTO `test`( `created_at`, `updated_at`) VALUES (DEFAULT,DEFAULT) -- PARAMETERS: []

//Throws error `created_at` does not have a default value

```

Did something change how the CreateDateColumn and UpateDateColumn decorators need to be configured?

**Comment by pleerock** [comment]
insertion query is correct. in `@next` create and update dates are inserted by database (instead of typeorm), e.g. using columns DEFAULT value where for create and update columns its CURRENT_TIMESTAMP. Looks like your schema is not in sync.

**Comment by ibox4real** [comment]
Thank you for clarifyin. The database schema is correct because initially it was supposed to be the responsibility of the application to insert the default values for the dates. I will make adjustments and add CURRENT_TIMESTAMP as the default value in the schema.
