### ISSUE TITLE
Password-less connection strings broken

### ISSUE THREAD

**Issue by patrickhousley** [typeorm/typeorm#1909]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

PR https://github.com/typeorm/typeorm/pull/1690 has broken connection strings that do not contain a password.

```ts
process.env.DATABASE_URL = 'postgres://buffalo_heroku@localhost:5432/buffalo_heroku';

// Produces:
// {
//   "host": "localhost",
//   "username": "",
//   "password": "buffalo_heroku",
//   "port": 5432,
//   "database": "buffalo_heroku"
// }
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by patrickhousley** [comment]
Temporary workaround:

```ts
process.env.DATABASE_URL = 'postgres://buffalo_heroku:@localhost:5432/buffalo_heroku';
```

**Comment by pleerock** [comment]
@Rhymmor can you please take a look on this issue?

**Comment by pleerock** [comment]
@Rhymmor thank you very much!
