### ISSUE TITLE
I have a problem with the relationship. @ManyToOne

### ISSUE THREAD

**Issue by Fokir** [typeorm/typeorm#191]
There are 2 models
```javascript
@Table()
export class Token extends Model {
    static __repository: Repository<Token>;

    @PrimaryGeneratedColumn()
    id: number;

    @Column({unique: true})
    token: string;

    @ManyToOne(type => User, (user: User) => user.tokens)
    @JoinColumn()
     user: Promise<User>; 
}
@Table()
export class User extends Model{
    static __repository: Repository<User>;
    __hide: Object = {password: true, email: function (u: User, r: Request) {
        if(r.user && u.id == r.user.id) return false;
        return true;
    }};

    @PrimaryGeneratedColumn()
    id: number;

    @Column({nullable: true, unique: true})
    email: string;

    @Column({nullable: true})
    password: string;

    @Column({unique: true})
    uplay: string;

    @ManyToMany(type=>Role, (role:Role)=>role.users)
    roles: Promise<Array<Role>>;

    @OneToMany(type=>Token, (token: Token)=>token.user)
    tokens: Promise<Array<Token>>;
}
```

The database data is stored as it should, but when I try to authenticate the user on the token, a promise Returns the void
`let token: Token = await Token.__repository.findOne({token: request.get<string>('token')});
`...
`let user: User = await token.user;
`user == undefined => true

> executing query: SELECT user.id AS user_id, user.email AS user_email, user.password AS user_password, user.uplay AS user_uplay FROM user user INNER JOIN token Token ON Token.user=user.id WHERE user.id=? -- PARAMETERS: [6]

This is carried out such a request.
It is not true. Instead the user id is inserted record id of the found token.

I can not understand where I was wrong

**Comment by Fokir** [comment]
![image](https://cloud.githubusercontent.com/assets/1648384/21854028/b2ce1c06-d832-11e6-94ef-7a775da628ca.png)
![image](https://cloud.githubusercontent.com/assets/1648384/21854047/c1e7e820-d832-11e6-960f-f2f7547afa34.png)

When searching for a token identifier equal to 3, and further loading the user relationship, there is such a request


> executing query: SELECT user.id AS user_id, user.email AS user_email, user.password AS user_password, user.uplay AS user_uplay FROM user user INNER JOIN token Token ON Token.user=user.id WHERE user.id=? -- PARAMETERS: [3]

**Comment by pleerock** [comment]
that was a bug. fixed and released in `0.0.7-alpha.8`. Do `npm i typeorm@0.0.7-alpha.8` to try it.

**Comment by Fokir** [comment]
Thank you very much, everything works as expected. So many hours has killed in order to understand what's the error

**Comment by pleerock** [comment]
ahh sorry about that

**Comment by ericwooley** [comment]
@pleerock 

It does version 0.0.7-alpha.8 (or alpha.25, or 0.0.7, or 0.0.8) does not appear to fix my issue. I am going to update the issue now.
