### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by ahmedNY** [typeorm/typeorm#1911]
**Issue type:**
[*] bug report

**Database system/driver:**
[*] `mysql` / `mariadb`

**TypeORM version:**
[*] `latest`

**Steps to reproduce or a small repository showing the problem:**

I had one to many relation like this
```ts
@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    url: string;

    @ManyToOne(type => User, user => user.photos)
    user: User;

}
import {Entity, PrimaryGeneratedColumn, Column, OneToMany} from "typeorm";
import {Photo} from "./Photo";

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column({nullable: true})
    nickname: number;

    @OneToMany(type => Photo, photo => photo.user)
    photos: Photo[];

}

/**********/
    const photos = await userRepository.createQueryBuilder("photo")
    .select(["photo", "user.nickname"])
    .leftJoin("photo.user", "user")
    .getMany();
    console.log(photos)
```

if the nickname is NULL then the user object is not injected on photo
i.e I expected the result as following
```
[
{ 
     id: 1,
     url: 'https://example.com/photo/1',
     user: { nickname: 'coolUser' },
},
{ 
     id: 2,
     url: 'https://example.com/photo/2',
     user: { nickname: null },
}
]
```
but i got the following
```
[{ 
     id: 1,
     url: 'https://example.com/photo/1',
     user: { nickname: 'coolUser' },
},
{ 
     id: 2,
     url: 'https://example.com/photo/2',
    // NO USER OBJECT HERE!!!!!!
}
]
```
i got no user object on the second photo at all, which toke me few hours to know that the selected column had NULL values!!

**Comment by pleerock** [comment]
Try to select `photo.id` as well. Ids are required for selection in such cases because since you don't select `user.id` there is no criteria to compare `photo.userId` with.

**Comment by ahmedNY** [comment]
Hi @pleerock am working on a new project with new / empty database,  it took me few hours to know that,  until i added user.id to .select() and discovered that nickname was null.

**Comment by pleerock** [comment]
QueryBuilder is very dynamic and its possible to cover all situations people do, when you use query builder you need to think what sql query are you building and what results it brings. Your used kinda advanced functionality and that's okay if you spent few hours to get a right solution. I think issue can be closed since you found a solution.

**Comment by ahmedNY** [comment]
I don't want other peoples to stuck like me for few hours, this is why i reported this issue

**Comment by pleerock** [comment]
thanks for the feedback, hope people won't face such issue too much
