### ISSUE TITLE
Find where for sub relation fields

### ISSUE THREAD

**Issue by anvaskes** [typeorm/typeorm#1916]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello!
Is that possible to do something like this ? 
```
const [results,count] = await this.repository.findAndCount({
	where: {
		relation: [
			{
				subRelation: [
					subRelationField: value
				]
			}
		]
	}
});
```
I want to get and count rows, but params which i need to match is one of nested relation fields.

**Comment by pleerock** [comment]
you need to use QueryBuilder for this purpose. It will be much cleaner btw.

**Comment by anvaskes** [comment]
Thank you! Can you give some example ? How to query this with query builder.

**Comment by pleerock** [comment]
see docs on site on how to use query builder. Basically its something like this:

```ts
repository.createQueryBuilder("photo")
    .innerJoin("photo.albums", "album", "album.name = :name", { name })
    .getManyAndCount()
```

**Comment by anvaskes** [comment]
Great! Thanks.
