### ISSUE TITLE
ioredis instead of redis (package) as cache client

### ISSUE THREAD

**Issue by szymonskirgajllo** [typeorm/typeorm#1919]
**Issue type:**

[ ] question
[ ] bug report
[X ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X] `0.1.19` (or put your version here)

Instead of using redis (https://www.npmjs.com/package/redis) as client which is used as cache maybe you should use ioredis which has a support for sentinel ;)

What do you think about it? @pleerock 

redis package does not have any support for cluster or sentinel so it can be problematic when redis instance fails 

can you change this client to ioredis? if yes i would like to know ETA :)

**Comment by pleerock** [comment]
> if yes i would like to know ETA :)

haha its open-source and its the same if I ask you to develop a ioredis plugin for typeorm and ask ETA :)

you can develop any cache store you want, typeorm allows it.

**Comment by pleerock** [comment]
The answer was given.
