### ISSUE TITLE
Is it possible to define custom relation conditions?

### ISSUE THREAD

**Issue by dario1985** [typeorm/typeorm#1924]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

There is any way, eg using decorators (instead of custom query builders) to add fixed conditions?

```typescript
        @OneToMany(
		type => Tag,
		...
                { where: { deletedAt: null } }
	)
	public tags: Tag[];
```

In this case the use case is if I need it to just filter soft deleted elements, but can be useful in others more.
Would be more clear and maintainable to add it as custom `where` in `RelationOptions` instead of generate custom query builders.

**Comment by pleerock** [comment]
no, its not possible and won't be. It brings you a limit you cannot avoid. It can be convenient in some cases, but overall it wont be a good practice. Use query builder for this purpose.

**Comment by dario1985** [comment]
Ok, and there is some way to reuse query builder criterias? to avoid duplication? something like this [filtering collections](http://doctrine-orm.readthedocs.io/en/latest/reference/working-with-associations.html#filtering-collections)

**Comment by pleerock** [comment]
No, there is not.

Duplication has its places where its actually better to duplicate. QueryBuilder queries is exact such place. Prefer duplication in QueryBuilder queries and you'll avoid lot of issues. 

But if you still want to reuse query builder parts you can do it easily by yourself, no overcomplicated orm functionality is needed for this purpose.

**Comment by Coly010** [comment]
@dario1985 How would you plan on reusing query builder criteria?
Do you have an example of such a query that you are using repeatedly?

**Comment by pleerock** [comment]
Answer on the original question was given. I think this issue can be closed.

**Comment by smnkgv** [comment]
It would be very convenient with soft delete, because otherwise there is no point in using ORM's relations on a project. Query builder is ok, but writing `.leftJoinAndSelect('xxx', 'yyy', 'yyy.deletedAt is NULL')` all the time is not.

**Comment by razorness** [comment]
Typeorm makes it very convenient to write simple queries. However, a very common solution is to use custom repositories for each entity to isolate query code from business logic.

https://github.com/typeorm/typeorm/blob/master/docs/custom-repository.md

**Comment by Silventino** [comment]
Oh wow :(
I really need that feature...

**Comment by Silventino** [comment]
Came back to say that I was able to achieve my goal with ViewEntity, maybe that helps someone:
https://typeorm.io/#/view-entities
