### ISSUE TITLE
Remove entity from TreeRepository (Closure table)

### ISSUE THREAD

**Issue by szepeshazi** [typeorm/typeorm#193]
Does the `remove() `method work for Closure tables? When I tried to remove a leaf node from a Category model, I got the following error message (using typeorm 0.0.6, typescript, mysql 5):

`ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`exampledb`.`category_closure`, CONSTRAINT `fk_11da9decc6d053c89b14825abe2` FOREIGN KEY (`descendant`) REFERENCES `category` (`id`))`

I checked the samples, but they only cover persisting and retrieving items from a TreeRepository.

**Comment by szepeshazi** [comment]
I just noticed the comment in https://github.com/typeorm/typeorm/blob/master/src/repository/TreeRepository.ts :

    // todo: implement moving
    // todo: implement removing

If you haven't started on those implementations yet, I can give it a try - I'd really need a fully functional TreeRepository.

**Comment by pleerock** [comment]
no I didnt switched to this functionality yet, go ahead if you want to contribute!

**Comment by hisamu** [comment]
I'm implementing some of this on my current project after following these samples:

```SQL
-- Delete Leaf node
-- ================
-- delete leaf node #7

DELETE FROM TreePaths WHERE descendant = 7;

-- Delete Subtree
-- ==============
-- delete #4 and all children from the tree

DELETE FROM TreePaths
WHERE descendant IN (SELECT descendant
                     FROM TreePaths
                     WHERE ancestor = 4);
```

I thought about implementing two separate methods for `removeDescendants` and `removeAncestors`, then calling them inside the `remove` method. 

On my project, I just check if the entity has any children. If not, I only remove the descendants. I still haven't implemented the ancestor removal, though, and I'm not sure about the best approach for that.

There's also a `move` example in here: https://gist.github.com/emmanuel/1004087/999411ba639df4b89c7a8cd94700877c16c8fa84#file-file-sql-L45

**Comment by raybornez** [comment]
Thank you for this amazing library. I am currently working on a project and I am using the closure table. I am wondering when will this remove method for the tree table be implemented?

**Comment by pleerock** [comment]
Currently there are lot of issues with more priority, Im thinking such "extra tree-related features" will be implemented in summer. But feel free to contribute if you want to get it quicker :)

**Comment by ldadams** [comment]
I would also be happy to contribute to a full closure table implementation as I have an immediate need and already using TypeORM.

**Comment by pleerock** [comment]
@ldadams sounds great! @awwong1 also pointed that he wants to contribute. For exactly this feature I was thinking simply to add `onDelete: "CASCADE"` to referenced columns in closure table and foreign key in original table. I think that should work

**Comment by awwong1** [comment]
I ended up implementing my own opinionated closure entity in my application, rather than relying on TypeORM's built in closure support.
https://github.com/udia-software/udia/blob/master/src/entity/ItemClosure.ts

My code for updating the items handles updating all of the children in the closure table:
https://github.com/udia-software/udia/blob/64898bc30d72fb2ea12f096d165beab4c8c87a42/src/modules/ItemManager.ts#L197
My application's delete is really a SQL Update that sets a deleted flag in the row and clears the nullable columns. The change to make this a true SQL delete is trivial.
https://github.com/udia-software/udia/blob/64898bc30d72fb2ea12f096d165beab4c8c87a42/src/modules/ItemManager.ts#L266

I'm still interested in implementing this in TypeORM but I'm not sure how to make it generic. Putting my code in this issue in hopes that it is useful to someone else.

**Comment by ambroiseRabier** [comment]
Any update? Would be worth adding a note to the documentation indicating closure-table is an incomplete feature.

**Comment by shusson** [comment]
If anyone takes a look at this, I'd be interested if we can make `remove` work using only postrges `onDelete` cascades.

**Comment by awwong1** [comment]
I decided to revisit this problem and wrote some code for moving entities in a closure-table.

My approach is to generate all of the necessary queries using QueryBuilder, then to execute all of the queries within a transaction within the TreeRepository `move`, `delete`, and `remove` functions.

I am running into an issue where QueryBuilder insert into closure table is not setting the values properly, despite the values being passed.

https://github.com/awwong1/typeorm/commit/e93d1b8b8c13196b12fdb8c7d75ee91dd675bc5f

Specifically, [TreeRepository.ts@304](https://github.com/awwong1/typeorm/commit/e93d1b8b8c13196b12fdb8c7d75ee91dd675bc5f#diff-b718d41629000e38727038684b1dd73aR304) is not passing the test case defined [here](https://github.com/awwong1/typeorm/commit/e93d1b8b8c13196b12fdb8c7d75ee91dd675bc5f#diff-a4361d2e277616195d3337ecb48941dcR72).

If you're using VisualStudioCode, you can check the variables being set with the following launch configuration: 
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Debug Mocha test",
            "program": "${workspaceFolder}/node_modules/.bin/_mocha",
            "args": [
                "--inspect-brk",
                "--recursive",
                "--timeout",
                "60000",
                "${workspaceFolder}/build/compiled/test",
                "--grep",
                "github issues > #193"
            ],
            "preLaunchTask": "npm: compile"
        }
    ]
}
```

**Comment by saulotoledo** [comment]
@awwong1 Are you still working on this?

**Comment by awwong1** [comment]
> @awwong1 Are you still working on this?

No, I have not used typeorm in some time now.

**Comment by kennylbj** [comment]
Any progress on this thread? It's a quite common scenario IMO.

**Comment by murshudov** [comment]
This is how I implemented `delete`. Works for Postgres, but I think should work for other DB's that works with closure table:
```js
import { DeleteResult, TreeRepository } from 'typeorm';
import { Transactional } from 'typeorm-transactional-cls-hooked';

export class BaseTreeRepository<T> extends TreeRepository<T> {
    @Transactional()
    async delete(id: string): Promise<DeleteResult> {
        const tableName = this.metadata.tablePath;
        const primaryColumn = this.metadata.primaryColumns[0].databasePath;
        const parentPropertyName = this.metadata.treeParentRelation.joinColumns[0].propertyName;
        const parentColumn = this.metadata.treeParentRelation.joinColumns[0].databasePath;

        const closureTableName = this.metadata.closureJunctionTable.tablePath;
        const ancestorColumn = this.metadata.closureJunctionTable.ancestorColumns[0].databasePath;
        const descendantColumn = this.metadata.closureJunctionTable.descendantColumns[0].databasePath;

        // Get all the descendat node ids from the closure table
        const closureNodes = await this.createQueryBuilder()
            .select(`closure.${descendantColumn}`)
            .distinct(true)
            .from(closureTableName, 'closure')
            .where(`closure.${ancestorColumn} = :ancestorId`, { ancestorId: id })
            .getRawMany();

        const descendantNodeIds = closureNodes.map((v) => v[`closure_${descendantColumn}`]);

        // Delete all the nodes from the closure table
        await this.createQueryBuilder()
            .delete()
            .from(closureTableName)
            .where(`${descendantColumn} IN (:...ids)`, { ids: descendantNodeIds })
            .execute();

        // Set parent FK to null in the main table
        await this.createQueryBuilder()
            .update(tableName, { [parentPropertyName]: null })
            .where(`${parentColumn} IN (:...ids)`, { ids: descendantNodeIds })
            .execute();

        // Delete from main table
        await this.createQueryBuilder()
            .delete()
            .from(tableName)
            .where(`${primaryColumn} IN (:...ids)`, { ids: descendantNodeIds })
            .execute();

        return { raw: descendantNodeIds };
    }
}
```
It shouldn't be hard to implement `remove` based on this.

For Transactions you can use manager.transaction, but for my case it was problematic, because on a higher level I use `typeorm-transactional-cls-hooked` and they are conflicting with each other.

**Comment by phil294** [comment]
FYI there's a working PR for tree update/delete logic: https://github.com/typeorm/typeorm/pull/7156

**Comment by kennylbj** [comment]
@phil294 Thank you for the info, I have tested the solution and now we can use `@TreeParent({ onDelete: 'CASCADE' })` to delete tree entity.
