### ISSUE TITLE
@beforeUpdate @afterUpdate not triggered on Array modification

### ISSUE THREAD

**Issue by 2xAA** [typeorm/typeorm#1930]
**Issue type:**

[*] question
[*] feature request

**Database system/driver:**

[*] `postgres`

**TypeORM version:**

[*] `latest`

**Steps to reproduce or a small repository showing the problem:**

Entity listeners are not triggered when pushing a new Entity to another Entity's Array.

e.g.
```TypeScript
audioItem.comments.push(audioComment);
await audioRepository.save(audioItem);
```

Would it be possible for this to become a feature in the long run or is there another approach to reproduce this functionality?

Obviously checking the whole of the Array would become too slow on a large set, so would there be any chance to watch the Array length changing?

**Comment by pleerock** [comment]
you need to handle this manually. Listeners are only notify about database columns changes, not relations.

**Comment by pleerock** [comment]
Let me know if you still have questions.

**Comment by velociraptor111** [comment]
how do you suggest we handle this manually?
