### ISSUE TITLE
DataTypeNotSupportedError: Data type "Object" is not supported by "postgres" database

### ISSUE THREAD

**Issue by darkbasic** [typeorm/typeorm#1931]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
@Column({nullable: true})
  receivedAt: Date;
```

The previous code used to work, after upgrading to latest @next snapshot now I get the following error:

```
(node:2899) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DataTypeNotSupportedError: Data type "Object" in "Recipient.receivedAt" is not supported by "postgres" database.
```

How am I supposed to specify a generic date type which will work with most dbs?
`@CreateDateColumn` is not an option because it will have to be initialized with a null value and updated with a date later on.

**Comment by pleerock** [comment]
there are tests which confirm this works without issues. Are you sure you did not change tsconfig options? Can you please provide a reproduction repo?

**Comment by darkbasic** [comment]
I didn't change anything else, I only updated typeorm.

Also the following works flawlessly:
```
@Column({type: "time without time zone", nullable: true})
receivedAt: Date;
```

To reproduce the issue you can simply run npm start from this repo:
https://github.com/Urigo/whatsapp-server-express

If you want me to create something more minimal just let me know, but should be good to reproduce the issue.

**Comment by pleerock** [comment]
if you simply do `tsc && node index.js` then everything works fine. Looks like an issue with ts-node or your project setup that leads ts-node to such strange behaviour. I can recommend you to minimize your example and open issue in ts-node repo.

**Comment by darkbasic** [comment]
https://github.com/TypeStrong/ts-node/issues/569

**Comment by darkbasic** [comment]
ts-node 6 has been released, changing the default behaviour to type check by default, making it compatible with typeorm.
