### ISSUE TITLE
MongoDB required column

### ISSUE THREAD

**Issue by mmenik** [typeorm/typeorm#1932]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

It's possible define @Column() or other way a property to set in MongoDB required field?
Thks

**Comment by pleerock** [comment]
no, you'll need to use some third-party validation library, like [class-validator](https://github.com/typestack/class-validator).

**Comment by pleerock** [comment]
Let me know if you still have questions.
