### ISSUE TITLE
Mongo: name in columnOptions is not being passed to find query

### ISSUE THREAD

**Issue by mcMickJuice** [typeorm/typeorm#1933]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.20` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an entity that has a name db name mapping to property name using ColumnOptions:

```typescript
 @Column({
    name: 'node_id',
  })
  nodeId!: string;
```

I have a query using a repository for this model

```typescript
  async getPageAssociationsForNodeId(nodeId: string) {
    const pageAssociations = await this.pageAssociationRepository.find({
      nodeId, //typed to Model so this cant be "node_id"
    });

    return pageAssociations;
  }
```

When I issue this query, looking at the logs in mongo, `nodeId` is being passed in the query, not `node_id` (name provided in column options):

```js
{
	"op" : "query",
	"ns" : "<myDb>.PageAssociation",
	"command" : {
		"find" : "PageAssociation",
		"filter" : {
			"nodeId" : "12345"
		},
		"$db" : "slingshot"
	},

```

`nodeId` is not the column name in the collection so no results are being returned.

My questions are:

1) am I using find appropriately?
2) is it wrong to assume that the ColumnOptions.name will be used instead of the property name of the class
3) if the answers to the above are "yes" and "no" respectively, is this a bug?

**Comment by mcMickJuice** [comment]
Looking through the code, it doesn't look like the column metadata is being taken into account for the `find` path, or any of the other `find` methods.  The name mapping DOES work with insert operations.

**Comment by pleerock** [comment]
I think this question was answered.

**Comment by mcMickJuice** [comment]
I understand that Mongo queries CAN be dynamic, but if you're using an ORM, doesn't this enforce a structure on your collection structure and property names?  In what situation when running a "find" query would this column mapping between property and name in your model and collection property not work?  Embedded documents?

If your position is that you don't think name property should be used in mongo, I would suggest then adding that to the docs and removing the functionality entirely from the MongoRepository/manager.  As I mentioned above, this mapping works when running a "save" operation but not any querying functions. This should be considered a bug.

FWIW, I'm willing to contribute to this repo to implement this feature.  I'm just wondering what the edge cases are that prevent you from wanting to have this implemented.

**Comment by mcMickJuice** [comment]
There are two issues here:

### Save operation

If the name column is respected on the save operation but no other query, that is a bug. How am I supposed to use the `find` operation if I have the name property respected on save but not on querying?  Either support the name feature 100% or don't support it at all.

### Dynamic queries

Yes, mongo supports dynamic queries and polymorphic collections but if you're using an ORM with models that are typed, aside from the aggregate (which is a custom query and shouldn't be typed to the Entity) and query (which isnt supported) methods, what's dynamic about these queries? 
 Methods like find and findOne are executed in the context of a specific collection, so what would be dynamic about these queries?  The properties should all be the same in the collection so where's the issue with column mappings if the queries themselves are typed to the Entity?

Please remember that I am trying to help here.  I've offered to look into this and am asking for specific examples of where this name mapping won't work.  In my experience, this is a standard feature in ORMs and it would be great if it were supported in TypeORM for mongo.  I still fail to see why it can not be done as all you're telling me is that mongo is dynamic and therefore it's not possible.

**Comment by Matthijn** [comment]
I'm more confused about not having this feature actually. In our system, I want to move from a homemade 'orm' to `typeorm`. But our database fields are all already `snake_cased`. While in typescript I'd like all my properties to be `camelCased`. 

I'm confused about why it is 'confusing' to have this feature on mongo because on other databases it is supported. I'm failing to see why mongo is different in this regard, or why that is wanted. 

Implementing a `NamingStrategyInterface` doesn't seem to work either, it does work for the table names, and the `columnName` method in the naming strategy is called, but it's result is ignored.

**Comment by TakeshiDaveau** [comment]
Why don't make this behaviour configurable ?

The ability to decorrelate the technical database name of an attribute from its object representation in programmation language is a key feature of an ORM. The "don't use `name`" doesn't match my conception of a professional ORM.

I disagree with the fact that 99% of the query are made over `query` in real app. When you create a CRUD API you need this simple `find` query. 
Moreover for me it's more dangerous to apply an unpredictable behaviour for simple things than for complexe things.

**Comment by Monstermash28425R1** [comment]
so this wasn't solve at the end? i still find this behavior when working with mongo
