### ISSUE TITLE
Question about migrating data to new system buillt using typeorm.

### ISSUE THREAD

**Issue by KrisChambers** [typeorm/typeorm#1935]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Not really much of an issue with the framework (really has helped speed up my development, you guys are doing a great job) just a bit of confusion on how to do something. I have an excel spreadsheet that has all my initial data and relationships in it. Things are associated accordingly in there with id's and what not and I want to migrate the data to a database built using typeorm.

What is the best way to migrate existing data to a database built using typeorm such that I can ensure the current primary keys and relationships are preserved?

**Comment by pleerock** [comment]
there are multiple ways but most safe probably is to create a migration script, load all the data from your old database (using separate connection and raw queries), create entities, relations, etc. via code and call `save` for them. e.g. everything is manual

**Comment by pleerock** [comment]
Let me know if you still have questions.
