### ISSUE TITLE
Migration Contexts

### ISSUE THREAD

**Issue by CanKattwinkel** [typeorm/typeorm#1939]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue
________________________

Is there any concept of context for migrations? Like [Liquibase has](https://www.liquibase.org/documentation/contexts.html).

So that I could specific a context for a migration e.g. "mock-data" and "schema". Then running locally both contexts but on my production server only the "schema" migrations.

**Motivation:**
I want to add inserts of mock data into my migration while developing but not run those scripts on production. What I could already do is to request the environment in the migration script but a more generic solution would be desirable

**Comment by pleerock** [comment]
It will complicate things. Migrations are also revertible and not sure how this affect revert functionality. I would like to avoid more complicated migrations functionality.

**Comment by CanKattwinkel** [comment]
So what approach would you recommend instead? 

The context adds complicity, that's right. But if everyone has to handle the migration of mock data context-dependently himself, then it doesn't make things easy either, does it? 

I wouldn't add this as a default, but possibly from switchable contexts. So if you specify a context in the class implementing `MigrationInterface` you can exclude/include it when you use the `migrations:run` command.

Goal: no breaking changes, API stays simple but is capable of working with contexts when needed.

**Comment by CanKattwinkel** [comment]
> What I could already do is to request the environment in the migration script but a more generic solution would be desirable

Since this is not really DRY, I'd repeat myself over and over again. Therefore I'd like a (re) use able feature of TypeORM CLI. But yeah, perhaps the additional complexity is the worse trade off.

**Comment by pleerock** [comment]
I just wanted to confirm that code I proposed may work. If yes, then it does not look like a worth implementation feature. I'll close this issue until it gets more votes from the community.
