### ISSUE TITLE
Support for partitioning in MySQL

### ISSUE THREAD

**Issue by d-yokoi** [typeorm/typeorm#1940]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to use range partitioned table in MySQL.
What is the standard way to make it with TypeORM?

**Comment by pleerock** [comment]
partition is your table internal functionality and does not affect object relational model anyhow. And its a bit specific so executing a raw query in a migration lets say sounds quite okay there. Don't you think its enough to make typeorm and partitions work?

**Comment by d-yokoi** [comment]
I wanted to know if there are some helpers , for example, a decoration which assures that the partitioning key is a part of the primary key.
I see there are not and I agree with you in that specific supports are not necessary, so I'll try as you say.
Thank you for responding!

**Comment by Fabiomad85** [comment]
I have a problem with a partitioned table without id

**Comment by tpiecora** [comment]
This is a problem in postgres.  Partitioned tables must be partitioned when they are initially created.
