### ISSUE TITLE
invalid input syntax for uuid for PrimaryGeneratedColumn("uuid") when initializing property

### ISSUE THREAD

**Issue by marpstar** [typeorm/typeorm#1945]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts

export class EntityBase {
  @PrimaryGeneratedColumn("uuid") public id: string = ""; // NOTICE: I'm initializing this property to ""
  @CreateDateColumn() public created: Date = new Date();
  @UpdateDateColumn() public updated: Date = new Date();
  @Column() public inactive: boolean = false;
}

@Entity("user_accounts")
export class User extends EntityBase {
  @Index("username_unique", { unique: true })
  @Column()
  public username: string = "";

  @Column() public passwordHash: string = "";
  public password: string | undefined;
}

```

Trying to insert entries of the above entity type but getting an error when calling `save` on the repository. My TypeScript project is set to `strict: true`, which requires property initialization.  I recently upgraded to `typeorm@next` (currently `0.2.0-alpha.46`) and began having this problem.  Before, I was running an earlier version of 0.2.0 and using `sqlite` instead of `postgres`. 

In one of my other entities, I was initializing a relation property to empty array (`[]`) and received an error in the console, which was very clear that I shouldn't initialize that property.  

I remove the initialization code and everything is now working.

Is this something that TypeOrm could detect and throw a clearer error for?

```
QueryFailedError: invalid input syntax for uuid: ""
    at new QueryFailedError (/src/error/QueryFailedError.ts:7:9)
    at Query.callback (/src/driver/postgres/PostgresQueryRunner.ts:170:26)
    at Query.handleError (/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/pg/lib/connection.js:117:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

**Comment by pleerock** [comment]
Let me know if I did not answer your question.
