### ISSUE TITLE
Support for POJOs

### ISSUE THREAD

**Issue by i0natan** [typeorm/typeorm#1950]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

For the sake of clean architecture and pure data-mapper, do you support plain JS objects that don't mix DB annotations so the mapping definition is located in the repository (external object, not within the model)?

**Comment by pleerock** [comment]
this feature is called entity schemas and you can find examples [here](https://github.com/typeorm/typeorm/tree/next/test/functional/entity-schema/basic).

**Comment by pleerock** [comment]
http://typeorm.io/#/separating-entity-definition documentation link

**Comment by i0natan** [comment]
Great work. You're the only Node ORM that is doing it right...

Maybe are there any docs how to use the EntitySchema with plain JS (not TS)? what replaces the generic type in new EntitySchema<entity-reference>()?

**Comment by i0natan** [comment]
@pleerock Cool, thanks. I've noted that EntitySchema has far less documentation that others methods, does it contain all the other mapping features of in-class annotations? does it have known limitations? I'm starting a big project with it and afraid to find it myself hitting walls

p.s. I'm the author of this repo, we soon start to write 'data access layer section' and looking for partners/writers/inspiration - if you're interested I'll be glad to speak. In any case we intend to praie the data-mapper strategy of typeorm
www.github.com/i0natan/nodebestpractices

**Comment by pleerock** [comment]
@i0natan its an alternative approaches, so I would say it has differences, not limitations
