### ISSUE TITLE
Couldn't start on server first time when there's no internet 

### ISSUE THREAD

**Issue by jefftoNNNNg** [typeorm/typeorm#1951]
**Issue type:**
[x] question

**Database system/driver:**
[x] `mssql`

**TypeORM version:**
0.1.20

**NodeJS version:**
8.9.4

**npm version:**
5.8.0

**server:**
windows server 2008 r2

Hi all
There's a typescript project work with express. It works fine in dev env.
When deploying to server, it breaks when starting.
My server is unable to connect to Internet and it's never run a typescript project before. (Nodejs by ecmascript project works fine)
So I copy all the source code (including node_modules) to the server. Version of node & npm are same with dev env.
Log on server and package.json has uploaded.
Wish for replay.

**package.json:**
`
{
   "name": "PropertyInfoWebservices",
   "version": "0.0.1",
   "private": true,
   "scripts": {
      "start": "ts-node app.ts"
   },
   "dependencies": {
      "body-parser": "~1.13.2",
      "debug": "~2.2.0",
      "express": "~4.13.1",
      "typeorm": "0.1.20",
      "reflect-metadata": "^0.1.10",
      "mssql": "^4.0.4"
   },
   "devDependencies": {
      "ts-node": "3.3.0",
      "@types/node": "^8.0.29",
      "typescript": "2.5.2"
   }
}
`
[2018-04-16T07_16_33_005Z-debug.log](https://github.com/typeorm/typeorm/files/1915945/2018-04-16T07_16_33_005Z-debug.log)

BTW, i guess something wrong with the environment variable on my server. I couldn't run 'npm install -g typescript' because there's no internet.

**Comment by pleerock** [comment]
I don't understand how is your issue related to typeorm. Closing.
