### ISSUE TITLE
querybuilder not returning any results

### ISSUE THREAD

**Issue by DR-BoneZ** [typeorm/typeorm#1954]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So I'm having some issues with the QueryBuilder when spawned from a manager, since upgrading to 0.2.0.
```
await manager.query('SELECT * FROM "post" "onePost"') // returns array of posts
await manager.createQueryBuilder().select().from(Post, "onePost") // returns empty array
```
db logging shows identical output for both queries

**Comment by pleerock** [comment]
get you please provide a complete code for second example?

**Comment by DR-BoneZ** [comment]
sorry, yeah. I ran: `console.log(await getManager().createQueryBuilder().select().from(Post, "onePost").getMany())`

**Comment by DR-BoneZ** [comment]
also note: works fine for `getConnection.createQueryBuilder()`

**Comment by DR-BoneZ** [comment]
a test:
```
    it("should successfully run a query with query builder from a manager", () => Promise.all(connections.map(async connection => {
        const post = connection.manager.create(Post, {
            title: "test post",
            text: "this is a test"
        });
        await connection.manager.save(post);
        expect((await connection.manager.createQueryBuilder().select().from(Post, "onePost").getMany()).length).to.equal(
            (await connection.manager.query(`SELECT * FROM "post" "onePost"`)).length
        );
    })));
    it("should successfully run a query with query builder from a query runner", () => Promise.all(connections.map(async connection => {
        const post = connection.manager.create(Post, {
            title: "test post",
            text: "this is a test"
        });
        await connection.manager.save(post);
        expect((await connection.createQueryBuilder(connection.createQueryRunner()).select().from(Post, "onePost").getMany()).length).to.equal(
            (await connection.manager.query(`SELECT * FROM "post" "onePost"`)).length
        );
    })));
```

**Comment by pleerock** [comment]
change to:

```ts
(await getManager().createQueryBuilder().select("onePost").from(Post, "onePost").getMany())
```

if you use `select` you need to specify what to select, because calling select without arguments will clear all previously added selects (select was added by createQueryBuilder method)

**Comment by florohaltero** [comment]
I have the same issue, but this doesn't work for me.. 

`await conn.createQueryBuilder().select("order").from(Order, "order")
      .where("order.google_category IN (:categories)", {categories: data.categories})
      .andWhere("order.energy_label_status = :status", {status: data.status}).limit(50).printSql().getMany();`

When I run the printed sql, it works.

**Comment by anodynos** [comment]
For whoever bumps into this: 
- `.getMany()` returns empty array if any column you want to select isn't "properly" written. Try using 
      `.createQueryBuilder('Document').select('Document.id')` instead of `.createQueryBuilder('Document')
        .select('id')` which fails.
- use `.execute()` works even with `.select('id')`, but you lose typing and class instantiation.
