### ISSUE TITLE
using mysql2 (https://www.npmjs.com/package/mysql2)

### ISSUE THREAD

**Issue by ithav** [typeorm/typeorm#1956]
**Issue type:**
[X] question

**Database system/driver:**
[X] `mysql`

**TypeORM version:**
[X] `latest`

**Steps to reproduce or a small repository showing the problem:**
How can I have typeorm using mysql2 instead of mysql?

Thanks
ithav

**Comment by ithav** [comment]
thanks @pleerock

**Comment by ryanhex53** [comment]
When you can't remove  package `mysql` in some reason, required by other packages for example. 

In version **`~0.3`** you can set `this.options.connectorPackage` option:
```
{
connectorPackage: 'mysql2'
//other options
}
```

In version **`~0.2`** you can set `this.options.driver` option
```
{
driver: PlatformTools.load('mysql2')
//other options
}
```
