### ISSUE TITLE
invalid input value for enum in postgres. Need an example

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#1957]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Version `^0.2.0-alpha.46`

I've tried the example in https://github.com/typeorm/typeorm/issues/1883 and some other threads to create a enum-type column with a default value in postgres:
````
export enum PostStatus {
    DELETED,
    NORMAL,
}
````
````
@Entity()
export class  Report{

    # 1.
    @Column('enum',{enum:PostStatus,default:PostStatus[PostStatus.NORMAL]})
    status:PostStatus;

    # 2. Also tried this:
    #@Column('enum',{enum:PostStatus,default:String(PostStatus.NORMAL)})
    #status:PostStatus;
}
````
The first one throws this error:
 `invalid input value for enum report_status_enum: "NORMAL"`

and the second one shows this:
` invalid input value for enum item_review_report_status_enum: "1"`

Can you please show me an example on how to define a enum type in postgres?

**Comment by AlexMesser** [comment]
The correct notation for your case is:
```ts
@Column("enum", { enum: PostStatus, default: PostStatus[PostStatus.NORMAL] })
status: PostStatus;
```
its results following queries:
```sql
CREATE TYPE "report_status_enum" AS ENUM('DELETED', 'NORMAL', '0', '1')
CREATE TABLE "report" ("id" SERIAL NOT NULL, "status" "report_status_enum" NOT NULL DEFAULT 'NORMAL', CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id"))
```
also in above enum you will get ` '0', '1'` numbers, this is typescript specifics and described in #1842

**Comment by stonecold123** [comment]
@AlexMesser , @pleerock 
I found out the problem.
The postgres still has the old type definition so if I change the enmu definitions in the entity it will throw out some conflict errors. I think you should DROP the type and CREATE them again instead of just ALTER. It will lead to some problems when renaming the column or updating the enmu definitions.

**Comment by Evilart86** [comment]
Why you close this if the problem is not solved?
What do you mean "I think you should DROP the types and CREATE them again"

**Comment by ValdekBro** [comment]
I found a solution for production, so as not to delete anything in the database, you can simply change the name of the enums after changing them, as far as I understand, a new enum will be created and bind to the column.
```ts
const enumsVersion = 'v' + 1
@Column({
        name: "informationAboutWisdomTeeth",
        enumName: `EWisdomTeethInformation_${enumsVersion}`,
        nullable: false,
        enum: EWisdomTeethInformation,
        default: EWisdomTeethInformation.UNSELECTED,
})
informationAboutWisdomTeeth: EWisdomTeethInformation
```
