### ISSUE TITLE
OneToMany - inverseSide never called?

### ISSUE THREAD

**Issue by netnexus** [typeorm/typeorm#196]
When running a code coverage in my project I was not able to execute the inverseSide of a OneToMany relation. All other annotations are covered. 

Please see the example below - the uncovered code would be "child.myClass". I was wondering what typeorm method must be called to execute the function "(child) => child.myClass".

```typescript
@Table()
export class MyClass {

    @PrimaryGeneratedColumn()
    public id: number;

    @OneToMany((type) => Child, (child) => child.myClass)
    public children: Child[];

}
```

**Comment by pleerock** [comment]
its `RelationMetadata.inverseSideProperty`

**Comment by netnexus** [comment]
Makes sense, thank you. So in contrast to the other relations - the OneToMany relations are is not executed during import of the entities - the OneToMany relations need to be really touched to execute the inverseSideProperty. Here is a small snippet if anyone is in need of the same thing.

```typescript

for (const meta of getConnectionManager().get().entityMetadatas) {
    for (const oneToMany of meta.oneToManyRelations) {
        const entity = meta.create();
        entity[oneToMany.name] = [];
    }
}

```
