### ISSUE TITLE
Migration generator produces duplicated changes

### ISSUE THREAD

**Issue by asvetliakov** [typeorm/typeorm#1960]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
import { PrimaryGeneratedColumn, Column, Entity } from "typeorm";

@Entity()
export class User {
    @PrimaryGeneratedColumn("increment")
    public id: number;

    @Column("varchar")
    public name: string;

    @Column("datetime")
    public date1: Date;

    @Column("datetime", { nullable: true })
    public date2: Date;
}
```

produces these changes for every created migration:

```ts
export class Test1523995934992 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `user` CHANGE `date1` `date1` datetime NOT NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `date2` `date2` datetime NULL");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `user` CHANGE `date2` `date2` datetime(0) NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `date1` `date1` datetime(0) NOT NULL");
    }

}
```

Also, just FYI, got the same issue as in #1686 . The problem was in the having the 2 keys for single relation:
```sql
  UNIQUE KEY `REL_e4a6fffee17f5467d57bff660e` (`communication_uuid`), -> New key name in 0.2
  UNIQUE KEY `IDX_e4a6fffee17f5467d57bff660e` (`communication_uuid`), -> This was produced by migration generator after upgrading from 0.1 to 0.2 
```

Deleting the IDX_ keys for relations solved the problem

**Comment by pleerock** [comment]
> produces these changes for every created migration

correct, you need to execute created migration before generating a new one. Migration generator checks your entities and your database, finds difference and writes into the file.

**Comment by asvetliakov** [comment]
This after executing it

**Comment by pleerock** [comment]
can you create a minimal reproduction git repo?

**Comment by asvetliakov** [comment]
Here you go, for both this issue and #1686

**Comment by HenryKari** [comment]
I was having this same issue with several columns in multiple tables. It turns out that some data types require precision attributes for the migrations to work correctly. The clue is in your up and down methods: 'down' tells you the SQL clauses that run if the migration is reverted and returned to its previous state. Before running the migration, your dates are of type "datetime(0)", and your up method tries to alter it to "datetime" without (0). However, if you run the migration MySQL presumably runs these dates as "datetime(0)" under the hood, causing TypeORM to think that the database is different than what is defined in the schema.

Try this:
`    @Column({type: "datetime", precision:0})
    public date1: Date;

    @Column({type: "datetime", precision:0, nullable:true})
    public date2: Date;`

Generate a new migration and run it. TypeORM should no longer detect a schema change if you try to generate another migration.

I've had similar issues with floats and decimals as well, so keep that in mind when you create columns with those types.

**Comment by jlitzingerdev** [comment]
I've run into this recently and wanted to try to provide some additional information.

My setup is mysql 5.6 (testing against a docker container), mysql2 driver, TypeORM 0.2.9.

I uncommented the logging here:
https://github.com/typeorm/typeorm/blob/a1ead76c89f4b4940424038c2a11f629320a4114/src/driver/mysql/MysqlDriver.ts#L613

And observed:

**Comment by arkus7** [comment]
This issue is still showing up for any `double` column type (like `real`, `double precision` etc.) with MySQL 5.7.

You can resolve it by providing the `precision` option manually to `22`

```js
@Column({ type: 'double', nullable: true, precision: 22 })
size: number;
```

**Comment by Mati365** [comment]
Problem still occurs in PostgreSQL `datetime` field nullability change

**Comment by henrique-codebase** [comment]
This problem hapening in Mariadb as well.  (typeorm version 0.2.31)

In my case, the generated migration for datetime says "create table ...... someColumn DATETIME NULL"
The thing is.... Mariadb, for some reason, store the column as 'DATETIME NULL DEFAULT NULL'. 

I've checked this generating a table ddl create on dbeaver.
The typeorm migrations logic believes that the entity schema is different from database. Therefore always generating a duplicated change with no real effect.

My 'solution' was to add the default on the column definition....
@Column({
    nullable: true,
    default: () => 'NULL', // <----------- redundant
  })
  dataNas?: Date;

**Comment by spmsupun** [comment]
it's 2021 and this's still happening with mariadb, anyone got a solution? :(

**Comment by imnotjames** [comment]
As there was a PR that had tests that confirmed this specific case resolved please open a new issue with information on how to reproduce the problem if you believe something similar is happening again.
