### ISSUE TITLE
How do I re-create this query with a cross product (no condition) and subquery?

### ISSUE THREAD

**Issue by jlaza020** [typeorm/typeorm#1962]
**Issue type:**

[x] question  
[ ] bug report  
[ ] feature request  
[ ] documentation issue  

**Database system/driver:**

[ ] `cordova`  
[ ] `mongodb`  
[ ] `mssql`  
[ ] `mysql` / `mariadb`  
[ ] `oracle`  
[x] `postgres`  
[ ] `sqlite`  
[ ] `sqljs`  
[ ] `websql`  

**TypeORM version:**

[x] `latest`  
[ ] `@next`  
[ ] `0.x.x` (or put your version here)  

I have an issue re-creating this query as a valid typeorm query:

```sql
SELECT candidate.id as cid, opportunity.id as oid
FROM candidate, opportunity
WHERE NOT EXISTS (
  SELECT 
  FROM application
  WHERE cid = candidate.id AND oid = opportunity.id
)
```

As an example, if I had these tables:

```
candidate    opportunity    application    
_________    ___________    ___________
c1           o1             a1 c1 o1
c2           o2             
```

I would expect this result:

```
c1 o2
c2 o1
c2 o2
```

I tried looking at the README, examples, stackoverflow, and GitHub issues but to no avail. Besides 
re-creating this query, I have no other issues using the API.

You might not need the entities, but here there are anyway:

```ts
// candidate.ts
@Entity()
export class Candidate {

    @PrimaryColumn()
    id: string;

    @OneToMany(type => Application, application => application.candidate)
    applications: Application[];
    
}

// opportunity.ts
@Entity()
export class Opportunity {

    @PrimaryColumn()
    id: string;

    @OneToMany(type => Application, application => application.opportunity)
    applications: Application[];

}

// application.ts
@Entity()
export class Application {

    @PrimaryColumn()
    id: string;

    @RelationId((application: Application) => application.candidate)
    candidateId: string;

    @RelationId((application: Application) => application.opportunity)
    opportunityId: string;

    @ManyToOne(type => Candidate, candidate => candidate.applications)
    candidate: Candidate;

    @ManyToOne(type => Opportunity, opportunity => opportunity.applications)
    opportunity: Opportunity;

}
```

**Comment by pleerock** [comment]
To build a query you need to use a QueryBuilder. Did you try to execute some query using it? [This](http://typeorm.io/#/select-query-builder/using-subqueries) might help you.

**Comment by jlaza020** [comment]
Yes, I have experience using it, but I can't seem to get this specific query to work the way I expect.

I'd think the query would look something like:

```ts
const result = await candidateRepository.createQueryBuilder("candidate")
.addFrom(CachedSqlOpportunity, "opportunity")
.where((qb) => {
    const subQuery = qb.subQuery()
        .select()
        .from(CachedSqlApplication, "application")
        .where(`application.candidate.id = candidate.id`)
        .andWhere(`application.opportunity.id = opportunity.id`)
        .getQuery();
    return "NOT EXISTS " + subQuery;
})
.getMany();
```

I just get:

```
c1
c2
```

**Comment by jlaza020** [comment]
Additionally, cross products don't work the way I expect it to as well. I would think that if I just add an additional from, I would get the cross product the same way I would with raw SQL. None of the columns from the other table are joined.

**Comment by pleerock** [comment]
```ts
const result = await candidateRepository.createQueryBuilder("candidate")
.addFrom(Opportunity, "opportunity")
.where((qb) => {
    const subQuery = qb.subQuery()
        .select()
        .from(Application, "application")
        .where(`application.candidate.id = candidate.id`)
        .andWhere(`application.opportunity.id = opportunity.id`)
        .getQuery();
    return "NOT EXISTS " + subQuery;
})
.getMany();
```

and what SQL it generates you? (you can add logging: true in connection options to see sql logs)

**Comment by jlaza020** [comment]
I used `printSql()` on the `QueryBuilder` and got something like this. This looks very
close to what I want.

```sql
SELECT "candidate"."id" AS "candidate_id" 
FROM "candidate" "candidate", "opportunity" "opportunity" 
WHERE NOT EXISTS (
    SELECT * 
    FROM "cached_sql_application" "application" 
    WHERE "application"."candidateId" = "candidate"."id" AND 
          "application"."opportunityId" = "opportunity"."id"
)
```

It is missing the additional select, so I modified my query:

```ts
const result = await candidateRepository.createQueryBuilder("candidate")
    .select("candidate.id", "cid")
    .addSelect("opportunity.id", "oid")
    .addFrom(Opportunity, "opportunity")
    .where((qb) => {
        const subQuery = qb.subQuery()
            .select()
            .from(Application, "application")
            .where(`application.candidate.id = candidate.id`)
            .andWhere(`application.opportunity.id = opportunity.id`)
            .getQuery();
        return "NOT EXISTS " + subQuery;
    })
.getMany();
```

The new generated SQL:

```sql
SELECT "candidate"."id" AS "candidate_id", "opportunity"."id" AS "oid" 
FROM "cached_sql_candidate" "candidate", "cached_sql_opportunity" "opportunity" 
WHERE NOT EXISTS (
    SELECT * 
    FROM "cached_sql_application" "application" 
    WHERE "application"."candidateId" = "candidate"."id" AND 
          "application"."opportunityId" = "opportunity"."id"
)
```

This seems to be a perfect match. When I run this raw SQL in my Postgres GUI 
(DBeaver), I get the correct result, but when executing the typeorm query (not raw 
SQL), I get an empty array. Why is this?

**Comment by jlaza020** [comment]
In fact, when I just do this simple query, I get no result (empty array) whereas with the raw SQL, I do:

```ts
const result = await candidateRepository.createQueryBuilder("candidate")
  .select("candidate.id", "cid")
  .printSql()
  .getMany();
```

`printSql()` generates this, which obviously works:

```sql
SELECT "candidate"."id" AS "cid" FROM "candidate" "candidate"
```

**Comment by jlaza020** [comment]
Ah, so using `getRawMany()` in place of `getMany()` gives the correct result. I'll do more research on the distinction between the two. Thanks for your help!

**Comment by pleerock** [comment]
hmm thats strange `getMany` shall work without issues here. Try to create a git repo and I'll take a look.

**Comment by rekoner** [comment]
I am having the same problem with a similar query. getMany() does not work, but getRawMany() does. I have to do the type mapping myself, which is doable, but is something typeorm should probably handle.
