### ISSUE TITLE
QueryBuilder Generates SQL SELECT without Schema When Entity name is string

### ISSUE THREAD

**Issue by petermetz** [typeorm/typeorm#1964]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

For me this happened specifically with the migrations table itself, but I think the issue applies to the more generic case stated in the title of the github issue.

**Steps to reproduce or a small repository showing the problem:**

```typescript
createConnection({
            autoMigrationsRun: false,
            autoSchemaSync: false,
            database: "postgres",
            dropSchemaOnConnection: false,
            entities: ["build/dist/main/typescript/model/entity/**/*.js"],
            host: "localhost",
            logger: "advanced-console",
            logging: "all",
            migrations: ["build/dist/main/typescript/model/database-migration/*js"],
            migrationsTableName: `my_type_orm_migrations_table`,
            password: "********",
            port: 5432,
            schema: "my_custom_schema_name",
            type: "postgres",
            username: "captain_database",
        } as any);

```

the later call the `.runMigrations();` method on the connection and watch it fail when it tries to query the migrations table on account of the query builder not appending the schema to the table name.

The patch I'm attaching fixed it for me locally but I'm not sure how to write tests for this exact issue so I can't submit a PR unfortunately. Figured I'd still open this issue to help out as much as I can.

[patch.diff.txt](https://github.com/typeorm/typeorm/files/1926727/patch.diff.txt)

**Comment by pleerock** [comment]
what **exact** typeorm version are you using? 

```typeorm -v```

**Comment by petermetz** [comment]
Here's what I meant with my checkbox ticks:

`0.1.21` => latest as of last night
`next` => I built the sources from master, installed that locally into my project.
Both exhibited the same issue.
Didn't try 0.2.0 yet (came out just now right?)

**Comment by petermetz** [comment]
Tried to give 0.2.0 a quick spin, but it has some other changes with `RelationOptions` that breaks my code so can't experiment with that at the moment.

**Comment by petermetz** [comment]
@pleerock works fine in 0.2.3, thanks!
