### ISSUE TITLE
how about setting column options nullable true by default

### ISSUE THREAD

**Issue by ReganHe** [typeorm/typeorm#1966]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

In common databases such as mysql、sql server and so on, when we add a new column in a table, its nullable property is true by default.
In a table with many columns, nullable columns is always the majority. however, we have to add {nullable: true} for every one of them.
How about setting column options nullable true by default?

**Comment by pleerock** [comment]
no, they are non nullable and it is by design. We will follow an inclusion strategy instead of exclusion.
