### ISSUE TITLE
[Question] Create subquery on table relation and limit by 1

### ISSUE THREAD

**Issue by Tyler-V** [typeorm/typeorm#1974]
**Issue type:**

[x] question
[?] bug report
[ ] feature request
[?] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

```
        const subQuery = this.scriptRepository
            .createQueryBuilder()
            .select('data')
            .from(Data, 'data')
            .orderBy('data.created', 'DESC')
            .limit(1)
            .getQuery();

        return await this.scriptRepository
            .createQueryBuilder('script')
            .leftJoin('script.author', 'author')
            .leftJoin('script.sessions', 'sessions')
            .leftJoin('sessions.user', 'user')
            .leftJoin('sessions.data', 'data')
            .where('script.id = :id', { id: scriptId })
            .select('script')
            .addSelect('author')
            .addSelect('user')
            .addSelect(`${subQuery}`, 'data')
            .getOne();
```

Using `.addSelect('data')` instead returns the entire entity and all the relations, I would like to return the a single script.sessions.data.object that `last created`.

I've read the documentation and the examples in `query-builder-subquery.ts` 

Can someone help me understand how to properly use a subQuery to limit a joined table?

**Comment by Tyler-V** [comment]
No idea if this is possible or not, I ended up creating an unwanted secondary `@ManyToOne(type => Data, data => data.summary)` relation on the session entity. Each time I insert new data into Session I save the data.id as session.summaryId and it allows me to look up the last submitted data entity of session.

This feels safe programmatically but potentially like overhead, you can close this is there isn't a better solution.

**Comment by pleerock** [comment]
When working with QueryBuilder you always need to think about SQL first and ask - what SQL you would like to build?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
