### ISSUE TITLE
QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.

### ISSUE THREAD

**Issue by chj-damon** [typeorm/typeorm#1995]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I'm using `transaction` to handle multiple inserts and I get an error:
`QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.`
Here is what my code looks like:
```ts
async save(entity: Entity, ids: string): Promise<Entity> {
    return await getManager().transaction(async transactionalEntityManager => {
      const result = await transactionalEntityManager.save(entity);
      ids.split(',').forEach(async id => {
        const rEntity = new REntity(result.id, +id);
        await transactionalEntityManager.save(rEntity);
      });
      return result;
    });
  }
```
I have no idea what I may miss.

**Comment by chj-damon** [comment]
I'll close this issue because I find out that `save` method can actually save bulks.

**Comment by pleerock** [comment]
btw you problem is in `forEach(async`, you need to use `map` instead of `forEach` and await all result using `Promise.all`

**Comment by chj-damon** [comment]
@pleerock yes you're right. Thanks for your help.
