### ISSUE TITLE
How to create index in typeorm? (index has name)

### ISSUE THREAD

**Issue by JingMo** [typeorm/typeorm#1998]
**Issue type:**

[ ] question

**Database system/driver:**

[ ] `mysql` / `mariadb`

**TypeORM version:**
[ ] `0.1.20` 

**Steps to reproduce or a small repository showing the problem:**

In MySQL:    create index 'index_xx' on table('column_xx');

How to write in Typeorm? Thanks!

@Index('index_xx') or @Index({ name: 'index_xx'})?

**Comment by dtruel** [comment]
https://github.com/typeorm/typeorm/blob/master/docs/indices.md
