### ISSUE TITLE
mixed todos

### ISSUE THREAD

**Issue by pleerock** [typeorm/typeorm#2]
These are the most relative todos that needs to be done:
- [x] all persist and remove operations needs to be performed in correct order to prevent errors. need to analyse this order somehow 
- [x] in query builder should we use property names or table names? (right now its kinda mixed)
- [x] think about indices
- [x] think more about cascades
- [x] add cascadeAll to cascades?
- [x] need to finish naming strategy
- [x] fix all propertyName/tableName problems and make sure everything work correctly
- [x] foreign keys for relations
- [ ] exceptions everywhere!
- [x] add ability to load only ids of the relation (similar to loading only single id)
- [x] make Index and CompoundIndex to work properly
- [x] make relations to connect not only to primary key (e.g. relation#referencedColumnName)
- [x] multiple primary key support?
- [x] ability to specify many-to-many column names in relation options
- [x] investigate relations support in abstract tables
- [x] allow inherited tables to work like abstract tables
- [x] check query builder query to function support
- [x] versioning?
- [x] check relations without inverse sides
- [x] check group by functionality
- [ ] send entity changeset in update event
- [x] create a cli for schema update
- [x] fixtures and migrations
- [x] lazy loading of properties throw promises? Property can have a Promise<Entity> type.
- [ ] logging, allow to provide a custom logger
- [x] check entities without generated ids
- [ ] fix issue with onDelete is not updated on each run (only initialized on first create)
- [x] add @DefaultOrder(order: "DESC"|"ASC") decorator to specify by which field qb will order by default?
- [x] use container everywhere to allow orm extensibility? 
- [ ] **in memory strategy and unit of work?**
- [x] support of embeddables ?
- [x] support table inheritance patterns? 
- [ ] multiple auto generation strategies?
- [x] rename event subscriber to entity event subcriber?
- [ ] caching strategies
- [x] connection pool
- [x] add option for the addToRelation and others to prevent duplicate keys to be inserted 
- [ ] implement extend of the entity schemas
- [ ] add @Where decorator
- [ ] add order decorator to relations
- [ ] internationalization features (for example @Internationalization() name can create fields for languages set in the configuration (lets say name_tj, name_ru, name_en, name_es) and during selection only fields of the current internationalization will be selected and mapped to their original name (e.g. name_en mapped to name)
- [x] special collections support for the relational arrays?
- [x] Where decorator should be supported by RelationCount as well 
- [x] check persistence when there are circular references
- [x] database DEFAULT values
- [x] global table prefix
- [x] allow to specify a prefixes into embedded columns
- [ ] add result caching capabilities to query builder
- [ ] custom id / value generation
- [x] bulk operations in specific repository?
- [ ] throw exceptions in persist if entity was updated with a new version/updated date 
- [ ] support nestedset and materialized path
- [ ] functionality for soft deletion? 
- [ ] functionality for versioning and revisions?
- [ ] pessimistic / optimistic locking?
- [x] add support of typeorm-config.json, maybe cli can use it instead of parameters
- [x] add support of configuration from ENV variables
- [ ] fix naming strategy issues, use naming strategy everywhere possible
- [x] partial loading (sometimes really needed)
- [x] add support for CHECK sql constraint or support ENUM data type?
- [ ] tree repository should be able to work with adjacency list, self referenced relations with tree decorators used
- [x] add ability to use custom repository classes
- [ ] add persistment options? (like UPDATE_COLUMNS|UPDATE_RELATIONS)? 
- [x] implement abstraction for webbased usage (browser/websql, ionic, etc.) 
- [x]  implement streaming for big data sets
- [x]  make sure array column works in both relational and mongodb
- [ ]  implement true relations and joins in mongo
- [ ]  reorganize docs to cover both relational and mongo databases
- [ ]  try to add more document storage databases
- [ ]  make sure lazy loading is working with mongo once mongo relations are setup
- [ ]  make sure create date / update date are working properly with mongo
- [ ] investigate multiple database queries issue

feel free to contribute. Open discussion on any of items here.

**Comment by JacobSoderblom** [comment]
Hi!

Is the feature "make relations to connect not only to primary key (e.g. relation#referencedColumnName)" released? We are trying to make a OneToOne relation with this options ´, its a relation between strings and we cannot get it to work.

**Comment by pleerock** [comment]
Hi, yes it should work. Please report a separate issue with short example of your issue and I'll try to debug it

**Comment by pleerock** [comment]
closing this one, moved some of tasks into #486
