### ISSUE TITLE
Paginated query not working SQL server 2012

### ISSUE THREAD

**Issue by samikroy-work** [typeorm/typeorm#200]
Pagination is not effecting in SQL server .

**CODE:**
entityManager.getRepository(elementObjectType).createQueryBuilder("q")
            .setFirstResult(paginatedRequest.startIndex|| 1)
             .setMaxResults(paginatedRequest.maxCount ||10)
             /*console.log("sql ",q.getSql());*/
                .getManyAndCount().then(data=> {
                    let paginatedResponse: PaginatedResponse = new PaginatedResponse();
                    paginatedResponse.records = data[0] as BaseEntity[];
                    paginatedResponse.totalRecords = data[1];
                    resolve(paginatedResponse);
                }, error=>reject(error));

**Comment by pleerock** [comment]
can you provide more info? maybe error or something? I think Ive checked this lib with latest version of sql server. 2012 is older then that. Does this version supports `offset fetch` ? (https://technet.microsoft.com/en-us/library/gg699618(v=sql.110).aspx)

**Comment by pleerock** [comment]
Closing as no answer from op. But pagination should totally work for mssql 2012 and newer.
