### ISSUE TITLE
Entity schemas documentation

### ISSUE THREAD

**Issue by ibox4real** [typeorm/typeorm#2001]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Hey how well implemented are entity schemas at this point? I see some documentation has emerged recently. I would like to see some examples how different decorators get translated in the schema files like GeneratedColumn, CreateDateColumn, UpdateDateColumn.

If i remove the decorators on the entities and create schema files targeting these entities instead then will my existing code (repositories/query-builders/enitity-manager) work without needing any additional modifications?

**Comment by pleerock** [comment]
There are should not be difference in usage between decorators and entity schemas, so you can use entity schemas if you prefer them. There still lack of docs which will be improved in the future, also feel free to contribute in this area.

**Comment by ibox4real** [comment]
Thank you, that is good to hear

**Comment by jebbdomingo** [comment]
Any example how to apply separate schema to an entity?

**Comment by johannesschobel** [comment]
@jebbdomingo have you managed to solve this for you? i am struggling of using an `Interface` of an entity (which is defined as schema) in a `Repository`...

**Comment by jebbdomingo** [comment]
@johannesschobel Unfortunately not yet 😄

**Comment by johannesschobel** [comment]
Hey @jebbdomingo , I managed to solve it like this:
```ts
const userRepository = getRepository<User>('UserSchema');
const user = await userRepository.findOne(1);
```

Whereas `User` is the `Interface` and `UserSchema` is the `EntitySchema` that describes the `User`. Respective `UserSchema` may look like this:
```ts
import { EntitySchema } from 'typeorm';
import { User } from './user.entity';

export const UserSchema = new EntitySchema<User>({
  name: 'UserSchema',
  tableName: 'users',

  columns: {
    id: {
      type: 'uuid',
      primary: true,
      generated: 'uuid',
    },

    email: {
      type: 'varchar',
      length: 150,
      unique: true,
    },
    username: {
      type: 'varchar',
      length: 150,
      unique: true,
    },
    password: {
      type: 'varchar',
      length: 150,
    },

    createdAt: {
      name: 'created_at',
      type: 'timestamp with time zone',
      createDate: true,
    },
    updatedAt: {
      name: 'updated_at',
      type: 'timestamp with time zone',
      updateDate: true,
    }
  },
  indices: [
    // ...
  ],
  relations: {
    // ...
  }
});
```

again, the `User` in this schema description is the previously mentioned `Interface`!

Maybe this helps?

**Comment by jebbdomingo** [comment]
@johannesschobel Great! Thanks 👍

**Comment by johannesschobel** [comment]
did it work out for you @jebbdomingo ?
You may also want to take a look at this issue here ( https://github.com/typeorm/typeorm/issues/3730 ).. This describes, how you can easily `extend` your `EntitySchema`s, like you would do with the decorated classes.. 

All the best

**Comment by xxRockOnxx** [comment]
I thought `Column` decorator is 1-1 with EntitySchema, however I'm not sure how to apply `geometry` and `spatialFeatureType` like #2423

The lint is complaining about the `spatialFeatureType` is not a valid key.
