### ISSUE TITLE
Support fo Oracle V11?

### ISSUE THREAD

**Issue by wdmcgrory** [typeorm/typeorm#2002]
**Issue type:**

[x] question
[ ] bug report
[? ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.1.20` (or put your version here)

I have successfully started using typeorm with a mysql back end for development. However, my customer requires us to use their existing oracle backend. Their configuration  is limited to Oracle Version 11. However, when I try to initialize entities for the oracle backend I get an error telling me that I COMPATIBLE parameter needs to be 12.0.0.0.0 or greater.

From the error message, this looks to be because the driver is trying to create a table wiht "SQL identity columns"?

I could see no discussion of required versions for oracle in the code repository. Am I missing something, or am I required to have oracle v12?

TIA,
Bill

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

Bill

**Comment by wdmcgrory** [comment]
I have successfully started using typeorm with a mysql back end for development. However, my customer requires us to use their existing oracle backend. Their configuration  is limited to Oracle Version 11. However, when I try to initialize entities for the oracle backend I get an error telling me that I COMPATIBLE parameter needs to be 12.0.0.0.0 or greater.

From the error message, this looks to be because the driver is trying to create a table wiht "SQL identity columns"?

I could see no discussion of required versions for oracle in the code repository. Am I missing something, or am I required to have oracle v12?

TIA,
Bill

**Comment by papagei9** [comment]
That's bad, because Oracle XE is only available as Version 11. V12 was never released and V18 is not yet finished. How are people able to test locally with a free version if it's not supported but there is no other option?

**Comment by pleerock** [comment]
we do run oracle tests in a docker container, so you should be able to do same as well.

**Comment by StetHD** [comment]
please open this case, I have two remote oracle 11g setup, for one of them it's working fine, for the other it gets ORA-00904
