### ISSUE TITLE
Set custom query runner

### ISSUE THREAD

**Issue by igor-ribeiro** [typeorm/typeorm#2004]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

We had to create a custom QueryRunner to solve some transactions problems we had, but when we lazy load a relation, TypeORM uses the default QueryRunner, is there a way for us to set our QueryRunner?

**Comment by pleerock** [comment]
This should already have been fixed by #1953 and will be released in 0.2.1 soon

**Comment by igor-ribeiro** [comment]
Nice! Thanks
