### ISSUE TITLE
Columns are being set to null after saving the entity

### ISSUE THREAD

**Issue by asvetliakov** [typeorm/typeorm#2006]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Repro:

```ts

@Entity()
class User {
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column("varchar", { nullable: true })
    token: string | null = null;
}

const u = new User();
u.token = "sometoken";

await db.manager.save(u);
u.token; // -> !!! null

const u2 = await db.manager.findOne(User, u.id);
u2.token; // "sometoken"

**Comment by pleerock** [comment]
Added test for this issue and everything works fine. Please provide more details.

@asvetliakov can you please next time create a failing test once you submit issues you can reproduce with a test.

**Comment by asvetliakov** [comment]
I added failing test. Sorry the repro example was incompleted.
