### ISSUE TITLE
@column should infer nullable property from variable declaration

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#201]
Can the @Column() decorator handle the following

```
@Column()
ua?: string
```

as equivalent to 

```
@Column({nullable: true})
ua?: string
```

?

**Comment by dcworldwide** [comment]
Asked the question here http://stackoverflow.com/questions/41648191/in-typescript-can-a-property-decorator-infer-an-optional-type

**Comment by pleerock** [comment]
no you can't. btw answered your question on stackoverflow too.

**Comment by dcworldwide** [comment]
Thanks. Wishful thinking.
