### ISSUE TITLE
error:  Argument of type '"timestamp"' is not assignable to parameter of type '(type?: any) => Function'

### ISSUE THREAD

**Issue by JingMo** [typeorm/typeorm#2010]
**Issue type:**

[ ] question

**Database system/driver:**

[ ] `mysql` / `mariadb`

**TypeORM version:**

[ ] `0.1.20`

**Steps to reproduce or a small repository showing the problem:**

@Column('timestamp', {
    nullable: true,
    default: () => 'CURRENT_TIMESTAMP',
    onUpdate: 'CURRENT_TIMESTAMP',
  })
  last_modify_time: Date;

[ts]error:  Argument of type '"timestamp"' is not assignable to parameter of type '(type?: any) => Function'

How to resolve ? Thanks!

**Comment by pleerock** [comment]
I think onUpdate is supported in 0.2.0 so you need to check this issue with 0.2.0
