### ISSUE TITLE
Question: Why doesn't the transaction below rollback on exception?

### ISSUE THREAD

**Issue by tomer-ben-david** [typeorm/typeorm#2013]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```typescript
import "reflect-metadata";
import {
    createConnection, EntityManager, Transaction, TransactionManager,
    useContainer
} from "typeorm";
import {User} from "./entity/User";
import {Container, Inject, Service} from "typedi";


useContainer(Container);
createConnection().then(async connection => {
    // await Container.get(FamilyService).save();
    await new FamilyService().save()
}).catch(error => console.log(error));

const parent = new User();
parent.firstName = "ParentFirst";
parent.lastName = "ParentLas";
parent.age = 40;

const child = new User();
child.firstName = "ChildFirst";
child.lastName = "ChildLas";
child.age = 9;

@Service()
export class ParentDAO {
    @Transaction()
    save(user: User, @TransactionManager() manager?: EntityManager) {
        return manager.save(user);
    }
}

@Service()
export class ChildDAO {
    @Transaction()
    save(user: User, @TransactionManager() manager?: EntityManager) {
        const ret = manager.save(user);
        throw new Error("exception in child"); // I Expected this exception to roll back the transaction why isn't it doing so?
        // return ret;
    }
}

@Service()
export class FamilyService {

    @Transaction()
    async save() {
        await Promise.all([
            Container.get(ParentDAO).save(parent),
            Container.get(ChildDAO).save(child) // The child.save is throwing an exception why isn't it rolling back the transaction? how can I make it roll back automatically?
        ]);
    }
}
```

Result in DB:

```sql
SELECT * FROM public.user;
 id |  firstName  | lastName  | age 
----+-------------+-----------+-----
 79 | ParentFirst | ParentLas |  40
 80 | ChildFirst  | ChildLas  |   9
(2 rows)
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
`Transaction` and `TransactionManager` decorators were created to use it in packages like routing-controllers and are very specific and not for general use. They are specific because of the way we override method and need to inject entity manager. I recommend avoid using them until you do/use packages like routing-controllers

**Comment by tomer-ben-david** [comment]
I see thanks, I will read about the routing-controllers, what is the recommended way for me to have some kind of the main method (service) that calls two dao's and if one of the dao fails then rollback the transaction (without explicit beginTransaction, commitTransaction, rollbackTransaction).  What I try to find out is whether I can do anything like the below (evaluating the library I want to recommend it):

```typescript
async main() {
  parentDAO.save(user);
  childDAO.save(user); // in case of exception here I want the above parentDAO to fail the transaction.
}
```

Is there any best practice recommended way to achieve the above?

**Comment by pleerock** [comment]
```ts
createConnection().then(async connection => {
    await connection.manager.transaction(async manager => {
            await manager.save(user1);
            await manager.save(user2);
            /// ...
    });
}).catch(error => console.log(error));
```

**Comment by tomer-ben-david** [comment]
Thanks, I actually started with an example as above, however, I then told myself that in a real project I will have multiple DAO's and multiple Services and I will surely have a scenario where one service will contact multiple DAOs and I would want them all to be in the same transaction.  In this example, I need all the DAO logic which should share the same transaction to reside inside the `connection.manager.transaction` block.  

Is there a way for me to have separate logic in separate DAO and share the same transaction?

**Comment by pleerock** [comment]
you have to implicitly pass `manager` created by transaction and use it everywhere. Alternative is to use scoped services, this is a bit more complex topic and requires you to build your own framework specific to your architecture to achieve this functionality (for example you can create transaction-per-request, use scoped container, store transactional entity manager inside scoped container, and execute all your services in that scoped container).

**Comment by tomer-ben-david** [comment]
ok, thanks.  So passing the manager as an argument is one option.  And if I want to build a more robust library for fellow developers to use and to enforce transactions in a more seamless way then I should read about scoped containers - I'm trying to think where to go from here, how to explore this, I'm new to this.  

So for `scoped containers` is it a term from `typedi`, so I should read about it at: [Using multiple containers and scoped containers](https://www.npmjs.com/package/typedi#using-multiple-containers-and-scoped-containers)? This is where I planned to continue from here.

**Comment by pleerock** [comment]
scoped containers is actually container isolation level and this term comes from other containers and DI, its not typedi-specific. Also if you can checkout [vesper-framework](https://github.com/vesper-framework/vesper) - I implemented typeorm + typedi scoped containers concept in there.

**Comment by tomer-ben-david** [comment]
Many thanks the information is extremely helpful.  Just one more question (for now :) ) what does `implicitly passing` manager means? I know `implicit parameter` from scala, what was the meaning here?

**Comment by pleerock** [comment]
ahh sorry I wanted to say explicitly haha

**Comment by tomer-ben-david** [comment]
Hi, I'm trying first with the first option of passing `explicitly` the manager, I tried the below which returns a failed promise for adding child, I expected the whole of the transaction to be rolled back but at the end in database I get:

```sql
=> SELECT * FROM public.user;
 id  |  firstName  | lastName  | age 
-----+-------------+-----------+-----
 110 | ParentFirst | ParentLas |  40
 111 | ChildFirst  | ChildLast |   9
(2 rows)
```
my code:

```typescript
@Service()
export class ParentDAO {
    save(user: User, manager: EntityManager): Promise<User> {
        return manager.save(user);
    }
}

@Service()
export class ChildDAO {
    save(user: User, manager: EntityManager): Promise<User> {
        let ret = manager.save(user);
        if (1 > 0) {
            ret = Promise.reject(new Error("problem in child")); // I reused the param manager I expected the caller transaction to get rolled back..
        }
        return ret;
    }
}

@Service()
export class FamilyService {

    @Transaction()
    async save(@TransactionManager() manager?: EntityManager) {
        await Promise.all([
            Container.get(ParentDAO).save(parent, manager),
            Container.get(ChildDAO).save(child, manager)
        ]);
    }
}
```

Log:

```
➜  my-service git:(master) ✗ npm start

> node-typescript-boilerplate@0.0.0 start /Users/myuserd/dev/my-service
> ts-node src/index.ts

Error: problem in child
    at ChildDAO.save (/Users/myuserd/dev/my-service/src/index.ts:45:34)
    at FamilyService.save (/Users/myuserd/dev/my-service/src/index.ts:58:37)
    at /Users/myuserd/dev/my-service/src/decorator/transaction/Transaction.ts:74:39
    at EntityManager.<anonymous> (/Users/myuserd/dev/my-service/src/entity-manager/EntityManager.ts:110:34)
    at step (/Users/myuserd/dev/my-service/node_modules/typeorm/entity-manager/EntityManager.js:32:23)
    at Object.next (/Users/myuserd/dev/my-service/node_modules/typeorm/entity-manager/EntityManager.js:13:53)
    at fulfilled (/Users/myuserd/dev/my-service/node_modules/typeorm/entity-manager/EntityManager.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Do I misunderstand it?
