### ISSUE TITLE
"column Y of Entity X does not support length property" for foreign key varchar Column 

### ISSUE THREAD

**Issue by itavq** [typeorm/typeorm#2014]
**Issue type:**
[X ] bug report

**Database system/driver:**
[X] `mysql` / `mariadb`

**TypeORM version:**
[X] `latest`

I have this QuestDraftApp entity:
```
@Entity("quest_draft_app")
@Index("quest_draft_app_revision",["Id","LiveRevisionid",])
export class QuestDraftApp {

    @OneToOne(type=>QuestDrafts, Id=>Id.quest_draft_app,{ primary:true, nullable:false,onDelete: 'RESTRICT',onUpdate: 'RESTRICT' })
    @JoinColumn({ name:'Id'})
    Id:QuestDrafts;
...
```
with the Id column being foreign key to QuestDraft.Id which is of type varchar with length 50
```
@Entity("quest_drafts")
@Index("quest_drafts_MentorId",["MentorId",])
@Index("quest_drafts_liveParentQuestId",["LiveParentQuestId",])
export class QuestDrafts {

    @Column("varchar",{
        nullable:false,
        length:50,
        primary:true,
        name:"Id"
        })
    Id:string;
```
on runtime I'm getting this exception

> Error: Column Id of Entity QuestDraftApp does not support length property.
>     at \node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:75:27
>     at Array.forEach (<anonymous>)
>     at EntityMetadataValidator.validate (\node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:70:36)
>     at \node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:41:74
>     at Array.forEach (<anonymous>)
>     at EntityMetadataValidator.validateMany (\node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:41:25)
>     at Connection.buildMetadatas (\node_modules\typeorm\connection\Connection.js:515:33)
>     at Connection.<anonymous> (\node_modules\typeorm\connection\Connection.js:162:30)
>     at step (\node_modules\typeorm\connection\Connection.js:32:23)
>     at Object.next (\node_modules\typeorm\connection\Connection.js:13:53)

I note that lately the length property was removed https://github.com/typeorm/typeorm/issues/1872 from numeric types for mySql but as this is varchar type I'm not sure what's the reason here.

**Comment by pleerock** [comment]
There are tests which use length + varchar in mysql and they successfully path. Can you please create a minimal reproduction git repo?

**Comment by itavq** [comment]
@pleerock 
Here is a minimal reproduction git repo:
https://github.com/itavq/typeorm_issue_2014

The MySql DDL is commented out inside app.ts file.

Thanks

**Comment by pleerock** [comment]
You have a wrong `@JoinColumn` definition.

either change it to simply:

```ts
@JoinColumn()
```

either if you want custom names, provide a correct number of columns:

```ts
    @JoinColumn([
        { name: "id1", referencedColumnName: "Id" },
        { name: "id2", referencedColumnName: "Revision" },
    ])
```

The issue you are currently facing is that you specify a single name and typeorm doesnt know to which of two columns it needs to set your provided name

**Comment by itavq** [comment]
@pleerock thanks a lot!
