### ISSUE TITLE
Wrong PK after save

### ISSUE THREAD

**Issue by kyle-mccarthy** [typeorm/typeorm#2015]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[x ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Here is a sample to test with:
https://github.com/kyle-mccarthy/typeorm-pk-after-save

```
  [...Array(5).keys()].forEach(async key => {
      const post = new Post();
      post.title = lorem.words(7);
      post.description = lorem.words(15);
      post.content = lorem.words(100);
      await post.save();
      console.log(post.id);
    });
```

Expect:

```
1
2
3
4
5
```

Have:

```
4
4
4
4
5
```

If you print the whole object, you can see that the posts are different but will have the same PK.

I noticed this in my test cases and use sql.js for that environment, but I haven't been able to try it on other DBs.

**Comment by pleerock** [comment]
This is only sqljs-specific issue because sqljs does not return us a generated id back. Instead we have to use `SELECT last_insert_rowid()` query to get latest id, but it requires users to execute queries in a sequence. Here is modified version of your code that resolves this issue:

```ts
import { Connection, createConnection, PromiseUtils } from 'typeorm';

    await PromiseUtils.runInSequence([...Array(5).keys()], async key => {
      const post = new Post();
      post.title = lorem.words(7);
      post.description = lorem.words(15);
      post.content = lorem.words(100);
      await post.save();
      posts.push(post);
      console.log(post.id);
    });
```

adding @daniel-lang

**Comment by kyle-mccarthy** [comment]
@pleerock Okay I actually wasn't aware of that limitation with sql.js.  I know it technically isn't your problem, but it may be helpful to note that somewhere in the docs.  I thought that it was a little confusing because I would feel like if it couldn't guarantee that the ID was right, it would defer to not setting it at all.

**Comment by daniel-lang** [comment]
The only two places would be `supported-platforms` or `connections-options` but I'm afraid, that not a lot of people will look for this kind of information there.
Don't know if this is something we could detect in code and output a warning at runtime. But this might be the best solution.

**Comment by pleerock** [comment]
Another option is to add it to FAQ... but not sure how frequent is this question.

**Comment by filipjnc** [comment]
Can be closed?
