### ISSUE TITLE
TypeError: Cannot read property 'joinColumns' of undefined

### ISSUE THREAD

**Issue by PavanBahuguni** [typeorm/typeorm#2016]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
**Entities:**
```
@Entity()
export class DatasourceAction {

    @PrimaryGeneratedColumn()
    id: string;

    @Column({ name: 'name', type: 'text' })
    name: string;

    @Column({ name: 'action', type: 'text' })
    action: string;

    @Column({ name: 'id_datasource', type: 'varchar' })
    datasourceId: string;

    @ManyToOne(type => Datasource)
    @JoinColumn({ name: 'id_datasource' })
    datasource: Datasource;
}

@Entity('datasource')
export class Datasource {
    @PrimaryColumn()
    id: string;

    @Column({ name: 'status', type: 'text', default: 'none' })
    status: string;

    @Column({ name: 'electorate_size', type: 'int4', default: 0 })
    electorateSize: number;

    @OneToMany(type => DatasourceAction, datasourceAction => datasourceAction.datasourceId, {
        cascade: true
    })
    actions: Array<DatasourceAction>;
}

```
**Query**:

```
const dRepo = connection.getRepository(Datasource);
    const datasource = await dRepo.save({
      id: '11',
      status: 'none',
      electorateSize: 101,
      actions: [
        {
          id: '5',
          name: 'action one',
          action: 'add',
          datasourceId: '11',
        }
      ]
    });
```

If I do the dRepo.save for the first time, it inserts the entries into DB. But when I use the same object and call dRepo.save for the second time to update, it throws the below error.

**Stack trace:**
```
(node:94008) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'joinColumns' of undefined
    at RelationIdLoader.<anonymous> (/Users/pavanbahuguni/practice/nest/typeorm/node-ts-graphql-boilerplate/src/query-builder/relation-id/RelationIdLoader.ts:62:70)
    at step (/Users/pavanbahuguni/practice/nest/typeorm/node-ts-graphql-boilerplate/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:32:23)
    at Object.next (/Users/pavanbahuguni/practice/nest/typeorm/node-ts-graphql-boilerplate/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:13:53)
    at /Users/pavanbahuguni/practice/nest/typeorm/node-ts-graphql-boilerplate/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/pavanbahuguni/practice/nest/typeorm/node-ts-graphql-boilerplate/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:3:12)
    at /Users/pavanbahuguni/practice/nest/typeorm/node-ts-graphql-boilerplate/src/query-builder/relation-id/RelationIdLoader.ts:26:76
    at Array.map (<anonymous>)
    at RelationIdLoader.<anonymous> (/Users/pavanbahuguni/practice/nest/typeorm/node-ts-graphql-boilerplate/src/query-builder/relation-id/RelationIdLoader.ts:26:52)
    at step (/Users/pavanbahuguni/practice/nest/typeorm/node-ts-graphql-boilerplate/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:32:23)
(node:94008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handledwith .catch(). (rejection id: 3)

```

**Comment by pleerock** [comment]
your `datasource` relation missing inverse side. You need to specify to point to `actions`

**Comment by PavanBahuguni** [comment]
@pleerock 
I have ManyToOne defined in DatasourceAction , and OneToMany defined in Datasource. Both sides of the relation are defined. What is wrong in the above code?

**Comment by pleerock** [comment]
@PavanBahuguni please read docs carefully about how to create bi-directional relations. THIS DOES NOT HAVE INVERSE SIDE:

```ts
@ManyToOne(type => Datasource)
    @JoinColumn({ name: 'id_datasource' })
    datasource: Datasource;
```

what it should be is:

```ts
@ManyToOne(type => Datasource, datasource => datasource. actions)
    @JoinColumn({ name: 'id_datasource' })
    datasource: Datasource;
```

**Comment by PavanBahuguni** [comment]
@pleerock This worked. Thank you.

**Comment by kashkashio** [comment]
> @PavanBahuguni please read docs carefully about how to create bi-directional relations. THIS DOES NOT HAVE INVERSE SIDE:
> 
> ```ts
> @ManyToOne(type => Datasource)
>     @JoinColumn({ name: 'id_datasource' })
>     datasource: Datasource;
> ```
> 
> what it should be is:
> 
> ```ts
> @ManyToOne(type => Datasource, datasource => datasource. actions)
>     @JoinColumn({ name: 'id_datasource' })
>     datasource: Datasource;
> ```

damn you saved me an hour bro xoxo

**Comment by grapereader** [comment]
Bidirectional relation not required though. ManyToOne is only needed on the side that holds the foreign key.

**Comment by coayscue** [comment]
> Bidirectional relation not required though. ManyToOne is only needed on the side that holds the foreign key.

Yes, so just adding @JoinColumn() on the side that holds the foreign key fixes the error. A little simpler than the other solution.

**Comment by ruslan-sh-r** [comment]
Just in case anyone faced with the same issue. 
In
```   
    @OneToMany(type => DatasourceAction, datasourceAction => datasourceAction.datasourceId, {
        cascade: true
    })
    actions: Array<DatasourceAction>;
```
replacing `datasourceAction => datasourceAction.datasourceId` with `datasourceAction => datasourceAction.datasource` should solve an issue without any other changes

**Comment by nioc** [comment]
Thanks @ruslan-sh-r for your answer, you saved my night :)
May be [this documentation](https://typeorm.io/many-to-many-relations#many-to-many-relations-with-custom-properties) should be updated.
