### ISSUE TITLE
How to publish compiled into production

### ISSUE THREAD

**Issue by coldpc** [typeorm/typeorm#2019]
**Issue type:**

[ ] question

I am a developer from China, thank you very much typeorm team.I use the typeorm - cli command structures, development environment, the development is complete now.How to publish compiled into production?

I tried to use ts - node command  'TSC compilation mode, but it doesn't  work.

**Comment by coldpc** [comment]
No, I think it's related to typeorm! 
I use a quick start, commond: 'typeorm init --name MyProject --database mysql --express'.
 I had been configuration file ormconfig.json，so I can connected the database with no config.
![image](https://user-images.githubusercontent.com/22537073/39235700-36eef7f2-48a9-11e8-9884-e5a0f46bdbf7.png)

But I complied project how can I use the ormconfig.json. I must  write the config in the code.
![image](https://user-images.githubusercontent.com/22537073/39235716-45367740-48a9-11e8-8e70-c7e8b8a8caf5.png)

I think it should have a more convenient method.
If you still not understand my question, it may be I don't really understand quick star typeorm cli. 
I'm sorry to have bothered you!

**Comment by pleerock** [comment]
> But I complied project how can I use the ormconfig.json. I must write the config in the code.

no, you should not. ormconfig.json is being automatically loaded from your project root path (near package.json and node_modules)

**Comment by coldpc** [comment]
Thank you very much, you gave me the inspiration.
 I have already solved the problem.
Where did I know the problem, because I compiled after the completion of the entities should put the corresponding path to directory compiled, so I just need to add a  compiled path.
 Very excited, thanks again!
![image](https://user-images.githubusercontent.com/22537073/39298004-9f40fb1a-4977-11e8-9251-4fd6147f4b6f.png)

**Comment by cassioseffrin** [comment]
> **Issue type:**
> 
> [ ] question
> 
> I am a developer from China, thank you very much typeorm team.I use the typeorm - cli command structures, development environment, the development is complete now.How to publish compiled into production?
> 
> I tried to use ts - node command 'TSC compilation mode, but it doesn't work.
take a look
https://github.com/typeorm/typeorm/issues/6997#issuecomment-955139814
