### ISSUE TITLE
Migrations Keep Generating Same File

### ISSUE THREAD

**Issue by sslgeorge** [typeorm/typeorm#2023]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I upgraded from version 0.1.6 to version 0.2, and when I tried generation migration for a new Entity I had created, Alter table queries were also created, all foreign keys were recreated, I decided to delete my old migrations and create a fresh single file that will migrate my whole system, but it keeps generating the same migration over and over without stopping

```
await queryRunner.query("ALTER TABLE `leave_extra` CHANGE `validTo` `validTo` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `leave_extra` CHANGE `validFrom` `validFrom` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `dateOfBirth` `dateOfBirth` datetime(0) NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `dateJoined` `dateJoined` datetime(0) NULL");
        await queryRunner.query("ALTER TABLE `leave_request` CHANGE `toDate` `toDate` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `leave_request` CHANGE `fromDate` `fromDate` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `leave_entitlement` CHANGE `validTo` `validTo` datetime(0) NOT NULL");
        await queryRunner.query("ALTER TABLE `leave_entitlement` CHANGE `validFrom` `validFrom` datetime(0) NOT NULL");
```

In my case the above keeps being created without end.
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
did you run your migration after you generate it for the first time?

**Comment by sslgeorge** [comment]
@pleerock Yes I did

**Comment by pleerock** [comment]
then please provide some repository with minimal reproduction where I can test this issue.

**Comment by sslgeorge** [comment]
Closing issue as I was unable to reproduce the issue
