### ISSUE TITLE
@CreateDateColumn & @UpdateDateColumn not using same timezone or something else ?

### ISSUE THREAD

**Issue by harishajdarevic** [typeorm/typeorm#2025]
**Issue type:**

[X] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[0.2.0-alpha.13] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
So problem is pretty straightforward for explanation. 

I have two columns in model defined as

```
    @UpdateDateColumn({
        name: "updated_at",
        type: "timestamp" })
    public updatedAt?: Date;

    @CreateDateColumn({
        name: "created_at",
        type: "timestamp",
    })
    public createdAt?: Date;
```

For updatedAt everything is good and date is saved in UTC format which is set on postgres db, but for created_at time is totally different 5 hours behind updated_at.

Fresh example:

created_at: 2018-04-25 08:01:59.094242
updated_at: 2018-04-25 12:37:10.039394

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [] `mysql`
    [X] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
I think you shall update to the latest version, since timezone and utc stuff behaviour was changed.

**Comment by chanlito** [comment]
I'm having this issue right now, `@CreateDateColumn` and `@UpdateDateColumn` is storing as UTC, while my own is storing as local.
```
@Column({ name: 'expired_date', type: 'datetime', precision: 6 })
expiredDate: Date;
``` 

So I change timezone config to `timezone: 'Z'`. 

Now all values store as UTC.

But when retrieve it back, it convert the UTC with UTC again.

**Comment by chanlito** [comment]
@harishajdarevic u may wanna take a look at this https://github.com/typeorm/typeorm/issues/1999#issuecomment-386235994

**Comment by chanlito** [comment]
@pleerock for me yes

**Comment by pleerock** [comment]
Okay, good
