### ISSUE TITLE
Error saving entity with composite key using a repository

### ISSUE THREAD

**Issue by ldadams** [typeorm/typeorm#2027]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Seeing an issue when attempting to save an entity with a composite key via a repository.  Typeorm is attempting to insert rather then update and returning `QueryFailedError: duplicate key value violates unique constraint "PK_1615d1e911edb86a12d7a14eb70"`.  I was not seeing this error when using Entities directly and `connection.manager.save()`.

Stepping through the code the below image indicates the difference in the comparison.  Note that Argument[0] is an object with two properties, collection and file, and Argument[1] is an Object with two nested objects collection and file.

![screen shot 2018-04-24 at 4 52 19 pm](https://user-images.githubusercontent.com/1102442/39259062-8c624d86-4883-11e8-820d-3e5b3aea34f6.png)

PR forthcoming with test to reproduce.

Thanks!

**Comment by ldadams** [comment]
PR created here:
https://github.com/typeorm/typeorm/pull/2028

**Comment by ldadams** [comment]
OK an update.  It appears the issue is that it's required to explicitly separate the Pr

Old:
`
@Entity("collection_file")
export class CollectionFile {

    @ManyToOne(type => File, file => file.collections)
    @PrimaryColumn({type: "uuid", name: "file_id"})
    @JoinColumn({name: "file_id"})
    file!: File;

    @ManyToOne(type => Collection, collection => collection.files)
    @PrimaryColumn({type: "uuid", name: "collection_id"})
    @JoinColumn({name: "collection_id"})
    collection!: Collection;

    @Column({type: "bigint"})
    sort: number;
}
}`

New
`@Entity("collection_file")
export class CollectionFile {
    @PrimaryColumn({type: "uuid", name: "file_id"})
    fileId: string;

    @ManyToOne(type => File, file => file.collections)
    @JoinColumn({name: "file_id"})
    file!: File;

    @PrimaryColumn({type: "uuid", name: "collection_id"})
    collectionId: string;

    @ManyToOne(type => Collection, collection => collection.files)
    @JoinColumn({name: "collection_id"})
    collection!: Collection;

    @Column({type: "bigint"})
    sort: number;
}`

**Comment by pleerock** [comment]
so, your issue is fixed?

**Comment by ldadams** [comment]
Yes issued resloved.

**Comment by 592da** [comment]
I am having the exact same problem, do you use the `next` branch ?

**Comment by muhammadnasr** [comment]
The issue still happen with latest typeorm version.
