### ISSUE TITLE
Advanced find options with FKs

### ISSUE THREAD

**Issue by Ryan104** [typeorm/typeorm#2031]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
[repo with example](https://github.com/Ryan104/fk-where-bug)

The advanced find options (In, Equal, etc) are not working on columns that are used for relationships.

For example if I wanted to find photos belonging to several users in a ManyToOne relationship:
```ts
const photos = await connection.manager.find(Photo, { where: { userId: In([1,2,3]) } });
```

This is returning an empty array.

Thank you.

**Comment by pleerock** [comment]
Its a bug, I committed a fix and it will be released in 0.2.3

I created a test for your use case, would be great if you next time create a PR with a failing test directly instead of git repository, thanks
