### ISSUE TITLE
Tree closure table is not updated on parent update

### ISSUE THREAD

**Issue by oorooroot** [typeorm/typeorm#2032]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Closure table is not updated when previously created entity updates its parent.

```import 'reflect-metadata';
import * as path from 'path';
import { createConnection, ConnectionOptions, getTreeRepository } from 'typeorm';
import { PrimaryGeneratedColumn, Column, Tree, TreeChildren, TreeParent, Entity } from 'typeorm';

@Entity()
@Tree("closure-table")
export class TestEntity {
	@PrimaryGeneratedColumn() id: number;
	@TreeChildren()
	children: TestEntity[];
	@TreeParent() parent: TestEntity;
}

var connectionOptions: ConnectionOptions = {
    type: 'sqlite',
    database: path.join(__dirname, 'test.db'),
    entities: [ TestEntity ],
    synchronize: true,
    logging: true,
    dropSchema: true
};

createConnection(connectionOptions).then(async (c) => {
    var repo = getTreeRepository(TestEntity);
    
    var parent1 = new TestEntity;
    await repo.save(parent1);
    var parent2 = new TestEntity;
    await repo.save(parent2);
    var child = new TestEntity;

    child.parent = parent1;
    await repo.save(child);
    console.log(...await repo.query(`SELECT * FROM ${repo.metadata.closureJunctionTable.name}`));
    
    child.parent = parent2;
    await repo.update(child.id, child);
    console.log(...await repo.query(`SELECT * FROM ${repo.metadata.closureJunctionTable.name}`));
});
```

**Comment by SharmaTushar** [comment]
https://github.com/typeorm/typeorm/blob/c654d5228ccdd867557cf0754e13d47cc2211186/src/repository/TreeRepository.ts#L13

I guess ability to change parent hasn't been implemented yet.

**Comment by linfan68** [comment]
I think this should be explicitly pointed out in the document.

**Comment by jtushman** [comment]
What is the current work around for this that people have implemented?

is it as simple as explictly updating the closure table?:

untested code:
```
      await connection
        .createQueryBuilder()
        .update('group_closure')
        .set({ "id_ancestor":  newParentId})
        .where('"id_descendant" = :id', { id: childId })
        .execute();
```

are there other considerations?

**Comment by dhruska** [comment]
I've opened a PR to add a note about this to the closure table section of the Tree Entity docs
https://github.com/typeorm/typeorm/pull/5179

**Comment by jeanpchr** [comment]
To the developers and contributors, thanks for the project it is a great tool.
With regards to this issue, was this behavior not implemented due to lack of time or on account of some database specificity that was hard to overcome?

**Comment by joyce-adelle** [comment]
//not a complete solution but works for moving subtrees
  async updateCategory(
    id: string,
    category: UpdateCategory
  ): Promise<Category> {
    try {
      let categoryDet = await this.findCategoryById(id);
      if (category.name) {
        categoryDet.name = category.name;
      }
      if (category.parentId) {
        if (category.parentId.toLowerCase() === "null") {
          categoryDet.parent = null;
        } else {
          categoryDet.parent = await this.findCategoryById(category.parentId);
        }

        await getConnection().query(
          `DELETE a FROM category_closure AS a
          JOIN category_closure AS d ON a.id_descendant = d.id_descendant
          LEFT JOIN category_closure AS x
          ON x.id_ancestor = d.id_ancestor AND x.id_descendant = a.id_ancestor
          WHERE d.id_ancestor = ${id} AND x.id_ancestor IS NULL`
        );

        await getConnection().query(
          `INSERT INTO category_closure (id_ancestor, id_descendant)
          SELECT supertree.id_ancestor, subtree.id_descendant
          FROM category_closure AS supertree JOIN category_closure AS subtree
          WHERE subtree.id_ancestor = ${id}
          AND supertree.id_descendant = ${category.parentId}`
        );
      }
      let updatedCategory = await this.save(categoryDet);
      return updatedCategory;
    } catch (error) {
      throw new Error(error.message);
    }
  }

**Comment by alexey2baranov** [comment]
Does this bug relate to Postgress driver too?

**Comment by Xin2050** [comment]
Tested code, it works.

```
const sql = `UPDATE function_closure SET id_ancestor =${newParentId}  WHERE id_ancestor = ${oldParentId} AND id_descendant =${id} `;
        
        const result = await getManager().query(sql);
```

**Comment by eilrix** [comment]
This one worked for me with repository
`
@EntityRepository(Entity)
export class EntityRepository extends TreeRepository {

   async updateParent(entity, newParent) {
        const descendantColumn = this.metadata.closureJunctionTable.descendantColumns[0].databasePath;
        const ancestorColumn = this.metadata.closureJunctionTable.ancestorColumns[0].databasePath;
        const closureTableName = this.metadata.closureJunctionTable.tablePath;

        const currentParent = (await this.findAncestorsTree(entity)).parent;

        if (!currentParent) {
            // insert into closure table
            await this.createQueryBuilder()
                .insert()
                .into(closureTableName, [ancestorColumn, descendantColumn])
                .values({
                    [ancestorColumn]: { id: newParent.id },
                    [descendantColumn]: { id: entity.id },
                })
                .execute();
        }

        if (currentParent && currentParent.id !== newParent.id) {
            // update parent in closure table
            await this.createQueryBuilder()
                .update(closureTableName)
                .set({
                    [ancestorColumn]: { id: newParent.id },
                })
                .where(`${descendantColumn} = :id`, { id: entity.id })
                .andWhere(`${ancestorColumn} = :parentId`, { parentId: currentParent.id })
                .execute();
        }

        entity.parent = newParent;

        await this.save(entity);
    }
}
`

**Comment by xdrago1** [comment]
@eilrix unfortunately this is not working for me. It seems to work for for the first level, but if I try to change the parent to an entity which is an descendant on 3rd level or more, it runs into the same problem it seems. I did not check your code yet, just gave it a quick try.

**Comment by eilrix** [comment]
@xdrago1 I tested my code on 3,4,5 levels, it worked. Can you send me some reproduction examples?

Maybe you are trying to set a parent which is at the same time a descendant? In my implementation I do check it before using code above. I haven't included this check because it's quite slow, I simply used this.findDescendants, without query builder.

I'm temporarily building my project in a private repo, but I can post full EntityRepository code somewhere

**Comment by xdrago1** [comment]
> Maybe you are trying to set a parent which is at the same time a descendant? In my implementation I do check it before using code above. I haven't included this check because it's quite slow, I simply used this.findDescendants, without query builder.

Thanks for the reply. Yes I tried to set a parent which is also a descendant. In my scenario I want to be able to switch around parent-categories of categories in the tree.  Do you have an idea how to solve this or solved it already?

**Comment by eilrix** [comment]
@xdrago1 Assign a parent which is a descendant is not correct business logic for this kind of thing. 
Well, technically it's possible, and I just checked my code, it's working on saving, but when I'm trying to retrieve such category with children via GraphQL, I predictably get "call stack size exceeded" error. 
So I just forbid to assign such parent. Forbidding logic is up to you, mine was not perfect, but it may help:
https://codesandbox.io/s/product-category-repository-63j9epc-63j9e?file=/src/ProductCategoryRepository.ts:3669-412

**Comment by phil294** [comment]
> Updating or removing a component's parent has not been implemented yet (see this issue). The closure table will need to be explicitly updated to do either of these operations.

Is this specific to closure table trees, or also to nested set and materialized paths?

**Comment by tuyennv86** [comment]
const category = await this.findOne(id);
        const categoryParent = await this.findOne(createCategoryDto.parentId);
        const categoryParentOld = await this.findOne(category.parentId);

        const parentIdNew = createCategoryDto.parentId;
        const parentIdOld = category.parentId;
        const listChildren = await this.findDescendants(category);
        const listParent = await this.findAncestors(categoryParent);
        const listParentOld = await this.findAncestors(categoryParentOld);

        category.name = createCategoryDto.name;
        category.title = createCategoryDto.title;
        category.isPublished = createCategoryDto.isPublished;
        category.order = createCategoryDto.order;
        category.userId = createCategoryDto.userId;
        category.createDate = createCategoryDto.createDate;
        if (categoryParent) {
            category.parent = categoryParent;
        } else {
            category.parent = null;
        }

        await category.save();
        if (!categoryParent) {// nếu cha la null chuyển về root
            // update toa bộ nó và con của nó bằng chính id của nó
            listChildren.forEach(item => {
                this.query(`update category_closure set id_ancestor = ${category.id} where id_ancestor = ${category.id} and id_descendant = ${item.id}`);
            });
        } else {
            listChildren.forEach(item => { // update toàn bộ id_ancestor của nó và con của nó về id cha mới
                this.query(`update category_closure set id_ancestor = ${parentIdNew} where id_ancestor = ${parentIdOld} and id_descendant = ${item.id}`);
            });

            // từ cha về con của 1 đối tượng  kiểm tra xem id_ancestor = parentNew and id_descendant = idItem có hay chưa nếu chưa thì thêm vào
            listParent.forEach(item => {
                this.query(`INSERT INTO category_closure(id_ancestor,id_descendant) select ${item.id},${id} 
                where not exists ( select id_ancestor FROM category_closure WHERE id_ancestor = ${item.id} and id_descendant = ${id})`);
            })

            //xoa parentOld
            // listParentOld.forEach(item => {
            //     try {
            //         this.query(`DELETE FROM category_closure where id_ancestor = ${item.id} and id_descendant = ${id}`);
            //     } catch (error) {
            //         //throw new BadRequestException(JSON.stringify(error));
            //     }
            // });

**Comment by tuyennv86** [comment]
update all id_ancestor == parentNew

**Comment by DDevil97** [comment]
Seems this is not implemented on materialized-path either or i'm misunderstanding something. It updates the column 'mpath' but it only writes the start as if the object i'm inserting is the parent of the tree, even though the parentId column is getting updated with the correct value.

**Comment by tuyennv86** [comment]
>  writes the start as if the object i'm inserting is the parent of the tree, even though the parentI

You use Closure table

**Comment by DDevil97** [comment]
> > writes the start as if the object i'm inserting is the parent of the tree, even though the parentI
> 
> You use Closure table

The issue i described in my comment was using materialized path, but i'm going to check closure table, don't mind having an extra table for a feature to work properly

**Comment by tuyennv86** [comment]
> 
> 
> > > writes the start as if the object i'm inserting is the parent of the tree, even though the parentI
> > 
> > 
> > You use Closure table
> 
> The issue i described in my comment was using materialized path, but i'm going to check closure table, don't mind having an extra table for a feature to work properly

I just did the instance of the closure table update

**Comment by tuyennv86** [comment]
> 
> 
> > > > writes the start as if the object i'm inserting is the parent of the tree, even though the parentI
> > > 
> > > 
> > > You use Closure table
> > 
> > 
> > The issue i described in my comment was using materialized path, but i'm going to check closure table, don't mind having an extra table for a feature to work properly
> 
> I just did the instance of the closure table update

![4-22-2021 10-04-51 AM](https://user-images.githubusercontent.com/39330649/115649911-6873d700-a352-11eb-9b1a-b461d5c7e0f1.png)
