### ISSUE TITLE
CLI picks up ormconfig.example.json

### ISSUE THREAD

**Issue by sslgeorge** [typeorm/typeorm#2033]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.2` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
* Create a project
* Create an ormconfig.example.json file with different credentials from ormconfig.json
* Create an entity
* Run typeorm migration:generate -n EntityMigration

You will notice that ormconfig.example.json is used instead of ormconfig.json
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
Sounds strange. Are you able to contribute to this issue?

**Comment by sslgeorge** [comment]
Unable to reproduce this on another project, closing.
