### ISSUE TITLE
@Unique doesn't work in MongoDB

### ISSUE THREAD

**Issue by thonythony** [typeorm/typeorm#2034]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

```typescript
@Entity()
export class PackageSettings implements IPackageSettings {
    @ObjectIdColumn() id: ObjectID;

    @Column({ unique: true })
    @IsString()
    @IsNotEmpty()
    name: string;

    @Column('simple-json') value: object;
}
```
and 
```typescript
@Entity()
@Unique(['name'])
export class PackageSettings implements IPackageSettings {
    @ObjectIdColumn() id: ObjectID;

    @Column()
    @IsString()
    @IsNotEmpty()
    name: string;

    @Column('simple-json') value: object;
}
```
No index unique created in mongodb and no error thrown when I try to save multiple objects with same name attribute.

Is decorator @Unique only RDBMS-specific ?

**Comment by pleerock** [comment]
yes `@unique` is rdbms specific feature (it creates an UNQIUE CONSTRAINT, not UNIQUE INDEX), use `@Index` for mongodb, there is a flag called `unique`.

**Comment by thonythony** [comment]
Ok thanks for your reply. Where do I put the decorator `@Index` ? At column-level or entity-level ?

**Comment by thonythony** [comment]
I tried this :
```typescript
@Entity()
export class PackageSettings implements IPackageSettings {
    @ObjectIdColumn() id: ObjectID;

    @Column()
    @IsString()
    @IsNotEmpty()
    @Index({ unique: true })
    name: string;

    @Column('simple-json') value: object;
}
```
It doesn't work.

**Comment by pleerock** [comment]
can you contribute and create a test or example repo?

**Comment by thonythony** [comment]
https://github.com/thonythony/typeorm-index-mongo

```bash
npm i && npm run test
```

Thanks for your help

**Comment by ruscon** [comment]
`@Index({ unique: true }) `
I checked on version 0.2.3, it works for me

**Comment by thonythony** [comment]
@ruscon I tested with 0.2.3 and no indexes created.
@pleerock I updated my repo, I removed jest. All code is now in src folder, and for execute it, simply type ```npm run test```

**Comment by pleerock** [comment]
You need to put `synchronize: true` in your connection options. This flag executes indices synchronization

**Comment by thonythony** [comment]
Ok thanks for your reply, I will test that

**Comment by gruckion** [comment]
I am getting the following

```
{ MongoError: The field 'unique' is not valid for an _id index specification. Specification: { ns: "5d22b6c5c56c98a72dcad7fc_test.instructor", v: 2, name: "IDX_e4a0b766819b48202dd4245951", key: { _id: 1 }, unique: false, sparse: false, background: false }
    at Connection.<anonymous> (D:\repos\incessus\Incessus-Api\node_modules\mongodb\lib\core\connection\pool.js:466:61)
    at Connection.emit (events.js:198:13)
    at processMessage (D:\repos\incessus\Incessus-Api\node_modules\mongodb\lib\core\connection\connection.js:364:10)
    at TLSSocket.<anonymous> (D:\repos\incessus\Incessus-Api\node_modules\mongodb\lib\core\connection\connection.js:533:15)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  operationTime:
   Timestamp { _bsontype: 'Timestamp', low_: 4, high_: 1564645466 },
  ok: 0,
  errmsg:
   'The field \'unique\' is not valid for an _id index specification. Specification: { ns: "5d22b6c5c56c98a72dcad7fc_test.instructor", v: 2, name: "IDX_e4a0b766819b48202dd4245951", key: { _id: 1 }, unique: false, sparse: false, background: false }',
  code: 197,
  codeName: 'InvalidIndexSpecificationOption',
  '$clusterTime':
   { clusterTime:
      Timestamp { _bsontype: 'Timestamp', low_: 4, high_: 1564645466 },
     signature: { hash: [Binary], keyId: [Long] } },
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }

```

Here is my ormconfig.json

```json
{
    "type": "mongodb",
    "useNewUrlParser": true,
    "url": "mongodb+srv://x:y@cluster.net/test?retryWrites=true&w=majority",
    "synchronize": true,
    "logging": false,
    "entities": [
        "src/entities/**/*.ts"
    ],
    "migrations": [
        "src/migration/**/*.ts"
    ],
    "subscribers": [
        "src/subscriber/**/*.ts"
    ],
    "cli": {
        "entitiesDir": "src/entities",
        "migrationsDir": "src/migration",
        "subscribersDir": "src/subscriber"
    }
}
```

Here is my entity. I would like each user to have a unique email address.

```ts
import {
    Entity,
    Column,
    CreateDateColumn,
    UpdateDateColumn,
    ObjectIdColumn,
    Index
} from "typeorm";
import { Length, IsNotEmpty, IsDate } from "class-validator";
import * as bcrypt from "bcryptjs";

export type Role = "ADMIN" | "INSTRUCTOR" | "STUDENT" | "ANONYMOUS";

@Entity()
export class User {
    @ObjectIdColumn()
    public id: string;

    @Column()
    @Length(1, 20)
    public givenName: string;

    @Column()
    @Length(1, 20)
    public familyName: string;

    @Column()
    @IsDate()
    public dateOfBirth: Date;

    @Column()
    @Length(4, 100)
    public password: string;

    @Column()
    @Length(4, 320)
    @Index({ unique: true })
    public email: string;

    @Column()
    @IsNotEmpty()
    public role: Role;

    @Column()
    @CreateDateColumn()
    public createdAt: Date;

    @Column()
    @UpdateDateColumn()
    private updatedAt: Date;

    public hashPassword() {
        this.password = bcrypt.hashSync(this.password, 8);
    }

    public checkIfUnencryptedPasswordIsValid(
        unencryptedPassword: string
    ): boolean | null {
        if (!(unencryptedPassword || this.password)) {
            return null;
        }
        return bcrypt.compareSync(unencryptedPassword, this.password);
    }

    public static accessibleProperties = (): (keyof User)[] => [
        "id",
        "givenName",
        "familyName",
        "dateOfBirth",
        "email",
        "role"
    ];
}

```

**Comment by bymi15** [comment]
Is it possible to have multiple unique indices with mongodb?
For instance with `@Unique` decorator, you could do:
`@Unique(["lastName", "middleName"])`
Is there an equivalent with `@Index`?

**Comment by SalahAdDin** [comment]
This is a persistent bug today:
```typescript
@Entity()
@Unique(['id', 'username'])
export class UserAccountEntity {
  @ObjectIdColumn()
  _id: string;

  @PrimaryColumn()
  id: string;

  @Column()
  userId: string;

  @Column({ unique: true })
  username: string;
```

I had to enforce it by adding the flag on the respective column because the decorator does not work.

Yes, I'm using **MongoDB**.

**Comment by rishabh0504** [comment]
Any update regarding this issue?

**Comment by LouisMazel** [comment]
Up !

**Comment by jr091291** [comment]
Para mi funciono agregando  app.useGlobalPipes(new ValidationPipe())}; en el main.

`import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';

import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter({ logger: true }),
  );
  app.enableCors();
  app.useGlobalPipes(new ValidationPipe());

  await app.listen(process.env.PORT, '0.0.0.0');
}
bootstrap();
`

`import {
  Entity,
  Column,
  OneToOne,
  JoinColumn,
  ObjectIdColumn,
  Index
} from 'typeorm';
import { Field, ID, ObjectType} from '@nestjs/graphql';
import { UserInfo } from './user-info.entity';
import { IsEmail, IsNotEmpty, IsString } from 'class-validator';

@Entity({name: "users"})
@ObjectType()
export class User {
  @Field(() => ID)
  @ObjectIdColumn()
  readonly userId: string;

  @Field()
  @Column()
  @IsEmail()
  @Index({ unique: true })
  email: string;

  @Field()
  @Column({ length: 60 })
  @IsNotEmpty()
  password: string;
}`
`import { Global, Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { UserInfo } from 'src/users/entities/user-info.entity';
import { UserPhone } from 'src/users/entities/user-phone.entity';
import { User } from 'src/users/entities/user.entity';


@Global()
@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        type: 'mongodb',
        host: configService.get('MONGODB_HOST'),
        port: parseInt(configService.get('MONGODB_PORT')),
        username: configService.get('MONGODB_USERNAME'),
        password: configService.get('MONGODB_PASSWORD'),
        database: configService.get('MONGODB_DATABASE'),
        entities: [User, UserInfo, UserPhone],
        migrations: [],
        authSource: 'admin',
        logging: true,
        useNewUrlParser: true,
        useUnifiedTopology: true,
        synchronize: false 
      }),
      inject: [ConfigService],
    })
  ],
  exports: [DatabaseModule],
})
export class DatabaseModule {}
`

**Comment by FelipeRomao** [comment]
> Você precisa colocar `synchronize: true`suas opções de conexão. Este sinalizador executa a sincronização de índices

this worked for me

**Comment by TBG-FR** [comment]
> You need to put `synchronize: true` in your connection options. This flag executes indices synchronization

[That's not recommend in production ](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md#how-migrations-work), so... what should we do ?
