### ISSUE TITLE
@BeforeUpdate Not called when using Model.update(id, args)

### ISSUE THREAD

**Issue by serranoarevalo** [typeorm/typeorm#2036]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi. I've got a function with the ```@BeforeUpdate``` decorator that is not being called when I use ```Model.update(id, args)```

My model is extending from ```BaseEntity```

Is this expected? On the listeners-subscribers documentation it says that ```@BeforeUpdate``` gets called on .save(), shouldn't it be also called on .update()?

Repo: https://github.com/serranoarevalo/nuber/tree/33d2e729a36c8fb08d721a5453e5c2d03d24e8d4

**Example of the GraphQL Resolver**:

````
updateUser: async (parent, args, { entities: { User } }) => {
      try {
        await User.update(args.id, args);
        return true;
      } catch (error) {
        console.log(error);
        return false;
      }
    }
````

**Example of the model** 

````
@Entity()
class User extends BaseEntity {
...
@BeforeUpdate()
  async updatePassword(): Promise<void> {
    if (this.password) {
      const hashedPassword = await this.hashPassword(this.password);
      this.password = hashedPassword;
    }
  }
}
````

Anyways thanks for the great work and for looking into this!

N.

**Comment by pleerock** [comment]
`updatePassword` is an instance method. when you do `User.update(args.id, args)` there is **no** instance of user on which we can call `user.updatePassword()`.

**Comment by serranoarevalo** [comment]
So by calling User.update I'm not updating an entity?

**Comment by pleerock** [comment]
```ts
const post = new Post();
post.title = "hello";
User.update(entity); // TypeORM calls post.updatePassword() inside
```

In your case:

```ts
User.update(args.id, args); // there is no object on which typeorm can call .updatePassword() method
```

**Comment by serranoarevalo** [comment]
Got it. Thanks!

**Comment by dennbagas** [comment]
I got this problem to
```ts
await User.createQueryBuilder('user')
      .update(User, currentUser)
      .where({ email })
      .returning(['username', 'email'])
      .execute()
```
Above code is not called the @BeforeUpdate

**Comment by danielprrazevedo** [comment]
In the documentation it says that updates must be made directly to the model
https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md#beforeupdate
```typescript
const user = this.userRepository.findOne(id);
user.password = '123456';
await this.userRepository.save(user);
```
alternatively, I used the following (T = User)
```typescript
async update(id: number | string, entity: Partial<T>) {
  const e = await this.repository.findOne(id);
  Object.keys(entity).forEach(key => {
    e[key] = entity[key];
  });
  return await this.repository.save(e);
}
```

**Comment by zadorozhny** [comment]
> ```ts
> const post = new Post();
> post.title = "hello";
> User.update(entity); // TypeORM calls post.updatePassword() inside
> ```
> 
> In your case:
> 
> ```ts
> User.update(args.id, args); // there is no object on which typeorm can call .updatePassword() method
> ```

it doesn't work

**Comment by leomotta121** [comment]
> ```ts
>  Object.keys(entity).forEach(key => {
>     e[key] = entity[key];
>   });
> ```

To make it easier there is Object.assign

```javascript
public async update(dto: UpdateDTO): Promise<Entity> {
    const entity = await this.repository.findOne(dto.id);

    return await this.repository.save(Object.assign(entity, dto));
}
```

**Comment by ByBogon** [comment]
> > ```ts
> >  Object.keys(entity).forEach(key => {
> >     e[key] = entity[key];
> >   });
> > ```
> 
> To make it easier there is Object.assign
> 
> ```js
> public async update(dto: UpdateDTO): Promise<Entity> {
>     const entity = await this.repository.findOne(dto.id);
> 
>     return await this.repository.save(Object.assign(entity, dto));
> }
> ```

I got duplication key error when I followed this code and using mongodb now
I'm using _id with @ObjectIdColumn

**Comment by cezarmzz** [comment]
Hey!
In my case, I use this method:
<pre>
<code>
public async update(user: Partial<User>, id: string): Promise<void> {
    const userFind = await this.repository.findOne(id);
    if (userFind) {
      const userToUpdate = Object.assign(userFind, user);
      await this.repository.update(id, userToUpdate);
    }
  }
</code>
</pre>

**Comment by maphstay** [comment]
> > ```ts
> >  Object.keys(entity).forEach(key => {
> >     e[key] = entity[key];
> >   });
> > ```
> 
> To make it easier there is Object.assign
> 
> ```js
> public async update(dto: UpdateDTO): Promise<Entity> {
>     const entity = await this.repository.findOne(dto.id);
> 
>     return await this.repository.save(Object.assign(entity, dto));
> }
> ```

The second option works for me, thanks man !

**Comment by Typeclass-identical506** [comment]
> > > Object.keys(entity).forEach(key => {
> > >     e[key] = entity[key];
> > >   });
> > 
> > 
> > To make it easier there is Object.assign
> > public async update(dto: UpdateDTO): Promise<Entity> {
> >     const entity = await this.repository.findOne(dto.id);
> > 
> >     return await this.repository.save(Object.assign(entity, dto));
> > }
> 
> The second option works for me, thanks man !
> 
> My user.entity.ts
> 
> @BeforeInsert()
>     @BeforeUpdate()
>     async hashPassword(): Promise<void> {
>         if (this.password) {
>             try {
>                 this.password = await bcrypt.hash(this.password, 10);
>             } catch (e) {
>                 throw new InternalServerErrorException('There are some wrong in the hash');
>             }
>         }
>     }
> My method on user.service.ts apllying the sollution
> 
>     async update(id: string, updateUserDto: UpdateUserDto) {
>         const entity = await this.userRepository.findOne({ external_id: id });
>         if (!entity) throw new NotFoundException(`User ${id} not found`);
>         if (updateUserDto.email) {
>             const emailExists = await this.userRepository.findOne({ email: updateUserDto.email });
>             if (emailExists && emailExists.external_id != id) throw new ConflictException('Email already exists');
>         }
>         await this.userRepository.save(Object.assign(entity, updateUserDto));
>         return await this.userRepository.findOne({ external_id: id });
>     }





https://cael-tote.github.io/Te3WJCgDtgBXYH5t-CryET9LLrvAM8KPjhJXK-KgkPhvBKkZHQGm/
