### ISSUE TITLE
RelationId throw error on nullables references

### ISSUE THREAD

**Issue by hugoserrana** [typeorm/typeorm#2039]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When I use the following mapping and relationId return null, the lib throw the error:
```QueryFailedError: invalid input syntax for integer: "null"```

``` 
@ManyToOne(type => Usuario, u => u.trocaLojaAlteracaoStatusList, { nullable: true })
@JoinColumn({ name: 'id_usuario_alteracao_status' })
usuarioAlteracaoStatus?: Usuario | null;

@RelationId((tl: TrocaLoja) => tl.usuarioAlteracaoStatus)
idUsuarioAlteracaoStatus?: number | null;
```

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by ishmaelthedestroyer** [comment]
I'm having this same issue with v0.2.19. I have a model like so:

```
@Entity('steps')
export class Step extends BaseEntity {
  // ... some properties here
  
  @ManyToOne(() => Step, {
    nullable: true,
  })
  _next: Step;

  @RelationId((step: Step) => step._next)
  next: Step;
}
```

In the instances where `_next` is null, it crashes.
