### ISSUE TITLE
Add JSON[] support to postgres

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#204]
Hi, I'm thinking about adding JSON[] support for Postgres. Please read through my proposal and confirm if you will accept it as a PR.

Problem:
-----------------

```
@Column("json")
products: Product[]
```

I'm trying to store an array of JSON objects in a JSON field. This breaks in typeorm, but is supported by Postgres. 

Potential Workaround
---------------------

As a workaround, I could wrap my Product[] in a json object, but then my Entities would have an extra level of indirection. 

I.e. 

.persist({id: 1, products: {products: myProductsArray}}

Proposed Solution
-----------------

It is possible to add the following new type 

```
@Column("json[]")
products: Product[]
```

This would then be serialised into 

```
INSERT INTO table ("products") 
VALUES (array['{"id":"1","name":"A","price":0}', '{"id":"2","name":"B","price":1}']::json[]);        
```

@pleerock  what are your thoughts?

**Comment by dcworldwide** [comment]
Relates to https://github.com/typeorm/typeorm/issues/183

**Comment by pleerock** [comment]
Why `json[]` column type is needed? I don't think we ned this extra type - we can use same `json` type. To be honest I surprised why array jsons aren't supported right. Json value is going right to the underlying driver and it should be able to handle arrays of json too. Did you research if `pg` supports array jsons?

**Comment by pleerock** [comment]
btw probably @mingyang91 already fixed issue with array jsob? Take a look on [this test](https://github.com/typeorm/typeorm/blob/master/test/functional/json/jsonb.ts#L48).

**Comment by mingyang91** [comment]
My workaround. `@Reflect.metadata("design:type", Object)`

```
@Entity()
export class Record {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({ type: "jsonb", nullable: true })
    data: any;

    @Column({ type: "jsonb", nullable: true })
    @Reflect.metadata("design:type", Object)
    dataset: Data[];
}

export class Data {
    name: string;
}
```

**Comment by pleerock** [comment]
@mingyang91 its a bug. Fixed it in `0.0.8-alpha.3`. I think this issue can be closed now.

**Comment by dcworldwide** [comment]
That's great. Just to confirm..is the reflect workaround needed?

**Comment by dcworldwide** [comment]
Will this also work with json as well as jsonb?

**Comment by pleerock** [comment]
> That's great. Just to confirm..is the reflect workaround needed?

no

> Will this also work with json as well as jsonb?

yes

**Comment by dcworldwide** [comment]
Works well, thanks

**Comment by akhil0317** [comment]
Hi just a small doubt can I know where I can find detailed  docs for Typeorm I am new to TypeOrm and I am facing difficulties in finding the details docs where I can find all information.

**Comment by AlexMesser** [comment]
@akhil0317 https://typeorm.io/
