### ISSUE TITLE
findOneOrFail throws when selecting a null valued column

### ISSUE THREAD

**Issue by koffmoff** [typeorm/typeorm#2040]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.3` (or put your version here)

findOneOrFail() throws when it shoulddn't.

Given this entity:

```ts
@Entity()
class Company {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    name: string

    @Column({nullable:true})
    nullName: string
}
```

then this snippet shows the problem:

```ts
// Given
const company = new Company()
company.name = "Company A"
await companyRepo.save(company)

// Then - This works
const c1 = await companyRepo.findOneOrFail(company.id, {select: ["name"]})
// Then - This throws "EntityNotFound: Could not find any entity of type "Company" matching: 1"
const c2 = await companyRepo.findOneOrFail(company.id, {select: ["nullName"]})
```

**Comment by pleerock** [comment]
Can you try this way:

```
const c2 = await companyRepo.findOneOrFail(company.id, {select: ["id", "nullName"]})
```

?

**Comment by koffmoff** [comment]
Yes, that works. It's my current workaround. But should selecting "id" really be necessary?

**Comment by pleerock** [comment]
by current design yes, id is required for selection because typeorm rely a lot on entity id

**Comment by joaovbibiano** [comment]
> Can you try this way:
> 
> ```
> const c2 = await companyRepo.findOneOrFail(company.id, {select: ["id", "nullName"]})
> ```
> 
> ?

It's VERY STRANGE this behavior, BUT works!

Thank you

**Comment by akwodkiewicz** [comment]
What is the reason for the bug to occur? Is the entity id column always required, or is selecting a single nullable column parsed in a wrong way, when the value is null?

**Comment by wiktor-obrebski** [comment]
it's very confusing and can easily lead to errors that can be missed before production release.
if `typeorm` need `id`, it should always fetch id, even if it is not asked for it.
