### ISSUE TITLE
Read-only setting is not working

### ISSUE THREAD

**Issue by DrunkenPoney** [typeorm/typeorm#2041]
It would be nice if there was a read-only option. It would prevent any non-voluntary edits to the database. I wanted to create a personal to for my job but I'm gonna look for an alternative since I'm not sure of what I'm doing and I don't want to risk to edit anything in the database.

**Comment by pleerock** [comment]
There is a `readonly` option in column decorator: `@Column({ readonly: true })`

**Comment by pleerock** [comment]
@ps2goat you able to provide a failing test for your issue?

**Comment by marceloverdijk** [comment]
I have a similar use case. I would like to open a sqlite db in read only mode.

`new sqlite3.Database(filename, [mode], [callback])`
where mode = `sqlite3.OPEN_READONLY`

Is it possible to pass db specific options in ormconfig.json?

**Comment by pleerock** [comment]
@marceloverdijk no, its not. But its quite easy feature to implement, so feel free to contribute. You only need to add option in `SqliteConnectionOptions` and pass it into the new sqlite3.Database in SqliteDriver

**Comment by djgould** [comment]
The current tests for readonly seem broken. https://github.com/typeorm/typeorm/blob/6fcaa0f762807743fbf8c346193348b1c66147a9/test/functional/columns/readonly/columns-readonly.ts#L17-L38

in this case `authorName` is readonly but the test is expecting the value to change (despite what the comments say). I believe the last line should be `expect(loadedPost!.authorName).to.be.equal("Umed");`

I didn't actually run the tests myself but if they are passing it seems there is a problem with the readonly property

**Comment by hielkehoeve** [comment]
I have created a PR for this issue: https://github.com/typeorm/typeorm/pull/2749

**Comment by vlapo** [comment]
Lets track this as main issue for this problem. Just summary:
 - readonly is not working as expected - please see comments here https://github.com/typeorm/typeorm/pull/2150#issuecomment-389915199
 - as @ps2goat pointed there is small inconsistency in current read only definition and we should add new properties as `updatable` and `insertable`
 - our current read only test is wrong and have to be fixed

**Comment by imnotjames** [comment]
Tests have been fixed in master and this feature seems to have been fixed now.
