### ISSUE TITLE
IndexedDB Support

### ISSUE THREAD

**Issue by alexandre-pereira** [typeorm/typeorm#2048]
Hello,

As we are entering the era of progressive web apps, it would be awesome to have the support of indexed DB in Typeorm. This will allow to make it easy to have offline app running on most of the modern browsers, where Web SQL is not supported by Microsoft and Mozilla.

**Comment by pleerock** [comment]
We do not have plans to support indexed db. If you want to implement another driver feel free to contribute.

Btw you can use sqljs which works in all browsers.

**Comment by pleerock** [comment]
> , to give me an idea of the amount of work

you just take a look how other drivers are implemented and trying to make indexdb implementation.

> why it's not planned or just a timing question

yeah time and resources.

**Comment by SimantoR** [comment]
I think it would be a great implementation. I can help out with the implementation if someone starts the pre-PR I can contribute as well.

**Comment by raymondboswel** [comment]
Just to add my 2c. Sql.js works fine, but the database is currently persisted to localstorage, as a stringified byte array. The limit on local storage is approximately 5Mb, and depending on your application that isn't all that hard to reach.

**Comment by upendra-web** [comment]
@raymondboswel, did you find any performance issues while using SQL.js with useLocalForage option? Thanks in advance!
