### ISSUE TITLE
One-to-many using EntitySchema

### ISSUE THREAD

**Issue by i0natan** [typeorm/typeorm#2050]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I seek for a long time a documentation on how to set relations using EntitySchema. Saw only very specific docs on setting many-to-many. I simply want to define my "Job" entity schema to have multiple "Payments" (each job has multiple payments), in other words the job object should have an array of payments[]. so I tried this:
```relations: {
    payments: {
      type: "one-to-many",
      target: "payment"
    }
  }
```

+ created a payment entity schema as well. 

But I get an error message:
"Entity metadata for Job#payments was not found"

Appreciate some help and also a reference, if exists, to a doc that explains about the EntitySchema schema.
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
in `target` you need to specify inverse entity name, e.g. 

`Post`:

```ts
"images": {
      "target": "Image",
      "type": "one-to-many",
      "inverseSide": "post"
    }
```

`Image`:

```ts
    "post": {
      "target": "Post",
      "type": "many-to-one",
      "inverseSide": "images"
    },
```
