### ISSUE TITLE
No changes in database schema were found - cannot generate a migration. To create a new empty migration use "typeorm migrations:create" command

### ISSUE THREAD

**Issue by nutrimax1987** [typeorm/typeorm#2051]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[
![screen shot 2018-04-29 at 21 40 31](https://user-images.githubusercontent.com/13996110/39409791-153f6aa6-4bf6-11e8-866c-066795ac0e51.png)
x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. running './node_modules/.bin/ts-node ./node_modules/.bin/typeorm migration:generate -n UserMigration'
Gives next warning message 
'No changes in database schema were found - cannot generate a migration. To create a new empty migration use "**typeorm migrations:create**" command'
 while documentation on official site  
![screen shot 2018-04-29 at 21 42 45](https://user-images.githubusercontent.com/13996110/39409817-4b9321a6-4bf6-11e8-9733-2870c8bbf0b2.png)

**Comment by pleerock** [comment]
If it says so it means it did not found any changes in your schema / model

**Comment by nutrimax1987** [comment]
I'm not complaining about the message itself , notice the difference between documentation command and warning message command

**Comment by pleerock** [comment]
ahh got you. Sorry it was called migrations: before and lately we renamed all migrations commands from `migrations:` to `migration:`. Thank you!
