### ISSUE TITLE
Return datetimes in defined timezone

### ISSUE THREAD

**Issue by michalhorcic** [typeorm/typeorm#2054]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is it possible to return all timestamps in different defined timezone? For example I save datetimes to postgres timestamp with timezone column, it is saved in UTC as expected. But I would like to return them in different timezone. I tried to set node app like `process.env.TZ = "Europe/Prague"` but with no success. This only change how datetimes are saved if time offset is not specified.

**Comment by pleerock** [comment]
not sure how this is related to typeorm. Typeorm returns you a date, and you are able to do anything with this date and convert it to any timezone having original date in utc format.

**Comment by michalhorcic** [comment]
I sure can, I was just wondering if there is some global settings which I overlooked and which would set all dates from database returned by TypeORM to defined timezone. Something like `SET timezone = 'Europe/Prague';` does for postgres database when timestamp with time zone is used.

**Comment by michalhorcic** [comment]
ok, no problem. Thanks for information. I am still pretty new to node js (more of Rails developer). Is there any best practice how to return all datetime fields in timezone defined in node environment? I am thinking writing some middleware which will convert all datetime fields. Thanks

**Comment by pleerock** [comment]
lets as our UTC and dates expert @chriskalmar if he can help here

**Comment by michalhorcic** [comment]
@chriskalmar thanks a lot for a thorough answer. One of the requirements for application I am developing is to return date in the timezone that is set on server. One of the features of the app is to record time needed to finish maintenance work. So we record beginning and end of work. They are saved in UTC whenever they are inserted. Actually I always work with that time as it was inserted in Prague.  

Then when somebody wants to check those times he has to see them in Prague's time wherever he might be at the moment. 

Thank you for the info about custom field selectors, I will probably go this route as I like the idea that database will handle it.

Thanks again for all your time.

**Comment by chriskalmar** [comment]
you are welcome.
One thing tho: Your use case seems to happen around a single timezone only. Why bother with timezones at all if you can just use the servers local time for storage and retrival?

postgres has the right data type for this: `timestamp without time zone`

**Comment by chriskalmar** [comment]
@michalhorcic please consider closing this issue if you have no more questions regarding this topic. thanks.

**Comment by michalhorcic** [comment]
sorry for not responding. In near future there may be use case for timezones again. So it is better to keep it as timestamp with timezone. 

My issue is solved by your tips, so I am happily closing the issue. Thank again.

**Comment by chriskalmar** [comment]
great, I'm happy it helped

**Comment by Kannas24** [comment]
Can someone help me with [6059](https://github.com/typeorm/typeorm/issues/6059)

**Comment by SeedSuite** [comment]
[hshshdh.txt](https://github.com/typeorm/typeorm/files/5613749/hshshdh.txt)
