### ISSUE TITLE
Closing a connection doesn't fully clean it up

### ISSUE THREAD

**Issue by jbernalvallejo** [typeorm/typeorm#2056]
**Issue type:**
[x] question

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x] `@next`

I am writing different API test suites that initialise the app once per suite. When starting my application I initialise the connection to a postgres db this way:
```javascript
const connection = await createConnection();
```

This works fine for the first suite but from that moment on, I get the following error:
```javascript
Unhandled promise rejection (rejection id: 12): TypeError: Cannot read property 'connect' of undefined
```

Which is coming from https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L636. 

After a thorough investigation I found that the following snippet would fail when requesting users for the second time:
```javascript
  const connection1 = await createConnection();
  const result1 = await getUsers();
  await connection1.close();

  const connection2 = await createConnection();
  const result2 = await getUsers();
  await connection2.close();
```

This is due to:
- When we close the connection, this doesn't become null. It is still set to the `Connection` object, however, `isConnected` is false.
- Hence, when you are trying to connect to the database again, `createConnection` doesn't return what it did the first time and following queries fail with the aforementioned error. 

They way I got it working is by replacing:
```javascript
const connection = await createConnection();
```
with: 
```javascript
let connection;
try {
   connection = await getConnection();
   if (!connection.isConnected) {
     await connection.connect();
   }
} catch (e) {
  // no connection created yet, nothing to get
  connection = await createConnection();
 }
```

My question is: should not this be handled inside the `createConnection` function?

As far as I can see, the issue is down to the `connection.close()` not leaving things as they were before the `createConnection` and that is causing the issue. If we are happy to leave this with still a `connection` object with `isConnected` to `false` then, when requesting a new connection, that function should be clever enough to do the logic above (createConnection VS getConnection & connect). It doesn't feel like from an app code point of view I should be worried to do the above if I explicitly closed the connection. 

What is your point of view on this? If so, I am happy to do the changes myself and submit a PR.

**Comment by pleerock** [comment]
hmm not sure if I completely got the problem, as you can see [here](https://github.com/typeorm/typeorm/blob/master/src/connection/Connection.ts#L227) we set isConnected to false once connection gets closed.

**Comment by jbernalvallejo** [comment]
Correct. And if you then try to call `createConnection` you will get the error above. 

First time you call `createConnection`, typeorm doesn't hold any information about any connection or whatsoever and hence, if you call `getConnection `it throws an exception. However, second time you call it, it knows about a "disconnected" connection. `getConnection `will retrieve the connection. Hence, scenario is different. 

As far as I can see there is no way to close a connection or clean up typerom so we end up as if we would never have created it.

**Comment by jbernalvallejo** [comment]
Just trying to make it more obvious:
```
try {
  await getConnection(); // throws exception
} catch(e) {}

let connection = await createConnection();
await connection.close();

connection = getConnection(); // this does not retrieve an exception as before, returns connection with isConnected=false

connection = await createConnection();
await getUsers(); // throws TypeError: Cannot read property 'connect' of undefined
```

Not sure why by the root cause for the error is that `this.master` is undefined in obtainMasterConnection.

**Comment by pleerock** [comment]
Last time you call `connection = await createConnection();` it shall replace exist connection with a new one, or maybe re-connect of the exist connection. Can you checkout the code and see where exactly problem is?

**Comment by jbernalvallejo** [comment]
Hi. Sure. Will try to debug and see why on second `createConnection()` `this.master` becomes null. Thanks for your answer.

**Comment by djGrill** [comment]
Hi, any progress on this?

**Comment by laukaichung** [comment]
@jbernalvallejo 
Have you solved this issue? I'm getting the same error with `close()`
````
Unhandled promise rejection (rejection id: 12): TypeError: Cannot read property 'connect' of undefined
````

**Comment by jbernalvallejo** [comment]
Hi all. Sorry for the delay. 

I have just retried the initial script and it now works:
```javascript
const connection1 = await createConnection();
await getRepository(User).find();
await connection1.close();

const connection2 = await createConnection();
await getRepository(User).find();
await connection2.close(); 
```

I am using the latest` typeorm 0.2.16` and `pg 7.9.0`. Which versions are you using?

**Comment by vlapo** [comment]
So @jbernalvallejo is your issue resolved in latest version of typeorm?

**Comment by jbernalvallejo** [comment]
I think so. I was not able to reproduce the issue again with the latest `typeorm` and `pg` (I can be 100% where the issue was).

**Comment by vlapo** [comment]
Glad to hear it! Closing as resolved in latest version.
