### ISSUE TITLE
relationship with 2 foreign keys

### ISSUE THREAD

**Issue by Flexiink** [typeorm/typeorm#2058]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
Category
-
id
created_at

CategoryL10n
id
category_id
language_id
name
```

How to set up such a relations?

`@OneToOne(type => CategoryL10n, l10n=> l10n.category_id   **AND l10n.language_id = 123** )`

**Comment by pleerock** [comment]
Yes its possible, second parameter must be simply inverse side, NOT inverse side id as you do it right now. See examples [here](https://github.com/typeorm/typeorm/tree/master/test/functional/relations/multiple-primary-keys).

**Comment by Flexiink** [comment]
Thank you
