### ISSUE TITLE
[Test suite enhancement] Extend npm test with an arg filter tests 

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#206]
I think the npm test script needs to take an argument that allows us to limit testing to a particular test case. This is useful for testing a specific issue

**Comment by pleerock** [comment]
you can submit a PR if you really need this feature. However I think the easiest way to run particular test is to temporary change code from `describe("...")` to `describe.only("...")`, or `it("...")` to `it.only("...")`. Same technique can be used to `skip` something e.g. `it.skip`. This is much convenient then cli arguments IMHO.

**Comment by dcworldwide** [comment]
OK that works. Will run with that.
