### ISSUE TITLE
Cannot load typeorm

### ISSUE THREAD

**Issue by heroic** [typeorm/typeorm#2060]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I created a new dummy app with `react-native init test`, and then followed the instructions to add typeorm. In my App.js I included `import {getManager} from 'typeorm'`, and then ran `react-native run-ios`.

I see the following error in metro-bundler:

> Error: Unable to resolve module `path` from `/Users/amit/Code/test/node_modules/typeorm/platform/PlatformTools.js`: Module `path` does not exist in the Haste module map

Here's a sample repository to show the problem: [https://github.com/heroic/react-native-test](https://github.com/heroic/react-native-test)

**Comment by nuvolarmobileteam** [comment]
Same problem here! Could you manage to make it work?

**Comment by pleerock** [comment]
There is a [react-native example repo](https://github.com/typeorm/react-native-example), did you try it?

**Comment by agurtovoy** [comment]
@nuvolarmobileteam Make sure you import everything from `typeorm/browser` rather than just `typeorm` (as per https://github.com/typeorm/react-native-example), e.g.

```
 import { createConnection } from "typeorm/browser";
```
This probably should be mentioned somewhere in the docs as well.

**Comment by nuvolarmobileteam** [comment]
Hi guys,

First of all thanks for your answers. 
Indeed the import was my problem when running the project.
It also helped me a lot to have the arm working is to have the example as a reference.

FYI I had to install `metro-bundler` and import it in the `rn-cli.config.js` as in the project example

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
