### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by shashikiran797** [typeorm/typeorm#2065]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am using NestJs with Typeorm
I get the request object form graphql, graphql parameters do not have ```__proto__``` set.
I am directly passing the graphql paramter object to the save method. I am getting the below error when I do that:
```
TypeError: Cannot convert object to primitive value
    at new MustBeEntityError (/Users/shashikiranms/projects/vcbackend/src/error/MustBeEntityError.ts:10:43)
    at EntityPersistExecutor.execute (/Users/shashikiranms/projects/vcbackend/node_modules/typeorm/persistence/EntityPersistExecutor.js:77:35)
    at EntityManager.save (/Users/shashikiranms/projects/vcbackend/src/entity-manager/EntityManager.ts:298:14)
    at UserRepository.Repository.save (/Users/shashikiranms/projects/vcbackend/src/repository/Repository.ts:138:29)
```

When I debugged the issue, it is beacause
EntityPersistExecutor.js checks for the entity to be an *instanceof Object*, which is false, because ```__proto__``` is not set for the entity

```js
if (!this.entity || !(this.entity instanceof Object)) {
     return Promise.reject(new MustBeEntityError_1.MustBeEntityError(this.mode, this.entity));
}
```

I think changing the above condition ``` this.entity instanceof Object``` to ``` typeof this.entity === 'object'``` solves the problem

PS: It was working in version 0.1.20. 
It is breaking once I upgraded to 0.2.0

**Comment by pleerock** [comment]
`typeof null` also is an object, if value you have isn't an object then what it is?

**Comment by shashikiran797** [comment]
this.entity is not null but an object, but it does not inherit from Object (i.e ```this.entity.__proto__``` is undefined) that's why ```this.entity instanceof Object``` is false.

**Comment by pleerock** [comment]
okay.. are you able to provide a PR?

**Comment by abrahamx97** [comment]
@shashikiran797 how do you solve this problem? I have the same proble using Nestjs with typescript, graphql and typeorm

**Comment by shashikiran797** [comment]
One way to solve this problem is to have constructors to each entity, create  objects of entity class and pass them to the tyoeorm methods

**Comment by vlapo** [comment]
Sure `this.entity !== null && typeof this.entity === 'object'` is satisfactory solution of this issue but this condition is true also for `new String()`, `new Number()`, `new Boolean()`, `new Date()`, `new Error()`, ... (more: http://bonsaiden.github.io/JavaScript-Garden/#types.typeof).

For javascript support is better condition `Object.prototype.toString.call({}) === '[object Object]'`. But there are some performance differences and also we have to check array (maybe type of each item in array if we want to be perfect).
```
"toString.call"                    x  93,991,941 ops/sec ±1.03% (86 runs sampled)
"toString.call + Array.isArray     x  82,102,219 ops/sec ±1.58% (89 runs sampled)
"typeof'"                          x 687,506,864 ops/sec ±0.71% (90 runs sampled)
"instanceof"                       x 116,683,504 ops/sec ±1.44% (88 runs sampled)
Fastest is "typeof"
```
*Note: run on node 10 on my personal pc*

What do you think @pleerock? Better type check for javascript or just fast bugfix using `typeof`?

**Comment by PachowStudios** [comment]
Any news on this? I'm also having issues because of this when using GraphQL with TypeORM.

**Comment by KovalenkoYurii** [comment]
Hello, I'd stucked with same problem. I found to instantinate entity with `repository.create` method of typeorm. Example:
`public createBun(newBun: DeepPartial<Bun>): Promise<Bun> {
    const bun = this.bunRepository.create(newBun);
    return this.bunRepository.save(bun);
  }`

**Comment by ricky300300** [comment]
You can solve something like this

`action.additionalDetails = {};
        if(input.additionalDetails) {
            Object.assign(action.additionalDetails, input.additionalDetails);
        }`

**Comment by meteorlxy** [comment]
Any news on that?

Many other projects are trying to create Objects by `Object.create(null)`, which results in `[Object: null prototype]`.

However, there are so many `instanceof Object` in typeorm, which may cause a lot of issues.

```js
Object.create(null) instanceof Object // false
```

Hope we can fix that, or at least put a notice in the documentation.

**Comment by SkvokeN** [comment]
Hello, any news?

**Comment by brokenthorn** [comment]
I don't know if my issue #4955 is related to this one but if it is, maybe someone can better explain the global issue here and why Typeorm needs prototype based inheritance?

**Comment by brokenthorn** [comment]
> One way to solve this problem is to have constructors to each entity, create objects of entity class and pass them to the tyoeorm methods

Won't work if the library you're using like Type-GraphQL creates proto-less objects when passing arguments to mutations for example and you use those same objects to pass to Typeorm to save or update entities. Typeorm probably needs to switch to proto-less objects too since it only uses them as hashmaps.

**Comment by amille14** [comment]
Just ran into this issue using type-graphql, typeorm and nestjs and was scratching my head for a while. This is a really obtuse issue and causes silent bugs. There are workarounds but it really needs to be fixed.

**Comment by jpoppe** [comment]
I solved it for my use case in NestJS with a simple object spread (required for input):
```ts
@Mutation(() => Item)               
public createItem(@Args('input') input: ItemCreateInput): Promise<Item>         
  return this.itemsService.create({...input}) // spread operator to clone input to new object                            
 } 
```
Hope it helps..

**Comment by ArcaneDiver** [comment]
probably we could just create a sort of Pipe that re-instance the object.

**Comment by greenreign** [comment]
Just ran into this issue with nestjs and graphql during a find condition and I'm shocked I haven't run into it before.  Or have I?

**Comment by maayanbar13** [comment]
I've had the same issue with the mongodb driver as well, with the same use case - nestjs + graphql + typeorm while using the same models as the input... can anyone offer a workaround that is more generic then what @jpoppe suggested?

**Comment by wowczarczyk** [comment]
I am still having this problem in Nest.JS even with using typeorm 0.2.29 which should contain a fix. Anyways, as workaround that works for nested objects as well I am doing:

```
import * as deepMerge from 'deepmerge';

const newDataObjectWithProto = deepMerge(newDataObject, {})
```

**Comment by siberian-man** [comment]
I use NestJS (GraphQL) and TypeORM. To bypass the issue I created a global pipe as shown bellow:

```
class EnsurePrototypePipe implements PipeTransform {
  transform(argument: unknown) {
    return ensurePrototype(argument);
  }
}

const ensurePrototype = (input: unknown): unknown => {
  if (Array.isArray(input)) {
    return input.map(it => ensurePrototype(it));
  }
  if (isObjectLiteral(input) && input.prototype === undefined) {
    const output = {};
    for (const property in input) {
      if (Object.prototype.hasOwnProperty.call(input, property)) {
        output[property] = ensurePrototype(input[property]);
      }
    }
    return output;
  }
  return input;
};

export const isObjectLiteral = (v: unknown): v is Record<string | number | symbol, unknown> => {
  if (typeof v !== 'object' || v == null) {
    return false;
  }
  const constructor = v.constructor;
  return constructor == null || constructor === Object;
};

```

And apply this pipe globally:

```
...
nestApp.useGlobalPipes(new ValidationPipe(), new EnsurePrototypePipe())
...
```
