### ISSUE TITLE
Doc issue: migration from sequelize

### ISSUE THREAD

**Issue by stevenmusumeche** [typeorm/typeorm#2066]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Thank you for this project.  It is awesome.  We are converting an API from sequelize and ran into a small bug in the documentation.

In the sequelize migration documentation, the following line is used to demonstrate how to create a new entity:

```
const employee = Employee.create({ name: "John Doe", title: "senior engineer" });
```

In order for this to work, the create method needs to be called on the repository, not the entity.

```
const employee = await EmployeeRepository.create({ name: "John Doe", title: "senior engineer" });
```

**Comment by pleerock** [comment]
if you are using active record (e.g extend BaseEntity) then `create` method is available to you

**Comment by stevenmusumeche** [comment]
Would you like a PR to the documentation to make that more clear?

**Comment by pleerock** [comment]
Okay, sure!
