### ISSUE TITLE
Unhandled promise rejection warning on postgres connection issues

### ISSUE THREAD

**Issue by nilshohmann** [typeorm/typeorm#2067]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

**Miscellaneous:**

npm: 6.0.0
node: 9.10.1
postgres: 10.3

**Steps to reproduce or a small repository showing the problem:**

I'm writing a small application using typeorm together with `typeorm-typedi-extensions` and a postgres database inside a docker container. Currently I'm running into an uncatchable error when the database connection breaks during runtime:

1. Start the database server.
2. Start the application and connect to the database.
3. Execute queries - everything works fine.
4. Stop the database server.
5. Try to execute a query (e.g. `SomeRepository.find()`).
6. You will now see an `UnhandledPromiseRejectionWarning` inside the terminal and your application has no idea what's going on.

```
(node:2899) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:14)
(node:2899) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was nothandled with .catch(). (rejection id: 1)
(node:2899) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

A small debugging session showed that the error is thrown at the `query(...)`-Method of the `PostgresQueryRunner`. The problem seems to be the async function inside the Promise call:

```ts
return new Promise<any[]>(async (ok, fail) => {
    const databaseConnection = await this.connect();
    ...
}
```

In my case the QueryRunner tries to create a new connection and execute the query, but since the database is not available an error is thrown. This error is caught inside the aync function, but since the surrounding Promise is only triggered when either the `ok` or the `fail` callback is called, the result (or in this case the error) returned by the async function is unreachable. The Promise call should be three lines below and wrapping the `databaseConnection.query`-method with the callback and should not contain an async method - instead the query method should be async. Another way is to wrap all the code inside the Promise into a try-catch block, like it's done in most other QueryRunners.

**Comment by pleerock** [comment]
`ECONNREFUSED 127.0.0.1:5432` means it cannot connect to your database because its unavailable. I guess you did not expose docker container ports.

**Comment by nilshohmann** [comment]
I totally understand what ECONNREFUSED means. The point of the issue is not the connection problem to the database (in fact I'm shutting it down on purpose here). The problem is that I'm NOT able to catch this error in the application. In the following snippet the connection error wouldn't be caught but just print out an `UnhandledPromiseRejectionWarning`:

```ts
SomeRepository.find().catch(console.log);
```

**Comment by nilshohmann** [comment]
The same issue is present in the `CordovaQueryRunner` and the `ReactNativeQueryRunner`, but I don't have time to fix and test this.
