### ISSUE TITLE
Adding an additional column to a closure table

### ISSUE THREAD

**Issue by ldadams** [typeorm/typeorm#2068]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is it possible to add an additional column to a closure table?  We are using a postgres plugin(Citus) to shard data based on distribution keys and need to add an additional column to support sharding for a multi-tenant application.

Doesn't look like its possible to create the closure table as a separate entity?  I see closure-junction as a table type but can't seem to use it directly?

If this isn't something that's currently support any thoughts on a work around or level of effort to implement?  Ideally I would also be able to add this column to the primary key of the generated closure table.

Looking around seems like there would be a few main changes.
 - Create a new decorator type `@TreeAdditionalColumn` ?
 - Update ClosureJunctionEntityMetadataBuilder to support adding an additional set of columns.
 - Update ClosureSubjectExecutor to correctly insert the closure table additional columns.

Sure I am missing some additional parts but thanks in advance for any thoughts here.

Thanks!

**Comment by derblitz** [comment]
In general Citus should work with typeorm, right?

**Comment by ldadams** [comment]
Yep works fine.  The question was specific to closure tables.  We ended up using an adjacency list.

**Comment by derblitz** [comment]
OK thanks!
