### ISSUE TITLE
Feature Request - Add truncate() to repository api

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#207]
Please add the ability to delete all table table via the repository api. Thanks

**Comment by pleerock** [comment]
I was thinking about to add this method already. However there is one small consideration why Im still not sure about this issue. `Repository` is a most commonly used class with public api needed for regular work with entities. `truncate` is more specific method and generally not commonly used, and should be used carefully. Is it a good idea to add such method there?

**Comment by dcworldwide** [comment]
Cool. I think it logically fits within the CRUD functionality of a Repository or the Entity Manager. 

I understand the concern. If it has an explicit name like truncate or removeAll IMO it is pretty clear to me about it's intent. Others might have different opinions...

**Comment by pleerock** [comment]
I think we can add this method. But I don't like `truncate` name. Looks very mysql-specific for more. Maybe we can came up with better name (which also will be correct for mongodb in the future)?

**Comment by dcworldwide** [comment]
Yeah agree with that. Ideas.... clear(), removeAll()

**Comment by pleerock** [comment]
`clear` sounds better, but is it descriptive enough name?

**Comment by dcworldwide** [comment]
For me yes,  reminds me of clearing a collection or array. Others might think differently

**Comment by dcworldwide** [comment]
Also, I've recently come up with a similar edge case. Sometimes I need to delete all data by FK. I.e. delete all orders belong to user X. I think the remove() api only allows for the removal of a single record atm. Would be nice to have the orm take care of this too.

**Comment by pleerock** [comment]
but thats not safe and can bring lot of issues on production....

**Comment by pleerock** [comment]
will be released in `@next` very soon...

**Comment by thalisvilela** [comment]
Meanwhile, how can i truncate tables? I've tried some ways but i keep getting a `{code: 5, message: "could not prepare statement (1 near "TRUNCATE": syntax error)"}`.
I've tried: 
`connection.getRepository(Client).query("TRUNCATE TABLE 'client'");`
also
`
connection.driver.createQueryRunner().then((qr)=>{
qr.query("TRUNCATE TABLE 'client'");
})
`
Any help on that?

**Comment by dcworldwide** [comment]
Great, thanks!
