### ISSUE TITLE
Migration CLI.  Class name begin with first letter lower.

### ISSUE THREAD

**Issue by ph55** [typeorm/typeorm#2070]
**Issue type:** bug report
**Database system/driver:** `mysql`
**TypeORM version:**  `latest`
**Node:** 8.11.1
**OS:** win32 x64

**Steps to reproduce or a small repository showing the problem:**

1. Add migration with CLI:
```
typeorm migration:create -n PostRefactoring
```
2. Class name begin with lowercase
![image](https://user-images.githubusercontent.com/1386622/39550496-1c80f94e-4e6a-11e8-8f06-43b0bb724070.png)

**Comment by pleerock** [comment]
Thanks for the report, fix will be released in 0.2.5
