### ISSUE TITLE
@CreateDateColumn does not auto populate upon insertion.

### ISSUE THREAD

**Issue by jdpalumbo** [typeorm/typeorm#2080]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.2` 

**Steps to reproduce or a small repository showing the problem:**

Sample entity definition.
```
export class MyEntity {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column({type: "int"})
    public password_reset_id: number;

    @Column({type: "varchar"})
    public password_hash: string;

    @CreateDateColumn()
    public created_at: Date;

    @UpdateDateColumn()
    public updated_at: Date;

    @Column({type: "timestamp"})
    public deleted_at: Date;
}
```

It would seem that after updating to version `0.2.2` my `created_at` columns are no longer being populated upon record insertion. Has the `@CreateDateColumn()` decorator changed in someway? Am I missing something completely obvious?

**Comment by pleerock** [comment]
Can you please check on latest version?

**Comment by pleerock** [comment]
Can you please check on latest version?

**Comment by lihue** [comment]
I have the same problem with version 0.2.5

**Comment by pleerock** [comment]
sounds strange, there are tests which confirm this functionality...  can you please provide a reproduction repo?

**Comment by jdpalumbo** [comment]
I have since rolled back to `0.1.9` which was the version I was on before upgrading to `0.2.2`. Prior to rolling back I had noticed that the `INSERT` queries where using the `DEFAULT` keyword for the `CreatedDateColumns` in `0.2.2` where as in `0.1.9` they contain a string literal of the current timestamp.

Query in `0.1.9`:

```
INSERT INTO `table_name`(`created_at`, `updated_at`) VALUES (?,?) -- PARAMETERS: ["2018-05-04T21:07:38.711Z","2018-05-04T21:07:38.711Z"]
```

Query in `0.2.2`:

```
INSERT INTO `table_name`(`created_at`, `updated_at`) VALUES (?,?) -- PARAMETERS: [DEFAULT,DEFAULT]
```

I am not entirely sure of the mechanism TypeORM is using to get the timestamp in place of `DEFAULT`. Does the database schema need to be altered in anyway to accommodate this? 

Furthermore, for what it is worth we are using mysql 5.6 if that could possible be the difference. If I can find the time I will try to provided an example that exhibits the observed behavior.

**Comment by jdpalumbo** [comment]
I forked the repository in the hopes of running the tests locally and perhaps trying the tests against a `mysql 5.6` container. However I cannot seem to get the tests to pass in their current state even though they appear to be passing in the CI build?

**Comment by pleerock** [comment]
okay, so in 0.1.x we used our own value as a date. Now in 0.2.x we are using column's DEFAULT which is equal to NOW(). You don't have created date because you schema is not in sync.

**Comment by jdpalumbo** [comment]
So i should just define defaults for `CURRENT_TIMESTAMP` for both my created and updated  columns in my schema?

**Comment by pleerock** [comment]
yes

**Comment by jdpalumbo** [comment]
👍 Thanks pleerock

**Comment by dcworldwide** [comment]
Just upgraded to 0.2.x and hit the same issue.

I can't rebuild the production schema. Instead I need to patch it via sql with zero outage. If I ran the following for all createdAt updatedAt columns (postgres) and then afterwards deploy the new code (with 0.2.x) can I expect any issues?

ALTER TABLE some_table ALTER COLUMN "createdAt" SET DEFAULT CURRENT_DATE;

**Comment by mrsauravsahu** [comment]
you can try 
```
@CreateDateColumn({ default: () => 'NOW()' })
createdAt: Date
```
in your entity. This should generate the right migration.
