### ISSUE TITLE
Can't create a postgresql array of enums

### ISSUE THREAD

**Issue by kodayashi** [typeorm/typeorm#2081]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello, trying to create an entity that has an array of enums. I see the docs on how to create an enum (which I got working) and the example on how to create an array (which I got working with strings). I would, however, like to create an array of enums. I'm currently trying this:

```ts
export enum Role {
    admin = 'admin',
    manager = 'manager',
    leader = 'leader',
    contributor = 'contributor',
}

...

  @Column('enum', { enum: ['admin', 'manager', 'leader', 'contributor'], array: true })
  roles: Role[];
```

How do I create such a type for this entity? I'm essentially shooting for:

```
CREATE TYPE enum_type AS ENUM ('value1', 'value2');
CREATE TABLE table ( enum_array_type enum_type[] );
```

**Comment by pleerock** [comment]
implemented, will be supported in 0.2.5

**Comment by kodayashi** [comment]
Works great in 0.2.5 thanks @pleerock !

**Comment by ilakshmikanthp** [comment]
@kodayashi I want to create a reusable enum used in different entities or enum used in different columns in the same entity. Did you try such scenario. Can you share some details on that.
