### ISSUE TITLE
Documentation: Find params

### ISSUE THREAD

**Issue by cjackson234** [typeorm/typeorm#2084]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ x ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

In the documentation, you have the following:

```
const user = new User();
user.firstName = "Timber";
user.lastName = "Saw";
user.age = 25;
await repository.save(user);

const timber = await repository.findOne({ firstName: "Timber", lastName: "Saw" });
```

which throws an error like 

> Object literal may only specify known properties

The following is found later in the docs and does not have this issue.

`const timber = await repository.findOne({ where: { firstName: "Timber", lastName: "Saw" }});`

**Comment by pleerock** [comment]
nope, first example is working and we have dozen of tests proven this basic functionality. Please provide a minimal reproduction for this issue.

**Comment by cjackson234** [comment]
I was indeed incorrect. There was more to my case that caused the issue. 

I have a one to many relationship kinda like this

```
@Entity()
export class ParentEntity{
    @PrimaryColumn()
    Id: string;

    @Column()
    Name: string;

    @OneToMany(type => ChildEntity, c => c.Parent, { cascade: ['insert'] })
    Children: Array<ChildEntity>;
}

@Entity()
export class ParentEntity{
    @PrimaryColumn()
    Id: string;

    @Column()
    Name: string;

    @ManyToOne(type => ParentEntity, e => e.Children, { cascade: ['insert'] })
    Parent: ParentEntity;
}
```

The child table will create a "parentId". If I wanted to search for the children without loading data from the parent I would do this:

`const children= await repository.find({ parentId: id });`

This gives me the following error 

> Object literal may only specify known properties, and 'parentId' does not exist in type 'FindConditions<ParentEntity>'.

**Comment by cjackson234** [comment]
But it still returns the correct data.

**Comment by pleerock** [comment]
Correct query is:

```ts
const children= await repository.find({ parent: { id: id } });
```
