### ISSUE TITLE
@PrimaryColumn in cascade

### ISSUE THREAD

**Issue by jondediego** [typeorm/typeorm#2085]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[x ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.4` (or put your version here)

I am experiencing an error for the latest typeorm version. I am not sure it is an issue but I tell you anyway. It happens when there is a table A that cascade insert into a table B if B has a @PrimaryColumn and we don't tell any value for its id before saving.
For example:
```
@Entity('user')
export class User {

    @PrimaryColumn()
    id: number;

    @Column()
    name: string;


    @ManyToOne(type => Office, {cascade: true})
    office: Office;
}
```

```
@Entity('office')
export class Office {

    @PrimaryColumn()
    id: number;

    @Column()
    officeName: string;


}
```

The following save fails:
```
   const user = new User();
      user.id=1;
      user.name="Kevin";
      const office = new Office();
      office.officeName="New York";
      user.office = office;
      const userRepository = getRepository('user') as Repository<User>;
      await userRepository.save(user);
```

If we set an id for office it doesn't fail. If we define column id in table Office as @PrimaryGeneratedColumn instead of @PrimaryColumn it doesn't fail either. It makes sense that it should be a @PrimaryGeneratedColumn because id is not going to be informed, but should it fail if we use a @PrimaryColumn? Or should it generate autommatically an id?
[Archivo comprimido.zip](https://github.com/typeorm/typeorm/files/1975889/Archivo.comprimido.zip)

I provide a reproduction example.

**Comment by ShadabFaiz** [comment]
Read the [doc](http://typeorm.io/#/many-to-one-one-to-many-relations)
```ManytoOne() cannot exist without OnetoMany()```

**Comment by pleerock** [comment]
@ShadabFaiz no, @ManyToOne can exist without @OneToMany, but @OneToMany can't exist without @ManyToOne

**Comment by pleerock** [comment]
@jondediego everything you are describing work as expected. If you mark it a `@PrimaryColumn` and do not set the value it must fail. And yeah, it should not generate you a value since you are using  `@PrimaryColumn`  and not `@PrimaryGeneratedColumn`.
