### ISSUE TITLE
id undefined fails when saving a relation

### ISSUE THREAD

**Issue by jondediego** [typeorm/typeorm#2086]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ x] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.4` (or put your version here)

This is not an issue but I tell you just in case you consider something should be changed or a check should be added. If I have an entity A that has a nullable relation with entity B and I try to save entity A informing relation B, but B.id = undefined, then there is an error. If B.id = null there is no such an error and save works. 

```
@Entity('user')
export class User {

    @PrimaryColumn()
    id: number;

    @Column()
    name: string;


    @ManyToOne(type => Office, {nullable: true})
    office: Office;
}
```

```
@Entity('office')
export class Office {

    @PrimaryColumn()
    id: number;

    @Column()
    officeName: string;


}
```

```
      const user = new User();
      user.id=1;
      user.name="Kevin";
      const office = new Office();
      office.id = undefined;
      user.office = office;
      const userRepository = getRepository('user') as Repository<User>;
      await userRepository.save(user);
```

I provide a reproduction example just in case it is useful.
[Archivo comprimido.zip](https://github.com/typeorm/typeorm/files/1975921/Archivo.comprimido.zip)

**Comment by vlapo** [comment]
Hi @jondediego, thnx for your question.

Why are you setting office id to undefined? Do you want to clear `user.office` relation?

I dont see any real life scenario to do this. Maybe it will be fixed by some changes in future but we do not have time to solve this kind edge cases if there is no reason to use typeorm this way.

**Comment by jondediego** [comment]
Sorry it was a long time ago and I don’t remember the reason. You can close it if you want.
