### ISSUE TITLE
Property 'insert' does not exist on type 'QueryRunner' after upgrading

### ISSUE THREAD

**Issue by OysteinAmundsen** [typeorm/typeorm#2087]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
export class FirstReleaseChanges1487003618914 implements MigrationInterface {

  async up(queryRunner: InsertQueryRunner): Promise<any> { // Next-gen Typeorm
    await queryRunner.insert('configuration', {
      name: 'defaultValues',
      value: JSON.stringify({
        // ... not important
      })
    });
  }
}
```
Upgraded from 0.1.21 to 0.2.5, and none of my migrations compile anymore. Error message described in issue title.

Searched through the CHANGELOG.md for signs of something which replaces this method, but could only find this:
```
insert, update and delete methods of QueryRunner now use InsertQueryRunner, UpdateQueryRunner and DeleteQueryRunner inside
```

The documentation for QueryRunner is marked as `TBD`, with no further instructions on how to retreive or use the `InsertQueryBuilder`. My VSCode does not know of any class called this and it does not seem to be exported anywhere in typeorm.

How can I translate the above code to something working under TypeOrm latest?

**Comment by pleerock** [comment]
See docs [here](http://typeorm.io/#/insert-query-builder).

**Comment by OysteinAmundsen** [comment]
Ok, so I'm not constrained to using `QueryRunner` in a migration? I can use `QueryBuilder`?

**Comment by OysteinAmundsen** [comment]
Thank you for your response, and for a magnificent piece of craftsmanship in this package.

**Comment by npatterson** [comment]
I too am a recent fan of the offering and progress of TypeORM.  I've started the upgrade to latest and I am running into this same issue for insert and update.  

I've attempted to use `EntityManager` and `QueryBuilder`, but the fact that they type check against the entity is an issue for how I'm currently using the `queryRunner.insert` and `queryRunner.update` in migrations. 

As the `Entity` changes and migrations are generated to modify the schema, I currently have update queries to modify the data to fit the schema adjustments using `queryRunner.update`.  I also `seed` related static data using `queryRunner.insert `.  This currently works well in the previous version as the `QueryRunner` offers insert and update methods using the table name and key value pairs for field names allowing for reference and use with various schema versions throughout the migration path.

With the latest version, I can no longer use this approach and reference older schema fields for versioning data updates.

Is there a means of accomplishing this in the latest version that I may be overlooking? I would greatly appreciate that this remain a target scenario for the framework to be able to support. Thanks!

**Comment by pleerock** [comment]
@npatterson you can insert into custom table as well:

```ts
queryRunner
   .manager
   .createQueryBuilder()
   .insert()
   .into("table_name")
   .values({ ... })
   .execute()
```

**Comment by ishanbakshi** [comment]
Just discovered I can also run any raw SQL in the migrations using this command (although avoid using raw SQL's if possible):

`queryRunner.manager.query("<raw SQL statment here>");`

Example : 
```queryRunner.manager.query("INSERT INTO `users` VALUES (1,'userName1','dummySurnameHere');```

**Comment by JimBeem** [comment]
My experience with this is that if I have a model file demo.ts with a class Demo that creates a table demo, using the below code still checks against the demo model and will throw a fit. Is that not how its supposed to work? I'd love to not have to write raw sql inserts in my seed data migrations.
```
queryRunner
   .manager
   .createQueryBuilder()
   .insert()
   .into("demo")
   .values({ ... })
   .execute()```

**Comment by Alex-dev02** [comment]
> @npatterson you can insert into custom table as well:
> 
> ```ts
> queryRunner
>    .manager
>    .createQueryBuilder()
>    .insert()
>    .into("table_name")
>    .values({ ... })
>    .execute()
> ```
Hi, @pleerock , how can I add  ```.where()``` to that, if I try after values, I get "Property 'where' does not exist on type 'InsertQueryBuilder<User>'"
