### ISSUE TITLE
Additional columns in pivot table

### ISSUE THREAD

**Issue by thalisvilela** [typeorm/typeorm#209]
Hello guys! Is there an "official" way to add columns to a pivot table? I hava a Product table, and an Order table, a many-to-many relation where an an order can have many products, but in the pivot, i have to add the "amount" column. Thanks in advance.

**Comment by pleerock** [comment]
can you please provide more details what exactly you want to achieve, how it should look and what you want to have as a final result/output ?

**Comment by thalisvilela** [comment]
@pleerock , thanks for the reply! So, trying to be more clear:
TABLES:
orders;
products;
order_products_product_orders; (auto generated junction table in the ManyToMany relation)

In the 'order_products_product_orders' junction table, besides "order_id" and "product_id" columns, i need to have another column named "amount", so when i get the order.products[], and loop through them, i can get the amount information perhaps like product.amount.

**Comment by pleerock** [comment]
if you want to have extra columns in junction tables, you simply need to create extra entity instead of auto generated junction table and make proper relations between three tables. Thats a standard practice and can't be avoided if you want more complex relational tables.

**Comment by thalisvilela** [comment]
Thanks a lot @pleerock ! Thats exactly what i ended up doing.

**Comment by univerze** [comment]
Hi @pleerock !
I have been trying to make above solution work with 3 tables joined but the data doesn't save into the jointable for some reason, and I cant see errors in the log.
Setup:
![screen shot 2018-10-17 at 10 33 21](https://user-images.githubusercontent.com/17457154/47080447-e560eb80-d1ff-11e8-867c-16ff34a27e5b.png)
```
@Entity({ name: 'workspace_field_values' })
export class WorkspaceFieldValues extends BaseEntity {
    @PrimaryColumn()
    workspaceId: number;

    @Column()
    workspaceFieldId: number;

    @Column()
    value: string;

    @ManyToOne(type => Workspace, workspace => workspace.fieldValues)
    workspace: Workspace;

    @ManyToOne(type => WorkspaceField, workspaceField => workspaceField.fieldValues)
    workspaceField: WorkspaceField;
}

@Entity({ name: 'workspace_fields' })
export class WorkspaceField extends BaseEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    label: string;

    @Column('json')
    attributes: object;

    @Column('json')
    validation: object;

    @Column({ type: 'timestamp' })
    createdAt: Date;

    @Column({ type: 'timestamp' })
    deletedAt: Date;

    @OneToMany(type => WorkspaceFieldValues, fieldValues => fieldValues.workspaceField)
    fieldValues: WorkspaceFieldValues[];

    @OneToMany(type => Workspace, workspace => workspace.customFields)
    workspaces: Workspace[];
}

@Entity({ name: 'workspaces' })
export class Workspace extends BaseEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    ownerId: number;

    @Column()
    name: string;

    @Column()
    description: string;

    @Column('json')
    settings: object;

    @Column({ type: 'timestamp' })
    createdAt: Date;

    @Column({ type: 'timestamp', select: false })
    updatedAt: Date;

    @Column({ type: 'timestamp', select: false })
    deletedAt: Date;

    @ManyToOne(type => User, owner => owner.workspaces)
    owner: User;

    @OneToMany(type => Document, document => document.workspace, { cascade: true })
    documents: Document[];

    @ManyToMany(type => User)
    @JoinTable()
    members: User[];

    @OneToMany(type => WorkspaceField, workspaceField => workspaceField.workspace)
    customFields: WorkspaceField[];

    @OneToMany(type => WorkspaceFieldValues, fieldValues => fieldValues.workspaceField)
    fieldValues: WorkspaceFieldValues[];
}
```

When I'm trying to save a workspace, the workspace data and members are being saved but not the custom fields. 
Payload:
Workspace {
  ownerId: 2,
  name: 'asd',
  description: '',
  fieldValues: [ { id: 1 } ],
  documents: [],
  members: [ { id: 2 } ] }

Log:
query: START TRANSACTION
query: INSERT INTO `workspaces`(`id`, `ownerId`, `name`, `description`, `settings`, `createdAt`, `updatedAt`, `deletedAt`) VALUES (DEFAULT, ?, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT) -- PARAMETERS: [2,"asd",""]
query: INSERT INTO `workspaces_members_users`(`workspacesId`, `usersId`) VALUES (?, ?) -- PARAMETERS: [24,2]
query: COMMIT

Am I missing something obvious here? There are no error messages regarding malformed relation data or missing columns or unknown properties.

Thanks for any help!
