### ISSUE TITLE
[sqlite] default value of columns in migration throw an error

### ISSUE THREAD

**Issue by pueue** [typeorm/typeorm#2092]
**Issue type:**

- [+] bug report

**Database system/driver:**

- [+] `sqlite`

**TypeORM version:**

- [+] `latest`

**Steps to reproduce or a small repository showing the problem:**

```ts
await queryRunner.createTable(new Table({
  name: 'User',
  columns: [
    {
      name: 'id',
      type: 'varchar',
      isPrimary: true,
    },
    {
      name: 'verified',
      type: 'boolean',
      default: false,
    }
  ]
}))
```
and enable `migrationsRun` in `createConnection()`.

Then `UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_ERROR: default value of column [verified] is not constant` is thrown.

**Comment by pleerock** [comment]
Try to set `default: 0` instead `default: false` - since sqlite does not support real boolean and use tinyint instead you may have this error.
