### ISSUE TITLE
Different syntax for choosing relations in ".find" method.

### ISSUE THREAD

**Issue by periman2** [typeorm/typeorm#2094]
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

First of all I wan to thank you for developing this amazing tool !

I would like to propose a new (or alternative) syntax of loading relations in the 'find' method since I'm not a big fan of the putting string literals to implement business logic. 

I'm thinking of something in the context of: 
```
For a simple case:
const channel = getConnection().getRepository(Channel).findOne(channeId, {
   relations: (channel: Channel) => channel.user
})

For more complex ones:
const relations = (channel: Channel) => [channel.user, channel.subscriptions]
const channel = getConnection().getRepository(Channel).findOne(channeId, {
   relations: relations 
})

For complex and nested relations: 
const nestedRelation = ( channel: Channel)  => ( subscription: Subscription ) => [channel.subscription.views, channel.subscription.remainder];

const relations = (channel: Channel) => [channel.user, nestedRelation(channel)]
const channel = getConnection().getRepository(Channel).findOne(channeId, {
   relations: relations 
})
```
I know this is adds much more overhead but in my personal opinion it increases productivity.
Let me know what you think of this and if it is at all possible.

**Comment by pleerock** [comment]
I think this breaks simplicity and readability - both are important to have. So, if we want to achieve type safety we need a better proposal I think

**Comment by periman2** [comment]
@pleerock  I guess you're right about that.
What about a kind of relational string builder?
Extremely simple implementation here: 
https://jsfiddle.net/b51vr5dh/
This only works if the names of the relationships are identical with the names of their classes.
I was thinking since you already manipulate the metadata using the @Column and @Entity operators maybe you could use this with the given names ? 
Maybe this is completely off scope I was just hoping it might help.

**Comment by pleerock** [comment]
I have a proposal for future of the find options in #2100. Let's keep discussion there.
