### ISSUE TITLE
[mysql] Database name isn't read from url

### ISSUE THREAD

**Issue by jcudzich** [typeorm/typeorm#2096]
**Issue type:**

[x] question

**Database system/driver:**

[x] `mysql` / `mariadb`

**TypeORM version:**

[x] `latest`

**Question:**

Hello,

I use mysql url connection string, but I get error:

```Option "database" is not set in your connection options, please define "database" option in your connection options or ormconfig.json```

When i add ```database``` property to connection options everything is fine, but why database name can't be read from url? My url:

```mysql://username:password@host:port/database```

I think that database should be reads from url when it's defined.
What do you think?

**Update:**
I'm not sure, but I think is bug, becouse when I debug connection I see that database name i corectly read from url, but error is throw by ```EntityMetadataValidator``` which not found database options in ```EntityMetadata```.

**Comment by pleerock** [comment]
are you able to dig into source code a bit and find a place with a problem?

**Comment by jcudzich** [comment]
I found that in `src/driver/mysql/MysqlDriver.ts` options property is set in line 242:

```
this.options = connection.options as MysqlConnectionOptions;
```

and in line 248 same file database property is set like this:

```
this.database = this.options.replication ? this.options.replication.master.database : this.options.database;
```

So problem is really simple. To create database property TypeORM use raw options, insted of options built by `DriverUtils.buildDriverOptions()` which has database parsed from url.

Replace above mentioned method to set options property in MysqlDriver solve problem.
After fix, line 242 in `src/driver/mysql/MysqlDriver.ts` is:
```
this.options = DriverUtils.buildDriverOptions(connection.options) as MysqlConnectionOptions;
```
I hope it was helpful.

**Comment by pleerock** [comment]
thanks for the investigations, are you able to provide a PR?

**Comment by jcudzich** [comment]
Sure, just give me some time :)

**Comment by vlapo** [comment]
I think this is no more issue. @jcudzich could you please test this on latest version of typeorm?

**Comment by nicolasigot** [comment]
Hello @vlapo ,
I just found this issue while getting it with version 0.2.11 of typeORM.
I provide URL with this format as explained above and no database as it is within the URL.
Same issue...

**Comment by vlapo** [comment]
Sorry for misunderstanding. I think it is fixed. But now I see we have this kind bug in all drivers. But in MySQL it is checked and throw error. I will check it later

**Comment by AndKiel** [comment]
I think it's not fixed, happening to me on `v0.2.13`.

**Comment by AlashaHonore** [comment]
Still not fixed in v0.2.17.

**Comment by giordy** [comment]
Still not fixed in v0.2.18

**Comment by cronosxfiles** [comment]
Still not fixed in v0.2.21

**Comment by vfasky** [comment]
Still not fixed in v0.2.22

**Comment by frostornge** [comment]
Still not fixed in v0.2.24

**Comment by edtownend** [comment]
for what it's worth, till the fix is released I've worked around this by regexing out the database from the connection string:
```
url: process.env.DB_URL,
database: process.env.DB_URL.match(/(?!.*\/)(.*)/)[1],
```

**Comment by ant45de** [comment]
My bugfix has been merged. Now it should work as intended :)
