### ISSUE TITLE
How can I extend Repository in a generic way?

### ISSUE THREAD

**Issue by babakyakhchali** [typeorm/typeorm#2097]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[*] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[0.1.21] `0.x.x` (or put your version here)

Hi
I'm using typeorm with routing-controllers to create a rest endpoint. I want to exend base repository class to have a method named saveAndReturn() which first calls a save() and the returns findOneById() to use for Put and Post request to send the newly created or updated object with default values in place. because I need this for all my repositories I can not use current approaches mentioned in [here](https://github.com/typeorm/typeorm/blob/master/docs/custom-repository.md) cause I need it to be generic. How can I do it?
thanks

**Comment by periman2** [comment]
@babakyakhchali The way I do it is simply by extending the repository class and using this extension instead of the repository:

```
export class RepoBase<T> extends Repository<T> {
//Your generic methods here
}
```
If you create custom repositories for each entity you can also do:
```
@EntityRepository(MyEntity)
export class MyEntityRepository extends RepoBase<MyEntity> {

}
```

So far this works well for me.

**Comment by babakyakhchali** [comment]
thanks but I dont want to create a repo for each of my entities. I need to add some common functionality to Repository class so I can use it on all repos created using
connection.getRepository(target);

**Comment by periman2** [comment]
@babakyakhchali  Then you only do the first step.
```
export class RepoBase<T> extends Repository<T> {
//Your generic methods here
}
```

Then you do:
```
connection.getRepository(RepoBase<target>);
```
only downside is that you'll have to import RepoBase everywhere you make the connnection.
(Maybe you'll need to do .getCustomRepository instead of the default method, not sure)

**Comment by pleerock** [comment]
I don't understand what is the issue here. You can create a class and put those methods there. There are [examples of custom repositories](https://github.com/typeorm/typeorm/blob/master/docs/custom-repository.md#custom-repository-without-extends) that are not tight to any entity at all.

**Comment by babakyakhchali** [comment]
I created my customer generic repository like below and now I want to create new repos based on it:
```ts
interface IId {
    id: number
}
export class ExRepo<E extends ObjectLiteral> extends Repository<E>{
    async saveAndReturn<T extends DeepPartial<E> & IId>(b: T, options?: SaveOptions) {
        await this.save(b, options);
        return this.findOneById(b.id);
    }
    async updateByIdAndReturn(id: any, partialEntity: DeepPartial<E>, options?: SaveOptions) {
        await this.updateById(id, partialEntity);
        return this.findOneById(id);
    }
}
```
is it possible?

**Comment by marceloverdijk** [comment]
@pleerock I'm actually look into the same right now. The [custom repository without extends](https://github.com/typeorm/typeorm/blob/master/docs/custom-repository.md#custom-repository-without-extends) example you shared actually depends on the `User`.
Not only is the repository named `UserRepository` but it also contains `return this.manager.findOne(User, { firstName, lastName });` using the `User` class.

What @babakyakhchali is meaning is that he wants to provide a custom "standard"/"base" repository that can be used for all repositories.

Let me try to explain. In my case I want to add `findPage(options)` method that queries a page of entities.
Now we don't want to create custom `User`, `Post` etc. repositories extending the custom repository.
We just would like to do something like `userRepository = getRepository(User);` which uses a configured custom "base" repository.

I think the best option is what @periman2 suggested: `connection.getRepository(RepoBase<target>);`
(but I didn't tried that myself.

On a related note: would you consider adding a `findPage(options)` method to typeorm.
This would introduce a Page object containing totalcount, has(Next|Previous)Page flags etc.

**Comment by marceloverdijk** [comment]
PS: @babakyakhchali solution using `getRepository(RepoBase<target>);` or `getCustomRepository(RepoBase<target>);` doesn't work for me. Both methods do not accept something like `RepoBase<User>` as argument...

So only option is to create a custom repo for each entity I guess...

**Comment by pleerock** [comment]
ORM provides you all functionality you need. 
You can organize classes whatever way you want, it does not depend on ORM. 
I even was thinking to drop custom repositories support since its one of the opinionated way how to organize your code. You can create hundred of others, orm provides all you need, everything else is up to you. If you need something that manages more then one entity then create that class and don't use custom repositories functionality. Repository is one repository for each entity in orm context. You probably need something else that you can create.

**Comment by santutu** [comment]
What is solution?

**Comment by santutu** [comment]
What is solution?

**Comment by santutu** [comment]
Use MyBaseEntity instead repo...


    import {BaseEntity, FindConditions, ObjectType} from 'typeorm';
    
        export default class MyBaseEntity extends BaseEntity {
    
            static async findOrCreate<T extends MyBaseEntity>(this: ObjectType<T>, conditions: FindConditions<T>): Promise<T> {
                let self = this as any;
                let entity = await self.findOne(conditions);
                if (!entity) {
                    entity = new self();
                    Object.assign(entity, conditions);
                    await entity.save();
                }
                return entity;
            }
        }

**Comment by hugoblanc** [comment]
So extending BaseEntity allow us to us save on it instead of using usual repo method ? 
I saw that we also have access to find, count  .. 
[BaseEntity.ts](https://github.com/typeorm/typeorm/blob/master/src/repository/BaseEntity.ts)
Did you tried it ? 
Do you know if it's usable ? 
I mean, can we really live without repository ?

**Comment by reverie** [comment]
Anyone found a solution here?

**Comment by reverie** [comment]
So, I think I'm getting close. At least to making a repository for each Entity with a single function call, rather than having to create N different classes.

```
class CustomRepository<Entity = void> extends Repository<Entity> {
  async get(...): Promise<Entity> {
    ...
  }
}
```
Then, later.
```
  function makeRepository<Entity>(entity: ObjectType<Entity>): CustomRepository<Entity> {
    const rep = new CustomRepository<Entity>();
    Object.assign(rep, {
      manager: db.manager,
      metadata: db.getMetadata(entity),
      queryRunner: db.manager.queryRunner,
    });
    (db.manager as any).repositories.push(rep);
    return rep;
  }
```
(...and passing around a context object with a constructed repository for each entity type.)

Everything typechecks and seems to work sometimes. The issue is that I get this runtime error: `No metadata found. There is more than once class-validator version installed probably. You need to flatten your dependencies.`. The suggestion is wrong; I don't have more than one class-validator version installed. I think deeper knowledge of type-graphql may be needed to debug.

**Comment by hmol** [comment]
Since I'm at the moment are working with really simple models, I want to do it this way:
`let users = await Repository<UserEntity>().find({ name: "Joe" });`

And if I want to query in another database table, I would like to do it like this:
`let cars = await Repository<CarEntity>().find({ color: "Red" });`

What I ended up doing was create a BaseRepository and a UserRepository, like this:

```
export class UserRepository extends BaseRepository<UserEntity> {
    
}
export default new UserRepository(UserEntity);
```

```
export default abstract class BaseRepository<T> {

    modelType;
    constructor(modelType) {
        this.modelType = modelType;
    }

    get Instance(): Repository<T> {
        return Db.Instance.GetRepository(this.modelType); // Db.Instance is object of type Connection
    }
}
```

And then using it in this manner:
`let users = await UserRepository.Instance.find({ name: "Joe" });`

**Comment by w11p3333** [comment]
my way


generic repository:

```typescript
import 'reflect-metadata';
import { Repository, Connection, ObjectType } from 'typeorm';

export class BaseRepository<T> extends Repository<T> {
  private connection: Connection;
  private entity: ObjectType<T>;

  constructor(entity: ObjectType<T>, connection: Connection) {
    super();
    this.entity = entity;
    this.connection = connection;
    Object.assign(this, {
      manager: connection.manager,
      metadata: connection.getMetadata(entity),
      queryRunner: connection.manager.queryRunner,
    });
  }

  test() {
    console.log('repo test', this.entity, this.connection);
  }

}
```

use:

```typescript
import { getConnectionManager } from 'typeorm';
import { MyEntity } from '../entity';
import { BaseRepository } from '../repository';

const repo = new BaseRepository(MyEntity, getConnectionManager().get('default'));
repo.test();
repo.findOne(options);
```

**Comment by nofacer** [comment]
```ts
export default interface IRead<T> {
    find(item: T): Promise<T[]>;

    findOne(id: string): Promise<T>;
}
```

```ts
export default interface IWrite<T> {
    create(item: T): Promise<boolean>;

    update(id: string, item: T): Promise<boolean>;

    delete(id: string): Promise<boolean>;
}
```
```ts
export abstract class BaseRepository<T> implements IWrite<T>, IRead<T> {
    modelType: ObjectType<T>;

    protected constructor(modelType: ObjectType<T>) {
        this.modelType = modelType;
    }

    async getConnection(): Promise<Connection> {
        const connectionManager = getConnectionManager();
        if (!connectionManager.has("default")) {
            logger.debug("generate new db connection")
            const connection = connectionManager.create({
                type: "sqlite",
                database: Constants.dbPath,
                entities: [
                    path.join(__dirname, "../do/*{.ts,.js}")
                ],
                synchronize: true,
            });
            await connection.connect();
            return connection
        } else {
            logger.debug("reuse db connection")
            return connectionManager.get();
        }
    }


    async create(item: T): Promise<boolean> {
        try {
            const connection = await this.getConnection();
            const repository = connection.getRepository(item.constructor);
            await repository.save(item);
            return true;
        } catch (e) {
            logger.error(e);
            return false;
        }
    }

    delete(id: string): Promise<boolean> {
        return Promise.resolve(false);
    }

    find(item: T): Promise<T[]> {
        return Promise.resolve([]);
    }

    async findOne(id: string): Promise<T> {
        try {
            const connection = await this.getConnection();
            const repository = connection.getRepository(this.modelType);
            const result = await repository.findOne(id);
            if (result) return result;
            return null;
        } catch (e) {
            return null;
        }
    }

    update(id: string, item: T): Promise<boolean> {
        return Promise.resolve(false);
    }

}
```
```ts
export default class BookRepository extends BaseRepository<BookDo> {
    constructor() {
        super(BookDo);
    }
}
```

**Comment by RufatGulabli** [comment]
This is my implementation of BaseCRUDService with `typeorm & typedi`

```
BaseModel.ts

@Entity()
export abstract class BaseModel {
  @PrimaryGeneratedColumn()
  public readonly id: number
}
```

```
Student.ts

@Entity('students')
export class Students extends BaseModel {
  @Column({ type: 'text' })
  public name: string
}
```

```
BaseCRUDService.ts

@Service()
export class BaseCRUDService<BaseModel> {
  constructor (
    protected repository: Repository<BaseModel>
  ) {}

  public async create (model: BaseModel): Promise<BaseModel> {
    return await this.repository.save(model)
  }

   other CRUD methods here ....
}
```

```
StudentService.ts

@Service()
export class StudentService extends BaseCRUDService<Student> {
  constructor (
    @InjectRepository(Student)
    protected repository: Repository<Student>
  ) {
    super(repository)
  }
}
```
