### ISSUE TITLE
Question: Electron + TypeORM + Webpack UglifyJsPlugin

### ISSUE THREAD

**Issue by cjackson234** [typeorm/typeorm#2104]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm setting up my connection like this:

```
 import { Table1 } from '../../entity/table1';
 import { Table2 } from '../../entity/table2';
 import { Table2 } from '../../entity/table3';

 const dbpath = require('os').homedir() + '/.myapp/db.sqlite'

 createConnection({
            type: 'sqlite',
            database: dbpath,
            entities: [
                Table1,
                Table2,
                Table3
            ]
        }).then(connection => {
            console.log('connected to sql from typeorm')
        }).catch(error => console.log(error));
```

This works just fine in dev, but in prod, it fails to find the tables.

> QueryFailedError: SQLITE_ERROR: no such table: e

I suspect its because in prod, webpack runs UglifyJsPlugin. Doe's anyone know how to fix this?

**Comment by pleerock** [comment]
you need to put table name into entity like this: `@Entity("table1") export class Table1 {`

**Comment by cjackson234** [comment]
Is this in the documentation somewhere?

**Comment by pleerock** [comment]
No, usually typeorm is used on the backend where minification is not happening thats why its not documented. But feel free to contribute and add this question and answer to it in FAQ.

**Comment by cjackson234** [comment]
When calling save I get the following. 

> Error: Uncaught (in promise): Error: Cyclic dependency: "e"

I do have OneToMany relationships on the object. Is there something additional I have to do?

**Comment by AmirTugi** [comment]
Experiencing this with MySQL and webpack as well
Driving me crazy

**Comment by dominic-simplan** [comment]
@pleerock I can confirm the Cyclic dependency error occurs when trying to save an entity (with a relation to another entity?) even though all entities have the decorator set.
Could you reopen this ticket?

A workaround seems to be to set the reserved option of UglifyJS to the list of entity names:
```
mangle: {
   reserved: ["AppSetting", "ProjectSettings", "Product"]
},
```

**Comment by pleerock** [comment]
or maybe simply disable mangle

**Comment by barczaG** [comment]
Quick fix: 
```
// webpack.config.js
module.exports = {
...
optimization: {
    minimize: false
  }
...
```

**Comment by pallymore** [comment]
If you are using Webpack 4, make sure to tell UglifyJS to not change function or classnames.

https://user-images.githubusercontent.com/2566530/49559629-64f46800-f8dd-11e8-8d90-cfd98c580e3a.png

Also I found out for migration files, it's good to change the libraryTarget to `umd` (migration files need to be processed separately since we want to keep their filenames)

**Comment by Adizbek** [comment]
>    reserved: ["AppSetting", "ProjectSettings", "Product"]

How to set up it in Vue ? vue has vue.config.js which contains all configs.
