### ISSUE TITLE
Raw Query Caching

### ISSUE THREAD

**Issue by MarkMatute** [typeorm/typeorm#2105]
**Issue type:**

[* ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[/] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[/ ] `0.1.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
await entityManager.query(`SELECT * FROM vital_group_mapping`);
```
Is there a way to enable caching in this? Instead of using caching with tht createQueryBuilder?

**Comment by pleerock** [comment]
no, this is not supported, caching is a query builder feature, so you have to build your query using it instead.

**Comment by pavelkalin** [comment]
@pleerock Has anything  changed since 2018? If not, are there plans to support caching of raw queries?

**Comment by cdbattags** [comment]
Hi folks, I have the same question as @pavelkalin. This would be an easy feature to add, no? I don't mind doing the work for it.

**Comment by pavelkalin** [comment]
@cdbattags @pleerock Created this - https://github.com/typeorm/typeorm/issues/8958 for a proper discussion. I also don't mind developing it. I've already allocated some time at work for this feature.
