### ISSUE TITLE
error TS2305: Module '"/node_modules/typeorm/index"' has no exported member 'Like'.

### ISSUE THREAD

**Issue by zkeyword** [typeorm/typeorm#2109]
When importing:

import { getManager, Like } from 'typeorm'

TypeORM version:

0.1.21

Error: 

error TS2305: Module '"/node_modules/typeorm/index"' has no exported member 'Like'.

**Comment by pleerock** [comment]
update to latest version, 0.1.0 is old and does not have this functionality.

**Comment by zkeyword** [comment]
http://typeorm.io/#/find-options is old?

**Comment by pleerock** [comment]
no its not, your typeorm version is old
