### ISSUE TITLE
[Postgres]: Where clause issue

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#211]
I have a Select Where In query that isn't working with query builder. 

I'm stuck, not sure what i'm doing wrong.. It may be a bug or simply my mistake. Would really appreciate some help.  

                .createQueryBuilder("ac")
                .where("ac.sId = :sId", { sId })
                .andWhere("ac.code IN (:codes)", { codes: codes.join(",") })
                .getOne();

It translates to SQL...

    SELECT "ac"."sId" AS "ac_sId", "ac"."code" AS "ac_code" FROM "table" "ac" WHERE "ac"."code" IN   ($1) -- PARAMETERS: ["treci"]

But no results return. 

I copied and pasted the SQL in Pgadmin and ran it and it failed. But...once I changed "ac"."code" IN ("treci") to "ac"."code" IN ('treci') it worked. 

Is there a quote issue?

**Comment by pleerock** [comment]
What was the issue?

**Comment by dcworldwide** [comment]
I made a silly mistake with my async test logic, was trying to read a record that didn't exist. :man_facepalming:

**Comment by pleerock** [comment]
in your code btw, instead of ` { codes: codes.join(",") }` you should just do `{ codes: codes }`

**Comment by dcworldwide** [comment]
Thanks. That's neat. I didnt see an example in the docs for where in queries.
