### ISSUE TITLE
Question: How can I create a column that references another column in the same entity?

### ISSUE THREAD

**Issue by wrod7** [typeorm/typeorm#2111]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

How can I create a column in my entity that is the sum of other columns in the same entity?

For example:

ALTER TABLE Item
ADD UnitsAvailable AS UnitsOnHand + UnitsOnOrder - UnitsReserved

**Comment by serranoarevalo** [comment]
I've got something like that on my entity (a column made up by other ones) but actually I don't know if its called a column. In my case all I'm doing is putting first name and last name together.

Entity:

````
@Entity()
class User extends BaseEntity {
  @PrimaryGeneratedColumn() id: number;

  @Column({ type: "text" })
  firstName: string;

  @Column({ type: "text" })
  lastName: string;

  fullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }
}
export default User;

````

I can then just call user.fullName and it works.

Cheers!

**Comment by wrod7** [comment]
Thanks for the suggestion @serranoarevalo 

This could work for me long term. I am moving an app to react with a new backend graphql api and the current database has fields that are the sum of others. I want to keep the database the same but I guess I could change the old backend if there isn't a way to do this.
