### ISSUE TITLE
Performance issue for selecting with Many-to-Many relationship

### ISSUE THREAD

**Issue by JiriBalcar** [typeorm/typeorm#2114]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.5`

**Steps to reproduce or a small repository showing the problem:**

```ts
@Entity()
export class Subscriber {
  @PrimaryGeneratedColumn() id: number;
  @Column({
    type: 'varchar'
  })
  email: string;
  @ManyToMany(type => MailingList, mailingList => mailingList.subscribers)
  mailingLists: MailingList[];
  @Column({
    name: 'del_flag'
  })
  delFlag: Boolean;
  @Column() solicited: Boolean;
  @Column() unsubscribed: Boolean;
}

@Entity('mailing_list')
export class MailingList {
  @PrimaryGeneratedColumn() id: number;
  @Column({
    type: 'varchar'
  })
  name: string;
  @ManyToMany(type => Subscriber, subscriber => subscriber.mailingLists)
  @JoinTable({
    name: 'mailing_list_subscriber',
    joinColumn: { name: 'mailing_list_id', referencedColumnName: 'id' },
    inverseJoinColumn: { name: 'subscriber_id', referencedColumnName: 'id' }
  })
  subscribers: Subscriber[];
}
```
In table Subscriber I have around **100 000 records** and in mailing_list_subscriber around **110 000 records**. When I try to run query below it takes significant amount of time (> 1min). 

```ts 
const repo = getManager().getRepository(Subscriber);
let subscribers = repo
  .createQueryBuilder('subscriber')
  .leftJoinAndSelect('subscriber.mailingLists', 'mailingList')
  .where('subscriber.del_flag = 0')
  .skip(10)
  .take(10)
  .getManyAndCount(); 
```

**Comment by pleerock** [comment]
Are you able to get all generated sql queries and run them and check how long they are running? Also, are you able to setup a git repo with minimal reproduction?

**Comment by JiriBalcar** [comment]
It hangs on this query, and it does not return results in 30sec (MYSQL timeout for reads). And MYSQL connection shows "State: Copying to tmp table"

```sql
SELECT DISTINCT
    `distinctAlias`.`subscriber_id` AS 'ids_subscriber_id'
FROM
    (SELECT 
        `subscriber`.`id` AS `subscriber_id`,
            `subscriber`.`email` AS `subscriber_email`,
            `subscriber`.`del_flag` AS `subscriber_del_flag`,
            `subscriber`.`solicited` AS `subscriber_solicited`,
            `subscriber`.`unsubscribed` AS `subscriber_unsubscribed`,
            `mailingList`.`id` AS `mailingList_id`,
            `mailingList`.`name` AS `mailingList_name`
    FROM
        `subscriber` `subscriber`
    LEFT JOIN `mailing_list_subscriber` `mailingList_subscriber` ON `mailingList_subscriber`.`subscriber_id` = `subscriber`.`id`
    LEFT JOIN `mailing_list` `mailingList` ON `mailingList`.`id` = `mailingList_subscriber`.`mailing_list_id`
    WHERE
        subscriber.del_flag = 0) `distinctAlias`
ORDER BY `subscriber_id` ASC
LIMIT 10 OFFSET 20;
```

**Comment by JiriBalcar** [comment]
I created repro repository https://github.com/JiriBalcar/typeorm_issue_2114 where the query take about 7 seconds.

**Comment by pleerock** [comment]
Okay so as you can see SQL takes lot of time and it works slowly not because of orm but because of your query. Why SQL is slow? Because when you select data and join lot of other data and select that data sql returns everything in rows and multiplies data which results into millions of returned rows.

Solution is to execute separate query for your subscribers, load only them, then execute separate query for mailing lists and load them, then map mailing lists into subscribers manually in your code.
