### ISSUE TITLE
Updating to new QueryRunner

### ISSUE THREAD

**Issue by vance** [typeorm/typeorm#2115]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

From the changelog: 

> insert, update and delete methods of QueryRunner now use InsertQueryRunner, UpdateQueryRunner and DeleteQueryRunner inside

Can you please clarify? When I upgrade, I do not find the types for `InsertQueryRunner` or `UpdateQueryRunner` etc. I do find the new QueryBuilders though.
```js
// The old implementation inside our migrations:
queryRunner: QueryRunner;
queryRunner.update(
      'public.someTechnologyTable',
      { technology: 'someTechnology' },
      { name: 'banana-pad' },
)
```
However queryRunner.update() is no longer defined and not sure what the new equivalent is.

**Comment by pleerock** [comment]
looks like this change in changelog is a bit wrong. it was working this way but lately we completely removed those methods. Now you need to use query runner instead:

```ts
queryRunner.manager.createQueryBuilder()
   .insert()
  .into(...)
  .values({ ... })
  .execute()
```
