### ISSUE TITLE
Question: Best approach to avoid violation of UNIQUE KEY constraint when save with cascade

### ISSUE THREAD

**Issue by wy193777** [typeorm/typeorm#2116]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Currently, the `save` method with `{cascade: true}` will not work if the referenced entity already existed in the database. Is there a convenient way to save data with possibilities that referenced entity has already existed without query database back and forth to check existence and works with transactions?

**Comment by pleerock** [comment]
provide a minimal possible example and reproduction git repo please

**Comment by wy193777** [comment]
I created a test but cannot run the test properly. https://github.com/wy193777/typeorm/tree/master/test/github-issues/2116

Basically, save two child entity with the same parent on cascading mode will cause violation of duplicate key error.

**Comment by wy193777** [comment]
User entity.
```typescript
@Entity()
@Unique(["name"])
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @OneToMany(type => Photo, photo => photo.user)
    photos: Photo[];

}
```

Photo entity
```typescript
```

**Comment by pleerock** [comment]
maybe you simply create a PR with code you added and let CI to run tests?

**Comment by Kononnable** [comment]
@wy193777 
Did you resolve your issue?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
