### ISSUE TITLE
Property 'findOne' does not exist on type 

### ISSUE THREAD

**Issue by serranoarevalo** [typeorm/typeorm#2118]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello!

So I've got this entity:

````

@Entity()
class User extends BaseEntity {
  @PrimaryGeneratedColumn() id: number;

  @Column({ type: "text", unique: true })
  @IsEmail()
  email: string;

  @Column({ type: "bigint", nullable: true })
  facebookId: number;

  @Column({ type: "text" })
  firstName: string;

  @Column({ type: "text" })
  lastName: string;
}
export default User;
````
And later on in my code I'm trying to do:

```const user: User = await User.findOne({ email: "lala@lala.com" });```

But I'm getting an error that says:

```Property 'findOne' does not exist on type 'User'```

What am I doing wrong?

Cheers!

**Comment by pleerock** [comment]
Sure you import a correct User instance?) Please provide a reproduction repo

**Comment by serranoarevalo** [comment]
It has to be an instance? Im just importing the entity file User.ts with the default export.

**Comment by pleerock** [comment]
no i meant class itself. provide a reproduction repo and let me take a look

**Comment by serranoarevalo** [comment]
https://github.com/serranoarevalo/nuber/blob/master/server/src/api/User/emailSignIn/emailSignIn.resolvers.ts

There you can see the const user : User, that one gives me an error.

**Comment by pleerock** [comment]
its not a minimal reproduction git repo. Its something on your side Im sure thats why try to debug and start with a empty repository to find a problem.

**Comment by serranoarevalo** [comment]
Thanks.

**Comment by pleerock** [comment]
@cjackson234 actually he used active record model and extends `BaseEntity` so all those methods are available for him in a user class.

**Comment by cjackson234** [comment]
Ahh! I see that now. I didn't know you could do that.

**Comment by VishalTank** [comment]
I am facing the same issue. I'm using Active Record Model with extended `BaseEntity` class and I'm getting the error `Property 'save' does not exist on type 'IRoom'` where IRoom is my interface: 
`export interface IRoom {
	id: number;
	room_id: string;
	members: string[];
	createdAt?: Date;
	updatedAt?: Date;
}`
