### ISSUE TITLE
In Memory Caching

### ISSUE THREAD

**Issue by MarkMatute** [typeorm/typeorm#2123]
**Issue type:**

[/] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[/] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
["0.1.17"] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. What would be advantage to store again the results on other table? then query it again.(Im trying not to hit mysql again)
2. Redis(Is Okay)
3. Is there a way to use "in memory" caching with typeorm?

**Comment by pleerock** [comment]
Have you tries [this](http://typeorm.io/#/caching)?

**Comment by karladler** [comment]
see this PR: https://github.com/typeorm/typeorm/pull/5195/files

**Comment by acathur** [comment]
Just created a lightweight cache module [typeorm-cache](https://www.npmjs.com/package/typeorm-cache) based on [keyv](https://www.npmjs.com/package/keyv). By default caching will work in memory.
