### ISSUE TITLE
When would the type argument to typeFunction of the ManyToOne and OneToMany decorators be used?

### ISSUE THREAD

**Issue by rduncan** [typeorm/typeorm#2130]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In the case referenced in the documentation the type argument to the typeFunction of a ManyToOne or OneToMany decorator is unused.  Thus the more appropriate declaration would be

```
    @ManyToOne(() => User, user => user.photos)
    user: User;
```
and

```
   @OneToMany(() => Photo, photo => photo.user)
    photos: Photo[];
```

This prevents an error when compiling with --noUnusedParameters. 

Is there a good example of how the parameters might be used?

**Comment by pleerock** [comment]
they are never used. Its just "syntax sugar". You can use () instead without any issues. Especially if you have noUnusedParameters flag enabled.
