### ISSUE TITLE
InsertResult return the same primary key

### ISSUE THREAD

**Issue by eightHundreds** [typeorm/typeorm#2131]
**Issue type:**

[ x] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `sqlite`

**TypeORM version:**

[x ] `@next`

```
@Entity()
export default class Marker extends BaseEntity {
  @PrimaryGeneratedColumn() id = undefined

  @Column('varchar') type = undefined
  @Column('varchar', {
    nullable: true
  })
  desc = undefined
  @Column('double') long = undefined
  @Column('double') lat = undefined

  @Column('varchar', {
    nullable: true
  })
  data = undefined

  @CreateDateColumn() createTime = undefined
  @UpdateDateColumn() updateTime = undefined

  @ManyToOne(type => ProjectPanorama,{
    onDelete: 'CASCADE'
  })
  projectPanorama
}

console.log(project.panoramas.find(projectP => projectP.id === p.id).markers)

const newMarkers = (await connection
        .createQueryBuilder()
        .insert()
        .into(Marker)
        .values(project.panoramas.find(projectP => projectP.id === p.id).markers)
        .printSql()
        .execute()).identifiers 
console.log(newMarkers)

```
first log
```
 [    { 
          type: 'jump',
          desc: null,
          long: 2,
          lat: 1.5,
          data: null,
          createTime: '2018-05-13T08:41:04.000Z',
          updateTime: '2018-05-13T08:41:04.000Z' },
        { desc: 'my desc', type: 'jump', long: 1, lat: 1 } 
]
```
second log 
```
 [ { id: 92 }, { id: 92 } ]
```

**Comment by dmlux** [comment]
Same happens when using mysql databases. Would be cool if "identifiers" and "generatedMaps" contain the correct ids for all inserted objects.

**Comment by robck** [comment]
An option to not return the ids and avoid making a new select query for each inserted row would be ideal too 

If you insert 100 rows, it will make 100 select statements after the insert. Crazy stuff. It selects only the Id and the CreateDateColumn

**Comment by okischuang** [comment]
Hi everyone, so any updates here? Is it because of driver or sth?
I checkout the log from `ReturningResultsEntityUpdator.js` and `identifiers` are already polluted before being pushing to `insertResult.identifiers` array.

**Comment by lucashfreitas** [comment]
Same as #4682

**Comment by Ryan-Shang** [comment]
Meet the same situation. Is there any updates or solutions?

**Comment by bobbyinsane** [comment]
any work around for this?

**Comment by jagabs** [comment]
updates anyone?

**Comment by wiktor-mazur** [comment]
Any updates on this? It's really annoying bug...

**Comment by olosegres** [comment]
I spent a lot of hours trying to find caouse of much higher level bug, but the root of the problems, as it turned out, is this bug :(

**Comment by imnotjames** [comment]
https://github.com/typeorm/typeorm/pull/6440 might make this issue clearer - I think this is related to the error that PR is "preventing" by throwing an error instead of just continuing along as if nothing went wrong.

**Comment by dolsup** [comment]
I created a PR #6668 to end this tragedy.

**Comment by imnotjames** [comment]
That only fixes the issue for MySQL when you're inserting multiple entities - that doesn't fix this issue.

**Comment by dolsup** [comment]
@imnotjames My PR includes fix for sqlite. Please check this out. If there is anything I missed, could you advise on that?

**Comment by imnotjames** [comment]
Ah, you're right.  I missed that in the PR, apologies.

**Comment by htrilasoft** [comment]
Still getting this same issue for sql.js and capacitor sqlite
