### ISSUE TITLE
leftJoinAndSelect with subQuery example?

### ISSUE THREAD

**Issue by darkbasic** [typeorm/typeorm#2132]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,
I have the following query:

```ts
let query = connection
  .createQueryBuilder(Chat, "chat")
  .leftJoin('chat.listingMembers', 'listingMembers')
  .where('listingMembers.id = :id', {id: currentUser.id})
  .leftJoinAndSelect('chat.messages', 'messages')
  .orderBy({
    "messages.createdAt": {order: "DESC", nulls: "NULLS LAST"},
    "chat.id": "DESC",
  });
```

I would like to filter the messages, with the following:

```ts
  .innerJoin('messages.holders', 'holders', 'holders.id = :userId', {userId: currentUser.id})
```

Unfortunately if I simply append the previous method it will filter out all the chats without messages, while I simply want to filter out all the messages which do not match the criteria.

I think that in order to obtain the desired result I will have to use `leftJoinAndSelect` with a `subQuery`, then do the `innerJoin` inside the `subQuery`. Unfortunately I didn't find any usage example with `subQuery` and `leftJoinAndSelect`, so I didn't manage to get it working.
Can you please tell me the right syntax in order to achieve that?

Thanks

**Comment by pleerock** [comment]
There are [examples](http://typeorm.io/#/select-query-builder/using-subqueries) how to create subqueries in docs. Its better if you create sql query you want to execute first, then try to convert it to query builder. From what I got you need to do:

```ts
  .innerJoin('messages.holders', 'holders')
  .where('holders.id = :userId OR holders IS NULL')
```

**Comment by pleerock** [comment]
you can't use values from top-level query in subquery. If you want me to help, then please provide a data table of what you have, and data table of what are your expected result. Also write SQL that resolves your problem before trying to build it using query builder.

**Comment by darkbasic** [comment]
Here is the data I have: https://github.com/Urigo/whatsapp-server-express/blob/master/db.ts

This is the data I want to get:
```
[ Chat {
    id: 8,
    name: 'Ethan\'s group',
    picture: 'https://randomuser.me/api/portraits/thumb/lego/1.jpg',
    messages: [ [Object], [Object], [Object] ] },
  Chat {
    id: 3,
    name: null,
    picture: null,
    messages: [ [Object], [Object] ] },
  Chat { id: 2, name: null, picture: null, messages: [ [Object] ] },
  Chat {
    id: 1,
    name: null,
    picture: null,
    messages: [ [Object], [Object] ] },
  Chat { id: 10, name: null, picture: null, messages: [] },
  Chat { id: 7, name: null, picture: null, messages: [] },
  Chat { id: 6, name: null, picture: null, messages: [] } ]
```

I can get it with the following query:
```ts
let query = connection
  .createQueryBuilder(Chat, "chat")
  .leftJoin('chat.listingMembers', 'listingMembers')
  .where('listingMembers.id = :id', {id: currentUser.id})
  .leftJoinAndSelect('chat.messages', 'messages')
  .orderBy({
    "messages.createdAt": {order: "DESC", nulls: "NULLS LAST"},
    "chat.id": "DESC",
  });

console.log(await query.getMany());
```

The only part that's missing is that I also want to filter the messages, displaying only the ones that are 'holded' by the current user. It means doing an inner join between `messages` and `holders` with the condition `holders.id = :userId`.

I basically want to achieve the following: https://stackoverflow.com/questions/28590173/sql-inner-joining-to-left-joined-table
`messages` and `holders` must be inner-joined first, then the result needs to be left-joined with `chats`.

I tried with:
```ts
let query = connection
  .createQueryBuilder(Chat, "chat")
  .leftJoin('chat.listingMembers', 'listingMembers')
  .where('listingMembers.id = :id', {id: currentUser.id})
  .leftJoinAndSelect('chat.messages', 'messages')
  .innerJoin('messages.holders', 'holders', 'holders.id = :userId', {userId: currentUser.id})
  .orderBy({
    "messages.createdAt": {order: "DESC", nulls: "NULLS LAST"},
    "chat.id": "DESC",
  });
```

but this is the result:
```
[ Chat {
    id: 8,
    name: 'Ethan\'s group',
    picture: 'https://randomuser.me/api/portraits/thumb/lego/1.jpg',
    messages: [ [Object], [Object], [Object] ] },
  Chat {
    id: 3,
    name: null,
    picture: null,
    messages: [ [Object], [Object] ] },
  Chat { id: 2, name: null, picture: null, messages: [ [Object] ] },
  Chat {
    id: 1,
    name: null,
    picture: null,
    messages: [ [Object], [Object] ] },
```

It doesn't display chats 6, 7 and 10 because they don't have any message. It's like if it does the left join between `chats` and `messages` BEFORE the inner join between `messages` and `holders`, which is not want I want.

**Comment by Kononnable** [comment]
@darkbasic 
Did you resolve your issue?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.

**Comment by Pawelh133** [comment]
I see i have similar issue. Im very begging on typeorm. 

its one table with 3 columns `device_id`,`datetime`and `temperature`
1. I want to put array of `devicescodes` as parameter
2. aggregated select is searching for row with max datetime
3. external select is just for adding the rest of the columns in found row.
working SQL script: 
```SELECT a.device_id , temperature
      FROM database.table a
        INNER JOIN(
          SELECT device_id, MAX(datetime)
          FROM database.table
          GROUP BY device_id
        ) b ON a.device_id = b.device_id AND a.datetime = b.datetime
      WHERE a.device_id IN devicecodes
```
How to write it in typeorm?
my script (which doesnt work)
```
const queryBuiler = await this.deviceDataRepository.createQueryBuilder('deviceData')
      .select(['deviceData.deviceCode', 'MAX(deviceData.recDateTime)'])
      .from(DeviceData, 'deviceData')
      .groupBy('deviceData.deviceCode');

    const result = await this.deviceDataRepository.createQueryBuilder('deviceData')
      .select(['deviceData.deviceCode', 'temperature'])
      .innerJoin(subquery => {
        return subquery
          .select(['deviceData.deviceCode', 'MAX(deviceData.recDateTime)'])
          .from(DeviceData, 'deviceData')
          .groupBy('deviceData.deviceCode');
      }, 'deviceData')
      .setParameters(queryBuiler.getParameters())
      .where('deviceData.deviceCode IN (:...devicesSerials)', { devicesSerials })
      .getRawMany();
```

**Comment by sgentile** [comment]
I also have something similar to this:
```
.leftJoinAndSelect(subQuery => {
  return subQuery
    .from(Message, "message")
    .innerJoinAndSelect('message.chat', 'chat')
    .innerJoin('message.holders', 'holders', 'holders.id = :userId', {userId: currentUser.id})
    .orderBy({"message.createdAt": "DESC"});
}, "messages", 'chat.id = message.chat.id')
```

ie. I want to do a leftJoinAndSelect and do a 'take' - where i only want to take 10.   I don't see how to do something like this.  And I can't use 'getRawMany'

**Comment by Hiroki111** [comment]
I too would like to know how to use `leftJoinAndSelect` with `subQuery`.

```
@Entity('staff')
export class StaffEntity {
    // other fields here

    @OneToMany(() => StaffAvailabilityEntity, (availableDates) => availableDates.staff)
    availableDates!: StaffAvailabilityEntity[];
}

@Entity('staff_availability')
export class StaffAvailabilityEntity {
    // other fields here

    @ManyToOne(() => StaffEntity, (staff) => staff.availableDates)
    @JoinColumn({ name: 'staff_id' })
    staff!: StaffEntity;
}
```
One `StaffEntity` has many `AvailabilityDate`.

```
const staffList = await getRepository(StaffEntity)
    .createQueryBuilder('staff')
    .select(['staff.id'])
    .leftJoinAndSelect(
        sq => sq.select(['date', 'staff_id']).from(AvailabilityDateEntity, 'availableDates'),
        'availableDates',
        '"availableDates"."staff_id" = staff.id'
    )
    .getMany();
```
The code above will return an array of `StaffEntity`, but each `StaffEntity` has no `availableDates`.

If I replace ` '"availableDates"."staff_id" = staff.id'` with ` 'availableDates.staff_id = staff.id'`, I get the following error:

```
error QueryFailedError: missing FROM-clause entry for table "availabledates"

query:
 'SELECT "staff"."id" AS "staff_id"
  FROM "staff" "staff"
  LEFT JOIN (SELECT date, staff_id FROM "staff_availability" "availableDates") "availableDates" ON availableDates.staff_id = "staff"."id"
```

It seems `leftJoinAndSelect` can't use `subQuery`

**Comment by Levis44** [comment]
I found hard to try using .leftJoinAndSelect with subQuery. In some cases it can be a little tricky.
What I needed to do was relate 2 tables. Here is an example just to simplify my explanation:

# Problem

Imagine we have this 2 entities:

```ts
@Entity('tb_users')
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('varchar')
  name: string;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @OneToMany(() => UserViews, (userViews) => userViews.user)
  userViews: UserViews[];
}

@Entity('tb_user_views')
export class UserViews {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('varchar', { name: 'user_id' })
  userId: string;

  @Column('varchar')
  name: string;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @ManyToOne(() => User, (user) => user.userViews, {
    onUpdate: 'CASCADE',
  })
  @JoinColumn([{ name: 'user_id', referencedColumnName: 'id' }])
  user: User;
}
```

In that case, we have the table users, wich is going to strore our users. UserViews, we will use to store the views wich certain user got on their profile.

What I needed to do was, pick all my users and the last viewed registred in my tb_user_views.

# Solution

I just achieved what I needed (in a certain way rsrs) doing this:

```ts
const users = this.connection
  .createQueryBuilder(User, 'user')
  .leftJoinAndSelect(
    (qb) =>
      qb
        .select()
        .from(UserViews, 'views')
        .orderBy('executed.createdAt', 'DESC')
        .limit(1),
    'userViews',
    'userViews.user_id = user.id',
  )
  .getRawMany(); // getMany() does not work
```

# Result

It was really hard to achieve this, because I was trying with .getMany(), I don't know why, but just worked with .getRawMany(). Otherwise, the result is not so satisfying. It kind looks like this:

```json
[
  {
    "user_id": "77",
    "user_name": "Levi",
    "user_createdAt": "2022-04-03T01:09:34.451Z",
    "id": "25",
    "userId": "76",
    "createdAt": "2022-04-03T02:04:01.000Z"
  }
]
```

.getRawMany() seems to work.

Hope it helped someone! ;)

**Comment by Nielio** [comment]
Since i was not happy with `getRawMany`, because you can not parse that data to TypeORM Entities, i tried to solve this problem on my own.

**AND HERE IT IS!**

You can use the subquery in the contition param on the joins functions. 

```typescript
 const subQuery = this.connection
      .createQueryBuilder(UserViews, 'views')
      // where and other things also possible
      .orderBy('views.createdAt', 'DESC')
      .limit(1);

    this.connection
      .createQueryBuilder(User, 'user')
      .andWhereInIds(id)
      .leftJoinAndSelect(
        'user.userViews',
        'views',
        `views.id IN (${subQuery.select('id').getQuery()})`,
      )
      .getOne();
```

I did not testet it with your model, but for my stuff this works very well. I hope someone finds this helpfull :)

It should also be possible to nest multiple subqueries and do some komplex filtering stuff. Especially good for access controll handling.

**Comment by TerryPanBigT** [comment]
> Since i was not happy with `getRawMany`, because you can not parse that data to TypeORM Entities. I tried to solve this problem on my own.
> 
> **AND HERE IT IS!**
> 
> You can use the subquery in the contition param on the joins functions.
> 
> ```ts
>  const subQuery = this.connection
>       .createQueryBuilder(UserViews, 'views')
>       // where and other things also possible
>       .orderBy('views.createdAt', 'DESC')
>       .limit(1);
> 
>     this.connection
>       .createQueryBuilder(User, 'user')
>       .andWhereInIds(id)
>       .leftJoinAndSelect(
>         'user.userViews',
>         'views',
>         `views.id IN (${subQuery.select('id').getQuery()})`,
>       )
>       .getOne();
> ```
> 
> I did not testet it with your model, but for my stuff this works very well. I hope someone finds this helpfull :)
> 
> It should also be possible to nest multiple subqueries and do some komplex filtering stuff. Especially good for nested access control handling.

Suppose the subQuery return a list of Ids, will In clause affect the performance ?
