### ISSUE TITLE
type bigint

### ISSUE THREAD

**Issue by guotie** [typeorm/typeorm#2134]
**Issue type:**

[*] question

**Database system/driver:**

[ ] `mysql` / `mariadb`

**TypeORM version:**

[ ] `latest`

**Steps to reproduce or a small repository showing the problem:**

If a define a column with type bigint, then i got this field as string?

for example:

```

@Entity()
export class Follow {
  @PrimaryGeneratedColumn()
  id: number

  @Column({ type: "bigint" })
  uid: number   


  static async testBigInt(id: number) {
    let f = await getRepository(Follow).findOne({uid: id})
    console.log(typeof f.uid)
  }
}

Follow.testBigint(1)
```

then, I got string

**Comment by pleerock** [comment]
its an expected behaviour. javascript's numbers can't fit huge bigint values

**Comment by guotie** [comment]
Ok.

**Comment by dev-jbam** [comment]
It might be helpful to represent `bigint` columns using the `Long` library.
This is the approach that the javascript/typescript implementation of Protocol Buffers uses.

**Comment by pleerock** [comment]
make requests to underlying libraries. But I guess they won't implement it. We have to wait until bigint come within next es standard.

**Comment by lal12** [comment]
Actually nodejs already supports bigint since 10.4 and typescript will in the next release 3.2 (RC is already out).

**Comment by ihack2712** [comment]
What about the `BigInt` type? It has been supported since Node v10, if not longer.
