### ISSUE TITLE
Many-to-Many where clause on join table

### ISSUE THREAD

**Issue by colum-ferry** [typeorm/typeorm#2135]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.5` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm using `Typeorm@0.2.5` with MySql driver.   
I have an entity, `MyEntity`, which has a many-to-many relationship with another entity, `RelEntity`. Therefore Typeorm generates a pivot table of the PKs to create the relationship.

My problem comes from the need to find all `MyEntity` using a where clause of `RelEntity.prop = mySearchKey`.

I'm not sure if this is down to me missing some documentation or not fully understanding how to structure this query withing Typeorm.

I believe my SQL statement for this would look something like:

    SELECT m.* FROM my_entity_table m 
    LEFT JOIN my_rel_pivot_table mrp ON mrp.my_entity_id = m.id 
    LEFT JOIN rel_entity_table r ON r.id = mrp.rel_entity_id
    WHERE r.id = {MY_VALUE_HERE}

However, I'm not too sure how to translate this into a Typeorm query.

I have tried:

    this.entityRepo.find({
        where: {
            rel: myValue
        }
    });

I have also tried:

    this.entityRepo.find({
        where: {
            rel: { id: myValue}
        }
    });

However, I received the following error:  
`Unknown column 'MyEntity.myEntityId' in 'where clause'`

Has anyone encountered this issue before, or have any idea how to solve this?

**Comment by pleerock** [comment]
You need to use QueryBuilder for such purpose:

```ts
const posts = await getManager().createQueryBuilder(Post, "post")
   .leftJoin("post.categories", "category", "category.someCondition = :someCondition", { someCondition })
   .getMany();
```

**Comment by colum-ferry** [comment]
Perfect, thank you for this.
It helped me look up the documentation and found the following:
http://typeorm.io/#/select-query-builder/inner-and-left-joins

Which in combination with what you have posted solves my problem.

Closing as resolved.
Thanks again!
Awesome work on this library.

**Comment by LogeswaranAnandan** [comment]
I have implemented multiple functionalities using repository.find(). Now due to a schema change I have to alter all the endpoints to fetch data based on a where condition of many to many relation.

```
this.entityRepo.find({
    where: {
        rel: { id: myValue}
    }
});
```

The Entity has many eager relationships, if I rewrite them using query builder then all the relations have to be inner joined manually which takes a lot of time to rework.

Do I have to rewrite all the methods using query builder? or is there a way to implement it using repository.find()?
