### ISSUE TITLE
Foreign key "Id" mapped to the type instead of a number

### ISSUE THREAD

**Issue by raime910** [typeorm/typeorm#2138]
**Issue type:**
[x] bug report

**Database system/driver:**
[x] `postgres`

**TypeORM version:** 
[x] `0.1.12` 

I created 2 tables in postgres - issues and projects. Each issue would come from a project so there's a project id foreign key that exist in the issues table. 
After running "typeorm-model-generator" instead of getting a projectId field in issues with type number, I get a projectId of type project.

@Entity('Issue')
export class Issue {

    @ManyToOne(type => Project, projectId => projectId.issues)
    @JoinColumn({ name: 'projectId'})
    projectId: Project; // this should be of type number and a new field called project should be created with type "project". 

    ...

}

**Comment by pleerock** [comment]
Please create issue in typeorm-model-generator repository.
