### ISSUE TITLE
Typeorm Upgrade

### ISSUE THREAD

**Issue by MarkMatute** [typeorm/typeorm#2139]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi do you have list of deprecated methods? I'm doing an upgrade.

**Comment by pleerock** [comment]
see changelog on the site.
