### ISSUE TITLE
[Question] count left joined table entries

### ISSUE THREAD

**Issue by D4edalus** [typeorm/typeorm#214]
assume we have two relations: problem and problem_check
each problem can be checked multiple times. the query below gets all problems and selects a count how often a problem was checked. this works fine with getRawMany()

```
@Table()
export class Problem {
    @PrimaryGeneratedColumn()
    id: number;

   numProblemChecks: number; // can i fill this automatically with a count ?
}
```

```
@Table()
export class ProblemCheck {
    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(type => Problem)
    problem: Problem;
}
```

```
query = problemRepository
                .createQueryBuilder("p")
                .addSelect("COUNT(pc.id) checks")
                .leftJoin("problem_check", "pc", "pc.problem=problem.id")
                .groupBy("ss.id")
                .getRawMany()
                .then(res => console.log(res))
                .catch(err => console.log(err));
```

how can i get the result of my counting into "numProblemChecks" ?

**Comment by D4edalus** [comment]
https://github.com/typeorm/typeorm/blob/master/test/functional/decorators/relation-count/query-builder-relation-count.ts

this needs to go to the sample section :) solved my problem

**Comment by pleerock** [comment]
You first example is correct. You just need to write value returned by getRawOne into class property. Note that @RelationCount is experimental decorator and isn't stable yet that's why it's not documented yet.

**Comment by pleerock** [comment]
You first example is correct. You just need to write value returned by getRawOne into class property. Note that @RelationCount is experimental decorator and isn't stable yet that's why it's not documented yet.

**Comment by stonecold123** [comment]
I can't even get `COUNT()` into the sql query with @RelationCount. Is this function completely disable at the moment?

**Comment by D4edalus** [comment]
https://github.com/typeorm/typeorm/blob/master/test/functional/decorators/relation-count/query-builder-relation-count.ts#L61

this works

**Comment by pleerock** [comment]
as I told this functionality is experimental thats why its not mentioned in docs. So something may not working yet, it will be implemented later once it gets more priority.

**Comment by timojokinen** [comment]
Is this feature implemented and tested now?

**Comment by pleerock** [comment]
no, this feature most probably will be dropped

**Comment by dwdewul** [comment]
Is there a particular reason that the @RelationCount will be dropped? I am using it currently in v0.2.5 and it saved me a lot of headache.

**Comment by pleerock** [comment]
lot of QueryBuilder features was experimental for a long time. relationid, relationcount are some of them. It will be dropped because: 

1. its not flexible approach and functionality is buggy and fixing bugs is extremely hard because of internal complexity
2. removal will lead to simplification and improve query builder maintenance
3. feature value is very low, you can easily do a separate query to do same, but costs are high (above)

**Comment by webmobiles** [comment]
it's really crazy, a  simple count from a left join table is very hard to do it, sometimes some addSelect simple give no column, but execute the sql internally, but no display values:

example:
no deal_count column is added on the result:

    const organizations = await getConnection()
      .getRepository(Organization)
      .createQueryBuilder('organization')
      .addSelect(
        '(SELECT COUNT(*) FROM deal WHERE deal.organization_id = organization.id) AS deal_count'
      )
      .where('organization.id=700')
      .orderBy('organization.id', 'DESC')
      .getMany();
