### ISSUE TITLE
When I use this @PrimaryGeneratedColumn("uuid"),  is this auto generated value universal in the world like the name?

### ISSUE THREAD

**Issue by JeongJun-Lee** [typeorm/typeorm#2141]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[*] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

Hello, I have two questions.
When I use this @PrimaryGeneratedColumn("uuid"), 
At first, is this auto generated value universal in the world like the name?
Second, can the uuid be generated by this decorator at Sqlite without any problem?

Thanks,
JJ

**Comment by pleerock** [comment]
its just regular generated uuid, see wiki on topic of uniqueness of uuid
