### ISSUE TITLE
Migration to 0.2.5 breaks MongoDB

### ISSUE THREAD

**Issue by MarkMatute** [typeorm/typeorm#2143]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, I previously upgraded to 0.2.5 from 0.1.17,
I run 2 connection 1 is mysql and mongodb,
on mongodb it says 'database name must be a string' even i added database: 'db_name' in the config.

```
[
  {
    "type": "mysql",
    "host": "127.0.0.1",
    "name": "main",
    "port": 3306,
    "username": "root",
    "password": "root",
    "database": "milo",
    "synchronize": true,
    "entities": [
      "\/Users\/markmatute\/Desktop\/Projects\/milo-backend\/dist\/config\/..\/entity\/**\/*"
    ],
    "logging": [
      "error",
      "query",
      "schema"
    ],
    "logger": "advanced-console"
  },
  null,
  {
    "type": "mongodb",
    "name": "mongo",
    "url": "mongodb:\/\/127.0.0.1:27017\/milo",
    "entities": [
      "\/Users\/markmatute\/Desktop\/Projects\/milo-backend\/dist\/config\/..\/entities-mongo\/**\/*"
    ],
    "logging": [
      "error",
      "query",
      "schema"
    ],
    "logger": "advanced-console",
    "ssl": false,
    "sslValidate": false
  }
]
```

**Comment by pleerock** [comment]
can you add a separate "database" option?

```ts
    "url": "mongodb:\/\/127.0.0.1:27017\/milo",
    "database": "milo"
```

**Comment by MarkMatute** [comment]
hi @pleerock i tried that, same result.

**Comment by pleerock** [comment]
then provide a minimal reproduction git repository please.

**Comment by MarkMatute** [comment]
ok will get back to you.

**Comment by alexdor** [comment]
@MarkMatute which mongo driver are you using?

I had the same issue using typeorm 0.2.5 and mongo driver 2.2, upgrading mongodb driver to 3.0.8 solved it for me.

**Comment by MarkMatute** [comment]
@alexdor, @pleerock   it did fix it. Haunted me all night.

I traced the error is triggered on the save method of the MongoManager? Using my given config above and trigger this code.

```
const mongoManager = getMongoManager(MONGO_NAME);
  const countryCities = new CountryCity();
  countryCities.type = 'COUNTRY_CITY';
  countryCities.countries = countries.map(c => {
    return { key: c[0], value: c[1], code: c[2], iso2: c[3] };
  });
  countryCities.countries_cities = countries_cities;
  await mongoManager.save(countryCities);
```

**Comment by pleerock** [comment]
so, did you fixed your issue?

**Comment by MarkMatute** [comment]
@pleerock yeah.

**Comment by n-lavrenko** [comment]
Guys, please, provide full example of using mongodb migration. Please!
Here is my code:
`import { getMongoManager, MigrationInterface, QueryRunner } from 'typeorm';
import { User } from '../../api/models/User';
import { env } from '../../env';


export class Init1538252088164 implements MigrationInterface {
    
    public async up(queryRunner: QueryRunner): Promise<any> {
        const mongoManager = getMongoManager(env.db.connectionName);
        const user = new User();
        user.username = 'niklavr';
        user.email = 'lavrenonik@gmail.com';
        
        user.firstName = 'Nikita';
        user.lastName = 'Lavrenko';
        
        user.password = 'abra';
        
        await mongoManager.save(user);
    }
    
    public async down(queryRunner: QueryRunner): Promise<any> {
        // some code here
    }
    
}

**and log in console is**:
`Error during migration run:
Error: Check schema queries are not supported by MongoDB driver.
    at MongoQueryRunner.<anonymous> (/projects/rolly/api/src/driver/mongodb/MongoQueryRunner.ts:498:15)
    at step (/projects/rolly/api/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:32:23)
    at Object.next (/projects/rolly/api/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:13:53)
    at /projects/rolly/api/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/projects/rolly/api/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:3:12)
    at MongoQueryRunner.hasTable (/projects/rolly/api/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:659:16)
    at MigrationExecutor.<anonymous> (/projects/rolly/api/src/migration/MigrationExecutor.ts:219:46)
    at step (/projects/rolly/api/node_modules/typeorm/migration/MigrationExecutor.js:32:23)
    at Object.next (/projects/rolly/api/node_modules/typeorm/migration/MigrationExecutor.js:13:53)`

**Comment by ruscon** [comment]
@n-lavrenko https://github.com/typeorm/typeorm/issues/2224
