### ISSUE TITLE
repository.update not updating deeper level data

### ISSUE THREAD

**Issue by younusmahmood** [typeorm/typeorm#2145]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [ ] `mysql`
    [X] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

Im trying to update an entity and have a dataset that looks something similar to this:

```
{
   "name":"Test 3",
   "timeGranularity":1,
   "clientId":1,
   "vars":[{...}]
}
```
And this is the code i'm running

```
await this.repository.update(id, updatedDto)) 
```
It updated the first 3 fine but when it hits the "vars" it doesn't update that. I tried using an insert but that didn't work either. Even tried another update that was like this:

```
await this.repository.update(id, {vars: updatedDto.vars}))
```
Which also didn't work

**Comment by younusmahmood** [comment]
Also forgot to mention the vars have a one to many relationship referencing different tables. I also have the ``onUpdate: "CASCADE"`` in my entity

**Comment by younusmahmood** [comment]
Got around it for now by deleting all the vars and then creating them again but still wondering about the update and if its supposed to update everything or not

**Comment by pleerock** [comment]
using repository.update you can only update a first-level data, e.g. only entity you are updating.
