### ISSUE TITLE
How to use postgres sql set?

### ISSUE THREAD

**Issue by Jimmysh** [typeorm/typeorm#2146]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

How to use https://www.postgresql.org/docs/10/static/sql-set.html

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Jimmysh** [comment]
The SET command changes run-time configuration parameters.

**Comment by pleerock** [comment]
use a raw query, e.g. `manager.query("SET ...")`

**Comment by Jimmysh** [comment]
@pleerock

I can use it in transaction.
```
    getManager()
      .transaction(async transactionalEntityManager => {
        transactionalEntityManager.query("set local aaa.b to '123';");
        return transactionalEntityManager.query(
          "select current_setting('aaa.b');"
        );
      })
      .then(d => {
        console.log(d); //[ { current_setting: '123' } ]
      });
```

but repository don't work;
```
Repository
      .query("set local aaa.b to '123';select current_setting('aaa.b');")
      .then(d => {
        console.log(d); // undefined
      });
```

I want to use it in repository and repository.createQueryBuilder()

**Comment by pleerock** [comment]
@Jimmysh probably thats expected

**Comment by jcamilo97** [comment]
@pleerock  Thanks! `manger.query("SET...")` it worked
I implemented a code to make it anything dynamic. But, there is other way for setting the update taking companyItems?
```typescript
 async updateCompany(comKey, companyItems) {
    let query:string = "UPDATE company SET";
    let iterator = Object.keys(companyItems);
    for (const key in companyItems) {    
        query += " "+key+`=$${iterator.indexOf(key)+1},`  
    }
    query = query.slice(0,-1)
    query += ` WHERE company.com_id ='${comKey}' `
    
    return await this.CompanyRepository.query(query, Object.values(companyItems))
      .then(response => { return '{"result":"update was success"}' })
      .catch(err => { return err.message })
  }
```

**Comment by pleerock** [comment]
@jcamilo97 I don't understand why do you use raw query instead of using `save` or `update` methods.

**Comment by jcamilo97** [comment]
@pleerock  because the method update does´not work.  here expose it. [issue](https://github.com/typeorm/typeorm/issues/2146#issuecomment-389266152)

**Comment by Jimmysh** [comment]
@jcamilo97 http://typeorm.io/#/update-query-builder

**Comment by pleerock** [comment]
@jcamilo97 first @Jimmysh 's issue is different, why do you post your message here without taking a look on this issue and confusing everybody? Second, you have issue because you use query builder the wrong way. Please checkout documentation and change your code.

@Jimmysh I think we can close this issue, please let me know if you want to add something.
