### ISSUE TITLE
Lazy load JoinColumn with multiple columns, name property is ignored for second reference column

### ISSUE THREAD

**Issue by jbpitts** [typeorm/typeorm#2147]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.5` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
export class User {
    @PrimaryGeneratedColumn('increment')
    public id: number;
    
    @Column()
    @Generated()
    public key: number;

    @IsNotEmpty()
    @Column({name: 'client_id'})
    public clientId: number;

    @IsNotEmpty()
    @Column({ name: 'updated_by'})
    public updatedById: number;

    @ManyToOne(type => User)
    @JoinColumn([{name: 'client_id', referencedColumnName: 'clientId'}, { name: 'updated_by', referencedColumnName: 'key'}])
    public updatedBy: Promise<User>;

    @UpdateDateColumn({ name: 'updated_at'})
    public updatedAt: Date;

    @VersionColumn()
    public epoch: number;
}
```

Call `find`, then call `await user.updatedBy` this will produce the following query

```sql
SELECT
  "updatedBy"."key"        AS "updatedBy_key",
  "updatedBy"."client_id"  AS "updatedBy_client_id",
  "updatedBy"."updated_by" AS "updatedBy_updated_by",
  "updatedBy"."updated_at" AS "updatedBy_updated_at",
  "updatedBy"."epoch"      AS "updatedBy_epoch",
  "updatedBy"."id"         AS "updatedBy_id"
FROM "user" "updatedBy" INNER JOIN "user" "User"
    ON "User"."client_id" = "updatedBy"."client_id" AND "User"."client_id" = "updatedBy"."key"
WHERE "User"."id" IN ($1)
```

**Notice, join clause** 

ON "User"."client_id" = "updatedBy"."client_id" AND **"User"."client_id"** = "updatedBy"."key" 

should be 

ON "User"."client_id" = "updatedBy"."client_id" AND **"User"."updated_by"** = "updatedBy"."key"

This works fine if I eager load, only fails for lazy load.

**Comment by pleerock** [comment]
Looks like a bug. Feel free to contribute!

**Comment by jbpitts** [comment]
Found the issue, working on fix.
