### ISSUE TITLE
Await save() issue using ActiveRecord

### ISSUE THREAD

**Issue by zappys** [typeorm/typeorm#2148]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello 

I have an issue with the following code.
I'm just checking if an Entity with an ID already exists in the database, if it doesn't then i want to create that Entity and persist it. 

Because i'm using await when saving the model into db i would expect my code to wait until that model was saved and then go to the next position in the array do the check if exists and so on. 

However, i get the following error which is unexpected because i check if a model with the same id already exists:

"UnhandledPromiseRejectionWarning: QueryFailedError: ER_DUP_ENTRY: Duplicate entry '1067251' for key 'PRIMARY'"

```ts
private async syncSpotResponse(response: TjSpotResponse[]){
    response.forEach(async spotResponse => { 

      const exists = await TjSpot.count({spot_id : spotResponse.spot_id});

      if (!exists){
        const spot = new TjSpot();
        spot.spot_id = spotResponse.spot_id;
        spot.spot_name = spotResponse.spot_name;
        await spot.save();
      }

    })
  }
```
Please note that the code for checking if the model already exists in the database works. The problem appears when i try to add hundreds of duplicated models that don't exist in the database. 

I think the execution does not wait until the model is saved into DB and by doing so when it checks the next position in array it tries to insert into db multiple models with the same id. 

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by zappys** [comment]
After some time i figured out the issue. You can't really use await in foreach with javascript. 
Solution : https://codeburst.io/javascript-async-await-with-foreach-b6ba62bbf404

**Comment by pleerock** [comment]
you can't isn't correct answer. You need to await your promises what you dont do. Solution:

```ts
await Promise.all(response.map(async spotResponse => { 

      const exists = await TjSpot.count({spot_id : spotResponse.spot_id});

      if (!exists){
        const spot = new TjSpot();
        spot.spot_id = spotResponse.spot_id;
        spot.spot_name = spotResponse.spot_name;
        await spot.save();
      }

    }))
```
