### ISSUE TITLE
Everything works but CLI can't find entity metadata?

### ISSUE THREAD

**Issue by KrisChambers** [typeorm/typeorm#2149]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

This is just a quick question about using CLI. I have everything setup in my configuration file. When I run it in my development environment it works fine. The production code works fine when I deploy it with a different ormconfig. But whenever I try to run a migration using the CLI I get an error telling me that typeorm can not find some metadata.

The migrations run fine when I do it programmatically using the connection object.

I thought this might of been because I removed reflect-metadata, but including it back in and rebuilding everything doesn't fix it.

I am at a loss as to where the problem could be.

**Comment by pleerock** [comment]
do you run cli from root of your project? Are paths in your ormconfig correct? I mean entities. Do you specify js files in there?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
