### ISSUE TITLE
Is it possible to perform multiple mysql raw queries?

### ISSUE THREAD

**Issue by quangpc** [typeorm/typeorm#2154]
**Issue type:**

[ x] question
[x ] bug report

**Database system/driver:**

[x ] `mssql`

**TypeORM version:**

[x ] `latest`

I tried to run this with typeorm but not success.
Could u guys show me how to use `SET @prev=0,@rownum=0` in below example:

```ts
return this.query(
            'SET @prev=0,@rownum=0;\
            SELECT user_id, survey_option_id FROM(\
              SELECT *, IF (\
                @prev <> survey_option_id,\
                @rownum := 1,\
                @rownum := @rownum+1\
              ) AS rank, @prev := survey_option_id, @rownum\
              FROM (\
                SELECT * FROM SurveyVotes WHERE survey_option_id IN (?) ORDER BY survey_option_id, created_at DESC\
              ) random_votes\
            ) vote_ranked\
            WHERE rank <= ?;',
            [optionIds, limit]
        );
```

**Comment by pleerock** [comment]
for more complex queries you'll probably need to do them directly using underlying [mssql driver](https://github.com/tediousjs/node-mssql). You can access driver properties and underlying stuff using `connection.driver`

**Comment by quangpc** [comment]
not sure I'm wrong or not. But I separated 2 queries into transaction and it's working now.
