### ISSUE TITLE
Can typeorm be used with sqljs without using custom webpack.config ?

### ISSUE THREAD

**Issue by redplane** [typeorm/typeorm#2156]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[x] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi, 

I'm new to `typeorm`. 
For now, I'm using `typeorm` with `sql.js`.

When I used driver: `sqljs`, it threw me an error :

**sql.js package has not been found installed. Try to install it: npm install sql.js --save**

I spent a day searching on internet and found [this repo](https://github.com/typeorm/ionic-example). After having cloned this project, I ran the code and it worked fine. But there is one thing notice : 
**The project uses a custom webpack config to load sql.js**

My question is : Can I use sql.js with `typeorm` without having to define a custom webpack config ? If it is possible then how ?

Thanks,

**Comment by redplane** [comment]
Finally, I've found a solution.

My solution is not to overwrite the default webpack configuration of ionic team, extend it instead.

This is my `webpack.config.js`

```
/*
* This configuration file is for extending ionic configuration file.
* */
const defaultConfiguration = require('../node_modules/@ionic/app-scripts/config/webpack.config');
const webpack = require('webpack');

let dev = defaultConfiguration.dev;
let prod = defaultConfiguration.prod;

//#region typeorm (dev)

dev.plugins.push(new webpack.NormalModuleReplacementPlugin(/typeorm$/, function (result) {
  result.request = result.request.replace(/typeorm/, "typeorm/browser");
}));

dev.plugins.push(
  new webpack.ProvidePlugin({
    'window.SQL': 'sql.js/js/sql.js'
  })
);

//#endregion

//#region typeorm (prod)

prod.plugins.push(new webpack.NormalModuleReplacementPlugin(/typeorm$/, function (result) {
  result.request = result.request.replace(/typeorm/, "typeorm/browser");
}));

//#endregion

console.log(defaultConfiguration.dev.plugins);
module.exports = defaultConfiguration;

```

Then I added this line to `package.json` file as the example did:

```
"configs": {
    "ionic_generate_source_map": true
  }
```

Perhaps, this is not very good solution, but at least, it helps me prevent overwriting default webpack configuration of angular cli .

**Comment by daniel-lang** [comment]
Sorry, for my late response.
You don't need to use the custom webpack config if you make sure `window.SQL` is defined and set to sql.js
This should be possible by simply loading `node_modules/sql.js/js/sql.js` before your application.

Conserning your webpack configuration, it looks like a good or ever better idea to extend the configure rather than completely copying it. Could you create a pr for you config over at [typeorm/ionic-example](https://github.com/typeorm/ionic-example)?

**Comment by redplane** [comment]
Ok. Thank you for your response.
I'll create PR for typeorm/ionic-example project :)
