### ISSUE TITLE
How to save image data to Cordova database?

### ISSUE THREAD

**Issue by mgreg89** [typeorm/typeorm#2157]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hello,
I have problems with correctly saving blob data (images) to my Cordova database. Inserting the data goes without any errors, but retrieving it again results in a string of the form "[object Object]" for each blob. Obtaining the type with `console.log(typeof items[0].frontgraphicpreview);` ends up with the output `string`. The blobs are valid images since they were correctly displayed on an HTML site before saving.
Here is how an image field is defined in my entity:
```typescript
@Column("blob",{ 
        nullable:true,
        name:"frontgraphic"
        })
    frontgraphic: Blob;
```

Is there a special mechanism for saving blob data into the database to circumvent the blob to string conversion, which seems is going on here?

Thanks in advance!

**Comment by pleerock** [comment]
I don't know how it is in cordova, but in sqlite it is simply `entity.frontgraphic = new Buffer("This is blob");`

**Comment by pleerock** [comment]
Probably you have to search a solution for your problem, I don't see typeorm issue in there.

**Comment by mgreg89** [comment]
After 2 weeks of searching the issue, I'm not 100% convinced that the problem is on my site. I have created a [ stackoverflow post](https://stackoverflow.com/questions/50590972/saving-images-as-blobs-with-typeorm-cordova-database). May be, I have described the problem a little bit better there.

**Comment by pleerock** [comment]
[Here](https://github.com/typeorm/typeorm/blob/8ef1695311dec4efa5ce9a81cf1621afc4611e10/test/functional/database-schema/column-types/sqlite/column-types-sqlite.ts#L44) we have a test that confirms buffer work for sqlite. Can you please create a PR with a failing test that shows the issue?

**Comment by mgreg89** [comment]
I finally managed to create a small repository [here ](https://github.com/mgreg89/cordova-sqlite-buffer-issue) to show the problem.
Please open the console after startup in order to better see the issue.

**Comment by vlapo** [comment]
Maybe problem with https://github.com/litehelpers/Cordova-sqlite-storage/issues/263 support in cordova plugin?

**Comment by pleerock** [comment]
@mgreg89 did you figure out solution for your issue?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
