### ISSUE TITLE
Search Engine Integration

### ISSUE THREAD

**Issue by leomongeg** [typeorm/typeorm#2159]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi folks,

I'm researching to use an ORM for a new project. But I need to be sure to have the possibility to easily index the DB to ElasticSearch, I can't see in the documentation that TypeORM support easy integration to ElasticSearch or similar search engines. Or maybe there is a third party plugin that allows that it would be great too.

Thanks in advance for the information.

Best regards,
Leonardo Monge García.

**Comment by dcworldwide** [comment]
It's very simple to just write code that bridges the two technologies. There is no es integration and I don't think there needs to be. I do it myself with little code using the official es npm package.

**Comment by dcworldwide** [comment]
It's very simple to just write code that bridges the two technologies. There is no es integration and I don't think there needs to be. I do it myself with little code using the official es npm package.

**Comment by pleerock** [comment]
yeap, agree with everything @dcworldwide said.
