### ISSUE TITLE
inject connection name to entity options automatically

### ISSUE THREAD

**Issue by wanganjun** [typeorm/typeorm#2160]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

entities.ts
```ts
import { Entity, EntityRepository, Repository } from 'typeorm';

// entity for Oracle table
@Entity('users')
export class OracleUser {}

@EntityRepository(OracleUser)
export class OracleUserRepository extends Repository<OracleUser> {}

// entity for MySQL table
@Entity('users')
export class MySQLUser {}

@EntityRepository(MySQLUser)
export class MySQLUserRepository extends Repository<MySQLUser> {}
```

ormconfig.ts
```ts
import { ConnectionOptions } from 'typeorm';
import { OracleUser, MySQLUser } from './entities.ts';

export const optinos: ConnectionOptions[] = [
    {
        name: 'defalut',
        type: 'oracle',
        username: process.env.ORACLE_USER,
        password: process.env.ORACLE_PASSWORD,
        url: process.env.ORACLE_CONNECT_STRING,
        entities: [
            OracleUser,
        ],
    },
    {
        name: 'mysql',
        type: 'mysql',
        host: process.env.MYSQL_HOST,
        username: process.env.MYSQL_USER,
        password: process.env.MYSQL_PASSWORD,
        database: process.env.MYSQL_DATABASE,
        entities: [
            MySQLUser
        ],
    },
];
```

crud.ts
```ts
import { OracleUserRepository, MySQLUserRepository } from './entities.ts';

const oracleRepo = getCustomRepository(OracleUserRepository);
// here, i have to pass connection name to function call, because
// MySQLUserRepository does not belong to default connection.
// I think we can make this better.
const mysqlRepo = getCustomRepository(MySQLUserRepository, 'mysql');
```

**feature description**
inject connection name to entity according to the orm configuration. 

For example, according to `ormconfig.ts`, `MySQLUser` belongs to connection named `mysql`.
If we  inject `{ connectionName: 'mysql' }` to entity options of `MySQLUser`, and somehow, function `getCustomRepository` can access `{ connectionName: 'mysql' }` , then we may get a custom repository from non-defalut connection like `const mysqlRepo = getCustomRepository(MySQLUserRepository);`

**Comment by pleerock** [comment]
no, we can't. Entities and repositories can be shared between multiple connections and in such cases connection is going to be messed up. You have to use connection name.
