### ISSUE TITLE
Not able to Pass Parameter for Stored Procedure

### ISSUE THREAD

**Issue by PawanKr2feb** [typeorm/typeorm#2161]
Below is my Stored Procedure.
```
USE test
GO
CREATE PROCEDURE UPDATE_TASK @description1 nvarchar(1750)
AS
SELECT * FROM task where description1 = @description1;
GO
```
The above Stored Procedure, i am trying to invoke using typeorm, but it fails.
```
export async function storedProcedure(request: Request, response: Response) {
    const manager = getManager();
    const results = await manager.query(`UPDATE_TASK`, [{ description1: 'pawan' }]);
    response.send(results);
}
```
and the Error is 
`QueryFailedError: Error: Procedure or function 'UPDATE_TASK' expects parameter '@description1', which was not supplied.`

**Comment by pleerock** [comment]
@quangpc I think you know how to do it, can you please help author?

**Comment by quangpc** [comment]
@pleerock @PawanKr2feb 
I'm not sure I'm right or not. I put them into transaction.
for example:
``` ts
const rawVotes = await getConnection().transaction(async transactionEntityManager => {
            await transactionEntityManager.query('SET @prev=0,@rownum=0;');
            return transactionEntityManager.query(
                'SELECT user_id, survey_option_id,\
                created_at, updated_at\
                FROM(\
                  SELECT *, IF (\
                    @prev <> survey_option_id,\
                    @rownum := 1,\
                    @rownum := @rownum+1\
                  ) AS rank, @prev := survey_option_id, @rownum\
                  FROM (\
                    SELECT * FROM SurveyVotes WHERE survey_option_id IN (?) ORDER BY survey_option_id, created_at DESC\
                  ) random_votes\
                ) vote\
                WHERE rank <= ?;',
                [optionIds, limit]
            );
        });
```

**Comment by quangpc** [comment]
Also, I think  my issue is not related to this issue since it uses parameter on query, not about `pass parameter to Procedure`

**Comment by quangpc** [comment]
@PawanKr2feb maybe u did in wrong way
As I read from this issue [https://github.com/typeorm/typeorm/issues/1207](url)
maybe u are missing ? operator:
like this
``` ts
let results = await this.database.getConnection().entityManager.query('CALL MyFunction(?)', [5086]));
```

**Comment by PawanKr2feb** [comment]
After adding ? operator i am getting below error.
`QueryFailedError: Error: Incorrect syntax near '?'.`

**Comment by quangpc** [comment]
@PawanKr2feb 
did u try:
```ts
const results = await manager.query(`CALL UPDATE_TASK(?)`, ['pawan']);
```

**Comment by PawanKr2feb** [comment]
Yes, Below is the code.
`export async function storedProcedure(request: Request, response: Response) {
    const manager = getManager();
    const results = await manager.query(`CALL UPDATE_TASK(?)`, ['pawan']);
    response.send(results);
}`

**Comment by pleerock** [comment]
Probably you'll need to use [underlying driver functionality](https://github.com/tediousjs/node-mssql).

**Comment by PawanKr2feb** [comment]
@pleerock  So you mean to say that we cannot achieve Passing Parameter to Stored Procedure using TypeOrm.

**Comment by pleerock** [comment]
No I mean its not typeorm responsibility since typeorm is an ORM, what you need is part of underlying driver, you can access it using typeorm.

**Comment by PawanKr2feb** [comment]
@pleerock  I might not agree with you on this, TyepOrm supports invocation of Stored Procedure and also query method signature (query(query: string, parameters?: any[]): Promise<any>) takes a Second Parameter so what is the use of that if we cannot pass a Parameter.

Thanks For what link you have shared but Could you please give a small Code snippet for above Procedure.

**Comment by pleerock** [comment]
I guess parameters of `query` are different from what you are asking for. Please research on now to use procedures on node-mssql site.

**Comment by PawanKr2feb** [comment]
@puttputt @lukaszklis @vaucouleur Any Help can you provide?

**Comment by pleerock** [comment]
why do you ping everybody in multiple issues? Consider googling and reading node-mssql documentation, READ AND TRY.

**Comment by Jana2018** [comment]
@PawanKr2feb Better to avoid TypeOrm and use some other Technology, if you are developing something for Production.. @pleerock As you mentioned that TypeOrm is a ORM so it won't work with Stored Procedure...If i go By your logic then Hibernate should also not have supported Stored Procedure...

**Comment by pleerock** [comment]
Jana2018 is a new user registered an hour ago, does the same styles messages and mistakes as OP. Really, better if you spent that time to read node-mssql documentation.

**Comment by Jana2018** [comment]
@pleerock ORM means it should support for all databases not for only ms SQL. Node ms SQL supports for only ms SQL server.

**Comment by pleerock** [comment]
ORM does not mean it. ORM is all about object relational mapping.

**Comment by NasrinAlphaOri** [comment]
For MSSQL Please use try below code,
await manager.query(`EXEC UPDATE_TASK`+ 'pawan');

If multiple params, use comma separator for every params.

**Comment by joaobsantos** [comment]
```    
const runProcedure = getConnection()
.getRepository(ENTITY_NAME)
.query(`PROCEDURE_NAME param1, param2, param3`)

console.log(runProcedure) 
```
If you awant variables for params:

``` 
const param1 = "param1"

const runProcedure = getConnection()
.getRepository(ENTITY_NAME)
.query(`PROCEDURE_NAME ${param1}, param2, param3`)

console.log(runProcedure) 
```
