### ISSUE TITLE
Why SelectQueryBuilder always add primary columns to selections?

### ISSUE THREAD

**Issue by astrohsy** [typeorm/typeorm#2165]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, I would like know why `select: false` on `PrimaryColumn` is not working.

Typeorm uses same Interface `ColumnOptions` for defining detailed options of the column, For both `Column` and `PrimaryColumn`. However, For `select` option, setting `select: false` when declaring `PrimaryColumn` is not working.  As a result of the code below in `buildEscapedEntityColumnSelects` of `SelectQueryBuilder.ts`.

```typescript
        const nonSelectedPrimaryColumns = this.expressionMap.queryEntity ? metadata.primaryColumns.filter(primaryColumn => columns.indexOf(primaryColumn) === -1) : [];
        const allColumns = [...columns, ...nonSelectedPrimaryColumns];

        return allColumns.map(column => {
                /* generating selection paths  */ 
        }
```

What should I do if I want to results without primary columns in it?
Plus, Adding the primary columns always to the selection list is on purpose?

**Comment by pleerock** [comment]
yes its by design. Primary columns are required for selection orm rely heavily on them
