### ISSUE TITLE
I saved a image in order which I want to save, but real saved result in the database exists in the opposite order.

### ISSUE THREAD

**Issue by JeongJun-Lee** [typeorm/typeorm#2169]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.3` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
...
// Delete
await shopImagesRepository.delete({ShopConfig_ShopId: currentShopConfig.ShopId});

photos.forEach(async photo => {
        // Insert
        let shopImage = new ShopImages();
        shopImage.ShopConfig_ShopId = currentShopConfig.ShopId;
        shopImage.image = photo;

        await shopImagesRepository.save(shopImage);
      });
```

I saved the image in order what I want to save, but real saved result in the database exists in the opposite order. How can it be existed in the database by the order what I saved? 

For your reference:

The id of ShopImages entity is auto-generated id.
All previous images in the database will be deleted before starting the image save.

**Comment by pleerock** [comment]
I guess code like this:

```ts
photos.forEach(async photo => {
```

are sources of your problems. Don't forget to await results, in this case you need to do `await Promise.all(photos.map(async photo => {`

**Comment by JeongJun-Lee** [comment]
But when I check the statement, await shopImagesRepository.save(shopImage); by break point in debugging. The value of shopImage parameter was the order I want to save. 
And when I changed the code like this as your recommendation, the result is same as before.

```
Promise.all(photos.map(async photo => {
        // Insert
        let shopImage = new ShopImages();

        shopImage.ShopConfig_onlineShopId = currentShopConfig.onlineShopId;
        shopImage.image = photo;

        await shopImagesRepository.save(shopImage);
      }));
```

**Comment by pleerock** [comment]
Did you put `await` before `Promise.all`? What you are saying is not possible. Can you please provide a PR with a failing test that proves issue you are talking about?

**Comment by JeongJun-Lee** [comment]
But when I stepped into the shopImageRepository.save(shopImage) function on Chrome debugging mode, I found the point to be in opposite order to the order I really sent  at shopImageRepository.save(shopImage). The point was at EntityPersistExecutor.prototype.execute = function () in EntityPersistExecutor.js. Is this process correct?

**Comment by JeongJun-Lee** [comment]
![image](https://user-images.githubusercontent.com/11474775/40298670-59c8009e-5cfd-11e8-9d16-df0c01c63b5b.png)

The order was right at Case 2 statement in at EntityPersistExecutor.prototype.execute = function (). But at case5, the order will be in the opposite direction.

**Comment by pleerock** [comment]
Promise.all makes your entities to be saved in parallel, if you want to save in a sequence then run your promises in a sequence

**Comment by JeongJun-Lee** [comment]
When I tried to control the promises in a sequence, but it looks like not possible because the EntityPersistExecutor.execute() function just returns the Promise of completion of the result which the save() function is executed, not Promise of the save() function itself.

**Comment by pleerock** [comment]
I think you have problems working with promises. If I got your issue correctly then you need to execute promises in a sequence. If you still think its an issue then create a PR with a failing test and see where problem is.

**Comment by JeongJun-Lee** [comment]
The reason is like your forecast. The hint is here, https://blog.lavrton.com/javascript-loops-how-to-handle-async-await-6252dd3c795. Thanks a lot. I'll close this.
