### ISSUE TITLE
Method to see if FB needs migration or possible pre-migration hook?

### ISSUE THREAD

**Issue by jmca** [typeorm/typeorm#2172]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm looking to see if there is a quick/convenient  way to find out if the connected DB needs to run a migration through the migration API (not cli). I need to perform some actions before `runMigrations()` is performed. I was hoping for something along the lines of `currentVersion()` or `latestVersion()` or `needsMigration()`. Maybe there is a pre-migration hook that is able to be tapped into?

**Comment by vlapo** [comment]
Hi @jmca. Maybe using `MigrationExecutor` and use `getMigrations` method to get all migrations and filter it like in code:
```typescript
// find all migrations that needs to be executed
const pendingMigrations = allMigrations.filter(migration => {
      // check if we already have executed migration
      const executedMigration = executedMigrations.find(executedMigration => executedMigration.name === migration.name);
      if (executedMigration)
          return false;
      return true;
});
```
But I think there is no official way to do that.

**Comment by pleerock** [comment]
no, there is no, and I don't think we need it.

You can control flow on your own - you have all methods you need in. Just create connection without running migrations or sync, do what you need and use connection.runMigrations after that.

Think we can close it.
