### ISSUE TITLE
Relation column name is transformed to small letter in a query

### ISSUE THREAD

**Issue by rafal-rudnicki** [typeorm/typeorm#2174]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.1.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have below entity:

```ts 
import { Entity, Column, PrimaryGeneratedColumn, OneToOne, JoinColumn, CreateDateColumn } from 'typeorm';
import { PageLanguage } from './page-language.entity';
import { Page } from './page.entity';

@Entity()
export class PageContent {

    @PrimaryGeneratedColumn() id: number;

    @Column({ length: 40}) name: string;

    @Column('text') content: string;

    @OneToOne(type => Page, page => page.id)
    @JoinColumn()
    page: Page;

    @OneToOne(type => PageLanguage, pageLanguage => pageLanguage.id)
    @JoinColumn()
    pageLanguage: PageLanguage;
}
 ```
which generates me table with column names: id, name, content, pageId, pageLanguageId. The problem is when i try to do a query like below:
```ts    
 async checkIfPageContentExistsAlready(pageId: number, pageLanguageId: number) {
        const result = this.pageContentRepository
            .createQueryBuilder('page_content')
            .where('page_content.pageId = :pageId AND page_content.pagelanguageId = :pageLanguageId', { pageId, pageLanguageId })
            .getOne();

        return result;
    } 
```

then i have that error:
> QueryFailedError: column page_content.pageid does not exist
    at new QueryFailedError (/var/www/project/src/error/QueryFailedError.ts:7:9)
   at Query.callback (/var/www/project/src/driver/postgres/PostgresQueryRunner.ts:216:26)
    at Query.handleError (/var/www/project/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/var/www/project/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.<anonymous> (/var/www/project/node_modules/pg/lib/connection.js:117:12)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)

So looks like typeorm wrongly generates query with small letters instead camel case. When i switch database to mysql then everything is ok, but unfortunatelly i have to use postgres. Could someone share with me his solution for that problem?

**Comment by pleerock** [comment]
you should use class property names instead of your database column names to let typeorm automatically escape your database column names:

```ts
.where('page_content.page = :pageId AND page_content.pageLanguage = :pageLanguageId', { pageId, pageLanguageId })
```

**Comment by pleerock** [comment]
I already did, read my last message.
