### ISSUE TITLE
Question: addSelect of leftJoins in SelectQueryBuilder

### ISSUE THREAD

**Issue by filipjnc** [typeorm/typeorm#2178]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**
[x] `postgres`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.5` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am trying to build the following query:
```
SELECT 
	"skill"."id", 
	"skill"."categoryId",
	"categoryTranslation"."name" AS "category",
FROM skill "skill"
LEFT JOIN skill_category_translation "categoryTranslation"
	ON "categoryTranslation"."categoryId" = "skill"."categoryId"
	AND "categoryTranslation"."langCode" = 'de_DE'
```
using SelectQueryBuilder:
```
async findAll(langCode: string): Promise<Skill[]> {
    return await this.repository.createQueryBuilder('skill')
      .select('skill.id')
      .addSelect('skill.categoryId')
      .addSelect('categoryTranslation.name', 'category')
      .leftJoin(
        SkillCategoryTranslation,
        'categoryTranslation',
        'categoryTranslation.categoryId = skill.categoryId AND categoryTranslation.langCode = :langCode',
        { langCode },
      )
      .getMany();
}
```
but I get this query:
```
SELECT 
    "skill"."id" AS "skill_id",
    "skill"."categoryId" AS "skill_categoryId",
    "categoryTranslation"."name" AS "category",
    "categoryTranslation"."categoryId" AS "categoryTranslation_categoryId", 
    "categoryTranslation"."langCode" AS "categoryTranslation_langCode"
FROM "skill" "skill"
LEFT JOIN "skill_category_translation" "categoryTranslation"
    ON "categoryTranslation"."categoryId" = "skill"."categoryId" 
    AND "categoryTranslation"."langCode" = $1
-- PARAMETERS: ["de_DE"]
```
which doesn't return any column from `categoryTranslation` and only the two from `skill`.

Any suggestions? I was looking into subQueries but it doesn't seem to deliver the simplicity I need. Thanks a lot!

**Comment by filipjnc** [comment]
**Update**
Even more strange, I tried the following:
```
async findAll(langCode: string): Promise<Skill[]> {
    return await this.repository.createQueryBuilder('skill')
      .select('skill.id, skill.categoryId, categoryTranslation.name AS "category"')
      .leftJoin(
        SkillCategoryTranslation,
        'categoryTranslation',
        'categoryTranslation.categoryId = skill.categoryId AND categoryTranslation.langCode = :langCode',
        { langCode },
      )
      .getMany();
}
```
and it generates the following query:
```
SELECT
    "skill"."id",
    "skill"."categoryId",
    "categoryTranslation"."name" AS "category"
FROM "skill" "skill"
LEFT JOIN "skill_category_translation" "categoryTranslation"
    ON "categoryTranslation"."categoryId" = "skill"."categoryId"
    AND "categoryTranslation"."langCode" = $1
-- PARAMETERS: ["de_DE"]
```
which returns an empty array in TypeORM.

When I run the same query in an SQL client, I get all the data correctly:
```
"id"	"categoryId"	"category"
"1107"	"1"	"Professional"
"1108"	"1"	"Professional"
"1109"	"1"	"Professional"
```

**Comment by pleerock** [comment]
try to change add select this way:

```ts
      .select(['skill.id', 'skill.categoryId', 'categoryTranslation.name'])
```

**Comment by filipjnc** [comment]
Thanks for the tip. Unfortunately it doesn't return the `categoryTranslation.name` column. I find it strange that the generated query (from logging: true) copy pasted in the SQL client does return the last column.

**Comment by pleerock** [comment]
Try to select `categoryTranslation.id` as well

**Comment by filipjnc** [comment]
@pleerock it didn't work. However I just tried `getRawMany()` instead of `getMany()` and I seem to get all the necessary columns, just in the unwanted format. 

May I guess that there is an issue in the SelectQueryBuilder code somewhere around this area?
```
        if (rawResults.length > 0) {

            // transform raw results into entities
            const rawRelationIdResults = await relationIdLoader.load(rawResults);
            const rawRelationCountResults = await relationCountLoader.load(rawResults);
            const transformer = new RawSqlResultsToEntityTransformer(this.expressionMap, this.connection.driver, rawRelationIdResults, rawRelationCountResults, this.queryRunner);
            entities = transformer.transform(rawResults, this.expressionMap.mainAlias!);

            // broadcast all "after load" events
            if (this.expressionMap.callListeners === true && this.expressionMap.mainAlias.hasMetadata) {
                const broadcastResult = new BroadcasterResult();
                queryRunner.broadcaster.broadcastLoadEventsForAll(broadcastResult, this.expressionMap.mainAlias.metadata, entities);
                if (broadcastResult.promises.length > 0) await Promise.all(broadcastResult.promises);
            }
        }
```

**Comment by pleerock** [comment]
okay, so try 0.3.0 (@next) I have changed the way find options work. If it still does not work for you then please contribute by creating a failing test and we'll try to fix issue together.

**Comment by mschuttt** [comment]
What's the status on this one? I currently have the same problem.. any workaround / fix?

**Comment by anodynos** [comment]
On a more general note, I have a similar problem: 

I add a virtual (i.e non existent field) such as `.addSelect(`'FOO'`, 'Table_alias_foo')` and although I can see it in the SQL and is returned properly when executed, it's not returned in the resulted object with `getMany()`. In my specific case it's a `count(*)` but `FOO` works well to demonstrate the issue.

The question is, can we include a custom field in the resulted object?

**Comment by qiwang97** [comment]
> Try to select `categoryTranslation.id` as well

but it not work now
