### ISSUE TITLE
MongoDB: database name must be a string

### ISSUE THREAD

**Issue by JeanDenisVIDOT** [typeorm/typeorm#2180]
**Issue type:**

[ * ] question
[ * ] bug report
[   ] feature request
[   ] documentation issue

**Database system/driver:**

[   ] `cordova`
[ * ] `mongodb`
[   ] `mssql`
[   ] `mysql` / `mariadb`
[   ] `oracle`
[   ] `postgres`
[   ] `sqlite`
[   ] `sqljs`
[   ] `react-native`

**TypeORM version:**

[ * ] `latest`
[   ] `@next`
[   ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Create a default project with command 
```
typeorm init --name test --database mongdb --express
cd test
yarn install
yarn start
```
You can see the following error : 
```
{ MongoError: database name must be a string
     at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
     at validateDatabaseName (/app/node_modules/mongodb/lib/db.js:1680:57)
     at new Db (/app/node_modules/mongodb/lib/db.js:156:3)
     at Db.db (/app/node_modules/mongodb/lib/db.js:1208:12)
     at MongoQueryRunner.getCollection (/app/src/driver/mongodb/MongoQueryRunner.ts:803:40)
     at MongoQueryRunner.<anonymous> (/app/src/driver/mongodb/MongoQueryRunner.ts:272:27)
     at step (/app/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:32:23)
     at Object.next (/app/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:13:53)
     at /app/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:7:71
     at new Promise (<anonymous>)
       name: 'MongoError',
       message: 'database name must be a string',
       driver: true }
```

My ormconfig.json file : 

```
{
   "type": "mongodb",
   "database": "test",
   "synchronize": true,
   "logging": false,
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}
```

**Comment by JeanDenisVIDOT** [comment]
Someone has the same problem ?

**Comment by pleerock** [comment]
Can you check what mongodb version do you have? (it shall be >3)

**Comment by alexbatis** [comment]
@pleerock upgrading mongodb dependency to at least version 3 solved this problem for me. when generating a project with the --express flag the default version (as specified in package.json) was "^2.2.31"

**Comment by MarkMatute** [comment]
use 3.0.8 mongofb

**Comment by glorious73** [comment]
I was able to fix the error by commenting out one of the lines in one of the files that caused the problem in the call stack.
**Fix:**

1. Navigate to _node_modules/mongodb/lib/db.js_
2. Go to the line that says:
 `validateDatabaseName(this.s.databaseName);`
3. Comment it out, like so:
![image](https://user-images.githubusercontent.com/44087932/50206577-e4be1000-037c-11e9-991e-5d338a2e977c.png)
4. Run again, and it should work.
![image](https://user-images.githubusercontent.com/44087932/50206666-2949ab80-037d-11e9-8c06-7639a6b6c8ff.png)

**Comment by pleerock** [comment]
Seems like easy fix, can somebody elaborate?
