### ISSUE TITLE
Changes to UpdateDateColumn precision needs to be detected

### ISSUE THREAD

**Issue by erangakm** [typeorm/typeorm#2184]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.1.18` 

**Steps to reproduce or a small repository showing the problem:**

I wanted to drop the timestamp precision from 6 to 2 for a column generated using ``@UpdateDateColumn()``.  Changing it to the following and generating a migration doesn't get picked up by typeorm.

``` 
@UpdateDateColumn({ type: "timestamp", precision: 2 })
public updated: Date;
```

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
