### ISSUE TITLE
Transaction Isolation Level Proposal

### ISSUE THREAD

**Issue by travtarr** [typeorm/typeorm#2185]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

It was mentioned in #233 to create an issue defining how one would see isolation levels being used.

I believe it would be as simple as an `isolationLevel` parameter on the transaction methods.  Alternatively an `options` parameter could be specified with the `isolationLevel` as a property of those options.

For the *EntityManager* an overloaded function would be needed in order to specify the options before the callback:
```ts
async transaction<T>(isolationLevel: IsolationLevel, runInTransaction: (entityManger: EntityManager) => Promise<T>): Promise<T>;
async transaction<T>(runInTransaction: (entityManger: EntityManager) => Promise<T>): Promise<T> {

  ...

  try {
    if (isolationLevel) {
      await queryRunner.startTransaction(isolationLevel);
    } else {
      await queryRunner.startTransaction();
    }
    const result = await runInTransaction(queryRunner.manager);
    await queryRunner.commitTransaction();
    return result;
    ...
}
```

For *PostgresQueryRunner*:
```ts
async startTransaction(isolationLevel?: IsolationLevel): Promise<void> {
  if (this.isTransactionActive)
      throw new TransactionAlreadyStartedError();

  this.isTransactionActive = true;
  await this.query("START TRANSACTION");
  if (isolationLevel) {
    await this.query("SET TRANSACTION ISOLATION LEVEL" + isolationLevel)
  }
}
```

Where the following are defined:
```ts
enum IsolationLevel {
  READ_UNCOMMITTED = 'READ UNCOMMITTED',
  READ_COMMITED = 'READ COMMITTED',
  REPEATABLE_READ = 'REPEATABLE READ',
  SERIALIZABLE = 'SERIALIZABLE'
}
```

Then to use it, it would be as simple as:
```ts
getManager().transaction(IsolationLevel.SERIALIZABLE, (manager) => {
  ...
});
```

References:
[Postgres](https://www.postgresql.org/docs/9.6/static/sql-set-transaction.html)
[MySQL](https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-isolation-levels.html)

**Comment by pleerock** [comment]
Thank you very much for your efforts! Did you check other databases support as well? We will need to implement this in every database. Also looks like an easy feature to implement, are you able to contribute?

**Comment by pleerock** [comment]
yeah probably so. Please add two overloads to transaction method: transaction(func) and transaction(isolation, func). Make sure to make isolation a string literal type. Thanks!

**Comment by rraina** [comment]
@pleerock -- when will 0.2.8 be published to npm? Would really like to use this feature...

**Comment by pleerock** [comment]
yes, end of this week. Im waiting for few other PRs to be merged before that

**Comment by azarus** [comment]
@pleerock was this published already? Really needed! Much appriciation for the project great job done.

**Comment by pleerock** [comment]
we have blocking issue that needs to be fixed first before we can release a new version, awaiting for that.

**Comment by azarus** [comment]
@pleerock if you need help could you please let me know, it would be a tons of help if it would be available by monday. and i'm available through whole sunday and could assist you in the release.
Thank you.

**Comment by deerares** [comment]
> we have blocking issue that needs to be fixed first before we can release a new version, awaiting for that.


Have any news about this version?

**Comment by nickarora** [comment]
Any news about this?  This feature is critical to our application...

**Comment by Kononnable** [comment]
0.2.8 was released few months ago, so this issue should be closed for some time :)
