### ISSUE TITLE
Throwing error when trying to insert a row with an existing id 

### ISSUE THREAD

**Issue by maxime1992** [typeorm/typeorm#2188]
**Issue type:**

[ ] question
[ ] bug report
[ x ] feature request
[ ] documentation issue

**Database system/driver:**

All?

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

*The following is a discussion to continue this issue: https://github.com/typeorm/typeorm/issues/691*

I first thought that the save method was throwing if the ID already existed but as pointed out by @kavinvin it does not.

I do not think that it is a "too specific requirement", I think that it's pretty important actually.

As the operations are asynchronous (promised based), if you do something like:
```
async register(user: User) {
  const userAlreadyExists = await this.findOneById(user.id);

  if (!userAlreadyExists) {
    const newUser = await this.userRepository.save(user);
  }
  
  // ...
}
```

What guarantee do you have that a user with the same ID will not be added right after the first await and right before the check? Then what? You just override him?

It should be a security coming form the database itself IMO.

**Comment by pleerock** [comment]
It is by **design** and one of the fundamental thing in typeorm and it won't be changed. In this design you don't care if your model exist in the database or not. You simply change it and save - and your model is being "sync up" automatically without making you worry if its insertion or updation. If you want to secure some logic in your code or simply getting know if your user is already in the database then you can simply check if `user.id` is defined or not. That's all.

**Comment by maxime1992** [comment]
> If you want to secure some logic in your code or simply getting know if your user is already in the database then you can simply check if user.id is defined or not. That's it.

That's where I disagree. As I said, it's promised based. So even if it's unlikely to happen, if you check that an ID is not available and in this case do something, between the 2 operations a row with that ID might have been added (promise so everything is asynchronous).

I know it's unlikely to happen, BUT unlikely doesn't mean it won't happen. I'm pretty sure that most of the database provide such a mechanism out of the box and I do not understand why it's by design and one of the fundamental. It's not for convenience to avoid a check, it's for security.

**Comment by pleerock** [comment]
There is no security point. If you want to check something then simply check before executing operation. You might disagree if you don't like something but hundred other people would agree. Again, its by design and is a really good and convenient feature.

**Comment by maxime1992** [comment]
> If you want to check something then simply check before executing operation

Typeorm is using Promises which is great.

But:

> simply check before executing operation

As it's asynchronous what guarantee do you have that after the check and before you execute an operation... Something hasn't been added that would make your check fail in the first place?

Nothing. 

I do love Typeorm but I do not understand why such a mechanism is not something that you want.

> is a really good and convenient feature

I'm not saying to change an existing feature like `save`. That'd be a huge breaking change.

But adding a new method, for example `saveSafely` or whatever would be a nice addition.

**Comment by GitStorageOne** [comment]
Agree, save should has additional optional parameter, `throwErrorIfExist`.
If we want be sure that record does not exist and only in this case perform any operations, 
there is only one way to do it granular - multiple queries in single transaction.
Option to just disable check and get DBMS duplicate key error indeed would be good in some cases.

**Comment by GitStorageOne** [comment]
Looks like there is option.
We can use EntityManager `insert` and `update` methods.

**Comment by percy507** [comment]
> SQL is a declarative form of programming that is not considered an error unless it is a syntax error, insufficient permissions, and locks cannot be executed at the database level.
>
> SQL 是一种声明式的编程方式，除非是语法错误、权限不足、在数据库的层面有锁无法执行，否则都不认为是错误。

**Just write your own code to judge if the request success by checking query result.**

```ts
async (ctx) => {
  const result = await getRepository(Article)
    .createQueryBuilder()
    .update()
    .set({ ...ctx.request.body, id: null })
    .where('id = :id', { id: ctx.request.body.id })
    .execute();

  // judge response by query result
  if (result && result.affected === 1) {
    ctx.res.success(null);
  } else {
    ctx.res.fail(BUSINESS_CODE.UNKNOWN_ERROR, 'Article not exists');
  }
}
```

**Comment by KMJ-007** [comment]
i have explained the issue and solution in gist 

https://gist.github.com/KMJ-007/1e58788f31f772bb422e5ebc8195f2a4,

i need some guidance to complete the PR

> Agree, save should have additional optional parameter, `allowedOperations: ["insert", "update"]`. If we want be sure that record does not exist and only in this case perform insert, there is only one way to do it safe - multiple queries in single transaction. Option to just disable checks and get DBMS error indeed would be good in some cases. What about [ACID](https://en.wikipedia.org/wiki/ACID_(computer_science))?
> 
> Also, almost every time, when building REST API, "POST" operation should insert data only if object key does not exist, otherwise - return http status 409. And "PUT" operation should update resource only if exist otherwise return http status 404.
