### ISSUE TITLE
How to increment/decrement in place for sqlite wirh QueryBuilder like on this StackOverflow answer?

### ISSUE THREAD

**Issue by Oroneki** [typeorm/typeorm#2189]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ X] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello, I am trying to create this SQL with query builder I saw on this StackOverflow answer:
https://stackoverflow.com/questions/744289/sqlite-increase-value-by-a-certain-number
```sql
UPDATE Products SET Price = Price + 50 WHERE ProductID = 1
```

How do I do that since the **set** function of the query builder only accepts an object: 

```ts
await getConnection()
    .createQueryBuilder()
    .update(User)
    .set({ age: 35, lastName: "Saw" })
    .where("id = :id", { id: 1 })
    .execute();
```

I tried something like:
```ts
...
.set({ someValue: `someValue + ${34 + 1}` })
```
but that saved the string "_someValue + 35_" into my sqlite database.

**Comment by pleerock** [comment]
```ts
await getConnection()
    .createQueryBuilder()
    .update(User)
    .set({ age: () => "age + 1", lastName: "Saw" })
    .where("id = :id", { id: 1 })
    .execute();
```

` () => ""` syntax allows you to execute custom sql expressions.

**Comment by Oroneki** [comment]
Thanks and congratulations for the great work! I am having lots of fun with typeorm.
