### ISSUE TITLE
An error in methods "find" and the like. It does not work for NULL sampling

### ISSUE THREAD

**Issue by Fokir** [typeorm/typeorm#219]
There is one unpleasant feature in the use of the method "find". When all the elements of the sample with the field set to "NULL" is requested.
`... WHERE user.email = null`
 This request does not work in MySQL, but works request.
`... WHERE user.email IS null`

**Comment by pleerock** [comment]
can you provide a code snippet how did you get this code generated? via `FindOptions`?

**Comment by Fokir** [comment]
Now I have done so
`let user = await User.__repository.createQueryBuilder('user').where('user.uplay = :uplay', {uplay: uplay})
            .andWhere('user.email is null').andWhere('user.password is null').getOne();`
It has previously been
`let user = await User.__repository.find({uplay: uplay, email: null, password: null})`

**Comment by pleerock** [comment]
fixed, will be released in `0.0.8-alpha.2`
