### ISSUE TITLE
TableForeignKeyOptions missing params for deferrable

### ISSUE THREAD

**Issue by jkl1337** [typeorm/typeorm#2191]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`TableForeignKeyOptions` is missing params to allow setting deferrable foreign key constraints. Not sure what the best interface for this is. sqlalchemy uses a bool and a free form string/expression for "initially".

**Comment by pleerock** [comment]
What database are you using? TableForeignKeyOptions tries to cover general foreign key functionality that any database has. Looks like deferrable foreign key constraints you are talking about is some database-specific? (I haven't used them). 

If some very-specific functionality is missing you can always call a `query` method and execute any SQL query you would like to.

**Comment by jkl1337** [comment]
Deferrable constraints are feature ID F721 of SQL-99. They are supported by a number of common engines, and also not supported by some notable engines.

https://www.postgresql.org/docs/9.0/static/sql-createtable.html
https://oracle-base.com/articles/8i/constraint-checking-updates
https://www.sqlite.org/foreignkeys.html#fk_deferred
I don't have the time to look at SQL Server, but as of 2012 it did not support them. Mysql unsurprisingly does not support them. Mariadb also does not.

Here is how sqlalchemy addresses it:
http://docs.sqlalchemy.org/en/latest/core/constraints.html#sqlalchemy.schema.ForeignKeyConstraint.__init__

Deferred FK constraints are one of those features that when you need them it is hard not to use them because the alternative is manageable but quite annoying.

I am cognizant of the issues of defining general functionality. But, the lowest common denominator is quite low. MySQL does not support CHECK constraints, Mariadb only does very recently. Both of these are provided explicitly in TypeORM. Similarly for partial indices. So there are arguments either way for this.

https://stackoverflow.com/questions/955671/dealing-with-circular-reference-when-entering-data-in-sql
https://github.com/cockroachdb/cockroach/issues/9897

**Comment by pleerock** [comment]
Okay, got you. We'll investigate how to add this feature to typeorm in the future. Meanwhile, feel free to contribute. For now you'll have to use raw sql queries.

**Comment by JanPeter** [comment]
Is there any update on this?

**Comment by Kononnable** [comment]
PR with feature implementation was merged, will be released by end of the week in `typeorm@0.2.17`

**Comment by gustavomick** [comment]
@Kononnable noticed this was closed but not added for sqlite, any reason for not adding sqlite? thanks
