### ISSUE TITLE
How to enable sync schema and not drop columns?

### ISSUE THREAD

**Issue by wy193777** [typeorm/typeorm#2196]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When using SQL Server, I use a not supported column type: rowversion. I guess typeorm has no way to define this column type. So I have a SQL script add this type if they are not been added. But when initialize typeorm, this column will be dropped if set sync to true.

Is there an option about not drop columns but only add columns when initializing?

**Comment by pleerock** [comment]
no, there is no. You can disable synchronization for the whole entity by setting `@Entity({ synchronization: false })`. Otherwise you can contribute and add rowversion support into typeorm.

**Comment by wy193777** [comment]
Created pull request #2198. Still working in progress.

**Comment by wy193777** [comment]
Is the new version with #2198 been published to NVM? Got error when try to use rowversion type today.

**Comment by pleerock** [comment]
no, I don't think so. I'll publish a new version these weekends.

**Comment by wy193777** [comment]
How can I install typeorm using NPM from GitHub? Always got this error:
```npm ERR! path ./node_modules/typeorm/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod './node_modules/typeorm/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-06-02T01_08_08_395Z-debug.log
```

**Comment by apiel** [comment]
Any chance to deactivate synchronization for a specific column?

**Comment by ArturoGamRod** [comment]
it is very easy to get this wrong and/or make a mistake. synchronization should not drop columns - **especially with existing  data** -  its a deal breaker guys.

**Comment by skliarovartem** [comment]
Yes, it is strange to delete columns with some data there. Usually sync works to add new columns only, and even don't change type

**Comment by Huge-Puppy** [comment]
I'm having this problem as well. Don't want to make custom migrations as I'm still in development, but I also don't want to keep remaking all of my data every time I sync.
