### ISSUE TITLE
Eager loading relations on tree entity 

### ISSUE THREAD

**Issue by xujif** [typeorm/typeorm#2197]
**Issue type:**

[ ] question
[+] bug report
[+] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[+] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[+] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
here is my entity:
```
class Status{
  @ManyToOne(type => User, {
        eager: true,
        nullable: false
    })
    @JoinColumn({ name: "userId" })
    user: User

   /**
     * 被转发的状态
     * 
     * @type {Status}
     * @memberof Status
     */
    @ManyToOne(type => Status, {
        eager: false,
        nullable: true
    })
    @JoinColumn({ name: "retweetedId" })
    retweeted: Status
}
```

1.  "Maximum call stack size exceeded" will throw when retweeted eager set to be true.  #1573 , Its no 
      way to resolve it but use join in querybuild instead.
2.   "table name "Status_user" specified more than once"  will throw when set user's eager to be true,
     I found the query sql join users table twice and both alias to Status_user,sometimes It's correct ,but why not to be more smart, like alias to a random string?

**Comment by mike-zenith** [comment]
Have you tried using the special Tree* decorators? 
https://github.com/typeorm/typeorm/blob/master/docs/tree-entities.md

I build up a forum-post tree based on closure table and its neat!

**Comment by xujif** [comment]
thanks
