### ISSUE TITLE
ColumnOptions not exported properly

### ISSUE THREAD

**Issue by TylerDev6** [typeorm/typeorm#22]
I'm getting TS compile errors when providing object literals for ColumnOptions.

{ generated: true } 

"Object literal may only specify known properties and 'generated' does not exist on ColumnOptions"

**Comment by pleerock** [comment]
it should not be possible. can you provide a complete code sample and specify a typescript version?

**Comment by TylerDev6** [comment]
It's likely an issue with my type definitions.... has this project been pushed to DT?

**Comment by TylerDev6** [comment]
I can see the type definitions in the node modules folder. I'm trying a few other configurations but it'd be really handy to get this on DT.

**Comment by TylerDev6** [comment]
I'm using typescript 1.9.0-dev, could be causing the issue as I'm getting numerous errors when compiling it.

**Comment by pleerock** [comment]
can you upgrade to latest typescript@next (2.1.x) and check?

**Comment by TylerDev6** [comment]
ok

**Comment by TylerDev6** [comment]
updating to @next didn't resolve it, I'm still getting the same error.

**Comment by TylerDev6** [comment]
Hmm, ok it seems that the interfaces are not exported in the index.d.ts file. the tsc compile doesn't change what I'm getting is an IDE warning.

**Comment by TylerDev6** [comment]
https://github.com/Microsoft/TypeScript/issues/3194

This resolves it

changing the interface exports from 

export interface Foo

to

interface Foo

export default Foo

**Comment by TylerDev6** [comment]
would you mind if I forked the project to do this?

**Comment by pleerock** [comment]
im sure its a problem on your side. provide a minimal representation of a problem in a separate repository, i'll checkout it and check. but this problem sounds like something wrong with your tooling

**Comment by TylerDev6** [comment]
how are your d.ts files being generated?

**Comment by TylerDev6** [comment]
I'm running latest typescript, latest tslint, when I install typeorm and try to use ColumnOptions I get errors every time because it's not exported.

**Comment by TylerDev6** [comment]
if I edit your ColumnOptions.d.ts file to make the export change above, I no longer get the errors

**Comment by pleerock** [comment]
hmm `ColumnOptions.d.ts` does contain `export` keyword. Don't you have it?

**Comment by pleerock** [comment]
> Microsoft/TypeScript#3194

the issue you have send isn't related, since its talking about `export default`, ColumnOptions does not have `default` keyword.

**Comment by pleerock** [comment]
what version of typeorm you are using?

**Comment by TylerDev6** [comment]
0.0.2-alpha.62, the version I get with a vanilla npm install typeorm.

That is what I had to do to fix the error. change "export interface" to inferface Foo, export default Foo

**Comment by pleerock** [comment]
maybe the issue in your IDE? are you sure your IDE runs latest typescript version? did you try to compile project without ide? if no, then open your project directory in a command line, do `tsc -v`, to make sure you are running latest typescript and run `tsc` to compile the project

**Comment by TylerDev6** [comment]
including the interfaces in your index.d.ts would also be a solution to the issue I'm experiencing.

**Comment by TylerDev6** [comment]
Yes, project compiles in typescript. IDE is latest webstorm. I am now just suggesting this as a recommendation to improve the type definitions. I'm sure I won't be the only one who comes across this problem.

**Comment by pleerock** [comment]
yes now I saw that they are missing in index.ts, but they should actually. Strange that I don't get same issue as you. I'll add them

**Comment by TylerDev6** [comment]
Ok, I've managed to work through those issues now. There were some local configs causing problems. Thanks for all your help.

**Comment by TylerDev6** [comment]
I'm still not able to get your code running.... now I seem to have an error with the default...

typeorm/connection/ConnectionManager.js:86
    get(name = "default") {
             ^

SyntaxError: Unexpected token =


I also can't seem to tsc compile any of your samples...

**Comment by TylerDev6** [comment]
Ah, having to upgrade Node to get support for default params.

**Comment by TylerDev6** [comment]
Alright, I'm properly configured. I'll close this.
