### ISSUE TITLE
How to do a `Group_CONCAT`?

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#220]
What is the typeorm way of using `GROUP_CONCAT,CONCAT_WS` in the query. Suppose this is the raw query I want to achieve: 
````
SELECT model_id,GROUP_CONCAT(CONCAT_WS('||', name,id) SEPARATOR '@@') AS variants" 
FROM variant
GROUP BY model_id
LIMIT 0,20
````
Basically,I want to fetch each model's variants' ids and names. I hardcode the group_concat part with `addSelect()` , but is there any other way of doing it?
Can I use self left join to get results like this:
````
[
  {
    "model_id": 3,
    "variants": [
      {
        "name": "AAA",
        "id": 2
      },
      {
        "name": "NNN",
        "id": 5
      }
    ]
  }
]
````
Table Model
````
@Table()
export class Variant{
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    model_id: number;

    @Column()
    name:string
}
````
Code:
````
let itemRepository = connection.getRepository(Variant);
let item = await ItemRepository
                .createQueryBuilder("variant")
                .addSelect("GROUP_CONCAT(CONCAT_WS('||', variant.name,variant.id) SEPARATOR '@@') AS variants")
                .groupBy("variant.model_id")
                .setFirstResult(0)
                .setMaxResults(20)
                .getManyAndCount();
````

**Comment by pleerock** [comment]
you can add custom selects and get models back to you. You have either to load model separately, then load data you need and use `getRawOne` or `getRawMany` methods and set your data to class property manually.
