### ISSUE TITLE
How to properly create a select query when using a (custom) junction table

### ISSUE THREAD

**Issue by nitzantomer** [typeorm/typeorm#2201]
This is a *question* regarding the proper way to select a record based on properties from both models (who share the junction table).

For example, let's say we have the following two models:
```
@Entity({ name: "users" })
class User extends BaseEntity {
	@PrimaryColumn()
	public id: string;
	
	@OneToMany(type => RecordContext, context => context.user)
	public contexts: RecordContext[];

	// more columns
}

@Entity({ name: "records" })
class Record extends BaseEntity {
	@PrimaryColumn()
	public id: string;
	
	@OneToMany(type => RecordContext, context => context.record)
	public contexts: RecordContext[];

	// more columns
}
```

And this junction table:
```
@Entity({ name: "record_contexts" })
class RecordContext extends BaseEntity {
	@ManyToOne(type => Record, record => record.contexts, { primary: true })
	public readonly order: Order;

	@ManyToOne(type => User, user => user.contexts, { primary: true })
	public readonly user: User;

	@Column()
	public readonly role: string;

	@Column("simple-json")
	public readonly meta: any;
}
```

I want to be able to get the joined records for a specific `record_id` **and** `user_id`, and I'm stuck here:
```
Record.createQueryBuilder("record")
	.innerJoinAndSelect("record.contexts", "context")
	.where("record.id = :recordId", { recordId })
	.andWhere("context.user_id = :userId", { userId })
```
My problem is how to reference the user part the in the last line, since `context.user` is `User` and I don't have the `user_id` column.  
I'm using TypeORM version `0.1.12`.

Thanks.

**Comment by nitzantomer** [comment]
Thanks @pleerock 

I went with your suggestion, but it ends up creating duplicity in the table:
```
Column   |       Type        | Collation | Nullable |
---------+-------------------+-----------+----------+
order_id | character varying |           | not null |
user_id  | character varying |           | not null |
role     | character varying |           | not null |
meta     | text              |           | not null |
orderId  | character varying |           |          |
userId   | character varying |           |          |
```

Is there a way to remove the created `orderId` and `userId` fields?

**Comment by pleerock** [comment]
typeorm does not create in a following naming convention: "order_id" columns by default, how do you have them created? Do you use some custom column naming? If yes then you need to change it or change property names to orderId to order_id as well.

**Comment by nitzantomer** [comment]
Well, this is my entity:
@Entity({ name: "record_contexts" })
class RecordContext extends BaseEntity {

	@PrimaryColumn({ name: "order_id" })
	orderId: number;

	@PrimaryColumn({ name: "user_id" })
	userId: number;

	@ManyToOne(type => Record, record => record.contexts)
	public readonly order: Order;

	@ManyToOne(type => User, user => user.contexts)
	public readonly user: User;

	@Column()
	public readonly role: string;

	@Column("simple-json")
	public readonly meta: any;
}

We just prefer to have this style of naming (underscore, and not camel case) in the database.

**Comment by nitzantomer** [comment]
@pleerock 

Other than the ability to control how the fields are named (without creating duplicity), I'm having a problem where the fetched data from the junction table is missing.

Doing something like:
```
Record.createQueryBuilder("record")
	.innerJoinAndSelect("record.contexts", "context")
	.where("record.id = :recordId", { recordId })
	.andWhere("context.userId = :userId", { userId })
```

Finds and returns the record instance, but the property `record.contexts` is null, even though the values do return from the query (I printed the query and then ran it on the db directly).  
Any idea why?

**Comment by pleerock** [comment]
Okay, update to 0.2.x and create a PR with a failing test and lets take on issue deeper.

**Comment by nitzantomer** [comment]
@pleerock 
I created a new PR: https://github.com/typeorm/typeorm/pull/2222
It has two issues, the first is the naming issue I mentioned in this thread, but the 2nd one is different than what I asked about here (it was a problem on my end).

**Comment by nitzantomer** [comment]
@pleerock 
Any updates regarding this? 
Thanks.

**Comment by pleerock** [comment]
I put answers in PR

**Comment by Amirm73** [comment]
Is it possible to query on typeORM junction tables?
 want to do a low complexity query on a many to many relations (todos-tags) using this query on todo_tags_tag junction table of typeORM with tagId and todoId FKs:
```
@Resolver(Todo)
export class TodoTagResolver {
  @FieldResolver(() => [Tag], { nullable: true })
  async Tags(@Root() todo: Todo): Promise<Tag[] | undefined> {
    const result = await getRepository(Tag).query(
      `SELECT * FROM tag
     INNER JOIN  todo_tags_tag ON tag.id=todo_tags_tag.tagId
     WHERE todoId=$1`,
      [todo.id]
    );
    console.log(result);
    return result;
  }
}
```
the respond is : `"column todo_tags_tag.tagid does not exist",`
