### ISSUE TITLE
Does typeorm cli allow native ts schema generation? 

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#2204]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm looking at the documentation for http://typeorm.io/#/using-ormconfig - the cli seems to only work with transpiled .js files. 

IE: if i use the following config i get a typeorm schema:log failure

dev.env
```
TYPEORM_ENTITIES=src/app/dtos/*.ts
TYPEORM_MIGRATIONS=src/database/migrations/*.ts
TYPEORM_SUBSCRIBERS=src/database/subscribers/*.ts

TYPEORM_ENTITIES_DIR=src/app/dtos
TYPEORM_MIGRATIONS_DIR=src/database/migrations
TYPEORM_SUBSCRIBERS_DIR=src/database/subscribers
```

IE: if i use the following config i get a typeorm schema:log works

prod.env
```
TYPEORM_ENTITIES=dist/src/app/dtos/*.js
TYPEORM_MIGRATIONS=dist/src/database/migrations/*.js
TYPEORM_SUBSCRIBERS=dist/src/database/subscribers/*.js

TYPEORM_ENTITIES_DIR=dist/src/app/dtos
TYPEORM_MIGRATIONS_DIR=dist/src/database/migrations
TYPEORM_SUBSCRIBERS_DIR=dist/src/database/subscribers
```

Is there support for those of us who only run ts-node when running on developer machines?

**Comment by pleerock** [comment]
not sure if I completely understood point of this issue. One of your env use ts and you say it does not work and another your example use js and you say it does not work as well? Btw if you use ts-node you need to run typeorm schema:log using ts-node, do you do that?

**Comment by rightisleft** [comment]
Clarification: the js approach works, the ts version does not. I've updated the original comment.

Question: How do i run the typeorm cli using ts-node ?

**Comment by pleerock** [comment]
`ts-node ./node_modules/.bin/typeorm`
