### ISSUE TITLE
Relation lost when field is lazy.

### ISSUE THREAD

**Issue by yuluyi** [typeorm/typeorm#2206]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Relation is lost when I set the "one side " of the Many-to-One relation to lazy.

**Steps to reproduce or a small repository showing the problem:**

```ts
class Child {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    name: string

    @ManyToOne(type => Parent, parent => parent.children)
    @Column()
    parent: Promise<Parent>
}


class Parent {
    @PrimaryGeneratedColumn()
    id: number

    @OneToMany(type => Child, child => child.parent)
    @Column()
    children: Promise<Child[]>
}

const parent = await parentRepository.findOne(1)
const children = [{name: 'a'}, {name: 'b'}]

queryRunner.manager.insert(Child, children.map(child => Child.create({
    name: child.name,
    parent: Promise.resolve(parent)
})))
```
but if i don't use Promise on the "One side", the relation is persisted in the database correctly.

**Comment by yuluyi** [comment]
@pleerock why must save? Also, I think bulk insert is very common. Why isn't insert working here?

**Comment by pleerock** [comment]
because if you want orm functionality completely to work you must always use `save` method. If you want to execute simple `insert into ... ` then you can use `insert` method. Functionality you are talking about is a bit advanced and is not covered by insert method.

Btw as usual, I strongly don't recommend to use lazy relations until you really think its a good fit for your app since lazy relations can be source of multiple unexpected issues.

Also, this:

```ts

    @OneToMany(type => Child, child => child.parent)
    @Column()
    children: Promise<Child[]>
```

is wrong. You shall not have `@Column` in there.

**Comment by yuluyi** [comment]
Thank you @pleerock. Another question. Is update also not recommended?  Should I also use save instead?

**Comment by yuluyi** [comment]
I've tried save. If the relation is lazy. Save also doesn't work. 
Btw, I think lazy relation is quite useful. 

Say I have a function
```ts
function doSomethingWithParent(parent: Parent) {
    let children = await parent.children
    let doSomethingWithChildren(children)
    saveChildren(children)
}
```

**Comment by mike-zenith** [comment]
It you set up cascade option properly, it should work. 

But sometimes you might find issues like this:
https://github.com/typeorm/typeorm/issues/2129#issuecomment-388806019

**Comment by Joo-hyun-Kang** [comment]
Adding solution:

- **`Using ORM . operator `**

@Entity()
export class MentoringLogs {
  @PrimaryGeneratedColumn('uuid')
  id: string;

	//変数の省略

  @ManyToOne(() => Mentors, (Mentors) => Mentors.mentoringLogs)
  mentors: Promise<Mentors>;

  @ManyToOne(() => Cadets, (Cadets) => Cadets.mentoringLogs)
  cadets: Promise<Cadets>;

  @OneToOne(() => Reports, (Reports) => Reports.mentoringLogs)
  reports: Promise<Reports>;
}


```jsx

       const keywordCategories = new KeywordCategories();
        
        keywordCategories.categories = Promise.resolve(category);
        keywordCategories.keywords = Promise.resolve(keyword);

        return await keywordCategoriesRepository.save(keywordCategories);
```
