### ISSUE TITLE
- when batch insert with relations, throw this error :

### ISSUE THREAD

**Issue by babepet** [typeorm/typeorm#2208]
- when batch insert with relations, throw this error :
Error: Uncaught (in promise): QueryFailedError: Expression tree is too large (maximum depth 1000)

data like this, arr.length > 10 , res.length more than 700 
res:[ { id:1, name : "ello", arr : [ ]},
        { id:1, name : "ello", arr : [ ]},
         . . .
 ]

How to improve performance when insert data？

**Comment by babepet** [comment]
@puttputt @solon

**Comment by pleerock** [comment]
Provide more information. Show the query being executed. Did you try to run same query using database? Looks like issue in your query, not orm.

**Comment by pleerock** [comment]
Looks like author is too lazy to find a fix for his problem. Closing.
