### ISSUE TITLE
Database Compatibility with Lower Version of MariaDB

### ISSUE THREAD

**Issue by naveensky** [typeorm/typeorm#2209]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi, I would like to understand if I can target a lower version of MariaDB than the latest version. Does typeorm correctly identified the MariaDB version and generates appropriate queries. I am getting following error when running my project on MariaDB 5.5.X 

`QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '6), updatedAt datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), deletedAt d' at line 1`

**Comment by pleerock** [comment]
I guess issue in `CURRENT_TIMESTAMP(6)`. You can change it by changing your UpdateColumn usage to:

```ts
@UpdateColumn({ default: () => "CURRENT_TIMESTAMP" })
updatedAt;
```

**Comment by naveensky** [comment]
@pleerock - Thanks for this. I was able to resolve the issue by upgrading the DB to latest version of MariaDB. For now, we can close this issue.
