### ISSUE TITLE
Postgres synchronisation unnecessarily drops column with data type "float"

### ISSUE THREAD

**Issue by mattb-prg** [typeorm/typeorm#2210]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.5`
Postgres v10

**Steps to reproduce or a small repository showing the problem:**

Create an Entity with a column of data type float:

```ts
@Entity()
export class FloatTest{

  @PrimaryColumn()
  id: number

  @Column('float')
  some_num: number
}
 ```
Add some data to the table:

```ts
const con = await createConnection({
    ...,
    synchronize: true,
    logging: true
  })
await con.manager.save(FloatTest, { id: 0, sum_num: 10.51 })
 ```
On the initial run this all works fine -- run it again however and you'll get an error like the following: `column "some_num" contains null values`. With logging enabled the "sum_num" column is clearly being dropped and rebuilt.

I think this error is due to Postgres using `double precision` as `float` internally(see https://www.postgresql.org/docs/10/static/datatype-numeric.html section 8.1.3). This seems to be the case when the column check SQL is run: `SELECT *, "udt_name"::"regtype" AS "regtype" FROM "information_schema"."columns"...`. The "regtype" for the float data type returns double precision.

The solution, I think is to add an additional check in the `normalizeType` function in `PostgresDriver.ts` like so: 
```ts
else if (column.type === "float") {
   return "double precision";
}
```

Thanks for the great ORM!

**Comment by serranoarevalo** [comment]
@mattb-prg any work around for this?

**Comment by mattb-prg** [comment]
@serranoarevalo Yep, just use the `double precision` type instead of `float` when defining your column.

**Comment by serranoarevalo** [comment]
@mattb-prg  Thanks!!

**Comment by scttcper** [comment]
confirmed this is still happening on the latest version, thanks for workaround

**Comment by Alex0007** [comment]
Confirming this bug on `typeorm@next` version

**Comment by basicBrogrammer** [comment]
I'm thinking about turning off `synchronize`. it seems kind of weird for postgres. I'm coming from an ActiveRecord background so I'm use to "migrate everything" .... I'm new to typeorm. So the Entities and Migrations are totally separated right ?

**Comment by Mattwmaster58** [comment]
This looks like it would be a trivial bug to fix, what are we waiting for?

**Comment by Kononnable** [comment]
@Mattwmaster58 
I don't know. If it is so trivial why don't you make a PR for it?

**Comment by pleerock** [comment]
@Mattwmaster58 more trivial bugfixes please! 😆 Thanks, this issue is fixed now.
