### ISSUE TITLE
Support for FoundationDB

### ISSUE THREAD

**Issue by xeoneux** [typeorm/typeorm#2211]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Will there be support for FoundationDB in near future with TypeORM?

**Comment by pleerock** [comment]
We don't have such plans. But, as always, you can contribute :)

**Comment by pleerock** [comment]
As it was mentioned multiple times we don't have in plans to implement new drivers in a near future. If you want to contribute - please feel free! To keep issues cleaner lets close this one and continue discussion in #4
