### ISSUE TITLE
Question - Joining tables with many-to-many

### ISSUE THREAD

**Issue by localnet** [typeorm/typeorm#2212]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```typescript
@Entity("question")
export default class QuestionEntity {
    @PrimaryGeneratedColumn()
    public id!: number;

    @Column({ type: "varchar" })
    public statement!: string;

    @ManyToMany(() => ResponseEntity, response => response.questions)
    public responses!: ResponseEntity[];
}
```

```typescript
@Entity("response")
export default class ResponseEntity {
    @PrimaryGeneratedColumn()
    public id!: number;

    @Column({ type: "varchar" })
    public statement!: string;

    @ManyToMany(() => QuestionEntity) @JoinTable({ name: "question_response" })
    public questions!: QuestionEntity[];
}
```

```typescript
export default class QuestionResolver {
    private questionRepository: Repository<QuestionEntity>;

    public constructor() {
        this.questionRepository = getRepository(QuestionEntity);
    }

    public async getQuestion(id: number): Promise<QuestionEntity | undefined> {
        return await this.questionRepository
            .createQueryBuilder("question")
            .leftJoinAndSelect("question.responses", "response")
            .where("question.id = :id", { id: id })
            .getOne();
    }
}
```

```typescript
const question = new QuestionResolver();

await question.getQuestion(1);
```

I think it is correct according with the [documentation](http://typeorm.io/#/many-to-many-relations) but I get the next error: 

> TypeError: Cannot read property 'tablePath' of undefined

Can somebody help me, I can't see what I am doing wrong

**Comment by mike-zenith** [comment]
If your staring Entity is QuestionEntity, you should set up the @JoinTable decorator there. 
Could you give it a try?

**Comment by localnet** [comment]
You are right, thanks you so much.

**Comment by mregula** [comment]
This is not necessarily true. Please check out the documentation:

> Note, the inverse relation does not have a @JoinTable. @JoinTable must be only on one side of the relation. Bi-directional relations allow you to join relations from both sides using QueryBuilder...

But you are right, without JoinTable decorator it deosn't work which is very confusing becasue documentations says differently. What is more I noticed some issues when JoinTable decorator is on both sides when you inserting or deleteing new rows.

**Comment by GustawOhler** [comment]
Yeah, I agree with @mregula. In my case when I try to join table in similar way like in the question it shows me error: 

> group_user.userid column doesn't exist

What's the problem?
