### ISSUE TITLE
Question: How would you go about getting a value for a field from a cache

### ISSUE THREAD

**Issue by iamgmd** [typeorm/typeorm#2213]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am building a GraphQL server and having a hard time trying to work out how I can return a getter that is looked up from a cache. Suppose I have this getter for a field in my entity class:

```
@Entity("accountbase")
export class Account extends BaseEntity {
  
  @Column("int") accountcategorycode: number;
  @Column({ select: false })
  get accountcategorycode_name(): string {
    return this.accountcategorycode !== null
      ? this.accountcategorycode.toString()
      : "";
  }
```

I need to be able to return a value looked up in a cache but I have no idea how I am going to get the cache context injected here, even with a constructor, how do I pass the cache context to it if I have a resolver like so:

```
  const connection = await createTypeOrmConnection(req);
      const records = await connection
        .getRepository(Account)
        .createQueryBuilder("accountbase")
        .leftJoinAndSelect("accountbase.primarycontactid_ref", "accountbase.primarycontactid_ref")
        .leftJoinAndSelect("accountbase.t4a_secondarycontactid_ref", "accountbase.t4a_secondarycontactid_ref")
        .getMany()
        .catch(error => { throw error as Error; });
        await connection.close();
      return records;
```

I am pretty new to TypeORM/TypeScript but I would of thought this use-case is pretty common-place, just haven't found any example of how to go about it so thanks in advance if you could help a fellow out.

**Comment by pleerock** [comment]
```ts

  @Column("int") accountcategorycode: number;
  @Column({ select: false })
  get accountcategorycode_name(): string {
    return this.accountcategorycode !== null
      ? this.accountcategorycode.toString()
      : "";
  }
```

use decorators on class properties, not methods or getter/setters. Probably its better to implement what you want with a better approach.

**Comment by iamgmd** [comment]
Hi @pleerock, I struggled with this somewhat and it is mostly to do with my lack of knowledge. 

From this code below in my GraphQL resolver, I am creating a typeORM connection passing in Express.Request and a Redis client that has been passed down through the GraphQL context.

```
    contact_all: async (_, {}, { req, redis }) => {
      const connection = await createTypeOrmConnection(req, redis);
      const records = await connection
        .getRepository(Contact)
        .createQueryBuilder("contactbase")
        .getMany()
        .catch(error => { throw error as Error; });
        await connection.close();
      return records;
    },
```

I am not sure if it is the .getRespository(Contact) or .createQueryBuilder("contactbase") that is responsible for instantiating the Contact objects but it is at this point where I need the Express.Request and Redis client to be accessible so that I can use it in the getter.

If anyone has any examples of decorators to do this I would really appreciate it.

**Comment by pleerock** [comment]
@iamgmd sorry but I don't understand your request. You need to use redis client or request in the getter? In entity getter? If yes then don't do it its a bad practice. Handle logic in your resolver code.
