### ISSUE TITLE
Documentation: QueryRunner

### ISSUE THREAD

**Issue by qumaujean** [typeorm/typeorm#2214]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi, first of all thanks for your great work on Typeorm !

I am using transactions with the Querry Runner in my project.
I realized after 8 instantiations of it, my Graphql server is crashing.
You just need to release it: `runner.release()` when you don't need it anymore to fix it, but that info is missing in typeorm's doc.

Thank you again for that amazing orm !

**Comment by pleerock** [comment]
Yes, you are right! Can you please contribute and add that to documentation in the place where you think its understandable to be?

**Comment by filipjnc** [comment]
Where is the main documentation for Query Runner? So far I found none on typeorm.io and one a TBD version on github. Thanks!

**Comment by pleerock** [comment]
@filipjnc http://typeorm.io/#/migrations/using-migration-api-to-write-migrations

BTW @qumaujean you should only release query runner if you manually created it. So I don't think this shall be in migration documentation since there are no examples how to create a query runner.
