### ISSUE TITLE
char / character in both MySQL and SQLite

### ISSUE THREAD

**Issue by pmoleri** [typeorm/typeorm#2217]
**Issue type:**

[x] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[x] `mysql` / `mariadb`
[x] `sqlite`

**TypeORM version:**

[x] `latest`
[x] `0.2.6`

**Steps to reproduce or a small repository showing the problem:**

I want to have a fixed length char in both MySQL and SQLite.

If I use `type: 'character'` I get:
> DataTypeNotSupportedError: Data type "character" in "Entity.column" is not supported by "mysql" database

If I use `type: 'char'` I get:
> Data type "char" in "Entity.column" is not supported by "sqlite" database.

I checked other issues and I found that this was addressed in issue #343 by adding a `fixedLength` option, but then was removed in [commit #f1c566f2efc206170533171110aed0980cd1360b](https://github.com/typeorm/typeorm/commit/f1c566f2efc206170533171110aed0980cd1360b), when database specific types were introduced.

Is there any way I can get around this?

If not, Wouldn't it make sense to have a some generic types like `char` that can be mapped in every database? Or re-introduce `String + fixedLength` type?

Whichever option, I would be glad to contribute if someone approves.

**Comment by chriszrc** [comment]
I agree that this should be better addressed in the docs, I was under the impression that I could have a column type of "varchar" and it would "just work" in any of the supported databases, isn't that why I'm using an ORM after all?

To address sqlite specifically though, it would seem this is a typeorm error here, because "char" is a perfectly valid column type name in sqlite:

https://www.sqlite.org/datatype3.html#determination_of_column_affinity

To extend the compatibility to postgres, I would appear that "character varying" should also be added to the acceptable types for sqlite here:

https://typeorm.io/#/entities/column-types-for-sqlite--cordova--react-native--expo

**Comment by chriszrc** [comment]
Not sure if this issue was addressed or not, but for anyone wondering, "varchar" works just fine between sqlite and postgres (and I assume mysql):

https://github.com/typeorm/typeorm/blob/39057ca08774283743974c278b6b54aa26d977de/src/driver/types/ColumnTypes.ts#L63

**Comment by pmoleri** [comment]
Yes I think that `varchar` is pretty well supported. The original issue is about using char/character fixedLength types and that mapping correctly to different DBMS, using varchar would be just a workaround using a different type.

I see that the issue was tagged with [`comp: entity schemas`](https://github.com/typeorm/typeorm/blob/master/docs/separating-entity-definition.md) so I assume that the authors think that support for multiple DBMS should be achieved by different _schemas_ and _migrations_ for the different DBMS and loading them conditionally, while maintaining a single Entity definition. Personally, I don't like this approach.

**Comment by chriszrc** [comment]
Is there a difference between varchar(128) and character fixedLength? I'm using this:

```
  @Column("varchar",{
        nullable:false,
        length:128,
        name:"setting"
 })
setting:string;
```

**Comment by pmoleri** [comment]
It makes a difference to the DBMS.
- `varchar` 128: _I'm storing a variable length string up to 128 chars_ 
- `character` 128: _I'm always storing 128 chars_.

The DBMS optimizes these 2 in different ways.

**Comment by chriszrc** [comment]
@pmoleri Ah, thanks for the clarification, I rarely use the later type, seems postgres has spoiled me:

"Different from other database systems, in PostgreSQL, there is no performance difference among three character types. In most situation, you should use text or varchar, and varchar(n) if you want PostgreSQL to check for the length limit."

http://www.postgresqltutorial.com/postgresql-char-varchar-text/
