### ISSUE TITLE
Datetime stored incorrectly in postgresql

### ISSUE THREAD

**Issue by jwclark** [typeorm/typeorm#2220]
**Issue type:**

[x ] bug report

**Database system/driver:**

[ x] `postgres`

**TypeORM version:**

[ ] `0.2.6` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The entity and test call below result in a timestamp in server time(rather than UTC) and without timezone information. This behavior exists as of pull request #1717 as far as I can tell. 

@entity()
export class DateTest {

@PrimaryGeneratedColumn("uuid")
public id?: string;

@Column()
public date?: Date;
}

testRepository.save({date: new Date()});

A potentially dangerous result of this bug is that two different servers in different timezones, but accessing the same database, could read the same entry and construct different timestamps(not just differences in timezone).

The comment [here](https://github.com/typeorm/typeorm/pull/1717#issuecomment-379262037) by @chriskalmar is not the actual behavior for postgres. As shown in the example above, new Date() is *not* stored as UTC.

**Comment by chriskalmar** [comment]
@jwclark I think you are constructing a column type without timezone, thus you don't get your timestamps stored in UTC.

From the postgres docs (https://www.postgresql.org/docs/9.6/static/datatype-datetime.html):
```
The SQL standard requires that writing just timestamp 
be equivalent to timestamp without time zone, 
and PostgreSQL honors that behavior.
```

So in order to overcome this, try to change the data type like this:
```
@Column("timestamp with time zone")
```

**Comment by jwclark** [comment]
While I would not deploy a production workload to a non-UTC server, it seems a bit fragile to me if changing the timezone of the server can cause these types of bugs.

As @chriskalmar and @filipjnc suggest, I've switched to 'timestamp with time zone' column type. Perhaps that should be the default for Date columns?

**Comment by pleerock** [comment]
> While I would not deploy a production workload to a non-UTC server, it seems a bit fragile to me if changing the timezone of the server can cause these types of bugs.

dates and timezones is a fragile system itself. Dates are always complex and you simply need to know how to handle each case and you'll understand why it works this way. ` if changing the timezone of the server` - you should not, that's the whole point. If you change it you'll have a fragile system to deal with. Why? Because its an issue with dates, not this or another tooling.

> As @chriskalmar and @filipjnc suggest, I've switched to 'timestamp with time zone' column type. Perhaps that should be the default for Date columns?

no.

**Comment by bengotow** [comment]
Hey folks, just wanted to chime in. I think the "put your server in UTC" solution is fine (and the server should already be running in UTC), but this causes all sorts of problems during local development. If you have postgres and node running on your machine and the timezone of both is the SAME, you can safely use `timezonetz` to fix this problem, but the default `timestamp` used by postgres will produce the wrong results.

**Comment by Shaft-pycord1** [comment]
> [@jwclark](https://github.com/jwclark) I think you are constructing a column type without timezone, thus you don't get your timestamps stored in UTC.
> 
> From the postgres docs (https://www.postgresql.org/docs/9.6/static/datatype-datetime.html):
> 
> ```
> The SQL standard requires that writing just timestamp 
> be equivalent to timestamp without time zone, 
> and PostgreSQL honors that behavior.
> ```
> 
> So in order to overcome this, try to change the data type like this:
> 
> ```
> @Column("timestamp with time zone")
> ```





https://stackdev.space/questions/exploring-the-mechanisms-of-storing-values-in-various-data-types-within-the-c-programming-language
