### ISSUE TITLE
Updating a fields with IN quarries.

### ISSUE THREAD

**Issue by PavanBahuguni** [typeorm/typeorm#2223]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I want to update a set of entries having a status as 'aa' or 'bb' or 'cc' (this set is dynamic). So I'm trying to use IN comparator with array to achieve this as so.
```
this.createQueryBuilder()
.update()
.set(updateObject)
.where('nonPrimaryColumn in :values', {values: ['aa', 'bb', 'cc']})
.execute();
```
But the above code errors out as it tries to run wrong sql query as follows.
`UPDATE sample_table SET testColumn = $1 WHERE nonPrimaryColumn IN $2 -- PARAMETERS: [4,['aa', 'bb', 'cc']]`

it should have been

`UPDATE sample_table SET testColumn = $1 WHERE nonPrimaryColumn IN ('aa', 'bb', 'cc') -- PARAMETERS: [4]`

Only option i see is to write raw SQL query and run it. Is there a way around to achieve what I'm looking for?

**Comment by PavanBahuguni** [comment]
Following code worked for me.
```
    import {In} from 'typeorm';
    this.update({
       nonPrimaryColumn: In(['aa', 'bb', 'cc'])
    }, updateObject);
```

**Comment by mike-zenith** [comment]
You have to add parentheses around the parameter when using `IN`:
```
this.createQueryBuilder()
    .update()
    .set(updateObject)
    .where('nonPrimaryColumn in (:values)', {values: ['aa', 'bb', 'cc']})
    .execute();
```

**Comment by pleerock** [comment]
@mike-zenith thanks for the answer.
