### ISSUE TITLE
Cannot run migration with mongodb database

### ISSUE THREAD

**Issue by rvitorsantos** [typeorm/typeorm#2224]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.6` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm trying to run migrations in a mongodb database, but I keep getting the Error `Error: Check schema queries are not supported by MongoDB driver`, even with no migrations to run. I believe that this error occurs when typeorm tries to create the migrations table. 

My question is: Migrations is supposed to work with mongodb database driver?

**Comment by pleerock** [comment]
they should work, looks like there is a bug. Please feel free to contribute!

**Comment by pvsong** [comment]
Same issue
