### ISSUE TITLE
how to use OR

### ISSUE THREAD

**Issue by keyiis** [typeorm/typeorm#2228]
**Issue type:**

[ *] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[* ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[* ] `0.x.x` (or put your version here)

I didn't find OR in document,i won't user querybuilder.
ex:
`select * from user where id=1 or name='test'`

**Comment by filipjnc** [comment]
Please search thoroughly the documentation before posting. This is a fairly basic functionality, well described in both the docs here on github and on the docs webpage:
http://typeorm.io/#/select-query-builder/adding-where-expression

**Comment by keyiis** [comment]
@filipjnc Thks reply,i need save query condition to json,like `find({or:[{id:1},{name:'test'}]})`
![qq 20180601122452](https://user-images.githubusercontent.com/7766085/40821145-b137cbe6-6597-11e8-954f-885a55986ab5.png)

**Comment by pleerock** [comment]
we are planning to extend find options functionality and 0.3.0 and you can even try it in `@next` but right now in 0.2.x you have to use query builder.
