### ISSUE TITLE
Migration File Not Generated Until Schema Drop

### ISSUE THREAD

**Issue by sslgeorge** [typeorm/typeorm#2230]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.2` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
 Create a  new package, create an entity and run typeorm migration:generate -n NameOfEntity, it tells me that no changes in databse schema werere found.
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
please create a reproduction git repo.

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
