### ISSUE TITLE
3rd level Nesting issue, problem retrieving the data

### ISSUE THREAD

**Issue by libritium** [typeorm/typeorm#2231]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

```typescript
@Entity()
export class User {

    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    name: string;

    @Column(type => Book)
    books: Book[];
}
```

```typescript
export class Book{
   
    @Column()
    id: ObjectID;

    @Column(type => Page)// <========= no exceptions and doesn't work
    // @Column('array') // work but as plain array | json
    pages: Page[];
}
```

```typescript
export class Page{
	
    @Column()
    id: ObjectID;

    @Column()
    number: number;

}
```

Using NestJS with typeorm, when requesting the data of pages of a certain book, the returned array is empty of items even though there are certainly items in the DB.
When adding a new item (page) to the array and saving it, It overwrites the pages array in the DB with and puts only the newly added item there, removing anything that was there previously.

**Comment by rustamwin** [comment]
@libritium Can you check latest version? #3574 should fix this issue

**Comment by WretchedDade** [comment]
Just wanted to say. I was getting an error retrieving documents with 3rd level nested objects and no longer get that after updating to 0.2.17.

**Comment by Kononnable** [comment]
Closing as no response from the author.
