### ISSUE TITLE
join naming to underscore

### ISSUE THREAD

**Issue by asifashraf** [typeorm/typeorm#2232]
**Issue type:**
[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have created a base/abstract class entity and two children classes 

```ts
export abstract class t_basic_entity {

    @orm.PrimaryGeneratedColumn()
    id: number;

    @orm.Index()
    @orm.Column({default: () => "uuid_generate_v1mc()"})
    id2: string;


    //{default: () => "CURRENT_DATE"}
    @orm.Index()
    @orm.CreateDateColumn()
    @orm.Column()
    createdAt: Date;

    @orm.Index()
    @orm.UpdateDateColumn()
    //default: () => "CURRENT_DATE"
    @orm.Column({nullable: true})
    updated_at: Date;

    @orm.VersionColumn()
    version: number;

    @orm.Index()
    @orm.Column({nullable: true})
    removed_at: Date;
   
}




export class t_user extends t_basic_entity {


    @orm.Column({ unique: true })
    @orm.Index()
    email: string;

    @orm.Column()
    @orm.Index()
    password: string;

    //@orm.OneToOne(type => t_user_detail, userDetail => userDetail.the_user)
    //user_detail: t_user_detail;

    @orm.OneToMany(type => t_user_image, userImage => userImage.user) 
    user_images?: t_user_image[];

    @orm.Column("simple-array", {nullable: true})
    titles?: string[];

    @orm.Column("simple-json", {nullable: true})
    profile?: { name: string, nickname: string };

    @orm.Column({nullable: false})
    @orm.Generated("uuid")
    uuid: string;

    //@orm.OneToOne(type => Setting, setting => setting.user)
    //setting: Setting;

    @orm.Column(type => t_embedded_name)
    name: t_embedded_name;
}

export class t_user_image extends t_basic_entity {


    @orm.Column()
    url: string;

    @orm.ManyToOne(type => t_user, user => user.user_images)
    user: t_user;

    @orm.ManyToMany(type => t_image_album, imageAlbum => imageAlbum.user_images)
    image_albums: t_image_album[];

}
```

Please focus on underscore naming I am using everywhere. All db is fine but lets focus on t_user_image class's ManyToOne Member

```ts
@orm.ManyToOne(type => t_user, user => user.user_images)
    user: t_user;
```

The resulted Foreign key column is "userId" in t_user_image table in database. I want to make this to underscore "user_id" but I cannot find a way how to do this. I checked parameters of ManyToOne object but there is no specification of column name or anything else like normal @Column attributes.

**Comment by pleerock** [comment]
There is a @JoinTable for many-to-many and @JoinColumn for one-to-one owner and many-to-one relations which accept name argument where you can specify join column name.

**Comment by asifashraf** [comment]
@pleerock  yes that worked for me , thanks 

To help others: The joincolumn will take two arguments column and Reference Column name; enough to fix the discussed issue

**Comment by spedy** [comment]
Args:
```
target: object.constructor,
propertyName: propertyName,
name: options.name,
referencedColumnName: options.referencedColumnName
```

located at: https://github.com/typeorm/typeorm/blob/master/src/decorator/relations/JoinColumn.ts
