### ISSUE TITLE
Apply .limit()  or take() to joined relation

### ISSUE THREAD

**Issue by starvinmelon** [typeorm/typeorm#2234]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello! I need to do something like this:  
```
this.someRepo.creaateQueryBuilder('mainAlias')
.innerJoinAndSelect('mainAlias.relationName', 'relationName', 'somecondition', { param })
// and here, i need to apply limit to each relationName result for example to limit it by 6: 
// [
// 	{
// 		id: 1,
// 		relationName: [
// 			// here goes max 6 entries
// 		]
// 	},
// 	{
// 		id: 2,
// 		relationName: [
// 			// here goes max 6 entries
// 		]
// 	},
// 	{
// 		id: 3,
// 		relationName: [
// 			// here goes max 6 entries
// 		]
// 	},
// ]
```
Is there way to do such thing? Thanks.

**Comment by pleerock** [comment]
You need to execute separate queries using query builder.

**Comment by atonamy** [comment]
@hazytheee you can achieve this using this [approach](https://github.com/typeorm/typeorm/issues/4255)  is hacking but it works, just don't forget initialise mysql vars

**Comment by JosipReh** [comment]
@atonamy  can you give example for the scenario mentioned above?
How to limit joined relation on N records but to still be able to limit the main query on M results
