### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by cesarve77** [typeorm/typeorm#2236]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

````
git clone https://github.com/cesarve77/typeorm-bug
cd typeorm-bug
npm i
npm run sync
````

## I get this error when I'm tryng to sync the database

```
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (/Users/cesar/Documents/www/test/rewrite/src/entities/Family/Parent.ts:7:9)
    at /Users/cesar/Documents/www/test/rewrite/src/entities/Family/Parent.ts:6:29
    at Object.<anonymous> (/Users/cesar/Documents/www/test/rewrite/src/entities/Family/Parent.ts:6:1)
    at Module._compile (module.js:649:30)
    at Module.m._compile (/Users/cesar/Documents/www/test/rewrite/node_modules/ts-node/src/index.ts:403:23)
    at Module._extensions..js (module.js:660:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/cesar/Documents/www/test/rewrite/node_modules/ts-node/src/index.ts:406:12)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)

```
## These are my entities:

```javascript

//entites/Family/Family.js
import {Entity, PrimaryGeneratedColumn, Column, OneToMany} from "typeorm";
import {Parent} from "./Parent";
import {Child} from "./Child";


@Entity()
export class Family {

    @PrimaryGeneratedColumn()
    id: number

    @OneToMany(type => Parent, parent => parent.family)
    parents: Parent[]

    @OneToMany(type => Child, child => child.family)
    children: Child[]



}

```

```javascript
//entites/Family/Member.js
@Entity()
@TableInheritance()
export class Member {

    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(type => Family)
    family: Family


}

```

```javascript

//entites/Family/Child.js
import {Column, ChildEntity, PrimaryGeneratedColumn, OneToMany, Entity, ManyToOne} from "typeorm";
import {Member} from "./Member";

@ChildEntity()
export class Child extends Member {

    @Column()
    type: string

}
```

```javascript
//entites/Family/Child.js
import {Column, ChildEntity, PrimaryGeneratedColumn, OneToMany, Entity, ManyToOne, TableInheritance} from "typeorm";
import {Member} from "./Member";


@ChildEntity()
export class Parent extends Member {

    @Column()
    type: string

}

```

**Comment by MarkMatute** [comment]
this looks like to me circular dependencies. Try to remove **OneToMany** to your Famili Entity.

**Comment by cesarve77** [comment]
Yes. If i remove manytoone. It works

IF I l move manytoone to parents and child entities.it  works



El 31 may. 2018 7:30 AM, "Mark Ernest R. Matute" <notifications@github.com>
escribió:

this looks like to me circular dependencies. Try to remove *OneToMany* to
your Famili Entity.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/typeorm/typeorm/issues/2236#issuecomment-393326053>,
or mute
the thread

**Comment by MarkMatute** [comment]
@cesarve77 whats your work around?

**Comment by cesarve77** [comment]
I duplicate the code. I place  @ManyToOne relation inside child and parent,
and removed from Member.

for example

//Memeber:

```Javscript

export abstract class Member {

    @Field(type => ID)
    @PrimaryGeneratedColumn()
    id: number;


}

```

and parent:

```javscript

@ObjectType()
@ChildEntity('parent')
export class Parent extends Member {


    @Field(type => Family)
    @ManyToOne(type => Family, family => family.parents)
    family: Family

}


```

2018-05-31 14:30 GMT+10:00 Mark Ernest R. Matute <notifications@github.com>:

**Comment by dbartholomae** [comment]
Having the same problem and can confirm that it works when moving the `@ManyToOne` decorator to the child entities.

**Comment by Ginden** [comment]
This is an issue related to how Node.js and TypeScript handle recursive dependencies, not TypeORM.
