### ISSUE TITLE
@BeforeInsert decorator fires on "save" not "insert"

### ISSUE THREAD

**Issue by brianasapp** [typeorm/typeorm#2237]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

## System Information
**Operating System:** macOS Sierra 10.12.6

## Node Information
**Node version:** 8.3.0
**TypeORM version:** 0.2.6
**Typescript version:** 2.8.3
**Reflect Metadata version:** 0.1.12
**Sqlite version:** 4.0.0

Hi all and thank you for taking the time to look at this issue. I have noticed that the beforeInsert listeners on entity metadata will fire on `save` but not `insert`.

Consider the following example:

```ts
import "reflect-metadata";

import { createConnection, BeforeInsert, Entity, PrimaryColumn } from 'typeorm';

@Entity()
export class Foo {

    @PrimaryColumn()
    private bar: string;

    @BeforeInsert()
    private beforeInsert() {
        console.log('executing before insert');
    }
}

async function main() {
    const db = await createConnection({
        type: 'sqlite',
        database: 'test.db',

        logging: false,
        synchronize: true,
        entities: [Foo],
    });

    const foo1 = new Foo();

    db.manager.save(foo1);
    db.manager.insert(Foo, {
        bar: 'new-id',
    });
}

main();
```

If you run the above code, you'll notice that the log statement in `beforeInsert` fires only once when `main()` is called.

Having dug a little deeper, I have found that when `insert` is called the metadata object has no `beforeInsertListeners` on the line found here https://github.com/typeorm/typeorm/blob/master/src/subscriber/Broadcaster.ts#L33.

Is this the desired behavior? If it is not I am happy to investigate further and open a pull request.

Thank you again and have a blessed day,
Brian

**Comment by brianasapp** [comment]
@pleerock sorry for the ping - but may you quickly confirm that this is a bug? Happy to investigate and fix if so

**Comment by pleerock** [comment]
`beforeInsert` is a method inside `Foo` class and can be called only on a real instance of Foo, e.g.  foo.beforeInsert(). In your case you don't pass instance of Foo to the insert method, instead you are passing a plain javascript object, thats why there is no method to be called by ORM.

Fix:

```ts
    const insertedFoo = new Foo();
    insertedFoo.bar = 'new-id';
    db.manager.insert(Foo, insertedFoo);
```

**Comment by brianasapp** [comment]
Hey, thanks for the reply! Is it wrong to believe that it might fire since the prototype is being passed into `insert`?

The reason I ask is that for wider tables it's very nice to just use

```ts
db.manager.insert(WideTable, {
  column1,
  column2,
  column3,
  column4,
});
```
and the compiler actually makes this type safe (don't know how but it's very nice).

I could create a constructor for each entity feels clunky to me (although it is the next best option).

If there isn't any value or is an antipattern - I can close this ticket, was just wondering if we could change this now to a feature request

**Comment by brianasapp** [comment]
as well as I would be happy to implement!

**Comment by pleerock** [comment]
there is no way to change this behaviour. Its a natural behaviour.  Again your method is instance of some class and that method can call let's say `this`.

**Comment by brianasapp** [comment]
okay no worries in that case
