### ISSUE TITLE
How to define ObjectID type column (other than _id)

### ISSUE THREAD

**Issue by thonythony** [typeorm/typeorm#2238]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an entity : 

```typescript
@Entity()
export class RolePermission implements IRolePermission {
    @ObjectIdColumn() id?: ObjectID;

    @Column()
    @IsNotEmpty()
    roleId: ObjectID;

    @Column()
    @IsNotEmpty()
    permissionId: ObjectID;
}
```

The code compiles. But when I start my server, this error throws :
```bash
> node ./dist/server.js

error:  ColumnTypeUndefinedError: Column type for RolePermission#roleId is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.
```

I have turned on the option in my tsconfig.json and I import reflect-metadata at the top of my file server.ts.

I read the code about the decorator ObjectIdColumn and if I think it used only for primary use case, so it's not applicable for my need.

Thanks a lot for your help

**Comment by pleerock** [comment]
you need to install mognodb typings and import ObjectID from mongodb, like this:

```ts
import {ObjectID} from "mongodb";

@Entity()
export class RolePermission implements IRolePermission {
    @ObjectIdColumn() id?: ObjectID;

    @Column()
    @IsNotEmpty()
    roleId: ObjectID;

    @Column()
    @IsNotEmpty()
    permissionId: ObjectID;
}
```

 I know this is confusing, and its something we have to resolve.

**Comment by thonythony** [comment]
I will test that.
But what's the difference between `ObjectID` from typeorm package and `ObjectID` from mongodb package ?

**Comment by pleerock** [comment]
in typeorm package they are just declarations without real implementations. In mongodb they are real :)

**Comment by thonythony** [comment]
Ok thx for your explanation. I have tested and I can confirm it works !

**Comment by Alex0007** [comment]
Having two ObjectID from various places is pain

**Comment by ruturajsolanki230** [comment]
By importing ObjectID from mongodb library it stores that field value other than _id as a String not as ObjectId in database collection.
Please give solution ASAP.
Thanks in advance.

**Comment by kiwikern** [comment]
This saves the ObjectID as string in the database though and leads to problems when querying a collection, see https://github.com/typeorm/typeorm/issues/2787.

**Comment by sergiuturus** [comment]
I tried importing ObjectID from mongodb and typeorm and in both cases my id is saved as string instead of an ObjectID. I don't understand what's the problem here.
