### ISSUE TITLE
Date Columns don't work - JS

### ISSUE THREAD

**Issue by rotexhawk** [typeorm/typeorm#2239]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following entity but typeorm doesn't create the fields in the database. I removed the table and started from scratch and still no change. Also had the values as undefined initially, which didn't work as well. 

import {Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn} from 'typeorm';

@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id = undefined;

    @Column('varchar')
    firstName = '';

    @Column('varchar')
    lastName = '';

    @Column('varchar')
    extra = '';

    @Column('integer')
    age = undefined;

    @CreateDateColumn
    created_at = Date.now();

    @UpdateDateColumn
    updated_at = Date.now();

}

**Comment by filipjnc** [comment]
1. A decorator must have brackets (`@CreateDateColumn` must be `@CreateDateColumn()`)
2. I think it's not recommended to define default values in the model definition, just provide the type. This is particularly relevant for dates, since it's always best to leave the database assign the dates by itself (they are using CURRENT_TIMESTAMP or similar in the background). 

Try the following:

```
@Column('varchar')
firstName: string;

@Column('varchar')
lastName: string;

@Column('varchar')
extra: string;

@Column('integer')
age: number;

@CreateDateColumn
created_at: Date;

@UpdateDateColumn
updated_at: Date;
```

**Comment by pleerock** [comment]
@filipjnc he uses javascript so it his case he cannot define types. @rotexhawk try to set type explicitly: `@CreateDateColumn({ type: "datetime" })`
