### ISSUE TITLE
Problem with relations after deployment

### ISSUE THREAD

**Issue by MoustafaElkady** [typeorm/typeorm#2241]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

hello, i'm using Typeorm with ionic, every thing is ok, when i test the app at browser or via Devapp it work find on Cordova storage and browser sql

the problem happens when i produce the apk, when i put the records that is many to one relation ship, its inserted into database without foreign  key

also when i'm doing this `ionic cordova build android --prod --release`
this happens

> ERROR in Error: TypeError: Cannot read property 'kind' of undefined

**Comment by havenchyk** [comment]
@MoustafaElkady could you please provide a small example to reproduce the problem?

**Comment by pleerock** [comment]
Google this error, it might be not related to typeorm.

**Comment by havenchyk** [comment]
I’d close this issue, feel free to reopen or ask a question at stackoverflow
