### ISSUE TITLE
discriminatorValue?

### ISSUE THREAD

**Issue by cesarve77** [typeorm/typeorm#2243]
First, thanks for this great package
second, sorry for my english 

**Issue type:**
[x ] question

**Database system/driver:**
[x ] `mssql`

**TypeORM version:**
[x ] `latest`

Could you explain please the following un document features:
TableInheritance options
and ChildEntity discriminatorValue

```
TableInheritance(options?: {
    pattern?: "STI";
    column?: string | ColumnOptions;
})

ChildEntity(discriminatorValue?: any)
```
As I view,  column create a column in the table and it is filled with discriminatorValue in each case.

I'm wondering that make something else behind the scene. Because if I made a find with one relation in a child entity, it bring me all records from ether table .

For works properly i have to use querybuilder and add the condition join
`
.leftJoinAndSelect("user.photos", "photo", "photo.type = :type", { type: discriminatorValue })
`

**Comment by cesarve77** [comment]
I can tried to help with this bug, just give me some clues, for where to start

**Comment by pleerock** [comment]
start with a PR with a failing test with minimal reproduction code

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
