### ISSUE TITLE
Missing primary column with composition - @next

### ISSUE THREAD

**Issue by RDeluxe** [typeorm/typeorm#2244]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```ts
import { Entity, ManyToOne, Column } from 'typeorm';
import { CandidateEntity } from '../candidate/candidate.entity';
import { SocialEntity } from './social.entity';

@Entity()
export class CandidateSocialEntity {
  @ManyToOne(type => CandidateEntity, candidate => candidate.candidateSocials, {
    primary: true,
  })
  public candidate: CandidateEntity;

  @ManyToOne(type => SocialEntity, social => social.candidateSocials, {
    primary: true,
  })
  public social: SocialEntity;

  @Column('text') public link: string;
}
```

This is basically a custom joint table, as I wanted to add another column to it (`link`). My primary key is a composition of foreign keys.

This was working in 0.2.0-alpha-9 but not anymore in 0.3.0-alpha.5.

**Comment by pleerock** [comment]
its a breaking change of 0.3.0. We would not allow to use primary relations without having a primary columns defined. This decision was made because of hundred issues bring by previous approach. New way is:

```ts
@Entity()
export class CandidateSocialEntity {

  @PrimaryColumn()
  candidateId: number;
 
  @ManyToOne(type => CandidateEntity, candidate => candidate.candidateSocials)
  public candidate: CandidateEntity;

  @PrimaryColumn()
  socialId: number;

  @ManyToOne(type => SocialEntity, social => social.candidateSocials)
  public social: SocialEntity;

  @Column('text') public link: string;
}
```
