### ISSUE TITLE
Schema synchronization and migration

### ISSUE THREAD

**Issue by KamGor** [typeorm/typeorm#2245]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Install typescript, ts-node, typeorm. Initialize project with cli using ts-node. Create some entites with relations one-to-one. After this use cli to synchronize database. After change synchronize database again. Then database reads tables and columns .After that operation cli want again create every table despite that there are exist tables like ex. users.

Error occurs even when try to run created migration.

Addition: My postgres database runs on docker container.

**Comment by pleerock** [comment]
please provide a minimal reproduction git repository.

**Comment by KamGor** [comment]
Here you are:
https://github.com/KamGor/typeormBug

I think i found what causes bug. When i provide schema public and default schema is public then cli can't properly read existing databases and update them.

**Comment by pleerock** [comment]
so, if you remove "public" from your connection options then it works fine?

**Comment by KamGor** [comment]
@pleerock Yes exactly

**Comment by imnotjames** [comment]
I'm gonna close this in favor of #6343
