### ISSUE TITLE
OneToMany relation works only at debug apk

### ISSUE THREAD

**Issue by WebFairyNet** [typeorm/typeorm#2247]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello everyone, I'm using the same structure used at ionic example, every thing is ok on the broswer and on debug apk, the problem happends when i make final production apk

the problem is when I'm using this method, author not saved at post

```
    const author = new Author();
    author.name = "Person";

    const post = new Post();
    post.title = "Control flow based type analysis";
    post.text = `TypeScript 2.0 implements a control flow-based type analysis for local variables and parameters.`;
    post.author = author;

    const postRepository = getRepository('post') as Repository<Post>;
    await postRepository.save(post);
```

**Comment by pleerock** [comment]
please provide more information

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
