### ISSUE TITLE
Can limit releation table fields in findoption? 

### ISSUE THREAD

**Issue by keyiis** [typeorm/typeorm#2248]
**Issue type:**

[* ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[* ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[* ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Can i limit releation table fields in findoption?like:
```
let rst = await getRepository(BalanceBill).findAndCount({
       select['*','account.name'],			
       relations:["account"]
       });
```
except sql
`select bill.*,account.name from bill,account where bill.faccount=account.id`

**Comment by pleerock** [comment]
you need to create a query builder for this purpose.

**Comment by keyiis** [comment]
@pleerock If can be realized this function in the next version would be great!

**Comment by pleerock** [comment]
you can already try it in `@next` (npm i typeorm@next)

**Comment by keyiis** [comment]
@pleerock That's great! where can i find document about @next?

**Comment by pleerock** [comment]
only source code!

**Comment by keyiis** [comment]
@pleerock I already update to @next,but how to use `or` and `select` in find options?has some example?

**Comment by keyiis** [comment]
@pleerock Has many error in @next verison
```
D:/test-api/node_modules/typeorm/find-options/FindOptions.d.ts(14,27): error TS1005: ';' expected.
D:/test-api/node_modules/typeorm/find-options/FindOptions.d.ts(14,42): error TS1005: ')' expected.
D:/test-api/node_modules/typeorm/find-options/FindOptions.d.ts(14,43): error TS1005: ';' expected.
D:/test-api/node_modules/typeorm/find-options/FindOptions.d.ts(14,69): error TS1005: '(' expected.
D:/test-api/node_modules/typeorm/find-options/FindOptions.d.ts(14,76): error TS1005: ',' expected.
D:/test-api/node_modules/typeorm/find-options/FindOptions.d.ts(14,98): error TS1005: ',' expected.
D:/test-api/node_modules/typeorm/find-options/FindOptions.d.ts(14,101): error TS1109: Expression expected.
......
```

**Comment by pleerock** [comment]
you need to update typescript version to > 2.8

checkout examples [here](https://github.com/typeorm/typeorm/tree/next/test/functional/find-options/basic-usage).

**Comment by keyiis** [comment]
@pleerock thks replay!

**Comment by samisamsam** [comment]
I have the same issue and update typescript didn't work for me
