### ISSUE TITLE
[Feature Request] Embedded caching driver

### ISSUE THREAD

**Issue by roeehershko** [typeorm/typeorm#2250]
**Issue type:**

[ ] question
[ ] bug report
[*] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Feature Request**
It can be nice to have other caching "drivers" besides redis and mysql table, redis is nice but it is still requires networking, if we had an option for embedded database caching (rocketsdb) that can
increase caching speed and mostly the network resources

**Comment by pleerock** [comment]
So redis and table is enough in most cases. You can implement your own caching driver for all other needs. There is abstraction and it does work. Simply provide implementation. If you think typeorm needs another generic and popular solution embed into typeorm then provide a proposal and feel free to contribute
