### ISSUE TITLE
Passing an array of objects removing property of child-table from object, causing query failure

### ISSUE THREAD

**Issue by matt-neal** [typeorm/typeorm#2253]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Utilizing an extended child-table of an ORM table, required fields for the child end up removed when being passed to the database, whether the child table or parent table name is used in the query.

When passing an array of objects to either `save` or `insert`, the ORM is removing the `anotherColumn` value from the objects within the array, which causes the query to fail due to a missing, but expected parameter.

```ts
import * as orm from "typeorm";

@orm.TableInheritance({ column: "type" })
@orm.Entity()
class User {
	constructor(init?: Partial<User>) {
		Object.assign(this, init);
	}

	@orm.PrimaryGeneratedColumn()
	id: number;

	@orm.Column()
	type: string;
}

@orm.ChildEntity("sub")
class SubUser extends User {
	constructor(init?: Partial<SubUser>) {
		super(init);
		Object.assign(this, init);
	}

	@orm.Column()
	anotherColumn: number;
}
// ...

const SubUsers = orm.getRepository(SubUser);
let subUsers: Partial<SubUser>[] = [/*...*/];

// all of these do the same thing
subUsers = subUsers;
subUsers = subUsers.map(u => SubUsers.create(u));
subUsers = SubUsers.create(subUsers);
subUsers = subUsers.map(u => new SubUser(u));

/*
all throw "QueryFailedError: bind message supplies 9 parameters, but prepared statement "" requires 10"
when subUsers.length === 2,
"supplies 13 but requires 15"
when subUsers.length === 3, etc
No error when subUsers.length === 1
*/
await SubUsers.save(subUsers);
await SubUsers.createQueryBuilder("sub_user")
	.insert().into(SubUser).values(subUsers)
	.execute();
await SubUsers.createQueryBuilder("sub_user")
}```

**Comment by paulfitz** [comment]
I hit the same problem.  In `InsertQueryBuilder.ts`, if I replace the two instances of `"discriminator_value"` with `"discriminator_value" + parametersCount` (or anything else that makes different uses of the column be treated as different parameters), then everything works for me.

**Comment by silberjan** [comment]
I ran into the same problem. Logging the sql shows, that the discriminator value is only beeing passed as a parameter to the very first item. 

``` sql
 query failed: INSERT INTO "location"("id", "lat", "lng", "details", "type", "sourceId", "parentId", "layerId") VALUES (DEFAULT, $1, $2, $3, $4, $5, DEFAULT, DEFAULT), (DEFAULT, $6, $7, $8, $9, $10, DEFAULT, DEFAULT) RETURNING "id", "details" -- PARAMETERS: [49.5502832,8.6543267,"{\"name\":\"Lidl\",\"organic\":null,\"city\":null}","DatasourceLocation","0bc9d5bf-7bcc-4bea-92b7-e9af30342232",49.5581699,8.6688487,"{\"name\":\"EDEKA\",\"organic\":null,\"city\":null}","0bc9d5bf-7bcc-4bea-92b7-e9af30342232"]
```

Location Model:
``` ts
import { ChildEntity, Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn, TableInheritance } from 'typeorm';
import { DataSource } from './dataSource';
import { Layer } from './layer';

@Entity()
@TableInheritance({ column: { type: 'text', name: 'type' } })
export class Location {
  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column({ type: 'double precision', nullable: false })
  lat: number

  @Column({ type: 'double precision', nullable: true })
  lng: number

  @Column({ type: 'jsonb', nullable: false, default: {} })
  details: { [key: string]: any }

  constructor(initial?: Partial<DatasourceLocation | LayerLocation>) {
    if (initial) {
      Object.assign(this, initial)

      if (this.id === null) {
        delete this.id
      }
      this.details = this.details || {}
    }
  }
}

@ChildEntity()
export class DatasourceLocation extends Location {
  @ManyToOne(type => DataSource, collection => collection.locations)
  source: DataSource
}

@ChildEntity()
export class Location extends Location {

  @JoinColumn()
  @ManyToOne(type => DatasourceLocation, { nullable: true })
  parent?: DatasourceLocation

  @ManyToOne(type => Layer)
  layer: Layer

}
```

It only occurs if i want to save more than one Entity at the same time. 

@pleerock If you could give me hint, where exactly to look at for this, i could try to fix it.

**Comment by paulfitz** [comment]
@silberjan when I had this problem, https://github.com/typeorm/typeorm/issues/2253#issuecomment-429437152 fixed it.  From reading the code, I see the multiple instances of the discriminator column being added, but then only one of their values gets retained.  Giving the discriminators unique names avoids this problem.  I'd be interested if the same fix works for you.

**Comment by grin0c** [comment]
@pleerock Here's the code https://github.com/typeorm/typeorm/blob/master/src/query-builder/InsertQueryBuilder.ts#L417

**Comment by paulfitz** [comment]
I made a PR with the solution that worked for me at #3998.  I'm sure it is part of the problem others have reported here, but I'm not 100% sure it is the whole problem that @matt-neal saw.
