### ISSUE TITLE
Best Practices for running multiple servers against a single database

### ISSUE THREAD

**Issue by HipsterZipster** [typeorm/typeorm#2255]
**Issue type:**

[X] question

**Database system/driver:**

[X] `postgres`

**TypeORM version:**

[X] `latest`

First off, I love working with typeorm, it's an amazing framework. 

I'm looking to scale up my express typeorm app and run multiple instances on different hosts that all use the same database.

I couldn't find any documentation written on this, but what are some best practices and things to watch out for? For example, do Subscribers and Listeners work any differently?

Thanks!

**Comment by pleerock** [comment]
I don't see any issues with scaling on multiple instances, typeorm does not care about it.
