### ISSUE TITLE
TypeError: relatedEntities.forEach is not a function

### ISSUE THREAD

**Issue by maxime1992** [typeorm/typeorm#2257]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

0.2.6 (latest at this date)

**Steps to reproduce or a small repository showing the problem:**

```
TypeError: relatedEntities.forEach is not a function
      
      at OneToManySubjectBuilder.Object.<anonymous>.OneToManySubjectBuilder.buildForSubjectRelation (../src/persistence/subject-builder/OneToManySubjectBuilder.ts:78:25)
      at ../src/persistence/subject-builder/OneToManySubjectBuilder.ts:42:22
          at Array.forEach (<anonymous>)
      at ../src/persistence/subject-builder/OneToManySubjectBuilder.ts:36:49
          at Array.forEach (<anonymous>)
      at OneToManySubjectBuilder.Object.<anonymous>.OneToManySubjectBuilder.build (../src/persistence/subject-builder/OneToManySubjectBuilder.ts:35:23)
      at EntityPersistExecutor.<anonymous> (../src/persistence/EntityPersistExecutor.ts:104:63)
      at step (../node_modules/typeorm/persistence/EntityPersistExecutor.js:32:23)
      at Object.next (../node_modules/typeorm/persistence/EntityPersistExecutor.js:13:53)
      at fulfilled (../node_modules/typeorm/persistence/EntityPersistExecutor.js:4:58)
```

I do have a service with that method:
```
  async createAccount(account: Account): Promise<Account> {
    const idAlreadyExists: Account = await this.findOneById(account.id);

    if (!!idAlreadyExists) {
      throw new ErrorAccountIdAlreadyExists();
    }

    console.log('fine', account);
    return this.accountRepository.save(account);
  }
```

From the console.log I can see that everything's fine, it's the expected object.

And an `Account` has the following type:
```
@Entity()
export class Account {
  @PrimaryColumn() id: string;

  @OneToMany(type => Bank, bank => bank)
  bank: Bank;

  @Column() shortName: string;

  @Column() fullName: string;

  @Column() color: string;

  @ManyToMany(type => User, user => user)
  @JoinTable()
  users: User[];
}
```

I've seen on [Gitter](https://gitter.im/typeorm/typeorm?at=5b11281f016ae21a4cff7a76) that @Horizahn has the same problem.

**Comment by Horizahn** [comment]
For some reason changing up the column order, even if the columns had nothing to do with the relationship seems to have fixed it.

**Comment by pleerock** [comment]
```ts
  @OneToMany(type => Bank, bank => bank)
  bank: Bank;
```

`@OneToMany` is always an array. So, it shall be `banks: Bank[];`

**Comment by Saintiano** [comment]
This error can come up when the oneTomany relationships are not properly written in the Entity design and also when you trying to store the relationships in a table.

The first One is, setting the Entity holding many of the other Entity like this

    @OneToMany(() => Address, (address) => address.users)
    address: Address[];

The other entity that has manyToOne relationship like this,

    @ManyToOne(() => Users, (users) => users.address)
    users: Users;

If the relationships are all good, then the problem is storing the entity relations to the database.

when creating the user, store the relationships like this 

    address = await this.addressRepository.findOneOrFail({
          
          where: {

            user_id: Number(userId),

          },

        });


    const user = new User();

    user.name = name;
    user.age = age;

    ### store the address as an array of objects to the relationship column
    users.address = [address]

**Comment by Sid-Turner-Ellis** [comment]
Also getting this error but in a different context: https://github.com/typeorm/typeorm/issues/9742

**Comment by Saintiano** [comment]
@Sid-Turner-Ellis what context is that

**Comment by Sid-Turner-Ellis** [comment]
Mine seems to be coming as a result of two child entities with a property of the same name that point to 2 different entities, i've ended up just changing the property names

You can see the full repo here if interested: https://github.com/Sid-Turner-Ellis/typeorm-bug
