### ISSUE TITLE
Incorrect SQL query

### ISSUE THREAD

**Issue by WeekendMan** [typeorm/typeorm#2259]
**Issue type:**

[ x ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have app based on node.js/express/typescript. When I add the following entity in the array of the typeorm entities app crashes.
I tried to use the @PrimaryGeneratedColumn decorator without the params, like in the docs, but it doesn't work neither.
The reason of crash - incorrect syntax of the SQL query (PostgreSQL) that generated by typeorm. The query is
`CREATE TABLE "social_account" ("id" NOT NULL, "first_name" character varying(255) NOT NULL, "last_name" character varying(255) NOT NULL, "image" character varying(255) NOT NULL, CONSTRAINT "PK_a69e41dd6fa725d17b040eda5e6" PRIMARY KEY ("id"))`
As you can see, there is no type after the `id` field.
Where is the problem?

```
@Entity()

export class SocialAccount {
  @PrimaryGeneratedColumn('increment', { type: 'int' })
  public id: number;

  @Column({ length: 255, name: 'first_name' })
  public firstName: string;

  @Column({ length: 255, name: 'last_name' })
  public lastName: string;

  @Column({ length: 255 })
  public image: string;

  @JoinColumn({ name: 'id' })
  @ManyToOne(() => SocialNetwork, (socialNetwork): number => socialNetwork.id)
  public socialNetworkID: number;

  @JoinColumn({ name: 'id' })
  @ManyToOne(() => User, (user): string => user.id)
  public userID: string;
}
```

**Comment by agubler** [comment]
Hi @pleerock I created a failing test for this issue (that I've also just run into) here: https://github.com/typeorm/typeorm/compare/master...agubler:postgres-incorrect-create-table-syntax

Is there anything else you need?

**Comment by pleerock** [comment]
Please create it in a PR against master branch.

**Comment by agubler** [comment]
Done @pleerock

**Comment by Kononnable** [comment]
Looks like issue was resolved(by fixing test).
