### ISSUE TITLE
PrimaryGeneratedColumn with UUID?

### ISSUE THREAD

**Issue by exports** [typeorm/typeorm#226]
incremental integer primary key is boring, it would be great if we can generate UUID as the primary key.

**Comment by pleerock** [comment]
yeah would be great to have this feature. I have plans to implement it in the future.

**Comment by dcworldwide** [comment]
Good idea. That would also help me +1

**Comment by maxcan** [comment]
this should be closed by #272 correct?

**Comment by pleerock** [comment]
yes should be so, also covered by #284

**Comment by zxr90** [comment]
Do you have plans to support this for MariaDB/MySQL?

**Comment by pleerock** [comment]
reopening this because uuid should be implemented by other drivers as well

**Comment by AlexMesser** [comment]
released in `0.1.0-alpha.33`

**Comment by pie6k** [comment]
@AlexMesser could you give an example how to use it?

**Comment by pleerock** [comment]
@pie6k I think you can look them [here.](https://github.com/pleerock/typeorm/blob/1430002e4adbf2df0061f3a5fe230257d167807c/test/functional/uuid)
