### ISSUE TITLE
[Question] Sqlite Transaction Completes Too Early

### ISSUE THREAD

**Issue by cjackson234** [typeorm/typeorm#2262]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
With the following example code, I am getting the console log for transaction complete BEFORE the transaction is complete. This seems to be worse as the entity count increases. I tested with around 1000 records. Is there a way to get an event after the data has successfully been written?

> import {getConnection} from "typeorm";
> 
> const connection = getConnection();
> const queryRunner = connection.createQueryRunner();
> 
> await queryRunner.connect();
> 
> await queryRunner.query("SELECT * FROM users");
> 
> const users = await queryRunner.manager.find(User);
> 
> await queryRunner.startTransaction();
> 
> try {
>     
>     // execute some operations on this transaction:
>     await queryRunner.manager.save(user1);
>     await queryRunner.manager.save(user2);
>     await queryRunner.manager.save(photos);
>     
>     // commit transaction now:
>     await queryRunner.commitTransaction();
>    
>    //transaction complete!
>    console.log('transaction');
>     
> } catch (err) {
>     
>     // since we have errors lets rollback changes we made
>     await queryRunner.rollbackTransaction();
>     
> }

**Comment by pleerock** [comment]
it can't be possible :) Please provide a failing test with reproduction of the issue!

**Comment by cjackson234** [comment]
So while breaking this down into a simple sample I found the issue. I was using a .forEach() loop to add entities which doesn't allow await. So I omitted it for `queryRunner.manager.save`.

Refactoring it to a for-of loop fixed it for me. Sometimes you just need to step away from the code for a while.

Thanks!
