### ISSUE TITLE
Is there a way to use adjacency relation when inheriting entity?

### ISSUE THREAD

**Issue by droplet92** [typeorm/typeorm#2264]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm using an abstract class to reduce duplicated codes.
```
/* contents.ts */

export default abstract class Contents {
  @PrimaryGeneratedColumn()
  public id: number

  @CreateDateColumn()
  public createdAt: Date

  @Column({
    default: "",
  })
  public title: string

  @Column("text")
  public text: string
}
```
```
/* documents.ts */

@Entity()
export default class Documents extends Contents {
  @ManyToOne(type => Users, author => author.documents, {
    eager: true,
    nullable : false,
  })
  public author: Users

  @OneToMany(type => Comments, comments => comments.rootDocument, {
    eager: true,
  })
  public comments: Comments[]

  @ManyToMany(type => Users, {
    eager: true,
  })
  @JoinTable()
  public likes: Users[]
}
```
Is there a way to reduce the code in such a way that the content contains the 'author'?
I read an issue #230 and it doesn't matter that the adjacency list is used or not.

**Comment by pleerock** [comment]
I already provided answer in #230. You can move this author relation into parent class but you'll have certain limitations with inverse side.

**Comment by pleerock** [comment]
you can suggest something real :)

**Comment by droplet92** [comment]
I succeeded move author relation and likes relation into parent class Contents, so single direction relation is formed. And I tried to use generic in the inverse side as shown below.
```typescript
/* Users.ts */
@Entity()
export default class Users<T>
{
  @PrimaryGeneratedColumn()
  public id: number

  @OneToMany(type => T, content => content.author)
  public contents: T[]
}
```
But I couldn't use T in right-side of type arrow, typeFunction (More specifically, ObjectType<T>.)
How does ObjectType<T> works? And It's not possible way?
```typescript
/* ObjectType.ts */
/**
 * Represents some Type of the Object.
 */
export type ObjectType<T> = { new (): T }|Function;
```

**Comment by pleerock** [comment]
I suggest you to start with the database design. How would you map everything into the database, how you would load it, etc. Its extremely hard to implement feature if its even possible to solve all issues.

**Comment by droplet92** [comment]
Thanks to your suggestion :)
