### ISSUE TITLE
Collection ordered wrong on 1:N relationship with eager loading

### ISSUE THREAD

**Issue by imione** [typeorm/typeorm#2265]
**Issue type:**
[X] question
[?] bug report

**Database system/driver:**
[X] `mysql` / `mariadb`

**TypeORM version:**
[X] `0.2.6` (or put your version here)

I got a little problem working with typeorm.
Now I am trying to find a record using `findOne(entityId)` method.

My table have 1:N relationship.
For example,
```
class User {
    @PrimaryColumn()
    id: string

    @OneToMany(() => UserSignInLog, (userSignInLog: UserSignInLog) => userSignInLog.user, {
        cascade: true,
        eager: true    
    })
    signInLogs: UserSignInLog[]
}

class UserSignInLog {
    @PrimaryColumn({ })
    id: string

    @ManyToOne(() => User, (user: User) => user.signInLogs, {
      onDelete: 'CASCADE'
    })
    @JoinColumn({ name: 'userId'})
    user: User;
}

- Consider entity specification can be quite wrong because of sample.
```

The problem is, when I load user and all of the its signIn logs, that the SignInlogs are not ordered correctly as I inserted.

I read all of query logs of my database, and tried to execute same queries which are logged. The query results are not ordered correctly same as the results of `findOne` method.
Some results are ordered fine, the others are ordered wrong: like, 'B' shows up after 'A' when it should be 'A' after ‘B’.

So, My question is,

- Is there any options to set or change order when loading all collection using eager loading?

If not, in my humble opinion, it is not a code-level problem, so I hope you to check the your query builder when `findOne` method executes. All data recorded as I wanted, only `findOne` returns wrong result.

Thanks!

**Comment by pleerock** [comment]
I think there is no strict definition of the "correct order" in all databases until you explicitly set `ORDER BY`. When you do eager relations typeorm don't know how exactly you want to order your rows thus it does not insert any ORDER BY into your query.

**Comment by imione** [comment]
@pleerock Yepp, you are right. Then the query builder has also no problem as you mentioned.
So, Can I have an option to set any 'order' ?
I need a collection correctly ordered :(

**Comment by pleerock** [comment]
> Then the query builder has also no problem as you mentioned.

but in query builder you are explicit and you can set any order you want.

Here we can add another option like `eagerOrder`, but Im not sure if I want to add another complexity.

**Comment by imione** [comment]
@pleerock
Querybuilder is not exactly what I want to use, but it is enough at the moment.
I determine using the querybuilder, and if you add some more options and complexity, then I am refactoring my application.
Closing this issue. Thanks for your supporting!

**Comment by mirupal** [comment]
This was exactly what I was search the docs for. Seemed logical to me to have an order option for relations. 

Then I'll have to use the querybuilder..
