### ISSUE TITLE
How to save an array of integer in MSSQL using typeorm?

### ISSUE THREAD

**Issue by KrishnaAnanthi** [typeorm/typeorm#2267]
I want to save an array of int(say [1,2,3]) in one column. I tried to use the following lines but typeorm is not recognizing array
I want to save the below request,
{
	"title":"Hello", 
	"simpleIntArray":[1,2]
}
Entity I used is,
@Entity()
export class ArrayTest {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    title: string; 

    @Column()
    simpleIntArray: number[];
    
}

I tried by declaring array in different ways but nothing was working. Am i doing anything wrongly?

 @Column("int", { isArray: true })
    simpleIntArray: number[];

 @Column("int", { isArray: true })
    simpleIntArray: Array<number>;

query failed:  CREATE TABLE "array_test" ("id" int NOT NULL IDENTITY(1,1), "title" nvarchar(255) NOT NULL, "modifiedDate" datetime2 NOT NULL CONSTRAINT "df_array_test_modifiedDate" DEFAULT (getdate()), "createdDate" datetime2 NOT NULL CONSTRAINT "df_array_test_createdDate" DEFAULT (getdate()), "testDate" datetime, "simpleIntArray"
int array NOT NULL, PRIMARY KEY("id"))
error:  { RequestError: Incorrect syntax near 'array'.

Please let me know how to save array of integer

**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:** 

[ ] `latest`
[ ] `@next`
[0.1.21 ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
mssql does not support arrays. 

you can use "simple-array" type (`@Column("simple-array")`) which is very trivial orm-level implementation of array, and it can be only string array.
