### ISSUE TITLE
Question: queryBuilder and entityManager yielding different queries, am I doing this wrong?

### ISSUE THREAD

**Issue by iamgmd** [typeorm/typeorm#2269]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have two entities Solution and SolutionComponent with the following relationships:

Solution

```
  @OneToMany(() => SolutionComponent, solutionComponent => solutionComponent.solutionid_ref)
  @JoinColumn({ name: "solutionid" })
  solutioncomponent_refs: [SolutionComponent];

```
SolutionComponent

```
  @ManyToOne(() => Solution, solution => solution.solutioncomponent_refs)
  @JoinColumn({ name: "solutionid" })
  solutionid_ref: [Solution];

  @OneToOne(() => SolutionComponent, solutioncomponent => solutioncomponent.rootsolutioncomponentid_ref)
  @JoinColumn({ name: "rootsolutioncomponentid" })
  rootsolutioncomponentid_ref: SolutionComponent;
```

If I run the following query, it generates the correct T-SQL but I cannot provide a where clause on a relation of solutionbase.solutioncomponent_refs.componenttype = 60 so queryBuilder seems the only option.

```
      const records = await connection.manager
        .findOne(Solution, {
          relations: [
            "solutioncomponent_refs",
            "solutioncomponent_refs.rootsolutioncomponentid_ref"
          ],
          where: {
            solutionid: solutionid,
          }
        })
        .catch(error => {
          connection.close();
          throw error as Error;
        });
```

query: SELECT "Solution"."configurationpageid" AS "Solution_configurationpageid", "Solution"."createdby" AS "Solution_createdby", "Solution"."createdon" AS "Solution_createdon", "Solution"."createdonbehalfby" AS "Solution_createdonbehalfby", "Solution"."description" AS "Solution_description", "Solution"."friendlyname" AS "Solution_friendlyname", "Solution"."installedon" AS "Solution_installedon", "Solution"."isinternal" AS "Solution_isinternal", "Solution"."ismanaged" AS "Solution_ismanaged", "Solution"."isvisible" AS "Solution_isvisible", "Solution"."modifiedby" AS "Solution_modifiedby", "Solution"."modifiedon" AS "Solution_modifiedon", "Solution"."modifiedonbehalfby" AS "Solution_modifiedonbehalfby", "Solution"."organizationid" AS "Solution_organizationid", "Solution"."parentsolutionid" AS "Solution_parentsolutionid", "Solution"."pinpointassetid" AS "Solution_pinpointassetid", "Solution"."pinpointsolutiondefaultlocale" AS "Solution_pinpointsolutiondefaultlocale", "Solution"."pinpointsolutionid" AS "Solution_pinpointsolutionid", "Solution"."publisherid" AS "Solution_publisherid", "Solution"."solutionid" AS "Solution_solutionid", "Solution"."solutionpackageversion" AS "Solution_solutionpackageversion", "Solution"."solutiontype" AS "Solution_solutiontype", "Solution"."uniquename" AS "Solution_uniquename", "Solution"."version" AS "Solution_version", "Solution"."versionnumber" AS "Solution_versionnumber", "Solution_solutioncomponent_refs"."componenttype" AS "Solution_solutioncomponent_refs_componenttype", "Solution_solutioncomponent_refs"."createdby" AS "Solution_solutioncomponent_refs_createdby", "Solution_solutioncomponent_refs"."createdon" AS "Solution_solutioncomponent_refs_createdon", "Solution_solutioncomponent_refs"."createdonbehalfby" AS "Solution_solutioncomponent_refs_createdonbehalfby", "Solution_solutioncomponent_refs"."ismetadata" AS "Solution_solutioncomponent_refs_ismetadata", "Solution_solutioncomponent_refs"."modifiedby" AS "Solution_solutioncomponent_refs_modifiedby", "Solution_solutioncomponent_refs"."modifiedon" AS "Solution_solutioncomponent_refs_modifiedon", "Solution_solutioncomponent_refs"."modifiedonbehalfby" AS "Solution_solutioncomponent_refs_modifiedonbehalfby", "Solution_solutioncomponent_refs"."objectid" AS "Solution_solutioncomponent_refs_objectid", "Solution_solutioncomponent_refs"."rootcomponentbehavior" AS "Solution_solutioncomponent_refs_rootcomponentbehavior", "Solution_solutioncomponent_refs"."rootsolutioncomponentid" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid", "Solution_solutioncomponent_refs"."solutioncomponentid" AS "Solution_solutioncomponent_refs_solutioncomponentid", "Solution_solutioncomponent_refs"."solutionid" AS "Solution_solutioncomponent_refs_solutionid", "Solution_solutioncomponent_refs"."versionnumber" AS "Solution_solutioncomponent_refs_versionnumber", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."componenttype" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_componenttype", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."createdby" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_createdby", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."createdon" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_createdon", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."createdonbehalfby" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_createdonbehalfby", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."ismetadata" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_ismetadata", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."modifiedby" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_modifiedby", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."modifiedon" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_modifiedon", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."modifiedonbehalfby" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_modifiedonbehalfby", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."objectid" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_objectid", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."rootcomponentbehavior" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_rootcomponentbehavior", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."rootsolutioncomponentid" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_rootsolutioncomponentid", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."solutioncomponentid" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_solutioncomponentid", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."solutionid" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_solutionid", "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."versionnumber" AS "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref_versionnumber" FROM "solutionbase" "Solution" LEFT JOIN "solutioncomponentbase" "Solution_solutioncomponent_refs" ON "Solution_solutioncomponent_refs"."solutionid"="Solution"."solutionid"  **LEFT JOIN "solutioncomponentbase" "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref" ON "Solution_solutioncomponent_refs_rootsolutioncomponentid_ref"."solutioncomponentid"="Solution_solutioncomponent_refs"."rootsolutioncomponentid"** WHERE "Solution"."solutionid" = @0 -- PARAMETERS: ["777D748C-8F4C-E811-80FD-005056930C8E"

If I run the following query, it generates incorrect T-SQL but I can provide a where clause on a relation of solutionbase.solutioncomponent_refs.componenttype = 60:

```
      const records = await connection
        .getRepository(Solution)
        .createQueryBuilder("solutionbase")
        .where("solutionbase.solutionid = :id", { id: solutionid })
        .leftJoinAndSelect(
          "solutionbase.solutioncomponent_refs",
          "solutionbase.solutioncomponent_refs", "solutionbase.solutioncomponent_refs.componenttype = 60"
        )
        .leftJoinAndSelect(
          "solutionbase.solutioncomponent_refs",
          "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"
        )
        .getOne()
        .catch(error => {
          connection.close();
          throw error as Error;
        });
```

query: SELECT "solutionbase"."configurationpageid" AS "solutionbase_configurationpageid", "solutionbase"."createdby" AS "solutionbase_createdby", "solutionbase"."createdon" AS "solutionbase_createdon", "solutionbase"."createdonbehalfby" AS "solutionbase_createdonbehalfby", "solutionbase"."description" AS "solutionbase_description", "solutionbase"."friendlyname" AS "solutionbase_friendlyname", "solutionbase"."installedon" AS "solutionbase_installedon", "solutionbase"."isinternal" AS "solutionbase_isinternal", "solutionbase"."ismanaged" AS "solutionbase_ismanaged", "solutionbase"."isvisible" AS "solutionbase_isvisible", "solutionbase"."modifiedby" AS "solutionbase_modifiedby", "solutionbase"."modifiedon" AS "solutionbase_modifiedon", "solutionbase"."modifiedonbehalfby" AS "solutionbase_modifiedonbehalfby", "solutionbase"."organizationid" AS "solutionbase_organizationid", "solutionbase"."parentsolutionid" AS "solutionbase_parentsolutionid", "solutionbase"."pinpointassetid" AS "solutionbase_pinpointassetid", "solutionbase"."pinpointsolutiondefaultlocale" AS "solutionbase_pinpointsolutiondefaultlocale", "solutionbase"."pinpointsolutionid" AS "solutionbase_pinpointsolutionid", "solutionbase"."publisherid" AS "solutionbase_publisherid", "solutionbase"."solutionid" AS "solutionbase_solutionid", "solutionbase"."solutionpackageversion" AS "solutionbase_solutionpackageversion", "solutionbase"."solutiontype" AS "solutionbase_solutiontype", "solutionbase"."uniquename" AS "solutionbase_uniquename", "solutionbase"."version" AS "solutionbase_version", "solutionbase"."versionnumber" AS "solutionbase_versionnumber", "solutionbase.solutioncomponent_refs"."componenttype" AS "solutionbase.solutioncomponent_refs_componenttype", "solutionbase.solutioncomponent_refs"."createdby" AS "solutionbase.solutioncomponent_refs_createdby", "solutionbase.solutioncomponent_refs"."createdon" AS "solutionbase.solutioncomponent_refs_createdon", "solutionbase.solutioncomponent_refs"."createdonbehalfby" AS "solutionbase.solutioncomponent_refs_createdonbehalfby", "solutionbase.solutioncomponent_refs"."ismetadata" AS "solutionbase.solutioncomponent_refs_ismetadata", "solutionbase.solutioncomponent_refs"."modifiedby" AS "solutionbase.solutioncomponent_refs_modifiedby", "solutionbase.solutioncomponent_refs"."modifiedon" AS "solutionbase.solutioncomponent_refs_modifiedon", "solutionbase.solutioncomponent_refs"."modifiedonbehalfby" AS "solutionbase.solutioncomponent_refs_modifiedonbehalfby", "solutionbase.solutioncomponent_refs"."objectid" AS "solutionbase.solutioncomponent_refs_objectid", "solutionbase.solutioncomponent_refs"."rootcomponentbehavior" AS "solutionbase.solutioncomponent_refs_rootcomponentbehavior", "solutionbase.solutioncomponent_refs"."rootsolutioncomponentid" AS "solutionbase.solutioncomponent_refs_rootsolutioncomponentid", "solutionbase.solutioncomponent_refs"."solutioncomponentid" AS "solutionbase.solutioncomponent_refs_solutioncomponentid", "solutionbase.solutioncomponent_refs"."solutionid" AS "solutionbase.solutioncomponent_refs_solutionid", "solutionbase.solutioncomponent_refs"."versionnumber" AS "solutionbase.solutioncomponent_refs_versionnumber", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."componenttype" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_componenttype", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."createdby" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_createdby", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."createdon" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_createdon", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."createdonbehalfby" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_createdonbehalfby", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."ismetadata" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_ismetadata", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."modifiedby" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_modifiedby", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."modifiedon" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_modifiedon", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."modifiedonbehalfby" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_modifiedonbehalfby", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."objectid" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_objectid", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."rootcomponentbehavior" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_rootcomponentbehavior", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."rootsolutioncomponentid" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_rootsolutioncomponentid", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."solutioncomponentid" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_solutioncomponentid", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."solutionid" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_solutionid", "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."versionnumber" AS "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref_versionnumber" FROM "solutionbase" "solutionbase" LEFT JOIN "solutioncomponentbase" "solutionbase.solutioncomponent_refs" ON "solutionbase.solutioncomponent_refs"."solutionid"="solutionbase"."solutionid" AND ("solutionbase.solutioncomponent_refs"."componenttype" = 60)  **LEFT JOIN "solutioncomponentbase" "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref" ON "solutionbase.solutioncomponent_refs.rootsolutioncomponentid_ref"."solutionid"="solutionbase"."solutionid"** WHERE "solutionbase"."solutionid" = @0 -- PARAMETERS: ["777D748C-8F4C-E811-80FD-005056930C8E"]

The latter query is joining on solutionid and not solutioncomponentid as in the first query. Am I doing something wrong here with the relation? Appreciate the advice.

**Comment by pleerock** [comment]
so basically the same comment as in #2268 can you please help with contributions and provide at least a failing test based on which we can quickly fix those issues?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
