### ISSUE TITLE
How to install TypeORM through GitHub directly?

### ISSUE THREAD

**Issue by wy193777** [typeorm/typeorm#2271]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Sometimes users might want to use a haven't published version, but currently use `npm install` from GitHub I always got errors:
```
npm ERR! path ./node_modules/typeorm/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod './node_modules/typeorm/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-06-04T18_01_59_137Z-debug.log
```

Some install command I have tried:
```
npm install --save https://github.com/typeorm/typeorm/tarball/master
npm install --save git+https://git@github.com/typeorm/typeorm.git
npm install --save https://github.com/typeorm/typeorm.git
npm install --save git://github.com/typeorm/typeorm.git#master
npm install --save git+ssh://git@github.com:typeorm/typeorm.git#master
```
They all produce same errors.

**Comment by pleerock** [comment]
I think you can't. Typeorm isn't that simple. You need to checkout repository run `gulp package` then `cd ./build/package` then publish a package as a npm module (or push result of the package into some git) and use it. I just published 0.2.7 you have the latest changes. Sorry for the delay.

**Comment by wy193777** [comment]
Thanks for your response. Maybe we can execute some hook script for this. I will try to find a doable way.

**Comment by jasperblues** [comment]
@wy193777 Can you share your githook? I have a feature in development - need to test it on a client project before sending a pull request.

**Comment by wy193777** [comment]
> @wy193777 Can you share your githook? I have a feature in development - need to test it on a client project before sending a pull request.

I didn't do any hook. I package the code locally then upload the package to a github repo. Then npm install from the github repo.
