### ISSUE TITLE
Selecting embedded entities

### ISSUE THREAD

**Issue by SharmaTushar** [typeorm/typeorm#2272]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How can embedded entities be selected?

```ts

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    age: number;

    @Column(() => Device)
    device: Device;

}

export class Device {
    @Column()
    type: string;

    @Column()
    token: string;
}

const user = await getRepository(User).find({
    select: ["id", "device"],
});

```
This results in 

```
Error: device column was not found in the User entity.
```
Trying to fetch it as a relation doesn't work either.

**Comment by pleerock** [comment]
they are always selected automatically, you don't need to explicitly select them.

**Comment by SharmaTushar** [comment]
It doesn't work if you also need to include columns which are decorated with ```@Column({select: false})```.

**Comment by pleerock** [comment]
in 0.3.0 (@next) syntax has changed, but in 0.2.0 not sure if such functionality was implemented for embed, but try following:

```ts
select: ["id", "device.type"],
```

**Comment by SharmaTushar** [comment]
I have already tried this and other variations with 0.2.x but they fail to compile. Same with @next.

**Comment by pleerock** [comment]
> I have already tried this and other variations with 0.2.x but they fail to compile

ah okay then 0.2.x does not support it.

>  Same with @next.

`@next` have different syntax:

```ts
select: {
    id: true,
    device" {
         type: true
    }
}
```
