### ISSUE TITLE
Can you add/remove to a many-to-many relationship without fetching all rows?

### ISSUE THREAD

**Issue by darkf** [typeorm/typeorm#2274]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.6` (or put your version here)

Is there a way to do this:

```typescript
const image = new Image();
const post = manager.find(Post, 1);

post.images.push(image);
manager.save(post);
```

(or remove)

without first loading & joining all images in post?

Also: Is there a way to select where a certain entity is in a relation? e.g.:

```
manager.find(Post, { where: { images: image } });
```

You can do this with query builders but what about the persistence layer?

**Comment by pleerock** [comment]
the other was is to use [relational query builder](http://typeorm.io/#/relational-query-builder)

**Comment by SharmaTushar** [comment]
> manager.find(Post, { where: { images: image } });  

I had been looking for something similar. It doesn't seem to work in 0.2.x, but works in `@next`.

```ts
@Entity()
    export class User {

        @PrimaryGeneratedColumn()
        id: number;

        @ManyToMany(() => ProductGroup, productGroup => productGroup.favoritedBy)
        favorites: ProductGroup[];

    }

    @Entity()
    export class ProductGroup {

        @PrimaryGeneratedColumn()
        id: number;

        @ManyToMany(() => User, user => user.favorites)
        @JoinTable({name: 'wishlist'})
        favoritedBy: User[];

    }
    
    const favorites = await getRepository(ProductGroup).find({
        where: {
            favoritedBy: [
                {id: 1} as User
            ]
        }
    });
```

**Comment by pleerock** [comment]
Glad that you got what you wanted.
