### ISSUE TITLE
event.entity is undefined in subscriber when deleteing using queryBuilder

### ISSUE THREAD

**Issue by EugeniaM** [typeorm/typeorm#2278]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.5` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am removing object in my custom repository using the method
```
removeById(id: number): Observable<DeleteResult> {
    return Observable.fromPromise(
      this.createQueryBuilder()
        .delete()
        .from(InspectionResult)
        .where('id = :inspectionResultId', { inspectionResultId: id })
        .execute()
    );
  }
```
My Subscriber looks like this
```
@EventSubscriber()
export class InspectionResultSubscriber implements EntitySubscriberInterface<InspectionResult> {

  listenTo() {
    return InspectionResult;
  }

  afterRemove(event: RemoveEvent<InspectionResult>) {
    console.log(event.entity);
  }
}
```

afterRemove is triggered, but I get undefined in event.entity. event object doesn't hold the info about removed entity at all. Can I use queryBuilder to remove the entity and get info about this entity in subscriber?

**Comment by pleerock** [comment]
please checkout similar discussion in #2246 . In this case when you call delete you don't have any entities that orm can send you to subscriber. query builder just executes you DELETE * FROM table WHERE x. To fix this behaviour ORM needs to execute SELECT * FROM table WHERE x. Its not efficient of course =) entity is being passed to subscriber only when you call manager/repository's .remove method with entity passed.
