### ISSUE TITLE
Selecting with an inner join

### ISSUE THREAD

**Issue by stormpat** [typeorm/typeorm#2279]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.4` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Im trying to build a aggregate from different tables, and join the result on an PK. Is there any way of doing this or should i just use raw sql for these kinds of queries? 

The SQL query:

```sql 
    SELECT users.id, users.name, costs.total_cost, profits.total_profit
    FROM users
    INNER JOIN (SELECT costs.user_id, sum(costs.amount) AS total_cost 
    FROM costs 
    GROUP BY costs.user_id) costs
    ON users.id = costs.user_id
    INNER JOIN (SELECT profits.user_id, sum(profits.amount) AS total_profit 
    FROM profits 
    GROUP BY profits.user_id) profits 
    ON users.id = profits.user_id
    WHERE users.id < 20;
```

**Comment by mike-zenith** [comment]
`SubQuery` might help:

https://github.com/typeorm/typeorm/blob/master/test/functional/query-builder/subquery/query-builder-subquery.ts

Imho assembling raw query is easier but its not that future-proof.

**Comment by stormpat** [comment]
Thanks @mike-zenith, i figured it out. For anyone else wondering, heres the final query using queryBuilder.

```javascript
    userQueryBuilder
      .select('*') // select your columns
      .innerJoin(
        query => {
          return query
            .from(Cost, 'costs')
            .select('costs.user_id, SUM(costs.cost)', 'total_costs')
            .groupBy('costs.user_id');
        },
        'costs',
        'id = costs.user_id'
      )
      .innerJoin(
        query => {
          return query
            .from(Profit, 'profits')
            .select('profits.user_id, SUM(profits.profit)', 'total_profits')
            .groupBy('profits.user_id');
        },
        'profits',
        'id = profits.user_id'
      )
      .where('user_id < :id', { id: 20 })
      .getRawMany();
