### ISSUE TITLE
Additional properties on JoinTable

### ISSUE THREAD

**Issue by SharmaTushar** [typeorm/typeorm#2282]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Would it be possible to add additional columns on JoinTable to keep relation specific data.

```ts
export class ProductGroup {

    @PrimaryGeneratedColumn()
    id: number;

    @ManyToMany(() => ProductGroup)
    @JoinTable({
        name: "accessory",
        joinColumn: {
            name: "product",
            referencedColumnName: "id"
        },
        inverseJoinColumn: {
            name: "accessory",
            referencedColumnName: "id"
        },
    })
    accessories: ProductGroup[];

}
```
Here each product has many related products, and they need to be sorted according to specified order, for which I need to save additional field `order` on the `accessory` table.

**Comment by pleerock** [comment]
yes, you can specify `joinColumns` and `inverseJoinColumn` in the options

**Comment by SharmaTushar** [comment]
Sorry, I'm unable to understand where the additional column goes. Currently I'm able to specify multiple join columns using `joinColumns` and `inverseJoinColumns`, but the column I'm trying to specify (order) doesn't join with any entity, just helps sorting related entities (accessories). This order may be different for each product, hence can't be added to the accessory (productGroup) itself.

**Comment by pleerock** [comment]
what do you call "order" here? with join columns you just specify what column in first table referencing to what column in second table.

**Comment by SharmaTushar** [comment]
`order` is just another column on the join table.

There are products and multiple products inside them. Each product can have many and belong to many products.

If each product were to belong to only one product, then I could specify this `order` column on the product table itself, but since it belongs to many products, the order of each item could vary according to which product is belongs to and the only logical place to keep this information seems to be the join table keeping relation information between the two entities.

**Comment by pleerock** [comment]
better if you draw a database tables, columns and relations that you want to achieve

**Comment by SharmaTushar** [comment]
Here is a [fiddle](http://sqlfiddle.com/#!9/88f9e6/7) showing the structure I want and the query I want to execute.

**Comment by pleerock** [comment]
now show your entites - what you tried to do.

**Comment by SharmaTushar** [comment]
My entity is shown in initial post. There is just one `ProductGroup` entity self referencing as `accessories`.

This should fit the one shown in fiddle
```ts
@Entity()
export class Product {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToMany(() => Product)
    @JoinTable({
        name: "accessory",
        joinColumn: {
            name: "parent",
            referencedColumnName: "id"
        },
        inverseJoinColumn: {
            name: "child",
            referencedColumnName: "id"
        },
    })
    accessories: Product[];

}
```

With this, the auto-generated `accessory` table contains only two columns `parent` and `child` and I can't seem to find any way to add the third column `order` which I need to use in `ORDER BY` clause.

**Comment by pleerock** [comment]
ah okay, so you kinda want to extend many-to-many table and add additional column. Anwser is - its not possible for multiple reasons. You need to create a separate entity and organize proper relations between them.

**Comment by SharmaTushar** [comment]
Even if I were to create another entity just to maintain relation specific properties, I don't get how they will be associated with existing relation. It could probably work if an existing entity table could be used as a JoinTable as well.

**Comment by pleerock** [comment]
I provided answer to your question. Now you need to try. You need to create two entities and make a one-to-many-many-to-one relations between them. Forget about JoinTable.

**Comment by deathstar1** [comment]
@SharmaTushar   
  But can we use just JoinColumn to get granchildren data . 
Fore example -  table A has foreign key from table B & table B has foreign key from table C  .
How do you get data from table C as well . Does Typeorm support this ?
