### ISSUE TITLE
@next Cannot read property 'propertyPath' of undefined

### ISSUE THREAD

**Issue by filipjnc** [typeorm/typeorm#2283]
**Issue type:**

[ ] question
[x bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.3.0-alpha.5` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I upgraded from 0.2.6 to 0.3.0-alpha.5 and I am getting an error when running the following:

`await this.repository.find({ relations: ['oneToManyRelationName'] });`

```
Cannot read property 'propertyPath' of undefined
TypeError: Cannot read property 'propertyPath' of undefined
    at \query-builder\RelationIdLoader.ts:307:100
    at Array.forEach (<anonymous>)
    at RelationIdLoader.loadForOneToManyAndOneToOneNotOwner (\src\query-builder\RelationIdLoader.ts:306:48)
    at RelationIdLoader.load (\src\query-builder\RelationIdLoader.ts:37:25)
    at RelationIdLoader.<anonymous> (\src\query-builder\RelationIdLoader.ts:64:40)
    at step (\node_modules\typeorm\query-builder\RelationIdLoader.js:32:23)
    at Object.next \node_modules\typeorm\query-builder\RelationIdLoader.js:13:53)
    at fulfilled (\node_modules\typeorm\query-builder\RelationIdLoader.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

I figured I'd just leave this here in order to avoid future issues.

**Comment by pleerock** [comment]
hmm strange, failing test is appreciated as usual 😆

**Comment by bennycode** [comment]
I also ran into this problem using "typeorm v0.3.0-rc.19":

> Cannot read property 'propertyPath' of undefined

For me the problem was also located in the `ManyToOne` setup. I forgot to define the inverse side:

```ts
@ManyToOne(() => OwnerEntity, {onDelete: 'CASCADE', nullable: false})
owner: OwnerEntity;
```

Specifying the inverse side fixed it for me:

```ts
@ManyToOne(() => OwnerEntity, owner => owner.strategies, {onDelete: 'CASCADE', nullable: false})
owner: OwnerEntity;
```
