### ISSUE TITLE
Querybuilding and getting from many to many relationship

### ISSUE THREAD

**Issue by younusmahmood** [typeorm/typeorm#2284]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [] `mysql`
    [X] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by younusmahmood** [comment]
I have a many to many relationships and want to find some data that can return whether an id is given or if its null. I tried using the repository find method but that wasn't working when given that clause. So is there a way to do that with find or querybuilder where I can pull data from the joined tables?

```
return await this.modelRepo
      .createQueryBuilder('model')
      .leftJoinAndSelect('model.client', 'client')
      .leftJoinAndSelect('model.igs', 'igs') // this is where the many to many isn't returning the connected table
      .where('model.clientId = :clientId', { clientId })
      .orWhere('model.clientId IS NULL')
      .orderBy('model.id', 'DESC')
      .getMany();
```
Model has a many-to-many relationship with an 'igs' entity and that entity has a joined table is table for igs and the data from that table isn't being return in the above query builder. It did when I used find just with the ID but when adding the id or null clause it didnt work for the null value.

**Comment by imnotjames** [comment]
Is this still an issue with the latest version of typeorm?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
