### ISSUE TITLE
Loading relationships from existing entity instance inside the same instance

### ISSUE THREAD

**Issue by JCWolf** [typeorm/typeorm#2285]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
It is possible to load relationships using an existing entity instance? 

For example, I have an `User` entity with `OneToMany` relationship with the `Reservation` entity. Then I have a user (`user = User.find(1)` ) and I want the reservations  property inside the user instance object like so(with no eager loading, lazy loading or query builder):

```ts
let user = User.find(1);
// do some processing
return user; 
/* 
expect: {
id : 1,
email : 'some@email'
}
*/
```
```ts
// load reservations
user.load('reservations')

return user;
/* 
expect: {
id : 1,
email : 'some@email',
reservations: [{etc},{etc},{etc}]
}
*/
```

PS. I cannot use eager loading because I will get `circular error`. The only option I see is by using `lazy loading` and adding the `reservations` array in my user instance like so:

```ts
let user = User.find(1);
let reservations = await user.reservations // after setting lazy loading in my entity
user.reservations = reservations;
return user;
```

**Comment by pleerock** [comment]
Without query builder you can't. Probably we can add methods to entity that can simplify loading relations without query builder in active record in the future. Feel free to contribute btw.

**Comment by JCWolf** [comment]
I understand. I'm a big fan o the Laravel's Eloquent ORM. I will steal some o the methods from there :D and try to implement them here. Thank you!

**Comment by johannesschobel** [comment]
Is there an Update regarding thus issued?

**Comment by IonelLupu** [comment]
@johannespfeiffer I didn't have time to implement this since the project I was working on was canceled.

**Comment by Matgsan** [comment]
Any updates?

**Comment by IonelLupu** [comment]
This is funny. A few moments ago I found myself needing this feature and after a quick google I found out that I was the person who posted this issue on Github. lol

Maybe it needs to be added on a priority list or something? @pleerock

**Comment by karladler** [comment]
how would the querybuilder approach look like having already an instance of the entity? Is there any solution without querying for the entity itself again?

**Comment by nickyhajal** [comment]
Also finding that this would be quite valuable!

**Comment by Antoine-arranz** [comment]
Hello, same issue here, any update ?

**Comment by Goldziher** [comment]
why is this issue closed?

**Comment by kbzowski** [comment]
+1

**Comment by daniloviic** [comment]
I've actually stumbled upon this issue a few times in the past year @IonelLupu.

I've come up with a way to fetch relations of my existing entities, but I'm using repository and query builder instead of the entity itself. I'll try to present my solution to you bellow. I know I'm really late to the party, but it seems that people are still having trouble with this, so I hope that I will maybe help someone or nudge them in the right direction for coming up with a better solution.

I'll use the analogy from the question above. So let's say that we have: `An User entity with OneToMany relationship with the Reservation entity`.

Let's also assume that our code is executed in a service class that is communicating with the user repository.
We have already loaded the user entity into a variable without any relations.

```typescript
// Fetching the user by id without any relations. Note that findById is a custom method.
const user = await this.userRepository.findById(1);
```
Assuming that the relation towards Reservation on User entity is saved under `reservations` attribute, we could do the following.
To fetch reservations of the existing user entity we can create the following function in the user repository:

```typescript
  /**
   * Returns user's reservations.
   * @param user - User entity.
   * @returns User's reservations.
   */
   async getReservations(
    user: User,
  ): Promise<Reservation[]> {
    return this.createQueryBuilder()
      // Note that 'reservations' should be the name of the relationship attribute on User entity.
      .relation(User, 'reservations')
      .of(user)
      .loadMany();
  }
```

This would fetch Reservations that are related to the given User, but wouldn't load them to the entity in question. To load the relations to the entity, we could do something like this:

```typescript
// Fetching the user by id without any relations. Note that findById is a custom method.
const user = await this.userRepository.findById(1);
const reservations = await this.userRepository.getReservations(user);
// Note that setReservations would be a simple custom method for filling the reservations attribute on user entity.
user.setReservations(reservations);
```

And there we go, you have the relations of the existing entity.

Furthermore, the function can be generalised to load any relation by passing the name of the relation as a second argument.

Something like this:

```typescript
  /**
   * Returns user's relation.
   * @param user - User entity.
   * @param relationKey - Relation key on user entity.
   * @returns User's relation.
   */
   async getRelation(
    user: User,
    relationKey: string
  ): Promise<BaseEntity[]> {
    return this.createQueryBuilder()
      .relation(User, relationKey)
      .of(user)
      .loadMany();
  }
```

This would require the following changes in the service method:


```typescript
// Fetching the user by id without any relations. Note that findById is a custom method.
const user = await this.userRepository.findById(1);
const reservations = (await this.userRepository.getRelation(user, 'reservations')) as Reservation[];
// Note that setReservations would be a simple custom method for filling the reservations attribute on user entity.
user.setReservations(reservations);
```

**Comment by rafaelklaessen** [comment]
I'm no TypeScript or TypeORM expert, but I've implemented this feature for myself (thanks to @daniloviic's comment) by adding the following method to my custom `BaseEntity` class (that all my actual entities extend):
```typescript
class BaseEntity extends TypeOrmBaseEntity {
  async loadRelation<T>(relationKey: string): Promise<T> {
    const staticAccessor = this.constructor as any;
    
    const relationValue: T = await staticAccessor.createQueryBuilder()
      .relation(staticAccessor, relationKey)
      .of(this)
      .loadMany();
 
    const currentEntity: any = this;

    currentEntity[relationKey] = relationValue;

    return relationValue;
  }
}
```

It could be used as follows:
```typescript
const posts = await user.loadRelation<Post>('posts');

// or alternatively
await user.loadRelation('posts');

console.log(user.posts);
```
> Note that the relation's value is both returned & set on the entity in question

I know it's certainly not the most neat solution - and perhaps I'm overlooking some reason as to why this is a no-go - but for me it seems to work.

**Comment by j8jacobs** [comment]
> I'm no TypeScript or TypeORM expert, but I've implemented this feature for myself (thanks to @daniloviic's comment) by adding the following method to my custom `BaseEntity` class (that all my actual entities extend):
> 
> ```ts
> import { BaseEntity as TypeOrmBaseEntity } from 'typeorm';
> 
> class BaseEntity extends TypeOrmBaseEntity {
>   async loadRelation<T>(
>     relationKey: string,
>     shouldLoadMany?: boolean,
>   ): Promise<T> {
>     if (relationKey.trim().length === 0) {
>       throw new Error('Cannot load empty relation.');
>     }
> 
>     shouldLoadMany = shouldLoadMany ?? relationKey.endsWith('s');
> 
>     const staticAccessor = this.constructor as any;
>     const relationQuery = staticAccessor
>       .createQueryBuilder()
>       .relation(staticAccessor, relationKey)
>       .of(this);
>     const relationValue: T = shouldLoadMany
>       ? await relationQuery.loadMany()
>       : await relationQuery.loadOne();
> 
>     const currentEntity: any = this;
>     currentEntity[relationKey] = relationValue;
> 
>     return relationValue;
>   }
> }
> ```
> 
> It could be used as follows:
> 
> ```ts
> const posts = await user.loadRelation<Post>('posts');
> 
> // or alternatively
> await user.loadRelation('posts');
> 
> console.log(user.posts);
> ```
> 
> > Note that the relation's value is both returned & set on the entity in question
> 
> I know it's certainly not the most neat solution - and perhaps I'm overlooking some reason as to why this is a no-go - but for me it seems to work.

@rafaelklaessen this is really cool, PR worthy perhaps? I would personally enjoy having this method in the existing BaseEntity I've been extending in all of my Entities @pleerock

**Comment by rafaelklaessen** [comment]
@j8jacobs I'm sure willing to open a PR if @pleerock thinks doing so is a good idea, but I'd need someone else to verify everything and write the corresponding test code. I've just been getting into TypeORM so I have no experience with its test suite.

**Comment by sebastiantf** [comment]
This is heavily needed!

**Comment by vsudakov** [comment]
would be great to have it!

**Comment by ShahinSorkh** [comment]
It's 2024 and the need is still there :)

**Comment by Alamonall** [comment]
its already on typeorm

https://orkhan.gitbook.io/typeorm/docs/eager-and-lazy-relations#lazy-relations
