### ISSUE TITLE
find operators like MoreThan and LessThan doesn't work properly for date fields

### ISSUE THREAD

**Issue by mkeremguc** [typeorm/typeorm#2286]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
find operators like MoreThan and LessThan doesn't work properly for date fields. some investigation showed that sqlite stores dates like ```2018-06-05 15:57:27.249``` but the query is like ```... WHERE "User"."createdAt" > ? -- PARAMETERS: ["2018-06-05T01:01:32.650Z"]``` meaning it queries in ISO date format. when you just need comparison till day factor, it doesnt look like a problem but when you also need the time/hours/mins/etc then it doesnt return proper results. i only tested for sqlite so i dont know if same problem goes for other dbs.

**Comment by enif-lee** [comment]
Hello contributors. I'm still working this issue. I don't know sqlite as well but I did test few cases about comparing datetime values. 

### What's the problem.

```sql
-- 1. getTime() doesn't working, EXPECTED: FALSE, ACTUAL: TRUE
select DATETIME('2019-01-10T00:00:00Z') > 9999999999999999999999999999999999999999999999999999999999999999999999999;

-- 2. toUTCString(), doesn't working, EXPECTED: TRUE, ACTUAL: FALSE
select DATETIME('2019-01-10T00:00:00Z') > 'Mon, 31 Dec 2018 15:00:00 GMT';

-- 3. toISOString()
-- Seem to work
-- EXPECTED: TRUE, ACTUAL: TRUE
select DATETIME('2019-01-10T00:00:00Z') > '2019-01-01T00:00:00.000Z';

-- What? Is this about timezone issue?
-- EXPECTED: TRUE, ACTUAL: FALSE
select DATETIME('2019-01-10T08:00:00Z') > '2019-01-10T00:00:00.000Z';

-- SQLite is configured UTC timezone as default on any environment,
-- EXPECTED: 2019-01-01 00:00:00, ACTUAL: 2019-01-01 00:00:00
select DATETIME('2019-01-01T00:00:00Z');

-- DATETIME comparing is working
-- EXPECTED: true, ACTUAL: true
select DATETIME('2019-01-01T00:00:00Z') = DATETIME('2019-01-01T00:00:00Z');
select DATETIME('2019-01-01T01:00:00Z') > DATETIME('2019-01-01T00:00:00Z');

-- 4. Finally I found the root cause.
-- THAT IS JUST STRING COMPARING.
select DATETIME('2019-01-01T12:00:00Z'), - RESULT: 2019-01-01 12:00:00
       '2019-01-01T00:00:00Z', - RESULT: 2019-01-01T00:00:00Z
       DATETIME('2019-01-01T12:00:00Z') > '2019-01-01T00:00:00Z', -- false
       DATETIME('2019-01-01T12:00:00Z') > '2019-01-01 00:00:00'   -- true
```

YES, sqlite support ISO 8601 date format, but it's just about insert or update, not about value comparing.
and sqlite doesn't have type to storing date, datetime, timestamp and [that will be stored as `text` type.](https://stackoverflow.com/questions/48478112/select-sqlite-date-values-in-iso-8601-format). In my think, `datetype` is just alias for `text`

```sql
-- for date
create table user
(
  id        integer  not null
    primary key autoincrement,
  createdAt datetime not null
);
select typeof(createdAt)
from user;
```
![image](https://user-images.githubusercontent.com/9916002/50906711-09337680-1469-11e9-9937-4d097d559de5.png)

### What's the solution.

1. In now, as the best simple solution. format the datetime value.

```typescript
export const MoreThanDate = (date: Date) => MoreThan(format(new Date(), 'yyyy-mm-dd HH:MM:ss.l'))
// ...
const user = await repository.findOne({
    createdAt: MoreThanDate(new Date())
})
```

2. Contribute support datetime in find interface.

**Comment by enif-lee** [comment]
@bioleyl Uhmm, this is from just simple external node package. 

Try to check below links. :)

1. https://www.npmjs.com/package/dateformat
2. https://www.npmjs.com/package/date-format

**Comment by bioleyl** [comment]
@enif-lee 
Ok thanks. I usually use an other one:
https://www.npmjs.com/package/date-fns
You just don't use the parameter date and you force new Date() in your function. Here is an update if someone is interested:

```
import { LessThan, MoreThan } from 'typeorm'
import { format } from 'date-fns'

// TypeORM Query Operators
export const MoreThanDate = (date: Date) => MoreThan(format(date, 'YYYY-MM-DD HH:MM:SS'))
export const LessThanDate = (date: Date) => LessThan(format(date, 'YYYY-MM-DD HH:MM:SS'))
// ...
const user = await repository.findOne({
    createdAt: MoreThanDate(new Date())
})
```

**Comment by pleerock** [comment]
Is it a sqlite-specific issue?

**Comment by jankarres** [comment]
Thank you for your solutions, @enif-lee and @bioleyl. I have added the functions `MoreThanOrEqualDate` and `LessThanOrEqualDate` to them. In the following several variants, depending on whether you use date-dns@2.x or date-dns@1.x. Tested with MySQL/MariaDB.

date-fns@2.x
```
import { MoreThan, MoreThanOrEqual, LessThan, LessThanOrEqual } from "typeorm";
import { format } from "date-fns";

// TypeORM query operators polyfills
const MoreThanDate = (date: Date) => MoreThan(format(date, "yyyy-MM-dd HH:MM:SS"));
const MoreThanOrEqualDate = (date: Date) => MoreThanOrEqual(format(date, "yyyy-MM-dd HH:MM:SS"));
const LessThanDate = (date: Date) => LessThan(format(date, "yyyy-MM-dd HH:MM:SS"));
const LessThanOrEqualDate = (date: Date) => LessThanOrEqual(format(date, "yyyy-MM-dd HH:MM:SS"));

export { MoreThanDate, MoreThanOrEqualDate, LessThanDate, LessThanOrEqualDate };
```

date-dns@1.x
```
import { MoreThan, MoreThanOrEqual, LessThan, LessThanOrEqual } from "typeorm";
import { format } from "date-fns";

// TypeORM query operators polyfills
const MoreThanDate = (date: Date) => MoreThan(format(date, "YYYY-MM-DD HH:MM:SS"));
const MoreThanOrEqualDate = (date: Date) => MoreThanOrEqual(format(date, "YYYY-MM-DD HH:MM:SS
const LessThanDate = (date: Date) => LessThan(format(date, "yyyy-MM-dd HH:MM:SS"));
const LessThanOrEqualDate = (date: Date) => LessThanOrEqual(format(date, "YYYY-MM-DD HH:MM:SS

export { MoreThanDate, MoreThanOrEqualDate, LessThanDate, LessThanOrEqualDate };
```

**Comment by stanleynguyen** [comment]
Same problem with PostGres

**Comment by ospfranco** [comment]
I was doing unit testing and found this problem, how is this still open for so long... very basic functionallity for an ORM...

**Comment by dgurns** [comment]
Thank you all for the info. This drove me crazy for a while and finally I solved it like this: 

My dates are saved in SQLite as ISO strings in UTC like `"2020-05-26T10:21:41.958Z"`

To compare saved dates against the current time, I did:

```
const currentUtcTimeAsSqliteString = new Date().toISOString().replace('T', ' ');

const shows = await getManager()
      .createQueryBuilder(Show, 'show')
      .where(
        'show.showtimeInUtc > :now',
        {
          now: currentUtcTimeAsSqliteString,
        }
      )
      .orderBy('show.showtimeInUtc', 'ASC')
      .getMany();
```

**Comment by ozknemoy** [comment]
for oracla this is enought: MoreThan(new Date('2020-05-31T21:00:00.000Z'))

**Comment by Jose24San** [comment]
Another example, I am using sqlite and the docs say sqlite stores dates like so "TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS")."

I needed to find items within a specific date range, I am using moment.js for date manipulations below and I am passing in a normal new Date() object as the startDate and endDate and using moment to covert them to the same string that sqlite stores them as so I can query them easily using typeORM syntax

  ```
const sqliteDateFormat = 'YYYY-MM-DD HH:MM:SS.SSS'
  const startDate = moment(options.startDate).format(sqliteDateFormat)
  const endDate = moment(options.endDate).format(sqliteDateFormat)

  const items = await getConnection()
    .getRepository(ItemsEntity)
    .createQueryBuilder('item')
    .where('item.trackedOn <= :startDate', { startDate })
    .andWhere('item.trackedOn >= :endDate', { endDate })
    .getMany()
```

And this gets many anything within the date ranges I pass in

**Comment by phil294** [comment]
This is because for persisting, dates are converted particularly:
https://github.com/typeorm/typeorm/blob/bc29597eea587d9e4423c86331e7631fe14fd13b/src/driver/sqlite-abstract/AbstractSqliteDriver.ts#L274-L277
but for querying, dates are not specifically handled
https://github.com/typeorm/typeorm/blob/bc29597eea587d9e4423c86331e7631fe14fd13b/src/driver/sqlite-abstract/AbstractSqliteDriver.ts#L355-L363
I assume the native sqlite driver then calls `.toISOString()` at some point. SQLite does not have a date type column, datetimes are internally stored as strings. So these two formats are not compatible.

**Comment by osmar85** [comment]
Yes, you are rigth!

**Comment by Aziz87** [comment]
import {DateUtils} from "typeorm/util/DateUtils";

`const dateFormat = DateUtils.mixedDateToUtcDatetimeString(date);
 const update = await this.shARepository.update({ updatedAt:LessThan(dateFormat)},{hash});
`

**Comment by vladotastc** [comment]
Hello there, I'm attempting to compare only time values. example: if 23:57 is BETWEEN 23:55 and 00:00. Any help
