### ISSUE TITLE
QueryBuilder IN and ANY Fail with .where - Postgres

### ISSUE THREAD

**Issue by svstartuplab** [typeorm/typeorm#2287]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This works:

```
    const sql = 'SELECT * FROM members WHERE '+ integerId + ' = ANY(skill_id_array)';
    const membersBySkill = await this.entityManager.query(sql);
    // This works: SELECT * FROM members WHERE 2 = ANY(skill_id_array)
```

Edit:  Also this works, although not originally because I set it up like the 'Any' example in Find Options in the docs.  This needs to be added to the QB doc for those of us who are new to the whole server stack and learning from the docs.

```
const membersBySkill = await getRepository(Members)
      .createQueryBuilder()
      .where(':id = ANY (skill_id_array)', {id: integerId})
      .getMany();
```

I've tried many setups but the two in the comments below have typical errors.  The problem seems to be in the .where with both IN and ANY.  Select statements are from my console.log on the server.  The var integerId as a value of say 2, is an integer and skill_id_array is a column in the db with values such as {1,2,5}.  There are no examples of my use in the docs or elsewhere and I suspect that this setup doesn't work in TypeORM yet or is a bug.

```
   const membersBySkill = await getRepository(Members)
      .createQueryBuilder()
      // .select('*') Do not use here. QB needs the entire selection per @pleerock in comments below.
      .where(':id IN (skill_id_array)', {id: integerId})
      .getMany();
   console.log('membersBySkill: ', membersBySkill);
   return membersBySkill;

    //  {id: '{2}'}) -> SELECT * FROM "members" "Members" WHERE $1 IN (skill_id_array) -- PARAMETERS: ["{2}"]
    //  membersBySkill =  [] empty array and no error.
    //  {id: integerId} -> SELECT * FROM "members" "Members" WHERE $1 IN (skill_id_array) -- PARAMETERS: [2]
    //  errors: malformed array literal: "2"  &  Array value must start with "{" or dimension information.
```
The entity:
```
  @Column('int', { array: true, nullable: true})
  skill_id_array: number[];
```

**Comment by pleerock** [comment]
you shall not add ".select('*')". please remove it.

**Comment by svstartuplab** [comment]
Removing .select makes no difference for the problem and wasn't there for most of the several days I've struggled with this.  Also, .select('*') gives me the above SQL that I want, SELECT * FROM...  Without it my SQL includes all the Member columns which is big and ugly.  Probably the same same effect though.

Another issue is why the double of FROM "members" "Members"?  A working SQL statement includes only one.  I tried overriding this with .from('members') but that added two more "members".

**Comment by svstartuplab** [comment]
Another issue is why the double of FROM "members" "Members"?  A working SQL statement includes only one.  Is this needed in the actual SQL for some reason?  I tried overriding this with .from('members') but that added two more "members".

**Comment by svstartuplab** [comment]
Thank you for the explanations!  It is hard to get a mental map of what TypeORM is trying to do.

As I mentioned, I added .select after battling this problem for a couple of days.  I removed it again.  It has nothing to do with the problem.  Same error messages with or without it.

As I also mentioned, I've tried both IN and ANY.  I'm showing only the IN version here.  I can add the ANY version.  Same problem.

**Comment by svstartuplab** [comment]
@pleerock I edited my post and commented out .select and added your explanation for those of us who are learning the whole server stack from the docs and don't have a mental map of how all this works.  I couldn't find good courseware to get an overview of the stack for a newbie.  

I also tried an ANY QB again and it works this time.  I added it above.  Previously I was using the Find Options docs for guidance because it shows 'Any', the TypeORM import, and the QB docs don't.  The two different methods are confusing at first.  

The IN QB still doesn't work.  It would be nice to get that solved so when others find this topic they can get work done instead of experimenting.

I see that you are the top contributor to TypeORM!  You are a god!  Thank you so much.  I will contribute $100 on OpenCollective soon.  I'm doing this for Nestjs also.  I also contribute by asking questions on SO and posting answers when I solve them.  It should help others.

**Comment by pleerock** [comment]
> I will contribute $100 on OpenCollective soon. 

Thank you! 👍 

>  I also contribute by asking questions on SO and posting answers when I solve them. It should help others.

Thank you very much, this is very important for TypeORM

What is `skill_id_array` in your code? Can you show your entity?

**Comment by svstartuplab** [comment]
I added the entity to the bottom of the issue.

**Comment by pleerock** [comment]
Here is a solution:

```ts
        const results = await getRepository(Members)
            .createQueryBuilder("member") // you shall assign an alias
            .where(":id = ANY(member.skill_id_array)", { id: 1 }) // and use that alias everywhere in your query builder
            .getMany();

```

**Comment by pleerock** [comment]
I also added a test (see above), next time you can create a PR with a failing test and I'll fix the issue if there is a bug. If there is no bug you'll find a solution by yourself pretty quickly or I can point on it. This way will save time for both of us I believe.

**Comment by svstartuplab** [comment]
Nice!  I have the ANY working now and added my version above.  Your version helps me understand more about alias.

What about the IN setup?  It should work like ANY but it isn't for me.

Putting $100 in your OpenCollective account now.  I wish more coders would contribute at this level.  I would love to do more but living off my wife's salary while I do another startup, and living in Silicon Valley is getting expensive!  :-)

**Comment by svstartuplab** [comment]
I tested your ANY suggestion in my setup and it works.  However, my app requires that I pass in variables such as my 'integerId' var.  That is a constant problem with the docs, they don't show using vars and that made it harder for me to get something that works.  Do devs really ever hard code data into their apps?

```
const membersBySkill = await getRepository(Members)
      .createQueryBuilder("member")
      .where(":id = ANY(member.skill_id_array)", { id: integerId })
      .getMany();
```

**Comment by pleerock** [comment]
> Putting $100 in your OpenCollective account now. I wish more coders would contribute at this level

Thank you very much

> What about the IN setup? It should work like ANY but it isn't for me.

it should be similar, provide code snippet that did not work

> Do devs really ever hard code data into their apps?

no, people always should use parameters and I believe they do. We should improve our documentation and add more information about parameters probably.

**Comment by svstartuplab** [comment]
The IN example that still doesn't work is in the OP above with the errors in the comments.

With hard coded data in the docs I found it confusing and was trying {}, [], and $ with the var.  I'm learning everything, including JavaScript, TypeScript, Angular, Nestjs, Express, Postgres so confusion comes easy :-)

**Comment by pleerock** [comment]
> SELECT * FROM Customers WHERE Country IN ('Germany', 'France', 'UK');

can be translated into:

```ts
createQueryBuilder(Customer, "customer")
   .where("customer.country IN (:countries)", { countries: countries.join(", ") })
   .getMany();
```

or 
```ts
createQueryBuilder(Customer, "customer")
   .where("customer.country IN (:...countries)", { countries: countries })
   .getMany();
```

**Comment by svstartuplab** [comment]
OK, but if we work on my code in the OP it should look like this but it fails:

```
const membersBySkill = await getRepository(Members)
      .createQueryBuilder("members")
      .where("members.skill_id_array IN (:id)", { id: integerId })
      .getMany();
```
This leads to the errors I mentioned in the OP, error: malformed array literal: "2".  The param and db table are the same as the ANY setups that are working so they aren't the problem.  I've tried it this way previous to my post, then reversed the .where string and it doesn't work either and with the same error.

It would really help if the docs explained how we setup these queries and why.  Examples help a lot but don't help to understand why they are done that way.

**Comment by pleerock** [comment]
> It would really help if the docs explained how we setup these queries and why.

Query Builder is just a wrapper around your SQL query. First you should know what SQL query you want to execute, next you try to build it via QueryBuilder. Docs can't cover all possible sql queries you can build with SQL.

In your code example, are you sure you can apply IN into arrays this way? Can you provide a working SQL example you built and tested and same query built with query builder that does not work?

**Comment by svstartuplab** [comment]
Thank you for your help!  I think QB is more than a wrapper because I can't use .select * with it in my query because somewhere in the black box of QB it does something different than SQL.  This is the kind of mystery that newbies spot quickly and get confused.  It eats a lot of time.

IN may work in QB but it is a lot of work.  This from my SO post on this topic:

[(https://stackoverflow.com/questions/50705276/typeorm-postgres-where-any-or-in-with-querybuilder-or-find/50745182#50745182)]

```
The issue is you can't use a variable with IN like you can with ANY. It will never work. It requires a 'list of scalars' instead of an expression is how the docs put it. My var contained a list of scalars but the IN param must have a list, not a reference to a list.

IN (id1, id2, id5) should work and you need to populate those vars elsewhere with either integers or strings. For my app that means parsing my skill_id_array and assigning the individual integers to their own unique vars. This is a lot of work when ANY will easily accomplish the same result.
```
