### ISSUE TITLE
Increment and decrement should take string also as a value

### ISSUE THREAD

**Issue by Rokt33r** [typeorm/typeorm#2288]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.6` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Because of the limit of javascript, typeorm is using a string for big integer. So, to use `increment` and `decrement` with big integer, we need to provide a string as a value.

And, I think we need a validator to check if the given string is a number because it cannot be handled by Typescript.

https://github.com/typeorm/typeorm/blob/master/src/entity-manager/EntityManager.ts#L652

If you think that we have to fix this, I'll create a PR for it.

**Comment by pleerock** [comment]
okay, create a PR. it can be `number | string`
