### ISSUE TITLE
SelectQueryBuilder from does not work

### ISSUE THREAD

**Issue by nikolay-rogovoy** [typeorm/typeorm#2291]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

        let customer2 = await connection
            .createQueryBuilder(Customer, 'customer')
            .select()
            .where('customer.id = :id', {id: 1})
            .getOne();

produces a query:
SELECT "Customer"."id" AS "Customer_id", "Customer"."name" AS "Customer_name"
FROM "customer" "Customer" WHERE "customer"."id" = $1

it works!
but:

        let customer2 = await connection
            .createQueryBuilder()
            .select()
            .from(Customer, 'customer')
            .where('customer.id = :id', {id: 1})
            .getOne();

produces a query:
SELECT *
FROM "customer" "customer" WHERE "customer"."id" = $1

this does not work: customer2 === undefined

In accordance with the documentation this should work.

**Comment by pleerock** [comment]
You need to specify what you want to select:

```ts
    let customer2 = await connection
        .createQueryBuilder()
        .select('customer')
        .from(Customer, 'customer')
        .where('customer.id = :id', {id: 1})
        .getOne();
```

When you do `createQueryBuilder(Customer, 'customer')` it automatically adds such selection for you (includes select and from).

**Comment by nikolay-rogovoy** [comment]
Thank you.
Make a change to the documentation:
http://typeorm.io/#/select-query-builder/how-to-create-and-use-a-querybuilder

import {getConnection} from "typeorm";

const user = await getConnection()
    .createQueryBuilder()
    .select()
    .from(User, "user")
    .where("user.id = :id", { id: 1 })
    .getOne();

**Comment by pleerock** [comment]
done, thank you. Don't hesitate to create PR next time!
