### ISSUE TITLE
Postgres Default Precision for Timestamp is greater than JavaScript Date precision

### ISSUE THREAD

**Issue by awwong1** [typeorm/typeorm#2296]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I just got bit by this while implementing a keyset pagination pattern over datetime. The [postgres date time types](https://www.postgresql.org/docs/current/static/datatype-datetime.html) default to 6 fractional seconds of precision, whereas JavaScript has millisecond precision only (3 fractional seconds).

Therefore, if you had some entity:

```ts
class Item {
  @CreateDateColumn({
    comment: "Item creation timestamp.",
    type: "timestamp with time zone"
  })
  public createdAt: Date;

}
```

The following query would return the item even though the greater than operator is specified:

```ts
// even though the JS date instance is the same
// db precision will evaluate `>` on these same dates to be true 
const itemInstance = await getRepository(Item).save(new Item());
const [items, count] = await getRepository(Item).createQueryBuilder("item")
  .where(`"item"."createdAt" > :createdAt`, { createdAt: itemInstance.createdAt })
  .getManyAndCount();
// itemInstance is in items
```

The workaround for people currently using the postgres `timestamp`, `time`, or `interval` types is to specify a precision in a migration:

```ts
export class TimeStampWorkaround implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(
      `ALTER TABLE "item" ALTER COLUMN "createdAt" ` +
        `TYPE timestamp(3) with time zone`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(
      `ALTER TABLE "item" ALTER COLUMN "createdAt" ` +
        `TYPE timestamp with time zone`
    );
  }
}
```

Feature? Bug? Something to note in documentation? Just wanted to put this out there in case someone else is running into this strangeness.

**Comment by pleerock** [comment]
In the flow you described there is no typeorm involved. Its all about JavaScript and Postgres. Btw instead of passing `createdAt: itemInstance.createdAt` you can format date and pass `createdAt: formatedForTheDatabaseCreatedAt)` I believe.


You can specify precision in `@CreateDateColumn` as well btw.

**Comment by awwong1** [comment]
Okay, I did not know that. Thank you!

**Comment by nikirepmvby** [comment]
I'm also having this issue and I want to get 6 fractional seconds of precision, and the only way to do that is to retrieve `createdAt` column as a string. But even specifying `createdAt!: string` without any decorator still maps to `Date` object. Is there any way to prevent that from happening?
