### ISSUE TITLE
find data with filtered relations  

### ISSUE THREAD

**Issue by lalalalaluk** [typeorm/typeorm#2297]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[^2.0.0 ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to filter with userextensions.K_Delete equal to NULL
I have two table.
One is userBasic and other is userextensions
Both have K_Delete field

```
        try {
            rtnVal = await this.userBasicRepository.find({
                relations: ['userextensions'],
                where: {
                    K_Delete: IsNull(),
                    userextensions: ??
                }
            })
            result.Success = true;
        } catch (ex) {
            result.Exception = ex;
        }
```

they have relations like below

```
@Entity("UserBasic")
export class UserBasic {

    // @Column("int",{ 
    //     generated:true,
    //     nullable:false,
    //     primary:true,
    //     name:"id"
    //     })
    @PrimaryGeneratedColumn()
    id: number;

....

    @OneToMany(type => UserExtension, userextensions => userextensions.fk_id,
        {
            cascade: true,
            onDelete: "CASCADE",
            onUpdate: "CASCADE",
        })
    userextensions: UserExtension[];

}

```

```
@Entity("UserExtension")
@Index("FK_id",["fk_id",])
export class UserExtension {

    @PrimaryGeneratedColumn()
    id:number;
        

   
    @ManyToOne(type => UserBasic, fk_id => fk_id.userextensions)
    @JoinColumn({ name:'fk_id'})
    fk_id:UserBasic;
    
  .....

    @Column("tinyint",{ 
        nullable:true,
        default:"NULL",
        name:"K_Delete"
        })
    K_Delete:number;
```

How can i get data with the K_Delete in UserExtension is NULL?

please!

**Comment by pleerock** [comment]
You need to use QueryBuilder. Please read QueryBuilder documentation, try and experiment and you'll find a solution. Think of what SQL you'll build using it.
