### ISSUE TITLE
Repository filtering not considering related columns as filter

### ISSUE THREAD

**Issue by Sturgelose** [typeorm/typeorm#2298]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`  (0.2.7)
[X] `@next` (0.3.0-alpha.5)
[] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Create models with multiple levels of relations:
```ts
@Entity()
class Ticket {
@PrimaryGeneratedColumn() id: number;
@Column() shopId: string;
@Column() chainId: string;
@OneToMany(type => TicketProduct, ticketProduct => ticketProduct.ticket)
  ticketItems: TicketProduct[];
}

@Entity()
class TicketProduct {
@PrimaryGeneratedColumn() id: number;
@ManyToOne(type => Product, product => product.id)
 product: Product;
@ManyToOne(type => Ticket, ticket => ticket.id)
ticket: Ticket;
}

@Entity()
class Product {
@PrimaryGeneratedColumn() id: number;
@OneToMany(type => TicketProduct, ticketp => ticketp.product)
ticketProduct: TicketProduct[];
}
```

I'm trying to do a query from the Ticket repository, adding TicketProduct and Product as related (which works up to here), but when I try to filter by Product ID, this doesn't appear reflected in the query.

My query is one such as:
```ts
let query = {
  where: {
     shopId: 'myshopId',
     chainId: 'myChainId',
     ticketItems: {
        product: {
          id: In([1, 2, 3]), // This gets ignored and not included in the query!
        },
      },
    },
  relations: ['ticketItems', 'ticketItems.product'],
}
this.ticketRepository.find(query);
```

Result query (SELECT a bit stripped off as it's a bit long):
```sql
SELECT * 
FROM `ticket` `Ticket` 
LEFT JOIN `ticket_product` `Ticket_ticketItems` ON `Ticket_ticketItems`.`ticketId`=`Ticket`.`id`  LEFT JOIN `product` `Ticket_ticketItems_product` ON `Ticket_ticketItems_product`.`id`=`Ticket_ticketItems`.`productId` 
WHERE `Ticket`.`shopId` = ? AND `Ticket`.`chainId` = ?

```
As you see there is no AND `Ticket_ticketItems_product`.`id` IN [id1, id2, id3]

**Comment by pleerock** [comment]
first, please provide a REAL code example and specify what EXACT version are you using. Code you written will not work in neither versions of orm and contain multiple mistakes.

**Comment by Sturgelose** [comment]
@pleerock The versions are marked in the start of the issue: I tried both with the latest `stable` and the latest `@next`. And check again because I'm providing the entities needed to make this work, the full query I'm doing and the SQL query generated from this. This is REAL code (just a bit stripped off of my real usecase as this is already replicates the issue!).

**Comment by pleerock** [comment]
I was talking about query part. For example `ticketItems = {` is not valid, it shall be `ticketItems: {`. Also `relations: ['ticketItems', 'ticketItems.product']` should give you compiler error since last part definitely won't work in `@next`

**Comment by Sturgelose** [comment]
Well, that's what you get when you are cleaning up the query (I had it in different variables but now I merged all in one to simplify the view of it and make it easier to read the query.) Still I understand that you want working code, but I'm also a human and do mistakes! Maybe adding this disclaimer that you need working code in the issue creation step would help?

Anyways, it really "works" in `@next`, you can compile it and typescript throws no erroers, but if you try to run the query you get the exception found in this other issue: https://github.com/typeorm/typeorm/issues/2283, so it doesn't work either.
In the "stable" version, it runs the query as described in the issue.

Mostly I'm trying to follow the directions found in this part of the docs:  https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#basic-options
If you see it is shown as example that you can do a find on embedded (and I guess that means related) entities.

**Comment by pleerock** [comment]
You have setup relations wrong. Here is what you need to fix:

```ts

@Entity()
export class TicketProduct {

    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(type => Product, product => product.ticketProduct) // INVERSE RELATION, NOT ID!
    product: Product;

    @ManyToOne(type => Ticket, ticket => ticket.ticketItems) // INVERSE RELATION, NOT ID!
    ticket: Ticket;
}
```

I added test that checks that everything works. Please next time if you report some bug or issue attach PR with a test so we can fix it more efficiently.

**Comment by clevercodenl** [comment]
> You have setup relations wrong. Here is what you need to fix:
> 
> ```ts
> @Entity()
> export class TicketProduct {
> 
>     @PrimaryGeneratedColumn()
>     id: number;
> 
>     @ManyToOne(type => Product, product => product.ticketProduct) // INVERSE RELATION, NOT ID!
>     product: Product;
> 
>     @ManyToOne(type => Ticket, ticket => ticket.ticketItems) // INVERSE RELATION, NOT ID!
>     ticket: Ticket;
> }
> ```
> 
> I added test that checks that everything works. Please next time if you report some bug or issue attach PR with a test so we can fix it more efficiently.

These relationships are setup correctly because typeorm will generate productId and ticketId columns for the TicketProduct table. I'm having the exact same problem, but with nested filtering...
