### ISSUE TITLE
Postgresql time - how to save just hours

### ISSUE THREAD

**Issue by rafal-rudnicki** [typeorm/typeorm#2299]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.1.9`

**Steps to reproduce or a small repository showing the problem:**

I have below entity
```ts  
@Entity()
export class Availability {

    @PrimaryGeneratedColumn() id: number;

    @Column({ name: 'available_from', type: 'time without time zone', length: 9}) availableFrom: string;
}
```

When i save an entity which has "18:30:00" as value of "availableFrom" then in result that entity looks in database this way: "1970-01-01 18:30:00". The question is how to force TypeORM to save just hour? In that case "18:30:00" should be saved. Thx!

**Comment by pleerock** [comment]
I think you need to use different database type which only stores hours.
