### ISSUE TITLE
Error when create relation with concrete table inheritance

### ISSUE THREAD

**Issue by exports** [typeorm/typeorm#230]
It throws `Error: Entity metadata for ResourceOwner#tokens was not found.` with following entity definitions.

```
@AbstractTable()
export class OAuthToken {
    ...

    @ManyToOne(type => ResourceOwner, owner => owner.tokens)
    owner: ResourceOwner;
}

@Table()
export class AccessToken extends OAuthToken {
}

// other subclass tokens...
```

```
@Table()
export class ResourceOwner {
    ...

    @OneToMany(type => OAuthToken, token => token.owner)
    tokens: OAuthToken[];
}
```

**Comment by pleerock** [comment]
You can't point to abstract property on inverse side. 

```typescript
@OneToMany(type => OAuthToken, token => token.owner)
    tokens: OAuthToken[];
```

you cant target only concrete entities like `AccessToken`, not abstract like `OAuthToken`

**Comment by GeeWee** [comment]
Is there any plans for this feature @pleerock ?

**Comment by pleerock** [comment]
its not possible to point to "any inherited table" from inverse side, referenced table should be a concrete table you want to reference, thats why you should use concrete entities in your base entities.
