### ISSUE TITLE
Export ValueTransformer

### ISSUE THREAD

**Issue by lorenzleutgeb** [typeorm/typeorm#2300]
**Issue type:** Feature Request

**TypeORM version:** `0.2.6`

**Steps to reproduce or a small repository showing the problem:**

As part of my application code I would like to implement [`ValueTransformer`](https://github.com/typeorm/typeorm/blob/master/src/decorator/options/ValueTransformer.ts). However, that type seems not to be exported by TypeORM. Please consider exporting it.

**Comment by pleerock** [comment]
Feel free to PR

**Comment by mohyt** [comment]
@pleerock : Created a PR for this: https://github.com/typeorm/typeorm/pull/2495
Can you please a bump up the version to have these changes?

**Comment by pleerock** [comment]
PR was merged, thanks for the contribution!

**Comment by mohyt** [comment]
@pleerock can you please publish the npm package for this change?
