### ISSUE TITLE
How to add a comment to the reference fields

### ISSUE THREAD

**Issue by nikolay-rogovoy** [typeorm/typeorm#2301]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In an ordinary column, this is done like this:
    @Column({
        nullable: true,
        comment: 'MyComment' // <---
    })
    my_field: string;

How do I add a comment to reference types?
    @ManyToOne(type => Appeal, appeal => appeal.callphoneIdappeals, {
        nullable: true
    })
    @JoinColumn({ name: 'idappeal' })
    appeal: Appeal;

**Comment by pleerock** [comment]
You can create a column with the same name and attach comment to it:

```ts
@column({
nullable: true,
comment: 'MyComment' // <---
})
my_field: string;


@Column({ nullable: true, comment: 'your comment' })
idappeal: number;

How do I add a comment to reference types?
@manytoone(type => Appeal, appeal => appeal.callphoneIdappeals, {
nullable: true
})
@joincolumn({ name: 'idappeal' })
appeal: Appeal;
```

p.s. please format your code properly.

**Comment by nikolay-rogovoy** [comment]
Thank you so much!

**Comment by JeetChaudhari** [comment]
How to add a comment on relations? I tried
```
@manytoone(type => Appeal, appeal => appeal.callphoneIdappeals, {
comment: 'my comment'
})
```

but typescript shows error.

**Comment by greenkarmic** [comment]
Is there really still no other way to add a comment to a reference field then duplicating the column?
