### ISSUE TITLE
Publish entities as package

### ISSUE THREAD

**Issue by enko** [typeorm/typeorm#2302]
**Issue type:**

[X] question

**TypeORM version:**

[X] `latest`

Is it possible to put entities that are shared by all our backends into a npm package?

We have some entities like a common base or user management that are common to most of our backends and would like to publish it to npm so we don't have to copy the files into every backend project.

**Comment by pleerock** [comment]
I don't see any technical limitations, I think you can.

**Comment by enko** [comment]
My mistake was, that i tried to to require the source files and not the compiled dist folder:

```
...
   "entities": [
      "node_modules/backend-base-entities/src/models/**/*.ts"
   ],
...
```

vs

```
...
   "entities": [
      "node_modules/backend-base-entities/dist/models/**/*.js"
   ],
...
```
