### ISSUE TITLE
@Depends Decorator or change detection

### ISSUE THREAD

**Issue by totalard** [typeorm/typeorm#2306]
**Issue type:**

[ ] question
[ ] bug report
[X ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ x] `@next`
[ ] `0.x.x` (or put your version here)

I have worked With Odoo and found one of the feature of them is better and effective... I didn't found it here.. It is really good.

Within an example you can find what I am expecting

@depends('student_id.balance','amount')
Some functions.......

Here every time the Decorator checks for any changes in the entity field mentioned OR MENTIONED RELATED FIELD..  It call certain Function...
That is. A field in current entity is strictly depends current entity field or related entity field... 

Help please

**Comment by pleerock** [comment]
Describe your proposal in more details. Its not clear what exactly this decorator is going to do.

**Comment by totalard** [comment]
This decorator will trigger the call to the decorated function if any of the fields specified in the decorator is altered by ORM

**Comment by pleerock** [comment]
Please provide a **detailed proposal** on how this feature must work and used. I still have no complete picture of what you are suggesting.

**Comment by totalard** [comment]
`import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;
   
    @Column()
    fullName: string;

    @Column()
    isActive: boolean;
    
    @depends('firstName','lastName')
     updateName(){
      this.fullname = this.firstName + this.lastName
     }
}
`


This is Sufficient To Understand.

**Comment by pleerock** [comment]
There is a `@BeforeUpdate` listener that you can use to do basically the same:

```ts
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

@entity()
export class User {

@PrimaryGeneratedColumn()
id: number;

@Column()
firstName: string;

@Column()
lastName: string;

@Column()
fullName: string;

@Column()
isActive: boolean;

@BeforeUpdate()
 updateName()
  this.fullname = this.firstName + this.lastName
 }
}
```

 you can check inside whatever you want, but you won't probably need to check first name or last name if they changed - because if they are not changed fullname will be same and orm will not update this column anyway.

**Comment by totalard** [comment]
There is something I need more, mentioned in first of this conversation.. check example

`import {Entity, PrimaryGeneratedColumn, Column, OneToMany} from "typeorm";
import {Photo} from "./Photo";

@Entity()
export class User {
    
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    name: string;
    
    @OneToMany(type => Photo, photo => photo.user)
    photos: Photo[];
    
  @depends('photos.name','name') //check the relation field has change
 updateName(){
  //Some Work Here.... Not a Important Matter
 }
}`

**Comment by totalard** [comment]
I didnt Recieved The required Answer.. The @BeforeUpdate() only works on own fields. Not The related Field.. I want a decorator which works only if mentioned fields or related fields Modified.

**Comment by totalard** [comment]
Anybody There, In Future Plan?

**Comment by havenchyk** [comment]
@totalard hey, thanks for the proposal. Even if your idea is fine and makes sense, you seem to be the only person who needs this feature at the moment, but the capacity of contributors is not infinite, so you can try to implement this by yourself or at least do some investigation of what parts of code need to be changed to make the change you want possible.

https://github.com/typeorm/typeorm/issues/3267#issue-391607316

**Comment by totalard** [comment]
Will Try

**Comment by pleerock** [comment]
Im going to close this one to keep issues organized since we aren't planning to implement it. If we notice other people reports with similar idea we'll open one of them with references to others.

**Comment by androettop** [comment]
I have also worked with odoo and this seems like a good proposal

**Comment by cdoukoure** [comment]
Hi everyone, it also a feature I think is very interesting.

For example, we have 3 entities

`
@entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    fullName: string;
    
    @OneToMany(type => Tool , t => t.user, { nullable: true })
    tools: Tool [];

}

@entity()
export class Tool {

    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    fullName: string;
    
    @ManyToOne(type => User, u => u.tools, { nullable: true })
    user: User;

    @OneToMany(type => UserLog, t => t.tool)
    userLogs: UserLog[];

    @Depends('user') //check the relation field has change
    createLog(){
        // For example
        /** Each time user change, we create a new  UserLog() with the previous user **/
    }

}

@entity()
export class UserLog {

    @PrimaryGeneratedColumn()
    id: number;
    
    @CreateColumn()
    date: string;
    
    @ManyToOne(type => Tool , t => t.userLogs)
    tool: Tool;    

    @ManyToOne(type => User)
    user: User;

}

`

So each time user change in Tool, it automatically create UserLog.

Actually, in @BeforeUpdate we do this in subscriber by tool = await getRepository(Tool).findOne(id, {relations: ['user']})
And we compare dto.user != tool.user, 
And etc..

Having this feature can reduce boileplate in code and help us make the code DRY.

Please check.

Thank !!!



Please check it.
