### ISSUE TITLE
relation update CASCADE problen

### ISSUE THREAD

**Issue by lalalalaluk** [typeorm/typeorm#2307]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[^2.0.0 ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have two table.
One is userBasic and other is userextensions
userBasic is onetomany to userextensions
when I use repository save method to update userBasic and userextensions
I got 
`error
:
"ER_BAD_NULL_ERROR: Column 'fk_id' cannot be null"`

they have relations  below

```
@Entity("UserBasic")
export class UserBasic {

    // @Column("int",{ 
    //     generated:true,
    //     nullable:false,
    //     primary:true,
    //     name:"id"
    //     })
    @PrimaryGeneratedColumn()
    id: number;

....

    @OneToMany(type => UserExtension, userextensions => userextensions.fk_id,
        {
            cascade: true,
            onDelete: "CASCADE",
            onUpdate: "CASCADE",
        })
    userextensions: UserExtension[];

}

```

```
@Entity("UserExtension")
@Index("FK_id",["fk_id",])
export class UserExtension {

    @PrimaryGeneratedColumn()
    id:number;
        

   
    @ManyToOne(type => UserBasic, fk_id => fk_id.userextensions)
    @JoinColumn({ name:'fk_id'})
    fk_id:UserBasic;
    
  .....

    @Column("tinyint",{ 
        nullable:true,
        default:"NULL",
        name:"K_Delete"
        })
    K_Delete:number;
```

I update with
`await this.userBasicRepository.save(newValue);`

console.log(newValue) is below
```
  {id: 1,
  Name: 'Luxa',
  ID_No: 'J9aaaa',
  userextensions:
   [ { id: 112,
       Admit_Type: 'aa2ff',
       Unit: 'sa',
       Title: 'bbb',
     { id: 139,
       Admit_Type: 'a',
       Unit: 'a',
       Title: null,
     { id: null,
       Admit_Type: 'ff',
       Unit: null,' } ] }
```

Is there anything I mistake?
Thx!

**Comment by pleerock** [comment]
Join column name and relation name must be different. Why do you call userBasic fk_id?

```ts
    @JoinColumn({ name:'fk_id'})
    fk_id:UserBasic;
```

Also you don't need this index `@Index("FK_id",["fk_id",])`.

Your mistake is your naming strategy. Everything looks ugly.
