### ISSUE TITLE
leftJoinAndMapOne partial select

### ISSUE THREAD

**Issue by cometta** [typeorm/typeorm#2308]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is it possible to do partial select when using leftJoinAndMapOne  ? It seems to return all fields

**Comment by rolandvar** [comment]
any news about it?
