### ISSUE TITLE
Lazy loading with eager loading in combination doesn't work

### ISSUE THREAD

**Issue by IonelLupu** [typeorm/typeorm#2315]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.5` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Giving the below entities;
```ts
class User extends BaseEntity{
    @OneToMany(type => Reservation, reservation => reservation.client)
    reservations: Promise<Reservation[]>;
}

class Reservation extends BaseEntity{
    @ManyToOne(type => Hotel, hotel => hotel.reservations, {eager: true})
    hotel: Hotel;

    @ManyToOne(type => User, user => user.reservations, {eager: true})
    user: User;
}

class Hotel extends BaseEntity{
    @OneToMany(type => Reservation, reservation => reservation.hotel)
    reservations: Promise<Reservation[]>;
}
```

Doing `User.find(1).reservations`  returns a list of reservations but without any eagerly loaded relations(for Hotel and User). 

I know there is some redundancy because the `User` under the `Reservation` is the same, but what I really want are the hotels (and if I request using some hotel, like `hotel.reservations` what I really I want are the users. But it's ok if there is some redundancy)

Doing `Reservation.find(1)` returns the expected result.

1. Is this intended behavior?
2. How can I get the expected result without manually getting every reservation and then load their relationships? Like:
```ts
let user = User.find(1).
let reservations = users.reservations;
reservations.forEach((reservation)=>{
    reservation.user...// load the relations somehow using query builder???.  this is really messy
    ....
})
```
The `Reservation.find(1)` works just fine and `User.find(1).reservations`  should also.

**Comment by JCWolf** [comment]
Anyone?

**Comment by MarkMatute** [comment]
await user.reservations ?

**Comment by MarkMatute** [comment]
@JCWolf let me know if this worked.

**Comment by pleerock** [comment]
You can't mix eager and lazy relations. Use one of them on both sides.

**Comment by JCWolf** [comment]
@pleerock, why I can't mix them? I wanted to use just one but my current configuration doesn't allow me that. :(

**Comment by JCWolf** [comment]
I am trying to get rid of the query builder as much as possible and use Active Record for simple queries like this. Why? I want the code to be simpler, more readable and easier to understand. The query builder looks redundant for these types of queries. Yes, it is OK for complex queries but for this I find it not needed.

For example this query:

```ts
const userId = await getRepository(User)
    .createQueryBuilder("user")
    .select("user.id")
    .where("user.id = :id", { id: 1 })
    .getRawOne();
// here, the word user is written 4 times
```

It would be nice to just write:
```ts
const photosSums = User.where('id',1).getRawOne('id')
// the `.where` will create a query parameter automatically
```

or
```ts
const users = await getRepository(User)
    .createQueryBuilder("user")
    .leftJoinAndSelect("user.photos", "photo")
    .where("user.group = :id", { id: 1 })
    .where("photo.album = :album", { album: 3 })
    .getMany();
```
Can be written like this maybe?:
```ts
const users = User
    .where('group',1) // get users that have the column group = 1
    .with({
        'photos': photo => photo.where('album',3) // eager loaded. `photo` is a query builder. here we have the full power of a query builder
    })
    .getMany()
// the `.with` for example will get the relationships. the `photo` argument is a query builder maybe?
```

I am just borrowing syntax from Laravel's Eloquent ORM. It just an idea to make it work easier with Active Record as I said in #2285.

**Comment by pleerock** [comment]
Using lazy relations for this purpose is a bad idea. Really, really better to contribute into ORM and add needed features 😆

**Comment by jckw** [comment]
Why is this a "really bad idea"?

**Comment by jronnybravo** [comment]
@pleerock I am not sure why it's a bad idea, can you explain further?

As for it being a good idea, it's very useful when one needs to get related items especially when they are circular. Laravel's Eloquent can do both lazy loading (by default) and use the function `with` for eager loading... Can we reconsider this approach? Thanks.

**Comment by npeham** [comment]
Why is this closed? Why are lazy-loaded relations bad / an anti-pattern?

**Comment by johannesschobel** [comment]
i also stumbled upon this thread - can you give more details about this issue please?
@IonelLupu : how did you manage to solve / work around your issue?

All the best and thanks a lot for your help

**Comment by IonelLupu** [comment]
@johannespfeiffer no, sorry :(

**Comment by venarius** [comment]
Any news on this?

**Comment by xenoterracide** [comment]
hmm... I suspect this may be my issue... lame

**Comment by fixpunkt** [comment]
It would be really nice to have an explanation of why this isn't supported (and why it seems to be considered a bad idea) here. Also, the docs should probably mention that this doesn't work.
