### ISSUE TITLE
[Question] Why is the relation count decorator deprecated?

### ISSUE THREAD

**Issue by marano** [typeorm/typeorm#2317]
I am in need of just that, but noticed that it is not documented and there is a deprecation message on the source.

**Comment by pleerock** [comment]
it does not work well, has multiple issues in different scenarios and is not flexible at all.

it was just experimental. you can simply execute a query manually and write a result into your model.

**Comment by marano** [comment]
@pleerock Thank you for your response.

**Comment by pie6k** [comment]
Could you write some example of how to write such query that would load count of relation without loading any other data?
