### ISSUE TITLE
Program only runs START TRANSACTION - COMMIT

### ISSUE THREAD

**Issue by Haxified1** [typeorm/typeorm#2322]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When I run my program, typeorm only runs 
```
START TRANSACTION
COMMIT
```
createConnection() doesn't produce any errors.

Any help would be appreciated! Thanks

**Comment by pleerock** [comment]
yeah but what is an issue? Please provide a reproduction repo and let us know what exact issue you have

**Comment by Haxified1** [comment]
Never mind, I'm stupid. Found the error.
