### ISSUE TITLE
Partial select a related entity via queryBuilder

### ISSUE THREAD

**Issue by kodayashi** [typeorm/typeorm#2325]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I read through the query builder docs and couldn't quite figure out if the case below is supported:

* User Entity
-- has an id, age and profilePhotoId
-- profilePhotoId is a one-to-one on ProfilePhoto entity (each user has unique profile photo)

* ProfilePhoto Entity
-- has an id and userId
-- userId is a one-to-one on User entity (each profilePhoto has a unique user)

I can build a query to select all users over the age of 18 and load the profile photo relation. That returns an array of UserEntity[] with a profilePhoto entity in each user entity.

However, I'd like to select on users but have the response be *only* the array of ProfilePhoto[] entities associated with the users found in the search. Something like:

```javascript
const profilePhotos: ProfilePhoto[] = await createQueryBuilder("user")
    .select(user.profilePhoto) // just deserialize the ProfilePhoto in the user
    .where("user.age > 18") // filtered set of users
    .leftJoinAndSelect(ProfilePhoto, "profilePhoto", "profilePhoto.userId = user.id") // Get all the ProfilePhoto info
    .getMany(); // looking for an array of ProfilePhoto[]
```

Is it possible to have the queryBuilder return an entity other than the table it's selecting on by "filtering" the proper relation?

**Comment by kodayashi** [comment]
Thanks @pleerock, can I use the repository pattern as well? Something like:

```javascript
const profilePhotos: ProfilePhoto[] = await this.userRepository.find({
  select: ["user.profilePhoto"],
  relations: ["profilePhoto"],
});

**Comment by pleerock** [comment]
yes but you don't need to do ` select: ["user.profilePhoto"]` there

**Comment by kodayashi** [comment]
Oh ok, without the select, I figured I would get an array of User[] back, witch each user having the hydrated ProfilePhoto. I will try that out thanks!

**Comment by kodayashi** [comment]
Here's another example (essentially what I have in code):

```javascript
@Entity('users')
export class UserEntity {
  @PrimaryGeneratedColumn('uuid')
  readonly id: string;

  @Column('uuid')
  groupId: string;

  @ManyToOne(type => GroupEntity, group => group.users, { primary: true })
  @JoinColumn({ name: 'groupId'})
  group: GroupEntity;
}```

```javascript
@Entity('groups')
export class GroupEntity {
  @PrimaryGeneratedColumn('uuid')
  readonly id: string;

  @Column()
  name: string;

  @OneToMany(type => UserEntity, user => user.group)
  users: UserEntity[];
}```

I just want to get an array of GroupEntity[] that a user is in (given their id). This query works if I run it manually:

`select "groups".* from "users"  left join "groups" on "users"."groupId" = "group"."id";

**Comment by kodayashi** [comment]
One of the issues I'm seeing is that, with the repository pattern, you can only return entities of that type. The query above uses the users repository but only returns columns in the groups table. I can't cast the response `as GroupEntity` using the user repository.

**Comment by pleerock** [comment]
> With just the relations option, I get the full User entity and the associated ProfilePhoto entity is just hydrated

correct behaviour. 

>  instead of just the profilePhotoId.

if you want to get `profilePhotoId` from `user` you don't need to select a relation, simply add `@Column({ nullable: true }) profilePhotoId` into user entity and it will be always selected you don't need to specify any other options.
