### ISSUE TITLE
Readonly PrimaryGeneratedColumn()

### ISSUE THREAD

**Issue by rmuchall** [typeorm/typeorm#2326]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Would it be possible to mark PrimaryGeneratedColumn() as read only?
Thanks!

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by dawid-pstrak-rmtcfm-com** [comment]
Was looking for solution for this and i think best option for now is to pass exact parameters that you want to update to repository method like
```
await this.usersRepository.update(id, { email });
```
