### ISSUE TITLE
has-many-through relation

### ISSUE THREAD

**Issue by ph55** [typeorm/typeorm#2328]
**Issue type:**
[V] question

**Database system/driver:**
[V] `mysql`

**TypeORM version:**
[V] `latest`

I have 3 tables:
`profile` (id, name...)
`package` (id, name...)
`profile_package` (id, packageId, profileId)

Profile could have many packages.

Is there any way to make such relation ?
`profile.packages` should return `Package[]` and not `ProfilePackage[]`

**Comment by ingun37** [comment]
So it's like HasManyThrouh from Loopback
I don't think TypeORM support such relation so Ive made one for myself like this
```
class A
OneToMany B[]

class B
ManyToOne A
ManyToOne C

class C
OneToMany B

It works pretty much like HasManyThrough

**Comment by ph55** [comment]
But you probably do `a.b.c` to get it.
And I want straight `a.c`

**Comment by ingun37** [comment]
You should make your question more clear.
Whether you want LoopBack's HasManyThrough-like relation,
or ManyToMany relation using custom table(not the table TypeORM automatically makes for you)
or you are using HasManyThrough by meaning of ManyToMany because as to your definition of profile_package class, theres no point of using HasManyThrough relation

**Comment by pleerock** [comment]
From what I see from the request you need to create a many-to-many relation, second side of which references to two columns: packageId, profileId. You can do it using `@JoinTable` decorator and provide column. Here is a short example of such relation:

```ts


    @ManyToMany(type => Category, category => category.tagsWithOptions)
    @JoinTable({
        name: "tag_categories",
        joinColumns: [{
            name: "tagTitle",
            referencedColumnName: "title"
        }, {
            name: "tagDescription",
            referencedColumnName: "description"
        }],
        inverseJoinColumns: [{
            name: "categoryName",
            referencedColumnName: "name"
        }, {
            name: "categoryType",
            referencedColumnName: "type"
        }]
    })
    categories: Category[];
```

**Comment by ph55** [comment]
> From what I see from the request you need to create a many-to-many relation

No, its one-to-many

I give up.
`hasManyThrough` is commonly used pattern. I don't know why and how I should explain it further.

http://docs.sequelizejs.com/manual/tutorial/associations.html#belongs-to-many-associations
https://laravel.com/docs/5.6/eloquent-relationships#has-many-through

---
User has many projects.

```
User
| id | username |  email  |
|----+----------+---------|
|    |          |         |

Project
| id | title | tag |
|----+-------+-----|
|    |       |     |

UserProject
| id | content | userId | projectId  |
|----+---------+--------+------------|
|    |         |        |            |
```

**Comment by ph55** [comment]
Well I'm stupid.
It's many-to-many and explained in docs -
http://typeorm.io/#/many-to-many-relations

**Comment by ashishpatel6958** [comment]
anyone found it's answer? has-many-through relation

**Comment by ryskin** [comment]
I was surprised it's absent, in ruby on rails I used it much
For example:
**Order** has_many **Patients**
**Patient** belongs_to **Service**

I want to get **order.services** 
Every time I need to get order patients then get service from each.

Very good explaining here:
https://guides.rubyonrails.org/images/association_basics/has_many_through.png

**Comment by avetisk** [comment]
Indeed, many other ORMs have it, for instance objection.js:

https://vincit.github.io/objection.js/api/types/#type-relationthrough
https://vincit.github.io/objection.js/api/model/static-properties.html#static-hasonethroughrelation

I wonder if there's a simple way to handle this with existing relation decorators or it's literally impossible? 🤔

**Comment by mmahalwy** [comment]
@pleerock wondering if there is any update on this? I think the `@JoinTable` works if there are no additional fields on the joining table. It is possible to do `@JoinTable` with an entity?
