### ISSUE TITLE
handle case iensitivity in postgreSQL

### ISSUE THREAD

**Issue by foisonocean** [typeorm/typeorm#2330]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm facing the same issue like in the [blog](https://blog.xojo.com/2016/09/28/about-postgresql-case-sensitivity/), can you guys improve this?

**Comment by pleerock** [comment]
There are no issues with case inesitivity of postgres in typeorm. So, you probably do something wrong.

**Comment by foisonocean** [comment]
Here are my error and my code:

![image](https://user-images.githubusercontent.com/15059605/41349434-7302b02a-6f42-11e8-9320-402699fc4268.png)

```typescript
const r = await connection
    .getRepository(SpaceMember)
    .createQueryBuilder('space_member')
    .where('space_member.spaceId IN (:...spaceIds)', {spaceIds: [8, 9]})
    .getMany();
console.dir(r);
```

**Comment by foisonocean** [comment]
@pleerock Could you have a look and see where is wrong?

**Comment by pleerock** [comment]
> 'space_member.spaceId

you shall use columns and relations defined in your entity if you want automatic escaping,try to change it to `space_member.space IN (:...spaceIds)'`

**Comment by foisonocean** [comment]
@pleerock yes this works
