### ISSUE TITLE
Inconsistent handling of "undefined" between save() and update()

### ISSUE THREAD

**Issue by hallsbyra** [typeorm/typeorm#2331]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

If I `update` a nullable column with `undefined`, the value is changed to `null`.

This passes:
```
        // Given
        await testFixture.companyRepo.save(dummy.company({id: "C0", logo: Buffer.from("test", "base64")}))

        // When
        await testFixture.companyRepo.update("C0", {logo: undefined})

        // Then
        const c1 = await testFixture.companyRepo.findOneOrFail("C0")
        expect(c1.logo).to.be.null
```

If I instead `save` a nullable column with `undefined`, the value is not changed.

This also passes:

```
        // Given
        await testFixture.companyRepo.save(dummy.company({id: "C0", logo: Buffer.from("test", "base64")}))

        // When
        const c1 = await testFixture.companyRepo.findOneOrFail("C0")
        c1.logo = undefined
        await testFixture.companyRepo.save(c1)

        // Then
        const c2 = await testFixture.companyRepo.findOneOrFail("C0")
        expect(c2.logo).to.not.be.null
```

I think the behavior of `save` is more semantically correct.

**Comment by pleerock** [comment]
You are right, `update` shall ignore the undefined values as well. Feel free to contribute BTW.

**Comment by gao-sun** [comment]
Is there any update on this?

**Comment by filipsuk** [comment]
seems to be still an issue

**Comment by jamie3** [comment]
2 years old? Seems like a good bug to fix.

**Comment by albertcito** [comment]
3 years old? Seems like a good bug to fix.

**Comment by imnotjames** [comment]
Feel free to contribute.
