### ISSUE TITLE
Q: Is one to one and other relations indexed?

### ISSUE THREAD

**Issue by jas99** [typeorm/typeorm#2334]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Can/Do I have to use `@index()` on property, or its automatically handled by database?

Thx

**Comment by pleerock** [comment]
probably question to your database. But as i know most of database already kinda implement indices on foreign keys and you kinda don't need to apply index on it.
