### ISSUE TITLE
Add HTTPS support to typeorm.io

### ISSUE THREAD

**Issue by RodrigoLeiteF** [typeorm/typeorm#2335]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

https://doesmysiteneedhttps.com/

**Comment by MatthiasKunnen** [comment]
GitHub pages support HTTPS on a custom domain. See https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ and https://help.github.com/articles/setting-up-an-apex-domain/

According to these links above, limited steps need to be taken.

**Comment by gintsgints** [comment]
@pleerock All should work by creating CNAME file on repo and creating CNAME DNS record.
https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by gintsgints** [comment]
Ahh I see, you did it already :(

**Comment by vlapo** [comment]
I think you have to update `A` records for `typeorm.io` - https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider

**Comment by pleerock** [comment]
yeah we already have A record in repository. I already bought certificate but don't know how to connect it with github

**Comment by vlapo** [comment]
We do not need buy any certificate. Github is providing free certificates also for custom domains connected to github page (they are using lets encrypt) as it is described here https://blog.github.com/2018-05-01-github-pages-custom-domains-https/.

You have to just add A records to IPs:
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```
and remove and again add custom domain as it is described in https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider step 4 :)

**Comment by vlapo** [comment]
Looks like we are HTTPS positive now :) What was a problem @pleerock ?

**Comment by pleerock** [comment]
Actually I already brought a certificate. I spoke with technical support who issued me that certificate and they told me that github doesn't support third-party certificate. Then I just followed [this nice](https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc) tutorial and setup it :)

**Comment by MatthiasKunnen** [comment]
That tutorial seems to state that flexible SSL is used. This means that the traffic between CloudFlare and the servers serving typeorm.io is not secured.

I'm curious why you decided to use a 3rd party provider (CloudFlare) and your own certificate while GitHub supports HTTPS on custom domains for free out of the box. Even if you already bought the certificate, using GitHub's built-in HTTPS support will be cheaper as you don't have to renew it.

Do the steps described in my previous comment not work?
> GitHub pages support HTTPS on a custom domain. See https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ and https://help.github.com/articles/setting-up-an-apex-domain/

Pay special attention to step 4 of the apex domain setup

> Add your custom domain to your GitHub Pages site. If you're updating an existing custom domain, first remove and then re-add your custom domain to your GitHub account to trigger the process of enabling HTTPS. For more information, see "[Adding or removing a custom domain for your GitHub Pages site.](https://help.github.com/en/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site)"
