### ISSUE TITLE
Extend entities in runtime

### ISSUE THREAD

**Issue by dotansimha** [typeorm/typeorm#2336]
I would like to suggest an issue that has been discussed here before, but still not resolved yet.

The goal of my idea is to allow extensibility of the ORM entities using `@Entity` declaration.

The goal is to add naming to entities and then to separate it's declaration to smaller pieces.

Suggested API:

// Base entity
```
@Entity({ name: 'user' })
class BaseUser {
    @Column()
    name: String;
}
```

// Extension A 
```
@Entity({ name: 'user' })
class UserWithProfile {
    @Column()
    profile: Profile;
}
```

// Extension AB
```
@Entity({ name: 'user' })
class UserWithAge {
    @Column()
    age: number;
}
```

Each declaration should let the user to access the entire `User` object, and access all of the fields that has been declared before or after. The merge between the entities will occur during runtime (using `entities: [ ... ]`), and they will be merged by a unique specifier (for example, `name`).
For example, if a user tries to save using `BaseUser`, all of the validations and ORM rules that relevant to `BaseUser`+`UserWithProfile`+`UserWithAge` will be executed (just like one big entity).
A fetch using the ORM will transform and return all of the fields. So a `find` execution using `getRepository(BaseUser)` will be the same as `getRepository(UserWithProfile)`.

I belive that this feature will also let you in the future the ability to separate between the core ORM logic and the TypeScript decorators, because of the fact that entities will be identified by a name and not by a class with a decorator.
It will also allow user to extend entities without the need for inheritance, and without the need to couple between the classes.

**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Comment by pleerock** [comment]
I would like to point that this feature can be implemented only with entity schemas as we discussed earlier.

**Comment by imnotjames** [comment]
This has seen little traction for several years.  I'd like to close it as I don't see it being implemented in the near future.
