### ISSUE TITLE
Generate/Export .d.ts Files on TS Complilation

### ISSUE THREAD

**Issue by joshrathke** [typeorm/typeorm#2337]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

I have spent the last several months using TypeORM within an Express API that serves up an Angular application and have run up against build problems when trying to reference the TypeORM Entities directly at times. Primarily these problems stem from the two projects being their own NPM Projects and thus having their own TypeScript environments as well.

Has there been any thought/attempts made towards a "Generate/Export .d.ts Files" feature that would automatically generate .d.ts files based on the current Entities within the system? These could then be referenced by an Angular (or any other Typescript) application without having to jump through a bunch of hoops due to overlapping TS Environments.

**Comment by pleerock** [comment]
this feature isn't tight to typeorm. it can be any other tool that generates interfaces from exist typescript classes. 

Architectures can be different, some people prefer reuse entities on multiple projects (lets say on the frontend), some people like me prefer not to do it (duplication is less pricy then multiple issues and limitations come from first approach most of times in my honest opinion), some people prefer create interfaces manually and use them across all projects, and then define entities like this: `class PostEntity implements Post` where `Post` is an entity.

For example I did even something different in my last project - I have a `graphql models`, I generate interfaces from those models, then I have entity with a different name, e.g. PostEntity that implements that generated interface, and on the frontend (e.g. different clients) I use generated entities.

**Comment by joshrathke** [comment]
For sure. I agree with you. I was just curious what the thoughts were on even a basic implementation. But that makes sense.

**Comment by pleerock** [comment]
I guess I can close this issue.
