### ISSUE TITLE
confusing command line 

### ISSUE THREAD

**Issue by ktwbc** [typeorm/typeorm#2339]
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I would actually vote to change this behavior but at least should be spelled out more clearly. When using the CLI, you can use the -f command to specify an alternate configuration file.

The normal expectation would be a complete filename, such as

ts-node ./node_modules/typeorm/cli.js schema:sync -c test-connection -f ormconfig-local.yml

However, the system is set up to expect no extension on the file (it rotates and checks for all possibilities), and including the extension gives the error "Error: No connection options were found in any of configurations file."

I would propose that manually specifying a file would normally include the extension and that should be allowed to work with TypeORM.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
PRs on documentation and CLI commands documentation are welcomed
