### ISSUE TITLE
Remove method on entity not working properly 

### ISSUE THREAD

**Issue by ukaric** [typeorm/typeorm#2343]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

Hi I have done some digging and cant seem to make `remove()` work as expected.

I have entity setup like so.
```ts

import {
  Entity,
  Column,
  PrimaryColumn,
  BeforeInsert,
  BaseEntity
} from 'typeorm'
import { v4 } from 'uuid'

@Entity()
export class Entry extends BaseEntity {
  @PrimaryColumn('uuid') id: string

  @Column('varchar', { length: 255 })
  firstName: string

  @Column('varchar', { length: 255 })
  lastName: string

  @Column('varchar', { length: 30, nullable: false, unique: true })
  telephone: String

  @BeforeInsert()
  addId() {
    this.id = v4()
  }
}
```

Since I'm using GraphQL my schema file is.

```graphql

type Mutation {
  deleteEntry(id: String!): Boolean
}


```

I'm using GraphQL and my resolvers for removing entity goes like this.

```ts

  Mutation: {
    deleteEntry: async (_, { id }: GQL.IDeleteEntryOnMutationArguments) => {
      try {
        // This is working
        // await Entry.remove(Entry.create({ id }))

        // This is not working
        const entry = await Entry.findOne({ id })
        console.log(entry)
        await Entry.remove(entry)

        return true
      } catch (error) {
        console.log(error)
        return false
      }
    }
  }
```

I'm fairly new to TS altogether I followed the official doc [here](http://typeorm.io/#/) where they try

```ts
import {createConnection} from "typeorm";
import {Photo} from "./entity/Photo";

createConnection(/*...*/).then(async connection => {

    /*...*/
    let photoToRemove = await photoRepository.findOne(1);
    await photoRepository.remove(photoToRemove);

}).catch(error => console.log(error));
```

And it is working. While I get following error 

```
error TS2345: Argument of type 'Entry | undefined' is not assignable to parameter of type 'BaseEntity'.
  Type 'undefined' is not assignable to type 'BaseEntity'.
```
It is probably silly question but I feel like `remove()` is not documented enough or perhaps I don't understand library well enough. I feel like documentation should be organized better with more solid examples to follow.

Also if there is interest I will share complete repo to reproduce the issue.

Thanks in advance.

**Comment by mrnagydavid** [comment]
This is a typescript feature.

It is because the find*() functions return an Entity OR undefined. So when you try to call remove() on something that might be an object but just might as well be undefined, Typescript warns you that the variable might be undefined and then there would be no remove method in it either.

```
        const entry = await Entry.findOne({ id })  // entry might be Entry, might be undefined
        console.log(entry)
        await Entry.remove(entry!) // ! is a non-null assertion operator telling TS that you are sure that it is not undefined
```

But you shouldn't be sure, you should ``` if(entry) { ... /* remove */ }```

**Comment by pleerock** [comment]
as @mrnagydavid mentioned its typescript **feature**. You can disable it by setting `strict: false` in your compiler options, or surround it with `if` or add hacky "!"

**Comment by ukaric** [comment]
Thanks, it is TS after all will have to sit trough it until I get proficient enough in it solved it with `if` check.
