### ISSUE TITLE
Data loss warning when field is removed from Entity and the column already contained data

### ISSUE THREAD

**Issue by basvdijk** [typeorm/typeorm#2344]
**Issue type:**

[ ] question
[ ] bug report
[X ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am not sure if this is by design or a bug:
Create an entity with two fields, doesn't matter which fields. Keep `synchronize` set to `true`. Now run the program, it will create two columns in the table. Insert some data in the table.

Next remove 1 field from the entity, and run again. The field is gone, together with the data in the column without any warning.

Entity has data loss protection for this. Now one mistake in the entity fields could lead to dataloss without warning.

**Comment by pleerock** [comment]
it is by design and it is called a schema synchronization which you explicitly enable. Working with schema is always a responsible work, so you should know what you are doing by explicitly enabling synchronization. In the case if you wan't to control something you can enable logging and always check what queries are executing for your actions in the entity.

**Comment by basvdijk** [comment]
@pleerock I still think a safeguard to prevent "mistakes" by having an explicit confirmation when data will go loss and not remove data by default without a prompt. Especially with these delicate operations.   

When you delete a file on your computer, you are prompted as well. The `rm` command a has a force parameter to skip the prompt and not a parameter to invoke a prompt. But neither of these remove without prompt by default. The Entity Framework doesn't remove data unless it is forced to.

I would ask you with the arguments above in mind to reconsider the design. Thanks :)

**Comment by pleerock** [comment]
Thanks for the suggestion, but the answer would be no.

If we talk about synchronize option in config, then its not possible to "prompt" something. If we talk about CLI then there are two commands - `schema:log` to see what queries and gonna execute and `schema:sync` to do that.

**Comment by basvdijk** [comment]
Ah I see, I was just about to propose to implement a 'dry run' option, didn't know about`schema:log` :)

Does `schema:log` show a warning about data loss?

How do you invoke this command? I've tried `nest schema:log` but it gave me an empty output.

**Comment by pleerock** [comment]
it won't show you warning about "data loss", it shows you queries it gonna execute. If you want DROP COLUMN it means you will have data loss in the case if you have data in those columns.

I don't know about nest, try using typeorm cli directly.

**Comment by basvdijk** [comment]
Ok, thanks so far for your help!

**Comment by GarryOne** [comment]
@basvdijk I also faced this problem, even when I was using Doctrine's `schema:update --force`. 
I think this issue can be handled at CI/CD pipeline with a command like this. Didn't tested it, just wanted to show the idea.
```
npm run typeorm schema:log | grep "DROP " && echo "Found data loss. Exiting" && exit
```
