### ISSUE TITLE
`isGenerated` does not work in Migration

### ISSUE THREAD

**Issue by nterthedesi** [typeorm/typeorm#2348]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

https://github.com/nterthedesi/typeorm-isgenerated

**Migration script**

```ts
import { MigrationInterface, Table, QueryRunner } from "typeorm";

export class UserInit1529258015467 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.createTable(new Table({
      name: "product",
      columns: [
        {
          name: "id",
          type: "int",
          isGenerated: true,
          isPrimary: true,
        },
      ],
    }))
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
  }
}
```

**Expected Outcome**
```sql
CREATE TABLE `product` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Actual Outcome**
```sql
CREATE TABLE `product` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
please set `generationStrategy` as well.

**Comment by nterthedesi** [comment]
```ts
generationStrategy: 'increment'
```
it works perfectly.
