### ISSUE TITLE
Support for S3?

### ISSUE THREAD

**Issue by patran** [typeorm/typeorm#2349]
Is there a plan to support S3 as the database in such away that AWS Athena can query it?

**Issue type:**

[ ] question
[ ] bug report
[ X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
No, currently we don't have such plans. We mostly support relational databases. But feel free to contribute.

**Comment by pleerock** [comment]
As it was mentioned multiple times we don't have in plans to implement new drivers in a near future. If you want to contribute - please feel free! To keep issues cleaner lets close this one and continue discussion in #4
