### ISSUE TITLE
Missing @DiscriminatorColumn() decorator?

### ISSUE THREAD

**Issue by marcorinck** [typeorm/typeorm#2351]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[X] `cordova` (Ionic 3.9.2)
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest` (0.2.7)
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm currently testing this library and playing around with many features. When trying to use single-table inheritance (copy pasted the entities from the doc here: http://typeorm.io/#/entity-inheritance/single-table-inheritance ) I get this error message when calling createConnection(): 

```` 
Error: Entity Content using single-table inheritance, it should also have a discriminator column. Did you forget to put @DiscriminatorColumn decorator?
 at EntityMetadataValidator.validate (VM1427 vendor.js:190492)
    at VM1427 vendor.js:190477
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (VM1427 vendor.js:190477)
    at Connection.buildMetadatas (VM1427 vendor.js:110248)
    at Connection.<anonymous> (VM1427 vendor.js:109895)
    at step (VM1427 vendor.js:109766)
    at Object.next (VM1427 vendor.js:109747)
    at fulfilled (VM1427 vendor.js:109738)
    at t.invoke (VM1426 polyfills.js:3)
```` 

But there is no DiscriminatorColumn decorator that I can import. And its not mentioned in the docs once. 

I guess that this was somehow refactored in one of the last versions? Because I can see that this worked in older versions.  

When not using single-table inheritance typeorm is working without any problems and I can read/write from the database.

**Comment by psucodervn** [comment]
From version 0.20.0 change log, `@DiscriminatorColumn decorator has been removed, use @TableInheritance options instead now`

You can use:
```
@Entity()
@TableInheritance({
  column: { name: 'type', type: 'varchar' }
})
export class Whatever {
  @Column({ nullable: false })
  type: string;
  ...
}
```

**Comment by pleerock** [comment]
@psucodervn thanks for the answer.

@marcorinck sorry looks like there some legacy left and error isn't proper. Follow @psucodervn and you'll get what you need working.

**Comment by marcorinck** [comment]
thanks for the feedback! Yes that works. 

Can TableInheritance() decorator be used without any options? If not, maybe mark options parameter as non-optional then? 

And another suggestion: I had seen the "column" property of ColumnOptions but didn't understand that this is the dicriminator column definition. Maybe rename "column" to "discriminatorColumn" to make this clearer? The parameter for ChildEntitiy() is already named "discriminatorValue" so it would make sense.

**Comment by pleerock** [comment]
> Can TableInheritance() decorator be used without any options? If not, maybe mark options parameter as non-optional then?

I'll check it and implement your suggestion, thanks

> Maybe rename "column" to "discriminatorColumn"

not sure about this change, too long and ugly. Plus not all people know what "discriminator" actually means... I'll think about it, thank you

**Comment by Kononnable** [comment]
Looks like issue was resolved long time ago.
