### ISSUE TITLE
Retrieving all rows in a Many to Many relationship when only one matches.

### ISSUE THREAD

**Issue by Grimscythe1983** [typeorm/typeorm#2353]
**Issue type:**

[X] question

**Database system/driver:**

[X] `mysql` / `mariadb`

**TypeORM version:**

[X] `latest`

**Steps to reproduce or a small repository showing the problem:**
I am trying to retrieve all the characteristics of a product even when only one of them matches. Product and Characteristic have a Many to Many relationship. Currently I have this method:

```ts
async search(query: string): Promise<Product[]> {

    query = "%" + query + "%";

    return await this.productRepository
        .createQueryBuilder("product")
        .innerJoinAndSelect("product.characteristics", "characteristic")
        .innerJoinAndSelect("product.brand", "brand")
        .innerJoinAndSelect("product.images", "image")
        .where("product.name LIKE :q", { q: query })
        .orWhere("product.origin LIKE :q", { q: query })
        .orWhere("product.description LIKE :q", { q: query })
        .orWhere("product.tag LIKE :q", { q: query })
        .orWhere("image.title LIKE :q", { q: query })
        .orWhere("characteristic.value LIKE :q", { q: query })
        .getMany()
}
```
If I have two characteristics in the product: "foo" and "bar" and I query "foo", I will get all the products that have the "foo" characteristic, but the query does not pull in any remaining characteristics that the product may have. What is the proper way of building this query with TypeORM?

**Comment by pleerock** [comment]
I guess question is what SQL you would like to build. QueryBuilder just helps you to build SQL you want. So, first create a working SQL, then try to implement it using QueryBuilder.

**Comment by Grimscythe1983** [comment]
That was exactly my thought, to be frank. I'll patch something together

**Comment by Grimscythe1983** [comment]
Solved it by doing a self-join, which is simply something new to me. Basically what one needs to do is: do an inner join on the many to many with an alias, "WHERE" it on the alias and then do an inner join and select on the the many to many again. 

The final query then looks like this:

```ts
return await this.productRepository
    .createQueryBuilder("product")
    .innerJoin("product.characteristics", "characteristic1")
    .innerJoinAndSelect("product.brand", "brand")
    .innerJoinAndSelect("product.images", "image")
    .where("product.name LIKE :q", { q: query })
    .orWhere("product.origin LIKE :q", { q: query })
    .orWhere("product.description LIKE :q", { q: query })
    .orWhere("product.tag LIKE :q", { q: query })
    .orWhere("image.title LIKE :q", { q: query })
    .orWhere("characteristic1.value LIKE :q", { q: query })
    .innerJoinAndSelect("product.characteristics", "characteristic")
    .getMany()

```
