### ISSUE TITLE
Change ormconfig behaviour and connection creation design in next TypeORM version

### ISSUE THREAD

**Issue by pleerock** [typeorm/typeorm#2358]
In this issue I want to describe few features I would like to introduce in 0.3.0 

I consider following changes:

1. **remove connection manager and don't manage connections at all. Users will be able to define and manage multiple connections following way:**

```ts
export const defaultConnection = createConnection({ ... });
export const anotherConnection = createConnection({ ... });
export const thirdConnection = createConnection({ ... });
```

2. **remove `getManager`, `getConnection`, `getRepository` and other exported methods, we don't need them, we will be able to simply do following:**

```ts
export const connection = createConnection({ ... }); // same as getConnection()
export const manager = connection.manager; // same as getManager()
export const getRepository<T> = (entity: T) => manager.getRepository(entity); // same as getRepository()
```

This approach fits more JavaScript world then current "connection manager" based approach. 

3. **remove automatic ormconfig loading** 

Not yet sure about this approach yet since CLI needs it, just like it needs `entities` sections of it, but still we need some solution. The best looking solution is to have ormconfig.ts (which compiles to ormconfig.js)

4. **remove support for directory paths in entities, migrations and subscribers options in ormconfig**

There are various issues user face with loading entities by directory path, e.g.

```ts
entites: ["entity/*.js"]
```

Most of issues are related to different compiler options and execution environments. Few examples of problems:

1. If you are using ts-node or similar approach of running typescript code instead of javascript you'll need to use following configuration: `entites: ["entity/*.ts"]`
2. If you are using ts-node for development, but node for production you'll need dynamic configuration or following configuration `entites: ["entity/*{.ts,.js}"]` but this may not work in rare specific cases
3. If you are using outDir of typescript you need to use following configuration: `entites: ["./out-dir/entity/*.js"]`. If you mix outDir, ts-node for development and node for production the situation gets ugly
4. If you remove or rename entity with outDir option enabled users get serious not obvious issues on why they have a wrongly synchronized database schema (they need to manually cleanup outDir directory to resolve this issue)

5. **rename Connection to DataSource and QueryRunner to Connection**

This is a huge change. Currently Connection is a wrong word since it does not establish a real database connection, its just a database source. And QueryRunner is actually is a connection, so I think they should be renamed.

**Comment by posgarou** [comment]
These all sounds like reasonable changes.

If you decide to remove them, it would be helpful to deprecate them for the 0.3.x releases and only take them out in the 0.4.0 release.

**Comment by btxtiger** [comment]
Custom naming strategy gets in conflict with usage of CLI and lib, because .ts config files are not supported by the lib. It is really a usage pain. 
Currently I need a .ts file for CLI usage with ts-node and a (almost similar) .js file + option overriding in the code for custom naming strategy.

**Comment by dmitrirussu** [comment]
@pleerock what about **getCustomRepository**?

**Comment by cfkxzsat** [comment]
Right now createConnection without any arguments use ormconfig.json(more detail in doc),but I wonder if we can assign the config file used by typeorm in createConnection function.

like
```js
createConnection('orm.yml')  // which use orm.yml in the project root directory
```

**Comment by ubershmekel** [comment]
I tried to use ormconfig.js and wasn't able to, I think the entities weren't being discovered correctly.

I ended up writing a `.ts` file that just creates a connection with `synchronize: true`. That's the poor man's `sync` I guess. Doesn't feel too poor though. Perhaps there should be a method called `synchronize` on the connection and avoid trying to make a commandline app out of typeorm?

**Comment by tobiaskraus** [comment]
**keep database connections seperate from project / ORM settings**

#510 got closed and pleerock asked to comment here instead:

For many people (me included) it is important to seperate general ORM configs (git tracked) and secret DB connection configs which is for any host system different (gitignored).

Just like @biels wrote in #510:

>I think the concern here is that (in my opinion) ormconfig.* mixes database connection concerns (ususally dynamically configured) with project related settings (entity, migration locations and info for the cli).
>I would like to commit the latter to the repository while keeping the former out in a separate config file or passed as environment variables. Maybe allowing environment variables to override ormconfig.* would be a good solution.

**Comment by Tyler-V** [comment]
+1 on ormconfig.ts

Currently use a TypeOrmModule.forRootAsync() and provide a ConfigService to get .env config variables off AWS environments. 

Not sure what my work around is and im unable to generate any migrations as I have to embed this configuration in my app.module.ts

**Comment by backbone87** [comment]
the cli could just use the exported connection?
`npx typeorm --connection ./path/to/connection.js#default schema:sync`
or
`npx ts-node --require tsconfig-paths/register ./node_modules/typeorm/cli.js --connection ./path/to/connection.ts#default schema:sync`

where `#default` designates the exported member of the module to use:
```
export default createConnection({ /* ... */ });
export const other = createConnection({ /* ... */ });
```
`#default` can be omitted.
multiple connections be passed to execute command on all of them:
`npx typeorm --connection ./path/to/connection.js --connection ./path/to/connection.js#other schema:sync`

**Comment by xxRockOnxx** [comment]
Any updates regarding this one? thought of bumping it since 2 months has passed

**Comment by vegerot** [comment]
How's the TypeScript support going?  Bumping after 8 months

**Comment by DarkLite1** [comment]
This is a great request! Would love to handle the connections more flexible. 
+1

**Comment by ginachoi** [comment]
Could anyone let me know ormconfig.ts is currently supported. The [Typeorm wiki page](https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#using-ormconfigxml) says it does but it doesn't work for me.

**Comment by Mati365** [comment]
bump

**Comment by rettgerst** [comment]
I ran into this issue today. I'm deploying on vercel and want to use a different database name on different branches, so data is kept separate and I can test migrations against a preview database in ci before running them against the production deployment. I made an ormconfig.ts file that dynamically created a config from environment variables. for my application code I can just import the file and pass that to createConnection, but the cli doesn't pick it up. all I get is `Error: No connection options were found in any orm configuration files.`.

**Comment by dobromyslov** [comment]
Would be nice to configure cli migrations more flexible and use it with cloud secrets managers like this one https://cloud.google.com/secret-manager/docs/quickstart#secretmanager-quickstart-nodejs

Found a workaround for custom TypeScript config here: https://stackoverflow.com/a/57538637/1177597

**Comment by Akazm** [comment]
Don't mind this comment, it's just a tumbleweed rolling through the desert of ignorance

**Comment by imnotjames** [comment]
https://github.com/typeorm/typeorm/issues/7427
