### ISSUE TITLE
cordova and migrations

### ISSUE THREAD

**Issue by marcorinck** [typeorm/typeorm#2360]
**Issue type:**
[X] bug
[X] question

**Database system/driver:**
[X] `cordova` (ionic)

**TypeORM version:**
[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

I'm still playing around with typeorm (awesome lib, thanks!) as I may want to use it in my next ionic/cordova project. My test project works nicely, I have some entities now with some relations, all is fine. But I'm currently having a problem to understand how to keep the user databases on their devices in sync with my entities. 

As far as I understand the typeorm cli and its migration generation or schema sync features does not help me much in this case, as it doesn't have any access to any database (which would only be available on a mobile device). Currently it throws a misleading error message when trying to use it with a cordova database in ormconfig.json, f.i.:

````
{ DriverPackageNotInstalledError: Cordova-SQLite package has not been found installed. Try to install it: npm install cordova-sqlite-storage --save
    at new DriverPackageNotInstalledError (/usr/local/lib/node_modules/typeorm/error/DriverPackageNotInstalledError.js:19:28)
    at CordovaDriver.loadDependencies (/usr/local/lib/node_modules/typeorm/driver/cordova/CordovaDriver.js:133:19)
```` 

(cordova-sqlite-storage is installed, but the driver just tries to access window.sqlitePlugin which node doesn't know about and just throws "window is not defined")

Next, I wanted to define the migrations in the connection options I use in my own code like this:

```` 
this.connection = await createConnection({
	type: 'cordova',
	database: 'database',
	location: 'default',
	logging: ['error', 'query', 'schema'],
	synchronize: false,
	migrations: ["migrations/*"],
	entities
});
```` 
The project is an ionic project and is using the custom webpack.config.js from the example project. But I get this error as soon as I open the connection:

```` 
Error: This option/function is not supported in the browser environment. Failed operation: require("glob").
load — PlatformTools.js:23
(anonyme Funktion) — DirectoryExportedClassesLoader.js:21
reduce
importClassesFromDirectories — DirectoryExportedClassesLoader.js:20
buildMigrations — ConnectionMetadataBuilder.js:26
buildMetadatas — Connection.js:510
```` 

As soon as I remove the "migrations" property and set "synchronize" to "true" its working again.

So how is migrations supposed to work with cordova? Can I check if the current database conforms to the current schema that would be created with the current entities?

**Comment by daniel-lang** [comment]
Sorry for the late response.

Migrations are supported in cordova but with some limitations.
As mentioned in your issue, CLI won't be of only help when creating migrations as it doesn't know anything of the cordova plugin. You can still create empty migrations just to get the current file naming.

When loading migrations you will have to import and specify each and every migration in your migrations file like:

```ts
import { FirstMigration1517339641128 } from 'migrations/1517339641128-First-Migration';
import { SecondMigration1517340398662 } from 'migrations/1517340398662-Second-Migration';

...

createConnection({
   ...
   migrations: [FirstMigration1517339641128, SecondMigration1517340398662]
});
```

**Comment by dominicdesu** [comment]
@marcorinck I am using the migrations in cordova just as @daniel-lang described. Do you still have issues with this? If not, could you close the ticket?

**Comment by daniel-lang** [comment]
Since @marcorinck didn't respond in three months I'm going to close this issue.

**Comment by tindn** [comment]
@daniel-lang I'm seeing the same issue with RN, and adding migration manually works. Do you have any insights into why that's the case?
