### ISSUE TITLE
ES Map Object

### ISSUE THREAD

**Issue by fuyifan** [typeorm/typeorm#2367]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Here is my code.
@Column({ type: "blob", transformer: new CardsTransform() })
cards: Map<number, Card>;

I want to a save a Map object as a blob data into MySQL. I implement the ValueTransformer interface.

class CardsTransform implements ValueTransformer {
    to(value: any) {
        // value is just {}
        // return serialize(value);
    }  
    from(value: any) {
        // TODO
    }
}

After I set several objects into the cards and invoke the save operation, I debug the _to_ function in CardsTransform and find the value is only {}

Can anyone help me to meet my requirement? Thanks.

**Comment by pleerock** [comment]
Would be great if you provide a PR with a failing test so we can debug and help you with your issue.

**Comment by fuyifan** [comment]
@pleerock Please check the PR above.

**Comment by pleerock** [comment]
Will be released in a next version
