### ISSUE TITLE
add @transaction on the method, but the parameter has no values

### ISSUE THREAD

**Issue by Owen-Zhang** [typeorm/typeorm#2369]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>
@Transaction()
async usetransaction(
        entity: UserEntity, address: AddressEntity,) : Promise<boolean> {
            console.log(`${entity.id} + ${entity.name} + ${entity.telphone}`);
            console.log(`${address.info} + ${address.username}`);
        return true;
    }

output:
undefined + undefined + undefined 
undefined + undefined

please help me

**Comment by Kononnable** [comment]
Looks like you forgot to describe the issue.

**Comment by chriszrc** [comment]
I just ran into this as well, I think what they meant to describe was that the docs have this example:

```typescript
@Transaction()
save(@TransactionManager() manager: EntityManager, user: User) {
    return manager.save(user);
}
```

But it's not clear that (and I'm guessing here, but it seems to be working), you have to pass in the entitymanger as a parameter to your method:

```typescript
entityManager = getManager();

myRepo.save(entityManager, user);
```
