### ISSUE TITLE
Is it possible to use this library without TypeScript?

### ISSUE THREAD

**Issue by apottere** [typeorm/typeorm#237]
I'm attempting to add ORM to a "plain" ES6/7 nodejs server, without TypeScript.

I was able to define my entities, but they didn't seem to do anything and the library would throw errors around metadata whenever I added parentheses to the decorators.  I installed `babel-plugin-transform-decorators-legacy`, `babel-plugin-decorator-metadata`, and `reflect-metadata` (along with `import 'reflect-metadata'`), but it didn't fix the errors.

Am I doing something wrong, or is this not something that's supported?

**Comment by pleerock** [comment]
You can use it with plain javascript and without decorators. There is an example in typeorm project repositories. However I didn't try to use it with javascript+babel decorators. But I guess it should be possible to use it with babel decorators, if not, then maybe small adoption is required.

**Comment by apottere** [comment]
I'm assuming the example you're talking about is in https://github.com/typeorm/typeorm/tree/master/sample somewhere, so far I can only find one that doesn't have decorators: https://github.com/typeorm/typeorm/tree/master/sample/sample24-schemas.  Is that what I'd have to do without decorators, or am I missing a better sample?

I'll set up a test project for ES6/7 with babel decorators tomorrow to show the errors thrown.

**Comment by apottere** [comment]
I set up a test project to show the bug here: https://github.com/apottere/typeorm-plain-js-bug

I'm using the `"transform-decorators-legacy"` and `"transform-metadata"` babel plugins with `import 'reflect-metadata';` (I also tried `"syntax-decorators"` and `"decorator-metadata"` with `"import 'core-js/es7/reflect';"`).

The error produced:
```
[nodemon] starting `babel-node src/index.js`
TypeError: Cannot read property 'name' of undefined
    at Function.ColumnTypes.typeToString (/build/compiled/src/metadata/types/ColumnTypes.ts:161:29)
    at /build/compiled/src/decorator/columns/PrimaryColumn.ts:36:43
    at /~~~/typeorm-plain-js-bug/src/entity/Photo.js:37:16
    at Array.reduce (native)
    at _applyDecoratedDescriptor (/~~~/typeorm-plain-js-bug/src/entity/Photo.js:36:41)
    at Object.<anonymous> (/~~~/typeorm-plain-js-bug/src/entity/Photo.js:71:19)
    at Module._compile (module.js:571:32)
    at loader (/~~~/typeorm-plain-js-bug/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/~~~/typeorm-plain-js-bug/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
```

**Comment by pleerock** [comment]
I made appropriate changes to make it to work properly without reflect-metadata shim. Checkout [this repository](https://github.com/typeorm/babel-example) for complete example of using typeorm with babel.

**Comment by apottere** [comment]
Awesome, thanks!

**Comment by Allam76** [comment]
Is there an example already without typescript and without babel?

**Comment by pleerock** [comment]
try https://github.com/typeorm/babel-example

**Comment by Allam76** [comment]
Thanks for the example! But this one is with babel...
