### ISSUE TITLE
How do I connect to a MongoDB replica set?

### ISSUE THREAD

**Issue by damianesteban** [typeorm/typeorm#2372]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am not sure how to connect to a mongodb replica set. Let's say that these are the hostnames for my replica set:

```
ip-10-0-11-111.ec2.internal:31111,
ip-10-0-22-222.ec2.internal:32222,
ip-10-0-33-333.ec2.internal:33333,
```

What values do I add to `hostname` and what values do I add to `replicaSet`?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by damianesteban** [comment]
Has anyone connected to a MongoDB Replica Set with TypeORM?

**Comment by darkfxt** [comment]
Hi, how are you? You must set it on de ormconfig file, as follow: 
{ 'type': 'mongodb',
    'host': 'db01,db02,db03',
    'port': 27017,
    'username': 'admin_dbo',
    'password': 'password',
    'database': 'dbname',
    'replicaSet': 'replicaname'}
Every mongod server must run on same port.
I hope been helpful.

**Comment by damianesteban** [comment]
Ok. So it isn’t possible if they each have different ports? That was where I was running into trouble.

**Comment by vaail** [comment]
@damianesteban 
You can config it as follow:
`{
'type': 'mongodb',
'url': 'mongodb://....'
}`

**Comment by vlapo** [comment]
Hi @damiandennis. Did you try @vaail suggestion? 
```typescript
// Connection URL
const url = 'mongodb://localhost:27017,localhost:27018/?replicaSet=foo';

await createConnection({
    type: 'mongodb',
    url
});
```
http://mongodb.github.io/node-mongodb-native/3.0/tutorials/connect/

**Comment by vlapo** [comment]
Closing as there is no response from author.
