### ISSUE TITLE
Primary Key column not included in returned object if primary key is is a foreign key of one-to-one relationship

### ISSUE THREAD

**Issue by dominic-simplan** [typeorm/typeorm#2373]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a table (ProjectSettings) whose primary key is also the foreign key of a one-to-one relation. My entities look like this:
```
@Entity()
export class Project {
    @PrimaryGeneratedColumn()
    id: number;
    @OneToOne(number => ProjectSettings, projectSettings => projectSettings.project, { onDelete: 'CASCADE', cascade: true })
    settings: ProjectSettings;
}
```
and
```
@Entity()
export class ProjectSettings {
    @JoinColumn()
    @OneToOne(type => Project, { primary: true })
    project: Project;
}
```

However, if I use the repository to find the ProjectSettings by the Project, the returned class does not contain the projectId:
```
let repository = getConnection().getRepository(ProjectSettings);
repository.findOne({ project: project }).then(projectSettings => { ...})
```
Thus, when trying to persist the ProjectSettings again, a new entry is created, as the projectId is unknown.
Actually I've tried many combinations of various annotation properties, however I am not able to get it working.

Could someone advise what I am doing wrong here?

**Comment by pleerock** [comment]
> the returned class does not contain the projectId:

because your class does not contain projectId property.

To avoid this kind of issues we are deprecating this format of definition of primary foreign keys in favour of following format:

```ts
@Entity()
export class ProjectSettings {

    @PrimaryColumn()
    projectId: number;

    @OneToOne(type => Project)
    @JoinColumn()
    project: Project;
}
```

please use it and probably you'll get rid of "strange" issues.

**Comment by dominic-simplan** [comment]
@pleerock thanks for the explanation! Saving and loading is working fine now, however I am getting an error when trying to delete the Project entity. (I want that the ProjectSettings are cascaded on insert, update and delete of the Project entity.)

```
@Entity('Project')
export class Project {
    @OneToOne(type => ProjectSettings, projectSettings => projectSettings.project, { cascade: true }) 
    settings: ProjectSettings;
}
```

```
@Entity('ProjectSettings')
export class ProjectSettings {
    @PrimaryColumn()
    projectId: number;
    @JoinColumn({ name: "projectId" })
    @OneToOne(type => Project, project => project.settings, { onDelete: 'CASCADE' })
    project: Project;
}
```

Trying to delete the project:
```
getConnection().getRepository(Project).remove(project);
```
creates an INSERT statement for the ProjectSettings, which fails because the ProjectSettings already exist:
```
query failed:  INSERT INTO "ProjectSettings"("projectId", "otherColumn", ) VALUES (?, ?) -- PARAMETERS: [17,"2018-06-25T00:00:00Z"]
```

I wonder why this INSERT statement is created? 
If I change the @OneToOne and set the cascase to update only, deletion is working, however the cascade insert is not working anymore (obviously):
```
@OneToOne(type => ProjectSettings, projectSettings => projectSettings.project, { cascade: ["update"] }) 
```

**Comment by pleerock** [comment]
that is strange, deletion can't cause cascade insert anyhow, this is something I need to investigate.

Can you contribute and create a failing test for this issue?

**Comment by dominic-simplan** [comment]
Hi,
I've created a PR with an according test case: #2416.
If you need any other information please let me know!

**Comment by imnotjames** [comment]
I've fixed the tests in your test PR.  You forgot to `await` the `remove` call.

They pass locally and I'll be confirming they pass in the CI as well.

**Comment by imnotjames** [comment]
The tests passed in CI.  I think they overlap a few other tests we have so I won't be merging them in.

They also show that this is not an actual issue.  I think you need to `await`.
