### ISSUE TITLE
Create relation entity question

### ISSUE THREAD

**Issue by lalalalaluk** [typeorm/typeorm#2374]
Issue type:

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[x ] mysql / mariadb
[ ] oracle
[ ] postgres
[ ] sqlite
[ ] sqljs
[ ] react-native

TypeORM version:

[ ] latest
[ ] @next
[^2.0.0 ] 0.x.x (or put your version here)

Steps to reproduce or a small repository showing the problem:

I have two table.
One is userBasic and other is userextensions
userBasic is onetomany to userextensions

belong is my schema
```javascript
@Entity("UserBasic")
export class UserBasic {

    @PrimaryGeneratedColumn()
    id: number;

     ....

    @OneToMany(type => UserExtension, userextensions => userextensions.userbasic,
        {
            cascade: true,
            onDelete: "CASCADE",
            onUpdate: "CASCADE",
        })
    userextensions: UserExtension[];

}
```
```javascript
@Entity("UserExtension")
export class UserExtension {

    @PrimaryGeneratedColumn()
    id:number;
        
    @ManyToOne(type => UserBasic, userbasic=> userbasic.userextensions)
    @JoinColumn({ name:'fk_id'})
    userbasic:UserBasic;
    
    .....

    @Column("tinyint",{ 
        nullable:true,
        default:"NULL",
        name:"K_Delete"
        })
    K_Delete:number;
```

I want only create a new userextension 

**my Json**
```javascript
{ id: null,
  Admit_Type:  'aa',
  Unit:  'aa',
  Title: 'aa',
  Date_Start: '2018-06-05',
  Date_Leave: '2018-06-05',
  Lead_Class:  'aa',
  Office_Tel:  'aa',
  Office_Ext:  'aa',
  Update_Date: '2018-06-21T09:20:42+08:00',
  Update_User: 'test',
  fk_id: '1' }
```
how can i save userextension  ?

when I save
```javascript
this.userExtensionRepository.save(userExtension);
```

I got this error
```javascript
error:"ER_NO_DEFAULT_FOR_FIELD: Field 'fk_id' doesn't have a default value"
```
when I create
```javascript
rtnVal = this.userExtensionRepository.create(userExtension);
```

nothing saved in database

but I can update and deletet...

**Comment by pleerock** [comment]
you create a user object, fill values, then you create user extension object and set this object to user and save it. Please follow typeorm homepage tutorials to understand more how typeorm relations work.

**Comment by lalalalaluk** [comment]
Really thank you!
