### ISSUE TITLE
warning: timers.enroll() is deprecated. timers.unenroll() is deprecated 

### ISSUE THREAD

**Issue by fuyifan** [typeorm/typeorm#2378]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When the NodeJS version is above 10.0, two warnings produced:
(node:41728) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:41728) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

**Comment by pleerock** [comment]
looks like some underlying module use those functions. Can you help to figure out what exact module does it? (and then need to report issue in their tracker)

**Comment by fuyifan** [comment]
It’s MySQL module

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Umed Khudoiberdiev <notifications@github.com>
发送时间: Friday, June 22, 2018 8:55:17 PM
收件人: typeorm/typeorm
抄送: fuyifan; Author
主题: Re: [typeorm/typeorm] warning: timers.enroll() is deprecated. timers.unenroll() is deprecated (#2378)


looks like some underlying module use those functions. Can you help to figure out what exact module does it? (and then need to report issue in their tracker)

―

**Comment by pleerock** [comment]
Then issue should be created in their repo.
