### ISSUE TITLE
How to save an int value to a foreign key 

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#238]
In the `Post` table, there is a one-to-one foreign key on `user_id` which links to the table `Members`, there is no problem with fetching the data like this:

`[{ "post_id":1,"user_id":{"user_name":'Someone','user_id':4}, 'comment':'xxxxxx'}]`

Suppose someone makes a comment, I get his comment and user id from express session, and want to save it to the `Post` table. Since `user_id` uses `Members` type, how can I save an int value to it? 
Would you please suggest a solution?

Here's an example:

````
@Table()
export class Post {
    @PrimaryGeneratedColumn()
    post_id: number;

    @OneToOne(type => Members,entity=>entity.user_id,{
        cascadeRemove: true
    })
    @JoinColumn()
    user_id: Members;

    @Column()
    comment:string;
}

export class Members {
    @PrimaryGeneratedColumn()
    user_id: number;

    @Column()
    user_name:string;
}
````

````
    let post = new Post()
    post.comment = "sadsadsa"
    post.user_id = 44 <<=== type error!
````

**Comment by pleerock** [comment]
you need to define both relation and id of the relation as a regular column. Example:

```typescript
@Table()
export class Post {
    @PrimaryGeneratedColumn()
    post_id: number;

    @OneToOne(type => Members,entity=>entity.user_id)
    @JoinColumn({ name: "memberId" })
    member: Members;

   @Column({  type: "int", nullable: true })
   memberId: number;

    @Column()
    comment:string;
}
```

**Comment by stonecold123** [comment]
@pleerock , I just did per your suggestion, but when I insert it into the table with `repository.persist(post)`, 
it gives me error 
````
(node:10665) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 1): 
Error: Relation metadata for tag#user_id was not found.
````
````
@Table()
export class Tag{
    @OneToOne(type=>Members, entity=>entity.user_id,{onDelete:"CASCADE"})
    @JoinColumn({name:'user_id'})
    user_data:Members;

    @Column({type:'int',nullable: true})
    user_id:number;
}
````

**Comment by Tobias4872** [comment]
Not quite sure what you are trying to do. You have defined "Post.user_id" as type "Members" which obviously is not only an id. So, if you want to create a post, you will need to assign an instance of type "Members" to "user_id", so let's say you have two models like the following (please notice that I have changed the naming a bit.

```
@Table()
export class Member {
    @PrimaryGeneratedColumn()
    public userId: number;

    @Column()
    public userName: string;
}

@Table()
export class Post {
    @PrimaryGeneratedColumn()
    public postId: number;

    @OneToOne(type => Member, (entity) => entity.userId,{
        cascadeRemove: true,
    })
    @JoinColumn()
    public user: Member;

    @Column()
    public comment: string;
}
```

You would then need to either create a new Member instance in advance or retrieve one from the db.

```
    const user = new Member();
    user.userId = 1;
    user.userName = "Username";

    const memberRepo = connection.getRepository(Member);
    await memberRepo.persist(user);

    const post = new Post();
    post.comment = "Test";
    post.user = user;

    const postRepo = connection.getRepository(Post);
    await postRepo.persist(post);
```

Let me know if this helps.

**Comment by vance** [comment]
If I use an existing `user:Member` entity, I get a violation of unique constraint when i update the 2nd post (since it uses the same `user` entity). How do a make a 2nd update to post?

**Comment by Jood80** [comment]
These answers were absolutely helpful, thank you both @pleerock @Tobias4872
