### ISSUE TITLE
TypeORM Entity Listeners and Subscribers with Javascript

### ISSUE THREAD

**Issue by ahmedosama94** [typeorm/typeorm#2384]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is it possible to use Entity Listeners and Subscribers with TypeORM in a JavaScript?

I would like for example to be able to add a listener to hash a user's password before insertion, but I can't just use decorators in JavaScript for this case. Any help?

**Comment by pleerock** [comment]
Closing in favour of #2305 . Currently there isn't elegant way to use them in JavaScript, but we definitely need to add it asap.
