### ISSUE TITLE
How to select only few related table columns with find() method?

### ISSUE THREAD

**Issue by anamanaguchi** [typeorm/typeorm#2385]
**Issue type:**
[x] question

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[X] `0.2.7` (or put your version here)

Hello,
I'm struggling for a while with selecting only 1 column from related table in `find()` method:

`someRepository.find({
            order: {'id': 'DESC'},
            relations: ['createdBy'],
            select: ['id', 'firstName', 'lastName', 'active', 'createdAt', 'lastLogin', 'phoneNumber', 'createdBy.email'],
        })`

When i try to run this, I got this error:
> createdBy.email column was not found in the Some entity

Could you please give me some clues how it should look like? 

Thanks in advance!

**Comment by pleerock** [comment]
You can select only top-level columns this way. This will be changed in next 0.3.0 version (you can try it via npm i typeorm@next).

In current 0.2.0 version you need to use QueryBuilder for this purpose.

**Comment by patrickmichalina** [comment]
@next didn't work for me. It threw an error `QueryFailedError: missing FROM-clause entry for table "role"`

**Comment by maximelafarie** [comment]
> You can select only top-level columns this way. This will be changed in next 0.3.0 version (you can try it via npm i typeorm@next).

@pleerock @Kononnable @imnotjames is there any docs about that? Has it been implemented yet? Because I also have this issue as well.

**Comment by sandesh-bhoir** [comment]
any update here, as we have to use querybuilder to achieve this

**Comment by JefferyHus** [comment]
Any updates here?

**Comment by m-daros** [comment]
Please, are there any updates?
Using Query Builder it's possible to obtain the selected columns, but they are mixed in an object, something like:

`[
  {
    "entity1_id": 10,
    "entity1_name": "CS my 2",
    "entity2_id": 1,
    "entity2_name": "value 1"
  },
  {
    "entity1_id": 10,
    "entity1_name": "CS my 2",
    "entity2_id": 3,
    "entity2_name": "value3"
  }
]`

So, to obtain the model structure one way is to iterate over the values and do some transformation.

Thank you in advance

**Comment by simlarsen** [comment]
For everyone looking for a solution - @pleerock answer https://github.com/typeorm/typeorm/issues/2385#issuecomment-410430444 actually works!

**Comment by ketanhtrentiya** [comment]
> @patrickmichalina oh, so in `next` syntax has changed. How you shall do it this way:
> 
> ```ts
> {
>    select: {
>       id: true,
>       person: {
>           id: true,
>           name: true
>       }
>    } 
> ```

This is works form, thanks!

**Comment by weimengxi** [comment]
Thanks a lot.
This feature was first supported in [0.3.0](https://github.com/typeorm/typeorm/releases?expanded=true&page=2&q=0.3.0)
Make sure you are using versions >= 0.3.0 


> > @patrickmichalina oh, so in `next` syntax has changed. How you shall do it this way:
> > ```ts
> > {
> >    select: {
> >       id: true,
> >       person: {
> >           id: true,
> >           name: true
> >       }
> >    } 
> > ```
> 
> This is works for me, thanks!

It's said that this feature was first supported in  v0.3.0

**Comment by SlmnVaival** [comment]
T

> Thanks a lot. This feature was first supported in [0.3.0](https://github.com/typeorm/typeorm/releases?expanded=true&page=2&q=0.3.0) Make sure you are using versions >= 0.3.0
> 
> > > @patrickmichalina oh, so in `next` syntax has changed. How you shall do it this way:
> > > ```ts
> > > {
> > >    select: {
> > >       id: true,
> > >       person: {
> > >           id: true,
> > >           name: true
> > >       }
> > >    } 
> > > ```
> > 
> > 
> > This is works for me, thanks!

By using these code typeorm is only fetching one relational record, it work prefect with one-to-one relation but not with the ManyToOne.

**Comment by Mcmhee** [comment]
```
const type = await this.doctorTyoeRepo.find({
        select: ['specialization'],
      });
```
this works for me... where specialization is the field i needed

**Comment by thexeos** [comment]
> By using these code typeorm is only fetching one relational record, it work prefect with one-to-one relation but not with the ManyToOne.

That's because the generated query looks something like this:
```sql
SELECT DISTINCT `distinctAlias`.`Entity_id` AS `ids_Entity_id`
FROM
  (SELECT `Entity`.`id` AS `Entity_id`,
          `Entity__Persons`.`id` AS `Entity__Persons_id`,
          `Entity__Persons`.`name` AS `Entity__Persons_name`
   FROM `entity` `Entity`
   LEFT JOIN `person` `Entity__Persons` ON `Entity__Persons`.`entity_id`=`Entity`.`id`
   WHERE (`Entity`.`id` = ?)) `distinctAlias`
ORDER BY `Entity_id` ASC
LIMIT 1
```
I found no workaround other than issuing two queries.

Furthermore, if the relation column is not selected on the parent entity (aka, if the example looked like this:

```
select: {
  someColumn: true,
  person: {
    id: true,
    name: true
  }
} 
```

), then the query will fail with `QueryFailedError: Unknown column 'distinctAlias.Entity_id' in 'field list'`.

**Comment by Starlette** [comment]
What if the relation has many "Persons" in it. It returns undefined for me.
