### ISSUE TITLE
Fields order when using relations

### ISSUE THREAD

**Issue by mxs42** [typeorm/typeorm#2386]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I've created an entity and added relation using `ManyToOne` decorator.
After sync TypeORM creates table and puts this field after all fields and I don't really like that my `createdAt` and `updatedAt` are not the last fields inside created table.
Is it an expected behavior and/or is there a way to change it?  
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
it is expected behaviour, if you want to change it you need to do it manually.

**Comment by mxs42** [comment]
OK, thanks.
