### ISSUE TITLE
Unable to create createdAt/upadtedAt fileds without decorators.

### ISSUE THREAD

**Issue by atomicus** [typeorm/typeorm#2389]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Excuse me if I'm just blind and didn't found it, but I cannot find anything in docs and examples on how to create autogenerated columns `createdAt`,`updatedAt` without use of decorators, in javascript only. Aka @CreateDateColumn @UpdateDateColumn if used by decorators.

Is it possible and I'm just missing something, or is it not currently supported?

**Comment by pleerock** [comment]
you can do it following way:

```ts
columns: {
     updatedAt: {
           /// other column properties
           updateDate: true
     }
}
```
