### ISSUE TITLE
Find operators get passed as objects to transformers

### ISSUE THREAD

**Issue by wcauchois** [typeorm/typeorm#2390]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
import 'reflect-metadata';
import { createConnection, Entity, Column, BaseEntity, PrimaryGeneratedColumn, Between } from 'typeorm';

@Entity()
class Thing extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    transformer: {
      from(value) {
        console.log('from', value);
        return value;
      },

      to(value) {
        console.log('to', value);
        return value;
      }
    }
  })
  field: number;
} 

async function run() {
  await createConnection({
    type: 'sqlite',
    database: './db.sqlite',
    entities: [Thing],
    synchronize: true,
    dropSchema: true
  });

  for (let i = 0; i < 5; i++) {
    const thing = new Thing();
    thing.field = i;
    await thing.save();
  }

  const result = await Thing.find({ where: { field: Between(2, 3) } });
  console.log(result);
}

run();
```

After running the above code you'll see one piece of output from the transformer that looks like this:

```
to FindOperator {
  _type: 'between',
  _value: [ 2, 3 ],
  _useParameter: true,
  _multipleParameters: true }
```

What seems to be happening is that the `Between` find operator is getting passed to the transformer as an object. I first ran into this issue because this caused my transformer to throw an exception.

I searched around for this issue and judging from @pleerock's comment [here](https://github.com/typeorm/typeorm/issues/1990#issuecomment-386950890) it seems that transformers are perhaps an underdeveloped feature right now. That's fine if they aren't applied in all cases, *however* it'd be ideal if things like find operators still worked at all under a transformer.

Would it be an easy fix to just sidestep transformers for find operators? That is, you'd use an un-transformed value for that Between operator.

My concrete use case here BTW is converting Date columns to use Luxon DateTimes.

Thanks in advance!

**Comment by pleerock** [comment]
Im keeping open all issues related to `transformer` and once I get more free time I'll resolve them all

**Comment by ryuuji3** [comment]
I know you're a busy guy- so I'm only merely asking, have you had or will you have any time to look into this at all @pleerock ? Thank you regardless.

For anyone who runs into this and still wants to use your Date transformers, you might be able to get around it using Moment to parse dates and convert to a Date object after you're done. Kind of silly, but there are a few limited use cases where it makes sense.

**Comment by Ciantic** [comment]
Maybe this could be a feature also, but with different function e.g. 

```typescript
Column({
        type: "int",
        transformer: {
            from(value: number): Date {
                return new Date(value);
            },
            to(value: Date): number {
                return value.getTime();
            }
            operator(value: FindOperator<Date>): FindOperator<number> {

            }
        }
    });
```

But only if the `operator()` is defined, anyhow it should not keep on passing the FindOperator stuff to the `to()` function, it makes things complicated.

**Comment by santiagofm** [comment]
Does anyone have another workaround without it being doing a plain SQL query(that's what I'm currently doing)?

I'd gladly take a look at how a fix can be implemented if anyone can point me in the right direction.

**Comment by Ciantic** [comment]
@santiagofm sure there is a workaround:

```
{
        type: "int",
        transformer: {
            from(value: number): Date {
                return new Date(value);
            },
            to(value: Date | FindOperator<any>): number | any {
                if (value instanceof Date) {
                    return value.getTime();
                } else {
                    // It's find operator
                    return value;
                }
            }
        }
    }
```

Or just check with structural typing

```
                    if (value.toSql) {
                        // It's find operator
                        return value;
                    }
```

**Comment by osdiab** [comment]
Could the workaround in https://github.com/typeorm/typeorm/issues/4399 potentially solve this issue while adding support for `FindOperator` instances throughout TypeORM?

**Comment by imnotjames** [comment]
Why shouldn't the logic on how to handle `FindOperator` be part of the transformer you write?

The [above comment](https://github.com/typeorm/typeorm/issues/2390#issuecomment-489462022) describes a reasonable way (though, you should `instanceof FindOperator` instead of duck typing check it) to handle `FindOperator`s if you don't care about changing the values.

Because a transformer is a function and transformers can do LITERALLY ANYTHING you can do in javascript there's no one-size-fits-all solution to this.

Can this be closed?

**Comment by nebkat** [comment]
> Why shouldn't the logic on how to handle FindOperator be part of the transformer you write?

I think in most circumstances one would want the transformer to act on the parameters to the `FindOperator`, rather than the operator itself. Take the example below:

```typescript
export class UserRole {
    static readonly ADMIN = new UserRole('admin', 3);
    static readonly MODERATOR = new UserRole('moderator', 2);
    static readonly USER = new UserRole('user', 1);

    static fromRank(rank: 1 | 2 | 3) {
        return [UserRole.USER, UserRole.MODERATOR, UserRole.ADMIN][rank - 1];
    }

    static toRank(role: UserRole) {
        return role.rank;
    }

    private constructor(readonly value: string, readonly rank: number) {}
}

@Entity()
export class UserEntity {
    // ...

    @Column({
        type: 'tinyint',
        default: UserRole.USER.rank,
        transformer: {
            from: UserRole.fromRank,
            to: UserRole.toRank
        }
    }) role!: UserRole;

    // ...
}
```

Except for `Raw()`, which isn't really an "operator", all of the values here should be mapped to the `rank` representation using the transformer:

```typescript
userRepository.find({
    role: Any(UserRole.USER, UserRole.MODERATOR), 
    role: Between(UserRole.USER, UserRole.MODERATOR),
    role: Equal(UserRole.ADMIN),
    role: In(UserRole.USER, UserRole.MODERATOR),
    role: LessThan(UserRole.MODERATOR),
    role: LessThanOrEqual(UserRole.MODERATOR),
    role: MoreThan(UserRole.MODERATOR),
    role: MoreThanOrEqual(UserRole.MODERATOR),
    role: Not(UserRole.MODERATOR),
   
    // Not relevant for this example
    role: ILike(UserRole.ADMIN),
    role: Like(UserRole.ADMIN),
    role: IsNull(),

    // Exception to the rule, of course
    role: Raw(UserRole.MODERATOR) // becomes `role = ${UserRole.MODERATOR}` directly
});
```

Only in situations where more complex logic applies should a transformer be expected to modify an operator, and I think @Ciantic's [suggestion](https://github.com/typeorm/typeorm/issues/2390#issuecomment-487080132) would be the best way to achieve that. A good use case for this would be special handling for `Date` objects.

**Comment by Celbine** [comment]
my way with find operators **'Between'**, **'MoreThanOrEqual'** and **'LessThanOrEqual'**:

```
@Column('bigint', {
    default: 0,
    transformer: {
      to: (amount) => {
        if(amount instanceof FindOperator){
          if(amount.type === 'between'){
            // @ts-ignore
            amount._value = amount.value.map((el) => Utility.ToBigInt(+el, 1000));
            return amount;
          }
          // @ts-ignore
          amount._value = Utility.ToBigInt(+amount.value, 1000);
          return amount;
        }
        return Utility.ToBigInt(amount, 1000)
      },
      from: (amount) => Utility.FromBigInt(amount, 1000),
    },
    nullable: false
  })
  balance: number;
```

**Comment by davorzdralo** [comment]
Another way to do it while keeping type safety and not using private fields:

```
import * as moment from 'moment';
import { FindOperator, ValueTransformer } from 'typeorm';

export const dateTransformer: ValueTransformer = {
  to: (m: moment.Moment | FindOperator<moment.Moment[]> | null) => {
    if (m instanceof FindOperator && m.type == 'between'){
      return new FindOperator(
        m.type,
        Array.isArray(m.value) ? m.value.map(value => value.format()) : null,
        m.useParameter,
        m.multipleParameters,
      );

    } else if (!(m instanceof FindOperator)) {
      return m != null ? m.format() : null;
    } else {
      throw new Error('Unknown input type in date transformer');
    }
  },
  from: (d: Date | string | null) => (d != null ? moment.utc(d) : null),
};

```

This transformed supports only Between function and not others, and is for transforming Moment.js dates.

**Comment by gyzo** [comment]
Looks like it still doesn't work. :/

**Comment by zlooun** [comment]
> Looks like it still doesn't work. :/

Yes, it is. Here is my solution:
![image](https://github.com/typeorm/typeorm/assets/50909481/2779a3fc-6bd8-48b4-980c-92a8caefb733)
![image](https://github.com/typeorm/typeorm/assets/50909481/e04375fe-d109-46e2-a8bf-1228ab480fb3)
