### ISSUE TITLE
And operator

### ISSUE THREAD

**Issue by Xstoudi** [typeorm/typeorm#2396]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.6` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I would like to make an AND operation on a WHERE operation.
Something like XXX AND XXX.

The actual code is the following:
```ts
const posts = await Post.find({
      where: {
        deleted: false,
        publishDatetime: Not(new Date(3000, 12, 31))
      },
      take: 10,
      order: {
        id: 'DESC'
      }
    })
```
But I want to add an other condition on publishDatetime: I want to verify that publishDatetime is before or equal the current datetime.

**Comment by pleerock** [comment]
Extended find options functionality will be avaliable in `0.3.0` via #2100

**Comment by Xstoudi** [comment]
Thank you!
Do you have a release date goal?

**Comment by pleerock** [comment]
I'm really busy last months so I expect to do it in September. You can try 0.3.0 with this particular feature in `@next` (npm i typeorm@next)

Please consider donation on [open collective](https://opencollective.com/typeorm) if you really like typeorm and want to support its development.

**Comment by Xstoudi** [comment]
I'll use @next for now!

I'm a student so, I will donate when I use TypeORM in a professional context.

**Comment by Xstoudi** [comment]
I'm on @next and the example in #2100 doesn't seems to solve the problem.

**Comment by phil294** [comment]
> I'm really busy last months so I expect to do it in September. You can try 0.3.0 with this particular feature in `@next` (npm i typeorm@next)
> 
> Please consider donation on [open collective](https://opencollective.com/typeorm) if you really like typeorm and want to support its development.

The `And()` operator does not seem to be present in the latest alpha version. Is this intended @pleerock ? Or how did you mean to fix OPs issue?

I can wholeheartedly understand if you're depending on donations. It is open source after all :-)
