### ISSUE TITLE
How to approach uni directional ManyToOne

### ISSUE THREAD

**Issue by ullalaaron** [typeorm/typeorm#2397]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am creating the entities that make up my db schema. 
I have the entity `Photo` that is bound to the entity `Hashtag` in a many to one relation (each photo has one hashtag, and each hashtag can belong to many photos).
 
In order to do this, as per TypeOrm documentation, I have to do the following.
In the **Photo** entity :

    @ManyToOne(type => HashtagEntity, hashtag => hashtag.Photos)
    @JoinColumn({ name: 'HashtagId' })
    Hashtag: HashtagEntity;

And in the **Hashtag** entity :

    @OneToMany(type => PhotoEntity, photo => photo.Hashtag)
    Photos: PhotoEntity[];

I have read that all entities are eagerly loaded in TypeOrm. Does this mean that each time I query a hashtag I materialize all the photos associated to it?
If this is the case, it's very bad as I only need the reference to the Hashtag from the photo and not the other way around.

How can I solve this? Should I use a `OneToOne` relation on the `Photo` entity or is there a way to make a unidirectional `ManyToOne`?

**Comment by pleerock** [comment]
> I have read that all entities are eagerly loaded in TypeOrm

no, its not correct. Relations are not loaded at all by default until you explicitly specify relations in find options or query builder.
