### ISSUE TITLE
Problem with updating a foreign key column in MySQL

### ISSUE THREAD

**Issue by Tobias4872** [typeorm/typeorm#240]
Hi,

I have run across a problem when updating a foreign key column to "nullable: false". I have setup a demo case in [https://github.com/Tobias4872/typeorm-foreign-key-index-problem](https://github.com/Tobias4872/typeorm-foreign-key-index-problem). If you have time, please review and let me know if you see the same.

Tobias.

P.s. - probably this has the same cause as suggested by @Luke265 in #231.

**Comment by pleerock** [comment]
Thank you for the report. Fixed and released in `0.0.8-alpha.4`. @Luke265 can you please check if your issue is fixed as well?

**Comment by Tobias4872** [comment]
Works fine on my end. Thanks!!
