### ISSUE TITLE
@OneToMany w/ cascade: am I just setting this up wrong?

### ISSUE THREAD

**Issue by savvyintegrations** [typeorm/typeorm#2401]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

I'm trying to set up `@OneToMany` relationships with `cascade`. The child objects get inserted into the database, but the foreign key value (`gather_id`) is `null`. I've been struggling to figure out whether I have this set up correctly. 

```
// Parent class
@Entity('gathers')
export class Gather {

    constructor(data?: GatherDataType) {
        if (data) {
            this.appVersion = data.appVersion;
            this.createPacketObjectsFromRawHex(data.rawData);
        }
    }

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        name: 'app_version',
    })
    appVersion: string;

    @OneToMany(type => Device, device => device.id, {
        cascade: true,
        onDelete: 'CASCADE',
    })
    devices: Device[];

    createPacketObjectsFromRawHex = (rawData: RawDataType) => {

        const packetObjects = {};

        Object.entries(rawData).forEach(d => {
            const syncTime = +d[0];
            const rawHex = d[1];
            const typeHex = rawHex.substr(8, 4);
            let packetObj = {};

            switch (typeHex) {
                // simplified... removed most cases
                case PacketType.Device:
                    packetObj = new Device(rawHex, syncTime);
                    break;
            }

            if (!packetObjects[typeHex]) {
                packetObjects[typeHex] = [];
            }

            packetObjects[typeHex].push(packetObj);
        });

        this.devices = packetObjects[PacketType.Device];
    }
}

// Child class
@Entity('devices')
export class Device extends BatteryDeviceBase {

    constructor(rawHex?: string, syncTime?: number) {
        super(rawHex, syncTime);
    }

    @ManyToOne(type => Gather, gather => gather.devices)
    @JoinColumn({ name: 'gather_id' })
    gather: Gather;

}

// How I'm calling this, passing in a `gatherData` JSON object...
const gather = new Gather(gatherData);
await connection.manager.save(gather);
```
All the inserts happen, i.e., a `gather` row and `device` rows, but `device.gather_id` is `null`. 

I tried setting `nullable: false` on the `@ManyToOne` column but that just results in an `INSERT` error, as one would expect.

I tried `cascade: true` on the `@ManyToOne` but that resulted in no inserts at all.

I also tried calling the `createPacketObjectsFromRawHex` method after creating the `Gather` object (i.e., not in the constructor), but that didn't make a difference.

**Comment by pleerock** [comment]
To make sure its not your code issue please provide a simpler reproduction code, or better a PR with a failing test directly to prove that its not working.

**Comment by savvyintegrations** [comment]
I'll try to comply. Meanwhile, I think this SO article is the same issue: https://stackoverflow.com/questions/48453848/how-to-do-cascading-inserts-with-tables-having-auto-increment-id-columns-in-type.

**Comment by saachinsiva** [comment]
hello

may I know if you have any update on this issue? We are facing similar issue.

**Comment by krazibit** [comment]
Bump

**Comment by vedranjukic** [comment]
I'm facing the same issue

**Comment by kitchanismo** [comment]
follow up not working

**Comment by MariusVB** [comment]
I think this needs a reopening

**Comment by CemYil03** [comment]
> **Issue type:**
> 
> [x] question
> [ ] bug report
> [ ] feature request
> [ ] documentation issue
> 
> **Database system/driver:**
> 
> [ ] `cordova`
> [ ] `mongodb`
> [ ] `mssql`
> [ ] `mysql` / `mariadb`
> [ ] `oracle`
> [x] `postgres`
> [ ] `sqlite`
> [ ] `sqljs`
> [ ] `react-native`
> 
> **TypeORM version:**
> 
> [ ] `latest`
> [x] `@next`
> [ ] `0.x.x` (or put your version here)
> 
> I'm trying to set up `@OneToMany` relationships with `cascade`. The child objects get inserted into the database, but the foreign key value (`gather_id`) is `null`. I've been struggling to figure out whether I have this set up correctly.
> 
> ```
> // Parent class
> @Entity('gathers')
> export class Gather {
> 
>     constructor(data?: GatherDataType) {
>         if (data) {
>             this.appVersion = data.appVersion;
>             this.createPacketObjectsFromRawHex(data.rawData);
>         }
>     }
> 
>     @PrimaryGeneratedColumn()
>     id: number;
> 
>     @Column({
>         name: 'app_version',
>     })
>     appVersion: string;
> 
>     @OneToMany(type => Device, device => device.id, {
>         cascade: true,
>         onDelete: 'CASCADE',
>     })
>     devices: Device[];
> 
>     createPacketObjectsFromRawHex = (rawData: RawDataType) => {
> 
>         const packetObjects = {};
> 
>         Object.entries(rawData).forEach(d => {
>             const syncTime = +d[0];
>             const rawHex = d[1];
>             const typeHex = rawHex.substr(8, 4);
>             let packetObj = {};
> 
>             switch (typeHex) {
>                 // simplified... removed most cases
>                 case PacketType.Device:
>                     packetObj = new Device(rawHex, syncTime);
>                     break;
>             }
> 
>             if (!packetObjects[typeHex]) {
>                 packetObjects[typeHex] = [];
>             }
> 
>             packetObjects[typeHex].push(packetObj);
>         });
> 
>         this.devices = packetObjects[PacketType.Device];
>     }
> }
> 
> // Child class
> @Entity('devices')
> export class Device extends BatteryDeviceBase {
> 
>     constructor(rawHex?: string, syncTime?: number) {
>         super(rawHex, syncTime);
>     }
> 
>     @ManyToOne(type => Gather, gather => gather.devices)
>     @JoinColumn({ name: 'gather_id' })
>     gather: Gather;
> 
> }
> 
> // How I'm calling this, passing in a `gatherData` JSON object...
> const gather = new Gather(gatherData);
> await connection.manager.save(gather);
> ```
> 
> All the inserts happen, i.e., a `gather` row and `device` rows, but `device.gather_id` is `null`.
> 
> I tried setting `nullable: false` on the `@ManyToOne` column but that just results in an `INSERT` error, as one would expect.
> 
> I tried `cascade: true` on the `@ManyToOne` but that resulted in no inserts at all.
> 
> I also tried calling the `createPacketObjectsFromRawHex` method after creating the `Gather` object (i.e., not in the constructor), but that didn't make a difference.

I would say typically the "cascade: true"-option belongs to the OneToMany-side whereas "onDelete: 'CASCADE'" is most of the time at the ManyToOne-side, beceause it is the entity with the actual foreign key constraint.

**Comment by justdvl** [comment]
> I would say typically the "cascade: true"-option belongs to the OneToMany-side 

Why?

**Comment by CemYil03** [comment]
Let's use an example for a one to many relation: one `User` has many `Posts`.
In the User class you would find: `@OneToMany(() => Post, (post: Post) => post.user, { cascade: true })`.
`{ cascade: true }` gives the direction to resolve persist nested relations when you use the save method on repositories, nothing else.

```typescript
usersRepository.save({
   ...userFields,
   posts: [        // <-- { cascade: true } triggers that this gets detected and resolved to sql insert statements
      { ...postFieldsForFirstPost },
      { ...postFieldsForSecondPost }
   ]
});
```
