### ISSUE TITLE
Adding extra columns to a join table/relationship table

### ISSUE THREAD

**Issue by OKNoah** [typeorm/typeorm#2402]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The documentation [here](http://typeorm.io/#/many-to-many-relations) says you only need to make 2 `Entity`s, and with the right decorators, you will get 3 tables. (e.g. `user`, `place` and `user_place`). You need only make `User` and `Place` entities.

Imagine a use case where the relationship between a `User` and a `Place` is not always the same. We could communicate this using another column like `type` in the `user_place` table. E.g. `type` could be `{ enum: ['lives at', 'lived at', 'visits', 'likes'] }`.

Is there a way to add other columns to these auto-generated tables? I thought `@JoinTable({ schema: 'entityWithTypesColumn' })` would allow me to extend the table to add more fields, but I get the error:

```
QueryFailedError: relation "user" does not exist
```

Even when just trying to create a user with no relation.

**Comment by OKNoah** [comment]
Also, looks like `typeorm` doesn't create `created at` columns on these join tables :(

```
+-------------+--------------+----------------------------+
|                   question_categories                   |
+-------------+--------------+----------------------------+
| questionId  | int(11)      | PRIMARY KEY FOREIGN KEY    |
| categoryId  | int(11)      | PRIMARY KEY FOREIGN KEY    |
+-------------+--------------+----------------------------+
```

**Comment by pleerock** [comment]
As I answered you in gitter you should create a separate entity with relation `question` and `category` relations and add any number of additional columns you want. 

You don't need to use `@ManyToMany` in this particular scenario. ManyToMany is just a junction table that directly connects two tables, nothing else. 

Example:

```
@Entity()
export class UserPlace {

       @ManyToOne(() => Question, ...) // inverse is one-to-many in question
       question: Question;

       @ManyToOne(() => Category, ...) // inverse is one-to-many in category
       category: Category;

       @Column()
       anyOtherColumnYouWant: string;

}
```

Again,  you don't need to use `@ManyToMany` in this particular scenario.

**Comment by OKNoah** [comment]
Sorry, I thought only many-to-many relationships would allow many entities to connect to many of the same other entities.

**Comment by OKNoah** [comment]
@pleerock Do you have a recommended source of information that describes a many-to-many? It seems I've misunderstood it.

**Comment by andreechristian** [comment]
@pleerock in this case, then if i want to access Place from User, i would need to access it by using `User.userPlace.place?` Instead of `User.place` if i use many-to-many relation?

**Comment by a7urag** [comment]
> As I answered you in gitter you should create a separate entity `user` and `place` relations and add any number of additional columns you want.
> 
> You don't need to use `@ManyToMany` in this particular scenario. ManyToMany is just a junction table that directly connects two tables, nothing else.
> 
> Example:
> 
> ```ts
> @Entity()
> export class UserPlace {
> 
>        @PrimaryColumn() 
>        userId: number;
> 
>        @ManyToOne(() => User, ...) // inverse "userPlaces: UserPlace[]" is one-to-many in user
>        @JoinColumn({ name: "userId" })
>        user: User;
> 
>        @PrimaryColumn() 
>        placeId: number;
> 
>        @ManyToOne(() => Place, ...) // inverse "userPlaces: UserPlace[]" is one-to-many in place
>        @JoinColumn({ name: "placeId" })
>        place: Place;
> 
>        @Column()
>        anyOtherColumnYouWant: string;
> 
> }
> ```
> 
> Again, you don't need to use `@ManyToMany` in this particular scenario.

CAn anyone please help on this? I am unable to relate my tables

**Comment by a7urag** [comment]
https://github.com/typeorm/typeorm/issues/1224#issuecomment-348426495

**Comment by a7urag** [comment]
#1224#issuecomment-348426495

**Comment by icharge** [comment]
> As I answered you in gitter you should create a separate entity `user` and `place` relations and add any number of additional columns you want.
> 
> You don't need to use `@ManyToMany` in this particular scenario. ManyToMany is just a junction table that directly connects two tables, nothing else.
> 
> Example:
> 
> ```ts
> @Entity()
> export class UserPlace {
> 
>        @PrimaryColumn() 
>        userId: number;
> 
>        @ManyToOne(() => User, ...) // inverse "userPlaces: UserPlace[]" is one-to-many in user
>        @JoinColumn({ name: "userId" })
>        user: User;
> 
>        @PrimaryColumn() 
>        placeId: number;
> 
>        @ManyToOne(() => Place, ...) // inverse "userPlaces: UserPlace[]" is one-to-many in place
>        @JoinColumn({ name: "placeId" })
>        place: Place;
> 
>        @Column()
>        anyOtherColumnYouWant: string;
> 
> }
> ```
> 
> Again, you don't need to use `@ManyToMany` in this particular scenario.



> As I answered you in gitter you should create a separate entity `user` and `place` relations and add any number of additional columns you want.
> 
> You don't need to use `@ManyToMany` in this particular scenario. ManyToMany is just a junction table that directly connects two tables, nothing else.
> 
> Example:
> 
> ```ts
> @Entity()
> export class UserPlace {
> 
>        @PrimaryColumn() 
>        userId: number;
> 
>        @ManyToOne(() => User, ...) // inverse "userPlaces: UserPlace[]" is one-to-many in user
>        @JoinColumn({ name: "userId" })
>        user: User;
> 
>        @PrimaryColumn() 
>        placeId: number;
> 
>        @ManyToOne(() => Place, ...) // inverse "userPlaces: UserPlace[]" is one-to-many in place
>        @JoinColumn({ name: "placeId" })
>        place: Place;
> 
>        @Column()
>        anyOtherColumnYouWant: string;
> 
> }
> ```
> 
> Again, you don't need to use `@ManyToMany` in this particular scenario.

Thank you. You just saved my day

**Comment by jarrus90** [comment]
If anyone will return here - i found a solution. Just @JoinTable({synchronize: false}) and relation is not creating automatically, so you can create your own definition with extra data, but when using ManyToMany relation you will not have access to this metadata, you will need to request it by your own.

**Comment by basemkhirat** [comment]
> pleerock

Thanks. But why we need to define two primary columns (userId, placeId). are these already created by joinColumn decorators?

**Comment by leonghia** [comment]
> ```js
> @Entity()
> export class UserPlace {
> 
>        @PrimaryColumn() 
>        userId: number;
> 
>        @ManyToOne(() => User, ...) // inverse "userPlaces: UserPlace[]" is one-to-many in user
>        @JoinColumn({ name: "userId" })
>        user: User;
> 
>        @PrimaryColumn() 
>        placeId: number;
> 
>        @ManyToOne(() => Place, ...) // inverse "userPlaces: UserPlace[]" is one-to-many in place
>        @JoinColumn({ name: "placeId" })
>        place: Place;
> 
>        @Column()
>        anyOtherColumnYouWant: string;
> 
> }
> ```
> 
> Thanks. But why we need to define two primary columns (userId, placeId). are these already created by joinColumn decorators in ManyToOne relationships?

`@JoinColumn()` if you want to use custom columns as PK, otherwise there's no need to define them manually as `@ManyToOne()` already handle that for you.

**Comment by danyalutsevich** [comment]
userId and placeId is needed
it does not work without primary columns, they are not created automatically
typeorm v0.3.20

**Comment by dberardo-com** [comment]
is it possible to use the query builder to do a 3 way join of a manytomany relation that also includes properties in the jointable column. example:

* table User
* table Documents
* table Shares - joinTable

the table Shares is the join table and includes also a column "permission" 

i am  trying to use leftJoinAndMapMany but i am not able to figure out how to return an array of objects of this kind:


UserDocuments = [{
userId: 
userName: 
documentId:
documentName:
shareId:
sharePermission: 
}]

i can only manage to get it in a "raw" form but not in a nicely mapped form
