### ISSUE TITLE
TypeError: Cannot read property 'COLLATION' of undefined

### ISSUE THREAD

**Issue by RAJKS87** [typeorm/typeorm#2403]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Getting below error when I tried to insert the second record into a mariadb table. 

`TypeError: Cannot read property 'COLLATION' of undefined
    at MysqlQueryRunner.<anonymous> (/Users/z244282/Desktop/MyProject/src/driver/mysql/MysqlQueryRunner.ts:1154:49)
    at step (/Users/z244282/Desktop/MyProject/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:42:23)
    at Object.next (/Users/z244282/Desktop/MyProject/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:23:53)
    at /Users/z244282/Desktop/MyProject/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/z244282/Desktop/MyProject/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:12)
    at /Users/z244282/Desktop/MyProject/src/driver/mysql/MysqlQueryRunner.ts:1150:54
    at Array.map (<anonymous>)
    at MysqlQueryRunner.<anonymous> (/Users/z244282/Desktop/MyProject/src/driver/mysql/MysqlQueryRunner.ts:1150:37)
    at step (/Users/z244282/Desktop/MyProject/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:42:23)`

Steps to reproduce the issue. 
1. Creare a sample with command 
`typeorm init --name MyProject --database mariadb`.

2. npm start works fine for the first time.  got below output. 

`Inserting a new user into the database...
Saved a new user with id: 1
Loading users from the database...
Loaded users:  [ User { id: 1, firstName: 'Timber', lastName: 'Saw', age: 25 } ]
Here you can setup and run express/koa/any other framework.`

3. npm start again gives the above error.

**Comment by pleerock** [comment]
can you please update typeorm version installed by `init` command to latest and try again?

**Comment by RAJKS87** [comment]
I have tried with the version `0.2.7`. Still I am getting the same error.

**Comment by pleerock** [comment]
I can only assume it is related to your mariadb version? Are you using the old version? Can you try on newer versions? Also try on mysql or some other db if possible

**Comment by scotzark** [comment]
BTW...this might be an issue on Mac w/ mySQL...I am able to remotely save entries to an Ubuntu instance I have setup.

**Comment by FLZz** [comment]
@pleerock emmmmmm， I just started learning node, and I met this problem。Interestingly, I found this to be due to the database naming problem.
I'm using MySQL.
When I first started the service with a lowercase name, the log showed that the table was created successfully and the database was connected successfully, and the service was started normally the second time.
But when I use a mixed case name, an error occurs the second time: "Cannot read property 'COLLATION' of undefined."
Limited level, can not find the basic reason ---来自有道翻译

**Comment by apissotte** [comment]
I have the same problem :
TypeError: Cannot read property 'COLLATION' of undefined
    at MysqlQueryRunner.<anonymous> (/Users/x/Desktop/TypeORMServer/src/driver/mysql/MysqlQueryRunner.ts:1154:49)
    at step (/Users/x/Desktop/TypeORMServer/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:42:23)
    at Object.next (/Users/x/Desktop/TypeORMServer/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:23:53)
    at /Users/x/Desktop/TypeORMServer/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/x/Desktop/TypeORMServer/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:12)
    at /Users/x/Desktop/TypeORMServer/src/driver/mysql/MysqlQueryRunner.ts:1150:54
    at Array.map (<anonymous>)
    at MysqlQueryRunner.<anonymous> (/Users/x/Desktop/TypeORMServer/src/driver/mysql/MysqlQueryRunner.ts:1150:37)
    at step (/Users/x/Desktop/TypeORMServer/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:42:23)

Does someone have a solution to this ?

**Comment by scotzark** [comment]
I was trying to run on mac.  It worked fine after switching to Linux.

**Comment by sylar107** [comment]
Same issue on mac with MariaDB / MySQL

**Comment by sylar107** [comment]
Problem source found, its not issue with TypeORM but with macOS version of MySQL.

It does not support capital letters in table names. It stores values to INFORMATION_SCHEMA.TABLES properly, but when reading from it returns them lowercase, thus not finding 'COLLATION'.

**Comment by scotzark** [comment]
Good catch.  For me, my deployment environment was Linux, I was just trying to use my Mac for quick development.  Once I moved over to Linux things worked well.  But this is good for others who might run into this.  Nice job.

**Comment by ah-yu** [comment]
Hi all, I met the same problem. Setting `lower_case_table_name=1` seems not work for me. Does someone have a solution to this ?

**Comment by jsadowski** [comment]
The problem still occurs in osx, typeorm, mariadb and lower_case_table_name=1 doesn't help as that variable is readonly. Has anyone idea how to fix it?

**Comment by daihovey** [comment]
I have same issue. Although if I nuke the table, and it has to CREATE TABLE first, it works, but subsequent inserts don't. 🤷‍♀️

**Comment by vjee** [comment]
I was running into the same problem, and the `my.cnf` trick didn't seem to work.
For me, what **_did work_** was ensuring the table's **_name_** was entirely **_lowercase_**. Eg: `Table` -> `table`.

**Comment by rednebmas** [comment]
In my case, the issue was using capital letters in my database name. E.g. `TypeORMTestDB` -> `typeormtestdb`.

**Comment by OCarvajalMora** [comment]
> In my case, the issue was using capital letters in my database name. E.g. `TypeORMTestDB` -> `typeormtestdb`.

This work for me too.

**Comment by SawickiKamil** [comment]
> In my case, the issue was using capital letters in my database name. E.g. `TypeORMTestDB` -> `typeormtestdb`.

That's right, this works for me too. Don't use capital letters naming your database.

**Comment by LuisAlejandro** [comment]
I think there should be at least a check here to throw a proper error when no collation is found https://github.com/typeorm/typeorm/blob/a909d5b6975f0feb0c8759dd146dba8f1e3ad168/src/driver/mysql/MysqlQueryRunner.ts#L2488

**Comment by Ousha23** [comment]
I had the same problem, I changed the name and made it in lowercase and that resolved the problem for me

**Comment by Griffin-restoration** [comment]
https://nodeer.space/questions/encountering-an-issue-when-trying-to-insert-the-query-into-the-database i located the answer
