### ISSUE TITLE
STI with mongodb - working?

### ISSUE THREAD

**Issue by benkrugerde** [typeorm/typeorm#2405]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
https://github.com/benkrugerde/nestjs-typeorm-test

Hi there,

we're currently evaluating typeorm with nestjs using mongodb to store data.

We have different classes for representing different data and behavior for e.g. persons and we want to store them in one single collection.
This is working with the STI-Strategy as described in the documentation.

If i use the PersonRepository to find students and employees, i get 2 entries back of type person.
I would expect to get one student and one employee, because i'm using the TableInheritance- and the ChildEntity-Decorators with discriminator settings.

Is this currently WIP or is this not supported in mongodb?
If so, does anyone has a workaround for this?

Thanks for your reply.

Heres are some snippets from the project:

person.entity.ts
```
@Entity('sample28_person')
@TableInheritance({ column: { name: 'type', type: 'varchar'} } )
export abstract class Person {

    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    type: string;

}
```

student.entity.ts
```
@ChildEntity('student')
export class Student extends Person {

    constructor(){
        super();
        this.type = 'student'; //the type field is not set by typeorm - i do it by myself
    }

    @Column()
    faculty: string;

}
```
```
@ChildEntity('employee')
export class Employee extends Person {
    constructor(){
        super();
        this.type = 'employee';
    }
    @Column()
    salary: number;

}
```

person.service.ts

```
@Injectable()
export class PersonService {
    constructor(
        @InjectRepository(Person)
        private readonly personRepository: Repository<Person>,

        @InjectRepository(Employee)
        private readonly employeeRepository: Repository<Employee>,

        @InjectRepository(Student)
        private readonly studentRepository: Repository<Student>,
    ) { }

    async createSample() {

        const employee = new Employee();
        employee.firstName = 'umed';
        employee.lastName = 'khudoiberdiev';
        employee.salary = 200000;
        await this.employeeRepository.save(employee);

        const student = new Student();
        student.firstName = 'umed';
        student.lastName = 'khudoiberdiev';
        student.faculty = 'computer science';

        await this.studentRepository.save(student);
    }

    async findSample() {
        return await this.personRepository.find();
    }
}
```

**Comment by pleerock** [comment]
Please note that most of TypeORM features are rdbms-specific, including STI. I don't think we would ever do similar things for MongoDB.

**Comment by marcorinck** [comment]
I'm currently investigating something similar with a cordova (ionic) database. There is a problem getting repositories for the ChildEntities there and when I use the Repository for the ParentEntity to save the ChildEntities I get instances of the ParentEntity when I re-read them from the database.

However, when I use the connectionManager directly to save the ChildEntities I get correctly  instanced child entity objects even when I use the ParentEntitiy repository.

Like this: 

```` 
  const tenant = new Tenant(); //Tenant is the ChildEntity of Person
  ....
  await connection.manager.save(tenant);

  const repository = getRepository("person") as Repository<Person>;
  const persons = respository.find();  //contains one object of type Tenant

````  

maybe try so save your child entities like this and try if it works.

**Comment by pleerock** [comment]
@marcorinck how your issue is related to this issue?

**Comment by pleerock** [comment]
> Maybe somone could help make this happen or give some short ideas where to find necessary classes and methods.

@benkrugerde not sure what you mean, I answered you that STI is rdbms-only feature.

**Comment by marcorinck** [comment]
@pleerock I also got an array of instanced ParentEntities despite writing ChildEntities (via ParentEntityRepository)

**Comment by pleerock** [comment]
point of this issue mongodb support.

**Comment by benkrugerde** [comment]
@pleerock  yes i understand that this is a rdms-only feature. Lets call it Single-Collection-Inheritance.
I got a look in your code and i think this is more an issue with the Metadata and Class-Transformer than an issue with mongodb.

The EntityMetadata for Person is built well by the Metadatacreator. The only thing i do not understand is where the Transformer decided to Transform to Base- or ChildEntity.

Maybe this describes a bit more what i need. Doctrine is doing sometihing similar to my needs:
https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/inheritance-mapping.html

Thank you
Ben

**Comment by benkrugerde** [comment]
@pleerock  i have a quick and dirty solution but working for me:

In DocumentToEntityTransformer.ts

```
resolveChildEntity(document: any, metadata: EntityMetadata) {
        const childs = metadata.childEntityMetadatas;
        let retEntity = undefined;

        if (!metadata.discriminatorColumn)
            return metadata.create();

        const discriminatorColumn = metadata.discriminatorColumn;
        const discriminatorColumnField = discriminatorColumn.databaseNameWithoutPrefixes;

        childs.forEach((childEntityMetadata) => {
            if (childEntityMetadata.discriminatorValue === document[discriminatorColumnField]) {
                retEntity = childEntityMetadata.create();
            }
        });

        return retEntity;
    }
```

and in transform replace

```
const entity: any = metadata.create();
```

with:

```
const entity: any = this.resolveChildEntity(document, metadata);
```

Just a 10 minute solution i know, but maybe something for the future

Benjamin

**Comment by pleerock** [comment]
thanks for your proposal, but as I told I don't have in plans to add such table inheritance for the mongodb in a near future for sure.

**Comment by benkrugerde** [comment]
@pleerock  are there any reasons why not?
We decided to use typeorm for mongodb and postgres usage. 
But if there are any limitations please let me know.

**Comment by pleerock** [comment]
mongodb issues and features take lot of time, currently we have different priorities and cannot spend lot of time time to those features. 

please consider supporting typeorm, so we can spend more time on it and make features faster.
