### ISSUE TITLE
Problem using find-options on repository or manager.

### ISSUE THREAD

**Issue by mpycio** [typeorm/typeorm#2408]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm trying to follow this information http://typeorm.io/#/find-options but I'm unable to specify any of the listed options (select, relations, order) and getting the following error:

Object literal may only specify known properties and 'where' does not exist in type 'FindConditions<xxx>'

'where' becomes 'relations' or 'order' depending on first option specified.

```
this.reportRepository.find({
  where: {},
  relations: ['fss'],
  order: {date_created: 'DESC'},
});
```

same problem happens when I'm trying to use manager:

`this.reportRepository.manager.find`

I'm clearly missing something simple but looking at signature of the find method I can't see how I could pass any of the options.

**Comment by pleerock** [comment]
you definitely do something wrong, if you provide some real code or repo I can help you to find a problem.

**Comment by mpycio** [comment]
I am doing something wrong but error was a bit misleading, I used a column name from the database and not a property name from the Entity in the order clause in the code example above and IDE was leading me to FindConditions<Entity> instead of FindManyOptions<Entity> so I got completely stuck looking in a wrong place. All sorted now and I don't think there's a way to improve this error so I'll close this issue.

**Comment by php1webmobtech** [comment]
@mpycio what's the solution??

**Comment by ebragaparah** [comment]
@mpycio I got the same problem and I solved it doing a explicit cast on my options object.

```
let options = {
    where: { <conditions> },
    order: { <order criteria> },
    relations: [ <relation string, if exists> ],
    skip: <skip length>,
    take: <take length>,
} as FindManyOptions;
```

its 2020, maybe you dont need it anymore :sweat_smile:
