### ISSUE TITLE
Error with alias in QueryBuilder for SQLite

### ISSUE THREAD

**Issue by otgerrogla** [typeorm/typeorm#241]
SQLite doesn't seem to support aliases on queries such as DELETE or UPDATE, so code generated like
` UPDATE "table" "t" SET "t"."field" = 1 ` fails with `SQLITE_ERROR: near ""t"": syntax error`. 

A workaround is to use an empty string in ``createQueryBuilder("")``, which does not write the alias. However, fields are still rewritten as ` ""."field" ` which causes an error.
Adding a check ``if (!alias.name) return;`` at ``QueryBuilder.replacePropertyNames`` ([QueryBuilder.ts:1500](https://github.com/typeorm/typeorm/blob/master/src/query-builder/QueryBuilder.ts#L1500)) fixes this last problem for me.

But it still seems a hack. Maybe the parameter in `createQueryBuilder()` should be made optional (even if it's just then internally filled in with an empty string), as in most DELETE/UPDATE queries there is not usually the need to use an alias anyway.

**Comment by pleerock** [comment]
This is a bug. As far as I remember I already fixed this for DELETE query, now its turn to UPDATE. Please use your hack, I'll fix this issue in next version of typeorm.

**Comment by maxcan** [comment]
just ran into this.  looking forward to the fix

**Comment by jjude** [comment]
I'm also running into this error. As of now, gone ahead with the hack proposed by @otgerrogla. Do we know when this will be fixed?

**Comment by Jeremias-Tecnom** [comment]
I have used @otgerrogla fix, but it would be great a permanent fix!

**Comment by pleerock** [comment]
This was already fixed in recent versions.
