### ISSUE TITLE
typeorm scaffold tsconfig.json file needs an update

### ISSUE THREAD

**Issue by ORESoftware** [typeorm/typeorm#2412]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`typeorm init --name MyProject --database mysql
`

yields this tsconfig.json file:

```
{
  "compilerOptions": {
    "lib": [
      "es5",
      "es6"
    ],
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./build",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  }
}
```

but in 2018, it should look like this:

```
{
  "include": [
    "src"
  ],

  "compilerOptions": {
    "skipLibCheck": true,
    "lib": [
      "es5",
      "es6"
    ],
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "dist",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  }
}
```

**Comment by pleerock** [comment]
> but in 2018, it should look like this

where did you get that information? =)

* `skipLibCheck` can be source of issues sometimes and at the same time its addition does really adds something
* `target: es6` well some older node users definitely will have issues 
* `include: src` what if user have test directory? He tries to add test and run them but fails because he don't know that somebody configured compiler for only src directory

**Comment by ORESoftware** [comment]
ourDir is build, so `include: ["src"]`, should definitely be set. You wouldn't want both src and test directories transpiled to the dist folder, that would be incorrect.

**Comment by pleerock** [comment]
> "ourDir" is set to "build", so include: ["src"]

we can exclude build

> You wouldn't want both src and test directories transpiled to the dist folder, that would be incorrect.

why? where do you want test output to go? distTest? dist also isn't the best name for both source and tests, thats why current build is the best name for it.
