### ISSUE TITLE
Feature/question - static JSON config files for models

### ISSUE THREAD

**Issue by ORESoftware** [typeorm/typeorm#2413]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`

I've used a variety of DBs in the Node.js world as well as some ORMs - I have used Loopback from StrongLoop - and using Loopback you could do database migrations both ways: from **code --> db**, or from **db --> code**, depending on which was your source of truth.

So if your DB was the source of truth, you would run a migration, and given the db, Loopback could generate static JSON files that represented the DB, and then Loopback would use those models.

So my question is - if the DB is the source of truth, instead of the code (this is true once you get more into production territory) is there a way to update the TypeORM code?

The only way I could see this is happening - is by doing what Loopback does - using JSON files which represent the DB models.

**Comment by pleerock** [comment]
TypeORM's concept is different. Code (e.g. models) is a source of truth.

**Comment by ORESoftware** [comment]
I am just saying that Loopback has both concepts.  Loopback can operate where the DB is the source of truth, or where the code is source of truth. It looks like TypeORM is just the latter. That is ok, because that is more common use case especially for startups where Node.js is more likely to be used.
It's just an idea.
