### ISSUE TITLE
entity code generation is not complete

### ISSUE THREAD

**Issue by ORESoftware** [typeorm/typeorm#2414]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

I run:
```bash
typeorm entity:create -n Mike
```

I get:

```js
import {Entity} from "typeorm";

@Entity()
export class Mike {

}
```

I start server, I get error:

>    'Entity "Mike" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.' }

So maybe do you think the code generation routine should add another imported property? : ]

**Comment by ORESoftware** [comment]
in other words, the code generation should just do this instead:

```js
import {Entity, PrimaryGeneratedColumn} from "typeorm";

@Entity()
export class Mike {

  @PrimaryGeneratedColumn()
  id: number;

}
```

**Comment by pleerock** [comment]
I don't think its that important, lets see if somebody vote on this.

**Comment by pleerock** [comment]
Im afraid that somebody can think that its required to have a column named "id" that should be a number with generated value.

**Comment by pleerock** [comment]
so no, probably its better not to do what was proposed.
