### ISSUE TITLE
A select query builder with an empty `WHERE IN` parameter causes a query error

### ISSUE THREAD

**Issue by shusson** [typeorm/typeorm#2417]
**Issue type:**
[x] question
[x] feature request

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x ] `0.2.5` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

We have a select query that looks like this:
```
 this.departmentRepository
   .createQueryBuilder("department")
   .where("department.id IN (:...ids)", { ids: ids });
```

If the `ids` array is empty we get the following error:

```
2018-06-26T08:47:13.022Z error: syntax error at or near ")"
2018-06-26T08:47:13.045Z error: QueryFailedError: syntax error at or near ")"
```

Can TypeORM ignore the `where` clause if the value of the parameter is empty?

**Comment by dlaynes** [comment]
You already wrote a condition to be fulfilled. Do this instead

`var query = this.departmentRepository
   .createQueryBuilder("department");
  if(ids.length){
    query.where("department.id IN (:...ids)", { ids: ids });
 }`

**Comment by shusson** [comment]
@dlaynes yes we currently do that, but it feels like TypeORM should/could handle this itself.

**Comment by dlaynes** [comment]
The method is already doing a lot of work expanding and inserting the variables. For empty arrays I would throw an exception, instead of breaking the single responsibility principle.

**Comment by shusson** [comment]
Yeah it's personal flavour but either way it would be good to have a better exception message.

**Comment by vlapo** [comment]
I think handle this in custom where statements is too complex. But there is issue about `In` find operator. 

Close this issue in favour of https://github.com/typeorm/typeorm/issues/2195.
