### ISSUE TITLE
Cannot use async/await due to TS compilation errors

### ISSUE THREAD

**Issue by antoniovazquezblanco** [typeorm/typeorm#2420]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

**Steps to reproduce or a small repository showing the problem:**

Code:
```
import 'reflect-metadata'
import { createConnection } from 'typeorm'

const conn = await createConnection(...)
```

Error:
```
error TS1308: 'await' expression is only allowed withing an async function.
```

TypeScript is complaining about the async/await definitions. Can anybody explain why is this happening?

**Comment by pleerock** [comment]
this is now JavaScript async/await syntax work - you can use `await` only in `async` function. Read more in the internet.

**Comment by antoniovazquezblanco** [comment]
That snippet almost comes from your documentation (see: http://typeorm.io/#/connection-api). From what I know, `createConnection` is an `async` function.

**Comment by pleerock** [comment]
right, code snippets are made this way for the simplicity, they assuming you already know javascript and how async/await works.

**Comment by antoniovazquezblanco** [comment]
Ok. Sorry for the disturbance. I will look harder for a solution. Thank you

**Comment by pleerock** [comment]
You can simply do:

```ts
async () => {
     const conn = await createConnection(...)
}()
```

or usually I do don't use await for top-level code and simply use classic promise's `then` method:
```ts
createConnection(...).then(async connection => {
      // do whatever you want with connection and use await if you want since its an async function
});
```

**Comment by antoniovazquezblanco** [comment]
Thank you.

From what I've read after this, await cannot be used unless you are withing a async function just in case anyone finds himself in the same situation.

Again sorry for the noob question.

**Comment by OSA413** [comment]
Indeed returning a chained promise for migration data source worked just fine.
