### ISSUE TITLE
Running tests against MSSQL

### ISSUE THREAD

**Issue by vance** [typeorm/typeorm#2421]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x] `latest` - master
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

run tests against MSSQL (linux docker). Successful connection, however immediately get this failure on first and any runs:

```
cascades > should insert by cascades from both sides (#57)
       "before each" hook for "should insert by cascades from owner side":
     QueryFailedError: Error: Cannot drop the table '#A2DCA339', because it does not exist or you do not have permission.
 at new QueryFailedError (src/error/QueryFailedError.ts:7:9)
      at /Users/m82878/code/typeorm/src/driver/sqlserver/SqlServerQueryRunner.ts:220:37
      at _query (node_modules/mssql/lib/base.js:1253:25)
      at Request.tds.Request.err [as userCallback] (node_modules/mssql/lib/tedious.js:620:15)
      at Request._this.callback (node_modules/tedious/lib/request.js:60:27)
      at Connection.endOfMessageMarkerReceived (node_modules/tedious/lib/connection.js:1906:20)
```

**I am using the sa user with correct password. Is it trying to drop the table before it exists during test setup?**

**Comment by pleerock** [comment]
```ts
QueryFailedError: Error: Cannot drop the table '#A2DCA339', 
```

This is a very strange error. Who is trying to remove named `#A2DCA339` and who even created it? Do you use image from `docker-compose` of typeorm?

**Comment by vance** [comment]
This was just using the latest MSSQL linux image from MS, and running the spec with the right credentials (the first time).

**Comment by pleerock** [comment]
Try to run mssql image that comes with typeorm repo inside docker-compose file. Just run it via docker-compose up in the root of typeorm project.

**Comment by Kononnable** [comment]
@vance 
Did you resolve your issue?

**Comment by vance** [comment]
sorry, really behind. I am planning on coming back to this soon, as I also have a meeting with the committee to contribute back for custom naming strategies.

**Comment by havenchyk** [comment]
I'm closing this issue for housekeeping purposes, if something is not clear yet, just continue the conversation or post a message in slack
