### ISSUE TITLE
Result set processing performance issue when using @RelationId

### ISSUE THREAD

**Issue by hielkehoeve** [typeorm/typeorm#2424]
**Issue type:**

[] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.6`

**Steps to reproduce or a small repository showing the problem:**

I am having a performance issue when loading a lot of records from an entity, resulting in very slow result set processing. We have written memory/redis cache logic which uses the relation id to lazy load the relation for us, but obviously the `@RelationId` makes our application terribly slow. Removing the `@RelationId` forces us to write custom queries for a number of business logic methods while currently the default select query combined with lazy loading/memory cache works quite well.

This problem seems similar to https://github.com/typeorm/typeorm/issues/1672. I have created a sample application to demonstrate my problem: https://github.com/hielkehoeve/typeorm/tree/master/test/github-issues/2424. The problem seems to be related to the `@RelationId` annotation. 

When fetching different amounts of an entity (any) the performance deteriorates very quickly when loading larger amounts.

amount  | EntityD        | EntityC       | EntityA
-------- | ----------- | ----------- | -----------
100        | 55ms           | 52m            | 52ms
1000      | 2042ms      | 2114ms      | 2179ms
10000    | 200846ms | 201482ms | 21238ms

(100000 items took too long, 200s+).

When I remove the `@RelationId` field and annotations the performance is very good:

amount | EntityD      | EntityC      | EntityA
-------- | ---------- | ---------- | -----------
100        | 3ms           | 3ms           | 3ms   
1000      | 18ms         | 12ms          | 14ms   
10000    | 110ms       | 120ms        | 125ms   
100000  | 1155ms     | 1170ms      | 1186ms

**Comment by pleerock** [comment]
Relation Id is something worth refactoring, but its not a priority yet. I guess for now I can recommend you to make a separate queries and increase a boilerplate code in your app a bit...

**Comment by Jusonex** [comment]
It took me almost an hour to find out that my application got ultra slow due to using the `RelationId` decorator (my typical result set is ~10000 entities). 

10000 is not incredibly much and therefore I think the `RelationId` is almost unusable in most application contextes (even a full join is faster whereas preventing that was the purpose of `RelationId`) and this impact should at least be documented as long as it doesn't work appropriately.
