### ISSUE TITLE
Is there any way to just check if query return a result or nothing ?

### ISSUE THREAD

**Issue by ecalafat** [typeorm/typeorm#2425]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[0.2.7] `0.x.x` (or put your version here)

Hi,
First of all I'd like to thank you for your job, this tool is really good and easy to use.

I would like to know if there is any way to know if my query return a result or not

Basically something like this.

checkIfExist(value: string): Promise<boolean> {
        const myRepository = getConnection().getRepository(Entity).createQueryBuilder('entity')
            .where('entity.value= :value', { value: value});

        return accidentRepository.Any();
    }

Hope you can help me.

Have a nice day

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by DirkDeVisser** [comment]
If you use `getMany` on the query builder you will get an empty array if there are no results. For example:

``` ts
public async checkAtLeastOne(value: string): Promise<boolean> {
    const result = await getConnection()
        .getRepository(Entity)
        .createQueryBuilder('entity')
        .where('entity.value= :value', { value: value})
        .getMany();
    return result.length >= 1;
}
```
If you want one result and use `getOne` on the query builder then you can check if it is undefined. For example: 

``` ts
public async checkIfExists(value: string): Promise<boolean> {
    const result = await getConnection()
        .getRepository(Entity)
        .createQueryBuilder('entity')
        .where('entity.value= :value', { value: value})
        .getOne();
    return result !== undefined;
}
```

**Comment by hielkehoeve** [comment]
```I would like to know if there is any way to know if my query return a result or not```

You could use a count query to check how many rows you would fetch. This is the fastest option out of all the API calls.

```public async checkIfExists(value: string): Promise<boolean> {
    return await getConnection()
        .getRepository(Entity)
        .createQueryBuilder('entity')
        .where('entity.value= :value', { value: value})
        .getCount() > 0;
}```

**Comment by pleerock** [comment]
I guess this can be closed, thanks everyone for the help!
