### ISSUE TITLE
The correct way to change ormconfig.json by env 

### ISSUE THREAD

**Issue by ORESoftware** [typeorm/typeorm#2426]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I don't think this is documented, but it should be - my question is, for the ormconfig.json file - how do we change the configuration based on env variables?

Or perhaps we can load different configuration files based on the env?

I have a question/answer here:
https://stackoverflow.com/questions/51054702/using-different-ormconfig-json-files-depending-on-env/51089439#51089439

**Comment by pleerock** [comment]
there is a note in the documentation that you can't use both - you need to use only one of the configuration source.

**Comment by ORESoftware** [comment]
yeah I think the default config file should just be the .js file, but yeah.

**Comment by AndrewRayCode** [comment]
I think this should be documented too, having a separate config file per env, and/or different configs per env, is pretty common

**Comment by IRCraziestTaxi** [comment]
@AndrewRayCode is right. Having separate config files per environment is very common. I'm having a time trying to figure out how to use the correct connection in a pipeline without [having to do something like this](https://stackoverflow.com/a/51089439/1778164).

**Comment by ORESoftware** [comment]
I wouldn't use a different config file by env, I would recommend just using env vars like so:

```js
module.exports = {
   "port": process.env.port,
   "host": process.env.host,
  // etc
}
```

**Comment by IRCraziestTaxi** [comment]
I decided to go with gulp with pre-build tasks to copy `ormconfig.*.json` to `ormconfig.json` (which is ignored by git). Seemed kind of heavy at first, but I feel like it's pretty clean in the end.

```js
// gulpfile.js

const { dest, src } = require("gulp");
const rename = require("gulp-rename");

function defaultTask(cb) {
    console.log("Default task is not defined. See \"gulp --tasks\" for build tasks.");

    cb();
}

function dev() {
    return src("./ormconfig.dev.json")
        .pipe(rename("ormconfig.json"))
        .pipe(dest("."));
}

function local() {
    return src("./ormconfig.local.json")
        .pipe(rename("ormconfig.json"))
        .pipe(dest("."));
}

function prod() {
    return src("./ormconfig.prod.json")
        .pipe(rename("ormconfig.json"))
        .pipe(dest("."));
}

function test() {
    return src("./ormconfig.test.json")
        .pipe(rename("ormconfig.json"))
        .pipe(dest("."));
}

exports.default = defaultTask;
exports.dev = dev;
exports.local = local;
exports.prod = prod;
exports.test = test;
```

```json
// package.json (excerpt)

  "scripts": {
    "build-dev": "gulp dev && \"node_modules/.bin/tsc\"",
    // ...
    "build-prod": "gulp prod && \"node_modules/.bin/tsc\"",
    "build-test": "gulp test && \"node_modules/.bin/tsc\"",
    // ...
    "tsc": "gulp local && \"node_modules/.bin/tsc\" --project tsconfig.local.json",
    // ...
  },
```

**Comment by sultanguvenbas** [comment]
But when use like this it is given me an error which is 
ERROR [ExceptionHandler] role "....." does not exist
error: role "sulta" does not exist


Someone can help me please?
