### ISSUE TITLE
Force DISTINCT?

### ISSUE THREAD

**Issue by iamgmd** [typeorm/typeorm#2429]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there a way to force DISTINCT? I have a few use cases where I need to perform a SELECT DISTINCT without take or skip. i.e. if (firstField) { sqb.selectDISTINCT(<field>) } else { sqb.addSelect(<field>) }

**Comment by pleerock** [comment]
can you show a complete sql query you need?

**Comment by zWaR** [comment]
@pleerock 
The objective is to generate a query like this:
```sql
SELECT DISTINCT t1.a
FROM table t1;
```

The following will not work, even though `getSql()` will return a correct SQL statement:

```ts
getConnection()
  .createQueryBuilder(Table, 't1')
  .select('DISTINCT t1.a')
  .getMany();
```

So the question is how to correctly get a SELECT DISTINCT clause?

**Comment by LogansUA** [comment]
Same question, how can I use DISTINCT in query builder?

**Comment by pleerock** [comment]
you need to get raw results if you select something other than entity, use `getRawMany` instead of `getMany()`

**Comment by omarargueles** [comment]
if I do some like:
```
getConnection()
  .createQueryBuilder(Table, 't1')
  .select('DISTINCT ON (t1.a) a')
  .addSelect('t1.id')
  .getMany();
```

This creates a query where like:
```
Select "t1"."id", DISTINCT ON (t1.a)...
```

Which will give an error in Distinct On because is in a second place instead of start the list of elements with it.

There is a way of forcing the Select statement to respect the order? or am I doing something wrong?

**Comment by JorgeBrs** [comment]
@zWaR @iamgmd @pleerock 

but when I want to pass more than one property in the select it throws me an error.

what I did to solve my mistake while I found a solution proposed by typeOrm was to change the distinct to a groudby

something like this:

getConnection()
  .createQueryBuilder(Table, 't1')
  .select('t1.a')
 ..groupBy('t1.id')
  .getRawMany();

**Comment by Diegorandom** [comment]
What if I need something like this
`let mbolScan = await getRepository(L)
        .createQueryBuilder("l")
        .select('l.a')
        .addSelect('b')
        .addSelect('loadout.c')
        .groupBy('loadout.al')
        .addGroupBy('loadout.b')
        .getRawMany()`
