### ISSUE TITLE
Slow batch write performance

### ISSUE THREAD

**Issue by p3v9d5ui** [typeorm/typeorm#2430]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[x ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

My application is importing a database of about 200,000 records (each record about 500 bytes). I write these records to a Typeorm database at 1000 records at a time. Each save of 1000 records takes about 18 seconds when using cordova storage (on device) and about 10 seconds using sqljs (testing in browser). Is this unusually slow, or should I expect this type of performance?

The latest version of TypeOrm actually resulted in worse performance. I just upgraded from v0.1.21 -- with that earlier version, the cordova performance was about 11 seconds.

An earlier issue discussing batch write performance indicated that v0.2 would improve performance, but I'm seeing the opposite:

https://github.com/typeorm/typeorm/issues/1115

Any feedback?

**Comment by pleerock** [comment]
in 0.2 batch inversion performance was greatly improved. I can suggest you to try to use `insert` method instead of `save` and compare difference

**Comment by p3v9d5ui** [comment]
Just tried this, but actually found insert() to be slower. In my test case, repository.insert() took about 1.8x the time that repository.save() took, for the same records.

**Comment by 19majkel94** [comment]
@pleerock 
I've tried using `insert` and the time was reduced to 800ms from 3300ms for 10k records. However when I try to write 50k records, I receive this error:
```
Error: bind message supplies 18928 parameters, but prepared statement "" requires 150000
```
And it prints the whole prepared statement `INSERT VALUES` 😕 	

So looks like I have to manually find the limit and push the inserts in groups?

**Comment by leandrogehlen** [comment]
I think, is not necessary use variables in bulk insert.

**Comment by imnotjames** [comment]
It's very necessary to use variables in a bulk insert if we want to prevent SQL injection.  If you're inserting 10k records at once there's not a whole lot we're able to do about that.  We'll send that to the underlying module but if it can't support it, not a whole lot else that can be done.

This is a few years old now without much activity.  I'm going to be closing it out.

Let me know if there's anything else I can do to help with this.
