### ISSUE TITLE
QueryBuilder insert for Oracle failed

### ISSUE THREAD

**Issue by yuluyi** [typeorm/typeorm#2434]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
await queryRunner.manager.createQueryBuilder()
          .insert()
          .into(Person)
          .values(people)
          .execute()

// { Error: ORA-00933: SQL command not properly ended errorNum: 933, offset: 140 }
```

Oracle seems doesn't support syntax like INSERT INTO xxx VALUES (value1, ...), (value2, ...)

**Comment by pleerock** [comment]
ah batch insertion is not supported by oracle. Please use a regular for loop over your values and insert data within multiple queries

**Comment by wfpena** [comment]
I created a PR to solve this issue #6927
