### ISSUE TITLE
Postgres LISTEN/NOTIFY

### ISSUE THREAD

**Issue by matt328** [typeorm/typeorm#2436]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Maybe I'm missing something, but how can I listen to Postgres notifications?  Using pg, it's possible like this:

```
var pg = require ('pg');

var pgConString = "postgres://localhost/bjorngylling"

pg.connect(pgConString, function(err, client) {
  if(err) {
    console.log(err);
  }
  client.on('notification', function(msg) {
    console.log(msg);
  });
  var query = client.query("LISTEN watchers");
});
```
My question boils down to how do I get a reference to the `client` instance?

**Comment by matt328** [comment]
After researching a little more into how postgres' listen/notify works, I think its best to handle this outside of the scope of typeorm.

For anyone else finding this, my understanding is that in order to listen to notifications from Postgres,  a long-lived, persistent `connection` is needed.  With typeorm using a pool of connections for efficiency, even if I could get a reference to a `client`, it would be ephemeral as its `connection` comes from the `pool` and will be closed and returned to the pool as soon as the `LISTEN` query finished executing.  Therefore the call to `on` and the `LISTEN` query would not persist.

I decided to use https://github.com/voxpelli/node-pg-pubsub alongside typeorm for listening to db notifications.

**Comment by pleerock** [comment]
Thanks for the research you did, it good to know limitations of using listen/notify we'll have

**Comment by jonathanroze** [comment]
I thank i would be a good idea to implement "on" method. 

Used another database library to just do it is not optimal!

**Comment by daanaerts** [comment]
old post, for anyone reading this after June 2024

https://orkhan.gitbook.io/typeorm/docs/listeners-and-subscribers

**Comment by Woodz** [comment]
> old post, for anyone reading this after June 2024
> 
> https://orkhan.gitbook.io/typeorm/docs/listeners-and-subscribers

This is a different concept - entity listeners and subscribers are a TypeOrm feature that can invoke callbacks on various ORM operations. This feature does not allow applications to subscribe to PSQL channels, which is what this issue requested

**Comment by vitaly-t** [comment]
If this library doesn't allow for persistent connections, then it is a joke. Any decent library supports persistent connections, as quintessential.
