### ISSUE TITLE
Using TypeORM with MySQL/MariaDB Galera Cluster

### ISSUE THREAD

**Issue by rmuchall** [typeorm/typeorm#2437]
**Issue type:**

[x ] question

**Database system/driver:**

[ x] `mysql` / `mariadb`

**TypeORM version:**

[ x] `latest`

Hi folks,

Apologies if this is not the correct place for this post.

I was wondering if anyone is currently using TypeORM on a MySQL or MariaDB Galera cluster and if there are any considerations I should take into account before attempting this? :)

Thanks!

**Comment by pleerock** [comment]
Not sure how many people are ysing galera cluster but its better to ask it on gitter, not sure if you get people answers here.

**Comment by TimPietrusky** [comment]
@rmuchall have you ever found an answer to your question? As the "gitter" doesn't exist anymore, I might ask this via Slack, but just wanted to be sure.

**Comment by rmuchall** [comment]
I did have TypeORM running on a MySQL Galera cluster for a while. The technology is impressive but I found it to be very brittle. Databases would desync due to the slightest network hiccup (or sometimes for seemingly no reason at all). It was complicated to debug if anything went wrong. It was doubly complicated to repair if anything needed fixing. It ended up increasing our downtime by a large margin instead of reducing it. So my recommendation is to think very hard before using it. As an alternative we switched to a single PostgreSQL instance with failover. Far, far easier to maintain at the cost of there being a couple of minutes of downtime if you need to failover. Good luck :)

**Comment by TimPietrusky** [comment]
@rmuchall thank you very much!
