### ISSUE TITLE
Add an ability to set postgresql schema per call

### ISSUE THREAD

**Issue by syabro** [typeorm/typeorm#2439]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

It would be a huge step to support multi-tenant systems with providing `schema` to `getManager` or to `getRepository`.  I've read @pleerock answer in #1577 and instead of it I suppose to open a connection per schema. 

But I don't get how many connections I have to open. Imagine I have 10k tenants. Does it mean I have to have 10k connections in the pool? How much memory will it consume?

**Comment by pleerock** [comment]
You can use schema name in a query builder, e.g. `createQueryBuilder("schema.tableName")`

**Comment by osman-mohamad** [comment]
@syabro can it be setup per repository ? to query with it ?
