### ISSUE TITLE
Suggestion for next major version - Active Record style

### ISSUE THREAD

**Issue by ORESoftware** [typeorm/typeorm#2442]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

Looking at the docs for Active Record style usage:

```js
const user = new User();
user.firstName = "Timber";
user.lastName = "Saw";
user.isActive = true;
user.save()
```

I assume there could be some property collisions there, I am always afraid of that.

Instead, why not an API like so:

```js
const user = new User();
user.set('firstName', 'Timber');
user.set('lastName', 'Saw');
user.set('xxxxx', 'bar');
user.save();
```

the user properties would be stored in user internally, so there would be no collisions.
The first argument to set, could be type-checked against the `@column` properties in the entities. 

Definitely more verbose, but perhaps with auto-completion wouldn't be so bad.

**Comment by ORESoftware** [comment]
On a similar subject of "type-checking" strings, it would be cool if the `@Index ` strings were checked so that they match a column name

![screenshot from 2018-07-02 00-40-32](https://user-images.githubusercontent.com/11139560/42151101-afbe2c54-7d90-11e8-96e9-9306f49e33fb.png)

in the image you can see that "customer" does not match "customerId"

**Comment by pleerock** [comment]
> I assume there could be some property collisions there, I am always afraid of that.

Thanks for the suggestion, but it does not make sense. There can't be property collisions, this is your model and you define properties you want as a database columns.

Regarding to second proposal please create a separate issue.
