### ISSUE TITLE
How to create geometry with SRID reference

### ISSUE THREAD

**Issue by antivist** [typeorm/typeorm#2443]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello, I want to create a geometry (point in this example) with reference to SRID "4326".
My entity looks like this: 
```
@Column('point')
    geometry: any;
```
And what I've found so far is that you create a point like this: 
`entity.geometry = "POINT(11.123 52.123)" `

This will not work because:
`Geometry SRID (0) does not match column SRID (4326)`

usually you would create a point in PSQL like this:

`let point = "ST_GeomFromText(POINT(11.123  52.123), 4326)";`
or
`let point = "ST_SetSRID(ST_MakePoint(11.123 52.123), 4326)";`

But this results in:

`parse error - invalid geometry`

In Sequelize I've done this as followed:
```
 geometry: {
                type: 'Point',
                coordinates: [11.123 , 52.123],
                crs: {type: 'name', properties: {name: 'EPSG:4326'}}
            },
```
How would I do this in typeORM?

**Comment by antivist** [comment]
After some searching I've found this commment: https://github.com/typeorm/typeorm/issues/370#issuecomment-399590891

So I create my point like this:
` let point = new wkx.Point(lng, lat, undefined, undefined, 4326).toEwkt();`

Which is inserted without any errors into my table.

**Comment by pleerock** [comment]
so your issue is resolved right?

**Comment by antivist** [comment]
Well my issue is solved, but my question is not. 
https://github.com/typeorm/typeorm/blob/master/docs/entities.md#column-types-for-postgres says that you support points (or geometries at all).
Will there be a way in near future to create geometries with reference to a srid without the use of wkx?
Like, for example:
```
@Column({type: 'point', srid: '4326'})
    geometry: Point;
```

**Comment by pleerock** [comment]
@mojodna do you think if this request can be covered by your PR?

**Comment by mojodna** [comment]
It is!

Syntax (for Postgres):

```typescript
@Column("geometry", {
  featureType: "Point",
  srid: 4326
})
```

@antivist #2423 allows PostGIS to be used without `wkx`. Geometries will be passed to/from client code as GeoJSON.

You can try it locally with `npm install "github.com:mojodna/typeorm#dist"`.

**Comment by antivist** [comment]
Thanks, will do!

**Comment by kukuandroid** [comment]
@mojodna  hi, how can i query for this type of column ? thanks
