### ISSUE TITLE
Extraneous fields - prevent extraneous fields from being written to a table

### ISSUE THREAD

**Issue by ORESoftware** [typeorm/typeorm#2444]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I put this question on SO:
https://stackoverflow.com/questions/51131490/making-fields-columns-optional-required-using-typeorm/51131629

For some reason I was able to insert some JSON into the DB, where the JSON fields were not on the model.

For example:

```js
router.post('/', (req, res, next) => {
  return RCustomer.save(req.body).then(v => res.json({success: v}));
});
```

The req.body object has bad properties on it, but still I was able to create a new record.

So I guess I am looking for a decorator like:
`@Entity({extraneousFields: false})`

or

`@Entity({unknownProperties: false})`

what is standard procedure here? class-validator can do validation for existing fields, but can class-validator be used to validate that only properties that exist in the model should be present in the payload?

**Comment by pleerock** [comment]
I answered your question on SO.
