### ISSUE TITLE
Partial selection on Inner Join Problem

### ISSUE THREAD

**Issue by PelayoChoya** [typeorm/typeorm#2447]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.7` 

**Steps to reproduce or a small repository showing the problem:**

Hi, thanks for creating this package. 
I am experiencing lots of trouble while trying to retrieve a particular column from a DB entity with a one to one relation.

I have got two entities, User and Token, with a one to one relation between them. The entities are shown bellow:

```

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  @IsString()
  @Length(4, 10)
  name: string;

  @Column({unique: true})
  @IsEmail()
  mail: string;

  @Column()
  @IsInt()
  @Min(18)
  @Max(99)
  age: number;

  @Column(({type: 'float'}))
  @Min(20.5)
  @Max(120.3)
  weight: number;

  @Column()
  password: string;

  @OneToOne( type => TokenInfo )
  @JoinColumn()
  token: TokenInfo;

  @Column({
		type: 'enum',
		enum: [
			'admin',
			'user',
		],
	})
  role: 'admin' | 'user';

  @Column()
  last_login: Date;
}

```
```
@Entity()
export class TokenInfo {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  value: string;

  @Column()
  expiration: Date;
}
```

I want to retrieve just the token 'value' column. For this, I employ the following command:

```
const userJoinPartial = await userRepository
    .createQueryBuilder('user')
    .select(['user', 'token', 'token.value'])
    .where('user.id = :id', { id: idx})
    .innerJoin('user.token', 'token')
    .getOne();
```
However, instead of getting an object with just { value: xxxx} I get the following:
```
User {
  id: 2,
  name: 'bbbb',
  mail: 'b@b.com',
  age: 33,
  weight: 88.5,
  password: '$2b$10$5l10RCEPsxuxOXavNE.jJ.FspjMTxobGBXLVXNjn1qnNB3vEwZCWG',
  role: 'user',
  last_login: 2018-07-02T11:11:26.568Z,
  token:
   TokenInfo {
     id: 2,
     value: 'a2fa03b6-18bc-fcfa-b1cb-eb7b58106db6',
     expiration: 2018-07-02T11:11:26.569Z } }
```
I have looked in the documentation and I did not see any aclaration on doing partial selects on Inner Join results. Besides, I have also looked at the issues of the repo, coming accross some messages telling the partial selection may not be fully covered.
Am I performing an incorrect query?

Thanks

**Comment by pleerock** [comment]
```ts
    .select(['user', 'token', 'token.value'])
```

By adding `token` you already select the whole token, thats why it selects everything for you. What you need is something like this:

```ts
    .select(['user', 'token.value'])
```

But this won't work since then user won't know what token it should map to what user since token.id value is missing, that's why you have to select id in any case no matter you need it or not:

```ts
    .select(['user', 'token.id, 'token.value'])
```

**Comment by PelayoChoya** [comment]
Thx for your quick response,

I have tried the following query as you pointed out:

```
const userJoinPartial = await userRepository
    .createQueryBuilder('user')
    .select(['user', 'token.id', 'token.value'])
    .where('user.id = :id', { id: idx})
    .innerJoin('user.token', 'token')
    .getOne();
```

However the result still includes all the user column's. However if I change the query to:
```
.select(['user.id', 'token.id', 'token.value'])
```
I get just the user id, token id and token value. I guess this is the minimum info I can get, right?

**Comment by pleerock** [comment]
>  .select(['user'

if you add "user" it means you select everything from the user, if you want to partially select something from it you need to specify everything you want to select just like you did with token

**Comment by stonestecnologia** [comment]
Hi !
I need select ony on field to services, look:
```
  async find(): Promise<AccountEntity[]> {
    const result = await this.repository
      .createQueryBuilder("account")
      .select(['account', 'accountServices', 'service.description'])
      .leftJoinAndSelect("account.accountAndServices", "accountServices")
      .leftJoinAndSelect("accountServices.service", "service")
      .getMany();
    return result === undefined ? null : result;
  }
```
How to ? please.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
