### ISSUE TITLE
Are findOne() where clause fields joined with OR operator?

### ISSUE THREAD

**Issue by mrnagydavid** [typeorm/typeorm#2448]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`EntityClass.findOne({ where: { userId: 1, footprintId: 2 } })`

produces this result:
```
Instance {
  id: 1,
  createdAt: 2018-07-02T12:45:02.268Z,
  updatedAt: 2018-07-02T12:57:58.073Z,
  isFollowing: true,
  footprintId: 1,
  userId: 1,
  completedMilestonesIds: [],
  lastViewedMilestoneId: 1 }
```

Even though I queried for a row with `"userId" = 1 AND "footprintId" = 2`, the result is one with `"userId" = 1 AND "footprintId" = 1`.

Does this mean that the PartialEntity fields in the query are connected by OR operators? I couldn't find any mention of this in the docs, and every example contains only a single conditional in the where clause.

**Comment by mrnagydavid** [comment]
Did a few run-ins with the query builder.

```
Instance
        .getRepository()
        .createQueryBuilder('FootprintInstance')
        .where({ userId })
        // @ts-ignore
        .andWhere({ footprintId: input.footprintId })
        .getOne();
```
returns the same wrong answers. Without @ts-ignore it doesn't even "compile".

```
Instance
        .getRepository()
        .createQueryBuilder('FootprintInstance')
        .where('"userId" = :userId', { userId })
        .andWhere('"footprintId" = :footprintId', { footprintId: input.footprintId })
        .getOne();
```
This is OK! But had to double-quote column names which feels a little too RDBM specific. (At least I suppose only postgres is allergic to capital letters in column names.)

**Comment by pleerock** [comment]
```ts
Instance
        .getRepository()
        .createQueryBuilder('FootprintInstance')
        .where({ userId })
        // @ts-ignore
        .andWhere({ footprintId: input.footprintId })
        .getOne();
```

this syntax is not supported.


```ts
Instance
        .getRepository()
        .createQueryBuilder('FootprintInstance')
        .where('"userId" = :userId', { userId })
        .andWhere('"footprintId" = :footprintId', { footprintId: input.footprintId })
        .getOne();
```

this actually should be this way:

```ts
Instance
        .getRepository()
        .createQueryBuilder('FootprintInstance', "footprint")
        .where('footprint.userId = :userId', { userId })
        .andWhere('footprint.footprintId = :footprintId', { footprintId: input.footprintId })
        .getOne();
```

don't forget to use aliases!

Regarding to first code:

```ts
EntityClass.findOne({ where: { userId: 1, footprintId: 2 } })
```

can you take a look what sql it does generate for you? Also can you please provide some reproduction so I can test?

**Comment by mrnagydavid** [comment]
Thanks pleerock!

Your "should be this way" code gives the following ts error: `[ts] Argument of type '"footprint"' is not assignable to parameter of type 'QueryRunner | undefined'.`

If I skip the error with @ts-ignore, then the TypeError during runtime is:

```
TypeError: queryRunner.query is not a function
    at SelectQueryBuilder.<anonymous> (/U.../api/src/query-builder/SelectQueryBuilder.ts:1899:43)
    at step (/U.../api/node_modules/typeorm/query-builder/SelectQueryBuilder.js:42:23)
    at Object.next (/U.../api/node_modules/typeorm/query-builder/SelectQueryBuilder.js:23:53)
    at /U.../api/node_modules/typeorm/query-builder/SelectQueryBuilder.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/U.../api/node_modules/typeorm/query-builder/SelectQueryBuilder.js:13:12)
    at SelectQueryBuilder.loadRawResults (/U.../api/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1493:16)
    at SelectQueryBuilder.<anonymous> (/U.../api/src/query-builder/SelectQueryBuilder.ts:1817:37)
    at step (/U.../api/node_modules/typeorm/query-builder/SelectQueryBuilder.js:42:23)
    at Object.next (/U.../api/node_modules/typeorm/query-builder/SelectQueryBuilder.js:23:53)
```

Can't it be because we are using the querybuilder "from" the actualy EntityInstance, and then only 1 parameter is needed, which is the alias? `createQueryBuilder(alias?: string, queryRunner?: QueryRunner): SelectQueryBuilder<Entity>;`

Following that thought I modified your proposed snipplet to this:

```
FootprintInstance
        .getRepository()
        .createQueryBuilder('footprint')
        .where('footprint.userId = :userId', { userId })
        .andWhere('footprint.footprintId = :footprintId', { footprintId: input.footprintId })
        .getOne();
```

Which throws the runtime error: `QueryFailedError: column footprint.userid does not exist`. 

I know postgres has a hard time understanding column names with capital letters, so every such column name needs to be put into double-quotes. But even if I use double quotes with aliases, then it still throws an error.

```
FootprintInstance
        .getRepository()
        .createQueryBuilder('footprint')
        .where('footprint."userId" = :userId', { userId })
        .andWhere('footprint."footprintId" = :footprintId', { footprintId: input.footprintId })
        .getOne();
```

This works as intended, but this is way too postgres specific for an ORM layer.

And I still don't understand why `FootprintInstance.findOne({ userId: 1, footprintId: 2 })` doesn't work.

I will attempt to put together a small repo w/ the issue and comment back, but do you have a repo where you can have findOne working with an actual DeepPartial<T> object with multiple fields as conditions? Is this an isolated incident? I mean not even typeorm's docs have any example of this use case, but theoretically it should work.

**Comment by mrnagydavid** [comment]
According to the log, the shorthand version runs the following query:
```SELECT 
"FootprintInstance"."id" AS "FootprintInstance_id", 
"FootprintInstance"."createdAt" AS "FootprintInstance_createdAt", 
"FootprintInstance"."updatedAt" AS "FootprintInstance_updatedAt", 
"FootprintInstance"."isFollowing" AS "FootprintInstance_isFollowing", "FootprintInstance"."footprintId" AS "FootprintInstance_footprintId", 
"FootprintInstance"."userId" AS "FootprintInstance_userId", "FootprintInstance"."lastViewedMilestoneId" AS "FootprintInstance_lastViewedMilestoneId" 
FROM "footprint_instance" "FootprintInstance"
```

No where clause whatsoever. :S

I will attempt to put together a small repo w/ the issue and comment back, but do you have a repo where you can have findOne working with an actual DeepPartial<T> object with multiple fields as conditions? Is this an isolated incident? I mean not even typeorm's docs have any example of this use case, but theoretically it should work.

**Comment by mrnagydavid** [comment]
Managed to compose a small repo. After setting ormconfig.json and `yarn start` you will see it output:

```
SomeEntity saved 1
SomeEntity:
SomeEntity {
  otherEntity: SomeOtherEntity { id: 1 },
  thirdEntity: ThirdEntity { id: 1 },
  id: 1,
  otherEntityId: 1,
  thirdEntityId: 1 }
Run query for:  { otherEntityId: 2, thirdEntityId: 2 }
query: SELECT "SomeEntity"."id" AS "SomeEntity_id", "SomeEntity"."otherEntityId" AS "SomeEntity_otherEntityId", "SomeEntity"."thirdEntityId" AS "SomeEntity_thirdEntityId" FROM "some_entity" "SomeEntity"
Result:
SomeEntity { id: 1, otherEntityId: 1, thirdEntityId: 1 }
Finished!
```

That is the query is run for `otherEntityId = 2 AND thirdEntityId = 2` and yet the result is `SomeEntity { id: 1, otherEntityId: 1, thirdEntityId: 1 }` instead of undefined.

https://github.com/mrnagydavid/typeorm-bug-findone

**Comment by pleerock** [comment]
```ts
FootprintInstance
        .getRepository()
        .createQueryBuilder('footprint')
        .where('footprint."userId" = :userId', { userId })
        .andWhere('footprint."footprintId" = :footprintId', { footprintId: input.footprintId })
        .getOne();
```

you need to use relations if you don't have such columns in your entity, e.g.:

```ts
FootprintInstance
        .getRepository()
        .createQueryBuilder('footprint')
        .where('footprint.user = :userId', { userId })
        .andWhere('footprint.footprint = :footprintId', { footprintId: input.footprintId })
        .getOne();
```

**Comment by pleerock** [comment]
Your issue in `@RelationId`. Use `@Column` instead of it it will solve all your issues. Problem that you can work with column findOne method, something that you mark with RelationId decorator isn't a column.

**Comment by mrnagydavid** [comment]
Thanks! That really did the trick.

AAMOF this works too then:
`Instance.findOne({ user: 1, footprint: 2 });`
but of course throws a typeerror, which can be suppressed with ts-ignore, or better:
`Instance.findOne({ user: { id: 1 }, footprint: { id: 2 } });`

The property with the RelationId is actually really a column in the DB in this case, but in other cases (ManyToMany) it might not be. So, this makes sense in a way.

Should we include such an example and some description in the docs?

**Comment by pleerock** [comment]
what exactly do you propose to add to the docs?

**Comment by mrnagydavid** [comment]
Good question. Something along the lines of
1) Do not query RelationId columns, because even if it has a similarly named column in the table, the query won't work.
2) .find() fails silently and if a .find() query is malformed, it will still give back an answer: the first entity it finds.

**Comment by ullalaaron** [comment]
> Good question. Something along the lines of
> 
> 1. Do not query RelationId columns, because even if it has a similarly named column in the table, the query won't work.
> 2. .find() fails silently and if a .find() query is malformed, it will still give back an answer: the first entity it finds.

Isn't point nr 2 kind of dangerous?  Would it be possible to add a findOrFail method such as for findOne?

**Comment by sertsedat** [comment]
+1

It's indeed very dangerous, in case we are dealing with sensitive data we wouldn't want to update it unless we are sure we got what we wanted.

**Comment by Nosfistis** [comment]
It would be nice to clarify in the docs more precisely cases that `@RelationId()` is useful. Using `@Column()` even without the `@RelationId()` does fetch the column, so when is the latter required?

Is it useful in separating entity owned properties vs entity relation-related properties? Should it be avoided unless really necessary, and when it is necessary? Does it provide further required info to the ORM?

**Comment by JohannesHome** [comment]
It would be very useful to be able to query via `RelationId`. It came as a suprise to me that it actually does not work.
```typescript
repository.findOne({ relationId }); // Does not work, it always returns the first entity

repository.findOne({ relation: { id: relationId }}); // This works correctly, using @ManyToOne on field relation
```

**Comment by DarkLite1** [comment]
Came here too while struggling on how to get the data from a `OneToOne` relationship within an SQL database. Essentially we want to retrieve the preferences stored for that specific account based on the account ID stored in the `Context`.. Finally figured it out, this how we did it.

```typescript
const account = await Account.findOne(
  { id: ctx.user.id },
  { relations: ['preference'] }
)

const preference = account?.preference
```

### Account
```typescript
@Entity()
export class Account extends BaseEntity {
  @PrimaryGeneratedColumn() 
   id: number

  @Column() 
   name: string

  @OneToOne(() => Preference, preference => preference.account)
  @JoinColumn()
  preference: Preference
}
```

### Preference
```typescript
@Entity()
export class Preference extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number

  @OneToOne(() => Account, account => account.preference)
  account: Account

  @Column({)
  language: string
}
```

Hope this helps others.

**Comment by imnotjames** [comment]
The original question `Are findOne() where clause fields joined with OR operator` has been answered.
