### ISSUE TITLE
Select columns to list on mapped entities

### ISSUE THREAD

**Issue by Tobias4872** [typeorm/typeorm#245]
Hi,

when I used "innerJoinAndMapOne" to join in let's say a parent element. Can I - e.g. - decide that I only want to see the "id" and the "name" column of that parent element in the map instead of the complete element?

Thanks,
   Tobias.

**Comment by pleerock** [comment]
no, partial selection is not supported yet, but I'm planning to implement it the future versions of orm.

**Comment by Tobias4872** [comment]
OK, thanks. Not sure if you want to close or keep this. Up to you.

**Comment by ascoders** [comment]
Hello @pleerock ,I find that if use `.select` method, it will override all select sql sentence:

```typescript
const user = await this.userRepository.createQueryBuilder('user')
            .where('user.id=:id', {id: Number(req.session['userId'])})
            .leftJoinAndMapOne('user.gameSimulatedPlanetUser', GameUser, 'gameUser', 'gameUser.user=user.id')
            .leftJoinAndMapMany('gameUser.planets', GamePlanet, 'gamePlanet', 'gameUser.id=gamePlanet.gameUser')
            .leftJoinAndMapMany('gamePlanet.buildings', GameBuilding, 'gameBuilding', 'gamePlanet.id=gameBuilding.planet')
            .select(['user.id as user_id']) // amazing
            .getSql()
```

And then i got a sql like `SELECT user.id as user_id FROM user user LEFT JOIN...`, and do not support syntax like `gameUser.something as gameUser_something`. Hope that the future can be supported!

Another question is that i don't know why this is true `.select(['user.id as user_id'])`, and `select['user.id']` doesn't,  may be a magic.

**Comment by pleerock** [comment]
you can use such code temporary until partial selection feature will come.

**Comment by pleerock** [comment]
Partial selection is already implemented in latest versions, so I'll close this issue.

**Comment by vsainiwelt** [comment]
what about if i want to select a column of gameUser.planets

from query as below
```
const user = await this.userRepository.createQueryBuilder('user')
            .where('user.id=:id', {id: Number(req.session['userId'])})
            .leftJoinAndMapOne('user.gameSimulatedPlanetUser', GameUser, 'gameUser', 'gameUser.user=user.id')
            .leftJoinAndMapMany('gameUser.planets', GamePlanet, 'gamePlanet', 'gameUser.id=gamePlanet.gameUser')
            .leftJoinAndMapMany('gamePlanet.buildings', GameBuilding, 'gameBuilding', 'gamePlanet.id=gameBuilding.planet')
            .select(['user.id as user_id']) // amazing
            .getSql()

```

**Comment by vcfvct** [comment]
@iamvsaini , i am also trying to find a way to do partial select on `mapped item`(child). I tried `addSelect()` on the child but no luck. Do you find any way to achieve this? 
Thanks.

**Comment by pleerock** [comment]
you simply do `.select(['user.id', 'user.name])` on what you want to select partially. Just make sure to select entity id, its required for selection

**Comment by vcfvct** [comment]
@pleerock , got it. I forget to remove the `AndSelect` part of my `join`. Thanks for the info and this great framework!

**Comment by judemanutd** [comment]
@pleerock I am trying to fetch just the `id` and `name` column from the `Section` table using the following code but I'm still getting the data for all the columns in `section`. 

```
    const query = getRepository(Tests)
      .createQueryBuilder("Tests")
      .select([
        "Tests.id",
        "Tests.name",
      ])
      .addSelect("SECTIONS.id")
      .addSelect("SECTIONS.name")
      .leftJoinAndMapMany(
        "Tests.Sections",
        Sections,
        "SECTIONS",
        "(SECTIONS.test = Tests.id AND SECTIONS.status != :statusDeleted)",
        { statusDeleted },
      );
```

I have also tried the code below but that didn't work either

```
      .select([
        "Tests.id",
        "Tests.name",
        "SECTIONS.id"
      ])
```

**Comment by judemanutd** [comment]
@pleerock I am trying to fetch just the `id` and `name` column from the `Section` table using the following code but I'm still getting the data for all the columns in `section`. 

```
    const query = getRepository(Tests)
      .createQueryBuilder("Tests")
      .select([
        "Tests.id",
        "Tests.name",
      ])
      .addSelect("SECTIONS.id")
      .addSelect("SECTIONS.name")
      .leftJoinAndMapMany(
        "Tests.Sections",
        Sections,
        "SECTIONS",
        "(SECTIONS.test = Tests.id AND SECTIONS.status != :statusDeleted)",
        { statusDeleted },
      );
```

I have also tried the code below but that didn't work either

```
      .select([
        "Tests.id",
        "Tests.name",
        "SECTIONS.id"
      ])
```

**Comment by pleerock** [comment]
`leftJoinAndMapMany` works with some specifics. Don't use it, instead create a separate query and map data manually.

**Comment by kubines17** [comment]
try this: static async getTest(limit: number = 20, offset: number = 0, id: number): Promise<any> {
    return await this.createQueryBuilder()
      .select('test.id', 'id')
      .addSelect('test.name', 'name')
      .addSelect('test.description', 'description')
      .addSelect('test.create', 'create')
      .addSelect('COUNT(likes.id)', 'likesQty')
      .from('test', 'test')
      .leftJoin('like', 'likes', 'likes.testId = test.id')
      .where('test.create >= DATE(NOW()) - INTERVAL 7 DAY')
      .andWhere('test.categoryId = :id', {id})
      .groupBy('likes.testId')
      .orderBy('likesQty', 'DESC')
      .limit(limit)
      .offset(offset)
      .getRawMany();
  }
output:
"sort by likes": [
        {
            "id": 5,
            "name": "hjg",
            "description": null,
            "create": "2018-12-19T11:55:36.687Z",
            "likesQty": "14"
        }

**Comment by OLDIN** [comment]
@pleerock Is this functionality still not implemented?

**Comment by trycontrolmymind** [comment]
This functionality is necessary for many cases

**Comment by trycontrolmymind** [comment]
Why is it closed?

**Comment by gmbwa** [comment]
This works, add the select after the leftJoinAndMapMany
