### ISSUE TITLE
Error on migration when parse tablename

### ISSUE THREAD

**Issue by vannytjahyadi** [typeorm/typeorm#2450]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

hi all this is my first `submit new issues`, please be nice..
I just create a new migration and use syntax as its example using migration api

```
import {MigrationInterface, QueryRunner, Table} from "typeorm";

export class test1530552105780 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.createTable(new Table({
            name: "users",
            columns: [
                {
                    name: "id",
                    type: "int",
                    isPrimary: true
                },
                {
                    name: "email",
                    type: "varchar",
                }
            ]
        }), true)        
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.dropTable("users");
    }

}
```

however when i tried to run migration, i got this error

```
TypeError: tableName.indexOf is not a function
    at MysqlQueryRunner.parseTableName (C:\Users\vanny.tjahyadi\AppData\Roaming\npm\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:1821:33)
    at MysqlQueryRunner.<anonymous> (C:\Users\vanny.tjahyadi\AppData\Roaming\npm\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:305:48)
    at step (C:\Users\vanny.tjahyadi\AppData\Roaming\npm\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:42:23)
    at Object.next (C:\Users\vanny.tjahyadi\AppData\Roaming\npm\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:23:53)
    at C:\Users\vanny.tjahyadi\AppData\Roaming\npm\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\vanny.tjahyadi\AppData\Roaming\npm\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:13:12)
    at MysqlQueryRunner.hasTable (C:\Users\vanny.tjahyadi\AppData\Roaming\npm\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:300:16)
    at MysqlQueryRunner.<anonymous> (C:\Users\vanny.tjahyadi\AppData\Roaming\npm\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:406:51)
    at step (C:\Users\vanny.tjahyadi\AppData\Roaming\npm\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:42:23)
```

would be nice if someone can help me fixed this.

**Comment by pleerock** [comment]
there are bunch of tests that prove this functionality works. Can you create some reproduction for this issue?

**Comment by vannytjahyadi** [comment]
here's my repository for this issue https://github.com/vannytjahyadi/frezto-api-dev

heres the steps to reproduce the issue : 
1.generate migration `typeorm migration:generate -n test`
2.create table using migration api
```
import {MigrationInterface, QueryRunner, Table} from "typeorm";

export class test1530552105780 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.createTable(new Table({
            name: "users",
            columns: [
                {
                    name: "id",
                    type: "int",
                    isPrimary: true
                },
                {
                    name: "email",
                    type: "varchar",
                }
            ]
        }), true)        
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.dropTable("users");
    }

}
```
3. run migration  `typeorm migration:run`

**Comment by pleerock** [comment]
<img width="1192" alt="screenshot 2018-07-03 08 53 49" src="https://user-images.githubusercontent.com/1753397/42197916-a04de674-7e9e-11e8-9a89-d5abf1e1c810.png">


it works. try to use local typeorm version or update a global one if you use global typeorm.

**Comment by vannytjahyadi** [comment]
thanks it works when i use local typeorm 👍

**Comment by eddieajau** [comment]
Just confirming this bug is represent in v0.2.7. The issue is in MysqlQueryRunner:

```
    MysqlQueryRunner.prototype.parseTableName = function (target) {
        var tableName = target instanceof Table_1.Table ? target.name : target;
        return {
            database: tableName.indexOf(".") !== -1 ? tableName.split(".")[0] : this.driver.database,
            tableName: tableName.indexOf(".") !== -1 ? tableName.split(".")[1] : tableName
        };
    };
```

The problem, I believe is that `Table_1.Table` is physically a different instance when you run the global install. On that basis, running the global `typeorm` as stated in the docs is never, ever going to work. I guess the code should be, perhaps, something like the following??:

```
    MysqlQueryRunner.prototype.parseTableName = function (target) {
        var tableName = target.name ? target.name : target;
        return {
            database: tableName.indexOf(".") !== -1 ? tableName.split(".")[0] : this.driver.database,
            tableName: tableName.indexOf(".") !== -1 ? tableName.split(".")[1] : tableName
        };
    };
```

@pleerock would that be acceptable, in which case I can do a pull request?

**Comment by yazshel** [comment]
FYI This same issue is also present int the PostgresQueryRunner; I get  the exact same `TypeError: tableName.indexOf is not a function` error message when performing a `typeorm migration:run` using the globally installed typeorm CLI.

In the Postgres case, it's the `PostgresQueryRunner.prototype.escapeTableName` function which needs the same treatment as @eddieajau proposes above.
![image](https://user-images.githubusercontent.com/8703183/44661359-c63eac80-aa4d-11e8-9612-6a4cb34180f1.png)

**Comment by XBeg9** [comment]
why this was closed? The bug is still present. Thanks

**Comment by f4z3k4s** [comment]
If you don't want to spend time checking mismatching versions - which is the source of the problem - you should simply run migrations via `npx` like `npx typeorm migration:run` which forces npm to use your local typeorm.

**Comment by johncmunson** [comment]
This issue should be re-opened, as the problem still exists. There exists a workaround (see above comment), but unless the workaround is officially documented or the root cause of the issue is fixed, then this issue should be re-opened.

**Comment by dlarchikov** [comment]
Not working on my environment when i run using ts-node
But working when i run
```
npx  node -r ts-node/register -r tsconfig-paths/register ./node_modules/typeorm/cli.js  migration:run
```
