### ISSUE TITLE
Tree entity table schema is undocumented

### ISSUE THREAD

**Issue by eropple** [typeorm/typeorm#2453]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

Hey there! TypeORM seems really cool, but something that's completely wrecking my day is figuring out how to build a table that resembles what TypeORM expects for tree entities, regardless of implementation.

The reason that this is important to me is that my project is migrations-first, right from the jump; `synchronize`-based databases have bitten me too many times in the past to risk them and I'd rather fully understand and think through the consequences of my actions by writing individual migrations and database seeds for them.

I'm familiar at a high level with, say, how a nested set works--but not how TypeORM expects the table to be structured. It would be really awesome if the tree entity documentation could have an example schema for each type of tree relationship table, or at least an explanation of how they are generated. (I'd be happy to write it myself...but the code's also a bit opaque to me. :( )

Thank you again for TypeORM!

**Comment by pleerock** [comment]
synchronize is one of the most powerful feature of typeorm, you just need to know how it works and if you afraid of anything  just run sql log before each run on production, take a look what it does before running it and make sure each sql it generates is OKAY for you. That's it. If its not okay then you can simply copy-paste/create a migration and make corrections you need. Again this is a very powerful feature and if you don't use it you miss a lot I think. 

What you can do in your case if you still don't want to use synchronization - you can create a new project with that entity on a new database, generate everything and take a look how exactly typeorm generates the schema, and copy everything in your database.

**Comment by eropple** [comment]
Regarding synchronization: I write my own migrations because I know the database I am targeting and I know how to optimize that database better than a generalized schema transformation system does. I don't want or need powerful features--I want features that are fully in my control, you know? So synchronization is not a good option for me and puzzling through generated SQL instead of having a reliable, parameterized example seems pretty user-hostile. I'm not unfamiliar with writing these things myself. I'm unfamiliar with _what TypeORM expects_, and that strikes me as something that really should be documented if TypeORM is focused on being a reliable and unsurprising tool.

I realize I can extract everything from my codebase, run a stub synchronize against a database that I don't care about getting trashed, and then step through the entire thing to figure out the schema. Alternatively, a short blurb of documentation that describes the structures expected would help both me and other people down the line.

(Consider also the case of porting an existing database schema to a product using TypeORM, for additional use cases here.)

**Comment by pleerock** [comment]
What you want to have documentation for is quite underlying and have lot deep things to cover.

>  realize I can extract everything from my codebase, run a stub synchronize against a database that I don't care about getting trashed, and then step through the entire thing to figure out the schema. 

What I can suggest you is to do it, and make a documentation that other people like you can use in the future.

**Comment by eropple** [comment]
I'm not against doing some work to get what I need, that's for sure, and I've already done this and documented it privately for future publication. But your attitude, to be frank, has exposed other probable issues with TypeORM.

Code-first design is not the only way that people work, it's very rarely the way people building systems at scale work, and making database-driven design so difficult and tasking end users with tracking the magic that a library does instead of _documenting that magic_ suggests future problems when TypeORM decides to be surprising in other ways, too. I don't want this to sound like a pout, you can obviously do whatever you want with your time and your code, but reliability is point one for me and I don't feel that, then, I can trust any documentation that I write for the project to not go stale when a developer whose viewpoint is "just use synchronize" decides to change its behavior.

Thanks for your time.

**Comment by pleerock** [comment]
Thank you, I understood your concerns about "synchronize". 

But my point remains the same - "synchronize" is very important part of TypeORM, complex one but very useful. And if I was thinking that it's bad or not reliable then I won't make or use it at all. Schema maintenance is a hard and dangerous, "synchronize" solves only one problem - it tries to make you things simpler, but danger still remains, you just need to know how "synchronize" works and have experience working with it before going to production. To make it more safe "synchronize" provides you ability to:

* view SQL queries its gonna execute via CLI command (before synchronize - it means you check SQL log to make sure everything is okay before running it)
* generate a migration with SQL query "synchronize" is going to execute - this way you have a full control - you can see what SQL queries are going to be executed and you can change it the way you want 

Extra documentation is always useful, and if you want to document something it will be really great. And if you are active TypeORM user then I strongly recommend you to keep track on changes going inside the project, its very important for you, as to user. This way you'll able to keep track on schema synchronization process and update documentation. Community support is very important, thank you for understanding.

**Comment by eropple** [comment]
Food for thought: literally no other ORM I've ever used requires one to track it for changes in any meaningful way just on the off chance that it frags the data it's entrusted with. I can trust Hibernate not to frag my data. But Hibernate also doesn't demand that it own the entirety of my database, my workflow, and dictate even how I deploy software (without, it should be noted for fairness significant changes that are undocumented and reliant on _copying stuff out of a test run_).

A DAL should be unsurprising and needs to be unsurprising. Nothing with a synchronize step is ever, _ever_, unsurprising, and it's mystifying how hard you're choosing to push that route over some really basic questions asked. The output of the software is not the documentation for it! _Yikes!_

I mean no disrespect, but the positively reckless way you've discussed this has resulted in moving moved away from TypeORM save for trivial projects where I don't care about my data. But I appreciate your attention and your time; good luck.
