### ISSUE TITLE
ormconfig for oracle

### ISSUE THREAD

**Issue by gaugustfrank2** [typeorm/typeorm#2455]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

I am trying to use TypeORM with Oracle 12.1.  Without TypeORM, a connection to the database is done with a connection string that specifies "host" and "service name" (tnsnames.ora).  There is a host property in the ormconfig.json file.  However, is it correct to place the service name in the database property of the file?  It does not seem to work?

**Comment by pleerock** [comment]
you missed issue description.

**Comment by gaugustfrank2** [comment]
The issue description was written but,  I don't know what happened.  I am seeking an example of the ormconfig.json for an oracle database. The connection string to an oracle database specifies a host and a service name.  Its apparent that the host value in the ormconfig would be initialized with the host value from the oracle connection string.  However, the placement of the service name is not as clear.  An example of the ormconfig that mimics the content of the oracle connection string would be appreciated.

**Comment by pleerock** [comment]
[Here is an example](https://github.com/typeorm/typeorm/blob/master/ormconfig.json.dist#L54) how oracle ormconfing can look like

**Comment by gaugustfrank2** [comment]
An oracle connection string is like -> <addressname> =
(DESCRIPTION =
   (ADDRESS_LIST =
     (ADDRESS = (PROTOCOL = TCP)(Host = <hostname>)(Port = <port>))
   )
(CONNECT_DATA =
   (SERVICE_NAME = <service_name>)
)
) The JSON object in the ormconfig has a place to put the host and the
port. I presume, however, typeorm does not know how to handle the service
name. Is that true? It only supports a SID? Thanks.

**Comment by pleerock** [comment]
it uses node-oracle underlying please checkout how do you do what you want with node-oracle (see docs on their options)

**Comment by gaugustfrank2** [comment]
The connection options for an oracle database are not documented in
connection-options.md.

The only example of an oracle entry in the ormconfig file shows the use of
an SID.  SIDs are not typically used with node-oracle to connect to an
oracle database.  An entry of the form

"Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=a host
url)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=a database service url)));User
ID=a_db_userid;Password=a_db_password"

found in a tnsnames.ora file is more likely to be used.

That means support for either a "connectionstring" or "servicename"
property would need to be added to the ormconfig.json file.

As it stands, it appears that typeorm only supports the use of an SID.  Is
that correct?

Thanks.

On Tue, Jul 3, 2018 at 1:16 PM, Umed Khudoiberdiev <notifications@github.com

**Comment by pleerock** [comment]
it what we use. 

Im not a big oracle expert, but we should support everything node-oracle does easily. Can you find in [their documentation](https://oracle.github.io/node-oracledb/doc/api.html) what exact connection options you need?

**Comment by gaugustfrank2** [comment]
I have successfully worked directly with node-oracle (oracledb) as follows.

var oracledb = require('oracledb');

oracledb.getConnection(
  {
    user          : "a_username",
    password      : "a_password",
    connectString : "(DESCRIPTION=(ADDRESS=(PROTOCOL = TCP)(HOST = a_hosturl)(PORT = 1521))(CONNECT_DATA=(SERVICE_NAME = a_serviceurl)))"
  },
  function(err, connection) {
    if (err) { console.error(err.message); return; }

    . . .  // use connection

    connection.close(
      function(err) {
        if (err) { console.error(err.message); }
      });
  });

Support for the connectString option is needed assuming this is not currently implemented in typeorm.
Thanks for your time.

**Comment by pleerock** [comment]
try to provide `connectString` in `extra` option of typeorm config. If that won't work then feel free to implement what you need, its easy to do!

**Comment by gaugustfrank2** [comment]
Thanks. Will do.

**Comment by derSoerrn95** [comment]
Nice, it works 🙂
