### ISSUE TITLE
Postgres array constructors support?

### ISSUE THREAD

**Issue by webwizrd** [typeorm/typeorm#2457]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Is there a way to use [postgres array constructors](http://www.postgresql.org/docs/current/interactive/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS) in typeorm?

**Comment by pleerock** [comment]
depends where exactly you would like to use it

**Comment by webwizrd** [comment]
I would like to select a column of type integer and return it as an array of integers (instead of an array of objects with one field of type integer).
In effect this:
`SELECT ARRAY(SELECT integerColumn FROM mytable WHERE attribute='value');`

This should result in an array of [int, int, int, int] (instead of [{integerColumn:int}, {integerColumn:int}, {integerColumn:int}].

Is this possible?
