### ISSUE TITLE
Dynamically create tables and queries at runtime?

### ISSUE THREAD

**Issue by SamuelMarks** [typeorm/typeorm#2458]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Not sure if this is easily doable, seeing as TypeScript compiles down to JavaScript, but is there a way to create tables at runtime? - And to modify the table name at runtime, without dropping to `.query`?

**Use case**
_Survey application_.: one Survey will be answered by many users, but created by one. Rather than take [the traditional approach](https://stackoverflow.com/q/1764435); I'm expecting an interface for users to create new tables—inheriting from a base (where PK and FK are set)—would dramatically improve efficiency of: insertion, update, read and aggregate analysis.

**Implementation**
Frontend(s) will allow user to create surveys. The questions [columns] are specified, and the transmitted to the API in JSON-schema. This JSON-schema is traversed, and used to create the table.

Hopefully this can be done with some TypeORM primitives; otherwise will revert to manually using `.query`.

---

What do you think?

**Comment by pleerock** [comment]
[There is api](http://typeorm.io/#/migrations/using-migration-api-to-write-migrations) you can use to create tables.
