### ISSUE TITLE
[SQLITE] Add options at column creation

### ISSUE THREAD

**Issue by blue112** [typeorm/typeorm#246]
I'd like to add options to some columns, so that this

    CREATE TABLE "group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" character varying(200) NOT NULL, "lastUpdateDate" timestamp without time zone NOT NULL, "createDate" timestamp without time zone NOT NULL, "creator" integer, "lastUpdater" integer)

     "name" character varying(200) NOT NULL

Turns into this

    "name" character varying(200) NOT NULL COLLATE NOCASE

So, just adding a custom string field to add after the field type descriptor would be fine.

**Comment by pleerock** [comment]
If we add "custom string field" schema sync wont work - because it won't be able to determine if column is changed or not, so its not recommended to add functionality. What exactly do you want to specify? Column COLLATION ?

**Comment by blue112** [comment]
Yes, I'd like to add COLLATE NOCASE to the column on table create, specifically.
So you could call that collation, and allow it to be set to "NOCASE" value in case of sqlite.

**Comment by pleerock** [comment]
Okay I'll mark this as a new feature and we will add "collation" into column options.

**Comment by pleerock** [comment]
this is easy feature but it needs time to implement it properly on all platforms and provide a test coverage. This is opened for PR if you have time and wish.

**Comment by AlexMesser** [comment]
released in `0.1.0-alpha.33`
