### ISSUE TITLE
postgres. After several hours of work in the pool, connections are exhausted.

### ISSUE THREAD

**Issue by nikolay-rogovoy** [typeorm/typeorm#2460]
**Issue type:**

[x ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

1) After several hours of work in the pool, connections are exhausted.
Which leads to the expectation of release of the connection, but they are not released.
`PostgresDriver.ts` :
`            this.master.connect((err: any, connection: any, release: any) => {

// here is the wait ... a long wait
// node-posgres:
/*
You must call the releaseCallback or client.release (which points to the releaseCallback) when you are finished with a client. If you forget to release the client then your application will quickly exhaust available, idle clients in the pool and all further calls to pool.connect will timeout with an error or hang indefinitely if you have connectionTimeoutMills configured to 0.
*/

                err ? fail(err) : ok([connection, release]);
            });
`
Perhaps somewhere that does not close the connection?

2) how to change max connection pool size?
PostgresConnectionOptions does not contain the corresponding property.
options.extra are marked as obsolete:

`        
// build connection options for the driver
        const connectionOptions = Object.assign({}, {
            host: credentials.host,
            user: credentials.username,
            password: credentials.password,
            database: credentials.database,
            port: credentials.port,
            ssl: credentials.ssl,
            max: 64, <--- ??????? default = 10
        }, options.extra || {});

     * todo: deprecate this and move all database-specific types into hts own connection options object.
     */
    readonly extra?: any;
`

**Comment by pleerock** [comment]
Please format your message properly. 

Such errors are hard to talk about, can you please create some demo repository that can somehow clearly show the problem?

**Comment by nikolay-rogovoy** [comment]
I was afraid of such an answer. :)
I see only one way.
change maxpoolsize in source code typeorm
and understand what happens to the connection pool itself.
I'll tell you about the results.
thanks for a quick response!

**Comment by pleerock** [comment]
Thank you very much for your investigations

**Comment by yonilerner** [comment]
@pleerock Following up on this, it seems like `MysqlDriver.createConnectionOptions` could be modified to accept `connectionLimit`. Would you accept a PR for this? I need to be able to access a much larger pool than 10 connections

**Comment by yonilerner** [comment]
Nevermind, I realized I can pass it with `extra`

**Comment by nikolay-rogovoy** [comment]
Everything works correctly.

**Comment by nikolay-rogovoy** [comment]
> Nevermind, I realized I can pass it with `extra`

    /**
     * Extra connection options to be passed to the underlying driver.
     *
     * todo: deprecate this and move all database-specific types into hts own connection options object.
     */
    readonly extra?: any;

One fine day it will stop working. :)
