### ISSUE TITLE
When emulating ionic app got error: Uncaught SyntaxError: Unexpected token ).

### ISSUE THREAD

**Issue by davidmpaz** [typeorm/typeorm#2461]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

Hello,

i am facing an issue with my ionic app when emulating or running it in a device, on browser runs fine. I hope someone could help me to find some direction to follow.

**Description**
After running the app it remains in a white screen. When I open the remote debugger in Chrome i can see this error: `Uncaught SyntaxError: Unexpected token ).`, and the error points me to this [chalk line](https://github.com/chalk/chalk/blob/v2.4.1/index.js#L117):
```
const proto = Object.defineProperties(() => {}, styles);
```

which makes me think about the fat arrow syntax is giving me troubles.

did some search and found this [other issue comment](https://github.com/VulcanJS/Vulcan/issues/1798#issuecomment-355277040) confirming my thoughts.

I did track down this problem to be introduced in a commit where I did move all db initialization to main `app.component` and db connection creation to be provided by Angular DI framework. Before that everything was working fine.

**Did Tried**
* to reproduce the error in the [ionic-example repo](https://github.com/davidmpaz/ionic-example/tree/reproduce-chalk-error) under the branch `reproduce-chalk-error`. I did not succeed. Still i did got an error: `RepositoryNotFoundError: No repository for "post" was found.` between message: `OPEN database: test` and `OPEN database: test - OK`. After that all queries ran ok. So maybe it could serve as reference to see what I currently have.
* to track which packages are using `chalk` and seems to be included by typeorm. At least in the `dependencies` section, not in `devDependencies`.
* to modify Webpack configuration to avoid it including `chalk` in the final bundle (vendor.js). Did not work either, or i did not do it right.

Sorry for the long post. Finally, my questions are :

**Questions**
* Is there any chance that `chalk@^2.3.2` and `cli-highlight@^1.2.3` (cli-highlight also uses chalk) could be moved to the dev dependencies?
* Could it be possible that the asynchronous calls are executing some logic before it should ? Most of the code is through Observables. The error from the repo make me think this.

Any help/hints would be highly appreciated.
Thanks in advance,
David

**Comment by pleerock** [comment]
> to modify Webpack configuration to avoid it including chalk in the final bundle (vendor.js). Did not work either, or i did not do it right.

I think this should work maybe try again?

> Is there any chance that chalk@^2.3.2 and cli-highlight@^1.2.3 (cli-highlight also uses chalk) could be moved to the dev dependencies?

we ship sql syntax highlighting in typeorm out of the box and its beautiful, I think we'll loose a lot if  we remove it because of those packages 

> Could it be possible that the asynchronous calls are executing some logic before it should ? Most of the code is through Observables. The error from the repo make me think this.

sorry I didn't understand what you mean

**Comment by davidmpaz** [comment]
Hi @pleerock thanks for your answer,

Regarding Webpack, i tried. But not succeed, I have see ionic guys also have some custom setup in place so, i will not dedicate more time into that.

I understand your point regarding the syntax highlight. Could you please point me out where in code is used the syntax highlighting or chalk in general? 

So far i have found references to it, only in PlatformTools.ts and in *Command classes. But commands are meant to be run in terminal (or not?) so I am more interested in logic executing at run time on devices.

I am thinking in giving it a try and remove all of that usage in a fork to troubleshoot the problem better.

thanks in advance,
David

**Comment by davidmpaz** [comment]
Just as documentation / feedback on the outcome of my last comment.

I did remove usage of syntax highlighting from `PlatformTools.js`, did move dependencies involved (`chalk` and `cli-highlight`) to the `devDependencies` section of my `package.json`.

So far results are positives. I don't get any error related to chalk and the app start normally on both, emulator and devices.
