### ISSUE TITLE
readonly with custom getter spatial property doubt

### ISSUE THREAD

**Issue by thiago-soliveira** [typeorm/typeorm#2462]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hey,

Should an `entity` like the one described below work? I'm facing issues while searching querying the database. I get no resuls, actually.

```ts 
@Entity()
export class Post {

 @PrimaryGeneratedColumn()
  id: number;

  @Column('decimal', { precision: 11, scale: 8 })
  latitude: number;

  @Column('decimal', { precision: 11, scale: 8 })
  longitude: number;

  @Column('point')
  get location(): string {
   return `POINT(${this.longitude} ${this.latitude})`
  }

}
 ```

It does work when I declare a property named `location` and set it with `entity.location = 'POINT(long lat)'`.

I don't like to set it this way and the `getter` seamed like a reasonable solution. I know there are other possibilities, but it would be nice to know if this is supposed to work or not.

Thanks a lot!
Awesome work btw

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
`@Column` must be set on a property, not getter function. What I can suggest you instead is to update location using even listeners (before update/insert)
