### ISSUE TITLE
Insert too many sql variables

### ISSUE THREAD

**Issue by samisamsam** [typeorm/typeorm#2463]
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[x ] `@next`
[ ] `0.x.x` (or put your version here)

I have many, many data to insert to my Database, and with save this is to slow i want it to be fast. With insert it is fast but i've got the sqlite error too many sql variables.
Can you help me find a solution please ?

**Comment by pleerock** [comment]
this is internal driver limitation and you can't avoid it. Solution is simple - insert your entities in chunks. For example if you want to save 10.000 entities, split array by 5 and call insert 5 times for each 2000 entities.

**Comment by pleerock** [comment]
Issue in your code. Just check it, found bugs and make your code work. There are no examples how to make your code work =)

**Comment by ricardocolares** [comment]
can i select my data in chunks? I have the same problem, but in my case, i'm trying yo bring data that it is already on database.

**Comment by Kononnable** [comment]
@ricardocolares I think [this](http://typeorm.io/#/select-query-builder/streaming-result-data) or [that](http://typeorm.io/#/select-query-builder/using-pagination) is what you're looking for.

**Comment by nextbyn** [comment]
Have same issue when insert a chunk of data. 

`PlatformTools.js:105 error:  Error: too many SQL variables
    at Database.handleError (sql.js:20)
    at Database.prepare (sql.js:20)
    at SqljsQueryRunner.<anonymous> (SqljsQueryRunner.js:101)
    at step (SqljsQueryRunner.js:41)
    at Object.next (SqljsQueryRunner.js:22)
    at SqljsQueryRunner.js:16
    at new t (polyfills.js:3)
    at __awaiter (SqljsQueryRunner.js:12)
    at SqljsQueryRunner.js:94
    at new t (polyfills.js:3)`


`Ionic:

   ionic (Ionic CLI)  : 4.4.0
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.3
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.1.1, (and 24 other plugins)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
`

**Comment by nextbyn** [comment]
This error came with a minimun list of element for insert  (146 elements in total)
`

[PlatformTools.js:105 query failed:  INSERT INTO "tt_detalle_promo"("idempresa", "codpromo", "orden", "artreq", "cantreq", "artbon", "cantrega", "bonif", "cada") VALUES (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?) -- PARAMETERS: [372,240,999904,3,999984,0,12.5,0,372,240,999904,3,999985,0,31,0,372,240,999904,3,940031,0,22.32,0,372,240,999904,3,940033,0,18.5,0,372,240,999904,3,946002,0,18.5,0,372,240,999904,3,947527,0,22.5,0,372,240,999904,3,999904,0,10.5,0,372,240,999904,3,999968,0,10.5,0,372,240,999904,3,937708,0,14.5,0,372,240,999904,3,937710,0,18.49,0,372,240,999904,3,938220,0,22,0,372,240,999904,3,939246,0,12,0,372,240,999904,3,939765,0,1.07,0,372,240,999904,3,939846,0,16,0,372,240,999904,3,933197,0,18,0,372,240,999904,3,933611,0,25.67,0,372,240,999904,3,933735,0,25.5,0,372,240,999904,3,935631,0,18.5,0,372,240,999904,3,936412,0,13.5,0,372,240,999904,3,937187,0,14.5,0,372,240,999904,3,921003,0,24,0,372,240,999904,3,924196,0,18,0,372,240,999904,3,929047,0,5.5,0,372,240,999904,3,930394,0,21.95,0,372,240,999904,3,931972,0,22,0,372,240,999904,3,933134,0,14,0,372,240,999904,3,903804,0,18.5,0,372,240,999904,3,903805,0,14,0,372,240,999904,3,918252,0,22,0,372,240,999904,3,919770,0,22,0,372,240,999904,3,920128,0,24,0,372,240,999904,3,920824,0,22,0,372,240,999968,3,902341,0,12.5,0,372,240,999968,3,902342,0,14.5,0,372,240,999968,3,902353,0,13,0,372,240,999968,3,902354,0,14,0,372,240,999968,3,902926,0,25,0,372,240,999968,3,902927,0,25,0,372,240,999968,3,999984,0,12.5,0,372,240,999968,3,999985,0,31,0,372,240,999968,3,940031,0,22.32,0,372,240,999968,3,940033,0,18.5,0,372,240,999968,3,946002,0,18.5,0,372,240,999968,3,947527,0,22.5,0,372,240,999968,3,999904,0,10.5,0,372,240,999968,3,999968,0,10.5,0,372,240,999968,3,937708,0,14.5,0,372,240,999968,3,937710,0,18.49,0,372,240,999968,3,938220,0,22,0,372,240,999968,3,939246,0,12,0,372,240,999968,3,939765,0,1.07,0,372,240,999968,3,939846,0,16,0,372,240,999968,3,933197,0,18,0,372,240,999968,3,933611,0,25.67,0,372,240,999968,3,933735,0,25.5,0,372,240,999968,3,935631,0,18.5,0,372,240,999968,3,936412,0,13.5,0,372,240,999968,3,937187,0,14.5,0,372,240,999968,3,921003,0,24,0,372,240,999968,3,924196,0,18,0,372,240,999968,3,929047,0,5.5,0,372,240,999968,3,930394,0,21.95,0,372,240,999968,3,931972,0,22,0,372,240,999968,3,933134,0,14,0,372,240,999968,3,903804,0,18.5,0,372,240,999968,3,903805,0,14,0,372,240,999968,3,918252,0,22,0,372,240,999968,3,919770,0,22,0,372,240,999968,3,920128,0,24,0,372,240,999968,3,920824,0,22,0,372,240,999984,3,902341,0,12.5,0,372,240,999984,3,902342,0,14.5,0,372,240,999984,3,902353,0,13,0,372,240,999984,3,902354,0,14,0,372,240,999984,3,902926,0,25,0,372,240,999984,3,902927,0,25,0,372,240,999984,3,999984,0,12.5,0,372,240,999984,3,999985,0,31,0,372,240,999984,3,940031,0,22.32,0,372,240,999984,3,940033,0,18.5,0,372,240,999984,3,946002,0,18.5,0,372,240,999984,3,947527,0,22.5,0,372,240,999984,3,999904,0,10.5,0,372,240,999984,3,999968,0,10.5,0,372,240,999984,3,937708,0,14.5,0,372,240,999984,3,937710,0,18.49,0,372,240,999984,3,938220,0,22,0,372,240,999984,3,939246,0,12,0,372,240,999984,3,939765,0,1.07,0,372,240,999984,3,939846,0,16,0,372,240,999984,3,933197,0,18,0,372,240,999984,3,933611,0,25.67,0,372,240,999984,3,933735,0,25.5,0,372,240,999984,3,935631,0,18.5,0,372,240,999984,3,936412,0,13.5,0,372,240,999984,3,937187,0,14.5,0,372,240,999984,3,921003,0,24,0,372,240,999984,3,924196,0,18,0,372,240,999984,3,929047,0,5.5,0,372,240,999984,3,930394,0,21.95,0,372,240,999984,3,931972,0,22,0,372,240,999984,3,933134,0,14,0,372,240,999984,3,903804,0,18.5,0,372,240,999984,3,903805,0,14,0,372,240,999984,3,918252,0,22,0,372,240,999984,3,919770,0,22,0,372,240,999984,3,920128,0,24,0,372,240,999984,3,920824,0,22,0,372,240,999985,3,902341,0,12.5,0,372,240,999985,3,902342,0,14.5,0,372,240,999985,3,902353,0,13,0,372,240,999985,3,902354,0,14,0,372,240,999985,3,902926,0,25,0,372,240,999985,3,902927,0,25,0,372,240,999985,3,999984,0,12.5,0,372,240,999985,3,999985,0,31,0,372,240,999985,3,940031,0,22.32,0,372,240,999985,3,940033,0,18.5,0,372,240,999985,3,946002,0,18.5,0,372,240,999985,3,947527,0,22.5,0,372,240,999985,3,999904,0,10.5,0,372,240,999985,3,999968,0,10.5,0,372,240,999985,3,937708,0,14.5,0,372,240,999985,3,937710,0,18.49,0,372,240,999985,3,938220,0,22,0,372,240,999985,3,939246,0,12,0,372,240,999985,3,939765,0,1.07,0,372,240,999985,3,939846,0,16,0,372,240,999985,3,933197,0,18,0,372,240,999985,3,933611,0,25.67,0,372,240,999985,3,933735,0,25.5,0,372,240,999985,3,935631,0,18.5,0,372,240,999985,3,936412,0,13.5,0,372,240,999985,3,937187,0,14.5,0,372,240,999985,3,921003,0,24,0,372,240,999985,3,924196,0,18,0,372,240,999985,3,929047,0,5.5,0,372,240,999985,3,930394,0,21.95,0,372,240,999985,3,931972,0,22,0,372,240,999985,3,933134,0,14,0,372,240,999985,3,903804,0,18.5,0,372,240,999985,3,903805,0,14,0,372,240,999985,3,918252,0,22,0,372,240,999985,3,919770,0,22,0,372,240,999985,3,920128,0,24,0,372,240,999985,3,920824,0,22,0]](url)`

PlatformTools.js:105 error:  Error: too many SQL variables

**Comment by havenchyk** [comment]
@nextbyn as already were answered, try to split your insert into chunks and run them one by one, check the comments above

**Comment by nextbyn** [comment]
> @nextbyn as already were answered, try to split your insert into chunks and run them one by one, check the comments above

I already do that. even if I split the array into 50 elements fails with error

**Comment by Kononnable** [comment]
Then try splitting by 10, or check your `SQLITE_MAX_VARIABLE_NUMBER` to see how many parameters you can use on your setup.

**Comment by pleerock** [comment]
there is a `chunk` option in save options that was created exactly for this particular issue, e.g. `save([...], { chunk: 100 })` - insert 100 items per time

**Comment by ataft** [comment]
I was able to get it to work with chunks, but the performance was very slow. Then I tried creating a SQL string without parameters/variables and executed a direct query, which took it from 16 seconds down to 2 seconds.

This may be naive, but for inserts, what is the purpose of variables/parameters since there will be one per insert value? Would it be better to insert like this:
```
INSERT INTO MyTable ( Column1, Column2 ) 
VALUES ( Value1, Value2 ), ( Value1, Value2 )

```

**Comment by nnabinh** [comment]
Imho, the library should handle it internally when it reaches the max limit.

**Comment by wmakeev** [comment]
It not possible to split on chunks if I have one entity which includes cascade collection. One `CustomerOrder` have many `CustomerOrderPosition` items, for example. 

```ts
@OrmEntity()
class CustomerOrder {
    @Column()
    name: string
    
    @OneToMany(() => CustomerOrderPosition, position => position.order, { cascade: true })
    positions!: CustomerOrderPosition
}
```

**Comment by o-k-l-l-a** [comment]
![Screenshot 2024-06-18 155939](https://github.com/typeorm/typeorm/assets/89906412/090ef727-cbab-4c9d-bb23-2d77bce4acfc)
The "get inbound failed: too many SQL variables" error suggests that a database query in your application is attempting to use more variables than the database allows. This is a common issue in applications dealing with large datasets or complex queries. Here's how you can address this issue:

### Steps to Resolve the "Too Many SQL Variables" Error

1. **Identify the Query Causing the Issue**:
   - Check the logs or the error message details to identify which query is causing the problem. This will help in understanding the context of the error.

2. **Review and Modify the SQL Query**:
   - If the query involves a large number of parameters, try to break it into smaller parts or batches.

3. **Use Batching for Large Queries**:
   - Split the data into smaller chunks and process each chunk separately. Here's an example in Python using SQLite:

   ```python
   def batch_query(cursor, data, batch_size=100):
       for i in range(0, len(data), batch_size):
           batch = data[i:i + batch_size]
           cursor.executemany("INSERT INTO table_name (col1, col2) VALUES (?, ?)", batch)
   ```

4. **Optimize the Query**:
   - If possible, rewrite the query to reduce the number of variables. For instance, instead of using an `IN` clause with many values, consider using temporary tables or join operations.

5. **Check and Adjust Database Configuration**:
   - For SQLite, the default limit for variables is 999. You can check this by running the following command in SQLite:

     ```sql
     PRAGMA compile_options;
     ```

     However, changing this limit requires recompiling SQLite, which is not recommended for production environments.

   - For PostgreSQL, MySQL, or other databases, refer to their respective documentation for increasing the limit or optimizing queries.

6. **Review Application Logic**:
   - Ensure that the application logic is not inadvertently creating queries with too many variables. This can happen in loops or bulk operations.

### Example Solution

Suppose you have a query that selects data using a large number of IDs:

```sql
SELECT * FROM table_name WHERE id IN (?, ?, ?, ..., ?);
```

Instead of a single large query, you can split it into multiple smaller queries:

```python
def fetch_data_in_batches(cursor, ids, batch_size=100):
    results = []
    for i in range(0, len(ids), batch_size):
        batch = ids[i:i + batch_size]
        placeholders = ', '.join('?' for _ in batch)
        query = f"SELECT * FROM table_name WHERE id IN ({placeholders})"
        cursor.execute(query, batch)
        results.extend(cursor.fetchall())
    return results
```

### Restart the X-ray Service

After addressing the SQL query issue, restart the X-ray service using the appropriate command for your operating system:

**On Linux:**

```sh
sudo systemctl restart xray
```
or
```sh
sudo service xray restart
```

**On Windows:**

```sh
net stop xray
net start xray
```

### Consult Documentation and Support

If the problem persists, consult the official documentation for your database and X-ray service. Seeking help from community forums or the support team might also provide specific insights or patches related to this issue.

By following these steps, you can resolve the "too many SQL variables" error and ensure that the X-ray service operates smoothly.
