### ISSUE TITLE
ManyToMany onDelete option

### ISSUE THREAD

**Issue by lucas-coelho** [typeorm/typeorm#2464]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

ManyToMany decorator `onDelete` options is not working. 
The  default value is 'CASCADE' and its not possible to change. 

```
export class Foo {

  @PrimaryGeneratedColumn()
  id: number;

  @JoinTable()
  @ManyToMany(_ => Bar, bar => bar.foos,  {
    cascade: false,
  })
  bars: Bar[]

}
```

**Comment by pleerock** [comment]
Im going to release this change end of this week. Thank you!

**Comment by P0oOOOo0YA** [comment]
Still the same using typeorm with SQLite onDelete: CASCADE doesn't work. Entities have ManyToMany relation.
