### ISSUE TITLE
postgres. schema synchronization error for long table names

### ISSUE THREAD

**Issue by nikolay-rogovoy** [typeorm/typeorm#2473]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1) datasourceatentitycolumncondition.ts
```
@Entity()
export class Datasourceatentitycolumncondition {
    @PrimaryGeneratedColumn()
    iddatasourceatentitycolumncondition: number;

    @Column({nullable: true})
    name: string;
}
```

2) getConnection().synchronize(); produces a query:
```
CREATE TABLE "datasourceatentitycolumncondition"
(
  "iddatasourceatentitycolumncondition" SERIAL NOT NULL,
  name varchar(50),
  CONSTRAINT "PK_20f68cdf35abf28169691b09e37" PRIMARY KEY ("iddatasourceatentitycolumncondition")
)
```

3) postgress automatically creates a sequence:
 ```
nextval('datasourceatentitycolumncondi_iddatasourceatentitycolumncon_seq'::regclass)
```
Attention: 'datasourceatentitycolumncondi_....  <--- the table name was truncated

4) when you call again getConnection().synchronize(); then
PostgresQueryRunner.ts -> loadTables(tableNames: string[])
incorrectly defines the field: column_default

`
if (dbColumn["column_default"].replace(/"/gi, "") === nextval('${this.buildSequenceName(table, dbColumn["column_name"], currentSchema, true)}'::regclass)) {
`
which leads to the removal of the sequence.

you must add a limit to the length of the table name.
or something come up :)

**Comment by pleerock** [comment]
Yes I think we can close it, don't think this issue worth investigations.
