### ISSUE TITLE
Safe Raw find operator

### ISSUE THREAD

**Issue by asafigan** [typeorm/typeorm#2475]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

Can there be a find operator that is like `Raw` but will safely insert values like the query builder's `where`?

API

`SafeRaw("title = :title", {title: "value"})`

I would like it so that like can do something like this:

```
{
    where: {
        id: In(SafeRaw(
            "select sluggableId from slug where slug in :slugs and sluggableType = :sluggableType", 
            {slugs: ['userInput'], sluggableType: Type.name}
        ))
    }
}
```

**Comment by darky** [comment]
:+1: to second parameter to exist `Raw`

**Comment by u8sand** [comment]
I'm also keen on getting this implemented; it will make full-text-search very simple to create an operator for. i.e. `SafeRaw(`ts_vector(${alias}) @@ plainto_tsquery('english', :1)`, query)`

I've done some work on this; perhaps it will provide a simple starting point for it to be incorporated. The following patch is a hack--I've coerced things to `any` and it should not be thought of as a ready-to-go implementation. Nonetheless, the existing `raw` operator is extended to support parameters and a working test is demonstrated. It does so by simply passing the value itself and any parameters to the `value` of `FindOperator` and sets the `useParameter` & `multipleParameters` to reuse the existing parameter passing code. The public `value` getter returns the `parameters` externally so that it gets used as expected. Internally, the raw function is given another argument for use in the query itself.

E.g. for my use case:
```
find({
  field: Raw(
    (alias, params) => `ts_vector(${alias}) @@ plainto_tsquery('english', ${params[0]})`,
    [query]
  )
})  
```

```
diff --git src/find-options/FindOperator.ts src/find-options/FindOperator.ts
index f2b8a6c5..83b35573 100644
--- src/find-options/FindOperator.ts
+++ src/find-options/FindOperator.ts
@@ -71,10 +71,15 @@ export class FindOperator<T> {
      * Gets the final value needs to be used as parameter value.
      */
     get value(): T {
-        if (this._value instanceof FindOperator)
+        if (this._value instanceof FindOperator) {
             return this._value.value;
+        }
 
-        return this._value;
+        if (this._type === 'raw') {
+            return (this._value as any).parameters;
+        } else {
+            return this._value;
+        }
     }
 
     // -------------------------------------------------------------------------
@@ -113,10 +118,10 @@ export class FindOperator<T> {
             case "isNull":
                 return `${aliasPath} IS NULL`;
             case "raw":
-                if (this.value instanceof Function) {
-                    return this.value(aliasPath);
+                if ((this._value as any).value instanceof Function) {
+                    return (this._value as any).value(aliasPath, parameters);
                 } else {
-                    return `${aliasPath} = ${this.value}`;
+                    return `${aliasPath} = ${(this._value as any).value}`;
                 }
         }
 
diff --git src/find-options/operator/Raw.ts src/find-options/operator/Raw.ts
index cb0c163e..22647312 100644
--- src/find-options/operator/Raw.ts
+++ src/find-options/operator/Raw.ts
@@ -2,8 +2,8 @@ import {FindOperator} from "../FindOperator";
 
 /**
  * Find Options Operator.
- * Example: { someField: Raw([...]) }
+ * Example: { someField: Raw([...], { ) }
  */
-export function Raw<T>(value: string|((columnAlias?: string) => string)) {
-    return new FindOperator("raw", value as any, false);
+export function Raw<T>(value: string|((columnAlias?: string, parameters?: string[]) => string), parameters: any[] = []) {
+    return new FindOperator("raw", { value, parameters } as any, true, true);
 }
\ No newline at end of file
diff --git test/functional/repository/find-options-operators/repository-find-operators.ts test/functional/repository/find-options-operators/repository-find-operators.ts
index 4434721f..5ed1e323 100644
--- test/functional/repository/find-options-operators/repository-find-operators.ts
+++ test/functional/repository/find-options-operators/repository-find-operators.ts
@@ -535,6 +535,26 @@ describe("repository > find options > operators", () => {
 
     })));
 
+    it("raw (function) with params", () => Promise.all(connections.map(async connection => {
+
+        // insert some fake data
+        const post1 = new Post();
+        post1.title = "About #1";
+        post1.likes = 12;
+        await connection.manager.save(post1);
+        const post2 = new Post();
+        post2.title = "About #2";
+        post2.likes = 3;
+        await connection.manager.save(post2);
+
+        // check operator
+        const loadedPosts = await connection.getRepository(Post).find({
+            likes: Raw((columnAlias, parameters: string[]) => `${parameters[0]} + ${columnAlias} = 4`, [1])
+        });
+        loadedPosts.should.be.eql([{ id: 2, likes: 3, title: "About #2" }]);
+
+    })));
+
     it("should work with ActiveRecord model", () => PromiseUtils.runInSequence(connections, async connection => {
         PersonAR.useConnection(connection);
 
```

Some of the types will need to be modified a bit, and maybe the approach can be less of a hack--I hope someone more familiar with the project can take it from me, or let me know what I can do to finalize this patch and submit it as a pull request.

**Comment by pedrosancao** [comment]
@u8sand since the last message have you done some work on this? Or there is a fork with ongoing work the other con contribute from?

**Comment by u8sand** [comment]
@pedrosancao unfortunately I have not; i ended up basically using and extending the query builder instead as my use case needed to take advantage of more combinational full text search queries expanding beyond the scope of the repository.

At the time however, my patch did work, i would expect that a similar approach should still be valid albeit with some modifications to reflect any changes to that code and additions to adequately express the typescript types.

**Comment by imnotjames** [comment]
Does #6850 cover this?

**Comment by quezak** [comment]
@imnotjames looks great! Would it be hard to also extend that PR to work with named parameters like query builder functions and [my example above](https://github.com/typeorm/typeorm/issues/2475#issuecomment-548009611)?

**Comment by temnov98** [comment]
> @imnotjames looks great! Would it be hard to also extend that PR to work with named parameters like query builder functions and [my example above](https://github.com/typeorm/typeorm/issues/2475#issuecomment-548009611)?

Thank you! I added this feature now.

**Comment by temnov98** [comment]
@asafigan you can close this issue. This functionality has been added to ```Raw()``` find operator in #6850.
