### ISSUE TITLE
Query an Array of Embedded Documents

### ISSUE THREAD

**Issue by CosmoFruit** [typeorm/typeorm#2483]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have two entities:

```
export class User {
  @ObjectIdColumn()
  id: ObjectID;

  @Column()
  username: string;

  @Column()
  avatar: string;

  @Column(type => UserAccount)
  accounts: UserAccount[];

}

export class UserAccount {
  @ObjectIdColumn()
  id: ObjectID;

  @Index({unique: true})
  @Column()
  email: string;

  @Column()
  password_hash: string;
}
```

i try find user by account id:
```
  const u: User = await this.userRepository.findOne({
      where { accounts: {id: targetAccauntId}}
    })
```
but result is empty

how to right search in array of embedded entities?

**Comment by lvao813** [comment]
I also encountered the same problem.

**Comment by atejadac** [comment]
I too have the same problem. Pretty hard to believe that TypeOrm doesn't offer that feature. Switching to Mongoose if this is not solved.

**Comment by Squallium** [comment]
Hi, I think this another issue could be related #1766

**Comment by rustamwin** [comment]
@CosmoFruit try it:
```typescript
const u: User = await this.userRepository.findOne({
       "accounts.id": targetAccauntId
    })
```
or
```typescript
const u: User = await this.userRepository.findOne({
       {accounts: {id: targetAccauntId}}
    })
```

**Comment by rustamwin** [comment]
See #3756

**Comment by kaczor6418** [comment]
> @CosmoFruit try it:
> 
> ```ts
> const u: User = await this.userRepository.findOne({
>        "accounts.id": targetAccauntId
>     })
> ```
> 
> or
> 
> ```ts
> const u: User = await this.userRepository.findOne({
>        {accounts: {id: targetAccauntId}}
>     })
> ```

Sorry but both of this options are not working, they are returning only **undefined**

**Comment by saykat** [comment]
const u: User = await this.userRepository.findOne({
      where: { "accounts.id" : targetAccauntId}
    })
hope it will work

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by hoangtrung17** [comment]
I tried this code for save data to test but accounts fill is null affter transform:
` @Column(type => UserAccount)
  accounts: UserAccount[];` 
I think Mongoose is better than typeOrm to work with mongoDB

**Comment by AbdallahShnaino** [comment]
const u: User = await this.userRepository.findOne({
      where: { "accounts.id" : targetAccauntId}
    })
