### ISSUE TITLE
Cannot assign to read only property `type` of object. (Problem when initializing driver)

### ISSUE THREAD

**Issue by maleta** [typeorm/typeorm#2486]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I get warning(error)
```
(node:11064) UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'type' of object '#<Object>'
    at Function.assign (<anonymous>)
    at PostgresDriver.<anonymous> (/mnt/c/Users/Maleta/Documents/Work/discord-exchange/admin-app/node_modules/typeorm/driver/postgres/PostgresDriver.js:780:38)
```

when starting my nodeJS app. Problem is with field `type` inside config because it is passed to constructor of postgres driver but field `type` is read only. If field `type` is not provided, then `typeorm` don't know what driver should be created, so I guess it's bug.

**Comment by pleerock** [comment]
> but  field type is read only.

what does it mean? You should not have this error until you do something very very strange.

**Comment by maleta** [comment]
I am not sure what means that field type is read only. It's something related to either postgres driver or typeorm library. I have configuration in JSON file and I use it like this:

`await createConnection(cfg.get("dbConfig"));`

and value of dbConfig in JSON config file is:

    {
         "type": "postgres",
        "host": "192.168.0.1:5432",
        "user:": "test",
        "password": "test",
        "database": "test",
        "entities": [
           "entity/admin/*.ts"
        ],
        "migrations": [
           "migrations/*.ts"
        ],
        "cli": {
           "entitiesDir": "entity",
           "migrationsDir": "migrations"
        }
    }

So there is no space in this few lines of code to have very strange code.

**Comment by maleta** [comment]
Problem is in postgres driver itself. Driver tries to change value on field `type`, but field is read only because it is loaded from config file using npm package config. I don't see why postgres driver would need to change value of `type` field. I got same error for field `name` when I added it to configuration.

**Comment by Kononnable** [comment]
Closing since related to db driver, not orm.
