### ISSUE TITLE
innerJoinAndSelect option but just select part of the model

### ISSUE THREAD

**Issue by dee-el** [typeorm/typeorm#2488]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi, i want asking something, if i using getManager().getRepository(model).
and using the join option, like `innerJoinAndSelect`, can i just do select part of the model?

**Comment by pleerock** [comment]
yes you can, but use `innerJoin` instead of `innerJoinAndSelect` and then add `select` manually, for example: `innerJoin("post.categories", "category").addSelect(["category.id", "category.name"])`

**Comment by dee-el** [comment]
thanks for the answer.
sorry for asking again,
i should put the example at first.

so i can try using two ways right?
the first is like this
```
const user = await getManager().getRepository(User)
    .where("user.id = :userId", {userId})
    .innerJoin("user.photos", "photo")
    .addSelect(["photo.id", "photo.name", "user.name"])
```
and the second one is like this
```
const user = await getManager().getRepository(User).findOne({
    where: {userId},
    join: {
         alias: "user",
          innerJoin: {
                photos: "user.photos"
           }
    },
    select: ["photo.id", "photo.name", "user.name"]
})
```

**Comment by Diluka** [comment]
>yes you can, but use innerJoin instead of innerJoinAndSelect and then add select manually, for example: innerJoin("post.categories", "category").addSelect(["category.id", "category.name"])

@pleerock If I use `innerJoin` and `addSelect` it will not work.
I checked the generated sql. It is right and selected witch I put in `addSelect`. But on the entity, the relation entity property is `null`

**Comment by anymost** [comment]
The same issue I found. Just use '.getRawMany()'. The result is right.

**Comment by imnotjames** [comment]
This has been answered.  As such I'm closing it out.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
