### ISSUE TITLE
"MissingPrimaryColumnError"

### ISSUE THREAD

**Issue by WoLfulus** [typeorm/typeorm#249]
Hello,

I don't know how to solve this problem. I do follow the patterns on the docs tho.

What am I doing wrong?

infracao.ts

```
/**
 * Imports
 */

import {
    Entity,
    AbstractEntity,
    Column,
    PrimaryColumn,
    PrimaryGeneratedColumn,
    CreateDateColumn,
    UpdateDateColumn
} from "typeorm";

import { InfracaoServiceBase } from "./base/infracao";

/**
 * infracao.ts
 */
@Entity("svc_infracao")
export class InfracaoService extends InfracaoServiceBase {

}
```

base\infracao.ts

```
import {
    Entity,
    AbstractEntity,
    Column,
    PrimaryColumn,
    PrimaryGeneratedColumn,
    CreateDateColumn,
    UpdateDateColumn
} from "typeorm";

@AbstractEntity()
export class InfracaoServiceBase {

    @PrimaryColumn("int", {
        name: "id",
        generated: true
    })
    id: number;

    @Column("string", {
        name: "ait",
        nullable: true,
        length: 255,
    })
    ait: string;

}
```

And the error:

```
api_1       |         "name": "MissingPrimaryColumnError",
api_1       |         "message": "Entity \"InfracaoService\" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity."
```

**Comment by pleerock** [comment]
Can you show your connection configuration? Did you include `InfracaoServiceBase` in entities list?

**Comment by WoLfulus** [comment]
I don't remember, but I think I didn't. I'll try adding it.

One question I had after re-reading the docs. This way will only generate one entity?

I mean, it's the "same" as adding all the columns in the base entity to a the final class?

I'll do some more tests.

**Comment by pleerock** [comment]
yes, correct.

**Comment by WoLfulus** [comment]
Adding the base class to the entities solved the issue. What about primary key composed by foreign keys? It throws the same error.

**Comment by pleerock** [comment]
can you provide complete example?

**Comment by WoLfulus** [comment]
I've skipped the table for now... I'll post a complete example when I'm back at it.

**Comment by pleerock** [comment]
Please reopen this issue if you still have problems.
