### ISSUE TITLE
Use Semantic Versioning to communicate breaking changes

### ISSUE THREAD

**Issue by leoskyrocker** [typeorm/typeorm#2490]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[X] `Any`
[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.x.x` (or put your version here)

**Steps to reproduce**
Try to upgrade typeorm from 0.1.21 to 0.2.26:

Observe breaking changes as entity options `cascadeInsert: true` is changed to `cascade: ['insert']`. We also observed several other breaking changes that we're not expecting when upgrading typeorm version.

**Comment by pleerock** [comment]
In a semantic versioning breaking changes between 0.x and 0.x are acceptable.

**Comment by leoskyrocker** [comment]
Please refer to https://docs.npmjs.com/about-semantic-versioning:

> If you introduce a change that breaks a package dependency, we strongly recommend incrementing the version major number; see below for details.

**Comment by Kononnable** [comment]
`X >0` is the crucial part.
>Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So technically it's compatible with semver. Do we like 0 as major version number is completely different thing :)
