### ISSUE TITLE
How to get HEX field password from db and test with MD5 string

### ISSUE THREAD

**Issue by stefy63** [typeorm/typeorm#2491]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello, i must get user from existing db table with password field type is VARBINARY and when
i test fiield with MD5(string) dont match. How can i made?

Stefano

**Comment by pleerock** [comment]
Please make investigations and provide additional information.
