### ISSUE TITLE
Issue while trying to overload custom class decorator with the Entity decorator

### ISSUE THREAD

**Issue by danrevah** [typeorm/typeorm#2492]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

Doesn't matter

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

--

First of all, it's a great library and I've really enjoyed using it. so good job for the great work!

I've got a problem while I'm trying to write custom class decorators and I'm trying to 'overload' it with one of the entities.

I'm not quite sure how the `@Entity` decorator is working behind the scenes.
But, let's assume this is my class deocrator:

```typescript
export function test (c: any): any {

  return class extends (c as { new(...args: any[]): any; }) {

    constructor(...args: any[]) {
      super(...args);
      console.log('constructor', typeof this);
      Object.getOwnPropertyNames(this).forEach((propertyKey: any) => {
        console.log('=>',propertyKey);
      });
    }
  }
}
```

and i'm trying to overload the entity as follow:

```typescript
@test // before or after it doesn't matter, I get for both errors.
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

   // ...
}
```

and i'm getting the following error: 

```
EntityMetadataNotFound: No metadata for "User" was found.
```

What I am trying to accomplish is to add a simple decorator and to print its properties using `getOwnPropertyNames`, is there something I should do so it would work with the Entity decorator?

---
 I'm trying to figure it out since I want to use the library I wrote `TypeSerializer` (https://github.com/danrevah/typeserializer) with your awesome lib.

**Comment by 19majkel94** [comment]
You can replace the class with your own class generated on the fly as other decorators are attached to the `User` class so that's why you get `EntityMetadataNotFound` error.

> I'm trying to figure it out since I want to use the library I wrote TypeSerializer (danrevah/typeserializer) with your awesome lib.

Why not just use [class-transformer](https://github.com/typestack/class-transformer)?

**Comment by pleerock** [comment]
> What I am trying to accomplish is to add a simple decorator and to print its properties using getOwnPropertyNames, is there something I should do so it would work with the Entity decorator?

But you do multiple other things. Your issue that you create a new class which is not just User anymore, and entity is getting attached to a new class that you return. 

This is not related to TypeORM somehow, so I'll close it.
