### ISSUE TITLE
Cascade insert issue

### ISSUE THREAD

**Issue by juancamilov06** [typeorm/typeorm#2494]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have two models, Booking and User with ManyToMany relationship. This is how i've defined them:

Booking model
`@Entity('Booking')
export class Booking {

    @PrimaryColumn()
    public id: number;

    @Column({ name: 'promotion_id' })
    public promotionId: number;

    @Column({ name: 'start_date', type: Date })
    public startDate: Date;

    @OneToOne(type => BookStatus)
    @JoinColumn({ name: 'status_id' })
    public status: BookStatus;

    @ManyToMany(type => User, { cascade: true })
    @JoinTable({
        name: 'UsersBooking',
        joinColumns: [
            { name: 'booking_id' }
        ],
        inverseJoinColumns: [
            { name: 'user_id' }
        ]
    })
    public users: User[];
}`

User model
`
@Entity('User')
export class User {

    @PrimaryColumn({ name: 'email'})
    public email: string;

    @Column({ name: 'name' })
    public name: string;

    @Column({ name: 'phone' })
    public phone: string;

}`

In booking model ManyToMany annotation i've set `{cascade: true}` but when i run this piece of code:
`
const book = new Booking();
book.users = [];
book.users.push(user);
book.promotionId = promotionId;
book.startDate = moment(date).toDate();
return await this.bookingRepository.save(book);
`
Only booking is saved. 
Thanks :)

**Comment by pleerock** [comment]
Does your user have a email set? Please provide a PR with a failing test that reproduces this issue and we'll try to fix that.

**Comment by juancamilov06** [comment]
yes, it has email set but when i insert booking, it doesn't insert in the middle table of the ManyToMany relationship, it only inserts in Booking table

**Comment by Kononnable** [comment]
@juancamilov06 
Did you resolve your issue?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
