### ISSUE TITLE
Virtual Field in Entity

### ISSUE THREAD

**Issue by totalard** [typeorm/typeorm#2498]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[] `@next`
[ ] `0.x.x` (or put your version here)

How can i create virtual fields in Entity
that is model has field, But it will not stored in the DB. it is defined as a function. the function defined at the entity, Every time the entity loaded this field act as normal fields, But only Readonly,

Hope You understood

**Comment by pleerock** [comment]
Provide a detailed proposal on a feature request with code examples.

**Comment by totalard** [comment]
It is Very Easy to Understand @pleerock 

Just a Field in Entity, Which is not stored in DB (Has No relation to DB)
But the value is calculated using other fields value (Eg : Total Amount)

For Every Query to Entity or in Json Response,, The Field Must be there as other DB Field. But cannot Write value in it,, Because it is a Calculated Field.

Hope U Understood.

A Definition:
Fields can have values calculated by a function, instead of simply reading a database stored value. A computed field is declared just like a regular field,

**Comment by s97712** [comment]
Like `asExpression`, but support all database in `typeorm`?

**Comment by s97712** [comment]
I also need this, are you accept PR for this? @pleerock

**Comment by nilfalse** [comment]
+1

**Comment by thatisuday** [comment]
@totalard Follow my answer here: https://github.com/typeorm/typeorm/issues/1288#issuecomment-478337948

**Comment by danjudex** [comment]
+1

**Comment by totalard** [comment]
Any Feedback?

**Comment by victorigualada** [comment]
I believe that what you are looking for if the method `getRawMany()`.

If you have an entity:
```
@Entity()
export class Employee {

  @Column('name')
  name: string;

  @Column('start_date')
  startDate: Date;

  // this is your "virtual field", as you called it, that remains a TS property
  // without the @Column() decoractor
  daysInEnterprise: number;
}
```

Then, in your query you could do:

```
  const employee: Employee = await getConnection()
    .createQueryBuilder(Employee, 'employee')
    .addSelect('DATE_DIFF(CURRENT_DATE(), employee.start_date)' as "daysInEnterprise")
    .where('employee.name = :name', { 'Timber' })
    .getRawMany();
```

In this way you will have all the properties in the `Employee` class populated by the the fields of the `addSelect()` plus the properties decorated with `@Column()`.

The keys here are:
  ·  `getRawMany()` so TypeORM won't map the result to the entity
  ·  the use of double quotes in the alias of the selected field `as "daysInEnterprise"`
     to match the name of the property

**Comment by giovannefc** [comment]
It works fine:
https://github.com/typeorm/typeorm/issues/1288#issuecomment-478337948

**Comment by Overfacto** [comment]
@victorigualada is right, it is not required function.

Maybe `addSelectAndMap` which will be implemented function helps you

**Comment by imnotjames** [comment]
Seems like this has been answered.  Closing out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by goranjviv** [comment]
For anyone bumping into this thread, you can use [listeners](https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md) to achieve this (I use `@AfterLoad` to calculate fields like `totalCountOfWords`, for example). 
If you need to be able to save modifications to 'virtual fields', you can achieve that by using `@BeforeInsert` and `@BeforeUpdate`. E.g. you can store money in two fields `(toPayAmount: bigint, toPayCurrency: CurrencyEnum)`, load them into `toPay: { amount, currency}` field by using `@AfterLoad`, and then save modifications to `toPay` by applying updates to fields mapped to real columns in a function decorated with `@BeforeInsert` and `@BeforeUpdate`.

**Comment by pietrzakadrian** [comment]
I wrote an article on my blog about it.
I have presented all possible solutions, including one very well-functioning solution to this problem. (v0.2.37)

https://pietrzakadrian.com/blog/virtual-column-solutions-for-typeorm ✌️

**Comment by CollinCashio** [comment]
@totalard @danjudex @imnotjames @goranjviv @pietrzakadrian - @pietrzakadrian your blog inspired me to create this issue https://github.com/typeorm/typeorm/issues/9323, because I also needed a way to search on the "Virtual Columns", and I wanted it to be consolidated into an entities class definition - I also created a pull request for this solution to be implemented in typeORM. Please check it out and let me know what you think.

**Comment by frankgo81** [comment]
see this article https://pietrzakadrian.com/blog/virtual-column-solutions-for-typeorm

**Comment by ilsrbn** [comment]
@CollinCashio As I understand your VirtualColumn decorator now is a part of typeorm. I've tried it.
Code example of retriving total balance of all related bank accounts:
```typescript
@VirtualColumn({
  type: 'decimal',
  query: (entity) =>
    `SELECT SUM(balance) FROM account WHERE ownerId = ${entity}.id AND deleted_at IS NULL`;
  })
balance: string;
```

Works perfect! Thanks for you contribution!

**Comment by emulienfou** [comment]
Great feature!
However how should I manage the case that my virtual column query is depending on a variable?

I have a use-case where I need to check if the logged-in user's Id exists in DB and I have the user's Id in a variable `userId`, I'm using nextjs btw!

So I cannot write a SELECT query inside the `@VirtualColumn` decorator because the entity doesn't have this information, but the Repository have it!

I was thinking of have a decorator without the required `query` parameter actually!

**Comment by tq-tuan** [comment]
@emulienfou I have the same issue with you. Looking forward the new option for VirtualColumn

**Comment by ronskyi** [comment]
"Virtual" can depend on aggregate from another table, `addSelectAndMap` is not implemented as well (

**Comment by aymather** [comment]
I really love this feature, but for some reason when I try to query other tables inside my virtual column query, i get an error saying that the relation cannot be found. I investigated the current schema and it says that the current schema inside that query is set to `public`, but that's not my current schema. Has anyone run into this?
