### ISSUE TITLE
Postgres DELETE query result is useless

### ISSUE THREAD

**Issue by newsiberian** [typeorm/typeorm#2499]
**Issue type:**
Hi, @pleerock, I faced with strange results from .remove() and .delete()  queries. delete() query result are pretty much useless currently. It is always `{ raw: [] }`.

Here is debugging result from [here](https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresQueryRunner.ts#L177)
![typeorm_1](https://user-images.githubusercontent.com/11130487/42551885-c20dc070-8503-11e8-9143-6a052d23dadc.png)

In addition, there is a lack in docs query results. Is it possible to consider the possibility of changing api and return something valuable. In my opinion, the number of removed rows will be the best for .remove() and .delete() queries.

[ ] question
[ ] bug report
[x] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
yes, we already had such feature request. We can return more information in Insert/Update/DeleteResult objects. Feel free to contribute!

**Comment by vlapo** [comment]
@newsiberian Is this issue resolved?

**Comment by newsiberian** [comment]
@vlapo, nope, even after pr was merged, I still receive the same results

**Comment by pleerock** [comment]
how come? it was merged a new version was released, why do you still have same results? do you have your changes in the latest version you have installed?

**Comment by Kononnable** [comment]
Closing as no response from the author.
