### ISSUE TITLE
OracleDb SYS_REFCURSOR

### ISSUE THREAD

**Issue by konraddysput** [typeorm/typeorm#2501]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hey!

I want to integrate my nodejs application with oracledb tables. I want to receive big amount of data by using SYS_REFCURSOR. From oracledb documentation available here: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-144-ref-cursor-bind-parameters I know that I can use SYS_REFCURSOR with oracledb. I try to recognize how I can do the same thing in typeorm. If this is not possible could you please show me how I can use for this one query oracledb instead of typeorm? (When I try to disconnect my application freeze :( )

**Comment by pleerock** [comment]
there is a `query` method that you can use execute raw sql queries

**Comment by konraddysput** [comment]
@pleerock let me show you sample procedure definition:

```sql
PROCEDURE sample_procedure (
       attrNumber    IN  ATTRIBUTE_NUMBER.STORE_NO%TYPE,
                      p_recordset_1 OUT SYS_REFCURSOR,
                      p_recordset_2 OUT SYS_REFCURSOR) 
```

Could you please describe how I can construct query that allows me to retrieve data from SYS_REFCURSOR?

**Comment by pleerock** [comment]
you can use `getConnection().driver` to get access to [ underlying driver](https://github.com/typeorm/typeorm/blob/master/src/driver/oracle/OracleDriver.ts) where you can use underlying driver and execute your specific operations with it

**Comment by konraddysput** [comment]
@pleerock I cannot use `execute` method on `driver` instance (Check sample below: https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-144-ref-cursor-bind-parameters) 

Im sorry but I still don't know how I can get data from `SYS_REFCURSOR`. Could you please show me example?

**Comment by pleerock** [comment]
You have to go deeper, try and experiment, I provided you links that you can use to explore. Take a look how driver and its query runner method use execute method to execute queries.

**Comment by konraddysput** [comment]
@pleerock don't get me wrong. I spend a lot of time on it and I don't have more ideas how to solve this problem :( Im not that guy that want to ask everything without my own work.

**Comment by konraddysput** [comment]
@pleerock 
Hi again. Sorry again I lost so much time on checking available API. I even ask other developer in our department to check API again with me but they don't have any good news for me. Your advices doesn't help me. Could you please check it too? I think other users that integrate with oracledb will have the same problems. 

I hope you could fine a time and provide some answers.

**Comment by dpmallinger** [comment]
Hello,

I was able to use typeorm along with  oracledb.CURSOR.   The code looks like this:

my pl/sql method looks like:
`procedure foo (p_recordset out cursor_type, obo in integer, e in integer);`


	
my node code looks like:
`try {
			const queryRunner: typeorm.QueryRunner = conn.createQueryRunner();

			const result: any = await queryRunner.query(query,
				[{ dir: oracledb.BIND_OUT, type: oracledb.CURSOR }, obo, entity]
			);

			// console.log(result);
			const rs: oracledb.ResultSet<any> = result[0];
			const response = [];
			let row;
			while ((row = await rs.getRow())) {
				response.push(row);
			}

			// always close the ResultSet
			await rs.close();
			await queryRunner.release();

			return response;
		}
		catch (error) {
			console.log(`error: ${error}`);
		}
`

**Comment by konraddysput** [comment]
Hey @dpmallinger If you were able to use SYS_REFCURSOR I think we can close this issue. In my cases we needed to change a way how we retrieve data. Thanks for example.
