### ISSUE TITLE
TypeError: One of the sources for assign has an enumerable key on the prototype chain

### ISSUE THREAD

**Issue by arolson101** [typeorm/typeorm#2502]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm running under react-native which is pedantic about Object.assign.  It's tripping in [```Object.assign(this, alias)```](https://github.com/typeorm/typeorm/blob/2758aec2a15745ec653bb107677bf33e7007afdb/src/query-builder/Alias.ts#L23) on ```target``` and ```metadata```.

I get this error:
> TypeError: One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.

**Comment by gabrielberlanda** [comment]
+ 1, same issue with the same version here.

**Comment by gabrielberlanda** [comment]
@pleerock I was thinking about this issue and I did the manual copy in the constructor of 'Alias', but, in my opinion, it will not solve the entire problem, because the main issue here is the react native Object.assign polyfill that throws an exception when u try to copy a object that have enumerable keys, and in typeORM we have many Object.assign's with another classes that have 'enumerable keys' too. If u want I can send the PR to fix the Alias object assign, but the main issue will still opened :/

**Comment by Snare92** [comment]
i have the same error when i try to save an entity, are there any other work arounds or solutions for this issue ??
failing at node_modules/typeorm/browser/persistence/Subject.js:67:56
in my case

**Comment by anicolaides** [comment]
I have been experiencing the same issue with react-native@0.56 and typeorm@0.2.7.

**Comment by jerolimov** [comment]
I had the same issue in my react-native project and could fix it by adding the [babel polyfill](https://babeljs.io/docs/en/babel-polyfill).

1. Add it as dependency (it is a runtime dependency, so you should not add it as devDependency)
    * with npm (`npm install --save @babel/polyfill`)
    * or yarn (`yarn add @babel/polyfill`)
2. Load the polyfills by loading it before your app-code / typeorm was loaded. For example, add this import to the top of your `index.js`:
    * `import '@babel/polyfill'`

**Comment by Noukkis** [comment]
> I had the same issue in my react-native project and could fix it by adding the [babel polyfill](https://babeljs.io/docs/en/babel-polyfill).
> 
>     1. Add it as dependency (it is a runtime dependency, so you should not add it as devDependency)
>        
>        * with npm (`npm install --save @babel/polyfill`)
>        * or yarn (`yarn add @babel/polyfill`)
> 
>     2. Load the polyfills by loading it before your app-code / typeorm was loaded. For example, add this import to the top of your `index.js`:
>        
>        * `import '@babel/polyfill'`

Seems to work but now every query takes 3 seconds to proceed
