### ISSUE TITLE
Tag 0.2.7 is not pushed to public

### ISSUE THREAD

**Issue by davidmpaz** [typeorm/typeorm#2504]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

Please could you push the `0.2.7` version tag to public. On [npm](https://www.npmjs.com/package/typeorm) i can see it is released already but can not find it here on git repo.

thanks,
David

**Comment by Kononnable** [comment]
Took long enough, but finally fixed.
