### ISSUE TITLE
Redis cache is not setting expire

### ISSUE THREAD

**Issue by kikar** [typeorm/typeorm#2505]
**Issue type:**

[X] bug report

**Database system/driver:**

[X] `mysql` / `mariadb`

**TypeORM version:**

[X] `latest`

**Steps to reproduce or a small repository showing the problem:**

Configured my db with:
```json
{
	"type": "redis",
    "duration": 5000,
    "options": {
		"host": "localhost",
		"port": 6379,
		"prefix": "dev-"
    }
}
```

And I'm using `selectQueryBuilder` with `.cache('some-key', 5000)`
The cache and the expiration seem to work correctly, but the Redis key has no expiry set.
Is this intended?

**Comment by kikar** [comment]
I opened a pull request to enable this: https://github.com/typeorm/typeorm/pull/2507

**Comment by pleerock** [comment]
Thanks going to release it in a next version

**Comment by kikar** [comment]
Thanks @pleerock.
Any ETA on the next version? Is it gonna be 0.2.8?
