### ISSUE TITLE
Typeorm min version for production environments?

### ISSUE THREAD

**Issue by ValiDraganescu** [typeorm/typeorm#2506]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I am using typeorm with AWS Lambda and I noticed that typeorm is rather large and pushes our code to the 50MB Lambda limit. I'd like to know which parts of the typeorm lib are not used at runtime. Like: is "browser" needed at runtime? Or do I need all drivers in the drivers folder? Is it enough to just keep what is inside mysql, and js files on the same level?

It would be nice to have a documentation that describes what part of the library is used at runtime or dev time. (I guess I can safely remove things that are related to the cli?)

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by ValiDraganescu** [comment]
I tried to remove all the drivers but mysql because that is the only one I need, but I cannot do that because the rest of the drivers are user through different code classes.

Maybe it would be good to have a plug and play architecture for the drivers, I don't see why I need to add the Oracle and MSSQL drivers when I don't need them. The orm should not crash without them.

**Comment by pleerock** [comment]
TypeORM doesn't come with oracle mssql and other drivers. There are some "driver" files but they are taking killobytes. I guess your problem is in node_modules, maybe typeorm uses some dependency that is heavy (it has its own dependency, etc.). On your local machine installation check what are the most "heavy" packages and what package bring them into your node_modules.
