### ISSUE TITLE
[Req] Example projects showing best practices?

### ISSUE THREAD

**Issue by estaub** [typeorm/typeorm#251]
My immediate need is to extend or wrap a repository with some queries.  I noted issue https://github.com/typeorm/typeorm-typedi-extensions/issues/1 . 

More generally, I'm looking for good examples of using typeorm in real projects that show best practices in integration and maybe testing.  I looked on NPM for projects using it; there isn't much (yet!).

**Comment by pleerock** [comment]
If you want to extend a repositories there are [custom repositories](https://github.com/typeorm/typeorm/tree/master/sample/sample33-custom-repository) support now.

> show best practices

yes that would be great if we create a separate repository with more complete example and best practices how to use typeorm

**Comment by estaub** [comment]
Thanks for the custom repo tip.  Re showcases, I was more thinking about pointing at _other_ folks' usage.  There's only so much you can do!  This is a great project, I'm porting from Sequelize and the code shrinkage is pretty startling.

**Comment by pleerock** [comment]
I think I can close this issue. Example repositories with more complex structures must be a community initiative and goes out of this repository scope.
