### ISSUE TITLE
Can generate the migration file having already the Entity

### ISSUE THREAD

**Issue by avedisdeclabs** [typeorm/typeorm#2511]
Y have a entity User with the necessary properties and the ormconfig.json as following : 

{
   "type": "postgres",
   "host": "localhost",
   "port": 5432,
   "username": "postgres",
   "password": ".....",
   "database": ".....",
   "synchronize": true,
   "logging": false,
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}

When I want to run the following script 

typeorm migration:generate -n UserEntity

to generate my first migration it appears the followinf error: 

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Function.PlatformTools.load 

I have red all docs and issues and I didnt find the posible anser for it yet.

**Comment by pleerock** [comment]
You have this error when you `generate` or when you `run`? I guess when you `run`. If so, then you need to run migrations against `js` files, or run `typeorm` using `ts-node`
