### ISSUE TITLE
moving from sequelize to typeorm questions regarding association, eager loading and queering associations

### ISSUE THREAD

**Issue by rares-lupascu** [typeorm/typeorm#2520]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi everyone,

I am thinking to switch from sequelize to typeorm but i have a pre-buy :)) question:

the scenario is this:
- i have users, teams and trainings tables
- i have 2 pivot tables for training_attending_playes and training_absent_players
- one user has many teams
- one team has many trainings

what i am able to do right now in sequelize is:
- to have on each training an association that will eager load all absent and attending players
```js
Training.belongsToMany(models.user, { as: 'presentPlayers', through: 'training_present_players', sourceKey: 'id', foreignKey: 'training_id', otherKey: 'user_id' });
Training.belongsToMany(models.user, { as: 'absentPlayers', through: 'training_absent_players', sourceKey: 'id', foreignKey: 'training_id', otherKey: 'user_id'  });
```

- when fetching the profile for the current user i can check if he is already attending or absent without any extra query ... so i am actually queering the association:
```js
await profile.trainings[i].hasPresentPlayers(user)
await profile.trainings[i].hasAbsentPlayers(user)
```

so bottom lime ... are these 2 easily doable in typeorm? :)

thanks

**Comment by Kononnable** [comment]
Did you resolve your issue?

**Comment by Kononnable** [comment]
Closing as no response from the author.
