### ISSUE TITLE
Can I configure the generated migrations files to use 2 spaces or tabs?

### ISSUE THREAD

**Issue by dkimot** [typeorm/typeorm#2521]
**Issue type:**

[x ] question
[x? ] feature request

**Database system/driver:**

[x ] `postgres`

**TypeORM version:**

[x] `0.2.7` (or put your version here)

When I generate migration files they have four spaces, is there a way to configure that, or can I create a pull request that checks the ormconfig.json for that setting?

Love this project and happy to help.

**Comment by Kononnable** [comment]
No, it's not possible. But you could run `prettier` or similar tool on generated migrations.
