### ISSUE TITLE
EntityManager.preload returns undefined

### ISSUE THREAD

**Issue by errorx666** [typeorm/typeorm#2522]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
connection.manager.transaction( async manager => {
	const gameEntity = await manager.preload( GameEntity, {
		id: game.gameId,
		ruleSet: game.rules.ruleSet
	} );
	console.log( gameEntity ); // undefined
} );
```
I'm expecting `gameEntity` to be an instance of `GameEntity`, even if no matching records exist.  Instead, however, it is `undefined`.

**Comment by itsthatguy** [comment]
+1

**Comment by yuks** [comment]
> Note that given entity-like object must have an entity id / primary key to find entity by.
> Returns undefined if entity with given id was not found.

https://github.com/typeorm/typeorm/blob/0419d7713d5080dcf1a25ed549022ddcbf82411c/src/repository/Repository.ts#L115

**Comment by errorx666** [comment]
I don't use this library anymore so I'm closing this issue.

**Comment by avin** [comment]
Check that id has **Number** type.
