### ISSUE TITLE
transient properties 

### ISSUE THREAD

**Issue by xmlking** [typeorm/typeorm#2523]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How to make a property transient and not to persist. e.g.,  I will be setting `isAdmin` on user after login success and use it else ware.But I don't want to persist this property to database. 
is there a convention to do this? I understand I can do `delete user.isAdmin` before save or update.

```ts
@Entity()
export class User {
  @ApiModelPropertyOptional()
  @ObjectIdColumn() id: ObjectID;

  @ApiModelProperty({ type: String })
  @IsString() @IsNotEmpty()
  @Index() @Column() firstName: string;

  @ApiModelProperty({ type: String })
  @IsString() @IsNotEmpty()
  @Index() @Column() lastName: string;

  @ApiModelProperty({ type: String, minLength: 10, maxLength: 100 })
  @IsEmail() @IsNotEmpty()
  @Index({ unique: true }) @Column() email: string;

  @ApiModelProperty({ type: String, minLength: 8, maxLength: 20 })
  @IsAscii() @IsNotEmpty() @MinLength(8) @MaxLength(20)
  @Index({ unique: true }) @Column() userId: string;

  // transient property
  isAdmin: boolean;

  @CreateDateColumn()
  createdAt?: Date;

  @UpdateDateColumn()
  updatedAt?: Date;

  @VersionColumn()
  version?: number;
}
```

**Comment by rickdana** [comment]
Yes was also looking for this feature ! so +1 for the Feature request

**Comment by Kononnable** [comment]
Could you check if setting both `readonly:true, select:false` does the job way you want?
However I'm not sure if merging database object with state of the running application is a correct approach and I would advice against it.

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.

**Comment by xmlking** [comment]
@Kononnable I tried your suggestion but didn’t work

**Comment by vlapo** [comment]
Properties without`@Column` should not to be persisted in DB. Are you sure your entity definition will create column in DB?

**Comment by darbio** [comment]
I have the same issue when persisting to mongodb using the experimental mongo client. The `events` property gets persisted.

```
import { Entity, ObjectID, ObjectIdColumn, Column, ColumnOptions } from 'typeorm';
import { IEvent } from 'src/contexts/base/event';

@Entity()
export abstract class BaseEntity {
  @ObjectIdColumn()
  public Id: ObjectID;

  private events: any[] = new Array();
  public get UncommittedEvents(): any[] {
    return new Array(this.events);
  }

  public AddEvent(event: IEvent) {
    this.events.push(event);
  }
}
```

**Comment by tanish7199** [comment]
Found a way to handle this.

We can leverage Virtual Column here. (ref: [Virtual Column](https://orkhan.gitbook.io/typeorm/docs/decorator-reference#virtualcolumn) )

The following could be an example:

```
  @VirtualColumn({
    query: () => `SELECT 1`,
    transformer: new ExcludeVirtualColumnTransformer(),
  })
  columnToExclude: string;
```

With the ExcludeVirtualColumnTransformer which looks like:

```
import { ValueTransformer } from "typeorm";

export class ExcludeVirtualColumnTransformer implements ValueTransformer {
  to(value: any): any {
    if (value) value = 1;
    return value;
  }

  from(value: any): any {}
}
```
