### ISSUE TITLE
All columns in the table are not returned by query with relations options in find method of Repository

### ISSUE THREAD

**Issue by JeongJun-Lee** [typeorm/typeorm#2527]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The code is like this.
```
let productsRepository = getRepository('Products') as Repository<Products>;
    return await productsRepository.find({
      relations: ['productDetails', 'Manufacturers_id', 'productImages'],
      where: { 
        id: id,
        isInactive: null 
      }
    });
```

By log at console, really all columns are required in the query with 3 left join like below. 
```
query: SELECT "Products"."id" AS "Products_id", "Products"."barcode" AS "Products_barcode",
 "Products"."name" AS "Products_name", "Products"."isInactive" AS "Products_isInactive", "Products"."Categories_id" AS "Products_Categories_id", "Products"."Manufacturers_id" AS 
"Products_Manufacturers_id", "Products_productDetails"."id" AS "Products_productDetails_id", 
"Products_productDetails"."expirationDate" AS "Products_productDetails_expirationDate", 
"Products_productDetails"."buyPrice" AS "Products_productDetails_buyPrice", 
"Products_productDetails"."currency" AS "Products_productDetails_currency", 
"Products_productDetails"."sellPrice" AS "Products_productDetails_sellPrice", 
"Products_productDetails"."description" AS "Products_productDetails_description", 
"Products_productDetails"."amount" AS "Products_productDetails_amount", 
"Products_productDetails"."alertAmount" AS "Products_productDetails_alertAmount", 
"Products_productDetails"."isInactive" AS "Products_productDetails_isInactive", 
"Products_productDetails"."location" AS "Products_productDetails_location", 
"Products_productDetails"."Products_id" AS "Products_productDetails_Products_id", 
"Products_productDetails"."Units_id" AS "Products_productDetails_Units_id", 
"Products_productDetails"."Suppliers_id" AS "Products_productDetails_Suppliers_id",
"Products_Manufacturers_id"."id" AS "Products_Manufacturers_id_id", 
"Products_Manufacturers_id"."name" AS "Products_Manufacturers_id_name", 
"Products_Manufacturers_id"."isInactive" AS "Products_Manufacturers_id_isInactive", 
"Products_productImages"."id" AS "Products_productImages_id", 
"Products_productImages"."image" AS "Products_productImages_image", 
"Products_productImages"."Products_id" AS "Products_productImages_Products_id" FROM 
"Products" "Products" LEFT JOIN "ProductDetails" "Products_productDetails" ON 
"Products_productDetails"."Products_id"="Products"."id"  LEFT JOIN "Manufacturers" 
"Products_Manufacturers_id" ON "Products_Manufacturers_id"."id"="Products"."Manufacturers_id"  LEFT JOIN "ProductImages" "Products_productImages" ON 
"Products_productImages"."Products_id"="Products"."id" WHERE "Products"."id" = ? AND 
"Products"."isInactive" IS NULL -- PARAMETERS: [1]
```

But the returned result doesn't include **Units_id** and **Suppiers_id** in the ProductDetails table even the columns are required in real SQL statement. Is it normal situation? For your information, the ProductDetails table also has own each relation with both Units and Suppliers tables.

My questions are ...
1. How can I get **Units_id** and **Suppiers_id** in the returned result?
2. The best is to get not only ids of both **Units_id** and **Suppiers_id** but returned result with the real values of the ids by another independent relations among ProductDetails, Units and Suppliers tables. 
In my opinion,  at first, the query result of relations among ProductDetails, Units and Suppliers tables by new Repository for ProductDetails should be existed and then have to make a left-join again with the result by Products Repository. Is there any best example for this?

![image](https://user-images.githubusercontent.com/11474775/42744135-7e886e66-88e3-11e8-8b45-8fee99979424.png)

**Comment by JeongJun-Lee** [comment]
If I add @ Column decorator with the relation decorator like this, the foreign key value will be returned with being included. Is this hack correct?

```
    @Column("int")
    @ManyToOne(type=>Units, Units_id=>Units_id.productDetails)
    @JoinColumn({ name:'Units_id'})
    Units_id:Units;
    
    @Column("int")
    @ManyToOne(type=>Suppliers, Suppliers_id=>Suppliers_id.productDetails)
    @JoinColumn({ name:'Suppliers_id'})
    Suppliers_id:Suppliers;
```

**Comment by Kononnable** [comment]
Did you resolve your issue?

**Comment by Kononnable** [comment]
Closing as no response from the author.
