### ISSUE TITLE
Any news regarding @RelationId?

### ISSUE THREAD

**Issue by royibernthal** [typeorm/typeorm#253]
Was it forgotten or is it still in development?

**Comment by pleerock** [comment]
its just not in priority. There bunch of other issues and new more important features that needs to be finish first. I wont expect RelationId in the near future. But I'll let you know once its finished.

**Comment by royibernthal** [comment]
That's a shame, I've been waiting for that one. Okay thanks.

**Comment by pleerock** [comment]
If shame for those, who are using this tool for free and don't want to contribute, while others spend their time and money to build it, then yes, I agree.
