### ISSUE TITLE
[OracleDb] Invalid count query

### ISSUE THREAD

**Issue by konraddysput** [typeorm/typeorm#2535]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello,

I try to get number of queries from my select. To get this I use count method available on repository object as below:
```javascript
const model = await this.customerRepository.count(query);
```
Query object contain:
```json
{
      "x":2,
      "y":9977,
      "z":100
}
```

When I executed code following sql was generated:
```sql
SELECT COUNT(DISTINCT(CONCAT("cust"."x", "cust"."y", "cust"."z"))) as "cnt" FROM "store"."CUSTOMER" "cust" WHERE "cust"."x" = :x AND "cust"."y" = :y AND "cust"."z" = :z
```
and then I receive driver error with information: `00909. 00000 -  "invalid number of arguments"`

Thanks.

**Comment by pleerock** [comment]
Provide entity code as well. PR with a failing test is welcomed.

**Comment by konraddysput** [comment]
@pleerock 
Today we analyse what is wrong in typeorm source code. Our entity contains 3 primary keys:

```

    @PrimaryColumn({ name: 'X'})
    public x: number;

    @PrimaryColumn({ name: 'Y'})
    public y: string;

    @PrimaryColumn({ name: 'Z'})
    public z: number;
```
and our search query have 3 parameters: 

```json
{
      "x":2,
      "y":9977,
      "z":100
}
```
We analyse file below:
https://github.com/typeorm/typeorm/blob/eece0c33fbd54c32f6da76a2692e6bf1b4b444a1/src/query-builder/SelectQueryBuilder.ts

1. From line 1705: We see invalid sql creation:
 `countSql = 'COUNT(DISTINCT(CONCAT(' + metadata.primaryColumns.map((primaryColumn, index) => ...`
2. This code was executed because you use this condition:
` if (metadata.hasMultiplePrimaryKeys) {` 
which is correct, but concat in oracledb accept only 2 parameters.

**Comment by pleerock** [comment]
Oh.. looks like we need to replace CONCAT with `||`. Feel free to contribute!

**Comment by imnotjames** [comment]
pretty sure this is fixed in `master` now
