### ISSUE TITLE
Combining inner join and left join

### ISSUE THREAD

**Issue by nikolay-rogovoy** [typeorm/typeorm#2541]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How to use the QueryBuilder to get the following query:

```
select
*
from a
  left join (
    select * 
    from b
        inner join c on b.id_b = c.id_b
) bc on a.id_a = bc.id_a

```
Ie, records in c should not cut records in a
but must shorten entries in b
Thanks!

**Comment by pleerock** [comment]
what did you try?

**Comment by nikolay-rogovoy** [comment]
so:
1) a.cs
```
import {Column, Entity, OneToMany, PrimaryGeneratedColumn} from "typeorm";
import {B} from "./b";

/***/
@Entity()
export class A {

    /***/
    @PrimaryGeneratedColumn()
    id_a: number;

    /***/
    @Column({nullable: true})
    name: string;

    /***/
    @OneToMany(type => B, b => b.a)
    bs: B[];
}

```
2) b.cs

import {Column, Entity, JoinColumn, ManyToOne, OneToMany, PrimaryGeneratedColumn} from "typeorm";
import {A} from "./a";
import {C} from "./c";

```
/***/
@Entity()
export class B {

    /***/
    @PrimaryGeneratedColumn()
    id_b: number;

    /***/
    @Column({nullable: true})
    name: string;

    /***/
    @ManyToOne(type => A, a => a.bs, {
        nullable: true,
        onDelete: 'CASCADE'
    })
    @JoinColumn({ name: 'id_a' })
    a: A;

    /***/
    @OneToMany(type => C, c => c.b)
    cs: C[];
}
```
3) c.cs

```
import {Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn} from "typeorm";
import {B} from "./b";

/***/
@Entity()
export class C {

    /***/
    @PrimaryGeneratedColumn()
    id_c: number;

    /***/
    @Column({nullable: true})
    name: string;

    /***/
    @ManyToOne(type => B, b => b.cs, {
        nullable: true,
        onDelete: 'CASCADE'
    })
    @JoinColumn({ name: 'id_b' })
    b: B;

}

```
4) query:

```
manager.createQueryBuilder()
            .select('a')
            .from(A, 'a')
            .leftJoinAndSelect((subQuery) => {
                return subQuery
                    .select('b')
                    .from(B, 'b')
                    .innerJoinAndSelect('b.cs', 'c')
            }, 'b', 'a.id_a = b.b_id_a')
            .getMany();

```
5) result:
```
[
        {
            "id_a": 1,
            "name": "a1"
        },
        {
            "id_a": 2,
            "name": "a2"
        }
]
```
... without b :)

IMHO: I do not see a way to solve my problem.
Thanks! :)

**Comment by nikolay-rogovoy** [comment]
Is no one worried about this problem? This is a typical task of working with sets.

**Comment by pleerock** [comment]
its without `b` because there is no place in your **model** where orm could use to map your data into. You need to use `getRawMany` in your case and work with raw data.
