### ISSUE TITLE
Typescript can't see id property of @PrimaryGeneratedColumn('uuid') in object returned from save

### ISSUE THREAD

**Issue by Lotafak** [typeorm/typeorm#2543]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Given code below

Group.ts file
```
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class Group {

  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('text')
  name: string;
}
```

group.controller.ts
```
// function definition and parameter doesn't really matter
requestHandler(name) => {
    const group = await getRepository(Group).save({ name });
    console.log(`/group/${group.id}`);
    return group;
  }
```

Typescript error `Property 'id' does not exist on type '{ name: string; }'.` appears when trying to access `group.id`. It does work when used, although the typescript error is not what I expected to see here.

**Comment by marcorinck** [comment]
{name} is just an object of type {name: string}, but not an instance of class Group, so TS correctly warns you that id does not exist on this type.

**Comment by Lotafak** [comment]
The thing is I'm not passing id, as it's auto-generated. So I can't pass the object of type Group to `save` function. Also, there's full-fledged Group object returned from `save` function, so there is no error in the runtime, only annoying Typescript errors

**Comment by marcorinck** [comment]
Yes, because thats the whole point of typescript, a compiler with a type system that compiles to JS. At runtime most of the type system is gone and JS doesnt know anything about your types.

You have to call save with an instance of Group (or a compatible type) to get rid of the warning/error. In this instance id is null/undefined and will be generated by typeorm. Thats not a bug but how typeorm and typescript work!

**Comment by Lotafak** [comment]
Yes, I understand those concepts.
What I don't understand, is why `save` method by definition doesn't have a return type of an object, that we're working on. To make myself more clear - I initialised a `Group` repository, implicitly saying, that I am working with `Group` objects.
Return type and something that is passed as an argument to the method can be quite different things.
I if understand you correctly - TypeORM, by design, wants me to specify each field that is created automatically (or similar cases) that I want back, when passing the object? 

Now - from official documentation

```
let photo = new Photo();
    photo.name = "Me and Bears";
    photo.description = "I am near polar bears";
    photo.filename = "photo-with-bears.jpg";
    photo.views = 1;
    photo.isPublished = true;

    return connection.manager
            .save(photo)
            .then(photo => {
                console.log("Photo has been saved. Photo id is", photo.id);
            });
```
I can't see any `id` field specified in `photo` object that is being saved, yet we use the `id` later. That will also produce a TS error.

**Comment by marcorinck** [comment]
That is really not a bug but a discussion how to use typescript. Stackoverflow would be the better place to discuss something like this. 

The code you copied from the typeorm documentation is using a "Photo" class. The class definition specifies that all Photo instances have an "id" property. The type "Photo" defines the id property and all objects which have this type can access this property. The property can be null/undefined of course which is the case before you save the photo in the database. save() will set it during persisting and the id can be accessed after. 

This is basic OOP and typescript usage and has nothing specifically to do with typeorm. 

Your original code also defined a type (class) with an id property: Group. But your call to save didn't use an object of this type but an inline object with the TYPE: "{name: string}". This type doesn't have an id property and therefore you can't use "id" on the object that is returned by save.

**Comment by Lotafak** [comment]
Ok, now I see where the thinking flaw from my side is.
Still, I'm not sure if that's the best way to handle it, but at least everything's clear now.
Thanks for you input @marcorinck .
