### ISSUE TITLE
repository.save() returns only the updated fields.

### ISSUE THREAD

**Issue by RedTailBullet** [typeorm/typeorm#2545]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When you use the `repository.save()` method to save an entity with an id (which means the entity exists in the database, thus it should be an update operation). The api only returns the updated fields rather than all fields. Is this a behavior by design?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
Yes, it is, it just returns you want it updated, e.g. you pass `{ id: x, name: y }` it will only return you `{ id: x, name: y, createdDate: "some updated values", someColumnWithDefault }`

**Comment by RedTailBullet** [comment]
@pleerock Thanks for replying. But Why is the behavior set like this? Is there any consideration? Or just this is how mysql's library work?

**Comment by Diluka** [comment]
@pleerock why it is just a pojo not entity? If I using ActiveRecord pattern to declare entity class, the `repository.save` returned object is not extending from `BaseEntity`!

**Comment by PerminovEugene** [comment]
This is still actual issue for me :(

**Comment by kennylbj** [comment]
What should I do if I want to update only partial fields but return the entire entity?

**Comment by imnotjames** [comment]
Select the entity again afterwards.  The existing output from this is not intended for use outside the internals of the framework and will change in the future.

**Comment by nlucero** [comment]
This won't work if you are using database replication :confused:
