### ISSUE TITLE
How to use SUM in queryBuilder

### ISSUE THREAD

**Issue by hengsoheak** [typeorm/typeorm#2546]
Sum a integer culumn by `SUM` method 
**TypeORM version:**: 0.1.3
 I test below query but not work

    Sum(employeeId, entityId, entityName) {
    return this.createQueryBuilder("LeaveBalance")
    .where("LeaveBalance.employeeId = :employeeId", { employeeId })
    .select("SUM(LeaveBalance.balance)", "sum")
    .getCount(); /// tested with getMany/getRawOne but not work
     }

**Comment by cjackson234** [comment]
Check this out.
[https://github.com/typeorm/typeorm/issues/673](https://github.com/typeorm/typeorm/issues/673)

**Comment by pleerock** [comment]
@hengsoheak did you resolve your issue?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
