### ISSUE TITLE
Discuss: Specify sequence name for generated column

### ISSUE THREAD

**Issue by petersondrew** [typeorm/typeorm#2547]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
We have schema controlled outside of TypeORM, with some sequences shared among multiple tables. I would like to discuss whether it is useful or makes sense for TypeORM to somehow support specifying the name of the sequence to be used for generated columns (particularly `PrimaryGeneratedColumn`). I'm happy to do the work myself, but wanted to discuss things first.

My current workaround is to user the `QueryBuilder` API to insert my entities as such:
```
createQueryBuilder()
      .insert()
      .values({
        id: () => "nextval('some_sequence')",
        ...entity,
      })
      .returning('id')
      .execute();
```
Then update my entity with the returned id. So I'm basically doing what the repository/entity manager insert methods do by hand in order to manually specify the sequence used by my primary key column.

Obviously I can make helper methods to make all this easier on myself, but if it seemed like it would be useful to the community and could fit well with TypeORM's API and current driver-specific functionality it would be worth me implementing as part of the `PrimaryGeneratedColumn` decorator.

I was envisioning something that looked like `PrimaryGeneratedColumn({ sequence: 'some_sequence' })` which would just be a no-op for other drivers, and doesn't seem too out of place given some of the other driver-specific column options that exist already.

**Comment by pleerock** [comment]
I know for some people this might be useful but having the fact of the issue complexity and implementation - don't think its something worth attention.
