### ISSUE TITLE
Do you have a plan to support memcached cache type?

### ISSUE THREAD

**Issue by yoshiaki-natsume** [typeorm/typeorm#2548]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Now typeorm cache support database and redis.
Do you have a plan to support memcached?

**Comment by pleerock** [comment]
No, we don't. Redis is good enough for the most use cases. But if you want memcached you can implement your own cache strategy easily, just do it!

**Comment by yoshiaki-natsume** [comment]
Okay, thank you!
