### ISSUE TITLE
Many-to-One replace relations

### ISSUE THREAD

**Issue by LogansUA** [typeorm/typeorm#2550]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello.

So I have 3 models, 2 of them connected using 1.

`Family -> FamilyForManufacturer <- Manufacturer`

<details><summary>family-for-manufacturer.ts</summary>

```ts
@Entity()
@Index(["familyId", "manufacturerId"], { unique: true })
export class FamilyForManufacturer {
    @PrimaryGeneratedColumn("uuid")
    public id: string;

    @Column({
        name: "family_id",
    })
    public familyId: string;

    @ManyToOne(type => Family, { onDelete: "CASCADE" })
    @JoinColumn({ name: "family_id" })
    public family: Family;

    @Column({
        name: "manufacturer_id",
    })
    public manufacturerId: string;

    @ManyToOne(type => Manufacturer, { onDelete: "CASCADE" })
    @JoinColumn({ name: "manufacturer_id" })
    public manufacturer: Manufacturer;

    @CreateDateColumn({
        name: "created_at",
    })
    public createdAt: Date;

    @UpdateDateColumn({
        name: "updated_at",
    })
    public updatedAt: Date;
}
```
</details>

<details><summary>manufacturer.ts</summary>

```ts
@Entity()
@Index(["code", "name"], { unique: true })
export class Manufacturer {
    @PrimaryGeneratedColumn("uuid")
    public id: string;

    @Column()
    @Index({ unique: true })
    public code: number;

    @Column()
    @Index({ unique: true })
    public name: string;

    @OneToMany(type => FamilyForManufacturer, familyForManufacturer => familyForManufacturer.manufacturer, { nullable: false })
    public familiesForManufacturers: Array<FamilyForManufacturer>;

    @CreateDateColumn({
        name: "created_at",
    })
    public createdAt: Date;

    @UpdateDateColumn({
        name: "updated_at",
    })
    public updatedAt: Date;
}
```
</details>

```ts
const connection = getConnection();

return connection.transaction(async manager => {
    const manufacturerRepository = manager.getCustomRepository(ManufacturerRepository);
    
    const manufacturer = await manufacturerRepository.findOne("%manufacturer_id%");
    
    const familyForManufacturer = new FamilyForManufacturer();
    
    /* fill family for manufacturer */
    
    manufacturer.familiesForManufacturers = [familyForManufacturer];

    await manufacturerRepository.save(manufacturer);
});
```

When the similar code is executing, the typeorm generates queries like this:
```sql
UPDATE "families_for_manufacturers" SET "manufacturer_id" = $2, "updated_at" = CURRENT_TIMESTAMP WHERE "id" = $1 -- PARAMETERS: ["%manufacturer_id%",null]
... 4 more
```

So after that I receive this error
```
error: null value in column "manufacturer_id" violates not-null constraint
```

Can I somehow force to replace this connections?

Now I make a workaround by deleting all relations for this `manufacturer` and then set new. But it's kinda messy.

Thank you.

**Comment by pleerock** [comment]
I didn't understand what exact issue you have. 

> UPDATE "families_for_manufacturers" SET "manufacturer_id" = $2, "updated_at" = CURRENT_TIMESTAMP WHERE "id" = $1 -- PARAMETERS: ["%manufacturer_id%",null]

this query means it tried to remove previously "bind" manufacturer to this families_for_manufacturers, and you have such error because db doesn't allow you to do so because manufacturer_id cannot be null. First question, do you understand this behaviour, and if yes, then is it expected by you? Depend on answer there can be different questions then.

**Comment by LogansUA** [comment]
I understand this behaviour, I just thought that there's way to automatically delete connections (without setting to null) when any field key is changing.
