### ISSUE TITLE
How to find entities with the same many-to-one relationship?

### ISSUE THREAD

**Issue by stanete** [typeorm/typeorm#2552]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Having a many-to-one one-to-many relationship between two entities... `Fuel` and `Station` for example:

```ts
@Entity()
export class Fuel {
  @PrimaryGeneratedColumn() id: number;

  @Column() price: string;

  @ManyToOne(type => Station, station => station.fuels)
  station: Station;
}
```
```ts
@Entity()
export class Station {
  @PrimaryColumn() id: string;

  @Column() name: string;

  @OneToMany(type => Fuel, fuel => fuel.station, { cascade: true })
  fuels: Array<Fuel>;
}
```

I want to **find all fuels with the same station id**.  

What I've tried and it doesn't work:

```ts
async findAll(stationId: string): Promise<Array<Fuel>> {
        return await this.repository.find({ where: { stationId: stationId } })
}
```

**Comment by cjackson234** [comment]
getRespository(Fuel).find({ station: { id: stationId } })

**Comment by stanete** [comment]
That is correct and works. Thank you.

**Comment by osnersanchez** [comment]
> find nested relationships

I'm trying to do something like that, but I do not get results, I do not know if it has anything to do with the scope of the relationship at the time of the consultation

`getRespository(Fuel).find({ station: { city: { id: cityId } } });`

**Comment by daniel-j-h** [comment]
I had the same issue and added `"logging": true"` to my config to check out the generated SQL.

Turns out the tables were prefixed with two underscores by typeorm, so I could hack a solution saying

```javascript
{ __station: { city: { id: cityId } } }
```

as a `where` property. Consider this a hack, though, and have a look at the generated SQL first.

**Comment by PauloMurakami** [comment]
Ola, para resolver isso eu utilizei algo assim 
findOne({ where: { city}, relations:["station"]  }

**Comment by PauloMurakami** [comment]
How, to solve it I am using
findOne('onde: ? cidade', relations: ["estação"] ?
