### ISSUE TITLE
Get result returned as an array of: header on first row, then all values

### ISSUE THREAD

**Issue by calebeaires** [typeorm/typeorm#2554]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[x ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ x ] `mysql` / `mariadb`
[x ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

All results with type orm cames on a json like array. Is there any option to get the result clear array like the above, header on first row, then results.

```javascript
[
    ['Year', 'Tesla', 'Nissan', 'Toyota', 'Honda', 'Mazda', 'Ford'],
    ['2017', 10, 11, 12, 13, 15, 16],
    ['2018', 10, 11, 12, 13, 15, 16],
    ['2019', 10, 11, 12, 13, 15, 16],
    ['2020', 10, 11, 12, 13, 15, 16],
    ['2021', 10, 11, 12, 13, 15, 16]
  ]
```

**Comment by cjackson234** [comment]
How is this more useful than the json result? I'm asking to try to understand your use case. 

You could easily create something like as a custom repository.

**Comment by calebeaires** [comment]
My project has a feature that migrate data from on server to another, so it transfer data from one database (oracle, mysql, mssql) to an mysql server.

If the primary data is a "rows as array" result, insted of textRows, it is more easy to do a bulk insert to the target.

```
      for (let index = 0; index < data.length; index++) {
        await this.db.query(
          `insert into ${this.databaseData.bucket}.${taskData.resultTable} (${columns.toString()}) values ?`,
          [[Object.values(data[index])]]
        );
      }
```

**Comment by cjackson234** [comment]
This absolutely sounds like you should use a custom repository to handle transforming the data like this. That way you can control things like boolean and date translations for each entity.

I don't think this is a documentation omission. I think json responses are by design.

Post your custom repository here though in case some else runs into this.

**Comment by pleerock** [comment]
@cjackson234 is right.

Its just one of hundred possible representations of the data structure. Transform data into structure you need using your local functions.
