### ISSUE TITLE
Customize highlight colors for AdvancedConsoleLogger

### ISSUE THREAD

**Issue by wcauchois** [typeorm/typeorm#2555]
**Issue type:**

[ ] question
[ ] bug report
[ x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Would it be possible to add a feature to customize the highlighting theme in AdvancedConsoleLogger?

It looks like the theme is defined in [PlatformTools L184](https://github.com/typeorm/typeorm/blob/6ed0f457c8373061858da02d96e7f144773c612e/src/platform/PlatformTools.ts#L184) but it is hard-coded in.

**Comment by pleerock** [comment]
there is no exposed api for this request. But you can override that prototype I believe

**Comment by vlapo** [comment]
Hi @wcauchois. I think you can write your own Logger - http://typeorm.io/#/logging/using-custom-logger

**Comment by pleerock** [comment]
Closing as there is no response from author.
