### ISSUE TITLE
MongoEntityManager always pass options as undefined to insertOne/insertMany

### ISSUE THREAD

**Issue by unlight** [typeorm/typeorm#2558]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
`MongoEntityManager.ts@insert()`
```ts
    async insert<Entity>(target: ObjectType<Entity>|EntitySchema<Entity>|string, entity: QueryPartialEntity<Entity>|QueryPartialEntity<Entity>[], options?: SaveOptions): Promise<InsertResult> {
        // todo: convert entity to its database name
        const result = new InsertResult();
        if (entity instanceof Array) {
            result.raw = await this.insertMany(target, entity);  // <--- passed options always as undefined
       // .....
        } else {
            result.raw = await this.insertOne(target, entity); // <--- passed options always as undefined
    }
```
So as `options` is always undefined, therefore [underlying MongoDb native](https://mongodb.github.io/node-mongodb-native/api-generated/mongoclient.html) will always use default options.

For my case option `forceServerObjectId` does not work.

see what options is using [insertOne](https://github.com/mongodb/node-mongodb-native/blob/master/lib/collection.js#L434-L451)
see what options is using [insertMany](https://github.com/mongodb/node-mongodb-native/blob/master/lib/collection.js#L480-L499)

**Comment by vlapo** [comment]
@rustamwin this issue is about mongodb options not about `SaveOptions`. 

@unlight this is because of inheritance from sql based `Repository.insert` method. Please use `insertMany` or `insertOne` instead of `insert`.

**Comment by pleerock** [comment]
`insert` method of mongo repository doesn't use SaveOptions. Simply said its not supported for mongo driver.
