### ISSUE TITLE
Can't reference to table with only OneToOne mapping

### ISSUE THREAD

**Issue by Shenno** [typeorm/typeorm#256]
In following situation:
1 entity with a @OneToOne(type => User, {primary: true}) and no other primary keys defined.
Now when I try to reference this entity from another entity, TypeORM can't resolve the member as a primary field. Following error occurs: TypeError: Cannot read property 'type' of undefined.
Code:

```typescript
@Entity()
export class Consultant {

  @OneToOne(type => User, {primary: true})
  @JoinColumn({name: "user_id"})
  user: User;

  @OneToMany(type => Proposition, prop => prop.consultant)
  propositions: Proposition[];
}
```

```typescript
@Entity()
export class Proposition {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(type => Consultant, consultant => consultant.propositions)
  @JoinColumn({name: "consultant_id"})
  consultant: Consultant;
```

Thanks :)

**Comment by Tobias4872** [comment]
Hi,

I don't have a solution to your immediate problem, but a proposition. If you want each consultant to be a user you can [table inheritance](https://typeorm.github.io/tables-and-columns.html#table-inheritance) for this. Just define user as an abstract entity ...
```
import { AbstractEntity, Column, PrimaryGeneratedColumn } from "typeorm";

@AbstractEntity()
export class User {

    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    public name: string;

}
```
... let consultant inherit from it ...
```
import { Entity, OneToMany } from "typeorm";

import { Proposition } from "./proposition.model";
import { User } from "./user.model";

@Entity()
export class Consultant extends User {

  @OneToMany(type => Proposition, prop => prop.consultant, {
      cascadeInsert: true,
  })
  public propositions: Proposition[];

}
```
... and create a consultant like this ...
```
    const repo = connection.getRepository(Consultant);
    const consultant = repo.create({
        name: "My First Consultant",
        propositions: [{
            subject: "My First Proposition",
        }, {
            subject: "My Second Proposition",
        }],
    });
    await repo.persist(consultant);
```
Please note, that this will _not_ create a "user" table, but rather a "consultant" table which will carry all the users properties as columns.

Let me know if this helps.

Tobias.

**Comment by Shenno** [comment]
Hi Tobias,

Thanks for your reply, unfortunatly we can't define User as AbstractEntity because we also have a persited Entity User in our model.

Shenno

**Comment by pleerock** [comment]
Sorry for the delayed answer but this issue to be resolved required lot of efforts and refactorings. I have completely refactored persistence system and fixed all problems with one-to-one relation I have seen. Please try a new version (npm i typeorm@next) and let me know if your issue is still not resolved.
