### ISSUE TITLE
Question: Insert record with foreign keys & retreive record with foreign key as string

### ISSUE THREAD

**Issue by davidjohnbell** [typeorm/typeorm#2560]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x` (^0.2.7)

**Steps to reproduce or a small repository showing the problem:**
```ts 
@Entity
class Chat extends BaseEntity {
    @PrimaryColumn()
    @Generated("uuid")
    id: string;

    @Column()
    message: string;

    @ManyToOne(type => User, user=> user.chats)
    user: User|string;

    static async getUserChats(userId) {
        // I want this to return id, message, and user (as an id)
        // but I only get id and message
        return await Chat.find({where:{user:userId}})
    }
}
@Entity()
class User extends BaseEntity {

    @PrimaryColumn()
    @Generated("uuid")
    id: string;

    @OneToMany(type => Chat, chat => chat.user)
    chats: Chat[];
}

```
Hi, and thankyou in advance.
In my database I have a user which has many chats. I want to grab all of the chats with the user id attached as a string rather than an object. I thought about using the relation syntax but that seems overboard when all I want is the id as a string - grabbing the related objects and mapping their ids back onto my desired output would be inefficient.

You might also have noticed that my schema accepts a User or (|) String. This is because I want to be able to insert a chat into the table in one shot without having to grab the user and set the chat property to the chat and then save. Is this acceptable or is it hacky? What is the proper way to do this? I am using the active record syntax and it seems inefficient to hit sql server twice to insert a single chat.

Some related sources that didn't pan out:
[Many to One docs ](https://github.com/typeorm/typeorm/blob/master/docs/many-to-one-one-to-many-relations.md)
[getting foreign key on instance](https://github.com/typeorm/typeorm/issues/586)

**Comment by shajeeck** [comment]
@davidjohnbell did you find the solution?

**Comment by davidjohnbell** [comment]
@shajeeck Kind of. We have since reconfigured everything to use the full object instead of the logical OR string. You should look into the annotation RelationId
