### ISSUE TITLE
Making Every Write and Update Query As Transaction

### ISSUE THREAD

**Issue by totalard** [typeorm/typeorm#2562]
**Issue type:**

[ ] question
[ ] bug report
[ X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ X] `@next`
[ ] `0.x.x` (or put your version here)

Dear,

I want to Make Every Save() as a transaction. Any Way to Do So. If any Error Occured, I need to Rollback it

**Comment by pleerock** [comment]
save is already wrapped into a transaction and if everything failed inside it - it will be reverted. If you want wrap several operations into transaction - you can use `transaction` method.
