### ISSUE TITLE
Proper disconnect/reconnect handling?

### ISSUE THREAD

**Issue by tonghae** [typeorm/typeorm#2563]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there any way to see a dicsonnect event? How to handle it in a proper way? I just don't know how to get things done in app after db goes down. Keep connection? Drop it and try to reconnect? Haven't seen any recipes here yet. Thanks for any help and advices.

**Comment by pleerock** [comment]
TypeORM doesn't expose API for listening to disconnection events. Probably you'll need to use some underlying API, e.g. `connection.driver.`. Dig into source code.

**Comment by tonghae** [comment]
Sorry but I still can't see connection.driver.on('error' / connection.driver.pool.on('error' / nothing suitable for centralized error catching in single place

**Comment by Kononnable** [comment]
Did you resolve your issue?

**Comment by vlapo** [comment]
As described here https://github.com/mysqljs/mysql#closing-all-the-connections-in-a-pool try:
```typescript
connection.driver.pool.end(function (err) {
  // all connections in the pool have ended
});
```
or:
```typescript
connection.driver.poolCluster.end(function (err) {
  // all connections in the pool have ended
});
```
to listen on end connections in underline mysql client.

**Comment by FlorianPfisterer** [comment]
Any news on this? I don't think the code to close all connections addresses the problem - the question (I think) is how to catch the error that the connection has died and then try to reconnect.

I'm facing the issue that once the database server (MySQL) is down (and I'm getting a "Pool does not exist" error), it does not recover, even if the database comes back up again. I need to manually restart the server to trigger a re-connect attempt. Is there any way to automatically do this?

**Comment by BFalls158** [comment]
> Any news on this? I don't think the code to close all connections addresses the problem - the question (I think) is how to catch the error that the connection has died and then try to reconnect.
> 
> I'm facing the issue that once the database server (MySQL) is down (and I'm getting a "Pool does not exist" error), it does not recover, even if the database comes back up again. I need to manually restart the server to trigger a re-connect attempt. Is there any way to automatically do this?

Any chance you came up with a solution to this? Currently facing the exact same problem.
