### ISSUE TITLE
Create single connection on every request

### ISSUE THREAD

**Issue by bertyhell** [typeorm/typeorm#2565]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm trying to get typeorm to work inside an express node app that runs inside aws lambda. Lambda functions essentially run the express service once to handle a single request and then close down.

How would it be best to create the db connection? If i use the "default" name, only one lambda will be able to connect to the database at a time. I tried generating a random number as the connection name, but then i get:

> Cannot create a new connection named "6810", because connection with such name already exist and it now has an active connection session.

I was trying to get the connection to close after every express request, and maybe i'm able to do that with some kind of final or error handler in express.
But it seems a bit heavy to setup a connection pool if i'm only going to use one connection for a few queries.
How can i create a single connection for every lambda request?

**Comment by pleerock** [comment]
> if i use the "default" name, only one lambda will be able to connect to the database at a time.

why? since lambda executing your functions in isolation how do they conflict with each other?

**Comment by undecidedapollo** [comment]
Lambda uses Docker to run your code and will reuse an existing container if the requests come in fast succession. If your logic to create a connection is not global, this error can occur. Another way around it is to close your connection after the execution is finished. 

Side Note: I do not think lambda reuses your container if there is a lambda execution timeout so you shouldn't have to worry about that edge case.
