### ISSUE TITLE
Unable to use async config

### ISSUE THREAD

**Issue by Nopik** [typeorm/typeorm#2566]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

It seems that currently it is impossible to have `ormconfig.js` (required by cli tools to operate) to return credentials asynchronously. In case when actual credentials are not in env, but rather need to be fetched from network (e.g. from Vault, AWS SSM, etc.), it is currently impossible to have `await/async` in `ormconfig.js` and return value for cli tools to operate.

It seems that even simple `await require( 'ormconfig' )` kind of code would solve the problem (and fall back to current behaior in case of sync config.

**Comment by pleerock** [comment]
just create a connection manually using `createConnection({ ... options ... })`, that will fit your requirements

**Comment by Nopik** [comment]
@pleerock I was talking about invoking `typeorm migrations:run` - it can't use async config.

**Comment by ajhodges** [comment]
:+1:

**Comment by valimero** [comment]
What's new there ?

**Comment by leonardfactory** [comment]
Actually, this is supported right now

**Comment by wdimmit** [comment]
@leonardfactory How should `ormconfig.js` be setup to allow for returning an async thunk?

**Comment by leonardfactory** [comment]
I'm using `ts-node`, but it should be doable with plain js. I'll take a guess:

```js
async function getConnectionOptions() {
  const config = await configLoader.load(); // Do whatever you need in order to load asynchronously the configuration
  return config;
}

module.exports = getConnectionOptions(); // So we are returning a Promise here
```

You can also do this with plain promises:

```js
function loadConfig() {
  return configLoader.load().then(config => {
    return {
       ...
    }
  });
}
module.exports = loadConfig();
```
