### ISSUE TITLE
DataTypeNotSupportedError when using "| null" type

### ISSUE THREAD

**Issue by Slessi** [typeorm/typeorm#2567]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `mysql`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

When I set one of my entity fields with `| null`, ex:

```ts
@Column({ name: "code", nullable: true })
public code?: string | null;
```

I am told

```
DataTypeNotSupportedError: Data type "Object" in "User.code" is not supported by "mysql" database.
    at new DataTypeNotSupportedError (/project/node_modules/typeorm/error/DataTypeNotSupportedError.js:16:28)
    at /project/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:73:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/project/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:70:36)
    at /project/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:41:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/project/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:41:25)
    at Connection.buildMetadatas (/project/node_modules/typeorm/connection/Connection.js:515:33)
    at Connection.<anonymous> (/project/node_modules/typeorm/connection/Connection.js:162:30)
    at step (/project/node_modules/typeorm/connection/Connection.js:32:23)
```

This is a problem for me as I use `strictNullChecks` (so `?` only allows undefined) and use the difference as:

- `null` === the field is null
- `undefined` === i dont know the value of this field

**Comment by pleerock** [comment]
You need provide a data type explicitly. By default typeorm reads typeorm from type definition, e.g. `: string`, and `string` is reflected into `String`. But `string|null` is reflected into `Object` and we cannot determine type. So, what you should do is to specify type explicitly:

```ts
@Column({ type: "string", name: "code", nullable: true })
public code?: string | null;
```

**Comment by Nift** [comment]
@pleerock it seems that this does not work with the postgres driver, as you are not allowed to specify the type 'string'. 

Here it does not work either to specify the type as 'text' which is a postgres type and stated in the `SimpleColumnType` type, it still converts the string to an object. 

Any suggestions as what to do @pleerock ?

**Comment by leomelzer** [comment]
@Nift We just had the same problem with the MSSQL driver and looked in the driver code. You may use `String` (as in, the Javascript type) and typeorm will fall back correctly on the most likely type for your DB: https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L523

Hope that helps.

**Comment by Nift** [comment]
@leomelzer Thanks for the response, however it seems that it does not solve the problem :( 

I will work on a fix whenever I have the time.

**Comment by leomelzer** [comment]
@Nift Alright, hope you find a solution :) BTW, we are on `0.3.0-alpha.21`.

**Comment by blyszcz** [comment]
@Nift I have the same problem, did you solve it?

**Comment by Nift** [comment]
@blyszcz sadly haven't had the time yet, I literally just search replace about all Objects in the generated js file and then run that. (Very cumbersome I know)

**Comment by mightyYaroslav** [comment]
@Nift I just had to cast the null to any with optional field type. Also a very cumbersome solution. @pleerock please look into it

**Comment by feimosi** [comment]
`"text"` type worked for me

```ts
@Column({ type: 'text', nullable: true })
content!: string | null;
```

**Comment by phil294** [comment]
`type: 'string'` only works with cockroachdb. You can find the correct type(s) for your database listed [here](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#column-types)
