### ISSUE TITLE
Add index to RelationOptions

### ISSUE THREAD

**Issue by jonathanrz** [typeorm/typeorm#2568]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

It would be nice to be able to define in a relation to automatically create an index for it. I think that the best place to put it would in the RelationOptions.

Today it is possible to get the desired result doing the following:

```
import {Entity, PrimaryGeneratedColumn, Column, ManyToOne, Index} from "typeorm";
import {User} from "./User";

@Entity()
export class Photo {
    
    @PrimaryGeneratedColumn()
    id: number;
    
    @ManyToOne(type => User, user => user.photos)
    user: User;

    @Index
    @RelationId((user: User) => user.photos)
    userId: number;
}
```

The idea was to be able to do the same with the following code:

```
import {Entity, PrimaryGeneratedColumn, Column, ManyToOne, Index} from "typeorm";
import {User} from "./User";

@Entity()
export class Photo {
    
    @PrimaryGeneratedColumn()
    id: number;
    
    @ManyToOne(type => User, user => user.photos, { index: true })
    user: User;
}
```

**Comment by pleerock** [comment]
indices have high cost, and should be used carefully, we can't decide for users if they should pay for it on each relation or not. They should decide it on their own.

**Comment by falahati** [comment]
@pleerock
He is asking for a simple way for the user to add an index. He is NOT asking for automatic indexing of foreign keys.

This issue should be open.

**Comment by nebkat** [comment]
#7119 adds this.

**Comment by leonidasv** [comment]
@jonathanrz 
> Today it is possible to get the desired result doing the following:
>```ts
>import {Entity, PrimaryGeneratedColumn, Column, ManyToOne, Index} from "typeorm";
>import {User} from "./User";
>
>@Entity()
>export class Photo {
>    
>    @PrimaryGeneratedColumn()
>    id: number;
>    
>    @ManyToOne(type => User, user => user.photos)
>    user: User;
>
>    @Index
>    @RelationId((user: User) => user.photos)
>    userId: number;
>}
>```

I think you mistyped and meant it to be:
```ts
    @Index
    @RelationId((photo: Photo) => photo.user)
    userId: number;
```

Since your example throws: `Error: Cannot find relation undefined. Wrong relation specified for @RelationId decorator.`. As the documentation shows, `@RelationId` receives the current class as parameter.

However, even after changing it to the example I posted above does not work to: `Error: Index contains column that is missing in the entity (Photo): userId`. 

Am I missing something? How can I get a ManyToOne relation to be indexed before #7119 is merged? I've tried adding a SQL query manually to the migration, but every time I run `migration:generate` now it tries to `DROP` my index.

**Comment by leonidasv** [comment]
For those who may be struggling with the same issue, I've managed to make it work by adding the `@Index()` decorator right to the relation and removing it from the `RelationId`:

```ts
   @Index()
   @ManyToOne(type => User, user => user.photos)
   user: User;

   @RelationId((photo: Photo) => photo.user)
   userId: number;
```

It generated the migration:
```ts
queryRunner.query(`CREATE INDEX "IDX_dddc92fd77a1b1682a8d6fb07d" ON "photo" ("userId")`)
```
(the hash after `IDX_` is illustrative)
