### ISSUE TITLE
RepositoryNotFoundError w/ serverless offline

### ISSUE THREAD

**Issue by kvarela** [typeorm/typeorm#2572]
**Issue type:**
[x] bug report

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. Use ormconfig.json, set entities to something like `"**/entities/*.{js,.ts}"`
2. Run `serverless offline start`
3. Try to get repo like: `this.repo = connection.getRepository<User>(User)`
4. I also tried like `this.repo = connection.getRepository<User>('User')`

Result:
RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "dev" connection?

I know my entities are set correctly in my ormconfig.json file b/c my database tables are all synced correctly, but I can't get a repo to do any work.

Please help!

Here's my ormconfig.json:
```
{
    "name": "dev",
    "type": "postgres",
    "host": "localhost",
    "port": 5432,
    "username": "postgres",
    "database": "postgres",
    "entities": [
        "**/entities/*.{js,.ts}"
    ],
    "synchronize": true,
    "logging": false
}
```

Here's what my Database class looks like:
```
export class Database {
    private connectionManager: ConnectionManager

    constructor() {
        Logger.info(`Database()`)
        this.connectionManager = getConnectionManager()
    }

    public async getConnection(): Promise<Connection> {
        Logger.info(`Database.getConnection()`)

        let connection: Connection

        try {
            connection = this.connectionManager.get(process.env.CONNECTION_NAME)
        }
        catch (e) {
            Logger.warn(`Database.getConnection()-error=${e}`)

            // read connection options from ormconfig file (or ENV variables)
            const connectionOptions = await getConnectionOptions(process.env.CONNECTION_NAME);
            Object.assign(connectionOptions, { namingStrategy: new SnakeNamingStrategy() });

            Logger.info(`Database.getConnection()-connectionOptions=${inspect(connectionOptions)}`)

            connection = await createConnection(connectionOptions)
        }

        return connection
    }
}
```

**Comment by adriankott** [comment]
I ran in the same issue 
1) Make sure your entities are pointing to the build folder js files "build/src/entity/**/*.js"
2) There seems to be a bug when trying to get an entity by class probably some conflict between reflection and serverless-ofline connection.getRepository("EntityName");

I'm guesing since you tried the second option the paths are not correct in your ormconfig

**Comment by kvarela** [comment]
Thank you for your response @adriankott. I made sure my entities prop is pointing the right place, but still can't get it to work:
![image](https://user-images.githubusercontent.com/2534096/43143003-9f737630-8f0e-11e8-88a9-d60c79ae135c.png)

I ended up getting it to work by explicitly calling out entities in code, but that's not the best way to do it:
```const connectionOptions: ConnectionOptions = await getConnectionOptions(process.env.CONNECTION_NAME);
            Object.assign(connectionOptions, {
                namingStrategy: new SnakeNamingStrategy(),
                entities: [Admin, Amenity, Hotel, HotelAmenity,
                    HotelBooking, HotelLocation, HotelRoom, HotelTag, HotelPhoto, Tag, User]
            });```

**Comment by kvarela** [comment]
Actually, interestingly, using `Object.assign()` and specifically calling out my entities works locally, but it doesn't appear to be working in Lambda.

**Comment by pleerock** [comment]
did you try what he suggested: 

> There seems to be a bug when trying to get an entity by class probably some conflict between reflection and serverless-ofline connection.getRepository("EntityName");

**Comment by kvarela** [comment]
I was able to get this working using the following:
```
const connectionOptions: ConnectionOptions = {
                name: `default`,
                type: `postgres`,
                port: 5432,
                synchronize: true,
                logging: true,
                host: process.env.DB_HOST,
                username: process.env.DB_USERNAME,
                database: process.env.DB_NAME,
                password: process.env.DB_PASSWORD,
                namingStrategy: new SnakeNamingStrategy(),
                entities: [
                    __dirname + "/entities/*.js"
                ]
            }

            connection = await createConnection(connectionOptions)
```

**Comment by ganesh9596** [comment]
@kvarela  can u plz send your full code..
i tried ur answer but i didnt get proper output

**Comment by kvarela** [comment]
@ganesh9596 I actually had to switch back to explicitly calling out the entities because I switched I had to minify my code (using Browserify) and after minification it no longer makes sense to have a directory structure.

But here's my current connectionOptions for reference:
```
export const connectionOptions: ConnectionOptions = {
    name: `default`,
    type: `postgres`,
    synchronize: true, // todo: remove for production, should be replaced with formal migrations once we're launched
    logging: false,
    replication: {
        master: {
            host: process.env.DB_HOST,
            username: process.env.DB_USERNAME,
            database: process.env.DB_NAME,
            password: process.env.DB_PASSWORD,
            port: 5432
        },
        slaves: [
            {
                host: process.env.DB_HOST_SLAVE,
                username: process.env.DB_USERNAME,
                database: process.env.DB_NAME,
                password: process.env.DB_PASSWORD,
                port: 5432
            }
        ]
    },
    namingStrategy: new SnakeNamingStrategy(),
    // This causes problems with minification since there's no longer a directory structure
    // entities: [__dirname + '/entities/*.*']
    entities: [
        Amenity,
        City,
        Hotel,
        HotelAmenity,
        HotelBooking,
        HotelPhoto,
        HotelPolicy,
        HotelRoom,
        HotelSupplyUpdate,
        HotelTag,
        Neighborhood,
        Policy,
        Tag,
        User
    ]
}
```

**Comment by ganesh9596** [comment]
thank so much

**Comment by warnerpinz** [comment]
Where can I get the class new SnakeNamingStrategy()?

**Comment by joaovpmamede** [comment]
@warnerpinz  https://www.npmjs.com/package/typeorm-naming-strategies
