### ISSUE TITLE
select option in mongodb

### ISSUE THREAD

**Issue by wujunyucg** [typeorm/typeorm#2573]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I saw there is `select` option  in `repository.find()` or `repository.findAndCount` functions .
```
/**   

     * Specifies what columns should be retrieved.  

     */   

    select?: (keyof Entity)[];
```

But it did not work. And in the code , it did not process this option.

```
const query = this.convertFindManyOptionsOrConditionsToMongodbQuery(optionsOrConditions);  

        const cursor = await this.createEntityCursor(entityClassOrName, query);  

        if (FindOptionsUtils.isFindManyOptions(optionsOrConditions)) {  

            if (optionsOrConditions.skip)  

                cursor.skip(optionsOrConditions.skip);  

            if (optionsOrConditions.take)  

                cursor.limit(optionsOrConditions.take);  

            if (optionsOrConditions.order)  

                cursor.sort(this.convertFindOptionsOrderToOrderCriteria(optionsOrConditions.order));  

        }  

        return cursor.toArray();```

**Comment by vlapo** [comment]
Already on roadmap https://github.com/typeorm/typeorm/issues/1929

**Comment by wujunyucg** [comment]
thanks
