### ISSUE TITLE
Is there a reason why listeners and subscribers would not work at all?

### ISSUE THREAD

**Issue by joebieb** [typeorm/typeorm#2577]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Using getRepository(Entity).save(data) or entityManager.save(Entity, data) will not fire the @AfterUpdate or @AfterInsert methods on the entity.

```
@AfterInsert()
@AfterUpdate()
someMethod() { 
 console.log("It worked!")
}
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
I guess its because your `req.body` is not instance of `ReportDetail`, and since its not instance of `ReportDetail` there is no method to call on `req.body`, e.g. you can't call `req.body.someMethod()`

**Comment by joebieb** [comment]
Thank you for the help. This code works and fires the @AfterUpdate method. There's probably a better way to map the req.body to the new ReportDetail object, but this works.

```
  public async save(req: Request, res: Response, next: NextFunction) {
    let _detail = new ReportDetail();
    for(var key in req.body) _detail[key]=req.body[key];
    let result = getRepository(ReportDetail)
                .save(_detail)
                .then(result => res.send(result))
                .catch(error => console.log(error));
  };
```
