### ISSUE TITLE
ActiveRecord model is returning empty results everytime

### ISSUE THREAD

**Issue by rangelfinal** [typeorm/typeorm#2578]
**Issue type:**
[X] bug report

**Database system/driver:**
[X] `postgres`

**TypeORM version:**
[X] `latest` (0.2.7)

**Problem**
ActiveRecord model is returning empty update results even when it's updating stuff in the database.

**Steps to reproduce or a small repository showing the problem:**
```
export default class OAuthAccessToken extends BaseEntity {
@Column() id: string;

@Column({ nullable: false })
  expires: Date;

public static async revoke(conditions: Partial<OAuthAccessToken>) {
    const now = new Date();
    return this.update({ ...conditions, expires: MoreThan(now) as DeepPartial<Date> }, { expires: now });
  }
}
```
```
const updateResult = await token.revoke({id: 'abc'}); // Token with id abc was updated in the database
console.log(updateResult); // UpdateResult { generatedMaps: [], raw: [] }
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
UpdateResult is somewhat system. What exactly do you expect `update` method to return?

**Comment by rangelfinal** [comment]
Any kind of indication that the update was successful.  
The full entities, their IDs or just a integer with the number of rows affected.  
Even a boolean would do, but a indication of the number of rows affected would be better.

**Comment by rangelfinal** [comment]
I will close this issue and follow the feature request, then.  
For future reference, the feature request is the issue #1308.
