### ISSUE TITLE
Relationship column names

### ISSUE THREAD

**Issue by WoLfulus** [typeorm/typeorm#258]
All our columns has a "id_" prefix for FKs. When dealing with relations, I ended up creating variables with id_ prefix too

Is there any way to set custom colum names for relations to avoid accessing those instances with a "id_" variable?

**Comment by pleerock** [comment]
Yeah you should be able to do so:

```typescript
@Table()
export class Post {
    @PrimaryGeneratedColumn()
    id: number;

    @OneToOne(type => Members, member=>member.post)
    @JoinColumn({ name: "member_id" })
    member: Members;

   // this is optional:
   // @Column({  type: "int", nullable: true })
   // memberId: number;

    @Column()
    comment:string;
}
```

**Comment by WoLfulus** [comment]
Thanks!

**Comment by petahbred** [comment]
How does one do this in vanilla javascript?

**Comment by netojose** [comment]
> Yeah you should be able to do so:
> 
> ```ts
> @Table()
> export class Post {
>     @PrimaryGeneratedColumn()
>     id: number;
> 
>     @OneToOne(type => Members, member=>member.post)
>     @JoinColumn({ name: "member_id" })
>     member: Members;
> 
>    // this is optional:
>    // @Column({  type: "int", nullable: true })
>    // memberId: number;
> 
>     @Column()
>     comment:string;
> }
> ```

@pleerock , thanks for the comment. I hate the typeorm documentation, has no search feature, and is very hard to find you are looking for

**Comment by itseramin** [comment]
How would one do the same thing with an enum? The migration generator thinks it's a new column and needs to be created.
