### ISSUE TITLE
How does TypeORM work with Express requests?

### ISSUE THREAD

**Issue by yang** [typeorm/typeorm#2581]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The examples for the Express app suggest that you should make a single call to createConnection() at the top of the app (which creates a connection pool).  Is this concurrency-safe?  This would require that TypeORM somehow know whether it needs to reuse an existing connection (for queries from the same request) or add a new connection (for a new request).  How exactly does it determine this?  I could not find this in the source.

I've also found previous mentions by @pleerock suggesting that just a single createConnection() is correct, e.g. https://github.com/typeorm/typeorm/issues/592.

I'm ultimately trying to figure out how to scope transactions to Express requests, using middleware (so that I'm not writing transaction wrappers on every request handler).  It's unclear to me whether the following is the right approach / how it interacts with the above magic:

```
app.use(async (req, res, next) => {
  getConnection().transaction(txMgr => {
    return new Promise(resolve => {
      req.txMgr = txMgr;
      req.on('end', () => resolve());
      next();
    });
  });
});
```

(The idea is that after this, request handlers can just access `req.txMgr` for the transactional EntityManager.)

Thanks.

**Comment by yang** [comment]
I think the answer is that the included examples are *not* transactional, unfortunately—it may be worth updating them to be transactional by default.

Also my snippet needs some tweaking:

```
app.use(async (req, res, next) => {
  getConnection().transaction(txMgr => {
    return new Promise(resolve => {
      req.txMgr = txMgr;
      res.on('finish', () => resolve());
      next();
    });
  });
});
```

**Comment by geersch** [comment]
@yang Your sample middleware code came in handy, but don't forget that you also need to reject the promise in case the request throws an error. Now you always resolve and thus COMMIT.
