### ISSUE TITLE
test failing

### ISSUE THREAD

**Issue by adrielcodeco** [typeorm/typeorm#2583]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

running the tests

Similar to #499
i'm running the tests but they're failing
![image](https://user-images.githubusercontent.com/2581560/43219257-32ce9d56-901d-11e8-8e04-53bcd57535cc.png)

commenting this test failed in :
![image](https://user-images.githubusercontent.com/2581560/43219706-697ecf1e-901e-11e8-87af-d8626bab8a95.png)

commenting this test all give ok

Anyone have any idea of the problem?

branch: master
node -v: v10.4.1
npm -v: 6.1.0
using nvm
os: ubuntu
editor: vscode
tz: utc-3
using docker-compose to dbs

**Comment by pleerock** [comment]
try to figure out! Tests seem to be passing on CI. Maybe its something environment-specific? At the end you can continue to do what you was trying to do, but left those tests commented and don't commit those changes.
