### ISSUE TITLE
Cannot read property 'joinColumns' of undefined

### ISSUE THREAD

**Issue by dariusmb** [typeorm/typeorm#2587]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
@Entity()
export class User {
 @PrimaryColumn()
 id: string;

 @Column({unique: true})
 username: string;

 @Column({unique: true})
 email: string;

 @OneToMany(type => Post, post => post.id)
 posts: Post[];
}

@Entity()
export class Post {

 @PrimaryGeneratedColumn()
 id: number;

 @ManyToOne(type => User, user => user.posts)
 @JoinColumn({name: 'user_id'})
 user: User;

 @OneToMany(type => Image, image => image.id)
 images: Image[];
}

@Entity()
export class Image {
 @PrimaryGeneratedColumn()
 id: number;

 @ManyToOne(type => Post, post => post.images)
 @JoinColumn({name : 'post_id'})
 post: Post;
}  
```
I have these 3 entites and I want to make a query to have all the posts from a user and for that post to get all the images. I am trying to do this using the following code:

`return await this.postRepository.createQueryBuilder("post")
  .innerJoinAndSelect("post.images", "image")
  .where("user_id = :userId", {userId: id})
  .getMany();`
And I get the following error:

 `"Cannot read property 'joinColumns' of undefined"`
I also tried this instead of the innerJoin from above:

 `.innerJoinAndSelect(Image, "image", "image.post_id = post.id")`
This way I don't get that error anymore, but as a result I get only the post and I don't get the images from it

**Comment by pleerock** [comment]
You have such errors because you setup relations wrong way. Relations are setup between objects, not between object and some property, e.g.

```ts
 @OneToMany(type => Image, image => image.id)
 images: Image[];
```

should be:

```ts

 @OneToMany(type => Image, image => image.post)
 images: Image[];
```

**Comment by premalatha-bv** [comment]
> You have such errors because you setup relations wrong way. Relations are setup between objects, not between object and some property, e.g.
> 
> ```ts
>  @OneToMany(type => Image, image => image.id)
>  images: Image[];
> ```
> 
> should be:
> 
> ```ts
>  @OneToMany(type => Image, image => image.post)
>  images: Image[];
> ```

@pleerock, 
Could you please help me to find the json syntax for entity schema to write this inverse relation for one to many relation.
Am unable to figure it out. It would be very helpful please.

**Comment by abolognino** [comment]
it would be nice to have a better error message
