### ISSUE TITLE
CreateDateColumn sets null instead of date

### ISSUE THREAD

**Issue by davran-sabiraliev** [typeorm/typeorm#2592]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
  @CreateDateColumn({ type: 'timestamp', name: 'created_at', nullable: false })
  createdAt: Date

  @UpdateDateColumn({ type: 'timestamp', name: 'updated_at' })
  updatedAt: Date
```

typeorm tries to set null instead of a current date

**Comment by pleerock** [comment]
Most probably you do something wrong. What method are you using to save this your object? Please provide a code reproduction example

**Comment by davran-siv** [comment]
I tried it in this way
```
    const userRepository = getManager().getRepository(UserModel);

    const entity = userRepository.create(domain)
    return userRepository.save(entity)
```

**Comment by davran-siv** [comment]
Everything saves except timestamp

**Comment by davran-sabiraliev** [comment]
@dcworldwide Could you please clarify what do you mean "has a default date in postgresql"?

**Comment by dcworldwide** [comment]
Check the table SQL in your database viewer, make sure the date columns have a default set to now()

**Comment by davran-sabiraliev** [comment]
Regarding createdAt I can do it, but I think updatedAt should contain null after the record was created and the date should be inserted only after record update

**Comment by filipjnc** [comment]
@davran-sabiraliev both `createdAt` and `updatedAt` are set by design to the current date at insertion. The difference is, `createdAt` will not get updated during following updates.

Have you checked database defaults? Have you solved the problem?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
