### ISSUE TITLE
When Ionic build with minifyjs option, the CircularRelationError will be emitted.

### ISSUE THREAD

**Issue by JeongJun-Lee** [typeorm/typeorm#2597]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When I try to build with --minifyjs, it emits circular relations error like this. The minifyjs option includes the mangling by uglifyjs. I think the TypeORM is not safe about this mangling process. But the mangling process to protect our source code from hacking in Ionic is very important. Ionic itself includes this mangling process in production build process with --prod option.

ERROR Error: Uncaught (in promise): CircularRelationsError: Circular relations detected: e -> t -> e. To resolve this issue you need to set nullable: false somewhere in this dependency structure.
CircularRelationsError: Circular relations detected: e -> t -> e. To resolve this issue you need to set nullable: false somewhere in this dependency structure.
at new t (vendor.js:1)
at e.validateDependencies (vendor.js:1)
at e.validateMany (vendor.js:1)
at e.buildMetadatas (vendor.js:1)
at e. (vendor.js:1)
at vendor.js:1
at Object.next (vendor.js:1)
at s (vendor.js:1)
at t.invoke (polyfills.js:3)
at Object.onInvoke (vendor.js:1)
at new t (vendor.js:1)
at e.validateDependencies (vendor.js:1)
at e.validateMany (vendor.js:1)
at e.buildMetadatas (vendor.js:1)
at e. (vendor.js:1)
at vendor.js:1
at Object.next (vendor.js:1)
at s (vendor.js:1)
at t.invoke (polyfills.js:3)
at Object.onInvoke (vendor.js:1)
at c (polyfills.js:3)
at polyfills.js:3
at polyfills.js:3
at t.invoke (polyfills.js:3)
at Object.onInvoke (vendor.js:1)
at t.invoke (polyfills.js:3)
at r.run (polyfills.js:3)
at polyfills.js:3
at t.invokeTask (polyfills.js:3)
at Object.onInvokeTask (vendor.js:1)

**Comment by pleerock** [comment]
> But the mangling process to protect our source code from hacking in Ionic is very important

again how mangling protects from hacking. Please avoid such statements to prevent users confusion.

TypeORM relys a lot on classes and mangling completely break it, so having it disabled is natural.

**Comment by JeongJun-Lee** [comment]
I apologize for making users confusion by my misunderstanding. You're right. Just mangling is not safe for hacking. If it's natural for TypeORM to prevent mangling, let's add this limitation on document at https://github.com/typeorm/ionic-example. then I'll close this issue.

**Comment by dauane** [comment]
I am facing exactly the same issue but on React-Native. Where you able to find a solution for it?

**Comment by alroux** [comment]
I am facing  the same issue but on Nativescript. Is threre a solution?
