### ISSUE TITLE
Support for Postgresql Schemas

### ISSUE THREAD

**Issue by AlvaDamian** [typeorm/typeorm#260]
Currently I have two schemas in my Postgresql database: **productos** and **usuarios**. Then in **productos** I have the table **item**.

My problem is, how to specify the schema for the table?.

Given the columns of table **item** in schema **productos**:

```sql
id serial primary key,
nomber VARCHAR(50)
```

When i fetch data from the table **item** in the schema **productos** I need the SQL to be something like this:

```sql
SELECT "productos"."item"."id" AS "item_id", "productos"."item"."nombre" AS "item_nombre" FROM "productos"."item";

--SELECT schema.table.column AS alias FROM schema.table
```

Can this be achieved?. I couldn't figured out how.

I've tried this and didn't work:

```javascript
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity("productos.item")
export class Item {

	@PrimaryGeneratedColumn()
	id:number;

	@Column("string")
	nombre:string;
}
```

**Comment by pleerock** [comment]
Currently schema is supported only on connection-level, so you can use only one specific schema. We probably can add specifying schema-per-entity however Im not sure what side effects it will have. @mingyang91 what do you think about it?

**Comment by AlvaDamian** [comment]
I was thinking that can be added in the Entity decorator and let the user override that configuration if it needs to use dynamic schema.

With dynamic schema I mean, when the dabatabase has an schema per user.

```javascript
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity("item", {"schema": "productos"})
export class Item {

	@PrimaryGeneratedColumn()
	id:number;

	@Column("string")
	nombre:string;
}
```

That code will override the default schema for **item** with **productos**.

The next code can be used to fetch data.

```javascript
let con:Connection;

/*...*/
/**
* This will fetch items using the default schema for the Entity Item.
*
* Expected result: SELECT "productos"."item"."id" AS "productos_item_id", "productos"."item"."nombre" AS "productos_item_nombre" FROM "productos"."item";
*/
con.entityManager.find(item);

/**
* This will change the schema for the Entity Item, but only for the current transaction.
*
* Expected result: SELECT "anotherSchema"."item"."id" AS "anotherSchema_item_id", "anotherSchema"."item"."nombre" AS "anotherSchema_item_nombre" FROM "anotherSchema"."item";
*/
con.entityManager.find(item).overrideConfiguration("schema", "anotherSchema");
/*or...*/
con.entityManager.overrideConfiguration("schema", "anotherSchema").find(item);
/*or...*/
con.entityManager.overrideConfigurationFor(Item, "schema", "anotherSchema");
/*or...*/
con.entityManager.useSchema("anotherSchema").find(Item);
```

**overrideConfiguration** can also let the user to change another configuration of the entity.

**Comment by pleerock** [comment]
yes defining schema in entity decorator is possible. `overrideConfiguration` is not needed, because query builder can find out entity schema from its definition in entity metadata.

**Comment by afr1983** [comment]
@pleerock I think it is best to keep the overrideConfiguration option, since in multi-tenant setups it is necessary to change the schema on-the-fly.

**Comment by pleerock** [comment]
@afr1983 query builder can find out entity schema from its definition in entity metadata thats why `overrideConfiguration` which is bad by suggested design. I don't see any cases when this wont work with query builder which can know about entity schema in entity metadata.

**Comment by afr1983** [comment]
@pleerock Perhaps I am misunderstanding how to use TypeORM, but I assume the entity metadata is the @Entity decorator, right? I don't see how can I change that in runtime, for a specific query.

In a multi-tenant setup separated by schemas, you have two customers in the same database, each one living on its own schema, where all the tables are identical. If you want to process a task from customer A you just `set search_path=customer_A` on the connection, and all the queries from that point will be using the customer A tables. Same for customer B, C etc. Therefore you need to change the schema dinamically at runtime.

**Comment by chriszrc** [comment]
Check out how hibernate does it. I think the ticket here is that the connection itself would be set with all the search paths, and that the queries themselves would use the schema prefix : 

https://www.thoughts-on-java.org/hibernate-tips-define-schema-table-names/

**Comment by pleerock** [comment]
complete schema support will land very soon, @AlexMesser is working on it right now

**Comment by AlexMesser** [comment]
feature will be available in `0.1.0-alpha.48`. Read related docs here: [Using multiple databases and schemas](https://github.com/typeorm/typeorm/blob/master/docs/using-multiple-databases.md)

**Comment by felipesabino** [comment]
@AlvaDamian @afr1983 Initially I was looking forward to having this feature on TypeORM just to allow me to do use is as a multi-tenant solution as well, but after doing some research we ended up not going this route due to the headache that it would be to scale in the future.

[Here is a nice post](https://influitive.io/our-multi-tenancy-journey-with-postgres-schemas-and-apartment-6ecda151a21f) that exposes some of the issues about using _"Shared Database, Separate Schemas"_ as a multi-tenant solution when trying to scale up that you might find useful. In the end I am following [Microsoft's Shared Database, Shared Schema](https://web.archive.org/web/20170530080303/https://msdn.microsoft.com/en-us/library/aa479086.aspx#mlttntda_sdshs) to separate our tenants instead. 

I am in the beginning of the implementation and still not sure how it will play out with TypeORM, but you might find useful to check this gist with an example of the [Tenant View Filter Pattern](https://gist.github.com/felipesabino/1f902e601479679abd339bd0cbdbef41) on PostgreSQL using `CURRENT_USER`,`ROLE`s and views to separate tenant data.

I am planning on using TypeORM migrations to create the tenant views but not so sure yet how to scope the queries and insertions for each user without creating multiple connections or using raw queries.

**Comment by webmobiles** [comment]
@pleerock please where is the doc, to set the schema? "Currently schema is supported only on connection-level"

**Comment by Kononnable** [comment]
You want to set schema on a entity level?  There is an option for that on Entity decorator. Not sure where is it mentioned in the docs.

**Comment by chiangf** [comment]
I think you can do something like
```
@Entity({ schema: 'foo', name: 'bar' })
class Bar {...}
```

which will reference the `foo.bar` table (in the `foo` schema)

**Comment by pleerock** [comment]
@webmobiles see what you can pass via connection options

**Comment by Rolias** [comment]
> @pleerock please where is the doc, to set the schema? "Currently schema is supported only on connection-level"

I don't know if the OP was looking for where to set the schema on the connection-level or not, but I was. For anyone else looking, this is documented in the [connection-options](https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md) file in the `docs` folder.

**Comment by bartcone-fulfilld** [comment]
Updated docs link if anyone else is looking: https://github.com/typeorm/typeorm/blob/master/docs/multiple-connections.md#using-multiple-schemas-in-a-single-connection
