### ISSUE TITLE
@UpdateDateColumn doesn't get updated on cascade

### ISSUE THREAD

**Issue by deini** [typeorm/typeorm#2601]
**Issue type:**
[X] question

**Database system/driver:**
[X] `postgres`

**TypeORM version:**
[X] `latest`

I have a question about `@UpdateDateColumn ` if I have a parent entity lets say `User` and it has a 1:1 cascade relationship of `Profile` then say I get a user like this:

```ts
const user = userRepo.findOne(1, { relations: ['profile'] });
```

And then modify and save it like
```ts
user.name = 'Daniel';
user.profile.bio = 'Updated Bio';

userRepo.save(user);
```

This will update the the user and profile, however the profile's `@UpdateDateColumn` doesn't get updated, is this expected?

**Comment by Kononnable** [comment]
@deini #
Did you resolve your issue?

**Comment by deini** [comment]
@Kononnable I haven't played with it for a while. Will re-open later if needed. Thanks.
