### ISSUE TITLE
Question: update query builder - setting a column to another column

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#2604]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.latest` (or put your version here)

I have a SQL update statement, with a reflexive field. E.g.

```
await this.data.createQueryBuilder()
    .update(Code)
    .set({
        paymentPaidAt: moment.utc().toDate(),
        paymentAmountPaid: "paymentAmountOwed",
        paymentAmountOwed: 0
    })
    .where("sId = :sId", { sId: s.id })
    .execute();

```

Specifically, I'm setting paymentAmountPaid to paymentAmountOwed. Which is another column.

Is this supported by QB?

**Comment by tenuki** [comment]
I'm having the same issue, with postgresql and typeorm 0.2.7.

Actually tried also this code, taking hints from tests:

    await this.data.createQueryBuilder()
        .update(Code)
        .set({
            paymentAmountPaid: () => "paymentAmountPaid"
        })
        .where("sId = :sId", { sId: s.id })
        .execute();

nor:

    await this.data.createQueryBuilder()
        .update(Code)
        .set({
            paymentAmountPaid: () => { return "paymentAmountPaid" }
        })
        .where("sId = :sId", { sId: s.id })
        .execute();

Any idea?

PS: I know setting to same column's value is non-sense but just an example for later ...

**Comment by tenuki** [comment]
@filipjnc I think there's a test for this: https://github.com/typeorm/typeorm/blob/master/test/functional/query-builder/update/query-builder-update.ts#L59

**Comment by filipjnc** [comment]
@tenuki that test I have not seen. Have you tried though to replicate the code, only customized for your case?
```
        const qb = connection.createQueryBuilder();
        await qb
            .update(Code)
            .set({ paymentAmountPaid: () => qb.escape(`paymentAmountOwned`) })
            .where("sId = :sId", { sId: s.id })
            .execute();
```
I haven't done a deep dive into the driver for postgres, but I think escape adds additional quotation marks around the column name to cope with the camelCase name.

**Comment by tenuki** [comment]
Thanks @filipjnc I seem to remember have tried that with the same result. I promise I will take a deeper view on test and with this you say!
