### ISSUE TITLE
Using `_id` suffix (underscores and lowercase) on foreign key columns rather than `Id` (camelCase)

### ISSUE THREAD

**Issue by hi2u** [typeorm/typeorm#2608]
Issue type: not sure if if it's a question, bug report, feature request or documentation issue.
Database: Postgres
TypeORM version: 0.2.7

I have a `disk` table and `filesystem` table.  A `disk` refers to hard drives, and can contain multiple filesystems (partitions).

I want the foreign key column to be called `disk_id`.  

I also want to be able to both access `disk_id` directly in the model (the raw UUID string, without loading the foreign model), as well as accessing the foreign model on the `Disk` property. ... not sure if this is relevant to the main question about getting the name to be `disk_id`, but I've read: http://typeorm.io/#relations-faq/how-to-use-relation-id-without-joining-relation

In my filesystem class, I've tried:

```ts
@Column({
    "name": "disk_id",
    "type": "uuid",
    "nullable": false
})
disk_id: string;

@ManyToOne(type => Disk, Disk => Disk.Filesystems)
Disk:Disk;
```

...and also...

```ts
@ManyToOne(type => Disk, Disk => Disk.Filesystems)
@Column({name: 'disk_id', type: 'uuid'})
disk_id:Disk;
```

...I know both of those are probably wrong, but I've tried about 10 other variations which I can't remember now.  No matter what I do, when I run `typeorm schema:log` it always wants to create a column called `diskId` or `diskIdId`.

I've spent hours searching the issues and documentation, am I missing something really basic here?

**Comment by hi2u** [comment]
Ok seems I misunderstood something.

All I needed to do was add a `@JoinColumn` line:

```ts
@ManyToOne(type => Disk, Disk => Disk.Filesystems)
@JoinColumn({ name: "disk_id" }) // <-- needed to add this
Disk:Disk;
```
...this prevents TypeORM from creating an extra `diskId` column.  I thought I read something somewhere else that said you don't need `@JoinColumn` but must have been confused.

**Comment by debuggerpk** [comment]
Thanks hi2u
