### ISSUE TITLE
env vs ormconfig.json differences in paths when using a comma within the path string.

### ISSUE THREAD

**Issue by bashleigh** [typeorm/typeorm#2609]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.6` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When using envs I've noticed the below example doesn't work 

```
TYPEORM_MIGRATIONS="src/migrations/**/*.{ts,js}"
```

However using the same string within ormconfig.json works fine. 

```json
{
    "migrations": ["src/migrations/**/*.{ts,js}"],
}
```

When printing the options within the connection's constructor I get the following output when using the above env example. 

```
{
    ...
    migrations: [ '"src/migrations/**.{ts', 'js}"' ],
    ....
}
```

Removing the comma and using the following works fine 

```
TYPEORM_MIGRATIONS="src/migrations/**/*.ts"
```

For me, I can use the above for now and use an alternative env within my production container. 
I'm not sure if this is a bug or the expected output. The same happens when using entities.
If this is the expected output could this be added to the documentation within env? Been stumped on this for 2 days, could save some other people some time :) 
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by frozenex** [comment]
+1

**Comment by havenchyk** [comment]
Seems to be a bug

**Comment by havenchyk** [comment]
@frozenex no need to put such comments, you can just add a reaction to the issue description you you're interested in fixing

**Comment by bashleigh** [comment]
sure, I'll create a repo that replicates the issue within the week 👍

**Comment by bashleigh** [comment]
Created a repo with description and working example of the issue https://github.com/bashleigh/typeorm-env-issue

**Comment by ariellephan** [comment]
+1 Still an issue for me as well

**Comment by billyjov** [comment]
@bashleigh i'm fassing to a similar issue using a typescript file as config.. all work fine locally but failed on prod system with the message `RepositoryNotFoundError: No repository for "XXX" was found. Looks like this entity is not registered in current "XXXX" connection?`

here my pattern:

```
entities: [
        // UserEntity,
        // RefreshTokenEntity
        // 'api/entities/index.ts',
        // 'api/entites/index.js',
        'api/entities/**/*.{ts,js}'
    ],
```

Any sugesstion on how to fix them ?

@ariellephan what issue do you have exactly ?

**Comment by billyjov** [comment]
I solved my Issue using `__dirname` for relative paths:

```
entities: [
     __dirname + 'path/to/entities/**/*.{ts, js}'
]
```

**Comment by canhkieu** [comment]
https://github.com/typeorm/typeorm/issues/3005#issuecomment-531467849

**Comment by imnotjames** [comment]
Sounds like you figured out the problem.
