### ISSUE TITLE
Why arent mysql column names escaped?

### ISSUE THREAD

**Issue by aequasi** [typeorm/typeorm#261]
https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlDriver.ts#L195

Seems like they were before? But were commented out.... Is this something we can get back, or have configurable?

**Comment by pleerock** [comment]
Having names escaped brings some problems in some cases, having non escaped names also may bring some other problems. I see you are a php dev, and you probably should know that doctrine also does not escape column names at all. I didn't decided yet which strategy is the best for typeorm. What problem do you have? Do you have some column that uses reserved name?

**Comment by aequasi** [comment]
Yeah, im using an existing database that has reserved words as column names. For the time being im just overriding the prototype to put them back. Is it something that can be done conditionally?

IIRC doctrine does escape them when necessary

**Comment by pleerock** [comment]
> IIRC doctrine does escape them when necessary

can you share you knowledge there, so I can implement it as best practices do. Do you know when exactly do doctrine escape them, and when not? As I remember doctrine forces you to enclose special names in "`", like this: ```/** @ORM/Column(name='`text`') **/ $column;```

**Comment by aequasi** [comment]
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/DefaultQuoteStrategy.php

They use "QuoteStrategy" classes to quote based on platform, along with the DBAL

https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L1847-L1869

**Comment by pleerock** [comment]
Ive returned back escaping in the latest `0.0.9-alpha.3` version. In the future versions I'll think more about best quoting strategy for typeorm.

**Comment by aequasi** [comment]
👍 I think a quoting strategy would be the best solution, though it does add a lot of work...

**Comment by pleerock** [comment]
Closing it since original issue was already resolved.
