### ISSUE TITLE
Data type "geometry" is not supported by "postgres" database.`

### ISSUE THREAD

**Issue by jpmonette** [typeorm/typeorm#2610]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
@Entity()
export class Event {
  @Column() name: string;

  // @ts-ignore (otherwise I get type warning)
  @Column("geometry", { nullable: true })
  location: string;
}
```

**Expected outcome:** Create the postgres table with a geometry column

**Actual outcome:** `DataTypeNotSupportedError: Data type "geometry" in "Event.location" is not supported by "postgres" database.`

Seems like the latest version of `PostgresDriver.ts` isn't in `typeorm@next`, or latest one as well.

---

```ts
@Entity()
export class Event extends BaseTable {
  @Column() name: string;

  @Column("point", { nullable: true })
  location: string;
}
```

This seems to work, but documentation says `geometry` should work as well.

**Comment by Alain1405** [comment]
Same holds valid for geography type:

`"typeorm": "0.2.7"`
```typescript
    @Column("geography")
    coordinates!: string;
```
yields
 `'Data type "geography" in "GeoLocation.coordinates" is not supported by "postgres" database.' }`
while
```typescript
    @Column("point")
    coordinates!: string;
```
works just fine.

Also notice that
```typescript
    @Column("geography", {
        featureType: "Point",
        srid: 4326
    })
    coordinates!: string;
```
produces a compile error: 
`src/entity/User.ts(29,13): error TS2345: Argument of type '"geography"' is not assignable to parameter of type '(type?: any) => Function'.`

**Comment by pleerock** [comment]
@vlapo thanks for the confirmation! Lets close it, feel free to reopen if something still isn't supported.

**Comment by abhyuditjain** [comment]
I have a Geography column, but how do I insert data into it?

**Comment by dmoree** [comment]
The error still occurs on `0.2.15`. I am receiving: `error: { error: type "geometry" does not exist`

 I have tried the solution @vlapo provided as well as the syntax suggested in https://github.com/typeorm/typeorm/issues/2443#issuecomment-401920350.

Perhaps this issue should be reopened?

**Comment by vlapo** [comment]
Just pass json structure as postgres require:
```typescript
this.entity.point = {
  type: "Point",
  coordinates: [0, 0]
};
// save
```
Check our tests https://github.com/typeorm/typeorm/tree/master/test/functional/spatial/postgres

**Comment by pleerock** [comment]
@AlexMesser at some point we'll need to add detailed docs on each data type we have and examples on how to use them

**Comment by pie6k** [comment]
You might want to check https://www.npmjs.com/package/@types/geojson type as it's compatible with postgis, so it might be helpful to manage your data

**Comment by shadrech** [comment]
Any update with the docs @pleerock . Its only been a year 😅

**Comment by mehtamanan** [comment]
+1

**Comment by roylee0704** [comment]
I've tried all the suggestions above.

It's not working - I still got the error `QueryFailedError: type "geography" does not exist`

**Comment by shadrech** [comment]
@roylee0704 make sure your postgres instance has postgis extension installed. With latest typeorm it should work

**Comment by kukuandroid** [comment]
How to query ?

**Comment by hc3** [comment]
i try this:

```
import { Geometry } from "geojson";
import { Column, Entity, JoinColumn, OneToOne } from "typeorm";
import { Base } from '../../config/entity.base'
import { User } from "./user.entity";

@Entity({ name: 'marketplaces' })
export class Marketplace extends Base {

  @Column({ type: 'varchar', length: 100, nullable: true })
  market_name: String

  @Column({ type: 'geometry', nullable: true, spatialFeatureType: 'Point', srid: 4326 })
  location: Geometry

  @OneToOne(() => User, user => user.id)
  @JoinColumn({ name: 'user_id' })
  user: User

}
```

and a got an error: 

```
QueryFailedError: type "geometry" does not exist
```

inside query log of typeorm :

```
ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/postgis.control": No such file or directory

STATEMENT:  CREATE EXTENSION IF NOT EXISTS "postgis"

ERROR:  type "geometry" does not exist at character 309

STATEMENT:  CREATE TABLE "marketplaces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "is_archived" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "market_name" character varying(100), "location" geometry(Point,4326), "user_id" uuid, CONSTRAINT "REL_18f8ca2e793c5d481e1442941f" UNIQUE ("user_id"), CONSTRAINT "PK_e4d5b8aa6ae255c4ce370792f79" PRIMARY KEY ("id"))

```

otherwise using this aprouch everything works fine:

i change type to point.

```
import { Geometry } from "geojson";
import { Column, Entity, JoinColumn, OneToOne } from "typeorm";
import { Base } from '../../config/entity.base'
import { User } from "./user.entity";

@Entity({ name: 'marketplaces' })
export class Marketplace extends Base {

  @Column({ type: 'varchar', length: 100, nullable: true })
  market_name: String

  @Column({ type: 'point', nullable: true, spatialFeatureType: 'Point', srid: 4326 })
  location: Geometry

  @OneToOne(() => User, user => user.id)
  @JoinColumn({ name: 'user_id' })
  user: User

}

```

**Comment by PradeepNooney** [comment]
https://stackoverflow.com/questions/67435650/storing-geojson-points-and-finding-points-within-a-given-distance-radius-nodej/67557083#67557083

**Comment by khaledbk** [comment]
any one having issue with `goemetry` or `geography` something like 
```
type "geography" does not exist
```

you need to install `postgis` extension first :

```bash
sudo apt-get install postgis
```

then using pgAdmin 4 in query runner you should run this

```bash
CREATE EXTENSION postgis;
```

then to check if everything is ok ,

```bash
SELECT * FROM pg_extension WHERE extname = 'postgis';
```
this should return a the extension.

Do not forget to restart postgres service

```bash
sudo service postgresql restart
```
