### ISSUE TITLE
Saving records with many to one relation

### ISSUE THREAD

**Issue by santhan456** [typeorm/typeorm#2611]
**Issue type:**
[*] question
[*] documentation issue

**Database system/driver:**
[*] `postgres`

**TypeORM version:**
[*] `latest`

**Steps to reproduce or a small repository showing the problem:**

I have two entities with Many to One relation (Client - Subscriber) like below. 

`@Entity()
export class Client extends Base {
    @PrimaryGeneratedColumn()
    public id: number;
    
    @ManyToOne(type => Subscriber, subscriber => subscriber.clients)
    subscriber: Subscriber;   
}`

`@Entity()
export class Subscriber extends Base  {
    @PrimaryGeneratedColumn()
    public id: number;

    @OneToMany(type => Client, client => client.subscriber)
    clients: Client[];
}`

While saving client record I have to pass subscriber to client.subscriber like below. Is that really necessary? 

`
client.subscriber  = subscriberRepository.findOne(subscriberId);
`

[https://github.com/typeorm/typeorm/blob/master/docs/relational-query-builder.md](url)
The document in above link says to use 'set' method for many to one relation & we can pass id in place of subscriber. It says it is possible to save with a primary key?

I am trying to run the query as below
`return await getConnection()
                                    .createQueryBuilder()
                                    .relation(Client, "subscriber")
                                    .of(client)
                                    .set(subscriberId); `

Its not helping to save the records and nothing returned. I don't know if I am doing wrong. If so tell me how to do it.

**Comment by filipjnc** [comment]
What if you try to provide only IDs of existing entities?
```
return await getConnection()
    .createQueryBuilder()
    .relation(Client, "subscriber")
    .of(client.id)
    .set(subscriber.id);
```
If it is still not working, have the following checked:
- Both entities exist in the database before running this snippet
- `client.id` and `subscriber.id` are the right ids with the right type

**Comment by santhan456** [comment]
I tried the same. Entities & related subscriber already exists in db.

**Comment by santhan456** [comment]
I got it worked. We can pass client.subscriber = id instead of client.subscriber = subscriber(); in save method
