### ISSUE TITLE
querying JSON-type column with TypeORN

### ISSUE THREAD

**Issue by EliKabasele** [typeorm/typeorm#2613]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `2.0.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>
How can I query from a JSON-type Column ? Let's say following is my Entity witch contains the JSON-type column validDates:
export Class Menu {
  @PrimaryGeneratedColumn('uuid')
     id: string;
  @Column('json', {nullable: true})
    validDates?: ValidDatesClass;
}

and ValidDatesClass looks like this: 
     export class ValidDatesClass {
    [key: string]: boolean;
}
And I want to retrieve all Menus where validDates 's value is true
Thanks

**Comment by Kononnable** [comment]
Looks like you forgot to describe the issue.
