### ISSUE TITLE
How can i use PostgreSQL through Unix socket?

### ISSUE THREAD

**Issue by MikalaiR** [typeorm/typeorm#2614]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I tried something like:

```
{
  "type": "postgres",
  "url": "postgresql://user:pass@%2Fcloudsql%2Fpath:5432/db",

  "entities": [
    "dist/**/**.entity.js"
  ],
  "synchronize": true
}
```
but it doesn't working.

**Comment by Kononnable** [comment]
@MikalaiR 
Did you resolve your issue? It doesn't look ORM related - can you connect with similar options using postgres driver directly?

**Comment by MikalaiR** [comment]
@Kononnable I have resolved this issue using temporary 'crutch'.
```
{
  "type": "postgres",
  "url": "postgresql://user:pass@localhost:5432/db",

  "extra": {
    "host": "/cloudsql/...."
  },
```

It don't work in right way because TypeORM parses `url` itself instead of pass it to driver. And `extra` works because `extra` apllied to parsed object. But it's temporary crutch i think, TypeORM should support it through `url`.

**Comment by fullofcaffeine** [comment]
I'd also like the know if this is currently supported / the status of this issue. Currently I'm using password auth restricted by host and pgsql is protected by a frewall, but it'd much more convenient if I had a unix user per db/app and could use pg_ident ithrough socket instead.

**Comment by paeolo** [comment]
The issue is still present in the latest release. Why TypeORM doesn't pass the url to the driver directly ?

**Comment by guillenotfound** [comment]
For anyone having the same issue, here are the variables I've set on my Cloud Run service:
![image](https://user-images.githubusercontent.com/5492960/89021248-7eeb8580-d320-11ea-9193-8590d84d33b4.png)

It does connect via socket, here is how the variable looks like:
`TYPEORM_HOST=/cloudsql/INSTANCE_CONNECTION_NAME`

More info here about service account permissions & APIs to enable here: https://cloud.google.com/sql/docs/postgres/connect-run

**Comment by imnotjames** [comment]
This is good to go in the next release.

**Comment by MrCube42** [comment]
Since I had a lot of research to do to find this out, I'll just let you know, that you can also use the following syntax here:
```
"url": "socket:<path-to-socket>?db=<databasename>",
```

for more details see:
https://github.com/brianc/node-postgres/tree/master/packages/pg-connection-string#unix-domain-sockets
