### ISSUE TITLE
example project for bundling a typeorm project with browserify

### ISSUE THREAD

**Issue by tstoppe89** [typeorm/typeorm#2617]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

Hey guys!
I'm currently trying to bundle my project with browserify, but I don't get it to work. The project is a SDK which contains typescript classes that also contain it's own DAO (data access object). Those DAO classes import typeorm with Entity, Column etc.
I'm bundling with browserify, but I'm getting:

```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (38:0) while parsing /projectpath/node_modules/typeorm/browser/index.js 
```
So it seems, that it didn't transpile this file to es5.

The gulp task:
```
gulp.task("web", function () {
    return browserify({
            basedir: '.',
            debug: true,
            entries: ['web_entry/Entry.ts'],
            cache: {},
            packageCache: {}
        })
        .plugin(tsify)
        .transform(babelify.configure({
          presets: ["es2015", "stage-0"]
        }))
        .bundle()
        .pipe(source('bundle.js'))
        .pipe(gulp.dest("WebContent"));
});
```
The `Entry.ts` file imports all classes of the sdk and makes it visible in the window object.

`tsconfig.json`:
```
{
    "version": "2.0.2",
    "compilerOptions": {
        "lib": ["es5", "es2015.promise", "dom", "es2015"],
        "target": "es5",
        "typeRoots": [
          "node_modules/@types"
        ],
        "outDir": "dist",
        "module": "commonjs",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true,
        "declaration": false,
        "sourceMap": true
    }
}
```

_Further explanation: This bundled file can be use for customers, which prefer to put a single file in their web page and use this sdk. For Angular users etc. a SDK module is generated._ 

Is there any example using typeorm with browserify?

**Comment by imnotjames** [comment]
You would need to transpile down with babel if the current output doesn't work for you.
