### ISSUE TITLE
where parameter not working

### ISSUE THREAD

**Issue by iswahyudhie** [typeorm/typeorm#2618]
**Issue type:**

[ x ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
 ```ts
const query = await itemRepository.createQueryBuilder('it')
                .where("it.description = :id", { id: "Timber" }) 
                .getSql();

 res.json(query);
 ```
I try to know why my query result is empty, so I write above code  and show the result in the browser
here is the result
```
"SELECT \"it\".\"item\" AS \"it_item\", \"it\".\"description\" AS \"it_description\", \"it\".\"qty_onhand\" AS \"it_qty_onhand\", \"it\".\"unit_price\" AS \"it_unit_price\", \"it\".\"createdDate\" AS \"it_createdDate\", \"it\".\"updatedDate\" AS \"it_updatedDate\" FROM \"item\" \"it\" WHERE \"it\".\"description\" = @0"
```

looks like the where parameter is not replaced by actual given value.
this is my first time using typeorm, any suggestion will be appreciated. 
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by filipjnc** [comment]
I have used the queryBuilder without initializing one of the types. Please try the following:
```
const query = await itemRepository.createQueryBuilder('it')
    .select()
    .where("it.description = :id", { id: "Timber" })
    .getSql();
```

**Comment by iswahyudhie** [comment]
hi filipjnc, i already did your suggestion unfortunately i still get same result.

**Comment by pleerock** [comment]
parameter will not be replaced, its underlying driver responsibility to properly replace parameter.

**Comment by iswahyudhie** [comment]
do you mean this is already work by design

**Comment by iswahyudhie** [comment]
sorry, my bad, I already solve my issue, apparently, I choose the wrong method to print query. I should use getQueryAndParameters method instead.

Regards
