### ISSUE TITLE
Datetime - conversion from database to object ignores 'no timezone' information

### ISSUE THREAD

**Issue by thiago-soliveira** [typeorm/typeorm#2622]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have this entity

```ts

@Entity()
export class ExampleEntity implements BaseEntity {

  @PrimaryGeneratedColumn()
  id: number;

  @Column({ default: true })
  active: boolean;

  @CreateDateColumn()
  createdAt: Date;

}

```

This is the table structure created. Note the `createdAt` field type - `timestamp without time zone`.

![screenshot 2018-08-04 16 02 33](https://user-images.githubusercontent.com/4991904/43679680-db4b7d02-97ff-11e8-901a-47c4dc7c2710.png)

At some point on my application, I save this entity by calling the `save` method of the related `repository`.

```ts
import { getRepository } from 'typeorm';

const repository = getRepository(Example);

const example = new Example();
example.active = true;

repository.save(example);
```

This is the item on the database. It has been saved **correctly**. The `createdAt` field matches the UTC date it was saved.

![screenshot 2018-08-04 16 25 22](https://user-images.githubusercontent.com/4991904/43679840-04189b22-9803-11e8-867b-899bfecc20eb.png)

Then, later on my application I retrieve that saved `entity`.

```ts
import { getRepository } from 'typeorm';

const repository = getRepository(Example);

const example = await repository.findOne({ active: true });
```

And the `createdAt` field value.

```
console.log(example.createdAt.toUTCString());
Sat, 04 Aug 2018 21:24:36 GMT
console.log(example.createdAt.toLocaleString());
2018-8-4 18:24:36
```

As you can see, `typeorm` read that database value  as my local time, which it shouldn't, since that value was stored as a `timestamp without time zone`.

**Comment by hielkehoeve** [comment]
Is your application running in the same timezone as the database? AFAIK databases never support timezones and JavaScript is bad at supporting timezones. It seems to be the defacto standard to save and use all timestamps in UTC time and let the client convert to local timezone.

**Comment by thiago-soliveira** [comment]
> Is your application running in the same timezone as the database?
Yes, they are. Actually, they were running on the same machine.

**Comment by elthrasher** [comment]
Try setting `dateStrings: true` in your connection settings. http://typeorm.io/#/connection-options

**Comment by Kononnable** [comment]
@thiago-soliveira 
Did you resolve your issue?

**Comment by thiago-soliveira** [comment]
Hey.. Sorry. There's no `dateStrings` option available for my scenario, which is postgres.  http://typeorm.io/#/connection-options/postgres-connection-options

**Comment by pthrasher** [comment]
@thiago-soliveira I just had to solve this for myself:

```javascript
import pg from 'pg'
pg.types.setTypeParser(1114, (stringValue) => new Date(`${stringValue}+0000`))
```

Use that code somewhere before you start working with your db.

**Comment by Kononnable** [comment]
Looks like issue was resolved.

**Comment by arusakov** [comment]
`TypeORM` still change `Date` object while inserting or selecting from `PostgreSQL` `timestamp` columns.

My simple ts script:
```
import { createConnection, Entity, Column, PrimaryGeneratedColumn } from 'typeorm'

@Entity()
class PgEntity {
    @PrimaryGeneratedColumn()
    id!: number

    @Column('timestamp')
    createdAt!: Date
}

createConnection({
    entities: [PgEntity],
    logging: 'all',
    synchronize: true,
    type: 'postgres',
    url: '******',
}).then(async (conn) => {
    await conn.manager.clear(PgEntity)

    const user1 = new PgEntity()
    user1.createdAt = new Date()

    await conn.manager.insert(PgEntity, user1)
})
```
`TypeORM` logging:
```
query: INSERT INTO "pg_entity"("createdAt") VALUES ($1) RETURNING "id" -- PARAMETERS: ["2019-11-05T11:40:46.406Z"]
```
And in `Postgres` directly via `psql`:
```
SELECT * FROM pg_entity;
 id |        createdAt        
----+-------------------------
 38 | 2019-11-05 14:40:46.406
(1 row)
```

I think it is wrong behavior of `TypeORM`. `TypeORM` must not manipulate with `Date` objects for `timestamp` columns.

**Comment by arusakov** [comment]
After some investigation I have found helpful links:
* https://node-postgres.com/features/types (interesting in the bottom)
* old issue https://github.com/typeorm/typeorm/issues/1716 (FIXED)

Summary:
`TypeORM` doing all the best, but `pg` module convert `Date` objects to local timezone. Why? I don't know :disappointed: 

I see the following options:
* @pthrasher [hack](https://github.com/typeorm/typeorm/issues/2622#issuecomment-476416712) above
* use `process.env.TZ` from [node-postgres docs](https://node-postgres.com/features/types) (can leads other unpredictable behavior)
* use `timestamp with timezone` everywhere
