### ISSUE TITLE
How do you detect if an attribute like password has changed

### ISSUE THREAD

**Issue by adetoola** [typeorm/typeorm#2624]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I realise that this might be a noob question but i can't find a reference in the docs. I am trying to a subscriber decorator to hash users password before persisting to the database. 

In sequelizejs, I use the following code,
```js
User.hashPassword = (user, options) => {
    if (!user.changed('password')) {
      return null;
    }
    // hash password
    return Bcrypt.hash(user.get('password'), SALT_ROUNDS)
      .then(hash => user.set('password', hash));
  };
```
Right now, my `typeorm` translation is roughly
```ts
@BeforeInsert()
@BeforeUpdate()
    hashPassword() {
        // conditional to detect if password has changed goes here
        this.password = bcrypt.hashSync(this.password, SALT_ROUNDS);
    }
```

Now, the issue is, I stuck at `!user.changed('password')`. Is there an equivalent function in typeorm to do this without rolling out my own solution?

**Comment by Keyj1n** [comment]
you can make a something like this to get arount this

`    @PrimaryColumn()
    public username: string;

    @Column()
    public password: string;

    @Column({ nullable: true })
    public jwtToken: string;

    private tempPassword: string;

    public toString(): string {
        return `${this.username}`;
    }

    @AfterLoad()
    private loadTempPassword(): void {
        this.tempPassword = this.password;
    }

    @BeforeUpdate()
    private encryptPassword(): void {
        if (this.tempPassword !== this.password) {
            //
        }
    }`

**Comment by quentin-vauban** [comment]
Hey guys,

I am wondering why this solution wouldn't work:
```js
@BeforeInsert()
@BeforeUpdate()
hashPassword() {
  if (this.password) {
    this.password = createHmac('sha256', this.password).digest('hex');
  }
}
```

Best,
lapwat

**Comment by lapwat** [comment]
Hey guys,

I don't understand your solution @Keyj1n. Isn't `this.tempPassword` the hash of the old password and `this.password` the new password (not hashed) ? How could you compare a hash and a plain text password.

I am wondering why this solution wouldn't work:

```js
@BeforeInsert()
@BeforeUpdate()
hashPassword() {
  if (this.password) {
    this.password = createHmac('sha256', this.password).digest('hex');
  }
}
```

Best,
lapwat

**Comment by julien-sarazin** [comment]
@lapwat not sure, but i think using the same encryption process without testing if the property has been updated will encrypt the property everytime the resource changes.

**Comment by lapwat** [comment]
@julien-sarazin 

Since the password will never be used extracted when hashed, what if we never load it ? That way you can be sure that if it is present in the DTO, it is necessarily a new password given by the user (and not a previous hashed value).

```ts
@Column({ select: true })
public password: string;

@BeforeInsert()
@BeforeUpdate()
hashPassword() {
  if (this.password) {
    this.password = createHmac('sha256', this.password).digest('hex');
  }
}
```

**Comment by trunda** [comment]
@lapwat but you have to load it to compare hash with provided password during login process, haven't you?

**Comment by lapwat** [comment]
@trunda I have edited my comment I meant `select: false`.

The field is not selected when the entity is extracted, but the queries can always refer to those columns. So if I want to check the user during the login process, I would use:

```ts
async findByEmailAndPassword(loginUserDto: LoginUserDto): Promise<User> {
  return getRepository(User).findOne({ email: loginUserDto.email, password: createHmac('sha256', loginUserDto.password).digest('hex') });
}
```

Then in the auth strategy:

```ts
const user = await this.usersService.findByEmailAndPassword(loginUserDto);

if (!user) {
  throw new UnauthorizedException();
}
```

**Comment by ssanusi** [comment]
just to update this thread 
@PrimaryColumn()
public username: string;

@Column()
public password: string;

@Column({ nullable: true })
public jwtToken: string;

private tempPassword: string;

public toString(): string {
    return `${this.username}`;
}

@AfterLoad()
private loadTempPassword(): void {
    this.tempPassword = this.password;
}

@BeforeUpdate()
private encryptPassword(): void {
    if (this.tempPassword !== this.password) {
        this.loadTempPassword()
    }
}

**Comment by elsangedy** [comment]
```
import {
  Connection,
  EntitySubscriberInterface,
  EventSubscriber,
  InsertEvent,
  UpdateEvent
} from 'typeorm';

import { User } from '../../../domain/users/entities/user.entity';
import { Password } from '../../password';

@EventSubscriber()
export class UserSubscriber implements EntitySubscriberInterface<User> {
  constructor(connection: Connection) {
    connection.subscribers.push(this);
  }

  listenTo() {
    return User;
  }

  async beforeInsert(event: InsertEvent<User>) {
    event.entity.password = await Password.hash(event.entity.password);
  }

  async beforeUpdate(event: UpdateEvent<User>) {
    if (event.entity.password !== event.databaseEntity.password) {
      event.entity.password = await Password.hash(event.entity.password);
    }
  }
}
```

**Comment by RodolfoSilva** [comment]
```ts
import { Column, Entity, PrimaryGeneratedColumn, BeforeInsert, BeforeUpdate } from 'typeorm';
import * as bcrypt from 'bcrypt';

@Entity()
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  username: string;

  @Column({ select: false })
  password: string; 

  @BeforeInsert()
  @BeforeUpdate()
  async hashPassword(): Promise<void> {
    if (!!this.password) {
      this.password = await bcrypt.hash(this.password, 10);
    }
  }
}
```

**Comment by plashenkov** [comment]
@lapwat We can use such selection by username and password only if we don't use salt. But that's not good, we really should use salt when calculating hashes.

**Comment by lapwat** [comment]
@plashenkov I am not sure I understand your comment. You can change the auth strategy by using salt if you'd like. How is it related to the selection in the database?

**Comment by plashenkov** [comment]
@lapwat 

If you mark the password property as `select: false`, you will not be able to compare the password from a user (when he tries to log in) with password stored in a database. Then you suggest to select by username and password:

```ts
getRepository(User).findOne({ email: loginUserDto.email, password: createHmac('sha256', loginUserDto.password).digest('hex') })
```

But you can't do that if you use salt. Because hash stored in database will not match hash you calculate right now, because of salt (you don't know salt which was used for calculation of the stored hash).

This is why @Keyj1n solution takes place.

**Comment by plashenkov** [comment]
For example,

```ts
const SALT_ROUNDS = 10
const result = await bcrypt.hash(password, SALT_ROUNDS)
```

This generates salt internally, then calculates hash based on password and salt, and then returns generated salt and hash as combined string. If you will try to repeat this algorithm, you'll get completely different result.

So you will net be able to select by username (email) and hash.

But if you select just by username (email), and your user entity contains password hash, you can compare it with newly entered password:

```ts
const passwordsMatch = await bcrypt.compare(enteredPassword, user.password)
```

(since `user.password` contains everything necessary to recalculate the hash and find out whether entered password is correct)

P.S. It's just for information, no claims :)

**Comment by lapwat** [comment]
OK I thought that the salt was global and stored in an env variable.

Le lun. 31 août 2020 à 23:34, Yuri Plashenkov <notifications@github.com> a
écrit :

**Comment by plashenkov** [comment]
@lapwat Ah, nope. Salt is different for every password, that's the point. Then even if two users have identical passwords, you'll have different hashes in the database. And if an attacker tries to use rainbow table (https://en.wikipedia.org/wiki/Rainbow_table), using salts makes his attack unrealizable.

**Comment by lapwat** [comment]
@plashenkov Can't we use the dto (email+password) as salt? It should be unique in the database.

```ts
async findByEmailAndPassword(loginUserDto: LoginUserDto): Promise<User> {
  const hash = createHmac('sha256', loginUserDto.email).update(loginUserDto.password).digest('hex');
  return getRepository(User).findOne({ email: loginUserDto.email, password: hash });
}
```

**Comment by plashenkov** [comment]
@lapwat Well, I do not know, maybe it's OK for your special case/software.

Ideally, the salt shouldn't be connected with some params like email/password and should be generated independently with some "cost" using special algorithm, see for example here: https://auth0.com/blog/hashing-in-action-understanding-bcrypt/#L-code-bcrypt--code--Best-Practices (that's what I've found first, maybe there are better explanations).

For example, bcrypt has `saltRounds` param which defines the "cost" of the salt:

```js
const SALT_ROUNDS = 10
const salt = await bcrypt.genSalt(SALT_ROUNDS)
const hash = await bcrypt.hash(password, salt)
```

Or a shortcut-version:

```js
const SALT_ROUNDS = 10
const hash = await bcrypt.hash(password, SALT_ROUNDS)
```

Maybe some security professionals can correct me or explain better.

**Comment by cloudratha** [comment]
I know this doesn't answer OP's question about detecting changes in attributes, but could be a potential solve for the password problem.

This might be an absurd approach but what if you added a non-column field to the entity. 

```js
@Entity()
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  username: string;

  @Column()
  password: string; 

  updatePassword: string;

  @BeforeUpdate()
  async hashPassword(): Promise<void> {
    if (!!this.updatePassword) {
      this.password = await bcrypt.hash(this.updatePassword, 10);
    }
  }
}
```

Or maybe a less barbaric approach:

```js
@Entity()
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  username: string;

  @Column()
  password: string; 

  async updatePassword(password): Promise<void> {
    if (!!password) {
      this.password = await bcrypt.hash(password, 10);
    }
  }
}

....
await user.updatePassword(password);
```

**Comment by IbrahimAlKhalil** [comment]
This may help someone, this is how I did it.

```typescript
import { EntitySubscriberInterface, EventSubscriber, InsertEvent, UpdateEvent } from 'typeorm';
import { User } from './user.entity';
import * as bcrypt from 'bcryptjs';

@EventSubscriber()
export class UserSubscriber implements EntitySubscriberInterface<User> {
  listenTo() {
    return User;
  }

  async hashPassword(entity: User): Promise<void> {
    entity.password = await bcrypt.hash(entity.password, 10);
  }

  beforeInsert(event: InsertEvent<User>): Promise<void> {
    return this.hashPassword(event.entity);
  }

  async beforeUpdate({ entity, databaseEntity }: UpdateEvent<User>): Promise<void> {
    if (entity.password !== databaseEntity?.password) {
      await this.hashPassword(entity);
    }
  }
}
```

**Comment by rafaelruda** [comment]
I did it in a more verbose way, but so far it serves me exactly as I wish.

```
import {
  Entity,
  Column,
  BeforeInsert,
  BeforeUpdate,
  AfterLoad,
} from "typeorm";
import bcrypt from "bcryptjs";

@Entity("users")
class User {
  @Column({ select: false })
  password?: string;
  
  @AfterLoad()
  private loadPassword() {
    Object.defineProperty(this, "_loadedPassword", {
      value: this.password,
      writable: false,
      configurable: true,
      enumerable: false,
    });
  }

  @BeforeInsert()
  @BeforeUpdate()
  private async hashPassword() {
    const loadedPassword = Object.getOwnPropertyDescriptor(this, "_loadedPassword")?.value;
    if (this.password && this.password !== loadedPassword) {
      this.password = await hash(this.password, 8);
    }
  }
}
```

By default, the password will never be returned from the database, but it can be overwritten and changed. Changing the descriptors of "_loadedPassword" made me necessary so that it is not even seen in eslint (private could do the same), but also so that it is not overwritten or read.

As the password is no longer returned by default in the bank, I added a method in the repository to authenticate the user, I will write below if anyone needs it.

```
import { EntityRepository, Repository } from "typeorm";
import User from "../models/User";
import bcrypt from "bcryptjs";

interface IloginReturn {
  user: User;
  token: string;
}

@EntityRepository(User)
class UserRepository extends Repository<User> {
  async login(email: string, password: string): Promise<IloginReturn | undefined> {
    const select: any = this.metadata.columns.map((e) => e.propertyName);

    const user = await this.findOne({ where: { email }, select });

    if (user && user.password && (await bcrypt.compare(password, user.password))) {
      delete user.password;
      return { user, token: "" };
    }
  }
}
```

In the example above, i added all User fields to select, which will bring me everything including those with `select: false`. This is just one way of doing it. Another way is that, since the "configurable" descriptor of "_loadedPassword" is set to true, you would not need to select, simply comparing the password with "_loadedPassword" after obtaining its value through the descriptor.

**Comment by alidavut** [comment]
I think I solved this problem by using this approach and wanted to share

```typescript
class MyBaseEntity extends BaseEntity {
  initialValues = new Map();

  changed(name: string): boolean {
    return this.initialValues[name] !== this[name]; // may be changed with deep equal function
  }
}
```

and with subscriber

```typescript
@EventSubscriber()
class ChangeSubscriber implements EntitySubscriberInterface {
  afterLoad(entity: MyBaseEntity): void {
    this.storeValues(entity);
  }

  afterUpdate(event: UpdateEvent<MyBaseEntity>): void {
    this.storeValues(event.entity);
  }

  afterInsert(event: InsertEvent<MyBaseEntity>): void {
    this.storeValues(event.entity);
  }

  storeValues(entity: MyBaseEntity): void {
    const columns = getConnection().getMetadata(entity.constructor).columns.map(i => i.propertyName);

    for(const column of columns) {
      entity.initialValues[column] = entity[column];
    }
  }
}
```

then use it in entity

```typescript
@Entity()
export class User extends MyBaseEntity {
  @BeforeInsert()
  @BeforeUpdate()
  async hashPassword(): Promise<void> {
    if(this.changed('password')) {
      this.password = await bcrypt.hash(this.password, 10);
    }

    if(this.changed('name')) {
      this.slug = await generateSlug(this.name);
    }
  }
}
```

This approach allows me to use ```this.changed``` in any entity.

I'll update if I encounter any problem with this.

**Comment by cloudratha** [comment]
@alidavut I like this approach for generality. But I often find myself needed to create a Subscriber for more controlled handling for each Entity. With that, you already have access to the `updatedColumn` in the `beforeUpdate` method.

One thing I would change, is using the map accessor method `get`, as well as handle unexpected property names (throw Exception? default false?). Also is there a way to pass type-hinting into `changed`?

Nice job

**Comment by alidavut** [comment]
@cloudratha good points. I think people can extend this for their needs. Also, I couldn't find a solution for type-hinging issue. The only way I found: 

```typescript
changed(name: keyof this): boolean {
  return this.initialValues[name as string] !== this[name];
}
```

but this only checks if ```name``` is available in the class or not. Vscode doesn't show any hint, it shows error if you enter invalid property name, somehow.

**Comment by DanielAlk** [comment]
Ok, I'd like to share my solution since I think is quite simple using a ValueTransformer

```typescript
const toBcryptHash: ValueTransformer = {
  from: (value: string) => value,
  to: (value: string) => value && hashSync(value, 10)
}

@Entity({ name: 'users' })
export class User extends AppEntity {
  @Column({ unique: true })
  email: string;

  @Exclude()
  @Column({ transformer: toBcryptHash, select: false })
  password: string;
}
```
Then in your auth strategy

```typescript
const select = <(keyof User)[]>getConnection().getMetadata(User).columns.map((e) => e.propertyName);
const user = await User.findOne({ where: { email }, select });
if (user && await compare(password, user.password))
  return user;
```

I'm using nestjs with class-transformer's Exclude decorator but you can always delete the password before returning the user
```typescript
if (user && await compare(password, user.password)) {
  delete user.password;
  return user;
}
```
Hope it helps.

**Comment by dmtar** [comment]
> This may help someone, this is how I did it.
> 
> ```ts
> import { EntitySubscriberInterface, EventSubscriber, InsertEvent, UpdateEvent } from 'typeorm';
> import { User } from './user.entity';
> import * as bcrypt from 'bcryptjs';
> 
> @EventSubscriber()
> export class UserSubscriber implements EntitySubscriberInterface<User> {
>   listenTo() {
>     return User;
>   }
> 
>   async hashPassword(entity: User): Promise<void> {
>     entity.password = await bcrypt.hash(entity.password, 10);
>   }
> 
>   beforeInsert(event: InsertEvent<User>): Promise<void> {
>     return this.hashPassword(event.entity);
>   }
> 
>   async beforeUpdate({ entity, databaseEntity }: UpdateEvent<User>): Promise<void> {
>     if (entity.password !== databaseEntity?.password) {
>       await this.hashPassword(entity);
>     }
>   }
> }
> ```

It's important to mention that with such approach there are the following problems:
- If you don't update the password field of the entity, but let's say only the email property. You will get an exception from the bcrypt.hash function as entity.password will be undefined
- You will hash the password on every update no matter the password is not changed, because entity.password is the plain text representation, but databaseEntity?.password is the hashed value, they will always be different. You have to use bcrypt.compare instead
- After you have a proper check for password changed make sure you do ```entity.password = databaseEntity.password;``` **if the password is not changed** or you can end up with plain text password in the database

**Comment by RizaHKhan** [comment]
> This may help someone, this is how I did it.
> 
> ```ts
> import { EntitySubscriberInterface, EventSubscriber, InsertEvent, UpdateEvent } from 'typeorm';
> import { User } from './user.entity';
> import * as bcrypt from 'bcryptjs';
> 
> @EventSubscriber()
> export class UserSubscriber implements EntitySubscriberInterface<User> {
>   listenTo() {
>     return User;
>   }
> 
>   async hashPassword(entity: User): Promise<void> {
>     entity.password = await bcrypt.hash(entity.password, 10);
>   }
> 
>   beforeInsert(event: InsertEvent<User>): Promise<void> {
>     return this.hashPassword(event.entity);
>   }
> 
>   async beforeUpdate({ entity, databaseEntity }: UpdateEvent<User>): Promise<void> {
>     if (entity.password !== databaseEntity?.password) {
>       await this.hashPassword(entity);
>     }
>   }
> }
> ```

This is a great solution, thank you for posting it.

**Comment by dakotacookenmaster** [comment]
> 
> 
> Hey guys,
> 
> I don't understand your solution @Keyj1n. Isn't `this.tempPassword` the hash of the old password and `this.password` the new password (not hashed) ? How could you compare a hash and a plain text password ?
> 
> I am wondering why this solution wouldn't work:
> 
> ```js
> @BeforeInsert()
> @BeforeUpdate()
> hashPassword() {
>   if (this.password) {
>     this.password = createHmac('sha256', this.password).digest('hex');
>   }
> }
> ```
> 
> Best,
> lapwat



> 
> 
> Hey guys,
> 
> I don't understand your solution @Keyj1n. Isn't `this.tempPassword` the hash of the old password and `this.password` the new password (not hashed) ? How could you compare a hash and a plain text password ?
> 
> I am wondering why this solution wouldn't work:
> 
> ```js
> @BeforeInsert()
> @BeforeUpdate()
> hashPassword() {
>   if (this.password) {
>     this.password = createHmac('sha256', this.password).digest('hex');
>   }
> }
> ```
> 
> Best,
> lapwat

When AfterLoad() completes, it will have loaded in the old (or possibly current) password, which should be hashed. If the password has not been changed (that is, another field changed causing an update to occur), then checking if this.tempPassword === this.password would return true, as the password had not changed. However, if the password HAD changed, it would mean that your comparison would now be comparing between an updated unhashed field and your current hashed field. At this point, you can recognize that you need to hash this new password.

**Comment by DanielMaranhao** [comment]
Hello, I would like to show my solution to this question, it is not 100% perfect but I believe it is the most simple and direct solution to this situation of bcrypt encryption. After making some tests encrypting passwords of varying lengths and contents, I noticed that the encrypted password always has a length of 60 characters. So a very pragmatic solution and also safe (as long as this doesn't change in the library), could be this

```typescript
@BeforeInsert()
@BeforeUpdate()
private async encryptPassword() {
  if (this.password.length !== 60) {
    const saltRounds = 10;
    const hash = await bcrypt.hash(this.password, saltRounds);
    this.password = hash;
  }
}
```

If there are cases in which the length is not exactly 60 (I'm not 100% sure), I think the check can simply verify if it is above 50 or 40, for example. Even because I don't think passwords are generally allowed to be that big. I know it's a work around but I hope this idea can add a bit of value to this discussion, best wishes.
