### ISSUE TITLE
unable to retrive auto generated postgresql columns after saving entities using repository patterns

### ISSUE THREAD

**Issue by pvaidhya** [typeorm/typeorm#2627]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

        //creates the users into the repository instance
        const state = this._repository.create(data);

        //save (or) insert the data into the db
        return this._repository.save(state);

Here  in the state entities, state id is an auto generated column in postgresql. while returing it back, we are not getting the auto-generated id which we will be using it for binding in angular 5.

**Comment by vlapo** [comment]
Hi @pvaidhya. 

I tested this issue and object `state` contains `id` after save. Could you please provide more information: entity definition?

**Comment by Kononnable** [comment]
Closing as no response from the reporter.
