### ISSUE TITLE
Outdated default values for mysql connection options in docs

### ISSUE THREAD

**Issue by m-burst** [typeorm/typeorm#2628]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

In [this commit](https://github.com/typeorm/typeorm/commit/0199b7f686a55dafe3f1becd3797f351f3d84ba0) default values for options `supportBigNumbers` and `bigNumberStrings` were changed. This was documented in the changelog, however the [connection options docs](https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md#mysql--mariadb-connection-options) still contain the old default values.

**Comment by pleerock** [comment]
fixed by @timothyvanderaerden !
