### ISSUE TITLE
Recursive table embedding

### ISSUE THREAD

**Issue by bpatrik** [typeorm/typeorm#263]
Hi,

Is typeorm supporting recursive table embedding? Like:

```
export class Photo {
  //...
    @Embedded(type => PhotoMetadata)
    metadata: PhotoMetadata;
  //...
}
@EmbeddableEntity()
export class PhotoMetadata{
  //...
    @Column("string")
    keywords: string;

    @Embedded(type => Camera)
    camera: Camera;
  //...
}

@EmbeddableEntity()
export class Camera {
   //..
    @Column("number")
    ISO: number;

    @Column("string")
    model: string;
   //..
}
```
Typeorm generates the column for `metadata-keywords`, but not for `metadata-camera-iso` or `-model`

Is it me who is doing something wrong? Or is it a bug or an unsupported behavior?

Thank you for the help!

**Comment by pleerock** [comment]
Hi! No, this use case is not implemented yet. I'll mark this as an enhancement, and will implement it later once more priority features will be done. If you have a time to contribute, feel free to jump in ;)

**Comment by bpatrik** [comment]
Thanks for the quick reply. I'm only using the lib for my home project. But I'll think about implementing this feature :)

**Comment by pleerock** [comment]
recursive embeds are now supported in latest 0.1.0 releases.
