### ISSUE TITLE
Aurora DB unnecessary Alter statement upon connect

### ISSUE THREAD

**Issue by jbamlee** [typeorm/typeorm#2634]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb` / `Aurora`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Every time typeorm connects to an Aurora Database it tries to alter the table, making no alteration. After some investigation, it seems that in the file `MysqlDriver.js` the function `findChangedColumns` return columns where the datatype is `double` and a precision level has not been specified. This is due to the condition `tableColumn.precision !== columnMetadata.precision` in which `columnMetadata.precision`  is `undefined`

This does not seem to affect MySQL databases where it seems to correctly establish a default value of 22 for `columnMetadata.precision`

**Comment by AlexMesser** [comment]
This was fixed in #7517 and will be available in the next release (`0.2.33`).
