### ISSUE TITLE
Question: Using mongodb and sql from the same entity

### ISSUE THREAD

**Issue by simonhoss** [typeorm/typeorm#2636]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[x] `sqlite`
[x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi

I want to use mongodb and sql together with one entity. 

The problem now is that I have to define and ObjectId type for mongodb which is not compatible with sql. Is there some generic primary column field which maps to both?

**Comment by Kononnable** [comment]
You should probably use entity schemas instead of decorator approach.

**Comment by vlapo** [comment]
Entity schema will not help. Right now mongodb and SQL based DBs have different implementation in typeorm (mainly because of `ObjectIdColumn`). So this is no possible now.

**Comment by kraikov** [comment]
Is it now possible to use the same entity for MongoDB and SQLite?

**Comment by xencodes** [comment]
any updates?
