### ISSUE TITLE
Querying json column without query builder in Postgres

### ISSUE THREAD

**Issue by santhan456** [typeorm/typeorm#2637]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

 I have created an entity with a json column in it as below.

```typescript
@Entity()
export class Approvers  {

    @PrimaryGeneratedColumn()
    public id: number;

    @Column('jsonb')
    public approversJson: IApprovers[]
     }
```
```typescript
interface IApprovers{
  approverName: string;
  approverEmployeeCode: string;
  emailAddress: string;
}
```
I am querying table with conditions on json column as below.

```typescript
const query = SELECT * from approvers WHERE approversJson @> '[{"approverEmployeeCode":"SomeEmployeeCode"}]' ;
 const data =  await this.approverRepository.query(query);
 ```

I would like to know if above querying can be done without query builder.

**Comment by Kononnable** [comment]
Did you resolve your issue?

**Comment by vlapo** [comment]
This is not possible without query builder and I do not think we will support this in near future.

**Comment by JayJoshiCoditas** [comment]
@santhan456 Can you help figure out adding a LIKE constraint against the "approverEmployeeCode" field?
