### ISSUE TITLE
DISTINCT in query builder

### ISSUE THREAD

**Issue by dariusmb** [typeorm/typeorm#2641]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

Is there any way to SELECT DISTINCT using query builder?

**Comment by afurculita** [comment]
Why not simply:

```
const applications = await Application.createQueryBuilder("applications")
    .select('DISTINCT applications.id', 'id')
    .addSelect('applications.loan_number', 'loanNumber')
    .addSelect('applicant.id', 'applicantId')
    .addSelect('ass.status', 'signature_status')
    .leftJoin('applications.applicationApplicants', 'applicant')
    .leftJoin('applications.applicationSignatureStatus', 'ass')
    .where("applications.deleted_at = null")
    .orderBy("applications.id", "DESC")
    .limit(4)
    .getRawMany();
```
?

**Comment by gabrielshawandpartners** [comment]
@afurculita The Postgres `DISTINCT ON` behaves a bit different from `DISTINCT` clause, I simplified the query a bit just to post here, but anyway, the same problem happens with `DISTINCT`

**Comment by gabrielshawandpartners** [comment]
I think we could have a `distinct`, like KNEXT does, like:
```
knex('tablename').distinct(knex.raw('ON (column) column'))
.orderBy('column')
.orderBy('another_column');
```

**Comment by exoszajzbuk** [comment]
Same issue here, the `DISTINCT ON` select is not getting placed as the first select => syntax error

**Comment by ollija** [comment]
I made a PR fixing this issue https://github.com/typeorm/typeorm/pull/3065

**Comment by kajalj3098** [comment]
select distinct p.id_company as idCompany
    FROM [dbo].[company_persons] p inner JOIN [dbo].[companies] c ON p.id_company=c.id_company where id_person=${id}

distinct in query builder is not working for me
