### ISSUE TITLE
Mongo boolean value false is transformed to undefined

### ISSUE THREAD

**Issue by singhsoldier13** [typeorm/typeorm#2642]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

`export class Profile {
  @Column()
  last: string;

  @Column()
  first: string;

  @Column()
  middle: string;

  @Column()
  facilityId: string[];

  @Column()
  phoneNumber: string;

  @Column()
  address: string;

  @Column()
  askNewPassword: boolean;

  @Column()
  status: boolean;

  @Column(type => PhysicianDetails)
  physicianDetails: PhysicianDetails | null;

  @Column(type => CalculatorSettings)
  calculatorSettings: CalculatorSettings | null;

  constructor(last: string, first: string, middle: string, facilityId: string[], phoneNumber: string, address: string, askNewPassword: boolean, status: boolean, physicianDetails: PhysicianDetails | null, calculatorSettings: CalculatorSettings | null) {
    this.last = last;
    this.first = first;
    this.middle = middle;
    this.facilityId = facilityId;
    this.phoneNumber = phoneNumber;
    this.address = address;
    this.askNewPassword = askNewPassword;
    this.status = status;
    this.physicianDetails = physicianDetails;
    this.calculatorSettings = calculatorSettings;
  }
}`

`@Entity({name: 'users'})
export class UserDTO {
  @ObjectIdColumn()
  _id: string;

  @Column()
  createdAt: Date;

  @Column()
  services: any; // we don't use these directly. If we start using it, should replace 'any' with schema

  @Column()
  username: string;

  @Column(type => Email)
  emails: Email[];

  @Column(type => Profile)
  profile: Profile;

  @Column()
  roles: string[];

  @Column()
  heartbeat: Date;

  constructor(id: string, createdAt: Date, services: any, username: string, emails: Email[], profile: Profile, roles: string[], heartbeat: Date) {
    this._id = id;
    this.createdAt = createdAt;
    this.services = services;
    this.username = username;
    this.emails = emails;
    this.profile = profile;
    this.roles = roles;
    this.heartbeat = heartbeat;
  }

}`

When I fetch this object via
`const repository = getMongoRepository(UserDTO);
    const user = await repository.findOne({username: 'someusername'});`

The boolean values for 'true' are transformed correctly but 'false' values are transformed to 'undefined'. Please let me know if I am missing something

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by singhsoldier13** [comment]
any update?

**Comment by rustamwin** [comment]
fixed #3900
