### ISSUE TITLE
Weird bug *.reload

### ISSUE THREAD

**Issue by elderapo** [typeorm/typeorm#2643]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```ts
import "reflect-metadata";
import {
  BaseEntity,
  ConnectionOptions,
  createConnection,
  Entity,
  PrimaryGeneratedColumn
} from "typeorm";

@Entity()
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;
}

const options: ConnectionOptions = {
  type: "mysql",
  host: "localhost",
  port: 3306,
  username: "test",
  password: "test",
  database: "test",

  synchronize: true,
  entities: [User]
};

createConnection(options).then(
  async connection => {
    await connection.synchronize(true);

    const user1 = User.create();

    await User.save(user1);

    const user2 = User.create();

    await User.save(user2);

    console.log("user1.id", user1.id); // should print 1 and prints 1
    console.log("user2.id", user2.id); // should print 2 and prints 2

    await user1.reload();
    await user2.reload();

    console.log("-------");

    console.log("user1.id", user1.id); // should print 1 and prints 1
    console.log("user2.id", user2.id); // should print 2 but prints 1 <------ BUG
  },
  error => console.log("Cannot connect: ", error)
);
```

I think it has to do something with `BaseEntity.getId` because it returns undefined.

PS: It works just fine with `typeorm@0.3.0-alpha.7` so I guess it was recently fixed?

**Comment by Kononnable** [comment]
Looks like issue was resolved - I'm nor reproducing it on latest version.
