### ISSUE TITLE
How to properly unit-test repository

### ISSUE THREAD

**Issue by oeddyo** [typeorm/typeorm#2644]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi there,

I'm gonna make my question as specific as possible. 

Say we have 1 model called User, and we have a normal method findBySessionToken which retrieves db and find the user with a UUID sessionToken. 

I started with Data Mapper pattern since it seems unit-test should be easier. But it turned out it's not with typeorm. 

The file structure is like
src
 - models/
 - services/
 - controllers/

models is where I keep user model. /services is where I keep repositories. for instance:
```
@EntityRepository(User)
export class UserRepository extends Repository<User> {
  findBySessionToken = (sessionToken: string) => {
    return this.createQueryBuilder("user")
      .where("user.sessionToken = :sessionToken", { sessionToken })
      .getOne()
  }
}
```

I have a unit-test for this findBySessionToken function in /services. 
This is all good and in /controller I use Express, which takes advantage of the function above

```
export class UserController {
  static getMe = async (req, res) => {
    // validate
    const sessionToken = req.get("sessionToken") as string
    console.log("sessionToken from header = ", sessionToken)
    if (!sessionToken) {
      throw Error("Invalid session. Please login first")
    }
    const userRepository = getCustomRepository(UserRepository)
    const me = await userRepository.findBySessionToken(sessionToken)
    return res.json(me)
  }
}
```

And here it gets tricky. In the unit-test I have for this controller, I'd like to mock what "userRepository.findBySessionToken" returns. Because it's unit-tested in /services already, I don't like to test it once again in /controllers. 

I tried to Sinon.stub it, but it still needs me to initialize db connection because I need to do
userRepository = getCustomRepository(UserRepository)
in beforeEach

On the other hand, unit-testing for Active Record is way easier. I could just do 
sandbox.stub(User, "findBySessionToken").returns(Promise.resolve({ "marco": "polo" }))

My question is, how do I stub data mapper pattern easier?

Code I use:
```
import { expect } from "chai"
import { UserController } from "./index"
import * as sinon from "sinon"
// unit test express route
// http://www.sheshbabu.com/posts/unit-testing-express-route-handlers/
import httpMocks = require("node-mocks-http")
//import { getCustomRepository } from "typeorm"
//import { UserRepository } from "../../services/user"
//const userController = new UserController()
import { User } from "../../models/user"
describe("UserController", () => {
  let sandbox: sinon.SinonSandbox
  //let userRepository: UserRepository
  beforeEach((done) => {
    (
      async () => {
        sandbox = sinon.sandbox.create()
        console.log("in constructor")
        //userRepository = getCustomRepository(UserRepository)
        done()
      }
    )()
  })
  it("should return 'hello world' for GET /example", (done) => {
    (
      async () => {
        console.log("ready here")

        //sandbox.stub(userRepository, "findBySessionToken").returns(Promise.resolve({"marco": "polo"}))
        sandbox.stub(User, "findBySessionToken").returns(Promise.resolve({ "marco": "polo" }))

        const mockRequest = httpMocks.createRequest({
          method: "GET",
          url: "/users/me",
          headers: {
            sessionToken: "abc"
          }
        })
        const mockResponse = httpMocks.createResponse()
        await UserController.getMe(mockRequest, mockResponse)
        //userController.getMe(mockRequest, mockResponse)
        const actualResponseBody = mockResponse._getData()
        const expectedResponseBody = "hello world!"
        console.log("actual = ", actualResponseBody)
        expect(actualResponseBody).to.eqls(expectedResponseBody)
      })()
  })
})
```

**Comment by bartlomiej-korpus** [comment]
You could inject the repository into the controller constructor using DI pattern(something like typedi, awilix). Then you would mock the repository in your tests and inject the mock.

**Comment by Kononnable** [comment]
Looks like issue was resolved.

**Comment by RaghunathVadlakonda** [comment]
Hi,
I'm facing the same problem - mocking the repository
may I know the solution for this.
How I can mock the typeorm repositories in unit test.

**Comment by JamieCorkhill** [comment]
@RaghunathVadlakonda like @Kononnable said, inject the Repository into the Controller with Awilix, TypeDI, or Inversify, etc.

This is known as Inversion of Control and will permit you to pass a mocked repository into the constructor.

**Comment by adico1** [comment]
The title say unit test the repository when the solution presents how to unit test the controller.

So i'm putting this link here which show how to test the repository as well
https://github.com/YegorZaremba/typeorm-mock-unit-testing-example
