### ISSUE TITLE
Custom CLI command implementation

### ISSUE THREAD

**Issue by andrew-yustyk** [typeorm/typeorm#2645]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

As far as I understand, typeorm does not provide functionality for the data fixtures. Developers should implement this functionality by themselves if it's required. 

I want to do this using custom CLI command, but i didn't find any docs for the custom commands implementation.

Is it possible to extend an existing set of commands?

**Comment by RobinCK** [comment]
You might like my implementation 
https://github.com/RobinCK/typeorm-fixtures
I am still working on the functionality.

**Comment by pleerock** [comment]
@RobinCK looks cool! 

Right now recommended typeorm's way to create fixtures is to use migrations. Maybe in the future we'll introduce some other way, but this probably needs to be done as a separate package just like what @RobinCK did. If someone wants to make it official package it should cover all use cases and be implemented completely - please feel free to create separate dedicated github issue.
