### ISSUE TITLE
[Question] Is it possible to bind Subscribers to Angular's DI system?

### ISSUE THREAD

**Issue by JeongJun-Lee** [typeorm/typeorm#2647]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I tried to bind Subscriber to Angular DI like code below. But it look like not working, because this.auditsProv is always Undefined. If it's not impossible, should I have to use another DI for Subscribers like TypeDI(https://github.com/typeorm/typeorm-typedi-extensions)?

[post-subs.ts]
```typescript
import { Injectable } from '@angular/core';
import { EventSubscriber, EntitySubscriberInterface, InsertEvent } from "typeorm";
import { AuditsProvider } from '../providers/audits/audits';

@Injectable()
@EventSubscriber()
export class PostSubscriber implements EntitySubscriberInterface {

  constructor(private auditsProv: AuditsProvider) {
    console.log(this.auditsProv);
  }

  /**
   * Called before entity insertion.
   */
  beforeInsert(event: InsertEvent<any>) {
    console.log(`BEFORE ENTITY INSERTED: `, event.entity);
    this.auditsProv.save();
  }

}
```

[app.module.ts]
```typescript
@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    AuditsProvider,
    PostSubscriber
  ]
})
export class AppModule {}
```

**Comment by Kononnable** [comment]
Did you resolve your issue?

**Comment by vlapo** [comment]
I do not think we have any possible way to register subscriber instance in typeorm.
