### ISSUE TITLE
findAll method to find all article of an user

### ISSUE THREAD

**Issue by pirmax** [typeorm/typeorm#2649]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want find all articles of one user.

On Sequelize, I have this:

```
async findAllByUser(userUuid: string, findOptions: object): Promise<Article[]> {
    return await Article.findAll<Article>({
        include: [{
            model: User,
            where: {
                uuid: userUuid
            }
        }]
    });
}
```

I want an alternative for TypeORM.

**Comment by Kononnable** [comment]
Did you resolve your issue?

**Comment by vlapo** [comment]
In this case you have to use query builder http://typeorm.io/#/select-query-builder/joining-relations.
