### ISSUE TITLE
Typescript Error on Importing Lodash

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#265]
/Users/jmurphy/projects/ubq/api/node_modules/@types/lodash/index.d.ts
Error:(19449, 15) TS2428:All declarations of 'WeakMap' must have identical type parameters.

I'm fairly confident this is a lodash issue, but it was brought in as a dependency of TypeORM. 

Any advice?

**Comment by rightisleft** [comment]
Sorry - looks to be an issue here:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14324

Adding `"skipLibCheck": true, ` to tsconfig.json worked well in WebStorm

**Comment by pleerock** [comment]
Hi, nope lodash is not a dependency of typeorm. Looks like someone else bring it you there.

**Comment by rightisleft** [comment]
So i just checked out MASTER and when i go through the DEVELOPER.MD guide i get:

➜  typeorm git:(master) ✗
➜  typeorm git:(master) ✗ pwd
/Users/jmurphy/projects/jack/typeorm
➜  typeorm git:(master) ✗ gulp package
[16:40:51] Requiring external module ts-node/register
[16:40:55] Using gulpfile ~/projects/jack/typeorm/gulpfile.ts
[16:40:55] Starting 'package'...
[16:40:55] Starting 'clean'...
[16:40:55] Finished 'clean' after 6.24 ms
[16:40:55] Starting 'packageCompile'...
node_modules/@types/lodash/index.d.ts(21027,11): error TS2428: All declarations of 'WeakMap' must have identical type parameters.
[16:41:01] TypeScript: 1 semantic error
[16:41:01] TypeScript: emit succeeded (with errors)
[16:41:01] Finished 'packageCompile' after 6.15 s
[16:41:01] Starting 'packageMoveCompiledFiles'...
[16:41:01] Finished 'packageMoveCompiledFiles' after 6.88 ms
[16:41:01] Starting 'packageClearCompileDirectory'...
[16:41:01] Finished 'packageClearCompileDirectory' after 1.27 ms
[16:41:01] Starting 'packagePreparePackageFile'...
[16:41:01] Starting 'packageReadmeFile'...
[16:41:01] Starting 'copyTypingsFile'...
[16:41:01] Finished 'copyTypingsFile' after 9.14 ms
[16:41:01] Finished 'packagePreparePackageFile' after 26 ms
[16:41:01] Finished 'packageReadmeFile' after 22 ms
[16:41:01] Finished 'package' after 6.19 s

**Comment by pleerock** [comment]
probably you should remove `node_modules` and run `npm i` again

**Comment by pleerock** [comment]
have you fix your issue?

**Comment by MalinGunasekara** [comment]
I'm getting this Error from TypeScript TypeScript compiler failed with exit code 1.

I have did try your solution remove `node_modules` and run `npm i` but after `tns run ios` again same Error popping up.. Any Solutions ...??? 

Thank you...

"dependencies": {
    "@types/lodash": "^4.14.39",
    "lodash": "^4.17.2",
  },


node_modules/@types/lodash/index.d.ts(19507,15): error TS2428: All declarations of 'WeakMap' must have identical type parameters.

node_modules/@types/node/index.d.ts(38,11): error TS2300: Duplicate identifier 'MapConstructor'.

node_modules/@types/node/index.d.ts(40,11): error TS2300: Duplicate identifier 'SetConstructor'.
node_modules/@types/node/index.d.ts(50,14): error TS2687: All declarations of 'iterator' must have identical modifiers.
node_modules/@types/node/index.d.ts(60,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'global' must be of type 'any', but here has type 'Global'.

node_modules/@types/node/index.d.ts(84,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NativeScriptRequire', but here has type 'NodeRequire'.

node_modules/@types/node/index.d.ts(96,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'module' must be of type 'NativeScriptModule', but here has type 'NodeModule'.
node_modules/@types/node/index.d.ts(4091,5): error TS2309: An export assignment cannot be used in a module with other exported elements.

node_modules/tns-core-modules/declarations.d.ts(3,15): error TS2300: Duplicate identifier 'Request'.

node_modules/tns-core-modules/declarations.d.ts(17,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'any', but here has type 'string[] | Headers | { [index: string]: string; }'.
node_modules/tns-core-modules/declarations.d.ts(19,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'mode' must be of type 'string', but here has type 'RequestMode'.
node_modules/tns-core-modules/declarations.d.ts(20,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'credentials' must be of type 'string', but here has type 'RequestCredentials'.
node_modules/tns-core-modules/declarations.d.ts(21,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cache' must be of type 'string', but here has type 'RequestCache'.

node_modules/tns-core-modules/declarations.d.ts(36,15): error TS2300: Duplicate identifier 'Headers'.
node_modules/tns-core-modules/declarations.d.ts(46,5): error TS2687: All declarations of 'bodyUsed' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(56,15): error TS2300: Duplicate identifier 'Response'.
node_modules/tns-core-modules/declarations.d.ts(72,5): error TS2687: All declarations of 'status' must have identical modifiers.

node_modules/tns-core-modules/declarations.d.ts(73,5): error TS2687: All declarations of 'statusText' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(74,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'any', but here has type 'HeaderInit'.

node_modules/tns-core-modules/declarations.d.ts(74,5): error TS2687: All declarations of 'headers' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(78,14): error TS2300: Duplicate identifier 'BodyInit'.

node_modules/tns-core-modules/declarations.d.ts(79,14): error TS2300: Duplicate identifier 'RequestInfo'.
node_modules/tns-core-modules/es-collections.d.ts(30,14): error TS2300: Duplicate identifier 'MapConstructor'.

node_modules/tns-core-modules/es-collections.d.ts(31,14): error TS2300: Duplicate identifier 'SetConstructor'.
node_modules/tns-core-modules/es6.d.ts(9,5): error TS2687: All declarations of 'iterator' must have identical modifiers.

node_modules/typescript/lib/lib.d.ts(5327,5): error TS2687: All declarations of 'status' must have identical modifiers.

node_modules/typescript/lib/lib.d.ts(5328,5): error TS2687: All declarations of 'statusText' must have identical modifiers.
node_modules/typescript/lib/lib.d.ts(5329,5): error TS2687: All declarations of 'headers' must have identical modifiers.
node_modules/typescript/lib/lib.d.ts(11168,11): error TS2300: Duplicate identifier 'Headers'.
node_modules/typescript/lib/lib.d.ts(11177,13): error TS2300: Duplicate identifier 'Headers'.
node_modules/typescript/lib/lib.d.ts(13566,11): error TS2300: Duplicate identifier 'Request'.
node_modules/typescript/lib/lib.d.ts(13583,13): error TS2300: Duplicate identifier 'Request'.
node_modules/typescript/lib/lib.d.ts(13588,11): error TS2300: Duplicate identifier 'Response'.

node_modules/typescript/lib/lib.d.ts(13599,13): error TS2300: Duplicate identifier 'Response'.
node_modules/typescript/lib/lib.d.ts(17714,14): error TS2687: All declarations of 'bodyUsed' must have identical modifiers.
node_modules/typescript/lib/lib.d.ts(19121,6): error TS2300: Duplicate identifier 'BodyInit'.

node_modules/typescript/lib/lib.d.ts(19152,6): error TS2300: Duplicate identifier 'RequestInfo'.

TypeScript compiler failed with exit code 1

**Comment by pleerock** [comment]
@MalinGunasekara are you using typeorm, or something else bring you there?

**Comment by MalinGunasekara** [comment]
I don't think so. I'm not using any ORMs  on the app @pleerock

**Comment by pleerock** [comment]
then probably you are reporting your issue in a wrong repository?

**Comment by pleerock** [comment]
Im closing this issue. @MalinGunasekara you probably need to report your issue in nativescript repository
