### ISSUE TITLE
URL string parser warning on MongoDB

### ISSUE THREAD

**Issue by fandy** [typeorm/typeorm#2650]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm getting an error when setting up MongoDB using a next.js + micro server:

```
// Node.js does not support ES6 imports/exports nicely: https://nodejs.org/api/esm.html

const {createConnection} = require('typeorm') 
const {parse} = require('url')
const match = require('micro-route/match')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'

const app = next({dev})
const handle = app.getRequestHandler()

async function main(req, res) {
  const parsedUrl = parse(req.url, true)
  const {query} = parsedUrl

  switch (match(req)) {
    case '/':
      return app.render(req, res, '/index', query)
      break;
  }

  return handle(req, res, parsedUrl)
}

async function setup(handler) {
  await app.prepare()

  await createConnection({
    type: 'mongodb',
    host: 'localhost',
    port: 27017,
    database: 'test'
  })

  return handler
}

module.exports = setup(main)
```

Error:
```
(node:55873) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlPars
er: true } to MongoClient.connect.
```

**Comment by vlapo** [comment]
TypeORM do not know which version of mongo client library you are using, so we cannot force `useNewUrlPars: true` by default (there are several issues with new url parser in oldest versions of mongo client library).
You have to add option to your connection configuration.

```typescript
await createConnection({
    type: 'mongodb',
    host: 'localhost',
    port: 27017,
    database: 'test',
    useNewUrlPars: true
  })
```
