### ISSUE TITLE
getMany returning less than getCount

### ISSUE THREAD

**Issue by ToonvanStrijp** [typeorm/typeorm#2653]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

So I'm using this query:

```
this.agendaItemRepository
      .createQueryBuilder('agendaItem')
      .innerJoin('agendaItem.answers', 'answer')
      .innerJoin('answer.schedule', 'schedule')
      .leftJoinAndSelect('agendaItem.subject', 'subject')
      .addSelect(
        '(SELECT t2.slug FROM subject t2 WHERE t2.lft <= subject.lft AND t2.rgt >= subject.rgt ' +
          'AND t2.depth = 1 LIMIT 1)',
        'subject_slug',
      )
      .where('answer.userId = :id', { id: studentId })
      .andWhere('schedule.startDate >= :startDate', {
        startDate: startDate.format('YYYY-MM-DD HH:mm:ss'),
      })
      .andWhere('schedule.endDate <= :endDate', {
        endDate: endDate.format('YYYY-MM-DD HH:mm:ss'),
      })
      .addSelect('schedule.startDate', 'agendaItem_startDate')
      .addSelect('schedule.endDate', 'agendaItem_endDate')
      .getMany();
```

This query returns 3 results, but the `getCount` returns value 4. I guess this is because `TypeORM` is filtering the results on the primary key right? But is there an option to avoid this? I saw the `getRawMany` but this won't format my result into classes and map the values to the right properties.

So my question is if there is a way to get all 4 results just by using the `getMany`?

**Comment by Kononnable** [comment]
Did you resolve your issue?
If not we probably need more data to reproduce the issue and find out what is wrong.

**Comment by Kononnable** [comment]
Closing as no response from the author.
