### ISSUE TITLE
Cache identifier

### ISSUE THREAD

**Issue by DarkInsight85** [typeorm/typeorm#2656]
**Issue type:**

[x ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

>     const configuration: UserConfiguration = await getManager().getRepository(UserConfiguration)
>      .findOne({
>        cache: CONSTANTS.CACHE_DURATION,
>        where: { CIN: CIN }
>      });

Using the example above, I found out that the same cached result is returned for different CIN I passed in, which is not the behaviour I want. Is it possible to retain the caching functionality but gives correct result basd on different CIN?

**Comment by lili21** [comment]
same issue here. Docs should declare the cache mechanism, what identify the cache ?

**Comment by kateile** [comment]
Late reply! You should use id to pass unique id for different CIN so that they wont interfere with each other like this.
```
      cache: {
        id: `${UNIQUE_CACHE_ID}:${primaryKey}`,
        milliseconds: 180000
      }
```

**Comment by imnotjames** [comment]
Looks like this was answered.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
