### ISSUE TITLE
cascadeRelations Entity

### ISSUE THREAD

**Issue by MaxDesplanches** [typeorm/typeorm#2659]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello,

I encounter a problem on save on postgres for link between three tables in cascade.

I have an Entity "Freelance" base on base Entity, with a link to account:
```
  @OneToOne(type => AccountEntity, {
    cascade: ['update'],
    eager: true,
    nullable: false,
    onDelete: 'CASCADE',
  })
  @JoinColumn()
  public account: AccountEntity;
```

The account detail is linked successfully. Otherwise, I have in account:

```
  @OneToOne(type => MediaEntity, {
    eager: true,
    cascade: true,
    nullable: true,
    onDelete: 'SET NULL',
  })
  @JoinColumn()
  public profilePicture?: MediaEntity;
``` 

this media exists in postgres, but the id is not set in account on column 

"profilPictureId".

I check the source code, and I found in node_modules/typeorm/persistence/subject-builder/CascadesSubjectBuilder.js

on line 25:

```
subject.metadata
           .extractRelationValuesFromEntity(subject.entity, subject.metadata.relations) // todo: we can create EntityMetadata.cascadeRelations
           .forEach(function (_a) {
```

It doesn't go in forearch, and it is in this case that the id is not saved. I saw a "todo" comment, maybe this part is not done yet ? I am in version 0.2.6.
```
    "typeorm": "^0.2.6",
```

Do you have any idea ? It is not possible in this version ?
Thanks in advance,

Max.

**Comment by imnotjames** [comment]
Cascades happen in database now, so this is no longer relevant.
