### ISSUE TITLE
Using migrations without ormconfig.json?

### ISSUE THREAD

**Issue by mildfuzz** [typeorm/typeorm#266]
I have been following [these](https://typeorm.github.io/migrations.html) docs on how to manage migrations.

I am not using an ormconfig.json, I am passing my config as a JS object in my code. The docs seem to suggest this is okay (the config object is not valid JSON, so one assumes that is lives in code base somewhere)

I am getting this error when trying to run my migrations (from the migrations folder, from the folder with the db config in and from the root folder)

![image](https://cloud.githubusercontent.com/assets/196705/22713491/946af4ce-ed80-11e6-80dd-97a77ec262b1.png)

**Comment by pleerock** [comment]
do you have a package.json in your project? You can checkout [this](https://github.com/typeorm/typescript-example) example and see if migrations work there for you.

**Comment by mildfuzz** [comment]
Must have had a silly mistake. Listed that ormconfig and adapted it and it's working.
