### ISSUE TITLE
typeorm nestjs and oracle connect ques

### ISSUE THREAD

**Issue by zhouyu94** [typeorm/typeorm#2670]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ X] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to use oracledb and i config this:
ormconfig.json
{
    "skip": true,
    "name": "oracle",
    "type": "oracle",
    "host": "ip",
    "username": "name",
    "password": "XXXX",
    "database": "XXXX",
    "port": 1521,
    "sid": "xe",
    "logging": false
}
but, report a Error:
Error: Cannot find connection default because its not defined in any orm configuration files.

and  what should i do to fix this.
thx ^-^...

**Comment by JoshWilliams92** [comment]
Hi, I was having issues trying to establish a connection in the thread:
Unable to connect to Oracle database via TypeORM #5462

I managed to resolve the issue by changing the import code to:

TypeOrmModule.forRoot({
type: 'oracle',
username: '',
password: '',
connectString: 'host-name-of-datbase:port-number/name-of-database',
entities: [],
synchronize: true,

This convention follows the guideline of the main node oracle db driver implementation.
Please see below the link and the connect guidelines.

https://oracle.github.io/node-oracledb/doc/api.html#getstarted
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
// myscript.js
// This example uses Node 8's async/await syntax.

const oracledb = require('oracledb');

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;

const mypw = ... // set mypw to the hr schema password

async function run() {

let connection;

try {
connection = await oracledb.getConnection( {
user : "hr",
password : mypw,
connectString : "localhost/XEPDB1"
});

const result = await connection.execute(
  `SELECT manager_id, department_id, department_name
   FROM departments
   WHERE manager_id = :id`,
  [103],  // bind value for :id
);
console.log(result.rows);
} catch (err) {
console.error(err);
} finally {
if (connection) {
try {
await connection.close();
} catch (err) {
console.error(err);
}
}
}
}

run();
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
