### ISSUE TITLE
Error when saving entity,

### ISSUE THREAD

**Issue by cuneytbetik** [typeorm/typeorm#2677]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Here is my model:
```
    @Entity()
    export class Issue {

    @PrimaryGeneratedColumn()
    public _id: ObjectID;

    @Column()
    public title: string;

    @Column()
    public responsible: string;

    @Column()
    public description: string;

    @Column()
    public severity: string;
    }
```

Here is my code:

```
public async update(issue: Issue): Promise<Issue> {
        const connection = await DatabaseProvider.getConnection();
        const repo = connection.getRepository(Issue);
        const entity = await repo.findOne(issue._id);
        entity.title = issue.title;
        entity.responsible = issue.responsible;
        entity.description = issue.description;
        entity.severity = issue.severity;
        return await repo.save(entity);
  }
```
but throwing error like this "TypeError: Cannot read property 'propertyName' of undefined" . I tried , "entity" variable isn't null. But when saving it is throwing that error.

**Comment by cuneytbetik** [comment]
I found it. "_id" column decorator should be ObjectIdColumn.

**Comment by fatihaziz** [comment]
Thank you so much!
