### ISSUE TITLE
Purpose of Relations in FindOne

### ISSUE THREAD

**Issue by zWaR** [typeorm/typeorm#2679]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi,

The example here: https://github.com/typeorm/typeorm#creating-a-many-to-many-relation includes the following snippet:

```ts
const loadedPhoto = await connection
    .getRepository(Photo)
    .findOne(1, { relations: ["albums"] });
```

Why is `relations` needed in `findOne` in this case? I am wondering, because the ManyToMany relationship between the entities Photo and Album has already been defined in the entities, why is it repeated on the query?

Thanks

**Comment by aaronstaves** [comment]
`relations` isn't _defining_ the relationship.  As you stated, that's already done in the entity itself.  When added to [find optinos](http://typeorm.io/#/find-options/basic-options), `relations` will also prefetch and populate that relation on the returned Entity.

Without adding it, `loadedPhoto` is just a Photo entity.  

```
{
    id: 1,
    name: "Me and Bears",
    description: "I am near polar bears",
    filename: "photo-with-bears.jpg"
}
```
Adding `relations` to the query, will return `loadedPhoto` as a Photo entity, as well as `loadedPhoto.albums` will be an array of albums belonging to that photo.

```
{
    id: 1,
    name: "Me and Bears",
    description: "I am near polar bears",
    filename: "photo-with-bears.jpg",
    albums: [{
        id: 1,
        name: "Bears"
    }, {
        id: 2,
        name: "Me"
    }]
}
```

**Comment by Usama-Tahir** [comment]
how can I retrieve foreign key also by this method?
