### ISSUE TITLE
[Question, possible issue] Can I use .update() on data returned by a QB with a partial field selection?

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#2683]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

For performance reasons, I would like to use a query builder, followed by repository.update() call. However, it appears that update() can break in this scenario?

E.g.

 let data = repository
                        .createQueryBuilder("ac")
                        .select(["ac.id", "ac.fieldToEdit"])
                        .where("ac.sId = :sId", { sId: s.id })
                        .andWhere("ac.status = :status", { status: AffiliateCodeStatus.Active })
                        .andWhere("ac.pId = :pId", { pId: p.id })
                        .andWhere("ac.aId IN (:...aIds)", { aIds: affected.map(x => x.id) })

then... manipulate some of the data,

then.... data.forEach(x => repository.update(x).

When I ran this code as an experiment, update blanked out the columns that were not returned by the QB. Is this correct behaviour? It would be nice for perf reasons if this scenario was supported by the update api.

**Comment by imnotjames** [comment]
Is this still the case?  I cannot replicate it anymore.
