### ISSUE TITLE
QueryFailedError: TimeoutError: ResourceRequest timed out

### ISSUE THREAD

**Issue by kgrvr** [typeorm/typeorm#2684]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest` (^0.2.7)
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello, I'm using **NestJS** on node for handling APIs and **MSSQL** as a database in my project. I'm sending a GET request to my APIs.

The problem I'm facing is I'm getting error:
`QueryFailedError: TimeoutError: ResourceRequest timed out`

The error logged in my API is as following:

    {
       "timestamp":"2018-08-20T07:35:53.085Z",
       "context":"AppExceptionFilter",
       "level":"error",
       "message":{
          "exception":{
             "stack":"QueryFailedError: TimeoutError: ResourceRequest timed out\n    at new QueryFailedError (My\\Project\\Path\\src\\error\\QueryFailedError.ts:7:9)\n    at My\\Project\\Path\\src\\driver\\sqlserver\\SqlServerQueryRunner.ts:209:37\n    at _query (My\\Project\\Path\\node_modules\\mssql\\lib\\base.js:1253:25)\n    at parent.acquire (My\\Project\\Path\\node_modules\\mssql\\lib\\tedious.js:555:25)\n    at <anonymous>",
             "message":"TimeoutError: ResourceRequest timed out",
             "name":"QueryFailedError",
             "query":"SELECT \"MyTable\".\"Id\" AS \"MyTable_Id\", \"MyTable\".\"A\" AS \"B\", \"MyTable\".\"C\" AS \"MyTable_C\", \"MyTable\".\"D\" AS \"MyTable_D\", \"MyTable\".\"E\" AS \"MyTable_E\", \"MyTable\".\"F\" AS \"MyTable_F\", \"MyTable\".\"G\" AS \"MyTable_G\", \"MyTable\".\"H\" AS \"MyTable_H\", \"MyTable\".\"I\" AS \"MyTable_I\", \"MyTable\".\"J\" AS \"MyTable_J\", \"MyTable\".\"K\" AS \"MyTable_K\", \"MyTable\".\"L\" AS \"MyTable_L\", \"MyTable\".\"M\" AS \"MyTable_M\", \"MyTable\".\"N\" AS \"MyTable_N\", \"MyTable\".\"O\" AS \"MyTable_O\", \"MyTable\".\"P\" AS \"MyTable_P\", \"MyTable\".\"Q\" AS \"MyTable_Q\", \"MyTable\".\"R\" AS \"MyTable_R\", \"MyTable\".\"S\" AS \"MyTable_S\", \"MyTable\".\"T\" AS \"MyTable_T\", \"MyTable\".\"U\" AS \"MyTable_U\", \"MyTable\".\"V\" AS \"MyTable_V\" FROM \"MyTable\" \"MyTable\" WHERE K = @0 ORDER BY Id DESC OFFSET 0 ROWS FETCH NEXT 13 ROWS ONLY",
             "parameters":[
                0
             ]
          },
          "request":{
             "headers":{
                "host":"localhost:3000",
                "connection":"keep-alive",
                "accept":"application/json, text/plain, */*",
                "origin":"http://localhost:4200",
                "authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MSwiaWF0IjoxNTM0NzQ1OTM2LCJleHAiOjMzMDc0NzQ1OTM2fQ.1oRWumndS5vDxGMBRVEHrNtLWlWZY4CZtALH8P7wNiE",
                "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
                "dnt":"1",
                "referer":"http://localhost:4200/home",
                "accept-encoding":"gzip, deflate, br",
                "accept-language":"en-US,en;q=0.9,hi;q=0.8",
                "if-none-match":"W/\"2150-9fHM7fYjDZMhuDbesi5ysbZ+OnM\""
             },
             "body":{
    
             },
             "route":{
                "path":"/home",
                "stack":[
                   {
                      "name":"<anonymous>",
                      "keys":[
    
                      ],
                      "regexp":{
                         "fast_star":false,
                         "fast_slash":false
                      },
                      "method":"get"
                   }
                ],
                "methods":{
                   "get":true
                }
             },
             "params":{
    
             },
             "query":{
                "size":"13",
                "page":"0",
                "search":""
             }
          },
          "status":500
       }
    }

This error occurs after this code:

    const result = await queryBuilder.getManyAndCount();

The error is very random and don't show any pattern. I've also tried following solutions described in these threads:

https://github.com/sequelize/sequelize/issues/7884
https://github.com/tediousjs/node-mssql/issues/610

But it didn't resolved my issue. Please help.

**Comment by Kononnable** [comment]
Either your query:
- was returning a lot of data and hydrating it took a lot of time,
- was very complicated and fetching data from db took a lot of time
- was blocked by transaction.
In theory it could also be some dependency problem, but I don't recall many people reporting such problems so I bet it's one of options I mentioned earlier.

Closing as issue is long overdue. If it's still happening to you let me know.

**Comment by ikenami** [comment]
It is still happening.

In my case I am also using NestJS, but with PostgreSQL. It happens when I receive a postback on my endpoint and use the request data to update my database.

It temporarily updates the DB (for long enough that when my Front-End makes a request to the API, it serves the updated data), but then since the query timedout the DB rollsback to the previous stage. And the updated data is gone. ):

My query is a simple `UPDATE` so it makes no sense be one of these:

> - was returning a lot of data and hydrating it took a lot of time,
> - was very complicated and fetching data from db took a lot of time

Maybe it's a dependency problem since when I do the `UPDATE` it also has to create a instance on another table.

For example: I have a `human` and a `pet` table. The `human` table has a `pet` reference by `pet_id`.
So when I `UPDATE` my `human` to add the `human.pet`, it has to create a new `pet` and reference its `id`

That's when my query fails cuz of timeout :thinking:

**Comment by kgrvr** [comment]
@Kononnable @ikenami
Yes. It is still happening in the Production environment of my Enterprise Grade application.

I guess this is due to somewhat related to memory leakage in the pool connection provider. I can tell this due to one pattern that I noted in my application logs. 

After every 4-5 days of continuous usage, all of a sudden all the requests to my APIs start getting Resource Timeout exception. Even simple sign-in request fails.
Then I have to restart my server to fix this. After restarting, it again goes to normal.

My application is hosted on Azure VM and the database is on Azure Data Platform.

**Comment by vlapo** [comment]
@kgrvr Underlying mssql driver had some problems with closing idle connections in pool. It occurs on node >=10. If it is your case try update mssql driver:
```
"mssql": "^4.3.1",
```

**Comment by kgrvr** [comment]
@vlapo 
Following are the versions being used:
Node version: 8.15.0
TypeORM: 0.2.7
mssql: 4.1.0

Updating these will fix the issues I'm facing?

**Comment by Kononnable** [comment]
@kgrvr 
If might fix, it might not - depending on if this problem is really on what @vlapo described. Only You can tell if this helped in your case.

@ikenami 
I'm not sure what you mean by temporary update - if it's done in transaction other queries(frontend request) shouldn't have access to changed data(untill transaction is committed). If this is done without transaction there shouldn't be a rollback(unless you're manually reverting the changes).

**Comment by vlapo** [comment]
@kgrvr I faced this issue only on node 10+ so it is really small chance. But updating node version and lib dependencies could resolve your issue anyway.
