### ISSUE TITLE
question backup mysql

### ISSUE THREAD

**Issue by Paul75** [typeorm/typeorm#2685]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello,

Only want to backup all the databases. When I can do it ?

Thanks

**Comment by Bessonov** [comment]
Sure: https://dev.mysql.com/doc/refman/5.7/en/mysqldump-sql-format.html

**Comment by Paul75** [comment]
sur but the client mysql must be installed into the server that have script ...

**Comment by Bessonov** [comment]
No, you can use it from anywhere you can connect to the DB.

Backups are out of scope of an ORM. Really.
