### ISSUE TITLE
Postgresql primary id generation not working if id is not called "id"

### ISSUE THREAD

**Issue by SebastianMetzger** [typeorm/typeorm#269]
Thank you for creating this library, it looks really awesome. We are considering using it in production for our current project.

We unfortunately found an issue:
How to reproduce:
```
@PrimaryColumn('integer', { generated: true })
  public question_id: number;
```

This will generate a buggy SQL CREATE statement with two ids:
```
CREATE TABLE public.snapaddy_question
(
  question_id integer NOT NULL DEFAULT nextval('snapaddy_question_id_seq'::regclass),
  question_id integer NOT NULL DEFAULT nextval('snapaddy_question_id_seq'::regclass),
  ...
}
```
The effect is random id already exists errors when inserting something into the table. Somehow always on the second and third time you try to insert something, but I don't know why.

Quick fix: Rename id field to just "id":
```
@PrimaryColumn('integer', { generated: true })
  public id: number;
```

Not a real big issue once you know it, but the primary columns should be called something else than "id" as well.

**Comment by pleerock** [comment]
This issue is not relevant in latest versions.
