### ISSUE TITLE
Option to run migrations in 1-transaction-per-migration mode

### ISSUE THREAD

**Issue by alexturek** [typeorm/typeorm#2693]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest` (0.2.7)

**Steps to reproduce or a small repository showing the problem:**

I just had a specific issue when running migrations (on my local DB, not against a production system), where running all migrations in a single transaction caused them all to fail. What I ran into was that I was running

1. <early timestamp> create table `foo`
2. <later timestamp> `insert into foo values ...`

The CLI output showed the create-table migration succeeding, and then insert-data failed with "no such relationship `tablename`"

I was able to fix this with `-t=false` (from #1408). But my ideal solution would run these migrations transactionally, just one transaction-per-migration. Some of this is my expectation from other ORM libraries I've used, where migrations always happen outside a transaction (bad), but at least if the last migration fails, the earlier ones have succeeded.

So my suggestion (not sure of the interface) is to add this third option:

1. (default, existing) Run all migrations inside a transaction. I assume this really only works for schema-change-in-transaction databases.
2. (existing) Run all migrations outside of a transaction. Just no `BEGIN` statements that the user doesn't specify. Solved with `typeorm migration:run -t=false`
3. (new) Run each migration inside a transaction. This will avoid partially applied migrations, but also let us lock in progress, so that it doesn't matter if users run all migrations at once, or one every day.

I can see the arguments both ways here. I'm just wondering if you'd be amenable to adding the third option. Also I'm not sure of the best interface, since it seems like `-t` is already a boolean flag, and I'm not sure I'd want a trilean option 😄

**Comment by Diluka** [comment]
> (new) Run each migration inside a transaction. This will avoid partially applied migrations, but also let us lock in progress, so that it doesn't matter if users run all migrations at once, or one every day.

I have encountered this situation
If defined a key too long the migration will break database structure

**Comment by kodayashi** [comment]
I just hit this too. In short I was migrating schema in migration 1 and seeding in migration 2. Running them one at a time worked, but `-t=false` allowed me to run them all in one `migration:run`. Nice find @alexturek.

**Comment by opensas** [comment]
> I just hit this too. In short I was migrating schema in migration 1 and seeding data (inserting) in migration 2. Running them one at a time worked, but `-t=false` allowed me to run them all in one `migration:run`. Nice find @alexturek.

How did you manage to run them one at a time? I am looking for an option like that, to allow me to run only the next 'n' transactions, something like `typeorm migrations:run --limit=1` is there something like that available?

**Comment by imnotjames** [comment]
Each migration is wrapped in a transaction now by default.  Closing this out.

**Comment by ekzyis** [comment]
> Each migration is wrapped in a transaction now by default. Closing this out.

Uhm, this does not seem to be the case for typeORM v7.1.0.

When running my migrations, there is only a single "START TRANSACTION" and "COMMIT" statement.

I will upgrade my typeORM version and see if this is still the case.

**Comment by alexisvisco** [comment]
@ekzyis Hey, I just found how to do it: in your configuration, you can set: `migrationsTransactionMode: "each",` and it will execute your migrations in one transaction one by one :)

**Comment by ekzyis** [comment]
Wow, thanks, will try this out tomorrow :) Thanks for letting me know

**Comment by tkssharma** [comment]
@alexisvisco you mean to say ormconfig ? i tried it didn't work

**Comment by alexisvisco** [comment]
Yeah in the ormconfig, strange can you drop your ormconfig ?

**Comment by ekzyis** [comment]
Oh, I forgot to test it out. Just tested it out and it doesn't seem to work for me, either.

My ormconfig.js:

```javascript
{
  type: 'postgres',
  entities: [ 'dist/**/*.entity.js' ],
  migrations: [ 'dist/migration/*.js' ],
  cli: { migrationsDir: 'src/migration' },
  logging: [ 'error' ],
  synchronize: false,
  namingStrategy: new SnakeNamingStrategy(),
  cache: { duration: 60000 },
  migrationsTransactionMode: 'each',
  host: '127.0.24.24',
  port: 5432,
  username: 'test',
  password: 'test',
  database: 'test'
}
```

Running migrations with `npx typeorm migration:run`. If I use `npx typeorm migration:run -t each` it works (as written above).

How did you find out about this `migrationsTransactionMode`?

**Comment by tkssharma** [comment]
npx typeorm migration:run -t each it worked so i am good :) 
ormconfig doesn't have this mode `migrationsTransactionMode`

**Comment by ekzyis** [comment]
Glad that I could help you but I would still be interested in making this work via the ormconfig :D
