### ISSUE TITLE
Add parameter names for execution of queries and stored procedures, instead of indexes

### ISSUE THREAD

**Issue by nikolalukovic** [typeorm/typeorm#2696]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When executing stored procedures or any query that wasn't made with query builder and adding parameters it requires adding them by index instead of parameter names. This should be changed.

https://github.com/typeorm/typeorm/blob/b794d0c3930614a3eb16a290d8b1d0e98632e602/src/driver/sqlserver/SqlServerQueryRunner.ts#L188

**Comment by imnotjames** [comment]
Why should this be changed?

**Comment by nikolalukovic** [comment]
Tedious supports calling stored procedures with parameter names. Either way I don't use typeorm anymore so it doesn't have to be changed.

**Comment by imnotjames** [comment]
Once we update the `query` API to also support named parameters we'll make sure to include mssql in that change!
