### ISSUE TITLE
Support for IBM DB2 Database Server

### ISSUE THREAD

**Issue by shortthirdman** [typeorm/typeorm#2699]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `db2` (experimental)
**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>
Also include support for IBM DB2 Server

**Comment by SkrabakL** [comment]
+1

**Comment by pleerock** [comment]
As it was mentioned multiple times we don't have in plans to implement new drivers in a near future. If you want to contribute - please feel free! To keep issues cleaner lets close this one and continue discussion in #4

**Comment by gabrielwillemann** [comment]
+1

**Comment by luan-vieira-er** [comment]
+1
