### ISSUE TITLE
CascadeUpdate not working. Still getting  Duplicate entry error

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#270]
Suppose you are updating an existing post and its existing meta data which has a `@ManyToOne` relationship:

````
@Entity()
export class Post {

    @PrimaryGeneratedColumn()
    post_id: number;

    @OneToMany(type=>MetaData,entity=>entity.post,{cascadeUpdate:true, cascadeInsert: true})
    @JoinTable()
    meta_data:MetaData[];

    @Column({type: 'text'})
    comment: string;
}

@Entity()
export class MetaData {
    @PrimaryGeneratedColumn()
    meta_submit_id:number;

    @Column({type:'text'})
    content:string;

    @ManyToOne(type => Post, entity => entity.meta_data)
    @JoinColumn({name:'post_id'})
    post: Post;

    @Column({type:'int'})
    post_id:number;

}
````

I thought that when the meta data's primary keys `submit ids` are provided, it would update the existing meta data instead of inserting new ones. However, I'm still getting `Error: ER_DUP_ENTRY: Duplicate entry '1' for key 'PRIMARY''` on the `MetaData `model,which indicates that the orm attempts to insert new rows instead of updating the existing rows. Can anyone figure out what's the problem?

Example Code:

````
@Post("/update/thread")
async updateExistingPost(@BodyParam("postId") postId:number,
                                 @BodyParam("comment")comment:string,
                                 @BodyParam("meta_submit_id") metaSubmitIds:number[],
                                 @BodyParam("content")metaContent:string[],
){
  let post = new Post();
  post.post_id = postId;
  post.comment = comment;
  post.meta_data = [];
  metaSubmitIds.foreach((submitId,idx)=>{
    let item = new MetaData()
    item.meta_submit_id = submitId;
    item.content = metaContent[idx];
    item.post_id = postId;
    post.meta_data.push(item);
  })
  let repository = Container.get(PostRepository)
  repository.persist(post);
}
````

**Comment by SebastianMetzger** [comment]
One thing that caught my eye looking over your model, we had issues with duplicate keys, when our PrimaryColumn was named anything else but "id":
https://github.com/typeorm/typeorm/issues/269

Maybe this is the root casue for your issue as well?

**Comment by stonecold123** [comment]
Thanks for your quick response! I'm testing it out. Will get you updated.

**Comment by stonecold123** [comment]
I've changed the `MetaData` model's primary key from `meta_submit_id` to `id`, but it's not working. The error still ocuurs on the `MetaData` model.

**Comment by stonecold123** [comment]
To get it work, I have to make `post_id` column in the MetaData model `nullable` , and use `onDelete` cascade on post column:

````
@Entity()
export class MetaData {
    @PrimaryGeneratedColumn()
    meta_submit_id:number;

    @Column({type:'text'})
    content:string;

    @ManyToOne(type => Post, entity => entity.meta_data,{onDelete:'CASCADE'})
    @JoinColumn({name:'post_id'})
    post: Post;

    @Column({type:'int',nullable:true})
    post_id:number;

}
````

I also find that routing controller still takes `metaSubmitIds` as an array of strings instead of array of int. I  need to do the following when creating an instance of MetaData:
````
@Post("/update/thread")
async updateExistingPost(@BodyParam("postId") postId:number,
                                 @BodyParam("comment")comment:string,
                                 @BodyParam("meta_submit_id") metaSubmitIds:number[],
                                 @BodyParam("content")metaContent:string[],
){
  let post = new Post();
  post.post_id = postId;
  post.comment = comment;
  post.meta_data = [];
  metaSubmitIds.foreach((submitId,idx)=>{
    let item = new MetaData()
    if(!isNaN(parseInt(submitIds[idx]))) {
          item.submit_id = parseInt(submitIds[idx]);
     }else{
          item.submit_id = null;
    }
    item.meta_submit_id = submitId;
    item.content = metaContent[idx];
    item.post_id = postId;
    post.meta_data.push(item);
  })
  let repository = Container.get(PostRepository)
  repository.persist(post);
}
```

**Comment by json-obregon** [comment]
I also experienced stonecold123 issue where ids are expected to be ints but is given strings by controller, rest, graphql, etc. These would therefore cause the duplicate key errors. May I suggest that ids be automatically converted depending on the type stated in @Column definition of the field.

**Comment by pleerock** [comment]
Sorry for the delayed answer but this issue to be resolved required lot of efforts and refactorings. I have completely refactored persistence system and fixed all problems with cascades I have seen. Please try a new version (npm i typeorm@next) and let me know if your issue is still not resolved.
