### ISSUE TITLE
Add AfterBulkLoad Subscriber Method

### ISSUE THREAD

**Issue by csuich2** [typeorm/typeorm#2700]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

There are certain aggregation options I'd like to do in afterLoad method (think comment count on a post) and while afterLoad certainly works, the issue is that it can submit a LOT of individual requests to the DB.

I'd like to propose a new method on the subscriber interface called afterBulkLoad which would work nearly identically to afterLoad, but would pass an array of loaded entities rather than a single entity. This would give subscribers the opportunity to perform one DB query to perform aggregations using a group by clause, then modify all of the loaded entities.

If this is a change you are willing to accept, I can make the changes, I just wanted to get your take on it before putting in too much work.

**Comment by csuich2** [comment]
@pleerock Any thoughts on this?

**Comment by imnotjames** [comment]
This seems somewhat complex with little payoff.  Given we've not seen much interest in this feature I'm going to be closing it out.

Batching of loads into a separate system could be done via a queue and debouncer mechanism.
