### ISSUE TITLE
NativeScript support is incomplete

### ISSUE THREAD

**Issue by darkyelox** [typeorm/typeorm#2701]
**Issue type:**

[ ] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[X ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I only install the latest typeorm and notice in the issues that NativeScript is now supported but i'm not sure because when i try to use the `type: 'nativescript'` VSCode marks and error and digging it i found that ConnectionOptions not exposes the driver options for NativeScript, then i go to the Vue NativeScript example and i see the typeorm version points to a fork from someone else, so the implementation in this repository is incomplete?

**Comment by imnotjames** [comment]
This no longer seems to be the case - this is in the live version & should work as expected.
