### ISSUE TITLE
Columns embedded in child entities are non nullable by default

### ISSUE THREAD

**Issue by fwoelffel** [typeorm/typeorm#2705]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

(confirmed with postgres; I don't know about the other databases)

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

**Steps to reproduce or a small repository showing the problem:**

I noticed that the single table inheritance doesn't work as expected when a child entity contains an embedded entity: the embedded properties are non nullable by default.

I'll submit a PR with a failing test.

A temporary workaround is to explicitly define each property of the embedded entity as nullable.

**Comment by fwoelffel** [comment]
Could be closed by https://github.com/typeorm/typeorm/pull/2801

**Comment by pleerock** [comment]
Closing this one since #2801 is merged now.
