### ISSUE TITLE
Bug in queryBuildier when summing

### ISSUE THREAD

**Issue by elderapo** [typeorm/typeorm#2708]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.3.0-alpha.7`, `0.3.0-alpha.10`, `0.2.7`

**Steps to reproduce or a small repository showing the problem:**

```ts
import {
  Column,
  ConnectionOptions,
  createConnection,
  Entity,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn
} from "typeorm";

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number;
}

const options: ConnectionOptions = {
  type: "mysql",
  host: "localhost",
  port: 6667,
  username: "test",
  password: "test",
  database: "test",

  synchronize: true,
  entities: [User]
};

createConnection(options).then(
  async connection => {
    await connection.synchronize(true);

    const u1 = new User();

    await connection.getRepository(User).save(u1);

    {
      const raw = await connection
        .getRepository(User)
        .createQueryBuilder("user")
        .select("SUM(user.id)", "sum")
        .getRawOne();

      const { sum } = raw;

      console.log("typeof sum", typeof sum); /// "string" ???
      console.log("sum === 1", sum === 1); // false becuase "1" !== 1
      console.log("res", raw);
    }

    {
      const raw = await connection
        .getRepository(User)
        .createQueryBuilder("user")
        .where("user.id = :id", { id: 1 })
        .getRawOne();

      console.log("typeof raw.user_id", typeof raw.user_id); // "number" - ok
      console.log("raw.user_id === 1", raw.user_id === 1); // true - ok
    }
  },
  error => console.log("Cannot connect: ", error)
);
```

**Comment by elderapo** [comment]
SQL passed to [this queryRunner.query](https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts#L1903) is ```"SELECT SUM(`user`.`id`) AS `sum` FROM `user` `user`"```.

Same query works just fine with normal `mysql` library:

```js
const mysql = require("mysql");
const con: any = mysql.createConnection({
  host: "localhost",
  port: 6667,
  user: "test",
  password: "test",
  database: "test"
});

con.connect();

const query = "SELECT SUM(`user`.`id`) AS `sum` FROM `user` `user`";

con.query(query, (err: Error, results: any) => {
  if (err) {
    return console.error(err);
  }
  console.log(typeof results[0].sum); // number - ok
});

con.end();
```

Unfortunately, I am not able to investigate it any further.

**Comment by elderapo** [comment]
Also noticed another bug with `SUM`. When the `SUM` query doesn't match any records it returns `null` instead of `0`.

```typescript
import {
  ConnectionOptions,
  createConnection,
  Entity,
  getRepository,
  PrimaryGeneratedColumn
} from "typeorm";

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  public id: number;
}

const options: ConnectionOptions = {
  type: "mysql",
  host: "localhost",
  port: 3306,
  username: "test",
  password: "test",
  database: "test",

  // logging: true,
  synchronize: true,
  entities: [User]
};

createConnection(options).then(
  async connection => {
    await connection.synchronize(true);

    const userRepository = getRepository(User);

    // it won't match anything since users table is empty
    const { sum } = await userRepository
      .createQueryBuilder("user")
      .select("SUM(user.id)", "sum")
      .getRawOne();

    console.log(sum); // prints null
  },
  error => console.log("Cannot connect: ", error)
);
```

Tested with `next` and `0.2.8` versions.

**Comment by Kononnable** [comment]
sum, avg, count returning string not number - isn't that connected with how big numbers are handled in js?

> Also noticed another bug with SUM. When the SUM query doesn't match any records it returns null instead of 0.
Isn't that a standard behavior for sql? Maybe you should use IFNULL or similar function.

**Comment by pleerock** [comment]
That's how mysql driver works (refer to their documentation/issues), as I remember the problem is that they can't understand what type is being returned

**Comment by elderapo** [comment]
@pleerock, by `mysql driver` you mean `mysql` library?

Same query executed using `mysql` library returns number instead of string so it's not that.

> SQL passed to [this queryRunner.query](https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts#L1903) is `` "SELECT SUM(`user`.`id`) AS `sum` FROM `user` `user`" ``.
> 
> Same query works just fine with normal `mysql` library:
> 
> ```js
> const mysql = require("mysql");
> const con: any = mysql.createConnection({
>   host: "localhost",
>   port: 6667,
>   user: "test",
>   password: "test",
>   database: "test"
> });
> 
> con.connect();
> 
> const query = "SELECT SUM(`user`.`id`) AS `sum` FROM `user` `user`";
> 
> con.query(query, (err: Error, results: any) => {
>   if (err) {
>     return console.error(err);
>   }
>   console.log(typeof results[0].sum); // number - ok
> });
> 
> con.end();
> ```
> 
> Unfortunately, I am not able to investigate it any further.

**Comment by pleerock** [comment]
ah sorry I understood this issue incorrectly. So problem is here:

```ts
      const raw = await connection
        .getRepository(User)
        .createQueryBuilder("user")
        .select("SUM(user.id)", "sum")
        .getRawOne();
```

you have raw.sum as a string, right? Its very strange, you should't have it. Can you create a failing test so we can debug it ?

**Comment by elderapo** [comment]
@pleerock, done! The weird thing is the test fails for all drivers except for `SqliteDriver`.

**Comment by hei-pa** [comment]
What is the state of this bug? Is there anything I could do instead of mapping the result?

**Comment by Cfvillarroel** [comment]
Hi, is there any solution for this bug instead of mapping?

**Comment by march08** [comment]
The issue is deeper I guess?

When I have a column e.g. 
```
    amount: {
      type: 'numeric',
      precision: 12,
      scale: 2,
      default: 0,
    },
```

When I want to retrieve the data, I get { amount: String } instead of { amount: Number } in the data.

**Comment by elderapo** [comment]
For anyone interested [here](https://github.com/typeorm/typeorm/pull/3391) you can find PR with a failing test case for this issue. I don't know `typeorm` internals well enough to fix/debug it any further.

**Comment by Cacivy** [comment]
https://github.com/typeorm/typeorm/issues/1875#issuecomment-404012045
it's work for me

**Comment by imnotjames** [comment]
This is not a bug - `SUM(user.id)` returns a `BIGINT` and TypeORM enables `bigNumberStrings` by default.

The standard `mysql` library does NOT enable `bigNumberStrings` by default.

**Comment by imnotjames** [comment]
In other words, you can sort of work around this by setting `bigNumberStrings` to `false`

Do note, however, that disabling `bigNumberStrings` means that numbers outside the integer threshold for `number` will become a floating point number!

**Comment by emmett-react-flexbox-gri** [comment]
@kaedwen https://stackdev.space/questions/add-a-new-column-to-a-table-and-organize-the-values-by-using-the-sum-function-along-with
