### ISSUE TITLE
How enable cache from environment variable?

### ISSUE THREAD

**Issue by Ilyaololo** [typeorm/typeorm#2709]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Question**

How set `cache: true` option from `.env` file? 
Maybe add support `TYPEORM_CACHE` environment variable?

**Comment by Devang142** [comment]
Please also add support to specify redis configuration in .env. For now, I am using ormconfig.json.

**Comment by pleerock** [comment]
Feel free to PR :)

**Comment by vlapo** [comment]
@rustamwin do not understand. How is this issue related to this commit?

**Comment by rustamwin** [comment]
Ah sorry :)

**Comment by sgentile** [comment]
> Please also add support to specify redis configuration in .env. For now, I am using ormconfig.json.

Are there any examples of this ?
