### ISSUE TITLE
Support for UUID columns in PostgreSQL (maybe other databases too)

### ISSUE THREAD

**Issue by MaikelH** [typeorm/typeorm#271]
Currently the PostgreSQL system for TypeORM does not support UUID columns. (see[ PostgresQueryRunner.ts](https://github.com/typeorm/typeorm/blob/6897da035ea028b5214327d9540d27ee1a7c9dc0/src/driver/postgres/PostgresQueryRunner.ts#L746)

Since the UUID type is a supported type in PostgreSQL, TypeORM should also support it.

Some example code:

```typescript
@Entity()
export class Product {
    @PrimaryColumn('uuid')
    public id: string;
}
```

This code will error with the following output:
```
Specified type (uuid) is not supported by Postgres driver
```

**Comment by pleerock** [comment]
Yes, we should add this column type. I'll implement it once I get more free time. But its easy feature, if you want to contribute - feel free to create PR for it.
