### ISSUE TITLE
Custom decorator?

### ISSUE THREAD

**Issue by leesiongchan** [typeorm/typeorm#2711]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How if I want to create a custom decorator say for example a blameable decorator?

**Comment by Kononnable** [comment]
I don't see how creating custom decorator is related to ORM. Could you describe your issue(if it is related to typeorm)?

**Comment by leesiongchan** [comment]
I mean a customer column decorator, like `@CreateDateColumn` or `@UpdateDateColumn`, what if I want to create a custom column decorator like `@CreateCreatorColumn` or `@UpdateCreatorColumn`?  Or can we have an example in doc?

**Comment by leesiongchan** [comment]
Yea, but it doesn't seem to have the flexibility to add your custom metadata, ORM later uses `mode` to determine the logic I believe.

**Comment by DishantAckplus** [comment]
> 

> `[](url)`
