### ISSUE TITLE
"synchronize" option removing data from the database

### ISSUE THREAD

**Issue by roeehershko** [typeorm/typeorm#2712]
**Issue type:**

[ ] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
when i enable "synchronize" option, it constantly changing my database data in very specific table and specific data, its changing the "Accounts" entity, changing the "company" field to empty string and the "active" column to 0 where the id is 1  
so my database looks like this:
id         | company |  active
1          | blabla      |  1 
transformed into this  on every change:
id         | company |  active
1          |                 |  0 

This is my account entity:
```
import { Entity, Column, PrimaryGeneratedColumn, OneToMany } from 'typeorm';
import { User } from './users.entity';
import { AccountKey } from './accounts-keys.entity';

@Entity('accounts')
export class Account {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToMany(type => User, user => user.account)
  users: User[];

  @OneToMany(type => AccountKey, accountKey => accountKey.account)
  accountKeys: AccountKey[];

  @Column()
  company: string;

  @Column()
  active: boolean;

  @Column({ type: 'datetime', default: () => 'CURRENT_TIMESTAMP'})
  modified: Date;

  @Column({ type: 'datetime', default: () => 'CURRENT_TIMESTAMP'})
  created: Date;

  @Column({ type: 'datetime', default: () => null, nullable: true })
  deleted: Date;
}
```

and this is the ormconfig:
```
{
  "type": "mysql",
  "host": "127.0.0.1",
  "port": 3306,
  "username": "root",
  "password": "",
  "logging": ["error"],
  "database": "mydb",
  "entities": ["./src/common/entity/*.entity.ts"],
  "synchronize": true
}
```

**Comment by popovicidinu** [comment]
I can confirm this issue. I have a different setup, but if i leave synchronize: true, it removes some data from my "users" table (specifically the string values).

**Comment by pleerock** [comment]
it removes only data that is affected by queries. For example if you remove column from your entity it will run drop column query that leads to data loss. It is expected behaviour. If you think in your case it does something unexpected, first inspect what SQL code it generates and executes and think why it does it, then provide more details for us.

**Comment by havenchyk** [comment]
I'm closing this issue for housekeeping purposes, if something is not clear yet, just continue the conversation or post a message in slack

**Comment by JaffParker** [comment]
I noticed it happening with `json` or `simple-json` columns. With the `syncronize` option enabled, whenever TypeORM runs checks on startup, the type of the created column in MySQL doesn't match whatever TypeORM is expecting, so it drops and re-creates that column, thus nullifying whatever was in it. Here's the queries that run on startup:

```sql
query: SELECT `s`.* FROM `INFORMATION_SCHEMA`.`STATISTICS` `s` LEFT JOIN `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` `rc` ON `s`.`INDEX_NAME` = `rc`.`CONSTRAINT_NAME` WHERE ((`s`.`TABLE_SCHEMA` = 'terminal_makeover' AND `s`.`TABLE_NAME` = 'users')) AND `s`.`INDEX_NAME` != 'PRIMARY' AND `rc`.`CONSTRAINT_NAME` IS NULL
query: SELECT `kcu`.`TABLE_SCHEMA`, `kcu`.`TABLE_NAME`, `kcu`.`CONSTRAINT_NAME`, `kcu`.`COLUMN_NAME`, `kcu`.`REFERENCED_TABLE_SCHEMA`, `kcu`.`REFERENCED_TABLE_NAME`, `kcu`.`REFERENCED_COLUMN_NAME`, `rc`.`DELETE_RULE` `ON_DELETE`, `rc`.`UPDATE_RULE` `ON_UPDATE` FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` `kcu` INNER JOIN `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` `rc` ON `rc`.`constraint_name` = `kcu`.`constraint_name` WHERE (`kcu`.`TABLE_SCHEMA` = 'terminal_makeover' AND `kcu`.`TABLE_NAME` = 'users')
renaming column "profile" in to "profile"
columns changed in "users". updating: profile
query: ALTER TABLE `users` DROP COLUMN `profile`
query: ALTER TABLE `users` ADD `profile` json NOT NULL
```

I'm guessing this happens because MySQL displays a `JSON` type column as `TEXT` and therefore it's not the same type. Not sure then, why it happens with `simple-json` as well, isn't that supposed to be just a `TEXT` column?

Funny thing also is that it doesn't happen in Oracle.

**Comment by Kononnable** [comment]
Ok, so now we now that it doesn't happen in Oracle but we don't know where it does happen 😄 
Please open a new issue with description on which database does it happen and some reproduction data(entity definition) /PR with failing test case.

**Comment by JaffParker** [comment]
@Kononnable oops, I didn't mention where it happens because I only confirmed the issue of @roeehershko. As in his case, it happens in MySQL for me.

**Comment by funkizer** [comment]
Same here. MySQL (MariaDB), typeorm v. 0.2.11.

Something definately changed between 0.2.9 and 0.2.11 causing this, as my project using 0.2.9 is in production and has had no issues.

@JaffParker are you also using uuid? One change I noticed is that on synchronize, the UUID generator strategy now sets the ID type as VARCHAR(36). In 0.2.9 it was VARCHAR(255). My new app is at hello world stage but the entity is configured exactly the same was as in the older working app:

```
@Entity({
  orderBy: {
    lastName: 'ASC',
    firstName: 'ASC',
  },
})
export class User {
  @PrimaryGeneratedColumn('uuid')
  id?: string;

  @Column() lastName: string;
...
```

**Comment by funkizer** [comment]
In my case, problems disappear using increment instead of uuid:

```
  @PrimaryGeneratedColumn('increment') id?: number;
```

**Comment by pleerock** [comment]
@funkizer this issue was fixed in `typeorm@rc`, try `npm i typeorm@rc`

**Comment by funkizer** [comment]
Thank you @pleerock! All good with 0.2.12-rc.2

**Comment by syuilo** [comment]
I do not know if it is related to this issue, but when creating an array column in PostgreSQL, data will be deleted at every sync.

**Comment by JaffParker** [comment]
@syuilo it seems related. Could you enable debug logs and see what exactly TypeORM does with your array column?

**Comment by SpeedoPasanen** [comment]
Probably not as if my memory serves, uuid had a different length when created and when compared for changes at synchronizing. Could be similar though :)

**Comment by ssi-hu-tasi-norbert** [comment]
same happened to me with boolean fields. I had to remove entities from dist folder. After rebuilding everything works as exprected.

**Comment by peteryangnw** [comment]
Thought I'd post here, since this happened to me as well and maybe it will save some time for someone. 
My issue was due to incorrect entity type / (width|length) mismatch. 

I had an entity defined with: 
`@PrimaryColumn({type="binary", width=16}) ` 

but it should have been:
`@PrimaryColumn({type="binary", length=16})`

It might be nice to have some error or warning similar to the warning for entity types that use length but shouldn't. Or, have some log that tells why the columns were changed (perhaps a summary of the console.log()'s in MysqlDriver.js:632:)

Here's how to reproduce:
1) Created Entity with a member 
```
@PrimaryColumn({type="binary", width=16})
 _id: Buffer;
```

2) Call  `let connection = createConnection( {
type:"mysql",
..., 
synchronize:false, 
...
});`
3) Call `connection.synchronize();`
exit program.

Database table created. No errors or warnings
Upon running the program again with no code changes or table changes, the column is dropped and re-added.

I uncommented some of the console.log output in the MysqlDriver.ts and got the following:
```
FIRST RUN DEBUG OUTPUT:
==============================================
MysqlDriver.js:632:

table: company
name: _id _id
type: binary binary
length:  
width: 16 16
precision: undefined undefined
scale: undefined undefined
zerofill: false false
unsigned: false false
asExpression: undefined undefined
generatedType: undefined undefined
comment:  
default: undefined undefined
enum: undefined undefined
default changed: false
onUpdate: undefined undefined
isPrimary: true true
isNullable: false false
isUnique: false false
isGenerated: false false
false



SECOND RUN:
=================================================
MysqlDriver.js:632:

table: company
name: _id _id
type: binary binary
length: 16 
width: undefined 16
precision: undefined undefined
scale: undefined undefined
zerofill: false false
unsigned: false false
asExpression: undefined undefined
generatedType: undefined undefined
comment:  
default: undefined undefined
enum: undefined undefined
default changed: false
onUpdate: undefined undefined
isPrimary: true true
isNullable: false false
isUnique: false false
isGenerated: false false
false
==========================================
columns changed in "company". updating: _id                                         
query: ALTER TABLE `company` DROP PRIMARY KEY

```

It appears that the first time around it is saved and recorded as a **length of 16** ,even though the entity is defined as **width of 16**, so in the second run it finds the mismatch and drops and re-adds the column

**Comment by hoangnguyenba** [comment]
it happens in 0.2.18 now.
MySQL
My type of column is "text".

When start connect to DB, it removes all column with type is "text"

**Comment by heshaShawky** [comment]
the problem still exists with MySQL with me  

the https://stackoverflow.com/questions/57739686/typeorm-queryfailederror-er-bad-field-error-unknown-column-wptermtaxonomymod

**Comment by chomenko** [comment]
try deleting folder dist

**Comment by yumindeckard** [comment]
Me, too

**Comment by kalicki2k** [comment]
Are there any news? Because the problem is still there! Or should a new issue be created?

**Comment by ssi-hu-tasi-norbert** [comment]
for me the error occured when I changed/renamed entities and didn't cleared my dist folder. After removing everything, the error has gone. Have you tried to delete dist folder before building?

**Comment by peteroreil** [comment]
> try deleting folder dist

Fixed for me. Thanks @chomenko !

**Comment by igortobert** [comment]
typeorm 0.2.24
sync: true
DROP COLUMN
DROP CONSTANT
rm -rf dist  - fix issue for me

Thanks
@chomenko !

**Comment by chinanderm** [comment]
> try deleting folder dist

This did it, thank you! Hopefully this is something that can be addressed in the library as a fix.

**Comment by BioAbnerUAD** [comment]
Is it ok for me to disable synchronization altogether? Some important data was deleted because of it. We had backups, but I don't want this to ever happen again.

**Comment by lazaroofarrill** [comment]
> Is it ok for me to disable synchronization altogether? Some important data was deleted because of it. We had backups, but I don't want this to ever happen again.

Well you are not supposed to use sync in production in the first place. Sync is destructive by nature. This bug affects development workflow but it's not the end of the world if it only happens in your test database which you probably drop and rebuild all the time. In production environments you need to use migrations, and check them manually.

**Comment by antonrinas** [comment]
I've got this problem too ((
Using:
"typeorm": "^0.2.38"

**Comment by lazaroofarrill** [comment]
> I've got this problem too (( Using: "typeorm": "^0.2.38"

Deleting the dist folder and running the project again might solve the issue.

**Comment by antonrinas** [comment]
> Deleting the dist folder and running the project again might solve the issue.

Also, I just turned off "synchronize"
`TypeOrmModule.forRoot({synchronize: false ...`

**Comment by DanielAdek** [comment]
data loss still happens on mysql with sync set to true

**Comment by FarzanKhan009** [comment]
> try deleting folder dist

Thank you brother. I was occupied from last 1 hour. Didn't know whats happening wrong.
I Think I had set a column default zero then later I removed this default, soon after every sync my wallet field zeroing all rows, all of the users wallet balance being zeroed.. Scary. Deleting Dist Solved it.

**Comment by usama-taro** [comment]
I am still facing this issue. If I remove or set synchronize to false, it does not create new columns or table in database. but if I set it to true, it add new tables or columns to the database but removed those columns which are not defined in that projects entity. 
So in the current scenarios I have two separate projects accessing single User table in the database. Each project has its own set of columns defined in it's User entity but mainly they all are same. So when project A run it adds its columns to the database, and after that when I start project B it adds its column to the database and remove the columns added by project A (with synchronize option set to true) and when I set it to false. None of the project is able to add its columns to table.

Can anybody here help me with this situation? I will be a huge help.

**Comment by SpeedoPasanen** [comment]
> I am still facing this issue. If I remove or set synchronize to false, it does not create new columns or table in database. but if I set it to true, it add new tables or columns to the database but removed those columns which are not defined in that projects entity. So in the current scenarios I have two separate projects accessing single User table in the database. Each project has its own set of columns defined in it's User entity but mainly they all are same. So when project A run it adds its columns to the database, and after that when I start project B it adds its column to the database and remove the columns added by project A (with synchronize option set to true) and when I set it to false. None of the project is able to add its columns to table.
> 
> Can anybody here help me with this situation? I will be a huge help.

This is not an issue. If you have several apps accessing the same database, they should all have identifical entities. And you should not use synchronize in production.

**Comment by lazaroofarrill** [comment]
> I am still facing this issue. If I remove or set synchronize to false, it does not create new columns or table in database. but if I set it to true, it add new tables or columns to the database but removed those columns which are not defined in that projects entity. So in the current scenarios I have two separate projects accessing single User table in the database. Each project has its own set of columns defined in it's User entity but mainly they all are same. So when project A run it adds its columns to the database, and after that when I start project B it adds its column to the database and remove the columns added by project A (with synchronize option set to true) and when I set it to false. None of the project is able to add its columns to table.
> 
> Can anybody here help me with this situation? I will be a huge help.

Well this sounds like a cumulus of terrible design decisions and bad practices. You shouldn't have two projects writing to the same db in the first place.

**Comment by usama-taro** [comment]
> > I am still facing this issue. If I remove or set synchronize to false, it does not create new columns or table in database. but if I set it to true, it add new tables or columns to the database but removed those columns which are not defined in that projects entity. So in the current scenarios I have two separate projects accessing single User table in the database. Each project has its own set of columns defined in it's User entity but mainly they all are same. So when project A run it adds its columns to the database, and after that when I start project B it adds its column to the database and remove the columns added by project A (with synchronize option set to true) and when I set it to false. None of the project is able to add its columns to table.
> > Can anybody here help me with this situation? I will be a huge help.
> 
> Well this sounds like a cumulus of terrible design decisions and bad practices. You shouldn't have two projects writing to the same db in the first place.

So you are saying that, each microservice should have its own database? So wtf are microservices and lambda functions are for?

**Comment by lazaroofarrill** [comment]
> > > I am still facing this issue. If I remove or set synchronize to false, it does not create new columns or table in database. but if I set it to true, it add new tables or columns to the database but removed those columns which are not defined in that projects entity. So in the current scenarios I have two separate projects accessing single User table in the database. Each project has its own set of columns defined in it's User entity but mainly they all are same. So when project A run it adds its columns to the database, and after that when I start project B it adds its column to the database and remove the columns added by project A (with synchronize option set to true) and when I set it to false. None of the project is able to add its columns to table.
> > > Can anybody here help me with this situation? I will be a huge help.
> > 
> > 
> > Well this sounds like a cumulus of terrible design decisions and bad practices. You shouldn't have two projects writing to the same db in the first place.
> 
> So you are saying that, each microservice should have its own database? So wtf are microservices and lambda functions are for?

that's rule no 1 of microservices

**Comment by Radek-Wawrzyk** [comment]
I'm having the same issue (MySQL + TypeORM 0.3.6). Each change in the code (not only entity files) removes fields from user table. What is funny, I created exactly the same entity for my previous project and the synchronize feature doesn't remove fields on any code change.

Removing dist directory doesn't help at all.

**Comment by pradip503** [comment]
I was having the same issue with `jsonb` in MYSQL and TypeORM 0.3.6. I was able to solve changing the type to `simple-json`.

**Comment by JeffCorp** [comment]
Removing the dist directory worked for me

**Comment by Mobilu-Adam** [comment]
@PrimaryColumn({ type: 'uuid', nullable: false })
  @Generated('uuid')
  id!: string;
  
  Solved the issue for me

**Comment by jamilmendez** [comment]
I use docker and I have configured the mysql volumes, when removing the volumes the error disappeared

**Comment by Ramirokaffo** [comment]
I just rename my table from 'user' to 'myuser' and everything work as expected
