### ISSUE TITLE
how to create background index in mongodb ?

### ISSUE THREAD

**Issue by ruanzhijun** [typeorm/typeorm#2713]
![_20180827110300](https://user-images.githubusercontent.com/4838161/44638375-1c2d3900-a9e9-11e8-85b0-a67c2934b7f0.png)

**Comment by ruanzhijun** [comment]
Issue type:

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[*] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[ ] postgres
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

TypeORM version:

[*] latest
[ ] @next
[ ] 0.x.x (or put your version here)

**Comment by ruscon** [comment]
ping ?

**Comment by Kononnable** [comment]
Statement which create index in the background is different than when index is normally created or is it just an operation running in the background thread?

**Comment by rustamwin** [comment]
@ruanzhijun you can create background index with pass option `background: true` in `createCollectionIndex`

**Comment by rustamwin** [comment]
I think `@Index` decorator should support `MongoIndexOptions`
