### ISSUE TITLE
[Question] Multiple connections - Static Entity operations

### ISSUE THREAD

**Issue by tomer-amir-vonage** [typeorm/typeorm#2715]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

I am starting to work with multiple DB connections on the same server, and each DB works with different entities.

I would expect to still be able to use the static methods for `find, save, remove` but it seems like I am doing something wrong, or it's not possible.

Here I create the connections:

```ts
await createConnections([{
	name: 'db1',
	...db1Conf,
	type: 'postgres',
	entities: [__dirname + '../db1_models/**/*'],
	synchronize: false
}, {
	name: 'db2',
	...db2Conf,
	type: 'postgres',
	entities: [__dirname + '../db2_models/**/*'],
	synchronize: false
}]);
```

but when I try to do:
```ts
import { User } from '../db1_modles/User'

User.find()
```

I get the following exception:
```
{ ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (/server/src/error/ConnectionNotFoundError.ts:8:9)
    at ConnectionManager.get (/server/src/connection/ConnectionManager.ts:40:19)
    at Object.getConnection (/server/src/index.ts:240:35)
    at Function.BaseEntity.getRepository (/server/src/repository/BaseEntity.ts:83:72)
    at Function.BaseEntity.find (/server/src/repository/BaseEntity.ts:259:30)
    at PGService.<anonymous> (/server/services/provisioning/PGService.ts:72:68)
  name: 'ConnectionNotFoundError',
  message: 'Connection "default" was not found.' }
```

I can only make it work using `this.db.manager.find(User)`

Am I doing something wrong?

**Comment by Kononnable** [comment]
Did you resolve your issue?

**Comment by vlapo** [comment]
I think it is by design because of case when same entity can be registered in more than one connection. In that case you have to use e.g.: `User.useConnection(getConnection('db1'))`.

Maybe add some note in docs?

**Comment by Superd22** [comment]
Just encountered the same issue. Besides documentation, should TypeORM provide a shorthand for this ? 

Either a `connectionName` option in the `@Entity` decorator,
or call `Entity.useConnection()` on all BaseEntities registered in one Connection once it becomes alive. (for entities registered in multiple connections, the latest to become alive would then be used, which could be documented and doesn't seem that weird, since you'd expect to have to manually select one anyway)

Any thoughts on this ? @vlapo

**Comment by Kononnable** [comment]
>Either a `connectionName` option in the `@Entity` decorator

Name of a connection is part of environment configuration, decorator is part of database schema which isn't dependent on any configuration options(maybe just on db engine type), so I would definetely not add a parameter here.

>call `Entity.useConnection()` on all BaseEntities registered in one Connection once it becomes alive

This would make sense with some of the cases, while it could be error prone and hard to debug in others. If you will be connected to just one server at the time this might be usefull, however if you connect to multiple you could end up with manually calling `useConnection()` and doing some async stuff while other connection gets online and change the active connection. And what about reconnections? If for whatever reason connection gets broken but reconnection succeed we could have changed default connection for Entity while nobody expected it.

I don't think Active Record Pattern is a good fit for multiple connections which are using same entities. It probably would be better to do some kind of inheritance just to have two identical classes which could be used on different connections.

**Comment by Superd22** [comment]
Fair enough for the decorator.

> I don't think Active Record Pattern is a good fit for multiple connections which are using same entities. It probably would be better to do some kind of inheritance just to have two identical classes which could be used on different connections.

I'm not arguing for that. The issue here arises even if you're using two connections with no shared entities. You will have to call `useConnection()` anytime you're not using default.

I'm not arguing ActiveRecord should behave any differently than DataMapper. It just feels weird i'd have to manually specify in one case and not the other to get the same behavior.

**Comment by pak11273** [comment]
> I think it is by design because of case when same entity can be registered in more than one connection. In that case you have to use e.g.: `User.useConnection(getConnection('db1'))`.
> 
> Maybe add some note in docs?

`Cannot find name 'getConnection'`

I'd also like to not have to duplicate this line in every entity file.

**Comment by imnotjames** [comment]
Question was answered.  If you have a specific actionable feature request, please open a new issue about it.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
