### ISSUE TITLE
Error reverting migration with enum postgres

### ISSUE THREAD

**Issue by zveljkovic** [typeorm/typeorm#2724]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.27` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Create migration below, run migration:run and then migration:revert.

***Expected***
To undo migration

***Actual***
Throws error `Error during migration revert:
{ QueryFailedError: type "test_status_enum" does not exist`

```import {MigrationInterface, QueryRunner, Table} from 'typeorm';

export class CreateTest1535031863784 implements MigrationInterface {

		public async up(queryRunner: QueryRunner): Promise<any> {
			await queryRunner.createTable(new Table({
				columns: [
					{
						isGenerated: true,
						isPrimary: true,
						name: 'id',
						type: 'int',
					},
					{
						enum: ['active', 'pending', 'inactive'],
						name: 'status',
						type: 'enum',
					},
				],
				name: 'Test',
			}));
		}

		public async down(queryRunner: QueryRunner): Promise<any> {
			await queryRunner.dropTable('Test');
		}
}

```

**Comment by Kononnable** [comment]
May be related to #1997.
