### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by zveljkovic** [typeorm/typeorm#2727]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Documentation on migrations with CreateDateColumn or UpdateDateColumn is lacking. Please provide more information on what type the columns need to be set in migrations to get the annotations to work properly. Currently save on new entity is not filling createdAt column and hence errors out.

Side question, why does all node ORM projects waste time on .sync() when it's clearly unusable for any production purposes?

**Comment by zveljkovic** [comment]
For anyone wondering you need to set default values in migrations for CreateDateColumn and UpdateDateColumn to 'now'.

```
{
  default: 'now()',
  name: 'createdAt',
  type: 'timestamp',
}, {
  default: 'now()',
  name: 'updatedAt',
  type: 'timestamp',
},
```

**Comment by gintsgints** [comment]
@zveljkovic sync is very useful for development process, when you do many changes. After you have stabilized your database you can export objects and make migrations from that.

If you would export sync made table with columns CreateDateColumn & UpdateDateColumn, you would see your solution is applied.
