### ISSUE TITLE
Can't remove entry  with PK base on two columns

### ISSUE THREAD

**Issue by apiel** [typeorm/typeorm#273]
When I try to remove an entity with a primary key base on multiple column, I get an error.

```
@Entity("Table")
export default class {
    @PrimaryColumn()
    cardId: string;
 
    @PrimaryColumn()
    time: number;
 
    @Column()
    status: string;
}
```

> 
>      Error: Database entity is not set for the given subject.
>       at Subject.get [as databaseEntity] (node_modules/typeorm/persistence/Subject.js:99:23)
>       at SubjectOperationExecutor.<anonymous> (node_modules/typeorm/persistence/SubjectOperationExecutor.js:770:148)
>       at step (node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)
>       at Object.next (node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)
>       at node_modules/typeorm/persistence/SubjectOperationExecutor.js:7:71
>       at __awaiter (node_modules/typeorm/persistence/SubjectOperationExecutor.js:3:12)
>       at SubjectOperationExecutor.remove (node_modules/typeorm/persistence/SubjectOperationExecutor.js:749:16)
>       at node_modules/typeorm/persistence/SubjectOperationExecutor.js:737:120
>       at Array.map (native)
>       at SubjectOperationExecutor.<anonymous> (node_modules/typeorm/persistence/SubjectOperationExecutor.js:737:82)
>       at step (node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)
>       at Object.next (node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)
>       at node_modules/typeorm/persistence/SubjectOperationExecutor.js:7:71
>       at __awaiter (node_modules/typeorm/persistence/SubjectOperationExecutor.js:3:12)
>       at SubjectOperationExecutor.executeRemoveOperations (node_modules/typeorm/persistence/SubjectOperationExecutor.js:733:16)
>       at SubjectOperationExecutor.<anonymous> (node_modules/typeorm/persistence/SubjectOperationExecutor.js:126:51)
>       at step (node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)
>       at Object.next (node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)
>       at fulfilled (node_modules/typeorm/persistence/SubjectOperationExecutor.js:4:58)
>       at process._tickCallback (internal/process/next_tick.js:103:7)
>

**Comment by pleerock** [comment]
you can't do `export default class {`, you need to specify a class name if you wan't typeorm to work correctly. This is most probably cause of your problem. Check it in latest typeorm version with improved multiple primary keys support.
