### ISSUE TITLE
oracle paging report error

### ISSUE THREAD

**Issue by zhouyu94** [typeorm/typeorm#2730]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

i use typeorm and oracle db. I want to get data by paging。i use skip and take, but it's report 
   error: { Error: ORA-00933: SQL command not properly ended errorNum: 933, offset: 522 }
how should i do to resolve this problem?

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.

**Comment by chasecs** [comment]
Maybe that's because your are using oracle-11g. skip and take only support oracle-12

**Comment by wyllbassos** [comment]
I have a same problem
