### ISSUE TITLE
Synchronizing MSSQL DB results in reassigning constraints in tables

### ISSUE THREAD

**Issue by kgrvr** [typeorm/typeorm#2733]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When I turn synchronize on, table gets created the first time, but second initialization of app results in following error:

> QueryFailedError: Error: Could not create constraint or index. See previous errors.
at new QueryFailedError (D:\Projects\Project\Codebase\master\Project.Api\src\error\QueryFailedError.ts:7:9)
at D:\Projects\Project\Codebase\master\Project.Api\src\driver\sqlserver\SqlServerQueryRunner.ts:209:37
at _query (D:\Projects\Project\Codebase\master\Project.Api\node_modules\mssql\lib\base.js:1253:25)
at Request.tds.Request.err [as userCallback] (D:\Projects\Project\Codebase\master\Project.Api\node_modules\mssql\lib\tedious.js:620:15)
at Request._this.callback (D:\Projects\Project\Codebase\master\Project.Api\node_modules\tedious\lib\request.js:60:27)
at Connection.endOfMessageMarkerReceived (D:\Projects\Project\Codebase\master\Project.Api\node_modules\tedious\lib\connection.js:1906:20)
at Connection.dispatchEvent (D:\Projects\Project\Codebase\master\Project.Api\node_modules\tedious\lib\connection.js:992:38)
at Parser. (D:\Projects\Project\Codebase\master\Project.Api\node_modules\tedious\lib\connection.js:813:18)
at emitOne (events.js:116:13)
at Parser.emit (events.js:211:7)

I investigated this issue by using MSSQL Profiler. It logged following alter queries being fired on it:

`exec sp_executesql @statement=N'ALTER TABLE "LogFileUpload" ALTER COLUMN "UploadDate" datetime'`

`exec sp_executesql @statement=N'ALTER TABLE "LogFileUpload" ADD CONSTRAINT "DF_fd73f87f20931690c7e1a099bdf" DEFAULT GETDATE() FOR "UploadDate"'`

The schema of table LogFileUpload already defines "UploadDate" column of "datetime" type. But still it alters this table to add this column. Secondly it adds a constraint of "DEFAULT GETDATE()" for it. This constraint is already defined on the table, therefore SQL Server is throwing following error:

> Msg 1781, Level 16, State 1, Line 1
> Column already has a DEFAULT bound to it.
> Msg 1750, Level 16, State 0, Line 1
> Could not create constraint or index. See previous errors.

I also referred this issue: https://github.com/typeorm/typeorm/issues/1991. Nothing helped.
Please help me solve this issue.

**Comment by kgrvr** [comment]
@AlexMesser Could you please help me with this issue?

**Comment by Kononnable** [comment]
@kgrvr 
Can you provide entities definitions on which you experience such error?

**Comment by kgrvr** [comment]
Yes. Following is the entity definition:

```
import { Column, Entity } from 'typeorm';
import { IsDate } from 'class-validator';
import { ApiModelProperty } from '@nestjs/swagger';

import { BaseEntity } from './base.entity';

@Entity('LogFileUpload')
export class LogFileUpload extends BaseEntity {
	
	...
	
	@IsDate()
	@Column({ nullable: true, default: () => 'GETDATE()' })
	@ApiModelProperty()
	public UploadDate: Date;

	...
	
}
```

Basically I'm experiencing such error everywhere where I'm setting default constraint for the column.

**Comment by kgrvr** [comment]
@Kononnable This issue is still occurring on the latest version 0.2.18.

In my entity, I tried adding a default constraint as following:
![image](https://user-images.githubusercontent.com/11766028/59148341-540be700-8a25-11e9-98f4-e986c376efa9.png)

Error: QueryFailedError: Error: Could not create constraint or index. See previous errors.

Queries executed on my database:
`
exec sp_executesql @statement=N'ALTER TABLE "TableName" ALTER COLUMN "CreatedDate" datetime2 NOT NULL'
`
`
exec sp_executesql @statement=N'ALTER TABLE "TableName" ADD CONSTRAINT "DF_fa707e48bd70e7dba747b4b2e3e" DEFAULT GETUTCDATE() FOR "CreatedDate"'
`

**Comment by Kononnable** [comment]
Right now you've provided completely different column then before. Passing test shows that previously provided definition is working correctly. Tested manually on `@CreateDateColumn` and it also worked for me. Create minimal reproduction repo/failing test - it might be something in your setup.
https://github.com/typeorm/typeorm/blob/master/test/github-issues/2733/entity/MSSQLDummy.ts
