### ISSUE TITLE
PrimaryGeneratedColumn not returning auto generated id Postgres and TypeORM

### ISSUE THREAD

**Issue by bsgsiva** [typeorm/typeorm#2739]
**Issue type:**

[ ] question
 

**Database system/driver:**

 
[ ] `postgres`
 
    "typeorm": "^0.3.0-alpha.10",

[ ] `latest`
 

**Steps to reproduce or a small repository showing the problem:**

 I am using typeorm ^0.3.0-alpha.10", I have auto identity column. Whenever I save data auto id column gets incremented but that id column is not returned in response whereas all the other columns are returned in response.

Save() {
    debugger;
    this.isSuccess = false;
    if (this.GalleryName == "") {
      this.isSuccess = true;
      this.ErrorMessage = "Gallery Name is required."
      return;
    }
   
    let gallery = {
      gallery_name: this.GalleryName,
      gallery_id:this.GalleryID,
      description: this.Description,
      file_path: "",
      url: "",
      Status: "",
      is_active: 1,
      created_on: new Date(),
      created_by: "1",
      modified_on: new Date(),
      modified_by: "1"
    }
  {

 /*  this.galleryService.getMaxGallery().subscribe(res=>{
    var idd=res;
   var id= res.max;
  });
 */
 
    this.galleryService.createGallery(gallery).subscribe(res => {
      debugger;
      if (res.Status == "Success") {
      
     
        this.isSuccess = true;
        this.ErrorMessage = "Saved Successfully";
        this.GalleryName = "";
        this.Description = "";
      }
    });
  }

In the above code you can see the line    this.galleryService.createGallery(gallery).subscribe(res => { 

gallery details should get saved and saved data should come in response. I am getting the saved data but I am not getting the particular gallery_id in the response. gallery_id is auto id column. Why is the auto generated id column not coming in the response where as all the other column details are coming correctly. Please help

**Comment by ravihugo** [comment]
I seem to be running into the same thing with Mysql backend.

**Comment by ravihugo** [comment]
Ok, false alarm for mysql: @PrimaryGeneratedColumn() was missing on my ID column.

**Comment by Kononnable** [comment]
@bsgsiva Did you resolve your issue?

**Comment by Kononnable** [comment]
Closing as no response from the author.
