### ISSUE TITLE
Graph structure from closure entity 

### ISSUE THREAD

**Issue by erlopezh** [typeorm/typeorm#274]
How to get a tree (graph) structure from a closure entity when the data represent a graph.
For example:
![captura de pantalla 2017-02-09 a las 17 07 06](https://cloud.githubusercontent.com/assets/16109226/22805191/6c036a96-eeea-11e6-9a1b-9ada6747deca.png)

Thanks! 

Sorry my bad english.

**Comment by pleerock** [comment]
you should use methods from [TreeRepository](https://github.com/typeorm/typeorm/blob/master/src/repository/TreeRepository.ts). Use `findTrees` method to find all trees of the closure table. I has been added by me in `0.0.9-alpha.3`, install this version first.

**Comment by erlopezh** [comment]
Hello again, sorry my basic English.
With ClosureEntity defined as the images shown, the closure table data represents a graph. 
![image](https://cloud.githubusercontent.com/assets/16109226/23934671/ecd08aca-0914-11e7-8b08-c5dc7df3a8f0.png)

I have installed `0.0.9` version and using `findTrees` the result obtained is a hierarchical tree where C node descendants don´t have the D node

![image](https://cloud.githubusercontent.com/assets/16109226/23934723/4275088e-0915-11e7-9a2d-61c736a3a355.png)

but the expected result is two trees where D is child node in both :

![image](https://cloud.githubusercontent.com/assets/16109226/23934789/990f73a0-0915-11e7-89ec-26598a21eb67.png)

Is there a way for get this result?

Thanks a lot.

**Comment by pleerock** [comment]
I've got what you mean. Your data is actually a graph, not a regular tree. This functionality is not supported. Only regular trees are supported by closure entities. 

However if your task is to save something twice on different nodes of a tree, you can change structure of your data:


```json
[
    {
        node: "A",
        category: 1,
        children: [
            {
                node: "B",
                category: 2
            }
        ]
    },
    {
        node: "C",
        category: 3,
        children: [
            {
                node: "D",
                category: 2
            }
        ]
    }
]
```

See in this example category `2` is used twice. You can use this technic if it fits your task.

**Comment by pleerock** [comment]
I hope I answered your question.
