### ISSUE TITLE
where on relationship in repository

### ISSUE THREAD

**Issue by filipcro** [typeorm/typeorm#2743]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`

Hello to everybody. I'm trying to query using join on multiple tables.  
Also I'd like to put where options on my join tables. This is what I tried.
```
const user = await getConnection().getRepository(User).findOne(
    userId,
    {
        relations: [
            'accounts',
            'accounts.transactions',
            'accounts.transactions.category'
        ],
        where: {
            'accounts.transactions.dateTime': Between(startDate, endDate)
        }
    });
```

I also tried using all of those:
```
dateTime: Between(startDate, endDate),
'transaction.dateTime': Between(startDate, endDate),
'user.accounts.transactions.dateTime': Between(startDate, endDate),
```
but also without success. If that can't be done, then I'd like to request a feature, and also can you please help me to select those transactions using query builder? I don't now how to join those two tables to extract data. Worst case I'll use raw SQL but for now I don't want to.

**Comment by Kononnable** [comment]
Did you resolve your issue?

**Comment by filipcro** [comment]
Oh that was ages ago :)

Anyway I didn't use `TypeORM` few months so I don't know if this feature was implemented. I'd hope so because it can be useful when building APIs.

I selected transactions using this query:

        const transactions = await getConnection()
            .getRepository(Transaction)
            .createQueryBuilder('transaction')
            .innerJoin('transaction.account', 'account')
            .where('transaction.dateTime >= :startDate', { startDate })
            .andWhere('transaction.dateTime <= :endDate', { endDate })
            .andWhere('account.userId = :userId', { userId })
            .getMany();

**Comment by vlapo** [comment]
Query builder is the only way to achieve this for now.

**Comment by vpaul08** [comment]
I don't think so. This is something I found on TypeORM doc (https://github.com/typeorm/typeorm/blob/master/docs/find-options.md):

`userRepository.find({ where: { name: { first: "Timber", last: "Saw" } } });`

Don't know how to use it and have been struggling to do something similar and need to use repository to prevent a huge refator.
