### ISSUE TITLE
Add creating wildcard queries to documentation

### ISSUE THREAD

**Issue by basvdijk** [typeorm/typeorm#2744]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have this querybuilder, created with information taken from the docs

```
    const users = await this.usersRepository.find({
      skip,
      take,
      order: sortingObject,
      join: {
          alias: 'user',
          leftJoinAndSelect: {
              country: 'user.country_id',
          },
      },
    });
```

However I am unable to find information how to add a `where` or `like` with a wildcard selection e.g. `%john%`

Note: Created a StackOverflow question to solve this: https://stackoverflow.com/questions/52100765/like-query-in-typeorm

**Comment by imnotjames** [comment]
```
const users = await this.usersRepository.find({
      where: { name: Like("%john%") },
      skip,
      take,
      order: sortingObject,
      join: {
          alias: 'user',
          leftJoinAndSelect: {
              country: 'user.country_id',
          },
      },
    });
```

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
