### ISSUE TITLE
sometimes magical things happen because of getRawMany()

### ISSUE THREAD

**Issue by ykxhzfj** [typeorm/typeorm#2747]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

getRawMany() Sometimes can't work correctly with `leftJoinAndSelect().offset().limit();

const userInfoWithOLRaw = await userRepo.createQueryBuilder('user').leftJoinAndSelect('user.posts', 'post').offset(1).limit(6).getRawMany();

const userInfoWithSTRaw = await userRepo.createQueryBuilder('user').leftJoinAndSelect('user.posts', 'post').getRawMany();

console.table(userInfoWithOLRaw);
console.table(userInfoWithSTRaw);

│ (index) │ user_id │ user_name │ post_id │    post_title    │ post_userId │
│    0    │    1    │ 'user_1'  │    1    │ 'user_1_title_1' │      1      │
│    1    │    2    │ 'user_2'  │    4    │ 'user_2_title_2' │      2      │
│    2    │    2    │ 'user_2'  │    3    │ 'user_2_title_1' │      2      │
│    3    │    3    │ 'user_3'  │    6    │ 'user_3_title_2' │      3      │
│    4    │    3    │ 'user_3'  │    5    │ 'user_3_title_1' │      3      │
│    5    │    4    │ 'user_4'  │    8    │ 'user_4_title_2' │      4      │

│ (index) │ user_id │ user_name │ post_id │    post_title     │ post_userId │
│    0    │    1    │ 'user_1'  │    1    │ 'user_1_title_1'  │      1      │
│    1    │    1    │ 'user_1'  │    2    │ 'user_1_title_2'  │      1      │
│    2    │    2    │ 'user_2'  │    3    │ 'user_2_title_1'  │      2      │
│    3    │    2    │ 'user_2'  │    4    │ 'user_2_title_2'  │      2      │
│    4    │    3    │ 'user_3'  │    5    │ 'user_3_title_1'  │      3      │
│    5    │    3    │ 'user_3'  │    6    │ 'user_3_title_2'  │      3      │
│    6    │    4    │ 'user_4'  │    7    │ 'user_4_title_1'  │      4      │
│    7    │    4    │ 'user_4'  │    8    │ 'user_4_title_2'  │      4      │
│    8    │    5    │ 'user_5'  │    9    │ 'user_5_title_1'  │      5      │
│    9    │    5    │ 'user_5'  │   10    │ 'user_5_title_2'  │      5      │
│   10    │    6    │ 'user_6'  │   11    │ 'user_6_title_1'  │      6      │
│   11    │    6    │ 'user_6'  │   12    │ 'user_6_title_2'  │      6      │
│   12    │    7    │ 'user_7'  │   13    │ 'user_7_title_1'  │      7      │
│   13    │    7    │ 'user_7'  │   14    │ 'user_7_title_2'  │      7      │
│   14    │    8    │ 'user_8'  │   15    │ 'user_8_title_1'  │      8      │
│   15    │    8    │ 'user_8'  │   16    │ 'user_8_title_2'  │      8      │
│   16    │    9    │ 'user_9'  │   17    │ 'user_9_title_1'  │      9      │
│   17    │    9    │ 'user_9'  │   18    │ 'user_9_title_2'  │      9      │
│   18    │   10    │ 'user_10' │   19    │ 'user_10_title_1' │     10      │
│   19    │   10    │ 'user_10' │   20    │ 'user_10_title_2' │     10      │
│   20    │   10    │ 'user_10' │   21    │ 'user_10_title_3' │     10      │
│   21    │   10    │ 'user_10' │   22    │ 'user_10_title_4' │     10      │

Obvious,the post_id was reversed when i use offset() and limit().
However, sometimes it can give me the correctly results.
Through my experiment,I found that  has nothing to do with the parity of the number of results.
why?

**Comment by hielkehoeve** [comment]
Cany you provide the generated SQL?

Because databases do not guarantee they will return the same subset when using offset & limit you should always explicitly add one or more order by `id`s to ensure that the database returns the same subset for the same offset & limit.

**Comment by ykxhzfj** [comment]
Thank u. You mean that i should add "order by post_id" when i use offset() and limit()?

**Comment by Kononnable** [comment]
You should order by by something distinct to this query - we don't know your entities so we don't know if post_id would be enough.
