### ISSUE TITLE
The default column is not present after calling save

### ISSUE THREAD

**Issue by rianby64** [typeorm/typeorm#2756]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Given the following migration
```ts
export class Post1535782493710 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
      await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS incr_by_db_seq;`);
      await queryRunner.query(`
        CREATE TABLE IF NOT EXISTS "post"
          (
              id serial NOT NULL,
              incr integer NOT NULL DEFAULT nextval('incr_by_db_seq'),
              title character varying(255),
              CONSTRAINT post_pkey PRIMARY KEY (id)
          );
      `);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
      await queryRunner.query(`DROP SEQUENCE IF EXISTS incr_by_db_seq;`);
      await queryRunner.query(`DROP TABLE IF EXISTS "post";`);
    }

}
```
The entity looks like
```ts

@Entity()
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    incr: number;

    @Column()
    title: string;

}
```

If perform a save call, then the result doesn't contain the column ```incr```
```ts
const post = new Post();
post.title = "Super title";
const result = await connection.manager.save(post);

expect(result).not.to.be.empty;
expect(result!.title).not.to.be.empty;
result!.title.should.be.equal("Super title");

expect(result!.incr_by_db, "incr field is present").not.to.be.empty;
expect(result!.incr_by_db).to.be.greaterThan(0);
```

**Comment by rianby64** [comment]
If you configure the entity as follows
```ts
@Entity()
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        default: 'whatever'
    })
    incr: number;

    @Column()
    title: string;

}
```

then, the field ```incr``` will be present after calling ```save```.

**Comment by pleerock** [comment]
@Kononnable can you help here? Im not sure I understood what author means here. Also he provided a PR but it doesn't change any file, only tests, and, at the same time, tests aren't failed.

**Comment by rianby64** [comment]
Here the meaning is that the behavior for `default` values is working incorrectly. Take a look to the field `incr`. Notice that this field has a default value given by Postgres. But for some strange reasons that default value from Postgres is not available when performing a post action.

**Comment by Kononnable** [comment]
Tbh description isn't very helpful. It requires to run the code, play with it a bit to see whats actually issue is about. Tests in PR can't be even merged because it is only postgres specific(sql syntax) and there is `connection.dropDatabase()`.

The important part: after `const result = await connection.manager.save(post);` there is no `incr` property in the result.
```
query: INSERT INTO "post"("incr", "title") VALUES (DEFAULT, $1) RETURNING "id" -- PARAMETERS: ["Super title"]
query: COMMIT
Post { title: 'Super title', id: 3 }
```

**Comment by rianby64** [comment]
My PR is not intended to be merged. It's an explanation of this case. You correctly found the root of this issue. If you define a model, and one field of this model has a default value given by postgres, then I'm expecting to see that field in the result of a `post` action. If not, then I'm forced to write a second request based on the last id, which is undesirable.

**Comment by imnotjames** [comment]
The related PR tests passed.  I don't believe this is an issue any longer.
