### ISSUE TITLE
Incorrect SELECT query being generated.

### ISSUE THREAD

**Issue by kuldeeps48** [typeorm/typeorm#2759]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Entity Class:  
```typescript
@Entity('hca_reader_settings')
export class ReaderSettingsEntity {
  @PrimaryColumn({ default: 1 })
  public id: number;

  @Column({
    name: 'read_count_for_tag_entry',
    nullable: false
  })
  public readCountForTagEntry: number;

  @Column({
    name: 'time_before_tag_exit',
    nullable: false
  })
  public timeBeforeTagExit: number;

  @Column({
    name: 'number_of_bytes_to_send',
    nullable: false
  })
  public numberOfBytesToSend: number;

  @Column({
    name: 'initial_bytes_to_match',
    type: 'varchar2',
    length: 256,
    nullable: true
  })
  public initialBytesToMatch: string;

  @Column({ name: 'created_by', type: 'varchar2', length: 64, nullable: false })
  public createdBy: string;

  @Column({ name: 'updated_by', type: 'varchar2', length: 64, nullable: false })
  public updatedBy: string;

  @CreateDateColumn({
    name: 'created_at',
    type: 'timestamp',
    nullable: false
  })
  public createdAt: Date;

  @UpdateDateColumn({
    name: 'updated_at',
    type: 'timestamp',
    nullable: false
  })
  public updatedAt: Date;

  @VersionColumn({
    nullable: false
  })
  public version: number;
}
```
When creating an entry in database:  
```Typescript
const config = {
      readCountForTagEntry: 10,
      timeBeforeTagExit: 10000,
      numberOfBytesToSend: 4,
      initialBytesToMatch: '',
      createdBy: 'HCA_SERVER',
      updatedBy: 'HCA_SERVER',
      version: 1
    };
```
Entry is created properly inside database as shown below:  
![db](https://user-images.githubusercontent.com/10128989/44958149-836f4f80-aef9-11e8-8bb6-cbacd40e6eb2.png)

When querying (find()), the query is incorrectly generated:  
![query](https://user-images.githubusercontent.com/10128989/44958162-aac61c80-aef9-11e8-80bd-b337ca2eaa90.png)

=> "ReaderSettingsEntity"."updated_by" AS "ReaderSettingsEntity_up"  
=> "ReaderSettingsEntity"."updated_at" AS "ReaderSettingsEntity_up"  
and  
=> "ReaderSettingsEntity"."created_at" AS "ReaderSettingsEntity_cr"  
=> "ReaderSettingsEntity"."created_by" AS "ReaderSettingsEntity_cr"  

And the result object we get is incorrect:

![output](https://user-images.githubusercontent.com/10128989/44958166-b9143880-aef9-11e8-9e32-63c2d41be4d4.png)

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by kuldeeps48** [comment]
Looks like Oracle 12.1 limitation of 30BYTES identifiers. 
Any way of manually giving alias while querying? Maybe provide in entity?
Thanks

**Comment by imnotjames** [comment]
This should be fixed as of a few releases ago - a number of oracle identifier length fixes were merged.

If there are any other issues, let's reopen this but for now I'm closing it.
