### ISSUE TITLE
Find conditions as Partial<Entity>

### ISSUE THREAD

**Issue by aequasi** [typeorm/typeorm#276]
Would it be possible to change the find conditions to `Partial<Entity>`, that way we get validation and intellisense?

**Comment by pleerock** [comment]
yes, this is a planned feature and it will be a breaking change. Probably you can expect this feature at the end of this month

**Comment by aequasi** [comment]
Awesome :D

**Comment by pleerock** [comment]
This feature is implemented on separate mongodb branch and will be available soon in `0.1.0-alpha.1` so I'll close this issue.

**Comment by pablocarreraest** [comment]
Hi, @pleerock can you help me with a small example how use findOne(options: FindOptions) with a WHERE [User].[username] = 'foo' OR [User].[email] = 'foo'). thanks in advance. 🙏

**Comment by pleerock** [comment]
@pablocarreraest 

```ts
repository
   .createQueryBuilder("user")
   .where("user.username = :username", { username: "foo" })
   .orWhere("user.email = :email", { email: "bar" })
   .getMany();
```
