### ISSUE TITLE
May we have @NullableColumn decorator

### ISSUE THREAD

**Issue by otienoanyango** [typeorm/typeorm#2762]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

Since we can't have the more elegant ? operator, requesting a @NullableColumn() decorator as shorthand for Column({nullable: true}). Having a lot of nullable fields looks a little crowded with the current method.

**Comment by afurculita** [comment]
@otienoanyango  Any reason for this?

**Comment by Kononnable** [comment]
`?` doesn't mean that something is nullable, it means that it can be undefined.

**Comment by vlapo** [comment]
I think this is just another shortcut we have to maintain and possible place to bug or forgot this exists... `@Column({nullable: true})` is almost same length as `@NullableColumn()`. We should close this.

**Comment by Kononnable** [comment]
I agree - since we want to entity schemas be a primary way of defining a database schema model I don't think new decorator is necessary(you can still implement it in your code).
