### ISSUE TITLE
Typeorm tries and fails to find a lowercased column name

### ISSUE THREAD

**Issue by dtruel** [typeorm/typeorm#2763]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Thanks for the hard work on TypeOrm! It's great!  I have a problem though.
I have a simple table called UserLoginToken that contains this column.

```typescript

@Entity()
export class UserLoginToken extends BaseEntity {

	@Column()
	LoginToken: string = null;
}
```

When attempting to run, a query I get this error:
`QueryFailedError: column "logintoken" does not exist`
When I change the name of the variable to `logintoken` it works.  Doing `@Column({name:"LoginToken"})` doesn't fix it.

Any idea what's going on?

**Comment by gintsgints** [comment]
This test works fine for me - https://github.com/gintsgints/typeorm/commit/bb4477326f2f381d8dcc0263557e9f08d3b5db84

Please compare and check what's diffrence.

**Comment by dtruel** [comment]
Ok I figured out what query was causing the problem, although I can't figure out why:

```typescript
connection.getRepository(UserLoginToken)
.createQueryBuilder("UserLoginToken")
.where("LoginToken = :loginToken", { loginToken: authKey })
.andWhere("ExpiresAt > NOW()").getOne();
```

**Comment by dtruel** [comment]
Well, I now know what the issue is. Apparently when doing a raw query and your column names are not lowercase, you have to put them in quotes!

**Comment by gintsgints** [comment]
Good to know you solved your problem.

**Comment by ambroiseRabier** [comment]
Well I was using orderBy with the column name without additional quotes, took me good 2 hours to find out you had to add quotes:

```
  async getRecent(offset: number = 0): Promise<Article[]> {
    return await this.repository.createQueryBuilder()
      .orderBy('createdAt', 'ASC') // '"createdAt"' is ok
      .offset(offset)
      .limit(20)
      .getMany();
  }
```

Sometimes I wonder if I would be better of just using raw query, so at least I would not have to suspect the ORM or my usage of it.

**Comment by JJK801** [comment]
I had the same issue while generating a view with migrations.

This works:
```
@ViewEntity({
    expression: (connection: Connection) => connection.createQueryBuilder()
        .select('m."myColumn"')
        .from(MyModel, 'm')
        .groupBy('m."id"')
})
```

But not:
```
@ViewEntity({
    expression: (connection: Connection) => connection.createQueryBuilder()
        .select('m.myColumn')
        .from(MyModel, 'm')
        .groupBy('m.id')
})
```
