### ISSUE TITLE
Many-to-Many Rel. Migration Missing Index on both FKs

### ISSUE THREAD

**Issue by larkintuckerllc** [typeorm/typeorm#2766]
**Issue type:**

[ X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Following instructions on creating Many-to-Many relationships, i.e., 
https://github.com/typeorm/typeorm#creating-a-many-to-many-relation

When I look at the generated (generating migration with TypeORM) table (used Todo instead of Album):

```
hellodb=> \d todo_categories_category
        Table "public.todo_categories_category"
   Column   |  Type   | Collation | Nullable | Default 
------------+---------+-----------+----------+---------
 todoId     | integer |           | not null | 
 categoryId | integer |           | not null | 
Indexes:
    "PK_5131c830636d855568d3a70c352" PRIMARY KEY, btree ("todoId", "categoryId")
Foreign-key constraints:
    "FK_4347fec6e6cc3be4ce39d9d9f36" FOREIGN KEY ("todoId") REFERENCES todo(id) 
ON DELETE CASCADE
    "FK_80456ff2d7fd676c1ac2d107f31" FOREIGN KEY ("categoryId") REFERENCES categ
ory(id) ON DELETE CASCADE

```

There is NO INDEX on categoryId.  My understanding of SQL would suggest then if I am searching for todos in a specific category the query has to scan the entire table. So, I want an index on categoryId.

Could not find a way to create this index using decorators on the entities.

Did create a migration that creates the index, BUT...

The next time I generate a migration, the migration wants to drop the index I created (because it is managing that table).

What am I missing?

**Comment by Kononnable** [comment]
@larkintuckerllc 
Did you resolve your issue?

**Comment by Kononnable** [comment]
Closing as no response from the author.
