### ISSUE TITLE
Set reference to null?

### ISSUE THREAD

**Issue by tombolala** [typeorm/typeorm#2767]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, 

I am new to typeorm and I like it very much!

Now I have some problem removing some reference from one entity to another. Apparently, its not possible to set null or undefined.

    @ManyToOne(type => Rezept, rezept => rezept.termine, {nullable: true, eager: true})
    rezept: Rezept

I assigned some "Rezept" to this entity, but I need to remove this again - my guess was this.rezept = null, but I get an error there. I am also new to typescript ;-)

Thanx in advance,
Thomas

PS: I also got some issue, that I need to set synchronize to "false". Otherwise some many-to-many relations are removed again all the time (database entries in assoc-table are going away after "synchronization"?!)

**Comment by Kononnable** [comment]
Looks like you found your answer :)
