### ISSUE TITLE
possible bug with eager loading?

### ISSUE THREAD

**Issue by tombolala** [typeorm/typeorm#2768]
**Issue type:**

[ x] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

maybe I am doing something wrong, but I noticed definitely, that whatever side the eager goes on a one-to-many relationship, only that side will show the value.

    in Termin:
    @ManyToOne(type => Rezept, rezept => rezept.termine, {nullable: true})
    rezept: Rezept

    in Rezept:
    @OneToMany(type => Termin, termin => termin.rezept, { eager: true })    
    termine: Termin[]

I just moved the eager from the "termine"-place to "rezept" (see above) and now I got a count of "termine", which was undefined before, but the other place where I show the linked "rezept" is now undefined?!

Both, "Termin" and "Rezept" are linked from patient, which is the "entry point", so I am loading patient first:
let termin of patient.termine
    termin.rezept is undefined if "eager" is on rezept.termine and set correctly to the "rezept" if "eager" is on termin.rezept
let rezept of patient.rezepte
   rezept.termine is an array of termine if "eager" is on rezept.termine, but is undefined if eager is on termine.rezept

    Patient:
    @OneToMany(type => Termin, termin => termin.patient, { eager: true})
    termine: Termin[];  

    @OneToMany(type => Rezept, rezept => rezept.patient, {eager: true})
    rezepte: Rezept[]

Best regards,
Thomas

**Comment by septk** [comment]
same here

**Comment by pleerock** [comment]
its not a bug, its just how lazy load works - it loads eagerly only from one side, to prevent circular issues.

**Comment by tombolala** [comment]
then, how do you load it from the other side?

**Comment by pleerock** [comment]
its the same data as you have from first side, right? You can manually assign data if you need.
