### ISSUE TITLE
Could we add support for the MySQL/MariaDB SET data type?

### ISSUE THREAD

**Issue by AlliterativeAlice** [typeorm/typeorm#2779]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Along with the ENUM data type, MySQL and MariaDB (and possibly other database systems) have a [SET data type](https://dev.mysql.com/doc/refman/8.0/en/set.html). It works like ENUM but allows for the column to hold multiple values. Could we add support for this data type to TypeORM?

Creating a column with a SET datatype could look like this:

```ts
enum Role {
  Admin = "Admin",
  Support = "Support",
  Developer = "Developer"
}

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column('set', { enum: Role })
    roles: Role[];
}
```

We can accomplish something similar with the simple array type, but having support for SET would be nice.

**Comment by kirrie** [comment]
any updates?

**Comment by SethVerishop** [comment]
https://github.com/typeorm/typeorm/pull/7665
Added this so that data-api can use this type also.
Fixes DataTypeNotSupportedError ... is not supported by "aurora-data-api" database.
