### ISSUE TITLE
Unable to connect to Heroku postgres from outside of Heroku

### ISSUE THREAD

**Issue by thiago-soliveira** [typeorm/typeorm#278]
In order to connect to Heroku postgres from outside of Heroku we need to use SSL.

So, I'm getting the following message when trying to connect typeorm to the Heroku postgres.

```
"message": "no pg_hba.conf entry for host "xxx", user "xxx", database "xxx", SSL off"
```

I believe this is happening because the postgres driver is trying to connect without SSL. If I'm correct, how can I tell the sql driver to use SSL.

**Comment by pleerock** [comment]
Solution is [here](http://stackoverflow.com/questions/22301722/ssl-for-postgresql-connection-nodejs). To do so in typeorm you need to provide option in special "extra" section of connection options:

```typescript
createConnection(
    driver: {
        type: "postgres",
        host: "localhost",
        port: 5432,
        username: "root",
        password: "admin",
        database: "test",
        extra: {
             ssl: true
        }
    },);
```

**Comment by AngelMunoz** [comment]
hey sorry old issue, but how do you set this with .env file or env vars?

**Comment by pleerock** [comment]
You need to set 

```env
TYPEORM_DRIVER_EXTRA = {"ssl":true}
```

**Comment by AngelMunoz** [comment]
thanks it did work

**Comment by pie6k** [comment]
In my case:

1. put what you get from `heroku config:get DATABASE_URL` to your `.env` file (heroku will automatically add that to `process.env`

2. connect with:

```
createConnection({
    url: process.env.DATABASE_URL,
    type: 'postgres',
    entities: [YOUR ENTITIES GO HERE],
    synchronize: true,
    extra: {
      ssl: true,
    },
  });
```

**Comment by N-CP** [comment]
I m trying to connect postgresql heroku to oracle sql developer. But i m getting the below error

message": "no pg_hba.conf entry for host "xxx", user "xxx", database "xxx", SSL off"

what could be the solution?
can anybody help me in this pls??

**Comment by jmaicaaan** [comment]
@N-CP, what is your `ormconfig` looks like?

**Comment by a1300** [comment]
For me it worked with:
```diff
createConnection({
    url: process.env.DATABASE_URL,
    type: 'postgres',
    entities: [YOUR ENTITIES GO HERE],
    synchronize: true,
+   ssl: true,
  });
```

**Comment by nilfalse** [comment]
I believe the original issue and the solutions (both JSON & env) has to be documented.

Would such pull request for docs website be accepted?

**Comment by Kononnable** [comment]
SSL options are already documented (https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md). However if you find a good place to remind about that(common problem?) PR will be accepted.

**Comment by AllanPamplona** [comment]
Also PGSSLMODE=require solves this problem.

**Comment by rakeshta** [comment]
> For me it worked with:
> 
> ```diff
> createConnection({
>     url: process.env.DATABASE_URL,
>     type: 'postgres',
>     entities: [YOUR ENTITIES GO HERE],
>     synchronize: true,
> +   ssl: true,
>   });
> ```

worked for me too.

**Comment by idudinov** [comment]
hi there!
still don't able to connect to remote Heroku Postgres server from local machine, my config looks like:

```typescript
const config: PostgresConnectionOptions = {
    ...baseConfig, // here're common settings
    url: process.env.DATABASE_URL, // got from DATABASE_URL config var in Heroku
    ssl: true, // double check
    extra: {
        ssl: true,
    },
};
```

also tried to set up `PGSSLMODE=require` as env var.

getting the error:

```bash
[ServerSetup] TypeORM connection error:  Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
```

not sure what certificate should I use, or can I bypass it somehow?

thanks in advance!

**Comment by idudinov** [comment]
jeez it fails on Heroku as well! 
pgAdmin connects successfully with such SSL options:
![image](https://user-images.githubusercontent.com/15375564/69616998-34eb2b00-1040-11ea-8e6d-0bb21685a049.png)

**Comment by JakeSidSmith** [comment]
@idudinov

> getting the error:
> 
> ```shell
> Error: self signed certificate
>     at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
>     at TLSSocket.emit (events.js:210:5)
>     at TLSSocket._finishInit (_tls_wrap.js:794:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
>   code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
> }
> ```
> 
> not sure what certificate should I use, or can I bypass it somehow?
> 
> thanks in advance!

I've just run into this issue and it seems that `node-postgres` have added an option to disable rejecting unauthorized connections. I don't think this is safe to run in production though. I'm just using it to run my migrations.

I believe the ideal solution is to get a new SSL certificate, but for now I have:

```
  ssl: true,
  extra: {
    ssl: {
      rejectUnauthorized: false,
    },
  },
```

**Comment by ownedbypeli** [comment]
so you arent using the typeorm ormconfig.json?

**Comment by aliskhanoff** [comment]
> 
> 
> @idudinov
> 
> > getting the error:
> > ```shell
> > Error: self signed certificate
> >     at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
> >     at TLSSocket.emit (events.js:210:5)
> >     at TLSSocket._finishInit (_tls_wrap.js:794:8)
> >     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
> >   code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
> > }
> > ```
> > 
> > 
> > not sure what certificate should I use, or can I bypass it somehow?
> > thanks in advance!
> 
> I've just run into this issue and it seems that `node-postgres` have added an option to disable rejecting unauthorized connections. I don't think this is safe to run in production though. I'm just using it to run my migrations.
> 
> I believe the ideal solution is to get a new SSL certificate, but for now I have:
> 
> ```
>   ssl: true,
>   extra: {
>     ssl: {
>       rejectUnauthorized: false,
>     },
>   },
> ```

it works for me. Thanks!

**Comment by italodeandra** [comment]
What fixed for me while using Postgres from Heroku was only adding the following environment variable:

```
PGSSLMODE=no-verify
```

**Comment by Haple** [comment]
What worked for me:

```
{
...
    "password": ...,
    "database": ...,
    "ssl": {
        "rejectUnauthorized": false,
    },
...
}
```

**Comment by kvarela** [comment]
> What worked for me:
> 
> ```
> {
> ...
>     "password": ...,
>     "database": ...,
>     "ssl": {
>         "rejectUnauthorized": false,
>     },
> ...
> }
> ```

Yes, this for me also, AND I had to REMOVE:
```
{
  extra: {
    ssl: true
  }
}
```
What a PITA

**Comment by altschuler** [comment]
If, like me, you added `?ssl=true` to the url, then the `rejectUnauthorized` wont work. You need to either remove the ssl param from the URL _or_ set it to `ssl=no-verify` in which case you can remove the ssl options from the typeorm config altogether. Found the answer here https://github.com/brianc/node-postgres/issues/2009#issuecomment-627817773

**Comment by agilatakishiyev** [comment]
> @idudinov
> 
> > getting the error:
> > ```shell
> > Error: self signed certificate
> >     at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
> >     at TLSSocket.emit (events.js:210:5)
> >     at TLSSocket._finishInit (_tls_wrap.js:794:8)
> >     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
> >   code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
> > }
> > ```
> > 
> > 
> > not sure what certificate should I use, or can I bypass it somehow?
> > thanks in advance!
> 
> I've just run into this issue and it seems that `node-postgres` have added an option to disable rejecting unauthorized connections. I don't think this is safe to run in production though. I'm just using it to run my migrations.
> 
> I believe the ideal solution is to get a new SSL certificate, but for now I have:
> 
> ```
>   ssl: true,
>   extra: {
>     ssl: {
>       rejectUnauthorized: false,
>     },
>   },
> ```

thanks a lot it worked for me too
i was using typeorm and nest.js and i was getting this error while connecting a database located in digitalocean

**Comment by benjaminudoh10** [comment]
> @idudinov
> 
> > getting the error:
> > ```shell
> > Error: self signed certificate
> >     at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
> >     at TLSSocket.emit (events.js:210:5)
> >     at TLSSocket._finishInit (_tls_wrap.js:794:8)
> >     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
> >   code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
> > }
> > ```
> > 
> > 
> > not sure what certificate should I use, or can I bypass it somehow?
> > thanks in advance!
> 
> I've just run into this issue and it seems that `node-postgres` have added an option to disable rejecting unauthorized connections. I don't think this is safe to run in production though. I'm just using it to run my migrations.
> 
> I believe the ideal solution is to get a new SSL certificate, but for now I have:
> 
> ```
>   ssl: true,
>   extra: {
>     ssl: {
>       rejectUnauthorized: false,
>     },
>   },
> ```

Thank you so much for this. I have searched everywhere. All the solutions on this thread did not work for me except this.

Thanks again.

**Comment by JakeSidSmith** [comment]
> @idudinov
> 
> > getting the error:
> > ```shell
> > Error: self signed certificate
> >     at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
> >     at TLSSocket.emit (events.js:210:5)
> >     at TLSSocket._finishInit (_tls_wrap.js:794:8)
> >     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
> >   code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
> > }
> > ```
> > 
> > 
> > not sure what certificate should I use, or can I bypass it somehow?
> > thanks in advance!
> 
> I've just run into this issue and it seems that `node-postgres` have added an option to disable rejecting unauthorized connections. I don't think this is safe to run in production though. I'm just using it to run my migrations.
> 
> I believe the ideal solution is to get a new SSL certificate, but for now I have:
> 
> ```
>   ssl: true,
>   extra: {
>     ssl: {
>       rejectUnauthorized: false,
>     },
>   },
> ```

Just as a follow up, since Heroku [enforced SSL for all postgres connections](https://devcenter.heroku.com/changelog-items/2035) the above is the [solution they recommend](https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js).

So I guess it is safe for production. 😊

**Comment by revskill10** [comment]
Guys, the issue is in the `PGSSLMODE=no-verify` combined with 
```
extra: {
    ssl: {
      rejectUnauthorized: false,
    },
  },
```

**Comment by lenybernard** [comment]
I resolve my issue by setting `NODE_TLS_REJECT_UNAUTHORIZED=0` to heroku env vars (see https://stackoverflow.com/a/45088585).

This was not a typeorm issue, it's because heroku use self signed certificates.
