### ISSUE TITLE
@Generated() columns does not return values on update

### ISSUE THREAD

**Issue by johvik** [typeorm/typeorm#2780]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Create an entity like this:
```typescript
@Entity()
export class Test {
    @Generated()
    @Index({ unique: true })
    @Column()
    id: number;

    @PrimaryColumn()
    name: string;
}
```

Run this code twice:
```typescript
const repo = connection.getRepository(Test);
const test = repo.create({ name: "abc" });
await repo.save(test);
console.log(test);
```

Notice that the second time (the update) does not print the id column. Isn't the generated columns supposed to be returned on update? Or does it only apply to the `@PrimaryGeneratedColumn` ones?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
```typescript
/**
 * Marks a column to generate a value on entity insertion.
 * There are two types of generation strategy - increment and uuid.
 * Increment uses a number which increases by one on each insertion.
 * Uuid generates a special UUID token.
 *
 * Note, some databases do not support non-primary generation columns.
 */
```
Value is generated on entity insertion, not on update so there is no need to fetch value on entity update. `@PrimaryGeneratedColumn` are returned on update because every column which is part of PK is returned(not because it's marked as generated).
