### ISSUE TITLE
How to elegantly divide the table by month?

### ISSUE THREAD

**Issue by whtiehack** [typeorm/typeorm#2785]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

For example,this is my entity:

```ts
// Photo2 entity

import {Entity, Column, PrimaryGeneratedColumn} from "typeorm";

@Entity()
export class Photo2 {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        length: 100
    })
    name: string;

    @Column("text")
    description: string;

    @Column()
    date: Date;
}

```

Now,the table name is `photo2`, but I need to change the table name every month.
`rename table photo2 to photo2_2018_09; create table photo2 .....` etc...

There is no idea after using typeorm, thank you.

**Comment by AlliterativeAlice** [comment]
Rather than using TypeORM to do this, you should probably create a stored procedure to do this and [create a SQLServer Agent Job](https://docs.microsoft.com/en-us/sql/ssms/agent/create-a-job?view=sql-server-2017) to run the stored procedure each month.

**Comment by whtiehack** [comment]
@AlliterativeAlice  Thanks for answer, I has understand .
