### ISSUE TITLE
down migration generation: quotes added for default CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by Darkein** [typeorm/typeorm#2786]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
generate a migration with an entity whose has a date property, remove it, and generate a new migration.

Hello,
I have a little bug with an alter table DEFAULT CURRENT_TIMESTAMP generated in the `down` method: quotes are added around it. I don't have any problem with the up() generation. for example:

my first generated migration:
```javascript
export class initDatabase1534947089809 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(
      'CREATE TABLE `recruitment` (`id` int NOT NULL AUTO_INCREMENT, `title` varchar(255) NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB'
    );
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query('DROP TABLE `recruitment`');
  }
}
```

and the second one: 
```javascript
export class recruitment1536568838058 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `recruitment` DROP COLUMN `created_at`");
        await queryRunner.query("ALTER TABLE `recruitment` DROP COLUMN `updated_at`");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `recruitment` ADD `updated_at` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
        await queryRunner.query("ALTER TABLE `recruitment` ADD `created_at` datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'");
    }

}
```
**`DEFAULT 'CURRENT_TIMESTAMP(6)'`** should be **`DEFAULT CURRENT_TIMESTAMP(6)`**

thanks!

**Comment by AlexMesser** [comment]
I tested it and it looks like this issue has been fixed already. Please update your TypeORM version and reopen this issue if you run into this error again.
