### ISSUE TITLE
Querying nested fields

### ISSUE THREAD

**Issue by rosshadden** [typeorm/typeorm#2789]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Question:**

How do you query on nested fields? For example, given a collection of records like:

```javascript
{
    foo: {
        bar: 'baz'
    }
},
{
    foo: {
        bar: 'qux'
    }
}
```

how do I get this query to work?:

```javascript
Things.find({
    foo: {
        bar: 'baz'
    }
});
```

**Comment by rosshadden** [comment]
Also, how do I index nested fields? This should technically be a separate issue/question, but it is very related.

If I have an `@orm.Index()` decorator on a field that is not at the root level of an entity, it seems to create an index for the field as if it were at the root level, as best as I can tell.
That is, if the path of the field I am trying to index is `foo.bar` like in my example above, an index is created for `bar`, not `foo.bar`.

**Comment by nico29** [comment]
I think I've managed to have it worked by querying "mongo style".

```typscript
Things.find({'foo.bar': 'baz'};
```

The query seems to be unaltered and sent as is to the Mongo driver, but this does not pass type checking.

**Comment by rustamwin** [comment]
Please follow a discussion in #3756
