### ISSUE TITLE
Allow casting from database to javascript

### ISSUE THREAD

**Issue by aequasi** [typeorm/typeorm#279]
I'm working with bigints in my databases that are ulongs/64bit ints, and bigger than javascript can allow in a number. Is there a way i can have the bigint cast to a string, or something like Mongo's `Long` class?

**Comment by pleerock** [comment]
How do underlying drivers handle it? Are you using mysql or pg? These drivers should handle such cases and convert to ints/strings by their own

**Comment by aequasi** [comment]
It casts into the database properly, but coming out of the database, its coming out as a `number`, and it gets chopped off

**Comment by pleerock** [comment]
same for retrieving from database - underlying drivers are handle it

**Comment by aequasi** [comment]
Well, i'm using mysql, and its not

**Comment by aequasi** [comment]
Huzzah! Not sure if this is documented, but you can pass extra options using `extra` in the driver options:

```
extra:    {
                    supportBigNumbers: true,
                    bigNumberStrings:  true,
                },
```
