### ISSUE TITLE
Passing a path to `entities` in createConnection() options in Windows doesn't find any entities

### ISSUE THREAD

**Issue by BehindTheMath** [typeorm/typeorm#2790]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

According to the docs and the examples, the `entities` options in `createConnection()` can be passed a path:
```js
createConnection({
    entities: [__dirname + '/entities/*'],
});
```

The paths are parsed by [this code](https://github.com/typeorm/typeorm/blob/b794d0c3930614a3eb16a290d8b1d0e98632e602/src/util/DirectoryExportedClassesLoader.ts#L24):
```js
return allDirs.concat(PlatformTools.load("glob").sync(PlatformTools.pathNormalize(dir)));
```

However, in Windows, in most cases, this will not return any entities. This is because [`path.normalize()`](https://nodejs.org/api/path.html#path_path_normalize_path) in Windows converts all path segment separators to `\`. As a result, something like `__dirname + '/entities/*` will be converted to `c:\Users\MyUser\MyProject\entities\*`. However, [`glob` interprets back-slashes as escape characters](https://github.com/isaacs/node-glob#windows), so that path will resolve to nothing.

It appears that the paths have to first be converted to POSIX paths before passing to `glob`.

**Comment by BehindTheMath** [comment]
The current code for [`PlatformTools.pathNormalize()`](https://github.com/typeorm/typeorm/blob/b794d0c3930614a3eb16a290d8b1d0e98632e602/src/platform/PlatformTools.ts#L132-L134) is:
```
    PlatformTools.pathNormalize = function (pathStr) {
        return path.normalize(pathStr);
    };
```

Here's a possible fix I came up with:

```
    PlatformTools.pathNormalize = function (pathStr) {
        let normalizedPath = path.normalize(pathStr);

        if (process.platform === "win32" {
            // Replace `\` with `/`
            pathStr = pathStr.replace(/\\/g, "/");

            // If the root matches something like 'C:\', drop the root
            const pathRoot = path.parse(dir).root;
            if (pathRoot.match(/.*:.*/)) {
                pathStr = pathStr.substring(pathRoot.length) - 1)
            }

            normalizedPath = path.posix.normalize(pathStr);
        }

        return normalizedPath;
    };
```

This should return a POSIX-compatible path, which can be used for `glob`.

**Comment by gintsgints** [comment]
There is error in given code:
```
entities: [__dirname + '/entities/*],'
```

should be:
```
entities: [__dirname + '/entities/*'],
```

**Comment by gintsgints** [comment]
Normalize should give two slashes on output. Try this in node (with glob installed in node_modules):
```
glob.sync(path.normalize(path.resolve('.') + '/*.json'))
[ 'C:/Users/gpolis/Documents/Private/typeorm/ormconfig.circleci.json',
  'C:/Users/gpolis/Documents/Private/typeorm/ormconfig.json',
  'C:/Users/gpolis/Documents/Private/typeorm/ormconfig.travis.json',
  'C:/Users/gpolis/Documents/Private/typeorm/package-lock.json',
  'C:/Users/gpolis/Documents/Private/typeorm/package.json',
  'C:/Users/gpolis/Documents/Private/typeorm/tsconfig.json',
  'C:/Users/gpolis/Documents/Private/typeorm/tslint.json' ]
```

**Comment by gintsgints** [comment]
@BehindTheMath  pls review and close if ok.

**Comment by BehindTheMath** [comment]
>There is error in given code:
>```entities: [__dirname + '/entities/*],'```
>should be:
>```entities: [__dirname + '/entities/*'],```

Fixed.

>Normalize should give two slashes on output. Try this in node (with glob installed in node_modules):
>
>glob.sync(path.normalize(path.resolve('.') + '/*.json'))
>[ 'C:/Users/gpolis/Documents/Private/typeorm/ormconfig.circleci.json',
>  'C:/Users/gpolis/Documents/Private/typeorm/ormconfig.json',
>  'C:/Users/gpolis/Documents/Private/typeorm/ormconfig.travis.json',
>  'C:/Users/gpolis/Documents/Private/typeorm/package-lock.json',
>  'C:/Users/gpolis/Documents/Private/typeorm/package.json',
>  'C:/Users/gpolis/Documents/Private/typeorm/tsconfig.json',
>  'C:/Users/gpolis/Documents/Private/typeorm/tslint.json' ]

I don't see how that resolves this issue. I suppose I could parse the paths myself into POSIX-compatible paths before passing them to TypeORM, but that shouldn't be necessary. As it stands right now, following the documentation will result in unexpected results.

**Comment by Kononnable** [comment]
@BehindTheMath 	@gintsgints 	
To summarize is it something here we should fix here or is it just a question on how path.normalize works?
I may have misunderstood something and don't want to close this prematurely.

**Comment by BehindTheMath** [comment]
@Kononnable This is something that IMO should be fixed. I posted a possible fix [above](https://github.com/typeorm/typeorm/issues/2790#issuecomment-420734321). I'm not sure why I didn't open a PR then. I'll try to work on that.

**Comment by BehindTheMath** [comment]
I can't reproduce the issue anymore, so I'm closing it.

**Comment by tgmarinho** [comment]
```
import { createConnection } from 'typeorm';
import path from 'path'
console.log(path.resolve(__dirname, '..', 'models/*.ts'))
createConnection({
  type: "mongodb",
  url: process.env.MONGODB_URI,
  useUnifiedTopology: true,
  useNewUrlParser: true,
  synchronize: true,
  entities: [path.resolve(__dirname, '..', 'models/*.ts')]
});
```
