### ISSUE TITLE
Creating Migrations Programmatically

### ISSUE THREAD

**Issue by ramesaliyev** [typeorm/typeorm#2792]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Can we create migrations programmatically? I've run through the documentation but cannot find. Something like `conn.generateMigration('name')` would be good.

**Comment by Kononnable** [comment]
What do you mean by create migrations programmatically? To write logic deciding if we should generate migration? 
You can exec TypeORM CLI in your code if you want your logic to define when to create automatic migrations.

**Comment by ramesaliyev** [comment]
No, I mean programmatically triggering migration script generator of typeorm. But yeah i'm trying to achieve that by calling typeorm cli from my script right now.

**Comment by Kononnable** [comment]
You could probably use `MigrationGenerateCommand` class but it creates connection on it own. 

Or write something based on that to use existing connection. https://github.com/typeorm/typeorm/blob/b794d0c3930614a3eb16a290d8b1d0e98632e602/src/commands/MigrationGenerateCommand.ts#L66-L90

**Comment by ramesaliyev** [comment]
Oh, thanks! I'll check this out.
