### ISSUE TITLE
VersionColumn shouldn't be allowed if driver is MySQL and engine is InnoDB

### ISSUE THREAD

**Issue by caseyduquettesc** [typeorm/typeorm#2798]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

According to the documentation (https://dev.mysql.com/doc/refman/8.0/en/example-auto-increment.html), `AUTO_INCREMENT` on a secondary column in a multiple-column index isn't available if your storage engine is InnoDB. 

Would be nice here (http://typeorm.io/#entities/special-columns) to see a note that `@VersionColumn` won't work in MySQL if you are using InnoDB as your engine.

I haven't tested this myself, but perusing the unit tests in the repo, it looks like you may not know about this incompatibility.
https://github.com/typeorm/typeorm/blob/a4dec02cc59d3219a29c7be0322af2253e1452dc/test/functional/schema-builder/change-column.ts#L104-L106

**Comment by imnotjames** [comment]
If MySQL handles this via emitting an error then it's working as intended.
