### ISSUE TITLE
query builder with date selection returns no result, works in DB

### ISSUE THREAD

**Issue by tombolala** [typeorm/typeorm#2799]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I run the following:
let termine: Termin[] = await getConnection().getRepository(Termin).createQueryBuilder("termin").
            where("termin.datum BETWEEN :date1 AND :date2", {date1: startDate, date2: endDate}).getMany()

logging shows:
query: SELECT "termin"."id" AS "termin_id", "termin"."datum" AS "termin_datum", "termin"."dauer" AS "termin_dauer", "termin"."patientFk" AS "termin_patientFk", "termin"."rezeptFk" AS "termin_rezeptFk", "termin"."rechnungId" AS "termin_rechnungId" FROM "termin" "termin" WHERE "termin"."datum" BETWEEN ? AND ? -- PARAMETERS: ["2018-09-09T22:00:00.000Z","2018-09-14T22:00:00.000Z"]

but got no results (termine.length is 0)

But in sqlite:
sqlite> select termin.id from termin where termin.datum between "2018-09-09T22:00:00.000Z" and "2018-09-14T22:00:00.000Z";
1
2
3
4
5

Whats going on?

Thanx in advance,
Thomas

**Comment by matomesc** [comment]
I have the same issue with postgres. Running the query logged by TypeORM works and returns results but the query builder doesn't return any data.

**Comment by Kononnable** [comment]
Can you guys provide some reproduction code/failing test?

**Comment by Kononnable** [comment]
Closing as no reproduction code/failing test.

**Comment by Adizbek** [comment]
Need proper date formating in typeorm.

For now, you can use this https://github.com/typeorm/typeorm/issues/2286#issuecomment-455872658

**Comment by stingers** [comment]
> I guess it might be some bug, I am passing two dates here, when I translate the dates to date and time in format YYYY-MM-DDTHH:MM myself it works.
this can help
qb.where("DATE_FORMAT(s.createdAt, '%Y-%m-%d') BETWEEN CAST(:fromDate as date) AND  CAST(:toDate as date)", {fromDate :fromDate, toDate: toDate} )

**Comment by stingers** [comment]
> I guess it might be some bug, I am passing two dates here, when I translate the dates to date and time in format YYYY-MM-DDTHH:MM myself it works.


qb.where("DATE_FORMAT(s.createdAt, '%Y-%m-%d') BETWEEN CAST(:fromDate as date) AND  CAST(:toDate as date)", {fromDate :fromDate, toDate: toDate} )
can help you
