### ISSUE TITLE
Can't override embedded entities in STI implementation

### ISSUE THREAD

**Issue by fwoelffel** [typeorm/typeorm#2800]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

(I tried with Postgres, but I assume I doesn't work either with other database systems)

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

**Steps to reproduce or a small repository showing the problem:**

Consider the following STI implementation:

```ts
import {Entity, PrimaryGeneratedColumn, TableInheritance, ChildEntity, Column} from "../../../../src";

export abstract class Engine {}

@Entity()
@TableInheritance({ column: { name: "type", type: "varchar" }})
export abstract class Vehicle {
    @PrimaryGeneratedColumn()
    public id?: number;
    public abstract engine: Engine;
}

export class PlaneEngine extends Engine {
    @Column()
    public beep: number;
    @Column()
    public boop: number;
}

@ChildEntity()
export class Plane extends Vehicle {
    @Column(type => PlaneEngine)
    public engine: PlaneEngine;
}

export class CarEngine extends Engine {
    @Column()
    public horsePower: number;
    @Column()
    public torque: number;
}

@ChildEntity()
export class Car extends Vehicle {
    @Column(type => CarEngine)
    public engine: CarEngine;
}
```

I'm expecting my table to have the columns `engineHorsePower`, `engineTorque`, `engineBeep` and `engineBoop` however only the two first ones are created.
It doesn't work any better when setting the `prefix` option for the embedded entity.

I'll create a PR with the failing test.

**Comment by fwoelffel** [comment]
Thanks for your insights on this issue @elthrasher I'll look into it today and hopefully submit a fix.

In regard of the columns created as non nullable, do you think it could be related to #2705?

**Comment by fwoelffel** [comment]
I fixed those two issues and the CI status is still green. I think we could review the PR (https://github.com/typeorm/typeorm/pull/2801) and wait for it to be merged.

**Comment by fwoelffel** [comment]
Can we close this since #2801 has been merged?

**Comment by Kononnable** [comment]
Yes, it looks like it should be closed some time ago.
