### ISSUE TITLE
Faulty boilerplate

### ISSUE THREAD

**Issue by cfmtm** [typeorm/typeorm#2803]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

**Steps to reproduce or a small repository showing the problem:**

Generate a new project using
```sh
$ typeorm init --name removeByIdIssue --database mongodb --express --docker
```
Open `src/controller/UserController.ts`  
You will find that typeorm generated a controller having
```typescript
// ...
    async remove(request: Request, response: Response, next: NextFunction) {
        await this.userRepository.removeById(request.params.id);
    }
// ...
```
Where `removeById` is not defined on `Repository`.

**Comment by Kononnable** [comment]
According to changelog `removeById` was removed in 0.2.0, so we need to update files generated by `typeorm init`. Thanks for pointing that out.

**Comment by Anticom** [comment]
@Kononnable Is there any replacement for that or would i have to refactor it to using plain `remove` and expecting the ID only?

**Comment by Kononnable** [comment]
I think this should work.
```typescript
await this.userRepository.delete(request.params.id);
```

**Comment by Anticom** [comment]
Wanted to contribute a PR to fix this, howver i saw that this is already fixed in `next` branch like so:
```ts
    async remove(request: Request, response: Response, next: NextFunction) {
        let userToRemove = await this.userRepository.findOne(request.params.id);
        await this.userRepository.remove(userToRemove);
    }
```

**Comment by tate-bowman** [comment]
Came here to file this issue.  The boilerplate controller has the updated syntax now, but it looks like the boilerplate route for the delete method is faulty.  Instead of 
```typescript
{
    method: "delete",
    route: "/users",
    controller: UserController,
    action: "remove"
}
```
this should be 
```typescript
{
    method: "delete",
    route: "/users/:id",
    controller: UserController,
    action: "remove"
}
```
I'm not sure if this is the same for all Express boilerplates, but the above was generate with Express and SQLite.

**Comment by pleerock** [comment]
@tate-bowman thanks for pointing out, I fixed that.
