### ISSUE TITLE
WHERE Query Operand Order

### ISSUE THREAD

**Issue by ajxs** [typeorm/typeorm#2804]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

My team is currently in the process of migrating a project to TypeORM. A minor issue that I've encountered is translating some of our queries into the typeORM `FindConditions` format. We use many queries in the following format to query rows specifying validity for a specifid time period, using the SCD2 pattern, such as:
````
-- Actual code omitted for brevity.
SELECT a.*
	FROM a
	WHERE a.name = 'something'
	AND '2018-01-01' >= a.start_date
	AND '2018-01-01' < COALESCE(a.end_date, '9999-12-30'::date)
	LIMIT 1;
````
We've successfully used this pattern in our architecture for some time now. One potential solution is to create a `VIEW` which exposes an already coalesced `end_date` column, but this seems cumbersome.
Can anyone point me in the right direction to how we would recreate this kind of query in typeORM?
Thank you very much.

**Comment by elthrasher** [comment]
@ajxs Can you provide an example of what you've tried? You should be able to put an arbitrary where clause into `FindOne` or a query builder. Both accept strings.

**Comment by elthrasher** [comment]
No problem, happy to help! I would probably write that with multiple `where` and `andWhere` clauses. Might make your code a bit cleaner, just as a suggestion.
If you're all set, please close this issue.
