### ISSUE TITLE
Multiple properties with one alias leftJoinAndSelect

### ISSUE THREAD

**Issue by black09bb** [typeorm/typeorm#2806]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[X] `0.3.0-alpha.6` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
 Adding multiple properties to join specific alias 
I just want to join user to changesHistory.creator and car.trader

```
            .leftJoinAndSelect('car.changesHistory', 'changesHistory') // working
            .leftJoinAndSelect('changesHistory.creator', 'user')
            .leftJoinAndSelect('car.trader', 'user') 
 // but it's throwing error (alias user is declared more than once) 
```
So i tried a lot of ways like: 
```
            .leftJoinAndSelect('car.changesHistory', 'changesHistory') // working
            .leftJoinAndSelect('changesHistory.creator, car.trader', 'user')
```

If I'm using only : 
```
            .leftJoinAndSelect('changesHistory.creator', 'user')
``` 
or only 
```
            .leftJoinAndSelect('car.trader', 'user') 
```
It's working

And I don't know how to make it working together in one querry :/

**Comment by afurculita** [comment]
Can you also show us please also the entities with the relations between them?

**Comment by black09bb** [comment]
I think It's not needed because if I use only 
```
.leftJoinAndSelect('changesHistory.creator', 'user')
```
or only 
```
.leftJoinAndSelect('car.trader', 'user')
```

It's working :D And I'm just looking for a way to make it together

**Comment by afurculita** [comment]
The definition for `leftJoinAndSelect` is:

```ts
    /**
     * LEFT JOINs entity's property and adds all selection properties to SELECT.
     * Given entity property should be a relation.
     * You also need to specify an alias of the joined data.
     * Optionally, you can add condition and parameters used in condition.
     */
    leftJoinAndSelect(property: string, alias: string, condition?: string, parameters?: ObjectLiteral): this;
```

The `alias` should be something unique. The alias here is not the alias of another column/entity. This alias is another name for the `property` argument. 

If you want to tie user to changesHistory.creator and car.trader you can do it using the third argument: `condition`. Something like this:

```ts
            .leftJoinAndSelect('car.changesHistory', 'changesHistory')
            .leftJoinAndSelect('changesHistory.creator', 'creator', 'creator.id = user.id')
            .leftJoinAndSelect('car.trader', 'trader', 'trader.id = user.id') 
```

For a more precise query, I need to see the entities and the relations between them.

**Comment by black09bb** [comment]
Actually, it's not working, so here is my entities : 

Car:

```
    @ManyToOne(type => User, user => user.cars)
    trader: User

    @OneToMany(type => CarHistory, carHistory => carHistory.car, { onDelete: 'CASCADE' })
    changesHistory: CarHistory[]

```

User: 

```
    @OneToMany(type => Car, cars => cars.trader)
    cars: Car[]

    @OneToMany(type => CarHistory, carHistory => carHistory.creator)
    changesHistory: CarHistory[]

```

CarHistory: 

```
    @ManyToOne(type => User, user => user.changesHistory)
    creator: User

    @ManyToOne(type => Car, car => car.changesHistory, { onDelete: 'CASCADE', nullable: false })
    car: Car

```

**Comment by black09bb** [comment]
@afurculita :D

**Comment by afurculita** [comment]
@black09bb sorry, I haven't had the time to look more into it. Have you solved it?

**Comment by black09bb** [comment]
No problem, understand that of course :D 

Yea, I have resolved it some minutes before by changin naming fron user to users to be unique
