### ISSUE TITLE
Electron React Webpack Typescript project configuration file entity not recognized

### ISSUE THREAD

**Issue by simpert** [typeorm/typeorm#2808]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am using nodev`8.11.4` npmv`5.6.0` and the latest `electron` `react` `webpack` in my project.

I was able to get everything to work with the `sqlite3` driver albeit after using a `postinstall` `npm` script to have `electron-builder` rebuild the driver for `electron`.

My difficulties were with `webpack`. 

Originally, I wished to use a standard options in a `ormconfig.json` file but I am unable to get `typeorm` to recognize any of my entities.

However, after several hours playing around with different configurations like using `webpack` `file-loader` I got everything to work but just not with the config file rather I needed to specify my entities in a `ConnectionOption`s object passed to `createConnection`.

This also required me to provide a table name in the `Entity` decorator.

I think this may be more of a `webpack` issue but since `electron` and `node webkit` are gaining steam rapidly it may be worth the time to get `typeorm` to play nice with `webpack`.

I believe `webpack` renames things and handles all the links to all resources. At first I figured I could point typeorm to look for entities int the `webpack` produced bundle since maybe it just looks for types marked with the decorator. This didn't work. 

Eventually, I needed to specify `typeorm` as a external dep in `webpack` as with `sqlite3` as well. Also, I only referenced `typeorm` and any entities in the rendered process.

I know `webpack` is mostly considered a client side tool and db related stuff with usually be in the backend or on server in node environment, however, `electron` and others have essentially merged the 2 and like in the case of my project I require db related code in node environment and `webpack` has been great for me for things like loading my sass and loading svg and other files.

I marked question at the top of this issue rather then bug.

I do have a working project that I put together to get Electron, React, Webpack, and Typeorm all working. I noticed a Electron sample project that uses a basic typescript config but not webpack.

If you would like the project please let me know. I do not have any experience with public repos and such else I would have just put a link to it here.

**Comment by dominicdesu** [comment]
Hi, is your question how to use the ormconfig.json together with Electron?

**Comment by imnotjames** [comment]
Hi there - there have been a number of improvements in this area and many of the problems you've mentioned should be better now.

If, for some reason, you're still having issues let's open a fresh issue with a way to replicate and I'm sure we can find a way to improve the experience.
