### ISSUE TITLE
Many-to-many table name not correct (postgres)

### ISSUE THREAD

**Issue by kodayashi** [typeorm/typeorm#2814]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Per documentation, if you have an entity called "a" and an entity called "b", and you setup a many-to-many relationship between them, your join table should be named "a_b_b_a", however all tables are only named "a_b_b". No known issues being caused due to this, I just noticed the discrepancy when viewing the tables and looking at some of the documented examples.

**Comment by Kononnable** [comment]
@typeorm Should we change docs or current behavior? Changing behavior could be breaking.

**Comment by vlapo** [comment]
For exactness name is generated by `NamingStrategyInterface#joinTableName`:
```typescript
joinTableName(firstTableName: string,
             secondTableName: string,
             firstPropertyName: string,
             secondPropertyName: string): string {
    return snakeCase(firstTableName + "_" + firstPropertyName.replace(/\./gi, "_") + "_" + secondTableName);
}
```
So as it is highly customizable we should only correct documentation. But I do not find exact place in docs where is naming strategy of join tables presented.
