### ISSUE TITLE
queryBuilder EXISTS query

### ISSUE THREAD

**Issue by victordidenko** [typeorm/typeorm#2815]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Feature request:**

Looks like EXISTS is optimised more, if you need to check only rows existence.
So, instead of

```sql
SELECT COUNT(*) FROM mytable WHERE a = "foo" AND b = "bar";
```

better do

```sql
SELECT EXISTS(SELECT * FROM mytable WHERE a = "foo" AND b = "bar");
```

But now query builder doesn't support such kind of queries, you need to write a raw query.
I think it would be cool to have something like

```js
queryBuilder()
  .select('*')
  .from(MyTable, 'tbl')
  .where('tbl.a = :foo AND tbl.b = :bar', { foo, bar })
  .isExists(); // <-- this row
```

**Comment by sykorax** [comment]
Any update on it?
Also would be nice to have this feature to be supported by repositories.

**Comment by victordidenko** [comment]
I made little helper
```typescript
export const isExistsQuery = (query: string) =>
  `SELECT EXISTS(${query}) AS "exists"`;
```
and use it like this:
```typescript
const [{ exists }] = await manager.query(isExistsQuery(
  manager.createQueryBuilder()
    .select('*')
    .from(MyTable, 'tbl')
    .where('tbl.a = ? AND tbl.b = ?')
    .getQuery(),
), [foo, bar]);
```

But native support from TypeORM would be better, of course :)

**Comment by feimosi** [comment]
This really would be useful. Has anyone found a way to have EXISTS inside a subquery? i.e.
`SELECT *, EXISTS(SELECT 1 FROM tbl WHERE user_id = :userId) ...`

I can't make it working with parameters.

**Comment by jubairsaidi** [comment]
here's how I did this:
```typescript
export const existsQuery = <T>(builder: SelectQueryBuilder<T>) => `exists (${builder.getQuery()})`;
```

So then later I can do something like:
```
    manager
      .getRepository(Role)
      .createQueryBuilder('role')
      .where(
        existsQuery(
          manager
            .getRepository(UserRole)
            .createQueryBuilder('user_role')
            .where('user_role.user_id = :userId and user_role.role_id = role.id')
        )
      )
      .setParameter('userId', userId)
      .orderBy(order as any)
      .limit(take)
      .skip(skip)
      .getMany()
```
However it should be noted that `where exists` is a very common style of quering things by relationships for optimal queries.  i.e. it's not a regular join query (do an explain on something like `select * from foo where exists (select 1 from bar where bar.id = foo.bar_id)`, vs the join version of this query and see the performance and efficiency difference.

Long way of saying, I really hope this is implemented natively!

**Comment by panzi** [comment]
I use this:
```TypeScript
import { SelectQueryBuilder } from 'typeorm';

// TODO: remove this once it is provided by TypeORM (in case that ever happens)
declare module 'typeorm' {
    interface SelectQueryBuilder<Entity> {
        whereExists<T>(query: SelectQueryBuilder<T>): this;
        andWhereExists<T>(query: SelectQueryBuilder<T>): this;
        orWhereExists<T>(query: SelectQueryBuilder<T>): this;
    }
}

SelectQueryBuilder.prototype.whereExists = function (query: SelectQueryBuilder<any>): SelectQueryBuilder<any> {
    return this.where(`EXISTS (${query.getQuery()})`, query.getParameters());
};

SelectQueryBuilder.prototype.andWhereExists = function (query: SelectQueryBuilder<any>): SelectQueryBuilder<any> {
    return this.andWhere(`EXISTS (${query.getQuery()})`, query.getParameters());
};

SelectQueryBuilder.prototype.orWhereExists = function (query: SelectQueryBuilder<any>): SelectQueryBuilder<any> {
    return this.orWhere(`EXISTS (${query.getQuery()})`, query.getParameters());
};
```

**Comment by fahussain** [comment]
How do you use this solution for an actual query?

**Comment by panzi** [comment]
Like this (copied from actual source):

```TypeScript
    const con = getConnection();
    const rect = await con.getRepository(Rect)
        .createQueryBuilder('rects')
        .where({
            documentId,
            index: req.params.index,
        })
        .andWhereExists(
            con.getRepository(Document)
                .createQueryBuilder('documents')
                .where('"documents"."clientId" = :clientId AND "documents"."id" = "rects"."documentId"', {
                    clientId: token!.client.id,
                })
        )
        .getOne();
```

You do need to put the extra functions in some file (e.g. `typeormExtras.ts`) and then `import 'typeormExtras';`.

**Comment by fahussain** [comment]
Thank you for quick reply. I am using an entity repository but for some reason I am getting all the results back, not just the matching records for whereExists condition. This is the shortened version of the query being run:
`SELECT `Tenant`.`id` AS `Tenant_id`,
  `Tenant`.`code` AS `Tenant_code`,
FROM `tenant` `Tenant`
WHERE EXISTS (
    SELECT `tenant`.`id` AS `tenant_id`,
      `tenant`.`code` AS `tenant_code`
    FROM `tenant` `tenant`
    WHERE `tenant`.`code` = 'test'
  )`
Am I doing something wrong?

**Comment by clevercodenl** [comment]
Does anyone know if the feature has been created or merged into the latest release ?

**Comment by tzahush** [comment]
I will add this.

**Comment by allanvobraun** [comment]
any updates on this?
any workarounds for: `select exists(select * from table)`

**Comment by craftsman01** [comment]
@tzahush @imnotjames wondering if this was picked up?

**Comment by Displee** [comment]
My implementation so far:
```ts
import { SelectQueryBuilder } from 'typeorm';

export const isExistsQuery = (query: string) => `EXISTS(${query}) AS "exists"`;

// TODO: remove this once it is provided by TypeORM (in case that ever happens)
declare module 'typeorm' {
	interface SelectQueryBuilder<Entity> {
		exists<T>(): Promise<boolean>;
	}
}

SelectQueryBuilder.prototype.exists = async function (): Promise<boolean> {
	const result = await this.select(isExistsQuery(this.getQuery())).where('').getRawOne();
	return result.exists === '1';
};
```
Usage:
```ts
import '../core/typeorm/typeorm-extensions';
...
async create(dto: CreateUserRequestDto): Promise<Partial<User>> {
	const exists = await this.usersRepository.createQueryBuilder().where({
		username: dto.username
	}).exists();
	if (exists) {
		throw new HttpException('This username is already in use.', HttpStatus.CONFLICT);
	}
	...
}
```

**Comment by simplenotezy** [comment]
> 

Unfortunately it does not perform an ideal query:

```sql
SELECT EXISTS(SELECT (... all fields on user) FROM "user" "User" WHERE ( "User"."email" = $1 ) AND ( "User"."deleted_at" IS NULL )) AS "exists" FROM "user" "User" WHERE ( "User"."email" = $2 ) AND ( "User"."deleted_at" IS NULL )
```

Ideally it should look like:

```sql
SELECT 1 FROM "user" "User" WHERE ( "User"."email" = $1 ) AND ( "User"."deleted_at" IS NULL )
```

**Comment by allanvobraun** [comment]
@simplenotezy can you share your implementation please?

**Comment by emman-ok** [comment]
> Unlike `COUNT`, `EXISTS` is a predicate, not a function, and requires a subquery. The SQL would look like:
> 
> ```sql
> SELECT
>   CASE
>     WHEN EXISTS(SELECT * FROM <table-name> [WHERE <conditions>])
>     THEN TRUE
>     ELSE FALSE
>   END AS "result"
> FROM SYS.DUMMY;
> ```
> 
> The SQL above should work in all SQL dialects. The queries in the previous comments will work only in specific dialects.
> 
> So IMO, you could also create a helper function to build this query using two query builders.

Your query is the only one that worked accross multiple DBs tested in (MYSQL, MSSQL, POSTGRES, SQLITE).
So heres is my implementation



```
export const isExistsQuery = (query: string) => `CASE WHEN EXISTS(${query}) THEN 1 ELSE 0 END AS "exists"`;
declare module 'typeorm' {
  interface SelectQueryBuilder<Entity> {
    exists<T>(): Promise<boolean>;
  }
}

SelectQueryBuilder.prototype.exists = async function (): Promise<boolean> {
  const result = await this.select(isExistsQuery(this.getQuery())).where('').take(1).getRawOne();
  return result?.exists == '1';
};

```


Thanks

**Comment by alumni** [comment]
Looking at @mortezaPRK's PR, there's also this alternative which should work in most dialects:
```sql
SELECT TRUE AS "row_exists"
FROM SYS.DUMMY
WHERE EXISTS(SELECT * FROM <table-name> [WHERE <conditions>]);
```
It's a bit shorter than the CASE-WHEN version, but you'd need to check if the query returns any result instead of using the result directly. Both are fine for me :)

One tiny thing: it seems selecting from nothing is quite different in different dialects. Most dialects require a `FROM` clause (SQLServer doesn't), so a dummy table is required. This is called DUMMY in most dialects (in Oracle it's called DUAL, but AFAIR DUMMY also works; DB2 has SYSDUMMYx). Maybe a dialect-based function `fromDummy()` could be useful 🤷🏻

**Comment by Groove-Theory** [comment]
Does this functionality have support for NOT EXISTS? I have been attempting to do so but to no avail.

Using `NotBrackets` doesn't seem to work with the new `.whereExists` method(s), as the `whereFactory` element on the constructor cannot use the exists methods that were added in the above PR.

**Comment by jsommer1738** [comment]
> Does this functionality have support for NOT EXISTS? I have been attempting to do so but to no avail.
> 
> Using `NotBrackets` doesn't seem to work with the new `.whereExists` method(s), as the `whereFactory` element on the constructor cannot use the exists methods that were added in the above PR.
> 
> I'm well aware that a left outer join can be logically equivalent, but there are performance reasons why people would want to use a NOT EXISTS over a join.

I need this very much!
