### ISSUE TITLE
Can not Select fields other than some fields that I don't want to get

### ISSUE THREAD

**Issue by isaaxite** [typeorm/typeorm#2819]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello,typeorm team!
when I use the `find` fuction, and it's `select` attribute, I find that I can not select fields other than some attributes( i don't want to select).
I hope that you can achieve it.

**Comment by Kononnable** [comment]
Could you provide some code examples on what you want to achieve? If you define what columns should be selected typeorm will only get those columns from db server(and PK) and other columns won't be filled with data.

**Comment by issaxite** [comment]
Such as the following entity：
```typescript
import {
  Index,
  Entity,
  Column,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import {BaseAbstractEntity} from '../../base.abstract.entity';

@Entity('Users')
export class User extends BaseAbstractEntity {
  @Column('varchar', {
    nullable: false,
    unique: true,
    length: 170,
    name: 'email',
  })
  email: string;

  @Column('varchar', {
    nullable: false,
    length: 255,
    default: 'user',
    name: 'name',
  })
  name: string;

  @Column('varchar', {
    nullable: true,
    length: 255,
    name: 'password',
  })
  password: string | null;

  @Column('varchar', {
    nullable: true,
    length: 255,
    name: 'phone',
  })
  phone: string | null;

  @Column('int', {
    nullable: true,
    default: '0',
    name: 'active',
  })
  active: number | null;

  @Column('int', {
    nullable: true,
    default: '0',
    name: 'role',
  })
  role: number | null;
}
```
I want to get the fields other than `active` and `role`.In the latest typeorm, I need to write like this：
```typescript
const users: User = getReporitory(User).find({
  select: ['email', 'name', 'password', 'phone'],
});
```
however, i want to get the feature like that:
```typescript
const users: User = getReporitory(User).find({
  selectOtherThan: ['active', 'role'],
});
```
My English is not very good. If the speech is not ceremonial, please bear with me.

**Comment by acro5piano** [comment]
@issaxite 
Hi, did you try select: false option?

```
    @Column({ select: false })
    active: string;
```

https://github.com/typeorm/typeorm/issues/828#issuecomment-328021507

**Comment by Kononnable** [comment]
Closing as no response from the author.
