### ISSUE TITLE
Always return primary key?

### ISSUE THREAD

**Issue by seanski** [typeorm/typeorm#282]
I am using UUIDs as the primary key on my tables, and one of the issues I am running into is that my entities are not populated with the primary key after I persist them.  I am using a default value of `uuid_generate_v4` to populate the primary key automatically in Postgres, but `{generate: true}` is not passed into my decorator, and the query runner checks for columns that are generated to pass into the `RETURNING` clause, so my primary key value is not coming back.

My primary keys look like this `@PrimaryColumn({type: "uuid", default: () => 'uuid_generate_v4()'})`.  Instead of checking for generated columns, perhaps we could always return the primary key?  Or, alternatively, we could check for columns that have a function type as the default value?  I'm happy to work on this, if so.

**Comment by seanski** [comment]
We could also update the `PrimaryGeneratedColumn` decorator to generate primary keys with the `uuid_generate_v4` function instead of creating a auto-incrementing sequence as it currently does, if the type is uuid.

**Comment by pleerock** [comment]
> We could also update the PrimaryGeneratedColumn decorator to generate primary keys with the uuid_generate_v4 function instead of creating a auto-incrementing sequence as it currently does, if the type is uuid.

Maybe we can do so.

There is a mess right now with "generated" stuff. This part needs a bit refactoring to match new features like uud support. Probably the best if we use "generated" check for both sequence and uuid and later handle situations based on its type if its possible

**Comment by nolazybits** [comment]
I've been seing a lot of issue regarding this and I was wondering if it would be possible to have maybe an extra annotation that will tell typeorm "always return this property"?
Cheers

**Comment by pleerock** [comment]
@nolazybits this issue is fixed, please provide more details on what problems you have
