### ISSUE TITLE
Inserting a point with WKX not working

### ISSUE THREAD

**Issue by wisepotato** [typeorm/typeorm#2820]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have the following entity:
```ts
@Entity()
export class Location {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column("point")
    point: Point;

    @ManyToMany(type => Entry, entry => entry.locations)
    entries: Entry[];



    toJson() {
        return {
            name: this.name,
            lalal: "no",
            point: this.point
        }
    }
}
```
In which I want to set the `point` variable:
```ts
let loc: Location = new Location();
let lat: number = 52.377546 + Math.random() / 10;
let lon: number = 4.901787 + Math.random();
loc.point = new Point(lat, lon);
loc.name = Math.random().toString();
```

Which, according to the docs should work, `Point` is a  `WKX.Point`, and the steps provided here https://github.com/typeorm/typeorm/issues/2443 do not work either. I get the following error:

```
QueryFailedError: invalid input syntax for type point: "{"hasZ":false,"hasM":false,"x":52.38588255451923,"y":5.172797673831698}"
```
I have posted this issue on stackoverflow but the community apparently does not know how to solve it/I don't know how to properly format my question. So there it is. I Would not mind one bit updating the docs, helping others, or even a pull request but I can't figure it out.

https://stackoverflow.com/questions/52375733/inserting-a-typeorm-point-using-wkx-for-postgresql

**Comment by ykxhzfj** [comment]
I think it may be related to your 'Point' type.
such as  @Column({type: ' double precision'}) lng: number;

**Comment by wisepotato** [comment]
> I think it may be related to your 'Point' type.
> such as @column({type: ' double precision'}) lng: number;

What do you mean? Should be a number? I would have assumed it to be a wkx.Point..,

**Comment by wisepotato** [comment]
Anybody?

**Comment by Kononnable** [comment]
Don't know about WKX.Point, but that code pass in CI.
https://github.com/typeorm/typeorm/blob/bcd5d82a09c2759498aabe0528c607ecf2486b49/test/functional/database-schema/column-types/postgres/entity/Post.ts#L144-L147

https://github.com/typeorm/typeorm/blob/bcd5d82a09c2759498aabe0528c607ecf2486b49/test/functional/database-schema/column-types/postgres/column-types-postgres.ts#L66

**Comment by wisepotato** [comment]
I'll check again, maybe something wrong with my configuration.

**Comment by nomadoda** [comment]
> I'll check again, maybe something wrong with my configuration.

Hi @wisepotato! Did you find some enlightenment?

**Comment by wisepotato** [comment]
I used the above, so not using the WKX point to get it working. Seemed... annoying but it worked!
