### ISSUE TITLE
Support .ts ormconfig in CLI

### ISSUE THREAD

**Issue by ssalka** [typeorm/typeorm#2828]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have an existing configuration file written in TypeScript, currently being used successfully at runtime. The config (`config/mongodb.ts`) is as follows:

```ts
export default {
  host: 'localhost',
  port: 27017,
  database: 'test',
  type: 'mongodb'
}
```

 However, I'm unable to use this config file via the CLI - I get the following from running `typeorm schema:sync --config ./config/mongodb`:

```
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
```

I was a little surprised by this. Given that the project is written in TypeScript, and is focused on providing functionality around TypeScript, it seems odd that developers end up having to use a `.js` or `.json` file to specify their config.

I've tried using a JSON file instead, which works for the CLI, but causes the following type error:

```
TSError: ⨯ Unable to compile TypeScript:
config/index.ts(6,14): error TS2322: Type '{ "host": string; "port": string; "database": string; "type": string; }' is not assignable to type 'MongoConnectionOptions'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type '"mongodb"'.
```

I could patch this by adding an `as any` type assertion, or by transpiling the file for usage with the CLI, but I'm generally against doing either - I'd prefer to use a TypeScript config file as the source of truth.

**Comment by ryuuji3** [comment]
I would recommend using ts-node to run the CLI; try pre-facing typeorm commands with:
```
ts-node ./node_modules/.bin/typeorm
```

**Comment by ssalka** [comment]
@ryuuji3 thanks for your suggestion - although this works as far as getting typeorm to read the config file I specify, I now end up with a `MissingDriverError`. This seems to be because the TS config file is parsed as `{ default: {/* actual config here */} }` rather than the actual object being exported (this is expected TypeScript behavior). The result is that the reader interprets the `driver` field as `undefined`.

In the end, I can get the schema sync to run successfully by exporting each key individually, i.e.
```ts
export const type = 'mongodb';
export const host = 'localhost';
...
```

But that is also non-ideal because 1) it is less readable than a single object or JSON file, and 2) I lose the ability to enforce the `MongoConnectionOptions` interface.

**Comment by ryuuji3** [comment]
Try changing it to module.exports = {} instead export default.

**Comment by ssalka** [comment]
Thanks @ryuuji3, I believe that will do as a workaround (ideally, would prefer that `ConnectionOptionsReader` can extract a default export from a `.ts` file).

I'm using TypeScript, so the `module` variable cannot be used as such. There is a TS-equivalent syntax though (which I've never used before) that appears to work:

```ts
export = {/* config */};
```

Then in my application code, I can write either `import * as ormconfig from '...'` or `import ormconfig = require('...')`

**Comment by zefexdeveloper** [comment]
I'm getting this error after running `ts-node ./node_modules/.bin/typeorm`

> basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
> SyntaxError: missing ) after argument list

**Comment by hackmushroom** [comment]
@zefexdeveloper I had the same issue. I now use a script entry like this in my package.json to get it working:
```
"scripts": {
    ...
    "typeorm:cli": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js -f ./ormconfig"
    ...
}
```

That way I can run commands easily. E.g.:

`yarn typeorm:cli migration:run`

**Comment by mwanago** [comment]
I've also managed to get it to work, but I would like to make a note here with some info gathered by debugging the CLI.
Before, I exported my config using the default export functionality. So naturally, I added the `cli` property:

`import { ConnectionOptions } from 'typeorm';

const config: ConnectionOptions = {
  type: 'postgres',
  host: process.env.POSTGRES_HOST,
  port: Number(process.env.POSTGRES_PORT),
  username: process.env.POSTGRES_USER,
  password: process.env.POSTGRES_PASSWORD,
  database: process.env.POSTGRES_DB,
  entities: [
    __dirname + '/../**/*.entity{.ts,.js}',
  ],
  cli: {
    migrationsDir: 'src/migrations',
  }
};
export default config;`

Turns out, this configuration is put into the _default_ property because the file uses _export default_ and therefore the CLI does not see the _cli.migrationsDir_ property.
The `ormconfig.ts` file needs to have a named export called _cli_ for the configuration to work properly, like that:

`import { ConnectionOptions } from 'typeorm';

const config: ConnectionOptions = {
  type: 'postgres',
  host: process.env.POSTGRES_HOST,
  port: Number(process.env.POSTGRES_PORT),
  username: process.env.POSTGRES_USER,
  password: process.env.POSTGRES_PASSWORD,
  database: process.env.POSTGRES_DB,
  entities: [
    __dirname + '/../**/*.entity{.ts,.js}',
  ],
};

const cli = {
  migrationsDir: 'src/migrations',
};

export { config, cli };`

My script looks like this:
`"scripts": {
  "typeorm:cli": "ts-node ./node_modules/typeorm/cli -f ./src/ormconfig.ts"
},`

I hope that saves some time for somebody.

**Comment by mikew** [comment]
seems like either PlatForm tools needs to support checking the resulting object for `.default` (https://github.com/typeorm/typeorm/blob/a12e72d417638ea8fba2ca672d5acfaaaaf691c9/src/platform/PlatformTools.ts#L128-L129), or explicit support in the `.js` and `.ts` loaders (https://github.com/typeorm/typeorm/blob/a12e72d417638ea8fba2ca672d5acfaaaaf691c9/src/connection/ConnectionOptionsReader.ts#L110-L114)

as it stands, the "out of the box" experience when using this library with TypeScript leaves a bit to be desired.

**Comment by hypeofpipe** [comment]
```
import ormconfig
Argument of type '{ type: string; host: string | undefined; port: string | undefined; username: string | undefined; password: string | undefined; database: string | undefined; logging: boolean; synchronize: boolean; charset: string; entities: string[]; subscribers: string[]; cli: { ...; }; }' is not assignable to parameter of type 'ConnectionOptions'.
  Type '{ type: string; host: string | undefined; port: string | undefined; username: string | undefined; password: string | undefined; database: string | undefined; logging: boolean; synchronize: boolean; charset: string; entities: string[]; subscribers: string[]; cli: { ...; }; }' is not assignable to type 'MysqlConnectionOptions'.
    Types of property 'type' are incompatible.
      Type 'string' is not assignable to type '"mysql" | "mariadb"'.ts(2345)
```

```
module.exports = {
  type: 'mysql',
  host: config.DB_HOST,
  port: config.DB_PORT,
  username: config.DB_USERNAME,
  password: config.DB_PASSWORD,
  database: config.DB_NAME,
  logging: false,
  synchronize: false,
  charset: '...',
  entities: [...],
  subscribers: [...]
}
```

I'm issuing same problem when trying to create a connection via connectionManager :(

`connectionManager.create(ormconfig)`

**Comment by vinimdocarmo** [comment]
Any updates on this one?

**Comment by antonphilin** [comment]
Any updates on this one?

**Comment by lookfirst** [comment]
`export = { ...config };`

**Comment by imnotjames** [comment]
I tested this and it works with the latest release
