### ISSUE TITLE
[Req] Integrated with class-sanitizer and class-validator

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#283]
Do you have plans to integrate typeorm with class-sanitizer and class-validator? I'm using the combination like this
````
@Entity()
export class Item{

    @IsInt()
    @PrimaryGeneratedColumn()
    id: number;

    @Escape()
    @Index()
    @Column({type:'string',length:60})
    info:string;

    @Sanitize(CustomClass)
    @Column({type:'text'})
    comment:string;

    @BeforeInsert()
   async purifyInsert() {
         await validate(this).then(errors => {
            if (errors.length > 0) {
            } else {
            }
            sanitize(this)
        })   
     }
}
````
I hope that an enhancement would be made so that I don't need to repeat the sanitizer and validator code in `@BeforeInsert` in every entity. 

I have made a pull request https://github.com/pleerock/class-sanitizer/pull/4 to fix a problem using sanitizer and typeorm.

**Comment by pleerock** [comment]
No, there is no plans in integration of these libraries. Only in separate framework, in the future. These tools are completely isolated and you can bind them quite easily by yourself.

Btw I dont recommend you to put such logic into your models. Better if you just call it before you persist entity.

**Comment by stonecold123** [comment]
Thanks. I will think about not using `@BeforeInsert`. 
Btw, I have provided an more detailed example in my pull request. https://github.com/pleerock/class-sanitizer/pull/4
