### ISSUE TITLE
Transaction decorators not modifying the method signature

### ISSUE THREAD

**Issue by VladimirMilenko** [typeorm/typeorm#2833]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When applying `@Transaction` decorator, method signature is not changed to Promise.

**Comment by Kononnable** [comment]
@VladimirMilenko 
Could you elaborate what you think should be done after applying `@Transaction` decorator? As for what I understood it might not be supported by typescript yet(Microsoft/typescript#4881)

**Comment by VladimirMilenko** [comment]
@Kononnable oh, I didn't notice it's not even planned for Typescript.
Then we just have to wait.
