### ISSUE TITLE
OneToMany lazy relation, bad name in JSON attributes

### ISSUE THREAD

**Issue by codematix** [typeorm/typeorm#2836]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `5.5.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a lazy `@OneToMany` relation between 2 entities in my project:

**user.entity.ts**

```ts
import {
  BaseEntity,
  OneToMany,
  Entity,
  PrimaryGeneratedColumn,
  Column,
  Unique,
} from 'typeorm'
import { Task } from '../../tasks/models/task.entity'

@Entity({
  name: 'users',
})
@Unique('uk_users_email', ['email'])
export class User extends BaseEntity {
  @PrimaryGeneratedColumn({
    name: 'id',
  })
  public id: number

  @Column({
    name: 'first_name',
    nullable: false,
  })
  public firstName: string

  @Column({
    name: 'last_name',
    nullable: false,
  })
  public lastName: string

  @Column({
    name: 'email',
    nullable: false,
  })
  public email: string

  @OneToMany(type => Task, task => task.owner, {
    lazy: true,
    onDelete: 'CASCADE',
  })
  public tasks: Promise<Task[]>
}
```

**task.entity.ts**

```ts
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  BaseEntity,
  ManyToOne,
} from 'typeorm'
import { User } from '../../users/models/user.entity'

@Entity({
  name: 'tasks',
})
export class Task extends BaseEntity {
  @PrimaryGeneratedColumn({
    name: 'id',
  })
  public id: number

  @Column({
    name: 'title',
    nullable: false,
  })
  public title: string

  @Column({
    name: 'due_date',
  })
  public dueDate: Date

  @Column({
    name: 'description',
  })
  public description: string

  @Column({
    name: 'priority',
    nullable: false,
    default: 1,
  })
  public priority: number

  @ManyToOne(type => User, user => user.tasks, {
    lazy: true,
  })
  public owner: Promise<User>

  constructor(title: string, dueDate = new Date(), priority = 5) {
    super()

    this.title = title
    this.dueDate = dueDate
    this.priority = priority
  }
}
```

I am using NestJS for the web framework. When I serialize the `Task` entity (defined below), I am seeing an bad name for the `owner` attribute in the JSON representation:

```json
{
        "title": "Second Task",
        "dueDate": "2018-09-22T18:30:00.000Z",
        "priority": 1,
        "id": 1,
        "description": "This is my task description",
        "__owner__": {
            "id": 1,
            "firstName": "John",
            "lastName": "Doe",
            "email": "jdoe@example.com"
        }
}
```

I am expecting to see something like this

```json
{
        "title": "Second Task",
        "dueDate": "2018-09-22T18:30:00.000Z",
        "priority": 1,
        "id": 1,
        "description": "This is my task description",
        "owner": {
            "id": 1,
            "firstName": "John",
            "lastName": "Doe",
            "email": "jdoe@example.com"
        }
}
```

If i set the `lazy` option in the `@OneToMany` decorator to `false`, I get the correct attribute name.

I understand that a lazy relation means that the associated object is retrieved only when the attribute is accessed. So to retrieve the related object I tried with 2 techniques:

```ts
const task = await Task.findOne(id, {
      join: {
        alias: 'task',
        leftJoinAndSelect: { owner: 'task.owner' },
      },
    })
```

And also:

```ts
const task = await Task.findOne(id, {
     relations: ['owner']
    })
```

Both yield the same result. Am I doing this incorrectly or is there a bug with `typeorm`?

**Comment by codematix** [comment]
Folks, any help available with this?

**Comment by codematix** [comment]
I deeply apologize, the version I am using was `0.2.6`. Must have gotten mixed up with a version number of another library. But the problem does exist with the `typeorm` library I have in my project.

**Comment by Kononnable** [comment]
It is done that way by design. There is already a property called `owner`and it is of type `Promise<User>`. You can see it by `console.log(task.owner)`.

**Comment by alonssro** [comment]
Hi! Do you have any response about this? How can I obtain the correct name for the lazy relation?

**Comment by aequasi** [comment]
This may be by design, but the output is not desired @Kononnable . Working with class-transformer, there should be a way to serialize an entity with lazy relations and get the expected keys, instead of the __PROPERTY__ ones

**Comment by Kononnable** [comment]
You can't have both promise and value of that promise under same name. It just how it works in js. You could replace promise with it's value after fetching it, but you would than have to marked such field with union type of `FieldType | Promise<FieldType`, so it wouldn't be as useful as it might initially look like.
Lazy loading is one of the things which are planned to be redesigned from scratch, but for now I don't see any possibility to change current behavior to what is described here.

**Comment by whileloop99** [comment]
Late, but for those who are using NestJS and still stuck with this issue, here is my workaround:

### Solution 1:　A quick and dirty solution
```typescript
import { Entity, Column, ManyToMany } from 'typeorm';
import { Expose } from 'class-transformer';

@Entity()
export class User {
  // ...

  @ManyToMany(() => Role, v => v.users)
  public roles: Promise<Role[]>;

  // Add this ▼▼▼
  @Expose({ name: "roles" })
  __roles__: Role[];
  // Add this ▲▲▲
}
```


### Solution 2:　My recommend approach

**user.entity.ts**
```typescript
import { Entity, Column, ManyToMany } from 'typeorm';
import { Expose } from 'class-transformer';
import { CommonEntity } from './common.entity';

@Entity()
export class User extends CommonEntity {
   // ...

  @ManyToMany(() => Role, v => v.users)
  public roles: Promise<Role[]>;
}
```

**common.entity.ts**
```typescript
import { instanceToPlain } from 'class-transformer';

export class CommonEntity {
    // ...

   /**
   * You need to override this function to customize the json output of class-transformer library
   * @returns 
   */
  toJSON(): {} {
    const record = instanceToPlain(this);

    // Remove all double underscores `__` from all properties when serializing object
    const cleanUnderscoresProperties = (obj: object): void => {
      for (const [key, val] of Object.entries(obj)) {
        if (key.startsWith('__') && key.endsWith('__')) {
          const newKey = key.substring(2, key.length - 2)
          obj[newKey] = obj[key];
          delete obj[key];
        } else if (typeof val === "object") {
          cleanUnderscoresProperties(val);
        }
      }
    };
    cleanUnderscoresProperties(record);
    
    return record;
  }
}
```
