### ISSUE TITLE
Reconnect to DB after connection error

### ISSUE THREAD

**Issue by IraErshova** [typeorm/typeorm#2838]
**Issue type:**
[x ] question

**Database system/driver:**
[x ] `mssql`

**TypeORM version:**
[ x] `0.1.21` (or put your version here)

Hi! I have a question about connection process in TypeORM. Unfortunately I don't find any useful information in issues and documentation. 

So I use Nest.js@4.6.6, Typeorm@0.1.21 and Mssql for my API. In case when I have an error because of DB connection during starting server, my API just crashes and DB doesn't reconnect. What should I do to reconnect DB in this case? 

I use TypeOrmModule for DB connection:
```
@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'mssql',
      host: DB_HOST,
      port: parseInt(DB_PORT, 10) || defaultPort,
      username: DB_USER,
      password: DB_PASS,
      database: DB_NAME,
      synchronize: false,
      logging: false,
      entities: [...]
    }),
```
This is a screenshot with an connection's error:
![screenshot from 2018-09-24 13-30-23](https://user-images.githubusercontent.com/14790520/45947739-09188380-bffe-11e8-830d-fbe80fba3e9c.png)

Behavior, which I expect:
`[TypeOrmModule] Unable to connect to the database. Retrying (1)... +XXms`

**Comment by brizer** [comment]
you should put an issue in nestjs/typeorm, but not here
