### ISSUE TITLE
Official way to share Typescript models with frontend?

### ISSUE THREAD

**Issue by tamethecomplex** [typeorm/typeorm#2841]
**Issue type:**
[X ] question
[ X] documentation issue

**TypeORM version:**
[X ] `latest`

Hi, first off thanks for this library, it's awesome so far.  

I did run into the issue [here](https://github.com/typeorm/typeorm/issues/1009) and saw there was some deliberation about how to best share models between frontend and backend in a typescript project.  I tried to find out what the final "recommended" approach was but I haven't been able to find it anywhere.  What's the best way to accomplish this?

**Comment by tamethecomplex** [comment]
After looking into past issues further, I see the solution is documented [here](https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js#L16-L21), having been referenced in the issue [here](https://github.com/typeorm/typeorm/issues/1362)

**Comment by tomspeak** [comment]
Hey — glad you solved your issue! Reusing the models on the frontend never occurred to me. Would you mind giving an example how you're doing this? I have never used Angular, so maybe it is Angular specific, as the other issues reference.

**Comment by tamethecomplex** [comment]
Hi @tomspeak , this was actually a more general issue with frontend bundles built with webpack - not specific to Angular (I'm using React and Typescript on the frontend).  Because several of my server's REST endpoints return entity objects, I wanted to be able to reference those models in the frontend (for stong typing) when I consume those services.  

As an aside, I build my node service routes using the library [here](https://www.npmjs.com/package/typescript-rest), which also builds swagger docs which include entity model definitions.

Does that answer your question?

**Comment by tomspeak** [comment]
That's amazing, I am just moving over a React project to TypeScript and would love to see any examples that you could share, would be appreciated.

**Comment by tamethecomplex** [comment]
Hi @DylanSp ,

All of my projects are in a monorepo, in sibling directories as you mention.  They each have their own package.json to track their own external dependencies, but module imports are direct to the siblings' code.  I use the tsconfig.json "extends" option so that all sibling packages extend a tsconfig.base.json file.  Then I use typescript's [path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html) to import from siblings without relative paths becoming unmanageable.

I tried to use Lerna to manage dependencies previously, but so far, the vanilla tsconfig extend + path mapping approach has worked better for both my workflow and my editor (VS Code) tooling.

**Comment by tamethecomplex** [comment]
@tomspeak , I'm actually planning to publish a boilerplate full stack typescript application (node / typescript / react / mobx) in a monorepo using the approach I described below.  It's not ready yet, but I'll link here when it is.

**Comment by SerkanSipahi** [comment]
@tomspeak we are looking (boilerplate) forward to it :)

**Comment by tamethecomplex** [comment]
Hi all, FYI I published the boilerplate [here](https://github.com/tamethecomplex/typescript-fullstack-monorepo).  This particular repo doesn’t use typeorm, but the monorepo approach with shared typescript code and multiple compilation targets should solve the problems discussed above.

**Comment by jiriKralovec** [comment]
@tomspeak Another use case I came across - I am developing an Electron application with Angular. Not sure if you are familiar with Electron - it works on concept of running Renderer process (Angular) and Main process (Node). As I like to separate my logic, all my 'back end' is in Main process e.g. creating files, communicating with local database etc. However, the models used for database are also used inside the application as well. To avoid duplicity and issues with maintainability, I use the same models for both.
