### ISSUE TITLE
@OneToOne 

### ISSUE THREAD

**Issue by jelling** [typeorm/typeorm#2842]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

We want to relate/join spouse entites. Currently our person entity looks like:

```
@Entity()
@TableInheritance({ column: { type: "varchar", name: "type" } })
export class Person {
    @PrimaryGeneratedColumn() id: number;

...

    // Couldn't get this to work, circular ref?
    @OneToOne(type => Person, spouse => spouse.id)
    @JoinColumn()
    spouse: Person;

```

This does not build, yielding the error:

> [Server] (node:20431) UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

It builds without the @JoinColumn attribute but in that case it doesn't work on save.

So how does one do a self-join? Do we need to use the tree decorators?

**Comment by imnotjames** [comment]
This looks more like a question than much else -- but if you think it's a bug please include more information to replicate it.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
