### ISSUE TITLE
Passing an array as a bound parameter for a `WHERE IN` clause (sqlite)

### ISSUE THREAD

**Issue by DeX3** [typeorm/typeorm#2845]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

It is currently not possible to pass an array as a bound variable to a QueryBuilder:

```ts
userRepository.createQueryBuilder('user')
  .where('user.id IN ?', [1,2,3])
  .getMany()
```

This will fail with an `SQLITE_ERROR: syntax error`, mainly because the sqlite3 doesn't allow passing dynamically sized arrays. Instead with plain sqlite it is possible to dynamically generate a string of the form `(?,?,?,...`) of appropriate length and then simply pass all bound `?`'s as an array.

However, typeorm forces you to use named aliases, so you would have to work around that by generating an array of aliases which is just a pain to do...

**Comment by Aareksio** [comment]
Check [this comment](https://github.com/typeorm/typeorm/issues/1239#issuecomment-366955628). This is already possible, yet I don't think it's documented anywhere.
