### ISSUE TITLE
double equals vs triple equals on PrimaryGeneratedColumn

### ISSUE THREAD

**Issue by ShadabFaiz** [typeorm/typeorm#2846]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.5` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
This is my User Entity.
```ts
export class User extends AuditedModel {
	@PrimaryGeneratedColumn()
	userId: number;

	@Column({ type: 'varchar', length: '300' })
	userName: string;

	@OneToOne(type => UserProfile, { cascade: true })
	@JoinColumn()
	userProfile: UserProfile;

	@OneToOne(type => UserCredential, { cascade: true, eager: true })
	@JoinColumn()
	userCredential: UserCredential;

	@ManyToMany(type => BusinessUnit, { cascade: true, onDelete: 'SET NULL' })
	@JoinColumn()
	businessUnit: BusinessUnit;

	@ManyToMany(type => ProductType, { cascade: true, onDelete: 'CASCADE' })
	@JoinTable()
	productType: ProductType[];
}

```
and this is my Product Entity.
```ts
export class ProductType extends AuditedModel{

    @PrimaryGeneratedColumn()
    productId: number;

    @Column({type:"varchar", length:80})
    productName: string;

    @Column({type:"varchar", length:1500})
    productDetail: string;

    @OneToOne(type => ProductPrice, {cascade:true, eager:true})
    @JoinColumn()
    productPrice: ProductPrice;
}
```

**What i was trying to do:** I wa trying to get the all the products the the user has. After that apply `some()` on product list to check whether a particular product is present or not.

```ts
public async verifyUserProduct(userId: number, productId: number): Promise<boolean> {
		let userDAO = UserDao.getInstance();
		let status = false;
		await userDAO.getUserProducts(userId).then(User => {
			status = User.productType.some(product => {
				if(product.productId === productId)
					return true;
			})
			console.log(`Status: ${status}`);
		});
		return status;
	}
```

```ts
	public async getUserProducts(userId: number): Promise<User> {
		info(`Getting product of userId: ${userId}`);
		return await getRepository(User).findOne({
			relations: ['productType'],
			where: { userId: userId }
		});
	}
```

**Whats Happening:** product.productId === productId is returning false even when productId is a number;

**Expected Behaviour:** product.productId === productId should return true.

**Comment by imnotjames** [comment]
This seems to be closer to a general support question about the Typescript language.  You'll need to do some debugging to get to the bottom of this & we can help you out with that through the support channels.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
