### ISSUE TITLE
Mongodb this.getCollection(...).geoNear is not a function

### ISSUE THREAD

**Issue by lucabachmann** [typeorm/typeorm#2847]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
public findClosest(point: Point): Promise<SignalStrength> {
        this.log.info('Find closest point to', point);
        const manager = getMongoManager();
        return manager.geoNear(SignalStrength, point.point.lat, point.point.long);
    }
```

The Error i get:
`[api:middlewares\ErrorHandlerMiddleware] TypeError 0=TypeError: this.getCollection(...).geoNear is not a function`

I havent found a proper example on hwo to use geoNear, does anyone see the problem here?

**Comment by strelov1** [comment]
I got the same problem(

**Comment by edjo** [comment]
I got the same problem... any updates?

**Comment by edjo** [comment]
> I got the same problem... any updates?

The error persists when trying to use the `geoNear` function directly.
Optionally, you can use `aggregate` or `aggregateEntity` to use this function:

example:
```
(async() {
  const manager = getMongoManager();
  const query = manager.aggregateEntity([
        {
          $geoNear: {
            near: { type: "Point", coordinates: [45.4893422, -73.6290889] },
            spherical: true,
            distanceField: "calcDistance",
            key: "location"
          }
        }
      ]);

  const result = await query.toArray();
})();
```
[$geoNear (aggregation) — MongoDB Manual](https://docs.mongodb.com/manual/reference/operator/aggregation/geoNear/)

**Comment by pleerock** [comment]
This method was in mongodb driver 0.2.x, now in 0.3.x it doesn't exist anymore. We'll remove method from repository once we stop support 0.2.x driver. Refer to official mongodb documentation to find alternatives to this method.
