### ISSUE TITLE
multiple statements in one query doesn't works

### ISSUE THREAD

**Issue by dancespiele** [typeorm/typeorm#2851]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hello I would like to create a query with multiple statements like this:

```typescript
queryRunner.query(`CREATE TABLE IF NOT EXISTS \`pool_${this.gameId}_${index + 1}\` ` +
                    `(\`id\` int NOT NULL AUTO_INCREMENT, ` +
                    `\`hash\` varchar(255) NOT NULL, ` +
                    `\`used\` boolean NOT NULL, ` +
                    `\`index\` int NULL, ` +
                    `PRIMARY KEY (\`id\`)) ENGINE=InnoDB; ` +
                    `CREATE TABLE IF NOT EXISTS` +
                    ` \`available_pool_${this.gameId}_${index + 1}\` ` +
                    `(\`id\` int NOT NULL AUTO_INCREMENT, PRIMARY KEY (\`id\`)) ENGINE=InnoDB;`);
```
But i get error, if I copy that inside of mysql it executes the query correctly.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by elthrasher** [comment]
What's the need to create two tables in one statement? Can't you just
```
await queryRunner.query(`CREATE TABLE 1...
await queryRunner.query(`CREATE TABLE 2...
```
In any case, it's possible to do this if your driver supports it, though it's not explicitly documented in typeorm. See https://github.com/mysqljs/mysql#multiple-statement-queries
You can pass these params through typeorm to the driver via the `extra` property: http://typeorm.io/#/connection-options/common-connection-options
I realize you're using mssql, not mysql. I glanced at the mssql docs and didn't see support for this, but I'm not familiar with the library. I recommend just using two statements. I don't see anything in the code above that would prohibit this.

**Comment by dancespiele** [comment]
Thank you @elthrasher, if I do that works:
```typescript
const connectionOptions = await getConnectionOptions();
Object.assign(connectionOptions, {multipleStatements: true});
const db = await createConnection(connectionOptions);
```
I know that I can do query for each statements but I want to save queries.

**Comment by snolangps** [comment]
Is this fixed? I'm also having trouble running multiple update statements.

**Comment by MartijnHols** [comment]
I worked around this without enabling `multipleStatements` globally by creating a procedure with multiple statements and then calling that.

**Comment by FreshCreamBun** [comment]
> `multipleStatements`여러 문이 있는 프로시저를 만든 다음 호출하여 전역적으로 활성화하지 않고 이 문제를 해결했습니다 .

If it's not an excuse, can I see an example of how to do it without setting it globally?

**Comment by vikaskandari** [comment]
is it possible to enable multipleStatements  for one time ? not globally on Database instance  like for example i have an api that is 100% secure and i like to execute multi statement update quries in bulk to speed up the response but i want to enable multipleStatements  for current execition only not for all executions bascially i am looking for conditinal way to enable disable multipleStatements
