### ISSUE TITLE
Entities are not created in the correct order and caused error 

### ISSUE THREAD

**Issue by zorji** [typeorm/typeorm#2852]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have 3 entities: `House`, `Room` and `Bed`.
`House` and `Bed` have a single column I. `Room` has a composite ID of `roomNumber` and `House.id`. `Room` also has a nullable reference to `Bed`. Both `House` and `Bed` have no reference to `Room`.

Here is the definition in code
```ts
@Entity()
export class House {
  @PrimaryColumn('char', {length: 16})
  id: string
  @OneToMany(type => Room, room => room.house, {cascade: true, eager: true})
  rooms: Room[]
}

@Entity()
export class Bed {
  @PrimaryColumn('char', {length: 16})
  id: string
}

@Entity()
export class Room {
  @PrimaryColumn()
  roomNumber: number
  @ManyToOne(type => House, house => house.rooms, {
    primary: true,
  })
  house: House

  @OneToOne(type => Bed, {cascade: true, eager: true})
  @JoinColumn()
  bed: Bed
}
```

In my test, the `@ManyToOne` relation in `Room` contains `primary: true` or `nullable: false`, the script failed because it always try to inserting the new `Room` before `Bed` is created. If I remove `primary: true`, it knows it should insert `Bed` before a `Room` is created.

Via debugging I found that it's `SubjectTopoligicalSorter.sort("insert")` sorting the subject incorrectly (source code around `typeorm/src/persistence/SubjectExecutor.ts:115`)

Below is the minimum code to reproduce the issue. 
```ts
import 'reflect-metadata'
import {
  Column,
  ConnectionOptions,
  createConnection,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToMany,
  OneToOne,
  PrimaryColumn,
} from 'typeorm'

@Entity()
export class House {
  @PrimaryColumn('char', {length: 16})
  id: string
  @OneToMany(type => Room, room => room.house, {cascade: true, eager: true})
  rooms: Room[]

  constructor(data: {
    id: string
    rooms: Room[]
  }) {
    Object.assign(this, data)
  }
}

@Entity()
export class Bed {
  @PrimaryColumn('char', {length: 16})
  id: string

  constructor(data: {
    id: string
  }) {
    Object.assign(this, data)
  }
}

@Entity()
export class Room {
  @PrimaryColumn()
  roomNumber: number
  @ManyToOne(type => House, house => house.rooms, {
    primary: true,
  })
  house: House

  @Column()
  north: boolean = true

  @OneToOne(type => Bed, {cascade: true, eager: true})
  @JoinColumn()
  bed: Bed

  constructor(data: {
    roomNumber: number
    bed?: Bed
  }) {
    Object.assign(this, data)
  }
}

(async () => {
  const config: ConnectionOptions = {
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'root',
    password: 'secret',
    synchronize: false,
  }
  const connection0 = await createConnection(config)
  await connection0.createQueryRunner().query(`DROP DATABASE IF EXISTS mydb;`)
  await connection0.createQueryRunner().query(`CREATE DATABASE mydb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`)
  await connection0.close()

  const connection = await createConnection({
    ...config,
    database: 'mydb',
    entities: [
      House, Room, Bed,
    ],
    synchronize: true,
    logging: true,
  })
  try {
    const record = new House({
      id: 'house_1',
      rooms: [
        new Room({
          roomNumber: 1,
          bed: new Bed({
            id: 'bed_1',
          }),
        }),
      ],
    })
    await connection.getRepository(House).save(record, {
      transaction: false
    })
  } catch (error) {
    console.log('<b>Error: ', JSON.stringify(error, null, 2), '</b>')
    console.log('Error: ', error)
  }
  await connection.close()
})().catch(async error => {
  console.log('<b>Error: ', JSON.stringify(error, null, 2), '</b>')
  console.log('Error: ', error)
})
```

**Comment by zorji** [comment]
Duplicated #2853

**Comment by rfclib** [comment]
Hey @zorji I'm facing the same issue. What solved the issue for you?

**Comment by zorji** [comment]
@rfclib It's not solved. I ended saving the entities manually.

**Comment by rfclib** [comment]
@zorji Thanks for the reply!! If you don't mind, can you please tell me how you did it manually?

**Comment by zorji** [comment]
@rfclib In my example, I'd expect when I save Room, it should also save Bed and House for me. Because it doesn't do it the way I expect, I need to manually save the House and Bed to the database first and save the Room entities last.

**Comment by rfclib** [comment]
@zorji Understood. Thanks a ton for the replies!

**Comment by ivelten** [comment]
I just found a workaround for this. Seems like the seed algorithm orders seeding by the file name inside your seed scripts folder. So, if you have a seed script file for each entity, you can put a number before the script to order them by name. Like, if you have 3 scripts `house.ts`, `bed.ts` and `room.ts`, rename them to `1-house.ts`, `2-bed.ts`, `3-room.ts`. This worked for me.
