### ISSUE TITLE
Overlap between two arrays (common elements)

### ISSUE THREAD

**Issue by sushilbansal** [typeorm/typeorm#2855]
**Issue type:**
[ x] question

**Database system/driver:**
[ x] `postgres`
[ x] `expo`

**TypeORM version:**
[ x] `latest`

**Steps to reproduce or a small repository showing the problem:**
How i can get an overlap between two arrays like mentioned here in PG documentation: https://www.postgresql.org/docs/9.1/static/functions-array.html

I tried: where("post.categories && :categories", { categories })
where("post.categories && (:categories)", { categories })

Did not work. any suggestions please?

**Comment by vlapo** [comment]
Hi @sushilbansal,

TypeORM support all SQL operators in SQL statements.`where` method you are using accepts raw SQL so it is definitely possible. Here is example from our application where we are using this operator.
```
qb.where('offer.categories && ARRAY[:...queryCategories]::varchar[]', { queryCategories });
```
But @elthrasher suggestion to enable logging should be good method to validate your queries. For example in some cases you have to change array type in SQL or any other SQL related issues could be detected.

Let me know if this help.

**Comment by rustamwin** [comment]
Closing since there is no answer from author

**Comment by doghappy** [comment]
@vlapo How to write it by using query object instead of queryBuilder?
