### ISSUE TITLE
adding support for IORedis in TypeORM

### ISSUE THREAD

**Issue by HussainAliAkbar** [typeorm/typeorm#2856]
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x ] `@next`
[ ] `0.x.x` (or put your version here)

Hi!
TypeORM currently uses node_redis to interact with the redis server to cache the results. It would be great if we could add support for IORedis as well. I went through the code and it doesn't look much hard to implement (i might be wrong though!). I identified 3 files where code will need to be changed:

**RedisQueryResultCache.ts**
A new class will need to be created just like this one which which interact with IORedis, create its instance, get and set values etc. lets name it "IORedisQueryResultCache"

**QueryResultCacheFactory.ts**
A new type will need to be added here like "ioredis" which will create a new instance of the class "IORedisQueryResultCache"

**PlatformTools.ts**
a new case for ioredis will need to be added.

I'd be happy to work on this and submit a PR if this seems like a feasible solution! Happy to know what you guys think of this.

**Comment by HussainAliAkbar** [comment]
@Kononnable  @pleerock Since this feature was needed by my team, i went ahead and made the changes. The changes can be found in this PR:

https://github.com/typeorm/typeorm/pull/3215

I have tested this feature manually and it works perfectly. I however, have not added any tests yet because i wasn't sure what/which tests to add. Some guidance related to what sort of tests i can add for this feature would be great. In the meantime, i will also look at adding tests for this feature as well.

**Comment by pleerock** [comment]
Closing it since PR was already merged.
