### ISSUE TITLE
MSSQL Select not maintaining specified types

### ISSUE THREAD

**Issue by eribeiro-datis** [typeorm/typeorm#2857]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.6`

**Steps to reproduce or a small repository showing the problem:**

I have an entity with a column of type `char` and length 3.

```ts
import { Entity, PrimaryColumn, Column } from 'typeorm';

@Entity('Companies')
export class Company {
  @PrimaryColumn({ type: 'char', length: 3 })
  Company: string;
}
```

I am using the SelectQueryBuilder to pass a parameter for that column in my WHERE statement.

```ts
const connection = getConnection();
const repo = connection.getRepository(Company);
return await repo.findOne({ Company: 'AHI' });
```

When I look at the query in SQL Profiler, it shows that the parameter is being sent as an `nvarchar` which is adding a scan and slowing down the query.

![screen shot 2018-09-27 at 11 05 33 am](https://user-images.githubusercontent.com/28350937/46155612-b4674980-c245-11e8-951b-003a35a1677e.png)

![screen shot 2018-09-27 at 11 07 15 am](https://user-images.githubusercontent.com/28350937/46155674-dc56ad00-c245-11e8-9b32-8561f848c978.png)

Am I missing a config option somewhere? I can see the columns types are passed correctly during INSERTs and UPDATEs, but not SELECTs.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by eribeiro-datis** [comment]
I found that in the WHERE clause, I can specify the type

```ts
// SelectQueryBuilder
.andWhere('company = :company', { company: new MssqlParameter(company, ‘char’, 3) })
```

Closing issue

**Comment by pedhenrique** [comment]
I'm having a similar issue. My model uses a varchar, but the queries send to the database by TypeORM are using nvarchar for MSSQL. Is this a bug @pleerock ?

Is there any configuration I can do to force the use of model type?

**Comment by nebkat** [comment]
If you pass a `new MssqlParameter()` as shown above it should work?

**Comment by pedhenrique** [comment]
It definitely works, but shouldn't the type be inferred from the model itself, like what happens with INSERTs and UPDATEs? 

What you're suggesting sounds to me more as a workaround than a definitive solution, no?

**Comment by nebkat** [comment]
You are correct, I'm working on a change #7282 that will do this. For now that is the only way unfortunately.

**Comment by pedhenrique** [comment]
That's really cool! Thanks @nebkat for the great work.
