### ISSUE TITLE
In Browser REST ORM client

### ISSUE THREAD

**Issue by badre429** [typeorm/typeorm#286]
Create A ORM on the browser for REST API

**Comment by pleerock** [comment]
this quite complicated feature that requires a good proposal and deep solutions of all related problems... If you want to contribute toward this functionality start with a good proposal of how you see it will work

**Comment by valeriy-devpronet** [comment]
Honestly, I do not like the idea make typeorm like multi-tool. Logic may be more and more complicated to satisfy the need for every type of developer. Polymorphism is great approach but not in cases when there are totally different ways for managing data in relational db and nosql. There may be a situation when typeorm will die because of many compromises between different approaches. Even upcoming MongDB release scares me because MongoDB and already implemented DB so different as it may this difference be. Personally I'm doing a migration from MongoDB to Postgres, first try it was Bookshelf until I did not meet TypeOrm and this was love from first view. In readme there is wrote that inspiration was taken from orms like Doctrine and others, I will not say about other orms, but as for Doctrine there is difference between projects. Doctrine for relational ORM and Doctrine for MongoDB. I hope that TypeOrm will not contain 'everyting-in-one'. And will go to the way when for each approach will be dedicated tool.

Thanks.

**Comment by pleerock** [comment]
thank you for your valuable feedback @valeriy-devpronet . I totally understand what you are talking about. Regarding to this particular request, it will not be implemented in typeorm core anyway. There are quite of challenges to implement this request, and if it will be implemented I sure it will be implemented in a separate additional library. Regarding to mongodb I understand your disturbances and some of them aren't reasonless. However in this case I want typeorm to be database-polymorfic as much as it can be, until some day. Once typeorm get more attention and users, and contributors team will be established we will think how to extract each non-relational type of database into their separate packages and make typeorm as modular as possible with different both light and heavy versions of orm the best way.

**Comment by sajjad-shirazy** [comment]
may i know how is the state of this feature request? does work anybody on it?

**Comment by pleerock** [comment]
no, its not that easy. If you are interested in the feature start with investigating how things should work and create a design proposal.

**Comment by sajjad-shirazy** [comment]
ok, these are what i guess must be:

### Driver Options:
* Url : 
base url of a RESTfull api. e.g. https://example.com/api/v1/

* Authentication Token :
a http request header key which provides user authentication in stateless comunications. usually a JWT token. e.g.
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
### Entity Manager:
* Create:
POST record to  https://example.com/api/v1/{entity}s/
* UpdateById:
PUT record to  https://example.com/api/v1/{entity}s/{id}
* RemoveById:
DELETE request to  https://example.com/api/v1/{entity}s/{id}
* FindOneById:
GET request to  https://example.com/api/v1/{entity}s/{id}
* Find:
GET request to  https://example.com/api/v1/{entity}s/?query={query}
### Relationships
* One to One:
CRUD on https://example.com/api/v1/{entity-1}s/{id}/{entity-2}/
CRUD on https://example.com/api/v1/{entity-2}s/{id}/{entity-1}/
* One to Many:
CRUD on https://example.com/api/v1/{entity-1}s/{id}/{entity-2}s/{id}
CRUD on https://example.com/api/v1/{entity-2}s/{id}/{entity-1}/
* Many to Many:
CRUD on https://example.com/api/v1/{entity-1}s/{id}/{entity-2}s/{id}
CRUD on https://example.com/api/v1/{entity-2}s/{id}/{entity-1}s/{id}

**Comment by pleerock** [comment]
Looks good. What about `https://example.com/api/v1/{entity}/?query={query}` - what is `query` here? And how shall we handle parameters security (escaping, validation and so on)

**Comment by sajjad-shirazy** [comment]
Regarding `{query}` it's a contract. take a look:
https://stackoverflow.com/questions/207477/restful-url-design-for-search
but i personally use an encoded JSON object as the `{query}` with this structure:
```
[
    ['property', 'operator', 'value'],
    ['property', 'operator', 'value'],
   ...
]
```
* `value` could be number/string/boolean or an array of values in case of `IN` operator
Regarding parameters security (escaping, validation and so on) i suggest leaving it for server side ...

**Comment by pleerock** [comment]
> Regarding {query}, it's a contract.

but how do you design contract? Queries can be quite flexible, how to achieve same flexibility that query builder can provide using simple query parameter?

> Regarding parameters security (escaping, validation and so on) i suggest leaving it for server side

of course it should be server-side, the question is how do we control it using this design.

**Comment by sajjad-shirazy** [comment]
> Regarding {query}, it's a contract.
you are right. we can have a default query generator and also an option for getting a query generator handler in the driver options. it gets parameters and return a string to append to the url.

> the question is how do we control it using this design.
no idea ...

**Comment by valeriy-devpronet** [comment]
What if try to use not REST but GraphQL?
http://graphql.org/

**Comment by sajjad-shirazy** [comment]
both are necessary and usefull

**Comment by sajjad-shirazy** [comment]
@pleerock what's the next?

**Comment by pleerock** [comment]
you have described very basic aspects of "rest client". We should go deeper and think about all problems with this new feature. Problems in details as usual. Next is to found solution for my questions:

> Regarding {query}, it's a contract.

> but how do you design contract? Queries can be quite flexible, how to achieve same flexibility that query builder can provide using simple query parameter?

> Regarding parameters security (escaping, validation and so on) i suggest leaving it for server side

> of course it should be server-side, the question is how do we control it using this design.

**Comment by BellerophonM** [comment]
I was wondering about this myself, specifically in the context of OData, which is a well-established and highly specified standard. An implementation of OData querying as a connection option would be a good way of providing this functionality without having to ad-hoc an entire REST specification. Thoughts?

**Comment by HanSeungHo** [comment]
breeze converts client query to OData URI.
- breeze - http://breeze.github.io/doc-js/features.html
- https://github.com/Breeze/breeze.js/blob/master/src/b00_breeze.uriBuilder.odata.js

**Comment by pleerock** [comment]
Im going to close this issue because it lacks of real proposal and generally looks like out of scope of ORM. Feel free to continue discussion however.

**Comment by jcrben** [comment]
The rather mature ORM SQLAlchemy is sometimes used to develop automatic restful APIs - see http://jasonrhaas.com/2017/07/17/adding-a-simple-api-to-your-postgres-database.html using https://github.com/jfinkels/flask-restless  for example

lots listed at https://github.com/dbohdan/automatic-api

anyway agreed that this is a big lift and a distraction right now
