### ISSUE TITLE
Promote the new slack group

### ISSUE THREAD

**Issue by tomspeak** [typeorm/typeorm#2862]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

We should advertise the slack group mentioned in #2784.

Do you think that the Slack group should deprecate Gitter?

**Comment by pleerock** [comment]
yes it should, thanks!

**Comment by eranganovade** [comment]
If you're wondering how to get the invite to Typeorm Slack, try [this invite link](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g). 🎉

**Comment by y-nk** [comment]
@eranganovade could i get an updated link 🙏 ?

**Comment by eranganovade** [comment]
@y-nk Use [this link](https://join.slack.com/t/typeorm/shared_invite/zt-uu12ljeb-OH_0086I379fUDApYJHNuw)

**Comment by sbahman** [comment]
@eranganovade could I also get an updated link? 🙏

**Comment by eranganovade** [comment]
@sbahman Try [this link](https://join.slack.com/t/typeorm/shared_invite/zt-1urxzwn7r-AMhcn1ffMc9BKmdE~9TZog) which is valid for 30 days from now.

**Comment by KsaRedFx** [comment]
Could I get a link as well?

**Comment by eranganovade** [comment]
Try [this never expiring link to join TypeORM Slack group](https://join.slack.com/t/typeorm/shared_invite/zt-1xu3kacbn-RR~TH2wfXFxPjLWPMRS26Q). Hope it works.
