### ISSUE TITLE
Simple select in SQLite fails to map aliased properties to entity attribute names

### ISSUE THREAD

**Issue by rgangopadhya** [typeorm/typeorm#2864]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[x] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I've done some googling and searching through opened and closed issues in this repo, but very possible I missed this... I feel like I am missing something simple. I am running Expo (react native), no typescript.

Setup:

```
import { Entity, Column, PrimaryColumn } from 'typeorm/browser';

@Entity()
export class Character {

  @PrimaryColumn('int')
  id: number;

  @Column('text')
  name: string;

  @Column({ type: 'text', nullable: true })
  local_image: string;

  @Column('text')
  s3_image: string;

  @Column('datetime')
  created_at: Date;
}
```

connection setup:
```
  dbConnect() {
    return createConnection({
      type: 'react-native',
      database: 'bbook',
      location: 'default',
      logging: ['error', 'query', 'schema'],
      synchronize: true,
      entities: [
        Character
      ]
    });
  }
```

Insert some data into table (I pulled from my server API). Then, query using [documented](http://typeorm.io/#/select-query-builder) API:

```
  const result = await getConnection()
    .createQueryBuilder()
    .select('character')
    .from(Character, 'character')
    .getMany();

   console.log('=== from db', result);
```

<img width="560" alt="screen shot 2018-09-28 at 11 34 00 am" src="https://user-images.githubusercontent.com/3359924/46226949-ac291000-c312-11e8-98cb-d2eeda39e489.png">

This shows that the (expected) 3 results were returned, but with the values all undefined. 

What happens if we try `getRawMany`?

<img width="557" alt="screen shot 2018-09-28 at 11 36 56 am" src="https://user-images.githubusercontent.com/3359924/46227018-d5e23700-c312-11e8-92a7-3312865f8006.png">

Ok, so this shows that the data is being stored properly in SQLite. The issue seems to be that there is no conversion from using the alias as a prefix for each column name to the entity name. I feel like I am missing something really simple here but have found nothing. Is there an issue in my config, or, if there is an issue with the query, what should be updated in the documentation to make the correct query possible? Thanks.

**Comment by elthrasher** [comment]
Can't find a way to run this with existing unit tests, so I'd need to see a sample repo to dig in, but you say you aren't using TypeScript, but you are using the decorators? I doubt that works. Here's a sample of how to use typeorm without TypeScript: https://github.com/typeorm/javascript-example/blob/master/src/app2-es5-json-schemas/entity/post.json
