### ISSUE TITLE
Questions About Cache Library

### ISSUE THREAD

**Issue by icruzr93** [typeorm/typeorm#2868]
1.- Is it possible to use the internal cache library to save a query result? 
ex. getConnection().query(`SELECT * FROM events AS e`, **{cache: true}**);

2.- Is it possible to use the internal cache library to save something? 
ex. getConnection().cacheWhatever().save('key', value);

Second question is derivated from first question, where i need to save result from my query.

**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by elthrasher** [comment]
`connection.query` doesn't support caching. You need to use QueryBuilder or Repository: http://typeorm.io/#/caching

It looks like you could manually instantiate a cache and do whatever you like with it:
```
const connection = await createConnection(...);
const factory = new QueryResultCacheFactory(connection);
const cache = factory.create();
cache.storeInCache(...);
```
I wouldn't necessarily recommend digging into internals like that though as this isn't a public api so it might change without warning. What problem are you trying to solve?

**Comment by i-cruz-ramirez** [comment]
> I wouldn't necessarily recommend digging into internals like that though as this isn't a public api so it might change without warning. What problem are you trying to solve?

I`m trying to save a big query result but like you say it is not possible yet. only with QueryBuilder or Repository, So i'm looking for options to save that result.

Do you have any recommended options?

**Comment by imnotjames** [comment]
Looks like this was more or less answered.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
