### ISSUE TITLE
find orWhere

### ISSUE THREAD

**Issue by ayonsaha2011** [typeorm/typeorm#2869]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Is there any query find orwhere ?**

**Comment by kodayashi** [comment]
I just see a where, and there's no documentation as to whether or not multiple conditions in the where us the AND or the OR conditional - https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#basic-options

@pleerock - Does "where" in find options use AND? If so, I would also like to see an `orWhere` in FindOneOptions, that would be sweet!

**Comment by kodayashi** [comment]
Or perhaps you could specify which operator to use with the where? Not sure what's best, or even if there's already a way to solve this :)

**Comment by pleerock** [comment]
or is possible using following syntax:

```ts
userRepository.find({
  where: [
    { firstName: "Timber", lastName: "Saw" },
    { firstName: "Stan", lastName: "Lee" }
  ]
});
```

documentation was updated recently.

**Comment by ndarilek** [comment]
I read these docs yesterday and am wondering if it's possible to do something like `where something = 0 and (somethingelse = 1 or somethingelse is not null)`? I'd like to see an example that mixes AND and OR if possible.

Thanks!

**Comment by rodrigoimenes** [comment]
> I read these docs yesterday and am wondering if it's possible to do something like `where something = 0 and (somethingelse = 1 or somethingelse is not null)`? I'd like to see an example that mixes AND and OR if possible.
> 
> Thanks!

Did you find some examples?

**Comment by ndarilek** [comment]
No, I eventually switched to using the query builder. I don't think it's 
possible with the simpler method.

**Comment by php1webmobtech** [comment]
@ndarilek can you find any way?

**Comment by jacobdo2** [comment]
Are there any news on this?

**Comment by neekey** [comment]
> I read these docs yesterday and am wondering if it's possible to do something like `where something = 0 and (somethingelse = 1 or somethingelse is not null)`? I'd like to see an example that mixes AND and OR if possible.
> 
> Thanks!

any solution about this?

**Comment by neekey** [comment]
to be honest, the syntax of using array form of `where` implies `or` condition is pretty bad design, as well as the key-value form of `where` means `and` condition.

From a person using SQLAlchemy in Python, it has helper functions like `and_` and `or_` where each accepts a list of conditions, so you can nest them all together to compose very complicated queries (the code below is in Python):

```python
User.query.filter(
  and_(
     User.type == 'admin',
     or_(
        User.firstName == 'test',
        User.lastName == 'test'
     ) 
 )
)
```

**Comment by santiagolarsen** [comment]
Hello! I've got another question related to this. I have to implement an OR query which is nested inside a property on the query object itself that I was using in find({where: queryObject). My query object looks like this:
`VenueQueryResultObject {
    locality?: string;
    status: VenueStatus;
    localityType?;
    size?: FindOperator<number>;
    rental?: {
        weekdayRate?: FindOperator<number>;
        eventTypes?: { [type: string]: boolean }[]; // This is where I need the OR query
    };
}`
I thought the array syntax could work but it doesn't, should I use the query builder to implement this or is there something I'm missing?

**Comment by Belligerator** [comment]
> > I read these docs yesterday and am wondering if it's possible to do something like `where something = 0 and (somethingelse = 1 or somethingelse is not null)`? I'd like to see an example that mixes AND and OR if possible.
> > Thanks!
> 
> any solution about this?

Here is a workaround, but it doesn't look clean. 

```
// If we refactor entity, we have to change it in query too. (or use MyEntity.name)
const entityName: string = this.myEntityRepository.metadata.targetName;

const myEntity: MyEntity[] = await this.myEntityRepository.find({
    where: {
        active: true,
        firstName: Raw(() => `(${entityName}.firstName LIKE :pattern OR ${entityName}.lastName LIKE :pattern)`, { pattern: `%${pattern}%` 
    }
});
```
