### ISSUE TITLE
OneToMany cascadeRemove

### ISSUE THREAD

**Issue by lucas-coelho** [typeorm/typeorm#287]
If I have the following schema:

`Cart`
```
  @PrimaryGeneratedColumn()
  id: number;

  @OneToMany(type => CartItem, product => product.cart, {
    cascadeInsert: true,
    cascadeUpdate: true
  })
  cartItems: CartItem[];
```

and CartItem:

```
  @PrimaryGeneratedColumn()
  id: number;
  @ManyToOne(type => Cart, {
        cascadeInsert: true,
        cascadeUpdate: true,
        cascadeRemove: true
    })
  cart: Cart;
```

Why I can't automatically remove in OneToMany relation?

I'm training to delete all the cart items but it just remove the cart reference from the cart items.
But when I delete the a reference from one of the cart item, it will remove the cart and all its reference.

I think this logic is twisted..  it could delete from the OneToMany relation but not from ManyToOne relation.

**Comment by 19majkel94** [comment]
Yeah, I'm upgrading my backend from `0.0.2-alpha.70` to `0.0.9` now and I have the same question @pleerock. I think that it's because casadeDelete logic was very complicated and not compatible with mongo integration, right?

But this is really like degrading the ORM by manually calling repository to delete are objects from OneToMany relation. If there is no substitute for that (because `onDelete` has been gone too), it's a deal breaker for me 😞

**Comment by 19majkel94** [comment]
Yeah, I'm upgrading my backend from `0.0.2-alpha.70` to `0.0.9` now and I have the same question @pleerock. Is this because (in this example) `CartItem` should set ` onDelete: "CASCADE"` to achieve the behavior when we delete `Cart` item and want to destroy all `CartItem`s?

**Comment by pleerock** [comment]
cascades, especially cascade removes are mess right now. Don't recommend to use them until I finish its design and resolve all related problems. As lucas-coelho mentioned the logic is twisted...

**Comment by AlexandreAWE** [comment]
Hello,
Same problem as @lucas-coelho

**Comment by erinpagemd** [comment]
what is the work around for now?

**Comment by pleerock** [comment]
workaround is to simply manually remove related objects, e.g. call `entityManager.remove`

**Comment by 19majkel94** [comment]
For me it's a big drawback that such basic things like cascade inserting is buggy and there's no cascade delete at all and we have to do everything manually. I wish I could help... is there any tutorial for beginners about how ORMs work? 😆 I could read it and understand the magic which is happening under the hood to make some contributions...

Even `onDelete` has been removed from relation decorators, so no `cascade` on db level is available although I see the support for it in query runners and others 😞

**Comment by pleerock** [comment]
as I already told earlier this is one of the most complex functionality of the framework. It seems so harmlessly but in fact its not... If I start fixing it it may take me months to fix it and all related problems. But there are dozen of other not less important issues need to be fixed. If I start fixing it and disappear for months other issues will have to wait for such a long period which is not good.

> Even onDelete has been removed from relation decorators, so no cascade on db level is available although I see the support for it in query runners and others 

No, `onDelete` still exists in the

**Comment by pleerock** [comment]
Cascade remove functionality is dropped and will be completely removed in `0.2.x`. Instead users must use `onDelete` functionality and database-level cascade deletion. This is new design and strategy typeorm follows and it resolves all issues with application-level cascades.

**Comment by keenondrums** [comment]
@pleerock 

> No, onDelete still exists in the relation options
There's no onDelete for oneToMany. Why is it so?

**Comment by 19majkel94** [comment]
@keenondrums Because you have to do `onDelete` on `@ManyToOne` which is holding the reference?

**Comment by keenondrums** [comment]
@19majkel94 that's what I figured, but it does not work for SQLite. I'll be repoducig the bug and opening an issue then. Asked just because I started doubting my sanity. Thanks!
