### ISSUE TITLE
Query the same ID after inserting

### ISSUE THREAD

**Issue by ws-applet** [typeorm/typeorm#2870]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
    const arr = [
        {name: 'name1', identify: 'identify1'},
        {name: 'name2', identify: 'identify2'},
        {name: 'name3', identify: 'identify3'},
      ]
      
      await resourceRepository.insert(arr)
```

SQL:
```
query: INSERT INTO `resource`(`id`, `name`, `identify`) VALUES (DEFAULT, ?, ?), (DEFAULT, ?, ?), (DEFAULT, ?, ?) -- PARAMETERS: ["name1","identify1","name2","identify2","name3","identify3"]
query: SELECT `Resource`.`id` AS `Resource_id`, `Resource`.`name` AS `Resource_name` FROM `resource` `Resource` WHERE (`Resource`.`id` = ?) -- PARAMETERS: [1]
query: SELECT `Resource`.`id` AS `Resource_id`, `Resource`.`name` AS `Resource_name` FROM `resource` `Resource` WHERE (`Resource`.`id` = ?) -- PARAMETERS: [1]
query: SELECT `Resource`.`id` AS `Resource_id`, `Resource`.`name` AS `Resource_name` FROM `resource` `Resource` WHERE (`Resource`.`id` = ?) -- PARAMETERS: [1]
```
The same ID was queried three times

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by marioblazev** [comment]
I've just run into this same issue. Makes the insert query builder unusable as you end up with incorrect duplicate PK's in your entities.

Also, is there a way to disable the select after insert? It would be nice if the selects were optimised rather than one per record.

**Comment by pleerock** [comment]
Actually, it wasn't supposed for `insert` to execute any additional query or return `InsertResult` result.

For, now to fix your issues you need to create insert query builder instead of using `insert` method from manager. Example:

```ts
        manager.createQueryBuilder()
            .insert()
            .into(EntityCls)
            .values(entities)
            .updateEntity(false)
            .execute();
```

**Comment by marioblazev** [comment]
In my case, I was using the `createQueryBuilder()` and had the same issue. Including `updateEntity(false)` removes the bad selects after the insert and allows me to optimise the query so that is helpful, thank you!

**Comment by imnotjames** [comment]
Is this still a problem?  We made a few changes that might have fixed this problem.
