### ISSUE TITLE
Add the project to hacktoberfest

### ISSUE THREAD

**Issue by galkin** [typeorm/typeorm#2877]
Thank you for awesome project!
Could you add this project to [hacktoberfest](https://hacktoberfest.digitalocean.com/)?
It's very simple, only `hacktoberfest` label creation is required.

**Comment by vlapo** [comment]
So we have to mark issues with this label and it will be available to search in hacktoberfest ?

**Comment by pleerock** [comment]
I think hacktoberfest is already finished?

**Comment by havenchyk** [comment]
Right, it’s finished :)

**Comment by gtpan77** [comment]
@pleerock, Could you add this project to [hacktoberfest](https://hacktoberfest.digitalocean.com)?
