### ISSUE TITLE
Firebird Support

### ISSUE THREAD

**Issue by edu-ricardo** [typeorm/typeorm#2880]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

[x] 'firebird' - new

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi, I wanted to use the typeorm in a project that I use firebird, I even started to develop, if it could be useful I could add to the project.

**Comment by pleerock** [comment]
As it was mentioned multiple times we don't have in plans to implement new drivers in a near future. If you want to contribute - please feel free! To keep issues cleaner lets close this one and continue discussion in #4

**Comment by kerwynrg** [comment]
What is missing to integrate your changes to typeorm repo?
