### ISSUE TITLE
Filtering based on a column in many to many relationship

### ISSUE THREAD

**Issue by LogeswaranAnandan** [typeorm/typeorm#2886]
**Issue type:**

[x ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Similar to the issue #2135 

I have implemented multiple functionalities using repository.find(). Now due to a schema change I have to alter all the endpoints to fetch data based on a where condition of many to many relation.

```
this.entityRepo.find({
    where: {
        rel: { id: myValue}
    }
});
```

The Entity has many eager relationships, if I rewrite them using query builder then all the relations have to be inner joined manually which takes a lot of time to rework.

Do I have to rewrite all the methods using query builder? or is there a way to implement it using repository.find()?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
