### ISSUE TITLE
http://typeorm.io/    website not working , from where i can find documentation ?

### ISSUE THREAD

**Issue by Meesam** [typeorm/typeorm#2888]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
It works for me. However docs are also saved as markdown files in docs folder in source.

**Comment by csuich2** [comment]
Working for me as well. @Meesam Are you still having issues?

**Comment by Krishna-Reflections** [comment]
TypeOrm documentation
![Screenshot 2022-12-08 124216](https://user-images.githubusercontent.com/91408997/206382474-37d9d768-4052-4cab-a123-147135658d82.png)
 is not showing

**Comment by noobd3v** [comment]
getting same issue.
<img width="883" alt="image" src="https://user-images.githubusercontent.com/13329441/206473256-68a46591-713d-4df4-8b05-ad5e6ff59de9.png">

**Comment by dhruv1409** [comment]
+1 for me too ! can anybody suggest

**Comment by Snowdrop-ctrl** [comment]
it's working some of user's and some for not.

**Comment by Deepak22448** [comment]
Has anyone found a solution to this issue?

**Comment by sahilpurav** [comment]
I'm facing the same problem.

**Comment by Deepak22448** [comment]
@sahilpurav I found a solution just use VPN then it will work , for more details you can refer issue #9705.

**Comment by noobd3v** [comment]
It seems to be an issue with network provider they seems to block some github user content at certain locations. Not sure what else is used to block the content but it is linked with network provider only, once I switched the network provider at my location the Documentation was visible.

**Comment by viralRupani** [comment]
It is the issue of firewall or ISP. I was having the same issue, TypeOrm is fetching its content from GitHub raw content, from here: https://raw.githubusercontent.com/  and your ISP or Firewall is blocking that page, just search how to allow raw GitHub content to your ISP or Firewall.
