### ISSUE TITLE
TypeORM Repository throws error on return types when wrapping it in a custom class

### ISSUE THREAD

**Issue by HussainAliAkbar** [typeorm/typeorm#2890]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I needed to add some custom functionality to the Repository so I made a wrapper class for Typeorm Repository. This wrapper class adds some new functions to the Repository class as well as overrides existing ones such as save,update etc.

```ts
export class TypeORMRepositoryWrapper<Entity> {
  public entityTableName: string;
  public roleName: string;
  public entityClass: ObjectType<Entity>;

  constructor(entityTableName: string, roleName: string, entityClass: ObjectType<Entity>) {
    this.entityTableName = entityTableName;
    this.roleName = roleName;
    this.entityClass = entityClass;
  }

  public getRepository<Entity>(connectionName: string = 'default'): Repository<Entity> {
    const repository = getConnectionManager()
      .get(connectionName)
      .getRepository<Entity>(this.entityClass);

    /*
    insert custom functions as well
    repository.customFunction = some function

    override default functions such as save, update, insert
    repository.insert = async (entity: Entity | Entity[], options?: SaveOptions): Promise<InsertResult> => {
      // custom functionality here
      return repository.manager.insert(repository.metadata.target, entity, options);
    };
    */
    return repository;
  }
}
```

next, I have a function which creates an instance of this TypeORMRepositoryWrapper and then invokes the getRepository method of that class which gives me a TypeORM Repository.

```ts
export const findById = async (id: number): Promise<City | undefined> => {
  const customRepo = new TypeORMRepositoryWrapper( 'some entity name','some role',City).getRepository();
  return customRepo.findOne({
    where: {
      id,
    }
  });
};
```
now, according to the documentation and the code that i went through, findOne will either return an instance of the entity (in this case City) or it will return undefined. However, Typescript throws an error here that: 

> Type '{} | undefined' is not assignable to type 'City | undefined'.
>   Type '{}' is not assignable to type 'City | undefined'.
>     Type '{}' is not assignable to type 'City'.
>       Property 'id' is missing in type '{}'. (2322)

same is the case with the find function. It should return an array of the Entities and an empty array however it throws a similar error:

> type '{}[]' is not assignable to type 'City[]'.
>   Type '{}' is not assignable to type 'City'. (2322)

Please note that i have not tinkered with the find and findOne functions in any way. I have not touched them neither have i overridden them.

When i change the return types to Promise < any >, all of these problems go away!!

However, using Promise < any > here seems extremely hacky so i would like to know if there's another way to do this or if there's something wrong in my implementation which can be fixed to fix this issue!

Thanks!

**UPDATE: I FIXED IT!**
I managed to fix this issue by adding an instance of the repository as an attribute of the wrapper class like this:
```ts
export class TypeORMRepositoryWrapper<Entity> {
  public entityTableName: string;
  public roleName: string;
  public entityClass: ObjectType<Entity>;
  public repository: Repository<Entity>;

  constructor(
    entityTableName: string,
    roleName: string,
    entityClass: ObjectType<Entity>,
    connectionName: string = 'default',
  ) {
    this.entityTableName = entityTableName;
    this.roleName = roleName;
    this.entityClass = entityClass;
    this.repository = getConnectionManager()
      .get(connectionName)
      .getRepository<Entity>(this.entityClass);
      
    // add custom methods to this.repository as needed
  }
}
```

this now works perfectly. But, i would still very much like to know what was wrong in my initial implementation and what i could have done to fix that.
looking forward to the feedback!

**Comment by Quynh-Nguyen** [comment]
@HussainAliAkbar 

Thank you so much,
I'm also finding the way for implement BaseRepository extends Repository (of typeorm)

--
But how you can call your `TypeORMRepositoryWrapper` from Services, Controllers?

**Comment by HussainAliAkbar** [comment]
apologies @Quynh-Nguyen , I did not understand your question. Could you please elaborate it more?
