### ISSUE TITLE
How to use transaction with custom repository

### ISSUE THREAD

**Issue by josecolella** [typeorm/typeorm#2892]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello I'd like to use transaction in a method of a custom repository. @pleerock Do you have any examples for this?

**Comment by ryuuji3** [comment]
I did some digging and I found this section which may be of some help;
http://typeorm.io/#/transactions/transaction-decorators

If you don't use decorators, however, you can always obtain call upon `this.manager.transaction(transactionManager => ...` inside the custom repository.

So in a really stupid example of that, I was able to save 2 entities like this;

```
@EntityRepository(User)
export default class UserRepository extends Repository<User> {
    async transactionSave(user: User, photos: Photo[]) {
        const em = this.manager;
        await em.transaction(async transactionalManager => {
            await transactionalManager.save(user);
            await transactionalManager.save(photos);
        });
    }
}
```

Is that what you were looking for?

**Comment by josecolella** [comment]
@ryuuji3 Thanks. This answers my question

**Comment by ericgoe** [comment]
Hey @ryuuji3,

Let's say I want to use the transaction decorators. F.e

```
@EntityRepository(User)
export default class UserRepository extends Repository<User> {
    async transactionSave(@TransactionManager() manager: EntityManager, user: User, photos: Photo[]) {
            await manager.save(user);
            await manager.save(photos);
    }
}
```

Do I need to manually add `manager.commitTransaction()` or `manager.release()` ?
