### ISSUE TITLE
Querybuilder in trigger with relations

### ISSUE THREAD

**Issue by alex5207** [typeorm/typeorm#2893]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Lets say you have an entity A for which an @AfterInsert trigger is defined.
This trigger is supposed to insert a record into entity B with some attributes of entity C which entity A has a Many-to-one relationship with.

For now, I've been trying to use the querybuilder (Defined on entity A) as follows:

``` ts
  @AfterInsert()
  public async makeTransaction(): Promise<void> {
    await getConnection()
    .createQueryBuilder()
    .insert()
    .into(B)
    .values([{value: this.sessionDuration,from: ?, to: ?}])
    .execute();
  }
```
Where the values inserted into "from" and "to" has to be columns of entity C. How would I grab those columns?
To access a propoerty of entity A i would just use this.xxx as in above example and it works fine.

Any help is much appreciated

Regards

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
