### ISSUE TITLE
Inconsistency with relationships - Insert violates foreign key constraint 

### ISSUE THREAD

**Issue by itslenny** [typeorm/typeorm#2900]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest` (0.2.7)
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the entities: `menu` has many `menuIteration` has many `menuCategory`.

The property name on `menuCategoryEntity` for `menuIterationEntity` was just `menu`, but it's pointed to the `menuIterationEntity`. This all works great locally, but for some reason when deployed it changes and wants to point to the `menuEntity` simply because of the way the variable is named (despite the decorator pointing to `menuIterationEntity`.

As a result I got a foreign key constraint error when adding a menu category because for some reason the foreign key is pointing to the `menuEntity` instead of the `menuIterationEntity`. Simply changing the variable from `menu` to `menuIteration` fixed this, but it makes me really nervous that it's somehow implying the table name from the variable name and even more so that it behaves differently locally than on our production server. I double checked and the typeorm versions which are the same on both.

Error message:

<img width="1679" alt="screen shot 2018-10-05 at 7 42 23 pm" src="https://user-images.githubusercontent.com/5210230/46575959-8df78b80-c974-11e8-8982-6eef636dbcfe.png">

Mitigation:

<img width="759" alt="screen shot 2018-10-05 at 8 21 29 pm" src="https://user-images.githubusercontent.com/5210230/46575961-9354d600-c974-11e8-8585-7956cf7e34e3.png">

**Comment by Kononnable** [comment]
You must have some differences between production and local development environments. On the same configuration it should work the same way.
Check your database for differences and connection settings like schema sync.

**Comment by itslenny** [comment]
@Kononnable 

You're probably right. I'm not sure where the difference is, but either way the relationship table shouldn't be inferred by the name of the instance variable name in any way. I should be able to call a relationship to users "owners" or "friends" or whatever. In most cases I can, and I have it working, but in this particular instance when I change the name of the property "menu" vs "menuIteration" it tries to relate it to a different table which is a huge bug.

**Comment by itslenny** [comment]
@Kononnable 

I have synchronize disabled. I didn't do any additional migrations between tests. This has nothing to do with database structure.

The query generated by typeorm when the variable is named "menu" tries to join with the "menu" table, but when I rename it to "menuIteration" it joins to the "menuIteration" table. No other changes were made other than what is shown above.

**Comment by Kononnable** [comment]
Closing as no response from the author.
