### ISSUE TITLE
The documentation makes it more difficult than it should be ...

### ISSUE THREAD

**Issue by FredericLatour** [typeorm/typeorm#2901]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Honnestly , the current documentation is very lacking. I struggled hours trying to get some request done without much success.

For instance:

- I couldn't find a single example where you select more than one field explicitely (eg: SELECT x, y, z )
- I couldn't find a single example where you select fields from a joined table (eg: SELECT t1.x, t1.y, t2.z FROM t1 inner join t2 on ....)
- I couldn't find a single example with a where clause involving field from a joined table (e: SELECT t1.x, t1.y, t2.z FROM t1 inner join t2 on ... WHERE t2.z = 'some value'.)
- Still not sure if I can use SQL function in where clause (eg: SELECT x, y, z FROM t1 WHERE year(x) = someyear)
- There's no reference that I could check to get clarification on some function or method

I picked sequelizejs a couple of days ago (had not previous experience) and was able to get something that works in a couple of hours:

```typescript
const query = {
    attributes: ['id', 'purchase_id', 'purchase_date', 'regname', 'bc_company'],
    include: [
      {
        model: tables.purchased_items,
        required: true,
        attributes: ['id', 'purchase_id_id', 'product_id', 'product_name'],
        include: [
          {
            model: tables.lickeys,
            required: true,
            attributes: [
              'purchase_item_id',
              'key',
              'maintenance_end_date',
              'license_type',
              'replace_key_id',
              'replaced_by_id'
            ],
            where: {
               sequelize.where(
                    sequelize.fn('year', sequelize.col('maintenance_end_date')),
                   options.maintYear
             )}
          },
          {
            model: tables.products,
            attributes: ['product_id', 'product_name'],
            include: [
              {
                as: 'maintenance',
                model: tables.products,
                attributes: ['product_name', 'price_usd', 'price_eur']
              }
            ]
          }
        ]
      }
    ],
    limit: 10
  }
  return await tables.orders.findAll(query)
```

When I'm not even able to work out a much simplified single join with typeorm

 ```typescript
 const oResult = cx
            .createQueryBuilder()
            .select(['ord.id', 'ord.purchase_id', 'ord.purchase_date', 'ord.regname', 'ord.bc_company'] )
            .from(orders, "ord")
            .innerJoin('ord.puchased_itemss', 'pi')
            .addSelect(['pi.id','pi.product_name'])
            .orderBy('ord.id', 'DESC')
            .getMany()

  return oResult
```

I can make this relation work when I'm not using querybuillder that way:

```typescript
   const result = orderRepo.find({
     select: ['id', 'purchase_id', 'purchase_date', 'regname', 'bc_company' ],
     relations: ['purchased_itemss'],
     order: { id: 'DESC' },
     take: 5
   })
```

But then I don't know how to select specific fields using this approach. I don't even know if it's possible. I could find an issue where someone is asking but he never get an answer.

I decided to give a go to typeOrm because I'm a typescript guy and had heard lots of good things but  it's too much frustration. Of course, I tried hard to find if those questions had been answered before but mostly, I just could find unanswered questions or incomplete and sometimes wrong answers.

So either the guys using typeOrm are very smart or I'm stupid or both but I just can't see how you can get anything done (without spending hours and hours of try hard and googling) past basic CRUD stuff at this time.

If someone can point me to some meaningful example, I'm more than ready to check. If not, I'll just give up on typeOrm for now.

In any cases, I thought it could be interesting to report my frustrating journey into  TypeOrm as I am certain I'm not the only one.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by feather-jmalone** [comment]
i'm not sure what the actual result/error is in your `createQueryBuilder` example, but I would suggest a slightly different approach.

try this... I'm assuming the class name of your 'orders' entity is 'Order,' but adjust line 2 if it's not:

```
const oResult = cx
  .createQueryBuilder(Order, 'ord')
  .select(['ord.id', 'ord.purchase_id', 'ord.purchase_date', 'ord.regname', 'ord.bc_company'] )
  .innerJoin('ord.puchased_itemss', 'pi')
  .addSelect(['pi.id','pi.product_name'])
  .orderBy('ord.id', 'DESC')
  .getMany();

 return oResult;
```

when you provide the entity class in your call to `createQueryBuilder`, you don't need to include a `.from()` line. additionally, the type of `oResult` will automatically be `Promise<Order[]>`.

**Comment by feather-jmalone** [comment]
also, just to be sure... the Order property that holds the relation is really called `purchased_itemss`? or is that a typo?

**Comment by FredericLatour** [comment]
Hi,
Thanks for trying.

Moving (model, alias) at createQueryBuilder level does not change anything. Without any join, both syntax return items from the model. By the way, I way prefer the `from` syntax (be it before or after the select).

As soon as I'm using `innerJoin` (I also tried leftJoin, innerJoinAndSelect, ... without more success), I don't get any more any items.

Yes, `puchased_itemss` is the relation (I auto-generated entities from a database).
And, as explained earlier, when using the follwoing approach:

```typescript
  const orderRepo = cx.getRepository(orders)
  const result = orderRepo.find({
    select: ['id', 'purchase_id', 'purchase_date', 'regname', 'bc_company' ],
    relations: ['purchased_itemss'],
    order: { id: 'DESC' },
    take: 5
  })
```
I will properly retrieve items from purchased_items (through the relation purchased_itemss). However in that case, I don't know how I can possibly select specific fields from the joined table (relation). I'm not even sure that it's possible which seems a bit weird to me if this is the case.

**Comment by feather-jmalone** [comment]
it is absolutely possible, but you need to provide more information about exactly what is happening when you use your `createQueryBuilder` code (with the `innerJoin`)... is an exception thrown? or simply no results?

**Comment by FredericLatour** [comment]
@feather-jmalone It just returns nothing. No exception thrown.
Well never mind. I will give up with TypeOrm for now and will stick with sequelize.
I should not have to try all possible ways to guess how it works. The documentation is clearly missing. I'm not the only one asking for clarifications. And the number of posts without any answers does not really inspire confidence.
Hopefully things will only get better in the future.
