### ISSUE TITLE
Is MongoDB still experimental?

### ISSUE THREAD

**Issue by rluvaton** [typeorm/typeorm#2903]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is MongoDB still experimental?

**Comment by Kononnable** [comment]
Depends what you define as experimental(I know it's used in readme). Some features are working, but not all of them(comparing to other drivers). Typeorm is mostly RDBMs focused and some functionalities will never be implemented to Mongo driver(because of differences between SQL and NO-SQL databases works). New features are mostly implemented by the community.

**Comment by ruscon** [comment]
We use, generally satisfied.
There are a lot of small notes, but most things work without problems.

**Comment by phil294** [comment]
Documentation does not really reflect what works and what doesnt, however. That would be great. For example, 
```
.find({ where: {
foo: 'bar'
}})
```
works, but
```
.find({ where: {
foo: Not('bar')
}})
```
Doesnt.

**Comment by havenchyk** [comment]
@phil294 PR with a fix is welcome :)

**Comment by pleerock** [comment]
I guess answer to this question was given and we can close this issue. Thanks for everyone's feedback!

**Comment by lonix1** [comment]
@phil294 and OP and others:

Now that you've been using it for a while, can you recommend it? Is it stable enough and feature complete enough for use in a production environment?

I'm using mongoose and I'm tired of all its shortcomings, but I don't want to adopt a new library that is still beta...

Any advice appreciated!

**Comment by phil294** [comment]
@lonix1 sorry the delay. Havent used it a lot, but so far, it was very good. Especially the ActiveRecord syntax feels very natural:
`let entity = new MyEntity(); entity.save()`
this is the reason I left mongoose behind where you can do the same thing, but there it's not a native class and you have no typings.
For find() queries, you are simply using the MongoDB driver. Works fine so far. The only real problem I have had so far was #3266 but maybe there is a good workaround. Joins are also not possible. In my experience however, once you actually require collection joins (which *are* possible with mongodb), you should probably be using a relational database instead :D
