### ISSUE TITLE
Type DeepPartial issue when used with generics

### ISSUE THREAD

**Issue by Hulago** [typeorm/typeorm#2904]
**Issue type:**

[ x ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ x ] `@next`
[ x ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```typescript

import {
  EntityManager,
  Transaction,
  TransactionManager,
  DeepPartial,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Connection,
  getConnection,
  getManager
} from 'typeorm';

namespace interfaces {
  export type klass<T> = { new (...args: any[]): T } | Function;
}

export class AuditedEntity {
  @PrimaryGeneratedColumn()
  id: number;

  savedBy: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}

export abstract class AbsBaseDao<E, PK = number> {
  conn: Connection;
  manager: EntityManager;
  baseEntity: interfaces.klass<E>;

  constructor(entity: interfaces.klass<E>) {
    this.conn = getConnection();
    this.manager = getManager();
    this.baseEntity = entity;
  }

  @Transaction()
  async create(entity: DeepPartial<E>, @TransactionManager() manager?: EntityManager) {
    return await manager.create(this.baseEntity, entity);
  }
}
export class TestDao<E extends AuditedEntity, PK = number> extends AbsBaseDao<E, PK> {
  async create(entity: DeepPartial<E>, @TransactionManager() manager?: EntityManager) {
    entity.createdAt = new Date();
    entity.updatedAt = new Date();
    entity.savedBy = 'SomeUSer';

    return super.create(entity);
  }
}
```
Typescript is giving me error on entity.createdAt, entity.updatedAt , entity.savedBy.

[ts] Type 'Date' is not assignable to type 'DeepPartial<E["createdAt"]>'.

But if I change the DeepPartial type from:

export declare type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]> };

to

export declare type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]> | **T[P]** };

the error disappears.

Could we change the DeepPartial type ?

Regards

Hugo

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Slessi** [comment]
I too have this issue and was able to fix it in the same way

```
Argument of type 'ChangeRequest<T>' is not assignable to parameter of type 'DeepPartial<ChangeRequest<any>>'.
  Types of property 'resolvedData' are incompatible.
    Type '{ [key: string]: unknown; } | null' is not assignable to type 'DeepPartial<{ [key: string]: unknown; }> | null | undefined'.
      Type '{ [key: string]: unknown; }' is not assignable to type 'DeepPartial<{ [key: string]: unknown; }>'
```

**Comment by vlapo** [comment]
@pleerock could you please check this?

**Comment by mdolgich** [comment]
Same issue here.

**Comment by adesege** [comment]
I am also running into the same issue

**Comment by pleerock** [comment]
Can you please check if you still have issue in typeorm@0.2.15-rc.1 ? (`npm i typeorm@0.2.15-rc.1`)

**Comment by Slessi** [comment]
@pleerock still the same for my case

**Comment by Hulago** [comment]
@pleerock I have also the same issue in  typeorm@0.2.15-rc.1, but I could fix it in my case with:

/**
 * Same as Partial<T> but goes deeper and makes Partial<T> all its properties and sub-properties.
 */
type DP<T> = {
  [P in keyof T]?: T[P] extends Array<infer U>
    ? Array<DeepPartial<U>>
    : T[P] extends ReadonlyArray<infer U>
    ? ReadonlyArray<DeepPartial<U>>
    : DeepPartial<T[P]>
};

export declare type DeepPartial<T> = { [P in keyof T]?: T[P] | DP<T> };

**Comment by derekngo** [comment]
This does not work in `typeorm@0.2.15-rc.1` for me

**Comment by robertmain** [comment]
I'm having this issue too

**Comment by AnthonyMacKinnon** [comment]
@pleerock The current definition of `DeepPartial` doesn't properly handle primitives and dates either. How about we use or mimic what is found at [ts-essentials](https://github.com/krzkaczor/ts-essentials/blob/master/lib/types.ts#L9)? It seems to solve the issue.

**Comment by duckies** [comment]
I received a similar error because of a nested interface using `unknown`.
```
Argument of type 'User' is not assignable to parameter of type 'DeepPartial<User>'.
    ...
        Type 'unknown[]' is not assignable to type 'DeepPartial<unknown>[]'.
            Type 'unknown' is not assignable to type 'DeepPartial<unknown>'
```

**Comment by vschoener** [comment]
Looks like I have the same issue trying to have an entity property be a generic and this error appear when I try to update the entity with the partial parameter

**Comment by filipdufka** [comment]
Same issue here.

**Comment by hitallow** [comment]
I have same issue when i use T generic type.
![image](https://user-images.githubusercontent.com/42446670/79291042-fa294880-7ea3-11ea-851c-59d14c1f76de.png)

**Comment by bestickley** [comment]
Same issue. I worked around by casting to any. Example: `.set({ isDeleted: true } as any)`

**Comment by martbock** [comment]
I have the same problem.
When using the repository with a generic `T extends MyClass`, objects with overlapping properties are not recognized correctly.

<img width="616" src="https://user-images.githubusercontent.com/16653872/81973814-f7e21780-9624-11ea-8e2a-3fa09986be7b.png">

<img width="963" src="https://user-images.githubusercontent.com/16653872/81973723-d123e100-9624-11ea-937f-4f0a46fa65ee.png">

**Comment by hitallow** [comment]
> Same issue. I worked around by casting to any. Example: `.set({ isDeleted: true } as any)`

It worked, but it's not the best way.

**Comment by edwinquaihoi** [comment]
Same issue :)

**Comment by thesiti92** [comment]
Will we ever get a fix for this? Allowing unknown types would be very helpful for jsonb columns in Postgres

**Comment by avifatal** [comment]
Any solution?

**Comment by Neant34** [comment]
Same issue !

**Comment by MatthiasKunnen** [comment]
I've found a solution but it would require upgrading TypeORM to TypeScript >= 3.7. 
This is the fix: <https://github.com/MatthiasKunnen/typeorm/commit/bb13f11e38c54bd4e1632e0fe0ab9e0def85965c>. 

If you are using TypeScript >= 3.7 you could override the `DeepPartial` with the code in the above commit.

**Comment by DadiAnas** [comment]
I got the same error, I was able to ignore the error by casting the variable to any.
from this.categoriesRepository.save({ ...categoriesData }); to this.categoriesRepository.save({ ...categoriesData as any });

and then I found that the reason behind this error is that I used different name for a column in entity and dto.

**Comment by anlauren** [comment]
+1 i have the same error trying to use generics.
using `as` would work but it's not quite the spirit to hardcode the types.
Is there any plan to upgrade `DeepPartial` to the above code?

**Comment by vgandzyuck** [comment]
Any updates here?

**Comment by kevinpiac** [comment]
Same issue folks!

**Comment by MatthiasKunnen** [comment]
I created a PR with the change of my [previous suggestion](https://github.com/typeorm/typeorm/issues/2904#issuecomment-675655018). It, however, introduces breaking change so it could be a while before we see this released.

**Comment by firxworx** [comment]
Ran into this one today

**Comment by nhhockeyplayer** [comment]
I think a simplification api layer needs to be introduced
cant keep clobbing stuff onto stuff when things turn brittle
im trying to override the repo now with simplified overrides
wish I could help but am pre-empted

**Comment by npc109** [comment]
same issue, pls fix this

**Comment by Distortedlogic** [comment]
this issue still exists.. bump

**Comment by iLazarus** [comment]
i am using nestjs for my project. and try make a generic service,just lolike this:
```
export class BaseService<Entity, Create, Update> {
  constructor(public readonly repository: Repository<Entity>) {}

    async save(dto: Create): Promise<Entity> {
    this.logger.log(`${this.constructor.name}.save`);
    const created = this.repository.create(dto);
    return this.repository.save(created);
  }
}
```

because of nestjs use typeorm 0.2.x version, so i run command 
```
npm i @nestjs/typeorm typeorm@0.2

````
wait 1 second, my pmtool install typeorm 0.2.45 for this project .
and I got the same trouble just lolike yours.

then i try modify version from 0.2.45 to 0.2.41,

the Trouble fixed.

so. what happens?

**Comment by mrsimb** [comment]
Issue still exists, one "unknown" type field in any entity can break type checking for entire project, and you wouldn't even know why, because typescript will give you absolutely unhelpful, giant, recursive error.

**Comment by map-strong41** [comment]
@iLazarus https://typescripter.space/questions/the-configuration-file-for-typescript-and-typeorm-specifically-the-ts-file-is-encountering-an-error
