### ISSUE TITLE
Is it possible to tell TypeORM to check if relation target exists by unique column other than PK?

### ISSUE THREAD

**Issue by Aareksio** [typeorm/typeorm#2907]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

**Question:**
Is it possible to tell TypeORM to check if relation target exists by unique column other than PK?

**Problem:**
Save data obtained from external source to normalized database.

**Example / reproduction:**
External API returns an array of users composed of their `name` and `position`, as the position is a string, we want to use artificial id to reduce storage space needed (and include some other information about it, say salary or department). Data is delivered in chunks (of one, for example simplicity).

My idea of executing such scenario is the following code, which violates unique key constraint. Is there a prefered approach to this problem?

```ts
// entity/User.ts
@Entity()
export default class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @ManyToOne(type => Position, position => position.users, { cascade: true })
  position: Position;
}

// entity/Position.ts
@Entity()
export default class Position {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ unique: true })
  name: string;

  @OneToMany(type => User, user => user.position)
  users: User[];
}

// test.ts
const externalData = [
  { name: 'Mark', positionName: 'administrator' },
  { name: 'Henry', positionName: 'administrator' } 
]

async function saveUser(name, positionName) {
  const position = new Position();
  position.name = positionName;

  const user = new User();
  user.name = name;
  user.position = position ;

  return getManager().save(user);
}

for (const { name, positionName} of externalData) {
  await saveUser(name, positionName);
}
```

_Not submitting tests, as this is technically not an issue_

**Existing solution:**
```ts
async createPosition(positionName) {
  const existingPosition = await getRepository(Position).findOne({ name: positionName });
  if (existingPosition) return existingPosition;

  const position = new Position();
  position.name = positionName;
  return position;
}

async function saveUser(name, positionName) {
  const position = await createPosition(positionName);

  // ...remaining code stays the same...
}
```

You could use [Active Record or Data Mapper patterns](http://typeorm.io/#/active-record-data-mapper) to abstract the logic:
```ts
async function saveUser(name, positionName) {
  // Using Custom Repository
  const position = await getCustomRepository(Position).findOneOrCreate({ name: positionName });

  // ...remaining code stays the same...
}
```

**Feature request, if better solution doesn't currently exist:**
Check if passed object has defined properties marked as unique, if so, search for existing record with these properties. _This may lead to bugs, as it effectively silence unique key constraint violation._

Instead, a new decorator may be added, or possibly better, an option to `@JoinColumn` allowing to specify which columns to check.

PS. This seems be the same problem as #2116, linking for discoverability

**Comment by rhogeranacleto** [comment]
This is a great feature! I kinda need it!

**Comment by Ginden** [comment]
Unfortunately, I think it's out of scope TypeORM. Custom hacks to finely tune database can be useful, but they shouldn't be a part of ORM.

My suggestion is to use custom brew cache:

```ts
const positionIdCache = {};
async function getOrCreatePosition(params) {
   if (positionCache[params]) return positionCache[params];
  const position = await repo.save(...);
  positionCache[params] = position.id;
  return params;
}
```
