### ISSUE TITLE
Allow active record entities to use find conditions

### ISSUE THREAD

**Issue by Aareksio** [typeorm/typeorm#2910]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

**Description:**
Current type declaration doesn't allow for use of FindConditions on active record entities, even though according to [BaseEntity.ts#L259](https://github.com/typeorm/typeorm/blob/master/src/repository/BaseEntity.ts#L259) the options are directly passed to [Repository.find](https://github.com/typeorm/typeorm/blob/master/src/repository/Repository.ts#L218), which clearly accepts `FindConditions`.

**Current workaround:**
```ts
ActiveRecordEntity.find(findConditions as any);
```

_Not sending PR as I'm new to typescript and don't feel confident enough to touch type related part of the codebase myself. Tagging as documentation issue as it's not a technical bug, rather an inconvenience_

**Comment by tsalpekar21** [comment]
+1 - I've been tracing down the source code for a while now and just found this issue! Wasn't sure why the FindOperator wasn't getting reduced to the right text.

**Comment by Kononnable** [comment]
Could you check if it is working as expected on @next? 
There are some big changes with find conditions.

**Comment by pleerock** [comment]
> Not sending PR as I'm new to typescript and don't feel confident enough to touch type related part of the codebase myself. Tagging as documentation issue as it's not a technical bug, rather an inconvenience

that's okay to start experimenting, we are here to check and help you with your results :)

PRs are accepted guys.

**Comment by imnotjames** [comment]
Looks like this was fixed as part of #3460
