### ISSUE TITLE
Simplify / Remove all the cli dependencies by extracting cli into typeorm-cli ?

### ISSUE THREAD

**Issue by jerolimov** [typeorm/typeorm#2913]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[x] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Adding typeorm adds some additional direct dependencies to a react-native, expo, cordova or web-only project. It works fine by importing `typeorm/browser`.

But I think the process could be simplified if this project has no direct dependencies to `path` etc.

Most of the dependencies in the package.json looks that these are only requried for the typeorm-cli. So maybe its a good idea to extract the cli tools into its own project?!

**Comment by Kononnable** [comment]
Closing this in favor of #2479 - splitting typeorm to more packages is discussed there.
