### ISSUE TITLE
Joining on a many-to-many relation gives TypeError

### ISSUE THREAD

**Issue by moazshorbagy** [typeorm/typeorm#2914]
**Issue type:**

[x] question

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `0.2.7`

**Problem**
I'm trying to implement a many-to-many relation between entity Teacher and Subject using javascript.
In the Subject entity
```
teachers: {
      target: "Teacher",
      type: "many-to-many",
      nullable: true,
      joinTable: true
    } 
```
In the Teacher entity
```
subjects: {
        target: "Subject",
	type: "many-to-many",
	nullable: true,
        inverseSide: "teachers"
    }
```
When I try:
```let teachers = await Subject.findOne(1, { relations: ["teachers"] })```
it works, but when I try:
```let subjects = await Teacher.findOne(1, { relations: ["subjects"] })```
it doesn't work with the following error:
```
TypeError: Cannot read property 'tablePath' of undefined
at /node_modules/typeorm/query-builder/SelectQueryBuilder.js:1082:73
```

**Comment by gintsgints** [comment]
@moazshorbagy could you please provide full model definitions for teachers & subjects?

**Comment by FreakTheMighty** [comment]
@moazshorbagy I bumped into the same error. I posted my solution here: https://github.com/typeorm/typeorm/issues/3148#issuecomment-466716971
