### ISSUE TITLE
.orderBy() doesn't add double-quotes around field name when not using table alias (Postgres)

### ISSUE THREAD

**Issue by doubliez** [typeorm/typeorm#2919]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

**Steps to reproduce or a small repository showing the problem:**

The following produces a query where "createdAt" is not quoted in the ORDER BY clause (therefore the query fails). However "subscriptionId" has double-quotes so why the different behavior between `.where` and `.orderBy`?

```
repository.createQueryBuilder()
    .select()
    .where({ subscriptionId: 1 })
    .orderBy({ createdAt: 'DESC' })
    .getManyAndCount()
```

However when using a table alias, it works but only if I reference the column using the table alias (which I don't need to do for `.where`):

```
repository.createQueryBuilder('mytable')
    .select()
    .where({ subscriptionId: 1 })
    .orderBy({ 'mytable.createdAt': 'DESC' })
    .getManyAndCount()
```

**Comment by gintsgints** [comment]
@doubliez could you please provide also model upon you do search?

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by Glavin001** [comment]
Experiencing the same problem when using `orderBy`:

```
column \"createdat\" does not exist
```

Discovered when I switched database system/driver from `mysql` to `postgres`.

Using `typeorm` version `0.2.18`.

## Snippet of Error object:

```
          "message": "column \"createdat\" does not exist",
          "name": "QueryFailedError",
          "length": 174,
          "severity": "ERROR",
          "code": "42703",
          "hint": "Perhaps you meant to reference the column \"problem.createdAt\".",
          "position": "446",
          "file": "parse_relation.c",
          "line": "3293",
          "routine": "errorMissingColumn",
          "query": "SELECT \"problem\".\"id\" AS \"problem_id\", \"problem\".\"createdAt\" AS \"problem_createdAt\" ... FROM \"problem\" \"problem\" WHERE \"problem\".\"userId\" IN ($1) ORDER BY createdAt DESC LIMIT 10",
          "parameters": [
```

## Fails

```typescript
      queryBuilder
        .orderBy(`createdAt`, "DESC")
        .getMany();
```

## Works

```typescript
      queryBuilder
        .orderBy(`"createdAt"`, "DESC")
        .getMany();
```

```diff
      queryBuilder
-        .orderBy(`createdAt`, "DESC")
+        .orderBy(`"createdAt"`, "DESC")
        .getMany();
```

@doubliez did you ever find a true fix?

**Comment by doubliez** [comment]
@Glavin001 I'm using the workaround I mentioned in my first post, explicitly using the table alias for the orderBy. A true fix would need to be implemented in TypeORM if this is still an issue.

Note that it's not the only case where TypeORM doesn't properly double-quote the column names. Related issue is https://github.com/typeorm/typeorm/issues/4017

**Comment by ekzyis** [comment]
Can you reopen this issue?

I am using  @nestjs/typeorm 7.1.0 with typeorm 0.2.25 and encountered following failed query after having put `{ reportCount: 'ASC'}` into `orderBy`:

```SELECT DISTINCT "distinctAlias"."reporter_id" as "ids_reporter_id", "distinctAlias".reportCount FROM (SELECT "reporter"."id" AS "reporter_id", "reporter"."first_seen" AS "reporter_first_seen", "reporter"."last_seen" AS "reporter_last_seen", "reporter"."count" AS "reporter_count", COUNT("report"."id") AS "reportCount" FROM "reporter" "reporter" INNER JOIN "report" "report" ON "report"."reporter_id"="reporter"."id" GROUP BY "reporter"."id") "distinctAlias" ORDER BY "distinctAlias".reportCount DESC, "reporter_id" ASC LIMIT 10```

It did not properly use double-quote in the ORDER BY statement like this:  "distinctAlias"."reportCount" 

It even "mocks" me with the hint given in the error message what I found quite hilarious: `hint: 'Perhaps you meant to reference the column "distinctAlias.reportCount".'`

**Comment by TrejGun** [comment]
same here

```
    "pg": "8.3.3",
    "typeorm": "0.2.26",
```

**Comment by gintsgints** [comment]
@Kononnable I managed to repeat this with test. Should be reopened.

**Comment by gintsgints** [comment]
Same problem exists for select(). Columns get escaped only when there is alias, as function ```replacePropertyNames``` does it only for strings with aliases.

I see two solutions here:

* add default alias for table
* add column name escaping specific places - or query builders or replacePropertyNames itself.

**Comment by ericmorand** [comment]
@Kononnable , can you please reopen. This is still an issue with the latest flavors of TypeORM.
