### ISSUE TITLE
Auto increment on non primary key field

### ISSUE THREAD

**Issue by nuno-morais** [typeorm/typeorm#2920]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**
[x] `0.1.21`

**Steps to reproduce or a small repository showing the problem:**
Hello,

How can we include a non primary key as field and auto increment? 

The `_id` should be ObjectIdColumn and I would like to have another property `code` as AutoIncrement (for example). 
Is it possible?

**Comment by rustamwin** [comment]
1. No. MongoDB does not support auto increment like as rdbms
2. You have to do it yourself (maybe can use `$inc` option)
