### ISSUE TITLE
BeforeInsert Issue

### ISSUE THREAD

**Issue by JamesCoonce** [typeorm/typeorm#2924]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Placing @BeforeInsert() and @AfterInsert do not work

```
@AfterInsert()
  modifyText() {
    console.log("Something is being inserted");
  }
```

```
@BeforeInsert()
  modifyText() {
    this.text = `${this.text} was modified before insert`;
  }
```

```
@BeforeInsert()
hashpassword(){
   this.password = ........
}
```

I've seen this in other issues and they were closed but the issue was never actually resolved.

**Comment by billyjov** [comment]
@JamesCoonce  `@BeforeInsert` work for me using version `0.2.7`. You have to be extra careful when working with asynchronous processes e.g your last use case for hashing a password.

It should work with the folowing syntax: 

```
@BeforeInsert
async hashpassword() {
    this.password = await your-hash-process;
}
```

**Comment by JamesCoonce** [comment]
I'm also using 0.2.7. Here is a basic example. This doesn't even work. It does no modify.
```
import { Entity, Column, PrimaryGeneratedColumn, BeforeInsert} from 'typeorm';

@Entity()
export class Todo {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ length: 500 })
  text: string;

  @Column()
  complete: boolean;

  @BeforeInsert()
  modifyText() {
    this.text = `${this.text} was modified before insert`;
  }
}
```

Inside of my todoService I have this

```
public async create(todo: CreateTodosDTO): Promise<Todo> {
        return await this.todoRepository.save(todo);
    }
```

**Comment by JamesCoonce** [comment]
When I send the post request it's 

```
{
  "text": "Today is Monday",
  "complete": false
}
```

What I get back is 

```
{
	"text": "Today is Monday",
	"complete": false,
	"id": 5
}
```

I check the database and it's the same. It's not being modified before insert.

**Comment by feather-jmalone** [comment]
i could be wrong about this, but my understanding is that because `BeforeInsert` is an instance-level method, you need an actual instance of `Todo` in order for it to be invoked (you can't reference `this.password` if there's no `this`). The object you're passing in the request is just an object that happens to have the same properties as `Todo`.

**Comment by JamesCoonce** [comment]
That works. I need to create an actual instance first.

**Comment by gintsgints** [comment]
@JamesCoonce consider closing issue then.

**Comment by belgiancoder** [comment]
I know why this works that way but it shouldn’t IMO.

**Comment by vinimdocarmo** [comment]
> That works. I need to create an actual instance first.

How can one call a validation method using repository.save passing just a plain object instead of an entity instance?

**Comment by liqwid** [comment]
> > That works. I need to create an actual instance first.
> 
> How can one call a validation method using repository.save passing just a plain object instead of an entity instance?

`Entity.prototype[methodName].apply(object, args)`

**Comment by niyodusengaclement** [comment]
You can use the create method to create an instance`const data = repository.create(yourDto)` and then save returned data `repository.save(data)`

This will solve the issue
