### ISSUE TITLE
When using base class' custom repository, the discriminator is ignored

### ISSUE THREAD

**Issue by ryuuji3** [typeorm/typeorm#2927]
**Issue type:**

[x ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a Single Table Inheritance structure; User and its child classes. At some point I am saving an instance of User's child class created with the appropriate constructor;

```ts
  static getUserInstanceFromPayload(payload: IUserPayload) {
    switch(payload.role) {
      case UserRole.ADMIN: return new Admin(); // class Admin extends User
      default: throw new Error(`Invalid role ${role}`);
    }
  }
  /* elsewhere... */
  const payload = req.payload as IUserPayload;
  const repository = em.getCustomRepository(User);
  const user = getUserInstanceFromPayload(payload);

  user.populateFromPayload(payload);

  return repository.save(user);
```

So I receive a payload object and then match the role and choose the appropriate constructor so that it should be the right kind of entity, and then populate it and save.

However, when I run this code, I receive this error:

```
Query failed: INSERT INTO "user"("id", "username", "password", "firstName", "lastName", "createdDate", "lastUpdatedDate", "role") VALUES (DEFAULT, $1, $2, $3, $4, DEFAULT, DEFAULT, $5) RETURNING "id", "createdDate", "lastUpdatedDate", "role" -- PARAMETERS: ["joe.schmoe@example.com","$2b$07$J4XESA9hrVFJPpG.Xjfo0.zv9HOB4cd3T2xLxbEI37N20Dvx11TsG","Joe","Schmoe","User"]
Error: error: invalid input value for enum user_role_enum: "User"
```

So I see that when it saves, it is somehow obtaining "User" as the discriminator value from the repository. 

My solution has been to use the EntityManager to save the entity and it works as expected. So it's not like it's impossible to do what I want.

```ts
return em.save(user); // works as expected
```

Additional info:

```ts
enum UserRole {
  ADMIN = "ADMIN",
  // etc...
}
```
My User entity:
```ts
@Entity()
@TableInheritance({
  column: {
    name: "role",
    type: "enum",
    enum: UserRole,
    default: UserRole.BASIC_USER
  }
})
export abstract class User {
  @Expose()
  protected role: UserRole;
}
```

And the admin:
```ts
@ChildEntity(UserRole.ADMIN)
export class Admin extends User {

  constructor() {
    super();

    this.role = UserRole.ADMIN; // this is only here so that unit tests work
  }
}
```

**Comment by ggarcia92** [comment]
I have this problem too. Can someone give some info about it? Thanks

**Comment by ryuuji3** [comment]
Closing because this hasn't had any response.

**Comment by pekunicki** [comment]
This issue still occurs, so would be worth resolving it.

**Comment by bombillazo** [comment]
Still an existing issue.

**Comment by Distortedlogic** [comment]
Still an existing issue

**Comment by bombillazo** [comment]
@Distortedlogic Nope, still an issue in v0.3.9

**Comment by Distortedlogic** [comment]
@bombillazo seems it was supposed to be fixed in like v0.3.5

![06-09-2022-11-03-44](https://user-images.githubusercontent.com/54854447/188669739-d0fa8c45-fe18-4db1-b418-45788c17daf8.png)

https://github.com/typeorm/typeorm/pull/8819

**Comment by bombillazo** [comment]
My bad! You are correct, I had fixed it, I was missing the discriminator type as the parameter of the decorator! Sorry for the confusion.  😖

**Comment by darrenrahnemoon** [comment]
This issue is still happening in `0.3.16`.
