### ISSUE TITLE
required properties produce a typescript error

### ISSUE THREAD

**Issue by P4sca1** [typeorm/typeorm#2936]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
import { Entity, BaseEntity, PrimaryGeneratedColumn } from "typeorm"

@Entity()
class MyClass extends BaseEntity {
    @PrimaryGeneratedColumn()
    public id: number
}
```

Typescript complains about the above code because id is not optional but is missing an initializer and is not definetely typed in the constructor.

Of course using `public id?: number` fixes the issue but that would lead to typescript being annoying about `id` being potentially undefined.

https://github.com/szokodiakos/typegoose which uses props in a similar way has the same problem:
https://github.com/szokodiakos/typegoose/issues/210

**Comment by P4sca1** [comment]
I was able to fix this issue by creating a new `tscsonfig` file in my `entities` folder, which includes `"strictPropertyInitialization": false`.

**Comment by tim-smart** [comment]
Probably the more correct way around this is using the `!` operator.

```typescript
import { Entity, BaseEntity, PrimaryGeneratedColumn } from "typeorm"

@Entity()
class MyClass extends BaseEntity {
    @PrimaryGeneratedColumn()
    public id!: number
}

**Comment by P4sca1** [comment]
@tim-smart Looks way better than my approach, will give it a try.

**Comment by IgorGee** [comment]
FYI, #2797 contains discussions around this.
