### ISSUE TITLE
DECIMAL(13, 2) column is converted back to string instead of number

### ISSUE THREAD

**Issue by c-kle** [typeorm/typeorm#2937]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

Hello everyone !

I am well aware that this issue has already been addressed and I tried what's suggested here #2745 but it doesn't seem to work for me ...
so I have an entity OrderItemEntity
```
@Entity('orders')
export default class OrderEntity extends AEntity {
  @Column({ type: Boolean })
  open: boolean;

  @Column({ type: 'decimal', precision: 13, scale: 2 })
  balance: number;

  @OneToMany(() => OrderItemEntity, (item) => item.order)
  items: OrderItemEntity[];
}

```
and I get the entities through this class

```
class OrdersRepository implements IOrdersRepository {

...

  public getAll(): Promise<OrderEntity[]> {
    return this.repository
      .find({ relations: ['items', 'items.product', 'items.options', 'items.options.product'] });
    }
}
```

By setting bigNumberStrings to false and supportBigNumbers to true I would expect to have balance as number but I get a string instead.

**Comment by Kononnable** [comment]
If you do that just by using underlying driver do you get result types you want? If not it might be db driver related, not typeorm.

**Comment by c-kle** [comment]
Yep you're right, this is caused by mysql2..
I tried using a transformer to get a number but I'm still having a string back though :o

**Comment by Kononnable** [comment]
Here is transformer [example](https://github.com/typeorm/typeorm/blob/master/test/functional/columns/value-transformer/entity/PhoneBook.ts). However you would have to use it one every column you want to use that way. Probably better to check how mysql2 should be configured or if it is a bug that can be fixed.

**Comment by Kononnable** [comment]
@Mordred 
https://github.com/brianc/node-postgres/issues/811

**Comment by Mordred** [comment]
@Kononnable Thanks.

It would be nice to add this to FAQ page. Maybe with transformer example?

**Comment by Kononnable** [comment]
Contributions to docs are always welcomed :smile:

**Comment by germansokolov13** [comment]
Why do you expect `decimal` to not be a `string`? JavaScript's numeric type is a floating point number. It's imprecise and does not fit well to hold a `decimal` value, especially if it's money. Js does not have a true decimal type.

**Comment by xtance** [comment]
So how to fix it?
BigInt bug can be fixed with "bigNumberStrings: false"... is there "numberStrings: false"? 

As of now I can have a "float" value by making it a property of a JSON object... Not so nice of a fix
