### ISSUE TITLE
Cannot select child entity properties

### ISSUE THREAD

**Issue by itslenny** [typeorm/typeorm#2940]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ x ] `postgres`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**Entity Setup**

```
// entity
@Entity('menu_item_size')
export class MenuItemSizeEntity extends BaseEntity {

  @Column(type => CurrencySubentity)
  public price: CurrencySubentity;

}

// child entity
export class CurrencySubentity {

  @Column({ type: 'bigint' })
  currencyAmount: number;

  @Column({
    type: 'bigint',
    default: 100,
  })
  currencyFraction?: number;

  @Column({
    type: 'varchar',
    length: 3,
    default: 'USD',
  })
  currencyCode?: string;

}
```

**Query**

```
this.menuItemSizeRepository.findOne(menuItemSizeId, { select: ['price'] });
```

**Result**

```
Error: price column was not found in the MenuItemSizeEntity entity.
    at .../find-options/FindOptionsUtils.ts:93:27
```

I also tried `select: ['priceCurrencyvalue']` which is the actual table column name, but that gives me a type error because it doesn't exist in the entity. I can do `select: <any>['priceCurrencyvalue']` to make it run, but I get the same error as above just with "priceCurrencyvalue" as the column that cannot be found.

**Comment by Kononnable** [comment]
Closing as no response from the author.
