### ISSUE TITLE
Sqlite vacuum?

### ISSUE THREAD

**Issue by p3v9d5ui** [typeorm/typeorm#2942]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi Everyone, 

I'm using Typeorm with a Cordova iOS app and the Sqlite database. I've noticed that my db size continues to grow, even after deleting all records. I assume this is because the Sqlite "vacuum" operation is not being executed. Is there a way to do this with Typeorm?

**Comment by Kononnable** [comment]
Can you check if you can do it by executing in from the raw query and does it works the way you've expected? Raw query can by executed e.g. on Repository/Entity Manager by `.query('')`

**Comment by p3v9d5ui** [comment]
I've just tried this. The query seems to execute without any errors, but the size of the database file did not change. The vacuum query also returns essentially instantaneously, which makes me think it's not doing anything.

**Comment by Kononnable** [comment]
You should then check disk usage per table to see if maybe something else is taking this storage. If not there may be some bugs within cordova sqlite itself. Right now it doesn't look like typeorm related(but who knows).

**Comment by imnotjames** [comment]
Given that this is likely not typeorm related & we've not had any other activity I'm gonna close this out.  If the vacuum is being called but isn't doing anything I'd definitely be looking at cordova suspiciously.

However, if you have a way to replicate the issue please feel free to open another issue with that information.
