### ISSUE TITLE
Inappropriate migration generated

### ISSUE THREAD

**Issue by btxtiger** [typeorm/typeorm#2943]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest` 0.2.7
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When using an `unsigned` **PrimaryGenerateColumn**, and generating a migration using `typeorm migration:generate`, the generated migrations get into a loop. The generated migration is always the same, because the query leads to an undocumented change in the database, which causes migration:generate to detect the change again and again.

Reproduction:
```ts
import { Entity, PrimaryGeneratedColumn, Column, PrimaryColumn, Generated } from 'typeorm';

/**
 * Log action
 */
@Entity('log_action')
export class LogAction {
   /**
    * logActionId
    */
   @PrimaryGeneratedColumn({
      name: 'log_action_id',
      unsigned: true
   })
   public logActionId: number;

   /**
    * title
    */
   @Column('varchar', {
      nullable: false,
      length: 150,
      name: 'title'
   })
   public title: string;
   /**
    * created
    */
   @Column('datetime', {
      nullable: false,
      default: () => 'CURRENT_TIMESTAMP',
      name: 'created'
   })
   public created: Date;

   /**
    * last_modified
    */
   @Column('datetime', {
      nullable: false,
      default: () => 'CURRENT_TIMESTAMP',
      onUpdate: 'CURRENT_TIMESTAMP',
      name: 'last_modified'
   })
   public lastModified: Date;
}
```

- **Create table**
`ts-node ./node_modules/.bin/typeorm schema:sync`
- **Create migration**
`ts-node ./node_modules/.bin/typeorm migration:generate -n test`

You can run `migration:generate` and `migration:run` multiple times, there will always be this migration generated, again and again.
```ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class test1539781487192 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `log_action` CHANGE `log_action_id` `log_action_id` int UNSIGNED NOT NULL AUTO_INCREMENT");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `log_action` CHANGE `log_action_id` `log_action_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT");
    }

}
```

At this point, it seems to be an issue of not defining a precision, but even adding `precision: 10` to **PrimaryGeneratedColumn** config doesn't solve it. It produces the following migration:
```ts
import { MigrationInterface, QueryRunner } from 'typeorm';

export class test1539782429566 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
      await queryRunner.query('ALTER TABLE `log_action` CHANGE `log_action_id` `log_action_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
      await queryRunner.query('ALTER TABLE `log_action` CHANGE `log_action_id` `log_action_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT');
   }

}


```

**Comment by btxtiger** [comment]
Having the same issue now for non _PrimaryGenerateColumn_ cols.
```ts
/**
 * stateRef
 */
@Column({ unique: true, unsigned: true, nullable: true })
public stateRef: number;
```
**No pending migrations, but migration generator generates:**
```ts
export class testmigration1554311517855 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `user` CHANGE `state_ref` `state_ref` int UNSIGNED NULL");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `user` CHANGE `state_ref` `state_ref` int(10) UNSIGNED NULL");
    }

}
```

Seems to be something between `int` and `int(10)`, which is the value from the DB.

**Comment by oeed** [comment]
Have the exact same issue... anyone know of a fix/work around?

**Comment by danielsantiago** [comment]
Having the same problem

**Comment by timothyvanderaerden** [comment]
Specifying the width solved it for me.

```javascript
/**
 * stateRef
 */
@Column({ unique: true, unsigned: true, nullable: true, width: 10 })
public stateRef: number;
```

If you want to set it on a primary generated column you can do it like:
```javascript
@PrimaryColumn({ type: 'int', width: 10, unsigned: true })
@Generated()
public id: number;
```

**Comment by btxtiger** [comment]
> Specifying the width solved it for me.

This worked for me too

**Comment by lookapanda** [comment]
Why is this still open? This workaround is not a solution for this issue, it only adds more unnecessary work.

**Comment by twigs67** [comment]
Where in the documentation does it say how TO CREATE A COLUMN AND MAKE THE DEFAULT NULL?!?!?!!?

**Comment by btxtiger** [comment]
@twigs67 is this relevant for this issue?
As shown in my [example](https://github.com/typeorm/typeorm/issues/2943#issue-371088900) `default: () => 'NULL'`
```ts
   /**
    * created
    */
   @Column('datetime', {
      nullable: false,
      default: () => 'CURRENT_TIMESTAMP',
      name: 'created'
   })
   public created: Date;
```

**Comment by twigs67** [comment]
@btxtiger it is not. Apologies. I was a having a few beverages while trying to fix what I thought would be really easy - it was not.

I didn't even ask the right question. I was looking for documentation on making a column nullable within migrations. I never found it, so I ended up creating a raw query like so, ` await queryRunner.query('ALTER TABLE someTable ADD COLUMN someColumn VARCHAR(255) DEFAULT NULL;');`.

**Comment by michaelbromley** [comment]
Here's the root cause of this issue:

When no `width` is specified for a numeric type, this hash is consulted to figure out what the default width should be:

https://github.com/typeorm/typeorm/blob/d1ed5723bb55d4124be13b21e57d9f729d0bae1a/src/driver/mysql/MysqlDriver.ts#L261-L288

For example, with an `int` type, the width is given as `11`. Why?

> The number for each type of integer by default is same as the number of characters in the largest negative value of that type. The largest negative value for an integer is -2147483648 which is 11 characters and hence the default display width is 11
source: https://www.virendrachandak.com/techtalk/mysql-int11-what-does-it-means

**However** the default width of an _unsigned_ int is `10`. So when TypeORM encounters a numeric type with no explicit `width`, it will try to infer the value from the hash above:

https://github.com/typeorm/typeorm/blob/d1ed5723bb55d4124be13b21e57d9f729d0bae1a/src/driver/mysql/MysqlQueryRunner.ts#L1301

And will arrive at `11`, whereas in MySQL the data type will be `INT(10)` (since it is unsigned).
