### ISSUE TITLE
How to create many-to-many relations for three entities ?

### ISSUE THREAD

**Issue by OLDIN** [typeorm/typeorm#2948]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How to create many-to-many relations for three entities ?

I need this kind of schema.
[http://prntscr.com/l7k1gp](url)
And I want to know whether it is possible to automatically generate a table to join 3 tables?
Or do me need to create a separate entity that will integrate all 3 tables?

**Comment by Kononnable** [comment]
You need to create a separate entity.

**Comment by OLDIN** [comment]
@vlapo, yes.
