### ISSUE TITLE
Optimistic concurrency check

### ISSUE THREAD

**Issue by adrianhara** [typeorm/typeorm#2949]
**Issue type:**
[x] question

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[ ] `0.2.8-rc1` (or put your version here)

I'm trying to understand how to implement optimistic concurrency using typeorm. What I'm trying to achieve is what other ORMs (e.g. hibernate, ef) offer, namely that when doing an UPDATE on an entity it will check some version column and if it's different it will let me know (throw error, return code whatever).

As far as I know other ORMs allow you to designate a version field/column and when doing an update will add a `WHERE <version_column> = <value_from_entity_version_column>` and if the result of the UPDATE returns no affected rows it's deemed an optimistic concurrency error and they notify you.

I've been searching through the docs, issues and unit tests for typeorm and I haven't found such an implementation. I found some older issues saying that optimistic concurrency is supported when using @UpdateDateColumn (which I do) but no concrete example. Trying it out generated a query without the additional WHERE clause for the update date column. What I found instead is some possibility to `setLock` when doing a query using the query builder and looking through the source code it seems to be the only place where it's used. This seems to check the value in the version column (e.g. UpdateDateColumn) when reading the value out of the database, but I haven't found any code which checks it (like the above mentioned `WHERE` clause addition) when actually doing the UPDATE. It seems strange to me that the value is checked when reading data because it could happen that between moment A when I read the data and the version is still ok and moment B when I'll do the UPDATE that version could change in the DB. Can anyone explain what I'm missing?

I tried doing this
```
  const updateResult = await repository.createQueryBuilder()
                .setLock('optimistic', entity.updateDateTime.toDate())
                .where('id = :id', {id: entity.id})
                .update()
                .set(fieldsToUpdate)
                .execute();
```
This will generate an UPDATE but without any `WHERE <version_column> = <value_from_entity_version_column>` so basically it will blindly try to update the entity in the DB.

Related question. Since I couldn't find a way to make it work OOTB, I thought of doing it myself:
```
  const updateResult = await repository.createQueryBuilder()
                .where('id = :id AND updateDateTime = :updateDateTime', {id: entity.id, updateDateTime: entity.updateDateTime.toDate()})
                .update()
                .set(fieldsToUpdate)
                .execute();
```
This though generates a query where value of the `updateDateTime` parameter is `2018-10-18T15:19:28.325Z` while in the DB the value is `2018-10-18 15:19:28.325113` (note 113 instead of Z at the end) which will cause the WHERE to fail and the UPDATE to not update anything. If I manually run the generated query but change `Z` to `113` so that the `updateDateTime` matches the one in the DB then the UPDATE works. Any idea how I can fix this?

Thanks!

**Comment by adrianhara** [comment]
Hmm I think I found the answer to my second question: Postgres has 6 digit millisecond accuracy whereas JS only 3. So I need to migrate my UpdateDateColumns to `timestamp(3)` and then my query works. This brings two new questions to my mind:
- why not have `timestamp(3)` by default in postgresql migration generated code?
- even though my UPDATE query works, the `updateResult` doesn't contain any information like the updated number of rows so I can detect the optimistic concurrency conflict (or lack thereof) myself; is there any way to get the actual number of rows affected?

**Comment by adrianhara** [comment]
Any input from the devs on this?

**Comment by adrianhara** [comment]
Nobody?

**Comment by adrianhara** [comment]
It would be really great to get some feedback about the design decisions behind the existing code...

**Comment by adrianhara** [comment]
Still no feedback :(

**Comment by pleerock** [comment]
@adrianhara thanks for the patience! Did you check [those tests](https://github.com/typeorm/typeorm/blob/master/test/functional/query-builder/locking/query-builder-locking.ts) as examples of locking?

**Comment by adrianhara** [comment]
I did. They seem to "lock" on GET which i wrote above seems to me is an incorrect approach as between the time you GET and the time you UPDATE something back the record in the DB might have been changed. I think it should check on UPDATE, i.e. enforce optimistic concurrency at the DB level as it's the only reliable one. Does this make sense?

**Comment by pleerock** [comment]
I'll need to remember how it all worked and why we did so. I'll return back to it once I'll have more time.

**Comment by nicomouss** [comment]
Check #3608 for an implementation of Optimistic Concurrency using an incremented version number.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by johnlister** [comment]
> I'll need to remember how it all worked and why we did so. I'll return back to it once I'll have more time.

@pleerock don't suppose you remembered the reasoning for putting the optimistic lock on the GET and not the UPDATE? Other than it is probably slightly simpler?
