### ISSUE TITLE
Typeorm Error: Relation with property path Table2 in entity was not found.

### ISSUE THREAD

**Issue by arpitadas09** [typeorm/typeorm#2950]
Error: Relation with property path People in entity was not found.

Below is my query.I am trying to get center details selecting two tables(centers and People)

 getCenterDetail(centerId: number) {
const centerDetailQuery = getManager();
        return getManager()
        .getRepository(Centers)
        .createQueryBuilder('centersrow')
        .select(['centersrow.id', 'centersrow.name', 'centersrow.url',
        'centersrow.description'])
        .addSelect('People.personofficialname', 'directorName')
        .leftJoinAndSelect('centersrow.Peoples', 'People')
        .where('centersrow.id = :id', { id: centerId } )
        .andWhere('Peoples.uid = centersrow.directorUid')
        .getOne();

can someone help me with this? Ask me, if any further information required.

_Originally posted by @arpitadas09 in https://github.com/typeorm/typeorm/issues/869#issuecomment-431464073_

**Comment by arpitadas09** [comment]
import { Entity, Column, PrimaryGeneratedColumn, BaseEntity, ManyToMany, OneToOne, JoinTable, JoinColumn, OneToMany } from 'typeorm';
import { Table2 } from './table2.entity';

@Entity()
export class Table1 extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column('varchar', { length: 255 })
    name: string;

    @Column('varchar', { length: 255 })
    url: string;

    @Column('varchar', { length: 15 })
    phone: string;

    @Column('varchar', { length: 15 })
    fax: string;

    @Column('varchar', { length: 255 })
    email: string;

    @Column('mediumtext')
    address: string;

    @Column('mediumtext')
    description: string;

    @Column('date')
    establishDate: Date;

    @Column('varchar', { length: 255 })
    authorizingDocument: string;

    @Column('tinyint')
    core: boolean;

    @Column('int')
    typeId: number;

    @Column('int')
    statusId: number;

    @Column('int')
    categoryId: number;

    @Column('varchar', { length: 64 })
    directorUid: string;

}

export default Table1;

==============================================================

import { Entity, Column, PrimaryGeneratedColumn, BaseEntity, ManyToMany,
        OneToOne, OneToMany, ManyToOne, JoinColumn, JoinTable} from 'typeorm';
import { Table1} from './table1.entity';

@Entity()
export class Table2 extends BaseEntity {

    @PrimaryGeneratedColumn()
    uin: string;

    @Column('varchar', { length: 255 })
    netid: string;

    @Column('char', { length: 32 })
    uid: string;

    @Column('varchar', { length: 255 })
    sn: string;

    @Column('mediumtext')
    givenname: string;

    @Column('mediumtext')
    displayname: string;

    @Column('varchar', { length: 256 })
    personofficialname: string;

    @Column('varchar', { length: 256 })
    mail: string;

    @Column('mediumtext')
    postaladdress: string;

    @Column('varchar', { length: 256 })
    mailstop: Date;

    @Column('mediumtext')
    localityname: string;

    @Column('mediumtext')
    stateorprovincename: string;

    @Column('varchar', { length: 40 })
    postalcode: number;

    @Column('varchar', { length: 32 })
    telephonenumber: string;

    @Column('mediumtext')
    cn: string;

    @Column('mediumtext')
    title: string;

    @Column('varchar', { length: 256 })
    departmentname: string;

    @Column('varchar', { length: 256 })
    personprimarymembername: string;

    @Column('varchar', { length: 256 })
    personaffiliation: string;

    @Column('datetime')
    overridedate: DateTimeFormat;

    @Column('tinyint')
    mqs: boolean;

    @Column('datetime')
    createdAt: DateTimeFormat;

    @Column('datetime')
    updatedAt: DateTimeFormat;

    @Column('datetime')
    deletedAt: DateTimeFormat;
}

export default Table 2;


Query:
```
  getTable1Detail(table1Id: number) {

    return getManager()
    .getRepository(Table1)
    .createQueryBuilder('table1row')
    .select(['table1row'.id', 'table1row'.name', 'table1row'.url',
    'table1row'.description'])
    .addSelect('table2row'.personofficialname', 'table2row'.uid')
    .leftJoinAndSelect(Table2, 'table2row', 'table2row'.uid = table1row.directorUid')
    .where(table1row.id = :id', { id: table1Id } )
    .getOne();
```

I am trying to select table 1 columns(id, name,url,description,directorUid) and from table2(personofficialname, uid) and both are matching on condition directorUid= uid.
Now with the above query, I could only get the table1 details.

I hope this is making sense now, This is my first time asking question on this platform.so let me know,if I have not formatted the question correctly.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
