### ISSUE TITLE
Add support for AWS Redshift and Google BigQuery

### ISSUE THREAD

**Issue by sandangel** [typeorm/typeorm#2951]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there any plan for adding support for Redshift and BigQuery and How much work do you think it would take?

I love to use typeorm to rewrite the current API app because currently, it's the only one ORM library that is written in typescript, but the problem is I need to use AWS Redshift for BI.

**Comment by sandangel** [comment]
@pleerock 	but as I'm aware of there is also support for mongodb right? Assume that Redshift is a fork of posgresql, is that it makes more sense for adding support for Redshift rather than mongodb?

**Comment by Kononnable** [comment]
The difference is that there already is support for mongodb. So there is no more time needed to make it work. Mongodb is mostly maintained/developed by the community right now - because lack of time.

**Comment by annymosse** [comment]
@sandangel i think mongoDB not a relational database ,however google Bigquery also sql like queries , i think it's not hard to maintain it .

**Comment by samirspatel** [comment]
@Kononnable why did you close this issue? If there is no time I'm sure other developers with interest could take this work on. We are also in need of TypeORM working with BigQuery. BigQuery is a fully relational database and will definitely work with an ORM. Please reopen this issue.

**Comment by ciekawy** [comment]
any chances for reopening? and/or possibly some community discussion

**Comment by chetanbillore-hitachi** [comment]
So finally there is no support of AWS Redshift in typeORM??
Please some confirmation either way Yes/No.

**Comment by bauti-defi** [comment]
BigQuery support would be great!
