### ISSUE TITLE
Mongodb Raw Spatial query

### ISSUE THREAD

**Issue by mabuonomo** [typeorm/typeorm#2953]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I want use this query with typeorm
`{ location:
   { $geoWithin:
      { $centerSphere: [ [ -73.93414657, 40.82302903 ], 5 / 3963.2 ] } } })
`

What is the correct type for location field? I have tried GeoJson.Point, but it is incorrect
`@ColumnORM("point")
location: Point;
`

Types of property 'location' are incompatible.
Type '{ $geoWithin: { $centerSphere: (number | number[])[]; }; }' is not assignable to type 'Point'.
Property 'type' is missing in type '{ $geoWithin: { $centerSphere: (number | number[])[]; }; }'.

**Comment by rustamwin** [comment]
@mabuonomo You can use `cursor` for not implemented find options
