### ISSUE TITLE
ManyToMany relation using incorrect table name

### ISSUE THREAD

**Issue by martis347** [typeorm/typeorm#2954]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I've been breaking my head around this for hours and cannot seem to find a solution to make it work.
I have a simple relation, many-to-many (Author has many books, book can belong to many authors).

**Tables:**

|  book        |   |
| ------------- |:------:|
| id       | status |

|  author|   |
| ------------- |:------:|
| id       | full_name|

|  author_books|   |
| ------------- |:------:|
| author_id| book_id|

For now I'm trying to at least set-up a unidirectional relation:

Book.ts:
```ts
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class Book {

    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    public status: number;
}
```
Author.ts:
```ts
import { Column, Entity, PrimaryGeneratedColumn, ManyToMany, JoinTable } from 'typeorm';

import { Book } from './Book';

@Entity()
export class Author {

    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    public full_name: string;

    @ManyToMany(type => Book)
    @JoinTable()
    public books: Book[];
}
```

index.ts:
```ts
    const book = new Book();
    book.status = 1;
    await connection.manager.save(book);

    const author = new Author();
    author.full_name = "Test";
    author.books = [book];

    await connection.manager.save(author);
```

The error I'm getting is: _QueryFailedError: relation "author_books_book" does not exist_

It seems, that this set-up is making an incorrect table name.

**Comment by rafalpetryka** [comment]
I think, that you should add migration with that table (author_books_book)

**Comment by vlapo** [comment]
I am sorry for really late response on this issue. But I do not see any problem in your example. Do you have enabled synchronization? Could you please test this issue on latest version of typeorm?

**Comment by AlexMesser** [comment]
closed as staled
