### ISSUE TITLE
Getting UpdateQueryResult when executing raw query

### ISSUE THREAD

**Issue by tonyxiao** [typeorm/typeorm#2958]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When using the UpdateQueryBuilder, it is possible to get the raw count of objects updated. However when using raw `connection.query` it doesn't appear to be possible. Is that intended?

**Comment by imnotjames** [comment]
`UpdateQueryBuilder`, on `execute`, returns an `updateResult` with affected rows.  Not all drivers support this but postgres should.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
