### ISSUE TITLE
Expose EntityNotFound exception

### ISSUE THREAD

**Issue by Rockson** [typeorm/typeorm#2960]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[X] `latest`

**Steps to reproduce or a small repository showing the problem:**

I need to check the instanceof the exception thrown:
```ts
if(exception instanceof EntityNotFound) {
// do something
}
```

**Comment by Kononnable** [comment]
Could you elaborate on what exactly you want to do/why do you need it?

**Comment by Rockson** [comment]
I'm using an exception filter from nestjs and I need to map the EntityNotFoundError to HttpNotFoundException. If the typeorm error is not exposed I have to do something like: error.constructor.name === "EntityNotFoundError". But it would be nice to make use of the instance of operator

**Comment by Kononnable** [comment]
It's not exported from the global scope, but you should still be able to access it by:
```typescript
import { EntityNotFoundError } from 'typeorm/error/EntityNotFoundError'
```

**Comment by Rockson** [comment]
Oh ok I couldn't find it through autoimport. It would be useful to have it in the global scope anyway. Thank you

**Comment by pleerock** [comment]
Right now I still didn't decide with how should we design exception errors. In JavaScript extending Error is really weird so Im really curios if we should do that just like we are used to in other languages.

**Comment by robertmain** [comment]
Yes, you should. Take a look at how @nestjs did it

**Comment by takayukioda** [comment]
Glad to find this issue before I make new one :)

I felt it a bit weird that function is exposed to global but not its exception.
Since there is a workaround to get the type, (thanks @Kononnable!) I wouldn't push hard though.

**Comment by jalooc** [comment]
I still would love to see the error classes importable through the _main_ package (that is not by a path inside a package). The `typeorm/error/EntityNotFoundError` path is not the documented way to import the error (there's not documented way whatsoever), so it has to be considered internal implementation. And that means, it's not subject to semver and therefore prone to unexpected changes.

**Comment by bogdan** [comment]
calling `if(exception instanceof EntityNotFound) {` has a benefit in typescript comparing to any other check because typescript will check strict typing inside of that condition without the necessaty to typecast manually.

I think the following construction should be a mainstream in exception handing in typescript at least:

``` typescript
try {
 ...
} catch (error) {
  if (error instanceof X) {
    
  } else if (error instanceof Y)
 } else {
  throw error
}
}
```

So I would export all error on top level from `typeorm`.

**Comment by DanielLoyAugmedix** [comment]
Since error handeling

**Comment by LeandroDoldan** [comment]
Hey guys, any news here? I'm in exactly the same situation.

**Comment by blabute** [comment]
> It's not exported from the global scope, but you should still be able to access it by:
> 
> ```ts
> import { EntityNotFoundError } from 'typeorm/error/EntityNotFoundError'
> ```

Hey @LeandroDoldan, @Kononnable mentioned it can be imported using the above code.

**Comment by vegerot** [comment]
Thanks @Kononnable for the help!

My question: Why is `QueryFailedError` exported from TypeORM but `EntityNotFoundError` is not?  Shouldn't they both be exported from `typeorm/error`

**Comment by doing-art** [comment]
To handle Typeform level exceptions with NestJs you can use the interception mechanism. The main idea is to override some DB exceptions with HTTP ones. An example can be found in [the nest documentation](https://docs.nestjs.com/interceptors#exception-mapping). And there is an instruction [how to bind interceptor](https://docs.nestjs.com/interceptors#binding-interceptors). Finally, below you can see my implementation which potentially can override any kind of exceptions:
`
import {
  CallHandler,
  ExecutionContext,
  Injectable,
  NestInterceptor,
  NotFoundException,
} from '@nestjs/common';
import { Observable } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { EntityNotFoundError } from 'typeorm/error/EntityNotFoundError';

const errorOverridingStrategy = [
  {
    initial: EntityNotFoundError,
    target: NotFoundException,
  },
  // To support additional types of exceptions just add them to this mapping
];

@Injectable()
export class ErrorsInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    return next.handle().pipe(
      catchError((error) => {
        errorOverridingStrategy.forEach(({ initial, target }) => {
          if (error instanceof initial) {
            throw new target(error.message);
          }
        });
        throw error;
      }),
    );
  }
}
`
