### ISSUE TITLE
Expose underlying `pg` pool for raw operations

### ISSUE THREAD

**Issue by maomaobug** [typeorm/typeorm#2972]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

I like typeorm a lot, it can help to complete common tasks efficiently. But when I want to make use of some advanced operations such as using explicit locks on tables & rows, I have to resort to `pg` api. I think use two separate connection pools for these different types of operation is not a good idea, so can you expose the underlying connection pool to share use with app developers? Thanks very much!

**Comment by JorritPosthuma** [comment]
What if you do something like this?

```typescript
const connection = createConnection(options);
if (connection.driver instanceof PostgresDriver) {
    const pool = connection.driver.master as Pool;
}
```

**Comment by umarrasydan** [comment]
For those scratching their head on how to import `PostgresDriver`
```typescript
import { PostgresDriver } from 'typeorm/driver/postgres/PostgresDriver';
```
