### ISSUE TITLE
readme wrong cli migration instead migrations

### ISSUE THREAD

**Issue by webmobiles** [typeorm/typeorm#2979]
**Issue type:**

[x ] documentation issue

on this link:
https://github.com/typeorm/typeorm/blob/master/docs/migrations.md

the migraton command is wrong:
typeorm migration:create -n PostRefactoring

the right is migration"s":
typeorm migrations:create -n PostRefactoring

**Comment by timothyvanderaerden** [comment]
As far as I know the command isn't wrong. It should be like in the documentations.
```
typeorm migration:create -n PostRefactoring
```

**Comment by webmobiles** [comment]
give me error, without the s on migrations,

help me give:

 migrations:create    Creates a new migration file.
  migrations:generate  Generates a new migration file with sql needs to be
                       executed to update schema.
  migrations:run       Runs all pending migrations.

so the anothers lines on the readme are wrong too?

**Comment by timothyvanderaerden** [comment]
Which version are you using?

**Comment by webmobiles** [comment]
0.1.21

**Comment by timothyvanderaerden** [comment]
Ok, that makes sense, since version 0.2 the command changes from `migrations` to `migration`.

You can look at the documentation for older releases:

https://github.com/typeorm/typeorm/blob/0.1.19/docs/using-cli.md

**Comment by webmobiles** [comment]
oh sorry,  apart from commands, to migrate last version there is a doc? or simple i update the package?

**Comment by timothyvanderaerden** [comment]
Updating from 0.1 to 0.2 has some breaking changes. The best place to look is in the changelog.

https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md#020

**Comment by havenchyk** [comment]
I tried to make it a little bit more clear with https://github.com/typeorm/typeorm/pull/3220
