### ISSUE TITLE
[Question] Automatically upsert entities with compound primary keys?

### ISSUE THREAD

**Issue by marshall007** [typeorm/typeorm#2982]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I've read through all the issues and discussions I could find related to this (namely #1463, #1926, and #2027). That said, I'm still not sure whether we should expect the `EntityManager.save(...)` API to automatically `UPDATE` existing entities based on their compound primary key.

If this is expected to work I can update this issue with a reproducible test case, but I just wanted to clarify the expected behavior first.

**Comment by kyle-mccarthy** [comment]
I am having this issue as well.  I would expect that it should perform and update if the record exists rather than trying to reinsert it based on the documentation, especially since that is the functionality when there is a single primary key vs a composite primary key.  To give a concrete example this will not work

```
@Entity()
export class Region {
  @PrimaryColumn()
  public id: string;

  @Column()
  public name: string;

  @OneToMany(type => Location, location => location.region)
  @JoinColumn([
    { referencedColumnName: 'regionId', name: 'id' },
    { referencedColumnName: 'regionSyncId', name: 'syncId' },
  ])
  public locations: Location[];

  @ManyToOne(type => Sync)
  public sync: Sync;

  @Index()
  @PrimaryColumn()
  public syncId: number;
}

@Entity()
export class Location {
  @PrimaryColumn()
  public id: string;

  // ...

  @ManyToOne(type => Region, region => region.locations)
  @JoinColumn([
    { referencedColumnName: 'id', name: 'regionId' },
    { referencedColumnName: 'syncId', name: 'regionSyncId' },
  ])
  public region: Region;

  @Index()
  @Column({ nullable: true })
  @RelationId((location: Location) => location.region)
  public regionId: string;

  @ManyToOne(type => Sync)
  public sync: Sync;

  @PrimaryColumn()
  public syncId: number;
}

// ...

const sync = new Sync();
await connection.manager.save(sync);

const location = new Location();
location.id = 'l-pk-1';
location.sync = sync;
await connection.manager.save(sync);

const region = new Region();
region.id = 'r-1';
region.name = 'First region';
region.sync = sync;
await connection.manager.save(region);

// next save will cause an error because it tries to insert rather than update
location.region = region;
await connection.manager.save(location);
```

**Comment by imnotjames** [comment]
Quite a lot of work has been done since then on composite primary key entities - if you still have issues with the latest release, please open a new issue with a means to replicate the problem :)
