### ISSUE TITLE
cache:clear command doesn't exit if cache is not enabled

### ISSUE THREAD

**Issue by kyvour** [typeorm/typeorm#2988]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.8` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1) Disable cache in the configuration file
2) Run command `npm run typeorm cache:clear`

**Current result:**
The command print message (`Cache is not enabled. To use cache enable it in connection configuration.`) to stdout and stay working.

**Expected result:**
The command print message to stdout and exits with code `0`

**Comment by pleerock** [comment]
fixed by #2989
