### ISSUE TITLE
(ES6) createConnection returns undefined for existing SQLite database ; promise does not resolve.

### ISSUE THREAD

**Issue by jordantogether** [typeorm/typeorm#2991]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest` (0.2.6)
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Using node v10.0.0. If  try to use just Javascript, and use the SQLite3 library, typeorm doesn't even give me a promise, or even run, it just returns undefined, and ends. 

~~~javascript
const typeorm = require('typeorm');

// Using regular promises
const shouldBePromise = typeorm.createConnection({
 type: 'sqlite',
 database: './data/my_database_that_absolutely_exists.db',
 synchronize: true,
}).then((res) =>{
 // Never get this value
}).catch((err) => {
 // Never get this either. 
});
console.debug(shouldBePromise); // undefined 

// Using async/await (assuming I'm in an async function)
const shouldBeClass = await typeorm.createConnection({
 type: 'sqlite',
 database: './data/my_database_that_absolutely_exists.db',
 synchronize: true,
});
console.debug(shouldBeClass); // undefined
~~~

If I do this with errors, then the promises work. So for instance: 
~~~~javascript
const shouldBePromise = typeorm.createConnection({
 type: 'sqlite',
 database: './path/my_database_that_absolutely_does_not_exist.db',
 synchronize: true,
}).then((res) =>{
 // Don't get this 
}).catch((err) => {
 console.debug(err); // Can't find the file. 
});
~~~~

** Packages **
"sqlite3": "^4.0.3",
 "typeorm": "^0.2.8"

**Comment by imnotjames** [comment]
Tested this and cannot replicate.
