### ISSUE TITLE
MySQL UNION with query builder possible?

### ISSUE THREAD

**Issue by btxtiger** [typeorm/typeorm#2992]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Is it possible to create  a `UNION` select statement using the query builder? I can't find anything in the documentation about that.

**Comment by lffg** [comment]
There is a plan to add union all to the query builder API?

**Comment by lffg** [comment]
@pleerock, there are any plans to add union to the query builder API?

**Comment by gfborges** [comment]
Is this a future plan ?

**Comment by golubvladimir** [comment]
My version
```
    const entityManager = getManager();

    const tableUn = this.tableUnion.createQueryBuilder('tu')
        .select(['id', 'description'])
        .getQuery();

    const tableTg = this.tags.createQueryBuilder('tg')
        .select(['id', 'name'])
        .getQuery();

    const tags = await entityManager.query(`${ tableUn } UNION ${ tableTg }`);

    return tags;
  }
```

**Comment by gfborges** [comment]
@golubvladimir , me and @gmendess implement this version with parameters.
```ts
union<R>(...queries: SelectQueryBuilder<T>[]): Promise<R> {
    const stringfyQuery = (query: UnionParameters, queryBuilder: SelectQueryBuilder<T>, index: number): UnionParameters => {
        const [sql, parameters] = queryBuilder.connection.driver.escapeQueryWithParameters(queryBuilder.getQuery(), queryBuilder.getParameters(), {});
        if (!index) {
            return { sql, parameters };
        }
        return {
            sql: `${query.sql} UNION ${sql}`,
            parameters: query.parameters.concat(...parameters)
        };
    };

    const { sql, parameters } = queries.reduce(stringfyQuery, { sql: "", parameters: [] });
    return this.query(sql, parameters);
}

interface UnionParameters {
    sql: string;
    parameters: any[];
}
```

**Comment by Gideon-Felt** [comment]
@patbassing what kind of structure is `props[]` in your implementation?

**Comment by patbassing** [comment]
@Gideon-Felt Props is an array of data I use to create the queries needed for my union. In this case, the function filteredIdQuery returns a query builder like so:

```
const filterIdQuery = (
  qb: SelectQueryBuilder<Entity>,
  prop: MyPropInterface,
  index: number
) => {
  const subQuery = qb
    .select('entity.id', 'id')
    .from(Entity, 'entity')

  // additional joins and filtering

  if(prop.shouldFilter){
    // Some specific filtering
    qb.where(...);
  }

  return subQuery;
}
```

**Comment by power-f-GOD** [comment]
In case anyone finds this useful...

I opted for using a `View` instead: [https://orkhan.gitbook.io/typeorm/docs/view-entities](https://orkhan.gitbook.io/typeorm/docs/view-entities).

I composed my `UNION` query in its `expression` option and only `SELECT`ed the fields I need.

It's important to keep in mind that the number of columns in your `UNION` must be equal.
If a column, such as `is_admin`, is not present in one of the tables, you can augment it by using a constant value: `SELECT ..., null AS "is_admin", ...`.

Welcome.✌🏼

**Comment by aestcar** [comment]
My version (I have not used it and have decided to concatenate two queries because it breaks the typing.): 

   const unionSql = `(${this.replaceParams(query.getQuery(), query.getParameters())}) UNION ALL (${this.replaceParams(
      secondQuery.getQuery(),
      secondQuery.getParameters()
    )})`;

    return await getConnection().query(unionSql);
    
   -------
    
    private replaceParams(queryString: string, params: ObjectLiteral): string {
    const query = this.removeOrderBy(queryString);
    const paramRegex = /:(\w+)/g;
    const replacedString = query.replace(paramRegex, (match, paramName) => {
      if (params.hasOwnProperty(paramName)) {
        return `'${params[paramName]}'`;
      }
      return match;
    });

    return replacedString;
  }

  private removeOrderBy(queryString: string): string {
    return queryString.includes('ORDER BY') ? queryString.substring(0, queryString.indexOf('ORDER BY')) : queryString;
  }
