### ISSUE TITLE
An ORM Independent From Electron main and render thread

### ISSUE THREAD

**Issue by aammfe** [typeorm/typeorm#2996]
I have a Dream !!!

Node is running on Electrons main thread and we can do any type of process over there.
When creating a desktop application it will be tedious to work on both threads.

sending messages b/w render and main threads for queries.

Is there any way we can get around this ?
a part of TypeORM working on main thread and on render thread we just create connection and query our data without noticing.
1- can we do it now ?
2-if not 1 then can we will be able to do it in future ? 

[ X] question
[ ] bug report
[X ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ X] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by aammfe** [comment]
Basically My background is enityframework where threads and architecture was not an issue.
Now Issue is these two threads are making life uneasy.



> If you ask if we would like to add a new feature into typeorm to run long-running processes in a separate thread

does it means we can use typeorm from ui thread with any database(mysql etc) supported by typeorm with out thread messaging mess ?

If yes then when I will see this feature ? :)

**Comment by pleerock** [comment]
> Basically My background is enityframework where threads and architecture was not an issue.
Now Issue is these two threads are making life uneasy.

you basically were working in non asynchronous environment

> If yes then when I will see this feature ? :)

as I told not soon :)

> does it means we can use typeorm from ui thread with any database(mysql etc) supported by typeorm with out thread messaging mess ?

in electron its not exactly UI thread... I don't know exactly but from what I know this system in electron is strange, they have two threads or processes but for some reason they are tightly coupled (sure they have design decisions docs).

If you have heavy database computations and you don't wanna block your dekstop process, solution for you is to create a separate thread or process and run all typeorm in there.

**Comment by aammfe** [comment]
> you basically were working in non asynchronous environment

It is an asynchronous environment but application have different threads with same memory poll.

but in electron things are different. two different threads with different memory poll. means we can not access variable from different thread.


  

> as I told not soon :)

is there any way it can be use now ? 
can we run typeorm on different node thread ?

**Comment by pleerock** [comment]
all java threading problems are actually because of same memory poll =)

> can we run typeorm on different node thread ?

yes, you can, just like any code you can run on different thread.
