### ISSUE TITLE
Bidirectional one-to-one in JS

### ISSUE THREAD

**Issue by RobinFalko** [typeorm/typeorm#2997]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, 
I'm reading the docs forward and backwards like crazy but I can't find an example for how to implementing a bidirectional one-to-one relation in JS. I only found this example for TS:
[https://github.com/typeorm/typeorm/blob/master/docs/one-to-one-relations.md](https://github.com/typeorm/typeorm/blob/master/docs/one-to-one-relations.md)

So my best guess (among others) was like:
```
module.exports = {
    AuthorSchema: new EntitySchema({
        name: "Author",
        target: Author,
        columns: {
            id: {
                primary: true,
                type: "int"
            },
            name: {
                type: "varchar"
            }
        },
        relations: {
            book: {
                target: "Book",
                inverseSide: "book.author",
                type: "one-to-one",
                joinColumn: true,
                cascade: true,
                eager: true
            }
        }
    }
)};


module.exports = {
    BookSchema: new EntitySchema({
        name: "Book",
        target: Book,
        columns: {
            id: {
                primary: true,
                type: "int"
            },
            name: {
                type: "varchar"
            }
        },
        relations: {
            author: {
                target: "Author",
                inverseSide: "author.book",
                type: "one-to-one"
            }
        }
    }
)};
```

But this still results in a unidirectional relation.What would be the way to go here? 
Is there a more extensive documentation for JS except those three code samples?

Thanks,
Robin

**Comment by pleerock** [comment]
in `inverseSide` you just need to specify a property name, it knows about target from "target" property. Change `inverseSide: "book.author"` to `inverseSide: "author"`

**Comment by RobinFalko** [comment]
Thank you very much!
