### ISSUE TITLE
ColumnOptions length not working?

### ISSUE THREAD

**Issue by fabLouis** [typeorm/typeorm#30]
Hello,

With the option "autoSchemaCreate: true" and the below column declaration, the 'token' column stays VARCHAR(255) in the MySQL database (the 'nullable' option works fine).
```
@Column({ length: 300, nullable: true })
 token: string;
```
Why?

**Comment by pleerock** [comment]
it should work. are you using mysql?

**Comment by pleerock** [comment]
just checked it work on me:

```typescript

    @Column()
    relativeType: string;

```
changed to:
```typescript
    @Column({ length: "300" })
    relativeType: string;
```
query executed:
```
ALTER TABLE `question` CHANGE `relativeType` `relativeType` varchar(300) NOT NULL
```

**Comment by fabLouis** [comment]
I am using MySQL. It's works well (checking wrong MySQL instance, my bad :/)
Sorry and thanks for your time.
