### ISSUE TITLE
missing FROM-clause entry for table "???????"

### ISSUE THREAD

**Issue by 0phis** [typeorm/typeorm#3000]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.x.x` (0.2.7)

**Steps to reproduce or a small repository showing the problem:**
 My test in pgAdmin4
   SELECT "campaignId", COUNT ("campaignId") AS "totalCampaign"
   FROM public.??????? WHERE "campaignId" = ANY (ARRAY 
   [31,30,28,29,23,19,24,20,21,22]) GROUP BY "campaignId"
   it's OK
   
   const countContact = await this.???????Repository.createQueryBuilder('???????')
            .select('???????.campaignId')
            .addSelect('COUNT(???????.campaignId)', 'totalCampaign')
            .where('???????.campaingId = ANY(:data)', {data})
            .groupBy('???????.campaignId')
            .execute();

The query is wrong, Thank
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [ ] `mysql`
    [x] `postgres`

    Also, please format your code properly
!>

**Comment by Kononnable** [comment]
@0phis 
Could you elaborate on issue description? I don't think I follow what you're trying to say here. What is the query you're trying to generate and what is typeorm generating for you?

**Comment by pleerock** [comment]
Closing as there is no answer from reporter.

**Comment by aliarshad9691** [comment]
I ma facing same issue, when trying to save entity with many2many relationship.
This is the query its generating:
`SELECT Campaign_businessGroups_rid.Business_Group_Id AS "Business_Group_Id", Campaign_businessGroups_rid.Campaign_Id AS "Campaign_Id" FROM "Business_Group" "Business_Group" INNER JOIN "Campaign_Business_Group" "Campaign_businessGroups_rid" ON (Campaign_businessGroups_rid.Campaign_Id = $1 AND Campaign_businessGroups_rid.Business_Group_Id = "Business_Group"."Business_Group_Id") ORDER BY Campaign_businessGroups_rid.Business_Group_Id ASC, Campaign_businessGroups_rid.Campaign_Id ASC'`

This is the error I am getting:
`QueryFailedError: missing FROM-clause entry for table "campaign_businessgroups_rid"`

**Comment by thellimist** [comment]
> I ma facing same issue, when trying to save entity with many2many relationship.
> This is the query its generating:
> `SELECT Campaign_businessGroups_rid.Business_Group_Id AS "Business_Group_Id", Campaign_businessGroups_rid.Campaign_Id AS "Campaign_Id" FROM "Business_Group" "Business_Group" INNER JOIN "Campaign_Business_Group" "Campaign_businessGroups_rid" ON (Campaign_businessGroups_rid.Campaign_Id = $1 AND Campaign_businessGroups_rid.Business_Group_Id = "Business_Group"."Business_Group_Id") ORDER BY Campaign_businessGroups_rid.Business_Group_Id ASC, Campaign_businessGroups_rid.Campaign_Id ASC'`
> 
> This is the error I am getting:
> `QueryFailedError: missing FROM-clause entry for table "campaign_businessgroups_rid"`

+1

**Comment by captainjapeng** [comment]
Same issue:

```sql
SELECT
    "organization"."id" AS "organization_id",
    "organization"."active" AS "organization_active",
    "organization"."createdAt" AS "organization_createdAt",
    "organization"."createdById" AS "organization_createdById",
    "organization"."createdByOrganizationId" AS "organization_createdByOrganizationId",
    "organization"."updatedAt" AS "organization_updatedAt",
    "organization"."updatedById" AS "organization_updatedById",
    "organization"."updatedByOrganizationId" AS "organization_updatedByOrganizationId",
    "organization"."key" AS "organization_key",
    "organization"."name" AS "organization_name",
    "organization"."isAdmin" AS "organization_isAdmin"
FROM
    "organization" "organization"
    INNER JOIN "user" "User" ON "User"."organizationId" = organization.organizationId
WHERE
    (
        "User"."organizationId" = $ 1
        AND "User"."id" = $ 2
    )
```

As you can see, I have defined a `@JoinColumn` but it's not getting respected. And the generated query's inner join doesn't have double quotes in it.

Here is my entity definition:
```typescript

@ObjectType({ isAbstract: true })
export class Node {
  @Field(type => ID)
  @PrimaryGeneratedColumn('uuid')
  id: string

  ...
}

@Entity()
@ObjectType()
export class Organization extends Node {
  ...
}

export class MultiTenantNode {
  @PrimaryColumn('uuid')
  organizationId: string

  @ManyToOne(type => Organization, { lazy: true })
  @JoinColumn({ name: 'organizationId', referencedColumnName: 'id' })
  organization: Lazy<Organization>

  @Field(type => ID)
  @PrimaryGeneratedColumn('uuid')
  id: string
}

@Entity()
@ObjectType()
export class User extends MultiTenantNode {
  ...
}
```

**Comment by ragilr** [comment]
Facing same issue. Please reopen

**Comment by ishan123456789** [comment]
@captainjapeng did you find a fix I'm facing a similar issue

**Comment by captainjapeng** [comment]
No I haven't, I just work around it by using find. Still waiting for a fix
😔

**Comment by btd1337** [comment]
Same problem here. Any solution?

**Comment by ishan123456789** [comment]
For me I was running a JSON query on a sub key
Here's an example
I was running a query on `data.listing` where `data` is of type JSON so running query on `data.listing` directly was throwing me error.

So here are the changes in code:
```
      .where('data.kitchenListings @> :data', {

        data: [

          {

            platformRestaurantId: inputId,

          },

        ],
```
**To**
```
      .where('data @> :outlet', {

        outlet: JSON.stringify({

          kitchenListings: [

            {

              platformRestaurantId: +inputId,

            },

          ],

        }),
```

**Comment by metelski** [comment]
Hello Everyone.

@pleerock @Kononnable I think this could be possibly reopened.

I started facing the same issue today with **TypeORM 0.2.24** using PostgreSQL driver when trying to fetch entities with `@ManyToMany` relation.

I don't know why, but the generated query is missing the double quotes which seems to be the reason of **missing FROM-clause entry for table** errors.

Here is a simplified extract from my entities:

```typescript
@Entity()
export class ProductOption {

    @ManyToMany(() => OptionValue, (value: OptionValue) => value.options)
    @JoinTable({ name: 'product_option_value' })
    public values: OptionValue[];
}

@Entity()
export class OptionValue {

    @Column({
        type: 'simple-json',
    })
    public value: { baseValue: string, alternativeValue: string }; // just an example

    @ManyToMany(() => ProductOption, (productOption: ProductOption) => productOption.values)
    public options: ProductOption[];
}
```

See I have both sides of ManyToMany relation defined with a custom-named `@JoinTable`.

Now, when I try to fetch `Options` with related `OptionValue`s, e.g.

```typescript
productOptionRepository.find({ relations: ["values"] });
```

I get this query generated and this FAILS:

> query failed: SELECT **ProductOption_values_rid**.**optionValueId** AS "optionValueId", **ProductOption_values_rid**.**productOptionId** AS "productOptionId" FROM "option_value" "option_value" INNER JOIN "product_option_value" "ProductOption_values_rid" ON (**ProductOption_values_rid**.**productOptionId** = $1 AND **ProductOption_values_rid**.**optionValueId** = "option_value"."id") ORDER BY **ProductOption_values_rid**.**optionValueId** ASC, **ProductOption_values_rid**.**productOptionId** ASC -- PARAMETERS: [123]

> error: missing FROM-clause entry for table "productoption_values_rid"

Please note the **bold** parts - they are missing double quotes. I compared that to a different but similar relation in other part of my apps, and there the query includes double quotes!  This is what I found in different sources can cause such `missing FROM-clause entry for table` errors. 

@ishan123456789 provided me a hint to check if the `simple-json` may be causing this issue. So I removed the relation:

```typescript
productOptionRepository.find();
```

and voliá! It magically works. There has to be something wrong with the query and/or pivot table being generated automatically by TypeORM for `@ManyToMany` relation when we have an entity containing `simple-json` column.

Any help kindly appreciated!

**Comment by Lampent** [comment]
> Hello Everyone.
> 
> @pleerock @Kononnable I think this could be possibly reopened.
> 
> I started facing the same issue today with **TypeORM 0.2.24** using PostgreSQL driver when trying to fetch entities with `@ManyToMany` relation.
> 
> I don't know why, but the generated query is missing the double quotes which seems to be the reason of **missing FROM-clause entry for table** errors.
> 
> Here is a simplified extract from my entities:
> 
> ```ts
> @Entity()
> export class ProductOption {
> 
>     @ManyToMany(() => OptionValue, (value: OptionValue) => value.options)
>     @JoinTable({ name: 'product_option_value' })
>     public values: OptionValue[];
> }
> 
> @Entity()
> export class OptionValue {
> 
>     @Column({
>         type: 'simple-json',
>     })
>     public value: { baseValue: string, alternativeValue: string }; // just an example
> 
>     @ManyToMany(() => ProductOption, (productOption: ProductOption) => productOption.values)
>     public options: ProductOption[];
> }
> ```
> 
> See I have both sides of ManyToMany relation defined with a custom-named `@JoinTable`.
> 
> Now, when I try to fetch `Options` with related `OptionValue`s, e.g.
> 
> ```ts
> productOptionRepository.find({ relations: ["values"] });
> ```
> 
> I get this query generated and this FAILS:
> 
> > query failed: SELECT **ProductOption_values_rid**.**optionValueId** AS "optionValueId", **ProductOption_values_rid**.**productOptionId** AS "productOptionId" FROM "option_value" "option_value" INNER JOIN "product_option_value" "ProductOption_values_rid" ON (**ProductOption_values_rid**.**productOptionId** = $1 AND **ProductOption_values_rid**.**optionValueId** = "option_value"."id") ORDER BY **ProductOption_values_rid**.**optionValueId** ASC, **ProductOption_values_rid**.**productOptionId** ASC -- PARAMETERS: [123]
> 
> > error: missing FROM-clause entry for table "productoption_values_rid"
> 
> Please note the **bold** parts - they are missing double quotes. I compared that to a different but similar relation in other part of my apps, and there the query includes double quotes! This is what I found in different sources can cause such `missing FROM-clause entry for table` errors.
> 
> @ishan123456789 provided me a hint to check if the `simple-json` may be causing this issue. So I removed the relation:
> 
> ```ts
> productOptionRepository.find();
> ```
> 
> and voliá! It magically works. There has to be something wrong with the query and/or pivot table being generated automatically by TypeORM for `@ManyToMany` relation when we have an entity containing `simple-json` column.
> 
> Any help kindly appreciated!

Same behavior here

**Comment by karousn** [comment]
Same problem here, it was resolved by using alias as the name of the table that i want to join with..!

**Comment by SCollinA** [comment]
@karousn That worked for me too. Seems like it is still an issue that the alias does not work as expected though.

**Comment by khuongphp** [comment]
You can follow my solution if another do not work. Just change your table name from **Snake case** to **Camel case**
[https://github.com/typeorm/typeorm/issues/3521#issuecomment-767252311](https://github.com/typeorm/typeorm/issues/3521#issuecomment-767252311)

**Comment by harshil93** [comment]
@karousn - Can you elaborate the alias fix ? For me the below code doesn't work, all my tables are snake_case

```
@ManyToOne(() => Actor, (actor) => actor.anchorTier2InvoiceMappings3, { eager: true })
  @JoinColumn([{ name: "tier1_id", referencedColumnName: "actorId" }])
  tier1: Actor;
  ```

**Comment by techemmy** [comment]
> For me I was running a JSON query on a sub key Here's an example I was running a query on `data.listing` where `data` is of type JSON so running query on `data.listing` directly was throwing me error.
> 
> So here are the changes in code:
> 
> ```
>       .where('data.kitchenListings @> :data', {
> 
>         data: [
> 
>           {
> 
>             platformRestaurantId: inputId,
> 
>           },
> 
>         ],
> ```
> 
> **To**
> 
> ```
>       .where('data @> :outlet', {
> 
>         outlet: JSON.stringify({
> 
>           kitchenListings: [
> 
>             {
> 
>               platformRestaurantId: +inputId,
> 
>             },
> 
>           ],
> 
>         }),
> ```

Thank you for sharing, @ishan123456789. It helped me with querying for a jsob column.
