### ISSUE TITLE
Typeorm becomes unresponsive when i execute bulk findOne queries in parallel

### ISSUE THREAD

**Issue by HussainAliAkbar** [typeorm/typeorm#3002]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

I have the following function that i am calling 100 times in parallel:

```
export const findByCityNameAndStateId = async (cityName: string, stateId: number):
  Promise<City | undefined> => {
  return getRepository(City).findOne({
    where: {
      value: cityName,
      state: {
        id: stateId
      }
    },
    relations: ['state']
  });
};

```

The problem is that Typeorm starts to behave erratically when i execute this method in parallel a 100 times and does not return. And i have noticed this behavior on and off in alot of other methods.  I even tried replacing findOne with find and a query builder but the same problem existed. 

The problem went away when i reduced the number of parallel executions from 100 to 10.

My question is that am i doing something wrong here or does this problem exist in Typeorm?

Looking forward to hearing on this!

**Comment by hussainakbar10p** [comment]
Alright thanks! i'll try increasing the pool size. If that doesn't work, i'll create a repository which shows the issue. 
Either way, i'll update in a while.

**Comment by HussainAliAkbar** [comment]
Thanks. I'll try increasing the pool size if it resolves the problem or not. If not, then i'll create a base bones repo and share.

**Comment by havenchyk** [comment]
@HussainAliAkbar did you solve your problem with increasing the number of connections?

**Comment by sahebte** [comment]
I have faced same issue on typeorm 0.2.34
