### ISSUE TITLE
How can development and production modes be separated?

### ISSUE THREAD

**Issue by kimjisung78** [typeorm/typeorm#3005]
**Issue type:**

[ O ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[ O ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I want to divide the development and deployment mode into .env files or ormconfig.json.

**Comment by Kononnable** [comment]
@kimjisung78 
https://stackoverflow.com/questions/51054702/using-different-ormconfig-json-files-depending-on-env/51089439#51089439
Does that help? It is an example of how to do that, I think there are also a few other solutions. Or did you mean something else by `development/production mode`?

**Comment by havenchyk** [comment]
@Kononnable maybe it makes sense to add this to documentation? what do you think?

**Comment by havenchyk** [comment]
Also you can create two separate files for example `ormconfig.json.dev` and `ormconfig.json.prod`.

And in production just do `cp ormconfig.json.prod ormconfig.json`.

Will it solve your problem?

**Comment by kimjisung78** [comment]
And I try to apply, so I should solve problem. Thank you!

**Comment by drwatsno** [comment]
@kimjisung78 It is a bad practice to use different configuration files for different environments. According to [12factor](https://www.12factor.net/), use environment variables to configure your application. Use .env files and utilities like dotenv-cli (or similar) to simplify your work with them.

**Comment by canhkieu** [comment]
I recommended use ormconfig.js to setting.

**ormconfig.js**
```javascript
const rootDir = process.env.NODE_ENV === "development" ?
  "src" :
  "build/src"

module.exports = {
  ...
  "entities": [rootDir + "/entities/**/*.{js,ts}"],
  "migrations": [rootDir + "/migrations/*.{js,ts}"],
  "subscribers": [rootDir + "/subscribers/**/*.{js,ts}"],
  "seeds": [rootDir + "/migrations/seeds/**/*.{js,ts}"],
  "factories": [rootDir + "/migrations/factories/**/*.{js,ts}"],
  ...
}
```

**tsconfig.json**
```
{
  "compilerOptions": {
    ...
    "outDir": "./build",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    ...
  },
  ...
}
```

And then, update your scripts in package.json
**package.json**
```
"scripts": {
    "start": "set debug=* && ts-node-dev --respawn --transpileOnly ./src/index.ts",
    "prod": "tsc && node ./build/src/index.js",    <== Focus to this line
  }
```
