### ISSUE TITLE
migration using generate vs create

### ISSUE THREAD

**Issue by webmobiles** [typeorm/typeorm#3006]
**Issue type:**

[x] question

**Database system/driver:**

[x] `postgres`

I've just create 3 tables and entities for 2 tables, I've trie to use generate: but generate don't add 'CREATE TABLE' to the generation, just changes between entities definiton and the current table. So i've delete the tables, and I run again 'generate', and i suspect i don't have the exactly create table that postgres show me when I use show create table....

my question, what is the right way to do the migration? need really 'generate', can I live only with manual copy paste from my postgres create table'?
In that case I've heard that typeorm change name of constrains, but that is when i use generate, not ?  when I use create , typeorm only follow the migration, without compare never the current table structure and my entities, am I right?

**Comment by gintsgints** [comment]
If I understund correctly, generate & sync try to make your defined entity appear in database. Not other way. So you will see generated statements only for objects you have as entities.
