### ISSUE TITLE
leftJoinAndMap with nested relations

### ISSUE THREAD

**Issue by WojtylaCZ** [typeorm/typeorm#3008]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How can I do `leftJoinAndMapOne` with nested relations? I want to accomplish `CardEntity.itemRequested` from following:

    const cards = await getRepository(CardEntity).createQueryBuilder("CardEntity")
      .leftJoinAndSelect("CardEntity.cardItems", "cardItemsEntity")
      .leftJoinAndSelect("cardItemsEntity.item", "ItemEntity")
      .getMany();

I tried to put `leftJoinAndMapOne` instead of last joinAndSelect `.leftJoinAndMapOne("CardEntity.itemRequested","cardItemsEntity.item", "item")` , but that does not map the property.

I tried to put the both JoinAndSelect to subquery, using signature `leftJoinAndMapOne(mapToProperty: string, subQueryFactory: (qb: SelectQueryBuilder<any>) => SelectQueryBuilder<any>, alias: string,` but that does not observe the "CardEntity" within the querybuilder. 

What am I missing?

**Comment by victorschinaider** [comment]
I have the same problem. Entities are not being mapped with SelectQueryBuilder, only with Find operation from Repository.

**Comment by jakubknejzlik** [comment]
@WojtylaCZ I'm trying this with sqlite/mysql driver and it works, is it related only to postgres? I'm using aliases though...so your example should be:
```
const cards = await getRepository(CardEntity).createQueryBuilder("CardEntity")
  . leftJoinAndMapOne("CardEntity.cardItems", "cardItemsEntity","CardEntity_cardItemsEntity")
  . leftJoinAndMapOne("CardEntity_cardItemsEntity.item", "ItemEntity")
  .getMany();
```

**Comment by pleerock** [comment]
@WojtylaCZ did you resolve your issue? You don't need to use `leftJoinAndMapOne`. Code you provided with leftJoinAndSelect looks right.

**Comment by Kononnable** [comment]
Closing as no response from the author.
