### ISSUE TITLE
Class Table inheritance and One To Many relation

### ISSUE THREAD

**Issue by yulric** [typeorm/typeorm#302]
I have an entity which has a OneToMany relationship with a parent class entity whose child classes and itself are using a class table inheritance pattern. I have cascadeInsert set true in the relation decorator columns but when I persist the class with the OneToMany relationship only a row for the parent class is inserted. The child class table does not have any rows. Any thoughts? I can provided some code if needed.

**Comment by Urigo** [comment]
I think I'm facing the same problem.
Here is what I'm trying to do:

`FinancialEntity` is a base class that will hold under it few types, one of them is `Business`.
All of those types will hold an array of `Transaction`:

`FinancialEntity.ts`
```
import {
  Entity,
  PrimaryGeneratedColumn,
  TableInheritance,
  DiscriminatorColumn,
  OneToMany
} from "typeorm";

import { Transaction } from "./Transaction";

@Entity()
@TableInheritance("class-table")
@DiscriminatorColumn({ name: "type", type: "varchar"})
export class FinancialEntity {

  @PrimaryGeneratedColumn()
  id: number;

  @OneToMany(type => Transaction, transaction => transaction.sender)
  transactions: Transaction[];
}
```

`Business.ts`
```
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne
} from 'typeorm';

import { FinancialEntity } from './financialEntity';

@Entity()
export class Transaction {

  @PrimaryGeneratedColumn()
  id: number;

  @Column('money')
  amount: string;

  @ManyToOne(type => FinancialEntity, sender => sender.transactions)
  sender: FinancialEntity | null;
}
```

`Transaction.ts`
```
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne
} from 'typeorm';

import { FinancialEntity } from './FinancialEntity';

@Entity()
export class Transaction {

  @PrimaryGeneratedColumn()
  id: number;

  @Column('money')
  amount: string;

  @ManyToOne(type => FinancialEntity, sender => sender.transactions)
  sender: FinancialEntity | null;
}

```

In `app.ts`:
```
  const transactionRepository = connection.getRepository(Transaction);
  const businessRepository = connection.getRepository(Business);

  const newBusiness = businessRepository.create();
  newBusiness.name = 'new business1';
  await businessRepository.save(newBusiness);

  const newTransaction1 = transactionRepository.create();
  newTransaction1.amount = "10.8";
  await transactionRepository.save(newTransaction1);

  const newTransaction2 = transactionRepository.create();
  newTransaction2.amount = "20.1";
  await transactionRepository.save(newTransaction2);

  newTransaction1.sender = newBusiness;
  await transactionRepository.save(newTransaction1);

  newTransaction2.sender = newBusiness;
  await transactionRepository.save(newTransaction2);

  const allBusinesses = await businessRepository.find({
    join: {
      alias: "business",
      innerJoinAndSelect: {
        transactions: "business.transactions"
      }
    }
  });

  console.log("all business: ", JSON.stringify(allBusinesses));
```

In the console I get this error:
`Error:  { QueryFailedError: column business.id does not exist`

I hope I'm using the right approach for what I'm trying to do

**Comment by pleerock** [comment]
@Urigo there are lot of issues with class/single table inheritance right now and I strongly recommend not to use them yet. Use instead regular inheritance using `extends` keyword or using [embedded columns](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#embedded-columns)

**Comment by Urigo** [comment]
@pleerock then I guess my question is, what is the best way to describe a `OneToMany` relation with multiple types?
Without the ORM I would create a table with `generated id`, `type` and `id(in the type table)` and relate it to the generated id of that table.
What would you suggest would be the best way to describe that with current limitations?

**Comment by pleerock** [comment]
You probably only have two choices:

1. create table with `type` string and `typeId` lets say number. Then everywhere handle things manually like `find({ type: "student", typeId: 1 }) or find({ type: "teacher", typeId: 1 })`. Also you won't have foreign keys in your table.

2. create a table with multiple columns, e.g. studentId, teacherId, employeeId, etc. All will have foreign key but when you save only one will take its id others will be nulls

**Comment by pleerock** [comment]
Class table inheritance support will be completely dropped in 0.2.0 due to complexity and value it brings. There are no plans to add CTI support in the near future as well.
