### ISSUE TITLE
Not able to query on single nested object

### ISSUE THREAD

**Issue by bhushankumarl** [typeorm/typeorm#3023]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

* I have define entiry which has sub type of User. 
* Thier are two attributes in the `_id` and `emails`.
* I have inserted data for entire GroupEntity.
* But now I want to query only those groups which will match the `group.user._id` This query always returns the blank array. It does look like it doen't allow me to query on single nested propertly of entire nested object. However Mongo does suuporte it. https://docs.mongodb.com/manual/tutorial/query-embedded-documents/

```ts
export class UserType {
    @ObjectIdColumn()
    _id: ObjectID;

    @Column(type => EmailsType)
    emails: EmailsType[];
}

@Entity('groups')
export class GroupEntity {

    @ObjectIdColumn()
    _id: ObjectID;

    @Column()
    name: string;

    @Column(type => UserType)
    user: UserType;

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;
}

const user: UserType = {
        _id: req.userStore._id
    };
    try {
        const groupModel = getMongoRepository(GroupEntity);
        const whereCondition = {
            user: user
        };
        debug('whereCondition ', whereCondition);
        req.groupItemStore = await groupModel.find(whereCondition);
    } catch (error) {
        debug('error ', error);
        return next(error);
    }
```

**Comment by nico29** [comment]
@bhushankumarl I think passing a thing in the where should work, as described [here](https://github.com/typeorm/typeorm/issues/2789).
Does that work for you ?

**Comment by imnotjames** [comment]
Given it's been a few years I'm gonna close this out, assuming that their mind was SO BLOWN that it could be fixed per the description there that they forgot to close it out themselves.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
