### ISSUE TITLE
How to use relation id without joining relation with @ManyToMany & @JoinTable

### ISSUE THREAD

**Issue by GitStorageOne** [typeorm/typeorm#3024]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.8` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

[Documentation describes](http://typeorm.io/#/relations-faq/how-to-use-relation-id-without-joining-relation) how to attach related object ID without loading. 
Is there a way to do same with such column:
```ts
  @ManyToMany((type) => Employee)
  @JoinTable({
    name: 'users_employees',
    joinColumn: { name: 'users', referencedColumnName: 'id' },
    inverseJoinColumn: { name: 'employees', referencedColumnName: 'id' }
  })
  employees: Employee[];
```

I would like to attach EmployeeIDs as string array, if possible.

**Comment by btxtiger** [comment]
I'm not sure if I understood your issue.

You could convert your array of ids to an array of Entity objects
```ts
const ids = [1, 2, 3, 4, 5];
const entities = ids.map(id => {
    const newEntity = new Employee();
    newEntity.id = id;
    return newEntity;
});
```

**Comment by GitStorageOne** [comment]
That's not what i mean :)
If you will not specify in `find` method `relations: ['employees']` then employees field will be undefined.
In fact, i realized that there is no way to get array of id's from junction table without loading related table.

**Comment by btxtiger** [comment]
You can achieve this by using raw sql and query builder. e.g.
```ts
getRepository(User)
  .createQueryBuilder('user')
  .select()
  .addSelect(query => {
    return query.subQuery()
      .select('GROUP_CONCAT(attachment_id)')
      .from('attachments', 'atm')
      .where('atm.ofUser = user.userId')
  }, 'userAttachmentIds')
  .where('userId' = :userId, { userId: userId })
  .getMany();

// ...
const userAttachmentIds = resp.split(',');
```
