### ISSUE TITLE
How to update data?

### ISSUE THREAD

**Issue by oipewr** [typeorm/typeorm#3026]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm using following this tutorial: https://itnext.io/building-restful-web-apis-with-node-js-express-mongodb-and-typescript-part-1-2-195bdaf129cf
...but with TypeORM and Postgres. 

How do I update? Here's my attempt:

```ts
  public async updateContact(req: Request, res: Response) {
    try {

      const crmRepository = getManager().getRepository(ECrm);

      // let qContact = await crmRepository.findOne(req.params.contactId);

      await crmRepository.update(
        { id: req.params.contactId },
        req.params.body,
      );

      const updatedContact = await crmRepository.findOne(req.params.contactId);

      res.send(updatedContact);

    } catch(err) {

      res.send(err);

    }
  }
```
That does nothing. Please help.

---
Edit: Add some files.

```ts
// CrmController.ts

import { ECrm } from './CrmEntity';
import { Request, Response,NextFunction } from 'express';
import { Repository, getManager, getRepository } from 'typeorm';

export class CrmController {

  public async addNewContact(req: Request, res: Response) {
    try {

      const crmRepository = getManager().getRepository(ECrm);

      let newContact = await crmRepository.create(req.body);
      await crmRepository.save(newContact);

      res.json(newContact);

    } catch(err) {

      res.send(err);

    }
  }

  public async getContacts(req: Request, res: Response) {
    try {

      const crmRepository = getManager().getRepository(ECrm);

      const contacts = await crmRepository.find();
      res.json(contacts);

    } catch(err) {

      res.send(err);

    }
  }

  public async getContactById(req: Request, res: Response) {
    try {

      const crmRepository = getManager().getRepository(ECrm);

      let qContact = await crmRepository.findOne(req.params.contactId);
      res.send(qContact);

    } catch(err) {

      res.send(err);

    }
  }

  public async updateContact(req: Request, res: Response) {
    try {

      const crmRepository = getManager().getRepository(ECrm);

      // let qContact = await crmRepository.findOne(req.params.contactId);

      await crmRepository.update(
        { id: req.params.contactId },
        req.params.body,
      );

      const updatedContact = await crmRepository.findOne(req.params.contactId);

      res.send(updatedContact);

    } catch(err) {

      res.send(err);

    }
  }

}
```
```ts
// CrmEntity.ts

import {
  Entity,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  PrimaryGeneratedColumn,
} from 'typeorm';
import {
  IsInt,
  Length,
  IsEmail,
  IsString,
  MaxLength,
  IsNotEmpty,
  IsOptional,
} from 'class-validator';


@Entity('crm')
export class ECrm {

  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({
    type: 'varchar',
    length: 150,
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(150)
  name: string;

  @Column({
    type: 'varchar',
    length: 150,
  })
  @IsEmail()
  email: string;

  @Column({
    type: 'text',
    nullable: true,
  })
  @IsOptional()
  company: string;

  @Column({
    type: 'int',
    nullable: true,
  })
  @IsInt()
  @IsOptional()
  @Length(5, 100)
  phone: number;

  @CreateDateColumn()
  created: Date;

  @UpdateDateColumn()
  updated: Date;

}
```
```ts
// CrmRoutes.ts

import { Request, Response } from 'express';
import { CrmController } from './CrmController';

export class Routes {

  public crmController: CrmController = new CrmController();

  public routes(app): void {

    app.route('/')
    .get((req: Request, res: Response) => {
      res.status(200).send({
        message: `GET request successful!`
      })
    })

    app.route('/contact')
    .get(this.crmController.getContacts)
    .post(this.crmController.addNewContact)

    .put((req: Request, res: Response) => {
      res.status(200).send({
        message: `PUT request successful!`
      })
    })

    .delete((req: Request, res: Response) => {
      res.status(200).send({
        message: `DELETE request successful!`
      })
    })

    app.route('/contact/:contactId')
    .get(this.crmController.getContactById)
    .put(this.crmController.updateContact)
    .delete((req: Request, res: Response) => {
      res.status(200).send({
        message: `DELETE request successful!`
      })
    })


  }
}
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by havenchyk** [comment]
Hey @oipewr, thanks for your question. 

It would be nice if you could provide as small example as possible with the results in db after every save/update operation to understand the root cause of the problem.

Also, the best place to ask questions either StackOverflow or [slack](https://join.slack.com/t/typeorm/shared_invite/enQtNDQ1MzA3MDA5MTExLTFiNDEyOGUxZGQyYWIwOTA0NDQxODdkOGQ0OTUxNzFjYjUwY2E0ZmFlODc5OTYyYzAzNGM3MGZjYzhjYTBiZTY)

**Comment by oipewr** [comment]
Hello @havenchyk, thanks for fast reply. I just updated and added some files. Please let me know if you need more information.

**Comment by havenchyk** [comment]
@oipewr was your problem solved with the comment https://github.com/typeorm/typeorm/issues/3026#issuecomment-435012476?

**Comment by havenchyk** [comment]
I'm closing this issue for housekeeping purposes, if something is not clear yet, just continue the conversation or post a message in slack

**Comment by rezamasrori** [comment]
how to update one column in pgadmin 4 for typeOrm ?

**Comment by fafamnzm** [comment]
> 
> 
> how to update one column in pgadmin 4 for typeOrm ?

I believe after going to pgadmin, on the left side, you open the servers>postgreSQL13 (your version)>databases, and find your db name, 
after clicking on it, you go to schemas, then scroll down and find the tables. after cascading the tables, you have to right click on the entity you want and select vie/edit. after that you can see that it will write a qurey automatically and opens the table on your right.after finding the one you want, you double click on the column you want to change. after modifying, make sure to save from the top panel which is the third icon from left and the shape of a table itself.
