### ISSUE TITLE
Shouldn't repository<Entity>.save<T> return Promise<Entity>, not Promise<T>?

### ISSUE THREAD

**Issue by the-daniel-rothig** [typeorm/typeorm#3027]
**Issue type:**

[ ] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

for an entity with two columns, the primary generated `id` and a free-text `name`, this doesn't work:

```
connection.getRepository(MyEntity)
  .then(repo => repo.save({name: "my new record"}))
  .then(result => console.log(`added new record: ${result.id}`));
```

because result is of type `DeepPartial<MyEntity>`. However, under the hood what save actually does return is a complete MyEntity so this works perfectly:

```
connection.getRepository(MyEntity)
  .then(repo => repo.save({name: "my new record"}))
  .then(result => console.log(`added new record: ${(result as MyEntity).id}`));
```

Isn't the point of the return value of save to represent what has been persisted? If so, returning Promise&lt;Entity&gt; makes more sense than Promise&lt;T&gt;.

**Comment by amaranth** [comment]
If it returned `Promise<Entity>` when you use single table inheritance and save a child entity you'd get back the parent type and couldn't access the child fields.

**Comment by the-daniel-rothig** [comment]
I hadn't considered inheritance but out of the top of my head maybe this?
```typescript
save<T extends Entity>(entity: DeepPartial<T>, options?: SaveOptions): Promise<T>;
```

**Comment by amaranth** [comment]
I usually do `repo.save(childObject)` or `repo.save({name: "my new record"} as Child)` otherwise yeah, you would need to cast the result. You could also use the second version to make your example work.

**Comment by the-daniel-rothig** [comment]
I really like that as a solution, thanks! That should go into the docs.

Is there a use case for returning DeepPartial at all? If there isn't, my suggestion would be to use a signature like:

```typescript
save<T extends Entity>(entity: DeepPartial<T>, options?: SaveOptions): Promise<T>;
```

Personally I'd find that more usable :)

**Comment by imnotjames** [comment]
`save` does not always return all fields so it must include the `DeepPartial`.  This is part of the way that `save` works.

It has to return `T extends Entity` because of single-table-inheritance.  If it didn't the `save` couldn't work with inherited classes.
