### ISSUE TITLE
Connection pooling doesn't really pool connections

### ISSUE THREAD

**Issue by swilliams-a3digital** [typeorm/typeorm#303]
It looks like when you create a connection and have connection pooling on type orm creates a "pool of 1 connection", and then when you close the connection type orm ends the pool.  Ideally what we want to do is create a pool of 50 connections in our web api that type orm re-uses across requests.  I'm new to type orm.  Hopefully I'm just missing some way to configure this.

**Comment by pleerock** [comment]
> when you close the connection type orm ends the pool

you should not close connection in the app lifecycle. You open connection once in application bootstrap and close only when application shut downs. Connection pools are handled in a single orm connection, and when you are closing connection - you are closing pool too. If you don't close connection - pool will work as you expect.

**Comment by swilliams-a3digital** [comment]
Thanks for the quick reply.  If I create the "type orm connection" in the app bootstrap, and I have a bunch of simultaneous requests that all use the one "type orm connection" will there be any issues?  

My concern is:
request A comes in, type orm does a persist and while its waiting for the promise to resolve node handles request B that uses the same type orm connection and there is some problem because the connection is in use.

**Comment by pleerock** [comment]
> If I create the "type orm connection" in the app bootstrap, and I have a bunch of simultaneous requests that all use the one "type orm connection" will there be any issues

no, because its designed to work this way.

> I'm hoping the answer is the one "type orm" connection will open multiple my sql db connections if it needs to do multiple things at the same time

yes it is. Real database connection is used from pull per each `persist` / `remove`/ or any other `find` method call

**Comment by swilliams-a3digital** [comment]
Thank you so much for the fast answer to my question.  You can close this issue.

**Comment by zxr90** [comment]
> yes it is. Real database connection is used from pull per each persist / remove/ or any other find method call

Sorry to hijack this issue but i have a similar question while browsing the docs. Is there an option to control the max number of real database connection? If no, what is the default pool size?

**Comment by pleerock** [comment]
@zxr90 I have created separate issue for your issue. You can setup connection pool using "extra" option in connection driver options and pass there underlying driver options (for example if you are using mysql see mysql driver options on how to do this)
