### ISSUE TITLE
Unable to load multi join relations in `find` and `findOne`

### ISSUE THREAD

**Issue by mowaiskalam** [typeorm/typeorm#3032]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, Typeorm not working as expected. I have an Entity `User` which has One-to-One relation with `Candidate`, `Candidate` has One-to-Many relation with `Candidate-Resume`, all relations are properly define in entities as shown below:

User.ts (Entity)
```
@OneToOne(() => Candidate, candidate => candidate.user, { cascade: true })
  public candidate: Candidate;
```
Candidate.ts (Entity)
```
@OneToMany(() => CandidateResume, candidateResume => candidateResume.candidate, {
    cascade: true
  })
  public resumes: CandidateResume[];
```
As mentioned in docs, we can load relation by using:
```
export const findByEmail = async (email: string): Promise<User | undefined> => {
  const userRepof = getConnection().getRepository(User);
  return userRepof.findOne({
    where: { email },
    relations: ['candidate', 'candidate.resumes'],
  });
};
```
Above method is showing ts compile type error: "Object literal may only specify known properties, and 'where' does not exist in type '{ id?: string | string[] | { $raw: string; }......"

And also npm I am getting this (javascript heap memory error) whenever I wrote multi relation 'candidate.resumes' in `findOne`:
```
<--- Last few GCs --->
betts-connect-api | 
betts-connect-api | [6214:0x5598423c0240]    25101 ms: Mark-sweep 1392.7 (1425.5) -> 1392.1 (1425.5) MB, 1110.9 / 0.0 ms  (average mu = 0.071, current mu = 0.002) allocation failure scavenge might not succeed
betts-connect-api | [6214:0x5598423c0240]    26571 ms: Mark-sweep 1392.9 (1425.5) -> 1392.3 (1426.0) MB, 1468.3 / 0.0 ms  (average mu = 0.031, current mu = 0.001) allocation failure scavenge might not succeed
betts-connect-api | 
betts-connect-api | 
betts-connect-api | <--- JS stacktrace --->
betts-connect-api | 
betts-connect-api | ==== JS stack trace =========================================
betts-connect-api | 
betts-connect-api |     0: ExitFrame [pc: 0x15df1b8dc01d]
betts-connect-api |     1: StubFrame [pc: 0x15df1b893490]
betts-connect-api | Security context: 0x2fcfe8c1e681 <JSObject>
betts-connect-api |     2: formatUnionTypes(aka formatUnionTypes) [0xda86568c2a9] [/app/node_modules/typescript/lib/typescript.js:~30152] [pc=0x15df1c16008b](this=0x05d2b88026f1 <undefined>,types=0x139786c05299 <JSArray[11]>)
betts-connect-api |     3: typeToTypeNodeHelper(aka typeToTypeNodeHelper) [0x139786c049a9] [/app/node_modules/typescript/lib/typescript....
betts-connect-api | 
betts-connect-api | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
Image attached for reference
![image](https://user-images.githubusercontent.com/17184822/47897030-cca83500-de91-11e8-96ed-c8c596e2c8e0.png)

Is i am making some mistake to load multiple join records using relations attribute?

Looking forward to hear the solutions. Thanks

**Comment by ryuuji3** [comment]
Can you make a sample repository so that someone can test this?

**Comment by pleerock** [comment]
> As mentioned in docs, we can load relation by using

Docs are for `master` not for the `next`. In `next` version `relations` has different syntax (they are type-safe now). If you want to load relation of the first level you need to do:

```ts
{
  where: { email },
  relations: [ "exampleRelation" ]
}
```

or 

```ts
{
  where: { email },
  relations: { exampleRelation: true }
}
```

But if you want to load nested relations then you can only do: 

```ts
{
  where: { email },
  relations: { exampleRelation: { subrelation: true } }
}
```

Again, this change was made to make queries type-safe.

**Comment by ryuuji3** [comment]
Oh. Whoops, didn't even think about version. Thanks @pleerock

**Comment by mowaiskalam** [comment]
Oh! Thanks @pleerock, same here. Since i'm using the `next` version and i'm loading like the master one. I am having issue when loading sub relation. I will try what you said and let you know. Thanks for the update
