### ISSUE TITLE
Unexpected string import reflect-metadata

### ISSUE THREAD

**Issue by christophedebatz** [typeorm/typeorm#3034]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[x] `0.x.x` (or put your version here) (all versions i've tested)

**Steps to reproduce or a small repository showing the problem:**

Hello everyone,

I'm facing a problem when a start my typescripted app.
So, here is my scripts config:

```
"scripts": {
    "build": "tsc -p src",
    "start": "node dist/app.js"
  }
```

When I execute the build phase, all is OK and a dist directory is created in my project with all the transpiled sources as ES5.

Here is my tsconfig.json:
```
{
  "compileOnSave": true,
  "buildOnSave": false,
  "compilerOptions": {
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es6",
    "module": "commonjs",
    "sourceMap": true,
    "sourceRoot": "src",
    "outDir": "../dist",
    "moduleResolution": "node",
    "removeComments": true,
    "skipLibCheck": true,
    "noImplicitReturns": true,
    "noImplicitAny": false,
    "preserveConstEnums": true,
    "lib": [
      "es6",
      "esnext",
      "dom"
    ]
  }
}
```

But then when I start my program, it's starts but after less than a second, it shows me this error:

```
/path/to/project/node_modules/typeorm/browser/index.js:38
import "reflect-metadata";
       ^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:80:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Can you help me please.

**Comment by grbspltt** [comment]
Your target is ES6. Take a look at your tsconfig.json
What version of node are you using?

**Comment by christophedebatz** [comment]
Hi @grbspltt 
Thanks for your quick reply!
Unfortunately, when I change my target to es5 or es2015 nothing changed.
I'm currently using the most recent node version that brew has downloaded, node v11.0.0.
I think the tsconfig is not transpiling the node_modules sources. So, it's the typeorm's code which has to be ES5 and not ES6.
Any idea please?

**Comment by christophedebatz** [comment]
that's to say? :p

**Comment by leandromsa** [comment]
@christophedebatz  I had a similar problem and it was the the autocomplete of the webstorm that made an import of the 'typeorm/browser' and gave that error

**Comment by grbspltt** [comment]
@leandromsa checked my app, not importing anything from `typeorm/browser`
@christophedebatz I used `require('reflect-metadata') to solve my problem.

**Comment by havenchyk** [comment]
@christophedebatz could you please provide a small repo with an example of your code? It will be easier to catch an error

**Comment by christophedebatz** [comment]
@havenchyk I will do that asap yes, please do not close this ticket 👍

**Comment by havenchyk** [comment]
@christophedebatz do you have any repo public? We can check your public repo, otherwise, it's not a problem of typeorm if you can't reproduce it.

**Comment by christophedebatz** [comment]
@havenchyk it's not a public repo in fact.
all my excuses @havenchyk , I think you can close this ticket, I'm currently passing to sequelize because I cannot find the error :(

**Comment by jerrychong25** [comment]
> **Issue type:**
> 
> [ ] question
> [x] bug report
> [ ] feature request
> [ ] documentation issue
> 
> **Database system/driver:**
> 
> [ ] `cordova`
> [ ] `mongodb`
> [ ] `mssql`
> [x] `mysql` / `mariadb`
> [ ] `oracle`
> [ ] `postgres`
> [ ] `sqlite`
> [ ] `sqljs`
> [ ] `react-native`
> [ ] `expo`
> 
> **TypeORM version:**
> 
> [x] `latest`
> [x] `@next`
> [x] `0.x.x` (or put your version here) (all versions i've tested)
> 
> **Steps to reproduce or a small repository showing the problem:**
> 
> Hello everyone,
> 
> I'm facing a problem when a start my typescripted app.
> So, here is my scripts config:
> 
> ```
> "scripts": {
>     "build": "tsc -p src",
>     "start": "node dist/app.js"
>   }
> ```
> 
> When I execute the build phase, all is OK and a dist directory is created in my project with all the transpiled sources as ES5.
> 
> Here is my tsconfig.json:
> 
> ```
> {
>   "compileOnSave": true,
>   "buildOnSave": false,
>   "compilerOptions": {
>     "declaration": true,
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "allowSyntheticDefaultImports": true,
>     "target": "es6",
>     "module": "commonjs",
>     "sourceMap": true,
>     "sourceRoot": "src",
>     "outDir": "../dist",
>     "moduleResolution": "node",
>     "removeComments": true,
>     "skipLibCheck": true,
>     "noImplicitReturns": true,
>     "noImplicitAny": false,
>     "preserveConstEnums": true,
>     "lib": [
>       "es6",
>       "esnext",
>       "dom"
>     ]
>   }
> }
> ```
> 
> But then when I start my program, it's starts but after less than a second, it shows me this error:
> 
> ```
> /path/to/project/node_modules/typeorm/browser/index.js:38
> import "reflect-metadata";
>        ^^^^^^^^^^^^^^^^^^
> 
> SyntaxError: Unexpected string
>     at new Script (vm.js:80:7)
>     at createScript (vm.js:264:10)
>     at Object.runInThisContext (vm.js:316:10)
>     at Module._compile (internal/modules/cjs/loader.js:670:28)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
>     at Module.load (internal/modules/cjs/loader.js:605:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:536:3)
>     at Module.require (internal/modules/cjs/loader.js:643:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> Can you help me please.

Exactly same issue here.

Tried with `require('reflect-metadata');` and changed from ES5 to ES6 also throw same **SyntaxError: Unexpected string** for **import "reflect-metadata";**.

No idea what is going wrong.

**Comment by xulingyuncetcxl** [comment]
i have the same error.
i create a demo project, with the command: "typeorm init"
the command: "npm start" can run correctly.
the command: "ts-node src/index.ts" can run correctly.
but the command: "node build/index.js" can not run correctly.

**Comment by xulingyuncetcxl** [comment]
i get the answer:
do not use the ormconfig.json
do use like below:

createConnection({
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "test",
    password: "test",
    database: "test",
    entities: [
        User
    ],
    synchronize: true,
    logging: false
}).then(async connection => {
    console.log("Inserting a new user into the database...");
    const user = new User();
    user.firstName = "Timber";
    user.lastName = "Saw";
    user.age = 25;
    await connection.manager.save(user);
    console.log("Saved a new user with id: " + user.id);

    console.log("Loading users from the database...");
    const users = await connection.manager.find(User);
    console.log("Loaded users: ", users);

    console.log("Here you can setup and run express/koa/any other framework.");
}).catch(error => console.log(error));
