### ISSUE TITLE
Schema migration dry run or generate .sql file

### ISSUE THREAD

**Issue by nghenglim** [typeorm/typeorm#3037]
**Issue type:**

[x ] question
[ ] bug report
[ x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Typeorm migrations seems like missing the ability to dry run migrations to look on the sql generated for migrations. This feature is impremented on [db-migrate](https://www.npmjs.com/package/db-migrate). 

It seems similar to the `schema:log`: Shows sql to be executed by schema:sync command. It shows sql log only for your default connection. To run update queries on a concrete connection use -c  option.

**Comment by qbright** [comment]
i have the same problem , so i develop a command tools to do this ，https://www.npmjs.com/package/typeorm-migrate-to-sql

hope can help you

**Comment by nghenglim** [comment]
@qbright nice one! 

after one year from now start getting less usage on typeorm (due to the code structure not able to tree-shake well), I shall unsubscribe from this thread

**Comment by gintsgints** [comment]
Only variant we found for now, is to execute flyway many times. Execution per object type/schema.

**Comment by mwmw7** [comment]
We need to add dry run

**Comment by sarahhenkens** [comment]
@pleerock @holm: I don't think we should close this issue yet. I think having a dry-run option for `typeorm migration:run` is still very useful to have.

Something like the following could print out the queries that will be generated:

```bash
npm run typeorm migration:run --dry
```

It's especially useful when we use the built-in helper functions instead of manually writing SQL:
```js
public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.addColumn('episodes',  new TableColumn({
        name: "date_deleted",
        type: "datetime",
        isNullable: true,
        default: null,
    }));
}
```

**Comment by DylanCulfogienis** [comment]
Any news on this? There is a dry run for migration:generate but we need one for migration:run

**Comment by bombillazo** [comment]
This feature is a must for CI/CD

**Comment by nodegin** [comment]
Is the `--fake` option works the same? I don't understand why it still inserts into migration table after run though.

**Comment by AlissonRS** [comment]
@nodegin the `--fake__ option will simply pretend to run migrations, by inserting pending migrations from your code into the `_migrations` table on your database, without actually running any of the migrations (won't create tables, modify schemas, etc).

It's not the same as a `--dry` option to just show the SQL script that would have been executed by a `run` command.

**Comment by vovados1** [comment]
Hey everyone! Had this issue as well, so I created a cli script that allows to generate `.sql` files from typeorm migration files, and revert them as `typeorm migration:revert` does it.

https://www.npmjs.com/package/typeorm-raw-migrations
