### ISSUE TITLE
Class-table inheritance problem

### ISSUE THREAD

**Issue by icewind** [typeorm/typeorm#304]
Hi. I'm using class-table inheritance and for some reason I'm unable to find anything using repository.
My models
```typescript
@Table()
@TableInheritance('class-table')
@DiscriminatorColumn({ name: 'type', type: 'string' })
export default class User {

  @PrimaryGeneratedColumn()
  public id: number;

  @Column()
  public email: string;

  @Column()
  public password: string;

  @Column()
  public firstName: string;

  @Column()
  public lastName: string;

  @Column()
  public phone: string;

};
```
and
```typescript
@ClassTableChild()
export default class Staff extends User {

  @Column()
  public position: string;

  @Column()
  public department: string;

};
```
In case I'm using Staff repository both tables(user and staff) gets populated, but when I'm trying to find something using User repository I'm receiving an empty response
```typescript
const connection = getConnectionManager().get();
const repository = connection.getRepository(User);
repository.find().then(r => console.log(r));
```
And if I'm trying to use `Staff` repository there is an error like this
```
ERROR:  syntax error at or near "."
STATEMENT:  SELECT "staff"."position" AS "staff_position", "staff"."department" AS "staff_department", "staff"."manager" AS "staff_manager", "staff"."userId" AS "staff_userId", parentIdColumn_"user"."id" AS parentIdColumn_"user"_"id", parentIdColumn_"user"."email" AS parentIdColumn_"user"_"email", parentIdColumn_"user"."password" AS parentIdColumn_"user"_"password", parentIdColumn_"user"."firstName" AS parentIdColumn_"user"_"firstName", parentIdColumn_"user"."lastName" AS parentIdColumn_"user"_"lastName", parentIdColumn_"user"."phone" AS parentIdColumn_"user"_"phone", parentIdColumn_"user"."type" AS parentIdColumn_"user"_"type" FROM "staff" "staff" JOIN "user" "parentIdColumn_user" ON staff.userId="parentIdColumn_user".id
```

**UPDATE**
Tried several options and in any case typeorm is generating wrong aliases
```
parentIdColumn_"user"."phone" AS parentIdColumn_"user"_"phone"
```

How can i select all users regardless of type? And how to select only specific type?
Thanks.

**Comment by kaspercools** [comment]
I am having the same issue, a solution to this issue would be appreciated!

**Comment by jtmthf** [comment]
Facing the same issue too

**Comment by pleerock** [comment]
class-table inheritance is a hugest pain in orm. I won't recommend use for now it if you have too much problems with it. Best way to use inheritance via `@AbtractEntity`

**Comment by jtmthf** [comment]
@pleerock Was in the process of trying Concrete Table Inheritance and that ended up working. Only issue was that schema sync couldn't handle the transition. Thanks for the suggestion though!

**Comment by pleerock** [comment]
don't forget to include abstract entities in `entities: []` (or specify dirs) of the connection properties

**Comment by pleerock** [comment]
Class table inheritance support will be completely dropped in 0.2.0 due to complexity and value it brings. There are no plans to add CTI support in the near future as well.
