### ISSUE TITLE
Programmatically Run Migrations

### ISSUE THREAD

**Issue by joshrathke** [typeorm/typeorm#3040]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there a way to programmatically run migrations? I bundle my server with web pack so it would be nice to bundle migrations up into one file and would like it if the server didn’t have to have TypeORM as a global dependency so the cli commands work properly. 

I saw some mention of importing/exporting all migrations the piping them into the getConnection method but can’t find any documentation on how exactly to structure the migration classes so getConnection will accept them.

Has anyone out there done this?

**Comment by joshrathke** [comment]
I mistakenly closed this issue. Using the following syntax results in a TypeError. As it states in the documentation this should accept a Migration class which is what CreateUser.... is. So I am a little unsure how to proceed.
```
createConnection({
    migrationsRun: true,
    migrations: [CreateUser1517934720430],
})
```

`TS2345: Argument of type '{ migrationsRun: true; migrations: any[]; }' is not assignable to parameter of type 'ConnectionOptions'.   Type '{ migrationsRun: true; migrations: any[]; }' is not assignable to type 'MongoConnectionOptions'.     Property 'type' is missing in type '{ migrationsRun: true; migrations: any[]; }'.`

**Comment by vinayluzrao** [comment]
Hey @joshrathke, do you mind sharing how you ultimately solved this?

**Comment by jerrychong25** [comment]
@joshrathke & @vinayluzrao,

Mind to share how do you fix this issue?

I faced similar issue on how to create new table and run migration progamatically.

Issue: https://github.com/typeorm/typeorm/issues/4295

Thanks.

**Comment by kevindashgit** [comment]
Is there documentation around this? Maybe I missed it.

**Comment by valVk** [comment]
cc: @kevindashgit 
`./src/migrations.ts`
```
import {
  createConnection
} from 'typeorm';
import config from './config';

(async() => {

  const connection = await createConnection({...config.defaultConnectionConfig, logging: true});

  await connection.runMigrations({
    transaction: false
  });
  await connection.close();
})();
```

To run 

`node -r ts-node/register ./src/migrations.ts` or after transpiling `node ./src/migrations.js`

Cheers.

**Comment by goldingdamien** [comment]
Note: `(property) transaction?: "all" | "none" | "each" | undefined`

**Comment by mirupal** [comment]
for current typorm versions using `DataSource`

```
import { DataSource, DataSourceOptions } from 'typeorm';

const options: DataSourceOptions = { .. your options ...};
const dataSource = new DataSource(options); // usually imported 

await dataSource.runMigrations({
  transaction: 'all',
});
await dataSource.destroy();
```

**Comment by guths** [comment]
`import { DataSource } from 'typeorm';
import { dataSourceOptions } from './data-source';

(async () => {
  const dataSource = new DataSource(dataSourceOptions);

  await dataSource.initialize();

  await dataSource.runMigrations({
    transaction: 'all',
  });
  await dataSource.destroy();
})();`


Dont forget dataSource.initialize guys

**Comment by siddrc** [comment]
In my case I was using electron+ typeorm and the path for migration files was creating a issue when I was calling `runMigrations`  during electron startup so I used the actual class name of the migration file in the migrations array [ same with entities ]  for some reason I would not get entities when running code from electron but if i use it in the array like below it works. 

   ¯\_(ツ)_/¯

```ts
import "dotenv/config";
import { DataSource } from "typeorm";
import { CustomerConfig } from "./src/modules/customer-config/customer-config.entity";
import { CustomerConfig1743620752385 } from "./migrations/1743620752385-migrations-customer-config";
const dataSource = new DataSource({
  type: "sqlite",
  database: process.env.SQL_LITE3_DATA_FILE,
  entities: [CustomerConfig],
  migrations: [
    CustomerConfig1743620752385
  ],
  synchronize: false, // important
  logging: true // use this for debugging
});
export {dataSource};
```
