### ISSUE TITLE
bind message supplies 0 parameters, but prepared statement "" requires 65536

### ISSUE THREAD

**Issue by gutenye** [typeorm/typeorm#3044]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Given

```ts
const posts = times(65536).map(v => Post.create({title: v}))
await Post.createQueryBuilder().insert().values(posts).execute() 
// or in transaction
connection.transaction(async (entityManager) => { 
  await entityManager.save(posts)
})
```

Got

```
bind message supplies 0 parameters, but prepared statement "" requires 65536
```

Because postgresql limit parameters to [65535](https://github.com/brianc/node-postgres/issues/1463#issuecomment-333313948)

Solution: create one single sql statement: `INSERT INTO posts(title) VALUES ('0'), ..., ('65535')` with [pg-promise insert helper](http://vitaly-t.github.io/pg-promise/helpers.html#.insert) or [pg-format](https://github.com/datalanche/node-pg-format#-arrays-and-objects)

EDIT:
It also affects transaction `connection.transaction(async (entityManager) => { await entityManager.save(lotsOfPosts) })`

**Comment by Kononnable** [comment]
You should split such inserts into chunks.

**Comment by havenchyk** [comment]
@gutenye you can create a PR to fix this behavior or feel free to create a new issue.

I'm closing this issue for housekeeping purposes, if something is not clear yet, just continue the conversation or post a message in slack

**Comment by pleerock** [comment]
> You should split such inserts into chunks.

You can do it following way:

```ts
await entityManager.save(posts, { chunk: 30 }) // save 30 entities in a time, for example
```
