### ISSUE TITLE
Validation based on value of other field

### ISSUE THREAD

**Issue by greensheep** [typeorm/typeorm#3046]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Simplistic example, but say I have an entity that includes two date fields like this:

```
@Entity()
export class Subscription {

  ...

  @Column()
  @IsDate()
  startDate: Date;

  @Column()
  @IsDate()
  endDate: Date;

  ...
}
```

I'm using the recommended `class-validator` package to apply `@IsDate()` validations, but also want to ensure the `endDate` is not before `startDate`. Because I can't do this:

```
@MinDate(this.startDate)
endDate: Date;
```

What's the recommended way to validate the `endDate` is not before the `startDate`?

**Comment by feather-jmalone** [comment]
you could do additional validations like that in a `@BeforeInsert`/`@BeforeUpdate` method. i don't know if that's the _recommended_ way (there's an argument to be had about how much logic should be contained in the entity class), but it works just fine.
