### ISSUE TITLE
types of property 'length' in ColumnWithLengthOptions and TableColumnOptions

### ISSUE THREAD

**Issue by jsnick** [typeorm/typeorm#3048]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
// ColumnwithLengthOptions.d.ts
export interface ColumnWithLengthOptions {
    /**
     * Column type's length.
     * For example type = "varchar" and length = "100" means ORM will create a column with type varchar(100).
     */
    length?: string | number;
}

// TableColumnOptions.d.ts
export interface TableColumnOptions {
        /**
     * Column type's length. Used only on some column types.
     * For example type = "string" and length = "100" means that ORM will create a column with type varchar(100).
     */
    length?: string;
}
```

As you can see, types of property 'length' are incompatible each other.
I use 'length' property in number type in Entity and migration files.
But in migration files, I cannot use 'length' property in number type.

**Comment by imnotjames** [comment]
This is intentional - `TableColumn.length` can only be strings because it comes from the database.  `ColumnMetadata` comes from user input and may have numbers - but it will be converted to strings before being used with anything else.
