### ISSUE TITLE
How to define a table's columns in a migration

### ISSUE THREAD

**Issue by Ilyes512** [typeorm/typeorm#305]
So I am trying to define a initial migration for a table. I got the fallowing working:

```js
import { Connection, EntityManager, MigrationInterface, QueryRunner, TableSchema, ColumnSchema } from "typeorm";

export class RoleMigration1487758190294 implements MigrationInterface {

    public async up(queryRunner: QueryRunner, connection: Connection, entityManager?: EntityManager): Promise<any> {
        let schema = new TableSchema('Role', [
            {
                name: 'roleId',
                type: 'integer',
                isGenerated: true,
                isPrimary: true,
            },
            {
                name: 'displayName',
                type: 'character varying(100)',
                isNullable: false,
            },
        ]);
        queryRunner.createTable(schema);
    }

    public async down(queryRunner: QueryRunner, connection: Connection, entityManager?: EntityManager): Promise<any> {
        return queryRunner.query('DROP TABLE IF EXISTS "Role";');
    }
}
```
By using the above I would lock my self to postgresql (because of `type: 'character varying(100)'`). How can I define columns with the same parameters as in the column decorator ([ColumnOptions](https://github.com/typeorm/typeorm/blob/master/src/decorator/options/ColumnOptions.ts)).

**Comment by pleerock** [comment]
there probably isnt easy way to do so right now. So better if you keep so for now, or even use raw sql queries if you need something complex until I (or someone else) create a good API helper functions for migrations. I have in plans to implement it in the near future.

**Comment by valeriy-devpronet** [comment]
It was be easy if `scehma:sync` does not only creation of a table but removing also.

**Comment by pleerock** [comment]
you can just call schema:drop before it.

**Comment by valeriy-devpronet** [comment]
yes, this can be done, but this will not work in case when I do not want delete whole DB just to remove one table.

**Comment by Ilyes512** [comment]
@valeriy-devpronet Can you create a separate issue to discuss your problem? This issue has nothing to do with your issue. I just find it really rude to "take over" some else his github issue.

**Comment by valeriy-devpronet** [comment]
This is not problem for me. Maybe it was not clear from my side.
> By using the above I would lock my self to postgresql
I just tried to propose a solution for creating table in 'Database agnostic' way, through entities and this is simple, but there exists one caveats you can't 'revert' your changes if you'll delete a newly created entity.
That all. if this is not solution for you, or not fits to your need that ok.

**Comment by Ilyes512** [comment]
@valeriy-devpronet Ah, my mistake then. I thought you where just merely asking a question.

At the moment while developing I am using the "sync"-feature, but for future production deployment we can not rely on the "sync"-feature.

For now I will stick to the postgres specific types.

**Comment by shanike** [comment]
Hello! Any updates on `ColumnOptions` API in TypeORM Migrations?
I have an Entity class, and a Migration that creates this entity, and currently the columns definition in the migration is duplicate to the column definition in the Entity.

*sync=off, migrations=on.

## Example
```ts
// Entity
@Entity()
export class AzureUsage {
    @PrimaryGeneratedColumn({ type: "bigint", name: "id", unsigned: true })
    id: number;

    @CreateDateColumn({ name: "timestamp" })
    timestamp: Date;

    @JoinColumn({ name: "user_id" })
    @ManyToOne(() => UserInfo, (user) => user.azureUsage, { nullable: true })
    userId?: number;

    ...
```
```ts
// Migration
        await queryRunner.createTable(new Table({
            name: tableName,
            columns: [
                { name: "id", type: "bigint", unsigned: true, isPrimary: true, isGenerated: true, generationStrategy: "increment" },
                { name: "timestamp", type: "datetime", length: "6", isNullable: false, default: "CURRENT_TIMESTAMP(6)" },
                { name: "user_id", type: "bigint", isNullable: true, unsigned: true },
                ...
```
Issue: duplicate information/code (:

Thanks!
