### ISSUE TITLE
Transactions - use inserted ids

### ISSUE THREAD

**Issue by jwhitmarsh** [typeorm/typeorm#3053]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I've read through the docs, and as many issues as possible, but I can't see how to use inserted record ids inside a transaction:

```ts
await getConnection().transaction(async trx => {
      const rec1 = await trx.save({...});
      const rec2 = trx.create(Entity, {
        parentId: rec1.id, // <---- here
        ...
      })
});
```

`id` on the enity is declared with `@PrimaryGeneratedColumn` but the `save` method doesn't even return the `id` column. 

Big thanks in advance for anyone that can help!

**Comment by michele-franchi** [comment]
You can get the last inserted ids by using createQueryBuilder().
Here's a working example:
`await getManager().transaction(async transactionalEntityManager => {
      const insertResult = await transactionalEntityManager.createQueryBuilder()
        .insert()
        .into(User)
        .values(user)
        .execute();
      const id = insertResult.identifiers[0].id;
      ...
});`

**Comment by pleerock** [comment]
In your example above `rec1` should have id in, I'm not sure why you don't have it.
