### ISSUE TITLE
{ EntityMetadataNotFound: No metadata for "User" was found.

### ISSUE THREAD

**Issue by efukela** [typeorm/typeorm#3054]
**Issue type:** Bug

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

`0.2.5`

**Steps to reproduce or a small repository showing the problem:**
    [x] `mysql`
    [x] `postgres`

I'm using Express-typescript [boilerplate](https://github.com/w3tecch/express-typescript-boilerplate) So to reproduce it's possible to clone it and see if the error persists, for some reason - it works on linux box, but not on windows, to be more specific i'm running windows 10, with 64bit.

**Comment by Kononnable** [comment]
@efukela 
Why do you think this is a bug in typeorm not in boilerplate?

**Comment by havenchyk** [comment]
I'm closing this issue for housekeeping purposes, if something is not clear yet, just continue the conversation or post a message in slack.
