### ISSUE TITLE
Correct use of onDelete

### ISSUE THREAD

**Issue by projectyang** [typeorm/typeorm#3059]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
@Entity()
export class Customer {
    @PrimaryColumn()
    id: string;

    @Column()
    name: string;

    @Column()
    region: string;

    @Index()
    @Column({ nullable: true })
    phase: string;

    @Index()
    @Column()
    status: string;

    @Column({ nullable: true })
    nextCommunicationAt: Date;

    @Column({ nullable: true })
    lastCommunicationAt: Date;

    @OneToMany(type => AdvertisingAccount, account => account.customer, {onDelete: 'CASCADE'})
    accounts: AdvertisingAccount[];
}


@Entity()
export class AdvertisingAccount {
    @PrimaryColumn()
    id: string;

    @PrimaryColumn()
    type: string;

    @Column()
    name: string;

    @Column({ nullable: true })
    currency: string;

    @Index()
    @Column()
    status: string;

    @Column({ nullable: true })
    timezone: string;

    @Column({ nullable: true })
    channelId: string;

    @ManyToOne(type => Customer, customer => customer.accounts, { eager: true, nullable: true })
    customer: Customer;
}

```

Expected:
Deleting a customer will also delete the associated advertising accounts.

Actual:
Receive a 'Cannot delete or update a parent row: a foreign key constraint fails' for customerId in AdvertisingAccount when attempting to delete a Customer row.

**Comment by DEllement** [comment]
Try to put the onDelete: "CASCADE" on the ManyToOne side, im having similar issue with this, in my case its working for ManyToOne but not OneToOne

**Comment by projectyang** [comment]
Tried switching onDelete to the other side, still doesn't work.

**Comment by DEllement** [comment]
Hi, i had similar issues as your, when working, record was simply detached, i ended up giving up on cascade delete in favor of doing manual delete instead, apparently this is still a work in progress feature of typeorm,

for now, in my case it is cheaper time wise, to do manual delete using queryBuilder.
Sorry i could note provide you the answer.

**Comment by projectyang** [comment]
No worries, I ended up doing the same as you and manually deleting it. Thanks for helping!

**Comment by gmbwa** [comment]
Adding the cascade to both sides (OneToMany and ManyToOne) work. If you put it on one side it will not work

**Comment by pdNN** [comment]
> Adding the cascade to both sides (OneToMany and ManyToOne) works. If you put it on one side it will not work

This works for me! UP

**Comment by justinIs** [comment]
For me I get
```
Error during migration generation:
Error: Relation <tableName>#<tableCol> and <otherTableName>#<tableCol2> both has cascade remove set. This may lead to unexpected circular removals. Please set cascade remove only from one side of relationship.
```

**Comment by matgott** [comment]
onCascade doesn't work on OneToMany relationships. This is a expected behavior?

I have a Role entity, which can have many Permissions (OneToMany), I want if some role is deleted, also all the permision associated with it must be deleted.
