### ISSUE TITLE
leftJoinAndMapMany is not mapping the result to the property when I pass a Subquery to the second argument

### ISSUE THREAD

**Issue by FelipeTaiarol** [typeorm/typeorm#3063]
**Issue type:**
[X] bug

**Database system/driver:**
[X] `postgres`

**TypeORM version:**
[X] `latest`

Steps to reproduce:
1. Clone [this repo](https://github.com/FelipeTaiarol/typeorm_issues)
2. ```npm install && tsc```
3. ```npm start```

These are the entities:
```
@Entity()
export class Category {
    @PrimaryGeneratedColumn()
    id: number;
    @Column()
    name: string;

    posts: Post[];
}

@Entity()
export class Post {
    @PrimaryGeneratedColumn()
    id: number;
    @Column()
    title: string;
    @Column('int')
    categoryId: number;
}
```

And this is how I build the queries:

This one returns the list of Posts:
```
connection.createQueryBuilder().select('category').from(Category, 'category')
              .leftJoinAndMapMany('category.posts', Post, 'post', 'post.categoryId = category.id');
```

This one does not:
```
connection.createQueryBuilder().select('category').from(Category, 'category')
                    .leftJoinAndMapMany('category.posts', qb => qb.select().from(Post, 'post'), 'post', 'post."categoryId" = category.id');
```

**Comment by FelipeTaiarol** [comment]
I didn't find a test with leftJoinAndMapMany using a Subquery instead of an Entity, but in  [this comment](https://github.com/typeorm/typeorm/issues/2074#issuecomment-386803563) @pleerock  says it should work, if I understood it correctly. It is also written that it should work in the docs [here](https://github.com/typeorm/typeorm/blob/c56e605e729506e405b3a00a98a9cebaf257ec94/src/query-builder/SelectQueryBuilder.ts#L471)

**Comment by oleksii-shnyra** [comment]
Confirm, the same issue here

**Comment by pleerock** [comment]
I'm going to deprecate joinAndMap methods in 0.4.0 and don't recommend to use them. Alternative is to execute a separate query, if you need to have it in the same query consider using raw query.

**Comment by victorschinaider** [comment]
@pleerock , execute a separate query? Then, if i select 2000 entities, i'll have to execute a query to 'joinandmap' in each entity item?

**Comment by andrew8er** [comment]
Is deprecating the `joinAndMap()` still on the table? If so, could you please update the roadmap accordingly?

**Comment by vvictorov** [comment]
No support for sub-queries?!?

**Comment by andreechristian** [comment]
@pleerock could you show us a sample alternative code? leftJoinAndMapOne / Many has really helped me to simplify the object returned from queryBuilder. Without it i will need to select deeply within an object / array for the result i wanted. Ex: User -> UserPost -> Post with custom junction table. Without leftJoinAndMapMany, i would need to do user.userPosts[0].post.title to retrieve the first post title, with leftJoinAndMapMany, i could do user.userPosts[0].title instead. Could you tell us also why this feature is going to be deprecated? :(

**Comment by Overfacto** [comment]
Same issue here.

I found the difference from loggings of getRawOne() when subquery is passed or not to leftJoinAndMapMany.

I think it maybe related mapping issue.

getRawOne(or getRawMany) result has not prefix of join target table when using subquery. While without subquery, We can find prefix.

ex) getRawOne result without subquery is 
```
category_id : 1  // catggory id
category_name : 'test category' // category name
id : 1 // post id
title : 'test post' // post title
```

and with subquery we can find the prefix for pos

```
category_id : 1  // catggory id
category_name : 'test category' // category name
post_id : 1 // post id
post_title : 'test post' // post title
```


and each other queries which can be found from  getQuery() result are same.

**Comment by ptucky** [comment]
Thank for this article, it save me.
 TypeOrm  leftJoinAndMapMany with joining Nth level

**Comment by Taher62** [comment]
Hi guys
Is there any solution or improvement for this problem?
I have the same issue.

**Comment by mladen107** [comment]
same here

**Comment by kuangshp** [comment]
What will replace it in the future

**Comment by MattEagle95** [comment]
it's a big bug since 4 years which makes it unable for business apps to use this library

**Comment by icepole-jon** [comment]
Obviously, many people have encountered this problem, but none of them have been solved. (from issues)
The subquery does not automatically generate the specified key in the entity
```ts
@Entity()
export class Product {
	@PrimaryGeneratedColumn()
  	id: number;
}
@Entity()
export class UsageRecord {
	@PrimaryGeneratedColumn()
  	id: number;

	@OneToOne(() => Product)
  	@JoinColumn()
  	product: Relation<Product>;
}
```
```ts
const good = await dataSource.getRepository(UsageRecord)
	  .createQueryBuilder("usageRecord")
	  .leftJoinAndMapOne(
		    "usageRecord.product",
		    "usageRecord.product",  // relation 
		    "product"
	  ).getManyAndCount()

const bad = await dataSource.getRepository(UsageRecord)
	  .createQueryBuilder("usageRecord")
	  .leftJoinAndMapOne(
		    "usageRecord.product",
		    (qb) => {
		    	return qb.select().from(Product, "product")
		    },
		    "product",
		    "product.id = usageRecord.productId"
	  ).getManyAndCount()
```
The mysql statements they generate are different, maybe that's why it doesn't work, even though their sql results are the same
):

**Comment by jimOnAir** [comment]
Is there any solution?

**Comment by Exchar** [comment]
same here
