### ISSUE TITLE
Automatic identity field for related entities on insert

### ISSUE THREAD

**Issue by pburrows** [typeorm/typeorm#3066]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am curious if I am doing something wrong. I have entities defined with OneToMany relationships. They are:
Category
CategoryItem

with Category being the top level and OneToMany relationships between CategoryItem.

When creating new records I do:

```
const newCategory: Category = new Category();
newCategory.name = 'Bob'
newCategory.items = [];

const newItem: CategoryItem = new CategoryItem();
newItem.someField = 'whatever';

newCategory.items.push(newItem);
```

Now, when I go to save these items, if I just do:

(note: `entities` in the below code is a `getManager()` call result)

```
await entities.save(category)
```

Then the categoryItems are not saved. (aren't they supposed to be)?

If I do

```
await entities.save(category);
for(const item of category.items) {
   await entities.save(item);
}
```

Then I get an error saying cannot insert null into categoryId field for the CategoryItem records. In order for it to save correctly, I find I have to do this:

```
await entities.save(category);
for(const item of category.items) {
    item.categoryId = category.categoryId;
   await entities.save(item);
}
```

only then will it save.

I feel that this should not be the case at all. 
I feel that all I really should have to do is the original `entities.save(category)`

Am I wrong? If not, any thoughts on what I might be doing wrong?

Thanks.

**Comment by pburrows** [comment]
I asked this question on stackoverflow, since there hasn't been any activity here:

https://stackoverflow.com/questions/53283468/does-typeorm-automatically-assign-foreign-keys-on-insert

**Comment by arsanjea** [comment]
Hey guys. I love this library (and already started collaborating on extensions)!
I am having the same problem. Can anyone look into this?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
