### ISSUE TITLE
Handling of database schemas

### ISSUE THREAD

**Issue by carragom** [typeorm/typeorm#3067]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.8` (or put your version here)

# Intro

Hello, first of all thanks for the great job on this library. I just started using it but so far is one of the best TS libraries I have worked with. I do have a question/request, please correct me if any of the following assumptions are wrong.

When working directly with a database (not using TypeORM) we have two options to work with objects that exist on a schema different than the default schema for the user.

1. References the objects by it's full name `myotherschema.mytable` or `myotherschema.myview`
2. Change the default schema and reference the objects just by it's name like `mytable` or `myview` 

AFAIK TypeORM only support the first option. It uses the schema option to reference the objects in the generated SQL by their full name.

With the second option, each database does it differently, but since this lib already handles database differences gracefully I don't think that to be an issue, e.g.

## PostgreSQL

In PostgreSQL we can configure the session to lookup objects on different schemas in the order we decide much like the `$PATH` variable in our shells.

```SQL
SET search_path TO myotherschema,public;
```
## Oracle

In Oracle we can change the default lookup schema in the following way

```SQL
ALTER SESSION SET CURRENT_SCHEMA=MYOTHERSCHEMA
```

## MySQL/MariaDB

MySQL is a bit of an oddball when it comes to schemas, they used to be called databases and are now transitioning to schemas which IMO is what they really are. But still possible

```SQL
USE myotherschema;
```

## MSSQL

Microsoft SQL does not support temporarily changing the default schema. It can only be done permanently for the user.

# Use case

In schema based multi-tenant applications there normally is one database with multiple schemas. One schema is the `main` where the common application data is stored and one for each tenant of the application. Normally each tenant schema has the same set of objects and is named using some kind of unique id. When a request enter the system the user is validated and a schema is selected using the data on the `main` schema. And then most/all subsequent database operations go to the tenant specific schema. As you can see the schema we want to use is only know at run time.

Another use case for this is the migrations API. While TypeORM migration API is very rich. I normally write my database migrations in pure SQL because it's really hard for an ORM to implement every possible DDL available in a database. When using SQL for migrations it's not possible to run the same set of migrations on different schemas using the CLI.

# What can be done today with TypeORM

* I think we could have a default connection to the `main` schema and dynamically create a connection with the tenant specific schema every time a request is received. I don't think this would scale at all and it would only work with generated SQL. Raw queries would have to be assembled dynamically to include the tenant schema which is only known at run time.
* Manually change the schema with a query for example `getConnection().query('SET search_path TO myschema');`. I think this could have unexpected results with the built in connection pooling.

# The ideal solution

Ideally there could be a function that would dynamically change the schema using the built in functionality of each database engine. Something like

```TS
const conn = await getConnection().changeDefaultSchema('myschema');
```

The previous statement would get an existing connection and send the correct statement to change the default schema depending on the database driver. As many other TypeORM functionality, the docs should state which databases support the functionality. Most of them do.

While I know this might not be something simple to implement or not be a priority right now. I hope to have at least convinced you that there is a valid use case for this functionality.

**Comment by webmobiles** [comment]
@carragom   please , where exactly you execute:  set search_path TO schema; ?  

I have this in my connection, but query is not going to ''original_public' I get errors 

`" QueryFailedError: no schema has been selected to create in" ...
`
my connection:
```
      await createConnection({
        type: 'postgres',
        url: process.env.DATABASE_URL,
        schema: 'original_public',
        synchronize: false,
        entities: [`${__dirname}/entity/**\.*?s`],
        migrations: [`${__dirname}/migrations/**\.*?s`],
        migrationsRun: true,
      });
```

**Comment by Jimmy-Hernandez** [comment]
I'm running into this exact use case myself. This would be a lovely feature :)

**Comment by nurikabe** [comment]
I've done some experimental refactoring to support this for PostgreSQL; especially with migrations:

https://github.com/nurikabe/typeorm/commits/master

This adds a switch to the `migration:generate` command such that one can generate SQL without schema prefixes:

`migration:generate --with-schema false -n Test`

The modified `migration:generate` command can then be passed the schema to use:

`migration:run --default-schema schema1`
`migration:run --default-schema schema2`

In this way migrations can be generated and then run against different schemas.

@carragom Is this along the lines of what you were thinking?

@pleerock Would you consider a PR if I fleshed-out the implementation?

**Comment by aaronfulkerson** [comment]
> I've done some experimental refactoring to support this for PostgreSQL; especially with migrations:
> 
> https://github.com/nurikabe/typeorm/commits/master
> 
> This adds a switch to the `migration:generate` command such that one can generate SQL without schema prefixes:
> 
> `migration:generate --with-schema false -n Test`
> 
> The modified `migration:generate` command can then be passed the schema to use:
> 
> `migration:run --default-schema schema1`
> `migration:run --default-schema schema2`
> 
> In this way migrations can be generated and then run against different schemas.
> 
> @carragom Is this along the lines of what you were thinking?
> 
> @pleerock Would you consider a PR if I fleshed-out the implementation?

This would be utterly fantastic.

**Comment by carragom** [comment]
> 
> 
> I've done some experimental refactoring to support this for PostgreSQL; especially with migrations:
> 
> https://github.com/nurikabe/typeorm/commits/master
> 
> This adds a switch to the `migration:generate` command such that one can generate SQL without schema prefixes:
> 
> `migration:generate --with-schema false -n Test`
> 
> The modified `migration:generate` command can then be passed the schema to use:
> 
> `migration:run --default-schema schema1`
> `migration:run --default-schema schema2`
> 
> In this way migrations can be generated and then run against different schemas.
> 
> @carragom Is this along the lines of what you were thinking?
> 
> @pleerock Would you consider a PR if I fleshed-out the implementation?

Yes, this would be great. As for the parameters I would make it so that when `--default-schema myschema` is used `--with-schema` is automatically `false`.

**Comment by sam-hunt** [comment]
This would be particularly useful for scenarios where multiple identical schemas exist in the same database, e.g.

- multiple tenant schemas
- main schema + e2e test schema.

Currently In Postgres, If an unprefixed raw query is executed with `schema: myotherschema` set in the initial `PostgresConnectionOptions`, the raw query uses the `public` schema tables rather than `myotherschema` which is quite unintuitive since `find` and `createQueryBuilder` will correctly use `myotherschema`.

Additionally, in cases where the schemas are identical, no `relation/column does not exist` error will be thrown. Unless the user role lacks permissions to access the `public` schema, or a foreign key constraint fails etc, these mistakes can be very difficult to debug.

This could be solved by running `SET search_path TO myotherschema;` on initialization when `schema: myotherschema` is set in the connection options.

**Comment by michaelharrisonroth** [comment]
@aaronfulkerson I am currently writing a multi-tenant/multi-locale app using this exact functionality. For now, to run migrations I do the following:

1. Remove the prefixes after I generate our primary `CreateTables` migration.

2. 
```
await tenantConn.query(`SET search_path TO tenant_${tenantId}_${lang},public,postgis`)
await tenantConn.runMigrations()
await tenantConn.query(`SET search_path TO public,postgis`)
```

Obviously, the primary issue is that future `Generate` commands don't work.

If you need help/support on this feature I'd be happy to pitch in as I will need it very soon.

@pleerock let us know what you would like to see in order to get a PR like this merged. 
P.S. TypeORM is by far my favorite ORM to date and I'm excited to watch it continue to mature.

**Comment by nyrrrr** [comment]
@nurikabe was this already implemented?

**Comment by nurikabe** [comment]
@nyrrrr Aside from my experimental branch, no.

**Comment by elias-garcia** [comment]
Any news on this?

**Comment by aaronfulkerson** [comment]
After thinking about this, how I'd like it to work is to have some sort of a file or table that defines tenant or schema names and those schemas are then generated after the connection to the database is made.

**Comment by elias-garcia** [comment]
But having the tenants defined in a file does not allow to dynamically create and query by tenants... The proper solution would be to select the `schema` dynamically on each query, something like `connection.schema("tenantId").getRepository(Entity).find()` for example...

**Comment by aaronfulkerson** [comment]
You'd still be able to query by tenant, it'd be a way to generate schemas before the application starts. I mean it might not be necessary since generation of the schema should happen at the same time the tenant is created. I can see cases where it would be useful but maybe not. Never mind!

**Comment by michaelharrisonroth** [comment]
> After thinking about this, how I'd like it to work is to have some sort of a file or table that defines tenant or schema names and those schemas are then generated after the connection to the database is made.

This is exactly how I am handling a multi-tenant application. I have a `tenants` table that resides in the `public` schema. My application service that handles creating new tenants adds a row to the table, then on startup, it runs migrations / seeds (that have not yet run) for each tenant in the table. This creates a new postgres schema and runs the table migrations/seeds on that new schema.

Here is a snippet from my `ApplicationService`:

```typescript
// create schema if not exists
const conn = getConnection()
await conn.query(`CREATE SCHEMA IF NOT EXISTS tenant_${tenantId}`)

// connect to schema
const tenantConn = await TenantService.connect(`tenant_${tenantId}`)

// run migrations
await tenantConn.query(`SET search_path TO tenant_${tenantId},public,postgis`)
await tenantConn.runMigrations()
await tenantConn.query(`SET search_path TO public,postgis`)
```

I also wrote a custom `SeederService` which is an extension of this library: 
https://github.com/w3tecch/typeorm-seeding

So I am able to do the following:
```typescript
// seed demo tenant data
const tenantConn = await TenantService.connect(`tenant_${tenantId}`)
await SeederService.run(
    tenantConn, 
    CreateRoles
)
```

**Comment by elias-garcia** [comment]
That's nice @michaelharrisonroth for creating and running migrations/seedings for an schema, but how then you easily query or insert in that schemas by tenant? I don't see an easy way of doing that. The only way would be to use a middleware to create connections and passing it all along the request scope so then you can get a repository from that connection...

**Comment by michaelharrisonroth** [comment]
> That's nice @michaelharrisonroth for creating and running migrations/seedings for an schema, but how then you easily query or insert in that schemas by tenant? I don't see an easy way of doing that. The only way would be to use a middleware to create connections and passing it all along the request scope so then you can get a repository from that connection...

@elias-garcia you're right - I use middleware in express for that purpose to grab the tenant from a subdomain or a route param:

```typescript
 try {
    // get tenant from DB
    const tenantRepository = getRepository(Tenant)
    res.locals.tenant = await tenantRepository.findOneOrFail({ 
        // subdomain: req.subdomains[0] 
        id: Number(req.params.tenant)
    })
} catch (err) {
    // tenant doesn't exist
    log.warn(err)
    res.sendStatus(HttpStatusCode.UNAUTHORIZED)
    return
}
```

Then in controllers, you can use a repo or a queryBuilder:

```typescript
const query = createQueryBuilder(Role, 'role', `tenant_${res.locals.tenant.id}`)
```

It's not perfect but it works quite well without too much complexity for my purposes.

**Comment by nyrrrr** [comment]
This is basically the same I did. (we run schema based tenants)
We also updated our migration files after generating them to adjust to different tenants.

    public async up(queryRunner: QueryRunner): Promise<any> {
     await queryRunner.query(
            `CREATE TABLE "` + queryRunner.connection.name + `"."tableName" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, ` ,....
        undefined);
    }

**Comment by imnotjames** [comment]
We've intentionally not implemented this because at one point in history it caused conflict with how we handle multi-schema environments.

While it doesn't now, there's not much push to implement it.  I had attempted to via the schema option but after chatting with other maintainers we decided that it wasn't bringing much as far as features go.

**Comment by killjoy2013** [comment]
> We've intentionally not implemented this because at one point in history it caused conflict with how we handle multi-schema environments.
> 
> While it doesn't now, there's not much push to implement it. I had attempted to via the schema option but after chatting with other maintainers we decided that it wasn't bringing much as far as features go.

Sorry to hear that. It could be really helpful to maintain various schemas with ease in microservice environment that use different db schemas in a database.

**Comment by dzcpy** [comment]
> > We've intentionally not implemented this because at one point in history it caused conflict with how we handle multi-schema environments.
> > While it doesn't now, there's not much push to implement it. I had attempted to via the schema option but after chatting with other maintainers we decided that it wasn't bringing much as far as features go.
> 
> Sorry to hear that. It could be really helpful to maintain various schemas with ease in microservice environment that use different db schemas in a database.

Well, MikroORM supports multitenancy through database schema (in their newest v5 version). This is the only JS ORM that I know which supports it

**Comment by beez-dev** [comment]
> But having the tenants defined in a file does not allow to dynamically create and query by tenants... The proper solution would be to select the `schema` dynamically on each query, something like `connection.schema("tenantId").getRepository(Entity).find()` for example...

this doesn't seem to be valid anymore

**Comment by beez-dev** [comment]
> @aaronfulkerson @carragom I am currently writing a multi-tenant/multi-locale app using this exact functionality. For now, to run migrations I do the following:
> 
>     1. Remove the prefixes after I generate our primary `CreateTables` migration.
> 
> 
> ```ts
> await tenantConn.query(`SET search_path TO tenant_${tenantId}_${lang},public,postgis`)
> await tenantConn.runMigrations()
> await tenantConn.query(`SET search_path TO public,postgis`)
> ```
> 
>     3. For all future queries, I rely on passing in the schema (which isn't perfect but works fairly well)
> 
> 
> ```ts
> getRepository(User, `tenant_${tenantId}_${lang}`)
> ```
> 
> Obviously, the primary issue is that future `Generate` commands don't work.
> 
> If you need help/support on this feature I'd be happy to pitch in as I will need it very soon.
> 
> @pleerock let us know what you would like to see in order to get a PR like this merged. P.S. TypeORM is by far my favorite ORM to date and I'm excited to watch it continue to mature.

Is this syntax possible? getRepository seems to be available now as dataSource.getRepository(Entity) which doesn't contain the second param.

**Comment by ameenpv** [comment]
> Then in controllers, you can use a repo or a queryBuilder:
> 
> ```ts
> const roleRepo = getRepository(Role, `tenant_${res.locals.tenant.id}`)
> // OR
> const query = createQueryBuilder(Role, 'role', `tenant_${res.locals.tenant.id}`)
> ```
> 
> It's not perfect but it works quite well without too much complexity for my purposes.

Thanks for explaining it @mikehroth
Does this affect the perfomance? Means, does this creates a new connection everytime the query/roleRepo is created, or is in the same connection pool?

**Comment by ameenpv** [comment]
> > @aaronfulkerson @carragom I am currently writing a multi-tenant/multi-locale app using this exact functionality. For now, to run migrations I do the following:
> > ```
> > 1. Remove the prefixes after I generate our primary `CreateTables` migration.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```ts
> > await tenantConn.query(`SET search_path TO tenant_${tenantId}_${lang},public,postgis`)
> > await tenantConn.runMigrations()
> > await tenantConn.query(`SET search_path TO public,postgis`)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 3. For all future queries, I rely on passing in the schema (which isn't perfect but works fairly well)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```ts
> > getRepository(User, `tenant_${tenantId}_${lang}`)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Obviously, the primary issue is that future `Generate` commands don't work.
> > If you need help/support on this feature I'd be happy to pitch in as I will need it very soon.
> > @pleerock let us know what you would like to see in order to get a PR like this merged. P.S. TypeORM is by far my favorite ORM to date and I'm excited to watch it continue to mature.
> 
> Is this syntax possible? getRepository seems to be available now as dataSource.getRepository(Entity) which doesn't contain the second param.

any luck?

**Comment by 4rcan31** [comment]
Hello everyone. I had a similar problem. In my PostgreSQL database, I use specific schemas and run separate migrations for each one.

The issue arose because TypeORM's run command (migration:run) executes migrations with raw SQL and doesn't specify which schema to apply the migrations to (It doesn't take it from the connection either). I assume it only works if you're using the public schema.

To solve this, I created a custom command. In my case, I'm using Nest.js with nest-commander, but this can be perfectly done with a .js or .ts script without needing nest-commander.

This is my code:

```ts
import { Command, CommandRunner, Option } from 'nest-commander';
import { AppDataSource } from '../../../database/datasource';
import { DataSource } from 'typeorm';

@Command({
  name: 'mgrn:run',
  description: 'Runs migrations on a specific schema',
})
export class RunMigrationCommand extends CommandRunner {
  async run(
    passedParams: string[],
    options?: { schema?: string },
  ): Promise<void> {

    const schema = options?.schema || process.env.DB_SCHEMA;

    /*
        I clone the DataSource for two reasons:
      
        1. Because `.runMigrations()` looks for the migrations table in the schema
            defined in the original DataSource. That's why I need to override the schema
            here if it's passed as a parameter to point to another schema.
            (Only PostgreSQL accepts the `schema` key, hence the validation).
      
        2. For the raw SQL of the migrations to execute in the expected schema,
            the connection is forced to the specific schema with:
            
              extra: { options: `-c search_path=${schema}` }
      
            Then the schema is explicitly set for raw SQL queries:
      
              await AppDataSource.query(`SET search_path TO "${schema}"`);
      
        The bug preventing migrations from running on a specific schema is documented at:
        
        https://github.com/typeorm/typeorm/issues/3067
    */

    const baseConfig = AppDataSource.options;

    const dynamicDataSource = new DataSource({
      ...baseConfig,
      ...(baseConfig.type === "postgres" ? {
        schema: schema
      } : {}),
      extra: { options: `-c search_path=${schema}` }
    });
    console.log(`Running migrations on schema: ${schema}`);
    try {
      await dynamicDataSource.initialize();
      await AppDataSource.query(`SET search_path TO "${schema}"`);
      await dynamicDataSource.runMigrations();
    } catch (error) {
      console.error('Error running migrations:', error);
    } finally {
      await dynamicDataSource.destroy();
    }
  }

  @Option({
    flags: '-s, --schema [schema]',
    description: 'PostgreSQL schema where migrations will be executed',
  })
  parseSchema(val: string) {
    return val;
  }
}
```
