### ISSUE TITLE
Postgresql full-text search. Can't find docs

### ISSUE THREAD

**Issue by itobert** [typeorm/typeorm#3068]
**Issue type:**

[ X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi! Looking all docs and i can't find any descriptions about How setting up entity and write query to use full-text search in Postgresql. 
I need to realize searching from all DB tables and colums to get id of all matches.
But i don't know how to start

**Comment by jtushman** [comment]
Take a look at:  https://github.com/typeorm/typeorm/blob/a4dec02cc59d3219a29c7be0322af2253e1452dc/test/github-issues/1259/issue-1259.ts#L38

to get started.

There is not explict TypeORM support -- but you can jump to the pg utils pretty easily

**Comment by jtushman** [comment]
I think if there was a recipe section -- this would be a cool recipe to have.

If helpful this is a pattern I have put into place.  Happy to make it more generic ...

```
    const { entities, raw } = await connection.manager
      .createQueryBuilder(Note, 'note')
      .leftJoinAndSelect('note.subjects', 'subject')
      .leftJoinAndSelect('note.notebook', 'notebook')
      .addSelect(
        "ts_rank_cd(to_tsvector(coalesce(note.content,'')), plainto_tsquery(:query))",
        'rank'
      )
      .where('notebook."ownerId" =(:userId)', { userId: user.id })
      .andWhere('notebook.id=(:notebookId)', { notebookId: notebook.id })
      .orderBy('rank', 'DESC')
      .setParameter('query', query)
      .getRawAndEntities();

    const enhancedEntities = entities.map((e, index) => {
      return { ...e, rank: raw[index].rank, isTypeOf: 'Note' };
    });

    return enhancedEntities.reduce((accum, entity) => {
      if (entity.rank > 0) {
        accum.push(entity);
      }
      return accum;
    }, []);
```

**Comment by vlapo** [comment]
Maybe add note about possibility write custom SQL where statement in `where`, `orWhere` and `andWhere` methods here http://typeorm.io/#/select-query-builder/adding-where-expression.

**Comment by pleerock** [comment]
There recently was a question on full text search in #3191. TBH personally I don't see a need to document this one since its possible to build thousand different queries with SQL and query builder, and any of them can be represented in a separate question/answer.

But if you think we should add docs with some generic documentation on how to use query builder with different complexity queries feel free to PR it.

I think we can close this issue. Don't hesitate to continue discussion, Im just closing issues for housekeeping purposes.

**Comment by rtman** [comment]
I put my implementation on this [stackoverflow question]( https://stackoverflow.com/a/64450994/7618813)
