### ISSUE TITLE
how to change order of composite primary keys

### ISSUE THREAD

**Issue by YuhangGe** [typeorm/typeorm#3069]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

````js
@Entity()
class Project {
  @PrimaryColumn()
  id: number;
  
  @OneToMany(type => Art, art => art.project)
  art: Art;
};

@Entity()
class Art {
  @ManyToOne(type => Project, project => project.arts, { primary: true })
  project: Project;
  
  @PrimaryColumn()
  id: number
}
````

Such code generate table with SQL: `CRETATE TABLE art ... PRIMARY KEY(id, projectId) ...`.

Could it be changed to `CRETATE TABLE art ... PRIMARY KEY(projectId, id) ...` ?

**Comment by danbruce** [comment]
Any progress or comments on this?

MySQL performance can be very dependent on the order of the fields in a composite primary key.

**Comment by Kononnable** [comment]
You should be able to make it work as you expect if you declare your entity a bit different.
Take a look at https://github.com/typeorm/typeorm/issues/3657#issuecomment-473409100

**Comment by YuhangGe** [comment]
Looks like it can be solved. I will try it later.
