### ISSUE TITLE
Creating a Schema with Relations

### ISSUE THREAD

**Issue by hlohrenz** [typeorm/typeorm#3073]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am having typescript issues when creating a Schema for my Entity. I have a news-article.schema.ts file below:

```ts
import { EntitySchema } from "typeorm";

export const NewsArticleSchema = new EntitySchema({
  name: 'news_article',
  tableName: 'news_articles',
  columns: {
    id: {
      type: Number,
      primary: true,
      generated: true
    },
    title: {
      type: String
    }
  },
  relations: {
    author: {
      type: 'many-to-one',
      target: 'user',
      inverseSide: 'author.news',
      eager: true,
      joinColumn: 'author_id'
    }
  }
});
```

However, I'm receiving this issue in my compiler:

> Types of property 'relations' are incompatible.
> Type '{ author: { type: string, target: string, inverseSide: string, eager: boolean, joinColumn: string } }' is not assignable to type '{ id?: EntitySchemaRelationOptions, title?: EntitySchemaRelationOptions; }'

I'm not seeing what I'm doing wrong here. Any ideas? Is this an issue with the schemas being so premature in Typeorm?

**Comment by Kononnable** [comment]
@hlohrenz 
Did you resolve your issue?

**Comment by hlohrenz** [comment]
@kononnable unfortunately, no :( I went a different route and just put my schema right inside my entity with decorators. A path I didn't want to take but oh well.

**Comment by vpp** [comment]
As per https://github.com/typeorm/typeorm/blob/master/src/entity-schema/EntitySchemaOptions.ts#L66 managed to overcome such issue by something like that:
```
import { EntitySchema } from "typeorm";

import { IAuthor } from './Author'

export interface INewsArticleSchema {
  id: number
  title: string
  author: IAuthor[]
}

export const NewsArticleSchema = new EntitySchema({
  name: 'news_article',
  tableName: 'news_articles',
  columns: {
    id: {
      type: Number,
      primary: true,
      generated: true
    },
    title: {
      type: String
    }
  },
  relations: {
    author: {
      type: 'many-to-one',
      target: 'user',
      inverseSide: 'author.news',
      eager: true,
      joinColumn: 'author_id'
    }
  }
});
```

**Comment by erhise** [comment]
@vpp , do you know if this a valid bug or your solution is completely necessary to get everything to work?

**Comment by vpp** [comment]
I think it was just incompleteness of documentation. The type definition in [here](https://github.com/typeorm/typeorm/blob/master/src/entity-schema/EntitySchemaOptions.ts#L66) actually requires relation to be described in the interface.
