### ISSUE TITLE
Use .env with migrations cli

### ISSUE THREAD

**Issue by zefexdeveloper** [typeorm/typeorm#3074]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In the `ormconfig.json` you have this setting:

```
"cli": {
  "migrationsDir": "migration"
}
```

However I can't reproduce the same using `.env`

If I try to run: `typeorm migration:create -n PostRefactoring`

It creates the migration in the root folder.

How can I set `.env` for the `cli`?

**Comment by zefexdeveloper** [comment]
Ops, looks like there's `TYPEORM_ENTITIES_DIR` after all, my mistake, I couldn't find anywhere in the docs, found in another issue tho.

**Comment by btxtiger** [comment]
Yes in deed, the last weeks I often slid into the situation not finding the information in the docs. Using google with "typeorm < subject >" often deliveres better results than looking in the docs.
Here you find all information about using different config files
https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md

**Comment by zefexdeveloper** [comment]
Thank you @btxtiger, the same happened with me, I found all the information on Google and not in the documentation.

**Comment by lili21** [comment]
`TYPEORM_MIGRATIONS_DIR` doesn't work at all. I'm using `typeorm@0.2.16`。It always create migration in the root folder.

**Comment by jellelicht** [comment]
It seems this doesn't work for `typeorm@0.2.25` either

**Comment by alkema** [comment]
I needed both `TYPEORM_MIGRATIONS_DIR` and `TYPEORM_MIGRATIONS` to be set. Without `TYPEORM_MIGRATIONS`, it searches for the migration in the root folder of my project.

```bash
➜  redacted-backend git:(main) ✗ cat .env
PORT="3000"
TYPEORM_CONNECTION="postgres"
TYPEORM_HOST="localhost"
TYPEORM_PORT=5432
TYPEORM_USERNAME=""
TYPEORM_PASSWORD=""
TYPEORM_DATABASE="redacted"
TYPEORM_MIGRATIONS_DIR=./src/migrations
TYPEORM_MIGRATIONS=./src/migrations/*.ts
```

```bash
➜  redacted-backend git:(main) ✗ ts-node ./node_modules/.bin/typeorm migration:run

query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'migrations'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
0 migrations are already loaded in the database.
1 migrations were found in the source code.
1 migrations are new migrations that needs to be executed.
query: START TRANSACTION
query:
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        CREATE TABLE users (
            id uuid DEFAULT uuid_generate_v4 (),
            first_name VARCHAR NOT NULL,
            last_name VARCHAR NOT NULL,
            email VARCHAR NOT NULL,
            phone VARCHAR,
            PRIMARY KEY (id)
        );

query: INSERT INTO "migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1617320082843,"CreateUsers1617320082843"]
Migration CreateUsers1617320082843 has been executed successfully.
query: COMMIT
➜  redacted-backend git:(main)
```

**Comment by brunocordeiro180** [comment]
I was using the version 0.3.5 of typeorm, then I changed to version 0.2.30 and it solved my problem.
