### ISSUE TITLE
migration:generate can't detect change on mssql

### ISSUE THREAD

**Issue by PJCAfonso** [typeorm/typeorm#3075]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[X] `0.2.8` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I try to update my database thru migration CLI command, but can't understand why is not working.
If I change the syncronize to true on creation connection, the database is created, so I know I are doing something wrong, but can find what?

_typeorm migration:generate -n
    No changes in database schema were found - cannot generate a migration. To create a new empty
    migration use "typeorm migration:create" command_

I've the ormconfig.json
**[{
    "name": "default",
    "type": "mssql",
    "host": "127.0.0.1",
    "port": 1433,
    "username": "******",
    "password": "******",
    "database": "testes",
    "entities": [
        "src/entities/**/*.ts}"
    ],
    "migration": [
        "src/migration/**/*.ts"
    ],
    "subscribers": [
        "src/subscribers/**/*.ts"
     ],
    "options:": {
        "encrypt": "false"
    }
}]**

and create database directly on SQL Server, and define the user used above as dbo of **testes**.

I have my connection like this:
**export const databaseInitializer = async () => {
    return await createConnection(
        {
        name    : "default",
        type    : "mssql",
        host    : "127.0.0.1",
        port    : 1433,
        username : "********",
        password : '********',
        database : 'testes',
        entities: [ 'src/entities/*{.js,.ts}' ],
        migrations: [ 'src/migrations/*{.js,.ts}' ],
        subscribers: [ 'src/subscribers/*{.js,.ts}'],
        logging: ['query', 'error'],
        synchronize: false,
        migrationsRun: true,
        options: {
            encrypt: false
        },        
        cli: {
            migrationsDir: 'src/migration',
            entitiesDir: 'src/entities',
            subscribersDir: 'src/subscribers'
        },
    }
    ).then((...args) => {
        debugger
        console.log('Database connection established');
    });
};**

Any help of what are wrong?

Thanks

**Comment by btxtiger** [comment]
First of all, please use backticks to escape your code, otherwise it is hard to read.
If you use `ormconfig.json`, you don't need to pass a config object to `createConnection()`, just leave it empty. I personally recommend to use `ormconfig.js` instead `.json`, because in most editors its easier to modify.

1. It seems your paths for entities, migration, subscribers are not correct. Make sure to have the filename wildcards available.
```js
module.exports = {
   type: 'mysql',
   host: 'localhost',
   port: 3306,
   username: 'root',
   password: '123456789',
   database: 'my_db',
   synchronize: false,
   logging: true,
   maxQueryExecutionTime: 100,
   entities: ['dist/database/entity/**/*{.js,.ts}'],
   migrations: ['dist/database/migration/**/*{.js,.ts}'],
   subscribers: ['dist/database/subscriber/**/*{.js,.ts}']
};
```

2. Do not use `synchronize: true`. If you want to establish a migration workflow, use the following steps:
   - Drop all tables from the database, the database must be empty. If you already have data in there, you can temporary configure another empty database.
   - Use the migration generator to create an "InitialMigration", which will create all tables. Every state of your database must be available as migration. If you don't have that initial migration, there will no entry in the migrations table. So the ORM could not resolve what state your database actually is, which results in failing migrations, because they are applied on a wrong state.

3. You don't need `options: {encrypt: false},` as it is the default, (except for MS Azure).

**Comment by PJCAfonso** [comment]
> 
> 
> First of all, please use backticks to escape your code, otherwise it is hard to read.
> If you use `ormconfig.json`, you don't need to pass a config object to `createConnection()`, just leave it empty. I personally recommend to use `ormconfig.js` instead `.json`, because in most editors its easier to modify.
> 
>     1. It seems your paths for entities, migration, subscribers are not correct. Make sure to have the filename wildcards available.
> 
> 
> ```js
> module.exports = {
>    type: 'mysql',
>    host: 'localhost',
>    port: 3306,
>    username: 'root',
>    password: '123456789',
>    database: 'my_db',
>    synchronize: false,
>    logging: true,
>    maxQueryExecutionTime: 100,
>    entities: ['dist/database/entity/**/*{.js,.ts}'],
>    migrations: ['dist/database/migration/**/*{.js,.ts}'],
>    subscribers: ['dist/database/subscriber/**/*{.js,.ts}']
> };
> ```
> 
>     1. **Do not use** `synchronize: true`. If you want to establish a migration workflow, use the following steps:
>        
>        * Drop all tables from the database, the database must be empty. If you already have data in there, you can temporary configure another empty database.
>        * Use the migration generator to create an "InitialMigration", which will create all tables. Every state of your database must be available as migration. If you don't have that initial migration, there will no entry in the migrations table. So the ORM could not resolve what state your database actually is, which results in failing migrations, because they are applied on a wrong state.
> 
>     2. You don't need `options: {encrypt: false},` as it is the default, (except for MS Azure).
> 
>     3. Not all changes on your entities will result in a database change, because in this case they are TypeORM specific. But changing property(column) names will always be changes in the database.

Hi btxtiger

1) I try leave createConnection empty, and also check the directory name, and the problem mantain!
2) If I change synchronize to false, the migration not work (and I do not know why?) so the for I have database ok, I must use until migration is working synchronize: true,
3) I got a message to put encrypt false! may be is wrong reading by me...
4) Is not correct, New columns, change name and relationship changes...

**Comment by PJCAfonso** [comment]
problems solve. adding extension on vs code.

**Comment by fjms** [comment]
> 
> 
> problems solve. adding extension on vs code.

How did you solve it? I have the same problem.

**Comment by deepakbaliga** [comment]
> problems solve. adding extension on vs code.

Could you please elaborate on this @PJCAfonso ?

**Comment by xoapit** [comment]
How did you solve it? What is the extension?

**Comment by rubiin** [comment]
@PJCAfonso share your solution

**Comment by btxtiger** [comment]
@rubiin what is the issue? I think there is everything clear. There is no extension that helps with typeorm.

**Comment by JimLynchCodes** [comment]
@btxtiger for me, this is the part that is not clear: 

>    * Use the migration generator to create an "InitialMigration", which will create all tables. 

I dropped all tables, but when I run "migration:generate" for the first time it always says, "No changes in database schema were found". 

Is there a special command or flag to run with it for the initial migration?

thanks!

**Comment by btxtiger** [comment]
@JimLynchCodes no there is no special command.
Make sure:
- Drop all tables, database must be completely empty
- Use `synchronize: false`
- Have the typeorm entities created correctly

Then `migration:generate` should create the first migration that creates the tables.

**Comment by ikushlianski** [comment]
For me the problem was that I did not list all entities for which I wanted to run migration in the db-config file.
Once I did this, migration was generated.

**Comment by wslp12** [comment]
please share to us

**Comment by AmirNaghibi** [comment]
> No changes in database schema were found - cannot generate a migration. To create a new empty migration use "typeorm migration:create" command

I was facing the above issue due to missing **export**  keyword for the entity class. 

```ts
@Entity()
export class User extends BaseEntity implements IUser {
    constructor() {
        super();
    }

    @PrimaryGeneratedColumn()
    readonly id!: number;

    @Column()
    name!: string;
}
```
