### ISSUE TITLE
Migration Unexpected token error

### ISSUE THREAD

**Issue by zefexdeveloper** [typeorm/typeorm#3079]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm having a problem when running `typeorm migration:run` I'm getting this error:

> (function (exports, require, module, __filename, __dirname) { import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';                  
> SyntaxError: Unexpected token {

After reading a few issues people suggested to run: `ts-node ./node_modules/.bin/typeorm migration:run`, but I'm also getting errors:

> basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
> SyntaxError: missing ) after argument list

**Comment by havenchyk** [comment]
@zefexdeveloper could you please post an example of your `ormconfig`? Or even better a small repo to reproduce the problem?

**Comment by btxtiger** [comment]
Looks like a syntax error in your entity. If you have prettier installed, you could use it as syntax validator as well, because formatting will fail if the syntax in not correct. I'm not sure if "standard" editor formatters would have this behaviour.

**Comment by zefexdeveloper** [comment]
That is how my entity looks like @btxtiger:

```
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity()
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;
}
```

And yes, I have Prettier installed.

**Comment by btxtiger** [comment]
Look ok for me. The only idea i have is that it could be a `tsconfig.json` issue. I'm running this config:
```json
{
   "compilerOptions": {
      "outDir": "dist",
      "baseUrl": ".",
      "sourceMap": true,
      "module": "commonjs",
      "moduleResolution": "node",
      "esModuleInterop": true,
      "allowSyntheticDefaultImports": true,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "noImplicitAny": true,
      "target": "es6",
      "types": [
         "node"
      ],
      "paths": {
         "*": [
            "node_modules/*"
         ]
      }
   },
   "include": [
      "src/**/*"
   ]
}

```

I would assume some of these properties:
```json
      "esModuleInterop": true,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "target": "es6",
```

Sometimes such strange errors just disappear when deleting `node_modules` folder and install the dependencies again.

**Comment by zefexdeveloper** [comment]
@btxtiger I tried to use your settings but it still doesn't work, I deleted the `node_modules` and even cleaned the `yarn` cache and installed again and nothing.
Do you have a boilerplate repository with that set up so I can try to run and see if it works here?

**Comment by havenchyk** [comment]
@zefexdeveloper did you solve your problem?

**Comment by alex-zukitek** [comment]
@zefexdeveloper Same error, did you solve it?

**Comment by btxtiger** [comment]
Do you have typescript installed? Make sure it is installed explicitly as dependency or dev-dependency

**Comment by havenchyk** [comment]
@alex-zukitek @Abrissirba could you please create a small repo to reproduce the problem?

**Comment by lukejagodzinski** [comment]
I have the similar error but stating `SyntaxError: Unexpected token import` and it's being thrown on `typeorm migration:generate -n UserRefactoring`

**Comment by pleerock** [comment]
Guys, I believe this problem happen when `typeorm migration:run` tries to execute `.ts` files. Try to change your ormconfig and specify only `.js` files in there.

**Comment by havenchyk** [comment]
After reading many similar issues, I have the same presumption ^^

**Comment by btxtiger** [comment]
I'm using migration with .ts files and it works without any problems.
```ts
// package.json->scripts
"db:migrate": "npx ts-node ./node_modules/.bin/typeorm migration:run -f ormconfig-cli",
```

```ts
// ormconfig-cli.ts
import { SnakeNamingStrategy } from './src/database/snake-naming.strategy';

module.exports = {
   type: 'mysql',
   host: 'localhost',
   port: 3306,
   username: 'root',
   password: '123456789',
   database: 'mydb',
   synchronize: false,
   logging: true,
   maxQueryExecutionTime: 100,
   namingStrategy: new SnakeNamingStrategy(),
   entities: ['src/database/entity/**/*.ts'],
   migrations: ['src/database/migration/**/*.ts'],
   subscribers: ['src/database/subscriber/**/*.ts'],
   cli: {
      entitiesDir: 'src/database/entity',
      migrationsDir: 'src/database/migration',
      subscribersDir: 'src/database/subscriber'
   }
};

```

**Comment by AhmadDeel** [comment]
after long I installed ts-node typescript typeorm globally and use
`ts-node ./node_modules/typeorm/cli.js  migration:generate -n new1`
command things start to work

**Comment by lukejagodzinski** [comment]
I solved my problem by installing ts-node as dev dependency:
```
npm i -D ts-node
```
and later by adding script to `package.json` file:
```js
{
  /* ... */
  "scripts": {
    /* ... */
    "typeorm": "ts-node ./node_modules/.bin/typeorm"
  }
}
```
Now you can invoke any typeorm CLI command in the following way:
```sh
npm run typeorm -- migration:generate -n MigrationName
```

**Comment by AhmadDeel** [comment]
> I solved my problem by installing `ts-node` as a dev dependency:
> 
> ```
> npm i -D ts-node
> ```
> and later by adding script to `package.json` file:
> 
> ```js
> {
>   /* ... */
>   "scripts": {
>     /* ... */
>     "typeorm": "ts-node ./node_modules/.bin/typeorm"
>   }
> }
> ```
> 
> Now you can invoke any typeorm CLI command in the following way:
> 
> ```shell
> npm run typeorm -- migration:generate -n MigrationName
> ```

I tried that and even changed the script to mine that was working
(`ts-node ./node_modules/typeorm/cli.js migration:generate -n new1`)
and typed `npm run typeorm ` with no lock.
the scipt it tries to run is
``ts-node ./node_modules/typeorm/cli.js "migration:generate" "-n" "MigrationName"``
why put them in quotations.

**Comment by EngrKhizarIqbal** [comment]
> > I solved my problem by installing `ts-node` as a dev dependency:
> > ```
> > npm i -D ts-node
> > ```
> > 
> > 
> > and later by adding script to `package.json` file:
> > ```js
> > {
> >   /* ... */
> >   "scripts": {
> >     /* ... */
> >     "typeorm": "ts-node ./node_modules/.bin/typeorm"
> >   }
> > }
> > ```
> > 
> > 
> > Now you can invoke any typeorm CLI command in the following way:
> > ```shell
> > npm run typeorm -- migration:generate -n MigrationName
> > ```
> 
> I tried that and even changed the script to mine that was working
> (`ts-node ./node_modules/typeorm/cli.js`)
> and typed `npm run typeorm ` with no lock.
> the scipt it tries to run is
> `ts-node ./node_modules/typeorm/cli.js "migration:generate" "-n" "MigrationName"`
> why put them in quotations ???
> 
> Update:
> solved by removing `"esModuleInterop": true,` from tsconfig
> but still, I have to put all script in scripts section
> I mean `npm run typeorm -- migration:generate -n MigrationName`
> translated to `ts-node ./node_modules/typeorm/cli.js "migration:generate" "-n" "MigrationName"`
> thanks

.\node_modules\.bin\ts-node ./node_modules/typeorm/cli.js migration:generate -n MigrationName worked for me. I've installed ts-node locally.

**Comment by FrancisNaN01** [comment]
when i want to install migration they told me the error:



 missing script: typeorm

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/francis/.npm/_logs/2020-02-12T18_52_29_672Z-debug.log



cold me help me please

**Comment by btxtiger** [comment]
@FrancisNaN01 what is the full command you are running? Seems there is a synatx error

**Comment by DarkLite1** [comment]
Very strange, on Windows this command runs flawless:

```js
./node_modules/.bin/ts-node ./node_modules/typeorm/cli.js migration:generate -n MigrationName -c ConnectionName
```

But when adding the same to scripts:
```js
  "scripts": {
    "typeorm": "./node_modules/.bin/ts-node ./node_modules/typeorm/cli.js"
  }
```

This fails:
```js
npm run typeorm migration:generate -n MigrationName -c ConnectionName
```

It feels like it's not passed on correctly the arguments.

**Comment by vlardeo** [comment]
Solution by @AhmadDeel helped me
https://github.com/typeorm/typeorm/issues/3079#issuecomment-449719368

**Comment by MounirOnGithub** [comment]
I've encountered this issue and my configuration is working fine here are my package.json, tsconfig.json and the -d file for DataSource

package.json 
```json
{
  "name": "api",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "typeorm": "typeorm-ts-node-esm",
    "fixtures:load": "npx ts-node src/fixtures/load-fixtures.ts",
    "fixtures:clear": "npx ts-node src/fixtures/load-fixtures.ts clear",
    "fixtures:reset": "npx ts-node src/fixtures/load-fixtures.ts reset",
    "migrate:run": "npx ts-node -r tsconfig-paths/register node_modules/typeorm/cli.js migration:run -d src/utils/data-source.ts",
    "migrate:run:prod": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:run -d ./src/utils/data-source.ts"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/typeorm": "^11.0.0",
    "pg": "^8.13.1",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1",
    "typeorm": "^0.3.20"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/config": "^4.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^5.0.0",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^8.0.0",
    "@typescript-eslint/parser": "^8.0.0",
    "eslint": "^8.0.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^7.0.0",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.2",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es6",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
    "types": [
      "node",
      "jest",
    ],
    "paths": {
      "*": [
        "node_modules/*"
      ],
      "src/*": ["src/*"]
    }
  },
  "include": ["src/**/*", "test/**/*"],
}

```

src/utils/data-source.ts
```typescript
import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';

dotenv.config();

const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432', 10),
  username: process.env.DB_USER || 'nestuser',
  password: process.env.DB_PASS || 'nestpass',
  database: process.env.DB_NAME || 'nestdb',
  synchronize: false,
  logging: true,
  entities: ['src/**/*.entity.ts'],
  migrations: ['src/migrations/*.ts'],
});

export default AppDataSource;
```


Hope it will helps someone
