### ISSUE TITLE
Inner joining to left joined table returns 0 rows

### ISSUE THREAD

**Issue by harm-less** [typeorm/typeorm#3080]
**Issue type:**

[ ] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.4`

**Steps to reproduce or a small repository showing the problem:**

Hey,
We ran into a problem with joining some relations and getting 0 results. The problem (and the solution) is described best in this [StackOverflow](https://stackoverflow.com/questions/28590173/sql-inner-joining-to-left-joined-table).

I, therefore, don't know if this should be considered a bug or a feature request, because the order of the `ON` keywords and joins seems to matter in this instance as can be seen from the accepted answer in the StackOverflow question.

I guess a solution could be to move the `ON` logic to underneath all the `LEFT` and `INNER` joins and reverse the order. Or would this be too simple if there's a whole bunch of joins instead of just 2?

For the time being, we're planning on making sure the child relations are always `LEFT JOIN` instead of 'INNER JOIN' so at least we're getting our results. This will give artefacts, but the amount of instances in our codebase like this at the moment is not that high.

Thanks in advance!

**Comment by Kononnable** [comment]
@harm-less 
Without code snippet, generated query and query you want to generate we wont't be able to help.

**Comment by pleerock** [comment]
@harm-less did you find a solution for your issue?

**Comment by harm-less** [comment]
I didn't yet, I'm still trying to find time to properly reply to this threat but other priorities keep coming up at work atm.

**Comment by pleerock** [comment]
let me close this issue then, create a new one with additional information once you'll have a time
