### ISSUE TITLE
Transaction with arrays

### ISSUE THREAD

**Issue by univerze** [typeorm/typeorm#3084]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Is there a way to add queries from array.map to a transaction? I have tried both approach in the transactions doc but I always get "Query runner already released. Cannot run queries anymore." error.

```ts
const queryRunner = getConnection().createQueryRunner();

await queryRunner.startTransaction();

try {
    const manager = queryRunner.manager;

    // update name, members and custom field values
    await manager.save(EntryEntity.create({
        id: entry.id,
        name: data.name,
        members: data.members.map(id => ({ id })),
        fieldValues: data.customFields,
    }));

    if (!entryCompleted) {
        await data.documents.map(async document => {
            const docToSave = { ...document, entryId: entry.id };
            // executes the first iteration and then fails
            if (!document.id) {
                await manager.save(DocumentEntity.create(docToSave)); // create new
            } else if (document.id) {
                const origin = entries.documents.find(doc => doc.id === document.id);
                if (origin.status === 0) {
                    await manager.save(Document.create(docToSave)); // update existing
                }
            }
        });
    }

    await queryRunner.commitTransaction();
} catch (err) {
    await queryRunner.rollbackTransaction();
} finally {
    await queryRunner.release();
}
```
Without the documents.map it works as expected, updates the entry name, members and fieldValues but it returns too early from the loop.

Do you have any suggestions please?
Thanks.

**Comment by Kononnable** [comment]
`Array.map()` is not awaitable - it doesn't return promise. You should use `Promise.all()`.

**Comment by havenchyk** [comment]
I'm closing this issue for housekeeping purposes, if something is not clear yet, just continue the conversation or post a message in slack
