### ISSUE TITLE
How do you create a new bit field using default?

### ISSUE THREAD

**Issue by ccarbonellbh** [typeorm/typeorm#3085]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. Create an Entity class with a mssql typeORM configuration
2. Synchronize to create the table for your entity
3. Attempt to add a new bit field to the entity using a default and synchronize

I am trying to create a new bit field on my User class by using the synchronize feature and I keep running into this error ```QueryFailedError: Error: ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Column 'enabled' cannot be added to non-empty table 'User' because it does not satisfy these conditions.```

Since I'm using mssql, the field would be a bit and I have tried the following with no luck:
```
@Column({ default: 'true' })
    enabled: boolean;

@Column({ default: true })
    enabled: boolean;

@Column({ default: '1' })
    enabled: boolean;

@Column({ default: 1 })
    enabled: boolean;
```
Am I doing something incorrectly, or is this possibly a bug? Thank you for your help

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by btxtiger** [comment]
Did you try it this way? In MySQL you would store a boolean as `tinyint`, which results in type number. I guess it should work for MSSQL in the same way.
```ts
@Column('bit', { default: 1 })
   enabled: number;
```

**Comment by ccarbonellbh** [comment]
Thanks for the suggestion! Still no luck that way either though :(

**Comment by btxtiger** [comment]
Does it fail with the same error? What happens if you don't set a default or you set type to :any instead number?

**Comment by ccarbonellbh** [comment]
Yep, it fails with the same error. Same with not using default and with using :any

**Comment by pburrows** [comment]
I am experiencing the same issue. I am trying to add a new column to a pre-existing entity, defined like this:

```
    @Column({type: 'bit', default: true})
    public isRequired: boolean;
```

yet the SQL that TypeOrm generates and tries to run is this:

```
ALTER TABLE "PayCategoryNoteSettingRecords" ADD "isRequired" bit NOT NULL
```

Note the lack of a DEFAULT keyword in the sql statement.

This behaves the same if I put true or 1 or false or 0, it does not try to set the default at all.

**Comment by hoonoh** [comment]
for me it worked with following syntax:
```typescript
@Column({
  type: 'bit',
  default: "b'1'",
  transformer: {
    from: (v: Buffer) => !!v.readInt8(0),
    to: (v: boolean) => v,
  },
})
booleanValue: boolean;

```

**Comment by imnotjames** [comment]
This seems to be resolved in the latest release.
