### ISSUE TITLE
.find() Oracle returning wrong data.

### ISSUE THREAD

**Issue by destinatus** [typeorm/typeorm#3089]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Connect to oracle database.
Create @EntityRepository and extending Repository.
Call this repository using await getCustomRepository(<repoName>).find();

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
@destinatus 
Are you passing any parameters to find method? Does the behavior change if you use extended repository not standard one?

**Comment by destinatus** [comment]
No parameters.
I will test different repository.

**Comment by Kononnable** [comment]
Closing as no response from the author.
