### ISSUE TITLE
@RelationId delete cascade

### ISSUE THREAD

**Issue by TheNoim** [typeorm/typeorm#3090]
**Issue type:**

[ ] question
[X] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

There is currently no option to add `ON DELETE CASCADE` if you use @RelationId

This could lead to the following problem:

```typescript

@Entity()
export class Debt {
    @RelationId((debt: Debt) => debt.debtor)
    debtorId: number;
}

@Entity()
export class Debtor {
    @OneToMany(type => Debt, debt => debt.debtor, {
        nullable: true,
        onDelete: 'CASCADE',
        cascade: true
    })
    debts?: Debt[];
}

```

Now If you try to delete an debtor, it will fail, because the constrain on the debt table for the RelationId does not have `ON DELETE CASCADE`

```sql
CONSTRAINT "FK_5ea1d47fdfc1abc79ebf3cfa954" FOREIGN KEY ("debtorId")
      REFERENCES public.debtor (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
``` 

There should be an option to change it to

```sql
CONSTRAINT "FK_5ea1d47fdfc1abc79ebf3cfa954" FOREIGN KEY ("debtorId")
      REFERENCES public.debtor (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
```

I am not experienced enough in typescript to even find anything in this source code allowing me to make a pull request. Someone else need to do this.

**Comment by syuilo** [comment]
any updates?

**Comment by dantman** [comment]
Wouldn't this be fixed by using a `debtor` prop with `@ManyToOne` on the Debt entity? Isn't RelationId normally used in addition to the relation object/entity prop?
