### ISSUE TITLE
New find options operators >= and <=

### ISSUE THREAD

**Issue by NiKlimenko** [typeorm/typeorm#3092]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

All

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Would be nice to see these operators <= (less than or equal to) and >= (more than or equal to) in TypeORM. A lot of cases require these operators.

**Comment by NiKlimenko** [comment]
@dhritzkiv nice idea, thank you. But it would be better if there was some short alias.

**Comment by dhritzkiv** [comment]
Definitely. It also is a lot more verbose when it gets converted to SQL, which is not great when when creating a large update/query with thousands of where clauses.

`NOT ("y" LESS THAN x)` is 21 chars vs `"y" >= x` at 8 chars: About 2.5 larger.

**Comment by johannesschobel** [comment]
i would also vote for a `LessThanOrEqual()` and `MoreThanOrEqual()` operators.. Can we please have this? @pleerock 

Maybe I can contribute via PR?

**Comment by Kononnable** [comment]
@johannesschobel 
Contributions are always welcomed. But you need to check `next` branch first - there were some big changes in find options(but I didn't have the time to check them myself yet).

**Comment by pleerock** [comment]
I don't like those operators TBH but I think we can add it. And yeah, its better to do it against `next` branch since there are some core changes in there, don't wanna die in conflicts fix later on.

**Comment by johannesschobel** [comment]
@pleerock there are a lot of use-cases where you need a  `>=` or `<=`, respectively!

I will try to figure out how to add those new operators to the `FindOptions` - hopefully i have some spare time over christmas holidays..

**Comment by pleerock** [comment]
@johannesschobel sounds great!

**Comment by roopamedisetti1** [comment]
how can I use something like where : { createdAt : moreThan(startDate)  , createdAt : lessThan(endDate) }
Any help would be appreciated

**Comment by dhritzkiv** [comment]
@roopamedisetti1 I don't believe you can use the object literal form, you'll have to use the string form:

```ts
qb.andWhere("createdAt > :startDate AND createdAt < :endDate", {
    startDate,
    endDate,
})
``` 

---

or alternatively, this fairly verbose object literal form:

```ts
qb
.where({createdAt : moreThan(startDate)})
.andWhere(new Brackets(qb3 => {
    qb3.where({
        createdAt : lessThan(endDate)
    })
});
```

I'm not sure why one can't use the object literal form in `.andWhere`, `.orWhere`, etc.

**Comment by roopamedisetti1** [comment]
Thank you for your message. Yes Need to use createQueryBuilder instead of find on repository

**Comment by sushma-hegde-coder** [comment]
i want to get some records according to toDate and fromDate. If I want to get the data of one day, both to and from dates are same. I tried with query builder and used 
       .where('post.createdAt >= :from', { from: fromDate })
      .andWhere('post.createdAt <= :to', { to: toDate })
here if I give to and from dates as same, I'm not getting any data. If I give toDate as next date then only I'm getting some data. Here < and <= are giving same data only. 
I tried using moreThanOrEqual operator with query builder. But it is throwing error.
       .where({ 'post.createdAt': MoreThanOrEqual('2021-09-29') })
      .andWhere({ 'post.createdAt': LessThanOrEqual('2021-09-30') })
Can some please tell me how to get the data if to and from date are same
