### ISSUE TITLE
Column Type 'rowversion' not supported in mssql

### ISSUE THREAD

**Issue by pburgmer** [typeorm/typeorm#3098]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Error Message:**
[Nest] 21844   - 11/12/2018, 2:45:41 PM   [TypeOrmModule] Unable to connect to the database. Retrying (2)... +3007ms
DataTypeNotSupportedError: Data type "rowversion" in "LanguageImpl.rowversion" is not supported by "mssql" database.

According to https://github.com/typeorm/typeorm/blob/master/test/functional/database-schema/column-types/mssql/column-types-mssql.ts rowversion should be supported in mssql

**Steps to reproduce or a small repository showing the problem:**
My project is quiet simple, but I can not share the code. I have no references, just a simple table with some string and number columns. Haven't tried to reproduce it with another application yet.

**Comment by vlapo** [comment]
Hi @pburgmer,

I am sure this should be fixed in latest version (now 0.2.9) of typeorm. Could you test it and close issue if it is ok?

**Comment by pleerock** [comment]
Yeah it should be fixed, let us know if you still have issues.
