### ISSUE TITLE
What is the best pattern to implement polymorphic associations

### ISSUE THREAD

**Issue by jtushman** [typeorm/typeorm#3099]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

(Concept also mentioned in #1502)

Hi Team,

Really enjoying working with TypeORM.  I know that TypeORM does not currently have native support for polymorphic associations.  My question here **what is the best pattern to implement polymorphic associations**  give the current API.

(if we like the approach eventually outlined on this issue, I would be happy to make a documentation PR)

### Consider the Following

Entities **Subjects** and **Events** can have **Reminders** for a given **User**

```ts
export interface IRemindable {
  reminders: Reminder[];
  id: string;
}

@Entity()
export class Reminder {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  targetType: string;

  @Column('uuid')
  targetId: string;

  @ManyToOne(() => User, (user: User) => user.reminders)
  user: User;

}

```

```ts
export class Subject implements IRemindable {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // Pretty sure that the inverse side of this is wrong
  @OneToMany(() => Reminder, (reminder: Reminder) => reminder.targetId)
  reminders: Reminder[];
}
```

```ts
export class Event implements IRemindable {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // Again, Pretty sure that the inverse side of this is wrong
  @OneToMany(() => Reminder, (reminder: Reminder) => reminder.targetId)
  reminders: Reminder[];
}
```

Some queries work, well such as:

```ts
    // gets the user and their reminders 
    const userRepo = conn.getRepository(User);
    user = await userRepo.findOne({
      where: { user },
      relations: ['reminders']
    });
```

and 

```ts
   // get all reminders of type subject
   reminder = await reminderRepo.findOne({
      targetType: 'Subject'
    });
```

**But I can't get to work nicely from the polymorphic end.**

```ts
    // what I want this do to is get the subject, and its associated reminders (this doesn't work)
    const rocketRaw = await subjectRepo
      .createQueryBuilder('subject')
      .leftJoinAndSelect(Reminder, 'reminder', 'reminder."targetId" = subject.id')
      .getOne();
```

^--- that gets the results but only with the **`getRawOne`** and I would then need to do manual mapping.

It would be amazing if we could do (but this does not work: `Cannot read property 'joinColumns' of undefined`):

```ts
    subject = await subjectRepo.findOne({
      where: { user },
      relations: ['reminders']
    });
```

**What is the best pattern to implement this?**

I am sure there can be some significant improvements to the code I provided

-----

One thing that I was thinking was to make a "derived column" in Subject that looks something like (but this also yielded the same `joinColumns` message)

```ts
  async target() {
    const targetRepo = getConnection().getRepository(this.targetType);
    return await targetRepo.findOneOrFail(this.targetId);
  }

  // then we could potentially do
  @OneToMany(() => Reminder, (reminder: Reminder) => reminder.target)
  reminders: Reminder[];
```

Thanks everyone!

**Comment by dhritzkiv** [comment]
I don't have an answer for you, but would something like `leftJoinAndMapMany` work for your requirements?

**Comment by dhritzkiv** [comment]
Also, try changing your `rocket` query to:

```ts
const rocketRaw = await subjectRepo
      .createQueryBuilder('subject')
      .leftJoinAndSelect("subject.reminders", 'reminder', 'reminder."targetId" = subject.id')
      .getOne();
```

**Comment by greghart** [comment]
While it may not be ideal to change your schema due to an ORM issue, there is the possibility of "Table Per Type" (https://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-2-table-per-type-tpt)

Here, instead of storing everything in one table, you store each class and subclass in its' own table. This has the advantage of relations being fully enforceable through foreign key constraints. Then instead of a type/id descriptor, you have a first class entity representation that relationship.

I implemented this in my project for "commentable", and TypeORM does a good job of making the additional overhead of separate tables not too big a deal.

====

```typescript
/**
 * Remindable supertable to model polymorphic reminder associations
 */
@Entity()
class Remindable {
  @PrimaryGeneratedColumn()
  id: number;

  // This column isn't necessary, but makes it slightly easier to track what
  // entities have been setup for reminders at a glance.
  @Column()
  descriptor: string;

  @OneToMany(type => Reminder, reminder => reminder.remindable)
  reminders: Reminder[];
}

@Entity()
class Reminder {
  // ...
  // instead of type descriptor, now we just have a remindable relationship
  @ManyToOne(type => Remindable, remindable => remindable.reminders)
  remindable: Remindable;
}

// Now "Remindable" owns all the reminders, and we can just link other entities one-to-one
@Entity()
class Event {
  // ...
  @OneToOne(type => Remindable, { nullable: true })
  @JoinColumn()
  remindable?: Remindable;
}

@Entity()
class Subject {
  // ...
  @OneToOne(type => Remindable, { nullable: true })
  @JoinColumn()
  remindable?: Remindable;
}

// Note I have them as optional, so before a first reminder you must setup the remindable. I do this with a custom repository to "findOrGetRemindable" basically, but you could also automatically set up the remindable for each entity on save or something.

@EntityRepository(Reminder)
export default class ReminderRepository extends Repository<Reminder> {

  /**
   * Find or get the remindable instance for an entity
   *
   * @returns a remindable that will be attached to the entity
   */
  async findOrGetRemindable<E extends { id: any, remindable?: Remindable }>(entity: E) {
    // Find an existing remindable, if any
    let remindable = entity.remindable ?
      entity.remindable :
      get(await
        this.manager.getRepository(entity.constructor)
        .createQueryBuilder('entity')
        .innerJoinAndSelect('entity.remindable', 'remindable')
        .getOne()
      , 'remindable');
    if (!remindable) {
      remindable = new remindable();
      remindable.descriptor = `${entity.constructor.name}-${entity.id}`;
      await this.manager.save(remindable);
      entity.remindable = remindable;
      await this.manager.save(entity);
    }
    return remindable;
  }
}   
```

Hope this helps!

**Comment by fullofcaffeine** [comment]
I'm also interested in this, coming from a Rails background. I like @greghart's approach, but it'd be nice to know what the maintainers/creators of TypeORM have in mind as well. 

I see @pleerock commented here: https://github.com/typeorm/typeorm/issues/1502#issuecomment-361874790, but there's no actual example of how to do it. It'd be nice to have them in some kind of examples/cookbook section of the manual (EDIT: Seems to fit well in the "Advanced Topics" section).

Cheers!

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
