### ISSUE TITLE
default is not setting default value in MySQL

### ISSUE THREAD

**Issue by TylerDev6** [typeorm/typeorm#31]
@Column({ default: "initialized" })
    public status: string;

This annotation in my class is returning the following in the SQL:

`status` varchar(255) NOT NULL,

**Comment by pleerock** [comment]
I have significantly refactored schema creation (including default value update) in the latest changes, but I didn't release a new version yet. Planning to release it next week, are you okay to wait for it?

**Comment by TylerDev6** [comment]
Yes, of course :) I just pre-populated my test data for now

**Comment by 19majkel94** [comment]
I have the bc8b604 version compiled but the issue still exist. Have you repaired this or only "TODO" in future?

Also the `@Index({ unique: true })` doesn't create UNIQUE when using as property decorator, only as class decorator.

**Comment by 19majkel94** [comment]
The `@Column({ unique: true })` works ok, so there's a workaround.

**Comment by pleerock** [comment]
fixed in `0.0.3-alpha.15`, feel free to reopen it if it still something not working
