### ISSUE TITLE
Add "conditional" method to query builder

### ISSUE THREAD

**Issue by lazarljubenovic** [typeorm/typeorm#3103]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:** All

**Steps to reproduce or a small repository showing the problem:**

I often conditionally add certain statements from the query based on some parameters. Those parameters in my case usually come from the query strings in a RESTful API, but the same could apply to many other use-cases.

For example:

```ts
const query = somehow
  .createQueryBuilder('users')
  .where(`user.deletedAt IS NOT NULL`)

if (params.hasImage) {
  query.andWhere(`user.image IS NOT NULL`)
}

if (params.q != '') {
  query.andWhere(`user.name LIKE :q`, { q: params.q })
}

const users = await sql.getMany()
```

This quite breaks the flow of the nice fluid chainable API that the query builder has. I propose a method `.if` or `.conditional` which accepts two arguments and then runs one of the given functions based on the given condition. 

```ts
const users = await somehow
  .createQueryBuilder('users')
  .where(`user.deletedAt IS NOT NULL`)
  .if(params.hasImage, query => query.andWhere(`user.image IS NOT NULL`))
  .if(params.q != '', query => query.andWhere(`user.username LIKE :q`, { q: params.q }))
  .getMany()
```

`.if` could accept a third argument which would be an `else` branch.

Thoughts?

**Comment by Kononnable** [comment]
I'm not sure if it wouldn't make code less readable. We would introduce two/three parameters and lines will become very long.
Why not use plain ifs?
```typescript
let query = somehow
  .createQueryBuilder('users')
  .where(`user.deletedAt IS NOT NULL`);
if(params.hasImage)
  query=query.andWhere(`user.image IS NOT NULL`);
if(params.q != '')
  query=query.andWhere(`user.username LIKE :q`, { q: params.q });
const users = query.getMany();
```

**Comment by pleerock** [comment]
@lazarljubenovic I completely understand your request and wanted this functionality for years, but when it comes to implementation another understanding comes: 

* it cover only some cases, when you'll have more non-trivial cases you'll have to fallback to if/else statements, and mixing both approaches isn't that fun anymore
* as @Kononnable mentioned it can be less readable, it works good mostly for a very short conditions and queries
* it breaks query builder semantics a bit since `if` isnt about building query
* it will bring lot of new questions regarding to this functionality and its inflexibility in the future

**Comment by Kononnable** [comment]
Ok, so what should we do with that issue? Should we mark it to be implemented in the future or decide it is too complicated to implement right now and close it?

**Comment by pleerock** [comment]
Yes let's close it for now, feel free to left your thoughts on this topic!

**Comment by ejoc** [comment]
it could be something like skipUndefined() of objectionjs where skip where clause with undefinded parameters

**Comment by irissoftworks** [comment]
Hey guys, I was wondering about this, I'm not sure if typeorm already has something similar, but have u guys looked at how knex / objection do this with modify ? 
Just my two cents, but I find it quite readable ?

```
Match.query(trx)
      .eager("[homeClub, awayClub]")
      .modify(primaryKeyFilter({ id }))
      .modify(competitionIdFilter({ competitionId }))
      .modify(seasonIdFilter({ seasonId }))
      .modify(firstFilter({ first }));
```

The trick here is that if the modify function returns false it doesn't do anything, so the composable higher order filter functions can take care of handling that. This allows for building one single query that can take a lot of different filters, which plays well with graphql and other more dynamic apis.

**Comment by cjmyles** [comment]
Until something like this is implemented I'm using something like the following.
```
.andWhere(status ? `status = :status` : '1=1', { status })
```

**Comment by vlio20** [comment]
Another option would be: 
```
const where = whereUsed ? qb.where.bind(qb) : qb.andWhere.bind(qb);
where(...)
```

**Comment by DrecDroid** [comment]
https://laravel.com/docs/5.8/queries#conditional-clauses

**Comment by mykyta-Koptsov** [comment]
you cant try to use 
const users = await somehow
  .createQueryBuilder('users')
  .where(`user.deletedAt IS NOT NULL`)
  .andWhere(params.hasImage ? `user.image IS NOT NULL` : null)
  .getMany();

**Comment by kkoomen** [comment]
I don't know why @DrecDroid got so many downvotes because laravel has probably one of the most advanced and developer-friendly query builders out there. I do suggest that we add a `.when()` equivalent inside TypeORM based on how laravel does it.

**Comment by umutyerebakmaz** [comment]
`@Authorized()
    @Query(() => [Coordinate])
    async coordinates(
        @Arg(‘filter’) filter: CoordinateFilterInput,
    ): Promise<Coordinate[]> {

        if (filter.keyword) {
            return await this.coordinateRepo.find({
                where: title ILIKE '${filter.keyword}%' OR description ILIKE '${filter.keyword}%',
                order: { updatedAt: “DESC” },
                skip: filter.skip,
                take: filter.take,
            });
        }

        if (filter.title) {
            return await this.coordinateRepo.find({
                where: title ILIKE '${filter.title}%',
                skip: filter.skip,
                take: filter.take,
            });
        }

        if (filter.description) {
            console.log(‘description’)
            return await this.coordinateRepo.find({
                where: description ILIKE '${filter.description}%',
                skip: filter.skip,
                take: filter.take
            });
        }

        if (filter.title && filter.description) {
            console.log(filter.title, filter.description);
            return await this.coordinateRepo.find({
                where: title ILIKE '${filter.title}%' OR description ILIKE '${filter.description}%',
                skip: filter.skip,
                take: filter.take
            });
        }

        if (filter.sourceList) {
            const coordinate_source = await getConnection().createQueryBuilder(CoordinateSource, “cs”)
                .where(“cs.sourceId IN (:...sourceIds)“, { sourceIds: filter.sourceList })
                .skip(filter.skip)
                .take(filter.take)
                .getMany();

            const ids = coordinate_source.map(cs => cs.coordinateId);
            console.log(ids);

            const coordinates = await this.coordinateRepo.findByIds(ids, {
                skip: filter.skip,
                take: filter.take,
            });

            return coordinates;
        }

        if (filter.insectList) {
            const coordinate_insect = await getConnection().createQueryBuilder(CoordinateInsect, “ci”)
                .where(“ci.insectId IN (:...insectIds)“, { insectIds: filter.insectList })
                .skip(filter.skip)
                .take(filter.take)
                .getMany();

            const ids = coordinate_insect.map(cs => cs.coordinateId);
            console.log(ids);

            const coordinates = await this.coordinateRepo.findByIds(ids, {
                skip: filter.skip,
                take: filter.take,
            });

            return coordinates;
        }

        else {
            return await this.coordinateRepo.find({
                order: { updatedAt: “DESC” },
                skip: filter.skip,
                take: filter.take
            });
        }

    }`

I've been searching for days, there is no way I haven't tried. repository, .andWhere. .orWhere doesn't get dynamic whatever I do. I have 5 parameters, I think it should not be that long to write a query with these 5 parameters. please someone help.

**Comment by neekey** [comment]
the `where` and `andWhere` switch is a pain in the ass to me

**Comment by lionipsum** [comment]
Same

**Comment by lionipsum** [comment]
> atus })
I was inspired by this solution so I thought I would share another solution using CASE
```
qb.andWhere(`CASE
    WHEN entity.status = '${StatusEnum.FOOBAR}'
    THEN entity.endsAt > now()
    ELSE 1=1
    END`)
 ```

**Comment by jojoldu** [comment]
I've been developing in Java before, and Java's Querydsl (entity framework) supports dynamic queries in the following ways.

If null is received, the corresponding `andWhere` / `orWhere` condition is not added to the conditional statement.

```javascript
    findAllByDto (dto: ArticleSearchDto) {
        return createQueryBuilder()
            .select("article")
            .from(Article, "article")
            .andWhere(this.eqTitle(dto.title))
            .andWhere(this.eqAuthor(dto.author))
            .orderBy("article.id desc")
            .getMany();
    }

    private eqTitle(title: string): string {
        if(!title) {
            return null;
        }

        return `article.title = :${title}`;
    }
```

I sent a PR to make it this way, but everyone is curious about their opinions.

https://github.com/typeorm/typeorm/pull/7684

**Comment by Heniker** [comment]
Another way to do it:

```js
const users = await somehow
  .createQueryBuilder('users')
  [param?.user ? 'where' : 'printSql']('user.username LIKE :q', param)
  .getMany()
```

It breaks types and arguably even less readable, so still rooting for `.if` method.

**Comment by Heniker** [comment]
Another way to do it:

```js
const users = await somehow
  .createQueryBuilder('users')
  [param?.user ? 'where' : 'printSql']('user.username LIKE :user', param)
  .getMany()
```

It breaks types and arguably even less readable, so still rooting for `.if` method.

**Comment by alanscordoba** [comment]
I add another way to do it
```
const users = await somehow
  .createQueryBuilder ('users')
  .where(param.user != null ? 'user.username LIKE :user' : 'false', {user:param.user}) 
  .getMany ()
```

**Comment by adamrehill** [comment]
While it might not be the best solution, I was able to add a monkey patch to achieve this:

```
declare module 'typeorm/query-builder/SelectQueryBuilder' {
  interface SelectQueryBuilder<Entity> {
    whereOptional(this: SelectQueryBuilder<Entity>, where: string, optionalValue: any): SelectQueryBuilder<Entity>
  }
}

SelectQueryBuilder.prototype.whereOptional = function <Entity>(this: SelectQueryBuilder<Entity>, where: string, optionalValue: any): SelectQueryBuilder<Entity> {
  if(optionalValue) {
    return this.where(where, optionalValue);
  }
  return this;
}
```

and then I repeated the same for things like orWhere(), etc.

**Comment by adamrehill** [comment]
While it might not be the best solution, I was able to achieve something similar with a monkey patch.

``` typescript
declare module "typeorm/query-builder/SelectQueryBuilder" {
  interface SelectQueryBuilder<Entity> {
    andWhereOptional(this: SelectQueryBuilder<Entity>, andWhere: string | Brackets | ((qb: this) => string), parameters: ObjectLiteral): SelectQueryBuilder<Entity>;
  }
}

function hasUndefinedParameters(parameters: ObjectLiteral): boolean {
  if(!parameters) {
    return true;
  }

  for (const key of Object.keys(parameters)) {
    if (parameters[key] === undefined) {
      return true;
    }
  }
  return false;
}

/** If the any of the provided parameters are not present, will return
 *  the base query, otherwise will add the andWhere.
 */
SelectQueryBuilder.prototype.andWhereOptional = function <Entity>(this: SelectQueryBuilder<Entity>, andWhere, parameters): SelectQueryBuilder<Entity> {
  if (hasUndefinedParameters(parameters)) {
    return this;
  }

  return this.andWhere(andWhere, parameters);
};
```

This will let you do something like this (where name may not be present):

``` typescript
baseQuery.andWhereOptional('person.name = :name', { name });
```

The only caveat is that if you provide multiple values and _any_ of them are undefined it will return the baseQuery and ignore the andWhere.

**Comment by sallamTanna** [comment]
> I'm not sure if it wouldn't make code less readable. We would introduce two/three parameters and lines will become very long. Why not use plain ifs?
> 
> ```ts
> let query = somehow
>   .createQueryBuilder('users')
>   .where(`user.deletedAt IS NOT NULL`);
> if(params.hasImage)
>   query=query.andWhere(`user.image IS NOT NULL`);
> if(params.q != '')
>   query=query.andWhere(`user.username LIKE :q`, { q: params.q });
> const users = query.getMany();
> ```

This is correct, but you need to add **await** in the last line, like: const users = await query.getMany(); to get the results array.

**Comment by kubet** [comment]
For me multiple `andWhere` didn't work so I used one `andWhere` with `AND` in-between. In this case it would look like
```js
    let string = '';
    let params = {};

    if (params?.hasImage) {
      string += (string ? ' AND ' : '') + 'user.image IS NOT NULL';
      
    }
    if(params?.q){
      string += (string ? ' AND ' : '') + 'user.username LIKE :q';
      Object.assign(params, { q: params.q });
    }

  const query = await somehow
  .createQueryBuilder('users')
  .where(`user.deletedAt IS NOT NULL`)
  .andWhere(string, params)
  .getMany()

**Comment by emulienfou** [comment]
Based on @adamrehill example, here is the implementation of the `if` conditional based on [$if](https://koskimas.github.io/kysely/classes/SelectQueryBuilder.html#_if) from kysely package:
```ts
import { SelectQueryBuilder } from "typeorm";

declare module "typeorm/query-builder/SelectQueryBuilder" {
  interface SelectQueryBuilder<Entity> {
    if(
      this: SelectQueryBuilder<Entity>,
      condition: boolean,
      func: (qb: this) => SelectQueryBuilder<Entity>
    ): SelectQueryBuilder<Entity>;
  }
}

SelectQueryBuilder.prototype.if = function <Entity>(
  this: SelectQueryBuilder<Entity>,
  condition,
  func
): SelectQueryBuilder<Entity> {
  if (condition) return func(this);

  return this;
};

```

**Comment by jfoza** [comment]
```
declare module 'typeorm/query-builder/SelectQueryBuilder' {
  interface SelectQueryBuilder<Entity> {
    when(
      value: any,
      callback?: (qb: this, value?: any) => SelectQueryBuilder<Entity>,
      defaultCallback?: (qb: this, value?: any) => SelectQueryBuilder<Entity>,
    ): SelectQueryBuilder<Entity>;
  }
}

SelectQueryBuilder.prototype.when = function <Entity>(
  this: SelectQueryBuilder<Entity>,
  value: any,
  callback?: (
    qb: SelectQueryBuilder<Entity>,
    value?: any,
  ) => SelectQueryBuilder<Entity>,
  defaultCallback?: (
    qb: SelectQueryBuilder<Entity>,
    value?: any,
  ) => SelectQueryBuilder<Entity>,
): SelectQueryBuilder<Entity> {
  if (typeof value === 'function') {
    value = value(this);
  }

  if (value) {
    return callback ? callback(this, value) : this;
  } else {
    return defaultCallback ? defaultCallback(this, value) : this;
  }
};
```
