### ISSUE TITLE
Missing change log for version 0.2.9

### ISSUE THREAD

**Issue by dmitrirussu** [typeorm/typeorm#3108]
Where we can find more info about version 0.2.9?

**Comment by jraoult** [comment]
@dmitrirussu same problem for me. The best I could do so far is: https://github.com/typeorm/typeorm/compare/0aea5d001e0256246582fd88747f51fd9729fe2d...master but since the repo is not following any convention for the PR or commit naming it is not super useful.

**Comment by havenchyk** [comment]
Seems to be https://github.com/typeorm/typeorm/pull/3001, but it contains the only line.

@pleerock ?

**Comment by rustamwin** [comment]
this issue should be closed?

**Comment by pleerock** [comment]
actually I think 0.2.3 had more changes then what we have in `CHANGELOG` now.
