### ISSUE TITLE
orderBy() a casted column

### ISSUE THREAD

**Issue by aco711** [typeorm/typeorm#3109]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.9` (or put your version here)

Is it possible to orderBy a casted column? My column is stored as a string, but I am hoping to be able to cast as a float and then order by using .orderBy()

Example:
`return qb.take(100).orderBy('(CAST(alias.value AS DECIMAL(10,6))', 'DESC').getMany();`
This gives me the error:
`(CAST(alias\" alias was not found. Maybe you forgot to join it?"
`
Thanks!

**Comment by Kononnable** [comment]
@aco711 
Did you resolve your issue?
If not you should show us generated query and the one you want typeorm to generate.

**Comment by pleerock** [comment]
complex orderbys do not work with `take/skip`. Consider using `limit`/`offset` when you use complex orderbys.
