### ISSUE TITLE
Can one use TypeORM with db-specific datatypes, like Postgresql bit strings?

### ISSUE THREAD

**Issue by estaub** [typeorm/typeorm#311]
I keep needing/wanting to use Postgresql-specific features, and wonder to what extent it's feasible with TypeORM.  

My specific case at the moment is the [Postgresql "bit string" datatype](https://www.postgresql.org/docs/9.6/static/datatype-bit.html), which provides efficient storage and queries for boolean arrays.  

I'm fine with using workarounds of various sorts, within reason - I just don't know whether it will work at all.  For instance, if I hand-alter the schema to add a bit-string field, will TypeORM see it and immediately error out, or autosync it away?  Also, the data values for bit-strings have their own syntax (see link above) - is it possible to specify a bit-string field value, e.g., during an insert?

**Comment by pleerock** [comment]
Right now its not supported at least until you make some hack. However I understand that we need this functionality (providing custom type) however it brings some problems in schema sync process. I'll think how add this feature and resolve all related problems.

**Comment by pleerock** [comment]
all postgres-specific data types are supported in latest typeorm versions
