### ISSUE TITLE
Default null for timestamptz tries to set a string 'null' as default value

### ISSUE THREAD

**Issue by lazarljubenovic** [typeorm/typeorm#3112]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Code:

```ts
  @Column({
    type: 'timestamptz',
    default: null,
    nullable: true,
  })
  ignoredAt: Date
```

Generated query:

```sql
CREATE TABLE "friend_request" (
  "senderId"   uuid      NOT NULL,
  "receiverId" uuid      NOT NULL,
  "createdAt"  TIMESTAMP NOT NULL,
  "ignoredAt"  TIMESTAMP WITH TIME ZONE DEFAULT 'null',
  CONSTRAINT "PK_3480812cafecf9155f4658b35ec" PRIMARY KEY ("senderId", "receiverId")
)
```

Should be:

```sql
CREATE TABLE "friend_request" (
  "senderId"   uuid      NOT NULL,
  "receiverId" uuid      NOT NULL,
  "createdAt"  TIMESTAMP NOT NULL,
  "ignoredAt"  TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  CONSTRAINT "PK_3480812cafecf9155f4658b35ec" PRIMARY KEY ("senderId", "receiverId")
)
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by lazarljubenovic** [comment]
Thanks, that works. Is this expected documented behavior?

**Comment by hassanas** [comment]
> Try this:
> `default: ( ) => 'null',`

QueryFailedError: ER_INVALID_DEFAULT: Invalid default value for 'column_name'

**Comment by Bastian1998** [comment]
i have the same error but when i do default: () => 'CURRENT_TIMESTAMP' it generates this query : INSERT INTO "carts"("created_at", "updated_at", "user_id", "amount", "currency_code") VALUES (DEFAULT, DEFAULT, $1, $2, $3) RETURNING "id", "created_at", "updated_at", and adds 'null' in the database
