### ISSUE TITLE
[Find options] MySQL "where and" on same column

### ISSUE THREAD

**Issue by brosbunbo** [typeorm/typeorm#3113]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi there,

I'm wonder how I can turn simple sql query below:
```sql
select * from user where id < 10 and id in(1, 2, 3);
```
to typeorm find options: https://github.com/typeorm/typeorm/blob/master/docs/find-options.md

Thanks and Best Regards,

**Comment by jwhitmarsh** [comment]
One way would be to use [`QueryBuilder`](http://typeorm.io/#/select-query-builder):
```
const data = await connection
    .getRepository(User)
    .createQueryBuilder("user")
    .where("user.id < :id", { id: 10 })
    .andWhere("user.id in (:ids)", { ids: [1,2,3] })
    .execute();
```

You can get `getSql`, `getQuery`, or `getQueryAndParameters` to check the raw SQL that will be generated for a query:
```
const data = await connection
    .getRepository(User)
    .createQueryBuilder("user")
    .where("user.id < :id", { id: 10 })
    .andWhere("user.id in (:ids)", { ids: [1,2,3] })
    .getSql();

console.log(data); // <-- select * from user where id < $1 and id in($2);
```

**Comment by pbbisme** [comment]
find-options  use  **Raw**

const ids = [1,2,3];
const id =10;
const data=this.repository.find({where:{id:Raw(alias=>`${alias} < ${id} and ${alias} in (${ids})`)}})

**Comment by pleerock** [comment]
currently you can only use suggestions from above ^^

We need to introduce some new syntax to handle your case as well with find options.

**Comment by Ephys** [comment]
Can that new syntax just use the existing operator system?

```
where: {
  id: And(LessThan(3), MoreThan(1)),
}
```

```
where: And({
  id: LessThan(3),
}, {
  id: MoreThan(1),
})
```

**Comment by SimplyComplexable** [comment]
@pleerock Any update on this? I agree that adding an `And` operator would be the best option.

**Comment by ernaneluis** [comment]
any update?

**Comment by momopig** [comment]
any update?

**Comment by JeGwan** [comment]
Please. Apply And Or syntax. Like prisma do.

**Comment by mehtamanan** [comment]
+1

**Comment by lajcf** [comment]
+1

**Comment by JVMartin** [comment]
Would love to see this implemented.

**Comment by danielb7390** [comment]
No update?

**Comment by Minetorpia** [comment]
Can we get an update on if there are plans to implement this?

**Comment by depyronick** [comment]
+1

**Comment by benzittlau** [comment]
+1

**Comment by talShtark** [comment]
+1

**Comment by tony-tsx** [comment]
+1

**Comment by mbecker16** [comment]
+1

**Comment by revskill10** [comment]
Please, we need this.

**Comment by netojose** [comment]
+1

**Comment by balazsbencs-sc** [comment]
+1

**Comment by sicsemperego** [comment]
plz

**Comment by robert-buliga-be** [comment]
Any news on this feature?

**Comment by erfanyousefi** [comment]
you can use Between operator in typeorm like this: 
where: {
   id: Between(1, 3)
}

**Comment by maximelafarie** [comment]
For those still wondering if it's available or not, yes it is: 

```ts
const productUsers = await ProductRepository.findOne({
    select: {
        users: {
            id: true,
            firstName: true,
            lastName: true
        }
    },
    relations: { users: true },
    where: { 
        id: productId,
        users: {
            role: And(In(allowedRoles), Not(UserRole.CUSTOMER))
        }
    }
});
```

**Comment by sucheep-s** [comment]
```
const purchaseHistoryList = await this.purchaseHistoryRepository.find({
    where: {
      And({purchaseId:purchaseId}, {purchaseId: Not(0)})
    }
});
```

How to use it with the above condition ? It shows me error

''purchaseId' is declared but its value is never read.'

**Comment by sucheep-s** [comment]
Please help me correct the right syntax. I cannot find its document.

```
const purchaseHistoryList = await this.purchaseistoryRepository.find({
  where: {
    purchaseId: And({purchaseId:purchaseId}, {Not(0)})
  }
});
```

**Comment by Repeat-swell** [comment]
@jwhitmarsh https://lnkr.fun/234d4ff
