### ISSUE TITLE
Integrating working typeorm project into existing Angular 7 project

### ISSUE THREAD

**Issue by zoezydk** [typeorm/typeorm#3114]
**Issue type:**

[x] question

**Database system/driver:**`

[x] `mssql`

**TypeORM version:**

[x ] `0.2.8`

**Steps to reproduce or a small repository showing the problem:**

_Intention_
Integrating a working typeorm project connected to a MSSQL database into an existing angular 7 project in order to read the returned database information into the aforementioned angular 7 project so data can be displayed there.

_Wanted_
Documentation or instructions on how to best achieve the above.

_Step#1 -->_ Create angular 7 project with CLI.
_Step#2 -->_ Create typeorm project following steps found in documentation (https://www.npmjs.com/package/typeorm), creating model and domain logic.

Thanks in advance for any help.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by zoezydk** [comment]
Is there any input to the above, please?

**Comment by ZiadJ** [comment]
The main reason I chose to use TypeORM is because it's typescript based just like Angular. I was hoping to be able to just reuse the backend models on the frontend because of that but that's not even possible right now apperently. Or is it?

**Comment by pleerock** [comment]
@ZiadJ you should understand that you have two different **platforms** and you try to share code in two different **platforms**, and this approach can bring you some issues. Technically they are resolvable, so if you want to do that - go ahead. By this question is out of typeorm's scope.

@zoezydk we aren't planning to write tutorials on how to integrate different frameworks and solutions with typeorm. It is our scope. Feel free to write tutorials and share links with the community!

**Comment by pleerock** [comment]
I'll close this issue. Also you can refer to #1290 for some hints on how to do it.

**Comment by zoezydk** [comment]
@pleerock If I was able to write a tutorial, then I wouldn't ask for one in the first place. If typeorm doesn't provide these features readily available and easily explained in its general documentation, then I'm sorry to say so, but it just isn't useful for application in those cases where projects require this knowledge in order to make things work. The logical consequence of that lack of documentation is that developers will be giving up on typeorm and turn towards other alternatives such as ie. Loopback or similar which are able to do the job. This outcome is inevitable if the support required isn't given and the project scope and time just keeps increasing exponentially without no end in sight.

**Comment by pleerock** [comment]
@zoezydk obviously we can't cover every technology exist in the documentation. TypeORM and angular are completely unrelated technologies. Yes, they can be used in the same project, just like react, vuejs, elasticsearch, redis, android, ios, anything else.

I know react and I know lets say elasticsearch and I want to use them both in my project. Can I make them to work together in application I'm planning to write? Yes. Even if no, I need to learn and research more to make it possible and I can't ask react or elasticsearch for missing tutorials on how to use them together.

**Comment by zoezydk** [comment]
@pleerock That's all fine if those are the conditions. But if developer's expectations are let's say, that you can use typeorm with MSSQL, but it turns out that using it hereafter within an Ng-project will be a time-consuming and tedious task, that information on complications and challenges should be clearly mentioned in the general documentation _beforehand_. There are other types of ORM that apparently _can_ do the job without those challenges and don't involve ie. having to "hack" some CLI config in Ng or similar and which are applicable out of the box.

**Comment by pleerock** [comment]
> here are other types of ORM that apparently can do the job without those challenges

That's why different frameworks, tools and solutions exist. Go with other framework if you think it solves more issues for you. One day you'll stumble with something else anyway that might be covered by our framework. Just because we spent more time on it rather than something else. It's impossible to make everything perfect and cover every possible use case, because there are infinite number of use cases.

I don't want to be rough or harm somebody, but in this case I think its just lack of experience and knowledge on particular technologies and platforms. Just work a bit more (learn, try & research) with those technologies and you'll get how to implement your desires with any of the framework. If you don't want, okay that's your choice, you can choose something else, but as I told you'll stumble over some other issue with other tools as well.

When you say that you are using something that is "time-consuming and tedious task", first you should understand how much "time-consuming and tedious task" it was for others to deliver something that is free for you. Don't forget its open source - please respect other people time and efforts.

**Comment by zoezydk** [comment]
@pleerock With all due respect, I do value others work. But I think that all the above information should be made available for the particular task at hand. This thread (and many others show) that there is a common confusion in this _particular_ area. So it would be best to address the most frequent issues if they appear on multiple occasions and over a longer period of time and either cover them in the documentation or if not possible due to time constraints, add a warning to the documentation. This isn't too much to ask for.

**Comment by pleerock** [comment]
> This thread (and many others show) that there is a common confusion in this particular area. 

believe me, its not the only thread that shows user demands. There are hundred of other issues that needs more or same level of attention. But unfortunately right now all my free time is taken by answering questions in issues (including current discussion). Again, its open source, its free and made by people for people, so if you have an opportunity to contribute - just do it. If no, well, then its unfair side of open source. If you do it, it will be valuable for people like you.

**Comment by zoezydk** [comment]
@pleerock Well, for what it's worth, I reckon that people stumbling upon this thread might just find the warning in terms of the headline and description of the issue which are unavailable in the present documentation. As such, you may close the thread.

**Comment by ZiadJ** [comment]
@pleerock It's been a year since TypeORM broke compatibility with Angular right after I had spent weeks writing code for dozens of model entities and now I don't have much choice apparently but to start all over again with another framework because I'm no expert enough in Angular to be able to fix it.

@zoezydk Have you given Loopback 4 a try yet? If so I'm curious to know about your impressions.

**Comment by pleerock** [comment]
> @pleerock It's been a year since TypeORM broke compatibility with Angular right after I had spent weeks writing code for dozens of model entities and now I don't have much choice apparently but to start all over again with another framework because I'm no expert enough in Angular to be able to fix it.

TypeORM didn't any compatibility with Angular because its not related to Angular anyhow. 

> @zoezydk Have you given Loopback 4 a try yet? If so I'm curious to know about your impressions.

obviously its not a place for such conversions. 

Please be more respectful to other people time. I'm going to lock this conversation.
