### ISSUE TITLE
`insert` does not respect `SaveOptions`

### ISSUE THREAD

**Issue by albrow** [typeorm/typeorm#3115]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following code:

```ts
await eventsRepository.insert(events, { chunk: Math.ceil(events.length / BATCH_SAVE_SIZE) });
```

I would expect `insert` to split my entities into `chunk` pieces of size `BATCH_SAVE_SIZE`. However, the `chunk` option is not actually being respected and this results in an error that looks like:

```
bind message supplies 31136 parameters, but prepared statement "" requires 489888
QueryFailedError: bind message supplies 31136 parameters, but prepared statement "" requires 489888
```

The error is the same regardless of the value of `chunk`.

[`Repository.insert` simply calls `EntityManager.insert`](https://github.com/typeorm/typeorm/blob/39e4008e5a36d8774b10ac3a7e164269ecfe8b45/src/repository/Repository.ts#L165) and passes its arguments through.

I believe this is happening because the [options passed in to `EntityManager.insert` are never actually used](https://github.com/typeorm/typeorm/blob/39e4008e5a36d8774b10ac3a7e164269ecfe8b45/src/entity-manager/EntityManager.ts#L367).

It is not just the `chunk` option. It looks to me like all options are being ignored.

**Comment by pleerock** [comment]
Closing in favor of #3417 - checkout exist conversation and feel free to add your thoughts!
