### ISSUE TITLE
orWhere not working in cycle as expected

### ISSUE THREAD

**Issue by darky** [typeorm/typeorm#3119]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `0.2.9`

**Steps to reproduce or a small repository showing the problem:**

```javascript
const userIds = ['id1', 'id2', 'id3'];
repository
  .createQueryBuilder()
  .where(new Brackets(qb => {
    userIds.forEach(userId => qb.orWhere('"userId" = :userId', {userId}));
  }))
  .getMany();
```

****Expected:****
Returns 3 users

****Actual:****
Returns only 1 user, because it pass only latest `userId === 'id3'`

****Workaround:****
Ignore pass as placeholder, inject userId in template string:

```javascript
userIds.forEach(userId => qb.orWhere(`"userId" = '${userId}'`));
```

**Comment by darky** [comment]
https://github.com/typeorm/typeorm/issues/1239#issuecomment-366955628
It help me

**Comment by geersch** [comment]
@darky:

As @hcesar mentioned this is indeed to caused by reusing the same parameter name within the loop. TypeORM probably optimises this and uses the last value assigned to a parameter name.

Make sure to index the parameter names so that each one is unique.

```
someArray.forEach((parameter, index) => {
      conditions.push(
        new Brackets((qb) => {
          qb
            .andWhere(`lookup.lookupType = :paramName${index}`, { [`paramName${index}`]: parameter })
        }),
      );
    });
```

**Comment by vfa-loinh** [comment]
I have the same issue:

- if (condition.brands && condition.brands.length > 0) {

                query.andWhere(new Brackets( subQy => {
                    condition.brands.map((brandName, idx) => {
                        if (brandName && brandName.length > 0) {
                            return subQy.orWhere('prd.brand_name LIKE :brandName',{brandName});
                        }
                    });
                }));
            }
