### ISSUE TITLE
What's the best practice of error handling when the network is every unstable?

### ISSUE THREAD

**Issue by lake2** [typeorm/typeorm#3122]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm developing a spider program， which will run on an ADSL server. The ADSL server's network is very unstable, the program's database manipulation probably throw network relevant error at any time. What's the best practice under this circumstance? Try and catch at every database operations will be fussy. When I use the Mysql package, I can handle errors when executing `connection.query`, `connection.beginTransaction` or `connection.commit` at low level, so I don't need to handle errors at every database operation. What should I do? Thanks.

**Comment by havenchyk** [comment]
In Koa there is a top level middleware that runs any code inside try/catch. So to level handler might be a solution.

I don't know if there is a mechanism in typeorm itself though

**Comment by imnotjames** [comment]
There's nothing in typeorm for this at this time for every driver.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
