### ISSUE TITLE
Do not try to create foreign key for relations on view

### ISSUE THREAD

**Issue by hcesar** [typeorm/typeorm#3124]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When joining a view we have to disable synchronization otherwise it will fail because TypeORM is going to try to create the Foreign Key

```
@Entity()
export class User {
  @Property({ primary: true })
  id: number;

  @Property({ length: 255 })
  name: string;

  @OneToOne(type => UserWhatever)
  @JoinColumn({ name: 'id', referencedColumnName: 'userId' })
  whatever: UserWhatever;
}
```

The following command:
```
 ALTER TABLE "user" ADD CONSTRAINT "FK_63215a5148ef25e4bd227cd1bdf" FOREIGN KEY ("id") REFERENCES "userWhatever"("userId")
```

Fails with the error:
`error: referenced relation "userWhatever" is not a table`

**Comment by hcesar** [comment]
Can be related to #3120

**Comment by havenchyk** [comment]
Seems to be the same request as #3120. Let's maybe close this issue and track #3120 as a main issue
