### ISSUE TITLE
Add `LessThanOrEqual` and `MoreThanOrEqual` find options operators

### ISSUE THREAD

**Issue by alfaproject** [typeorm/typeorm#3126]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Is there any chance these 2 operators can be added? `LessThan` and `MoreThan` already exist, so maybe this was overlooked?

**Comment by alfaproject** [comment]
Actually, even `MoreThan` seems to be acting out:
```
query failed: SELECT `Session`.`id` AS `Session_id`, `Session`.`userId` AS `Session_userId`, `Session`.`sessionId` AS `Session_sessionId`, `Session`.`expiresAt` AS `Session_expiresAt`, `Session`.`createdAt` AS `Session_createdAt`, `Session`.`updatedAt` AS `Session_updatedAt` FROM `session` `Session` WHERE `Session`.`sessionId` = ? AND `Session`.`expiresAt` = ? -- PARAMETERS: [{"type":"Buffer","data":[99,134,232,11,69,249,134,27,178,205,176,166,197,128,63,86]},{"_type":"moreThan","_value":"2018-11-19T15:33:15.337Z","_useParameter":true,"_multipleParameters":false}]

error: { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', `_value` = '2018-11-19 15:33:15.337', `_useParameter` = true, `_multipleParame' at line 1
```

**Comment by tobyhinloopen** [comment]
👍 Why does this not yet exist?
