### ISSUE TITLE
orderBy error Mysql in typeorm (works in request sql)

### ISSUE THREAD

**Issue by Paul75** [typeorm/typeorm#3128]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I make a query into repositiory to add in order the element but it strenge when I display the sql (querySql()) and go to phpMyAdmin it give a result but into execute into TypeOrm it failed ....

My SQL query generated is : 
```
SELECT `etablissements`.`id` AS `etablissements_id`, `etablissements`.`regate` AS `etablissements_regate`, `etablissements`.`libelle` AS `etablissements_libelle`, `etablissements`.`territoireId` AS `etablissements_territoireId`, `etablissements`.`typeEtablissementId` AS `etablissements_typeEtablissementId`, `etablissements`.`dtId` AS `etablissements_dtId`, `type_etablissement`.`id` AS `type_etablissement_id`, `type_etablissement`.`libelle` AS `type_etablissement_libelle`, `territoire`.`id` AS `territoire_id`, `territoire`.`libelle` AS `territoire_libelle` FROM `etablissements` `etablissements` LEFT JOIN `type_etablissement` `type_etablissement` ON `type_etablissement`.`id`=`etablissements`.`typeEtablissementId`  LEFT JOIN `territoires` `territoire` ON `territoire`.`id`=`etablissements`.`territoireId` ORDER BY `etablissements`.`libelle` DESC
```

But in Error is : 
``` Error 0=Error: "`etablissements`" alias was not found. Maybe you forgot to join it? ```
strenge is into the same table not join ....

Thanks

**Comment by Paul75** [comment]
I found a solution : it was a problem for naming of relation I transform the element with the `table`.`field`. I means if the table name 'etablissements' and field is 'libelle' I transform before send : `etablissements`.`libelle`.

I don't know why is good right to pass to query ...

Thanks

**Comment by lorenzofox3** [comment]
You should probably close your issue then ! Cheers
