### ISSUE TITLE
A way easier approach to getCount()

### ISSUE THREAD

**Issue by D4edalus** [typeorm/typeorm#313]
https://github.com/typeorm/typeorm/blob/1e6b7364ff1b36715b38e9aab64e1ad3eb93842e/src/query-builder/QueryBuilder.ts#L1068

https://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_found-rows

```
SELECT SQL_CALC_FOUND_ROWS * FROM tbl_name WHERE id > 100 LIMIT 10;
SELECT FOUND_ROWS();
```

**Comment by pleerock** [comment]
is it mysql-specific? If so then we need to implement something different for other databases. Also there are comments that it works slower then regular approach [here](http://stackoverflow.com/questions/186588/which-is-fastest-select-sql-calc-found-rows-from-table-or-select-count).

**Comment by D4edalus** [comment]
yes it is mysql specific i as far as i know. i guess that make it unfeasible.



Sorry that I'm on a bug reporting spree, but i found a problem related to getCount()

Suppose we have two table `action` and `reports`. any action can be reported n times. For convenience we want the field numReports be available to quickly access the number of reports.

.createQueryBuilder("action")
.leftJoinAndSelect("action.reports", "reports")
.addSelect(`SUM(reports.id IS NOT NULL) as numReports`)

So far so good query works and count works. but wait! The `SUM()` aggregation needs `.addGroupBy("action.id")` to group correctly .. and here is where the problem starts.

`getCount()` now is confused, and gives us not one value, but one count per group!

my workaround looks like this:
```
const generatedQuery = query.getSqlWithParameters(false); // 0 query, 1 parameters
SELECT COUNT(*) as somerandomname FROM (${generatedQuery[0]}) anotherrandomname
```

**Comment by pleerock** [comment]
The only fix for now I could came up with is to remove `group by` from count query. I don't really think its needed in count query. So closing this issue.
