### ISSUE TITLE
please remove word "ORM" from project name!

### ISSUE THREAD

**Issue by eritikass** [typeorm/typeorm#3130]
a really nice job with this project, have been given a fair share of time to research this lately and really wanting to introduce my company as part of our stack. But did run head against a wall, as this package has to be big and ugly ORM (like name say's).

if possible please remove word "ORM" from project name - or replace with something more generic (like db etc...), so those who have had bad experiences with ORM's in past would not panic out when you suggest typeorm as db library.

**Comment by havenchyk** [comment]
@eritikass did your company make donations or is going to make donations to the project? If not, why do you think that people will do this change (it's a time-consuming change), based on your request?

Unfortunately it's up to you to use or not to use `typeorm`, but I personally don't see any reason to rename the project. There are many different opensource projects, feel free to use them instead.
