### ISSUE TITLE
Issue connecting with MongoDB Atlas Cluster

### ISSUE THREAD

**Issue by charlieroth** [typeorm/typeorm#3133]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

**package.json:**
```json
{
   "name": "...",
   "version": "...",
   "description": "...",
   "devDependencies": {
      "ts-node": "7.0.1",
      "@types/node": "^10.12.9",
      "typescript": "3.1.6"
   },
   "dependencies": {
      "@types/dotenv": "^6.1.0",
      "dotenv": "^6.1.0",
      "mongodb": "^3.1.10",
      "reflect-metadata": "^0.1.10",
      "tslint": "^5.11.0",
      "typeorm": "0.2.9"
   },
   "scripts": {
      "start": "..."
   }
}
```

**Steps to reproduce or a small repository showing the problem:**
```ts
import * as dotenv from "dotenv";
import "reflect-metadata";
import { createConnection } from "typeorm";

dotenv.config();
createConnection({
    cli: {
        entitiesDir: "src/entity",
        migrationsDir: "src/migration",
        subscribersDir: "src/subscriber",
    },
    entities: [
        "src/entity/**/*.ts",
    ],
    logging: true,
    migrations: [
        "src/migration/**/*.ts",
    ],
    subscribers: [
        "src/subscriber/**/*.ts",
    ],
    synchronize: true,
    type: "mongodb",
    url: `mongodb+srv://${process.env.MONGODB_ATLAS_USERNAME}:${process.env.MONGODB_ATLAS_PASSWORD}@inquisitive-cluster-1-j18op.mongodb.net/inquisitive-db?retryWrites=true`,
}).then(async (connection) => {
    console.log("Connection succesful");
    console.log("Connection: ", connection);
}).catch((error) => {
    console.log("Connection failed");
    console.log(error);
});
```
When I run `npm start` I get the following error:
```
(node:3634) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
```

I see older issues with a similar problem and was wondering if an update in the MongoDB node driver is causing this or if this is due to my configuration settings?

**Comment by nik-amir** [comment]
I've never used MongoDB Atlas Cluster before, but I think you need to include [`useNewUrlParser: true`](https://github.com/typeorm/typeorm/blob/master/src/driver/mongodb/MongoConnectionOptions.ts#L256) in your `createConnection` options.

```js
import * as dotenv from "dotenv";
import "reflect-metadata";
import { createConnection } from "typeorm";

dotenv.config();
createConnection({
    cli: {
        entitiesDir: "src/entity",
        migrationsDir: "src/migration",
        subscribersDir: "src/subscriber",
    },
    entities: [
        "src/entity/**/*.ts",
    ],
    logging: true,
    migrations: [
        "src/migration/**/*.ts",
    ],
    subscribers: [
        "src/subscriber/**/*.ts",
    ],
    synchronize: true,
    useNewUrlParser: true
    type: "mongodb",
    url: `mongodb+srv://${process.env.MONGODB_ATLAS_USERNAME}:${process.env.MONGODB_ATLAS_PASSWORD}@inquisitive-cluster-1-j18op.mongodb.net/inquisitive-db?retryWrites=true`,
}).then(async (connection) => {
    console.log("Connection succesful");
    console.log("Connection: ", connection);
}).catch((error) => {
    console.log("Connection failed");
    console.log(error);
});
```

**Comment by vlapo** [comment]
Similar issue https://github.com/typeorm/typeorm/issues/2650

**Comment by pointtoken** [comment]
I'm seeing this as well. But the issue for me isn't just getting a warning; I can't connect via typeorm to a mongodb atlas cluster at all. What are the tricks for getting typeorm to connect to a mongodb atlas cluster? (Works fine against a local mongodb instance)

**Comment by vlapo** [comment]
@charlieroth if this issue is only about warning please, please see this comment https://github.com/typeorm/typeorm/issues/2650#issuecomment-451387055.

If there is problem with connect to mongo atlas please check this answer https://github.com/typeorm/typeorm/issues/3347#issuecomment-451320383

Let me know if this help.

**Comment by vlapo** [comment]
This issue should be fixed by https://github.com/typeorm/typeorm/pull/3366 and will be in next release. Feel free reopen if problem persists.
