### ISSUE TITLE
Generating entity classes after loading entities via connection

### ISSUE THREAD

**Issue by kristianmandrup** [typeorm/typeorm#3141]
**Issue type:**

[ x ] question
[ x ] feature request
[ x ] documentation issue

The docs are not clear on how to interoperate and use Entity classes when loading `entities` or `entitiesSchema` via their respective connection options in `createConnection`.

Would I need to create a custom iterator to run through the `entityMetaDatas` of the connection and create those classes decorated by Entity or is this already somehow built in? Does one overwrite the other or are they seamlessly merged or what?

I'd like to use [graphGenTypeorm](https://github.com/jjwtay/graphGenTypeorm) to generate my typeorm entities from a GraphQL schema, then add extra decorators, methods and fields if/when necessary for each, possibly using additional metadata in a codegen approach.

Would this kind of approach work? 

```js
import { Entity } from 'typeorm'

const identity = (value: any) => value

function entityClasses(connection: Connection, entityStore = {}, decorate: Function = identity) {
    const entityMetaDatas: any[] = ...connection.entityMetaDatas
    const { propertiesMap } = entityMetaDatas
    const entityNames = Object.keys(propertiesMap)

    return entityNames.reduce((acc, name) => {
        // create blank @Entity decorated class
        const entityClazz = Entity(class {})
        // decorate entity class further and add class to map
        acc[name] = decorate(entityClazz, propertiesMap[name], propertiesMap)
        return acc
    }, entityStore)
}
```

**Comment by Kononnable** [comment]
@kristianmandrup 
Could you elaborate on what exactly you think should be changed here? Tbh issue description is not clear to my and I'm not sure what is your problem here.

**Comment by pleerock** [comment]
If I got you right, what you need is to write data into `getMetadataStorage()` instance, same way as decorators do.

**Comment by imnotjames** [comment]
Pretty sure that's the answer.  Closing!

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
