### ISSUE TITLE
Database operations are not working when i run in release mode :( 

### ISSUE THREAD

**Issue by wliadmin** [typeorm/typeorm#3146]
Database operations are not working in release mode

### **Steps to reproduce**
-> Run application by archiving application in iOS
-> Database operations are not performing in release mode

### **Expected behaviour**
-> All the database operations should be performed

**Comment by havenchyk** [comment]
@wliadmin I don't think it's a problem of typeorm, but anyway, could you please provide an example to reproduce the problem?

**Comment by wliadmin** [comment]
> @wliadmin I don't think it's a problem of typeorm, but anyway, could you please provide an example to reproduce the problem?

You can check with this demo: https://github.com/typeorm/react-native-example

I am running on react-native platform. 

Thanks in advance

**Comment by Kononnable** [comment]
@wliadmin 
Did you resolve your issue?

It might be same issue as #3933

**Comment by tindn** [comment]
@wliadmin this solved it for me https://github.com/typeorm/typeorm/issues/3933#issuecomment-486340881
