### ISSUE TITLE
Recursive relation - Referenced Object

### ISSUE THREAD

**Issue by RobinFalko** [typeorm/typeorm#3149]
**Issue type:**

[x] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Steps to reproduce or a small repository showing the problem:

**Having two entities with a recursive relation, I would like to fetch entities where child entities are references.**

**E.g. given a "Planet A" orbiting on any Orbit and "Planet B" orbiting around "Planet A" (on "Orbit B")**

I'm fetching all Planets: 

```
...
space: Space { planets: {
    Planet { name: "Planet A", …},
    Planet {name: "Planet B",
        orbit: Orbit {name: "Orbit B", …},
        parentPlanet: Planet {name: "Planet A", …} //<- This object is not the same reference as the one at index 0
    }
}
...
``` 
Is it possible to let typeORM create references if the data set is actually the same? So in this case the object at "index 0" and "index 1->parentPlanet" should be the same reference.

I'm also wondering what would happen if I change "index 1->parentPlanet" and then save the root object "space" again. What data set would dominate? - Planet at index 0 or Planet at index 1->parentPlanet.

Schemas:
```
new EntitySchema({
        name: "Planet",
        target: Planet,
        columns: {
            id: {
                primary: true,
                type: "int",
                generated: true
            },[...]
        },
        relations: {
            orbit: {
                target: "Orbit",
                type: "many-to-one",
                inverseSide: "planets"
            },
            orbits: {
                target: "Orbit",
                inverseSide: "parentPlanet",
                type: "one-to-many",
                joinColumn: true,
                cascade: true
            },[...]
        }
    }


new EntitySchema({
        name: "Orbit",
        target: Orbit,
        columns: {
            id: {
                primary: true,
                type: "int",
                generated: true
            },[...]
        },
        relations: {
            parentPlanet: {
                target: "Planet",
                inverseSide: "orbits",
                type: "many-to-one"
            },
            planets: {
                target: "Planet",
                type: "one-to-many",
                inverseSide: "orbit",
                joinTable: true,
                cascade: true
            }
        }
    }
```

**Comment by tsarevpp** [comment]
Same question here.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
