### ISSUE TITLE
Create real-world example how to use TypeORM with Express

### ISSUE THREAD

**Issue by pleerock** [typeorm/typeorm#315]
This should go into separate repository in typeorm organization, like typescript-example and javascript-example.

**Comment by valeriy-devpronet** [comment]
What is the requirements for minimum?
I'm ready to create such kind of example, but for koajs@2. If it interested and fits to this request.

**Comment by pleerock** [comment]
yes I think good to have examples for both koa and express. Requirements are to fit best practices from koa and typeorm (Im going to guide you over last), create few entities for example `Post` and `Category` or `Blog` and `Category` and few controllers. Directory structure should be:

```ts
controller
entity
...
app.ts or index.ts
```

As base starter typescript-example should be taken.

**Comment by pleerock** [comment]
Implemented.

* [Example how to use Express and TypeORM with TypeScript](https://github.com/typeorm/typescript-express-example)
* [Example how to use Koa and TypeORM with TypeScript](https://github.com/typeorm/typescript-koa-example)
