### ISSUE TITLE
postgres generated wrong query for  "ANY" condition 

### ISSUE THREAD

**Issue by xmlking** [typeorm/typeorm#3150]
I have `array` type column and want to find all rows where array column contain given entry.

**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
import { Column, CreateDateColumn, Entity, Index, UpdateDateColumn, VersionColumn } from 'typeorm';
import { ApiModelProperty } from '@nestjs/swagger';
import { IsAscii, IsNotEmpty, IsString, IsUrl, MaxLength, MinLength } from 'class-validator';
import { Exclude } from 'class-transformer';
import { Base } from '../core/entities/base.entity';

@Entity('subscription')
export class Subscription {
  @ApiModelPropertyOptional()
  @PrimaryGeneratedColumn()
  id: number;

  @ApiModelProperty({ type: String })
  @IsNotEmpty()
  @IsUrl({}, { message: 'endpoint must be a valid url.' })
  @Index({ unique: true })
  @Column()
  endpoint: string;

  @ApiModelProperty({ type: String })
  @IsNotEmpty()
  @IsString()
  @Column({})
  auth: string;

  @ApiModelProperty({ type: String })
  @IsNotEmpty()
  @IsString()
  @Column({})
  p256dh: string;

  @ApiModelProperty({ type: String, isArray: true })
  @Column('text', { array: true })
  topics: string[];
}
```

```ts
import { Any, FindConditions, Repository } from 'typeorm';
async notifyAll(topic: string) {
const subscriptions = await this.repository.findAndCount({ topics: Any([topic]) } );
}
```

query failed: 
```
SELECT "Subscription"."id" AS "Subscription_id", "Subscription"."endpoint" AS "Subscription_endpoint", "Subscription"."auth" AS "Subscription_auth", "Subscription"."p256dh" AS "Subscription_p256dh", "Subscription"."userId" AS "Subscription_userId", "Subscription"."topics" AS "Subscription_topics", "Subscription"."createdAt" AS "Subscription_createdAt", "Subscription"."updatedAt" AS "Subscription_updatedAt", "Subscription"."version" AS "Subscription_version" FROM "subscription" "Subscription" WHERE "Subscription"."topics" = ANY($1) -- PARAMETERS: [["sumo1"]]
```

Expected  something like this: 
```
SELECT * FROM subscription where 'sumo1'  = ANY(topics);
```

**Comment by YegorZaremba** [comment]
@xmlking I tried fix this bug, but it so rare situation. We defenetly add specific condition for this case, but not sure that its matter. In suggestions on SO people recommend don't use `any` in arrays searching
https://stackoverflow.com/questions/56631311/no-operator-matches-the-given-name-and-argument-types-you-might-need-to-add-e

@vlapo just ping you about my update :)

**Comment by vlapo** [comment]
`Any` operator is only "shortcut" and generates simple `<column> = ANY(<parameterArr>)` sql statement. So I think this works as intended and it is not a bug.

@xmlking you have to use `Raw` with `&&` operator as @YegorZaremba mentioned:
```ts
await this.repository.findAndCount({
    topics: Raw( alias => `${alias} && ARRAY["${topic}"]` ) 
});
```
Did not test it maybe it need some improvement.

Note: In point of generating SQL query typeorm know nothing about type of column (in current implementation). So there is no way how to handle this case anyway (in current implementation).
