### ISSUE TITLE
'uuid' in PrimaryGeneratedColumn causes Many-to-Many Relationship to Fail

### ISSUE THREAD

**Issue by eeyang92** [typeorm/typeorm#3151]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Note.ts:
```
import { Entity, Column, PrimaryGeneratedColumn, ManyToMany, JoinTable } from 'typeorm'
import { Category } from './Category'

@Entity()
export class Note {
    @PrimaryGeneratedColumn('uuid')
    id: number

    @Column()
    content: string

    @ManyToMany((type) => Category, (category) => category.notes)
    @JoinTable()
    categories: Category[]
}
```

Category.ts:
```
import { Entity, Column, PrimaryGeneratedColumn, ManyToMany } from 'typeorm'
import { Note } from './Note'

@Entity()
export class Category {
    @PrimaryGeneratedColumn('uuid')
    id: number

    @Column()
    name: string

    @ManyToMany((type) => Note, (note) => note.categories)
    notes: Note[]
}

```

Error upon startup (synchronize):

```
query failed: ALTER TABLE `note_categories_category` ADD CONSTRAINT `FK_c43c88ee88c5c2c09452d328943` FOREIGN KEY (`noteId`) REFERENCES `note`(`id`) ON DELETE CASCADE
error: { Error: Cannot add foreign key constraint
.
.
.
code: 'ER_CANNOT_ADD_FOREIGN',
errno: 1215,
sqlState: 'HY000',
sqlMessage: 'Cannot add foreign key constraint'
```

Note: When I remove `uuid` from the PrimaryGeneratedColumn, mysql successfully creates the schema without any complaints. Also, the issue did not show up until I completed both sides of the relationship (it was working with just Many-to-Many implemented on Notes, but broke when I implemented it on Category).

**Comment by aphex** [comment]
Sorry to dig this back up but I am seeing this same issue if Note has an `id` that is just a `PrimaryColumn` of type string also. I am trying to store data where the unique id is coming from another service and its a string, so I would like that string to be the primary key for the table.  That table also will have a OneToMany/ManyToOne relationship.

It seems that something is forcing id to be an `int` even though I have specified it to be a `varchar`

```
 @PrimaryColumn()
    id: string
```
