### ISSUE TITLE
Problem with implementing typeorm with cordova

### ISSUE THREAD

**Issue by SzateX** [typeorm/typeorm#3156]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi i got an error in my project while trying to apply to my project cordova example. I run: npm run android, and got error like this: [error.log](https://gist.github.com/SzateX/1c52d9291af399a973d39ae790f83db3)

I have no idea what i'm doing wrong and can't read it from log.

My repo code is here: [repo_link](https://github.com/SzateX/IntApp)

**Comment by imnotjames** [comment]
Hi there - there repo link is gone & the error log has no error messages referring to TypeORM.  If you have the reproduction link I'd be interested in taking a look, though.

**Comment by imnotjames** [comment]
If you do end up getting any of the repo back up please re-open a new issue & we'll dig into the underlying cause!  For now I'll be closing this issue as we're unable to replicate.
