### ISSUE TITLE
Unable to select related column

### ISSUE THREAD

**Issue by mogusbi** [typeorm/typeorm#3161]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am trying to filter the columns returned on a related property. In the example below, I am trying to just select the home entity's id.

What I get is this error: `Relation "home.id" was not found, please check if it is correct and really exist in your entity.`

```ts
# team.entity.ts

@Entity()
export class Team {
  @PrimaryGeneratedColumn('uuid')
  public id: string;

  @Column({
    unique: true
  })
  public name: string;
}

# fixture.entity.ts

@Entity()
export class Fixture {
  @PrimaryGeneratedColumn('uuid')
  public id: string;

  @OneToOne((): typeof Team => Team, {
    eager: true
  })
  @JoinColumn()
  public away: Team;

  @Column()
  public awayScore: number;

  @Column()
  public date: Date;

  @OneToOne((): typeof Team => Team, {
    eager: true
  })
  @JoinColumn()
  public home: Team;

  @Column()
  public homeScore: number;
}

# fixture.service.ts

const fixtureRepository = connection.getRepository(Fixture);
const fixtures = await fixtureRepository.find({
  relations: [
    'home.id'
  ]
});
```

**Comment by mogusbi** [comment]
@havenchyk I've also tested this out with postgres and the same issue persists

**Comment by vlapo** [comment]
I think this is wrong entity definition. The right one is `ManyToOne`:
```

@Entity()
export class Team {
    @PrimaryGeneratedColumn("uuid")
    public id: string;

    @Column({
        unique: true
    })
    public name: string;
}

@Entity()
export class Fixture {
    @PrimaryGeneratedColumn("uuid")
    public id: string;

    @ManyToOne(type => Team, {
        eager: true
    })
    public away: Team;

    @Column()
    public awayScore: number;

    @Column()
    public date: Date;

    @ManyToOne(type => Team, {
        eager: true
    })
    public home: Team;

    @Column()
    public homeScore: number;
}

const fixtureRepository = connection.getRepository(Fixture);
        const fixtures = await fixtureRepository.find({
            relations: [
                "home"
            ]
        });
```
One team could be in many fixtures.
But there is issue https://github.com/typeorm/typeorm/issues/2661.

**Comment by mogusbi** [comment]
@vlapo you are correct in that it should be `ManyToOne` but the issue still persists because you cannot control which related columns you wish to return

**Comment by vlapo** [comment]
Ou, I am sorry. I did not understand your issue before. But sill I think this is no issue because this feature is not available in 0.2.x. Check this issue https://github.com/typeorm/typeorm/issues/2385. In next branch is this feature implemented with some syntax changes :)

**Comment by mogusbi** [comment]
That's good, is there timeline of when the next version will be ready? I know it's available on the `@next` channel but i'd rather wait until it's "final", so to speak

**Comment by havenchyk** [comment]
@mogusbi no timeline since @pleerock can't handle everything https://github.com/typeorm/typeorm/issues/3267

**Comment by pleerock** [comment]
Think we can close it since its resolved in `@next`. Right now Im strongly focused on current github issues, so no time for `@next`.
