### ISSUE TITLE
Typeorm migration folder not being detected when too 'deep' in structure/

### ISSUE THREAD

**Issue by ahaw** [typeorm/typeorm#3166]
**Issue type:**
[x ] bug report

**Database system/driver:**
[x ] `mssql`
**TypeORM version:**
[x ] `0.2.9` 

**Steps to reproduce or a small repository showing the problem:**
I used ormconfig.json as a config holder.
My json structure is (I removed not important parts): 
```
{
     [..]
        "migrations": [
            "src/db/migrations/**/*.ts"
        ],
        "migrationsTableName": "migration_table",
        "cli": {
        [..]
            "migrationsDir": "src/db/migrations"
        }
    }
```

With this configuration migrations are working fine. 
But when I change migrations path to: "src/shared/db/migrations/* */*.ts" migrations are never discovered.
```
{
     [..]
        "migrations": [
            "src/shared/db/migrations/* */*.ts"
        ],
        "migrationsTableName": "migration_table",
        "cli": {
        [..]
            "migrationsDir": "src/shared/db/migrations"
        }
    }
```
Other probles is migrations doesn't work at all when using ormconfig.js as config holder but I think it was mentioned before.

**Comment by gintsgints** [comment]
@ahaw why at second example there is space in path?

**Comment by ahaw** [comment]
At the beggining I didn't use code block for config view and  double asterisk made text **bold** so I added space in between

**Comment by imnotjames** [comment]
Please provide a replication as a repo or otherwise - I can't replicate this issue.
