### ISSUE TITLE
CosmosDB support

### ISSUE THREAD

**Issue by chengjia0807** [typeorm/typeorm#3174]
Hi,

I have an issue with CosmosDB (Mongo API).

I can connect to CosmosDB through mongodb driver or Mongoose without any problem

Howeven when I tried to use TypeORM it threw an expection:

```
Invalid schema, expected `mongodb` or `mongodb+srv`
```

Sometimes get this error: 

```
{ Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
```

Is there any solution on this?

Thanks
CJ

**Comment by joaogoya** [comment]
same error, but on a mongoose and mongo db
