### ISSUE TITLE
Using this.save() in @AfterInsert() to set default json values leads to ER_DUP_ENTRY

### ISSUE THREAD

**Issue by creadicted** [typeorm/typeorm#3178]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.8` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hello! I would like to add default values to a json field in sql. Since this is not supported i thought to use the after insert method to change the values. 

Minimal demo: 
```typescript

@Entity('sample')
export class SampleEntity {
  @Column()
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('json', {
    nullable: true
  })
  sampleObject: SampleObject;

  @AfterInsert()
  initDefaultValues() {
    if (!this.sampleObject) {
      this.sampleObject = {
        foo: []
      };
    }
    this.save();
  }
}
```
This leads to: 
`error: { Error: ER_DUP_ENTRY: Duplicate entry '531c026c-a7e6-480a-9530-0e3510e82edc' for key 'PRIMARY'
`
and the default values are not set.

**Comment by pleerock** [comment]
Correct.
