### ISSUE TITLE
Cannot execute increment on column defined by embedded entity

### ISSUE THREAD

**Issue by smonv** [typeorm/typeorm#3182]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.8` (or put your version here)

I have a embedded entity contain some friend statistics of a User. When user send a friend request to other user, I want increase `friend.sent` counter but the query always try to update `null` to `frientSent`.

My entity:
 
```ts
class FriendStats {
    @Column('bigint', { default: 0 })
    count: number;

    @Column('bigint', { default: 0 })
    sent: number;

    @Column('bigint', { default: 0 })
    received: number;
}

@Entity('users')
export class User {
    @Column(type => FriendStats)
    friend: FriendStats;
}
```

Query: 

```ts
await this.manager.increment(User, { id: user.id }, 'friend.sent', 1);
```

TypeORM generated SQL:

```
UPDATE "users" SET "friendSent" = $2, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = $1 -- PARAMETERS: ["123456",null]
```

Error

```
query failed: UPDATE "users" SET "friendSent" = $2, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = $1 -- PARAMETERS: ["123456",null]

error: { error: null value in column "friendSent" violates not-null constraint ......
```

**Comment by apellizzn** [comment]
This seems a bit strange, considering that the following is the output of the increment function in the `EntityManager.ts`
```
await this
            .createQueryBuilder(entityClass, "entity")
            .update(entityClass)
            .set({
                [propertyPath]: () => this.connection.driver.escape(column.databaseName) + " + " + Number(value)
            })
            .where(conditions)
            .execute();
```
There should be at least a `+` in your query output!

**Comment by smonv** [comment]
I'm tried with `createQueryBuilder` and `update` but got same error and same generated query.

```ts
await manager.createQueryBuilder(User, 'u')
                .update()
                .set({
                    'friend.sent': () => `"friendSent" + ${Number(1)}`,
                })
                .where({ id: user.id }).execute();
```

Query:

```
UPDATE "users" SET "friendSent" = $2, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = $1 -- PARAMETERS: ["123456",null]
```

Error

```
error: { error: null value in column "friendSent" violates not-null constraint
```

**Comment by pleerock** [comment]
We need a PR with a failing test for this issue.

**Comment by smonv** [comment]
Thanks for the fix.
