### ISSUE TITLE
PlatformTools.js:105 error:  Error: too many SQL variables

### ISSUE THREAD

**Issue by nextbyn** [typeorm/typeorm#3183]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

 
    [x] `sqlite`
    [ ] `postgres`

 

This error came with a large (150) elements on insert query .

`PlatformTools.js:105 error: Error: too many SQL variables at Database.handleError (sql.js:20) at Database.prepare (sql.js:20) at SqljsQueryRunner.<anonymous> (SqljsQueryRunner.js:101) at step (SqljsQueryRunner.js:41) at Object.next (SqljsQueryRunner.js:22) at SqljsQueryRunner.js:16 at new t (polyfills.js:3) at __awaiter (SqljsQueryRunner.js:12) at SqljsQueryRunner.js:94 at new t (polyfills.js:3)

`
Ionic:

ionic (Ionic CLI) : 4.4.0
Ionic Framework : ionic-angular 3.9.2
@ionic/app-scripts : 3.2.0

Cordova:

cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
Cordova Platforms : android 7.1.4, browser 5.0.3
Cordova Plugins : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.1.1, (and 24 other plugins)

System:

NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
npm : 5.6.0
OS : Windows 10
`

se this example

`PlatformTools.js:105 query failed:  INSERT INTO "tt_detalle_promo"("idempresa", "codpromo", "orden", "artreq", "cantreq", "artbon", "cantrega", "bonif", "cada") VALUES (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?), (?, ?, NULL, ?, ?, ?, ?, ?, ?) -- PARAMETERS: [372,240,999904,3,999984,0,12.5,0,372,240,999904,3,999985,0,31,0,372,240,999904,3,940031,0,22.32,0,372,240,999904,3,940033,0,18.5,0,372,240,999904,3,946002,0,18.5,0,372,240,999904,3,947527,0,22.5,0,372,240,999904,3,999904,0,10.5,0,372,240,999904,3,999968,0,10.5,0,372,240,999904,3,937708,0,14.5,0,372,240,999904,3,937710,0,18.49,0,372,240,999904,3,938220,0,22,0,372,240,999904,3,939246,0,12,0,372,240,999904,3,939765,0,1.07,0,372,240,999904,3,939846,0,16,0,372,240,999904,3,933197,0,18,0,372,240,999904,3,933611,0,25.67,0,372,240,999904,3,933735,0,25.5,0,372,240,999904,3,935631,0,18.5,0,372,240,999904,3,936412,0,13.5,0,372,240,999904,3,937187,0,14.5,0,372,240,999904,3,921003,0,24,0,372,240,999904,3,924196,0,18,0,372,240,999904,3,929047,0,5.5,0,372,240,999904,3,930394,0,21.95,0,372,240,999904,3,931972,0,22,0,372,240,999904,3,933134,0,14,0,372,240,999904,3,903804,0,18.5,0,372,240,999904,3,903805,0,14,0,372,240,999904,3,918252,0,22,0,372,240,999904,3,919770,0,22,0,372,240,999904,3,920128,0,24,0,372,240,999904,3,920824,0,22,0,372,240,999968,3,902341,0,12.5,0,372,240,999968,3,902342,0,14.5,0,372,240,999968,3,902353,0,13,0,372,240,999968,3,902354,0,14,0,372,240,999968,3,902926,0,25,0,372,240,999968,3,902927,0,25,0,372,240,999968,3,999984,0,12.5,0,372,240,999968,3,999985,0,31,0,372,240,999968,3,940031,0,22.32,0,372,240,999968,3,940033,0,18.5,0,372,240,999968,3,946002,0,18.5,0,372,240,999968,3,947527,0,22.5,0,372,240,999968,3,999904,0,10.5,0,372,240,999968,3,999968,0,10.5,0,372,240,999968,3,937708,0,14.5,0,372,240,999968,3,937710,0,18.49,0,372,240,999968,3,938220,0,22,0,372,240,999968,3,939246,0,12,0,372,240,999968,3,939765,0,1.07,0,372,240,999968,3,939846,0,16,0,372,240,999968,3,933197,0,18,0,372,240,999968,3,933611,0,25.67,0,372,240,999968,3,933735,0,25.5,0,372,240,999968,3,935631,0,18.5,0,372,240,999968,3,936412,0,13.5,0,372,240,999968,3,937187,0,14.5,0,372,240,999968,3,921003,0,24,0,372,240,999968,3,924196,0,18,0,372,240,999968,3,929047,0,5.5,0,372,240,999968,3,930394,0,21.95,0,372,240,999968,3,931972,0,22,0,372,240,999968,3,933134,0,14,0,372,240,999968,3,903804,0,18.5,0,372,240,999968,3,903805,0,14,0,372,240,999968,3,918252,0,22,0,372,240,999968,3,919770,0,22,0,372,240,999968,3,920128,0,24,0,372,240,999968,3,920824,0,22,0,372,240,999984,3,902341,0,12.5,0,372,240,999984,3,902342,0,14.5,0,372,240,999984,3,902353,0,13,0,372,240,999984,3,902354,0,14,0,372,240,999984,3,902926,0,25,0,372,240,999984,3,902927,0,25,0,372,240,999984,3,999984,0,12.5,0,372,240,999984,3,999985,0,31,0,372,240,999984,3,940031,0,22.32,0,372,240,999984,3,940033,0,18.5,0,372,240,999984,3,946002,0,18.5,0,372,240,999984,3,947527,0,22.5,0,372,240,999984,3,999904,0,10.5,0,372,240,999984,3,999968,0,10.5,0,372,240,999984,3,937708,0,14.5,0,372,240,999984,3,937710,0,18.49,0,372,240,999984,3,938220,0,22,0,372,240,999984,3,939246,0,12,0,372,240,999984,3,939765,0,1.07,0,372,240,999984,3,939846,0,16,0,372,240,999984,3,933197,0,18,0,372,240,999984,3,933611,0,25.67,0,372,240,999984,3,933735,0,25.5,0,372,240,999984,3,935631,0,18.5,0,372,240,999984,3,936412,0,13.5,0,372,240,999984,3,937187,0,14.5,0,372,240,999984,3,921003,0,24,0,372,240,999984,3,924196,0,18,0,372,240,999984,3,929047,0,5.5,0,372,240,999984,3,930394,0,21.95,0,372,240,999984,3,931972,0,22,0,372,240,999984,3,933134,0,14,0,372,240,999984,3,903804,0,18.5,0,372,240,999984,3,903805,0,14,0,372,240,999984,3,918252,0,22,0,372,240,999984,3,919770,0,22,0,372,240,999984,3,920128,0,24,0,372,240,999984,3,920824,0,22,0,372,240,999985,3,902341,0,12.5,0,372,240,999985,3,902342,0,14.5,0,372,240,999985,3,902353,0,13,0,372,240,999985,3,902354,0,14,0,372,240,999985,3,902926,0,25,0,372,240,999985,3,902927,0,25,0,372,240,999985,3,999984,0,12.5,0,372,240,999985,3,999985,0,31,0,372,240,999985,3,940031,0,22.32,0,372,240,999985,3,940033,0,18.5,0,372,240,999985,3,946002,0,18.5,0,372,240,999985,3,947527,0,22.5,0,372,240,999985,3,999904,0,10.5,0,372,240,999985,3,999968,0,10.5,0,372,240,999985,3,937708,0,14.5,0,372,240,999985,3,937710,0,18.49,0,372,240,999985,3,938220,0,22,0,372,240,999985,3,939246,0,12,0,372,240,999985,3,939765,0,1.07,0,372,240,999985,3,939846,0,16,0,372,240,999985,3,933197,0,18,0,372,240,999985,3,933611,0,25.67,0,372,240,999985,3,933735,0,25.5,0,372,240,999985,3,935631,0,18.5,0,372,240,999985,3,936412,0,13.5,0,372,240,999985,3,937187,0,14.5,0,372,240,999985,3,921003,0,24,0,372,240,999985,3,924196,0,18,0,372,240,999985,3,929047,0,5.5,0,372,240,999985,3,930394,0,21.95,0,372,240,999985,3,931972,0,22,0,372,240,999985,3,933134,0,14,0,372,240,999985,3,903804,0,18.5,0,372,240,999985,3,903805,0,14,0,372,240,999985,3,918252,0,22,0,372,240,999985,3,919770,0,22,0,372,240,999985,3,920128,0,24,0,372,240,999985,3,920824,0,22,0]
`

`PlatformTools.js:105 error:  Error: too many SQL variables
    at Database.handleError (sql.js:20)
    at Database.prepare (sql.js:20)
    at SqljsQueryRunner.<anonymous> (SqljsQueryRunner.js:101)
    at step (SqljsQueryRunner.js:41)
    at Object.next (SqljsQueryRunner.js:22)
    at SqljsQueryRunner.js:16
    at new t (polyfills.js:3)
    at __awaiter (SqljsQueryRunner.js:12)
    at SqljsQueryRunner.js:94
    at new t (polyfills.js:3)`

**Comment by Kononnable** [comment]
https://github.com/typeorm/typeorm/issues/2463
There is already an issue which describes this behavior, why it throws an error and what can be done to avoid that.

**Comment by Kononnable** [comment]
If you got troubles deciding how many elements can you add in a single query read about `SQLITE_MAX_VARIABLE_NUMBER`.

**Comment by havenchyk** [comment]
@nextbyn @Kononnable also it would be great to have this problem documented, what do you think?

**Comment by Kononnable** [comment]
Issue is too specific to put it in general documentation. I think it would be good for us to add something like FAQ for every documentation page and put there common problems with described topic.

**Comment by havenchyk** [comment]
sure, @nextbyn https://www.sqlite.org/limits.html
