### ISSUE TITLE
mongodb: _id is not recognized as PrimaryKey on .save()

### ISSUE THREAD

**Issue by phil294** [typeorm/typeorm#3184]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```ts
@Entity 
class X extends BaseEntity {
  @ObjectIDColumn()
  public _id!: ObjectID;
}

const x = await X.findOne({});
await x.save(); // <-- error
```
Fails (similar to #732, but mongodb) with `{ BulkWriteError: E11000 duplicate key error collection: dbName.X index: _id_ dup key: { : ObjectId('5c02d72245b5066037a6017f') }`

It should not because [according to the documentation](https://github.com/typeorm/typeorm/blob/master/docs/mongodb.md), the code is correct and `.save()` should look up the primary key. 
(and shouldnt `id` in the documentation actually be `_id`, the always-a-primary-key by default in MongoDB?)

Thanks for this tool. MongoDB integration is pretty good

**Comment by pleerock** [comment]
Adding @rustamwin

**Comment by rustamwin** [comment]
this issue related to #3291

**Comment by vlapo** [comment]
@phil294 I cannot reproduce your problem on next branch. Could you provide working example?
Also please test your problem on latest version from npm. But I think it should be ok.

About _id/id: We are converting `id` column to `_id` internally.

**Comment by rustamwin** [comment]
@vlapo can be closed?

**Comment by vlapo** [comment]
Yeah. No answer from issue creator.

**Comment by phil294** [comment]
Sorry the delay! Yup - no errors anymore. Thanks

**Comment by hhwsgit** [comment]
Excuse me. I had the same problem. How do you solve the problem? I need to save multiple data. And I am a beginner.
Thank you!

**Comment by phil294** [comment]
@hhwsgit The error described above got fixed. So if you are using the latest version, `x = X.findOne({}); x.save()` shouldnt throw an error anymore

**Comment by pairmix** [comment]
Hi there, always same error.
Impossible to let it work.
Only insertOne and UpdateOne work fine.
save() return error. 

````
@Entity('profils')
export class Profil {
  @ObjectIdColumn()
  _id: ObjectId;

  @ApiModelProperty()
  @Column('smallint')
  sexe: number;
}
````

````
let profil = await this.profilRepository.findOne({
       where: {
         candidat: candidatId,
      },
    });
return this.profilRepository.save(profil);
````
````
[Nest] 15200   - 2019-09-28 11:42:03   [ExceptionHandler] E11000 duplicate key error collection: pairmix.profils index: _id_ dup key: { : ObjectId('5d8f217efd402b249c9502d6') }
BulkWriteError: E11000 duplicate key error collection: pairmix.profils index: _id_ dup key: { : ObjectId('5d8f217efd402b249c9502d6') }
    at OrderedBulkOperation.handleWriteError (C:\Data\Projects\current\nestjs\node_modules\mongodb\lib\bulk\common.js:1112:11)
    at resultHandler (C:\Data\Projects\current\nestjs\node_modules\mongodb\lib\bulk\common.js:501:23)
    at handler (C:\Data\Projects\current\nestjs\node_modules\mongodb\lib\core\sdam\topology.js:973:24)
    at C:\Data\Projects\current\nestjs\node_modules\mongodb\lib\core\sdam\server.js:437:5
    at C:\Data\Projects\current\nestjs\node_modules\mongodb\lib\core\connection\pool.js:420:18
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
````

**Comment by rustamwin** [comment]
@pairmix Do you have sync enabled?

**Comment by pairmix** [comment]
@rustamwin 
No i don't:
````
const dotenv = require('dotenv');
dotenv.config();

module.exports = {
    type: "mongodb",
    useNewUrlParser: true,
    useUnifiedTopology: true,
    synchronize: false,
    authSource: "admin",
    url: process.env.PANGORIA_DATABASE_CONNECTION,
    entities: [`${process.env.PANGORIA_SOURCE_PATH}/**/**.entity{.ts,.js}`],
}
````

**Comment by pairmix** [comment]
same error with typeorm or typeorm@next

**Comment by rustamwin** [comment]
@pairmix Could you submit a new detailed issue?

**Comment by pairmix** [comment]
I found the solution.
My entities were like:
````
@Entity('visiteurs')
export class Visiteur {
  @ObjectIdColumn()
  _id: ObjectId;

  @Column()
  moi: ObjectId;

  @Column(type => Candidat)
  lui: Candidat;
}
````

It's @Column(type => Candidat) that generate error.

If i use:
````
@Column()
  lui: Candidat;
````
Everything works fine!

Sorry.
David
