### ISSUE TITLE
batch save error:  Expression tree is too large (maximum depth 1000)

### ISSUE THREAD

**Issue by bpatrik** [typeorm/typeorm#3185]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite` @4.0.4
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9`

I get ` Expression tree is too large (maximum depth 1000)` while saving a larger array of entities to DB.

Entity is a [single table entity](https://github.com/bpatrik/pigallery2/blob/4cf1536d5fe157a22b802fc0ad1dcf8049494d33/backend/model/sql/enitites/PhotoEntity.ts#L75). I'm using repositories to save them:
```ts
await connection.getRepository(PhotoEntity).save(photoArray)
```
[exact line of code is here, if interested](https://github.com/bpatrik/pigallery2/blob/4cf1536d5fe157a22b802fc0ad1dcf8049494d33/backend/model/sql/GalleryManager.ts#L343)

Error: 
```
{ QueryFailedError: SQLITE_ERROR: Expression tree is too large (maximum depth 1000)
    at new QueryFailedError (/var/www/node_modules/typeorm/error/QueryFailedError.js:28:28)
    at handler (/var/www/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:92:38)
    at replacement (/var/www/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/var/www/node_modules/sqlite3/lib/sqlite3.js:16:21)
  message:
   'SQLITE_ERROR: Expression tree is too large (maximum depth 1000)',
  errno: 1,
  code: 'SQLITE_ERROR',
  name: 'QueryFailedError',
  query:...
```

If I slice/chunk the array manually to length of 100, it solves my problem.

**Comment by vlapo** [comment]
Hi @bpatrik 

There are additional options for `save` method and you have to define `chunk`. More info http://typeorm.io/#/repository-api/additional-options (currently merged and published in docs).

**Comment by havenchyk** [comment]
Feel free to reopen if the solution provided by @vlapo doesn't work, but it should work.

**Comment by bpatrik** [comment]
Thank you, it worked for me!
