### ISSUE TITLE
Raw when value is a function

### ISSUE THREAD

**Issue by pontusab** [typeorm/typeorm#3186]
**Issue type:**

[X ] question

**Database system/driver:**

[X ] `postgres`

**TypeORM version:**

[ ] `latest`
[X ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Trying to implement LOWER on the title and following this example: 
```
import {Raw} from "typeorm";

const loadedPosts = await connection.getRepository(Post).find({
    currentDate: (alias) => Raw(`${alias} > NOW()`)
});
```

I'm doing something like: 

```
import {Raw} from "typeorm";

const loadedPosts = await Project.find({
    title: (alias) => Raw(`LOWER(${alias}) LIKE '%something%'`)
});
```

And this is not working, how can I change the WHERE statement in find?

**Comment by dschoeni** [comment]
I had a similar issue in writing a comparison function with a date. I think its a small mistake in the documentation, that still compiles however.

I got it to work like this:

`
const loadedPosts = await connection.getRepository(Post).find({
    currentDate: Raw((alias) => `${alias} > NOW()`)
});
`

**Comment by pleerock** [comment]
yeap someone made mistake in docs. I have fixed that. Thanks!
