### ISSUE TITLE
Store UUID as binary type in MySQL

### ISSUE THREAD

**Issue by igat64** [typeorm/typeorm#3187]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Given an Entity with primary column that store `uuid` as a value. 
```ts
@Entity()
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  ...
}
```
Generated type in the mysql database is varchar(255).
![image](https://user-images.githubusercontent.com/3001168/49344831-4f88ff00-f68d-11e8-8d40-572ce5ed6216.png)

As I know [this is not efficient way](https://mysqlserverteam.com/mysql-8-0-uuid-support/) of storing uuid as varchar. It should be possible to store uuid as a binary type. And mysql 8 has buildin functions like: UUID_TO_BIN/BIN_TO_UUID. These function could be used to convert from the human-readable format (char/varchar) to the compact format (binary) and back.

Is it possible to use uuid values for the primary generated column and store it as binary type under the hood?

**Comment by elovin** [comment]
@igat64 you can add a varchar binary key and convert from/to string/Buffer with the event listeners BeforeInsert, BeforeUpdate, AfterUpdate ...

The only problem I have found so far is that 
`this.usersRepository.findOne(id); `
does not work if a Buffer id, you have to use a workaround e.g. 

```
 return this.usersRepository.findOne({
            where: {
                id: uuidBuffer.toBuffer(id)
            }
        });
```

**Comment by Alia5** [comment]
My workaround, short and simple.
Probably also related to #7470

```typescript
const uuidTransformer {
    to: (uuid: string|undefined) => uuid ? Buffer.from(uuid.replace(/-/g, ''), 'hex') : uuid,
    from: (bin: Buffer) => `${bin.toString('hex', 0, 4)}-${bin.toString('hex', 4, 6)}-${
        bin.toString('hex', 6, 8)}-${bin.toString('hex', 8, 10)}-${bin.toString('hex', 10, 16)}`
};

@Entity()
export class Room {
    @PrimaryColumn({
        type: 'binary',
        length: 16,
        generated: false,
        transformer: uuidTransformer,
        default: () => 'UNHEX(REPLACE(UUID(), \'-\', \'\'))'
    })
    public id!: string;
    /// ...
}
```

**Comment by maxbethke** [comment]
With @Alia5's workaround I run into [ this problem](https://github.com/typeorm/typeorm/issues/7643) caused by the `default` property not setting id before the Entity Manager tries to reload the entity after a `.save()`.

Any ideas about this?

**Comment by leonceaklin** [comment]
The Workaround by @Alia5 also doesn't work for me when using relationships. For example when I query a many-to-many relationship, the value transformer is not applied. I created a [new issue (10365)](https://github.com/typeorm/typeorm/issues/10365) for this but did not get any answer. I'd like to fix the problem with a PR but don't know where to start. Help appreciated.

**Comment by hitesh-pathak** [comment]
> To not make this another [DenverCoder](https://xkcd.com/979/)-like situation
> 
> My workaround, short and simple. Probably also related to #7470
> 
> ```ts
> const uuidTransformer {
>     to: (uuid: string|undefined) => uuid ? Buffer.from(uuid.replace(/-/g, ''), 'hex') : uuid,
>     from: (bin: Buffer) => `${bin.toString('hex', 0, 4)}-${bin.toString('hex', 4, 6)}-${
>         bin.toString('hex', 6, 8)}-${bin.toString('hex', 8, 10)}-${bin.toString('hex', 10, 16)}`
> };
> 
> @Entity()
> export class Room {
>     @PrimaryColumn({
>         type: 'binary',
>         length: 16,
>         generated: false,
>         transformer: uuidTransformer,
>         default: () => 'UNHEX(REPLACE(UUID(), \'-\', \'\'))' // using maria-db so UUID_TO_BIN does not exist
>     })
>     public id!: string;
>     /// ...
> }
> ```
> 
> For sake of completion: with relations:
> 
> Click me!

Thanks a lot - this works for me with querybuider and with Many-One and One-Many relations too :D

**Comment by nalbertcerqueira** [comment]
> To not make this another [DenverCoder](https://xkcd.com/979/)-like situation
> 
> My workaround, short and simple. Probably also related to #7470
> 
> ```ts
> const uuidTransformer {
>     to: (uuid: string|undefined) => uuid ? Buffer.from(uuid.replace(/-/g, ''), 'hex') : uuid,
>     from: (bin: Buffer) => `${bin.toString('hex', 0, 4)}-${bin.toString('hex', 4, 6)}-${
>         bin.toString('hex', 6, 8)}-${bin.toString('hex', 8, 10)}-${bin.toString('hex', 10, 16)}`
> };
> 
> @Entity()
> export class Room {
>     @PrimaryColumn({
>         type: 'binary',
>         length: 16,
>         generated: false,
>         transformer: uuidTransformer,
>         default: () => 'UNHEX(REPLACE(UUID(), \'-\', \'\'))' // using maria-db so UUID_TO_BIN does not exist
>     })
>     public id!: string;
>     /// ...
> }
> ```
> 
> For sake of completion: with relations:
> 
> Click me!

Thanks a lot man ! This saved me :D

**Comment by mkfyi** [comment]
Thanks @Alia5, but we should check in `from` if `bin` is actually not `null`, otherwise the `ApplyValueTransformers` might fail with this message: `TypeError: Cannot read properties of null (reading 'toString')`.

### `uuid-value.transformer.ts`
  
```TypeScript
import { ValueTransformer } from 'typeorm';

class UuidValueTransformer implements ValueTransformer {
  public to(uuid: string | undefined | null): Buffer | null {
    return uuid ? Buffer.from(uuid.replace(/-/g, ''), 'hex') : null;
  }

  public from(bin: Buffer | undefined | null): string | null {
    return bin
      ? `${bin.toString('hex', 0, 4)}-${bin.toString('hex', 4, 6)}-${bin.toString(
          'hex',
          6,
          8,
        )}-${bin.toString('hex', 8, 10)}-${bin.toString('hex', 10, 16)}`
      : null;
  }
}

export const uuidValueTransformer = new UuidValueTransformer();
```

I also wrapped the column definitions into own decorators to reduce the amount of the same column definitions when working with multiple entities.

### `typeorm.decorators.ts`

```TypeScript
import { Column, PrimaryColumn } from 'typeorm';
import { uuidValueTransformer } from '../database/uuid-value.transformer';

export const PrimaryGeneratedBinaryUuidColumn = (): ReturnType<
  typeof PrimaryColumn
> =>
  PrimaryColumn({
    type: 'binary',
    length: 16,
    generated: false,
    transformer: uuidValueTransformer,
    default: () => "UNHEX(REPLACE(UUID(), '-', ''))",
  });

export const BinaryUuidColumn = (
  name?: string,
): ReturnType<typeof Column> =>
  Column({
    type: 'binary',
    name,
    length: 16,
    generated: false,
    transformer: uuidValueTransformer,
    unique: false,
  });
```

So your example would look like:

```diff
@Entity()
export class Room {
-  @PrimaryColumn({
-    type: 'binary',
-    length: 16,
-    generated: false,
-    transformer: uuidTransformer,
-    default: () => "UNHEX(REPLACE(UUID(), '-', ''))",
-  })
+  @PrimaryGeneratedBinaryUuidColumn()
  public id!: string;

  @Column({ length: 100, unique: true })
  public name!: string;

  @OneToMany(() => Member, (member: Member) => member.room)
  @JoinColumn()
  public members!: Member[];
}

@Entity()
export class Member {
-  @PrimaryColumn({
-    type: 'binary',
-    length: 16,
-    generated: false,
-    transformer: uuidTransformer,
-    default: () => "UNHEX(REPLACE(UUID(), '-', ''))",
-  })
+  @PrimaryGeneratedBinaryUuidColumn()
  public id!: string;

  @Column({ length: 100 })
  public name!: string;

-  @Column({
-    type: 'binary',
-    length: 16,
-    generated: false,
-    transformer: uuidTransformer,
-    unique: false,
-  })
+  @BinaryUuidColumn()
  public roomId!: string;

  // eslint-disable-next-line @typescript-eslint/no-unsafe-return
  @ManyToOne(() => Room, (room: Room) => room.members)
  @JoinColumn()
  public room!: Room;
}
```

**Comment by festo** [comment]
Whoever stumbles upon this, make sure you handle the FindOperators as well. 
```ts
if (InstanceChecker.isFindOperator(value)) {
  // Pass through FindOperators (e.g. IsNull()) without transforming
  return value
}
```
