### ISSUE TITLE
Entity Listeners event parameter

### ISSUE THREAD

**Issue by TheKiteEatingTree** [typeorm/typeorm#319]
Is there any reason entity listeners are not passed an event object like subscribers are?  I get that some of the properties are useless in an entity listener, but at least the entityManager would be nice to have unless there's some way to access it that I'm missing.  I could work on a PR for this if it makes sense.

**Comment by pleerock** [comment]
The reason behind this is the idea of typeorm and data mapper - your models should be dummy. By providing entity manager to your models you are making them _complex_ - now your entities aren't just dummy logic, they also do a complicated logic and operations using entity manager. I'm not sure yet if we should go this way.

**Comment by TheKiteEatingTree** [comment]
That explanation makes sense to me.  Thanks!

**Comment by pleerock** [comment]
Lets close it for now then
