### ISSUE TITLE
EntityMetadataNotFound - Reporting no metadata from connection when inside a class

### ISSUE THREAD

**Issue by ambiguities** [typeorm/typeorm#3197]
**Issue type:**

[x] question
[?] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`

**Steps to reproduce with a small repository showing the problem:**

1. clone: [typeorm-oclif-entitymetadatanotfound](https://github.com/ambiguities/typeorm-oclif-entitymetadatanotfound)
2. run ```npm install```
3. run ```npm run prepack```
3. run ```node bin/run hello```

**Reflection**
You will notice that the entity is found in ```src/index.ts```, but in ```src/commands/hello.ts``` it is not. 
If you inspect the connection from inside the hello.ts class method, it clearly shows that the entity and the metadata exist. Why does this occur? This is a complete roadblock for me.

**Comment by pleerock** [comment]
are you sure you are running code inside `src/commands/hello.ts` after you run code inside `src/index.ts` ? put console.logs into createConnection block and before not working getConnection inside hello.ts and make sure flow is correct.

**Comment by ryuuji3** [comment]
Out of curiosity, would it work if you put ```import "reflect-metadata";``` at the top of hello.ts? I'm noticing that it's absent therein.

**Comment by ryuuji3** [comment]
I played around with this for a bit.
I was able to make it work by getting the repository using the entity manager;

```ts
const connection = await getConnection();
const em = connection.manager;
const repository = em.getRepository(User);
```

**Comment by ambiguities** [comment]
@ryuuji3 I tried adding `import "reflect-metadata";` to the top of hello.ts and tried the code you suggested.
I'm now getting: 

```
RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?
    at new RepositoryNotFoundError (/tmp/broken-demo/src/error/RepositoryNotFoundError.ts:10:9)
    at EntityManager.getRepository (/tmp/broken-demo/src/entity-manager/EntityManager.ts:720:19)
    at Hello.run (/tmp/broken-demo/src/commands/hello.ts:18:27)
```

**Comment by ryuuji3** [comment]
Hmmm...
Oh, I did run with ts-node instead of building and running node... 

I'll check to see what I did besides though

**Comment by ambiguities** [comment]
@ryuuji3, again I thank you for your time working on this. I apologise, I forgot to put one of the build commands in the original comment. I have edited it now.

I looked into it further and it does seem that the node process is creating a bunch of child processes. Thanks to your suggestion I was able to get it working. I created a database connection method and using that inside of the `async run()` method. 

I find it strange that I was able to create the connection inside of the parent process and then when I used console.log in the child process I was able to see all of the connection information including entities and metadata but was unable to use any of it. ¯\_(ツ)_/¯

Although this was a configuration issue it might be worth looking into why it is visible but not useable.

Again, thank you for the time you invested. It is greatly appreciated.

@pleerock Your lack of patience and aggresive language not only makes you look bad but also affects the PR of the projects you work on.

**Comment by jamesrobertclarke** [comment]
@pleerock Thank you for responding. A majority of my work is fixing other peoples mistakes so I not only understand but can empathise. I really do appreciate you even taking the time to look at my issue. You work on a very valuable and popular project and unfortunately the voices that complain are usually louder and more often than those who appreciate you. I for one appreciate you for helping to maintain this awesome project.

@pleerock @ryuuji3 I hope the new year brings you both joy and prosperity.

**Comment by ambiguities** [comment]
@pleerock Thank you for responding. A majority of my work is fixing other peoples mistakes so I not only understand but can empathise. I really do appreciate you even taking the time to look at my issue. You work on a very valuable and popular project and unfortunately the voices that complain are usually louder and more often than those who appreciate you. I for one appreciate you for helping to maintain this awesome project.

@pleerock @ryuuji3 I hope the new year brings you both joy and prosperity.

**Comment by xavimb** [comment]
Hi there, I'm having the same issue and after digging a bit I found that the problem is in the comparison used inside the method `findMetadata` of the connection class. More specifically in this line https://github.com/typeorm/typeorm/blob/df771ca37f73cfca69c5df40df97534e7ead8324/src/connection/Connection.ts#L460

The problem is that after compiling TS to JS, classes are converted to functions and inheritance doesn't work anymore. That's why it works with ts-node and not with javascript, like @ryuuji3 mentioned. This could be fixed adding another comparison similar to:
```
if (typeof target === 'function' && typeof metadata.target === 'function') {
  return target.toString() === metadata.target.toString();
}
```

**Comment by vlapo** [comment]
@xavimb https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof

First example:
```javascript
function Car(make, model, year) {
  this.make = make;
  this.model = model;
  this.year = year;
}
var auto = new Car('Honda', 'Accord', 1998);

console.log(auto instanceof Car);
// expected output: true

console.log(auto instanceof Object);
// expected output: true
```

**Comment by pleerock** [comment]
> The problem is that after compiling TS to JS, classes are converted to functions and inheritance doesn't work anymore. 

@xavimb that's a wrong statement

**Comment by xavimb** [comment]
@pleerock yes, that might be wrong. I couldn't figure out what was the reason, though
