### ISSUE TITLE
Entity Listener @BeforeUpdate() Potential Inconsistency

### ISSUE THREAD

**Issue by duranhumes** [typeorm/typeorm#3198]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Update code
```ts
const manager = getManager()
const data = { userName: 'My new UserName' }

const user = await manager.findOne(User, { id: some-id })

const tempUser = new User()
Object.assign(tempUser, data)
await manager.update(User, String(user.id), tempUser)
```

Also tried
```ts
const userRepository = manager.getRepository(User)

Object.assign(user, data)
await userRepository.save(user)
```

Listener in entity
```ts
@BeforeUpdate()
public beforeUpdate() {
    this.email = this.email.toLowerCase()
    this.userName = this.userName.replace(/\s+/g, '-').toLowerCase()
}
```

For some reason the above would work beautifully on the first run, then I'd run the update a second time immediately after and the `@BeforeUpdate()` it fires again but the data being saved doesn't seem to be the same thats logged out. I'm not sure if I'm doing something wrong, spent the day searching for answers. Any help would be much appreciated.

Logs from console.table(this) at the top of the listener function and again at the bottom.

**First run**
<img width="1000" alt="screen shot 2018-12-04 at 8 04 36 pm" src="https://user-images.githubusercontent.com/31602742/49483206-5421f480-f800-11e8-83ea-c6bd4668f276.png">

**Second run**
<img width="1000" alt="screen shot 2018-12-04 at 8 08 07 pm" src="https://user-images.githubusercontent.com/31602742/49483233-6e5bd280-f800-11e8-9cf1-bca51552a249.png">

**Comment by pleerock** [comment]
@duranhumes did you figure it out?

**Comment by duranhumes** [comment]
Yeah, this seems to work, consistently. The difference is that I'm passing in the found user instance to the `Object.assign` call.

```js
const manager = getManager()

const foundUser = manager.findOne(User, { id: 'some-id' })
const newUserData = { email: 'my@newemail.com' }

const tempUser = new User()
Object.assign(tempUser, foundUser, newUserData)

const updatedUser = await manager.save(User, tempUser)
```
