### ISSUE TITLE
Primary key value not detected with alias'ed Column

### ISSUE THREAD

**Issue by andreasrueedlinger** [typeorm/typeorm#32]
When using a Primary key colum with an alias, the persisting of an entity fails:
`Given object does not have a primary column, cannot transform it to database entity.`
The problem is that the PlainObjectToDatabaseEntityTransformer uses `metadata.primaryColumn.name` instead of `metadata.primaryColumn.propertyName`.
Could you please fix this? I hope there are not too many other cases where an alias breaks the whole application.

**Comment by pleerock** [comment]
Looks like I already [did this](https://github.com/typeorm/typeorm/blob/master/src/query-builder/transformer/PlainObjectToDatabaseEntityTransformer.ts#L39) in master. I was planning to release a new version next week, it contains lot of new features and breaking changes. Are you okay to wait? (if you are not I can release urgently)

> I hope there are not too many other cases where an alias breaks the whole application.

I hope too. Custom column names isn't well tested feature, no one test or sample using it. So I don't recommend to use it yet, but if you need it, then become a first tester and will fix all issues quickly together :)

**Comment by andreasrueedlinger** [comment]
Great, I did not realize you already refactored a lot. It does not hurry with the new version.
And we can do some "testing" when we are evaluating typeorm for our project where we have a lot of custom column names.

**Comment by andreasrueedlinger** [comment]
Here is another bug:
https://github.com/typeorm/typeorm/blob/master/src/persistment/PersistOperationExecutor.ts#L488
propertyName should be name in L488 and L493.

**Comment by pleerock** [comment]
fixed in 1b4295b

**Comment by andreasrueedlinger** [comment]
When are you planning this next release now?

**Comment by pleerock** [comment]
there are few things left, and I planned to release it on Monday - Thursday. But I can do release right now, if you need it

**Comment by andreasrueedlinger** [comment]
Yes that would be great

**Comment by pleerock** [comment]
**0.0.2-alpha.63**, there are some breaking changes, mostly in the connection options, take a look on connection options interface in the docs
