### ISSUE TITLE
Bug in getManyAndCount

### ISSUE THREAD

**Issue by d-bechtel** [typeorm/typeorm#320]
Hi,

i'm bulding the following query with the QueryBuilder:
`SELECT     activity.id, 
           b.matchedtilecount, 
           count(activity.id) AS tilecount 
FROM       activity activity 
INNER JOIN tile_activities_activity_id activity_tile 
ON         activity_tile.activityid=activity.id 
INNER JOIN tile tile 
ON         tile.id=activity_tile.tileid 
INNER JOIN (SELECT count(activityid) AS matchedtilecount, tile_activities_activity_id.activityid FROM tile INNER JOIN tile_activities_activity_id ON tile.id = tile_activities_activity_id.tileid WHERE tile.id IN (:tiles) GROUP BY activityid) b
ON         b.activityid = activity.id 
GROUP BY   activity.id 
HAVING     b.matchedtilecount = :tileCount 
OR         tilecount <= b.matchedtilecount 
ORDER BY   activity.end_date DESC`

if i call it with query.getMany(), i will get my expected result. If i call it with getManyAndCount() i will get an error.
Query failed: 
`SELECT DISTINCT(distinctalias.activity_id) AS ids_id, 
                distinctalias.activity_end_date 
FROM            ( 
                           SELECT     activity.id, 
                                      b.matchedtilecount, 
                                      count(activity.id) AS tilecount 
                           FROM       activity activity 
                           INNER JOIN tile_activities_activity_id activity_tile 
                           ON         activity_tile.activityid=activity.id 
                           INNER JOIN tile tile 
                           ON         tile.id=activity_tile.tileid 
                           INNER JOIN (SELECT count(activityid) AS matchedtilecount, tile_activities_activity_id.activityid FROM tile INNER JOIN tile_activities_activity_id ON tile.id = tile_activities_activity_id.tileid WHERE tile.id IN [2,3] GROUP BY activityid) b
                           ON         b.activityid = activity.id 
                           GROUP BY   activity.id 
                           HAVING     b.matchedtilecount = 2
                           OR         tilecount <= b.matchedtilecount) distinctalias 
ORDER BY        distinctalias.activity_end_date DESC limit 50`

error during executing query:Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.activityId FROM tile INNER JOIN tile_activities_activity_id ON tile.id = ti' at line 1

**Comment by pleerock** [comment]
Hi, please provide a code sample with your entity and query you are building using query builder, so I can debug it

**Comment by D4edalus** [comment]
@d-bechtel 
please post the code, i'm running into similar issues.

meanwhile you can use a workaround like this probably (assuming the query generated with getMany() is working): 
https://github.com/typeorm/typeorm/issues/313#issuecomment-282470289

**Comment by d-bechtel** [comment]
here is my code. i have removed some fields which are not relevant. 
https://gist.github.com/d-bechtel/d84f9b0e9ccf131161a521e97c7c0830

**Comment by d-bechtel** [comment]
how is the status for this bug?

**Comment by pleerock** [comment]
I can't confirm its a bug. Your code is complex, you should have provide a minimal reproduction example without subqueries and everything else which are not root case of your issue. In your code you select `activity.id`, `b.matchedTileCount`, `COUNT(activity.id) as tileCount`. You don't actually select entity. Thats why you should not use `getMany` or `getManyAndCount`. You should use `getRawMany` or `getRawOne`.

**Comment by AlexMesser** [comment]
I have reproduced this issue but unfortunatelly it's not resolvable, because of COUNT operation specifics in `getManyAndCount()`. Consider executing separate query by yourself.

**Comment by Jorgevillada** [comment]
This has happened to me too, I do not know if it is a bug, it happens when the entity id is not selected (PrimaryGeneratedColumn)
```javascript
manager.createQueryBuilder(Identity, "idn")
            .select("idn.uuid").getManyAndCount();
```
returns [ [],2 ]

```javascript
manager.createQueryBuilder(Identity, "idn")
            .select("idn.id")
            .addSelect("idn.uuid").getManyAndCount();
```
returns [[{..}, {..}], 2]

**Comment by pleerock** [comment]
@Jorgevillada entity must be selected, its a requirement if you get non-raw results.

**Comment by BasirBaidya** [comment]
Hi, I have faced similar type of issue while creating a query builder:
I have noticed that if the query contain `HAVING` statement then `getManyAndCount()` total count is not return the exact result. It seems that HAVING filter is not considering by `getManyAndCount()` for returning the total count value.

` 
const [getStories, total] = await connection.getRepository(Tbl_story).createQueryBuilder("s")
            .select()
            .innerJoin(Tbl_storytags, "t", "t.story_id = s.story_id")
            .where(
              "s.story_status_id=3 AND s.isfeature=1 AND t.tag_id IN (:tags)",
              { tags: data.story_tags }
            )
            .having("COUNT(DISTINCT t.tag_id)=:tagCount", {
              tagCount: data.story_tags.length,
            })
            .groupBy("t.story_id")
            .orderBy("s.posted_on", "DESC")
            .skip(skip)
            .take(take)
            .getManyAndCount();`

**Comment by mickaelmesdocteurs** [comment]
Hi, I got the same problem with `addSelect`, `having` and `getManyAndCount`.
```ts
  async brokenFn() {
    const qb = this.repository.createQueryBuilder();
    qb.addSelect('1000', 'distance');
    qb.having('distance < :val', { val: 1001 });
    const error = await qb.getManyAndCount();
  }
```
Leads to the following error: `QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column 'distance' in 'having clause' `

@pleerock Is there any workaround to achieve this ?

Thanks for any tips

**Comment by oNguyenThiThuy** [comment]
@mickaelmesdocteurs Did you resolve your issue. Currently, I face the same :(

> Hi, I got the same problem with `addSelect`, `having` and `getManyAndCount`.
> 
> ```ts
>   async brokenFn() {
>     const qb = this.repository.createQueryBuilder();
>     qb.addSelect('1000', 'distance');
>     qb.having('distance < :val', { val: 1001 });
>     const error = await qb.getManyAndCount();
>   }
> ```
> 
> Leads to the following error: `QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column 'distance' in 'having clause' `
>

**Comment by mickaelmesdocteurs** [comment]
`getManyAndCount` consists in two queries.
First, the actual query with the results.
Then, the 'count all' query.

When logging these, I realize the second query does not include the `addSelect` statement but it does includes the `having` condition. So here the example : 
```js
 async brokenFn() {
    const qb = this.repository.createQueryBuilder();
    qb.addSelect('1000', 'distance');
    qb.having('distance < :val', { val: 1001 });
    const error = await qb.getManyAndCount();
  }
```
Produce the two following queries:
```sql
-- Will succeed
SELECT `DemoTable`.`id` AS `DemoTable_id`, 1000 AS `distance` FROM `DemoTable` `DemoTable` WHERE 1 HAVING distance < ? -- PARAMETERS: [1001]

-- Will fail, addSelect is not included
SELECT COUNT(1) AS `cnt` FROM `DemoTable` `DemoTable` WHERE 1 HAVING distance < ? -- PARAMETERS: [1001]
```

My workaround was to use the 'getMany' instead of `getManyAndCount`, and make a custom `count` query
```js
const qb = this.repository.createQueryBuilder();
qb.addSelect('1000', 'distance');
qb.having('distance < :val', { val: 1001 });
const values = await qb.getMany();

const cpt = await this.repository.query('SELECT 1000 as distance, count(1) as cpt FROM DemoTable d HAVING distance < 1001');
```

But if you have time, the best thing to do is to fix the `getManyAndCount` (2nd query) and make a pull request
