### ISSUE TITLE
Can the CLI work directly against Typescript based schema files?

### ISSUE THREAD

**Issue by cuzzlor** [typeorm/typeorm#3201]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi all firstly wanted to say thanks for TypeORM it is really fantastic. My question is around migrations and their use / state for SQLite and typescript based dev.

I’m successfully running using typescript under ts-node. My CLI config appears to be fine in terms of being able to scaffold new entity classes or empty migrations. I can run my app with the synchronize setting enabled and my database automagically is created or gets updated which is fantastic.

I’m wondering if I should be able to generate migrations in this scenario? Every time I use the CLI sync command it doesn’t create or update anything (no changes detected) and same if I generate a migration it’s always empty. It can connect to/create the database ok, no errors.

Is this is because my entities are typescript and the CLI won’t be able to read them?

If my guess is correct, is there any way of setting up typescript support for the CLI eg configuring it to import ts-node/register and to be able to read the typescript based entity files?

**Comment by cuzzlor** [comment]
thanks for the reply, i have only been using the sync option because i can't get generated migrations working.

the process i've been trying is to delete the sqlite db file, then run typeorm schema:generate -n 'Initial', i would expect this to generate me one migration containing all the schema, does that sound right?

if this scenario is supposed to work, i'll try create a minimal to replicate the issue and post that.

thanks for your time!

**Comment by pleerock** [comment]
`sync` is for development purpose (it can be used in production as well, depend on your schema sync strategy and preferences). When you have it enabled database schema will be synced automatically when you run the app. Since schema is synced when you run it there is nothing new to put into migration. Try to disable sync, make some changes in entities and run migration generation and see how it works.

**Comment by wederer** [comment]
The command usage is `typeorm migration:generate -n SomeMigration`. What command are you using exactly?

**Comment by pleerock** [comment]
I'll close this issue if there is no more questions.

**Comment by karinehovhannisyan** [comment]
Hi, @cuzzlor ! 
Have you figured what the issue was? I face something similar.

**Comment by wederer** [comment]
@karinehovhannisyan See [here](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md#running-and-reverting-migrations) for an example with ts-node which enables you to use `.ts` files.

**Comment by karinehovhannisyan** [comment]
@wederer ,
Thanks, I've had a look at the source. I use everything as mentioned. I also am able to create migrations and execute them, but no migrations can be generated. Any ideas what could go wrong?

**Comment by wederer** [comment]
@karinehovhannisyan Is there an error message or what is the problem?

**Comment by karinehovhannisyan** [comment]
@wederer no, nothing. Just the message says there is nothing to migrate, whereas there is.

**Comment by wederer** [comment]
@karinehovhannisyan Then your ormconfig is not correct. The cli is not finding the migration files.

**Comment by karinehovhannisyan** [comment]
@wederer would you mind to have a quick look at it?
