### ISSUE TITLE
Allow ActiveRecord to specify connection

### ISSUE THREAD

**Issue by chiangf** [typeorm/typeorm#3205]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

From other closed issues (e.g. https://github.com/typeorm/typeorm/issues/2052), ActiveRecord does not support multiple connections.

Is it possible to specify the connection that an ActiveRecord should use?

E.g.
```
@Entity({ connection: 'db1Connection' })
export class Foo extends BaseEntity {
  ...
}
```

where the named connection matches with the created connections:
```
const connections = await createConnections([{
    name: "db1Connection", // matches connection in Foo
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "root",
    password: "admin",
    database: "db1",
    entities: [__dirname + "/entity/*{.js,.ts}"],
    synchronize: true
},
...
]);
```

From https://github.com/typeorm/typeorm/blob/master/src/repository/BaseEntity.ts#L84, it doesn't look like it currently looks for that when calling `getConnection`, but it could potentially pass in the connection name?

This would be especially useful when needing to migrate ActiveRecord entities from one RDS to another.

**Comment by vlapo** [comment]
If target of this issue is some default connection for specific active record entity. What about define 
```typescript
class BaseEntity {

    public static defaultConnectionName: string = "default";

    // ...

    static getRepository<T extends BaseEntity>(this: ObjectType<T>): Repository<T> {
            const connection: Connection = (this as any).usedConnection || getConnection((this as any).defaultConnectionName || "default");
            return connection.getRepository<T>(this);
    }
}
```
So you should overwrite your entity like:
```typescript
@Entity()
export class Example extends BaseEntity {

    public static defaultConnectionName = "nondefaultnameconnection";

    @PrimaryGeneratedColumn()
    id!: number;

    @Column()
    name: string;
}
```
Do not have such experience with active record but would not this help @pleerock ?
But still @chiangf. Why do you not use `useConnection` method in `BaseEntity`?

**Comment by chiangf** [comment]
@vlapo Yup, calling `SubEntity.useConnection()` would work, I was just thinking that there might be a way to define this upfront.

That being said, the use-case that I'm thinking of (e.g. migrating from one RDS to another) is a pretty ephemeral thing, so I'm fine with calling `useConnection` for each model when that happens. I'll close the question, thanks!

**Comment by Crazy-kun** [comment]
You can set `usedConnection` property with connection name in entity. Like this:
```@Entity()
export class Foo extends BaseEntity {
    usedConnection = "db1Connection";
      ...
}```
