### ISSUE TITLE
Unable to update the length of a column because typeorm would drop the column first

### ISSUE THREAD

**Issue by laukaichung** [typeorm/typeorm#3216]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9`

**Steps to reproduce or a small repository showing the problem:**

[x] `postgres`

I couldn't alter the size of an existing column. These are the queries run by `typeorm` on the altered column:

````
query: ALTER TABLE "feedback" DROP COLUMN "plainText"
query: ALTER TABLE "feedback" ADD "plainText" character varying(4000) NOT NULL
query failed: ALTER TABLE "feedback" ADD "plainText" character varying(4000) NOT NULL
error: { error: column "plainText" contains null values
````
I don't understand why typeorm would drop the existing column just for updating the size of it. If the column is non-null, dropping it and adding it back would cause data loss and an error. 
I would expect a query like this to update the column size:
````
ALTER TABLE feedback ALTER "plainText" TYPE varchar(4000);
````
Is it a bug in postgres? 

Table:

````
import {Field, ID, Int, ObjectType} from "type-graphql";
import {
    Column,
    CreateDateColumn,
    Entity,
    Index,
    JoinColumn,
    ManyToOne,
    PrimaryGeneratedColumn,
    UpdateDateColumn
} from "typeorm";

@ObjectType()
@Entity()
@Index("suggestion_userId_modelId", (entity: Feedback) => [entity.userId,entity.modelId])
export class Feedback{

    @Field(type=>ID)
    @PrimaryGeneratedColumn()
    id: number;

    @Field(type=>Int)
    @Column({type:'int'})
    modelId:number;

    @Field(type=>Int)
    @Column({type:'int'})
    userId;

    @Field(type=>String)
    @Column({type:'varchar',length:1000})
    plainText:string;

}

````

**Comment by pleerock** [comment]
It is by design. Why? Because not all databases gracefully support this feature, and implementing it to cover all edge cases is too complex.

Lets say you have a length set to `100`. And you have data in. Now lets say you changed it to `10`. What should happen with your data? Right, data loss. Some database ignore this and allow data loss, more strict databases will give you error. Do people want to have errors when they change their `length`? No.

I suggest you to manually write migration if in your case you can safely convert data length.

**Comment by baio** [comment]
uh oh, that's should be done better at least some clear guidelines how to do this properly since as I suspect the whole word now just run scripts directly on db which is road to hell.
