### ISSUE TITLE
Extend QueryBuilder and DataMapper to map Business Model into EAV structure

### ISSUE THREAD

**Issue by stalniy** [typeorm/typeorm#3217]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Description**:
I'd like to extend functionality of typeorm to support [Entity-Attribute-Value](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model) database schema but keep it simple on Business level. So, I can effectively use `QueryBuilder` and Domain Models without exposing information to application level about database structure

So, my question is:
Where can I start? I need to override some of QueryBuilder implementations so they send queries into different tables based on specified attributes and probably EntityManager to properly map the end result into Domain model.

For example:
I have a `Person` entity which has `firstName`, `lastName` and `age` attributes. `firstName` and `lastName` attributes are stored in `entity_attribute_values_string` and `age` in `entity_attribute_values_int`. Eventuall I want to query the data like this:

```js
QueryBuilder.from(Entity)
  .where('age > :age', { age: 10 })
  .where('lastName = :lastName', { lastName: 'Doe' })
```

Could you please recommend where to start looking at in the code and whether it's possible to do in typeorm architecture?

**Comment by pleerock** [comment]
its JavaScript, code is near you, so everything is possible. Everything else is how good your design is, how much make really makes sense and what problems you a going to face and fix.

What you described here is pretty abstract, and I don't have everything that is in your head, so my answer is go ahead and try to implement your ideas.

Im quite satisfied with current `find options` - they are separate from database structure and cover 90% of user queries. If user need something more than 90% he most likely need something specific that usually can't be covered with proper abstraction.

**Comment by stalniy** [comment]
Sure, everything is possible. 
What I'm asking is about direction and maybe some typeorm design decision log and/or diagrams. Whatever what can help me.

I goal is to implement EAV ORM on top of typeorm, similar to http://mvpdev.github.io/django-eav/ .

**Comment by pleerock** [comment]
You need to be more specific about your questions and I'll try answer you.

> typeorm design decision log and/or diagrams. 

log is in my head, there is no time to make them in a diagrams. So just ask.

> My goal is to implement EAV ORM on top of typeorm, similar to http://mvpdev.github.io/django-eav/ .

sorry not familiar with django.

**Comment by stalniy** [comment]
Do you think this is something easy to achieve or I'm looking for unicorns? :)

**Comment by pleerock** [comment]
EAV is actually treated as an anti-pattern. What is the point to implement it?

**Comment by stalniy** [comment]
The point is that sometimes this is the only way to do the job. Take a look at Grakn (https://grakn.ai) for the example and you will understand that there are domains where EAV is a valid choice. 

Singleton is also treated as anti-pattern. 

So, I think it should be the argument :)

**Comment by pleerock** [comment]
Singleton is a solution to the language limitation which lacks proper solution for the real problem, while any such solution to a real problem is treated as anti-pattern because of the incompatibility of the designs. 

EAV is bad from all perspectives. Maybe you are right, but I didn't ever face issue that only EAV can resolve.

What you are saying is possible, just dig into QueryBuilder internals, but it has a very high complexity. I don't think we would ever support this in TypeORM.

**Comment by stalniy** [comment]
I see. Thanks for your time

**Comment by stalniy** [comment]
Good point :) 

You can also take a look at PHP based version on top of Doctrine ORM: https://github.com/VincentChalnot/SidusEAVModelBundle

Also, I want to point that this is the only way to store any data for information integration systems (ontology based systems) like Palantir - https://youtu.be/dVsx4I8gkKk

**Comment by stalniy** [comment]
By the way, later data can be replicated & searched by elastic search. 

So, eventually dB is required only for acid & key lookups

**Comment by ethanorlanderypm** [comment]
@stalniy did you end up implementing some form of EAV in TypeORM?

I need to do this as well and am hoping you can save me some hours of mess-ups if you've already come up with a good implementation.

**Comment by stalniy** [comment]
I did this using sequelize. Frankly speaking, you don’t need ORM for EAV. Use something like knex.js and write your own.
