### ISSUE TITLE
Cascade delete doesn't work in one-to-one relationship 

### ISSUE THREAD

**Issue by jalooc** [typeorm/typeorm#3218]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Not sure it's a bug or a feature, but here it goes: For the one-to-one relationship, cascade delete works only for the inverse side.

Having entities like this:
```typescript
@Entity()
class User {
  @PrimaryGeneratedColumn('uuid')
  id!: string

  @OneToOne(
    () => Profile,
    profile => profile.user,
    { cascade: true, onDelete: 'CASCADE' },
  )
  @JoinColumn()
  profile!: Profile
}

@Entity()
class Profile {
  @PrimaryGeneratedColumn('uuid')
  id!: string

  @OneToOne(
    () => User,
    user => user.profile,
    { onDelete: 'CASCADE' }, // This line doesn't actually make any difference
  )
  user!: User
}
```
what happens is:
```typescript
await getManager().remove(someProfile) // The profile gets deleted along with the user
```
but
```typescript
await getManager().remove(someUser) // The user gets deleted, but the profile stays in place
```

How I would like it to work, is the related entities to be actually removed when I define `onDelete: 'CASCADE'` on both sides of the relation.

**Comment by pleerock** [comment]
@jalooc do you know how SQL's `onDelete` works? Because it requires this understanding to understand how it works in typeorm (it works same way)

**Comment by jalooc** [comment]
@pleerock I know how SQL's `ON DELETE` works, but wasn't aware that it's the only thing typeorm does when setting `onDelete: "CASCADE"`. Now I know :)

So, to get it right - there's no way to perform a cascade delete on one-to-one relation from both sides then? All I'm left with is programatic delete of both entities?

**Comment by mateothegreat** [comment]
Put your `@JoinColumn()` on the inverse side (on Profile).

**Comment by maximosdrr** [comment]
> your `@JoinColumn()` on the inverse side (on Profile).

If you do this it will create a circular dependence, so it doesn't works

**Comment by Deadpoolweid** [comment]
Why is this closed, however problem is still persist after 2 years?

**Comment by ashfaqnisar** [comment]
++

**Comment by isarojdahal** [comment]
still not working in 2023, Dec 14.

**Comment by tech-magnety-ai** [comment]
Sill not working :(

**Comment by hamza-trimulabs** [comment]
yeah, still not working!

**Comment by phosmium** [comment]
@imnotjames reopen, this is not solved, still a thing

**Comment by fullstackmaverick** [comment]
This is still an issue! Tried mostly all. I can't logically assign the ownership to the child side to handle case :/

**Comment by thekennysong** [comment]
STILL AN ISSUE HELP!

**Comment by sinapirani** [comment]
Still an issue

**Comment by joaoaugustogrobe** [comment]
Still an issue

**Comment by james-astra** [comment]
This is still an issue to this day, why was the ticket closed?

**Comment by skpn** [comment]
still an issue for me as well

I have multiple tables with one to one relationships to a single child table, meaning I don't want to add a one to one for every single parent table on the child, but just delete from the parent when needed

**Comment by antoineheseque** [comment]
After a few searches  with OneToOne relations, removing automatically with parent is possible only when JoinColumn is defined in child part, not in parent, in a bidirectional relation.
`@Entity()
class Parent {
  @PrimaryGeneratedColumn('uuid')
  id!: string

  @OneToOne(
    () => Parent,
    parent => children.parent,
    { cascade: true }, // Can be used to automatically save children when calling "*.save()" on Repository<Parent>.
  )
  children!: Children
}`

`@Entity()
class Children {
  @PrimaryGeneratedColumn('uuid')
  id!: string

  @OneToOne(
    () => User,
    user => user.profile,
    { onDelete: 'CASCADE' }, // Automatically remove associated Children when calling "*.remove()" or "*.delete()" on Repository<Parent>"
  )
  @JoinColumn()
  parent!: Parent
}`

**Comment by Bubuioc** [comment]
Do cascade works without setting inverse side?

**Comment by uribrod** [comment]
It still didn't work. Has anyone found a workaround? an option is to move the FK to the parent, but I don't like it so much

**Comment by ateso-rfuchs** [comment]
### Problem Description

I have the following setup:

* **Template Entity** (`@JoinColumn`) ↔ **File Entity** (`@OneToOne`)
* Config:

  ```ts
  onDelete: 'SET NULL',
  cascade: ['remove'] // on Template side
  ```

### Expected Behavior

* Deleting a **File** → Template reference should be set to `null` ✅
* Deleting a **Template** → should also delete the related **File** (cascade remove) ✅

### Actual Behavior

* Deleting a **File** → Template reference is set to `null` ✅
* Deleting a **Template** → related **File** is **not deleted** ❌
* If I change to `onDelete: 'CASCADE'`:

  * Deleting a **File** → also deletes the **Template** ❌
  * Deleting a **Template** → does **not** delete the **File** ❌

### Summary

Cascade `remove` does not seem to work correctly with a `ONE_TO_ONE` relation.
onDelete `CASCADE` does work only to one side

### Question

When will proper support for `cascade: ['remove']` on `ONE_TO_ONE` relations be fixed?
