### ISSUE TITLE
current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect. SERVER IS RUNNING ON localhost:4000

### ISSUE THREAD

**Issue by Sm03leBr00t** [typeorm/typeorm#3219]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hey and again same Issue like the quoted one:

#2270 

MongoDb asks to select the **new Url Parser**.

`(node:25768) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.` #

**Comment by vlapo** [comment]
There is `useNewUrlParser` option in mongodb connection. Set it to `true` if you are using mongodb driver that requires it. If you do not see `useNewUrlParser` option you are using `next` branch and this change is not merge yet.

**Comment by pleerock** [comment]
@vlapo thank you very much for your answer!
