### ISSUE TITLE
Create Many-to-One-Relation with unique column

### ISSUE THREAD

**Issue by loliman** [typeorm/typeorm#322]
Hi there,

I got two tables defiened like this:
```
@Entity("A")
export class Issue {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({default: ""})
    title: string;

    @ManyToOne(type => B)
    @JoinColumn()
    fk_B: B;
}
```
and
```
@Entity("B")
export class B {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    @Index({unique: true})
    title   : string;
}
```
Now I'm inserting one item into the db.
```
{"title": "Test_A, "fk_B": "Test_B"}
```
repo.persist() works fine here, the item is inserted into the db, A and B are created. Afterwards I'm trying to insert a new A-item with the same fk_B as before.
```
{"title": "Test_A_2, "fk_B": "Test_B"}
```
I would expect, that Test_A_2 is created, Test_B not. Test_A_2 should have the same fk-id as Test_A. But what I get is an ER_DUP_ENTRY.
Any suggestions, what I am doing wrong?

**Comment by icewind** [comment]
You are using OneToOne, but trying to insert ManyToOne. Same FK means you have several `A` referencing one `B` it is not OneToOne

**Comment by loliman** [comment]
Jep, I noticed that the second I submitted the request. I fixed that in my code, but the result is still the same. 
When I remove the unique parameter B is inserted two time, when I add the parameter the persist will result in an ER_DUP_ENTRY.

**Comment by icewind** [comment]
Can you show your code? How you're saving the entities.
For me
```
const first = await repository.persist(model);
const second = await secondRepository.create({ ... fk_b: first });
await repository.persist(second);
```
works fine

**Comment by loliman** [comment]
Right now I'm saving the entities like this

```
let bRepo = connection.getRepository(B);
let b = new B();
b.title = 'Test_B'

let aRepo = connection.getRepository(A);
let a = new A();
a.title = 'Test_A'
a.fk_B = B;
aRepo.persist(a); //Works, A and B are created

let a2 = new A();
a2.title = 'Test_A_2'
a2.fk_B = B;
aRepo.persist(a2); //ER_DUP_ENTRY
```

**Comment by icewind** [comment]
What database are you on?
I tried to recreate your example(using SQLite3) and everything works just fine. Try to drop your tables and create new. Maybe there is an issue with constraints.
My models
```typescript
@Entity()
export class Foo {

  @PrimaryGeneratedColumn()
  public id: number;

  @Column({ type: 'text', default: "" })
  title: string;

  @ManyToOne(type => Bar)
  bar: Bar;

}
```
```typescript
@Entity()
export class Bar {

  @PrimaryGeneratedColumn()
  public id: number;

  @Column('text')
  @Index({unique: true})
  public title: string;

}
```
and the code
```typescript
createConnection().then(async (connection) => {
  console.log('Connection created');

  const barRepo = connection.getRepository(Bar);
  const bar = barRepo.create({ title: 'first bar title' });
  await barRepo.persist(bar);

  const fooRepo = connection.getRepository(Foo);
  const foo1 = fooRepo.create({ title: 'first foo', bar });
  await fooRepo.persist(foo1);

  const foo2 = fooRepo.create({ title: 'second foo', bar });
  await fooRepo.persist(foo2);

});
```
as result I got one record in `bar` table

| id   | title |
| --- | --- |
| 1    | first bar title |

and two records in `foo`

| id   | title | bar |
| --- | --- | --- |
| 1 | first foo |	1 |
| 2 | second foo | 1 |

**Comment by loliman** [comment]
Okay, I found my issue. For some reason I forgot to surround the Bar persist witch a try catch. This works now:

```
createConnection().then(async (connection) => {
  console.log('Connection created');

  const barRepo = connection.getRepository(Bar);
  const bar = barRepo.create({ title: 'first bar title' });
  try {
    await barRepo.persist(bar);
  } catch (err) {
    bar = barRepo.createQueryBuilder('bar')
            .where('bar.title = :title')
            .setParameters({title: title})
            .getMany();
  }

  const fooRepo = connection.getRepository(Foo);
  const foo1 = fooRepo.create({ title: 'first foo', bar });
  await fooRepo.persist(foo1);
});
```

Thanks for your help!
