### ISSUE TITLE
createConnection should wait untill database tables are created from entities

### ISSUE THREAD

**Issue by P0oOOOo0YA** [typeorm/typeorm#3224]
**Issue type:**

[ *] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[* ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[* ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When creating a connection using `createConnection` my understanding is it makes a connection object add it to the connection pool and calls its connection method. then what happens if we get the connection from the pool and does a query against a table which is not created yet. (synchronize: true). I think when we use `await` before `createConnection` it should wait until all the entities are created.  

This is how i create a connection.

```ts
(async () => {
  try {
    await createConnection("dict");
  } catch (err) {
   throw err
  }
})()
```
Now make a query fast before database tables are created.

```ts
  try {
    const dictConnection = await getConnection("dict");
    const entries: Entry[] = [];

    lines2BeSaved.forEach(item => {
      const entry = new Entry();      
     // adding entry properties
      entries.push(entry);
    });

    const entryRepo = dictConnection.getRepository("entry");
    await entryRepo.save(entries)
  } catch (err) {
     thow err
  }
```
the result is the following error:
```
error: { [Error: SQLITE_ERROR: no such table: entry] errno: 1, code: 'SQLITE_ERROR' }
```
for now i solved my  problem by adding `setTimeout` around query.

**Comment by pleerock** [comment]
it does await everything. It can't be wrong. You definitely do something wrong, please check your code and reproduce your issue in minimal reproduction. You can pull typeorm example repository and check that it works.

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by zment** [comment]
Same pb for me with a ionic cordova angular app and a typeorm cordova connection

In my app.component constructor, I call :
await createConnection(dbOptions);

In my first displayed page, in IonViewWillEnter() or IonViewDidEnter(), I call :
const repository = getConnection().getRepository(Entity);

I can't await the createConnection and the getRepo is called too early
core.js:7376 ERROR RepositoryNotFoundError: No repository for "Entity" was found

**Comment by wintertime-inc** [comment]
> Same pb for me with an ionic cordova angular app and a typeorm cordova connection
> 
> In my app.component constructor or async ngOnInit(), I call :
> await createConnection(dbOptions);
> 
> In my first displayed page, in IonViewWillEnter() or IonViewDidEnter(), I call :
> const repository = getConnection().getRepository(Entity);
> 
> I can't await the createConnection and the getRepository(Entity) is called too early :
> core.js:7376 ERROR RepositoryNotFoundError: No repository for "Entity" was found
> 
> In ionic cordova app, it seems that I can't use ormconfig.json

I have a feeling that this is common issue, same for me, if process fire too quick, the connection doesn't wait for connected status, problem is that while you await createConnection() it is not connected yet for some milliseconds, looks like bug in library to me.
When I tested it with 100ms delay, everything works just fine, otherwise it doesn't work for 1st request on the app.

**Comment by lausek** [comment]
For typeorm v0.2.41 there seems to be an issue with the handling of parallel requests. In case of two requests happening at the same time, the following behavior occurs:

```typescript
    const connection = container.get<ConnectionProvider>()();
    // First request:   blocks until connection is established.
    // Second request:  returns connection object but isConnected is false.
```

As the connection is not established for the second request, it cannot locate any repository.

For me, this only happens in dev setup. The production service starts way slower, giving the service time to establish the connection.

I "fixed" it with this code right here:

```typescript
const getEstablishedConnection = async (): Promise<Connection> => {
  const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

  return new Promise(async (ok, fail) => {
    // this should at most take 3s = retriesLeft * sleep = 3 * 1000ms
    for(let retriesLeft = 3; 0 < retriesLeft; retriesLeft--) {
      const connection = await container.get<ConnectionProvider>(TYPES.ORMConnection)();
      if(connection.isConnected) return ok(connection);
      await sleep(1000);
    }
    return fail();
  });
};
```
