### ISSUE TITLE
saving and updating OneToMany or ManyToOne cascaded entities. 

### ISSUE THREAD

**Issue by akaanish** [typeorm/typeorm#3225]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x ] `@next`
[ ] `0.2.9` (or put your version here)

I have attached the entities & service code snippet here to reproduce the issue at your end. I am following the steps as documented in typeorm docs: 
[http://typeorm.io/#/many-to-one-one-to-many-relations](url)

Following is the code snippets:

**1. Device Entity**
@Entity("device", {
    schema: "device_registry"
})

@Index("fk_device_device_status_snapshot1_idx", ["deviceStatusSnapshot"])
export class Device {

    @Column("varchar", {
        nullable: false,
        primary: true,
        length: 50,
        name: "id"
    })
    id: string;

    @OneToOne(type => DeviceStatusSnapshot, DeviceStatusSnapshot => DeviceStatusSnapshot.device, {
        onDelete: 'NO ACTION', onUpdate: 'NO ACTION',
        eager: true
    })
    @JoinColumn({
        name: 'device_status_snapshot_id'
    })
    deviceStatusSnapshot: DeviceStatusSnapshot | null;

    @OneToMany(type => DeviceControlCommand, DeviceControlCommand => DeviceControlCommand.device, {
        onDelete: 'NO ACTION', onUpdate: 'NO ACTION',
        cascade: ['insert', 'update', 'remove'],
        eager: true
    })
    deviceControlCommands: DeviceControlCommand[];

    @Column("datetime", {
        nullable: false,
        name: "last_modified_on"
    })
    lastModifiedOn: Date;
}

**2. DeviceControlCommand Entity**
 @Entity("device_control_command", {
    schema: "device_registry"
  })
  @Index("fk_device_control_command_device1_idx", ["device", ])
  export class DeviceControlCommand {
  
    @PrimaryGeneratedColumn({
      name: "id"
    })
    id: number;
  

    @ManyToOne(type => Device, Device => Device.deviceControlCommands, {
      nullable: false,
      onDelete: 'NO ACTION', onUpdate: 'NO ACTION',
      
    })
    @JoinColumn({
      name: 'device_id'
    })
    device: Device | null;
  
  
    @Column("json", {
      nullable: false,
      name: "command"
    })
    command: Object;  
  }

**3. DeviceStatusSnapshot Entity**

@Entity("device_status_snapshot", {
    schema: "device_registry"
  })
  export class DeviceStatusSnapshot {
  
    @PrimaryGeneratedColumn({
      name: "id"
    })
    id: number;

    @Column("enum", {
      nullable: false,
      enum: ["PROVISIONED", "JOINED", "ACTIVE", "INACTIVE"],
      name: "status"
    })
    status: string;
  
    @OneToOne(type => Device, Device => Device.deviceStatusSnapshot, {
      onDelete: 'NO ACTION', onUpdate: 'NO ACTION',
      
    })
    device: Device;
  }

****Now following service code snippet, which is importing the device entity & updating the commands & snapshot in the device entity and saving the device entity back into the database.**

**DeviceService****
@Injectable()
export class DeviceService {
    constructor(
        @InjectRepository(Device) private readonly deviceRepository: Repository<Device>,
    ) {

    }
    async control(deviceControlRequestDto: DeviceControlRequestDto) {
        try {
            const deviceId: string = deviceControlRequestDto.getDeviceId();
            const command: object = deviceControlRequestDto.getCommand();
            let device: Device = await this.deviceRepository.findOne({
                id: deviceId
            });
            const deviceControlCommand: DeviceControlCommand = new DeviceControlCommand();
            deviceControlCommand.device = device;
            deviceControlCommand.command = command;
            if (!device.deviceControlCommands) {
                device.deviceControlCommands = [];
            }
            device.deviceControlCommands.push(deviceControlCommand);
            let deviceStatusSnapshot: DeviceStatusSnapshot = device.deviceStatusSnapshot;
            if (!deviceStatusSnapshot) {
                deviceStatusSnapshot = new DeviceStatusSnapshot();
            }
            deviceStatusSnapshot.status = 'PROVISIONED';
            device.deviceStatusSnapshot = deviceStatusSnapshot;
            device.lastModifiedOn = new Date();
            device = await this.deviceRepository.save(device);
        } catch (error) {
            console.log(error);
        }
    }
}

using postman i called the DeviceService simultaneously through route, but it inserts one or two records and then throws the following errors:

**UnhandledPromiseRejectionWarning: QueryFailedError: ER_BAD_NULL_ERROR: Column 'device_id' cannot be null**

**UnhandledPromiseRejectionWarning: QueryFailedError: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction**

I am using mysql version :-  **mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64)**

Also using nest js framework for development.

**Comment by pleerock** [comment]
Not enough details. You probably do something wrong. Please create a PR with a failing test and I'll review your issue.

**Comment by akaanish** [comment]
> Not enough details. You probably do something wrong. Please create a PR with a failing test and I'll review your issue.

i have updated the details for your reference in the original description.

**Comment by pleerock** [comment]
yeap, please create a PR with a minimal reproduction of your issue.

**Comment by Kononnable** [comment]
Closing as no response from the author.
