### ISSUE TITLE
Inserting big arrays

### ISSUE THREAD

**Issue by wederer** [typeorm/typeorm#3228]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an array (>50,000 entries) which I want to insert into my table via TypeORM. When doing `entityRepository.insert(entities)` I get an error:

```
Error: bind message supplies 13868 parameters, but prepared statement "" requires 669228
```

This does not happen when I split the array into multiple arrays (e.g. length of 1000).
Why does this happen? Isn't this something that TypeORM should handle? Why do I have to split the array myself?

**Comment by havenchyk** [comment]
@wederer it can be a good improvement, we have several similar issues, but the general advice would be to split array by yourself, PR is appreciated

**Comment by wederer** [comment]
@havenchyk Do you have an idea how to implement it, or how other ORMs do it? I have looked at the codebase and InsertQueryBuilder is probably the correct class, but am unsure on the specifics.

**Comment by havenchyk** [comment]
@pleerock @Kononnable ^^

**Comment by vlapo** [comment]
@wederer Did you try `entityRepository.save(entities, { chunk: entities.length / 1000 })`? This solution works for me.

But I think this is nasty contradiction here because `insert` method of manager also contains options with `chunk` but this options are never used in `next` or in `master` branche.

**Comment by pleerock** [comment]
@vlapo is correct, for exactly this problem `chunk` option was created to prevent max parameters problem.

**Comment by chriszrc** [comment]
Is the chunk option anywhere in the current documentation? And why is it missing from insert, since that runs into the same problem?
