### ISSUE TITLE
How to save entity with ManyToOne with nullable: false set?

### ISSUE THREAD

**Issue by draoncc** [typeorm/typeorm#3229]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm terribly tired so apologies if the answer is obvious, and I'm just blind and not seeing it.

Assuming the following two entities:

```typescript
@Entity()
export class Parent {
  @PrimaryGeneratedColumn()
  id!: number

  @OneToMany(type => Child, child => child.parent)
  children!: Child[]
}

@Entity()
export class Child {
  @PrimaryGeneratedColumn()
  id!: number

  @ManyToOne(type => Parent, parent => parent.children, { nullable: false })
  parent!: Parent
}
```

When doing `entityManager.insert(Child, {})`, naturally the error `null value in column \"parentId\" violates not-null constraint` is thrown. When trying to do `entityManager.insert(Child, { parentId: 1 })`, the same error is thrown though.

So how do I create and save new `Child`s with the above model?

**Comment by vlapo** [comment]
Your `Child` entity do not have defined `parentId` column in entity class. I am getting error in IDE
```
Object literal may only specify known properties, and 'parentId' does not exist in type 'QueryPartialEntity<Child> | QueryPartialEntity<Child>[]'. [2345]
```
So typeorm will ignore this property value during query build. Of course typeorm know about this join column but entity argument of insert is `QueryPartialEntity<Child>|(QueryPartialEntity<Child>[])` so does not expect `parentId` property.

There are two options:

1. Define additional `parentId` column in `Child` class.
```typescript
@Entity()
export class Child {
    @PrimaryGeneratedColumn()
    id!: number;

    @Column()
    parentId: number;

    @ManyToOne(type => Parent, parent => parent.children, { nullable: false })
    parent!: Parent;
}
```
2. Use little trick and call `insert` method like this:
```typescript
await entityManager.insert(Child, { parent: { id: 1 } as Parent });
```
