### ISSUE TITLE
Relation between tables from different databases

### ISSUE THREAD

**Issue by Goodmain** [typeorm/typeorm#323]
Hello.

First of all, thank you for your awesome work.

For some reasons I have a table in a different database and I need to use it for relations.
For example, I have EntityA, which represents `table A` from `DB1`:

```
@Entity()
export class EntityA {

    @PrimaryGeneratedColumn('int')
    ID: number;

    @Column()
    Something: string;

    @Column()
    ForeignID: number;

    @ManyToOne(type => EntityB, B => B.ID)
    @JoinColumn({ name: "ForeignID" })
    B: EntityB;
}
```

And EntityB, which represents `table B` from `DB2`:

```
@Entity()
export class EntityB {

    @PrimaryGeneratedColumn('int')
    ID: number;

    @Column()
    SomethingElse: string;
}
```

How I can relate entities in the QueryBuilder?

Sorry, If I missed something. I tried to find similar issue but nothing.

**Comment by pleerock** [comment]
Using query builder.

```typescript
const entities = await connection.getRepository(Post)
        .createQueryBuilder("post")
        .leftJoinAndSelect("post.category", "category")
        .getMany();
```

**Comment by Goodmain** [comment]
But where I should to set different DB (DB2)? Connection related with only one DB (DB1 in my example).

**Comment by icewind** [comment]
I think you need to establish two different connections and register appropriate entities for each one. Something like this(untested)
Config
```javascript
[{
  name: 'default',
  driver: {
    type: 'postgres',
    host: process.env.DB1_HOSTNAME,
    port: process.env.DB1_PORT,
    username: process.env.DB1_USERNAME,
    password: process.env.DB1_PASSWORD,
    database: process.env.DB1_NAME
  },
  entities: [
    'models'
  ]
}, {
  name: 'db2',
  driver: {
    type: 'postgres',
    host: process.env.DB2_HOSTNAME,
    port: process.env.DB2_PORT,
    username: process.env.DB2_USERNAME,
    password: process.env.DB2_PASSWORD,
    database: process.env.DB2_NAME
  },
  entities: [
    'models_for_second_db'
  ]
}]
```
Then create your connections
```typescript
import { createConnections } from 'typeorm'
await createConnections(/*pass config here unless you're using ormconfig.json */);
```
Then somewhere in your code
```typescript
import { getConnectionManager } from 'typeorm';

const connection = getConnectionManager().get(); // for default connection
const db2connection = getConnectionManager().get('db2');
```
and then, just use appropriate repositories/entity managers from each connection

**Comment by Goodmain** [comment]
Thank you @icewind, But when I'm using QueryBuilder it based on only one connection.

In my example:
```
const entities = await connection.getRepository(EntityA)
        .createQueryBuilder("EntityA")
        .leftJoinAndSelect("EntityA.B", "EntityB")
        .getMany();
```

**Comment by icewind** [comment]
Ok, just to clarify. This should work in MySQL/MariaDB if current user has an access to both databases. And this will not work in Postgres out of the box. To achieve this you need to use a couple of extensions `postgres_fdw` and `dblink`. 
And in this case you should create relations manually

**Comment by Goodmain** [comment]
Yes, this is for MySQL and user has access to both databases.

**Comment by icewind** [comment]
You can check generated query by using
```typescript
.createQueryBuilder('EntityA')
...
.getSql()
```
And maybe try to execute raw query?
```typescript
const entities = await connection.getRepository(EntityA)
    .query('SELECT a.*, b.filed FROM dba.some_table a INNER JOIN dbb.other_table b ON ...')
```

**Comment by pleerock** [comment]
Also the question is how do you retrieve connections? Because if you have two connections it means they  should have different names. If they have different names the question is how do you retrieve them, because for example if you use `getConnection()` it already should be named as `getConnection("connection-name")`.

**Comment by Goodmain** [comment]
I tried direct relations:

```
const entities = await connection.getRepository(EntityA)
        .createQueryBuilder("EntityA")
        .leftJoinAndSelect(EntityB, "EntityB", "EntityB.ID = EntityA.ForeignID") //EntityB from DB2
        .getMany();
```

Result:

```
SELECT
	`EntityA`.`ID` AS `EntityA_ID` ,
	`EntityA`.`Something` AS `EntityA_ Something` ,
        `EntityA`.`ForeignID ` AS `EntityA_ ForeignID ` ,
	`EntityB`.`ID` AS `EntityB_ID` ,
	`EntityB`.`SomethingElse ` AS `EntityB_ SomethingElse`
FROM
	`EntityA` `EntityA`
LEFT JOIN `EntityB` `EntityB` ON `EntityB`.`ID` = `EntityA`.`ForeignID`
```

And custom table:

```
const entities = await connection.getRepository(EntityA)
        .createQueryBuilder("EntityA")
        .leftJoinAndSelect('db2.EntityB', "EntityB", "EntityB.ID = EntityA.ForeignID")
        .getMany();
```

And as result I got error: `Error: Alias "db2" was not found`

**Comment by Goodmain** [comment]
@pleerock I not tried to manipulate with data from DB2 yet. Main table in my case is the DB1. I rewrite whole queries to typeorm. In several cases I should use relations with DB2. When I tried to rewrite - I not found the way how I should do this.

And I think for this (not common) case I'd like use one connection (because I have only one difference between 2 connections - DB name).

**Comment by pleerock** [comment]
Its not designed to work this way. You have to setup two connections, and if you want to load entity and some related entity from second connection you need to load it separately using second connection and set it to entity.

**Comment by Goodmain** [comment]
Ok, I setup 2 connections. How I can create relation and get data via QueryBuilder?

**Comment by pleerock** [comment]
You don't create relation. Lets say you have `Post` in connection 1 and `Category` in connection 2. Your post will look like this:

```ts
@Entity()
export class Post {
    /// ...

    @Column("int")
    categoryId: number; // not foreign key, just regular column, you'll store value here using post.categoryId = category.id, you can also create a getter/setter for category below

    category: Category; // note: no relations here

}

@Entity()
export class Category {
    /// ...
    
    posts: Post[]; // note: no relations here

}
```

And fetch it like this:

```ts
const category = await connection1.getRepository(Category).createQueryBuilder("category").getOne();
const posts = await connection2.getRepository(Post).createQueryBuilder("post").where("post.categoryId = :categoryId", { categoryId: category.id }).getMany();
category.posts = posts;
```

**Comment by Goodmain** [comment]
Got it. In this case, if I need many categories I should fetch all categories (which I need) and assign appropriated posts to each category.

**Comment by Goodmain** [comment]
But, seems I found the solution.

I slightly changed my EntityB

```
@Entity('DB2.EntityB')
export class EntityB {

    @PrimaryGeneratedColumn('int')
    ID: number;

    @Column()
    SomethingElse: string;
}
```

And I got query:
```
SELECT
	`EntityA`.`ID` AS `EntityA_ID` ,
	`EntityA`.`Something` AS `EntityA_ Something` ,
        `EntityA`.`ForeignID ` AS `EntityA_ ForeignID` ,
	`EntityB`.`ID` AS `EntityB_ID` ,
	`EntityB`.`SomethingElse` AS `EntityB_ SomethingElse`
FROM
	`EntityA` `EntityA`
LEFT JOIN `DB2.EntityB` `EntityB` ON `EntityB`.`ID` = `EntityA`.`ForeignID`
```
Next, I’ve changed EntityB to:
```
@Entity('DB2`.`EntityB')
export class EntityB {

    @PrimaryGeneratedColumn('int')
    ID: number;

    @Column()
    SomethingElse: string;
}
```

And got what I wanted:

```
SELECT
	`EntityA`.`ID` AS `EntityA_ID` ,
	`EntityA`.`Something` AS `EntityA_ Something` ,
        `EntityA`.`ForeignID ` AS `EntityA_ ForeignID` ,
	`EntityB`.`ID` AS `EntityB_ID` ,
	`EntityB`.`SomethingElse` AS `EntityB_ SomethingElse`
FROM
	`EntityA` `EntityA`
LEFT JOIN `DB2`.`EntityB` `EntityB` ON `EntityB`.`ID` = `EntityA`.`ForeignID`
```

Dirty solution but it works. Maybe it helps somebody.

Sure, if I could choose I would use only one DB.

**Comment by pleerock** [comment]
> Got it. In this case, if I need many categories I should fetch all categories (which I need) and assign appropriated posts to each category.

right. I really suggest you this solution instead of dirty hack you did. First your hack will not transform entities for you correctly, second its not reliable and can break in future versions of orm

**Comment by Goodmain** [comment]
It transform entities correctly (for selection queries, I not checked insert/update yet).
Initially, for insert/update I planned to use second connection.

**Comment by pleerock** [comment]
Anyway, be careful with this hack as it may not work some day because orm is not intended for such operations. I think we can close this issue now.

**Comment by nebkat** [comment]
For anyone finding this now, multiple databases are supported since https://github.com/typeorm/typeorm/commit/878634c58441a2134cb71045ac12a971897c10e7

**Comment by DanielMenke** [comment]
@nebkat how does this solve the problem if you want to query a relation of an entity which is persisted in another database than the entity itself, by using only one querybuilder?

**Comment by nebkat** [comment]
> @nebkat how does this solve the problem if you want to query a relation of an entity which is persisted in another database than the entity itself, by using only one querybuilder?

I know for sure there is an issue where if you make a query with an entity in another database then entities from the default database will be referred to without the database name, and the current workaround for this is to also define the database parameter for those entities even if it is the default. There may also be other places in query builder where the database name isn't placed in the query even if it is defined, but I'm not sure of that.

**Comment by DanielMenke** [comment]
@nebkat while you are right, the initial issue was about using a single querybuilder call to join two entities which reside in different databases... Does the declaration of the database on entity level eable you to do this? Would be great.

**Comment by nebkat** [comment]
@DanielMenke in theory it should... try it out and if it doesn't just post a new issue with a test for the broken functionality and I'll get it fixed.
