### ISSUE TITLE
listenTo for EventSubscriber called 6 times per insert.

### ISSUE THREAD

**Issue by dilame** [typeorm/typeorm#3232]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am NestJS user, so i forced to use dirty hack for event subscribing until this issue https://github.com/typeorm/typeorm/issues/2630 is opened , but i am sure it doesn't matter.

```
import { Injectable } from '@nestjs/common';
import { InjectConnection } from '@nestjs/typeorm';
import { EntitySubscriberInterface, Connection, InsertEvent } from 'typeorm';
import { ChatMessageEntity } from '../models/chat-message.entity';
import { ChatGateway } from '../chat.gateway';

@Injectable()
export class ChatMessageSubscriber implements EntitySubscriberInterface<ChatMessageEntity> {
  constructor(
    @InjectConnection() private connection: Connection,
    private chatGateway: ChatGateway,
  ) {
    connection.subscribers.push(this);
  }

  listenTo() {
    console.log('call listenTo');
    return ChatMessageEntity;
  }

  afterInsert(event: InsertEvent<ChatMessageEntity>): Promise<any> | void {
    this.chatGateway.server.emit('chat:message:created', event.entity);
  }
}

```

I discovered that i have exactly 6 `call listenTo` in my console per each 1 insert operation. Is it normal?

**Comment by pleerock** [comment]
yeah, why not? Its not normal if `afterInsert` is called 6 times when you just insert a single entity. 

I don't remember exactly call trace, but it might check using listenTo each time before calling all types of methods.

**Comment by dilame** [comment]
This shows the architecture leaks under the hood. Why to call the same function 6 times just to evaluate 1 payload function? I made only insert, not removing or updating, so @BeforeUpdate, @AfterUpdate, @BeforeRemove, @AfterRemove will not be called anyway. Even more, why to call the same function even twice, when i do sequential inserts, when you can cache it in first call.
The method is called `listenTo`, so i expect that it will be called only once, because if it will call twice, it might assign handler for events two times too.
I want to `console.log` inside `listenTo` to know how many listeners do i have and how what entities do they listen.

**Comment by pleerock** [comment]
> This shows the serious architecture leaks under the hood. 

if some almost zero-const function being called 6 times instead of one it doesn't show any "serious architecture leaks under the hood". It just shows you telling something before thinking deeply about it :)

If you want to improve something, feel free to do that, but make sure to provide minimal subset of changes to make sure we won't break anything else because of this almost worthless change.

**Comment by martijnvdbrug** [comment]
Subscribing my subscriber with `getConnection().subscribers.push(this)` results in the `afterInsert()` method in my subscriber being triggered for **all** entities, even though my subscriber extends `EntitySubscriberInterface<Order>`. No solution found yet.

**Comment by jbjhjm** [comment]
@martijnvdbrug hmmm you can't inherit EntitySubscriberInterface. It's an interface. Which won't even be there after compiling. You'll need to find out how typeORM filters which subscribers shall be notified.
