### ISSUE TITLE
Ids of related objects instead of instances after creation

### ISSUE THREAD

**Issue by Evilart86** [typeorm/typeorm#3236]
** Type of problem: **

[x] question
[x] function request

** System database / driver: **
[x] `postgres`

** TypeORM Version: **
[x] `0.2.7` (or post your version here)

** Steps to play or a small repository showing the problem: **
1. Create some object with a ManyToOne relation

The returned object will have an embedded related object. But I only need to get the Id of the related object. How can I see only the Id of this related object?
I found one way: I need to do another transaction to find this created object:
`repository.find ({loadRelationIds: true})`
But I would not like to make an additional request to the database and would like to be able to have Id of  related objects after the creation phase.

**Comment by pleerock** [comment]
Lets say you have following relation:

```ts
@ManyToOne(() => Category)
category: Category;
```

You can just create a following column:

```ts
@ManyToOne(() => Category)
category: Category;

@Column()
categoryId: number;
```

And it will work as you expect (assuming referenced column name is `id`)

**Comment by Evilart86** [comment]
I have already tried this way. Your example returns both Id and category object. I need only Id because I have a problem with circular dependency when serializing in json. 

My model Seat with relation to SeatSchema
![image](https://user-images.githubusercontent.com/20624473/49949048-633e2c00-fefd-11e8-95c7-b90115f67046.png)

If I set schema or schema and Id as result I get and schema object and schemas Id:
![image](https://user-images.githubusercontent.com/20624473/49949668-d98f5e00-fefe-11e8-8c12-e8d0cf29dc97.png)


If I set Id and try to save this Seat I get object with schema = null and Id = null, but in database it saved correctly:
![image](https://user-images.githubusercontent.com/20624473/49949625-bebce980-fefe-11e8-88ec-56c18d5bd4d0.png)

This `repository.find ({loadRelationIds: true})` resolve my problem but I don't want to do another request to database. I feel it's wrong. May be not. I don't know:)

**Comment by pleerock** [comment]
> I have already tried this way. Your example returns both Id and category object. I need only Id because I have a problem with circular dependency when serializing in json.

it doesn't return you object until you explicitly load it.

**Comment by Evilart86** [comment]
But I don't need a object:) I just want to have only Ids without any nested objects. Like with the option `{loadRelationIds: true}` in _find_ method

**Comment by pleerock** [comment]
@Evilart86 yeah, so this is what I told - you don't have object until you load it. You have something that loads your relation. Check your code. If you think its a typeorm issue then provide a reproduction for this problem.
