### ISSUE TITLE
Still can't get the update result.raw?

### ISSUE THREAD

**Issue by coldice9417** [typeorm/typeorm#3237]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

UpdateResult {
  generatedMaps: [],
  raw:
   OkPacket {
     fieldCount: 0,
     affectedRows: 1,
     insertId: 0,
     serverStatus: 2,
     warningCount: 0,
     message: '(Rows matched: 1  Changed: 0  Warnings: 0',
     protocol41: true,
     changedRows: 0 }
}

**Comment by coldice9417** [comment]
UpdateResult {
  generatedMaps: [],
  raw:
   OkPacket {
     fieldCount: 0,
     affectedRows: 1,
     insertId: 0,
     serverStatus: 2,
     warningCount: 0,
     message: '(Rows matched: 1  Changed: 0  Warnings: 0',
     protocol41: true,
     changedRows: 0 } 
}

**Comment by coldice9417** [comment]
sorry, is generatedMaps.... I want to know the number of rows and ids updated. But now generatedMaps is always empty

**Comment by pleerock** [comment]
I'll close this issue if you won't provide more details with a good explanation of your problem.

**Comment by coldice9417** [comment]
like this, i want 'generatedMaps' can return affectedRows id or entity.
`let ret = await getRepository(Cart).update({
            goods_id: goodsId,
            buyer_id: memberId
        },{
           goods_num : num
 });`

`UpdateResult {
  generatedMaps: [],
  raw:
   OkPacket {
     fieldCount: 0,
     affectedRows: 1,
     insertId: 0,
     serverStatus: 2,
     warningCount: 0,
     message: '(Rows matched: 1  Changed: 1  Warnings: 0',
     protocol41: true,
     changedRows: 1 } }`

**Comment by pleerock** [comment]
`generatedMaps` is used mostly internally. `update` method executes a raw sql query, that's only thing it does. If you want more you need to use `save` method instead.

**Comment by coldice9417** [comment]
thanks
