### ISSUE TITLE
Missing documentation for Save/Insert/Remove Options

### ISSUE THREAD

**Issue by wederer** [typeorm/typeorm#3241]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

I have recently opened an issue #3228, because I could not find a chunking/batching feature for saving with a repository. The [Repository API Documentation](https://github.com/typeorm/typeorm/blob/master/docs/repository-api.md#repository-api) does not list the available options for the given functions.

**Comment by pleerock** [comment]
merged, thanks!

**Comment by wederer** [comment]
You're welcome. Thank you for typeorm 👍
