### ISSUE TITLE
Changes in enum type is not reflected when generating migration (in definition file)

### ISSUE THREAD

**Issue by philippfo9** [typeorm/typeorm#3244]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hey,
I got his issue too with the newest typeorm 0.2.8. I have got an enum like this: 

`enum ERateType {
        RT_UNKNOWN = 0,
        RT_REF_TO_PAYMENT = 10,
        RT_REF_TO_SUBSCRIPTION = 11,
        RT_REF_TO_TAX = 12,
        RT_REF_TO_STORAGE = 13,
        RT_SUBSCRIPTION_TO_PAYMENT = 20,
        RT_SUBSCRIPTION_TO_TAX = 21,
        RT_SUBSCRIPTION_TO_STORAGE = 22,
        RT_PAYMENT_TO_STORAGE = 30,
        RT_PAYMENT_TO_SUBSCRIPTION = 31,
        RT_PAYMENT_TO_TAX = 32,
        RT_PAYMENT_TO_REF = 33,
        RT_STORAGE_TO_PAYMENT = 40,
        RT_STORAGE_TO_TAX = 41
    }` in a .d.ts file.

Now I when I generate the first migration it all works fine. I get this line in the the table enum restriction: `type enum ('RT_UNKNOWN', 'RT_REF_TO_PAYMENT', 'RT_REF_TO_SUBSCRIPTION', 'RT_REF_TO_TAX', 'RT_REF_TO_STORAGE', 'RT_SUBSCRIPTION_TO_PAYMENT', 'RT_SUBSCRIPTION_TO_TAX', 'RT_SUBSCRIPTION_TO_STORAGE', 'RT_PAYMENT_TO_STORAGE', 'RT_PAYMENT_TO_SUBSCRIPTION', 'RT_PAYMENT_TO_TAX', 'RT_PAYMENT_TO_REF', 'RT_STORAGE_TO_PAYMENT', 'RT_STORAGE_TO_TAX', '0', '10', '11', '12', '13', '20', '21', '22', '30', '31', '32', '33', '40', '41') NULL`

Then I change one of the enum values from e.g. RT_REF_TO_PAYMENT to RT_REFERENCE_TO_PAYMENT or add a new type in the enum.
If I then I generate a new migration, the change won't be reflected in the restriction and the possible values stay the same.

I have specified the enum like this:
![image](https://user-images.githubusercontent.com/30824277/49940759-c79ec280-fee0-11e8-9b2d-7557172a49dc.png)
ERateTypeTransformer just transforms the values to the strings.
![image](https://user-images.githubusercontent.com/30824277/49940843-164c5c80-fee1-11e8-8b36-9ae84dfa61f0.png)

I generate migrations like this: ts-node ./node_modules/.bin/typeorm migration:generate -n <migration-name>

**Comment by pleerock** [comment]
can you please find in git history who made a change and point him where he missed something?

**Comment by philippfo9** [comment]
I have tried it back with version 0.2.5 and 0.2.0, but it doesn't seem to work either. It doesn't change the restriction when generating a new migration afterwards

**Comment by jippy89** [comment]
I'm currently using TypeORM 0.3.12 and still experienced this issue?

I tried running via `migration:generate` command, and it doesn't detect it.
