### ISSUE TITLE
[psql] Creating migration for already existing table

### ISSUE THREAD

**Issue by lukejagodzinski** [typeorm/typeorm#3250]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm trying to create migration that would work with already existing database. I have a table which has two fields:

```
id BIGSERIAL PRIMARY KEY,
org_id BIGSERIAL UNIQUE,
```

and in the TS class I have fields defined in the following way:

```ts
@PrimaryGeneratedColumn()
readonly id: number;

@Column("bigint", { name: "org_id", unique: true })
orgId: number;
```

and it keeps creating migrations for those two fields. Is there a way to define those two fields that would not create migration?

**Comment by pleerock** [comment]
Try following:

```ts
@PrimaryColumn("bigint")
@Generated()
readonly id: number;

@Column("bigint", { name: "org_id", unique: true })
@Generated()
orgId: number;
```

**Comment by lukejagodzinski** [comment]
@pleerock thanks! It worked!
