### ISSUE TITLE
QueryFailedError: ER_PARSE_ERROR when I am trying update data with createQueryBuilder

### ISSUE THREAD

**Issue by aroksetx** [typeorm/typeorm#3252]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.x.x` (^0.2.9)

**Steps to reproduce or a small repository showing the problem:**

I am using an example from your official documentation. And I am getting the next error.
Am I doing something wrong?
> QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `id` = 12' at line 1

```
@httpPatch('/:userId')
    public async updateUserProfile(@requestParam("userId") userId: number, @request() req: express.Request, @response() res: express.Response) {
        const authData: UserDataInterface = req.body; 
        const user = await getConnection()
        .createQueryBuilder()
        .update(User)
        .set(authData)
        .where("id = :id", { id: Number(userId) })
        .execute();
       return user;
    }
```

**Comment by vlapo** [comment]
Hi @aroksetx.

Could you please use method `getQueryAndParameters()` instead of execute and provide output? Maybe there are problem with `authData`. This is really hard to say.

**Comment by pleerock** [comment]
Yes my guess is also to `authData`. Try to log it, if its empty, make sure you are passing your data correctly from the client you use.

**Comment by aroksetx** [comment]
@vlapo 10x. I changed on `getQueryAndParameters `
