### ISSUE TITLE
Closing all open database connections

### ISSUE THREAD

**Issue by wederer** [typeorm/typeorm#3253]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

Similar to `createConnections()` a `closeConnections()` would be very handy.
Is this feature planned or should I provide a PR?

**Comment by Kononnable** [comment]
PRs are always welcomed :)

**Comment by pleerock** [comment]
no, I think we won't introduce this feature since we are planning to change createConnection syntax (and make it not store connections inside ORM) in the future versions.

**Comment by DarkLite1** [comment]
+1 on a `closeConnections()`
