### ISSUE TITLE
Feature request: reload with relations without eager

### ISSUE THREAD

**Issue by samjmckenzie** [typeorm/typeorm#3255]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

example

```ts
@Entity()
export class User extends BaseEntity {
   @PrimaryGeneratedColumn()
   id: number;

   @Column()
   username: string;

   @OneToMany(type => Profile, profile => profile.user)
   profiles: Profile[];
}

@Entity()
export class Profile extends BaseEntity {
   @PrimaryGeneratedColumn()
   id: number;

   @ManyToOne(type => User, user => user.profiles)
   user: User;
}

const user = new User();
user.username = 'samjmckenzie';
await user.save();

const profile = new Profile();
profile.user = user;
await profile.save();

// first argument is the relations that need to be reloaded
await user.reload(['profiles']);

```

**Comment by samjmckenzie** [comment]
Why is it wrong? And why would you prevent eager relations from reloading?

**Comment by pleerock** [comment]
Reload meant to reload current entity, why the hell it should reload something else? Current behaviour can be treated as a bug since we just missed this point when implementing this reload feature.

**Comment by NathanPB** [comment]
Updates on this? Why was it closed without an answer?

The request is pretty useful

**Comment by imnotjames** [comment]
> Updates on this? Why was it closed without an answer?
> 
> The request is pretty useful

The reporter closed it.  If you'd like to make a feature request like this please feel free to open another.

**Comment by dustinlacewell** [comment]
I'm confused. If reload() doesn't reload relations, and you need to do that... how do you do it?

**Comment by mmamedel** [comment]
I had same problem and a possible work around is simply create an override method like this:
```typescript
import { BaseEntity, FindManyOptions } from 'typeorm';
import { ObjectUtils } from 'typeorm/util/ObjectUtils';

export class Base extends BaseEntity {
  override async reload<T extends Base>(options?: FindManyOptions<T>) {
    const base = this.constructor as typeof Base;
    const id = base.getRepository().metadata.getEntityIdMap(this);
    const reloadedEntity: BaseEntity = await base
      .getRepository<T>()
      .findOneOrFail(id as any, options);

    ObjectUtils.assign(this, reloadedEntity);
  }
}
```

Then you can expand your Entities from this Base class instead of native BaseEntity class and use the reload function with find options like this:
```typescript
import { FindManyOptions } from 'typeorm';
import { Base} from './base';

class MyEntity extends Base {}

const options: FindManyOptions<MyEntity> = { relations: ['another-table'] }

const myInstance = MyEntity.findOneOrFail('instance-id', options)

myInstance.reload(options)
```

**Comment by mmamedel** [comment]
For TyperORM developers: Ideally users would want the options to be deduced from the Entity, but I didn't the findOptions saved as metadata in the entity itself, that's why I decided to resend it in the reload... but with additional metadata we could definitely skip this addition.
