### ISSUE TITLE
have a way to access column and relations by same way?

### ISSUE THREAD

**Issue by s97712** [typeorm/typeorm#3259]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
## example: 
```
import {Entity, PrimaryGeneratedColumn, Column, BaseEntity} from "typeorm";

@Entity()
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    age: number;

    @OneToOne(type => Profile)
    @JoinColumn()
    profile: Profile;

}
```
I want to access  `Column` and `JoinColumn` by same way, such as
```
userRepository.find({column: ["firstName", "profile"]})
```
Instead of
```
userRepository.find({select: ["firstName"], relations: ["profile"]})
```
or automatically transform `{column: ["firstName", "profile"]}` to `{select: ["firstName"], relations: ["profile"]}` according to the defined model

has some way to do these?

**Comment by havenchyk** [comment]
I don't think it's possible, moreover, I don't see the way to parse your desired query properly to understand what you want it to be converted to.

Please check docs https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#basic-options.

You can try to implement this behavior if you find it useful. PR is welcome

**Comment by vlapo** [comment]
As a question and current state answer is no, there is no way how to do this. But maybe it will be consider in next releases. I think there is some task abou `deprecate eager and lazy loading`.

**Comment by pleerock** [comment]
I think this can be closed since even if it will be a feature request, it doesn't make sense.
