### ISSUE TITLE
Can not find TableInheritance column

### ISSUE THREAD

**Issue by wszgrcy** [typeorm/typeorm#3261]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `mysql` / `mariadb`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
@Entity('grab')
@TableInheritance({ column: { name: 'grabType', type: 'varchar', select: true } })
export class GrabAbstract {
    @PrimaryGeneratedColumn() id?: number;
    @Column('varchar') url: string;
}

```
```ts
@Injectable()
export class GrabService {
    constructor(
        @InjectRepository(GrabAbstract)
        private readonly grabRepository: Repository<GrabAbstract>,
    ) { }

    findAll() {
        return this.grabRepository
            .createQueryBuilder('grab')
            .select([
                'grab',
                'grab.grabType'
            ])
            .getMany();
    }

}
```
When I call findAll the result as follow
the column [grabType] can not return
like this
```ts
[ SingleGrab {
    id: 27,
    url: 'https://xxxx.cn/',
xxx:'xxxxx'
  },
  MultiGrab {
    id: 28,
    url: 'http://yyyy.com/',
yy:'yyyyy'
   },]
```
not have `grabType:'multi'` or `grabType:'single'`(child entity type)

**Comment by pleerock** [comment]
If you want a discriminator column to appear in the entity after selection you need to define this column in your model, e.g.:

```ts
@Entity('grab')
@TableInheritance({ column: { name: 'grabType', type: 'varchar' } })
export class GrabAbstract {
    @PrimaryGeneratedColumn() id?: number;
    @Column('varchar') url: string;
    @Column('varchar') grabType: string;
}
```

**Comment by wszgrcy** [comment]
> If you want a discriminator column to appear in the entity after selection you need to define this column in your model, e.g.:
> 
> ```ts
> @Entity('grab')
> @TableInheritance({ column: { name: 'grabType', type: 'varchar' } })
> export class GrabAbstract {
>     @PrimaryGeneratedColumn() id?: number;
>     @Column('varchar') url: string;
>     @Column('varchar') grabType: string;
> }
> ```

thx
