### ISSUE TITLE
when insert record to table, generate same key

### ISSUE THREAD

**Issue by kaimiyang** [typeorm/typeorm#3264]
**Issue type:**
[x] bug report

**Database system/driver:**
[x] `mysql

**TypeORM version:**
[x] `latest`
[x] `@next`

![image](https://user-images.githubusercontent.com/25541839/50051773-31260780-0153-11e9-9ee4-1aa336346187.png)

why generate same key exec program every time ?

**Comment by kaimiyang** [comment]
this is my code
```
 const UserModel = getConnection(DB.UC).getRepository(User)

  const newUser = UserModel.create(data)

  try {
    ### await UserModel.save(newUser)
  } catch(err) {
    const { message } = err //// TODO:
    return err
  }
```
`await` not insert data, report key same used!

**Comment by Kononnable** [comment]
You've got unique on that index? 
You don't change newUser data, so why wouldn't it generate same default entity every time?

**Comment by kaimiyang** [comment]
> You've got unique on that index?
> You don't change newUser data, so why wouldn't it generate same default entity every time?

yes, I've add unique on Column, and named loginName, such as
```
@Column({
      type: "varchar",
      length: 32,
      default: '',
      unique: true,
    })
    loginName: string
```
but I created different loginName in `data`, I want to add new data only!
Is this way use unique wrong, why ?

**Comment by kaimiyang** [comment]
I see, this is my fault.
set another column unique, but not set value, so report this error...
Thanks, @Kononnable
