### ISSUE TITLE
Paginate by updatedAt from previous results

### ISSUE THREAD

**Issue by pontusab** [typeorm/typeorm#3269]
**Issue type:**

[ X] question

**Database system/driver:**

[X ] `postgres`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi,

I'm trying to build a cursor based pagination and using `updatedAt` to sort the results, for that I need the previous latest cursor with the value of `updatedAt`. But the problem is that the data returned as an object, but I need to use the value in the database to be able to sort by it. 

Any ideas? 

Thanks!

**Comment by pleerock** [comment]
Can you please explain in details and how your request is related to typeorm?

**Comment by pontusab** [comment]
Yep, how can I get the value return exactly as it is in the database? If the saved value is `2018-12-15 14:25:47.032796` but instead it gives me a date object?

**Comment by pleerock** [comment]
Its returned as a Date because almost all use cases prefer to use Date object. You have a Date object, so if you need it in a string format, just convert it to the format you need.
