### ISSUE TITLE
how do I get an empty array when nested join is null? 

### ISSUE THREAD

**Issue by wrod7** [typeorm/typeorm#3273]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have this createQueryBuilder below:

```
const i = await Item.createQueryBuilder()
        .innerJoinAndSelect('Item.PrimaryUOM', 'uom')
        .leftJoinAndSelect('Item.CycleCountInventorys', 'cci')
        .leftJoinAndSelect('cci.CycleCountDetail', 'ccd')
        .leftJoinAndSelect('ccd.Location', 'cl')
        .where('Item.IsActive = 1')
        .andWhere('(ccd.Id = :CycleCountDetailId OR ccd.Id IS NULL)', { CycleCountDetailId })
        .andWhere(`(Item.Number = :search
                  OR Item.Name = :search
                  OR Item.Barcode = :search)`, { search })
        .getOne()
        console.log(i)
```

Here is what it logs:

```
Item {
  Id: 16237,
  IsActive: true,
  IsKitted: false,
  Number: 'Item 1',
  Name: 'Item Name 1',
  Barcode: '023535819999',
  UnitPrice: 2.99,
  UnitCost: 0.88,
  UnitsOnHand: 18,
  UnitsOnOrder: 0,
  UnitsReserved: 0,
  UnitsAvailable: 18,
  LastModifiedBy: 1,
  LastModifiedDate: 2018-09-21T15:20:02.217Z,
  CycleCountInventorys:
   [ CycleCountInventory {
       IsApproved: null,
       Units: null,
       CreatedDate: null,
       LastModifiedDate: null,
       CycleCountDetail: null } ] }
```
How can I get CycleCountInventorys to return an empty array when everything inside of it is null?

I notice if I remove the second .leftJoinAndSelect, it returns an empty array.

**Comment by pleerock** [comment]
results that you have is built from SQL query you have built. Determine what SQL you need to create, create it and execute to get results are you expecting.

**Comment by wrod7** [comment]
If I remove these two left joins:

```
.leftJoinAndSelect('cci.CycleCountDetail', 'ccd')
.leftJoinAndSelect('ccd.Location', 'cl')
```

I get the results that I want. An empty array for "CycleCountInventorys"
```
Item {
  Id: 16237,
  IsActive: true,
  IsKitted: false,
  Number: 'Item 1',
  Name: 'Item Name 1',
  Barcode: '023535819999',
  UnitPrice: 2.99,
  UnitCost: 0.88,
  UnitsOnHand: 18,
  UnitsOnOrder: 0,
  UnitsReserved: 0,
  UnitsAvailable: 18,
  LastModifiedBy: 1,
  LastModifiedDate: 2018-09-21T15:20:02.217Z,
  CycleCountInventorys: [ ] }
```

how can I get an empty array when I have those two joins added when the cyclecountinventory object is full of nulls?

**Comment by pleerock** [comment]
I think you didn't read my message properly. First determine what SQL you need to build, then build and run it. Then try to build it using typeorm.
