### ISSUE TITLE
Fail to detect PK existing constraint name on migration:generate

### ISSUE THREAD

**Issue by lukejagodzinski** [typeorm/typeorm#3274]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

I have a psql table created with the following queries:

```sql
CREATE TABLE users (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(255) NOT NULL UNIQUE,
    password character varying(60) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE UNIQUE INDEX users_pkey ON users(id uuid_ops);
CREATE UNIQUE INDEX users_email_key ON users(email text_ops);
```

I've created entity that matches the table but right now I want to change type of the `id` field. Everything ok, so far. Now I run command: `typeorm migration:generate -n Init` which creates migration file but it fails to properly detect constraint name. It does not see the ID field with the constraint named as `users_pkey` but instead it just uses random hash. So, the migration query looks like follows:

```sql
ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"
ALTER TABLE "users" DROP COLUMN "id"
ALTER TABLE "users" ADD "id" BIGSERIAL NOT NULL
ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")
```

and it should look like this:

```sql
ALTER TABLE "users" DROP CONSTRAINT "users_pkey"
ALTER TABLE "users" DROP COLUMN "id"
ALTER TABLE "users" ADD "id" BIGSERIAL NOT NULL
ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")
```

I was trying to provide my own constraint name that would match the old one but it doesn't look like possible for the primary key. Do you know about this bug?

**Comment by pleerock** [comment]
own constraint name aren't supported in typeorm. Typeorm rely on its own names to make a proper schema sync. So, current behaviour you see is correct.

**Comment by lukejagodzinski** [comment]
@pleerock ok so I assume that this library is not intended to work with existing databases where we can use custom constraint name? That's not a big deal as I can rename constraint in migration but would be great to at least detect that change on migration. Thanks anyway!

**Comment by pleerock** [comment]
@lukejagodzinski we try to support existing databases as much as possible, but there are some things like custom constraint name that aren't supported. Maybe we'll try to add this feature in the future, but its not in our priority list currently.

**Comment by lukejagodzinski** [comment]
@pleerock ok thanks for info :) It's definitely nothing blocking anyone from using it. I can just make some manual changes. Thanks!

**Comment by vegerot** [comment]
@pleerock what about something similar to what you have for migrations: where there is a unique id generated in the front, then a custom name can be given after.  Best of both worlds
