### ISSUE TITLE
UUID and ID Auto_increment on same table

### ISSUE THREAD

**Issue by nikoliveira** [typeorm/typeorm#3278]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

How to use UUID and ID (Auto increment) in the same table?

**Comment by Kononnable** [comment]
Why do you need both? From a database perspective single should suffice. If it is because you want to use eg. ID in your app but show user an UUID - then it is an application logic layer problem and should be separated from storage layer.

**Comment by nikoliveira** [comment]
I want to show the uuid for the user, but is very slow insert with UUID. 
Today I executed some tests.
See:
Test:
Com ID [10 Inserts] Minutos: 0.004966666666666666, segundos: 0.298
Com ID [50 Inserts] Minutos: 0.027183333333333334, segundos: 1.631
Com ID [100 Inserts] Minutos: 0.0421, segundos: 2.526
Com ID [1000 Inserts] Minutos: 0.5875166666666666, segundos: 35.251
Com ID [5000 Inserts] Minutos: 3.8082333333333334, segundos: 228.494

Com UID [10 Inserts] Minutos: 0.044566666666666664, segundos: 2.674
Com UID [50 Inserts] Minutos: 0.2667, segundos: 16.002
Com UID [100 Inserts] Minutos: 0.61065, segundos: 36.639
Com UID [1000 Inserts] Minutos: 6.57315, segundos: 394.389
Com UID [5000 Inserts] Minutos: 36.63303333333333, segundos: 2197.982

**Comment by nikoliveira** [comment]
Thank's 

> yes you can, there is a `@Generated("uuid")` decorator that you can use to mark regular columns as generated.

Thanks, it Works! 👍

**Comment by pleerock** [comment]
You are welcome :)

Answering people questions takes time and lot of efforts. Contribute to the future of TypeORM and donate to the project!
