### ISSUE TITLE
findOne found wrong data with alias

### ISSUE THREAD

**Issue by pavlovsch** [typeorm/typeorm#328]
For details please check special [repo](https://github.com/pavlovsch/bug-typeorm-find-one)

**Comment by pleerock** [comment]
Don't use such syntax - its deprecated and will be removed in next typeorm version. Use query builder instead. Also in your code you probably don't have relation value and its simply not returned you because you used inner join. Try to user `leftJoinAndSelect` instead.

**Comment by pavlovsch** [comment]
Nope, relation value is returned. With `leftJoinAndSelect` i have the same results. But in my code I don't check for relation value. In second fetching but with `alias` and `innerJoinAndSelect/leftJoinAndSelect` properties I still expecting John's data, but receive Mike's data.

**Comment by pavlovsch** [comment]
Query builder works fine, thank you for help!
