### ISSUE TITLE
@CreateDateColumn/@UpdateDateColumn timestamps are off in Postgres

### ISSUE THREAD

**Issue by pwwolf** [typeorm/typeorm#3286]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[x ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Seems similar to #3213 , but I'm seeing this in postgres instead of mysql.
When I query an object that contains @CreateDateColumn fields, the value of those fields comes back 5 hours ahead of the current time. I am in a -5 timezone, so it does seem like it's assuming the value I get back from Postgres is in my local time instead of UTC, and then adding 5 hours to compensate.

I have a simple entity (Test) containing @CreateDateColumn and @UpdateDateColumn fields. I've also added a manually-set timestamp field, `date`, to make the problem more apparent.

```ts
import {
  Entity,
  CreateDateColumn,
  UpdateDateColumn,
  Column,
  PrimaryColumn,
  PrimaryGeneratedColumn
} from "typeorm";

@Entity()
export class Test {
  @PrimaryGeneratedColumn()
  id: number;

  @CreateDateColumn()
  created: Date;

  @UpdateDateColumn()
  updated: Date;

  @Column()
  date: Date;
}
```
Now I create a Test entity, set its date field, and retrieve it

```ts
    console.log(new Date().toISOString());
    let entity = new Test();
    entity.date = new Date();
    await this.connection.getRepository(Test).save(entity);
    let fetched = await this.connection.getRepository(Test).findOne(2);
    console.log(fetched);
```
The resulting output is
```
Test {
  id: 3,
  created: 2018-12-19T19:05:32.054Z,
  updated: 2018-12-19T19:05:32.054Z,
  date: 2018-12-19T14:05:32.040Z
}
```
 
So to walk through the results, the current time UTC is 2018-12-19T14:05:32.040Z (2:05pm UTC/9:05am EST).
The *date* field is set to the current time, and the resulting objects comes back correctly as 2:05pm UTC/9:05am EST. The created/updated fields, however, both show 7:05pm UTC/2:05pm EST. So they're 5 hours ahead of the actual time.

I would have expected the created, updated, and date fields to all have close to the same time.
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
is it same as #3202 ?

**Comment by pwwolf** [comment]
Turns out this was an issue with the pg driver.

What was happening is that before pg would execute the query, it would convert the date from UTC to a local timestamp. So even though the typeorm logs were saying that it was inserting the string "2018-12-19T14:05:32.040Z", pg was converting it to "2018-12-19T09:05:32.040-05:00" when executing the query.
Since a postgres timestamp type has no timezone, Postgres would just save the time as 9:05, ignoring the offset.

The values of the CreateDateColumn columns, however, are saved using the postgres server's timezone setting, which is UTC. That then explains why the values in CreateDateColumn don't match up to the values manually inserted.

Then the second issue happened when the values were retrieved. The pg driver would assume the timestamps were saved in local time and add 5 hours to convert to UTC. That made the manually-inserted value appear correct and the CreateDateColumn to appear off by 5 hours.

So a few options I'm exploring
1. Ensure both the nodejs server and postgres server are running in UTC
2. Set the column types to "timestamptz" instead of the default of "timestamp", which will preserve timezone
3. Tell pg to treat everything as UTC. 

To avoid getting mangled on write I could set
```ts
let driver = this.connection.driver as PostgresDriver;
driver.postgres.defaults.parseInputDatesAsUTC = true;
```

And on retrieval
```ts
driver.postgres.types.setTypeParser(1114, (str: any) => {
      return moment.utc(str).format();
})
```

Closing since this all appears to be behavior caused by the pg library and not typeorm

**Comment by pleerock** [comment]
if you can provide any feedback in #3202 based on your research it would be really great.

**Comment by pontusab** [comment]
When I'm doing this: 

`connection.driver.postgres.types.setTypeParser(1114, str => str)`

I get this error: `Property 'postgres' does not exist on type 'Driver'.`

How can I add `setTypeParser` to Postgres driver?

**Comment by pwwolf** [comment]
@pontusab is that a compilation error?
That's why I had to cast it to PostgresDriver first.
```ts
let driver = this.connection.driver as PostgresDriver;
```

**Comment by pontusab** [comment]
@pwwolf Yep :) Thanks!

**Comment by birkir** [comment]
Without moment:
```ts
(connection.driver as PostgresDriver).postgres.types.setTypeParser(1114,
  (str: string) => new Date(str+'Z')
);
```

**Comment by rakeshta** [comment]
Thank you. This helped me. My code consolidated from all code snippets above to avoid typescript compile issues and not rely on moment.js:
```
        const driver = getConnection().driver as any;
        driver.postgres.defaults.parseInputDatesAsUTC = true;
        driver.postgres.types.setTypeParser(1114, (str: any) => new Date(str + 'Z'));
```

**Comment by elie222** [comment]
Another solution is to set the Node server to UTC timezone:

```sh
TZ=utc node index.js
```

More here: https://dev.to/raphaelbadia/how-to-avoid-and-debug-most-of-timezone-problems-in-production-2h1l
