### ISSUE TITLE
Annotation of overridden entity attribute is ignored

### ISSUE THREAD

**Issue by dominic-simplan** [typeorm/typeorm#3287]
**Issue type:**

[X] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Assume I have the following entity structure:

```
@Entity()
export class Company {
    @OneToMany(type => Person, person=> person.company)
    persons: Array<Person>;
}

@Entity()
export class Person {
    @ManyToOne(type => Company , company => company.persons)
    company: Company;
}
```

Now I want to extend `Person` in a new class and add a new column to it:
```
@Entity("Person")
export class CustomPerson extends Person {
    @Column()
    newShinyColumn: string;
}
```

How do I need to load the `Company` with relations so that the `CustomPerson`, and not the `Person` entity is loaded?
I tried to override the `Company` entity as well and redefine the `persons` attribute:
```
@Entity("Company")
export class CustomCompany {
    @OneToMany(type => CustomPerson, person=> person.company)
    persons: Array<CustomPerson>;
}
```

But trying to load the company entity (`getRepository(CustomCompany).find({ relations: ["persons"]})`) still has a reference only to the `Person`, and not to the `CustomPerson` entity.

Should this work or is this structure not supported by TypeORM? I would assume that if I override an attribute in a subclass (`CustomCompany.persons`), the annotations of the overridden attribute should be applied, and not the annotations of the attribute in the parent class anymore.

What I am trying to achieve is having a default project (Company, Person), and a customer specific project which has an extra column on the Person entity.

**Comment by pleerock** [comment]
Don't create a mess. Simply add columns you need to original entity. If you want to add columns dynamically you can try to play around with object proptotype and use more low-level typeorm api.

**Comment by pleerock** [comment]
Explore source code of the `Column` decorator and you'll find an example.

**Comment by dominic-simplan** [comment]
thanks!
