### ISSUE TITLE
Foreign key not showing on a find call

### ISSUE THREAD

**Issue by enricrp8** [typeorm/typeorm#3288]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
In order to reproduce the problem you need to have 2 entities, one called Photo and the other one called User. User has an auto-generated id of type string and a name. Photo has also an auto-generated id, which is also an string, and has a @ManyToOne reference to User, more specifically, to userId. However, whenever I do a repository.find({]) the userId field is not returned, however it is stored inside photo's table.
I am using nestjs framework.

What I have now is the following code:

### User entity:
```typescript
        @Entity()
        export class User extends RootEntity {
            @PrimaryColumn()
            public id: string;

            public name: string;
        }
```
### Photo entity:
```typescript

        @Entity()
        export class Photo extends RootEntity {
            @PrimaryGeneratedColumn()
            public id: string;

            @ManyToOne((type) => User)
            public user: User;
        }
```
### My create-photo.dto.ts:
```typescript

        export class CreatePhotoDto {
            @IsDefined()
            public user: User;
        }

```
### My photo service class:
```typescript

        @Injectable()
        export class PhotoService {
            constructor(
                @InjectRepository(Photo)
                private readonly photoRepository: Repository<Photo>,
            ) {}

            public createPhoto(photo: CreatePhotoDto) {
                this.photoRepository.save(photo);
           }
            public findAll() {
                return this.photoRepository.find({});
            }
       }
```
### My photo controller class:
```typescript

        @Controller("photo")
        export class PhotoController {
            constructor(private readonly photoService: PhotoService) {}

            @Get()
            public findAll() {
                return this.photoService.findAll();
            }
         @Post()
            public createPhoto(@Body() createPhotoDto: CreatePhotoDto) {
                this.photoService.createPhoto(createphotoDto);
            }

       }
```

Whenever I call to findAll, it returns just the id of the photo.
Thanks in advance.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by enricrp8** [comment]
> Change your code to:
> 
> ```ts
>   @Entity()
>         export class Photo extends RootEntity {
>             @PrimaryGeneratedColumn()
>             public id: string;
> 
>             @Column()
>             public userId: number;
> 
>             @ManyToOne((type) => User)
>             public user: User;
>         }
> ```
> 
> How do you expect `userId` to be when its not defined in your model.

I've tried it, but I get a ER_INVALID_USE_OF_NULL compiler error, so I change the column to accept null values (@Column({ nullable: true }).However, when I execute the create call, it returns me the Photo created with the correct userId, but whenever I do the findAll call userID is null.

**Comment by pleerock** [comment]
`ER_INVALID_USE_OF_NULL compiler error` - compiler error? Provide more details.

**Comment by enricrp8** [comment]
> `ER_INVALID_USE_OF_NULL compiler error` - compiler error? Provide more details.

Sorry, not compiler error. It sais:  [TypeOrmModule] Unable to connect to the database. Retrying (1)...
QueryFailedError: ER_INVALID_USE_OF_NULL: Invaliduse of NULL value

**Comment by pleerock** [comment]
I guess you do something wrong. Create a PR with a failing test and minimal reproduction code and lets see if it fails on CI.

**Comment by albertsgrc** [comment]
YOUR FUCKING TEST SYSTEM IS BULLSHIT NIGGA

**Comment by enricrp8** [comment]
Note that changing line 23 of he main test case file from:

```typescript
photo.user = dbUser.id as any;
```
into

```typescript
photo.user = dbUser;
```
fixes the issue. This is related to #536, where according to your last comment it should be supported to assign the inserted reference field to the id instead of the reference instance.

**Comment by pleerock** [comment]
Okay, I'll check your issue. For now simply use `photo.user = dbUser;` or `photo.userId = dbUser.id;`

**Comment by albertsgrc** [comment]
What

> Okay, I'll check your issue. For now simply use `photo.user = dbUser;` or `photo.userId = dbUser.id;`

What is the convention when `photo.users` is an array, e.g a ManyToMany relationship? Should we use `photo.userIds`, `photo.usersIds`, `photo.users = [ { id: 1 }, { id: 2 }, ... ]`... ?

**Comment by pleerock** [comment]
@albertsgrc here we talk about join column, your case in different and you need to set real user objects, e.g. `photo.users = [ { id: 1 }, { id: 2 }, ... ]`

**Comment by brt-han-mai** [comment]
if we explicitly declare something like `@JoinColumn({name: "userId"})` will it work? I see no, on my setup. Please stop blaming the users and try to fix it. `userId` is a valid field in the db and if we select it in `find()` function, e.g. `Photo.find({select: ["id", "userId"]})`, it should be a valid request and valid SQL.

**Comment by BaDo2001** [comment]
I had the same problem, but adding `eager: true` as a connection option fixed it.
From https://typeorm.io/#/relations

> eager: boolean - If set to true, the relation will always be loaded with the main entity when using find* methods or QueryBuilder on this entity

```
       @Entity()
        export class Photo extends RootEntity {
            @PrimaryGeneratedColumn()
            public id: string;

            @ManyToOne((type) => User, { eager: true })
            public user: User;
        }
```

**Comment by JarLowrey** [comment]
Seems to be working fine now, Dec 2020:

    @Field(type => MyModel)
    @ManyToOne(type => MyModel, mod => mod.items)
    mod: MyModel;

    @Column()
    @Field()
    modelId: string;

There are some caveats though. Note that the modelId column is non nullable, so when seeding the proper way would be `model2.myModelId = myModel.id` vs the standard `model2.myModel = myModel`. Also, queries may need to be rewritten: 

      let entity = await MyModel.findOne({ where: {user: {id: 'asdf'}} }) as any; //vs
      let entity = await MyModel.findOne({ where: {userId: 'asdf'} }) as any;

In my opinion, defining an id column is preferred to eager loading or manually defining relations. Getting FK only (vs all fields) improves performance. Also a full query may cause errors when you try to save a model with nested objects: the server might try to overwrite those nested objects in the DB. Defining the FK ids explicitly give you the most control.

Also, in my opinion, TypeORM should make these FK ids available by default and search by id by default. Forcing you to manually create this id column, despite it already being created in the DB/TypeORM backend, seems brittle to me.

**Comment by abrarniyazi** [comment]
> I had the same problem, but adding `eager: true` as a connection option fixed it.
> From https://typeorm.io/#/relations
> 
> > eager: boolean - If set to true, the relation will always be loaded with the main entity when using find* methods or QueryBuilder on this entity
> 
> ```
>        @Entity()
>         export class Photo extends RootEntity {
>             @PrimaryGeneratedColumn()
>             public id: string;
> 
>             @ManyToOne((type) => User, { eager: true })
>             public user: User;
>         }
> ```

Hey there, actually I am having this problem now. Actually it has been working fine for 3-4 months and now suddenly I don't get foreign key id anymore. I do not want to use `eager` and I don't want whole relation. I need just the id. Have you found any other solution to this?

**Comment by jcrben** [comment]
also having this issue on postgres; @imnotjames mind adding driver postgres to the issue?

**Comment by jjhiggz** [comment]
> > I had the same problem, but adding `eager: true` as a connection option fixed it.
> > From https://typeorm.io/#/relations
> > > eager: boolean - If set to true, the relation will always be loaded with the main entity when using find* methods or QueryBuilder on this entity
> > 
> > 
> > ```
> >        @Entity()
> >         export class Photo extends RootEntity {
> >             @PrimaryGeneratedColumn()
> >             public id: string;
> > 
> >             @ManyToOne((type) => User, { eager: true })
> >             public user: User;
> >         }
> > ```
> 
> Hey there, actually I am having this problem now. Actually it has been working fine for 3-4 months and now suddenly I don't get foreign key id anymore. I do not want to use `eager` as I don't want whole relation. I need just the id. Have you found any other solution to this?

This can work, but it's not really an efficient solution. When you set eager to true you are saying that every time a user requests an entity, load all the values from the related entity. That slows down the query and in my case adds WAY to much data to the object being sent to the user.

**Comment by jjhiggz** [comment]
> Seems to be working fine now, Dec 2020:
> 
> ```
> @Field(type => MyModel)
> @ManyToOne(type => MyModel, mod => mod.items)
> mod: MyModel;
> 
> @Column()
> @Field()
> modelId: string;
> ```
> 
> There are some caveats though. Note that the modelId column is non nullable, so when seeding the proper way would be `model2.myModelId = myModel.id` vs the standard `model2.myModel = myModel`. Also, queries may need to be rewritten:
> 
> ```
>   let entity = await MyModel.findOne({ where: {user: {id: 'asdf'}} }) as any; //vs
>   let entity = await MyModel.findOne({ where: {userId: 'asdf'} }) as any;
> ```
> 
> In my opinion, defining an id column is preferred to eager loading or manually defining relations. Getting FK only (vs all fields) improves performance. Also a full query may cause errors when you try to save a model with nested objects: the server might try to overwrite those nested objects in the DB. Defining the FK ids explicitly give you the most control.
> 
> Also, in my opinion, TypeORM should make these FK ids available by default and search by id by default. Forcing you to manually create this id column, despite it already being created in the DB/TypeORM backend, seems brittle to me.

What library is `@Field` coming from. I'm not getting it autosuggested in my app.

**Comment by JarLowrey** [comment]
@jjhiggz https://github.com/MichalLytek/type-graphql

**Comment by imnotjames** [comment]
> TypeORM should make these FK ids available by default and search by id by default. Forcing you to manually create this id column, despite it already being created in the DB/TypeORM backend, seems brittle to me.

TypeORM doesn't just stick fields into your classes at random.  They're explicitly defined.  For example, you can have the field name `coolLevel` but with `@Column({ name: "cool_level"})` it does the `M` part - mapping.

If it was writing just the `id` into that field when not eager then that was a bug.  It breaks the typing and conventions. 

If you just want the relation ID, check out [@RelationID](https://www.github.com/typeorm/typeorm/tree/master/docs%2Fdecorator-reference.md#relationid).  If you feel there should be other ways of referencing these, open another PR with a more detailed feature request.

You can even try `@Column` for the field you want on particular but that acts up sometimes..

As it stands, this has been answered.
