### ISSUE TITLE
Adding .select() to createQueryBuilder return undefined

### ISSUE THREAD

**Issue by valeriy-devpronet** [typeorm/typeorm#329]
```typescript
@EntityRepository(SomeEntity)
export class SomeEntityRepository extends Repository<SomeEntity>
{
   async handleThis()
  {
      const q = this.createQueryBuilder('e')
            .select(['e.id', 'e.anotherProperty'])
            //or 
            //.select('e.id, e.anotherProperty')
            //or even
            //.select('e.id')
            .addOrderBy('e.createdAt', 'DESC')
            .getOne();
  }
}
```
`q` is always `undefined`

but if I remove `.select()` or if i'm using it without parameters it works. But I do not need a complete list of columns in the result.
I did not found how to use `.select()` in the right way nor in examples neither in source.
Thanks.

**Comment by pleerock** [comment]
> But I do not need a complete list of columns in the result.

this feature of partial selection is not supported yet. However it will be supported in next version. Adding @AlexMesser

**Comment by valeriy-devpronet** [comment]
I saw that mentions in another issues. Seems like this issue #245  relates also to that enhancement and if i'm not mistaken this also #296. Am I correct?

**Comment by pleerock** [comment]
partial selection is already supported in latest typeorm versions.

**Comment by valVk** [comment]
does it in stable release or in unstable?

**Comment by pleerock** [comment]
there are some features broken (like cascades and class-table and single-table inheritances, but they did not work well before too), as well lot of bugfixes and new features.

**Comment by JaosnHsieh** [comment]
having same issue here. current work around is to comment out partial select.

from

```typescript
      Device.createQueryBuilder('device')
      .innerJoinAndSelect('device.xxx', 'xxx', 'xxx.yyyy = :s', {
        s: '123',
      })
      .innerJoinAndSelect('device.a', 'a')
      .innerJoinAndSelect('device.b', 'b')
      .select(['a.id',', 'a.id', 'a.name'])
      .getOne();
```


to

```typescript
  Device.createQueryBuilder('device')
      .innerJoinAndSelect('device.xxx', 'xxx', 'xxx.yyyy = :s', {
        s: '123',
      })
      .innerJoinAndSelect('device.a', 'a')
      .innerJoinAndSelect('device.b', 'b')
//      .select(['a.id',', 'a.id', 'a.name'])
      .getOne();
```

versions
```
"pg": "^7.3.0",
 "typeorm": "0.2.25"
```
