### ISSUE TITLE
Handling SQL Local Variables

### ISSUE THREAD

**Issue by projectyang** [typeorm/typeorm#3290]
**Issue type:**

[x] question
[] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Getting an ER_PARSE_ERROR when trying to use local variables in a raw sql query:

await manager.query(`SET @rowindex := -1;
 
SELECT
   AVG(g.grade)
FROM
   (SELECT @rowindex:=@rowindex + 1 AS rowindex,
           grades.grade AS grade
    FROM grades
    ORDER BY grades.grade) AS g
WHERE
g.rowindex IN (FLOOR(@rowindex / 2) , CEIL(@rowindex / 2));

  `);

What's the correct way to use local variables within the raw SQL query?

**Comment by pleerock** [comment]
You shall use underlying driver API for this purpose. Read `mssql` documentation on how to do it, you can access mssql connection from `connection.driver`
