### ISSUE TITLE
andWhereInIds bug

### ISSUE THREAD

**Issue by taehyeong224** [typeorm/typeorm#3293]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

I want use query in below
```
 SELECT *
 FROM `guest` `guest`
 LEFT JOIN `someting` `someting` ON `someting`.`guestIdx`=`guest`.`idx` 
WHERE `guest`.`isDeleted` = false 
AND guest.sometingIdx = 1111 
AND (`guest`.`name` LIKE ? OR `guest`.`phone` LIKE ?) AND `guest`.`idx` in (?, ?, ?) 
GROUP BY `guest`.`idx` 
```

so, I use andWhereIds(1,2,3,4)

but result query is

```

...
AND ( guest.idx = ? or guest.idx = ? ... ) 
```

and I use function .getManyRaw() but not work it's length = 0

I copied this query and use it in mysql console it was work.

finally, I changed andWhereInIds to andWhere(`guest.idx in (${somearray.toString()})`)

this is work.

I think andWhereIds function has some problems

**Comment by pleerock** [comment]
you didn't say what exactly is wrong with `AND ( guest.idx = ? or guest.idx = ? ... ) `?

**Comment by taehyoung** [comment]
if use andWhereIds, then it convert (idx =? or idx=? or idx=? or idx=?...) not (idx in (?,?,?,?)

and .andWhereIds([1,2,3]).getRawMany() has length = 0

but when I use .andWhere(`idx in (1,2,3)`).getRawMany() got correct result.

i'm sorry about my english 😢

**Comment by pleerock** [comment]
strange, `(idx =? or idx=? or idx=? or idx=?...)` and `(idx in (?,?,?,?)` are equivalent expressions. Can you find a differences? Maybe parameters values are different or what?

**Comment by pleerock** [comment]
can you please compare SQLs and parameters order?

**Comment by taehyoung** [comment]
When I use 'andWhere', I use 'template literal' like `(${1,2,3})`not parameter option
```
SELECT guest.*,
 COUNT(`reservation`.`idx`) AS `visitCount`, 
MAX(reservation.`finishTime`) AS `latestVisit`

 FROM `guest` `guest` 
LEFT JOIN `something` `something` ON `something`.`guestIdx`=`guest`.`idx` 

WHERE `guest`.`isDeleted` = false 
AND (`guest`.`name` LIKE ? OR `guest`.`phone` LIKE ?) 
AND `guest`.`idx` in (1,2,3) 

GROUP BY `guest`.`idx` 
HAVING visitCount >= 1 
AND latestVisit >= '2018-02-20 14:40:20' 
AND latestVisit is not null 
ORDER BY latestVisit 
DESC LIMIT 11 -- PARAMETERS: ["%abc%","%abc%"]

```

And this is when use andWhereInIds
```
SELECT guest.*,
 COUNT(`reservation`.`idx`) AS `visitCount`, 
MAX(reservation.`finishTime`) AS `latestVisit`

 FROM `guest` `guest` 
LEFT JOIN `something` `something` ON `something`.`guestIdx`=`guest`.`idx` 

WHERE `guest`.`isDeleted` = false 
AND (`guest`.`name` LIKE ? OR `guest`.`phone` LIKE ?) 
AND ((`guest`.`idx` = ?) OR (`guest`.`idx` = ?) OR (`guest`.`idx` = ?))  

GROUP BY `guest`.`idx` 
HAVING visitCount >= 1 
AND latestVisit >= '2018-02-20 14:40:20' 
AND latestVisit is not null 
ORDER BY latestVisit 
DESC LIMIT 11 -- PARAMETERS: [1,2,3,"%abc%","%abc%"]

```

now that it was parameters order probloms

i make query 

```
guestQueryBuilder.
              ....
               andWhere("(guest.name LIKE :query OR guest.phone LIKE :query)", {
                query: "%" + query.trim() + "%"
            })
         .andWhereInIds([1,2,3])
         .getRawMany()
```

**Comment by taehyoung** [comment]
sometimes, queryBuilder paramers are not match,

**Comment by pleerock** [comment]
it looks like a bug. actually, `whereInIds` methods were created for internal usage, so maybe its even good not to use them.

**Comment by taehyoung** [comment]
thank you 😄

**Comment by silentroach** [comment]
@taehyoung can you recheck it in master?
