### ISSUE TITLE
@IdColumn decorator

### ISSUE THREAD

**Issue by 19majkel94** [typeorm/typeorm#33]
It would be nice to have an alias `@IdColumn` for `@PrimaryColumn("int", { generated: true })`. 

It should be easy to do and I think I might be able to do the PR but not know, I have to learn TypeORM better and build some app using it first :wink:

**Comment by pleerock** [comment]
> It should be easy to do and I think I might be able to do the PR but not know, I have to learn TypeORM better and build some app using it first 

yes, sure its much more complicated codebase and requires time to learn it

> It would be nice to have an alias @IdColumn for @PrimaryColumn("int", { generated: true })

But id column means that id will have an unique identifier, right? And it isnt necessary to be generated

**Comment by 19majkel94** [comment]
It might be named `@AutoIdColumn` or sth meaningfull, it's just an alias and behave the same as `@PrimaryColumn("int", { generated: true })` - it creates database column `id          | int(11)      | PRIMARY KEY AUTO_INCREMENT` :wink:

Almost everyone use it and the `@PrimaryColumn("int", { generated: true })` syntax repeated in every class doesn't look nice and it's a pain to code it every time.

**Comment by pleerock** [comment]
> Almost everyone use auto generated int primary key in databases and the @PrimaryColumn("int", { generated: true }) syntax repeated in every class doesn't look nice and it's a pain to code it every time.

agree. But'll call it `@GeneratedIdColumn` to be more akin to generated in column options. implemented in b39e5ae

**Comment by 19majkel94** [comment]
Ok, great! Thanks! :smiley:
