### ISSUE TITLE
Indices created for Table Inheritance

### ISSUE THREAD

**Issue by MatthiasKunnen** [typeorm/typeorm#3300]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[x] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[x] `sqlite`
[x] `sqljs`
[x] `react-native`
[x] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When a model is using table inheritance, two indices are automatically created. One on the discriminator column, and one on the discriminator and primary column(s). Code here:
https://github.com/typeorm/typeorm/blob/6cd665fef156611b51030172b18cfd32dced1d26/src/metadata-builder/EntityMetadataBuilder.ts#L600-L619

I can see how the first index would benefit queries such as retrieving all Child Entities. I can't, however, come up with cases for the second index. In which cases does the ORM issue queries that benefit from the second index?

**Comment by pleerock** [comment]
We need to check who made this change and ask motivation. If its me - then I dont remember =(

**Comment by MatthiasKunnen** [comment]
I went down the `git blame` rabbit hole and found the original commit.
It was you :)
2016-09-11 https://github.com/typeorm/typeorm/commit/cf2d6f5f9#diff-d0c02b8b8b9772f4f8c2030e45fbf7acR387 Merged in b6e27c07f41470798c86e67e7e004387503ce145 PR #29

**Comment by pleerock** [comment]
haha okay. So it was two years ago. I don't know why. Probably we can remove it, I don't see reason why we need it.

**Comment by MatthiasKunnen** [comment]
I'll make a PR to remove this.
