### ISSUE TITLE
Tracking query time for slow queries and statsd timers

### ISSUE THREAD

**Issue by chiangf** [typeorm/typeorm#3302]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'd like to be able to log slow queries to console/file and keep track of average query times with statsd. From http://typeorm.io/#/logging/using-custom-logger, I know that I can define a custom logger, and if I set `maxQueryExecutionTime=-1` (since 0 will be falsy), then the custom logger will always be called.

At that point, I can fire `statsd.timer` as well as check if the query took longer than some threshold and log as well. But this feels more difficult than it should be. I also looked into subscribers but it doesn't seem to track query time.

Is there a better way to do this?

**Comment by pleerock** [comment]
what is difficult exactly? Creating a custom logger?

**Comment by chiangf** [comment]
@pleerock It didn't feel right to have to use the slow query logger since I am trying to track statsd for all queries (not just slow ones), and setting maxQueryExecutionTime=-1 felt strange too. So I figured there must be another way. But I'm fine with it if this is the official way.

**Comment by pleerock** [comment]
ah okay. We probably can add `beforeQuery` and `afterQuery` subscriber events. Feel free to PR

**Comment by GaryChangCN** [comment]
anything new here?

**Comment by MoritzGruber** [comment]
If anyone else has the same problem.
Here is a solution I came up with:

`
var pg = require('pg');
var shimmer = require('shimmer');


function wrapQuery(orig, name) {
  return function wrappedFunction(sql) {

    console.time(`PSQL: ${sql}`);
    var args = arguments
    var index = args.length - 1
    var cb = args[index]

    if (Array.isArray(cb)) {
      index = cb.length - 1
      cb = cb[index]
    }

    if (typeof cb === 'function') {
      args[index] = end
      return orig.apply(this, arguments)
    } else {
      cb = null
      var query = orig.apply(this, arguments)

      if (typeof query.on === 'function') {
        query.on('end', end)
        query.on('error', end)
      } else if (typeof query.then === 'function') {
        query.then(end)
      }

      return query
    }
    function end() {
      console.timeEnd(`PSQL: ${sql}`);
      if (cb) return cb.apply(this, arguments)
    }
  }
}
shimmer.wrap(pg.Client.prototype, 'query', wrapQuery);

`

**Comment by mohsinamjad** [comment]
@MoritzGruber can you explain a little on what's going on that gist
I just want to log the duration of each query/mutation in terminal or maybe push those on Prometheus.

**Comment by JeremySazMining** [comment]
> ah okay. We probably can add `beforeQuery` and `afterQuery` subscriber events. Feel free to PR

Was this, or something equivalent for job, ever added?

**Comment by simplenotezy** [comment]
Isn't this solved by https://orkhan.gitbook.io/typeorm/docs/logging#log-long-running-queries ?

**Comment by JeremySazMining** [comment]
> Isn't this solved by https://orkhan.gitbook.io/typeorm/docs/logging#log-long-running-queries ?

thx! I will give it a try :)

**Comment by andrewda** [comment]
I have a need for something like this and found that custom loggers were not quite the solution I was looking for. I created PR https://github.com/typeorm/typeorm/pull/9270 to add `BeforeQuery` and `AfterQuery` subscriber events per https://github.com/typeorm/typeorm/issues/3302#issuecomment-449422542. If anyone here wants to take a look and see if this would solve their use cases as well (or could be modified to fit it), that would be great!

**Comment by gaollard** [comment]
anything new here?
