### ISSUE TITLE
Postgres key(keyId, keyId, keyId)=(2, 2, 2) is not present in table constraint, but it is

### ISSUE THREAD

**Issue by egorzaremba** [typeorm/typeorm#3306]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
https://stackoverflow.com/questions/53883123/postgres-keykeyid-keyid-keyid-2-2-2-is-not-present-in-table-constraint

**Comment by pleerock** [comment]
answered you in SO question.

**Comment by egorzaremba** [comment]
Thanks, I changed according to your code, but it still failed with same error

**Comment by pleerock** [comment]
There is no problem with typeorm, problem is in your code, check and fix it and everything will work.
