### ISSUE TITLE
Field doesn't have a default value

### ISSUE THREAD

**Issue by johnbendi** [typeorm/typeorm#331]
I specified a `{default: null}` option to a column in my entity but it still gives the above error when trying to insert without the field in the entity. 

Here is an excerpt of the error:
```
error during executing query:Error: ER_NO_DEFAULT_FOR_FIELD: Field 'full_name' doesn't have a default value
executing query: ROLLBACK
{ Error: ER_NO_DEFAULT_FOR_FIELD: Field 'full_name' doesn't have a default value
    at Query.Sequence._packetToError (~/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (~/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (~/app/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (~/app/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (~/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (~/app/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
```

**Comment by pleerock** [comment]
If you want to set null as default you should do `nullable: true` instead of `{default: null}`

**Comment by johnbendi** [comment]
Alright, I saw where you mentioned that elsewhere as a hack but was wondering if that is standard. I had already started on that path. Thanks for clarifying.

**Comment by pleerock** [comment]
nullable: true is a standard and won't be changed

**Comment by marioallaa** [comment]
i am facing a similar problem: 

```

@Entity()
export class entity extends BasicEntity {

...
  @Column({nullable: true})
  forUser: string
...
}

```

and when I try to save something on the database, by sending a request that does not contain the 'forUser' variable, NestJS returns a 500 "Internal Server Error" and it logs the following: 
```
[Nest] 4998   - 05/05/2021, 02:19:47   [ExceptionsHandler] Field 'forUser' doesn't have a default value +10360ms
QueryFailedError: Field 'forUser' doesn't have a default value
    at new QueryFailedError 

```

**Comment by taoliujun** [comment]
> i am facing a similar problem:
> 
> ```
> 
> @Entity()
> export class entity extends BasicEntity {
> 
> ...
>   @Column({nullable: true})
>   forUser: string
> ...
> }
> ```
> 
> and when I try to save something on the database, by sending a request that does not contain the 'forUser' variable, NestJS returns a 500 "Internal Server Error" and it logs the following:
> 
> ```
> [Nest] 4998   - 05/05/2021, 02:19:47   [ExceptionsHandler] Field 'forUser' doesn't have a default value +10360ms
> QueryFailedError: Field 'forUser' doesn't have a default value
>     at new QueryFailedError 
> ```

hot to resolve it? man.

**Comment by estani** [comment]
I have the same problem (within NestJs). I think the culprit is `synchronise: true` in my case, which is not working properly.

Here's the entity excerpt:
```js
// excerpt entity.js
  @Column({
    unique: true,
    nullable: false
  })
  version: string;

  @Column({
    nullable: true
  })
  message: string;
```
Here's the log entries of the synchronise SQLs.

First run (note message is wrong):
```
...
query: ALTER TABLE `version` CHANGE `message` `message` varchar(255) NULL
query: ALTER TABLE `version` CHANGE `version` `version` varchar(255) NULL
query: ALTER TABLE `version` CHANGE `message` `message` varchar(255) NOT NULL
```
second run (note version is wrong):
```
...
query: ALTER TABLE `version` CHANGE `version` `version` varchar(255) NOT NULL
query: ALTER TABLE `version` CHANGE `message` `message` varchar(255) NULL
query: ALTER TABLE `version` CHANGE `version` `version` varchar(255) NULL
```

And then it alternates between the two. So synchronise does not seam to be idempotent and/or there are some caching mechanism going awry.
The workaround for me is to turn synchronise off and forget about it, now it works reliably.

**Comment by lolicrafter** [comment]
> I have the same problem (within NestJs). I think the culprit is `synchronise: true` in my case, which is not working properly.
> 
> Here's the entity excerpt:
> 
> ```js
> // excerpt entity.js
>   @Column({
>     unique: true,
>     nullable: false
>   })
>   version: string;
> 
>   @Column({
>     nullable: true
>   })
>   message: string;
> ```
> 
> Here's the log entries of the synchronise SQLs.
> 
> First run (note message is wrong):
> 
> ```
> ...
> query: ALTER TABLE `version` CHANGE `message` `message` varchar(255) NULL
> query: ALTER TABLE `version` CHANGE `version` `version` varchar(255) NULL
> query: ALTER TABLE `version` CHANGE `message` `message` varchar(255) NOT NULL
> ```
> 
> second run (note version is wrong):
> 
> ```
> ...
> query: ALTER TABLE `version` CHANGE `version` `version` varchar(255) NOT NULL
> query: ALTER TABLE `version` CHANGE `message` `message` varchar(255) NULL
> query: ALTER TABLE `version` CHANGE `version` `version` varchar(255) NULL
> ```
> 
> And then it alternates between the two. So synchronise does not seam to be idempotent and/or there are some caching mechanism going awry. The workaround for me is to turn synchronise off and forget about it, now it works reliably.

thanks bro,you save me
