### ISSUE TITLE
Why not getRawManyAndCount method?

### ISSUE THREAD

**Issue by zhongzhong0505** [typeorm/typeorm#3317]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.98` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

my sql like this:

```
select max(date) as maxDate , min(data) as minData, name, email from user group by sessionId
```

i need mapping select columns to one Entity , but i can not found getRawManyAndCount method.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
I think this is not possible now. But I was looking for this method before so maybe it is time to introduce in typeorm api. Lets see what @pleerock say.

**Comment by zhongzhong0505** [comment]
> I think this is not possible now. But I was looking for this method before so maybe it is time to introduce in typeorm api. Lets see what @pleerock say.

@vlapo  i use getManyAndCount method, but this method can not return maxTs and minTs to Entity,  the Entity like this:

```
@Entity()
class User {
    @Column()
     name: string
    ...
    maxTs: number
    minTs: number
}
```

**Comment by pleerock** [comment]
this request doesn't make much sense. `getManyAndCount` does two queries anyway, so consider to call `getRawMany` and `getCount` separately to get the result you need.
