### ISSUE TITLE
cascadeRemove on ManyToMany-Relations 

### ISSUE THREAD

**Issue by loliman** [typeorm/typeorm#332]
Hi there,

is cascadeRemove on ManyToMany-Relations not possible anymore? If yes, why? 

Thanks in advance!

**Comment by pleerock** [comment]
Cascade removes are one of the most complex ORM features. There are some problems caused by circular references in cascade remove functionality. I had temporary removed it, need some time to think better approaches. Please remove objects manually for now

**Comment by pleerock** [comment]
Cascades remove concept was completely removed from the ORM. Use `onDelete` property of the relation to set a database-level cascade removes.
