### ISSUE TITLE
QueryBuiler: group by is removed from SQL query when using having

### ISSUE THREAD

**Issue by mohamed-badaoui** [typeorm/typeorm#3322]
**Issue type:**
[X] bug report

**Database system/driver:**
[X] `mysql` / `mariadb`

**TypeORM version:**

[X] `latest` 0.2.9
[X] `@next` 0.3.0 alpha.22

QueryBuiler: group by is removed from SQL query when using having

**Steps to reproduce or a small repository showing the problem:**
To be completed

**Comment by mohamed-badaoui** [comment]
It is understandable to have group statement stripped from SQL query on a getManyAndCount
So, maybe it should be nice to have a getRawManyAndCount.
Otherwise just execute 2 queries.

**Comment by vlapo** [comment]
We had this discussion before https://github.com/typeorm/typeorm/issues/3317

**Comment by mohamed-badaoui** [comment]
Thanks for the link.

In the comments, @pleerock recomment to
> ... so consider to call getRawMany and getCount separately to get the result you need.

But when you use a group by on query builder, even the getCount should not work simply because it ignores it.

look at https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts#L1728-L1737

**Comment by sandeshgb** [comment]
@pleerock for multiple group by clause, we cannot do the entire query just to get the count. What @mohamed-badaoui  suggested was fair, that we could have something like getRawCount()
