### ISSUE TITLE
Column for Array[Enum] gives Postgres & TypeOrm an error

### ISSUE THREAD

**Issue by aronraja** [typeorm/typeorm#3323]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] `0.2.9` (or put your version here)

Hello there!

I have a problem with creating a `Column` for my UserEntity. I want to insert some enums inside an Array. I've looked at some issues and seemed fixed but in my case I couldn't find an answer.

**User.entity**
```typescript
@Column({
    type:"enum", 
    enum: AppRoles, 
    array: true, 
    default: AppRoles[AppRoles.USER]
})
roles: AppRoles;
```

*Roles.ts*
```typescript
export enum AppRoles {
    USER = "USER",
    ADVANCED = "ADVANCED",
    USERADMIN = "USERADMIN",
    ADMIN = "ADMIN"
}
```

*Error*
```
ExceptionHandler] type "enum[]" does not exist +77ms

QueryFailedError: type "enum[]" does not exist
    at new QueryFailedError (/DIRECTORY/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/DIRECTORY/src/driver/postgres/PostgresQueryRunner.ts:175:30)
    at Query.handleError (/DIRECTORY/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/DIRECTORY/node_modules/pg/lib/client.js:160:17)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:442:20)
    at Socket.<anonymous> (/DIRECTORY/node_modules/pg/lib/connection.js:124:12)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
```

**Comment by vlapo** [comment]
First `default: AppRoles[AppRoles.USER]` is really weird construction and is incorrect.

But still I think we have bug related to array like default values:

For postgres enum types this will generate error:
```typescript
@Column({
    type:"enum", 
    enum: AppRoles, 
    array: true, 
    default: [AppRoles.USER]
})
roles: AppRoles;
```
Same error for basic columns like numeric[]. This also generate error.
```typescript
@Column({ type: "numeric", array: true, default: [1, 2, 3] })
numerics: number[];
```
I think it is all related to `PostgresDriver.normalizeDefault()` method where we have to better handle array types and also enum array types.

**Comment by pleerock** [comment]
how it should look like in SQL? `DEFAULT ???`

**Comment by pleerock** [comment]
I think correct syntax is `default: '{1,2,3}'`, but we probably can extend normalizeDefault to transform javascript array into this format.

**Comment by vlapo** [comment]
`'{1,2,3}'::numeric[]` for basic data types. Need to cast.

**Comment by pleerock** [comment]
Im sure this is how it currently works:

```ts
@Column({ type: "numeric", array: true, default: '{1,2,3}' })
numerics: number[];
```

**Comment by aronraja** [comment]
Thanks for the response @pleerock  and @vlapo . This is the SQL query what was requested:

```
query: SELECT "n"."nspname", "t"."typname" FROM "pg_type" "t" INNER JOIN "pg_namespace" "n" ON "n"."oid" = "t"."typnamespace" WHERE "n"."nspname" = current_schema() AND "t"."typname" = 'user_roles_enum'
query: CREATE TYPE "user_roles_enum" AS ENUM('USER', 'ADVANCED', 'USERADMIN', 'ADMIN')
query: ALTER TABLE "user" ADD "roles" "user_roles_enum" array NOT NULL DEFAULT 'USER'::enum[]
query failed: ALTER TABLE "user" ADD "roles" "user_roles_enum" array NOT NULL DEFAULT 'USER'::enum[]
```
