### ISSUE TITLE
Typeorm not using default charset from database

### ISSUE THREAD

**Issue by btxtiger** [typeorm/typeorm#3326]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

From MySQL connection options:
```
/**
 * The charset for the connection. This is called "collation" in the SQL-level of MySQL (like utf8_general_ci).
 * If a SQL-level charset is specified (like utf8mb4) then the default collation for that charset is used.
 * Default: 'UTF8_GENERAL_CI'
 */
readonly charset?: string;
```

Using the SQL-level charset seems not to work properly. 
My MySQL database is configured as:
```
Default collation: utf8mb4_unicode_ci
Default charset: utf8mb4
```

When inserting a string, that contains an emoji, the query fails with: 
`ER_TRUNCATED_WRONG_VALUE_FOR_FIELD`, `'Incorrect string value: \'\\xF0\\x9F\\x98\\x9C \' for column \'message\' at row 1',`

That indicates, that the default charset of the database is not used, and the default `UTF8_GENERAL_CI ` used instead (which does not support emoji). 
And in deed, if I set `charset: 'utf8mb4'` explicitly in the typeorm config, inserting works properly.

**Comment by pleerock** [comment]
`charset` is being set to underlying driver. Try to reproduce your error using `mysql` package.

**Comment by pleerock** [comment]
@rustamwin closed it as there is no answer from issue author.

**Comment by robertoandres24** [comment]
> charset: 'utf8mb4'

it works. typeorm documentation is tricky because they  only put the general stuffs in their webpage, but more specific things are in their github repo

**Comment by woodinteractive** [comment]
> > charset: 'utf8mb4'
> 
> it works. typeorm documentation is tricky because they only put the general stuffs in their webpage, but more specific things are in their github repo

@robertoandres24 Can you clarify what exactly worked? I'm having a similar issue and my column types are set to 'uft8mb4', but I'm still getting the error message ```ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xE2\x80\x90tim...' for column 'content' at row 1```

**Comment by iamprawesh** [comment]
**If you are using TYPEORM then you can change the charset on both Entity level and Column level**.

*For entity level* 

    @Entity({engine: 'InnoDB DEFAULT CHARSET=utf8mb4COLLATE=utf8mb4_unicode_ci'})

*For Column Level* 

       @Column({charset: 'utf8mb4',collation: 'utf8mb4_unicode_ci'})

**Comment by zw-slime** [comment]
> My solution is
```@Module({
  imports: [
    CoreModule,
    TypeOrmModule.forRoot({
      type: 'mysql',
      host: config.mysql.host,
      port: config.mysql.port,
      username: config.mysql.username,
      password: config.mysql.password,
      database: config.mysql.database,
      entities: [PageNewEntity, TaskNewEntity],
      synchronize: true,
      charset:'utf8mb4', // set this  set Column set entity do not work
      logging: false,
      // timezone: config.mysql.timezone,
    })
  ],
  exports: [TaskNewModule, TaskAsyncModule],
})
export class AppModule {}```

**Comment by samankhademi** [comment]
For the first time, you want to create your entity something like this:

```
@Entity({
    name: 'xxx',
    engine: 'InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8mb4_xxx_ci',
})
```
Note that it doesn't work for existing tables


Also, you can apply it to columns as well:
```
@Column({name: 'xxx',  charset: 'utf8mb4', collation: 'utf8mb4_xxx_ci'})
```
