### ISSUE TITLE
How can to search column with case insensitive with findAndCount

### ISSUE THREAD

**Issue by hanjeahwan** [typeorm/typeorm#3329]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ 'x' ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
const [results, total] = await this.userRepository.findAndCount({
    where: {
        name: Like(`%${options.keywords}%`),
        status: Equal(options.status)
    },
    order: { id: "DESC" },
    take: options.limit,
    skip: options.skip,
})
```
How can to search the name column with case insensitive in findAndCount api. I saw another solution is use query builder like below , so how to achieve this in findAndCount. Thanks you so much.
```
const posts = await repository.createQueryBuilder()
     .where("LOWER(title) = LOWER(:title)", { title })
     .getMany();
```

**Comment by pleerock** [comment]
You can only use QueryBuilder for your purpose, there is no syntax in find options. We can introduce `Lower` function, but for the first part `LOWER(title)` its problematic to find a good design. If you have good ideas let us know.

**Comment by hanjeahwan** [comment]
> You can only use QueryBuilder for your purpose, there is no syntax in find options. We can introduce `Lower` function, but for the first part `LOWER(title)` its problematic to find a good design. If you have good ideas let us know.

Is there any example to get total count and result with QueryBuilder ? if use QueryBuilder  i need to define two query in order to get total and result. Is it correct?

**Comment by neekey** [comment]
@pleerock Thanks for your info! I found the document [here](https://typeorm.io/#/select-query-builder) about query builder does not mention `getManyAndCount` at all.  It should be mentioned in the document.

**Comment by wyqydsyq** [comment]
Just wondering, would it not be possible for TypeORM to support a pattern like:

```ts
    const title = 'Foo'
    this.myRepository.find({
      where: {
        'LOWER(title)': Lower(title)
      },
    })
```

Where string properties that are not included in the model's properties don't get magically resolved to the associated model property column and are instead used literally in the query e.g.

```
SELECT * FROM `myModel` WHERE LOWER(title) = LOWER('Foo')
``

This requires the developer to ensure it matches up to actual database columns without any type safety against the model's defined properties, but it's still a nicer API than constructing queries manually with QueryBuilder where you don't get any type safety on column names anyway.

**Comment by n1kalai** [comment]
this is what you need exactly 

```
 const [result, total] = await this.findAndCount(
    {
  where: { title: Raw(alias => `LOWER(${alias}) Like '%${value}%'`) },

take: take,
  skip: skip
}

);
  return {
    data: result,
    count: total
  }
```

**Comment by zhanbst** [comment]
> this is what you need exactly
> 
> ```
>  const [result, total] = await this.findAndCount(
>     {
>   where: { title: Raw(alias => `LOWER(${alias}) Like '%${value}%'`) },
> 
> take: take,
>   skip: skip
> }
> 
> );
>   return {
>     data: result,
>     count: total
>   }
> ```

Bad idea! In all ways you have sql injection

**Comment by vensauro** [comment]
> > this is what you need exactly
> > ```
> >  const [result, total] = await this.findAndCount(
> >     {
> >   where: { title: Raw(alias => `LOWER(${alias}) Like '%${value}%'`) },
> > 
> > take: take,
> >   skip: skip
> > }
> > 
> > );
> >   return {
> >     data: result,
> >     count: total
> >   }
> > ```
> 
> Bad idea! In all ways you have sql injection

```js
Raw(alias =>`LOWER(${alias}) Like 'LOWER(:value)'`, { value: "wubba lubba" })
```

**Comment by LucaGuidoRegolini** [comment]
I tried your solution and I'm having the following error

`QueryFailedError: could not determine data type of parameter $1`

I did a little research and found that it could be because I'm using Postgres, but I can't find a solution.

my code:

```js
const clients = await clientRep.find({
      order: {
        name: "ASC",
      },
      where: {
        name: Raw((columnAlias) => `LOWER(${columnAlias}) Like :name`, { name: name }),
        phone: Like(`%${phone}%`),
      },
      take: Number(10),
    });

```

**Comment by kenso312** [comment]
```

**Comment by kenso312** [comment]
```
Raw((alias) => `LOWER(${alias}) Like LOWER(:value)`, {
            value: `%${keyword}%`,
          })
```
I think no single quota needed.
