### ISSUE TITLE
[FEATURE REQUEST]Auto generate REST api

### ISSUE THREAD

**Issue by TangMonk** [typeorm/typeorm#333]

**Comment by pleerock** [comment]
same proposal in #286 . Closing as duplicate. Please provide a deep proposal of the future request in there.

**Comment by jure** [comment]
I think the feature proposed in #286 is different. This one is more likely about something like: https://github.com/alarner/bookshelf-api, i.e. automatically generating a CRUD API server side.

Is this correct, @TangMonk?

**Comment by TangMonk** [comment]
@jure yes, it similar to bookshelf-api

**Comment by pleerock** [comment]
start with a deep proposal on this feature request
