### ISSUE TITLE
Creating a WITHOUT ROWID table

### ISSUE THREAD

**Issue by P0oOOOo0YA** [typeorm/typeorm#3330]
**Issue type:**

[*] question

**Database system/driver:**
[*] `sqlite`

**TypeORM version:**
[*] `latest`

In SQLite, one can create a [`WITHOUT ROWID`](https://www.sqlite.org/withoutrowid.html) table with the following query.

```sql
CREATE TABLE IF NOT EXISTS wordcount(
  word TEXT PRIMARY KEY,
  cnt INTEGER
) WITHOUT ROWID;
```
What is its equivalent in TypeORM?

**Comment by pleerock** [comment]
Its not supported. We can make `@Entity` to accept this option and use in during query building. Feel free to contribute.
