### ISSUE TITLE
impossible select some fields with leftJoin, it's needed always leftAndSelect

### ISSUE THREAD

**Issue by webmobiles** [typeorm/typeorm#3333]
**Issue type:**
[x] bug report

**Database system/driver:**

[x] `postgres`
**TypeORM version:**

[ ] 0.2.8

**Steps to reproduce or a small repository showing the problem:**

 startups  --> deals ---> organizations

i can't select organizations fields, I need do a  .leftJoinAndSelect for 'deals' if i want to get 'organizations' fields, why ? sometimes i get just silent result with  no fields.

it's a bug solved on prs?  I find very hard to use typeorm but simple sql with a lot of related tables. anyone are using a innerJoin, with manual select? where is the trick?

**Comment by Kononnable** [comment]
Care to elaborate? Some code snippets would be nice - without them we have no idea how your entities are declared, what are you really doing etc. So without a real issue description we can only guess what(who) is to blame.

You should post code snippet with yours ussage of query builder, generated query by typeorm and query you wish to achieve(in sql).

**Comment by Kononnable** [comment]
Closing as no response from the author.
