### ISSUE TITLE
GCP Firestore Support

### ISSUE THREAD

**Issue by KitsuneDev** [typeorm/typeorm#3334]
I'm currently porting a project I was working on to zeit.co's now.sh, and I believe Google Cloud Firestore is an accessible way to store data in the cloud, but, unfortunately, it is not supported by TypeORM. I'm currently trying to write a driver, but since I don't have much experience, I don't know if I'll be able to finish it. Is Firestore support planned for the future? Anyone else has interest in this?

**Comment by IngAjVillalon** [comment]
Yes please,
Support for firestore ... I join the request.

**Comment by desarrollotrimax** [comment]
Yes please, Support for firestore! I also join the request.

**Comment by Crewnie** [comment]
It would be great if TypeORM had support for Firestore...

**Comment by Radecom** [comment]
Yes!... It would be Great!  I also join the request.

**Comment by havenchyk** [comment]
Guys, just put your :+1: to the first post, if you’re interested. Thanks ;)

**Comment by pleerock** [comment]
Its a non-relational database right? If yes, then unfortunately we don't have a plans to support any new non-relational database. Its a huge work to add a support for a new non-relational database driver and unfortunately we don't have a time currently. But if you want to contribute - feel free. I see many people are interested - you can contribute by implementing this feature or provide a [commercial support](https://github.com/typeorm/typeorm/issues/3267).

**Comment by rustamwin** [comment]
> Its a non-relational database right?

Yep. Its NoSQL database

**Comment by apnerve** [comment]
Firebase API is already so straight forward. Why complicate it by using an ORM? Isn't it an overhead?

**Comment by epoleacov** [comment]
@apnerve Answer is simple, if you have reusable codebase and next project you want to switch from Firebase to for example MongoDB, you have to rewrite all related sources, even DB structure the same. 
In case both supported by TypeORM, you have just to change configs.

**Comment by napalm272** [comment]
This would be amazing!

**Comment by gavinwilliams** [comment]
+1

**Comment by otri** [comment]
A simple TypeORM wrapper for Firestore would be helpful for a number of issues that are not NoSQL specific:
- portability between other databases targets
- schema migration (upgrades) are more concretely managed with an ORM schema definition
- Firestore uses a Timestamp class to natively wrap Dates, and process them efficiently.  so not a simple type definition.  This would be the one mapping that TypeORM could do well.

TypeORM schemas can be easily generated by using [@marcj/marshal](https://github.com/marcj/marshal.ts#typeorm).
This is a stepping stone towards full interop between Firestore, Nodejs apps, and REST.

So I +1 this too...

**Comment by francismariecayaco** [comment]
Yes please,
Support for firestore ... I join the request.

**Comment by destructor465** [comment]
I join too, It would be good to have support for firestore.

**Comment by jayarjo** [comment]
Firestore!

**Comment by FlxEd** [comment]
Would be interested as well because I don't have the skills to code such a driver :(
+1 then :)

**Comment by acSpock** [comment]
While the community awaits a standard solution, are there working examples in the field for firebase with typeorm?

**Comment by Leeaandrob** [comment]
Any news about the interest in start a feat to add the support to Firestore like Mongodb?  @pleerock

**Comment by RWOverdijk** [comment]
Cam something like fireorm help? https://fireorm.js.org/

I found it while looking for alternative solutions. It seems a bit weird to me but with some voodoo it could maybe be useful here?

**Comment by Daniel-SGA** [comment]
I wouldn't recommend Fireorm as it's not maintained and has several issues.

Recently I found the https://firelordjs.com/ and so far it works nicely. It's not true ORM though. It's built around type checking, but it's interchangeable between server/client.

**Comment by fzn0x** [comment]
I don't understand why people need ORM for this, use AI.

**Comment by uchar** [comment]
@fzn0x  lol AI hype is even here
