### ISSUE TITLE
Get streamed data from raw query

### ISSUE THREAD

**Issue by qmphan** [typeorm/typeorm#3341]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello,

Is there a way to get streamed data from a raw query? I am calling a stored procedure that return a table of some hundred thousands of lines and write the data to a .csv file. Here is the syntax of the query in postgresql:

```
SELECT * FROM get_message_for_enterprise(10)
```

I can get the result in form of list with EntityManager.query but that will use too much memory.

It would be simple if I could use QueryBuilder to create this kind of query but it doesn't seem to be possible.

Any hints on how to do this please?

Cheers,
David

**Comment by nicomouss** [comment]
You can play with raw result, not sure if you've already stumbled on this in the doc :
https://github.com/typeorm/typeorm/blob/9570052bc0a8aaab4dc1019799ee397799db51f4/docs/select-query-builder.md#getting-raw-results

**Comment by qmphan** [comment]
@nicomouss : getRawMany function also returns a list. I don't want to get all the result in a list at once because that list would take up a lot of memory. 

I would like to have access to a "cursor" and use fetchOne to get each line in a loop.

**Comment by nicomouss** [comment]
@qmphan: stream() function should return a stream, from where you can work from. Haven't tested that yet, just reading it from the doc.

**Comment by nicomouss** [comment]
@qmphan Ok, is there actually any architectural decision/design that prevent you to use a QueryBuilder inside your code ?

**Comment by vlapo** [comment]
You can use `connection.manager.queryRunner.stream("SELECT * FROM get_message_for_enterprise(10)");` function for now. 

But I think this is relevant request and maybe we should add `stream` method to manager and repository api.

**Comment by qmphan** [comment]
Thank you @vlapo. Let me try it.

**Comment by Kononnable** [comment]
@qmphan  Did you resolve your issue?

**Comment by pleerock** [comment]
@qmphan yes its going to work. Why you didn't use `connection.manager.queryRunner.stream` ?

**Comment by vlapo** [comment]
@pleerock Should we not expose `stream` method in `EntityManager` same as `query` method?

**Comment by pleerock** [comment]
yes we can, but lets plan it for 0.4.0 since Im planning to rework some concepts and make stream to return entities instead of raw like right now.

**Comment by qmphan** [comment]
@pleerock: queryRunner is undefined when I tried to use it that way in the code bellow:

```typescript
import { getConnection } from 'typeorm';
...
async getMessageStream(enterpriseId: number)  {
    const queryRunner = getConnection().manager.queryRunner;
    await queryRunner.connect();  // <== ERROR HERE: queryRunner is undefined
    const s = await queryRunner.stream(`SELECT * FROM get_message_for_enterprise(${enterpriseId})`);
    s.on('end', () => {
        queryRunner.release();
      }
    );
    s.on('error', () => {
        queryRunner.release();
      }
    );
  
    return s;
}
```

**Comment by n370** [comment]
@qmphan why you didn't used query parameters? The stream method appears to support it just like the query method as well as callbacks to the end and error stream events.

https://github.com/typeorm/typeorm/blob/bdfe67be3762baa248dc45385b08f937a1e17e09/src/driver/postgres/PostgresQueryRunner.ts#L198

https://github.com/typeorm/typeorm/blob/bdfe67be3762baa248dc45385b08f937a1e17e09/src/driver/postgres/PostgresQueryRunner.ts#L155

**Comment by qmphan** [comment]
Good point @n370. Thanks for pointing that out.

**Comment by sanderboom** [comment]
> @pleerock Should we not expose `stream` method in `EntityManager` same as `query` method?

Is this still being worked on?
And support for `pause()` and `resume()`, see https://github.com/typeorm/typeorm/pull/3885 ?

BTW apparently, this:
```ts
    await queryRunner.connect();
```

is not needed (anymore), when looking at https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlQueryRunner.ts#L187

**Comment by fr1sk** [comment]
> yes we can, but lets plan it for 0.4.0 since Im planning to rework some concepts and make stream to return entities instead of raw like right now.

@pleerock When you plan to add entities instead of raw?
