### ISSUE TITLE
How to not insert duplicate row on save() with PrimaryGeneratedColumn()

### ISSUE THREAD

**Issue by Werner91** [typeorm/typeorm#3342]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, I run in this problem:

My entity don't need a PrimaryColumn but typeorm need it otherwise I get the error "MissingPrimaryColumnError". So I added a PrimaryGeneratedColumn with a UUID like this:
`
  @PrimaryColumn()
  @PrimaryGeneratedColumn('uuid')
  uuid: string;
`
This works fine. But now I run into a other problem. When I want to save a second dataset to my db like `repository.save(data)` the .save() method don't see the duplication with already added rows because of the UUID every row have. Is there a way to specify a auto generated uuid field so that .save would not insert duplications?
 
Or a other option which would also work is checking on save if two column values are the same.
Like:

got a entity with objects like this:
`{
firstName: Peter,
lastName: Parker,
city: Fakecity,
phone: 555-666,
}`

Now if there is already a object in the database with the same firstName and lastName then update that object otherwise insert

**Comment by liangchunn** [comment]
If you really want to handle unique columns, you would use the `@Unique` on the class, something like `@Unique(['firstName', 'lastName'])`, but this doesn't _really_ solve your problem.

I would suggest passing the primary `uuid` every single time you want to 'update' something, because it can happen that two people can have the same `firstName` and `lastName`, and because `uuid` is  ultimately the identifier for the row.

Something like this would do it:

```ts
const userRepository = await connection.getRepository(User)
const user = await userRepository.findOne({ uuid })
user.firstName = 'new name'
await userRepository.save(user)
```

**Comment by Werner91** [comment]
Thanks for you answer. But this will not work.
My example was maybe not very good with the firstname and the lastname. The real example is a combination of a timestamp and a special_ID. Multiple rows can have the same special_ID (f.e. 1234) and multiple rows can have the same timestamp (f.e. 1546040428) but only one row can have that exact combination of special_ID 1234 and timestamp 1546040428, thats guaranteed.

Also passing the uuid will not do the trick very well. Because the data that will be saved to the database will be fetched by a API and that can be from one to ten thousand objects so I would have to check every single object separately. And I even don't know the uuid without selecting the data from the table.

Maybe that makes it more clear what my problem is:

Let's say I start with a database like this:

uuid | special_id | timestamp | duration | title | ...   
------------ | ------------- | ------------- | ------------- | ------------- | -------------
abc-123 | 99:88:789  | 1546040428  | 120  | title_1 |...
def-456 | 98:89:880  | 1546040400  | 90  | title_2 | ...

then I fetch some data like this:

    {
      special_id: 99:88:789,
      timestamp: 1546040428,
      duration: 120,
      title: title_1
    },
    {
      special_id: 88:88:888,
      timestamp: 1546040459,
      duration: 70,
      title: title_3
    }

and would like to add them to the database if necessary.

In the documentation it tells me:
`Repository<T>.save()`
>Saves all given entities in the database. If entities do not exist in the database then inserts, otherwise updates.

So what I was thinking the table would look like this (because the first object already exists):

uuid | special_id | timestamp | duration | title | ...   
------------ | ------------- | ------------- | ------------- | ------------- | -------------
abc-123 | 99:88:789  | 1546040428  | 120  | title_1 |...
def-456 | 98:89:880  | 1546040400  | 90  | title_2 | ...
geh-789 | 88:88:888  | 1546040459  | 70  | title_3 | ...

But what it realy looks like is this:

uuid | special_id | timestamp | duration | title | ...   
------------ | ------------- | ------------- | ------------- | ------------- | -------------
abc-123 | 99:88:789  | 1546040428  | 120  | title_1 |...
def-456 | 98:89:880  | 1546040400  | 90  | title_2 | ...
xyz-987 | 99:88:789  | 1546040428  | 120  | title_1 |...
geh-789 | 88:88:888  | 1546040459  | 70  | title_3 | ...

The first object from the fetch should be skipped or update the row in the database because it's the same but because of the uuid the .save() function insert it as a new row. So how can I solve this? As I said I don't need a uuid column but the typeorm need it but with a auto generated ID column the .save() function don't work like in the documentation?

**Comment by liangchunn** [comment]
> My entity don't need a PrimaryColumn but typeorm need it otherwise I get the error "MissingPrimaryColumnError".

Every table needs _at least_ one primary column. This probably ensures 

> Multiple rows can have the same special_ID (f.e. 1234) and multiple rows can have the same timestamp (f.e. 1546040428) but only one row can have that exact combination of special_ID 1234 and timestamp 1546040428, thats guaranteed.

In that case, a suggestion is to remove `uuid` and make `specialId` and `timestamp` the primary keys (which enforces unique (special_ID, timestamp) in the whole table):
```ts
@Entity('table')
export class Table {

  @PrimaryColumn()
  public special_id: string

  @PrimaryColumn()
  public timestamp: number

  @Column()
  public duration: number

}
```

And use it like this:
```ts
const repository = await c.getRepository(TestTable)
const incomingTableData = [
  {
    special_id: '99:88:789',
    timestamp: 1546040428,
    duration: 120,
  },
  {
    special_id: '88:88:888',
    timestamp: 1546040459,
    duration: 70,
  },
]
await repository.save(incomingTableData)
```

I've tested this out and it seems to work fine with this approach, and replicates your desired results.

**Comment by Werner91** [comment]
Cool, this seems to work :) thank you

**Comment by pleerock** [comment]
Guess this can be closed, thanks @liangchunn !
