### ISSUE TITLE
one to Many  Update

### ISSUE THREAD

**Issue by MerelyPerfect** [typeorm/typeorm#3344]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:0.3.0-alpha.22**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
class Company {
   ....
   ....  
  @OneToMany(type => Contact, Contact => Contact.company, {
    cascade: true,
    onDelete: "CASCADE",
    onUpdate: "CASCADE"
  })
  contacts: Contact[];
}

class Contact {
    ...
    ...
    @ManyToOne(type=>Company, Company=>Company.contacts,{ onDelete: 'CASCADE',onUpdate: 'CASCADE' })
    @JoinColumn({ name:'companyId'})
    company:Company | null;
}
```
A simple one to many relation works well with Insert (Using Repository.save)
```
repository.save(company)  
```
When I try to update the Contact alone or add a Contact alone to existing Company, it is not working! Am I mandated to use Query Builder? Is there any concrete example for Query Building on these scenarios?

**Comment by pleerock** [comment]
Can you please create a PR with a failing test so we can reproduce and fix this problem?

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by joseSignot** [comment]
This should open as it is an issue still
