### ISSUE TITLE
Can't Connect To MongoDB Atlas Cluster

### ISSUE THREAD

**Issue by pointtoken** [typeorm/typeorm#3347]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a valid connection string to a Mongo Atlas DB that I am trying to use with TypeORM. I know the connection string works because I have used it from Python and from the Mongo shell. But it doesn't work from typeorm. I have tried both the **mongodb://** and **mongo+srv** synax. Not sure how to debug or figure this one out. Here is the error:

```
(node:19257) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
{ MongoNetworkError: connection 5 to cluster0-XXXX.mongodb.net:27017 closed
    at Socket.<anonymous> (/home/administrator/Source/Repos/emoon-relayer/node_modules/mongodb-core/lib/connection/connection.js:276:9)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:611:12)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
```

**Comment by vlapo** [comment]
Did you try add `useNewUrlParser: true` to your connection config?

**Comment by rustamwin** [comment]
Try add `dbName: <your database name>` to your connection options

**Comment by pointtoken** [comment]
Thanks guys -- but how do I actually pass parameters when MongoDB  connects. The JSON object passed on createConnection in typeORM wraps when MongoDB calls connect.

**Comment by vlapo** [comment]
After few tries I have two valid configurations for typeorm and mongo atlas:
```typescript
const connection = await createConnection({
            type: "mongodb",
            useNewUrlParser: true,
            url: "mongodb://admin:password@testcluster0-shard-00-00-1cmyo.mongodb.net:27017,testcluster0-shard-00-01-1cmyo.mongodb.net:27017,testcluster0-shard-00-02-1cmyo.mongodb.net:27017/test?ssl=true&replicaSet=TestCluster0-shard-0&authSource=admin&retryWrites=true",
            ssl: true,
            authSource: "admin",
            replicaSet: "TestCluster0-shard-0"
        });
```
and second one
```typescript
const connection = await createConnection({
            type: "mongodb",
            url: "mongodb+srv://admin:admin@testcluster0-1cmyo.mongodb.net/test?retryWrites=true",
            ssl: true,
            authSource: "admin",
            replicaSet: "TestCluster0-shard-0"
        });
```
But I think @pointtoken is right. Calling mongodb connect method with undefined option properties overwrites settings from url.

**Comment by pointtoken** [comment]
@vlapo  nice that worked!

**Comment by vlapo** [comment]
Still I think we should not pass all mongo options to mongo client with undefined values. Our current implementation will overwrite all options from url with `undefined`.

**Comment by vincedgy** [comment]
I know it's a closed case... 
but since I'm using dotenv and MongoDB Atlas this is what I found :

.env

```properties
TYPEORM_CONNECTION = mongodb
TYPEORM_URL = mongodb+srv://admin:password@cluster-XXXXX-pSDig.mongodb.net/graphql-ts?retryWrites=true&w=majority
TYPEORM_DATABASE = graphql-ts

TYPEORM_ENTITIES = src/entity/*.ts
TYPEORM_MIGRATIONS = src/migration/**/*.ts
TYPEORM_ENTITIES_DIR = src/entity
TYPEORM_SUBSCRIBERS_DIR = src/subscriber
TYPEORM_MIGRATIONS_DIR = src/migration

TYPEORM_DRIVER_EXTRA = '{"useUnifiedTopology":true}'
```

**Comment by oliviermattei** [comment]
Hello,

I have the same problem with a free Mongo Atlas cluster. 
```
type: 'mongodb',
      url:
        'mongodb+srv://***:***@test-tqajp.gcp.mongodb.net/test?retryWrites=true&w=majority',
      entities: ['./**/*.type.ts'],
      synchronize: true,
      useNewUrlParser: false,
      logging: true,
```
`[TypeOrmModule] Unable to connect to the database. Retrying (1)... +2006ms`

I'm using nestjs, but with mongoose all works fine. But i'd like using typeorm because i need multiple connections with other kind of databases. I don't think it's a problem of @nestjs/typeorm package.

**Comment by Philip-Nunoo** [comment]
@oliviermattei facing the same issue did you find a solution to this.

**Comment by Adondriel** [comment]
Updating this ticket with a code block that got mine to work, using the free cluster.
`
  const connection = await createConnection({
    type: 'mongodb',
    url: 'mongodb+srv://<user>:<pass>@test-cluster.cgl5c.mongodb.net/<db name>',
    w: 'majority',
    ssl: true,
    authSource: 'admin',
    entities: ['dist/**/*.entity.js'],
  });
`

**Comment by Funnelll** [comment]
I had the same issue. Passing the MongoDB Atlas as URL (mongodb://) lead to the  
`MongoNetworkError: connection X to cluster0-XXXX.mongodb.net:27017 closed` error. Passing the host, port, username, password, database, authSource, and ssl worked. After looking more into it, it seems that only one host is picked up (and it seems to me the parameters are ignored as well) from the URL.

Since I didn't want to change my environment variable in my environment, I fixed this by creating a method that parses the URL and constructs the options correctly. Here are the details of the implementation in case it becomes handy for anybody else.


```
private static async connectToDataBase() {

        const options = {
            useNewUrlParser: true,
            bufferMaxEntries: 0,
            connectTimeoutMS: 60000,
            useUnifiedTopology: true,
            serverSelectionTimeoutMS: 60000
        };

        const connectionOptions:any = await getConnectionOptions();
        Object.assign(connectionOptions, options);
        Object.assign(connectionOptions, Server.extractDriverOptions(Environment.databaseUrl));

        try{
            await createConnection();
            logger.info(`Connected to database ${connectionOptions.host}`, Server);
        } catch (error) {
            logger.error(`Failed to connect to database ${connectionOptions.host}: ${error}: ${error.stack}`, Server);
        }
}
private static extractDriverOptions (url) {
        const type = url.split(":")[0];
        const firstSlashes = url.indexOf("//");
        const preBase = url.substr(firstSlashes + 2);
        const secondSlash = preBase.indexOf("/");
        const base = (secondSlash !== -1) ? preBase.substr(0, secondSlash) : preBase;
        let afterBase = (secondSlash !== -1) ? preBase.substr(secondSlash + 1) : undefined;
        // remove mongodb query params
        if (afterBase && afterBase.indexOf("?") !== -1) {
            afterBase = afterBase.substr(0, afterBase.indexOf("?"));
        }
        const lastAtSign = base.lastIndexOf("@");
        const usernameAndPassword = base.substr(0, lastAtSign);
        const hostAndPort = base.substr(lastAtSign + 1);
        let username = usernameAndPassword;
        let password = "";
        const firstColon = usernameAndPassword.indexOf(":");
        if (firstColon !== -1) {
            username = usernameAndPassword.substr(0, firstColon);
            password = usernameAndPassword.substr(firstColon + 1);
        }
        const hostAndPortParts = hostAndPort.split(',');
        let part;
        let host;
        let port;
        for (let i=0; i<hostAndPortParts.length; i++) {
            if (i === 0) {
                part = hostAndPortParts[i].split(":");
                host = part[0];
                port= part[1];
            } else {
                host = host + "," + hostAndPortParts[i].split(":")[0];
            }
        }

        const driverOptions = {
            type: type,
            host: host,
            username: decodeURIComponent(username),
            password: decodeURIComponent(password),
            port: port ? parseInt(port) : undefined,
            database: afterBase || undefined
        };
        const properties = url.split('?')[1]?.split('&');
        let property;
        let value: string;
        for (let i=0; i<properties.length; i++) {
            property = properties[i].split('=')[0];
            value = properties[i].split('=')[1];
            if (value.toLowerCase().indexOf('true') > -1 || value.toLowerCase().indexOf('false') > -1) {
                driverOptions[property] = (value.toLowerCase().indexOf('true') > -1);
            } else {
                driverOptions[property] = value;
            }
        }

        return driverOptions;
 }
```
Here is what my ormconfig.json looks like:

```
{
  "type": "mongodb",
  "synchronize": false,
  "logging": false,
  "entities": [
    "build/entities/**/*.js"
  ],
  "cli": {
     "entitiesDir": "src/entity"
  }
}
```
I am using  "mongodb": "^3.6.3", "typeorm": "^0.2.29".

P.S. Please note that this implementation doesn't account for cases where the configuration has a parameter with a number value (but it is an easy fix to add if you are sending a parameter that has a numeric value in the URL).

**Comment by PierBusDev** [comment]
I am still getting this problem with typeorm 0.2.29.
None of the solutions posted above work right now

**Comment by aleccool213** [comment]
@PierBusDev is correct. MongoDB Atlas support is currently broken unless you specify the exact shard you want to connect to. Wasted a few hours on this :/ This issue should be re-opened with a fix or with some documentation.

**Comment by smasala** [comment]
Can confirm - using the shard worked 🤦

**Comment by smasala** [comment]
v0.2.30 fixes the issue. Can connect to an atlas cluster again. Thanks @pleerock!

**Comment by jrista** [comment]
Hmm. So, we seem to be in a catch-22. I upgraded to 0.2.30, but did not change my mongo connection string, which I REVERTED to a `mongo://` after upgrading to 0.2.29 before and having problems connecting to mongo. So my connection currently uses a STANDARD mongo connection string...

After upgrading to 0.2.30 a short while ago, our connection to mongo stopped working. It just would time out trying to connect. We updated numerous modules at once, and it took a bit of experimentation to figure out that it is the 0.2.30 version of TypeORM that is causing the problem.

So while we may have gained the ability to use `mongo+srv://` type connection strings, we seem to have LOST the ability to use `mongo://` type connection strings...

I would offer it is best if we can use both types of connection strings, as necessary, to connect TypeORM to various mongo databases.

**Comment by AmbassEugene** [comment]
So the below worked for me. I am using Nestjs

```
{
  "type": "mongodb",
  "url": "mongodb+srv://<user>:<password>@cluster0.somethingsomething.mongodb.net/<dbname>?retryWrites=true&w=majority",
  "useNewUrlParser": true,
  "synchronize": true,
  "logging": true,
  "useUnifiedTopology": true,
  "entities": ["dist/**/*.entity{.ts,.js}"]
}
```

**Comment by Drakoun** [comment]
Thank you @AmbassEugene, it worked for me.

**Comment by aequasi** [comment]
This doesn't seem to work anymore?
