### ISSUE TITLE
How do I use prepared statements in SQlite?

### ISSUE THREAD

**Issue by P0oOOOo0YA** [typeorm/typeorm#3349]
**Issue type:**
[*] question

**Database system/driver:**
[*] `sqlite`

**TypeORM version:**
[*] `latest`

This is how you can use prepared statements in `node-sqlite3`. 

```js
var sqlite3 = require('sqlite3')
var db = new sqlite3.Database('data.db');

db.serialize(function() {
    var stmt = db.prepare("SELECT * FROM table WHERE "+KEY_FIELD_NAME+"=(?)");
    stmt.get(fieldName,function(err,row){
        var callbckObj = null;

        if(row != undefined){
            callbckObj = new callbckObj(row);
        }
        callback(err, callbckObj);      
    });
    stmt.finalize();
});
db.close();
```
How we can do the same in `TypeORM`?

**Comment by pleerock** [comment]
TypeORM doesn't have additional api for prepared statements. You need to use underlying driver, e.g. `node-sqlite3` itself. You can use it via `connection.driver`
