### ISSUE TITLE
All caps table names aren't taking inserts

### ISSUE THREAD

**Issue by kalebhermes** [typeorm/typeorm#335]
I have both an Oracle and mysql table who's name is all caps, and inserts aren't committing data into my database. When the table starts with one capital letter, or is all lowercase, the inserts happen fine. 

My tables name is PHOTOZ. I've enabled logging and noticed that the table name is being represented as 'p_h_o_t_o_z' rather than PHOTOZ. This created a new table in my mysql database called 'p_h_o_t_o_z'. 

Am I missing something, or is there something I can do to correct this? Changing the name of the table isn't feasible, as I'm attempting to use this for work.

**Comment by pleerock** [comment]
You can set custom entity name, e.g. `@Entity("PHOTOZ") export class Photo {` to solve your issue.

**Comment by kalebhermes** [comment]
Ah beautiful! I forgot to mention that I'm using bare JS, is there a way to do what your suggesting if I go that route? 

Assuming this is what my Entity looks like currently

`module.exports = {
    name: "PHOTOZ",
    columns: {
        id: {
            primary: true,
            type: "int",
            generated: true
        },
        name: {
            type: "string"
        ...
    }
};`

**Comment by pleerock** [comment]
```typescript
module.exports = {
    name: "Photo",
    table: {
         name: "PHOTOZ"
    }
    columns: {
        id: {
            primary: true,
            type: "int",
            generated: true
        },
        name: {
            type: "string"
        }
};
```

**Comment by kalebhermes** [comment]
This is great. Thank you for your quick response!
