### ISSUE TITLE
Sync dropping TEXT column

### ISSUE THREAD

**Issue by Ionaru** [typeorm/typeorm#3352]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest` -> `0.2.10`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
A TypeORM synchonization will drop and recreate columns with type `TEXT`, **destroying** all data that was in those columns.

Gist to reproduce behaviour:
https://gist.github.com/Ionaru/5ac6f41759dc72230c266bc8ee1bf593

Running the script above once will result in the following SQL in all subsequent runs.

```sql
START TRANSACTION
SELECT DATABASE() AS `db_name`
SELECT * FROM `INFORMATION_SCHEMA`.`TABLES` WHERE (`TABLE_SCHEMA` = 'web_text_test' AND `TABLE_NAME` = 'bar')
SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE (`TABLE_SCHEMA` = 'web_text_test' AND `TABLE_NAME` = 'bar')
SELECT * FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` WHERE `CONSTRAINT_NAME` = 'PRIMARY' AND ((`TABLE_SCHEMA` = 'web_text_test' AND `TABLE_NAME` = 'bar'))
SELECT `SCHEMA_NAME`, `DEFAULT_CHARACTER_SET_NAME` as `CHARSET`, `DEFAULT_COLLATION_NAME` AS `COLLATION` FROM `INFORMATION_SCHEMA`.`SCHEMATA`
SELECT `s`.* FROM `INFORMATION_SCHEMA`.`STATISTICS` `s` LEFT JOIN `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` `rc` ON `s`.`INDEX_NAME` = `rc`.`CONSTRAINT_NAME` WHERE ((`s`.`TABLE_SCHEMA` = 'web_text_test' AND `s`.`TABLE_NAME` = 'bar')) AND `s`.`INDEX_NAME` != 'PRIMARY' AND `rc`.`CONSTRAINT_NAME` IS NULL
SELECT `kcu`.`TABLE_SCHEMA`, `kcu`.`TABLE_NAME`, `kcu`.`CONSTRAINT_NAME`, `kcu`.`COLUMN_NAME`, `kcu`.`REFERENCED_TABLE_SCHEMA`, `kcu`.`REFERENCED_TABLE_NAME`, `kcu`.`REFERENCED_COLUMN_NAME`, `rc`.`DELETE_RULE` `ON_DELETE`, `rc`.`UPDATE_RULE` `ON_UPDATE` FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` `kcu` INNER JOIN `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` `rc` ON `rc`.`constraint_name` = `kcu`.`constraint_name` WHERE (`kcu`.`TABLE_SCHEMA` = 'web_text_test' AND `kcu`.`TABLE_NAME` = 'bar')
ALTER TABLE `bar` DROP COLUMN `someText`
ALTER TABLE `bar` ADD `someText` text NOT NULL
COMMIT
```

**Version information:**
* Node `10.15.0`
* MySQL `5.7.20`

```json
"dependencies": {
  "mysql": "^2.16.0",
  "reflect-metadata": "^0.1.12",
  "ts-node": "^7.0.1",
  "typeorm": "^0.2.10",
  "typescript": "^3.2.2"
}
```

**Comment by Ionaru** [comment]
This problem seems to be introduced with version `0.2.10`, it did not occur in `0.2.9` or earlier.

**Comment by pleerock** [comment]
This sounds critical. Thanks for the report. I reproduced this error, trying to find what change caused this.

**Comment by pleerock** [comment]
okay, so #3310 broke it

**Comment by pleerock** [comment]
according to the code when you change `withLengthColumnTypes` you also need to update `dataTypeDefaults` for sync to work properly. Not sure why exactly you added those types into withLengthColumnTypes, but I'll revert them for now.

**Comment by pleerock** [comment]
published a fix and released 0.2.11

**Comment by vlapo** [comment]
I am really sorry folks. Did not check `withLengthColumnTypes` and `dataTypeDefaults` properly. Thnx @pleerock for so fast hotfix.

**Comment by pleerock** [comment]
@vlapo that's fine, schema sync is a complex part, we just need to be a bit more careful when we change it.

**Comment by Ionaru** [comment]
Can confirm issue is fixed in `0.2.11` :+1:

**Comment by MikeDabrowski** [comment]
Sorry to reopen this, but I have similar problem for varchar and text, probably more types. Don't really know whats causing this.

During restart I got this
```
query: ALTER TABLE `user` DROP COLUMN `token`
query: ALTER TABLE `user` ADD `token` text NOT NULL
```

And boom, all tokens gone. I tried different lengths but I'm lost, don't know what to try next.
Im using nest.js and my Entity is as follows:
```
@Entity()
export class User {
  @PrimaryGeneratedColumn({ type: 'int' })
  userId: number;
  @Column({ nullable: false, length: 255, type: 'varchar' })
  password: string;
  @Column({ type: 'text' })
  token: string;
  @Column({ unique: true, nullable: false, length: 255, type: 'varchar' })
  login: string;
}
```

**Comment by dmlo** [comment]
This is happening for me as well, 0.2.18.

`
@Entity()
export class Prototype {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    // unique: false,
    nullable: true,
  })
  description: string;

}
`

**Comment by alirezavafaee** [comment]
This is happening for me too.
"typeorm": "^0.2.41"

**Comment by andkom** [comment]
same for me: 0.2.41

**Comment by Ionaru** [comment]
@alirezavafaee @andkom It's best to open a new ticket and reference this one. It's unlikely that comments on a closed ticket will get seen.

**Comment by auragit** [comment]
same here 0.2.38

**Comment by ananvodo** [comment]
Same is happening for the laster typeorm version 0.3.17

**Comment by gezerramos** [comment]
the same with me in the version 0.3.20
