### ISSUE TITLE
Error on cascade inserting

### ISSUE THREAD

**Issue by 19majkel94** [typeorm/typeorm#336]
I got this error when trying to cascade insert:
```
executing query: START TRANSACTION
executing query: INSERT INTO `chart`(`type`, `sortingOrder`) VALUES (?,?) -- PARAMETERS: ["normal","performance"]
executing query: INSERT INTO `chart_row`(`isDistinctive`, `result`) VALUES (?,?) -- PARAMETERS: [1,3]
executing query: INSERT INTO `chart_row`(`isDistinctive`, `result`) VALUES (?,?) -- PARAMETERS: [0,1]
executing query: INSERT INTO `chart_row`(`isDistinctive`, `result`) VALUES (?,?) -- PARAMETERS: [0,2]
query failed: INSERT INTO `chart_row`(`isDistinctive`, `result`) VALUES (?,?) -- PARAMETERS: [1,3]
error during executing query:Error: ER_NO_DEFAULT_FOR_FIELD: Field 'chart' doesn't have a default value
executing query: ROLLBACK
query failed: INSERT INTO `chart_row`(`isDistinctive`, `result`) VALUES (?,?) -- PARAMETERS: [0,1]
error during executing query:Error: ER_NO_DEFAULT_FOR_FIELD: Field 'chart' doesn't have a default value
```
Entities:
```typescript
@Entity()
export class ChartRow {
    @PrimaryGeneratedColumn()
    public readonly id: number;

    @ManyToOne(_type => Chart, chart => chart.rows, { nullable: false, onDelete: "CASCADE" })
    public chart: Chart;

    @ManyToOne(_type => Result, { nullable: false, onDelete: "CASCADE" })
    public result: Result;

    @Column({ default: false })
    public isDistinctive: boolean = false;
}

@Entity()
export class Chart {
    @PrimaryGeneratedColumn()
    public readonly id: number;

    @Column("string", { default: "normal" })
    public type: Chart.Types = "normal";

    @Column("string", { default: "performance" })
    public sortingOrder: Chart.SortingOrders = "performance";

    @OneToMany(_type => ChartRow, row => row.chart, { cascadeInsert: true, cascadeUpdate: true })
    public rows: ChartRow[] = [];
}
```
`chart` column is not nullable in DB (as set in decorator), so no default value is a problem
I know that the old persistence mechanism required nullable field due to inverted inserting order but now the orded is correct (chart is added) but the `chart_id` in rows is not inserted with data in one statement.

**Comment by 19majkel94** [comment]
Calling @pleerock - are you aware of this problem? 
I have another project with another cascade inserting bug. Here are parts of entities
```typescript
export class PlaylistItem {
    @Column("int")
    public order: number;

    @ManyToOne(_type => Playlist, playlist => playlist.items, { nullable: true })
    public playlist: Playlist;
}

export class Playlist {
    @ManyToOne(_type => User, { nullable: false })
    public user: User;

    @OneToMany(_type => PlaylistItem, playlistItem => playlistItem.playlist, { cascadeInsert: true, cascadeUpdate: true })
    public items: PlaylistItem[] = [];
}
```
And cascade inserting by this way is not working (partial code):
```typescript
const playlistItems = items.map(item =>
    this.playlistItemRepository.create({
        order: item.order,
    });
);

const playlist = this.playlistRepository.create({
    items: playlistItems,
    user,
});

await this.playlistRepository.persist(playlist);
```

The only awkward solution is to create a `Playlist`, persist it in database, then create `PlaylistItem`s as assign playlist object to each of them and then again persist playlist in db.

Cascade inserting worked very well on `0.0.2-alpha.70` but on `0.0.9` and `0.0.11` it fails 😢

**Comment by pleerock** [comment]
there are quite lot of issues with cascades... cascades is the most complex part of orm. It needs refactoring and loooot of time and redesign to fix all those issues. Still hoping if someone help me there.

**Comment by 19majkel94** [comment]
I know there might be issues with cascades but it worked in older version and now it stops working 😞 So you started refactoring by removing 80% of the code and you need some time to start from scratch?
It's simple cascade insert, not complicated delete case, so the sample from docs site now won't work too?

**Comment by pleerock** [comment]
simply cases should work. Looks like your problem is usage of `nullable: false`. Don't do that with relations which has cascades because orm cant determine order of inserted entities which can be recursive.

**Comment by 19majkel94** [comment]
I had this problem before, you told that the cascade option first insert records without foreign keys and then update it when the related record is inserted. So I checked that and now I have `nullable: true` like you can see in the second snippet - now I don't have sql error but the foreign key is just `NULL`, there's no `UPDATE` query after insert like in earlier TypeORM versions 😞

**Comment by 19majkel94** [comment]
Closing since it works for now in 0.1.1 😉

**Comment by pleerock** [comment]
😓
