### ISSUE TITLE
setting COMMENT on columns and tables (PostgreSQL)

### ISSUE THREAD

**Issue by ulo** [typeorm/typeorm#3360]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Feature request:**
When I define my entities I would like to be able to set a COMMENT to the database object. From looking at the source code this seems to be currently possible only for **MySQL** and not for **PostgreSQL**:
```ts
@Entity()
export class User {
  ...
  @Column({comment: 'The age in years.'})  // <--
  age: number
}
```

Using PostgreSQL one can also set a COMMENT on the **table** itself, which is not yet supported by TypeORM at all, but could look like this:
```ts
@Entity({comment: 'A user profile in the wep app.'})  // <--
export class User {
  ...
  @Column({comment: 'The age in years.'})
  age: number
}
```

I am asking for this feature as I am using the awesome PostGraphile tool, which heavily relies on COMMENTs for its configuration, and it would be really useful to do this by using TypeORM entity decorators!!

Many thanks,
Ulrich

**Comment by vlapo** [comment]
This should be fixed also for mysql. And investigate comments in all supported databases and implemented it too.

**Comment by Diluka** [comment]
Please save comment in meta first. It helps generating API docs.

**Comment by DavidTheProgrammer** [comment]
Is anybody currently working on this?

**Comment by imagine10255** [comment]
+1

**Comment by auerbachb** [comment]
+1

**Comment by imnotjames** [comment]
Code in #6902 is ready to go, has tests, should be good to merge.

**Comment by AlainBartmanDilaw** [comment]
> This should be fixed also for mysql. And investigate comments in all supported databases and implemented it too.

Has this feature been implemented for mysql databases ?

**Comment by derushio** [comment]
```ts
@Entity({comment: 'A user profile in the wep app.'})
```

Is this option not implemented?

**Comment by nawaz-pasha** [comment]
> ```ts
> @Entity({comment: 'A user profile in the wep app.'})
> export class User {
> ...
> }
> ```
> 
> Is this option not implemented?

Don't think so.

Looks like as part of the PR #6092, only column comments support was added. Is there a different issue for table comments support?

**Comment by manoger** [comment]
I'm facing the same issue. Entities aren't able to have meta-descriptions.

**Comment by gabbrieu** [comment]
Any news to table comments?

**Comment by block2k** [comment]
table comments are not implement
