### ISSUE TITLE
Isolation Level in `transaction()` from `Connection`

### ISSUE THREAD

**Issue by victorschinaider** [typeorm/typeorm#3363]
**Issue type:**

[x] question
[ ] bug report
[x] feature request (possible?)
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In documentation we have a parameter to define isolation level from `getManager()`:
 
```typescript
await getManager().transaction("SERIALIZABLE", transactionalEntityManager => {

});
```

But, if we try to do the same thing from `Connection` class, there isn't such definition, only the callback: 

```typescript
transaction(runInTransaction: (entityManager: EntityManager) => Promise<any>): Promise<any>;
```

I'm using Typeorm in a NestJs, so `Connection` class comes from Injection. If i use `getManager()`, it'll get the same "session" in Connection class injected?

**Comment by victorschinaider** [comment]
And is there a way to globally define the isolation? It could be possible?

**Comment by pleerock** [comment]
> And is there a way to globally define the isolation? It could be possible?

yes it should be possible, refer to your database documentation.

> transaction(runInTransaction: (entityManager: EntityManager) => Promise<any>): Promise<any>;

looks like guy who implemented this feature missed this signature. Feel free to update it!
