### ISSUE TITLE
Querybuilder: Join many-to-many relation and filter results

### ISSUE THREAD

**Issue by cvh23** [typeorm/typeorm#3369]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.9`

**Steps to reproduce or a small repository showing the problem:**

I have 2 tables: `users` and `groups` and they are connected via many-to-many relation. So a user can belong to multiple groups and groups can be related to multiple users. Now I want to query (select) all users belonging to a list of groups BUT if they match all of their groups should be included in the result.

I found no hint how to implement that with TypeORM's query builder. In raw SQL I would propably do it with sub-selects. Now, in this case, I didnt want to add all the user groups with additional querys and attach that data via Typescript, because that has propably poor performance with large datasets.

Minimal example (includes all matching users, but only matching groups -> should include all groups of a matching user):

```ts
let qb = this.repository.createQueryBuilder('user');

qb = qb.leftJoinAndSelect('user.groups', 'userGroups');

const groupIds = [1, 5];
qb.where('userGroups.id IN (:...groupIds)', { groupIds });

qb.getMany();

```

**Comment by cvh23** [comment]
This is how I would solve it in pure SQL:

```sql
SELECT users.last_name, users.first_name, groups.name
FROM users_groups_map
  INNER JOIN users
    ON users_groups_map.user_id = users.id AND users_groups_map.group_id IN (1, 5)
  LEFT JOIN users_groups_map users_groups_map2
    ON users.id = users_groups_map2.contacts_id
  INNER JOIN groups
    ON groups.id = users_groups_map2.group_id
```

**Comment by cvh23** [comment]
This is my solution now, it's working. Is there a more elegant alternative?

```ts
const groupIds = [1, 5];

const qb = this.repository
  .createQueryBuilder('user')
  .innerJoin(qb2 => {
    return qb2
      .select('user.id', 'id')
      .from(User, 'user')
      .innerJoin('user.groups', 'userGroups')
      .where('userGroups.id IN (:...groupIds)', { groupIds });
    }, 'userWithCertainGroups', 'user.id = "userWithCertainGroups".id')
  .leftJoinAndSelect('user.groups', 'userGroups');

qb.getMany();
```

**Comment by pleerock** [comment]
You should ask yourself how you would do this query using joins instead of subselects. You need something like this:

```ts
const qb = this.repository
  .createQueryBuilder('user')
  .innerJoin('user.groups', 'userGroup', 'userGroup.id IN (:...groupIds)', { groupIds });
```

**Comment by willyguevara** [comment]
> You should ask yourself how you would do this query using joins instead of subselects. You need something like this:
> 
> ```ts
> const qb = this.repository
>   .createQueryBuilder('user')
>   .innerJoin('user.groups', 'userGroup', 'userGroup.id IN (:...groupIds)', { groupIds });
> ```

Got problems with the parameters order when adding the `qb.where()` it put the `groupIds` at the end of the array.

**Comment by Chetan11-dev** [comment]
For those who want to select many to many relations with a relationship having a list of properties AND also the other associated relations (which is the original question)
Below query Works. It gets all the products having a list of categories and also other categories associated with the following product.
```
this.productsRepository.createQueryBuilder('products').innerJoinAndSelect('products.categories',
        'productsCategories', 'productsCategories.name IN (:...categs)'
        , { categs: ['Fruit','Vegetable'] })
        .leftJoinAndSelect('products.categories', 'productsCategoriess')
        .getMany()
```



> This is my solution now, it's working. Is there a more elegant alternative?
> 
> ```ts
> const groupIds = [1, 5];
> 
> const qb = this.repository
>   .createQueryBuilder('user')
>   .innerJoin(qb2 => {
>     return qb2
>       .select('user.id', 'id')
>       .from(User, 'user')
>       .innerJoin('user.groups', 'userGroups')
>       .where('userGroups.id IN (:...groupIds)', { groupIds });
>     }, 'userWithCertainGroups', 'user.id = "userWithCertainGroups".id')
>   .leftJoinAndSelect('user.groups', 'userGroups');
> 
> qb.getMany();
> ```

**Comment by aadrianras** [comment]
I've followed all the suggestions on this page, and I was able to complete a complex query. I'm going to leave it here; it may be helpful to see a full example of the implementation. Good luck!

`const { skip = 0, take = 20, select = undefined, artStyles = [], bodyParts = [], states = [], search } = queryParams;

    try {
      const queryBuilder = this.tattooRepository
        .createQueryBuilder('tattoo')
        .leftJoinAndSelect('tattoo.artist', 'artist')
        .leftJoinAndSelect('artist.user', 'user')
        .skip(skip)
        .take(take);

      if (search) {
        queryBuilder.where(
          new Brackets((qb) => {
            qb.where('tattoo.description ILIKE :search', { search: `%${search}%` });
            qb.orWhere('user.nickname ILIKE :search', { search: `%${search}%` });
            qb.orWhere('user.name ILIKE :search', { search: `%${search}%` });
            qb.orWhere('user.lastname ILIKE :search', { search: `%${search}%` });
          }),
        );
      }

      if (states.length > 0) {
        queryBuilder.andWhere('user.stateId IN (:...states)', { states });
      }

      if (artStyles.length > 0) {
        queryBuilder.innerJoin('tattoo.artStyles', 'artStyles', 'artStyles.id IN (:...artStyles)', {
          artStyles: artStyles,
        });
      }

      if (bodyParts.length > 0) {
        queryBuilder.innerJoin('tattoo.bodyParts', 'bodyParts', 'bodyParts.id IN (:...bodyParts)', {
          bodyParts: bodyParts,
        });
      }

      if (select) {
        queryBuilder.select(select);
      }

      const tattoos = await queryBuilder.getMany();

      return {
        data: tattoos.map((tattoo) => instanceToPlain(tattoo)),
        total: tattoos.length,
        skip,
        take,
      };
    } catch (error) {
      console.log(error)
    }`
