### ISSUE TITLE
Where condition affects relation in querybuilder

### ISSUE THREAD

**Issue by univerze** [typeorm/typeorm#3377]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hi!
This may be more of a mysql question but I couldn't work out what would be the solution for this.
I have a query which should select all workspaces where the current user is a member but also return all members for that workspace. I have 3 tables:
users: id, name
workspaces: id, name
workspaces_members_users: workspacesId, usersId
My query is code is
```ts
Workspace.createQueryBuilder('workspace')
.leftJoinAndSelect('workspace.members', 'members', 'members.deletedAt IS NULL')
.where({ deletedAt: null })
.andWhere('members.id = :userId', { userId })
.select(['workspace.name', 'members.name'])
.getMany();
```
The produced query is
SELECT `workspace`.`name` AS `workspace_name`, `workspace`.`id` AS `workspace_id`, `members`.`name` AS `members_name`, `members`.`id` AS `members_id` FROM `workspaces` `workspace` LEFT JOIN `workspaces_members_users` `workspace_members` ON `workspace_members`.`workspacesId`=`workspace`.`id` LEFT JOIN `users` `members` ON `members`.`id`=`workspace_members`.`usersId` AND (`members`.`deletedAt` IS NULL) WHERE `workspace`.`deletedAt` IS NULL AND `members`.`id` IN (?) -- PARAMETERS: [["de8d0e55-d68c-4d31-bad0-55013aab61cd"]]

This returns all the workspaces where I am a member but also returns only one user relation.

I would like to get all workspaces where I am a member and all members of that workspace.

Should this be a subquery or an other left join to get all the members and not just one?

Thanks in advance!

**Comment by pleerock** [comment]
this isn't a good place for such questions :) First, you need to figure out what SQL you need to build, second you build this SQL query using typeorm's QueryBuilder. You shall ask about particular SQL in some forums or stackoverflow for example.
