### ISSUE TITLE
How to query relation table different set ?

### ISSUE THREAD

**Issue by zerox12311** [typeorm/typeorm#3378]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Sorry... I don't know how to describe this question in title better..

I have two table
classroom  1---*  shcedule, relation is one to many

## classroom

 id | className 
----|-----------
 1  | A         
 2  | B         
 3  | C         
 4  | D

## schedule

| id 	| curTime 	| classRoomId 	|
|----	|---------	|-------------	|
| 1  	| 101     	| 1           	|
| 2  	| 103     	| 1           	|
| 3  	| 104     	| 1           	|
| 4  	| 102     	| 3           	|
| 5  	| 202     	| 2           	|

curTime is mean day + section
101 is monday's first section

Now I want to query the classroom is free time in curTime array like this
For example:
I have a curTime array [102,103,201]
I want to find the classroom in this array time is free (not in schedule), so in this case I want to query out classroom id 2 and 4 because id 2 and 4 in schedule had no curTime in [102,103,201]

Please help~~
My algorithm now is query all classroom in to array, then query all shedule curTime in [102,103,201] and find out the classRoomId to splice it, but I think it's so stupid. Thanks!!!

**Comment by vlapo** [comment]
Hi @zerox12311, 

I think this question is pretty simple. You have to use query builder with left join.

```typescript
await connection.getRepository(ClassRoom).createQueryBuilder("classroom")
            .select()
            .leftJoinAndSelect(Schedule, "schedule", "schedule.classRoomId = classroom.id AND schedule.curTime IN (:...currTimes)", { currTimes: [102, 103, 201] })
            .where("schedule.id IS NULL")
            .getMany();
```

**Comment by zerox12311** [comment]
@vlapo thank you!
I will try it tomorrow!!
