### ISSUE TITLE
The semantics of the query is ambiguous, when use JoinColumn.

### ISSUE THREAD

**Issue by ascoders** [typeorm/typeorm#338]
`JoinColumn` decorator helped a lot when use join query, but think about the following without join query:

Table `article` set `ManyToOne` linked to table `user`, we can query the user is very convenient to get the corresponding article entity.

But if i write like this:

```typescript
this.articleRepository.createQueryBuilder('article')
  .where('article.user=:userId', { id: Number(req.session['userId']) }) // wow!
```

We know that the user entity is stored with number, it's userId, but we wrote a confusing code `article.user=:userId`!

Is there a better way? How to think about the side effects?

**Comment by 19majkel94** [comment]
I think you have to create your own [naming strategy](https://github.com/typeorm/typeorm/blob/master/src/naming-strategy/DefaultNamingStrategy.ts) where relations will have `_id`  or `Id` suffix.

So then when you have `Article.prototype.user` property, you can create query `.where('article.userId=:userId', ...` which should be convinient (enough for me) :wink:

**Comment by ascoders** [comment]
May be entity conversion to id is the biggest problem.

**Comment by pleerock** [comment]
As I understood problem with `'article.user=:userId'` is that you don't like that "user" object is compared to "user id"? 

Personally I don't find anything bad in it. Also I can't imagine any alternative to this approach. What are you suggesting?

**Comment by ascoders** [comment]
I don't have any better suggestions, but this real kind of design is odd in this situation.

**Comment by pleerock** [comment]
I don't think there are alternative for the current design at the moment, so I'll close this issue.
