### ISSUE TITLE
manipulate relations without query

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#3383]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

### Is there a way to do like this...

```ts
photo.addRelatons("albums", ...ids); // put photo into several albums
album.removeRelations("photos", ...ids); // remove some photos from album
```
To add or remove an entity from the relation without query the whole relationship is easier, faster and more atomic.

**Comment by pleerock** [comment]
you can use [relational query builder](http://typeorm.io/#/relational-query-builder).

**Comment by Diluka** [comment]
I see. thx. I thought `QueryBuilder` is just for query not manipulation.
