### ISSUE TITLE
Oracledb returns Buffer as default for BLOB columns since typeorm 0.2.0. Is it correct behavior ?

### ISSUE THREAD

**Issue by kubisG** [typeorm/typeorm#3384]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] since 0.2.0 - latest
**Steps to reproduce or a small repository showing the problem:**

Hi everyone,

Introduction
- At first I need to meantion I'm using oracledb directly for fetch & insert BLOBs. Reason is Lob streaming.

Problem
- fetch, select BLOB column via oracledb returns Buffer as default

Investigation
- I just upgrade version of typeorm from 0.1.18 to latest. Everything looks good until I noticed oracledb ruturns instance of Buffer instead of Lob instance when fetching BLOB column. After some investigation I found out that "behaviour of oracledb" has changed (has been affected) since typeorm version 0.2.0.
- tested with various oracledb version - no effect

Expected (worked until typeorm version 0.2.0)
- fetch, select BLOB column via oracledb returns Lob as default

What oracledb documentation says
- fetch BLOB column returns Lob instance as DEFAULT 
- if anybody needs to return Buffer for Blob or String for Clob, must be specified
- Lob has to be used for large files (which is exactly my case) 

Does anybody notice same behaviour ? 
Is it bug or it's a feature which should be configured somehow ? 

Thanks a lot for any response

K.
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by kubisG** [comment]
Solved

-  it seems that typeorm (from version 0.2.0) set oracledb fetch strategy (globaly) to oracledb.fetchAsBuffer = [ oracledb.BLOB ];
- this should be override "localy" by setting fetchInfo object to
{ fetchInfo: { COLUMN_NAME: { type: oracledb.DEFAULT}}},

Oracledb documentation 
- 4.2.6.3.4 fetchInfo
- Using oracledb.DEFAULT overrides any global mapping given by fetchAsString or fetchAsBuffer. The column data is returned in native format.

**Comment by kordeviant** [comment]
please don't change default behavior of oracledb driver.
