### ISSUE TITLE
Querying MongoDB using ObjectId

### ISSUE THREAD

**Issue by ShadabFaiz** [typeorm/typeorm#3387]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `~0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
These 2 my my Entity.
``` typescript
import { Column, Entity, ObjectID, ObjectIdColumn, OneToOne } from 'typeorm';

import { BaseEntity } from '../BaseEntity';
import { UserProfile } from './UserProfile';

@Entity()
export class User extends BaseEntity {
  @ObjectIdColumn()
  userId: ObjectID;

  @Column({ unique: true, type: 'varchar' })
  username: string;

  @Column({ unique: true, type: 'varchar' })
  emailId: string;

  @Column({ type: 'varchar' })
  credential: string;

  @OneToOne(type => UserProfile, { eager: true })
  userProfile: UserProfile;
}

import { Column, Entity, ObjectID, ObjectIdColumn } from 'typeorm';

import { BaseEntity } from '../BaseEntity';

@Entity()
export class UserProfile extends BaseEntity {
  @ObjectIdColumn()
  profileId: ObjectID;

  @Column()
  gender: string;

  @Column()
  age: number;
}
```
What is Desired?
Like it happens in RDBMS, i ant to create 2 different collections for each entity, so the are related by ObjectIdColumn(), so that i can retrieve them seperately later on.

Currently, when i save the User Object in the database, only User Collection is created and UserProfile is embedded in the user object instead of creating a seperate UserProfile collection.

``` typescript
{
        "_id" : ObjectId("5c34901c841f24686fc518ae"),
        "username" : "shadaab_2",
        "emailId" : "addsdaasdasd@gm.com",
        "credential" : "$2a$10$Jfrr7dPAnAI3ixBn7/.D2OJT7T9t56/tz75PBjatuSunLOY0RV72m",
        "userProfile" : {
                "gender" : "M",
                "age" : 44
        }
}
```
Also, Now when i try to retirve the user collection. i'm expecting it to contain the userProfile (because it is embedded in it.), but i dont get user profile.

``` typescript
return getMongoRepository(User)
      .findOne({ where: { _id } })
 // returns

    "userId": "5c34901c841f24686fc518ae",
    "username": "shadaab_2",
    "emailId": "addsdaasdasd@gm.com",
    "credential": "$2a$10$Jfrr7dPAnAI3ixBn7/.D2OJT7T9t56/tz75PBjatuSunLOY0RV72m"
```

When we cascade the userProfile like this,
``` typescript 
  @OneToOne(type => UserProfile, { eager: true, cascade: true })
  userProfile: UserProfile;
```
then, user_profile collection is being created but, still it also have is embedded in the user collection too.
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by rustamwin** [comment]
mongo driver does not support relations (for now), I think there is no problem with ObjectId
