### ISSUE TITLE
How to set poolSize for postgres driver?

### ISSUE THREAD

**Issue by wederer** [typeorm/typeorm#3388]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have found [this answer](https://stackoverflow.com/questions/10212796/node-postgres-setting-max-connection-pool-size) on Stackoverflow how to set the poolSize for node-postgres. How can I set it wit TypeORM?
@pleerock commented [here](https://github.com/typeorm/typeorm/issues/2441#issuecomment-402255173) that the `extra` argument can be used.

So like this?
```
{
  ...,
  "extra": { poolSize: 10 }
}
```

Thanks

**Comment by vlapo** [comment]
Typeorm will pass extra to node-postgres Pool. Config is here https://node-postgres.com/api/pool.

So you have to define extra as:
```
{
  ...,
  "extra": { max: 10 }
}
```

But I think we should add this options to `PostgresConnectionOptions` since we are using pooling every time.

**Comment by damianmigo** [comment]
According to the Pool class of the Postgres driver, both options (max or poolSize) should work:

```
class Pool extends EventEmitter {
  constructor (options, Client) {
    super()
    this.options = Object.assign({}, options)
    this.options.max = this.options.max || this.options.poolSize || 10
```

**Comment by wederer** [comment]
@damianmigo Thanks!

**Comment by pleerock** [comment]
Since most of drivers support connection pool, we should extract this option into top-level connection options and add docs to it.

**Comment by wederer** [comment]
@pleerock Should I open a seperate issue for your suggestion?

**Comment by jpollard-cs** [comment]
to save future travelers time - if you're wondering if the typeorm uses the pg `Pool` under the hood: it does indeed at least at the time of this writing

**Comment by emlynmac** [comment]
I arrived here because I need to do some performance tuning of a production instance. One of the things I don't see how to do currently is to get the number of connections active or waiting.
It would be really great to pull out the pool object to be available externally for logging purposes.

**Comment by goktugyil** [comment]
> Typeorm will pass extra to node-postgres Pool. Config is here https://node-postgres.com/api/pool.
> 
> So you have to define extra as:
> 
> ```
> {
>   ...,
>   "extra": { max: 10 }
> }
> ```
> 
> But I think we should add this options to `PostgresConnectionOptions` since we are using pooling every time.

inside ormconfig?

**Comment by jacobgoh101** [comment]
>   "extra": { max: 10 }

This works for controlling the connection pool size. But when my server has more than 10 concurrent queries, I need to add `connectionTimeoutMillis: 1000` as well. Otherwise, some TypeORM queries will never respond. 

```
  extra: {
    // based on  https://node-postgres.com/api/pool
    // max connection pool size
    max: 10,
    // connection timeout
    connectionTimeoutMillis: 1000,
  },
```

**Comment by beez-dev** [comment]
> According to the Pool class of the Postgres driver, both options (max or poolSize) should work:
> 
> ```
> class Pool extends EventEmitter {
>   constructor (options, Client) {
>     super()
>     this.options = Object.assign({}, options)
>     this.options.max = this.options.max || this.options.poolSize || 10
> ```

is there any tool to given a statistically verifiable output , if pooling is working as expected?

**Comment by anandrmedia** [comment]
There is a common `poolSize` property in `DataSourceOptions` that specifies the maximum number of active connections in the pool.

**Comment by albr74** [comment]
Hi guys.

I would like have more control on connection pool, but I couldn´t find more options about the pool. Please, can you help me about this?

For example:
1. Max connections: I think it is the parameter max cited previously.
2. Min connections: The minimum available connections when the application starts. It is important in applications with a high number of clients. When the application starts this number of connections are available initially. And if there are no interactions with the application this number of connection is kept opened all the time.
3. Increase connections: if min connections is consumed, new connections need to be created. This parameter sets how many new connections will be created.

Are there these parameters (2 and 3) in TypeORM?

Thanks :-)
