### ISSUE TITLE
Repo.FindByIds do not preserve item order?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [typeorm/typeorm#3390]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```js
const ids = [ 75, 185, 722]

console.log(await conn.getRepository(Product).findByIds(ids)); 
/**
 [
    {id:722, ...},
    {id:185, ...},
    {id:75, ...}
  ]


*/

```
Is this behavior by design? How to preserve the same order as input?
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
I dont think so this is typeorm by design problem. This method generate simple SQL and typeorm do not modify order of returned rows by default. 

You can define order with order option:
```typescript
await conn.getRepository(Product).findByIds(ids, { order: { id: "ASC" } })
```

**Comment by pulgamecanica** [comment]
> I dont think so this is typeorm by design problem. This method generate simple SQL and typeorm do not modify order of returned rows by default.
> 
> You can define order with order option:
> 
> ```ts
> await conn.getRepository(Product).findByIds(ids, { order: { id: "ASC" } })
> ```

My compiler doesn't agree....
![image](https://user-images.githubusercontent.com/28810331/213889807-48ff0205-f7dd-41e6-80d0-9151b07dce06.png)


![image](https://user-images.githubusercontent.com/28810331/213889818-6d47524c-44de-428b-b7c2-be4ef520c5f4.png)
