### ISSUE TITLE
How to get 'user_id' to 'userId'

### ISSUE THREAD

**Issue by StormKid** [typeorm/typeorm#3399]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**When I read table , I just find that it was named 'user_id' , but I want to get it's name 'userId', How can I do it?** 

```typescript
   export class User{
           @Colum()
           userId: string
   }
```

**table**
|user_id| .....
|es9238sdje| ....

**Comment by StormKid** [comment]
just like mybatis：
```xml
<setting name="mapUnderscoreToCamelCase" value="true"/>
```

**Comment by RobinCK** [comment]
maybe

```typescript
export class User{
       @Colum({name: 'userId'})
       userId: string
}
```

**Comment by StormKid** [comment]
@RobinCK 
![](https://user-images.githubusercontent.com/13798727/50956394-83f6a300-14f6-11e9-896c-7904ae0bc124.jpg)

**Comment by vlapo** [comment]
@StormKid Do you use custom naming strategy? Because by default typeorm is using property name as column name, or camel case.

```typescript
columnName(propertyName: string, customName: string, embeddedPrefixes: string[]): string { // todo: simplify
    if (embeddedPrefixes.length)
        return camelCase(embeddedPrefixes.join("_")) + (customName ? titleCase(customName) : titleCase(propertyName));

    return customName ? customName : propertyName;
}
```

**Comment by StormKid** [comment]
@vlapo I wish typeorm will have global setting to control it.

**Comment by vlapo** [comment]
There is possibility to define custom naming strategy. I think it is better than one option to switch camel case vs snake case.

**Comment by StormKid** [comment]
I think that both of them would be useful , I hope the global controller would be producted in this lib, Thanks a lot , this question can be closed

**Comment by coldpc** [comment]
How did you solve it？

**Comment by coldpc** [comment]
@StormKid I also want to solve this promble like mybatis( <setting name="mapUnderscoreToCamelCase" value="true"/>)? How did you solve it？

**Comment by StormKid** [comment]
Look at this code：
```
     @Column({ name: 'ask_title' })
      askTitle: string;
```

**mysql:**

![{G59UM)UQ(AXAWX@~H8I@HA](https://user-images.githubusercontent.com/13798727/55524745-f1167080-56c0-11e9-9b65-f870ce342a8b.png)


**result:**

![(}G$AG2IJ)XU )N@CJ90_PB](https://user-images.githubusercontent.com/13798727/55524784-17d4a700-56c1-11e9-930a-c17c7cc8f65d.png)


**so , You only spell it on every colum. Do not have any solution to make the global setting**

**Comment by StormKid** [comment]
@coldpc
