### ISSUE TITLE
Error during connection to the db:  { error: syntax error at or near ")"

### ISSUE THREAD

**Issue by paistipoikka** [typeorm/typeorm#34]
Hi,

I am trying to connect to postgres with the following code. To try and narrow things down I have pulled out all of my entities. 

```
let dbHost = process.env.DB_HOST || 'localhost'
        let dbPort = process.env.DB_PORT || 5432;
        let dbName = process.env.DB_NAME || 'TEST_DB';
        let dbUserName = process.env.DB_PASS || 'testuser';
        let dbPassword = process.env.DB_USER || 'testpw';

        const options: ConnectionOptions = {
            driver: {
                type: 'postgres', // specify driver type here.
                host: dbHost,
                port: dbPort,
                username: dbUserName,
                password: dbPassword,
                database: dbName
            },
            autoSchemaCreate: true,
            entities: []
            // entityDirectories: ['./server/model/**/{*.ts,*.js}'],
            // subscriberDirectories: ['./server/subscriber/**/{*.ts,*.js}']
        };

        createConnection(options).then(connection => {

            // at this point you are connected to the database, and you can
            // perform queries

        }).catch(error => console.log('Error during connection to the db: ', error));
```
The error I am receiving is:
```
Error during connection to the db:  { error: syntax error at or near ")"
    at Connection.parseE (/Users/jt/Documents/workspace/tester/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/Users/jt/Documents/workspace/tester/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/Users/jt/Documents/workspace/tester/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
  name: 'error',
  length: 84,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '380',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1081',
  routine: 'scanner_yyerror' }
```

Has this problem been encountered by anyone and is this an issue or a config problem? It looks like an issue as it appears that there is some sort of connection string problem. I may be wrong. 

Cheers

JT

**Comment by pleerock** [comment]
what node and typescript compiler versions are you using? Also try to add logging to your configuration, maybe you will have more verbose errors:

```typescript
 /// ...
    autoSchemaCreate: true,
    entities: []
    logging: {
        logQueries: true,
        logSchemaCreation: true
    },
```

**Comment by paistipoikka** [comment]
Ahhh....that's a bit more helpful.. :)

```
> node ./src/server.js; webpack-dev-server --inline --hot --progress --port 4200; tsc ./src/server.ts --watch

executing query: SELECT * FROM information_schema.tables WHERE table_catalog = 'TEST_DB' AND table_schema = 'public'
executing query: SELECT * FROM information_schema.columns WHERE table_catalog = 'TEST_DB' AND table_schema = 'public'
executing query: SELECT t.relname AS table_name, i.relname AS index_name, a.attname AS column_name 
                                FROM pg_class t, pg_class i, pg_index ix, pg_attribute a
                                WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid
                                AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' AND t.relname IN ()
                                ORDER BY t.relname, i.relname
executing query: SELECT table_name, constraint_name FROM information_schema.table_constraints WHERE table_catalog = 'TEST_DB' AND constraint_type = 'FOREIGN KEY'
executing query: SELECT * FROM information_schema.table_constraints WHERE table_catalog = 'TEST_DB' AND constraint_type = 'UNIQUE'
executing query: SELECT table_name, constraint_name FROM information_schema.table_constraints WHERE table_catalog = 'TEST_DB' AND constraint_type = 'PRIMARY KEY'
query failed: SELECT t.relname AS table_name, i.relname AS index_name, a.attname AS column_name 
                                FROM pg_class t, pg_class i, pg_index ix, pg_attribute a
                                WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid
                                AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' AND t.relname IN ()
                                ORDER BY t.relname, i.relname
Error during connection to the db:  { error: syntax error at or near ")"
    at Connection.parseE (/Users/jordan/Documents/workspace/tester/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/Users/jordan/Documents/workspace/tester/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/Users/jordan/Documents/workspace/tester/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
  name: 'error',
  length: 84,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '380',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1081',
  routine: 'scanner_yyerror' }


```

**Comment by paistipoikka** [comment]
Using postgres. The database is currently empty i.e. no tables.

**Comment by pleerock** [comment]
this looks like a bug, I'll fix it. But the problem is that there is no any entity. You need to create and specify at least one entity, and you'll not see this error.

**Comment by paistipoikka** [comment]
OK, added an entitity and that worked. :)

**Comment by zany49** [comment]
typeorm conf 

export const typeOrmConfig: TypeOrmModule = {
  type: databaseConfig.type,
  host: databaseConfig.host,
  port: databaseConfig.port,
  username: databaseConfig.username,
  password: databaseConfig.password,
  database: databaseConfig.database,
  synchronize: databaseConfig.synchronize,
  // URL: databaseConfig.URI,
  // conn: databaseConfig.conn,
//  ssl: true,
  extra: {
    ssl: {
      rejectUnauthorized: false
    }
  },
  // ssl : true,
  entities: [`${__dirname}/../../**/*.entity.{js,ts}`],
  // tls: {
  //   rejectUnauthorized: false,
  // },
  options: { encrypt: false },
  logging: true,
};




error I get

query: SELECT * FROM current_schema()
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
query: SELECT * FROM current_database()
query: SELECT * FROM current_schema()
query: SELECT "t".* FROM "typeorm_metadata" "t" INNER JOIN "pg_catalog"."pg_class" "c" ON "c"."relname" = "t"."name" INNER JOIN "pg_namespace" "n" ON "n"."oid" = "c"."relnamespace" AND "n"."nspname" = "t"."schema" WHERE "t"."type" IN ('VIEW', 'MATERIALIZED_VIEW') AND (1=1)       
query: SELECT * FROM current_schema()
query: ALTER TABLE "public"."role" DROP COLUMN "role" (update_by"
query failed: ALTER TABLE "public"."role" DROP COLUMN "role" (update_by"
error: error: syntax error at or near "("
    at Parser.parseErrorMessage (C:\Users\abdul\OneDrive\Desktop\theecode\react\saftey-backend\Admin-Api\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (C:\Users\abdul\OneDrive\Desktop\theecode\react\saftey-backend\Admin-Api\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\abdul\OneDrive\Desktop\theecode\react\saftey-backend\Admin-Api\node_modules\pg-protocol\dist\parser.js:39:38) 
    at TLSSocket.<anonymous> (C:\Users\abdul\OneDrive\Desktop\theecode\react\saftey-backend\Admin-Api\node_modules\pg-protocol\dist\index.js:11:42)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 90,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '48',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror'
}

im facing this error
