### ISSUE TITLE
IDs are deleted when starting the server after changing TypeORM version 

### ISSUE THREAD

**Issue by creadicted** [typeorm/typeorm#3408]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `mysql` / `mariadb`

**TypeORM version:**

[x] `latest`

After updating from "0.2.8" the IDs of some entities are deleted when I start the server.
I am not sure why they are deleted on one entity but not on the other

Could be that it is related to #3379 

Edit: 0.2.9 is not effected.

**Comment by pleerock** [comment]
Its hard to tell without additional information. Can you provide some reproduction for this issue?

**Comment by funkizer** [comment]
Please see my comments in a closed issue: https://github.com/typeorm/typeorm/issues/2712
Sorry, should've search here instead of google :)

**Comment by pleerock** [comment]
this issue was fixed in `typeorm@rc`, try `npm i typeorm@rc`

**Comment by creadicted** [comment]
@funkizer : I searched here but missed your issue. 
Thank you very much!

**Comment by pleerock** [comment]
Think we can close this issue now.
