### ISSUE TITLE
Unknown fields are stripped from WHERE clause

### ISSUE THREAD

**Issue by realyze** [typeorm/typeorm#3416]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Reproducible with https://github.com/typeorm/typescript-example

1. Create some categories in the DB

Add this snippet
```
const categoryRepository = getRepository(Category);
const categories = await categoryRepository.find({doesNotExist: 'any value'} as any);
console.log(categories);
```

I would expect `categories` to be empty since we're querying a non-existent field. However the query actually returns everything (i.e., every record in the `Category` table).

Is there any reason the `doesNotExist` key is not present in the resulting SQL query please?

**Comment by pleerock** [comment]
@vlapo this is fixed by #3324 right?

**Comment by vlapo** [comment]
> this is fixed by #3324 right?

3324 was about update. This is select. In this case are unknown properties removed without error.

**Comment by pleerock** [comment]
ah, okay... Shall we apply same strategy for selects?

**Comment by vlapo** [comment]
Original question:
> Is there any reason the `doesNotExist` is not present in the resulting SQL query please?

@realyze if typeorm do not remove non-exists columns from your query, you will get error from database. So thats reason why we do it.

> ah, okay... Shall we apply same strategy for selects?

This is breaking change. Lot of users will get errors after it. But IMHO it is correct behaviour to throw error if someone try to use unknown column in where statement of SQL (database will return error in this case, too). @Kononnable, @havenchyk what do you think about this?

**Comment by pleerock** [comment]
Im for throwing an error. If its so-breaking we need to do it against `next`.

**Comment by silentroach** [comment]
Just got the same thing - thought that the field was used in the query, but it was just skipped :{

Will be great to throw an error.

**Comment by realyze** [comment]
How about adding a flag that toggles between the new/old behaviour? IMO the default should be to throw (because of principle of least surprise) but it would be good to allow users to opt out.

**Comment by silentroach** [comment]
Here is an issue for this #2528

**Comment by Kononnable** [comment]
Adding a flag would increase complexity. I think we should just throw an error - it's a programmer error and it should be fixed as soon as possible or program logic may become unstable.

**Comment by spech66** [comment]
I still think this is **highly critical**. This bug causes delete/update statements to drop/update more data than the query would assume.

**Comment by justvamp** [comment]
Very often it happens like this: `where: { userId }` instead of `where: { user }`.
It can be really hard to find this out during a code review.

**Comment by spech66** [comment]
Any progress?

**Comment by anthonylau** [comment]
I think it should just throw an error as well. This kind of error is very difficult to be checked during code review.

**Comment by vlapo** [comment]
Okey, I think we should add this into 0.3.0 release as throwing error is breaking change for som users.

**Comment by ElePhontitis** [comment]
Would it be possible to get a config switch or something alike for this in the next release? This is really dangerous behaviour imho.

**Comment by baba43** [comment]
Like @spech66 mentioned, the current behaviour is very dangerous, because intentionally one would think that queries are correct when there is no error. If I query "Tasks by user" and the user field is misspelled (or has been changed), then TypeORM is leaking ALL data.

Finding a solution for this would be great 👍

**Comment by reverie** [comment]
This is deeply wrong behavior. Has anyone found a workaround?

**Comment by araujoigor** [comment]
I just opened a similar issue about this but on a different perspective:

As a user, I want the compiler to tell me I'm using a property that does not exist.

My suggestion for this would be to have two different `where` properties: a raw one and a "typed" one.

To maintain backwards compatibility, the current `where` could be of type `string|ObjectLiteral|FindConditions<Entity>` and keep the property stripping behavior.

The new `where` property could be forcefully set to `FindConditions<Entity>` and not stripe anything.

**Comment by dsbert** [comment]
I think this issue can be closed.

**Comment by bhuvinth** [comment]
This is major issue when you consider using find and remove.
Is there any way we can help to solve this issue?

**Comment by imnotjames** [comment]
> I think this issue can be closed.

I think so too - much of this seems to be resolved by https://github.com/typeorm/typeorm/pull/5603

> This is major issue when you consider using find and remove.
> Is there any way we can help to solve this issue?

Could you elaborate how this is still a problem after the aforementioned PR?

**Comment by imnotjames** [comment]
I'm gonna close this for now - but please let me know if this is still an issue.  I cannot replicate it any longer.

**Comment by osdiab** [comment]
would be nice if it were a compile time error instead of just a runtime one, but the types for these functions are already way too broad so maybe it's too late to make that kind of api change...

**Comment by imnotjames** [comment]
Compile time should be in the `@next` but require a version of typescript we can't use yet.

**Comment by osdiab** [comment]
Oh sweet, thanks for the info @imnotjames !
