### ISSUE TITLE
[sqlite:v0.2.11] error during inserting array with inherited tables

### ISSUE THREAD

**Issue by bpatrik** [typeorm/typeorm#3419]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.11` (or put your version here)

I found two potential bugs in connection with `insert`:

insert won't run on arrays if I'm inserting [entities with inheritance](https://github.com/bpatrik/pigallery2/blob/22aecea2637bdcb6d17b34e54d8b4c9b46211275/backend/model/sql/enitites/MediaEntity.ts#L56) (parent and child entities are saved into single table with a `type`  flag).
E.g:
```typescript
@Entity() 
@TableInheritance({column: {type: 'varchar', name: 'type'}})
export abstract class A {
...
}
@ChildEntity()
export class B extends A { 
name:string;
}
@ChildEntity()
export class C extends A { 
...
}
const entities:B[] = [{name:'test'},{name:'test2'},{name:'test3'}];
connection.getRepository(B).insert(entities);
```
The generated SQL will be something like:
```SQL
INSERT INTO "B"("name","type") VALUES (?,?) ,  (?,?) ,  (?,?) - pamateres: ['test','B','test2','test3']
```
So the `type` will be missing from the parameters (only the first entity will have type)

**Comment by pleerock** [comment]
Ahh if those questions regarding to `insert`/`update` methods will keep coming I'll remove them from ORM.

`insert`/`update` methods are trivial and used to execute a basic `INSERT`/`UPDATE` query. Use `save` method instead.

**Comment by bpatrik** [comment]
Yeah that would be my intention (to use a more trivial method).
In this case I know that the entities are not present in the DB yet, and I only would like to insert them an efficient way. As I saw `update` `SELECT` and `INSERT` every entities separately. I only need to insert them at once. 
`insert` actually works in other cases, but here just skips the `type` tag for every entity except the first one.

**Comment by pleerock** [comment]
`save` actually does hundred things that `insert` does not. `insert` is almost as trivial as writing a simple insert query.

Think we can close it.
