### ISSUE TITLE
Loading dotEnv file and ormconfig.js

### ISSUE THREAD

**Issue by clovis1122** [typeorm/typeorm#3420]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Coming from Sequelize, this is a very awesome ORM!

I'm implementing multi-environment variables (`.env`, `.env.testing`) that is part of a Docker setup in my project. I created an ormconfig.js file and attempted to load my `.env.testing` using `dotenv`, but found out that someone had already loaded an environment.

It seems that Typeorm is pre-loading the dotEnv file in the [ConnectionOptionsReader](https://github.com/typeorm/typeorm/blob/51f889f6343a36b93cb5507b538a5da848fece59/src/connection/ConnectionOptionsReader.ts#L107) file without allowing the option to customize this load.

This introduces two issues for me:

1. If the variable `TYPEORM_CONNECTION` exists then my `ormconfig.js` file won't be loaded. This was probably intentional, but not a very intuitive behavior. Shouldn't explicit configurations (such as an `ormconfig,js` file) override the less explicit ones (such as a .env defined variable)?

2. I cannot load the environment that I want because Typeorm already loaded one and overriding already-defined environment variables [is not supported by `dotenv`, due to security reasons](https://github.com/motdotla/dotenv/issues/220).

The temporal workaround that I'm using is to override the env variables and also had to rename my env variables to avoid Typeorm not loading my `ormconfig` file.

Would it be possible to address (2) by giving the user the option to load the environment (or to specify the path) using a config file? For (1), would it be possible to attempt to load the `ormconfig` files before loading the `.env` variables?

**Comment by clovis1122** [comment]
> > If the variable TYPEORM_CONNECTION exists then my ormconfig.js file won't be loaded. This was probably intentional, but not a very intuitive behavior. Shouldn't explicit configurations (such as an ormconfig,js file) override the less explicit ones (such as a .env defined variable)?
> 
> its controversial. Some people may point that they have development configuration in ormconfig and on production they want to override that using env variables.
> 
> why you simply won't override .env with your .env.testing (mount it, replace it or something)?

Thanks for taking the time to reply to this.

That use case is fine, though I think we should be more explicit on how Typeorm is loading the configuration file. Having implicit ordering can be a nightmare to debug later on.

Perhaps if we cannot solve the controversy, would it be fine to document this behavior in the documentation, so that people know how Typeorm decides from where to take the configuration?

As for the `.env` topic, we follow the convention of using a `.env` file for normal development (The file is overrided for prod) and `.env.testing` file for running the tests. This allow us to override certain configurations (e.g, the DB that's accessed, caching, logs, and other settings) that we would otherwise have to hardcode.

I cannot override the `.env` with the `.env.testing` because the development configuration would be lost. My solution was to use `ormconfig.js` to read the NODE_ENV variable and load the appropriated env file, but that didn't work.

**Comment by pleerock** [comment]
to make it to work with CLI probably you have only one option - left only `ormconfig.js` and setup what you need in there through env-related checks.

**Comment by clovis1122** [comment]
Sounds good, thanks!

**Comment by moltar** [comment]
Arguably it is outside of TypeORM's responsibility to manage `.env` files.

This is a very unexpected and magical behaviour.

This magical behaviour can lead to many issues.

Arguably implicitly reading config from any env is a bad behaviour.

What if I accidentally set an env variable and forget to unset it, and can destroy data this way.

I think the best way is to offload config loading to third party packages that can be loaded separately.

**Comment by grumpyoldman-io** [comment]
I just spend 2 hours finding out why my env vars are not being expanded properly, loading of custom `.env.x` vars is not that uncommon (it is the default in Create React App for instance).

I think it is bad practice to have a tool implicitly (magically) ingest `env` vars, especially when it is so easy to add env var loading in a ormconfig file. TypeOrm should be confined to what you explicitly put in.

**Comment by JSilversun** [comment]
Another case where I spent 2 hours figuring out why I wasn't able to load a `.env.x` file or why my `.env` was being loaded magically because yes, you don't expect for your orm to load your environment variables.

**Comment by pethaniakshay** [comment]
I too spent 1 hour and came across this thread. I want to explicitly set the env file but no way to do it.

**Comment by thauam09** [comment]
i'm facing the same problem. There is no way to implement this feature in the future?

**Comment by ordep2v** [comment]
same problem in 2022
