### ISSUE TITLE
Cannot save to nested-tree table if schema is used in postgres

### ISSUE THREAD

**Issue by jest10820** [typeorm/typeorm#3422]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Repo with the example: https://github.com/jest10820/typeorm-tree-issue

When using an entity with `schema` and `name` using the `Tree` decorator like:

```ts
@Entity({ name: 'users', schema: 'admin' })
@Tree('nested-set')
class UserModel {
  @PrimaryColumn('uuid')
  public id: string;
  @Column({ nullable: false })
  public email: string;

  @TreeParent()
  public manager: UserModel;

  @TreeChildren()
  public managerOf: UserModel[];
}
```

I got the next error when trying to save new objects into the database:

```bash
database_1  | 2019-01-14 16:30:43.775 UTC [35] STATEMENT:  UPDATE "admin.users" SET "nsleft" = CASE WHEN "nsleft" > 2 THEN "nsleft" + 2 ELSE "nsleft" END,"nsright" = "nsright" + 2 WHERE "nsright" >= 2
test_1      | query: UPDATE "admin.users" SET "nsleft" = CASE WHEN "nsleft" > 2 THEN "nsleft" + 2 ELSE "nsleft" END,"nsright" = "nsright" + 2 WHERE "nsright" >= 2
test_1      | query failed: UPDATE "admin.users" SET "nsleft" = CASE WHEN "nsleft" > 2 THEN "nsleft" + 2 ELSE "nsleft" END,"nsright" = "nsright" + 2 WHERE "nsright" >= 2
test_1      | error: { error: relation "admin.users" does not exist
test_1      |     at Connection.parseE (/app/node_modules/pg/lib/connection.js:555:11)
test_1      |     at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:380:19)
test_1      |     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:120:22)
test_1      |     at Socket.emit (events.js:182:13)
test_1      |     at addChunk (_stream_readable.js:283:12)
test_1      |     at readableAddChunk (_stream_readable.js:264:11)
test_1      |     at Socket.Readable.push (_stream_readable.js:219:10)
test_1      |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I guess this is the same issue as https://github.com/typeorm/typeorm/issues/2043 but for NestedTree, and maybe the changes from https://github.com/typeorm/typeorm/commit/40b6587157a5ac607d1cc272580987f29d22da6c but applied to https://github.com/typeorm/typeorm/blob/master/src/persistence/tree/NestedSetSubjectExecutor.ts should solve the problem.

Thanks.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
Feel free to PR those changes with tests applied!
