### ISSUE TITLE
Datatype: Fixed character char(100)

### ISSUE THREAD

**Issue by navossoc** [typeorm/typeorm#343]
Hi, I like to know if it is possible to create a `character` column on postgres.

I was reading the docs, but I didn't find anything related to create a column with fixed length.
Am I missing something here or it's not possible at the moment?

Is there any chances this data type will be added?

```sql
CREATE TABLE users (
    id integer NOT NULL,
    login character varying(100) NOT NULL,
    hash character(64) NOT NULL
);
```

Thanks.

**Comment by pleerock** [comment]
you can do that:

```typescript
@Entity("users")
export class User {
     // ....

     @Column({ length: 100 })
     login: string;

}
```

**Comment by navossoc** [comment]
@pleerock Yes, but that result in `character varying(100)`.

I'm trying to achieve the `character` type, like on the hash column.

**Comment by pleerock** [comment]
ah no, there is no separate type for character. I will do that in the future once I get more free from more priority tasks. If you have a time you can contribute, its pretty easy feature to implement.

**Comment by navossoc** [comment]
Sure, but give me some guidelines here, maybe I can help.

How do you plan to implement it? I mean...

Are you planning to add a new option `type` at the @Column() decorator?

Something like this:
```ts
@Entity("users")
export class User {
     // ....

     @Column({  type: "stringfixed", length: 64})
     hash: string;
}
```
Maybe, you are planning to add a new option flag like "fixed"?

```ts
@Entity("users")
export class User {
     // ....

     @Column({  type: "string", length: 64, fixed: true})
     hash: string;
}
```

Personally, I think the second option would make more sense since it could be used for other types of data in the future. For example, in MySQL:
```
char / varchar
binary / varbinary
```

Or maybe in a totally different way...
Let me know what are you plans on this and I can push a PR to help you on that.

[]'s

**Comment by pleerock** [comment]
Having `fixed` looks a better option then adding separate types for each of them. Its a bit more complicated to implement (but still easy) and it looks like a better approach. Should it be named `fixed` or `fixedLength`? Adding @19majkel94

**Comment by 19majkel94** [comment]
I think that `length` should set the fixed length n chars and `maxLength` should do the varchar like.
You can get typesafe in the same way like [here](https://github.com/typeorm/typeorm/issues/289#issuecomment-282101194)
If you don't want to introduce a breaking change, the best substitute would be `fixed` option I think.

**Comment by navossoc** [comment]
I think `fixedLength` sounds better to me than just `fixed`.

To be honest, we can go on the other way around and call it the `variableLength` (default = true).

Not sure now, this is a touchy question!
I will think about it, if I have a better idea I let you guys know.

I'll keep following the discussion.

[]'s

**Comment by pleerock** [comment]
@19majkel94 having length and maxLength is too confusing and complicated in my opinion. Better to simply add a new option which is clear and straightforward. 

@navossoc haha right `fixedLength` or `variableLength` thats touchy. I think I still like `fixedLength`, but not completely sure 😆

**Comment by WoLfulus** [comment]
So, here's my vote...
I think that `fixedLength` is more clear than just `fixed`... anyone who sees that "fixed" will be wondering "fixed what?"

**Comment by pleerock** [comment]
agree, thanks for the feedback @WoLfulus

**Comment by pleerock** [comment]
in latest alpha versions typeorm supports all database supported column types, so now you can use `@Column("char")` if you need fixed character length.
