### ISSUE TITLE
Migration Generation Without Database Connection

### ISSUE THREAD

**Issue by devmattrick** [typeorm/typeorm#3430]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Currently, from what I can tell, generating a migration requires that typeorm's CLI is able to connect to a database. However, in an development environment, there are situations where it is less then ideal to run it against an live database. For example, I am running my application inside of a Docker container for development.

I understand the way migration:generate command works at the moment is entirely based on a database connection, but I'm wondering what the feasibility is of generating new migrations based off of a comparison with existing migrations.

Thank you so much for your time!

**Comment by Diluka** [comment]
@devmattrick No matter where the application or the database is running. The application can connect to a database and docker can bind mounts and execute commands. So it's not a problem.

**Comment by felixhayashi** [comment]
@pleerock isn't it possible for typeorm to simply generate the whole schema if no connection is provided :thinking:  ...it seems a bit clumsy to me having to setup and boot a db just for the sake of generating an initial schema for the first migration.

**Comment by varanauskas** [comment]
Additionally, this possibly extends to a feature request, but the way migrations could be generated without a database connection is by simulating all of the existing migrations in order on a mock database (to get the schema, if no migrations exist, then schema is empty) and then add the new migration based on the constructed schema on the mock database.

**Comment by fan-tom** [comment]
+1 for @varanauskas suggession, Django ORM acts in this way, also it keeps migrations abstract and declarative (no backend-specific things in migrations, migration is just changeset that needs to be transformed to sql for actual backend)

**Comment by varanauskas** [comment]
In the meantime I am using a quick and dirty solution, it creates a new database locally on developer machine, runs all migrations on it and then drops the database, effectively not having to touch any production database but only a local development one. (Only tested in postgres)

```ts
import { Query } from "typeorm/driver/Query";
import { SqlInMemory } from "typeorm/driver/SqlInMemory";
import { promises } from "fs";
import { createConnection, getConnectionOptions } from "typeorm";

const queryParams = (parameters: unknown[] | undefined) =>
  !parameters || !parameters.length ? "" : `, ${JSON.stringify(parameters)}`;
const queryToStatement = ({ query, parameters }: Query) =>
  `    await queryRunner.query(\`${query.replace(/`/g, "\\`")}\`${queryParams(
    parameters
  )});`;
const renderTemplate = (
  name: string,
  { upQueries, downQueries }: SqlInMemory
) => `import { Service } from "typedi";
import { MigrationInterface, QueryRunner } from "typeorm";

export class ${name} implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
${upQueries.map(queryToStatement).join("\n")}
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
${downQueries.map(queryToStatement).join("\n")}
  }
}
`;

async function createMigrationQueries() {
  const database = `migration_generation_${Date.now()}`;
  const options = await getConnectionOptions();
  const connection = await createConnection({
    ...options,
    synchronize: false,
    migrationsRun: false,
    dropSchema: false,
    logging: false,
  });
  try {
    await connection.query(`CREATE DATABASE "${database}"`);
    const temporaryConnection = await createConnection({
      ...options,
      database,
      name: "temporary",
    });
    try {
      await temporaryConnection.runMigrations();
      return await temporaryConnection.driver.createSchemaBuilder().log();
    } finally {
      temporaryConnection.close();
    }
  } finally {
    await connection.query(`DROP DATABASE "${database}"`);
    await connection.close();
  }
}

export async function generateMigration(name: string) {
  const timestamp = Date.now();
  const { cli: { migrationsDir } } = await getConnectionOptions();
  const queries = await createMigrationQueries();
  const content = renderTemplate(`${name}${timestamp}`, queries);
  const filename = `${migrationsDir}/${timestamp}-${name}.ts`;
  await promises.writeFile(filename, content);
}
```

**Comment by AlissonRS** [comment]
Coming from .NET Core, I miss this. Entity Framework can generate migrations without connecting to database, so it's a shame TypeORM not only does not support, but the team behind it is not interested in improving it.
