### ISSUE TITLE
Nested objects won't update on Repository.save

### ISSUE THREAD

**Issue by algkebab** [typeorm/typeorm#3436]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[*] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have two entities and one is a part of another. When I try to save new parent object, all child objects get created, but once I try to save it again, postgresql log doesn't show that update query was executed for nested objects instead it tries to insert same objects and I get: error: duplicate key value violates unique constraint "stops_pkey" QueryFailedError: duplicate key value violates unique constraint "stops_pkey", which is expected. however documentation says the following:

>  /**
>      * Saves a given entity in the database.
>      * If entity does not exist in the database then inserts, otherwise updates.
>      */
>     save<T extends DeepPartial<Entity>>(entity: T, options?: SaveOptions): Promise<T>;

is it the case for nested objects? Because obviously it didn't work in my case. How to make it update instead of insert of nested objects? Because everything works just fine for parent entity. My entity description is below:

```
@ObjectType()
@InputType('TripInstanceInput')
@Entity({name: 'trip_instance'})
export class TripInstance {

    @Field()
    @PrimaryColumn({name: 'trip_id'})
    tripId: string;

    @Field()
    @PrimaryColumn({name: 'service_date'})
    serviceDate: string;

    @Field({nullable: true})
    @Column({name: 'service_id'})
    serviceId: string;

    @Field({nullable: true})
    @Column({name: 'updated_timestamp'})
    updatedTimestamp: Date;

    @Field(type => [Stops], {nullable: true})
    @OneToMany(type => Stops, stops => stops.tripInstance, {eager: true, cascade: true})
    stops: Stops[];
}

@ObjectType()
@InputType('StopsInput')
@Entity({name: "stops"})
export class Stops {

    @Field({nullable: true})
    @PrimaryColumn({name: 'trip_id'})
    tripId: string;

    @Field({nullable: true})
    @Column({name: 'stop_id'})
    stopId: string;

    @ManyToOne(type => TripInstance, tripInstance => tripInstance.stops)
    @JoinColumn({name: 'trip_id', referencedColumnName: 'tripId'})
    tripInstance: TripInstance;
}

this.connection.getRepository(TripInstance).save(tripInstance, options);
```

**Comment by pleerock** [comment]
Most probably you did something wrong. We need a PR with a failing test attached with **minimal reproduction code**

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by ullalaaron** [comment]
I have experienced the same issue:
On typeorm 0.2.16 + postgresql calling `save` updates the parent but only creates (and not updates) children. 
Parent class is defined as :
```
@Entity()
export class Company extends BaseEntity {
    ...
    @Column({ type: 'varchar', length: 30 })
    vatCode: string;

    @OneToMany(type => CompanyContact, companyContact => companyContact.company, { cascade: true, eager: true })
    contactList: CompanyContact[];
}
```

Child class defined as
```
@Entity()
export class CompanyContact extends BaseEntity {

    @Column({ type: 'enum', enum: CompanyContactType })
    type: CompanyContactType;

    @Column({ type: 'varchar' })
    url: string;

    @Exclude()
    @ManyToOne(type => Company, company => company.contactList)
    company: Company;
}
```
