### ISSUE TITLE
Create an Index on an Embedded Field (mongodb)

### ISSUE THREAD

**Issue by ricardovf** [typeorm/typeorm#3437]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
user.ts
@Index('phoneNumberIndex', ['phone.number'], { unique: true })
@Entity()
export class User {
    ....
    @Column(type => Phone)
   phone: Phone;
}
```

```ts
phone.ts
export class Phone {
  ...
  @Column()
  number: string;
}
```

Trying to use index on embedded documents (https://docs.mongodb.com/manual/core/index-single/#create-an-index-on-an-embedded-field)

The index created on the collection should be **phone.number**, instead **phone** index was created. 

Might be related to https://github.com/typeorm/typeorm/issues/3142

![screen shot 2019-01-16 at 20 01 06](https://user-images.githubusercontent.com/453574/51281417-7b580e00-19c9-11e9-96f1-4fa044c14f48.png)

**Comment by rustamwin** [comment]
https://github.com/typeorm/typeorm/blob/f0990ce91fb632d7f45f34ff5c6790ed59907c9b/src/metadata/IndexMetadata.ts#L149

**Comment by ricardovf** [comment]
@rustamwin i really don't have the time to go into the source code now, but as it seems, for now it's not possible to do it, right?

I guess i will create a migration and create the indices directly. Or do you have another suggestion?

Thanks

**Comment by rustamwin** [comment]
@ricardovf Yes. I think this problem will be fix soon

I guess too

**Comment by ricardovf** [comment]
Ok, i hope so! Thanks
