### ISSUE TITLE
TypeORM migration:generate produces pointless migration changes 

### ISSUE THREAD

**Issue by vladimirmoushkov** [typeorm/typeorm#3441]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Add an following entity to existing TypeORM projecT:

```
import { Column, Entity, Index, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from "typeorm";
import { User } from "./User";

@Entity()
export class Session {
    @PrimaryGeneratedColumn()
    public id: number;

    @ManyToOne(() => User)
    @JoinColumn()
    public user: User;

    @Column({type: "char", precision: 64, nullable: false})
    @Index({unique: true})
    public sessionId: string;

    @Column()
    public validTo: Date;

    @Column()
    public lastActive: Date;
 }

```
Generate a migration using:

> ts-node ../../../node_modules/.bin/typeorm migration:generate -n AnyName

It will produce initial migration that contains Session table creation. Then run the migration as:
> ts-node ../../../node_modules/.bin/typeorm migration:run

And then re-run the migration generation
> ts-node ../../../node_modules/.bin/typeorm migration:generate -n AnyName2

Result of that will be migration that regenerates sessionId **column**.  If the entity lacks precision specifier, and the above scenario is re-ran it will produce no second **AnyName2** migration.

The issue is similar to these ones where the precision triggers non existing difference observation by the migration generator:
https://github.com/typeorm/typeorm/issues/1960
https://github.com/typeorm/typeorm/issues/2943

**Comment by corocn** [comment]
Same issue to me. "Date" column continues to generate migration files that have pointless alter sql command.

**Comment by hungneox** [comment]
Is there any news on this? I also have the same issue.

**Comment by volnyansky** [comment]
@hungneox I fixed it with  @Column({type:"datetime",precision:0})

**Comment by Kononnable** [comment]
@vladimirmoushkov 
>Result of that will be migration that regenerates sessionId **column**.

You shouldn't use precision on char column. Precision property is intended only for some numeric types. You should set length property instead.

As for datetime and precision - it will be fixed in 0.3.0 after merging #3262

**Comment by wasims1** [comment]
anyone knows how to solve this issue? i have the same problem and it's getting rediculous..

**Comment by stouch** [comment]
Same problem here.

**Comment by spmsupun** [comment]
it's 2021 and it's still happening  :(

**Comment by dilpazir-whizpool** [comment]
2022 and still happening.
Version using: 0.2.41 (latest)

**Comment by bitpickle** [comment]
2025 and stills happening. (^0.3.22)

**Comment by stouch** [comment]
I hesitated to add this thread in https://github.com/typeorm/typeorm/issues/6803#issuecomment-2097719487
