### ISSUE TITLE
@JoinTable on entities without synchronization

### ISSUE THREAD

**Issue by kzoltan86** [typeorm/typeorm#3443]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Some of my entities are mapped to temporary tables. Therefore, turning off synchronization for these entities is a must for me. With that, TypeORM won't attempt to create tables with the given name. However, if one of these entities contain a ManyToMany relation with a JoinTable, TypeORM always creates (unless syncronization is turned off globally) the junction table.
This also leads to database errors while TypeORM tries to create foreign key constraints between the junction table and the nonexistent temp tables.

**Comment by pleerock** [comment]
We need to introduce a flag for relation options, something like:

```ts
@ManyToMany()
@JoinTable({ synchroization: false }
```

Feel free to contribute.

**Comment by phil294** [comment]
I could imagine `synchronize: false` also being helpful for normal columns, not just relations. This means, typeorm should expect the column to be in the database, but not attempt to sync it upon `schema:sync` or `migration:generate`. Sample use case: https://github.com/typeorm/typeorm/issues/1822#issuecomment-573492291
Hope I'm not misunderstanding this issue
