### ISSUE TITLE
Column decorators should work with constructor parameter

### ISSUE THREAD

**Issue by shivawu** [typeorm/typeorm#3445]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Consider the following code. I'm trying to define all the properties and the constructor
at the same time, which saves a lot of duplicated code.

```ts
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class User {
  constructor(
    @PrimaryGeneratedColumn()
    public readonly id: number,
    @Column()
    public readonly name: string,
  ) {}
}
```

But this fails because typeorm cannot detect the types of the arguments (properties).
I believe this can be implemented by extracting the parameter types from `design:paramtypes` metadata key from the constructor and match the index there. 

I could start working on a PR, but wanted to make sure this is a valid usecase and it's accomplishable.

**Comment by shivawu** [comment]
Thanks for getting back at me! Yeah, that does make sense about what you proposed. One bad thing about the constructor approach that I had is, it doesn't support named arguments properly. OTOH, issue with your approach is TS will yell about "uninitialized property" when `strict` is enabled, so we have to `public readonly id!: number`.

I guess let's keep it here? Having alternatives is almost always a good thing :)

**Comment by pleerock** [comment]
> Having alternatives is almost always a good thing :)

I heard having multiple ways of doing same thing is a bad thing 🤣

**Comment by shivawu** [comment]
Nooo, not another philosophy question! LOL

To add a little bit more context, this constructor thing happens when I wrote some data importers from external data source, like JSON files. It involves converting a JSON object into a typeorm object, with proper conversion of PK, FK, and special data types and all. I had to do something like 
```
const entity = new User();
entity.id = '...';
entity.name = '...';
```
Plus all the `!` on the field declaration. I assume constructing a entity locally and storing them into DB is a pretty common use case, and we should have a propery way of doing it without `!`.

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by webleaf** [comment]
need this feature too

**Comment by Flaavius** [comment]
one way I found to do this is creating an interface for the class : 
`
export interface IUser {
  name: string;
  age: number;
  job: string;
}

@Entity()
export class User implements IUser {

  @Column({
    length: 100,
  })
  public name: string;

  @Column()
  public age: number;

  @Column({
    length: 50,
  })
  public job: string;

  @PrimaryGeneratedColumn()
  private id: number;

  constructor(user: IUser) {
    Object.assign(this, user);
  }
}
`
this way when you create the user entity it will not complain about the primaryFields. 

`
  const user = new User({
    name: "Flavius",
    age: NaN,
    job: "Developer",
  }); // no complaints!
`

I hope this helps someone.
