### ISSUE TITLE
select max value with specific column in typeorm 

### ISSUE THREAD

**Issue by hengsoheak** [typeorm/typeorm#3448]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.8` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
 
**Is it possible to use existing sql function Max() in Typeorm?

`getOneMaximumQuotationVersion() {
    return this.createQueryBuilder("Quotation")
    .select(["Quotation.id", "Quotation.quotationVersion"])
    .addSelect("MAX(Quotation.id)", "max")
    .getOne();
  }  `

**Comment by pleerock** [comment]
you need to use `getRawOne` method instead
