### ISSUE TITLE
Join query on ManyToMany relations not working

### ISSUE THREAD

**Issue by AurelieV** [typeorm/typeorm#345]
I define two entities

```
@Table()
export class Target {
    @PrimaryColumn() agfold_id: number;
    [...]
    @ManyToMany(type => User, user => user.targets)
    @JoinTable()
    users: User[];
}

@Table()
export class User {
    @PrimaryGeneratedColumn() id: number;
    [...]
    @ManyToMany(type => Target, target => target.users)
    targets: Target[];
}
```
Then, I try to fetch some users with associated targets.

```
userRepos
            .createQueryBuilder("user")
            .leftJoinAndSelect("user.targets", "targets")
            .where("targets.agfold_id IN(:ids)", { ids: targetIds })
            .getMany();
```
The request fails, because the join condition is not written correctly
```
[...]
LEFT JOIN "target_users_user_id" "user_targets" ON "user_targets"."userId"="user"."agfold_id" 
```

(the key is not the good name. It has to be `user.id`, not `user.agfold_id`)

Version 0.0.9, with sqlite.

**Comment by tomymolina** [comment]
I have the same issue.

**Comment by pleerock** [comment]
fixed and released in `0.0.10`. Please check that.

**Comment by AurelieV** [comment]
Hi @pleerock 
It works well when (in my case) selecting target and joining users, but not when selecting users and joining target.
I have `"error":"TypeError: Cannot read property 'table' of undefined"`

**Comment by pleerock** [comment]
is what you are talking differs from example you wrote before?

**Comment by AurelieV** [comment]
Hi @pleerock.
The problem `"error":"TypeError: Cannot read property 'table' of undefined"` appears in this request, when using v0.0.10
```
userRepos
            .createQueryBuilder("user")
            .leftJoinAndSelect("user.targets", "targets")
            .where("targets.agfold_id IN(:ids)", { ids: targetIds })
            .getMany()
```

When I do this other request, 
```
targetRepos
            .createQueryBuilder("target")
            .leftJoinAndSelect("target.users", "user")
            .where("user.id IN(:ids)", { ids: userIds })
            .getMany();
```

everything is fine in v0.0.10. The models are the same than the initial problem. So it seems that the fix works when we are at the owning side or not.

**Comment by pleerock** [comment]
See I added [test](https://github.com/pleerock/typeorm/blob/553eea2ef48fe143977175bd56eb2d8d05296455/test/github-issues/345/issue-345.ts#L27-L27) which exactly what you have but with different model names. It seems to work there. Can you point is my testing wrong?

**Comment by AurelieV** [comment]
Hmmm this is the same case as mine.
My request is a bit more complicated, but I am pretty sure the problem is with the join, when I comment it everything just work fine.
This is what I see can be different => Target have also manyToOne relation to User (creator). I also join to others entities in my request.
Can you explain me how to run your test? I will try to find a minimal way to reproduce the problem, it will be easier for you to fix it.

**Comment by pleerock** [comment]
you can find documentation in contributors guide. Basically what you need to do is:
* checkout project
* run `npm i`
* copy/paste ormconfig.json and change to your settings if needed
* if you are using docker you can do `docker-compose up` and it will setup you databases
* you can disable not needed drivers in ormconfig.json

**Comment by AurelieV** [comment]
@pleerock I am not able to reproduce the issue with a minimal settings yet, but I investigate and the error happen at [this line](https://github.com/typeorm/typeorm/blob/master/src/query-builder/QueryBuilder.ts#L1736)
junctionMetadata is undefined.

Our model is a bit complexe, do you have an idea why this can be undefined? It can help me to find a way to reproduce the error.

**Comment by pleerock** [comment]
not quite sure. junction table is a table of many-to-many relations. Its defined if your relation is many-to-many.

**Comment by AurelieV** [comment]
@pleerock I finally resolve this. I have forgotten the second argument for ManyToMany decorator in Target for the owning side (I think this is currently the case in the README)
Thanks for your help
