### ISSUE TITLE
Mongo embedded document @BeforeInsert error when embedded document is not set

### ISSUE THREAD

**Issue by ricardovf** [typeorm/typeorm#3450]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
user.ts
@Entity()
export class User {
    @Column()
    name: string;

    @Column(type => Phone)
   phone: Phone;
}
```

```ts
phone.ts
export class Phone {
  @Column()
  number: string;

  @BeforeInsert()
  beforePhoneCreate() {
    this.number = onlyNumbers(this.number);
  }
}
```

```ts
const user = new User();
user.name = 'Whatever'
await repo.save(user);
```

Save throws error that can't call beforePhoneCreate of undefined. As the Phone embedded document is optional an not defined. Can't i defined optional embedded document?

(i will keep reporting bugs as this lib is really great, but mongo support can improve)

**Comment by ricardovf** [comment]
> Please feel free not only to report bugs, but also try to contribute and fix them. Mongo support can be improved A LOT, and we expect it to be a community initiative.

I really want to, but now im programming 10-12h a day on my new company. When we succeed i intent to patron the main projects that are supporting our code, as TypeORM

**Comment by vlapo** [comment]
@rustamwin do you want to check it?

**Comment by rustamwin** [comment]
@vlapo Yeah, I'll check and try to fix it
