### ISSUE TITLE
Argument of type '{ name: FindOperator<any>; }' is not assignable to parameter of type 'DeepPartial<Entity>'

### ISSUE THREAD

**Issue by barmaglot92** [typeorm/typeorm#3460]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.11`

Hello. My question is about https://github.com/typeorm/typeorm/blob/master/docs/find-options.md.
I can't use condition "In" at Entity.find method.

```
    Group.find{ name: In(["test"]) }

Argument of type '{ name: FindOperator<any>; }' is not assignable to parameter of type 'DeepPartial<Group>'.
  Types of property 'name' are incompatible.
    Type 'FindOperator<any>' is not assignable to type 'string'
```
but

```
getRepository(Group).find{ name: In(["test"]) }
still works
```

I compared Repository.find and BaseEntity.find methods interfaces and seen
1.    find(conditions?: FindConditions<Entity>): Promise<Entity[]>;
2.   static find<T extends BaseEntity>(this: ObjectType<T>, conditions?: DeepPartial<T>): Promise<T[]>;

What the reason this differences?

**Comment by pleerock** [comment]
It's a bug. `BaseEntity` declaration is old and invalid. I'll push a fix.

**Comment by barmaglot92** [comment]
Thank you. Will you close issue when fix will be deployed

**Comment by barmaglot92** [comment]
Unfortunately typings have't updated
```
    static find<T extends BaseEntity>(this: ObjectType<T>, conditions?: DeepPartial<T>): Promise<T[]>;
```

i think some troubles with build..

**Comment by barmaglot92** [comment]
It actuals only for npm package, in sources all good

**Comment by ricardovf** [comment]
@pleerock can you update the NPM version? I need this fix urgent too. Thanks!

**Comment by barmaglot92** [comment]
This issue still without upgrade version in npm from two weeks ago, as I see it's already released, but not deployed. I'm so interested in so interested why it's not in npm avail for now

**Comment by barmaglot92** [comment]
Sorry for bad English😒

**Comment by ShanniL** [comment]
I updated the the latest version 0.2.12 today, and still see the error "Type 'FindOperator<string>' is not assignable to type 'string'", I'm using Like<T> 

So.. seems the fix doesn't work.

**Comment by pleerock** [comment]
I'll publish a new version this weekend

**Comment by derekngo** [comment]
@pleerock has this issued been addressed? seems also related to https://github.com/typeorm/typeorm/issues/2904. thank you

**Comment by moltar** [comment]
I am getting these too. Pretty simple use case:

```ts
    // create a new entity instance using the repository
    const crawlRequest = this.crawlRequestRepo.create(req)

    // now try to save it - fails here ...
    await this.crawlRequestRepo.save(crawlRequest)
```

Error raised:

```
const crawlRequet: CrawlRequest
Argument of type 'CrawlRequest' is not assignable to parameter of type 'DeepPartial<CrawlRequest>'.
  Types of property 'iterations' are incompatible.
    Type 'CrawlIteration[]' is not assignable to type 'DeepPartial<CrawlIteration>[]'.
      Type 'CrawlIteration' is not assignable to type 'DeepPartial<CrawlIteration>'.
        Types of property 'results' are incompatible.

           ... and on and on it goes for every column
```

**Comment by moltar** [comment]
In fact, just instantiating an entity manually, yields to the same result!

```ts
const cr = new CrawlRequest()
await this.crawlRequestRepo.save(crawlRequest)
```

Same error!
