### ISSUE TITLE
@Unique docs and implementation discrepancies

### ISSUE THREAD

**Issue by jalooc** [typeorm/typeorm#3461]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

---

The docs say that `@Unique` can be used only on an entity, and only with `string|string[]` type for column names. [The code](https://github.com/typeorm/typeorm/blob/master/src/decorator/Unique.ts#L32), however, indicates that the decorator might as well work on a single class field (see the 2 parameters, first one being class and the second one being property name). Is this an oversight or a delibarate move? Can we / will we be able to use `@Unique` on a single field?

The only thing that _stands_ on the way to use `@Unique` on a class field is (apart of the docs that clearly say not to do it) that a no-op parameter would have to be supplied to satisfy TS, like below:
```javascript
@Entity()
class Foo {

  @Column()
  @Unique(() => ({}))
  bar: string

}
```
:point_up: this in turn leads to my second question - how does the `function` type argument documented in TS, but not mentioned in the docs, work? Is it even permitted to use it?

P.S. I tried the above code and seems that it works 🤷‍♂️

**Comment by pleerock** [comment]
right, `@Unique` can be used on columns as well. Its same as you set `@Column({ unique: true })`. You don't need to do `@Unique(() => ({}))`, simply `@Unique()`.

**Comment by jalooc** [comment]
Aha, thanks for the `@Column({ unique: true })` - I wasn't aware of that!
But regarding `@Unique` - the TS definitions don't allow using `@Unique` without arguments. Should this be fixed? If yes, let know if a PR for both TS and docs will be helpful.

**Comment by jalooc** [comment]
And what about the `fields: (object?: any) => (any[]|{ [key: string]: number })` [parameter](https://github.com/typeorm/typeorm/blob/master/src/decorator/Unique.ts#L17)? What does it do? I wasn't able to find it in the docs. I may add it in one go if there's indeed no doc for it.
