### ISSUE TITLE
Migration Usage

### ISSUE THREAD

**Issue by robotlemons** [typeorm/typeorm#3463]
**Issue type:**

**[x] question**
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
**[x] `postgres`**
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

**[x] `latest`**
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Please forgive me but I'm relatively new to DB related development and I am trying to understand setting up Migrations.

I currently have about 7 entities setup and in development, with synchronize, have had no issues. I know that when I go to production, I want to switch off sync and work with migrations. When I try to generate a migration, currently, it sees no changes so it generates nothing. That makes sense, because I've never set up any migrations but I do have some schema changes to at least one of my entities. 

I assume running .. 
`typeorm migration:generate -n Initialize` 
.. would write migrations for the schemas of my entities as they are currently setup but it does not. 

So I am curious, when I go to production, will I just need to create migrations and use them as needed? Should I run with sync: true at first deploy to production and turn it off to then use migrations as needed?

Thanks for any knowledge you can provide!

**Comment by pleerock** [comment]
> Should I run with sync: true at first deploy to production and turn it off to then use migrations as needed?

yes you can do it this way, I think its more optimal if you are flexible.
