### ISSUE TITLE
createdAt getter throws error (mongodb)

### ISSUE THREAD

**Issue by kiwikern** [typeorm/typeorm#3466]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest (regression since 0.2.10)`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an entity that exposes a createdAt date when its serialized to JSON; createdAt should not be stored in the database though. With 0.2.9 this was working just fine.

```
import { ObjectIdColumn } from 'typeorm';
import {  Expose } from 'class-transformer';

export class ProductEntity {
  @ObjectIdColumn()
  _id: ObjectID;

  @Expose({ name: 'createdAt' })
  @ApiModelProperty()
  get createdAt(): Date {
    return this._id ? this._id.getTimestamp() : null;
  }
}
```

Since 0.2.10 (also tested with 0.2.12), I get the following error: `Cannot set property createdAt of #<ProductEntity> which has only a getter`

If I rename the getter `createdAt` to any other name, no error is thrown. Therefore, I assume this is connected to https://github.com/typeorm/typeorm/issues/2938.

**Comment by pleerock** [comment]
how is it related to #2938 if you don't use `@CreateDateColumn`?

**Comment by kiwikern** [comment]
Maybe it is not at all. I quickly glanced over the code changes in this pull request and couldn't spot anything. Just thought because it is specifically only with `get createdAt` and the version matches. Sorry, I didn't mean to be misleading.

**Comment by pleerock** [comment]
I don't see how your issue is related to typeorm because you don't have anything typeorm-related on `createdAt` property. Maybe error is right because your models doesn't have a setter?

**Comment by rustamwin** [comment]
agree with @pleerock because in model `createdAt` property is readonly
