### ISSUE TITLE
Get data stream from database

### ISSUE THREAD

**Issue by Spoki4** [typeorm/typeorm#347]
What I can use, if I have very more rows in table, and I need select all, but in parts?

**Comment by pleerock** [comment]
In recent versions (0.1.0-alpha.24) there is a stream support. However it just returns you a stream that you can use to get raw data. Its not possible to get real entities using stream because stream returns your data partially, and it can be partial entity (not a single entity) which makes it impossible to return one entity in a stream at once. Thats why streaming would work only for raw data.

**Comment by pleerock** [comment]
api for new stream functionality is `queryBuilder.stream()`

**Comment by AlexandreAWE** [comment]
@pleerock It works, but the documentation is not clear.
```js
const steam = await this.createQueryBuilder('log');

stream.on('data', console.log); // Don't work (Standard nodejs stream event)
stream.on('result', console.log); // Work

```

**Comment by pleerock** [comment]
what is `createQueryBuilder` in your code?

**Comment by AlexandreAWE** [comment]
Sorry my bad : 
```js
 const stream = await this.createQueryBuilder('log')
            .where(`date <= :date`, { date })
            .stream();
```

More over, I can't pipe the stream object : 
TypeError: stream.pipe is not a function

**Comment by pleerock** [comment]
what database you are using? You probably shall refer to underlying driver, .e.g `mysql` package, since we simply return what those packages return in case of streams.

**Comment by AlexandreAWE** [comment]
Mysql driver, you right. I just point that is not clear in TypeORM documentation that event name for retrieve data is called "result" and not "data".
eg: http://typeorm.io/#/select-query-builder/streaming-result-data

**Comment by ORESoftware** [comment]
hmmm, doesn't the stream return whole records from tables?

**Comment by pleerock** [comment]
yes but those records aren't entities

**Comment by ORESoftware** [comment]
@pleerock why couldn't those records be entities? I guess they could not necessarily be mapped to entities? Couldn't the user create an entity that was designed for streaming?

**Comment by pleerock** [comment]
streaming returns data partially, but for typeorm to make a proper mapping to entities it needs all the data (to make proper grouping and mapping). 

The only solution for now is to use streaming and make your query to return you raw results you actually want

**Comment by ayushpratap2494** [comment]
@pleerock Is there any way to pipe the the stream its returning promise<readstream> , M using MYSQL with typeorm. I want pipe this stream. More over M not able to call stream.on('result',()=>{ }) on the stream its saying  stream.on is not a function.

const  stream = Repository.createQueryBuilder.stream();

**Comment by ayushpratap2494** [comment]
@AlexandreAWE 
Is there any way to pipe the the stream its returning promise , M using MYSQL with typeorm. I want pipe this stream. More over M not able to call stream.on('result',()=>{ }) on the stream its saying stream.on is not a function.

const stream = Repository.createQueryBuilder.stream();

**Comment by Calamitizer** [comment]
@ayushpratap2494 

```typescript
const accountStream = (await accountRepository
  .createQueryBuilder('account')
  .stream())
  .on('result', data => { console.log(data); });
```

**Comment by shadrech** [comment]
Is there to specify the amount of data you receive in each chunk? I believe this is the `readableHighWaterMark` value? Is there a way to set it before reading the typeorm stream?

**Comment by Qlub53** [comment]
> @pleerock It works, but the documentation is not clear.
> 
> ```js
> const steam = await this.createQueryBuilder('log');
> 
> stream.on('data', console.log); // Don't work (Standard nodejs stream event)
> stream.on('result', console.log); // Work
> ```

Streaming postgres with `pg-query-stream` here.

`'result'` did not work, no data captured at all. 
The node worker would just sit there and await incoming data for ever.

`'data'` worked, but I had to manually convert raw data into entity objects.

**Comment by Qlub53** [comment]
> Mysql driver, you right. I just point that is not clear in TypeORM documentation that event name for retrieve data is called "result" and not "data". eg: http://typeorm.io/#/select-query-builder/streaming-result-data

Probably because mysql driver has explicitly implemented a 'result' event? (I haven't looked into any mysql driver source code, yet.)

In my case of postgres streaming, the [stream()](https://github.com/typeorm/typeorm/blob/9ac8e9ed0da0ac5bba71b76ee99d6f0c4eb0871f/src/query-builder/SelectQueryBuilder.ts#L1789) method returns a built-in [fs.ReadStream](https://nodejs.org/docs/latest-v16.x/api/fs.html#class-fsreadstream) which extends [stream.Readable](https://nodejs.org/docs/latest-v16.x/api/stream.html#choose-one-api-style) that does not have a 'result' event to listen to.

**Comment by morasyad** [comment]
what if i use mysql instead?
