### ISSUE TITLE
When use .save() method, select all left join

### ISSUE THREAD

**Issue by taehyoung** [typeorm/typeorm#3470]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.7` (or put your version here)

```ts
@Entity()
class Book {
   ....
   @OneToMany()
   ...
   @OneToMany()
   ....
   @ManyToMany()
   as: A[];

   @ManyToMany()
}

@Entity()
class A {
  ...
 @OneToMany()
  ...
@OneToMany()
  ...
@OneToMany()
  ...
}
```

```
let book = new Book()
book.as = aList // A[]
const result = await Book.save(book)
console.log(result)
```
When I Use Book.save(book) and print log,

I saw sql log so many left join that I didn't want

I want to see only Book and A(cascade) not book.tests[].test2s[].test3s[]
 
this query make slow query.

rows_sent are 62496.

how can i fix this query?

**Comment by pleerock** [comment]
it executes multiple queries to **check** if you added anything to your relations (compares what you have in models with what you have in the database). Without those queries it cannot understand if you added or removed something from your model or not.

**Comment by taehyoung** [comment]
thank you I was mistaken
