### ISSUE TITLE
cross db types

### ISSUE THREAD

**Issue by vedun** [typeorm/typeorm#3471]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[* ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[* ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello.
Is it possible to describe the model regardless of the type of database? For example i want to have general text column, somthing like this:
```
@Entity()
class User {
    @PrimaryGeneratedColumn() id: number;
    @Column("generalString") name: string;
}
```
or like this:
```
@Entity()
class User {
    @PrimaryGeneratedColumn() id: number;
    @ColumnString() name: string;
}
```
and that in the postgres it would be a `TEXT` type and in MSSQL `NTEXT`.
One of the options is to write wrapper around decorators, that accept databse type. Perhaps there more elegant options to achive this?
Maybe you are planning to do cross databse types in the future?
Thanks.

**Comment by vedun** [comment]
You do not plan to support cross db functionality or something like that?

**Comment by pleerock** [comment]
I believe what you want to achieve can be done by using entity schemas instead of decorated classes and providing different modified entity schemas to different connections

**Comment by vedun** [comment]
Yes, this is a working approach. But then I lose some of the ORM functionality, such as automatic update of primary keys during save operation. For example:
```TypeScript
@Entity()
class User {
    @PrimaryGeneratedColumn() id: number;
    @Column() name: string;
}
@Entity()
class Application {
    @PrimaryGeneratedColumn() id: number;
    @Column() code: string;
    @ManyToOne(type => User) user: User;
}
// .......
    await connection.connect();

    const user = new User();
    user.name = "user1";

    const app = new Application();
    app.code = "code1";
    app.user = user;

    await connection.manager.save([user, app]);
```
user and app are automatically sorted in the correct topological order and will have the correct primary keys after save. If I describe my models using `EntitySchema`, then such functionality will be unavailable (save many related models in one operation with proper pk generation). Or I'm wrong?

**Comment by pleerock** [comment]
You are wrong. EntitySchema is just another way of schema definition.

**Comment by kirdk** [comment]
But in the case, if I want to support three DB engines I should define each entity four times (one as interface and three as constants of EntityShema?

**Comment by Kononnable** [comment]
If column types differs from each other, than yes. Take a look at https://github.com/typeorm/typeorm/tree/master/test/functional/entity-schema/basic

**Comment by johannesschobel** [comment]
@kirdk that should be true, yes.. But you would need to have 3 different decorators as well - because types may change across the databases..

however, if you have `EntitySchema` you may use the `SpreadOperator` (`...`) in order to generalize some basic fields, that apply to all databases..
