### ISSUE TITLE
future of mongodb driver

### ISSUE THREAD

**Issue by rustamwin** [typeorm/typeorm#3472]
I think about creating cursor builder e.g `SelectQueryBuilder`. What about this?

_Originally posted by @rustamwin in https://github.com/typeorm/typeorm/pull/3410#issuecomment-455123830_

**Comment by rustamwin** [comment]
@pleerock @vlapo

**Comment by rustamwin** [comment]
#3267

**Comment by pleerock** [comment]
please provide a detailed proposal on what you want to do. Mongodb driver itself already has all api it needs so I would like to avoid if its just a wrapper around it.

**Comment by rustamwin** [comment]
I'm reference some issues, them have feature, currently mongodb driver doesn't support latest mongodb features (relation, transaction, multi db, etc...)
I will try add listed above features

**Comment by chengjia0807** [comment]
> I'm reference some issues, them have feature, currently mongodb driver doesn't support latest mongodb features (relation, transaction, multi db, etc...)
> I will try add listed above features but it takes time.

Hey bro, any luck on this?

**Comment by vlapo** [comment]
@rustamwin do you have any detailed proposal about this? I think we have some basic functionality in typeorm right now and maybe it is enough. We do not have capacities to handle all databases in the universe.

**Comment by chengjia0807** [comment]
> @rustamwin do you have any detailed proposal about this? I think we have some basic functionality in typeorm right now and maybe it is enough. We do not have capacities to handle all databases in the universe.

Transaction is the life-changing feature of MongoDB. It brings up the database to a different level

**Comment by vlapo** [comment]
@chengjia0807 sure I understand. Feel free contribute :) We support transcations in relation databases. Check implementation, docs about this and try contribute.

IMHO support transactions is one of the bigger topic and we do not have capacity now. Thats reason why is mongo community supported only.
