### ISSUE TITLE
Slow batch operations with react native

### ISSUE THREAD

**Issue by NKlug** [typeorm/typeorm#3473]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
When calling e.g. `save(objects)`, where `objects` is an array using the react native backend, the whole operation takes extremely long (about 30s for 2500 objects). The reason for this is that the communication between react native's javascript runtime and the native platform.   
Typorm calls `executeSql` for every object individually, so there are multiple times the javascript runtime has to communicate with the native platform, which makes it quite slow. In order to avoid this, the `react-native-sqlite-storage` package (which is also used by typeorm) offers a function `sqlBatch`, with sends every query to the native platform at once (which makes it faster).   
As a solution one could just call `sqlBatch` on batch CRUD operations when using the react-native driver.

**Comment by maxammann** [comment]
This possibly also affects expo.

**Comment by pleerock** [comment]
TypeORM groups objects of same type into single `INSERT`, e.g. you should have one insert per 2500 objects lets say. Can you debug what exact queries take you so much time?

**Comment by maxammann** [comment]
I think typeorm does use BEGIN TRANSACTION and COMMIT but each insert is still a separate SQL query which is sent to react-native-sql-storage

**Comment by pleerock** [comment]
@maxammann it does optimize where its possible

**Comment by NKlug** [comment]
@pleerock If someone could give me some tips about which files would need to be changed to use the `sqlBatch` function for batch queries I'm willing to fix this and open a PR (if that's ok).

**Comment by mbret** [comment]
I gave a try myself and when trying to save an array of entity I have indeed one query (one native call) per insert. This is a total no go for us since we have a huge batch of data to save unfortunately.

**Comment by biaji** [comment]
The implement should be: ReactNativeQueryRunner.java

it only support executeSql interface.

**Comment by imnotjames** [comment]
This is pretty stale and we don't really have a path forward here.  I'm going to close it out.  If you have a more up to date case where this performance issue is seen please open a new issue with more information & a way to replicate.
