### ISSUE TITLE
I set dateStrings to true but datetime columns still returning in '2018-12-21T05:55:00.000Z' format

### ISSUE THREAD

**Issue by malexindigo** [typeorm/typeorm#3474]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] `0.1.19`

I set my typeorm connection with the following options:
```ts
{
  type: "mysql",
  synchronize: true,
  logging: false,
  cache: false,
  dateStrings: true,
  entities: [
    `${ __dirname }/../domain/*.${ process.env.NODE_ENV ? 'js' : 'ts' }`
  ],
  migrations: [
    `${ __dirname }/../migration/*.${ process.env.NODE_ENV ? 'js' : 'ts' }`
  ],
  cli: {
    migrationsDir: `${ __dirname }/../migration/`
  },
  host: [host]
  port: [port]
  username: [user]
  password: [password]
  database: [database]
}
```
also I have a entity with the next configuration:
```ts
import { Entity, Column, PrimaryGeneratedColumn, ManyToOne, JoinColumn, OneToMany } from 'typeorm';

@Entity()
export class Entertainment {

  @PrimaryGeneratedColumn({ type: "bigint" })
  id: number;

  @Column({default: "2000-01-01 00:00:00"})
  celebrationDate: Date;

  @Column({default: "2000-01-01 00:00:00"})
  doorOpening: Date;

  @Column({default: "2000-01-01 00:00:00"})
  saleStart: Date;

  @Column({default: "2000-01-01 00:00:00"})
  saleEnd: Date;
}
```
But when I query to this entity I get the dates with the format '2018-12-21T05:55:00.000Z' instead of the string, I set the dateStrings option to true but it is ignored.

**Comment by pleerock** [comment]
You specified version `0.1.19`. Its very very old, consider upgrading.

Regarding to your issue, date columns are always type of `Date`, why you should get a string? `default` is just a directive to database what DEFAULT value should be inserted into the database when you don't specify its values during insertion.

**Comment by malexindigo** [comment]
Thanks @pleerock, that was the problem, now with string type returns correctly.

**Comment by pleerock** [comment]
note that with string its type in database is a string too

**Comment by malexindigo** [comment]
Thanks @pleerock, so I can't set my column to datetime but return the mysql format "YYYY-MM-DD HH:mm"?

**Comment by pleerock** [comment]
datetime is a Date. If you need to get a string out of a date use appropriate methods of the Date object.

**Comment by StormKid** [comment]
I have a same problem about datetime formart. How to solve this problem

**Comment by pleerock** [comment]
I wrote solution above ^

**Comment by golubvladimir** [comment]
After I removed the datatype it worked.
