### ISSUE TITLE
Typings have't updated

### ISSUE THREAD

**Issue by barmaglot92** [typeorm/typeorm#3476]
As for issue #3460 

Unfortunately typings have't updated
```
    static find<T extends BaseEntity>(this: ObjectType<T>, conditions?: DeepPartial<T>): Promise<T[]>;
```

i think some troubles with build..

It actuals only for npm package, in sources all good

**Comment by pleerock** [comment]
yes because new version wasn't published yet. Wait for new npm release :)

**Comment by barmaglot92** [comment]
I thought it was in 0.2.22 ver, okay)

**Comment by barmaglot92** [comment]
This changes are under 0.2.12 tag.. seems this version must contains new type declarations
