### ISSUE TITLE
Question about relations

### ISSUE THREAD

**Issue by jest10820** [typeorm/typeorm#3477]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Description: I have a User entity and a Party entity. When I create a Party, I want to send an array of users that are invited to the party. Automatically, I want to have an association table with: partyId-userId-extraFields (for example if the user has confirmed the event).

Test repo: https://github.com/jest10820/typeorm-issues

I think this is easy to solve, but I'm lost right now, and I guess that I'm doing something wrong with relations. I have the next entities:

```ts
@Entity({ name: 'user' })
export class User {
    @PrimaryGeneratedColumn('uuid')
    id: string;
}

@Entity({ name: 'party' })
export class Party {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @OneToMany(type => Guests, guest => guest.party, {
    nullable: true,
    cascade: true,
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  })
  guests: User[] | null;
}

@Entity({ name: 'guests' })
@Index((relation: Guests) => [relation.user, relation.party], { unique: true })
export class Guests {
    @PrimaryGeneratedColumn('uuid')
    public id: string;

    @ManyToOne(type => User, user => user.id, {
      nullable: false,
      primary: true,
    })
    user: User;

    @ManyToOne(type => Party, party => party.id, {
      nullable: false,
      primary: true,
    })
    party: Party;

    @Column({
      default: false
    })
    confirmed: boolean;
}
```

I'd like to save a Party entity by sending a list of users, so the relation table is populated automatically:

```ts
    const user1 = new User();
    await manager.save(user1);
    const user2 = new User();
    await manager.save(user2);
    const user3 = new User();
    await manager.save(user3);

    const party = new Party();
    party.guests = [user1, user3];

    // I would expect this to create an entry
    // in Party and two entries in Guests
    const myParty = await manager.save(party);
    console.log(myParty);

    const myPartyGuests = await manager.findOne(Party, myParty.id, {
      relations: ['guests']
    });
    console.log(myPartyGuests);
```

And then, if the party is modified (and a user is removed from it), I would also like the relation table be updated automatically. In both cases, only Party table is updated, and no operations are performed on Guests table.

Any help is more than welcome. Thanks.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Diluka** [comment]
```ts
    @OneToMany(type => Guests, guest => guest.party, {
    nullable: true,
    cascade: true,
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  })
  guests: User[] | null;
```

what is the difference about `cascade`, `onDelete` and `onUpdate` in the options

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
