### ISSUE TITLE
All Error thrown by TypeOrm shall have a base type

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#3479]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Since the error thrown by `TypeOrm` has no unique base class, it is very difficult to accurately catch errors from `ORM` with the type-based `ExceptionFilter` of `nest.js`.

**Comment by pleerock** [comment]
errors in javascript are tricky and extending them is tricky as well. Note sure if should continue extending error classes.

**Comment by Diluka** [comment]
But there are already so many here. https://github.com/typeorm/typeorm/tree/master/src/error
I have read this https://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript
There are too many versions of browsers, but you still can support the target node first, right?

**Comment by Kononnable** [comment]
> Note sure if should continue extending error classes.

@pleerock Any other good way to achieve what we want without extending error classes?

**Comment by ruscon** [comment]
I agree that a base typeorm error class is needed

For `Axios` in our project, we have something like this

```typescript
import { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

// AxiosError - is a plain object :/
export class AxiosException<T = any> extends Error implements AxiosError {
    config: AxiosRequestConfig;
    code?: string;
    request?: any;
    response?: AxiosResponse<T>;
    isAxiosError: boolean;

    constructor(error: Partial<AxiosError>) {
        const responseMessage: string = error.response && error.response.data ? `Response: ${JSON.stringify(error.response.data)}` : '';
        const errorMessage: string = responseMessage ? `${error.message} ${responseMessage}` : error.message || '';

        super(errorMessage);

        Object.assign(this, error);
        this.message = errorMessage;

        this.name = error.constructor.name;
        this.code = error.code;

        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, AxiosException);
        }
    }
}

```

**Comment by DanielLoyAugmedix** [comment]
This is a fantastic idea. @pleerock can you explain why this would be a problem in Typescript? I'm a recent Java transplant so some of the Ts => Js issues don't make sense yet. But when I learned that there wasn't a super class of `TypescriptError` I was disappointed. It would make good error handling so much cleaner.

**Comment by jbjhjm** [comment]
> This is a fantastic idea. @pleerock can you explain why this would be a problem in Typescript? I'm a recent Java transplant so some of the Ts => Js issues don't make sense yet. But when I learned that there wasn't a super class of `TypescriptError` I was disappointed. It would make good error handling so much cleaner.

Did you mean TypeOrmError? TypescriptError doesn't seem to make any sense to me.

**Comment by fwoelffel** [comment]
If I'm not mistaken, the biggest issue here is that the Error object (like some other built-ins)  is breaking the prototype chain. See https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work

One way to implement a generic `TypeOrmError` would be:
```ts
class TypeOrmError extends Error {
    constructor(m: string) {
        super(m);
        // Set the prototype explicitly.
        Object.setPrototypeOf(this, TypeOrmError.prototype);
    }
}
```

**Comment by imnotjames** [comment]
Through some experimentation and with some testing I think the following will work:

```typescript
export abstract class TypeORMError extends Error {
    get name() {
        return this.constructor.name;
    }

    constructor(message?: string) {
        super(message);

        // restore prototype chain
        if (Object.setPrototypeOf) {
            Object.setPrototypeOf(this, new.target.prototype);
        }  else {
            (this as any).__proto__ = new.target.prototype;
        }
    }
}
```

**Comment by delucca** [comment]
No updates on this?
