### ISSUE TITLE
Stream for mongoDB

### ISSUE THREAD

**Issue by ShadabFaiz** [typeorm/typeorm#3480]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Since queryBuilder is not supported for the MongoDb. Is there any other way to stream the collection data in mongoDB? What other option do i have for getting large data (say 2M+).
I'm trying to crreate a csv file in nodejs containing collection data. But since its going to get large data, i  thinkin about stream those data. So how can i stream those data using typeorm?

**Comment by rustamwin** [comment]
@pleerock in MongoEntityManager don't yet, I guess @ShadabFaiz can use this following methods
`createEntityCursor`
`createCursor`

**Comment by ShadabFaiz** [comment]
@rustamwin  that worked. thanks
