### ISSUE TITLE
How to use where statement in findTrees method of Closure table?

### ISSUE THREAD

**Issue by kaimiyang** [typeorm/typeorm#3481]
**Issue type:**

[x] question

**Database system/driver:**
[x] `mysql` / `mariadb`

**TypeORM version:**

[x] `latest`
[x] `@next`

**How to use where statement in findTrees method of Closure table:**
```
const manager = getManager();
const trees = await manager.getTreeRepository(Category).findTrees();

//I want to add where statement in findTrees, just like this:
await manager.getTreeRepository(Category).findTrees({
  where: { uid: 1 }
})
```

Above it, how to do ?

**Comment by DaLiangLee** [comment]
same question... ohhh

**Comment by kyo8300** [comment]
same question

**Comment by girumasfaw** [comment]
same question

**Comment by Jood80** [comment]
same question

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
