### ISSUE TITLE
Best practices for import of large datasets

### ISSUE THREAD

**Issue by Shin--** [typeorm/typeorm#3483]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am importing data from csvs of up to 500k rows. Let's say I have a model named `Sample` that has some fields and a `ManyToMany` relation to `SampleRelation`, which also is created from a csv. My current approach is to first create the `SampleRelation` objects, get their ideas, create a `Sample` object with the same structure as the model, add an Array of `SampleRelation` to its `sampleRelations` property and then save it to the database. My `Sample` object would be in an `array` that I then iterate through and `await` with `Promise.all()`.

```
          Promise.all(sampleList.map(async (item: ISample) => {
            let exists = await connection.getRepository('sample')
                                          .count({where: {name: item.name}})
            if (!exists) {
              let newSampleRelations: ISampleRelation[] = []
              for (let sampleRelKey of item.sampleRelations) {
                sampleRelations.push(sampleRelationMap[sampleRelKey])
              }
              item.sampleRelations = newSampleRelations
              connection.getRepository('sample').save(item)
            }
          }))
```

This works well (besides being a bit slower than I would like to), unless the sampleList gets too large, at which point my App stops itself before running out of RAM.
What would be a better approach to save large amounts of data? I have also tried to not promisify the iteration, update all the `sampleRelations` but not save within the iteration but use `connection.getRepository('sample').save(sampleList)`. I am not sure if the performance has improved much there because I didn't check further since this lead to all `Samples` but no relations being saved.

**Comment by pleerock** [comment]
You need to use [relational query builder](http://typeorm.io/#/relational-query-builder).

**Comment by Shin--** [comment]
Ah, I have seen this before but didn't think that it could help me. This has lead me to to use the `insert()` function of of `createQueryBuilder` to add an array of new "sample" objects to my database. This works, but it loses the relations. I thought about using the relational query builder to then add the relations to me freshly created entries, but I would need the `id`s of the new objects. Unfortunately, the query builder only returns the `id` of the latest item for all of them. Here is a screenshot of what happens when I add 20 at once:

![image](https://user-images.githubusercontent.com/4537422/51633934-28df9a00-1f53-11e9-94d8-df91cdbf40db.png)

Could this be a bug?

Would this approach be good or am I missing something crucial to speed up the performance? I think I might have worded what I am doing not that well before, so I will try to explain my steps in case it isn't optimal:
- I parse a csv file
- I create objects of my items (here named `sample`) and save to which `sampleRelation`s they will have a relation
- I also save the values for my `sampleRelation`s and then insert those into the database after the parsing is completed
- After this, I map those relations to my `sample` items (as seen in my example) and save them to the database

**Comment by pleerock** [comment]
I don't tell you to use `insert`. Use relational query builder to insert your relations separately.

**Comment by Kononnable** [comment]
@Shin--  Did you resolve your issue?

**Comment by Shin--** [comment]
Not yet. I have some ideas but have delayed solving this for a later part of my project (in 1 or 2 weeks)

**Comment by vlapo** [comment]
Hey @Shin--. Did you have time for this?

**Comment by Shin--** [comment]
@vlapo Oh, sorry, I completely forget to update it. I ended up rewriting some of it and settled on using `save()` and passing a list:
```
while (itemList.length > 0) {
    await connection.getRepository('sample').save([...itemList.splice(0, 500)])
}
```
I had to limit it to 500 elements because of the size of parameters and contraints in sqlite. I never got to the speed I wanted but it ended up being "okay".

**Comment by vlapo** [comment]
Glad to hear you resolved your issue. 
Btw.: `save` method of repository have second argument with options and special `chunk` option. You can use it:
```ts
await connection.getRepository('sample').save([...itemList], { chunk: 500 });
```
and typeorm will split your data into chunks of size 500 and save.
