### ISSUE TITLE
don't start ORM with oracle DB.

### ISSUE THREAD

**Issue by mrfoe7** [typeorm/typeorm#3484]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, for everyone!
How set connection to oracle-db with typeorm?
My wrong config's file.

I want use typeorm with oracle-DB. But in documentation haven't ormconfig's file is not exist.
```json
{
    "type": "oracle",
    "host": "testhost",
    "username": "test",
    "password": "testpasswd",
    "synchronize": true,
    "logging": true,
    "entities": [
        "./entity/*.js"
    ],
    "migrations": [
        "./migration/*.js"
    ],
    "subscribers": [
        "./subscriber/*.js"
    ],
    "cli": {
        "entitiesDir": "./entity",
        "migrationsDir": "./migration",
        "subscribersDir": "./subscriber"
    }
}
```
I spend some time in Google and find this https://github.com/typeorm/typeorm/issues/2455.

I installed natice oracle db driver and checked this correct work.

Notice: i am use nodejs version 10.15.0 and only JS

**Comment by mrfoe7** [comment]
it is correct config: 

{
    "type": "oracle",
    "name": "oracle",
    "host": "testhost",
    "port": 1521,
    "username": "testuser",
    "sid": "testsid",
    "password": "testpasswd",
    "logging": false,
    "entities": [
        "./entity/*.js"
    ],
    "migrations": [
        "./migration/*.js"
    ],
    "subscribers": [
        "./subscriber/*.js"
    ],
    "cli": {
        "entitiesDir": "./entity",
        "migrationsDir": "./migration",
        "subscribersDir": "./subscriber"
    }
}

**Comment by vlapo** [comment]
@mrfoe7 So, did you resolve your problem by adding `sid`?

**Comment by mrfoe7** [comment]
@vlapo yes, but i deleted `synchronize` param, and this started

**Comment by mrfoe7** [comment]
@vlapo but if i use `synchonize` : `true` i am catch next error:
{ [Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor] errorNum: 12514, offset: 0 }

**Comment by vlapo** [comment]
Seem to not be typeorm problem:
https://stackoverflow.com/questions/10786782/ora-12514-tnslistener-does-not-currently-know-of-service-requested-in-connect-d
https://stackoverflow.com/questions/46914943/can-not-connect-ora-12514-tnslistener-does-not-currently-know-of-service-reque

**Comment by mrfoe7** [comment]
@vlapo Ths for help dude.
It is problem resolved by add row - "connectString" with "TNS Orcale options"

**Comment by geabenitez** [comment]
> @vlapo Ths for help dude.
> It is problem resolved by add row - "connectString" with "TNS Orcale options"

Hello @mrfoe7, is it possible for you to share the ormconfig file? I am trying to get this to work without success. thank you.

**Comment by mrfoe7** [comment]
@geabenitez Hi :) It is my ormconfig file.
{
    "type": "oracle",
    "host": $DB_HOST,
    "port":$DB_PORT,
    "username": $DB_USERNAME",
    "sid": $DB_SID,
    "password": $DB_PASSWORD,
    "logging": false,
    "connectString": "(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(Host = $DB_HOST)(Port =$DB_PORT)))(CONNECT_DATA =(sid =$DB_SID)(SERVER=dedicated)))"
}

P.S. @vlapo Don't forget check dependencies about https://github.com/oracle/node-oracledb and oracle client. i am use manual from this docs. https://oracle.github.io/node-oracledb/INSTALL.html#quickstart . Some time ago, i try install oracle client in docker container, but is not success.

Good luck :)
