### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by calebeaires** [typeorm/typeorm#3488]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When for some reason a param value is null or empty, typeorm create an infinit querie, running the query again and again. Why it does not throw an error

Code: 

```typescript

  private async credentials(sourceId) {
    const db = getConnection();
    return await db
      .query('select credentials from sources where sourceId = ?', [sourceId])
      .then(res => (res[0] ? res[0].credentials : {}));
  }

```

Here is the image of the infinite running query of typeorm. This query run and does not stop:

<img width="705" alt="screen shot 2019-01-22 at 18 34 00" src="https://user-images.githubusercontent.com/794195/51564231-ce244080-1e75-11e9-8a35-8fb863d65d78.png">

**Comment by pleerock** [comment]
it can't be typeorm's problem. Please make sure everything is right from your side.

**Comment by Kononnable** [comment]
@calebeaires 
Did you resolve your issue?

**Comment by calebeaires** [comment]
Yes, like you said. I were my coding!
