### ISSUE TITLE
json and jsonb comparison does not work

### ISSUE THREAD

**Issue by grin0c** [typeorm/typeorm#3496]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ 0.2.8] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
If we save such an object in the database:
```
[{"message": "", "attributeKey": "files", "level": "wrong"}]
```
then postgresql saves this object as:
```
[{"level": "wrong", "message": "", "attributeKey": "files"}]
```
The problem is here: https://github.com/typeorm/typeorm/blob/master/src/persistence/SubjectChangedColumnsComputer.ts#L80-L83

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
please provide more details including minimal entity code for reproduction.

**Comment by grin0c** [comment]
```
@Entity()
export class Post {
  @PrimaryGeneratedColumn()
  id: number

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date

  @Column({ type: 'jsonb', nullable: true })
  problems: object
}

const connection = await createConnection(connectionOptions)
const repository = connection.getRepository(Post)

const p = await repository.save(repository.create({ problems: [{ attributeKey: 'files', level: 'wrong', message: '' }] }))

await repository.save(p)
```
The second save method is to run update.

**Comment by pleerock** [comment]
> The problem is here: 

can you please explain why problem is in there? Json.stringify doesn't change properties order, right?

**Comment by grin0c** [comment]
The order of keys changes postgres when saves json.
<img width="925" alt="2019-01-24 10 48 06" src="https://user-images.githubusercontent.com/7963898/51663647-5ca8d700-1fc8-11e9-8c98-405b30f57cf4.png">

When save requests a model from the database, the keys in json come in a different order and are obtained:
```
JSON.stringify([{"message": "", "attributeKey": "files", "level": "wrong"}]) !== JSON.stringify([{"level": "wrong", "message": "", "attributeKey": "files"}])
```

**Comment by pleerock** [comment]
ah okay, problem is that comparison doesn't work properly. If you could describe it in details I could understand it more easily from the beginning. How do you suggest to make this comparison then?

**Comment by grin0c** [comment]
```
} else if (column.type === "json" || column.type === "jsonb") {
    if (OrmUtils.deepCompare(entityValue, databaseValue)) return;
}
```

**Comment by pleerock** [comment]
okay, PR it. Make sure to make it against all drivers.
