### ISSUE TITLE
mongodb如何实现复杂查询

### ISSUE THREAD

**Issue by yulintianxia** [typeorm/typeorm#3497]
我想用mongodb查询时间戳小于150000的数据，或者我想找出排序之后的第一条数据，mongodb没法createQueryBuilder，而且相关的文档也不太清楚

**Comment by vlapo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand  the problem. 

Also can you please translate your issue to English or work with an English speaking community member to create an issue in English? Thank you for understanding.
