### ISSUE TITLE
 ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

### ISSUE THREAD

**Issue by mrfoe7** [typeorm/typeorm#3498]
**Issue type:**

[ ] question
[ X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ X  ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, everyone!

I'm caught with this problem:

I use manual 'how to use typeorm with es6 in js' from this repository - https://github.com/typeorm/javascript-example/blob/master/src/app3-es6
But i'am offen take this mistake when do query `find()`

{ [Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor] errorNum: 12514, offset: 0 } what is mean.

My OS is Windows 10.

My source code:

//entity
const typeorm = require('typeorm');

module.exports = new c.EntitySchema{
  name: `${'system_config'.toUpperCase()}`,
  tableName: `${'system_config'.toUpperCase()}`,
  target: SYSTEM_CONFIG,
  columns: {
    ID: {
      primary: true,
      type: 'int',
      generated: true,
    },
    NAME: {
      type: 'varchar2',
    },
    VALUE: {
      type: 'varchar2',
    },
    ENABLE: {
      type: 'char',
    },
    CHANGE_TIME: {
      type: 'timestamp',
    },
    ADDED_TIME: {
      type: 'timestamp',
    },
  },
};

// model
class SYSTEM_CONFIG {
  constructor(
      id,
      name,
      value,
      enable,
      change_time,
      added_time
  ) {
    this.ID = id;
    this.NAME = name;
    this.VALUE = value;
    this.ENABLE = enable;
    this.CHANGE_TIME = change_time;
    this.ADDED_TIME = added_time;
  }
}

//used 
async () => {
  try {
    const connect = await db.getConnect();
    const postRepository = connect.getRepository(SYSTEM_CONFIG);
    const queryResult = await postRepository.find();
    console.log(queryResult);
    return queryResult;
  } catch (error) {
    console.log(error);
  }
}

**Comment by pleerock** [comment]
its oracle error, you need to seek oracle answer.

**Comment by mrfoe7** [comment]
@pleerock how to add tns in ormconfig?

**Comment by mrfoe7** [comment]
it is fix by add params in ormconfig:
"connectString": "(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(Host = myhost)(Port = 1521)))(CONNECT_DATA =(sid = mysid)(SERVER=dedicated)))"

**Comment by mrfoe7** [comment]
@pleerock please, close issue
