### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by yulintianxia** [typeorm/typeorm#3499]
Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.
   at new AlreadyHasActiveConnectionError
如何处理呀，我对一个数据库需要连接2次

**Comment by vlapo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand the problem.

Also can you please translate your issue to English or work with an English speaking community member to create an issue in English? Thank you for understanding.
