### ISSUE TITLE
Insert with options chunk Not work

### ISSUE THREAD

**Issue by LeandroDelaygue** [typeorm/typeorm#3502]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

 
According to the documentation, the way to implement multiple insertion is:

>  chunk: number - Breaks save execution into given number of chunks. For example, if you want to save 100.000 objects but you have issues with saving them, you can break them into 10 groups of 10.000 objects (by setting { chunk: 10 }) and save each group separately. This option is needed to perform very big insertions when you have issues with underlying driver parameter number limitation.
> reload: boolean - Flag to determine whether the entity that is being persisted should be reloaded during the persistence operation. It will work only on databases which does not support RETURNING / OUTPUT statement. Enabled by default.
> Example:
> // users contains array of User Entities
> userRepository.insert(users, {chunk: users.length / 1000});

But it does not work for me, it does not respect the save options.

**Comment by vlapo** [comment]
Duplicate https://github.com/typeorm/typeorm/issues/3417. Please try search in current issues first.
