### ISSUE TITLE
Find doesn't allow ordering by embedded entity properties

### ISSUE THREAD

**Issue by robbyemmert** [typeorm/typeorm#3508]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `^0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Ideally, I'd like to be able to order results by an embedded entity, the same way I can already specify WHERE parameters by embedded entities.

The following query is how I'd expect it to work, given the functionality `where` currently offers. But the following results in Typescript errors. Manually casting away the TS errors still results in undesired behavior, verifying that it's not just a typing issue.

```ts
const requireServiceType = {
            type: { id: search.serviceTypeId }
        }

const [results, totalItems] = await this.serviceRepository.findAndCount({
            where: [
                {
                    ...requireServiceType,
                    country: {
                        code: Like(`%${search.country}%`)
                    }
                },
                {
                    ...requireServiceType,
                    country: {
                        name: Like(`%${search.country}%`)
                    }
                }
            ],
            take: pageSettings.pageSize,
            skip: pageSettings.pageSize * indexPage,
            order: {
                country: {
                    code: 'ASC'
                }
            }
        })
```

The part that doesn't work is the `order` configuration. According the the TS definitions, only flat configuration is allowed:

```ts
{
    ...otherConfig,
    order: {
        country: 'ASC'
    }
}
```

But of course that doesn't work, since 'country' isn't a real column name, but the name of the embedded entity.

Manually casting away the TS errors and trying to directly reference the column also produces an error:
```ts
{
    ...otherConfig,
   order: {
                countryCode: 'ASC'
            }
}
```

The error produced:
```
Error: countryCode column was not found in the Service entity
```

To summarize, I think it would make sense to allow nested order configuration like so:
```ts
{
    order: {
                country: {
                    code: 'ASC'
                }
            }
}
```

For reference, here are my entity definitions:

```ts
export class Country extends BaseModel {
    @Column()
    name: string

    @Column({
        unique: true
    })
    code: string
}

@Entity()
export class Service extends BaseModel {
    @ManyToOne(type => ServiceType, serviceType => serviceType.services, {
        eager: true
    })
    type: ServiceType

    @Column(type => Country)
    country: Country

    @Column({
        type: 'text',
        default: ''
    })
    notes: string

    @Column({
        type: 'boolean',
        default: false
    })
    active: boolean
    //...a whole bunch more irrelevant fields
}

Thanks in advance!
```

**Comment by pleerock** [comment]
This feature will be available in 0.3.0 (its already in there in `@next`, you can test it)

**Comment by robbyemmert** [comment]
Awesome thanks!

**Comment by Nargonath** [comment]
Does it concern the query builder also? I'm trying to sort on a property of an embedded entity using query builder but I get a strange error so I was wondering.

**Comment by u8sand** [comment]
On `0.3.0-alpha.23`, when I try to use

```
...
order: {
  jsonb_field: {
    underlying_field: 'DESC'
  }
}
...
```

The resulting query simply does:

```
select jsonb_field from tbl order by jsonb_field asc;
```

It doesn't take into account the nested field at all. But using nested fields in `select` with dot notation seems to properly filter out the fields--can't it be done with order?

```
{
  select: ['jsonb_field.underlying_field'],
  order: { jsonb_field.underlying_field: 'DESC' }
}
```

**Comment by queses** [comment]
> Does it concern the query builder also? I'm trying to sort on a property of an embedded entity using query builder but I get a strange error so I was wondering.

As for current `next` (0.3.0-alpha.24) this solution works:
`.orderBy({ 'user.name.first': 'ASC' }`

**Comment by snolangps** [comment]
> > Does it concern the query builder also? I'm trying to sort on a property of an embedded entity using query builder but I get a strange error so I was wondering.
> 
> As for current `next` (0.3.0-alpha.24) this solution works:
> `.orderBy({ 'user.name.first': 'ASC' }`

Are you totally sure this works for nested related objects? This looks like the `first` column exists on the User entity, no?

**Comment by snolangps** [comment]
> > Does it concern the query builder also? I'm trying to sort on a property of an embedded entity using query builder but I get a strange error so I was wondering.
> 
> As for current `next` (0.3.0-alpha.24) this solution works:
> `.orderBy({ 'user.name.first': 'ASC' }`

Are you totally sure this works for nested related objects? This looks like the `first` column exists on the User entity, no?

**Comment by queses** [comment]
> Are you totally sure this works for nested related objects? This looks like the `first` column exists on the User entity, no?

Well this won't work with relations, like `@ManyToOne` but it works fine with embedded objects. So ordering query `.orderBy({ 'user.name.first': 'ASC' }` will work for following code:

```
class UserName {
  @Column() first: string
  @Column() last: string
}

@Entity()
class User {
  @PrimaryGeneratedColumn() readonly id: number
  @Column(type => UserName) name: UserName
}
```

**Comment by snolangps** [comment]
> Well this won't work with relations

I need to read titles better :(
You're right about embedded objects, I thought the problem was with entity relations, which some other issue led me here and I didn't even attempt to read the title... My bad.

**Comment by Firaenix** [comment]
Is 0.3.0-alpha ready enough for production?
I really need this feature.

**Comment by cfremgen** [comment]
> Is 0.3.0-alpha ready enough for production?
> I really need this feature.

`0.3.0-rc.19` is probably very close.

You can view available versions by running `npm view typeorm versions`

**Comment by queses** [comment]
> Is 0.3.0-alpha ready enough for production?

Actually in my project all versions starting with `typeorm@0.3.0-rc.10` and higher are throwing the same error
![image](https://user-images.githubusercontent.com/14962059/80114389-f16bfd00-859c-11ea-89f5-0ada83745445.png)

So i just using `rc.9` and it works pretty good and stable. When we will finish the development we're gonna push it in production

**Comment by roylee0704** [comment]
I understand it works for `QueryBuilder`, but does it work for `.find` yet? :)

**Comment by queses** [comment]
> I understand it works for `QueryBuilder`, but does it work for `.find` yet? :)

Yep, but it works in `next` branch
It can be installed by executing `npm i typeorm@0.3.0-rc.9` (rc-10 and greater doesn't work for my project)
I did it because I needed an ability to sort by embedded entities properties. I use it in production and I never met any probles. But I also would not recommend to do it unless you really need it. The point is that the branch `next` seems to be abandoned.

**Comment by rafaturtle** [comment]
I've tried to use 0.30 to get the sorting working but it broke how you define a custom repository. Can't find any documentation or test to work out how to do this. Currently I'm extending the class Repository, and you can't do that anymore with 0.30
