### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by yulintianxia** [typeorm/typeorm#3510]
这是第一个方法，
public  checkNode(timeout: number): Promise<any> {
        /**
         * query of sks_node all edge node
         */
       return  createConnection(options).then(async connection => {
       let sksRepository = await connection.getRepository(SksNode); // or connection.getMongoManager
       let data =  await sksRepository.find({
            where: {
                last_opter: {$lt: (new Date().getTime() - (timeout * 60 * 1000))},
              },
        });
          return data;
        }).catch(error =>  this.logger.error(error));
      }
第二个方法：
public async releaseNode(node: any): Promise<any> { 
  if (node && node.ip) {
        let ip = await this.tools.ObserPromise<string>((r, j) => {

       createConnection(options).then(async connection => {
                try {
                     let sksnodesRepository =  await connection.getRepository(SksNode); 
                    let data =  await sksnodesRepository.remove(node);
                    this.logger.info('data', data);
                    r(node.ip);
                 }catch (error) {
                     j(error);
                 }
     } 
}
第二个方法连接的时候有错误    createConnection(options).then(async connection => { }有错误，
错误如下,AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.
我怎么处理在默认的连接里面，在其他函数里面建立连接，来使用对应的方法

**Comment by pleerock** [comment]
I'm sorry but we do not speak and understand Chinese.
