### ISSUE TITLE
Best way to convert exec SP raw results to Entities ?

### ISSUE THREAD

**Issue by kktos** [typeorm/typeorm#3513]
**Issue type:**

[X ] question

**Database system/driver:**

[ X] `mssql`

**TypeORM version:**

[ X] `latest`

**Steps to reproduce or a small repository showing the problem:**

Hi,
I have some Stored Procedure to call that return rows of an already defined entity.
So far, I have no way to tell TypeORM that the result will be a list of this entity so I tried to transform it like:
```ts
// Execute SP then bind each row with given type
function execSP<Entity>(sql: string, entityClass: ObjectType<Entity>): Promise<Entity[]> {
	const repo= getRepository(entityClass);
	const meta= repo.manager.connection.getMetadata(entityClass);
	const transfomer= new PlainObjectToDatabaseEntityTransformer(repo.manager);

	return repo.query(sql).then(async (rows: any) => {
		await Promise.all(
			rows.map( async (row: any) => await transfomer.transform(row, meta))
		);
		return rows;
	});

}

// and how to use it:
const customerList= execSP("execute GetAllCustomers", Customer);
```
~~It's only a test so I'm keeping only the first row.~~
Is this the best way to do it or is there a better ?
TIA,
/Thierry

**Comment by pleerock** [comment]
I think there is no other way currently. Use it if it works for you.

**Comment by kktos** [comment]
There's something I've noticed while at it:
```ts
    @PrimaryGeneratedColumn({name: "id_customer"})
	public id: number;
```
The column name, in the DB, is "id_customer" and I want to have a simple "id" in the code.
But it seems it isn't working with this method (PlainObjectToDatabaseEntityTransformer), it seems it didn't transform id_customer to id.
Did I miss something ?
Thx

**Comment by pleerock** [comment]
I can't tell you this way why its not working. You need to debug and figure this out.
