### ISSUE TITLE
where inside find, findOne, findXXX not working

### ISSUE THREAD

**Issue by MetaiR** [typeorm/typeorm#3515]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Entity:
```
@Entity({ name: 'user' })
export class User {
    @PrimaryGeneratedColumn({ name: 'user_id' })
    private _id: number = undefined;
    @Column({ name: 'user_username' })
    private _username: string = undefined;
    @Column({ name: 'user_password' })
    private _password: string = undefined;
    @Column({ name: 'user_is_admin' })
    private _isAdmin: boolean = undefined;
    @Column({ name: 'user_insert_access' })
    private _insertAccess: boolean = undefined;
    @Column({ name: 'user_update_access' })
    private _updateAccess: boolean = undefined;
    @Column({ name: 'user_deleted' })
    private _deleted: boolean = undefined;
    @Column({ name: 'user_lastmodify' })
    private _lastModify: Date = undefined;
    @OneToOne(() => Person, { eager: true })
    @JoinColumn({ name: 'user_person' })
    private _person: Person = undefined;

    // extra
    private _noneEncryptedPassword: string;
}
```

what did I do
```
login(un: string) // un is inputed username
{
        const conn = getConnection();
        conn.getRepository(User).findOne({username: un}).then(
            result => console.log(result)
        );
}
```
there is just one record in the database and it's username is equal to `seyed` so if there is a wrong username inputted I must see null or undefined on my console but instead, I see the DB record.

I also tried:
`conn.getRepository(User).findOne({where: {username: un}})`
`conn.getRepository(User).findOne({where: {user_username: un}})`
`conn.getRepository(User).findOne({where: {'user_username': un}})`
`conn.getRepository(User).findOne({user_username: un})`

none of them working

where did I go wrong?

**Comment by pleerock** [comment]
it should be `conn.getRepository(User).findOne({where: {_username: un}})`

**Comment by MetaiR** [comment]
I didn't expect it even it now seems to be very reasonable. any way, thanks, u really saved me
