### ISSUE TITLE
Is there a way to get the last item from an entity?

### ISSUE THREAD

**Issue by JClackett** [typeorm/typeorm#3516]
I wana be able to get the last time when querying an entity, like rails' active record's .last

Is there something in typeorm like this, i can't find it in the docs

**Issue type:**

[ ] question
[ ] bug report
[-] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[-] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[-] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
I guess you need query entity and order it by id desc?

**Comment by Zhaorachi** [comment]
You could get the latest record just with findOne query
