### ISSUE TITLE
mongodb: .save() method does not set _id column value

### ISSUE THREAD

**Issue by encobrain** [typeorm/typeorm#3517]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
@Entity()
class EntityClass {
    @ObjectIdColumn()
    _id: ObjectId;

    @Column()
    name: string;
}

let ent = new EntityClass();
ent.name = "abc";

await connection.mongoManager.save(ent);

console.log(ent._id); // inserts new document but does not set _id. _id is undefined
```

**Comment by pleerock** [comment]
@rustamwin

**Comment by vlapo** [comment]
Sry guys. I did not realize possibility of property name `_id`. Fix is coming in next release.
