### ISSUE TITLE
Chunk on save has strange behavior in mssql

### ISSUE THREAD

**Issue by victorschinaider** [typeorm/typeorm#3518]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In documentation, we've:

> For example, if you want to save 100.000 objects but you have issues with saving them, you can break them into 10 groups of 10.000 objects (by setting { chunk: 10 }) and save each group separately. 

But it isn't happening in some drivers. First, i have no ideia how to create failure test cases for something like this, so i've used a typeorm example project, and i'll try to reproduce here. 

Here is the code:

```typescript
    const user = new User();
    user.firstName = "Timber";
    user.lastName = "Saw";
    user.age = 25;

    const user2 = new User();
    user2.firstName = "Timber";
    user2.lastName = "Saw";
    user2.age = 25;

    const user3 = new User();
    user3.firstName = "Timber";
    user3.lastName = "Saw";
    user3.age = 25;

    const user4 = new User();
    user4.firstName = "Timber";
    user4.lastName = "Saw";
    user4.age = 25;

    const user5 = new User();
    user5.firstName = "Timber";
    user5.lastName = "Saw";
    user5.age = 25;

    const user6 = new User();
    user6.firstName = "Timber";
    user6.lastName = "Saw";
    user6.age = 25;

    await connection.manager.save([user, user2, user3], { chunk: 3 });
    await connection.manager.save([user4, user5, user6], { chunk: 1 });
```

Like documentation, we can understand `chunks` as `groups`. So in **first case** save, we need 3 groups (in this case, 3 insert queries), and in **second case** save, we need only one insert query (one group)

In `mssql` driver, the generated query was: 

```sql
query: COMMIT
query: BEGIN TRANSACTION
query: INSERT INTO "user"("firstName", "lastName", "age") OUTPUT INSERTED."id" VALUES (@0, @1, @2), (@3, @4, @5), (@6, @7, @8) -- PARAMETERS: [{"value":"Timber","type":"nvarchar","params":[]},{"value":"Saw","type":"nvarchar","params":[]},{"value":25,"type":"int","params":[]},{"value":"Timber","type":"nvarchar","params":[]},{"value":"Saw","type":"nvarchar","params":[]},{"value":25,"type":"int","params":[]},{"value":"Timber","type":"nvarchar","params":[]},{"value":"Saw","type":"nvarchar","params":[]},{"value":25,"type":"int","params":[]}]
query: COMMIT
query: BEGIN TRANSACTION
query: INSERT INTO "user"("firstName", "lastName", "age") OUTPUT INSERTED."id" VALUES (@0, @1, @2) -- PARAMETERS: [{"value":"Timber","type":"nvarchar","params":[]},{"value":"Saw","type":"nvarchar","params":[]},{"value":25,"type":"int","params":[]}]
query: INSERT INTO "user"("firstName", "lastName", "age") OUTPUT INSERTED."id" VALUES (@0, @1, @2) -- PARAMETERS: [{"value":"Timber","type":"nvarchar","params":[]},{"value":"Saw","type":"nvarchar","params":[]},{"value":25,"type":"int","params":[]}]
query: INSERT INTO "user"("firstName", "lastName", "age") OUTPUT INSERTED."id" VALUES (@0, @1, @2) -- PARAMETERS: [{"value":"Timber","type":"nvarchar","params":[]},{"value":"Saw","type":"nvarchar","params":[]},{"value":25,"type":"int","params":[]}]
query: COMMIT
```

The concept is changed! In queries, `chunks` means number of `entities` per query. So i ask, what is wrong? Documentation or code?

Other question, how to create tests to verify queries generated by save? How can we access the query after operation save is executed in typeorm?

**Comment by vlapo** [comment]
You are right. Documentation for `chunk` option is wrong. Number in this option mean "number of entities in one chunk group".

> But it isn't happening in some drivers.

In what drivers is this not happening?

**Comment by victorschinaider** [comment]
Well, i don't know if there is other drivers with the same behaviorismo, but i tested with sqllite and MySQL, but generated queries aren't equal. For SqlLite and MySQL don't care if there is chunk or not, it generates onde query per entity in transaction.

**Comment by vlapo** [comment]
Sure. I just realized what is problem with mysql and sqlite. They are not supporting returning statement so we do not know what values are inserted if we insert in batch. In `save` method we need to return newly inserted records so for this limitation we need to insert records one by one. This should definitely documented.

From code comment:

> However there are some limitations with bulk insertions of data into tables with generated (increment) columns in some drivers. Some drivers like mysql and sqlite does not support returning multiple generated columns after insertion and can only return a single generated column value, that's why its not possible to do bulk insertion, because it breaks insertion result's generatedMap and leads to problems when this subject is used in other subjects saves. That's why we only support bulking in junction tables for those drivers.
> Other drivers like postgres and sql server support RETURNING / OUTPUT statement which allows to return generated id for each inserted row, that's why bulk insertion is not limited to junction tables in there.

**Comment by pleerock** [comment]
Maybe I wrongly described my thoughts, feel free to update documentation. Written here behaviour is expected.
