### ISSUE TITLE
我本来填的是别的地址，为什么总是读127.0.0.1的redis

### ISSUE THREAD

**Issue by zf329398320** [typeorm/typeorm#3519]
0|xxx | Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
0|xxx |     at Object._errnoException (util.js:992:11)
0|xxx |     at _exceptionWithHostPort (util.js:1014:20)
0|xxx |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

**Comment by vlapo** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand the problem. Please fill our issue template and provide as much as possible information.

Also we are using English to communicate in this project. Thank you for understanding.
