### ISSUE TITLE
Error when trying to set Many to Many lazy relation Promise.resolve

### ISSUE THREAD

**Issue by breytex** [typeorm/typeorm#3524]
**Issue type:**

[?] question
[?] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.x.x` (or put your version here): 0.2.11

**Steps to reproduce or a small repository showing the problem:**
Hi there,

I get 
```
_1  | TypeError: Cannot read property 'find' of undefined
backend_1  |     at /src/node_modules/typeorm/persistence/subject-builder/ManyToManySubjectBuilder.js:127:73
backend_1  |     at Array.forEach (<anonymous>)
backend_1  |     at ManyToManySubjectBuilder.buildForSubjectRelation (/src/node_modules/typeorm/persistence/subject-builder/ManyToManySubjectBuilder.js:99:25)
backend_1  |     at /src/node_modules/typeorm/persistence/subject-builder/ManyToManySubjectBuilder.js:38:23
backend_1  |     at Array.forEach (<anonymous>)
backend_1  |     at /src/node_modules/typeorm/persistence/subject-builder/ManyToManySubjectBuilder.js:34:50
backend_1  |     at Array.forEach (<anonymous>)
backend_1  |     at ManyToManySubjectBuilder.build (/src/node_modules/typeorm/persistence/subject-builder/ManyToManySubjectBuilder.js:29:23)
backend_1  |     at EntityPersistExecutor.<anonymous> (/src/node_modules/typeorm/persistence/EntityPersistExecutor.js:101:115)
backend_1  |     at step (/src/node_modules/tslib/tslib.js:133:27)
```

when I try to set a Many to Many relationship.

Here is my setup (using `type-graphql` for generating a graphql api, thats where the `@Field` decorators come from):

User.ts
```typescript
@ObjectType()
@Entity()
export class User extends MyEntity {
    @Field()
    @Column()
    @IsEmail()
    email: string

    @ManyToMany(type => Project, project => project.userAccess)
    projectAccess: Promise<Project[]>
}
```

Project.ts
```typescript
@ObjectType()
@Entity()
export class Project extends OwnerEntity {
    @Field()
    @Column()
    title: string
    @ManyToMany(type => User, user => user.projectAccess)
    @JoinTable()
    userAccess: Promise<User[]>
}
```

Resolver.ts
```typescript
    @Authorized()
    @Mutation(returns => Boolean)
    async grantProjectAccessByEmail(@Arg("projectid") id: string, @Arg("email") email: string, @Ctx() { user }: MyContext) {
        const project = await Project.findOneOrFail({ id, user })
        const invitee = await User.findOneOrFail({ email })
        project.userAccess = Promise.resolve([invitee])
        await project.save()
        return true
    }
}
```

the line `project.userAccess = Promise.resolve([invitee])` triggers the error message.
When I uncomment it, the error is gone. Also, `project` and `invitee` are not null. Otherwise "findOneOrFail" would throw an exception, which is not the case.

I followed
https://github.com/typeorm/typeorm/blob/master/docs/eager-and-lazy-relations.md
to set up the lazy many-to-many relation and tried to figure out the error message my self at
https://github.com/typeorm/typeorm/blob/master/src/persistence/subject-builder/ManyToManySubjectBuilder.ts#L127
but I dont know what possibly could trigger that error :(

I have also tried:
- Setting the relation from the other way round:
```typescript
        invitee.projectAccess = Promise.resolve([project])
        await invitee.save()
```

- usung PromiseUtils
```typescript
        invitee.projectAccess = PromiseUtils.create([project])
        await invitee.save()
```

both result in the same error.
Any advice?

**Comment by MatheusKonradt** [comment]
Hi @breytex, 
I ran into a similar problem. Turns out the problem is that you are required to load all the entity relations before updating it.
If you don't want to load all the relations there's a way around. Update the entity using the code below:
`
import { getConnection } from 'typeorm';

...

await getConnection()
      .createQueryBuilder()
      .relation(Project, 'userAccess')
      .of(project)
      .add(invitee);
`

If you don't want to have duplicate relations, you can use the code below (it works like an "INSERT IGNORE" for unique indexes)
`
import { getConnection } from 'typeorm';

...

await getConnection()
      .createQueryBuilder()
      .relation(Project, 'userAccess')
      .of(project)
      .addAndRemove(invitee, invitee);
`

**Comment by breytex** [comment]
Works like charm.
Thank you very much, @MatheusKonradt!

**Comment by Kononnable** [comment]
Looks like issue was resolved.
