### ISSUE TITLE
Is it possible to filter entities by foreign key with repository.find()?

### ISSUE THREAD

**Issue by vimmerru** [typeorm/typeorm#3525]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, i use lazy loading and have for example the following entities:

```
@Entity()
export class Cat {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  name!: string;

  @ManyToOne(type => Color)
  color!: Promise<Color>;
}

@Entity()
@Unique(['name'])
export class Color {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  name!: string;
}
```

I want to select all cats with specific color may be with additional filetering and sorting. Is it possible to get all cats with specific color with `catRepositery.find()`? Corresponded  sql query will be just `select * from cats where colorId=:colorId`.

Unfortunately I can't find how to do filtering by foreign keys in documentation.

**Comment by keenondrums** [comment]
@vimmerru take a look at http://typeorm.io/#/relations-faq/how-to-use-relation-id-without-joining-relation

I figure then it would look like this
```ts
@Entity()
export class Cat {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  name!: string;

  @ManyToOne(type => Color)
  color!: Promise<Color>;

  @Column({ type: 'int', nullable: true })
  colorId?: number | null
}

@Entity()
@Unique(['name'])
export class Color {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  name!: string;
}

// in your service
const colorId = 111
const cats = await catsRepository.find({ where: { colorId } })
```

**Comment by vimmerru** [comment]
@keenondrums Thanks for the answer! It causes one additional question. If i have exposed foreighKeys as dedicated columns what is the correct way to create entities?

```typescript
catRepo.create({
  name: 'Cat name',
  colorId,
})
```

or 

```typescript
catRepo.create({
  name: 'Cat name',
  color: Promise.resolve(color),
})
```
or both will work?

**Comment by keenondrums** [comment]
@vimmerru as far as I can remember both are gonna work if you're not doing cascade creates, i.e. you're not trying to create a new color while creating a a new cat.

**Comment by Kononnable** [comment]
Looks like issue was resolved.
