### ISSUE TITLE
Getting count of duplicates from query

### ISSUE THREAD

**Issue by Murahnus** [typeorm/typeorm#3532]
[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**
[X] `sqlite`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Assuming I have an Entity `Category` and `Photo` and `Photographer`

```
@Entity()
export class Category {
  @PrimaryGeneratedColumn()
  id: number

  @OneToMany(type => Photo, photo => photo.category)
  @JoinTable()
  photos: Photo[]
}
```

`Photo` has a relation to `Category` and `Photo` also has a relation to `Photographer`. Now I would want to get all the categories for Photos taken by a specific Photographer, to stay close to the examples.

```
connection.getRepository('category')
    .createQueryBuilder('category').select('category')
    .leftJoin('category.photos', 'photos')
    .where('photos.photographerId = :photographerId', {photographerId})
    .getMany()

```
This would return me all the categories, but I am also interested by how often each category has been found. Let's say there would be 100 photos, each has a category, and it would return me 20 categories as many are duplicates. How would I also find out if "category 1" has 10 relations to the photos?

**Comment by Kononnable** [comment]
If you work with query builder you need to think of the sql query you want typeorm to generate. How would it look like? What is the difference between your current generated query and desired one?
I think you're looking for group by and count.

**Comment by Kononnable** [comment]
Closing as no response from the author.
