### ISSUE TITLE
Sync only works once for enums on entities with capital letters in entity name

### ISSUE THREAD

**Issue by onionhammer** [typeorm/typeorm#3536]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Create a column of type enum array, sync the database, then try to sync it again

Example

```ts
@Column("enum", { enum: AccountPermission, array: true, default: '{}' })
accountPermission: AccountPermission[]
```

When I run typeorm schema:sync on an empty database it works, when I run it again it crashes with error

`type "pcc._roles_accountpermission_enum" does not exist`

It seems to be adding a leading `_` before the type name in one spot but not another; in the database the type is `Roles_accountpermission_enum`

**Comment by onionhammer** [comment]
Additional notes

1. This does not only affect arrays

2. This only seems to fail if your `@Entity()` name has capital letters in it; such as "Roles" in the above example.

**Comment by nikolovjd** [comment]
I have a similar issue, however for me the issue appears if the column name in the db has an underscore.

**Comment by onionhammer** [comment]
Hey @vlapo what was the name of the \@Entity you used? I can try to create a failing test tomorrow

**Comment by vlapo** [comment]
This is entity and enum definition:
```typescript
export enum AccountPermission {
    Thing1 = 1,
    Thing2 = 4,
    Thing3 = 3,
    Thing4 = 2
}

@Entity("Roles")
export class Roles {

    @PrimaryGeneratedColumn()
    id: string;

    @Column("enum", { enum: AccountPermission, array: true, default: '{}' })
    accountPermission: AccountPermission[];
}
```
Are you sure you are using latest version from npm?

**Comment by vlapo** [comment]
Ou sry boys! I see error now. Had a drop schema setting enabled from previous test. Will check this later today. 🙌

**Comment by OLDIN** [comment]
I have a similar problem:
Error: `type "public.customfield_type_enum" does not exist`
My entity name: `customField`
My synchronization and migrations do not work.

The name is transformed to lower case. После чего я получаю ошибку что `type "public.customfield_type_enum" does not exist`.

I suspect there are problems with the default naming strategy. But I'm not sure.

**Comment by romain-gilliotte** [comment]
@AlexMesser 

This patch in combination with mine (https://github.com/typeorm/typeorm/issues/3792) is causing typeorm migration tool to crash again:

```
{ QueryFailedError: type "transaction.detail_type_enum" does not exist
    at new QueryFailedError (/home/mclarsen/Projects/compass/core-services/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/home/mclarsen/Projects/compass/core-services/src/driver/postgres/PostgresQueryRunner.ts:176:30)
    at Query.handleError (/home/mclarsen/Projects/compass/core-services/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/home/mclarsen/Projects/compass/core-services/node_modules/pg/lib/client.js:160:17)
    at Connection.emit (events.js:189:13)
    at Connection.EventEmitter.emit (domain.js:441:20)
    at Socket.<anonymous> (/home/mclarsen/Projects/compass/core-services/node_modules/pg/lib/connection.js:125:12)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
```

My patch corrected the missing quotes in the driver that were causing the crash when uppercase letters existed in enums names.

This one is lowercasing all enum names so that it works without properly quoting the queries.

Using both patches at the time cause typeorm to both lowercase and quote the enum type, which contains uppercase letters, causing the same crash again.

Both solutions are OK, need to choose only one!
