### ISSUE TITLE
ioredis/cluster 2nd(options) parameter support

### ISSUE THREAD

**Issue by scvgoe** [typeorm/typeorm#3538]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Question**
Hi, I appreciate your support for ioredis/cluster.

Actually, ioredis.Cluster constructor allow two parameters (startupNodes and options).
You can check them [here](https://github.com/luin/ioredis/blob/master/API.md#new-clusterstartupnodes-options)

But I cannot inject 2nd parameter (options) to [here](https://github.com/typeorm/typeorm/pull/3364/files#diff-7ef1785809892325abcbdb5d564dce09R64).

Do you have any plan to fix this problem?

**Comment by vlapo** [comment]
`ioredis` and `ioredis-cluster` caches were thankfully provided by @HussainAliAkbar and @ignacioblit. Could you please check this issue?

Also feel free to contribute.

**Comment by Kononnable** [comment]
I think this issue can be closed now since, PR was merged.
