### ISSUE TITLE
ColumnTypeUndefinedError although emitDecoratorMetadata is enabled

### ISSUE THREAD

**Issue by ibrahimduran** [typeorm/typeorm#354]
Stacktrace:
```
C:\Users\ibrah\Desktop\foo\bar\node_modules\typeorm\decorator\columns\Column.js:36
            throw new ColumnTypeUndefinedError_1.ColumnTypeUndefinedError(object, propertyName);
            ^

ColumnTypeUndefinedError: Column type for Job#name is not defined or cannot be guessed. Try to implicitly provide a column type to @Column decorator.
    at new ColumnTypeUndefinedError (C:\Users\ibrah\Desktop\foo\bar\node_modules\typeorm\decorator\error\ColumnTypeUndefinedError.js:10:28)
    at C:\Users\ibrah\Desktop\foo\bar\node_modules\typeorm\decorator\columns\Column.js:36:19
    at __decorate (C:\Users\ibrah\Desktop\foo\bar\build\api\models\job.js:5:110)
    at Object.<anonymous> (C:\Users\ibrah\Desktop\foo\bar\build\api\models\job.js:18:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

Config:
```json
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es6",
		"noImplicitAny": false,
		"sourceMap": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"outDir": "build"
	},
	"include": ["src/**/*"]
}
```
Source and reproduced js files are [here](https://gist.github.com/ibrahimduran/56f04d358a3256ce2fefb47badf6fa98).

typeorm v0.0.9

**Comment by pleerock** [comment]
Did you import reflect-metadata in your app before everything else?

**Comment by ibrahimduran** [comment]
No, sorry looks like I forgot to add that. Thank you.

**Comment by Cyral** [comment]
Might be worth adding "Make sure reflect-metadata is installed." or something to that error message.

**Comment by pleerock** [comment]
@Cyral but its not only about reflect-metadata. In the case if reflect-metadata is installed but it cannot guess its type - its the same issue.

**Comment by Eileen0917** [comment]
hi @pleerock ,

did you solve this problem?
I am facing same question now.
I already set `emitDecoratorMetadata: true` in tsconfig and `import "reflect-metadata"` on the top of my main.ts file, but this error still occur.
am I missing out something else?

thanks!

**Comment by Vienkk1010** [comment]
In file tsconfig.json add line code above:
"emitDecoratorMetadata": true

**Comment by gaurav341** [comment]
@Column() must set a type,like  @Column('text',{nullable:true})
