### ISSUE TITLE
addSelect with join no result

### ISSUE THREAD

**Issue by webmobiles** [typeorm/typeorm#3550]
**Issue type:**

[x ] bug report

**Database system/driver:**

[x ] `postgres`

**TypeORM version:**

[x ] `latest`

**Steps to reproduce or a small repository showing the problem:**
it's really crazy, a simple count from a left join table is very hard to do it, sometimes some addSelect simple give no column, but execute the sql internally, but no display values:

example:
no deal_count column is added on the result:

```
const organizations = await getConnection()
  .getRepository(Organization)
  .createQueryBuilder('organization')
  .addSelect(
    '(SELECT COUNT(*) FROM deal WHERE deal.organization_id = organization.id) AS deal_count'
  )
  .where('organization.id=700')
  .orderBy('organization.id', 'DESC')
  .getMany();
```

I get all fields from Organization, but not the field  'deal_count',  on the log postgress is executing the sql, so  i can get the column on the query tool:

`SELECT "organization"."id" AS "organization_id", ..., (SELECT COUNT(*) FROM deal WHERE deal.organization_id = "organization"."id") AS deal_count FROM "organization" "organization" WHERE "organization"."id"=700 ORDER BY "organization"."id" DESC`

**Comment by vlapo** [comment]
`deal_count` do not exists in `Organization` entity. You have to use `getRawMany()` or `getRawAndEntities()`. Check http://typeorm.io/#/select-query-builder/getting-raw-results

**Comment by webmobiles** [comment]
thanks @vlapo, but how i can define a count column in Organization entity?

**Comment by vlapo** [comment]
I think you are looking for this feature https://github.com/typeorm/typeorm/issues/296

**Comment by Kononnable** [comment]
Looks like issue was resolved.
