### ISSUE TITLE
How to select appropriate column from  left join table

### ISSUE THREAD

**Issue by vladmelnikov** [typeorm/typeorm#3552]
![image](https://user-images.githubusercontent.com/13378944/52069010-f5be8b80-258e-11e9-978b-66e75dd8c7de.png)

I cant get columns from joined tables it always returns empty array

i am using nestjs/typeorm module but it is based on typeorm 0.2.7

**Comment by vladmelnikov** [comment]
but i if i use getRawMany instead of getMany it works as expected

**Comment by vlapo** [comment]
`getMany()` method map results from query builder into entity and you do not have defined any `cv_type.value` property in your entity class. But i think you are searching for `leftJointAndMapOne`. More info here http://typeorm.io/#/select-query-builder/joining-and-mapping-functionality
