### ISSUE TITLE
 Mongodb database encryption

### ISSUE THREAD

**Issue by yulintianxia** [typeorm/typeorm#3553]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

MongoError: not authorized on sshdb to execute command

**Comment by rmainseas** [comment]
Solved it: I was using the `username`/`password` fields to connect to mongo in addition to the `url` field. I moved my username and password into the `url` field(whilst making sure my password didn't contain any unescaped at symbols) and it worked fine.

```js
{
    url: `mongodb://${SOURCE_DB_USERNAME}:${SOURCE_DB_PASSWORD}@${SOURCE_DB_HOST}:${SOURCE_DB_PORT}/${SOURCE_DB_DATABASE}`,
    // ... Other config stuff here
}
```

**Comment by imnotjames** [comment]
Solution is above I I'll be closing this out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
