### ISSUE TITLE
Extend sqljs driver with localforage lib for asynchronous save and load operations

### ISSUE THREAD

**Issue by tstoppe89** [typeorm/typeorm#3554]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Description**

Hey guys,
we are currently running into performance problems with the sql.js library in the browser, because of it's synchron (and blocking) save and load operations of the whole database. In several ionic & angular apps the initialization takes 3 - 9 seconds and freezes the application in this time, because of the local storage usage. We also tested your sql.js driver solution by replacing the localstorage operations with localforage (https://github.com/localForage/localForage), which is using the non-blocking asynchronous indexedDB - but also as key-value store, like the local storage is doing. By replacing it, the app can initialize the database asynchronously in the background while starting (or displaying a loading screen) without freezing.

Our fork & the specific branch: https://github.com/ApinautenGmbH/typeorm/tree/driver-sqljs-localforage

I've already started working on this extension by adding another connection option to the `SqljsConnectionOptions` like:

```
    /**
     * Enables the usage of the localforage library to save & load the database asynchronously from the
     * indexedDB instead of using the synchron local storage methods in a browser environment.
     */
    readonly useLocalforage?: boolean;
```

in the SqljsDriver.ts i'm doing soemthing like this:
```
    if (this.options.useLocalforage) {
        if (window.localforage) {
            await window.localforage.setItem(path, JSON.stringify(databaseArray));
        } else {
            throw new Error(`localforage is not defined - please import localforage.js into your site`);
        }
    } else {
        PlatformTools.getGlobalVariable().localStorage.setItem(path, JSON.stringify(databaseArray));
    }
```

I really would like to write tests and searched browser tests for the sqljs - are there some browser tests in typeorm? Or how do you test the sqljs browser-version? 
I could also set up an ionic test project if this would help.

P.S.: I really like your library and your work here!
P.S.S: We also would like to implement an own driver for indexedDB (in the future), because we are thinking, that this would give those browser application another performance boost. We also saw the #2048 issue

**Comment by Kononnable** [comment]
Unfortunately we don't have any automated browser tests. We've only got tests runs inside node environment - so no browser/mobile platforms are really tested automatically.

**Comment by tstoppe89** [comment]
PR #3572 resolved this issue.

**Comment by lgrignon** [comment]
Thanks @tstoppe89, you made my day :)

This fixes the localStorage quota problem with sql.js database.
FYI I linked your solution in [this sql.js issue](https://github.com/sql-js/sql.js/issues/132#issuecomment-613904440) because it seems to me that it answers the question.
