### ISSUE TITLE
Column property is undefined in QueryFailedError object

### ISSUE THREAD

**Issue by winelivery** [typeorm/typeorm#3555]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.11`

**Steps to reproduce or a small repository showing the problem:**

Hi guys,

thanks for your awesome library.

I need to catch when an email is duplicate, but in the error object `QueryFailedError` the column attribute is `undefined`.

Is there a way to show which column violates this unique constraint?

This is my QueryFailedError:

```
{ QueryFailedError: duplicate key value violates unique constraint "UQ_97672ac88f789774dd47f7c8be3" ...
  message: 'duplicate key value violates unique constraint "UQ_97672ac88f789774dd47f7c8be3"',
  name: 'QueryFailedError',
  length: 245,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (email)=(duplicate_email@domain.com) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'users',
  column: undefined,
  dataType: undefined,
  constraint: 'UQ_97672ac88f789774dd47f7c8be3',
  file: 'nbtinsert.c',
  line: '535',
  routine: '_bt_check_unique',
  query: 'INSERT INTO ...',
  parameters: [ ... ] }
```

**Comment by vlapo** [comment]
This is not typeorm based error. We are throwing errors from underline driver `node-pg`. Here are few issues about this problem with undefined fields in error - https://github.com/brianc/node-postgres/issues/995, https://github.com/brianc/node-postgres/issues/978.

**Comment by pleerock** [comment]
I guess this can be closed.

**Comment by hamzazahidulislam** [comment]
thank you so much brother @winelivery , your solution is working, and  I am handling multiple duplications by this method 😍😍
