### ISSUE TITLE
How to make a many to many relationship to a junction table

### ISSUE THREAD

**Issue by P0oOOOo0YA** [typeorm/typeorm#3562]
**Issue type:**
[*] question

Suppose `A `and `B` are two distinct entities with many to many relationship which results in `AB` junction table. We have another entity named `C` which has many to many relationship with`AB`.  To my knowledge in typeorm to make relationships we need to have entities to be defined and loaded. But there is no entity for a junction table. So how in this case `C` can be related to `AB`?

**Comment by saurabhpati** [comment]
I was searching for a different issue for my problem but landed upon this question. 

I think **maybe** I can help with this.

So if you have many to many relationship between A and B and you are needing a many to many relationship between another entity C and AB, 

It **may be** possible for you to redesign to have 

A <--many2many --> B

A <--many2many --> C

B <--many2many --> C

which would create separate join tables AB, AC and BC.

suppose you require C for a given value of A and B,
you can query your repository like 
A JOIN B 
JOIN C 
WHERE A == conditionalParamOfA 
AND WHERE B == conditionalParamOfB

suppose you require C for a given value of A.
you can query repository like
A JOIN C 
WHERE A == conditionalParamOfA

and so on and so forth.

Does it help?
