### ISSUE TITLE
Retrieving ID in @AfterInsert operation

### ISSUE THREAD

**Issue by alex5207** [typeorm/typeorm#3563]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have two entities, **Person** and **Photo** which has a one-to-one relationship. After creating a person I'm trying to create a Photo in the `@AfterInsert` part. However, when trying to fetch the id of the newly created person, it returns undefined (

```@Entity()
export class Person {

  @AfterInsert()

  public async handleAfterInsert() {
    const person = await getConnection()
      .getRepository(Person)                     //<--- This is where the problem is
      .findOne(this.id);

    //Insert into Photo
      const photo = New Photo();
      photo.person = person;

    await getConnection()
      .getRepository(Photo)
      .save(photo);
  }

  @PrimaryGeneratedColumn()
  public id: number;

  @OneToOne(type => Photo, photo => photo.person)
  public photo: Photo
}
`

**Comment by vlapo** [comment]
Did you use `save()` or `insert()` method? Because `insert()` method is just simple INSERT in DB and save method do lot of magic around - like fill primary generated column.

**Comment by alex5207** [comment]
When creating a `Person` I am using the `save()` method.
Note: I can verify that the ID is present if I do a `console.log(this.id)`.

So, its like the repository is not updated quickly enough

**Comment by vlapo** [comment]
Understand now. I thought `this.id` is undefined before. This is problem of transactions. Insert statement is done but transaction is not committed yet so person is not available in new select.

But I do not understand why you need select person again? You have your entity in `this` so use it.
```typescript
@AfterInsert()
public async handleAfterInsert() {
    //Insert into Photo
    const photo = New Photo();
    photo.person = this;

    await getConnection()
      .getRepository(Photo)
      .save(photo);
}
```

**Comment by vlapo** [comment]
Yeah you need use same `entityManager` instance because of transactions. In short you have to use subscriber instead of listener.

```typescript
@EventSubscriber()
export class PersonSubscriber implements EntitySubscriberInterface<Person> {

    listenTo() {
        return Person;
    }

    async afterInsert(event: InsertEvent<Person>) {
        const photo = new Photo();
        photo.person = event.entity;

        await event.manager
            .getRepository(Photo)
            .save(photo);
    }
}
```


More info: https://github.com/typeorm/typeorm/issues/743 and https://github.com/typeorm/typeorm/issues/1705#issuecomment-372931885

**Comment by alex5207** [comment]
@vlapo  - Thanks a lot for your example. Forgive me, but I somehow still cannot get this to work.
I have implemented exactly as in your example in a **seperate** file from the `Person` entity.

Nothing really happens when I insert a new `Person`. I tried doing a `console.log('inserted person')` inside `afterInsert` to try and verify whether anything was happening. Nothing came from it.

I tried to read [https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md#what-is-a-subscriber] as well. Seems to provide almost an identical example to yours.

Do I need to create an instance of this class anywhere, or?

Thanks for your patience
BR

**Comment by vlapo** [comment]
You have to define subscribers in your connection options. Check this http://typeorm.io/#/connection-options, option `subscribers`. 

I am really suprised we do not have any note about this option in https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md.

**Comment by alex5207** [comment]
Worked like a charm - Thanks a lot @vlapo
