### ISSUE TITLE
define fields which isn't a table column

### ISSUE THREAD

**Issue by MetaiR** [typeorm/typeorm#3569]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I want to have an extra field in my entity model, which isn't in my database table. I mean something like this:

```
export class Person {
    @PrimaryGeneratedColumn({ name: 'person_id' })
    private _id: number = undefined;
    @Column({ name: 'person_national_id' })
    private _nationalId: string = undefined;
    @Column({ name: 'person_firstname' })
    private _firstname: string = undefined;
    @Column({ name: 'person_lastname' })
    private _lastname: string = undefined;
    @Column({ name: 'person_phonenumber' })
    private _phone: string = undefined;
    @Column({ name: 'person_address' })
    private _address: string = undefined;
    @Column({ name: 'person_father_name' })
    private _fathername: string = undefined;
    @Column({ name: 'person_birth_year' })
    private _birthYear: number = undefined;
    @Column({ name: 'person_deleted' })
    private _deleted: boolean = undefined;
    @Column({ name: 'person_lastmodify' })
    private _lastModify: Date = undefined;
    @Column({ name: 'person_work_address' })
    private _workAddress: string = undefined;
    @Column({ name: 'person_work_phonenum' })
    private _workPhone: string = undefined;

    // extra
    private _loading = false; // I want this one
}
```
the problem is typeorm looks this field as a table column

**Comment by MetaiR** [comment]
no idea?

**Comment by pleerock** [comment]
> the problem is typeorm looks this field as a table column

if you mean it creates you a column for `_loading` then it can't be true. Please check everything once again.

**Comment by MetaiR** [comment]
@pleerock 
no, it doesn't create a column, it considers it as a column and looking for it and because it isn't a column it throws an exception.
I just want to have an extra field which has nothing to do with database tables in my entity model

**Comment by vlapo** [comment]
What exception is typeorm throwing? Please describe your case in more details. Sry but from one entity definition and one setence `the problem is typeorm looks this field as a table column` we really do not know what is problem and how to help you or resolve it.

**Comment by MetaiR** [comment]
@vlapo 
just this question, how do u add a property to ur entity class which isn't and won't be in ur database table (like a property with @transient annotation in java hibernate)?

**Comment by vlapo** [comment]
As a property without `@Column()` annotation. Could you provide example of code with issue?

**Comment by MetaiR** [comment]
I sent an example in my first post.
I did use a field without `@Column()` but typeorm still think it is a column and search for it in the database and because there is no column for this field it throws an exception

**Comment by vlapo** [comment]
Post example of code where is error throws. Not only entity definition.

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by totalard** [comment]
Anybody Fixed This problem, Shall i get field without db column.. Please Help

**Comment by oussaki** [comment]
i had the same issue i don't want to show non column fields to show in my response.

**Comment by vixson** [comment]
Hi. Please it would be nice to have a `@NotColumn` decorator or see that `@Exclude` decorator from [Class Transaform](https://github.com/typestack/class-transformer) can fix this.

Thanks

**Comment by vixson** [comment]
Anyways. Here is the quick fix.
The basic idea is to have only the class properties that are marked as columns to be sent to the update function right?
Well simply filtered the data for that 💡 

```ts
import {pick} from 'lodash';
import {getRepository} from 'typeorm';

// ...

 updatePerson(@Body() data: any) {
    const model = getRepository(Person);
    data = pick(model.create(data), model.metadata.columns.map(c => c.propertyName)); // Pick only the `@Column` fields
    return model.update(data.id, data);
  }

```

You can use any Object filtering method of choice. I preferred [lodash](https://lodash.com/docs/#pick) here.

**Comment by wallace-sf** [comment]
Hello guys, i found a solution suggested by Bing AI (i tried ChatGPT, but it gives wrong answer 😂). The solution is use getters and setters for override the dummy property. See: 

```ts
@Entity()
export class Product{
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  dummy: string;

  // <-- Getters and Setters -->
  set _dummy(value: string) {
    this.dummy = value.toUppercase();
  }

  get _dummy() {
    return this.dummy;
  }

  // <-- Hooks -->
  @BeforeInsert()
  doSomething() {
    console.log(this.dummy);
  }
}
}
```
This way we have a dummy column that could be used in entity hooks, but there is not in database. Not need of VirtualColumn which enforces to pass query param. Hope it helps.
