### ISSUE TITLE
ID gets appended to field name

### ISSUE THREAD

**Issue by Murbal** [typeorm/typeorm#3575]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have a problem regarding many to one
```ts
@Entity()
export class Post {
    @PrimaryGeneratedColumn({type: 'int'})
    id: number
    @ManyToOne(type => User, user => user.id)
    @Column({type: 'int'})
    authorId: User
}
```
```ts
@Entity()
export class User {
    @PrimaryGeneratedColumn({type: 'int'})
    id: number
}
```
When I try to get all posts via
```ts
const posts = await this.postRepository.find({
                       relations: ['authorId']
                       })
```
I get a ER_BAD_FIELD_ERROR with the message: Unknown column 'Post.authorIdId' in 'field list'
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
You have `ManyToOne` and `Column` defined for one property. if you want to have `authorId` and `author` property in your `Post` entity:
```typescript
@Entity()
export class Post {
    @PrimaryGeneratedColumn({type: 'int'})
    id: number

    @Column({type: 'int'})
    authorId: number

    @ManyToOne(type => User, user => user.id)
    author: User;
}
```
and of course call find like this:
```typescript
const posts = await this.postRepository.find({
      relations: ['author']
})
```

**Comment by Murbal** [comment]
Thanks this solved my issue
