### ISSUE TITLE
Error when saving an entity after lazy loading its relations: TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by P4sca1** [typeorm/typeorm#3576]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Repository demonstrating the problem:**

https://github.com/P4sca1/typeorm-problem

**Comment by P4sca1** [comment]
I made some more tests and noticed that this issue exists since `v0.2.12`.
Prior versions work like expected.

**Comment by vinsidious** [comment]
I ran into this as well and found it very difficult to debug.

**Comment by pinguinjkeke** [comment]
Yeah, the same here.

**Comment by pleerock** [comment]
Looks like this was broken by #3231

**Comment by joelgallant** [comment]
This should be the fix @pleerock https://github.com/typeorm/typeorm/pull/3656

**Comment by P4sca1** [comment]
I am not experienced with testing frameworks, but would probably be good to add a test for this for the future?

**Comment by pleerock** [comment]
I release 0.2.14 with this fix, please check it.

**Comment by kashkashio** [comment]
You guys are awesome! just encountered this bug and found you solved it and all i had to do is upgrade.
Brilliant ! thank you!

**Comment by P4sca1** [comment]
Thank you for solving the issue!
