### ISSUE TITLE
Add support to cube on posgres

### ISSUE THREAD

**Issue by ricardovf** [typeorm/typeorm#3577]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Add support for the cube type with postgres. https://www.postgresql.org/docs/10/cube.html

**Comment by ricardovf** [comment]
I have added two cube columns manually using migrations, all working. Good.

But now i run **migration:generate -n Test** and a migration is generated dropping the columns, as i have not mapped them in the entity cause CUBE is not supported...

````
public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_ENCODING_LOW_HIGH"`);
        await queryRunner.query(`ALTER TABLE "frame_encoding" DROP COLUMN "encodingLow"`);
        await queryRunner.query(`ALTER TABLE "frame_encoding" DROP COLUMN "encodingHigh"`);
    }
````

How can i get around this?

**Comment by ricardovf** [comment]
Bump, any plans on this?

**Comment by vlapo** [comment]
We do not have any plans for this feature. But feel free to contribute.

**Comment by ricardovf** [comment]
Can i have a option to somehow make migration:generate not want to remove this fields that i manually created?

**Comment by vlapo** [comment]
Sorry, I do not think so we have any way how to skip column (or deleting column) from migration generation. Typeorm simply know nothing about this column and think it is old column and need to delete.

But if you have any idea how to implement this functionality into typeorm migrations feel free contribute or write detailed proposal.

**Comment by ricardovf** [comment]
I understand. Maybe using an annotation in the entity to do something like:

@IgnoreMigration('DROP INDEX "IDX_ENCODING_LOW_HIGH"')
@IgnoreMigration('ALTER TABLE "frame_encoding" DROP COLUMN "encodingLow"')
@IgnoreMigration('ALTER TABLE "frame_encoding" DROP COLUMN "encodingHigh"')

So in the migration generation, if the output equals some of the marked migrations string, it will be ignored.

What do you think?

**Comment by liaujianjie** [comment]
I'm willing to work on this if pointed in the right direction. 😄

**Comment by liaujianjie** [comment]
Coming up with a checklist, right off the bat. Am I missing anything?

- [ ] Add entity metadata checker for existence of entities with column of type `cube`
- [ ] Attempt to install `cube` extension if not installed
   https://github.com/typeorm/typeorm/blob/4d0ebc64c2819ff2af70537f6fb98ed42effe480/src/driver/postgres/PostgresDriver.ts#L316-L346
- [ ] Add `cube` as supported type https://github.com/typeorm/typeorm/blob/4d0ebc64c2819ff2af70537f6fb98ed42effe480/src/driver/postgres/PostgresDriver.ts#L88-L152

**Comment by vlapo** [comment]
@liaujianjie the best example case is PR https://github.com/typeorm/typeorm/pull/2423/files. Please check it. But in general there is few areas you have to handle:
 - schema sync from entity to db
 - migrations - something change in column in time
 - query builder
 - driver - supported column type, extension and so on
 - documentation
 - tests
----------
> @IgnoreMigration('DROP INDEX "IDX_ENCODING_LOW_HIGH"')
@IgnoreMigration('ALTER TABLE "frame_encoding" DROP COLUMN "encodingLow"')
@IgnoreMigration('ALTER TABLE "frame_encoding" DROP COLUMN "encodingHigh"')

@ricardovf I think this is too specific. Now we have option in `@Entity({ synchronize: false })` so maybe add some property `skipColumnSynchronize: ['col1']`. Or something like that. But this is really only idea. But keep this issue about `cube`. Feel free open issue with proposal for this functionality and we can discuss there.

**Comment by liaujianjie** [comment]
@vlapo Thanks for the link to the PR, I've made a PR (#4378) using that as a reference. Let me know if there's anything missing. 😃
