### ISSUE TITLE
npm install when use typeorm --init

### ISSUE THREAD

**Issue by jaigm** [typeorm/typeorm#3582]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Any reason why are you not running `npm install` after create the project structure when using: `typeorm init --name MyProject --database mysql --express`?

**Comment by vlapo** [comment]
I think the reason is that some users are using `yarn` instead of `npm`. But it is no to killing feature and maybe someone could contribute :-) 

E.g. angular-cli is good point to check:
https://github.com/angular/angular-cli/blob/master/packages/angular/cli/tasks/npm-install.ts
