### ISSUE TITLE
error TS2322: Type 'FindOperator<string>' is not assignable to type 'string' 

### ISSUE THREAD

**Issue by ShanniL** [typeorm/typeorm#3589]
What the reason this differences?

**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.12` (or put your version here)

Hello. My question is about https://github.com/typeorm/typeorm/blob/master/docs/find-options.md.
I can't use condition "In" at Entity.find method.

```
    Group.find({ name: Like("%abc") })
```
Type 'FindOperator<string>' is not assignable to type 'string'
And I saw here https://github.com/typeorm/typeorm/blob/master/src/find-options/operator/Like.ts

```
/**
 * Find Options Operator.
 * Example: { someField: Like("%some sting%") }
 */
```

As my code did nothing wrong but Typescript is treating { someField: Like("%some sting%") } as assignment rather than query.

**Comment by vlapo** [comment]
What version of typescript do you use? I try this with v3.2.1 and do not have this problem.

**Comment by ShanniL** [comment]
Yea, I'm on the same typescript version v.3.2.1 and ts-node v6.2.0
