### ISSUE TITLE
any spanner plans

### ISSUE THREAD

**Issue by chadbr** [typeorm/typeorm#359]
Any plans to add spanner to the mix? 

https://cloud.google.com/spanner/

Just curious...

**Comment by pleerock** [comment]
There are really so many things to do right now, so no plans on it in a near future. So, I expect contributors initiative for this issue.

**Comment by chadbr** [comment]
Ok, I may have a look after I study the code base a bit.

Thanks!

**Comment by simonireilly** [comment]
Is there any renewed appetite to support this within typeorm?

Given cockroach support was added: https://github.com/typeorm/typeorm/issues/1040 and spanner is attempting a postgres compatible dialect https://cloud.google.com/spanner/docs/postgresql-interface
