### ISSUE TITLE
parentheses showing up in column name

### ISSUE THREAD

**Issue by MaozSayag** [typeorm/typeorm#3590]
**Issue type:**

[x ] question
[? ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[X ] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>
hello,
i'm new to typeorm so i dont know if its simply somthing i dont understsnd.
my problem is:
i create a table using the foloing entite;

@Entity('JOBS')
export class Job{
   @PrimaryGeneratedColumn()
    id: number;

    @Column({length: 25})
    name: string;
]
my table is getting created but my coloms apear in the DB with parentheses.
so column 'id' shows up as '"id"'.
and when i look at the create table Q i can c the extra onse. such as: 
CREATE TABLE "JOBS" (""code"" number NOT NULL, ""name""  varchar2(25) NOT NULL, CONSTRAINT "PK_075442sasd44" PRIMARY KEY ׁׂ(""code""))

im not sure what exsactly cuses this and how to prevent it. and i cant locate any issue concetning this.

if someone can help me with this id much appreciate it ♥

**Comment by vlapo** [comment]
Could you please provide more info not just a title? Example of entity definition?

**Comment by MaozSayag** [comment]
im not sure what happend.. i wrote my issue... never mind.

my issue is as follows:

i have an entitie job as follows:
@Entity('JOBS')
export class UserPlace {

       @PrimaryColumn() 
       code: number;

       @Column({length; 25}) 
       name: string;
}
after i run program in the DB i see the thable names with parentheses,
so 'code' is actualy conveted to '"code"'. 
wen i look at the Q that typeorm creates i see:
CREAT TABLE "JOBS" (""code"" number NOT NULL, name varchar2(25) NOT NULL, CONSTRAINT "PK_ba212dsdvdcsf12" PRIMARY KEY (""code"") )

im not sute how to eleminate the extra parentheses im getting. or why im getting them

**Comment by vlapo** [comment]
I tested this on latest version of typeorm and do not have this problem. Sql generated: 
```
CREATE TABLE "JOBS" ("code" number NOT NULL, "name" varchar2(25) NOT NULL, CONSTRAINT "PK_be85a791c914b7810087adb735f" PRIMARY KEY ("code"))
```
Please try latest version of typerom and also check if problem is not in your entity definition.

**Comment by MaozSayag** [comment]
ill try updating my vertion, and see if it helps.

**Comment by MaozSayag** [comment]
i updated to the latest version. an i also no longer see the double parentheses.
but im my SQL developer i still see the tables with parentheses. as is;
select code from JOBS; will return an invalid identifire but,
select "code" from JOBS; will work. this is now much weirder.

in case it helps this is my ormconfig.json ->
{
"type": "oracle",
"connectString": "test",
"username": "maoz",
"password": "test",
"entities": ["dist/models/*.js],
"migrations":["dist/migrations/*.js"],
"synchronies": true,
"logging": true
}

**Comment by vlapo** [comment]
You update to latest version of typeorm works?

I do not understand your problem with SQL developer. Is there still any problem with typeorm?

**Comment by Kononnable** [comment]
Closing as no response from the author.
