### ISSUE TITLE
Is there any way to configure a `Repository`, `EntityManager` or `Entity` to use a non-default connection?

### ISSUE THREAD

**Issue by rangelfinal** [typeorm/typeorm#3593]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

---------------------------------------------------------------------------------------------------

By default, if no connection is specified, managers and repositories will act on the default connection.
Is there any way to set a manager or custom repository to always use some other connection?
Or the only way to use a non default connection is to do something like `getConnection("myConnection").manager().doSomething`?

**Comment by vlapo** [comment]
I dont think so there is another way than you provide in your question.
