### ISSUE TITLE
mongodb support where condition to relations on find options 

### ISSUE THREAD

**Issue by Shashi-GS** [typeorm/typeorm#3596]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
We are not able to query with where condition for many records and not able to execute sql queries also on top of MOngoDB. Could you please help me out.

**Comment by Kononnable** [comment]
Could you elaborate? Some code snippet, more info on what exactly you want to achieve and what is current outcome of executing your code.

**Comment by craftball** [comment]
const existingUser = await this.userRepository.findOne({
      where: [
        {email: data.email},
        {username: data.username}
      ]
    });

Running this WHERE / OR will return:

code: 8000
codeName: 'AtlasError'
name: 'MongoError'

**Comment by rustamwin** [comment]
Closing no answer from issue author
