### ISSUE TITLE
typeorm create mongodb collection on start of server.

### ISSUE THREAD

**Issue by Shashi-GS** [typeorm/typeorm#3598]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Is there any way I can create database and collections based on entities on start of server if not exist.

**Comment by rustamwin** [comment]
mongodb schema builder only supported to indices build
you can use migrations :smile:

**Comment by phil294** [comment]
It makes sense to allow this feature, as `Entity.clear()` fails with `ns not found`, if no entity has been saved beforehand (and as such, the collection doesnt exist). I think this should be reopened.
