### ISSUE TITLE
CLI generate migration get DriverPackageNotInstalledError

### ISSUE THREAD

**Issue by Tyzar** [typeorm/typeorm#3599]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I've tried to run cli command ts-node ./node_modules/typeorm/cli.js migration:generate -n SimpleMigration to generate migration file but get exception DriverPackageNotInstalledError. I use cordova-sqlite-storage for database. Cordova sqlite storage has been installed and can be found in node_modules folder. This error does not occur when run on device, database can be created and functions well.

This is the ormconfig.json:
{    
    "type":"cordova",
    "database":"msmdb",
    "location":"default",
    "logging":["error","schema"],
    "synchronize":false,
    "entities":[".src/entities/*.ts"],
    "migrations":[".src/providers/db/migrations/*.ts"],
    "cli":{
        "migrationsDir":["./src/providers/db/migrations"],
        "entitiesDir":["./src/entities"]
    }
}

Why typeorm cannot detect the cordova-sqlite-storage package when run migration generate command?

**Comment by Kononnable** [comment]
I don't think it's possible to use CLI for migrations with cordova. Cordova driver requires application to be running on a device while you run cli on your PC.
