### ISSUE TITLE
Mongo count() is stuck on collection of big size

### ISSUE THREAD

**Issue by Alex0007** [typeorm/typeorm#3601]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

```js
    const parcelsCount = await getConnection("my_connection")
        .getMongoRepository(Parcel)
        .count();
    
    console.log('parcelsCount', parcelsCount);
```

Nothing happens, then (in 3-5 minutes) this error is shown

```
MongoNetworkError: connection 1 to <url> timed out
    at Socket.<anonymous> (/<app>/node_modules/mongodb-core/lib/connection/connection.js:259:7)
```  

Collection is big enough

> db.getCollection('parcels').count()

108890741

This snippet works well on `@next` version. It also works well on smaller collections on `@latest`

**Comment by rustamwin** [comment]
Hey @Alex0007 

> db.getCollection('parcels').count()

Can you check `db.getCollection('parcels').countDocuments()` work as well?

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by Alex0007** [comment]
@rustamwin 
```
Failed to execute script.

Error:
TypeError: db.getCollection(...).countDocuments is not a function :
@(shell):1:1
```

`countDocuments` is 4.0.3+, while my instance is 4.0.1
