### ISSUE TITLE
update query run twice with new data and old data

### ISSUE THREAD

**Issue by gabrieljo** [typeorm/typeorm#3602]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.3.0-alpha.22` (or put your version here)

Hi there,

I have faced error. I tried to update user data. and there is no error but data not updated.  so I just have looked query,  it looks like run twice. and first query is what I expected run with new data then query run again with old data. 

query results

query: SELECT ... = ? -- PARAMETERS: [15]
//This query is what I expected
query: UPDATE `user` SET `firstname` = ?, `updatedAt` = CURRENT_TIMESTAMP WHERE `id` = ? -- PARAMETERS: ["Youngmin",15]

query: SELECT ...  FROM `user` `User` WHERE (`User`.`id` IN (15))
POST /graphql 200 24.166 ms - 56

query: START TRANSACTION
//But this query run the parameter is old data
query: UPDATE `user` SET `firstname` = ?, `storeId` = ?, `updatedAt` = CURRENT_TIMESTAMP WHERE `id` IN (15) -- PARAMETERS: ["Gabriel",null]
query: SELECT `User`.`id` AS `User_id`, `User`.`updatedAt` AS `User_updatedAt` FROM `user` `User` WHERE (`User`.`id` = ?) -- PARAMETERS: [15]
query: COMMIT

my code
========================================================================
const user = req.user;
        const notNull: any = removeNull({ ...args });

        try {
          if (notNull.password !== null) {
            user.password = args.password;
            user.save();
            delete notNull.password;
          }

         await User.update({ id: user.id  }, { ...notNull });

          return {
            success: true,
            error: null
          };
        } catch (error) {
          return {
            success: false,
            error: error.message
          };
        }
========================================================================

is there a any solution?

**Comment by Kononnable** [comment]
You're sure you don't want to await that? `user.save();`
