### ISSUE TITLE
Using jsonb_array_elements with createQueryBuilder

### ISSUE THREAD

**Issue by Skullflow** [typeorm/typeorm#3609]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi guys,

Is there a way to use `jsonb_array_elements` with `createQueryBuilder()`.

It doesn't work with from, because it want an Entity as first parameters.

**Comment by vlapo** [comment]
Maybe post your entity definition and SQL you want to run using query builder.

**Comment by Skullflow** [comment]
This is a generic question, but I'll try to explain with an example.

Consider this entity:

```ts
@Entity()
class Store {
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column({ type: 'jsonb', name: 'time_tables'})
    timeTables: TimeTable[];
}
```

Where TimeTable is an interface defined like this:
```ts
interface TimeTable {
    day: number; //week day
    openings: Opening[];
}

interface Opening {
    from: string; //from opening time, e.g.: 10:00:00
    to: string; //to opening time, e.g.: 20:00:00
}
```

Now, i want to retrieve all the stores that are open in a specific time. So i need to iterate over my jsonb column.

Raw sql query would be:

```sql
SELECT DISTINCT *
FROM stores,
jsonb_array_elements(time_tables) time_table,
jsonb_array_elements(time_tables->'openings') openings,
WHERE
 ($1 BETWEEN CAST(openings ->> 'from' AS TIME) AND CAST(openings ->> 'to' AS TIME))
AND time_table ->> 'day' = '0'
```
Where $1, $2 are parameter that specify a time ($1) and a week day ($2) 

So, in order to iterate over my json, i need to unwind the 2 arrays and check if time parameter is between the opening (from and to) in a specified week day.

I dont want to retrieve raw results, so i want to use createQueryBuilder.

**Comment by ignaion** [comment]
Hi, any update about this case?
thank you.

**Comment by imnotjames** [comment]
You'll want to use the raw operator or query builder with `where`>

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by neekey** [comment]
@ignaion have you found a solution?

**Comment by kalyuk** [comment]
> @ignaion have you found a solution?

yap, I`m switched my project to sequelize
