### ISSUE TITLE
Issue Inserting Relations With IDs

### ISSUE THREAD

**Issue by CWSpear** [typeorm/typeorm#361]
TypeORM version: 0.9
Postgres: 9.6.2
Node: 6.10.0

(See [created a reduced test case](https://gist.github.com/CWSpear/76de95f7d34b81bcfc363dac7d3dd87b) for further details.)

I have an app that creates some entities on the client and it generates the UUID on the client side, and then sends if off to the server. I [created a reduced test case](https://gist.github.com/CWSpear/76de95f7d34b81bcfc363dac7d3dd87b) where you can see the full details, but this is the crux of it:

```ts
const book = new Book();

book.name = 'The Awesome Book';
// book.author is a ManyToOne relationship
book.author = new Author();
book.author.id = uuid();
book.author.name = 'CWSpear';

// throws an error: insert or update on table "book" violates foreign key constraint
connection.entityManager.persist(book);
```

That's because it tries to do an `insert` on the `book.author` field with the ID (whereas if we didn't supply the ID, it would do a separate `update` to add the ID).

I hope that's making sense...

I don't know if this is something that would best be solved in the code, but it's worth noting that you can set the FK to be `DEFERRABLE INITIALLY DEFERRED` in Postgres and it will work.

**Comment by CWSpear** [comment]
i.e This is the query log when you run the above:

```sql
-- executing query: 
COMMIT
SELECT "operateSubject"."id" AS "operateSubject_id", "operateSubject"."name" AS "operateSubject_name" FROM "author" "operateSubject" WHERE "operateSubject"."id"=$1 -- PARAMETERS: [13]
START TRANSACTION
INSERT INTO "book"("name", "author") VALUES ($1,$2)  RETURNING "id" -- PARAMETERS: ["The Awesome Book",13]
INSERT INTO "author"("id", "name") VALUES ($1,$2)  RETURNING "id" -- PARAMETERS: ["e3b53871-8240-44d0-810d-c9eefd76100c","CWSpear"]
-- query failed: 
INSERT INTO "book"("name", "author") VALUES ($1,$2)  RETURNING "id" -- PARAMETERS: ["The Awesome Book","e3b53871-8240-44d0-810d-c9eefd76100c"]
ROLLBACK
-- query failed: 
INSERT INTO "author"("id", "name") VALUES ($1,$2)  RETURNING "id" -- PARAMETERS: ["e3b53871-8240-44d0-810d-c9eefd76100c","CWSpear"]
```

This is what it is if you don't set `book.author.id`:

```sql
-- executing query: 
START TRANSACTION
INSERT INTO "book"("name") VALUES ($1)  RETURNING "id" -- PARAMETERS: ["The Awesome Book"]
INSERT INTO "author"("name") VALUES ($1)  RETURNING "id" -- PARAMETERS: ["CWSpear"]
UPDATE "book" SET "author"=$1  WHERE "id"=$2 -- PARAMETERS: ["81881074-fece-490d-bfd9-e1ed06c51eaf","a6e4ece2-5f2d-4fe7-ac32-7cacce8d24cd"]
COMMIT
```

**Comment by pleerock** [comment]
thats looks like a bug. Cascades are quite complicated feature and in this case it looks like it can't handle issue with non generated id is used and object is being inserted before referenced object is inserted, but it has an id and it thinks that its already inserted.

However there is one strange things in your code above.

Here, 

```sql
INSERT INTO "book"("name", "author") VALUES ($1,$2)  RETURNING "id" -- PARAMETERS: ["The Awesome Book",13]
INSERT INTO "author"("id", "name") VALUES ($1,$2)  RETURNING "id" -- PARAMETERS: ["e3b53871-8240-44d0-810d-c9eefd76100c","CWSpear"]
```

`-- PARAMETERS: ["The Awesome Book",13]` should be `-- PARAMETERS: ["The Awesome Book","e3b53871-8240-44d0-810d-c9eefd76100c"]`. However I assume its just your corrections.

**Comment by CWSpear** [comment]
@pleerock yeah, sorry, I was trying to show the example with UUIDs, but my reduced test case used `int`s because it was easier to stand up Postgres in Docker without `uuid-ossp`. I updated my example.

**Comment by pleerock** [comment]
Sorry for the delayed answer but this issue to be resolved required lot of efforts and refactorings. I have completely refactored persistence system and fixed all problems with cascades I have seen. Please try a new version (npm i typeorm@next) and let me know if your issue is still not resolved.
