### ISSUE TITLE
`Error: No connection options were found in any of configurations file.`Continue to be displayed

### ISSUE THREAD

**Issue by nitaking** [typeorm/typeorm#3611]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

my step...
```sh
npm install typeorm -g
typeorm init --name projectname --database postgres 

npm start
```

```
$ ts-node src/index.ts
Error: No connection options were found in any of configurations file.
    at ConnectionOptionsReader.<anonymous> (/Users/pc148/code/instagram-clone-typeorm/packages/typeorm/src/connection/ConnectionOptionsReader.ts:41:19)
    at step (/Users/pc148/code/instagram-clone-typeorm/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/pc148/code/instagram-clone-typeorm/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/Users/pc148/code/instagram-clone-typeorm/node_modules/tslib/tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:178:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at Object.<anonymous> (/Users/pc148/code/instagram-clone-typeorm/node_modules/ts-node/src/_bin.ts:182:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
```

my ormconfig.json
```json
{
   "type": "postgres",
   "host": "localhost",
   "port": 5432,
   "username": "",
   "password": "",
   "database": "instagram_clone",
   "synchronize": false,
   "logging": false,
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}

```

I have confirmed that I can connect to postgres

What is going on? Is it due to my local environment?

**Comment by vlapo** [comment]
This have to be some issue in your project. Are you sure you have a `ormconfig.json` in root of project folder?

**Comment by nitaking** [comment]
After re-creating the project and re-executing, it worked.

Because it was using with monorepo, it may be because that setting was bad.
I could write a few trouble. Thanks!

**Comment by bamtron5** [comment]
Incase anyone else experiences this issue in a mono repo (workspace yarn style) ... I moved ormconfig.json to the mono repo root and it worked.

**Comment by jAlfredsson** [comment]
> This have to be some issue in your project. Are you sure you have a `ormconfig.json` in root of project folder?

thank you!!! 2 hours to find out I by accident put ormconfic in ./src ...

**Comment by Jeff-Tian** [comment]
I had to fix this error by explicitly pass the `postgres` type to the options:

```
type: 'postgres',
url: 'postgres://xxxx'
```

**Comment by tiagob** [comment]
I had this issue with a yarn workspaces monorepo. It worked when I moved ormconfig.json to the root project

**Comment by christianallred** [comment]
has anyone found a solution that allows em to put the config files in the project folders they belong too? Putting it in the Root of the project for a monorepo is REALLY bad practice.

**Comment by tiagob** [comment]
Yeah, actually using a different solution now

In the root package.json add typeorm to nohoist

```json
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/typeorm",
      "**/typeorm/**"
    ]
  },
```

**Comment by rogerioisj** [comment]
With me, was necessary reinstall the Node :p

**Comment by msegers** [comment]
@tiagob did you do anything else in your package json? I have a similar setup (also the packages in the same folder etc.) for me I still get the same error unless my config resides in the root

**Comment by timthedev07** [comment]
> I had this issue with a yarn workspaces monorepo. It worked when I moved ormconfig.json to the root project

It does work for in my case.

**Comment by manikbajaj** [comment]
> I had this issue with a yarn workspaces monorepo. It worked when I moved ormconfig.json to the root project

That beats the whole point of having a monorepo. What if another project needs to ormconfig with different details. I have tested as to what you are saying is correct, putting the file in the root of the monorepo does work but that's definitely not the solution.
