### ISSUE TITLE
Update Date column from SQL

### ISSUE THREAD

**Issue by thellimist** [typeorm/typeorm#3614]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

---

Is there a way to update `Date` column from SQL. Something like

```
        await connection
            .createQueryBuilder()
            .update(Session)
            .set({ ip_address: ip, last_login: 'CURRENT_TIMESTAMP'})
            .where('session.user_id = :id', { id: userId })
            .execute()
```

`UpdateDateColumn` does not work for me because I need to update the column only in some save actions whereas `UpdateDateColumn` gets triggered in all save actions

**Comment by vlapo** [comment]
Did you try 
```typescript
.set({ ip_address: ip, last_login: () => 'CURRENT_TIMESTAMP'})
```

**Comment by thellimist** [comment]
works 👍
