### ISSUE TITLE
SubjectWithoutIdentifierError when trying to remove something

### ISSUE THREAD

**Issue by Bernd-L** [typeorm/typeorm#3615]
# Metadata
Issue type|Database system/driver|TypeORM version
-|-|-
bug report|`postgres`|`latest` (`0.2.13`)

## Versions
Windows 10 Pro |Node|Npm
-|-|-
Version 1809 (OS Build 18298.1000)|v10.8.0|6.2.0

# The Problem

When trying to save an entity, TypeORM will just give me this output in the console instead of doing what it should:

>SubjectWithoutIdentifierError: Internal error. Subject Category must have
an identifier to perform operation. Please report a github issue if you face this error.

# Preparation

You'll need:
- The Repository
- A Postgres server
- Two keys
- Postman (`cURL` may not be sufficient because of JWT-cookies)

## The repository
https://github.com/Bernd-L/exDateMan/tree/561c8b111613289a228093cd96af10f5cba72b64
(`exDateMan` = Expiration date manager)
It's a small project of mine. It manages one's inventory (with a special focus on expiration dates).
I linked you the commit which will reproduce the error.

## The environemnt variables

Some configuration values are stored in environment varaibles:

```TS
host: process.env.EDM_HOST,
port: parseInt(process.env.EDM_PORT, 10),
username: process.env.EDM_USER,
password: process.env.EDM_PWD,
database: process.env.EDM_DB,
```

Set the values in your test system accordingly.

## The keys
You'll need two keys.

Generate them using [this tool](http://travistidwell.com/jsencrypt/demo/). They will be used to sign and verify the JWT.

Save them somewhere in separate files, and save their paths to these environment variables:
`EDM_PUBLIC_KEY` and `EDM_RSA_PRIVATE_KEY`.

## The database

I have made [this backup file](https://github.com/typeorm/typeorm/files/2849461/Backup_2019-02-10_1.zip) of my `public` schema in Postgres using pgAdmin.

## Steps to follow

1. Clone the repo (using the commit I linked to)
2. `npm install`
3. Set up the server
4. Import the backup file into Postgres (optional; you can create some records yourself if you really want to)
5. Set up your connection parameters in your environment variables
6. Generate the keys and save their paths into their environment variables (see above)

# Reproducing the problem

Assuming `{{baseUrl}}` is set to `localhost:420` in Postman.

1. Make sure you followed the preparation properly (see above).
2. `npm run dev`
3. Send a `POST` request to `{{baseUrl}}/api/v1/auth/login` with the following body:
```JSON
{
	"email": "someone@example.com",
	"pwd": "SecurePWD"
}
```
4. Send a `DELETE` request to `{{baseUrl}}/api/v1/inv/2/categories/3`

At 4. there will be an error message.
TypeORM will fail to delete the record.

---

Thanks for reading 😄

**Comment by Bernd-L** [comment]
Notice that the `Category` entity has a primary key consisting of two columns, and a self-referencing foreign key (pointing to said two columns).

**Comment by mhpe** [comment]
Why has this been closed, did you figure something out? I am also seeing this error on removal and to me it still seems like an issue.

**Comment by Bernd-L** [comment]
> Why has this been closed, did you figure something out? I am also seeing this error on removal and to me[,] it still seems like an issue.

I do not recall closing this...
Perhaps it was just an issue with my code, but I just checked my commit log of the repo in question, and there is no commit to fix this bug.

**Comment by Bernd-L** [comment]
But I do believe that I found a workaround for that.

**Comment by Crazy-kun** [comment]
I got same error while i trying to remove entity who contains another entity as column.
