### ISSUE TITLE
STI Inheritance issue

### ISSUE THREAD

**Issue by lhrolim** [typeorm/typeorm#3617]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I´m getting the following error when trying to setup a STI inheritance:

`TypeError: Cannot read property 'ownColumns' of undefined
    at /Users/luizrolim/workspace/nqa/src/metadata-builder/EntityMetadataBuilder.ts:320:64
    at Array.map (<anonymous>)
    at EntityMetadataBuilder.computeEntityMetadataStep1 (/Users/luizrolim/workspace/nqa/src/metadata-builder/EntityMetadataBuilder.ts:316:14)
    at /Users/luizrolim/workspace/nqa/src/metadata-builder/EntityMetadataBuilder.ts:108:45
    at Array.forEach (<anonymous>)`

Debugging a bit I found that the parentMetadata of the entity is marked as undefined 

I ´ve described the issue here https://stackoverflow.com/questions/54629321/typeorm-sti-inheritance-issues

Not sure what I am doing wrong, probably something silly.

Thanks

**Comment by galkin** [comment]
@Kononnable, @lhrolim do you have any updates on this issue?

**Comment by galkin** [comment]
I resolve this problem. The parent entity was not present at metastorage. I added import for parent entity and all work.
