### ISSUE TITLE
Doc with comparison operators

### ISSUE THREAD

**Issue by jdelobel** [typeorm/typeorm#362]
Is it possible to have doc for comparison operators (postgresql for my needs):

if i make

`
const posts = await connection
            .getRepository(Post)
            .createQueryBuilder("post")
            .where("post.id !=:id")
            .setParameter('id', 1);
            .execute();
`
It does not works.

How i can  use comparison operators like >, <; >=, <=, and !=?

**Comment by pleerock** [comment]
QueryBuilder creates a regular SQL query, and you write inside your database query. Your  example is correct and should work. Can you provide more details (or demo repo) with your issue, because its strange and it should work.

**Comment by pleerock** [comment]
let me know if I didnt answer your question.
