### ISSUE TITLE
Migrations: ManyToMany does not carry "default" value of new primary key

### ISSUE THREAD

**Issue by AlexandreHetu** [typeorm/typeorm#3620]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi there,

Adding a new `@PrimaryKey` column on a table that's part of a `@ManyToMany` relation results in the intermediate table not getting the `default` value set in the original table.

I've setup a small repo to demonstrate the issue here: https://github.com/AlexandreHetu/typeorm-no-default-demo

Basically, when generating a migration from this
```
@Entity()
export class Product {
    @PrimaryGeneratedColumn() key!: number;

    @Column() name!: string;

    @ManyToMany(() => Entitlement, { eager: true }) @JoinTable() entitlements!: Entitlement[];
}

@Entity()
export class Entitlement {
    @PrimaryColumn() identifier!: string;

}
```
and adding a new, non-generated primary key to one side of the relation.
```
@Entity()
export class Entitlement {
    @PrimaryColumn() identifier!: string;
    @PrimaryColumn({default: 'GOGGLES'}) company!: string;
}
```
The default value from the `company` column is properly added to the `entitlement` table but not to the `product_entitlements_entitlement` table. Which means that the migration cannot be applied on live data. The generated `alter table` statement reads like this:

        await queryRunner.query(`ALTER TABLE "product_entitlements_entitlement" ADD "entitlementCompany" character varying NOT NULL`);

I already have a fix for this issue so I'll be opening a PR. However, I have no idea how to write a test for the "migrations" part of type-orm!

Thanks

**Comment by pleerock** [comment]
I don't see reason why `default` should be applied on a junction table. Right, in your case this can help you, but it doesn't mean default should be copied to the junction table. Your case should be handled by manually created migration.
