### ISSUE TITLE
MongoDB Drivers not able to restrict the duplicate with "unique:true" flag

### ISSUE THREAD

**Issue by nbaua** [typeorm/typeorm#3624]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

We are not able to restrict the duplicate email ids to be saved to MongoDB with the @Column notation

Please check the following code value.

```typescript 
@ObjectType()
@Entity()
export class User extends BaseEntity {

    @Field(()=>ID)
    @ObjectIdColumn()
    id: number;

    @Field()
    @Column()
    firstName: string;

    @Field()
    @Column()
    lastName: string;

    @Field()
    @Column("text", {unique:true}) ////THIS IS THE 
    email: string;

    //@Field() -- Keep this hidden from GraphQL
    @Column()
    password: string;
}
```

![image](https://user-images.githubusercontent.com/17998763/52636408-83d13500-2ef2-11e9-96e4-ba38cc72c638.png)

**Comment by vlapo** [comment]
Do you use synchronize option in connection?  Please check https://github.com/typeorm/typeorm/issues/2034

**Comment by nbaua** [comment]
@vlapo

Hi,
Thanks for your input, however I guess the synchronize option is for indices, in my case I want to check uniqueness for the non-index (non-  _id) column. Do you suggest it will work regardless? Please validate.

**Comment by rustamwin** [comment]
@nbaua You should create index with unique flag
Not sure, in columns unique flag for mongodb has no effect

**Comment by vlapo** [comment]
Do not understand. it is "Unique index" https://docs.mongodb.com/manual/core/index-unique/.

**Comment by rustamwin** [comment]
Probably we add this in future to  mongodb schema building

**Comment by vlapo** [comment]
In some reason `@Column("text", { unique: true })` is not working on mongodb. We should fix this. 

But I think it is no root of @nbaua problem. If you want to check uniqueness you have to enable synchronisation of schema from entity to DB (or synchronize schema first time only) like discussed in https://github.com/typeorm/typeorm/issues/2034 and use workaround:
```typescript
@Index({ unique: true })
@Column("text")
email: string;
```

Keep open this issue as report about problem with unique `@Column("text", { unique: true })` for mongodb. PR is welcome.

**Comment by nbaua** [comment]
@vlapo, 
I'll check on @Index({ unique: true}) later some time. Thanks for your time.
