### ISSUE TITLE
Order by a computed field/column in createQueryBuilder

### ISSUE THREAD

**Issue by Skullflow** [typeorm/typeorm#3628]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi guys,

I need to order my results by a computed field with `createQueryBuilder`.

In the docs, I see that `.orderBy` wants a column as a paramenter, but I cannot compute a column (in this case a boolean colum) with `createQueryBuilder`.

Consider this simple entity:
```ts
class Store {
    @Column({ type: 'time' })
    from: string;
    
    @Column({ type: 'time' })
    to: string;

}
```

Now, i want to retrieve all products from stores and sort them in order to show first all the products available in that moment (so the store has to be open) and after all the products that are not available.

This is the raw sql query to find all stores and order them based on the availability at a specific time:

```sql
SELECT *, (:time BETWEEN stores.from AND stores.to) as is_open
FROM stores
ORDER BY is_open DESC
```

Is it possible to do this without `getRawMany`?

**Comment by vlapo** [comment]
Did you even try find solution here in issues ? :) You can do custom selects and order by:
```typescript
await connection.getRepository(Store)
        .createQueryBuilder("stores")
        .select()
        .addSelect("(:time BETWEEN stores.from AND stores.to)", "is_open")
        .orderBy("is_open")
        .getMany();
```
or use `getRawAndEntities` if you need `is_open` too.

**Comment by Skullflow** [comment]
Hi vlapo, yes I tried to find the solution in other issues, but I didn't find this particular case.

Anyway, I tried now your solutions and it works with that simple entity.

In my real case, Store entity is more complex and it can has more than one time slot (from, to) and they are handled with another entity (TimeTable) that specify even a week day.

So i create a subquery in `addSelect` like this:

```ts
await connection.getRepository(Store)
            .createQueryBuilder('store')
            .select()
            .addSelect(sq => {
                return sq
                    .select('bool_or(:day = timeTable.day AND :time BETWEEN timeTable.from AND timeTable.to)', 'is_open')
                    .from('stores', 'sqStore')
                    .innerJoin('sqStore.timeTables', 'timeTable')
                    .where('sqStore.id = store.id')
                    .setParameter('time', time)
                    .setParameter('day', 0);

            }, 'is_open')
            .orderBy('is_open', 'DESC')
```

For each store I check if it's open in at least one time slot and then with `sql bool_or` I'm able to aggregate the is_open result and assign it to every row.

Seems like to work now.

Thanks for help me to figure in out! :)

**Comment by vlapo** [comment]
You are welcome :)

**Comment by phucsang0spt** [comment]
hi @vlapo , i did the same when order by additional field and I got this error: "for SELECT DISTINCT, ORDER BY expressions must appear in select list". But there is no any DISTINCT in my sql query :|

**Comment by amiralammohawk** [comment]
@phucsang0spt  same error
