### ISSUE TITLE
Unexpected token * in tslib

### ISSUE THREAD

**Issue by alejandromorenoalberto** [typeorm/typeorm#3629]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.13` 

When I tried getManage or getConnection I'm getting the following error:

```
node_modules/typeorm/browser/index.js:1
(function (exports, require, module, __filename, __dirname) { import * as tslib_1 from "tslib";
                                                                     ^

SyntaxError: Unexpected token *
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

My app.ts looks like:

```
import express from "express";
import { Server } from "typescript-rest";
import "reflect-metadata"
import { UserController } from "./controllers/userController";
import { createConnection } from "typeorm";
import {Category} from "./models/category";


createConnection().then(conn => {
    let app: express.Application = express();

    Server.buildServices(app, UserController);
    Server.swagger(app, './src/config/swagger.json', '/api-docs');
    conn.getRepository(Category).find().then(results=>console.log(results))

    app.listen(3000, function() {
        console.log('Rest Server listening on port 3000!');
    });
});
```

I'm only trying to get connection and build queries, that's why I'm executing conn.getRepository(Category).find().then(results=>console.log(results)) in app.ts

Thanks!

**Comment by vlapo** [comment]
Hey @webleaf. Could you please check also?

**Comment by webleaf** [comment]
It's not problem with tslib.
`SyntaxError: Unexpected token *` means such import syntax not supported by your ES version.
It's problem about ES5/ES6/ES7. Check your tsconfig.
Also I don't understand, why error appear in `typeorm/browser`, if you import just `typeorm` (you should use `typeorm`, not `typeorm/browser` in node.js)

**Comment by OdedCohenGadol** [comment]
it happened to me too, the problem occurred because i've accidently imported 'BaseEntity' from 'typeorm/browser' instead of 'typeorm'.

the first one is js file, and the second is ts file.

**Comment by pleerock** [comment]
Yes, please be careful when you auto-import in your IDE. If you aren't using browser version of typeorm you must import from "typeorm" instead of "typeorm/browser".

**Comment by chriszrc** [comment]
Yeah, I ran into this when another project changed the module type in the shared tsconfig file from:

```
"module": "commonjs",
```

to

```
"module": "esnext",
```

**Comment by dgreene1** [comment]
For me, the problem was solved by correcting the entity location to use the post-transpilation files. I figured that out from this SO answer: https://stackoverflow.com/a/52785365/706768

So my .ormconfig looks like this now:
```
                ...
                entities: [`${__dirname}/entities/*{.js,.ts}`],
                migrations: [`${__dirname}/migrations/*{.js,.ts}`],
                subscribers: [`${__dirname}/subscribers/*{.js,.ts}`],
                ...
```

**Comment by MikeInSwitzerland** [comment]
I didn't use to have this error, until I recently reinstalled Windows 10, then installed the latest NodeJS, Angular CLI, etc.

What I had forgotten to do was install TypeScript.

`npm install –g typescript`

So, if anyone's getting this strange error when trying to run their Angular application on a "fresh" PC, check that you have TypeScript installed, using:

`tsc -v`
