### ISSUE TITLE
EntityManager can't save/delete 2 unrelated entity types in a single persist/remove call

### ISSUE THREAD

**Issue by CWSpear** [typeorm/typeorm#363]
TypeORM: 0.9
Node: 6.10.0
Postgres: 9.6.2

Consider 2 entities that have no relation and 2 fields, `id` and `name`:

```ts
const banana = new Banana();
banana.name = 'The Awesome Banana';

const apple = new Apple();
apple.name = 'The Awesome Apple';

await connection.entityManager.persist([banana, apple]);
```

I would expect this to save a row in the `apple` table and a row in the `banana` table, but it saves 2 rows in the `banana` table.

This _may_ be intentional, but seems like a bug to me? Especially looking at the code, it seemed like it wasn't doing anything that should cause it to do this behavior.

**Comment by CWSpear** [comment]
(This maybe deserves its own ticket:) Should multiple entities being persisted all be in one transaction? This creates a transaction for each entity, but it may be nice/desired/make sense that a single persist call is all wrapped in one big transaction, even if passed in multiple entities.

**Comment by pleerock** [comment]
right thats an issue. You can fix it [there](https://github.com/typeorm/typeorm/blob/master/src/entity-manager/EntityManager.ts#L106) don't use constructor of the first object, instead use constructor of each entity. Or wait until I do.

> single persist call is all wrapped in one big transaction

yeah probably its better to do it this way

**Comment by CWSpear** [comment]
Ah, whoops, I was originally looking at the `persist` for a Repository. I can set up a PR for the first issue.

**Comment by CWSpear** [comment]
I noticed the same behavior in `entityManager.remove` and handled both in #364.
