### ISSUE TITLE
Query fails if In() array is empty

### ISSUE THREAD

**Issue by nomadoda** [typeorm/typeorm#3630]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The following query returns authors with id 1, 3 and 7:

```
const shifts = await getRepository(Author)
    .createQueryBuilder('a')
    .where('a.id IN (:...authorIds)', { authorIds: [1, 3, 7] })
    .getMany();
```

The same query with an empty array throws an exception:

```
const shifts = await getRepository(Author)
    .createQueryBuilder('a')
    .where('a.id IN (:...authorIds)', { authorIds: [] })
    .getMany();
```

**Expected outcome**:

Return an empty array (Author[])

**Actual outcome**:

Error: ("message": "syntax error at or near \")\"")

**Comment by vlapo** [comment]
Hey @nomadoda. You are creating custom where statement so you have to handle empty array case in your code (check https://github.com/typeorm/typeorm/issues/2417). It should be too complex handle this in ORM. 

But we have `In` operator in typeorm. But right now we have issue with empty array, too. Please check https://github.com/typeorm/typeorm/issues/2195.

Close this issue in favour of https://github.com/typeorm/typeorm/issues/2195.
