### ISSUE TITLE
TypeORM QueryRunner Select distinct

### ISSUE THREAD

**Issue by Dharita** [typeorm/typeorm#3633]
**Issue type:**
[x] question

**Database system/driver:**
[x] `mysql` 

**TypeORM version:**
[x] 0.2.9

SQL:
`Select distinct ports.port_name from orders left join port_master on orders.officeId = ports.portId;`
How to write above SQL using typeorm query runner to select the distinct port name? Below syntax fetches all the ports
`await queryRunner.manager.find(Orders, { relations: ["ports"], where: filter }).then((result: any) => { orders = result; });`

[https://stackoverflow.com/questions/54666465/typeorm-queryrunner-select-distinct](url)

**Comment by vlapo** [comment]
I think you have to use custom query builder http://typeorm.io/#/select-query-builder and `getRawMany()` method.

Something like:
```typescript
await connection.getRepository(Orders)
    .createQueryBuilder('orders')
    .select('DISTINCT ports.port_name', 'port_names')
    .leftJoinAndSelect("orders.offices", "ports")
    .where(...)
    .getRawMany()
```
Note: This is just a "pseudocode". Did not test it. I do not know your entity definitions. Please check docs.

**Comment by sandeshgb** [comment]
adding leftJoinAndSelect puts all the fields of the relation into the query and we get the syntax error 'syntax error at or near "Distinct"'.

**Comment by edge721** [comment]
`await connection.getRepository(Orders)
    .createQueryBuilder('orders')
    .leftJoinAndSelect("orders.offices", "ports")
    .distinctOn(['ports.port_name'])
    .where(...)
    .getRawMany()`
