### ISSUE TITLE
Remove Callbacks not firing with Postgres

### ISSUE THREAD

**Issue by ediewoelfle** [typeorm/typeorm#3639]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When I remove a Person, the `@BeforeRemove()` callback is not triggering. I have no issues with inserts or updates on the same model. 

**Person.ts**
```
/* eslint-disable no-unused-vars */
import {
  BaseEntity,
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinTable,
  ManyToMany,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  OneToOne,
  OneToMany,
  AfterInsert,
  AfterUpdate,
  BeforeRemove
} from 'typeorm'

@Entity()
class Person extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column()
  firstName: string

  @Column()
  lastName: string

  @Column('date', { nullable: true })
  birthdate?: string

  @CreateDateColumn()
  createdAt: Date

  @UpdateDateColumn()
  updatedAt: Date

  @AfterInsert()
  @AfterUpdate()
  updatePerson() {
      console.log('updated person')
    })
  }

  @BeforeRemove()
  deletePerson() {
    console.log('------------ delete person')
  }
}

export default Person

```

**Mutation.ts**
```
deletePerson: async (_, args) => {
    const { id } = args

    await Person.delete(id)
    return true
  }
```

**Comment by OrlandoCo** [comment]
Try with remove function, according to the documentation:

> You can define a method with any name in the entity and mark it with @BeforeRemove and TypeORM will call it before a entity is removed using repository/manager **remove**.

**Comment by ediewoelfle** [comment]
@OrlandoCo thanks - good catch. I've changed it over to remove and it works as expected.
