### ISSUE TITLE
Cannot use environment variables in .env with multiple connections

### ISSUE THREAD

**Issue by bugkarma** [typeorm/typeorm#3641]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

Predefined environment variables can be used in the .json, or .env config files, but only for a single connection.

I propose adding a numerical suffix to the database environment variables to allow for an n-number of database connections.

**Comment by Kononnable** [comment]
From 0.4.0 TODOs:
`    * (breaking) re-work current configuration loading and ormconfig file concept`
We will probably remove support for typeorm configuration through environment variables, so that FR would probably be implemented in another way. However I will keep it open till decisions how configuration should be changed are final.

**Comment by DigivolveIo** [comment]
Plz don't remove .env support, maybe just add a digit to indicate the second or third connection

**Comment by euaaron** [comment]
It would be really useful to have this functionality as @DigivolveIo suggested... this way I would be able to use mongo and postgres simultanially without leaving all connection info available to others on a public repository.

**Comment by imnotjames** [comment]
> Plz don't remove .env support, that would significantly reduce the desirability of typeorm, maybe just add a digit to indicate the second or third connection.
> Any update on this issue?

No.

You can accomplish this by writing a wrapper around TypeORM configuration instead should you want it.  This is probably what we'll release as a separate package once this has been phased out from the core.

The reason for it is that `.env` configuration as it stands had caused far more pain than the ease of use it might bring to some people.  It limits the use of typeorm in various frameworks, for example.  It also means a spurious `.env` file can be used to maliciously overwrite the expected environment variables.

**Comment by imnotjames** [comment]
We are not planning on implementing this feature so I'll be closing the issue.
