### ISSUE TITLE
How to check if a row exists in an entity?

### ISSUE THREAD

**Issue by lenikhilsingh** [typeorm/typeorm#3642]
**Issue type:**

[ ] question

**Database system/driver:**

[ ] `mysql` 

**TypeORM version:**

[ ] `latest`

I have to check if a particular email id exists in my entity , `Users`. How can i do that?
`let user = await User.find({ where: { email: email } })`
`return user === undefined`
This code above gives random answer.

**Comment by vlapo** [comment]
Try `count` method

**Comment by vegerot** [comment]
@vlapo using `Repository.count` will not terminate after finding the first result.  The best answer should be something like 

```javascript
await User.exists({ where: { email: email } })
```

However, for some reason this is not implemented in TypeORM (#2815)

**Comment by ameenpv** [comment]
> However, for some reason this is not implemented in TypeORM (#2815)

#9303 Its done now, but docs are pending
