### ISSUE TITLE
FindOneOptions["where"] type

### ISSUE THREAD

**Issue by tlaziuk** [typeorm/typeorm#3644]
**Issue type:**

- [x] question
- [x] bug report
- [ ] feature request
- [x] documentation issue

**Database system/driver:**

- [ ] `cordova`
- [ ] `mongodb`
- [ ] `mssql`
- [ ] `mysql` / `mariadb`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `sqlite`
- [ ] `sqljs`
- [ ] `react-native`
- [ ] `expo`

**TypeORM version:**

- [ ] `latest`
- [ ] `@next`
- [x] `0.2.13` (and previous versions)

**Steps to reproduce or a small repository showing the problem:**

according to doc (https://github.com/typeorm/typeorm/blob/0.2.13/docs/find-options.md) results can be filtered by the `where` find option and alternative conditions (`OR`) can be separeted by passing an array of conditions to that option,

yet the type doesn't reflect that, is there any particular reason why the type `Array<FindConditions<Entity>>` isn't there? https://github.com/typeorm/typeorm/blob/0.2.13/src/find-options/FindOneOptions.ts#L18

**Comment by Diluka** [comment]
> yet the type doesn't reflect that, is there any particular reason why the type `Array<FindConditions<Entity>>` isn't there? https://github.com/typeorm/typeorm/blob/0.2.13/src/find-options/FindOneOptions.ts#L18

https://github.com/typeorm/typeorm/blob/4448f4a5553454c391aaf448fbed1f68f2b479e8/docs/find-options.md#L49-L58
