### ISSUE TITLE
TypeORM error => name: 'AlreadyHasActiveConnectionError'

### ISSUE THREAD

**Issue by Domiserver** [typeorm/typeorm#3649]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.13` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
These are the layers:
* Express-graphql
* TypeORM
* PostgreSQL

I was able to insert a table and a row.
When I try to insert a new record, I get the following TypeORM error: 

`{ AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.
    at new AlreadyHasActiveConnectionError (/home/ronew/Documents/basicotypeorm/node_modules/typeorm/error/AlreadyHasActiveConnectionError.js:10:28)
    at ConnectionManager.create (/home/ronew/Documents/basicotypeorm/node_modules/typeorm/connection/ConnectionManager.js:51:23)
    at Object.<anonymous> (/home/ronew/Documents/basicotypeorm/node_modules/typeorm/index.js:196:66)
    at step (/home/ronew/Documents/basicotypeorm/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/ronew/Documents/basicotypeorm/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/home/ronew/Documents/basicotypeorm/node_modules/tslib/tslib.js:104:62)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  name: 'AlreadyHasActiveConnectionError',
  message:
   'Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.' }`

PS: I read issue https://github.com/typeorm/typeorm/issues/592 from June 2017 but it didn't help.

#typeorm #error

**Comment by Kononnable** [comment]
@Domiserver How are we supposed to reproduce the issue? We don't know your code so we have no idea on what exactly are you doing wrong.

**Comment by Domiserver** [comment]
@Kononnable thanks. Here is the missing code.   I am able to create a table and insert a raw but when I try to add a second to PostgreSQL using http://localhost:3000/graphql I get the error posted above. 

Below is the index.ts file.


    `import "reflect-metadata";
const express = require('express');
const bodyParser = require('body-parser');
const graphqlHttp = require('express-graphql');
const { buildSchema } = require("graphql");

import {createConnection} from "typeorm";
import {getConnection} from "typeorm";

import {User} from "./entity/User";
const { Event } = require("./entity/Event");

// Communication between the Server and the Browser
const app = express();
app.use(bodyParser.json());

app.use(
    '/graphql',
    graphqlHttp({
        schema: buildSchema(`
            type Event {
                _id: ID!
                title: String
                description: String!
                price: Int
                date: String!
            }

            input EventInput {
                title: String!
                description: String!
                price: Int
                date: String!
            }
                
            type RootQuery{
                events: [Event!]!
            }
    
            type RootMutation {
                createEvent(eventInput: EventInput): Event
            }
    
            schema {
                query: RootQuery
                mutation: RootMutation
            }    
    `),
    rootValue: {
        events: ()  => {
            return Event;
        },
        createEvent: (args: any) => {
        
        // Communication between the Server and PostgreSQL
            createConnection().then(async connection => { 
           
            const event =
                await getConnection()
                .createQueryBuilder()
                .insert()
                .into(Event)
                .values([
                    { id: args.eventInput.title,
                    title: args.eventInput.title,
                    description: args.eventInput.description,
                    price: args.eventInput.price,
                    date: new Date(args.eventInput.date)  }
                 ])
                .execute();                    
                })
                .catch(error => console.log(error));
      }
     },
    graphiql: true
    })
);
// Testing communications between the Server and the Browser
app.get('/', (req:any, res:any, next:any) => {
    res.send('Confirmation message posted on http://localhost:3000 ');
})

createConnection().then(() => {
    app.listen(3000);
});`

**Comment by wowtrxqn** [comment]
怎么解决的

**Comment by jayan2019** [comment]
In my case I used 
```
if (error.constructor === AlreadyHasActiveConnectionError) {
    return findConnection();
}
```
and the ```findConnection``` 

```
try {
   const connection = await getConnection();
   setConnection(connection);
} catch (error) {
   console.log(error);
}
```
