### ISSUE TITLE
Security multi-company association 

### ISSUE THREAD

**Issue by engineer999** [typeorm/typeorm#3652]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.13` 

**Steps to reproduce or a small repository showing the problem:**

**Problem:** a company can associate records that are not theirs, just by informing the id in the relationship

**Scenario:** My api is multi-company and each company manage your records (products, orders...), but these companies can only view and use records that belong to them. However, it is possible to enter an id of a product of another company in an order and should not

**Example:** The Apple company can only inform the iPhone product in its orders, if it tried to inform the Google Pixel should have some error message

**Observations:** I hope I do not need to validate each record associated with the order before saving because my actual schema has multiple relationships (20 tables associated with a order, some 2 level cascade) and this is only small example. It would be very complicated to search the database for each product and verify that it belongs to the company. I think it would be possible to prevent this recording with some index setting

**Question:** How can I prevent associating records from other companies with current company records, even reporting the id on body request?

I would appreciate your help, since I have a system in production with this situation.

**company.entity.ts**
```company.entity.ts
@Entity()
export class Company {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToMany(() => Product, (product) => product.company)
  products: Product[];

  @OneToMany(() => Order, (order) => order.company)
  orders: Order[];
}
```

**product.entity.ts**
```product.entity.ts
@Entity()
export class Product {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  description: string;

  @ManyToOne(() => Company, (company) => company.products)
  company: Company;
}
```

**order.entity.ts**
```order.entity.ts
@Entity()
export class Order {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  description: string;

  @ManyToOne(() => Company, (company) => company.orders)
  company: Company;

  @ManyToMany(() => Product)
  @JoinTable()
  products: Product[];
}
```

**order.controller.ts**
```order.controller.ts
@Controller('orders')
export class OrderController {

  constructor(
    @InjectRepository(Order)
    public repository: Repository<Order>,
  ) { }

  @Post()
  public async create(@Body() body: Order): Promise<Order> {
    body.id = undefined;
    body = await this.repository.save(body);
    return await this.repository.findOne(body.id, { relations: ['products'] });
  }

  @Put(':id')
  public async update(@Param('id') id, @Body() body: Order): Promise<Order> {
    body.id = Number(id);
    await this.repository.save(body);
    return await this.repository.findOne(id, { relations: ['products'] });
  }
}
```

**Company table**
![image](https://user-images.githubusercontent.com/47681047/52899927-07cb3b80-31d7-11e9-9231-5783dcbb9c4c.png)
**Item table**
![image](https://user-images.githubusercontent.com/47681047/52899915-e9fdd680-31d6-11e9-8b73-12e78d30009b.png)

**POST http://localhost:3040/orders** 
Body Request:
Obs.: here the user informs the iPhone which is a product that he knows, and forces the product id 2 being an unknown product, because api GET validate which products are visible to Apple, in this case only the iPhone
```json
{
    "company": 1,
    "description": "Order 001",
    "products": [
        {
            "id": 1,
            "description": "iPhone"
        },
        {
            "id": 2
        }
    ]
}
```
Body Response:
Obs.: even informing the product of another company, on the return of the api is presented the Google Pixel that could not be recorded at Apple's order. Here you should have an error message
```json
{
    "id": 2,
    "description": "Order 001",
    "products": [
        {
            "id": 1,
            "description": "iPhone"
        },
        {
            "id": 2,
            "description": "Google Pixel"
        }
    ]
}
```

**Result Tables**
Order table
![image](https://user-images.githubusercontent.com/47681047/52900094-f71bc500-31d8-11e9-9258-9466faf6723e.png)

Order Product table
![image](https://user-images.githubusercontent.com/47681047/52900111-3b0eca00-31d9-11e9-9367-b3266ad48e66.png)

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
This looks more like `stackoverflow` question.

**Comment by engineer999** [comment]
Ok, i create a question there
https://stackoverflow.com/questions/54797858/security-multi-company-association

**Comment by Kononnable** [comment]
Closing since question was moved to SO and an answer was given there.
