### ISSUE TITLE
Paramters empty when using an array of multiple items with insert() and querybuilder

### ISSUE THREAD

**Issue by Murahnus** [typeorm/typeorm#3658]
**Issue type:**

[X] question
[?] bug report
[ ] feature request
[?] documentation issue

**Database system/driver:**

[X] `sqlite`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,
I have a model that has a field for a unique string, an auto-generated ID, and some more fields including relations.
```
@Entity()
export class Example {
  @PrimaryGeneratedColumn()
  id: number

  @Column({
    type: 'varchar',
    length: 256,
    unique: true,
  })
  uniqueName: string
 
  ... more fields
}
```
I am creating new items of said structure and want to `insert` them using the query builder.
```
newItem: IExample = {}
newItem.uniqueName = 'someName'
newItem.someOtherField = 9
connection.createQueryBuilder().insert().into('example').values([newItem]).execute()
```

This works, but since I would like to save more than one item at once, I tried to do this:
```
newItemList: IExample[] = []
<iteration with newItemList.push(newItem)>
connection.createQueryBuilder().insert().into('example').values(newItemList).execute()
```
This fails because `uniqueName` would be `NULL`. Before the failed insert, typeorm sends a query like this: `
SimpleConsoleLogger.ts:28 query: SELECT COUNT(DISTINCT("Example"."id")) as "cnt" FROM "example" "Example" WHERE "Example"."uniqueName" = ? -- PARAMETERS: ["myUniqueString"]`
It uses the paramters for `uniqueName` inside the array, but on `insert` it suddenly has them all set to `NULL`: `query: INSERT INTO "example"("uniqueName", "otherName", "val1", "val2", "val3", "relation1Id", "relation2Id") VALUES (NULL, NULL, NULL, NULL, ?, NULL, NULL) -- PARAMETERS: [0]`

**Comment by vlapo** [comment]
I am sorry but I cannot reproduce your issue. My entity:
```typescript
@Entity()
export class DbEntity {
    @PrimaryGeneratedColumn()
    id: string;

    @Column({
        type: 'varchar',
        length: 256,
        unique: true,
    })
    uniqueName: string;
}
```
and code with insert:
```typescript
const repo = connection.getRepository(DbEntity);
const arr = [];
for (let index = 0; index < 3; index++) {
    const entity = new DbEntity();
     entity.uniqueName = "asd" + index;
     arr.push(entity);
}
await connection.createQueryBuilder().insert().into(DbEntity).values(arr).execute();
```
Are you sure your `uniqueName` is not undefined? Please check all on your side or post working example here,

**Comment by Kononnable** [comment]
Closing as no response from the author.
