### ISSUE TITLE
Is there any way to save date with with timezone +00:00 in mssql

### ISSUE THREAD

**Issue by trantuat** [typeorm/typeorm#3660]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.11`

**Steps to reproduce or a small repository showing the problem:**

Hi team,

I have a entity named Test:

```typescript
export class Test {
    
    @CreateDateColumn({
        type: 'datetimeoffset',
        default: () => 'getutcdate()'
    })
    createdAt: Date;

    @Column({
        type: 'datetimeoffset',
        nullable: true
    })
    deletedAt: Date;
}
```
When creating a record, createdAt save the time '2019-02-18 02:50:47.9670000 +00:00'.
However, when I update field deleledAt, database will save the time '2019-02-18 10:01:47.3420000 +07:00'. Data saved is correct, but it's inconsistence between timezone createdAt and deleledAt (createdAt: +00:00, deleledAt: +07:00). So is there any way to make deleledAt will save the time  '2019-02-18 03:01:47.3420000 +00:00' ?. 

`UPDATE "Test" SET "deletedAt" = @0 -- PARAMETERS: [{"value":"2019-02-18T07:57:47.342Z","type":"datetimeoffset","params":[]}]`

Thanks.

**Comment by Kononnable** [comment]
If you don't want to specify the timezone wouldn't it be better to use column type which doesn't save timezone information? In current scenario you're wasting space in db(which also affect performance etc.).

**Comment by trantuat** [comment]
> f you don't want to specify the timezone wouldn't
I need to save timezone. My problem is the value that's saved in createdAt and deletedAt is inconsistency. One saved "2019-02-18 02:50:47.9670000 +00:00'" and other one saved "2019-02-18 10:01:47.3420000 +07:00". You can see, timezone is different.

**Comment by Kononnable** [comment]
What's the point of saving timezone if you always want to reset it to 0?

First let's see what timezone should be set 'by default':
createdAt - it's populated by the db - it's using db server timezone
deletedAt - it's populated by client(node app) - it's using timezone of machine node is running

However `getutcdate()` returns datetime which doesn't contains timezone offset(will always be +0). So the only way to have both column with equal timezone offset is to reset set timezone to 0 on node side. And here comes a problem - as far as I know tedious(mssql driver for node) doesn't support setting different timezone. You can change `useUTC` option passed to `createConnection` - it might help, but I don't think it would be enough on its own.

But either way - if you wan't to always set timezone offset to zero you don't need a column with timezone offset.
