### ISSUE TITLE
Generate db schema diagram from migrations

### ISSUE THREAD

**Issue by yogevlahyani** [typeorm/typeorm#3662]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

It will be great to have a tool that generates visual db schema diagram in order to present it in the readme and keep track with the db design.
Also, it will be great to have it in the other direction, generate entities from a db schema diagram.

For example, I use [plantuml](http://plantuml.com/) in order to create a visualize db schema diagram which I need to update manually for any changes I do with the db structure.

Some repo's I found that might be helpful:
https://github.com/grafov/plantuml2mysql
https://github.com/Hywan/Database-to-PlantUML

**Comment by vlapo** [comment]
I dont think this should be part of typeorm :) But if you will create some lib compatible with typeorm api we can add link to README.

**Comment by eugene-manuilov** [comment]
Hey @yogevlahyani 

I have created a npm package that helps to generate db schema diagrams based on Typeorm entities. Do you mind to look at it? https://www.npmjs.com/package/typeorm-uml

Just install it as a dev dependency and run it. It will output an URL to your diagram.

**Comment by eugene-manuilov** [comment]
@vlapo do you mind to add `typeorm-uml` to the `Extensions` list in the README file?
