### ISSUE TITLE
getRepository generic over abstract class shows confusing behaviour

### ISSUE THREAD

**Issue by mdolgich** [typeorm/typeorm#3665]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hello dear typeorm developers and community,
Currently I am taking my first steps in this most amazing API. Now I have implemented a couple classes and I ran into a problem which I don't quite understand and I hope you can help me with it. I have implemented an abstract class 
```
import { Entity, PrimaryGeneratedColumn } from 'typeorm';
@Entity()
export abstract class DbEntity {
    @PrimaryGeneratedColumn()
    id!: string;
    public abstract update(data: { [key: string]: any }): void;
}
```
and a User class that inherits from it 
```
@Entity()
export class User extends DbEntity {
    @Column()
    userName!: string;
    ...
}
```
Now I tried to implements some general functions over my `DbEntity` with a new class 
```
export class DbInteraction {
    private repository: Repository<DbEntity>;
    constructor(repository: Repository<DbEntity>) {
        this.repository = repository;
    }
    public async checkExistenceById(id: string): Promise<boolean> {
        return (await this.repository.findByIds([id])).length !== 0;
    }
    ...
}
```
Now I am trying to use the interaction class in my extended `Connection` like this:
```
export class DbConnection extends Connection {
    public userInteraction: DbInteraction;

    constructor(config: DatabaseConfig) {
        super(...);
        this.userInteraction = new DbInteraction(this.getRepository(User));
    }
```
I get the following Error from my typescript compiler (version 3.0.1):
```
Argument of type 'Repository<User>' is not assignable to parameter of type 'Repository<DbEntity>'.
  Types of property 'count' are incompatible.
    Type '{ (options?: FindManyOptions<User> | undefined): Promise<number>; (conditions?: FindConditions<User> | undefined): Promise<number>; }' is not assignable to type '{ (options?: FindManyOptions<DbEntity> | undefined): Promise<number>; (conditions?: FindConditions<DbEntity> | undefined): Promise<number>; }'.
      Types of parameters 'options' and 'options' are incompatible.
        Type 'FindManyOptions<DbEntity> | undefined' is not assignable to type 'FindManyOptions<User> | undefined'.
          Type 'FindManyOptions<DbEntity>' is not assignable to type 'FindManyOptions<User>'.
            Type 'DbEntity' is not assignable to type 'User'.

          this.userInteraction = new DbInteraction(this.getRepository(User));
```
I'm not sure what I'm to do about it. I kindly ask for your help

Kind regards
Maxim
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
This looks like some kind of problem in your code. Are you sure you have right `User` class imported in your `DbConnection` class? I try this in one TS file and everything is ok.

**Comment by mdolgich** [comment]
Hello @vlapo,
Sorry for the late answer. I have done some further investigation and I have found out that the problem occurs if the `strict` mode of the tsc compiler is on. 

```
{
    "compilerOptions": {
        "module": "commonjs",
        "strict": true,
        "target": "es6",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true
    },
    "include": ["*"]
}
```
is a minimal `tsconfig.json` that reproduces the behaviour together with the sample code.

**Comment by mdolgich** [comment]
```
 this.userInteraction = new DbInteraction(
            this.getRepository<DbEntity>(User),
```
removes the compile error, though.

**Comment by vlapo** [comment]
Glad to hear you resolved your problem :)
