### ISSUE TITLE
Date column is string

### ISSUE THREAD

**Issue by shendaras** [typeorm/typeorm#3666]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x]  `0.2.13` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have several entities whose definitions contain columns like the following (with many fields and other parts removed):
```ts
    @Column("date", {
        nullable: false,
        primary: true,
        name: "StartDateKey",
    })
    startDateKey: Date;
```

I had expected that the type of `startDateKey` would be a `Date` object, but after I got errors when calling `startDateKey.getTime()` I realized that this in fact returns a string value.  

Issue #2176 seemed to indicate this might be the expected behavior.  It was unclear to me from reading that issue whether or not `date` column types were simply stored as string values when saving or if they were always string values with no translation to the `Date` type.

I checked the tests and see that a function under DateUtils gets called:

 https://github.com/typeorm/typeorm/blob/23f350f1a97a3e831ab0fe3f4a11ad25d4593dc7/test/functional/database-schema/column-types/mssql/column-types-mssql.ts#L98 

Should I be using this function or duplicating its functionality whenever I have a `date` column type?

**Comment by vlapo** [comment]
Yes this is expected behaviour. Only full datetime is mapped into Date object. You can use `transformer` (http://typeorm.io/#/entities) to transform string into date. But `DateUtils` is not exported out of typeorm as public, so you have to use your own trasformation function.

**Comment by tncbbthositg** [comment]
I'm having the same issue, except that the transformer doesn't seem to work.  It's actually kind of interesting.  It looks like the value is a date going into the database and coming out.  Then, Type ORM converts it to a string before assigning it to the entity.

I've created a an interface for typed transformers and a date transformer like so:
```
export interface TypedTransformer<TEntity, TDatabase> {
  to: (entityValue: TEntity) => TDatabase;
  from: (databaseValue: TDatabase) => TEntity;
}

export const dateTransformer: TypedTransformer<Date, string> = {
  to: (value: Date) => { return value.toISOString() },
  from: (value: string) => { return new Date(value); }
} as const;
```

I added the transformer to the column definition, but still the value is a string!!
```
  @Column({ transformer: dateTransformer }) dataPublicationDate!: Date;
```

Funny thing is that it's a date coming out of the database!!

If I change my transformer to this, I can call date methods on the database value:
```
export const dateTransformer: TypedTransformer<Date, string> = {
  to: (value: Date) => { console.log(value.toISOString()); return value.toISOString() },
  from: (value: string) => { console.log((value as unknown as Date).toISOString()); return new Date(value); }
} as const;

//  console.log src/entities/transformers/dateTransformer.ts:4
//    2019-09-03T00:00:00.000Z

//  console.log src/entities/transformers/dateTransformer.ts:5
//    2019-09-03T00:00:00.000Z
```

I tried various other types like `timestamp`, `Date`, `raw`, etc., but I still always get a string.

Any idea how I force TypeORM to leave the date as a Date as it comes out of the database?

**Comment by kapik** [comment]
I think `transformer` are not apply for all query 😢
