### ISSUE TITLE
OneToManySubjectBuilder issue since 0.2.12

### ISSUE THREAD

**Issue by GM-Alex** [typeorm/typeorm#3668]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.12`

Since 0.2.12 I'm getting the following error messages:

 TypeError: Cannot read property 'find' of undefined
     at /app/src/persistence/subject-builder/OneToManySubjectBuilder.ts:119:90
     at Array.forEach (<anonymous>)
     at OneToManySubjectBuilder.buildForSubjectRelation (/app/src/persistence/subject-builder/OneToManySubjectBuilder.ts:78:25)
     at /app/src/persistence/subject-builder/OneToManySubjectBuilder.ts:42:22
     at Array.forEach (<anonymous>)
     at /app/src/persistence/subject-builder/OneToManySubjectBuilder.ts:36:49
     at Array.forEach (<anonymous>)
     at OneToManySubjectBuilder.build (/app/src/persistence/subject-builder/OneToManySubjectBuilder.ts:35:23)
     at EntityPersistExecutor.<anonymous> (/app/src/persistence/EntityPersistExecutor.ts:104:63)
     at step (/app/node_modules/tslib/tslib.js:133:27)

**Comment by vlapo** [comment]
Hi. Provide please entity definitions and small code when this problem occurs.

**Comment by GM-Alex** [comment]
Sure. Here is an minimal example:

```typescript
@Entity()
@Unique(["shopId", "productId"])
export default class Product {
    @PrimaryGeneratedColumn()
    public readonly id: number;

    @Column("datetime")
    public lastFullUpdate: Date;

    @Column()
    public readonly shopId: string;

    @Column()
    public readonly productId: string;

    @OneToMany((type) => (ProductPrice), (productPrice) => (productPrice.product), {cascade: true})
    public priceHistory: Promise<ProductPrice[]>;

    @OneToMany(
        (type) => (ProductAttributeValue),
        (productAttributeValue) => (productAttributeValue.product),
        {cascade: true}
    )
    public attributeValues?: Promise<ProductAttributeValue[]>;
}
```

```typescript
@Entity()
export default class ProductPrice {
    @PrimaryGeneratedColumn()
    public readonly id: number;

    @ManyToOne((type) => (Product), (product) => (product.priceHistory))
    public product: Product;

    @UpdateDateColumn()
    public date: Date;

    @Column("float")
    public price: number;
}
```

```typescript
const productRepository = connection.getRepository<Product>(Product);
   
let product = await productRepository.findOne({
    where: {
        shopId: "someShopId",
        productId: "someProductId"
    }
});

const priceHistory = await product.priceHistory;
await productRepository.save(product);
```

Loading and saving a product works like expected but if I load the price history and try to store it again the error occurs.

**Comment by Kononnable** [comment]
Confirmed bug on 0.2.12, but after upgrading to 0.2.15 it's working as expected.
