### ISSUE TITLE
Old version of column is rewriting new version of column

### ISSUE THREAD

**Issue by isiah-lloyd** [typeorm/typeorm#3669]
**Issue type:**

[ ] question
[ X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I previously had a column that was set as a Boolean, I then changed it to a string in the entity. When TypeORM is synchronizing, I see that it's creating the new string column and then altering it to a Boolean. 
Console output on startup: 
```
query: ALTER TABLE "registrant" DROP COLUMN "confirmedAttendance"
query: ALTER TABLE "registrant" ADD "confirmedAttendance" text
query: ALTER TABLE "registrant" DROP COLUMN "confirmedAttendance"
query: ALTER TABLE "registrant" ADD "confirmedAttendance" boolean NOT NULL DEFAULT false
query: COMMIT
```
Entity (truncated):
```ts
  @IsString()
  @Column('text', {
    nullable: true,
  })
  confirmedAttendance: string;
```
This is the only instance of confirmedAttendance in the entity. I have tried droping the table and letting TypeORM create the schema from scratch with the same results. 

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
This have to be something on your side. I do not see any way how typeorm can know about previous boolean type. Try recompile your TS sources and maybe create reproduction with minimal entity setup.

**Comment by Kononnable** [comment]
Closing as no response from the author.
