### ISSUE TITLE
Indices in javascript schema.

### ISSUE THREAD

**Issue by oskr** [typeorm/typeorm#367]
Hello, 
Is there any way to create indices in javascript schema?
This feature is documented only with decorators but the usage in javascript is missing

Tried:

```javascript
module.exports = {
    name: "Category",
    columns: {
        id: {
            primary: true,
            type: "int",
        },
        name: {
            index: true,  //setting index here
            type: "string"
        }
    }
};
```

Also tried
```javascript
...
name:{
       index:{ //index metadata like @Index params
             name: "INAME"
       }
}
...
```
or with the indices property at schema level:
```javascript
...
name: "Category",
indices:[
         {
              name: "INAME",
              columns: ["name"]
         }
]
...
```

Is this feature supported on javascript or only for typescript using decorators?

**Comment by pleerock** [comment]
no, this is not implemented yet. But something we need to do

**Comment by pleerock** [comment]
@iz-iznogood this is now supported by the latest entity schema changes, right?

**Comment by iz-iznogood** [comment]
Yes it works fine
