### ISSUE TITLE
ER_TRUNCATED_WRONG_VALUE_FOR_FIELD on changing relationship type/column

### ISSUE THREAD

**Issue by randomAccessMe** [typeorm/typeorm#3670]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
import {Column, Entity, JoinColumn, ManyToOne, OneToOne, PrimaryGeneratedColumn} from "typeorm";
import {Order} from "./Order";
import {OrderLine} from "./OrderLine";

@Entity()
export class ShipmentInfo
{
    @PrimaryGeneratedColumn()
    id:number;

    @Column()
    name:string;

    @ManyToOne(type => Order)
    @JoinColumn()
    order: Order
}
```
Changed ManyToOne relation to a OneToOne with a different model
```
import {Column, Entity, JoinColumn, ManyToOne, OneToOne, PrimaryGeneratedColumn} from "typeorm";
import {Order} from "./Order";
import {OrderLine} from "./OrderLine";

@Entity()
export class ShipmentInfo
{
    @PrimaryGeneratedColumn()
    id:number;

    @Column()
    name:string;

    @OneToOne(type => OrderLine)
    @JoinColumn()
    line: OrderLine
}
```

received the following error on syncing the db

> ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'NULL' for column 'lineId' at row 1

**Workaround:** 

1. I managed to get the change I needed by deleting the column relation completely e.g: 
```
export class ShipmentInfo
{
    @PrimaryGeneratedColumn()
    id:number;

    @Column()
    name:string;

    // @OneToOne(type => OrderLine)
    // @JoinColumn()
    // line: OrderLine
}
```

2. Allowing the db to sync 
3. Adding new relation 
4. Synced again
5. Tada everything works

Thought I'd report this either way

**Comment by Kononnable** [comment]
That is expected behavior.
Migrations/schema sync tries to change db as little as possible. It doesn't know you removed a column and added another one with the same name - it thinks you just want to alter it. There is an error because you're table is already populated.
