### ISSUE TITLE
[Feature] Switch to eslint

### ISSUE THREAD

**Issue by corbinu** [typeorm/typeorm#3672]
Would you be open to a PR that switches over to eslint for linting or possibly even prettier?

The typescript team is moving to eslint https://github.com/Microsoft/TypeScript/issues/29288 and https://github.com/typescript-eslint/ has made massive progress in the last few months.

I really love this project and would be happy to do some cleanup up PRs in general as I know that isn't usually primary priority but should make things much easier for newbies.

**Comment by corbinu** [comment]
Also relevant: https://medium.com/palantir/tslint-in-2019-1a144c2317a9

**Comment by pleerock** [comment]
Sounds good, just make sure to configure it the way it is right now, because we won't change formatting at this moment (maybe in the future).

**Comment by corbinu** [comment]
@pleerock For sure totally understand that should be a different PR

**Comment by imnotjames** [comment]
Conversion to use `eslint` was completed in #6452 - this can probably be closed.
