### ISSUE TITLE
Comparing entities with database table schema

### ISSUE THREAD

**Issue by nomadoda** [typeorm/typeorm#3676]
**Issue type:**

[x] question
[ ] bug report
[?] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm quite new to devops and I'm just deploying my first application thanks to TypeORM! 🎉

When I deploy my application, I rely on deployed database migrations to make the production database reflect my entities. If for some reason however, the migrations aren't sufficient, the application is likely to crash. Between deploying a new version of the application and running the database migrations, I would like to confirm there are no diffs in the production database schema and the TypeORM entity schema. Any way I could do this? Or should this be unnecessary?

**Comment by Kononnable** [comment]
To confirm your your db schema is up to date you can run something like that:
```typescript
const schemaBuilder = connection.driver.createSchemaBuilder();
const syncQueries = await schemaBuilder.log();
expect(syncQueries.downQueries).to.be.eql([]);
expect(syncQueries.upQueries).to.be.eql([]);
```
