### ISSUE TITLE
How can I make migrations run automatically

### ISSUE THREAD

**Issue by Leaking** [typeorm/typeorm#3677]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

I have read doc of migrations for several times [migrations.md](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md)

But I still have a question, it seems that I always need to run migrations manually，But I use typeorm in my desktop application based on electron, I can not run migrations manually for all users.

How can I achieve that:  migrations run automatically when I launch my application.

**Comment by rustamwin** [comment]
You can use `migrationsRun: true` option

**Comment by rustamwin** [comment]
@vlapo need add note about this option to [migrations.md](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md) ?

**Comment by vlapo** [comment]
Sure some note with link to connection options is not bad idea.

**Comment by kraiz** [comment]
Note is still not in docs. Came here from googling 'typeorm run on start'.

**Comment by plashenkov** [comment]
Yep, the note is still missing. I was searching for a method to disable auto importing of migrations.

**Comment by julianpoemp** [comment]
Note still missing

**Comment by maratsaddarov** [comment]
Node is still missing (one more time), would save tons of time if docs would be updated :(

**Comment by basit-trd** [comment]
There is another issue, may be helpful
[Programmatically Run Migrations](https://github.com/typeorm/typeorm/issues/3040)

**Comment by mlaskowski-rsk** [comment]
Docs for `migrationsRun`: https://typeorm.io/data-source-options#common-data-source-options

**Comment by hsk-kr** [comment]
> Docs for `migrationsRun`: https://typeorm.io/data-source-options#common-data-source-options

Thanks. I was looking for this command. The docs is literally hidden.
