### ISSUE TITLE
Active Record pattern findOne type error when using array spread

### ISSUE THREAD

**Issue by univerze** [typeorm/typeorm#3678]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

It would be helpful if spread operator or return array from function could be used as select parameters. We have a lot of columns in the users table but only 4 is public (the rest is set to {select: false} and it's hard to maintain hardcoded arrays everywhere we need to query users. However some calculations need non-public fields to be selected and added to the select array, please see following example.
Would be great if BaseEntity / findOneOptions supported spread or functions:

```ts
UserService.ts
...
import { User, publicUserFields } from './user.entity';
...
findOne(id: string, extraFields: string[] = []): Promise<User> {
    return User.findOne({
        select: [...publicUserFields, ...extraFields],
        where: { deletedAt: null, id },
        relations: ['role'],
    });
}
```
Currently throws the following error:
Argument of type '{ select: string[]; where: { deletedAt: null; id: string; }; relations: string[]; }' is not assignable to parameter of type 'FindConditions<User>'.
  Object literal may only specify known properties, and 'select' does not exist in type 'FindConditions<User>'.
31             select: [...publicUserFields, ...extraFields],

I have a tried a few combinations by defining id, findConditions and findOptions with no luck. As soon as I remove the spread and replace it with array of strings it works.

Thanks for the reply in advance.

**Comment by vlapo** [comment]
From `FindOneOptions` definition:
```typescript
export interface FindOneOptions<Entity = any> {

    /**
     * Specifies what columns should be retrieved.
     */
    select?: (keyof Entity)[];
    // ...
}
```
Define type of `publicUserFields` and `extraFields` as `(keyof User)[]` should works as you expected.

**Comment by Kononnable** [comment]
Closing as no response from the author.
