### ISSUE TITLE
setup coverage report via codecov/coveralls

### ISSUE THREAD

**Issue by championswimmer** [typeorm/typeorm#3679]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[x] documentation issue

Having a codecov/coveralls page to show coverage would be great so that people who want to contribute tests know which parts aren't covered and can work on those. Right now tests lack a lot and making it easier for people to know which parts can be worked on is great!

**Comment by championswimmer** [comment]
@pleerock 
CircleCI and Travis can automatically push the lcov to Codecov and Coveralls for this.

**Comment by championswimmer** [comment]
I realised codecov reports are already generated. so I sent a PR to add the badge for it https://github.com/typeorm/typeorm/pull/3680

**Comment by Kononnable** [comment]
Badge was added but coverage reports aren't generated currently - right now we're showing coverage from a year ago.

**Comment by imnotjames** [comment]
Coverage for that is up to date for master now.  🎉
