### ISSUE TITLE
Does typeorm support join with tables from diffrent databases?

### ISSUE THREAD

**Issue by miaolq** [typeorm/typeorm#368]
typeorm has supported connecting diffrent databases.

Does typeorm support join with tables from diffrent databases?
like table A from  database one, table B from database two. 
How to join A and B with typeorm.

thanks

**Comment by pleerock** [comment]
No at the moment. I recommend to do separate queries for your operation. There was a [related discussion](https://github.com/typeorm/typeorm/issues/323) earlier.

**Comment by miaolq** [comment]
get it. thanks a lot
