### ISSUE TITLE
OneToMany and ManyToOne setup fails: You need to provide explicit type

### ISSUE THREAD

**Issue by dharric** [typeorm/typeorm#3688]
This is a bug report for typeorm 0.2.13 and postgres

I have two entities and I am trying to setup a ManyToOne and OneToMany relationship between the two but it fails with error. I've also included the exact code for both entities.
Error: You need to provide explicit type for DzThread#user !
    at Object.findType (I:\Code\DzHaven\code\dzhaven-server-pg\node_modules\type-graphql\helpers\findType.js:17:15)
    at Field (I:\Code\DzHaven\code\dzhaven-server-pg\node_modules\type-graphql\decorators\Field.js:15:53)
    at DecorateProperty (I:\Code\DzHaven\code\dzhaven-server-pg\node_modules\reflect-metadata\Reflect.js:553:33)
    at Object.decorate (I:\Code\DzHaven\code\dzhaven-server-pg\node_modules\reflect-metadata\Reflect.js:123:24)
    at __decorate (I:\Code\DzHaven\code\dzhaven-server-pg\src\entity\DzThread.ts:4:92)
    at Object.<anonymous> (I:\Code\DzHaven\code\dzhaven-server-pg\src\entity\DzThread.ts:33:1)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Module.m._compile (C:\Users\dharr\AppData\Local\Temp\ts-node-dev-hook-8590636753454728.js:55:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)

`@ObjectType() // for graphql
@Entity({ name: "DzThreads" }) // for typeorm
export class DzThread extends Auditable {
  @Field(() => ID) // for graphql
  @PrimaryGeneratedColumn({ name: "Id", type: "bigint" }) // for typeorm
  id: number;

  @Field()
  @Column("int", { name: "Views", default: 0, nullable: false })
  views: number;

  @Field()
  @Column("boolean", { name: "IsDisabled", default: false, nullable: false })
  isDisabled: boolean;

  @Field()
  @ManyToOne(() => DzUser, user => user.threads)
  user: DzUser;

  @Field()
  @Column("boolean", { name: "IsAnswered", default: false, nullable: false })
  isAnswered: boolean;

  @Field()
  @Column("numeric", { name: "Bounty", default: 0.0, nullable: false })
  bounty: number;

  @Field()
  @Column("varchar", { name: "Title", length: 150, nullable: false })
  title: string;

  @Field()
  @Column("varchar", { name: "Body", length: 2000, nullable: false })
  body: string;
}

@ObjectType() // for graphql
@Entity({ name: "DzUsers" }) // for typeorm
export class DzUser extends Auditable {
  @Field(() => ID) // for graphql
  @PrimaryGeneratedColumn({ name: "Id", type: "bigint" }) // for typeorm
  id: number;

  @Field()
  @Column("varchar", {
    name: "Email",
    length: 120,
    unique: true,
    nullable: false
  })
  email: string;

  @Field()
  @Column("varchar", {
    name: "UserName",
    length: 60,
    unique: true,
    nullable: false
  })
  userName: string;

  @Field()
  @Column("varchar", {
    name: "Address",
    length: 160,
    unique: true,
    nullable: false
  })
  address: string;

  @Field()
  idUserName: string;

  @Column("varchar", { name: "Password", length: 100, nullable: false })
  @Length(6, 100)
  password: string;

  @Column("boolean", { name: "Confirmed", default: false, nullable: false })
  confirmed: boolean;

  @Column("boolean", { name: "IsDisabled", default: false, nullable: false })
  isDisabled: boolean;

  @Field()
  @OneToMany(() => DzThread, thread => thread.user)
  threads: DzThread[];
}`

**Comment by dharric** [comment]
I moved the ManyToOne down to bottom of my definition and now it works. However the name of the field in the table is userId. How can I set this name myself?

**Comment by vlapo** [comment]
Please format your comments properly. https://guides.github.com/features/mastering-markdown/

**Comment by Kononnable** [comment]
Closing as no response from the reporter.
