### ISSUE TITLE
 I am having trouble using closure-table

### ISSUE THREAD

**Issue by Teeoo** [typeorm/typeorm#3691]
**Issue type:**

- [x] bug report

**Database system/driver:**

- [x] `mysql` / `mariadb`

**TypeORM version:**

- [x] `latest`

**Steps to reproduce or a small repository showing the problem:**

```typescript
// Entity
import {Column, PrimaryGeneratedColumn,Tree,TreeChildren,TreeParent} from "typeorm";
@Tree("closure-table")
export class Category {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;
    
    @TreeParent()
    parentCategory: Category;

    @TreeChildren({ cascade: true })
    childCategories: Category[];
}

// code
public async delete(data: number): Promise<Category> {
        const result = await this.categoryRepository.findOne({ id: data });
        this.logger.warn(result);
        return await this.categoryRepository.remove(result);
}

// message
`ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`lee`.`category_closure`, CONSTRAINT `FK_4aa1348fc4b7da9bef0fae8ff48` FOREIGN KEY (`id_ancestor`) REFERENCES `category` (`id`))`
```
**Steps to reproduce or a small repository showing the problem:**

**Comment by jtushman** [comment]
Hi -- did you find the best way to do this? (or any way to do this) I am hitting this now as well.

**Comment by jtushman** [comment]
I added this to my delete logic and it seems to work.  (it also makes sense to me)

```
     // and from group
      await connection
        .createQueryBuilder()
        .delete()
        .from('group_closure')
        .where('"id_ancestor" = :id', { id })
        .execute();
```

**Comment by Teeoo** [comment]
> Hi -- did you find the best way to do this? (or any way to do this) I am hitting this now as well.


Sorry, it didn't work. I didn't see the relevant implementation in the code.

**Comment by Teeoo** [comment]
> I added this to my delete logic and it seems to work. (it also makes sense to me)
> 
> ```
>      // and from group
>       await connection
>         .createQueryBuilder()
>         .delete()
>         .from('group_closure')
>         .where('"id_ancestor" = :id', { id })
>         .execute();
> ```

Is this useful? Will delete dependencies?

**Comment by jtushman** [comment]
For you before you delete your category you need to clear out its tree, so ...


```
    public async delete(data: number): Promise<Category> {
        const categoryToDelete = await this.categoryRepository.findOne({ id: data });
        this.logger.warn(result);

       // remove dependant tree relations
       await connection
            .createQueryBuilder()
            .delete()
            .from('category_closure')                   // check your db or migrations for the actual table name
            .where('"id_ancestor" = :id', { id })
            .execute();

        return await this.categoryRepository.remove(categoryToDelete);
}
```

**Comment by Teeoo** [comment]
> For you before you delete your category you need to clear out its tree, so ...
> 
> ```
>     public async delete(data: number): Promise<Category> {
>         const categoryToDelete = await this.categoryRepository.findOne({ id: data });
>         this.logger.warn(result);
> 
>        // remove dependant tree relations
>        await connection
>             .createQueryBuilder()
>             .delete()
>             .from('category_closure')                   // check your db or migrations for the actual table name
>             .where('"id_ancestor" = :id', { id })
>             .execute();
> 
>         return await this.categoryRepository.remove(categoryToDelete);
> }
> ```


Ok, I am free to try.

**Comment by Teeoo** [comment]
> > For you before you delete your category you need to clear out its tree, so ...
> > ```
> >     public async delete(data: number): Promise<Category> {
> >         const categoryToDelete = await this.categoryRepository.findOne({ id: data });
> >         this.logger.warn(result);
> > 
> >        // remove dependant tree relations
> >        await connection
> >             .createQueryBuilder()
> >             .delete()
> >             .from('category_closure')                   // check your db or migrations for the actual table name
> >             .where('"id_ancestor" = :id', { id })
> >             .execute();
> > 
> >         return await this.categoryRepository.remove(categoryToDelete);
> > }
> > ```
> 
> Ok, I am free to try.


When I update the data, it seems to be a problem. Will you update the relationship when updating the data?

**Comment by Teeoo** [comment]
> For you before you delete your category you need to clear out its tree, so ...
> 
> ```
>     public async delete(data: number): Promise<Category> {
>         const categoryToDelete = await this.categoryRepository.findOne({ id: data });
>         this.logger.warn(result);
> 
>        // remove dependant tree relations
>        await connection
>             .createQueryBuilder()
>             .delete()
>             .from('category_closure')                   // check your db or migrations for the actual table name
>             .where('"id_ancestor" = :id', { id })
>             .execute();
> 
>         return await this.categoryRepository.remove(categoryToDelete);
> }
> ```

When I update the data, it seems to be a problem. Will you update the relationship when updating the data?

**Comment by jtushman** [comment]
see: https://github.com/typeorm/typeorm/issues/2032

**Comment by kennylbj** [comment]
For me, I have to delete both ancestor and descendant id in category_closure table in order to make thing works. Otherwise, I will get an error indicate something likes: Cannot delete or update a parent row: a foreign key constraint fails xxx.
```ts
await categoryRepository
      .createQueryBuilder()
      .delete()
      .from('category_closure')
      .where('id_ancestor = :id', { id })
      .orWhere('id_descendant = :id', { id })
      .execute();
```
