### ISSUE TITLE
Sync enums on schema sync

### ISSUE THREAD

**Issue by darko1979** [typeorm/typeorm#3694]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.13` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

For enum columns first table sync creates enum values correctly but if I change my enum class (add, remove or update values) next schema sync won't update enum values in database. I looked through typeorm code and did not find any part of code that updates enums.
I don't know if this is planned in the future but until then does anybody have a suggestion or a piece of code that I could run to update changed enums?

**Comment by jackykwandesign** [comment]
big trap here... this issue still exist in typeorm 0.3.17
