### ISSUE TITLE
Does "cli-highlight" really have to be a dependency or can it be a devDependency?

### ISSUE THREAD

**Issue by onionhammer** [typeorm/typeorm#3695]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

I am using webpack to perform treeshaking before pushing a library into a lambda; one of the largest dependencies in the output (according to the bundle analyzer) is cli-highlight. Can this be a devDependency only or is this massive package crucial to the runtime functioning of typeorm?

**Comment by zackzachariah** [comment]
Adding to the concerns, `cli-highlight` is also responsible for all of the project's "High severity" warnings when you run `yarn audit` - it would be great to not have to worry about those in a production deploy situation.

**Comment by pleerock** [comment]
yes, it have to be a regular dependency since CLI is using it. If we install it as dev-dependency then cli won't be able to use it.

Solution here is to extract cli functionality into separate typeorm-cli package, but this will not be implemented in a near future.

**Comment by thatcort** [comment]
`cli-highlight` just broke our builds due to a problem with its dependence on `highlight.js`: https://github.com/highlightjs/highlight.js/issues/1984

I'd also love to see this dependency removed/moved/reduced.

**Comment by zackzachariah** [comment]
Agree with your ideal solution @pleerock, though I wish there was an optional dependencies model we could use here in the meantime.

I'll keep following this issue for when the team gets around to splitting out the CLI code, though I'm sadly gonna be uncomfortable using `typeorm` in production code until then. I worry that the sheer number of vulnerabilities introduced via `cli-highlight`, even if they're not exposed to the open internet in production, makes it much more likely that a downstream user will miss new, important audit flags 😞

**Comment by pleerock** [comment]
but why `cli-highlight` is bringing you such issues? Maybe worth reporting this issue on their repo?

**Comment by zackzachariah** [comment]
(@pleerock - assuming your comment is in response to the user who just deleted their comment about a build break and not to me?)

**Comment by pleerock** [comment]
no, it was to you. I'm talking about this statement:

> the sheer number of vulnerabilities introduced via `cli-highlight`

**Comment by zackzachariah** [comment]
Ah ok - apologies for the misunderstanding.

I went to report an Issue with them as you suggested and found the following trail:
1. CLI-Highlight is aware of the issue and it's tracked by [felixfbecker/cli-highlight#58](felixfbecker/cli-highlight#58). It's an upstream dependency of _theirs_, `highlight.js`.
2. Highlight.js is _also_ aware of the dependency as has been aware of it for at least 2.5 years! It's tracked in their repo at [highlightjs/highlight.js#1369](highlightjs/highlight.js#1369). It's also an upstream depenency of _theirs_ called `gear`, which is a dead project no longer maintained. As of this morning, when this apparently cropped up simultaneously for everyone, they're working on a solution involving forking `gear` or moving to an entirely new build system.
3. I guess that once _that_ issue in highlight is closed, the cli team will pull it in, and then we can come back to this thread and talk about pulling it into `typeorm` and then everyone can have clean vulnerability-free code for their servers again 😄

**Comment by pleerock** [comment]
oh, okay, thanks for clarification

**Comment by pleerock** [comment]
@zackzachariah looks like highlightjs team released a new version can you check that? Maybe your issues are gone now?

**Comment by zackzachariah** [comment]
@pleerock thanks for looping back, yes indeed it looks like all the audit issues for this package are now confined to the devDependencies, so it's yet again safe to depend on 😄

While I was checking out the `npm audit` results after highlight's update, I found a really quick low-hanging-fruit cleanup opportunity, so I'll open a PR for that as well.

**Comment by zackzachariah** [comment]
So yes, to close out my reason for being in this thread: I'll try out `typeorm` in my project now that the security issues are resolved. I think that the issue @onionhammer (great username) had is still valid, though, in that having `cli-highlight` as a dependency is still going to blow up the size of webpack'd outputs for Lambda deploys (though that might be helped by the fact that the ultimate resolution to my issue was for `highlightjs` to move some of their build-system dependencies to `devDependencies`, so we won't have them anymore in `typeorm` post webpack either).

But yeah, I'll bow out of this thread now. 👋

**Comment by pleerock** [comment]
Thank you, awesome!

**Comment by dominic-simplan** [comment]
If this has any relevance, I don't see this dependency in my typeorm browser environment (Apache Cordova):
```
new webpack.NormalModuleReplacementPlugin(/typeorm$/, function (result) {
    result.request = result.request.replace(/typeorm/, "typeorm/browser");
}),
```

I see it only in the non-browser environment (Electron).

**Comment by Ciantic** [comment]
This is problem for me, the `cli-highlight` package breaks the electron build somehow.

**Comment by Ciantic** [comment]
Okay, I now have a proposal for first steps:

Refactor these two functions: [`highlightSql()` and `highlightJson()`](https://github.com/typeorm/typeorm/blob/master/src/platform/PlatformTools.ts#L194-L214) outside the PlatformTools. Because cli parts of the application depends on these two functions, whereas rest of the codebase depends on PlatformTools in general. It's therefore easier to break these two functions outside the PlatformTools.

Is it agreed in general by maintainers that creation of `typeorm-cli` should be done? If someone gives this a try, it won't be wasted.

**Comment by imnotjames** [comment]
It's definitely going to be important that we create a separate `cli` package, but at this time we can't make `cli-highlight` a dev dependency or optional dependency.  It'd break a number of existing use cases.
