### ISSUE TITLE
Connection pooling in express app

### ISSUE THREAD

**Issue by paistipoikka** [typeorm/typeorm#37]
Hi, 

Using TypeOrm what is the best way to create a pool of connections using express?

Will this code in my server.ts be sufficient?

```
db = createConnection();
app.locals.db = db; 
```
Then just call app.local.db in my application whenever I need a database connection. Is this likely to cause a problem with the library?

Are there any examples of how this is done?

Cheers

JT

**Comment by pleerock** [comment]
connection pooling is enabled by default, and most probably you should not worry about it. 

```typescript
db = createConnection();
app.locals.db = db; 
```

createConnection returns a promise with a connection inside, this means you code should look like this:

`createConnection().then(connection => app.locals.connection = connection);`

Do you have a plans to use a service container in your app? If yes then with typedi you can inject your connection anywhere you need.

**Comment by pleerock** [comment]
you can also use a ConnectionManager to get connection from anywhere from your app:

```typescript
import {getConnectionManager} from "typeorm";
const connectionManager = getConnectionManager();
const defaultConnection = getConnectionManager().get();
const secondaryConnection = getConnectionManager().get("secondary-connection");
```

**Comment by paistipoikka** [comment]
Yes, I've just wired up a DI container (inversify) and it seems to be working nicely. I've created a DBConnection class which will contain the connection in the instance state.

**Comment by pleerock** [comment]
`I've created a DBConnection`

You really should not. You already have your connections in a single place, and you access it anytime using `getConnectionManager().get()`

**Comment by pleerock** [comment]
You also should give a try to [typedi](https://github.com/pleerock/typedi), there also[ nice typedi extensions for typeorm](https://github.com/typeorm/typeorm-typedi-extensions)

**Comment by paistipoikka** [comment]
> try to typedi, there also nice typedi extensions for typeorm

Looks good. Cheers!

**Comment by Shepless** [comment]
@paistipoikka I'm trying to get typeorm to work with Inversify, would it be possible for you to share your implementation please? It's been a long time since I've worked with IoC so I'm probably going about it completely the wrong way. It would be a great learning experience for me to see how other people are approaching this.

**Comment by paistipoikka** [comment]
@Shepless I didn't end up using Inversify in the end. Sorry. 

What about typedi?

**Comment by Shepless** [comment]
@paistipoikka Thanks for getting back. Is typedi as flexible as Inversify? Although inversify has a steep learning curve and is possibly "over-engineered" it does seem to have more features?

**Comment by paistipoikka** [comment]
@Shepless I think the author of the software is the one to ask about these questions.

**Comment by Shepless** [comment]
@pleerock sorry to be a pain but am I missing something here: RE: multiple instances/factories?

**Comment by Shepless** [comment]
@pleerock sorry to be a pain but am I missing something here: RE: multiple instances/factories?

**Comment by pleerock** [comment]
there is no support of factories the way you described in typedi. If you need it create an issue here and lets discuss implementation and behaviour details there
