### ISSUE TITLE
MySQL Spatial Type Support : GeomFromText function is not supported

### ISSUE THREAD

**Issue by thatisuday** [typeorm/typeorm#3702]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
As per the documentation, I have the following column in my table

```
@Column("geometry", {
        spatialFeatureType: "Point",
        srid: 4326
})
position: string;
```

It successfully creates the column of type "geometry" in MySQL Table but when you are inserting some data like

```
const location = new Location();
location.name = 'my-location';
location.tags = [ 'tag-1', 'tag-2' ];
location.position = 'POINT(1 1)';

const _location = await connection.manager.save( location );
```

It gives the following error

```
(node:40807) UnhandledPromiseRejectionWarning: QueryFailedError: ER_SP_DOES_NOT_EXIST: FUNCTION mydb.GeomFromText does not exist
```

This is because MySQL 8.0 and higher doesn't recognize `GeomFromText` function (deprecated), it supports these spatial functions with `ST_` prefix like `ST_GeomFromText`. Please read my article on Medium on the spatial data type in MySQL (https://itnext.io/playing-with-geometry-spatial-data-type-in-mysql-645b83880331).

> After fixing this issue my modifying typeorm code, I also found that SRID specification while mentioning column type is not working. typeorm is inserting data with SRID 0 (default MySQL).

Is there anything I am doing wrong or **typeorm** doesn't support spatial data types in MySQL.
 

**Proposed solution**
- Add new connection option `legacySpatialSupport` which defaults to `true`. If `false`, newer spatial functions will be used like `ST_GeomFromText` and `ST_AsText` etc.
- Like PostgreSQL, make use of `srid` while creating spatial column in simple format `@Column( { type: 'point', srid: 4326 } ) position: string;`

**Comment by murbanowicz** [comment]
Any update on this?

**Comment by hawkeng** [comment]
There is a workaround that I use by using QueryBuilder
```
connection.createQueryBuilder()
  .insert()
  .into(MyModel)
  .values({
    location: () => `ST_GeomFromText('POINT(${lat} ${long})', 4326)`
  })
  .execute()
```

**Comment by sunjoong85** [comment]
Same as me. I have ST_AsText problem. Hope to be fixed soon.

**Comment by francistm** [comment]
Assuming you're using MySQL version higher than 5.7 (like 8.0 currently).
Don't know why mysql rename those functions like `AsText`, `GeomFromText` to a `ST_` prefix.

So you can create them as an alias in mysql.

``` sql
CREATE FUNCTION `GeomFromText`(string VARCHAR(255)) RETURNS geometry
DETERMINISTIC
BEGIN
RETURN ST_GeometryFromText(string);
END
```

**Comment by ahmed-com** [comment]
I'm having that same issue _**exactly**_ , could someone please elaborate on how to fix it ?

**Comment by alloystory** [comment]
for anyone who faces this issue, just set `legacySpatialSupport: false` in your `ormconfig` file

**Comment by malcam** [comment]
> for anyone who faces this issue, just set `legacySpatialSupport: false` in your `ormconfig` file

it works for me, thanks

**Comment by minho-lee0716** [comment]
> for anyone who faces this issue, just set `legacySpatialSupport: false` in your `ormconfig` file

Thx :) 👍

**Comment by aahj** [comment]
> for anyone who faces this issue, just set `legacySpatialSupport: false` in your `ormconfig` file

thanks
