### ISSUE TITLE
Provide a way to work without Primary Column, or add support for composite column index. (MissingPrimaryColumnError)

### ISSUE THREAD

**Issue by nbaua** [typeorm/typeorm#3704]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
(This is slightly different than issue no #2629)

There should be support for the non-primary columns added for querying the database.
For example: One of my database table does not want to enforce any primary key (**as we are using the composite key using 3 column values, forming uniqueness**). When working with this table I get following exception.

> MissingPrimaryColumnError: Entity "BaseDetailMaster" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.

Please suggest an immediate workaround if possible..

**Comment by nbaua** [comment]
OK,
I can create multiple @PrimaryColumn() and that worked like a composite key. Please have this documented somewhere. Thanks, closing this issue.

**Comment by saostad** [comment]
but this is not working for this code: 
```
import { Column, Entity, Index } from "typeorm";

@Index("biARBL", ["co", "mth", "batchId", "batchSeq", "arLine"], {
  unique: true,
})
@Index(
  "biARBLApplied",
  ["co", "applyMth", "applyTrans", "applyLine", "mth", "batchId", "batchSeq"],
  {},
)
@Entity("bARBL", { schema: "dbo" })
export class BArbl {
  @Column("tinyint", { name: "Co" })
  co: number;

  @Column("smalldatetime", { name: "Mth" })
  mth: Date;

  @Column("int", { name: "BatchId" })
  batchId: number;

  @Column("int", { name: "BatchSeq" })
  batchSeq: number;

  @Column("smallint", { name: "ARLine", nullable: true })
  arLine: number | null;

  @Column("char", { name: "TransType", length: 1 })
  transType: string;
}
```

I can't add @PimaryColumn on all fields of my index because one of them `arLine` is nullable.
