### ISSUE TITLE
no such file or directory highlight.js/tools/build.js when installing typeorm

### ISSUE THREAD

**Issue by yogevlahyani** [typeorm/typeorm#3705]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I tried to install typeorm in a clean new directory (no other dependencies except typeorm) and I got this error:
`ENOENT: no such file or directory, chmod '/Users/user/dev/nestjs-custom-base-entity/node_modules/highlight.js/tools/build.js'`

Also happens when I tried to install typeorm globally with sudo. tried to clean npm cache couple of time.

**Comment by yogevlahyani** [comment]
Works for me when I run `npm i typeorm --no-bin-links`

**Comment by Vinlow** [comment]
Got the same issue. Thanks for the quickfix @yogevlahyani

**Comment by NachtmahrEDM** [comment]
Got the same problem, @yogevlahyani workaround helped.

**Comment by hk-Edifixio** [comment]
How would this workaround work on a deployment server's npm install?

**Comment by BelgianCrowbar** [comment]
Looks like this is a bug from highlight.js latest version 
https://github.com/highlightjs/highlight.js/issues/1984

**Comment by abingoal** [comment]
> Looks like this is a bug from highlight.js latest version
> [highlightjs/highlight.js#1984](https://github.com/highlightjs/highlight.js/issues/1984)

My solution: `npm i highlight.js@9.14.2 -D`.
They have solved this problem,waiting for the new version.

**Comment by WiRight** [comment]
Try use `yarn`
It's solved for me

**Comment by LucasBrd** [comment]
Seems that typeorm depends on cli-highlight which itself depends on highlight.js 9.6.0

> "dependencies": {
>     "chalk": "^2.3.0",
>     "highlight.js": "^9.6.0",
>     "mz": "^2.4.0",
>     "parse5": "^4.0.0",
>     "yargs": "^11.0.0"
>   },

**Comment by Stradivario** [comment]
I am really not sure why we need `cli-highlight` installed as a dependency what they are using ? i will investigate if not i think it should be removed as soon as possible since it breaks many builds....

**Comment by Stradivario** [comment]
Oh my freaking god!!

https://github.com/typeorm/typeorm/blob/master/src/commands/SchemaLogCommand.ts#L60
https://github.com/typeorm/typeorm/blob/master/src/platform/PlatformTools.ts#L3
https://github.com/typeorm/typeorm/blob/master/src/commands/SchemaLogCommand.ts#L4

It is insane for highlighting and console log typeorm is broken :D 
It is strange also that CLI is not separated from the main build ;)

**Comment by Stradivario** [comment]
I have a production release and i am stucked any help will be appreciated..


Type orm Dependency graph

typeorm > cli-highligh > higlight.js

so we need to fix cli-higlight to have strict package of highlight.js and then we need to install it on typeorm.For fuck sake please LOCK your dependencies! everytime so things like this wont happen ! :)

**Comment by Stradivario** [comment]
I have manage to succeed with this for now

Let me explain how i did it.

Go to package-lock.json

find this block:

```
    "cli-highlight": {
      "version": "1.2.3",
      "resolved": "https://registry.npmjs.org/cli-highlight/-/cli-highlight-1.2.3.tgz",
      "integrity": "sha512-cmc4Y2kJuEpT2KZd9pgWWskpDMMfJu2roIcY1Ya/aIItufF5FKsV/NtA6vvdhSUllR8KJfvQDNmIcskU+MKLDg==",
      "requires": {
        "chalk": "^2.3.0",
        "highlight.js": "^9.6.0",
        "mz": "^2.4.0",
        "parse5": "^3.0.3",
        "yargs": "^10.0.3"
      },
```

Replace ` "highlight.js": "^9.6.0"` with `"highlight.js": "9.6.0"`

When you install your packages try with `npm ci` instead of `npm i` that way npm will install dependencies from package-lock and VOALA you can now proceed with your build.

This is really ugly fix but it saves the day.Waiting for fix! Regards!

**Comment by NaturesProphet** [comment]
any progress? please, its ruining my work!

**Comment by pleerock** [comment]
Can you please use provided solution for now?

`npm i highlight.js@9.14.2 -D`

We just need to wait when highlight.js fix their issue, its a critical issue, I'm sure they will fix it very soon.

**Comment by Kononnable** [comment]
Looks like issue was resolved some time ago.
