### ISSUE TITLE
getMany doesn't work

### ISSUE THREAD

**Issue by lmjavascriptprogrammer** [typeorm/typeorm#3707]
**Issue type:**

[х ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[х ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[х ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi. The method getMany() does not behave as I expect.
I have:

```js
this.connection.getRepository(ContactsEntity)
.createQueryBuilder('contact')
   .select('contact.email')
   .leftJoin(qb => {
        return qb
        .select(`poco."contactsEntityId"`, `ceid`)
        .addSelect(`max(poco."pollEntityId")`, `pemax`)
        .from(`poll_entity_contacts_contacts_entity`, `poco`)
        .groupBy(`poco."contactsEntityId"`)
    }, 'stable', `contact.id = stable.ceid`)
    .leftJoinAndSelect(PollEntity, 'poll', 'poll.id = stable.pemax')
    .getMany()
```
I get like this:

```json
"email": "emailaddress",
```

But I am counting on like this:

```json
"email": "emailaddress",
"poll": {
   "id": 1
}
```

If I use getRawMany method, I have like this:

```sql
"email": "emailaddress",
"poll_id": 1
...
```

Why do I have problems with this?

The SQL Query:

```
select * from contacts_entity contact left join (select poco."contactsEntityId" as ceid, max(poco."pollEntityId") as pemax from poll_entity_contacts_contacts_entity poco group by poco."contactsEntityId") stable on contact.id = stable.ceid left join poll_entity poll on poll.id = stable.pemax;
```

**Comment by vlapo** [comment]
Did you try `leftJoinAndMapOne` https://typeorm.io/#/select-query-builder/joining-and-mapping-functionality

**Comment by lmjavascriptprogrammer** [comment]
> Вы пробовали `leftJoinAndMapOne` https://typeorm.io/#/select-query-builder/joining-and-mapping-functionality

Oh, yea, it's working. Thank's for you help!
But this method inappropriate for custom selection. Or not?..

**Comment by lmjavascriptprogrammer** [comment]
Using my approach, I could make a sample. But it can't be like that.
