### ISSUE TITLE
Migration cli unexpected token import

### ISSUE THREAD

**Issue by adithep** [typeorm/typeorm#371]
I wrote everything in typescript.
The application and everything work fine, but as soon as I call 

`typeorm migrations:run`

I get this error

src/entity/User.ts:1
(function (exports, require, module, __filename, __dirname) { import {Entity, Column, PrimaryGeneratedColumn} from "typeorm";
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.PlatformTools.load (/usr/local/lib/node_modules/typeorm/platform/PlatformTools.js:26:20)
    at /usr/local/lib/node_modules/typeorm/util/DirectoryExportedClassesLoader.js:29:69
(node:38469) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): SyntaxError: Unexpected token import
(node:38469) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Not sure if it matters but this is my tsconfig.json:

{
  "compilerOptions": {
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "isolatedModules": false,
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "dist",
    "sourceMap": true,
    "sourceRoot": "src",
    "noEmitHelpers": false,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": ["es6", "dom"]
  },
  "exclude": [
    "node_modules"
  ]
}

What ever I change in tsconfig.json seems to not effect the error at all.

**Comment by pleerock** [comment]
you node environment tries to load `src/entity/User.ts`, but it should load `.js`. So you either need to run app with ts-node, or set proper configuration for JS FILES in your ormconfig cli section, e.g. `dist/migrations/.*js`

**Comment by pleerock** [comment]
did you resolve your issue?

**Comment by adithep** [comment]
Yes. Thankyou.

On Sat, Apr 1, 2017 at 6:08 PM, Umed Khudoiberdiev <notifications@github.com

**Comment by SaeedSyedAli96** [comment]
@adithep how did you resolve the issue?

**Comment by stormpat** [comment]
Anyone wondering about this, you must run your .ts files thru ts-node first.

Simply:
```
>> ./node_modules/.bin/ts-node ./node_modules/.bin/typeorm <command>
```

**Comment by davidmpaz** [comment]
Hi @stormpat,

thanks for the hint. Still is not working for me.

```
./node_modules/.bin/ts-node ./node_modules/.bin/typeorm schema:log
```

gives me still:
```
import { Column, Entity, ManyToOne } from 'typeorm';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Module.m._compile (/srv/http/is7/mobile-sdk/src/modules/products/node_modules/ts-node/src/index.ts:422:23)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/srv/http/is7/mobile-sdk/src/modules/products/node_modules/ts-node/src/index.ts:425:12)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
```

Any idea ?

**Comment by pleerock** [comment]
@davidmpaz try to setup your tsconfig properly - try to set target to es5

**Comment by davidmpaz** [comment]
Hi @pleerock ,

thanks for answering. These are my current config files

tsconfig.json:
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "noStrictGenericChecks": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

ormconfig.json
```json
{
    "type": "sqlite",
    "database": "./products.db",
    "synchronize": true,
    "logging": false,
    "entities": [
        "src/models/**/*.ts"
    ],
    "migrations": [
        "src/migration/**/*.ts"
    ],
    "subscribers": [
        "src/subscriber/**/*.ts"
    ],
    "cli": {
        "entitiesDir": "src/models",
        "migrationsDir": "src/migration",
        "subscribersDir": "src/subscriber"
    }
}
```
package.json deps:
```json
"dependencies": {
        "@angular/common": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "ionic-angular": "^3.6.0",
        "typeorm": "0.1.11",
        "reflect-metadata": "^0.1.10",
        "ngx-order-pipe": "^1.1.0",
        "sqlite3": "3.1.13",
        "rxjs": "5.4.0"
    },
    "devDependencies": {
        "tslint": "^5.8.0",
        "tslint-eslint-rules": "^4.1.1",
        "ts-node": "4.1.0",
        "typescript": "^2.6.1"
    }
```

I would like to see what get generated with my current entity models definitions, was trying to do 'insitu'. I guess I will try to generate a project from scratch and copy paste entities.

But would be nice if I can get it up running in my existent project.

thanks in advance for your time,
David

**Comment by davidmpaz** [comment]
It seems my problem is known [here](https://github.com/TypeStrong/ts-node/issues/313#issuecomment-296399197), related to my settings: `"module": "es2015"`

Sorry to introduce this noise.

Thanks!!

**Comment by 91debug** [comment]
@davidmpaz  how did you resolve the issue?

These are my current config files
tsconfig.json:
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "rootDir": "./",
    "outDir": "./tsc",
    "noImplicitAny": false,
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "declaration": false,
    "listFiles": false,
    "lib": [
      "es6",
      "dom",
      "es2015.promise",
      "esnext.asynciterable"
    ],
    "noUnusedLocals": true,
  },
  "exclude": [
    ".vscode",
    ".serverless",
    ".git",
    "node_modules"
  ],
  "compileOnSave": true,
  "buildOnSave": false
}

**Comment by davidmpaz** [comment]
@91debug currently I haven't.

**Comment by 91debug** [comment]
@davidmpaz i resolved! thank you

**Comment by davidmpaz** [comment]
@91debug, could you share ? :)

**Comment by 91debug** [comment]
@davidmpaz 

I used this command
./node_modules/.bin/ts-node ./node_modules/.bin/typeorm schema:sync

**Comment by tonyxiao** [comment]
it's surprising that typeorm cli doesn't work with typescript by default without asking user to explicitly pass through ts-node. Is that something which could be built in given how typeorm itself is written in typescript?

**Comment by SaeedSyedAli96** [comment]
I found a way to make migratons working with my ionic 3 application.
in **ormconfig.json**:
```
{
    "cli": {
        "migrationsDir": "src/migrations/"
    }
}
```

and the **connection**: 
```
 await createConnection({
            type: 'cordova',
            database: 'test',
            location: 'default',
            logging: ['error', 'query', 'schema'],
            synchronize: false,
            entities: [
                //entities
            ],
            migrations:[
                //migrations generated by typeorm cli
            ],
            migrationsRun: true
        }).catch(err => console.log("error: ", err));
```

**Comment by tonyxiao** [comment]
@SaeedSyedAli96 how does it work?

**Comment by SaeedSyedAli96** [comment]
@tonyxiao I just used migration cli to generate migrations as it needs timestamp. Else Entitites and and other stuff I did manually. I was having issues in running migration from cli but then I got to know that there is an option of migrationsRun as well.

**Comment by mindonline** [comment]
Also, in Win 10 works:
`ts-node node_modules\typeorm\cli.js`

**Comment by worudso** [comment]
`ts-node ./node_modules/.bin/typeorm <command>`
It doesn't work with windows. `./node_modules/.bin/typeorm` in windows is not a shebang-starting js file.Instead, it's a bash script not like in linux.

**Comment by eightHundreds** [comment]
for es project
```
.\node_modules\.bin\babel-node .\node_modules\typeorm\cli.js schema:sync
```

**Comment by bennyn** [comment]
I had a similar issue when running my JavaScript application code (which has been transpiled from TypeScript):

> (function (exports, require, module, __filename, __dirname) { import {Column, Entity, PrimaryGeneratedColumn} from "typeorm";
>
> SyntaxError: Unexpected token {

I solved it by pointing the `entities` in my `ormconfig.js` to my compiled JavaScript code. Before that (when I had the error) they have been linked to my TypeScript source code.

This configuration now works for me:

**ormconfig.js**

```js
const ConnectionOptions = {
  cli: {
    entitiesDir: 'src/main/entity',
    migrationsDir: 'src/migration',
    subscribersDir: 'src/subscriber',
  },
  database: 'database/development.db3',
  entities: ['dist/entity/*.js'],
  logging: false,
  migrations: ['src/migration/**/*.ts'],
  subscribers: ['src/subscriber/**/*.ts'],
  synchronize: true,
  type: 'sqlite',
};

if (process.env.NODE_ENV === 'production') {
  ConnectionOptions.database = 'database/production.db3';
}

if (process.env.NODE_ENV === 'test') {
  ConnectionOptions.database = 'database/test.db3';
}

module.exports = ConnectionOptions;
```

**Comment by AhmadDeel** [comment]
after long I installed ts-node typescript typeorm globally and use
`ts-node ./node_modules/typeorm/cli.js  migration:generate -n new1`
command things start to work.
then added these
```js
> {
>   /* ... */
"scripts": {
>     /* ... */
>     
      "typeorm-migration-generate": "ts-node ./node_modules/typeorm/cli.js migration:generate -n MigrationName",
      "typeorm-migration-run": "ts-node ./node_modules/typeorm/cli.js migration:run",
      "typeorm-migration-revert": "ts-node ./node_modules/typeorm/cli.js migration:revert"
>   }
> }
> ```

**Comment by 2234839** [comment]
"entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],

我遇到了同样 的 问题在将 ormconfig.json中的 ts 改为 js之后解决了问题

**Comment by vngrv** [comment]
> It seems my problem is known [here](https://github.com/TypeStrong/ts-node/issues/313#issuecomment-296399197), related to my settings: `"module": "es2015"`
> 
> Sorry to introduce this noise.
> 
> Thanks!!

this changes kill my build.

**Comment by rpmonteiro** [comment]
Using ENV variables, the fix for me was
```
TYPEORM_ENTITIES=dist/**/*.entity.js
TYPEORM_MIGRATIONS=dist/migration/*.js
TYPEORM_MIGRATIONS_DIR=dist/migration
```

Hope this helps someone

**Comment by willianfalbo** [comment]
If you are using `ormconfig.json` file, it should look like:

```
{
    "type": "postgres",
    "host": "localhost",
    "port": 5432,
    "username": "root",
    "password": "password",
    "database": "persona_db",
    "entities": [
        "dist/**/*.entity{.ts,.js}"
    ],
    "synchronize": false,
    "migrations": [
        "dist/migrations/**/*{.ts,.js}"
    ],
    "cli": {
        "migrationsDir": "migrations"
    }
}
```
**NOTE: Please refer to the "dist" folder and not the root folder...**

**Comment by zeroliu** [comment]
@willianfalbo I ran into a similar issue with deploying the compiled js code to server. I was very confused how any ts file was referenced to the compiled code. Didn't even think about checking ormconfig.json...Thanks so much!!!

**Comment by gitDylanHub** [comment]
> Hi @stormpat,
> 
> thanks for the hint. Still is not working for me.
> 
> ```
> ./node_modules/.bin/ts-node ./node_modules/.bin/typeorm schema:log
> ```
> 
> gives me still:
> 
> ```
> import { Column, Entity, ManyToOne } from 'typeorm';
> ^^^^^^
> 
> SyntaxError: Unexpected token import
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:607:28)
>     at Module.m._compile (/srv/http/is7/mobile-sdk/src/modules/products/node_modules/ts-node/src/index.ts:422:23)
>     at Module._extensions..js (module.js:654:10)
>     at Object.require.extensions.(anonymous function) [as .ts] (/srv/http/is7/mobile-sdk/src/modules/products/node_modules/ts-node/src/index.ts:425:12)
>     at Module.load (module.js:556:32)
>     at tryModuleLoad (module.js:499:12)
>     at Function.Module._load (module.js:491:3)
>     at Module.require (module.js:587:17)
> ```
> 
> Any idea ?
Another workaround for executing the TypeORM from a NPM Scritp.
"typeorm": "node --require ts-node/register ./node_modules/typeorm/cli.js",
"migration:generate": "npm run typeorm migration:generate -- -n",
