### ISSUE TITLE
npm: deprecated minimatch installing typeorm

### ISSUE THREAD

**Issue by patrick904** [typeorm/typeorm#3710]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Installing typeorm to a new, clean project with npm i typeorm or typeorm@latest:
```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
´´´
Last week icould install typeorm without any errors.

**Comment by lixaotec** [comment]
Had the same issue, try using yarn 

Don´t know if is correct but seems to be highlight.js last publish gone with bug. 

You may check they are woking on.

**Comment by patrick904** [comment]
Hi, thank you - i seems to be highlight.js - but they muted the issue a few hours ago. Hopefully there will be a fix soon - fixbuild is not avaiable any more ...

**Comment by patrick904** [comment]
I found a solution: 
`npm i highlight.js@9.12.0`
installs successfully. After that i was able to run`npm i typeorm --save `without any errors.
