### ISSUE TITLE
Foreign key display

### ISSUE THREAD

**Issue by lixaotec** [typeorm/typeorm#3713]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Dear folks,

I was wondering if is it possible to config/tell typeorm to show foreign key along with their properties in Entity.

Just don´t know if is it possible neigther if its a good practice, however I have a timeseries Entity (table) that receives keys from other tables, and when I try fo .find() them, relation fields doesn´t come if I don´t relate them in .find({relations:... instructions.

The time series with joins reduces response time, and I dont need them.

I know it can be accomplished with a custom query, however is there any config that enables those kind of field to be exposed?

Thank you in advance

**Comment by feather-jmalone** [comment]
Assuming the ID property exists in your entity class already, you simply need to specify that it's a database column. For example, consider a `ProductOption` class, which has a parent `Product` relation.

```
  // Product ID
  @Column()
  productId: number;


  // Product
  @ManyToOne(type => Product, product => product.options)
  product: Product;
```

I won't weigh in on the 'best practice' part of your question, but for whatever its worth, I personally access ID columns from time to time using that approach, and it doesn't cause any problems.

One caveat, however: use it for 'read only' purposes... you should still set a foreign relation using the entity property, not the ID property (in fact, you might wanna define the ID column as `readonly: true`).

**Comment by lixaotec** [comment]
Thank you @feather-jmalone , that helped a lot.

**Comment by neekey** [comment]
Thanks @feather-jmalone , this post helped me understand better about the relationship between entity definition and the usage of the entity. 

using the "foreign key" makes more sense in my case:

I have a "case" table and each case has a doctor and a patient. so when creating a new case, it is easier to just:

```
async function createCase({ patientId, doctorId }) {
    const newCase = new Case();
    newCase.patientId = patientId;
    newCase.doctorId = doctorId;
    await newCase.save();
    return newCase;
}
```

otherwise, the I need to make extra queries to get the patient and doctor object first:

```
async function createCase({ patientId, doctorId }) {
    const newCase = new Case();
    newCase.patient = await User.findOne(patientId);
    newCase.doctor = await User.findOne(doctorId);
    await newCase.save();
    return newCase;
}
```
