### ISSUE TITLE
queryBuilder: missing results when using leftJoinAndMapOne

### ISSUE THREAD

**Issue by cvh23** [typeorm/typeorm#3715]
**Issue type:**

[ ] question
[] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.9`

**Steps to reproduce or a small repository showing the problem:**

```ts
 const qb = this.communicationListMemberRepository
      .createQueryBuilder('communicationListMember')
      .innerJoin('communicationListMember.communicationList', 'communicationList')
      .leftJoinAndMapOne('communicationListMember.searchContact', qb2 => {
        return this.buildSearchQuery(qb2, this.queryParams);
      }, 'searchContact', '"searchContact".id = communicationListMember.contact.id');
```
This is a mailing list subscriber table (communication list subscriber table) which join mailing list (communication list) table and then there should be a left join, from a dynamically generated query on contact data. The SQL generated by TypeORM is okay (I've tested it in postgres console), but the result of the left join sub query *searchContact* is not provided in the result object. Do you have any hints? Or more complex examples than in the docs?

**Comment by Kononnable** [comment]
Can you post a reproduction repo? There is too little information to tell what's wrong.

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by Seemspyo** [comment]
@Kononnable This need to be re-open.

In my case, when using query builder inside `leftJoinAndMapOne`, mapping is not work as expected.

```txt
User
id   |  username

Comment
id   |   authorId
```

```js
const query =
getRepository(Comment)
.createQueryBuilder('comment')
.leftJoinAndMapOne('comment.author', subQuery => {
    return subQuery.from(User, 'user');
}, 'user', 'user.id = comment.authorId');

console.log(await query.getRawMany()) //[ { comment_id: "..", comment_authorId: "..", id: "..", username: ".." } ]
console.log(await query.getMany()) // [ { id: "..", authorId: ".." } ]
```

As you can see, the query working fine(In SQL service level). It fetching joined data as it should. But mapping doesn't.

I even tried rename all the property like `user.id = user_id`, think this might related with typeorm's hacky naming, but none of them worked. And this is same for `leftJoinAndSelect`.

You might think there is better solution for this example, BUT this is just an example. I won't use sub query if case is that simple.
