### ISSUE TITLE
Migration of table with FK of type "uuid" emits field of type "character varying"

### ISSUE THREAD

**Issue by JimBeem** [typeorm/typeorm#3718]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.14` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Given the following two models:

**issueDemo.ts**:
```
import { Column, Entity, JoinColumn, ManyToOne, PrimaryColumn } from 'typeorm';
import { DemoOrg } from './demoOrg';

@Entity()
export class Demo {
  @PrimaryColumn()
  pid!: string;

  @ManyToOne(() => DemoOrg)
  @JoinColumn({ name: 'id', referencedColumnName: 'id' })
  organization?: DemoOrg;

  @Column({ type: 'uuid' })
  id!: string;

  @Column({ type: 'uuid' })
  properUuid!: string;
}
```

**demoOrg.ts**:
```
import { Column, Entity, Generated, PrimaryColumn } from 'typeorm';

@Entity()
export class DemoOrg {

  @PrimaryColumn({ unique: true })
  identifier!: string;

  @Column({ unique: true })
  @Generated('uuid')
  id?: string;
}
```

When I run `ts-node ./node_modules/typeorm/cli.js migration:generate -n "Demo"`, the following migration script is generated:
```
import { MigrationInterface, QueryRunner } from 'typeorm';

export class Demo1551212833052 implements MigrationInterface {

  async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query('CREATE TABLE "demo_org" ("identifier" character varying NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "UQ_102239d15446e5646a35a1ecf31" UNIQUE ("id"), CONSTRAINT "PK_9054507b781106593133a7d80d5" PRIMARY KEY ("identifier"))');
    await queryRunner.query('CREATE TABLE "demo" ("pid" character varying NOT NULL, "id" character varying NOT NULL, "properUuid" uuid NOT NULL, CONSTRAINT "PK_6e80a681ae117c5221a25f54f90" PRIMARY KEY ("pid"))');
    await queryRunner.query('ALTER TABLE "demo" ADD CONSTRAINT "FK_9d8d89f7764de19ec5a40a5f056" FOREIGN KEY ("id") REFERENCES "demo_org"("id") ON DELETE NO ACTION ON UPDATE NO ACTION');
  }

  async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query('ALTER TABLE "demo" DROP CONSTRAINT "FK_9d8d89f7764de19ec5a40a5f056"');
    await queryRunner.query('DROP TABLE "demo"');
    await queryRunner.query('DROP TABLE "demo_org"');
  }
}
```

The problem here, is that I expect (and require) that the `id` on table `demo` to be:
`"id" uuid NOT NULL,`
but it instead gets generated as:
`"id" character varying NOT NULL`

If I change the database, model, and migration script to specify type `uuid`, then the _next_ migration that I generate will undo my manual changes and re-create the foreign key as `character varying NOT NULL`.

Am I doing something wrong? Any help / guidance would be appreciated.

**Comment by vlapo** [comment]
Please try change `Demo.organziation` relation definition to:
```typescript
@ManyToOne(() => DemoOrg, demoOrg => demoOrg.identifier)
organization?: DemoOrg;
```

**Comment by vlapo** [comment]
EDIT: Problem is that your `DemoOrg.id` is type `string` (so it is normalized into `character varying`) and your `Demo.id` is type `uuid` and it will cause error `Key columns "id" and "id" are of incompatible types: character varying and uuid.`. Change `DemoOrg.id` to:
```typescript
@Column({ type: 'uuid', unique: true })
@Generated('uuid')
id?: string;
```

**Comment by vlapo** [comment]
Previous comment edited sry :)

**Comment by JimBeem** [comment]
That fixed it for me, thanks for the quick response!

**Comment by vlapo** [comment]
You are welcome.

**Comment by ullalaaron** [comment]
> EDIT: Problem is that your `DemoOrg.id` is type `string` (so it is normalized into `character varying`) and your `Demo.id` is type `uuid` and it will cause error `Key columns "id" and "id" are of incompatible types: character varying and uuid.`. Change `DemoOrg.id` to:
> 
> ```ts
> @Column({ type: 'uuid', unique: true })
> @Generated('uuid')
> id?: string;
> ```

this solved it for me aswell
