### ISSUE TITLE
Where condition on relations/join in find

### ISSUE THREAD

**Issue by abhyuditjain** [typeorm/typeorm#3724]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This is the gist: https://gist.github.com/abhyuditjain/006075be771d5265614e0189045b542d

I want to fetch data based on certain conditions on the relations. I can't seem to figure out how.

**Comment by Kononnable** [comment]
@abhyuditjain 	
Did you resolve your issue?
If not please provide some more info about what you want to achieve and what exactly is missing at the moment.

**Comment by ryuuji3** [comment]
I think this is related to you using Moment. Try converting the Moment object to a Date object. 

If you still want to keep on using Moments, please be aware of this: https://github.com/typeorm/typeorm/issues/2390

**Comment by Kononnable** [comment]
Closing as no response from the author.
