### ISSUE TITLE
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'test'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by KAROTT7** [typeorm/typeorm#3726]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>
My computer is Mac, npm is lastest, node is v10.0.0
I am new to learn typeorm, so I follow quick start
after i run 
```typeorm init --name MyProject --database mysql
cd MyProject
npm install
npm start```
It's not working
show error ```Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'test'@'localhost' (using password: YES)```

plz tell me why
Do I need to download mysql in www.mysql.com?

**Comment by KAROTT7** [comment]
I am new to learn typeorm
I follow quick start to run this command
```
typeorm init --name demo --database mysql
cd demo
npm i
npm start
```
but it doesn't works
plz tell me

**Comment by rustamwin** [comment]
you should configure your connection options in `ormconfig.json`

**Comment by puttputt** [comment]
👍 to @rustamwin 's answer. 

The error is showing because typeorm can't connect to your database.
It appears your database is running because you have received an authentication error. So check these things:
- Ensure your configuration has the right user/pass configuration for localhost.
- Ensure user 'test' has the permission to access the localhost database.

**Comment by KAROTT7** [comment]
Thank @rustamwin and @puttputt  very much
I am noob, now I need to learn mysql server

**Comment by rustamwin** [comment]
Accordingly this issue can be closed @vlapo
