### ISSUE TITLE
Allow modification of ormconfig.json config in createConnection()

### ISSUE THREAD

**Issue by craig552uk** [typeorm/typeorm#373]
The CLI migration requires DB config to be in JSON file (e.g. `ormconfig.json`), which means it's not possible to set attributes which are not JSON-serialisable (e.g. `options.logging.logger`) when establishing a connection.

I'd like to be able to do something like below, to specify further options, in addition to those loaded from `ormconfig.json`.
```javascript
typeorm.createConnection("production", "ormconfig.json", {
  logging: {
    logger: (level, msg) => { /* ... */ }
  }
}).then(connection => { /* ... */ })
```

I'm aware that I could provide a configuration object to `createConnection()`, but then I would have to duplicate config between the the application source and `ormconfig.json`.

**Comment by pleerock** [comment]
But you can do it easy as 

```ts
const config = Object.assign(require("ormconfig"), { // find with name "default" if needed
  logging: {
    logger: (level, msg) => { /* ... */ }
  }
});
createConnection("production", config).then(connection => { /* ... */ });
```

**Comment by craig552uk** [comment]
Thanks, `createConnection` doesn't accept arguments like `createConnection(ConnectionName, ConnectionOptions)` (At least not in v0.0.9).

However the below does work.
Presumably because of `require()` caching...?

```javascript
const ormConfig : ConnectionOptions = require("ormconfig.json").map(con => {
  con.logging = con.logging || {};
  con.logging.logger = (level, msg) => { /* ... */ };
  return con;
});
createConnection("production").then(connection => { /* ... */ });
```

Either way, `createConnection(ConnectionName, ConnectionOptions)` would be a useful API to provide.

**Comment by pleerock** [comment]
> Presumably because of require() caching...?

Probably yes, but it does not look good, better if you do it the way I described.

> Either way, createConnection(ConnectionName, ConnectionOptions) would be a useful API to provide.

ConnectionName is already in ConnectionOptions, so ConnectionOptions is enough. I edited my last comment a bit, it was wrong. You just need to rewrite and pass a config object

**Comment by pleerock** [comment]
In the latest `0.1.0-alpha.8` you can do it this way:

```ts
    const options = await new ConnectionOptionsReader().get("default");
    Object.assign(options, { logger: { /*...*/ } });
    const connection = await getConnectionManager().create(options).connect();
```

**Comment by pleerock** [comment]
please let me know if you still have questions.
