### ISSUE TITLE
Question: How to keep all relations when only filtering by one of them

### ISSUE THREAD

**Issue by Sheng-Xuan** [typeorm/typeorm#3731]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a User table and  a Category table, the relation is many-to-many,

I want to select all users who are under a specific category.

```ts
    users = await userRepository
      .createQueryBuilder('user')
      .leftJoinAndSelect('user.categories', 'category')
      .where('category.categoryId = :id', { id: catId})
      .orderBy('user.age', 'DESC', 'NULLS LAST')
      .getMany();
```

It filters correct users, but under each user, only the requested category Id is kept. But I want to keep all the categories under each user. I did not find a similar question for this and did not find a solution in the docs.

i.e.

```ts
users = [
{ id = 1, categories: [ cat1, cat2, cat3...] },
{ id = 2, categories: [ cat1, cat2, cat3...] }
...
]
```

not 

```ts
users = [
{ id = 1, categories: [cat2] },
{ id = 2, categories: [cat2] }
...
]
```

My current solution is using findByIds with relations, passing in all the userIds got from the previous step,  I can get what I want but I don't think it is optimal.

Does anyone know how to handle such query?

Thanks a lot.

**Comment by vlapo** [comment]
Just fast tip but try this:
```typescript
users = await userRepository
      .createQueryBuilder('user')
      .leftJoin('user.categories', 'category')
      .leftJoinAndSelect('user.categories', 'categorySelect')
      .where('category.categoryId = :id', { id: catId})
      .orderBy('user.age', 'DESC', 'NULLS LAST')
      .getMany();
```

**Comment by Sheng-Xuan** [comment]
@vlapo That works. Thanks a lot!
