### ISSUE TITLE
Saving nested entities plain object

### ISSUE THREAD

**Issue by Dancia** [typeorm/typeorm#3733]
**Issue type:**

[x] question

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**
```ts
@Entity("foos")
export class Foo {
    @PrimaryGeneratedColumn()
    public foo_id!: number;

    @Column()
    public foo_name!: string;

    @OneToMany(_ => Bar, inverseSide => inverseSide.bar)
    @JoinColumn({ referencedColumnName: "bar_id", name: "bar_id" })
    public bars!: Bars[];
}

@Entity("bars")
export class Bar {
    @PrimaryGeneratedColumn()
    public bar_id!: number;

    @Column()
    public bar_name!: string;

    @ManyToOne(type => Foo, foo => foo.bars)
    @JoinColumn({ referencedColumnName: "foo_id", name: "foo_id" })
    public foo!: Foo;
}

// A: Foo is created, but bars are not.
getRepository(Foo).save({
    foo_name: "foo",
    bars: [{ bar_name: "bar1" }, { bar_name: "bar2" }]
});

// B: Works fine.
const foo = getRepository(Foo).save({
    foo_name: "foo"
});
const bar1 = getRepository(Bar).save({
    bar_name: "bar1"
});
const bar2 = getRepository(Bar).save({
    bar_name: "bar1"
});
foo.bars = [bar1, bar2];
getRepository(Foo).save(foo);
```

`B` method works fine, but I would like to do it `A`'ish. Does `TypeORM` support save'ing of nested object? If yes, how do I do it correctly?

**Comment by Dancia** [comment]
`cascade` is what I was searching for.

**Comment by Warchant** [comment]
@Dancia could you share small example?

**Comment by rmainseas** [comment]
@Warchant so in your `@ManyToOne(type => Foo, foo => foo.bars)` you'd just add `{cascade: true}` as a third param

**Comment by subhrashisdas** [comment]
TypeORM version: 0.2.22

```ts
import {
  Column,
  ConnectionOptions,
  createConnection,
  Entity,
  getRepository,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn
} from 'typeorm';

@Entity("foos")
export class Foo {
  @PrimaryGeneratedColumn()
  public foo_id!: number;

  @Column()
  public foo_name!: string;

  @OneToMany(_ => Bar, inverseSide => inverseSide.foo)
  @JoinColumn({ referencedColumnName: "bar_id", name: "bar_id" })
  public bars!: Bar[];
}

@Entity("bars")
export class Bar {
  @PrimaryGeneratedColumn()
  public bar_id!: number;

  @Column()
  public bar_name!: string;

  @ManyToOne(type => Foo, foo => foo.bars, { cascade: true })
  @JoinColumn({ referencedColumnName: "foo_id", name: "foo_id" })
  public foo!: Foo;
}

// A: Foo is created, but bars are not.

async function main() {
  const connectionString: ConnectionOptions = {
    type: "postgres",
    host: "localhost",
    username: "postgres",
    password: "password",
    database: "test",
    synchronize: true,
    logging: true,
    entities: [Foo, Bar]
  };
  await createConnection(connectionString).then(async (connection) => {
    await getRepository(Foo).save({
      foo_name: "foo",
      bars: [{ bar_name: "bar1" }, { bar_name: "bar2" }]
    });
  });
}

main()
  .then(console.log)
  .catch(console.log);
```

Still not working. Only foos is saved. Bars table isn't saved.

**Comment by tobiaskraus** [comment]
any news on that?

Your examples used `@JoinColumn` on both sides of the relation. But TypeOrm DOcumentation states:

> Only one side of relational can be owning. Using @JoinColumn decorator is required on the owner side of the relationship

Might not cause the problem though.

I got a similar problem:

```ts
// parent
@Entity()
export class Ticket {
  @OneToOne(() => TicketMedia, { cascade: true })
  @JoinColumn()
  mediaFields?: TicketMedia;
}

// child
@Entity()
export class TicketMedia {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => TicketMediaFormat,{onUpdate: 'CASCADE', cascade: true, onDelete: 'CASCADE', nullable: true })
  @JoinColumn({referencedColumnName: 'id', name: 'formatId'})
  format: TicketMediaFormat;

  formatId: number;
}

// nested child
@Entity()
export class TicketMediaFormat {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;
}
```

tried this to save:

```ts
getRepository(Ticket)
.save({
  id,
  mediaFields: {
    formatId: 3
  }
});
```

it updates Ticket, and creates new TicketMedia (mediaFields) and references them. BUT it does not reference to existing TicketMediaFormat with ID = 3

**Comment by tobiaskraus** [comment]
I think my quote before might explain your problem. You should remove the `@JoinColumn()` from Foo and add `cascade: true` as the other comments stated.

My problem was another thing: I could not cascade insert by setting the JoinColumn value (`formatId`) but had to pass instead the TicketMediaFormat object with `id` set.

```ts
getRepository(Ticket)
.save({
  id,
  mediaFields: {
    format: {
      id: 3
    }
  }
});
```

It's stupid though, cause the TicketMediaFormat Entity might have more properties which I'm not interested as I just want to reference to an existing entity (id comes from Client, and I don't want to query the actual media)

**Comment by tobiaskraus** [comment]
seems like I can also use the JoinColumn to reference existing child entities in `save()` method without retrieving first the Child Entities. This works when we define the `@JoinColumn` again explicitly with `@Column()`:

```ts
  @ManyToOne(() => TicketTrainingFormat,{ cascade: true, nullable: true })
  @JoinColumn({referencedColumnName: 'id', name: 'formatId'})
  format: TicketTrainingFormat;

  @Column()
  formatId: number;
```

```ts
getRepository(Ticket)
.save({
  id,
  mediaFields: {
    formatId: 3
  }
});
```

found this solution here: https://stackoverflow.com/a/61433772/4623244

**Comment by VictorCurean** [comment]
I still cannot find a way to make it work, even with `{cascade: true}`.  I tried playing around with the parameters but the many-to-one entities are not saved. TypeORM version: 0.2.31 with and postgres: 12.5

**Comment by RomanDeveloperAcc** [comment]
Hello. As for this issue, looks like the `{ cascade: true }` param should be added to `@OneToMany` relation, but not the `@ManyToOne`. I hope it is resolved, but sharing this info just in case someone needs that.

**Comment by totalard** [comment]
Does this work with Many2Many ? seems not working
