### ISSUE TITLE
Audit spits lot of security warnings !

### ISSUE THREAD

**Issue by Sharlaan** [typeorm/typeorm#3734]
**Issue type:**

[ ] question
{x] dependency/security report
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**
`latest 0.2.14`

**Steps to reproduce or a small repository showing the problem:**
1. mount a project based on TypeORM
2. yarn audit

Step 2 will spit warnings :
> yarn audit 1.13.0
>
> 24 vulnerabilities found - Packages audited: 85783
Severity: 6 Low | 10 Moderate | 8 High
<details><summary>Audit details</summary>
<pre>
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ moderate      │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ mime                                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >= 1.4.1 < 2.0.0 || >= 2.0.3                                 │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > less >   │ 
│               │ mime                                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/535                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ moderate      │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ mime                                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >= 1.4.1 < 2.0.0 || >= 2.0.3                                 │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > less >   │ 
│               │ request > form-data > mime                                   │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/535                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ moderate      │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ mime                                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >= 1.4.1 < 2.0.0 || >= 2.0.3                                 │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > mime     │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/535                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ low           │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ debug                                                        │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > knox >   │ 
│               │ debug                                                        │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/534                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ high          │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ minimatch                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=3.0.2                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > gear >   │ 
│               │ liftoff > findup-sync > glob > minimatch                     │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/118                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ high          │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ minimatch                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=3.0.2                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > glob >   │ 
│               │ minimatch                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/118                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ high          │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ minimatch                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=3.0.2                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > jshint > │ 
│               │ cli > glob > minimatch                                       │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/118                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ high          │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ minimatch                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=3.0.2                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > jslint > │ 
│               │ glob > minimatch                                             │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/118                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ high          │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ minimatch                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=3.0.2                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > jshint > │ 
│               │ minimatch                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/118                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ high          │ Prototype Pollution                                          │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ handlebars                                                   │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=4.0.13                                                     │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib >          │ 
│               │ handlebars                                                   │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/755                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ high          │ Cross-Site Scripting                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ handlebars                                                   │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=4.0.0                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib >          │ 
│               │ handlebars                                                   │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/61                        │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ low           │ Incorrect Handling of Non-Boolean Comparisons During         │ 
│               │ Minification                                                 │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ uglify-js                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >= 2.4.24                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib >          │ 
│               │ handlebars > uglify-js                                       │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/39                        │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ low           │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ uglify-js                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=2.6.0                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib >          │ 
│               │ handlebars > uglify-js                                       │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/48                        │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ low           │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ uglify-js                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=2.6.0                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib >          │ 
│               │ uglify-js                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/48                        │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ low           │ Arbitrary File Write                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ cli                                                          │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=1.0.0                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > jshint > │ 
│               │ cli                                                          │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/95                        │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ low           │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ clean-css                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=4.1.11                                                     │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > less >   │ 
│               │ clean-css                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/785                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ moderate      │ Remote Memory Exposure                                       │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ request                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=2.68.0                                                     │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > less >   │ 
│               │ request                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/309                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ moderate      │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ hawk                                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=3.1.3 < 4.0.0 || >=4.1.1                                   │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > less >   │ 
│               │ request > hawk                                               │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/77                        │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ moderate      │ Prototype Pollution                                          │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ hoek                                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > less >   │ 
│               │ request > hawk > boom > hoek                                 │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/566                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ moderate      │ Prototype Pollution                                          │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ hoek                                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > less >   │ 
│               │ request > hawk > cryptiles > boom > hoek                     │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/566                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ moderate      │ Prototype Pollution                                          │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ hoek                                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > less >   │ 
│               │ request > hawk > hoek                                        │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/566                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ moderate      │ Prototype Pollution                                          │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ hoek                                                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > less >   │ 
│               │ request > hawk > sntp > hoek                                 │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/566                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ high          │ Regular Expression Denial of Service                         │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ minimatch                                                    │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=3.0.2                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear > liftoff >    │ 
│               │ findup-sync > glob > minimatch                               │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/118                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
┌───────────────┬──────────────────────────────────────────────────────────────┐ 
│ moderate      │ Memory Exposure                                              │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Package       │ tunnel-agent                                                 │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Patched in    │ >=0.6.0                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Dependency of │ typeorm                                                      │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ Path          │ typeorm > cli-highlight > highlight.js > gear-lib > less >   │ 
│               │ request > tunnel-agent                                       │ 
├───────────────┼──────────────────────────────────────────────────────────────┤ 
│ More info     │ https://nodesecurity.io/advisories/598                       │ 
└───────────────┴──────────────────────────────────────────────────────────────┘ 
</pre>
</details>

**Comment by pleerock** [comment]
related discussion is here #3695

**Comment by Kononnable** [comment]
No vulnerabilities found on typeorm 0.2.15.
