### ISSUE TITLE
How to get entity information in afterDelete/beforeDelete subscriber methods?

### ISSUE THREAD

**Issue by HussainAliAkbar** [typeorm/typeorm#3739]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

I have this class for a subscriber which is working perfect except for the beforeRemove and afterRemove methods.

The entity **user-skills** is a simple entity with 3 fields: **id, userId, skillId**.

```ts
import { EventSubscriber, EntitySubscriberInterface, UpdateEvent, InsertEvent, RemoveEvent } from 'typeorm';
import { UserSkill } from '../entities/user-skill';

@EventSubscriber()
export class UserSkillsSubscriber implements EntitySubscriberInterface<UserSkill> {
  public listenTo() {
    return UserSkill;
  }

  public afterUpdate(event: UpdateEvent<UserSkill>) {
    console.log(`AFTER ENTITY UPDATED: `, event.entity);
  }

  public afterInsert(event: InsertEvent<UserSkill>) {
    console.log(`AFTER ENTITY INSERTED: `, event.entity);
  }

  public beforeRemove(event: RemoveEvent<UserSkill>) {
    console.log(`AFTER ENTITY WITH ID ${event.entityId} REMOVED: `, event.entity);
  }


  public afterRemove(event: RemoveEvent<UserSkill>) {
    console.log(`AFTER ENTITY WITH ID ${event.entityId} REMOVED: `, event.entity);
  }
}

```

My requirement is to get the userId in all the subscribed methods i.e. **afterInsert, afterUpdate and afterDelete**. The afterInsert and afterUpdate methods return the entire entity which includes userId as well which fulfills my requirement. However, for afterDelete and beforeDelete, i keep getting undefined in entity.

**Is there a way we can get the userId somehow in the afterDelete/beforeDelete methods?**

**Comment by johannesschobel** [comment]
Dear @HussainAliAkbar ,
in https://github.com/typeorm/typeorm/issues/3749 someone reported a similar with the `beforeUpdate` method.. Does this work for you?

All the best

**Comment by HussainAliAkbar** [comment]
hey @johannesschobel , Thank you for the reply. But i dont think that #3449 will work for me because the solution in that issue requires me to call the save method which i cant do because i need to delete an entity.

However yes, there can be a method other than .delete() that can be used to get the entity in the beforeDelete() method but i am not sure which one

**Comment by rustamwin** [comment]
Hey @HussainAliAkbar 
the subscriber does not have beforeDelete/afterDelete methods.

you need to use `remove` method to get the entity information

**Comment by juan91** [comment]
the afterRemove method not working.
if it works for these methods : afterInsert, afterUpdate

**Comment by sandesh-bhoir** [comment]
any update on this, I tried both afterRemove and beforeRemove both gives event.entity as undefined

**Comment by bthibault** [comment]
+1 beforeRemove gives undefined entity

**Comment by bthibault** [comment]
for anyone else that finds this -- my issue was i was calling  Repository.delete() , which just runs a database delete where id = foo ... this never retrieves an entity and thus doesn't pass the entity to the subscriber hooks. 

If you need entity in beforeRemove use the remove() method

**Comment by Zo-ambinintsoa** [comment]
+1 beforeRemove and afterRemove `gives` undefined entity

the code : 

```
          // Delete the logement
          const data = await this.logementRepository.delete({ id: lg.id });
```

the listener function : 

```
  /**
   * Called after entity removal.
   */
  afterRemove(event: RemoveEvent<any>) {
    console.log(
      `AFTER ENTITY WITH ID ${event.entityId} REMOVED: `,
      event.entity,
    )
  }
```

return Undefined

**Comment by ashfaqnisar** [comment]
Umm, did anyone resolve this issue ?

**Comment by hershmire** [comment]
Is there a reason why the `beforeRemove()` and `afterRemove()` hooks are still called when `repository.delete(...)` is called? I would expect that these hooks are only called when `repository.remove(...)` is called.

**Comment by taoliujun** [comment]
And in EntityClass, The code here:

```typescript
@AfterRemove()
@AfterSoftRemove()
async subjectDeletion() {
    console.debug('==remove', this.id, this.truename);
}
```

Call `entity.softRemove()`, output is `==remove 3 somebody's name`.
Call `entity.remove()`, output is `==remove undefined somebody's name`.

How can i get the id after `remove`? cry:)
