### ISSUE TITLE
setMaxResults and setFirstResult are not working

### ISSUE THREAD

**Issue by icewind** [typeorm/typeorm#374]
I'm selecting my entities using query builder and I have several joins and group by. 
When I'm using setOffset and setLimit it is working fine, but setMaxResults and setFirstResult are not. 
I tried to print generated query using `queryBuilder.getSql()` and there is not offset of limit instructions

**Comment by pleerock** [comment]
`setMaxResults` and `setFirstResult` are not simple `limit` and `offset`. Its quite complex operation which make two queries to get your data for pagination purpose. Provide a minimal reproduction example of problem you have

**Comment by icewind** [comment]
Sorry for report like this. I'm in the process of narrowing the area. It is reproducible in my current env and looks like it is related to grouping(not sure). In a meantime offset and limit works fine. 
I've read the code and got the point of setMaxResults/setFirstResult.
