### ISSUE TITLE
Are methods like 'orderBy' sql-injection safe?

### ISSUE THREAD

**Issue by onionhammer** [typeorm/typeorm#3740]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I want to allow callers of API to pass a 'sortBy' parameter, what steps do I have to go through to protect input?

**Comment by pleerock** [comment]
please provide more detailed with small code examples

**Comment by onionhammer** [comment]
@pleerock 

For example; say you're writing an API like this:

```ts
async function getAllAccounts(req) {
    const { limit=0, offset=0, sortBy="" } = req.query;

    const results = await someQuery()
        .offset(+offset)
        .limit(+limit)
        .orderBy(sortBy) // <-- is it safe to take 'sortBy' from the query string or should it be escaped or something?
        .exec();

    return {
        total: 0,
        results
    }
}
```

**Comment by pleerock** [comment]
depends on what exac api you use, your provided code example isn't typeorm's api. If you are talking about query builder then no, its not injection-safe, you need to use parameters to avoid injection.

**Comment by onionhammer** [comment]
Why not make those methods on querybuilder injection safe?

**Comment by onionhammer** [comment]
@pleerock Is it possible to pass a parameter into the 'order by' clause of a query?

**Comment by Kononnable** [comment]
It's not possible.
Some might say it's sql servers limitation, but in reality it's how sql servers are working. Parameters can't change execution plan of the query. They can only change value of what is compared to field in a table(or view, or computed value etc.). Specifying different 'order by' clause may change execution plan - you could even put a subquery there.

**Comment by onionhammer** [comment]
Entity framework has no trouble with this @Kononnable

**Comment by Kononnable** [comment]
@onionhammer 
Could you please put a code snippet here with a way of doing it in EF? I'm pretty sure sql parameters doesn't allow that, but it would be great to learn something new.

**Comment by onionhammer** [comment]
@Konnable, come to think of it, I’ve done it with expression parsing which translates to a different sql query at runtime, not a parameterized query, but something like that probably isn’t possible with no runtime types. Perhaps if with whatever runtime checking typeorm does for relationship resolution

**Comment by Kononnable** [comment]
Problem with orderBy and making it injection safe is variety of things that can go there. We can even put a subquery there.
Closing - question was answered. If you like you can make w feature request, but I doubt it will be implemented because of its complexity.

**Comment by onionhammer** [comment]
I would say the very least that should be done is guidance on what methods are safe and what aren't. There are a lot of calls in this library that take strings, which just invites people to put unsafe ones inside them

**Comment by benatkin** [comment]
I'm concerned about this. It would be great to re-visit.
