### ISSUE TITLE
Add to migrations atomic flag in MigrationInterface

### ISSUE THREAD

**Issue by Insidexa** [typeorm/typeorm#3743]
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**
( all db where exist DDL transaction )

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Need to implement in typeorm migrations atomic mode. By default all migrations atomic.
Disable atomic mode need when you create migration, for example,  add not nullable column to table, but you can`t add not null column on exists data.
In this problem you have two ways to solve this problem.
1. Delete all data, and add not nullable column.
2. Add not nullable column, fill this column or default value and change column to not nullable

Python, Django backend framework
> Update existing rows
> Update December 2017: Support for non-atomic migrations was added to Django 1.10. The following hacks are not necessary anymore.
> Updating data in batches as part of your data migration is tricky because you will have to break out of the database transaction that is already started by the migration executor.

2 way is the most correct. 
But, in typeorm when run migration ( wrap up and down methods in transaction ). Its not allow to modify table data. Only select.

Need to implement manually run transaction in typeorm migration.

Would expect such behavior
```
export class AddSomeColumnNotNullToUserEntity1551270058491 implements MigrationInterface {

    public ATOMIC = false; // disable transaction only this migration

    public async up(queryRunner: QueryRunner): Promise<any> {

        // add nullable column to user entity

        // update nullable column with some data

        // add not null to column
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        // drop column
    }

}
```

Thanks.

**Comment by johannesschobel** [comment]
what kind of data would you insert for the `not null` column if no data exist? this would throw an error..

**Comment by Kononnable** [comment]
>Add not nullable column, fill this column or default value and change column to not nullable

I think you wanted to add nullable column at the beginning(or I misunderstood you)

3rd option:
Add not nullable column with default value, then change it if necessary

Could you give as an example of what is not possible right now? Tbh I don't see what is blocked by transaction right now. Transactions are necessary here in case something went wrong - without transaction we wouldn't know in what exact state is db.

**Comment by rupurt** [comment]
I would love to be able to disable transactions on a per migration basis

**Comment by airhorns** [comment]
@Insidexa would you mind explaining why this was closed?

I think a big use case for a non-transactional migration would be a script that loops over all the data in the database and does something useful with it, like updating a `jsonb` column to move data around. The migration interface already makes this possible by just passing in a query runner, so it's easy to fetch the list of stuff and then save it. But, if the migration is wrapped in an automatic transaction, it means that every row the migration touches will be locked for the duration of it, which is a very big, very slow transaction. 

It's not strictly a series of DDL statements, but it's still a unit of work that all the developers need to run to continue developing, and that needs to run in production once, so it'd still be great to use the migrations system to execute a change like this. I think if users want to drop the transactional requirement, they should be able to.

**Comment by romandvoskin-circle** [comment]
Please consider this feature. In my case its for CREATE DATABASE for Postgres - this command is not allowed to be run in a transaction.
