### ISSUE TITLE
Google Datastore support?

### ISSUE THREAD

**Issue by kmturley** [typeorm/typeorm#3748]
**Issue type:**
[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**
[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**
[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Description:**
When hosting sites on Google Cloud, you can support MongoDB or other databases, but they require a Flexible environment which costs more. You can also use Google Cloud SQL, but that is a relational database.

Is there a plan to support Google Datastore (non-relational database) which is scalable and runs on the standard environment?
https://github.com/googleapis/nodejs-datastore

The NodeJS example:
```
const {Datastore} = require('@google-cloud/datastore');

async function quickStart() {
  const projectId = 'YOUR_PROJECT_ID';
  const datastore = new Datastore({
    projectId: projectId,
  });
  const kind = 'Task';
  const name = 'sampletask1';
  const taskKey = datastore.key([kind, name]);
  const task = {
    key: taskKey,
    data: {
      description: 'Buy milk',
    },
  };
  await datastore.save(task);
  console.log(`Saved ${task.key.name}: ${task.data.description}`);
}
quickStart().catch(console.error);
```

**Comment by Kononnable** [comment]
As it was mentioned multiple times we don't have in plans to implement new drivers in a near future. If you want to contribute - please feel free! To keep issues cleaner lets close this one and continue discussion in #4

**Comment by kmturley** [comment]
Ok sounds good, thanks!
