### ISSUE TITLE
Entity field in EventSubscriber beforeUpdate payload

### ISSUE THREAD

**Issue by Varkal** [typeorm/typeorm#3749]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest` 
[ ] `@next`
[x ] `0.2.14`

I've created an EventSubscriber for my User Entities 

```ts
export class UserSubscriber implements EntitySubscriberInterface<User> {

    listenTo() {
        return User;
    }

    beforeInsert(event: InsertEvent<User>) {
        console.log("INSERT", event);
    }

    beforeUpdate(event: UpdateEvent<User>) {
        console.log("UPDATE", event)
    }
}
```
And on update, with this line :

```ts
await this.userRepository.update(id, {password: "pipo"});
```

beforeUpdate hook is fired, but in the console.log i got
```ts
{
    ...
    entity: undefined, 
    databaseEntity: undefined, 
    updatedColumns: [], 
    updatedRelations: []
}
```
So i can't update the payload (hash password for example) or event know which entity is updated 

But in the database, the update have been made

**Comment by johannesschobel** [comment]
This issue https://github.com/typeorm/typeorm/issues/3739 may be related?

**Comment by Varkal** [comment]
Maybe ! It's strange that's work only in beforeInsert, but I don't try the other hooks

**Comment by rustamwin** [comment]
Please use `save` instead of `update`

**Comment by johannesschobel** [comment]
@rustamwin , what do you mean exactly? Like so:
```ts
// use save() instead of update()
await this.userRepository.save(id, {password: "pipo"});
```

Thanks a lot

**Comment by rustamwin** [comment]
> await this.userRepository.save(id, {password: "pipo"});

@johannesschobel Yeah

**Comment by rustamwin** [comment]
@Varkal Did you resolve your issue?

**Comment by Varkal** [comment]
Hi @rustamwin, sorry for the late answer, i've been very busy this week. 
And no this doesn't seems to work : 

```ts
// use save() instead of update()
await this.userRepository.save(id, {password: "pipo"});
```

throw a MustBeEntityError 

```
MustBeEntityError: Cannot save, given value must be an entity, instead "2" is given.
    at new MustBeEntityError (/.../src/error/MustBeEntityError.ts:8:9)
    at EntityPersistExecutor.execute (/.../src/persistence/EntityPersistExecutor.ts:46:35)
    at EntityManager.save (/.../src/entity-manager/EntityManager.ts:316:14)
    at Repository.save (/.../src/repository/Repository.ts:140:29)
    at UserController.<anonymous> (/.../src/user/user.controller.ts:87:35)
    at Generator.next (<anonymous>)
    at /.../src/user/user.controller.ts:19:71
    at new Promise (<anonymous>)
    at __awaiter (/.../src/user/user.controller.ts:15:12)
    at UserController.updateUser (/.../src/user/user.controller.ts:65:16)
```

Maybe I do something wrong ?

**Comment by rustamwin** [comment]
@Varkal you should pass `Entity` instead of `id`
for example: 
```typescript
user.password = 'pipo';
await this.userRepository.save(user);
```

**Comment by vinimdocarmo** [comment]
> Please use save instead of update

The problem with this is that every developer now and forever has to remember (unknown unknown) using `.save` because of the subscriber implementation. Is there any other way to get the entity old values in my subscriber even though I'm using the method `repository.update`?

Already tried using `event.manager` to get the old values from database, but it is using the same transaction as the update, so I'm getting the newer values.
