### ISSUE TITLE
Post Migration EntityColumnNotFound Error

### ISSUE THREAD

**Issue by judemanutd** [typeorm/typeorm#3750]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Initial Structure 

```ts
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn
} from "typeorm";

@Entity()
export class StudentLogins {
  @PrimaryGeneratedColumn()
  id: number;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @Column({ type: "tinyint", default: 1 })
  status: number;
}
```

> Skipped a few columns for brevity

Step 1. Run a migration to add a `retry` column and a `last_login_attempt` column 

```ts
import { MigrationInterface, QueryRunner } from "typeorm";

export class studentLoginRateLimit1551614884815 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(`ALTER TABLE student_logins ADD retry tinyint default 0`);
    await queryRunner.query(`ALTER TABLE student_logins ADD last_login_attempt text`);
  }

  async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(`ALTER TABLE student_logins DROP COLUMN retry`);
    await queryRunner.query(`ALTER TABLE student_logins DROP COLUMN last_login_attempt`);
  }
}
```
>Verified the database, the columns were created and migration table was updated 

Step 3 : Updated the model file manually to reflect the change

```ts
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn
} from "typeorm";

@Entity()
export class StudentLogins {
  @PrimaryGeneratedColumn()
  id: number;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @Column({ type: "tinyint", default: 1 })
  status: number;

  @Column({ type: "tinyint", default: 1 })
  retry: number;

  @Column({ type: "text" })
  last_login_attempt: string;
}
``` 

Step 4 : Fetch from the table

```ts
const query = getRepository(StudentLogins)
      .createQueryBuilder()
      .select([
        "id",
        "retry",
        "last_login_attempt",
      ]);

    const data = await query.getRawOne();
```

When trying to run the above query I get a `EntityColumnNotFound` error with the message `No entity column "retry" was found.`. I enabled logging so typeorm generates the raw query in the console which I can run manually in the sql console and it works fine. Seems like typeorm is out of sync with the database. Am I missing a step here ?

Do I need to run `synchronize`, wouldn't that beat the point of migrations?

**Comment by DustinTheGreat** [comment]
did you find  a fix mate?
