### ISSUE TITLE
[EntitySchema] Better Tyings

### ISSUE THREAD

**Issue by johannesschobel** [typeorm/typeorm#3757]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When trying to work with `EntitySchema`s, i stumbled upon this inconsistency in the API. Consider the following example:

```ts
export const UserSchema = new EntitySchema<User>({
  name: 'InstrumentSchema',
  tableName: 'instruments',

  columns: {
    // not important for this case
  },
  relations: {
    project: {
      type: 'many-to-one',
      target: 'ProjectSchema',
      joinColumn: { name: 'project_id', referencedColumnName: 'id' },
    },
  },
});
```

Note that the `relations.*.target` is typed as `Function | string` here:
https://github.com/typeorm/typeorm/blob/a12e72d417638ea8fba2ca672d5acfaaaaf691c9/src/entity-schema/EntitySchemaRelationOptions.ts#L13

Wouldn't it be better to actually type it as:
```ts
target: EntitySchema | Function | string;
```

What do you think?
All the best

**Comment by imnotjames** [comment]
The typing has been updated to be `EntityTarget` in most places so this should be handled!
