### ISSUE TITLE
Android data insertion is too slow(cordova)

### ISSUE THREAD

**Issue by coturiv** [typeorm/typeorm#3758]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.14` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
ts...

const entity = 'xxx';
await getManager().transaction(async tem => {
        const records = await getRecords(); // load over 30,000 records from api.
        
        await tem.clear(entity);

        const start = performance.now();
        await tem.save(records);
        const end = performance.now();
        console.log(`Synchronized for ${end - start} ms.`);
});
```
But, I am getting different results for iOS, Android, and browser(uses sql.js).

> iOS:  20s ~ 30s
> Android:  15 minutes ~ 20 minutes
> Browser: < 15s

**Comment by mhgs** [comment]
Same here, Android Behavior is not that far of as in your case. However i see more than double amount of time needed comparing the browser Vs. Cordova. 

Same situation, simple large batch save from API results. Browser with sqljs blazing fast for these amounts of data, between 5-10 seconds. Cordova/sqlite uses aprox. 20-35. Latat verslons of TypeORM and Cordova SQLite plug-in

**Comment by coturiv** [comment]
Solution was to use **sql.js** on Android, instead of **cordova**.

**Comment by mhgs** [comment]
Using sql.js is not a real solution, it's just a workaround. The real issue is still here, the difference in performance with the same data using the Cordova/sqlite vs sqljs. I'm still debugging to see whether the TypeORM or the Cordova lib is causing these issues, but I think this issue should not be closed right know.

**Comment by mablae** [comment]
Here is what is tried: Using sqljs with `useLocalForage : true` is superfast and resolves to IndexedDB on my phone. However different sources say these type of storage may be deleted by the OS like `localStorage`. It only solves the space limitations.

Using `cordova` is however incredible slow and only works on debug builds at least for me.

**Comment by SimMue** [comment]
@mhgs did you find any solution to your problem?
I got the same problem. When trying to save ~5'000 records it takes up to 2 minutes to insert them on an android device with  `cordova`.

**Comment by mhgs** [comment]
> @mhgs did you find any solution to your problem?
> I got the same problem. When trying to save ~5'000 records it takes up to 2 minutes to insert them on an android device with `cordova`.

Nope, not a real solution, with localstorage no issue, on the device itself we ran into issues, currently we've optimized our data to insert up to 10.000 records in 30/35 seconds. Import is that you use batch inserts then you can play with the size of each batch to tweak the performance. Note: this is also heavily impacted by the device itself, so a batch size that is optimal for your device can possibly slow down on another device for what we've encountered.

**Comment by raymondboswel** [comment]
I experienced the same issue, where about 20000 records would take 2 minutes to insert. After having spent a lot of time trying to optimize TypeORM, I ended up using SQLiteporter for inserting my entities. I also needed upsert functionality, so handcrafted some SQL based on https://www.sqlite.org/draft/lang_UPSERT.html and executed the SQL directly on the SQL database. The performance gain has been great, down to approximately 20s. 

I still use TypeORM for all other queries, thereby keeping the ORM goodness without the performance drag in key areas.

**Comment by imnotjames** [comment]
Not much that typeorm can do at the moment for cordova being that much slower.

In the future we might look at techniques to batch up inserts / updates but until then you might want to open issues against the upstream projects.

If there's a more actionable detail I missed I'd be glad to hear it, though.

**Comment by imnotjames** [comment]
Also if you can use sql.js use 1.3.2 with wasm!
