### ISSUE TITLE
use mongo operator error

### ISSUE THREAD

**Issue by luanxuechao** [typeorm/typeorm#3760]
**Issue type:**

[] question
[x] bug report
[] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `mongodb`
**TypeORM version:**
[x ] `0.2.9` 

**Steps to reproduce or a small repository showing the problem:**
```ts
this.tmpRepository.count({
         id:id,
          status: {$ne: 0},
      });
```
the error is  `Type '{ $ne: number; }' is not assignable to type 'number | FindOperator<number> | undefined'.`

but when I use `$ne` in `find`,there is no error, why?

**Comment by imnotjames** [comment]
You need to type it as a `MongoRepository` not a `Repository`
