### ISSUE TITLE
Change in FK generation for MySQL

### ISSUE THREAD

**Issue by Slessi** [typeorm/typeorm#3761]
**Issue type:**

[x] question

**Database system/driver:**

[x] `mysql`

**TypeORM version:**

[x] `0.2.14`

**Steps to reproduce or a small repository showing the problem:**

In PR #3692 (specifically commit 849e0de) the following changes were introduced to [src/metadata/ForeignKeyMetadata.ts#L83..L84](https://github.com/typeorm/typeorm/blob/849e0de2f15a9ece282fda2b7eb142645b08aaa0/src/metadata/ForeignKeyMetadata.ts#L83..L84)

```diff
- this.onDelete = options.onDelete;
- this.onUpdate = options.onUpdate;
+ this.onDelete = options.onDelete || "NO ACTION";
+ this.onUpdate = options.onUpdate || "NO ACTION";
```

This changes the behaviour for MySQL, which uses `RESTRICT` by default as per [docs](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html)

> For an `ON DELETE` or `ON UPDATE` that is not specified, the default action is always `RESTRICT`.

Whilst technically the same ...

> `NO ACTION`: A keyword from standard SQL. In MySQL, equivalent to `RESTRICT`.

... was this an intended change?

Generating a migration now re-generates all my FKs from `RESTRICT` -> `NO ACTION`. After running the generated migration, further migration generations will not repeat the action, but want to confirm if this was intended.

**Comment by Kononnable** [comment]
Adding @AlexMesser

**Comment by AlexMesser** [comment]
Yes, it was intended. We need it because when these options are not defined in foreign key definition, DBs set them as `NO ACTION` and its causes problems with further schema syncronizations.

**Comment by Slessi** [comment]
@AlexMesser Ok, so long as it is going to stay this way I can just update my db
