### ISSUE TITLE
typeorm-model-shim.js in ionic v4

### ISSUE THREAD

**Issue by queejie** [typeorm/typeorm#3762]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
We would love to use the typeorm-model-shim, but there is no webpack.config.js in ionic 4.  Would you have any idea on how to get the path alias into an ionic 4 build?

**Comment by imnotjames** [comment]
Custom ionic 4 webpack plugin can be found here -- https://www.npmjs.com/package/@angular-builders/custom-webpack

Found via https://stackoverflow.com/questions/56620462/how-to-use-custom-webpack-configuration-in-ionic-4

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
