### ISSUE TITLE
Sorting over nested object key with postgres as backend 

### ISSUE THREAD

**Issue by pawan-saxena-srijan** [typeorm/typeorm#3765]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
It's a question, already put on stackoverflow but no response there till now; so looking forward for some help here : 

I am using typeorm to stored a large object inside the postgres database as json object. The object somewhat looks like :

```
{
  "id": {
    "value": "46bcf52a-01be-43ee-8ee3-8a47479340f5"
  },
  "task": {
    "id": {
      "value": "2f880880-2e01-11e9-ad01-632c0693ada2"
    },
    "key1": {
      "value": {
        "id": {
          "id": "2f880881-2e01-11e9-ad01-632c0693ada2",
          "key": "id",
          "value": "46bcf52a-01be-43ee-8ee3-8a47479340f5",
          "label": "Id",
          "flags": []
        },
        "name": {
          "id": "2f882f91-2e01-11e9-ad01-632c0693ada2",
          "key": "name",
          "value": "Some Value",
          "label": "Name",
          "flags": []
        },
        "dataAsOf": {
          "id": "2f8856a1-2e01-11e9-ad01-632c0693ada2",
          "key": "dataAsOf",
          "value": "2019-02-11T13:30:23.882Z",
          "flags": [],
          "source": "some source",
          "label": "dataAsOf"
        }
      }
    },
    "dueDate": {
      "value": "2019-02-11T13:30:23.881Z"
    },
    "processToBeCalled": {
      "value": "demoPorcess"
    },
    "role": {
      "value": "demoRole"
    },
    "key5": {
      "value": "46bcf52a-01be-43ee-8ee3-8a47479340f5"
    },
    "collection": {
      "value": [
        {
          "id": {
            "value": "2efb7ff0-2e01-11e9-ad01-632c0693ada2"
          },
          "fields": {
            "value": {
              "key2": {
                "id": "2efb7ff1-2e01-11e9-ad01-632c0693ada2",
                "key": "some value",
                "value": "some value",
                "source": "some value",
                "label": "some value",
                "flags": []
              },
              "key3": {
                "id": "2efb7ff2-2e01-11e9-ad01-632c0693ada2",
                "key": "some value",
                "value": "0",
                "source": "some value",
                "label": "some value",
                "flags": []
              },
              "classIdentifier": {
                "id": "2efb7ff3-2e01-11e9-ad01-632c0693ada2",
                "key": "classIdentifier",
                "value": "TF",
                "source": "working_trial_balance",
                "label": "ClassIdentifier",
                "flags": [
                  {
                    "id": "2efb7ff4-2e01-11e9-ad01-632c0693ada2",
                    "type": "errors"
                  }
                ]
              },
              "entityNumber": {
                "id": "2efb7ff9-2e01-11e9-ad01-632c0693ada2",
                "key": "entityNumber",
                "value": "5501",
                "source": "some value",
                "label": "EntityNumber",
                "flags": [
                  {
                    "id": "2efb7ffa-2e01-11e9-ad01-632c0693ada2",
                    "type": "errors"
                  }
                ]
              },
              "glAccountNumber": {
                "id": "2efb7ffe-2e01-11e9-ad01-632c0693ada2",
                "key": "glAccountNumber",
                "value": "1234567890",
                "source": "testGlAccountNumber",
                "label": "GlAccountNumber",
                "flags": []
              },
              "qualifierDescription": {
                "id": "2efb8002-2e01-11e9-ad01-632c0693ada2",
                "key": "qualifierDescription",
                "value": "",
                "source": "some value",
                "label": "some value",
                "flags": []
              },
              "dueDate": {
                "id": "2f8856a2-2e01-11e9-ad01-632c0693ada2",
                "key": "dueDate",
                "value": "2019-02-11T13:30:23.882Z",
                "flags": [],
                "source": "Data Science / BO-Service",
                "label": "dueDate"
              }
            }
          },
          "key4": {
            "value": "466423a0-2306-11e9-a69a-0242ac130006"
          }
        }
      ]
    }
  }
}
```

My database holds a large number of these json objects. My goal is to do sorting (groupBy) over two (or more) fields which are :
`name` inside  `key1`
`entityNumber`
and 
`glAccountNumber`
So first all objects should get sorted over name, entityNumber and then glAccountNumber which are at different level inside the object, i was also thinking of using a limit clause. Right now i fetching objects from postgres using typeorm as :

```
public async read(id?: Array<string>) {
    if (id === undefined) {
        return false;
    }
    let data: any;
    this.relations = undefined ? [] : this.relations;
    data = await this.repository.find({
        where: { id: In(id) },
        "relations": this.relations
    });
    return data;
}
```

so this function simply reads the objects also fetching any relations it might have. Need help to move in right direction, is there any way alreay in postgres or typeorm to achieve this.

**Comment by Kononnable** [comment]
I love when people just copy paste without formatting code. It's so readable, it's so encouraging.

Can you fetch all those records and group by them on your backed side, or there may be to much info(too slow) and you have to do it on sql database side?

**Comment by pawan-saxena-srijan** [comment]
@Kononnable 
Thanks for the feedback about formatting.
Will keep it in mind from next time.
For now can you give it a try :)

Yes i fetched all records from the postgres and group them in my backend but due to heavy sizes of objects i cannot pull all the required records and just a couple of them.

**Comment by Kononnable** [comment]
I don't think typeorm will give you mach of a hand here. I didn't find anything which would help with working on complex JSON columns on server side.
This means you have to use raw query/query builder and 'json part' of sql yourself.
Here is a tutorial of querying json columns in postgres http://www.postgresqltutorial.com/postgresql-json/

**Comment by pawan-saxena-srijan** [comment]
@Kononnable thanks.
I will give it a try today and let you know with benchmarks.

**Comment by Kononnable** [comment]
I didn't use rdbms with json columns yet, so I'm definitely not an expert in this matter. SQL is mostly standardized - if there is same api available in different db engines it should be easy to achieve. If not we would have to specify different versions of implementation for each driver. Either way it's probably just a few sql statements so probably no using of native libraries will be necessary.

**Comment by imnotjames** [comment]
Updated the top post with block tags so the code is more readable.

**Comment by imnotjames** [comment]
Sounds like this question has been more or less answered.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
