### ISSUE TITLE
Deep relation querying where first relation is not set gives wrong result

### ISSUE THREAD

**Issue by Alfalfamale** [typeorm/typeorm#3769]
**Issue type:**

[x] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.14` (or put your version here)

**Code**
https://github.com/Alfalfamale/TypeOrmIssue

**Description**
I'm creating a structure where I have Repositories, Contributions and Users.

A repository has multiple contributions done by different users. It is important that I know the count property on the contribution.

But when I create a new Repository entity without connections I get weird behaviour querying.

**What I noticed**
The query that is executed nests two `LEFT JOIN` statements and that makes it return a broken entity for the first relation.

**What I tried**
Removing the eager on the ManyToOne from Contribution to User fixes the error and I correctly get an empty contributions array. But it isn't really a solution for the repositories that do have contributions.

**Comment by Kononnable** [comment]
It works if you declare primary columns explicitly. It's required in @next version(so your code will be compatible with upcoming changes), in 0.2 it's not required but there might be some errors if you don't do it.

`@JoinTable()` should be used only in ManyToMany relations.

```typescript
@Entity()
export class Contribution{

	@PrimaryColumn()
	repositoryName: string
	
	@PrimaryColumn()
	userGithub: number

	@ManyToOne(type => Repository, repository => repository.contributions)
	@JoinColumn()
	repository: Repository;

	@ManyToOne(type => User, user => user.contributions, {eager: true, cascade: true})
	@JoinColumn()
	user: User;

	@Column()
	count: number;
}
```

**Comment by Alfalfamale** [comment]
Wow, thank you very much @Kononnable , that worked.
