### ISSUE TITLE
How to add uuid as default value using migrations

### ISSUE THREAD

**Issue by davran-siv** [typeorm/typeorm#3770]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

How could I add `uuid_generate_v4()` as a default value using typeorm migrations
For example, 

```ts 
import { MigrationInterface, QueryRunner, Table } from 'typeorm'
import uuid = require('uuid')

export class InitUserTable1551883596067 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.createTable(new Table({
      name: 'users',
      columns: [
        {
          name: 'id',
          type: 'uuid',
          isPrimary: true,
          isUnique: true,
          default: '??'
        }
      ]
    }), true)
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.dropTable('users', true)
  }

}
 ```
If I used sql I would do it this way
```sql 
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
COMMIT;

CREATE TABLE users
(
    id         uuid DEFAULT uuid_generate_v4() PRIMARY KEY
);
```

**Comment by davran-siv** [comment]
@pleerock Please take a look if you have time. I didn't find any examples.

**Comment by davran-siv** [comment]
It worked if I set `default: 'uuid_generate_v4()'`))))

**Comment by yuri-scarbaci-lenio** [comment]
For anyone coming by this and using postgresql this is a way to get uuid generated ids

```
        await queryRunner.createTable(new Table({
            name: "your_table",
            columns: [
                {
                    name: "id",
                    type: "uuid",
                    isPrimary: true,
                    isUnique: true,
                    generationStrategy: 'uuid',
                },
            ]
        }), true);
```

**Comment by ikushlianski** [comment]
To make migrations also generate `uuid` you need the following definition in your model:
```
  @PrimaryGeneratedColumn(**'uuid'**, {
    name: 'authorized_product_id',
  })
  authorizedProductId: string;
```

**Comment by maddy2894** [comment]
Is there a way to generate `uuid` for MySQL (typeorm migration)?

**Comment by colinricardo** [comment]
similarly is there a way to do something like 

```
@Primary("custom", {default: getRandomId() })
customId:string
```

or similar?
