### ISSUE TITLE
RepositoryNotFoundError

### ISSUE THREAD

**Issue by lizhen2013** [typeorm/typeorm#3774]
**Issue type:**

[ ] question
[ X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X ] ^0.2.14

**Steps to reproduce or a small repository showing the problem:**
There is a service in my demo application and I only can get the repository by use the entity's name, when I use  entity "Feedback" import to this service , the getRespository function thrown a "RepositoryNotFoundError" issue.

And the following content is my service code and entity difinition:
```typescript
import { getManager } from 'typeorm'
import { Feedback } from '../models/Feedback'
const getFeedbacks = async () => {
  console.log(Feedback.name)
  const feedbackRepo = getManager().getRepository('Feedback')
  return feedbackRepo.find()
}

const addFeedback = async (text: string) => {
  const feedbackRepo = getManager().getRepository('Feedback')
  const feedback: Feedback = new Feedback()
  feedback.text = text
  return feedbackRepo.save(feedback)
}

const removeFeedback = async (id: number) => {
  const feedbackRepo = getManager().getRepository('Feedback')
  const feedback = await feedbackRepo.findOne(id)
  return feedbackRepo.remove(feedback)
}

export default {
  getFeedbacks,
  addFeedback,
  removeFeedback
}
```
--------------------------------------
```typescript
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm'

@Entity()
export class Feedback {
  @PrimaryGeneratedColumn()
  public id: number

  @Column()
  public text: string

  @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
  public createdAt: number
}
```

**Comment by leejh3224** [comment]
You need to leave a link to your Github repository to make it reproducible so that anyone can run it and check what happens. And it is always better to format your code properly. You can see basic markdown syntax here (https://www.markdownguide.org/basic-syntax/).

**Comment by lizhen2013** [comment]
Hi I found the solution in other ticket. https://github.com/typeorm/typeorm/issues/2598
