### ISSUE TITLE
MySQL Fulltext index with ngram parser

### ISSUE THREAD

**Issue by loganyott** [typeorm/typeorm#3777]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

We're able to create full text indexes in MySQL like so:
```
@Index(["name"], { fulltext: true })
```
This generates SQL like so:
```
CREATE FULLTEXT INDEX `name` ON `table`(`name`)
```

However, MySQL allows you to also specify a parser for fulltext indexes, specifically `ngram`. This lets you perform fuzzy search.
```
CREATE FULLTEXT INDEX `name` ON `table`(`name`) WITH PARSER ngram
```

It would be great if we could have an additional index option for this. I'm thinking this could be something like
```
@Index(["name"], { fulltext: true, ngram: true })
```
or
```
@Index(["name"], { fulltext: true, parser: 'ngram'|'mecab'|null })
```

That way, we can still use generated migrations and schema sync without losing specific parsers.

**Comment by vlapo** [comment]
I think this is simple to implement. Feel free to contribute :)

**Comment by hanguihe** [comment]
When will this new feature be released?
