### ISSUE TITLE
 db connection error : TypeError: optionsArray.filter is not a function

### ISSUE THREAD

**Issue by nadavten** [typeorm/typeorm#378]
getting this error when starting app:

> db connection error : TypeError: optionsArray.filter is not a function

ormconfig.json:
```
{
    "name": "default",
    "driver":{
        "type":"sqlite",
        "database":"test"
    },
    "entities":[
        "data/models/*.js"
    ],
    "autoSchemaSync":true
}
```

stacktrace:

> "TypeError: optionsArray.filter is not a function    at ConnectionManager.<anonymous> (c:\projects\typeorm-test\node_modules\typeorm\connection\ConnectionManager.js:309:55)    at step (c:\projects\typeorm-test\node_modules\typeorm\connection\ConnectionManager.js:32:23)    at Object.f [as next] (c:\projects\typeorm-test\node_modules\typeorm\connection\ConnectionManager.js:13:53)    at __awaiter (c:\projects\typeorm-test\node_modules\typeorm\connection\ConnectionManager.js:7:71)    at __awaiter (c:\projects\typeorm-test\node_modules\typeorm\connection\ConnectionManager.js:3:12)    at ConnectionManager.createFromConfigAndConnect (c:\projects\typeorm-test\node_modules\typeorm\connection\ConnectionManager.js:303:16)    at ConnectionManager.<anonymous> (c:\projects\typeorm-test\node_modules\typeorm\connection\ConnectionManager.js:151:48)    at step (c:\projects\typeorm-test\node_modules\typeorm\connection\ConnectionManager.js:32:23)    at Object.f [as next] (c:\projects\typeorm-test\node_modules\typeorm\connection\ConnectionManager.js:13:53)    at __awaiter (c:\projects\typeorm-test\node_modules\typeorm\connection\ConnectionManager.js:7:71)"

**Comment by pleerock** [comment]
ormconfig.json should contain an array with connections. So change it to 

```json
[
{
    "name": "default",
    "driver":{
        "type":"sqlite",
        "database":"test"
    },
    "entities":[
        "data/models/*.js"
    ],
    "autoSchemaSync":true
}
]
```

And this will fix your issue.
