### ISSUE TITLE
Primary key of (left) joined entities always appears in results

### ISSUE THREAD

**Issue by nurikabe** [typeorm/typeorm#3780]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have tried hiding the primary key of left joined entities in a couple of ways:

1. Not selecting the primary key column via `.select()`
2. Hiding via @Column({primary: true, select: false})

Primary key always appears.  Example:

```
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
        "status": {
          "id": 1,
          "state": "foo",
```

Using either of the approaches above I wouldn't expect to see ` "id": 1,` in the results.

**Comment by Kononnable** [comment]
Primary columns will always be selected from db. It's the only way for ORM to know which table row we're operating on.
