### ISSUE TITLE
There is no way to exclude fields easily in mongo.

### ISSUE THREAD

**Issue by ElianCordoba** [typeorm/typeorm#3781]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

The `@Column({ select: false })` does not work in mongo, so I thought about adding (PR coming soon™) an `exclude` option in all `find` methods. Basically the current `select` uses the value 1 to the projection of the query, so the `exclude` will use the value 0.

Use case: when you want to return a user from the DB and want to filter sensible information (password, salt, credit card info, etc).

[Relevant doc](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/#return-all-but-the-excluded-fields)

**Comment by jbjhjm** [comment]
I'm experiencing the same issue with sqlite.

**Comment by nhactung** [comment]
it seems the `find({ select: ['abc'] })` works. However, it cannot exclude the `_id` field while mongo itself has the option `_id: 0` to suppress the field, [https://docs.mongodb.com/manual/reference/method/db.collection.find/#behavior](here).

**Comment by AllanPinheiroDeLima** [comment]
@nhactung how did you solve your problem?

**Comment by meirkl** [comment]
@nhactung how did you solve your problem?

**Comment by nhactung** [comment]
@AllanPinheiroDeLima 
> @nhactung how did you solve your problem?

It's been a long time. What I remember is I switched to another library.

**Comment by phil294** [comment]
```js
select: {
            _id: false,
        },
```
also does not work, unfortunately :-/

**Comment by petrind** [comment]
Still happened :(

**Comment by phosmium** [comment]
It's been 5 years and this is still unresolved, yikes

**Comment by tanish7199** [comment]
Found a way to handle this.

We can leverage Virtual Column here. (ref: [Virtual Column](https://orkhan.gitbook.io/typeorm/docs/decorator-reference#virtualcolumn)

The following could be an example:

```
  @VirtualColumn({
    query: () => `SELECT 1`,
    transformer: new ExcludeVirtualColumnTransformer(),
  })
  columnToExclude: string;
```

With the ExcludeVirtualColumnTransformer which looks like:

`import { ValueTransformer } from "typeorm";

export class ExcludeVirtualColumnTransformer implements ValueTransformer {
  to(value: any): any {
    if (value) value = 1;
    return value;
  }

  from(value: any): any {}
}
`

**Comment by raymonslickdeals** [comment]
2024 and I still cannot do a mongo 'projection' in TypeORM.  Maybe TypeORM is only designed for RDBMS
