### ISSUE TITLE
Create isolated connections for each query and close after

### ISSUE THREAD

**Issue by guilhermemiua** [typeorm/typeorm#3784]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello! Actually, I'm creating a microservice that connects to two databases. The database connection should be off. The connection should be only established on a query for example, after finishing the query, the connection should be turned off. 

In this issue https://github.com/typeorm/typeorm/issues/592, @pleerock said that there should have only one connection pool. And on each request for orm functions, they are using different connections from the pool. But does it closes these different connections for each orm function? If no, how can I resolve this problem? 

Thank you very much! :)

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
Connecting only on request can make your microservice really slow. Connecting to db takes time.

>But does it closes these different connections for each orm function? If no, how can I resolve this problem?

Connections are kept alive by pool. They are closed only after `Connection.close()` is called.

You're using mssql, so disabling pool should be possible by passing specific connection options.
https://github.com/typeorm/typeorm/blob/1521f186a46014dbac9fb6886ad8a97907a28680/src/driver/sqlserver/SqlServerConnectionOptions.ts#L39-L51

**Comment by sslash** [comment]
@Kononnable  isn't this what you would do in a serverless (e.g aws lambda) setup though?

**Comment by JannikZed** [comment]
Asking myself the same question now for AWS lambda (next.js API route). What is the best practice here?

**Comment by ryanmargono** [comment]
@sslash @JannikZed did you ever find this answer? I'm trying to do the same thing (Lambda).

**Comment by JannikZed** [comment]
@sslash I started using Prisma - they offer more for the serverless world.
