### ISSUE TITLE
Question: Is using getters only for properties possible in typeorm?

### ISSUE THREAD

**Issue by marrionluaka** [typeorm/typeorm#3789]
**Issue type:**
I'm trying to build a demo app while following a DDD approach but i'm having some issues.
When I try to save an entity with the code below using 'connection.manager.save()', I get the following error:

> UnhandledPromiseRejectionWarning: TypeError: Cannot set property Name of #<CustomerEntity> which has only a getter at ColumnMetadata.setEntityValue

Is typeorm using setters in the background? is there a way to write the above code while avoiding this error. Great lib by the way!

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

 ```
 @Entity("customer")
  export default class CustomerEntity {
      private _name: string;

      @Column({ 
        type: String, 
        name: "name"
       })
       public get Name(): string {
          return this._name;
       }

      private constructor(name?: string){
           if(!!name) this._name = name;
      }

      public static create(name: string): CustomerEntity {
           if(!name) throw "error name is required...";
           return new CustomerEntity(name);
      }
  }
```
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by SamKhachatryan** [comment]
No as I know it's don't possible.
