### ISSUE TITLE
Query without join can't get the foreign key.

### ISSUE THREAD

**Issue by miaolq** [typeorm/typeorm#379]
It seems when i use find or QueryBuilder without join, i can't get the foreign key .
SQL as follows:
```
SELECT `photo`.`name` AS `photo_name`,`photo`.`clinicId` AS `photo_clinicId` FROM `photo` `photo`
``` 
ClinicId is a foreign key,i can't get it.
How can i get a foreign key without join.
thank you.

**Comment by valVk** [comment]
I do not know whether this is a bug or not. but I'm doing something like that in my models to achieve the same thing what you are trying to get.

```typescript
...
    @RelationId((profile: UserProfile) => profile.gender)
    @Column('int', { name: 'gender_id', nullable: true })
    @Index()
    genderId: number;

    @ManyToOne(type => Gender, gender => gender.profiles)
    @JoinColumn({ name: 'gender_id', referencedColumnName: 'id' })
    gender: Gender;

...
```

In that way my model always has a parameter genderId with id.

**Comment by pleerock** [comment]
@valVk your approach is almost correct. What you should do is:

```ts
    @Column('int', { name: 'gender_id', nullable: true })
    genderId: number;

    @ManyToOne(type => Gender, gender => gender.profiles)
    @JoinColumn({ name: 'gender_id', referencedColumnName: 'id' }) // you can omit referencedColumnName
    gender: Gender;
```

**Comment by miaolq** [comment]
I see. Thank you all.     ^_^

**Comment by valVk** [comment]
@pleerock Ehhmm, than what is this doing `@RelationId((profile: UserProfile) => profile.gender)`? )
I saw that solution somewhere in the deep of issues, I did not find a notices what is RelationId() itself, so I've made a decision to use it like I showed above, because it helps me to get ids of the relations.
Thanks.

**Comment by pleerock** [comment]
you can do it the way I described without `@RelationId`. `@RelationId` can also do it other way for, however right better if you do it the way I described.

**Comment by valVk** [comment]
Thanks.
