### ISSUE TITLE
WITH Clause in the Query Builder

### ISSUE THREAD

**Issue by Neo-Zhixing** [typeorm/typeorm#3794]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is it possible to create queries with "WITH Clause" using the query builder?

Like this: 
```sql
WITH regional_sales AS (...subquery... )
SELECT region,
       product,
       SUM(quantity) AS product_units,
       SUM(amount) AS product_sales
FROM regional_sales 
```

**Comment by Kononnable** [comment]
#1116

**Comment by Prafull1Kumar** [comment]
I have the same problem.
