### ISSUE TITLE
ColumnTypeUndefinedError with create-react-app and sql.js

### ISSUE THREAD

**Issue by bearbytes** [typeorm/typeorm#3795]
**Issue type:**
[x] bug report

**Database system/driver:**
[x] `sqljs`

**TypeORM version:**
[x] `0.2.14`

**Steps to reproduce or a small repository showing the problem:**

The problem occurs in a minimal React app:
```
npx create-react-app typeorm-test
cd typeorm-test
npm i typeorm reflect-metadata sql.js
npm i -D typescript @types/node
``` 

tsconfig.json:
```json
{
  "compilerOptions": {
    "outDir": "dist",
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "noEmit": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "jsx": "preserve",
    "strict": true,
    "noImplicitAny": true,
    "allowJs": false,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "isolatedModules": true
  },
  "include": [
    "src"
  ]
}
```

index.ts:
```ts
import "reflect-metadata";

import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  createConnection
} from "typeorm";

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  name!: string;
}

createConnection({
  type: "sqljs",

  location: "sqljs",
  autoSave: true,

  entities: [User],

  logging: "all"
});
```

When run via `npm start`, I get the following error:
**ColumnTypeUndefinedError: Column type for User#name is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.**

Note that emitDecoratorMetadata is set to true and reflect-metadata is imported as the first line of the index file.

The problem also exists when setting `"strict": "false"` in tsconfig.json

**Comment by vlapo** [comment]
Please provide repository with minimal reproduction of this problem. It is hard to help you if we do not know all circumstances and what `npm start` do.

**Comment by Kononnable** [comment]
1) `"noEmit": true,` looks kinda weird in tsconfig
2) `"module":` should be set to `"commonjs"`, not `esnext`

Code runs after those changes - I've tested it.

**Comment by bearbytes** [comment]
These settings are automatically enforced by [create-react-app](https://github.com/facebook/create-react-app), so these two tools seem to be incompatible with each other right now.

**Comment by Kononnable** [comment]
If you change module resolution to comonjs does react part work well? I think it should, but it's been some time since I read about how esnext modules should work in node.

Typeorm is not yet esnext modules compatible, but I think we should add it to our roadmap.

**Comment by gruckion** [comment]
> If you change module resolution to comonjs does react part work well? I think it should, but it's been some time since I read about how esnext modules should work in node.
> 
> Typeorm is not yet esnext modules compatible, but I think we should add it to our roadmap.

Create-react-app automatically changes it back when it runs.

**Comment by andrerpena** [comment]
I'm currently trying to run TypeORM in `jest` integration tests in a Create React App app.
Since tests are run with `react-scripts`, I cannot control the `tsconfig.json` file and the default one is enforced to be `esnext` and not `commonjs`.
