### ISSUE TITLE
Entity Import order matters?

### ISSUE THREAD

**Issue by Mindar** [typeorm/typeorm#3796]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[x] documentation issue

My application crashes depending on import order of my Entities. Error is: ```UnhandledPromiseRejectionWarning: Error: Referenced column userParty was not found in entity User```. I'm not sure if this is a bug or if it is "working as intended". If it is working as intended, the reason should be clearly explained in the documentation. Also, I'd be interested to learn and understand why it behaves that way, so if you have the time and motivation to explain it I'd be incredibly thankful. I believe this issue might be related to #3788 

**Database system/driver:**

I only tested MariaDB so far

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**index.ts** If Group and User imports switch position, it works.
```
import {createConnection} from "typeorm";

import { Party } from "./Party";
import { User } from "./User";
import { Group } from "./Group";



async function start(){
	const connection = await createConnection({
		type: "mysql",
		host: "localhost",
		port: 3306,
		username: "root",
		password: "123",
		database: "testdb",
		synchronize: true,
		entities: [
			Party,
			User,
			Group
		],
		logging: true
	});
}

start();
```

**Party.ts**
```
import {Entity, BaseEntity, Column, PrimaryGeneratedColumn} from "typeorm";

@Entity()
export class Party extends BaseEntity {

	@PrimaryGeneratedColumn()
    id!: number;

	@Column({type: "varchar"})
	type!: string;
}
```

**Group.ts**
```import {Entity, BaseEntity, Column, ManyToMany, OneToOne, JoinColumn, JoinTable} from "typeorm";

import { Party } from "./Party";
import { User } from "./User";


@Entity()
export class Group extends BaseEntity {
	@JoinColumn()
	@OneToOne(type => Party, {primary: true})
	groupParty!: Party;
	
	@Column()
	username!: string;

	@ManyToMany(type => User)
	@JoinTable({
		name: "user_group_relation",
		joinColumn: {
			name: "group",
			referencedColumnName: "groupParty"
		},
		inverseJoinColumn: {
			name: "user",
			referencedColumnName: "userParty"
		}
	})
	members!: User[];
}
```

**User.ts**
```
import {Entity, BaseEntity, Column, ManyToMany, OneToOne, JoinColumn} from "typeorm";

import { Party } from "./Party";
import { Group } from "./Group";

@Entity()
export class User extends BaseEntity {
	@JoinColumn()
	@OneToOne(type => Party, {primary: true})
	userParty!: Party;
	
	@Column()
	username!: string;

	@ManyToMany(type => Group)
	groups!: Group[];
}
```

**Comment by oeddyo** [comment]
very similar to my problem

Can you paste your tsconfig?

**Comment by Kononnable** [comment]
Closing in favor of #3788.
