### ISSUE TITLE
Migrations don't work with dynamic config

### ISSUE THREAD

**Issue by WeekendMan** [typeorm/typeorm#3797]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] `0.x.x` (0.2.8)

Migration "up" method doesn't save anything to table.

App based on Express / Typescript.

No ormconfig file. Config defines dynamically from given ENV variables and static values defined in code. All given values are valid and checked (method's params), all migration files exist in build, paths are correct, migration called by app. Method that creates config returns this:
```ts
    {
      type: 'postgres',
      host,
      port,
      username,
      password,
      database,
      synchronize: true,
      logging: false,
      migrationsRun: true,
      cli: { migrationsDir: `${dirname}/migrations` },
      entities: [ `${dirname}/entities/*.entity.js` ],
      migrations: [ `${dirname}/migrations/*.migration.js` ],
      subscribers: [ `${dirname}/subscribers/*.subscriber.js` ]
    } as PostgresConnectionOptions
```
Command from terminal:
`TYPEORM_MIGRATIONS=dist/migrations/*.migration.js TYPEORM_CONNECTION=postgres TYPEORM_DATABASE=dbname TYPEORM_USERNAME=dbusername TYPEORM_PASSWORD=dbpassword npm start`

Migration's "up" method:
```ts
  public async up(): Promise<void> {
    await getConnection()
      .createQueryBuilder()
      .insert()
      .into(CountryEntity)
      .values([ { id: 'someID', name: 'Name1', iso: 'N1' } ])
      .execute();
  }
```
Migration's method has been called. Tried to use another syntax that I've found in example like
```ts
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.connection.getRepository(CountryEntity).save(new CountryEntity({
      id: 'someID',
      name: 'some name',
      iso: 'some ISO'
    }));
  }
```
Nothing changes, table is empty.

Entity:
```ts
@Entity({ name: 'country' })
export class CountryEntity {
  @PrimaryColumn({ unique: true, readonly: true, nullable: false, length: COUNTRY_ENTITY_LIMITS.get('id') })
  public readonly id: string;

  @Column({ readonly: true, nullable: false, length: COUNTRY_ENTITY_LIMITS.get('name') })
  public readonly name: string;

  @Column({ name: 'iso', readonly: true, nullable: false, length: COUNTRY_ENTITY_LIMITS.get('iso') })
  public readonly iso: string;

  @OneToMany(() => UserEntity, (user: UserEntity) => user.country)
  public readonly citizens: UserEntity[];

  @OneToMany(() => UserEntity, (user: UserEntity) => user.location)
  public readonly locatedIn: UserEntity[];

  public constructor(params: CountryEntityInterface = {} as CountryEntityInterface) {
    this.id = params.id;
    this.name = params.name;
    this.iso = params.iso;
    this.citizens = params.citizens;
    this.locatedIn = params.locatedIn;
  }
}
```

Migration table wiped every time when I start app (manually) to check the result.
Important - outside of migration it works perfectly (in controllers etc)

What am I doing wrong?

**Comment by Kononnable** [comment]
Can you enable logging? We would see then if query was send to a db server, if transaction was rolled back etc.

**Comment by Kononnable** [comment]
Closing as no response from the author.
