### ISSUE TITLE
default option in column does not work in Mongo

### ISSUE THREAD

**Issue by ElianCordoba** [typeorm/typeorm#3799]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
export class User {

  @ObjectIdColumn()
  _id: ObjectID;

  @Index({ unique: true }) 
  @Column()
  email: string;

  @Column({ default: true })
  active: boolean;

  @Column()
  salt: string;

}
```
I report this because, for example, `@Unique` do work properly but `@Column({ select: true })` (#3781) does not.

**Comment by kashyaprahul94** [comment]
For me, even @Unique is not working :(

**Comment by ElianCordoba** [comment]
@kashyaprahul94  If you want to have a column/field that is unique you have to use `@Index({ unique: true })`

**Comment by kashyaprahul94** [comment]
> @kashyaprahul94 If you want to have a column/field that is unique you have to use `@Index({ unique: true })`

Yes, i tried with '@Index({ unique: true })' only, but it did not work for me, it was accepting duplicate values.
My bad, i should have been more verbose.

**Comment by kashyaprahul94** [comment]
> > @kashyaprahul94 If you want to have a column/field that is unique you have to use `@Index({ unique: true })`
> 
> Yes, i tried with '@index({ unique: true })' only, but it did not work for me, it was accepting duplicate values.
> My bad, i should have been more verbose.

I just realized it was @Index. Though @Column({ unique: true }) accepts duplicate values too for me :(

**Comment by rustamwin** [comment]
@kashyaprahul94 could you check indexes from mongodb database?

**Comment by Nastaliss** [comment]
I am having the same problem.
I have found an temporary solution though:
```
    @Column()
    @IsArray()
    @IsNotEmpty()
    comments: Array<ObjectID> = [];
```
It seems to work but an implementation for the default option would be much better :)

**Comment by hominhhieu7** [comment]
Try this:
 @AfterInsert()
    async afterInsert() {
  this.active = true;
 }

**Comment by mehmetnyarar** [comment]
@hominhhieu7 didn’t work for me

**Comment by alberluc** [comment]
I solved this issue with this :
`    
@Field()
@Column()
countClient: number = 0
`

**Comment by alberluc** [comment]
I solved this issue with this 
```    
    @Field()
    @Column()
    countClient: number = 0
```

**Comment by LisaSeltenheim** [comment]
> I solved this issue with this
> 
> ```
>     @Column()
>     countClient: number = 0
> ```
> 
> The value is not saved in database but it's passed in find queries results.

Thank you, worked for me. Values are saved in db!

**Comment by burlakko** [comment]
So what about this issue? It's closed without any notice and at least for me the bug is still there

**Comment by imnotjames** [comment]
> So what about this issue? It's closed without any notice and at least for me the bug is still there

The author closed it.  You can open another with more information.
