### ISSUE TITLE
ConnectionOptions.entityDirectories not detecting files

### ISSUE THREAD

**Issue by paistipoikka** [typeorm/typeorm#38]
Hi, I am using the following ConnectionOptions object when setting up my connection. 

```
ConnectionOptions = {
            driver: {
                type: 'postgres', // specify driver type here.
                host: this.dbHost,
                port: this.dbPort,
                username: this.dbUserName,
                password: this.dbPassword,
                database: this.dbName
            },
            autoSchemaCreate: true,
            logging: loggerOptions,
            entityDirectories: ['../model/**/{*.js}']
        };
```

It is not detecting the files in the `entityDirectories` property. I am just looking for the .js files. Am I doing something wrong?

JT

**Comment by pleerock** [comment]
You wrongly specify `entityDirectories`, each directory should have __dirname appended:

`entityDirectories: [__dirname + '/../model/**/{*.js}']`

**Comment by paistipoikka** [comment]
Yes, I have tried that however it still appears that the files are not detected.

**Comment by pleerock** [comment]
then try to debug, it totally should work, maybe you specify a wrong path or something

**Comment by pleerock** [comment]
btw try `entityDirectories: [__dirname + '/../model/**/*.js']` and `entityDirectories: [__dirname + '/model/**/*.js']` - maybe one of them will work for you

**Comment by paistipoikka** [comment]
`entityDirectories: [__dirname + '/../model/**/*.js']` 

Removing the curly braces works. Thank you.

JT
