### ISSUE TITLE
Simple-json should use "nvarchar" to be in line with current JSON support in SQL server.

### ISSUE THREAD

**Issue by svegalopez** [typeorm/typeorm#3804]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have a question regarding support for [JSON in SQL SERVER](https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-2017) (mssql).

It would be nice to have typeORM support for querying based on properties of the JSON column like you can see in the link above. However, I understand this will take a lot of work so it probably wont happen in the near future ? 

In the meantime, we have a work around that involves using the Raw operator to do such queries.
But there is a problem that I think can be solved easily (correct me if I  am wrong). When using the type "simple-json" this is translated to "ntext" in mssql. This is problematic because all those JSON operations that you can see in the link above operate on "nvarchar".  So there is a need to cast from ntext to nvarchar everytime. If I create a column of type "simple-json" and manually set it to nvarchar in the database then everytime I use the "migrate:generate" command, it tries to change it to ntext.

Do you think changing simple-json to nvarchar in mssql is a feasible change ?

**Comment by pleerock** [comment]
> However, I understand this will take a lot of work so it probably wont happen in the near future ?

Correct.

> Do you think changing simple-json to nvarchar in mssql is a feasible change ?

It became `ntext` because other drivers also have `text` data type. And they have a text data type because the problem is that varchar is too way short and in practice it won't fit most of json data you are going to store in it. But it looks like in mssql we can use NVARCHAR(MAX). 

I think we can change it to `NVARCHAR(MAX)` but unfortunately the change is breaking and we can't do it right now.

Solution for now is to use nvarchar type instead of simple-json and use transformers or event hooks to JSON.parse and JSON.stingify data before save/after load.

**Comment by svegalopez** [comment]
> Solution for now is to use nvarchar type instead of simple-json and use transformers or event hooks to JSON.parse and JSON.stingify data before save/after load

I tried that. The problem is that whenever I add the transformations the Raw operators stops working.
Below are the logs that I got

Query:

```javascript 
manager.findOne(Contact, { where:{ id: newContact.id, approvals: Raw( alias => `JSON_VALUE( ${alias}, '$.active' )='true'`) }});
```

Transformations OFF (looks GOOD): 
```
"Contact"."id" = @0 AND JSON_VALUE( "Contact"."approvals", '$.active' )='true'
```

Transformation ON:
```
...AND "Contact"."approvals" = @1  -- PARAMETERS: [3877,"{\"_type\":\"raw\",\"_useParameter\":false,\"_multipleParameters\":false}"]
```

When the transformation is on, the query is not constructed properly. Look at param @1 above.

**Comment by pleerock** [comment]
Can you try to use [even listeners](https://typeorm.io/#/listeners-and-subscribers) instead of transformers then?

**Comment by svegalopez** [comment]
I will give it a try.

**Comment by svegalopez** [comment]
> Can you try to use even listeners instead of transformers then?

If anybody else comes across this issue, event listeners work for now: 
```javascript
@AfterLoad()
parse() {
    this.state = JSON.parse(this.state as string)
}

@BeforeInsert()
@BeforeUpdate()
stringify() {
    this.state = (JSON.stringify(this.state) as ContactState)
}
```

Just be aware that these listeners will trigger on ```manager.save()```  and wont trigger on ```manager.update()```. So you need to manually parse when using update method.

**Comment by Kononnable** [comment]
@pleerock 
>I think we can change it to NVARCHAR(MAX) but unfortunately the change is breaking and we can't do it right now.

Should we do that in 0.3.0 or mark it for 0.4.0?

**Comment by ImBoop** [comment]
Hmm, why was this closed as completed despite simple-json still using ntext?
