### ISSUE TITLE
How to update associated schemas at the same time when I update the main schema

### ISSUE THREAD

**Issue by linzelong95** [typeorm/typeorm#3807]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

As shown in the figure, the main schema is "Photo" while the associated schemas are Album, Author and "PhotoMetadata". My goal is to update the main schema called Photo and the associated schemas would be automatically updated. But I failed. It showed that the column named "metadata" and the column named "albums" were not found. Could you please help me deal with this problem or show me the example? Thank you!
![relationsUpdataError](https://user-images.githubusercontent.com/40480550/54173622-afc5e300-44bd-11e9-9636-3c27b93affff.png)
![schema](https://user-images.githubusercontent.com/40480550/54173791-44c8dc00-44be-11e9-90ca-836703691c7d.png)

**Comment by vlapo** [comment]
Hey @linzelong95 you have to use `save` method. `update` method perform just simple `UPDATE` statement in DB and do not check any relations defined in typeorm.

https://stackoverflow.com/questions/54904349/typeorm-one-to-many-entitycolumnnotfound-no-entity-column-context-physicalp

**Comment by linzelong95** [comment]
@vlapo 
Thank you for your answer. And I am sorry to bother you again.  This time, I used "save()" to update the information with complex relations, but i failed again. It seemed to execute "insert" instead of "update". What was wrong with my code? How can I solve it? Look forward to your reply.Thank you.
![err](https://user-images.githubusercontent.com/40480550/54333171-6cee4180-465c-11e9-88a6-6f644f0b9078.png)

**Comment by vlapo** [comment]
I think this is not a problem of inserting instead of updating. Enable logging and check constraint referenced in error message (as `REL_...`). This is related to your `@OneToOne` relation.

**Comment by Kononnable** [comment]
If you want to update an entity why don't you fetch it from db before? You created it from scratch in your code.

**Comment by rmainseas** [comment]
Just to add my two cents here. I'm seeing this issue too when I try to call `EntityManager::save` with relations. So say for example I do this:

```typescript
manager.save(users.map((user): User => {
    const u = new User();
    const newPhoto = new Photo();
    newPhoto.name = 'My Photo'
    u.photos = [newPhoto];
    return u;
  })
);
```

My `User` parent entity is saved, but the user's `Photo`s aren't.
