### ISSUE TITLE
Is it possible to group by using QueryBuilder when column name is camelCase ?

### ISSUE THREAD

**Issue by talantbekov123** [typeorm/typeorm#3810]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

## Is it possible to group by using QueryBuilder when column name is camelCase ?
Here is a snippet of the code. I get the following error `QueryFailedError: column "companyid" does not exist`

```bash
const companies: any = await getRepository(Coupon)
   .createQueryBuilder('coupon')
   .select('companyId')
   .groupBy('companyId')
   .getRawMany();

**Comment by vlapo** [comment]
Please provide definition of your `Coupon` entity.

**Comment by talantbekov123** [comment]
This is a snippet of `Coupon` entity.

```bash
export class Coupon extends BasicEntity {

  @ApiModelProperty()
  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    nullable: true,
  })
  companyId: number;

  @Index()
  @ApiModelProperty()
  @ManyToOne(type => Company, company => company.coupons, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  company: Company;

**Comment by vlapo** [comment]
You have to define alias:
```typescript
await connection.getRepository(Coupon)
            .createQueryBuilder('coupon')
            .select('coupon.companyId')
            .groupBy('coupon.companyId')
            .getRawMany();
```

**Comment by talantbekov123** [comment]
Thanks, issue solved!
