### ISSUE TITLE
ORA-00923 Error

### ISSUE THREAD

**Issue by geabenitez** [typeorm/typeorm#3812]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.15-rc.2` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am connecting to a Oracle database, and I Get the following error
Error: QueryFailedError: ORA-00923: FROM keyword not found where expected

And the query that is supposed to be wrong is this one
https://github.com/typeorm/typeorm/blob/4916a645aa41331f071f57c3dc7dfe805b3309de/src/driver/oracle/OracleQueryRunner.ts#L1107-L1113

Sorry, i'm not as good as I expect with Oracle and queries, that's why i'm reporting this. 

btw, DB version is 10.2g

Best regards.

**Comment by Kononnable** [comment]
OracleDb is supported by typoerm on versions 12+ (#2002)
On older versions you may get errors.
