### ISSUE TITLE
typeorm does not find its configuration file in a monorepo

### ISSUE THREAD

**Issue by aaronjensen** [typeorm/typeorm#3813]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] all
[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

I have a monorepo like this:

```
package.json
server/package.json
...
```

I'm using typeorm in the `server/` package.

If I place the ormconfig.js in the `server/` directory, it is not found when I do a `createConnection`.

If I place it in the project root, it is found.

Am I doing something wrong, or is there a way to ensure that typeorm looks in the right place, or is this a bug?

Thanks!

**Comment by vlapo** [comment]
Please provide more information, repository with minimal reproduction could be the best.

**Comment by aaronjensen** [comment]
@vlapo sorry it took me so long, but here you go: https://github.com/aaronjensen/typeorm-monorepo-repro

**Comment by vlapo** [comment]
We have an issue for yarn workspace problem https://github.com/typeorm/typeorm/issues/2805. Feel free to discuss or come with some solution there. Close in favour mentioned issue.

**Comment by aaronjensen** [comment]
Ugh, there was a problem with the PR template. I just realized that all of the original detail I put in did not show up.
