### ISSUE TITLE
Where is ObjectID constructor?

### ISSUE THREAD

**Issue by hash** [typeorm/typeorm#3815]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.13 and 0.2.15-rc.2`

**Steps to reproduce or a small repository showing the problem:**

```ts
import { getMongoRepository, MongoRepository } from 'typeorm';
import { ObjectID } from 'typeorm/driver/mongodb/typings';
// or 
import { getMongoRepository, MongoRepository, ObjectID } from 'typeorm';
// it does not matter
import { Transaction } from './entity/transaction'; // also does not matter

const repo: MongoRepository<Transaction> = getMongoRepository(Transaction);
// on
const tran: Transaction = await repo.findOne(new ObjectID('hexString'));
// result
// TypeError: typings_1.ObjectID is not a constructor
```

**Comment by etherealyn** [comment]
Try

```typescript
import { ObjectID } from 'mongodb';
```

**Comment by rustamwin** [comment]
You can get expected result using `hexString` instead of ObjectID.

**Comment by hash** [comment]
@rustamwin Only if _id is of type ObjectId, if _id is string it fails to find. 

@etherealyn ```Argument of type 'ObjectId' is not assignable to parameter of type 'string | number | Date | ObjectID | FindOneOptions<Transaction> | Partial<Transaction>'.
  Property 'generate' is missing in type 'ObjectId' but required in type 'ObjectID'.ts(2345)```

So it looks like the possibility to find objects with _id set to string is not possible, but one can set _id to string. 

@rustamwin Your answer works for me, thank you.

**Comment by anlauren** [comment]
It looks like there's a problem because the `ObjectId` type is not compatible with the current mongodb definition but the actual implementation of the class is not re-exported, so we can't use that definition either :/

**Comment by lucasraziel** [comment]
Is this issue solved?

**Comment by imnotjames** [comment]
> It looks like there's a problem because the `ObjectId` type is not compatible with the current mongodb definition but the actual implementation of the class is not re-exported, so we can't use that definition either :/

There's no definition in typeorm, just a type.

**Comment by gentunian** [comment]
> Try
> 
> ```ts
> import { ObjectID } from 'mongodb';
> ```

this won't work. There's no `ObjectID` in mongodb (4.1.0) and it won't work neither with `ObjectId`:

```
import { ObjectId } from 'mongodb';

myRepository.findOne(new ObjectId(idString));
// will throw: TypeError: Right-hand side of 'instanceof' is not an object
```

If we have declared an entity with:

```
  @ObjectIdColumn()
  id: ObjectID;
```

how we should fetch an item?

**Comment by gentunian** [comment]
I think this is related, mongodb version 4 is not yet compliant: https://github.com/typeorm/typeorm/issues/7086

**Comment by imnotjames** [comment]
You get a warning when you attempt to use mongo 4 with typeorm (or at least you should?)

We only support node-mongo 3.x at this time.
