### ISSUE TITLE
Select certain tables from a db

### ISSUE THREAD

**Issue by vicenteserra** [typeorm/typeorm#3816]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

hi, I have a lot of tables in my mssql server db, as much as 3140, some of them with more than 250 fields.
There is any possibility to select only certain tables?
Thank you. 

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
Do not understand your question. Could you please describe more whats a problem? Typeorm works only with defined entities and related tables. So just define entities you need and disable synchronization.

**Comment by vicenteserra** [comment]
Sorry, the issue is for the project typeorm-model-generator.
