### ISSUE TITLE
Can typeorm support connections to both mysql and oracle simultaneously?

### ISSUE THREAD

**Issue by cnneel** [typeorm/typeorm#3818]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[x ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

 I am trying to copy a table in MySQL to a table in Oracle.  Due to differences in the column types, once I open a connection for MySQL, I get errors when I try to open a connection to Oracle.   The only work around so far that I have found is to have two separate copies of the entities, but I would like to avoid this.   In the entities, I import in the column types in order to have flexibility between MySQL and Oracle, but it seems once a connection is made, the column types are fixed (thus I have separate copies as a work around).   Is there another way to accomplish this?  Thanks.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
You could use entity schemas instead of column decorators to define entities. This way you should be able to use same typeorm classes for different specific database types(which are compatible with each others).
