### ISSUE TITLE
camelCaseColumns doesn't work

### ISSUE THREAD

**Issue by falconwbb** [typeorm/typeorm#3822]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x` (5.2.2)

**Steps to reproduce or a small repository showing the problem:**

I want my DB columns with first letter uppercase, camelCaseColumns seems the right setting, refer to following comments, but why i still get camelCase when set it to true ?

/**
         * A boolean, controlling whether the column names returned will have the first letter converted to lower case
         * (true) or not. This value is ignored if you provide a columnNameReplacer. (default: false).
         */
        readonly camelCaseColumns?: boolean;
```
export const DATABASE_CONFIG: ConnectionOptions = {
    database: utils.toString(database),
    entities: [
        utils.getPath(__dirname, '../core/common/entities/**.entity{.ts,.js}'),
        utils.getPath(__dirname, '../modules/**/**.entity{.ts,.js}')
    ],
    host: utils.toString(host),
    logger: new DatabaseLogger(logging),
    logging,
    password: utils.toString(password),
    port: utils.toNumber(port),
    synchronize: true,
    type: 'mssql',
    options: {
        camelCaseColumns: true
    },
    username: utils.toString(username)
};
```

**Comment by Kononnable** [comment]
>I want my DB columns with first letter uppercase

What do you mean by that? You're using migrations/schema sync and wants generated columns to be camelCased?  I think you're looking for naming strategy: https://github.com/typeorm/typeorm/blob/master/docs/naming-strategy.md

**Comment by falconwbb** [comment]
> > I want my DB columns with first letter uppercase
> 
> What do you mean by that? You're using migrations/schema sync and wants generated columns to be camelCased? I think you're looking for naming strategy: https://github.com/typeorm/typeorm/blob/master/docs/naming-strategy.md

It seems exactly what I want. I'll try when i get a chance. @Kononnable, thank you so much!

**Comment by falconwbb** [comment]
The solution works. Paste my code here:

import { pascalCase, titleCase } from 'change-case';
import { DefaultNamingStrategy } from 'typeorm';

export class NamingStrategy extends DefaultNamingStrategy {
    public columnName(
        propertyName: string,
        customName: string,
        embeddedPrefixes: string[]
    ): string {
        // todo: simplify
        if (embeddedPrefixes.length) {
            return (
                pascalCase(embeddedPrefixes.join('_')) +
                (customName ? titleCase(customName) : titleCase(propertyName))
            );
        }

        return customName ? customName : pascalCase(propertyName);
    }
}
