### ISSUE TITLE
merge master to next please.

### ISSUE THREAD

**Issue by Jimmysh** [typeorm/typeorm#3826]
**Issue type:**

[ ] question
[ ] bug report
[ x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ x ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
yeah I know, I know... Really want to do that too.

**Comment by pleerock** [comment]
Merged

**Comment by s97712** [comment]
@next can work on production environment?

**Comment by Jimmysh** [comment]
@pleerock need merge. 😃
