### ISSUE TITLE
class-validator with separated entitySchema

### ISSUE THREAD

**Issue by chiaraperino** [typeorm/typeorm#3833]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have insert the class-validator package inside my react-native app.
I have declared my EntitySchema in separated file, like the example:

file utilities.schema.js
```
import { EntitySchema } from 'typeorm/browser';
import { IsNotEmpty } from 'class-validator';

import { Utilities } from 'db/models';

export default new EntitySchema({
  tableName: 'utilities',
  target: Utilities,
  columns: {
    @IsNotEmpty({ message: 'target_not_null' })
    target: { type: 'varchar', length: 32, primary: true },
    // @IsNotEmpty({ message: 'field_not_null' })
    field: { type: 'varchar', length: 32, primary: true },
    value: { type: 'varchar', length: 64, nullable: true },
  },
});
```

file Utilities (models)
```
import { BaseEntity } from 'typeorm/browser';

export class Utilities extends BaseEntity {}
```

file vat.schema.js
```
import { EntitySchema } from 'typeorm/browser';
import { Min, IsNotEmpty } from 'class-validator';

import { Vat } from 'db/models';

export default new EntitySchema({
  tableName: 'vat',
  target: Vat,
  columns: {
    id: { type: 'integer', primary: true, generated: true },
    @IsNotEmpty({ message: 'name_not_null' })
    name: { type: 'varchar', length: 32 },
    @Min(0, { message: 'rate_gt_0' })
    rate: { type: 'integer' },
    notes: { type: 'text', nullable: true },
    extraColumns: ['date'],
  },
  checks: [
    { name: 'rate_gt_0', expression: '"rate" > 0' },
  ],
  uniques: [
    { columns: ['name'] },
  ],
});
```

When I create a vat element, the error is:
```
Array [
  ValidationError {
    "children": Array [],
     "constraints": Object {
       "isNotEmpty": "target_not_null",
     },
     "property": "target",
     "target": Vat {
       "name": "prova",
       "rate": 2,
       "serialize": [Function anonymous],
     },
     "value": undefined,
   },
 ]
```

but "target_not_null" is the utilities error validation and not vat error validation.
Why?

Thanks

**Comment by Kononnable** [comment]
We don't know exactly what are you doing, we don't see how validator is called etc.
For me it looks like wrong use of class-validator or error in theirs codebase. I didn't use that library but should the decorators be declared on EntitySchema or directly on  entity model.

**Comment by chiaraperino** [comment]
I have followed the guide in typeorm (https://typeorm.io/#/validation) but I think that is not compatible with EntitySchema but only directly in entity model.

I have resolved without decorators (https://github.com/typestack/class-validator#defining-validation-schema-without-decorators) and it works.

Thanks for your help.
