### ISSUE TITLE
SQLITE_ERROR: "AUTOINCREMENT": syntax error

### ISSUE THREAD

**Issue by Knaackee** [typeorm/typeorm#3834]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.15` (or put your version here)

After updating from 0.2.14 to 0.2.15 i get the following error using PrimaryColumn and PrimaryGeneratedColumn with SQLite3 

> SQLITE_ERROR: "AUTOINCREMENT": syntax error

**Comment by Kononnable** [comment]
I'm not reproducing the issue. Could you provide failing test/reproduction repo?

**Comment by Knaackee** [comment]
Ok, I will do that asap.

**Comment by imnotjames** [comment]
No test case, closing.

**Comment by sumeet-bansal** [comment]
@imnotjames I'm running into the same issue. If you pull this commit ([`15579df` (acmucsd/membership-portal#134)](https://github.com/acmucsd/membership-portal/pull/134/commits/15579df0a6f69b7d07d351dfd91ae76a9ba703f3) and try `npm run test` it fails with that exact error.

**Comment by sumeet-bansal** [comment]
@Knaackee curious how/if you were able to get it to work?

**Comment by sumeet-bansal** [comment]
@imnotjames I think it's because the auto-incrementing key is not the primary key. Is there a way to still make the auto-increment work through the ORM somehow? Or maybe disable it while testing?

**Comment by imnotjames** [comment]
SQLite can't do non-PK auto incrementing. Can it?
