### ISSUE TITLE
Disable Cache Programmatically

### ISSUE THREAD

**Issue by thellimist** [typeorm/typeorm#3836]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

---

Is there a way to disable cache for integration tests?

**Comment by Kononnable** [comment]
Cache is enabled in connections options - you can just modify your connectionOptions if running under integration tests. You can also disable cache per specific query if you don't like to disable it completely(you're using same connection in multiple tests).
