### ISSUE TITLE
startSession and startTransaction

### ISSUE THREAD

**Issue by kraikov** [typeorm/typeorm#3839]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hey guys, you are doing a great job with TypeORM! 

I know that transactions are not yet supported, but I need to use this feature in my application and I still want to use TypeORM because it's just awesome.

Can you give me some guidance how can I do that?

I need have access to ```MongoClient``` and use ```startSession``` (ref: http://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html#startSession).

This will give me ```ClientSession``` object and after that I can use ```startTransaction``` and ```commitTransaction``` (ref: http://mongodb.github.io/node-mongodb-native/3.1/api/ClientSession.html#startTransaction)

I have a hard time to merge the ```createConnection``` and the one used with MongoClient. Any help will be much appreciated. Thanks in advance!

**Comment by imnotjames** [comment]
Fetch the client off the driver & call the methods on that.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by juansb827** [comment]
Obtaining the underlying client was a bit tricky.
This is what worked for me.

```
  const client = (this.repository.manager.connection.driver as MongoDriver)
      .queryRunner.databaseConnection;
  const session = client.startSession();   
```

**Comment by imnotjames** [comment]
Yes - unfortunately, the way the mongo driver was implemented really breaks the abstraction at this point in time.  We'll hopefully be correcting that in the near future..

**Comment by StagnantIce** [comment]
If I use update, I cant use session, if I use updateOne - i need use _id insetad id for findOne.
Please, provide normal updateOne, Thank you

**Comment by fire-cracker** [comment]
This worked for me!

```
    const queryRunner = this.typeOrmDataSource.mongoManager.mongoQueryRunner;
    const mongoClient: MongoClient = queryRunner.databaseConnection;
    const session: ClientSession = mongoClient.startSession();
 ```
