### ISSUE TITLE
Chinese documentation

### ISSUE THREAD

**Issue by jyang0110** [typeorm/typeorm#3844]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

I noticed that chinese documentation isnt really complete yet. Since this is a very interesting library to use and I have been using typeorm a lot recently, I would like to do some translation so more chinese can use it. Is there someone else doing it already?

**Comment by jyang0110** [comment]
I noticed that chinese documentation isnt really complete yet. Since this is a very interesting library to use and I have been using typeorm a lot recently, I would like to do some translation so more chinese can use it. Is there someone else doing it already?

**Comment by abingoal** [comment]
> I noticed that chinese documentation isnt really complete yet. Since this is a very interesting library to use and I have been using typeorm a lot recently, I would like to do some translation so more chinese can use it. Is there someone else doing it already?

Hi, thank for your contribution. I have finished the translation of the Chinese documents.
Since my English’s not very good, there might be some mistakes. It would be great if you could improve them together with me.
With regard to theses official documents, the most important thing for us is to keep it up to date.
Will you be able to maintain Chinese version and make it always up to date? I hope you can do it constantly.

**Comment by jyang0110** [comment]
I will try to do it. If we can do it together @abingoal, it will be more efficient.
