### ISSUE TITLE
FK/PK naming strategy or name override question

### ISSUE THREAD

**Issue by zelid** [typeorm/typeorm#3847]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have some custom UI logic which takes into consideration names of foreign keys.
`TypeORM` automatically gives random FK names like `FkC6Cc2C34Bd5420Cf0F3Fe38695D` which seems to be different after each DB re-creation and similar way for PKs like `Pk51F365875Ce04758B07Bc160204`.

Having for example 
```ts
@Entity()
export class WebsiteEmail {
  @PrimaryGeneratedColumn()
  id: number

  @ManyToOne(type => Website)
  @JoinColumn()
  website: Website
  @RelationId((self: WebsiteEmail) => self.website)
  websiteId: number

  @Column()
  address: string
}
``` 

I'm interested in both FK/PK naming strategy and manual FK/PK name override. Reading documentation showed only JoinColumn name overrides or I've missed the part about FK/PK names...

How to specify FK name for `website: Website` to be `fk_website_email_website_id` and PK name for `id: number` to be `pk_website_email_id` ?

update 1:
There is some [givenName](https://github.com/typeorm/typeorm/blob/master/src/metadata/CheckMetadata.ts#L32) property in the source code. Not sure how to pass there a value from attributes yet.

**Comment by Kononnable** [comment]
I don't think we've got manual name override for PKs/FKs available as some column option etc. but You can  achieve it by using custom [NamingStrategy](https://github.com/typeorm/typeorm/blob/master/docs/naming-strategy.md).

Just extend DefaultNamingStrategy and override `primaryKeyName()` and `foreignKeyName()` functions.

**Comment by tkvw** [comment]
> Just extend DefaultNamingStrategy and override `primaryKeyName()` and `foreignKeyName()` functions.

This is really cool, but it would be useful to call `foreignKeyName` with the `referencedTablePath` and `referencedColumnNames`: https://github.com/typeorm/typeorm/blob/8757e769d2e2d39240ff70eaa6cd2dc24be202a4/src/metadata/ForeignKeyMetadata.ts#L105-L109

Now I can't use my favorite naming convention.
