### ISSUE TITLE
Replace All During Update

### ISSUE THREAD

**Issue by adamaho** [typeorm/typeorm#3850]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.12` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Wondering if there is a way for me to bulk update a relation replaces all related rows with the new data.

Say I have the following data:

```
  const user = {
    id: 1
    name: 'eve',
    photos: [{
      id: 1,
      userId: 1,
      photo: 'picture'
    }]
  }
```
and I want to update this users photos by replacing all existing photos with the photos I am supplying above. 

Currently my only solution at this point to achieve this is to remove all photos corresponding to the specific userId and insert the new ones in a transaction. Just wondering if there is a better way to achieve this kind of behaviour. Keep in mind, some of the photos might be the same. So executing

```
user.photos = newPhotos;
await user.save();
```
might throw `Duplicate key error`

```
await getManager().transaction(async (manager) => {
  await manager.delete(Photos, { userId })
  user.photos = newPhotos

  await manager.save(User, user);
}
```

Thanks! Love the work you guys are doing on this btw.

**Comment by Kononnable** [comment]
If you want to remove unused photos(not just remove relation between photo and user) I think there is no 'helper' in ORM for that.
However I don't think save should throw duplicate errors. It tries to update records if they already exists. You should check if yours newPhotos have PK column values specified - without it ORM won't be able to tell that those objects already exists in database and may throw duplicate error(e.g. if you've got unique index on some columns).

**Comment by imnotjames** [comment]
Hope this answered, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
