### ISSUE TITLE
Electron project generated platformtools.js type set to "browser"

### ISSUE THREAD

**Issue by ian-callaghan** [typeorm/typeorm#3858]
**Issue type:**

[x ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm trying to install typeorm to use sqlite for an electron project however on debugging it seems that the platformtools.js type is getting set to "browser" rather than "node". This results in it failing to load the sqlite3 package as it thinks it's running in a browser environment.

What are the conditions that generate the paltformtools.js file to be either "node" or "browser"?

**Comment by reubenmallaby** [comment]
Did you solve this? I keep getting the same error.
