### ISSUE TITLE
Unable to load sqlite on electron

### ISSUE THREAD

**Issue by ian-callaghan** [typeorm/typeorm#3859]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Getting to this block of code:
```
PlatformTools.load = function (name) {
        if (this.type === "browser")
            throw new Error("This option/function is not supported in the browser environment. Failed operation: require(\"" + name + "\").");
    };
```

for some reason typeorm thinks it's on a browser platform and I cannot for the life of me figure out why or where the type is set. Is there a way to manually override this so it knows it's in a node environment?

**Comment by Kononnable** [comment]
You didn't give us much details on where are you using it, to see if it isn't really a browser part of electron etc.
Without more info I can only refer you to https://github.com/typeorm/electron-typescript-example/blob/master/src/index.ts

**Comment by ian-callaghan** [comment]
> You didn't give us much details on where are you using it, to see if it isn't really a browser part of electron etc.
> Without more info I can only refer you to https://github.com/typeorm/electron-typescript-example/blob/master/src/index.ts

Turned out to be an issue with the dynamic "require" with webpack which had a knock on effect

**Comment by haroldo-ok** [comment]
BTW, how was this problem solved? I'm having the exact same problem using TypeORM + Electron + Webpack.

**Comment by haroldo-ok** [comment]
BTW, that's not the first time TypeORM has had conflicts with Webpack...

**Comment by ian-callaghan** [comment]
> BTW, how was this problem solved? I'm having the exact same problem using TypeORM + Electron + Webpack.

It was a long time ago but looking at the project I don't think it was solved, it's using sequelize & sequelize-typescript.

**Comment by haroldo-ok** [comment]
Many thanks. I'll see if I can do some workaround.
