### ISSUE TITLE
How does Typeorm migration work to prevent data lose?

### ISSUE THREAD

**Issue by jyang0110** [typeorm/typeorm#3861]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am working on a project that wants to reform its backend structure using typeorm. One big thing is about losing data. I havnt seen any official documentation explaining the mechanism. Also, reading migrations.ts didnt help me figure it out. I noticed a similar issue was opened at #3147 . And no discussion was given on that. Is there a way to make sure data will not be lost when migration was run?

**Comment by Kononnable** [comment]
Migrations just execute sql statements. If sql statements don't do anything unsafe then migration will be safe for data. After generating a migration you should always take a look at them and review if it's ok. There are cases when ORM is unable to know if it is able to alter the column without possibility of loosing data. In such cases you would have to modify generated queries on your own.
