### ISSUE TITLE
Is it sql-injection safe if using `FindOption` direction in find?

### ISSUE THREAD

**Issue by SunnyTam** [typeorm/typeorm#3862]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[x] `0.2.15` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Is it sql-injection safe if using `FindOption` direction in find? for example:
As the document saying `raw()` is not sql injection safe, but how about other FindOption operation? 

```ts
    typeorm.getRepository(User)
        .find({
            where: { name: typeorm.Like(`%${sqlInjectionVariable}%`) }
        })
```

**Comment by Kononnable** [comment]
If you run such query with logging enabled you can see that `sqlInjectionVariable` is passed as sql parameter - so yes, it's sql injection safe.
