### ISSUE TITLE
Injecting dependencies into an entity or repository.

### ISSUE THREAD

**Issue by CesarHuelamo** [typeorm/typeorm#3864]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Is there a way to inject clases from outside of the typeorm environment, like a class service. This is what i'm trying to do, but it doesn't work in any way:

``` 
@Entity()
export class Users {
  constructor(private readonly usersService: UsersService){}
  @PrimaryGeneratedColumn()
  @ApiResponseModelProperty()
  id: number;
}
```

UsersService being a declared class with dependencies injected into it.

**Comment by vlapo** [comment]
We do not know your environment :) so it is hard to help you with this problem. But I do not think so entity is right place to work with services. You should move this functionality to service or another place with business logic.

Note: In current version of typeorm constructor parameters have to be optional (this is subject of change in `next` version).

**Comment by ksuhiyp** [comment]
@vlapo I can give a use case of this, suppose we have an AWS service and we need to trigger deleteObject method from that service by using @BeforeRemove(), How could you do that?

**Comment by neuro-sys** [comment]
> @vlapo I can give a use case of this, suppose we have an AWS service and we need to trigger deleteObject method from that service by using @BeforeRemove(), How could you do that?

How are you going to rollback if the database operation fails?
