### ISSUE TITLE
Feature: Possibility to constraint decorators to a specific database type

### ISSUE THREAD

**Issue by pmoleri** [typeorm/typeorm#3865]
**Issue type:**
[x] feature request

**Database system/driver:**

[x] `mysql` / `mariadb`
[x] `sqlite`

**TypeORM version:**

[x] `0.2.6`

Currently we need to specify some options in a DBMS specific way, as noted in #2217.

Today I hit another issue:
```ts
    @Column({ type: String, nullable: true, charset: "utf8mb4", collation: "utf8mb4_unicode_ci" })
```
This works fine in MySQL but fails in SQLite, which makes sense because this collation is specific to MySQL.

The proposal is some way to define decorators that would apply only to a specific driver.
e.g.:
```ts
    @Column({ type: String, nullable: true, charset: "utf8" })
    @Column({ only: "mysql", type: "varchar", nullable: true, charset: "utf8mb4", collation: "utf8mb4_unicode_ci" })
    description: string;
```

Both decorators get applied to the same column. When using MySQL the second one overwrites the first one.
If a solution like is possible, it would empower developers that need to support different databases.

**Comment by Kononnable** [comment]
If you want to use same schema with multiple db drivers you should use entity schemas to define your db structure. It's much better approach in such cases.

Adding new decorator would make entity definition less readable and I think it would require major changes in typeorm code.

**Comment by imnotjames** [comment]
Unfortunately, this feature is not likely going to happen.  It makes the API much more difficult to document and use.  Per @Kononnable for the foreseeable future user entity schemas.
