### ISSUE TITLE
Mongo Db full text search crashes

### ISSUE THREAD

**Issue by judemanutd** [typeorm/typeorm#3866]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Model File 

```ts
@Entity({ database: MONGO_DATABASE_NAME })
export class PlatformIngredients {
  @ObjectIdColumn()
  id: ObjectID;

  @Index({ fulltext: true })
  @Column()
  name: string;

}
```

Query being run 

```ts
    const repo = getMongoRepository(PlatformIngredients, MONGO_CONNECTION_NAME);

    const condition: any = {};

    if (query) {
      condition.where = {
        status: 1,
        name: { $text: { $search: query } },
      };
    }

    condition.skip = 0;
    condition.take = 10;

    const data: any = await repo.find(condition);
    return {
      status: true,
      payload: data,
    };
```

This causes a crash with the following error

```ts
[ { MongoError: unknown operator: $text
      at /home/jude/VScodeProjects/OrderForMe/ofm/node_modules/mongodb-core/lib/connection/pool.js:581:63
      at authenticateStragglers (/home/jude/VScodeProjects/OrderForMe/ofm/node_modules/mongodb-core/lib/connection/pool.js:504:16)
      at Connection.messageHandler (/home/jude/VScodeProjects/OrderForMe/ofm/node_modules/mongodb-core/lib/connection/pool.js:540:5)
      at emitMessageHandler (/home/jude/VScodeProjects/OrderForMe/ofm/node_modules/mongodb-core/lib/connection/connection.js:310:10)
      at TLSSocket.<anonymous> (/home/jude/VScodeProjects/OrderForMe/ofm/node_modules/mongodb-core/lib/connection/connection.js:453:17)
      at TLSSocket.emit (events.js:197:13)
      at addChunk (_stream_readable.js:288:12)
      at readableAddChunk (_stream_readable.js:269:11)
      at TLSSocket.Readable.push (_stream_readable.js:224:10)
      at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
    operationTime:
     Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1553184899 },
    ok: 0,
    errmsg: 'unknown operator: $text',
    code: 2,
    codeName: 'BadValue',
    '$clusterTime': { clusterTime: [Timestamp], signature: [Object] },
    name: 'MongoError',
    [Symbol(mongoErrorContextSymbol)]: {} } ]
```

One thing to note is, there was already data in the collection when i created the `fulltext` index. Is that the reason for this issue? The mongodb is hosted on atlas and I checked the collection, the index is created.

**Comment by judemanutd** [comment]
Also noted that the `@Index({ fulltext: true })` is not creating a text instead but instead created a `regular` index, which seems to be the problem. I'm using MongoDb Atlas

**Comment by brdacost** [comment]
I am having the exact same problem while doing a full-text search on my node API. Any updates on a solution??

**Comment by umstek** [comment]
I had a similar problem and found this result: https://github.com/typeorm/typeorm/search?q=fulltext&unscoped_q=fulltext.

> The FULLTEXT modifier indexes the entire column and does not allow prefixing. Works only in MySQL.

**Comment by kemicofa** [comment]
I've attempted to set do a search like so:

```
{
    //  ...conditions
    where: {
        $text: { $search: "hello world" }
    }
}
```

Which is giving me:
> MongoError: text index required for $text query

I then added:
```
@Entity()
@Index('text', ['title', 'summary'])
class Book extends BaseEntity {}
```

And when I check my indexes, I get:

```
[
  { v: 2, key: { _id: 1 }, name: '_id_', ns: 'nova-lux.book' },
  {
    v: 2,
    key: { title: 1, summary: 1 },
    name: 'text',
    ns: 'nova-lux.book',
    sparse: false,
    background: false
  }
]
```

The index with the name "text" was correctly created, however I'm still getting the same issue. I feel like I'm close.

What am I missing?

**Comment by kemicofa** [comment]
Alright, figured it out. If you want to create a text index, then you need to use the built in methods.

```
getMongoManager()
    .createCollectionIndex(Book, {
        title: "text",
        summary: "text"
    }).then(res => console.log(res))
      .catch(err => console.log(err));
``` 

Then this type of search will work

```
{
    //  ...conditions
    where: {
        $text: { $search: "hello world" }
    }
}
```

**Comment by vanleantking** [comment]
Is typeorm mongo repository support on sorting base on meta score text search mongo?
example, from mongo, i want to search:
`db.todos.find( 
    {$text: { $search: "coffee" }}, 
    {score: { "$meta": "textScore" }})
.sort({score: { "$meta": "textScore" }})
.limit(20);`

How can i do it from typeorm?

**Comment by oussaki** [comment]
@kemicofa it didn't work for me what you did exactly ? am trying to search iin a nested document.

**Comment by oussaki** [comment]
i tried my self the only way that works for me is regular expression

`getRepository(Product).find({ where: {
            title :  new RegExp(keyword, 'gi'),
  
        }})`

**Comment by imnotjames** [comment]
This isn't an issue with TypeORM as far as I can see - instead, with Mongo's query mechanisms which we don't really touch.  As such, I'm closing this out.
