### ISSUE TITLE
Select where string is in simple-array

### ISSUE THREAD

**Issue by frenchqwerty** [typeorm/typeorm#3868]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.14` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi everyone, I'm trying to select some rows where a string is in an simple-array. Let's see some code :

```js
export class Picture {
    @PrimaryGeneratedColumn()
    id: number;

    @Column('bigint')
    createdDate: number;

    @Column('text', {nullable: true})
    description: string;

    @Column("simple-array", {nullable: true})
    mentions: string[];

    @Column("simple-array", {nullable: true}) //that
    tags: string[];

    @Column('text')
    url: string;

    @Column('text')
    userId: string;
}
```

```js
await getRepository(Picture)
                .createQueryBuilder("picture")
                .where("picture.tags IN tags", {tags: string})
                .getMany();
```

Thanks for help !

**Comment by frenchqwerty** [comment]
I have fixed my issue !

```js
tags = await getRepository(Picture)
                .createQueryBuilder("picture")
                .where("picture.tags like :tags", {tags: search + '%'})
                .getMany();
```

**Comment by martijnvdbrug** [comment]
Your query only gives result where the first tag is 'search'. To find all record containing 'search' you should also add '%' as prefix to the search tag:
```
tags = await getRepository(Picture)
                .createQueryBuilder("picture")
                .where("picture.tags like :tags", {tags: `%${search}%`})
                .getMany();
```

**Comment by plopezm** [comment]
My solution is as follows:

```
this.getFindQueryBuilder().where("recipe.tags && ARRAY[:...tags]", {tags: tags})
```
"getFindQueryBuilder": Is a function to get shared SelectQueryBuilder in order to save code.

The important part here is the where clause that I have shown in the example.

**Comment by kallol24** [comment]
@plopezm I m getting "operator does not exist: text @> text[]" error

**Comment by kennylbj** [comment]
The `like` operation is not working in all conditions.

Assume there are two pre-defined tags: 'Admin' and 'SuperAdmin'. User A has tags: [Admin] and user B has tags: [SuperAdmin].

Then if I query by `Admin` using `like` operation as ```qb.where("user.tags like :tags", {tags: `%Admin%`})```, both user A and user B will return.

However, the expected result is to return user A only.
