### ISSUE TITLE
TypeError: _this.mssql.Connection is not a constructor

### ISSUE THREAD

**Issue by kjetilhp** [typeorm/typeorm#387]
Testing the first example in the repo agains MS SQL results in a type error, tested against mysql and that config works, the config is the same as in the samples and the mssql package is installed

```javascript
Cannot connect:  TypeError: _this.mssql.Connection is not a constructor
    at /Users/kjetil/dev/typeorm/simple/node_modules/typeorm/driver/sqlserver/SqlServerDriver.js:98:30
    at SqlServerDriver.connect (/Users/kjetil/dev/typeorm/simple/node_modules/typeorm/driver/sqlserver/SqlServerDriver.js:97:16)
    at Connection.<anonymous> (/Users/kjetil/dev/typeorm/simple/node_modules/typeorm/connection/Connection.js:165:58)
    at step (/Users/kjetil/dev/typeorm/simple/node_modules/typeorm/connection/Connection.js:32:23)
    at Object.next (/Users/kjetil/dev/typeorm/simple/node_modules/typeorm/connection/Connection.js:13:53)
    at /Users/kjetil/dev/typeorm/simple/node_modules/typeorm/connection/Connection.js:7:71
    at __awaiter (/Users/kjetil/dev/typeorm/simple/node_modules/typeorm/connection/Connection.js:3:12)
    at Connection.connect (/Users/kjetil/dev/typeorm/simple/node_modules/typeorm/connection/Connection.js:157:16)
    at ConnectionManager.<anonymous> (/Users/kjetil/dev/typeorm/simple/node_modules/typeorm/connection/ConnectionManager.js:329:57)
    at step (/Users/kjetil/dev/typeorm/simple/node_modules/typeorm/connection/ConnectionManager.js:32:23)

```

app.ts 
```javascript
import "reflect-metadata";
import {createConnection, ConnectionOptions} from "typeorm";
import {Post} from "./entity/Post";

const options: ConnectionOptions = {
    driver: {
        type: "mssql",
        host: "integration",
        username: "sa",
        password: "....",
        database: "PDB01",
        port: 1433
    },
    logging: {
        logQueries: true,
        logSchemaCreation: true
    },
    autoSchemaSync: true,
    entities: [Post]
};

createConnection(options).then(connection => {

    let post = new Post();
    post.text = "Hello how are you?";
    post.title = "hello";
    post.likesCount = 100;

    let postRepository = connection.getRepository(Post);

    postRepository
        .persist(post)
        .then(post => console.log("Post has been saved: ", post))
        .catch(error => console.log("Cannot save. Error: ", error));

}, error => console.log("Cannot connect: ", error));
```

running a simple mssql node query from same directory works so should be nothing wrong with the driver or config

package.json
```javascript
{
  "name": "typeorm-typescript-example",
  "version": "0.0.1",
  "devDependencies": {
    "typescript": "^2.2.2"
  },
  "dependencies": {
    "@types/node": "^7.0.12",
    "mssql": "^4.0.1",
    "mysql": "^2.13.0",
    "reflect-metadata": "^0.1.10",
    "typeorm": "0.0.11"
  }
}
```

**Comment by pleerock** [comment]
the only reason I can guess is the version of mssql you have. Its `4.0.1` and looks like they had breaking changes. Try to install `3.3.0` until I take a look whats new in the 4 release.

`npm i mssql@3.3.0`

**Comment by kjetilhp** [comment]
Great, thx, that did it :)

**Comment by pleerock** [comment]
np. I'll keep this opened to investigate this issue later

**Comment by kjetilhp** [comment]
3.x to 4.x changes

- Library & tests are rewritten to ES6.
- **Connection was renamed to ConnectionPool.**
- Drivers are no longer loaded dynamically so the library is now compatible with Webpack. To use msnodesqlv8 driver, use const sql = require('mssql/msnodesqlv8') syntax.
- Every callback/resolve now returns result object only. This object contains recordsets (array of recordsets), recordset (first recordset from array of recordsets), rowsAffected (array of numbers representig number of affected rows by each insert/update/delete statement) and output (key/value collection of output parameters' values).
- Affected rows are now returned as an array. A separate number for each SQL statement.
- Directive multiple: true was removed.
- Transaction and PreparedStatement internal queues was removed.
- ConnectionPool no longer emits connect and close events.
- Removed verbose and debug mode.
- Removed support for tds and msnodesql drivers.
- Removed support for Node versions lower than 4.

(just for reference)

**Comment by pleerock** [comment]
thank you for the information

**Comment by bensquire** [comment]
Any updates RE this issue? v3 of node msSQL seems to be giving me issues, but v4 isn't compatible yet...

**Comment by pleerock** [comment]
v4 is supported since `0.1.0-alpha.10`

**Comment by TBG-FR** [comment]
I'm getting the same error with the following versions
```
"mssql": "^6.4.1",
"typeorm": "^0.3.6"
"@nestjs/typeorm": "^8.1.4",
"@types/mssql": "^8.0.2",
"msnodesqlv8": "^2.5.0",
```

Any ideas on how to fix this ?
