### ISSUE TITLE
Mysql bit(1) not converted to boolean. How to map this type?

### ISSUE THREAD

**Issue by squalsoft** [typeorm/typeorm#3875]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Entity Framework generated bool columns as bit(1) in mysql. When i map those columns in typeorm as bit type and boolean property type they do not read as true/false from db. Instead those props read as complex object. Expected true or false.
How to properly bind boolean to mysql bit(1) column?

```
@Column({
    type: 'bit',
    nullable: false,
    default: () => `"'b'1''"`,
    name: 'can_read'
  })
 can_read!: boolean;
```

// After db read i receive:
```
const user = await this.workersRepository.findOne({ login: username });
user.can_read // Buffer(1) [0] <= Here must be false
```

**Comment by squalsoft** [comment]
I can resolve this issue with transformer:
`class BoolBitTransformer implements ValueTransformer {
  // To db from code
  to(value: boolean | undefined): ArrayBuffer | null {
    if (value === null) {
      return null;
    }
    const res = new ArrayBuffer(1);
    res[0] = value ? 1 : 0;
    return res;
  }
  // From db to typeorm
  from(value: ArrayBuffer): boolean | undefined {
    const tt = typeof value;
    if (value[0] === null) {
      return undefined;
    }
    return value[0] === 1;
  }
}`

And then

`
  @Column({
    type: 'bit',
    nullable: false,
    default: () => `"'b'1''"`,
    name: 'can_read',
    transformer: new BoolBitTransformer()
  })
  can_read!: boolean;`


But maybe it exists more comfortable solution?

**Comment by vlapo** [comment]
We are mapping boolean into `tinyint` as DB type for mysql driver. So your solution with transformer is only possible solution for now.

**Comment by webtimo-de** [comment]
Hello, so I have another question. If I then want to search for something with "where" and I want to have all "true", he can't translate that.


```
let list = await StaffFile.find({
    where: {
        hasBeenNotified: true
    }
});
```

**Comment by webtimo-de** [comment]
Hello folks, I found a solution because I personally found the fact that typeorm does not offer bit(1) as a boolean in MySQL, found another solution!
TypeORM has a Raw() function, or the In() function.

However, the BoolBitTransformer must be changed for this.

```typescript
import {FindOperator, ValueTransformer} from 'typeorm';

export class BoolBitTransformer implements ValueTransformer {
    // To db from typeorm
    to(value: boolean | null): Buffer | null {
        if ((value as any) instanceof FindOperator) {
            return <any>value;
        }
        if (value === null) {
            return null;
        }
        const res = Buffer.alloc(1);
        res[0] = value ? 1 : 0;
        return res;
    }

    // From db to typeorm
    from(value: Buffer): boolean | null {
        if (value === null) {
            return null;
        }
        return value[0] === 1;
    }
}
```

And if you now want to search for true or false, you have to specify this in the query.

Raw() Function:
```typescript
const boolean: boolean = true; // true, false
const data = await Staff.find({
    where: {
        active: boolean ? Raw('true') : Raw('false') 
    }
});
```

In() Function:
```typescript
const boolean: boolean = true; // true, false, null
const data = await Staff.find({
    where: {
        active: In([boolean])
    }
});
```


Personally, I prefer the In() function because you can also pass true, false and null here, even as a variable without any problems.

So I'll go and rewrite my code, I hope I could make life easier for others (:

**Comment by ertl** [comment]
@webtimo-de, your workaround for the FindOperator assignment is excellent. It seems to be addressing the same issue as either #9381 or #9793. With the introduction of PR #9777, the extra if condition in your transformer is no longer required.
