### ISSUE TITLE
Are repositories "light" objects?

### ISSUE THREAD

**Issue by acrodrig** [typeorm/typeorm#3879]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am wondering if I should cache the repositories that I get via `getRepository` in a static class field, or if it is OK to keep calling `getRepository` every time I need one.

Could you advise as to what is the best practice? Thanks.

**Comment by Kononnable** [comment]
You can call `getRepository` each time. Repository object kind of acts as a singleton.
https://github.com/typeorm/typeorm/blob/21134ceeaaa25aa353908719dffe2dd2ba538cda/src/entity-manager/EntityManager.ts#L1004-L1020

**Comment by acrodrig** [comment]
Thanks much.
