### ISSUE TITLE
Can I call createConnection multiple times?

### ISSUE THREAD

**Issue by acrodrig** [typeorm/typeorm#3880]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

What happens when I call `createConnection` multiple times from different files? Does one wait on the other? Do they duplicate resources?

Ideally both would return the same promise? Thanks for letting me know.

**Comment by Kononnable** [comment]
If you try to open the same connection as one which is already active you will get `AlreadyHasActiveConnectionError`.

**Comment by marclar** [comment]
@Kononnable running into this right now. What's the correct way to avoid this error?

**Comment by Kononnable** [comment]
You should save connection object after connecting and reuse it - or close it(if you don't want it for some reason to be open) and you will be able to open it again without an error.

**Comment by msheakoski** [comment]
Here is what I ended up doing in each file:
```typescript
try {
    getConnection();
} catch (e) {
    await createConnection();
}
```

**Comment by imnotjames** [comment]
Looks like it worked for you!  In the future we'll be moving away from a lot of the connection tracking - but you'll still be wanting to use something to reuse connections.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
