### ISSUE TITLE
Typeorm extension points

### ISSUE THREAD

**Issue by irissoftworks** [typeorm/typeorm#3884]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

There is a new package which wraps cls based transactions https://github.com/odavid/typeorm-transactional-cls-hooked and solves https://github.com/typeorm/typeorm/issues/1895. 

My problem at the moment is that it requires extending a base repository - This inheritance based model makes it kind of unclean to integrate multiple different typeorm extension libraries - if all extension libraries require extending a custom repository it will become messy at one stage no matter what. 

Example, I would love to integrate both cls-transactions and typeorm-linq-repository, as per https://github.com/IRCraziestTaxi/typeorm-linq-repository/issues/54

Does anyone know of any existing typeorm guidelines for integrating third party functionality into the orm in a way that multiple extensions can work together ? If there were some simple guidelines this type of issues could be avoided ? Does it depend too much on what type of extension it is, or would some general guidelines work for most cases ?

I am guessing most of these would involve repositories using the entityManager provided / modified by another library, so maybe being able to pipe the entityManager modifications / retrieval logic at bootstrap in some way would work (I am thinking middleware kind of approach) ?

Any ideas ? What do you reckon @nicomouss, @odavid, @IRCraziestTaxi ?

Also, for typeorm maintainers would it be possible to maybe share some ideas on how you think this problem could be better solved or if it was already solved and I'm missing something ?

**Comment by IRCraziestTaxi** [comment]
That `typeorm-transactional-cls-hooked` lib looks awesome! Good work, @odavid!

For what it's worth, aside from what would probably be a huge pain to use a base repo from both `typeorm-transactional-cls-hooked` and `typeorm-linq-repository` in order to make both work, I do believe that `typeorm-linq-repository` should support transactions on its own, so I will likely do something similar for `typeorm-linq-repository` in a way that works for it.

Still, great question - there are a lot of great libs that makes TypeORM even easier to use and it would be great to figure out a way to integrate them more easily. The middleware suggestion could be promising. I will take that into consideration while I'm fiddling with transaction support in `typeorm-linq-repository` while keeping an eye on this thread.

**Comment by irissoftworks** [comment]
@IRCraziestTaxi thanks so much for sharing !

Sure, your first suggestion that typeorm-linq-repositories could support transactions would work for this case, it would make the library more powerful. If you proceed with that of course will be super happy as the functionality will be there. 

Still, would be great to explore if it could be avoided reinventing the wheel and rewriting the same functionality while at the same time have something that works for any future integrations ?

These are two different types of libraries. One that changes the contract and implementation of repositories, i.e typeorm-linq-repositories, and one that modifies the entity manager resolution logic i.e cls-transactions. 
It seems to me like they would require different types of integration with the orm and each other. 

I wonder if a library that is just modifying the entity manager resolution needs a custom repository since they are not changing the contract of the repo. 
Maybe they could (alternatively or in addition) provide a factory encapsulating the logic of resolving the entity manager. 
This would mean creating / exporting a factory from the cls-transactions, and modify cls-transactions to also use this same factory, for anyone who wants to use the custom repo.
I believe it would be easy enough to combine multiple factories if further entity manager resolution logic is required.

To integrate this approach with libraries that modify the repository contracts such as linq-repos the repo libraries would have to accept a custom entity mgr factory.
It would also become easier to implement custom repos that use the factory internally without inheriting or rewriting the resolution logic.

**Comment by odavid** [comment]
Hi @irissoftworks,
The only reason I created the [BaseRepository](https://github.com/odavid/typeorm-transactional-cls-hooked/blob/master/src/BaseRepository.ts) was for being able to have the [manager](https://github.com/odavid/typeorm-transactional-cls-hooked/blob/master/src/BaseRepository.ts#L16) property being overridden.
If inheritance is not an option (or at least not the preferred one), I believe a person can just use the same code within his repositories.

@Diluka suggested the following solution: https://gist.github.com/Diluka/87efbd9169cae96a012a43d1e5695667 (Haven't tried it, but maybe you will find it useful)...

**Comment by irissoftworks** [comment]
Hi @odavid thanks so much for the insight.

Sure would be great if we could simply use the same code and implement the custom repository. 

I was looking at it:
```
import { getEntityManagerForConnection, NAMESPACE_NAME } from './common'

private getManagerOrTransactionManager(): EntityManager {
    const context = getNamespace(NAMESPACE_NAME)

    if (context && context.active) {
      const transactionalEntityManager = getEntityManagerForConnection(
        this._connectionName,
        context
      )

      if (transactionalEntityManager) {
        return transactionalEntityManager
      }
    }
    return this._manager || getManager(this._connectionName)
 }
```

I could be wrong, maybe there is another way, but the functions above from common aren't exported from index, would it be possible to export them ?

**Comment by odavid** [comment]
Will do.

**Comment by irissoftworks** [comment]
Great! thanks for that and also for pointing out the patch, I haven't tried it yet, but if it works maybe adding the patch function with the package is a good solution as well. 

I am happy with whichever u think it's best!

**Comment by odavid** [comment]
@irissoftworks - See https://github.com/odavid/typeorm-transactional-cls-hooked/pull/13

**Comment by irissoftworks** [comment]
Thanks very much.

I think with this clean and easy approach we can close the issue! thanks all.

**Comment by odavid** [comment]
@irissoftworks - I also added https://github.com/odavid/typeorm-transactional-cls-hooked/pull/14
So now, patching/mixing BaseRepository and Repository could be done by calling a `patchTypeORMRepositoryWithBaseRepository` during initialization.

**Comment by IRCraziestTaxi** [comment]
@odavid That's awesome! That should make using `typeorm-transactional-cls-hooked` a cinch to use with `typeorm-linq-repository`. In fact, it looks like there won't even be a need to add `typeorm-transactional-cls-hooked` as a dependency for `typeorm-linq-repository` - the user can simply call your `patchTypeORMRepositoryWithBaseRepository` and `typeorm-linq-repository` does its thing without a need to worry about it. Thanks so much for the awesome work!
