### ISSUE TITLE
How to create many to many

### ISSUE THREAD

**Issue by kouchao** [typeorm/typeorm#3886]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How to create many to many such as :
![image](https://user-images.githubusercontent.com/23720738/54876504-dedc3d00-4e4b-11e9-81a9-6ad770c5bef3.png)

**Comment by vlapo** [comment]
Hey @kouchao. We have plenty of issues about this problem. Please check https://github.com/typeorm/typeorm/issues/2402 or https://github.com/typeorm/typeorm/issues/1224.
