### ISSUE TITLE
OneToMany doesn't work

### ISSUE THREAD

**Issue by akliyiping** [typeorm/typeorm#3887]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

```
import {BaseEntity, Column, Entity, Index, JoinColumn, JoinTable, ManyToMany, ManyToOne, OneToMany, OneToOne, PrimaryColumn, PrimaryGeneratedColumn, RelationId} from 'typeorm';
import {EquipmentPropertyUnit} from './EquipmentPropertyUnit';

@Entity('equipment', {schema: 'kings' } )
@Index('equipment_label_uindex', ['label'], {unique: true})
export class Equipment extends BaseEntity {

    @PrimaryGeneratedColumn({
        type: 'bigint',
        name: 'id',
        })
    id: string;

    @Column('varchar', {
        nullable: true,
        unique: true,
        length: 100,
        name: 'label',
        })
    label: string | null;

    @Column('varchar', {
        nullable: true,
        length: 100,
        name: 'name',
        })
    name: string | null;

    @Column('varchar', {
        nullable: true,
        length: 300,
        name: 'image_url',
        })
    imageUrl: string | null;

    @Column('decimal', {
        nullable: true,
        scale: 1,
        name: 'price',
        })
    price: string | null;

    @Column('varchar', {
        nullable: true,
        length: 100,
        name: 'category',
        })
    category: string | null;

    @OneToMany(type => EquipmentPropertyUnit, equipment_property_unit => equipment_property_unit.equipmentLabel, { onDelete: 'NO ACTION' , onUpdate: 'NO ACTION' })
    equipmentPropertyUnits: EquipmentPropertyUnit[];

}
```

```
import {BaseEntity, Column, Entity, Index, JoinColumn, JoinTable, ManyToMany, ManyToOne, OneToMany, OneToOne, PrimaryColumn, PrimaryGeneratedColumn, RelationId} from 'typeorm';
import {Equipment} from './Equipment';
import {PropertyUnit} from './PropertyUnit';

@Entity('equipment_property_unit', {schema: 'kings' } )
@Index('equipment_property_unit_equipment_label_fk', ['equipmentLabel'])
@Index('equipment_property_unit_property_unit_label_fk', ['unitLabel'])
export class EquipmentPropertyUnit extends BaseEntity {

    @PrimaryGeneratedColumn({
        type: 'bigint',
        name: 'id',
        })
    id: string;

    @ManyToOne(type => Equipment, equipment => equipment.equipmentPropertyUnits, { onDelete: 'NO ACTION', onUpdate: 'NO ACTION' })
    @JoinColumn({ name: 'equipment_label'})
    equipmentLabel: Equipment | null;

    @ManyToOne(type => PropertyUnit, property_unit => property_unit.equipmentPropertyUnits, { onDelete: 'NO ACTION', onUpdate: 'NO ACTION' })
    @JoinColumn({ name: 'unit_label'})
    unitLabel: PropertyUnit | null;

    @Column('bigint', {
        nullable: true,
        name: 'size',
        })
    size: string | null;

}

```

# console print query log

SELECT `Equipment`.`id` AS `Equipment_id`, `Equipment`.`label` AS `Equipment_label`, `Equipment`.`name` AS `Equipment_name`, `Equipment`.`image_url` AS `Equipment_image_url`, `Equipment`.`price` AS `Equipment_price`, `Equipment`.`category` AS `Equipment_category`, `Equipment__equipmentPropertyUnits`.`id` AS `Equipment__equipmentPropertyUnits_id`, `Equipment__equipmentPropertyUnits`.`size` AS `Equipment__equipmentPropertyUnits_size`, `Equipment__equipmentPropertyUnits`.`equipment_label` AS `Equipment__equipmentPropertyUnits_equipment_label`, `Equipment__equipmentPropertyUnits`.`unit_label` AS `Equipment__equipmentPropertyUnits_unit_label` FROM `kings`.`equipment` `Equipment` LEFT JOIN `kings`.`equipment_property_unit` `Equipment__equipmentPropertyUnits` ON `Equipment__equipmentPropertyUnits`.`equipment_label`=`Equipment`.`id`

the query log is wrong;
the last line,
***`Equipment__equipmentPropertyUnits`.`equipment_label`=`Equipment`.`id`***
should be 
***`Equipment__equipmentPropertyUnits`.`equipment_label`=`Equipment`.`label`***

**Comment by alfonsoal1983** [comment]
Hi. for the joincolumn to refer to another column of the table you have to put the referencedColumnName option as it appears in this part of the documentation.
https://github.com/typeorm/typeorm/blob/master/docs/relations.md#joincolumn-options

Try to change this:

`@ManyToOne(type => Equipment, equipment => equipment.equipmentPropertyUnits, { onDelete: 'NO ACTION', onUpdate: 'NO ACTION' })
    @JoinColumn({ name: 'equipment_label'})
    equipmentLabel: Equipment | null;`

for this:

`@ManyToOne(type => Equipment, equipment => equipment.equipmentPropertyUnits, { onDelete: 'NO ACTION', onUpdate: 'NO ACTION' })
    @JoinColumn({ name: 'equipment_label', referencedColumnName: 'label'})
    equipmentLabel: Equipment | null;`

Remember that the value of the referencedColumnName must exist in the entity to which you refer.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
