### ISSUE TITLE
Zero as a discriminator value

### ISSUE THREAD

**Issue by menixator** [typeorm/typeorm#3891]
Due to this line, I am unable to use `0` as a discriminator value. Is this intended?
https://github.com/typeorm/typeorm/blob/b91a7259b4b9e1226c14f26f9ecbafea08eaae23/src/decorator/entity/ChildEntity.ts#L18

Currently working around it by starting the enum I use to hold the discriminators from `1`.

**Comment by imnotjames** [comment]
I added to just that location.  Wasn't enough.  Somewhere else must be checking...

**Comment by imnotjames** [comment]
Ok - ran into some weirdness but we should be good to go.  Waiting on tests to pass then I'll open a PR!
