### ISSUE TITLE
migrations not run with dotenv file

### ISSUE THREAD

**Issue by kodayashi** [typeorm/typeorm#3894]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello, I'm trying to run migrations. I have a dotenv configuration file for each non-production environment per the dotenv instructions (.env.development, .env.test, etc.). However, when I run migrations I get the error:

Error: No connection options were found in any of configurations file.

I've tried explicity setting the file with --config .env.development and I've tried leaving things blank. How should I be specifying this file?

**Comment by kodayashi** [comment]
I see now that this works IFF the file is named `.env`. This won't work for us as our development and test environments use different databases. Would love to be able to just specify an arbitrary config file here using the standard dotenv naming structure (`.env*`).

**Comment by kodayashi** [comment]
I also see that it works with `--config development.env` so we can change our dotenv configuration to read from `<environment>.env` instead of `.env.<environment>` however it'd be nice if an arbitrary filename could be configured here.

**Comment by FbPalmabit** [comment]
@kodayashi have you resolved this problem?

**Comment by devdemi** [comment]
I have the same problem. I have a file with typeorm configuration `src/config/typeorm.ts`
```
export default {
    type: "postgres",
    host: process.env.DB_HOST,
    port: parseInt(process.env.DB_PORT),
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    schema: process.env.DB_SCHEMA,
    logging: process.env.DB_LOGGING == 'true',
    sync: process.env.DB_SYNC == 'true',
    entities: ["dist/**/*.entity{.ts,.js}"],
    migrations: ["dist/migrations/*{.ts,.js}"],
    cli: {
        migrationsDir: "migrations"
    }
}
```
I couldn't execute `typeorm migration:run --config dist/src/config/typeorm.js` because `dotenv` doesn't apply enviroment variables. And it seems `--config development.env` or `--config .env.development` will not work because the file contains just text wich describe enviroment variables.
Please advise how to apply config which uses environment variables.

**Comment by sergiubreban** [comment]
@devdemi have you resolved this?

**Comment by italoiz** [comment]
I have the same problem here. I verified the code base and I noticed that the TypeORM doing loading `.env` file, overriding my `dotenv` rules.

See how my environment files are configured.

```typescript
// >>> env.ts
import dotenv from 'dotenv';
import path from 'path';

const envFile = process.env.NODE_ENV ? `.env.${process.env.NODE_ENV}` : '.env';
const envPath = path.resolve(__dirname, `../../${envFile}`);

dotenv.config({
  path: envPath,
});

// >>> ormconfig.ts
import '@config/env';

const { DB_TYPE, DB_USER, DB_PASS, DB_NAME, DB_HOST } = process.env;

module.exports = [
  {
    type: DB_TYPE || 'postgres',
    name: 'default',
    host: DB_HOST,
    username: DB_USER,
    password: DB_PASS,
    database: DB_NAME,
    entities: ['src/modules/**/infra/typeorm/entities/*.ts'],
    migrations: ['src/shared/infra/typeorm/migrations/*.ts'],
    cli: {
      migrationsDir: 'src/shared/infra/typeorm/migrations',
    },
    migrationsTableName: '_migrations',
  },
];
```

I believe that what is causing problems is the excerpt below. We should and could have a way to avoid this behavior.

https://github.com/typeorm/typeorm/blob/4ed79c9cf9ad0f1e51930159dfdab8c1e8549339/src/connection/ConnectionOptionsReader.ts#L98-L101

**Comment by rubiin** [comment]
> I have the same problem here. I verified the code base and I noticed that the TypeORM doing loading `.env` file, overriding my `dotenv` rules.
> 
> See how my environment files are configured.
> 
> ```ts
> // >>> env.ts
> import dotenv from 'dotenv';
> import path from 'path';
> 
> const envFile = process.env.NODE_ENV ? `.env.${process.env.NODE_ENV}` : '.env';
> const envPath = path.resolve(__dirname, `../../${envFile}`);
> 
> dotenv.config({
>   path: envPath,
> });
> 
> // >>> ormconfig.ts
> import '@config/env';
> 
> const { DB_TYPE, DB_USER, DB_PASS, DB_NAME, DB_HOST } = process.env;
> 
> module.exports = [
>   {
>     type: DB_TYPE || 'postgres',
>     name: 'default',
>     host: DB_HOST,
>     username: DB_USER,
>     password: DB_PASS,
>     database: DB_NAME,
>     entities: ['src/modules/**/infra/typeorm/entities/*.ts'],
>     migrations: ['src/shared/infra/typeorm/migrations/*.ts'],
>     cli: {
>       migrationsDir: 'src/shared/infra/typeorm/migrations',
>     },
>     migrationsTableName: '_migrations',
>   },
> ];
> ```
> 
> I believe that what is causing problems is the excerpt below. We should and could have a way to avoid this behavior.
> 
> https://github.com/typeorm/typeorm/blob/4ed79c9cf9ad0f1e51930159dfdab8c1e8549339/src/connection/ConnectionOptionsReader.ts#L98-L101

i am using migrations with dotenv and it works

**Comment by rndnusanet** [comment]
this config not work.
export const AppDataSource = new DataSource({
  type: process.env.DB_TYPE as 'mysql' | 'mariadb' | 'postgres',
  host: process.env.DB_HOST,
  port: parseInt(process.env.DB_PORT),
  username: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DBNAME,
  synchronize: false,
  entities: [],
  migrations: ['migrations/*'],
  migrationsTableName: 'ttb_migration_table',
});

but this config work
import 'reflect-metadata';
import { DataSource } from 'typeorm';

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: '*****',
  port: 3306,
  username: '*****',
  password: '*****',
  database: '*****',
  synchronize: false,
  entities: [],
  migrations: ['migrations/*'],
  migrationsTableName: 'ttb_migration_table',
});

why ???

**Comment by rndnusanet** [comment]
the script  not load my .env file

**Comment by IamSanjayGupta** [comment]
`import 'dotenv/config';`

just add above line in you migration.config.ts file it will work.
