### ISSUE TITLE
Subdocuments (embed documents) return undifined column by 0 or false value

### ISSUE THREAD

**Issue by SevenWaysEO** [typeorm/typeorm#3899]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts 
@Entity()
export class User {

    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column(type => Profile)
    profile: Profile;
}

export class Profile {

    @Column()
    about: string;

    @Column()
    age: number;

    @Column()
    showProfile: boolean;

    @Column()
    visits: number;
}
 ```

Mongodb saved Document
```json
{
  _id: "5c98ef4bf9f43841ba76990c",
  firstName: "Max",
  lastName: "Musterman",
  profile: {
    about: "Test",
    age: 22,
    showProfile: false,
    visits: 0
  }
}

 ```
Typeorm returns

```json
User {
  _id: "5c98ef4bf9f43841ba76990c",
  firstName: "Max",
  lastName: "Musterman",
  profile: Profile  {
    about: "Test",
    age: 22
  }
}

 ```
The  showProfile and visits are undefiened.

A bug is in src/query-builder/transformer/DocumentToEntityTransformer.ts:101

```ts
 if (!value) return;
```

**Comment by johnwick2614** [comment]
Can you plz share your SaveRepository function.

const order = new Orders();
order.product = [
      new Product(name, quantity, productAmount)
    ];
await orderRepository.save(order);

i getting null value in array
