### ISSUE TITLE
MYSQL Charset Option

### ISSUE THREAD

**Issue by solarhell** [typeorm/typeorm#390]
I want to save some emoji in database. But it seems that it use utf8 as default connection option.
And i have already set my database to support utf8mb4.
![qq20170407-120014](https://cloud.githubusercontent.com/assets/10279583/24785118/d43bcbaa-1b89-11e7-8c41-75d83a2b2a52.png)
![qq20170407-120023](https://cloud.githubusercontent.com/assets/10279583/24785120/d6a82348-1b89-11e7-9695-2380f606ffb3.png)
![qq20170407-120110](https://cloud.githubusercontent.com/assets/10279583/24785126/e865392c-1b89-11e7-915a-e96f8513d8ab.png)

**Comment by pleerock** [comment]
do you want to set a charset per table? Maybe you simply set charset per database

**Comment by solarhell** [comment]
I want to create db connection with utf8mb4 charset, and my config file is like this
```json
[
  {
    "name": "default",
    "driver": {
      "type": "mysql",
      "host": "localhost",
      "port": 3306,
      "username": "xxxx",
      "password": "xxxx",
      "database": "xxxx",
      "charset": "utf8mb4_unicode_ci"
    },
    "autoSchemaSync": true
  }
]
```
But it doesn't work. And i have checked the previous issue but nobody else meet this issue.

**Comment by pleerock** [comment]
typeorm does not create a database for you. All you need to do is to create a database and specify charset during database creation. Click on "new database" in sequel pro and choose your encoding.

**Comment by solarhell** [comment]
I already have a database created with utf8mb4 encoding and utf8mb4_unicode_ci collation, so i can store emoji in it.
My issue is that when i use typeorm to retrive the record, it doesn't use the utf8mb4 encoding.
So i want to know if there is an option to set charset encoding in config file that i used to create database connection?
Thanks.

**Comment by pleerock** [comment]
Can you try this setup?:

```json
[
  {
    "name": "default",
    "driver": {
      "type": "mysql",
      "host": "localhost",
      "port": 3306,
      "username": "xxxx",
      "password": "xxxx",
      "database": "xxxx",
      "extra": {
          "charset": "utf8mb4_unicode_ci"
      }
    },
    "autoSchemaSync": true
  }
]
```

**Comment by solarhell** [comment]
Thanks for your reply! It works and i will close the issue.
Maybe you can add this example to README to help following people.

**Comment by pleerock** [comment]
Yeah good to have such section in README. You can pass any [underlying driver option](https://github.com/mysqljs/mysql#connection-options) in "extra" property.

**Comment by pmoleri** [comment]
Just wanted to point out that setting `charset` inside the `extra` options is obsolete since commit 6aeda88aeba5165b1c213e9e05c3ceecb70f0426 (July 2017).
Just add the `charset` option directly to `ConnectionOptions`.

**Comment by haroonKhan-10p** [comment]
Can I set it via environment variables?

**Comment by constb** [comment]
> Can I set it via environment variables?

`TYPEORM_DRIVER_EXTRA='{"charset":"utf8mb4_unicode_ci"}'`

**Comment by haroonKhan-10p** [comment]
didn't get it to work. How can I be sure that this variable is set?

**Comment by Zach-Ma** [comment]
If all answer above doesn't help you, you can change the database manually by doing:

`ALTER DATABASE dbname CHARACTER SET utf8 COLLATE utf8_general_ci;`

`ALTER TABLE tbl_name CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

link:
[How to convert an entire MySQL database characterset and collation to UTF-8?
](https://stackoverflow.com/questions/6115612/how-to-convert-an-entire-mysql-database-characterset-and-collation-to-utf-8)

**Comment by Tada5hi** [comment]
You can also use [https://www.npmjs.com/package/typeorm-extension](typeorm-extension) package, to solve this problem.
You can also `create` or `drop` the database specified for the connection.
The package parses the extra parameter `charset` and `characterSet` of the extra parameter (ENV: TYPEORM_DRIVER_EXTRA)
```typescript
import {getConnectionOptions} from "typeorm";
import {createDatabase} from "typeorm-extension";

(async () => {
    const connectionOptions = await getConnectionOptions();

    await createDatabase(connectionOptions, {ifNotExist: true});
    process.exit(0);
})();
````
You can also provide the `charset` and `characterSet` as second parameter to the `createDatabase()` function.
F.e 
- postgres
`createDatabase(connectionOptions, {ifNotExist: true, characterSet: "UTF8"});`
- mysql
`createDatabase(connectionOptions, {ifNotExist: true, charset: "utf8mb4_general_ci", characterSet: "utf8mb4"});`

If you have any questions or concerns feel free to contact me or contribute to the codebase on github :)
