### ISSUE TITLE
Generating migrations on entities with "public" schema explicitly specified fails

### ISSUE THREAD

**Issue by evtuhovdo** [typeorm/typeorm#3907]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.16`

**Steps to reproduce or a small repository showing the problem:**

```ts
import {
    Column,
    Entity,
    PrimaryGeneratedColumn,
} from 'typeorm';

@Entity('blank', {schema: 'public'})
export class Blank {
    @PrimaryGeneratedColumn({
        type: 'integer',
        name: 'id',
    })
    id: number;

    @Column('timestamp with time zone', {
        nullable: false,
        name: 'created_at',
    })
    createdAt: Date;

    @Column('timestamp with time zone', {
        nullable: false,
        name: 'updated_at',
    })
    updatedAt: Date;

    @Column('timestamp with time zone', {
        nullable: true,
        name: 'deleted_at',
    })
    deletedAt: Date | null;
}
```

```ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class initial1553669400616 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "public"."blank" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_5950c5787286cfacfe11ce432b3" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP TABLE "public"."blank"`);
    }

}
```

When run generate migrations i got table create sql code, even if i already migrate db. And after insert changes in model got full create table migration.

**Comment by Kononnable** [comment]
`And after insert changes in model got full create table migration.`
What changes?
Is Db created completely with typeorm? If not could you create db from typeorm(schemaSync) and after disabling it see if same situation occurs with migrations?

**Comment by evtuhovdo** [comment]
@Kononnable full example

**/ormconfig.json**
```json
{
   "type": "postgres",
   "host": "localhost",
   "port": 5432,
   "username": "postgres",
   "password": "postgres",
   "database": "test",
   "synchronize": false,
   "logging": true,
   "entities": [
      "orm/entity/**/*.ts"
   ],
   "migrations": [
      "orm/migration/**/*.ts"
   ],
   "subscribers": [
      "orm/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "orm/entity",
      "migrationsDir": "orm/migration",
      "subscribersDir": "orm/subscriber"
   }
}
```

**/orm/entity/Role.ts** initial entity state
```ts
import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity('role', { schema: 'public' })
export class Role {
  @PrimaryGeneratedColumn({
    type: 'integer',
    name: 'id',
  })
  id: number;

  @Column('character varying', {
    nullable: false,
    unique: true,
    length: 20,
    name: 'name',
  })
  name: string;
}
```

Then run command 
```
ts-node --project ./server/tsconfig.json ./node_modules/typeorm/cli.js migration:generate -n initial
```
typeorm create file in migration folder
**/orm/migration/1554616941608-initial.ts**
```ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class initial1554616941608 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "public"."role" ("id" SERIAL NOT NULL, "name" character varying(20) NOT NULL, CONSTRAINT "UQ_eab36d4e05c0ab7a112841e788d" UNIQUE ("name"), CONSTRAINT "PK_ab841b6a976216a286c10c117f1" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP TABLE "public"."role"`);
    }

}
```

Migrate db
run 
```ts-node --project ./server/tsconfig.json ./node_modules/typeorm/cli.js migration:run```

typeorm create new tables migrations and role, insert in migrations executed migration data.

![image](https://user-images.githubusercontent.com/2404639/55679679-e581ae80-5939-11e9-8acc-01e9cfb4ef77.png)

![image](https://user-images.githubusercontent.com/2404639/55679688-fcc09c00-5939-11e9-8c81-f25d1f96df26.png)

![image](https://user-images.githubusercontent.com/2404639/55679691-0a762180-593a-11e9-931b-edf438ffb882.png)

### MAKE CHANGES
Change Role.ts entity - add field code
**/orm/entity/Role.ts** with new field code
```ts
import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity('role', { schema: 'public' })
export class Role {
  @PrimaryGeneratedColumn({
    type: 'integer',
    name: 'id',
  })
  id: number;

  @Column('character varying', {
    nullable: false,
    unique: true,
    length: 20,
    name: 'name',
  })
  name: string;

  // new field
  @Column('character varying', {
    length: 100,
    name: 'code',
  })
  code: string;
}
```

Then run command 
```
ts-node --project ./server/tsconfig.json ./node_modules/typeorm/cli.js migration:generate -n add_code_field_to_role
```

typeorm create new file in migration folder
**/orm/migration/1554618278294-add_code_field_to_role.ts**
```ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class addCodeFieldToRole1554618278294 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "public"."role" ("id" SERIAL NOT NULL, "name" character varying(20) NOT NULL, "code" character varying(100) NOT NULL, CONSTRAINT "UQ_eab36d4e05c0ab7a112841e788d" UNIQUE ("name"), CONSTRAINT "PK_ab841b6a976216a286c10c117f1" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP TABLE "public"."role"`);
    }

}

```

### result
Second migration **/orm/migration/1554618278294-add_code_field_to_role.ts** got `CREATE TABLE` statement, but expected `ALTER TABLE`. 
If i run ```ts-node --project ./server/tsconfig.json ./node_modules/typeorm/cli.js migration:run``` will return error `error: relation "role" already exists`

### env

PostgreSQL _9.6.9_
TypeOrm _0.2.16_
ts-node _8.0.3_

**Comment by evtuhovdo** [comment]
@Kononnable if found reason.

if use `@Entity('role', { schema: 'public' })` i got this error
but if do not set schema `@Entity('role')` migrations work as well.

**Comment by Flash619** [comment]
I just found this after using `typeorm-model-generator` to create migrations for an existing database. Removing the `{ schema: 'mydatabase' }` fixed this issue.
