### ISSUE TITLE
Define Tree Depth

### ISSUE THREAD

**Issue by raydirty** [typeorm/typeorm#3909]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Linking to the official [documentation](https://typeorm.io/#/tree-entities/working-with-tree-entities) about Trees.

Is it possible to limit the depth in a recursive tree hierarchy?

For example something like that:

```ts
const manager = getManager();
const trees = await manager.getTreeRepository(Category).findTrees({limit: 1});
```

and then the response would look like this:

```json
[{
    "id": 1,
    "name": "a1",
    "children": [{
        "id": 2,
        "name": "a11"
    }, {
        "id": 3,
        "name": "a12"
    }]
}]
```

This could be helpful to "paginate" trees and to improve the performance of APIs.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by johanneslumpe** [comment]
I am also interested in this. Right now the closure table strategy does not  store the tree depth in the table, so without code changes to how the strategy is implemented this probably isn't possible.

**Comment by guiaramos** [comment]
Any workaround for this?
