### ISSUE TITLE
discussion: add support for dotenv files in CLI

### ISSUE THREAD

**Issue by NoNameProvided** [typeorm/typeorm#391]
Storing configuration in the environment separated from code is a well established practice and in most of the time developers use `.env` files to store their configuration options.

TypeORM itself supports loading config from environment variables but the CLI does not. To use the CLI, an `ormconfig.json` must be present.

From docs:
> Note, that to make command line tools to work, you must create a [ormconfig.json] file. - [ref](https://typeorm.github.io/updating-database-schema.html)

This prevents the usage of the CLI to run migrations on the development or on the production environment before starting an app.

I am happy to create a PR for this, if I can get a minimal guidance how would you want to see this in TypeORM.

For reference we use the [motdotla/dotenv](https://github.com/motdotla/dotenv) package.

**Comment by pleerock** [comment]
> To use the CLI, an ormconfig.json must be present.

Maybe cli should be able to read configuration from ENV as well? I did not get a point of having .env file

**Comment by NoNameProvided** [comment]
> Maybe cli should be able to read configuration from ENV as well?

Yes, the ability to read from .env files what I mean under adding support for it in the CLI.

**Comment by pleerock** [comment]
wait wait Im not talking about " ability to read from .env files ", Im talking about just simply read from environment variables. I don't understand why ".env files" are needed at all

**Comment by NoNameProvided** [comment]
> Im talking about just simply read from environment variables.

Yes that can be enough to use the cli with a wrapper script.

> I don't understand why ".env files" are needed at all.

`.env` files are used to simulate environment variables in dev environment. Creating and maintaining enviroment variables manually in a dev machine is inconvenient, the [dotenv](https://github.com/motdotla/dotenv) package help with that by auto-inserting the content of `.env` files as environment variables when your project is starting. 

If the TypeORM CLI doesn't supports `.env` files then every call must be made through a custom script which reads and inserts the environment variables from the `.env` file first and then call the CLI. This step can be prevented if the CLI would know the `.env` file type and load it automatically.

Of course maybe this is not the best way, as some developer could favor some other tool for this job. I think though that it's widely used. (In last month it has been installed [more than 1.5 million](https://yarnpkg.com/en/package/dotenv))

**Comment by pleerock** [comment]
okay this is first time I hear about dotenv and it sounds it is a good idea for typeorm to support such files, so go ahead.

If you desire you can also investigate typeorm config support from `yml` and `xml` formats too (something I have in my long-list of todos). Just need to implement good abstraction for all types of configuration files.

**Comment by slavafomin** [comment]
`.env` support is a "must have" actually. I'm now using it with Sequelize migrations, however, I would like to migrate to TypeORM.

In Sequelize I'm calling `require('dotenv').config();` to load environment variables in `config.js` which is loaded automatically by Sequelize CLI. In TypeORM I can't do this, because it uses JSON instead of JS, so there is no way to inject some additional logic to it.

Here's how my config looks in Sequelize:

```js
require('dotenv').config();

const commonConfig = {
  dialect: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: process.env.DB_PORT || 5432,
  database: process.env.DB_NAME || '',
  username: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || '',
  migrationStorageTableName: 'migrations'
};

module.exports = {
  development: commonConfig,
  production: commonConfig
};
```

So I see two problems here:

1). The TypeORM needs to load environment configuration from `.env` file in the root of the project.
2). There should be a way to reference those environment variables in database connection configuration.

I think it would be great if TypeORM would support JS configuration style additionally, not only JSON (which is very limited — we have to only use hardcoded values).

**Comment by slavafomin** [comment]
I think #373 is partially related to this.

**Comment by NoNameProvided** [comment]
A lot of think happened in the last weeks, so I couldn't really find any time to code, but now things seems to settle so I hope I can give this one a go next weekend.

**Comment by NoNameProvided** [comment]
@pleerock please can you take a look at [NoNameProvided/typeorm#config-loader](/NoNameProvided/typeorm/tree/feature/config-loader)? The code is very WIP but I am interested in you opinion. 

Also as I started to work on this I have noticed a few stuff I want to ask about:

1. There are a few env variables which cannot be set as connection option via the API. What should we do with these, shouldn't `ConnectionOptions` support all environment variable options and vica-versa? Btw this is the two:
    - TYPEORM_LOGGING_FAILED_QUERIE
    - TYPEORM_LOGGING_ONLY_FAILED_QUERIES
   

2. There are a few `ConnectionOptions` option which cannot be set with environment variables, one of them is the `driver.database` option. I don't understand why this hasn't got it's own specific env variable because it's needed for every connection. (I see I can assign it via TYPEORM_DRIVER_EXTRA, but that feels strange as it is a mandatory field.) Shouldn't we add it?
Others are:
    - `dropSchemaOnConnection?: boolean`
    - `usedNamingStrategy?: string|Function`
    - `migrations?: Function[]|string[];`
    - `autoMigrationsRun?: boolean`

3. How handle errors? Custom error class for every type? (You can search for TODO-s in my code to see where I want to throw.)

To test you can run `gulp package` then in node REPL (from project root):

```node
const Manager = require('./build/package/config-loader/ConfigManager').ConfigManager;
const manager = new Manager();
manager.getConfiguration('/path/to/env/.env').then(console.log)
// You should see a partial connection option
```

Example `.env` file: 

```
# Example .env file
# .env files never should be committed, this is an example .env file you can use
# to create your own.

# In Production these env variables will be set from HEROKU dashboard.

# Secret for JWT tokens
JWTSECRET=verysecretmuchencryption

# Debug options, which module should debug
DEBUG=*

# TypeORM options aka PostgresSQL connection options
TYPEORM_DRIVER_TYPE=postgres
DATABASE_URL=postgresql://postgres:root@localhost/gshoppt

TYPEORM_HOST=localhost
TYPEORM_PORT=5432
TYPEORM_USERNAME=postgres
TYPEORM_PASSWORD=admin
TYPEORM_DATABASE=gshoppt

# Azure API key
AZURE_KEY=xxxxx

# Mailgun credentials
MAILGUN_KEY=key-aeeaa6973ac338b0530c89d88c2c66c7
```

Currently I see the following TODOS: 
 
- [ ] finish `ConfigManager`
- [ ] add loader for `ormconfig.json` 
- [ ] refactor to use config manager everywhere
- [ ] add loader for Yaml configuration
- [ ] polish dotenv loader (error handling, etc)
- [ ] write tests

If you think I missed something tell me

**Comment by NoNameProvided** [comment]
> I think it would be great if TypeORM would support JS configuration style additionally, not only JSON (which is very limited — we have to only use hardcoded values).

@slavafomin You can just export the module and import it in your bootstrap code like:

```ts
// config.ts
const commonConfig = {
  driver: {
        type: "mysql",
        host: "localhost",
        port: 3306,
        username: "root",
        password: "admin",
        database: "test"
    },
   entities: [
        __dirname + "/entity/*.js" // here we load all entities from entity directory
    ],
    autoSchemaSync: true
};

 export const developmentConfig = Object.assing({}, commonConfig);
 export const productionConfig = Object.assing({autoSchemaSync: false}, commonConfig);
```

```ts
import {createConnection} from "typeorm";
import { developmentConfig } from './config';

createConnection(developmentConfig).then(connection => {
    // connected. Now you can manipulate your entities!
});
```

Anyway it's easy to implement this with the new approach, so I will add this as well.

**Comment by slavafomin** [comment]
Thanks @NoNameProvided , but how do I do this with CLI and migrations?

**Comment by NoNameProvided** [comment]
> but how do I do this with CLI and migrations?

Not yet, but we will be able to do this once these feature will  be merged.

**Comment by pleerock** [comment]
@NoNameProvided 

answers to your questions:

1. yes
2. if there is no env for driver.database then it must be added, looks like i missed it
3. yes you can do that

You missed `xml` support. This is not popular choice, but it would be great if orm can support all possible formats 😆 

Also probably you can create a separate module for what you are doing, typeorm will only use it to load configuration, e.g.:

`loadConfiguration("ormconfig")` - then it automatically load ormconfig.json/.yaml/.yml/.xml/.env from root (using app root package).

This is at least what I have planned to do before you suggested a help.

Because I need this in one another package - typestack.

**Comment by NoNameProvided** [comment]
Okay, I will reorganize it into a package, just created a repo for it: [NoNameProvided/conly](https://github.com/NoNameProvided/conly)

**Comment by NoNameProvided** [comment]
I am running really low on time 😞 , hard to find any 🕐 , hopefully I can do this this in the following next few weeks.

**Comment by pleerock** [comment]
after deep investigation I found that it probably wont be possible to have such package because some of formats (especially xml) have too much complicated structure and it wont be possible to create a lib that will return everything in a single json object format.

So I decided to implement xml/yml/env/json support right in the package. Its available in `0.1.0.alpha-8`. Thanks for your efforts @NoNameProvided

**Comment by vuk-nikolic** [comment]
> `.env` support is a "must have" actually. I'm now using it with Sequelize migrations, however, I would like to migrate to TypeORM.
> 
> In Sequelize I'm calling `require('dotenv').config();` to load environment variables in `config.js` which is loaded automatically by Sequelize CLI. In TypeORM I can't do this, because it uses JSON instead of JS, so there is no way to inject some additional logic to it.
> 
> Here's how my config looks in Sequelize:
> 
> ```js
> require('dotenv').config();
> 
> const commonConfig = {
>   dialect: 'postgres',
>   host: process.env.DB_HOST || 'localhost',
>   port: process.env.DB_PORT || 5432,
>   database: process.env.DB_NAME || '',
>   username: process.env.DB_USER || 'postgres',
>   password: process.env.DB_PASSWORD || '',
>   migrationStorageTableName: 'migrations'
> };
> 
> module.exports = {
>   development: commonConfig,
>   production: commonConfig
> };
> ```
> 
> So I see two problems here:
> 
> 1). The TypeORM needs to load environment configuration from `.env` file in the root of the project.
> 2). There should be a way to reference those environment variables in database connection configuration.
> 
> I think it would be great if TypeORM would support JS configuration style additionally, not only JSON (which is very limited — we have to only use hardcoded values).

I know this is an old and closed ticket, but in case somebody wants to use `.env` files, I'm using this same approach (actually that got me thinking). 
I do have `ormconfig.js` instead of `ormconfig.json` and in there I have `require('dotenv').config({ path: fileName });` where fileName can be `.env` or any other file.

Here is my whole `ormconfig.js` that is in the root of the project:
```javascript
const fs = require('fs');
const ENVIRONMENT = process.env.NODE_ENV || 'development' ;
const fileName = `.env.${ENVIRONMENT}`;

if (fs.existsSync(fileName)) {
    require('dotenv').config({ path: fileName });
} else {
    require('dotenv').config({ path: ".env.example" });
}
const database = {
    type: process.env.DATABASE_TYPE,
    host: process.env.DATABASE_HOST,
    port: process.env.DATABASE_PORT,
    username: process.env.DATABASE_USERNAME,
    password: process.env.DATABASE_PASSWORD,
    database: process.env.DATABASE_DB,
    synchronize: process.env.DATABASE_SYNCHRONIZE,
    logging: process.env.DATABASE_LOGGING,
};
const config = {
    "type": database.type,
    "host": database.host,
    "port": database.port,
    "username": database.username,
    "password": database.password,
    "database": database.database,
    "synchronize": database.synchronize,
    "logging": database.logging,
    "entities": [
        "dist/entity/**/*.js"
    ],
    "seeds": [
        "dist/seeds/**/*.seed.js"
    ],
    "migrations": [
        "dist/migration/**/*.js"
    ],
    "subscribers": [
        "dist/subscriber/**/*.js"
    ],
    "cli": {
        "entitiesDir": "src/entity",
        "migrationsDir": "src/migration",
        "subscribersDir": "src/subscriber"
    }
};

if (process.env.NODE_ENV === 'production') {
    config['extra'] = {
        ssl: true
    }
}
module.exports = config;
```

**Comment by baclv** [comment]
@vuk-nikolic I copied your `ormconfig.js` but I don't know why `dotenv` loaded `.env.development` but overridden by `.env` 😢

**Comment by vuk-nikolic** [comment]
> @vuk-nikolic I copied your `ormconfig.js` but I don't know why `dotenv` loaded `.env.development` but overridden by `.env` 😢

hey @baclv look these two lines:
```
const ENVIRONMENT = process.env.NODE_ENV || 'development' ;
const fileName = `.env.${ENVIRONMENT}`;
```
you can change that to just `const fileName = '.env'` to load only .env
in our project we got different .env files so it's loading .env.development or .env.test etc depending on the process.env.NODE_ENV. I just copy pasted the code without changing that.

hope that helps.

**Comment by baclv** [comment]
@vuk-nikolic thank you 👍   I find out that `typeorm` auto load `.env` after `dotenv` 😭 
https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#creating-a-new-connection-from-the-configuration-file
