### ISSUE TITLE
JDBC driver implementation for GraalVM

### ISSUE THREAD

**Issue by Thihup** [typeorm/typeorm#3911]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `other`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

It would be possible to implement a layer to communicate with JDBC driver while using GraalVM?

**Comment by pleerock** [comment]
I never heard about this technology and don't know the answer. Not sure if anyone can answer your question here. You need to explore this question on your own.
