### ISSUE TITLE
Cannot set embedded entity to null

### ISSUE THREAD

**Issue by adamalfredsson** [typeorm/typeorm#3913]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Check out this small repository: https://github.com/nomadoda/typeorm-embedded-bug

I have an embedded entity:
```
export class Salary {
  @Column("decimal", { nullable: true })
  public amount: number;
}
```

And I'm using it in this entity:
```
@Entity()
export class Employee extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column(() => Salary)
  salary?: Salary | null;
}
```

Consider this:
```
createConnection()
  .then(async connection => {
    await connection.synchronize(true);
    const salary = new Salary();
    salary.amount = 120;
    const employee = Employee.create({
      salary
    });
    await employee.save();
    console.log("Saved a new employee with id: " + employee.id);

    console.log("Set salary to null and save");
    employee.salary = null;
    await employee.save();

    console.log("Get employee");
    await employee.reload();
    console.log(employee.salary);
    // Salary { amount: '120' }
  })
  .catch(error => console.log(error));
```

**Expected outcome**

Setting salary to null should set all embedded fields in database to null.

**Actual outcome**

Salary did not change on update

**Comment by holm** [comment]
I ran into a bug today that was caused by this. It's surprising that you cannot set an embedded object to null and have all columns be null. It seems to just be ignored.

**Comment by vincentbavitz** [comment]
Seen this also. Really against my preference to collapse embedded entities to the top-level entity, but that's what I've had to do for now.

**Comment by khaelys** [comment]
> As well as this, if all embedded columns are null on load, it's not possible to use the field in the top-level entity as a check.
> 
> e.g. if I had an embedded `Address` entity, the absence of address data can't be checked simply with `entity.address`. Each field in the embedded entity needs to be checked: `entity.address.lineOne`, `entity.address.lineTwo`, etc.
> 
> This isn't exactly the same problem as this issue, but I feel it's in the same realm, where it would be nice to be able to read/write `null` from/to the columns in the embedded entity through the top-level entity.

That is true and leads to a subtle bug in my case. Unfortunately, there is no `transformer` option on `ColumnEmbeddedOptions`, so I came up with this solution.

Firstly we need a function that returns null when all object properties are null.
```ts
export function asNullOnNullProperties<T>(obj: T): T | null {
  for (const key in obj) {
    if (obj[key] != null) {
      return obj;
    }
  }
  return null;
}
```

Now we can use an `@AfterLoad()` listener to modify the embedded entity value.

```ts
@AfterLoad()
handleEmbeddedEntities() {
  this.myEmbeddedEntity = asNullOnNullProperties(this.myEmbeddedEntity);
}
```

Hope it helps 👍
