### ISSUE TITLE
Default values support for mongodb

### ISSUE THREAD

**Issue by elie222** [typeorm/typeorm#3914]
**Issue type:**

bug report

**Database system/driver:**

`mongodb`

**TypeORM version:**

`latest`

**Steps to reproduce or a small repository showing the problem:**

```ts
  // active, draft, archive
  @Column({ type: 'string', default: 'draft' })
  state: string
```

Upon insert, the document does not receive the default value of `draft`.

**Comment by rustamwin** [comment]
Duplicate of #3799
