### ISSUE TITLE
React Native: null is not an object (NativeModules[SQLite][method])

### ISSUE THREAD

**Issue by matheusgrieger** [typeorm/typeorm#3915]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have just created a new project using `react-native init Project --template typescript` (which is the official way of starting a new project with TypeScript now), configured and installed everything, but the app fails when creating a connection. Here is a screenshot of what shows up:

![Screenshot_1553805863](https://user-images.githubusercontent.com/6992464/55191509-241ca980-5181-11e9-9494-5c47bb59ff7a.png)

Config files:

**babel.config.js**
```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    'babel-plugin-transform-typescript-metadata',
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    // ['@babel/plugin-proposal-class-properties', { loose: true }]
  ]
};
```

(class-properties is commented due to another issue with [Babel 7 and Flow](https://github.com/facebook/react-native/issues/21154#issuecomment-425433797))

**App.tsx#connect**
```ts
  async connect() {
    await createConnection({
      type: 'react-native',
      database: 'gestor',
      location: 'default',
      logging: ['error', 'query', 'schema'],
      synchronize: true,
      entities: Object.values(models) // this evaluates to an array of entity classes
    });
    Alert.alert('hello!');
    this.setState({ loading: false });
  }
```

**Comment by matheusgrieger** [comment]
Nevermind. For anyone in the future with the same error, using `react-native link` or `react-native install` *does not* work with react-native-sqlite-storage. You have to add the dependencies manually.

**Comment by prasad456** [comment]
does not work for me
