### ISSUE TITLE
Any way to set the timezone of ormlogs.log file ?

### ISSUE THREAD

**Issue by SunshowerC** [typeorm/typeorm#3918]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.11` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
what I got in `ormlogs.log` is `Z` timezone 
```
[2019-03-29T08:05:24.633Z][QUERY]: COMMIT
```
**any way to set the timezone of `ormlogs.log` file ?**
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
Date is generated by `new Date().toISOString()` and it's not customizable by options. If you wan't to change it you probably need to implement your own custom logger(based on FileLogger).

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
