### ISSUE TITLE
how to write query with foreign key relationship

### ISSUE THREAD

**Issue by prolink007** [typeorm/typeorm#392]
I have the following two tables and i want to query the Comic table for all Comics that are from a specific Series.

If i have the `fancyId` of the Series, how can i get all Comics that are in that Series?

Right now i am just running a `find` to get the id of the series that matches the `fancyId` and then doing another `find` to get all the comics that match the found id. Seems like there is a better way to do this.

```
@Entity()
export class Comic {

    @ManyToOne(type => Series, series => series.comics)
    public series: Series;
}
```

```
@Entity()
export class Series {

    @Column("int")
    public fancyId: number;

    @OneToMany(type => Comic, comic => comic.series)
    public comics: Array<Comic>;
}
```

**Comment by pleerock** [comment]
Did you try `QueryBuilder` ?

```ts
const comicsWithSeries = connection.getRepository(Comic)
     .createQueryBuilder("comic")
     .leftJoinAndSelect("comic.series")
     .getMany();
```

**Comment by pleerock** [comment]
same from the inverse side. You don't need `fancyId` in series

**Comment by prolink007** [comment]
`fancyId` is a unique Id given to a series external from me. I do need it. It is not the same as the primary id that is auto incremented.

**Comment by pleerock** [comment]
your `fancyId` should be a relation if you want orm to map entities using `.leftJoinAndSelect`. Having simple column won't work.

**Comment by prolink007** [comment]
Here is how I would do this with a SQL query.

`select * from comic where comic.series=(select series.id from series where
series.fancyid=21493)`

What you suggested will not work because at no point am I giving it the
unique Id that defines which series I am interested in.

**Comment by pleerock** [comment]
I still didnt quite understand what exactly you want. Do you want to generate following query:

```sql
`select * from comic where comic.series=(select series.id from series where
series.fancyid=21493)`
```

If you do, then I think you can do it via query builder. Create first query using query builder, and second (subquery) query using second query builder, then use in first query builder `getSql` of the second query builder in a `.where` expression of the first query builder.

**Comment by prolink007** [comment]
Yes. I was just wanting to see if there was a way to do it without multiple
selects.

**Comment by prolink007** [comment]
@pleerock Can you show me how you would do what you are suggesting with the query builder? I am not able to get it to work.

**Comment by pleerock** [comment]
As of `0.1.0-alpha.23` there are lot of useful methods to create subqueries using more elegant api. See [there](https://github.com/typeorm/typeorm/blob/0b4e3ff5eb52ca05f0fe9e9fe5d7b6e1b575863a/test/functional/query-builder/subquery/query-builder-subquery.ts#L74) how to use subqueries. Some of examples are:

```ts

        const posts = await connection.getRepository(Post)
            .createQueryBuilder("post")
            .where(qb => {
                const subQuery = qb.subQuery()
                    .select("user.name")
                    .from(User, "user")
                    .where("user.registered = :registered")
                    .getQuery();
                return "post.title IN " + subQuery;
            })
            .setParameter("registered", true)
            .getMany();
```

So you can implement your task using syntax above. Let me know if you still have questions.
