### ISSUE TITLE
Connecting to mssql server

### ISSUE THREAD

**Issue by trithesh** [typeorm/typeorm#3924]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Done everything as shown in examples of typeorm website but i'm getting error of localhost dosent found any port number. I have checked port numbers also. Please provide a answer

**Comment by vlapo** [comment]
Hey @trithesh. Please provide more info: connection configuration, full text of error and we will try help you. But from your modest description I think this is problem on your site.

**Comment by Kononnable** [comment]
Closing as no response from the author.
