### ISSUE TITLE
Which reference should I better use in that case?

### ISSUE THREAD

**Issue by Blitss** [typeorm/typeorm#3928]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Let's suppose I have 2 models, `LocalizedString` and `Answer`. `LocalizedString` contains three fields: `locale`, `key`, `value`. `Answer` should connect `LocalizedString` by `LocalizedString.key` but I can't figure a way to do this. `Answer` may contain multiple locale strings which may be connected by `key`.

Which decorator should I use to reference `key`? So I don't have to add dedicated field to `LocalizedString` like:
```typescript
// What I'm trying to avoid
@ManyToOne(type => Answer, d => d.locales)
  public answer: Question;
```
What I'm trying to achieve
```typescript
@Entity()
export class LocalizedString extends BaseEntity {
  @Column()
  public key: string;

  @Column({ default: 'en_US' })
  public locale: string = 'en_US';

  @Column({ default: '' })
    public value: string;
  }
}

@Entity()
export class Answer extends BaseEntity {
   // *How do I reference LocalizedString here by its key so I can load it later with relations?*
   @Column({ nullable: true })
   public localeKey: string;
}
```

**Comment by Kononnable** [comment]
I'm not sure what you're trying to achieve - you want to represent OneToMany relationship without ManyToOne decorator?

**Comment by Blitss** [comment]
@Kononnable I wanna join multiple `LocalizedString` entities using `key` field. As I am aware, this is not possible yet, so I dealt with it another way.
Something like:
`SELECT * FROM answer INNER JOIN localized_string ls on question.localeKey = ls."key"` is what I was trying to achieve.

**Comment by Kononnable** [comment]
Oh, you want to add a 'relation'(answer<->localized_string) based on joining through another table(question). Typeorm decorators like @ManyToOne represents relations in databse - such relations can connect only two tables.
You can however add property with getter in your entity class which would get the data you want.

**Comment by rustamwin** [comment]
no answer from the author, closing.

**Comment by Blitss** [comment]
never mind, figured it out.

Should use OneToMany – ManyToOne kind of relation in that case.
I was dumb to see what they were really doing.
