### ISSUE TITLE
setting lock_timeout for transactions of explicit locks?

### ISSUE THREAD

**Issue by NorthTommy** [typeorm/typeorm#3929]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hi,
how can I specify the lock timeout then using e.g. pessimistic write lock or transactions in general.
Normally using postgres I would setup it by "SET  lock_timeout = '1s'" (locally within transaction scope) or globally for the connection.
I tried it with "extras" connection option, but this didn't work. The generated "SELECT... FOR UPDATE" blocked much longer than the specified time.
Is there any possibility next to executing the statement above for each transaction manually using the queryRunner?
Thx
Thomas

**Comment by imnotjames** [comment]
You can always set those parameters yourself before starting operations.  This isn't part of the current API & isn't a widely supported feature across databases.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by dhermes** [comment]
So for those curious I went a bit deeper to figure this out: https://github.com/brianc/node-postgres/issues/983#issuecomment-736075608

You can set `lock_timeout` and `statement_timeout` via

```
    extra: {
      options: '-c lock_timeout=400ms',
      statement_timeout: 500,
    },
```

and can expand that out more for any runtime configuration field (https://www.postgresql.org/docs/12/runtime-config-client.html)

**Comment by dhermes** [comment]
> You can always set those parameters yourself before starting operations. This isn't part of the current API & isn't a widely supported feature across databases.

This is sort of possible, though requires an "on create" hook to run for every connection in the pool.
