### ISSUE TITLE
Dropbox-like folder structure with nested file count

### ISSUE THREAD

**Issue by driescroons** [typeorm/typeorm#3930]
**Issue type:**

[X] question  
[ ] bug report  
[ ] feature request  
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`  
[ ] `mongodb`  
[ ] `mssql`  
[ ] `mysql` / `mariadb`  
[ ] `oracle`  
[x] `postgres`  
[ ] `cockroachdb`  
[ ] `sqlite`  
[ ] `sqljs`  
[ ] `react-native`  
[ ] `expo`

**TypeORM version:**

[X] `latest`  
[ ] `@next`  
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi guys, I've been struggling to build a dropbox-like feature. Let's say you have a folder structure with files & nested folders. I want to be able to count all of the files in all my nested folders. Following example should be returned by my query:

```
const dropbox = {
  id: 1,
  folders: [
    {
      id: 2,
      folders: [
        {
          id: 3,
          folders: [],
          files: [
            {
              name: "subSubFile"
            }
          ],
          parent: 2,
          fileCount: 1
        }
      ],
      files: [
        {
          name: "subFile"
        }
      ],
      parent: 1,
      fileCount: 2
    }
  ],
  files: [
    {
      name: "file"
    }
  ],
  parent: null,
  fileCount: 3
};
```

# Folder entity
```
@Entity()
@Tree('closure-table')
export class Folder {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column()
    description: string;

    // @ManyToOne(type => Folder, folder => folder.folders)
    @TreeParent()
    parent: Folder;

    // @OneToMany(type => Folder, folder => folder.parent)
    @TreeChildren()
    folders: Folder[];

    @OneToMany(type => File, file => file.folder)
    files: File[];

    // virtual?
    fileCount: number;
}
```

# File entity
```
@Entity()
export class File {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToOne(() => Folder, folder => folder.files)
    folder: Folder;
}
```

# The query
experiment with flat list & only 1 level deep:
```
const queryBuilder = folderRepository.createDescendantsQueryBuilder('folder', 'closureFolder', folder);

const [childFolders, count] = await queryBuilder
  .innerJoinAndSelect('folder.files', 'file')
  .loadRelationCountAndMap('folder.fileCount', 'folder.files', 'file')
  .take(take)
  .skip(skip)
  .getManyAndCount();
```
  
The query above only returns the files within parents folder. However, I'd like to get the count of nested files within folders on each level. 

Please do not copy and paste above examples, they're untested examples to clarify my question! If I get this sorted, I'll make an example repo out of this. I'm sure lots of people have struggled with something similar.

**Comment by driescroons** [comment]
I'm also open to not using the tree repository, as it seems like some of the functionality is still missing. https://github.com/typeorm/typeorm/issues/193

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
