### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ybchoo** [typeorm/typeorm#3936]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>
Hi Gurus at typeorm,

I tried typeorm to update but it does not override item instead it created a new document.
When I tried findOne or find using Id, result is always null.
Can someone please kindly provide samples so that I can use typeorm at ease on mongodb?

**Comment by ybchoo** [comment]
This will not work for update.
x.hpnumber = request.body.hpnumber;
return  this.xRepository.save ( x );

**Comment by premalatha-bv** [comment]
when am trying to update the many to many relations tables. It is getting updated successfully, but the relation mapping table data gets cleared.

Am I doing anything wrong.

var parentTableRepo = createConnection().getRepoistory('parentTable');
var parentTable = {
    id: 1,
    name: 'xyz',
   Childs: {
      id: 2,
      name: 'abc'
   }
}
parentTableRepo.save(parentTable); //saves successfully
// the mapping table parentTable_childTable data is cleared. which has the parentTable id and child Table id.

**Comment by vlapo** [comment]
Closing as no description of problem. Feel free reopen with description and formatted code.
