### ISSUE TITLE
Unable to delete subordinate relation entity when saving parent entity

### ISSUE THREAD

**Issue by superical** [typeorm/typeorm#3938]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

My intention was to remove the subordinate entities in a relation from the parent entity. 

For example, I've a `Photo` entity which has a one-to-many relation setup with another entity `MetaData`. So, when I retreive a `Photo` entity with `MetaData` relation, the `Photo` entity should have a shape like this:

```ts
    const photoEntity = this.photoRepository.findOne({where: {id: 5}, relations: ['metaData'])
    photoEntity: {
       file: 'someimage.jpg',
       metaDatas: [
          {
             type: 'date',
             data: '12-12-2000'
          },
          {
             type: 'location',
             data: '123.00 123.00'
          }
       ]
    }
```

Basically, the `metaDatas` property in `Photo` entity will be an array. My intention is to remove all `MetaData` from the `Photo` entity.

What I did was simply by setting the array of `photoEntity.metaDatas` to an empty array and then save `photoEntity` like so:

```ts
    const photoEntity = this.photoRepository.findOne({where: {id: 5}, relations: ['metaData'])
    // One photo can have many metadata rows of information in photoEntity.metaDatas
    // Photo entity has a one-to-many relationship setup with MetaData entity
    photoEntity.metaDatas = []   //  Remove all metaDatas in photoEntity
    
    this.photoRepository.save(photoEntity)   // Throws error that ER_BAD_NULL_ERROR: Column 'photoId' cannot be null
```

However, this throws an error that `Column 'photoId' cannot be null`.  This is because instead of running a `DELETE` query, the SQL TypeORM did an `UPDATE` this:

```sql
sql: 'UPDATE `metaData` SET `photoId` = NULL, `updatedAt` = CURRENT_TIMESTAMP WHERE `metaDataId` = `123` }
```

Shouldn't a `DELETE` query be run instead of an update one?
In this case, how can I remove the `MetaData `entities from the `Photo `entity?

**Comment by Kononnable** [comment]
Can you provide your entity definitions? Without them we have to guess how exactly they're defined and which statement should be used.

**Comment by amiiit** [comment]
I'm facing a similar issue when updating the instances on the Many side of a One to Many relation. When setting `one.many = []` seems like typeorm is trying to set `oneId` to null instead of just deleting this stuff. I'm using postgres.

The relevant part of my code is:

```
@Entity()
export class Event extends BaseEntity {
  @PrimaryGeneratedColumn("uuid")
  id: number

   @OneToMany(type => EventOccurrence, occurrence => occurrence.event, {
    cascade: true
  })
  occurrences: Promise<EventOccurrence[]>

  updateOccurrences() {
    const occurences = []
    const occ = new EventOccurrence()
    occ.during = `[${this.time.start},${this.time.end}]`
    occurences.push(occ)

    occurences.forEach(occ => {
      occ.start = this.time.start
      occ.end = this.time.end
      occ.event = Promise.resolve(this)
    })

    this.occurrences = Promise.resolve(occurences)
    return
  }
}
```

Then running `event.updateOccurrences()` and then saving, instead of removing the existing `event.occurrences` it seems like it tries to break the relation by setting eventId to null, which is not what I wanted.

Is there a way to make typeorm delete the old `many`s and replace them with the new one?

Thanks

**Comment by Kononnable** [comment]
I think you're looking for this: https://github.com/typeorm/typeorm/issues/1460

**Comment by brau0060** [comment]
@amiiit I'm having the same issue, what did you do to fix this. I have tried onUpdate: 'CASCADE' but it still adds null to the old many's and doesn't delete them?

**Comment by Nemolo** [comment]
i'm also having the same issue, and adding onUpdate: 'CASCADE' does not work

**Comment by ericmartinezr** [comment]
I have the same issue. I did "solve" it by deleting the property instead of assigning an empty array. The problem persists if you remove one of many elements and the array is not empty.

**Comment by crutch12** [comment]
It really sucs :(

**Comment by esmoney** [comment]
하.. 진짜 빡침..

**Comment by greenreign** [comment]
Any advice on this issue @pleerock?  I know it's always been this way (ie typeorm will not handle it) but maybe just updating this issue with that direction would help.  Then we know it's not something we've misconfigured.  We have to manage it ourselves.

**Comment by shindiogo** [comment]
Hi @greenreign 
I have the same problem. Did you find the solution?

**Comment by yleflour** [comment]
For anyone still looking for a fix, here is a patch to correct this. Use it with patch-package.

https://gist.github.com/yleflour/0bda286aef0b80c16000ae7c93107178

I don't think I will be opening an official PR with this change as it would be an undocumented cascading effect. A proper solution should require its own configuration parameter in the OneToMany relationship decorator

**Comment by shindiogo** [comment]
> For anyone still looking for a fix, here is a patch to correct this. Use it with patch-package.
> 
> https://gist.github.com/yleflour/0bda286aef0b80c16000ae7c93107178
> 
> I don't think I will be opening an official PR with this change as it would be an undocumented cascading effect. A proper solution should require its own configuration parameter in the OneToMany relationship decorator

Hi @yleflour ,

Thanks for you sugestion. I tried to implement it, but i get the same error.
I will share with you:

**My package edited**
![image](https://user-images.githubusercontent.com/14137669/91560343-9a52ac00-e931-11ea-8cde-676e189c3c38.png)

**Team entity**
![image](https://user-images.githubusercontent.com/14137669/91560400-b9513e00-e931-11ea-9394-45dfe9b75715.png)

**Team Element**
![image](https://user-images.githubusercontent.com/14137669/91560435-c66e2d00-e931-11ea-96a5-742e3def943c.png)


Can you help me?

**Comment by yleflour** [comment]
@shindiogo My check uses the `!isNullable` on the FK to know if it has to be deleted which might not be for the best.
Can you check the `relation.inverseRelation.isNullable` value at runtime ?

I believe that adding the option `nullable: false` might fix your issue.

**Comment by Silventino** [comment]
Any updates?

**Comment by douglasgsouza** [comment]
I used **orphanedRowAction** and it worked for me.

Parent:
```
@OneToMany(() => ConfiguracaoCotacaoDetalhe, detalhe => detalhe.configuracaoCotacao, {
        cascade: true
    })
    detalhes?: ConfiguracaoCotacaoDetalhe[];
```

Child:
```
    @ManyToOne(() => ConfiguracaoCotacao, config => config.detalhes, {orphanedRowAction: 'delete'})
    @JoinColumn({name: 'configuracaoCotacaoId'})
    configuracaoCotacao: ConfiguracaoCotacao;
```

**Comment by stefda** [comment]
Thanks @douglasgsouza, your suggestion works well! Here's the [doc](https://github.com/typeorm/typeorm/blob/master/docs/relations.md#relation-options) for anyone interested.

As far as I can tell, this solves it and the issue and can be closed?

**Comment by shindiogo** [comment]
> I used **orphanedRowAction** and it worked for me.
> 
> Parent:
> 
> ```
> @OneToMany(() => ConfiguracaoCotacaoDetalhe, detalhe => detalhe.configuracaoCotacao, {
>         cascade: true
>     })
>     detalhes?: ConfiguracaoCotacaoDetalhe[];
> ```
> 
> Child:
> 
> ```
>     @ManyToOne(() => ConfiguracaoCotacao, config => config.detalhes, {orphanedRowAction: 'delete'})
>     @JoinColumn({name: 'configuracaoCotacaoId'})
>     configuracaoCotacao: ConfiguracaoCotacao;
> ```

Works here!

Thanks, i think this can be closed.

**Comment by imnotjames** [comment]
Closing as it seems this has been resolved.

**Comment by maximosdrr** [comment]
> I used **orphanedRowAction** and it worked for me.
> 
> Parent:
> 
> ```
> @OneToMany(() => ConfiguracaoCotacaoDetalhe, detalhe => detalhe.configuracaoCotacao, {
>         cascade: true
>     })
>     detalhes?: ConfiguracaoCotacaoDetalhe[];
> ```
> 
> Child:
> 
> ```
>     @ManyToOne(() => ConfiguracaoCotacao, config => config.detalhes, {orphanedRowAction: 'delete'})
>     @JoinColumn({name: 'configuracaoCotacaoId'})
>     configuracaoCotacao: ConfiguracaoCotacao;
> ```

Still working, thanks mate !

**Comment by LapX** [comment]
> I used **orphanedRowAction** and it worked for me.
> 
> Parent:
> 
> ```
> @OneToMany(() => ConfiguracaoCotacaoDetalhe, detalhe => detalhe.configuracaoCotacao, {
>         cascade: true
>     })
>     detalhes?: ConfiguracaoCotacaoDetalhe[];
> ```
> 
> Child:
> 
> ```
>     @ManyToOne(() => ConfiguracaoCotacao, config => config.detalhes, {orphanedRowAction: 'delete'})
>     @JoinColumn({name: 'configuracaoCotacaoId'})
>     configuracaoCotacao: ConfiguracaoCotacao;
> ```

Thanks that was the solution for my problem !
