### ISSUE TITLE
Using TypeORM with custom mapping to an existing DB structure

### ISSUE THREAD

**Issue by mremond** [typeorm/typeorm#3939]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Question**

Is there a way to use TypeORM without schema creation, with a custom mapping to plug it to an existing DB?

The goal is to have the flexibility of either letting the user of the project have the database created, or use one existing database (for example for user base).

Thanks!

**Comment by Kononnable** [comment]
You can disable schema sync - then no structure of database tables will be changed. You will be able to use typeorm just fine if your entity models are compatible with tables in db.
