### ISSUE TITLE
Missing mongodb driver error in postgres project

### ISSUE THREAD

**Issue by mkatrenik** [typeorm/typeorm#394]
I've project running typeorm 0.0.11 with postgres, when I upgrade to 0.1.0-alpha, it errs with missing mongodb driver error.

**Comment by pleerock** [comment]
right if you want to use `next` version you have to install mongodb driver for now `npm i mongodb --save`. There are few problems needs to be solved to fix this issue.

**Comment by pleerock** [comment]
this is already fixed in latest alpha versions.
