### ISSUE TITLE
Unique index for multiple tables

### ISSUE THREAD

**Issue by EvgeniyZo** [typeorm/typeorm#3940]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

```

@Entity()
export abstract class Actor {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;
}

@Entity()
export class Organization extends Actor {
}

@Entity()
export class User extends Actor {
}

```
Field "name" must be unique for all tables

I tried "@Index" and "@Unique" in different places, but it creates separate indexes

**Comment by hcesar** [comment]
Do you want one unique key for **each** table or you want one that is **shared** by all tables?

The first one can be achieved by adding `@Unique` at Actor class:
```
@Entity()
@Unique(["name"])
export abstract class Actor { ... }
```

The second one is impossible at database level. You can have that although, by using inheritance (https://github.com/typeorm/typeorm/blob/master/docs/entity-inheritance.md#single-table-inheritance):
```
@Entity()
@Unique(["name"])
@TableInheritance({ column: { type: "varchar", name: "type" } })
export abstract class Actor {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;
}

@ChildEntity()
export class Organization extends Actor {}

@ChildEntity()
export class User extends Actor {}
```

In this case you would have just one table which would be shared by all types, and the name would be unique among all types as well.
