### ISSUE TITLE
Use Case statement inside queryBuilder-2

### ISSUE THREAD

**Issue by noteasybutclear** [typeorm/typeorm#3941]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16` (or put your version here)

I'd like to use orderby in order of the values I want using the CASE WHEN statement.

I've already checked issue #3167 and we've gone ahead and there's an error. 

My code is as follows.

```
result = await getConnection()
          .getRepository(Post)
          .createQueryBuilder("post")
          .orderBy(_sortField, _sortOrder)
          .skip(_offset)
          .take(_limit)
          .leftJoinAndSelect("post.user", "user")
          .leftJoinAndSelect("post.products", "product")
          .leftJoinAndSelect("product.brand", "brand")
          .orderBy(`CASE WHEN product.category='SOMETHING' THEN 1 END`, "DESC") // test code, not work!
          .getMany();
```

Error codes are as follows:

```
Error: "CASE WHEN product" alias was not found. Maybe you forgot to join it?
```

Please help me.

**Comment by hcesar** [comment]
I did this and it worked well:
```
const posts = await conn.manager
      .createQueryBuilder("post", "p")
      .addSelect("CASE WHEN p.id % 2 = 0 then -p.id else p.id end", "_rank")
      .leftJoinAndSelect("p.parent", "pr")
      .skip(2)
      .take(100)
      .orderBy('_rank')
      .getMany();
```

It generated two queries:
```
query: SELECT DISTINCT `distinctAlias`.`p_id` as "ids_p_id", `distinctAlias`._rank FROM (SELECT `p`.`id` AS `p_id`, `p`.`name` AS `p_name`, `p`.`description` AS `p_description`, `p`.`parentId` AS`p_parentId`, `pr`.`id` AS `pr_id`, `pr`.`name` AS `pr_name`, `pr`.`description` AS `pr_description`, `pr`.`parentId` AS `pr_parentId`, CASE WHEN `p`.`id` % 2 = 0 then -p.id else `p`.`id` end AS `_rank` FROM `post` `p` LEFT JOIN `post` `pr` ON `pr`.`id`=`p`.`parentId`) `distinctAlias` ORDER BY `distinctAlias`._rank ASC, `p_id` ASC LIMIT 100 OFFSET 2

query: SELECT `p`.`id` AS `p_id`, `p`.`name` AS `p_name`, `p`.`description` AS `p_description`, `p`.`parentId` AS `p_parentId`, `pr`.`id` AS `pr_id`, `pr`.`name` AS `pr_name`, `pr`.`description` AS `pr_description`, `pr`.`parentId` AS `pr_parentId`, CASE WHEN `p`.`id` % 2 = 0 then -p.id else `p`.`id` end AS `_rank` FROM `post` `p` LEFT JOIN `post` `pr` ON `pr`.`id`=`p`.`parentId` WHERE `p`.`id` IN (4, 2, 1, 3, 5, 7, 9) ORDER BY _rank ASC
```

And the result is correct.

**Comment by vlapo** [comment]
@noteasybutclear could you please enable logging and post generated query?

**Comment by ricky300300** [comment]
> I did this and it worked well:
> 
> ```
> const posts = await conn.manager
>       .createQueryBuilder("post", "p")
>       .addSelect("CASE WHEN p.id % 2 = 0 then -p.id else p.id end", "_rank")
>       .leftJoinAndSelect("p.parent", "pr")
>       .skip(2)
>       .take(100)
>       .orderBy('_rank')
>       .getMany();
> ```
> 
> It generated two queries:
> 
> ```
> query: SELECT DISTINCT `distinctAlias`.`p_id` as "ids_p_id", `distinctAlias`._rank FROM (SELECT `p`.`id` AS `p_id`, `p`.`name` AS `p_name`, `p`.`description` AS `p_description`, `p`.`parentId` AS`p_parentId`, `pr`.`id` AS `pr_id`, `pr`.`name` AS `pr_name`, `pr`.`description` AS `pr_description`, `pr`.`parentId` AS `pr_parentId`, CASE WHEN `p`.`id` % 2 = 0 then -p.id else `p`.`id` end AS `_rank` FROM `post` `p` LEFT JOIN `post` `pr` ON `pr`.`id`=`p`.`parentId`) `distinctAlias` ORDER BY `distinctAlias`._rank ASC, `p_id` ASC LIMIT 100 OFFSET 2
> 
> query: SELECT `p`.`id` AS `p_id`, `p`.`name` AS `p_name`, `p`.`description` AS `p_description`, `p`.`parentId` AS `p_parentId`, `pr`.`id` AS `pr_id`, `pr`.`name` AS `pr_name`, `pr`.`description` AS `pr_description`, `pr`.`parentId` AS `pr_parentId`, CASE WHEN `p`.`id` % 2 = 0 then -p.id else `p`.`id` end AS `_rank` FROM `post` `p` LEFT JOIN `post` `pr` ON `pr`.`id`=`p`.`parentId` WHERE `p`.`id` IN (4, 2, 1, 3, 5, 7, 9) ORDER BY _rank ASC
> ```
> 
> And the result is correct.

This saved my day

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by NikolaLukic1** [comment]
I have the same problem. The query isn't generated at all, just the message as @noteasybutclear provided.
