### ISSUE TITLE
how to get the foreign's ID?

### ISSUE THREAD

**Issue by Vbubblery** [typeorm/typeorm#3945]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello,

I have two tables here: User and UserInfo
and their relationship is one to one. And the architecture in User like:

> column_name
> id
> name
> userInfoId

and for me, I do not want directly get the useinfo with the code:
```js
getRepository(User).createQueryBuilder("user").leftJoinAndSelect("user.userInfo", "userInfo").getOne();
```
I hope I can get the userinfoid when I call 
```js
getRepository(User).getOne();
=> user{
 id:1
name:"bubble"
userinfoid:1
}
```
Is it possible?

**Comment by vlapo** [comment]
Please provide entity definitions.
