### ISSUE TITLE
Whats the current status of mongo support?

### ISSUE THREAD

**Issue by dryajov** [typeorm/typeorm#395]
I was wondering what is the current status of mongo support in typeorm?

**Comment by pleerock** [comment]
experimental. You can check it in `npm i typeorm@next`. There are some architectural problems need to be resolved before it will be released.

**Comment by dryajov** [comment]
Thanks!

**Comment by 19majkel94** [comment]
@pleerock so it's experimental feature available on `typeorm@next` - why you don't use git flow with release branches, etc.? now mongo is on master branch and there is mongo in samples directory which might be confusing for users as the docs site aren't alway up to date 😉

**Comment by pleerock** [comment]
are you right, I need to create and maintain few branches :( Planning to do it right after figuring out #344)

**Comment by pleerock** [comment]
Mongodb support is available in latest `0.1.0-alpha` versions. You can find good samples in tests.
