### ISSUE TITLE
SELECT ... FOR UPDATE

### ISSUE THREAD

**Issue by zhongjixiuxing** [typeorm/typeorm#3950]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How to build mysql `SELECT ... FOR UPDATE` transaction query ?

**Comment by foxling** [comment]
[set-locking](https://typeorm.io/#/select-query-builder/set-locking
)
`.createQueryBuilder().setLock('pessimistic_write')`
