### ISSUE TITLE
Fixing table name comparison in migration process.

### ISSUE THREAD

**Issue by sassanh** [typeorm/typeorm#3951]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

This line https://github.com/typeorm/typeorm/blob/master/src/schema-builder/RdbmsSchemaBuilder.ts#L350 which is
```
                return table.name === fullTableName;
```
Should change to this:
```
                const fullExistingTableName = this.connection.driver.buildTableName(table.name, schema, database);
                return fullExistingTableName === fullTableName;
```

Otherwise if I have `@Entity({schema: 'public'})` decorator before my entity class it'll try to generate the table again and again and again in each migration (which will make migrations fail since the second)
There may be other places in codebase that need this type of update in the migration generation process (when comparing a name in models to a name in database.) so I'm not creating a PR as I don't have enough knowledge about codebase.

**Comment by Kononnable** [comment]
Please create PR - then we can discuss it more since we will see if such change don't break existing tests.

**Comment by sassanh** [comment]
https://github.com/sassanh/typeorm/pull/1

**Comment by sassanh** [comment]
https://github.com/typeorm/typeorm/pull/4020

**Comment by pleerock** [comment]
changes in schemas-related logic might be sensitive because there are lot of small gotchas, only @AlexMesser aware about all of them. @sassanh thats your default schema name, is it equal to `public` or not?

**Comment by sassanh** [comment]
Unfortunately I don't have the time to reproduce it again on my machine, my company decided to not use typeorm. At the time of reporting this issue I thought it'll trigger something for you, sorry I should've provide more information. In case it doesn't make sense for you feel free to close this issue.
