### ISSUE TITLE
Primary key as join column in 1:1 relation

### ISSUE THREAD

**Issue by jahudka** [typeorm/typeorm#3952]
**Issue type:**

[x] question
[?] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.12`

**Steps to reproduce or a small repository showing the problem:**

Let's say I have the following two entities (simplified for demonstration purposes):

```typescript
@Entity()
export class A {
  @PrimaryGeneratedColumn('uuid')
  readonly id: string;

  @OneToOne(() => B, b => b.a, { nullable: true })
  readonly b: B | null;
}

@Entity()
export class B {
  @PrimaryColumn()
  readonly id: string;

  @OneToOne(() => A, a => a.b)
  @JoinColumn({ name: 'id' })
  readonly a: A;
}
```

Running `schema:log` or `migration:generate` on a blank database shows that TypeORM generates both a primary key as well as a unique key for `B.id`. It's clear why TypeORM would want to add a unique key constraint on a column which represents a 1:1 relation in general, but in this case the column already has a primary key and therefore I'd think the unique key is redundant. If my logic is sound then this is a bug :-) it also happens if entity `B` already existed previously and now I'm adding entity `A` and changing `B.id` from a generated UUID primary column to a join column for the new relation - the migration that is generated drops the default value of `B.id`, creates the appropriate table for `A` and the foreign key `B("id") references A("id")`, but also creates the unique key while leaving the existing primary key in place. (One other thing it does is `DROP SEQUENCE "b_id_seq"`, which never existed as `B.id` is a UUID column and not a `serial`, but that's a separate issue.)

The question is therefore: is this the _expected_ behaviour (as in "expected by design")? If so, why is that? Why wouldn't the primary constraint do the job? And if not, well, then like I said, I'd like to report a beetle sighting :-)

**Comment by edgeman** [comment]
We have just run across the same problem, would also like to know if this is expected behaviour, and if not if there is a short-term workaround while this is being looked at? Thanks :-)

**Comment by bmoe24x** [comment]
+1 we are having the same issue. Don't want a redundant column if both entities are related based on their primary key.

**Comment by roylee0704** [comment]
@jahudka 

Simply add  `@PrimaryColumn({name: 'id')`.

```
@Entity()
export class A {
  @PrimaryGeneratedColumn('uuid')
  readonly id: string;

  @OneToOne(() => B, b => b.a, { nullable: true })
  readonly b: B | null;
}

@Entity()
export class B {

  @OneToOne(() => A, a => a.b)
  @JoinColumn({ name: 'id' })
  @PrimaryColumn({name: 'id')
  readonly a: A;
}
```

**Comment by DASPRiD** [comment]
> We have just run across the same problem, would also like to know if this is expected behaviour, and if not if there is a short-term workaround while this is being looked at? Thanks :-)

Workaround right now: Make it a `ManyToOne`.

**Comment by m-nikhil** [comment]
Any resolution for the same?

**Comment by MrBacony** [comment]
This Issue also occurs also for SQLite Generation. So probably this is a general problem for generating table relations with primary keys.

**Comment by anthonylau** [comment]
same issue on postgres migration generation, generating unique constraint on primary key

**Comment by jorenvandeweyer** [comment]
It looks like this is not by design?

1. I generate a migration
2. I run the migration
3. I generate a second migration (nothing changed on models)
4. I new migration is created that is adding unique keys on my primary keys

I'd be happy to implement this if someone can give me some pointers on where and how it should be implemented.

**Comment by masoud-msk** [comment]
This can be done like this:
```ts
@Entity()
export class A {
  @PrimaryGeneratedColumn('uuid')
  readonly id: string;

  @OneToOne(() => B, b => b.a, { nullable: true })
  readonly b: B | null;
}

@Entity()
export class B {
  @OneToOne(() => A, a => a.b, { primary: true })
  @JoinColumn({ name: 'id' })
  readonly id: string;
}
```
However in my opinion it's a bit weird for `@OneToOne` to have a `primary` option. I think it would be better to place it in `@JoinColumn`'s, because its a characteristic of the column not the relation.

**Comment by ilyazolotarov** [comment]
@masoud-msk "primary: true" doesn't work for me, it still generates unnecessary unique constraint on a second migration

**Comment by KiranNadig62** [comment]
The { primary: true } option does not appear to have a declaration in RelationOptions.

**Comment by masoud-msk** [comment]
@KiranNadig62 @ilyazolotarov 

> The { primary: true } option does not appear to have a declaration in RelationOptions causing a typescript error.

It worked in v0.2.34 but was [removed in v0.3.0](https://github.com/typeorm/typeorm/pull/8616) and is documented in last bullet of _BREAKING CHANGE_.

**Comment by jrista** [comment]
> @KiranNadig62 @ilyazolotarov
> 
> > The { primary: true } option does not appear to have a declaration in RelationOptions causing a typescript error.
> 
> It worked in v0.2.34 but was [removed in v0.3.0](https://github.com/typeorm/typeorm/pull/8616) and is documented in last bullet of _BREAKING CHANGE_.

The documentation of the 0.3.0 PR states that `OneToOne` should still support such relationships via the primary key. The only breaking aspect was supposed to be the removal of the `{ primary: true }` aspect of the RelationOptions. I believe, however, an UNINTENTIONAL breaking change was introduced by only supporting this with `@PrimaryColumn()`, and not supporting `@PrimaryGeneratedColumn()`. 

I have tables where we extend existing tables that need to support older applications by creating new extension tables, with new columns, where the join is on the primary key. We leave the auto-generated key on the main table, and use the same key in the extension table. This used to be supported....before `{ primary: true }` was nuked...

**Comment by nmphat** [comment]
> @KiranNadig62 @ilyazolotarov
> 
> > The { primary: true } option does not appear to have a declaration in RelationOptions causing a typescript error.
> 
> It worked in v0.2.34 but was [removed in v0.3.0](https://github.com/typeorm/typeorm/pull/8616) and is documented in last bullet of _BREAKING CHANGE_.

Im finding the solution for using a forein key as a part of composite primary key.

For who is finding the solution as me: [solution](https://github.com/typeorm/typeorm/pull/8616#:~:text=%29%0Auser%3A%20User-,Now,-%3A)

I really thanks for your help. I am a newbie and I have never thought that I must read the github conversation for findout the solution.
