### ISSUE TITLE
[Proposal] cli show migration enhancement

### ISSUE THREAD

**Issue by aa-neg** [typeorm/typeorm#3954]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[X] `cordova`
[X] `mongodb`
[X] `mssql`
[X] `mysql` / `mariadb`
[X] `oracle`
[X] `postgres`
[X] `cockroachdb`
[X] `sqlite`
[X] `sqljs`
[X] `react-native`
[X] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Goals**

To have greater confidence before applying / reverting migrations on a database.

**Current state**

Currently when running migrations from the cli useful information such as which migrations have been executed and the specific sql which would be run are displayed *after* the fact.

```bash
ts-node ./node_modules/typeorm/cli.js migration:run
```

**Proposal**

We propose to have functionality similar to https://docs.djangoproject.com/en/2.2/ref/django-admin/#django-admin-showmigrations which will allow the developer to receive the additional information before applying the changes. 

e.g some options

```bash
# New command (which would list which has been applied or not and developer can determine which is going to be run / reverted)
ts-node ./node_modules/typeorm/cli.js migration:show

# additional flag
ts-node ./node_modules/typeorm/cli.js migration:run --plan
ts-node ./node_modules/typeorm/cli.js migration:revert --plan
```

Hoping to generate some discussion on the feature and we are happy to do the work and make the PR. 

cc @Juddling

**Comment by vidhu** [comment]
I agree and if TypeORM provided feature comparable to django's ORM. That'd be a game changer. Especially in the migrations area

**Comment by Juddling** [comment]
Example output from Laravel's migration CLI tool:

```
> php artisan migrate:status
+------+------------------------------------------------------------------+-------+
| Ran? | Migration                                                        | Batch |
+------+------------------------------------------------------------------+-------+
| Y    | 2018_06_26_212752_create_test_table                              | 0     |
| Y    | 2018_06_26_212752_create_test2_table                             | 0     |
| Y    | 2018_06_26_212752_create_test3_table                             | 0     |
| Y    | 2018_06_26_212752_create_test4_table                             | 0     |
```

and another from Django:
```
> python manage.py showmigrations
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
```

**Comment by izayl** [comment]
why not add a flag to specific migration.

e.g

```shell
$ ts-node ./node_modules/typeorm/cli.js migration:run --target-migration
$ ts-node ./node_modules/typeorm/cli.js migration:revert --target-migration
```

**Comment by Juddling** [comment]
@izayl we want to be able to run checks without applying any changes, being able to specify a migration to run may be useful, but outside the scope of what we are looking for here.

**Comment by Juddling** [comment]
May also be useful for this command to return useful exit codes for a CI use case:

0: No unapplied migrations
1: Unapplied migrations

**Comment by pleerock** [comment]
Looks like this functionality can be useful, feel free to go with PR
