### ISSUE TITLE
ormconfig.js doesn't work with imports/requires

### ISSUE THREAD

**Issue by vidhu** [typeorm/typeorm#3955]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**
Donesn't matter

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

My `ormconfig.js` imports a `config.ts` file I've created to do something to the effect of:
```
import config from './src/config';

module.exports = {
  ...
  host: config.get('host'),
  cli: {
    migrationsDir: 'src/migrations',
  },
}
```

My package.json TypeORM cli script looks like this
```
{
  "scripts": {
    ...,
    "typeorm": "node --inspect-brk ./node_modules/typeorm/cli.js"
  },
}
```

When I run `npm run typeorm -- migrations:create -n CreateUser`, my migration file doesn't save to the `./src/migrations` folder. 

If I remove the `import ...` statement from `ormconfig.js`, the migration appears in the expected folder

--------

I did a little debugging. 
Looks like the `ormconfig.js` file is trying be loaded in [`PlatformTools.js Line:129`](https://github.com/typeorm/typeorm/blob/master/src/platform/PlatformTools.ts#L129)

If you look there, the default case tries to run `require('path/to/ormconfig.js')` and this fails. The exception is that my imported module (in ormconfig.js) is not found.

Here is a screenshot of the error in the developer console
![image](https://user-images.githubusercontent.com/1566265/55700839-dd0f8f00-599e-11e9-8c06-ca661a149165.png)

What could be a workaround to this?

Edit: This seems to be the case with using `require()` statements as well

**Comment by vlapo** [comment]
Hi @vidhu. 

You are mixing JS and TS. Require/import in your ormconfig.js file will load only js files. But you are trying to import `config.ts`.

**Comment by vidhu** [comment]
@vlapo  Thanks for the response, I'm not sure if that's the issue since I tried both, ts and js. Either way, I scaffolded my project again from scratch and it seemed to fix it so you can close this issue if you'd like. Not sure what was the issue
