### ISSUE TITLE
Error on Referencing a relation column in Unique constraint. 

### ISSUE THREAD

**Issue by shumailxyz** [typeorm/typeorm#3960]
I'm trying to add a `Unique` constraint with 2 columns where one column is the `id` column of the same entity and second column is the `id` column of the `@ManyToOne` relation column.

This isn't working and TypeORM throws error:
`Error: Index contains column that is missing in the entity: albumId`

Here's my class:
```
@Entity()
@Unique('test_index', ['id', 'albumId'])
export class Photo {

  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(type => Album, album => album.photos)
  album: Album;
```

What I am trying to achieve is to create a `Unique` index on combination of 2 columns where 1 column (`albumId`) is supposedly the foreign key column generated by TypeORM.

What's the correct way to reference the `albumId` column in `Unique` index?

I also tried `@Unique('test_index', ['id', 'album.albumId'])` but that didn't work either.

Thanks! 

**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by hcesar** [comment]
You should declare your `albumId` column (it doesn't interfere on the relation).

You can declare it as private if you are not going to use it:
```
@Column({ nullable: true })
private albumId: number;
```

**Comment by shumailxyz** [comment]
commenting here for future if someone lands here from google:

This is not possible yet. It's mentioned in Docs as well: https://typeorm.io/#/decorator-reference/unique

**_"This decorator can be applied only to an entity itself."._**

**Comment by jose-calderon** [comment]
if this is not possible yet, why the issue is close?

**Comment by jose-calderon** [comment]
nvm ... declaring the id as column name works fine

**Comment by dkretsch12** [comment]
It's handy to pass in `{ readonly: true }` as an option in your `@Column`

**Comment by dan-klasson** [comment]
Just exclude the `Id` part.
