### ISSUE TITLE
Plans for an Admin interface (similar to Django's)?

### ISSUE THREAD

**Issue by raychz** [typeorm/typeorm#3961]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Quick question.  Are there plans for an auto-generated admin interface, similar to Django's (see: https://docs.djangoproject.com/en/2.2/ref/contrib/admin/)?  "It reads metadata from your models to provide a quick, model-centric interface where trusted users can manage content on your site."  

I can imagine a similar TypeORM feature that would automatically analyze existing TypeORM entities and generate a simple frontend to perform CRUD operations on them.  Is this a good idea?  I'd be happy to take this on once I have some free time.  Thanks!

**Comment by vlapo** [comment]
I dont think so it will be time to this kind of feature/admin generator. We have so much work to do with issues (new features). So feel free to contribute. 

But if you have some free time and want to help. Check issues and try answer :) or even better check issues, source code and try contribute into typeorm.

**Comment by Kononnable** [comment]
Django is a web framework, typeorm is an ORM. ORMs by definition have nothing to do with any kind of fronted, so there is no place for such features here.

If you want to build such feature, you're welcome to(some folks will be happy to use it), but it should be done in separate package. When it's completed we could add it to our extensions section in README.
However typeorm works on multiple platforms so I guess it would require some more work to create such package.

Question was answered, so I'm closing the issue, but we can continue discussion here.
