### ISSUE TITLE
Search by objectId doesn't work for MongoDB

### ISSUE THREAD

**Issue by tien** [typeorm/typeorm#3964]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
import { ObjectID } from "mongodb";
import { Column, Entity, Index, ObjectIdColumn } from "typeorm";

@Entity()
@Index(["clientId", "name"], { unique: true })
export class User {
  @ObjectIdColumn()
  public id: ObjectID;

  @Column()
  public companyRef: ObjectID;

  @Column()
  public name: string;

  @Column()
  public mobile: number;
}
```
```ts
const repository = getMongoRepository(EventSchema);
const id = "hex-string";
// These work
repository.findOne(id);
repository.find({where:{ _id: id }});

// But this doesn't
repository.find({id: id, mobile: 021029022});
```

**Comment by deepchudasama** [comment]
Please read documents carefully it's not an issue. You should not use `find` in mongodb like that way. Use `findOne` instead.
```
import {getMongoRepository} from "typeorm";

const userRepository = getMongoRepository(User); // or connection.getMongoManager
const timber = await userRepository.findOne({ firstName: "Timber", lastName: "Saw" });
```

And if you want to use `find` you should use `where` inside of it.

**Comment by tien** [comment]
@deepchudasama sorry for the confusion, when I try
`repository.findOne({id: id, mobile: 021029022});`
It also doesn't work. But when I change the the entity definition from
```ts
@ObjectIdColumn()
  public id: ObjectID;
// to
@ObjectIdColumn()
  public _id: ObjectID;
```
It work. Which is kind of confusing as the example usage of mongo use id instead of _id

**Comment by deepchudasama** [comment]
@tien So you saying that when you use `id` code doesn't work but when you use `_id` it does?

**Comment by tien** [comment]
@deepchudasama yes. And when I use id for entity schema and _id in the “where” property, it would also work.

**Comment by robbyemmert** [comment]
I can second this. This is very confusing. Being forced to use _id means that mongo-specific code is leaking into my business logic and even the front-end unless we do a bunch of manual serialization.

@pleerock is there a way to make this less confusing?

**Comment by robbyemmert** [comment]
@pleerock I've created a repo to repro the error based on the typescript mongo example: https://github.com/robbyemmert/mongo-typescript-example

PS.  I've added a docker-compose.yml file for convenience. Just make sure docker is installed and type `docker-compose up -d && npm start` and it should run.

**Comment by robbyemmert** [comment]
For quick reference, I think this summarizes the issue:
<img width="501" alt="Screen Shot 2019-04-25 at 12 03 48 PM" src="https://user-images.githubusercontent.com/7490085/56709133-3f63e000-6752-11e9-9407-ac00d849defe.png">

For context:
```ts
import {Column, Entity, ObjectID, ObjectIdColumn} from "typeorm";
import {Category} from "./Category";

@Entity()
export class Post {

    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    title: string;

    @Column()
    text: string;

    @Column(type => Category)
    categories: Category[];

}
```

**Comment by robbyemmert** [comment]
Some more debugging info from another project:
This works:
<img width="502" alt="Screen Shot 2019-04-25 at 12 39 31 PM" src="https://user-images.githubusercontent.com/7490085/56710207-8f917100-6757-11e9-9ca8-8f6bbcf811e0.png">

This fails with a duplicate ID error.
<img width="500" alt="Screen Shot 2019-04-25 at 12 40 54 PM" src="https://user-images.githubusercontent.com/7490085/56710241-b18af380-6757-11e9-8872-4f42e3d35f84.png">

```ts
export abstract class BaseModel {
    init(data: InitPayload<this>) {
        Object.keys(data).forEach((key) => {
            this[key] = data[key]
        })
        return this
    }

    @ObjectIdColumn()
    _id: ObjectID | string

    @TimestampWithZone()
    created: number

    @TimestampWithZone()
    updated: number
}

@Entity()
export class Session extends BaseModel {
    @Column()
    directionDomain: string

    @Column()
    referrerDomain: string

    @Column(type => ClientLocation)
    clientLocation: ClientLocation

    @Column(type => ChatMessage)
    messages: ChatMessage[]
}

```

**Comment by alirezamirsepassi** [comment]
I think this is a feature request and can be added! Simply if database type was mongo, change id => _id and the run the query

**Comment by imhazige** [comment]
updateOne,updateMany({id:'sssss'}) also not work, while update(id) work.

**Comment by viktorstaikov** [comment]
Hey guys,

I was just reading the issue here and experimenting with some stuff and randomly I've nailed it:
```
async findById(id: string): Promise<UserEntity> {
   return await this.userRepository.findOne(id);
}
```

Basically one have to pass only the `id` to basically find by id in mongo.
This is my entity class:
```
@Entity('users')
export class UserEntity {
  @ObjectIdColumn()
  id: string;

  @Column({ unique: true })
  email: string;

  @Column()
  password: string;
}
```

**Comment by ibosev** [comment]
This is quite old but still..

My solution is just to name the column:

```
  @ObjectIdColumn({ name: 'id' })
  id: string;

  repository.findOne({ id });

```

**Comment by belukha** [comment]
It doesn't work, because `_id` is NOT instance of ObjectID. To make it work, you should manually create `ObjectID` instance, something like this

```javascript
//Note, that I use constructor from mongodb and type from typeorm, but they shouldn't have the different names if they're in different files
import { ObjectID } from 'mongodb';
import { ObjectID as ObjectIDType} from 'typeorm'

@Entity()
export class User {
  @ObjectIdColumn()
  _id: ObjectIDType;

  @Column()
  name: string;
}

const userId = '5d961d865ede2a35d0f51207';

const userRepository = connection.getMongoRepository(User);
const user = await userRepository.findOne({
 _id: new ObjectID(userId)
});

//or just use
const user = await userRepository.findOne(userId)
```

**Comment by mayognaise** [comment]
@belukha it worked!! thank you so much!

**Comment by hugogomess** [comment]
@belukha it not works for me, i'm trying to use something like this: 

`
if (!ObjectID.isValid(id)) {
  throw new NotFoundException('User not found');
}

user = await this.userRepository.findOne(id);
`

but i got undefined every time trying with an existing id, can anyone helps me?

**Comment by vishwassingh47** [comment]
> Some more debugging info from another project: I'm using Typeorm version ^0.2.15
> 
> This works: <img alt="Screen Shot 2019-04-25 at 12 39 31 PM" width="502" src="https://user-images.githubusercontent.com/7490085/56710207-8f917100-6757-11e9-9ca8-8f6bbcf811e0.png">
> 
> This fails with a duplicate ID error. <img alt="Screen Shot 2019-04-25 at 12 40 54 PM" width="500" src="https://user-images.githubusercontent.com/7490085/56710241-b18af380-6757-11e9-8872-4f42e3d35f84.png">
> 
> Here's the error:
> 
> ```
> BulkWriteError: E11000 duplicate key error collection: admin.session index: _id_ dup key: { : ObjectId('5cc138bc6ae997f91f44b6a3') }
>     at OrderedBulkOperation.handleWriteError (/[REDACTED]/node_modules/mongodb/lib/bulk/common.js:1061:11)
>     at resultHandler (/[REDACTED]/node_modules/mongodb/lib/bulk/ordered.js:167:23)
>     at /[REDACTED]/node_modules/mongodb-core/lib/connection/pool.js:397:18
>     at process._tickCallback (internal/process/next_tick.js:61:11)
> ```
> 
> ```ts
> export abstract class BaseModel {
>     init(data: InitPayload<this>) {
>         Object.keys(data).forEach((key) => {
>             this[key] = data[key]
>         })
>         return this
>     }
> 
>     @ObjectIdColumn()
>     _id: ObjectID | string
> 
>     @TimestampWithZone()
>     created: number
> 
>     @TimestampWithZone()
>     updated: number
> }
> 
> @Entity()
> export class Session extends BaseModel {
>     @Column()
>     directionDomain: string
> 
>     @Column()
>     referrerDomain: string
> 
>     @Column(type => ClientLocation)
>     clientLocation: ClientLocation
> 
>     @Column(type => ChatMessage)
>     messages: ChatMessage[]
> }
> ```

Any fix for this?

**Comment by akarabach** [comment]
> > Some more debugging info from another project: I'm using Typeorm version ^0.2.15
> > This works: <img alt="Screen Shot 2019-04-25 at 12 39 31 PM" width="502" src="https://user-images.githubusercontent.com/7490085/56710207-8f917100-6757-11e9-9ca8-8f6bbcf811e0.png">
> > This fails with a duplicate ID error. <img alt="Screen Shot 2019-04-25 at 12 40 54 PM" width="500" src="https://user-images.githubusercontent.com/7490085/56710241-b18af380-6757-11e9-8872-4f42e3d35f84.png">
> > Here's the error:
> > ```
> > BulkWriteError: E11000 duplicate key error collection: admin.session index: _id_ dup key: { : ObjectId('5cc138bc6ae997f91f44b6a3') }
> >     at OrderedBulkOperation.handleWriteError (/[REDACTED]/node_modules/mongodb/lib/bulk/common.js:1061:11)
> >     at resultHandler (/[REDACTED]/node_modules/mongodb/lib/bulk/ordered.js:167:23)
> >     at /[REDACTED]/node_modules/mongodb-core/lib/connection/pool.js:397:18
> >     at process._tickCallback (internal/process/next_tick.js:61:11)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```ts
> > export abstract class BaseModel {
> >     init(data: InitPayload<this>) {
> >         Object.keys(data).forEach((key) => {
> >             this[key] = data[key]
> >         })
> >         return this
> >     }
> > 
> >     @ObjectIdColumn()
> >     _id: ObjectID | string
> > 
> >     @TimestampWithZone()
> >     created: number
> > 
> >     @TimestampWithZone()
> >     updated: number
> > }
> > 
> > @Entity()
> > export class Session extends BaseModel {
> >     @Column()
> >     directionDomain: string
> > 
> >     @Column()
> >     referrerDomain: string
> > 
> >     @Column(type => ClientLocation)
> >     clientLocation: ClientLocation
> > 
> >     @Column(type => ChatMessage)
> >     messages: ChatMessage[]
> > }
> > ```
> 
> Any fix for this?

```
const user = await userRepository.findOne({
 _id: new ObjectID(userId)
});
```
this is working for me. BTW not clear why it was closed...

**Comment by akarabach** [comment]
@imnotjames please reopen this issue, wasted hours to fix this out

**Comment by JefferyHus** [comment]
This is still an ongoing issue, the current typeorm 0.3 has so many conflicts with MongoDD drivers version 4.

**Comment by JefferyHus** [comment]
The only work around is:

```typescript
import { ObjectId } from 'bson'; // this is necessary

@Entity()
class Entity {
  @ObjectIdColumn()
  id: ObjectId // <= this type is from the mongodb package or bson package and it is not the one from typeorm
}
```

then in your code to find a document by id you do:
```typescript
entityRepository.findOne({
  _id: new ObjectId('your string id here')
} as any)
```

**Comment by dominicarrojado** [comment]
I still face a similar issue with these package versions:
```json
    "@nestjs/typeorm": "^8.1.4",
    "mongodb": "^4.7.0",
    "typeorm": "^0.3.7"
```

I referenced the same way as @JefferyHus's workaround above but instead of using `any`, here's what I did:

```ts
const user = await this.usersRepository.findOne({
  where: { _id: new ObjectId(id) } as Partial<User>,
});
```

**Comment by PinoFlores** [comment]
So, how this was solved? I can not see any solution working. 

 "typeorm": "^0.3.6"
  "mongodb": "^4.8.0"

**Comment by N14R56** [comment]
Still a work around but I think it's cleaner.

```
import { Entity, Column, ObjectIdColumn } from 'typeorm';

@Entity({name: "cars"})
export class Car {
    @ObjectIdColumn()
    _id: any;
}
```

and

```
carsRepository.findOneBy({ '_id' : new ObjectId(id) })
```

**Comment by thiagozf** [comment]
Please, reopen this issue. It makes no sense to use `_id` when you explicitly decorate the ID attribute with `@ObjectIdColumn`

**Comment by Astlvk** [comment]
Want to use id instead of _id. no more appropriate solution, please reopen this issue.

**Comment by fufuShih** [comment]
The following is work for me, but when i use `import { ObjectID } from 'typeorm';`, it is not work.
import { ObjectID } from 'mongodb';

  ...
  const product = await productRepository.findOne(Product, {
    where: {
      _id: new ObjectID(req.query.id as string),
    },
  });
```

**Comment by IFafaa** [comment]
I'm going through the same problem...
Can you give me the solution, even if it's not the best, so I can at least move forward?

my entitiy:

```typescript
import { Column, Entity, ObjectIdColumn } from "typeorm";


@Entity("user")
export class User {
  @ObjectIdColumn({ name: "_id" })
  id: string;

  @Column("name")
  name: string;
  }
``` 


my service:

```typescript
async findOneById(id: string): Promise<User> {
    try {
      const user = await this.repository.findOne(id as any);
      return user;
    } catch (error) {
      return error;
    }
  }
``` 


please reopen this issue.

**Comment by IFafaa** [comment]
please reopen this issue...

**Comment by Morxi** [comment]
This approach works, but I'm not sure if it's the right way.
```ts
import { ObjectIdLike } from 'typeorm/driver/mongodb/bson.typings';

export class Datas {
  @ObjectIdColumn()
  _id: ObjectIdLike;

```

```ts
    const mydata = await this.data_Repository.findOne({
      where: { _id: new ObjectId(id) },
    });
```
