### ISSUE TITLE
Can't set SSL on from .env

### ISSUE THREAD

**Issue by singhsimranjot** [typeorm/typeorm#3968]
Can't set something like ```TYPEORM_SSL=true``` in ```.env``` file to set connection options.
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.15` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [ ] `mysql`
    [x] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
Hi @singhsimranjot. Use EXTRA property as described in https://github.com/typeorm/typeorm/pull/3409:
```
TYPEORM_DRIVER_EXTRA='{ "ssl": true }'
```

**Comment by olaven** [comment]
@vlapo To add to this, is it possible to specify a certificate value in a environment variable?
