### ISSUE TITLE
How to Set NumberLong Data Type？

### ISSUE THREAD

**Issue by zhangtanlin** [typeorm/typeorm#3969]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:6.0.0**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

### I want to use Mongodb's NumberLong data type in typeorm, but I haven't used it.

```javascript
import { Entity, Column, ObjectID, ObjectIdColumn } from 'typeorm';
@Entity('cat')
export class Cat {
	@ObjectIdColumn()
	id: ObjectID;
	// 长数据类型【NumberLong data type】
        // For example, I want to set NumberLong data type for longNum
	@Column()
	longNum: number;
}
```

**Comment by vlapo** [comment]
Did you try:
```ts
const Long = require('mongodb').Long;
... 
Long.fromInt(1)
...
```
Reference: https://stackoverflow.com/questions/27167569/how-to-insert-long-value-in-mongo-using-node

**Comment by rustamwin** [comment]
Closing issue as no answer from the author.
