### ISSUE TITLE
Expo-Example: ormconfig.json generates warning

### ISSUE THREAD

**Issue by Blackleones** [typeorm/typeorm#3971]
**Issue type:**

[x ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[x ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] pulled from `github:cuibonobo/typeorm-package`

**Problem**
If I move the connection configuration from hardCode (inside AppRoot.tsx) to ormconfig.json I will get the following warning: " PossibleUnhandled Promise Rejection (id: 0): Error: this option/function is not supported in the browser environment. Failed operation: <b>require("app-root-path") </b>"

**Steps to reproduce or a small repository showing the problem:**

I pulled your example [https://github.com/typeorm/expo-example](url) and I made the following changes:

1. create ormconfig.json file
   `{
   "database": "test",
   "synchronize": true,
   "type": "expo"
    }`

   > Note: entities has not been reported for test semplification.

2. inside AppRoot.tsx  I changed line 36 (connect() function) in 
   `connect() { return createConnection("test"); }`

Anyway I create a repository with my changes at [https://github.com/Blackleones/expo-example-warning](url) so you can pull it

**Comment by Kononnable** [comment]
In browser environment there is completely different concept of files, paths etc. so that's why you cant use ormconfig.json file. You probably could import file in your code and pass it as option arguments, but it depends on your bundler configuration).
