### ISSUE TITLE
Manual entity transform

### ISSUE THREAD

**Issue by ssi-hu-tasi-norbert** [typeorm/typeorm#3972]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I query the system-version table with raw sql, since afaik I can't do that with built methods or querybuilder.
```
return this.repoResult.query(`SELECT * FROM result **FOR SYSTEM_TIME ALL** WHERE id = ?`, [ id ]);
```
It works as expected but I'd like to use the result as entity, because one of my fields is a simple-json which is not parsed. I can do it manually of course, but I prefer a better way if it exists.

So my question is: is there any example about manual entity transformation? I just like to use what typeorm uses. Or is there a way to use the querybuilder with database specific addons?

Thank you,

tano

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
Hi @ssi-hu-tasi-norbert. Typeorm use some classes to transform raw results from database into entities. But it is internal behaviour of typeorm and we do not provide any exposed api to transform results into entities. You have to transform your query result into class by yourself :)

**Comment by ozknemoy** [comment]
i write method for this 
```
static transformEntityManual<T extends BaseEntity>(entity: T, _obj) {
    let obj = __.copy(_obj);
    
    connection.getMetadata(<any>entity).columns.forEach(col => {
      const prop = col.propertyName;
      if(col.transformer && obj.hasOwnProperty(prop)) {
        obj[prop] = col.transformer.to( obj[prop])
      }

    });
    return obj

  }
```

**Comment by Helveg** [comment]
The `col.transformer` doesn't work for me in `typeorm@0.3.20`, instead I use this:

```ts
function transformRaw(dataSource: DataSource, entity: Type, raw: Record<string, any>) {
  const metadata = dataSource.getMetadata(entity);
  const obj = metadata.create();
  for (const col of metadata.columns) {
    col.setEntityValue(obj, dataSource.driver.prepareHydratedValue(raw[col.databaseName], col)
  }
}
```

The key piece of the puzzle is `dataSource.driver.prepareHydratedValue` which converts the raw db value to the entity value.

It doesn't deal with relationships or any other fancy features, just the plain columns.
