### ISSUE TITLE
`leftJoinAndMapOne` suggested entity definition incorrect (documentation)

### ISSUE THREAD

**Issue by jalada** [typeorm/typeorm#3973]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

On https://github.com/typeorm/typeorm/blob/master/docs/select-query-builder.md#joining-and-mapping-functionality the documentation suggests:

```typescript
export class User {    
    /// ...
    profilePhoto: Photo;
}
```

But without any kind of initializer (which would defeat the purpose) this isn't allowed as it can't be undefined. You probably need:

```typescript
export class User {
    /// ...
    profilePhoto: Photo | undefined;
}
```

Unless there's a different recommendation?

**Comment by vlapo** [comment]
IMHO this is matter of strict mode enabled in typescript or not. But if you think it is doc issue feel free to contribute :)

**Comment by pleerock** [comment]
Yes its matter of strict mode and it really depends how you are using typescript. It complicates docs and isn't consistent with other docs we have. Thank you for PR anyway.
