### ISSUE TITLE
Field value letter casing when trying to update a row

### ISSUE THREAD

**Issue by zelbov** [typeorm/typeorm#3980]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I got an issue updating an object through repository.save(). It's about letter casing.

When we have an object e.g. User with properties "email" ( string / varchar(128) ) and "active" (tinyint) and we update only "email" to it's lowercase, we can get an update executed properly.
But when we change both fields e.g. "email" to lowercase and "active" to another value (0 -> 1) and perform an update, "email" field doesn't change and still contains upercase letters.

I think that letter casing change is only tracked when the field is the only one in a fieldset that is changed before we call an update.

`

    let repo = getConnection().getRepository(User);

    repo.find().then((result: User[]) => {
    
        for(var r in result){
            let row = result[r];
            if(row.email != row.email.toUpperCase()) row.email = row.email.toUpperCase();
            row.active ? row.active = 0 : row.active = 1;
            repo.save(row);
        }

    })

`

that's the quite common example of an issue: when `row.active` is changed to another value and `row.email` is changed to it's lowercase, 'email' field does not update in a database after `repo.save()` call. However, if we remove `row.active` field change from a code, 'email' field updates properly.

**Comment by vlapo** [comment]
This have to be problem in your code. 

`repo.save(row);` is async operation. You have to handle it properly. Code you posted is wrong and it will not work properly.

**Comment by rustamwin** [comment]
Closing, no response from author
