### ISSUE TITLE
How can I write the insert QueryBuilder in a for loop and only run the execute once?

### ISSUE THREAD

**Issue by haohello** [typeorm/typeorm#3984]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

This is what I am writing for now: 

`async (dt_str, items) => {
    let recordsToSave = []
    for(const it of items) {
      let it2Save = {
        //  "交易代码": "000001",
        zqdm: it['交易代码'],

        //  "名称": "平安银行",
        //  "证券名称":"通源石油"
        zqmc: it['名称'],

        //  "财务更新": "20190402",
        cwgxrq: it['财务更新'],

        //  "上市日期": "19910403",
        ssrq: it['上市日期']
      }
      // recordsToSave.push(it2Save)

      await this.repository
        .createQueryBuilder()
        .insert()
        .into(Stock)
        .values(it2Save)
        .onConflict(`("zqdm") DO UPDATE SET "zqmc" = :zqmc, "cwgxrq" = :cwgxrq`)
        .setParameter("zqmc", it2Save.zqmc)
        .setParameter("cwgxrq", it2Save.cwgxrq)
        .execute()
    }
  }`

**Comment by haohello** [comment]
The below is what I am doing for now in the code,  but I'm wondering if you have better ways to only run the execute once?

`async (dt_str, items) => {
    let recordsToSave = []
    for(const it of items) {
      let it2Save = {
        //  "交易代码": "000001",
        zqdm: it['交易代码'],

        //  "名称": "平安银行",
        //  "证券名称":"通源石油"
        zqmc: it['名称'],

        //  "财务更新": "20190402",
        cwgxrq: it['财务更新'],

        //  "上市日期": "19910403",
        ssrq: it['上市日期']
      }
      recordsToSave.push(it2Save)

      /*console.log('要保存的数据为: ')
      console.log(it2Save)*/

      await this.repository
        .createQueryBuilder()
        .insert()
        .into(Stock)
        .values(it2Save)
        .onConflict(`("zqdm") DO UPDATE SET "zqmc" = :zqmc, "cwgxrq" = :cwgxrq`)
        .setParameter("zqmc", it2Save.zqmc)
        .setParameter("cwgxrq", it2Save.cwgxrq)
        .execute()
    }
  }`

**Comment by Kononnable** [comment]
If you have to use queryBuilder I think this is the only way. But you probably could use ORM `.save` method instead(but it really depends on rest of your code) - but it could generate more sql statements.

As for the code - you may want to use `Promise.all` instead of awaiting every singe promise.

**Comment by imnotjames** [comment]
Hope this answered your question, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
