### ISSUE TITLE
ColumnTypeUndefinedError with 'reflect-metadata' and emitDecoratorMetadata added

### ISSUE THREAD

**Issue by Aaltuj** [typeorm/typeorm#3995]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1) open the project attached 
1) run  `yarn install`
1) run `yarn tsc`
2) run `.\bin\run hello`

this will result in:
```
D:\x\x\x\terminal>.\bin\run
(node:49924) ColumnTypeUndefinedError Plugin: repro: Column type for User#firstName is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.
module: @oclif/config@1.12.12
task: toCached
plugin: repro
root: D:\x\x\x\terminal
See more details with DEBUG=*
VERSION
  repro/0.0.0 win32-x64 node-v8.11.3

USAGE
  $ repro [COMMAND]

COMMANDS
  help  display help for repro
```

Reproduction project:
[terminal.zip](https://github.com/typeorm/typeorm/files/3079961/terminal.zip)

Any help would be appreciated.

**Comment by discosultan** [comment]
@Aaltuj Did you ever find a solution or went with a workaround?

**Comment by josephbuchma** [comment]
Babel does not support this out of box, here is a plugin
https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata#readme

**Comment by Aaltuj** [comment]
yeah i've switch to rxdb and couchdb was mor suitable for my needs thanks anyway
