### ISSUE TITLE
Add support for postgres materialized views

### ISSUE THREAD

**Issue by EvgeniyZo** [typeorm/typeorm#3996]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

https://www.postgresql.org/docs/10/sql-creatematerializedview.html

**Comment by dhritzkiv** [comment]
Will TypeORM 0.2.17's [ViewEntity](https://typeorm.io/#/view-entities) be able to support materialized views? At least for querying (though, triggering a data refresh would be excellent as well)

**Comment by moltar** [comment]
Yes, a must have!!

**Comment by NinthAutumn** [comment]
+1
