### ISSUE TITLE
synchronize=true always failing when using decimal column type with a foreign key constraint

### ISSUE THREAD

**Issue by pjolayres** [typeorm/typeorm#3997]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Repro [here](https://github.com/pjolayres/typeorm-sqlite-recreate-error).

1. `typeorm init --name MyProject --database sqlite`
1. Set `"synchronize": true` in `ormconfig.json`
1. Add photo entity inside `src/entity/Photo.ts`.
1. Update `src/entity/User.ts` to include new column with decimal type.
1. Create relationship between the two entities: User (one) <==> Photo (many).
1. run `npm start` once to create database successfully.
1. run `npm start` again to show error:
```shell
query: BEGIN TRANSACTION
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('photo', 'user')
query: SELECT * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('photo', 'user')
query: PRAGMA table_info("user")
query: PRAGMA index_list("user")
query: PRAGMA foreign_key_list("user")
query: PRAGMA table_info("photo")
query: PRAGMA index_list("photo")
query: PRAGMA foreign_key_list("photo")
query: CREATE TABLE "temporary_user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "height" decimal(9,6) NOT NULL)
query: INSERT INTO "temporary_user"("id", "name", "height") SELECT "id", "name", "height" FROM "user"
query: DROP TABLE "user"
query failed: DROP TABLE "user"
error: { [Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] errno: 19, code: 'SQLITE_CONSTRAINT' }
query: ROLLBACK
{ QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
    at new QueryFailedError (/Users/paulo/Repositories/typeorm-sqlite-recreate-error/src/error/QueryFailedError.ts:9:9)
    at Statement.handler (/Users/paulo/Repositories/typeorm-sqlite-recreate-error/src/driver/sqlite/SqliteQueryRunner.ts:53:26)
    at Statement.replacement (/Users/paulo/Repositories/typeorm-sqlite-recreate-error/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.replacement (/Users/paulo/Repositories/typeorm-sqlite-recreate-error/node_modules/sqlite3/lib/trace.js:19:31)
```

Two issues are happening in this case:
1. TypeORM is recreating the table because it thinks there has been a change of column definition from:
```javascript
{
    ...
    type: 'decimal',
    precision: 9,
    scale: 6
}
```
to
```javascript
{
    ...
    type: 'decimal(9,6)'
}
```

This is the change in column definitions as found by TypeORM when debugged in vscode:
![image](https://user-images.githubusercontent.com/23610081/56153745-ef558280-5fc7-11e9-8524-d372f5bbe160.png)

2. Because of the "change in schema", SQLite driver is attempting to recreate the table by copying the contents to `temporary_user` table and then dropping the original `user` table. Unfortunately, due to the foreign key reference of `photo` table to `user` table, the operation causes the `QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed` error. This is somewhat related to #3863.

**Comment by rettgerst** [comment]
my team is running into this issue which doesn't appear to be resolved yet. are there any updates? is a fix coming in a future version?

**Comment by prgmtx** [comment]
Also experiencing similar issue regarding synchronization of entities with "decimal" attributes on SQLite. TypeORM "recreating" the table on each application start.

**Comment by trevorhanus** [comment]
Any word on this one? I'm still running into the same issue.

**Comment by AlexMesser** [comment]
This was fixed and released. Please update your TypeORM version to the latest and reopen this issue if the error persists.

**Comment by 1gluk** [comment]
this problem has not been resolved. Any change to table fields that have a foreign key constraint will result in an error deleting the old version of the table and rolling back the transaction. Synchronization doesn't work. A workaround suggested at https://github.com/typeorm/typeorm/issues/2576
