### ISSUE TITLE
add more database drivers 

### ISSUE THREAD

**Issue by pleerock** [typeorm/typeorm#4]
Need to add database drivers for at least these databases:
- [x] PostgreSQL
- [x] SQLite
- [x] Microsoft SQL Server
- [x] MariaDB
- [x] Mongodb
- [ ] Cassandra?
- [ ] Redis?
- [ ] Oracle
- [ ] DB2 ?
- [ ] mixed databases like indexeddb

**Comment by pleerock** [comment]
basic support of PostgreSQL has been added

**Comment by lhecker** [comment]
Hey I've just noticed that you added PostgreSQL support., Awesome work so far! 😊

What I don't really understand yet though is why you manually serialize and deserialize incoming data, since all database drivers you use already come shipped with a much broader serialization support. For instance [this](https://github.com/typeorm/typeorm/blob/7fc08acecba3f98786a9e5abe1e7044919dd546c/src/driver/postgres/PostgresDriver.ts#L184) won't work well because you don't serialize the timezone in the `Date` object, resulting in wrong values in the database.

So what's the reason to not just pass the data 1:1 into the DB driver?

**Comment by pleerock** [comment]
Thank you.

>  this won't work well because you don't serialize the timezone 

yes, you are probably right. There are such very small bugs that needs to be fixed. In this case probably need to check if timezone is used for this column and add it too. Or as you said delegate work to the driver if it completely can handle it.

As I remember, the reason why I added this logic is because mysql driver wasn't able to handle my Date objects properly. Right now Im not sure which driver actually can handle what data and which can't. But this is totally something that should be optimized in a free time.

**Comment by lhecker** [comment]
Hmm this is probably not wrong but I strongly suggest you to simply pass data to the `pg` driver unmodified, because it's quite well in handling those. I've been using it for a long time now and never had any kind of issue with serializing all builtin JS types with `pg`. You can see what it supports [here](https://github.com/brianc/node-pg-types/blob/2ded8faafaab6e5f48d1e8e0a9ddb37188f7542c/lib/textParsers.js#L140-L176) btw. I believe you can safely assume that all types which _are_ implemented already are implemented correctly.

**Comment by pleerock** [comment]
okay, I'll investigate this question, and after check if everything will work good with pg itself, I'll do as you said

**Comment by pleerock** [comment]
support for mariadb and sqlite has been added. next drivers are for oracle and sqlserver

**Comment by bijeebuss** [comment]
I would definitely give this a try if it supported SQL Server. Any idea when it might be integrated?

**Comment by pleerock** [comment]
sql server is in progress, I think 70-80% its support already there. Next week Im going to finish it

**Comment by bijeebuss** [comment]
Awesome thanks

**Comment by pleerock** [comment]
@19majkel94 added 9e12347

**Comment by 4nxiety** [comment]
how much postgresql is supported?

**Comment by pleerock** [comment]
@4nxiety postgres support is pretty good, probably same as mysql right now

**Comment by 4nxiety** [comment]
thanks you. I will take a look on it. The persisting of the data are capsuled into a transactions with automaticlly rollback if something happen?

**Comment by pleerock** [comment]
yes, during a single call of persist method

**Comment by 4nxiety** [comment]
awesome, thanks

**Comment by pleerock** [comment]
sql server support is much better now in `0.0.4`

**Comment by mdsaleemj** [comment]
Is oracle supported by typeorm ?

**Comment by pleerock** [comment]
oracle support is experimental and there are few issues with it that needs to be finished before I can say that it works

**Comment by michoo** [comment]
Hi pleerock! can you share with us more about issues you still have with Oracle integration? 
Thanks

**Comment by pleerock** [comment]
oracle is quite different and there are some methods left unfinished in `OracleQueryRunner`. Schema synchornization don't work correctly right now. And right now Im busy with other tasks with higher priority.

**Comment by michoo** [comment]
Thanks!

**Comment by pleerock** [comment]
Closing it. Enough databases support for now. Mongodb is supported and there are example how to use it in tests. Oracle has better support nowdays however there are still few issues needs to be fixed. I plan to fix them all in a next few months.

**Comment by strictd** [comment]
Are you going to implement the mysql2 driver? your docs say you are, the code says you aren't. https://github.com/typeorm/typeorm/blob/master/src/driver/DriverFactory.ts

**Comment by vhb56** [comment]
Hi, great stuff you are doing here!

But what about browsers support?
Now when PWA are becoming popular & frameworks like Ionic are investing so much in PWA.
WebSQL is obsolete. Not developed anymore, limited browser support?
IndexedDB - becomes a standart. All new guides from google about PWAs are using it.
Support almost in every browser. Fast?
So i really curious how are you going to support browsers?

If market really making making a shift to PWAs.
Why supporting WebSQL and not IndexedDB?
Then i saw sql.js in roadmap.
If i understood well sql.js creates virtual DB, high memory consumption, no persistant changes?

I just want to have a better picture about typeorm future ( and why indexedDB is not an option? ), 
nothing  more :)

Thx, for everything you do!

**Comment by pleerock** [comment]
add for sql.js is already implemented. TypeORM is mostly relational databases ORM, only mongodb non-relational database is supported for now. Right now there are lot of features needed to be finished and personally I cannot work on indexeddb implementation. But community can take an initiative and implement this new database type as a new typeorm driver!

**Comment by vhb56** [comment]
Thx for the response!
Yep, it would be awesome (native+fast+supported even in mobile browsers)
https://www.caniuse.com/#search=indexeddb

Too bad i am not skilled enough to do such implementation, 
all i can do is asking questions, sorry  :)

I'm developing an app with Ionic & your example is working great on android device, but fails in browser, folks in Ionic said to not build Cordova Browser Platform, if i use sql.js will it work everywhere?
Mobile apps & Browser?
Example app for Ionic will change too much with use of sql.js? At the end data can be saved?

**Comment by pleerock** [comment]
>  if i use sql.js will it work everywhere?

question to @daniel-lang

**Comment by vhb56** [comment]
guys, i've just found this lib, they say they are faster than sql.js & they export to indexeddb:

https://github.com/agershun/alasql

**Comment by daniel-lang** [comment]
sql.js can be used for Ionic apps and in browser. It has an auto-save feature, that will automatically save and load the database to localstorage

**Comment by pleerock** [comment]
> i've seen that the sql.js has this feature, but don't know yet how to do it with typeorm,

@daniel-lang can you please point him a documentation link with description how to do this

> https://github.com/agershun/alasql

Looks interesting, we can probably implement it as well if @daniel-lang will be kind enough 😆

**Comment by daniel-lang** [comment]
Documentation for sql.js options are [here](http://typeorm.io/#/connection-options/sqljs-connection-options).

I will add alasql to my list of driver to implement...

**Comment by SkrabakL** [comment]
Any plans for db2 support ?

**Comment by nextbyn** [comment]
> Any plans for db2 support ?

Is really a good question here, in my project I'm still using sql js but it have a slow performance on big querys.

**Comment by Kononnable** [comment]
https://github.com/typeorm/typeorm/issues/2699 
There are no plans to implement new drivers in the near future by typeorm maintainers, but community can decide to do it. Maintainers will help, but don't have enough time to implement support for new driver on their own.
