### ISSUE TITLE
How to use isNull and isNotNull with querybuilder?

### ISSUE THREAD

**Issue by jerlam06** [typeorm/typeorm#4000]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have been searching for a long time but I don't find how to use isNull and isNotNull with queryBuilder:

```
 const moviesNotWatched = await getManager()
        .createQueryBuilder(Movie, 'movie')
        .where('movie.isWatched = :isWatched', { isWatched: false })
        .andWhere('movie.metadata = :metadata', { metadata: Not(IsNull()) })
        .getMany();
```

I don't think it is in the docs.

**Comment by s97712** [comment]
```
const moviesNotWatched = await getManager()
        .createQueryBuilder(Movie, 'movie')
        .where('movie.isWatched is null')
        .andWhere('movie.metadata is not null')
        .getMany();
```

**Comment by brt-han-mai** [comment]
How to use IsNotNull() in find options?

**Comment by lexyblazy** [comment]
@brt-han-mai use something like

```ts

 {
     movie: typeorm.Not(typeorm.IsNull())
  }
```

**Comment by power-f-GOD** [comment]
@brt-han-mai This also seems to work for me too:
```
{ movie: Not('null') }

**Comment by kajalj3098** [comment]
.andWhere('movie.metadata is not null') is not working for me

 @[s97712](https://github.com/s97712)

**Comment by mdarkawi** [comment]
{ movie: IsNull() }
