### ISSUE TITLE
no exported member 'ViewEntity', 'ViewColumn'

### ISSUE THREAD

**Issue by ThinkontrolSY** [typeorm/typeorm#4001]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[x] `0.2.16` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
- node_modules/typeorm"' has no exported member 'ViewEntity'.
- node_modules/typeorm"' has no exported member 'ViewColumn'.

**Comment by ThinkontrolSY** [comment]
also try
`@next`
`0.2.15`
`0.2.14`
`0.2.8`
`0.2.6`

same problem

**Comment by ThinkontrolSY** [comment]
![image](https://user-images.githubusercontent.com/11331554/56187793-57eb4080-6056-11e9-98a5-2ac8b8eca8ee.png)

I also checked directory in node_module/typeorm/decorator
there is no ViewColumn files

**Comment by rustamwin** [comment]
`entity view` functionality not released yet

**Comment by ThinkontrolSY** [comment]
@rustamwin Thanks
which version and when will release view function?

**Comment by rustamwin** [comment]
I think in `0.2.17` version

**Comment by ThinkontrolSY** [comment]
@rustamwin 
0.2.17 released, but still not support viewEntity, which version will? thanks

**Comment by vlapo** [comment]
@ThinkontrolSY I am sure version 0.2.17 supports `ViewEntity`. It has to be problem in your environment setup.

**Comment by ThinkontrolSY** [comment]
@vlapo Yes, Something wrong in my environment, thanks
