### ISSUE TITLE
Support alias in insert into

### ISSUE THREAD

**Issue by biern** [typeorm/typeorm#4003]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[x] `postgres`

PostgreSQL supports alias in INSERT INTO statement since v9.5, eg. `INSERT INTO "tablename" as "alias"` (https://www.postgresql.org/docs/9.5/sql-insert.html). It would be nice to be able to use that in insert query builder.

Our use case is incrementing a counter using `INSERT ... ON CONFLICT` statement and using table prefixes at the same time. eg:

```
this.createQueryBuilder()
      .insert()
      .into(Velocity)
      .values(velocity)
      .onConflict(
        `("date", "symbol") DO UPDATE SET value = v1_velocity.value + :velocity `
      )
      .setParameter('velocity', velocity.value)
      .execute();
```

`v1_` is our prefix here and it shouldn't have to be hardcoded in the query. I think we can workaround this by using `this.manager.connection.driver.options.entityPrefix` but I think that using explicit alias would be clearer.

**Comment by tonyxiao** [comment]
To confirm, you mean `INSERT INTO "tablename" as "alias"` right? If so 👍

**Comment by biern** [comment]
@tonyxiao yes, thanks for pointing this out, I've updated the issue to include that explicit statement example.

**Comment by antoine-pous** [comment]
Oh! i was looking for exactly this feature :'(

**Comment by kyle-seongwoo-jun** [comment]
any updates?

**Comment by falahati** [comment]
not having this makes the `ON CONFLICT DO UPDATE` unusable. Please take another look at this issue.
