### ISSUE TITLE
RenameTable error: constraint does not exist

### ISSUE THREAD

**Issue by danielmhanover** [typeorm/typeorm#4008]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I believe my constraints were generated from a previous TypeORM version, so when I go to renameTable() in typeorm@latest, it attempts to find the existing constraints based on the current naming convention rather than the old one, so it fails. Is there a way to delete and regenerate all constraints with the current naming convention?

**Comment by SirBernardPhilip** [comment]
Are there any updates on this? I am struggling with the same thing.

**Comment by odeds-confetti** [comment]
Same here. any updates?

**Comment by imnotjames** [comment]
This should be fixed with 0.2.38
