### ISSUE TITLE
Joining table sql error?

### ISSUE THREAD

**Issue by royibernthal** [typeorm/typeorm#401]
I'm trying to select a specific player and join his corresponding group.

I'm getting the following error:

> (node:8472) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'group group ON group.id=player.group WHERE player.email = 'test@gmail.co' at line 1

Also, if it matters, I'm passing 'test@gmail.com' not 'test@gmail.co' as it states in the error.
I'm not even using MariaDB as far as I know - standard xampp installation.

The query works without the join. What am I missing?

**Query**

```
getPlayer(email: string): Promise<Player> {
		return this.connection.entityManager.createQueryBuilder(Player, 'player')
					.where('player.email = :email')
					.setParameter('email', email)
					.innerJoinAndSelect('player.group', 'group') //this line causes the problem
					.getOne();
	}
```

**Group**

```
@Table()
export class Group {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    username: string;
    
    @Column()
    password: string;
    
    @Column()
    name: string;

    @Column()
    country: string;

    @Column()
    domain: string;
    
    @CreateDateColumn()
    date: Date;

    @OneToMany(type => Player, player => player.group)
    players: Player[];

}
```

**Player**

```
@Table()
export class Player {

    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    email: string;
    
    @Column()
    password: string;

    @Column()
    ban: boolean;
    
    @CreateDateColumn()
    date: Date;

    @ManyToOne(type => Group, group => group.players)
    group: Group;

}
```

**Comment by pleerock** [comment]
I think this a bug. Looks like its not escaping "group" properly. Your problem right now is that you are using "group" which is not escaped. I suggest to name "group" something differently for now.

**Comment by royibernthal** [comment]
Thanks, that was indeed the problem.

**Comment by valVk** [comment]
This is for reference
https://github.com/typeorm/typeorm/issues/334

**Comment by pleerock** [comment]
This is already fixed in latest typeorm versions. Corresponding tests are added.
