### ISSUE TITLE
Connection "default" not found

### ISSUE THREAD

**Issue by guillaumepn** [typeorm/typeorm#4010]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.14` 

I've tried the other issues related to this but none worked unfortunately.  

I'm using Typeorm in combination with Express and Apollo Server

The createConnection step goes well, but when I'm calling a specific resolver (the Register one, a Graphql mutation resolver to sign up to my app), I'm getting `Uncaught (in promise) Error: GraphQL error: Connection "default" was not found.` in my browser console

How I create my connection : 
```javascript
await createConnection(connectionOptions);
```

the value of connectionOptions is what I have in my ormconfig.js : 
```javascript
module.exports = {
  name: "production",
  type: "postgres",
  host: "db", // db is the name of my Docker service running the database
  port: 5432,
  username: process.env.ORM_USER,
  password: process.env.ORM_PASSWORD,
  database: process.env.ORM_DB,
  synchronize: true,
  logging: false,
  entities: [process.env.ORM_ENTITIES],
  migrations: [process.env.ORM_MIGRATIONS],
  subscribers: [process.env.ORM_SUBSCRIBERS],
  cli: {
    entitiesDir: process.env.ORM_ENTITIES_DIR,
    migrationsDir: process.env.ORM_MIGRATIONS_DIR,
    subscribersDir: process.env.ORM_SUBSCRIBERS_DIR
  }
};
```
my env variables seem correct (ORM_ENTITIES = "dist/entity/**/*.js", which is the correct path) 

my User entity : 
```javascript
...
@Entity()
export class User extends BaseEntity {
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column("text")
  email: string;

  @Column("text", { nullable: true })
  username: string | null;

  @Column("text")
  password: string;
...
```

The problem doesn't seem to be in my resolver, because the console.logs I put in it are not reached

This issue occurs in production, I don't have it in local development

**Comment by guillaumepn** [comment]
Ok I found the solution, in case someone faces the same issue : I had to declare both `default` and `production` in my ormconfig.js and create them with `createConnections()` instead of `createConnection(connectionOptions)` 

I don't know why I need both connections though, but at least it's working

**Comment by Kononnable** [comment]
I don't think this is the solution. You(or something in your dependencies) probably creates default connection somewhere that's why it's requiring it configuration options. You should probably trace that error in your code.

However it doesn't seem like typeorm bug, just problem with your code.

**Comment by le0l1** [comment]
I've got the same problem, the reason is that when using entity's methods like `findOne`,  it will connect to default, then the error throw out
https://github.com/typeorm/typeorm/blob/3cbbeadd5cea22e44283b588a3444401bcb0a274/src/repository/BaseEntity.ts#L84-L87

**Comment by wijourdil** [comment]
I got the same issue and solved it by using `getRepository(Entity).find()...` instead of `Entity.find()...`

**Comment by drewjbartlett** [comment]
If this is still an issue for anyone, I've solved it by making a factory function: 

```ts
import { getRepository } from 'typeorm/browser';
import { UserEntity, UserModel } from './schema';

export function getUserRepository() {
  return getRepository<UserModel>(UserEntity);
}
```

And then I import the function to use:

```ts
import { getUserRepository } from '...';

getUserRepository().findOne(1);
```

**Comment by sasa6277** [comment]
Hi 
i have same problem and i do it and solve

`import { createConnection } from 'typeorm';
    const conn = await createConnection({
    type: 'postgres',
    username: process.env.PG_USERNAME,
    password: process.env.PG_PASSWORD,
    host: 'localhost',
    port: 5432,
    url: process.env.DB_URL,
    entities: [Post, User],
    name: process.env.PG_DATABASE,
    logging: true,
    synchronize: true
  });`

**Comment by vilsonborges3** [comment]
I have the same problem and dont know correct

**Comment by vilsonborges3** [comment]
"i call my service here:"

import { getRepository, getConnection, createConnection } from 'typeorm';
import User from '../models/User';

interface Request {
  name: string;
  email: string;
  password: string;
}

class CreateUserService {
  public async execute({ name, email, password }: Request): Promise<User> {
    const conn = await createConnection({});

    console.log('teste4');
    const usersRepository = getRepository(User);
    console.log('teste5');
    const checkUserExists = await usersRepository.findOne({
      where: { email },
    });

    if (checkUserExists) {
      throw new Error('Email address already used.');
    }

    const user = usersRepository.create({
      name,
      email,
      password,
    });

    await usersRepository.save(user);

    return user;
  }
}

export default CreateUserService;

**Comment by vilsonborges3** [comment]
"And this is the error:"

yarn run v1.22.5
$ ts-node-dev --inspect --ignore node_modules  src/server.ts
[INFO] 02:22:03 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.3)
Debugger listening on ws://127.0.0.1:9229/ab084465-507a-45c9-9ca4-1831c5881f15
For help, see: https://nodejs.org/en/docs/inspector
� Server started on port 3333!
ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (C:\Users\vilso\Desktop\bootcamp\aulas\primeiro-projeto-node\src\error\ConnectionNotFoundError.ts:8:9)
    at ConnectionManager.get (C:\Users\vilso\Desktop\bootcamp\aulas\primeiro-projeto-node\src\connection\ConnectionManager.ts:40:19)  
    at Object.getRepository (C:\Users\vilso\Desktop\bootcamp\aulas\primeiro-projeto-node\src\index.ts:284:35)
    at C:\Users\vilso\Desktop\bootcamp\aulas\primeiro-projeto-node\src\routes\users.routes.ts:11:28
    at step (C:\Users\vilso\Desktop\bootcamp\aulas\primeiro-projeto-node\src\routes\users.routes.ts:33:23)
    at Object.next (C:\Users\vilso\Desktop\bootcamp\aulas\primeiro-projeto-node\src\routes\users.routes.ts:14:53)
    at C:\Users\vilso\Desktop\bootcamp\aulas\primeiro-projeto-node\src\routes\users.routes.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\vilso\Desktop\bootcamp\aulas\primeiro-projeto-node\src\routes\users.routes.ts:4:12)
    at C:\Users\vilso\Desktop\bootcamp\aulas\primeiro-projeto-node\src\routes\users.routes.ts:9:47

**Comment by albjeremias** [comment]
I'm having a huge struggle with this issue.. i'm developing in this repository:

https://github.com/helpbuttons/helpbuttons/tree/admin-user

its the admin-user branch.. if someone can take a look.. I would also would love to understand how-to debug this kind of stuff in nestjs, its really annoying everytime u do a upgrade some stuff like this happens.
