### ISSUE TITLE
How to use (OR) AND (OR) in where clause

### ISSUE THREAD

**Issue by Menci** [typeorm/typeorm#4013]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How to make these query with find options:

```
SELECT * FROM table WHERE (a = 1 or b = 2) and (c = 1 or d = 2);
```

**Comment by victorschinaider** [comment]
I image that you want a deep description of this query in select query builder mode, but i think it doesn't exists.
You've to use:

```
query
.where('a = 1 OR b = 2')
.andWhere('c = 1 OR d = 2')
``` 
Or just use the `where` clause, it's you choose.

**Comment by rustamwin** [comment]
Closing - no answer from the author.

**Comment by tusharsrivastava** [comment]
Hi Is there an answer available now?
