### ISSUE TITLE
Re-use connection pool in other modules

### ISSUE THREAD

**Issue by HoldYourWaffle** [typeorm/typeorm#4022]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb` (at least in my case)
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**The question**
Is it possible to re-use the (driver-specific?) connection pool created by `typeorm`?
I want to use [express-mysql-session](https://www.npmjs.com/package/express-mysql-session) in my project, and it needs to be given a database connection. Obviously I could just create another connection pool, but I feel like it should be possible to re-use the one `typeorm` created.
Is this possible? If so, how do I do it? If it isn't, why not, what should I do instead and how stupid am I for thinking it should be possible?

**Comment by vlapo** [comment]
I think you can use pool from `MysqlDriver`. https://github.com/typeorm/typeorm/blob/b9ae4133a1ccb2a3894e7f502ccdc8ebec00719d/src/driver/mysql/MysqlDriver.ts#L44

**Comment by HoldYourWaffle** [comment]
The following worked for me (using the aforementioned [express-mysql-session](https://github.com/chill117/express-mysql-session)):

```typescript
import { createConnection } from 'typeorm'
import { MysqlDriver } from 'typeorm/driver/mysql/MysqlDriver'

// ... snip ...

createConnection({
	// ... snip ...
}).then(connection => {
	const MySQLStore = MySQLSessionStore(session);

	app.use(session({
		// ... snip ...

		store: new MySQLStore({}, (connection.driver as MysqlDriver).pool, err => {
			// ... snip ...
		})
	}));
	
	// ... snip ...
});
```

> But this is internal property and it may change in future.
Any hopes on 'officially' exposing this functionality?

**Comment by moltar** [comment]
Maybe instead of exposing the pool, we need the ability to supply own pool instance, which then can be re-used.

That would provide more control over the pool and yield to the same result.

But I am also interested in re-using the pool with other modules.

Pool re-use is extremely important on Heroku, because of limited connections provided.

**Comment by imnotjames** [comment]
This would be very difficult as we do a lot with the connection pool already - having something else poking at it at the same time could cause a lot of issues depending on the specific pool / connection implementation.

You can access the underlying connections through various escape hatches but I don't see a big push for this & it would mostly make the API more complex & more difficult to maintain.
