### ISSUE TITLE
How to create column with type Numeric

### ISSUE THREAD

**Issue by nikoliveira** [typeorm/typeorm#4025]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I want use numeric columns, but when run the migrations a column decimal is generated.

`
    @Column("numeric")
    aNumericColumn: number;
  `
![image](https://user-images.githubusercontent.com/23386937/56518640-50281200-6516-11e9-819d-131d05a1a11d.png)

**Comment by vlapo** [comment]
Mysql do not have separate `NUMERIC` column type. It is just a synonym for `DECIMAL`. Try create table directly over SQL and you will see `NUMERIC` column is converted into `DECIMAL(10,0)` or similar.

From mysql docs:
> DEC[(M[,D])] [UNSIGNED] [ZEROFILL], NUMERIC[(M[,D])] [UNSIGNED] [ZEROFILL], FIXED[(M[,D])] [UNSIGNED] [ZEROFILL]
These types are synonyms for DECIMAL. The FIXED synonym is available for compatibility with other database systems.
