### ISSUE TITLE
MongoDB find returns same id for all Object ID fields

### ISSUE THREAD

**Issue by judemanutd** [typeorm/typeorm#4026]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

### Model

```ts
@Entity({ database: MONGO_DATABASE_NAME })
export class Items {
  @ObjectIdColumn()
  id: ObjectID;

  @ObjectIdColumn()
  id_student: ObjectID;

  @ObjectIdColumn()
  id_teacher: ObjectID;
}
```
### Query to run 

```ts
const repo = getMongoRepository(Items, MONGO_CONNECTION_NAME);
const data = await repo.find({
  where: {
   id_student: new ObjectID("5c9fc905cd23655349ccb58a,"),
  },
});
```
### Actual Output

 ```json
[  
   {  
      "id":"5ca31a45d2fb9001c7056af2",
      "id_student":"5ca31a45d2fb9001c7056af2",
      "id_teacher":"5ca31a45d2fb9001c7056af2"
   }
]
```

### Expected Output

```json
[  
   {  
      "id":"5ca31a45d2fb9001c7056af2",
      "id_student":"5c9fc905cd23655349ccb58a",
      "id_teacher":"5c9882d55b83863f5d5ff01d"
   }
]
```

### Values in the database

```json
{  
   "_id":{  
      "$oid":"5ca31a45d2fb9001c7056af2"
   },
   "id_student":{  
      "$oid":"5c9fc905cd23655349ccb58a"
   },
   "id_teacher":{  
      "$oid":"5c9882d55b83863f5d5ff01d"
   }
}
```
As you can see the id fields are duplicated for the given query even though the actual data in the database is different. Using an `aggregate` query returns the correct results but `find` returns the above irregularities.

**Comment by imnotjames** [comment]
If you don't define the `name` option in `@ObjectIdColumn` it defaults to `_id`.  Set the `name` property like `@ObjectIdColumn({ name: 'id_student' })` and it should work fine.

If you'd like to fix this, PRs welcome.
