### ISSUE TITLE
Updating using query builder with inner join

### ISSUE THREAD

**Issue by ajayvardhan** [typeorm/typeorm#4029]
**Issue type:**

[* ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[* ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ *] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm trying to update a column in my table using another column in the same table. Is there any way to use an inner join inside an update query where I can do this?

I want to do something like 

```
UPDATE users u
JOIN users s ON s.ID = u.ID
SET u.column1 = u.column2 + "some test string"
```
Using Query builder - 
 
```
await getConnection()
            .createQueryBuilder()
            .update(User)
            .set({ column1: () => "column2 + "some test string"})
	    .execute()
```

Is there any way where I can access column2 when I'm setting column1. I want to do this for all the rows in the table.

**Comment by Kononnable** [comment]
I think this is mentioned in the docs and you almost wrote it(just escaping is messed up) - https://github.com/typeorm/typeorm/blob/master/docs/update-query-builder.md#raw-sql-support

**Comment by ajayvardhan** [comment]
thanks!
