### ISSUE TITLE
Will there be auto-migrations generator like in DoctrineMigrations?

### ISSUE THREAD

**Issue by idchlife** [typeorm/typeorm#403]
Hi! Right now without auto-migrations I'm wondering, is there easy way to just collect SQL from syncing and just save it into file?

**Comment by pleerock** [comment]
This is must-have feature and I plan to do it. However right now there so many other issues needs to be resolved, my hands just didnt touch this part yet.

**Comment by idchlife** [comment]
@pleerock got it, thanks!

**Comment by pleerock** [comment]
basic generation functionality is landed since `0.1.0-alpha.17`. It has some features missing plus it do not generate sql for `down` method yet. Start testing it 🏭

**Comment by GuillaumeNury** [comment]
@pleerock Awesome work !
I tried `migrations:generate` in `0.1.0-alpha-19`. Migration script contains all what is needed to update/add/remove columns, but he does not have anything about creating missing table.

**Comment by vance** [comment]
Any good way to configure it with naming strategy?

**Comment by pleerock** [comment]
@GuillaumeNury hmm thats strange, are you sure about it? It should create schema for new entities as well. Maybe you forgot to specify your entities in orm configuration?

@vance what do you mean?

**Comment by ddyrcz** [comment]
Is there any instruction how to use the `migrations:generate` command?

**Comment by yoz** [comment]
@vance maybe see #1482?

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.

**Comment by LogansUA** [comment]
@pleerock Sorry for popping this issue up but question is still remain for me.

Can we somehow collect all synching queries and write them to some file?

For now the only way I see to write custom logger and define method `logQuery` but filter those which are `SELECT/DELETE/UPDATE`. Is there better way to do it?

**Comment by pleerock** [comment]
yes we can, there is a migration:generate command that you can use, see CLI documentation.
