### ISSUE TITLE
SchemaBuilder generates unneeded queries for varchar array

### ISSUE THREAD

**Issue by tonyxiao** [typeorm/typeorm#4030]
**Issue type:**
[x] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**
[x] `0.2.16` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following entities

```ts
@Entity()
class User {
  @Column('varchar', { array: true, default: '{}' })
  attachmentIds!: string[]
}
```

Immediately after running `typeorm schema:sync`, running `typeorm schema:log` would produce the following lines

```
----------------------------------------------------------------
-- Schema syncronization will execute following sql queries (1):
----------------------------------------------------------------
ALTER TABLE "public"."user" ALTER COLUMN "attachment_ids" SET DEFAULT '{}'::varchar[];
```

This is unexpected and throws off our logic that detects whether schema is up to date. 

Edit: Could it be related to the default value?

**Comment by vlapo** [comment]
Did you try `default: []`?

**Comment by tonyxiao** [comment]
Setting `default: []` will in fact generate the following invalid sql query. 
```
ALTER TABLE "public"."user" ALTER COLUMN "attachment_ids" SET DEFAULT '[]'
```

**Comment by vlapo** [comment]
Seems like bug with sync default values for array for me. Try check this later.

**Comment by karl-agnes** [comment]
Hello!
Any progress on this issue?

**Comment by AlexMesser** [comment]
This was fixed and released. Please update your TypeORM version to the latest and reopen this issue if the error persists.
