### ISSUE TITLE
How to inherit multiple columns/classes? 

### ISSUE THREAD

**Issue by alexeightsix** [typeorm/typeorm#4031]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have a slug column and timestamps columns I want to be able to re-use across other models inside my application. 

How can I "extend" both of these classes into my main entity? I've read there's Mixins but not sure if it will work with TypeORM? Is there any examples or anyone have any suggestions?

// timestamps.ts
export class Timesamps {
// ....
    @CreateDateColumn()
    created_at: string;

    @UpdateDateColumn()
    updated_at: string;

}

// slug.ts
export Class Slug {
....
 @Column({type: "varchar", unique: true, length: 255, nullable: false})
    @Length(5, 25)
    @IsSlug({
        message: "Text must be a valid slug."
    })
    slug: string;
}

// Status.ts 
@Entity()
class Status ... (should have access to all the methods from the two classes above)

How can Status inherit both the slug and timestamp classes?

Thanks

**Comment by vlapo** [comment]
Try mixins https://stackoverflow.com/questions/26948400/typescript-how-to-extend-two-classes. Did not test it, so let me know if it helped.

**Comment by alexeightsix** [comment]
@vlapo I ended up trying a few variations of this method but will try again tonight with post some examples.
Thanks

**Comment by alexeightsix** [comment]
@vlapo 

I wasn't able to get it working, I tried various libraries and what usually happens is the 2nd class that gets defined won't work:

 AssertionError: expected { Object (skip_slug_generation, skip_validation, ...) } to have own property 'created_at'

The second object (Timestamps as a created_at field) but they are not visible.

Are you aware of a "type orm" way to do this? Or any examples of somebody doing something similar?

**Comment by vlapo** [comment]
Do not know way how to do it now. Maybe using schemas https://typeorm.io/#/separating-entity-definition. Will check this later. Or maybe another developer will help.

**Comment by alexeightsix** [comment]
@vlapo 

I was able to find an example on GitHub but it doesn't work for me, I may try to download their entire repo and see if it's an issue with my code or maybe it's because of a different version of one of the packages I'm using?

https://github.com/vc-devs/vc-devs-api-v2/blob/714aa24acd10f1c367a0e84cf75f8c68091a4027/src/modules/school/school.entity.ts

**Comment by alexeightsix** [comment]
@vlapo 
Not sure what im doing wrong but unfortunately it's not working.  

import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, BeforeInsert, AfterLoad } from "typeorm";
import { mixin } from 'magical-mixin'
import { Slug } from '../inheritance/Slug';
import { Timestamps } from '../inheritance/Timestamps';

class MyClass extends mixin(Timestamps, Slug) { }

@Entity('status')
export class Status extends MyClass {
    @PrimaryGeneratedColumn()
    id: number;

    @Column("varchar", { length:  100})
    name: string; 
}

**Comment by Kononnable** [comment]
You would probably have to compose mixins with single table inheritance, to make it work or add typeorm metadata manually.
I would really recommend using entity schemas in your case - it's easy to achieve what you want in that approach.

**Comment by alexeightsix** [comment]
> You would probably have to compose mixins with single table inheritance, to make it work or add typeorm metadata manually.
> I would really recommend using entity schemas in your case - it's easy to achieve what you want in that approach.

@Kononnable 
Do you have any links to some examples of either option which resolves the same problem as I'm having?

**Comment by Kononnable** [comment]
https://typeorm.io/#separating-entity-definition/extending-schemas

**Comment by abinici** [comment]
@alexeightsix, I have an example which I think solves your issue.

To inherit columns in TypeORM you need to write an abstract class which your entity will inherit from. So I wrote a function that returns an abstract class through a class expression:

```Typescript
export type Constructor<T = {}> = new (...args: any[]) => T;

export function EntityWithBase<TBase extends Constructor>(Base: TBase) {
    abstract class AbstractBase extends Base {
        @PrimaryGeneratedColumn()
        id: number;
    }
    return AbstractBase;
}

export function EntityWithTenant<TBase extends Constructor>(Base: TBase) {
    abstract class AbstractBase extends Base {
        @Column({ nullable: false })
        tenantId: number;
    }
    return AbstractBase;
}

export function EntityWithDates<TBase extends Constructor>(Base: TBase = class { } as any) {
    abstract class AbstractBase extends Base {
        @Column({
            type: 'timestamp without time zone',
            nullable: true
        })
        public updatedAt: number;

        @Column({
            type: 'timestamp without time zone',
            nullable: true
        })
        public createdAt: number;

        @BeforeUpdate()
        public setUpdatedAt() {
            this.updatedAt = Math.floor(Date.now() / 1000);
        }

        @BeforeInsert()
        public updateDates() {
            const time = Math.floor(Date.now() / 1000);
            this.createdAt = time;
            this.updatedAt = time;
        }
    }
    return AbstractBase;
}
```

And here is how to use these mixins with an entity:

```Typescript
export class EmptyClass {}

@Entity('Users')
export class UserEntity extends EntityWithDates(EntityWithTenant(EntityWithBase(EmptyClass))) {

    @Column({
        name: 'EmailAddress',
        length: 256
    })
    email: string;

}
```

By using these functions, we end up building a chain of subclasses:

```
UserEntity > EntityWithDates > EntityWithTenant > EntityWithBase
```

When I run the application, TypeORM is able to sync this entity correctly with the database:

```Sql
CREATE TABLE "public"."Users" (
    "Id" int4 NOT NULL DEFAULT nextval('"Users_Id_seq"'::regclass),
    "TenantId" int4 NOT NULL,
    "UpdatedAt" timestamp,
    "CreatedAt" timestamp,
    "EmailAddress" varchar(256) NOT NULL,
    PRIMARY KEY ("Id")
);
```

**Comment by ruslanguns** [comment]
thank you @abinici ... I based my configurations based in your example: https://github.com/ruslanguns/nestjs-starter/tree/master/src/common/abstracts

**Comment by abinici** [comment]
@ruslanguns, glad I could help :)

Since my comment I have improved my base entities. I wasn't satisfied with using the EmptyClass to terminate the chain of subclasses. Instead, I decided to use the EntityWithBase for termination:

```TypeScript
export function EntityWithBase() {
    return class AbstractBase {
    };
}
```

I suggest you add base methods or columns to this base class. You could for example add a method to get the DTO for this entity ([Link](https://github.com/NarHakobyan/awesome-nest-boilerplate/blob/master/src/common/abstract.entity.ts)). And then I moved the id-column to a separate base entity class:

```TypeScript
export function EntityWithId<TBase extends Constructor>(Base: TBase) {
    abstract class AbstractBase extends Base {
        @PrimaryGeneratedColumn()
        id: number;
    }
    return AbstractBase;
}
```

This way the subclassing becomes prettier IMO:

```TypeScript
@Entity('Users')
export class UserEntity extends EntityWithDates(EntityWithTenant(EntityWithId(EntityWithBase()))) {
}
```

**Comment by dumasss163** [comment]
@abinici looks like not work for Tree entity...

**Comment by abinici** [comment]
@dumasss163 I haven't tried this code with Tree entity. Have you tried?

**Comment by dumasss163** [comment]
> @dumasss163 I haven't tried this code with Tree entity. Have you tried?

I tried, not work

**Comment by dumasss163** [comment]
> @dumasss163 I haven't tried this code with Tree entity. Have you tried?

I tried, and not work

**Comment by dumasss163** [comment]
> @dumasss163 I haven't tried this code with Tree entity. Have you tried?

@abinici I tried, and not work

**Comment by cantoute** [comment]
Has anyone tried lodash deep merge ?
https://stackoverflow.com/questions/52283935/deep-merge-two-class-instances

**Comment by imnotjames** [comment]
I think this was answered - you won't be able to use the decorators to do mixins like this.  Instead, you have to manually manage the entity schemas if you'd like to do mixins.

This is due to the nature of class and property decorators.

**Comment by meisammirkahromi** [comment]
Thanks @abinici for this solution, this works fine. The only issue is that if you, for some reason, what to have any kind of relation in the **abstract class**, like ManyToOne, you cannot reference back to EntityWithTenant as it is not a BaseEntity. 

Imagine you have TenantType entity 
class TenantType extends BaseEntity {
   ...
   
   @OneToMany(() => EntityWithTenant, entitiyWithTenant => entitiyWithTenant.tenantType)
   entityWithTenant: EntityWithTenant
}

are there any work around inside for that too?

**Comment by abinici** [comment]
Glad I could help @meisammirkahromi.

Adding relations to these abstract classes is tricky, because they are dynamically defined you cannot reference them.

I am not sure if this is a solution, but maybe you could solve it if you export the class:

```
export class ClassEntityWithTenant {
    @ManyToOne(() => TenantType, (tenant) => tenant.entityWithTenant, { nullable: false })
    @JoinColumn({
        name: 'TenantId',
        referencedColumnName: 'id'
    })
    tenantType: TenantType
};

export function EntityWithTenant() {
    return ClassEntityWithTenant;
}
```

And then reference it from your TenantType like this:

```
export class TenantType extends BaseEntity {
    ...
    @OneToMany(() => ClassEntityWithTenant, inv => inv.tenantType)
    entityWithTenant: ClassEntityWithTenant;
}
```

But for this to work, you must use EntityWithTenant like a leaf in your mixins:

```
@Entity('Users')
export class UserEntity extends EntityWithDates(EntityWithTenant(EntityWithBase(EntityWithTenant))) {

    @Column({
        name: 'EmailAddress',
        length: 256
    })
    email: string;

}
```

**Comment by meisammirkahromi** [comment]
Thanks for the prompt reply. 
I am not sure if I understood it correctly, because the EntityWithTenant is an abstract class returned by its wrapper function. 

```
export function EntityWithTenant<TBase extends Constructor>(Base: TBase) {
    abstract class AbstractBase extends Base {
        @Column({ nullable: false })
        tenantId: number;
    }
    return AbstractBase;
}
```

**Comment by abinici** [comment]
The trick is to expose the inner class and not only the wrapper function:

```
export class ClassEntityWithTenant {
    @ManyToOne(() => TenantType, (tenant) => tenant.entityWithTenant, { nullable: false })
    @JoinColumn({
        name: 'TenantId',
        referencedColumnName: 'id'
    })
    tenantType: TenantType
};

export function EntityWithTenant() {
    return ClassEntityWithTenant;
}
```

**Comment by meisammirkahromi** [comment]
But then I think in this case I cannot benefit from that abstract class which is the base for your initial workaround for inheriting multiple entities, right?

**Comment by abinici** [comment]
@meisammirkahromi Exactly, this solution introduces other challenges.

I have one more suggestion, its not pretty, but it should work with both inheriting multiple entities and having relations in the base class:

```Typescript
export class EntityWithTenantClass {
    @ManyToOne(() => TenantType, (tenant) => tenant.entityWithTenant)
    @JoinColumn({
        name: 'TenantId',
        referencedColumnName: 'id'
    })
    tenantType: TenantType;
}

export function EntityWithTenant<TBase extends Constructor>(Base: TBase) {
    abstract class AbstractBase extends Base {
        @ManyToOne(() => TenantType, (tenant) => tenant.entityWithTenant)
        @JoinColumn({
            name: 'TenantId',
            referencedColumnName: 'id'
        })
        tenantType: TenantType;
    }
    return AbstractBase;
}

export class TenantType extends BaseEntity {
    @OneToMany(() => EntityWithTenantClass, inv => inv.tenantType)
    entityWithTenant: EntityWithTenantClass;
}

@Entity('Users')
export class UserEntity extends EntityWithDates(EntityWithTenant(EntityWithBase())) {

    @Column({
        name: 'EmailAddress',
        length: 256
    })
    email: string;

}
```

The key part is that you have the defined the base class both inside the wrapper function and outside the wrapper function. The class outside the wrapper function is for relations. And the class inside the wrapper function is for inherit mixin. In other words, you have in a way two definitions of the same class.

**Comment by meisammirkahromi** [comment]
Hats off man, hats off!

**Comment by raezon** [comment]
Base not found

**Comment by abinici** [comment]
@raezon @ngouy 

You are right, there is an error in my original comment. I will update my comment.

Try the following. Change the code for EntityWithBase from:

```typescript
export function EntityWithBase() {
    abstract class AbstractBase extends Base {
        @PrimaryGeneratedColumn()
        id: number;
    }
    return AbstractBase;
}
```

to:

```typescript
export function EntityWithBase() {
    abstract class AbstractBase {
        @PrimaryGeneratedColumn()
        id: number;
    }
    return AbstractBase;
}
```

EntityWithBase does not need a Base because its the end of the chain.

Hope it fixes the issue :)

**Comment by ngouy** [comment]
yea. I managed to do something like that on my end, thanks so much for your help.

I combined that with https://github.com/1nVitr0/lib-ts-mixin-extended

to have this beauty:
```ts
@Entity({ name: "teacher" })
export class TeacherEntity extends mixin(
  BaseEntityMixin,
  AuditableEntityMixin,
  SoftDeletableMixin,
  UserFieldsMixin,
) {
  // my teacher specific attributes
  ...
  }
  ```
