### ISSUE TITLE
How to force create when call save()?

### ISSUE THREAD

**Issue by nikoliveira** [typeorm/typeorm#4034]
**Issue type:**

[x] question

**Database system/driver:**

[x] `mysql`

**TypeORM version:**

[x] `latest`

I'm  loading a entity with 13 entities dependents, and I have that duplicate this register.
But when I run my `user.findOne (id)` and after `user.save ()` he is updated, is there any possibility to force a new register for my main entity and dependencies?

**Comment by vlapo** [comment]
I really did not get you. Could you please provide some simple entity example and procedure of operations with expected and current behaviour?

**Comment by nikoliveira** [comment]
I have a user and want duplicate this user. For exemple.

`
let myUser = await User.findOne("abc-123", {relations: [ "skils", "equipaments", "avaliables", ... ] });
let newUser = await myUser.create( );
`

This new User I want that have  news "skills", "equipments", "available" too

**Comment by Kononnable** [comment]
I guess you're just looking for javascript spread syntax. But remember to clone object without primary key properties(or delete them after cloning/change them if they're not autogenerated by db).
```typescript
const x = new Ingredient();
x.name = 'a';
await x.save();
const y = Ingredient.create({ ...x, id:undefined })
await y.save();
```

**Comment by rustamwin** [comment]
No answer from the author. Closing

**Comment by rachmanzz** [comment]
I have same issue, @Kononnable answer not solve my problem.
there any way to force create ?
