### ISSUE TITLE
InsertResult.generatedMaps is an ObjectLiteral[]?

### ISSUE THREAD

**Issue by osdiab** [typeorm/typeorm#4037]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When I use an `EntityManager` to insert data like so:

```typescript
    const result = await transactionEntityManager.insert(UserFollow, {
      fromId: fromUser,
      toId: toUser
    });
```

I can get the inserted elements by calling `result.generatedMaps()`, which returns an `ObjectLiteral[]` that happens to be the same shape as an actual `Entity`.

I thought, wouldn't it be cooler if `InsertResult` was declared as a generic that could take in an `Entity` class? It's an easy change - change `InsertResult.ts` to look like this:

```typescript
import { ObjectLiteral } from "../../common/ObjectLiteral";
/**
 * Result object returned by InsertQueryBuilder execution.
 */
export declare class InsertResult<Entity = ObjectLiteral> {
  /**
   * Contains inserted entity id.
   * Has entity-like structure (not just column database name and values).
   */
  identifiers: Entity[];
  /**
   * Generated values returned by a database.
   * Has entity-like structure (not just column database name and values).
   */
  generatedMaps: Entity[];
  /**
   * Raw SQL result returned by executed query.
   */
  raw: any;
}
```

And throw in the generic into the `EntityManager.insert()` return type. But I noticed that the comments say that these have "entity-like structure", which implies that they aren't actually `Entity` instances.

What exactly does that mean? Trying to understand what separates an `Entity` from an entity-like structure.

**Comment by osdiab** [comment]
In the meantime I'm just casting the value, but should I be doing something to "upgrade" these "entity-like" things into real entities? or is that safe to do?

**Comment by vlapo** [comment]
In this case `Entity` is instance of entity class with filled data from database. But `entity-like structure` means it is just raw json/data from database. It is not instance of entity so it has to be `ObjectLiteral`.

`insert(...)` method is just raw insert and typeorm will not convert results into entities. If you want entities returned you have to use `save(...)` method.

**Comment by osdiab** [comment]
Is there a type then that could denote an ObjectLiteral with the same shape as an entity? Like would it make sense to make ObjectLiteral be a generic as well, so that I can denote that we know what the shape would be like but not actually make it a proper Entity class (which is all I need for this endpoint)? If that’s not something we want in typeorm typings that’s fine I can do the same in my repo and use a type suggestion, but seems like a natural primitive to be expressible by the library

**Comment by vlapo** [comment]
I think `ObjectLiteral` is not 1:1 with `Entity`. There are some processes between converting raw data into entity.

**Comment by dberardo-com** [comment]
is it possible to usa save to insert only ? in particular i want to avoid the 2 queries that save does, basically i would like insert() to return an entity like save ...
