### ISSUE TITLE
.select('TOP 10') breaking query in MSSQL

### ISSUE THREAD

**Issue by d30jeff** [typeorm/typeorm#4048]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
return getRepository(BreakdownJob)
  .createQueryBuilder('bj')
  .select('TOP 10')
  .addSelect('e.id', 'equipmentId')
  ...
```

**Error**

`error: { RequestError: Incorrect syntax near the keyword 'TOP'.`

**Produced Query**

```
SELECT "e"."id" AS "equipmentId", ..more fields, TOP 10 FROM "breakdown_jobs" "bj"
```

MSSQL expects `TOP 10` to appear first before the rest of the fields

Is there a workaround for this?

Thanks

**Comment by alfonsoal1983** [comment]
If you want to take the first 10 results you should use the take or the limit, depending on the case you will need one or the other. Here is the documentation:

https://github.com/typeorm/typeorm/blob/master/docs/select-query-builder.md#using-pagination

**Comment by d30jeff** [comment]
@alfonsoal1983 

Thanks, I ended up using that.
