### ISSUE TITLE
Changes to default configuration not detected in migrations

### ISSUE THREAD

**Issue by staff0rd** [typeorm/typeorm#405]
If I create a column that does not have a `default` value configured, adding a `default` after a migration has no effect.  Likewise, creating a column that has a `default` value and removing that `default` configuration after a migration will not cause the `default` to be removed on successive migrations.

Using the pg driver.

```typescript
@Entity()
export class MyEntity {
    @Column("boolean") // cannot add default after first migration
    myField1: boolean

    @Column({type: "boolean", default: false}) // edits to default are not reflected after first migration
    myField2: boolean
}
```

**Comment by pleerock** [comment]
are you using `migrations` term. You probably mean schema synchonization that performs each time you run the application, right? If yes, then this issue is fixed in `0.1.0-alpha.10`

**Comment by pleerock** [comment]
are you able to confirm this issue?

**Comment by pleerock** [comment]
closing as no answer from reportee.

**Comment by yogevlahyani** [comment]
I have the same bug
