### ISSUE TITLE
FindOneOptions Array.map Compatibility

### ISSUE THREAD

**Issue by Flash619** [typeorm/typeorm#4053]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I found a simple function online for getting field selections from GraphQL `fieldNodes` and adjusted it to be typesafe.

```ts
const mapAttributes = <T>(model: T, { fieldNodes }): keyof T[] => {
    const columns = new Set(Object.getOwnPropertyNames(model));
    let requestedAttributes = fieldNodes[0].selectionSet.selections.map(({ name: { value } }) => snakeCase(value));
    requestedAttributes = requestedAttributes.filter(attribute => columns.has(attribute));
    return requestedAttributes;
};

export const resolvers: IResolvers<any, APIContext> = {
    Query: {
        user: (obj, { id }, ctx, inf) => {
            const select: keyof User[] = mapAttributes(User, inf) as keyof User[];
            return ctx.db.getRepository(User).findOne(id, { relations: ['department'], select: select });
        },
    },
};
```

When I try to plug the resulting field names into the findOne selection parameter, I get the following error.

```
Error:(36, 88) TS2322: Type 'number | "length" | "toString" | "toLocaleString" | "pop" | "push" | "concat" | "join" | "reverse" | "shift" | "slice" | "sort" | "splice" | "unshift" | "indexOf" | "lastIndexOf" | ... 15 more ... | "flatMap"' is not assignable to type '("id" | "employeeId" | "userName" | "firstName" | "lastName" | "email" | "hash" | "isGlobalViewer" | "isManager" | "isPayroll" | "isAdmin" | "createdOn" | "enabled" | "department" | ... 6 more ... | "subordinates")[]'.
  Type 'number' is not assignable to type '("id" | "employeeId" | "userName" | "firstName" | "lastName" | "email" | "hash" | "isGlobalViewer" | "isManager" | "isPayroll" | "isAdmin" | "createdOn" | "enabled" | "department" | ... 6 more ... | "subordinates")[]'
```

The definition for select appears to map only the keys of the provided Entity which is causing any array properties to trigger a typescript error.

```ts
select?: (keyof Entity)[];
```

Is there any known way around this? I don't know of a good way to automate field selection with this limitation.

**Comment by Kononnable** [comment]
Not really sure what you're doing here, but shouldn't it be like that?
```typescript
export const resolvers: IResolvers<any, APIContext> = {
    Query: {
        user: (obj, { id }, ctx, inf) => {
            const select: (keyof User)[] = mapAttributes(User, inf) as (keyof User)[];
            return ctx.db.getRepository(User).findOne(id, { relations: ['department'], select: select });
        },
    },
};
```
You're probably don't want to pass properties of the array object, just properties of the element of an array.

**Comment by imnotjames** [comment]
Hope this answered your question, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
