### ISSUE TITLE
Allow passing Javascript types to @Column

### ISSUE THREAD

**Issue by vjpr** [typeorm/typeorm#4055]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When using Typescript, column types are inferred from the field's static types. However when using JS or even `@babel/preset-typescript` this metadata is not available.

It seems that TypeORM requires you to use a db-specific column type. I would like to provide the JS primitive type (string, number, etc).

**Comment by imnotjames** [comment]
Pretty sure this is now possible.  However, TS types can't be passed because they are not values.

https://github.com/typeorm/typeorm/blob/master/src/driver/types/ColumnTypes.ts#L206
