### ISSUE TITLE
Is there any option to have a batch update? I am trying to update 130 records based on indiviual ID's and its taking enough time to casue teh performance issue

### ISSUE THREAD

**Issue by rk-ravikiran** [typeorm/typeorm#4057]
**Issue type:**

[ X] question
[X ] documentation issue

**Database system/driver:**
[ X] `mysql` / `mariadb`

**TypeORM version:**

[X] `latest`

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
Please put your question in the issue content, do not put it into it's title.

You can use e.g. query builder for that with where similar to: `.where("post.authorId IN (:...authors)", { authors: [3, 7, 9] })`

**Comment by rustamwin** [comment]
Closing as no response from the author.
