### ISSUE TITLE
How to run Migration with specific connection

### ISSUE THREAD

**Issue by nikoliveira** [typeorm/typeorm#4062]
**Issue type:**

[x] question

**Database system/driver:**

[x] `mysql` / `mariadb`

**TypeORM version:**

[x] `latest`

In my ormconfig.ts I have two connection.

`[{
     "name": "dev",
     ....
},
{
      "name": "prod",
       ...
}]`

How to run typeorm migration:run just "prod" connection?

**Comment by Kononnable** [comment]
I think you're looking for that :)
https://github.com/typeorm/typeorm/blob/e85c0124bdfc59a1bad2e54865bfc2a43199eb26/src/commands/MigrationRunCommand.ts#L19-L22
