### ISSUE TITLE
WHERE, Date, and BETWEEN for MongoDB

### ISSUE THREAD

**Issue by limweb** [typeorm/typeorm#4064]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
how to  find  date between

**Comment by marcosfede** [comment]
any updates on this? this is not working:
```javascript
repo.find({
     where: {
       fields: {
         resolutiondate: Between(new Date(startDate), new Date(endDate)),
       },
     },
   })
```
I used a cursor query for the time being:
```javascript
repo
    .createEntityCursor({
      'fields.resolutiondate': {
        $gte: startDate,
        $lte: endDate,
      },
    })
```

**Comment by alexjs87** [comment]
```
repo.find({
     where: { 
         resolutiondate: {
        $gte: new Date(startDate),
        $lt: new Date(finalDate),
      },   
     },
   })
```

**Comment by danielehrhardt** [comment]
>  where: { 
>          resolutiondate: {
>              $gte: new Date(startDate),
>              $lt: new Date(finalDate),
>          },   
>      },
```

.count({
      where: {
        date: {
          $gte: new Date('20' + year),
          $lt: new Date('20' + (+year + 1).toString()),
        },
      },
    });
```
somehow does not work with .count

**Comment by imnotjames** [comment]
Use `$expr` with count.

This has been answered.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by bernardorz** [comment]
```js
 const exampleBetween = await getMongoRepository(User).find({
            where : {
                createdAt : {
                    $gte : startDate,
                    $lt : endDate
                }
            }
        })
```

You have an example, but I wanted to know how to use not between
