### ISSUE TITLE
Express + TypeORM Example doesn't work as expected

### ISSUE THREAD

**Issue by lnryan** [typeorm/typeorm#4065]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The express example doesn't appear to have been tested as a working application. If you run through the code as is, the services will never resolve, because they don't provide a response. 

Using a `return` statement is also not typical usage in `express` (see [Getting Started with Express](https://expressjs.com/en/starter/hello-world.html) ) so if it's included here for a reason, it would make sense to mention why.

For the 5 examples routes that illustrate the basic CRUD activities, where it has

```
    return userRepository. ...
```

it should have 
```
   resp.success( ... )
```
or `return resp.success(...)` or `resp.json` etc. 

Also, the examples are  missing `await` and do not return the respected results as is, even where they are declared as `async` functions. For example, the `app.get('/users',...)` route returns empty. But changing this to `await userRepository.find()` fixes the issue and returns the stored records.

Likewise, the update example, creates additional records the way it is written 
```
app.put("/users/:id", function(req: Request, res: Response) {
        const user = userRepository.findOne(req.params.id);
        userRepository.merge(user, req.body);
        return userRepository.save(user);
    });
```

changing it to the below, fixes it
```
app.put("/users/:id", function(req: Request, res: Response) {
        const user = await userRepository.findOne(req.params.id);
        userRepository.merge(user, req.body);
        return userRepository.save(user);
    });
```

**Comment by imnotjames** [comment]
This has been fixed.
