### ISSUE TITLE
Auto incrementing column does not auto-increment

### ISSUE THREAD

**Issue by robertmain** [typeorm/typeorm#4067]
**Issue type:**

- [ ] question
- [x] bug report
- [ ] feature request
- [x] documentation issue

**Database system/driver:**

- [ ] `cordova`  
- [ ] `mongodb`  
- [ ] `mssql`  
- [x] `mysql` / `mariadb`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `cockroachdb`
- [ ] `sqlite`
- [ ] `sqljs`
- [ ] `react-native`
- [ ] `expo`

**TypeORM version:**

- [x] `latest`
- [ ] `@next`
- [ ] `0.x.x` (or put your version here)

When using @PrimaryGeneratedColumn, TypeORM isn't setting the column as `AUTO_INCREMENT`, meaning that if I try to insert values into the table outside of TypeORM, I get duplicate key query errors.

1. Configure TypeORM to connect to MariaDB with `mysql` driver.
1. Use the following repository/entity

Repository:
```ts
import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity()
export class Ingredient {
  @PrimaryGeneratedColumn()
  public id: number;

  @Column('text')
  public name: string;
}
```

Migration:
```ts
import {
  MigrationInterface,
  QueryRunner,
  Table,
} from 'typeorm';

export class createIngredientsTable1555981124297 implements MigrationInterface {
  private tableName: string = 'ingredient';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(new Table({
      name: this.tableName,
      columns: [
        {
          name: 'id',
          type: 'int',
          isPrimary: true,
        },
      ],
    }));
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable(this.tableName);
  }
}
```

Generated SQL: 
```sql
CREATE TABLE `ingredient` (
  `id` int NOT NULL,
  PRIMARY KEY (`id`)
)
```

**Comment by robertmain** [comment]
To follow up on this, it looks like my migration requires the following:

```ts
{

  isGenerated: true,
  generationStrategy: 'increment',
}
```

However, I'm still leaving this open as I think this may be a documentation issue. My understanding from the documentation was that `@PrimaryGeneratedColumn` would perform this

**Comment by Kononnable** [comment]
`@PrimaryGeneratedColumn` would do it if you have enabled synchronization, or generated migration by typeorm. If you decide to write migration yourself you're taking the responsibility of database schema.

**Comment by robertmain** [comment]
Thanks for getting back to me on this. Yeah, I deliberately disabled synchronization because it was causing headaches - figuring out whether I'd make a schema change with a migration, or synchronization had. 

As for generated migrations - what do you mean? My migrations look like [this](https://github.com/robertmain/meal-plan/blob/master/src/migrations/1555981124297-createIngredientsTable.ts) - is there another way that I _should_ be doing it?

**Comment by Kononnable** [comment]
What I meant is that migration is written 'by hand', it's not generated by typeorm. There was a proposal to generate migrations like that, but it wasn't implemented(at least yet).

Migration is fine(after adding those two properties), but I don't see where in that case may be a docs issue. `@PrimaryGeneratedColumn` would perform that, but you've disabled schema sync and didn't generate migrations by typeorm. So there is no way in which typeorm can change your database schemas(set column as AUTO_INCREMENT).

**Comment by robertmain** [comment]
Right, but generating a migration using `typeorm generate migration` or whatever, just generates a stub file like the one above that you have to fill in the guts of, which produces the same outcome as described. Unless you're referring to TypeORM just changing the DB using synchronization, which is cool but feels a bit "magic" to me - hence why I turned it off.

>but I don't see where in that case may be a docs issue. 

Okay, fair enough. There's a couple of things here.

The docs say [here](https://typeorm.io/#/migrations/how-migrations-work) under the "Migrations" heading to use `@PrimaryGeneratedColumn` to set `AUTO_INCREMENT` in the database. This is true, but only when using synchronization(sidenote: the behavior described by you for synchronization - is [in my opinion] **NOT** migrations...just db schema sync). Unless I've missed it somewhere ,the documentation fails to mention the fact that this is no longer the case when writing migrations by hand - which most developers (including myself) do as it makes the project easier to bring up in dev(and prod).

**Comment by Kononnable** [comment]
First make sure you're running latest typeorm version when you call cli(`typeorm -v`). If you've got latest version running `typeorm migration:generate -n "mig"` should generate a migration file - with changes between your db and entities defined in code(not empty). 
For generating a stub there is a separate command `typeorm migration:create -n "mig"`.

**Comment by robertmain** [comment]
>If you've got latest version running typeorm migration:generate -n "mig"

Right, but I don't see how that solves the issue - that just generates migrations containing schema creation code [like I already have.](https://github.com/robertmain/meal-plan/blob/master/src/migrations/1555981124297-createIngredientsTable.ts)

**Comment by Kononnable** [comment]
It generates migrations with schema changing statements based on your typescript entity definition. You don't have to write them by hand so you won't forget to adding `isGenerated: true,` because orm will generate that for you.
Information about PK will be in two places(same as in your current setup), but if you don't write your own schema changing sql statements it will be the same information(orm takes care of that).

In other ways - you can't expect to eat a cookie and have a cookie. If you wan't to disable ORM ways of synchronizing entities with db state(schema sync and generated migrations) you can - but you can't assume that ORM will do anything about those differences if you told it not to.

**Comment by robertmain** [comment]
>Information about PK will be in two places(same as in your current setup), but if you don't write your own schema changing sql statements it will be the same information(orm takes care of that).

Except that information is now (essentially duplicated)....

>In other ways - you can't expect to eat a cookie and have a cookie. If you wan't to disable ORM ways of synchronizing entities with db state(schema sync and generated migrations) you can - but you can't assume that ORM will do anything about those differences if you told it not to.

I understand that, but again - the documentation lead me to believe that annotating my entity with `@PrimaryGeneratedColumn` would somehow produce an auto-incrementing column when I ran my migrations. It feels as though the docs were written around the idea of schema sync, and then migrations were kind of an afterthought. This (in my opinion) isn't at all clear from the docs. I'm happy to PR it in, but I want to discuss first to make sure that such a change would be welcomed.

**Comment by Kononnable** [comment]
If you have an idea of making docs better please create PR. We can discuss concrete proposition there.

**Comment by jp-ryuji** [comment]
This seems to be fixed at least at 0.2.25, the latest version at this point in time.

**Comment by hitallow** [comment]
> To follow up on this, it looks like my migration requires the following in the `id` column:
> 
> ```ts
> isGenerated: true,
> generationStrategy: 'increment',
> ```
> 
> However, I'm still leaving this open as I think this may be a documentation issue. My understanding from the documentation was that `@PrimaryGeneratedColumn` would perform this

Thanks a lot!

**Comment by thyago608** [comment]
Olá dev, estava passando por um problema similar:

Tente mudar 'int' para 'integer':

                    {
                        name: "id",
                        type: "integer",
                        isPrimary:true,
                        isGenerated:true,
                        generationStrategy:'increment'
                    },

Estava com o problema de gerar o identificador único para cada registro no banco de dados.

**Comment by johnathanthedev** [comment]
> To follow up on this, it looks like my migration requires the following in the `id` column:
> 
> ```ts
> isGenerated: true,
> generationStrategy: 'increment',
> ```
> 
> However, I'm still leaving this open as I think this may be a documentation issue. My understanding from the documentation was that `@PrimaryGeneratedColumn` would perform this

This should really be included in documentation.
