### ISSUE TITLE
MissingDriverError: Wrong driver: "undefined" given.

### ISSUE THREAD

**Issue by feimosi** [typeorm/typeorm#4068]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm trying to run migrations, however, using the same ORM connection options that work on the server, the CLI throws: 
```sh
MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "sqljs", "react-native".
    at new MissingDriverError (/home/feimosi/Projects/saycaster-podcatcher/backend/src/error/MissingDriverError.ts:8:9)
    at DriverFactory.create (/home/feimosi/Projects/saycaster-podcatcher/backend/src/driver/DriverFactory.ts:55:23)
    at new Connection (/home/feimosi/Projects/saycaster-podcatcher/backend/src/connection/Connection.ts:125:43)
    at ConnectionManager.create (/home/feimosi/Projects/saycaster-podcatcher/backend/src/connection/ConnectionManager.ts:64:28)
    at Object.<anonymous> (/home/feimosi/Projects/saycaster-podcatcher/backend/src/index.ts:223:35)
    at step (/home/feimosi/Projects/saycaster-podcatcher/backend/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/feimosi/Projects/saycaster-podcatcher/backend/node_modules/tslib/tslib.js:114:57)
    at /home/feimosi/Projects/saycaster-podcatcher/backend/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/feimosi/Projects/saycaster-podcatcher/backend/node_modules/tslib/tslib.js:103:16)
``` 

I run it with the following command (based on [this article](https://wanago.io/2019/01/28/typeorm-migrations-postgres/)):
`ts-node ./node_modules/typeorm/cli -f ./src/orm.config.ts`

I'm sure `type: 'postgres'` property is set. Am I missing something?

**Comment by ccsCarolSerrao** [comment]
Same error hapens here!! =(

**Comment by KillerCodeMonkey** [comment]
solved it by export the config this way:

```
export = ORMConfig
```

**Comment by Kononnable** [comment]
@feimosi @ccsCarolSerrao 
Does the same situation happened to you and exporting config helped? If not we would have to have something to work on. We can't just guess what's wrong.

**Comment by feimosi** [comment]
I can confirm, @KillerCodeMonkey's solution works for me :+1:

**Comment by jhnns** [comment]
`export = ORMConfig` is the old TypeScript module format afaik.

This could be fixed in TypeORM by checking for a `default` property on the exported object.

**Comment by shawnkoh** [comment]
> `export = ORMConfig` is the old TypeScript module format afaik.
> 
> This could be fixed in TypeORM by checking for a `default` property on the exported object.

Agreed. This issue needs to be reopened.

**Comment by TrejGun** [comment]
@pleerock this is still an issue

**Comment by umarrasydan** [comment]
Still an issue

**Comment by WaterBleu** [comment]
is there an update on this particular issue?

**Comment by mukulvaidya** [comment]
> solved it by export the config this way in my ormconfig.ts:
> 
> ```
> export = ORMConfig
> ```

**Comment by jyotendra** [comment]
@KillerCodeMonkey works excellently, but I was using ormconfig.ts which was imported in another ts file to provide connection details (in TS.ed framework). Had to use ```import * as config from "./ormconfig.ts"``` for it to get imported without error.

Apparently, ```export = config``` exports as a module.

**Comment by rostgoat** [comment]
Have any of you tried deploying your apps to Heroku? using `export` I get `unexpected token export`

```
2020-03-25T05:07:57.946988+00:00 app[web.1]: export = ORMConfig
2020-03-25T05:07:57.946988+00:00 app[web.1]: ^^^^^^
2020-03-25T05:07:57.946988+00:00 app[web.1]: 
2020-03-25T05:07:57.946989+00:00 app[web.1]: SyntaxError: Unexpected token 'export'
```

**Comment by alitsvin** [comment]
For me there was needed also to configure "typeorm" script as described in typeorm [instruction](https://typeorm.io/#/using-cli/installing-cli)

**Comment by vithalreddy** [comment]
`module.exports = TypeORM;` working for me in latest version.

**Comment by marabesi** [comment]
Same here, I just switched my ormconfig.ts file from: 

```
export default connectionOptions;
```
to:

```
module.exports = connectionOptions;
```

Now it works as expected

**Comment by pak11273** [comment]
@KillerCodeMonkey solution still works for me

**Comment by snackycracky** [comment]
I had to set the environment variable: `TYPEORM_CONNECTION` to `postgres`

**Comment by kinjoyuya1219** [comment]
Same error happen（；＾ω＾） But, modify config file

```ormconfig.ts

// ormconfig.ts
import { ConnectionOptions } from 'typeorm';

export const config: ConnectionOptions = {
 // hogehoge
};

module.exports = config;
```

And then, below command, no problem.

```migration.fish

// fish. there is no '$' .
npx ts-node (npm bin)/typeorm migration:show
```

**Comment by khru** [comment]
> solved it by export the config this way in my ormconfig.ts:
> 
> ```
> export = ORMConfig
> ```

And if you have 2 connections on the same file, what do you do?

**Comment by khru** [comment]
I solve it creating an other ormconfig file, call ormconfig.cli.ts, in which I only have one connection and I had to exported with an `export =`

```typescript
require('dotenv').config();
import { ConnectionOptions } from 'typeorm';

const port: number = Number.parseInt(process.env.MYSQL_PORT);

const DatabaseConnectionTestConfiguration: ConnectionOptions = {
    name: process.env.MYSQL_TEST_NAME,
    type: 'mysql',
    host: 'localhost',
    port: port,
    username: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASSWD,
    database: process.env.MYSQL_DB_TEST,
    synchronize: true,
    dropSchema: true,
    logging: true,
    logger: 'file',
    entities: [__dirname + '/**/*.entity.ts'],
    migrations: [__dirname + '/**/*.migration.ts'],
    subscribers: [__dirname + '/**/*.subscriber.ts'],
    cli: {
      entitiesDir: __dirname + '/typeorm/entity',
      migrationsDir: __dirname + '/typeorm/migration',
      subscribersDir: __dirname + '/typeorm/subscriber',
    },
  };
  
  export = DatabaseConnectionTestConfiguration;
```

**Comment by Nastaliss** [comment]
The following seems to work just fine for me, maybe an update fixed this issue ?
```
// ormconfig.ts
export default {
  type: 'postgres',
  host: 'localhost',
  port: 5432,
  username: 'postgres',
  password: 'pass',
  database: 'filmash',
  entities: ['dist/**/*.entity{.ts,.js}'],
  synchronize: true,
}
```
```
// app.module.ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { MyModule } from './movie/my.module';
import { TypeOrmModule } from '@nestjs/typeorm';
import connectionOptions from './ormconfig';

const IMPORTED_MODULES = [MyModule];

@Module({
  imports: [TypeOrmModule.forRoot(connectionOptions), ...IMPORTED_MODULES],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

**Comment by allanmelo** [comment]
Still an issue. Resolved using @KillerCodeMonkey suggestion.

**Comment by valdineifer** [comment]
@Kononnable
> Does the same situation happened to you and exporting config helped? If not we would have to have something to work on. We can't just guess what's wrong.

Hi. What kind of info is needed? I have the same issue and the KillerCodeMonkey solution did not work for me. Now, when I run TypeORM (with `migration:show` for example), it returns nothing. I also create a [post on StackOverflow](https://stackoverflow.com/questions/66604876/typeorm-commands-return-nothing).

**Comment by jesus546** [comment]
bueno lo mio funciono solamente poniendo el ormconfig.json

**Comment by Macstyg** [comment]
Same issue for me. Fixed with [this comment](https://github.com/typeorm/typeorm/issues/4068#issuecomment-655963645)

**Comment by raulportela** [comment]
> Tive que definir a variável de ambiente: `TYPEORM_CONNECTION`para`postgres`

Here it work

**Comment by slice-harshil** [comment]
@KillerCodeMonkey 's solution worked for me.
earlier I was doing this :

import { ConnectionOptions } from "typeorm";
...
...
export const config_test: ConnectionOptions = {
  name: "default",
  type: "postgres",
  host:somehost,
  port:someport,
  ...

I added following line at the end of the file and it started working
export default config_test;

**Comment by miugel** [comment]
As a data point, I got this error because I was running my start command before running my typescript watch command.

**Comment by rohit-gh** [comment]
I'm only using ormconfig only for migrations. It does not work on server.
I have to use the object directly to inject the connection properties in my nodejs app.

**Comment by RinSabbit** [comment]
solved with changing `import`(not imports) order like this

```javascript
// same error happens in this order
// import { DatabaseConfigModule } from '@config/database/config.module';
// import { AppConfigModule } from '@config/common/config.module';
// ...

import { AppConfigModule } from '@config/common/config.module';
import { DatabaseConfigModule } from '@config/database/config.module';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [AppConfigModule, DatabaseConfigModule],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule implements NestModule {
}

```

**Comment by aq-gabriel** [comment]
it worked for me 😅😅😅😅😅

`db/index.ts`
 ```javascript
import { DataSource } from 'typeorm'

import ormconfig from  '../../ormconfig.json'

// I know this shouldn't be quite correct but I swear it works lol
const dataSource = new DataSource({ type: "postgres", ...ormconfig });  

dataSource.initialize()
  .then(() => console.log('Data Source has been initialized successfully!!!'))
  .catch((err) => console.error('Error during Data Source initialization!!!', err));
```

`ormconfig.json`

````JSON
{
  "host": "localhost",
  "port": 5433,
  "username": "postgres",
  "password": "root",
  "database": "health-postgres",
  "migrations": [
    "./src/db/migrations/*.ts"
  ],
  "cli": {
    "migrationsDir" : "./src/db/migrations/*.ts"
  }
}

**Comment by bertyhell** [comment]
Somewhere in my code i had an extra:
```
TypeOrmModule.forRoot(),
```

Next to the main:
```
TypeOrmModule.forRoot({
    ...config
})
```

Deleting the empty one, fixed this issue

**Comment by Mpilo-Pillz** [comment]
Thanks @bertyhell, I also had an empty  TypeOrmModule.forRoot(). Removing the empty one fixed it for me.

**Comment by akshayrajp** [comment]
Thanks @bertyhell , that was my issue as well.
