### ISSUE TITLE
Quotes missing around field when using innerJoin with Postgres

### ISSUE THREAD

**Issue by derblitz** [typeorm/typeorm#4069]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.2.16` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I seem to do something wrong. The issue is that the produced query has no quotes around the field names of the joined table.

### My model:
**Table 1:**
```
@Entity()
export class Collection extends BaseEntity {
    @PrimaryGeneratedColumn("uuid")
    id: string

    @Column()
    name: string

    @OneToMany(_type => UserCollection, (userCollection: UserCollection) => userCollection.collection)
    userCollections: UserCollection[];

```

**Table 2:**
```
@Entity()
export class UserCollection extends BaseEntity {

    @ManyToOne(_type => CollectionRight, collectionRight => collectionRight.userCollections, { primary: true })
    collectionRight: CollectionRight

    @ManyToOne(_type => User, user => user.userCollections, { primary: true })
    user: User

    @ManyToOne(_type => Collection, collection => collection.userCollections, { primary: true })
    collection: Collection
}
```

### Query:
```
        const r = await getRepository(Collection).createQueryBuilder('collection')
            .addSelect('userCollection.userId')
            .addSelect("collection.name")
            .innerJoin('collection.userCollections', 'userCollection')
            .getMany()
```

### Problem
The produced query (**userCollection.userId** needs to be in quotes as well but isn't): 
```
query failed: SELECT "collection"."id" AS "collection_id", "collection"."name" AS "collection_name", "collection"."config" AS "collection_config", "collection"."updatedAt" AS "collection_updatedAt", "collection"."deleted" AS "collection_deleted", "collection"."updatedById" AS "collection_updatedById", "collection"."name" AS "collection_name", "collection"."name", userCollection.userId FROM "collection" "collection" INNER JOIN "user_collection" "userCollection" ON "userCollection"."collectionId"="collection"."id"
```

I already tried several different variations, some I remember:
- I started with only select (and the fields of both tables in the select) instead of addSelect
- I tried innerJoinAndSelect
- I tried to add quotes in the query manually (the error disappears but the field is jsut ignored by the query generator)

**Comment by derblitz** [comment]
fyi: It also doesn't work if I use an alias for the selected fields.

**Comment by derblitz** [comment]
I also learned I would need to use getRawMany instead of getMany. This does not solve the issue.

**Comment by Kononnable** [comment]
It works for me after adding quotes `.addSelect('"userCollection"."userId"')`.

**Comment by chriszrc** [comment]
That's a useful workaround, but there are generic libraries like:

 https://github.com/nestjsx/crud

That won't know about specifically modifying the behavior of joins just for postgres. It would be more ideal to have it work without any specific postgres workarounds-

**Comment by derblitz** [comment]
I can live without a solution but I think it's something many people in the future will stumble upon.

**Comment by vesse** [comment]
I was already questioning my sanity for not being able to write a query with joins and select only certain fields but then noticed the same. The relations I'm trying to load have join columns that have the same names and the generated query resulted in a set that had three columns with the same name which got TypeORM confused and it didn't load the relations.

I'm using query builder with `innerJoinAndSelect` and `leftJoinAndSelect`, and if I do not specify the columns with `.select()` the relations are loaded correctly, but with `.select()` I end up with a query that selects one column from each table without giving the result column an alias name. These colums are all join columns for the selected relations, ie.

```
SELECT 
"master_collection"."id" AS "master_collection_id", 
"item"."id" AS "item_id", 
"extra"."id" AS "extra_id", 
"subitem"."id" AS "subitem_id", 
"subextra"."id" AS "subextra_id", 
master_collection.item_id, 
extra.item_id, 
subitem.parent_item_id, 
subextra.item_id 
```

If I do eg. `.select([ 'subextra.item_id AS subextra_item_id' ])` the relation is loaded properly.

**Comment by vesse** [comment]
Oh nevermind the previous commit - this was clearly a user error!

I need to use the model property names for the `AS` generation to work properly, ie.`.select([ 'subextra.itemId' ])` instead of `.select([ 'subextra.item_id' ])`.

**Comment by janaszer** [comment]
Are there any plans to fix that? This issue makes typeorm unusable for me :(

**Comment by jeffreyschultz** [comment]
I have encountered an issue that I think is related to the one in this ticket. The ManyToMany relation that I am using with postgres works correctly when nestjsx/crud constructs the queries. It's fine, and the relation is returned. The issue pops up when I send the same entity back to nestjsx/crud through a PATCH operation, which essentially just passed the entity through to the save() method on the repository. The repository is a normal TypeOrm generated repository.

Its bizarre that I can use the relation to the select the data, but then calling this.repo.save() on the entity causes it to blow up.

```
query failed: SELECT Package_owners_rid.owner_id AS "owner_id", Package_owners_rid.package_id AS "package_id" FROM "user" "user" INNER JOIN "package_owner_user_xref" "Package_owners_rid" ON (Package_owners_rid.package_id = $1 AND Package_owners_rid.owner_id = "user"."id") ORDER BY Package_owners_rid.owner_id ASC, Package_owners_rid.package_id ASC -- PARAMETERS: [65]
error: error: missing FROM-clause entry for table "package_owners_rid"
    at Parser.parseErrorMessage (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg-protocol/dist/parser.js:241:15)
    at Parser.handlePacket (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg-protocol/dist/parser.js:89:29)
    at Parser.parse (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg-protocol/dist/parser.js:41:38)
    at Socket.<anonymous> (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 130,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '178',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3305',
  routine: 'errorMissingRTE'
}
[Nest] 2446   - 05/15/2020, 10:06:22 PM   [ExceptionsHandler] missing FROM-clause entry for table "package_owners_rid" +21706ms
QueryFailedError: missing FROM-clause entry for table "package_owners_rid"
    at new QueryFailedError (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg/lib/query.js:146:19)
    at Connection.connectedErrorMessageHandler (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg/lib/client.js:233:17)
    at Connection.emit (events.js:310:20)
    at /home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg/lib/connection.js:109:10
    at Parser.parse (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg-protocol/dist/parser.js:42:17)
    at Socket.<anonymous> (/home/schultz.jeffrey/Source/psd/tcd-1.x.x/backend/tcd-api/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
```
