### ISSUE TITLE
String type primary key support error.

### ISSUE THREAD

**Issue by EdmundTheRadiance** [typeorm/typeorm#407]
In file QueryBuilder.ts line 971:
const ids = results.map(result => result["ids_" + metadata.firstPrimaryColumn.propertyName]);
const areAllNumbers = ids.map((id: any) => typeof id === "number");
if (areAllNumbers) {
    // fixes #190. if all numbers then its safe to perform query without parameter
    condition = `${mainAliasName}.${metadata.firstPrimaryColumn.propertyName} IN (${ids.join(", ")})`;
} else {
    parameters["ids"] = ids;
    condition = mainAliasName + "." + metadata.firstPrimaryColumn.propertyName + " IN (:ids)";
}

and my ids is 
![image](https://cloud.githubusercontent.com/assets/9878880/25131061/f930b4c0-2476-11e7-9840-c4aa282edc48.png)
then areAllNumbers is 
![image](https://cloud.githubusercontent.com/assets/9878880/25131114/29de684c-2477-11e7-9f0c-b9e30fe69db0.png)
code "if (areAllNumbers) " is true
then "condition = `${mainAliasName}.${metadata.firstPrimaryColumn.propertyName} IN (${ids.join(", ")})`;" will be excute and my condition is
![image](https://cloud.githubusercontent.com/assets/9878880/25131199/71d5d81a-2477-11e7-8efa-7b0e993f1b06.png)
finially it will throw exception
![image](https://cloud.githubusercontent.com/assets/9878880/25131245/91995ef6-2477-11e7-8dc5-87671e721b9c.png)

**Comment by EdmundTheRadiance** [comment]
Right condition should be 
t_app_click_job.wx_account_name IN ("654321", "acfunwx", "aibizhihd", "aikan4G", "aiPai_YuanChuang", "alibaba_1688", "Alitrip_com", "amazing58", "androidesk_bizhi", "anjukeshanghai")

**Comment by pleerock** [comment]
thank you for your report, Im aware of this issue, it will be fixed in next versions of typeorm

**Comment by pleerock** [comment]
Fix for this issue is available from `0.1.0-alpha.26`.
