### ISSUE TITLE
[MongoDB] Event listener in list of nested documents gives error

### ISSUE THREAD

**Issue by danielsetreus** [typeorm/typeorm#4071]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16`

**Steps to reproduce or a small repository showing the problem:**

```ts
export class Category {
    @Column()
    public slug: string;

    @Column()
    public name: string;
    
    @AfterLoad()
    someFunk() {
      console.log('Loaded')
    }
}

@Entity()
export class Article {
    @ObjectIdColumn()
    public id: ObjectID;

    @Column(type => Category)
    public categories: Category[];
}
```

Gives error 
```
entity[propertyPath][this.propertyName] is not a function
```

When the entities column is not an array it works, i.e
```ts
...
@Column(type => Category)
public category: Category;
...
```

I would expect the event listeners to be called once for every instance in the array.

**Comment by ziofat** [comment]
any updates on this?
