### ISSUE TITLE
Default value function not re-evaluated for inserts

### ISSUE THREAD

**Issue by saarw** [typeorm/typeorm#4081]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16` (the one pulled in by NestJS)

The default function that only gets evaluated once is this
```@PrimaryColumn('varchar', { length: 14, default: () => `'${shortid.generate()}'` })```

I'm implementing the PrimaryColumn directive to use shortid to generate default IDs from the answer to the SO-post below, but getting "QueryFailedError: duplicate key value violates unique constraint" for any inserts after the first, so the default-value function only seems to get called once
https://stackoverflow.com/questions/52157791/how-do-you-set-a-custom-default-unique-id-string-for-the-primarygeneratedcolumn

**Comment by Kononnable** [comment]
`default` is saved as default value in sql. You probably want to set this property in entity constructor.
