### ISSUE TITLE
How to correctly join Many-to-Many relation with custom fields

### ISSUE THREAD

**Issue by timoangerer** [typeorm/typeorm#4083]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following Entities:

```
@Entity('party')
export default class Party extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column({ type: 'varchar', length: 100, nullable: false })
  @Index()
  name: string

  @OneToMany(() => PartySong, partySong => partySong.party)
  partySongs: PartySong[]
}

@Entity('song')
export default class Song extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column({ type: 'varchar', length: 255, nullable: false, unique: true })
  @Index({ unique: true })
  spotifyId: string

  @OneToMany(() => PartySong, partySong => partySong.song)
  partySongs: PartySong[]
}

@Entity('party_song')
export default class PartySong extends BaseEntity {
  @PrimaryColumn()
  partyId: string

  @ManyToOne(() => Party, party => party.partySongs)
  @JoinTable({ name: 'partyId' })
  party: Party

  @PrimaryColumn()
  songId: string

  @ManyToOne(() => Song, song => song.partySongs)
  @JoinTable({ name: 'songId' })
  song: Song

  @Column()
  @Index()
  playable: boolean
}

```

I want to query a single party by ID and have all the songs of this party that are playable = true populated inside the party object.

How can I do this most effectively?

**Comment by kferrone** [comment]
Have you tried using the subscribers? Specifically the `afterLoad` method? The subscribers give you a ton of control by providing a way to do your won style of eager loading. 

```ts
@EventSubscriber()
export class PartySubscriber implements EntitySubscriberInterface<Party> {
    public listenTo() {
        return Party;
    }
    public afterLoad(entity: Party): Promise<any> {
        //code to get playable songs for the party
    }
}
```

https://typeorm.io/#/listeners-and-subscribers

https://github.com/typeorm/typeorm/blob/master/src/subscriber/EntitySubscriberInterface.ts

**Comment by Kononnable** [comment]
Closing as no response from the author.
