### ISSUE TITLE
Support for the experimental syntax 'decorators-legacy' isn't currently enabled

### ISSUE THREAD

**Issue by joris1995** [typeorm/typeorm#4089]
**Issue type:**
[x] question

**Database system/driver:**
[x] `react-native`

**TypeORM version:**
[x] `latest`

Today I stumbled into TypeORM for a React-Native project I'm working on. I was looking for a maintainable and scalable approach to manage my SQLite database, and this seems just perfect.

I followed the steps you provided. In my project's root directory
- Installed react-native-sqlite-storage. I know this is working, as the app worked with this plugin before I added TypeORM
- ran npm install typeorm --save
- ran npm install @types/node --save-dev
- added `skipLibCheck: true` to my TSConfig. However, in an effort to get the app running, I replaced all my tsconfig contents with the one from your example, but without results
- I set react-native as the connection type (This function is called in the constructor of my main API class): 

 `ConnectDatabase() {
        return createConnection({
            name: 'my-database',
            type: 'react-native',
            database: 'default',
            location: 'default',
            logging: ['error', 'query', 'schema'],
            synchronize: true,
            entities: [DBPlayer, DBParticipant]
        })
    }`

When I try to run this, the Metro Bundler gives me this:
![Schermafbeelding 2019-05-05 om 19 47 34](https://user-images.githubusercontent.com/44894683/57198042-b1b49b80-6f6e-11e9-8e45-dc2d519ae0a3.png)

For testing purposes, I only added 2 of my entities as @Entity instances and this error appears for both of them.

How can I solve this?

**Comment by Kononnable** [comment]
Some parts of react-native presets were changed recently. This should do the trick.
https://stackoverflow.com/questions/52262084/syntax-error-support-for-the-experimental-syntax-decorators-legacy-isnt-cur

**Comment by linfan68** [comment]
> Some parts of react-native presets were changed recently. This should do the trick.
> https://stackoverflow.com/questions/52262084/syntax-error-support-for-the-experimental-syntax-decorators-legacy-isnt-cur

THANK YOU!
This works for me, and here is my package.json and .babelrc:
```json
{
....
    "devDependencies": {
....
        "@babel/plugin-proposal-decorators": "7.4.4",
....
    }
}
```

```js
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    [ "@babel/plugin-proposal-decorators", {"legacy": true }]
  ]
}
```

**Comment by Kononnable** [comment]
Looks like issue was resolved.
