### ISSUE TITLE
Custom repository support in transaction

### ISSUE THREAD

**Issue by 19majkel94** [typeorm/typeorm#409]
Currently, the signature of the transaction wrapper is set to
```typescript
async transaction(runInTransaction: (repository: Repository<Entity>) => Promise<any>|any): Promise<any>
```
which means, that if you extend basic `Repository<Entity>` class, you can't use extended methods in transactions.

The problem is with [that line](https://github.com/typeorm/typeorm/blob/master/src/repository/Repository.ts#L424) - it could be replaced with `const transactionRepository = new this.constructor()`. I know, it's a bit hacky for TypeScript but `any` assertions should fix it - see [this demo](http://www.typescriptlang.org/play/#src=class%20Test%20%7B%0D%0A%20%20%20%20property%20%3D%20%22Test%22%0D%0A%20%20%20%20say()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%22Hello%22%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20clone()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20this.constructor()%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20SuperTest%20extends%20Test%20%7B%0D%0A%20%20%20%20greet()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%22Greet%22%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20test%20%3D%20new%20SuperTest()%0D%0Aconst%20copy%20%3D%20test.clone()%3B%0D%0Aalert(%60Greet%3A%20%24%7Bcopy.greet()%7D%60))

@pleerock
Can I make my first PR or you think that it's not a good idea with `new this.constructor()`?

**Comment by pleerock** [comment]
transaction method in repository is really useless... I was thinking if I should remove it - because first it confuses users and second most transactions are with multiple tables, not single tables, but with this method your transaction will work only for insertions into table of this repository entity.

**Comment by 19majkel94** [comment]
Yeah, it sucks, I even wrote about it on gitter a few minutes ago 😄 

Can we have a `getConnection().beginTransaction();` method? Then we could manually do
`getConnection().rollBack();` or `getConnection().commit();`. But I'm afraid that there would be a problem with nested transactions (they are now used by repository operations) 😞

**Comment by pleerock** [comment]
there are also parallel transactions, so no, we can't do that.

**Comment by pleerock** [comment]
In latest alpha versions I have removed transaction method from repository. Plus custom repositories are not singleton services anymore - now you can obtain them via entity manager right in the transaction
