### ISSUE TITLE
Repository save doesn't return autogenerated columns 

### ISSUE THREAD

**Issue by daniildxb** [typeorm/typeorm#4090]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Hi, I've noticed that Repository.save doesn't return several of auto-generated field

Model Route.ts
```ts
@Entity({ name: 'routes' })
export class Route {
  @PrimaryGeneratedColumn()
  public id!: number;

  @Column({ nullable: true })
  public name!: string;

  @Column({ nullable: true })
  public description!: string;

  @Column({ nullable: true })
  public distance!: number;

  @Column({
    default: 'inactive',
    enum: ['active', 'not active', 'testing', 'checking'],
  })
  public status!: string;

  @Column({ nullable: true })
  public zoom!: number;

  @Column({ nullable: true, type: 'decimal' })
  public latitude!: number;

  @Column({ nullable: true, type: 'decimal' })
  public longitude!: number;

  @CreateDateColumn({ name: 'created_at' })
  public createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  public updatedAt!: Date;

  @OneToMany(type => RouteLeg, routeLeg => routeLeg.route, { cascade: true })
  public legs!: RouteLeg[];

  @ManyToOne(type => Route, route => route.id)
  @JoinColumn({ name: 'source_id' })
  public source!: Route;
}
```
Method call
```getRepository(Route).save(_);```

For some reason `id` and `createdAt` are not returned while `updatedAt` is value is returned

**Comment by kferrone** [comment]
You need some more examples here for anyone to help ya out. This is not an issue for me and therefore i can't recreate.

**Comment by Kononnable** [comment]
I'm also not reproducing the issue. Please make a simple reproduction repo or add a PR with failing test.

**Comment by fullstackwebdev** [comment]
I can confirm this is an issue or that I have reproduced an issue like this.  I am still investigating it.

But what I have so far, is my Repository.save() is not returning ID (!!!)
* In my case, if I remove the ManyToOne, it does return the ID
* If I add the ManyToOne back, it fails to return the ID and other columns.

**Comment by DimaIT** [comment]
Have same issue.
It seems to me that save fails to return autogenerated columns when cascade insert used and both `OneToMany` and `ManyToOne` relations involved.

I think #3246 is also related. Query examples and reproduction present there.

Example to reproduce bellow:

**Code:**
```ts
@Entity('a')
export class EntityA {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @CreateDateColumn({ name: 'created_ts', type: 'timestamptz' })
  createdTS: string;

  @UpdateDateColumn({ name: 'updated_ts', type: 'timestamptz' })
  updatedTS: string;

  @ManyToOne(() => EntityC, { cascade: true })
  @JoinColumn({ name: 'c_id' })
  entityC: EntityC;

  @OneToMany(() => EntityB, b => b.entityA, { cascade: true, eager: true })
  bList: EntityB[];
}

@Entity('b')
export class EntityB {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('text')
  name: string;

  @ManyToOne(() => EntityA, { onDelete: 'CASCADE', nullable: false, })
  @JoinColumn({ name: 'a_id' })
  entityA: EntityA;
}

@Entity('c')
export class EntityC {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('text')
  name: string;
}
```

```ts
const repo = await connection.getRepository(EntityA);

const result = await repo.save({
  entityC: { name: 'test' },
  bList: [
    { name: 'test1' }
  ]
});
console.log(result);
console.log(result.id);
```

**Output:**
```
{
  entityC: {
    name: 'test',
    id: 'd8647518-dae5-40f3-b455-3d10088c9c86'
  },
  bList:
    [{
      name: 'test1',
      id: 'e6465452-d0a9-4666-b4ee-682d23313662'
    }],
  updatedTS: '2019-06-26T19:39:56.153Z '
};
undefined
```

**Queries**
```
query: START TRANSACTION
query: INSERT INTO "test"."a"("id", "created_ts", "updated_ts", "c_id") VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT) RETURNING "id", "created_ts", "updated_ts"
query: INSERT INTO "test"."b"("id", "name", "a_id") VALUES (DEFAULT, $1, $2) RETURNING "id" -- PARAMETERS: ["test1","c8f8725f-6e1c-4188-bed7-5f81512b6cc7"]
query: INSERT INTO "test"."c"("id", "name") VALUES (DEFAULT, $1) RETURNING "id" -- PARAMETERS: ["test"]
query: UPDATE "test"."a" SET "c_id" = $2, "updated_ts" = CURRENT_TIMESTAMP WHERE "id" IN ($1) RETURNING "updated_ts" -- PARAMETERS: ["c8f8725f-6e1c-4188-bed7-5f81512b6cc7","6d9332a9-c51f-4670-8b9c-f69175cf9cb4"]
query: COMMIT
```

**Comment by RDeluxe** [comment]
We encountered this case multiple times. The previous solution fixed it.

**Comment by brinzi** [comment]
I have the same issue when using mysql backend.

**Comment by andrewfhart** [comment]
@DimaIT  @Kononnable 

The common thread seems to be entities with both a `@PrimaryGeneratedColumn` **AND** an `@UpdateDateColumn`. 

In these cases, when `save()` is executed, it is implemented as two queries in a transaction:

```
START TRANSACTION

INSERT INTO "foo"("id", "createdAt", "updatedAt") VALUES (DEFAULT, DEFAULT, DEFAULT) 
  RETURNING "id", "createdAt", "updatedAt" 

UPDATE "foo" SET "updatedAt" = CURRENT_TIMESTAMP WHERE "id" IN ($1)
  RETURNING "updatedAt" 
-- PARAMETERS: ["<autogenerated_id_from_first_query>"]

COMMIT
```

* The first query returns the generated ids as expected.
* The second query only returns columns where `.isUpdateDate` or `.isVersion` is true ([ref](https://github.com/typeorm/typeorm/blob/master/src/query-builder/ReturningResultsEntityUpdator.ts#L174))

The result is that only the `@isUpdateDate` column is returned in the response. The rest get "lost" in the middle of the transaction.

A trivial fix involves modifying [ReturningResultsEntityUpdator.ts](https://github.com/typeorm/typeorm/blob/4c2bffc7bade17c9e27c3876669d112593b314f1/src/query-builder/ReturningResultsEntityUpdator.ts#L169-L176) from:
```
    /**
     * Columns we need to be returned from the database when we update entity.
     */
    getUpdationReturningColumns(): ColumnMetadata[] {
        return this.expressionMap.mainAlias!.metadata.columns.filter(column => {
            return column.isUpdateDate || column.isVersion;
        });
    }
```
to:
```
    /**
     * Columns we need to be returned from the database when we update entity.
     */
    getUpdationReturningColumns(): ColumnMetadata[] {
        return this.expressionMap.mainAlias!.metadata.columns.filter(column => {
            return column.isUpdateDate || column.isVersion || column.isGenerated
        });
    }
```

However, I do not know if that is problematic or undesirable for other reasons.

**Comment by AllSeeingEye** [comment]
This issue is reproducible with the latest TypeORM / Postgres.

**Comment by shuramita** [comment]
have the same issue here, with many to many relations

**Comment by abinhho** [comment]
Same here.
`postgres:11.6`
`"@nestjs/typeorm": "^6.2.0",`

```
@UpdateDateColumn()
  updatedAt: string; // ==> Not return after insert or update, alway undefined but stored in DB already.
```

**Comment by lealcalhau** [comment]
Same problem here.
"mysql": "^2.17.1"
"typeorm":"^0.2.21"
"@nestjs/typeorm":"^6.2.0"


export class ValorProduto {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({nullable: false})
    valor: number;

    @ManyToOne(() => Produto, (p) => p.nome, { nullable: false})
    produto: Produto;

    @ManyToOne(() => UnidadeMedida, (um) => um.nome, { nullable: false})
    unidadeMedida: UnidadeMedida;
   
}


Return after repository.save

{ valor: '14', produto: '1', unidadeMedida: '2' }

no ID

**Comment by TayyabKML** [comment]
I'm running into the same issue as well. I have an entity with one OneToMany relation and another ManyToOne relation. Both these related entities further have relations in their respective entities.

Removing ManyToOne relation from the entity fixes the problem for me but its not an ideal solution.

**Comment by jtethras** [comment]
Same issue, with ManyToOne relation, though _reproduces only sometimes_, approximately 1/20

**Comment by NaturesProphet** [comment]
same problem here

**Comment by adamclark64** [comment]
> Same issue, with ManyToOne relation, though _reproduces only sometimes_, approximately 1/20

same with `OneToOne`

if I try to create a record w/o relations, i get id back. if I save any relations, i dont get id or created, just updated

**Comment by bquartz** [comment]
I had the same issue, the solution from @andrewfhart solved it.

**Comment by endurance** [comment]
Bump. Could we get a beta release out with @andrewfhart's fix folded in?

**Comment by jvaca92** [comment]
I have the same problem wit mssql. Try to avoid multiple inserts. Would be great do that at once and get the auto gen id.

**Comment by guyisra** [comment]
any updates on this?

**Comment by TranBaVinhSon** [comment]
> I have the same problem wit mssql. Try to avoid multiple inserts. Would be great do that at once and get the auto gen id.

Yeah, exactly, I had the same problem with bulk insertion

**Comment by brinzi** [comment]
Any updates?

**Comment by vincilbishop** [comment]
Same here problem here...this almost seems new

I was able to workaround by using insert instead of save. Kind of a hassle, but in my instance it was kind of sort of not hacky.

**Comment by carlos-technogi** [comment]
Using insert instead of save worked for me:
```typescript

 async createWorkerPayments(remittance: Remittance): Promise<WorkerPayment[]> {
    const payments = await Promise.all(remittance.lines.map(this.createWorkerPayment()))
    await this.paymentsRepository.insert(payments)
    return payments
  }
```

instead of

```typescript
async createWorkerPayments(remittance: Remittance): Promise<WorkerPayment[]> {
    const payments = await Promise.all(remittance.lines.map(this.createWorkerPayment()))
    return this.paymentsRepository.save(payments)
  }
```

**Comment by fstn** [comment]
Same here problem here...this almost seems new

I was able to workaround by using insert instead of save.

**Comment by brianqian** [comment]
Was running into this issue but `userRepo.create(userObj).save()` works for me.

**Comment by fstn** [comment]
The last commit fix the issue for meThe last commit fix the issue for me

**Comment by Feida-Meng** [comment]
The issue is still there for version 0.2.29

**Comment by stingalleman** [comment]
I'm also still having this issue.

**Comment by rfajarachmad** [comment]
Still found the same issue version 0.2.30

`@PrimaryGeneratedColumn('uuid')
    id: string;
`

```
this.userRepository.save(user);
user.id <-- undefined
```

but if 
`
return this.userRepository.save(user);
`
the id was populated

**Comment by stingalleman** [comment]
If anybody is still having issues with this (or any other typeorm issue that has been open for years, or just typeorm in general), use [Prisma](https://www.prisma.io). I used to love typeorm but I just had so many issues with it. Prisma is basically typeorm on steroids.

**Comment by andrewfhart** [comment]
While that advice certainly makes sense for anyone starting a new project in 2021, for folks tasked with maintaining a significant existing code base, "just" using another ORM may be quite a shift. Fortunately this thread has several workarounds to the issue, which I'll summarize here because the thread is growing lengthy:

1. https://github.com/typeorm/typeorm/issues/4090#issuecomment-526854041 (simple 1-line implementation example: https://github.com/bkstorm/typeorm/commit/fb6fa62bd57dd6fdb5dbbafd2350bf9ac421e4be)
2. https://github.com/typeorm/typeorm/pull/6969 (slightly more involved, but possibly more complete)
3. https://github.com/typeorm/typeorm/issues/4090#issuecomment-662220009 (using insert rather than save)

Good luck!

**Comment by iceboss3d** [comment]
Adding `{cascade: true, eager: true}` to the each OneToOne and ManyToOne relations in the Entity solved it for me.

`@ManyToOne(type => UserEntity, user => user.applications, {cascade: true, eager: true})
    @JoinColumn()
    user: UserEntity;`

**Comment by ivenuss** [comment]
In my case I forgot to add `default` values of columns,.

**Comment by sallamTanna** [comment]
In my case, I needed to remove "void" as the return value returned from the function that I used to save new data.

**Comment by baldhruv** [comment]
I am seeing this issue for our service. Can someone point out if I'm doing something incorrectly?

- DB: Postgres
- TypeOrm Version: "^0.3.4"

**Entity**
```
export abstract class X {
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column({ unique: true })
  @Generated("increment")
  formNumber: number;

  ...
```

**DataSource**
```
  public async saveX(
    form: X
  ): Promise<X | null> {
    if (!form.id) {
      return await this.repository.save(form);
    }
    return null;
  }
```

**GraphQL Query**
```
{
  "input": {
    "a": true,
    "b": "lol",
    "c": "6da6c63b-f5a5-46bd-abe5-a11c552a326e",
    "d": "2020/04/20",
    "r": "123",
    "f": 3,
    "g": 44,
    "h": null,
    "cascadeThisObject": [
      {
        "j": "Doo Doo",
        "k": 4,
        "l": "ABCD123",
        "m": "ABCD123",
        "n": "RETAIL",
        "o": 4,
        "p": "12345",
        "q": "DAL",
        "r": "DED"
      }
    ]
  }
}
```

The generated INSERT query (columns don't match the names in the GraphQL Query, but you get the idea.
```
query: INSERT INTO "public"."purchase_order_request_form"("id", "createdOn", "updatedOn", "deletedOn", "version", "a", "b", "c", "d", "e", "f", "g", "h", "i") VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, 1, :param_1, :param_2, :param_3, :param_4, :param_5, DEFAULT, DEFAULT, DEFAULT, :param_6) -- PARAMETERS: [{"name":"param_1","value":"lol"},{"name":"param_2","value":true},{"name":"param_3","value":"6da6c63b-f5a5-46bd-abe5-a11c552a326e"},{"name":"param_4","value":"2020-04-20 07:00:00","cast":"TIMESTAMP"},{"name":"param_5","value":"123"},{"name":"param_6","value":3}]
```

**Return value from `save()`:**

```
X {
  a: true,
  r: '123',
  f: 3,
  g: 44,
  b: 'lol',
  d: 2020-04-20T07:00:00.000Z,
  c: '6da6c63b-f5a5-46bd-abe5-a11c552a326e',
  z: null,
  y: null,
  x: null,
  w: null
}
```

Basically there is no `ID` column, nor `formNumber` column, both of which are generated. This causes the cascade (for the object provided in the `cascadeThisObject` field in the GraphQL query) to fail also because it seems like the `formNumber` column (which is needed for the cascade) doesn't seem to be passed in.

**Comment by maks-rafalko** [comment]
Still have the same issue for ActiveRecord usage with `0.3.17` version.

```ts
@Entity({ name: "logistics" })
export class Logistic extends BaseEntity {
  @PrimaryGeneratedColumn()
  index?: number;

  @Column({
    generatedType: "STORED",
    asExpression: `('slot_'::text || index::character varying::text)`,
    comment: `same as index, but prefixed with slot_`,
    nullable: true,
    unique: true,
  })
  id: string;
}
```

the following code works incorrectly:

```ts
const logistic = new Logistic();
await logistic.save();

console.log(logistic.id); // null

// but if reload it from db

logistic = Logistic.findOneByOrFail({ index: logistic.index });

// then ID is present

console.log(logistig.id); // slot_1
```

**Comment by dberardo-com** [comment]
i believe that now primaryColumn are not returned by the save function ... is this true ?
