### ISSUE TITLE
Delete on JSON column: QueryFailedError: operator does not exist: json = unknown

### ISSUE THREAD

**Issue by christopherdiehl** [typeorm/typeorm#4094]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.16` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
@Entity()
export class Organization extends BaseEntity {
  // allows us to pass in an object in the constructor
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: "text" })
  name: string;

  @Column({ type: "boolean", default: true })
  active: boolean;
  
  @Column({ type: "json", default: {} })
  metadata?: any;

  @UpdateDateColumn()
  updatedDate: Date;

  @CreateDateColumn()
  createdDate: Date;

}

const organization : Organization= {
   name : "TEST",
}
await organization.save();
await Organization.delete(organization);

```

Result: 
The generated sql uses a where clause on a JSON column.
```
    QueryFailedError: operator does not exist: json = unknown

      at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
      at Query.callback (src/driver/postgres/PostgresQueryRunner.ts:176:30)
      at Query.Object.<anonymous>.Query.handleError (node_modules/pg/lib/query.js:142:17)
      at Connection.connectedErrorMessageHandler (node_modules/pg/lib/client.js:183:17)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:125:12)
```

Generated SQL: 
```
    query: DELETE FROM "organization" WHERE "name" = $1 AND "id" = $2 AND "active" = $3 AND "metadata" = $4 AND "updatedDate" = $5 AND "createdDate" = $6 -- PARAMETERS: ["tempget",14,true,{},"2019-05-07T00:11:11.053Z","2019-05-07T00:11:11.053Z"]
```

Fix: 
`await Organization.delete({id: organization.id})`

**Comment by Kononnable** [comment]
You're looking for `remove()`.
If you want to remove an entity you should use `remove` - it will create where condition based on PK. If you use `delete()` it generate where condition with every field in passed object.

However delete should not throw an error, so it looks like there is a bug after all.

**Comment by imnotjames** [comment]
This should throw an error if you've asked it to create a query the underlying database can't understand, though, right?  Especially when you've passed an incomplete model over.

I'm going to close this out, as I believe it's operating as expected.
