### ISSUE TITLE
Unable to set embedded entities column values 

### ISSUE THREAD

**Issue by Tochemey** [typeorm/typeorm#4095]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";
@Entity()
import {Entity, Column} from "typeorm";

export class Name {

    @Column()
    first: string;

    @Column()
    last: string;

}
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";
import {Name} from "./Name";
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: string;

    @Column(type => Name)
    name: Name;

    @Column()
    isActive: boolean;

}
`
When I am creating an instance of `User` and I want to set `nameFirst` by doing this 
`
const user: User = new User();
user.name.first = 'John';
`
I got undefined property `first`.

**Comment by jeanfortheweb** [comment]
```
user.name = new Name();
user.name.first = 'John';

// or

const user = userRepository.create({ 
    name: {
        first: 'John',
    }
});
```

Just guessing. I don't see a reason why `new User()` should initialize the name property. This has nothing to do with typeorm, it's language specific.

**Comment by Tochemey** [comment]
@jeanfortheweb Thank you for your answer. I just figured it out that it is not typeorm issue but Javascript related issue. I was able to fix it.
