### ISSUE TITLE
Cannot drop view because other objects depend on it

### ISSUE THREAD

**Issue by Skullflow** [typeorm/typeorm#4098]
**Issue type:**

[ x ] question
[ ] bug report
[ x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] 0.2.17

Hi guys,

thanks for update typeorm with View entity, such a great improvement.

I have a question, maybe a request depending on the problem.

I'm working with `ViewEntity` and i want to create a View that depends on a View; but when I'm working with synchronization, i got this error message: "cannot drop view because other objects depend on it".

The message is quite clear: i need to perform a DROP CASCADE of the views every time I restart my app.

How can i achieve this?
Can I run initialization sql command somewhere before initialize my DB? (Then I am able to specify that i want to DROP CASCADE all the views that i need to delete)

Thanks!

**Comment by Skullflow** [comment]
This is a trivial example but it helps to understand the problem:

```typescript
@ViewEntity({
    expression: (connection) => connection
        .createQueryBuilder()
        .select("user.id", "id")
        .addSelect("user.name", "name")
        .from(User, "user")
})
export class UserView {
    @ViewColumn()
    id: number;
    @ViewColumn()
    name: string;
}

@ViewEntity({
    expression: (connection) => connection
        .createQueryBuilder()
        .select("user.id", "id")
        .from(UserView, "user")
})
export class AnotherUserVIew {
    @ViewColumn()
    id: number
}
```

**Comment by Kononnable** [comment]
You can disable synchronization in connection options. Then right after connection is initialized make your raw query deleting the views and call `await connection.synchronize()` to synchronize db schema.

**Comment by imnotjames** [comment]
Hope this was an answer to your question.  Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by stewartmcgown** [comment]
Reviving this because I'm experiencing this when I have views that depend on other views. Is this bad practice hence why TypeORM is calling me out for it?

```
 query failed: DROP VIEW "rider_booking_score"
 error: error: cannot drop view rider_booking_score because other objects depend on it
     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)
     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:8:42)
     at Socket.emit (events.js:315:20)
     at Socket.EventEmitter.emit (domain.js:467:12)
     at addChunk (internal/streams/readable.js:309:12)
     at readableAddChunk (internal/streams/readable.js:284:9)
     at Socket.Readable.push (internal/streams/readable.js:223:10)
     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
   length: 262,
   severity: 'ERROR',
   code: '2BP01',
   detail: 'view booking_metric_rank depends on view rider_booking_score',
   hint: 'Use DROP ... CASCADE to drop the dependent objects too.',
   position: undefined,
   internalPosition: undefined,
   internalQuery: undefined,
   where: undefined,
   schema: undefined,
   table: undefined,
   column: undefined,
   dataType: undefined,
   constraint: undefined,
   file: 'dependency.c',
   line: '1196',
   routine: 'reportDependentObjects'
 }
```

**Comment by superopengl** [comment]
I experienced this issue these days and finally managed to solve it like this:

1. In the `.env` file, set `TYPEORM_MIGRATIONS_RUN=false` and `TYPEORM_SYNCHRONIZE=false` to disable automatic sync and migration
2. In my code right after creating the typeorm connection, do below (expressed in pseudo code )
  ```ts
  async function connectDatabase() {
    const connection = await createConnection();
    // 1. drop all views/mviews, as typeorm cannot drop them in correct order nor does cascade drop.
    await dropAllTypeOrmViews(connection);
    await dropAllTypeOrmMaterializedViews(connection);

    // 2. Manually synchroize database schema changes (reflect typeorm table/view entities changes)
    await connection.synchronize(false);

    // 3. Manually run all migration scripts
    await connection.runMigrations();
    return connection;
  }
  ```
