### ISSUE TITLE
Can JoinColumn be used to specify custom column name in one-to-many relations?

### ISSUE THREAD

**Issue by lackovic** [typeorm/typeorm#4102]
**Issue type:**

[x] question
[x] documentation issue

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `0.2.11`

**Question:**

Can `JoinColumn` be used to specify custom column name in one-to-many relations?

I was not able to find an answer to this question in none of the following sources:

- [JoinColumn.ts](https://github.com/typeorm/typeorm/blob/master/src/decorator/relations/JoinColumn.ts)
- [@JoinColumn](https://github.com/typeorm/typeorm/blob/master/docs/decorator-reference.md#joincolumn)
- [@JoinColumn options](https://github.com/typeorm/typeorm/blob/master/docs/relations.md#joincolumn-options)

My guess is: it's not needed and should not be used.

**Comment by kferrone** [comment]
Indeed you can like this: 

```ts
@JoinColumn({
        name: 'custom_column_name'
})
```

**Comment by lackovic** [comment]
@kferrone thanks. 

I noticed adding it does not produce any error, and I also noticed that leaving it out does not hinder any functionality.

So my question is what would be the need of adding it? What benefit does it add?

And if indeed it is useful, shouldn't it be mentioned in the documentation?
