### ISSUE TITLE
One to many throws error with tsconfig target of es6

### ISSUE THREAD

**Issue by atul221282** [typeorm/typeorm#4103]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.15` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Create two entities with one to many relation and in tsconfig.json file change the target to es6. it will give error of circular dependency, please note I am using the webpack for bundling
Error can be easily reproduced here on this url [https://gitlab.com/atul221282/special-repo](https://gitlab.com/atul221282/special-repo). Just clone the repo and run ng s --project=api.

**Comment by aprat84** [comment]
Had the same problem. Solution was to change either `"target": "es5"` or `"module": "commonjs"` in tsconfig.json. It has to do with how modules work in ES6+, but I don't have time or knowledge enough to dig into it...

**Comment by Kononnable** [comment]
Typeorm isn't `module:esnext` compatible yet. There are plans to do it, but it will be the future(0.4.0).
Closing issue to keep list cleaner to not duplicate issues which are already reported elsewhere.
