### ISSUE TITLE
Specify enum type name in postgres

### ISSUE THREAD

**Issue by lgyanf** [typeorm/typeorm#4106]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm thinking to migrate my application from Sequelize to TypeORM, as a first step I've tried to reimplement current Sequelize models to TypeORM. 
I've encountered an issue that Sequelize and TypeORM generate postgres' enum type names differrently: Sequelize uses pattern `'enum_${tableName}_${columnName}'` whereas TypeORM uses `'${tableName}_${columnName}_enum'.toLowerCase()`. Is there a way I can specify custom type name in TypeORM's model definition?
If not, would it be useful to be able to specify type name in column definition? Something like 
```
@Column({
    type: 'enum',
    typeName: 'my_enum',
    enum: MyEnum,
})
enum_column: MyEnum
```

This would also allow to reuse same postgres enum type across multiple columns.

**Comment by GitStorageOne** [comment]
```typescript
  @Column('enum', { name: 'my_enum', enum: MyEnum})
  myEnum: MyEnum;
```

**Comment by CarstenWalther** [comment]
`@Column('enum', { name: 'my_enum', enum: MyEnum})`
This only changes the `columnName` part of the enum type but you don't have control over the full name.

Another use case of this feature is for using the same enum type in multiple tables. Currently typeORM creates a new enum type for each table where the enum appears. It would be nice when two enums share the same enum type if  their `typeName` are identical.

**Comment by Kononnable** [comment]
>  It would be nice when two enums share the same enum type if their typeName are identical.

This would be error prone - after some time you would add one more value to only one enum column - we would have to walk through every entity column and check if it isn't already using enum which we want to modify. Also how would we name such enum type?

**Comment by abobwhite** [comment]
We are currently seeing this because we are not allowing `synchronize` outside of local development. When running migrations we need to be able to create the enum type that will match the typeorm expectations when the code is executed. Right now we need to ensure our migrations create the exact same enum type that typeorm would have created for us. Pretty error prone. Tables and Columns do this - why not Types? @Kononnable

**Comment by ejose19** [comment]
Any updates on this? Many users use different naming conventions and this breaks out as it's the only thing that typeorm doesn't give full control to the user.
