### ISSUE TITLE
Can not manage to use order option field in find method for repository

### ISSUE THREAD

**Issue by Asone** [typeorm/typeorm#4107]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

I can't manage to use the `order` option when trying to call the `find` method for a repository. 
Digging around i found [this issue](https://github.com/typeorm/typeorm/issues/1240) that seems to had the same problem. Unfortunately the OP did not 
provide its code nor an explicit explanation of how (s)he solved its problem. 

As you'll see in the code below, in the service, when i just use `skip` and `take`, my code compiles without any problem. 
It also compiles if i add an empty order : `order:{}`. However i get the following message when adding an `order` field based on any property 
declared in the `Amendement` entity : 

> Argument of type '{ order: { block: number; }; skip: number; take: number; }' is not assignable to parameter of type 'FindConditions<Amendement>'. Object literal may only specify known properties, and 'order' does not exist in type 'FindConditions<Amendement>'

I might probably do things the bad way, however i can't figure out why and how. Any help & explanation would be welcome. 

Many thanks ! 

---

### The code :

**Entity** 

```
@Entity({
    name: "amendement",
    orderBy: {
        registered_at: "DESC"
    }
})
export class Amendement {

    @PrimaryColumn('uuid')
    public uuid: string;

    // @IsNotEmpty()
    @Column()
    public tx: string;

    // @IsNotEmpty()
    @Column()
    public address: string;

    @Column()
    public deposit_date: Date;

    @Column()
    public registered_at: Date;

    @Column()
    public deployed_at: Date;

    @Column()
    public contract_state: string;

    @Column()
    public amendement_state: string;

    @Column()
    public block: number;

    @Column()
    public blockhash: string;

    @Column()
    public receipt: string;

    public toString(): string {
        return `${this.uuid}`;
    }
```

**Repository**

```
@EntityRepository(Amendement)
export class AmendementRepository extends Repository<Amendement> {}
```

**Service**
```
@Service()
export class AmendementService {

    constructor(
        @OrmRepository(Amendement) private amendementRepository: AmendementRepository,
        // @EventDispatcher() private eventDispatcher: EventDispatcherInterface,
        @Logger(__filename) private log: LoggerInterface
    ) { }

    public find(pagination?: {start?: number, limit?: number}): Promise<Amendement[]> {
        return this.amendementRepository.find({
            order: {
                block: 'DESC'
            },
            skip: (pagination && pagination.start ? pagination.start : 0),
            take: (pagination && pagination.limit ? pagination.limit : 50),
        });
    }
}
```

**Comment by MinionsDave** [comment]
I had the same issue, version 0.2.17

**Comment by Kononnable** [comment]
You're sure this exact error was thrown from this lines of code? Errors says `order: { block: number; }` while you pass a `'DESC'` there. It would be nice if you could check if it's only problem with typings or is it not working at all. Just add `as any` so compiler doesn't complain.

**Comment by Asone** [comment]
hi @Kononnable : 

The element you quote is probably due to the fact that i tried many options possible in order to see if i can make it work. I'll give another proper test that i'll annotate here to ensure the failure i notified is consistent. 

I'll also give a try with the `as any` as requested today or tomorrow

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
