### ISSUE TITLE
node-sqlcipher with TypeORM

### ISSUE THREAD

**Issue by MuizMahdi** [typeorm/typeorm#4108]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`

**Steps to reproduce or a small repository showing the problem:**

I'm using [node-sqlcipher](https://github.com/journeyapps/node-sqlcipher), which is a modified fork of node-sqlite3 that uses SQLCipher. It works fine without TypeORM, but I couldn't make it work with TypeORM. I have added the 'key' option to the ConnectionOptions: `key: 'sqlcipher-key'`

I get the following exception when I add the key option:

`ERROR Error: Uncaught (in promise): Error: SQLITE_ERROR: near "-": syntax error Error: SQLITE_ERROR: near "-": syntax error at resolvePromise (zone.js:814) at zone.js:724 at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388) at Object.onInvoke (core.js:14060) at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387) at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138) at zone.js:872 at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421) at Object.onInvokeTask (core.js:14051)`

Adding the key in the 'extra' option `extra: { key: 'sqlcipher-key' }` doesn't throw an exception, but the database doesn't get encrypted.

**Comment by jprules321** [comment]
Mind if I ask how you implemented the library to get used instead of regular SQLite3 ? I installed journeyapps/sqlcipher instead of sqlite3 and it was always popping the no driver error, only way I found was the mock the require in my code and in the cli doing that

```js
const m = require('mock-require');
require('ts-node/register');
m('sqlite3', '@journeyapps/sqlcipher');
require('typeorm/cli.js');
```
then ```ts-node ormcli.j migration:generate```
