### ISSUE TITLE
MissingPrimaryColumnError using inheritance and EntitySchema

### ISSUE THREAD

**Issue by anthonyjlmorel** [typeorm/typeorm#4115]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[X] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am using TypeORM without concrete classes but only interfaces. Hence, I use EntitySchema to describe my data model.
I try to inherit from a schema but I run into the MissingPrimaryColumnError (on the HierarchyMeasuredPoint schema).

Here are my interfaces followed by their associated schemas:

```
 interface IHierarchyNode {
    id?: string;
    name?: string;

    children?: IHierarchyNode[];
    parent?: IHierarchyNode;
}

interface IHierarchyMeasuredPoint extends IHierarchyNode{
    data?: string;
}

interface IHierarchyNotMeasuredPoint extends IHierarchyNode{
    
}
```

``` 
import {EntitySchema} from "typeorm";

export const HierarchyEntity: EntitySchema = new EntitySchema<IHierarchyNode>({
    "name": "HierarchyNode",
    "columns": {
        "id": {
            "primary": true,
            "type": "varchar",
            "generated": "uuid"
        },
        "name": {
            "type": "varchar"
        }
    },
    "relations": {
        parent: {
            type: "many-to-one",
            target: "HierarchyNode",
            inverseSide: "children"
        },
        children:{
            type: "one-to-many",
            target: "HierarchyNode",
            inverseSide: "parent"
        }
    }
});

export const HierarchyMeasuredPointEntity: EntitySchema = new EntitySchema<IHierarchyMeasuredPoint>({
    name: "HierarchyMeasuredPoint",
    extends: "HierarchyNode",
    
    columns:{
        "data": {
            "type": "varchar"
        }
    },
    relations:{
       
    }
});

export const HierarchyNotMeasuredPointEntity: EntitySchema = new EntitySchema<IHierarchyNotMeasuredPoint>({
    name: "HierarchyNotMeasuredPoint",
    extends: "HierarchyNode",
    columns:{

    },
    relations:{
        
    }
});
```

Could you have a look ?

**Comment by anthonyjlmorel** [comment]
Ok, I got it, according to the docs, schema does not support inheritance out-of-the-box. It seems I have been flawed by the keyword  "extend" in the Typescript definition files, or is it an update ?

**Comment by imnotjames** [comment]
Ok - sounds like you've gotten to the bottom of that.  Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
