### ISSUE TITLE
Separate core from drivers and other extraneous stuff

### ISSUE THREAD

**Issue by jacobg** [typeorm/typeorm#4116]
**Issue type:**

[ ] question
[ ] bug report
[X ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Currently, all of typeorm is in one npm package, and the documentation says to import the index file, which imports everything. This results in a large bundle, with much of it probably unused.

It would be great to split out the drivers and any other extraneous stuff, such as cli stuff. I'd like to just import the core, and then the one driver I need. As the screenshots below show, the bundle size would be much smaller.

![Screen Shot 2019-05-09 at 12 26 09 PM](https://user-images.githubusercontent.com/736985/57470055-f9c90c00-7255-11e9-81ce-54bc29599ce3.png)

<img width="724" alt="screen_shot_2019-05-09_at_16 06 02" src="https://user-images.githubusercontent.com/736985/57470048-f5045800-7255-11e9-9b45-86319740625d.png">

**Comment by Kononnable** [comment]
We plan to split typeorm to smaller packages. However since it's not a trivial task we don't really have a clear timeline when it will be implemented.

Closing in favor of #2479 - to keep discussion in one thread.
