### ISSUE TITLE
Subscriber methods are not calling on adding/removing related entities

### ISSUE THREAD

**Issue by icewind** [typeorm/typeorm#412]
Hi. I'm using a simple subscriber which is listening for all entities. Something like this
```Typescript
EventSubscriber()
export class GeneralSubscriber implements EntitySubscriberInterface<any> {

  public async afterInsert(event: InsertEvent<any>) {
    return this.insertOrUpdate(event.entity);
  }

  public async afterUpdate(event: UpdateEvent<any>) {
    return this.insertOrUpdate(event.entity);
  }
}
```
And it works just fine if I'm updating some of the properties of an entity. But if I'm adding or removing related entities non of the subscriber methods gets called at all.
As example:
```Typescript
const student = await repository.findOneById(...);
student.name = 'Bob';
repository.persist(student); // Works fine

student.books.push(await booksRepo.findOne...)
repository.persist(student); // Saving all objects and relations but no subscriber events
```

**UPDATE**: Also `UpdateDateColumn` is not changing as well

**Comment by pleerock** [comment]
Its a way how subscribers and listeners designed and work. They are called only when entity columns are changed. When you add some entity into a many-to-many relation its not a change of this entity, you just bind one entity into another in a separate junction table.

Same with UpdateDateColumn. It works when real database table is updated, but in the case of many-to-many relation your target entity's table is not updated.
