### ISSUE TITLE
addSelect field has tow `select`

### ISSUE THREAD

**Issue by zeromake** [typeorm/typeorm#4128]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**
[x] `0.2.17`
## demo
[demo](https://github.com/zeromake/typeorm-demo.git)

db/entity/user.ts
``` ts
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity({
    name: "users",
})
export default class User {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    public username: string;

    @Column({
        select: false,
    })
    public password: string;
}
```
ormconfig.ts
``` ts
export default {
    type: "sqlite",
    database: "sqlite.db",
    synchronize: true,
    logging: true,
    entities: ["db/entity/**/*.ts"],
    migrations: ["db/migrations/**/*.ts"],
    cli: {
        entitiesDir: "db/entity",
        migrationsDir: "db/migrations",
    },
}
```
test.ts
``` ts
import { createConnection } from "typeorm";
import User from "./db/entity/user";
import config from "./ormconfig";

async function main() {
    const conn = await createConnection(config as any);
    const UserRepository = conn.getRepository(User);
    const user = await UserRepository.createQueryBuilder()
            .addSelect('User.password')
            .getOne();
    console.log(user);
}
main();
```

run
``` bash
yarn
yarn ts-node ./test.ts
```

sql output
``` bash
SELECT "User"."id" AS "User_id", "User"."username" AS "User_username", "User"."password" AS "User_password", "User"."password" FROM "users" "User"
```
## question
1. `FROM "users" "User"` alias is class name but createQueryBuilder has param set ailas.
2. `"User"."password" AS "User_password", "User"."password"` has tow `password` field select.
3. getOne not has limit?

**Comment by Kononnable** [comment]
You wrote points in questions, but only the last one is actually a question.

1 - passing alias param is optional
2 - You've selected every field from entity and then added a select of password field again - so yes, this field is selected two times
3 - If you're looking for limit it has a separate method - just add `.limit(1)`
