### ISSUE TITLE
Automatic switch to ts/ js entities depending on the run mode(ts, node)

### ISSUE THREAD

**Issue by hatim-heffoudhi** [typeorm/typeorm#4134]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

First of all, thank you for this awesome project 💯 , its very usefull 👍  !!
I have a question, in the documention to mention the path of the entities. 
if we use javascript run,  we specify the path js example : 

```
"logging": true,
  "entities": ["dist/main/infrastructure/db/entity/**/*.js"]
```

And for Ts node, we change to 

```
"logging": true,
  "entities": [
    "src/main/infrastructure/db/entity/**/*.ts"
  ],
```

This is manually action, my question please, 
Is there any  automatic configuration for this need ? to reduce this action ?

**Comment by Kononnable** [comment]
Depending on your configuration you might want to use `*.{js,ts}`. If you're compiling typescript to another folder(`outDir` in `tsconfig.json`) this should work just fine.

**Comment by hatim-heffoudhi** [comment]
thank you @Kononnable , for your answer, you see in  my question i put : 
```
"logging": true,
  "entities": [
    "src/main/infrastructure/db/entity/**/*.ts"
  ],

```

```
"logging": true,
  "entities": ["dist/main/infrastructure/db/entity/**/*.js"]

```
In the ormconfig.json , we specify the absolute path of the entities,for ts it's src and for js is dist, is there any option like that  : ?

  ```
"entities": [
    "__dirname/infrastructure/db/entity/**/*.{js,ts}"
  ],

```

**Comment by Kononnable** [comment]
I think it is still relative path, not absolute one. Maybe you should change location of ormconfig.json. It's hard to tell without knowledge of your project structure. If it still doesn't help you can pass orm options as js object - then you could write your own logic to choose different entities folder(if it's a complicated logic).

**Comment by hatim-heffoudhi** [comment]
hello @Kononnable , thank you for your return, i've changed the implementation programmatically.
