### ISSUE TITLE
Uncaught ColumnTypeUndefinedError with Electron, mysql

### ISSUE THREAD

**Issue by EngrKhizarIqbal** [typeorm/typeorm#4135]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

First thanks to all of you for this awesome library. After struggling with Sequelize for one week to use it with typescript, I finally decided to use typeorm. My background is .NET and I feel really comfortable with it.

Before moving to the electron, I've successfully checked the app in Node/express and it worked perfectly in the test app. So, I've moved to electron app. I've generated migrations, created the database and run the migration successfully.

I've checked the [official electron typescript example repo](https://github.com/typeorm/electron-typescript-example), but it addresses the uses of the app in an HTML page or in the main.js page, while I want to isolate it so that we can use the same react app in the website.

I am developing an app in electron js with react. I'm getting the following error when I run the app.
```
ColumnTypeUndefinedError.js:9 Uncaught ColumnTypeUndefinedError: Column type for Customer#name is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also, make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported). If you are using JavaScript instead of TypeScript you must explicitly provide a column type.
```

My ormconnection.json
```
{
    "type": "mysql",
    "host": "localhost",
    "port": 3306,
    "username": "root",
    "password": "root",
    "database": "easy-inventory",
    "synchronize": false,
    "logging": true,
    "migrationsRun": false,
    "entities": ["src/server/database/entity/**/*.ts"],
    "migrations": ["src/server/database/migration/**/*.ts"],
    "subscribers": ["src/server/database/subscriber/**/*.ts"],
    "migrationsTableName": "__migrations",
    "cli": {
        "entitiesDir": "src/server/database/entity",
        "migrationsDir": "src/server/database/migration",
        "subscribersDir": "src/server/database/subscriber"
    }
}
```
packages.json (only relevent packages)
```
"dependencies": {
      "mysql": "^2.14.1",
      "reflect-metadata": "^0.1.10",
      "typeorm": "0.2.17"
   },
"devDependencies": {
      "typescript": "^3.4.5",
      "ts-node": "^8.1.0",
},
"scripts": {
      "start:react:dev": "cross-env TS_NODE_PROJECT=\"tsconfig-for-webpack-config.json\" webpack-dev-server --config config/webpack.react.dev.config.ts",
      "typeorm-cli": "ts-node .\\node_modules\\typeorm\\cli.js"
}
```

Customer.ts
```
import { PrimaryGeneratedColumn, Column, Entity } from 'typeorm';

@Entity()
class Customer {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;
}

export default Customer;
```

App.tsx
```
import 'reflect-metadata'; 
import * as ReactDOM from 'react-dom';
import * as React from 'react';

import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/css/bootstrap-grid.min.css';

import Dashboard from './components/Dashboard';

ReactDOM.render(<Dashboard />, document.getElementById('easy-inventory-root'));

if (module.hot) {
    module.hot.accept();
}
```
I don't understand why I'm getting this error. When I update my Customer's name column with the following:
```
@Column({
        type: 'text',
        nullable: false
    })
    name: string;
```
I got the following error:
```
Uncaught ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (http://localhost:3000/bundle.js:76330:28)
    at ConnectionManager../node_modules/typeorm/browser/connection/ConnectionManager.js.ConnectionManager.get (http://localhost:3000/bundle.js:65337:19)
    at getRepository (http://localhost:3000/bundle.js:78822:35)
    at new CustomerRepository (http://localhost:3000/bundle.js:100243:90)
    at new Dashboard (http://localhost:3000/bundle.js:100157:32)
    at constructClassInstance (http://localhost:3000/bundle.js:31827:18)
    at updateClassComponent (http://localhost:3000/bundle.js:35153:5)
    at beginWork (http://localhost:3000/bundle.js:36110:16)
    at performUnitOfWork (http://localhost:3000/bundle.js:39778:12)
    at workLoop (http://localhost:3000/bundle.js:39818:24)
```

Can anyone please guide to solve this issue.
Thanks in advance.
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
It looks like electron is bundling your code to js file(it probably also minifying them). That's why you it can't find ormconfig file - because it doesn't exist in bundled environment. You should move ormconfig to js and pass it as a parameter.

As for the error with column without know type - you should check solutions described in error message. If that doesn't help take a look at your configuration. Maybe minification breaks metadata from typescript types. But you can still use typeorm with defining column types explicitly.

**Comment by Vienkk1010** [comment]
In file **tsconfig.json** add line code above:
"emitDecoratorMetadata": true

**Comment by imnotjames** [comment]
This seems like an issue with your environment, not typeorm.  As such, I'm gonna close it but if you can get more information that points at this being a typeorm specific issue please feel free to open a new issue.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
