### ISSUE TITLE
TypeScript target:es2015 not supporting OneToOne

### ISSUE THREAD

**Issue by kbajalc** [typeorm/typeorm#414]
When using tsc with target es2015, the sample for OneToOne compiles but module load fails with: ```ReferenceError: PostMetadata is not defined``` or ```ReferenceError: Post is not defined``` depending which class is first to use the OneToOne relation. Same behavior with node 7.3.0 and 6.10;

It is strange that many other entities using a network of ManyToOne and OneToMany work fine with target es2015. 

Please clarify if typeorm must be used with target es5 as in the tsconfig.json on this git repo. The code bellow works fine with es5. 

```
import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    OneToOne,
    JoinColumn
} from "typeorm";

@Entity("sample2_post")
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    title: string;

    @Column()
    text: string;

    @OneToOne(type => PostMetadata, metadata => metadata.post, {
        cascadeRemove: true
    })
    @JoinColumn()
    metadata: PostMetadata;
}

@Entity("sample2_post_metadata")
export class PostMetadata {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    description: string;

    @OneToOne(type => Post, post => post.metadata)
    post: Post;

}
```

**Comment by pleerock** [comment]
what is your node.js version?

**Comment by kbajalc** [comment]
node 7.3.0 and 6.10; checked with both - same behavior

**Comment by pleerock** [comment]
wait I see your problem now. you cant first use class, then define it. Simply extract both your classes into separate files and import dependencies.

**Comment by pleerock** [comment]
let me know if you still have problems with it
