### ISSUE TITLE
Postgre One-To-Many relation not returning any data

### ISSUE THREAD

**Issue by k0eff** [typeorm/typeorm#4141]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next` 
[x] `0.2.7` (or put your version here)
[x] `0.3.0-alpha.23` (or put your version here)
currently next version is 0.3.0-alpha.23

**Steps to reproduce or a small repository showing the problem:**

Following the example of Many-to-one / One-to-many relations https://github.com/typeorm/typeorm/blob/master/docs/many-to-one-one-to-many-relations.md
What I got: empty array (no results)
What I expect to get: a result of Entity Product with "qty" array populated with 1 row. With Quantity table row joined to the Product table row

What I got:
```json
{}
```
What I expected to get:
```json
{"id":1,"name":"Banana","descr":"good quality bananas","categories":[{"id":2,"name":"Fruits"}], "qty":[{"num":20}]}
```

---

Code used:
```typescript
    .findOne({ where: { id }, relations: ["qty"] })
```

Note: if you provide the Category relation (Many-to-many) using
```typescript
    .findOne({ where: { id }, relations: ["categories"] })
```
it works.

However if you add qty
```typescript
    .findOne({ where: { id }, relations: ["qty", "categories"] })
```
it doesn't work and again returns 
```json
{}
```

---
---
Steps to reproduce:

Product.ts
```typescript
import { Category } from "./Category";
import { Quantity } from "./Quantity";
import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  OneToMany,
  ManyToMany,
  ManyToOne,
  JoinColumn,
  JoinTable
} from "typeorm";

@Entity()
export class Product {
  @PrimaryGeneratedColumn("increment")
  id: number;

  @Column("character varying")
  name: string;

  @Column("text")
  descr: string;

  @OneToMany(type => Quantity, quantity => quantity.id)
  qty: Quantity[];

  @ManyToMany(type => Category)
  @JoinTable({
    name: "ProductRelCategory",
    joinColumn: {
      name: "productId",
      referencedColumnName: "id"
    },
    inverseJoinColumn: {
      name: "catId",
      referencedColumnName: "id"
    }
  })
  categories: Category[];
}
```

---
Quantity.ts
```typescript
import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  ManyToOne,
  JoinColumn
} from "typeorm";
import { Product } from "./Product";

@Entity()
export class Quantity {
  @PrimaryGeneratedColumn("increment")
  id: number;

  @Column({
    type: "int",
    nullable: false
  })
  num: number;

  @ManyToOne(type => Product, product => product.qty)
  @JoinColumn({ name: "productId" })
  product: Product;
}
```

---
Category.ts
```typescript
import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  OneToMany,
  ManyToOne
} from "typeorm";

@Entity()
export class Category {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    type: "character varying",
    length: 255
  })
  name: string;

  @ManyToOne(type => Category, category => category.children)
  parent: Category;

  @OneToMany(type => Category, category => category.parent)
  children: Category[];
}
```
---

productRouter.ts
```typescript
router.get("/id/:id", (req: Request, res: Response) => {
  let id: number = parseInt(req.params.id) || null;

  getRepository(Product)
    .findOne({ where: { id }, relations: ["qty"] })
    .then(product => {
      console.log(product);

      res.json(product);
    })
    .catch(err => {
      res.status(200).send(err);
    });
});
```

---

Quantity table
```csv
"id","num","productId"
2,20,1
5,30,1
```

Product table:
```csv
"id","name","descr"
1,"Banana","good quality bananas"
```

Category table:
```csv
"id","name","parentId"
1,"Fruits & Vegetables",NULL
2,"Fruits",1
```

ProductRelCategory table:
```csv
"productId","catId"
1,2
```

**Comment by Kononnable** [comment]
>` @OneToMany(type => Quantity, quantity => quantity.id)`

Should be `@OneToMany(type => Quantity, quantity => quantity.product)` You should point to other side of relation, not PK of other table.

**Comment by imnotjames** [comment]
Hope this was an answer to your question.  Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
