### ISSUE TITLE
`SQLITE_ERROR: near "-": syntax error` when use sqlite, simple-enum

### ISSUE THREAD

**Issue by if1live** [typeorm/typeorm#4147]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

repo : https://github.com/5minlab/typeorm-sqlite-simple-enum-bug

1. create new typeorm project. I use `typeorm init`
2. use simple-enum. I modify `src/entity/User.ts`

```typescript
export enum UserType {
    Normal = "normal",
    Admin = "admin",
}

@Entity()
export class User {
    ....
    @Column({
        type: "simple-enum",
        enum: UserType,
    })
    ty: UserType;
}
```

3. use sqlite, enable sychronize in ormconfig.json, execute twice.

first execution, working well.
```
PS F:\bug\typeorm-sqlite-simple-enum-bug> npm run start

> sqlite-simple-enum@0.0.1 start F:\bug\typeorm-sqlite-simple-enum-bug
> ts-node src/index.ts

Inserting a new user into the database...
Saved a new user with id: 1
Loading users from the database...
Loaded users:  [ User {
    id: 1,
    firstName: 'Timber',
    lastName: 'Saw',
    age: 25,
    ty: 'admin' } ]
Here you can setup and run express/koa/any other framework.
```

second execution, not working.
`SQLITE_ERROR: near "-": syntax error`.
`simple-enum` is included in SQL.

```
PS F:\bug\typeorm-sqlite-simple-enum-bug> npm run start

> sqlite-simple-enum@0.0.1 start F:\bug\typeorm-sqlite-simple-enum-bug
> ts-node src/index.ts

{ QueryFailedError: SQLITE_ERROR: near "-": syntax error
    at new QueryFailedError (F:\bug\typeorm-sqlite-simple-enum-bug\src\error\QueryFailedError.ts:9:9)
    at handler (F:\bug\typeorm-sqlite-simple-enum-bug\src\driver\sqlite\SqliteQueryRunner.ts:53:26)
    at replacement (F:\bug\typeorm-sqlite-simple-enum-bug\node_modules\sqlite3\lib\trace.js:19:31)
    at Statement.errBack (F:\bug\typeorm-sqlite-simple-enum-bug\node_modules\sqlite3\lib\sqlite3.js:16:21)
  message: 'SQLITE_ERROR: near "-": syntax error',
  errno: 1,
  code: 'SQLITE_ERROR',
  name: 'QueryFailedError',
  query:
   'CREATE TABLE "temporary_user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "age" integer NOT NULL, "ty" simple-enum CHECK( ty IN (\'normal\',\'admin\') ) NOT NULL)',
  parameters: [] }
```

I modify `src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts` to fix bug.
but I can't trust my approach.

https://github.com/5minlab/typeorm/commit/ed4e91d1381d60e94299ddf99e1290a52c1bc99f

**Comment by goldcaddy77** [comment]
I ran into this issue, too, and this was the fix I used:  https://github.com/typeorm/typeorm/pull/4379

I have no idea if that's the right way to do it, though... hoping somebody on the project will be able to guide us in the right direction.
