### ISSUE TITLE
Support for async ormconfig

### ISSUE THREAD

**Issue by moltar** [typeorm/typeorm#4149]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

---

Propose to support async/Promises returned from the `ormconfig.js` and `ormconfig.ts` files.

The use case for this is to be able to figure out connection details in a non-standard ways.

E.g. two uses cases come to mind:

1. Database credentials are obtained from a remote secret store.
2. Loading up complex configs from store in a non-blocking way. E.g. reading many files and combining the config.
2. Usage of dependency inversion containers. E.g. load up config as a dependency first, and then inject the config somewhere. This is my actual use case atm.

I think the fix can be pretty simple. We can just `Promise.resolve` any output from the `.js` and `.ts` files. If it is static data, then it will be resolved immediately anyways, if it's a Promise, then we'll wait for the Promise to resolve.

Example use case:

```
module.exports = () => {
  return Promise.resolve({
    type: 'postgres',
    url: process.env.DATABASE_URL,
  })
}
```

---

I can work on a PR, if this is deemed to be a good feature.

**Comment by Kononnable** [comment]
I don't think this is really necessary. You don't need to use ormconfig at all. You can just pass your connection options to `createConnection` method. This way you can do anything in determining what connection option should be.

In future version we plan to deprecate and finally remove passing options as ormconfig file or connection environment variables.

**Comment by moltar** [comment]
But how would that work with the CLI? What if my options are NOT in the env?

**Comment by Kononnable** [comment]
Yeah, you found a hole in my reasoning. I've completely forgot that ormconfig is useful with cli(again?). It looks like a small change(check if object is a promise, await if it is) so I think it won't hurt us to have it. 

But to be honest I don't like such design. I think ormconfig should be local and if there is some logic on determining it - it should be done once in environment preparation stage(e.g. docker image build or before app is run).
For cli it should be a problem, but what if someone use such approach with a standard application? Application will be running in multiple instances and someone decide to indirectly change the ormconfig while app is running. Now let's assume that one instance has gone wild and had to be restarted. After restart it will be using different ormconfig then rest of the app and it could cause some serious damage.

**Comment by moltar** [comment]
Right.

My actual main use case is that I am using a dependency inversion container (`typedi`).

And I am loading config as a dependency, and all of that is very much async. I have no other option.

---

But for the 12 factor use case, where config is loaded and injected before hand - I tend to agree with your reasoning. I usually prefer to do that too.

But I know there are some use cases where that is not possible due to organizational constraints.

For example, sometimes I've seen database config is provisioned via HashiCorp Vault for a K8S container. And since credentials change often, that would require a container restart on each credential change. So the preferred method is to poll for connection details inside the app itself.

---

I don't think there is a hard rule that the database configuration MUST be obtained in a sync way. I feel this is something, us as developers, have imposed onto ourselves. But in reality, there are plenty of use cases in production when configuration is obtained in async way.

**Comment by moltar** [comment]
I think the fix can be as simple as just adding `Promise.resolve()` around the final return.

Because if the value is not a promise, it will just resolve right away.

If it is a promise, it will wait for resolution first.

Pseudo-code:

```ts

async function configGetter() {
  return Promise.resolve({})
}

const configSync = await Promise.resolve( require('./ormconfig.json') )

const configAsync = await Promise.resolve( configGetter() )
```

Both of these lead to the same end result - a resolved config.

**Comment by moltar** [comment]
I think this:

https://github.com/typeorm/typeorm/blob/3d65c275984a5203e799284ffb7395f2dc05c617/src/connection/ConnectionOptionsReader.ts#L114

If we'd change it to:

```ts
connectionOptions = await Promise.resolve( PlatformTools.load(configFile) );
```

(and the same for JS case)

Then this would maintain backward compatibility and allow for async configs.

**Comment by FLoppix** [comment]
Any update on this?

**Comment by biern** [comment]
For anyone else in dire need of this feature, I'm sharing a hack that we've been using as a workaround successfully for some time (thanks @moltar for suggestions where it should be patched).

`ormconfig.ts`:
```typescript
import { ConnectionOptionsReader } from 'typeorm/connection/ConnectionOptionsReader';

function patchAsyncConnectionSetup() {
  const prototype = ConnectionOptionsReader.prototype as any;

  const original = prototype.normalizeConnectionOptions;

  prototype.normalizeConnectionOptions = function(
    options: Promise<any> | object,
  ) {
    if ('then' in options) {
      return options.then((arg) => original.call(this, arg));
    }

    return original.call(this, options);
  };
}

patchAsyncConnectionSetup();

async function buildConnectionOptions() { ... }

const config = buildConnectionOptions();

export = config;
```

Tested with `typeorm 2.0.18`

**Comment by Bnaya** [comment]
its also useful when i'm using kms to encrypt secrets and need to decrypt them asynchronously

**Comment by Safiyya** [comment]
Thanks @biern for the hack. I get an error 
```
import { ConnectionOptionsReader } from 'typeorm/connection/ConnectionOptionsReader';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Function.PlatformTools.load (/Users/USER/PATH/node_modules/typeorm/platform/PlatformTools.js:108:28)
    at ConnectionOptionsReader.<anonymous> (/Users/USER/PATH/node_modules/typeorm/connection/ConnectionOptionsReader.js:121:75)
    at step (/Users/USER/PATH/node_modules/tslib/tslib.js:136:27)
```

Here is my `ormconfig.ts`: 

```
import { ConnectionOptionsReader } from 'typeorm/connection/ConnectionOptionsReader';
import {
  SQL_PORT,
  SQL_LOGGING,
  SQL_HOST,
  SQL_USERNAME,
  SQL_PASSWORD,
  SQL_DATABASE,
} from 'datasources/sql/constants/config.json';
import EnvKeys from 'constants/env-keys';
import Environments from 'constants/environments';
import { getEnvs } from '@packages/infrastructure';

// This is a hacky patch
// async functions for the ormconfig
/* eslint-disable */

function patchAsyncConnectionSetup() {
  const { prototype } = ConnectionOptionsReader;

  // @ts-ignore
  const original = prototype.normalizeConnectionOptions;

  // @ts-ignore
  prototype.normalizeConnectionOptions = function(options) {
    if ('then' in options) {
      // @ts-ignore
      return options.then(arg => original.call(this, arg));
    }

    return original.call(this, options);
  };
}
/* eslint-enable */
// @ts

patchAsyncConnectionSetup();

async function buildConnectionOptions() {
  const configs = [
    EnvKeys.ENV,
    SQL_PORT,
    SQL_LOGGING,
    SQL_HOST,
    SQL_USERNAME,
    SQL_PASSWORD,
    SQL_DATABASE,
  ];
  const [
    env,
    port,
    logging,
    host,
    username,
    password,
    database,
  ] = await Promise.all(configs.map(getEnvs));

  const isLocal = env === Environments.LOCAL;
  const extension = isLocal ? 'ts' : 'js';

  const config = {
    type: 'mysql',
    host: isLocal ? host : undefined,
    port: Number(port),
    username,
    password,
    database,
    synchronize: true,
    entities: [`src/datasources/sql/entities/**/*.${extension}`],
    migrations: [`src/datasources/sql/migrations/**/*.${extension}`],
    // subscribers: [
    //   `src/datasources/sql/subscribers/**/*.${extension}`,
    // ],
    cli: {
      migrationsDir: 'src/datasources/sql/migrations',
    },
    logging: logging === 'true',
    // extra: {
    //   socketPath: !isLocal ? `/cloudsql/${host}` : undefined,
    // },
  };

  return [
    {
      ...config,
    },
    {
      ...config,
      name: 'seed',
      migrationsTableName: 'seeds',
      migrations: `src/datasources/sql/seeds/**/*.${extension}`,
      cli: {
        migrationsDir: `src/datasources/sql/seeds/**/*.${extension}`,
      },
    },
  ];
}

const config = buildConnectionOptions();

module.exports = config;
``` 

When using a simple `ormconfig.json` with the same arguments, it works but not with the `ormconfig.ts`. Any idea what I'm missing?

**Comment by abhimanusharma** [comment]
I am trying to connect with mongoDB atlas, 

Thanks to @biern I was able to make my ormconfig async and config values are loaded successfully, even then when I am trying to save a data in the mongoDB atlas, it is throwing error
```
/var/www/html/project_dev/node_modules/typeorm/connection/ConnectionOptionsReader.js:36
                            throw new Error("No connection options were found in any orm configuration files.");
                                  ^

Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/var/www/html/project_dev/node_modules/typeorm/connection/ConnectionOptionsReader.js:36:35)
    at step (/var/www/html/project_dev/node_modules/tslib/tslib.js:143:27)
    at Object.next (/var/www/html/project_dev/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/var/www/html/project_dev/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

Here is my ormconfig.ts file.

```
import { ConnectionOptions } from 'typeorm';
import * as dotenv from 'dotenv'
import * as fs from 'fs'
import * as path from 'path'
import { SecretManager } from "@app/utils/util";
import { ConnectionOptionsReader } from 'typeorm/connection/ConnectionOptionsReader';

function patchAsyncConnectionSetup() {
	const prototype = ConnectionOptionsReader.prototype as any;
  
	const original = prototype.normalizeConnectionOptions;
  
	prototype.normalizeConnectionOptions = function(
	  options: Promise<any> | object,
	) {
	  if ('then' in options) {
		return options.then((arg) => original.call(this, arg));
	  }
  
	  return original.call(this, options);
	};
  }
  patchAsyncConnectionSetup();

/**
 * @Type - @config- For typeOrm with Database
 * @name ConnectionOptions
 * @description This ConnectionOptions used to access the database cred for app.
 * @return { export } export the database configurations to use on time migrations,seeds with cli.
 */
const currentEnv = process.env.NODE_ENV || 'local'
const envConfig: any = dotenv.parse(fs.readFileSync(path.resolve(process.cwd(), 'api/env', `.env.${currentEnv}`)))

const entityPath = path.join(__dirname, "../db/models/**/*{.ts, .js}");

async function buildConnectionOptions() {	
	const sm = await SecretManager();

	if(sm) {
                console.log(sm); // here it is loading all keys from aws successfully.

		const conf:  ConnectionOptions = {
			type: envConfig.DATABASE_TYPE,
			url: sm.MONGO_URL,
			connectTimeoutMS: 80000,
			useUnifiedTopology: true,
			useNewUrlParser: true,
			entities: [entityPath],
			synchronize: false,
			logging: true,
			logger: 'file',
			migrations: ['src/db/migrations/*.ts'],
			cli: {
				migrationsDir: 'src/db/migrations',
			},
		}
		return conf;
	}
}

const config = buildConnectionOptions();

export default config
```
I have tried debugging all config  related files and tried searching any article to connect my NestJs application with typeorm and mongodb but even after trying my best I am still getting above error.

Using current latest version of NestJs and typeorm.

**Comment by LeOndaz** [comment]
@StevenGBrown @pleerock 
I've created an app with a `ormconfig.ts` that returns an async function. For some reason, the function is being passed to typeorm as "Async function" and it doesn't get evaluated. It didn't get `await`ed. Any ideas? [more](https://stackoverflow.com/questions/68979725/typeorm-cli-wont-await-the-exported-async-method-from-ormconfig-ts) info

**Comment by LeOndaz** [comment]
Okay that's totally my bad. 

```
// a.ts
const f = async () => {};
export f;
```
And now,
```
// b.ts
const f = await require('./a.ts');
```
This was what's happening, I was exporting the method itself and awaiting the require assuming it will call the method and await it, however, this was not the case. This will pass an "Async function" to typeorm.
This will work if:

```
// b.ts
const f = await require('./a.ts')();
```
but this requires working inside typeorm # fail

but we can:
```
// a.ts
const f = async () => {};
export f();
```
call f, so we require the f call and not f itself, so await works on it.

**Comment by mteichtahl** [comment]
> its also useful when i'm using kms to encrypt secrets and need to decrypt them asynchronously 

Would you have a sample ?

**Comment by ronnyhel** [comment]
I'm having an issue using migrations
`typeorm-ts-node-commonjs migration:run -d ormconfig.ts

Error during migration run:
Error: Given data source file must contain export of a DataSource instance
    at Function.loadDataSource (metadata-api/node_modules/src/commands/CommandUtils.ts:54:19)
    at async Object.handler (metadata-api/node_modules/src/commands/MigrationRunCommand.ts:42:26)
`
is #5048 supposed to work even with migrations?
