### ISSUE TITLE
Use full command in using-cli.md and migrations.md documentation

### ISSUE THREAD

**Issue by ambroiseRabier** [typeorm/typeorm#4151]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x ] documentation issue

https://github.com/typeorm/typeorm/blob/master/docs/using-cli.md with https://github.com/typeorm/typeorm/blob/master/docs/migrations.md describe how to make a migration.

https://github.com/typeorm/typeorm/blob/master/docs/using-cli.md#notes-on-entity-files-written-in-typescript this part is ok, giving full working command lines.

All the others command lines start by `typeorm ...` when they should start with `npm run typeorm`, for example `typeorm migration:create -n PostRefactoring` should be `npm run typeorm migration:create -n PostRefactoring`.

I suppose this has been made to reduce verbosity, but this is actually confusing to beginners.

**Comment by Kononnable** [comment]
Exact command really vary on how have you set up your environment. If you use `ts-node` you have added added commands to `package.json` - you will use `npm run ...`. If you installed typeorm globally you will use `typeorm ...`. If you only have installed typeorm as local dependency you may wish to use `npx typeorm ...`. 
All of those options are valid for some configurations. If you have an idea how to make docs more friendly you're welcomed to make a PR.
