### ISSUE TITLE
Eager relation are not loaded from both side...

### ISSUE THREAD

**Issue by Nooka10** [typeorm/typeorm#4154]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

```
@Entity('Parent')
export class Parent {
  ...

 @ManyToMany(type => Child, child => child.parents, { nullable: true, eager: true })
  childrens: Child[];
}


@Entity('Child')
export class Child {
...

  @ManyToMany(type => Parent, parent => parent.children, { nullable: true })
  @JoinTable()
  parents: Parent[];
}
```

With this two entities, when you use find() on Parent, the childrens are correctly loaded, but if you use find on Children, the parents are not...
I tried to put the eager tag on both side of the relation because it throw an error...
And if you inverse the situation like following, then use find() on Parent will not load the childrens relation but use find() on Children will load parents relation....

```
@Entity('Parent')
export class Parent {
  ...

 @ManyToMany(type => Child, child => child.parents, { nullable: true })
  childrens: Child[];
}


@Entity('Child')
export class Child {
...

  @ManyToMany(type => Parent, parent => parent.children, { nullable: true, eager: true })
  @JoinTable()
  parents: Parent[];
}
```

**Comment by hamiltop** [comment]
I don't think this is a bug. It's stated in the docs:

> Eager relations can only be used on one side of the relationship, using eager: true on both sides of relationship is disallowed.

To me that says that what you want is just not supported. Might be a worthy feature request though.
