### ISSUE TITLE
How to create and save a relation?

### ISSUE THREAD

**Issue by fookit** [typeorm/typeorm#4158]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This is my user model:
```ts
// user.model.ts
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text')
  name: string;

  @Column({
    unique: true
  })
  @Length(5, 100)
  @IsEmail()
  email: string;

  @Column()
  hashedPassword: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  /* eslint-disable */
  @OneToMany(type => Book, book => book.user)
  books: Book[];
}
```

And this is books model:
```ts
// book.model.ts
@Entity('books')
export class Book {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column()
  description: string;

  /* eslint-disable */
  @ManyToMany(type => Genre, genre => genre.books, {
    cascade: true
  })
  @JoinTable()
  genres: Genre[];

  @ManyToOne(type => User, user => user.books)
  user: User;
}
```

And this is the controller to handle `POST` request from `http://localhost:4000/users/:id/books`:
```ts
export async function usersCreateBook(
  req: Request,
  res: Response
): Promise<void> {
  try {
    // Get a user repository to perform operations with user
    const userRepository: Repository<User> = getManager().getRepository(User);
    // Get a book repository to perform operations with book
    const bookRepository: Repository<Book> = getManager().getRepository(Book);

    // Build up entity book to be saved
    const bookToBeSaved: Book[] = bookRepository.create(req.body);

    // Validate user entity
    const errors: ValidationError[] = await validate(bookToBeSaved, {
      skipMissingProperties: true
    }); // Errors is and array of validation errors

    if (errors.length > 0) {
      // Return a BAD REQUEST status code and errors array
      res.status(400).json(errors);
    } else {
      // Save the book contained in the POST body
      let book = await bookRepository.save(bookToBeSaved);

      // Load user by id
      let user = await userRepository.findOne(req.params.id);
      user.books.push(book);

      // Return a CREATED status code and updated book
      res.status(201).json({
        message: 'Book saved successfully',
        book
      });
    }
  } catch (e) {
    res.status(400).json({
      message: 'Failed to save boook',
      errors: e
    });
  }
}
```

I got an error:
```shell
error TS2345: Argument of type 'Book[]' is not assignable to parameter of type 'Book'.
  Type 'Book[]' is missing the following properties from type 'Book': id, title, description, genres, user

74       user.books.push(book);
```
How do I do that to save a user's book?

---
With Objection.js, I can do it with just:
```ts
// Load user by id
const user = await User.query().findById(req.params.id);
let product;

if (user) {
  product = await user
    .$relatedQuery<Product>("products")
    .insert(req.body);
```

Please help me.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by jcpc91** [comment]
maybe because Book is a class and you  need declare

`let user: Book = await userRepository.findOne(req.params.id);`

or make the properties optional with Interface

`export interface IBook {
  id?: number;
  title?: string;
  description?: string;
  genres?: Genre[];
  user?: User;
}`

`export class Book implements Ibook {

}`

**Comment by Mexman2Rowen** [comment]
@jcpc91 Tried both, still got the same error.

**Comment by alfonsoal1983** [comment]
What is the value of req.body? You are putting the parameters of the class book are mandatory but you may not be sending them well.
The error is telling you that some mandatory parameters of the book class have no value.
You have to look at the values ​​of the fields in object 'bookToBeSaved' to see if all the mandatory parameters have value

**Comment by Mexman2Rowen** [comment]
@alfonsoal1983 Thanks for enlightened me. Now I can save a user's book.
```ts
export async function usersCreateBook(
  req: Request,
  res: Response
): Promise<void> {
  try {
    // Get a user repository to perform operations with user
    const userRepository: Repository<User> = getManager().getRepository(User);
    // Get a book repository to perform operations with book
    const bookRepository: Repository<Book> = getManager().getRepository(Book);

    // Load user by id
    let user: User = await userRepository.findOne(req.params.id);

    let newBook = new Book();
    newBook.title = req.body.title;
    newBook.description = req.body.description;
    newBook.user = user;

    // Build up entity book to be saved
    const bookToBeSaved = bookRepository.create(newBook);

    // console.log(bookToBeSaved);

    // Validate user entity
    const errors: ValidationError[] = await validate(bookToBeSaved, {
      skipMissingProperties: true
    }); // Errors is and array of validation errors

    if (errors.length > 0) {
      // Return a BAD REQUEST status code and errors array
      res.status(400).json(errors);
    } else {
      // Save the book contained in the POST body
      let book = await bookRepository.save(bookToBeSaved);

      // Load user by id
      let user: User = await userRepository.findOne(req.params.id);
      user.books.push(book);

      // Return a CREATED status code and updated book
      res.status(201).json({
        message: 'Book saved successfully',
        book
      });
    }
  } catch (e) {
    res.status(400).json({
      message: 'Failed to save boook',
      errors: e
    });
  }
}
```
_(I didn't want to use `new Book()` because it's boring if the table has several columns)_

---
But somehow the `response` is:
```json
{
    "message": "Failed to save boook",
    "errors": {}
}
```

Even though I can `GET` an array of user's book from `/users/:id/books` and an array of all listed books from `/books`.

What went wrong?

**Comment by alfonsoal1983** [comment]
I need to know the body to see what the error may be.

Anyway I would make the following changes:

`let newBook = {
	title: req.body.title,
	description: req.body.description,
	user
};`

You dont need this
`// Build up entity book to be saved
const bookToBeSaved = bookRepository.create(newBook);`

And you should put this:
`let book = await bookRepository.save(newBook);`

**Comment by imnotjames** [comment]
Hope this answered your question, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
