### ISSUE TITLE
Unescaped table name in generated foreign key SQL

### ISSUE THREAD

**Issue by petargrchevski** [typeorm/typeorm#416]
The target database I'm using is MySQL. I have a table named "Condition". The table is created without any problem, but by using the `@ManyToOne()` relation when the foreign key is about to be added, the table name 'condition' is unescaped in the query and since condition is a reserved word, the query fails.

Example:

```ALTER TABLE condition ADD CONSTRAINT `fk_9b81e8bcc1d6703f77b8ed17cac` FOREIGN KEY (`ruleId`) REFERENCES `rule`(`ruleId`)```

I circumvented the issue by renaming the table, but perhaps it would be an improvement to have it quoted.

**Comment by pleerock** [comment]
Right looks like there left something unescaped

**Comment by pleerock** [comment]
this is already fixed in latest 0.1.0-alpha versions
