### ISSUE TITLE
Log entity files loaded from directories in debug mode

### ISSUE THREAD

**Issue by aktraore** [typeorm/typeorm#4162]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I lost a couple of hours during the last week because my glob pattern in the ormconfig.json/options object for entities was wrong. I fixed the issue later by putting a breakpoint in _DirectoryExportedClassesLoader.ts_ where the code for loading directory files is located. I was wondering if it would be possible to log (in debug mode) the files loaded or indicate that no files were found using the glob pattern supplied. At first glance the code would be in _DirectoryExportedClassesLoader.importClassesFromDirectories_ . I'd be willing to submit a PR if this is deemed a reasonable request.

**Comment by vlapo** [comment]
I think this is great idea. I am tired answering again and again same question about `RepositoryNotFoundError` or similar related to wrong glob pattern.

@pleerock @Kononnable what do you think about this idea? It is simple non-breaking change.

**Comment by Kononnable** [comment]
I think `debug` logging flag is a great idea, but we would need to find a very good spot for it in documentation, so people will know that it exists and can help them. I don't recall if we've already got any specific page about troubleshooting.

**Comment by vlapo** [comment]
I dont know if new `debug` mode is necessary. I thought we can show list of loaded entities with full path when `logging` in connection option is enabled.

**Comment by Kononnable** [comment]
Well maybe not introducing a new flag, but we could put it in one of the existing ones. We've got quite a bit of options with logging levels and just enabling it for `logging:true` might not be a good idea. Not sure if all of the flags are really used.

```typescript
export type LoggerOptions = boolean|"all"|("query"|"schema"|"error"|"warn"|"info"|"log"|"migration")[];
```

**Comment by vlapo** [comment]
Of course. I suggest `info` or `log`. And `troubleshooting` page in docs should be great!

@aktraore are you still interested in submitting a PR?

**Comment by aktraore** [comment]
Ok, I'll to submit something in the coming days.

**Comment by aktraore** [comment]
@vlapo , @Kononnable , I've submitted the PR. https://github.com/typeorm/typeorm/pull/4346
I tried my best with the mandarin (google trad) for the docs.
