### ISSUE TITLE
Question about TransactionalEntityManager

### ISSUE THREAD

**Issue by FelipeTaiarol** [typeorm/typeorm#4168]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Regarding this part of the documentation:

> The most important restriction when working in an transaction is, to ALWAYS use the provided instance of entity manager - transactionalEntityManager in this example. If you'll use global manager (from getManager or manager from connection) you'll have problems. You also cannot use classes which use global manager or connection to execute their queries. All operations MUST be executed using the provided transactional entity manager.

Could you give more details about why this is needed? I assume it is required so that all SQL statements are executed in the same transaction, but what if I have some statements that are not important to be in the transaction? Is it still required that I use the same EntityManager?

I'm asking because I am having a problem where all my connections are "idle in transaction" and I think this is happening because I am using a different EntityManager inside of a transaction.

I have many parallel requests that do the following:
```
this.getConnection().then(connection => {
    return connection.transaction(em => runInTransaction(em));
 });
```

Inside ```runInTransaction``` most operations are done using the EntityManager, but some are not (there is no good reason why they aren't, mostly because of code organization and also because I don't need transaction guarantees for them). 

The ones that are not executed using the transactional EntityManager get a SelectQueryBuilder by doing:

```
this.getConnection().then(conn => conn.createQueryBuilder());
```

I think this is causing a deadlock in my application logic. 

The transaction will only be commited when the promise returned by ```runInTransaction``` resolves. This promise is waiting on a query created with an EntityManager that is not the transactional EntityManager. And that EntityManager may be waiting for a connection that is in a similar situation. So the ```runInTransaction``` Promise will never resolves, meaning the transaction will never be commited, meaning the connection will be blocked forever. If that happens to all connections the service is not able to connect to the database anymore.

I understand this can be solved by simply following what the documentation clearly says :) 

I created this issue because this is a race condition problem that is not always reproducible so I just wanted to confirm that my understanding of the root cause is correct.

**Comment by FelipeTaiarol** [comment]
Sorry, I created before finishing to write it, I'll close it and reopen it soon.

**Comment by Kononnable** [comment]
Enable logging in connection options and you should be able to see where your program is stopping.
As for using another entity manager - it will use another connection from the poll so it will run outside of your transaction. There are two major side effects on that:
* queries won't produce locks for time of whole transaction
* queries won't be able to use records locked by active transaction(depending on your server settings)

I bet you're hitting the second point - trying to read something that is already locked by an active transaction.

**Comment by imnotjames** [comment]
Hope this was an answer to your question.  Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
