### ISSUE TITLE
Get list of excluded columns.

### ISSUE THREAD

**Issue by maxchehab** [typeorm/typeorm#4172]
**Issue type:**
How does one get a list of excluded columns? I noticed that `EntityMetadata` has an `exclusions` property, however it is an empty array upon transpilation.
[ ] question
[ ] bug report
[] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
const metadata: EntityMetadata =  this.repository.metadata;
console.log(metadata.exclusions) // []
```

**Comment by Kononnable** [comment]
Please create reproduction repo/failing test. I've tested and it is correctly filled with data so it must be something in your setup.
