### ISSUE TITLE
how to model/use a relation with a compound key

### ISSUE THREAD

**Issue by sthuck** [typeorm/typeorm#4175]
**Issue type:**

[x ] question

**Database system/driver:**
[x] `mssql`

**TypeORM version:**

[ ] `0.2.16`

Hi, 

I'm trying to build a favorite/like mechanism for my app, need some help figuring out the typeorm way to do this. 

basically I have my entity:
```ts
@Entity()
class Photo {
@PrimaryColumn({...dbConf.idColumn})
  id!: string;
//other stuff goes here
}
```
but since I want "likes" to be saved per user, I created the following table, where if a row exists means the user "likes" this entity.

```ts
@Entity()
export class Favorites {
  @Column({...dbConf.shortTextField, primary: true, unique: false})
  owner!: string;

  @Column({...dbConf.idColumn, unique: false, primary: true})
  entityId!: string;
}
```

now as you can see I need to do the join manually, as `OneToOne` doesn't really apply here, I need to provide an `owner`.

(not sure what the terminology is for what I'm looking for, would edit title for better google if anyone has a suggestion)

My initial and unsuccessful approach is using `leftJoinAndMapOne`.
I have added a field to `Photo` class called `isLiked`, but didn't decorate it with a `@Column` as I don't want it as a column on the photo table.
```ts

async function demo() {
  const conn = await createConnection();
  const photoRepo = conn.getRepository(Photo);
  const id = 'someId';
  const owner = 'someOwner@foo.com';

  const q = notebookRepo
    .createQueryBuilder('photo')
    .leftJoinAndMapOne(
      'photo.isLiked',  //also tried just 'isLiked'
      qb =>
        qb
          .from(Favorites, 'favorites')
          .select('entityId is not null', 'liked') 
          .where(`favorites.owner = :owner and favorites.entityId = :id`, {
            owner,
            id
          }),
      'f1',
      `1 = 1`
    )
    .where('photo.id = :id', {id});

  console.log(q.getQueryAndParameters());
  const result = await q.getOne();
  console.log(result);

  await conn.close();
}
```
if I do `q.getRawOne()` I see that a value for `liked` is returned, however when going `getOne()` it's not mapped and doesn't appear on the object.

So, any idea what I'm doing wrong with `leftJoinAndMapOne`?

Alternatively, is there a way to do this join with multiple keys with typeorm without going into the query builder?(seems like no, but typeorm has surprised me in the past 💯 )

**Comment by Kononnable** [comment]
You should be able to use `OneToMany` relation. Then just fetch it and filter on your user.
```typescript
await connection.getRepository(Favorites)
      .findOne({ where: { owner:1 }, relations: ["photo"] })
```

**Comment by imnotjames** [comment]
Hope this was an answer to your question.  Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
