### ISSUE TITLE
Returns last id on multiple insertion

### ISSUE THREAD

**Issue by deeptechuz** [typeorm/typeorm#4176]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Just try to insert multiple values at a time with any of `queryBuilder` or `repository`.

Got result something like below:

```
InsertResult {
  identifiers:
   [ { id: 67 },
     { id: 67 },
     { id: 67 },
     { id: 67 },
     { id: 67 },
     { id: 67 } ],
  generatedMaps:
   [ { id: 67 },
     { id: 67 },
     { id: 67 },
     { id: 67 },
     { id: 67 },
     { id: 67 } ],
  raw:
   OkPacket {
     fieldCount: 0,
     affectedRows: 6,
     insertId: 67,
     serverStatus: 2,
     warningCount: 0,
     message: '&Records: 6  Duplicates: 0  Warnings: 0',
     protocol41: true,
     changedRows: 0 } }

```

As you can see I got last inserted `id`.
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by deeptechuz** [comment]
Hey guys, 
any solutions or references?

**Comment by Kononnable** [comment]
Ahh, you didn't put any reproduction code, so I can only assume that your results are correct.
I think there was a similar issue here ... somewhere ...

Please add some code on which we could reproduce the issue.

**Comment by vlapo** [comment]
Same as https://github.com/typeorm/typeorm/issues/2131 ?

**Comment by deeptechuz** [comment]
> Same as #2131 ?

@vlapo and @Kononnable Thanks for replying guys.

Yeah it looks same!
