### ISSUE TITLE
Selecting nested relations missing in @next

### ISSUE THREAD

**Issue by oskarious** [typeorm/typeorm#4177]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[ ] `latest`
[X] `@next (0.3.0-alpha.23)`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, I am using @next since it fixes an issue we were having with `where` options, however, some of the `relations` options seem to be broken/missing. As outlined [here](https://github.com/typeorm/typeorm/issues/1270#issuecomment-348429760) and in the [docs](https://typeorm.io/#/find-options/basic-options), you are supposed to be able to select sub-entities using `relations: ['ent1', 'ent1.prop1']`, alternatively, using `join`, but it doesn't seem to exist anymore.

We can use query builder as a last resort, but it seems silly if there already exists good features in the find options. 

Have they been dropped, or is it just a case of the alpha missing features?

`getManager().find(Channel, {relations: ['booking', 'messages', 'users', 'booking.user'],})`
This line throws the following typescript error: `Argument of type 'typeof Channel' is not assignable to parameter of type 'string'.ts(2345)`

**Comment by Tooyz** [comment]
You should use it as 
```
getManager().find(Channel, {relations: {
  booking: {
    user: true
  },
  messages: true,
  users: true
}})
```

**Comment by oskarious** [comment]
Yep, that was it! Thanks 😊

**Comment by paulmil1** [comment]
how do u even use it?
![image](https://user-images.githubusercontent.com/38671110/68090342-f1ebcc80-fe72-11e9-8557-428db4097f4a.png)

using latest version of typeorm@next ....
