### ISSUE TITLE
Add support for CLI configuration in JavaScript format

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#418]
This is related to this issue/comment: https://github.com/typeorm/typeorm/issues/391#issuecomment-296395159

I would suggest to add a way to use a CLI configuration not only in JSON, but in JavaScript format too. This will allow us to have some logic for configuration. In my case I want to use configuration values, loaded from environment. There is no way to implement it in JSON, because JSON is a plain string format.

The CLI could look for the `ormconfig.js` first and then for `ormconfig.json`.

**Comment by pleerock** [comment]
its supported from `0.1.0-alpha.8`. Create `ormconfig.js`:

```js
module.exports = [
    {
        "name": "default",
        "driver": {
            "type": "mysql",
            "host": "localhost",
            "port": 3306,
            "username": "test",
            "password": "test",
            "database": "test"
        },
        "autoSchemaSync": true,
        "entities": [
            "src/entity/*.js"
        ],
        "subscribers": [
            "src/subscriber/*.js,"
        ],
        "migrations": [
            "src/migration/*.js"
        ],
        "cli": {
            "entitiesDir": "src/entity",
            "migrationsDir": "src/migration",
            "subscribersDir": "src/subscriber"
        }
    }
];
```
