### ISSUE TITLE
Use conventional commit message approach 

### ISSUE THREAD

**Issue by deeptechuz** [typeorm/typeorm#4183]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

It will be easy to understand for contributors and new coming contributors while looking through the project history.

[Conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)

Also, there is an CLI tool available for the conventional commit message:
[commitlint](https://github.com/conventional-changelog/commitlint)

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by rustamwin** [comment]
We can do it. Please participate in a discussion in #4143
