### ISSUE TITLE
Relation decorators: allow to pass string instead of typeFunction

### ISSUE THREAD

**Issue by haschu** [typeorm/typeorm#4190]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

---

To define table relations using decorators, this is the current way:

Photo.ts
```ts
    @ManyToOne(type => User, user => user.photos)
    user: User;
```

User.ts
```ts
    @OneToMany(type => Photo, photo => photo.user)
    photos: Photo[];
```

This works fine on Node.js, but can cause circular dependency issues on the frontend side (e.g. when using Angular CLI). See: #2059 or #1290

We could overcome those issues, if the following would be possible:

Photo.ts
```ts
    @ManyToOne('User', 'photos')
    user: User;
```

User.ts
```ts
    @OneToMany('Photo', 'user')
    photos: Photo[];
```

This should be fairly easy to implement, as it turns out that TypeORM already supports `string` instead of types (e.g. when using `EntitySchema`) - the only thing to do is to adjust the `typeFunction` type of the decorator functions.

@pleerock If that feature would be ok I could post a PR :)

**Comment by haschu** [comment]
PR is submitted.

As an example, the following pattern would now prevent circular dependency issues with `@OneToMany`/`@ManyToOne` (using abstract classes would be more suitable for bigger entities to prevent duplicate code):

IUser.ts
```ts
export interface IUser {

  id: number;

  name: string;

}
``` 

IPhoto.ts
```ts
export interface IPhoto {

  id: number;

  url: string;

}
``` 

User.ts
```ts
@Entity()
export class User implements User {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToMany('Photo', 'user')
  photos: IPhoto[];

}
```

Photo.ts
```ts
@Entity()
export class Photo implements iPhoto {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  url: string;

  @ManyToOne('User', 'photos')
  user: IUser;

}
```

**Comment by jordancue** [comment]
@haschu great work!

**Comment by haschu** [comment]
@jordancue Thank you :) Hope 0.2.18 will be released soon.

**Comment by Michael-Dawkins** [comment]
In my angular app, I have set **"showCircularDependencies": false** in the angular.json to simply ignore the circular dependency messages and it fixed my issues, it looks clean to me because there indeed are cycles in my typeORM models and this is fine.
The only downside I see to this approach is that, sometimes, the circular dep warning can be helpful to detect an actual code smell.

Am I missing something?

What I prefer with this method over using strings is the maintainability aspect, I can still refactor the name of a class and have my IDE propagate the rename from the db down to the frontend.

**Comment by haschu** [comment]
@Michael-Dawkins I guess you don't miss anything :)

> The only downside I see to this approach is that, sometimes, the circular dep warning can be helpful to detect an actual code smell

Beware that circular dependencies can be pretty dangerous, as they lead to null/undefined references that may be hard to debug. That's why I find the warning are overall helpful. 

TypeORM can deal with it, because is forwards the reference using a `typeFunction`. That's btw. the reason you have to write `@OneToMany(type => Something)` instead of `@OneToMany(Something)` - because `Something` can be null/undefined at this time.

But if you by accident introduce another circular dependency, the compiler won't warn you, and debugging can be a hard time.

**Comment by Michael-Dawkins** [comment]
Thank you for the explanation.

It seemed weird to me at first why typeORM does not use `@OneToMany(Something)`, thank you for the insight about the fact it may be undefined if evaluated too early.

**Comment by haschu** [comment]
You're welcome :) 

As you you're using Angular: have a look a [forwardRef](https://angular.io/api/core/forwardRef), it's the exact same use-case.

**Comment by bigLucas** [comment]
Hello everyone, just a little thing, when we work with **typeorm and webpack,** as we use in the **serverless/aws structure,** it's good to try changing the repository method to save your entities, **don't use repository.save(entity)**, because this method waits for an entity fully loaded, which can generate cyclic dependency. 
**An alternative is to use the repository.createQueryBuilder()** that transforms your entity values into string objects, making a normal insert query.

**Comment by notHaiLuu** [comment]
Thanks @haschu , you save my life. Just change like this:

From: `@OneToMany(() => Todo, (todo) => todo.author) `
To: `@OneToMany('Todo', 'author')`

From: `@ManyToOne(() => Author)`
To: `@ManyToOne('Author', 'todos')`

It's resolved circular dependency.
![Screenshot 2020-04-07 at 21 55 15](https://user-images.githubusercontent.com/42777857/78684286-7bb82e00-791a-11ea-841c-4d39ada3ec7f.png)

**Comment by jdnichollsc** [comment]
@notHaiLuu thanks for sharing! I was getting an issue with **Swagger** from a **NestJS** project because that circular dependency
Regards

**Comment by kamranblueeast** [comment]
@haschu, thanks good work, saves my day. :)

**Comment by Valiib** [comment]
I HOPE YOU YOU  fulfill all your desires. I was going crazy. its first time i comment on a github. you are great @haschu

**Comment by DJEDAINI** [comment]
@haschu 

You saved my day, thank you

**Comment by hecmondev** [comment]
@haschu 2021 almost 2022 finding this solution after a lot of searching thank you so much cowboy nice job! 🥇

**Comment by jdnichollsc** [comment]
@JohnTheBeloved try WatermelonDB instead, TypeORM is for Backend side (NodeJS), check my example for React Native here: https://github.com/proyecto26/MyApp

**Comment by HyopeR** [comment]
@JohnTheBeloved Hello. I have the same problem when I define relations using string as suggested. However, I should point out that only in **PRODUCTION** mode.

If I define a relation using string. Initializing the database fails with this error;
`Entity metadata for t#entity was not found.`

If I do relationship definition normally. If I try to save a nested structure using the save method it fails with this error;
`cyclic dependency "u".`

Were you able to find any solution?

**Comment by HyopeR** [comment]
If anyone is still struggling with these issues, check out this link. https://github.com/typeorm/typeorm/issues/4714 

I am using Typeorm with React native. And the solution in the link makes your application run successfully in production mode.

**Comment by LincWong** [comment]
good
