### ISSUE TITLE
Whats the best way to get a descriptor of all the fields in an Entity

### ISSUE THREAD

**Issue by iyobo** [typeorm/typeorm#4192]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

What's the best way to get all the fields in an entity including all the rules for each field? e.g length, validator, etc.

**Comment by iyobo** [comment]
So I have figured out the best way is to check entityMetaData when creating the connection.

```
const connection = await createConnection(config.data.typeORM.default);
connection.entityMetadatas;
```

and then in each EntityMetaData there is `columns` which is an array of ColumnMetaData objects which is the descriptor for each field.

I can see ColumnMetaData.type which tells me what type of field this is...but how can I determine the various validators for the field? i.e isEmail, length, etc?

**Comment by haschu** [comment]
This isn't related to TypeORM as the validators are from [class-validator](https://github.com/typestack/class-validator)

I guess what you're trying to do is (?):
```ts
import { getFromContainer, MetadataStorage } from 'class-validator';

const metadata = getFromContainer(MetadataStorage);
```

**Comment by vlapo** [comment]
I think you answered your question by yourself. But be careful. `entityMetadatas` is not part of typeorm api so it is possible it will be subject of change in future.

Validators are not related to TypeORM.
