### ISSUE TITLE
Postgres ltree extension

### ISSUE THREAD

**Issue by derblitz** [typeorm/typeorm#4193]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

There is an official extension in postgres called ltree. Ltree let's you use the column type "ltree". Currently Typeorm does not support it as it seems. Is there a plan to support it in the future or to get a general (generic) solution for postgres specific extension types?

**Comment by vlapo** [comment]
I dont think we have any way how to implement this without touching typeorm core code. So if you want this functionality you have to fork typeorm code and contribute. You should check `postgis` extension implementation https://github.com/typeorm/typeorm/pull/2423.

**Comment by derblitz** [comment]
Ok thanks. That's a pitty. I thought there may be a generic solution that at least let's you use such types in a way that typeorm doesn't complain about the type - also if it's not 100% supported.

**Comment by fbrbovic** [comment]
I agree, there should be at least some generic way to allow any custom type.  I also need ltree support.

**Comment by NinthAutumn** [comment]
+1

**Comment by jrmacks** [comment]
+1

**Comment by BestNathan** [comment]
+1

**Comment by reececasey** [comment]
+1

**Comment by edubskiy** [comment]
Tested and working. Would be great to see examples in official docs.
