### ISSUE TITLE
ReadOnlyRepository feature

### ISSUE THREAD

**Issue by vanhumbeecka** [typeorm/typeorm#4194]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

It would be nice to have a `Repository` act as a `ReadOnlyRepository`. This could help in implementing clearer CQRS principles. `ReadOnlyRepository`s can only fetch data, making sure you don't accidentaly write to your store when using these. So in essence, a subset of features of the `Repository` in first instance.

This would allow you to structure your code like this for example:
* `BlogWriteService` --> uses `Repository<Blog>`
* `BlogReadService` --> uses `ReadOnlyRepository<Blog>`

**Comment by vlapo** [comment]
I do not think this is really hot topic in typeorm. As workaround you can create your own read-only repository https://typeorm.io/#/custom-repository.

**Comment by vanhumbeecka** [comment]
Ok thanks, I must have skipped over that part.
Looks like this could do the job in theory, both with `AbstractRepository` and the inject-manager-in-constructor way. I'll try this out.

**Comment by anhnam00** [comment]
@vanhumbeecka ViewEntity is What you need, but ViewEntity dont support relation
