### ISSUE TITLE
Docs: many-to-many violates not-null constraint

### ISSUE THREAD

**Issue by haschu** [typeorm/typeorm#4196]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

From the many-to-many docs:

```ts
@Entity()
export class Question {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    title: string;

    @Column()
    text: string;

    @ManyToMany(type => Category)
    @JoinTable()
    categories: Category[];

}
```

`title` and `text` are missing at: 
```ts
const question = new Question();
question.categories = [category1, category2];
await connection.manager.save(question);
```

which violates not-null constraint and throws an error.

I'll submit a PR during next week.

**Comment by vlapo** [comment]
Feel free to contribute :)
