### ISSUE TITLE
Timestamp column support

### ISSUE THREAD

**Issue by paistipoikka** [typeorm/typeorm#42]
Can you please add support for timestamp column inside ColumnTypes.js
This will also need to support precision. 

Cheers

JT

**Comment by paistipoikka** [comment]
UPDATE: I just tried to add it to the ColumnTypes.js file  but the driver wouldn't allow it. Maybe a limitation of the driver....

**Comment by AlexMesser** [comment]
fixed and released in `0.1.0-alpha.29` version
