### ISSUE TITLE
Multiple unique keys when using one to one

### ISSUE THREAD

**Issue by luqezman** [typeorm/typeorm#4200]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi guys, I'm trying to have unique keys with foreign key associated with one of them but I think typeorm is creating different unique keys.

Here is my model file:

```ts
import {
  Column,
  Entity,
  JoinColumn,
  OneToOne,
  PrimaryGeneratedColumn,
  Unique,
} from 'typeorm';

import { BotModel } from './bot.model';

@Entity('intent')
@Unique(['botId', 'name'])
export class IntentModel {
  @PrimaryGeneratedColumn('uuid')
  intentId: string;

  @Column()
  botId: string;

  @OneToOne(() => BotModel, { cascade: true })
  @JoinColumn({
    name: 'botId',
    referencedColumnName: 'botId',
  })
  bot: BotModel;

  @Column({ length: 16 })
  name: string;

  @Column({
    length: 128,
    nullable: true,
  })
  description: string;
}
```

My `create table intent` from mysql:

```mysql
CREATE TABLE `intent` (
  `intentId` varchar(36) NOT NULL,
  `botId` varchar(255) NOT NULL,
  `name` varchar(16) NOT NULL,
  `description` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`intentId`),
  UNIQUE KEY `REL_94de4914fe0a743917de52fe8e` (`botId`),
  UNIQUE KEY `IDX_94de4914fe0a743917de52fe8e` (`botId`),
  UNIQUE KEY `IDX_78750387b2c61fb51adb75b5ab` (`botId`,`name`),
  CONSTRAINT `FK_94de4914fe0a743917de52fe8e7` FOREIGN KEY (`botId`) REFERENCES `bot` (`botId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

When I try to insert different name with id(already inserted) I'm getting this:
```mysql
ER_DUP_ENTRY: Duplicate entry '0b387f8b-d330-4b39-93d2-5637f11001b7' for key 'REL_94de4914fe0a743917de52fe8e'
```

I tried in different ways but no success.

**Comment by vlapo** [comment]
It shouldn't be `ManyToOne` relation? I mean you want allow one `BotModel` to be related with many `IntentModel`.

`OneToOne` is reason of first `UNIQUE KEY 'REL_94de4914fe0a743917de52fe8e' ('botId'),` but I do not understand second one `UNIQUE KEY 'IDX_94de4914fe0a743917de52fe8e' ('botId'),`. It does not appear in my test.

**Comment by luqezman** [comment]
Working :-D

Thanks
