### ISSUE TITLE
[Question] How to REPLACE row in conflict key?

### ISSUE THREAD

**Issue by rsbh** [typeorm/typeorm#4204]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
Please update issue description and say more about your question.

**Comment by rishabh09** [comment]
ActiveAndroid provides REPLACE on Conflict for SQLite

```
@Column(notNull = true,
    unique = true,
    onUniqueConflict = Column.ConflictAction.REPLACE)
    public String name;
```

it will replace the whole row on conflict

**Comment by vschoener** [comment]
I'm looking for this solution, replacing the entire row when a conflict rise. Otherwise, I would have to use a try/ catch and update in the catch block to have my behaviour with a bit of control over it

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
