### ISSUE TITLE
Option to omit/infer entities config

### ISSUE THREAD

**Issue by zen0wu** [typeorm/typeorm#4207]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The context is https://github.com/nestjs/nest/issues/755.

Basically, the issue is loading entities in some cases can cause problems. So it occurred to me if it's possible to let typeorm just set the entities implicitly. 

The idea is because `@Entity` decorator is already run when the entity class is imported (except the case for EntitySchema). TypeORM already has an idea about all the entities. Under the case that all the entities are properly imported, does it make sense to omit the entities settings and just let TypeORM figure it out automatically?

The same can be true for migrations, but I think the issue is migration doesn't have annotation. EntitySchema is tricky, so maybe this option should be opted-in.

Copy from the context, this is basically the same as, first importing all the entities, then set the connection options as
```ts
{
  entities: getMetadataArgsStorage().tables.map(tbl => tbl.target),
  ...
}
```
But it took me a while to figure out this API and I'm also not sure if this is an internal API or not, it certainly doesn't look internal :)

**Comment by haschu** [comment]
Personally, I wouldn't like to see this implemented in TypeORM (it would be a bit too implicit for my taste). What would we do, in case we got multiple connections - pass the connection name to each `@Entity` declaration?

I think you could easily workaround this (as you already did :)):

E.g.:

For nest.js
```ts
export class ImplicitTypeOrmModule extends TypeOrmModule {
  static async forRoot(options) {
    (options.entities as any) = getMetadataArgsStorage().tables.map(tbl => tbl.target);
    return super.forRoot(options);
  }
}
```

Or for TypeORM in general
```ts
export async function createImplicitConnection(
  options: ConnectionOptions
): Promise<Connection> {
  (options as any).entities = getMetadataArgsStorage().tables.map(
    tbl => tbl.target
  );
  return createConnection(options);
}
```

And if you don't want to rely on `getMetadataArgsStorage`, you could write your own `Entity` decorator:

```ts
import {Entity as _Entity} from 'typorm';
 
export function Entity(
  nameOrOptions?: string|EntityOptions, 
  maybeOptions?: EntityOptions
): Function {
  return function (target: Function) {
    yourGlobalEntityStorage.add(target);
    _Entity(nameOrOptions, maybeOptions)(target);
  }
}
```

**Comment by zenozen** [comment]
Sure. But it's ok to call API like `getMetadataArgsStorage`, right? Like the name didn't suggest clearly if it's intended to be called from outside.

The custom Entity decorator approach looks tasty :D

**Comment by haschu** [comment]
> But it's ok to call API like getMetadataArgsStorage, right? Like the name didn't suggest clearly if it's intended to be called from outside.

I'm not the maintainer of TypeORM, so I can't tell - for me it also doesn't sounds like a public api to be honest :P

**Comment by vlapo** [comment]
No, `getMetadataArgsStorage` is definitely not a public API :) But I think this is not so bad idea. We should still support `entities` option (because of multiple connection feature) but in case `entities` option is not defined we should use our internal API and load all entities.

Right now I dont see any blocking point about this functionality. Btw there is proposal with quite similar change https://github.com/typeorm/typeorm/issues/2358.

**Comment by haschu** [comment]
IMHO this feature could potentially bring in a lot of confusion when entities will be loaded completely implicit by some kind of magic - and that per default.

Users might forget about the "entities" property as everything works automatically, and by the time they decide to use multiple connection, things might getting ugly...

How about something like:

```ts
createConnection({
  // ...
  loadEntitiesFromMetadata: true
})
```

Or:
```ts
createConnection({
  name: "myConnection"
  entities: [...]
})

// And for the entity definition:

@Entity({
  loadInConnection: "myConnection"
})
export class MyEntity {
  //...
}
```

Personally, I would go for the second approach. This would still fulfill the use case but wouldn't be too implicit und not the default way - plus it would work with multiple connections :)

**Comment by vlapo** [comment]
Sure you are right but I think the less experienced developers search exactly this kind of "magic". They want to define entity, create connection with as less options as possible and BUM it works. After that they feels like a magicians and want more :D We should brings this kind of experience in first place.

On the other hand there are more experienced developers and for them we have more complex options (of course it should be properly documented - this is little bit problem in typeorm now).

I like `loadEntitiesFromMetadata` in connection options more. It is simple and developer have the feature under full control.

`loadInConnection` in entity options is always interesting but I dont know if I want to pass the connection name into every `@Entity`.

Lets invite @Kononnable and @pleerock into discussion

**Comment by haschu** [comment]
> Sure you are right but I think the less experienced developers search exactly this kind of "magic". They want to define entity, create connection with as less options as possible and BUM it works. After that they feels like a magicians and want more :D We should brings this kind of experience in first place.

Yeah... that's definitely a good argument :) I also like feeling like a magician but I also like to know what I'm doing :P

**Comment by Kononnable** [comment]
Tbh. I'm not a fan. The idea of registering entities based on decorator is nice, but I don't like using global objects in general. A lot of time will pass till we're able to not use global objects in typeorm at all, but such functionality might just be a blocker for that(yet we might implement it and remove it in the future leaving unsatisfied users).

In general, are we certain that entity decorators will always run before `createConnection`? We have to consider all of the module systems etc. If there is at least one case in which entities won't be registered we'll get ourselves even a bigger problem. Troubleshooting why entity wasn't registered would be really painful. People will come for help and 'just put it in entities in connection options` won't be an answer. Folks will use it because doing it automagically means one less thing for them to worry about(unless there is a bug).

**Comment by imnotjames** [comment]
I think global entities & implicit-ness here would lead to more confusion and problems.  We already have a lot of issues with the magic behind `ormconfig` failing & causing issues.

However, if this was provided by a framework with FAR MORE RIGID ways of defining entities.. sure.  Just not for TypeORM.

**Comment by imnotjames** [comment]
Also given that it's been a year since discussion on this has happened & not many folks have been clamoring for it via :+1: to the initial post I'm gonna close this out.
