### ISSUE TITLE
 Foreign key is saved as null on entity save

### ISSUE THREAD

**Issue by artem-sydorenko** [typeorm/typeorm#4208]
**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**Steps to reproduce or a small repository showing the problem:**
```ts
import { PersonEntity } from '../../person/person.entity';

@Entity('some-table')
export class SomeEntity {

    @PrimaryGeneratedColumn('uuid')
    id: string;
  
    @OneToOne(type => PersonEntity, {
        onDelete: 'CASCADE',
    })
    @JoinColumn({name: 'person_id'})
    person: PersonEntity;

    @RelationId((someEntity: SomeEntity) => someEntity.person)
    person_id: string;
} 

// in service file
await this.someEntity.save({person_id: 'id_11232132142414545'});
```
The person_id every time is saved as null. 
Is there something wrong with @RelationId in my Entity?

Thanks.

**Comment by pbirsinger** [comment]
What's the solution here? Having same issue

**Comment by artem-sydorenko** [comment]
> What's the solution here? Having same issue

I removed @RelationId decorator from my entity.
Then you can save new row with "person" property:
`await this.someEntity.save({person: 'id_11232132142414545'});`

**Comment by pbirsinger** [comment]
how does that pass the typechecker for you? Typescript has person as a whole entity, and complains if I do that saying i'm saving a string

**Comment by satya-tradehero** [comment]
What's the solution. I'm still facing this issue
