### ISSUE TITLE
Query builder join as entity

### ISSUE THREAD

**Issue by nevodavid** [typeorm/typeorm#421]
Hi,
when I'm using the ORM to fetch some entity it's coming back as model, but the join comes back as a normal object(not mapped to model), is there any way to fix it? or I have to deserialize it in the getter functions.

**Comment by pleerock** [comment]
if you do joinAndSelect a relation it should come you mapped to your entity. Can you provide a come example?

**Comment by pleerock** [comment]
@nevodavid any news on this issue?

**Comment by pleerock** [comment]
closing it as no answer from op. Please let me know if you still have questions/issues.
