### ISSUE TITLE
Why are Repositories are more convenient to use than EntityManagers?

### ISSUE THREAD

**Issue by ben-z** [typeorm/typeorm#4215]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Qustion**

In README.md, it says "[When you deal with entities a lot, Repositories are more convenient to use than EntityManagers](https://github.com/typeorm/typeorm/blob/6fd579301ea7efb780e34bd806b3e2299397f30e/README.md#L688)". From reading the README, the [doc on `EntityManager`](https://github.com/typeorm/typeorm/blob/6fd579301ea7efb780e34bd806b3e2299397f30e/docs/working-with-entity-manager.md) and the [doc on `Repository`](https://github.com/typeorm/typeorm/blob/6fd579301ea7efb780e34bd806b3e2299397f30e/docs/working-with-repository.md), I can't tell the difference between them. Can we add a statement in README to clarify how Repositories are more convenient to use than EntityManagers?

**Comment by haschu** [comment]
Using `EntityManager`, you'll always have to pass the entity class:

```ts
await connection.manager.find(Photo, someFindOptions);
await connection.manager.find(Photo, someOtherFindOptions);
await connection.manager.find(Photo, oneMoreFindOptions);
```

While using `Repository` you'll only have to pass it once, as the repository stores the entity class inside:
```ts
const photoRepository = connection.getRepository(Photo);
```

And now you can do stuff with it, without referencing `Photo` all the time:
```ts
await photoRepository.find(someFindOptions);
await photoRepository.find(someOtherFindOptions);
await photoRepository.find(oneMoreFindOptions);
```

E.g. you could outsource `photoRepository` into a separate file, from which you'll export it along your app. So you won't have to import `Photo` all the time (imagine what would happen if you'd rename `Photo` to `Photography` for whatever reason - happy refactoring :))

Also, you can extend your repository's functionality with the "custom repository" feature.

**Comment by ben-z** [comment]
Ah, makes sense. Thanks!
