### ISSUE TITLE
class-transformer-shim: support metadata reflection

### ISSUE THREAD

**Issue by haschu** [typeorm/typeorm#4219]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

---

TypeORM provides a [class-transformer-shim](https://github.com/typeorm/typeorm/blob/master/extra/typeorm-class-transformer-shim.js), which is awesome for browser/fronend application usage.

However, the transformation of `Date` types for example - or any other type, that isn't passed via a decorator and a typeFunction - requires additional `class-transformer` code:

```ts
@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    url: string;
    
    // Works fine => class-transformer creates User objects :)
    @ManyToOne(type => User, user => user.photos)
    user: User;
    
    // No Date object, class-transformer leaves that as string :(
    @CreateDateColumn()
    createdAt: Date;

}
```

To make it work, we need to write:

```ts
import { Type } from 'class-transformer';

//...

@Type(() => Date)
@CreateDateColumn()
createdAt: Date;
```

which I find annoying, especially when sharing entities between backend and frontend. One would also have to import the `class-transformer` library into his backend, but actually it's only used on the frontend side. Plus of course, it saves us lots of code lines.

We could solve this, if [typeorm-class-transformer-shim.js](https://github.com/typeorm/typeorm/blob/master/extra/typeorm-class-transformer-shim.js) would support metadata reflection. 
If the client imports "reflect-metadata", we could use `design:type` and automatically pass it to the `@Type` decorator of class-transformer, as we already do with typeFunctions.

PR is on the way.

**Comment by Michael-Dawkins** [comment]
Huge thanks for bringing this up, I am currently "reviving" all dates individually and manually on the front end and forgetting this is often a source of bugs for us.

I am not familiar with the use of reflect-metadata, have you managed to implement a bridge from typeORM's date annotation to class-transformer ?

**Comment by haschu** [comment]
@Michael-Dawkins yes, it's already included in the latest release :)

You have to include typeorm-class-transformer-shim.js into your tsconfig.json `path` section:

```json
    "paths": {
      "typeorm": [ "node_modules/typeorm/extra/typeorm-class-transformer-shim.js" ]
    }
```

**Comment by Michael-Dawkins** [comment]
You just made my day.

I've been thinking for months it would be nice to simply use the annotations already present from using TypeORM or heck, even typescript.
Now I can remove so much low value code from our codebase .

By reading class-transformer's doc again today, I also discovered "enableImplicitConversion"'s new option of class-transformer which is a nice addition.
