### ISSUE TITLE
Question: Insert using QueryBuilder and JOIN

### ISSUE THREAD

**Issue by TomerSalton** [typeorm/typeorm#4224]
**Issue type:**
[V] question

**Database system/driver:**
[V] `postgres`

**TypeORM version:**
[V] `latest`

**Steps to reproduce or a small repository showing the problem:**
Hello,
My question is regarding using an Insert QueryBuilder with inner-join in 1 transaction.

Let me give a little background:
I'm having 3 tables: tbl_a, tbl_b, and tbl_c;
tbl_c has a foreign key to tbl_b (b_id), and tbl_b has a foreign key to tbl_a (a_id).
In other words, the relations are: a has one-to-many with b, and b has one-to-many with c.

I'm getting the following request: POST a/a_id/b/b_id/c (with $request_body of c)
My purpose is to create c that is related to b, which is not difficult.
The challenge I'm running into is to validate that there is b that is related to the a_id that is specified. 

I could do that using 2 transactions: 1 with inner-join to get the final object (b), and then another one for creating a new object related to the specified b.
Is there any other option to create C within one transaction?

Thanks for your help,
Tomer Salton.

**Comment by haschu** [comment]
I would go with the "2 transactions" approach (if I understand you correctly).

If the user requests "3/a_id/5/b_id/c" and 5(b) isn't related to 3 (a), you certainly want to throw an error to the user, which you can do when your first result is empty.

**Comment by TomerSalton** [comment]
@haschu 
Thank you for your quick reply.

Let me just verify we are on the same page;
The query I'm trying to achieve here is:

`insert into c (name, "bId") values('c_name',(
select b.id from a inner join b on a.id = 3 and b."aId"=a.id and b.id=5)
);`

I believe that an error will be thrown if the result of the select is empty and b_id field will be set to not_null.

**Comment by haschu** [comment]
Yes, you can do this. Check out the [subqueries part](https://typeorm.io/#/select-query-builder/using-subqueries) of the QueryBuilder docs.

**Comment by TomerSalton** [comment]
There's no documentation regarding subquery in insert though;
Are you familiar with it?

**Comment by haschu** [comment]
You can write your subquery with the "functional style" approach as described [here]https://typeorm.io/#/insert-query-builder/raw-sql-support) in the docs :)

**Comment by haschu** [comment]
You may also have a look at #1178

**Comment by TomerSalton** [comment]
Thank you for your help!
