### ISSUE TITLE
Multiple ManyToOne

### ISSUE THREAD

**Issue by cfkxzsat** [typeorm/typeorm#4225]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an application that each building will have several comments(barrages) post by user.
So here's my User, Barrage, Building entity code.
```ts
@Entity()
export default class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({unique: true})
    openid: string;

    @OneToMany((type: any) => Barrage, (barrage: Barrage) => barrage.postUser)
    postBarrages: Barrage[];

    // @ManyToMany((type: any) => Barrage, (barrage: Barrage) => barrage.likedUsers)
    // @JoinTable()
    // likedBarrages: Barrage[];
}

@Entity()
export default class Building {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({unique: true})
    name: string;

    @Column()
    introduction_text: string

    @Column()
    image_url: string

    @OneToMany((type: any) => Barrage, (barrage: Barrage) => barrage.building)
    barrages: Barrage[];
}

@Entity()
export default class Barrage {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({unique: true})
    text: string;

    @ManyToOne((type: any) => Building, (building: Building) => building.barrages)
    building: Building;

    @ManyToOne((type: any) => User, (user: User) => user.postBarrages)
    postUser: User;

    // @ManyToMany((type: any) => User, (user: User) => user.likedBarrages)
    // likedUsers: User[];

}
```

And I got Error: Entity metadata for User#postBarrages was not found. Check if you specified a correct entity object and if it's connected in the connection options.

What I'm missing? Or Am I design the model wrong?

**Comment by haschu** [comment]
I checked you example and it works for me. Can you provide a minimal repository?

Did you pass all your entities to `createConnection(...)`?

**Comment by cfkxzsat** [comment]
@haschu I have index.ts in /entity folder which export all my entities and in ormconfig.ts my entities property is 'entity/index.ts'. I solved this problem by delete index.ts and include all separate entities files which finally  in ormconfig.ts the entities property's value is 'entity/*.ts. But honestly, I don't know why I stumbled into the problem.
