### ISSUE TITLE
Many to Many, use existing values for relation

### ISSUE THREAD

**Issue by w2kzzz** [typeorm/typeorm#4229]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

i'm trying to put together a User/Role Relation so i'm doing a Many to Many however i want to have an existing list of roles and from that make those relations, my issue is that with what i'm doing it seems that is trying to insert the role each time generating issues with duplicates.

Code.

User entity:

``` ts 
import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  ManyToMany,
  JoinTable,
} from 'typeorm';
import { Role } from './role.entity';

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ length: 50, unique: true })
  username: string;

  @Column({ length: 500 })
  email: string;

  @Column({ length: 100, nullable: true })
  password: string | undefined;

  @Column({ length: 100, nullable: true })
  passwordHash: string | undefined;

  @ManyToMany(type => Role, { cascade: ['insert'] })
  @JoinTable({
    name: 'userRoles', // table name for the junction table of this relation
    joinColumn: {
      name: 'userId',
      referencedColumnName: 'id',
    },
    inverseJoinColumn: {
      name: 'roleId',
      referencedColumnName: 'id',
    },
  })
  roles: Role[];
}

```

Role entity:

``` ts
import { Entity, Column, PrimaryGeneratedColumn, ManyToMany } from 'typeorm';

@Entity()
export class Role {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ length: 50, unique: true })
  name: string;
}

```

User Service

``` ts
import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { User } from '../_entities/user.entity';
import * as bcrypt from 'bcrypt';

@Injectable()
export class UserService {
  private saltRounds = 10;

  constructor(
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,
  ) {}

  async getUsers(): Promise<User[]> {
    return await this.userRepository.find();
  }

  async getUserByUsername(username: string): Promise<User> {
    return (await this.userRepository.find({ username }))[0];
  }

  async createUser(user: User): Promise<User> {
    user.passwordHash = await this.getHash(user.password);

    // clear password as we don't persist passwords
    user.password = undefined;
    // tslint:disable-next-line: no-console
    console.log('User to dave:', user);

    return this.userRepository.save(user);
  }

  async getHash(password: string | undefined): Promise<string> {
    return bcrypt.hash(password, this.saltRounds);
  }

  async compareHash(
    password: string | undefined,
    hash: string | undefined,
  ): Promise<boolean> {
    return bcrypt.compare(password, hash);
  }
}

```

i'm testing with postman passing the proper data in the body so when i have let's say a list of roles

1. Admin
2. User

i want the relation to be for instance userId = 1 roleId = 1, userId = 1, roleId = 2 if the user is the 1st and it have both roles, but if i want to add another user with the same roles it will say that Admin and User already exists in the roles table because is trying to insert them.

thanks in advance for the help.

**Comment by vlapo** [comment]
Could you please post some short example of code? I mean omit HTTP/postman part and write short example using typeorm functions and entities only. It is really hard for me to understand what do you want to do :)
