### ISSUE TITLE
Add number with length

### ISSUE THREAD

**Issue by victorblq** [typeorm/typeorm#4231]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
@Column({name: "quote_number"})
quoteNumber: number;
```
If I put a `length` in that `@Column` I receive an error because `ColumType` "number|decimal|int|numeric" are not present in the `ColumnType.WithLengthColumnType`

**Expected behavior**
```ts
@Column({name: "quote_number", type: "numeric", length: 6})
quoteNumber: number;
```
Generates a NUMERIC(6) column at the database. 
I search how to generate number columns with length but no success.

**Comment by vlapo** [comment]
Dont know if I understand properly your question. But `number` data type does not exist in postgres. And if you mean `numeric`, right syntax is `NUMERIC(precision, scale)` so you have to set `precision` or `scale` in `@Column` decorator not a `length`.

**Comment by victorblq** [comment]
@vlapo with precision and scale I make it the way I wanted, thanks.

**Comment by vlapo** [comment]
You are welcome :)
