### ISSUE TITLE
Use entities defined in external package

### ISSUE THREAD

**Issue by lukejagodzinski** [typeorm/typeorm#4238]
**Issue type:**

[x] question

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `latest`

Hi, I have an app where I'm creating connection in the following way:

```ts
import { entities } from "@mypackage/entities";

(async function() {
  const connectionOptionsReader = new TypeORM.ConnectionOptionsReader();
  const connectionOptions = (await connectionOptionsReader.all())[0];
  connectionOptions.entities.push(...entities);
  await TypeORM.createConnection(connectionOptions);

  /* ... */
})();
```

As you can see, I'm loading connectionOptions from config file (that part works properly). And later I'm adding entities from the `@mypackage/models` to the `connectionOptions.entities` list. I've checked the connectionOptions and it looks good. However, when I try to load something from the database I get the `Context creation failed: No repository for \"User\" was found. Looks like this entity is not registered in current \"default\" connection?` error.

Now, going to the package. It's pretty straightforward.

```ts
import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity({ name: "users" })
class User {
  @PrimaryGeneratedColumn({ type: "bigint" })
  readonly id: number;

  @Column({
    name: "first_name",
    type: "character varying",
    length: 50
  })
  firstName: string;

  @Column({
    name: "last_name",
    type: "character varying",
    length: 50
  })
  lastName: string;
}

const entities = [User];

export { entities };
```

I'm building this package with TS. Everything is built properly. I've read in some issue regarding Nest that this kind of operation is possible. But I'm probably missing something. Could you help? I haven't found anything in docs

**Comment by lukejagodzinski** [comment]
Ok sorry, my bad. I've solve the problem. It appears that I was using the `getRepository` not with the `User` class coming from the `@mypackage/entities` but rather with the class that extends it:

```ts
import { User as UserBase } from "@mypackage/entities";

class User extends UserBase { /* ... */ }

const repository = getRepository(User);
// And should do
const repository = getRepository(UserBase);
```

Leaving it here for posterity. Maybe someone will have similar problem.

**Comment by tdnghia98** [comment]
Hi @lukejagodzinski ,
Do you use nestjs or only node? I currently have an issue with importing external entities, I tried to create a package at @app/common with all my entities decorated with type-orm, then sym link this package to two other packages using lerna. The issue was that when I tried to use the repository in the other packages by importing the class from @app/common, I got the "No repository for <Entity name> was found.". Would you mind sharing the architecture of your application please?
Thanks a lot,

**Comment by abrar30** [comment]
@tdnghia98  , hi man  i am having same kind a problem , is there a solution ! 
I tested as below : 
works 
```
 entities: [
      'src/modules/**/*Entity.ts',
       Test,   // directly import entity from common-node
    ],
```
 Does not work 
```
 entities: [
      'src/modules/**/*Entity.ts',
      '../../common-node/src/modules/**/*Entity.ts',
    ],
```

Thanks

**Comment by pavel-luhin** [comment]
@tdnghia98 hi man, did you find the solution? I have custom abstract repository in my common module and I got the same error

**Comment by bnymn** [comment]
Any solutions?

**Comment by kamranblueeast** [comment]
Hi @lukejagodzinski,
Hope you are doing well, 
import { User as UserBase } from "@mypackage/entities";
How did you manage this "@mypackage/entities" was it an npm package?
And in the package you just export entities and not repositories.

**Comment by Hifounder** [comment]
> You guys can check this solution proposal: https://stackoverflow.com/questions/54110369/how-use-external-entities-in-nestjs-project-with-typeorm?rq=1

use for typeORM CLI migrate and follow your step, but my entity use for relation with other entity then throw error code.
```
> npx ts-node ./node_modules/typeorm/cli.js schema:sync -f ./ormconfig.ts

miss the TypeORMError: Entity metadata for District#county was not found.
```
how can i fix in  external package
