### ISSUE TITLE
Dynamic Table Name for entity at runtime

### ISSUE THREAD

**Issue by qmphan** [typeorm/typeorm#4245]
**Issue type:**
[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

Hello,

I am trying to migrate a PHP project to Nodejs and from Doctrine to TypeORM. I am currently stuck at setting dynamic table name for query.

We have many big table and we use table partition to keep table size relatively small so querying them won't take too much time (cf https://www.postgresql.org/docs/10/ddl-partitioning.html)

For example, the table UserLog is partitioned by month. So in 2019 I have the following tables:
user_log_201901
user_log_201902
user_log_201903
...

I am looking to achieve something like this:
```typescript
class UserLog {...};

// Select
const originalRepo = getRepository(UserLog);
const repo201903 = originalRepo.cloneWithMetaData( { tableName: 'user_log_201903'});

const rows = await repo201903.find(); // Get all rows from user_log_201903 table

// Insertion
const newLog = new UserLog();
const repo201906 = originalRepo.cloneWithMetaData( { tableName: 'user_log_201906'});
repo201906.save(newLog);
```

Currently I can do it with Doctrine like this (not ideal but it works):
$em
  ->getClassMetadata('MyApp\MyBundle\Entity\UserLog')
  ->setTableName('user_log_201906');

I am writing this as feature request as I cannot find a way to do it with TypeORM. Table partitioning is an important feature for any enterprise DBM so having support for it would help many developers.

(You can use trigger/rules at DBM level to redirect query to partition table but when there are lots of table, inserting to the main table make a lot of overhead).

Thank you for your consideration.

**Comment by vlapo** [comment]
I have not tried it before. But maybe using `EntitySchema` could resolve your issue. https://typeorm.io/#/separating-entity-definition

**Comment by qmphan** [comment]
It does seem to be the solution. Let me experiment with that. Thank you for the hint @vlapo

**Comment by vlapo** [comment]
Let me know if it helped ;-)

**Comment by ronniegong** [comment]
@qmphan i'm afraid EntitySchema couldn't help

**Comment by Kononnable** [comment]
What about something like that? 
```typescript
function prepareEntityName() {
    return "name";
}
@Entity({ name: prepareEntityName()})
export class Product {

    @PrimaryGeneratedColumn()
    id: number;
...
}
```

You could alternatively do it on db side of things - always save to the same db table and once a month change name of such table(add partial date) and make a new(empty) one in its place.

**Comment by imnotjames** [comment]
Hope this answered your question, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by GMCoder** [comment]
> It does seem to be the solution. Let me experiment with that. Thank you for the hint @vlapo

I have the same problem as you, can you tell me your solution

**Comment by Juantrix123** [comment]
@GMCoder You can try something like this
const repository = getConnection().getRepository(User)
repository.metadata.tablePath = 'new table name'

**Comment by avishwakarma** [comment]
I was also struggling with the same issue and here is my hack

Create an Entity same as your dynamic collection

```
@Entity()
export class Sample {
 ...
}
```

Add this entity to your connection.

```
const connection: Connection = await createConnection({
   ...
    entities: [Sample]
});
```

Use the Sample repository and change tableName before making a query

```
const repository = getRepository(Sample);
repository.metadata.tableName = "dynamic";

const data = await repository.find()' // return results from the dynamic collection instead of sample
```

**Comment by linhx** [comment]
https://gist.github.com/linhx/e5cce0b941546557d7e1625923b7f0c2
I created a few lines code that allow to dynamic table name. It seem to work well but I'm not sure if there is anything wrong.
Hope the authors could verify it.

**Comment by jrista** [comment]
I've recently run into a use case where I need dynamic table names for a collection of entities. We were originally storing the data for these in a single set of tables, however due to the nature of the process, its not exactly the best solution. We wanted to switch to creating tables dynamically for each "instance" of a process that needs to store certain data...then we realized that TypeORM statically maps the table to the entity.

Would be very useful to have a way to dynamically, on-demand (i.e. at the moment you query/CUD), optionally specify an alternative table name...

Maybe just in the standard repository methods? As part of an options object?

**Comment by xmsz** [comment]
any update?

**Comment by codetestmg** [comment]
any update? Even i have similar scenario

**Comment by codetestmg** [comment]
> 

Hi your solution does not work as expected for me. any think missing or changed recently

**Comment by cod3kid** [comment]
> 

    instead of `tableName` use `tablePath`
`    repository.metadata.tablePath = `${subdomain}_users`;
`

**Comment by cod3kid** [comment]
@codetestmg

**Comment by maickelbr** [comment]
I have the impression that sequelise solves this

**Comment by Ginden** [comment]
I think this is solvable with dynamic entity creation.

```ts

export class UserLog {
...
}

export const userLogEntityClasses: Class<UserLog> = [];

for(const year of range(2010, (new Date).getFullYear() + 1) {
   for (const month of range(1, 12)) {
      class UserLogPerMonth extends UserLog {

      }
      // Define name of class to improve debugging
      Object.defineProperty(UserPerLogMonth, 'name', {value: `UserLog_${year}_${month}`});
      Entity({name: `userlog_${month}_${year}`, synchronize: false})(UserLogPerMonth); // Manually decorate entity with @Entity decorator
   }
}
```

You can add function to get proper entity class by year/month.

And in DataSource/Connection options:

```ts
createConnection({
...
entities: [...userLogEntityClasses],
...
})
```

**Comment by wesleyfebarretos** [comment]
I found a way to effiecent to do that in typeorm 2024 cause getRepository is deprecated. 

const repository = dataSource.createQueryBuilder().connection.getRepository<Entity>(Entity);
repository.metadata.tablePath = `${scheme}.${partition_table_name}`

await repository.find() // Like a normal entity

if your table is in public scheme, u dont need the scheme identifier.
