### ISSUE TITLE
Grand lack of documentation

### ISSUE THREAD

**Issue by twothe** [typeorm/typeorm#4246]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am currently trying to use a [tree repository](https://typeorm.io/#/tree-entities), however the grand lack of documentation on most features makes this task much harder than it should be.

There is no documentation on how to set any parameters like left and right columns on tree, the adjacent tree is not functional, the examples cover only the absolute basic situation, there is no specification on how to set ManyToOne columns, and so on...

An API is only as good as it's documentation, and TypeORM is really lacking here.

**Comment by vlapo** [comment]
We all agree with this statement. But we do not have as much free time as we want for `typeorm`. We are still looking for good people to help with documentation, PRs/architecture and improvements. Feel free to submit issue with proposal, PR or just contact someone on slack channel and ask what is needed :)
