### ISSUE TITLE
"RegExp too big" error

### ISSUE THREAD

**Issue by SirNiggo** [typeorm/typeorm#4247]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Repository to reproduce the error:
https://github.com/NicoEnking/typeorm-error

**Comment by NicoEnking** [comment]
It would be nice to add a more precise error message (and catch the exception) if relations get too big. Is there any way to get around this besides not selecting big relations from db?

**Comment by vlapo** [comment]
Could you please provide your error message/stack?

**Comment by NicoEnking** [comment]
Hello vlapo,

you can just install the repo I provided in the issue and run it. The error is extremely big because it prints the whole RegExp into the console.

I can provide the error to you later if you want to but do currently not have access to my computer.

**Comment by NicoEnking** [comment]
Please look at the error log here @vlapo :
https://github.com/NicoEnking/typeorm-error/blob/master/error.log

**Comment by vlapo** [comment]
Checked your repository and found this issue is resolved in `@next` branch. There are some changes in relation area. Please use `@next` version in your project :)

**Comment by NicoEnking** [comment]
Thanks. I'll give it a try later on!
