### ISSUE TITLE
typeorm delete entity and child entity

### ISSUE THREAD

**Issue by joelPangop** [typeorm/typeorm#4249]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

this is my code:
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  OneToMany,
  ManyToOne,
  JoinColumn,
  OneToOne,
  Index,
  BaseEntity,
  ManyToMany,
  JoinTable,
  TreeChildren
} from "typeorm";
import { Formation } from "./formation";
import { Diplome } from "./diplome";
import { TelephoneEmploye } from "./telephoneEmploye";   
import { Adresse } from "./Adresse";
import { Projet } from "./projet";

@Entity("employe")
export class Employe extends BaseEntity{
  @PrimaryGeneratedColumn()
  id: number;
  @Column()
  nom: string;
  @Column()
  prenom: string;
  @Column()
  role: string;
  @Column()
  courriel: string;

  @OneToMany(
    () => TelephoneEmploye,
    telephoneEmploye => telephoneEmploye.employe,
    { nullable: true, eager: true, onDelete:'CASCADE', onUpdate:'CASCADE', cascade:["insert", "update", "remove"] }
  )
  telephoneEmploye: TelephoneEmploye[];
  
  
  @Index()
  @OneToOne(() => Adresse, { nullable: true, onDelete:'CASCADE', onUpdate:'CASCADE', cascade:["insert", "update", "remove"] })
  @JoinColumn({name:'adresseId'})
  adresse: Adresse;

  @ManyToMany(()=>Projet, projet=>projet.employes)
  @JoinTable({name:"employe_projet"})
  projets: Projet[];
}

I am trying to delete the employe. i can actually update, add in cascade the adresse and the TelephoneEmploye entities but i have this error:

 message:
   'ER_BAD_FIELD_ERROR: Unknown column \'employeId\' in \'where clause\'',
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'employeId\' in \'where clause\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'DELETE FROM `employe` WHERE `id` = 33 AND `nom` = \'tchomeni\' AND `prenom` = \'joel\' AND `role` = \'dev\' AND `courriel` = \'joelpangop@gmail.com\' AND `adresseId` = 25 AND employeId = NULL',
  name: 'QueryFailedError',
  query:
   'DELETE FROM `employe` WHERE `id` = ? AND `nom` = ? AND `prenom` = ? AND `role` = ? AND `courriel` = ? AND `adresseId` = ? AND employeId = ?',
  parameters:
   [ 33,
     'tchomeni',
     'joel',
     'dev',
     'joelpangop@gmail.com',
     25,
     undefined ] }

**Comment by vlapo** [comment]
Please update your issue properly and use markdown to code and output formation.

**Comment by Kononnable** [comment]
Closing as no response from the author.
