### ISSUE TITLE
typeorm adds sorting by id ASC automatically

### ISSUE THREAD

**Issue by judos** [typeorm/typeorm#4251]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next` (0.3.0-alpha.23)
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

We have some complex query we build using the querybuilder. The important part is the sorting by scoreTotal:
```
let query = this.targetService.createQueryWithJoinedEntities();
    query = this.targetService.filterQuery(query, type, source, interesting);
    query = this.targetService.filterQueryFreeText(query, filterText);
    query = query.orderBy('target.scoreTotal', 'DESC');
    return this.targetService.toPaginateObject(page, limit, (pageClean, limitClean) => {
      query = query.skip(pageClean * limitClean).take(limitClean);
      return query.getManyAndCount();
    });
```

This generates the following sql query & logs:
```
query is slow: SELECT DISTINCT `distinctAlias`.`target_id` as "ids_target_id", `distinctAlias`.`target_scoreTotal` FROM (SELECT ... FROM `target` `target` LEFT JOIN ... WHERE `target`.`filteredOut` = false AND `target`.`type` = ?) `distinctAlias` ORDER BY `distinctAlias`.`target_scoreTotal` DESC, `target_id` ASC LIMIT 10 -- PARAMETERS: ["Person"]
execution time: 276
```

As you can see the query is very slow (276ms). This happens because we have an index only on the scoreTotal. When I execute the same sql query without the target_id ordering the query is fast (<1ms).
So the question is: Why/Where does typeorm add the sorting by entity id? As you can see above when I create the SelectQueryBuilder I only want to sort by scoreTotal....

Thanks for your help!

**Comment by vlapo** [comment]
Could you please provide minimal example with simple entities and using only typeorm? Maybe it will be help us find where problem is :) Also if you have some free time feel free check typeorm code and find root problem by yourself. We are looking for new contributors every day.

**Comment by judos** [comment]
Unfortunately I didn't find the time to reproduce this properly.
We fixed it in our project by moving to mysql8 with better indices on the tables. So the performence is fine again.

**Comment by gpoplee122** [comment]
const queryBuilder = this.employeeRepository
      .createQueryBuilder('employee')
      .leftJoinAndSelect(
        'employee.gardeningProfiles',
        'gardeningProfile',
        'gardeningProfile.key = :year',
        { year }
      )
      .orderBy('gardeningProfile.total_water_drops', 'DESC')
      .skip(skip)
      .take(pageSize);
      
      
      and this is query in console:
      
      query: SELECT DISTINCT "distinctAlias"."employee_id" AS "ids_employee_id", "distinctAlias"."gardeningProfile_total_water_drops" FROM (SELECT "employee"."id" AS "employee_id", "employee"."createdAt" AS "employee_createdAt", "employee"."updatedAt" AS "employee_updatedAt", "employee"."name" AS "employee_name", "employee"."externalId" AS "employee_externalId", "employee"."email" AS "employee_email", "employee"."phone" AS "employee_phone", "employee"."employee_code" AS "employee_employee_code", "employee"."department" AS "employee_department", "employee"."status" AS "employee_status", "employee"."facebook_url" AS "employee_facebook_url", "employee"."linkedin_url" AS "employee_linkedin_url", "employee"."avatar" AS "employee_avatar", "employee"."position" AS "employee_position", "employee"."dob" AS "employee_dob", "employee"."sessionId" AS "employee_sessionId", "employee"."employee_type" AS "employee_employee_type", "employee"."employee_type_name" AS "employee_employee_type_name", "employee"."is_leader" AS "employee_is_leader", "employee"."companyId" AS "employee_companyId", "gardeningProfile"."id" AS "gardeningProfile_id", "gardeningProfile"."createdAt" AS "gardeningProfile_createdAt", "gardeningProfile"."updatedAt" AS "gardeningProfile_updatedAt", "gardeningProfile"."key" AS "gardeningProfile_key", "gardeningProfile"."total_plants" AS "gardeningProfile_total_plants", "gardeningProfile"."total_water_drops" AS "gardeningProfile_total_water_drops", "gardeningProfile"."total_completed_plants" AS "gardeningProfile_total_completed_plants", "gardeningProfile"."total_dead_plants" AS "gardeningProfile_total_dead_plants", "gardeningProfile"."total_friend_plants_watered" AS "gardeningProfile_total_friend_plants_watered", "gardeningProfile"."total_caught_bugs" AS "gardeningProfile_total_caught_bugs", "gardeningProfile"."total_caught_friend_bugs" AS "gardeningProfile_total_caught_friend_bugs", "gardeningProfile"."total_killed_bugs" AS "gardeningProfile_total_killed_bugs", "gardeningProfile"."total_released_bugs" AS "gardeningProfile_total_released_bugs", "gardeningProfile"."playerId" AS "gardeningProfile_playerId" FROM "employee" "employee" LEFT JOIN "gardening_player_profile" "gardeningProfile" ON "gardeningProfile"."playerId"="employee"."id" AND ("gardeningProfile"."key" = $1)) "distinctAlias" ORDER BY "distinctAlias"."gardeningProfile_total_water_drops" DESC, "employee_id" ASC LIMIT 10 -- PARAMETERS: ["2024"]
      
query: SELECT "employee"."id" AS "employee_id", "employee"."createdAt" AS "employee_createdAt", "employee"."updatedAt" AS "employee_updatedAt", "employee"."name" AS "employee_name", "employee"."externalId" AS "employee_externalId", "employee"."email" AS "employee_email", "employee"."phone" AS "employee_phone", "employee"."employee_code" AS "employee_employee_code", "employee"."department" AS "employee_department", "employee"."status" AS "employee_status", "employee"."facebook_url" AS "employee_facebook_url", "employee"."linkedin_url" AS "employee_linkedin_url", "employee"."avatar" AS "employee_avatar", "employee"."position" AS "employee_position", "employee"."dob" AS "employee_dob", "employee"."sessionId" AS "employee_sessionId", "employee"."employee_type" AS "employee_employee_type", "employee"."employee_type_name" AS "employee_employee_type_name", "employee"."is_leader" AS "employee_is_leader", "employee"."companyId" AS "employee_companyId", "gardeningProfile"."id" AS "gardeningProfile_id", "gardeningProfile"."createdAt" AS "gardeningProfile_createdAt", "gardeningProfile"."updatedAt" AS "gardeningProfile_updatedAt", "gardeningProfile"."key" AS "gardeningProfile_key", "gardeningProfile"."total_plants" AS "gardeningProfile_total_plants", "gardeningProfile"."total_water_drops" AS "gardeningProfile_total_water_drops", "gardeningProfile"."total_completed_plants" AS "gardeningProfile_total_completed_plants", "gardeningProfile"."total_dead_plants" AS "gardeningProfile_total_dead_plants", "gardeningProfile"."total_friend_plants_watered" AS "gardeningProfile_total_friend_plants_watered", "gardeningProfile"."total_caught_bugs" AS "gardeningProfile_total_caught_bugs", "gardeningProfile"."total_caught_friend_bugs" AS "gardeningProfile_total_caught_friend_bugs", "gardeningProfile"."total_killed_bugs" AS "gardeningProfile_total_killed_bugs", "gardeningProfile"."total_released_bugs" AS "gardeningProfile_total_released_bugs", "gardeningProfile"."playerId" AS "gardeningProfile_playerId" FROM "employee" "employee" LEFT JOIN "gardening_player_profile" "gardeningProfile" ON "gardeningProfile"."playerId"="employee"."id" AND ("gardeningProfile"."key" = $1) WHERE "employee"."id" IN ($2, $3, $4, $5, $6, $7, $8, $9, $10, $11) ORDER BY "gardeningProfile"."total_water_drops" DESC -- PARAMETERS: ["2024","01HZH3Z6277GBABK37X51E2YBJ","01HZH3Z62Y42S1TCT25C0Q607Y","01HZH3Z636HKHQ5Z1922EB18WN","01HZH3Z63DP3SWSCZ84Y8GVVAY","01HZH3Z63SPVJZ2AN1HKSR8KQQ","01HZH3Z640B98STDZV3K4JHKF3","01HZH3Z646ADT05Y35T421WADJ","01HZH3Z64AH4RDYGK78GD1X2T7","01HZH3Z64GSXC344QHF21XF3NW","01HZH3Z64NAETEN0DMP9BZEYC6"]

query: SELECT COUNT(DISTINCT("employee"."id")) AS "cnt" FROM "employee" "employee" LEFT JOIN "gardening_player_profile" "gardeningProfile" ON "gardeningProfile"."playerId"="employee"."id" AND ("gardeningProfile"."key" = $1) 

you can see the typeorm auto add : "employee_id" ASC LIMIT 10

**Comment by kormang** [comment]
Thanks @gpoplee122. I have also noticed this, and it affects performance of my queries significantly.

**Comment by kormang** [comment]
I understand it now. It is added when using skip/take, which is recommended for pagination, instead of offset/limit.
