### ISSUE TITLE
TypeORM AfterSave() triggers after creation but when queried, it returns NULL

### ISSUE THREAD

**Issue by errawn** [typeorm/typeorm#4253]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Please look at the detailed question:
[https://stackoverflow.com/questions/56482544/typeorm-aftersave-triggers-after-creation-but-when-queried-it-returns-null](https://stackoverflow.com/questions/56482544/typeorm-aftersave-triggers-after-creation-but-when-queried-it-returns-null)
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
Answered on stackoverflow :)

**Comment by rustamwin** [comment]
@errawn did you solve your problem?

**Comment by rustamwin** [comment]
Closing as no answer from the author.
