### ISSUE TITLE
Prevent nullification of missing related entities

### ISSUE THREAD

**Issue by mgreg89** [typeorm/typeorm#4258]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In our backend system, we face the problem of editing entities with relations by several clients. Given the following scenario:

```@Entity("game")
export class game {
	...some columns ...

	@OneToMany(type => gamelanguagerelation, gamelanguagerelations =>
	gamelanguagerelations.fk_gameid, { cascade: ['insert', 'update'] })
	gamelanguagerelations:gamelanguagerelation[];
}
```

If one client (user A) now creates a new game and submits this to the backend, a second user (user B) could create a new `gamelanguagerelation` for this game on his side. He will submit this relation within the whole game object to the backend. Then, the user A uses its offline copy of this game to also add a new `gamelanguagerelation` with a new (UUID) primary key. When sending this new relation (also within a game object) to the backend, typeorm tries to nullify the first relation (which was inserted by user B) since it is not part of the entity of user A. This even happens if cascade is only set to insert or update (but not remove). Unfortunately, save operation fails in this case because the foreign key (fk_gameid in gamelanguagerelation) is not nullable. Even if it would succeed, I don't want to 'orphanize' missing relations.

Is there a way in typeorm to not nullify missing relations in a data set, that gets saved?

Thanks in advance!

**Comment by Kononnable** [comment]
Ok, so problem is that you've got an entity which doesn't have actual data and it destroys some of your new data on `save`? You should use `preload` to load an actual state of data or use an query builder(probably even a relationalQueryBuilder).

**Comment by mgreg89** [comment]
Thank you for that tip regarding preload! I wasn't aware of this function. But it looks like it is exactly what I was looking for :)

But nevertheless, wouldn't it be more intuitive if such missing data will only be removed from the database when `cascade: true` or `cascade: ['remove']` was explicitly set?

**Comment by Kononnable** [comment]
`cascade:remove` is pretty complex subject and is discussed in few other issues.

As for why it is removed - you're telling typeorm to save a state of an object(an entity). Part of the object is the relation(doesn't matter where it is stored) - you're telling it to set entity as empty table(or at least 'not so full'), so it does that. Cascades do something different - they define if related entity should also be saved - other entity fields, not just state of the relation.
