### ISSUE TITLE
Without refreshing entity from database in mid-process, relations do not work as intended.

### ISSUE THREAD

**Issue by idchlife** [typeorm/typeorm#426]
Here is part of code which is not working as intended. Was not working as intended.

![image](https://cloud.githubusercontent.com/assets/4563032/25497332/e313c9ee-2b8c-11e7-9560-4fa7eef6d05a.png)

User entity has

```typescript
  @OneToMany(type => Player, player => player.user)
  players: Player[];

  @OneToOne(type => Player, player => player.usersCurrent)
  @JoinColumn()
  currentPlayer: Player;
```

Player entity has

```typescript
  @OneToOne(type => User, user => user.currentPlayer, { onDelete: "SET NULL" })
  usersCurrent: User;

  @ManyToOne(type => User, user => user.players)
  user: User;
```

This is refreshFromDB for User

![image](https://cloud.githubusercontent.com/assets/4563032/25497449/48f84118-2b8d-11e7-8d33-24d9e54bf7f3.png)

Doesn't entity object refresh automatically by entityManager

**Comment by idchlife** [comment]
Well, I heavily refactored my entities relations and my code, not relevant anymore.

If anyone stumbles upon this:

review your relations, also know that persist() does not affect your original object but returns new, that was persisted and ready to work with your entities.

It's not like in Doctrine (well, I came from there). No object-link-modifying

**Comment by pleerock** [comment]
right, there is no identity map that stores all your objects in memory, each time you load object its unique and independent object instance.
