### ISSUE TITLE
Auto-failover in TypeORM

### ISSUE THREAD

**Issue by yeung108** [typeorm/typeorm#4262]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Does Replication in TypeORM support auto-failover, assuming that Postgres auto-failover has already setup? Like if the master connection failed, Postgres will automatically make secondary node as the primary node, but will TypeORM automatically make the one of the slave node as the master node?

```
{
  type: "postgres",
  logging: true,
  replication: {
    master: {
      host: "server1",
      port: 3306,
      username: "test",
      password: "test",
      database: "test"
    },
    slaves: [{
      host: "server2",
      port: 3306,
      username: "test",
      password: "test",
      database: "test"
    }, {
      host: "server3",
      port: 3306,
      username: "test",
      password: "test",
      database: "test"
    }]
  }
}
```

E.g. in above case, if server1 has some problem and Postgres service is unavailable, Postgres has automatically make server2 the primary node; but will TypeORM automatically change master to server2 so that read and write are supported in server2?

**Comment by vlapo** [comment]
Hey thank for your question. Typeorm use `node-postres` [Pool](https://node-postgres.com/features/pooling) under the hood, so this kind of question is for them. Check for example this issue https://github.com/brianc/node-postgres/issues/1075.
