### ISSUE TITLE
delete via join

### ISSUE THREAD

**Issue by yinso** [typeorm/typeorm#427]
Hi,

I'm trying to delete via join, though with postgres join doesn't work with delete.

with this query (assuming `Account` <-> `Project` as 1:many join):

```
conn.getRepository(Project)
  .createQueryBuilder('p')
  .innerJoin('p.account = account', 'account')
  .where('account.accountId = :accountId', { accountId: 'test' })
  .delete();
```
it generates the following SQL:

```
DELETE FROM "projects" INNER JOIN "accounts" "account" ON "account"."account_id"="p"."account_id" WHERE "account"."name" = 'test';
```

Which causes postgres to throw the following error:

```
LINE 1: DELETE FROM "projects" INNER JOIN "accounts" "account" ON "a...
```

It looks like the alias `p` isn't used in the query generation, also, the way to make inner join work for postgres is via `using <alias>`, as follows:

```
DELETE FROM "projects" *USING "projects" AS "p"* INNER JOIN "accounts" "account" ON "account"."account_id"="p"."account_id" WHERE "account"."name" = 'test';
```

This can certainly be me not knowing how to use the query builder correctly. Can anyone help verify if I need a different query or if this is not implemented at this time?

Thanks.

**Comment by pleerock** [comment]
No, deletion "via join" is not supported. Consider object deletion manually for each your relation.

**Comment by yinso** [comment]
If this isn't supported, it means that I'll need to retrieve the data first before I delete them right?

Something like below?

```
conn.getRepository(Project)
  .createQueryBuilder('p')
  .innerJoin('p.account = account', 'account')
  .where('account.accountId = :accountId', { accountId: 'test' })
  .getMany()
  .then((projects) => {
    return conn.getRepository(Project).remove(projects)
  })
```

**Comment by pleerock** [comment]
right

**Comment by yinso** [comment]
k thanks.

**Comment by jun9358** [comment]
Please support this feature...

**Comment by Ezard** [comment]
@pleerock are you open to a PR to provide this functionality?

**Comment by Overfacto** [comment]
any progress ?

**Comment by JoaquinAraujo** [comment]
My solution, I hope it will soon be available in TypeORM

```
async delete(id, { order, customer }): Promise<OrderItem> {
    const [ orderItemErr, orderItem ] = await to(
      this.orderItemsRepository.createQueryBuilder('order_item')
        .select([
          'order_item.id',
          'order_item.quantity',
          'order_item.price'
        ])
        .innerJoin('order_item.order', 'order')
        .where({ id, order })
        .andWhere('order.customer = :customer', { customer })
        .getOne()
    )
    // track: console.log(orderItemErr)

    if (orderItemErr || !Boolean(orderItem)) throw new Error('item-not-found')

    const [ err, deletedOrderItem ]: [ Error, DeleteResult ] = await to(this.orderItemsRepository.delete({ id: orderItem.id }))
    // track: console.log(err)

    if (err || !Boolean(deletedOrderItem) || !Boolean(deletedOrderItem.affected)) throw new Error()

    return orderItem
  }
```

**Comment by MichaelSp** [comment]
that would be actually quite useful.

**Comment by TheProgrammer21** [comment]
Extremely useful.. @pleerock could you please open the issue again?

**Comment by imnotjames** [comment]
This was closed by the author.

Should you want this feature please open a properly formatted feature request.
