### ISSUE TITLE
How to use customRepositories into services ?

### ISSUE THREAD

**Issue by pairmix** [typeorm/typeorm#4271]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi there,
I'd like to know what's the best way to use custom repositories into services classes.
I'm using service factories to inject them into my service classes but it's heavy to set many mappers.
Isn't it more easy not to use factories and directly call repositories into my service classes like this:

````
let connection = typeorm.getConnection();
let candidatMapper = connection.getCustomRepository(CandidatRepository)
````

David

**Comment by pairmix** [comment]
When i use services into other services i do:
````
Container.get(ConfigService).get('HOSTID')
````
This way services are not injected via factories.

**Comment by vlapo** [comment]
Hey @pairmix. Maybe I didnt not get you but this is question about your architecture not about typeorm. Please ask this kind of questions on stackoverflow.

Note.: I like to use https://github.com/nestjs/nest framework. Maybe it is answer to your question.

**Comment by pairmix** [comment]
you're right, i'm sorry.
i made a mistake.
this question is relative to routing-controllers (https://github.com/typestack/routing-controllers)

**Comment by pairmix** [comment]
Thank you for your link.
I think i should replace routing-controllers by nestjs.

**Comment by vlapo** [comment]
Or ask this question in `routing-controllers` repository ;)

**Comment by pairmix** [comment]
It's not necesserary anymore. nestjs seems a much better framework.

**Comment by rustamwin** [comment]
You can to use [typedi](https://github.com/typeorm/typeorm-typedi-extensions) or [rc](https://github.com/typeorm/typeorm-routing-controllers-extensions)
