### ISSUE TITLE
expo: foreign_keys pragma not enabled

### ISSUE THREAD

**Issue by schie** [typeorm/typeorm#4276]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[x] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. Created a connection
```js
  const connection = await createConnection({
    name: 'default',
    database: 'somedb',
    synchronize: true,
    type: 'expo' 
```

2. Query pragma
```js
const keyStatus = await connection.manager.query('PRAGMA foreign_keys');
console.log(keyStatus); // [ { "foreign_keys": 0 } ]
```

**Notes**
I noticed this when a 1-to-M relationship was not successfully cascade deleting.
According to the [SQLite docs](https://www.sqlite.org/foreignkeys.html#fk_enable), `foreign_keys` needs to be enabled to work. In the driver, we are setting the pragma, but, per the query, it is still disabled.

Does anyone one know what may be going on?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
This should be enabled now

https://github.com/typeorm/typeorm/blob/b1db370986509253a1043afcc6a0cf781198bf53/src/driver/expo/ExpoDriver.ts#L75
