### ISSUE TITLE
Using cache in findAndCount and getManyAndCount returns 0 as count

### ISSUE THREAD

**Issue by Tallyrald** [typeorm/typeorm#4277]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[x] `0.2.18`

**Steps to reproduce or a small repository showing the problem:**

Consider the following code (the function is inside an abstract class):
```ts
static async GetBasicList(userRepo: Repository<User>, limit: number, page: number): Promise<[User[], number]> {
	return userRepo.findAndCount({
		cache: {
			id: 'userBasicList',
			milliseconds: 100000,
		},
		order: {
			id: 'DESC',
		},
		relations: ['profile'],
		skip: page * limit,
		take: limit,
	});
}
```
Without the cache, the result is fully correct (returns the correct amount of users in the right order, loads the profile relation, correctly paginates and gives back the number of total hits). However when the above is run with caching (as it is specified above) the full result count returns 0.
For example if I have 10 users in my database and I run the query with limit set to 5 and page set to 0, I get 5 users and a count of 0 instead of 10.

The User entity is fairly complex with 11 relations and some other fields, however nothing is eagerly loaded. Some relations have cascade set to true (like the profile the query uses), but removing cascades does not help.

Caching is enabled in ormconfig.js and this issue is present with database cache and ioredis as well.

Also interesting to observe that in the cache, there are 2 queries inserted. One with the 'userBasicList' identifier and one with a NULL identifier. The latter contains a query that starts like this:
```sql
SELECT DISTINCT `distinctAlias`.`User_id` as "ids_User_id", `distinctAlias`.`User_id` FROM (SELECT...
```

Tried using @next, but the same thing happened.

EDIT:
Forgot to mention but the exact same pattern applies when a queryBuilder.getManyAndCount() is used.

**Comment by Tallyrald** [comment]
It seems the problem originates from somewhere in SelectQueryBuilder's getManyAndCount() method.
Looking at the logs whenever the cache option is omitted (that is cache is disabled on the query) 3 queries are run.
1) The one mentioned above which fetches the required user ids (I believe it's this part here)
https://github.com/typeorm/typeorm/blob/0d47ccdb0255a480a9fe0044cbac152675337d52/src/query-builder/SelectQueryBuilder.ts#L1794-L1804
2) The data fetching query generated by the same method using the loadRawResults method
https://github.com/typeorm/typeorm/blob/0d47ccdb0255a480a9fe0044cbac152675337d52/src/query-builder/SelectQueryBuilder.ts#L1806-L1835
3) The entity counting query
https://github.com/typeorm/typeorm/blob/0d47ccdb0255a480a9fe0044cbac152675337d52/src/query-builder/SelectQueryBuilder.ts#L1731-L1743

However, with caching enabled on the query, the counting query is missing from the logs so I assume it does not get executed for some reason and therefore `!results[0]["cnt"]` (see 3rd linked code line 1742) returns true since it doesn't exist. Even better in my debugging session the `result` variable contained raw text results from the second query instead of the counting query. I haven't been able to narrow it down any further yet.

**Comment by mikelduffy** [comment]
Faced a similar issue. This is happening in the [getFromCache](https://github.com/typeorm/typeorm/blob/master/src/cache/RedisQueryResultCache.ts#L98) function when being used with a cache id (`userBasicList` in your case). The cache stores the JSON string of a single query/result set using the cache id as the key. So when used with `findAndCount` the cache will always return the results for the first query (raw elements) rather than the second query (total element count).

**Comment by lookapanda** [comment]
Any update on this?

**Comment by Thibaut-B** [comment]
Same problem for me...

**Comment by xmflsct** [comment]
Same, using `postgres` and `redis`.

**Comment by piosystems** [comment]
The bug is still in place as at 0.2.37. Any upcoming fix?

**Comment by aamirpinger** [comment]
Is that Typeorm not maintained anymore? The last commit is a month old to the repo. Is any chance for the above to resolve or any workaround for the above?

@imnotjames @pleerock
