### ISSUE TITLE
Error in Mysql query changing column name for @UpdateDateColumn

### ISSUE THREAD

**Issue by tzahush** [typeorm/typeorm#4281]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When changing the column name in the database for an @UpdateDateColumn, it would create the following query:

`ALTER TABLE *** CHANGE updated_at updated_at2 datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'`

But there is a fault in the query for mysql, the 'CURRENT_TIMESTAMP(6)' should be without brackets, like so:
`ALTER TABLE ***  CHANGE updated_at updated_at2 datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`

Otherwise the following error rises:
`ALTER TABLE *** CHANGE updated_at updated_at2 datetime(6) NOT NULL DEFAULT 'CURRENT_TIMESTAMP(6)'	Error Code: 1067. Invalid default value for 'updated_at2' `

**Comment by AlexMesser** [comment]
I've added a test and it looks like this issue is already fixed. Please reopen it if you face this error again.
