### ISSUE TITLE
Usage with environment variables

### ISSUE THREAD

**Issue by rmainseas** [typeorm/typeorm#4288]
**Issue type:**

- [x] question
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

**Database system/driver:**

- [ ] `cordova`
- [ ] `mongodb`
- [ ] `mssql`
- [x] `mysql` / `mariadb`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `cockroachdb`
- [ ] `sqlite`
- [ ] `sqljs`
- [ ] `react-native`
- [ ] `expo`

**TypeORM version:**

- [x] `latest`
- [ ] `@next`
- [ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm currently trying to configure TypeORM by passing a config object into the constructor from my config service.

```ts
@Module({
  imports: [
    ConfigModule,
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (
        config: ConfigService
      ): Promise<TypeOrmModuleOptions> => (config.dbOptions),
      inject: [ConfigService],
    }),
  ],
  providers: [
    ConfigService,
  ],
})
```

This works fine, but the problem is that I can't find a way to have TypeORM use this configuration to run migrations...it seems to expect an `ormconfig.json` file on disk...which isn't there because my config is coming in via `ConfigService`. This means that I can't currently run my migrations because typeorm can't find my `ormconfig.json` file. 

How do I tell TypeORM to use the configuration values provided to the constructor?

**Comment by vlapo** [comment]
Do you run migration using typeorm cli?

**Comment by rmainseas** [comment]
Yep

**Comment by vlapo** [comment]
There is no way how to use it this way. Your `ConfigService` is nestjs code and typeorm know nothing about nest. You have to write your own scrip, initialize nestjs and run migrations programatically. Or you have to use `ormconfig.json`.

**Comment by vlapo** [comment]
Ok we have property in connection options. You have to set `migrationsRun` and `migrations`. Typeorm should run pending migrations right after connect.

**Comment by rmainseas** [comment]
So, I'd have to create some kind of CLI interface for my app to run the migrations?

**Comment by vlapo** [comment]
If you want to use typeorm cli with some external service like `ConfigService` yes. Otherwise use `migrationsRun` and run migrations every time nestjs application is started.

**Comment by rmainseas** [comment]
Yeah, not liking the sound of that for my prod environment. Might go with the CLI option, thanks.

**Comment by jspizziri** [comment]
I came across this issue when trying to consistently use environment variables without a file.  It's not exactly the issue described here, however at the root level it sounds like the same problem.

If you're using Docker and setting the env variables in your container, you might run into an issue where it appears that the CLI requires env to be loaded from a file, you just need to [set either the `TYPEORM_CONNECTION` or `TYPEORM_URL`](https://github.com/typeorm/typeorm/blob/00c9f4be0e99d6a54bb2265cacdfea68ce7a4b76/src/connection/ConnectionOptionsReader.ts#L107) variables, and then [the CLI will load config from the environment](https://github.com/typeorm/typeorm/blob/00c9f4be0e99d6a54bb2265cacdfea68ce7a4b76/src/connection/options-reader/ConnectionOptionsEnvReader.ts#L20).

Hope this helps!

**Comment by tobyhinloopen** [comment]
One could use `ormconfig.js` or even `ormconfig.ts` and load your config there. Let the cli know to import that config file with the `--config` option.

```ts
import * as config from "config";
import { SnakeNamingStrategy } from "typeorm-naming-strategies";

export = {
  ...config.get("typeorm") as object,
  namingStrategy: new SnakeNamingStrategy(),
  entities: ["src/entity/*.ts"],
  migrations: ["db/migration/*.ts"],
  subscribers: [],
  cli: {
    migrationsDir: "db/migration",
  },
};
```

I invoke this with `ts-node ./node_modules/typeorm/cli.js --config ormconfig.ts`
