### ISSUE TITLE
Foreign key inside the relation's object

### ISSUE THREAD

**Issue by guschnwg** [typeorm/typeorm#4289]
**Issue type:**

[ x ] question
[ ] bug report
[ x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Is there any way I could get the foreign key inside the object without loading it?

```ts
@Entity()
export default class User {
  @PrimaryGeneratedColumn()
  public id!: number;

  @Column()
  public name!: string;

  @OneToMany((type) => Image, (image) => image.user)
  public images!: Image[];
}

@Entity()
export default class Image {
  @PrimaryGeneratedColumn()
  public id!: number;

  @Column()
  public src!: string;

  @ManyToOne((type) => User, (user) => user.profile)
  public user!: User;
}

```

In the table `Profile` there is a column for the relation `userId`.

If I do what is documented [here](https://typeorm.io/#/relations-faq/how-to-use-relation-id-without-joining-relation) and set `userId` explicitly as a column, i am able to get something like `image.userId`.

I would like to know if I can select the `image` in a form like this: 

```ts
Image {
  id: 0,
  src: '',
  user: {
    id: 0
  }
}
```

Instead of explicitly set `userId` as the column, I could get this `userId` inside a user object (this one ONLY with the id, without any join in db).

**Comment by guschnwg** [comment]
For example, when inserting some `image` to user's id: `10`.

I can do: 

```ts
const entity = this.repository.create({
  src: '',
  user: {
    id: 10,
  },
});
return this.repository.save(entity);
```

It would be useful (and less code inside Entity's class) if we could get:
```ts
{
  id: 12,
  src: '',
  user: {
    id: 10
  }
}
```

Note: that user property inside the image object contains ONLY the id, not the whole database row.

**Comment by vlapo** [comment]
I think there is no way how to achieve this behaviour. Please use additional `userId` column. This column is not some kind of hack. It is recommended way how to work with relation foreign key :)
