### ISSUE TITLE
bug: Table inheritance doesn't work with @AbstractEntity in Postgres

### ISSUE THREAD

**Issue by NoNameProvided** [typeorm/typeorm#429]
When using Postgres (haven't tested other drivers) the `@AbstractEntity` doesn't work. Trying to extend a baseclass has no effect, the created tables misses the columns of the base class. 

Example entities:

```typescript
import { Entity,
  Column, 
  CreateDateColumn, 
  UpdateDateColumn, 
  VersionColumn,
  Index 
} from "typeorm";
import { BaseEntity } from '.';

@Entity()
export class User extends BaseEntity {

  @Column()
  @Index({ unique: true })
  email: string;

  @Column()
  passwordHash: string;

  @Column()
  firstName: string;

  @Column()
  lastName: string;
}
```

```typescript
import {
  AbstractEntity,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  VersionColumn
} from "typeorm";

@AbstractEntity()
export abstract class BaseEntity {

  @PrimaryGeneratedColumn()
  id: number;

  @CreateDateColumn({ timezone: true })
  createdAt: Date;

  @UpdateDateColumn({ timezone: true })
  updatedAt: Date;

  @VersionColumn()
  version: number;
}
```

This example doesn't run because TypeORM will throw an error about missing primary key on the User entity. But if we add a primary key to it (with a different name than id) then we can see that the created table doesn't have the `updatedAt`, `createdAt`, `version` numbers.

**Comment by pleerock** [comment]
Did you include your `BaseEntity` into entities section of orm configuration?

**Comment by NoNameProvided** [comment]
I haven't, thought I have to import only `@Entity` classes. It works after importing. Anyway maybe worth mentioning this in the docs?

**Comment by pleerock** [comment]
probably it is
