### ISSUE TITLE
 Cannot read property 'Database' of undefined

### ISSUE THREAD

**Issue by liangzeng** [typeorm/typeorm#4291]
**Issue type:**

[x] question

**Database system/driver:**

[ x ] `sqljs`

**TypeORM version:**

[ x ] `@next`

**Steps to reproduce or a small repository showing the problem:**

```js
createConnection({
  type: "sqljs",
  location: "test", 
  autoSave: true,
  entities: [
      User
  ],
  logging: ['query', 'schema'],
  synchronize: true
})
```

![image](https://user-images.githubusercontent.com/8503065/59541164-afad0780-8f32-11e9-825a-a08570974957.png)

**Comment by vlapo** [comment]
Did you check our docs ? There is some additional configuration for using sql.js in browser. Problem is `window.SQL` is undefined. https://typeorm.io/#/supported-platforms/browser

**Comment by liangzeng** [comment]
@vlapo thanks

**Comment by liangzeng** [comment]
use sql.js@0.5.0 , @1.0.0  `no constructor`

**Comment by amin-pi** [comment]
> use sql.js@0.5.0 , @1.0.0 `no constructor`

i have same error
how to you solved this problem?

**Comment by bayssmekanique** [comment]
@amin-pi,  revert to `sql.js` version `0.5.0`, and then add below to your webpack plugins array:
```js
      new webpack.ProvidePlugin({
        'window.SQL': 'sql.js/js/sql.js'
      })
```

**Comment by amin-pi** [comment]
> @amin-pi, revert to `sql.js` version `0.5.0`, and then add below to your webpack plugins array:
> 
> ```js
>       new webpack.ProvidePlugin({
>         'window.SQL': 'sql.js/js/sql.js'
>       })
> ```

thanks,
Could you please help me where should i add this part of code?

**Comment by vlapo** [comment]
Does it mean typeorm do not support `sql.js@1.0.0`? Becauase I know we had PR about this topic before. https://github.com/typeorm/typeorm/pull/4105

**Comment by bayssmekanique** [comment]
@vlapo, it does appear that `sql.js@1.0.0` breaks the implementation.  I spent a few hours trying to track down where the changes need to happen but so much of the project has changed from `0.5.0` to `1.0.0` that it might require a full rewrite.

@amin-pi, you need to place the `webpack.ProviderPlugin` in your `webpack.js` file in the `plugins` array.

**Comment by vlapo** [comment]
Add @michaelbromley as author of PR mentioned before

**Comment by michaelbromley** [comment]
Hi. I was summoned 😆

It appears that there are no unit tests for running sql.js in a browser environment, which is why my PR did not account for this scenario (I simply considered it OK once all existing unit tests were passing, which seemed reasonable).

So from the [upgrading to v1.0 section of the docs](https://github.com/kripken/sql.js#upgrading-from-0x-to-1x) it seems that in v0.5, sql.js exposed an `SQL` object on the `window`:

```js
 var db = new SQL.Database();
```

and now it exposes an `initSqlJs` function:

```js
initSqlJs({ locateFile: filename => `/dist/${filename}` }).then(function(SQL){
    var db = new SQL.Database();
    //...
});
```

So it seems that this part:
https://github.com/typeorm/typeorm/blob/efe1a5ff6e59c61056455b28cc6186e315e60b70/src/driver/sqljs/SqljsDriver.ts#L275-L277

should now include a check for the new function, so something like:

```ts
if (PlatformTools.type === "browser") {
    this.sqlite = window.SQL || window.initSqlJs;
}
```

**Comment by vlapo** [comment]
Yeah we do not have browser based tests :/ If someone interested in this topic feel free contribute. I would love to see tests for browser JS/webpack/angular in future.

So what about this issue. @michaelbromley could you test your fix and contribute ? :)

**Comment by fkirc** [comment]
I was able to workaround this issue by placing the following in my global `index.tsx`:

```TypeScript
import sqlite from "sql.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
window.SQL = sqlite;
```

**Comment by moxgeek** [comment]
i have the same issues on ionic , i tried puting a custom webpack and nothing works.
`core.js:6210 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'Database' of undefined
TypeError: Cannot read property 'Database' of undefined
    at SqljsDriver.<anonymous> (SqljsDriver.js:268)
    at step (tslib.es6.js:102)
    at Object.next (tslib.es6.js:83)
    at tslib.es6.js:76
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at __awaiter (tslib.es6.js:72)
    at SqljsDriver.push.dyj+.SqljsDriver.createDatabaseConnectionWithImport (SqljsDriver.js:262)
    at SqljsDriver.<anonymous> (SqljsDriver.js:127)
    at step (tslib.es6.js:102)
    at Object.next (tslib.es6.js:83)
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at zone-evergreen.js:721
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:28591)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28578)`

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
