### ISSUE TITLE
npm 0.2.18 can't download

### ISSUE THREAD

**Issue by xiaofangqie** [typeorm/typeorm#4294]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
Looks like all works now. Maybe small unavailability of npm servers.
```
vlapo$ npm install typeorm@0.2.18 --save

+ typeorm@0.2.18
added 103 packages from 356 contributors and audited 207 packages in 4.96s
found 0 vulnerabilities
```
