### ISSUE TITLE
JOIN with no results produces entity with nulled properties

### ISSUE THREAD

**Issue by martinsiden** [typeorm/typeorm#4299]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

First, thank you for providing this amazing ORM to the community. You guys are doing awesome work on this project.

Now, I have an issue with "custom" many-to-many that you hopefully can help me with. 

I wanted to have a `Many-to-many` relationship setup using TypeORM, but I needed to add some extra properties to the pivot table between them and was therefore not able to use an "automatically" generated pivot table.

Instead, I ended up doing this:

```
@Entity()
export class User {

    ...other properties

    @OneToMany(type => Participant, participants => participants.user)
    events: Array<Participant>;

}

@Entity()
export class Participant {

    ...other properties

    @ManyToOne(type => CalendarEvent, calendarEvent => 
    calendarEvent.participants, { primary: true })
    event: CalendarEvent;

    @ManyToOne(type => User, user => user.events, { primary: true })
    user: User;

}

@Entity()
export class CalendarEvent {

    ...other properties

    @OneToMany(type => Participant, participants => participants.event)
    participants: Array<Participant>;

}
```

This works if I left JOIN from either `CalendarEvent` to pivot, or from `User` to pivot and will produce an empty array if there are no results. But if I left join once more to get the other entity as well, I get a pivot object back where all properties are null.

Joining once:

```
return this.entityManager.createQueryBuilder(User, "user")
                                .leftJoinAndSelect("user.events", "pivot")
                                .where("user.id = :ID", {
                                    ID: "UUID-in-here"
                                })
                                .getOne();
```

It produces empty arrays when there is no results:

```
{
    "id": "UUID-in-here"
    "events": []
}
```

Joining again to retreive the event data:

```
return this.entityManager.createQueryBuilder(User, "user")
                                .leftJoinAndSelect("user.events", "pivot")
                                .leftJoinAndSelect("pivot.event", "event")
                                .where("user.id = :ID", {
                                    ID: "UUID-in-here"
                                })
                                .getOne();
```

I get the following result:

```
{
    "id": "UUID-in-here"
    "events": [
        {
            ...extra pivot columns here with value = null
            "event": null
        }
    ]
}
```

This doesn't happen if you left JOIN multiple times using "normal" many-to-many relationships. For instance, if I run this:

```
return this.entityManager.createQueryBuilder(User, "user")
                            .leftJoinAndSelect("user.teams", "team")
                            .leftJoinAndSelect("team.messages", "message")
                            .where("user.id = :ID", {
                                ID: "UUID-in-here"
                            })
                            .getOne();
```

Where `user` is `many-to-many` with `teams`, and `team` is `many-to-many` with `messages`, I get empty arrays if there is no relationship.

Either:

```
{
    "id": "UUID-in-here",
    "teams": []
}
```

or:

```
{
    "id": "UUID-in-here",
    "teams": [
        "id": "UUID-in-here",
        "messages": []
    ]
}
```

How do I setup the relationship/query to avoid having that object with nulled properties when there are no results?

**Comment by vlapo** [comment]
Tested and it works.

Output:
```
{"id":1,"username":"user1","events":[{"additionalProperty":"additionalProperty","event":{"id":1,"name":"Event name muhaha"}}]}
```
Test case:
```ts

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    username: string;

    @OneToMany(type => Participant, participants => participants.user)
    events: Array<Participant>;

}

@Entity()
export class Participant {

    @Column()
    additionalProperty: string;

    @ManyToOne(
        type => CalendarEvent,
        calendarEvent => calendarEvent.participants,
        { primary: true }
    )
    event: CalendarEvent;

    @ManyToOne(
        type => User,
        user => user.events,
        { primary: true }
    )
    user: User;

}

@Entity()
export class CalendarEvent {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @OneToMany(type => Participant, participants => participants.event)
    participants: Array<Participant>;

}

describe("github issues > #4299", () => {

    let connections: Connection[];
    before(async () => connections = await createTestingConnections({
        entities: [
            User,
            CalendarEvent,
            Participant
        ],
        schemaCreate: true,
        dropSchema: true,
        enabledDrivers: ["postgres"],
        logging: true
    }));
    beforeEach(() => reloadTestingDatabases(connections));
    after(() => closeTestingConnections(connections));

    it("shoud run", () => Promise.all(connections.map(async connection => {

        const entityManager = connection.createEntityManager();

        const user = new User();
        user.username = "user1";
        await entityManager.getRepository(User).save(user);
        const event = new CalendarEvent();
        event.name = "Event name muhaha";
        await entityManager.getRepository(CalendarEvent).save(event);
        const participant = new Participant();
        participant.user = user;
        participant.event = event;
        participant.additionalProperty = "additionalProperty";
        await entityManager.getRepository(Participant).save(participant);

        const result = await entityManager.createQueryBuilder(User, "user")
            .leftJoinAndSelect("user.events", "pivot")
            .leftJoinAndSelect("pivot.event", "event")
            .where("user.id = :ID", {
                ID: user.id
            })
            .getOne();

        console.log(result);
    })));
});
```

**Comment by martinsiden** [comment]
Yeah, but you're saving both a calendar event and a pivot entry. My problem only occurs when there is no relationship found. 

If there is a relationship setup, it will produce proper results. But if there are no rows in either `participant` or `calendar event`, you get the object containing nulled properties.

**Comment by martinsiden** [comment]
Sorry if that was unclear in my initial description!

**Comment by vlapo** [comment]
Ou, pardon. I understand now :) Looks like a bug for me. We have a similar test case but without custom junction table and additional properties:
https://github.com/typeorm/typeorm/blob/82b06d0a59ae368233c00b32330d7f87787a64cd/test/other-issues/join-empty-relations/join-empty-relations.ts#L38-L59

**Comment by CarstenWalther** [comment]
I stumbled across the same problem yesterday. It has something to do with the composed primary key over two relations (over event and user in the example above). If there is a separate primary id column instead, the result does not contain the object with null properties.

**Comment by martinsiden** [comment]
You're right @CarstenWalther. Thanks for the workaround.

**Comment by sapabg** [comment]
You need to add the joining condition in the leftJoinAndSelect function not in the where() one;
Example: 
.leftJoinAndSelect("user.events", "pivot").where("user.id = :ID", { ID: "UUID-in-here" })
should be
.leftJoinAndSelect("user.events", "pivot", "user.id = :ID", { ID: "UUID-in-here" });

At least that's how it works for me...
WORKING: return this.connection
            .getRepository(Contragents)
            .createQueryBuilder('contragents')
            .where('contragents.id = :id', { id: id })
            .leftJoinAndSelect("contragents.properties", "properties", "properties.from <= :year AND properties.to > :year", { year })
            .leftJoinAndSelect("properties.property_use", "property_use")
            .leftJoinAndSelect("properties.property_form", "property_form")
            .leftJoinAndSelect('contragents.payments', 'payments', 'payments.year = :year', { year })
            .leftJoinAndSelect('payments.production', 'production')
            .leftJoinAndSelect('production.production_info', 'production_info')
            .getOne();

NOT WORKING:
this.connection
            .getRepository(Contragents)
            .createQueryBuilder('contragents')
            .where('contragents.id = :id', { id: id })
            .leftJoinAndSelect("contragents.properties", "properties")
            .leftJoinAndSelect("properties.property_use", "property_use")
            .leftJoinAndSelect("properties.property_form", "property_form")
            .andWhere('properties.from <= :year', { year })
            .andWhere('properties.to > :year', { year })
            .leftJoinAndSelect('contragents.payments', 'payments')
            .leftJoinAndSelect('payments.production', 'production')
            .andWhere('payments.year = :year', { year })
            .leftJoinAndSelect('production.production_info', 'production_info')
            .getOne();

**Comment by MardariG** [comment]
Omg, this issue is from before COVID era. Any milestone?

**Comment by serov1** [comment]
You can duplicate your join properties as columns

this fixed the issue for me

`@Entity()
export class Participant {

    ...other properties

    @ManyToOne(type => CalendarEvent, calendarEvent => 
    calendarEvent.participants, { primary: true })
    event: CalendarEvent;

    @ManyToOne(type => User, user => user.events, { primary: true })
    user: User;
    
    @Column({
      name: 'user_id',
      type: 'integer',
      primary: true,
    })
    userId: number;

    @Column({
      name: 'event_id',
      type: 'integer',
      primary: true,
    })
    eventId: number;
}`

**Comment by MardariG** [comment]
@serov1 I think this was [fixed ](https://github.com/typeorm/typeorm/commit/9abf727691d98351f49aa523c5ea03ec2b1ac620) in 0.2.32 version. At least CHANGELOG says so.

**Comment by imnotjames** [comment]
Seems to be fixed in the latest release.

**Comment by clintonb** [comment]
In the event that someone else finds this issue after having issues joining to a `ViewEntity`, follow the example at https://orkhan.gitbook.io/typeorm/docs/view-entities#complete-example and create a `@PrimaryGeneratedColumn` for your view.
