### ISSUE TITLE
MissingPrimaryColumnError when primary defined in relation

### ISSUE THREAD

**Issue by 19majkel94** [typeorm/typeorm#43]
I have an entity described that:

```typescript
import { Test } from "./test";
import { Product } from "./product";

import { Table, Column, ManyToOne } from "typeorm";

@Table()
export class Result {
    @ManyToOne(type => Test, { primary: true, nullable: false })
    public test: Test;

    @ManyToOne(type => Product, { primary: true, nullable: false })
    public product: Product;

    @Column()
    public primaryValue: number;

    @Column()
    public secondaryValue: number;
}
```

And I have an error on launch:
`Error! { MissingPrimaryColumnError: Entity "Result" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.`

Does the `primary` in relations option doesn't work yet or it's just a bug in checking if primary is defined?

**Comment by pleerock** [comment]
this is not supported yet. But it should be in the future version. Right now its a bit complicated, because orm doesn't analize insertion/updating order (which is complicated) and first inserts object with entity with NULL in relationId, then updates its relationId after it saves related entity. With relation's column primary key it won't work because primary key cannot be NULL. 

So, to fix this issue it needs deep refactoring, and I'll plan it to the future versions

**Comment by 19majkel94** [comment]
Ok, it's not a big deal for now - I created `PrimaryGeneratedColumn` to have a foreign key for my other relation. 

But is there an option to have a pair of relation fields defined as an unique constraint?
I need to have only one result for a pair of `Test` and `Product`.

**Comment by pleerock** [comment]
maybe using [indices](https://typeorm.github.io/indices.html) can help?

**Comment by 19majkel94** [comment]
Yes, thanks! It works great now 😄  Sorry for asking this kind of question but the docs is empty and website documentation was updated today and I haven't checked it yet :wink:

**Comment by rostamiani** [comment]
> maybe using [indices](https://typeorm.github.io/indices.html) can help?

Excuse me, How indices can help with this error?
I added `@Index()` to both keys and nothing solved

(Your link is no longer valid)
