### ISSUE TITLE
Oracle driver adds extra ":" symbol to parameters.

### ISSUE THREAD

**Issue by gintsgints** [typeorm/typeorm#430]
With oracle driver, when I do - findOneById
While making query it's forming query with where:

```
WHERE "SKD_PERSONS"."id"=:id_0
```

Not sure what was idea of function escapeQueryWithParameters in oracle driver, but it adds extra column 

```
WHERE "SKD_PERSONS"."id"=::id_0
```

to variable so it get's Oracle error - Error: ORA-01036: illegal variable name/number

**Comment by vitorveiga** [comment]
I have same issue in findByIds.

...DRMS_T_TEG_TEST_CREATED_DATE", "DRMS_T_TEG_TEST"."MODIFIED_DATE" AS "DRMS_T_TEG_TEST_MODIFIED_DATE" FROM "DRMS_T_TEG_TEST" "DRMS_T_TEG_TEST" WHERE "DRMS_T_TEG_TEST"."ID_TEST"=::id_0 -- PARAMETERS: [2]
2017-04-28T17:19:08.868Z - 
error: [4076] error during executing query:Error: ORA-01036: illegal variable name/number

**Comment by gintsgints** [comment]
OK. I will prepeare merge request with removing column in that function. That way it works for me.
