### ISSUE TITLE
AWS Aurora Data API Support?

### ISSUE THREAD

**Issue by lopun** [typeorm/typeorm#4305]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

https://aws.amazon.com/about-aws/whats-new/2018/11/aurora-serverless-data-api-beta/
AWS released new feature called data api which I can query sql through HTTP Request for Aurora Serverless MySQL Edition.
Is there any chance that typeorm will provide this feature?
Otherwise, I would like to get advise how to apply this feature with typeorm.
Thanks :)

**Comment by vlapo** [comment]
Typeorm use underlying "native" drivers to communicate with database. So basically typeorm do not care how sql requests are executed in DB, it is responsibility of "native" driver. 

For this reason I think this is not feature for typeorm. Write your own "native" driver or try open FR in `mysql`, `mysql2` or `pg` native drivers supported by typeorm.

**Comment by Can-Sahin** [comment]
Well i opened up a issue for it and seems like its no do for `mysql`

https://github.com/mysqljs/mysql/issues/2242

So what to do ? Is there any way to intercept the sql statements before they are sent and direct them into a HTTP api instead of mysql connections?

**Comment by lopun** [comment]
Thanks for issuing on mysql repository! @Can-Sahin 🙇 
Actually all I need is to know whether I can get only sql from Entity without using querybuilder.
Here's an example for things I wanna do.

```typescript
import User from 'src/entities/User'

const getSqlToFindUser = () => {
  // note that this isn't promise.
  const sql = User.find({id: 1}).toSql()
  // call data api with this sql string
}
```

I want to get only sql string from repository API(Entity). Is it possible to do so?

**Comment by Can-Sahin** [comment]
I agree to @lopun 

If sql string is obtainable (which i also see when i turn on `logging` flag) then it can be used with another driver instead of `mysql`. There will be still some problems matching `Transactions` but it's still mappable I guess.

**Comment by ArsenyYankovsky** [comment]
I submitted a PR with the first implementation: https://github.com/typeorm/typeorm/pull/4375
Most of the queries should work fine.

**Comment by lopun** [comment]
Really appreciated @ArsenyYankovsky

**Comment by Kononnable** [comment]
PR was merged, so I guess we can close this one.
