### ISSUE TITLE
Class TableCheck is not exported

### ISSUE THREAD

**Issue by michaeldzjap** [typeorm/typeorm#4313]
**Issue type:**

[ ] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am trying to create a check constraint using query runner, but I run into trouble when I want to define the table check instance I have to give as the second argument to `queryRunner.createCheckConstraint`. The `TableCheck` class is not exported, so I can't import it. And if I try to just pass an object of the form `{expression: '"value" >= 0',}` then I get a _TypeScript_ related error (i.e. various required properties are missing).

Could the `TableCheck` class perhaps be exported? I'm happy to submit a PR for this, but it seems easy enough to add this.

Thanks in advance.

**Comment by YegorZaremba** [comment]
Hi, thanks for reporting issue, could you please share code/mini-repo to reproduce this bug

**Comment by michaeldzjap** [comment]
Something like this should clarify it:

```typescript
import {MigrationInterface, QueryRunner, Table, TableCheck} from 'typeorm';

export class CreateBalanceTable1560877295135 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.createTable(new Table({
            name: 'foo',
            columns: [
                {
                    name: 'id',
                    type: 'int',
                    isPrimary: true,
                },
                {
                    name: 'bar',
                    type: 'int',
                    'default': 0,
                },
            ],
        }), true);

        await queryRunner.createCheckConstraint('balance', new TableCheck({
            expression: '"bar" >= 0',
        }));
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.dropTable('foo');
    }

}
```

`TableCheck` class cannot be imported, since it is not exported by _typeorm_.

**Comment by vlapo** [comment]
Looks like more than `TableCheck` is not exported in `index.ts`. Feel free to contribute.

**Comment by michaeldzjap** [comment]
I've submitted #4325 to fix this. Also exported some other missing classes.
