### ISSUE TITLE
Getting Nested objects typeorm

### ISSUE THREAD

**Issue by suku-h** [typeorm/typeorm#4319]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following entities:

**Shipment**

    export class Shipment {
     @PrimaryGeneratedColumn('increment', {
       type: 'int',
       name: 'shipment_id',
     })
     shipmentId: number

     @OneToMany(type => Package, shipmentPackage => shipmentPackage.Shipment, { cascade: true })
     packages: Package[]
    }

**Package**

    export class Package {

      @PrimaryGeneratedColumn('increment', {
       type: 'int',
       name: 'package_id',
      })
      packageId: number

     @ManyToOne(type => Shipment, shipment => shipment.packages)
     @JoinColumn({
       name: 'shipment_id',
     })
     Shipment: Shipment

     @OneToMany(type => PackageItem, shipmentPackageItem =>  shipmentPackageItem.package, { cascade: true, eager: true })
     items: PackageItem[]
    }

**PackageItem**

    export class PackageItem {

     @PrimaryGeneratedColumn('increment', {
      type: 'int',
      name: 'package_item_id',
     })
     packageItemId: number

     @ManyToOne(type => Package, shipmentPackage => shipmentPackage.items)
     @JoinColumn({
      name: 'package_id',
     })
     package: Package
    }

This is the way I am trying to get a shipment

    const condition = {
      where: {
        shipmentId,
      },
      relations: ['packages', 'packages.items'],
    }

I am getting the following error:

     Error: Property "packages.items" was not found in Shipment. Make sure your query is correct

Based on the discussion [here][1] , this is the correct method

What am I missing?

  [1]: https://github.com/typeorm/typeorm/issues/1270#issuecomment-348429760

**Comment by vlapo** [comment]
I am not not sure but I think this is resolved in `@next` branch. Could you check it?

**Comment by suku-h** [comment]
There is nothing in the @next branch on this feature (or bug). If I use `eager: true` in package then it gives items also.
