### ISSUE TITLE
Tarantool support (sql)

### ISSUE THREAD

**Issue by suenot** [typeorm/typeorm#4327]
**Issue type:**

[ ] feature request

**Database system/driver:**

[ ] `tarantool`

Tarantool supported sql: https://www.tarantool.io/en/doc/2.1/reference/reference_sql/sql/

**Comment by Kononnable** [comment]
It looks like trantool have [mysql connector](https://github.com/tarantool/mysql), so you should be able to use it with typeorm as standard mysql database.

**Comment by suenot** [comment]
Thanks! I'll try this later.
