### ISSUE TITLE
Do typeorm support mysql 8.0 xdevapi?

### ISSUE THREAD

**Issue by surajrana52** [typeorm/typeorm#4328]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I wanted to know if typeorm supports the ```@mysql/xdevapi```

Can I work with [Mysql Document Store](https://www.mysql.com/products/enterprise/document_store.html) with the current version of the typeorm.

If current version of typeorm doesn't support the ```@mysql/xdevapi``` will it support in near future?

**Comment by Kononnable** [comment]
No, typeorm doesn't support Mysql Document Store and there are no plans to implement it soon. Unless someones from the community steps in.

**Comment by AbuAbbaad** [comment]
Any plans to include xdevapi support to typeorm ?

**Comment by imnotjames** [comment]
Nope, not unless someone would like to build it.
