### ISSUE TITLE
default value (json) is not getting set in postgreSQL

### ISSUE THREAD

**Issue by DogsForArms** [typeorm/typeorm#433]
Howdy.  I noticed that the default values were being set for columns of type string, boolean, number... but not for a column of type json.  Here is a picture of what my entity may look like:
<img width="356" alt="screen shot 2017-04-30 at 12 22 56 am" src="https://cloud.githubusercontent.com/assets/5252468/25561907/6ac23b6e-2d3b-11e7-8a05-8bad09524be8.png">

The output of this is:
(node:16089) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): error: null value in column "context" violates not-null constraint.

If I were to make this "context" column nullable, I see my database getting filled without the default value of {}, instead NULL.  PS, I am using PostgreSQL 9.5.5.  Thanks very much!

Minor update, I noticed that just setting
context:any = {} 
will do the trick. ( but I still think the intended behavior is that the default field should do this).

**Comment by pleerock** [comment]
thank you for your report. json support is new feature and this looks like a bug, I'll check that.

**Comment by AlexMesser** [comment]
fixed and released in `0.1.0-alpha.29` version
