### ISSUE TITLE
Proper/shorter way to create and save relations

### ISSUE THREAD

**Issue by fookit** [typeorm/typeorm#4330]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am trying to create and save a user's products.

Here's my attempt:
```ts
// userEntity.ts

import { Product } from '../product';

@Entity('user')
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    unique: true
  })
  email: string;

  @Column()
  password: string;

  @OneToMany(type => Product, product => product.user)
  products: Product[];

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
```
```ts
// productEntity.ts

import { ProductCategory } from './productCategoryEntity';
import { User } from '../user';

@Entity('product')
export class Product {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @ManyToOne(type => ProductCategory, {
    eager: true,
    cascade: true
  })
  @JoinTable()
  category: ProductCategory;

  @ManyToOne(type => User, user => user.products)
  user: User;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
```

`POST` at `http://localhost:4000/users/1/products`. 

```ts
// userPost.ts

export async function userPostProduct(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const userRepository: Repository<User> = getManager().getRepository(User);
    const productRepository: Repository<Product> = getManager().getRepository(
      Product
    );

    // Load user by id
    const user = await userRepository.findOne(req.params.id);

    const { ...data } = req.body;

    const productToBeSaved = new Product();
    productToBeSaved.name = data.name;
    productToBeSaved.category = data.category;
    if (user) {
      productToBeSaved.user = user;
    }

    // Validate product entity
    const errors: ValidationError[] = await validate(productToBeSaved, {
      skipMissingProperties: true
    }); // Errors is and array of validation errors

    if (errors.length > 0) {
      // Return BAD REQUEST status code
      return next(createError(400, errors));
    } else {
      let product = await productRepository.save(productToBeSaved);
      // Return a CREATED status code and new product
      res.status(201).send({
        message: 'Product saved successfully',
        product
      });
    }
  } catch (err) {
    // Return a BAD REQUEST status code and email already exists error
    return next(createError(400, err));
  }
}
```
Is there any other way around without assigning every each data like this?
```ts
    const { ...data } = req.body;

    const productToBeSaved = new Product();
    productToBeSaved.name = data.name;
    productToBeSaved.category = data.category;
    if (user) {
      productToBeSaved.user = user;
    }
```

I have tried:
```ts
// Build up entity product to be saved
const productToBeSaved = productRepository.create(req.body);
productToBeSaved.user = user;

if (user) {
  user.products = [productToBeSaved];
  await userRepository.save(user);
}
```

..but it said `productToBeSaved missing properties of Product[]: id, name, category, etc...`

So I changed:
```ts
// Build up entity product to be saved
const productToBeSaved = productRepository.create(req.body);
productToBeSaved.user = user;

if (user) {
  user.products = [...productToBeSaved];
  await userRepository.save(user);
}
```
Now it says `Property 'user' does not exist on type: 'Product[]'.`

What's the best/proper/shorter way to create and save relations? Because sometimes I have multiple columns (more than 10), and I don't want to assign each. 

Please educate me. 

Tech stack: TypeScript, Express, PostgreSQL

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by PachowStudios** [comment]
What are the exact contents of req.body? repository.create **is** the way to go.

**Comment by Mexman2Rowen** [comment]
@PachowStudios This is the `req.body`:

```json
{
  "name": "Pencil",
  "category": {
    "name": "Stationary"
  }
}
```

**Comment by imnotjames** [comment]
Hope this answered your question, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
