### ISSUE TITLE
PostgreSQL 12 compatibility (lack of consrc)

### ISSUE THREAD

**Issue by luzat** [typeorm/typeorm#4332]
**Issue type:**
[x] bug report
[x] feature request

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x] `latest`
[x] `@next`

**Steps to reproduce or a small repository showing the problem:**
PostgreSQL 12 removes the `pg_constraint.consrc` column. This makes `constraintsSql` from `loadTables` in [PostgresQueryRunner.ts](https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresQueryRunner.ts#L1372) fail with an exception and aborting the transaction. Documentation:

* [PostgreSQL 12](https://www.postgresql.org/docs/12/catalog-pg-constraint.html)
* [PostgreSQL 11](https://www.postgresql.org/docs/11/catalog-pg-constraint.html)

The docs for 11 still include `consrc`, but recommend to use `pg_get_constraintdef`,  which only seems to be used for exclusions constraints (`x`) here. This has been introduced in #2710 for exclusions constraints. It seems that `expression` is used in some places, but giving it a very rough look I think whatever `pg_get_constraintdef` returns might work as well. Always using `pg_get_constraintdef` at least gets my 1 entity test running, but this obviously does not use many constraints.

**Comment by viktor-ku** [comment]
@Kononnable I see that it's fixed in the fork of typeorm. Will it be fixed also in the main typeorm (this) repo some day?

**Comment by danvy** [comment]
Is there any work around until a new release is published?

**Comment by MaSydJun** [comment]
I think the only workaround right now is to build https://github.com/eliziario/typeorm yourself and use its command line tool to achieve certain goals. 

Make sure you build eliziario-typeorm first like this:
```
npm install
npm run compile
npm run package
```

After that you could implement a custom npm-script like this:
```
...
"scripts": {
  ...
  "typeorm": "node /path/to/eliziario-typeorm/build/package/cli.js",
  ...
}
...
```

Then you can use this for instance:
```
npm run typeorm -- migration:run
```

Hope this helps & works, didn't really test it...

**Comment by Domiserver** [comment]
I already have a NestJS project built with Angular ready to be deployed.
How should I add this temporary solution to the project?
Thanks

**Comment by stefanpartheym** [comment]
> I already have a NestJS project built with Angular ready to be deployed.
> How should I add this temporary solution to the project?
> Thanks

I'm not aware of any issues during runtime tbh. Am I missing something?
I only experienced the above issue when using the typeorm command line tool to run migrations.
That's why I currently use the eliziario-typeorm command line tool to achieve this.

**Comment by mokanfar** [comment]
@stefanpartheym yes I am currently experiencing issues during runtime. Preventing my nestjs app from working in dev environment.

**Comment by stefanpartheym** [comment]
@mokanfar This seems very odd to me, since I'm not experiencing this issue during runtime.
However, I can imagine you are using `ConnectionOptions.synchronize = true` in order to automatically update your database after making changes to entity classes.

Since I use `ConnectionOptions.synchronize = false` in development, staging and production as well. This might be the reason.

**Comment by Domiserver** [comment]
I downgraded PostgreSQL from version 12 to 11.5 and TyperOrm and the database is running without the "QueryFailedError: column cnst.consrc does not exist".

I will test the project with ConnectionOptions.synchronize = false to check if this is causing the conflict.

Regards.
RonaLT

**Comment by mokanfar** [comment]
@stefanpartheym Yes, setting ```ConnectionOptions.synchronize = false``` removes the error... but I am working now at slight inconvenience in dev mode now with it turned off. Thank you for isolating the issue.

**Comment by viktor-ku** [comment]
@stefanpartheym yeah, thanks for pointing that out.

**Comment by adico1** [comment]
For people following the NestJS ORM install over postgres 12, the following should work

in file 'package.json' instead of the following:
    "typeorm:migration:generate": "npm run typeorm -- migration:generate -n",

use 
    "typeorm:migration:generate": "npm run typeorm -- migration:create -n",

**Comment by ericbiewener** [comment]
I'm getting this error on Postgres 12 even with `synchronize = false` when running the command `typeorm migration:generate`.

**Comment by stefanpartheym** [comment]
@ericbiewener I suspect, the error occurs whenever TypORM is trying to use the QueryRunner to either modify table structure or read/get information about table structure.

As I already mentioned earlier, you could use the typeorm cli from https://github.com/eliziario/typeorm, as described here:

> I think the only workaround right now is to build https://github.com/eliziario/typeorm yourself and use its command line tool to achieve certain goals.
> 
> Make sure you build eliziario-typeorm first like this:
> 
> ```
> npm install
> npm run compile
> npm run package
> ```
> 
> After that you could implement a custom npm-script like this:
> 
> ```
> ...
> "scripts": {
>   ...
>   "typeorm": "node /path/to/eliziario-typeorm/build/package/cli.js",
>   ...
> }
> ...
> ```
> 
> Then you can use this for instance:
> 
> ```
> npm run typeorm -- migration:run
> ```
> 
> Hope this helps & works, didn't really test it...

**Comment by bartlomiej-korpus** [comment]
This is clearly a bug due to breaking change in postgres 12.

**Comment by nolazybits** [comment]
hit the same issue. subscribing.

**Comment by kshitij-srv** [comment]
tried running schema:sync with cli and got the same error. I have tried reverting back to postgres 11.5 but it still doesn't work for me. Tried with versions 11.5, 12 and 12.1

**Comment by stefanpartheym** [comment]
@kshitij-srv 
> tried running schema:sync with cli and got the same error. I have tried reverting back to postgres 11.5 but it still doesn't work for me. Tried with versions 11.5, 12 and 12.1

Have you tried my proposed solution above?

**Comment by kshitij-srv** [comment]
> @kshitij-srv
> 
> > tried running schema:sync with cli and got the same error. I have tried reverting back to postgres 11.5 but it still doesn't work for me. Tried with versions 11.5, 12 and 12.1
> 
> Have you tried my proposed solution above?

@stefanpartheym my bad, hadn't tried it yet. Using cli after manually building from https://github.com/eliziario/typeorm does solve the issue locally. Thanks 👍

**Comment by zishe** [comment]
When you can release this change? I have nest app, that method doesn't work for it.

**Comment by edge777** [comment]
> @mokanfar This seems very odd to me, since I'm not experiencing this issue during runtime.
> However, I can imagine you are using `ConnectionOptions.synchronize = true` in order to automatically update your database after making changes to entity classes.
> 
> Since I use `ConnectionOptions.synchronize = false` in development, staging and production as well. This might be the reason.

This does get rid of the bug for time being! thanks!!

**Comment by zishe** [comment]
It works in `0.2.21`! Thanks!
