### ISSUE TITLE
can not set default value for datetime field inside migration

### ISSUE THREAD

**Issue by shinux** [typeorm/typeorm#4334]
**Issue type:**

- [x] question
- [x] bug report
- [x] feature request
- [ ] documentation issue

**Database system/driver:**

- [ ] `cordova`
- [ ] `mongodb`
- [ ] `mssql`
- [x] `mysql` / `mariadb`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `cockroachdb`
- [ ] `sqlite`
- [ ] `sqljs`
- [ ] `react-native`
- [ ] `expo`

**TypeORM version:**

- [x] `latest`
- [ ] `@next`
- [ ] `0.x.x` (or put your version here)

let's suppose that I want to add a new datetime column to specific table.

```javascript
      await queryRunner.addColumn('message', new TableColumn({
        name: 'delivered_at',
        type: 'datetime',
        default: new Date('2018-07-30 12:00:00'),
      }));
```

I've tried:
`default: new Date('2018-07-30 12:00:00')`
`default: new Date()`
`default: '2018-07-30 12:00:00'`
`default: () => '2018-07-30 12:00:00'`
`default: '() =>  '2018-07-30 12:00:00'`

none of them works, the only default value works is `default: 'now()'`

Does that means typeorm only support setting current_timestamp as datetime field's default value .

**Comment by Kononnable** [comment]
Define 'doesn't work'. You got an error during schema creation, default value isn't set correctly or column is added again on every migration.

**Comment by michaelbromley** [comment]
I might be running into the same thing. In my I am passing a JavaScript `Date` object as the `default`, and the resulting migration line looks like:

```ts
await queryRunner.query("ALTER TABLE `product` ADD `customFieldsBolly` datetime NULL DEFAULT Wed Jan 01 2020 00:11:00 GMT+0100 (Central European Standard Time)", 
```

which is the result of the `Date.toString()` method.

This is using the MySQL driver (MariaDB).

**Comment by golubvladimir** [comment]
It works for me.

```
	@Column({
		type: 'datetime',
		default: () => 'NOW()'
	})
	dateCreate: string;

	@Column({
		type: 'timestamp',
		default: () => 'CURRENT_TIMESTAMP'
	})
	dateEdit: string;
```

**Comment by Kaminto** [comment]
this will work just add string `CURRENT_TIMESTAMP` to default property
```
await queryRunner.addColumn('message', new TableColumn({
        name: 'delivered_at',
        type: 'datetime',
        default: 'CURRENT_TIMESTAMP',
      }));
```

**Comment by shinux** [comment]
@Kaminto @golubvladimir 

`CURRENT_TIMESTAMP` may work.
But how you guys achieve non-current default value?

```
ALTER TABLE <TABLE_NAME> 
CHANGE COLUMN <COLUMN_NAME> <COLUMN_NAME> DATETIME NOT NULL DEFAULT '2015-05-11 13:01:01';
```

**Comment by golubvladimir** [comment]
@shinux 
```
new Date().toISOString().slice(0, 19).replace('T', ' ');
```

**Comment by imnotjames** [comment]
Keep in mind that at this time the default value is not escaped - you'll need to manually handle that yourself.
