### ISSUE TITLE
insert does not return auto-generated column if relation id is undefined

### ISSUE THREAD

**Issue by MardariG** [typeorm/typeorm#4335]
**Issue type:**

[* ] question
[* ] bug report
[*] feature request

**Database system/driver:**

[*] `postgres`

**TypeORM version:**

[*] `latest`

**Steps to reproduce or a small repository showing the problem:**
```
@Entity({ name: 'app_campaign' })
export class CampaignEntity extends AbstractEntity {

  @PrimaryGeneratedColumn({ name: 'id' })
  public id: number;

  @Column({ name: 'title' })
  public title: string;

  @ManyToOne(() => CampaignCategoryEntity, category => category.campaigns, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'category_id' })
  public category: CampaignCategoryEntity;
}
```
```
@Entity({ name: 'app_campaign_category' })
export class CampaignCategoryEntity {

  @PrimaryGeneratedColumn({ name: 'id' })
  public id: number;

  @Column({ name: 'title_ru' })
  public titleRu: string;

  @Column({ name: 'title_ro' })
  public titleRo: string;

  @Column({ name: 'slug' })
  public slug: string;

  @OneToMany(() => CampaignEntity, campaign => campaign.category)
  public campaigns: CampaignEntity[];

  @BeforeInsert()
  private generateSlug(): void {
    this.slug = sluggifyString(this.titleRo);
  }
}

```
I have following insert: 
```
  const campaign = new CampaignEntity();
  campaign.title = title;
  campaign.category = { id: undefined } as CampaignCategoryEntity; // intentionally {id: undefined}
  const response = await getManager().save(CampaignEntity, campaign);
```
In this case, insert is persisted properly but `response .id` is missing. 
**expected:**
```response.id``` to be auto generated primary key, as it was inserted in database and in table it is present.
**cause of issue**
 ```campaign.category = { id: undefined } ```

**Comment by Kononnable** [comment]
Please provide entity definition.
As missing you mean it's not defined and you expect it to be set to undefined?

**Comment by MardariG** [comment]
> Please provide entity definition.
> As missing you mean it's not defined and you expect it to be set to undefined?

I updated issue.
As missing I mean ```response.id``` from persisted ```CampaignEntity``` is missing completely from response, but it should be defined, as entity was persisted successfully in database.

**Comment by Kononnable** [comment]
What is the purpose of `campaign.category = { id: undefined }`? What do you expect out of it? New versions of typescript even screams at you that something is wrong there.
```
Conversion of type '{ id: undefined; }' to type 'CampaignCategoryEntity' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type '{ id: undefined; }' is missing the following properties from type 'CampaignCategoryEntity': titleRu, titleRo, slug, campaignsts(2352)
```

**Comment by MardariG** [comment]
As you may see in my example it is `campaign.category = { id: undefined } as CampaignCategoryEntity;` , but point is not in that, it was passed as this from a DTO, so it may happen with others too, i can fix this easily with some basic validation. The point is that TypeORM is not returning `id` or throw an error. I believe you don't really understood the problem or just ignore the fact that it's a bug and I'm wasting my time trying to improve this library.

**Comment by Kononnable** [comment]
If you see this as wasting time then I agree, we should close this and both of us should stop wasting time.

Typeorm(and many other OSS libraries) assume that user knows what he want to do. So some checks you are expecting from commercial software aren't in place. Are such problems bugs? Depends on the point of view - in commercial software help desk will agree with the client and say it might be a bug/something which should be implemented. In most OSS cases if there is a reasonable way to do get expected results without modifying the code and issue isn't common such problem won't be even considered to be 'fixed'. Difference is about resources and being open either problem is planned to be 'fixed'. In software you pay for they will always accept a new bug application even if they mark it as 'to-be-ignored' in internal system.

So yeah, it matters what you want to achieve. If you want just to show that typeorm can be broken - you can, but the issue will be literally ignored. If there is an actual use case for what you want to achieve then we can talk how to make it work.

Comment which isn't related directly to this issue, but it might explain a little more why typeorm(and many other OSS) isn't going to be ideal and bugfree ever.
https://github.com/typeorm/typeorm/issues/1987#issuecomment-462075049

PS: You always have to validate data from users you get on backend. If you just work on it you will have completely unsecured app, which can be completely hacked in a minute or two if someone knows what he's doing.
