### ISSUE TITLE
Why are queries in electrons main thread blocking both ui and main thread?

### ISSUE THREAD

**Issue by hemmoleg** [typeorm/typeorm#4340]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[0.2.11] `0.x.x` (or put your version here)

Yesterday I made a post on stackoverflow asking why database queries using typeorm are blocking not only the main thread but also the ui thread of my electron application (https://stackoverflow.com/questions/56689970/typeorm-database-queries-blocking-electrons-ui-thread)
Unfortunately I didnt get any answers so I thought I ask the same question here in hope of getting a response.
Also I kept working on the problem today and during my tests I found that if I run the queries in the ui thread they work properly, meaning the ui thread is not blocked. However I realy would like to know why this happens and what I have to do to run queries in the main thread without blocking neither it nor the ui thread.

**Comment by Kononnable** [comment]
If something is async it can't block anything(by definition). Unless it makes complex calculations - you should be able to determine it by seeing if one of your cores is running at full speed with node process.
Nevertheless if there really is a problem we won't be able to debug it without simple reproduction code(and there is a big possibility that your problem isn't really connected to typeorm).

**Comment by hemmoleg** [comment]
I checked the core utilization and none of the cores jumps to 100%, not even close.
Here is the call from the UI
`await ipc.send("testAsyncIpc", filePath);`
and then in the main process

```
export class Reader
{
    constructor(private ipcMain: IpcMain)
    {
        this.ipcMain.on("testAsyncIpc", this.testAsyncIpc.bind(this));
    }

    async testAsyncIpc(event: electron.Event, filePath: string)
    {
        let connection: Connection = await createConnection({
            type: "sqljs",
            location: filePath,
            entities: [Accounts, Messages, MessagesNew, Conversations, ConversationsNew,
                ContactsOld, ContactsNew, Transfers, DbMeta]
        });

        this.messageRepository = await connection.getRepository(
            Messages
        );
        await this.messageRepository.createQueryBuilder().getCount();

        event.sender.send("testAsyncResponse", "test async done");
    }
}
```

**Comment by Kononnable** [comment]
Sorry for late response.
When are you calling `await ipc.send("testAsyncIpc", filePath);` if it is somewhere inside electron lifecycle loop(I don't use electron, so the name might not be valid) awaiting something asynchronous might block the lifecycle loop. If this is just on user input event handler I don't see why such code might block the entire UI.

**Comment by imnotjames** [comment]
This doesn't seem to be a problem directly related to TypeORM.  Without a simple way of replicating the issue it's very difficult to determine if this is working as intended or not.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
