### ISSUE TITLE
Compile error when passing typed object to EntityManager.create()

### ISSUE THREAD

**Issue by jcford73** [typeorm/typeorm#4342]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The following code generates a compile error: "Argument of type 'typeof LogEntry' is not assignable to parameter of type 'string'.ts(2345)" LogEntry is my entity class.

What am I doing wrong here?

```
const logData = {
    message: 'The quick brown fox...',
    additional: ['...jumps over the lazy dog.'],
    level: 1,
    timestamp: new Date(),
    fileName: 'file.js',
    lineNumber: '12:7',
} as ILogEntry;
const logEntry = this.entityManager.create(LogEntry, logData);
this.db.save(logEntry);
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
Please provide entity definition.

**Comment by OliverLeighC** [comment]
I am running into this same problem as well. 

My entity:

```

@Entity({ database: "<name of db>", name: "Persons" })
export class Persons {
  @PrimaryGeneratedColumn({ name: "PersonID", type: "int" })
  personID: number;

  @Column({ name: "FirstName", type: "varchar", length: 256 })
  firstName: string;

  @Column({ name: "MiddleName", type: "varchar", length: 256, nullable: true })
  middleName: string;

  @Column({ name: "LastName", type: "varchar", length: 256 })
  lastName: string;

  @Column({ name: "Biography", nullable: true })
  biography: string;

  @ManyToOne(type => TitleEnum)
  @JoinColumn({ name: "TitleEnumID" })
  titleEnum: TitleEnum;

}

```

the situation:

```
let manager = await getConnection("<connection name>").manager;
await manager.find(Persons, { filters })

```

error on Persons:

No overload matches this call. Argument of type 'typeof Persons' is not assignable to parameter of type string.

And then the location in EntityManager it points to is: node_modules/typeorm/entity-manager/EntityManager.d.ts

```
find<Entity>(entityClass: string, conditions?: FindConditions<Entity>): Promise<Entity[]>;
    /**
     * Finds entities that match given find options.
     * Also counts all entities that match given conditions,
     * but ignores pagination settings (from and take options).
     */
```
with entityClass of type string


I am also using an mssql database, on the latest typeorm version

**Comment by sunnystas** [comment]
same issue in the migration file when trying to use it as a seeder to populate db table.
The funniest fact is that I have exactly same `.create` call in the other file which works fine. This one breaks...

**Comment by jubairsaidi** [comment]
I'm also seeing this same error with the following code:

```typescript
const connection = await createConnection(config);
const manager = connection.createEntityManager();

const admin = query.create(Admin, {
  userId: 1234567890
});
```

```typescript
@Entity()
export class Admin {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('bigint')
  userId: number;
}
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
