### ISSUE TITLE
Whenever a Postgres connection dies, the error is uncaught and crashes the whole app

### ISSUE THREAD

**Issue by tcolar** [typeorm/typeorm#4347]
**Issue type:**

[X] bug report

**Database system/driver:**

[X ] `postgres`

**TypeORM version:**

[X ] `0.2.18` 

---

- Behavior: 
I have TypeOrm with postgres, when a connection is lost, the whole service crashes 
- Expected:
The pool catches the error and recycles or renew the connection. `Pool.on` catches it as noted here : https://github.com/typeorm/typeorm/issues/1689

I created a minimum repro repo here:
https://github.com/tcolar/typeormbug

**TypeOrm Minimal example**
- Code: https://github.com/tcolar/typeormbug/blob/master/src/typeorm.ts
- Output (I manually restarted the DB to cause the connection to drop):
https://github.com/tcolar/typeormbug/blob/master/orm_output.log

Issues: 
- 1) the errors does not appear to be caught by typeOrm, i see typeOrm uses `Pool.on` to catch and print the error, that does not seem to happen. 
- 2) The error is uncaught, the app crashes

**Pg-pool minimal example**
- Code: https://github.com/tcolar/typeormbug/blob/master/src/pgpool.ts
- Output: https://github.com/tcolar/typeormbug/blob/master/pool_output.log

Notes:
- 1)  At least here it seems, `Pool.on` did see and log the error
- 2) While the error is printed, it continues up the stack and crashes the program still.

Am I missing something ?

**Comment by tcolar** [comment]
Actually for the Pg-pool minimal example it makes sense the error is uncaught since I was using `client.query`, using `pool.query` it gets handled properly.

However with typeOrm I never get the error, I tried `logging: ['query', 'error']` and `logging: true`, the sql statements do print out, but the error never does.

I'm wondering if maybe TypeOrm is not using the pool somewhere (ie: using client.query instead)

**Comment by justvamp** [comment]
Any updates on this?

**Comment by tcolar** [comment]
What I have done to get around the issue is set the postgres server to use keepalives every 10mn, this way does my connection does not get messed with (seem to be broken after 15mn of inactivity)

``` 
alter system set tcp_keepalives_idle='600';
alter system set idle_in_transaction_session_timeout='10min';
select * from pg_reload_conf();
```

I also had to do something similar for my redis containers `tcp-keepalive 600`

**Comment by AlexSun98** [comment]
any update?

**Comment by mateusppereira** [comment]
Maybe its related with this error on `pg` lib, fixed on this PR https://github.com/brianc/node-postgres/pull/2081. Try upgrade `pg` version to `8.x`

**Comment by mateusppereira** [comment]
@pleerock Is it safe to use `pg` version `8.x`? I've seem this comment https://github.com/typeorm/typeorm/issues/777#issuecomment-610051081, but for me it seems it works well.
