### ISSUE TITLE
migration:generate consider .gitignore

### ISSUE THREAD

**Issue by antoine-pous** [typeorm/typeorm#4348]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18`

**Steps to reproduce or a small repository showing the problem:**
For convenience and testing i use two kinds of entities files. The first one which are pushed on live server. And others which are not yet on live server but used locally.

Actually i have to works with two directories which is a bit painful. So can you add `.gitignore` detection and skip ignored entities files?

With that in my directory i'll be able to sync all entities but generate migrations only for those i want.

**Comment by Kononnable** [comment]
And what if someone uses different kind of source versioning system?

I think for your use case you might want to consider using two different ormconfigs(or entries in one ormconfig).

**Comment by antoine-pous** [comment]
Many projects use .gitignore i don't see any argument to not implement a way to deal with it natively. It can be an opt-out option.

I already have many configurations and i always use a specific filename scheme to exclude unwanted files.

If the biggest problem is using .gitignore it can be a new config key like `TYPEORM_ENTITIES_IGNORED = db/*.ignore.entity.ts` or similar.

**Comment by imnotjames** [comment]
The `gitingore` solution isn't super clear.  If you want to omit specific entities or migrations, [glob](https://www.npmjs.com/package/glob) - which we use - allows you to create a negative pattern.

> `!(pattern|pattern|pattern)` Matches anything that does not match any of the patterns provided.

If that's not enough, you can pretty easily use multiple directories & wrap the migration runner in your own CLI if you want these to work in a specific way.
