### ISSUE TITLE
Oracle not returning @CreateDateColumn, @UpdateDateColumn and  @PrimaryGeneratedColumn

### ISSUE THREAD

**Issue by bauzer** [typeorm/typeorm#4349]
https://github.com/typeorm/typeorm/blob/117185b5e5d7a4672af6ba1f1341de98fa8d1fef/src/query-builder/ReturningResultsEntityUpdator.ts#L88

`insertResult.raw instanceof Array` returns false.

When it change to `Array.isArray(upsertResult.draw)`, the correct result is returned.

**Comment by julienxaop** [comment]
Hello. I had the same issue. After having spend hours digging into the code I finally found that error as well. How can this issue still be Open? This is a definitively a blocking issue for all Oracle users.

**Comment by ykosyakov** [comment]
Hello. I run the same issue but only when using Typeorm in context of Jest: https://github.com/facebook/jest/issues/2549

**Comment by imnotjames** [comment]
This change has already been made.
