### ISSUE TITLE
Use double quotes for update query in PostgreSQL

### ISSUE THREAD

**Issue by jjude** [typeorm/typeorm#435]
TypeORM uses "" while creating a table and inserting into a table. However for update it doesn't wrap the column names with "". In pg, if a table column is mentioned within "", it treats it with case sensitivity. So this creates a bug while update, if the column name is not wrapped within "".

Ref: http://stackoverflow.com/a/31072263/770719. That is the exact same error I got (column of relation doesn't exist)

**Comment by pleerock** [comment]
this is fixed in `0.1.0-alpha.10`
