### ISSUE TITLE
How to update Tree with closure table?

### ISSUE THREAD

**Issue by YannisMarios** [typeorm/typeorm#4353]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

Hi,

Has anyone figured out how to update a tree stored in closure table?

I followed the example given in the documentation but there seems to be no obvious way to update a node or for example move a child node to another parent.

Is this implemented or not?

I have tried to delete the category from the category table and the categories_closure table in order to re-insert it with a different parent.  try to delete it like this

```
    await getManager()
      .createQueryBuilder()
      .delete()
      .from('categories_closure')             
      .where('"id_ancestor" = :id', { id })
      .execute();
    
    await this.repo.delete(id);

```

which reasonably produces error:

```
error: update or delete on table "categories" violates foreign key constraint "FK_51fff5114cc41723e8ca36cf227" on table "categories_closure"
```

Thank you.

**Comment by YannisMarios** [comment]
Hi I am trying to update a tree stored in a closure table.

What I am trying to do (since in the documentation there is no obvious way to achieve this) is to delete the category from the categories table and the closure table and then re-create it.

I am trying to delete like this: 

```
   let res = await this.repo.findOne(id);
     
    await getManager()
      .createQueryBuilder()
      .delete()
      .from('categories_closure')             
      .where('"id_ancestor" = :id', { id })
      .execute();
    
    await this.repo.delete(id);
```

which reasonably produces error:

```
error: update or delete on table "categories" violates foreign key constraint "FK_51fff5114cc41723e8ca36cf227" on table "categories_closure"
```

Has anyone managed to update a tree stored in a closure table?

Thank you.

**Comment by YannisMarios** [comment]
Hi I am trying to update a tree stored in a closure table.

What I am trying to do (since in the documentation there is no obvious way to achieve this) is to delete the category from the categories table and the closure table and then re-create it.

I am trying to delete like this: 

```
   let res = await this.repo.findOne(id);
     
    await getManager()
      .createQueryBuilder()
      .delete()
      .from('categories_closure')             
      .where('"id_ancestor" = :id', { id })
      .execute();
    
    await this.repo.delete(id);
```

which reasonably produces error:

```
error: update or delete on table "categories" violates foreign key constraint "FK_51fff5114cc41723e8ca36cf227" on table "categories_closure"
```

Has anyone managed to update a tree stored in a closure table?

Thank you.

**Comment by YannisMarios** [comment]
Hi I am trying to update a tree stored in a closure table.

What I am trying to do (since in the documentation there is no obvious way to achieve this) is to delete the category from the categories table and the closure table and then re-create it.

I am trying to delete like this: 

```
   let res = await this.repo.findOne(id);
     
    await getManager()
      .createQueryBuilder()
      .delete()
      .from('categories_closure')             
      .where('"id_ancestor" = :id', { id })
      .execute();
    
    await this.repo.delete(id);
```

which reasonably produces error:

```
error: update or delete on table "categories" violates foreign key constraint "FK_51fff5114cc41723e8ca36cf227" on table "categories_closure"
```

Has anyone managed to update a tree stored in a closure table?

Thank you.

**Comment by imnotjames** [comment]
What is a closure table?

**Comment by abbbel2** [comment]
I have this problem too, anybody got a work around for this?
