### ISSUE TITLE
Switch from dotenv to dotenv-flow

### ISSUE THREAD

**Issue by TheAifam5** [typeorm/typeorm#4354]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

_dotenv-flow extends dotenv adding the ability to have multiple .env* files like .env.development, .env.test and .env.production, also allowing defined variables to be overwritten individually in the appropriate .env*.local file._

**Comment by imnotjames** [comment]
I don't think this makes sense for a project like TypeORM, does it?

It also wouldn't allow for mutiple `.env` files - the connection option reader would need to be updated to effectively support that itself.

It only uses `dotenv` to load a VERY SPECIFIC file.

**Comment by TheAifam5** [comment]
I forgot to close this issue, more info you can find the closed PR.

**Comment by scbird** [comment]
For those wishing to use dotenv-flow, you can place this line at the top of your `ormconfig.js` file:
```javascript
require("dotenv-flow").config({ silent: true, purge_dotenv: true });
```
