### ISSUE TITLE
What is the best practice for saving/updating entities with relations

### ISSUE THREAD

**Issue by gregory-latinier** [typeorm/typeorm#4358]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Let's say that I have the objects Review, Customer and Article

A review is linked to a customer and an article

```
@Entity()
@Unique(["customer", "article"])
export class Review {
  constructor(id?: string) {
    this.id = id;
  }

  @PrimaryGeneratedColumn(("uuid"))
  id: string;

  @CreateDateColumn()
  public createdAt: Date;

  @UpdateDateColumn()
  public updateAt: Date;

  @Column({ length: 2000, nullable: false })
  content: string;

  @Column({ type: "integer", nullable: false, enum: [1, 2, 3, 4, 5] })
  rating: number;

  @ManyToOne(type => Customer, customer => customer.reviews, { nullable: false })
  customer: Customer;

  @ManyToOne(type => Article, article=> article.reviews, { nullable: false })
  article: Article;
}

```

What is the recommanded way to save a review

By setting directly the related ids (dto is the object from the request)

```
await this.reviewRepository.insert({
      rating: dto.rating,
      content: dto.content,
      customer: { id: dto.customerId },
      article: { id: dto.articleId},
    });
```
and let the service handle any database exceptions (foreign keys, ...)

or getting the related objects and assigning them

something like

```
const article = await this.articleRepository.findOne(dto.articleId)

const review = new Review()
review.article = article

await this.reviewRepository.save(review)
```

My issue is that in this case we do one more access. And the more related entities we have the more additionnal database queries we do. But it's something I've seen a lot.

So what's best from a TypeORM PoV ? 1 or 2

Thank you

**Comment by Kononnable** [comment]
Probably depends on what you are used to.
Second option have an advantage - if for whatever reason PK structure of your entity changes(was one column before, now will be composed of two columns) your code will still work.
As for the performance - in most cases I doubt it will matter in overall application performance(if it doesn't just choose more readable option for you), but in some specific cases it might matter.

**Comment by imnotjames** [comment]
Hope this was an answer to your question.  Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
