### ISSUE TITLE
Query Builder - Update with custom naming strategy

### ISSUE THREAD

**Issue by smalbs** [typeorm/typeorm#436]
The SELECT & DELETE query builders use escape methods for tables and column names while UPDATE does not:

<pre><code>
const updateSet = Object.keys(this.updateQuerySet).map(<b>key => key + "=:updateQuerySet_" + key);</b></code></pre>

and

<pre><code>
return "UPDATE " + <b>tableName</b> + " " + (alias ? this.escapeAlias(alias) : "") + " SET " + updateSet;
</code></pre>

Is this intentional, and or should a pull request be submitted?

**Comment by pleerock** [comment]
Looks like I missed this part, would be great if you do a PR

**Comment by pleerock** [comment]
fixed and released in `0.1.0-alpha.10`
