### ISSUE TITLE
CLI not generating migrations when using type-graphql

### ISSUE THREAD

**Issue by Ponjimon** [typeorm/typeorm#4361]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. Create any TypeORM entity
2. Add `@ObjectType()` decorator to it
3. Run `migration:generate`
4. Nothing happens. No error, no log, nothing.

Hello,

I want to use TypeORM together with type-graphql as in this example: https://github.com/19majkel94/type-graphql/tree/master/examples/typeorm-basic-usage

But I cannot get the migration generator to work. If I try to run `migration:generate` just nothing happens. There is no log, no error, nothing.

I’m running this command:
`ts-node -P tsconfig.typeorm.json --log-error -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:generate -n UserEntity`

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
Is this still an issue?  A similar issue had cropped up & the individual could not replicate it.

**Comment by Ponjimon** [comment]
I guess so, I cannot remember what the original issue even was since I never got a reply. I only know that the underlying issue is that errors with the CLI can get swallowed and never show up unless I console log it modifying the compiled code in node_modules.
