### ISSUE TITLE
Method save does not return an instance of the entity class

### ISSUE THREAD

**Issue by affanshahid** [typeorm/typeorm#4363]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

With an entity like:

```ts
import { Exclude } from 'class-transformer';

@Entity()
export class Tenant {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Exclude() // from class-transformer
  @Column()
  name!: string;
}
```

Calling `.save({ name: 'foobar' })` returns a plain object instead of an instance of `Tenant` class. Due to which: decorators from `class-transformer` package do not run. Is there a work around to this? or am I forced to call `.create()` first?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by ajxs** [comment]
Does this work as intended if you instantiate the object using its constructor?

**Comment by quezak** [comment]
I just found this issue because I thought one of my repositories returned plain objects, where all the others usually returned class instances on `save()`. Turns out that in all other places I indeed called `create()` before `save()`. It looks like `save` returns an entity instance when it was given an entity instance, and a plain object when it's given a plain object.

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by viktornord** [comment]
@Kononnable  why it does not return the entity instance by default?
