### ISSUE TITLE
How to update inner collection in mongodb with operators like $addToSet

### ISSUE THREAD

**Issue by vigneshwargupta** [typeorm/typeorm#4365]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

I am using tis with mongodb. I have a requirement to insert a new set of item in an existing collection like $addToSet operator. Is it possible with latest one?
If yes, please submit some small sample code

Thanks in advance

**Comment by vigneshwargupta** [comment]
Noone is interested to answer this, so change it to mongoose as less support of typeorm with Mongo db.

**Comment by judemanutd** [comment]
What have you tried so far? Is there something that does not work? Any troubles using the existing operator in the format as specified in the [mongodb documentation](https://docs.mongodb.com/manual/reference/operator/update/addToSet/)?
