### ISSUE TITLE
Object literal may onlt specify known properties, and 'where' does not exist in type 'FindConditions'

### ISSUE THREAD

**Issue by uuuusssseeeerrrr** [typeorm/typeorm#4369]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

hello... 
i am found 'Object literal may only...' error while typescript compile.
I don't know which this is an typescript error or typeorm error.
help me please.

version -> typescript : 3.5.2, typeorm : 0.2.18

error img ▽
![error](https://user-images.githubusercontent.com/20100284/60321248-3a701680-99b7-11e9-9fdb-7420d139158f.png)

my code ▽
```
import { Arg, Query, Resolver, Authorized, Mutation, Ctx } from 'type-graphql';
import { getRepository } from 'typeorm'
import resumeEntity from "../database/entity/resume"
import resumeSchema from "../schema/resume"

@Query(returns => [resumeSchema])
  async resumeList() {
    return await this.resumeRepo.find({
      where: {
        jobYn: 'y'
      },
      order: {
        seq: "DESC"
      }
    });
  }
```

**Comment by uuuusssseeeerrrr** [comment]
no answer

**Comment by humbertowoody** [comment]
I am having the same issue. Did you solved it somehow??

**Comment by uuuusssseeeerrrr** [comment]
@humbertowoody try to IDE & project file reinstall.

**Comment by humbertowoody** [comment]
I've already tried but Typescript transpilation throws same error even without an IDE :( 
Did you updated your TS version or something else? :)

**Comment by uuuusssseeeerrrr** [comment]
@humbertowoody 
sorry, i'm late.
TS - 3.5.2
typeorm - 0.2.18
