### ISSUE TITLE
ColumnOption to perform concurrency check on update

### ISSUE THREAD

**Issue by tomkroening** [typeorm/typeorm#437]
What are your thoughts on adding the ability to have a columnOption that specifies which columns to add to the WHERE condition in UPDATE statements?

You could have TypeORM check all columns or simply a version column (such as created with @VersionColumn) to make sure that no one has changed the entity prior to update. EntityFramework has a similar feature with its optimistic concurrency mode. An exception is raised whenever a concurrency violation occurs. I suppose the ability the do this for any arbitrary column would require you to track original values which may be out of scope. Just the ability to track this on the version or updatedate columns would be great.

```typescript


@Entity()
export class Account
{
@PrimaryGeneratedColumn("int")
accountId: number | null = null;

@Column("int")
balance: number = 0;

@VersionColumn({type: "int", check: true})
version: number

}

UPDATE account set balance = 1000 WHERE accountId = 1 AND version = 10;
```

**Comment by pleerock** [comment]
Don't think its a good idea. How do you generate such update query? Using update of QueryBuilder? If yes then you have flexibility to create any kid of queries and extra `andWhere` only adds explicitness instead of magic. If you do it via `persist` you must mark your columns primary to make it work.

**Comment by tomkroening** [comment]
So the way I envisioned this is exactly how EntityFramework works... when calling persist (or SaveChanges in EF), TypeORM builds the appropriate update/insert query as is however it also tacks on an additional WHERE condition to UPDATE statements if you have a VersionColumn defined.

This would be no more magic that how persist works today by generating the appropriate statement for the matching record. This would be an opt-in feature that you define while building the model so it shouldn't be a surprise when it does the check. I'm not seeing how versionColumn is very useful without the ability to use it to perform optimistic concurrency ensuring that the first writer wins.

See this article on how EF works. Scroll down to "Detecting Concurrency Conflicts" and see the first bullet point.

https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/handling-concurrency-with-the-entity-framework-in-an-asp-net-mvc-application

NHibernate has a similar feature.

https://weblogs.asp.net/ricardoperes/lesser-known-nhibernate-features-versioning-and-optimistic-concurrency

I suppose alternatively we could listen for a before update event from TypeORM and write custom code to modify the update query via the QueryBuilder providing we could get access to that through the event system.

Yes, it is almost as if version becomes part of the primary key however the difference is that primary keys  shouldn't change so I'd hate to mark this as a key.

**Comment by pleerock** [comment]
I don't think there is a place for this feature in orm design in a near future. So closing it for now.

**Comment by mattmeye** [comment]
@pleerock Please think about it in a future version.

sequelize : http://docs.sequelizejs.com/manual/tutorial/models-definition.html#optimistic-locking
doctrine: 12.2.1. Optimistic Locking http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/transactions-and-concurrency.html

**Comment by pleerock** [comment]
@mattmeye wait author told to enable subscriber events and you are talking about locking. There is already locking support in ORM. See small peace of doc [here](https://github.com/typeorm/typeorm/blob/master/docs/query-builder.md#set-locking) and some examples [here](https://github.com/typeorm/typeorm/blob/master/test/functional/query-builder/locking/query-builder-locking.ts), optimistic one works with `@Version` and `@UpdateDate` decorators
