### ISSUE TITLE
typeorm referenced column name not working

### ISSUE THREAD

**Issue by RobsonnDumbledore** [typeorm/typeorm#4382]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`import { Entity, PrimaryGeneratedColumn, Column, JoinColumn, ManyToOne, OneToMany } from 'typeorm'
import { Company } from './company.entity';

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number

    @Column({ default: null })
    name: string

    @OneToMany(type => Company, company => company.users)
    @JoinColumn({ name : "company_id" })
    company_id: Company

}`

`import { Entity, Column, OneToOne, JoinColumn, OneToMany, PrimaryGeneratedColumn, ManyToMany, ManyToOne } from "typeorm";

import { User } from "./user.entity";

@Entity()
export class Company {

    @PrimaryGeneratedColumn()
    id: number

    @Column({ default: null })
    name: string

    @ManyToOne(type => User, user => user.company_id)
    @JoinColumn({ name: "users_id", referencedColumnName: "company_id"})
    users: Promise<User[]>

}`

(node:6260) UnhandledPromiseRejectionWarning: Error: Referenced column company_id was not found in entity User
--

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by rmainseas** [comment]
Would you mind surrounding your code with 3 backticks instead of one and "ts"? That way GitHub will format it nicely :)

Like so:

    ```ts
    const foo = 'bar';
     ```

Which will do this:


```ts
const foo ='bar';
```


---

Coming back to your problem - it seems that TypeORM can't find the `company_id` property on your `User` entity. Likely because you've done a 1 to many and not filled in that side of the relation

**Comment by Kononnable** [comment]
Closing as no response from the author.
