### ISSUE TITLE
Feature for repository.delete to return useful information.

### ISSUE THREAD

**Issue by griebdaniel** [typeorm/typeorm#4383]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

I want the repository.delete method to return something useful. For now it returns { name: unknown }. I'd like to add this feature on my own, but I'm new to git and I never contributed to anything before. Can you please tell me the steps to implement this feature? (not regarding to code I can do that I guess).

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by rmainseas** [comment]
I'm not a project contributor, but just generally - I'd suggest changing the title of this issue to be less vague(i.e: describe the thing you want to implement). Something along the lines of "Change repository delete method to return <whatever>". It just makes it easier for the project people to triage :)

> Can you please tell me the steps to implement this feature? (not regarding to code I can do that I guess).

What kind of steps were you looking for? You'd need to fork the repo, make your changes and then submit a PR. Was that the kind of info you're after? If so, GitHub have some great info on Pull Requests [here](https://help.github.com/en/articles/about-pull-requests) 

Hope this helps!

**Comment by griebdr** [comment]
Yes thank you. Yes, but I'd also like to know exactly which files should I look for to change.

**Comment by rmainseas** [comment]
You'd have to read the code

**Comment by imnotjames** [comment]
Delete now returns a `DeleteResult` -  could be what you're looking for.

Hope this answered your question, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by simplenotezy** [comment]
@imnotjames I don't see any output from:

```ts
      const test = await this.repository
        .createQueryBuilder()
        .delete()
        .from(TemporaryToken)
        .where({
          token,
          phoneNumber,
        })
        .execute();
```
