### ISSUE TITLE
Is there an option to create ManyToMany intersection?

### ISSUE THREAD

**Issue by nevodavid** [typeorm/typeorm#439]
I want to create like a "sync" command to send the IDs that I want, and the system will know whether to insert/delete/update into the relation table,
same as laravel "sync" in php for reference.

**Comment by pleerock** [comment]
Please provide more description about feature you want, how it should look like and work. I'm not familiar with laravel "sync".

**Comment by nevodavid** [comment]
Yes,
I want to always provide the id in the relation table and according to that the system will perform queries, for example:
**table a - main table - should have many to many**
id | name
1     a
2     a
3     a

**table b - reverse side table**
id | name
1        b
2       b
3       b

**table ab**
a  |  b
1      2
1      3

now i'm fetching the first row from table a, and say that from table b I want only 1,2

so **table ab** should look like that now
a | b
1    1
1    2

So in high level, it insert new row for 1, leave id 2 as it is, removed id 3

**Comment by nevodavid** [comment]
here is php example of laravel 
https://laracasts.com/discuss/channels/eloquent/eloquent-sync-associate?page=1

**Comment by pleerock** [comment]
you can use joins:


```ts
const posts = postRepository.createQueryBuilder("post")
    .leftJoinAndSelect("post.categories", "category", "category.id IN (:ids)")
    .setParameter("ids", [1, 2])
   .getMany();
```

will give you posts with 1 and 2 categories

**Comment by nevodavid** [comment]
Yeah, but i'm taking about persisting not about fetching

**Comment by pleerock** [comment]
okay so you want to `partially` persist into many to many table?

**Comment by nevodavid** [comment]
I want to choose what ids I want to persist in the relation side, here is a little bit of example I wrote with code

```
export class DBHelper
{
    /**
     * Sync items
     * @param obj
     */
    static async sync(obj : {
        relationTableName : string,
        tableId : number,
        relationIds : number[],
        relationKey : string,
        tableKey : string
    })
    {
        let values = await ConnectionComponent.connection().entityManager.query(`SELECT * FROM  ${obj.relationTableName} WHERE ${obj.tableKey} = ?`, [
            obj.tableId
        ]);

        values = _.uniq(_.map(values, obj.relationKey));

        const toRemove = _.difference(values, obj.relationIds);
        const toAdd    = _.difference(obj.relationIds, values);

        const ToAdd = toAdd.map(data => {
            return `(${obj.tableId}, ${data})`;
        }).join(',');

        ConnectionComponent.connection().entityManager.transaction(async (entityManager : EntityManager) => {
            let relations = toRemove.join(',');
            if(relations.length) {
                await entityManager.query(`DELETE FROM ${obj.relationTableName} WHERE ${obj.tableKey} = ? AND ${obj.relationKey} IN(${relations})`, [obj.tableId]);
            }
            if(ToAdd.length) {
                await entityManager.query(`INSERT INTO ${obj.relationTableName} (${obj.tableKey},${obj.relationKey}) VALUES${ToAdd}`);
            }
        });
    }
}
```

**Comment by pleerock** [comment]
isnt regular binding enough? 

```ts
const post = postRepository.createQueryBuilder("post")
      .leftJoinAndSelect("post.categories", "category")
      .getOne();
post.categories.push(new Category(...)); /// add new more categories
post.categories.push(new Category(...));
postRepository.persist(post);
```

**Comment by nevodavid** [comment]
mmm it's not what I mean,
I just want to pass array of all the categories and according to the database he will know what to remove / add / leave

**Comment by pleerock** [comment]
what is "he"? Is it "post"? In my example there is post and I can control what I want to add/remove/leave from the database

**Comment by nevodavid** [comment]
but you don't know what you need to remove and what to insert, you need to fetch what you have from the database and then compare it with your id array, and then decide what to do with every element of the array, and what to do with the database came back from the server.

let's assume I already have a relation table with data:
table ab
1 | 2
1 | 3

now i want to replace this values with new array values
1 | 1
1 | 2

so that means I need to remove column
1 | 3
and need to add column
1 | 1

So you need some kind of automatic thing for that, that can take the database results and compare it with you new data.

**Comment by pleerock** [comment]
> you need to fetch what you have 

right

> compare it with your id array

its your specific use case

I've got your request, and I'll think about this feature. But for now you have to use the way I described and do your specific operations manually

**Comment by pleerock** [comment]
This is specific feature and currently out of orm design. Maybe it will be implemented as part of SpecificRepository in the future. Closing this for now.

**Comment by pleerock** [comment]
I latest releases old's SpecificRepository functionality was refactored into new functionality as part of a new QueryBuilder. Now, if you want to perform manipulations with relations without having to load them you can use relational query builder. Examples are:

```ts
// adds image #3 to post #3
        await connection
            .createQueryBuilder()
            .relation(Post, "images")
            .of({ id: 3 }) // post id
            .add({ id: 3 }); // image id
```

```ts
// removes image #3 from post #3
        await connection
            .createQueryBuilder()
            .relation(Post, "images")
            .of({ id: 3 }) // post id
            .remove({ id: 3 }); // image id
```

More examples can be found [here](https://github.com/pleerock/typeorm/blob/875afb9adf5cf5d62d81f4ff5d0d7bcc3dff2ea4/test/functional/query-builder/relational).
