### ISSUE TITLE
Is there a way to execute WHERE (column1, column2) IN ( (vala, valb), (valc, vald) ) without using a Raw query?

### ISSUE THREAD

**Issue by pavilesjose** [typeorm/typeorm#4393]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[0.2.11 ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to execute this query

```sql
select distinct on ("lastName") * from dogs where ("firstName", "lastName") in (('Mark','Chen'), ('Coco', 'Seth'));
```
I currently got it to this point

```ts
    return this.dogRepository.createQueryBuilder("dog")
    .select("DISTINCT ON (dog.lastName) *")
    .where("(dog.firstName, dog.lastName) IN (:...array)", { array })
    .getMany();
```

Where `array` is a array with nested array of strings, in pairs:

`[ [ 'Mark', 'Chen'], [ 'Coco', 'Set' ] ]`

And I get the following error

` input of anonymous composite types is not implemented`

I assume I'm just doing it wrong. What is the proper way to achieve this? Or is it truly not implemented?

**Comment by haschu** [comment]
You could do:

```ts
const array = [['Mark', 'Chen'], ['Coco', 'Set']];

const firstNames = array.map(name => e[0]);
const lastNames = array.map(name => e[1]);

//...
.where('dog.firstName IN (:...firstNames) AND dog.lastNames IN (:...lastNames)', {
  firstNames,
  lastNames
});
```

**Comment by FelipeTaiarol** [comment]
You can do it like this, for example:

```typescript
const subQuery = qb.subQuery()
		.select('assignment.projectId, assignment.taskId')
		.from(TaskAssignment, 'assignment')
		.where('assignment.userId IN (:...assignedToIds)', {assignedToIds});

qb.andWhere(`(task.projectId, task.taskId) IN ${subQuery.getQuery()}`);
```
