### ISSUE TITLE
Question about the connection management

### ISSUE THREAD

**Issue by lffg** [typeorm/typeorm#4395]
**Issue type:**

- [x] question
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

I was wondering... How does TypeORM works? Because I don't need to store the `connection` instance created from `createConnection` method in any variable.

It just works when I call an entity method... How does it do this? Does TypeORM stores the current connection in the `global` namespace?

PS: Thanks for the awesome ORM. 👏 😄

**Comment by imnotjames** [comment]
TypeORM stores the connection in a globally namespaced `ConnectionManager` object using a library-specific IOC - https://github.com/typeorm/typeorm/blob/c6336aa4c3bbdc4c7907db605c5bd497c0eb42a3/src/index.ts#L204

**Comment by lffg** [comment]
Thanks! :)
