### ISSUE TITLE
Finding entity with with relation condition

### ISSUE THREAD

**Issue by brinzi** [typeorm/typeorm#4396]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello,

Is it possible to query an entity by placing a condition on one of its join columns?

For example, let's say I have the user entity that is in relation to the photos entity. (one-to-many relationship)

Why can't I use the following find configuration to filter the photos based an owning user's property. ?

Eg. I want all the photos for the users that have the firstName='Dan'

```Javascript
let photos = await photosRepo.find({
  where: {
      user: {
          firstName: 'Dan'
      }
  }
})
```

**Comment by pietrzakadrian** [comment]
U can use destructive assigment.

**Comment by Kononnable** [comment]
I guess you're looking for `relations` in find options parameters.

**Comment by anthonyjlmorel** [comment]
Hi guys, what's the status on this ?

I would like to be able to request entities placing where condition on joined relations too which seems either missing or undocumented.

Could you advise on this ?

**Comment by march08** [comment]
Same issue here. Anyone knows how to perform such a find? 

To give a better example
 ```
Car { id, user }
User { id, company }
Company { id }

// I want to find cars with specific company ID
// something like this, but it's not working

let carsOfCompany = await getRepository(Car).find({
  relations: ['user'],
  where: {
      user: {
          companyId: 'someid'
      }
  }
})
```

**Comment by Yoshinari-Exodev** [comment]
meeting.projects, task.qualifications, issues
結局ここら辺って、リレーション先のstatus関係ないのでは？
つまり、project, qualification, assetsIssueとかを単体で削除する機能がないから。。
そもそもリレーション先のstatusを見ている部分は無さそうです。。。

**Comment by ilovett** [comment]
The relation where only seems to work on `id` or perhaps primary columns,

EG if your Car has `user` with `JoinColumn()` you could successfully query on `where: { user: { id: 123 } }` however it doesnt seem to work for non primary columns or joins such as the user's `companyId`

**Comment by ilovett** [comment]
I found it unexpected that the orm was not able to consider that relational query

**Comment by ilovett** [comment]
In my query I tried to parse on `{ user: { mongoId: "xxx" } }` but my `Thing.find({ where: { user: { mongiId: "xxx" } })` yielded, I am guessing because my `Thing.user` `@JoinColumn` is `id` and not `mongoId`

```
WHERE "Thing"."user_id" = $1 -- PARAMETERS: [null]
```

**Comment by alpharder** [comment]
There's a workaround for filtering based on relation fields for `findOne()`/`find()` methods that I've discovered recently. The problem with filtering related table fields only exists for `ObjectLiteral`-style `where`, while string conditions work perfectly. 

Assume that we have two entities – `User` and `Role`, user belongs to one role, role has many users:

```typescript
@Entity()
export class User {
  name: string;

  @ManyToOne(() => Role, role => role.users)
  role: Role;
}

@Entity()
export class Role {
  @OneToMany(() => User, user => user.role)
  users: User[];
}
```

Now we can call `findOne()`/`find()` methods of `EntityManager` or repository:

```typescript
roleRepository.find({
  join: { alias: 'roles', innerJoin: { users: 'roles.users' } },
  where: qb => {
    qb.where({ // Filter Role fields
      a: 1,
      b: 2
    }).andWhere('users.name = :userName', { userName: 'John Doe' }); // Filter related field
  }
});
```

You can omit the `join` part if you've marked your relation as an eager one.

**Comment by daryl-cecile** [comment]
> The relation where only seems to work on `id` or perhaps primary columns,
> 
> EG if your Car has `user` with `JoinColumn()` you could successfully query on `where: { user: { id: 123 } }` however it doesnt seem to work for non primary columns or joins such as the user's `companyId`

Honestly, this should stated in docs somewhere - saved me hours!

Thank you

**Comment by gajananfc** [comment]
@alpharder I used the same code removed the join part, as I've marked relation as eager, but getting an error

> [error]: ER_BAD_FIELD_ERROR: Unknown column ''users.name' in 'where clause'  QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column ''users.name' in 'where clause'

`roleRepository.find({
  where: qb => {
    qb.where({ // Filter Role fields
      a: 1,
      b: 2
    }).andWhere('users.name = :userName', { userName: 'John Doe' }); // Filter related field
  }
});`

What am I missing here?

**Comment by kop7** [comment]
find cars where model location is 9

```ts
Car {id, name, model(ManyToOne->model)}
Model{id, name, location(MaynToOne->location), cars(OneToMany->cars)}
Location{id, name, models(OneToMany->models)}

carRepository.find({
            relations: ['model','model.location'],
            where: {
                'model.location': { id: 2},
            },
        });
```

~~~sql
SELECT
       `Car`.`id` AS `Car_id`,
       `Car`.`title` AS `Car_title`,
       `Car`.`modelId` AS `Car_modelId`,
       `Car__model`.`id` AS `Car__model_id`,
       `Car__model`.`name` AS `Car__model_name`,
       `Car__model`.`locationId` AS `Car__model_locationId`,
       `Car__model__location`.`id` AS `Car__model__location_id`
    FROM `job` `Car` LEFT JOIN `model` `Car__model` ON `Car__model`.`id`=`Car`.`modelId`
    LEFT JOIN `location` `Car__model__location` ON `Car__model__location`.`id`=`Car__model`.`locationId`
~~~~

but miss locationId parameter?...
what am I doing wrong?

**Comment by chenwenqin** [comment]
+1

**Comment by fchu** [comment]
I found the same issue, but for postgres...
Seems like the find method signatures could be more strict, so that all the different variants don't get mingled without clear error handling

**Comment by david-macharia** [comment]
@Cop

> find cars where model location is 2
> 
> ```ts
> Car {id, name, model(ManyToOne->model)}
> Model{id, name, location(MaynToOne->location), cars(OneToMany->cars)}
> Location{id, name, models(OneToMany->models)}
> 
> carRepository.find({
>             relations: ['model','model.location'],
>             where: {
>                 'model.location': { id: 2},
>             },
>         });
> ```
> 
> ```sql
> SELECT
>        `Car`.`id` AS `Car_id`,
>        `Car`.`title` AS `Car_title`,
>        `Car`.`modelId` AS `Car_modelId`,
>        `Car__model`.`id` AS `Car__model_id`,
>        `Car__model`.`name` AS `Car__model_name`,
>        `Car__model`.`locationId` AS `Car__model_locationId`,
>        `Car__model__location`.`id` AS `Car__model__location_id`
>     FROM `job` `Car` LEFT JOIN `model` `Car__model` ON `Car__model`.`id`=`Car`.`modelId`
>     LEFT JOIN `location` `Car__model__location` ON `Car__model__location`.`id`=`Car__model`.`locationId`
> ```
> 
> but miss locationId parameter?...
> what am I doing wrong?

Did you find out why where is ignored?

**Comment by grigdevelop** [comment]
You can also get entities with all relations.
```
     const repo = manager.getRepository(entityType);
     const relations = repo.metadata.relations.map(m => m.propertyName);
     const entities = await repo.find({ relations });
```

**Comment by AlexanderKiriluyk** [comment]
> You can also get entities with all relations.
> 
> ```
>      const repo = manager.getRepository(entityType);
>      const relations = repo.metadata.relations.map(m => m.propertyName);
>      const entities = await repo.find({ relations });
> ```

This will return the first level relations, but not return nested relations

**Comment by niccolofanton** [comment]
I was having the same issue with eager relations, thanks to @alpharder for the workaround.
In case of eager relations you have to use this syntax: 

```
const results= await this.genericEntityRepository.find({
    where: (qb: SelectQueryBuilder<genericEntity>) => {
        qb.where('GenericEntity_relationName.relationProperty= :value', { value: ... })
    }
});
```

real example: 

```
@Entity()
export class ConditionKaizenStatus extends BaseEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Type(() => Status)
    @ManyToOne(() => Status, { eager: true })
    @JoinColumn({ name: 'from_status_id' })
    statusFrom: Status;

    @Type(() => Status)
    @ManyToOne(() => Status, { eager: true })
    @JoinColumn({ name: 'to_status_id' })
    statusTo: Status;

    @Type(() => KaizenType)
    @ManyToOne(() => KaizenType, { eager: true })
    @JoinColumn({ name: 'kaizen_type_id' })
    kaizenType: KaizenType;

    @Column('varchar', { default: CONDITION_OPERATOR_AND })
    operator: ConditionOperator;

    @ManyToMany(type => KaizenField, { eager: true })
    @JoinTable({ name: 'conditions-fields'})
    kaizenFields: KaizenField[];
}
```
Use case in action

```
const mandatoryFields2 = await this.conditionRepository.find({
    where: (qb: SelectQueryBuilder<ConditionKaizenStatus>) => {
        qb
            .where('ConditionKaizenStatus_statusTo.code = :statusCode', { statusCode: STATUS_CODES.INSERTED })
            .andWhere('ConditionKaizenStatus_kaizenType.code = :typeCode', { typeCode: ACTIVITY_KAIZEN_TYPE })
    }
});
```

Hope this can help! Have a nice day :)

**Comment by pvoisin** [comment]
> The relation where only seems to work on `id` or perhaps primary columns,
> 
> EG if your Car has `user` with `JoinColumn()` you could successfully query on `where: { user: { id: 123 } }` however it doesn't seem to work for non primary columns or joins such as the user's `companyId`

How sad! I just confirmed that too (I'm not using the annotation but results are the same). Searching with something like the following doesn't work whilst using "branchId" (primary key) instead of "languageId" does work:
```
where: {
  name: {
    languageId: 7,
  },
}
```

@niccolofanton - thanks for the snippet! It does the trick but, to me, having to rely on somewhat raw SQL defeats the ORM purpose a little...

**Comment by BenSjoberg** [comment]
Seems related to #2707

**Comment by guitexa** [comment]
> 
> 
> There's a workaround for filtering based on relation fields for `findOne()`/`find()` methods that I've discovered recently. The problem with filtering related table fields only exists for `ObjectLiteral`-style `where`, while string conditions work perfectly.
> 
> Assume that we have two entities – `User` and `Role`, user belongs to one role, role has many users:
> 
> ```ts
> @Entity()
> export class User {
>   name: string;
> 
>   @ManyToOne(() => Role, role => role.users)
>   role: Role;
> }
> 
> @Entity()
> export class Role {
>   @OneToMany(() => User, user => user.role)
>   users: User[];
> }
> ```
> 
> Now we can call `findOne()`/`find()` methods of `EntityManager` or repository:
> 
> ```ts
> roleRepository.find({
>   join: { alias: 'roles', innerJoin: { users: 'roles.users' } },
>   where: qb => {
>     qb.where({ // Filter Role fields
>       a: 1,
>       b: 2
>     }).andWhere('users.name = :userName', { userName: 'John Doe' }); // Filter related field
>   }
> });
> ```
> 
> You can omit the `join` part if you've marked your relation as an eager one.

I'd like to know how can I filter part of the string of the related field:

Eg. The string is `John Doe` but I'd like to search for `John` 🤔

```js
}).andWhere('users.name = :userName', { userName: Like(`%John%`) });
```

Thanks🙏🏼

**Comment by ngoding** [comment]
Hey, found a solution. Not sure if it's best practice, but it works for me.
```
let photos = await photosRepo.find({
  where: {
      user: {
          firstName: 'Dan'
      }
  }
})
```
Change to
```
let photos = await photosRepo.find({
  relations: ['user'],
  where: qb => {
    qb.where('Photos__user.firstName = :firstName', { firstName: 'Dan' })
  }
})
```

**Comment by nrowley** [comment]
has finding an entity with relation condition been implemented?
I think this is a necessity for an ORM

**Comment by pradeep0601** [comment]
Eagerly waiting for this feature to search based on relation fields other than the primary key.

**Comment by jeffersonlicet** [comment]
Hi, is anyone working on this? I can take this issue and try to send a pull request.

**Comment by MardariG** [comment]
> Hi, is anyone working on this? I can take this issue and try to send a pull request.

any status here?

**Comment by jeffersonlicet** [comment]
> > Hi, is anyone working on this? I can take this issue and try to send a pull request.
> 
> any status here?

By default only JoinColumns are used (id) I'm trying to include relation cols in a non-intrusive way.

**Comment by Goldziher** [comment]
wow this is a bad bug

**Comment by jeffersonlicet** [comment]
I'll adventure myself and send a non-optimized pull request so I can get feedback about a better way to do this. But seems like it's working now.

**Comment by salvationarinze** [comment]
Any solution to this yet?

**Comment by imnotjames** [comment]
This is directly related to #2707.  If that gets fixed, this does.
