### ISSUE TITLE
WHERE LIKE condition with multiple values

### ISSUE THREAD

**Issue by ninohane** [typeorm/typeorm#4398]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following entity:

```ts
@Entity()
export class Audio {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    title: string;
}
```

And I have an array of strings. For example: ["love", "death", "loneliness"] (there may be more keywords)

I want to form a query where I can search audio with WHERE LIKE condition with multiple values. For example:

```mysql
SELECT * FROM audio WHERE title LIKE '%love%' OR title LIKE '%death%' OR title LIKE '%loneliness%'
```

What would be the most elegant way to do this?

**Comment by ricardotavaresjumia** [comment]
I came up with this soluciton
```

    names.forEach((name, index) => {
        const parameters = {
          ['name_' + index]: '%' + name + '%',
        };
        (!index) ?
          queryBuilder.andWhere(`${tableName}.name LIKE :name_${index}`, parameters) :
          queryBuilder.orWhere(`${tableName}.name LIKE :name_${index}`, parameters);
      });
```

**Comment by riccycastro** [comment]
I came up with this solution:

```
    names.forEach((name, index) => {
        const parameters = {
          ['name_' + index]: '%' + name + '%',
        };
        (!index) ?
          queryBuilder.andWhere(`${tableName}.name LIKE :name_${index}`, parameters) :
          queryBuilder.orWhere(`${tableName}.name LIKE :name_${index}`, parameters);
      });
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by AimeurAmin** [comment]
@itseramin did you find a way to do it without the queryBuilder?

**Comment by itseramin** [comment]
> @itseramin did you find a way to do it without the queryBuilder?

Sadly, no. But I managed to make it work with query builder.

**Comment by Merdi-kim** [comment]
The answer from @RosoPenaranda did the job for me
