### ISSUE TITLE
Transformers and FindOperators like MoreThan or Raw

### ISSUE THREAD

**Issue by joey-lucky** [typeorm/typeorm#4399]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
when use transformer like this

```
@Column({
        name: "date_time",
        type: "datetime",
        transformer: {
            from: (date: Date) =>moment(date).format("YYYY-MM-DD HH:mm:ss"),
            to: (date: string) => moment(date).toDate(),
        }
    })
    dateTime: string;
```

find operators like MoreThan and Raw doesn't work properly for date fields. 
```
// success
let data = await getRepository(BdBill).find({
    dateTime:"2019-04-10 06:47:18"
});

//  all failure under
let data = await getRepository(BdBill).find({
    dateTime:LessThan("2019-04-10 06:47:18")
});
let data = await getRepository(BdBill).find({
    dateTime:LessThan(new Date())
});
let data = await getRepository(BdBill).find({
    dateTime: Raw(alias =>`${alias} > ${new Date()}`)
});
let data = await getRepository(BdBill).find({
    dateTime: Raw(alias =>`${alias} > str_to_date('2019-04-10 06:47:18','%Y-%m-%d %H:%i:%s')`)
});
```

**Comment by joey-lucky** [comment]
look at source code,maybe cause
```
// when run 
// step 1 return Date object
getEntityValue(entity: ObjectLiteral, transform: boolean = false): any|undefined {
    if (transform && this.transformer)
        value = ApplyValueTransformers.transformTo(this.transformer, value);
}
// step 2 when parameterValue is Date while return `${aliasPath} = ${parameter}`; 
protected computeWhereParameter(where: string|((qb: this) => string)|Brackets|ObjectLiteral|ObjectLiteral[]) {
	let parameterValue = column.getEntityValue(where, true);
	if (parameterValue === null) {
		return `${aliasPath} IS NULL`;
	} else if (parameterValue instanceof FindOperator) {  
		
	} else {
		this.expressionMap.nativeParameters[parameterName] = parameterValue;
		parameterIndex++;
		const parameter = this.connection.driver.createParameter(parameterName, parameterIndex - 1);
		return `${aliasPath} = ${parameter}`;
	}
}
```
how to fix to make sure lessthan work

**Comment by hei-pa** [comment]
There is a hacky way to manipulate the value inside the FindOperator

```
      transformer: {
        from: (value: any) => {
          if (!NullOrUndefined(value) && Number(value)) {
            return new Date(Number(value));
          }
        },
        to: (value: any) => {
          if (value) {
            if (value instanceof Date) {
              return value.getTime();
            } else if (value instanceof FindOperator) {
              
              if (value.value instanceof Date) {
                (value as any)._value = value.value.getTime();
              }

              return value;
              
            }
          }
        }
      }
```

This seems to work with all FindOperators. Better solution would be to flag value inside FindOperator to NOT readonly ...

**Comment by osdiab** [comment]
If the above workaround works for all find operators, maybe that workaround can be placed somewhere in TypeORM to simultaneously solve https://github.com/typeorm/typeorm/issues/2390 then? like call the `transformer` before assigning to `_value` wherever that's being used, could be promising if that's kosher.

**Comment by baflo** [comment]
@hei-pa your solution seems not to work with arrays if using the `In` operator. Simply returning an array of parse value does not seem to be the solution.

Does anybody have an idea?

**Comment by baflo** [comment]
This works for me:

```typescript
function to(entityValue: string | FindOperator<any[]>): Buffer | FindOperator<Buffer[]> {
  if (entityValue) {
    if (entityValue instanceof FindOperator) {
      return new FindOperator(
        (entityValue as any)._type,
        Array.isArray(entityValue.value) ? entityValue.value.map(value => this.to(value)) : (this.to(entityValue.value) as any),
        entityValue.useParameter,
        entityValue.multipleParameters
      );
    }

    return transformToBuffer(entityValue.value);
  }
}
```

**Comment by baflo** [comment]
@pleerock Could you make the property `type` public readonly just as `value` such that I don't have to use the hidden property `_type`?

**Comment by imnotjames** [comment]
There is now an accessor for `type` - it'll eventually become a readonly property & `_type` will be removed.

Unfortunately, because transformers can do a WIDE variety of things we cannot do anything within TypeORM except pass you the `FindOperator`.  Not all values should be transformed.

**Comment by sgronblo** [comment]
So what is the recommended workaround if you want to use value transformers and FindOperators? I didn't really understand the reasoning why this problem cannot be solved in Typeorm?
