### ISSUE TITLE
How to use Active Record in a transaction

### ISSUE THREAD

**Issue by lblblong** [typeorm/typeorm#4401]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

----------------
How to use Active Record in a transaction
```typescript
await getManager().transaction(async transactionalEntityManager => {
    const user = new User()
    user.firstName = "Timber"
    user.lastName = "Saw"
    user.isActive = true
    await user.save()
    
    // transaction does not roll back
    throw Error()
})
```

**Comment by likyh** [comment]
I have a same Question. Could you please tell me How to resolve this ?

**Comment by johnkahn** [comment]
Not an author, but just in case you were still wondering, looks like this isn't possible.

From the docs: https://typeorm.io/#/transactions
> You also cannot use classes which use global manager or connection to execute their queries. All operations **MUST** be executed using the provided transactional entity manager.
