### ISSUE TITLE
Upper level Join with repository

### ISSUE THREAD

**Issue by mrfoe7** [typeorm/typeorm#4403]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, everyone!

Please, help me with my problem.

How to use join's with repositories without queryBuilder.
I wanna use typeorm with upper level ORM.
I don't wanna use this soup of code.

```
manager.createQueryBuilder()
            .select('a')
            .from(A, 'a')
            .leftJoinAndSelect((subQuery) => {
                return subQuery
                    .select('b')
                    .from(B, 'b')
                    .innerJoinAndSelect('b.cs', 'c')
            }, 'b', 'a.id_a = b.b_id_a')
            .getMany();

```

I try to use this example https://typeorm.io/#/find-options
But i don't understand how declared entity with all relations in this user case.

```
userRepository.find({ 
    join: {
        alias: "user",
        leftJoinAndSelect: {
            profile: "user.profile",
            photo: "user.photos",
            video: "user.videos"
        }
    }
});
```

My user case:

entity - Auto.ts
```
import { Entity, Column, PrimaryGeneratedColumn} from 'typeorm';

@Entity()
export default class Auto {

    @PrimaryGeneratedColumn({name: 'ID', type: 'int'})
    id?: number;

    @Column({name: 'Name', type: 'int', nullable: true})
    name?: number;

    @Column({name: 'Status', type: 'bit', nullable: true})
    status?: number;

    @Column({name: 'LastAction', type: 'datetime', nullable: true})
    lastAction?: Date;

    @Column({name: 'Total_stat', type: 'bit', nullable: true})
    totalStat?: number;

}
```
Entity - Group.ts
```
import { Entity, Column, PrimaryGeneratedColumn, OneToOne} from 'typeorm';

@Entity()
export default class Group {

    @PrimaryGeneratedColumn({name: 'ID',  type: 'int'})
    id?: number;

    @Column({name: 'Name', type: 'nvarchar'})
    name?: string;

    @Column({name: 'autoID', type: 'int', nullable: true})
    autoId?: number;
}
```

Query
```
const GroupRepository = getManager().getRepository(Group);
        const result = await GroupRepository.findOne({
            join: {
                alias: ??????,
                leftJoinAndSelect: {
                     ?????????
                }
            },
            where: {
                id: requestBody.groupId
            }
        });
```
I need OneToOne mapping *autoId* from Group and *id* from Auto.
Target sql query 
```
SELECT * from [Group]
left join [Auto] on [Auto].ID = [Group]. autoID
where [Group]. autoID = 20
```

Do you have examples for dummies with perfect resolve my problem?

Nearly i use sequilize.
Required function is realized by simple example:
```
GroupRepository.findOne({
    where: {
        id: '12'
    },
    include: [    <--- Join here!!!
      {
        model: Auto,
      }
    ],
  });
```

**Comment by mrfoe7** [comment]
This repository is contain of solution by my question. https://github.com/typeorm/typeorm/tree/a858de1f195d41aaffdeb8c10faa538dc1a15f5c/sample/sample19-one-side-relations

But i don't understand because 'alias' is necessary attribute.
https://github.com/typeorm/typeorm/blob/a4dec02cc59d3219a29c7be0322af2253e1452dc/src/find-options/JoinOptions.ts#L38

Entity - Auto.ts
```
@Entity()
export default class Auto {

    @PrimaryGeneratedColumn({name: 'ID', type: 'int'})
    id?: number;

    @Column({name: 'Name', type: 'int', nullable: true})
    name?: number;

    @Column({name: 'Status', type: 'bit', nullable: true})
    status?: number;

    @Column({name: 'LastAction', type: 'datetime', nullable: true})
    lastAction?: Date;

    @Column({name: 'Total_stat', type: 'bit', nullable: true})
    totalStat?: number;

}
```

Entity - Group.ts
```
@Entity()
export default class Group {

    @PrimaryGeneratedColumn({name: 'ID',  type: 'int'})
    id?: number;

    @Column({name: 'Name', type: 'nvarchar'})
    name?: string;

    @Column({name: 'autoID', type: 'int', nullable: true})
    dispatcherId?: number;

    @OneToOne(type => Auto)
    @JoinColumn({name: 'autoID', referencedColumnName:'id'})
    auto?: Auto;
}
```

Controller.ts
```
...
 const result = await GroupRepository.findOne({
            join: {
                alias: 'group',
                leftJoinAndSelect: {
                    action: "group.autodispatcher",
                },
            },
            where: {
                id: requestBody.groupId
            }
        });
...
```

**Comment by imnotjames** [comment]
I think you may have found an answer to your question.  Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
