### ISSUE TITLE
Duplicate keys issues

### ISSUE THREAD

**Issue by majdi** [typeorm/typeorm#4407]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello, I have a minor but important issue, I used Typeorm for a while and everything is very nice but I just complete a project for a client. He added manually some rows on a database [ don't ask me why ] and now when I save a new entity, Typeorm throw me an exception around a primary key **duplicate key value violates unique constraint "xxx_pkey"**

The issue is that TypeOrm is trying to set the next id value that he insert "himself".

For example, I programmatically create **100 entities** from id 1 to 100, my client added another **42 entities** with id **101... 142**. Then, Typeorm try on save to create an entity with the id 101.

How can a fix, configure that ?

Thanks :)

ps: waaaah an issue with no code 😜

**Comment by jahuuar** [comment]
You need to inform postgres the change on the sequence of ids. Go to pgadmin or psql console and find the name of the attached sequence of the id column, then execute:  
`ALTER SEQUENCE name RESTART 143`

**Comment by majdi** [comment]
Hello @jahuuar, thanks, it's what I did yesterday but is there a option in typeorm handle ? Or even is it  the role of typeorm to handle this kind of issue ?

**Comment by jahuuar** [comment]
If you use directly postgres then you have the same problem, because when you insert a row in a table with id of type `serial` you don't specific the id (e.g. INSERT INTO users(name, description) VALUES ('name1', 'description1')). The id value is calculated with the associated sequence. You can verify the current value of the sequence and the max value of the ids in each insert command, but it will be inefficient, better create a migration with the alter sequence command.

**Comment by majdi** [comment]
Ok nice to know it thank you :)

**Comment by twigs67** [comment]
Is this a TypeOrm related issue or PostGres primarily? This seems kind of insane that we have to manage this.
