### ISSUE TITLE
Not quite clear how to use   @CreateDateColumn() with existing rows: column contains null values. { default: value } seems to have no effect

### ISSUE THREAD

**Issue by idchlife** [typeorm/typeorm#441]

**Comment by pleerock** [comment]
probably you need to fill your database before using it? What if you use `nullable: true`

**Comment by idchlife** [comment]
@pleerock yes, of course, this is the first thing that pops in ones mind when encountering this message. Could you possibly tell me, is it possible to fill database with DEFAULT modifier for database to fill all existing rows with default value? Without erroring about existing rows - like let database to workout rows values based on DEFAULT

I mean it's not exactly developer friendly - by hand filling those values or fill them in migrations every time your app in rapid development. Rapid development is like lean and mean. It don't have to break everything every time, but it has to give opportunity to work fast without thinking about this stuff.

As always, I should mention, I got used to work with Doctrine and Django ORM. Doctrine will fill existing not null columns with null without even warning, and then you could work with your new scheme and work out how to fill null column values. But I don't actually know if this behaviour possible for postgresql. Mysql creates not null columns with null easily (if I'm not mistaken). Maybe postgres etc will break.

Django orm will ask you and propose default value if it can, and if it can't - will ask for default value. But there is CLI for django orm, so it's not quite possible with typeorm (I guess yet)

**Comment by pleerock** [comment]
okay, I've got your point. When adding a new column without nullable set to true, but with `default` value, ORM should automatically set values for exist columns to given default value, am I right?

**Comment by idchlife** [comment]
@pleerock I think that is one of the options. I don't completely back this point of view, because not familiar how will oracle/postgresql behave. Can it event be done in those databases?

It will be a nice feature, though

**Comment by pleerock** [comment]
I think this is a good feature to have

**Comment by pleerock** [comment]
this is implemented since `0.1.0-alpha.10`
