### ISSUE TITLE
findByIds return empty if one of Id not exists

### ISSUE THREAD

**Issue by abdullahgb** [typeorm/typeorm#4411]
- Using Typeorm with Nestjs.
- findByIds return empty list if one of id in passed ids list not exist in database
- Id is Mapped with 'bigint' datatype on Sql Server
- Sample Code

```
@Controller('fonts')
export class FontsController {
  constructor(
    @InjectRepository(Icon)
    private readonly iconRepository: Repository<Icon>,
    private readonly fontService: FontService,
  ) { }
  @Post()
  @ApiImplicitBody({ name: 'icons',type:[IconDto] })
  async getIcons(@Res() res:Response,@Body() body:IconDto[]) {
    let ids = body.map(x=> x.id)  ;

    // Here IconEntities will be empty if one of passed Id not exist in Database
    // If All ids exist in database, iconEntites is never empty list
    let iconEntities =await this.iconRepository.findByIds(ids,{});

  }
```

**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by vlapo** [comment]
Please update description of issue and give us some example code.

**Comment by wmtjaychhatrola** [comment]
const manager = getMongoManager("mongo");
const data = await manager.findByIds(EntityName,["5d68ee65ded19a53c8b581d9"])

retrun null []

@vlapo

**Comment by Karnith** [comment]
this line is the culprit https://github.com/typeorm/typeorm/blob/e92c743fb54fc404658fcaf2254861b6aa63bd98/src/entity-manager/MongoEntityManager.ts#L146

this needs to be changed to return new objectIdInstance(id);

**Comment by initplatform** [comment]
What is the expected return value for findByIDs if not all the ids exist? Is it null, empty array, or the subset of ids? I'd vote for null, as you know there's an error if you're looking for an id that does not exist... 

On that point.. are the return values of the typeORM functions documented anywhere? They are not documented on https://typeorm.io/#/repository-api

**Comment by imnotjames** [comment]
I believe as of a little while ago this should now throw an exception.
