### ISSUE TITLE
EntitySubscriber hooks on cascade delete

### ISSUE THREAD

**Issue by oshtman** [typeorm/typeorm#4419]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

I am trying to accomplish running a `beforeRemove` hook on a child relation when it's being deleted through a parent entity.

Conceptual example:
```ts
@Entity()
class User extends BaseEntity {
....
....
  @OneToOne(type => File, image => image.user, {
    nullable: true,
    eager: true,
    cascade: true,
  })
  image?: File;
}

@Entity()
class File extends BaseEntity {
....
....
  @JoinColumn({ name: 'user_id' })
  @OneToOne(type => User, user => user.image, {
    nullable: true,
    onDelete: 'CASCADE',
  })
  user?: User;
}

@EventSubscriber()
class FileSubscriber implements EntitySubscriberInterface<File> {
....
....
  beforeRemove(event: RemoveEvent<File>) {
    // This is not being called when cascade deleting
  }
```

When I delete a user entity with a file relation present, it correctly removed both from the database, however, without calling the beforeRemove hook.

Is this intended behavior, or am I missing something obvious here?

**Comment by lyandr** [comment]
Hello, i notice that remove and delete are different. So if you use entity.delete() the beforeRemove hook will not be called. Use entity.remove() instead.

**Comment by Kononnable** [comment]
`onDelete: 'CASCADE'` is database layer setting. It is set in your db schema and deletion is done by database(not orm) - that's why orm is not aware of record being removed and such subscriber doesn't work.
You might look for `cascade` option in relation options, but I'm not sure if cascades deletion was working everyone expected(there was an old, long issue about that matter).
