### ISSUE TITLE
Escape entity IDs when inserting into closure table

### ISSUE THREAD

**Issue by eduardoweiland** [typeorm/typeorm#442]
When inserting into closure tables, the generated SQL includes literal IDs that are not escaped, so it does not work when using string IDs. For MySQL, the code currently looks like

```ts
sql = `INSERT INTO ${this.driver.escapeTableName(tableName)}(ancestor, descendant, level) ` +
      `SELECT ancestor, ${newEntityId}, level + 1 FROM ${this.driver.escapeTableName(tableName)} WHERE descendant = ${parentId} ` +
      `UNION ALL SELECT ${newEntityId}, ${newEntityId}, 1`;
```

The variables `newEntityId` and `parentId` are simply inserted in the query without properly escaping.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.
