### ISSUE TITLE
Error thrown when use select in `findOne`

### ISSUE THREAD

**Issue by assapir** [typeorm/typeorm#4431]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[X] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have the following entity:
```
@Entity()
export default class User implements IUser {
    @PrimaryGeneratedColumn(`uuid`)
    public id: string;

    @Column({ nullable: false })
    public firstName: string;

    @Column({ nullable: false })
    public lastName: string;

    @Index({ unique: true })
    @Column({ nullable: false })
    public email: string;

    @Column({ nullable: false })
    public password: string;

    @Column({ nullable: false, default: Role.USER, type: Number })
    public role: Role;

    @OneToMany((type) => Line, (line) => line.user, {
        eager: true,
    })
    public lines: Line[];
}
```

and I am trying to do the following: 
```
const user = await this._repository.findOne({
            select: [`id`, `firstName`, `lastName`, `email`, `role`, `lines` ],
            where: { email },
        });
```
but this fails with: `Error: lines column was not found in the User entity.`
before adding the `select` statement, everything worked as expected.

EDIT:
This is also happens in a easier use case:
```
const user = await this._repository.findOne(id, { select: [`id`, `firstName`, `lastName`, `email`, `role`, `lines` ] });
```

Thanks

**Comment by meijin007** [comment]
To make it clear - if I use the select option, I don't get the `eager` relation, but I also cannot select it, because it is not it that table.

**Comment by Kononnable** [comment]
Looks like you described the behavior, but didn't ask the question. As you said - lines is a relation(a table), so it cannot be put directly into select part of the query.

**Comment by imnotjames** [comment]
More information to understand the issue would be very helpful in cases like these. Since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
