### ISSUE TITLE
TypeOrm breaks depending on how the constructor for the entity is implemented. Very weird

### ISSUE THREAD

**Issue by CupCakeArmy** [typeorm/typeorm#4433]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

## Repo for reproducing

https://git.nicco.io/cupcakearmy/typeorm-bug

## TLDR;

**Works** ↓:

```ts
constructor(type: TokenType, scopes: TokenScope[], additional: any = '') {
	super()

	this.type = type
	this.scopes = scopes
	this.additional = additional
}
```

**Breaks** ↓:  "TypeError: Cannot destructure property 'scopes' of 'undefined' or 'null'."

```ts
constructor({ scopes, additional, type }: Pick<Token, 'type' | 'scopes'> & { additional?: any }) {
	super()

	this.type = type
	this.scopes = scopes
	this.additional = additional
}
```

**Comment by Tydax** [comment]
I had the same issue, I think your problem is because TypeORM calls the constructor without any parameter, and the constructor is attempting to deconstruct the parameter (which ends being `undefined`). Try adding a default value to your object parameter in your constructor, for example:
```typescript
constructor({ scopes, additional, type }: Pick<Token, 'type' | 'scopes'> & { additional?: any } = {}) {
  // …
}
```

**Comment by CupCakeArmy** [comment]
Awesome, works. Don't know how I did not come to think that

```typescript
constructor(init: ConstuctorInit) {

		super()

		const { scopes, additional, type } = init || {} as ConstuctorInit

		this.type = type
		this.scopes = scopes
		this.additional = additional
	}
```

Btw: if you add the definitive assignment to a field (`myfield!: string`) you can do the following

```typescript
type ConstuctorInit = Pick<Token, 'type' | 'scopes'> & { additional?: any }

constructor(init: ConstuctorInit) {
	super()
	
	Object.assign(this, init)
}
```

**Comment by bennycode** [comment]
The fact that TypeORM doesn't run the constructor hit me hard. The sentence: "[When using an entity constructor its arguments must be optional](https://typeorm.io/#/entities)" should be more prominent on the TypeORM website.

My workaround is to use an `init` function in the constructor which is decorated with [@AfterLoad()](https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md#afterload):

**Example**

```ts
@Entity()
export class Example {

  @PrimaryGeneratedColumn()
  id!: number;

  @Column({length: 500})
  name!: string;

  isInitialized!: boolean;

  constructor() {
    init();
  }

  @AfterLoad()
  init() {
    this.isInitialized = true;
  }

}
```
