### ISSUE TITLE
Deep relation returns an array

### ISSUE THREAD

**Issue by javid-abd** [typeorm/typeorm#4434]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16` (or put your version here)

I need to find an entity (named Case) that has two nested relations (createdBy: employee and employee: Organization). I use deep relations like `['createdBy',  'createdBy.organization]`. It works fine but shows Organization entity inside an array [Organization]. Here is an simplified example:

```
  Case {
    hash: 'jy31jw3eiydavjbyqvkqgpaleb',
    created_at: 2019-07-14T14:15:23.452Z,
    last_updated: 2019-07-14T14:15:23.452Z,
    createdBy:
     Employees {
       hash_id: 'jy31iphnaindfaiavinj5euv8dhrgrj',
       created_at: 2019-07-14T14:14:28.345Z,
       last_updated: 2019-07-14T14:14:28.345Z,
       organization: [Organizations] } } ]
}
```
can someone please explain what I'm doing wrong?

**Comment by Kononnable** [comment]
Please pate your entity definitions. Without them we have no idea how you have declared them(relation might be oneToMany etc.)

**Comment by javid-abd** [comment]
Thanks for the response. As we no longer use TypeORM, I'm going to close the issue
