### ISSUE TITLE
BeforeInsert without decorator (in javascript)

### ISSUE THREAD

**Issue by chiaraperino** [typeorm/typeorm#4437]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I use typeorm with javascript and with entity schema separated.

Is it possible to call BeforeInsert and AfterLoad function without decorator inside a model class?

Thanks
Chiara

**Comment by Kononnable** [comment]
Yes, it should be possible, but it  might be easier to use subscribers instead - they provide similar functionality while not require using of decorators(if memory serves correctly).

**Comment by mrtnzagustin** [comment]
@chiaraperino are you using migrations with the cli? i cant make it work

**Comment by imnotjames** [comment]
The listeners aren't really accomplished using entity schema but subscribers should do what you need.  As the questions been answered I'm gonna close this out.
