### ISSUE TITLE
Update not working !

### ISSUE THREAD

**Issue by aloysius-tim** [typeorm/typeorm#444]
Hey, 
I'm trying to update a row of my database, but it is not working as it should.

`return getEntityManager()
      .getRepository(Audience)
      .createQueryBuilder("audience")
      .update(audience)
      .execute();`
`audience` contains the JSON representing my Audience object with the updated fields.

And I get this error -> `Unhandled rejection Error: ER_DUP_ENTRY: Duplicate entry '14' for key 'PRIMARY'`

It seems that it's trying to add the entry and not update it ?

I also tried with the basic way to update with persist, but not working either.

Thanks for your help !

**Comment by tomkroening** [comment]
Persist is the way you should be doing this.

Keep in mind that a JSON != class as Javascript is a prototypical language. Yes, properties will be there however what about everything else your class contains? Functions? Decorations? Custom getters/setters? You can use tools to clone or map objects as necessary. I tend to write my own map functions as it gives me ultimate control. You can also copy the prototype from your class type into the JSON although I would never recommend doing that on the server side (can't trust the client!).

To me, persisting a JSON object is of limited use... where did you get it from? If it is coming from the client you should be reselecting the original entity and selectively updating it vs. trusting what the client posts. JSON will just be your DTO (Data Transfer Object). 

Anyway - probably more of a question geared for stackoverflow.

**Comment by pleerock** [comment]
> I also tried with the basic way to update with persist, but not working either.

Please show what you are doing. `persist` is the way you should go, and it should work.

**Comment by aloysius-tim** [comment]
Thanks guys! 

Indeed I was trying to cast my JSON to my Entity class directly... Won't do that again!
I'm now using the constructor then set all fields 1by1 and it works perfectly.

Thanks again for your time and for this amazing ORM.
