### ISSUE TITLE
"SyntaxError: Unexpected token o in JSON at position 1" when using `@Column("simple-json")`

### ISSUE THREAD

**Issue by haydennyyy** [typeorm/typeorm#4440]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `"typeorm": "^0.2.17"`

**Steps to reproduce or a small repository showing the problem:**

Well, I'm trying to make an array for a 'custom field' feature of my backend. In my model, I have
```typescript
  @Column("simple-json", { nullable: true })
  public customFields!: { name: string, content: string };
```
which seems correct, given the documentation.

However, then running...
```
char.customFields = req.body.customFields ? req.body.customFields : char.customFields;
```
results in this error.

```
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Function.DateUtils.stringToSimpleJson (C:\Users\Hayden\Source\Repos\roleplay-system\api\src\util\DateUtils.ts:173:49)
    at PostgresDriver.prepareHydratedValue (C:\Users\Hayden\Source\Repos\roleplay-system\api\src\driver\postgres\PostgresDriver.ts:483:31)
    at C:\Users\Hayden\Source\Repos\roleplay-system\api\src\query-builder\transformer\RawSqlResultsToEntityTransformer.ts:143:55
    at Array.forEach (<anonymous>)
    at RawSqlResultsToEntityTransformer.transformColumns (C:\Users\Hayden\Source\Repos\roleplay-system\api\src\query-builder\transformer\RawSqlResultsToEntityTransformer.ts:128:26)
    at RawSqlResultsToEntityTransformer.transformRawResultsGroup (C:\Users\Hayden\Source\Repos\roleplay-system\api\src\query-builder\transformer\RawSqlResultsToEntityTransformer.ts:105:33)
    at C:\Users\Hayden\Source\Repos\roleplay-system\api\src\query-builder\transformer\RawSqlResultsToEntityTransformer.ts:43:33
    at Map.forEach (<anonymous>)
    at RawSqlResultsToEntityTransformer.transform (C:\Users\Hayden\Source\Repos\roleplay-system\api\src\query-builder\transformer\RawSqlResultsToEntityTransformer.ts:42:15)
```

This seems to be something that happened before, back in November 2016. I read #96 and it seems like it was fixed. However... it now seems like the objects hitting TypeORM are still objects, so they're either not being stringified (which I did try doing manually to no success) or something else is going on here.

If it's my code error, *please* let me know.

**Comment by abhijeet1403** [comment]
Is this resolved?

**Comment by abhijeet1403** [comment]
For now just make sure the json-fields in your sql table is null or has JSON value a '' value will thropw this error.

**Comment by haydennyyy** [comment]
I fixed it by switching it to `@Column("json", { array: true })`

**Comment by abhijeet1403** [comment]
@haydennyyy  Do you need to run migrations again?

**Comment by imnotjames** [comment]
Was the value in the database `[object Object]`?

**Comment by imnotjames** [comment]
https://github.com/typeorm/typeorm/pull/6574 was merged in.  You may see this issue recur.  If you do, please join the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) and ping me.  I'm pretty sure this was an error of invalid data in your database.

**Comment by gfborges** [comment]
Is this on release 0.2.29

**Comment by jenkasiaK** [comment]
Try to run your project withnode v12.18.3

**Comment by tahirjamil92** [comment]
Its happening again in  "typeorm": "0.2.45"

**Comment by voinmerk** [comment]
Hello everyone. Faced the same problem. The fact is that for a field with the type JSON there is a condition "if the type is a string, then JSON.parse". The JSON.parse itself is enough to wrap in a Try Catch. In case of an error, the value will be returned in the form in which it came from the database. This is a suggestion to solve the problem in TypeORM. You can also actually set the JSON type for a field in the database, and in the model properties say that this field is of the Text type, then write your DataTransformer, example below:

`
@Column({
  type: 'text',
  nullable: false,
  transformer: {
    to(value: any): any {
      if (typeof value === 'object') {
        value = JSON.stringify(value);
      }

      return value;
    },
    from(value: any): any {
      if (typeof value === 'string') {
        try {
          return JSON.parse(value);
        } catch (e) {
          return value;
        }
      }

      return value;
    }
  }
})
value: any;
`
