### ISSUE TITLE
Queries being executed between rollbackTransaction and release

### ISSUE THREAD

**Issue by FelipeTaiarol** [typeorm/typeorm#4446]
**Issue type:**

[X] question

**Database system/driver:**

[X] `postgres`

**TypeORM version:**

[X] `latest`

I am having a problem with queries being executed after the transaction is rolled back but before the query runner is released.

I created a small example that shows the problem, you can clone [this repo](https://github.com/FelipeTaiarol/typeorm_transactions_problem) and run ```./test.sh``` to reproduce it.

**How the example works**

I create a QueryRunner, start a transaction and pass the EntityManager along to functions that execute in parallel sending queries to the database. If all of them return ok I commit the transaction, if one fail I roll it back by doing this:

```typescript
 await queryRunner.rollbackTransaction();
 await queryRunner.release();
```

If one of the functions fail the others will continue to try to executed queries. They should not be able to do it because the QueryRunner was released.

The problem is that because the code is waiting for ```rollbackTransaction``` transaction to return before calling ```release```, it is possible that some statements will run after the transaction was rolled back but before the QueryRunner was released. 

I was able to "fix it" by not waiting for the ```rollbackTransaction``` to release the QueryRunner.

```typescript
queryRunner.rollbackTransaction();
await queryRunner.release();
```

But this is quite a nasty race condition problem and I was wondering if there is a better way to fix it in my code or if the library should maybe provide a ```rollbackTransactionAndReleaseConnection``` method or something similar?

PS: In my example I am manually handling the transactions to make the code smaller and reproduce it more reliably. In our application code this also happens when using
```typescript
connection.transaction(em -> {
 ....
})
```
but it is not so easy to reproduce.

**Comment by imnotjames** [comment]
This is entirely your application, not a typeorm issue.

You need to wait for all of the promises to resolve or reject before trying to roll back.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by onknight05** [comment]
How about adding a process.nextTick() with a release callback before the rollback.
