### ISSUE TITLE
findOneOrFail on undefined

### ISSUE THREAD

**Issue by chungchi300** [typeorm/typeorm#4448]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```javascript
await photoRepository.findOneOrFail(undefined);

//it returns photo element !
```

**Comment by LuisAngelMoralesRomo** [comment]
There is already a discussion about this on issue #2500

**Comment by vlapo** [comment]
Close as duplicate of #2500
