### ISSUE TITLE
How to use typeorm with Sql?

### ISSUE THREAD

**Issue by likyh** [typeorm/typeorm#4455]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How to use typeorm with Sql?
I want to do like this, but dont want to use `QueryBuilder`:
```
Order.findBySql('SELECT * FROM order WHERE id=1 FOR UPDATE');
```
Because select Sql is to difficult too write with `QueryBuilder`.

**Comment by vlapo** [comment]
We have a `query` method in repository.
https://github.com/typeorm/typeorm/blob/10a5182aeb79db4ef7efb343b76e597e31695707/src/repository/Repository.ts#L325-L327

**Comment by likyh** [comment]
Nonono, I want use Sql to query some data to Model. Not only use Sql function. Such as:
```javascript
let order = Order.findBySql('SELECT * FROM order WHERE id=1 FOR UPDATE');
let user = await order.user
……
```

**Comment by rustamwin** [comment]
@likyh Did you mean "get data by sql as model"?

**Comment by likyh** [comment]
> @likyh Did you mean "get data by sql as model"?

yes

**Comment by vlapo** [comment]
This is not possible right now, sorry.
