### ISSUE TITLE
postgres json array include 

### ISSUE THREAD

**Issue by dasoncheng** [typeorm/typeorm#4457]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

[Check if a Postgres JSON array contains a string](https://stackoverflow.com/questions/19925641/check-if-a-postgres-json-array-contains-a-string)
```sql
create table rabbits (id bigserial primary key, info json not null);
insert into rabbits (info) values
  ('{"name":"Henry", "food":["lettuce","carrots"]}'),
  ('{"name":"Herald","food":["carrots","zucchini"]}'),
  ('{"name":"Helen", "food":["lettuce","cheese"]}');

select id, info ->> 'name' as name, info ->> 'food' as food
from rabbits
where (info -> 'name')::jsonb ? 'Helen'
   or (info -> 'food')::jsonb ? 'carrots';
```
this can work
```ts
foodRepository
  .createQueryBuilder('rabbits')
  .select('rabbits.id', 'id')
  .addSelect(`rabbits.info ->> 'name'`, 'name')
  .addSelect(`rabbits.info ->> 'food'`, 'food')
  .where("(rabbits.info->'name')::jsonb ? ':name'", { name: 'Helen' })
  .orWhere("(rabbits.info->'food')::jsonb ? ':food'", { food: 'carrots' })
  .orderBy('rabbits.id', 'ASC')
  .getMany();
```

but how can I implement the above SQL requirements with `typeorm` find options
```ts
rabbitsRepository.find({
  select: ['rabbit_id', 'info'],
  order: {
    rabbit_id: 'ASC',
  },
  where: [
    {
      info: `(info->'name')::jsonb ? 'Helen`,
    },
    {
      info: `(info->'food')::jsonb ? 'carrots`,
    },
  ],
});
```

**Comment by imnotjames** [comment]
Use the `Raw` operator.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
