### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_this.sqlite.openDatabase')

### ISSUE THREAD

**Issue by ydstaana** [typeorm/typeorm#4466]
**Issue type:**

[-] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[-] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[- ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Using Ionic 4 and IOS, I have cloned this example https://github.com/coturiv/ionic4-typeorm-starter and built using ionic cordova run ios 

**Steps to reproduce or a small repository showing the problem:**
app.component.ts
```
ngOnInit() {
  this.dbService.ready();
}
```

On app startup (db.service.ts)
```
async ready() {
    try {
      await getConnection();
      console.log("Database connected!");
    
    } catch (ex) {
      
      console.log('Connection not established!', ex);

      await this.createConnection();

    }
  }

  private createConnection(): Promise<Connection> {
    let dbOptions: ConnectionOptions;
    
    if (this.platform.is('cordova')) {
      dbOptions = {
        type: 'cordova',
        database: '_vcitemobile',
        location: 'test'
      };
    } else {
      dbOptions = {
        type: 'sqljs',
        location: 'browser',
        autoSave: true
      };
    }

    // additional options
    Object.assign(dbOptions, {
      logging: ['error', 'query', 'schema'],
      synchronize: true,
      entities: [
           User
      ]
    });

    return createConnection(dbOptions);
  }
```

User.ts
```
@Entity('user')
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  username: string;

  @Column()
  password: string;
}
```

Issue:
```
ConnectionNotFoundError: Connection "default" was not found
```
RepositoryNotFoundError: No repository for "user" was found. Looks like this entity is not registered in current "default" connection
```

**Comment by ydstaana** [comment]
UPDATE: 

Should anyone encounter this issue, the fix for me is to wait until deviceready for cordova

this.platform.ready().then(async () => {
    await dbService.ready();
}

**Comment by YannaAlghamdi** [comment]
but it didnt work :(
