### ISSUE TITLE
feature: allow saving relations by their ids

### ISSUE THREAD

**Issue by NoNameProvided** [typeorm/typeorm#447]
Now if I set a relation on A to B and I want to save a new A instance while having only the id of B the relation wont be saved. So I have to query B first and set it as a property.

```ts
let categoryRepository = await this.connection.getRepository<Category>(Category);
product.category = req.body.category;
product.storageUrl = req.body.storageUrl;

let result = await this.repository.persist(<any>product);
// Doesn't work, category column is null in DB (postgres)
```

```ts
let categoryRepository = await this.connection.getRepository<Category>(Category);
let category = await categoryRepository.findOneById(req.body.category);
let product = new Product();
product.category = category;
product.storageUrl = req.body.storageUrl;

let result = await this.repository.persist(product);
// Works, relation is saved into the DB.
```

**Comment by pleerock** [comment]
Can you try this?:

```ts
let product = new Product();
product.category = { id: 1 }; // or new Category().id = 1 or assigned via constructor
product.storageUrl = req.body.storageUrl;

let result = await this.repository.persist(product);
```

**Comment by NoNameProvided** [comment]
It works this way, thanks! 

Still it would be nice if typeORM would see its a primitive value and save it properly.

Sidenote: I am using routing-controllers and my function signature is 

```ts
async create( @Body() product: Product) {
    product.category = <any>{ id: product.category };
    return { payload: await this.repository.persist(product) };
}
```
It cannot convert `product.category` automagically right? Anyway it's better this way in this scenario because I don't want an another query to get the full category object from the database when I only need the `id` which I already have.

The problem is intellisense still thinks that `category` is an instance of `Category`, so to interact with it I must prefix it with `<any>` like: 

```ts
product.category = <any>{ id: product.category };
```

Is this avoidable somehow?

**Comment by pleerock** [comment]
you can add categoryId right to the product as a column and use it:


```ts
@Entity()
class Product {

     @Column({ type: "int", nullable: true })
     categoryId: number;

     @ManyToOne(type => Category)
     @JoinColumn({ name: "categoryId" })
     category: Category;

}
```

Then you can assign `categoryId` each time you want to set a relation and it will work as you expect.

**Comment by NoNameProvided** [comment]
I haven't tried but doesn't this confuse intellisense also? I think

```ts
product.categoryId = product.category;
```

wont work because Typescript thinks I try to assign an instance of `Category` to a `number`.

Anyway lets close this, I think both `product.category = <any>{ id: product.category };` and your last solution is perfectly fin to use and the need to cast the property into `any` before assigning it is not a big deal.

**Comment by pleerock** [comment]
no, it won't confuse anything.

You can do:

```ts
product.categoryId = product.category.id;
```

or 

```ts
product.category = product.category;
```

to persist your relation and everything will work fine and typesafe.

**Comment by codeartch** [comment]
Should this way of declaring an association still work with the newly introduced Insert Query Builder?

`product.category = { id: 1 };`

It works the way it's described above, but not with the Query Builder. In my case i used a many-to-many relation.

**Comment by pleerock** [comment]
@codeartch can you provide a complete example?

**Comment by codeartch** [comment]
Because of our project timeline i had to move on with the Repository.save(data) solution. Sadly i dont have the code of my first query builder attempt anymore, sorry.

I can share some more info though:
`
var data = {
  name: 'itemA',
  users: [{id: 1}]
}
`

`mySelectQueryBuilder.insert().into('items').values(data).execute();`

I replaced the query builder code with this one, and it works as expected.

`db.getConnection().getRepository('items').save(data);`

**Comment by pleerock** [comment]
InsertQueryBuilder is used to perform a SINGLE INSERT OPERATION. Its purpose to create a single insertion. But your requirement is a way complex and requires multiple operations. That's why you can't do it with insert query builder, either you need to use a complex solution - `save` method, either you need to create multiple insert queries for all the data you want to insert

**Comment by Can-Sahin** [comment]
This approach doesn't work when you wanna update the entity with the id

```typescript
let product = await productRepository.findOneById(someId);
product.categoryId = 2;

await productRepository.save(product)
```

This creates the following sql update statement 
```
query failed: UPDATE `product` SET `categoryId` = ?, `categoryId` = ?  WHERE `id` IN (?)'
```
`categoryId` is duplicated here for some reason and statement crashes with `ER_PARSE_ERROR`

@pleerock

**Comment by velociraptor111** [comment]
> you can add categoryId right to the product as a column and use it:
> 
> ```ts
> @Entity()
> class Product {
> 
>      @Column({ type: "int", nullable: true })
>      categoryId: number;
> 
>      @ManyToOne(type => Category)
>      @JoinColumn({ name: "categoryId" })
>      category: Category;
> 
> }
> ```
> 
> Then you can assign `categoryId` each time you want to set a relation and it will work as you expect.

Does anyone knows how we can achieve this in a ManyToMany relationship? 

So for example rather than categoryId we want to store categoryIds ?

**Comment by bestickley** [comment]
@velociraptor111 From my research, it's not possible. But assuming you have `categoryIds: number[]` I think you could map the ids to an object with just ids `product.category = categoryIds.map(id => ({ id }))` and then save the product.

**Comment by velociraptor111** [comment]
Yes this is what I ended up doing as well. Thanks!

**Comment by luismasserral** [comment]
> you can add categoryId right to the product as a column and use it:
> 
> ```ts
> @Entity()
> class Product {
> 
>      @Column({ type: "int", nullable: true })
>      categoryId: number;
> 
>      @ManyToOne(type => Category)
>      @JoinColumn({ name: "categoryId" })
>      category: Category;
> 
> }
> ```
> 
> Then you can assign `categoryId` each time you want to set a relation and it will work as you expect.

I know this was closed long time ago but I'm using this solution right now and I had a problem being forced to update both `category.id` and `categoryId` or the update was not working fine.

@pleerock based on this, what would happen if you have a product with a category that has id 1, and then you change its `categoryId` to 2 and save it?

```js
product.categoryId = 2;

this.repository.persist(product);
```

At the `persist` point, the `categoryId` of the product is 2, but the `category` object is the one with id 1. How does `typeorm` know which field is the good one, the `categoryId` or the `category`?

**Comment by GarryOne** [comment]
The current implementation doesn't make so much sense to me and even affect the performance considerably, as far as I understand.

So for each insert/update query on models that has relations, I need to make additional queries to fetch those relations objects which I don't need actually (I need only the IDs), just to be able to make the update?

So, If I want to update a model, that has, for example, 5 relations. That means that on every insert/update I need to make other 5 additional queries, every time!?

Could someone explain to me the logic behind it?
Thanks.

**Comment by lassemt** [comment]
> @velociraptor111 From my research, it's not possible. But assuming you have `categoryIds: number[]` I think you could map the ids to an object with just ids `product.category = categoryIds.map(id => ({ id }))` and then save the product.

Thanks @bestickley, this worked like a charm! I feel like this should be in the docs somewhere.

**Comment by alanscordoba** [comment]
I had this same problem and leave it to solve it in case it works for someone

  `@ManyToOne(type => Category, {
      cascade: true,
      nullable: false,
    })`

    @JoinColumn({name: "idcategory"})
    provincia: string;
    
    @Column()
    @IsNotEmpty()
    idcategory: number;

**Comment by MSohailMemon** [comment]
@pleerock I have encountered a weird issue. If we try to update with product.category = category, the SQL's update command append categoryId=[?] twice, which causes the command to be failed. 
![image](https://user-images.githubusercontent.com/16705547/106360631-61cd5900-633b-11eb-9b0d-dbedc181745d.png)


> no, it won't confuse anything.
> 
> You can do:
> 
> ```ts
> product.categoryId = product.category.id;
> ```
> 
> or
> 
> ```ts
> product.category = product.category;
> ```
> 
> to persist your relation and everything will work fine and typesafe.

**Comment by binki** [comment]
@MSohailMemon I don’t see the multiple categoryId. Am I blind? Could you share the code you are using?

It sounds like you’re issuing a command but it isn’t sending parameters properly…?

**Comment by MSohailMemon** [comment]
> @MSohailMemon I don’t see the multiple categoryId. Am I blind? Could you share the code you are using?
> 
> It sounds like you’re issuing a command but it isn’t sending parameters properly…?

@binki actually its "delegate_contact_person_organization_id" in my case. I just referred to categoryId to continue with the example that was being discussed in comment. 

Following is my organization entity:
   
   @Column({ name: "delegate_contact_person_organization_id", nullable: true }) 
   delegateContactPersonOrganizationId: number;

   @ManyToOne(() => ContactPersonOrganization)
   @JoinColumn({ name: "delegate_contact_person_organization_id" })
   delegateContactPersonOrganization?: ContactPersonOrganization;

Now when I fetch organization object using find, then update delegateContactPersonOrganization and then orgRepository.update(id, {organizationObj}), it tries to set delegate_contact_person_organization_id twice.

**Comment by aardvarkk** [comment]
I believe this works now with the following style:

```
product.category = <any>theRelationId;
```

It's weird because all the stuff above seems to point you in the direction of adding new `RelationId` columns (which I felt was ugly), and it's also said that setting `product.category = { id: theRelationId };` will work, which it doesn't seem to for me. 

However, when *directly setting the relation to just the relation ID that I wanted*, it worked. **Don't** set it to an _object containing the ID_ but the ID itself and you should be good.

Strange.

**Comment by ronen-agranat** [comment]
@aardvarkk That works for me... strange, indeed. Thanks for this!

```typescript
    minutes.person = personId as any; // Type of personId is number; type of person is Person
```

 I am concerned though that this may break in the future, so it would be good to get a definitive answer on this.

It would be great if you could say personId and TypeORM would recognise that it's setting the relation id directly, like Ruby on Rails and ActiveRecord. Doesn't seem too difficult or controversial to me; what do you think?

**Comment by Deel96** [comment]
The solution with any does not work for me but I would love to see this features, since it saves a lot of code.

**Comment by craftsman01** [comment]
Using Typeorm with NestJs and the solution with any is working for me, but I was curious if this is intended or will it break in a future version.

**Comment by uranderu** [comment]
> @velociraptor111 From my research, it's not possible. But assuming you have `categoryIds: number[]` I think you could map the ids to an object with just ids `product.category = categoryIds.map(id => ({ id }))` and then save the product.

Tysm! For everybody using TS and not knowing, if you want to use this you need to prefix it with `<any>`

**Comment by OlteanuCosmin** [comment]
> you can add categoryId right to the product as a column and use it:
> 
> ```ts
> @Entity()
> class Product {
> 
>      @Column({ type: "int", nullable: true })
>      categoryId: number;
> 
>      @ManyToOne(type => Category)
>      @JoinColumn({ name: "categoryId" })
>      category: Category;
> 
> }
> ```
> 
> Then you can assign `categoryId` each time you want to set a relation and it will work as you expect.

@pleerock How can this be achieved for a @ManyToMany relationship?

Adding a new entity in a ManyToMany using only the ID, can be done as you said with an array of `new Category().id`. Can we avoid the object and just send the plain string ID as in @ManyToOne? Thanks!

**Comment by StephanBis** [comment]
@OlteanuCosmin I'm very curious aswell, we are using multiple _manytomany_ relations and are running into the same problem. Setting the IDs instead of objects doesn't seem to work anymore.

**Comment by Gilmar-Gomes** [comment]
> @OlteanuCosmin I'm very curious aswell, we are using multiple _manytomany_ relations and are running into the same problem. Setting the IDs instead of objects doesn't seem to work anymore.

Same to me. Using in a ManyToOne, sets null the relation field

**Comment by stouch** [comment]
Is https://github.com/typeorm/typeorm/issues/447#issuecomment-298896602 the official answer to this thread ? Thanks to him actually because it saved us in many of our entities. But why this issue has been closed while it is an obvious missing feature?

**Comment by benwiley4000** [comment]
> @velociraptor111 From my research, it's not possible. But assuming you have `categoryIds: number[]` I think you could map the ids to an object with just ids `product.category = categoryIds.map(id => ({ id }))` and then save the product.

Unfortunately this causes problems with TypeScript and requires a typecast. There should be an option to pass a string array of ids to avoid having to lie to TypeScript.
