### ISSUE TITLE
Can't build 0.2.18

### ISSUE THREAD

**Issue by davewasmer** [typeorm/typeorm#4481]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18`
[x] `master`

**Steps to reproduce or a small repository showing the problem:**

Trying to follow the `DEVELOPER.md` instructions to get a local copy of the repo up and running, I'm getting TS compilation errors with 0.2.18 and with master.

There's 1000+ errors from `node_modules` - those don't seem to impact the resulting build though (see #4480). But there's 4 errors I'm seeing:

```sh
$ git clone typeorm/typeorm
$ yarn
$ cp ormconfig.json.dist ormconfig.json
$ yarn package
# ... snip ...
src/entity-manager/MongoEntityManager.ts(576,47): error TS2339: Property 'where' does not exist on type 'FindManyOptions<Entity> | Partial<Entity>'.
  Property 'where' does not exist on type 'Partial<Entity>'.
src/entity-manager/MongoEntityManager.ts(578,39): error TS2339: Property 'where' does not exist on type 'FindManyOptions<Entity> | Partial<Entity>'.
  Property 'where' does not exist on type 'Partial<Entity>'.
src/query-builder/ReturningResultsEntityUpdator.ts(72,88): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'DeepPartial<ObjectLiteral>'.
src/query-builder/ReturningResultsEntityUpdator.ts(73,57): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'ObjectLiteral'.
TypeScript: 4 semantic errors
TypeScript: emit succeeded (with errors)
[11:06:34] 'packageCompile' errored after 14 s
```

The `build/package` folder is empty. Did I miss an environment setup step, or was 0.2.18 published with these type errors? If the latter - did you follow a separate procedure to get it to build with those errors?

I ask because I need to publish my own copy of TypeORM (until a new version is published) to get a recent PR that landed on master but hasn't yet been released (#4230).

**Comment by VLZH** [comment]
I have the same problem.

**Comment by imnotjames** [comment]
Typescript issue, not related to TypeORM.
