### ISSUE TITLE
Event subscribers not affecting abstract entities

### ISSUE THREAD

**Issue by nevodavid** [typeorm/typeorm#449]
Tried to create a new abstract entity with created_at and updated_at to be automatically update on change, it's not working, only if I put the columns in the entity itself.

btw, is there any built in soft deletes?

**Comment by pleerock** [comment]
> btw, is there any built in soft deletes?

no

> Tried to create a new abstract entity with created_at and updated_at to be automatically update on change, it's not working, only if I put the columns in the entity itself.

they should work. Did you include your abstract entity in the `entities` of the configuration?

**Comment by nevodavid** [comment]
Thanks! that was the issue,
is there any why I can put global condition on each entity so I can add for example
"deleted_at" is null?

**Comment by pleerock** [comment]
no there is no such way, put your queries always if you need this.
