### ISSUE TITLE
How can I enable mysql from browser / angular app

### ISSUE THREAD

**Issue by spiotr12** [typeorm/typeorm#4490]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Question**

How can I use connection to mysql or postgres database directly from browser/angular frontend. I know it might make no sense but I still would like to know.

Thanks!

**Comment by Kononnable** [comment]
You can't do that probable because of - https://github.com/defunctzombie/package-browser-field-spec. You would have to override those settings somehow(or download typeorm repo, make changes locally and use locally build package).

**Comment by imnotjames** [comment]
As far as I can tell - there's also no MySQL or Postgres driver that works in a browser context. 

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
