### ISSUE TITLE
one to one relation - can't use repository find on inverse side

### ISSUE THREAD

**Issue by Lennard-Dietz** [typeorm/typeorm#4492]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

As stated in the [documentation](https://github.com/typeorm/typeorm/blob/master/docs/one-to-one-relations.md), resolving a one-to-one relation on the inverse side (the one that doesn't save the id in the database), is done by using the `QueryBuilder`.

However, when trying to use `findOne` of the related `Repository` instead, for example when searching the profile of a specific user:
```ts
const profiles = await connection.getRepository(Profile).findOne({user: theUserOfTheProfile});
```
we will always get the first `profile` from the database, opposed to the one related with the `user`. The resulting sql query that was send to the database does not contain any of the user parameters.

This can lead to very unexpected results.

**Comment by LuisAngelMoralesRomo** [comment]
Can you post your entities `Profile` and `User`?

**Comment by Kononnable** [comment]
Closing as no response from the author.
