### ISSUE TITLE
Excessive memory usage when loading models with relations

### ISSUE THREAD

**Issue by nikolovjd** [typeorm/typeorm#4499]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

If I load a list of models like this:

```ts
const models = await this.modelRepository
  .createQueryBuilder('model')
  .innerJoinAndSelect('model.relationshipA')
  .innerJoinAndSelect('model.relationshipB')
  .innerJoinAndSelect('model.relationshipC')
  // etc
  .getManyAndCount();
```
With many elements (100 in my case) it gets up to 2+ GB of memory usage for the query, where if i load the model by itself, and then make separate queries for each relationship such as:

```ts
  const galleries: Gallery[] = await relationshipAModel.createQueryBuilder('model')
          .leftJoinAndSelect('model.subRelationshipA', 'a')
          .leftJoinAndSelect('model.subRelationshipB', 'b')
          .whereInIds(firstResultIds)
          .getMany();
```

And then map the results to the original list, the memory footprint is not even noticeable.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by dyatko** [comment]
Confirming the same experience using mysql driver

**Comment by Kononnable** [comment]
Could you provide reproduction repo? It will be much easier to see what's eating this memory.

**Comment by thellimist** [comment]
I have the same issue. I left join 7 relations. The total size of the returned object is 2MB, however, typeorm uses 1 - 2GB memory

**Comment by tangb** [comment]
Same problem too. My server instance kicks my program every time the request consumes a certain amount of memory. My workaround is to remove leftJoin and put together all my data frontend side requesting multiple times my backend... not the best but it works.

**Comment by HansG89** [comment]
I can confirm this issue in my environment (NestJS + TypeOrm + Postgres).
When joining 5 tables with conditions (inner join and left join), nodejs takes more than 4gb of memory. The query is not that complex and the result should only have about 2.500 entries.
Increasing nodejs max old space size prevents the process from crashing but thats not a solution for a production environment.

**Comment by AmauryD** [comment]
Same problem here, typeorm with mysql makes an out of memory on my server when joining a lot of relations. Even if they are not a lot of records in my database.

**Comment by thellimist** [comment]
@pleerock any updates

**Comment by jd1386** [comment]
Just experienced the same memory leak in NestJS/TypeOrm/Postgres. I'd really love to know if there're any way as to fix this.

**Comment by yj-ang** [comment]
I'm having the same problem.  (NestJS + Typeorm + mysql driver)

**Comment by AuspeXeu** [comment]
Same problem typeorm + pq driver I cannot even select 100 rows?!

**Comment by guyisra** [comment]
any updates on this?

**Comment by bogdan** [comment]
In other ORMs, preloading of associations using join is not considered a default way. The best way is to use a separated query for each relations and only use join for specific reasons. This can be even better with `Promise.all` in node.

I would consider adding the same preloading schema into query builder as it is used in `find({relations}` where you just specify individual relations to be loaded as separated queries. It would allow to combine the flexibility of query builder with an adequateness of relations preloading. Even more advanced ORMs allow you to preload associations into objects like:

```
const posts = Post.findAll()
Preloader.preload(posts, 'category')
// where category is an association of Post`
```

**Comment by gfborges** [comment]
Any updates on this issue ?

**Comment by dborisenkowork** [comment]
I experience such issues even without relations. Memory usage is out of control

**Comment by GP4cK** [comment]
The problem with loading multiple relations is that TypeORM will make one `SELECT` query with several `JOIN`s which will return a lot of duplicated line, and then aggregate the results nicely for you.

Ex: Let's say that in your table `model`, you have 100 records. Then for each record in `model`, you have 10 records in relationship A, B & C, the `SELECT` query with 2 JOINs will return 100 x 10 x 10 x 10 = 100,000 lines.  

The best solution I've found so far is to write a custom query with nested `SELECT`s and use `json_agg` to aggregate the relations.
I've also created a question on StackOverflow [here](https://stackoverflow.com/questions/65649628/how-to-load-multiple-one-to-many-relations-in-typeorm-postgresql). Maybe there's a better approach...

**Comment by cdalton713** [comment]
any fixes to this?

**Comment by rpurdon-nf** [comment]
Still waiting for updates on these issues? How can it be that a ORM is using so much memory to do a simple query? We have a ECS task with 6gigs of memory and it cannot even load a the query with three relations, and the main table only has like 1200 records. 

Anyone else that can suggest a better ORM for teams to use that do not kill a container each time a simple query is done.

**Comment by jjhbw** [comment]
@rpurdon-nf I've been using [mikro-orm](https://mikro-orm.io) for a while, and I like it. It takes some getting used to because it uses the identity map pattern, but that's what allows it to spit out very efficient SQL.

**Comment by bogdan** [comment]
Loading relations with a join instead of separated queries for each relation is a doomed strategy: If you load 10 entities with 3 relations and each of them 10 records on average, that is 10000 result set returned.

That is why most ORM prefer separated queries as a default relations loading strategy and only allow preloading with joins as an option. With javascript `Promise.all` out of the box, separated queries can be even faster loading strategy than complex join.

**Comment by hungnv-zinza** [comment]
when will this issue  be resolved

**Comment by Jtosbornex** [comment]
I just wanted to add that I was having this same issue. I couldn't load more than 4 rows without a hitting 2.5gb of RAM and making my server crash. This could have been a combination of both nestjsx and typeorm.

I ended up rewriting the query with parallel joins where possible and RAM usage went to imperceptible levels. The speed of the request speed up by orders of magnitude as well. This was a significant change.

I don't know the proper terminology but I highly recommend parallel joins being on the radar of future development.

**Comment by liteultom** [comment]
One more person with this issue.

**Comment by t2y** [comment]
I have the same issue. I'm debugging now. I took some heap snapshots in Chrome DevTools. 

![image](https://user-images.githubusercontent.com/96569/123515255-8bfc2a80-d6d1-11eb-816b-f18d7e8eaed2.png)

My table entity called `Trial` and confirmed `Retained size` is large even if it doesn't get a relation table's data. My table entity has 9 lazy relations. In my debugging, I found one reason consuming heap memory. That is: `enableLazyLoad()` sets properties of getter/setter for relation table. It consumes the heap memory for each entity. I wonder whether setting many lazy relations consumes large memory.

* https://github.com/typeorm/typeorm/blob/0.2.32/src/metadata/EntityMetadata.ts#L533
* https://github.com/typeorm/typeorm/blob/0.2.32/src/query-builder/RelationLoader.ts#L186

**Comment by liteultom** [comment]
It's not a fix, as my solution does not provide exactly the same features as the original, but I wrote a custom generic repository that builds its own queries and has a much lower memory usage. If this can be of use to somebody while waiting for an official (and better) fix.

First, wrote 2 utility methods to generate queries: 
- `autoQueryBuilder()` will take a target class, conditions, metadata of the target class and options (only allows for `depth` for now) and will return a query that should satisfy the conditions and have every entity hydrated as deep as the `depth` option is set.
- `recursiveQueryBuilder()` is charge of writing the "joins" part of the query, going as deep as the `depth` option requires.

*Note :* you don't really need `lodash` or `config` here. `lodash` is only used to check for an empty object and `config` for a default value for the `depth` option.

```
import config from 'config'
import _ from 'lodash'
import { FindOptionsUtils } from 'typeorm'

export function autoQueryBuilder (targetClass, conditions, metadata, opts) {
  const qb = targetClass.createQueryBuilder(metadata.tableName)

  if (!_.isEmpty(conditions)) {
    FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder(qb, conditions)
  }
  if (!opts.depth) {
    opts.depth = config.get('db.autoJoinDepth')
  }
  if (metadata.relations.length) {
    recursiveQueryBuilder(qb, metadata, opts.depth, metadata.tableName)
  }

  return qb
}

/**
 *
 * @param {*} qb: query builder object
 * @param {*} metadata: metadata of the current entity
 * @param {*} depth: depth of join to link from here
 * @param {*} tableName: name of the current table
 * @param {*} parentClassName: name of the parent class
 * @returns a query builder object with all joins up to the depth given in param,
 *
 * WARNING: for now, it automatically excludes relations ship that are the same
 * type as the parent in order to avoid repeated information. Maybe this will
 * need to be modified later (if necessary)
 */
export function recursiveQueryBuilder (qb, metadata, depth, tableName, parentClassName) {
  if (metadata.relations.length) {
    // count relations in order to have unique name for each
    // joined table
    let relationCounter = 0

    const relations = metadata.relations
      // remove relation that are the same type as the parent ( in
      // order to remove the parent itself. Maybe a modification will
      // be needed here later if it removes needed fields)
      .filter(r => !parentClassName || r.type !== parentClassName)
      // map relations in order to include the relationCounter
      .map(r => {
        relationCounter++
        return {
          field: r.propertyName,
          type: r.type,
          entityMeta: r.inverseEntityMetadata,
          relationCounter,
          tableName: (tableName || '') + r.propertyName.charAt(0) + relationCounter,
        }
      })

    // Add needed joins
    relations.forEach(r => {
      qb.leftJoinAndSelect(`${tableName}.${r.field}`, r.tableName)
    })

    if (depth > 0) {
      // recursively add joins for deeper relations as long
      // as asked depth is > 0
      relations.forEach(r => {
        qb = recursiveQueryBuilder(
          qb,
          r.entityMeta,
          depth - 1,
          r.tableName,
          metadata.name,
        )
      })
    }
  }
  return qb
}
```

Then use these method in a custom repository:
```
import { EntityRepository, getConnection } from 'typeorm'
import { autoQueryBuilder } from '@/utils/dbUtils'

@EntityRepository()
class GenericRepository {

  manager
  metadata
  type

  constructor (manager) {
    this.manager = manager
  }

  setType (type) {
    this.type = type
    this.metadata = getConnection().getMetadata(this.type)
  }

  find (conditions, opts = {}) {
    return autoQueryBuilder(this.type, conditions, this.metadata, opts).getMany()
  }

  findOne (id, opts = {}) {
    return autoQueryBuilder(this.type, { id }, this.metadata, opts).getOne()
  }

  save (entity) {
    return this.manager.save(entity)
  }

}

export { GenericRepository }
```
*Drawback :* it does NOT inherit from the `Repository` class because doing so requires to specify the `type` of the entity, and I want to keep this repository generic. If needed, the `entityManager` is available to easily add useful methods such as `save(entity)`

And then to use the custom repository:
```
this.repository = getConnection().getCustomRepository(GenericRepository)
this.repository.setType(/*Your entity class here*/)

*This solution is not perfect* but it covers most of my needs and is easily customizable. The memory usage is divided by a factor of 30 to 50
```

**Comment by imnotjames** [comment]
Pretty sure this is a duplicate of #2381

**Comment by PhillipBSDL** [comment]
Simple single table selects seem to causing run away memory usage. This is pretty much unusable

**Comment by nabby27** [comment]
Any updates on this? Same problem typeorm + postgresql

**Comment by spotykatch** [comment]
Can someone please provide some tests for this? I can't reproduce it.

**Comment by vlad-healthhelper** [comment]
Happens for us on NestJS 8 and TypeORM 0.3.6

**Comment by justinoboyle** [comment]
Seems to be happening with us for NextJS 12.3.1 and TypeORM 0.3.9. Can we reopen this issue?

**Comment by visgotti** [comment]
It's bizarre how much faster loading entities by a foreign key is than using the native relations param... why does this happen?

**Comment by camilofelipe** [comment]
would using relationLoadStrategy: 'query' help? You can use it like this:

`em.find(Entity, {where: { ... }, relations: ['...'], relationLoadStrategy: 'query'})`

The value of relationLoadStrategy is 'join' by default.

**Comment by behzad1k** [comment]
setting the relationLoadStrategy to 'query' instead of join solved it for me thanks to @camilofelipe

**Comment by baochanh18** [comment]
> would using relationLoadStrategy: 'query' help? You can use it like this:
> 
> em.find(Entity, {where: { ... }, relations: ['...'], relationLoadStrategy: 'query'})
> 
> The value of relationLoadStrategy is 'join' by default.
This is very helpful. Thanks to @camilofelipe!

**Comment by arnab4477** [comment]
@camilofelipe Thank you, this finally fixed it for me. I just want to add that if you subsequently face the error `TypeError: Cannot read properties of undefined (reading 'propertyPath')` after making this change, make sure that you have set the relations both ways for the related entites.

Thanks to - https://github.com/typeorm/typeorm/issues/2283#issuecomment-748624563
