### ISSUE TITLE
Saving a relationship

### ISSUE THREAD

**Issue by Matt007** [typeorm/typeorm#450]
I'm probably just doing this wrong. I'm trying to add related object to another object through a many2many relationship.

Here's my scenario:

User->hasFriends [User] (many2many)
User->hasGroups [Group] (many2many)

When i want to add a group to a user I
1) fetch the respective user
2) left join the groups
3) fetch my respective group
4) push my group, user.addGroup(group)
5) persist my user object.

This works; but deletes all friend relationships. If I add a friend to my user; all group relationships get deleted.

Here are my model definitions:

User:

	require("reflect-metadata");
	import {Entity, PrimaryColumn, Column, ManyToMany, JoinTable} from "typeorm";
	import Group from './Group';
	
	
	@Entity()
	export default class User {
	
	    @PrimaryColumn("int", { generated: true })
	    id = undefined;
	
	    @Column("string")
	    email = "";
	
	    @Column("string")
	    firstname = "";
	
	    @Column("string")
	    lastname = "";    
	    
	    @Column("string")
	    middlename = "";
	    
	    @Column("string")
	    password = "";
	    
	    @Column("string")
	    salt = "";
	       
	    
	    setEmail(email) {
		    this.email = email;
		    return this;
	    }
	    
	    getEmail() {
		    return this.email;	    
	    }
	    
	    setFirstname(firstname) {
		    this.firstname = firstname;
		    return this;
	    }
	    
	    getFirstname() {
		    return this.firstname;
	    }
	    
	    setLastname(lastname) {
		    this.lastname = lastname;
		    return this;
	    }
	    
	    getLastname() {
		    return this.lastname;
	    }
	    
	    setMiddlename(middlename) {
		    this.middlename = middlename;
		    return this;
	    }
	    
	    getMiddlename() {
		    return this.middlename;
	    }
	    
	    setPassword(password) {
		    this.password = password;
		    return this;
	    }
	    
	    getPassword() {
		    return this.password;
	    }
	    
	    setSalt(salt) {
		    this.salt = salt;
		    return this;
	    }
	    
	    getSalt() {
		    return this.salt;
	    }
	    
	    addFriend(friend) {
		    this.friends.push(friend);
	    }
	
	    getGroups() {
		    return this.groups;
	    }
	    
	    addGroup(group) {
		    this.groups.push(group);
	    }
	    
	    getFriends() {
		    return this.friends;
	    }
	    
	    getFriendsInverse() {
		    return this.friends;
	    }
	    
	
		@ManyToMany(type => User, user => user.friendsInverse, {
			cascadeInsert: false,
			cascadeUpdate: false,
		})
		@JoinTable()
		friends = [];
	
		@ManyToMany(type => User, user => user.friends, {
			cascadeInsert: true,
			cascadeUpdate: true,
			cascadeRemove: false,
		})
		friendsInverse = [];
		
		
	    @ManyToMany(type => Group, group => group.users, {
	        cascadeInsert: true,
	        cascadeUpdate: true,
	        cascadeRemove: false
	    })
	    groups = [];
	    
	    
	}

Group:

	require("reflect-metadata");
	import {Entity, PrimaryColumn, Column, ManyToMany, JoinTable} from "typeorm";
	import User from './User';
	
	@Entity()
	export default class Group {
	
	    @PrimaryColumn("int", { generated: true })
	    id = undefined;
	
	    @Column("string")
	    title = "";
	
	    @Column("string")
	    description = "";
	
	    
	    setTitle(title) {
		    this.title = title;
		    return this;
	    }
	    
	    getTitle() {
		    return this.title;	    
	    }
	    
	    setDescription(description) {
		    this.description = description;
		    return this;
	    }
	    
	    getDescription() {
		    return this.description;
	    }
	
		@ManyToMany(type => User, user => user.groups, {
			cascadeInsert: true,
	        cascadeUpdate: true,
	        cascadeRemove: true
		})
		@JoinTable()
		users = [];
	    
	    
	}

-------

Is this the expected behaviour?

**Comment by pleerock** [comment]
Remove initializations from your model ` = []`. When you load object without friends and there is initialization orm thinks that you have remove all friends from your object and removes them. There is no way it can understand is it just initialized empty array or its empty because all entities were removed.

**Comment by Matt007** [comment]
Oh, makes sense! Thanks a lot for your help!

Maybe it would help to point this out in the example. I'm sure a lot of people might run into the same issue when they copy&paste the example from the docs.

**Comment by pleerock** [comment]
you are right, thanks.
