### ISSUE TITLE
inject data into transaction and extract it

### ISSUE THREAD

**Issue by abhijeet1403** [typeorm/typeorm#4500]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[x] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[x] `cockroachdb`
[x] `sqlite`
[x] `sqljs`
[x] `react-native`
[x] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Is there a way to inject data into and extract from a running transaction.
Usecase: I need it to save audit data, i.e. which logged in user changed what entity.
I retrieve which user is logged in using the jwt in req body, i want to attach it to transaction block when it starts and pull it inside the @beforeUpdate / @beforeCreate hook and save the audit data.

**Comment by imnotjames** [comment]
This would have to live outside of TypeORM.  We don't support specific business logic use cases.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
