### ISSUE TITLE
Is TypeORM for MongoDB Production Ready?

### ISSUE THREAD

**Issue by imomin** [typeorm/typeorm#4506]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am planning to use TypeORM for Mongodb in my next project. I've been playing around with TypeORM and MongoDB and I noticed there are many things that doesn't work. Examples,
1) @Column({select:false})
2) @Column({default:___})
3) OneToOne, OneToMany, ManyToOne and ManyToMany
4) createQueryBuilder or Aggregate

Do you guys recommend to use typeORM and MongoDB for real world application?

Please advice.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Binaryify** [comment]
mongodb's support is bad

**Comment by imnotjames** [comment]
If specific features don't work as expected, PRs are definitely accepted!  There are definitely projects using TypeORM and mongoDB in production.
