### ISSUE TITLE
Why is only QueryFailError exported?  It would be nice to export all the errors.

### ISSUE THREAD

**Issue by kedarmoghe** [typeorm/typeorm#4507]
**Issue type:**

[X] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm using custom repositories and I'm wondering if it would be possible to export all the specific errors.  For example, if a bad relation value is passed in, it would be nice to check that it is a FindRelationsNotFoundError (not currently exported) and I could throw my own custom error with an appropriate message.

**Comment by mgbarnech** [comment]
+1
In my case, I need to show a custom error when someone tries to sort by a column that does not exist.
At the moment a normal error is being thrown.

**Comment by Kononnable** [comment]
Error is exported, but not directly from index file. You can just use:
```typescript
import {FindRelationsNotFoundError} from "typeorm/src/error/FindRelationsNotFoundError"
```
