### ISSUE TITLE
Why is the Typeorm require the react-native-sqlite-storage module that is not using in my project?

### ISSUE THREAD

**Issue by chicrock** [typeorm/typeorm#4509]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi ~ 
When I using typeorm with Next.js react framework..
I got the warning message like this.

`./node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js
Module not found: Can't resolve 'react-native-sqlite-storage' in '/Users/chicrock/Documents/projects/node_modules/typeorm/browser/driver/react-native'`

I only use mysql database in my project.

why is typeorm load the `react-native-sqlite-storage` module unnecessary to me. 

Is this bug ? or something wrong to my usage ?

**Comment by Ginden** [comment]
> or something wrong to my usage ?

Almost certainly yes, because on my installation TypeORM doesn't even check for presence of `react-native-sqlite-storage` module.

**Comment by chicrock** [comment]
@Ginden Do you use in getInitialProps function on React NextJS framework ?
Could you explain some use case for me ?

**Comment by marcorinck** [comment]
The same happens when using typeorm in a Ionic4 project. 

Look at this example project: https://github.com/coturiv/ionic4-typeorm-starter
It has an install script to patch the ReactNativeDriver.js so that it does not try to require react-native-sqlite-storage. 

I don't know why this happens, but I know that TypeOrm only works with this patch in my personal Ionic4 testproject.

**Comment by chicrock** [comment]
@marcorinck Thanks !! It's work for me.

I think it's a temporary solution..
Is anybody knows why this happened ?

**Comment by Maus3rSR** [comment]
+1

**Comment by yuri-scarbaci-lenio** [comment]
I'm using next.js 9.2 with postgresql and I was affected by this too.

@marcorinck  solution works without any problem

in my case this created a problem of circular dependency and rejected promise without a catch

this is the log of the problem after I start the server that DOESN'T use sql-lite...

```
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
> Using external babel configuration
> Location: "/Users/{my-user}/path/to/project/.babelrc"
[ warn ]  ./node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js
Module not found: Can't resolve 'react-native-sqlite-storage' in '/Users/{my-user}/path/to/project/node_modules/typeorm/browser/driver/react-native'
[ info ]  ready on http://localhost:3000
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
[ warn ]  ./node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js
Module not found: Can't resolve 'react-native-sqlite-storage' in '/Users/{my-user}/path/to/project/node_modules/typeorm/browser/driver/react-native'
[ info ]  ready on http://localhost:3000
(node:15069) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'NormalModule'
    |     property 'dependencies' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'HarmonyCompatibilityDependency'
    --- property 'originModule' closes the circle
    at JSON.stringify (<anonymous>)
    at /Users/{my-user}/path/to/project/node_modules/webpack-hot-middleware/middleware.js:111:38
    at /Users/{my-user}/path/to/project/node_modules/webpack-hot-middleware/middleware.js:66:7
    at Array.forEach (<anonymous>)
    at everyClient (/Users/{my-user}/path/to/project/node_modules/webpack-hot-middleware/middleware.js:65:26)
    at Object.publish (/Users/{my-user}/path/to/project/node_modules/webpack-hot-middleware/middleware.js:110:7)
    at Function.middleware.publish (/Users/{my-user}/path/to/project/node_modules/webpack-hot-middleware/middleware.js:48:17)
    at HotReloader.send (/Users/{my-user}/path/to/project/node_modules/next/dist/server/hot-reloader.js:5:640)
    at /Users/{my-user}/path/to/project/node_modules/next/dist/server/hot-reloader.js:15:508
    at /Users/{my-user}/path/to/project/node_modules/next/dist/build/output/index.js:5:651
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:15069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

this is a really really weird and unexpected bug...

currently on
```
    "typeorm": "^0.2.22"
```

**Comment by chicrock** [comment]
👀

**Comment by jeromeSH26** [comment]
got the same issue trying to run typeorm in a react appli. What's wrong?```

	"dependencies": {
		"babel-loader": "^8.0.6",
		"dataloader": "^2.0.0",
		"express": "^4.17.1",
		"path": "^0.12.7",
		"pg": "^7.18.2",
		"react": "^16.12.0",
		"react-dom": "^16.12.0",
		"react-router": "^5.1.2",
		"react-router-dom": "^5.1.2",
		"typeorm": "^0.2.24",
		"uuid": "^7.0.2"
	},
```

**Comment by jmaister** [comment]
This has been fixed on next.js version 9.3.6. Just update it.

https://github.com/zeit/next.js/issues/8601

**Comment by chicrock** [comment]
@jmaister That does not work for me.
I thought the process of connection for the database in getInitialProps function may have some security problems.
So I changed the process to connect to the express server that connects the database using axios.

**Comment by jmaister** [comment]
getInitialProps is recommended to change getServerSideProps, so you can make a connection from that method. And not from the browser.
https://nextjs.org/docs/api-reference/data-fetching/getInitialProps

**Comment by chicrock** [comment]
@jmaister oh~ `Next.js 9.3 or newer`
I gonna upgrade my Next.js.
Thanks to replied

**Comment by nontoxice** [comment]
same here +1

`  "dependencies": {
    "axios": "^0.19.2",
    "debug": "^4.1.1",
    "fast-glob": "^3.2.2",
    "fastify": "^2.14.1",
    "fastify-cors": "^3.0.3",
    "js-cookie": "^2.2.1",
    "js-yaml": "^3.13.1",
    "lodash": "^4.17.15",
    "luxon": "^1.24.1",
    "moment": "^2.26.0",
    "mysql": "^2.18.1",
    "next": "^9.3.6",
    "nextjs-redirect": "^2.0.2",
    "nodemon": "^2.0.4",
    "nprogress": "^0.2.0",
    "react": "^16.13.1",
    "react-csv": "^2.0.3",
    "react-dom": "^16.13.1",
    "react-moment": "^0.9.7",
    "react-toastify": "^5.5.0",
    "semantic-ui-react": "^0.88.2",
    "socket.io": "^2.3.0",
    "socket.io-client": "^2.3.0",
    "styled-components": "^5.1.0",
    "ts-node": "^8.10.1",
    "typeorm": "^0.2.24",
    "uuid": "^3.4.0"
  },`

**Comment by tianyazjq** [comment]
![image](https://user-images.githubusercontent.com/5754329/91629371-2b418a00-e9fb-11ea-8932-19ff307cc200.png)

[0]
[0] WARNING in ./node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js
[0] Module not found: Error: Can't resolve 'react-native-sqlite-storage' in 'E:\wwwroot\ImPcMaster\pc-chat-master\node_modules\typeorm\browser\driver\react-native'
[0]  @ ./node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js
[0]  @ ./node_modules/typeorm/browser/driver/DriverFactory.js
[0]  @ ./node_modules/typeorm/browser/connection/Connection.js
[0]  @ ./node_modules/typeorm/browser/index.js
[0]  @ ./src/js/wfc/client/wfc.js
[0]  @ ./src/js/ui/stores/index.js


=======================

![image](https://user-images.githubusercontent.com/5754329/91629377-3eecf080-e9fb-11ea-927c-c8a69eaf31a4.png)

![image](https://user-images.githubusercontent.com/5754329/91629383-490eef00-e9fb-11ea-9859-0249e2d433c9.png)
 
i try to this methord to fixed this bug ,but not success !!!! somebody have other ideas ????

**Comment by imnotjames** [comment]
This is a warning.

You can ignore it, hide it, etc.  This is because of static analysis & because we ship all of our drivers as one bundle.

See #2318 for some efforts on splitting the packages up.

I'll be closing this, as there's nothing for us to do.

**Comment by muhaimincs** [comment]
> getInitialProps is recommended to change getServerSideProps, so you can make a connection from that method. And not from the browser.
> https://nextjs.org/docs/api-reference/data-fetching/getInitialProps

I use getStaticProps to prepare data for the page and still hit this error

**Comment by muhaimincs** [comment]
@tianyazjq did you manage to solve it?

**Comment by imnotjames** [comment]
> @tianyazjq did you manage to solve it?
> 
> @imnotjames it's not just warnings. I failed to build the project because of it

Are you importing from browser but are not in a browser context?

**Comment by pleerock** [comment]
@imnotjames actually there is such error when you use it in browser, at least I've seen it in one of my projects running typeorm in the browser (initially built with create-react-app) recently

**Comment by imnotjames** [comment]
> @imnotjames actually there is such error when you use it in browser, at least I've seen it in one of my projects running typeorm in the browser (initially built with create-react-app) recently 

I don't doubt it - it probably should be a different issue, though, shouldn't it?  With more info to replicate.  This was using MySQL and getting some definite weirdness where the react native code was getting loaded.  Then someone started talking about nextjs and now we're messin' with CRA. 😄

Long term, without finding a good way to split the drivers out & separate the browser bundle from the main package (mostly just omitting the nodejs only drivers?  Also stubbing some FS pieces..) there's always going to be trouble trying to use it isomorphic.

**Comment by ajmas** [comment]
Even if it is a warning, it is a little bothersome for those who prefer warning free builds.

Looking at the [source code](https://github.com/typeorm/typeorm/blob/137bec73f4a8d7c9c569492c670a2f0e501663d1/src/driver/DriverFactory.ts) it is likely because the file is explicitly imported, even if we aren't using it. Is there any reason why this couldn't be moved to a dynamic import, when the configuration indicates react is being used?

In fact, if we look at [ReactNativeDriver.ts](https://github.com/typeorm/typeorm/blob/master/src/driver/react-native/ReactNativeDriver.ts) the  dependency of `react-native-sqlite-storage` is loaded dynamically, so we should simply being doing the same thing for the driver itself?

```
    protected loadDependencies(): void {
        try {
            this.sqlite = require("react-native-sqlite-storage");

        } catch (e) {
            throw new DriverPackageNotInstalledError("React-Native", "react-native-sqlite-storage");
        }
    }
```

**Comment by imnotjames** [comment]
Why is it this but nothing else is having this problem

**Comment by ajmas** [comment]
If I have time I could look at this, but I wouldn’t want to put the effort unless the dev team are onboard. So far I haven’t seen any feedback from them here.

**Comment by danieloi** [comment]
> ignore it, hide it, etc. This is because of sta

you want to run npm/yarn install after specifying a new dependency shim

**Comment by eternalcomet** [comment]
@chicrock Hi everyone, I found a solution for that. I have read the `package.json` of typeorm, and found out that typeorm imports different libraries for different environment (node or browser). In some cases, we want to use database server-side, however, typeorm is seen as a client-side dependency, and it will assume it's under browser environment and require react-native packages. To handle this, just add this into your project's `package.json`:
```json
  "browser": {
    "typeorm": false
  }
 ```

**Comment by rejoanahmed** [comment]
> @chicrock Hi everyone, I found a solution for that. I have read the `package.json` of typeorm, and found out that typeorm imports different libraries for different environment (node or browser). In some cases, we want to use database server-side, however, typeorm is seen as a client-side dependency, and it will assume it's under browser environment and require react-native packages. To handle this, just add this into your project's `package.json`:
> 
> ```json
>   "browser": {
>     "typeorm": false
>   }
> ```

doesn't solve the issue for me. i removed all the node modules and pnpm lockfile. reinstalled it with that browser: typeorm:false setting. still the same issue. using next 14 with langchain js. 

```ts
import { RunnableSequence } from '@langchain/core/runnables'
import { SqlDatabase } from 'langchain/sql_db'
import { DataSource } from 'typeorm'

const dataSource = new DataSource({
  type: 'postgres',
  url: process.env.POSTGRES_URL
})
const llm = new ChatAnthropic({})
```
