### ISSUE TITLE
Select DISTINCT with COUNT

### ISSUE THREAD

**Issue by NoNameProvided** [typeorm/typeorm#451]
I must have miss something, but it seems I cannot get distinct values with their ammount with TypeORM.

Example:
```sql
SELECT "releaseDate", count("releaseDate") AS "product_count" FROM "product" WHERE "deleted" = false AND "isPublished" = false GROUP BY "releaseDate"
```

Which returns:

| releaseDate | product_count |
| ------------- | ------------- |
| 2017-05-02 13:00:00 | 2  |
| 2017-05-06 08:00:00  | 2  |
| 2017-05-08 12:00:00  | 1 |

**Comment by pleerock** [comment]
can you provide more details? Do you generate this query using raw sql or query builder? What do you expect to get - entity or raw data. I didn't understand your purpose at all

**Comment by NoNameProvided** [comment]
I am using it now with `repository.query` like:

```ts
await this.repository.query(`SELECT "releaseDate", count("releaseDate") AS "productCount" FROM "product" WHERE "deleted" = false AND "isPublished" = false GROUP BY "releaseDate"`)
```

My "problem" is that I dont see how can I achieve this via `QueryBuilder` if there is a way.

**Comment by pleerock** [comment]
I think its possible. But you need to get raw results using `getRawMany()`. Can you show the code you tried with query builder?

**Comment by NoNameProvided** [comment]
I tried with `getManyAndCount()`:
```ts
let products = await this.repository.createQueryBuilder('product')
      .where(`product.isPublished = 'false'`)
      .andWhere(`product.deleted = 'false'`)
      .groupBy("product.releaseDate")
      .getManyAndCount();
```

but it returns the following error: 

```json
{
  "name": "error",
  "message": "column \"product.id\" must appear in the GROUP BY clause or be used in an aggregate function",
  "length": 172,
  "severity": "ERROR",
  "code": "42803",
  "position": "8",
  "file": "parse_agg.c",
  "line": "1344",
  "routine": "check_ungrouped_columns_walker"
}
```
The generated query is quiet different from the one I wrote by hand:

```sql
SELECT "product"."id" AS "product_id", "product"."title" AS "product_title", "product"."description" AS "product_description", "product"."price" AS "product_price", "product"."releaseDate" AS "product_releaseDate", "product"."expirateionDate" AS "product_expirateionDate", "product"."videoUrl" AS "product_videoUrl", "product"."releaseCount" AS "product_releaseCount", "product"."isPublished" AS "product_isPublished", "product"."deleted" AS "product_deleted", "product"."createdAt" AS "product_createdAt", "product"."updatedAt" AS "product_updatedAt", "product"."version" AS "product_version", "product"."category" AS "product_category" FROM "product" "product" WHERE "product"."isPublished" = 'false' AND "product"."deleted" = 'false' GROUP BY "product"."releaseDate"
```

**Comment by pleerock** [comment]
this code is different thous solution is different. regarding for your first question you should do same but use `getRawMany()` instead. Regarding to second - its not orm error, its database or underlying driver error. Try to add group by by product.id too.

**Comment by NoNameProvided** [comment]
>  Try to add group by by product.id too.

How? For me it seems if I add multiple `groupBy` then only the last one is used.

> this code is different thous solution is different.

Yes, exactly. My problem is not how I can get the result with sql, but how express it via querybuilder if its possible.

 Product table:

|id |   category | release_date |
|--|-----------|------------------|
|1 |   1|              2017-06-26 08:00:00|
|2|    2|             2017-06-26 08:00:00|
|3|    2 |            2017-06-26 08:00:00|
|4|    1 |          2017-05-02 12:00:00|
|5|    2 |         2017-05-02 12:00:00|
|6|    1 |            2017-05-02 12:00:00|
|7|    1 |            2017-05-02 12:00:00|

```sql
select release_date, Count(*) from Products group by release_date
```

| release_date  | Count       |
| ------------- | ---------- |
| 2017-06-26 08:00:00 | 3 |
| 2017-05-02 12:00:00  | 4 |

This is what I want to express via query builder but I don't know how.

**Comment by pleerock** [comment]
there is a `groupBy` method and `addGroupBy`. First overrides all previous. If you want to add a new - use `addGroupBy` method.

To generate `select release_date, Count(*) from Products group by release_date` you can do something like this:

```ts
let results = await this.repository.createQueryBuilder('product')
      .select("product.releaseDate AS release_date")
      .addSelect("COUNT(*) AS count")
      .groupBy("product.releaseDate")
      .getRawMany();
```

**Comment by NoNameProvided** [comment]
That is what I wanted, thanks!
