### ISSUE TITLE
Failed to parse: filter...

### ISSUE THREAD

**Issue by freevital** [typeorm/typeorm#4516]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18`

**Steps to reproduce or a small repository showing the problem:**

```ts
// my-migration.ts
public async down(queryRunner: QueryRunner): Promise<any> {
    const usersRepository = queryRunner.connection.getMongoRepository(User);
    
    const entities = await usersRepository.find({
        where: [
            { email: 'admin@example.com' },
            { email: 'manager@example.com' }
        ]
    });
   await usersRepository.remove(entities);
}
```

I get an error with conditions: `.find({ where: [...] })`. 
```
// Error
{ MongoError: Failed to parse: filter: [ { email: "admin@example.com" }, { email: "manager@example.com" } ]. 'filter' field must be of BSON type object.
    at Connection.<anonymous> (/Users/kravchyshyn/Projects/chill-chicago/api/node_modules/mongodb/lib/core/connection/pool.js:466:61)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at processMessage (/Users/kravchyshyn/Projects/chill-chicago/api/node_modules/mongodb/lib/core/connection/connection.js:364:10)
    at Socket.<anonymous> (/Users/kravchyshyn/Projects/chill-chicago/api/node_modules/mongodb/lib/core/connection/connection.js:533:15)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
  ok: 0,
  errmsg:
   'Failed to parse: filter: [ { email: "admin@example.com" }, { email: "manager@example.com" } ]. \'filter\' field must be of BSON type object.',
  code: 9,
  codeName: 'FailedToParse',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
```
How can I resolve it?

**Comment by rustamwin** [comment]
Use object condition.
```javascript
const entities = await usersRepository.find({
        where: {
            ....
        }
    });
```

**Comment by freevital** [comment]
> Use object condition.
> 
> ```js
> const entities = await usersRepository.find({
>         where: {
>             ....
>         }
>     });
> ```

And how can I

**Comment by freevital** [comment]
> Use object condition.
> 
> ```js
> const entities = await usersRepository.find({
>         where: {
>             ....
>         }
>     });
> ```

I need to use `OR` condition as { where: [condition1, condition2] }

**Comment by rustamwin** [comment]
> I need to use OR condition as { where: [condition1, condition2] }

Try this
```javascript
const entities = await usersRepository.find({
        where: {
            $or: [condition1, condition2]
        }
    });
```

**Comment by Anissa-BH** [comment]
But  if we are using TypeORM, $or can't work, we should use the syntax  where: [{condition1}, {condition2}]

**Comment by Yassine-Ezzedini** [comment]
this gives me trust issues, can someone explain why did this error appear ? i had the exact same one, i solved it by using $or, but i wanna understand why ?
