### ISSUE TITLE
[Discussion] Use version column as a hint to insert vs update

### ISSUE THREAD

**Issue by thynson** [typeorm/typeorm#4517]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I notice that when creating new entity and assign an id to it before persistence,  TypeORM will perform select before insert when saving the newly-created entity. 

I understand that when id (or primary key) is presented on an entity, TypeORM has no context to know whether it should create or update an entity. 

Since TypeORM already support version column, I came up an idea that by using null-version as a hint to executor to perform insert directly. I think this is reasonable:
1. The purpose of version column is used prevent concurrent modification, while insert is a kind of modification. 
2. Null-version is more acceptable when null-id. Null-id prevent the program to create related entities before persistence, while null-version does not.

**Comment by Kononnable** [comment]
Not everyone wants to add version column to all of their tables - it's optional functionality, that's why it can't be used to do something as crucial as deciding either record should be inserted or updated.
You might want to use `insert` method, but be aware of its limitations(no cascades etc.).
