### ISSUE TITLE
How to retrieve ObjectID from another Entity/Subdocument

### ISSUE THREAD

**Issue by mehmetnyarar** [typeorm/typeorm#4520]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the two entities: `User` and `Review`, and `Provider` sub-document which stores `ObjectID`s of `Review`s on `reviews` field.

```ts

@Entity({ name: 'users' })
export class User extends BaseEntity {
  @Field(() => ID)
  @ObjectIdColumn()
  readonly id: ObjectID

  @Field(() => Provider, { nullable: true })
  @Column(() => Provider)
  provider?: Provider
}

@Entity({ name: 'reviews' })
export class Review extends BaseEntity {
  @Field(() => ID)
  @ObjectIdColumn()
  readonly id: ObjectID
}

@ObjectType()
export class Provider {
  @Field(() => [Review]) // GraphQL should return an array of Review objects
  @Column(() => X) // ObjectIDs are stored. Which type should I return?
  reviews: Y[] // Which type it should be?
}
```

As it makes sense to me, I've tried the followings:

```ts
  @Field(() => [Review])
  @Column(() => ObjectID)
  reviews: ObjectID[]

  @Field(() => [Review])
  @Column(() => ObjectID)
  reviews: Review[]
```

both gives the same error `Cannot convert undefined or null to object`.

What should I do?

**Comment by mehmetnyarar** [comment]
Somehow it worked like this:

```ts
  @Field(() => [Review])
  @Column() // () => ObjectID doesn't work
  reviews: ObjectID[]
```

but I'm not sure whether it's the correct way or not. This was the only retrieve part of the thing, let's see when it comes to save...

**Comment by mehmetnyarar** [comment]
I wanted to test the code in production mode. Removing `ObjectID` worked in dev mode, however I receive en error in production.

```ts
@Entity({ name: 'workorders' }) {
  @Field(() => Service)
  @Column()
  service: ObjectID
}
```

> /<root>/src/error/ColumnTypeUndefinedError.ts:9
        super();
        ^
ColumnTypeUndefinedError: Column type for Workorder#service is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.

If I keep `ObjectID`, this time I receive error in dev mode:

> MONGO ERROR { ex:
   TypeError: Cannot convert undefined or null to object
       at Function.getPrototypeOf (<anonymous>)
       at getPrototypeOf (/<root>/src/metadata-builder/MetadataUtils.ts:15:34)

What should I do, could you please suggest?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
