### ISSUE TITLE
How to get the updated entity foreign key relation in afterUpdate subscription

### ISSUE THREAD

**Issue by mowaiskalam** [typeorm/typeorm#4521]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Problem Statement:**

Hi, I need to implement the audit trail of fields in my project. I am using the subscriber class and afterUpdate() method, I am able to get the changed entity but having a challenge about getting the foreign key value like if I change on the foreign key id in table the updated entity is showing the id value as change but I need the value so that I can display it as text and save it in my audit trail table without making an extra call to fetch the foreign key record.
And I cannot pass the custom value in that subscriber event, so is there anyway for getting the updated entity's foreign key entity as well in afterUpdate() method.

Can anyone guide me about the efficient way to manage this. Any help would be appreciated
Thanks in advance!

**Comment by Mando75** [comment]
Just to make sure I'm understanding correctly, you have the following scenario:

You have a relation like Book => Author, e.g.

```ts
@Entity()
class Book extends BaseEntity {
   @ManyToOne(() => Author)
   author: Author;
   // .. your other fields
}
```
this would create a foreign key column on the books table like `authorId`

You change the the author the book belongs to and want to capture the new author id via the subscriber? e.g.
```ts
book.author // returns Author with id = 1
book.author = aDifferentAuthor; // has id = 2
book.save() 
```

Assuming my understanding is correct, try the following.

I believe you should have access to the relation in your update subscriber.

```ts
// Book subscriber
afterUpdate(event: UpdateEvent) {
  const book = event.entity // entity should be a book
  const newAuthorId = book.author.id // this relation should be already loaded since you changed it
}
```

Another option is to just add the authorId as a column in your entity

```ts
@Entity()
class Book extends BaseEntity {
   @ManyToOne(() => Author)
   author: Author;
  
   @Column({
      type: "uuid", // or whatever your id type is
      nullable: false
   })
   authorId: string | number // whatever your id is
   // .. your other fields
}
```

Then as long as you are loading the column when loading your entity (via `find` or a query builder select), you should always have the foreign key available to you.

```ts
// Book subscriber
afterUpdate(event: UpdateEvent) {
  const book = event.entity // entity should be a book
  const newAuthorId = book.authorId 
}
```

Please let me know if I misunderstood you question. I'm not a maintainer, but I'd like to help if I can.

**Comment by mowaiskalam** [comment]
Thanks @Mando75 Appreciated it!

Yes, you are correct above but here is the problem like you said 'to add the authorId as a column in your entity', I have it and I am updating that and getting that as a change in afterUpdate() event

But I need the complete entity like this:
`
// Book subscriber
afterUpdate(event: UpdateEvent) {
  const book = event.entity // entity should be a book
  const newAuthorId = book.authorId // this is the foreignKey that is changed
  const newAuthor = book.author // this is foreignKey entity which I need because I want to extract the name of the author so that I can show it in my audit trail log i.e. book.author.name -> Author Name changed to {newAuthorName}
}
`
I am not getting the updated foreign key complete entity because I need to extract information from it. I can fetch the record from the foreign key table but I don't want to do because this subscriber can hit frequently whenever a changed happened in entity, so I need an efficient way to implement this.

I hope you understand my problem now. Thanks

**Comment by Mando75** [comment]
@mowaiskalam 
Yes that makes sense. The best way that I can see to get around that would be to load the entity before you save it.

Assuming you are doing something like the following:
```ts
const myBook = Book.find(myBookId) // you could also use the query builder for this
const myAuthor = Author.find(myNewAuthorId) 
myBook.author = myAuthor
myBook.save()
```

instead of setting the `authorId` property on the book, set the author

```ts
myBook.authorId = myNewAuthorId
myBook.save()
```

Performing the assignment on the relation field instead of the id field will still update the database column, but should also provide you with the loaded entity relation in your subscriber. This does assume that you have a relation set up similar to what I posted above:

```ts
@Entity()
class Book extends BaseEntity {
   // make sure the relation is defined... 
   @ManyToOne(() => Author)
   author: Author;
  
   @Column({
      type: "uuid", // or whatever your id type is
      nullable: false
   })
   authorId: string | number // whatever your id is
   // .. your other fields
}
```

```ts
// Book subscriber
afterUpdate(event: UpdateEvent) {
  const book = event.entity // entity should be a book
  const newAuthorId = book.author.id // this relation should be already loaded 
                                                               // if you set book.author before save
}
```

From my experience with TypeORM, I don't think there will be a way for you to access that entity data without loading it at some point. I agree that you should avoid loading it in your subscriber, which is why i suggest loading it beforehand and using it in the assignment.

**Comment by mowaiskalam** [comment]
Yeah @Mando75 Thanks!
Btw, do you know how this subscriber works like do they hit the database to get the database entity on `beforeUpdate()` and `afterUpdate()` method

```typescript
// Book subscriber
afterUpdate(event: UpdateEvent) {
  const book = event.entity // this is the entity which we pass on save() method
  const oldBook = event.databaseEntity // I also need to know how they fetch this, 
// do they hit the database before saving the record 
// because I am not seeing the query logs and couldn't find any query to fetch the previous record
// so how they do that?
}
```
The reason for asking this I really need to do my audit trail in an efficient way and I have a big entity to update and I don't want to make an extra calls.

**Comment by imnotjames** [comment]
You can always enable the debug logging, try it, and see.

Looks like this answered your question. Since it's been about a year since you asked the question and there wasn't any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
