### ISSUE TITLE
Boolean column being dropped then re-added during synchronization

### ISSUE THREAD

**Issue by aaronfulkerson** [typeorm/typeorm#4524]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

After seeding my database and allowing TypeORM to synchronize I was noticing an error about a column having a null value. According to the logger, TypeORM is trying to drop columns and then re-add them.

```
query: ALTER TABLE "tenant" DROP COLUMN "super"
query: ALTER TABLE "tenant" ADD "super" boolean NOT NULL
```

Here's the definition of the entity:

```TS
import { Entity, PrimaryGeneratedColumn, Column, OneToMany } from 'typeorm';
import { User } from '../users/user.entity';

@Entity()
export class Tenant {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column()
  super: boolean;

  @OneToMany(type => User, user => user.tenant)
  users: User[];
}
```

**Comment by aaronfulkerson** [comment]
I'm not sure if this would fall under "bug" or not but basically an old entity file in the dist folder was messing things up when TypeORM synchronized.

**Comment by sergamers** [comment]
@aaronfulkerson thanks so much for your advice!
