### ISSUE TITLE
Using User Defined Data Types

### ISSUE THREAD

**Issue by dpthayer** [typeorm/typeorm#4528]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

Does TypeOrm support complex data types such as arrays or UserDefinedTypes such as are found in postgres and many other DBS Systems?

**Comment by dpthayer** [comment]
You could have a decorator for a class such as @UDF allowing that class to now be used as a field type in a table.

**Comment by dpthayer** [comment]
Just discovered the Embedded Entities section of your docs.  This seems to answer all of my questions.  Sorry to bother everybody.
Great Product by the way.

**Comment by udf** [comment]
I'm not a decorator!

**Comment by dpthayer** [comment]
:)
