### ISSUE TITLE
can't filter createdAt field by date at all

### ISSUE THREAD

**Issue by d3vhound** [typeorm/typeorm#4529]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

server

```
.andWhere(
        req.query.startDate ? "workorder.requested_date >= :startdate" : "1=1",
        {
          startdate: req.query.startDate
        }
      )
      .andWhere(
        req.query.endDate ? "workorder.requested_date < :enddate" : "1=1",
        {
          enddate: req.query.endDate
        }
      )
```

client

```
fetchOrders(
        moment(dates[0])
          .endOf("day")
          .toISOString(),
        moment(dates[1])
          .startOf("day")
          .toISOString()
      )
```

I don't understand what I'm doing wrong? surely you can filter based on createdAt with querybuilder?

**Comment by Kononnable** [comment]
Please provide reproduction repo/failing test. Without knowledge of your codebase there is no way to tell what exactly are you doing, how your table schema looks like etc.
