### ISSUE TITLE
Connect using Active Directory account

### ISSUE THREAD

**Issue by StickNitro** [typeorm/typeorm#453]
Hi, this is a question really, is it possible with typeorm to connect to an MSSQL database using a Windows Active Directory account? In other words is it possible to specify the DOMAIN with the connection either separately or with the username?

for example:
```
{
  username: "test.user",
  password: "...",
  domain: "mydomain"
}
```
or
```
{
  username: "mydomain/test.user",
  password: "..."
}
```

I am looking at options for using an ORM in an upcoming NodeJS service but one of the caveats is that we must use a Windows Domain account to connect to the database (we cannot use an sql account)

**Comment by pleerock** [comment]
Im not familiar with sql-server specific options, so I can't answer your question. Orm uses [this underlying driver](https://github.com/patriksimek/node-mssql) which is responsible for the whole connection. Probably you can ask them if they are supporting what you are talking about?

**Comment by StickNitro** [comment]
Hi,

It is supported on the referenced driver, you can include a ```"domain": "mydomain"``` property when connecting to mssql.

From looking at the driver code in the repository it looks like this is not included in the ```ConnectionOptions``` or ```DriverOptions``` types and is therefore not catered for in the ```SqlServerDriver```.

I can take a look at this and see if I can get a PR together to include this option.

**Comment by pleerock** [comment]
you can do this:

```json
[
  {
    "name": "default",
    "driver": {
      "type": "mysql",
      "host": "localhost",
      "port": 3306,
      "username": "xxxx",
      "password": "xxxx",
      "database": "xxxx",
      "extra": {
           "domain": "mydomain"
      }
    },
    "autoSchemaSync": true
  }
]
```
