### ISSUE TITLE
Is it possible to use the same database connection for multiple files?

### ISSUE THREAD

**Issue by camero2734** [typeorm/typeorm#4530]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I am trying to use the same database in two files at the same time. I am using the following JavaScript to create the connection:
```js
let connection = await typeorm.createConnection({
    type: "sqlite",
    database: "database.sqlite",
    synchronize: true,
    logging: false,
    entities: entities
});
```
Is there a way to share the same connection between two files?

Edit: Just as clarification, I mean across two separate processes, not across modules.

**Comment by Kononnable** [comment]
You want to share JS objects between two completely different processes? No, it's not possible on a language/platform level(or at least there is no easy/nice solution for that). You have to create separate connections.

**Comment by veluxa** [comment]
You many get useful information for this page : [using-multiple-databases-in-a-single-connection](https://typeorm.io/#/multiple-connections/using-multiple-databases-in-a-single-connection)
