### ISSUE TITLE
clear method not resets AUTO_INCREMENT value to 1

### ISSUE THREAD

**Issue by lichnow** [typeorm/typeorm#4533]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
`connection.manager.clear(AclRole);` or `this.roleRepository.clear()` can delete of data of `roles` table, but not resets AUTO_INCREMENT value to 1, `clear()` method is `TRUNCATE`,why cannot do it?

**Comment by Kononnable** [comment]
Why should it? I don't see anything in documentation about that.
Tbh we're kind of in a grey area - for some use cases it might be useful, in other it would be considered a bug. I don't think changing this behavior would be a good idea - function does what it is supposed to do(name is `clear`, not `clearAndResetSeed`) and it can be breaking change for some already existing code.

In some databases(not sure if in all) exact value of auto incremented fields isn't always `lastValue+1` e.g. in mssql docs precisely says that new value will always be bigger than already existing ones, but might not be +1 - in some rare cases counter just hit 1000 for no known reason and starts from there. That's why it's not safe to assume that there will be a record with lower number(even if no record was removed)

**Comment by TiE23** [comment]
I found being able to reset the increment to be useful in e2e unit testing. I had e2e tests where I created some entities and destroyed them with `repository.clear()`. But when a later test I wrote offered the ability to retrieve a single entity by its ID I would seed the table with one entry and hit the API asking for `:id = 1` and it would fail. 

At that point, I had previous tests that created 4 entities in the table. They were all deleted, sure, but the ID my seed entity was assigned ID 5.

First, a caveat: **I am using SQLite**. So, this solution only works for that. But I imagine it can be adapted for use with SQL if SQL allows for resetting a sequence through a query.

The solution was to execute a query against the SQLite database to reset the counter for my particular entity. I found the method for this [here](https://www.designcise.com/web/tutorial/how-to-reset-autoincrement-number-sequence-in-sqlite).

```
 UPDATE `sqlite_sequence` SET `seq` = 0 WHERE `name` = '<table name here>';
```

My sample code is of a test I wrote that exercised an entity named "Category".

```
describe('Category e2e tests', () => {
  let app: INestApplication;
  let categoriesRepository: Repository<CategoryEntity>;
  let categoriesService: CategoryService;
  let connection: Connection;

  beforeAll(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [
        CategoryModule,
        TypeOrmModule.forRoot({
          entities: [__dirname + '/../**/*.entity.ts'],
          autoLoadEntities: true,
          synchronize: true,
          database: ':memory:', // Using in-memory DB for testing.
          type: 'sqlite',
        }),
      ],
    })
      .compile();

    app = module.createNestApplication();
    configureApp(app, 'test');  // Some personal code that adds stuff like cors and validation.
    await app.init();

    categoriesRepository = app.get(getRepositoryToken(CategoryEntity));
    categoriesService = app.get(CategoryService);
    connection = app.get(Connection);
  });

  afterAll(async () => {
    await app.close();
  });

  // Clear the Categories table. Defined this as a function to allow for precise execution.
  const clearCategoriesTable = async () => {
    await categoriesRepository.clear();
    // Reset SQLite's internal sequence table to 0 for consistent id values.
    await connection
      .createQueryRunner()
      .query(
        "UPDATE `sqlite_sequence` SET `seq` = 0 WHERE `name` = 'category_entity'"
      );
  };
[...]
```
Later in the test I would call the `clearCategoriesTable()` function where it made sense:
```
describe('GET /category/:id; findOne()', () => {
  beforeAll(async () => {
    // Seed with one Category.
    await categoriesService.create({ title: 'Category 1' });
  });

  afterAll(async () => {
    await clearCategoriesTable();
  });
  it('should find a specific Category', async () => {
    // ...
  });
});
```

I hope this helps someone out there and that this solution of mine can be adapted for SQL.
