### ISSUE TITLE
migration: every generate include alter geometry column even that column wasn't change

### ISSUE THREAD

**Issue by smonv** [typeorm/typeorm#4534]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

***Entity***

```ts
import { Entity, Column } from 'typeorm';
import { Geometry } from 'geojson';

@Entity()
export class Store {
    @Column({ type: 'geometry', srid: 4326 })
    geometry: Geometry;
}
```

Everytime I run `migration:generate` it include the code below to migration script. I have manually delete it inside `up` and `down` function.

```ts
await queryRunner.query(`ALTER TABLE "store" ALTER COLUMN "geometry" TYPE geometry(GEOMETRY,0)`);
```

**Comment by dflourusso** [comment]
I'm using:

```js
  @Column('geometry', { spatialFeatureType: 'Point', srid: 4326 })
  @IsNotEmpty()
  location: Point
```
and having the same issue. How can i solve it?

**Comment by smonv** [comment]
After applied the suggestion from @krazibit , i'm still facing same issue

```ts
@Column('geometry', { srid: 4326, spatialFeatureType: 'Point' })
coordinates: Point;
```

```ts
 await queryRunner.query(
       `ALTER TABLE "store" ALTER COLUMN "coordinates" TYPE geometry(Point,4326)`,
        undefined,
 );
```

**Comment by JeyongOh-MAASASIA** [comment]
This PR #5525 solves this problem. 
I forgot to link this issue in PR, so this issue is not closed automatically.
This issue can be closed.

**Comment by BlakeGardner** [comment]
For anyone else looking for a solution to this issue, this was affecting me with Postgres using the following code:

```ts
  @Column({
    type: 'point',
    spatialFeatureType: 'Point',
    srid: 4326,
  })
  point: string;
```

For whatever reason, changing my column to this fixed the issue for me:

```ts
import { Point } from 'typeorm';


  @Column('geometry', {
    spatialFeatureType: 'Point',
    srid: 4326,
  })
  point: Point;
```

Not entirely sure if this is still considered a bug, but it works.
