### ISSUE TITLE
How to orderBy custom field on mysql

### ISSUE THREAD

**Issue by moosoul** [typeorm/typeorm#4535]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want order by custom sequence，how?
Like this sql 
SELECT * FROM table ORDER BY FIELD(status,'offline','available','busy','distance')

**Comment by johannesschobel** [comment]
I think, i dont get your question.. Do you want to order the result by `status, distance`. However, the field `status` has 3 different options (i.e., `offline, available, busy`)?

you are looking for a query like
```sql
SELECT * FROM table WHERE ... ORDER BY status, distance
```

This returns the results ordered by `status` first and then ordered by `distance`. However, the status values are ordered `available`, `busy`, `offline` (ascending).

If you would like to have a completely custom order, i would suggest to add a `sortOrder` field and order by this field..

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by xingqiwu55555** [comment]
I met a same issue.
