### ISSUE TITLE
why dropSchema will drop all tables from database

### ISSUE THREAD

**Issue by metauro** [typeorm/typeorm#4536]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I think the dropSchema option only can drop table if table name prefix match entityPrefix, but dropSchema will drop all tables now. its very dangerous if I just want to rebuild my tables

**Comment by Kononnable** [comment]
Mysql treats schema and database as the same thing - there is no separate context like in postgres, mssql etc.
Name prefix is something completely different which doesn't really have much in common with schemas - it might create an illusion of the schema, but it lacks basic schema functionalities like ability to set access rights.
