### ISSUE TITLE
Error Creating table using MariaDB.

### ISSUE THREAD

**Issue by domzgarcia** [typeorm/typeorm#4541]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
I'm using
MySQL mariadb-10.2.3-win32


{ Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"todo" ("id"
integer PRIMARY KEY AUTOINCREMENT NOT NULL, "text" varchar NOT NULL' at line 1
    at Query.Sequence._packetToError
```

**Comment by hauau** [comment]
Show your config

**Comment by domzgarcia** [comment]
I am using foalTS framework.

```
{
  "name": "todos",
  "version": "0.0.0",
  "description": "",
  "scripts": {
    ...
  },
  "engines": {
    "node": ">=8"
  },
  "dependencies": {
    "@foal/core": "^1.0.0",
    "@foal/typeorm": "^1.0.0",
    "@types/mysql": "^2.15.6",
    "mysql": "^2.17.1",
    "source-map-support": "^0.5.1",
    "sqlite3": "^4.0.0",
    "typeorm": "^0.2.6"
  },
  "devDependencies": {
    ...
  }
}


```

**Comment by domzgarcia** [comment]
My colleague told me that AUTO_INCREMENT was replaced with AUTOINCREMENT that's why MySQL doesn't recognize the syntax.

**Comment by hauau** [comment]
`AUTOINCREMENT` is used only in `sqlite`. What driver `type` is in your ormconfig?

**Comment by Kononnable** [comment]
Closing as no response from the author.
