### ISSUE TITLE
Connection to mssql fails without output.

### ISSUE THREAD

**Issue by tylerjwatson** [typeorm/typeorm#455]
Hi guys,

I have a connection setup with the following configuration prototype: 
```
[
    {
        "name": "default",
        "driver": {
            "type": "mssql",
            "url": "mssql://****:****@****.database.windows.net/metadata?encrypt=true"
        },
        "autoSchemaSync": true,
        "entities": [
            "../../bms-framework/dist/entities/**/*.js"
        ],
        "logging": {
            "logQueries": true,
            "logSchemaCreation": true,
            "logFailedQueryError": true
        }
    },
    {
        "name": "local",
        "driver": {
            "type": "sqlite",
            "storage": "test.db"
        },
        "autoSchemaSync": true,
        "entities": [
            "../../bms-framework/dist/entities/**/*.js"
        ],
        "logging": {
            "logQueries": true,
            "logSchemaCreation": true,
            "logFailedQueryError": true
        }
    }
]
```
The SQLite one works fine but the mssql one fails without output.  I have tried the following scenarios:

1.  Jasmine test case, calling `createConnection` in `beforeAll()`, which hangs indefinitely until jasmine's async timeout interval,
2. Typeorm's `typeorm schema:sync -c default`, which produces no output despite logging enabled and appears to exit cleanly whilst doing nothing
3. `ts-node` REPL to test `node-mssql`'s connection using the URL syntax, which connects fine.
4. Typeorm's `typeorm schema:sync -c local` which works fine.

I had to use `mssql@3.3.0` because the latest version breaks under another issue already reported here.

Typeorm does not log output under these error cases so I am at a loss as to what more information I could provide.  Does anyone know what is going on?

Cheers!

**Comment by pleerock** [comment]
Most probably something with your environment or configuration. Try to debug. Did mssql worked anytime before for you? Mssql 3.3.0 works fine on my machine.

**Comment by tylerjwatson** [comment]
mssql has never worked in typeorm, it has worked when using `mssql` package by itself, also works in SQL Management Studio.

is there a way to turn on more verbose logging?

**Comment by tylerjwatson** [comment]
Okay so it turns out I was miss passing the `encrypt: true` option to the driver. `mssql@3.3.0` does not properly emit socket connection errors when encryption is required and the `encrypt: true` option is not passed properly.

I was using the url string `mssql://username:password@****.database.windows.net:1433/metadata?encrypt=true` as documented [here](https://github.com/patriksimek/node-mssql#configuration) which does not work in typeorm (it erroneously makes the query string as part of the catalog name), and also setting options as detailed here:

```json
"driver": {
    "type": "mssql",
    "url": "mssql://****:****@****.database.windows.net/metadata?encrypt=true" // does not work
    extra: {
       encrypt: true, //does not work
       options: {
           encrypt: true //works
       }
   }
}
```

I am closing this immediate issue as it appears to be resolved, but better logging/clearer instructions would be better.
