### ISSUE TITLE
getCount() not DISTINCT()?

### ISSUE THREAD

**Issue by SkyLin0909** [typeorm/typeorm#4550]
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

now getCount() => select count(DISTINCT(id)), i want select count(id)` or `select count(*)

```ts
.getCount({ DISTINCT: false })
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `msql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
Could you elaborate on your problem? If Id is unique(primary key) what seems to be the problem?

**Comment by SkyLin0909** [comment]
Id is primary key. My problem is when the amount of data is too large, the query speed is not as good

**Comment by dboune** [comment]
I just ran into this as well in a slightly different way with mysql/mariadb on a table with 850k rows, and two primary keys, just wanting to get a total count of rows. This is on my dev machine, so we can expect unusually high query times.

In this case it is running a COUNT(DISTINCT(CONCAT...

Using another SQL tool...
Simple Count on First Primary Key: **1.867 seconds**
Count+Distinct: **2.683 seconds** _(Obviously this would render an undesirable result for this case)_
Count+Concat: **2.484 seconds**
Count+Distinct+Concat: **22.873 seconds**

I realize my case here adds the complexity of two primary keys, and that I could handle this a bit differently. Still, it does highlight how the construction of the count query is not always straightforward, and can currently lead to unnecessary complexity for what looks like a simple case. For a table with far more rows, and I'll have a few of those, the impact would be even greater.

For some cases, it may be possible to simply add an additional index to the primary key.

For my case, I'll go back and build out this count manually, which should resolve my own issue.

**Comment by Zippersk** [comment]
This also happens on postgres. Is there an option to turn off `DISTINCT` on `count()`?

1.8 sec with DISTINCT:
![image](https://user-images.githubusercontent.com/6651236/92418105-0faa5200-f166-11ea-9a4c-20e1811c1f6f.png)

0.235 sec without DISTINCT:
![image](https://user-images.githubusercontent.com/6651236/92418132-39fc0f80-f166-11ea-9bf6-49fa94dfc30f.png)

**Comment by palashCItobuz** [comment]
I have a scenario where the querybuilder query is returning two rows of data with same id, but `getCount()` is applying a distinct on the query and thus returning 1 as count.

```
"data": {
      "items": [
            {
                "campaign_id": "1",
                "campaign_name": "September Bonanza 2",
                "promoter_join_date": "2020-09-15T09:05:21.425Z",
                "promoter_id": "3",
                "promoter_full_name": "Charles Trenet",
                "promoter_email": "charles.trenet@gmail.com"
            },
            {
                "campaign_id": "1",
                "campaign_name": "September Bonanza 2",
                "promoter_join_date": "2020-09-15T09:05:47.889Z",
                "promoter_id": "4",
                "promoter_full_name": "Rupert Bear",
                "promoter_email": "rupert.bear@gmail.com"
            }
     ],
     "itemsCount": 1,
     "totalPages": 1,
     "currentPage": 1
}
```

**Comment by imnotjames** [comment]
Pretty sure distinct on count is because the joins that happen as part of an entity loading.  Without it the count would not work as expected.

@palashCItobuz in your case you'd want to update the query builder to be on the promoter - not the campaign.

**Comment by imnotjames** [comment]
While there can be performance improvements in some cases, this is working as intended as far as I can see.

**Comment by Leulz** [comment]
@imnotjames I was thinking of creating a new issue here for a Feature Request, since I'd like the `repository.count()` to have the possibility to be not distinct. But then I found this issue and read your comments, and now I'm not so sure.

This feature is wanted by me due to the fact that in Postgres, a `COUNT(DISTINCT...))` query can be pretty heavy. There are quite a few references online talking about that, [this article](https://www.citusdata.com/blog/2016/10/12/count-performance/) being one example. So, for Postgres, it'd be great if we could tell typeorm that we know that the distinct is not needed. The default behaviour would keep being the current one, of course.

Do you think this feature would be useful? I'm currently getting around it by using a QueryBuilder, but it'd be far less verbose if I could just pass an option to `count`.
