### ISSUE TITLE
Does query builder .get return Entity or BaseEntity?

### ISSUE THREAD

**Issue by saoudrizwan** [typeorm/typeorm#4552]
I want to make sure that when I do queries with getConnection() for example:
```typescript
const posts = (await getConnection()
			.createQueryBuilder()
			.relation(User, "posts")
			.of(req.user)
			.loadMany())
```
that `posts` would be able to be `save`d, i.e. `Post.save(posts)`

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
