### ISSUE TITLE
Can bidirectional one-to-one relationship have null on non-foreign-key-owning side?

### ISSUE THREAD

**Issue by saoudrizwan** [typeorm/typeorm#4553]
**Issue type:**

[x] question

**Database system/driver:**

[x] `postgres`

I have a one to one relationship like so:
```typescript
@Entity()
export class Car extends BaseEntity {
	@PrimaryColumn()
	id: number

	@OneToOne(type => User, user => user.car, { nullable: true })
	user?: User
}
```
```typescript
@Entity()
export class User extends BaseEntity {
	@PrimaryGeneratedColumn()
	id: number

	@OneToOne(type => Car, car => car.user)
	@JoinColumn()
	car: Car
}
```
Is it okay for me to able to create `User`s without creating `Car`s, and `Car`s without `User`s? 
By making `car.user` nullable, I'm wanting to make it such that a `car` can exist without a `user`, but a `user` cannot exist without a `car`.

**Comment by mantagen** [comment]
@saoudrizwan 

You've probably moved on from that particular problem, but if you haven't or if anyone stumbles on this:

The OneToOne column will be nullable by default. No make it not nullable, see this comment:
https://github.com/typeorm/typeorm/issues/4301#issuecomment-634032714

For you it would look something like
```ts
@Entity()
export class Car extends BaseEntity {
	@PrimaryColumn()
	id: number

	@OneToOne(type => User, user => user.car)
	user: User | null
}
@Entity()
export class User extends BaseEntity {
	@PrimaryGeneratedColumn()
	id: number

        @Column({ type: "integer" })
        carId: number;
        
	@OneToOne(type => Car, car => car.user)
	@JoinColumn()
	car: Car
}
```

By adding `carId`, which defaults to `nullable: false`, a `NOT NULL` constraint will be added to the carId field in the Car table (which will not be added in your example as you've written it)

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by schroedermichael** [comment]
> @saoudrizwan
> 
> You've probably moved on from that particular problem, but if you haven't or if anyone stumbles on this:
> 
> The OneToOne column will be nullable by default. No make it not nullable, see this comment:
> [#4301 (comment)](https://github.com/typeorm/typeorm/issues/4301#issuecomment-634032714)
> 
> For you it would look something like
> 
> ```ts
> @Entity()
> export class Car extends BaseEntity {
> 	@PrimaryColumn()
> 	id: number
> 
> 	@OneToOne(type => User, user => user.car)
> 	user: User | null
> }
> @Entity()
> export class User extends BaseEntity {
> 	@PrimaryGeneratedColumn()
> 	id: number
> 
>         @Column({ type: "integer" })
>         userId: number;
>         
> 	@OneToOne(type => Car, car => car.user)
> 	@JoinColumn()
> 	car: Car
> }
> ```
> 
> By adding `userId`, which defaults to `nullable: false`, a `NOT NULL` constraint will be added to the `userId` field in the Car table (which will not be added in your example as you've written it)

Is this not backwards? Wouldn't you want to add a `carId` column to the user table?

**Comment by mantagen** [comment]
@schroedermichael yes you're right, that code snippet is erroneous... looks like it should be:
```ts
@Entity()
export class Car extends BaseEntity {
	@PrimaryColumn()
	id: number

	@OneToOne(type => User, user => user.car)
	user: User | null
}
@Entity()
export class User extends BaseEntity {
	@PrimaryGeneratedColumn()
	id: number

        @Column({ type: "integer" })
        carId: number;
        
	@OneToOne(type => Car, car => car.user)
	@JoinColumn()
	car: Car
}
```

**Comment by msiric** [comment]
@mantagen What if I'm using UUIDs as primary keys instead of auto incrementing integers?
How would I define carId column in that case?

**Comment by mantagen** [comment]
@msiric see: https://github.com/typeorm/typeorm/blob/master/docs/entities.md#primary-columns

You can write
```ts
    @PrimaryGeneratedColumn("uuid")
    id: string;
```

And see: https://github.com/typeorm/typeorm/blob/master/docs/entities.md#column-types
Note that you can write `@Column("uuid")` or `@Column({ type: "uuid" })` interchangably.

**Comment by msiric** [comment]
I already tried that and I keep getting this error: QueryFailedError: null value in column "artworkId" violates not-null constraint

**Comment by msiric** [comment]
@mantagen I already tried that and I keep getting this error:
QueryFailedError: null value in column "carId" violates not-null constraint

For context, this is a OneToOne relationship.

Edit: I'm not sure if I explained correctly what I'm trying to accomplish. Taking your example with User and Car entities above, I want to make sure that when I insert a new Car entity in the db, the User's Car column cascades and gets updated as well.
But I want a bi-directional relationship where the User entity has a carId foreign key AND the Car entity has a userId foreign key.
How do I do this?

**Comment by mantagen** [comment]
@msiric if you want this behaviour then I recommend that you follow the docs here: https://github.com/typeorm/typeorm/blob/master/docs/one-to-one-relations.md

That should give you the behaviour that you want to achieve.

This thread is specifically for adding a "NOT_NULL" constraint to `user.carId`, which I don't _think_ is compatible with the way you're wanting to insert data. I could be wrong.

> For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
