### ISSUE TITLE
columns are dropped and recreated at server start using oracle db

### ISSUE THREAD

**Issue by Gnilherk** [typeorm/typeorm#4558]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

We use sqlite for our local development and an oracle db for our deployed versions. 
When we start the server the first time using our oracle db everything works fine. All the tables are created. But when we start it a second time, typeorm says the columns changed, even though they didn't, and drops all the constraints/columns and re-creates them right afterwards. 

```
columns changed in "users". updating: id, createdBy, updatedBy, name
query: ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"
query: ALTER TABLE "users" DROP COLUMN "id"
query: ALTER TABLE "users" ADD "id" varchar2(255) NOT NULL
query: ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")

```

This obviously leads to data loss and since it's deleting/recreating column by column it messes up the oracle db and leads to following error as soon as data is inserted: 
QueryFailedError: ORA-01758: table must be empty to add mandatory (NOT NULL) column

if we use exactly the same configuration in an sqlite setup nothing like this happens and the db starts up without dropping any columns.

I set up a small project to recreate the issue: 
https://github.com/Gnilherk/typeormapp

**Comment by ilakshmikanthp** [comment]
Even I am facing the same issue. Is there any solution for this?
ALTER TABLE "approval" DROP CONSTRAINT "CHK_1bcdabef874c10beae0ed4ddfd"
ALTER TABLE "approval" DROP COLUMN "approval_type"
ALTER TABLE "approval" ADD "approval_type" character varying(10)

**Comment by rosebudsystems** [comment]
Even I am facing the same issue. Is there any solution for this?

**Comment by eXXeption** [comment]
Same issue for me with oracle and latest typeorm version.

**Comment by danielkbx** [comment]
Anything new here? I just added two columns, nothing special, and they both keep getting deleting and re-created on every server startup.

**Comment by hsharghi** [comment]
Same here using it with sqlite. 
I see some strange behavior in addition to dropping tables, like: 
```
renaming column "department" in to "department"
```

Anyone found a way to fix it?

**Comment by ataquino** [comment]
I have a similar issue with `mssql`, columns with `{ type: 'varchar', length: 'max' }` are always dropped and created, even when generating migrations. By looking at the migration file, I saw the `up()` method was creating the column with type `varchar(max)` and the `down()` method was creating it as `varchar(MAX)`. So I changed `length: 'max'` to `length: 'MAX'` and the problem went away. 

Maybe something similar is happening in these other cases?

**Comment by Logic-Bits** [comment]
@hsharghi, @ataquino  Thanks for the idea... problem was that the default in my enum was not a string but the enum value. It always got droped and recreated (therefore also problem with views).

use:
`@Column("enum", { enum: StorageType, nullable: false, default: "STANDARD" })`
instead of 
`@Column("enum", { enum: StorageType, nullable: false, default: StorageType.STANDARD })`

**Comment by AlexMesser** [comment]
This was fixed and released. Please update your TypeORM version to the latest and reopen this issue if the error persists.

**Comment by RyannGalea** [comment]
Anyone continue to have this issue?

Everytime I restart my server it has been dropping and re-adding a constraint, deleting the id driving me insane as seen here:

```
query: ALTER TABLE "user" DROP CONSTRAINT "FK_68d3c22dbd95449360fdbf7a3f1"
query: ALTER TABLE "user" DROP COLUMN "accountId"
query: ALTER TABLE "user" ADD "accountId" uuid
```

It also deletes the roles array
```
query: SELECT "n"."nspname", "t"."typname" FROM "pg_type" "t" INNER JOIN "pg_namespace" "n" ON "n"."oid" = "t"."typnamespace" WHERE "n"."nspname" = 'public' AND "t"."typname" = 'user_roles_enum'
query: SELECT "udt_schema", "udt_name" FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'user' AND "column_name"='roles'
query: ALTER TABLE "user" DROP COLUMN "roles"
query: DROP TYPE "public"."user_roles_enum"
```

This is how my entity looks
```
  @Field(type => [String])
  @Column({ type: 'simple-array', enum: UserRolesEnum, default: UserRolesEnum.BASIC })
  roles: string[]

or

  @Field(type => [String])
  @Column({ array: true, type: 'simple-array', enum: UserRolesEnum, default: [UserRolesEnum.BASIC] })
  roles: string[]
```

This is using Postgres by the way.

I am migrating a project from Mongo to Postgres and I'm getting hit with some "gotcha's" Is this expected behavior?

How do I remedy this for the development process?
