### ISSUE TITLE
Add options to input config when initializing sql.js

### ISSUE THREAD

**Issue by DavidChen-minted** [typeorm/typeorm#4559]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Typeorm added supports for Sql.js v1.0 https://github.com/typeorm/typeorm/issues/4104 but it needs a new connection option to pass in initConfigs, such as [`{ locateFile: filename => ``/dist/${filename}`` }`](https://github.com/kripken/sql.js/tree/fbe8427c32d5077be06bb808283c2efb22a84c97#upgrading-from-0x-to-1x).

**Comment by exequielc** [comment]
Hi,  I'm using this old sql.js v0.5.0  and don't understand how to change the conection in order to upgrade to 1.0

I'm using the Ionic implementation.

```
let dbOptions: ConnectionOptions;
 dbOptions = {
          type: 'sqljs',
          location: 'browser',
          autoSave: true
 };
 Object.assign(dbOptions, {
      synchronize: true,
      autoSchemaSync: true,
      migrationsRun: true,
      entities: [    tables   ]
    });
     return createConnection(dbOptions).then(connection => {
      console.log("Data Access connected!");
      return connection;
    }).catch(error => {
      //console.log("Data Access Error : ", );
      return null;
    });

```
