### ISSUE TITLE
How to create a case sensitive database? or make a one be case sensitive ?

### ISSUE THREAD

**Issue by lili21** [typeorm/typeorm#4562]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

is there a way I can make an exist database be case sensitive ?

**Comment by Kononnable** [comment]
What do you mean by case sensitive database? You want to have columns case sensitive, you expect database to treat data as case sensitive?

**Comment by lili21** [comment]
I expect database to treat data as case sensitive.

```typescript
//entity
@Entity()
class App {
  @Column()
  name: string
}

const app = await getManager().findOneOrFail(App, { where: { name: 'AbcEfg' } })
```

Suppose I got a record where `app.name === 'abcefg'`,  I expect the above find be failed.

**Comment by Kononnable** [comment]
You should check https://stackoverflow.com/a/1411260 to see on which level your collation is set to case insensitive. If you want to change it just for specific column you can use `collation` property in column decorator options.
