### ISSUE TITLE
Not able to pass array of string to filter through database columns

### ISSUE THREAD

**Issue by Ajinkya1496** [typeorm/typeorm#4563]
**Issue type:**

[x] `question`

**Database system/driver:**
[x ] `postgres`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Here is what I am trying to do-
I have an array of strings coming from client side and wanted to filter this array against the array in column in postgres databse 
Array coming from frontend- ```["English","Spanish","German"]```
In my database table I have column ```langugae``` of type ```character varying[]```

Now the query I am using here to get the result in plain database is -
``` select * from blogs where language @> '{"English","German"}';  ``` and this gives me correct results.

My question is how do I implement the above query in ```typeorm``` syntax ?
Entity Structure-
```
@Column("character varying",{array:true})
 language: string[];
```
What I tried so far is -
```
return await this.blogsRepo.find({
      where: [
        {
          language: Any(body.languages),
        }
      ]
    })
```
I get an error saying- ```could not find array type for data type character varying[] ```

Is it because the array stored in the postgres table is like ```{English, Spanish}``` and what I am passing is in the form ["English", "Spanish"]

I did not face any issue with inserting, updating same array field (got from client side) but getting stuck at this.

Thanks in advance,

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Ajinkya1496** [comment]
@pleerock Can you have a look at this one or give me an suggestion on what could be the other possible way out of this?

**Comment by vlapo** [comment]
I think we do not have implemented any find options for this `@>` operator. You have to use query builder and write your where statement by yourself.

**Comment by Ajinkya1496** [comment]
Thanks for your response! I used raw query for the above requirement. If you think this can be a useful feature, it will be great if you add it.

**Comment by imnotjames** [comment]
Looks like you got an answer to your question.  Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
