### ISSUE TITLE
tree entity recursive select?

### ISSUE THREAD

**Issue by ThisIsHG** [typeorm/typeorm#4564]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is it possible to select all entity's, laying underneath a specified tree component?

For example I've got an Entity "Category" like in the example of Tree Entities and "Posts" which can have a Category as a One to Many relation. 

Can I build a query that returns all posts of all categorys underneath a specified one? And if so how?

**Comment by arminghm** [comment]
I think you can use `relations`, take a look at https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#basic-options

**Comment by zecka** [comment]
@ThisIsHG do you find the solution with "relations" ?
I don't find how to build this query.

**Comment by TheProgrammer21** [comment]
I just implemented a pull request to satisfy your needs!

**Comment by imnotjames** [comment]
This has been merged and released.  Closing out this PR.
