### ISSUE TITLE
No sub-select or limit on left join possible

### ISSUE THREAD

**Issue by apiel** [typeorm/typeorm#457]
It doesn't seem possible to make sub select

`	let query = db.getRepository(User)
		.createQueryBuilder('u')
		.where('u.email = :email')
		.setParameter('email', username)
		.andWhere('d.idWeight = (SELECT "idWeight" FROM "Weight" ORDER BY "startTime" DESC LIMIT 1)')
		.leftJoinAndSelect('u.Weight', 'd')
		.addSelect()
		.orderBy('d.startTime', 'DESC');`

And the limit parameter in leftJoinAndSelect doesn't seem to work

`	let query = db.getRepository(User)
		.createQueryBuilder('u')
		.where('u.email = :email')
		.setParameter('email', username)
		.leftJoinAndSelect('u.Weight', 'd', null, {limit: 1})
		.addSelect()
		.orderBy('d.startTime', 'DESC');`

How should I proceed to get only 1 row from my leftJoin request?

**Comment by pleerock** [comment]
subselects are possible. Something like this should work:

```ts
const itemRepository = DatabaseConnection.get().getRepository(Item);
let innerSelect = itemRepository
    .createQueryBuilder('item')
    .orderBy('item.checksum', 'DESC')
    .setLimit(2);

await projectRepository
    .createQueryBuilder('project')
    .leftJoinAndSelect(`(${innerSelect.getGeneratedQuery()})`, 'item', '(project.id = item.project)')
    .getMany();
```

Limit thought joins aren't possible and unlikely ever will be, because of limitations returned by sql.

At the end you can perform a separate query and load data you need.

**Comment by apiel** [comment]
```
	let innerSelect = db.getRepository(Weight)
		.createQueryBuilder('d')
		.orderBy('d.startTime', 'DESC')
		.setLimit(1);

	let query = db.getRepository(User)
		.createQueryBuilder('u')
		.where('u.email = :email', {email: username})
		.leftJoinAndSelect(`(${innerSelect.getGeneratedQuery()})`, 'd', '(d.idUser = u.idUser)')
```
I tried your syntax but I get an error:

> error: syntax error at or near "".""

**Comment by apiel** [comment]
```
	let query = db.getRepository(User)
		.createQueryBuilder('u')
		.where('u.email = :email', {email: username})
		.leftJoinAndSelect('u.Weight', 'd')
		.select('u.*, MAX("d"."startTime")')
		.groupBy('u.idUser')
```
And like this I get undefined, even if the generated SQL query return data. :-/

**Comment by pleerock** [comment]
do you still have problems with subquery?

**Comment by apiel** [comment]
Unfortunately I was not able to manage it. I finally made multiple query
and combine everything with typescript :-/

**Comment by apiel** [comment]
Actually it would be great to solve this issue ;-)

**Comment by pleerock** [comment]
Okay I'll create a test with a sample how to make subqueries

**Comment by apiel** [comment]
Super, thanks a lot for this library and I am looking forward to use
sub-queries ;-)

**Comment by dgbrokaw** [comment]
Is there any update on this? I think I need a similar query.

I tried something similar to apiel's test of your example, but got the same syntax error even with the most simple query I could write.

Also, I am unsure how this is supposed to work if parameters are used in the sub-select.

`
let innerSelect = db.getRepository(Person)
        .createQueryBuilder("person")
        .where(`person.first_name = :name`, { name: "Test" });

await db.getRepository(Something)
        .createQueryBuilder("something")
        .leftJoinAndSelect(`(${innerSelect.getGeneratedQuery()})`, "person", "(something.personId = person.person_id)");
`

I have tried things like the above, as well as concatenating the inner select string within another query string and trying other methods like getSqlWithParameters. None of these seem to fill in the parameter values in the query string reported by the error message. They will be listed like ":name" or "$1" or the like.

Thanks.

**Comment by pleerock** [comment]
As of `0.1.0-alpha.22` there are lot of useful methods to create subqueries using more elegant api. See [there](https://github.com/typeorm/typeorm/blob/0b4e3ff5eb52ca05f0fe9e9fe5d7b6e1b575863a/test/functional/query-builder/subquery/query-builder-subquery.ts#L74) how to use subqueries. Some of examples are:

```ts

        const posts = await connection.getRepository(Post)
            .createQueryBuilder("post")
            .where(qb => {
                const subQuery = qb.subQuery()
                    .select("user.name")
                    .from(User, "user")
                    .where("user.registered = :registered")
                    .getQuery();
                return "post.title IN " + subQuery;
            })
            .setParameter("registered", true)
            .getMany();
```

```ts
const posts = await connection
            .createQueryBuilder()
            .select("user.name", "name")
            .from(subQuery => {
                return subQuery
                    .select("user.name", "name")
                    .from(User, "user")
                    .where("user.registered = :registered", { registered: true });
            }, "user")
            .setParameters(userQb.getParameters())
            .getRawMany();
```

**Comment by dgbrokaw** [comment]
That's great! I will try it out.

**Comment by sergioalvz** [comment]
Hey @pleerock any chances you could help me to understand why this is not working? This issue is the closest I have found to be a similar problem. I'm trying to do a query like the following (I've changed the entities' names to make the domain more friendly to understand):

```typescript
await getRepository(Photo)
  .createQueryBuilder('photo')
  .addFrom<Photo>((query) => {
    return query
      .select('camera')
      .addSelect('MAX(likes)', 'maxLikes')
      .addSelect('userId')
      .from(Photo, null)
      .where('userId = :userId', { userId })
      .groupBy('userId')
      .addGroupBy('camera');
  }, 'filtered')
  .innerJoinAndSelect('photo.user', 'user')
  .where('filtered.camera = photo.camera')
  .andWhere('filtered.userId = photo.userId')
  .andWhere('filtered.maxLikes = photo.likes')
  .getMany();
```

I'm able to get the expected collection of Photos but once I add the`innerJoinAndSelect` function to load the relation between User and Photo, I start to see the following error:

```
message: 'ER_BAD_FIELD_ERROR: Unknown column \'photo.userId\' in \'on clause\'',
code: 'ER_BAD_FIELD_ERROR',
errno: 1054,
sqlMessage: 'Unknown column \'photo.userId\' in \'on clause\'',
```

Not sure whether this is a bug or not. I couldn't find any similar use cases by reading the documentation. Let me know if there is anything else I can do.

Thanks in advance!

**Comment by sergioalvz** [comment]
Finally it has nothing to do with TypeORM but with the query itself. It was solved by moving the subquery from the `FROM`clause to an `INNER JOIN` clause:

```typescript
getRepository(Photo).createQueryBuilder('p')
  .innerJoinAndSelect('p.user', 'user')
  .innerJoin(
    (query) => {
      return query
        .select('userId')
        .addSelect('MAX(likes)', 'maxLikes')
        .addSelect('camera')
        .from(Photo, null)
        .where('userId = :userId', { userId })
        .groupBy('userId')
        .addGroupBy('camera');
    },
    'f',
    'f.userId = p.userId and f.camera = p.camera and f.maxLikes = p.likes',
  )
  .getMany();
```

**Comment by kjr247** [comment]
Is this possible with the find methods for example findAndCount? Is there a related issue for that one?
