### ISSUE TITLE
How to use DATE(<timestamp>)

### ISSUE THREAD

**Issue by kaigothe** [typeorm/typeorm#4579]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have following mySQL table / Entinity Class:

```ts
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

@Entity()
export class Event{
    @PrimaryGeneratedColumn()
    eventID:number 

    @Column({default: "no name"})
    name:string

    @Column({type: "datetime", default: () => "CURRENT_TIMESTAMP"})
    date: Date
}
```

**Question:** How can I select all events from today?
In SQL I would use:

```SQL
SELECT eventID FROM event WHERE DATE(date) = CURDATE()
```

How can I achieve this with TypeORM?

**Comment by Mando75** [comment]
Have you tried doing something like this?

```ts
connection
   .getRepository(Event)
   .createQueryBuilder("event")
   .where("DATE(event.date) = CURDATE()")
  .getMany()
```

See the query builder docs for more info. https://typeorm.io/#/select-query-builder/adding-where-expression

**Comment by kaigothe** [comment]
Thank you,
it work for me. 😊
