### ISSUE TITLE
leftJoinAndSelect does not return a sub-object

### ISSUE THREAD

**Issue by YeisonGomez** [typeorm/typeorm#4582]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts

@Entity("user",{schema:"users" } )
export class user {

    @PrimaryGeneratedColumn({
        type:"bigint", 
        name:"id"
        })
    id:string;
        
    @Column("character varying",{ 
        nullable:false,
        length:200,
        name:"email"
        })
    email:string;
   
    @OneToMany(type=>admin, admin=>admin.fkUser,{ onDelete: "CASCADE" ,onUpdate: "CASCADE" })
    admins:admin[];
}
```

```ts
@Entity("admin",{schema:"users" } )
export class admin {

    @PrimaryGeneratedColumn({
        type:"integer", 
        name:"id"
        })
    id:number;
     
    @ManyToOne(type=>user, user=>user.admins,{  nullable:false,onDelete: 'CASCADE',onUpdate: 'CASCADE' })
    @JoinColumn({ name:'fk_user'})
    fkUser:user | null;
}
```

Select and get an admin sub-object:
```ts
    getManager('schemaUsers').createQueryBuilder(user, 'us')
    .select("us.email", "email")
    .innerJoinAndSelect("us.admins", "admin")
    .execute()
```

This is what I hope

```ts
    [{
        "email": "test1@gmail.com",
        "admin": { "id": 1, fk_user: "1" }
    },
    {
        "email": "test2@gmail.com",
        "admin": { "id": 2, fk_user: "2" }
    }]
```

But returns

```ts
    [{
        "email": "test1@gmail.com",
        "admin_id": 1,
        "admin_fk_user": "1"
    },
    {
        "email": "test2@gmail.com",
        "admin_id": 2,
        "admin_fk_user": "2"
    }]
```

**Comment by Mando75** [comment]
Your example code is using innerJoinAndSelect, not leftJoinAndSelect. For the differences, see the documentation here: https://typeorm.io/#/select-query-builder/inner-and-left-joins

Instead of using `.execute()` try using `.getOne()` or `.getMany()`. `.execute()` returns back raw sql results. https://github.com/typeorm/typeorm/blob/master/src/query-builder/QueryBuilder.ts#L397

**Comment by YeisonGomez** [comment]
Sorry for the delay in answering.
I tried to get a getOne, but I don't get an answer. Try async / await and then as a promise

`typescript
    this.userRepository.createQueryBuilder('us')
    .select("us.email", "email")
    .getOne()
    .then(data => console.log(data))
    .catch(err => console.log(err))
`

In this case the data log returns me undefined. The same happens to me with the getMany.
Do you know anything about it?

**Comment by YeisonGomez** [comment]
Oh, I found my problem. the `getOne()` and `getMany()` returns nothing if the select have aliases.

Maybe I skip this in the documentation. Thank you
