### ISSUE TITLE
dynamic connectionOptions

### ISSUE THREAD

**Issue by MartinHignett** [typeorm/typeorm#4587]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` 

**Steps to reproduce or a small repository showing the problem:**

I have an issue with connection management/pooling. We would like to rotate the password on our database regularly, but without restarting all our application code (this is split across many lambdas, so would be painful to automate). What I am looking for is a an API a bit like this:

```ts
await createConnection(async () => {
    const secret = await readSecretFromSecretsManager(); 
    return {
        type: 'postgres',
        host: secret.host,
        username: secret.userName,
        password: secret.password,
        port: 5432,
        database: secret.database,
        synchronize: false,
        dropSchema: false,
        logging: enableLogging,
        entities: myEntities
    }
});
```
The goal here is that every time a new connection is added to the pool, the secret is read from the SecretsManager service. This means that if the password changes, when TypeORM tries to create a new connection, it will use the new password. Currently, TypeORM is using the stale, cached connectionOptions.

Thanks for any thoughts or advice on this!

**Comment by itonics-tbeauvais** [comment]
This is quite critical in our application. Otherwise, we get a solution, or we will have to think about moving away from TypeORM.

**Comment by imnotjames** [comment]
I think this is better managed within your application code.  When you know the password has rotated, close all connections and connect with the new password.
