### ISSUE TITLE
Best practices when releasing a new version [React-Native]

### ISSUE THREAD

**Issue by viniciusvelasco** [typeorm/typeorm#4590]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[X] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello, I am using typeorm in a React Native app and would like to know a best practices when releasing a new version with new table or columns. I set the sync property to true and when I select or insert it very slow, I set the sync property to false fast but if I release a new version I would not know how to upgrade my database. Can you help me? (I use Google translate)

**Comment by imnotjames** [comment]
You could use migrations - but I don't think your queries should be that slow with the synchronize flag - just the first load of the connection.  Perhaps an example repository or code snippet could help determine the cause there.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
