### ISSUE TITLE
Dynamically generate one entity property and don't create a column for it

### ISSUE THREAD

**Issue by mstoetzer** [typeorm/typeorm#4594]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Question:**

* Imagine two DB tables: Photos and Albums

Is it possible, that Album gets a property `albumPreview` that contains a random ID from one of the Photos in the Photos table?

So, everytime I ask for an Album, I will get a different Photo ID in `albumPreview`.

Is such thing possible with TypeORM?

**Comment by imnotjames** [comment]
Yes, it's possible.  Accessor + query builder.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by thalysonalexr** [comment]
pls, show me example
