### ISSUE TITLE
Date Oddities

### ISSUE THREAD

**Issue by xlxAciDxlx** [typeorm/typeorm#4595]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:** 

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:** 

[x] `latest` (0.2.18)
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I see a bunch of issues pertaining to dates and went through a bunch of them, but (unless I searched for the wrong keywords) I could not find any issues relating to my specific issue (or related to MySQL specifically). So sorry if I missed a relevant one. 😛

In my project, I have the following entity `ServiceConnection`:
```ts
@Entity({
	name: "service_connections"
})
export class ServiceConnection extends BaseEntity {
	@PrimaryGeneratedColumn()
	id: number;

	@Column()
	accessToken: string;

	@CreateDateColumn()
	readonly createdAt: Date;

	@Column("timestamp", {
		default: () => {
			return "CURRENT_TIMESTAMP";
		}
	})
	expiresAt: Date;

	@ManyToOne(
		type => {
			return User;
		},
		user => {
			return user.id;
		},
		{
			eager: true
		}
	)
	owner: User;

	@Column()
	@IsNotEmpty()
	refreshToken: string;

	@ManyToOne(
		type => {
			return Service;
		},
		service => {
			return service.id;
		},
		{
			eager: true
		}
	)
	service: Service;

	@Column()
	serviceKey: number;

	@UpdateDateColumn()
	readonly updatedAt: Date;
}
```

I have the following code to check if `expiresAt` is greater than the current date, and if so the access/refresh token are expired (this is for OAuth tokens):
```ts
const tokenExpiration = connectionData.expiresAt;
this.logger.debug(`Now: ${new Date()}`)
this.logger.debug(`Expires: ${tokenExpiration}`);
this.logger.debug(`Expired?: ${new Date() > tokenExpiration ? "Yes" : "No"}`); // Returns no, which is bad/incorrect
this.logger.debug(`Expired [Date]?: ${new Date() > new Date(tokenExpiration) ? "Yes" : "No"}`); // Returns yes (good, but not how it needs to get to here)

if (new Date() > tokenExpiration) {
	this.logger.error("OAuth token expired, unable to continue!");
	return Promise.reject();
} else {
	// Token isn't expired and can be used
}
```

---

Another issue I noticed is that when data is initially inserted into the database (via `createdAt` and `updatedAt`) it has the proper timezone, though returning it (echoing it via console.info) or updating the value past the row being created does not have the timezone.

---

What could be causing the inconsistency/issue with this? I have `dateStrings: false` in my config options, but changing that value seems to make no difference. I'm sure I'm missing something, the logical code that should be needed should _NOT_ be to have to do `new Date(date)` for _every_ column with a field of `Date`.

**Comment by xlxAciDxlx** [comment]
Bump. Nothing?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
