### ISSUE TITLE
@JoinColumn position not same at schema

### ISSUE THREAD

**Issue by ardyfeb** [typeorm/typeorm#4596]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

i have schema like this;
```
@Entity('user')
@Index(['status'])
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ unique: true })
  email: string;

  @OneToOne(() => UserProfile)
  @JoinColumn({
    name: 'profileId',
    referencedColumnName: 'id',
  })
  profile: UserProfile;

  @Column()
  password: string;

  @OneToMany(type => UserAddress, address => address.userId)
  address?: UserAddress[];

  @Column({
    type: 'enum',
    enum: UserStatus,
    default: UserStatus.UNVERIFIED,
  })
  status: UserStatus;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
```
but stored on database like this:
![Screenshot from 2019-08-18 18-57-07](https://user-images.githubusercontent.com/30074366/63224137-0e6c5700-c1ea-11e9-9f8c-a219dccc0459.png)

`profileId` stored at end of table column, but in schema position `profileId` after `email` column

**Comment by AlexMesser** [comment]
TypeORM does not care about column positions in the database table. By design.
