### ISSUE TITLE
Not loading data from @OneToOne relation

### ISSUE THREAD

**Issue by 19majkel94** [typeorm/typeorm#46]
There is a problem with loading object from database. The creating and saving works (I looked in the database) but when loading from database it doesn't load the data from relation.

``` typescript
import "reflect-metadata";

import { createConnection } from "typeorm";

import { Post } from "./post";
import { PostDetails } from "./post-details";

async function main() {
    try {
        console.log(`Before connection!`);
        let connection = await createConnection({
            driver: {
                type: "mysql",
                host: "localhost",
                port: 3306,
                username: "root",
                password: "qwerty123",
                database: "typeorm"
            },
            entities: [
                Post, PostDetails
            ],
            logging: {
                logQueries: true,
                logFailedQueryError: true,
            },
            autoSchemaSync: true,
        });
        console.log(`Connected!`);

        let post = new Post();
        post.title = "Title";
        post.text = "Lorem ipsum";
        post.details = new PostDetails();
        post.details.testField = "test";
        console.log(post);
        post = await connection.getRepository(Post).persist(post);
        console.log(post);
        let loadedPost = await connection.getRepository(Post).findOneById(post.id);
        console.log(loadedPost);

        console.log(`Saved ok!`);
        process.exit(0);
    } catch (error) {
        console.log(`Error!`, error);
        process.exit(1);
    }
}

main();
```

My entities:

``` typescript
import { Table, PrimaryGeneratedColumn, Column, OneToOne, JoinColumn } from "typeorm";
import { PostDetails } from "./post-details";

@Table()
export class Post {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    title: string;

    @Column("text")
    text: string;

    @JoinColumn()
    @OneToOne(type => PostDetails, { cascadeInsert: true, nullable: true })
    details: PostDetails | null;
}
```

``` typescript
import { Table, PrimaryGeneratedColumn, Column } from "typeorm";

@Table()
export class PostDetails {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    testField: string;
}
```

Created object looks like this:

```
Post {
  title: 'Title',
  text: 'Lorem ipsum',
  details: PostDetails { testField: 'test', id: 1 },
  id: 1 }
```

But it generates sql without joins on relation, so only id is returned not the data:
`SELECT post.id AS post_id, post.title AS post_title, post.text AS post_text, post.details AS post_details FROM post post WHERE post.id=? -- PARAMETERS: [1]`
So the loaded object has empty `details` field:

```
Post { id: 1, title: 'Title', text: 'Lorem ipsum' }
```

This is a bug or I should add some decorator in `PostDetails`?

**Comment by pleerock** [comment]
```typescript
        let loadedPost = await connection.getRepository(Post).findOneById(post.id);
```

`findOneById` never joins relations by itself, you need to specify manually what relations you want to join. This is implemented this way because your object can have tons of relations, which can be nested deep and even recursive, thats why its not possible to always join all relations. Use needs to be explicit what he wants. You have two choices: use query builder or provide find options to `findOneById` method. Docs for both you can find on site

**Comment by 19majkel94** [comment]
> findOneById never joins relations by itself, you need to specify manually what relations you want to join. This is implemented this way because your object can have tons of relations, which can be nested deep and even recursive, thats why its not possible to always join all relations.

It's not an user friendly solution. People use ORM to simplify data access - just use `@Decorator` and don't worry about foreing keys, joins and other stuffs.

If someone have relation which might be bigger (not one-to-one) eg. 1000 relations, and he don't want do load it all, he can use [lazy relations](/typeorm/typeorm/tree/master/sample/sample18-lazy-relations). But when I add new relation to my class I have to remember to change joins in all query builder or make another layer with custom repository which will do that.

I think we should stick to the idea of Hibernate - eager and lazy loding. `QueryBuilder` or joins in `find` should be used only to make custom joins on columns that aren't defined as relations.

**Comment by pleerock** [comment]
> People use ORM to simplify data access - just use @Decorator and don't worry about foreing keys, joins and other stuffs.

actually you are not worrying about keys or joins. You are just telling which relation you need to load.

But I got your point, I have some ideas how to add automatic joins, i'll try to implement them later. Until that use query builder or find options

**Comment by 19majkel94** [comment]
> You are just telling which relation you need to load.

Ok, but how to deep/nested join? I mean in this chain `Product -> Category -> User` I can do 
```
leftJoinAndSelect: {
    category: "product.category"
}
```
to join category to product but with no user info. But what to do to join user to category? I tried `"category.user": "category.user"` and other combination but no luck - I got error in SQL  `(...) category.user AS category_user, category.user.id AS category.user_id` 😢

**Comment by pleerock** [comment]
It will look like this:

```typescript
leftJoinAndSelect: {
    category: "product.category",
    user: "category.user"
}
```

Also its generally better to use query builder for complex queries:

```typescript
const results = await repository.createQueryBuilder("product")
    .leftJoinAndSelect("product.category", "category") 
    .leftJoinAndSelect("category.user", "category.user")
    .getResults();
```

**Comment by 19majkel94** [comment]
Thanks! I thought that it will join to `product.user`, not to `product.category.user` 😉 

QueryBuilder are more powerfull but my custom repository is extending an `Repository` to have access to `persist` or `create` without copy-paste boilerplate code.

**Comment by mibanez** [comment]
What about returning a default value when join doesn't return any relation? Like an empty array or null

**Comment by 19majkel94** [comment]
In non lazy relation, if you do `leftJoinAndSelect` you will get undefined on relation property and on `innerJoinAndSelect` you will get undefined object (like returning no rows in select query). Haven't tested the lazy relations yet due to this #46 bug.

BTW, @pleerock could you update repository types to TS 2.0? `findOne` and `findOneById` should return `Promise<Entity | undefined>` 😉

**Comment by mibanez** [comment]
Mmm that makes sense, specially when the relation is not loaded. Now, if the relation is explicitly loaded and no rows are returned, wouldn't be better to return an empty array? I mean, the relation does exist and was required so i'm expecting it as a member of my entity.

**Comment by 19majkel94** [comment]
If it's `OneToMany`, you will get an empty array. If it's `OneToOne` or `ManyToOne` - undefined.
Of course when it works ok - now it's not working due to wrong sql syntax 😜

**Comment by mibanez** [comment]
That's why then, thanks :)

**Comment by pleerock** [comment]
@19majkel94 PRs haha 😈  This is something that needs to be done (and easy to do in most obvious places ;)) Right now Im pretty busy with refactoring of persistent mechanizm to solve some small and hard fixable bugs...

**Comment by 19majkel94** [comment]
It's 15s change in function declarations - do it in next npm release, PM is waste of time and resources 😜

**Comment by pleerock** [comment]
> BTW, @pleerock could you update repository types to TS 2.0? findOne and findOneById should return Promise<Entity | undefined> 😉

@19majkel94 done in 57e13f6

**Comment by jcrben** [comment]
@19majkel94 if it's so easy couldn't you you have made a pull request? doesn't seem right to hassle someone who is already so busy and *volunteering• his time...

**Comment by pleerock** [comment]
@19majkel94 is awesome guy and made lot of contributions in different other libraries, strange that he is still not in contributors list of typeorm

**Comment by 19majkel94** [comment]
@pleerock thanks :relaxed:
typeorm is really big library so it's not as easy to contribute like class-validator or routing-controllers and I have no experience with ORMs so I can only suggest in issues what I would like to have or change the behavior 

@jcrben 
I left this for pleerock because updating this two types was just a part of upgrading to TS 2.0 - I haven't know which other functions or methods might needed type change as find* was.

**Comment by pleerock** [comment]
thats easy to get started with something small and little by little make bigger and bigger contributions. There are really lot of small tasks that can be implemented easily ;)

**Comment by pleerock** [comment]
Eager relations are added in `0.1.0-alpha.44`. Docs can be found [here](https://github.com/typeorm/typeorm/blob/master/docs/relations.md#eager-relations).
