### ISSUE TITLE
still not support int array in Postgres?

### ISSUE THREAD

**Issue by Rwing** [typeorm/typeorm#460]
table

```
CREATE TABLE test
(
    a INTEGER[]
);
```

and entity.ts

```
export class test {
    @Column("simple_array")
    a: number[];
}
```

and insert a record
```
let t = new test();
t.a = [1,2,3];
repository.persist(t);
```
I got a error

> nodejs.error: malformed array literal: "1,2,10"
    at Connection.parseE (/Users/XXX/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/Users/XXX/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/Users/XXX/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
name: 'error'
length: 142
severity: 'ERROR'
code: '22P02'
detail: 'Array value must start with "{" or dimension information.'
hint: undefined
position: undefined
internalPosition: undefined
internalQuery: undefined
where: undefined
schema: undefined
table: undefined
column: undefined
dataType: undefined
constraint: undefined
file: 'arrayfuncs.c'
line: '319'
routine: 'array_in'

**Comment by NoNameProvided** [comment]
Simply use `autoSchemaSync: true` and it will work. 

Simple array behind the scenes is a comma separated string, so `[1, 2, 3, 4]` will become `"1,2,3,4"`.

**Comment by Rwing** [comment]
Sorry, I didnt catch your meaning, the field's type is INTEGER[] in database, so string "1,2,3,4" can't insert into database yet.

**Comment by NoNameProvided** [comment]
When you write: 

```
@Column({ type: 'simple_array', default: '' })
categories: number[];
```

The created field by TypeORM is a `text` field.

The table you create by hand is incorrect, you should create:

```sql
CREATE TABLE test(a TEXT NOT NULL);
``

**Comment by Rwing** [comment]
I got it, but for same reason, I can't change the database schema so the field must be INTEGER[] 😢

**Comment by Rwing** [comment]
I solved it by a temp solution :
use return value instant of at this line
https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L235

**Comment by pleerock** [comment]
postgres-specific array support will be in the future versions of typeorm

**Comment by Rwing** [comment]
is there a dated schedule/roadmap?

**Comment by pleerock** [comment]
not soon. right after #344 which is non trivial to implement.

**Comment by pleerock** [comment]
"simple array" type and postgres arrays are different. Support for postgres array is implemented in latest typeorm versions. See [here](https://github.com/typeorm/typeorm/blob/master/test/functional/database-schema/column-types/postgres/entity/Post.ts) example how to use them

**Comment by adnan-kamili** [comment]
I tried version 0.1.0-alpha.33 but it throws:

`type \"function Array() { [native code] }\" is not supported in \"postgres\" database."`

Has the change been published to the npm? Or in which version can we expect the feature?

**Comment by pleerock** [comment]
you can see tests which work fine. Can you provide a code snippet?

**Comment by hpop** [comment]
I had the same problem as @adnan-kamili an fixed it by setting the column to:
```
@Column({type: String, isArray: true})
roles: string[];
```

**Comment by coolboygym** [comment]
@pleerock  I solved this problem using the code in the [example](https://github.com/typeorm/typeorm/blob/master/test/functional/database-schema/column-types/postgres/entity/Post.ts).  Thanks !

@Column("int", { isArray: true })
    array: number[];

**Comment by codeandcats** [comment]
I'm also having trouble with enum array column types in Postgres.

I have a `User` entity which can have zero or more roles, and looks like this:

```typescript
@Entity()
export class User {
  ...
  @Column('simple_array')
  roles: UserRole[];
}

export type UserRole = 'techAdmin' | 'productOwner';
```

However I am unable to insert new users into the database, instead it errors with: `malformed array literal: "techAdmin,productOwner"`

So I tried using the suggested `isArray` option:

```typescript
@Column('enum', { isArray: true })
roles: UserRole[];
```

This lets me insert users now and the data in the table looks right, however when typeorm selects a user the role field is a string instead of a string array. 😢

Has anyone else having this issue? Any ideas how to solve/workaround this?

**Comment by codeandcats** [comment]
Okay, I just discovered the `transformer` option so I believe I've worked around the issue like so:

```typescript
export const typeOrmUserRoleTransformer = {
  to: (value: string[]): string[] => value,
  from: (value: string): string[] => value.replace(/\{|\}/g, '').split(',')
};

@Entity()
export class User {
  ...
  @Column('enum', {
    isArray: true,
    enum: userRoles,
    transformer: typeOrmUserRoleTransformer
  })
  roles: UserRole[];
}
```

The `from` function takes a string value like `'{techAdmin,productOwner}'` and replaces it with an array like `['techAdmin', 'productOwner']` which is what I want.

**Comment by t3hmrman** [comment]
BTW if anyone's run into this recently, here's what worked for me:

```js
@Column({type: String, array: true, enum: Role})
roles: Role[]; 
```

**Comment by kodayashi** [comment]
> "simple array" type and postgres arrays are different. Support for postgres array is implemented in latest typeorm versions. See [here](https://github.com/typeorm/typeorm/blob/master/test/functional/database-schema/column-types/postgres/entity/Post.ts) example how to use them

@pleerock - I'm a bit confused, your example shows how to create a native postgres array of ints, but when I try to create a native array of strings with:

```javascript
    @Column("string", { array: true })
    array: string[];
```

I get a lint error:

> [ts] Argument of type '"string"' is not assignable to parameter of type '(type?: any) => Function'.

**Comment by t3hmrman** [comment]
Hey @kodayashi, here's how I solved that. I will admit the documentation is a little confusing but eventually I got it working:

```
    @Column("enum", {array: true})
    public readonly roles: Role[] = [];
```

Also this:

```
    @Column({type: "text", array: true})
    public readonly roles: Role[] = [];
```

Alternatively:

```
    @Column({type: "text", array: true})
    public readonly roles: string[] = [];
```

I use Postgres, so `text` is the easiest-to-use variable length text type, could also have used `varchar` I guess.

Also, your error isn't a lint error, it's a TypeScript error itself, maybe your linter is just reporting it.

**Comment by kodayashi** [comment]
@t3hmrman - Nailed it, the third option is what i was looking for

```javascript
  @Column({type: 'text', array: true, nullable: true })
  optionalArrayOfStrings: string[];
```

**Comment by kaousheik** [comment]
Is storing array of json objects possible in pg

**Comment by RobbieGM** [comment]
@kaousheik You should probably just use `@Column('simple-json')` and store the JSON objects inside a JSON array.
