### ISSUE TITLE
Node Cluster with Typeorm

### ISSUE THREAD

**Issue by chukhlov** [typeorm/typeorm#4604]
**Issue type:**
When application working with nodejs cluster, typeorm with option `synchronize: true` doing synchronization, each of nodes trying to create the same table in the database.

After tables created part of nodes throw exceptions like:
`duplicate key value violates unique constraint "pg_type_typname_nsp_index"`
`relation "users" already exists`

How to configure typeorm for node cluster to away of the issue?

**Database system/driver:**
[ ] `postgres`

**TypeORM version:**
[ ] `latest`

<img width="596" alt="Screen Shot 2019-08-19 at 4 54 07 PM" src="https://user-images.githubusercontent.com/49238231/63271098-0ff95600-c2a2-11e9-8c3c-06caf006212f.png">
<img width="401" alt="Screen Shot 2019-08-19 at 4 54 12 PM" src="https://user-images.githubusercontent.com/49238231/63271105-138cdd00-c2a2-11e9-9350-b9ae45f57819.png">
<img width="539" alt="Screen Shot 2019-08-19 at 4 54 20 PM" src="https://user-images.githubusercontent.com/49238231/63271113-1556a080-c2a2-11e9-8b64-f90a9071dc2d.png">

**Comment by nionoku** [comment]
This is what the documentation says about the synchronize parameter:
> `synchronize` - Indicates if database schema should be auto created on every application launch. Be careful with this option and don't use this in production - otherwise you can lose production data. This option is useful during debug and development. As an alternative to it, you can use CLI and run `schema:sync` command. Note that for MongoDB database it does not create schema, because MongoDB is schemaless. Instead, it syncs just by creating indices.

You can use `schema:sync` command before running your application.
