### ISSUE TITLE
Parameterization with Wildcards

### ISSUE THREAD

**Issue by nrcmkoh** [typeorm/typeorm#4605]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

**Description**
When a query contains a `WHERE field LIKE` and a `WHERE field =`, it is applying the parameter of the latter one to both where clauses.

**Steps to reproduce or a small repository showing the problem:**

1. On query builder, add an `andWhere` (or `where` if first predicate), where you are using the `LIKE` operator with string parameter containing wildcard
2. On query builder, add another `andWhere`, where you are using the `=` operator with string parameter
3. Observe that both parameters are missing the wildcard. When Steps 1 and 2 are reversed, both parameters contain the wildcard.

This code snippet:
```ts
    let a = "abcd%";
    let b = "abcd";
    qb = qb
      .andWhere("lbk.value like :value", { value: a })
      .andWhere("fbk.value = :value", { value: b });
```

Produces this result when I write the generated SQL to console:

>  AND "lbk"."Value" like @2 AND "fbk"."Value" = @3 -- PARAMETERS: [3543,false,"abcd","abcd"]

**Comment by silentroach** [comment]
Try to use `Like` operator https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#advanced-options

```typescript
.where({
    value: Like("abcd%")
})
```

**Comment by nrcmkoh** [comment]
> Try to use `Like` FindOperator https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#advanced-options
> 
> ```ts
> .where({
>     value: Like("abcd%")
> })
> ```

Thanks for the suggestion, but then what about the aliases?
