### ISSUE TITLE
Feature: SIMILAR TO helper

### ISSUE THREAD

**Issue by osdiab** [typeorm/typeorm#4607]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

There are helpers for using operators like `LIKE` with TypeORM's `find` options, but not the `SIMILAR TO` SQL operator, it seems. Would be nice to have one for that.

**Comment by imnotjames** [comment]
We won't be adding dialect specific operators but you can use the new raw features

```
const SimilarTo = value => Raw(alias => `${alias} SIMILAR TO :value`, { value });
```
