### ISSUE TITLE
Self referencing belongs to

### ISSUE THREAD

**Issue by craigcartmell** [typeorm/typeorm#4616]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

Quick question regarding setting up a "belongs to" or equivalent relation. I'd like to add  `createdBy`, `updatedBy`, etc columns to my entities, which would contain a user id. The user itself will also have these columns.

Currently when I save a new user, passing the existing user in `createdBy`, `createdBy` always ends up as NULL in the database.

Here's my code, probably a silly mistake on part if anyone can spot anything?

```
// user-entity.ts

import { Column, Entity, JoinColumn, OneToOne, PrimaryColumn } from 'typeorm'
import uuid from '../helpers/uuid'

@Entity({ name: 'users' })
export class UserEntity {
  @PrimaryColumn()
  public id: string

  @Column()
  public externalId: string

  @OneToOne(type => UserEntity, { nullable: true })
  @JoinColumn({ name: 'id' })
  public createdBy: UserEntity

  @Column({ type: 'time with time zone', nullable: false })
  public createdAt: Date

  @OneToOne(type => UserEntity, { nullable: true })
  @JoinColumn({ name: 'id' })
  public updatedBy: UserEntity | null

  @Column({ type: 'time with time zone', nullable: true })
  public updatedAt: Date | null

  @OneToOne(type => UserEntity, { nullable: true })
  @JoinColumn({ name: 'id' })
  public deletedBy: UserEntity | null

  @Column({ type: 'time with time zone', nullable: true })
  public deletedAt: Date | null
}

```

```
// my resolver

 const repository = connection.getRepository(UserEntity.name)

 const existingUser = (await repository.findOne()) as UserEntity

 const newUser = await repository.save({
   id: uuid(),
   externalId: uuid(),
   createdAt: new Date(),
   createdBy: existingUser,
})
```

**Comment by imnotjames** [comment]
We have tests that show that this feature works in TypeORM.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
