### ISSUE TITLE
Require cycle warnings under React Native

### ISSUE THREAD

**Issue by jrr** [typeorm/typeorm#4617]
Though Webpack seems to tolerate require cycles by default, [Metro](https://github.com/facebook/metro) (React Native's bundler) emits a bunch of warnings at startup of the form:

> [Warning] Require cycle: node_modules/typeorm/browser/index.js -> node_modules/typeorm/browser/connection/ConnectionManager.js -> node_modules/typeorm/browser/connection/Connection.js -> node_modules/typeorm/browser/error/EntityMetadataNotFoundError.js -> node_modules/typeorm/browser/index.js (blob:http://localhost:8081/0039e485-31c4-46d2-bd6e-a5a9afad21a2, line 83)
> 
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

I currently have 57 instances from `browser/index.js`, and 1 from `browser/schema-builder/RdbmsSchemaBuilder.js`.

It's [debatable](https://github.com/facebook/metro/issues/287) whether this warning has merit, but for now TypeORM could provide a much better getting started experience with React Native if it didn't cause a bunch of warnings in the JS console.

**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**Comment by Kononnable** [comment]
I understand the issue, and agree about bad user experience in this area however I'm gonna close it.
With the way typeorm is implemented getting away from cycle warnings would require rewriting most of library code. Some of the work in this area is planned for 0.4.0(whenever it will be released), but I don't think it would be possible to remove all of them.

**Comment by likern** [comment]
> I understand the issue, and agree about bad user experience in this area however I'm gonna close it.
> With the way typeorm is implemented getting away from cycle warnings would require rewriting most of library code. Some of the work in this area is planned for 0.4.0(whenever it will be released), but I don't think it would be possible to remove all of them.

Cycle dependencies might lead to errors in [Hermes JS engine ](https://hermesengine.dev/) which might become de-facto standard in React Native (at least new Reanimated 2 library supports only Hermes on Android).

I'm still investigating, but it looks like Hermes error
```bash
[Tue Jun 23 2020 23:42:49.869]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
```
is because of TypeORM cycle dependencies.

**Comment by josephmbeveridge** [comment]
@likern were you able to fix your issues running TypeORM on hermes? I'm coming across the same issue now and haven't been able to find any good resources

**Comment by likern** [comment]
> @likern were you able to fix your issues running TypeORM on hermes? I'm coming across the same issue now and haven't been able to find any good resources

Yes, my comment is invalid. I think warning about cycle dependencies are not related to issues I had wit Hermes.
TypeORM should work fine, without tweaks, on Hermes as far as I remember.
Good chance the issues you have related to Hermes itself.
