### ISSUE TITLE
Bulk update of over 1000 entities causes abnormally large SQL expression tree

### ISSUE THREAD

**Issue by tylerjwatson** [typeorm/typeorm#462]
Hi,

Given I have an entity of the following prototype which has a self-referencing one-to-many relationship: 

```ts
@Entity('FieldDefinition')
export class FieldDefinition extends ListItem {

    @ManyToOne(type => ItemDefinition, itemDef => itemDef.Fields, { cascadeAll: true, onDelete: 'CASCADE' })
    @JoinColumn({ name: 'ItemDefinitionId' })
    Definition: ItemDefinition;

    @OneToMany(type => FieldDefinition, fieldDef => fieldDef.LookupTarget)
    LookupDestinations: FieldDefinition[] = [];

    @ManyToOne(type => FieldDefinition, fieldDef => fieldDef.LookupDestinations, { nullable: true, onDelete: 'SET NULL' })
    @JoinColumn({name: 'LookupTargetId'})
    LookupTarget?: FieldDefinition;

    ...
}
```

And perform a bulk update of each `FieldDefinition` like in  the following code:

```ts
for (let itemDef of tenantSite.ItemTypes.filter(i => i.TypeValue !== 'System')) {
	for (let fieldDef of itemDef.Fields.filter(f => f.TypeValue === 'Lookup')) {
		let lookupTarget = await this.setLookup(entityManager, tenantSite, fieldDef);

		if (lookupTarget) {
		    fieldDef.LookupTarget = lookupTarget;
		}
	}
}
```

It causes an abnormally large SQL statement, which, on SQLite at least is far too big to execute. I'll attach it here because the statement is too big to paste into the body of this issue.

[sqlite_error.txt](https://github.com/typeorm/typeorm/files/988933/sqlite_error.txt)

I am trying to trawl though the query builder to find what could generate this, but in the meantime, is there something I can do to workaround this issue?  Do I chunk the updates/persists into batches of 100 or something?

Thanks!

**Comment by seb777** [comment]
Can be a solution : http://stackoverflow.com/a/17032196
but requires changes in typeorm

**Comment by tylerjwatson** [comment]
I am thinking more along the lines of `WHERE Id IN (...)`

**Comment by pleerock** [comment]
typeorm has lot of features and each even small but useful feature can add extra queries to make them work. Of course there are rooms for optimization, but right now there are lot of features that left to be done before those optimizations. In the future I'll add methods to do bulk insertions with all those orm features disabled.

**Comment by tylerjwatson** [comment]
> typeorm has lot of features and each even small but useful feature can add extra queries to make them work. 

We know, that's why this library is so great :)

This is a rather large problem for me at the moment, can you please point me in some direction so that I may look at fixing the issue?  I am working on it, but it is a rather large codebase to try and get my head around in a night :) I assume you are willing to accept PR's to fix issues?

**Comment by pleerock** [comment]
I don't think that right now design allows you to create a good PR for this feature, it needs some refactoring before it can be done properly. If you have such problem I suggest you to prepair results manually and execute raw sql query. Or you can do it via `connection.driver.createQueryRunner().insert` method. I don't there is an elegant way of doing this at the moment.

**Comment by pleerock** [comment]
bulk insertion is supported via QueryBuilder in latest 0.1.0 versions. Example: 

```ts
        await connection.createQueryBuilder()
            .insert()
            .into(User)
            .values([
                { name: "Umed Khudoiberdiev" },
                { name: "Bakhrom Baubekov" },
                { name: "Bakhodur Kandikov" },
            ])
            .execute();
```

**Comment by tahir-jamil** [comment]
> bulk insertion is supported via QueryBuilder in latest 0.1.0 versions. Example:
> 
> ```ts
>         await connection.createQueryBuilder()
>             .insert()
>             .into(User)
>             .values([
>                 { name: "Umed Khudoiberdiev" },
>                 { name: "Bakhrom Baubekov" },
>                 { name: "Bakhodur Kandikov" },
>             ])
>             .execute();
> ```

but it does not support relations
