### ISSUE TITLE
How to get rid off table columns without double quotes at all for all operations?

### ISSUE THREAD

**Issue by engmsaleh** [typeorm/typeorm#4624]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Could I have the database table columns names without double quotes at all on all operations?

**Comment by keithics** [comment]
+1

**Comment by imnotjames** [comment]
Unfortunately, I'm having a bit of trouble parsing your question.

Perhaps try asking it (or other questions) on the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
