### ISSUE TITLE
Saving empty string array

### ISSUE THREAD

**Issue by yulric** [typeorm/typeorm#463]
Hi there,

I have a field which is an Array<string> and it is defined as a simple_array in the Column decorator. But when I save an empty array in the database and then retrieve it, it comes back with a single entry that is an empty string. I can provide code if needed.

Edit: using version 0.0.11 and postgres

Thanks

**Comment by pleerock** [comment]
yes please provide a minimal reproduction code example.

**Comment by yulric** [comment]
A simple entity with a string array
```
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class EntityWithArray {
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column('simple_array')
   simpleStringArray: Array<string>;
}
```

Code that saves a new entity and retrieves it
```
let entityWithArray = new EntityWithArray();
entityWithArray.simpleStringArray = [];

await getConnection()
    .entityManager
    .getRepository(EntityWithArray)
    .persist(entityWithArray);

const savedEntity = await getConnection()
    .entityManager
    .getRepository(EntityWithArray)
    .findOne({});
```

If you look at the simpleStringArray field in the savedEntity const it's an array with an empty string inside it

**Comment by pleerock** [comment]
Bug is fixed and will be released in `0.1.0-alpha.33`

**Comment by yulric** [comment]
Thank you

**Comment by sandrooco** [comment]
Quick follow up to this question:
```
@Column()
public roles: string[];
```
will create the following migration line:

```
await queryRunner.query("ALTER TABLE `dbxy`.`user` ADD `roles` function Object() { [native code] } NOT NULL");
```

Why does that happen? Is there anything I have to setup for using primitive array types/not relations @pleerock ?
