### ISSUE TITLE
Postgresql migrations result in entire database schema being recreated

### ISSUE THREAD

**Issue by wallopthecat** [typeorm/typeorm#4632]
**Issue type:**

[x] bug report

**Database system/driver:**
[x] `postgres`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**
Basic config, no sync. Postgresql docker container running on windows host. 

When I run `typeorm migration:generate -n newMigration`, TypeORM always generates a migration file (regardless of whether the entities have been changed), and this migration is a single-migration setup of the entire database schema (including any new additions). OP in issue also was on Windows, unsure if that matters

Same exact issue, different db driver, described here:
https://github.com/typeorm/typeorm/issues/4362
https://stackoverflow.com/questions/52800204/typeorms-migrationgenerate-regenerates-the-whole-database-schema

**Comment by mcrawshaw** [comment]
You misunderstand how `generate` works.  When you run the command it looks at the schema of the **actual** database (it doesn't care about existing `build/server/migrations/*`), then compares it with your `build/server/entity/*` files.  The difference between the 2 is what is generated.

To create a new migration, run the following commands (in order):
- `typeorm migration:drop`
- `typeorm migration:run`
- `typeorm migration:generate -n [NAME]`

**Comment by wallopthecat** [comment]
fix is apparently removing `{schema: 'public'}` from the @Entity def

**Comment by mcrawshaw** [comment]
Ah, it must have had trouble comparing the schema with the db.  Sorry for the misunderstanding.
