### ISSUE TITLE
Batch insert for `ManyToMany` when having extra column? 

### ISSUE THREAD

**Issue by thismarcoantonio** [typeorm/typeorm#4633]
**Issue type:** question
**Database system/driver:** `postgres`
**TypeORM version:** `latest`

I have two two tables which are connected as many to many and need to have an extra field. In the case of many to many with extra field, how can I batch insert data? I receive a lot of second table ids to insert in the database at once? There's any better option than loop through them?

Also, I've read this issue: https://github.com/typeorm/typeorm/issues/1025

Thanks 👍

**Comment by PedramMarandi** [comment]
@thismarcoantonio Have you found any solution for this question?

**Comment by thismarcoantonio** [comment]
@PedramMarandi Yes I did. I just tried to create an array with the entities that I wanted to insert in the relation table. I had the itemsToInsert, so I easily could create something like:

```
      await entityManager.save(
        itemsToInsert.map((item, index) => 
          ManyToManyEntity.create({
            item,
            anotherOne,
            ... // here you can insert all other custom columns
          })
        )
      )
```

The names are modified, but I think you can understand what's going on.
