### ISSUE TITLE
Problems working with repository.count

### ISSUE THREAD

**Issue by nobiit** [typeorm/typeorm#4634]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
@Entity()
export abstract class EntityAbstract {
    @ObjectIdColumn()
    _id: ObjectID;

	@Column()
	name: string;

    @CreateDateColumn({type: 'timestamp', update: true})
    createdAt: Date;

    @UpdateDateColumn({type: 'timestamp'})
    updatedAt: Date;

    @Column({type: 'timestamp'})
    deletedAt: Date;
}
```
```ts
console.log(await this.repository.find({where: {deletedAt: {$exists: true}}})); // ok, return 2 record
console.log(await this.repository.count({where: {deletedAt: {$exists: true}}})); // opps, return 0
```

**Comment by playahater** [comment]
Perhaps not a best way to address the issue, but let me do it here for start and we can move it in a separate issue if needed.

**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I can reproduce the same issue with mysql driver.
Seem like that repository.count is not returning correct count results in my case as well.

have a simple condition in it:
`repository.count({ ColumnA: valueA, ColumnB: ValueB });`

**Comment by nobiit** [comment]
@playahater It seems too many issues and the author is quite busy. I think in the meantime, look for another method, though it is not as effective. And once they find a solution to this problem, we will continue

**Comment by playahater** [comment]
Yeah, no problem. Already found a workaround.

Thanx

**Comment by PizzaPartyInc** [comment]
Hey!

Can anyone share a workaround? Have the same issue while working with postgres. Tried it with typeorm 0.2.22 and 0.3.0-alpha.24, 0 is returned in both versions if filtering options are provided.

**Comment by playahater** [comment]
I've used the raw query() method [ [repository-api](https://typeorm.io/#/repository-api) | [entity-manager-api](https://typeorm.io/#/entity-manager-api) ] instead of count() and resolved the issue for now.
Not that clean, but works.

**Comment by danmana** [comment]
I ran also into this issue when Using `Repository`.

The problem is the typings.

The more generic `Repository` class has three signatures for count:
```ts
count(options?: FindManyOptions<Entity>): Promise<number>;
count(conditions?: FindConditions<Entity>): Promise<number>;
count(optionsOrConditions?: FindManyOptions<Entity>|FindConditions<Entity>): Promise<number>;
```

But `MongoRepository` implementation only has
```ts
count(query?: ObjectLiteral, options?: MongoCountPreferences): Promise<number>;
```
This is equivalent to the second signature, the one with `FindConditions`

So in case you are using Mongo you can only use the second signature from Repository
```ts
// good signature
repository.count({ myField: "myValue"});

// bad signature, even if the typing says it's valid !
repository.count({ where: { myField: "myValue"}});
```



You have two options:
* you take care and always use just the second signature
* or you switch the type of your repository to `MongoRepository` and get the correct typings

**Comment by imnotjames** [comment]
Yep - because we pass everything directly to the underlying mongo client there's not much we can do here.

This is a very specific tradeoff chosen when implementing the mongo driver & changing it would be akin to rewriting the driver.
