### ISSUE TITLE
Tell repository to use entityManager

### ISSUE THREAD

**Issue by Lennard-Dietz** [typeorm/typeorm#4635]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am using TypeORM in combination with NestJS to build a backend server. To be able to handle my different entities from different parts in the application i created a service for every entity, that can be injected into the other parts. These services use the `@InjectRepository(...)` decorator to inject the needed repository for the entity.

Now let`s say i have an `afterInsert` hook created by an `EntitySubscriberInterface`, i need to use the `entityManager` from the given `insertEvent` to be able to add queries to the active queryrunner, so they are run in the same transaction.

So my question is:
Is there a built in way to be able to tell an injected repository to use a specific `entityManager` instance, so all queries are run in the same transaction?

Or would i always need to create a new repository instance based on the `entitiyManager` that holds my current transaction?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
You always need to create a new repository. 

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
