### ISSUE TITLE
Run transaction on injected repositories

### ISSUE THREAD

**Issue by BenBeri** [typeorm/typeorm#4639]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there a way to run a transaction on injected repositories?
https://stackoverflow.com/questions/57656893/typeorm-run-transaction-on-provider-level/57659041#57659041

**Comment by imnotjames** [comment]
You'd need to start the transaction via the `EntityManager` as transactions are not exposed via the `Repository`.  I think there was also an interesting response on your stackoverflow.

If that didn't solve your question, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
