### ISSUE TITLE
"Not(true)" doesnt work on Null Values

### ISSUE THREAD

**Issue by Logic-Bits** [typeorm/typeorm#4640]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi,

when using 
` where: { deleted: Not(true) }`
and the value in the column is null it doesnt work.

(But SQL Logic works like that : "select * from address where deleted is not true")

Thanks!

**Comment by silentroach** [comment]
it is translated to `deleted != true` and it is not the same as `deleted is not true`

why not use `{ deleted: Not(IsNull()) }` ?

**Comment by ardyfeb** [comment]
> it is translated to `deleted != true` and it is not the same as `deleted is not true`
> 
> why not just use `{ deleted: IsNull() }` ?

Whats about `IS NOT NULL` ?

**Comment by BrandLibel** [comment]
I've tried using Raw(), e.g. `where: { deleted: Raw('IS NOT TRUE') }` evaluates to `deleted = IS NOT TRUE` which is also incorrect.

It would be helpful to have a way to do `IS NOT TRUE` using this API, without QueryBuilder

**Comment by imnotjames** [comment]
That's because it should be:

```
Raw(alias => `${alias} IS NOT TRUE`)
```

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
