### ISSUE TITLE
Is it possible to create an entity member that will group other members with OneToMany relations under a single class?

### ISSUE THREAD

**Issue by nosteiner** [typeorm/typeorm#4647]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

There is an entity which has oneToMany relations with other entities.
is it possible to group some of them in a class that has no representation in the DB, or in other words - is not an entity?

For example: 
There is an entity `Patient` which has relations with the entities: `PatientAlergy, PatientSymptom, MedicalCondition, etc...`

I would like to group all of those in a single class `MedicalHistory` so that `Patient` will have a member `medicalHistory`.

Is is possible to give this `medicalHistory` field a deecorator to define it so that the ORM will recognize it?

I tried looking for an answer in the docs and examples, but didn't find anything useful. 

 patient.entity.ts:

    @Entity()
    @ObjectType()
    @InputType('patient')
     export class Patient extends BaseEntity {
      @PrimaryGeneratedColumn()
      @Field(type => ID, { nullable: true })
      id: number

      @Field(type => MedicalHistory, { nullable: true })
      //@SomeDecorator()
      medicalHistory?: MedicalHistory
    }

madical-history.dto.ts:
```
@ObjectType()
@InputType('medicalHistory')
// @SomeOtherDecorator()
export class MedicalHistory {
  @Field(type => MedicalCondition, { nullable: true })
  @OneToMany(type => MedicalCondition, medicalCondition => medicalCondition.patient, { cascade: true })
  medicalConditions: MedicalCondition[]

  @Field(type => FamilyMedicalCondition, { nullable: true })
  @OneToMany(type => FamilyMedicalCondition, familyMedicalCondition => familyMedicalCondition.patient, { cascade: true })
  familymedicalConditions: FamilyMedicalCondition[]

  @Field(type => PatientAlergy, { nullable: true })
  @OneToMany(type => PatientAlergy, patientAlergy => patientAlergy.patient, { cascade: true })
  alergies: PatientAlergy[]

  @Field(type => PatientProcedure, { nullable: true })
  @OneToMany(type => PatientProcedure, patientProcedure => patientProcedure.patient, { cascade: true })
  procedures: PatientProcedure[]

  @Field(type => PatientSymptom, { nullable: true })
  @OneToMany(type => PatientSymptom, patientSymptom => patientSymptom.patient, { cascade: true })
  symptoms: PatientSymptom[]
}
```

I would love to know if there is an option to describe the patient's medical history that way.,

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
