### ISSUE TITLE
TypeORM OpenCollective does not show up on BackYourStack

### ISSUE THREAD

**Issue by dantman** [typeorm/typeorm#4649]
I uploaded the package.json for a project of mine using TypeORM to https://backyourstack.com/ to get a list of projects we're using with OpenCollectives to try and get my client to pledge to.

However while https://opencollective.com/typeorm exists and #3267 has been trying to get people to support the library, that OpenCollective does not show up in the list. When I examine the detected dependencies it does not appear that the `typeorm` package is associated with any OpenCollective.

If the maintainers want to make more people aware of the TypeORM OpenCollective, https://backyourstack.com/faq suggests that the owners of the collective should contact OpenCollective support.

**Comment by imnotjames** [comment]
Pretty sure this is because the `funding` element is not in the package manifest.
