### ISSUE TITLE
How to use a sql function in TypeORM?

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#465]
I need update a field using sql function. How can I do?
For example:
```sql
UPDATE User SET lastLoggedInAt = NOW() WHERE id = 1
```

**Comment by pleerock** [comment]
using raw sql query, e.g. `connection.entityManager.query(`UPDATE User SET lastLoggedInAt = NOW() WHERE id = 1`)`

**Comment by Diluka** [comment]
what about using query builder or update method? How can I pass sql function to those?

**Comment by pleerock** [comment]
no, custom functions aren't supported by query builder

**Comment by Diluka** [comment]
If I want to use built-in function `GROUP_CONCAT()` in `SELECT`, only can I use raw query too?

**Comment by pleerock** [comment]
no in selects you can use custom functions, just make sure not to change selected result and make sure your functions aren't affected transformation to real entity.

**Comment by badcoder28** [comment]
Hi @pleerock is there any examples/demo how to use `getEntityManager.query()`? I would like to see if it is possible to get a raw database results in json format. 

I found this [query](https://typeorm.github.io/entity-manager.html#api.entityManager.query) function document but there is no usage examples.

Thanks!

**Comment by pleerock** [comment]
its quite simple:

```ts
const results = await entityManager.query(`SELECT * FROM table`);
```

**Comment by badcoder28** [comment]
Its working now and that's elegant thanks!

**Comment by pleerock** [comment]
as of `0.1.0-alpha.25` you can use sql functions in update expression this way:

```ts
await connection.createQueryBuilder()
            .update(User)
            .set({ name: () => "SUBSTR('Diluka', 1, 4)" })
            .where("name = :name", { name: "Diluka" })
            .execute();
```

**Comment by bestickley** [comment]
This is actually possible. I've gotten it working for SQL Server but I would think it would work for other DBs. Use a view entity with the name of the table as the function expression with parameters that you set later.
Example:
```ts
@ViewEntity({
  schema: "Maaps",
  name: "QuestionnaireTable(:echelon, :startDate, :endDate, :orgId)",
})
export class QuestionnaireTable {
  @ViewColumn()
  completionDate: Date;
  @ViewColumn()
  dueDate: Date;
  @ViewColumn()
  firstName: string;
  @PrimaryGeneratedColumn()
  id: number;
}
```
Then:
```ts
createQueryBuilder(QuestionnaireTable, "qTable")
.setParameters({ echelon: 2, startDate: "2020-10-10", endDate: "2020-10-10", orgId: ""});
.getManyAndCount();
```
Hope this helps someone!

**Comment by rrrix** [comment]
@bestickley I can't get that one to work, it gives me an error `TypeError: view.expression is not a function`. 

Using PostgreSQL 11.

How are you getting around not having an `expression: '...'` property in the `@ViewEntity()` decorator options?

```
creating a new view: application_hierarchy(:org_id, :group_ids)
query: ROLLBACK
Error during schema synchronization:
TypeError: view.expression is not a function
    at PostgresQueryRunner.createViewSql (src/driver/postgres/PostgresQueryRunner.ts:1783:86)
```

```typescript
import { ViewColumn, ViewEntity } from 'typeorm';

@ViewEntity({
  name: 'application_hierarchy(:org_id, :group_ids)',
})
export class ApplicationHierarchy {
  @ViewColumn({ name: 'group_id' })
  groupId: string;

  @ViewColumn({ name: 'organization_id' })
  organizationId: string;
}
```

**Comment by bestickley** [comment]
@rrrix, I don’t use TypeORM to create my tables and functions in the DB. My team has separate SQL scripts that create all our tables and functions.
Maybe there is a way in TypeORM to mark this “view” to not be created?

**Comment by fullstackzach** [comment]
I was hopeful that @rrrix's example would be applicable to Posgresql stored functions as well. unfortunately it does not seem that TypeORM can find them.

I see an error `relation "<schema>.<fn>($1)" does not exist QueryFailedError: relation "<schema>.<fn>($1)" does not exist` .. Although the schema and function name is correct.

**Comment by Segev95** [comment]
> I was hopeful that @rrrix's example would be applicable to Postgresql stored functions as well. unfortunately it does not seem that TypeORM can find them.
> 
> I see an error `relation "<schema>.<fn>($1)" does not exist QueryFailedError: relation "<schema>.<fn>($1)" does not exist` .. Although the schema and function name is correct and it exists.

I got the same error. it is because the parenthesis are on the param as well. if it were `relation "<schema>.<fn>"($1)` it would work, but I don't think TypeORM supports that yet...
