### ISSUE TITLE
save is not update

### ISSUE THREAD

**Issue by AntoninSorrento** [typeorm/typeorm#4650]
**Issue type:**

[ ] question
[ √] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ √] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[√ ] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

![image](https://user-images.githubusercontent.com/26902024/63823187-832b5800-c985-11e9-860f-e6ba710eb919.png)

![image](https://user-images.githubusercontent.com/26902024/63823199-90484700-c985-11e9-85ca-5e6f0220b1e0.png)

I want update verify field ，but is not

**Comment by jahuuar** [comment]
Is `id` the primary key? Then specify `id` in the entity.

**Comment by AntoninSorrento** [comment]
@jahuuar  
![image](https://user-images.githubusercontent.com/26902024/63986067-e55e9700-cb04-11e9-9a55-9d40d2c91866.png)

.save  It is always created and will not replace the update

**Comment by jahuuar** [comment]
And what happens if there are two or many rows with the same phone? Update all? Save function verify if there is a row on database with the "provided" primary key (`id` in your case) to update, if not, then insert one generating the primary key.

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by brunoleonardobr** [comment]
In this case:
`let i = await Model.findOne(id)
if (i) {
   i.prop = newProp
   await Model.save(i)
}`
