### ISSUE TITLE
How to Suppress SELECT query after INSERT?

### ISSUE THREAD

**Issue by nrcmkoh** [typeorm/typeorm#4651]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

I am executing the following line of code in a transaction using entity manager
```ts
await entityManager.insert(
                      CriteriaClause,
                      {
                        customerId: clause.customerId,
                        criteriaStatementId: clause.criteriaStatementId,
                        criteriaPhraseNum: clause.criteriaPhraseNum,
                        fieldName: clause.fieldName,
                        lowValue: clause.lowValue,
                        highValue: clause.highValue,
                        criteriaOperatorId: clause.criteriaOperatorId,
                        criteriaTableId: clause.criteriaTableId,
                        modifiedBy: clause.modifiedBy
                      },
                      { reload: false }
                    );
```
When this code executes, it's extremely slow because of the `select` query after the `insert`. My understanding is that setting the `reload` option to false should suppress the query. If this is not the way, how would I do that?

**Comment by liaozhongwu** [comment]
I fixed it by using save and { reload: false }, Any idea about insert?

**Comment by nrcmkoh** [comment]
It sounds like this option only works for save, which is unfortunate because save was not cascading the relationships for me. I switched over to explicitly inserting and updating all the entities in my entity graph.

One detail I forgot to mention earlier is that the query after the insert was slow due to setting the orderBy option on the entity. I resolved the issue by removing the option and performing the order by where I needed it.

**Comment by nrcmkoh** [comment]
Any plans to implement fix resolve this? I'm hitting up against this again, and I don't want to have to write raw SQL every time I need fast inserts. I feel like the reload negates the performance benefits of using `insert`, especially since it's creating a select statement for each record.

**Comment by asecher** [comment]
@nrcmkoh You can use updateEntity(false) with an insert query builder like this:

```javascript
entityManager
  .createQueryBuilder()
  .insert()
  .into("user")
  .values(users)
  .updateEntity(false)
  .execute();
```

**Comment by nrcmkoh** [comment]
> @nrcmkoh You can use updateEntity(false) with an insert query builder like this:
> 
> ```js
> entityManager
>   .createQueryBuilder()
>   .insert()
>   .into("user")
>   .values(users)
>   .updateEntity(false)
>   .execute();
> ```

I've already converted the code, and I don't want to change it now, but thank you for showing me this! I'll use it the next time I need to prevent reload.

**Comment by hypeofpipe** [comment]
You saved our costs! Great question and great answers!

**Comment by dangphu2412** [comment]
You can easily turn it off in .save() method like the code below:
`
    @Transaction()
    public async createOne(dto: LoginDto, @TransactionManager() manager?: EntityManager) {
        const user: User = new User();

        user.username = dto.username;
        user.password = dto.password;
        await manager.save(user, { reload: false });
    }
`

**Comment by coyoteecd** [comment]
For whoever ends up here, keep in mind that using `updateEntity(false)` causes your inserted identities **not** to be copied back into the object being inserted, and neither in the InsertResult.identifiers array. The workaround is to manually copy them from the raw result, which is a bit meh, especially for bulk inserts.

I added a proposal to address this [here](https://github.com/typeorm/typeorm/issues/5348#issuecomment-779748622).

**Comment by imnotjames** [comment]
This was answered.  `updateEntity(false)` prevents the select.

**Comment by FrancoCorleone** [comment]
Th provided workaround doesn't work. It should be possible to do `reload: false` on insert operation as well. Save operation updates the row if entity already exist. It definitely should be possible to do well performing insert without selecting first. We should be fine with simply catching a duplicate error and resolve it!
