### ISSUE TITLE
How to create a composite key based on foreign keys?

### ISSUE THREAD

**Issue by onkarjit** [typeorm/typeorm#4653]
<img width="832" alt="Screenshot at Aug 28 19-16-58" src="https://user-images.githubusercontent.com/26631593/63880406-f789e980-c9cd-11e9-8bae-478a4e7a68ff.png">

I'm trying to create the entities and their relationships like in the ERD above.

**User entity**

```
import {Entity, PrimaryColumn, Column, CreateDateColumn, UpdateDateColumn} from "typeorm"`

@Entity()
export class User {

    @PrimaryColumn()
    id: string;

    @Column( { type: "string", unique: true } )
    IGN: string;

    @Column()
    age: number;

    @CreateDateColumn()
    created_at: Date;

    @UpdateDateColumn()
    updated_at: Date;
}
```

**Achievement entity**

```
import {Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn} from "typeorm";

@Entity()
export class Achievement {

    @PrimaryGeneratedColumn()
    id: string;

    @Column( { type: "text", unique: true } )
    name: string;

    @Column()
    description: string;

    @CreateDateColumn()
    created_at: Date;

    @UpdateDateColumn()
    updated_at: Date;
}
```

I'm having hard time to make the user_achievement entity. Since it has foreign keys that need to be turned into composite keys. How can I accomplish this?

**Comment by onkarjit** [comment]
I did the following to accomplish this: 

**UserAchievement**

import {CreateDateColumn, Entity, ManyToOne, JoinColumn, PrimaryColumn} from "typeorm";
import { User } from "./User";
import { Achievement } from "./Achievement";

```
@Entity()
export class UserAchievement {
    @PrimaryColumn()
    user_id: string;

    @PrimaryColumn()
    achievement_id: string;

    @ManyToOne(type => User, user => user.id)
    @JoinColumn({ name: "user_id" })
    public user!: Achievement;

    @ManyToOne(type => Achievement, achievement => achievement.id)
    @JoinColumn({ name: "achievement_id" })
    public achievement!: Achievement;

    @CreateDateColumn()
    created_at: Date;
}
```

**Comment by tareqdayya** [comment]
running into same issue. Does the solution offered by @onkarjit have any negative effects? I thought i would just use number instead of the type for the foreign entity but then again the ts compiler will complain every time i try and add an object (instance of the foreign entity) instead of a numeric id.

**Comment by tareqdayya** [comment]
Ok, I was able to solve it by adding PrimaryColumn with specific type and column name (the type to match the driver and the column name to match the generated column name from the relation): e.g.
`  @PrimaryColumn({ type: 'int', name: 'songId' })
  @ManyToOne(() => Song, (song) => song.id, {
    nullable: false,
    onUpdate: 'CASCADE',
    onDelete: 'CASCADE',
  })
  @JoinColumn()
  song!: Song;

  @PrimaryColumn({ type: 'int', name: 'authorId' })
  @ManyToOne(() => Author, (author) => author.id, {
    nullable: false,
    onUpdate: 'CASCADE',
    onDelete: 'RESTRICT',
  })
  @JoinColumn()
  author!: Author;`

**Comment by tareqdayya** [comment]
And it seems you can also set **primary** option to **true** inside the relation options. This way you wouldn't have to use the @PrimaryColumn decorator:
`@ManyToOne(
    () => Author,
    (author) => author.id,
    {
      primary: true,
    },
  )`

**Comment by imnotjames** [comment]
Looks like this has been resolved.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by Jaisiero** [comment]
> And it seems you can also set **primary** option to **true** inside the relation options. This way you wouldn't have to use the @PrimaryColumn decorator:
> `@ManyToOne( () => Author, (author) => author.id, { primary: true, }, )`

Neat! Thank you.

**Comment by marines** [comment]
Mind that this option will be removed since 0.3. https://github.com/typeorm/typeorm/commit/abd4212f0c5207b3829e0a01b820058f1c9bad0f

**Comment by RDeluxe** [comment]
> Mind that this option will be removed since 0.3. [abd4212](https://github.com/typeorm/typeorm/commit/abd4212f0c5207b3829e0a01b820058f1c9bad0f)

Is it me or this commit is more than 2 years old ?

**Comment by aitchkhan** [comment]
> Is it me or this commit is more than 2 years old ?

3 years to be precise.

**Comment by 41y08h** [comment]
Here's what I've done with `@Unique` decorator;

User Entity
```ts

@Entity()
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToMany(() => Video, (video) => video.creator)
  videos: Video[];

  @ManyToOne(() => Subscriber, (subscriber) => subscriber.user)
  subscriptions: Subscriber[];

  @ManyToOne(() => Subscriber, (subscriber) => subscriber.channel)
  subscribers: Subscriber[];
}
```

Subscriber Entity
```ts
@Entity()
@Unique("subscriber", ["user", "channel"])
export default class Subscriber extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToMany(() => User, (user) => user.subscriptions)
  user: User;

  @OneToMany(() => User, (user) => user.subscribers)
  channel: User;
}

```

The way to use `@Unique` decorator is to decorate the whole class rather than any property.

**Comment by Mokdy** [comment]
monkes togethr stronk

**Comment by innokenty** [comment]
Wanna outline the solution for `typeorm 0.3.10`: setting `@PrimaryColumn` on a `@ManyToOne` column does indeed work, together with any other normal columns.

My project is not configured in a way that it picks up types and names automatically, if yours is – you can probably avoid `type` and `name` params inside column annotations.

This was enough for me:
```ts
@Entity()
export class UserAchievement {

    @PrimaryColumn({ name: 'created_by', type: 'text' })
    createdBy!: string;

    @PrimaryColumn({ name: 'achievement_id', type: 'number' })
    @ManyToOne(type => Achievement, achievement => achievement.id)
    public achievement!: Achievement;

    @CreateDateColumn({ name: 'created_at', type: 'timestamp' })
    createdAt!: Date;
}
```

It most likely works the same with both primary columns being `@ManyToOne` columns, but I didn't try it.

**Comment by humayyun00** [comment]
I also faced this problem and the solution is actually pretty simple. In the older typeorm versions you can specify {primary:true}  in you ManytoOne relation. However in the newer version typeorm has removed that option now you'll have to use @PrimaryColumn() `decorator

`export class  UserRoles {
  @PrimaryColumn({name:"role",nullable:false,unique:false})
  role: string; 

  @PrimaryColumn({name:"user_id",type:"integer",unique:false}) 
  @ManyToOne(() => User, user => user.userRoles,{nullable:true,createForeignKeyConstraints:true})   
  @JoinColumn({name:"user_id",referencedColumnName:"id"})
  public userId: User;
}`

**Comment by KevinNitroG** [comment]
> I also faced this problem and the solution is actually pretty simple. In the older typeorm versions you can specify {primary:true} in you ManytoOne relation. However in the newer version typeorm has removed that option now you'll have to use @PrimaryColumn() `decorator
> 
> `export class UserRoles { @PrimaryColumn({name:"role",nullable:false,unique:false}) role: string;
> 
> @PrimaryColumn({name:"user_id",type:"integer",unique:false}) [@manytoone](https://github.com/manytoone)(() => User, user => user.userRoles,{nullable:true,createForeignKeyConstraints:true}) [@joincolumn](https://github.com/joincolumn)({name:"user_id",referencedColumnName:"id"}) public userId: User; }`

The schema created by typeorm using this works. But, it fails to while saving the entity with nested entity...

**Comment by Exifers** [comment]
The solution given from @tareqdayya works but then this doesn't: 
```typescript
repository.find({
  where: {
    user: { id }
  }
})
```
It gives this error:
```
invalid input syntax for type uuid: "{"id":"acfe8249-9224-4b1a-b1f8-e4739cc59bb9"}"
```
