### ISSUE TITLE
how to create split table with typeorm?

### ISSUE THREAD

**Issue by loseleo** [typeorm/typeorm#4654]
I want to create table by month, like this:

table_data_2019_03
table_data_2019_04
table_data_2019_05

how to do with typeorm?
thanks

**Comment by Lostlover** [comment]
```
(ConnectionMetadataBuilder as any).prototype.buildEntityMetadatas = function (entities) {
  ...
  allEntityClasses.push(...yourEntity) 
}

eval(`function yourEntity() {}`)
Entity(tableName)(yourEntity)
connection.buildMetadatas();
await connc.synchronize();
```

**Comment by imnotjames** [comment]
You can define the table via a function now - that should allow you to change the table dynamically.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
