### ISSUE TITLE
UUID version

### ISSUE THREAD

**Issue by isfernand** [typeorm/typeorm#4656]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

How can I check the uuid version typeorm use? I want to use v4 with mysql but the Generated decorator only recives the strategy "uuid" and the documentation says nothing about the version of the uuid strategy.
https://tools.ietf.org/html/rfc4122#section-4.1.3

**Comment by mureatencio** [comment]
@isfernand  Did you find a solution for that? I'm having the same issue.

**Comment by isfernand** [comment]
@mureatencio no :( I decided to create the uuid field manually and set the value with the library [uuid](https://www.npmjs.com/package/uuid) until I have an answer.

**Comment by silentroach** [comment]
https://github.com/typeorm/typeorm/blob/master/src/util/RandomGenerator.ts#L149

**Comment by AlexMesser** [comment]
TypeORM uses RFC4122 compliant UUID v4 function for drivers which do not have a built-in uuid function
