### ISSUE TITLE
Feature Request : current Server Discovery and Monitoring engine is deprecated. Option to use the new Server Discover and Monitoring

### ISSUE THREAD

**Issue by psdmca** [typeorm/typeorm#4657]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
There is no necessary steps to reproduce warning. Just create any database connection using sample mongodb and it will come back.

(node:9868) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To
use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to MongoClient.connect.

**Comment by pleerock** [comment]
fixed by #4684

**Comment by abequar** [comment]
I created a new database but the message kept coming so I passed the { useUnifiedTopology: true } into the mongoose.connect and its works!

Like this: 
mongoose.connect('mongodb+srv://my:password@cluster0-oa9y0.mongodb.net/Tindev?retryWrites=true&w=majority', {
  useNewUrlParser: true,
  useUnifiedTopology: true
});
