### ISSUE TITLE
Compile Error from mongodb

### ISSUE THREAD

**Issue by beomyongchoi** [typeorm/typeorm#4659]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

error log =>
error TS2321: Excessive stack depth comparing types 'FindConditions<?>' and 'FindConditions<?>'. 
error TS2321: Excessive stack depth comparing types 'MongoRepository<Entity>' and 'Repository<Entity>'. 
node_modules/typeorm/repository/MongoRepository.d.ts(45,5): error TS2321: Excessive stack depth comparing types '(optionsOrConditions?: string | number | Date | ObjectID | FindOneOptions<Entity> | Partial<Entity> | undefined, maybeOptions?: FindOneOptions<Entity> | undefined) => Promise<...>' and '{ (id?: string | number | Date | ObjectID | undefined, options?: FindOneOptions<Entity> | undefined): Promise<Entity | undefined>; (options?: FindOneOptions<Entity> | undefined): Promise<...>; (conditions?: FindConditions<...> | undefined, options?: FindOneOptions<...> | undefined): Promise<...>; }'. 

maybe occurred by this =>
https://www.npmjs.com/package/mongodb/v/3.3.2

**Comment by Ionaru** [comment]
Having the same error, did you find a solution?

**Comment by charlex** [comment]
@Ionaru @beomyongchoi  If you are on a greater version of typescript than 3.5.3, downgrade to 3.5.3. This fixed this problem for me.

Related issues:

#4662

#4427

#4470

Related roadmap:

#31639

**Comment by choibeomyong** [comment]
@Ionaru i also downgrade to 3.5.3, and fixed it :)
