### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [typeorm/typeorm#4660]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, projects could parse out the address and provide donation capabilities to the user.

**Comment by imnotjames** [comment]
For tax purposes and other reasons, this is going through open collective now as well as GitHub sponsors.  Please use those avenues instead.
