### ISSUE TITLE
how to enable compression protocol  when connect mysql

### ISSUE THREAD

**Issue by guanshouan** [typeorm/typeorm#4661]
I want to enable compression protocol because the data transferred may be large.

So how to config the options to achieve my goal?
`createConnection(options: ConnectionOptions)`

thanks

**Comment by silentroach** [comment]
Compression is currently not supported in TypeORM for MySQL.

You can try to pass `compress: true` with `createConnection( { [other options], compress: true } as any)` and be sure to have installed `mysql2` and not `mysql`. Currently TypeORM tries to use `mysql` package and then `mysql2` as a fallback, but compression protocol is currently supported in `mysql2` package only.
