### ISSUE TITLE
Need help , tsc -d catch error, seems typeorm error, i’m not sure.

### ISSUE THREAD

**Issue by cevio** [typeorm/typeorm#4662]
I cannot build with `tsc -d`, it does not work well.

![image](https://user-images.githubusercontent.com/2226260/63927604-9f5fef80-ca80-11e9-87d9-b1164c4405a7.png)

my repo is [here](https://github.com/nelts/typeorm), you can clone it and run `npm run build`.

Then you can see the errors.

tsc version: 3.6.2 
node version: v10.16.0
use vscode.

Who can help me? thanks!

**Comment by cevio** [comment]
I rollback typescript@3.5.3, then it work well. typeorm does not work well with ts@3.6.2 ?

**Comment by zetoke** [comment]
I have the same issue. Not sure how to fix that right now without rolling back.

**Comment by cevio** [comment]
@zetoke use ts@3.5.3

**Comment by zetoke** [comment]
@cevio yeah, I do. I just didn't merge the branch with an updated typescript 😄

**Comment by zetoke** [comment]
Probably related https://github.com/typeorm/typeorm/issues/4662

**Comment by zetoke** [comment]
Probably related discussions at the end of threads
https://github.com/microsoft/TypeScript/issues/29112
https://github.com/typeorm/typeorm/issues/3194

**Comment by zetoke** [comment]
And this one as a confirmed bug in Typescript https://github.com/microsoft/TypeScript/issues/33132
looks very similar

**Comment by zetoke** [comment]
There should be a fix https://github.com/microsoft/TypeScript/pull/33144

**Comment by Kampfmoehre** [comment]
I have temporarily added this in my tsconfig.json to workaround:
```json
{
  "skipLibCheck": true
}
```

**Comment by sam-hunt** [comment]
typescript@3.6.3-insiders.20190909 is out on npm
