### ISSUE TITLE
Insert many should be able to do not wait for response for each inserted entities

### ISSUE THREAD

**Issue by daniel-dia** [typeorm/typeorm#4665]
When inserting many, for a very large number (10k or more) the inserty many is very fast, but TypeORM do a for-loop for each inserted object. wich can be a VERY slow task.

At this line, should be an option to disable this post-insert  check.

https://github.com/typeorm/typeorm/blob/00d46e1ef0096ed5932fae8fcb3f62dabfeacaeb/src/entity-manager/MongoEntityManager.ts#L202

**Comment by imnotjames** [comment]
We have to iterate over these to correctly generate the results so the ORM can do its job.

If you have suggestions for optimization, let us know, but we can't disable this.
