### ISSUE TITLE
asExpression column altered on every sync

### ISSUE THREAD

**Issue by zortoflaven** [typeorm/typeorm#4669]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Local development against a default install of MySQL8 Community Edition.

```
@Entity("metadataversion")
export class metadataversion {

    @Column({
        primary: true,
        nullable: false,
        type: "varchar",
        length: 255,
        name: "MetaDataVersionOID",
        asExpression: "concat('MDV.',upper(replace(`Name`,' ','')))",
        generatedType: "STORED"
    })
    MetaDataVersionOID: string;

    @Column("varchar", {
        nullable: false,
        length: 45,
        name: "Name"
    })
    Name: string;
}
```
I have `synchronize: true` in my config.

When starting the server, typeorm will alter the MetaDataVersionOID column every time:

> [0] query: ALTER TABLE `metadataversion` CHANGE `MetaDataVersionOID` `MetaDataVersionOID` varchar(255) AS (concat('MDV.',upper(replace(`Name`,' ','')))) STORED NOT NULL

To try and see why typeorm was thinking this column was different, I went into `driver/mysql/MysqlDriver.js` and uncommented out line 641:

> console.log("asExpression:", tableColumn.asExpression, columnMetadata.asExpression);

When I run now, typeorm logs the following:

>[0] asExpression: concat(_utf8mb3\\'MDV.\\',upper(replace(\`Name\`,_utf8mb3\\' \\',_utf8mb3\\'\\'))) concat('MDV.',upper(replace(\`Name\`,' ','')))

I tried modifying my expression to include the additional info to make them match like so:
```
    @Column({
        primary: true,
        nullable: false,
        type: "varchar",
        length: 255,
        name: "MetaDataVersionOID",
        asExpression: "concat(_utf8mb3\\'MDV.\\',upper(replace(`Name`,_utf8mb3\\' \\',_utf8mb3\\'\\')))",
        generatedType: "STORED"
    })
    MetaDataVersionOID: string;
```

This works when the table already exists; I no longer see any `ALTER` statement. However, when creating the table when it doesn't exist, it looks like typeorm adds more escapes and I end up with an expression like:

```
"concat(_utf8mb3\\\'MDV.\\\',upper(replace(`Name`,_utf8mb3\\\' \\\',_utf8mb3\\\'\\\')))"
```
Which MySQL fails on.

Not a huge issue as the alters don't result in any data loss and we will have `synchronize: false` set for production, but any ideas here? Thanks!

**Comment by JeremyLoy** [comment]
Just recently added a column which is also exhibiting this issue. My project does not use synchronize, but explicit migrations. 

Same problem.

We ended up fixing it by **removing all spaces** from the `asExpression` string, **in addition to** double escaping it as you said.

**Comment by michael-golden** [comment]
One thing I noticed is that in CASE expression, 'IS NULL' expressions are converted into ISNULL() function calls.

Original:
```
@Column({
        asExpression: [
            '(CASE',
            '   WHEN field1 IS NULL AND field2 IS NULL THEN NULL',
            '   WHEN field1 IS NOT NULL THEN IF ( field2 IS NULL, field1 , NULL)',
            '   WHEN field2 IS NOT NULL THEN IF ( field1 IS NULL, field2 , NULL)',
            '   ELSE FALSE',
            'END) = TRUE'].join(' '),
        generatedType: 'VIRTUAL',
        nullable: false
    })
    public validateFields: string;
```

DDL from Mysql:
```
CASE
    WHEN (isnull(field1) AND isnull(field2))
        THEN NULL
    WHEN (field1 IS NOT NULL)
        THEN if(isnull(field2), field1, NULL)
    WHEN (field2 IS NOT NULL)
        THEN if(isnull(field1), field2, NULL)
    ELSE FALSE END) = TRUE)
```

In order to get around this, I had to copy the DDL from mysql directly into my asExpression.

**Comment by kb05** [comment]
The same thing happens to me around here (```10.5.8-MariaDB-1:10.5.8+maria~focal-log```, ```typeorm@0.2.32```).

I see that the field on database appear like that ```  `field` tinyint(4) GENERATED ALWAYS AS (1) VIRTUAL``` maybe it has something to do with the ```GENERATED ALWAYS```  and is related with how the migration fields are compared with the current database fields.

The point is that the problem that I have is the same, every time I make a migration and run in the next migration the migration file contains the virtual field again.

Perhaps an option to avoid certain blocking cases until new versions are released could be an option to prevent column synchorization like ```@Column({sync:false})```  or ```@Column({migrate:false})```
