### ISSUE TITLE
How to get raw result of Postgres?

### ISSUE THREAD

**Issue by Rwing** [typeorm/typeorm#467]
I found this line in source code:
https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresQueryRunner.ts#L149
But I wanna get the `result` not `result.rows` in postgres,  does not yet supported?

**Comment by pleerock** [comment]
no, this is too specific. Use underlying driver to get results, e.g. `connection.driver.databaseConnection.connection.query`

**Comment by Rwing** [comment]
The connection.driver.databaseConnection is internal, cant access it from outside.
btw, why driver of pg is return `result.row `else return `result` ?
https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlQueryRunner.ts#L156

**Comment by pleerock** [comment]
> The connection.driver.databaseConnection is internal, cant access it from outside.

then make `any` casting.

because only pg has extra data other then "rows", in other drivers result is equal to pg's result.rows

**Comment by pleerock** [comment]
You can do `connection.driver.nativeInterface.connection.query` as well

**Comment by Rwing** [comment]
I think direct return `result` is better, cause same important data in `result`, for example `rowCount` .

**Comment by pleerock** [comment]
rowCount is equal to results.length right?

**Comment by Rwing** [comment]
actually not, in update | insert | delete operation, rowCount = number of rows affected, results = []

**Comment by Rwing** [comment]
in this case , I need get the rowCount to decide whether the query is successful.

**Comment by pleerock** [comment]
If you need row count there is no other way - you should execute your query using underlying driver interface. There is no other way to achieve it.
