### ISSUE TITLE
Save array of jsonb in Postgres

### ISSUE THREAD

**Issue by lukasfrana** [typeorm/typeorm#4674]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,
I have this column

```ts
@Column('jsonb', { array: true })
arrayOfJson: {foo: string}[];
```

and this function

```ts
async test() {
  const baz = await this.bazRepository.create({
    arrayOfJson: [
      {foo: 'bar'}
    ]
  })
  this.bazRepository.save(baz)
}
```

The column is created correctly in the database but when I try to save it I am getting this error
`QueryFailedError: malformed array literal: "[{"foo":"bar"}]"`

It was issued here #204. Am I doing something wrong?

**Comment by secmohammed** [comment]
facing the same exact issue. any idea? @pleerock

**Comment by secmohammed** [comment]
I was able to tackle this having the column with type simple-json

```
    @Column({ type: "simple-json" })
    products: {
        id: string;
        quantity: number;
    };

```

then I tried to insert an array of products ( normally without stringifying or anything else), and it worked smoothly. Actually this was mentioned at the [docs](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#simple-json-column-type).


>  When you'll load data from the database, you will have your object/array/primitive back via JSON.parse

**Comment by elie222** [comment]
But `simple-json` stores as a string rather than as `jsonb`?

**Comment by nclsndr** [comment]
Yes, `simple-json` stores in `text` (in Postgres) — Is there a way to force usage of `jsonb`?

**Comment by Lampent** [comment]
any new on the subject ?

**Comment by suyashgulati** [comment]
@lukasfrana Removing array:true from options works for me perfectly.

    @Column('jsonb')
    tasks: Foo[];

where Foo is another interface with multiple keys.
No problem with saving as well.

**Comment by lukasfrana** [comment]
> @lukasfrana Removing array:true from options works for me perfectly.
> 
>     @Column('jsonb')
>     tasks: Foo[];
> 
> where Foo is another interface with multiple keys.
> No problem with saving as well.

Yeah, that's valid workaround. Thank you. 

But I was trying to achieve storing JSON array as native Postgres array. Column type could be  `jsonb[]`. Now I think it's too much complicated use case and I should stick with your solution. 

Closing issue.
