### ISSUE TITLE
Does TypeORM support JSON data type in MySQL5.7?

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#468]
Does TypeORM support JSON data type in MySQL5.7?

**Comment by pleerock** [comment]
no json support only in postgres. Contributions are welcomed for this feature.

**Comment by johncoffee** [comment]
@Diluka I'm currently using JSON with MySQL5.7 on google app engine. It's easy to make errors when manually writing JSON (eg. through Sequel Pro). One gotcha is that JSON maps to Text, which means your JSON document is limited to 65KB!

**Comment by Diluka** [comment]
@pleerock 
I made some tests. In MySQL5.7, an object is stored as text in both json or text field. But there are some different between json and text. JSON string will be checked before stored json field. Both can be queried with JSON expressions. If the string is not JSON in text field, will raise an error.

I don't know if JSON type has additional optimizations than TEXT in MySQL5.7. If has, obviously we should store json as json.

But...

Lower version of MySQL or MariaDB is not support JSON type. And TypeORM is already using TEXT to store json as json type. 

So, to support part of them is not that easy.

**Comment by johncoffee** [comment]
Same results here (typeorm <= v0.0.11). So, as pleerock said, no json support yet (even with in MySQL 5.7).

**Comment by Diluka** [comment]
@johncoffee Sorry, I'm taking about the next 0.1.0

**Comment by pleerock** [comment]
@Diluka if msql 5.7 supports json we should not use text and should use json type instead. People who need json below msyql 5.7 can simply use "text" type.

**Comment by pleerock** [comment]
custom database types are supported now and json mysql type should be available in `0.1.0-alpha.11`. Please test it and let me know if everything is working as expected.

**Comment by xiaoyang4011** [comment]
@pleerock  After testing, everything is working as expected, in 0.1.0-alpha.11 and mysql 5.7.
