### ISSUE TITLE
[Question] How to link new post with exist categories 

### ISSUE THREAD

**Issue by heshaShawky** [typeorm/typeorm#4685]
**Issue type:**
[x] question

**Database system/driver:**
[x] `mysql` / `mariadb`

**TypeORM version:**
[x] `latest`

I'm building a Rest API using express with typeORM I linked the posts with categories with many to many relationships and setting the cascade to true

 So when creating a post with categories it generates new categories every time even if it exists before! of course with different ids. 

**So what I need is using the existing categories ( create a relation between this categories and the new post id ) and if not existing just create a new one.** 

**My create function:** 
```javascript
private createPost = async (request: express.Request, response: express.Response) => {

    const data: WpPostsModel = request.body;
    const entries: any[] = request.body.taxonomies;
    let taxonomies = [];

    for (let i = 0; i < entries.length; i++) {
        const entry = entries[i];

        let newTaxonomy = new WpTermTaxonomyModel();

        newTaxonomy = {
            taxonomy: entry.taxonomy,
            description: '',
            term: {
                name: entry.term.name,
                slug: entry.term.name.replace(/\s+/g, '-'),
                term_group: 0,
                // term_id: entry.term.term_id
            }
        }

        taxonomies.push(newTaxonomy);
    }


    const newPost = await this.postRepository.create({
        post_title: data.post_title,
        post_content: data.post_content,
        post_excerpt: data.post_excerpt,
        post_type: 'post',
        post_mime_type: '',
        comment_status: 'closed',
        ping_status: 'closed',
        to_ping: '',
        pinged: '',
        comment_count: 0,
        post_parent: 0,
        post_status: 'publish',
        post_content_filtered: '',
        post_password: '',
        post_name: ( data.post_title ) ? data.post_title.replace(/\s+/g, '-') : '',
        post_date: new Date(),
        post_date_gmt: new Date(),
        post_modified: new Date(),
        post_modified_gmt: new Date(),
        taxonomies
    });

    await this.postRepository.save(newPost);

    response.send(newPost);

}

```

**Comment by Kononnable** [comment]
Please post your entity definitions - without them there is no way to know exactly how entities were defined. Also I don't see anything named as categories in your createPost function.

**Comment by imnotjames** [comment]
With the limited info we've got access to we aren't able to help too much here.  As such, I'll be closing this out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
