### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ygorlazaro** [typeorm/typeorm#4686]
[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I am having a lot of problems with `TypeORM` in production, some of them was resolved in @next or planning to be resolved *soon*.

My question: when is **soon**? I do not see any progress on this project, last release was months ago and the @next version is so alpha, breaking and undocumented I cannot use anywhere without to be certain of some kind of support.

Nested where, soft deletes, alias naming conflicting on a large join, the 'ORM' part is a lot weaker when you need to query, so I need to do lots of queries with QueryBuilder.

I have a bunch of another problems to list that seems to be at least a bit better in other versions or plans of this ORM.

It's sad for me, using in production with this problems, and still TypeORM does work fine with NestJS.

**Comment by ygorlazaro** [comment]
I'm sorry, but... someone?

**Comment by pleerock** [comment]
TypeORM is open source project and isn't baked by any company. It means it can be maintained only by people who have a free time and can spend their time doing work for _free_. This is what you get when you are using a free tool, its quite common experience in open source. 

> Nested where

if you have complex queries consider using query builder.

> soft deletes

in current typeorm philosophy this feature must be a domain/project-specific feature.

> alias naming conflicting on a large join

just use different aliases, it shouldn't be a problem

> the 'ORM' part is a lot weaker when you need to query, so I need to do lots of queries with QueryBuilder.

QueryBuilder is what originally designed for complex queries. 

I don't know what other problems you have in production, personally I run few big projects on TypeORM and don't have any problems with it. But if you really do have some blockers, consider forking and apply fixes if you need them faster than soon.

**Comment by ygorlazaro** [comment]
I'm sorry.

I understood your points, but you didn't answer me. Some of this points where fixed or evolved by another TypeORM branches.

Let me ask you more clearly: does this project have a roadmap? Because this issues (and others that other people must be having now) are fixed somewhere.

Nested where for instance isn't an advanced query:

```
const data = await conn.findOne(User, { where: {
    user:{
        person: {
            id: 4
        }
    }
}
});
```

I've found yesterday another bug, for instance:


```
const data = await conn.findOne(User.name, { where: {
    user:{
        slug: "this-entity-doesnt-has-one"
    }
}
});
```

This query above returns results, besites `slug` isn't a column at the entity.

Soft deletes are also in some roadmap, witch I don't know. At GitHub there's a issue asking about 0.4.0 version, the doc tells about an 1.0.0, and the @next I clearly have no idea witch version it will become.

About the conflicting alias name, this is happening in a query with some relations, and custom column names using `@JoinColumn`. It is an issue marked  far early this year or last year. This issue is an example: https://github.com/typeorm/typeorm/issues/3721

I understand this is an open source project, free time, no payments, I know all of this. I do by myself some work in opensource projects, and I really don't need to be taught how this world works. I am asking with a pure question and doubt, and I would love a concrete answer.

If all the answers returns to me as "using QueryBuilder" and will be fixed, this breaks a lot what a ORM can do. Building query isn't code performative, there is almost no difference from using `mysql` provider directly.

I appreciate all work involved here, but since it's an OpenSource project, I have rights to ask and know more about it. "Make a fork an fix for you" is a good answer as "create another project and evolve alone". It breaks a little more the OpenSource power, that could be concentrate to solve the same problem better for more people <3

**Comment by pleerock** [comment]
`@next` will become 0.4.0, yes we have a roadmap - first release 0.4.0, then 0.5.0 etc then 1.0.0 etc. And there are many features and bug fixes needs to be done. As you can see right now there are 900+ issues opened and first step in this roadmap is to fix as much as possible bugs from opened issues then try to release 0.4.0. But how fast we are going to reach our goals depend on a free time, right now I have no opportunities to spend full time development on this project, and I hope I will have it in the future.

**Comment by vimmerru** [comment]
@pleerock thanks for explanation. Unfortunately such level of support doesn't allow to use typeorm in production and i will look to alternative solution. mikro-orm looks not bad.

**Comment by pleerock** [comment]
its completely up to you guys, make sure you objectively measured all pros and cons of each decision :)

**Comment by antondc** [comment]
We were migrating a project from Sequelize to TypeORM. It is a very well developed project, with a nice website and documentation. 

But almost a thousand open issues on Github, and no clear roadmaps with planned release dates is a no go for us. We have to review our decision and opt for a library with a stable API and active support in the long term. Both Sequelize and TypeORM lack of this long term approach.

**Comment by OJezu** [comment]
I'm sorry, maintained only by people who are doing it for free? You have sponsors, and the biggest expense is your salary. I understand this is not comparable with a full time job, but still, it's not working for free. And there are 992 open issues.

https://opencollective.com/typeorm

Good thing I'm not a sponsor, or I would be so pissed.
