### ISSUE TITLE
Why `repository.findOne(null)` returns 1st record of the table?

### ISSUE THREAD

**Issue by anthonylau** [typeorm/typeorm#4687]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.15` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
const user = await userRepository.findOne(null); 
// user.id is 1
```

I expect it would returns `undefined`. Is it intended?

**Comment by DimaIT** [comment]
As we have in documentation: `findOne - Finds first entity that matches some id or find options.`. If no find options given then every record matches.

It may be confusing, especially when you are expecting `findOne` to search by id only. In such case it may be better to search by id explicitly: `userRepository.findOne({ id: value })`. Then you 'll get `undefined` for `null` value.
