### ISSUE TITLE
Async problems when saving one-to-many 

### ISSUE THREAD

**Issue by arejaycola** [typeorm/typeorm#4689]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a many-to-many relationship that I am representing with two one-to-many relationships (User, Skill) and a joining/mapping table (UserSkill).

In my UserSkill model, I have a function that is supposed to get a user and skill and save it as a UserSkill. I don't think details of the models are important for the problems I am experiencing.

 ```javascript
    let user = await User.getUserById(1);
    let skill = await Skill.getSkillById(1);
    let userSkill = new UserSkill();
    userSkill.skill = skill;
    userSkill.user = user;

   await userSkill.save();
```
In my User.ts file I have:

```javascript

static async getUserById(id) {
	let user = await getRepository('User')
		.createQueryBuilder('user')
		.leftJoinAndSelect('user.userSkills', 'userSkills')
		.leftJoinAndSelect('userSkills.skill', 'skill')
		.leftJoinAndSelect('user.roles', 'role')
		.leftJoinAndSelect('role.permissions', 'permissions')
		.where('user.id = :id', { id: id })
		.getOne();

		return new User(user);
	}
```

In Skill.ts I have: 
```javascript
    static async getSkillById(skillId) {
		let skill = await getRepository('Skill')
			.createQueryBuilder('skill')
			.leftJoinAndSelect('skill.system', 'system')
			.leftJoinAndSelect('skill.userSkills', 'userSkills')
			.where('skill.id = :id', { id: skillId })
			.getOne();

		return new Skill(skill);
    }
```

When I run the above code, it sometimes populates the database correctly. Sometimes it won't populate the userId. As a test, a ran the above code with the save function being called inside a timeout with 100ms delay. 

```javascript
  setTimeout(() =>{
      await userSkill.save();
},100)
```

This gives me success 100% percent of the time. It seems to be an asynchronous problem yet I think I am 'awaiting' everywhere this may be a problem. Am I doing something wrong?

Thanks!

**Comment by arejaycola** [comment]
I may have figured out my problem.

**Comment by fatima-afzal** [comment]
@arejaycola I seem to be facing something similar. What was your problem?

**Comment by arejaycola** [comment]
@fatima-afzal Hmm. I don't remember exactly. I think i would call userSkill.save() and then in its parent function was also calling user.save(). I believe this was overwriting the userSkill that I had just saved.

Does that make sense?
