### ISSUE TITLE
Strange typing of EntityManager::save that returns Promise<T extends DeepPartial<Entity>>

### ISSUE THREAD

**Issue by vimmerru** [typeorm/typeorm#4690]
**Issue type:**

[ x] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x ] `cordova`
[x ] `mongodb`
[ x] `mssql`
[x ] `mysql` / `mariadb`
[ x] `oracle`
[x ] `postgres`
[x ] `cockroachdb`
[x ] `sqlite`
[ x] `sqljs`
[x ] `react-native`
[ x] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

Here is definition of EntityManager::save method

```
save<Entity, T extends DeepPartial<Entity>>(targetOrEntity: ObjectType<Entity> | EntitySchema<Entity>, entity: T, options?: SaveOptions): Promise<T>;
```
Could you explain why it returns ```Promise<T>``` instead of ```Promise<Entity>```? It seems completely use less. The obvious usage:

1. You save partial because some columns are auto-generated
2. You want complete entities to be returned to be able to return id from rest endpoint, but the type is just DeepPartial your provided

It makes EntityManager interface incompatible with strict nulls environment. Also it contradicts with Repository::save that returns ```Promise<Entity>```.

**Comment by imnotjames** [comment]
`EntityManager.save` works a little differently so the return type is different from `Repository`.  If you think it shouldn't be this please update the typing & confirm it in a PR.  Cheers!

---

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
