### ISSUE TITLE
Error: Option "database" is not set in your connection options when use "url" option for connection

### ISSUE THREAD

**Issue by CavidM** [typeorm/typeorm#4691]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

### **`Error: Option "database" is not set in your connection options, please define "database" option in your connection options or ormconfig.json`**
 But i define "database" option in "url" option by this way: `"url": "mysql://root:@localhost/myDb"`

**Comment by pleerock** [comment]
closed by #4694
