### ISSUE TITLE
PessimisticLockTransactionRequiredError: An open transaction is required for pessimistic lock.

### ISSUE THREAD

**Issue by TranBaVinhSon** [typeorm/typeorm#4692]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I want to use `SELECT ... FOR UPDATE` so I add `.setLock("pessimistic_write")` to my query, like this
```ts
  async find(connection: Connection): Promise<User> {
    const user: User = await connection
      .getRepository(User)
      .createQueryBuilder("user")
      .setLock("pessimistic_write")
      .where("ms_token.id = :id", { id: 1 })
      .getOne();
    return token;
  }
```
and call `find` function:
```ts
const user: User = await userService.find(connection);
```
But I got this error

> UnhandledPromiseRejectionWarning: PessimisticLockTransactionRequiredError: An open transaction is required for pessimistic lock.

When I remove `.setLock("pessimistic_write")`, there was no error anymore, Do I miss something?
Any advice is welcome!

**Comment by Kriskit** [comment]
Have you tried adding `.useTransaction(true)`?

**Comment by TranBaVinhSon** [comment]
Thanks man, it works now, But I noticed that my query is using `LOCK IN SHARE MODE` not `SELECT ... FOR UPDATE`. Is there any difference between two of queries?
