### ISSUE TITLE
How to run Migration in the Browser ?

### ISSUE THREAD

**Issue by anthonyjlmorel** [typeorm/typeorm#4695]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[] `sqlite`
[X] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, the migration documentation explains how to run migration for a Client/Server application.
What if I was building the app using sqljs and wanted to migrate the DB structure ? Meaning all the app is running client-side, in-browser. How can I use the CLI ?

Thanks

**Comment by DimaIT** [comment]
Not sure if it's possible to use CLI in browser. But probably you should be still able to run migrations with [connection-api](https://github.com/typeorm/typeorm/blob/master/docs/connection-api.md), just use `connection.runMigrations()`.

**Comment by anthonyjlmorel** [comment]
@DimaIT Didn't see this, that might do the trick, will test this ! Thanks
