### ISSUE TITLE
manager.findOne not work as needed.

### ISSUE THREAD

**Issue by jason-chang** [typeorm/typeorm#4713]
**Issue type:**

[ ] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[*] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

My entry is like this
```typescript
@Entity({ name: 'config' })
export class ConfigModel {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ type: 'varchar', length: 250 })
  resourceDir!: string;
}
```

I query database like this.
```typescript
  const config = await getConnection(CONNECTION_NAME_CONFIG).manager
    .findOne(ConfigModel, 1);
```

But get sql like this.
```sql
SELECT "ConfigModel"."id" AS "ConfigModel_id", "ConfigModel"."resourceDir" AS "Conf
igModel_resourceDir" FROM "config" "ConfigModel" WHERE "ConfigModel"."id" IN (?)
```

EntryOptions.name does not work, when us `.manager.findOne`.

**Comment by Kononnable** [comment]
Closing as no response from the author.
