### ISSUE TITLE
Custom Function (extends SelectQueryBuilder)

### ISSUE THREAD

**Issue by ahmadarif** [typeorm/typeorm#4716]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Questions:**
1. How to add custom functions such as findCustom(params) in Repository object, without using CustomRepository.
```ts
const params = {
  employeeIds: [1, 2, 3, 4],
};
const employeeLists = await getRepository(Employeee).findCustom(params);
```

2. How to add custom functions such as getManyCustom(params) in the SelectQueryBuilder  object
```ts
const params = {
  employeeIds: [1, 2, 3, 4],
};
const employeeLists = await Employeee.createQueryBuilder('employee').getManyCustom(params);
```

**Comment by ahmadarif** [comment]
Now, I'm using monkey patch to implement custom function.

```ts
import { SelectQueryBuilder } from 'typeorm/query-builder/SelectQueryBuilder';
import { Auth } from './helpers/auth.helper';

// TypeORM patch :===============================================================================
declare module 'typeorm/query-builder/SelectQueryBuilder' {
  interface SelectQueryBuilder<Entity> {
    getOneAuth(auth: Auth): Promise<Entity>;
    getManyAuth(auth: Auth): Promise<Entity[]>;
  }
}

SelectQueryBuilder.prototype.getOneAuth = function(auth: Auth) {
  console.log(this);
  console.log('getOneAuth called');
  return this.getOne();
};

SelectQueryBuilder.prototype.getManyAuth = function(auth: Auth) {
  console.log(this);
  console.log('getManyAuth called');
  return this.getMany();
};
```

**Comment by imnotjames** [comment]
You cannot extend the query builder directly.  If you'd like to monkey-patch it, we can't stop ya, but it's definitely not supported.

A utility method could give you similar results that you pass a query builder into.

**Comment by ahmadarif** [comment]
Thanks for the response, the complete result is I've added some where clause on query builder before return the results.
Btw, using monkey patch can solve my need 👍
