### ISSUE TITLE
ReactNative entities are not loaded

### ISSUE THREAD

**Issue by mustafawm** [typeorm/typeorm#4717]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

```
//db/index.ts

import 'reflect-metadata';
import {
  Column,
  createConnection,
  Entity,
  PrimaryGeneratedColumn,
} from 'typeorm/browser';

@Entity()
export class Product {
  @PrimaryGeneratedColumn()
  public id: number;

  @Column('string')
  public name: string;

  @Column('number')
  public amount: number;

  @Column('string')
  public createdAt: string;

  @Column('boolean')
  public synced: boolean;
}

createConnection({
  type: 'react-native',
  database: 'test',
  location: 'default',
  logging: ['error', 'query', 'schema'],
  synchronize: true,
  entities: [
    Product
  ]
})
  .then(conn => {
    console.log('✅ init db', conn);
    console.log('connnnn', conn);
    const x = new Product();
    x.amount = 90;
    x.name = 'ddddddd';
    x.createdAt = 'lkjlkj';
    x.synced = false;
    conn.manager.save(x);
  })
  .catch(err => console.error(err));

// then in App.tsx 
import './db/index.ts';
```
<img width="641" alt="Screen Shot 2019-09-10 at 3 35 07 pm" src="https://user-images.githubusercontent.com/13101565/64597916-f3ec5e80-d3e0-11e9-9be8-48120ca84bc1.png">

![Screen Shot 2019-09-10 at 3 36 44 pm](https://user-images.githubusercontent.com/13101565/64597937-fb136c80-d3e0-11e9-97a8-c8b2e5dfb2f0.png)

**Comment by sajidit** [comment]
Try to import from typeorm not from typeorm/browser

**Comment by mustafawm** [comment]
Tried that already.

Best regards,
Mustafa

On 11 Sep 2019, at 2:51 pm, sajidit <notifications@github.com<mailto:notifications@github.com>> wrote:


Try to import from typeorm not from typeorm/browser

**Comment by sajidit** [comment]
There might be issue of importing Products by relative path

**Comment by mustafawm** [comment]
Solved.
If you're facing a similar issue, try changing babel decorators config from `decoratorsBeforeExport: true` to `legacy: true`

**Comment by Vluf** [comment]
Welp, I looked for that solution for ages, thanks @mustafawm
