### ISSUE TITLE
TypeORM tries to drop views that are needed by the pg_stat_statements extension

### ISSUE THREAD

**Issue by lucaslenz** [typeorm/typeorm#4718]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Enable extension pg_stat_statments
2. Start your application with the synchronize option set to true

The error that is caused:

`QueryFailedError: cannot drop view pg_stat_statements because extension pg_stat_statements requires it`

Why is TypeORM trying to drop a view that is needed by the extension? Is TypeORM not compatible with pg_stat_statements?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
I don't know this extension, but it looks like it creates it's own tables/views in your schema. Typeorm while synchronizing deletes every database object which isn't described using typeorm decorators(or entity schemas). It can't distinguish if such object is no longer necessary or is it something completely not related to your app code.

If you want to use typeorm with tables/views not related to your app code you probably need to make dummy view/table in typeorm and disable synchronization for it - just empty class decorated with Column/ViewEntity with `synchronize:false` and proper name.

**Comment by LucasLenz49** [comment]
Thanks for your advice.
I solved the problem by only using Migrations instead of the synchronization feature as you suggested.

Can be closed.

**Comment by zveljkovic** [comment]
I would like this to be reopened as we have a need to reset the database and would like to use `schema:drop` but it fails with

`
query: 'DROP VIEW IF EXISTS "public"."pg_stat_statements" CASCADE;',
  parameters: undefined,
  driverError: error: must be owner of view pg_stat_statements
`

It would be nice to exclude some views/tables from dropping by config.

**Comment by Ginden** [comment]
@zveljkovic You can describe these views and mark them with `synchronize: false`.

**Comment by joachimbulow** [comment]
@Ginden Thats a hefty workaround. The views are internal to extensions, you would not want to describe these
