### ISSUE TITLE
Drop table in migration

### ISSUE THREAD

**Issue by pldin601** [typeorm/typeorm#472]
I creating migration. On "up" it creates table and I want to drop it on "down". But I did not find appropriate method on queryRunner. Is it any way to do this without raw query?

**Comment by pleerock** [comment]
There is a [down method](https://typeorm.github.io/migrations.html) support in migrations.

**Comment by pldin601** [comment]
I know about "down", but I don't know what to write there to drop the table?

**Comment by pleerock** [comment]
ah, okay. Then you have to write raw sql queries. Migrations at the moment don't have well developed api, its something expected in the future versions.

**Comment by pldin601** [comment]
Created PR with this feature
https://github.com/typeorm/typeorm/pull/473

**Comment by ishanbakshi** [comment]
just writing if it helps anyone. 
Unlike other queries drop table works without quotes around the table name.
So if i had to drop a table "user"
I'll do 
```public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("DROP TABLE user2");
    }```

**Comment by allancssio1** [comment]
what is command to down a user table? pls
