### ISSUE TITLE
DriverPackageNotInstalledError: SQL Server package has not been found installed

### ISSUE THREAD

**Issue by ghost** [typeorm/typeorm#4721]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I'm trying to use TypeORM in a Sharepoint 2016 Web part to connect to SQL Server and perform a simple query.  I've tried reading the documentation about usage in the Browser and from what I understand I can only use sql.js, is that correct?

Because this is part of a Sharepoint Web Part that has many levels of code I can't really provide a sample for you to use that's standalone. 

The issue i'm running into is:
DriverPackageNotInstalledError: SQL Server package has not been found installed. Try to install it: npm install mssql --save

I have installed the mssql package several times but continue to receive the same message.
I'm assuming this is because there is no support for mssql in the browser?

Any info you could give would be greatly appreciated.
I'm very new to typescript and all this stuff.

Thank you for your time.

**Comment by silentroach** [comment]
yep, you can't use mssql via browser package

**Comment by imnotjames** [comment]
mssql is a binary package.  As such, like said above - it can't be installed as part of the browser.  Also as of the latest version we prevent this from occurring at all by replacing the driver with a no-op.

**Comment by emazzu** [comment]
alguien puso solucionar esto ??
