### ISSUE TITLE
[BUG] `synchronize` in Expo production mode combines all entities together

### ISSUE THREAD

**Issue by lookitsatravis** [typeorm/typeorm#4723]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[X] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Using SQLite via Expo.

I've got an Entity `Job` which looks something like this:

```ts
@Entity()
export class Job {
  @PrimaryColumn('text')
  shiftId: string;

  @Column('int', { nullable: true })
  callBack: number;
}
```

and another called Config:

```ts
@Entity()
export class Config {
  @PrimaryColumn('text')
  id: string;

  @Column('int', { nullable: true })
  status: number;
}
```

And I'm creating a DB connection like this:

```ts
const awaitDbConnection = createConnection({
  database: 'mydb',
  synchronize: true,
  type: 'expo',
  entities: [Job, Config],
  // logging: true,
});
```

During development, everything is totally fine. `synchronize` works as expected, and things are okay. The schema produced looks like this:

```sql
CREATE TABLE "job" ("shiftId" text PRIMARY KEY NOT NULL, "callBack" integer)
```

When I publish the app via `expo publish` or run the app locally with production mode on, I get some unexpected behavior. Typeorm introduces new columns including a new `id` PK non-nullable column which causes everything to break. The schema produced looks like this:

```sql
CREATE TABLE "t" ("status" integer, "id" varchar NOT NULL, "shiftId" text NOT NULL, "callBack" integer, CONSTRAINT "FK_20cfd8d22ef5493a7fcc0baa534" FOREIGN KEY ("jobShiftId") REFERENCES "t" ("shiftId") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("id", "shiftId"))
```

As you can see, a lot is going on in the minified Expo code which is not happening in development, but the biggest hang up here is the introduction of a second primary key which is not present on my entity class.

# Cause/Work-around

After minification/uglify takes place, for whatever reason, typeorm sees all of the entities as type `t`. In development, typeorm checks to see if tables exist for `job`, `config`, `picture`, etc., but when run in the prod code, it checks to see if tables exist for `t`, `t`, `t`, etc. And what winds up happening is the synchronize process tries to combine all of the table definitions together into a single table (which explains the extra constraints in the OP). Not sure why that is happening, and I assume it is a bug of some kind with the inference of table names.

The solution is to explicitly declare the table name when defining an Entity. So...

```ts
@Entity({ name: 'jobs' })
export class Job {
  @PrimaryColumn('text')
  shiftId: string;

  @Column('int', { nullable: true })
  callBack: number;
}
```

After making that change for all of my entities, the problem was solved in the production build. I'll leave this open in case there is anything to follow up on.

**Comment by lookitsatravis** [comment]
Update...

I figured out what was happening and a workaround. After minification/uglify takes place, for whatever reason, typeorm sees all of the entities as type `t` (I have more entities which I didn't list above). In development, typeorm checks to see if tables exist for `job`, `config`, `picture`, etc., but when run in the prod code, it checks to see if tables exist for `t`, `t`, `t`, etc. And what winds up happening is the `synchronize` process tries to combine all of the table definitions together into a single table (which explains the extra constraints in the OP). Not sure why that is happening, and I assume it is a bug of some kind with the inference of table names.

The solution is to explicitly declare the table name when defining an Entity. So...

```ts
@Entity({ name: 'jobs' })
export class Job {
  @PrimaryColumn('text')
  shiftId: string;

  @Column('int', { nullable: true })
  callBack: number;
}
```

After making that change for all of my entities, the problem was solved in the production build. I'll leave this open in case there is anything to follow up on.

**Comment by paldepind** [comment]
This is probably due to the minification/uglify step throwing away those names that TypeORM uses. This can probably not be changed except for added documentation.

**Comment by paldepind** [comment]
Here is a relevant issue: https://github.com/facebook/metro/issues/154

Some of the comments mention TypeORM and how to set up the bundler such that class names are preserved.

**Comment by lookitsatravis** [comment]
Hey, thanks @paldepind. I did indeed permanently solve this issue by changing the minify configuration, and I agree that this is not a fault in typeorm. I can close this. Or I suppose we could keep it open if a documentation update is warranted.

**Comment by macfanatic** [comment]
This forum link solved the issue for me thankfully!

https://forums.expo.io/t/change-minifierconfig-for-minify-uglify/36460/2
