### ISSUE TITLE
How to run SELECT... FOR UPDATE inside queryRunner ?

### ISSUE THREAD

**Issue by TranBaVinhSon** [typeorm/typeorm#4725]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
How can I run `SELECT... FOR UPDATE` inside `queryRunner`  ?
I see the TypeORM doc that queryRunner can only access `manager`, how I can access `Repository` to lock record. For example `queryRunner.getRepository(User).setLock("pessimistic_write").....`

```ts
      console.log("----------------- START TRANSACTION -----------------");

      const queryRunner = connection.createQueryRunner();
      // establish real database connection using our new query runner
      await queryRunner.connect();

      await queryRunner.startTransaction();

      try {
        // `SELECT....FOR UPDATE`
        // Want to .setLock("pessimistic_write")
        

        // commit transaction now:
        await queryRunner.commitTransaction();
      } catch (err) {
        // since we have errors lets rollback changes we made
        await queryRunner.rollbackTransaction();
      } finally {
        // you need to release query runner which is manually created:
        await queryRunner.release();
      }

      console.log("----------------- FINISH TRANSACTION -----------------");
```
Any advice is welcome!

**Comment by TranBaVinhSon** [comment]
Yupp, actually we can access `Repository` from `manager`, problem solved 👍 
```
        users = await queryRunner.manager
          .getRepository(User)
          .createQueryBuilder("user")
          .useTransaction(true)
          .setLock("pessimistic_write")
          .where("user.status = :status", { status: status })
          .getMany();
```

**Comment by dannyozh** [comment]
Hi all, thanks for this thread, it has been useful. Is there a way to detect if a pessimistic write has been implemented? I have two nodes running my backend cron service and they call the cron at the same time, so i'm thinking if the slower one can detect the pessimistic write, then it will be stopped or something.

**Comment by ufukomer** [comment]
@TranBaVinhSon what I don't understand is to "release". How would I release that lock? Because in the next lines i need to read data from that "users" and it should be locked until I commit the transaction.

**Comment by dmytrovskyi** [comment]
When using **TypeORM's `transaction` method**, you do not need to explicitly call `COMMIT` or `ROLLBACK`. TypeORM manages the transaction lifecycle for you. Here's how it works:

1. **Commit**:
   - If the callback function (the code inside the `transaction` block) executes successfully without throwing an error, TypeORM automatically commits the transaction.

2. **Rollback**:
   - If an error is thrown inside the callback function, TypeORM automatically rolls back the transaction.

### Example Breakdown

In the provided example:

```typescript
await connection.transaction(async (manager) => {
  // Your transactional logic here
  const employee = await manager
    .getRepository(Employee)
    .createQueryBuilder("employee")
    .setLock("pessimistic_write")
    .where("employee.id = :id", { id: employeeId })
    .getOne();

  if (!employee) {
    throw new Error("Employee not found");
  }

  employee.salary += increment;

  await manager.save(employee);
});
```

- **Success**: If no errors occur in the block, the transaction will automatically commit.
- **Failure**: If an error is thrown (e.g., `throw new Error("Employee not found")`), the transaction will automatically roll back.

### Manual Transaction Management

If you prefer more control, you can manage the transaction explicitly. Here's how:

```typescript
const connection = getConnection();
const queryRunner = connection.createQueryRunner();

await queryRunner.startTransaction();

try {
  // Lock the row
  const employee = await queryRunner.manager
    .getRepository(Employee)
    .createQueryBuilder("employee")
    .setLock("pessimistic_write")
    .where("employee.id = :id", { id: employeeId })
    .getOne();

  if (!employee) {
    throw new Error("Employee not found");
  }

  // Update the salary
  employee.salary += increment;

  // Save the changes
  await queryRunner.manager.save(employee);

  // Commit the transaction
  await queryRunner.commitTransaction();
} catch (error) {
  // Rollback the transaction in case of an error
  await queryRunner.rollbackTransaction();
  console.error("Transaction failed:", error);
} finally {
  // Release the query runner
  await queryRunner.release();
}
```

### Key Differences:
1. **TypeORM Transaction Helper (`connection.transaction`)**:
   - Simplifies the process.
   - Automatically handles `COMMIT` and `ROLLBACK`.
   - Recommended for most use cases.

2. **Explicit Transaction Management (`queryRunner`)**:
   - Gives more control over the transaction flow.
   - Useful for advanced scenarios where you need custom transaction handling.

For most use cases, the helper method is sufficient. Use explicit management only if you need additional flexibility.
