### ISSUE TITLE
Understanding dropSchema, synchronize and migrationRun

### ISSUE THREAD

**Issue by dcs3spp** [typeorm/typeorm#4731]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

I am a new user trying to understand some key concepts. 

After reading the [docs](https://typeorm.io/#/connection-options/common-connection-options) I am not sure that I understand the difference between dropSchema and synchronize? Does *dropSchema* connection option delete all tables for entities marked with the *@Entity* decorator every time a new connection is made **while** the application is running? The difference between this and *synchronize* is that with synchronize this only happens once, i.e. each time the application is started???????

Does *dropSchema* and *synchronize* connection options conflict with option *migrationsRun*? Are they mutually exclusive, since if an entity schema (table) is created and a migration is run that creates that same table then a conflict has occurred?????

Kind Regards

dcs3spp

**Comment by elderapo** [comment]
`dropSchema` drops all tables within the specified database (along with the records).

`synchronize` called without arguments tries to "auto synchronize" current DB schema to match typeorm entities. If called with `true` as first argument it drops DB and then recreates DB structure from typeorm entities.

I would say this "auto synchronization" is only viable for development. In production, you should just use migrations to update your DB.

**Comment by dcs3spp** [comment]
Many thanks @elderapo, appreciated...so synchronize(true) is sort of similar to dropSchema.

Is the configuration below invalid/illegal since the options perform similar operation?
{
synchronize(true),
dropSchema,
...
}

Ok, so {synchronize(true), migrationsRun} are mutually exclusive especially in production due to conflicts with entities created by migration scripts and auto synchronization scripts ....

**Comment by iyobo** [comment]
I have synchronize set to true, but I don't think it drops my DB in dev.
I get errors like `null value in column "oldColumn" violates not-null constraint` when oldColumn has been deleted in the model.

**Comment by chriszrc** [comment]
@iyobo I'm running into the same problem with not null constraints failing when synchronize is set to true. Did you ever find a way around this? How is everyone not having this problem...

**Comment by iyobo** [comment]
@chriszrc ensure you are running build after every change to your model files.

This could happen if typeorm is searching for model definitions in your build folder.

**Comment by iyobo** [comment]
Better yet, stop using the model directory method for instantiating typeorm. 

Instantiate your models by feeding in the actual model classes themselves.... Instead of a directory where they exist.

**Comment by mpkasp** [comment]
I've had the same issue @iyobo and @chriszrc have been having in my sqlite instance on a cordova mobile app, but not using websql for cordova development in browser. Seems like disabling synchronization prevents the app from trying to update tables that exist which makes this go away. 

After poking around I found and resolved this issue by explicitly naming my entity tables with lowercase characters as suggested by https://github.com/typeorm/typeorm/issues/4420 (via https://github.com/typeorm/typeorm/issues/2782)

**Comment by rex2002xp** [comment]
// Spanish
Este inconveniente se presenta cuando la "entity" se declara el esquema al que pertenece, por ejemplo: 

@Entity({
    schema: 'public',
    name: 'users'
})

Mientras no declares el esquema, no presenta error de sincronización.

// English
This issue is showed when the entity are set name schema, example:
@Entity({
    schema: 'public',
    name: 'users'
})

But no set the property "schema" the synchronization working nice.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
