### ISSUE TITLE
"Cannot read property 'metadata' of undefined" when using `orWhereInIds` in a Brackets where expression

### ISSUE THREAD

**Issue by QuantumKing** [typeorm/typeorm#4732]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

```ts
const qb = this.repository.createQueryBuilder('member');

qb.where(new Brackets((sq) => {
    sq.orWhereInIds(query.includeMemberIds);
}));
```

The above query fails with the error "Cannot read property 'metadata' of undefined". The following works fine:

```ts
const qb = this.repository.createQueryBuilder('member');

qb.where(new Brackets((sq) => {
    sq.orWhere('member.id IN (:...includeMemberIds)', { includeMemberIds: query.includeMemberIds });
}));
```

**Comment by fan-tom** [comment]
The same issue with `where` instead of `orWhereInIds`, when I pass object. Looking at source code, I can conclude that until fixed it will only work for strings and functions

**Comment by fan-tom** [comment]
Also, if I workaround this by manually initializing `mainAlias` (using `from`), I get error that, when using object as conditions, values are written to `nativeParameters`, but later extracted from qb using `getParameters()`, which doesn't return them, so you get query with parameters placeholders (`$<number>` in case of postgres), but without values passed to db for them

**Comment by lucafaggianelli** [comment]
I faced the same issue, the workaround work though! thanks

**Comment by imnotjames** [comment]
I believe this fails because there's overlap in the parameters & how they get pulled in with brackets.

this is made worse because the `orWhereInIds` just does its own thing separate from everything else.

Ideally:

- Allow for nested parameter sets that don't get overwritten
- Update whereInIds to just use standard queries / `.where` code instead of special logic & crafting its own special SQL
