### ISSUE TITLE
QueryRunner Data

### ISSUE THREAD

**Issue by krazibit** [typeorm/typeorm#4736]
**Issue type:**

[ x] question
[ ] bug report
[ x] feature request
[ ] documentation issue

**Database system/driver:**

[ x] `cordova`
[ x] `mongodb`
[ x] `mssql`
[ x] `mysql` / `mariadb`
[ x] `oracle`
[ x] `postgres`
[ x] `cockroachdb`
[ x] `sqlite`
[ x] `sqljs`
[ x] `react-native`
[ x] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Currently I bind a queryRunner instance with my request object to use a single transaction throughout the request lifecycle and i'll like to pass some global data in the `queryRunner.data` field.
This would work fine but my worry is that it can be overridden if someone else passes `data` in the save options of a repository using the same queryRunner because of here 
https://github.com/typeorm/typeorm/blob/0aa79173e667e193cee653492176a43eb06abcd5/src/persistence/EntityPersistExecutor.ts#L58
Ideal fix is to merge the `queryRunner.data` and the `option.data` there, so my question is if this is okay or there is a side effect i'm not currently seeing.
Thanks.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
