### ISSUE TITLE
object converted automatically with toString()

### ISSUE THREAD

**Issue by hariDasu** [typeorm/typeorm#4740]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[X] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have item data with LatLng coordinate pairs stored in a column, and it comes back from my API  in JSON format: `item: {id: 3, latlngs: {lat: 123, lng: 456}`

I have tried to use the `@BeforeInsert()` method to convert the column data with `JSON.stringify(latlngs)` but this isn't being processed accordingly, and i keep getting the yellowbox.js error in the console with the message: 

`addStatement - parameter of type <object> converted to string using toString()`

I had this working before by manually extracting the item data via a `flatMap()`and transforming each individual item's latlng via JS via `JSON.stringify()` but I am unsure how to inject this behavior when I am doing cascading inserts for these entities.

any guidance/help would be greatly appreciated! this ORM is fantastic and I am enjoying and greatly benefiting from using it thus far, thank you to all the maintainers and developers on this project! 
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by silentroach** [comment]
seems like you need to [use transformers](https://github.com/typeorm/typeorm/blob/2c34e53bdf5bedd7e73a28066f6ad3089e9d15bb/test/github-issues/3395/entity/Post.ts#L12)

**Comment by hariDasu** [comment]
@silentroach thank you for pointing this out to me i must have missed this feature in typeorm docs

i tried to use it but it doesnt seem to be working with the code i have:

```
  @Column({
    type: "varchar",
    nullable: true,
    transformer: {
      from(val: object | null | undefined) {
        return val === null ? "" : JSON.stringify(val);
      },
      to(val: string | null | undefined) {
        return val;
      }
    }
  })
  latlngs: string;
```

maybe I am misunderstanding the demo code

**Comment by silentroach** [comment]
```typescript
  @Column({
    type: "varchar",
    nullable: true,
    transformer: {
      // used to deserialize your data from db field value
      from(val: string) {
        return JSON.parse(val);
      },
      // used to serialize your data to db field
      to(val: object) {
        return JSON.stringify(val);
      }
    }
  })
  latlngs: object;
```

**Comment by hariDasu** [comment]
thank you @silentroach !

**Comment by csdal** [comment]
(a comment for future references, who searched for this error)

In `react-native-sqlite-storage: ^6.0.1`, I experience this:
```
 WARN  addStatement - parameter of type <object> converted to string using toString()
```

Solved by this:
```
values.toString()
```

Example code (Solution):

```
const addOne = async (db, {firstName, lastName})=>{
  const values = [firstName, lastName].toString(); // 👈👈 add .toString() after array-based values
  const statement = `INSERT INTO tableName (firstName, lastName) VALUES (?,?)`;
  await db.execute(statement, values);
}
```
