### ISSUE TITLE
Cannot use Exclude<> as a Column Type

### ISSUE THREAD

**Issue by GabeKuslansky** [typeorm/typeorm#4743]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
 `Error:  UnhandledPromiseRejectionWarning: DataTypeNotSupportedError: Data type "Object" in "Match.region" is not supported by "sqlite" database.` 
```ts
enum Region {
    All,
    NorthAmerica,
    Europe
}

class Match {
	@PrimaryGeneratedColumn()
	id: number;

        @Column()
        Region: Exclude<Region, Region.All>;
}
```

Ideally, the type becomes something like Region.NorthAmerica | Region.Europe as that would be mapped correctly to the database. The exclude is necessary as the enum can grow without the Region type in match needing to ever change.

**Comment by Ginden** [comment]
This isn't supported by Typescript reflection capabilities and it's out of scope of TypeORM. You need to manually define enum type in such case, eg. by:

```ts

class Match {
        @Column('enum', {enum: Object.values(Region).filter(r => r !== Region.all}})
        Region: Exclude<Region, Region.All>;
}
```
