### ISSUE TITLE
Cannot create PgSQL database on the fly

### ISSUE THREAD

**Issue by antoine-pous** [typeorm/typeorm#4747]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
If the specified database name does not exists migrations fail.

A new connection parameter, `TYPEORM_DATABASE_CREATE`, would be awesome to avoid issues related to the missing database.

Then when enabled TypeORM can connect to `postgres` or `template1` database, create the new database and switch on it before starting migrations process.

**Comment by imnotjames** [comment]
This isn't a goal of typeorm.  Should you want this, query runners should have methods to create databases.

However, given how fragile every suggested implementation of this is so far I don't think we'll be moving forward with this feature.
