### ISSUE TITLE
Can't define relations with EntitySchema

### ISSUE THREAD

**Issue by gbirke** [typeorm/typeorm#4749]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I've updated the example code like this, adding a category to the user:

```ts
import {EntitySchema} from "typeorm";

export class User {

    id: number;

    firstName: string;

    lastName: string;

    age: number;

    category?: UserCategory;
}

export class UserCategory {
    id: number;

    name: string;
}

export const UserCategorySchema = new EntitySchema({
    name: 'UserCategory',
    target: UserCategory,
    columns: {
        id: {
            type: 'int',
            generated: true,
            primary: true
        },
        firstName: {
            type: 'varchar'
        },
    },
});

export const UserSchema = new EntitySchema( {
    name: 'User',
    target: User,
    columns: {
        id: {
            type: 'int',
            generated: true,
            primary: true
        },
        firstName: {
            type: 'varchar'
        },
        lastName: {
            type: 'varchar'
        },
        age: {
            type: 'int'
        }
    },
    relations: {
        category: {
            type: 'many-to-one',
            target: UserCategory,
            joinColumn: true
        }
    }
    
})
```

However, this code gives me the following error:
```
TSError: ⨯ Unable to compile TypeScript
src/entity/User.ts (57,9): Type '{ category: { type: string; target: typeof UserCategory; joinColumn: boolean; }; }' is not assignable to type '{ id?: EntitySchemaRelationOptions; firstName?: EntitySchemaRelationOptions; lastName?: EntitySchemaRelationOptions; age?: EntitySchemaRelationOptions; }'.
  Object literal may only specify known properties, and 'category' does not exist in type '{ id?: EntitySchemaRelationOptions; firstName?: EntitySchemaRelationOptions; lastName?: EntitySchemaRelationOptions; age?: EntitySchemaRelationOptions; }'.
```

What am I missing?

Gauging from #3073 and #3632 I think there might be some documentation issue here.

**Comment by kwoon** [comment]
You can fix it by adding generic into `new EntitySchema<User>({})`. 
EntitySchema looks at keys of related class  User and tries to find key with relation's name `category`.
Also you can write something like this:
relations: {
        category: {
            type: 'many-to-one',
            target: UserCategory,
            joinColumn: true
        } as any
    }

**Comment by imnotjames** [comment]
That looks like the answer to me!

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
