### ISSUE TITLE
Cannot insert extra date to joins table

### ISSUE THREAD

**Issue by ivan-ionin** [typeorm/typeorm#4751]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^6.1.3` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have some tables: 

@Entity('vsk_users_roles')
export class UsersRolesEntity extends BaseEntity {

    @Column({
        type: 'varchar',
        length: 32,
        nullable: false,
        comment: '...'
    })
    name: string;

    @Column({
        type: 'varchar',
        length: 255,
        nullable: false,
        comment: '...'
    })
    description: string;

    @OneToMany(type => JoinsRolesToPermissionsEntity, link => link.permission)
    permissions!: UsersPermissionsEntity[];
}

@Entity('vsk_users_permissions')
export class UsersPermissionsEntity extends BaseEntity {

    @Column({
        type: 'varchar',
        length: 64,
        nullable: false,
        comment: '...'
    })
    name: string;

    @Column({
        type: 'varchar',
        length: 255,
        nullable: false,
        comment: '...'
    })
    description: string;

    @Column({
        type: 'int',
        unsigned: true,
        nullable: false,
        default: 0,
        comment: '...'
    })
    weight: number;

    @Column({
        type: 'text',
        nullable: true,
        comment: '...'
    })
    options: any;

    @OneToMany(type => JoinsRolesToPermissionsEntity, link => link.role)
    roles!: UsersRolesEntity[];

    @BeforeUpdate()
    @BeforeInsert()
    stringifyData() {
        this.options = this.options && 'string' !== typeof this.options  ? JSON.stringify(this.options) : this.options || null;
    }

    @AfterLoad()
    parseData() {
        this.options = this.options ? JSON.parse(this.options) : null;
    }
}

And entity for joins table:

@Entity('vsk_joins_roles_to_permissions')
export class JoinsRolesToPermissionsEntity extends BaseEntity {

    @Column()
    public roleId!: number;

    @Column()
    public permissionId!: number;

    @ManyToOne(type => UsersRolesEntity, role => role)
    public role!: UsersRolesEntity;

    @ManyToOne(type => UsersPermissionsEntity, permission => permission)
    public permission!: UsersPermissionsEntity;

    @Column({
        type: 'integer',
        unsigned: true,
        default: 0,
        comment: 'This is weight of link'
    })
    weight: number;
}

When i create new role and add permissions to her i need save weight between role and permissions on joins table!

And I don’t understand how.

**Comment by ivan-ionin** [comment]
const currentPermission = new UsersPermissionsEntity();
currentPermission.name = permission.name;
currentPermission.description = permission.description;
currentPermission.weight = permission.weight;
currentPermission.options = permission.options;
return this.mysql.create(currentPermission).then(() => { ... ... ...

And now i try create role:

const currentRole = new UsersRolesEntity();
currentRole.name = role.name;
currentRole.description = role.description;
currentRole.permissions = [currentPermission];
return this.mysql.create(currentRole).then(() => { ... ... ...

But i need add extra data to joins table.

**Comment by imnotjames** [comment]
https://typeorm.io/#/many-to-many-relations/many-to-many-relations-with-custom-properties

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
