### ISSUE TITLE
Cannot enlarge memory arrays with sqlJS

### ISSUE THREAD

**Issue by ydstaana** [typeorm/typeorm#4752]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

SqlJsConnectionOptions allow for a sqlJsConfig input but there is no information on how to turn on 
ALLOW_MEMORY_GROWTH=1 or to use 

from sqljs documentation
```
sql-asm-memory-growth.js : Asm.js doesn't allow for memory to grow by default, because it is slower and de-optimizes. If you are using sql-asm.js and you see this error (Cannot enlarge memory arrays), use this file.
```

**Comment by imnotjames** [comment]
You can pass in options to `sqljs` directly with `extra` in the connection options.
