### ISSUE TITLE
Question: How to Handle Knowing if Relation Properties are Populated?

### ISSUE THREAD

**Issue by CatGuardian** [typeorm/typeorm#4757]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**My Question:**

I am switching over to using TypeORM from a different ORM and one of the common problems I have with the other ORM is that sometimes in my code I am not sure if a nested entity has been loaded or not.

For example:

```
@Entity()
export class User {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToMany(type => Photo, photo => photo.author, {
    cascade: true,
  })
  photos: Photo[];
}
```

And then, for example, I have a reusable middleware that is used on almost every server endpoint that will retrieve the User object of the person making the request and attach it to the request context.

By attaching it to the request context I am able to access that User object in any of my endpoints that I write. But since the middleware is so reusable I don't automatically have it populate the `photos` property. Now, for example, in one of the endpoints that deals with photos for the User I can't reliably know if the `photos` property has valid data or not. So I have to write code to check to see if the `photos` property is `undefined` and if it is then write code to go get the photos and then work with them.

That is just a made up example to help illustrate a problem I experience but it isn't usually that cut and dry. The real issue usually happens when I start passing the User object into a reusable function and that function passes the User to another unrelated and reusable function and then that function needs to access the `photos` property and since these are functions that are used in a lot of places, the function can't rely on the `User.photos` property to always be populated. So I feel the need to write code that checks to see if the property is defined and if it isn't, then write code to retrieve the property.

My questions are these:
1. Does TypeORM have an already built in function that I can call to populate the relation if it isn't already filled out? Thus making if a 1 line of code that wouldn't really be distracting in my functions (as opposed to writing the several lines of code to check for undefined and retrieve the property from the database if it is undefined)
2. If it doesn't have a built in function like that, then is that a good idea for a feature request?
3. Is there a better way for me to write my code so that there is never a question of if I have the data or not? (like maybe instead of a function taking in just the User object, also take in as another parameter the array of photos that are needed even if the `User.photos` property is filled out)?
4. Any other comments or advice on this matter?

**Comment by ematipico** [comment]
> Does TypeORM have an already built in function that I can call to populate the relation if it isn't already filled out? Thus making if a 1 line of code that wouldn't really be distracting in my functions (as opposed to writing the several lines of code to check for undefined and retrieve the property from the database if it is undefined)

Have you checked the entity listener? https://typeorm.io/#/listeners-and-subscribers/what-is-an-entity-listener

Maybe it could help you out with that.

**Comment by christhegrand** [comment]
How would having an entity listener help in this case? We're having similar issues and are discussing how best to structure the code so that it's clear from the types when the relation is present or not.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
