### ISSUE TITLE
QueryRunner.query() should have a consistent result

### ISSUE THREAD

**Issue by dustin-H** [typeorm/typeorm#4758]
**Issue type: `feature request / API improvement`**

**Database system/driver: `postgres (but basically all)`**

**TypeORM version: `latest (0.2.19)`**

**Description:**

Hi there,

first of all, thanks for that amazing project! :)

For some advanced functionality we are using the `QueryRunner.query()` of Typeorm directly. (Without QueryBuilder).

This API has changed recently: https://github.com/typeorm/typeorm/commit/7808bba416c0b1cf9850194499e8c8d3502657b7

Before it returned an array of rows for each query.

Now it returns a different result dependent on the incoming query.

When I run a create or select query it returns an array of rows like before.

However, if I run an update or delete query it returns an array with two elements. The first one is the array rows, and the second one is an integer which describes the affected rows by an update/delete.

For me it is really important to also get the affected rows, but I need to build switches everywhere dependent on the query-type to parse the result.

How about changing this result-array to an object. There we can add as many metadata as we want without breaking the general usage.

Here my intent for a result object:

```ts
interface QueryRunnerResult {
  rows: any[];
  affectedRows?: number;
  raw: any; // Raw result from db-driver (This would solve any future problems of people who need any meta-data from the result)
}
```

What do you think about that?
If you agree I would make a pull request. (at least for the pg-driver)

**Comment by mshwery** [comment]
Related to https://github.com/typeorm/typeorm/issues/4817
