### ISSUE TITLE
Running persist on existing Entity with a Composite Key uses INSERT INTO instead of UPDATE in MySQL

### ISSUE THREAD

**Issue by ykim** [typeorm/typeorm#477]
I'm currently using typeorm 0.0.9. As the title states, when I run persist on an Entity with multiple PrimaryKeyColumn(s), typeorm correctly inserts it on the initial call. However, after I retrieve the Entity using a QueryBuilder and update non-primary fields, calling persist issues an INSERT INTO command instead of an UPDATE, which yields ER_DUP_ENTRY errors. Is this the intended behavior? If so, is there a solution around this?

**Comment by pleerock** [comment]
improved support for composite primary keys are coming in next big release via #337

**Comment by ykim** [comment]
I see. So, there isn't a solution currently, correct? I'm guessing that I'll have to do some work around in this case then. Thanks :)

**Comment by pleerock** [comment]
this should be implemented in `0.1.0-alpha.2` - you can try it via `npm i typeorm@next`

**Comment by pleerock** [comment]
Please let me know if it still do not work in latest 0.1.0 alpha versions.
