### ISSUE TITLE
How can I select the "parent" relation ID?

### ISSUE THREAD

**Issue by lffg** [typeorm/typeorm#4773]
**Issue type:**

- [x] **question**
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

**Database system/driver:**

- [ ] `cordova`
- [ ] `mongodb`
- [ ] `mssql`
- [x] **`mysql` / `mariadb`**
- [ ] `oracle`
- [ ] `postgres`
- [ ] `cockroachdb`
- [ ] `sqlite`
- [ ] `sqljs`
- [ ] `react-native`
- [ ] `expo`

**TypeORM version:**

- [x] **`latest`**
- [ ] `@next`
- [ ] `0.x.x` (or put your version here)

I have the following `EventImage` entity:

```ts
@Entity()
export class EventImage {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('text')
  uri: string;

  @ManyToOne(() => Event, (event) => event.images)
  event: Event;
}
```

Which creates the following table structure in the SQL database:

| id | uri | eventId |
| -- | --- | ------- |

How can I select that `eventId` field? I need that field, and the only way I find to get it is to use an `INNER JOIN` in the query builder, which is obviously unnecessary. Why I need to make a `JOIN` if I already have the field in my table?

So, as described above, I am currently doing this:

```ts
const images = await getRepository(EventImage)
  .createQueryBuilder('image')
  .innerJoinAndSelect('image.event', 'event') // :(
  .select(['image', 'event.id'])
  .where('image.eventId IN (:...ids)', { ids: eventIds })
  .getMany();
```

The question is: how I can get that `eventId` field without need to mess up with relations (which is _not_ what I need)?

I would be extremely grateful for your help.

**Comment by XuToTo** [comment]
```
  @ManyToOne(() => Event, (event) => event.images)
  event: Event;
```

**Comment by XuToTo** [comment]
Hi, I have found a workaround in [official document](https://typeorm.io/#/relations-faq/how-to-use-relation-id-without-joining-relation).

So, you need add an `eventId` field in your entity class:

```
@Entity()
export class EventImage {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('text')
  uri: string;

  @ManyToOne(() => Event, (event) => event.images)
  event: Event;

  @Column({ nullable: true })
  eventId: string;
}
```

Hope this helps ;-)

**Comment by lakinduakash** [comment]
@XuToTo It works!
Thanks
:)
