### ISSUE TITLE
Duplacate alias in generated SQL request

### ISSUE THREAD

**Issue by Iruora** [typeorm/typeorm#4776]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.18`

Whenever the sum of a database column name length and the entity name length, both exceeds 32 character which is the maximum alias or column length in oracle database we get ambiguous generated aliases making request failure.

Example :

let's suppose we have an entity named '**BeneficiaryClient**' wich have two database column named **BENEFI_CLIENT_AMOUNT_DELIVERED** and **BENEFI_CLIENT_AMOUNT_ACCEPTED**.
We create a query builder and w specify the alias with three significatifs letters (ie: **bcl**)

the generated request aliases normally should look like the following: 
```
 SELECT .... bcl.BENEFI_CLIENT_AMOUNT_DELIVERED AS 
                 bcl_BENEFI_CLIENT_AMOUNT_DELIVERED, -- 32 oracle alias length rule not respected 
                 bcl.BENEFI_CLIENT_AMOUNT_ACCEPTED AS
                 bcl_BENEFI_CLIENT_AMOUNT_ACCEPTED -- 32 oracle alias length rule not respected 
```
 
but we get the following : 
```
 SELECT .... bcl.BENEFI_CLIENT_AMOUNT_DELIVERED AS 
                 bcl_, 
                 bcl.BENEFI_CLIENT_AMOUNT_ACCEPTED AS
                 bcl_ 
```
We've got two different columns with the same alias => ambiguity 
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
Is this still a problem?
