### ISSUE TITLE
Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by booradleys** [typeorm/typeorm#478]
Hi there,
I got this issue:

{"name":"TypeError","message":"Cannot read property 'target' of undefined","stack":"TypeError: Cannot read property 'target' of undefined\n    at TCandidatRepository.Repository.createQueryBuilder (C:\\Applications\\Node\\exotica\\node_modules\\typeorm\\repository\\Repository.js:79:32)\n    at TCandidatRepository.getNbInscritsValides (C:\\Applications\\Node\\exotica\\server\\dist\\repository\\TCandidatRepository.js:50:30)\n    at IndexController.guest (C:\\Applications\\Node\\exotica\\server\\dist\\modules\\default\\controllers\\IndexController.js:33:48)\n    at ActionMetadata.executeAction (C:\\Applications\\Node\\exotica\\node_modules\\routing-controllers\\metadata\\ActionMetadata.js:258:62)\n    at C:\\Applications\\Node\\exotica\\node_modules\\routing-controllers\\RoutingControllerExecutor.js:74:33\n    at process._tickCallback (internal/process/next_tick.js:103:7)"}

```typescript
// TCandidatRepository.ts
import { Inject, Service, Container } from "typedi";
import {Request} from "express";
import { FindOptions } from "typeorm";
import { Repository, EntityRepository } from "typeorm";
import { OrmCustomRepository } from "../../../node_modules/typeorm-typedi-extensions/decorators/OrmCustomRepository";
import { TCandidat } from "../entity/TCandidat";

// create custom Repository class
@Service()
@EntityRepository(TCandidat)
export class TCandidatRepository extends Repository<TCandidat>
{
    getNbInscritsValides(group_id: number) {
            const results = this.createQueryBuilder('c1')
                    .select("*")
                    .from('TCandidat', 'c')
                    //.where('c.idGroupe = :group_id')
                    //.andWhere('c.statut in (1,2,3)')
                    //.setParameter('group_id', group_id)
                    //.getOne();
                    ;
            return results;
    }
}
```
I don't understand why.
David

**Comment by pleerock** [comment]
David, please format code properly before posting. Noone will spend time helping you if you dont spend your time to provide a good question.

Don't do `.select("*").from('TCandidat', 'c')`. What do you want to achieve?
