### ISSUE TITLE
orWhere breaks setFirstResult / setMaxResult

### ISSUE THREAD

**Issue by emorris00** [typeorm/typeorm#479]
I believe this is also a problem with skip / take.

When you use setFirstResult and setMaxResult the querybuilder runs 2 queries behind the scenes. The first query gets the entity ids and the second query gets the entities. When executing the second query to get the entities from the ids, it clones the query and adds an andWhere.
https://github.com/typeorm/typeorm/blob/master/src/query-builder/QueryBuilder.ts#L1046
If the original query had an orWhere in it, it breaks because the end query is:
`WHERE test1 OR test2 AND ids IN (...)`

Adding paranthesis to make it clear how it executes:
`WHERE test1 OR (test2 AND ids IN (...))`

It needs to be:
`WHERE (test1 OR test2) AND ids IN (...)`

Some example code to reproduce:
```javascript
@Entity()
class Test {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    column1: string
}

createConnection({
    // connection options
}).then(async connection => {
    var repository = connection.getRepository(Test)

    var result = await repository
        .createQueryBuilder('test')
        .where("test.column1 LIKE :filter")
        .orWhere("test.column1 LIKE :filter")
        .setParameter("filter", "%%")
        .setFirstResult(0) // or skip
        .setMaxResults(1) // or take
        .getMany()

    // result will have every Test instead of just the first one
})
```

**Comment by pleerock** [comment]
this is fixed in `0.1.0-alpha.2` - you can try it via `npm i typeorm@next`
