### ISSUE TITLE
PostGres requires superuser priveleges to access database

### ISSUE THREAD

**Issue by StephenPaul** [typeorm/typeorm#481]
First of all, congrats on the amazing library.

I noticed that, when attempting to connect to my Postgres database, I could not connect without providing superuser privileges to my user. Am I missing an option in the configuration options by any chance?

**Comment by pleerock** [comment]
Thank you,

`typeorm` uses [node-pg](https://github.com/brianc/node-postgres) underlying driver, so if you can't access db without superuser then try to do it via node-postgres directly without typeorm.

Or, if you are able to make connection, then maybe some query typeorm executes require you special priveleges. If so, then try to enable query logging and check what sql query is problematic for you.

**Comment by StephenPaul** [comment]
Thanks @pleerock. Actually my dev-ops guy had it wrong. Just gave the user ownership of the DB and no further problems. Thanks for your attention nonetheless.
