### ISSUE TITLE
An open transaction is required for pessimistic lock.

### ISSUE THREAD

**Issue by istoros** [typeorm/typeorm#4810]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When I try to run this method, I accept Error: An open transaction is required for pessimistic lock.
What's wrong?
```ts
    public constructor(
        @InjectRepository(User)
        @TransactionRepository(User)
        private readonly userRepository: Repository<User>
    ){}

    @Transaction()
    public async test(userId: string) {
        await this.userRepository.findOne({
            where: {
                userId: userId
            },
            lock: { mode: "pessimistic_write" }
        });

        ...
        
        await this.userRepository.update({ userId }, { balance: 50 });
        return await this.userRepository.findOne({ userId });
    }
```

**Comment by slavafomin** [comment]
I'm having exactly the same question, @pleerock can you elaborate on this please?

I'm calling `findOne()` on repository instantiated from transaction entity manager, but getting the same error.

**Comment by slavafomin** [comment]
While waiting for a response, I've implemented a following helper-function, which could be used with PostgreSQL to find and lock entities by ID:

```typescript
import { EntityManager } from 'typeorm';
import { ObjectType } from 'typeorm/common/ObjectType';


export async function selectByIdForUpdate<EntityType>(
  entityClass: ObjectType<EntityType>,
  id: number,
  entityManager: EntityManager,
  lockingClause?: ('NOWAIT' | 'SKIP LOCKED')

): Promise<EntityType> {

  const repository = entityManager.getRepository(entityClass);

  await repository.query(
    (`
      SELECT FROM "${repository.metadata.tableName}"
      WHERE id = $1
      FOR UPDATE ${lockingClause || ''}
    `), 
    [id]
  );

  return repository.findOne(id);

}
```

It also supports [Locking Clause](https://www.postgresql.org/docs/12/sql-select.html).

**Comment by imnotjames** [comment]
The issue here is that the `queryRunner` you've got in that repository is NOT the same query runner in the transaction decorator.

As such, no, you have no transaction active.

The transaction decorator gives you new arguments - the transaction manager, the repositories, etc - you have to use those to be within the transaction.
