### ISSUE TITLE
Slack invite link is no longer active

### ISSUE THREAD

**Issue by bbenoist** [typeorm/typeorm#4811]
**Issue type:**

[x] documentation issue

**Database system/driver:**

N/A

**TypeORM version:**

N/A

**Steps to reproduce or a small repository showing the problem:**

1. Go to https://typeorm.io/#/
2. Click on the Slack icon (top-right of the page): ![image](https://user-images.githubusercontent.com/2091902/65605477-706a6a00-dfa9-11e9-9ac2-820f18f5f947.png)
3. The following error is displayed: ![image](https://user-images.githubusercontent.com/2091902/65605358-41ec8f00-dfa9-11e9-83f6-916007d452dd.png)

**Comment by silentroach** [comment]
partially fixed in a3b2ee0c96379339b8d707a520d9c853b184b94d and in #4836

**Comment by pleerock** [comment]
This was already fixed, thanks
