### ISSUE TITLE
grouping by some not-pk column requires the pk in the group list

### ISSUE THREAD

**Issue by dengue8830** [typeorm/typeorm#4814]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.19` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
### TLDR;
1) create a simple table with `id` and some other column
2) use querybuilder to select the other column
3) add a `groupby` pointing to the `some other column`
4) see the error
`QueryFailedError: Error: Column 'Podcast.Id' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.`

### Long version
hi! i'm new on typeorm and i giving it a chance. Its an awesome project!

This code

```
await getRepository(Podcast)
      .createQueryBuilder('p')
      .select('p.season')
      .getMany();
```

generates this result

```
[  { season: 1 }, { season: 1 } ]
```

and adding a simple group by 

```
await getRepository(Podcast)
      .createQueryBuilder('p')
      .select('p.season')
      .groupBy('p.season')
      .getMany();
```

produces this error

```
QueryFailedError: Error: Column 'Podcast.Id' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
```

if i add the requested `id` 

```
await getRepository(Podcast)
      .createQueryBuilder('p')
      .select('p.season')
      .groupBy('p.season')
      .addGroupBy('p.id')
      .getMany();
```

the result is

```
[ { season: 1 }, { season: 1 } ]
```

the error is gone but the result is not what i expected, because i just want to group by `season` and should get one single item (because both are from the same `season`). 

Thanks in advance

**Comment by ahmadarif** [comment]
I get this issue on mssql too, but it doesn't happen on mysql.

**Comment by Asatelit** [comment]
Same problem: TypeORM 0.2.20 + Postgres.

**Comment by Innovator007** [comment]
I am facing the same issue working with typeorm and postgresql database. Generates same kind of error. Does anyone know a fix for this?

**Comment by imnotjames** [comment]
Use `getRawMany` - you're trying to map back into the podcast object something that's not a podcast.

**Comment by Innovator007** [comment]
Thanks @imnotjames 👍🏻

**Comment by imnotjames** [comment]
Suffice it to say - this isn't a bug - more of a support request

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
