### ISSUE TITLE
Breaking change for raw UPDATE statements

### ISSUE THREAD

**Issue by chriskalmar** [typeorm/typeorm#4817]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

PR #4432 introduced a breaking change for raw `UPDATE` statements. 

Given the following update statement:
```sql
UPDATE product SET state = $2 WHERE NAME LIKE $1 RETURNING * -- PARAMETERS: ["phone%",4]
```

the result in the latest `0.2.19` release is this:
```js
[ 
  [ 
    { id: '28', name: 'phone1', state: 4 },
    { id: '29', name: 'phone2', state: 4 } 
  ],
  2 
]
```

but in `0.2.18` it looked like that:
```js
[  
  { id: '21', name: 'phone1', state: 4 },
  { id: '22', name: 'phone2', state: 4 } 
]
```

As you can see here, the result gets now nested inside another array. The change is quite profound and deserves at the very least a `Breaking Change` mention in the changelog.

While we are at it, why not introduce the very same structure to `INSERT` statements as well? At least this would bring in full consistency among all query types. (`DELETE` is covered already)

**Comment by silentroach** [comment]
@j6lim ⬆️

**Comment by joras** [comment]
Do we know if this is intentional change and we need to update our code to handle typeorm versions >= 0.2.19 , or will this be reverted?

**Comment by mshwery** [comment]
This is a fairly significant breakage – it is no longer possible to rely on a consistent return from raw queries.

**Comment by imnotjames** [comment]
This is indeed an intentional change.

I'm currently in the process of figuring out how to get a more consistent result in place.

**Comment by silentroach** [comment]
See you next year

**Comment by imnotjames** [comment]
A heads up - I've opened PR #7753 which adds a temporary extra option to `query` - `useStructuredResult`.  This is mostly to prevent some backwards compatibility breaks again.

When it's set, a `QueryResult` object is returned with a consistent API.
