### ISSUE TITLE
Update an entity without loading it first

### ISSUE THREAD

**Issue by Tobias4872** [typeorm/typeorm#482]
Hi,

is it possible to update an entity without loading it from the DB first? I am trying to update an entity in the database with the repository.persist() method. I am passing a plain JS object which already carries the correct id, but repository.persist() will try to INSERT the entity instead of running an UPDATE on it. Is there a trigger that I can use to insist on an UPDATE instead of an INSERT?

Thanks,
   Tobias.

**Comment by pleerock** [comment]
yes it is possible. Please provide an example of what you are doing. Most probably your id is not equal to id in the database. Because if you provide any new object but with exist id in the database orm will always update that entity.

**Comment by Tobias4872** [comment]
Finally found the problem. I did re-set the id of the entity, but set it as a string and not as a number. So, the explanation you provide below perfectly makes sense.

This is good to be closed.
