### ISSUE TITLE
What Is Recommended Practice For Preserving Data When Schema Changes?

### ISSUE THREAD

**Issue by JimLynchCodes** [typeorm/typeorm#4823]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, first of all thanks for making this awesome ORM! I have been using this on a project successfully, but when I run migrations I often get errors that my current data does not fit the new schema.

For example, suppose I initially have one entity with property that is an enum of strings, and then in a migration it is changed to a new Entity (ie db table where that old string is a property of new entity). What’s the recommended way to convert our current production data to the new scheme? 🤔

Thanks!

**Comment by tphbrok** [comment]
_This is not a TypeORM issue, but more of a deployment issue. Yet, I still have an answer for you._

A migration is not defined as a change of the data model. If you add/remove a column, change types or make any changes to the data model that results in incorrect data, you have to make a pre/post-migration.

**Example** (I want to add non-nullable column to table A, which already has data in it)
1. Add **nullable** column to table A.
2. Column will have value `null` for each row.
3. Insert values into this column for all rows, leaving **no** `null`'s afterwards.
4. Alter the table and make the column **non-nullable**.

So in the end, the migration is still the addition of a column, but you just need to manipulate the data or the order of operations to get it done.

Hope it helps!

**Comment by imnotjames** [comment]
Looks like this was answered pretty well there! Closing.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
