### ISSUE TITLE
why Typeorm slows down when using simple where in operator

### ISSUE THREAD

**Issue by uraman2000** [typeorm/typeorm#4828]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

i am using the typeorm where in operators where i get the max(date) for each location and after about 70 location it returns the data after 90 second where in sql server takes only 5 seconds.

this is what i got so far this code works but the after alot of unsynclocations it slows that to the point it wont rerurn data anymore.

> const getLastTimeIn = await getRepository(TimeInOut)
>   .createQueryBuilder("TimeInOut")
>   .select(["max(DateTrans) as date"])
>   .where("location IN (:...location)")
>   .setParameters({ location: unsyncLocations })
>   .groupBy("location")
>   .getRawMany();

i also tried looping the locations but it seems much slower than the code above

> 
> for (let i = 0; i < unsyncLocations.length; i++) {
>   const element = unsyncLocations[i];
>   const getLastTimeIn = await getRepository(TimeInOut)
>     .createQueryBuilder("TimeInOut")
>     .select("top 1 DateTrans")
>     .where("location = :location")
>     .setParameters({ location: element })
>     .orderBy("DateTrans", "DESC")
>     .getRawMany();
>   console.log(getLastTimeIn);
>   await unsyncData.push({
>     id: id,
>     location: element,
>     DateTrans: this.dateFormater(getLastTimeIn[0].DateTrans)
>   });
>   id++;
> }

this is the entity for the timeinout

> 
> @Entity("TimeInOut")
> export class TimeInOut {
>   @PrimaryColumn("int")
>   ID: number;
>   @Column("datetime")
>   DateTrans: string;
>   @Column("int")
>   Attrib1: string;
>   @Column("varchar", { length: 30 })
>   Attrib2: string;
>   @Column("int")
>   Attrib3: string;
>   @Column("int")
>   Attrib4: string;
>   @Column("int")
>   IsSync: string;
>   @Column("varchar", { length: 100 })
>   location: string;
>   @Column("datetime")
>   timeStampLog: string;
>   @Column("varchar", { length: 500 })
>   CompanyId: string;
>   @Column("varchar", { length: 500 })
>   sourcelocation: string;
> }
>

**Comment by imnotjames** [comment]
Pretty sure this was fixed by #7821
