### ISSUE TITLE
TransactionError: Transaction has been aborted.

### ISSUE THREAD

**Issue by jerrythimothyj** [typeorm/typeorm#4830]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
async create(tenantid: string, staff: StaffDto): Promise < any > {
  const connection = getConnection();
  const queryRunner = connection.createQueryRunner();
  await queryRunner.connect();
  await queryRunner.startTransaction();

  try {
    const userQuery = `insert into Users(Username, Password)  Output Inserted.Id values('${User.Username}', '${User.Password)
  }')`;
    await queryRunner.query(userQuery);

  const query = `insert into Address( CountryId,StateProvinceId,City,Address1,Address2,ZipPostalCode,PhoneNumber )  Output Inserted.Id values('${staff.Address.CountryId}','${staff.Address.StateProvinceId}','${staff.Address.City}','${staff.Address.Address1}','${staff.Address.Address2}','${staff.Address.ZipPostalCode}','${staff.Address.PhoneNumber}')`;
  await queryRunner.query(query);

  await queryRunner.commitTransaction();
  return {
    ...staff,
    Id: userQueryResult[0].Id,
  };
} catch (err) {
  await queryRunner.rollbackTransaction();
  this.errorService.throwAPIError(err);

} finally {
  await queryRunner.release();
}
}
```

I am trying to perform a rollback on a failed transaction. What happens in the above code is that, the Address query throws an exception when it is trying to CountryId is with 'undefined', hence an exception occurs and comes to the catch block.

But, rollback fails with:
```
TransactionError: Transaction has been aborted.
    at Transaction._rollback (/Users/xxx/Documents/codes/yyy/node_modules/mssql/lib/base.js:984:37)
    at Transaction._rollback (/Users/xxx/Documents/codes/yyy/node_modules/mssql/lib/tedious.js:370:11)
    at Transaction.rollback (/Users/xxx/Documents/codes/yyy/node_modules/mssql/lib/base.js:957:12)
    at /Users/xxx/Documents/codes/yyy/src/driver/sqlserver/SqlServerQueryRunner.ts:156:37
    at new Promise (<anonymous>)
    at SqlServerQueryRunner.<anonymous> (/Users/xxx/Documents/codes/yyy/src/driver/sqlserver/SqlServerQueryRunner.ts:155:16)
    at step (/Users/xxx/Documents/codes/yyy/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/xxx/Documents/codes/yyy/node_modules/tslib/tslib.js:117:57)
    at /Users/xxx/Documents/codes/yyy/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
```

**Comment by imnotjames** [comment]
I think this is closer to something that MSSQL does - when you are in a query and a bit of SQL fails it will abort the query.

This can be configured via [SET XACT_ABORT](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-xact-abort-transact-sql?view=sql-server-ver15)

Not really a problem with TypeORM.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
