### ISSUE TITLE
Columns with the type "enum" are not supported in the migration API

### ISSUE THREAD

**Issue by ZsoltMaslanyi** [typeorm/typeorm#4833]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When writing migrations by hand using the migration API to create a new table that has an enum column 3 things happen that shouldn't: 
- The generated SQL does not sets the column's type to enum.
- Worse, it sets the column's type to "[Tablename]_[column]_enum".
- The "enum" TableColumnOptions parameter gets ignored.

A simple example:

```ts
// == The entity

export enum RatingType {
  low = 'bad',
  neutral = 'neutral',
  good = 'good'
}

@Entity({ name: 'Ratings' })
export default class Rating extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column({ type: 'enum', enum: RatingType })
  rating: RatingType
}

// == The migration

import { MigrationInterface, QueryRunner, Table } from 'typeorm'

export class CreateRatings1569818629816 implements MigrationInterface {
  private ratingsTable = new Table({
    name: 'Ratings',
    columns: [
      {
        name: 'id',
        type: 'uuid',
        isPrimary: true,
        isGenerated: true,
        generationStrategy: 'uuid',
      },
      {
        name: 'rating',
        type: 'enum',
        enum: ['bad', 'neutral', 'good'],
        isNullable: true
      }
    ],
  })

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(this.ratingsTable, true)
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable(this.ratingsTable)
  }
}

```

The generated SQL looks like this:

```
CREATE TABLE "Ratings" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "rating" "Ratings_rating_enum",
  CONSTRAINT "PK_ee6436ff188c9bb00cc70fc447a" PRIMARY KEY ("id")
)
```

**Comment by jrbytes** [comment]
Try:

await queryRunner.query('DROP EXTENSION "uuid-ossp"')
await queryRunner.query('CREATE EXTENSION "uuid-ossp"')

Before your 
await queryRunner.createTable(this.ratingsTable, true)

**Comment by kishan-samcom** [comment]
how to set default value for enum

**Comment by jrbytes** [comment]
> how to set default value for enum

@kishan-samcom  my migration have one column:
```javascript
{
  name: 'type',
  type: 'enum',
  enum: ['income', 'outcome'],
},
```
Work perfectly.
https://raw.githubusercontent.com/jrbytes/desafio-database-upload/master/src/database/migrations/1587076060658-CreateTransactions.ts

**Comment by ralmarri12** [comment]
> how to set default value for enum

this worked with me

`
{
    name: 'status',
    type: 'enum',
    enum: ['active', 'inactive', 'paused'],
    enumName: 'statusEnum',
    default: '"inactive"'
}
`

**Comment by vinayuttam** [comment]
We already have a table which has an `enum` column with some values. However, if we want to support more values, how should the migration be defined if required?

**Comment by kkoomen** [comment]
> > how to set default value for enum
> 
> this worked with me
> 
> ```
> {
>     name: 'status',
>     type: 'enum',
>     enum: ['active', 'inactive', 'paused'],
>     enumName: 'statusEnum',
>     default: '"inactive"'
> }
> ```

@ralmarri12 The `enumName` field was the field I was missing. That did the trick.

**Comment by bigLucas** [comment]
> > how to set default value for enum
> 
> this worked with me
> 
> ```
> {
>     name: 'status',
>     type: 'enum',
>     enum: ['active', 'inactive', 'paused'],
>     enumName: 'statusEnum',
>     default: '"inactive"'
> }
> ```

**Almost the same solution**, but here with typeorm `0.2.30` and `Postgres` as database, I **fixed** with this:
```typescript
// enum
enum NiceEnum {
    FOO: 'FOO',
    BAR: 'BAR',
}
// column
{
    name: 'status',
    type: 'enum',
    enum: [NiceEnum.FOO, NiceEnum.BAR],
    enumName: 'statusEnum',
    default: `'${NiceEnum.FOO}'` // here, I used single quotes
}
```

**Comment by marlon-poloni** [comment]
> > > how to set default value for enum
> > 
> > 
> > this worked with me
> > ```
> > {
> >     name: 'status',
> >     type: 'enum',
> >     enum: ['active', 'inactive', 'paused'],
> >     enumName: 'statusEnum',
> >     default: '"inactive"'
> > }
> > ```
> 
> **Almost the same solution**, but here with typeorm `0.2.30` and `Postgres` as database, I **fixed** with this:
> 
> ```ts
> // enum
> enum NiceEnum {
>     FOO: 'FOO',
>     BAR: 'BAR',
> }
> // column
> {
>     name: 'status',
>     type: 'enum',
>     enum: [NiceEnum.FOO, NiceEnum.BAR],
>     enumName: 'statusEnum',
>     default: `'${NiceEnum.FOO}'` // here, I used single quotes
> }
> ```

It saved me, thanks! :heart:

**Comment by 1cornerstone** [comment]
{
    name: 'status',
    type: 'enum',
    enum: ['active', 'inactive', 'paused'],
    enumName: 'statusEnum',
    default: "'inactive'"
}
this saved me
