### ISSUE TITLE
Running Postgres COPY FROM in TypeORM transaction

### ISSUE THREAD

**Issue by osdiab** [typeorm/typeorm#4839]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I would love the ability to run a Postgres `COPY FROM` command inside of a TypeORM transaction (for a data population script that I'm writing, for which normal `INSERT` calls are quite slow).

While I can use `query()` to actually run the command, I don't know how to actually make the data file accessible to the server within my node script, and I don't know how to use pipe the data to `STDIN` if I try to run the `COPY` command that way ([`node-pg-copy-streams`](https://github.com/brianc/node-pg-copy-streams) exists, but that requires actually getting a handle to the `pg` driver instance, which I'm also not sure how to do with TypeORM, especially in the context of a transaction (does that change anything?)

For now I'm just writing the files to disk, and then uploading them in a separate step using `psql`'s `\copy` command. But it would be nice if my script could also do the copy in the same transaction that fetched and transformed the data in the first place, though I the part I can't get past is actually sending the file data to the server.

**Comment by darky** [comment]
You can expose native postgres client via `queryRunner.databaseConnection` on your transaction entity manager

**Comment by osdiab** [comment]
I'll give it a go soon to see if I can make that work, for some reason that didn't occur to me - will report back soon :)

**Comment by imnotjames** [comment]
Sounds like it worked!

**Comment by sapabg** [comment]
Any idea why there is no documentation on queryRunner here https://typeorm.io/ ?

**Comment by polastre** [comment]
### How do you use postgres `COPY FROM` in typeorm to bulk import?

This is for anyone else that runs into this same question. I couldn't figure out how to get access to `queryRunner.databaseConnection` because it is protected within the BaseDriver class. This is how I hacked it. Would love to hear if there's a better way to do this.

```
import { PostgresQueryRunner } from 'typeorm/driver/postgres/PostgresQueryRunner'
import { pipeline } from 'stream/promises';
import { from as copyFrom } from 'pg-copy-streams';

const pgConnection = await (<PostgresQueryRunner>queryRunner).connect();
await pipeline(
    fs.createReadStream("datafile.csv"),
    pgConnection.query(copyFrom('COPY table_name FROM STDIN WITH (FORMAT csv, HEADER TRUE)')),
);
```

**Comment by CannuJ** [comment]
Is this still the current workaround? I am trying to stream CSV data from a source into a Postgres-like db and would really love to be able to query it through my existing DataSource connection.
