### ISSUE TITLE
Cant implement the one to one relationship

### ISSUE THREAD

**Issue by httpsOmkar** [typeorm/typeorm#484]
While implementing  the one to one relationship I got one problem
If I have two tables 1) `user` 2) `user_basic_info`
I have inserted data in the user and user_basic_info but problem is if I repeat the user_basic_info query then it can inserted. So need the `unique` in the `RelationOptions`.

**Comment by pleerock** [comment]
please provide a code example what you are doing

**Comment by httpsOmkar** [comment]
User issue token
```typescript
import { Entity, Column, PrimaryColumn, OneToOne, ManyToOne, JoinColumn } from 'typeorm';
import { UserModel } from '../user-authentication/user';

@Entity()
export class UserBasicInfo {
  @PrimaryColumn('uuid', {
    type: 'uuid',
    generated: true
  })
  id: string;

  @Column('string', {
    type: 'string',
    nullable: false,
  })
  name: string;
  @OneToOne(type => UserModel, user => user.basicInfo, {
    // Need Unique here
    nullable: false,
    cascadeRemove: false
  })
  @JoinColumn()
  user: UserModel;
}
```

User
```typescript
import {
  Entity,
  PrimaryColumn,
  Column,
  OneToOne,
  JoinColumn,
  OneToMany
} from 'typeorm';

import { UserBasicInfo } from '../registration/user-basic-info';

@Entity('authentication_user_authentication_user')
export class UserModel {
  @PrimaryColumn('uuid', {
    type: 'uuid',
    generated: true
  })
  id?: string;

  @Column('string', {
    nullable: false
  })
  firstName: string;

  @Column('string', {
    nullable: false
  })
  lastName: string;

  @OneToOne(type => UserBasicInfo, user => user.user)
  basicInfo: UserBasicInfo;

}

```

```typescript

const user = new UserModel();
const userBasicInfo = new UserBasicInfo();
user.email = 'something';
...
await connection.persist(user);
userBasicInfo.name = 'Something';
// I can call this many times and it create the row in the basic info of duplicate user
await connection.persist(user);
user.id = null;
await connection.persist(user);
user.id = null;
await connection.persist(user);
user.id = null;
await connection.persist(user);
user.id = null;
await connection.persist(user);
user.id = null;
await connection.persist(user);
user.id = null;
```

**Comment by pleerock** [comment]
Feels like problem with `uuid`. Can you check it again without `uuid`, simple `generated: true` ?

**Comment by zumazu** [comment]
Same issue here, when I persist User entity with data related to OneToOne-connected Profile entity, it creates a new instance each time I call the repository to flush changes to DB. I use PrimaryGeneratedColumn in both tables as id. Feels like OneToOne is not that 'toOne' :D

**Comment by zumazu** [comment]
Just to note, if I disable 'cascadeInsert', nothing happens. It doesn't make any changes to db. I ended up using profile repository and it works like a charm. I'd love to contribute to TypeORM and make any possible positive impact but my skills are rather low and I'd need some guidance in the source code as it seems overwhelming.

**Comment by pleerock** [comment]
there are few know issues with one-to-one relation when u are trying to save from inverse side of it. Maybe you faced them. Fix for those issues are scheduled in my refactoring plan. If you want to contribute to typeorm it would be very great. But you need to start from small and implement small tasks first. This particular issue is quite complex.
