### ISSUE TITLE
(Expo) TypeError: undefined is not an object (evaluating '_this.sqlite.openDatabase')

### ISSUE THREAD

**Issue by crofoot** [typeorm/typeorm#4846]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[x] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Issue: I haven't seen any examples with typeorm & expo. I am trying to get a basic application working/connecting to a sqlite db, but I keep running into this issue. 

 ``` 
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_this.sqlite.openDatabase')]
- node_modules\typeorm\browser\driver\expo\ExpoDriver.js:63:56 in <unknown>
````

Any insight would be great, I provided the code I am testing with below, and I bootstrapped the project with expo-cli. 

App.tsx 
``` 
import 'reflect-metadata';
import React from 'react';
import List from './src/List';
import { Item } from './entities/item';
import { View, Button, Text } from 'react-native';
import { createConnection, getRepository } from "typeorm";

interface State {
  data: Item[];
}

interface Props {

}


export default class App extends React.Component<Props, State> {

  constructor(props: Props) {
    super(props);

    this.state = {
      data: []
    };

    this.connect();

  }


  async connect() {
    return await createConnection({
      database: "test",
      entities: [
        Item
      ],
      synchronize: true,
      type: "expo",

    });
  }


  private addString = async () => {
    let item = new Item();
    item.name = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
    await getRepository(Item).save(item);
    this.setState({
      data: [...this.state.data, item]
    });
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <Button title='Add' onPress={this.addString} />
        <List data={this.state.data} />
      </View>
    );
  }
}
```

item.ts 
```
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

@Entity('item')
export class Item {

    @PrimaryGeneratedColumn()
    id!: number;

    @Column('text',{nullable:true})
    name!: string;

}
```

List.tsx
```
import * as React from 'react';
import { View, Text, FlatList } from 'react-native';
import { Item } from '../entities/item';

export interface Props {
    data: Item[];
}

export interface State {

}

export default class List extends React.Component<Props, State> {

    constructor(props: Props) {
        super(props);
    }

    public render() {
        return (
            <FlatList
                data={this.props.data}
                renderItem={({item}) => <Text>{item.name}</Text>}
            />
        );
    }

}

```

package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "expo-sqlite": "^7.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-sqlite-storage": "^4.1.0",
    "react-native-web": "^0.11.7",
    "reflect-metadata": "^0.1.13",
    "typeorm": "^0.2.19"
  },
  "devDependencies": {
    "@types/node": "^12.7.9",
    "@types/react": "^16.8.23",
    "@types/react-native": "^0.57.65",
    "babel-preset-expo": "^7.0.0",
    "typescript": "^3.4.5"
  },
  "private": true
}
```

**Comment by fluciotto** [comment]
Hi,

I have the same problem.
With Expo SDK 35, window.Expo.SQLite is undefined (and read-only), even if expo-sqlite is loaded.

I achieved to make it work with a modification to the file "/src/driver/expo/ExpoDriver.ts", by replacing "this.sqlite = window.Expo.SQLite;" in the function loadDependencies() with "this.sqlite = require('expo-sqlite')".
But it's a weird workaround, just pointing where is the problem.

I think you'll have to downgrade to Expo SDK 34 for now.

**Comment by lookitsatravis** [comment]
Another workaround that worked for me. Inside my root component (App in my case), I added this before the App class declaration:

```ts
(window as any).Expo = Object.freeze({ ...(window as any).Expo, SQLite });
```

where SQLite is from `import * as SQLite from 'expo-sqlite';`.

Note: I needed to install expo-sqlite version 7.0.0 (latest as of this comment) in order for that to work.

**Comment by verse316** [comment]
don't forget import as below (that was my issue, hopefully this gets fixed)

`import * as SQLite from 'expo-sqlite'`

**Comment by mcfliermeyer** [comment]
> don't forget to import as below (that was my issue, hopefully this gets fixed)
> 
> `import * as SQLite from 'expo-sqlite'`

that was my issue as well. thank you

**Comment by cmcnicholas** [comment]
are you guys still using this workaround? I'm on latest version of expo and expo-sqlite and typeorm isn't playing ball, I get:

```
ExpoDriver.js:63 Uncaught (in promise) TypeError: Illegal invocation
    at ExpoDriver.js:63
    at new Promise (<anonymous>)
    at ExpoDriver.../node_modules/typeorm/browser/driver/expo/ExpoDriver.js.ExpoDriver.createDatabaseConnection (ExpoDriver.js:61)
    at ExpoDriver.<anonymous> (AbstractSqliteDriver.js:130)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at tslib.es6.js:73
    at new Promise (<anonymous>)
    at Module.__awaiter (tslib.es6.js:69)
    at ExpoDriver.../node_modules/typeorm/browser/driver/sqlite-abstract/AbstractSqliteDriver.js.AbstractSqliteDriver.connect (AbstractSqliteDriver.js:124)
    at Connection.<anonymous> (Connection.js:109)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at tslib.es6.js:73
    at new Promise (<anonymous>)
    at Module.__awaiter (tslib.es6.js:69)
    at Connection.../node_modules/typeorm/browser/connection/Connection.js.Connection.connect (Connection.js:101)
    at CustomerDatabase.getConnection$ (CustomerDatabase.ts:10)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:145
```

I can see this particular line gets called when debugging but haven't dove any further https://github.com/typeorm/typeorm/blob/master/src/driver/expo/ExpoDriver.ts#L75

**Comment by FottyM** [comment]
> are you guys still using this workaround? I'm on latest version of expo and expo-sqlite and typeorm isn't playing ball, I get:
> 
> ```
> ExpoDriver.js:63 Uncaught (in promise) TypeError: Illegal invocation
>     at ExpoDriver.js:63
>     at new Promise (<anonymous>)
>     at ExpoDriver.../node_modules/typeorm/browser/driver/expo/ExpoDriver.js.ExpoDriver.createDatabaseConnection (ExpoDriver.js:61)
>     at ExpoDriver.<anonymous> (AbstractSqliteDriver.js:130)
>     at step (tslib.es6.js:99)
>     at Object.next (tslib.es6.js:80)
>     at tslib.es6.js:73
>     at new Promise (<anonymous>)
>     at Module.__awaiter (tslib.es6.js:69)
>     at ExpoDriver.../node_modules/typeorm/browser/driver/sqlite-abstract/AbstractSqliteDriver.js.AbstractSqliteDriver.connect (AbstractSqliteDriver.js:124)
>     at Connection.<anonymous> (Connection.js:109)
>     at step (tslib.es6.js:99)
>     at Object.next (tslib.es6.js:80)
>     at tslib.es6.js:73
>     at new Promise (<anonymous>)
>     at Module.__awaiter (tslib.es6.js:69)
>     at Connection.../node_modules/typeorm/browser/connection/Connection.js.Connection.connect (Connection.js:101)
>     at CustomerDatabase.getConnection$ (CustomerDatabase.ts:10)
>     at tryCatch (runtime.js:45)
>     at Generator.invoke [as _invoke] (runtime.js:271)
>     at Generator.prototype.<computed> [as next] (runtime.js:97)
>     at tryCatch (runtime.js:45)
>     at invoke (runtime.js:135)
>     at runtime.js:145
> ```
> 
> I can see this particular line gets called when debugging but haven't dove any further https://github.com/typeorm/typeorm/blob/master/src/driver/expo/ExpoDriver.ts#L75

I did use that workaround some few days ago

**Comment by cmcnicholas** [comment]
I will try a clean project with simple example to see if I'm missing something but my config looks identical except running v36 sdk

**Comment by cmcnicholas** [comment]
still no cigar here: bare minimum example https://github.com/cmcnicholas/expotypeorm
