### ISSUE TITLE
Closure table getting wrong value

### ISSUE THREAD

**Issue by PierreDemailly** [typeorm/typeorm#4847]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `mysql` / `mariadb`

**TypeORM version:**

[x] `^0.3.0-alpha.23` 

**Steps to reproduce or a small repository showing the problem:**

I have a Category entity with closure:
```
@Entity()
@Tree("closure-table")
export class Category {
  ...

  @TreeChildren()
  childrens: Category[];

  @TreeParent()
  parent: Category;
}
```

When I try to persist a new category with parent, for example:
```
{ 
  name: 'NAME 4',
  description: 'DESCRIPTION 4',
  parent: {
     id: 3,
     name: 'NAME 3',
     description: 'DESCRIPTION 3',
  }, 
}
```

I persist this way:
```
static create = async (req: Request, res: Response) => {
  const categoryRepository = getRepository(Category);
  const category = req.body as Category;
  const errors = await validate(category);

  if (errors.length > 0) {
    res.status(400).json({ error: errors });
    return;
  }

  try {
    categoryRepository.save(category);
    res.status(201).send();
  } catch (e) {
    res.status(404).json({ errror: e });
  }
}
```

In the category table, the ```parentId``` column is good (3, from the example)
The closure table is wrong.
I get 2 records :
```
id_ancestor = 3 | id_descendant = 4
id_ancestor = 4 | id_descendant = 4
(4 is the id of the persisted category in the above example)
```

So when i'm trying to get ancestors with treeRepository I get empty array everytime. I even tryed to remove the 4|4 row, not working. I'm not able to get parent with ```getTreeRepository(Category).findAncestors(categoryId) ```

Am I missing something ? Thanks

**Comment by PierreDemailly** [comment]
updated to ```^0.2.19```made it works. Soz

**Comment by Digital-Prestige** [comment]
tried version ^0.2.19 and it's not working well`
