### ISSUE TITLE
JoinColumn on multiple columns does not find column on referenced entity

### ISSUE THREAD

**Issue by brokenthorn** [typeorm/typeorm#4850]
_Originally posted by @brokenthorn in https://github.com/typeorm/typeorm/issues/2099#issuecomment-537617168_:

Seems to not be working again?

```ts
// Product.ts
@Entity()
export default class Product extends BaseEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ length: 255 })
  name!: string;

  @ManyToOne(() => Company, { primary: true })
  producer!: Company;

  @CreateDateColumn()
  createdDate!: Date;

  @UpdateDateColumn()
  updatedDate!: Date;
}
```

```ts
// ProductVarant.ts
@Entity()
export default class ProductVariant extends BaseEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ length: 255 })
  name!: string;

  @ManyToOne(() => Product)
  @JoinColumn([
    { name: "productId", referencedColumnName: "id" },
    { name: "producerId", referencedColumnName: "producerId" },
  ])
  product!: Product;
}
```

### Output:

```sh
[INFO] 21:09:02 Restarting: manual restart from user
Using ts-node version 8.4.1, typescript version 3.6.3
Application starting...
INFO: No classes were found using the provided glob pattern:  "src/subscriber/*.*"
INFO: All classes found using provided glob pattern "src/entity/*.*" : "src/entity/Company.ts,src/entity/Product.ts,src/entity/ProductVariant.ts,src/entity/User.ts"
Referenced column producerId was not found in entity Product
```

### Actual DB:

```sh
pcs-store=# \d+
Did not find any relations.
pcs-store=# \dt
Did not find any relations.
```

### Versions:

```sh
$ npm list --depth 0
+-- pg@7.12.1
+-- reflect-metadata@0.1.13
+-- typeorm@0.2.19
`-- typescript@3.6.3
```

**Comment by brokenthorn** [comment]
I think I fixed my own issue. It really didn't make sense to me but this:

```sql
CREATE TABLE books (
  id SERIAL PRIMARY KEY
)
```

does not create a `UNIQUE` constraint on the primary key column, it only creates an `int` column with a default value of the next value from a PostgreSQL `sequence`.

PostgreSQL documentation actually says this:

> The data types smallserial, serial and bigserial are not true types, but merely a notational convenience for creating **unique** identifier columns (similar to the AUTO_INCREMENT property supported by some other databases).

The word **unique** is what threw me off. Of course, reading further in the documentation, the fact becomes apparent that `id` would not be guaranteed to be unique, from the equivalent code that would be run from specifying a column as type `serial`:

```sql
CREATE SEQUENCE tablename_colname_seq;
CREATE TABLE tablename (
    colname integer NOT NULL DEFAULT nextval('tablename_colname_seq')
);
ALTER SEQUENCE tablename_colname_seq OWNED BY tablename.colname;
```

So I fixed it by specifying a new unique index:

```ts
@Entity()
@Unique(["id"])
export default class Product extends BaseEntity {
// ...
}
```

My bad for not reading the whole documentation.

Might I request that a `unique` property be added to [`PrimaryGeneratedColumnNumericOptions`](https://github.com/typeorm/typeorm/blob/a4dec02cc59d3219a29c7be0322af2253e1452dc/src/decorator/options/PrimaryGeneratedColumnNumericOptions.ts#L6) to make this easier?

**Comment by dbatistat** [comment]
ping

we have the same problem, but in a relation OneToOne

**Comment by OhadTutay** [comment]
Did anyone here succeed in solving this?

**Comment by sebs** [comment]
Same problem with Many to Many.

**Comment by dilame** [comment]
Same here, @pleerock pleease!

**Comment by piotr-pawlowski** [comment]
@dilame @brokenthorn 
You have to define producerId explicity:

`// Product.ts
@Entity()
export default class Product extends BaseEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ length: 255 })
  name!: string;
 
  @Column({ nullable: false })
  producerId: number

  @ManyToOne(() => Company, { primary: true })
  producer!: Company;

  @CreateDateColumn()
  createdDate!: Date;

  @UpdateDateColumn()
  updatedDate!: Date;
}`

**Comment by vegerot** [comment]
@piotr-pawlowski is this a workaround, or how it should be?

**Comment by piotr-pawlowski** [comment]
> @piotr-pawlowski is this a workaround, or how it should be?

It's not a workaround: https://typeorm.io/#/relations-faq/how-to-use-relation-id-without-joining-relation

**Comment by evindunn** [comment]
I ran into this when by member variable names were different than the database column names:
```
@Column("int", {
    primary: true,
    name: "cid",
    unsigned: true,
    default: () => "'0'",
})
characteristicID: number;

@Column("varchar", { primary: true, name: "cs", length: 16 })
characterStateStr: string;
```

And solved it by using the member name, not the database name:
```
@ManyToOne(() => CharacterState, (kmcs) => kmcs.characterStateImages, {
    onDelete: "CASCADE",
    onUpdate: "CASCADE",
})
@JoinColumn([
    { name: "cid", referencedColumnName: "characteristicID"},
    { name: "cs", referencedColumnName: "characterStateStr" },
])
characterState: CharacterState;
```

**Comment by Pruiz05** [comment]
I have one table with multiple primary columns:

and I just use de referenced colum

```ts

  @JoinColumn({ name: 'AGREEMENT_ID', referencedColumnName: 'ID' })
  @JoinColumn({ name: 'SECUENCE', referencedColumnName: 'SECUENCE' })
  agreement: Agreement
```
