### ISSUE TITLE
Query a simple-array column for item inclusion within another array.

### ISSUE THREAD

**Issue by DannyMcwaves** [typeorm/typeorm#4853]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi!

I'm using your library and am very much in love with it but I have a question(small problem).

So, I have a sample `Profile` Entity that looks similar to the one provided below.  

```javascript
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column } from "typeorm";

@Entity("profiles")
export class Profile extends BaseEntity {

  /**
   * Basic profile information
   */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column("uuid")
  userId: string;

  /**
   * Outdoor sports & activities
   */
  @Column("simple-array", { default: "" })
  outdoors: string[];

  @Column("simple-array", { default: "" })
  indoors: string[];

  @Column("simple-array", { default: "" })
  values: string[];

}
```

My problem, I'm trying to come up with a query for the `simple-array` Columns to check for a possible inclusion of at least one item within another array.

for instance, the `outdoors` Column, which is a simple-array, should contain at least one item within another array. Take a look at the query below:

```javascript
let profQuery = Profile
    .getRepository()
    .createQueryBuilder("profile")
    .where("profile.userId IN (:...userId)", { userId: user.coHostIds })
    .andWhere("profile.gender = :gender", { gender })
    .andWhere("profile.userId NOT IN (:...ids)", { ids: ids.length ? ids : [session.userId]  })
    .andWhere("LOWER(profile.username) LIKE LOWER(:username)", {username: `%${searchData.name}%`})
    .andWhere("LOWER(profile.city) LIKE LOWER(:city)", {city: `%${ searchData.city === 'All' ? '' : searchData.city }%` })
    .andWhere("profile.age BETWEEN :minAge AND :maxAge", {minAge: searchData.age[0], maxAge: searchData.age[1]})
    .andWhere("profile.height BETWEEN :minHeight AND :maxHeight", {minHeight: searchData.height[0], maxHeight: searchData.height[1]});

if(searchData.outDoorActivities && searchData.outDoorActivities.length)
   profQuery = profQuery.andWhere("profile.outdoors IN (:...outdoors)", {outdoors: searchData.outDoorActivities })
```

In this case, `searchData.outDoorActivities` is an `array` and `profile.outdoors` is also an array(simple-array).

The expected result should be a list of profiles where the `outdoor` field contains at least one value within `searchData.outDoorActivities`.
However, even if that exists, the query returns an empty array.
I'm very positive that the problem is not with the top part of the query as that returns data when you comment out the "array inclusion" search part.

Perhaps I'm doing something wrong and I'd appreciate any help on this.

Thanks.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
You won't be able to check it using `IN` operator. `simple-array` is internal type that is mapped to the underlying VARCHAR type. Let's say you are storing [a,b,c] in the database. In the db this data will look like "a,b,c" and when you do IN ("a", "b") it will be equal to if "a,b,c" === "a" OR "a,b,c" === "b" in the database lookup and both expressions will result to false and returning you nothing. 

You either should use real array types (its possible since you are using postgres), either you should filter your data manually (using javascript map/filter functions) after you fetch the data from the db.

**Comment by DannyMcwaves** [comment]
```javascript
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column } from "typeorm";

@Entity("profiles")
export class Profile extends BaseEntity {

  /**
   * Basic profile information
   */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column("uuid")
  userId: string;

  /**
   * Outdoor sports & activities
   */
  @Column("text", { array: true })
  outdoors: string[];

  @Column("text", { array: true })
  indoors: string[];

  @Column("array", { true: true })
  values: string[];
}
```

The query for the array inclusion then becomes;
```javascript
let profQuery = Profile
    .getRepository()
    .createQueryBuilder("profile")
    .where("profile.userId IN (:...userId)", { userId: user.coHostIds })
    .andWhere("profile.gender = :gender", { gender })
    .andWhere("profile.userId NOT IN (:...ids)", { ids: ids.length ? ids : [session.userId]  })
    .andWhere("LOWER(profile.username) LIKE LOWER(:username)", {username: `%${searchData.name}%`})
    .andWhere("LOWER(profile.city) LIKE LOWER(:city)", {city: `%${ searchData.city === 'All' ? '' : searchData.city }%` })
    .andWhere("profile.age BETWEEN :minAge AND :maxAge", {minAge: searchData.age[0], maxAge: searchData.age[1]})
    .andWhere("profile.height BETWEEN :minHeight AND :maxHeight", {minHeight: searchData.height[0], maxHeight: searchData.height[1]});
    .andWhere("profile.outdoors::text[] @> (:activities)::text[] AND profile.indoors::text[] @> (:indoors)::text[] AND profile.values::text[] @> (:values)::text[]", { activities: searchData.outDoorActivities, indoors: searchData.inDoorActivities, values: searchData.values });
```

**Comment by plopezm** [comment]
My solution for Postgres is as follows:

```
this.getFindQueryBuilder().where("recipe.tags && ARRAY[:...tags]", {tags: tags})
```
"getFindQueryBuilder": Is a function to get shared SelectQueryBuilder in order to save code.

The important part here is the where clause that I have shown in the example.

**Comment by kallol24** [comment]
@plopezm @DannyMcwaves I get error 'operator does not exist: text @> text[]'

**Comment by apurvayaar** [comment]
Is there a solution for this yet?

**Comment by jovsz** [comment]
> @plopezm @DannyMcwaves I get error 'operator does not exist: text @> text[]'

this work for me: 
.where("recipe.tags && ARRAY[:...tags]", {tags: [tags]})

**Comment by flchaux** [comment]
I created an operator to be used in the FindOptions where to compare an array and a simple-array column.
```
import { Raw } from "typeorm";

/**
 * a typeorm operator that checks if at least one string from an array is in a simple-array column.
 * simple-array column is a column that is stored as a string array in the database.
 */
export const ArrayIn = (array: string[] | undefined) =>
    array && array.length > 0 ? Raw((alias) => `string_to_array(${alias}, ',') && ARRAY[:...array]`, { array }) : undefined;
```

**Comment by aman1205** [comment]
@Column('simple-array')
  options: string[];
  
  Is there a way to fix the length of the array like  @Column('simple-array).lenth(4)

**Comment by hmh6a** [comment]
Try this ...
```ts
const data = await this.repository.createQueryBuilder('repository')
  .where(`:color = ANY(string_to_array(repository.colors, ','))`, { color: 'red' })
  .getOne();
```
