### ISSUE TITLE
Can TypeORM parse denormalized data like a one-to-many?

### ISSUE THREAD

**Issue by tncbbthositg** [typeorm/typeorm#4856]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18`

I have a datasource that I don't control and cannot change that's in a denormalized format.  I need to parse these data into a normalized object graph.  Interestingly, the data are stored in the same shape they would be if they were normalized and joined together.

I'd like to tell TypeORM to parse these data exactly as it would if the ORM had built the query.

For example, consider these data:
```
userId | userName | photoUrl | photoCaption
-------------------------------------------
1      | Lu       | <url1>   | photo 1
1      | Lu       | <url2>   | photo 2
2      | Pat      | <url3>   | photo 3
2      | Pat      | <url4>   | photo 4
```

I'd like to get an object graph shaped like this:
```
[
  {
    userId: 1, userName: 'Lu', 
    photos: [
      { photoUrl: <url1>, photoCaption: 'photo 1' },
      { photoUrl: <url2>, photoCaption: 'photo 2' }
    ]
  },
  {
    userId: 2, userName: 'Pat', 
    photos: [
      { photoUrl: <url3>, photoCaption: 'photo 3' },
      { photoUrl: <url4>, photoCaption: 'photo 4' }
    ]
  }
]
```

If my data were normalized, this would be a trivial one to many:
```
id | userName 
------------------
1      | Lu       
2      | Pat      


userId | photoUrl | photoCaption
-------------------------------------------
1      | <url1>   | photo 1
1      | <url2>   | photo 2
2      | <url3>   | photo 3
2      | <url4>   | photo 4
```

The funny thing is that the query produced would be roughly:
```
SELECT users.*, photos.*
FROM users
LEFT JOIN photos
  ON users.id = photos.userId;
```

Which produces the same data structure I have physically stored in my table.

Is there a way to get TypeORM to parse these data into the parent child structure as though it had generated the query itself?

Something like this:
```
@Entity()
class Photo extends BaseEntity {
  @PrimaryColumn() photoId!: number;
  @Column() photoUrl!: string;
  @Column() photoCaption!: string;
}

@Entity()
class UserPhotos extends BaseEntity {
  @PrimaryColumn() id!: number;
  @Column() userName!: string;

  @SomethingMagicalAndWonderful()
  photos: Photo[]
}
```

Or maybe using `OneToMany` but having some tricky configuration that indicates it's not really a join?

**Comment by humodz** [comment]
From glancing at SelecQueryBuilder.ts I'd guess no. The logic in SelecQueryBuilder.executeEntitiesAndRawResults that maps the raw result to the entities seems to heavily assume that the tables actually exist.

**Comment by imnotjames** [comment]
The closest you'll get is an embedded entity.

You'll need to process the rest yourself.
