### ISSUE TITLE
get effected rows as orm entity after update query

### ISSUE THREAD

**Issue by oyakovVonage** [typeorm/typeorm#4857]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16` (or put your version here)

Can I update a table and get the updated rows as orm entity in one query?
I tried to use returning('*') but it returns me the effected rows in original DB format and not as orm entity.

The query I tried:
```
			await this.conn
				.getRepository(User)
				.createQueryBuilder()
				.update()
				.where({ accountID, id: userID })
				.set(user)
				.returning('*')
				.execute();
```

**Comment by imnotjames** [comment]
They get returned as an `UpdateResult`.  For performance reasons we don't create entities from that.
