### ISSUE TITLE
Disable "AS" statements.

### ISSUE THREAD

**Issue by wintertime-inc** [typeorm/typeorm#4862]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```ts
import { Column, Entity, PrimaryColumn } from 'typeorm';

@Entity({
    name: 'roles'
})
export class Roles {

    @PrimaryColumn({
        name: "roleId"
    })
    roleId: number;

    @Column({
        name: "roleLabel"
    })
    roleLabel: string;

    @Column({
        name: "roleCategory"
    })
    roleCategory: string;

    @Column({
        name: "roleKey"
    })
    roleKey: string;

    @Column({
        name: "roleType"
    })
    roleType: string;

}

```

Is there any way to disable "AS" statements that are produced into DB?
I trough adding Entity, PrimaryColumn, Column, options of { name: 'Column name'} will fix the problem, however during debug mode the "AS" statements are still produced, is there any chance to remove those statements and force TypeORM to use declared names e.g. "Roles"."roleId".

The problem is that once you have a lot of relations e.g. 4-6 joins or more complicated queries, and something isn't clear, with those "AS" it is a way more difficult to debug/reproduce it in simple SQL in my opinion.

Any chance to disable it? Or this is built-in and this is how this ORM works?

Example debug:
`SELECT "Roles"."roleId" AS "Roles_roleId", "Roles"."roleLabel" AS "Roles_roleLabel", "Roles"."roleCategory" AS "Roles_roleCategory", "Roles"."roleKey" AS "Roles_roleKey", "Roles"."roleType" AS "Roles_roleType" FROM "roles" "Roles"`

**Comment by imnotjames** [comment]
TypeORM uses this to enable the mapping as needed.

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
