### ISSUE TITLE
Can custom names be given to relation columns in table created from a @Many-to-many relationship?

### ISSUE THREAD

**Issue by charliemc** [typeorm/typeorm#4863]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Given the following two entities that have a `@ManyToMany` relationship:

```ts
@Entity({ name: 'products' })
export class ProductEntity {
  @PrimaryColumn()
  id: number;

  @Column()
  name: string;

  @ManyToMany(type => CategoryEntity, { eager: true })
  @JoinTable({ name: 'products_categories' })
  categories: CategoryEntity[];
}
```

```ts
@Entity({ name: 'categories' })
export class CategoryEntity {
  @PrimaryColumn({ length: 40 })
  code: string;
}
```

As a result I get created a table called `"products_categories"` (as expected) with the following column names:

- `productsId` 
- `categoriesCode`

Is there a way of giving these two columns custom names? I would like to rename them as follows without renaming the _products_ and _categories_ table name:

- `productsId` -> `productId`
- `categoriesCode` -> `categoryCode`

**Comment by tphbrok** [comment]
You can rename columns of a join table by extending the options object given to `@JoinTable`, as easily found in the [TypeORM docs](https://github.com/typeorm/typeorm/blob/master/docs/relations.md#jointable-options):

```ts
@ManyToMany(type => Category)
@JoinTable({
    name: "question_categories", // table name for the junction table of this relation
    joinColumn: {
        name: "question",
        referencedColumnName: "id"
    },
    inverseJoinColumn: {
        name: "category",
        referencedColumnName: "id"
    }
})
categories: Category[];
```

**Comment by charliemc** [comment]
Thank you very much @tphbrok, looked for that on the docs but I missed it! 🙏🙏🙏

**Comment by michaelmontero** [comment]
This issue should be closes @charliemc.
