### ISSUE TITLE
Select does not work as I expected - all properties are in reponse

### ISSUE THREAD

**Issue by mirekuhlir** [typeorm/typeorm#4864]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi,
I have this query 
 ```javascript 
const productInstance = await this.entityManager
      .createQueryBuilder(ProductInstance, 'ProductInstance')
      .leftJoinAndSelect('ProductInstance.RentalItems', 'RentalItems')
      .where('ProductInstance.Id = :id', { id: id })
      .select([
        'ProductInstance.Id',
        'ProductInstance.Color',
        'RentalItems.Id',
        'RentalItems.Start',
        'RentalItems.End',
      ])
      .getOne();
```

which return this reponse 

```{
    "Id": 3008,
    "SerialNumber": "",
    "Color": "Silver",
    "AvailableForRent": true,
    "RequiresConditionRevision": 0,
    "Note": "",
    "IsBorrowed": 0,
    "Created": null,
    "CreatedBy": null,
    "Modified": null,
    "ModifiedBy": null,
    "RentalItems": [
        {
            "Id": 19868,
            "Phase": null,
            "Condition": null,
            "Start": "2019-10-07T00:00:00.000Z",
            "End": "2019-10-09T00:00:00.000Z”… 
```

I used select. All properties are in response. The key names remain here. Those that were not specified do not have values, such as serial number or note. I would like to receive only those properties that I defined in select. Without serial number, note etc.

If I use getRawOne instead of getOne, I only get those properties that I defined in select, but the structure of the rental items array is lost.

```
{
    "ProductInstance_Id": 3008,
    "ProductInstance_Color": "Silver",
    "RentalItems_Id": 19868,
    "RentalItems_Start": "2019-10-07T00:00:00.000Z",
    "RentalItems_End": "2019-10-09T00:00:00.000Z"
} 
```
I would like to receive a response where all the structure is preserved and there are only the values defined in select. Is it possible? Thanks.

**Comment by veluxa** [comment]
It could be the cause by use leftJoinAndSelect,try to use leftJoin

**Comment by imnotjames** [comment]
Looks like this has been answered.
