### ISSUE TITLE
TypeORM becomes unresponsive after this code is run 10x

### ISSUE THREAD

**Issue by bengotow** [typeorm/typeorm#4866]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.16` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hey! Ok - so I've finally narrowed this issue down to a reproducible case. I'm building an express application and one of my routes does this:

```

router.get('/testtest', async (req, res) => {
  const db = await dbconnection;
  const runner = db.createQueryRunner();
  await runner.startTransaction();
  // queries
  await runner.commitTransaction();
  return res.json({ success: true });
});
```

After running this 10x, (presumably the size of the default connection pool), TypeORM stops responding to all queries. On the 11th run, this code awaits forever and other code which uses `Model.findOne()`, etc. also locks.

**Comment by bengotow** [comment]
Edit: After reading the docs more carefully, it turns out I was missing a call to `runner.release()` and this behavior was entirely appropriate!

If anyone comes across this, I think I'm going to wrap my code into a function like this that binds the runner to a nested scope, ensuring it is not possible to forget the release. It's hard to identify that this is a problem in development because it doesn't cause issues until the 10th execution.

```
async function inTransaction(cb: (runner: QueryRunner) => void) {
  const db = await dbconnection;
  const runner = db.createQueryRunner();
  await runner.startTransaction();
  try {
    cb(runner);
    await runner.commitTransaction();
  } catch (err) {
    await runner.rollbackTransaction();
  } finally {
    runner.release();
  }
}
```

**Comment by rmmo1975** [comment]
It helped me a lot mate! Thanks!

**Comment by denes16** [comment]
Im facing the same issue. Im using nestjs/mysql, im running a trasaction, but afer 8,9 o 10 request becomes unresponsive.
Im releasing the query runner too.

**Comment by denes16** [comment]
My code looks like this
```
async create(
    createChatMessageDto: CreateChatMessageDto,
    currentUser: CurrentUser,
    file?: UploadedS3File,
  ) {
    const queryRunner = this.connection.createQueryRunner();
    await queryRunner.connect();
    await queryRunner.startTransaction();
    try {
...someCode
await queryRunner.commitTransaction();
await queryRunner.release();
// send reponse to user
} catch (error) {
      await queryRunner.rollbackTransaction();
      await queryRunner.release();
      throw error;
    }
}
```
