### ISSUE TITLE
URL Connection string not overridden by supplied options

### ISSUE THREAD

**Issue by ryanmr** [typeorm/typeorm#4878]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

From the docs:

> url - Connection url where perform connection to. Please note that other connection options will override parameters set from url.

In my particular situation, I pass `url` for host, port, database, etc in the TypeORM options but supply username and password directly.

```ts
    TypeOrmModule.forRoot({
      type: 'mysql',
      url: DB_CONNECTION, // CONNECTION STRING
      // for example: mysql://localhost:3306/dev
      username: DB_USERNAME, // abc
      password: DB_PASSWORD, // abc
      database: 'dev',
      entities: ['src/**/**.entity{.ts,.js}'],
    }),
```

The _username_ and _password_ are not set in the given connection string, and based on the documentation, the two values should have priority from the options vs the unspecified values in the connection string url.

It seems like [this could be reversed](https://github.com/typeorm/typeorm/blob/358e8a1a4872a950b471835cb48ff2bbc74cf6ce/src/driver/DriverUtils.ts#L31) and this would work as documented.

```ts
return Object.assign({}, options, urlDriverOptions);
```

```
// before
{
  type: 'mysql',
  url: 'mysql://localhost:3306/dev',
  username: '',
  password: '',
  database: 'dev',
  entities: [ 'src/**/**.entity{.ts,.js}' ],
  host: 'localhost',
  port: 3306
}

// after
{
  type: 'mysql',
  url: 'mysql://localhost:3306/dev',
  username: 'abc',
  password: 'abc',
  database: 'dev',
  entities: [ 'src/**/**.entity{.ts,.js}' ],
  host: 'localhost',
  port: 3306
}
```

Another solution I think, may be to [enhance the current parsing](https://github.com/typeorm/typeorm/blob/488d21090aadb52c88dc9b5f66302f68aea97d95/src/driver/DriverUtils.ts#L90) and switching the order of the order object assign.

Thanks for the consideration.

**Comment by Redmega** [comment]
This was the cause of such confusion for me as I took the documentation at face value.

https://github.com/typeorm/typeorm/blob/defa9bced0b5d1258e4f50d5c590978e6d3324d3/src/driver/DriverUtils.ts#L31

Indeed, this needs to be reversed.
