### ISSUE TITLE
Assigning new one2one relation fails

### ISSUE THREAD

**Issue by Tobias4872** [typeorm/typeorm#488]
Hi,

I have a model "zone" which is connected to a model "specification" on a one2one relationship.

```javascript
export class Zone {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column({
        length: 128,
    })
    public name: string;

    @OneToOne((type) => Specification, (ps) => ps.zone, {
        cascadeAll: true,
        onDelete: "CASCADE",
    })
    @JoinColumn()
    public specification: Specification;
}
```

```javascript
@Table()
export class Specification {

    @PrimaryGeneratedColumn()
    public id: number;

    @Column({
        length: 128,
    })
    public name: string;

    @OneToOne((type) => Zone, (zone) => zone.specification)
    public zone: Zone;

}
```

When I create a new zone with a specification, it properly inserts two data items into the database and connects the two accordingly:

```javascript
    const z1 = await zoneRepo.persist({
        name: "Zone 1",
        specification: {
            name: "Spec 1",
        },
    } as Zone);
```

Debug output is:

```
executing query: INSERT INTO zone(name) VALUES (?) -- PARAMETERS: ["Zone 1"]
executing query: INSERT INTO specification(name) VALUES (?) -- PARAMETERS: ["Spec 1"]
executing query: UPDATE zone SET specification=?  WHERE id=? -- PARAMETERS: [8,5]
```

When I remove the specification from the zone, it properly disconnects the two and deletes the specification as it is not needed anymore:

```javascript
    z1.specification = null;
    await zoneRepo.persist(z1);
```

Debug output is:

```
executing query: UPDATE zone SET specification=?  WHERE id=? -- PARAMETERS: [null,5]
executing query: DELETE FROM specification WHERE id=? -- PARAMETERS: [8]
```

But when I now try to set a new specification, it inserts the new specification into the database, but fails to connect the two:

```javascript
    z1.specification = {
        name: "Spec 2",
    } as Specification;
    await zoneRepo.persist(z1);
```

Debug output is:

```
executing query: INSERT INTO specification(name) VALUES (?) -- PARAMETERS: ["Spec 2"]
```

Am I missing something?

Thanks,
  Tobias.

**Comment by pleerock** [comment]
Looks like a bug

**Comment by netnexus** [comment]
Anything new on this topic?

**Comment by pleerock** [comment]
not yet, I quite busy with other tasks at the moment. I won't expect I can fix persistence next few month.

**Comment by pleerock** [comment]
Sorry for the delayed answer but this issue to be resolved required lot of efforts and refactorings. I have completely refactored persistence system and fixed all problems with cascades I have seen. Please try a new version (npm i typeorm@next) and let me know if your issue is not resolved in new versions too.
