### ISSUE TITLE
More FindOperators

### ISSUE THREAD

**Issue by BugsBunnyBR** [typeorm/typeorm#4881]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Right now I need to write raw sql to select a Date/DateTime/Timestamp that is from a given year.

Something like
```ts
this.createQueryBuilder('holiday')
            .where('deleted_at IS NULL AND YEAR(DATE(day))=:year', {
                year
            })
            .getMany();
```

It would be great if more date related FindOperators could exist... something like

```ts
           this.find( {
            where: {
                day: ofYear(year),
                deletedAt: IsNull()
            }
        });

```

// YEAR(date(day))=:year AND MONTH(date(day))=:month
```ts
           this.find( {
            where: {
                day: ofYear(year, ofMonth(month)),
                deletedAt: IsNull()
            }
        });

```

// YEAR(date(day))=:year AND MONTH(date(day))=:month AND DAYOFMONTH(date(day))=:day
```ts
           this.find( {
            where: {
                day: ofYear(year, ofMonth(month), ofDay(day)),
                deletedAt: IsNull()
            }
        });

```

Those are just some ideas... I am new to typeorm, but if there is a sample and the developers agree with this approach, maybe I can open some PRs?

Thanks.

**Comment by imnotjames** [comment]
`Raw` is available with parameters now so you can make your own custom FindOperators by wrappting the `Raw` one!
