### ISSUE TITLE
How to implement Pascal Case Naming Strategy (MSSQL)?

### ISSUE THREAD

**Issue by davidhenley** [typeorm/typeorm#4885]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am having an issue figuring out how to implement a naming strategy while avoiding duplicate column name errors.

Here is a sample of my entity:

```
@Column()
customerId: number;

@ManyToOne(type => Customer)
@JoinColumn({ name: 'customerId' })
customer: Customer;
```

**When I override the `tableName` and `columnName` methods to capitalize the table and columns I get an error that `customerId` is duplicated in the table. It's trying to add 2 columns.**

Which additional method(s) do I need to implement in order for this to work?

```
tableName(targetName: string, userSpecifiedName: string | undefined): string {
  return capitalize(userSpecifiedName ? userSpecifiedName : targetName);
}

columnName(propertyName: string, customName: string, embeddedPrefixes: string[]): string {
  return capitalize(customName ? customName : propertyName);
}
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
