### ISSUE TITLE
Feature Request - PaperTrail like logging?

### ISSUE THREAD

**Issue by dgobaud** [typeorm/typeorm#4886]
I really miss https://github.com/paper-trail-gem/paper_trail for Ruby on Rails ActiveRecord. Hugely helpful - does anything like that exist? If not would be a great feature!

**Comment by ernestdolog** [comment]
Indeed. Following.

**Comment by imnotjames** [comment]
This can be accomplished with subscribers.

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by dgobaud** [comment]
@imnotjames it can be done with subscribers but the idea is to have native support so maybe we just include a setting in an entity and everything is then logged automatically

**Comment by imnotjames** [comment]
That's really not something typeorm can or should do.  Something built on top of it, something reusable, would be a much more maintainable system than trying to include all of those complexities within.

Similar to paper trail.  It's not part of RoR core, it's built on top of Active record.

The scope of typeorm is already huge enough as is. :) I'd rather work on features to support something like paper trail where everyone can reuse the features than work on a bunch of features nobody else can use for one edge case product extension.

**Comment by imnotjames** [comment]
(if there are features missing to make that happen please open an issue requesting them!)

**Comment by arjunlol** [comment]
It looks like there's some libraries that are similar to PaperTrail for TypeORM like [typeorm-versions](https://github.com/frane/typeorm-versions) and [typorm-auditing](https://github.com/kibae/typeorm-auditing). 

We've also recently built [bemi](https://github.com/bemihq/typeorm) which takes a slightly different approach by integrating at the database level (more reliable and less performance overhead) and may be useful to you depending on what you were building.
