### ISSUE TITLE
@Unique decorator to check Email for uniqueness

### ISSUE THREAD

**Issue by ZuevR** [typeorm/typeorm#4888]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.19` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Please tell me. Can i use `@Unique` decorator to check the email field for uniqueness? And if so, how is this possible?

`User.ts`
```ts
import { Entity, PrimaryGeneratedColumn, Column, Unique } from "typeorm";
import { IsEmail, IsNotEmpty, Length } from "class-validator";

@Entity({ name: 'users' })
@Unique(['email'])
export class User {

  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  @Length(2, 30, { message: 'The name must be at least 2 but not longer than 30 characters' })
  @IsNotEmpty({ message: 'The name is required' })
  name!: string;

  @Column()
  @Length(6, 30, { message: 'The password must be at least 6 but not longer than 30 characters' })
  @IsNotEmpty({ message: 'The password is required' })
  password!: string;

  @Column({ name: 'email' })
  @IsEmail({}, { message: 'Incorrect email' })
  @IsNotEmpty({ message: 'The email is required' })
  email!: string;

  constructor(user: Partial<User>) {
    Object.assign(this, user);
  }

}
 ```
`AuthController.ts`
```ts
import { NextFunction, Request, Response } from 'express';
import { getManager } from 'typeorm';
import { User } from '../entities/User';
import { validate } from 'class-validator';


export class AuthController {

  public static async signUp(req: Request, res: Response, next: NextFunction) {
    const { name, email, password } = req.body;
    const user = new User({ name, email, password });
    const errors = await validate(user);
    console.log(errors);
    getManager().save(user).catch(e => {
      console.log(e);
    });
    res.send({test: 'test'});
  }
  
}
```

**Comment by leonardofalk** [comment]
You can use `@Column({ unique: true })`, that will add a SQL constraint.

**Comment by ZuevR** [comment]
Thanks for the answer. As far as I understand, this will introduce a condition into the database during synchronization, but it will not replace model-level validation. I decided to use other solutions in my project.

**Comment by J-Ibarra** [comment]
Hello, @ZuevR, I have the same issue, can you share you solution?

**Comment by angristan** [comment]
I'm interested too!

**Comment by J-Ibarra** [comment]
my solution whit `class-validation`
file: `UniqueValidation.ts`

```
import { registerDecorator, ValidationArguments, ValidationOptions, ValidatorConstraint, ValidatorConstraintInterface } from 'class-validator';
import { getManager } from 'typeorm';

@ValidatorConstraint({ async: true })
export class UniqueOnDatabaseExistConstraint implements ValidatorConstraintInterface {
  async validate(value: any, args: ValidationArguments) {
    const entity = args.object[`class_entity_${args.property}`];
    return getManager()
      .count(entity, { [args.property]: value })
      .then((count) => count < 1);
  }
}

export function UniqueOnDatabase(entity: Function, validationOptions?: ValidationOptions) {
  validationOptions = { ...{ message: '$value already exists. Choose another.' }, ...validationOptions };
  return function (object: Object, propertyName: string) {
    object[`class_entity_${propertyName}`] = entity;
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [],
      validator: UniqueOnDatabaseExistConstraint,
    });
  };
}
```

to Use

```
export class CustomerRegisterPayload {
  @IsNotEmpty()
  fullname: string;
  @IsEmail()
  @UniqueOnDatabase(Customer)
  email: string;
}
```

this works fine for me

**Comment by angristan** [comment]
Awesome! It works for me too. Thanks a lot.

**Comment by swapnilbanga** [comment]
@J-Ibarra your solution will work fine for creating records, but not for updating.

**Comment by J-Ibarra** [comment]
> @J-Ibarra your solution will work fine for creating records, but not for updating.

Ok, @swapnilbanga you can modify the logic to pass custom query, try this: 

 ```
import { registerDecorator, ValidationArguments, ValidationOptions, ValidatorConstraint, ValidatorConstraintInterface } from 'class-validator';
import { getManager } from 'typeorm';

@ValidatorConstraint({ async: true })
export class UniqueOnDatabaseExistConstraint implements ValidatorConstraintInterface {
  async validate(value: any, args: ValidationArguments) {
    const req = args.object['__req__'];
    const entity = args.object[`__entity__${args.property}__`];
    let query = args.object[`__query__${args.property}__`](req) || {};
    query = { [args.property]: value, ...query };
    return getManager()
      .count(entity, query)
      .then((count) => count < 1);
  }
}

export function UniqueOnDatabase(entity: Function, query = (req: any) => {}, validationOptions?: ValidationOptions) {
  validationOptions = { ...{ message: '$value already exists. Choose another.' }, ...validationOptions };
  return function (object: Object, propertyName: string) {
    object[`__entity__${propertyName}__`] = entity;
    object[`__query__${propertyName}__`] = query;
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [],
      validator: UniqueOnDatabaseExistConstraint,
    });
  };
}
```

```
import { Request } from 'express';
import { Not } from 'typeorm';
import { UniqueOnDatabase } from '../../../core/http';
import { Country } from '../../Entities/CountryEntity';

export class CountryPayload {
  @UniqueOnDatabase(Country, (req: Request) => (req.params.id ? { id: Not(req.params.id) } : {}))
  name: string;
  @UniqueOnDatabase(Country, (req: Request) => (req.params.id ? { id: Not(req.params.id) } : {}))
  countryCode: string;
  @UniqueOnDatabase(Country, (req: Request) => (req.params.id ? { id: Not(req.params.id) } : {}))
  phoneCode: string;
}
```
```
async function trimBodyAndValidate(body: any, validation?: any, req?: any) {
  const trimBody = (body: any) =>
    Array.isArray(body)
      ? body.map((object) => trimBody(object))
      : Object.keys(body).reduce((trimed, key) => {
          switch (typeof body[key]) {
            case 'string':
              if (key === 'password') trimed[key] = body[key];
              if (key !== 'password') trimed[key] = body[key].replace(/( )+/, ' ').trim();
              if (trimed[key].length < 1) trimed[key] = undefined;
              break;
            case 'object':
              trimed[key] = trimBody(body[key]);
              break;
            default:
              trimed[key] = body[key];
          }
          return trimed;
        }, {});

  const trimed = trimBody(body);

  return Bluebird.resolve(createClass(validation, trimed))
    .tap((toValidate) => (toValidate['__req__'] = req))
    .then((toValidate) => validate(toValidate))
    .then((errors) => (errors.length > 0 ? Bluebird.reject(createError(errors)) : trimed));
}
```
```
export const createClass = (target: any, values: any) => {
  const constructor = typeof target === 'function' ? target : target.constructor;
  return Object.assign(new constructor(), values);
};
```

**Comment by leosfont** [comment]
less verbose solution for updates.

`import { registerDecorator, ValidationArguments, ValidationOptions, ValidatorConstraint, ValidatorConstraintInterface } from 'class-validator'
import { getRepository, Not } from 'typeorm'

@ValidatorConstraint({ async: true })
export class UniqueOnDatabaseExistConstraint implements ValidatorConstraintInterface {
  async validate(value: any, args: ValidationArguments) {
    const entity = args.object[`class_entity_${args.property}`]
    const req_id = args.object['id'] || -1
    const items = await getRepository(entity).findAndCount({ [args.property]: value, id: Not(req_id) })
    return !items[1]
  }
}

export function UniqueOnDatabase(entity: Function, validationOptions?: ValidationOptions) {
  validationOptions = { ...{ message: '$value already exists. Choose another.' }, ...validationOptions }
  return function (object: Object, propertyName: string) {
    object[`class_entity_${propertyName}`] = entity
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [],
      validator: UniqueOnDatabaseExistConstraint,
    })
  }
}`

**Comment by bc05** [comment]
how get param from request in dto? @J-Ibarra

**Comment by J-Ibarra** [comment]
@bc05 

this its my DTO,  in @UniqueOnDatabase you can send the query `(req: Request) => (req.params.id ? { id: Not(req.params.id) } : {}`

```
import { Request } from 'express';
import { Not } from 'typeorm';
import { UniqueOnDatabase } from '../../../core/http';
import { Country } from '../../Entities/CountryEntity';

export class CountryPayload {
  @UniqueOnDatabase(Country, (req: Request) => (req.params.id ? { id: Not(req.params.id) } : {}))
  name: string;
  @UniqueOnDatabase(Country, (req: Request) => (req.params.id ? { id: Not(req.params.id) } : {}))
  countryCode: string;
  @UniqueOnDatabase(Country, (req: Request) => (req.params.id ? { id: Not(req.params.id) } : {}))
  phoneCode: string;
}
```

in the controller you can create instance class, assign params, assign request in toValidate instance param and call validate from class validator

```
const toValidate = Object.assign(new CountryPayload(), request.body);
toValidate['__req__'] = request;
const errors = validate(toValidate);
```

import { registerDecorator, ValidationArguments, ValidationOptions, ValidatorConstraint, ValidatorConstraintInterface } from 'class-validator';
import { getManager } from 'typeorm';

and use the Custom Validator Constraint

```
@ValidatorConstraint({ async: true })
export class UniqueOnDatabaseExistConstraint implements ValidatorConstraintInterface {
 async validate(value: any, args: ValidationArguments) {
   const req = args.object['__req__'];
   const entity = args.object[`__entity__${args.property}__`];
   let query = args.object[`__query__${args.property}__`](req) || {};
   query = { [args.property]: value, ...query };
   return getManager()
     .count(entity, query)
     .then((count) => count < 1);
 }
}

export function UniqueOnDatabase(entity: Function, query = (req: any) => {}, validationOptions?: ValidationOptions) {
 validationOptions = { ...{ message: '$value already exists. Choose another.' }, ...validationOptions };
 return function (object: Object, propertyName: string) {
   object[`__entity__${propertyName}__`] = entity;
   object[`__query__${propertyName}__`] = query;
   registerDecorator({
     target: object.constructor,
     propertyName: propertyName,
     options: validationOptions,
     constraints: [],
     validator: UniqueOnDatabaseExistConstraint,
   });
 };
}
```

**Comment by SamTomashi** [comment]
I am getting this error:

`EntityMetadataNotFoundError: No metadata for "undefined" was found`

What could be the issue?

**Comment by kasper334** [comment]
@SamTomashi not sure if relevant, but in my case the `PartialType` helper caused `No repository for "undefined" was found` issue.

I have 2 DTOs:

`create-project.dto.ts`
```ts
import { IsNotEmpty, IsString, Length } from 'class-validator';
import { DatabaseUnique } from '../../../decorators/database/unique.decorator';
import { Project } from '../project.entity';

export class CreateProjectDto {
  @IsNotEmpty()
  @IsString()
  @Length(1, 255)
  @DatabaseUnique(Project)
  name: string;
}
```
`update-project.dto.ts`
```ts
import { PartialType } from '@nestjs/mapped-types';
import { CreateProjectDto } from './create-project.dto';

export class UpdateProjectDto extends PartialType(CreateProjectDto) {}
```

As for `CreateProjectDto` - it worked perfectly, but when I called `PATCH` method (which uses `UpdateProjectDto`) - it failed with error `No repository for "undefined" was found`.
Searching online showed that [class-validator does not support generics](https://stackoverflow.com/a/64401153).

So the fix, unfortunately, would be either extending `CreateProjectDto` directly without using `PartialType` (and overriding properties manually with `IsOptional` decorator), or writing fully custom DTO without extending.
Would be happy if someone proves me wrong.

So my final `update-project.dto.ts` looks like this:
```ts
import { IsOptional } from 'class-validator';
import { CreateProjectDto } from './create-project.dto';

export class UpdateProjectDto extends CreateProjectDto {
  @IsOptional()
  name: string;
}
```

**Comment by kodunmi** [comment]
> less verbose solution for updates.
> 
> ```
> import { registerDecorator, ValidationArguments, ValidationOptions, ValidatorConstraint, ValidatorConstraintInterface } from 'class-validator'
> import { getRepository, Not } from 'typeorm'
> 
> @ValidatorConstraint({ async: true })
> export class UniqueOnDatabaseExistConstraint implements ValidatorConstraintInterface {
>   async validate(value: any, args: ValidationArguments) {
>     const entity = args.object[`class_entity_${args.property}`]
>     const req_id = args.object['id'] || -1
>     const items = await getRepository(entity).findAndCount({ [args.property]: value, id: Not(req_id) })
>     return !items[1]
>   }
> }
> 
> export function UniqueOnDatabase(entity: Function, validationOptions?: ValidationOptions) {
>   validationOptions = { ...{ message: '$value already exists. Choose another.' }, ...validationOptions }
>   return function (object: Object, propertyName: string) {
>     object[`class_entity_${propertyName}`] = entity
>     registerDecorator({
>       target: object.constructor,
>       propertyName: propertyName,
>       options: validationOptions,
>       constraints: [],
>       validator: UniqueOnDatabaseExistConstraint,
>     })
>   }
> }
> ```
> 
> send the id to be validated together

Please can you help modify this for TS ?
And getManager() is depreciated

**Comment by yxqme** [comment]
here is my new solution

add a file name `is-unique.ts` Custom validation decorators

```ts
import { Injectable } from '@nestjs/common';
import {
  registerDecorator,
  ValidationArguments,
  ValidationOptions,
  ValidatorConstraint,
  ValidatorConstraintInterface,
} from 'class-validator';
import { DataSource } from 'typeorm';

@ValidatorConstraint({ name: 'isUnique', async: true })
@Injectable()
export class IsUniqueConstraint implements ValidatorConstraintInterface {
  constructor(private dataSource: DataSource) {}
  validate(value: any, args: ValidationArguments) {
    return this.dataSource
      .getRepository(args.targetName)
      .findOne({
        where: {
          [args.property]: value,
        },
      })
      .then((entity) => {
        if (entity) return false;
        return true;
      });
  }
}

export function IsUnique(validationOptions?: ValidationOptions) {
  return function (object: object, propertyName: string) {
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [],
      validator: IsUniqueConstraint,
    });
  };
}

```

 inject dependencies into your custom validator in `main.ts`

```ts
import { NestFactory } from '@nestjs/core';
import { useContainer } from 'class-validator';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    logger: ['error', 'warn', 'debug'],
  });

  //  inject dependencies into your custom validator
  useContainer(app.select(AppModule), { fallbackOnErrors: true });

  await app.listen(process.env.PORT || 3000);

  console.log(`Application is running on: ${await app.getUrl()}`);
}

bootstrap();
```

make inject work in `app.module.ts`

```ts
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { WinstonModule } from 'nest-winston';
import * as winston from 'winston';
import { AuthModule } from './auth/auth.module';
import { IsUniqueConstraint } from './common/validation-decorator/is-unique';
import { UsersModule } from './users/users.module';

@Module({
  imports: [
    WinstonModule.forRoot({
      transports: [
        //
        // - Write all logs with importance level of `error` or less to `error.log`
        // - Write all logs with importance level of `info` or less to `combined.log`
        //
        new winston.transports.File({ filename: 'debug.log', level: 'debug' }),
        new winston.transports.File({ filename: 'error.log', level: 'error' }),
        new winston.transports.File({ filename: 'combined.log' }),
      ],
    }),
    TypeOrmModule.forRoot({
      type: 'sqlite',
      database: 'db.sql',
      autoLoadEntities: true,
      synchronize: true,
    }),
    UsersModule,
    AuthModule,
  ],
  controllers: [],
  // add to providers
  providers: [IsUniqueConstraint],
})
export class AppModule {}
```

just use it in you `entity.ts`

```ts
import {
  Column,
  Entity,
  PrimaryGeneratedColumn
} from 'typeorm';
import { IsUnique } from '../../common/validation-decorator/is-unique';

@Entity({ name: 'users' })
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @IsUnique({ always: true, message: 'username already exists' })
  @Column({ unique: true })
  username: string;
}

```

**Comment by alvissraghnall** [comment]
> here is my new solution
> 
> add a file name `is-unique.ts` Custom validation decorators
> 
> ```ts
> import { Injectable } from '@nestjs/common';
> import {
>   registerDecorator,
>   ValidationArguments,
>   ValidationOptions,
>   ValidatorConstraint,
>   ValidatorConstraintInterface,
> } from 'class-validator';
> import { DataSource } from 'typeorm';
> 
> @ValidatorConstraint({ name: 'isUnique', async: true })
> @Injectable()
> export class IsUniqueConstraint implements ValidatorConstraintInterface {
>   constructor(private dataSource: DataSource) {}
>   validate(value: any, args: ValidationArguments) {
>     return this.dataSource
>       .getRepository(args.targetName)
>       .findOne({
>         where: {
>           [args.property]: value,
>         },
>       })
>       .then((entity) => {
>         if (entity) return false;
>         return true;
>       });
>   }
> }
> 
> export function IsUnique(validationOptions?: ValidationOptions) {
>   return function (object: object, propertyName: string) {
>     registerDecorator({
>       target: object.constructor,
>       propertyName: propertyName,
>       options: validationOptions,
>       constraints: [],
>       validator: IsUniqueConstraint,
>     });
>   };
> }
> ```
> 
> inject dependencies into your custom validator in `main.ts`
> 
> ```ts
> import { NestFactory } from '@nestjs/core';
> import { useContainer } from 'class-validator';
> import { AppModule } from './app.module';
> 
> async function bootstrap() {
>   const app = await NestFactory.create(AppModule, {
>     logger: ['error', 'warn', 'debug'],
>   });
> 
>   //  inject dependencies into your custom validator
>   useContainer(app.select(AppModule), { fallbackOnErrors: true });
> 
>   await app.listen(process.env.PORT || 3000);
> 
>   console.log(`Application is running on: ${await app.getUrl()}`);
> }
> 
> bootstrap();
> ```
> 
> make inject work in `app.module.ts`
> 
> ```ts
> import { Module } from '@nestjs/common';
> import { TypeOrmModule } from '@nestjs/typeorm';
> import { WinstonModule } from 'nest-winston';
> import * as winston from 'winston';
> import { AuthModule } from './auth/auth.module';
> import { IsUniqueConstraint } from './common/validation-decorator/is-unique';
> import { UsersModule } from './users/users.module';
> 
> @Module({
>   imports: [
>     WinstonModule.forRoot({
>       transports: [
>         //
>         // - Write all logs with importance level of `error` or less to `error.log`
>         // - Write all logs with importance level of `info` or less to `combined.log`
>         //
>         new winston.transports.File({ filename: 'debug.log', level: 'debug' }),
>         new winston.transports.File({ filename: 'error.log', level: 'error' }),
>         new winston.transports.File({ filename: 'combined.log' }),
>       ],
>     }),
>     TypeOrmModule.forRoot({
>       type: 'sqlite',
>       database: 'db.sql',
>       autoLoadEntities: true,
>       synchronize: true,
>     }),
>     UsersModule,
>     AuthModule,
>   ],
>   controllers: [],
>   // add to providers
>   providers: [IsUniqueConstraint],
> })
> export class AppModule {}
> ```
> 
> just use it in you `entity.ts`
> 
> ```ts
> import {
>   Column,
>   Entity,
>   PrimaryGeneratedColumn
> } from 'typeorm';
> import { IsUnique } from '../../common/validation-decorator/is-unique';
> 
> @Entity({ name: 'users' })
> export class User {
>   @PrimaryGeneratedColumn('uuid')
>   id: string;
> 
>   @IsUnique({ always: true, message: 'username already exists' })
>   @Column({ unique: true })
>   username: string;
> }
> ```

tried this and it doesn't work. It still throws error:
```
[Nest] 11080  - 19/02/2023, 20:28:51   ERROR [ExceptionsHandler] duplicate key value violates unique constraint "UQ_e12875dfb3b1d92d7d7c5377e22"
QueryFailedError: duplicate key value violates unique constraint "UQ_e12875dfb3b1d92d7d7c5377e22"
    at PostgresQueryRunner.query ...
```

**Comment by alvissraghnall** [comment]
> > here is my new solution
> > add a file name `is-unique.ts` Custom validation decorators
> > ```ts
> > import { Injectable } from '@nestjs/common';
> > import {
> >   registerDecorator,
> >   ValidationArguments,
> >   ValidationOptions,
> >   ValidatorConstraint,
> >   ValidatorConstraintInterface,
> > } from 'class-validator';
> > import { DataSource } from 'typeorm';
> > 
> > @ValidatorConstraint({ name: 'isUnique', async: true })
> > @Injectable()
> > export class IsUniqueConstraint implements ValidatorConstraintInterface {
> >   constructor(private dataSource: DataSource) {}
> >   validate(value: any, args: ValidationArguments) {
> >     return this.dataSource
> >       .getRepository(args.targetName)
> >       .findOne({
> >         where: {
> >           [args.property]: value,
> >         },
> >       })
> >       .then((entity) => {
> >         if (entity) return false;
> >         return true;
> >       });
> >   }
> > }
> > 
> > export function IsUnique(validationOptions?: ValidationOptions) {
> >   return function (object: object, propertyName: string) {
> >     registerDecorator({
> >       target: object.constructor,
> >       propertyName: propertyName,
> >       options: validationOptions,
> >       constraints: [],
> >       validator: IsUniqueConstraint,
> >     });
> >   };
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > inject dependencies into your custom validator in `main.ts`
> > ```ts
> > import { NestFactory } from '@nestjs/core';
> > import { useContainer } from 'class-validator';
> > import { AppModule } from './app.module';
> > 
> > async function bootstrap() {
> >   const app = await NestFactory.create(AppModule, {
> >     logger: ['error', 'warn', 'debug'],
> >   });
> > 
> >   //  inject dependencies into your custom validator
> >   useContainer(app.select(AppModule), { fallbackOnErrors: true });
> > 
> >   await app.listen(process.env.PORT || 3000);
> > 
> >   console.log(`Application is running on: ${await app.getUrl()}`);
> > }
> > 
> > bootstrap();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > make inject work in `app.module.ts`
> > ```ts
> > import { Module } from '@nestjs/common';
> > import { TypeOrmModule } from '@nestjs/typeorm';
> > import { WinstonModule } from 'nest-winston';
> > import * as winston from 'winston';
> > import { AuthModule } from './auth/auth.module';
> > import { IsUniqueConstraint } from './common/validation-decorator/is-unique';
> > import { UsersModule } from './users/users.module';
> > 
> > @Module({
> >   imports: [
> >     WinstonModule.forRoot({
> >       transports: [
> >         //
> >         // - Write all logs with importance level of `error` or less to `error.log`
> >         // - Write all logs with importance level of `info` or less to `combined.log`
> >         //
> >         new winston.transports.File({ filename: 'debug.log', level: 'debug' }),
> >         new winston.transports.File({ filename: 'error.log', level: 'error' }),
> >         new winston.transports.File({ filename: 'combined.log' }),
> >       ],
> >     }),
> >     TypeOrmModule.forRoot({
> >       type: 'sqlite',
> >       database: 'db.sql',
> >       autoLoadEntities: true,
> >       synchronize: true,
> >     }),
> >     UsersModule,
> >     AuthModule,
> >   ],
> >   controllers: [],
> >   // add to providers
> >   providers: [IsUniqueConstraint],
> > })
> > export class AppModule {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > just use it in you `entity.ts`
> > ```ts
> > import {
> >   Column,
> >   Entity,
> >   PrimaryGeneratedColumn
> > } from 'typeorm';
> > import { IsUnique } from '../../common/validation-decorator/is-unique';
> > 
> > @Entity({ name: 'users' })
> > export class User {
> >   @PrimaryGeneratedColumn('uuid')
> >   id: string;
> > 
> >   @IsUnique({ always: true, message: 'username already exists' })
> >   @Column({ unique: true })
> >   username: string;
> > }
> > ```
> 
> tried this and it doesn't work. It still throws error:
> 
> ```
> [Nest] 11080  - 19/02/2023, 20:28:51   ERROR [ExceptionsHandler] duplicate key value violates unique constraint "UQ_e12875dfb3b1d92d7d7c5377e22"
> QueryFailedError: duplicate key value violates unique constraint "UQ_e12875dfb3b1d92d7d7c5377e22"
>     at PostgresQueryRunner.query ...
> ```

welpp. I just figured out why - at least in my use-case. I was decorating the entity class directly rather than DTO classes. Moving the decorator (and editing it a bit, I must say) worked for me.

**Comment by carloschneider** [comment]
@alvissraghnall How did you access the `dataSource` object inside `validate` method?

**Comment by bahaa-alden** [comment]
`import { Injectable } from '@nestjs/common';
import {
  registerDecorator,
  ValidationArguments,
  ValidationOptions,
  ValidatorConstraint,
  ValidatorConstraintInterface,
} from 'class-validator';
import { DataSource } from 'typeorm';

@ValidatorConstraint({ name: 'isUnique', async: true })
@Injectable()
export class IsUniqueConstraint implements ValidatorConstraintInterface {
  constructor(private dataSource: DataSource) {}
  validate(value: any, args: ValidationArguments) {
    return this.dataSource
      .getRepository(args.constraints[0])
      .findOne({
        where: {
          [args.property]: value,
        },
      })
      .then((entity) => {
        if (entity) return false;
        return true;
      });
  }
}

export function IsUnique(
  entity: string,
  validationOptions?: ValidationOptions,
) {
  return function (object: object, propertyName: string) {
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [entity],
      validator: IsUniqueConstraint,
    });
  };
}
`

i put the entity name in the constraints and pass it as parameter like this
`   @ApiProperty()
  @IsEmail({}, { message: 'please provide valid email' })
  @IsUnique(Entities.User, { message: 'Email already taken' })
  readonly email: string;
`

**Comment by bahaa-alden** [comment]
i put the entity name in the constraints 
`import { Injectable } from '@nestjs/common';
import {
  registerDecorator,
  ValidationArguments,
  ValidationOptions,
  ValidatorConstraint,
  ValidatorConstraintInterface,
} from 'class-validator';
import { DataSource } from 'typeorm';

@ValidatorConstraint({ name: 'isUnique', async: true })
@Injectable()
export class IsUniqueConstraint implements ValidatorConstraintInterface {
  constructor(private dataSource: DataSource) {}
  validate(value: any, args: ValidationArguments) {
    return this.dataSource
      .getRepository(args.constraints[0])
      .findOne({
        where: {
          [args.property]: value,
        },
      })
      .then((entity) => {
        if (entity) return false;
        return true;
      });
  }
}

export function IsUnique(
  entity: string,
  validationOptions?: ValidationOptions,
) {
  return function (object: object, propertyName: string) {
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [entity],
      validator: IsUniqueConstraint,
    });
  };
}
`
and pass it like that 
` @IsUnique('User', { message: 'email already exist' })
  @ApiProperty()
  @IsEmail({}, { message: 'please provide valid email' })
  readonly email: string;
`
and it worked
