### ISSUE TITLE
no need to check for existing relations on insert/delete

### ISSUE THREAD

**Issue by byteCrunsher** [typeorm/typeorm#4895]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I  have two entities, **users** and **groups**. A User can join multiple groups and a group can have multiple users.

```ts
@Entity('User')
export class UserEntity {
    @PrimaryGeneratedColumn()
    id: number;

    // ...

    @ManyToMany((type: any) => GroupEntity, (group: GroupEntity) => group.users)
    @JoinTable()
    groups: GroupEntity[];
}
```

```ts
@Entity('Group')
export class GroupEntity {
    @PrimaryGeneratedColumn()
    id: number;

    // ...

    @ManyToMany((type: any) => UserEntity, (user: UserEntity) => user.groups)
    users: UserEntity[];
}
```

I want to provide two endpoints to assign a user to a group / remove a user from a group. This is how I currently assign a user to a group:

```ts
public async persistGroupRelationById(persistGroupRelationByIdDTO: PersistGroupRelationByIdDTO): Promise < void > {
    const user: UserEntity = await this.usersRepository.findOne(persistGroupRelationByIdDTO.userId, {
        relations: ['groups']
    });

    if (!user) {
        throw new NotFoundException('user not found');
    }

    const group: GroupEntity = await this.groupsRepository.findOne(persistGroupRelationByIdDTO.groupId);

    if (!group) {
        throw new NotFoundException('group not found');
    }

    user.groups.push(group);

    await this.usersRepository.save(user);
}
```

For the removing part I do the same but instead of pushing I remove the group by filtering

```ts
user.groups = user.groups.filter((currentGroup: GroupEntity) => currentGroup.id !== group.id);
```

I played around with the code and it seems to work fine. If the relation already exists and I try to add it, the code will **NOT** throw an exception. If it doesn't exist and I want to remove it neither.

I'm assuming I don't have to check for the relation before manipulating it then?

Thanks in advance!

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
