### ISSUE TITLE
[MSSQL] Enum column definition removes and recreates constraint overwritting existing data

### ISSUE THREAD

**Issue by karlos1337** [typeorm/typeorm#4897]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```ts
export type UserRole = 'user' | 'admin';
export const userRoles = {
  USER: 'user' as UserRole,
  ADMIN: 'admin' as UserRole,
};

@Column('simple-enum', {
  default: userRoles.USER,
  enum: Object.values(userRoles),
})
role: UserRole;
```
On each compilation related constraint is removed and recreated so existing data is overwritten with default value (in this case switching all `admin` roles to `user`). I tried also using native `enum` or setting an static array `['user', 'admin']` as Column enum option, both with same result.

Related trace from nest:
```bash
nest_1    | query: SELECT * FROM "nest"."INFORMATION_SCHEMA"."TABLES" WHERE "TABLE_NAME" = 'typeorm_metadata' AND "TABLE_SCHEMA" = SCHEMA_NAME()
nest_1    | dropping old check constraint: "CK__user__role__3631FF56" from table "user"
nest_1    | query: ALTER TABLE "user" DROP CONSTRAINT "CK__user__role__3631FF56"
nest_1    | renaming column "role" in to "role"
nest_1    | columns changed in "user". updating: role
nest_1    | query: ALTER TABLE "user" DROP CONSTRAINT "DF_6620cd026ee2b231beac7cfe578"
nest_1    | query: ALTER TABLE "user" DROP COLUMN "role"
nest_1    | query: ALTER TABLE "user" ADD "role" nvarchar(255) CHECK( role IN ('user','admin') ) NOT NULL CONSTRAINT "DF_6620cd026ee2b231beac7cfe578" DEFAULT 'user'
nest_1    | query: COMMIT
```

**Comment by reilem** [comment]
I am having this exact same issue.

First I received a warning that ALTER TABLE isn't possible unless the enum'ed column was either nullable or had a default value. If I added nullable, then on server refresh (with synchronise on) the entire column was made NULL, and if I added a default value, the entire column became that default value.

Are there any updates on this?

**Comment by Shavindra** [comment]
I am experiencing the same issue when declaring the ` type: 'simple-enum',`

**Comment by reilem** [comment]
Thanks @AlexMesser 😄

**Comment by sannajammeh** [comment]
Typeorm overwrites my enums with the Postgres driver as well.

**Comment by Dezzmeister** [comment]
I am having the same issue with Postgres 13. As far as I have tested, this issue has been present since typeorm 0.2.21. To reproduce:
1. Create an entity with an enum member. Do not give the enum member a default value.
2. Create (do not generate) a migration. In the migration, create a table for the entity and populate it with rows for which the value of the enum is not identical.
3. Run the migration and start the server.
4. The server should crash when typeorm tries to destroy your table.
