### ISSUE TITLE
TypeORM including tables not related to query when using a subquery

### ISSUE THREAD

**Issue by oscar-corredor** [typeorm/typeorm#4898]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I am currently trying to implement the following query in typeorm:
```
 select id,"createdAt", "updatedAt","deactivatedAt",(EXTRACT(EPOCH FROM "deactivatedAt" - "createdAt")/3600 ) as lifespan
    from (
       select id,"createdAt", "updatedAt","deactivatedAt", (EXTRACT(EPOCH FROM "deactivatedAt" - "createdAt")/3600 )as time
       from apartment_listing where active = false)as subquery
where subquery.time <24
```
For this, I have implemented the following code in in TypeScript:
```
    const mainQuery = this.repository
      .createQueryBuilder()
      .select("subquery.id", "id")
      .addSelect("subquery.time", "time")
      .addSelect("subquery.created", "createdAt")
      .addSelect("subquery.deactivated", "deactivatedAt")
      .from(qb => {
        const sub = qb.select(
          "(EXTRACT(EPOCH FROM listing.deactivatedAt - listing.createdAt )/3600 )",
          "time"
        )
        .addSelect("listing.deactivatedAt", "deactivated")
        .addSelect("listing.id", "id")
        .addSelect("listing.createdAt", "created")
        .addSelect("listing.active","active")
        .from(this.type, "listing")
        .where("listing.active = false")
        return sub;
      }, "subquery")
      .where("subquery.time < 24")
```

However, when executing this code the query generated by typeorm is incorrect and results in an infinite query which ends up using 100% of ram. The query generated is:
```
SELECT subquery.id AS "id", subquery.time AS "time", subquery.created AS "createdAt", subquery.deactivated AS "deactivatedAt" 
FROM "apartment_listing" "ApartmentListing", (SELECT "listing"."id" AS "id", "listing"."active" AS "active", "listing"."createdAt" AS "created", "listing"."deactivatedAt" AS "deactivated", (EXTRACT(EPOCH FROM "listing"."deactivatedAt" - "listing"."createdAt" )/3600 ) AS "time" FROM "apartment_listing" "listing" WHERE "listing"."active" = false) "subquery" 
WHERE subquery.time < 24
```

As you can see, in the FROM clause it includes the ```"apartment_listing" "ApartmentListing"``` table as well as the subquery. If I copy and paste this query in PgAdmin, it also ends up in an infinite query, but if I remove that extra ```"apartment_listing" "ApartmentListing",``` table from the FROM clause, the result is successfull and I get the correct result.

Why is typeORM including this ```"apartment_listing" "ApartmentListing",```? in my code implementation there is only one FROM and it points to the subquery. How can I get rid of that extra table so the query executes successfully?

Thanks in advance

**Comment by imnotjames** [comment]
Can you create a reproducible example?  It's hard to know what's going on without that.

**Comment by aravind-korada** [comment]
Same problem for me as well.
The generated query is this 
`SELECT a.* FROM "scheduled_posts" "ScheduledPost", (SELECT *, "click"/"reach" as ctr, ROW_NUMBER () OVER (PARTITION BY "postId" order by "click"/"reach" DESC) as rank FROM "scheduled_posts" "ScheduledPost" WHERE "reach" > 0) "a" WHERE "rank" <= 2`

but the expected is this
`SELECT a.* FROM (SELECT *, "click"/"reach" as ctr, ROW_NUMBER () OVER (PARTITION BY "postId" order by "click"/"reach" DESC) as rank FROM "scheduled_posts" "ScheduledPost" WHERE "reach" > 0) "a" WHERE "rank" <= 2`
