### ISSUE TITLE
Date: Timezone problem

### ISSUE THREAD

**Issue by yannisgu** [typeorm/typeorm#49]
Currently dates are parsed with `moment(dateString)`. This assumes that the `dateString`is in the local timezone. However this is not necessary the case. Especialy with `DATE` columns, where you only store the date, but not the time. If your environemnt is not in UTC, you will end with really strange behaviours. Given you are in UTC+1, when you get 2016-10-02 from the DB, you will have a  Date object with the value `2016-10-02 00:00:00 UTC+1`. When you use a UTC method like `toISOString` you will get `2016-10-01T23:00:00.000Z`. As `toISOString` is how `JSON.stringify` serializes date, this is kind of problematic. 

That's why I would argue to use `moment.utc(dateString)` to parse dates from the DB.

**Comment by pleerock** [comment]
do you use mysql database? I remember I had same issues as you, and made same change as you suggested on my local branch, but later forgot to push. I was worrying if this solution will work in all cases (I was thinking how to handle situations when use want to save dates in a local timezone). Do you think it will work in all cases?

**Comment by yannisgu** [comment]
Yes I use MySql. Good question. I probably depends on the column type:
`DATE`
Here we don't care about timezones, because there is no time. Actually the best thing would be to have a JavaScript type for "Date without time and timezone", but since this doesn't exist I think the best solution is to use UTC here. 
Or maybe it would be better to consider `DATE` as string as there is no good JavaScript type for it?

`TIME` & `DATETIME`
Here you are probably right. Some want to store in UTC, some in the servers timezone. But generally it's much better to store in UTC. What if you change your hosting to another Timezone? Everything will break. 


What is important, is that this must be considered in the save mechanism too. So `preparePersistentValue` must also be changed to `moment(value).utc().format("xx"), at least for `TIME` and `DATETIME`. For `DATE` I'm not too sure. Again... string for `DATE` would make things much easier in my opinion.

**Comment by pleerock** [comment]
[here](https://github.com/typeorm/typeorm/pull/73/commits/146d1499d1cb55dc8c3323af2071cd6c5529daa0) I made a change:

`DATE` and `TIME` now simply strings. `DATETIME` now saved in utc by default. To make mysql driver to return date in utc format you need to set `extra: { timezone: "utc" }`

**Comment by pleerock** [comment]
will be released in next typeorm version
