### ISSUE TITLE
How to make a migrations without ormconfig.json ?

### ISSUE THREAD

**Issue by jdelobel** [typeorm/typeorm#490]
I need to work without configuration file but only with environment variables.

Is it possible to do a typeorm migrations:run using only environment variables?
Can you give me an example?

**Comment by pleerock** [comment]
Yes it should be possible using [env variables](https://typeorm.github.io/connection.html#connection-environment-variables)

**Comment by pleerock** [comment]
In recent 0.1.0-alpha.8 version I have added complete support of ENV variables in both cli and app.

Also now typeorm now uses [donenv](https://github.com/motdotla/dotenv) package, so instead of ormconfig.json you can create ormconfig.env and define it this way:

```ini
TYPEORM_CONNECTION = mysql
TYPEORM_HOST = localhost
TYPEORM_PORT = 3306
TYPEORM_USERNAME = test
TYPEORM_PASSWORD = test
TYPEORM_DATABASE = test
TYPEORM_AUTO_SCHEMA_SYNC = true
TYPEORM_ENTITIES = src/entity/*.js
TYPEORM_SUBSCRIBERS = src/subscriber/*.js
TYPEORM_MIGRATIONS = src/migration/*.js
TYPEORM_ENTITIES_DIR = src/entity
TYPEORM_MIGRATIONS_DIR = src/migration
TYPEORM_SUBSCRIBERS_DIR = src/subscriber
`

**Comment by pleerock** [comment]
feel free to reopen it if you still have questions

**Comment by NoNameProvided** [comment]
This means, #391 is obsolete now right?

**Comment by pleerock** [comment]
right

**Comment by mmitchellgarcia** [comment]
@pleerock would you welcome a PR that allows you to specify config in simply a .env file? I work on Heroku and it is much simpler to work with config in this way. Currently, in order to get config loaded by the CI, I have to specify an ormconfig.js like this:

`
const dotenv = require('dotenv');
const config = dotenv.config().parsed;

module.exports = {
	type: config.TYPEORM_CONNECTION,
	/// etc.
}
`

**Comment by pleerock** [comment]
@mmitchellgarcia TypeORM already supports `ormconfig.env` file

**Comment by mmitchellgarcia** [comment]
@pleerock I believe Heroku is only looking for a singular instance of a '.env' file. So the file 'ormconfig.env' is ignored, but anything specified in the file '.env' is included. 

What I'm looking for is Typeorm to read from a '.env' file in the project directory if 'ormconfig.env' is undefined.

**Comment by pleerock** [comment]
I don't see any reason why typeorm should look for `.env` file in the case if `ormconfig.env` file does not exist. Looks like very specific need. I recommend you to manually load all env files from your `.env` file (maybe using don-env package) and typeorm will catch up all env vars from process.env as usual

**Comment by sumeet-bansal** [comment]
@pleerock Is it possible to use existing env vars and maybe tell the CLI which vars to use via `ormconfig` or something similar?
