### ISSUE TITLE
EntityManager.find() : Complex where condition 

### ISSUE THREAD

**Issue by JulienB37** [typeorm/typeorm#4903]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

I would like to execute a simple query like this : `SELECT * FROM user.user WHERE deleted is NULL AND (lastname = 'Doe' OR (lastname != 'Doe' AND firtname = 'john'))`

Is it possible to write this where condition with the entityManager.find() function ? If yes, how ??

Thanx a lot for your help

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
You'll need to use the querybuilder.
