### ISSUE TITLE
OneToMany relation is undefined when new object is constructed

### ISSUE THREAD

**Issue by bogdan** [typeorm/typeorm#4907]
**Issue type:**

[ ] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[*] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[*] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

``` typescript
import {BaseEntity, Column, Entity, OneToOne, PrimaryGeneratedColumn, OneToMany, ManyToOne, RelationId} from 'typeorm';

@Entity
export default class Tx extends BaseEntity {
  @ManyToOne(type => Tx, tx => tx.children, {nullable: true })
  parent: Tx

  @OneToMany(type => Tx, tx => tx.parent)
  children: Tx[]
}


let tx = new Tx()
tx.children // expected => [], actual => undefined
```

**Comment by njbrown** [comment]
I'm having the same issue on version 0.2.20

**Comment by JemarJones** [comment]
Anyone figure this out? I've got the same issue currently

**Comment by imnotjames** [comment]
If you want it to construct with an empty array you have to define it as that.

```

@Entity
export default class Tx extends BaseEntity {
  @ManyToOne(type => Tx, tx => tx.children, {nullable: true })
  parent: Tx

  @OneToMany(type => Tx, tx => tx.parent)
  children: Tx[] = []
}
```

We don't touch the props except during load from db
