### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by Erchoc** [typeorm/typeorm#4908]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

![image](https://user-images.githubusercontent.com/19908809/66787904-0560e300-ef18-11e9-9e9f-80bfe7fca7a4.png)

when I import entity from typeorm，this problem happend. how can I solve it please

**Comment by sandramfdeveloper** [comment]
If you're using @nestjs try to change the new commands recently added to package.json.

So change start:dev and and start and put the old ones:

"start": "ts-node -r tsconfig-paths/register src/main.ts",
"start:dev": "tsc-watch -p tsconfig.build.json --onSuccess \"node dist/main.js\"",

Hope to work

**Comment by Erchoc** [comment]
> If you're using @nestjs try to change the new commands recently added to package.json.
> 
> So change start:dev and and start and put the old ones:
> 
> "start": "ts-node -r tsconfig-paths/register src/main.ts",
> "start:dev": "tsc-watch -p tsconfig.build.json --onSuccess "node dist/main.js"",
> 
> Hope to work

why should do these steps？ It looks not work yet.

**Comment by douhn** [comment]
I've just had this problem, too.
You can add this symbol here.
![image](https://user-images.githubusercontent.com/15902994/66939788-52f36200-f076-11e9-9765-2f67dbb233ef.png)

**Comment by anvad** [comment]
check out the [comments from similar issue 150](https://github.com/nestjs/typeorm/issues/150#issuecomment-510716686) reported earlier.


```ts
/* replaced original two lines */
      // entities: ['**/*.entity{.ts,.js}'],
      // migrations: ['src/migration/*.ts'],

/* with these two lines */
      entities: [path.join(__dirname, '../**/*.entity{.ts,.js}')],
      migrations: [path.join(__dirname, '../migration/*{.ts,.js')],
 ```
Look at the answer to this SO question for details on what I did following the suggestions in the previous issue comments: https://stackoverflow.com/questions/58902715/nx-nestjs-typeorm-syntaxerror-unexpected-token/60215116#60215116

**Comment by Lampent** [comment]
Having the same problem, let me know if you found a solution.

**Comment by imnotjames** [comment]
This is a Typescript / project configuration problem.

For other questions like this, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
