### ISSUE TITLE
How to set primary key name?

### ISSUE THREAD

**Issue by max10rogerio** [typeorm/typeorm#4909]
How to alter primary key constraint name of `PK_3e9888411f62082be12e16ed545` to `user_pk_id`, on migration?

**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
- Create a migration with column id - primary key
- See in table constraint primary key name, ex: PK_3e9888411f62082be12e16ed545

Postgres - migration - example:
```ts
import { MigrationInterface, QueryRunner, Table } from 'typeorm'

export class CreateTableInstituicao1571078771928 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.createTable(
      new Table({
        name: 'User',
        columns: [
          {
            name: 'id',
            type: 'int',
            isPrimary: true,
            isGenerated: true,
            generationStrategy: 'increment',
            // pk constraint name?
          },
          {
            name: 'name',
            type: 'varchar',
          },
        ],
      })
    )
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.dropTable('User')
  }
}
```

**Comment by danielszenasi** [comment]
@max10rogerio did you solve it somehow?

**Comment by max10rogerio** [comment]
yeap! I gonna close this issue... thanks!

**Comment by veyronfei** [comment]
maybe I ask what is the solution?

**Comment by sidneiklein83** [comment]
I need also control the primary key name and no found the solution/configuration.

**Comment by max10rogerio** [comment]
Typeorm don't have this option... then I changed to `sequelize-typescript` in 2019-10.
Today I need use named contraints and the lib haven't this feature #sad :'(
A moderade solution is use a custom class of namedStrategy but is very limited.

https://github.com/typeorm/typeorm/blob/master/docs/naming-strategy.md

**Comment by max10rogerio** [comment]
Example:
> ormconfig.ts
```js
import { CustomNamingStrategy } from "./src/configs/CustomNamingStrategy";

module.exports = {
  type: "mssql",
  host: "localhost",
  username: "sa",
  password: "Dev#0110",
  port: 1433,
  database: "conversor",
  logging: false,
  entities: ["src/entity/**/*.ts"],
  migrations: ["src/migration/**/*.ts"],
  subscribers: ["src/subscriber/**/*.ts"],
  cli: {
    entitiesDir: "src/entity",
    migrationsDir: "src/migration",
    subscribersDir: "src/subscriber",
  },
  namingStrategy: new CustomNamingStrategy(),
};
```

> CustomNamingStrategy
```js
import { DefaultNamingStrategy, Table, NamingStrategyInterface } from "typeorm";

export class CustomNamingStrategy extends DefaultNamingStrategy implements NamingStrategyInterface {
  primaryKeyName(tableOrName: Table | string, columnNames: string[]) {
    const table = tableOrName instanceof Table ? tableOrName.name : tableOrName;
    const columnsSnakeCase = columnNames.join("_");

    return `${table}_${columnsSnakeCase}_pk`;
  }
}
```

> entity -> Alunos.ts
```js
import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity("alunos")
export class Alunos {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("char", { name: "codigo", nullable: true, length: 6 })
  codigo: string | null;

  @Column("varchar", { name: "nome", nullable: true, length: 65 })
  nome: string | null;
}
```

> migration (auto-generated by command: `yarn typeorm migration:generate -n create-table-alunos`
```js
import { MigrationInterface, QueryRunner } from "typeorm";

export class createTableAlunos1595611662216 implements MigrationInterface {
  name = "createTableAlunos1595611662216";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "alunos" ("id" int NOT NULL IDENTITY(1,1), "codigo" char(6), "nome" varchar(65), CONSTRAINT "alunos_id_pk" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "alunos"`);
  }
}
```

**Comment by bc05** [comment]
Thanks for this <3

**Comment by bc05** [comment]
https://github.com/typeorm/typeorm/blob/master/docs/naming-strategy.md

**Comment by vspok** [comment]
> Exemplo:
> 
> > ormconfig.ts
> 
> ```js
> import  {  CustomNamingStrategy  }  de  "./src/configs/CustomNamingStrategy" ;
> 
> módulo . exportações  =  { 
>   tipo : "mssql" , 
>   host : "localhost" , 
>   nome de usuário : "sa" , 
>   senha : "Dev # 0110" , 
>   porta : 1433 , 
>   banco de dados : "conversor" , 
>   registro : falso , 
>   entidades : [ "src / entidade /**/*.ts " ] , 
>   migrações : [ " src / migration / ** / *. ts " ] , 
>   assinantes : ["src / subscriber / ** / *. ts" ] , 
>   cli : { 
>     entityDir : "src / entity" , 
>     migrationsDir : "src / migration" , 
>     subscribersDir : "src / subscriber" , 
>   } , 
>   namingStrategy : new  CustomNamingStrategy ( ) , 
> } ;
> ```
> 
> > CustomNamingStrategy
> 
> ```js
> import  {  DefaultNamingStrategy ,  Table ,  NamingStrategyInterface  }  de  "typeorm" ;
> 
> export  class  CustomNamingStrategy  estende  DefaultNamingStrategy  implementa  NamingStrategyInterface  { 
>   primaryKeyName ( tableOrName : Table  |  string ,  columnNames : string [ ] )  { 
>     const  table  =  tableOrName  instanceof  Table ? tableOrName . nome : tableOrName ; 
>     const  columnSnakeCase  =  columnNames . juntar ( "_" );
> 
>     return  ` $ { table } _ $ { columnsSnakeCase } _pk` ; 
>   } 
> }
> ```
> 
> > entidade -> Alunos.ts
> 
> ```js
> import  {  Column ,  Entity ,  PrimaryGeneratedColumn  }  de  "typeorm" ;
> 
> @ Entity ( "alunos" ) 
> exportar  classe  Alunos  { 
>   @ PrimaryGeneratedColumn ( ) 
>   id : number ;
> 
>   @ Column ( "char" ,  {  nome : "codigo" ,  nullable : true ,  length : 6  } ) 
>   codigo : string  |  null ;
> 
>   @ Column ( "varchar" ,  {  nome : "nome" ,  anulável : verdadeiro ,  comprimento : 65  } ) 
>   nome : string  |  null ; 
> }
> ```
> 
> > migração (gerada automaticamente pelo comando: `yarn typeorm migration:generate -n create-table-alunos`
> 
> ```js
> import { MigrationInterface, QueryRunner } from "typeorm";
> 
> export class createTableAlunos1595611662216 implements MigrationInterface {
>   name = "createTableAlunos1595611662216";
> 
>   public async up(queryRunner: QueryRunner): Promise<void> {
>     await queryRunner.query(
>       `CREATE TABLE "alunos" ("id" int NOT NULL IDENTITY(1,1), "codigo" char(6), "nome" varchar(65), CONSTRAINT "alunos_id_pk" PRIMARY KEY ("id"))`,
>     );
>   }
> 
>   public async down(queryRunner: QueryRunner): Promise<void> {
>     await queryRunner.query(`DROP TABLE "alunos"`);
>   }
> }
> ```

não funcionou pra mim ja uso 
```js
columnName(
    propertyName: string,
    customName: string,
    embeddedPrefixes: string[],
  ): string {
    return (
      snakeCase(embeddedPrefixes.concat('').join('_')) +
      (customName ? customName : snakeCase(propertyName))
    );
  }
```
que funciona. 
mas 
```js
primaryKeyName(tableOrName: Table | string, columnNames: string[]) : string {
    const table = tableOrName instanceof Table ? tableOrName.name : tableOrName;
    const columnsSnakeCase = columnNames.join("_");
    console.log( `${table}_${columnsSnakeCase}_pk`)
    console.log( 'adasdas')
    return `${table}_${columnsSnakeCase}`;
  }
```
não funciona
