### ISSUE TITLE
Migrations: the timestamp is not correct

### ISSUE THREAD

**Issue by jdelobel** [typeorm/typeorm#491]
When I make a migrations,  the timestamp is not correct so the next migration fails because the timestamp is smaller than the previous migration.

Example in db:

3737971793;"AddConstraint1493737971793"
9616541690;"ActivateUUID1489616541690"

The first 3 digit is not present in the timestamp.

**Comment by Spoki4** [comment]
Update typeorm version. it's bug fixed. #360
