### ISSUE TITLE
Mix raw where condition with key-value conditions

### ISSUE THREAD

**Issue by bogdan** [typeorm/typeorm#4914]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

What is the best way to mix where conditions in Raw SQL and simple conditions (aka `FindConditions`?

I have a complex raw SQL condition:

``` typescript
let rawCondition = `"Tx"."parentId" is null or exists(select 1 from txprocessor_tx ptx where ptx.id = "Tx".id and ptx.status = ${Tx.Status.Confirmed})`
``` 

And I want to mix that with trivial conditions like `{name: value1, title: value2}`.
How can I pack all that into the same `find` call with `AND` statement in between? So that I get the following SQL:

``` sql
select * ... 
where "Tx"."parentId" is null or exists(
    select 1 from txprocessor_tx ptx 
    where ptx.id = "Tx".id and ptx.status = ${Tx.Status.Confirmed}) and
        title = $1 and name = $2
)
```

**Comment by imnotjames** [comment]
You could maybe get by with `Raw` find operator.  But generally I think you're pushing `find` too hard here - you should be using the query builder.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by bogdan** [comment]
@imnotjames I didn't mean I have to use `find` here. If you can give me an example with query builder, it would be nice.
