### ISSUE TITLE
Error: Column "email" of relation "user" does not exist

### ISSUE THREAD

**Issue by coooolers** [typeorm/typeorm#4915]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

$npm run db:seed
> cab-api@1.0.0 db:seed /home/raman/Project/p/api
> ts-node src/seed.ts
Creating seeds 🌱
column "email" of relation "user" does not exist

**seed.ts**

`
import "reflect-metadata"
import { createDbConnection } from "./db"
import { User } from "./modules/user/user.entity"

import Container, { Service } from "typedi"
import { UserService } from "./modules/user/user.service"

@Service()
class Seeds {
  constructor(private readonly userService: UserService) {}
  async create() {
    console.log("Creating seeds 🌱")
    await createDbConnection()
    const user1 = await User.create({
      email: "my-email-address@gmail.com",
      firstName: "First",
      lastName: "Last",
      password: "password",
    }).save()
  }
}

Container.get(Seeds)
  .create()
  .then(() => {
    console.log("Seeds created 🌳")
    process.exit()
  })
  .catch(err => {
    console.log(err.message)
    process.exit()
  })
`

**Migration generated for the User table**
`import {MigrationInterface, QueryRunner} from "typeorm";

export class CreateUserTable1571226867951 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying NOT NULL, "password" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "confirmed" boolean NOT NULL DEFAULT false, "role" "user_role_enum" NOT NULL DEFAULT 'user', CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP TABLE "user"`, undefined);
    }

}`

Strange Error, cannot find a solution. Kindly help.

Thanks

**Comment by imnotjames** [comment]
This looks like an environment issue.

For questions or general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
