### ISSUE TITLE
Object prototype may only be an Object or null: undefined at setPrototypeOf (<anonymous>)

### ISSUE THREAD

**Issue by alfredo-celso** [typeorm/typeorm#4919]
**Issue type:**

[ ] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**I would like to know what is causing this error:**
alfredo-celso@laptop /c/career-cxoss-main-fe (master)
$ npm start

> cx-onliner20@1.0.0 start C:\career-cxoss-main-fe
> ng serve --port=8080

An unhandled exception occurred: Object prototype may only be an Object or null: undefined
See "C:\Users\ALFRED~1\AppData\Local\Temp\ng-a2uzp3\angular-errors.log" for further details.
npm ERR! file C:\windows\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! cx-onliner20@1.0.0 start: `ng serve --port=8080`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the cx-onliner20@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alfredo-celso\AppData\Roaming\npm-cache\_logs\2019-10-17T13_45_34_859Z-debug.log

**The package.json file is the following:**
{
  "name": "cx-onliner20",
  "version": "1.0.0",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "ng build",
    "ci": "ng lint && ng test --code-coverage --browsers=ChromeHeadless --no-watch && ng build --prod",
    "e2e": "ng e2e",
    "lint": "ng lint",
    "postversion": "git push && git push --tags",
    "start": "ng serve --port=8080",
    "start:hmr": "ng serve --hmr --configuration=hmr",
    "test": "ng test",
    "version": "standard-changelog && git add -A CHANGELOG.md"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "dependencies": {
    "@angular-builders/custom-webpack": "^7.2.0",
    "@angular-builders/dev-server": "^7.2.1",
    "@angular-devkit/build-angular": "^0.803.10",
    "@angular-devkit/build-ng-packagr": "git+https://github.com/angular/angular-devkit-build-ng-packagr-builds.git",
    "@angular/animations": "8.2.0-next.2",
    "@angular/cli": "~8.1.2",
    "@angular/common": "8.2.0-next.2",
    "@angular/compiler": "8.2.0-next.2",
    "@angular/core": "8.2.0-next.2",
    "@angular/forms": "8.2.0-next.2",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "8.2.0-next.2",
    "@angular/platform-browser-dynamic": "8.2.0-next.2",
    "@angular/router": "8.2.0-next.2",
    "@okta/okta-angular": "^1.2.2",
    "@okta/okta-auth-js": "^2.8.0",
    "dotenv": "^6.2.0",
    "tslib": "^1.9.0"
  },
  "devDependencies": {
    "ajv": "^6.10.2",
    "@angular/compiler-cli": "~8.2.0-next.2",
    "@types/node": "~8.9.4",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.4.5"
  }
}

**Your support will be much appreciate it**
I am facing this error during 3 days and I am not able to find a solution.
Thank you

**Comment by imnotjames** [comment]
I don't see TypeORM in your dependencies, so I think this is unrelated.  As such, I'll be closing it.
