### ISSUE TITLE
Cant implement the many to many relation

### ISSUE THREAD

**Issue by httpsOmkar** [typeorm/typeorm#492]
Hey their Im trying to create the many to many relation. It works but only when the application is started on first time on second time it throws error
```
query failed: CREATE SCHEMA IF NOT EXISTS "public";CREATE TABLE "user_information_course_data_subjects_user_information_subjects_id" ("userInformationCourseDataId" uuid NOT NULL, "userInformationSubjectsId" uuid NOT NULL, PRIMARY KEY("userInformationCourseDataId", "userInformationSubjectsId"))
executing query: ROLLBACK
Error:  { error: relation "user_information_course_data_subjects_user_information_subjects" already exists
```

**Comment by httpsOmkar** [comment]
Right now I have fixed with the name option in JoinTable

**Comment by pleerock** [comment]
This sounds strange. I need sample git repo with reproduction of this problem.

**Comment by httpsOmkar** [comment]
Hello this happens because I have mentioned the name of the entity table in `@Entity('name')` when I restored this as default then after this works like a charm also this affect to the many many relation.
this wont work
```
@Entity('my_tab')
export class Something {
...
@ManyToMany(...)
@JoinTable()
something: Array<any>=[]
}
```

**Comment by pleerock** [comment]
First, try to reproduce your issue with latest `0.1.0-alpha.3` version. If everything is okay with this version then continue using it. If no, then create a minimal sample git repo with reproduction of this problem.
