### ISSUE TITLE
Use env var DATABASE_URL

### ISSUE THREAD

**Issue by antoine-pous** [typeorm/typeorm#4926]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `all`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)
[x] `any`

**Explanations:**
Actually we have to use exclusively `TYPEORM_URL` env var. But on Heroku apps the default env var is `DATABASE_URL`.

So i suggest to check for `TYPEORM_URL` env var if `DATABASE_URL` is not set, with that we have a system compliant with most of hosting providers without breaking changes.

_PS: I'm working on a PR for this issue_

**Comment by pupeno** [comment]
I'm thinking about how to deploy to Heroku and don't you run into other problems as well, such as defining entities, migrations, subscribers, etc. Do you set envvars for all of those in Heroku itself? Do you have a workaround for DATABASE_URL?

**Comment by imnotjames** [comment]
You can always read the environment variables yourself and `createConnection`.  For custom behavior like this that's your best bet.
