### ISSUE TITLE
XML parsing Dependency migration

### ISSUE THREAD

**Issue by amitguptagwl** [typeorm/typeorm#4927]
**Issue type:**

* [ ] question
* [ ] bug report
* [x] feature request
* [ ] documentation issue

#### Short description of the problem:
The current library we are using to parse XML into JS object gives incorrect results when it parses long XML. It is also slow. Here is the comparison;

![Benchmark](https://raw.githubusercontent.com/NaturalIntelligence/fast-xml-parser/master/static/img/fxpv3-vs-xml2jsv0419_chart.png)

#### What behavior are you expecting?
I would like to suggest to migrate to [fast-XML-parser](https://github.com/NaturalIntelligence/fast-xml-parser).

Here is the tabular representation.

file size |  fxp 3.0 parser (rps) | xml2js 0.4.19 (rps)
-- |  -- | --
1.5k  | 14032.09323 | 4615.930805
1.5m  | 13.23366098 | 5.90682005
13m  | 1.135582008 | -1
1.3k with CDATA  | 43160.52342 | 8398.556349
1.3m with CDATA  | 52.68877009 | 7.966000795
1.6k with cdata,prolog,doctype  | 41433.98547 | 7872.399268
98m  | 0.2600104004 | -1

As you can notice, in case of large file xml2js gives an error.

**Comment by imnotjames** [comment]
#6353 same as here - thanks for the suggestion but we should be fine for now
