### ISSUE TITLE
How to query relatons?

### ISSUE THREAD

**Issue by fookit** [typeorm/typeorm#4931]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

---

How do I query relations?

I'd like to query the author of post. 

Here's how I tried:
```ts
  async findAuthor({root: rootArg}: {root: Post}): Promise<User[]> {

    // Match post's author id with ids from user table
    const result = await User.find({where: {id: rootArg.author}})

    // Returns empty array
    console.log('@ RESULT HERE > ', result)

    // Return author
    return result;
  }
```

Previously with `Knex.js`:
```ts
    const result: User[] = await knex('user')
      .where('id', rootArg.author)
      .returning('*');
```

Also finding the a user's posts:
```ts
  // Find posts related to user
  async findPosts({root: rootArg}: {root: User}): Promise<Post[]> {

    // Match user's id with author id from post database
    const result = await Post.find({where: {author_id: rootArg.id}})

    // This returns all posts from db
   console.log('@ RESULT HERE > ', result)

    // Return posts
    return result;
  }
```

Previously with `Knex.js`:
```ts
    const result: Post[] = await knex('post')
      .where('author', rootArg.id)
      .returning('*');
```

Please help me.

Stack: TypeScript, Apollo-server-express, GraphQL

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
