### ISSUE TITLE
Missing SRID feature of MSSQL and suggested modification

### ISSUE THREAD

**Issue by ChiHang1221** [typeorm/typeorm#4936]
**Issue type:**

[ ] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
The SRID feature is not properly implemented for MSSQL. 
The original implementation cause rejection if SRID constraint is implemented in SQL server.
I added the following code to `typeorm/query-builder/UpdateQueryBuilder.js` after line 369.
After modification, it works.

Codes:
`else if (_this.connection.driver instanceof SqlServerDriver_1.SqlServerDriver && _this.connection.driver.spatialTypes.indexOf(column.type) !== -1) {
                            expression = column.type + "::STGeomFromText(" + _this.connection.driver.createParameter(paramName, parametersCount) + ", " + (column.srid||"0") + ")";
                        }`

**Comment by waikuen2010** [comment]
We encounter the same issue in our project. The problem actually affect update of geometry column also.  

I have submitted a PR #4936 fixing the problem. However the CI fail and I have no idea why. Can somebody help to review and merge the PR.  

Currently we have to monkey patch all of our projects to use typeorm with mssql.

**Comment by imnotjames** [comment]
#5947 was merged which should have fixed this
