### ISSUE TITLE
Typeorm does not rename sequence of PK on renaming of table

### ISSUE THREAD

**Issue by yaroslavyal** [typeorm/typeorm#4937]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. Create `Table1` with primary key id as serial type
2. Run cli command
```
typeorm migration:create -n RenameTable1
```
3. Write on migration
```
queryRunner.renameTable('Table1', 'Table2')
```
4. Run cli command
```
typeorm migration:generate -n CheckActualShema
```
Expected result - new migration is not generated.
Actual result - migration is generated.
```
await queryRunner.query(
      `CREATE SEQUENCE "Table2_id_seq" OWNED BY "Table2"."id"`
    )
    await queryRunner.query(
      `ALTER TABLE "Table2" ALTER COLUMN "id" SET DEFAULT nextval('Table2_id_seq')`
    )
    await queryRunner.query(
      `ALTER TABLE "Table2" ALTER COLUMN "id" DROP DEFAULT`
    )
```

**Comment by pconerly** [comment]
I'm getting this bug too! :-/

**Comment by fullc0de** [comment]
I also met this issue. and I found that `renameTable` method doesn't care of renaming the sequence name related to the target table. I'm not sure if that is intended or not. As you can see, any follow-up from the authors couldn't be expected because they don't have enough time to do. :-( I think, therefore, there are two options as follows.

1) Fork the project and modify the method in order to match up your need.
2) Wait for any response from the authors. In the meantime, write additional query by using `queryRunner` to do manually what you want.

**Comment by pconerly** [comment]
@fullc0de We could also modify the method and submit a PR to this repo? The typeorm authors are busy, but I hope they would accept a well-done PR.

**Comment by fullc0de** [comment]
That's good idea even though there are many PRs already stacked. :-) I will go through relevant code to it again.

**Comment by fullc0de** [comment]
fixed this issue only for PostgreSQL. 
https://github.com/fullc0de/typeorm/commit/e2dc798dce3623e744d3ae80de99875dcf456f60

**Comment by GarryOne** [comment]
A node script to fix all tables in postgres.

```
const pg = require('pg');
const { Client } = pg;

const updateTables = async () => {

  const client = new Client({
    user: 'postgres',
    host: 'localhost',
    database: 'my-database',
    password: 'postgres',
    port: 5432,
  });

  await client.connect();

  console.log('Connected');

  const execQuery = async (queryStr, params = []) => {
    return new Promise((resolve, reject) => {
      client.query(queryStr, params, (error, results) => {
        if (error) {
          reject(error);
        } else {
          resolve(results);
        }
      })
    })
  }

  const tablesRes = await execQuery(`
    SELECT table_name
    FROM information_schema.tables
    WHERE table_type='BASE TABLE'
    AND table_schema='public';
  `)

  const tables = tablesRes.rows.map(row => row.table_name);

  tables.map(async tableName => {
    let lastId;
    try {
      const res = await execQuery(`SELECT id from "${tableName}" ORDER BY id DESC LIMIT 1`);
      lastId = res.rows[0].id;
    } catch (e) {}

    if (lastId) {
      const nextId = lastId + 1;
      const queryStr = `ALTER SEQUENCE ${tableName}_id_seq RESTART WITH ${nextId}`;
      await execQuery(queryStr);
      console.log(tableName, queryStr);
    }
  })

};

updateTables();
```
