### ISSUE TITLE
@Index and module paths developing on case insensitive environments

### ISSUE THREAD

**Issue by StrikeForceZero** [typeorm/typeorm#494]
Developing on windows and using intellij. When using Decorators I can usually type them out, `alt` + `enter` and import the module automatically. Unfortunately under windows, it defaults to `typeorm/decorator` when it should be `typeorm/decorator/Index`. Everything will still work as intended until you switch to a case sensitive file system and receive this:

```
TS2307: Cannot find module 'typeorm/decorator'.
```

I'm not even sure this can be fixed, without renaming the file to not collide with a default import looking for `index.ts`

**Comment by pleerock** [comment]
It looks like some bug in IDE. AFAIK there is no such issue in latest webstorm. Try webstorm since it has latest typescript improvements fixes.

**Comment by StrikeForceZero** [comment]
It's not an issue with the ide. I'm always using EAP or latest version of intellij. It's the way modules are resolved. If you specify a folder it defaults to an index file or package.json. since Windows is using a case insensitive filesystem these 3 imports all work the same:

`import { Index } from 'typeorm/decorators/Index`
`import { Index } from 'typeorm/decorators/index`
`import { Index } from 'typeorm/decorators`

On a case sensitive filesystem these imports fail:

`import { Index } from 'typeorm/decorators`
`import { Index } from 'typeorm/decorators/index`

**Comment by StrikeForceZero** [comment]
I mean I guess I could blame the IDE somewhat since it was the one that chose to import it that way...

**Comment by pleerock** [comment]
Of course you should blame IDE. This is how they are trying to automatically guess where from they should import. And their algorithms should be improved and  take in count if file name is `Index`. Also `Index` is already exported in `typeorm/index` so they probably should not go deeper and try to find something in `typeorm/decorator`

**Comment by StrikeForceZero** [comment]
True. Apologies if I came off hostile at all. I should leave replies for normal functioning hours heh.. I initially read your first response as if you ignored the filesystem case sensitivity point I brought up, but you're right. The more I think about it, the IDE is completely at fault here. I'll give webstorm a go just out of curiosity. And maybe open a ticket on the webstorm youtrack if it still exhibits the behavior.

**Comment by StrikeForceZero** [comment]
Same issue under latest version of webstorm

Opened [WEB-27099](https://youtrack.jetbrains.com/issue/WEB-27099) and [WEB-27098](https://youtrack.jetbrains.com/issue/WEB-27098)

**Comment by rightisleft** [comment]
I'm seeing this as well

**Comment by rightisleft** [comment]
The above work around worked fine - but it seems to only occur on my builder server

[go] Task: tsctook: 1.575sexited: 2
src/fish/dtos/document.dto.ts(5,21): error TS2307: Cannot find module 'typeorm/decorator'.

Just food for thought...

**Comment by vecernik** [comment]
import { Index } from "typeorm/decorator/Index"
works on case-sensitive fs.

**Comment by adrianhara** [comment]
Yea, but why do we need to import from /Index, per @pleerock 's comment, we shouldn't need that? 

For me it also works locally (macos) but fails on build server (bitbucket pipeline) if I do just import from 'typeorm/decorator', however if i do import from 'typeorm/decorator/Index' it will work on  the build server as well.

**Comment by vecernik** [comment]
exactly, because macos fs is case-insensitive by default: 
$ ls -l node_modules/typeorm/decorator/index.js
but on macosx:
$ ls -l node_modules/typeorm/decorator/ | grep -i index
