### ISSUE TITLE
getRepository(EntityClassName) returns repository for incorrect entity

### ISSUE THREAD

**Issue by silentroach** [typeorm/typeorm#4940]
Introduced in version 0.2.20 with #4804.

Now, when you have different entities with the same classname, `connection.getRepository` will return first by class **name** instead of **class pointer** comparison (like it was before 0.2.20)

Steps to reproduce: just describe two entities with the same classname in different directories.

**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Comment by pleerock** [comment]
I was aware of this issue, but still merged because I thought it's a rare case when people have entities with same class names. We need to figure out some solution that would work both on serverless and non-serverless environment. On serverless we can't rely on different class instances, we need some unique identifier like entity name. What is your use case of having same class names?

**Comment by pleerock** [comment]
I guess you have same class names, but different table names?

**Comment by silentroach** [comment]
In my case I have `UserEntity` for different cases (for authentication with hash fields) and for others without it.

And I can imagine if somebody have structure like `[app]/user/Entity.ts`, `[app]/post/Entity.ts`.

**Comment by pleerock** [comment]
but these entities if they are using same table can't go into same connection, right?

**Comment by silentroach** [comment]
why not?

**Comment by pleerock** [comment]
what is the point?

**Comment by fiendfiend** [comment]
The use case that we are facing where this is problematic is the same entity name in different schemas on Postgres.

Since it is possible to have such a setup on Postgres, you could simply include the schema name as part of the key to uniquely identify the entities.

**Comment by silentroach** [comment]
no, it just should be reverted

**Comment by smallg** [comment]
@silentroach What about this issue? fixed it?

**Comment by silentroach** [comment]
@smallg discussion moved to #4967

**Comment by smallg** [comment]
@silentroach in 4967, i can not found solution, i used different class name and table name

**Comment by silentroach** [comment]
@smallg there is no solution yet
