### ISSUE TITLE
calculation of exec time per call

### ISSUE THREAD

**Issue by binarytracer** [typeorm/typeorm#4946]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] `0.x.x` (0.2.20)

**Steps to reproduce or a small repository showing the problem:**

**Question:** How to get exec time on every db calls ( especially find/fetch ) in typeORM?

Findings so far: 
- I managed to read queries as [indicated here](https://typeorm.io/#/logging/using-custom-logger) but it has no exec time.
- Checked also [listeners-and-subscribers](https://typeorm.io/#/listeners-and-subscribers) i think i can measure there all write operations but not for find/fetch calls. 
- Considering currently using this [accessing parent class methods](https://stackoverflow.com/questions/13121431/accessing-member-of-base-class), Do you have similar example on this implementation?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
