### ISSUE TITLE
beforeUpdate subscriber entity argument is undefined

### ISSUE THREAD

**Issue by simpert** [typeorm/typeorm#4947]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `typeorm@0.2.19` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
@EventSubscriber()
export class UpdateModifiedSubscriber implements EntitySubscriberInterface {
    beforeUpdate ( event: UpdateEvent<any> ) {
        if ( ( event.entity as IEntityBase ) != null )
            ( event.entity as IEntityBase ).dateModified = new Date();
    }

    beforeInsert ( event: InsertEvent<any> ) {
        if ( ( event.entity as IEntityBase ) != null )
            ( event.entity as IEntityBase ).dateModified = new Date();
    }
}

export interface IEntityBase {
    id?: string;
    dateModified?: Date;
}

export abstract class EntityBase<T> implements IEntityBase {
    constructor ();
    constructor ( entity: Partial<T> );
    constructor ( entity?: any ) {
        if ( !entity ) return;

        for ( const key in entity )
            this[ key ] = entity[ key ];
    }

    @PrimaryGeneratedColumn( 'uuid' )
    id: string;

    @Column( { type: dateTimeType(), nullable: true } )
    dateModified: Date;
}

@Entity( 'Player' )
export class Player extends EntityBase<IPlayer> implements IPlayer {
    @Column( { type: 'nvarchar', length: 20, nullable: false } )
    firstName: string;

    @Column( { type: 'nvarchar', length: 20, nullable: false } )
    lastName: string;

    @Column( { type: 'integer', nullable: false } )
    jerseyNumber: number;

    @Column( { type: 'integer', nullable: false } )
    weight: number;

    @Column( { type: 'text', nullable: true } )
    stats?: string;

    @Column( { nullable: false } )
    teamId: string;

    /**
     * The players complete name
     *
     * @readonly
     * @memberof Player
     */
    get fullName () { return `${ this.firstName } ${ this.lastName }`; }
}

    async update ( playerId: string, player: Partial<Player> ): Promise<boolean> {
        // test that the a record to update exists in the database
        let existingPlayer: Player;
        try {
            existingPlayer = await this
                .connection
                .getRepository( Player )
                .findOneOrFail( playerId );
        } catch ( error ) {
            throw new BadRequest( error );
        }

        try {
            if ( process.env.DATABASE_TYPE && process.env.DATABASE_TYPE == 'sqlite' ) {
                Object.keys( player ).forEach( prop => {
                    if ( existingPlayer.hasOwnProperty( prop ) )
                        existingPlayer[ prop ] = player[ prop ];
                } );
                // I absolutely do NOT like this. It smells to me. However, I wonder if sql server driver eventually does
                // the same thing here with output clause by select query after the update.
                let updateResult = await this.connection
                    .getRepository( Player )
                    .update( playerId, existingPlayer );
                // await this.connection
                //     .createQueryBuilder()
                //     .update( Player )
                //     .set( player )
                //     .where( "id = :id", { id: playerId } )
                //     .execute();

                let updatedPlayer = await this
                    .connection
                    .getRepository( Player )
                    .findOne( playerId );

                return isMatch( updatedPlayer, player );
            } else {
                // so we are going to use mssql output clause to return updated cols and values then test that instead of 
                // running seperate additional select query to see if all updated cols were success
                let result = await this.connection
                    .createQueryBuilder()
                    .update( Player )
                    .set( player )
                    .where( "id = :id", { id: playerId } )
                    .output( Object.keys( player ) )
                    .execute();

                if ( result.raw && result.raw.length > 0 )
                    return isEqual( result.raw[ 0 ], player );
            }
        } catch ( error ) {
            throw new BadRequest( error );
        }

        return false;
    }
```

The update method shows a few different things I have tried in order to perform the partial update.  I would expect the commented out querybuilder code to work. I understand I can result to using the `save` repo method but I would like the partial support and optimized primitive query. I tried `mssql` driver and it works as expected. It is also much more convenient as you can see the code simply need just test the update query results to see if update was a success. However, I must use `sqlite` and I understand there is no output clause. To test if success update I am selecting the record after the update then testing that. All the `beforeInsert` subscribers work as expected however the `beforeUpdate` doesn't pass the event.entity and therefore I cannot update the `dateModified`.   

![2019-10-21 (1)](https://user-images.githubusercontent.com/2422222/67256493-9407bf80-f444-11e9-9316-06139dd16bf3.png)

Is there a different or better way to do this. I absolutely love `typeorm` and will work around this issue, however, it would be nice to have more concise partial update code to implement `expressjs` server patch routes. I have not had the time to scour the `queryRunner` `manager` or `metadata` and it is not clear to me what if any I can update in order to pass the new date to the query in the subscriber method.

I apologize for the example code not being complete and I hope there is enough there to see the issue. I tried the beforeUpdate subscriber in a older project where I also used typeorm and the same issue exists. I wondered if the metadata of the inheritance and stuff might of been a issue. 

I will try to write some tests for the listeners soon and will update here on that or offer a PR.

**Comment by xlxAciDxlx** [comment]
I can confirm this bug on both the latest TypeORM version (0.2.20), as well as on the `next` version (0.3.0-alpha.24). I'd provide sample code, but it's as simple as just setting up the `beforeUpdate` and `afterUpdate` subscriber events, logging their output, and seeing that the `entity` and `databaseEntity` are both undefined.

**Comment by xlxAciDxlx** [comment]
So, at least in my case, this seems like a really odd issue. When running in debug mode in Visual Studio Code, the entities _ARE_ properly set. However, when I run the exact same code in Node or Nodemon the entities aren't set.

**Comment by xlxAciDxlx** [comment]
@simpert Sorry for the mention, but I'm unfortunately still encountering this and was wondering if you have had any luck figuring out why it might be happening, or have you found a workaround? Thanks!

**Comment by or313** [comment]
Any progress on this one? Im encountering the same thing

**Comment by xlxAciDxlx** [comment]
I've tried to figure out what might be causing it so I could fix it and submit a PR myself, but I've had no luck yet. 

@pleerock Sorry for the tag, but any chance you could look into this?

**Comment by simpert** [comment]
@xlxAciDxlx and @or313 I went a different route when coming across the bug and so I did not investigaate all that much. I really needed the subscribers to work. I want to help though so I poked around the source a bit and discovered that the entity instance is not being passed to the subscribers beforeUpdate event object.
```
var executionResult = subscriber.beforeUpdate({
                        connection: _this.queryRunner.connection,
                        queryRunner: _this.queryRunner,
                        manager: _this.queryRunner.manager,
                        entity: entity,
                        metadata: metadata,
                        databaseEntity: databaseEntity,
                        updatedColumns: updatedColumns || [],
                        updatedRelations: updatedRelations || []
                    })
```  
this is because the entity is not be passed into the `Broadcaster.broadcastBeforeUpdateEvent` function. Further up, the `UpdateQueryBuilder.execute` function is the culprit. It has the entity object that is being updated but fails to pass it to the broadcasters `broadcastBeforeUpdateEvent`.  

I debugged and confirmed this. I found the entity to be updated to be stored in the query builders `this.expressionMap.valuesSet` member.  Also, I simply updated the code on line 68 to pass in the entity and this seams to work fine.
`queryRunner.broadcaster.broadcastBeforeUpdateEvent(broadcastResult, this.expressionMap.mainAlias.metadata, this.expressionMap.valuesSet);`

All in all, it appears that maybe the feature was not finished but this is just one devs 2cents on it.

However, I do not have the time Today to create a PR and write some tests but knowing this little change for a fix I hope this helps you. I may have time to work on it further this weekend.

**Comment by or313** [comment]
@simpert Thank you for the response!
What did you ended up doing in order for the subscribers to work in your environment?
I mean, i cannot change the source code and a PR process could take a while.. i really need those subscribers too.

Maybe im missing another solution to my problem but i intend to use those after subscribers in order to write the changes to an audit table to save the history.. any other ideas in for that matter?

Thank you in advance

**Comment by xlxAciDxlx** [comment]
I wonder if something like `patch-package` would work for a temporary workaround while maintaining a "proper" fix locally? Basically you can modify a file in your `node_modules`, run `patch-package [package-name]` and it'll generate a `.patch` file that will be executed and patched after you run `npm i` or `yarn`, `yarn install`, etc.

I've tried looking through the compiled source to figure out where to apply the patch you mentioned @simpert , but I can't seem to find the exact line (not sure if you were mentioning changes in source files or the compiled files). If you can point me to maybe the line that needs changing in the generated code, I'll gladly generate a patch and share it here so we can all benefit from it as I also need subscribers (I'm kinda relying on them to tie my backend to my frontend).

**Comment by xlxAciDxlx** [comment]
So I finally tracked down the lines I needed to change and was able to locally fix the issue :)

### _NOTE:_ I'm NOT sure this will work universally for everyone, but it _MAY_ work as a temporary workaround. I do plan to attempt to do a proper PR today if I get the chance.

### _NOTE:_ This is for version `0.2.22` of `TypeORM`, I'm not sure if this will work or break with other versions!

For those that want to try using `patch-package` (how I was able to fix it for now), follow these steps:
- Install `patch-package` globally (or locally in your project, not sure if it matters but I've installed it globally and locally)
- Create `patches/typeorm+0.2.22.patch` (in your root project directory. I,e [rootDir]/patches/typeorm+0.2.22.patch`) with the following contents:
```patch
diff --git a/node_modules/typeorm/query-builder/UpdateQueryBuilder.js b/node_modules/typeorm/query-builder/UpdateQueryBuilder.js
index 01e7760..9926e1f 100644
--- a/node_modules/typeorm/query-builder/UpdateQueryBuilder.js
+++ b/node_modules/typeorm/query-builder/UpdateQueryBuilder.js
@@ -67,7 +67,8 @@ var UpdateQueryBuilder = /** @class */ (function (_super) {
                     case 3:
                         if (!(this.expressionMap.callListeners === true && this.expressionMap.mainAlias.hasMetadata)) return [3 /*break*/, 5];
                         broadcastResult = new BroadcasterResult_1.BroadcasterResult();
-                        queryRunner.broadcaster.broadcastBeforeUpdateEvent(broadcastResult, this.expressionMap.mainAlias.metadata);
+                        // Fix beforeUpdate subscriber
+                        queryRunner.broadcaster.broadcastBeforeUpdateEvent(broadcastResult, this.expressionMap.mainAlias.metadata, this.expressionMap.valuesSet);
                         if (!(broadcastResult.promises.length > 0)) return [3 /*break*/, 5];
                         return [4 /*yield*/, Promise.all(broadcastResult.promises)];
                     case 4:
@@ -103,7 +104,8 @@ var UpdateQueryBuilder = /** @class */ (function (_super) {
                     case 8:
                         if (!(this.expressionMap.callListeners === true && this.expressionMap.mainAlias.hasMetadata)) return [3 /*break*/, 10];
                         broadcastResult = new BroadcasterResult_1.BroadcasterResult();
-                        queryRunner.broadcaster.broadcastAfterUpdateEvent(broadcastResult, this.expressionMap.mainAlias.metadata);
+                        // Fix afterUpdate subscriber
+                        queryRunner.broadcaster.broadcastAfterUpdateEvent(broadcastResult, this.expressionMap.mainAlias.metadata, this.expressionMap.valuesSet);
                         if (!(broadcastResult.promises.length > 0)) return [3 /*break*/, 10];
                         return [4 /*yield*/, Promise.all(broadcastResult.promises)];
                     case 9:
```
- Add the following to the "scripts" section of your `package.json`:
```json
"postinstall": "patch-package"
```
- Run `yarn`/`yarn install` or `npm i`
  - In Yarn, you should see something like the following:
```json
yarn install v1.21.1
[1/4] Resolving packages...
success Already up-to-date.
$ patch-package
patch-package 6.2.0
Applying patches...
typeorm@0.2.22 ✔
```
- Run things how you normally do, if you log the `entity` value from the `beforeUpdate` or `afterUpdate` you should see the changes you made in the returned object
  - NOTE: It does not seem to populate the `databaseEntity`, not sure if there's a way to do that or not

**Comment by simpert** [comment]
> NOTE: It does not seem to populate the databaseEntity, not sure if there's a way to do that or not

@xlxAciDxlx the `databaseEntity` is expected as a paramter to the `broadcastBeforeUpdateEvent` just aftter the entity. I just debugged the update to discover what was available in the QueryBuilder as far as state. I found the `metadata` to be quite large and so it may contain the database entity. As it seams the subscriber update feature was not completed, you may just need to find the `databaseEntity` object and patch to pass it in to the `broadcastBeforeUpdateEvent` just after the entity object.  

Hope this helps. As for a PR, if you would like any help with that and perhaps to fully complete the feature, I can help this next weekend. Just let me know. I am just really busy during the week.

**Comment by or313** [comment]
@xlxAciDxlx This looks interesting, I'll give it a go first thing tommorow morning.
I think we should defently persue a PR on this and I will love to give a hand on this so let me know.

**Comment by xlxAciDxlx** [comment]
> the `databaseEntity` is expected as a paramter to the `broadcastBeforeUpdateEvent` just aftter the entity.

Ahh okay. I wasn't sure what the expected arguments were since I was modifying the contents inside of `node_modules` so I didn't have IntelliSense.

> Hope this helps. As for a PR, if you would like any help with that and perhaps to fully complete the feature, I can help this next weekend. Just let me know. I am just really busy during the week.

It definitely has! I'll hopefully get around to taking a stab at a PR tomorrow morning. My eventual goal is to properly PR this obviously, but I just wanted to get it up and running since you had thankfully given me some sort of direction or hope that this was fixable.

I should be able to at least start on the PR, and at the very least can make some progress so either of you can pick it up and finish off anything I might not be able to figure out. I'm hoping that working with the actual source where I'll have IntelliSense will make things a bit easier. :) haha

**Comment by simpert** [comment]
@xlxAciDxlx and @or313 can use branch in https://github.com/typeorm/typeorm/pull/5443 PR if need. The PR only addresses the `entity` object and not the `databaseEntity` however, I was thinking the PR might be helpful for one of you to reference to create a PR for the additional data in the subscriber event if needed. There is also a `afterUpdate` that could probably use the entity object as well. I created the first PR and ran into many issues on my side getting my editor to not format so weird so the checks would not pass. I ended up creating a new PR after closing the first and using notepadd++ to do it all.

Finally, I do not have the means to install so many different databases (nor do I want to) in order to run all tests locally. I have mongoose and sqlserver installed so was able to run those and the sqlite tests but did not run others. This might prevent PR from progressing so if one of you guys have the means and will to lobby it through that would be great.

**Comment by xlxAciDxlx** [comment]
Awesome, I'll look into it! I also don't have _all_ of the needed databases for the tests to pass, though from the little I did in my PR (pretty much the same you had done, minus the tests) they were already failing for me early on lol

Also, I've looked through just about every logical spot I could think of to find the `databaseEntity` value, and, unless I'm missing it, I have _no clue_ where it could be coming from. So, unfortunately, I don't think there's much I could contribute via the PR.

**Comment by or313** [comment]
@xlxAciDxlx  @simpert Hey guys!
Ive decided to try and solve our problem using the patch-package method as it seems to work fine as a mid way solution.
Up until this point i was able to add the entityID into the afterRemove event as well as the actual entity.
Same as simpert i was not able to find the databaseEntity anywhere that i can add it to the events, I did try to add it to the Subject class which as i understand acts as a middleware between the actual transaction to the EventSubscriber.

Before we get into tests and other time consuming things lets try and see if we can actually solve this this. here is my patch:
`diff --git a/node_modules/typeorm/browser/subscriber/Broadcaster.js b/node_modules/typeorm/browser/subscriber/Broadcaster.js
index c63d14e..e357706 100644
--- a/node_modules/typeorm/browser/subscriber/Broadcaster.js
+++ b/node_modules/typeorm/browser/subscriber/Broadcaster.js
@@ -194,6 +194,7 @@ var Broadcaster = /** @class */ (function () {
                         entity: entity,
                         metadata: metadata,
                         databaseEntity: databaseEntity,
+                        entityId: metadata.getEntityIdMixedMap(databaseEntity),
                         updatedColumns: updatedColumns || [],
                         updatedRelations: updatedRelations || []
                     });
diff --git a/node_modules/typeorm/persistence/SubjectExecutor.js b/node_modules/typeorm/persistence/SubjectExecutor.js
index 2bd1ae6..c3d8d3b 100644
--- a/node_modules/typeorm/persistence/SubjectExecutor.js
+++ b/node_modules/typeorm/persistence/SubjectExecutor.js
@@ -175,7 +175,7 @@ var SubjectExecutor = /** @class */ (function () {
         var _this = this;
         var result = new BroadcasterResult_1.BroadcasterResult();
         if (this.insertSubjects.length)
-            this.insertSubjects.forEach(function (subject) { return _this.queryRunner.broadcaster.broadcastAfterInsertEvent(result, subject.metadata, subject.entity); });
+            this.insertSubjects.forEach(function (subject) { return _this.queryRunner.broadcaster.broadcastAfterInsertEvent(result, subject.metadata, subject.entity, subject.databaseEntity); });
         if (this.updateSubjects.length)
             this.updateSubjects.forEach(function (subject) { return _this.queryRunner.broadcaster.broadcastAfterUpdateEvent(result, subject.metadata, subject.entity, subject.databaseEntity, subject.diffColumns, subject.diffRelations); });
         if (this.removeSubjects.length)
diff --git a/node_modules/typeorm/query-builder/DeleteQueryBuilder.js b/node_modules/typeorm/query-builder/DeleteQueryBuilder.js
index b615a09..8544406 100644
--- a/node_modules/typeorm/query-builder/DeleteQueryBuilder.js
+++ b/node_modules/typeorm/query-builder/DeleteQueryBuilder.js
@@ -60,7 +60,8 @@ var DeleteQueryBuilder = /** @class */ (function (_super) {
                     case 3:
                         if (!(this.expressionMap.callListeners === true && this.expressionMap.mainAlias.hasMetadata)) return [3 /*break*/, 5];
                         broadcastResult = new BroadcasterResult_1.BroadcasterResult();
-                        queryRunner.broadcaster.broadcastBeforeRemoveEvent(broadcastResult, this.expressionMap.mainAlias.metadata);
+                        // fix for BeforeRemoveEvent
+                        queryRunner.broadcaster.broadcastBeforeRemoveEvent(broadcastResult, this.expressionMap.mainAlias.metadata, this.expressionMap.valuesSet);
                         if (!(broadcastResult.promises.length > 0)) return [3 /*break*/, 5];
                         return [4 /*yield*/, Promise.all(broadcastResult.promises)];
                     case 4:
@@ -89,7 +90,8 @@ var DeleteQueryBuilder = /** @class */ (function (_super) {
                         }
                         if (!(this.expressionMap.callListeners === true && this.expressionMap.mainAlias.hasMetadata)) return [3 /*break*/, 8];
                         broadcastResult = new BroadcasterResult_1.BroadcasterResult();
-                        queryRunner.broadcaster.broadcastAfterRemoveEvent(broadcastResult, this.expressionMap.mainAlias.metadata);
+                        // Fix for AfterRemove
+                        queryRunner.broadcaster.broadcastAfterRemoveEvent(broadcastResult, this.expressionMap.mainAlias.metadata, this.expressionMap.valuesSet);
                         if (!(broadcastResult.promises.length > 0)) return [3 /*break*/, 8];
                         return [4 /*yield*/, Promise.all(broadcastResult.promises)];
                     case 7:
diff --git a/node_modules/typeorm/query-builder/UpdateQueryBuilder.js b/node_modules/typeorm/query-builder/UpdateQueryBuilder.js
index 01e7760..9926e1f 100644
--- a/node_modules/typeorm/query-builder/UpdateQueryBuilder.js
+++ b/node_modules/typeorm/query-builder/UpdateQueryBuilder.js
@@ -67,7 +67,8 @@ var UpdateQueryBuilder = /** @class */ (function (_super) {
                     case 3:
                         if (!(this.expressionMap.callListeners === true && this.expressionMap.mainAlias.hasMetadata)) return [3 /*break*/, 5];
                         broadcastResult = new BroadcasterResult_1.BroadcasterResult();
-                        queryRunner.broadcaster.broadcastBeforeUpdateEvent(broadcastResult, this.expressionMap.mainAlias.metadata);
+                        // Fix beforeUpdate subscriber
+                        queryRunner.broadcaster.broadcastBeforeUpdateEvent(broadcastResult, this.expressionMap.mainAlias.metadata, this.expressionMap.valuesSet);
                         if (!(broadcastResult.promises.length > 0)) return [3 /*break*/, 5];
                         return [4 /*yield*/, Promise.all(broadcastResult.promises)];
                     case 4:
@@ -103,7 +104,8 @@ var UpdateQueryBuilder = /** @class */ (function (_super) {
                     case 8:
                         if (!(this.expressionMap.callListeners === true && this.expressionMap.mainAlias.hasMetadata)) return [3 /*break*/, 10];
                         broadcastResult = new BroadcasterResult_1.BroadcasterResult();
-                        queryRunner.broadcaster.broadcastAfterUpdateEvent(broadcastResult, this.expressionMap.mainAlias.metadata);
+                        // Fix afterUpdate subscriber
+                        queryRunner.broadcaster.broadcastAfterUpdateEvent(broadcastResult, this.expressionMap.mainAlias.metadata, this.expressionMap.valuesSet);
                         if (!(broadcastResult.promises.length > 0)) return [3 /*break*/, 10];
                         return [4 /*yield*/, Promise.all(broadcastResult.promises)];
                     case 9:
diff --git a/node_modules/typeorm/subscriber/Broadcaster.js b/node_modules/typeorm/subscriber/Broadcaster.js
index f960b9d..8164397 100644
--- a/node_modules/typeorm/subscriber/Broadcaster.js
+++ b/node_modules/typeorm/subscriber/Broadcaster.js
@@ -196,6 +196,7 @@ var Broadcaster = /** @class */ (function () {
                         entity: entity,
                         metadata: metadata,
                         databaseEntity: databaseEntity,
+                        entityId: metadata.getEntityIdMixedMap(databaseEntity),
                         updatedColumns: updatedColumns || [],
                         updatedRelations: updatedRelations || []
                     });
`

Let me know what you think and how we should proceed from here

**Comment by rossi-jeff** [comment]
is it possible to add entityId to UpdateEvent as in RemoveEvent so that in cases where entity / databaseEntity are undefined they could be loaded in the subscriber?

**Comment by xlxAciDxlx** [comment]
Admittedly, at least from what I can tell by looking at the commit history for the subscriber files, it looks like this was definitely not a finished feature - or at least was last modified quite some time ago. I'm not sure what the proper handling of this is, as I'm just learning how the data is getting passed around in trying to fix this bug.

While we _could_ technically do what you suggested @rossi-jeff , I'm not entirely sure what the proper/desired way of handling it is. I feel like the `entity` and `databaseEntity` should always be available by this point, it's just figuring out _where_ that's been the main blocking thing (at least for myself).

**Comment by simpert** [comment]
> is it possible to add entityId to UpdateEvent as in RemoveEvent so that in cases where entity / databaseEntity are undefined they could be loaded in the subscriber?

So the PR for this issue resolves the entity obj being undefined in the `beforeUpdate` event object. The entity object was being passed in other events like insert so I think it may have just been an oversight. Anyhow, it seams that this issue only exist's when using the repositories. What I mean by that is if using the `connection.manager.save(entity)` the entity object is passed to the subscriber. I found that there are many oversights in the queryBuilder's. Entity is not being forwarded to subscribers in many of the events such as `afterUpdate` etc. The fixes are really simple though. I think there need be another issue raised and separate PR for fixing all of them. This issue only describes entity not being forwarded in the `beforeUpdate` handler of subscribers.

Further, it seams the `databaseEntity` is not being passed in much of any of them. I have not been able to think of a use case for it either. Perhaps if your entities are structured and named much differently then the database tables? However, seams to me the entity object being updated is necessary in the `beforeUpdate` subscriber handler since it seams modifying the entity may be the whole reason why one would want the subscriber. 

There is a work around it seams by using the `connection manager` methods rather then the repos. For an example there is some tests here `test\other-issues\entity-change-in-subscribers\entity-change-in-subscribers.ts` that show this. 

Feel free to use the branch with this issues fix https://github.com/simpert/typeorm/tree/fix-issue-4947 . It seams there is alot of PR's in this repo so there is no idea when or if the PR will be merged. After reading the pinned issues I think the repo maintainers may be on a break.

**Comment by simpert** [comment]
@xlxAciDxlx if it help's, the `src\persistence\SubjectExecutor.ts` class `broadcastBeforeEventsForAll` function is the only function in the project that properly calls the `beforeUpdate` subscriber handler with appropriate arguments. This should help to determine what data should be passed in the `databaseEntity` param.

Further, the `src\persistence\Subject.ts` describes the data via comments.
```
/**
 * Subject is a subject of persistence.
 * It holds information about each entity that needs to be persisted:
 * - what entity should be persisted
 * - what is database representation of the persisted entity
 * - what entity metadata of the persisted entity
 * - what is allowed to with persisted entity (insert/update/remove)
 *
 * Having this collection of subjects we can perform database queries.
 */
export class Subject {}
```  
Also, the `src\persistence\EntityPersistExecutor.ts` `execute` function shows the subjects being created.

Hope it helps. 🤞

**Comment by simpert** [comment]
Further investigation I realize via the repositoies the save function goes through the `EntityPersistExecutor` which properly creates `Subject` instances and passes everything to subscribers correctly, however, the udpate function goes through the `queryBuilder` instead.

**Comment by simpert** [comment]
@xlxAciDxlx right now I am using the https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter VS Code extension to run and debug the tests in this project. There are so many tests and test dependencies so I found that limiting the scope helps. I know there are much easier ways to debug mocha tests but the extention makes it pretty trivial and allows debugging right in Code. To limit the scope I just configure the ext in Code workspace settings with:
```
{
    "mochaExplorer.files": [
        "test/github-issues/4947/issue-4947.ts",
    ],
    "mochaExplorer.envPath": "",
    "mochaExplorer.timeout": 60000,
    "mochaExplorer.require": "ts-node/register",
    "mochaExplorer.logpanel": true,
}
```  
then you can just set a breakpoint in the test and click debug. 

This way you can view the data that is available in the subscribers or anywhere else. 
![2020-02-01](https://user-images.githubusercontent.com/2422222/73599125-56173e80-44fd-11ea-873d-363a88b6b0fe.png)  

![2020-02-01 (1)](https://user-images.githubusercontent.com/2422222/73599132-5c0d1f80-44fd-11ea-862c-377e2b357871.png)

**Comment by pedroaraujo1952** [comment]
I have the same issue for `beforeRemove` and `afterRemove`
