### ISSUE TITLE
How to UPDATE in a transaction. 

### ISSUE THREAD

**Issue by Ericnr** [typeorm/typeorm#4953]
I'm probably missing something, but I don't see any examples and can't figure out how to update or use the `queryBuilder` inside a transaction. Docs tell me to use the `transactionalEntityManager` to save my entities but when I invoke `User.update()` or the query builder there's no need to `.save()`. How do I do it?

**Comment by mamhaidly** [comment]
did you find anything?

**Comment by Ericnr** [comment]
@mamhaidly you can do `transactionManager.update(User, { id: 1}, { name: newName })`

**Comment by arieuu** [comment]
> @mamhaidly you can do `transactionManager.update(User, { id: 1}, { name: newName })`

Thank you
