### ISSUE TITLE
TypeORM 0.2.20 getRepository returns results from another Repo.

### ISSUE THREAD

**Issue by mabintact** [typeorm/typeorm#4958]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.20`

**Steps to reproduce or a small repository showing the problem:**

As soon as I update to TypeORM 0.2.20 (NPM Version) when we ran a graphql query the results obtain had nulls everywhere except for the keys. I added a console log to the query and discovered the results were for another repository NOT included in the query's file.

async getQuerySomething(_root: any, _args: any) {
  const queryData = await getConnection("mainConn")
  .getRepository(Repo)
  .find();
  
  console.log("/** getQuerySomething * Start ***");
  console.log(queryData);
  console.log("*** getQuerySomething * End   **/");
  
  return queryData;
},

The output of queryData showed results that were inconsistent with the repository. When outputing the result of getRepository, we could clearly see the table name was wrong. It wasn't even an Entity included in the Resolver file. The Entity came from another Resolver.

Reproducing the issue was easy as all we had to do was go back and forth from 0.2.19 to 0.2.20.
0.2.20 is the only version that seemed to cause the issue.

**Comment by pleerock** [comment]
can you check if its the same issue as #4940 ?

**Comment by mabintact** [comment]
The class names are different in our case.

One is:
@Entity("request_type", {schema: "public" } )
export class RequestType {...}

and the other:
@Entity("request_status", {schema: "public" } )
export class RequestStatus {...}

**Comment by smallg** [comment]
@mabintact also catch this issue, how about solution?

**Comment by Soinou** [comment]
We are also encountering this issue. Here's what happens:

## first.ts

```typescript
import { Column, Entity } from "typeorm";

@Entity({ name: "first" })
export class First {
    @Column("int", {
        nullable: false,
        primary: true,
        unique: true,
    })
    public id!: number;

    @Column("varchar", {
        nullable: true,
        primary: false,
        unique: false,
    })
    public name?: string;
}
```

## second.ts

```typescript
import { Column, Entity } from "typeorm";

@Entity({ name: "second" })
export class Second {
    @Column("int", {
        nullable: false,
        primary: true,
        unique: true,
    })
    public notId!: number;

    @Column("varchar", {
        nullable: true,
        primary: false,
        unique: false,
    })
    public notName?: string;
}
```

## query.ts

```typescript
import { First } from "first.ts";

const results = await getConnection()
    .getRepository(First)
    .createQueryBuilder("a")
    .where("name = 'b'")
    .getMany();
```

## Output (SQL)

```sql
select `a`.`notId`, `a`.`notName` from `second` `a` where `a`.`name` = 'b';
```

Note: this is not actually the code we have since I can't really make it public, but I can add some specifics if someone needs it.

For now going back to 0.2.19 fixes the issue though.

**Comment by millsmcilroy** [comment]
@mabintact Does the latest release 0.2.24 with commit https://github.com/typeorm/typeorm/commit/e3be9e34e00768af3304b238389fb80ce13bb567 resolve this issue?

**Comment by mabintact** [comment]
> @mabintact Does the latest release 0.2.24 with commit [e3be9e3](https://github.com/typeorm/typeorm/commit/e3be9e34e00768af3304b238389fb80ce13bb567) resolve this issue?

It's working great for me. :-)
I updated to 0.2.24 and everything I could thing to test is working great.
