### ISSUE TITLE
How to automatically create a related OneToOne entity if one wasn't set during initial creation??

### ISSUE THREAD

**Issue by thusfar7** [typeorm/typeorm#4962]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have 2 entities. User and UserProfile. Is it possible to automatically create and insert UserProfile object one wasnt provided?? What would be the best way to achieve that?

My models

```ts 
import * as bcrypt from 'bcrypt';
import {
    AfterLoad,
    BeforeInsert,
    BeforeUpdate,
    Column,
    Entity,
    JoinColumn,
    OneToOne,
    PrimaryGeneratedColumn
} from "typeorm";
import {UserProfile} from "./UserProfile";

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    user_id: number;

    @Column({type: 'varchar', length: 100, unique: true})
    email: string;

    @Column({type: 'varchar', length: 100})
    password: string;

    @Column({type: 'bool', default: false})
    is_active: boolean;

    @Column({type: 'bool', default: false})
    is_superuser: boolean;

    @Column('timestamp with time zone', {nullable: false, default: () => 'CURRENT_TIMESTAMP'})
    joined_at: Date;

    @OneToOne(type => UserProfile, profile => profile.user) // specify inverse side as a second parameter
    @JoinColumn({name: 'profile_id'})
    profile: UserProfile;
```

```ts 

import {Column, Entity, OneToOne, PrimaryGeneratedColumn} from "typeorm";
import {User} from "./User";


@Entity()
export class UserProfile {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    first_name: string;

    @Column()
    last_name: string;

    @OneToOne(type => User, user => user.profile) // specify inverse side as a second parameter
    user: User;

}
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by rogrdat** [comment]
How about using the @AfterInsert event on the User entity to trigger creation of a UserProfile entity?

**Comment by thusfar7** [comment]
@rogrdat yes I'm aware of that. I just want to know the best approach to do that. Can I do something like

```
@afterInser
async createProfile() {
   this.profile = UserProfile()
   this.save()
}
```

or do I have to import my UserProfile repository and do it that way.

Or is there a better way?

**Comment by TobiGe** [comment]
I'd second that question, 
The user case is similar, I'd like to create a "UserSettings" Entity whenever a "User" Entity is created.   
Both are linked in a OneToOne Relationship which is owned by the User-Entity. (Using @JoinColumn()) 

I have tried using {cascade: ["insert"]} without success. Any hints?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
