### ISSUE TITLE
Await for entities to be registered.

### ISSUE THREAD

**Issue by wintertime-inc** [typeorm/typeorm#4965]
**Issue type:**
[X] question
[X] bug report

**Database system/driver:**
[X] `postgres`

**TypeORM version:**
[X] `latest`

**Steps to reproduce or a small repository showing the problem:**
For my application I would like to setup connection on-fly which is already done and works fine based on request details, after request is received the Middleware checks if connections exists, if not is trying to create new connection or return error.

When connection is created with status of connection.isConnected === true, but I send let's say 3 queries in the same time, it is getting errors on Entity registration e.g:
`[Nest] 9257   - 10/24/2019, 2:13:56 PM   [ExceptionsHandler] No repository for "XXX" was found. Looks like this entity is not registered in current "XXX" connection? +4250ms`

Every next query **will work fine**, as the entity is registered in the meantime using:
`entities: [__dirname + '/**/**/*.entity{.ts,.js}']`
It doesn't matter if I use this example for entities or even calling them [SomethingEntity] it doesn't make any difference.

This situation happen always when backend is restarted and after the restart of an app while getting more than one query, some of the entities are not yet registered.
I made really bad workaround for this for now which is working fine (it basically wait 3 secs after connection is established to make sure everything is initialized, this will work only for first queries after app restart, later createConnection is skipped if already exists), however I believe there must be an option to wait if all entities has been already initialized and then let it go.

Working workaround  solution:
```ts
await createConnection(connection);
await new Promise( resolve => setTimeout(resolve, 3000) );
const conn = await getConnection(connection.name);
if (conn.isConnected) {
    next( now it will try to get repository and other business logic which will work);
}
```
Not working solution:
```ts
createConnection(connection).then(
  (connection) => {
      console.log(connection.isConnected);
      next( not it will try to get repository and other business logic which will fail );
  }
).catch(
  (err) => {
      ...only returns issues related to the connection itself
  }
)
```

**Comment by imnotjames** [comment]
I cannot replicate this.

We connect and build the metadata as part of `createConnection` by awaiting the completion of `connect`
