### ISSUE TITLE
Migrate using decorators

### ISSUE THREAD

**Issue by antoine-pous** [typeorm/typeorm#4966]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `any`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Request:**
Actually when we migrate we mostly use `queryRunner.query` which run raw SQL queries. But it would be awesome to be able to use decorators instead. Then a migration can be even more readable and it's code will become compliant with it's model.

Here's an example:
We add an index to a table, then just do

**Actual way to migrate:**
```typescript
class addIndexToTable123456789 {
  up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1234" ON "schema"."table" ("col1", "col2", "col3") `)
  }

  down(): Promise<void> {
    await queryRunner.query(`DROP INDEX "schema"."IDX_1234"`)
  }
}
```
**Requested changes:**
```typescript
@migrate
class addIndexToTable123456789 {
  @up()
  @addIndex('indexName', 'tableName', ['col1', 'col2', 'col3'], { unique: true })

  @down()
  @dropIndex('indexName', 'tableName')
}
```

The main goal is avoiding raw strings and use a minimalist code to perform migrations when it's possible, when we can't we can still use `queryRunner`.

**Comment by pconerly** [comment]
@antoine-pous I like the syntax change for `addIndex`, but I think that the `@up()` is going too far? Having up and down organized into two separate methods is a nice way to organize, and it's similar to other migration frameworks.

**Comment by antoine-pous** [comment]
@pconerly i agree with you, this can become painful :)

```ts
@migrate
class addIndexToTable123456789 {
  public up(): Promise<void> {
    @addIndex('indexName', 'tableName', ['col1', 'col2', 'col3'], { unique: true })
  }

  public down(): Promise<void> {
    @dropIndex('indexName', 'tableName')
  }
}
```
Seem good too, maybe allowing both and let the dev decide depending his migration can be the best approach :thinking:

**Comment by MurkyMeow** [comment]
You could save 2 characters by not putting that `@` symbol in front of each function call 😉.

**Comment by imnotjames** [comment]
You can use `queryRunner.createIndex` to do this - sure, it's not a decorator, but it's an API that is EFFECTIVELY what you're describing! :)
