### ISSUE TITLE
TypeORM Data Mapper/Domain Model SoC and Query Performance 

### ISSUE THREAD

**Issue by JamieCorkhill** [typeorm/typeorm#4968]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Question**

Hello, I apologize in advance if this is the wrong to place to post this question. I wanted to ask a few questions about TypeORM that have been stopping me from using it, which I was hoping someone could help clear up.

Firstly, I'm not a fan of tightly coupling my domain models to my database model. I prefer the Data Mapper Pattern over Active Record, namely, Repositories.

TypeORM requires that you sprinkle decorators around your database entities. Is it possible to still have domain model classes in the Domain Layer that are completely database and ORM agnostic with TypeORM? That is, I would like to have simple Domain Models with their own Value Objects and Invariants that I pass into the Repository for commands, and I'd like to Repositories to map to Domain Models for queries. Is that possible with TypeORM?

Secondly, I've heard that, as with any ORM, TypeORM querying is not optimized. Is that the case?

Thank you.

**Comment by felideon** [comment]
I'm setting up a new project and, If I'm reading the docs correctly, it seems like it would be more accurate to say that TypeORM supports the [Repository](https://martinfowler.com/eaaCatalog/repository.html) pattern, but not the [Data Mapper](https://martinfowler.com/eaaCatalog/dataMapper.html) pattern (emphasis mine):

> With Data Mapper the in-memory objects needn't know even that there's a database present; they need no SQL interface code, and certainly **no knowledge of the database schema**.

Unless I'm misreading the docs, TypeORM entities must map to database columns 1:1 using `@Column` decorators, as opposed to say [MikroORM](https://mikro-orm.io/docs/defining-entities#virtual-properties) or [Ecto](https://hexdocs.pm/ecto/data-mapping-and-validation.html#schemas-are-mappers) (to use an example from a different language).

I think this is an important question to answer, as it was the same [mistake made by the original DataMapper Ruby library](https://en.wikipedia.org/wiki/DataMapper) and throws people off who are looking for data mapper libraries in Node.

**Comment by JamieCorkhill** [comment]
Thanks, @felideon.

It does appear that TypeORM is not properly supporting the Data Mapper pattern. One potential workaround would be to define TypeORM Entities at the persistence layer as well as plain Domain Models at the domain layer, and then build a custom mapper that gets injected into the repository. It may be possible to build a custom repository and inject the ORM rather than using TypeORM's repo.

What I've resolved to is doing away with TypeORM and any ORM altogether. Now, I implement everything from scratch with the Knex Query Builder. This lets me define custom mappers, custom repositories, and custom units of work.

**Comment by JamieCorkhill** [comment]
Although, this link was mentioned in #1950:

https://typeorm.io/#/separating-entity-definition

**Comment by felideon** [comment]
Ah, right. I saw that in the docs, but it seems like you still have to set up `columns` which is troublesome imo.

**Comment by JamieCorkhill** [comment]
I completely agree. The minute I saw that, it stopped making sense in terms of how that solution is viable.

With that said, it looks like TypeORM is making a distinction between entities and models. Nothing really stops you from creating a decorator-ridden _entity_ that lives with persistence only, but then also a nice clean POTO (for TS) in the domain that's separate. Now it just comes down to building a mapper in between them, something like:

```typescript
export interface IMapper<TDomain, TEntity> {
    toDomain(raw: TEntity): TDomain;
    toPersistence(domain: TDomain): TEntity;
}
```

Right?

**Comment by felideon** [comment]
Perhaps. I'd have to see an example of what that looks like in practice, because at that point it's not clear why I'd still be using TypeORM. Might as well just drop down to knex, as you mentioned.

I'm not too interested in figuring out the workarounds to adapt TypeORM to my needs. Heck, I'm still considering my non-JS options (e.g. Ecto or Ruby Object Mapper).

**Comment by felideon** [comment]
I really appreciate the input, though, @JamieCorkhill!

**Comment by JamieCorkhill** [comment]
You're welcome @felideon 

As far as why it would be useful still, with Knex, you it becomes difficult to persist aggregates that span multiple tables because you sometimes have to open a transaction in the repo, which feels like a bad practice. 

The ORM in the repo will make it easier.

**Comment by JamieCorkhill** [comment]
I might be able to come up with an example when I have time. I've been considering giving TypeORM another chance with the configuration I mention above. 

I've been taking a simplified CQRS approach lately wherein I use pure SQL on the query side and it's really nice. It's also more performance because you can use joints, which gets messy with Repo/DM.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
