### ISSUE TITLE
How to retrieve data from  the many to many relationship

### ISSUE THREAD

**Issue by httpsOmkar** [typeorm/typeorm#497]
Hello again,
I need help I have implemented the many to many relationship but problem is how to retrieve the data from it. How to join the tables.

**Comment by pleerock** [comment]
Use query builder:

```ts
connection.getRepository(Post)
    .createQueryBuilder("post")
    .leftJoinAndSelect("post.categories", "category")
    .getMany();
```

where Post has many-to-many with categories.
