### ISSUE TITLE
Call SQL Server Stored Procedure with Parameter

### ISSUE THREAD

**Issue by kevinsherman** [typeorm/typeorm#4970]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I would like to be able to call a stored procedure that requires input parameters.

```const asOfDate = request.query.asOfDate;
   const connection = await connect(); // gets or creates connection
   const param = new MssqlParameter(moment(asOfDate).toDate(), "date"); // convert string to date
   const ret = await connection.manager.query('EXECUTE MyStoredProcedure', [param]);
```
Result: 
```
QueryFailedError: Error: Procedure or function 'MyStoredProcedure' expects parameter '@AsOfDate', which
was not supplied.
at new QueryFailedError
(/home/kevin/projects/sablelab/client/functions/node_modules/typeorm/error/QueryFailedError.js:11:28)
at /home/kevin/projects/sablelab/client/functions/node_modules/typeorm/driver/sqlserver/SqlServerQueryRunner.js:232:61
at _query (/home/kevin/projects/sablelab/client/functions/node_modules/mssql/lib/base.js:1346:25)
at Request.tds.Request.err [as userCallback]
(/home/kevin/projects/sablelab/client/functions/node_modules/mssql/lib/tedious.js:671:15)
at Request.callback (/home/kevin/projects/sablelab/client/functions/node_modules/tedious/lib/request.js:37:27)
at Connection.endOfMessageMarkerReceived
(/home/kevin/projects/sablelab/client/functions/node_modules/tedious/lib/connection.js:2104:20)
at Connection.dispatchEvent
(/home/kevin/projects/sablelab/client/functions/node_modules/tedious/lib/connection.js:1084:36)
at Parser.tokenStreamParser.on
(/home/kevin/projects/sablelab/client/functions/node_modules/tedious/lib/connection.js:914:14)
at Parser.emit (events.js:189:13)
at Parser.parser.on.token
(/home/kevin/projects/sablelab/client/functions/node_modules/tedious/lib/token/token-stream-parser.js:27:14)

```
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by kevinsherman** [comment]
I was able to get this to work by using: 

```const ret = await connection.manager.query('EXECUTE MyStoredProcedure @AsOfDate= "' + asOfDate + '"');```

It works - but I'd still like input/guidance as to whether or not this is the correct way to do this. Thank you!

**Comment by dsbert** [comment]
@kevinsherman I think you risk SQL Injection with that method.

**Comment by alexanderomnix** [comment]
To avoid sql injection and use params on you mssql stored procedure or whatever query you wish, just use:
Example:
await MymssqlConnection.query(
      'select * from test where thing1 = @0 and thing2 = @1',
      ['param 1 data', 'param 2 data'],
    );

**Comment by edboyledev** [comment]
For MySQL
```typescript
connection.manager.query('CALL sp_someStoredProc(?, ?)', [user.id, user.something])
```
This will return a [RowDataPacket](https://stackoverflow.com/questions/38133084/how-to-access-rowdatapacket-mysql-node-js/38139286), and you will need to have [EXECUTE privileges](https://stackoverflow.com/questions/10089308/mysql-stored-procedure-permissions).

For SQL Server
I have not worked with SQL Server in years, but I can only guess based on previous comments here it would look something like this:
```typescript
connection.manager.query('EXECUTE sp_someStoredProc(@0, @1)', [user.id, user.something]) // Untested
```
And again, you may have to set permissions. 

You get the general Idea 
```typescript
connection.manager.query('COMMAND WITH PARAMS', [ARRAY, OF, VALUES])
```

**Comment by eprokhor** [comment]
const result = await getConnection().query('EXEC coach.GetRoleComponents  @0,@1,@2',
            [nodeId, userId, 'JSONResult']);
console.log(result);
printing undefined but when I run this in sql studio for mssql I get a json.

**Comment by imnotjames** [comment]
Looks like a few possible approaches.  Going to close tis as it seems to be all set.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by eprokhor** [comment]
@imnotjames I don't think it should be closed as these are work arounds which opens a new connection to the db. This is not a typeorm fix. This is using mssql library.

**Comment by AdamJessop** [comment]
@eprokhor I was able to achieve this with by creating the following function:

`export const callStoredProcedure = (connection: Connection, sp: string, params: Record<string, unknown>) => {

    const paramsStr = Object.keys(params)
        .map((key, index) => `@${capitalise(key)}=@${index}`)
        .join(', ');

    const queryStr = `EXEC ${sp} ${paramsStr}`;

    return connection.query(queryStr, Object.values(params));
}`

DISCLAIMER: Only used it for queries with 1 argument for now but I just got it working and wanted to remember to reply :)

**Comment by eprokhor** [comment]
Thank you so much @AdamJessop

**Comment by dfenerski** [comment]
How about getting values from

1. output parameters
2. SP return value

Any examples, clues on this?

**Comment by eprokhor** [comment]
@dfenerski  https://github.com/typeorm/typeorm/issues/6856

**Comment by AdamJessop** [comment]
@dfenerski 

I updated the code I sampled above to handle the passing in of output Params, here is an excerpt from my DB class:


```
export interface IOutputParams {
    [paramName: string]: 'nvarchar(200)' | 'Int';
}

private async callStoredProcedure(sp: string, params: Record<string, unknown> = {}, outputParams: IOutputParams = {}, flatten = false, database?: Database) {
        const db = this.getDatabaseConnection(database);

        const outputKeys = Object.keys(outputParams).length > 0 ? Object.keys(outputParams) : undefined;

        // declare outputs
        const declareOutputs = outputKeys
            ? `DECLARE ${outputKeys.map((key) => `@${capitalise(key)} ${outputParams[key]} `)}`
            : '';

        const paramsArr = Object.keys(params).map((key, index) => `@${capitalise(key)}=@${index}`);

        const outputParamsArr = outputKeys
            ? outputKeys.map((key, index) => `@${capitalise(key)}=@${capitalise(key)} OUTPUT`)
            : [];

        const paramsStr = [...paramsArr, ...outputParamsArr].join(', ');

        const selectOutputs = outputKeys ? `SELECT ${outputKeys.map((key) => `@${capitalise(key)} as '${key}'`).join(',')}` : '';

        const queryStr = `${declareOutputs} EXEC ${sp} ${paramsStr} ${selectOutputs}`;

        const response = await db.query(queryStr, Object.values(params));

        if (flatten && response?.length === 1) {
            if (outputKeys && outputKeys.length === 1) {
                return response[0][outputKeys[0]];
            }

            return response[0];
        }

        if (flatten && response?.length === 0) {
            return undefined;
        }

        return response;
    }
```

**Comment by gusleo** [comment]
@AdamJessop : thanks for your solution, I'm implement your code on several stored procedure call. But when I try with OUT parameter that is no return value for output paramater, only the main exec stored procedure.

**Comment by amirainfo** [comment]
> For MySQL
> 
> ```ts
> connection.manager.query('CALL sp_someStoredProc(?, ?)', [user.id, user.something])
> ```
> 
> This will return a [RowDataPacket](https://stackoverflow.com/questions/38133084/how-to-access-rowdatapacket-mysql-node-js/38139286), and you will need to have [EXECUTE privileges](https://stackoverflow.com/questions/10089308/mysql-stored-procedure-permissions).
> 
> For SQL Server
> I have not worked with SQL Server in years, but I can only guess based on previous comments here it would look something like this:
> 
> ```ts
> connection.manager.query('EXECUTE sp_someStoredProc(@0, @1)', [user.id, user.something]) // Untested
> ```
> 
> And again, you may have to set permissions.
> 
> You get the general Idea
> 
> ```ts
> connection.manager.query('COMMAND WITH PARAMS', [ARRAY, OF, VALUES])
> ```

About this case . How to catch the error handling the data base ? Do you know ?

**Comment by rezaizadijahromi** [comment]
> How about getting values from
> 
> 1. output parameters
> 2. SP return value
> 
> Any examples, clues on this?

have same problem any solution ?

**Comment by KamaliyaDhawal** [comment]
Checkout this NPM package

[NestJs TypeOrm SPCall](https://www.npmjs.com/package/dk-typeorm-spcall)

**Comment by emman-ok** [comment]
People, save yourself some time. Don't use this library in production.

**Comment by maxrks** [comment]
> @eprokhor I was able to achieve this with by creating the following function:
> 
> ```
> export const callStoredProcedure = (connection: Connection, sp: string, params: Record<string, unknown>) => {
> 
>     const paramsStr = Object.keys(params)
>         .map((key, index) => `@${key}=@${index}`)
>         .join(', ');
> 
>     const queryStr = `EXEC ${sp} ${paramsStr}`;
> 
>     return connection.query(queryStr, Object.values(params));
> }
> ```
> 
> DISCLAIMER: Only used it for queries with 1 argument for now but I just got it working and wanted to remember to reply :)

Well done,  Thanks!  Here is demo.

```
const sqlProc = (sp: string, params: Record<string, unknown>) => {
  const paramsStr = Object.keys(params)
    .map((key, index) => `@${key}=@${index}`)
    .join(', ');
  const queryStr = `EXEC ${sp} ${paramsStr}`;

  return getManager().query(queryStr, Object.values(params));
};
```

Given a `sp` as `sp_demo` with parameters`@p1,@p2,@p3,@p4`

```
const result = await sqlProc('sp_demo',{p1:'p1_value',p4:'p4_value'})
```
works if `@p2,@p3` in default value.
