### ISSUE TITLE
Refresh Materialized View

### ISSUE THREAD

**Issue by frascaluigi** [typeorm/typeorm#4971]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi,

I have a materialized view in my project and I am trying to refresh it each time I insert or update a related table. At now I am using this solution:

`@AfterInsert()`
`@AfterUpdate()`
`updateMaterialedView(){`
  `getRepository(MyMaterializedView).query('REFRESH MATERIALIZED VIEW materialized_view')`
  `.then(resp => console.log('update materialized view ok'))`
   `.catch(err => console.error('update materialized view error'))`
`}`

Is there another solution to avoid writing the query manually ?

Thanks,
Luigi

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
Unfortunately, I think that's your best bet - you could also do a subscriber instead of a listener but it's roughly the same thing.
