### ISSUE TITLE
Rollback migrations in cascade

### ISSUE THREAD

**Issue by antoine-pous** [typeorm/typeorm#4973]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `any`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Request:**
Allow us to link two migrations, which will allow to rollback many migrations in cascade when we need to split them due to some timeouts or to preserve our code readability
```ts
export class MyMigration12345 implements MigrationInterface {
  // An huge migration which require to be splitted in two transactions to avoid any timeout
  public up(): Promise<void> {}

  public down(): Promise<void> {}
}

export class MyMigration23456 implements MigrationInterface {
  // If this transaction fail or is rollback by another linked migration, we rollback MyMigration12345 too
  linkedTransaction: string = `MyMigration12345`
 
  public up(): Promise<void> {}

  public down(): Promise<void> {}
}

export class MyMigration34567 implements MigrationInterface {
  // If this transaction fail, we rollback MyMigration23456 too
  linkedTransaction: string = `MyMigration23456`
 
  public up(): Promise<void> {}

  public down(): Promise<void> {}
}
```
I know we can drop many things using `CASCADE`, but doing that don't delete the entries from the migrations table, which can lead to even more issues.

**Comment by imnotjames** [comment]
You can set `migrationsTransactionMode` as `all` or you can combine them into one migration file.
