### ISSUE TITLE
How to make typeORM read explicit fields of entity?

### ISSUE THREAD

**Issue by Amirm73** [typeorm/typeorm#4974]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How to make typeORM read explicit fields of a query from a database?
assume this query:
{
getAllTodos{
name
}
}

the Todo entity has other fields like tags, and so on. so how can I set typeORM to prevent other fields to be read from the database? (i know they are ALL  read from DB but returns the requested fields.)

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
