### ISSUE TITLE
Problems create connection with Expo

### ISSUE THREAD

**Issue by henrique25teles** [typeorm/typeorm#4976]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[x] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

ormconfig.json:
```
{
   "type": "expo",
   "database": "AppDatabase.db",
   "synchronize": true,
   "logging": false,
   "entities": [
      "src/models/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}
```

App.tsx (Just important parts):

```
import "reflect-metadata"
import {createConnection} from 'typeorm'

import Start from 'Start'
import store from 'store'

createConnection({type: 'expo', database: "AppDatabase.db"})
  .then(async conection => {
    console.log(conection)
  })
  .catch(error => console.log(error));

```

createConnection doesn't work with expo properly.
I am receiving message of missing dependency `react-native-sqlite-storage`
this message: 
`Unable to resolve "react-native-sqlite-storage" from "node_modules\typeorm\browser\driver\react-native\ReactNativeDriver.js"`

It's weird because Expo has its own SQLite
`import * as SQLite from 'expo-sqlite'`

My package.json:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "set REACT_NATIVE_PACKAGER_HOSTNAME=192.168.100.7 && expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "expo-asset": "~7.0.0",
    "expo-localization": "~7.0.0",
    "expo-sqlite": "~7.0.0",
    "firebase": "^7.2.1",
    "i18n-js": "^3.3.0",
    "node-emoji": "^1.10.0",
    "rastrojs": "^1.0.3",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-elements": "^1.2.6",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "~1.2.0",
    "react-native-screens": "~1.0.0-alpha.23",
    "react-native-svg": "~9.9.2",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.2.2",
    "react-navigation-stack": "^1.9.3",
    "react-navigation-tabs": "^2.5.5",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "reflect-metadata": "^0.1.13",
    "sqlite3": "^4.1.0",
    "typeorm": "^0.2.20",
    "typesafe-actions": "^4.4.2"
  },
  "devDependencies": {
    "@types/node": "^12.11.7",
    "@types/react": "^16.8.23",
    "@types/react-native": "^0.57.65",
    "@types/react-redux": "^7.1.4",
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-preset-expo": "^7.0.0",
    "ts-node": "^8.4.1",
    "typescript": "^3.4.5"
  },
  "private": true
}

```

**Comment by allangomessl** [comment]
I'm having same problem with postgres

**Comment by cmcnicholas** [comment]
I'm experiencing this, did you manage to resolve?

**Comment by ken0x0a** [comment]
{See https://github.com/typeorm/expo-example}

We need to add "react-native-sqlite-storage" as a dependency.

**Comment by imnotjames** [comment]
Looks like it fails because metro is not super great at determining what to pull in - so it tries to pull in this as well.

I'll be closing this out as it seems to be a problem with metro and not TypeORM but please open an issue if you've found a way to correct this issue from the TypeORM side of things.

**Comment by danieloi** [comment]
This helped me out https://dev.to/jgabriel1/expo-sqlite-typeorm-4mn8

**Comment by mbrimmer83** [comment]
This did not help me. The connection never returns and there appears to be a memory leak somewhere. My memory rockets from about 150mb to 9 gb when trying to connect with typeorm.

**Comment by danieloi** [comment]
Hmm 🤔 
It didn’t work for me till the I followed the article closely.
