### ISSUE TITLE
Querying postgres schema by deeply nested relations

### ISSUE THREAD

**Issue by rmainseas** [typeorm/typeorm#4977]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

At present it seems to only be possible to refer to the columns in the current table, including relation foreign keys (unless you drop to SQL and write the queries manually)

I'm looking to be able to do something like this:

```js
this.User.find({
    where: {
        photos: {
            name: Like('%Fubar%')
        }
    }
});
```

Is this currently possible? If not, I'm happy to turn this into an issue and maybe look at putting in a PR if that's agreeable?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
It was not - should be possible with #7805
