### ISSUE TITLE
Use query builder without a registered entity

### ISSUE THREAD

**Issue by ValiDraganescu** [typeorm/typeorm#4979]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Just a simple question: Can I use the SelectQueryBuilder without an Entity?

My use case is that I don't know the structure of the database from where I'm reading data, but I'd like to use the query builder to build queries ( a user can do simple filtering in frontend and send their options to the backend via REST API). I want to use the query builder to generate the query. Right now the `...select().from()` is required, but I don't have an entity registered with the connection. Ideally, I will use the query builder to call `getSql` on it and execute it as raw query.

**Comment by muhamad-rizki** [comment]
try executing raw query using [entity manager](https://typeorm.io/#/entity-manager-api) so it would be like this:
`await manager.query('select * from UnregisteredEntity');`
where **UnregisteredEntity** is your table on database

**Comment by ValiDraganescu** [comment]
@muhamad-rizki I ended up doing that, but it's not a great thing to do when you have a complex query that can also be build dynamically based on user settings.

**Comment by wwwork** [comment]
same qustion

**Comment by parvaurea** [comment]
following

**Comment by thalysonalexr** [comment]
follow

**Comment by otonii** [comment]
https://github.com/typeorm/typeorm/blob/920e7812cd9d405df921f9ae9ce52ba0a9743bea/docs/select-query-builder.md#getting-values-using-querybuilder

> There are two types of results you can get using select query builder: entities or raw results. Most of the time, you need to select real entities from your database, for example, users. For this purpose, you use getOne and getMany. But sometimes you need to select some specific data, let's say the sum of all user photos. This data is not an entity, it's called raw data. To get raw data, you use getRawOne and getRawMany. Examples:

```js
const { sum } = await getRepository(User)
    .createQueryBuilder("user")
    .select("SUM(user.photosCount)", "sum")
    .where("user.id = :id", { id: 1 })
    .getRawOne();
```

```js
const photosSums = await getRepository(User)
    .createQueryBuilder("user")
    .select("user.id")
    .addSelect("SUM(user.photosCount)", "sum")
    .groupBy("user.id")
    .getRawMany();

// result will be like this: [{ id: 1, sum: 25 }, { id: 2, sum: 13 }, ...]
```

Typescript: `...getRawOne<MyType>()` and `...getRawMany<MyType>()`.

**Comment by imnotjames** [comment]
Answered and linked to docs.  Closing.  Thanks, friend!

**Comment by fortezhuo** [comment]
@imnotjames and @otonii 

I can't get it working and I found createQueryBuilder need parameter ```entityClass``` on typeorm 0.3.6

```
    createQueryBuilder<Entity>(
        entityClass: EntityTarget<Entity>,
        alias: string,
        queryRunner?: QueryRunner,
    ): SelectQueryBuilder<Entity>

    /**
     * Creates a new query builder that can be used to build a SQL query.
     */
    createQueryBuilder(queryRunner?: QueryRunner): SelectQueryBuilder<any>

    /**
     * Creates a new query builder that can be used to build a SQL query.
     */
    createQueryBuilder<Entity>(
        entityClass?: EntityTarget<Entity> | QueryRunner,
        alias?: string,
        queryRunner?: QueryRunner,
    ): SelectQueryBuilder<Entity> {
        if (alias) {
            return this.connection.createQueryBuilder(
                entityClass as EntityTarget<Entity>,
                alias,
                queryRunner || this.queryRunner,
            )
        } else {
            return this.connection.createQueryBuilder(
                (entityClass as QueryRunner | undefined) ||
                    queryRunner ||
                    this.queryRunner,
            )
        }
    }

```
https://github.com/typeorm/typeorm/blob/master/src/entity-manager/EntityManager.ts

**Comment by FireFighter80** [comment]
@fortezhuo If you add a second parameter that is null to the from() function, it works like a charm.

```ts
const res = await manager
    .createQueryBuilder()
    .select()
    .from("tableName", null)
    .where("user.id = :id", { id: 1 })
    .getRawMany();
```

**Comment by gsmental** [comment]
const data = await PostgresDataSource.createQueryBuilder()
    .select("*")
    .from("invent.vmasterproduct", "p")
    .getRawMany();

**Comment by samdeanpinknews** [comment]
I've had success with this:

`const builder = myRepository.manager.connection.createQueryBuilder();`

Or, if you aren't in a place where you've got a repository, get one straight from any entity class you have:

`const builder = MyEntity.getRepository().manager.connection.createQueryBuilder();`
