### ISSUE TITLE
Error on ORACLE servers

### ISSUE THREAD

**Issue by gerwinbrunner** [typeorm/typeorm#4981]
**Issue type:**

[X] question
[?] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, I'm having a pretty straight forward model that works nicely on sqlite.
When I try to run it on it works on the first server start up.

On the second startup it queries the schema and tries to alter tables and I get the following kind of error

```
I20191028-10:43:44.248(1)? query: SELECT "TABLE_NAME" FROM "USER_TABLES" WHERE "TABLE_NAME" = 'typeorm_metadata'
I20191028-10:43:44.297(1)? renaming column "SYS_C00010_19102217:20:46$" in to "id"
I20191028-10:43:44.300(1)? query: ALTER TABLE "KRI_DATA_POINTS" RENAME COLUMN "SYS_C00010_19102217:20:46$" TO "id"
I20191028-10:43:44.327(1)? query failed: ALTER TABLE "KRI_DATA_POINTS" RENAME COLUMN "SYS_C00010_19102217:20:46$" TO "id"
I20191028-10:43:44.328(1)? error: { Error: ORA-00904: "SYS_C00010_19102217:20:46$": invalid identifier errorNum: 904, offset: 44 }
I20191028-10:43:44.330(1)? query: ROLLBACK
W20191028-10:43:44.393(1)? (STDERR) /Users/ap/.meteor/packages/promise/.0.11.2.1ixw4hn.8uhlk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
W20191028-10:43:44.393(1)? (STDERR)       throw error;
W20191028-10:43:44.393(1)? (STDERR)       ^
W20191028-10:43:44.393(1)? (STDERR) 
W20191028-10:43:44.394(1)? (STDERR) QueryFailedError: ORA-00904: "SYS_C00010_19102217:20:46$": invalid identifier
W20191028-10:43:44.394(1)? (STDERR)     at new QueryFailedError (/Users/ap/Documents/Data/Vilango/workspace/egit/owl-v2/app/node_modules/typeorm/error/QueryFailedError.js:11:28)
W20191028-10:43:44.394(1)? (STDERR)     at handler (/Users/ap/Documents/Data/Vilango/workspace/egit/owl-v2/app/node_modules/typeorm/driver/oracle/OracleQueryRunner.js:175:45)

```

So my question would be:
How do I use Oracle in a production setting if I can't use `synchronize = true`
and there is no way to generate the schemas DDL?

Best,
Gerwin

**Comment by imnotjames** [comment]
Can you include more information? This is a bit limited.

Entities and Oracle version that exhibit this issue at the least would help debug.

**Comment by imnotjames** [comment]
Without a way to replicate this issue I am closing it.
