### ISSUE TITLE
How to set initial value of PrimaryGeneratedColumn?

### ISSUE THREAD

**Issue by eugeneshemonaev** [typeorm/typeorm#4982]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I need the order numbers to start at 1000, and each next incremented. How to achieve this?

**Comment by imnotjames** [comment]
You'll need to use a migration and write this specifically as part of the migration.  It's not something we can set easily as part of the sync because most of these you'd have to set it once and if we execute it again it would reset the counting.
