### ISSUE TITLE
Hooks for custom select fields dynamically.

### ISSUE THREAD

**Issue by allangomessl** [typeorm/typeorm#4984]
**Hooks for custom select fields dynamically.**

I intent to manager column level security based on user permissions.

today, we can to do this put @column({ select: false }) but I think we could make it dinamically.

for example:
```
class Sku {

  @OnQuery()
  fun overrideQuery(connection: Connection, query: QueryBuilder) {
    var userVisibilty = connection.getRepository(UserVisibility).find(currentUser);
    query.selectfield('sensitiveColumn', userVisibilty.sensitiveColumn)
  }
}
```

and this role will be used to load in other query with relations 
```
const skuGroups = connection.getRepository(SkuGroup).find({ relations: ['skus'] });
{
  name: 'group1'
  skus: [
    {
         // sensitiveColumn is hidded or not depends of user
    }
  ]
}
```

**Issue type:**

[] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[x] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[x] `cockroachdb`
[x] `sqlite`
[x] `sqljs`
[] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
duplicate of #1601
