### ISSUE TITLE
Simple JSON property is empty on save

### ISSUE THREAD

**Issue by Yavorss** [typeorm/typeorm#4985]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] `0.2.20`

When we create a DB record with a simple JSON property of the entity, the returned JSON is an empty object.

This method returns an instance of the entity with `description` property which is a simple JSON.
`
    const tableAccountElement = this._createTableAccountElementEntity(
      orderElement, tableAccount, vatCoefficient, userId,
    );
`
![image](https://user-images.githubusercontent.com/16567086/67726663-47e1ef80-f9ef-11e9-8bca-e3a6cea93fb5.png)

When the record is created, the description property is an empty object.
![image](https://user-images.githubusercontent.com/16567086/67726726-73fd7080-f9ef-11e9-818a-7aeefcfe6cc0.png)

If I get the record manually again, everything is fine witch means that `transaction.save()` does not return properly value.
![image](https://user-images.githubusercontent.com/16567086/67726963-46fd8d80-f9f0-11e9-8cd6-1320d517f553.png)

I tried to track the problem and I ended up on line `145` in `EntityPersistExecutor.js`. When the sequence pass, the entity object is already changed and the JSON signature is missing.
![image](https://user-images.githubusercontent.com/16567086/67727159-f63a6480-f9f0-11e9-9f66-9f580b99da10.png)

**Comment by tzellman** [comment]
I could be wrong, but I am experiencing the same issue (on the latest `0.2.20` release). I believe it stems from a change made here: https://github.com/typeorm/typeorm/pull/4476

In order to support sqlite (for testing) and postgres (dev/ops), I was forced to set the annotated type for some of my json fields to `simple-json` (sqlite will only work with `simple-json`), even though our migrations use `jsonb` if the driver is postgres.

**Comment by naive924** [comment]
I had the same problem with typeorm 0.2.22.
If it is new, you can avoid it for now by executing insert.

```
let repo = this.getRepository(target);
let found = await repo.findOne(id);
if (!found) {
  await repo.insert(entity);
} else{
  await repo.save(entity);
}
```

**Comment by imnotjames** [comment]
This should be fixed in the next release.
