### ISSUE TITLE
Migrations crash with exit code 137 on VPS

### ISSUE THREAD

**Issue by dannytatom** [typeorm/typeorm#4986]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18`

**Steps to reproduce or a small repository showing the problem:**

```bash
yarn run v1.19.1
$ yarn run ts-node ./node_modules/.bin/typeorm migration:run
$ /home/danny/bots/cake-boss/node_modules/.bin/ts-node ./node_modules/.bin/typeorm migration:run
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Locally, all is fine. When I try to run migrations on a $5/mo Digital Ocean droplet, it dies after hanging for a while. It seems likely it's because it runs out of memory, but is there a way around this without resizing droplet every time I need to do a migration? This works, but is obviously kinda lame lol.

**Comment by hbthegreat** [comment]
Did you end up fixing this @dannytatom? I am running into the same issue on an AWS micro box that I am trying to use for dev branches.

**Comment by hbthegreat** [comment]
Had a further look into this. It is an npm run run issue running out of memory rather than a typeorm migration one (unless that itself is taking too much memory which is a different discussion).

You can either use a box with more memory or you can hack around it with swapfiles if you are on ubuntu. (This is what I have done for my short lived feature branches).

**Comment by exfarnanda1945** [comment]
In my case, i added --transpile-only inside migration script
example: 
DATABASE_NAME=myDatabase MIGRATION_DIR=myApp yarn run ts-node --transpile-only ./node_modules/typeorm/cli.js migration:run

**Comment by imnotjames** [comment]
Pretty sure this is an issue of not having enough memory on the smaller droplets.

If you can find that the migrations cause an undue amount of memory usage please include more information to help replicate.

Until then, I'll be closing this.

**Comment by ryan-efendy** [comment]
> Had a further look into this. It is an npm run run issue running out of memory rather than a typeorm migration one (unless that itself is taking too much memory which is a different discussion).
> 
> You can either use a box with more memory or you can hack around it with swapfiles if you are on ubuntu. (This is what I have done for my short lived feature branches).

@hbthegreat how did you determine or figure out ^ it was bc of the npm run vs. the typeorm migration? doesn't the `npm run` run the typeorm migration script, so they're technically the same thing right?

**Comment by ArtemKurtiakZenwayCode** [comment]
@exfarnanda1945 it works, but are there any better method to avoid this bug?

**Comment by limistah** [comment]
> In my case, i added --transpile-only inside migration script example: DATABASE_NAME=myDatabase MIGRATION_DIR=myApp yarn run ts-node --transpile-only ./node_modules/typeorm/cli.js migration:run

This worked for me as well, I am not sure why is there an update for this issue.
