### ISSUE TITLE
can not create migrations table oracle database

### ISSUE THREAD

**Issue by bauzer** [typeorm/typeorm#4990]
**Issue type:**

[ ] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[*] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Oracle requires lowercase column names to be quoted .

https://github.com/typeorm/typeorm/blob/540ce3d63ccf59a7cc0a3c7c96e0ba7fcc03ad94/src/migration/MigrationExecutor.ts#L320

```
.orderBy("\"id\"", "DESC") 
```

**Comment by imnotjames** [comment]
This has been fixed in the master branch
