### ISSUE TITLE
官网的中文文档出现BUG

### ISSUE THREAD

**Issue by holleworldabc** [typeorm/typeorm#4993]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by jayzhou3** [comment]
Just ditch this project, it does not work for chinese

**Comment by chaojiangcn** [comment]
哪里有中文文档？~

**Comment by jayzhou3** [comment]
@chaojiangcn 

https://typeorm.io/#/ 

Check the language on the top right corner
