### ISSUE TITLE
how to use the JSON_EXTRACT function in a query using createQueryBuilder in a where clause

### ISSUE THREAD

**Issue by JorgeBrs** [typeorm/typeorm#4994]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am trying to make the following query:

this.createQueryBuilder('modelo_producto_especifico')
     .where('JSON_EXTRACT(modelo, `$[0].value`) = :reference', { reference: '123456789' })
     .getOne();

and it shows me this error.

QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column '$[0].value' in 'where clause'

I could not find a post to help me with this error.

**Comment by RecuencoJones** [comment]
Hi @JorgeBrs,
I've just reproduced the issue and fixed it by adding quotes around `$[0].value`:

Created a mysql instance with:

```
docker run -dit \
  --name mysql \
  -p 3306:3306 \
  -e MYSQL_ROOT_PASSWORD=root \
  -e MYSQL_DATABASE=mysql \
  -e MYSQL_USER=mysql \
  -e MYSQL_PASSWORD=mysql \
  mysql:5.7
```

Then:

```typescript
import { Entity, PrimaryGeneratedColumn, Column, createConnection } from 'typeorm';

type JSONValue = {
  value: string;
};

@Entity('ent')
export class MyEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('json')
  data: JSONValue[];
}

async function main() {
  const connection = await createConnection({
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    database: 'mysql',
    username: 'mysql',
    password: 'mysql',
    entities: ["*.ts"],
    synchronize: true
  });

  const a = await connection.manager.create(MyEntity, { data: [{ value: 'test' }] });

  console.log(a);
  await connection.manager.save(a);

  const b = await connection.manager.create(MyEntity, { data: [{ value: 'foo'  }] });

  console.log(b);
  await connection.manager.save(b);

  const res = await connection.manager
    .createQueryBuilder(MyEntity, 'ent')
    .where('JSON_EXTRACT(ent.data, "$[0].value") = "test"')
    .execute();

  console.log(res);
}

main();
```

Console output:
```
MyEntity { data: [ { value: 'test' } ] }
MyEntity { data: [ { value: 'foo' } ] }
[ RowDataPacket { ent_id: 1, ent_data: '[{"value": "test"}]' } ]
```

Also:

<details>
<summary>
package.json
</summary>
<pre>
{
  "name": "typeorm-json-extract",
  "version": "1.0.0",
  "scripts": {
    "start": "ts-node index.ts"
  },
  "dependencies": {
    "mysql": "2.18.1",
    "ts-node": "8.8.1",
    "typeorm": "0.2.24",
    "typescript": "3.8.3"
  }
}
</pre>
</details>

<details>
<summary>
tsconfig.json
</summary>
<pre>
{
  "compilerOptions": {
    "lib": [ "esnext", "dom" ],
    "experimentalDecorators": true
  }
}
</pre>
</details>

**Comment by toalmoal** [comment]
Whats the solution to this please?
