### ISSUE TITLE
Support in-memory database for testing

### ISSUE THREAD

**Issue by dbartholomae** [typeorm/typeorm#4996]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[X] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Feature idea:**

Writing tests is a breeze when using typeorm itself, e. g. for testing a Controller that should write an event to a database
```
it('writes an event to the database', async () => {
  const controller = Container.get(Controller)
  await controller.saveEvent('someEvent')
  expect(await getRepository(Event).count({ name: 'someEvent' })).toBe(1)
})
```
This works out in integration tests with the corresponding database. These tests are, unfortunately, quite slow. Ideally there would be a way to configure typeorm to run with an in-memory database.
The closest I got to this is to use `sql.js` as the database, but this does not fully solve the problem yet, as `sql.js` is not fully compatible with the other databases, e. g. due to the missing `enum` type.

What are the current thoughts on writing unit tests in typeorm? I would be willing to try myself on a PR if someone can lead me into the right decision, though I fear this might be a too big undertaking for just one person. Currently my best idea is to go to the `sql.js` repo and try to add `enum` and the other types.

**Comment by dbartholomae** [comment]
Just saw that there is `simple-enum` which solves the `enum` problem I think, but I am now stuck with `json`. There is also `simple-json`, but this does not create a json type in e. g. PostGres but instead a `text` column. Maybe this is solvable with less work than I feared :)

**Comment by dbartholomae** [comment]
So for my own use case it would be enough to either change `simple-json` so it is saved as `json` instead of `text` in PostGres (which could be considered either a Breaking Change or a bugfix, or both), or to add a new type that behaves like simple-enum (being a json when json is supported and a text otherwise). I would be willing to provide a PR either way, including also a bit of documentation on the usage for unit testing, just need to know which way would be preferred and whether this would be appreciated overall :)

**Comment by kenberkeley** [comment]
https://github.com/kenberkeley/quiz/blob/master/packages/server/src/utils/testing-helpers/createMemDB.ts#L31-L33
