### ISSUE TITLE
Not possible to create a relation

### ISSUE THREAD

**Issue by KonstantinSchuette** [typeorm/typeorm#5010]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have this entity to create a user:
```
@ObjectType()
@Entity()
export class User extends BaseEntity {
    @Field(() => ID)
    @ObjectIdColumn()
    id: ObjectID;

    @OneToOne(type => User, User => User.recruitedUsers)
    @Field({ nullable: true })
    @Column()
    recruitedBy: ObjectID;

    @ManyToOne(type => User)
    @Field({ nullable: true })
    @Column()
    recruitedUsers: ObjectID;
}
```
The error:
```
TSError: ⨯ Unable to compile TypeScript:
src/entity/User.ts:45:15 - error TS6133: 'type' is declared but its value is never read.
@OneToOne(type => User, (user: User) => user.recruitedUsers)
```

I tried this also:
```
@OneToOne(() => User, (user: User) => user.recruitedUsers)
```
But that gives me this error:
```
(node:11820) UnhandledPromiseRejectionWarning: Error: Cannot determine GraphQL output type for register
```

I've also posted this question on stackoverflow:
https://stackoverflow.com/questions/58629197/create-a-relation-to-the-same-table-one-to-one

**Comment by silentroach** [comment]
first one error is TypeScript error (check `noUnusedLocals` config option in your tsconfig) or use `()` like you do.

second error is not a typeorm error, but your GraphQL library interaction
