### ISSUE TITLE
Invalid sequence creation when adding to well known

### ISSUE THREAD

**Issue by Ginden** [typeorm/typeorm#5011]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

tl;dr:

Given class:
```typescript
class Banner {
   @PrimaryGeneratedColumn()
   public id: number;

    @Column({type: 'int', generated: 'increment'})
    public camelCaseColumnId: number;
}
```
TypeORM generates wrong migration.
```
await queryRunner.query(`CREATE SEQUENCE "banner_camelCaseColumnId_seq" OWNED BY "nps_banner"."pollId"`);
await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "camelCaseColumnId" SET DEFAULT nextval('banner_camelCaseColumnId_seq`);
 ```

This fails with message `ERROR: relation "banner_camelcasecolumnid_seq" does not exist`.

Second line should be:
```typescript
await queryRunner.query(`ALTER TABLE "banner" ALTER COLUMN "camelCaseColumnId" SET DEFAULT nextval('"banner_camelCaseColumnId_seq"`); // double quote marks in string
````

**Comment by imnotjames** [comment]
This seems to have been fixed already.
