### ISSUE TITLE
What's the right way to escape user input for `like` queries in mysql?

### ISSUE THREAD

**Issue by viczam** [typeorm/typeorm#5012]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Comment by humodz** [comment]
```ts
function escapeLikeString(raw: string, escapeChar = '\\'): string {
    return raw.replace(/[\\%_]/g, match => escapeChar + match);
}

// For tagged template literals
function escapeLikeTag(parts: TemplateStringsArray, ...args: unknown[]) {
    const escapedArgs = args.map(arg => escapeLikeString(String(arg)));

    const result: string[] = [];

    parts.forEach((part, i) => {
        result.push(part);
        if (i < escapedArgs.length) {
            result.push(escapedArgs[i]);
        }
    });

    return result.join('');
}

// find all users whose first name contains john_smith
// Desired result: firstName like '%john\_smith%'

const userInput = `john_smith`;

await userRepository.find({
    firstName: Like(`%${escapeLikeString(userInput)}%`),
});    

await userRepository
    .createQueryBuilder('user')
    .where('firstName LIKE :value', { value: `%${escapeLikeString(userInput)}%`})
    .getMany();

await userRepository.find({
    firstName: Like(escapeLikeTag`%${userInput}%`),
});

await userRepository
    .createQueryBuilder('user')
    .where('firstName LIKE :value', { value: escapeLikeTag`%${userInput}%`})
    .getMany();
```

**Comment by constb** [comment]
in case someone finds this issue while searching for the same answer, the regex in snippet above can be simplified to

```js
function escapeLikeString(raw: string): string {
    return raw.replace(/[\\%_]/g, '\\$&');
}
```

also, remember that queries for "contained" strings (`LIKE "%str%"`) cannot use indexes, while "begins with" (`LIKE "str%"`) can.

**Comment by imnotjames** [comment]
Answered.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by shaffan-mergn** [comment]
this doesnt work if just want to search names having % in them

'%/%%' want this
