### ISSUE TITLE
Entity.find to return a specific property of it's many-to-many relation

### ISSUE THREAD

**Issue by stelescuraul** [typeorm/typeorm#5013]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**TLDR;** 

I have custom many-to-many A -> B <- C
When calling A.find() I want A.property to be array of C.someOtherPropertyOfC

**Explanation**

I am trying to create the following Many to Many structure. 

User -> User_Role <- Role

I have the following:

```ts
// User.ts

  @OneToMany(() => UserRole, userRole => userRole.userId, {
    cascade: true,
    eager: true
  })
  roles: Partial<UserRole>[];

// UserRole.ts (join table)

  @ManyToOne(() => Role, { nullable: false, eager: true })
  @JoinColumn({ name: 'role' })
  role: string;

  @ManyToOne(() => User, { nullable: false })
  @JoinColumn({ name: 'user_id' })
  userId: number;
```

Role entity has primary key called `key` which UserRole is joining on. When I do `User.find(...)` it returns the right thing, however it has the following format:

User.roles is array of type UserRole
UserRole array values contain a key called `role` which is an array of Role

I'd like `User.roles` to contain an array of `Role.key` string values. Is it possible to do from the definitions of the relations or do i need to introduce listener on User ?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
