### ISSUE TITLE
How to use findOne with a leftJoin and where clause?

### ISSUE THREAD

**Issue by kevinvdburgt** [typeorm/typeorm#5015]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I was wondering how I should construct the `EntityName.findOne();` parameter object to run the following query:
```sql
SELECT 
  users.* 

FROM 
  users 

LEFT JOIN 
  tokens ON tokens.userId = users.id 
  
WHERE 
  tokens.token = "SECRET";
```

I kinda got stuck after this part, as I am not sure how I can add where conditions on the `leftJoin`.
```ts
return this.findOne({
  join: {
    alias: 'user',
    leftJoin: {
      apiToken: 'user.apiTokens',
    },
  },
});
```

**Comment by ardyfeb** [comment]
have you try 
```
this.findOne({
  join: {
    alias: 'user',
    leftJoin: {
      apiToken: 'user.apiTokens',
    },
  },
  where: {
     apiToken: <token>
  },
})
```
?

**Comment by dsbert** [comment]
See https://github.com/typeorm/typeorm/issues/5215#issuecomment-566253819

**Comment by markos13** [comment]
A little bit late here but for the below is working.
Lets assume we 3 entities. A Company with many Offices and one address we can have something like this: 
```

.createQueryBuilder<Company>('company', 'c')
            .innerJoinAndSelect('c.address', 'a')
            .leftJoinAndSelect('c.offices', 'o', 'o.isActive = :activeOff', { activeOff: true })

```
this brings all the companies but only the active offices .
