### ISSUE TITLE
how can I set  mysql pool options?

### ISSUE THREAD

**Issue by jikhww** [typeorm/typeorm#5025]
**Issue type:**

[* ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ *] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ *] `0.2.20` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
i want to set mysql pool to avoid 10 connections limit,but not find any way to do it

**Comment by tzellman** [comment]
I have not tried it, but it appears you should be able to specify `connectionLimit` in the `extra` field of the `BaseConnectionOptions`...

The PoolConfig from the mysql driver:
https://github.com/mysqljs/mysql/blob/ad014c82b2cbaf47acae1cc39e5533d3cb6eb882/lib/PoolConfig.js#L17

Where it is passed into the driver in typeorm:
https://github.com/tzellman/typeorm/blob/19e21795d0450bc96c84cf4a5b88d73546b0007b/src/driver/mysql/MysqlDriver.ts#L854

**Comment by imnotjames** [comment]
Yup - use `extra`
