### ISSUE TITLE
this.driver.connect is not a function

### ISSUE THREAD

**Issue by adnanmasd** [typeorm/typeorm#5028]
**Issue type:**

[ ] question
[* ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[*] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, I am facing error while connecting to my mssql remote database. Following is my connection:
```ts
createConnection({
      type: 'mssql',
      host: "*******",
      port: 1433,
      schema : "dbo",
      username: "****",
      password: "******",
      database: '*****',
      domain : "true",
      logging: ['error', 'query', 'schema'],
      synchronize: true,
      entities: [
        "../models/entities/*.ts"
      ]
    }).then(async connection => {
      const dataRep = connection.getRepository(AMCusInvDtl);
      loadedData = await dataRep.findOne({ where: { DOCNUM: "012013000001" } });
      if (loadedData) {
        console.log("Post has been loaded: ", loadedData);
      }
    }).catch(error => console.log(error));
```

And i am getting error on the console:
```
TypeError: this.driver.connect is not a function
```

I am using mssql driver@3.3.0

**Comment by Misbahyi** [comment]
Hy. I have the same problem. Please tell me what to do if you has result thé problem

**Comment by Misbahyi** [comment]
Hy. I have the same problem. Please tell me what to do if you are result this.
