### ISSUE TITLE
At time zone  from sql to typeorm

### ISSUE THREAD

**Issue by jorgehero** [typeorm/typeorm#5029]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm trying to reproduce this sql in typeorm:

select 
	time_entry."startTime",
        time_entry."endTime"
AT time zone
       'utc'
      AT time zone
      'America/Tegucigalpa'
FROM 
        public.time_entry
WHERE 
        time_entry."createdAt" BETWEEN '2019-09-02 08:24:08' AND 
        '2019-10-11 08:24:08';

I'm struggiling on how to convert the "At Time zone" in typeorm.

Current code looks like this:

      query.andWhere('"startTime" BETWEEN :startValue AND :endValue', {
        startValue: startDate
          .utc()
          .startOf('day')
          .format(),
        endValue: endDate
          .utc()
          .endOf('day')
          .format(),
      });
    }

**Comment by imnotjames** [comment]
That's not exactly supported in TypeORM.

To work through various workarounds and other ways to try to make this happen, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
