### ISSUE TITLE
How to use where clause to select any value of that record

### ISSUE THREAD

**Issue by KasraAhmadi** [typeorm/typeorm#5030]
**Issue type:**

[* ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ *] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ *] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have many input fields and i want to write only one find query for getting any state of input query.
sometimes mycity variable is undefined and i want to search any kind of city in my database when the variable is undefined. how can i achieve that?

`const cmp = await houseRentRepo.find({ where: { complex: user.complex, city: mycity } });`
`

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
