### ISSUE TITLE
How to use nestjs service methods inside typeorm transactions

### ISSUE THREAD

**Issue by ahmednawazkhan** [typeorm/typeorm#5037]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
`6.2.0` 

I have read about transactions in typeorm.

````
@Transaction()
save(user: User, @TransactionRepository(User) userRepository: Repository<User>) {
    return userRepository.save(user);    
}
````
I have a nestjs application with multiple modules and services. what i need to do is call different service methods inside a transaction. but `@TransactionRepository` provides me with the `repository` only. So what should i do to achieve a transaction with multiple service methods being called inside it. like
````
class Module3Service{
    constructor(
    private readonly module1service: Moudle1Service,
    private readonly module2service: Module2Service
    ){}

    @Transaction()
    save() {
        this.module1service.create()
        this.module2service.create()
    }
````
I don't know how to achieve it. and also correct me if I am wrong that a possible solution is to change the moduleservice dependencies ( module1service dependency => module1repositoroy) to change to our new repository instance that we get from `@TransactionRepository(Module1Enity) module1repository: Repository<Module1Entity>` inside the tranction method. or any other solution please help

**Comment by msheakoski** [comment]
I was also thinking about this today but did not yet attempt an implementation. The main issue to solve is that all changes in the transaction need to share the same `transactionalEntityManager`.

One approach is to make special methods in your service that receive `transactionalEntityManager` as an argument, or it could be an optional argument to your existing methods and they would handle the case where it is or is not supplied.

I'm not sure if there is a better way that uses some kind of @decorator magic, but you should definitely ask others in the Nest.js community as well:
* Discord Community Chat: https://discord.gg/G7Qnnhy
* StackOverflow: https://stackoverflow.com/questions/tagged/nestjs using the tag `nestjs`

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
