### ISSUE TITLE
Find creating the wrong query

### ISSUE THREAD

**Issue by alexkroeger** [typeorm/typeorm#5045]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm trying to use the `find` method to grab instances of an entity where column `y` greater than or equal to 10.

```const entities = await repository.find({ y: MoreThanOrEqual(10) });```

I get a `QueryFailedError` when running the code.

```error: { error: invalid input syntax for integer: "[object Object]"```.

Trying to follow examples here: https://github.com/typeorm/typeorm/blob/master/docs/find-options.md.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by silentroach** [comment]
```
const entities = await repository.find({ where: { y: MoreThanOrEqual(10) } });
```

**Comment by silentroach** [comment]
can you show the entity?
