### ISSUE TITLE
InsertQueryBuilder orUpdate using :param parameters format for every driver

### ISSUE THREAD

**Issue by Samuel-B-D** [typeorm/typeorm#5049]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.20` (or put your version here)

`InsertQueryBuilder` is not creating parameter properly inside of the `orUpdate` method. It always force the named `:param` syntax, which doesn't work for example with PostgreSQL.
https://github.com/typeorm/typeorm/blob/f7993a32f8d8e22d8b6e8cd84303637e2c5fdf8f/src/query-builder/InsertQueryBuilder.ts#L248

The following line could be replaced by the following construct instead for example:
```ts
const _this = this;
const parametersCount = Object.keys(this.expressionMap.nativeParameters).length;
this.expressionMap.onUpdate.columns = statement.columns.map(function(column) {
    return column + ' = ' + _this.connection.driver.createParameter(column, parametersCount++);
}).join(', ');
```

I am currently circumventing the issue with a patch-package looking like this : 
```patch
diff --git a/node_modules/typeorm/query-builder/InsertQueryBuilder.js b/node_modules/typeorm/query-builder/InsertQueryBuilder.js
index 629b102..b3c6288 100644
--- a/node_modules/typeorm/query-builder/InsertQueryBuilder.js
+++ b/node_modules/typeorm/query-builder/InsertQueryBuilder.js
@@ -209,9 +209,13 @@ var InsertQueryBuilder = /** @class */ (function (_super) {
             this.expressionMap.onUpdate.conflict = " ( " + statement.conflict_target.join(", ") + " ) ";
         if (statement && typeof statement.conflict_target === "string")
             this.expressionMap.onUpdate.conflict = " ON CONSTRAINT " + statement.conflict_target + " ";
-        if (statement && statement.columns instanceof Array)
-            this.expressionMap.onUpdate.columns = statement.columns.map(function (column) { return column + " = :" + column; }).join(", ");
-        if (statement && statement.overwrite instanceof Array) {
+        if (statement && statement.columns instanceof Array) {
+            var _this = this;
+            var parametersCount = Object.keys(this.expressionMap.nativeParameters).length;
+            this.expressionMap.onUpdate.columns = statement.columns.map(function(column) {
+                return column + ' = ' + _this.connection.driver.createParameter(column, parametersCount++);
+            }).join(', ');
+        } if (statement && statement.overwrite instanceof Array) {
             if (this.connection.driver instanceof MysqlDriver_1.MysqlDriver || this.connection.driver instanceof AuroraDataApiDriver_1.AuroraDataApiDriver) {
                 this.expressionMap.onUpdate.overwrite = statement.overwrite.map(function (column) { return column + " = VALUES(" + column + ")"; }).join(", ");
             }

```

**Comment by igorkamyshev** [comment]
Hello, any updates here?

**Comment by imnotjames** [comment]
I don't even understand what the intent was of `columns` because `createParameter` isn't right either there.

**Comment by imnotjames** [comment]
Oh - I see what it is.  It was because they didn't implement it correctly with `overwrite` and this was kind of a hack to get it working with parameters.

I'll fix it but I think it'd be best to just mark that as a deprecated mechanism..

**Comment by imnotjames** [comment]
Actually, stepping through the code -

You probably aren't using `setParameter()` on the `InsertQueryBuilder`

If you're using the `columns` option instead of `overwrite` you need to bind a parameter that matches the column name.
