### ISSUE TITLE
saveOptions chunk is very confusion

### ISSUE THREAD

**Issue by linchen2chris** [typeorm/typeorm#5050]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have 100,000 entity to save, I'd like to split them to 10 chunks, each chunk has 10,000 items. so what's the saveOption chunk should I pass? 10? or 10,000?
I check api document, it says 10,000, https://typeorm.io/#/repository-api/additional-options
![image](https://user-images.githubusercontent.com/3970087/68278397-28f8f280-00ac-11ea-8f4d-b9b75df50692.png)

I also check code, but the comments says it should be 10. https://github.com/typeorm/typeorm/blob/80d6f6628af01ae58152aea39fe30b819351f6be/src/repository/SaveOptions.ts
![image](https://user-images.githubusercontent.com/3970087/68278313-01a22580-00ac-11ea-81d3-f5f01e0ae807.png)

**Comment by VarunBatraIT** [comment]
Chunk in various languages and library simply means the length of each chunk and not number of chunks

lodash: https://lodash.com/docs/#chunk
php: https://www.php.net/manual/en/function.array-chunk.php
laravel: https://laravel.com/docs/5.8/collections#method-chunk

**Comment by linchen2chris** [comment]
@VarunBatraIT  you are right I checked the source code https://github.com/typeorm/typeorm/blob/ed5ebb082560f8fd56ffd5b7eaf60fcd5a3d26c5/src/util/OrmUtils.ts

    /**
     * Chunks array into peaces.
     */
    static chunk<T>(array: T[], size: number): T[][] {
        return Array.from(Array(Math.ceil(array.length / size)), (_, i) => {
            return array.slice(i * size, i * size + size);
        });
    }

chunk should be the size you wanna to create/remove at one single time.

**Comment by knicefire** [comment]
There is still some official documentation adjustments needed as it suggests bad code example that most people would follow without giving it a second thought

https://orkhan.gitbook.io/typeorm/docs/repository-api

![Image](https://github.com/user-attachments/assets/328149a1-79bd-41e5-a728-0af30f070277)

It should be something like 

```
// users contains array of User Entities
userRepository.save(users, { chunk: 1000 })
```
