### ISSUE TITLE
What is the right/recommended way for error handling?

### ISSUE THREAD

**Issue by aldee07** [typeorm/typeorm#5057]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x` (0.2.20)

**Steps to reproduce or a small repository showing the problem:**

I see no hint of being able to handle database calls error properly. In my case, I have to catch duplicate entry error as follow:

#### // user.repository.ts
```ts

const result = this.save(user)
      .catch((err: any) => {
          console.log(err);
      });
```
...and this is what I got

```js 
{
  message: 'ER_DUP_ENTRY: Duplicate entry ' +
    "'a.xxxxxxxx@xxxxx.com' for key " +
    "'IDX_97672ac88f789774dd47f7c8be'",
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlMessage: "Duplicate entry 'a.xxxxxxxx@xxxxx.com' " +
    "for key 'IDX_97672ac88f789774dd47f7c8be'",
  sqlState: '23000',
  index: 0,
  sql: 'INSERT INTO `users`(`id`, `email`, `password`, `firstname`, ' +
    '`lastname`, `status`, `token`) VALUES ' +
    "('3433c6a6-6a64-4071-bf77-6a752a09879f', 'a.xxxxxxxx@xxxxx.com', " +
    "'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', " +
    "'Aldee', 'XXXXXX', 'active', 'aa86b69a0b1f5')",
  name: 'QueryFailedError',
  query: 'INSERT INTO `users`(`id`, `email`, `password`, `firstname`, ' +
    '`lastname`, `status`, `token`) VALUES (?, ?, ?, ?, ?, ?, ?)',
  parameters: [
    '3433c6a6-6a64-4071-bf77-6a752a09879f',
    'a.xxxxxxxx@xxxxx.com',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'Aldee',
    'XXXXXX',
    'active',
    'aa86b69a0b1f5'
  ]
}
```

As you can see, the `code` property is available as well as the `errno`. 
The exception thrown says that it is an instance of `QueryFailedError`. 

Ok, so now, in the case above, I can modify my code and handle duplicate error exception like this:

```ts
const result = this.save(user)
      .catch((err: any) => {
        if (err instanceof QueryFailedError) {
          switch (err.code) { 
            case: 'ER_DUP_ENTRY':
               // do something
               break;
          }
        }
      });
```

But not so fast! The argument of the `switch` throws an error because the `QueryFailedError` class doesn't contain `code` property.

To bypass that issue, I just omitted the `instanceof` checking and `switch` part.

```ts
const result = this.save(user)
      .catch((err: any) => {
        switch (err.code) {
          case 'ER_DUP_ENTRY':
            // do something....
            break;
        }
      });
```

It's working if I bypass the typing (using `any`) but it adds some risk if the API changes in the future. Is there any neat way to do this?

**Comment by aldee07** [comment]
Also, is there any interface or enum for the error code? The same way nestjs implemented it for the [HttpStatus](https://github.com/nestjs/nest/blob/master/packages/common/enums/http-status.enum.ts).

**Comment by drdgvhbh** [comment]
A type guard might work in this scenario

```ts
const queryFailedGuard = (
  err: any
): err is QueryFailedError & { code: string } =>
  err instanceof QueryFailedError;
if (queryFailedGuard(err)) {
  // do something
}

```

**Comment by m-nikhil** [comment]
Can we add a field 'driver error' to QueryFailedError? So we can get the driver error and make a decision.

Now there's a necessity to avoid the Type QueryFailedError, as it can't give the driver error info.

**Comment by m-nikhil** [comment]
If the solution is promising, please guide me to fix the same. Thanks.

**Comment by imnotjames** [comment]
Looks like this was answered!

**Comment by lightnet328** [comment]
These days, `pg-protocol` can be used. This is used inside `pg` so I think we can get a better type.

```typescript
import { QueryFailedError } from 'typeorm';
import { DatabaseError } from 'pg-protocol';

export const isQueryFailedError = (err: unknown): err is QueryFailedError & DatabaseError =>
  err instanceof QueryFailedError;
```

https://www.npmjs.com/package/pg-protocol

https://github.com/brianc/node-postgres/blob/ec1dcab966ecb03080e75112f6d3623d1360b634/packages/pg-protocol/src/messages.ts#L97

**Comment by Minishlink** [comment]
@lightnet328 This does not look to contain any enum types for the actual db error

**Comment by hkar19** [comment]
as suggested by @lightnet328 in [here](https://github.com/typeorm/typeorm/issues/5057#issuecomment-734442426)

either way you can cast the error such as:
```ts
      if (error instanceof QueryFailedError) {
        const err = error.driverError as DatabaseError;
        
        if (err.code === '23505') {
          throw new ConflictException('username already exist');
        }
      }
```

**Comment by Hiroki111** [comment]
@lightnet328 

```
import { QueryFailedError } from 'typeorm';
import { DatabaseError } from 'pg-protocol';

export const isQueryFailedError = (err: unknown): err is QueryFailedError & DatabaseError =>
  err instanceof QueryFailedError;
```

This looks cool, but `DatabaseError` doesn't seem to work with typeorm.

```
// Function for saving an entity
async function saveUser(payload: Payload) {
  await getRepository(UserEntity).save({ payload });
}

// Error handler
import { DatabaseError } from 'pg-protocol';
import { QueryFailedError } from 'typeorm';

export function DbErrorHandler(err: unknown, req: Request, res: Response, next: NextFunction): void {
  if (err instanceof QueryFailedError) {
    console.log('Instance of QueryFailedError!'); // This is printed
  }

  if (err instanceof DatabaseError) {
    console.log('Instance of DatabaseError!'); // This isn't printed
  }
}
```

Here are the versions of the relevant dependencies
```
"typeorm": "^0.2.32"
"typescript": "4.3.4"
"pg-protocol": "^1.5.0"
```

**Comment by micalevisk** [comment]
@Hiroki111 typeorm didn't know about `DatabaseError` class or any other (AFIK) since they don't want to be tied with this lib. Thus you can't use `err instanceof DatabaseError` (when `err` is an object created by typeorm).

Instead you need to compare the fields in `err` that `DatabaseError` defines. Doing something like:

```ts
if (isQueryFailedError(err))
  if (err.code === '23505')
     throw new ConflictException()
```

**Comment by wdifruscio** [comment]
Great thread.. I feel like some of these strategies should be added to docs somewhere..

**Comment by matterai** [comment]
As @hkar19 already mentioned seems like mostly correct way to deal with different Postgres exceptions is to handle [PostgreSQL Error Codes](https://www.postgresql.org/docs/current/errcodes-appendix.html) which are placed in `sqlState` field. So basically you can user `switch` statement based on that field.

**Comment by Jarrettproperty5** [comment]
Here’s what https://nodejser.space/questions/tips-for-correcting-a-mysql-error-message-for-duplicate-entries I found: the answer
