### ISSUE TITLE
Schema sync/drop in 0.1.0-alpha.3

### ISSUE THREAD

**Issue by hrbcksq** [typeorm/typeorm#506]
I've got some problems with typeorm@0.1.0-alpha.3:

`typeorm schema:sync`

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.metadataArgsStorage.filterTables is not a function`

The same issue with `schema:drop` command.
nodejs: v6.10.3
env: windows 10 x64
server: PostgreSQL 9.4.11 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit"

By the way: where can i find the information about debug way for typeorm cli commands?
Thanks.

**Comment by pleerock** [comment]
You have this issue because your `ormconfig.json` is not an array, ormconfig.json should contain an array of connection options, e.g.:

```json
[{
  "driver": {
    "type": "mysql",
    "host": "localhost",
    "port": "$databasePort$",
    "username": "test",
    "password": "test",
    "database": "test",
    "usePool": true,
    "extra": {
      "timezone": "utc"
    }
  },
  "autoSchemaSync": true,
  "entities": [
    "modules/**/entity/{*.ts,*.js}"
  ],
  "subscribers": [
    "modules/**/subscriber/{*.ts,*.js}"
  ]
}]
```

> where can i find the information about debug way for typeorm cli commands? 

you debug it just the regular way you usually debug javascript

**Comment by hrbcksq** [comment]
Thank you very much!
