### ISSUE TITLE
TypeORM + Webpack: RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?

### ISSUE THREAD

**Issue by dong-dohai** [typeorm/typeorm#5064]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

I am using Webpack to build my Typescript app with TypeORM.

When I run the built artefact I have the following problem:
```
RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?
```
Afaik, the reason for this error is that Webpack bundle all files into a single file, which causes the entity setting not correct anymore.

Has anyone been able to setup TypeORM with Webpack? Please share your config :).

Thanks in advance.

**Comment by rustamwin** [comment]
Could you provide your config?

**Comment by dong-dohai** [comment]
I managed to solve my issue.

The problem is that Webpack bundles all of our code into a single file, so my config, which using blob can't find my entities. I fixed the above issue by importing and passing the class directly to `entities` property in my connection option.

**Comment by gtpan77** [comment]
If you are using SnakeNamingStrategy of "typeorm-naming-strategies" library, then you can't use entity classes for getting repositories if their name is not in snake case.
I created a entity class UserLedger.
`import { UserLedger } from "../entity/UserLedger";`
`this.userLedger = getRepository(UserLedger);`
It was failing and throwing error. RepositoryNotFoundError: No Repository for "UserLedger" was found.

changed the entity name to "user_ledger", it fixed the issue.
`this.userLedger = getRepository("user_ledger");`

**Comment by prashant-padwal** [comment]
@dong-dohai can you please provide the code snippets how you have configured it in orm.config.ts ?

The problem is that Webpack bundles all of our code into a single file, so my config, which using blob can't find my entities. I fixed the above issue by importing and passing the class directly to entities property in my connection option.

**Comment by Pomile** [comment]
I resolved setting entities property to  ```[join(__dirname, '/../**/', '*.entity.{ts,js}')]``` in connection option
e.g ```entities: [join(__dirname, '/../**/', '*.entity.{ts,js}')]```

**Comment by Alynva** [comment]
> If you are using SnakeNamingStrategy of "typeorm-naming-strategies" library, then you can't use entity classes for getting repositories if their name is not in snake case. I created a entity class UserLedger. `import { UserLedger } from "../entity/UserLedger";` `this.userLedger = getRepository(UserLedger);` It was failing and throwing error. RepositoryNotFoundError: No Repository for "UserLedger" was found.
> 
> changed the entity name to "user_ledger", it fixed the issue. `this.userLedger = getRepository("user_ledger");`

This solved for me, but as I'm using ts, I had to add `EntityTarget<ContribuicaoEntity>` as the type of the string, so the typings aren't `unkown`
