### ISSUE TITLE
Integration with @kaviar/nova ?

### ISSUE THREAD

**Issue by theodorDiaconu** [typeorm/typeorm#5066]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[x] `mongodb`

I would like to know whether we can integrate the nova-driver that allows high-speed relational linking between mongo collections? Or, how would I go about to write an integration myself? 

https://github.com/kaviarjs/nova#readme

**Comment by imnotjames** [comment]
It's not supported & does a lot of what we already attempt to do.

If you'd like to use it you can grab the underlying mongo client off a query runner.

For  other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
