### ISSUE TITLE
ORA-00972: identifier is too long on joins with FindOptions

### ISSUE THREAD

**Issue by derSoerrn95** [typeorm/typeorm#5067]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

It's a copy of #693, cause the issue was closed, but the error still exists - at least with oracle.

When I'm using one of the `getRepository(Entity).find({})` functions with realations array set in the `FindOptions`, I'm getting the `too long identifier` error. I think the main reason it doesn't work is because of Oracle, but I cannot be sure about it and I'm not able to change my db.. 

So it would be really cool, if anyone could make a PR, that allows the user to add an alias for `RelationOptions` or (the easier way) let the aliases only contain out of 1-2 letters.

**Comment by cesc1802** [comment]
i have same issue when table name and column name too long, alias name sometime wrong. for example i have 2 columns name CREATE_DATE and CREATE_BY into table BLABLABLABLABLABLA. alias name is BLABLABLABLABLABLA.CREATE_ and BLABLABLABLABLABLA.CREATE_ for 2 columns
