### ISSUE TITLE
comment doesn't escaped

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#5070]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

code:
```ts
@Column({
  comment: 'Consumer\'s Phone Number',
  length: 16
})
phone: string;
```

generate sql:
```sql
`phone` varchar(16) NULL COMMENT 'Consumer's Phone Number'
```

**Comment by Diluka** [comment]
- in code: `{comment: 'Consumer\'s Phone Number'}`
- in sql file: `"... NULL COMMENT 'Consumer\'s Phone Number' ..."`
- when execute: `NULL COMMENT 'Consumer's Phone Number'`

**Comment by imnotjames** [comment]
Is this still an issue?

**Comment by imnotjames** [comment]
It was. I took a crack at it and merged a fix into master.  Hopefully soon we can get a release cut!

**Comment by imnotjames** [comment]
PR in question is #6903
