### ISSUE TITLE
Website doesn't show documentation

### ISSUE THREAD

**Issue by Nargonath** [typeorm/typeorm#5073]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The website only show the navigation column but when you click on an item nothing shows up. Noticed on latest Chrome and latest Firefox Developer.
![image](https://user-images.githubusercontent.com/583657/68686840-8b4e6900-056c-11ea-81ab-7e74ef696c09.png)

**Comment by alfonsoal1983** [comment]
It works perfectly for me. Is it possible that the url has blocked your antivirus?

**Comment by Nargonath** [comment]
It was working the last week so that's strange. I'll wait a bit more and see later in the week how it goes.

**Comment by Nargonath** [comment]
Ok well it just came back the same way it disappeared in the first place: by magic. I'll close the issue.

**Comment by prabhat2505** [comment]
Its still not working

**Comment by mathews-mathai** [comment]
The documentation doesn't load for me either.
