### ISSUE TITLE
TypeORM doesn't work with Jest

### ISSUE THREAD

**Issue by haydennyyy** [typeorm/typeorm#5077]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.20` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

https://dev.azure.com/rlme/API/_git/API (Repository with the issue, database config in `src/utilities/database.ts`)

https://dev.azure.com/rlme/API/_build/results?buildId=8&view=results (ci failure. fails locally and in CI)

**Comment by haydennyyy** [comment]
Jest doesn't seem to be waiting for `connection.synchronize()` to complete, despite it being awaited in the config.

**Comment by silentroach** [comment]
I think you should make `Server.addDatabase` async and await there for `createConnection`

**Comment by haydennyyy** [comment]
@silentroach I did that and it seems to work better, but I don't think `await <model here>.remove({});` calls are working.

**Comment by silentroach** [comment]
`.remove` is used to remove entities (you should pass entities as arguments)

or if you want to truncate the table in tests, try to use `.clear()`

**Comment by haydennyyy** [comment]
I'm closing this. The company(?) I was working for is going under, so API dev is stopping. Thanks for the help though, I'll likely need to know this again.

**Comment by shirshak55** [comment]
@haydennyyy hey didn't u face problem with multiple test suites? Like how did u created Connection . I  get connection default not defined as it seems jest use worker and worker resolves fresh node_modules :(

**Comment by wi-ski** [comment]
Same issues here.
