### ISSUE TITLE
@OneToOne via a non primary column

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#508]
In the following example, Is it possible to join the `ModelReview` and `ItemInfo` tables via `modelId`, which isn't a primary column in `ItemInfo` ?

With this query:

````
 this.entityManager.createQueryBuilder(ModelReview, "m")
                .innerJoinAndSelect(`m.itemInfo`, 'i')
                .where("m.postId=:postId")
                .setParameter("postId", postId)
                .getMany()
````
The raw query ends up like this:

````
 FROM `model_review` `m` INNER JOIN `item_info` `i` ON `i`.`mid`=`m`.`modelId` WHERE `m`.`postId`=:postId
````
However, I was expecting this:

 FROM `model_review` `m` INNER JOIN `item_info` `i` ON **`i`.`modelId`**=`m`.`modelId` WHERE `m`.`postId`=:postId

How can I get the above result? I thought     
`@OneToOne(type=>ItemInfo,entity=>entity.modelId)` would tell the script to join `ItemInfo` via modelId, but it doesn't work.

````
export class ModelReview{
    @PrimaryGeneratedColumn()
    postId: number;

    @OneToOne(type=>ItemInfo,entity=>entity.modelId)
    @JoinColumn({name:'modelId'})
    itemInfo:ItemInfo;

    @Column({type:'int'}) // << THIS
    modelId:number;
}
````

````
export class ItemInfo{
    @PrimaryGeneratedColumn()
    variantId: number;

    @Column({type:'int'}) // << JOINS THIS
    modelId:number;
}
````

**Comment by pleerock** [comment]
Try to specify `referencedColumnName`

```ts
    @OneToOne(type=>ItemInfo,entity=>entity.modelId)
    @JoinColumn({name:'modelId', referencedColumnName: 'modelId'})
    itemInfo:ItemInfo;
```

**Comment by stonecold123** [comment]
@pleerock 
I don't see any change using `referencedColumnName`. It's still joinning `variantId` instead of `modelId`. Maybe it is a bug?

**Comment by pleerock** [comment]
can you provide a complete and small code example?

**Comment by pleerock** [comment]
Probably we can close it now.
