### ISSUE TITLE
migration:generate throws a SyntaxError with clean project template

### ISSUE THREAD

**Issue by darthmall** [typeorm/typeorm#5087]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.20` (or put your version here)

`typeorm migration:generate` throws a `SyntaxError` when you run it on a brand new project generated by `typeorm init`.

**Steps to reproduce or a small repository showing the problem:**

I set up a MySQL database (version 5.6) in a Docker container so that it was accessible via the default configuration in `ormconfig.json`. Then I did the following:

```bash
$ npx typeorm init
$ npm install
$ npx typeorm migration:generate -n User
```

This was the result:

```
Error during migration generation:
…/src/entity/User.ts:1
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Function.PlatformTools.load (…/node_modules/typeorm/platform/PlatformTools.js:109:28)
    at /media/evan.sheehan/workshop/tmp/typeorm_template/node_modules/typeorm/util/DirectoryExportedClassesLoader.js:39:69
    at Array.map (<anonymous>)
    at Object.importClassesFromDirectories (…/node_modules/typeorm/util/DirectoryExportedClassesLoader.js:39:10)
```

I would expect that, having changed nothing in the project template, I should be able to generate a migration for the User entity.

**Comment by Matiiii** [comment]
I have the same problem :(

**Comment by darthmall** [comment]
Well, I figured out a solution, but it's not pleasant. You need to make sure that it's executed with `ts-node`.

```
$ ./node_modules/.bin/ts-node ./node_modules/typeorm/cli.js migration:generate -n 'User'
```

That worked for me, but it'd be really nice if there was a way to set it up with a less cumbersome invocation. Not sure I'm finding a lot of value in the `typeorm` CLI if I can't just run it from the command line or an NPM script.

**Comment by msheakoski** [comment]
@darthmall That is the recommended way according to https://typeorm.io/#/migrations/running-and-reverting-migrations

I like to add a script to my package.json:
```json
"scripts": {
  "typeorm": "TS_NODE_PROJECT=tsconfig.ts-node.json TS_NODE_TRANSPILE_ONLY=true ts-node ./node_modules/typeorm/cli.js"
}
```
tsconfig.ts-node.json for reference:
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": { "module": "commonjs" }
}
```
and from that point, I run the typeorm cli using `yarn typeorm migration:generate -n User`

**Comment by TheBenji** [comment]
I had the same issue and after looking through it a bit it seems you have to change the `ormconfig.json` and change
```
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
```
to
```
   "entities": [
      "build/entity/**/*.js"
   ],
   "migrations": [
      "build/migration/**/*.js"
   ],
   "subscribers": [
      "build/subscriber/**/*.js"
   ],
```

Of course then running `npm run start` might not work as expected and you'll have to change that from `ts-node` to just use `node` and have a build step before and that seems to work.

Not sure if that's working as intended or is a bug...

**Comment by tundebabzy** [comment]
@msheakoski gave the 'TypeORM blessed way'. See https://typeorm.io/#/using-cli/if-entities-files-are-in-typescript for a better explanation and how to configure cli options in `ormconfig`

**Comment by ctrlplusb** [comment]
This drove me slightly insane. 

I tried the [answer](https://github.com/typeorm/typeorm/issues/5087#issuecomment-557385885) from @msheakoski but it wouldn't work.

In the end the following worked for me.

**Step 1: create a tsconfig that outputs modules as commonjs**

You are essentially extending your underlying tsconfig, ensuring that it will compile to `commonjs` module type.

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": { "module": "commonjs" },
}
```

**Step 2: add the npm script**

I had to explicitly pass the flag rather than use the env variable in order to get `ts-node` to use the correct config.

```json
{
  "scripts": {
    "typeorm": "ts-node --project tsconfig.ts-node.json ./node_modules/typeorm/cli.js"
  }
}
```

**Comment by msheakoski** [comment]
@ctrlplusb your approach is more cross-platform than mine with the same end goal accomplished. Are you by any chance doing this from Windows? If so, that would be why the env variables were not being picked up. The cross-env npm package is another option. It smooths out differences in how platforms handle env vars.

**Comment by ctrlplusb** [comment]
@msheakoski nope, using osx. Strange that it didnt work. Wonder if there was a change in ts-node.

**Comment by yutao1129** [comment]
In package.json
...
"typeorm": "ts-node ./node_modules/typeorm/cli.js"
...


In cmd/shell

npm run typeorm migration:generate -- -n "User"

`
npm run typeorm migration:generate -- -n "User"

> myProject@0.0.1 typeorm E:\xiangmu\typeormStudy\myProject
> ts-node ./node_modules/typeorm/cli.js "migration:generate" "-n" "User"

Migration E:\xiangmu\typeormStudy\myProject/src/migration/1596159641335-User.ts has been generated successfully.

`

**Comment by imnotjames** [comment]
This looks to be an issue with the environment and less with TypeORM.

For other questions & support not bug / feature / etc related, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by D4ITON** [comment]
> I tried the [answer](https://github.com/typeorm/typeorm/issues/5087#issuecomment-627743159) from @ctrlplusb

TypeError: The specified path does not exist: tsconfig.ts-node.json
