### ISSUE TITLE
Relation with Single Table Inheritance

### ISSUE THREAD

**Issue by ziofat** [typeorm/typeorm#5088]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a single table inheritance like this:
```ts
enum SourceType {
    RAID = 'raid'
    REPUTATION = 'reputation',
    REDEEM = 'redeem',
    ACTIVITY = 'activity',
    OTHER = 'other',
}

@Entity()
@TableInheritance({ column: { type: 'enum', enum: SourceType } })
export class Source {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column({
        nullable: true,
    })
    public comment?: string;
}

@ChildEntity()
export class RaidSource extends Source {
    @Column()
    public boss: string;
}

@ChildEntity()
export class ReputationSource extends Source {
    @Column()
    public reputation: string;
}

@ChildEntity()
export class RedeemSource extends Source {
    @Column()
    public redeem: string;
}

@ChildEntity()
export class ActivitySource extends Source {
    @Column()
    public activity: string;

    @Column()
    public limitedTime?: boolean;
}

@ChildEntity()
export class OtherSource extends Source {

}

@Entity()
export class Equip {
    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    public name: string;

    @ManyToMany(() => Source, source => source.id)
    @JoinTable()
    public source: Source[];
}
```

This is a database of game equipment. Every equip has one or more sources. It might be any of the child entities above.

I am using entity manager to get one equip with following code:
```ts
const equip = await manager.findOne(Equip, id, {
    relations: ['source'],
});
```

But the equip has only properties in `Source` entity, even if it has other properties in actual database table.

```ts
const equip = await manager.findOne(Equip, id, {
    relations: ['source', 'source.type'],
});
```
And try to get `type` at the same time cause error: Relation "source.type" was not found, please check if it is correct and really exist in your entity.

I am sure there was something I messed up. I believe normally entity should related to a child entity not the base one. But in this relation it needs to be. What is the correct way to do so?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by ziofat** [comment]
Well, I get it.

Child entities should have the discriminator value so the base entity can identify them. Still, `type` itself is not present. To make that work, you have to declare a column in the base entity.


```diff
enum SourceType {
    RAID = 'raid'
    REPUTATION = 'reputation',
    REDEEM = 'redeem',
    ACTIVITY = 'activity',
    OTHER = 'other',
}

@Entity()
-@TableInheritance({ column: { type: 'enum', enum: SourceType } })
+@TableInheritance({ column: { type: 'enum', enum: SourceType, name: 'type' } })
export abstract class Source {
    @PrimaryGeneratedColumn()
    @Title('ID')
    public id: number;

    @Column({
        nullable: true,
    })
    public comment?: string;

+   @Column({
+       type: 'enum',
+       enum: SourceType,
+   })
+   public type: SourceType;
}

-@ChildEntity()
+@ChildEntity(SourceType.RAID)
export class RaidSource extends Source {
    @Column()
    public boss: string;
}

-@ChildEntity()
+@ChildEntity(SourceType.REPUTATION)
export class ReputationSource extends Source {
    @Column()
    public reputation: string;
}

-@ChildEntity()
+@ChildEntity(SourceType.REDEEM)
export class RedeemSource extends Source {
    @Column()
    public redeem: string;
}

-@ChildEntity()
+@ChildEntity(SourceType.ACTIVITY)
export class ActivitySource extends Source {
    @Column()
    public activity: string;

    @Column()
    public limitedTime?: boolean;
}

-@ChildEntity()
+@ChildEntity(SourceType.OTHER)
export class OtherSource extends Source {

}
```

**Comment by ronnno** [comment]
In the example above - will the results of `await manager.findOne()` or `await manager.find()` include `source` instances of type `Source` (the parent) including only columns _it_ defines? Or will they be instances of the child classes, inferred by the discriminator column and inflated with all the additional columns they define?

In my use case some of the child entities are pretty heavy and I usually want to load them as relations only with the base Entity properties
