### ISSUE TITLE
Generated alias in persist operation is too long using Oracle Driver

### ISSUE THREAD

**Issue by joaoblopes** [typeorm/typeorm#509]
When persisting an object/entity that already exists in the Oracle database, the generated alias for columns is "operateSubject_COLUMN_NAME". If the COLUMN_NAME has more than 15 characters, we get error ORA-00972: identifier is too long.

Is there a way to configure the alias name?

2017-06-01T10:50:36.229Z - error: [24870] query failed: SELECT "operateSubject"."ID_USER" AS "operateSubject_ID_USER", "operateSubject"."ID_TENANT" AS "operateSubject_ID_TENANT", "operateSubject"."REGISTRATION_DATE" AS "operateSubject_REGISTRATION_DATE", "operateSubject"."ID_REGISTRATION" AS "operateSubject_ID_REGISTRATION", "operateSubject"."LAST_GPS_LATITUDE" AS "operateSubject_LAST_GPS_LATITUDE", "operateSubject"."LAST_GPS_LONGITUDE" AS "operateSubject_LAST_GPS_LONGITUDE", "operateSubject"."CREATED_DATE" AS "operateSubject_CREATED_DATE", "operateSubject"."CREATED_BY" AS "operateSubject_CREATED_BY", "operateSubject"."MODIFIED_DATE" AS "operateSubject_MODIFIED_DATE", "operateSubject"."MODIFIED_BY" AS "operateSubject_MODIFIED_BY" FROM "DRMS_T_TEG_USER" "operateSubject" WHERE "operateSubject"."ID_USER"=:id_0 -- PARAMETERS: [102]
2017-06-01T10:50:36.237Z - error: [24870] error during executing query:Error: ORA-00972: identifier is too long

**Comment by pleerock** [comment]
ahh those oracle limitations... we have discussion about them in #454

**Comment by vitorveiga** [comment]
Hello,

i'm curious about why the alias needs to be "operateSubject". Can not be word with a less characters? at least it will minimize the  "ORA-00972: identifier is too long.".

Best Regards

**Comment by pleerock** [comment]
damn `"ORA-00972: identifier is too long."` error.... Yeah we can make something shorter, but generally need to figure out some good solution what to do with stupid oracle limitations....

**Comment by mrbraca15** [comment]
i hace the same issue here, what can i do to remove the alias?

**Comment by pleerock** [comment]
its not possible to remove alias - ORM needs them to make proper entity bindings. Probably at the moment the only way to shorten column names. Thats very strange oracle limitation.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.

**Comment by ishwaryasrinivasan** [comment]
We also faced the same problem while using the previous version of typeorm. So we upgraded to this alpha version and the code fails with unable to find reposotory error. We are using javascript for our entity.
module.exports = {
	"name":"users",
	"table":{
		"name":"USERS"
	},
	"columns":{
		"USER_ID":{
			"type":"varchar2",
			"primary":"true"
		},
		"FIRST_NAME":{
			"type":"varchar2"
		},
		"LAST_NAME":{
			"type":"varchar2"
		},
		"EMAIL":{
			"type":"varchar2"
		},
		"CREATED_BY":{
			"type":"varchar2"
		},
		"CREATED_SDATE":{
			"type":"date"
		},
		"LAST_UPDATED_BY":{
			"type":"varchar2"
		},
		"LAST_UPDATED_SDATE":{
			"type":"date"
		}
	}
};
and we are registering the entities as below
typeorm.createConnection({
	    type: "oracle",
	    host: "localhost",
	    port: 1701,
	    schema:"test",
	    username: "test",
	    password: "test#999",
		sid: "localhost",
	    synchronize: false,
	    logging:true,
	    entitySchemas: [
	      	       require("./entity/users")
	    ]
	    
	})

how to register the entities with 0.2.0-alpha.23 version?

**Comment by pleerock** [comment]
In new version entity schemas must be wrapped into `EntitySchema` object, e.g.:

```ts
    entities: [
        new EntitySchema<Post>(require(...)),
    ]
```

See sample [here](https://github.com/typeorm/typeorm/blob/1606ab8afb812af588dca07eadaedbbc551e9a12/sample/sample24-schemas/app.ts#L29).

**Comment by ishwaryasrinivasan** [comment]
Thanks for the details. I could see that you have shared typescript sample. Can you please share javascript sample?

**Comment by pleerock** [comment]
there is no separate javascript example, but as you know its the same as typescript, you just remove type declarations, like `<Post>` and `:Post`
