### ISSUE TITLE
How do you type this query using repositories?

### ISSUE THREAD

**Issue by depyronick** [typeorm/typeorm#5091]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

```
                                         SELECT
						COUNT(*) AS likeCount,
						jargons.*
					FROM interactions
					INNER JOIN jargons ON jargons.id = jargon_id
					WHERE interaction_type = 'like'
					GROUP BY jargon_id
					ORDER BY likeCount DESC
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
