### ISSUE TITLE
TypeORM with Express and Date type

### ISSUE THREAD

**Issue by carlocorradini** [typeorm/typeorm#5093]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a simple Film entity with class-validator as Date on release_date field:
 ```ts
export default class Film {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  title!: string;

  @Column({type: 'date' })
  @IsDate({ message: '$property must be a Date type' })
  release_date!: Date;
}
 ```

Using with Express as example below:
 ```ts
 app.post("/film", async function(req: Request, res: Response) {
    const film = await getRepository(Film).create(req.body);
    const errors = await validate(film);

   if (errors.length > 0) {
       console.log(''validation error);
   } else {
       await getRepository(Film).save(film);
       console.log(''Success!!!)
   }
});
 ```
I always receive a validation error on release_date saying: "release_date must be a Date type".

**So my answer is how TypeORM can take a string Date from body and correctly convert it to a Date type so class-validator is happy with that?**

PS: I correctly use middleware body-parser with JSON, and my raw data example is as simple as it is:
 ```json
{
    "title": "Joker",
    "release_date": "2019-10-08"
}
 ```

Thanks in advance for the help 👍

**Comment by d337** [comment]
Firstly the issue is not regarding the TypeORM and secondly, you can try two of the following:

1. Use ```@IsDateString()``` instead of ```@IsDate()```
2. Or more convenient way is to use [class-transformer](https://www.npmjs.com/package/class-transformer)     [Converting date strings into objects](https://github.com/typestack/class-transformer#%D1%81onverting-date-strings-into-date-objects)

**Comment by carlocorradini** [comment]
> Firstly the issue is not regarding the TypeORM and secondly, you can try two of the following:
> 
> 1. Use `@IsDateString()` instead of `@IsDate()`
> 2. Or more convenient way is to use [class-transformer](https://www.npmjs.com/package/class-transformer)     [Converting date strings into objects](https://github.com/typestack/class-transformer#%D1%81onverting-date-strings-into-date-objects)

Thanks!!!
