### ISSUE TITLE
How to plug Prometheus to my database?

### ISSUE THREAD

**Issue by kerenfi** [typeorm/typeorm#5094]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I want to plug my database to Prometheus and create metrics mostly related to throughput, and latency.
I was wondering how should I approach this.
Is there something built-in, or should I catch a before/after event?

If someone has an example to share that would be great

**Comment by imnotjames** [comment]
This probably would be to be done firefly with the database, outside of typeorm.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
