### ISSUE TITLE
TypeOrmModule missing imports error

### ISSUE THREAD

**Issue by Akifcan** [typeorm/typeorm#5100]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

```
Hello i connected nestjs app and postresql db  but its give me error. I loaded necessary dependencies

import { Module } from '@nestjs/common';
import { TasksModule } from './tasks/tasks.module';
import { TypeOrmModule } from '@nestjs/typeorm';

@Module({
	TypeOrmModule.forRoot({
			type: 'postgres',
			host: 'localhost',
			port: 5432,
			username: 'postgres',
			password: 'postgres',
			database: 'taskmanagement',
			entities: [__dirname + '/../**/*.entity.{js,ts}'],
			synchronize: true,
		}
	),
	imports: [TasksModule],
})
export class AppModule {}
```

But its give me metadada error.
Error: `argument of type '{ TypeOrmModule: typeof TypeOrmModule; (Missing): any; imports: (typeof TasksModule[];}' is not object literal may only specify known properties and 'TypeOrmModules' doest not exist in type 'ModuleMetaData'.`

Console error: ```
src/app.module.ts:6:15 - error TS1005: ',' expected.

6  TypeOrmModule.forRoot({
                ~

11:01:27 AM - Found 1 error. Watching for file changes.
```
i installed this dependencies
-typeorm
-@nestjs/typeorm
-pg

**Comment by d337** [comment]
You should do something like these

```
@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'postgres',
      host: 'localhost',
      port: 5432,
      username: 'postgres',
      password: 'postgres',
      database: 'taskmanagement',
      entities: [__dirname + '/../**/*.entity.{js,ts}'],
      synchronize: true,
    }),
    TasksModule
  ],
})
```

**Comment by Akifcan** [comment]
i tried but still same

**Comment by TertAlex** [comment]
I have the same issue

**Comment by imnotjames** [comment]
This looks like a nestjs specific issue and not score typeorm issue, unfortunately.  I don't think we can help much on it.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
