### ISSUE TITLE
Escaping issue in ORDER BY  Clause - Error: ORA-00904: "ID": invalid identifier errorNum: 904, offset: 49

### ISSUE THREAD

**Issue by gerwinbrunner** [typeorm/typeorm#5102]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`
query: SELECT "TABLE_NAME" FROM "USER_TABLES" WHERE "TABLE_NAME" = 'MIGRATIONS'
query: CREATE TABLE "MIGRATIONS" ("id" number GENERATED ALWAYS AS IDENTITY, "timestamp" number NOT NULL, "name" varchar2(255) NOT NULL, CONSTRAINT "PK_983c4f16a86b461ae4f6d9c5753" PRIMARY KEY ("id"))
query: SELECT * FROM "MIGRATIONS" "MIGRATIONS" ORDER BY id DESC
query failed: SELECT * FROM "MIGRATIONS" "MIGRATIONS" ORDER BY id DESC
error: { Error: ORA-00904: "ID": invalid identifier errorNum: 904, offset: 49 }
`

This happens when I try to use migrations with an oracle DB. 
The issue is that the create statement has the "id" column with quotes, but the select directly after `SELECT * FROM "MIGRATIONS" "MIGRATIONS" ORDER BY id DESC` it does the order by id without the quotes - so it raises the error

The correct query would be `SELECT * FROM "MIGRATIONS" "MIGRATIONS" ORDER BY "id" DESC` 

Why is this happening?
Is there a way to solve this?
How can I force all column names to be upper case?

Best,
Gerwin

**Comment by gerwinbrunner** [comment]
Any hints how to fix this?

**Comment by imnotjames** [comment]
This was fixed by #5102
