### ISSUE TITLE
How to allow only one row for a table?

### ISSUE THREAD

**Issue by billyjov** [typeorm/typeorm#5105]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Ginden** [comment]
This is out of scope of this repo, but:

```
import {BaseEntity, Entity, PrimaryColumn} from 'typeorm';

@Entity()
@Check(`ensure = 1`)
export class Singleton extends BaseEntity {
@PrimaryColumn({type: 'int', default: () => `1`, nullable: false})
public ensure: 1;
}
```

**Comment by lueenavarro** [comment]
@Check does not enforce the condition for me

**Comment by imnotjames** [comment]
Is it actually getting defined in the database?  I can confirm it's working with 8.0.21

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
