### ISSUE TITLE
TypeORM seems to not respect the `database` field of Entity

### ISSUE THREAD

**Issue by petterroea** [typeorm/typeorm#5106]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm trying to seperate my TypeORM project over multiple databases as it is growing in size, and its components are very discrete(yet interlinked, so i need to be able to have relations cross-database).

I am trying to do that using the database setting on the `@Entity` decorator, as described here: https://typeorm.io/#multiple-connections/using-multiple-databases-in-a-single-connection

However, It does not seem like it is working. I expect each entity to appear in the database i asked for. This is however not what happens

I made a MRE here: https://github.com/petterroea/TypeOrmBug-MRE - It uses docker to reproduce the exact environment it is running in

**Comment by imnotjames** [comment]
Postgres does not support multiple databases in a single connection. 

It also - as far as I know - does not support cross-database foreign keys, constraints, or joins - so a cross-database relation would be very difficult.
