### ISSUE TITLE
Allow for Generics to be used to define Entities on the connection

### ISSUE THREAD

**Issue by ScottMGerstl** [typeorm/typeorm#511]
I am looking to structure my code by feature rather than tier. I want to create a folder structure that allows me to put my implementation of the database for a specific feature in the same folder with the rest of the code. To that end, I want to create a single framework file that allows me to pass in the type I want to connect to and persist and use this class generically. 

Here is an example of what I would like to do:

```
import { createConnection } from "typeorm";

export class Orm {

    public getConnection<T>(): Promise<Connection> {

        return createConnection({
            driver: {
                type: "mysql",
                host: "localhost",
                port: 3306,
                username: "root",
                password: "admin",
                database: "test"
            },
            entities: [ T ],
            autoSchemaSync: true,
        });
    }
}
```

However, when doing this I get the error `'T only refers to a Type, but is being used as a value here.'`. I would appreciate it if you would provide a way to pass the type the createConnection method and use the connection for only that object (or multiple types if passed).

The idea here is that I would be able to return the connection inside of a promise and use async/await syntax after receiving the connection to operate on that table or tables.

Thanks!

**Comment by hugoserrana** [comment]
I think that you doesn't have to take connection always. Get all entities by path and configure typeorm only once, at start your application: 

```
 //Use options or ormconfig.json
 let dbOptions = {}  
 createConnection(dbOptions).then(connection => {
            console.log('Database connected!');
        }).catch(error => {
            console.log(error)
        });
```

Wharever you want use a connection, use getConnectionManager  for this. TypeOrm will handle this for you. Then you may try (I don't tested this):

```
import { getConnectionManager } from "typeorm";

export default class Orm {
    private repo: any;

    constructor(T) {
        this.repo = getConnectionManager().get().getRepository(T);
    }

    public getRepo(){
        return this.repo;
    }
}
```

but, is more simplier use directly where you need it:

```
import { getConnectionManager } from "typeorm";
impot User from './entity/User';

let repo = getConnectionManager().get().getRepository(User);

//And use repo to queries etc
```

**Comment by pleerock** [comment]
@ScottMGerstl  I think you didn't get how generics are working. 

`T` is needed to implement type safety, but in your case its not used anywhere which means you don't have something to make it type safe. Also `T` is compile-time stuff, its not actual code that will be outputed anywhere, so you can do what you did.

You simply need to do:

```ts
export class Orm {

    public getConnection(entities: Function[]): Promise<Connection> {

        return createConnection({
            driver: {
                type: "mysql",
                host: "localhost",
                port: 3306,
                username: "root",
                password: "admin",
                database: "test"
            },
            entities: entities,
            autoSchemaSync: true,
        });
    }
}
```

**Comment by pleerock** [comment]
Reopen discussion if you still have questions.
