### ISSUE TITLE
How to return a relation column as top level in response?

### ISSUE THREAD

**Issue by ejose19** [typeorm/typeorm#5111]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Suppose I have 2 Entites:

Entity1
- id
- entity2Id

Entity2
- id
- someValue

I want to join and receive the response as:

Entity 1 {
  id,
  entity2Id,
  someValue
}

but with getMany I receive:

Entity 1 {
  id,
  entity2Id,
  Entity2: {
    someValue
  }
}

and doing aliases I can get what I want with getRaw but I lose all the parse that typeorm brings when returning as entity instead of raw.

What's the cleanest way to accomplish this? Currently I'm iterating the array with .map() and flattening but if this could be solved directly from the sql/typeorm then it would be great.

**Comment by papaiatis** [comment]
@ejose19 have you ever found a solution for this? I have the same problem. I do not want to use `leftJoinAndSelect`. I only care about the foreign key column which is part of the source table.

**Comment by ejose19** [comment]
@papaiatis there's no native way as of typeorm 2.X, don't know if this is possible for 3.X, but I'm using .map to fixing it myself in the meanwhile, as the other solution would be doing a raw query and manually mapping (way less desirable)

**Comment by imnotjames** [comment]
This isn't possible, and is outside the scope of typeorm at this time.
