### ISSUE TITLE
Order by alphabet and then by numbers

### ISSUE THREAD

**Issue by dulkith** [typeorm/typeorm#5113]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**problem**
I want to sort records by UID, 
my UIDs are like 

> A5
>  A4
>  Z1
>  B2
>  C7
>  C1A
>  C11A
>  B1
>  B4

I want them to be sorted in this manner 

> A4
> A5
> B1
> B2
> B4
> C1
> C11A
> C7
> Z1
> 

This sql query can do it, How to do it with query builder?
`SELECT * FROM items ORDER BY SUBSTRING(uid,'\d+')::int`

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
