### ISSUE TITLE
#4476 breaks non-object simple-json columns

### ISSUE THREAD

**Issue by svvac** [typeorm/typeorm#5116]
Bug report for 0.2.20 (MySQL/MariaDB, but it probably is backend-independent)

[This added check][1] in PR #4476 forbids using `simple-json` columns with non-object values as it defaults to returning an empty object if the parsed value is not an object.

This breaks existing models that support e.g. string or number values in such a column.

```typescript
@Entity()
class ConfigValue {
    @PrimaryColumn()
    public key: string;

    @Column('simple-json')
    public value: any;
}

async function test (connection) {
    const repo = connection.getRepository(ConfigValue);
    const config = new ConfigValue({ key: 'numeric config', value: 42 })
    await repo.save(config);
    const read = await repo.findOne('numeric config');
    assert(read.value === 42); // fails
}
```

  [1]: https://github.com/typeorm/typeorm/pull/4476/files#diff-f0f40758177783349c31da1ee0725addR175

**Comment by svvac** [comment]
See PR #5125

**Comment by imnotjames** [comment]
Separate PR merged.  This will be fixed in next release.
