### ISSUE TITLE
Generate custom error strings

### ISSUE THREAD

**Issue by nosyminotaur** [typeorm/typeorm#5118]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How can I generate custom errors from the errors provided by TypeORM?
If I have an Entity Class and I have set a field as `nullable = false`,
I want to return a custom error when I do not provide any value in the class object
while saving or updating the database using the Repository or Manager.
How can I do that?
I want something like =>
```ts
@Column({error_message: "Sorry, field must be provided!"})
public item: string;
```
Instead of the default error.
Thanks!

**Comment by imnotjames** [comment]
This is outside the scope of TypeORM.  You'll need to catch the exceptions and rethrow them somehow if you'd like to change that.

---

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
