### ISSUE TITLE
Foreign keys whose referenced table change are not updated by migrations

### ISSUE THREAD

**Issue by csuich2** [typeorm/typeorm#5119]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

It appears that migrations do not generate up and down statements to modify a foreign key when the referenced table changes. This *maybe* be a dup of https://github.com/typeorm/typeorm/issues/3509, but I have a reproduction repo and believe I found the root cause and potential solution.

After digging for a solution, I found that `DefaultNamingStrategy` does not incorporate the referenced table name when generating a foreign key name, despite it being a parameter to the method.

Off the top of my head, I see two solutions so far:

1. Update the naming strategy to incorporate the referenced table name. However, this would cause a lot of noise for all users since all foreign keys would be renamed.
2. Update `RdbmsSchemaBuilder.dropOldForeignKeys()` and `RdbmsSchemaBuilder.createForeignKeys()` to check for the change in referenced table name and generate a new FK with the same name.

Any other thoughts on how to fix this?

**Comment by csuich2** [comment]
@pleerock @Kononnable Any thoughts on this? I'm happy to do the work and file the PR if we can agree on the fix.

**Comment by osdiab** [comment]
I too am experiencing this problem and perhaps can pitch in a little bit, but i'm slow since i don't really know in much detail how this repo works.

**Comment by osdiab** [comment]
Option 2 sounds like the way to go to avoid messing up people's existing databases - i'll see if i can make it work lightweight
