### ISSUE TITLE
TableName doesn't get escaped in UPDATE

### ISSUE THREAD

**Issue by bartlomiej-korpus** [typeorm/typeorm#512]
The tableName doesn't get escaped in UPDATE in QueryBuilder. It is a problem for certain naming strategies.
[Guilty line of code](https://github.com/typeorm/typeorm/blob/master/src/query-builder/QueryBuilder.ts#L1602)

I will try to sent a PR later.

I am wondering if I should do it on master or query builder refactoring. @pleerock

**Comment by pleerock** [comment]
please do it against `0.1.0` branch

**Comment by pleerock** [comment]
released in `0.1.0-alpha.4`

**Comment by bartlomiej-korpus** [comment]
@pleerock This also occurs in 0.0.11, can you consider merging it to that branch and releasing a patch? Its a major issue.

**Comment by pleerock** [comment]
create PR against 0.0.x branch and I'll release a new version
