### ISSUE TITLE
how to know which line case EntityNotFound 

### ISSUE THREAD

**Issue by ruandao** [typeorm/typeorm#5123]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X] `0.x.x` (or put your version here)
"typeorm": "^0.2.20"

**Steps to reproduce or a small repository showing the problem:**

when i  start new project, the project was change often, and i clear database and run migration each time

but some times, it will throw Exception like the following:

```
(node:13331) UnhandledPromiseRejectionWarning: EntityNotFound: Could not find any entity of type "Project" matching: {
    "where": {}
}
    at new EntityNotFoundError (/Users/cpu/gitClone/nyd-server/src/error/EntityNotFoundError.ts:11:9)
    at /Users/cpu/gitClone/nyd-server/src/entity-manager/EntityManager.ts:910:39
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:13331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
promist:  Promise { <pending> }
```

I not sure which line case this exception, in many place I use the `Project` entity

**Comment by stingers** [comment]
Hi! did you find a solution for the issue ? I 'm farcing the same error and don't know what is wrong

**Comment by ruandao** [comment]
sorry i forget how i solve it
