### ISSUE TITLE
Incorrect time/datetime types for SQLite

### ISSUE THREAD

**Issue by cfowlerdev** [typeorm/typeorm#513]
Using the SQLite driver, when defining a column type as "time" or "datetime" it creates the column as "timestamp without time zone" or "timestamp with time zone" depending on whether or not the "timezone" flag is set.
This column type is only currently supported by Postgres (as even pointed out in ColumnOptions.d.ts).
Oddly enough it seems to work when setting "timezone: true", but not when I set it to false.
Ideally, according to SQLite docs and various blogs, date time columns should be defined as TEXT types in SQLite db.
I'm running TypeORM 0.0.11 with SQLite3 driver 3.1.8, and validating with DB Browser 3.9.1 on MacOS.
Happy to do a PR, but wanted to check the vibe on this first...

**Comment by pleerock** [comment]
yes please create a PR for this feature. Fix is [there](https://github.com/pleerock/typeorm/blob/4e2c095ba54518afa953efb690788e9770a272ca/src/driver/sqlite/SqliteQueryRunner.ts#L774-L774). Please create PR against `0.1.0` branch. Also the most important you should include tests in a PR. Thank you

**Comment by Ciantic** [comment]
This is not working when deing SELECTS with find or query builder.

Insert works just fine:
```
INSERT INTO "my_entity"("date") VALUES (?) -- PARAMETERS: ["2000-01-01 00:00:00.000"]
```

However, with select it uses wrong format:

```
SELECT "MyEntity"."id" AS "MyEntity_id", "MyEntity"."date" AS "MyEntity_date" FROM "my_entity" "MyEntity" WHERE "MyEntity"."date" = ? -- PARAMETERS: ["2000-01-01T00:00:00.000Z"]
```


Stand alone test that fails:
```
import { createConnection, getConnection, Entity, getRepository } from "typeorm";
import { PrimaryGeneratedColumn, Column } from "typeorm";

@Entity()
export class MyEntity {
    @PrimaryGeneratedColumn()
    id?: number;

    @Column()
    date!: Date;
}

beforeEach(() => {
    return createConnection({
        type: "sqlite",
        database: ":memory:",
        dropSchema: true,
        entities: [MyEntity],
        synchronize: true,
        logging: true
    });
});

afterEach(() => {
    let conn = getConnection();
    return conn.close();
});

test("store Date and find it", async () => {
    await getRepository(MyEntity).insert({
        date: new Date("2000-01-01T00:00Z")
    });
    let found = await getRepository(MyEntity).find({
        where: {
            date: new Date("2000-01-01T00:00Z")
        }
    });
    expect(found[0].date).toBe(new Date("2000-01-01T00:00Z"));
});
```
