### ISSUE TITLE
I cannot get migration on postgres to work

### ISSUE THREAD

**Issue by rubiin** [typeorm/typeorm#5136]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a repo hosted at www.github.com/rubiin/test

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by UnsolvedCypher** [comment]
Could you provide some more information? What did you attempt to do and what was the result?

**Comment by rubiin** [comment]
whenever i attempt to change a field and generate migration, i get all the initial queries instead of just the alter query
