### ISSUE TITLE
Entities not creating tables in postgres

### ISSUE THREAD

**Issue by kylemann16** [typeorm/typeorm#5141]
**Issue type:**

[ x ] question
[ ? ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ 0.2.20 ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hey there,

I'm having problems producing tables using the entities described in the documentation. I need to be able to initialize a database from scratch, create all the tables and their associated parts. In the docs it says that using Entities will create a database table, but no iteration of my code allows me to do this. I think I have to be doing something wrong.

I'm currently having to completely circumvent the Entity part of typeorm and I'm using query builders and the `createTable` method, but I feel like that's not the intended work flow.

Am I doing something incorrectly? Am I reading the documentation incorrectly? What am I missing?

Here is an example of simplest entity I could think of to create and I failed to get it:

```ts
import { Entity, Column, PrimaryColumn } from 'typeorm';

@Entity()
export class Test {
    @PrimaryColumn("text")
    test_primary!: string;

    @Column("text")
    test_column_1!: string;

    @Column("text")
    test_column_2!: string;
}
```
The connection code:
```ts
import { createConnection, Connection } from 'typeorm';

createConnection({
    type: "postgres",
    host: "localhost",
    port: 5433,
    username: "test",
    password: "test",
    database: "test",
    synchronize: true,
    logging: true,
    entities: [
        Test
    ]
})
.then((connection: Connection) => {
    console.log("created connection", connection.isConnected)
})
.catch(err => {
    console.log("error.", err)
})
```

The postgres creation code, I'm just using the latest docker image of postgres:
```
docker run -d --name db-test -it --rm -p 5433:5432 -e POSTGRES_PASSWORD=test -e POSTGRES_DB=test -e POSTGRES_USER=test postgres
```

The output I get from running: 
```
query: START TRANSACTION
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'typeorm_metadata'
query: COMMIT
created connection true
```

The output from querying the database:
```
$ psql -h localhost -W --username test --dbname test -p 5433
Password for user test: 
psql (10.10 (Ubuntu 10.10-0ubuntu0.18.04.1), server 12.1 (Debian 12.1-1.pgdg100+1))
WARNING: psql major version 10, server major version 12.
         Some psql features might not work.
Type "help" for help.

test=# \d
Did not find any relations.
test=# \dt
Did not find any relations.
test=# \dn
List of schemas
  Name  | Owner 
--------+-------
 public | test
(1 row)
```

What I expected to find was a table created named test with columns test_primary, test_column_1 and test_column_2.

Thank you very much for any kind of advice or information you can help me with.

**Comment by kylemann16** [comment]
After updating my typescript version, typescript config, and changing to version 11.5 of postgres (12 causes other problems), this has been fixed.

**Comment by alysonfs** [comment]
hi, I fixed added  **autoLoadEntities: true,**  in connection config: 

`import { createConnection, Connection } from 'typeorm';

createConnection({
    type: "postgres",
    host: "localhost",
    port: 5433,
    username: "test",
    password: "test",
    database: "test",
    synchronize: true,

    **autoLoadEntities: true,**

    logging: true,
    entities: [
        Test
    ]
})
.then((connection: Connection) => {
    console.log("created connection", connection.isConnected)
})
.catch(err => {
    console.log("error.", err)
})`

**Comment by gagandua078** [comment]
> hi, I fixed added **autoLoadEntities: true,** in connection config:
> 
> `import { createConnection, Connection } from 'typeorm';
> 
> createConnection({ type: "postgres", host: "localhost", port: 5433, username: "test", password: "test", database: "test", synchronize: true,
> 
> ```
> **autoLoadEntities: true,**
> 
> logging: true,
> entities: [
>     Test
> ]
> ```
> 
> }) .then((connection: Connection) => { console.log("created connection", connection.isConnected) }) .catch(err => { console.log("error.", err) })`

This worked like a charm - 
    autoLoadEntities: true,
