### ISSUE TITLE
Column names should not be escaped for Oracle

### ISSUE THREAD

**Issue by judavi** [typeorm/typeorm#5142]
**Issue type:**

 

[ ] question

[X ] bug report

[ ] feature request

[ ] documentation issue

 

**Database system/driver:**

 

[ ] `cordova`

[ ] `mongodb`

[ ] `mssql`

[ ] `mysql` / `mariadb`

[X ] `oracle`

[ ] `postgres`

[ ] `cockroachdb`

[ ] `sqlite`

[ ] `sqljs`

[ ] `react-native`

[ ] `expo`

 

**TypeORM version:**

 

[X ] `latest`

[ ] `@next`

[ ] `0.x.x` (or put your version here)

 

**Steps to reproduce or a small repository showing the problem:**

 

Having a simple view like:

```sql

create table NOTES

(

    NOTE_NAME    VARCHAR2(3000) not null

)

```

And an entity like:

```js

import {ViewEntity, ViewColumn} from "typeorm";

 

@ViewEntity({

    expression: `

      SELECT NOTE_NAME FROM NOTES WHERE PROJECT_NAME = 'twistlock'

    `,

    materialized: false,

    name: "TNOTES"

})

export class Tnotes {

 

    @ViewColumn()

    note_name!: string;

 

}

```

And a simple query:

```js

connection.getRepository(Tnotes).find();

```

 

TypeOrm will fail with the next error:

```

query: SELECT "Tnotes"."note_name" AS "Tnotes_note_name" FROM "TNOTES" "Tnotes"

PlatformTools.ts:222

query failed: SELECT "Tnotes"."note_name" AS "Tnotes_note_name" FROM "TNOTES" "Tnotes"

PlatformTools.ts:226

error:

PlatformTools.ts:226

Error: ORA-00904: "Tnotes"."note_name": invalid identifier

```

The query should be

```

SELECT "Tnotes".note_name AS "Tnotes_note_name" FROM "TNOTES" "Tnotes"

```

In case you need an Oracle DB for testing:

```

docker run -d -p 8080:8080 -p 1521:1521 quay.io/maksymbilenko/oracle-12c

 

"type": "oracle",

        "host": "localhost",

        "port": 1521,

        "username": "system",

        "password": "oracle",

        "sid": "xe",

```

Thanks for the help!

**Comment by dennis-d** [comment]
I think you need to change   
`escape(columnName: string): string {
        return '"${columnName}"';
    }`
in OracleDriver.ts:339

**Comment by imnotjames** [comment]
I can't seem to replicate this issue & all of our oracle tests pass.  Is this still an issue?
