### ISSUE TITLE
How to perform a left join on an inner join?

### ISSUE THREAD

**Issue by shawnkoh** [typeorm/typeorm#5143]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi, I'm trying to perform a left join on an inner join subquery but I'm not sure how do I go about doing this in typeORM's query builder.

This is what I tried
```ts
getRepository(Script)
  .createQueryBuilder("script")
  .where("script.id = :scriptId", { scriptId })
  .andWhere("script.discardedAt IS NULL")
  .leftJoin("script.questions", "question", "question.discardedAt IS NULL")
  .innerJoin(
    "question.questionTemplate",
    "questionTemplate",
    "questionTemplate.discardedAt IS NULL"
  )
  .select("questionTemplate.id", "id")
  .addSelect("questionTemplate.name", "name")
  .getRawMany();
```

The problem is that it is trying to inner join "question.questionTemplate" when there is no question, hence the query returns null.

How do I write a leftJoin subquery such that it will only leftJoin the script with (question innerJoin questionTemplate)?

I apologise if this question is a duplicate, but the examples on https://typeorm.io/#/select-query-builder/using-subqueries and the answers on https://github.com/typeorm/typeorm/issues/2132 do not seem to help.

**Comment by thiago-soliveira** [comment]
Hey.. @shawnkoh 

I had this same question and [this issue](https://github.com/typeorm/typeorm/issues/869) helped me. 
It might help you as well.

Cheers

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
