### ISSUE TITLE
Strict Entity creation?

### ISSUE THREAD

**Issue by zxti** [typeorm/typeorm#5144]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[x] documentation issue

EntityManager.create() and other similar typeorm methods take a DeepPartial.  This means you can easily omit fields, esp. as you evolve the schema and add more new fields over time - you have to be diligent in ensuring the places that create objects are always passing all fields.

Is there a way to create a type-safe variant of this (without handcrafting a specialized function for every single DB type in a large schema)?  Something that is similar to .create() but requires all fields, except that foreign relationship fields can still accept e.g. `{id: "..."}` objects so that you don't have to actually fetch the full related object if you already have the ID handy? 

We are thinking of heading down the codegen path, but not sure if there was a simple solution we are overlooking.  Thanks.

**Comment by Quesstor** [comment]
Did you find a solution yet?

**Comment by imnotjames** [comment]
You'll want to use constructors or helpers for this.  `create` is effectively doing exactly what happens with deserialization.  We don't do validation & don't plan on it.  TypeORM relies on the database to enforce this.

**Comment by apiel51** [comment]
Arriving here after hitting a bug caused by failing to update all `create` calls for an entity after adding a non-nullable column.

@imnotjames Curious what the rationale is behind choosing not to validate entity creation - it seems to follow the TypeORM ethos of providing static type-checking to DB interactions.

**Comment by imnotjames** [comment]
Because the problem set of run time validation in typescript varies widely.  There are a number of tools that solve this, and there are use cases where you would not want run time validation.

Plus, like I said, the database should be performing validation during run time.

**Comment by apiel51** [comment]
@imnotjames 
Sorry if I was a bit vague - I'm specifically asking about _static type-checking_ related to `DeepPartial` like the original question outlines. And I understand that TypeORM doesn't provide static analysis, but it _does_ define the types that TS uses for validation. Having the DB handling runtime validation makes sense, but catching these bugs before they run is kind of the whole point of static analysis, right?
