### ISSUE TITLE
Add support to fuzzystrmatch on postgresql

### ISSUE THREAD

**Issue by benedictpmateo** [typeorm/typeorm#5145]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Add support to fuzzystrmatch on postgresql: https://www.postgresql.org/docs/9.1/fuzzystrmatch.html

**Comment by benedictpmateo** [comment]
Or I can just add this code in my database.service.ts
```ts

@Injectable()
export class DatabaseService {
  constructor(@Inject('Connection') public connection: Connection) {
    try {
      this.executeQuery(connection, `CREATE EXTENSION IF NOT EXISTS "fuzzystrmatch"`);
    } catch (error) {
      throw new AppError(AppErrorTypeEnum.SERVER_ERROR, error);
    }
  }

  protected executeQuery(connection: any, query: string) {
    return new Promise((ok, fail) => {
        connection.query(query, (err: any, result: any) => {
            if (err) { return fail(err); }
            ok(result);
        });
    });
  }
}
```

**Comment by pedrolcn** [comment]
I belive this would be better done as a migration. It should not be the application's responsibility to check for the availability or enable the extension in the DB. Less overhead and less code to be maintained later.

```typescript
export class EnableFuzzyStrMatchExtension implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner(`CREATE EXTENSION IF NOT EXISTS "fuzzystrmatch"'`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP EXTENSION IF EXISTS "fuzzystrmatch"`)
    }
}
```

**Comment by benedictpmateo** [comment]
> I belive this would be better done as a migration. It should not be the application's responsibility to check for the availability or enable the extension in the DB. Less overhead and less code to be maintained later.
> 
> ```ts
> export class EnableFuzzyStrMatchExtension implements MigrationInterface {
>     public async up(queryRunner: QueryRunner): Promise<any> {
>         await queryRunner(`CREATE EXTENSION IF NOT EXISTS "fuzzystrmatch"'`);
>     }
> 
>     public async down(queryRunner: QueryRunner): Promise<any> {
>         await queryRunner.query(`DROP EXTENSION IF EXISTS "fuzzystrmatch"`)
>     }
> }
> ```

I think this is the best way. Thank you for that.
