### ISSUE TITLE
Repository.create() is not setting data for embedded entities

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#515]
Hello!

I'm experiencing an unexpected behavior with embedded entities.

Consider, I have two classes defined this way:

```typescript
@Entity()
export class User {

  @PrimaryGeneratedColumn()
  id?: number;

  @Column()
  email?: string;

  @Embedded(type => UserProfile)
  profile?: UserProfile;

}
```

```typescript
@EmbeddableEntity()
export class UserProfile {

  @Column()
  firstName?: string;

  @Column()
  lastName?: string;

}
```

And my database table looking like this:

```sql
CREATE TABLE users (
  id serial,
  email text,
  profile jsonb NOT NULL DEFAULT '{}'
);
```

I'm trying to create new entity from data in a plain object:

```typescript
const user = Repository.create({
  email: 'john@example.com',
  profile: {
    firstName: 'John',
    lastName: 'Doe'
  }
});
```

But, when I examine the returned entity I can see that only `email` property is set. The `profile` property is missing from the created entity entirely.

Also, is my use case correct? I want to store sub-entities in one table inside of `jsonb` columns as binary JSON strings.

---

I've tried to compile `0.0.x-version` branch of the project in order to perform some tests, but sadly `tsc` throws a bunch of errors at me for some reason.

**Comment by pleerock** [comment]
> is my use case correct? 

no, it does not seem so. Embeds are nested objects which create columns in main entity for each column in nested object. In your case you schema will be generated this way:

```sql
CREATE TABLE users (
  id serial,
  email text,
  firstName varchar,
  lastName varchar,
);
```

> I've tried to compile 0.0.x-version branch of the project in order to perform some tests, but sadly tsc throws a bunch of errors at me for some reason.

please show me them so I can assist

Regarding to your issue, probably its not implemented yet - `create`/`preload` method does not work with embeds yet

**Comment by slavafomin** [comment]
Thanks for a quick reply.

How do you recommend to implement my use case? I want to store data as JSONB, but at the same way have a correct typing and probably member functions for embedded entities.

I've managed to persist data correctly, by defining my model this way:

```typescript
@Entity()
export class User {
  @Column(ColumnTypes.JSONB)
  profile?: UserProfile;
}
```

However, it looks like I will have to implement custom transformer (from plain object to my model) and to call it when creating a new entities and in onLoad listener in order to cast plain data loaded from the database to correct types. Is this approach looks reasonable to you?

Thanks!

---

Alos, here's the [compilation errors](https://gist.github.com/slavafomin/497913e761c7bbd49810395e8b60b403).

**Comment by pleerock** [comment]
Yeah, correct. If you want to convert jsonb object to the class instance you have to do it manually, in onload event, or anywhere else.

can you please tell me what branch are you trying to compile and what typescript compiler version do you have?

**Comment by slavafomin** [comment]
I've managed to implement JSONB embedded entities in TypeORM. It has a boilerplate and duplicated code, but it works good as a workaround. I will gladly see this implemented in TypeORM directly though.

I'm posting it here for peer review and as a reference for other developers, who are interested in this problem as well. I will gladly accept any comments and suggestions, thanks.

# User Model

```typescript
@Entity()
export class User {

  @PrimaryGeneratedColumn()
  id?: number;

  @Column()
  email?: string;

  @Column(ColumnTypes.JSONB)
  profile?: UserProfile;


  @AfterLoad()
  public afterLoad () {
    User.deserializeEmbeddedEntities(this, this);
  }


  public static fromPlainObject (plainObject: any): User {

    const user = new User();

    Object.assign(user, _.pick(plainObject, [
      'id',
      'email'
    ]));

    User.deserializeEmbeddedEntities(user, plainObject);

    return user;

  }

  public static deserializeEmbeddedEntities (user: User, plainObject: any) {

    if (plainObject.profile) {
      user.profile = UserProfile.fromPlainObject(plainObject.profile);
    }

  }

}
```

# User Profile (JSONB Embedded Entity)

```typescript
export class UserProfile {

  @Column()
  firstName?: string;

  @Column()
  lastName?: string;


  public static fromPlainObject (plainObject: any): UserProfile {

    const userProfile = new UserProfile();

    return _.extend(userProfile, _.pick(plainObject, [
      'firstName',
      'lastName'
    ]));

  }

}
```

When user entity is loaded from the database, it's `profile` property is set to plain JavaScript object. Then, I'm using `AfterLoad` listener to call `deserializeEmbeddedEntities()` static method which takes plain object and converts it to a proper instance class, i.e. `UserProfile`, by calling `fromPlainObject()` static method, which just creates a new instance of the class from plain objects.

Also, user's class has it's own `fromPlainObject()` method in order to create valid entities from plain data (sent in HTTP request for example).

---

Here's the info regarding branch compilation:

```
$ git status
On branch 0.0.x-version
```

```
$ tsc --version
Version 2.3.3
```

**Comment by pleerock** [comment]
I'll close it for now since transformers can be used for this purpose.
