### ISSUE TITLE
TypeORM modifies oracledb driver options at the global level, causing shenanigans

### ISSUE THREAD

**Issue by tkambler** [typeorm/typeorm#5150]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

TypeORM modifies a number of [oracledb driver](https://github.com/oracle/node-oracledb/blob/master/doc/api.md) options at the global level, which causes problems for applications that are also using the driver directly and are reliant upon the default behavior. Here are the three instances I've found:

- [oracle.outFormat](https://github.com/typeorm/typeorm/blob/master/src/driver/oracle/OracleDriver.ts#L220)
- [oracle.fetchAsString](https://github.com/typeorm/typeorm/blob/master/src/driver/oracle/OracleDriver.ts#L243)
- [oracle.fetchAsBuffer](https://github.com/typeorm/typeorm/blob/master/src/driver/oracle/OracleDriver.ts#L244)

Rather than setting these options in this manner, TypeORM should instead pass them as options to the connection object's `execute()` method.

**Comment by imnotjames** [comment]
```
oracle.fetchAsString
oracle.fetchAsBuffer
```

these two can't be passed into the `execute`.  It only allows for individual columns.
