### ISSUE TITLE
Custom Validator 

### ISSUE THREAD

**Issue by mgeisman** [typeorm/typeorm#5153]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there an option to validate a parameter which is a string, that can be one of Enum values or just a string of numbers. 

For example:

dto:
```
  @ApiModelProperty()
  @IsString()
  phone_number_expression: string;
```

enum:
``` 
export enum BlockingOptions {
  INFORMATION = 'INFORMATION',
  BLOCKED = 'BLOCKED',
}
```

phone_number_expression can be one of the values of BlockingOptions OR some string number: for example "123". 

Is it possible to add a special validator for that?

**Comment by TrejGun** [comment]
yes you can

```js
import {
  ValidationArguments,
  ValidationOptions,
  ValidatorConstraint,
  ValidatorConstraintInterface,
} from "class-validator";


@ValidatorConstraint()
class CustomValidation implements ValidatorConstraintInterface {
  private reason: string;

  public validate(value: any, args: ValidationArguments): boolean {
    this.reason = this.isValid(value, args);
    return !this.reason;
  }

  public defaultMessage(): string {
    return this.reason;
  }

  private isValid(value: any, args: ValidationArguments): string {
 
   // do your validation here
   // return "error";

    return "";
  }
}
```

**Comment by imnotjames** [comment]
I'd definitely suggest using a third party library for business-logic validations.  We're probably not going to add it natively in TypeORM.
