### ISSUE TITLE
How to deal with migrations in React-Native?

### ISSUE THREAD

**Issue by joris1995** [typeorm/typeorm#5154]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[X] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

First of all, thank you so much for this wonderful library. Local storage plays a key role in my React-Native project and TypeORM has made it really easy to implement.

I am now entering a phase where my project is live, and I want to add new functionalities that require an adjustment to my datamodel. To start, I have used the react-native-example project. I have built my datamodel on this and would now like to implement a migration into it.

There seems to be no definitive manual/guide on how to perform migrations on React-Native. 
Since I don't have access to the databases of my users, I can't run the migrations manually. So far, I found out that there is a 'migrationsRun' option in the connection settings which can be set to true, forcing migrations to be executed at every launch of the app, if needed.

Question then is: How should the actual migrations be created, what should they look like (plain sql queries?), and where should I put them?

Any guidance on migrations in a react-native app would be very helpful.

**Comment by dehy** [comment]
I have the same problem here. Do we need to include the migration files in the app bundle?

**Comment by crutchcorn** [comment]
It seems there's been someone looking into it and answered on StackOverflow:

https://stackoverflow.com/a/59887552

**Comment by imnotjames** [comment]
Looks like it was more or less answered.  Great!

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
