### ISSUE TITLE
@Unique helper generate random names 

### ISSUE THREAD

**Issue by PedramMarandi** [typeorm/typeorm#5155]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Create a unique constraint using the below code 
`@Unique('email_uniq_index', ['email'])`
I expect the resulting constraint name to be `email_uniq_index` but it will create a unique constraint with random values like `UQ_f603fc24759b12726df73c1ad46`.

**Comment by ong-ar** [comment]
mysql 5.7

same..
