### ISSUE TITLE
can i use this qeury using option without createQueryBuilder 

### ISSUE THREAD

**Issue by tjholic** [typeorm/typeorm#5157]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

await connection.getRepository(Review)
.createQueryBuilder('review')
.where({ reviewType: ReviewerType.Client })
.andWhere('review.shop.id IN (:shopIds)', { shopIds })
**.andWhere('childReview.id IS NULL')**
.leftJoinAndSelect('review.shop', 'shop')
.leftJoinAndSelect('review.reviewer', 'reviewer')
**.leftJoinAndMapMany('review.childReviews', ChildReview, 'childReview', 'review.id=childReview.parentReviewId')**
.leftJoinAndSelect('childReview.reviewer', 'childReviewer')
.leftJoinAndSelect('childReview.operator', 'childOperator')
.leftJoinAndSelect('shop.orderApp', 'orderApp')
.orderBy('review.reviewedAt', 'DESC')
.skip(pagination.pageNum * pagination.itemPerPage)
.take(pagination.itemPerPage).getManyAndCount();

Bold means it's important.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by tjholic** [comment]
`const reviewQuery = await connection.getRepository(Review)
    .createQueryBuilder('review')
    .where({ reviewType: ReviewerType.Client })
    .andWhere('review.shop.id IN (:shopIds)', { shopIds })
    .andWhere('childReview.id IS NULL')
    .leftJoinAndSelect('review.shop', 'shop')
    .leftJoinAndSelect('review.reviewer', 'reviewer')
    .leftJoinAndMapMany('review.childReviews', ChildReview, 'childReview', 'review.id=childReview.parentReviewId')
    .leftJoinAndSelect('childReview.reviewer', 'childReviewer')
    .leftJoinAndSelect('childReview.operator', 'childOperator')
    .leftJoinAndSelect('shop.orderApp', 'orderApp')
    .orderBy('review.reviewedAt', 'DESC')
    .skip(pagination.pageNum * pagination.itemPerPage)
    .take(pagination.itemPerPage).getManyAndCount();`

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
