### ISSUE TITLE
Cannot use raw SQL functionality as expected in the insert query builder

### ISSUE THREAD

**Issue by LeoW93** [typeorm/typeorm#5158]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
👋 TypeORM!

Here's some brief setup to describe the problem I'm having:
I have a table which has several columns, including an `id`, which is a `uuid` and the primary key, an `event_type` and a `boolean` `rejected` column, like so: 
```ts
@Entity()
class Event {
 @PrimaryColumn()
 id: string;

@Column()
 event_type: string;

 @Column()
 rejected: boolean;
}
```

Now when I use the `EntityManager` exposed from the `Repository<Event>`, I would like to use some raw SQL in the `values()` method, like so:

```ts
  const transaction: EntityManager = eventRepository.manager; 
  const event: Event = {
     id: uuid(),
     event_type: 'foo',
     rejected: () => "exists (select 1 from "events" where event_type = 'rejected')"
  }
  await transaction
    .createQueryBuilder()
    .insert()
    .into(Event)
    .values(event)
    .execute();
```

In this example, I would like `rejected` to be true if there's another event where the `event_type = 'rejected'`. As explained in the [`InsertQueryBuilder` docs](https://github.com/typeorm/typeorm/blob/fb6068849215e6ea75222f7bb015030314cf67d6/docs/insert-query-builder.md), this should certainly be possible. 
However, the `PostgresDriver` overwrites my functional value for the `rejected` property, since it knows the column is a boolean and so casts it to `1` or `0`.

Clearly this should not be happening and I should be able to still use a function to write my value using SQL.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by lamuertepeluda** [comment]
Damn right, I'm also facing the same kind of issue and I cannot overload it.
Function members in value are ignored/casted to 1 or 0. For sure they do not behave as described in the documentation. Any clues on how to work around this? I was also trying setting native parameters but somehow it is not working 😢

**Comment by lamuertepeluda** [comment]
In my case, I was able to move on on my problem by setting a before insert and update trigger where I modify the field by calling another function and by setting deferrable constraints on the entity. 
Of course this is a workaround, it does solve my specific problem but I would expect the InsertQueryBuilder to work as per documentation

**Comment by LeoW93** [comment]
My workaround was to perform an insert followed by a conditional update. Not ideal, but works for now. Hoping to have a proper look at this soon

**Comment by LeoW93** [comment]
@lamuertepeluda this was closed by https://github.com/typeorm/typeorm/pull/5305 🎉
