### ISSUE TITLE
use alias crashed with relation query

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#5165]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

### this crashed
```ts
    await this.repo.createQueryBuilder('A')
      .relation('A.involvedBAs')
      .of(activityId)
      .add(baList);
```

```
Relation A.involvedBAs was not found in entity A
```

### this is ok
```ts
    await this.repo.createQueryBuilder()
      .relation('involvedBAs')
      .of(activityId)
      .add(baList);
```

**Comment by imnotjames** [comment]
`relation` is always off the main alias.  This is expected.
