### ISSUE TITLE
Typeorm Caching return Async callback not invoked in Jest testing

### ISSUE THREAD

**Issue by dennbagas** [typeorm/typeorm#5167]
**Issue type:**

[ ] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[*] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an API Endpoint written in Express and testing using Jest. I have caching enabled in typeorm configuration. I have to remove a cache when i update a data with this code:
```ts
await getConnection().queryResultCache?.remove([`device:${req.params.device_uuid}`]);
```
It works just fine, but when it comes to testing with Jest it always gets Timeout with error: `Async callback was not invoked within the 5000ms`, and when i commenting out that line, the test is passing.
Is there a wrong part I am missing or this is a bug in typeorm caching?

**Comment by kateile** [comment]
@dennbagas do you have cache enabled in both typeorm config for `testing `and `development`?. May be you forgot adding caching config for tests.

**Comment by imnotjames** [comment]
This isn't really typeorm specific or seemingly an issue with typeorm.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
