### ISSUE TITLE
Spatial DataTypes

### ISSUE THREAD

**Issue by DavidPMacNeil** [typeorm/typeorm#517]
Hello, 

I'm wondering if there is a plan to include Geography or Geometry Data types in the future. Although these data types are used less than others, they are helpful and needed for some projects. I know Postgres uses PostGIS, and that this was already discussed in issue #370. I know that MySQL has Geometry and some other spatial data types, and Sql Server has Geography and Geometry as well. 

Thanks,
David

**Comment by pleerock** [comment]
yes there is a plan to support all database-specific column types in the future.

**Comment by mitchell44** [comment]
@pleerock Is there any idea as to where that is in the road map to include spatial data types?

**Comment by pleerock** [comment]
it will be shipped into `0.1.0` however final release of `0.1.0` I expect in autumn.

**Comment by mitchell44** [comment]
Perfect, thanks!

**Comment by pleerock** [comment]
Custom column data types are landed in `0.1.0-alpha.10`. Now you can use any datatype postgres has. Feel free to test them!

**Comment by DavidPMacNeil** [comment]
@pleerock Does this only apply to Postgres? Can you give an example of defining a custom column?

**Comment by pleerock** [comment]
I didn't checked all column types yet, you can use any of those postgres types:

```
    |"point" // postgres
    |"line" // postgres
    |"lseg" // postgres
    |"box" // postgres
    |"circle" // postgres
    |"path" // postgres
    |"polygon" // postgres
```

for example: `@Column("line")`

**Comment by ghashi** [comment]
What about `mysql`? 
@pleerock, Is there any idea as to where that is in the road map to include spatial data types for `mysql`? 

https://dev.mysql.com/doc/refman/5.7/en/spatial-datatypes.html

**Comment by pleerock** [comment]
I'll reopen this issue to add mysql support as well. This can be implemented once we get free from bunch of other more prioritable tasks. You can implement this feature on your own, its not hard to make it.

**Comment by goulash1971** [comment]
@pleerock - can you give some guidance where the best place to implement spatial type support for MySQL would be in TypeOrm (I can see you have added it into the 0.2.0 roadmap - which is great! - just want to implement a temporary 'patch' until the support becomes offical).

When I implemented similar support on JPA (ages ago) I used a ValueTransfomer to transform to and from WKB/WKT storage in MySql.

Looking at typeOrm it seems that the better way would be to patch the driver - is that what you would advise?

**Comment by pleerock** [comment]
@goulash1971 the best if you create a pull request and we merge this feature into typeorm 😆

**Comment by AlexMesser** [comment]
Spatial types support for MySQL added in `typeorm@0.2.0-alpha.40`. You can try it via `npm i typeorm@next`. Usage: 

```typescript
@Entity()
export class Post {
   @Column("point")
   point: string;
}

post.point = "POINT(1 1)";
```

**Comment by DavidPMacNeil** [comment]
The purpose of this issue wasn't for MySQL Specifically, but to have spatial datatypes for all supported databases. Nice Work on MySQL!

**Comment by kukuandroid** [comment]
@AlexMesser  Hi mate, how do i query the geospatial ?
for this : 
    ```
SELECT * FROM post  WHERE GeometryType(ST_Centroid(location)) = 'POINT' AND 
   ST_Distance_Sphere(location,ST_MakePoint(${long},${lat})) <= ${radius} * 1609.344`);
```

**Comment by HazemHa** [comment]
> @AlexMesser Hi mate, how do i query the geospatial ? for this :
> 
> ```
> SELECT * FROM post  WHERE GeometryType(ST_Centroid(location)) = 'POINT' AND 
>    ST_Distance_Sphere(location,ST_MakePoint(${long},${lat})) <= ${radius} * 1609.344`);
> ```




I think there is no way to write it in TypeORM expect use QueryBuilder because there is many functions not exist between the versions in MYSQL


this example I have use it with MYSQL


```
async findByNearNodes() {
        const data = this.nodesRepository.find({})

        let lang = 25.3542266;
        let lat = 55.3882615

        let currentPoint = `ST_GeomFromText(\"POINT(${lang} ${lat})\",4326)`

        // ST_GeomFromText('POINT(51.513 -0.08)', 4326)
        let locations = await this.nodesRepository
            .createQueryBuilder('node')
            .select(['*', `ST_Distance_Sphere(location,${currentPoint})/ 1000 as km`])
            .where(`ST_Distance_Sphere(location,${currentPoint})/ 1000 <= :range `)
            .setParameters(
                {
                    range: 500
                }
            )
            .getRawMany();
        console.log(locations)


        console.log("this.nodesRepository.locations :", locations)


        return locations;
    }
```
