### ISSUE TITLE
transaction already released, cant not run queries

### ISSUE THREAD

**Issue by hoochycoochie** [typeorm/typeorm#5173]
Mutation: {
    createProduct: companyPermission.createResolver(
      async (_parent, args, { user_id: author_id, url, productRepo }) => {
        const uniqueName = await productRepo.findOne({
          where: { name: args.product.name, company_id: args.company_id },
        });
        if (uniqueName) {
          return {
            ok: false,
            errors: [{ path: 'name', message: 'name_exists_already' }],
          };
        }
        let id_public = null;
        const queryRunner = await getConnection().createQueryRunner();
        await queryRunner.startTransaction();
        try {
          const transactionalEntityManager = queryRunner.manager;
          const product = new Product();

          const {
            file,
            name,
            category_id,
            has_choice_size,
            sizes,
            has_choice,
            choices,
            description,
            price,
          } = args.product;
          if (file) {
            const public_id = await processUpload(file);
            id_public = public_id;
            product.picture_public_id = public_id;
            product.picture = `${url}/images/${public_id}`;
          }
          product.description = description;
          product.company_id = args.company_id;
          product.author_id = author_id;
          product.name = name;
          product.category_id = category_id;
          product.has_choice_size = has_choice_size;
          product.has_choice = has_choice;
          product.price = price;

          await transactionalEntityManager.save(product);
          if (has_choice_size && sizes && sizes.length) {
            sizes.forEach(async siz => {
              const size = new ChoiceSize();
              size.name = siz.name;
              size.author_id = author_id;
              size.price = siz.price;
              size.product_id = product.id;
              await transactionalEntityManager.save(size);
            });
          }
          if (has_choice) {
            choices.forEach(async choose => {
              const choice = new Choice();
              choice.product_id = product.id;
              choice.name = choose.name;
              choice.author_id = author_id;
              choice.choice_mandatory = choose.choice_mandatory;
              choice.choice_multiple = choose.choice_multiple;
              choice.choice_number = choose.choice_number;
              choice.subcat_id = choose.subcat_id;

              await transactionalEntityManager.save(choice);

              if (choose.subprods && choose.subprods.length) {
                choose.subprods.forEach(async subprod => {
                  const choice_subprod = new ChoiceSubProd();
                  choice_subprod.subprod_id = subprod.subprod_id;
                  choice_subprod.name = subprod.name;
                  choice_subprod.choice_id = choice.id;

                  choice_subprod.free_choice = subprod.free_choice;
                  choice_subprod.price = subprod.price;
                  choice_subprod.product_id = product.id;
                  choice_subprod.company_id = args.company_id;
                  await transactionalEntityManager.save(choice_subprod);
                });
              }
            });
          }
          await queryRunner.commitTransaction();
          return {
            ok: true,
            product,
          };
        } catch (error) {
          await queryRunner.rollbackTransaction();
          if (id_public) {
            await deleteFile(id_public);
          }
          return {
            ok: false,
            errors: [{ path: 'global', message: error.message }],
          };
        }
        finally {
          // you need to release query runner which is manually created:
          if (!queryRunner.isReleased) {
            await queryRunner.release();
          }
        }
      }

I have problem with transaction in typeorm. When i do as documention said, i have have issue like cant run queries transaction already release, and when i comment finnaly block, when i run 2 times the same function i'm in an infinite loop. i dont understand. I precise i'm working on a grapqh nodejs stack. Thank you

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
