### ISSUE TITLE
Typeorm generates DROP VIEW instead of DROP MATERIALIZED VIEW

### ISSUE THREAD

**Issue by GSKryachko** [typeorm/typeorm#5175]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.20` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello! I've created a materialized view using `@ViewEntity` option `materialized: true` and typeorm generated a migration. In it's up method it uses
    `CREATE MATERIALIZED VIEW`,
but in it's down method it has
    `DROP VIEW` 
instead of 
   `DROP MATERIALIZED VIEW`

**Comment by Ginden** [comment]
I wrote code for materialized views, so I will try to fix it today.

**Comment by minism** [comment]
Any progress here?  Still seems to be a bug.

**Comment by ekzyis** [comment]
Just encountered this. Checked if there is already an issue for this. There is :+1:

**Comment by mmarifat** [comment]
still facing this issue with typeorm: 0.3.20 and nestjs 10.3.3

**Comment by mmarifat** [comment]
> still facing this issue with typeorm: 0.3.20 and nestjs 10.3.3

Okay. found the issue.
If you have already declared the view as VIEW and then enabled materialised: true, then it creates one more entry in public.typeormmetadata table.
You need to give a new name to the ViewEntity or remove the entry from typeormmetada table
