### ISSUE TITLE
Can't create SQLite migrations (DriverPackageNotInstalledError)

### ISSUE THREAD

**Issue by philonor** [typeorm/typeorm#5176]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.20` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Repo: https://github.com/philonor/electron-typescript-example
Steps:
1. Clone
1. Run `npm i`
1. Run `npm run db:migrate`

**Description**
Hi there,

I'm trying to generate database migrations for SQLite.
My ormconfig.json looks like this:
```
{
  "type": "cordova",
  "database": "test",
  "location": "default",
  "synchronize": false,
  "logging": ["error", "schema"],
  "logger": "simple-console",
  "entities": [
    "src/entity/*.js"
  ]
}
```
I followed the guide https://typeorm.io/#/migrations and used `./node_modules/typeorm/cli.js migration:generate -n SomeMigration` to create a entity migration script.
The following error pops up: `Cordova-SQLite package has not been found installed. Try to install it: npm install cordova-sqlite-storage --save`.
My package.json contains the cordova plugin, I did a fresh `npm i` to ensure everything is present.

[You state here](https://github.com/typeorm/typeorm/issues/1380#issuecomment-354750865) that we should use `synchronize:true` although the guide is advising against using it in production.
Does TypeORM support sqlite migrations? If not, what would be best practice to write manual migration scripts and use database versioning?

Thanks

**Related**
- https://github.com/typeorm/typeorm/issues/1380
- https://github.com/typeorm/typeorm/issues/2393
- https://github.com/typeorm/typeorm/issues/3441

**Comment by philonor** [comment]
Alternative approach, as far as I understand it correctly, would be to use the [migration API](https://typeorm.io/#/migrations/using-migration-api-to-write-migrations).
This [guide](https://wanago.io/2019/01/28/typeorm-migrations-postgres/) points out how to run them from code:
```
  try {
    const connection = await createConnection(config);
    await connection.runMigrations();
  } catch (error) {
    console.log('Error while connecting to the database', error);
    return error;
}
```
It states that `TypeORM always checks if there are any migrations that it needs to run at the start.`. 
If this is true, it would be nice to document how it determines in which order to run migrations.
In production, there will be different database schema version and migrations to update between the versions.
Does TypeORM use an internal database versioning? Can we define our own schema versions and specify the migrations to run for updating between them?

**Comment by git-karthik** [comment]
> **Issue type:**
> 
> [ ] question
> [x] bug report
> [ ] feature request
> [x] documentation issue
> 
> **Database system/driver:**
> 
> [x] `cordova`
> [ ] `mongodb`
> [ ] `mssql`
> [ ] `mysql` / `mariadb`
> [ ] `oracle`
> [ ] `postgres`
> [ ] `cockroachdb`
> [ ] `sqlite`
> [ ] `sqljs`
> [ ] `react-native`
> [ ] `expo`
> 
> **TypeORM version:**
> 
> [ ] `latest`
> [ ] `@next`
> [x] `0.2.20` (or put your version here)
> 
> **Steps to reproduce or a small repository showing the problem:**
> Repo: https://github.com/philonor/electron-typescript-example
> Steps:
> 
> 1. Clone
> 2. Run `npm i`
> 3. Run `npm run db:migrate`
> 
> **Description**
> Hi there,
> 
> I'm trying to generate database migrations for SQLite.
> My ormconfig.json looks like this:
> 
> ```
> {
>   "type": "cordova",
>   "database": "test",
>   "location": "default",
>   "synchronize": false,
>   "logging": ["error", "schema"],
>   "logger": "simple-console",
>   "entities": [
>     "src/entity/*.js"
>   ]
> }
> ```
> 
> I followed the guide https://typeorm.io/#/migrations and used `./node_modules/typeorm/cli.js migration:generate -n SomeMigration` to create a entity migration script.
> The following error pops up: `Cordova-SQLite package has not been found installed. Try to install it: npm install cordova-sqlite-storage --save`.
> My package.json contains the cordova plugin, I did a fresh `npm i` to ensure everything is present.
> 
> [You state here](https://github.com/typeorm/typeorm/issues/1380#issuecomment-354750865) that we should use `synchronize:true` although the guide is advising against using it in production.
> Does TypeORM support sqlite migrations? If not, what would be best practice to write manual migration scripts and use database versioning?
> 
> Thanks
> 
> **Related**
> 
> * #1380
> * #2393
> * #3441

Hi Philonor,
Did you check if the sqlite3 module is installed to your 'node_modules' directory? I believe it does not exist. Try delete the sqlite3 dependency from your package.json and run 'npm i sqlite3 --save' again.
Hopefully, this issue would be resolved.

Regards,
Karthikeyan R

**Comment by eightfivelabs** [comment]
@philonor did you get this working? Having a similar issue

**Comment by m-nikhil** [comment]
I am facing similar issues '(DriverPackageNotInstalledError)'.

I do have it installed and it exists within node_modules.
Typeorm couldn't find it.

**Comment by imnotjames** [comment]
Is this still an issue with TypeORM 0.2.27?

**Comment by imnotjames** [comment]
The cordova sqlite plugin is expected to be exposed in the global `window` scope.

If you haven't exposed it via a `ProvidePlugin` in your webpack config it won't be able to do much with it.

```
    protected loadDependencies(): void {
        try {
            this.sqlite = window.sqlitePlugin;

        } catch (e) {
            throw new DriverPackageNotInstalledError("Cordova-SQLite", "cordova-sqlite-storage");
        }
    }
```

This is a configuration issue with your cordova app.
