### ISSUE TITLE
QueryBuilder leaving nullable fields as undefined

### ISSUE THREAD

**Issue by bartlomiej-korpus** [typeorm/typeorm#518]
This issue is about 0.0.11, I don't know if its the same on 0.1.0-alpha3.
When using QueryBuilder or Repository's .find* to query for entities with fields marked as nullable and of type  "something | null", fields which are null in database become undefined in fetched entity. 
Quick hack is to define their default value to null, but it doesn't work for relations.

Unfortunately, I am unable to contribute in this issue yet, I don't know codebase enough.

**Comment by DavidPMacNeil** [comment]
I am getting this as well with 0.1.0-alpha3 for all fields, unless I explicitly define the datatype in the column decorator:
`@Column('int')`
Try that and see if you still get undefined.

**Comment by bartlomiej-korpus** [comment]
@DavidPMacNeil 
Still the same, actually I have defined explicit types for almost all my fields.

**Comment by bartlomiej-korpus** [comment]
@DavidPMacNeil Yeah i PR'd fix for this issue and am waiting for an update on NPM.
Let's wait for feedback on this from @pleerock 
If someone was able to point me in right direction in the codebase, I probably would be able to work on it.

**Comment by pleerock** [comment]
is it same as #408 ? If yes, then its by design, at least at the moment.

**Comment by bartlomiej-korpus** [comment]
@pleerock Yes it is the same, I am sorry for not searching first.

**Comment by bartlomiej-korpus** [comment]
@pleerock 
Is it possible it is being changed in the future? 0.1.0 maybe? 
I can help implementing it if it was anticipated.

**Comment by pleerock** [comment]
this is easy to implement, however Im not sure if this is right feature to have, shall it work this way by design or not. Didn't decided yet.

**Comment by bartlomiej-korpus** [comment]
@pleerock An argument for this to work this way, may be that for now, you cannot tell whether the nullable relation wasn't loaded (undefined) or is actually null (null), you have to remember if you did load it or not for every place in code.

**Comment by messerbill** [comment]
hi i think i have a similar issue here:
`let matchRepository = DatabaseConnection.connection.getRepository(Match)
            let match = matchRepository.createQueryBuilder("match")
                .innerJoinAndSelect("match.players", "players")
                .getMany().then(res => {
                    console.log('====')
                    console.log(res)
                    console.log('====')
                }).catch(res => {
                    console.log(res)
                })`

this always returns undefined while no player is saved in the database. After adding a player in the player table, the query works as expected. How can i achive that he won't return "undefined" but something like "Match { bla: bla, foo: foo, bar: bar, players: []}" ? Trying to achieve this for 2 Days now...

greetings

**Comment by messerbill** [comment]
i really need to achieve this, if necessary i can implement it and create a PR (so far this is really a bug and i am not just doing something wrong)

**Comment by messerbill** [comment]
The problem still exists - but i'd really like to use typeorm - please fix that bug...

**Comment by pleerock** [comment]
Okay now when you fetch columns with nulls they are returned to you. Available from `0.1.0-alpha.21`

**Comment by bartlomiej-korpus** [comment]
@pleerock how do new changes apply to relations? left join where right value isn't found, will result in null or undefined?

**Comment by pleerock** [comment]
it applies only on colums and embeds with columns. Relations will be undefined as before.

**Comment by messerbill** [comment]
hey @pleerock thank you for the update - i was using 0.0.11 before (like recommended in readme) and now updated to `0.1.0-alpha.21`. But now i cannot get `tsc` working due to:
`node_modules/typeorm/repository/MongoRepository.d.ts(12,22): error TS2415: Class 'MongoRepository<Entity>' incorrectly extends base class 'Repository<Entity>'.
  Types of property 'count' are incompatible.
    Type '(query?: ObjectLiteral, options?: MongoCountPreferences) => Promise<any>' is not assignable to type '{ (options?: FindManyOptions<Entity>): Promise<number>; (conditions?: DeepPartial<Entity>): Promi...'.
      Types of parameters 'query' and 'conditions' are incompatible.
        Type 'DeepPartial<Entity>' is not assignable to type 'ObjectLiteral'.
`
greetings,
Messerbill

**Comment by pleerock** [comment]
What is your typescript compiler version?

**Comment by messerbill** [comment]
my tsconfig:

`{ \n
  "compilerOptions": {\n
    "target": "es6",\n
    "module": "commonjs",\n
    "moduleResolution": "node",\n
    "sourceMap": true,\n
    "emitDecoratorMetadata": true,\n
    "experimentalDecorators": true,\n
    "lib": [ "es2015", "dom" ],\n
    "noImplicitAny": false,\n
    "suppressImplicitAnyIndexErrors": true\n
  },\n
  "compileOnSave": true,\n
  "exclude": [\n
    "node_modules/*",\n
    "**/*-aot.ts"\n
  ]\n
}`

**Comment by pleerock** [comment]
I didnt asked about tsconfig I asked typescript version you are using to compile the project

**Comment by messerbill** [comment]
sorry, my brain lagged....
 `tsc -v` prints `Version 2.1.4`

**Comment by pleerock** [comment]
Probably its because you are using too old typescrip version. Try to upgrade to `2.3.4`

**Comment by messerbill** [comment]
thanks for your help, now the error is dissappeard, followed by another one :D but this looks resolvable. I need to leave for several hours now, gonna try it tonight. But this looks good -thank you so far! You are doing a great job with typeorm! I will update this post with my results!

best regards,
Messerbill

**Comment by messerbill** [comment]
hi mate, for now this is the situation:

```
let res = await DatabaseConnection.connection.getRepository(Match).createQueryBuilder("match")
                .innerJoinAndSelect("match.users", "users").where("match.id="+matchId)
                .getOne()
console.log(res)
```
res is now undefined.

These are the Entities:

```
@Entity()
export class User {

    @PrimaryColumn("int", { generated: true })
    id: number

    @Column("text")
    name: string

    @Column("text")
    email: string

    @Column("text")
    password: string

    @OneToMany(type => Move, move => move.user, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    moves: Move[]

    @ManyToMany(type => Round, round => round.users, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    rounds: Round[]

    @ManyToMany(type => Match, match => match.users)
    matches: Match[]
}
```
And Match:
```
@Entity()
export class Match {

    @PrimaryColumn("int", { generated: true })
    id: number

    @Column("text")
    name: string

    @Column("text")
    description: string

    @Column("text")
    type: string

    @Column("datetime")
    date: number

    @Column("text")
    status: string

    @OneToMany(type => Round, round => round.match, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    rounds: Round[];

    @ManyToMany(type => User, user => user.matches,  {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    @JoinTable()
    users: User[];
}
```

**Comment by pleerock** [comment]
its expected behaviour. Try to use `leftJoinAndSelect` instead of `innerJoinAndSelect` it should resolve your issue.

**Comment by messerbill** [comment]
sorry, i was too foolish to notice this......thanks a lot! great job!
