### ISSUE TITLE
Limitations on executing and reversing migrations in multi-system environments

### ISSUE THREAD

**Issue by jefmenegazzo** [typeorm/typeorm#5184]
**Issue type:**

[ ] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The way migrations are executed and reversed today is quite limited. Some interesting features that could be added:

- Execute (up) a particular migration (instead of executing all pending at one time).

- Reverse (down) a particular migration (not just the last one). In some cases, the migration that is causing problems is not the last.

Still regarding the migration reversal, the current programmed form does not take into account that sometimes the same database is used for more than one application. Thus, in an environment with system A and system B, connecting to the same database, since there is a limitation that only the last migration can be reversed, we have to:

- How to revert only the last migration from system A, when in the database the last migration performed is from system B?

- If an attempt is made to reverse the last migration by the connection on system A and the last one performed by system B, the source code to revert will not be found.

**Comment by imnotjames** [comment]
Up and down specific migrations https://github.com/typeorm/typeorm/issues/3591

>  Still regarding the migration reversal, the current programmed form does not take into account that sometimes the same database is used for more than one application. Thus, in an environment with system A and system B, connecting to the same database, since there is a limitation that only the last migration can be reversed, we have to:

Connection Options has `migrationsTableName` - set that per app
