### ISSUE TITLE
Recommended way of executing MongoDB migrations

### ISSUE THREAD

**Issue by phil294** [typeorm/typeorm#5187]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Since we cannot use `queryRunner.query()` with the mongodb driver, how would you write migrations? Basic example, insert data into a collection. Digging through [older pull requests](https://github.com/typeorm/typeorm/pull/3304/files#diff-7e61158ea652e5bde170b1fd6287f82bR324), I found the following solution works just fine:

```ts
public async up(queryRunner: QueryRunner): Promise<any> {
        const mongoRunner = queryRunner as MongoQueryRunner;
        const database = (await getConnectionOptions()).database as string;
        await mongoRunner
            .databaseConnection
            .db(database)
            .collection('my-collection').insert({ some: 'data' });
    }
```
Is this the way to go?

If yes, should we add a sentence about it to [migrations.md](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md)? Recommending to do the type cast and use the underlying mongo driver. I can submit a pull request for it

**Comment by ian-r-johnson** [comment]
You can also use the MongoQueryRunner methods

```
public async up(queryRunner: MongoQueryRunner): Promise<any> {
  const count = await queryRunner.cursor('my-collection', {}).count(false);
}
```

```
public async up(queryRunner: MongoQueryRunner): Promise<any> {
  await queryRunner.insertOne('my-collection', doc);
}
```

**Comment by av1m** [comment]
I think we need to add a section in [migrations.md](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md).
Such PR will be accepted?

**Comment by fabiohbarbosa** [comment]
I do not understand why this ticket has been closed without a solution for the request (update the migration guide)

**Comment by chioarub** [comment]
import { MongoQueryRunner } from 'typeorm/driver/mongodb/MongoQueryRunner';
