### ISSUE TITLE
does not throw an error when a column is set to unique constraint when running on test env

### ISSUE THREAD

**Issue by artoodeeto** [typeorm/typeorm#5188]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x` (0.2.20)

**Steps to reproduce or a small repository showing the problem:**

hello typeorm team awesome work here. Love what youve done. this helps me a lot.

may I ask if this is a bug? so ...

I have a migration that looks like this.
```
import { MigrationInterface, QueryRunner } from 'typeorm';

export class UsersTable1575433829516 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(`
            CREATE TABLE users (
                id INT AUTO_INCREMENT,
                username VARCHAR(100) NOT NULL,
                email VARCHAR(100) NOT NULL UNIQUE,
                password VARCHAR(255) NOT NULL,
                PRIMARY KEY(id)
            );
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.dropTable('users', true);
  }
}
```
the email is unique.

this is the model
```
@Entity('users')
export class User extends BaseModel {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  username!: string;

  @Column()
  @IsEmail()
  email!: string;

  @Column()
  password!: string;
}
```
when I run local dev and make a post request on with the same email it throws an error which is expected.

but when I do the same thing on a test. it doesnt throw an error.
heres the test.

```
import { Connection, createConnection } from 'typeorm';
import { User } from '../../src/models/user_model';

describe('User model test', () => {
  let connection: Connection;

  beforeEach(async () => {
    connection = await createConnection({
      type: 'mysql',
      host: 'localhost',
      username: 'root',
      password: 'password',
      database: 'test_db',
      synchronize: true,
      dropSchema: true,
      entities: [User]
    });
  });

  afterEach(async () => {
    connection.close();
  })

  it('should create a user', async (done) => {
    const user = await User.create({
      username: 'foo',
      email: 'foo@gmail.com',
      password: 'password'
    }).save();

    expect(user.id).toEqual(1);
    done();
  });


  it('should not create a user with the same email', async (done) => {
    try {
      await User.create({
        username: 'foo',
        email: 'foo@gmail.com',
        password: 'password'
      }).save();

      await User.create({
        username: 'foo',
        email: 'foo@gmail.com',
        password: 'password'
      }).save();

      // expect(user.id).toEqual(1);
    } catch (error) {
      expect(error).toHaveProperty('ss')
    }
    done();
  });

});
```

I can confirm this when I check the actual database, the records are their. I dont know if this is from you or from mysql2

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by artoodeeto** [comment]
@pleerock hello there sir. I think this is really a bug. So I added a column constraint of unique right and on testing it didnt fail. but I added the property `unique: true` on the @column decorator and its working now. shouldn't be both are checked? from the database and model level? anyway, dont listen to the naysayers I love your orm feels like i didn't leave ruby on rails functionality. :)  blessyou sir

**Comment by iWinston** [comment]
Hi, I think it may not be a bug.
This is your [ormconfig.ts](https://github.com/artoodeeto/ggpo-server/blob/master/ormconfig.ts):

```
let ormConfig: any;

if (process.env.NODE_ENV === 'test') {
  // test environment database should be drop every time. so synchronize should be true for this config
  ormConfig = {
    type: 'mysql',
    host: 'localhost',
    username: 'root',
    password: 'password',
    database: 'test_db',
    synchronize: true,
    dropSchema: true,
    entities: ['src/models/**/*.ts']
  };
} else {
  ormConfig = {
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'root',
    password: 'password',
    database: 'development_db',
    synchronize: false,
    logging: true,
    entities: ['src/models/**/*.ts'],
    migrations: ['db/migrations/**/*.ts'],
    subscribers: ['src/subscribers/**/*.ts'],
    cli: {
      entitiesDir: 'src/models',
      migrationsDir: 'db/migrations',
      subscribersDir: 'src/subscribers'
    }
  };
}

export default ormConfig;
```
When you run the test, you set the `synchronize` to true, so the unique doesn't work.
Adding the property unique: true on the @column decorator is the best way for you to solve the problem.

**Comment by artoodeeto** [comment]
@iWinston ahhh. shit!! thank you again! appreciate the help dude. thank you thank you! ill close this now. thank you!
