### ISSUE TITLE
Why typerom create unique constraint on foreign keys?

### ISSUE THREAD

**Issue by vikei** [typeorm/typeorm#5194]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have entity with foreign keys, and typeorm when create table make them unique constraint, why it happens?

```
@Entity()
export class Cv {
  @AfterLoad()
  parseSalary() {
    this.salary = parseFloat(<string>(<unknown>this.salary));
  }

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column({ type: 'decimal', scale: 2 })
  salary: number;

  @Column({ default: false })
  relocate: boolean;

  @Column({ default: false })
  remote: boolean;

  @Column()
  description: string;

  @Column({ nullable: true })
  countryId?: number;

  @OneToOne(() => Country)
  @JoinColumn()
  country?: Country;

  @Column({ nullable: true })
  cityId?: number;

  @OneToOne(() => City)
  @JoinColumn()
  city?: City;

  @Column()
  currencyId: number;

  @OneToOne(() => Currency)
  @JoinColumn()
  currency: Currency;

  @ManyToMany(() => Category, { cascade: true })
  @JoinTable()
  categories: Category[];

  @Column()
  userId: number;

  @ManyToOne(() => User)
  user: User;
}
```
<img width="1106" alt="Screen Shot 2019-12-06 at 5 31 34 PM" src="https://user-images.githubusercontent.com/55663427/70334668-879dc180-184e-11ea-862a-77ea4afcbe92.png">

**Comment by vikei** [comment]
Need to use ManyToOne instead OneToOne

**Comment by mernen** [comment]
That's because you're using `@OneToOne`, which implies a unique value for this column. Replace it with `@ManyToOne` (and drop the `@JoinTable()` annotation), and the constraint should disappear.
