### ISSUE TITLE
excess apostrophe in an example of documentation(PART:update using queryBuilder)

### ISSUE THREAD

**Issue by greatofdream** [typeorm/typeorm#5199]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
In the part [**update using queryBuilder.Raw sql support**](https://typeorm.io/#update-query-builder/raw-sql-support),  sql in `set` function shouldn't contain apostrophe around `age` in the example.

```
age: () => "'age' + 1"
```
should be modified to
```
age: () => "age + 1"
```
otherwise, the ts engine will throw error ` invalid input syntax for integer:`
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
This is dependent on the SQL dialect.  In some SQL dialects this is correct.
