### ISSUE TITLE
Foreign Keys must be ints

### ISSUE THREAD

**Issue by DavidPMacNeil** [typeorm/typeorm#520]
Foreign Keys must ints in order to function, currently. Primary Keys may be nvarchar as well for various reasons.

**Comment by pleerock** [comment]
both foreign keys and primary keys can be different types depend on what columns they are serving. If your `id` is string then primary key should be nvarchar/varchar, if its a number then it should be int/other numeric types. Foreign keys takes type of referenced columns. If referenced column is a string id then foreign key column type cannot be integer.

**Comment by DavidPMacNeil** [comment]
[Here](https://gist.github.com/DavidPMacNeil/85dc23b7d9c9a3a97806c1f772152d1e) is a gist of the issue I am having, as we discussed on gitter.

**Comment by DavidPMacNeil** [comment]
So I've tried again after the fixes, but I'm getting the same error. Tried with a Primary Key of Int and it works for that but still is not for nvarchar.

```
query failed: ALTER TABLE "WO_Location" ADD CONSTRAINT "fk_e286f587045b523da57d0b40829" FOREIGN KEY ("customerCustomerID") REFERENCES "WO_Customer"("CustomerID")
(node:6772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Could not create constraint or index. See previous errors.
```

**Comment by DavidPMacNeil** [comment]
So I've looked into it more, and found that when using strings the foreign key in Location.ts is being built as ```customerCustomerID```, since the reference between the two is customer, and locations[]. Therefore, the already defined field of ```CustomerID``` does not match.

**Comment by pleerock** [comment]
What is conclusion?

**Comment by DavidPMacNeil** [comment]
@pleerock I've submitted a new issue. For string type PK in mssql typeorm is requiring a strange foreign key name. More info in #620
