### ISSUE TITLE
ViewEntity expression doesn't work on mssql

### ISSUE THREAD

**Issue by focux** [typeorm/typeorm#5200]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When I noticed that the view entity wasn't taking into account the expression, I did a test changing the expression to `lol`, just to confirm it wasn't working:
e.g .
```typescript
import { ViewEntity, ViewColumn } from 'typeorm';

@ViewEntity({
  expression: `
  lol
`,
})
export class Stats {
  @ViewColumn()
  name: string;
}
```

This is the error I'm getting:
`Error: Invalid object name 'stats`

And I got no idea where he is getting this query that he's executing:
```
SELECT \"Stats\".\"name\" AS \"Stats_name\" FROM \"stats\" \"Stats\" ORDER BY (SELECT NULL) OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
```

I was using a valid expression before testing with `lol`, so it's not because the expression is invalid.

What I want to do is to map values to view column like this e.g.
```typescript
import { ViewEntity, ViewColumn } from 'typeorm';

@ViewEntity({
  expression: `
  SELECT stats.id as id FROM stats
`,
})
export class Stats {
  @ViewColumn()
  name: string;
}
```
But that doesn't work either.

**Comment by bilal-wiztech** [comment]
getting same issue

**Comment by anteriovieira** [comment]
the same here, any progress?

**Comment by anteriovieira** [comment]
Hi @focux , the problem is because you don't have the view in the database. You need to create and run the migration before queries the data.

https://github.com/typeorm/typeorm/blob/beea2e1e4429d13d7864ebc23aa6e58fa01647ea/test/functional/view-entity/mssql/view-entity-mssql.ts#L21-L24

**Comment by imnotjames** [comment]
Yup, looks like your view hasn't been created yet - not that the expression isn't being used.
