### ISSUE TITLE
Array as variable in SELECT WHERE IN - Postgresql

### ISSUE THREAD

**Issue by jmpreston** [typeorm/typeorm#5201]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[X] `postgres`

**TypeORM version:**

[X ] `0.2.20`

**Steps to reproduce or a small repository showing the problem:**

Pitch to those visiting this issue:  Please donate to TypeORM.  I have and intend to donate more when I can.  Help the devs who are helping you.

This issue is an extension of this [issue from 2018](https://github.com/typeorm/typeorm/issues/1239)

1.  Could you please use real world coding in the docs?  There are examples all over the Web that use array literals but never variables.  I assume that all coders but me are hard coding the data into their work :-). It sure is difficult as a noob to learn the right way to code when almost every tutorial and software documentation uses hard coding!

2.  I need to understand how to use a var in TypeORM QueryBuilder arrays.  I've spent days on this issue with many different search terms and no answer.

One issue is that Postgres wants '{ }' for arrays, but I have only errors if I use them.

**What is going on here?  What are we supposed to do in the real world?**

This works with {ids: [1]} but it chokes with [1,6]:
    `syntax error at or near ","`

```
const techArray = [1];

return this.entityManager
  .createQueryBuilder(Projects, "projects")
  .where(":...ids = ANY (projects.technologies)", { ids: techArray })
  .getMany();
```

And this works:

```
 public async findByTechId(techArray) { 
  return this.entityManager
      .createQueryBuilder(Projects,"projects")
      .where("projects.technologies && ARRAY [1,6]")
      .getMany();
  }
```
This fails, it doesn't like the var:

The rest has techArray = [1,6].

```
public async findByTechId(techArray) {
  return this.entityManager
    .createQueryBuilder(Projects,"projects")
    .where("projects.technologies && ARRAY (:...ids))",  {ids: techArray}). <-----
    .getMany();
  }
```

And not with this setup and many others I've tried:

```
const techArray = [1,6];

return this.entityManager
      .createQueryBuilder(Projects, "projects")
      .where("projects.technologies = ANY (:...ids)", {ids: techArray})  // Also tried IN (no '=').
      .getMany();
```

This works but not with a var:
```
const sql = "SELECT * FROM projects WHERE technologies && ARRAY[1,6]";
return await this.entityManager.query(sql);
```
But with an array:

```
FROM "projects" "projects" WHERE $1, $2 = ANY ("projects"."technologies") -- PARAMETERS: [1,6]
 error: syntax error at or near ","
```

**Comment by DMeechan** [comment]
This syntax for a `WHERE IN` works for me with TypeORM:

```javascript
const projectIds = [1, 2, 3];

const projects = await this.entityManager
  .createQueryBuilder(Projects, "projects")
  .where("projects.id IN (:...ids)", {
    ids: projectIds,
  })
  .getMany();
```


I hope this helps!

**Comment by jmpreston** [comment]
@DMeechan  That did it!  Thanks!  I had this hacky for loop mess but this is more clean.  I'm sure it will help others.

**Comment by jmpreston** [comment]
Unfortunately this will not work with GraphQL, which returns the error syntax error at or near ",".

**Comment by kitsoRik** [comment]
> Unfortunately this will not work with GraphQL, which returns the error syntax error at or near ",".

I had the same problem with GraphQL, I was changing my code many times, but still got the same error, after removed unworked code, I got the same error (but code block was deleted), after many actions I explained, it was problem with Google Chrome (it was just returning the same (caching) answer on all my requests, also refresh page not helper).
To fix it: I just closed this tab and reopen site in the new tab, it was work.

About code above, it work fine with typeorm, and it has nothing to GraphQL, check your resolver returning value (if it correctly, typeorm there is nothing)
