### ISSUE TITLE
Run migration:generate twice will generate two same migration file

### ISSUE THREAD

**Issue by zerox12311** [typeorm/typeorm#5203]
**Issue type:**

[X] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.20` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I follow this repo step to create my ormconfig.ts 
[Here](https://github.com/ambroiseRabier/typeorm-nestjs-migration-example)

And I create my entity , then run **migration:generate** will generate migration file.
It is good! but I run **migration:generate** second time immediately without migration:run
It will generate second migration file, but content is same as first one. (It's wrong!!!)

In python django framework, I do this action, It will show **No changes detected** in second time
But in typeorm it will generate second file.
How can I fix it?

**Comment by gaspard** [comment]
Why would you use `migration:generate` a second time without running the migrations before hand ?

What you are asking is to simulate the existing migrations that have not been run before comparing database with entities. This is error prone and requires lots of work for an unclear added value I think.

**Comment by imnotjames** [comment]
This is just how the generator works.

Per #5260 there's an idea proposed of changing it.  If you think this should change please chat there.
