### ISSUE TITLE
Use an existing pg.Client connection

### ISSUE THREAD

**Issue by dncrews** [typeorm/typeorm#5211]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Request:**

The [previous request is closed](https://github.com/typeorm/typeorm/issues/210) and the workaround there doesn't seem to work anymore. I'm trying to implement [AWS request tracing for Postgres](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-sqlclients.html). I can't seem to find a non-hacky way to override this require, but I'd really like to do that somehow.

Help/Thoughts?

**Comment by avin-kavish** [comment]
Yeah, I have the same use case. This public api shouldn't be much of a challenge. Something like this could work,

```ts
const conn = await createConnection({
 type: 'postgres'
 pg: AWSXRay.capturePostgres(require('pg'))
})

// or a common driver property
const conn = await createConnection({
 type: 'mysql'
 driver: AWSXRay.captureMySQL(require('mysql'))
})
```

**Comment by agustinhaller** [comment]
@dncrews @avin-kavish Did you manage to solve this issue?
If so, can you share what worked for you?

**Comment by seriousManual** [comment]
Hi, would also be interested in a solution for this

**Comment by dncrews** [comment]
@agustinhaller nope. I never did.

**Comment by avin-kavish** [comment]
@agustinhaller Haven't done it myself because I've moved away to Now. But one way I can think of is to have a local patch for typeorm which does just the above and have it committed to version control using [patch-package](https://www.npmjs.com/package/patch-package). The file you would want to patch is `typeorm/platform/PlatformTools.js` in node_modules. I.e the compiled version of this [file](https://github.com/typeorm/typeorm/blob/master/src/platform/PlatformTools.ts).

**Comment by MIrinkov** [comment]
From what I see [in source](https://github.com/typeorm/typeorm/blob/e92c743fb54fc404658fcaf2254861b6aa63bd98/src/driver/postgres/PostgresDriver.ts#L279-L292), if you need a `Pool` instance, you can find it in `(connection.driver as PostgresDriver).master as pg.Pool`.
If you need the `pg` instance, `(connection.driver as PostgresDriver).postgres as pg` is what you need ([source](https://github.com/typeorm/typeorm/blob/e92c743fb54fc404658fcaf2254861b6aa63bd98/src/driver/postgres/PostgresDriver.ts#L900-L912)).

**Comment by imnotjames** [comment]
This is not currently supported.  There might be ways to make it happen, but we probably aren't gonna support this in the near term.

---

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by lenis0012** [comment]
That's a shame. I am using a wrapper around the postgres client as well to kill ghost connections for use in serverless functions.

**Comment by calvin-summer** [comment]
> That's a shame. I am using a wrapper around the postgres client as well to kill ghost connections for use in serverless functions.
@lenis0012 hey! totally off topic for tor the thread but i'm wondering how you handled killing the ghost connections? i'm working on the same issue right now. planning on trying to execute a `select 1` with the driver to determine if a connection actually exists.
