### ISSUE TITLE
how can i filter in relation

### ISSUE THREAD

**Issue by windreamlion** [typeorm/typeorm#5215]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

i have two entity

## User Entity
```
@Entity()
export class User {
    @ManyToMany(() => Role, role => role.users)
    @JoinTable()
    roles: Promise<Role[]>
}
```

## Role Entity
```
@Entity()
export class Role {
    @ManyToMany(() => User, user => user.roles)
    users: User[]
}
```

i create two role, Admin (id=1) and Guest (id=2) , i assigned role to some user.

### my question:
when i find users, how filter user with role value

i try this, but it doesn't work
```
this.userRepository.find({
      where: { roles: { id: 1 } },
    })
```

please give some help, thanks

**Comment by oscar-corredor** [comment]
Have you checked the SQL query generated by TypeORM?

**Comment by alpharder** [comment]
Unfortunately you cannot. There are dozens of similar issues here ignored by developers. All you can do right now is either use Query Builder or switch to Sequelize

**Comment by alpharder** [comment]
There's a workaround for filtering based on relation fields for `findOne()`/`find()` methods that I've discovered recently. The problem with filtering related table fields only exists for `ObjectLiteral`-style `where`, while string conditions work perfectly. 

Assume that we have two entities – `User` and `Role`, user belongs to one role, role has many users:

```typescript
@Entity()
export class User {
  name: string;

  @ManyToOne(() => Role, role => role.users)
  role: Role;
}

@Entity()
export class Role {
  @OneToMany(() => User, user => user.role)
  users: User[];
}
```

Now we can call `findOne()`/`find()` methods of `EntityManager` or repository:

```typescript
roleRepository.find({
  join: { alias: 'roles', innerJoin: { users: 'roles.users' } },
  where: qb => {
    qb.where({ // Filter Role fields
      a: 1,
      b: 2
    }).andWhere('users.name = :userName', { userName: 'John Doe' }); // Filter related field
  }
});
```

You can omit the `join` part if you've marked your relation as an eager one.

**Comment by imnotjames** [comment]
Looks like this was answered.  I'll be closing it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by alpharder** [comment]
@imnotjames Well, the answer was basically a workaround because the root issue is that filtering by relations doesn't work for plain object where.
