### ISSUE TITLE
Tables created in custom migrations are not created in the schema defined in the connection

### ISSUE THREAD

**Issue by paweloque** [typeorm/typeorm#5216]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I create a typeorm migration which creates a new table exampletbl: 
```
await queryRunner.query(`CREATE TABLE "exampletb" ()`);
```

My connection is defined to connect to the `core` schema, which is not the `public` schema: 
```
connectionOptions = {
    ..await getConnectionOptions(),
    name: 'local',
    schema: 'core'
};
await createConnections([connectionOptions]);
connection = await getConnection('local');
await connection.runMigrations();
```

When I execute the migration, the table is created in the `public` schema where I'd expect it to be created in the `core` schema. Is that how typeorm is supposed to work or a is this a bug?

**Comment by harikvpy** [comment]
I believe that is how it is supposed to work.

Currently, schema support is 'hard-wired' to the entity in its declaration. Meaning that the schema for an entity can be specified in the Entity decorator and if so declared, those entities will be created in the specified schema.

You can test it out. Use `@Entity({schema: <schemaName>})`.

I'm by no means an expert in TypeORM having picked it up in the last couple of weeks. So do test out my deduction with a live example.
