### ISSUE TITLE
Error on using TYPEORM_PORT environment variable

### ISSUE THREAD

**Issue by felixbillon** [typeorm/typeorm#5219]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm trying to run typeorm with environment variables.
In DockerFile : 

```yaml
ARG VERSION=12
FROM node:$VERSION-alpine

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn install --frozen-lockfile --silent --prod

COPY dist ./dist

EXPOSE 3000

ENV NODE_ENV=production
ENV PORT=3000
ENV TYPEORM_CONNECTION=mssql
ENV TYPEORM_PORT=1443
ENV TYPEORM_HOST=192.168.1.27
ENV TYPEORM_USERNAME=admin-fish
ENV TYPEORM_PASSWORD=root
ENV TYPEORM_DATABASE=FishFinder
ENV TYPEORM_ENTITIES=dist/**/*.entity.js
ENV TYPEORM_DRIVER_EXTRA='{"instanceName": "DESKTOP-LOJLH5K\\SQLEXPRESS"}'

CMD yarn start:prod
```
After build it and run it, I got the following error : 

`TypeError: The "config.options.port" property must be of type number.
    at new Connection (/app/node_modules/tedious/lib/connection.js:588:17)
    at /app/node_modules/mssql/lib/tedious/connection-pool.js:61:23
    at new Promise (<anonymous>)
    at ConnectionPool._poolCreate (/app/node_modules/mssql/lib/tedious/connection-pool.js:12:12)
    at ConnectionPool._connect (/app/node_modules/mssql/lib/base/connection-pool.js:166:10)
    at ConnectionPool.connect (/app/node_modules/mssql/lib/base/connection-pool.js:136:12)
    at /app/node_modules/typeorm/driver/sqlserver/SqlServerDriver.js:681:35
    at new Promise (<anonymous>)
    at SqlServerDriver.createPool (/app/node_modules/typeorm/driver/sqlserver/SqlServerDriver.js:672:16)
    at SqlServerDriver.<anonymous> (/app/node_modules/typeorm/driver/sqlserver/SqlServerDriver.js:204:51)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by niccolofanton** [comment]
Hi @felixbillon, I have the same issue with TYPEORM_PORT, the port string isn't parsed to number. There is a pull request for solving this issue: https://github.com/typeorm/typeorm/pull/4531

**Comment by imnotjames** [comment]
This should be fixed in the next release
