### ISSUE TITLE
default value "false" becoming "0"

### ISSUE THREAD

**Issue by hood** [typeorm/typeorm#5222]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Define an entity with a column of 'string' type, having either 'true' or 'false' as values.

______

Unfortunately a company which I'm working for has a column of type "string"("varchar" in the db), in which values can either be "true" or "false". I know this is bad design, but unfortunately there's nothing I can do to make their team revert this BAD design decision. Anyway the problem is that when the default value should be inserted in the database, "0" gets inserted instead of "false". Shouldn't users have a way to control this behavior?

**Comment by imnotjames** [comment]
Can you include your entity definition
