### ISSUE TITLE
TypeORM ReadStream to MySQL driver, so we can import big CSV files

### ISSUE THREAD

**Issue by calebeaires** [typeorm/typeorm#5224]
**Issue type:**
[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**
[x ] `mysql` / `mariadb`

**TypeORM version:**
[x ] `latest`

**Steps to reproduce or a small repository showing the problem:**

When using `LOAD LOCAL DATA INFLIE...` to import a big csv to MySQL database, TypeORM returns an error suggesting to use ReadStream. I now that on MySQL2 node module you can use somenthing like the above code, but with TypeORM I didnt find in documentation.

```javascript
// MYSQL2 node module
connection.query('SELECT * FROM table')
      .stream()
```

Here is my code using TypeORM
```typescript

// typeorm createConnection, then
// file size: 350mb

this.connection.query(`
LOAD DATA INFILE '/home/data.csv' INTO TABLE studio_data
  FIELDS TERMINATED BY ',';
`)
// results in a error
```

When using ` LOAD DATA INFILE... ` to import a **big csv** to MySQL database, TypeORM returns an error suggesting to use ReadStream. I now that on MySQL2 node module you can use somenthing like the above code, but with TypeORM I didnt find in documentation.

```javascript
connection.query('SELECT * FROM table')
      .stream()
```

*Error message*

```
As a result of LOCAL INFILE command server wants to read /home/data.csv file, 
but as of v2.0 you must provide 
streamFactory option returning ReadStream.
```

**Comment by calebeaires** [comment]
After some research, I found out that mysql2 has update its way to make load file infile works correctly. On this update, we need to pass to the dialect a ReadStream function.

> MAJOR: LOCAL INFILE does not automatically read #1034 from the local fs and now requires an explicit infileStreamFactory to be specified in query options.

Here is some example made on the pure mysql2

```javascript
const { Readable } = require('stream');
class EmptyStream extends Readable {
	_read(){
		this.emit('end');
	}
}

let dialectOptions = {
  infileStreamFactory: (name) => {
    console.log(`Server wants to access local ${name} file, access denied`)
    return new EmptyStream();
  }
};
```

how can we implement this with TypeORM

**Comment by imnotjames** [comment]
This doesn't seem to relate to an orm.

You should use the driver directly for a feature so separate from entities and anything that typeorm is good at, shouldn't you?

We aren't a complete "does everything" database connector.  Instead, it's a way to map data from objects in typescript to databases.

**Comment by dotMortis** [comment]
Was answered here: https://github.com/sidorares/node-mysql2/issues/1080#issuecomment-615901859
