### ISSUE TITLE
Subscriber not call when create and save new entity when run migration command

### ISSUE THREAD

**Issue by shuramita** [typeorm/typeorm#5225]
**Issue type:**

[x ] question 
[ ] bug report

**Database system/driver:**

[ x] `mysql` / `mariadb`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Setup typeorm configuration in .env like this.

`
....
TYPEORM_SUBSCRIBERS=src/modules/**/subscribers/*.subscriber.ts,src/modules/**/subscribers/*.subscriber.js,src/core/**/subscribers/*.subscriber.ts,src/core/**/subscribers/*.subscriber.js
`

Run migration 
```
ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js "migration:run"
```

add file src/modules/organization/subscribers/business-unit.subscriber.ts

```
import { EntitySubscriberInterface, EventSubscriber, InsertEvent } from 'typeorm';
import { BusinessUnitEntity } from '../entities/business-unit.entity';

@EventSubscriber()
export class BusinessUnitSubscriber implements EntitySubscriberInterface<BusinessUnitEntity> {
    listenTo() {
        return BusinessUnitEntity;
    }

    async afterInsert(event: InsertEvent<BusinessUnitEntity>) {
        console.log('It should run ');
       
    }
}
```

Expect function afterInsert called when create new BusinessEntity in migrations file
src/modules/organization/migrations/1575620763059-CreateBusinessUnitsTable.ts

```
  await BusinessUnitEntity.create({
            ...buConfig.defaultBuData, ...{
                ownerId: rootUser.id,
                organization,
                createdBy: rootUser.id,
            },
        }).save();
```

But the function never call

**Comment by imnotjames** [comment]
For questions and other general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
