### ISSUE TITLE
Why does querybuilder on manager only returns raw results?

### ISSUE THREAD

**Issue by bobo-le** [typeorm/typeorm#5229]
**Issue type:**

[x] question
[] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hey, why i can only retrieve raw results when using getManager() and from()?

**Steps to reproduce or a small repository showing the problem:**
```ts
// result is undefined
const tmp = await getManager().createQueryBuilder()
      .from(CronJob, 'cronjob')
      .getOne();

// contains correct raw results
const tmp2 = await getManager().createQueryBuilder()
      .from(CronJob, 'cronjob')
      .getRawOne();

// contains correct entity
const tmp3 = await getRepository(CronJob).createQueryBuilder()
      .getOne();
```

**Comment by imnotjames** [comment]
Pass the model to `createQueryBuilder`
