### ISSUE TITLE
Closure table isn't updated

### ISSUE THREAD

**Issue by b-ponomarenko** [typeorm/typeorm#5230]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I specified a model
```ts
@Entity()
@Unique(['name'])
@Tree("closure-table")
export class Category {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @TreeChildren()
  children: Category[];

  @TreeParent()
  parent: Category;
}
```
and DB structure
![image](https://user-images.githubusercontent.com/9141542/70813724-065ca680-1ddb-11ea-9517-ad52cc85f28d.png)

If I create entities in this way it'll be ok
```ts
const manager = getManager();

  const a1 = new Category();
  a1.name = "a1";
  await manager.save(a1);

  const a11 = new Category();
  a11.name = "a11";
  a11.parent = a1;
  await manager.save(a11);

  const a12 = new Category();
  a12.name = "a12";
  a12.parent = a1;
  await manager.save(a12);
```
Database looks like
```
category
| id | name | parent_id |
|----|------|-----------|
| 1  | a1   | null      |
| 2  | a11  | 1         |
| 3  | a12  | 1         |

category_hierarchy
| id_ancestor | id_descendant |
|-------------|---------------|
| 1           | 1             |
| 1           | 2             |
| 1           | 3             |
| 2           | 3             |
| 3           | 3             |
```
But if I try to create entities in another way I won't receive the expected result
```ts
const manager = getManager();

  const a11 = new Category();
  a11.name = "a11";
  await manager.save(a11);

  const a12 = new Category();
  a12.name = "a12";
  await manager.save(a12);

  const a1 = new Category();
  a1.name = "a1";
  a1.children = [a11, a12];
  await manager.save(a1);
```
DB looks like
```
category
| id | name | parent_id |
|----|------|-----------|
| 3  | a1   | null      |
| 1  | a11  | 3         |
| 2  | a12  | 3        |

category_hierarchy
| id_ancestor | id_descendant |
|-------------|---------------|
| 1           | 1             |
| 2           | 2             |
| 3           | 3             |
```
I think it's the wrong behavior. 

Or I just don't have the ability to create 3 `Category` entities and connect with each other (make update operation).
```ts
const manager = getManager();

  const a11 = new Category();
  a11.name = "a11";
  await manager.save(a11);

  const a12 = new Category();
  a12.name = "a12";
  await manager.save(a12);

  const a1 = new Category();
  a1.name = "a1";
  await manager.save(a1);

  a11.parent = a1;
  a12.parent = a1;

  await manager.update(Category, a11.id, a11);
  await manager.update(Category, a12.id, a12);
```
The same result.

Does typeorm have the ability to doing things like this?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
