### ISSUE TITLE
Infer nullability from type

### ISSUE THREAD

**Issue by sam3d** [typeorm/typeorm#5234]
**Issue type:**
[X] feature request

**Database system/driver:**
[X] `postgres`

**TypeORM version:**
[X] `latest`

---

Related to #201, isn't this:

```ts
class User {
    @Column()
    email?: string;
}
```

Functionally equivalent to this:

```ts
class User {
    @Column({ nullable: true})
    email?: string;
}
```

Is it programatically possible for the nullability of the database field to be inferred from the typescript optionality syntax?

**Comment by Kononnable** [comment]
`?` doesn't mean something is nullable, it means it can be not specified(undefined).
Anyhow, it is not possible to do such thing - `?` is not emitted by typescript compiler. 

`design:type` metadata is kind of weird here:
```
email1: string;                             - String
email2: string | null;                      - Object
email3: string | undefined;                 - Object
email4: string | null | undefined;          - Object
email5?: string;                            - String
email6?: string | null;                     - Object
email7?: string | undefined;                - Object
email8?: string | null | undefined;         - Object
```
`email5?: string; ` is emitted as string, but IntelliSense says it is `(property) Post.email5?: string | undefined` - so could be also emitted as `Object`.
