### ISSUE TITLE
Transaction across two connections

### ISSUE THREAD

**Issue by harikvpy** [typeorm/typeorm#5235]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I tried to search for this, but couldn't find a suitable question/answer.

Would it be possible to use a single transaction to wrap operations involving two separate Connection objects?

I have two separate connection objects -- one 'default' and one for another Postgres schema. Tables in both these connections need to be updated in a single operation. How can I wrap this entire sequence of DB ops in a single transaction? Any other mechanisms or third-party packages that'll help accomplish this?

TIA

**Comment by Kononnable** [comment]
How would you achieve this using plain sql(no ORM)? It looks like question outside of ORM responsibilities.

**Comment by harikvpy** [comment]
Thanks for following up.

To be honest I'm not that familiar with SQL and am just learning both (typeORM & sql). Researching a little bit on SQL, I now realize that the question is flawed as transactions have to be inherently bound to one connection.

**Comment by Kononnable** [comment]
There are e.g. distributed transactions, but they've got problems of theirs own, so I would avoid having single transaction on multiple servers wherever possible.

https://wiki.postgresql.org/wiki/Atomic_Commit_of_Distributed_Transactions
