### ISSUE TITLE
Using env vars for multiple databases

### ISSUE THREAD

**Issue by smr-dev** [typeorm/typeorm#5238]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have my main ormconfig.json in the route of my project that contains all my different databases which are on the same instance and share the same username and password. Can I set the environment variable options for username and password and will that same username and password be picked up by typeorm or do you need either use the json config or env variables?

**Comment by Kononnable** [comment]
You can use ormconfig saved as js module and use env variables there.
https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#using-ormconfigjs

**Comment by smr-dev** [comment]
@Kononnable Good shout, thanks :)
