### ISSUE TITLE
Nativescript support for typeorm

### ISSUE THREAD

**Issue by sanketsw** [typeorm/typeorm#524]
Hi
We are using Nativescript with Angular to implement a big commercial application in Australia. I would like to use typeorm with the typescript in the application so that I can use SQLite underneath the typescript data model. 

As I understand typeorm does not currently support Nativescript because of the requirement for node shim and lack of **Nativescript compliant driver**. We can help in validating and testing the driver and contribute back to typeorm if your team is willing to build the driver with us.

We would happy to provide you with a reference if the typeorm goes well for this commercial deployment.

Regards
Sanket

**Comment by pleerock** [comment]
Hi,

I would like typeorm to support nativescript too. Typeorm does not have to be run on node.js - you can see examples where typeorm runs in browser. I'm sure we can pack typeorm to run on nativescript too, just need to know what changes should be made to make it to work. Unfortunately at the moment there are plenty of other  tasks with more priority I have and I cannot afford to do this task right now. Plus I don't know nativescript specifics and how it works inside. If you are really interested in using typeorm with nativescript - please start contributing. I'll help as much as I can.

**Comment by NoNameProvided** [comment]
Most likely it will need a new `SQLiteNativeScript` driver since it cannot connect directly to SQLite as far as I know. TypeORM needs to use something like [nativescript-sqlite](https://github.com/NathanaelA/nativescript-sqlite).

**Comment by mobidev111** [comment]
this request is very similar to requests from the browser-based / cross-platform browser-based application. 

How does [nativescript-sqlite](https://github.com/NathanaelA/nativescript-sqlite) compare to the Cordova equivalent of [cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage)?

This may help us to join forces, see #548.

**Comment by pleerock** [comment]
all discussion should be moved into #548
