### ISSUE TITLE
Using repository in migration results in relation "foo" does not exist

### ISSUE THREAD

**Issue by mikecann** [typeorm/typeorm#5242]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Simply trying to use a repository in a migration results in error, im not sure if im supposed to do this or not..

e.g.

```typescript
export class AddedPlayers1576824417454 implements MigrationInterface {
  name = "AddedPlayers1576824417454";

  public async up(queryRunner: QueryRunner): Promise<any> {    
    const count = await queryRunner.connection.getRepository(DbMatch).count();
  }

...
```

Results in `UnhandledPromiseRejectionWarning: QueryFailedError: relation "match" 
does not exist`

Should it be possible to use repositories in migrations?

**Comment by etienne-martin** [comment]
I'm having the same issue. I saw [here](https://medium.com/@bansalsushil_34403/how-to-seed-typeorm-d9637a5948cc) that other people are doing the same thing. Not sure if that's a problem on my end or not.

**Comment by seltsamonkel** [comment]
Use `queryRunner.manager` to run the query in the same transaction as the one migrations are running.
I suspect that the table is being created in another migration file, but has not been committed, hence the error.

**Comment by etienne-martin** [comment]
What did the trick for me was to add `migrationsTransactionMode: "each"` to my typeorm config so that each migration have their own transaction.

**Comment by imnotjames** [comment]
This is because the migrations run in a transaction.

You're escaping the transaction by accessing the connection off the query runner & creating a new repository.

The new repository does not run within the transaction.
