### ISSUE TITLE
leftJoinAndSelect requires condition

### ISSUE THREAD

**Issue by jayalfredprufrock** [typeorm/typeorm#5243]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Not 100% positive, but it looks like a bad typing here: 
https://github.com/typeorm/typeorm/blob/d19162c8bca1d7f4bf4b7378e243932327b5e952/src/query-builder/SelectQueryBuilder.ts#L365

Per the docs, not seeing a reason why the condition should be required. Happy to submit a PR if this is indeed a bug.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
This indeed seems like a bug.  Easy fix, at least!
