### ISSUE TITLE
Support for Stored Computed Columns in Postgres 12

### ISSUE THREAD

**Issue by ziahamza** [typeorm/typeorm#5244]
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Currently TypeORM supports `asExpression` on columns to create computed columns for MySQL. PostgreSQL added support for stored computed columns in v12 and would love to see support come in TypeORM to extend `asExpression` for PostgreSQL as well.

**Comment by ziahamza** [comment]
Basically adding support for PostgreSQL as it was added for MySQL: https://github.com/typeorm/typeorm/commit/7a6dc511fb5d59b533b1e47bc21f6f7678b905df

**Comment by Anushil98** [comment]
@pleerock need this for postgreSQL

**Comment by lyxsus** [comment]
Any update?

**Comment by AlexMesser** [comment]
implemented in #6469
