### ISSUE TITLE
Support for specific postgres range operators

### ISSUE THREAD

**Issue by H6LS1S** [typeorm/typeorm#5245]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When there will be support for operators to work with range / array / geometry and .etc? In my opinion, such operators should be included in the same level with operators less*, more*, equal, and so on, since range filtering ( range is contained by - `<@`, contains range - `@>`, overlap - `&&`, [more](https://www.postgresql.org/docs/current/functions-range.html) )  is ubiquitous. If it is already released, can I get documentation or examples ?

**Steps to reproduce or a small repository showing the problem:**
At the moment, I need to use such a crutch in a situation where the fields in the request may be optional and the external interface is different from the search interface. 
**!!!The approach described below is not clean and not suitable as a permanent solution.!!!**
```ts
import { Transform, Type } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';
import { In, Raw} from 'typeorm';
import {
  IsUUID,
  IsOptional,
} from 'class-validator';

import { Range } from '../../../common/decorators/range.decorator';

export class GameFilter {
  @IsUUID()
  @IsOptional()
  @ApiProperty({
    required: false,
    example: 'b4e19ca1-48ea-482c-81ea-1f646d7f75d9',
  })
  public readonly id: string;

  @IsOptional()
  @Range(1, 40)
  @Transform(value =>
    Raw((alias: string) => `${alias} <@ '${JSON.stringify(value)}'`),
  )
  @ApiProperty({
    minimum: 1,
    maximum: 40,
    isArray: true,
    required: false,
    example: [1, 40],
    default: [1, 40],
    type: () => [Number, Number],
  })
  public readonly amount: [number, number];
```
Thanks in advance for reply

**Comment by swim** [comment]
I'm keen on the overlaps op as well!

**Comment by HELSIS666** [comment]
It is strange that in almost a month two people became interested in this problem.

**Comment by imnotjames** [comment]
It's not likely that we will be adding dialect specific operators in the near future.

This can be currently accomplished by the additions to `Raw` operator to support parameters & prevent SQL Injection.

```
const Overlap = value => Raw(alias => `${alias} <@ :value`, { value })
```
