### ISSUE TITLE
How to debug TypeOrm with typescript and VisualStudio

### ISSUE THREAD

**Issue by yanosh1982** [typeorm/typeorm#5247]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here

I have problems to debug a TypeOrm scaffolded application using typescript and VisualStudio.

Can you give me a valid launch.json configuration and some advice to make it work? 

I can successfully debug other script not using TypeOrm API

Thank you

**Comment by Kononnable** [comment]
Ok, but what is the problem? 
You've said that you can debug other scripts but not something connected with typeorm? Any errors?

**Comment by yanosh1982** [comment]
I've already solved my problem. Thank you and sorry.
