### ISSUE TITLE
Unable to resolve module `crypto` from `node_modules/typeorm/browser/util/StringUtils.js`

### ISSUE THREAD

**Issue by nochkin** [typeorm/typeorm#5249]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.22` (this is the `latest` at this moment)

When using with React Native I'm getting "Unable to resolve module `crypto`" error when trying to use TypeORM.
The issue appears in the 0.2.22 only. This is due to the following recent change:
https://github.com/typeorm/typeorm/commit/edc8e6dfd2c250656ab5b143297c60f57787ce77#diff-3fbb9e2b917220327e7c2fe6522c9b6d

**Steps to reproduce or a small repository showing the problem:**

```react-native init TypeormHash```
```cd TypeormHash```
```Add "import {Entity} from 'typeorm/browser';" at the top of App.js```
```react-native run-android```

**Comment by nochkin** [comment]
I guess this is open for discussions as I'm not sure this is the right approach.
My own fix is to use sha.js instead of "crypto" which is not available in RN:
https://github.com/nochkin/typeorm/commit/ba160304f89e8a533b075d4af9961066a09bd05a

**Comment by Kononnable** [comment]
It looks like a regression, so yes it is acceptable :)
Although this library was last updated 2 years ago, so there might be better alternatives.

@papermana There was any particular reason to use crypto, or just because it was available without need to download more dependencies.

**Comment by papermana** [comment]
@Kononnable No particular reason. As you say, it was simply there (or so I assumed). Any library that produces a SHA256 hash (or maybe a different one as well) should be ok.

**Comment by nochkin** [comment]
Thanks for confirmation.
The [sha.js](https://www.npmjs.com/package/sha.js) has over 3M weekly downloads according to npmjs. This was my main concerns when I picked up. Others were not so popular.
I'll create PR now.

**Comment by Kononnable** [comment]
My bad, I was having internet troubles and download graph wasn't showing properly.  Looks like it isn't updated frequently, because it is pretty stable.

**Comment by sallar** [comment]
Can we have a release please? The latest version is broken on React Native.

**Comment by nochkin** [comment]
@sallar,
I understand that will not answer your question as I don't know when 0.2.23 (or whatever will be the next version) will be released, but meanwhile you can keep the previous version in your RN app:

> yarn add typeorm@0.2.21

If you must have the latest bleeding edge, you can get it like this:

> yarn add https://github.com/typeorm/typeorm

**Comment by sallar** [comment]
Thanks @nochkin, I did that, but I didn’t end up using this library. I’m using React Native and typescript and no matter what I did, I couldn’t get it working with the decorator metadata. Installed everything as instructed and added proper babe plugins etc, but it didn’t work unfortunately. 

Thanks for the workaround anyway.

**Comment by nochkin** [comment]
If you are using older version, then your issue is not related to this change.
At least 0.2.21 works for my React Native project.
Maybe you should open a separate discussion thread to get it working.

**Comment by maixuanhan** [comment]
I face this : ```error: Error: Unable to resolve module `url` from `node_modules\typeorm\browser\util\OrmUtils.js`: url could not be found within the project.```

**Comment by nochkin** [comment]
@maixuanhan 
This is not related to the issue above. It's a separate issue.

**Comment by maixuanhan** [comment]
but it's similar, right? do you have issue number? thanks.

**Comment by nochkin** [comment]
How is it similar? I made a fix due to missing "sha". You are reporting something else which is not the cause or related to the "sha".
I suspect you commented on a wrong issue by mistake. Please check.

**Comment by maixuanhan** [comment]
Sorry, I don't want to argue with you about this but.. they are same category. Both use the non-existent client components. Components may be not the same but symptom is same, component is same. Why would open a new issue while this one is still opening? Even it is worth opening another issue, they will split it later when they fix your issue. Your contribution is very welcome and appreciated but please don't make yourself in-charge of this repo. 

BTW, you said you made "a fix". Well, if it is about "your fix" then, well, let's say.. yah, that's not a proper fix when you include a huge external library for all kind of platforms instead of use the right one for each. That I've not mentioned some native android/ios hash algorithms there. Your fix will bring the additional library to the application. "Your fix" works like a workaround only.

**Comment by likern** [comment]
> Sorry, I don't want to argue with you about this but.. they are same category. Both use the non-existent client components. Components may not be the same but symptom is same, root cause is same. Why would open a new issue while this one is still opening? Even it is worth opening another issue, they will split it later when they fix your issue. Your contribution is very welcome and appreciated but please don't make yourself in-charge of this repo.
> 
> BTW, you said you made "a fix". Well, if it is about "your fix" then, well, let's say.. yah, that's not a proper fix when you include a huge external library for all kind of platforms instead of use the right one for each. That I've not mentioned some native android/ios hash algorithms there. Your fix will bring the additional library to the application. "Your fix" works like a workaround only.

I agree, at least there should be stated what functions exactly are required from `crypto` module, for why and what kind of security / cryptographic security / collisions are expected.

Based on this information we might need to take knowledgeable actions.

Maybe it's really better to implement this in native or just create small supported library for this hashing algorithm. Given that sha.js is not actively maintained.

If it's just "simple hashing" without any cryptographic security with low collisions probability - as I think how that's crypto is used - then we can choose appropriate hashing algorithm for that.

**Comment by nochkin** [comment]
Symptoms are not the same (unless you refer "does not work" as an actual symptom in this case).
This issue was resolved long time ago as I made a fix for it and it was accepted. The fix is part of the release already. It's not a workaround.
I don't see how my fix created the issue you are referring to. This is the reason why I mentioned the issues are not related to each others.

I may be wrong here, but I would guess you saw my fix caused the issue you are reporting, this is why I explained why it's not the case because the issue is not the same.
Please feel free to share if this is not the case.

Yes, of course, a new issue worth opening a new issue for it so it can be properly tracked and addressed by community.

**Comment by papermana** [comment]
Guys, I feel like you're kind of ganging up on @nochkin for no good reason.

1. The problem has been fixed. Another similar problem will be more effectively dealt with by opening a new Github issue instead of commenting on an already forgotten one.
2. There's nothing wrong with the solution used here. SHA256 is not secure anyway, there's no need to overthink it.

I think this issue would best be closed.
