### ISSUE TITLE
In the readme persist is used, but it seems to be deprecated

### ISSUE THREAD

**Issue by bersling** [typeorm/typeorm#525]
In the readme `persist` is used, but it seems to be deprecated.

**Comment by bartlomiej-korpus** [comment]
Where is it deprecated?

**Comment by bersling** [comment]
EntityManager.d.ts of typeorm:0.1.0-alpha.4

It has @deprecated in the comments and Intellij interprets this as deprecated.

**Comment by bersling** [comment]
<img width="514" alt="screen" src="https://user-images.githubusercontent.com/10352805/26917639-5cb58ad6-4c2f-11e7-8106-89153f2be127.png">

**Comment by bartlomiej-korpus** [comment]
Oh, so you are talking about EntityManager's persist. Now I see. 
Should be probably changed to Repository's persist.

**Comment by pleerock** [comment]
Thank you, I know about it. I plan to update README at the end once `0.1.0` will be ready.

**Comment by pleerock** [comment]
You should start using `save` instead of `persist`.

**Comment by pleerock** [comment]
I'll update readme once 0.1.0 final is released. Thank you for pointing it out.
