### ISSUE TITLE
[Question] Can i do my query with find options ?

### ISSUE THREAD

**Issue by amourlanne** [typeorm/typeorm#5251]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello, is it possible to do my query with find options ?

My query who work fine
```ts
 return this.userRepository.createQueryBuilder('user')
        .innerJoinAndSelect('user.accountConfirmationToken', 'token')
        .where("token.value = :value", { value: token })
        .andWhere('token.used = false')
        .andWhere('token.expiredAt >= :expiredAt', { expiredAt: moment().toDate() })
        .getOne();
```
I try this with find options but don't work

```ts
  return this.userRepository.findOne({
        join: {
          alias: "user",
          innerJoinAndSelect: {
            accountConfirmationToken: "user.accountConfirmationToken",
          }
        },
        where: {
          accountConfirmationToken: {
            value: token,
            used: false,
            expiredAt: MoreThan(moment().toDate())
          },
        }
      });
```
With find options, the "Where" nested conditions are not considered

**Comment by amourlanne** [comment]
With find options, the "Where" nested conditions are not considered

**Comment by dsbert** [comment]
See https://github.com/typeorm/typeorm/issues/5215#issuecomment-566253819

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
