### ISSUE TITLE
Option migrationsTransactionMode not working with typeorm cli

### ISSUE THREAD

**Issue by chutiphon-k** [typeorm/typeorm#5252]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I config `migrationsTransactionMode: 'each'` and run the script with below but transaction mode is still `'all'` mode. This config working with `migrationsRun: true` but not working with cli.

# Typeorm config
```ts
const config: TypeOrmModuleOptions = {
  ...
  type: 'postgres',
  migrationsTransactionMode: 'each',
  ...
};
```
# Script
```bash
ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js --config src/databases/databases.config.ts migration:run
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by mtomic86** [comment]
Any update to this ticket?
I'm facing the same problem.

**Comment by jeiea** [comment]
MySQL seems to be same. `queryRunner.isTransactionActive` is true and rollback statement is shown but it doesn't rollback actually.

**Comment by robbiet480** [comment]
@nlenepveu It seems that `migrationsTransactionMode` wasn't properly implemented into the `migration:run` CLI command. Mind taking a look?

**Comment by nlenepveu** [comment]
I encourage anyone that faces the problem to take a look at the code and open a PR, this should not be a big deal. I won't be able to take a look at this in the coming days but as soon as I have the opportunity I will.

**Comment by jackieiscool** [comment]
Is there any updates on this? I can try to take a look the code and put in a PR but I'm very new to typeorm and typescript.
