### ISSUE TITLE
Pass undefined to findOne will return id 1 object

### ISSUE THREAD

**Issue by kievechua** [typeorm/typeorm#5254]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `latest`

```
console.log(id, 'undefined');
const group = await this.groupsRepository.findOne(id, { relations });
```
When pass undefined to findOne, it will produce sql with default id 1
```
WHERE "Groups"."group_id" IN (1)
```

**Comment by imnotjames** [comment]
This is a known issue and is planned to be fixed for the next minor release.
