### ISSUE TITLE
migrationsRun option act different from CLI

### ISSUE THREAD

**Issue by Mighty683** [typeorm/typeorm#5257]
**Issue type:**

[ x] question

**Database system/driver:**
[ x] `postgres`

**TypeORM version:**

[ x] `^0.2.19` 

On my project I have a problem

Using cli `migration:run` is working flawless, but using typeorm build with `nest.js` is causing to run all migrations from start with `migrationsRun` option set to `true` no matter what migrations were run before.
Does `migrationsRun` option cause omit check for runned migrations?

Output from running app:
```
server_1    | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
server_1    | query: START TRANSACTION
server_1    | query: CREATE TABLE <first_migration>... "
```
Output from running CLI:
```
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'migrations'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
No migrations are pending
```

**Comment by Kononnable** [comment]
Are you using exactly the same connection options? Is it using same file(ormconfig.json) or you have overridden those options in app code(e.g. manually call create connection with passed option object).
Please check if `dropSchema` setting is disabled - it's easy to miss it sometimes.

**Comment by Mighty683** [comment]
Thank you for help. I missed disabling `dropSchema`. Now both cli comand and project build work fine.
