### ISSUE TITLE
Missing documentation for save() method return value

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#5259]
Hello!

And once again, thank you for your hard work.

Today, I've noticed a strange behavior of the `save()` method. I was under impression that it returns the updated entity after persisting it to the database, but it isn't the case. I've looked into type declarations and documentation, but noticed that return value of this method is not documented anywhere.

Could you elaborate on what exactly should we expect from this method in respect to it's return value?

Looks like it returns the generated primary key after inserting record to the database, but other fields with the default values are not returned.

Thanks!

**Comment by imnotjames** [comment]
It returns a partial.
