### ISSUE TITLE
Adding Entities At Runtime to Entity Directory Array

### ISSUE THREAD

**Issue by totalard** [typeorm/typeorm#5261]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[*] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ *] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ *] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am Using NestJS With Typeorm. I have some issues in Entities Adding Dynamically.

I have some predefined Entitites in The System, I also have another Single Table Inheritance Entity(To do). When App Started, The Predefined Entities are loaded and Tables are Created. Its Okay.

When **App Running**. I want to add the second inherited Entity into the Entity Array so that the app sync the tables (Automatically or by some trigger).

Hope You Understood.

**Comment by Selast** [comment]
Hi. Did you find an issue ?

**Comment by chamerling** [comment]
Hello

Is there an API to register entities manually by giving classes to some manager without have Ng to give them to the connection options?

**Comment by imnotjames** [comment]
Entities must be added as part of the connection initialization process.  If you close the connection and open a new one you can update the entities.
