### ISSUE TITLE
how to write a subquery to retrieve up to 3 rows of the left panel

### ISSUE THREAD

**Issue by nonghaiqn195** [typeorm/typeorm#5267]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.22` (or put your version here)

Suppose `Review`  and `Comment` have relation one to many.
How to select all Review, each review has a maximum of `3` comments?
I searched and found that the subquery was applicable, but I didn't write how to write it,
please help me

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
