### ISSUE TITLE
Full text search in Postgres

### ISSUE THREAD

**Issue by Axmouth** [typeorm/typeorm#5272]
**Issue type:**

[ x] question
[ ] bug report
[ x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there a way to use this feature on Postgres from within typeorm(Full text search)? Looking in the settings definitions, it seems to apply only to MySQL, but I reckon Postgres has this kind of functionality as well.

**Comment by swim** [comment]
Have you seen, https://github.com/typeorm/typeorm/issues/3068

**Comment by Axmouth** [comment]
Greetings! This helps! Ideally I'd be able to use the fulltext index option for postgres too just like mysql, and adding a custom query later is less an issue. Thanks for the heads up!

**Comment by imnotjames** [comment]
Between the new functionality in `Raw` and the various other escape hatches available you should be good to go.
