### ISSUE TITLE
How to give privilege for sys user for oracle?

### ISSUE THREAD

**Issue by paul-thomas0** [typeorm/typeorm#5280]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
While creating the connection I am giving the following options
```javascript
import { createConnections } from "typeorm";
createConnections([{
                "name": "oracle_0",
                "type": "oracle",
                "host": "localhost/orcl",
                "port": 1521,
                "username": "sys",
                "password": "password",
                "sid": "",
                "connectionTimeout": 15000,
                "requestTimeout": 15000,
                "synchronize": true,
                'privilege': 'sysdba'
            }]);
```
which throws me the following error:
```error: ORA-28009: connection as SYS should be as SYSDBA or SYSOPER```
I couldn't find oracle connection options on https://typeorm.io/#/connection-options and at ```typeorm/src/driver/oracle/``` there is no mention for privilege option.

I have also tried:
```javascript
import { createConnections } from "typeorm";
createConnections([{
                "name": "oracle_0",
                "type": "oracle",
                "host": "localhost/orcl",
                "port": 1521,
                "username": "sys",
                "password": "password",
                "sid": "",
                "connectionTimeout": 15000,
                "requestTimeout": 15000,
                "synchronize": true,
                'privilege': 2
            }]);
```
as given in the node-oracledb documentation: https://oracle.github.io/node-oracledb/doc/api.html#oracledbconstantsprivilege
Oracle Db version: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Machine: OS Name	Microsoft Windows 10 Home Single Language, Version	10.0.18362 Build 18362

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by kenlane-af** [comment]
I have the same issue. I notice that  @paul-thomas0  had single quotes around "privilege". I tried adding the parm with double-quotes but still failed with ORA-28009. I don't have an invite to the slack community and SO doesn't seem to have any reference to this either. Anyone else? `Error: ORA-12545: Connect failed because target host or object does not exist`
