### ISSUE TITLE
Showing Unique Key instead of Foreign Key  with MySql 

### ISSUE THREAD

**Issue by BMLande** [typeorm/typeorm#5282]
[ ] question
Hi, Might be this is a silly mistake but I need to understand this one. I am just creating a simple example of one to one relation with MySql DB , I was gone through the same document provided on typeorm.io.
When I am creating One To One relation with User and Profile entities it's showing, profile Id as Unique key instead of foreign key on User Table. can you please make me clear here, just go through docs for one to one relationship.

My mySql Screenshot :
mysql> desc user;
+-----------+--------------+------+-----+---------+----------------+
| Field     | Type               | Null   | Key | Default | Extra          |
+-----------+--------------+------+-----+---------+----------------+
| id             | int(11)          | NO   | PRI | NULL      | auto_increment |
| name      | varchar(255) | NO   |         | NULL    |                |
| profileId   | int(11)          | YES  | UNI | NULL    |                |
+-----------+--------------+------+-----+---------+----------------+

You can check in above table description foreign key from profile added as UNI
I am also adding my User and Profile Entities.

User.ts
```
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  OneToOne,
  JoinColumn
} from "typeorm";
import { Profile } from "./Profile";

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToOne(() => Profile)
  @JoinColumn()
  profile: Profile;
}
```

```
import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

@Entity()
export class Profile {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  gender: string;

  @Column()
  photo: string;
}
```
Thanks .

**Database system/driver:**
[ ] `mssql`

**TypeORM version:**
[ ] `latest`

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
