### ISSUE TITLE
How use Find_in_set()?

### ISSUE THREAD

**Issue by ArmandoAA** [typeorm/typeorm#5284]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm using Typeorm to make my lib, but I found a problem, I need to store a array in a MariaDB cell, for this I converted array to string, now I need to use Find in set to find a elements in this Cell, but I cannot know how use Find In Set on typeorm.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by JohnnyB9991** [comment]
Why was this closed?

**Comment by vicary** [comment]
Why closed?

**Comment by gugug** [comment]
why??

**Comment by MohammadHussain1** [comment]
vhjnhj

**Comment by MohammadHussain1** [comment]
const vendors = await getManager()
      .createQueryBuilder(Users, 'users')
      .andWhere('users.stripeAccountId IS NOT NULL')
      .leftJoin(
        'users.vendor',
        'vendorDetail',
        'vendorDetail.profileCompletedStatus >= 6 AND vendorDetail.status = :status',
        { status: 1 },
      )
      .andWhere('FIND_IN_SET(:zipcodeId, vendorDetail.zipcodeIds)', { zipcodeId })
      .addSelect(['vendorDetail.id', 'vendorDetail.zipcodeIds', 'vendorDetail.accessoryIds'])
      .getMany();

**Comment by henafufa** [comment]
what if zipcodeId is string array input?
