### ISSUE TITLE
this.driver.connect is not a function

### ISSUE THREAD

**Issue by Vincenzo-DR** [typeorm/typeorm#5285]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi everyone, I'm trying to connect to a local PosstgreSQL server, my connection options are these:
```ts
      createConnection({
      type: 'postgres',
      host: 'localhost',
      port: 5432,
      username: 'xxx',
      password: 'xxx',
      database: 'xxx',
      entities: [
        'src/entity/**/*.ts'
      ],
      synchronize: true,
    }).then(async connection => {
      // here you can start to work with your entities
    }).catch(error => console.log(error));
```
In the console I get this message:
TypeError: this.driver.connect is not a function
Thanks for helping.

**Comment by wajdibeltaifa** [comment]
Hello @Vincenzo-DR, i have the same problem here with mysql driver, have you found any solution for this, please ?
Here's my connection options:
`createConnection({
      type: 'mysql',
      host: 'localhost',
      port: 3306,
      username: 'root',
      password: 'root',
      database: 'my_db',
      entities: [
        'src/entity/**/*.ts'
      ],
      synchronize: true,
    }).then(async connection => {
    }).catch(error => console.log(error));`

**Comment by Vincenzo-DR** [comment]
Hi, TypeOrm has no native support with Angular. I was trying to let it work
with it but I changed creating a backend server with NestJS, TypeOrm and a
RESTful architecture.
Hope it helps.
Vincenzo.

Il ven 17 gen 2020, 12:51 wbeltaifa <notifications@github.com> ha scritto:
