### ISSUE TITLE
How Add new entities to active Connection

### ISSUE THREAD

**Issue by totalard** [typeorm/typeorm#5291]
**Issue type:**

[* ] question
[ ] bug report
[ *] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ *] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there any way exist to add new Entity.ts Files or Add New entity directories to Active Connection. 
and Synchronize it.

or There is another logic I have, Just close the Active Connection, and create new Connection, this make resync entity with added new entity, But closing a connection and Connecting it Further doesn't synchronize it.

Please Help

**Comment by totalard** [comment]
I Mean.. Without Closing Connection.

**Comment by imnotjames** [comment]
Yes, this can be done.  You'd have to take a look at how the decorators work with the `MetadataArgsStorage` and replicate it.

It definitely won't be pretty but it can be done.

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
