### ISSUE TITLE
ManyToOne field not returned in queries

### ISSUE THREAD

**Issue by JorgeMorata** [typeorm/typeorm#5292]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[] `0.2.22`

**Steps to reproduce or a small repository showing the problem:**

With the next entity:

```
import {Column, Entity, ManyToOne, PrimaryGeneratedColumn} from 'typeorm';
import {ApiProperty} from "@nestjs/swagger";
import {Field, InputType, ObjectType} from 'type-graphql';
import {Agency} from '../agencies/agency.entity';

@InputType()
@ObjectType('user')
@Entity('users')
export class User {
    @PrimaryGeneratedColumn()
    @Field({ nullable: true })
    @ApiProperty()
    id: number;

    @Column({length: 100})
    @Field()
    @ApiProperty()
    name: string;

    @Column({length: 100})
    @Field()
    @ApiProperty()
    email: string;

    @Column({length: 100})
    @Field()
    @ApiProperty()
    fiscalId: string;

    @Column({comment: '1 - Administrator, 2 - Manager, 3 - Client'})
    @Field()
    @ApiProperty()
    type: number;

    @ManyToOne(type => Agency, agency => agency.users)
    @Field(type => Agency)
    @ApiProperty()
    agency: Agency;

    @Field({ nullable: true })
    password: string;

    @Column({length: 1024})
    hash: string;

    @Column({length: 32})
    salt: string;
}
```

The field **agency** is never returned in the query (in mysql has correct numeric value).

The UserService method is the next:
```
@Injectable()
export class UsersService {
    constructor(
        @InjectRepository(User)
        private readonly usersRepository: Repository<User>) {
    }

    async findAll(): Promise<User[]> {
        console.log(await this.usersRepository.find());
        return await this.usersRepository.find();
    }
}
```

Executing the findAll() the console.log writes:
```
User {
    id: 3,
    name: 'TestName',
    email: 'testname@testmail.com',
    fiscalId: '12345678Z',
    type: 2,
    hash: 'XXXXXXXX',
    salt: 'YYYYYYYY' }
```

I don't know if it's a bug, but i've allready read the TypeOrm documentation a few times and I don't found the problem.

**Comment by mendozammatias** [comment]
Hi @JorgeMorata !
I think you just have to indicate the agency relation in find callback options.
Something like this should work:
`
    async findAll(): Promise<User[]> {
        console.log(await this.usersRepository.find({relations: ['agency']}));
        return await this.usersRepository.find({relations: ['agency']});
    }
`

**Comment by JorgeMorata** [comment]
Hi @mendozammatias this is the solution!!!! Thank you very much for your comment!! :)
