### ISSUE TITLE
can you pass a parent class a parameter for a predefined association?

### ISSUE THREAD

**Issue by fabioespinosa** [typeorm/typeorm#5297]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Example:

Scenario:

There are multiple entities that can be reviewed. 

Each review has an association to comments, to a user who created it and some other attributes specific to that type of review.

For this example. Each review has an association to the entity being reviewed:

----

Is it possible to create an abstract class that has associations predefined, say something like the following (which I know is incorrect since i'm using the type as a value):

And then the type of the association be passed via parameter?

```typescript
@ObjectType({ isAbstract: true })
export abstract class Review<EntityBeingReviewed>  {

  @Column()
  rating: number;


  @Field(type => EntityBeingReviewed)
  @ManyToOne(
    type => EntityBeingReviewed,
    machine => machine.reviews, 
  )
  entityBeingReviewed: **EntityBeingReviewed**;
}
```

So is there a way to pass to a parent class some parameter so that it can then use the appropriate association entity type? In this case **EntityBeingReviewed**

This would certainly make my code much more maintainable as there are multiple entities my project "reviews".

**Comment by fabioespinosa** [comment]
I tried passing it via constructor (using prototype of EntityBeingReviewed) but I get the following error:

```
Error: Entity metadata for <entity> was not found. Check if you specified a correct entity object and if it's connected in the connection options
```

**Comment by Destreyf** [comment]
@fabioespinosa What you're looking for is essentially a polymorphic relationship, TypeORM doesn't directly support this, however i noticed you're using @ObjectType which is not a TypeORM decorator.

What you could do possibly, is create a factory function to define a base set of behavior and have a generic entity "Extend" the factory function, which would have a base class.  But this would ultimately end up in having a table/database for each type of Reviewable entity.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
