### ISSUE TITLE
Compile to production

### ISSUE THREAD

**Issue by kukuandroid** [typeorm/typeorm#5298]
**Issue type:**
[X] question

**Database system/driver:**
[X] `postgres`

**TypeORM version:**
[X] `latest`

**Steps to reproduce or a small repository showing the problem:**
Hello, how can build the dist folder just like NestJS that contain main.ts. Im going to use it for serverless build. Thank you

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
