### ISSUE TITLE
Field createdAt doesn't have a default value Issue

### ISSUE THREAD

**Issue by etudor** [typeorm/typeorm#5306]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I define my `User.ts` createdAt field in the following way
```ts
  @CreateDateColumn({ name: 'createdAt', type: 'datetime' })
  createdAt: Date
```

If I try to create a new user via the following code
```ts
  ...
  sampleUser.createdAt = new Date()
  ...

  await getRepository(User).save(sampleUser)
```
I get this error: 
```
UnhandledPromiseRejectionWarning: QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'createdAt' doesn't have a default value
```

I went into node_modules typeorm code and console logged the query and the params:

```
[ 'test@test.com',
  'John Doe',
  'hashedpass',
  'salt',
  'test',
  1,
  'admin' ] /// the createdAt field is missing?
```

Here is the definition of the `createdAt` property in my sql table: 
```
`createdAt` DATETIME NOT NULL,
```
The query looks good, but the field `createdAt` is missing from the params. 

1. The errors should log more details, like the full query and the full params. Some errors are so general that I have no idea where to start debugging.
2. I'm working on an existing database and I don't want to run sync, so my table doesn't have a default value for the `createdAt` field. Still, I should be able to set my own createdAt field in the code. I fail to understand why something so basic, simple and so straightforward fails?

**Comment by etudor** [comment]
I just found out about the `update` property of the CreateDateColumn
```   
     /**
     * Indicates if column value is updated by "save" operation.
     * If false, you'll be able to write this value only when you first time insert the object.
     * Default value is "true".
     */
    update?: boolean;
```

The default value should do the trick in my case but apparently it didn't so I manually set it to true with no success then set it to false with no success either. The `createdAt` is still missing from the params sent to mysql.

**Comment by tobyhinloopen** [comment]
Just curious: Is `sampleUser` an instance of `User`?

`console.log(sampleUser instanceof User)`

**Comment by etudor** [comment]
@tobyhinloopen  Yes.
```
const sampleUser = new User()
...

I skipped this issue by setting default value in my sql tables.
```
	`createdAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	`updatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
```

**Comment by tobyhinloopen** [comment]
@etudor I found out recently: If you use Typeorm CLI's `migration:generate`, `UpdateDateColumn()` and `CreateDateColumn()` create migrations with a default current_timestamp. I think that is "the" way to use these column types.

**Comment by sangwoo-98** [comment]
Without using the "skipping" way shown in this issue's title, the same issue is also happening with MySQL and MariaDB also.

**Comment by AlexMesser** [comment]
> I'm working on an existing database and I don't want to run sync, so my table doesn't have a default value for the createdAt field. Still, I should be able to set my own createdAt field in the code

`@CreateDateColumn` uses database level `default` to generate a new timestamp. So, you can't use this decorator without any changes to the database schema.
