### ISSUE TITLE
It wont work in angular2

### ISSUE THREAD

**Issue by badcoder28** [typeorm/typeorm#531]
Im having this issue while connecting to the database following both the [installation](https://typeorm.github.io/index.html#installation) and the [quickstart ](https://typeorm.github.io/index.html#quick-start) but in **Angular2** approach.

This is my application looks like:

**app.component.ts file**
```
import "reflect-metadata";

import { Component, OnInit } from '@angular/core';

import { createConnection } from "typeorm";
import { Photo } from "./Photo";


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
  title = 'app';

  constructor() { }

  ngOnInit(): void {

    createConnection({
      driver: {
        type: "mysql",
        host: "localhost",
        port: 3306,
        username: "root",
        password: "admin",
        database: "crud-angular2"
      },
      entities: [
        Photo
      ],
      autoSchemaSync: true,
    }).then(connection => {
      // here you can start to work with your entities
    }).catch(error => console.log(error));

  }

}
```
___

**photo.ts**
```
import {Entity, Column, PrimaryGeneratedColumn} from "typeorm";

@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        length: 500
    })
    name: string;

    @Column("text")
    description: string;

    @Column()
    fileName: string;

    @Column("int")
    views: number;

    @Column()
    isPublished: boolean;
}
```
___

**The Angular2 application is working fine but it has a warning telling me that:**
> Mysql package has not been found installed. Try to install it: npm install mysql --save 

But in my `package.json` it is already installed.

**Comment by NoNameProvided** [comment]
You cannot use TypeORM in the browser with _MySQL_, you have to use the _WebSQL_ driver.

To use TypeORM with MySQL you have to use NodeJS.

**Comment by badcoder28** [comment]
@NoNameProvided hi there thanks for your reply, aint that angular2 is running via node?

**Comment by NoNameProvided** [comment]
Angular 2 runs in your browser when users are using it. It's not node, the two are different.

**Comment by DavidPMacNeil** [comment]
You want something like [this](https://github.com/typeorm/typescript-express-example/tree/master/src). You are running Angular 2 as the client, and Node is the server. Install express on your server, and use express and node to make a backend API. You will need to connect to the DB in the backend, which will create your files in the DB. Next, you need routes, and controllers, the route defines what action from the controller will be completed. Finally, in Angular 2 you can hit the API endpoints to work with the data.

**Comment by badcoder28** [comment]
@NoNameProvided thanks for your reply, ill try what @DavidPMacNeil  suggested, it is very interesting.. thanks a lot you guys. I'll close this issue once resolve.
