### ISSUE TITLE
creating entity on the root folder instead of the specified path

### ISSUE THREAD

**Issue by artoodeeto** [typeorm/typeorm#5310]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

hello sir. I have here my `ormconfig.ts` file I used to use the json format but with just the else block of code and now I decided to use ts file and put my logic here if its a test or development, but the problem now is that when I do `npx typeorm entity:create -n Post` the cli directories are not being read? (im not sure) because its being generated on the root folder and not on the directory. Is there a sample that you could give me a link? thank you.

```
let ormConfig: any;

if (process.env.NODE_ENV === 'test') {
  // test environment database should be drop every time. so synchronize should be true for this config
  ormConfig = {
    type: 'mysql',
    // host: '0.0.0.0',
    host: 'localhost', // not needed if run on docker
    username: 'root',
    password: 'password',
    database: 'test_db',
    synchronize: true,
    dropSchema: true,
    entities: ['src/models/**/*.ts']
  };
} else {
  ormConfig = {
    type: 'mysql',
    // host: 'db', // docker service database name
    host: 'localhost', // not needed if run on docker
    port: 3306, // not needed if run on docker
    username: 'root',
    password: 'password',
    database: 'development_db',
    synchronize: false,
    logging: true,
    entities: ['src/models/**/*.ts'],
    migrations: ['db/migrations/**/*.ts'],
    subscribers: ['src/subscribers/**/*.ts'],
    cli: {
      entitiesDir: 'src/models',
      migrationsDir: 'db/migrations',
      subscribersDir: 'src/subscribers'
    }
  };
}

export = ormConfig;
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
Is this still a problem?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
