### ISSUE TITLE
Entity resolver by type

### ISSUE THREAD

**Issue by dgram** [typeorm/typeorm#5311]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I search for an solution to resolve an entity or to handle like doctrine embedded columns, for example:

If you have 3 Post-Types:
- PostEntity
- ImagePostEntity
- SurveyPostEntity

We need to handle them in an single table. The idea is, to define an PostEntity with fields like:
- post-type: enum('image', 'survey')
- additional: json

```ts
enum PostTypeEnum {
    Image  = 'image',
    Survey = 'survey'
}

@Entity('posts')
class PostEntity
{
    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        type: 'enum',
        enum: PostTypeEnum,
        default: PostTypeEnum.Image
    })
    type: PostTypeEnum

    @Column({ type: 'json' })
    additonal: object
}

class SurveyPostEntity extends PostEntity
{
    type: PostTypeEnum = PostTypeEnum.Survey

    public set questions(questions: string[])
    {
        // convert array to json
        this.additional = getObjectFromArray(questions);
    }

    public get questions(): string[]
    {
        return getArrayFromObject(this.additional);
    }
}
```

Is it possible to add an resolver, so the entity manager return the SurveyPostEntity instead of the PostEntity if type is PostTypeEnum.Survey and to transform? The idea is to save the posts in the 'posts' table and resolve them to the right Object i.e. SurveyPostEntity.

**Comment by Destreyf** [comment]
@dgram Currently this isn't possible in typeorm from what i understand, what you're looking for is referred to as a PolyMorphic relationship, it would be super helpful if TypeORM had native support for them but it doesn't at this time.

Maybe someone has found a workaround, here's issues referring to polymorphic relationships: https://github.com/typeorm/typeorm/issues?utf8=%E2%9C%93&q=is%3Aissue+PolyMorphic

**Comment by dgram** [comment]
@Destreyf thanks for your fast answer. yes, its exactly what i'm searching for. we run into an workaround and use json types and save the objects directly into the column, for relations we use the single table inheritance, it's not the best solution but works for us in this way.

but i'm with you, the native support would be very usefull
