### ISSUE TITLE
Can't add new command when connection is in closed state

### ISSUE THREAD

**Issue by daweedm** [typeorm/typeorm#5316]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
{ QueryFailedError: Can't add new command when connection is in closed state
 |        at new QueryFailedError (/usr/src/my-app/src/error/QueryFailedError.ts:9:9)
 |        at Query.onResult (/usr/src/my-app/src/driver/mysql/MysqlQueryRunner.ts:166:37)
 |        at PoolConnection._addCommandClosedState (/usr/src/my-app/node_modules/mysql2/lib/connection.js:139:11)
 |        at PoolConnection.query (/usr/src/my-app/node_modules/mysql2/lib/connection.js:534:17)
 |        at MysqlQueryRunner.<anonymous> (/usr/src/my-app/src/driver/mysql/MysqlQueryRunner.ts:155:36)
 |        at step (/usr/src/my-app/node_modules/tslib/tslib.js:136:27)
 |        at Object.next (/usr/src/my-app/node_modules/tslib/tslib.js:117:57)
 |        at fulfilled (/usr/src/my-app/node_modules/tslib/tslib.js:107:62)
 |        at process._tickCallback (internal/process/next_tick.js:68:7)
 |      message: 'Can\'t add new command when connection is in closed state',
 |      fatal: true,
 |      name: 'QueryFailedError',
 |      query: 'COMMIT',
 |      parameters: [] } }
```

With no reason, the underlying mysql connection seems to be closed. It seems related to connection pooling (see https://github.com/sidorares/node-mysql2/issues/939)

How can we fix that using typeorm ?

**Comment by Destreyf** [comment]
@daweedm 

I am not using MySQL myself at this time, however looking at this (as i was curious) it appears TypeORM is already using createPool (the "solution" that the last comment mentions).

You can see it here: [drivers/mysql/MysqlDriver.ts](https://github.com/typeorm/typeorm/blob/0.2.22/src/driver/mysql/MysqlDriver.ts#L332-L341)

Based on the code in that link (which is the code in release 0.2.22) it appears it will use "createPool" or "createPoolCluster" depending on if you're using replication. 

Are you using replication?  I think having a repository showcasing the issue could help, although i understand that it's not always easy to show break down issues like this.

Another thought, is you could pass in a keep-alive argument to the underlying driver using the "extra" configuration parameter: https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md

Are you using a connection string or are you passing in a config object, it might be helpful to see a copy of your connection config (omit any username/password/database names for security).

**Comment by daweedm** [comment]
@Destreyf 

I'm using a config object : 

```js
 { name: 'default',
   type: 'mysql',
   host: 'db',
   port: 3306,
   entities: [ 'src/**/*.Entity.ts' ],
   migrations: [ 'src/migration/**/*.ts' ],
   subscribers: [ 'src/**/*.Subscriber.Entity.ts' ],
   cli:
    { entitiesDir: 'src/entity',
      migrationsDir: 'src/migration',
      subscribersDir: 'src/subscriber' },
   synchronize: false,
   logging: false,
   username: 'xxx',
   password: 'xxx',
   database: 'app',
   namingStrategy: SnakeNamingStrategy {} }
```

Could this error happen if I try to save something to a repository that is not transactional inside a transactionalManager callback ?

I just find that was a mistake in the code, but I'm not sure that's the origin of the problem, i.e. somehting like that : 

```ts

class SomeClass() {
    constructor() {
         this.repository = getRepository(SomeEntity);
    }

    someMethod() {
         await getManager().transaction(transactionalManager => {
              this.repository.save(something); // <-- this should be transactionalManager.save(...)
              // may this wrong use of transaction cause this kind of problem ?
         });
    }
}

Also, when saw the log, the problem showed up when called very quickly about 10 to 15 times the `someMethod()` described here. Could the connection pool be affected with that ?

Many thanks !

**Comment by daweedm** [comment]
Someone just added a comment by pointing out that the author of the issue is, in fact, already using pooled connection, as him (https://github.com/sidorares/node-mysql2/issues/939)

So it does not seem related to the use or not of mysql connections pools

**Comment by Destreyf** [comment]
In the case you mentioned where you're using a repository that's from outside the transaction, yes that would cause issues.

You need to use the  @TransactionRepository() in your method instead of your global one in the constructor as the repository likely isn't bound to a pooled connection once it's inside the connection manager.

See here: https://github.com/typeorm/typeorm/blob/master/docs/transactions.md#transaction-decorators

**Comment by daweedm** [comment]
Ok, so either using @TransactionRepository() or the `transactionalManager` (as I write in the comments in the code) in the case I mentioned will prevent the error to happen ?

**Comment by daweedm** [comment]
And a last question : is it error prone to keep a repository in a class variable and reuse it **without using transactions**, should I except errors by doing that ? May the "cached repository" expires or something like that ? Or should it be fine if I ensure that I never merge the use of transactionalRepositories and "normal" ones

**Comment by daweedm** [comment]
Or is it best to call the `getRepository(...)` every time I need it ?

**Comment by Destreyf** [comment]
@daweedm Sorry i was away from my computer for a bit.

You can use a global one instantiated on the constructor, i would just be careful when doing transactions as they have to exist within the scope of the transaction.

**Comment by daweedm** [comment]
@Destreyf No problem, thanks for your help !

**Comment by itinance** [comment]
faced the same issue in a NestJS application using TypeORM exactly reproducable after a Query for the 150 time (no transaction, no writes, only reads).
