### ISSUE TITLE
make primary column optional

### ISSUE THREAD

**Issue by saostad** [typeorm/typeorm#5317]
error message: 
```
Use @PrimaryColumn decorator to add a primary column to your entity.
``` 
```
import { Column, Entity, Index } from "typeorm";

@Index("biARBL", ["co", "mth", "batchId", "batchSeq", "arLine"], {
  unique: true,
})
@Index(
  "biARBLApplied",
  ["co", "applyMth", "applyTrans", "applyLine", "mth", "batchId", "batchSeq"],
  {},
)
@Entity("bARBL", { schema: "dbo" })
export class BArbl {
  @Column("tinyint", { name: "Co" })
  co: number;

  @Column("smalldatetime", { name: "Mth" })
  mth: Date;

  @Column("int", { name: "BatchId" })
  batchId: number;

  @Column("int", { name: "BatchSeq" })
  batchSeq: number;

  @Column("smallint", { name: "ARLine", nullable: true })
  arLine: number | null;

  @Column("char", { name: "TransType", length: 1 })
  transType: string;
}
```

I can't add @PimaryColumn on all fields of my index because one of them `arLine` is nullable.

_Originally posted by @saostad in https://github.com/typeorm/typeorm/issues/3704#issuecomment-573211839_

**Comment by AnanthGopal** [comment]
when releasing this feature?

**Comment by Kononnable** [comment]
>I can't add @PimaryColumn on all fields of my index because one of them arLine is nullable.

It's a 'limitation' of sql, not orm related. Primary key columns aren't allowed to be nullable.

@AnanthGopal  Which feature?

**Comment by AnanthGopal** [comment]
I can't run my application when my table doesn't have a primary key. I need an entity without a primary key. 

-

**Comment by Kononnable** [comment]
Typeorm requires entity to have primary key defined to work correctly and there are no plans to change that.
If you don't want to use primary key(or you're forced not to use it) you can mark unique index as primary key and disable schema sync for such table. It would deceive ORM and you should be able to use such table.

**Comment by AnanthGopal** [comment]
Thank you for your answer. My table doesn't have a unique index so that I am asking that functionality.

**Comment by korniychuk** [comment]
Pay attention for projects that works with TimeScaleDB (a PostgreSQL extension). Most of the hyper tables in this database can't have a primary key.

**Comment by kodi** [comment]
Did anyone figured out how to create models for TimeScaleDB that only have index on `timestamp` columns?

**Comment by Maddimax** [comment]
> you can mark unique index as primary key

How can I mark a unique index as a primary key? I could not find anything in the documentation.

**Comment by SvenC56** [comment]
Was anyone able to make TypeORM working with TimescaleDB?

**Comment by matthewdowns** [comment]
Not sure if you still need an answer to this, but I managed to make it work by just having two primary keys
```
import { Column, Entity, Index, PrimaryColumn } from "typeorm";

@Index(
  "biARBLApplied",
  ["co", "applyMth", "applyTrans", "applyLine", "mth", "batchId", "batchSeq"],
  {},
)
@Entity("bARBL", { schema: "dbo" })
export class BArbl {
  @PrimaryColumn("tinyint", { name: "Co" })
  co: number;

  @PrimaryColumn("smalldatetime", { name: "Mth" })
  mth: Date;

  @PrimaryColumn("int", { name: "BatchId" })
  batchId: number;

  @PrimaryColumn("int", { name: "BatchSeq" })
  batchSeq: number;

  @PrimaryColumn("smallint", { name: "ARLine", nullable: true })
  arLine: number | null;

  @Column("char", { name: "TransType", length: 1 })
  transType: string;
}
```

Hope it helps.
