### ISSUE TITLE
Automatically generate models from existing database

### ISSUE THREAD

**Issue by arzzzae** [typeorm/typeorm#532]
Is there a plan to implement this feature?

**Comment by pleerock** [comment]
its almost pointless. Even if you generate models from the database they will be relationless and with bad naming of entities, columns and other properties.

**Comment by pleerock** [comment]
but if someone thinks different and can provide a really good implementation of this feature I would accept that with pleasure

**Comment by pleerock** [comment]
duplicate of #540 so closing it

**Comment by Maydmor** [comment]
For those still looking for an alternative

You can also use an online tool like 

[Evernox](https://evernox.com/)

It has tools to directly generate code in multiple languages from your database. 

It's really easy : 

- Create a new diagram 

- Click on "Connect Database" and sync Evernox with your Database

- Click on "Generate code" and select Type ORM from the list
