### ISSUE TITLE
Mongo - properties that aren't defined are saved to database

### ISSUE THREAD

**Issue by flobiber** [typeorm/typeorm#5321]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
@Entity()
export class User {
  @ObjectIdColumn()
  id: number;

  @Column()
  firstName?: string;
}

repo.save({
  firstName: 'My',
  lastName: 'Me' //<- This is possible, although it's not defined! 
})

```

Is there a possibility to forbid saving not described properties?

**Comment by Davut97** [comment]
Can i take this?
