### ISSUE TITLE
How is the performance of property .take(10) and .skip (10) when I have 10.000 registres

### ISSUE THREAD

**Issue by pookdeveloper** [typeorm/typeorm#5322]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

How is the performance of property .take(10) and .skip (10) when I have 10.000 registres,
It get all rows and then cut 0 to 10 ? o is like limit ??

Thanks.

**Comment by krislefeber** [comment]
TypeORM uses the database to do the take and skip commands. Since you asked specifically about mysql, I would look here: https://dev.mysql.com/doc/refman/8.0/en/limit-optimization.html. It would have to do a full table scan in some scenarios, but with only 10,000 rows that shouldn't be a problem.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
