### ISSUE TITLE
Cannot get the correct class out of inheritance relation

### ISSUE THREAD

**Issue by GeeWee** [typeorm/typeorm#533]
Hi.

I want to have a relation, in this case between Widgets, and DataFetcherStrategies. I'd like to be able to give Widgets a base-class, inherit that, and then automatically get the correct subclass. I have tried multiple types of inheritance, the SingleTableInheritance seems to get me closest.
In code:

```javascript
//widget.ts

@Entity()
export class Widget {
    @PrimaryGeneratedColumn()
    id: number;
    
    @OneToOne(type => DataFetchingStrategy, (widget) => widget.widgetOwner)
    dataFetcher: DataFetchingStrategy;
}

//data-fetching-strategy.ts
@Entity()
@TableInheritance("single-table")
@DiscriminatorColumn({name: 'type', type: 'string'})
export class DataFetchingStrategy {
    @PrimaryGeneratedColumn()
    id: number;

    @JoinColumn() //Does not matter who owns join
    @OneToOne(type => Widget, (widget) => widget.dataFetcher)
    widgetOwner: Widget;

    fetchData() {
        throw new Error('must subclass method')
    }
}

@SingleEntityChild()
@DiscriminatorValue('Strategy1')
export class ConcreteDataFetchingStrategy1 extends DataFetchingStrategy {
    public fetchData(): any {
        console.log('Strategy 2 called');
    }
}
```

and a test: 
```javascript
const widget = new Widget();
widget.dataFetcher = new ConcreteDataFetchingStrategy1() ;
await widgetRepo.persist(widget);
const widgetsFromDb = await widgetRepo.createQueryBuilder('widgets')
  .leftJoinAndSelect('widgets.dataFetcher', 'fetcher')
  .getRawMany();
```
returns 
[ RowDataPacket {
        widgets_id: 1,
        widgets_description: '',
        widgets_dataFetcher: 1,
        widgets_owner: null,
        fetcher_id: 1,
        fetcher_type: 'DataFetchingStrategy',
        fetcher_strat1Integer: null,
        fetcher_Strat2String: null } ]

Where I would expect `fetcher-type` to be `Strategy1`.
I would also expect that it is cast to the correct class, e.g. the instance that I would get back would be a ConcreteDataFetchingStrategy1. 
 
Is there any way of doing what I'm trying to do?

**Comment by pleerock** [comment]
as I understood you want to have different entities to be mapped into the `Widget#dataFetcher`. You kinda can use single table inheritance but I don't recommend to use it because its quite unstable and very limited type of inheritance. Alternative is to have multiple relations, e.g. `Widget#ftpDataFetcher`, `Widget#fileDataFetcher`, ... which may not convenient, but is natural way of doing things - you can then manually collect fetchers and expose them in a single getter / method / property

**Comment by GeeWee** [comment]
Yes you understood correctly :)
Okay, thanks for that - is the functionality I'm looking for something you're you plan on supporting at some point in the future, or is there technical reasons why it'll never happen?

**Comment by pleerock** [comment]
there are technical reasons, you can't create interface-based/abstract relations, because you need concrete tables with which relations are created in the database.

**Comment by GeeWee** [comment]
Fair enough. I just figured that if we checked at runtime what the @DiscriminatorValue for the actual derived class was, and inserted that in the table, it would be possible.

**Comment by GeeWee** [comment]
So I did some mucking around, and it's definitely technically possible.
Here's a test that demonstates getting the correct Repository from a subclass.

```javascript
it('Should be able to fetch a repo for subclass', async () => {
		//Instantiate strategy and cast to superclass
		const dfs1 : DataFetchingStrategy = new ConcreteDataFetchingStrategy1();
		//get repo for superclass, but with metadata from subclass
		const repo : Repository<DataFetchingStrategy> = connection.getRepository(dfs1.constructor.name) as Repository<typeof dfs1>;
		await repo.persist(dfs1);
		const results = await repo.find();
		expect(results[0] instanceof ConcreteDataFetchingStrategy1).toEqual(true);
	});
```

**Comment by pleerock** [comment]
its possible if you use single table inheritance. Single table inheritance has its own limitations and something used in very specific use cases. I was talking about regular relations.

**Comment by GeeWee** [comment]
I see. Fair enough - thanks for your time. :)

**Comment by cgdangelo** [comment]
My issue seems related to this discussion so I didn't want to open another. @pleerock can you clarify if the limitations on regular relations that you're talking about are the cause of my error? I'm doing something like:

```typescript
abstract class AbstractEntity {
  @OneToOne(() => User)
  public createdBy: User;

  @OneToOne(() => User)
  public updatedBy: User;
}

class User extends AbstractEntity {}
```

```
/Users/charles.dangelo/Documents/Workspace/dsl/node_modules/tslib/tslib.js:53
        extendStatics(d, b);
        ^
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (native)
    at Object.__extends (/Users/charles.dangelo/Documents/Workspace/dsl/node_modules/tslib/tslib.js:53:9)
    at /Users/charles.dangelo/Documents/Workspace/dsl/src/entities/User.ts:5:35
    at Object.<anonymous> (/Users/charles.dangelo/Documents/Workspace/dsl/src/entities/User.ts:5:1)
    at Module._compile (module.js:571:32)
    at Module.m._compile (/Users/charles.dangelo/Documents/Workspace/dsl/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/charles.dangelo/Documents/Workspace/dsl/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

The relations work as expected when moved to the concrete `User` class.

**Comment by pleerock** [comment]
When you are using `@OneToOne` decorator you MUST put `@JoinColumn` on it, e.g.

``ts
abstract class AbstractEntity {
  @OneToOne(() => User)
  @JoinColumn()
  public createdBy: User;

  @OneToOne(() => User)
  @JoinColumn()
  public updatedBy: User;
}
```

Also, did you put `@Entity` decorator on `User` object?

**Comment by cgdangelo** [comment]
Sorry, was trying to reproduce code from memory. 😆 I have those decorators as well and still get that error.

**Comment by bombillazo** [comment]
> there are technical reasons, you can't create interface-based/abstract relations, because you need concrete tables with which relations are created in the database.

This in the docs would be vital to many with a complex relational data model!
