### ISSUE TITLE
How can i use src for development purpose

### ISSUE THREAD

**Issue by totalard** [typeorm/typeorm#5333]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[ *] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ *] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ *] `0.2.21` (or put your version here)

When i Installed typeorm with npm i typeorm.. i got built version of it. I just need source package with my developement. i want to implement some modifications in the code..

When i used src with my app. It triggers errors. mostly type related..

What is the issue.. How can i use src with my app.. 

shall i have to build each time to use it.. 

please help

**Comment by justblender** [comment]
Clone this repository, install required dependencies using `npm install` and then proceed with `npm run package` to build a distribution package, which will be located in `build/package` directory. More on setting up development environment is in this [document](https://github.com/typeorm/typeorm/blob/master/DEVELOPER.md).
