### ISSUE TITLE
Default value is not escaped when using enum, which cause error: cannot use column reference in DEFAULT expression

### ISSUE THREAD

**Issue by ksewo** [typeorm/typeorm#5335]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have simple migration.
```typescript
import {
  MigrationInterface,
  QueryRunner,
  Table,
} from 'typeorm';

export class CreateExampleable1578929385472 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(new Table({
      name: 'example',
      columns: [
        {
          name: 'id',
          type: 'int',
          isPrimary: true,
          isGenerated: true,
        },
        {
          name: 'enum',
          type: 'enum',
          enum: ['A', 'B', 'C'],
          default: 'A',
        },
      ],
    }));
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('example');
  }
}
```

I am getting error: QueryFailedError: cannot use column reference in DEFAULT expression

SQL which cause issue:
`CREATE TABLE example(... "status" "example_enum_enum" NOT NULL DEFAULT A ... )`

It should quote default value:
`CREATE TABLE example(... "enum" "example_enum_enum" NOT NULL DEFAULT 'A' ... )`

I had to quote default value my self to make it work:
(Without whitespaces, whitespaces added, to make it visible)
`default: " 'A' "`

**Comment by andrewdhazlett** [comment]
I had a similar error when adding a column with a default value, no db-level enum involved:
> I was able to fix a similar issue (on postgres) by wrapping my default value in single quotes:
> ![image](https://user-images.githubusercontent.com/2836999/73193905-ef56e700-40f0-11ea-9b47-1a1452245f30.png)
> 
> Previously I was getting the error `column "open" does not exist`:
> ![image](https://user-images.githubusercontent.com/2836999/73194300-9d629100-40f1-11ea-8225-718e24f52739.png)
> 
> This is downright baffling behavior.

(quoted from https://github.com/typeorm/typeorm/issues/2980)

**Comment by agoulziprod** [comment]
this solution found here: [https://github.com/typeorm/typeorm/issues/4833](https://github.com/typeorm/typeorm/issues/4833) worked for me finally,
```
{
    name: 'status',
    type: 'enum',
    enum: ['active', 'inactive', 'paused'],
    enumName: 'statusEnum',
    default: '"inactive"'
}
```

**Comment by petrusdemelo** [comment]
The @agoulziprod 's solution don't work to me. But that works:

```
{
   name: 'type',
   type: 'enum',
   enum: ['provider', 'client'],
   default: `'client'`,
}

**Comment by elhaouari-mohammed** [comment]
workaround 
```javascript
{
  name: "gender",
  type: "enum",
  enumName: "gender",
  enum: ["male", "female", "other"],
  default: `"other"`, // eslint-disable-line quotes
  isNullable: false,
}
```

**Comment by stazrad** [comment]
@elhaouari-mohammed the double quotes did not work for me but the single quotes in the backticks worked @petrusdemelo -- thank you! (strange bug)

**Comment by elhaouari-mohammed** [comment]
@stazrad well this entire behaviour is weird, it should not be the case.

**Comment by heinekenbh** [comment]
`{
   name: 'default_theme',
   type: 'enum("Light", "Dark")',
   isNullable: false,
  default: '"Light"'
}`

This works for me.

**Comment by AlexMesser** [comment]
You should manually escape values in `column.default` , because it suppose to accept SQL expressions, not just string or number values.

**Comment by elioenays** [comment]
> The @agoulziprod 's solution don't work to me. But that works:
> 
> ```
> {
>    name: 'type',
>    type: 'enum',
>    enum: ['provider', 'client'],
>    default: `'client'`,
> }
> ```

solved for me
