### ISSUE TITLE
Exclude seeded data from subscribers

### ISSUE THREAD

**Issue by HunterJS-bit** [typeorm/typeorm#5346]
**Issue type:**

[X ] question

**Database system/driver:**

[ X] `postgres`

**TypeORM version:**
[ X] `latest`

Hi guys Im using TypeORM for my project and currently I'm stuck at subscribers, Im having problem that my beforeInsert method is activated in subscriber is activated,
Is there any way to exlude subscriber on seed files or before seeeder is run to deactivate subscriber ?

Here is my subscriber:

```
mport { EntitySubscriberInterface, EventSubscriber, InsertEvent, UpdateEvent } from 'typeorm';
import { User } from '../users/user.entity';

@EventSubscriber()
export class HistorySubscriber implements EntitySubscriberInterface<User> {

    listenTo() {
        return User;
    }


    // eslint-disable-next-line no-unused-vars
    async beforeInsert(event: InsertEvent<User>) {
        // this gets called contantly when I seed data ????
    }



}

```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
