### ISSUE TITLE
Exclude certain field from being selected?

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#535]
Is it possible to exclude some fields from being selected during the query building, like an opposition of `addSelect()`, for example:
````
let results = this.ormRepository.createQueryBuilder("i")
                   .excludeSelect("i.comment')
                   .leftJoinAndSelect("i.someData", 'o')
                   .where("i.id >:id",{id:20})
````
I don't need the `comment` field in every query and it feels like a waste when it is being fetched every time.

**Comment by pleerock** [comment]
try this:

```ts
 const posts = await connection.createQueryBuilder(Post, "post")
            .select("post.id")
            .addSelect("category.name")
            .leftJoinAndSelect("post.category", "category")
            .getMany();
```

**Comment by pleerock** [comment]
e.g. you specify everything you want to select instead of including

**Comment by pleerock** [comment]
Did my answer help you?

**Comment by stonecold123** [comment]
@pleerock 
Thank you.

Can you please consider a method like `excludeSelect` so that I only need to provide the column I want to include without specifying every column I want to select.

**Comment by pleerock** [comment]
No, Im sorry this looks like a side-effect method and not something needed for mainstream.

**Comment by RDeluxe** [comment]
my2c => this could be useful for some data, like passwords, that you don't want to select. Having to write all the fields to select except the one is cumbersome.
I can understand your point though.

**Comment by Daynil** [comment]
@RDeluxe I had the same thought, however I realized the answer is in the docs.

```
@Column({select: false})
password: string;
```

Whenever you select the item with the password, you would have to explicitly "addSelect", otherwise this field is effectively excluded from general selects.

http://typeorm.io/#/select-query-builder/hidden-columns

**Comment by webmobiles** [comment]
why use:

`.addSelect("category.name")'`

is not easier use:

`.select([ "category.name", "post.id" ])`

?

**Comment by pleerock** [comment]
@webmobiles just matter of taste probably, it looks good when you chain many expressions each in one row

**Comment by pookdeveloper** [comment]
> try this:
> 
> ```ts
>  const posts = await connection.createQueryBuilder(Post, "post")
>             .select("post.id")
>             .addSelect("category.name")
>             .leftJoinAndSelect("post.category", "category")
>             .getMany();
> ```

Dosen't work for me

**Comment by mcchrish** [comment]
Would be nice to not resort to query builder if possible and do it via the repository methods instead. e.g. `repository.find({ forceSelect: true })` or `{ forceSelect: ['password'] }`

**Comment by rednebmas** [comment]
In my case, for the fields to be automatically serialized to the returned object, I had to use `UppercaseModelName.fieldName` in the addSelect method like so

```js
return getRepository(User)
	.createQueryBuilder()
	.where(findConditions)
	.addSelect('User.passwordHash')
	.addSelect('User.refreshToken')
	.getOne();
```

**Comment by gideaoms** [comment]
This approach hides the fields only when sent to the user.

```
@Entity('examples')
class MyEntity {
      toJSON () {
          delete this.password;
          return this;
  }
}
```

**Comment by abhijithvijayan** [comment]
> toJSON () {
>           delete this.password;
>           return this;
>   }

Thank you so much :)

**Comment by kennylbj** [comment]
For now, we can use select option in find method:
```ts
@Column({select: false})
password: string;


await this.repository.findOne({
      select: ['id', 'username', 'password'],
      where: { username }
 });
```

**Comment by vikrambhatla** [comment]
> For now, we can use select option in find method:
> 
> ```ts
> @Column({select: false})
> password: string;
> 
> 
> await this.repository.findOne({
>       select: ['id', 'username', 'password'],
>       where: { username }
>  });
> ```

I am seeing following error message:
error message: Cannot read property 'username' of undefined

**Comment by vikrambhatla** [comment]
Actually I figured out, I had ValidationPipe so the wrong username was coming as undefined which is the correct behavior.

**Comment by SakirSoft** [comment]
> ```ts
> leftJoinAndSelect
> ```

Try leftJoin instead of leftJoinAndSelect, worked for me. Hope this helps.

**Comment by SakirSoft** [comment]
> > try this:
> > ```ts
> >  const posts = await connection.createQueryBuilder(Post, "post")
> >             .select("post.id")
> >             .addSelect("category.name")
> >             .leftJoinAndSelect("post.category", "category")
> >             .getMany();
> > ```
> 
> Dosen't work for me

Try leftJoin instead of leftJoinAndSelect, worked for me. Hope this helps.

**Comment by fselcukcan** [comment]
> 
> 
> @RDeluxe I had the same thought, however I realized the answer is in the docs.
> 
> ```
> @Column({select: false})
> password: string;
> ```
> 
> Whenever you select the item with the password, you would have to explicitly "addSelect", otherwise this field is effectively excluded from general selects.
> 
> http://typeorm.io/#/select-query-builder/hidden-columns

Looks like that would just not work with decorated Primary keys in entities. Otherwise to me the cleanest and most declarative way is that one seems to be that one.

**Comment by y-nk** [comment]
adding on @fselcukcan , this approach does not work with views since the `select: false` prop doesn't appear in `@ViewColumn()` decorator.

**Comment by sergiuturus** [comment]
> @RDeluxe I had the same thought, however I realized the answer is in the docs.
> 
> ```
> @Column({select: false})
> password: string;
> ```
> 
> Whenever you select the item with the password, you would have to explicitly "addSelect", otherwise this field is effectively excluded from general selects.
> 
> http://typeorm.io/#/select-query-builder/hidden-columns

It looks like this isn't working when using `.find()` method.

```
constructor(
  @InjectRepository(User)
  private usersRepository: MongoRepository<User>,
 ) {}

const users = await this.usersRepository.find({
  select: ['id', 'firstName', 'lastName', 'email', 'role']
});
```
still selects the password field :(

**Comment by sangimed** [comment]
> my2c => this could be useful for some data, like passwords, that you don't want to select. Having to write all the fields to select except the one is cumbersome. I can understand your point though.

Using @Exclude()'s `class-transformer` solves the issue for passwords.

**Comment by Eduwardo** [comment]
What's the point of having select options working with value object like this: 

`await this.repository.findOne({
      select: [{username: true}]
 });`


but not: 

What's the point of having object with true value working: 

`await this.repository.findOne({
      select: [{username: false}]
 });`

**Comment by g-radam** [comment]
@Eduwardo This was the behavior I expected too. If the property is specified and the value is a boolean, it denotes if it should be selected or not. Else, null or undefined means default behavior. Superficially, I don't see any reason why this could be retroactively added??
