### ISSUE TITLE
Typeorm need to be packaged to check with NestJS..Fix?

### ISSUE THREAD

**Issue by totalard** [typeorm/typeorm#5351]
**Issue type:**

[ *] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ *] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.22` (or put your version here)

Dear,

I need to do some changes in Typeorm. I am using NestJS here. So i have put typeorm source to my project directory and imported all decorators (etc) from this source typeorm..

This make some error when nestjs compile. mostly Type related issues
like (string|number)[]  ie.. enum  doesnt have method like .replace() ..

so i build it. the build doesnt has any issues. it works fine. but building for every check is not at all good.. Any Solution to use SRC with my project

**Comment by imnotjames** [comment]
You'll need to build typeorm then link it using `npm link`.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
