### ISSUE TITLE
React native - pre-populate sqlite db

### ISSUE THREAD

**Issue by Ontegor** [typeorm/typeorm#5363]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[0.2.20] `0.x.xx` (or put your version here)

Hello!

I have installed:
"react-native": "0.61.5",
"react-native-sqlite-storage": "^4.1.0",
"typeorm": "0.2.20"

I want to use a pre-populated database. Before that I read it [https://github.com/andpor/react-native-sqlite-storage#importing-a-pre-populated-database](url) But I can’t connect the database in this way

I created a database in the folder android/app/src/main/assets/www

My code for db connection

```
createConnection({
  type: 'react-native',
  database: 'test.sqlite',
  location: 'default',
  createFromLocation: 1,
  name: 'test',
  logging: ['error', 'query', 'schema'],
  synchronize: true,
  entities: [InitialTable, TodoItemTable, TodoCategoryTable],
})
```

Thanks!

**Comment by kranczeer** [comment]
+1, it will be very helpful option

**Comment by rickydj** [comment]
Hi, i've checked all logs that typeorm has sent to the console, and i saw something important, this behavior occurs always the system creates a new database, this is my log:

OPEN database: teleapp.db
OPEN database: teleapp.db - OK
query:  PRAGMA foreign_keys = OFF;
query:  BEGIN TRANSACTION
query:  SELECT 'DROP TABLE "' || name || '";' as query FROM "sqlite_master" WHERE "type" = 'table' AND "name" != 'sqlite_sequence'
query:  DROP TABLE "Tipo_segmento";
query:  DROP TABLE "Listas";
query:  DROP TABLE "Parametros";
query:  DROP TABLE "Direcciones";
query:  DROP TABLE "Unidades";
query:  DROP TABLE "Clientes";
query:  DROP TABLE "Solicitudes";
query:  DROP TABLE "Comentarios";
query:  DROP TABLE "Zonificacion";
query:  DROP TABLE "Servicios";
query:  DROP TABLE "Geopos";
query:  DROP TABLE "Estados";
query:  DROP TABLE "Mantenimiento";
query:  DROP TABLE "DetalleCotizacion";
query:  DROP TABLE "Elementos";
query:  DROP TABLE "Cotizaciones";
query:  DROP TABLE "documentos";
query:  DROP TABLE "Encargados";
query:  DROP TABLE "encuestas";
query:  DROP TABLE "android_metadata";
query:  COMMIT
query:  PRAGMA foreign_keys = ON;

even if you set the synchronize option to false, i gues it could be an action or option to avoid this, but i cant found anything that i can use to,

i will search for this option, and if i resove this, i'll tell you

**Comment by Thomascogez** [comment]
I have face the same issue recently and I found this solution. I found in the doc that you can pass non-specified parameters to the database driver by using the property "extra". 

So if i have a database store in android/app/src/main/assets/www/db.db
I have to use this config to acces it : 

```js
createConnection({
 type:'react-native',
 location:'default',
 database:'db.db',
 extra: {
  createFromLocation:'~www/db.db'
 }
 entities: [.....]
})
```
If you have install your app on your device previously, make sure to recompile everythings and delete all old data of the application / unistall it.

Also make sure to disable synchronized (it can delete table from your database if your don't have implemented all entities)

**Comment by imnotjames** [comment]
sounds like it's sort of handled with the `createFromLocation`
