### ISSUE TITLE
Generated Identity

### ISSUE THREAD

**Issue by Css-IanM** [typeorm/typeorm#5365]
**Issue type:**

[ ] question
[ ] bug report
[ x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Include Decorator or decorator parameters for primary key identity IE: Postgres 10+ 
```sql
GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY { ( sequence_option ) }
```

**Comment by mitsos1os** [comment]
IMO this should also be the default behavior for `@PrimaryGeneratedColumn()` under PostgresVesion > 10 using an options flag during the connection or something

**Comment by mitsos1os** [comment]
@pleerock @AlexMesser I am willing to issue a non-breaking PR for implementing this feature in a flag-option enabled way.
Would this be something that you would consider accepting as a feature, or should I not deal with it at all?
Thanks!
