### ISSUE TITLE
Load ALL Relations of an entity

### ISSUE THREAD

**Issue by joris1995** [typeorm/typeorm#5366]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[X] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

In an app I'm building, I have cases where I need to load fully populated objects.T That includes the all layers of relations as wel. I can do this manually, but that seems really messy and I can't imagine there isn't a way to accomplish this with query builder.

How can one load ALL layers of relations of an entity?

**Comment by joelcoronah** [comment]
Hi, any update?

**Comment by blandman** [comment]
I found a workaround

```
let relations = this.store.metadata.relations.map(relation => {
    return relation.propertyName;
});
const entity: Entity | undefined = await this.store.findOne(id, { relations });
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
