### ISSUE TITLE
Return undefined instead of null?

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#5368]
**Issue type:**

[X] question
[X] feature request

**Database system/driver:**

[X] `postgres`

**TypeORM version:**

[X] `latest`

---

Hello!

Is it possible to make TypeORM to return `undefined` instead of `null` for columns with `NULL` values in them?

This will really help to make values consistent, because missing values will be represented by a single `undefined` value not two different values (`undefined` and `null`).

The other way would be to initialize all empty values in my new entities with `null`s, but it would be cumbersome and will make code more complex.

---

```typescript

class MyEntity {
  @Column()
  const value?: string;
}

const myEntity = new MyEntity();

expect(myEntity.value).to.be.undefined; // OK

myEntity = await entityManager.save(myEntity);

expect(myEntity.value).to.be.undefined; // Not OK, its null now

```

**Comment by imnotjames** [comment]
If you'd like this behavior you can add a listener or subscriber that `@AfterLoad` sets null values to undefined.

https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md

**Comment by imnotjames** [comment]
Coming back to this I was thinking about it some.

> Is it possible to make TypeORM to return undefined instead of null for columns with NULL values in them?

I don't think this is the case.  These are two very different mechanisms and states.  `NULL` is that the data has been loaded but is null.  Undefined is that it isn't there.

I'll be closing this out.

**Comment by Asondo** [comment]
The value in entity is optional, so, if it doesnt set it has to be undefined. Null means the value is exists and uts value is null in typescript, but the value is not set and in the world of typescript this is exact undefined value. Dont mix null in postrges with null in typescript please, it is not cool.

In other way we have to set optional type as `Type | null` and it is silly for the value that as you expect may not be set at all.

**Comment by Asondo** [comment]
May be it will be good to add flag to config like `undefinedAsNull: boolean` or something like that

**Comment by jesusbarcenilla** [comment]
I also think it should be at least a flag in typeorm but this is my workaround in case someone find it useful:

All my entities implement this base class.

```
import { AfterLoad } from "typeorm";

export abstract class EntityWithUndifinedValues {

  @AfterLoad()
  private nullToUndefined() {
    const instance: any = this;

    Object.getOwnPropertyNames(instance).forEach((p) => {
      if (instance[p] === null) {
        instance[p] = undefined;
      }
    });
  }
}

```

**Comment by edeesis** [comment]
I agree with imnotjames's accessing of this issue.

In my opinion - the fact that Javascript has a meaningful difference between `null` and `undefined` is a great thing, and should be embraced.

To me this is the meaning they have in TypeORM:

null - the value is NULL in the database
undefined - the value wasn't queried for

I think the best typing for nullable fields is:

```typescript
class MyEntity {
  @Column({ nullable: true })
  const value: string | null;
}
```

but as noted in https://github.com/typeorm/typeorm/issues/4139 that triggers `Data type "Object" in "Article.title" is not supported by "postgres" database`. So until that issue is actually fixed (despite it being marked as completed). I'm doing this:

```typescript
class MyEntity {
  @Column({ nullable: true, type: String })
  const value: string | null;
}
```
