### ISSUE TITLE
Alter failing mssql

### ISSUE THREAD

**Issue by DavidPMacNeil** [typeorm/typeorm#537]
Alter table does not appear to be working in MSSQL. I initially discovered this with #520, however I wasn't sure that was happening. Now, adding UpdatedAt, and CreatedAt fields, the fields will be created with no problem. But, trying to alter to make one or either of the columns lowercase gives the following error:

`query failed: ALTER TABLE "cat" ADD "createdAt" datetime NOT NULL
[3] (node:18032) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TransactionError: Transaction has been aborted.`

Altering the name of any other field works fine. However, it seems to fail on imported columns, such as Relations, or TypeORM columns like Updated and Created. 

This is the error I got for creating FK in #520:
`query failed: ALTER TABLE "WO_Location" ADD CONSTRAINT "fk_e286f587045b523da57d0b40829" FOREIGN KEY ("customerCustomerID") REFERENCES "WO_Customer"("CustomerID") [2] (node:19352) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TransactionError: Transaction has been aborted`

**Comment by pleerock** [comment]
fixed in `0.1.0-alpha.10`
