### ISSUE TITLE
Default enum null value causes a bug

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [typeorm/typeorm#5371]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `mysql` / `mariadb`

**TypeORM version:**

[x] `latest`
[x] `@next`

**Steps to reproduce or a small repository showing the problem:**
Create an enum column with default value null
```ts
enum MyEnum {
  valueA = 'valueA',
  valueB = 'valueB',
}

@Entity()
export class Entity extends BaseEntity {
  @Column({
    type: 'enum',
    enum: MyEnum,
    nullable: true,
    default: null,
  })
  field?: MyEnum;
}
```

result 
```js
{
  message: "Invalid default value for 'field'",
  code: 'ER_INVALID_DEFAULT',
  errno: 1067,
  sqlState: '42000',
  sqlMessage: "Invalid default value for 'field'",
  name: 'QueryFailedError',
  query: "ALTER TABLE `entity` CHANGE `field` `field` enum ('valueA', 'valueB') NULL DEFAULT 'null'",
  parameters: []
}
```

It should've generated  `query: "ALTER TABLE ``entity`` CHANGE ``field`` ``field`` enum ('valueA', 'valueB') NULL DEFAULT null"`,

Adding `&& defaultValue !== null` seems to work
https://github.com/typeorm/typeorm/blob/e8eb98b0bd3c551d82c3f6fd0899259ea868c685/src/driver/mysql/MysqlDriver.ts#L572

**Comment by robertrypula** [comment]
Any updates on this topic? I'm stuck in the same issue :(

**Comment by agoulziprod** [comment]
this solution found here: [https://github.com/typeorm/typeorm/issues/4833](https://github.com/typeorm/typeorm/issues/4833) worked for me finally,
```
{
    name: 'status',
    type: 'enum',
    enum: ['active', 'inactive', 'paused'],
    enumName: 'statusEnum',
    default: '"inactive"'
}
```

**Comment by falahati** [comment]
This happens with PostgreSQL as well.
Following is the result of TypeOrm field definition:
```sql
"status" "status_enum" DEFAULT \'null\'
```
From:
```typescript
@Column({ name: "status", type: "enum", enum: Status, nullable: true, default: undefined  })
public winner: Status| null = null;
```
Resulting in:

> 'invalid input value for enum status_enum: "null"'

Probably due to putting null inside `''` and escaping it.

Suggested answer by @robertrypula just removes the default value since by setting the property to `undefined` we are telling TypeOrm that there is no default value for this field and therefore we have to provide the value when creating a row. This is not a workaround. So as of now, we can't use nullable enum fields.

**Comment by falahati** [comment]
The same fix when applied here should fix the problem with PostgreSQL:

https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L724

**Comment by pleerock** [comment]
what is the point to set `default: null`, if when you set `nullable: true` database already sets you a null by default?

**Comment by nebkat** [comment]
It is probably unnecessary if the database uses null by default, but likely the user is just trying to be explicit with the default value and there shouldn't be unexpected behavior like this.
