### ISSUE TITLE
Is there a way to get all Columns and types from an Entity? 

### ISSUE THREAD

**Issue by ELI7VH** [typeorm/typeorm#5375]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Trying to find a way to do this, I can't seem to find any search results either. I am just looking for a way to get all colum names and types from my entities after they have been created! is this possible?

**Comment by bobo-le** [comment]
The result of ```getConnection().getMetadata(YourEntity)``` contains infos about columns, relations, ...

**Comment by imnotjames** [comment]
Hopefully that answered your question.  You should be able to use the metadata to understand yourmodel just as typeorm does!

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
