### ISSUE TITLE
Update @UpdateDateColumn when relation is updated

### ISSUE THREAD

**Issue by sebamomann** [typeorm/typeorm#5378]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X] `0.2.22` (or put your version here)

Is there any way that the `@CreateDateColumn` in Entity "Appointment" gets updated when a relation get's updated?

Appointment Entity
```
@Entity()
export class Appointment {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({nullable: false})
    title: string;

    @Column({nullable: false})
    description: string;

    @Column({nullable: false, unique: true})
    link: string;

    @Column({nullable: false})
    location: string;

    @Column('timestamp', {nullable: false})
    date: Date;

    @Column('timestamp', {default: null})
    deadline: Date;

    @Column('int', {default: null})
    maxEnrollments: number;

    @OneToMany(type => Enrollment,
        enrollment => enrollment.appointment, {
            eager: true
        })
    enrollments: Enrollment[];

    @OneToMany(type => Addition,
        addition => addition.appointment,
        {
            eager: true,
        })
    additions: Addition[];

    @Column('smallint', {default: false})
    driverAddition: boolean;

    @ManyToMany(type => User,
        user => user.administrations,
        {eager: false})
    @JoinTable()
    administrators: User[];

    @OneToMany(type => File,
        file => file.appointment,
        {
            eager: true,
        })
    files: File[];

    @ManyToOne(type => User,
        user => user.appointments)
    @JoinColumn()
    creator: User;

    @CreateDateColumn()
    @Exclude({toPlainOnly: true})
    iat: Date;

    @UpdateDateColumn({name: 'lud', nullable: true})
    @Exclude({toPlainOnly: true})
    lud: Date;
}
```
Enrollment Entity
```
@Entity()
@Index("index_unique_name_appointment", ["name", "appointment"], {unique: true}) // first style
export class Enrollment {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({nullable: false, unique: true})
    name: string;

    @Column({nullable: true})
    comment: string;

    @OneToOne(type => Driver, driver => driver.enrollment,
        {
            eager: true,
            onUpdate: "CASCADE",
        })
    driver: Driver;

    @OneToOne(type => Passenger,
        passenger => passenger.enrollment,
        {
            eager: true,
            onUpdate: "CASCADE",
        })
    passenger: Passenger;

    @ManyToMany(type => Addition, {eager: true})
    @JoinTable({name: 'enrollment_addition'})
    additions: Addition[];

    @ManyToOne(type => Appointment,
        appointment => appointment.enrollments)
    appointment: Appointment;

    @OneToMany(type => Comment,
        comment => comment.enrollment,
        {
            eager: true
        })
    comments: Comment[];

    @CreateDateColumn()
    iat: Date;

    @ManyToOne(type => User,
        {onDelete: "CASCADE"})
    @JoinTable({name: 'enrollment_creator'})
    creator: User;

    @OneToOne(type => Key,
        key => key.enrollment,
        {onDelete: "CASCADE"})
    key: Key;

    @UpdateDateColumn({name: 'lud', nullable: true})
    @Exclude({toPlainOnly: true})
    lud: Date;

    editKey: string;
}
```

So when updating an Enrollment, kind of "trigger" the `@UpdateDateColumn` in the Appointment Entity. The relation get's updated by its specific ID.

**Comment by dinhphuochiep** [comment]
Is there any way update @UpdateDateColumn when only updating its relations.

**Comment by gabriellupu** [comment]
A workaround would be to add a new entity property:
```ts
@Column()
tempUpdatedAt: Date;
```
and manually setting the current date when updating the relations
```ts
<entity>.tempUpdatedAt = new Date();
repositoru.save(<entity>);
```
Very frustrating that the `UpdateDateColumn` is not updated when updating relations 😢

**Comment by hiepinnomizetech** [comment]
A workaround:
`
Change
@UpdateDateColumn({name: 'lud', nullable: true})
    lud: Date;
To
@Column({name: 'updated_at', nullable: true})
    updatedAt: Date;

Then using Subscribers of TypeORM to manual handling this field
beforeUpdate(event: UpdateEvent<any>) {
    if (event.entity) {
      event.entity.updatedAt = new Date();
    }
  }
`

**Comment by royi-frontegg** [comment]
Will there be a native solution for that instead of these workarounds ?

**Comment by imnotjames** [comment]
Not likely - you are modifying a relationship - not the record itself.  Because of this, we don't update the `UpdatedAt`

**Comment by imnotjames** [comment]
There were answers supplied via the subscribers & listeners.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by TiE23** [comment]
> A workaround: ` Change @UpdateDateColumn({name: 'updated_at', nullable: true}) updatedAt: Date; To @column({name: 'updated_at', nullable: true}) updatedAt: Date;
> 
> Then using Subscribers of TypeORM to manual handling this field beforeUpdate(event: UpdateEvent) { if (event.entity) { event.entity.updatedAt = new Date(); } } `

I had e2e errors occur when I followed the suggestion of changing to `@Column(...)`. I left it as `@UpdateDateColumn(...)` and it worked for me.

**Comment by emmyduruc** [comment]
@TiE23 what version of TypeOrm are you using? for my case @UpdateDateColumn({name: 'updated_at', nullable: true}) does not update automatically i needed to assign new Date() which is really annoying.

**Comment by ahoys** [comment]
In cases where you are trying to update relations via the record (i.e. `profile.images = [Image]; profile.save()`), the trick seems to be to use `@VersionColumn` and manually up it: `model._version += 1;` before saving. This will also update the `@UpdateDateColumn`.

The drawback is that the version will up with 2, instead of 1 now, but in most cases I'd imagine this to be trivial. You could also make a separate `@Column` for this purpose only, but I find that a bit messy.

And obviously this doesn't work if you are directly altering the relation record and saving that.
