### ISSUE TITLE
how to create middleware for Every Express Request to share a Transaction

### ISSUE THREAD

**Issue by yangguang-hs** [typeorm/typeorm#5388]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an express app, and for each request, I may add/update multiple Entities, how to add the middleware to do the transaction so that I don't need to do init transaction in each controller, so that I can roll back the all the changes if something happen.
I define my controller inside the AppRouter.
I want to be able rollback the transaction in handleError. and commit if nothing happen
```
app.use(auth);
app.use('/', AppRouter);
app.use(handleError);
```

This is the way I save data into DB: 
```
await getManager().getRepository(Role).save(existingRole);
```

I have try this, but seems cannot rollback the changes
```
app.use(async (req, res, next) => {
  getConnection().manager.transaction(txMgr => {
    return new Promise(resolve => {
      res.locals.txMgr = txMgr;
      res.on('finish', () =>{console.log("complete"); resolve();});
      next();
    });
  });
});
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
