### ISSUE TITLE
Allow manual rollback or commit of transaction

### ISSUE THREAD

**Issue by yonilerner** [typeorm/typeorm#539]

**Comment by pleerock** [comment]
Everything you wrap into transaction will be executed and in the end transaction will be commited. You can throw exception in your transaction function and rollback will be executed. Why do you need more then this? But yeah, you can do manual rollback and commit, but using more low-level api.

**Comment by yonilerner** [comment]
@pleerock How can I access this lower level API? I dont see any references in the documentation.

Throwing exceptions of course works, but its often more cumbersome than really necessary if all I want to do is rollback a transaction based on a condition

**Comment by pleerock** [comment]
as of `0.1.0-alpha.9` its possible using this syntax:

```ts
const queryRunner = connection.driver.createQueryRunner(); // queryRunner is a single real connection to the database obtained from a connection pool
await queryRunner.startTransaction();
// execute sql queries using queryRunner
await queryRunner.commitTransaction(); // or .rollbackTransaction()
await queryRunner.release(); // don't forget to release connection, very important!
```

Execute any sql operations using queryRunner. USE ONLY this queryRunner to execute queries, don't use entity managers, repositories because they are running queries on their own query runners. In the case you want to use managers/repositories you need to create them using this api:

```ts
const entityManager = connection.createIsolatedManager(yourQueryRunner);
```

or 

```ts
const entityRepository = connection.createIsolatedRepository(Entity, yourQueryRunner);
```

**Comment by yonilerner** [comment]
Great, thank you!

**Comment by EVINK** [comment]
@pleerock

Hi, there! I am using UPDATE SQL in queryRunner.query API, and I do not commit it, but it has changed data to db later.

Here is my code

```ts
// A request is coming, since I do not commit it , so the data in db not changes after responded
// but it is changed while an another request arrived (this new request had calling "startTransaction() ")
const queryRunner = getConnection().createQueryRunner()
try{
    await queryRunner.startTransaction() 
    await queryRunner.connect()
    await queryRunner.query('UPDATE ...')
}catch(err){
    return next(err)
}finally{
    this.queryRunner.release()
}

```
How I gonna do if I want to ensure the data not changed?
