### ISSUE TITLE
Provider #ConnectionManager not provided in #Module

### ISSUE THREAD

**Issue by Cassianokunsch** [typeorm/typeorm#5390]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

![image](https://user-images.githubusercontent.com/9349768/72805467-b4a50880-3c31-11ea-92f9-1d1551a92650.png)

![image](https://user-images.githubusercontent.com/9349768/72805509-cdadb980-3c31-11ea-8b6b-a0b483580591.png)

![image](https://user-images.githubusercontent.com/9349768/72805525-dd2d0280-3c31-11ea-82c8-7d73fcf197ce.png)

![image](https://user-images.githubusercontent.com/9349768/72805537-e7e79780-3c31-11ea-934a-770a62a41ccc.png)

![image](https://user-images.githubusercontent.com/9349768/72805553-f2099600-3c31-11ea-8ed0-1977aaeb82c9.png)

![image](https://user-images.githubusercontent.com/9349768/72805573-fd5cc180-3c31-11ea-9c73-f6d0944c89b3.png)

![image](https://user-images.githubusercontent.com/9349768/72805692-3bf27c00-3c32-11ea-8e1e-f7792c1f3a4a.png)

I have this problem and I can't solve it.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
