### ISSUE TITLE
[BUG] postgresql unmatched constant key constraint id in embedded entity

### ISSUE THREAD

**Issue by lirannh** [typeorm/typeorm#5396]
**Issue type:**

[ ] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:*
   

[ ] `latest`
[ ] `@next`
[X ] `0.x.x` (^0.2.22)

**Steps to reproduce or a small repository showing the problem:**

i have three entities : 

**Invoice Entity** : 

`
@Entity('invoice')
export class InvoiceEntity
{
 @PrimaryGeneratedColumn('uuid')
  _id: string;

 @OneToMany(type => ItemEntity, (item: ItemEntity) => item.invoiceOwner)
  items: ItemEntity[];

  @Column(type=> PriceEntity)
  totalValueOfGoodsForeignCurrency: PriceEntity;

}

**Price Entity** 

export class PriceEntity   {

  @PrimaryGeneratedColumn('uuid')
  _id: string;

@Column({ type: 'numeric', default: -1 })
  value: number;
}

**Item Entity :** 

@Entity('item')
export class ItemEntity implements ItemModel {
  @PrimaryGeneratedColumn('uuid')
  _id: string;

 @ManyToOne(type => InvoiceEntity, (invoice: InvoiceEntity) => invoice.items, { onDelete: 
   'CASCADE' })
  invoiceOwner: InvoiceEntity;

 @Column({ default: '' })
  description: string;

}

`

When I try to POST invoice, Then a new invoice created with embedded entity as expected.
But, when i try to POST item, I get exception 500 with the following server error : 
QueryFailedError: insert or update on table "item" violates foreign key constraint "FK_37bf364f26463f19bcf764f0952"

So I've checked the database : 

![image](https://user-images.githubusercontent.com/51078686/72913991-a694dc00-3d46-11ea-80c5-02c9cce073bb.png)

As you can see above, There is a wrong connection between the ids. 

Thank you, And i hope you can solve my issue .

**Comment by Cali93** [comment]
@lirannh As specified in the docs https://github.com/typeorm/typeorm/blob/master/docs/many-to-one-one-to-many-relations.md

> You can omit @JoinColumn in a @ManyToOne / @OneToMany relation. @OneToMany cannot exist without @ManyToOne. If you want to use @OneToMany, @ManyToOne is required. However, the inverse is not required: If you only care about the @ManyToOne relationship, you can define it without having @OneToMany on the related entity. Where you set @ManyToOne - its related entity will have "relation id" and foreign key.

**Comment by lirannh** [comment]
> @lirannh
> 
> > You can omit @JoinColumn in a @manytoone / @OneToMany relation. @OneToMany cannot exist without @manytoone. If you want to use @OneToMany, @manytoone is required. However, the inverse is not required: If you only care about the @manytoone relationship, you can define it without having @OneToMany on the related entity. Where you set @manytoone - its related entity will have "relation id" and foreign key.
> 
> As specified in the docs: https://github.com/typeorm/typeorm/blob/master/docs/many-to-one-one-to-many-relations.md. As this is not a bug, can you please close the issue ? Thanks in advance.

Hey, Cali,thank you for reply my issue. 
I saw the docs, my @oneToMany and many to one works fine, when I remove the embedd entity totalValueOfGoodsForeignCurrency, every things works, But I need to that entity also and with her I got execption.

**Comment by Cali93** [comment]
@lirannh You're welcome. You are referencing the field totalValueOfGoodsForeignCurrency as a relation to the PriceEntity but you're not specifying any relation decorator on any side. To me it is not a bug but more a miss understing/miss use.
