### ISSUE TITLE
Cascade remove option not working

### ISSUE THREAD

**Issue by AdriVig** [typeorm/typeorm#54]
Hi,

I'm trying to remove rows using cascade option but it's not working.
I'm using insert and update cascade options and it's working well.

Here is my model :
`
@OneToMany(type => TemplateAnswer, templateAnswer => templateAnswer.block, {
        cascadeInsert: true,
        cascadeUpdate: true,
        cascadeRemove: true
    })
  templateAnswers: TemplateAnswer[] = [];
`

And my controller :
`
    @Delete('/:id')
    deleteOne(@Req() request, @Res() response, @Param('id') id) {
      var entityManager;
      return DatabaseManager.getInstance().getConnection()
      .then(connection => {
        entityManager = connection.entityManager;
        return entityManager.findOneById(Block, id);
      })
      .then(block => {
        return entityManager.remove(block);
      })
      .catch((error: HttpError) => {
        response.status(error.code).send({message: error.message});
      })
      .catch(error => {
        response.status(500).send({message: "Internal error"});
      })
    }
`

AdriVig

**Comment by pleerock** [comment]
Looks like a bug, please use manual remove (using repository#remove or entityManager#remove) until I fix this issue

**Comment by pleerock** [comment]
this issue should be fixed in `npm i typeorm@next` version. Please try again with it, and if it still will not work, please let me know, we'll go deeper with your concrete example.
