### ISSUE TITLE
Converting database to typeorm entities (Reverse engineering)

### ISSUE THREAD

**Issue by Deilan** [typeorm/typeorm#540]
Any plans or thoughts about implementing reverse engineering in `typeorm` (converting a database to `typeorm` entities)?

**Comment by pleerock** [comment]
we can implement basic functionality for this, however it seems to me to be more a toy then a real tool. But maybe Im a wrong and we can create a tool that will be used by users.

We probably can generate entity names from table names, and columns with column names and column types.... It will be hard to generate indices, but maybe possible. It probably will be impossible to generate proper relations and foreign keys.

**Comment by kmsquire** [comment]
For reference: https://github.com/SweetIQ/schemats

**Comment by miltonhowe** [comment]
There is another project I am looking at which might do some of what you are looking for:

[typeorm-model-generator](https://github.com/Kononnable/typeorm-model-generator)

**Comment by chriszrc** [comment]
re: [typeorm-model-generator](https://github.com/Kononnable/typeorm-model-generator)

I just tried that out and it's really a great first start at database reverse engineering. I hope this feature get's serious consideration (or links to the other project, something), because for many of us, we're not starting projects with blank databases. Being able to reverse engineer the entities is a real time saver, and for large databases with dozens of entities, this is a real life saver

**Comment by NoNameProvided** [comment]
@pleerock have you considered merging that project into TypeORM  (or at least transferring it under the TypeORM organization)  if @Kononnable agrees? I think thats a good functionality to have.

**Comment by pleerock** [comment]
Yes its very welcomed in the case if @Kononnable can bring his codebase under typeorm standards and he'll have a time to maintain this functionality then

**Comment by Kononnable** [comment]
Sorry for the delay. I was really busy lately(getting master's degree).

I would be very happy to bring [typeorm-model-generator](https://github.com/Kononnable/typeorm-model-generator) under [typeorm](https://github.com/typeorm/typeorm). I should have enough time to maintain this functionality. I'm not planning to abandon it any time soon :)

I think it would be better to transfer repo under [typeorm](https://github.com/typeorm) organization and not integrate directly in [typeorm](https://github.com/typeorm/typeorm) repo. Creating ORM models isn't needed in production version of apps, so it shouldn't be shipped with them. I'm not up-to-date on [typeorm](https://github.com/typeorm/typeorm) road map, but If I remember correctly there were plans to divide code under separate packages(so there is no point in merging it just for few months). 
However it may bring some versioning misunderstandings([typeorm-model-generator](https://github.com/Kononnable/typeorm-model-generator) have higher version number than [typeorm](https://github.com/typeorm/typeorm), so there is no way to use same version numbers if we don't want [typeorm](https://github.com/typeorm/typeorm) to miss some version numbers), but I don't see any good way to change it(unless [typeorm](https://github.com/typeorm/typeorm) API is declared as stable and becomes 1.0.0).

**Comment by pleerock** [comment]
>  If I remember correctly there were plans to divide code under separate packages(so there is no point in merging it just for few months).

yes but we decided not to do it in the near future.

**Comment by pleerock** [comment]
If you think there is no need to merge code into typeorm repository, then Im not sure what are benefits of adding this repository into typeorm ogranization. If you think its better then we can do it, or alternatively we can add a link in the homepage (extensions section) link to repository in your profile. Decide yourself.

**Comment by Kononnable** [comment]
There are few good reasons to keep production-ready code and developer tools separate, so I think its best not to migrate this into one big repository.
The main point(for me) in going under typeorm organization was people awareness that such reverse engineering tool exists. However now if I think about it this issue and link in extension section should be enough to point in right direction if someone is looking for reverse engineering tool. And it doesn't make typeorm-model-generator 'official', so there is a better chance someone will make another reverse engineering tool for typeorm by taking different approach(more the merrier).

**Comment by pleerock** [comment]
Good points. Feel free to create a PR with links to your repository. Once TypeORM will have stronger community and extensions we'll create a separate page on site with all available plugins and extensions.

**Comment by pleerock** [comment]
I'll close this issue since we can use awesome typeorm-model-generator module thanks to @Kononnable

**Comment by aayani** [comment]
> I'll close this issue since we can use awesome typeorm-model-generator module thanks to @Kononnable

Any luck with that? It's been more than 4 years already. :smile:

**Comment by Maydmor** [comment]
For those still looking for an alternative

You can also use an online tool like

[Evernox](https://evernox.com)

It has tools to directly generate code in multiple languages from your database.

It's really easy :

- Create a new diagram

- Click on "Connect Database" and sync Evernox with your Database

- Click on "Generate code" and select Type ORM from the list
