### ISSUE TITLE
Entities from `.save()` getter issue

### ISSUE THREAD

**Issue by reggi** [typeorm/typeorm#5401]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have a entity like this, it has a "getter".

```ts
@ObjectType()
@Entity()
export class User extends BaseEntity {

  @Field(() => String, { nullable: true })
  @Column({ type: PostgresColumn.VARCHAR, nullable: true })
  stripeCustomerId: NullableColumn<string>

  get requireStripeCustomerId(): ReadOnlyColumn<string> {
    if (this.stripeCustomerId !== null) return this.stripeCustomerId
    throw new Error('user is missing stripeCustomerId')
  }

}
```

For some reason entities returned with `findOne` have the getter working, but entities returned with `save` do not.

How can I fix this?

**Comment by imnotjames** [comment]
The values returned from `save` aren't entities.  They're what was persisted to the database and are mostly an artifact of how TypeORM works internally.
