### ISSUE TITLE
how to use $lookup with mongodb

### ISSUE THREAD

**Issue by Binaryify** [typeorm/typeorm#5403]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

how to use $lookup with mongodb
```
 const mongoManger = getMongoManager()
   
    const result = await mongoManger.aggregate(User, [
      {
        $lookup: {
          from: 'jobs',
          localField: 'openid',
          foreignField: 'openid',
          as: 'jobs',
        }
      }
    ])
```
can't get the normal result

in normal mongodb cli, i can use 
```
db.user.aggregate({
    $lookup:{
         from: 'jobs',
            localField: 'openid',
            foreignField: 'openid',
            as: 'jobs',
    }
})
```

somebody helps?

**Comment by rustamwin** [comment]
Try this
```javascript
    const mongoManger = getMongoManager()
   
    const result = await mongoManger.aggregate(User, {
        $lookup: {
          from: 'jobs',
          localField: 'openid',
          foreignField: 'openid',
          as: 'jobs',
        }
      })
```

**Comment by Binaryify** [comment]
@rustamwin 
that's didn't work

![image](https://user-images.githubusercontent.com/12221718/72982245-9b5eb080-3e19-11ea-997d-37ccd7ba4890.png)

**Comment by rhutchison** [comment]
@Binaryify if you didn't figure it out or for those that stumble upon this issue, ObjectLiteral is an array.

```
    const mongoManger = getMongoManager()
   
    const result = await mongoManger.aggregate(User, [{
        $lookup: {
          from: 'jobs',
          localField: 'openid',
          foreignField: 'openid',
          as: 'jobs',
        }
      }])
```

**Comment by Binaryify** [comment]
@rhutchison thank for the help~

**Comment by ragil000** [comment]
> @Binaryify if you didn't figure it out or for those that stumble upon this issue, ObjectLiteral is an array.
> 
> ```
>     const mongoManger = getMongoManager()
>    
>     const result = await mongoManger.aggregate(User, [{
>         $lookup: {
>           from: 'jobs',
>           localField: 'openid',
>           foreignField: 'openid',
>           as: 'jobs',
>         }
>       }])
> ```

I am using multiple connections, and getting the error message "Connection \"mongo\" was not found.".
