### ISSUE TITLE
sid and serviceName for oracledb config are mixed up

### ISSUE THREAD

**Issue by Rainson12** [typeorm/typeorm#5408]
**Issue type:**

[ ] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When actually setting the connection the property sid is actually the serviceName. 

The following code
```
@Module({
  imports: [
    TypeOrmModule.forRoot({
      name: "oracle",
      type: 'oracle',
      host: '127.0.0.1',
      port: 49161,
      username: 'indivunet',
      password: 'oracle',
      database: 'indivunet',
      entities: [],
      synchronize: true,
      sid: "CWDB01",
      logging: false,
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule { }
```

results in:
Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

while the same config in the offical Oracle SQL Developer is successfull:
![01](https://user-images.githubusercontent.com/13119203/72980982-f83b7600-3ddb-11ea-965d-ffe5421fd610.png)
When now using the serviceName as the "sid" property value:
`sid: "CWDB01.td.clckwrk.com",`

the connection can be established. However this is the serviceName and not the SID. See Oracle SQL Developer screenshots as proof: 
![02](https://user-images.githubusercontent.com/13119203/72980983-f83b7600-3ddb-11ea-8523-726b30f0d166.png)
![03](https://user-images.githubusercontent.com/13119203/72980984-f83b7600-3ddb-11ea-82d3-1816f41c3c76.png)

This would mean that the sid is actually reflecting the serviceName

**Comment by Blira** [comment]
Just encountered this same problem. 
Thanks for posting! :)

**Comment by imnotjames** [comment]
Can probably use the connect descriptor?

```
(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=mymachine.example.com)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=ORCL)(SERVICE_NAME=orcl)))
```
