### ISSUE TITLE
TypeOrm with typescript in Azure functions: different query generates when built for webpack production

### ISSUE THREAD

**Issue by zafrulNaheen** [typeorm/typeorm#5412]
**Issue type:**

[x ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

TypeOrm with typescript in Azure functions: different query generates when built for webpack production
stackoverflow link:https://stackoverflow.com/questions/59884849/typeorm-with-typescript-in-azure-functions-different-query-generates-when-built

**Comment by imnotjames** [comment]
Try disabling the terser plugin - the optimizations that does can cause some issues.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
