### ISSUE TITLE
[Feature Request] Enable github stale bot

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#5422]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

@pleerock  I recommend that we enable [Github's free stale bot](https://github.com/marketplace/stale) to automatically close issues that have been inactive for X (configurable) days. 

Why? 1300+ issues is not easily manageable and confuses the priorities for the project. The bot will automatically re-open issues once there is activity. 

So nothing is lost. But clarity is gain.

**Comment by imnotjames** [comment]
We're up to 1700 now.  I've gotten that down from 2200.  While we may eventually enable that, for now we are going to hold off.

Thanks for the suggestion, though!
