### ISSUE TITLE
Configure the from part of a query

### ISSUE THREAD

**Issue by Nivelium** [typeorm/typeorm#5433]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hello!

I need a suggestion for the next problem:

I have an entitiy. But actually there are 2 tables for it.
I use PG table inheritance feature for that.
And of them is the child of another.
The parent table contains all the entities.
The child table contains all the previous versions of the entities, and it has one more column "status".
For example i have tables:
```MY_TABLE``` - is the parent.
```MY_TABLE_HISTORY``` - is the table containing history records.
When i need to query only actual records i would like to do something like:
```
SELECT *
FROM ONLY MY_TABLE
WHERE ID = 🆔 
```
When i need to get all historical data of a record i would like to do something like(i don't need to query MY_TABLE_HISTORY, it will be queried by pg automatically):
```
SELECT *
FROM MY_TABLE
WHERE ID = 🆔 
```

So sometimes i need to inject word ```ONLY``` between ```FROM MY_TABLE```.
It also matters for ```save``` method, because if i update it, i should use ```update only my_table```, otherwise it will update all records.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
