### ISSUE TITLE
getRawMany() and getMany() inconsistent results

### ISSUE THREAD

**Issue by mszubiczuk** [typeorm/typeorm#5436]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.2.22` (or put your version here)

Hello,
having following Entity declared 
```
@Entity('test')
export default class Test {
  @PrimaryGeneratedColumn({
    name: 'id',
  })
  id: number;

  @Column({
    unique: true,
  })
  @IsNotEmpty()
  @Length(1, 16)
  name: string;

  @Column()
  isTest: boolean;

  @Column()
  @CreateDateColumn()
  createdAt: Date;

  @Column()
  @UpdateDateColumn()
  updatedAt: Date;
}
```

I try to get for example a list of results with an additional column (eg. ```count```)
using a query like: 

```
await getRepository(Test)
        .createQueryBuilder('test')
        .select([
          'test.id',
          'test.name',
        ])
        .addSelect('COUNT(test.id)', 'count')
        .groupBy('test.id')
        .getMany();
```
the same example with ```.getRawMany()``` produces the same SQL:

```
SELECT "test"."id" AS "test_id", "test"."name" AS "test_name", COUNT("test"."id") AS "count" FROM "test" "test" GROUP BY "test"."id"
```

With ```getMany()```  I agree that `count` column is not returned, but with `getRawMany()` I'd expect an output like this:

1. 
```
[
    {
      "id": 2,
      "name": "name2",
      "count": "1"
    },
    {
      "id": 1,
      "name": "name1",
      "count": "1"
    }
  ]
```

but I get 

2. 
```
[
    {
      "test_id": 2,
      "test_name": "name2",
      "count": "1"
    },
    {
      "test_id": 1,
      "test_name": "name1",
      "count": "1"
    }
  ]
``` 
instead. 
Is this a correct behaviour that every Entity's column is prefixed with an alias? According to TypeOrm documentation the 1. should be returned and this is what I want to get.
I can walk around this overwriting each alias manually with separate `.addSelect('test.id', 'id')` and so on, but this doesn't seem to be scaling well. #

**Comment by jinusean** [comment]
Have you tried `.createQueryBuilder()` without an alias?

**Comment by imnotjames** [comment]
This is intentional because every select field must have a unique alias to be returned.  If you want to customize it, yes, you need to individually add them with aliases.

You can preview the query with `getQuery` to understand how this is happening
