### ISSUE TITLE
Group by missing in  find options of typeorm crud service

### ISSUE THREAD

**Issue by sandeshgb** [typeorm/typeorm#5437]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.21` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Typeorm findOne is missing group by clause. Even if I'm using a normal find() the group by isn't present.
I just want to execute a simple query using group by clause.

[FindOneOptions.txt](https://github.com/typeorm/typeorm/files/4133504/FindOneOptions.txt)

**Comment by sahilkumar129** [comment]
Is this feature planned to be released in the future yet?

**Comment by imnotjames** [comment]
`groupBy` doesn't make sense in `.find()` because then it won't map back up to the entity - it would be an aggregate instead.

You'll need to use the query builder.
