### ISSUE TITLE
TableForeignKey is missing table schema

### ISSUE THREAD

**Issue by LorenzHenk** [typeorm/typeorm#5439]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.20` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```sql
CREATE SCHEMA test;
SET search_path TO test;

CREATE TABLE t_item (
	id serial PRIMARY KEY,
	item_name text NOT NULL UNIQUE
);

CREATE TABLE t_cart (
	id serial PRIMARY KEY,
	item_id int NOT NULL REFERENCES t_item
);
```

```ts
const queryRunner = getConnection().createQueryRunner();

const table = await queryRunner
    .getTable(`test.t_cart`);

const foreignKey = table.foreignKeys[0]
```

This returns the following object:

```
TableForeignKey {
  columnNames: [ 'item_id' ],
  referencedColumnNames: [ 'id' ],
  name: 't_cart_item_id_fkey',
  referencedTableName: 't_item',
  onDelete: 'NO ACTION',
  onUpdate: 'NO ACTION',
  deferrable: undefined
}
```

If I want to get more information on the referenced table, I can't do 

```ts
const referencedTable = await queryRunner
    .getTable(`t_item`); // this will fail
```

because the schema is missing.

### Solution

Either set `referencedTableName` to `test.t_item` or add another column `referencedTableSchema` or something alike.

**Comment by imnotjames** [comment]
This should be fixed in the next release.  This can be confirmed in the latest dev build - `0.2.38-dev.22676a0`
