### ISSUE TITLE
groupBy() and getCount() cannot be used at the same time

### ISSUE THREAD

**Issue by bobmayuze** [typeorm/typeorm#544]
During my development, I found there is literally no way to count the number of kinds of data in a query with Typeorm. The getCount wiil return the fist value of groupBy(). For example, if we have 9 fruits in the db, 4 apples, 3 bananas, and 2 cherries. The getCount after groupBy will return us 4 coz we have 4 apples. Any idea?

**Comment by pleerock** [comment]
`getCount` of `QueryBuilder` is for pagination purposes. For example if you have 1000 bananas, but your query to load bananas uses `skip`/`take` for pagination purposes which returns you only 20 bananas, you need to get know how many bananas do you have overall to create correct number of pages. Thats what `getCount` stays for. For your purposes you probably need to use regular SQL COUNT() in your queries and get raw results.

**Comment by pleerock** [comment]
Did I answer your question?

**Comment by bobmayuze** [comment]
Thanks for answering the question, but I wonder if I can do so with typeorm.

**Comment by pleerock** [comment]
> For your purposes you probably need to use regular SQL COUNT() in your queries and get raw results.

yeah you simply do something line `const results = await queryBuilder.select("COUNT(post.id) AS cnt").getRawMany()`

**Comment by bobmayuze** [comment]
Thanks for the help! Really appreciate for that

**Comment by wodka** [comment]
I created a helper for myself to do the same thing:

```typescript
import { SelectQueryBuilder } from 'typeorm'

export class CoreQbHelper {
  public static async getRawManyAndCount<T>(qb: SelectQueryBuilder<any>, groupColumns: string[]): Promise<[number, T[]]> {
    return Promise.all([
      new Promise<number>((resolve, reject) => {
        const cQb = qb.clone()
        cQb.skip(0)
        cQb.select(`COUNT(DISTINCT (${groupColumns.join(', ')})) as c`)
        cQb.orderBy(null)
        cQb.getRawOne()
          .then(value => resolve(value.c ? Number(value.c) : 0))
          .catch(e => reject(e))
      }),
      new Promise<T[]>((resolve, reject) => {
        const vQb = qb.clone()
        vQb.groupBy(groupColumns.join(', '))
        vQb.getRawMany()
          .then(values => resolve(values))
          .catch(e => reject(e))
      }),
    ])
  }
}
```

And to use it pass the columns you are grouping to it as well like `CoreQbHelper.getRawManyAndCount(qb, ['b.type'])`

**Comment by Logic-Bits** [comment]
> I created a helper for myself to do the same thing:
> 
> ```ts
> import { SelectQueryBuilder } from 'typeorm'
> 
> export class CoreQbHelper {
>   public static async getRawManyAndCount<T>(qb: SelectQueryBuilder<any>, groupColumns: string[]): Promise<[number, T[]]> {
>     return Promise.all([
>       new Promise<number>((resolve, reject) => {
>         const cQb = qb.clone()
>         cQb.skip(0)
>         cQb.select(`COUNT(DISTINCT (${groupColumns.join(', ')})) as c`)
>         cQb.orderBy(null)
>         cQb.getRawOne()
>           .then(value => resolve(value.c ? Number(value.c) : 0))
>           .catch(e => reject(e))
>       }),
>       new Promise<T[]>((resolve, reject) => {
>         const vQb = qb.clone()
>         vQb.groupBy(groupColumns.join(', '))
>         vQb.getRawMany()
>           .then(values => resolve(values))
>           .catch(e => reject(e))
>       }),
>     ])
>   }
> }
> ```
> 
> And to use it pass the columns you are grouping to it as well like `CoreQbHelper.getRawManyAndCount(qb, ['b.type'])`

Thanks!

I just flipped number and T[] so its works just like the getManyAndCount()

**Comment by choninoa** [comment]
count = await (await qb.getRawMany()).length

**Comment by ernestdolog** [comment]
> count = await (await qb.getRawMany()).length

unless You are paginating, and set a `first` and/or an `after`
