### ISSUE TITLE
An honest question

### ISSUE THREAD

**Issue by PQMISSCMP** [typeorm/typeorm#5441]
[x] question

Why have you created an application and then forget to help those who use it?
I ask with good intention ... I see many problems published here but it seems a discontinued application. 

A shame

**Comment by msheakoski** [comment]
@PQMISSCMP read #3267

**Comment by duckies** [comment]
This is best left in #3267, but unfortunately it's been a year since that thread was created with no major update to it. It would not be unfair to say it's currently in triage, with a staggering amount of the updates being triage PRs from contributors, and support for SAP Hana. I enjoy TypeORM, but there's no roadmap or communication about next steps, so supporting it is difficult.

**Comment by PQMISSCMP** [comment]
I have the impression that the creation of this library was motivated for profit purposes instead of contributing to the community.

**Comment by msheakoski** [comment]
> I have the impression that the creation of this library was motivated for profit purposes instead of contributing to the community.

@PQMISSCMP That is quite insulting to creators and contributors of open source software. You should be more thankful to the people who put in their time and money to create things that you benefit from. You did not have to pay a single cent to use TypeORM. It is entirely your choice if you only want to take, or to give back financially or by **"contributing to the community"**.

**Comment by PQMISSCMP** [comment]
I'm sorry, but it is my impression, I am probably wrong but I have reason to think so. However, I think that despite everything, typeorm is a magnificent tool and the creators were generous in developing it

**Comment by PQMISSCMP** [comment]
> > Tengo la impresión de que la creación de esta biblioteca fue motivada con fines de lucro en lugar de contribuir a la comunidad.
> 
> @PQMISSCMP Eso es bastante insultante para los creadores y contribuyentes de software de código abierto. Deberías estar más agradecido con las personas que invierten su tiempo y dinero para crear cosas de las que te beneficias. No tuvo que pagar un solo centavo para usar TypeORM. Es completamente su elección si solo quiere tomar, o devolver financieramente o **"contribuyendo a la comunidad"** .

I'm sorry, but it is my impression, I am probably wrong but I have reason to think so. However, I think that despite everything, typeorm is a magnificent tool and the creators were generous in developing it

**Comment by PQMISSCMP** [comment]
> > I have the impression that the creation of this library was motivated for profit purposes instead of contributing to the community.
> 
> @PQMISSCMP That is quite insulting to creators and contributors of open source software. You should be more thankful to the people who put in their time and money to create things that you benefit from. You did not have to pay a single cent to use TypeORM. It is entirely your choice if you only want to take, or to give back financially or by **"contributing to the community"**.

I'm sorry, but it is my impression, I am probably wrong but I have reason to think so. However, I think that despite everything, typeorm is a magnificent tool and the creators were generous in developing it
