### ISSUE TITLE
Webpack and circular imports with entities relations

### ISSUE THREAD

**Issue by arxhqd** [typeorm/typeorm#5448]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hello. I am using webpack as buildtool. So i started describing entities but got circular dependency error obviously it happend because of relations between entities. Is there anyway to use typeorm with webpack without getting circular deps errors? I was thinking about describing schemas separatly, but it will not help either, also i like to describe entities using decorators.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
