### ISSUE TITLE
How to Set a default value as  CURRENT_TIMESTAMP using migration API

### ISSUE THREAD

**Issue by renjithspace** [typeorm/typeorm#5452]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
async up (queryRunner: QueryRunner) {
    await queryRunner.createTable(new Table({
      name: 'user',
      columns: [
        { name: 'name', type: 'varchar' },
        { name: 'createdAt', type: 'timestamp', default: CURRENT_TIMESTAMP }, // How to set default value as MySQL CURRENT_TIMESTAMP here?
      ]
    }), true)
  }
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by jhoch** [comment]
For Postgres, I was able to do the following:

```typescript
public async up(queryRunner: QueryRunner): Promise<void> {
  await queryRunner.createTable(new Table({
    name: "table",
    columns: [{
      name: "created_at",
      type: "timestamp with time zone",
      default: "timezone('utc'::text, now())",
    }],
  }));
}
```

where `"timezone('utc'::text, now())"` is a string I found by querying an existing known-good column.

Curious if (1) anyone knows a cleaner way to do this using TypeORM, and (2) if this helps you with the MySQL/MariaDB case.

**Comment by imnotjames** [comment]
Looks like this was answerd.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
