### ISSUE TITLE
Multiple where generates invalid parameters.

### ISSUE THREAD

**Issue by waveiron** [typeorm/typeorm#5455]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ `0.2.22` ] `0.x.x` (or put your version here)

Say, we have a simple user entity with a json field:

```typescript
@Entity()
export class User extends BaseEntity {
	@PrimaryGeneratedColumn()
	id: number

	@Column({ type: 'json' })
	data?: any
}
```

Create some test data:

```typescript
// Clear user table before every test.
await User.clear()

// Insert test data.
await User.insert([
	{ data: { value: 1 } },
	{ data: { value: 2 } },
	{ data: { value: 3 } },
])
```

Run a multiple where query:

```typescript
const list = await User.createQueryBuilder()
	// This part could be dynamically generated by iterating
	.orWhere('data -> "$.value" = :value', { value: 1 })
	.orWhere('data -> "$.value" = :value', { value: 2 })
	.getMany()

console.log(list)
```

Result:

```typescript
[ { id: 2, data: { value: 2 } } ] // It should be: [  { id: 1 data: { value: 1 } }, { id: 2, data: { value: 2 } } ]
````

SQL generated:

```sql
SELECT `User`.`id` AS `User_id`, `User`.`data` AS `User_data` 
  FROM `user` `User` WHERE data -> "$.value" = ? OR data -> "$.value" = ? 
-- PARAMETERS: [2,2] (It should be: [1, 2])
```

**Comment by imnotjames** [comment]
This is in the documentation - you can't have overlapping names of parameters in your where clauses at this time.
