### ISSUE TITLE
Yugabyte Support

### ISSUE THREAD

**Issue by simisoz** [typeorm/typeorm#5459]
Can we use the current Postgres setup to connect to Yugabyte?

**Comment by likern** [comment]
@simisoz Have you succeeded in using TypeORM for YugaByte? I think it should work if using PostgreSQL driver since they use PostgreSQL query layer

**Comment by marcus-sa** [comment]
It should work out of the box, atleast that's what it does with Prisma.
You just have to set the `default_transaction_isolation` option to `serializable` in `ysql_pg_conf`

Reference https://docs.yugabyte.com/latest/develop/graphql/prisma/

I'm just curious whether or not TypeORM supports YSQL distributed transactions.

**Comment by imnotjames** [comment]
TypeORM does not officially support any features by Yugabyte, but please try it and see!

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
