### ISSUE TITLE
EntityMetadaNotFound

### ISSUE THREAD

**Issue by hmarcelodn** [typeorm/typeorm#546]
I have created an entity like below and i am not being able to retrieve its repository because of the following error:

> (node:10712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): EntityMetadataNotFound: No metadata
> for "Technology" was found.

```
@Entity('Technology')
 export class Technology extends BaseEntity{

     constructor(){
         super();
     }
 
     @Column({
         name: 'Name'
     })
     name: string;
 
 }
```

It fails when:

`let repo = conn.getRepository(Technology);`

It works when (using string instead):

`let repo = conn.getRepository('Technology');`

Can someone provide some guidance?

**Comment by pleerock** [comment]
thats strange, are you sure you are using correct instance of `Technology` ? Do you have table created for a `Technology` entity?

**Comment by hmarcelodn** [comment]
Yes as soon as I connect to the database it creates the table. I have any other table around named Technology.

**Comment by NoNameProvided** [comment]
You are importing it from a different location, see @tomkroening and my answer for details: 
https://github.com/typeorm/typeorm/issues/420#issuecomment-307219380

**Comment by hmarcelodn** [comment]
I was wrong in one character. Thanks a lot!
