### ISSUE TITLE
help connect  with Sap hanna

### ISSUE THREAD

**Issue by Eduardo555** [typeorm/typeorm#5465]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `Sap Hana`
**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hey everyone, i need help, for connect with sap hana. when i created project and using cli.

`typeorm init --name nome --database saphana`

the configurations of databases stayed in withe empty. 
how should I proceed?

**Comment by zamarrong** [comment]
Hi i have the same issue how you proceed? Find any fix?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by luizcarlospedrosogomes** [comment]
news?

**Comment by P3dream** [comment]
news?

**Comment by alumni** [comment]
@P3dream news about what?

You can read the [installation](https://typeorm.io/#installation) docs if you want to setup HANA. You just need to add the peer dependencies `@sap/hana-client` and `hdb-pool` and setup a `DataSource` with `type: 'sap'`.
