### ISSUE TITLE
Question: How to continue  to next value ( aport ) if there a duplications error 

### ISSUE THREAD

**Issue by heshaShawky** [typeorm/typeorm#5470]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I'm scraping from multiple websites and I save the data on MySQL type database using nestJS and TypeOrm frameworks. 

I have a cron job that runs that scraper service every day checking for new data available and inserted into my SQL database, the problem I don't wanna duplication data so I did a unique column in my table, so any duplicated data not getting be saved.

Now I got the `dup error` as I expected but I can't find a way to handle this error to just ignore that row and continue for the rest instead of stopping everything.

The code for saving the data: 
```typescriprt
async clonningFromScraper() {
   //my scraper data ( array of objects )
    let articles = await this.articlesScraper.articles('1'); 

    articles = articles.map( article => ({ ...article, key: decodeURIComponent(article.url).substring(0, 255) }));

 // saving the data into my database
    return this.articleRepository
        .save(articles);
}
```

**Comment by aatecey** [comment]
Don't think save has an option to handle this. Could use the query builder for this case though. Not tested this but something like:

        await this.articleRepository.createQueryBuilder()
            .insert()
            .orIgnore()
            .into(Article)
            .values(articles)
            .execute();

**Comment by heshaShawky** [comment]
> Don't think save has an option to handle this. Could use the query builder for this case though. Not tested this but something like:
> 
> ```
>     await this.articleRepository.createQueryBuilder()
>         .insert()
>         .orIgnore()
>         .into(Article)
>         .values(articles)
>         .execute();
> ```
the `save` method supposed to do that as it's documented 
```
 /**
     * Saves all given entities in the database.
     * If entities do not exist in the database then inserts, otherwise updates.
     */
```
Your code works well for me, thanks.
