### ISSUE TITLE
Issue with ionic 4 

### ISSUE THREAD

**Issue by omkar1707** [typeorm/typeorm#5473]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.20` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am able to use **sql-asm.js** with typeorm in ionic 4. It is working fine.
But if I changed to **sql-wasm.js** then it is not working.

webpack.config.js
```
const webpack = require('webpack');

module.exports = {
    plugins: [
        new webpack.ProvidePlugin({
            'window.SQL': 'sql.js/dist/sql-wasm.js'
        }),
        new webpack.NormalModuleReplacementPlugin(/typeorm$/, function (result) {
            result.request = result.request.replace(/typeorm/, "typeorm/browser");
        })
    ],
    node: {
        fs: 'empty',
        net: 'empty',
        tls: 'empty'
    },
    optimization: {
        minimize: false
    }
};

```
Error 
<img width="1440" alt="Screenshot 2020-02-05 at 8 44 58 AM" src="https://user-images.githubusercontent.com/26362645/73807968-4432e580-47f4-11ea-9b96-91d7dad5df47.png">

**Comment by imnotjames** [comment]
This is an issue outside of TypeORM.  TypeORM does not load sqljs, you do.  The only thing TypeORM does is look to see if TypeORM is at `window.SQL` - doesn't load it.
