### ISSUE TITLE
Setting enumName doesn't change how migrations get generated

### ISSUE THREAD

**Issue by osdiab** [typeorm/typeorm#5478]
I want to share enum names with the same values across several tables, but after making the changes `generateMigrations` doesn't actually change anything. `enumNames` ought to also be reflected in migration generation

### Original comment in enumName PR

@ejose19 - am i'm right in thinking this won't affect the migrations generated? It appears they're still being prefixed with table names and ignoring the new `enumName`..

I can take a crack at a PR if i can get a few pointers..

_Originally posted by @elmpp in https://github.com/typeorm/typeorm/pull/4824#issuecomment-545484163_

**Comment by osdiab** [comment]
an attempt at #5479 to try to see if that would fix it (after looking through the code I believe the names should be right but the migration generation code just isn't detecting the change, which gets called by each of the appropriate `SchemaBuilder.log()` -> `RdbmsSchemaBuilder.updateExistColumns()` -> `driver.findChangedColumns()` calls i believe.

**Comment by osdiab** [comment]
in `PostgresDriver`, `createEnumTypeSql()` is called in `addColumn()`, `createTable()`, `changeColumns()`, and `dropColumn()` - i think `createTable()`, `addColumn()` and `dropColumn()` should all be fine because the `createEnumTypeSql()` method already produces the correct names, so I guess `changeColumns()` needs to be called, which is in the `RdbmsSchemaBuilder.updateExistColumns()` method - so I think what I did might be on the right track then. Need to figure out how to try it out now

**Comment by ejose19** [comment]
Yes you're correct. When I implemented the patch I just did the core for active operations, not the migrations. As I suggested in that thread, find the files related to migrations and make your way from here.

**Comment by golergka** [comment]
Using the same enum across multiple tables currently breaks migration generation, so any help with this would be greatly apprecaited.

**Comment by osdiab** [comment]
@golergka when i get the chance i'll try to finish up that PR! hopefully later this week

**Comment by golergka** [comment]
@osdiab tell me if I can be of help! I use TypeORM pretty extensively, but haven't do any contribution to the library itself yet, so it seems like a problem I wouldn't be able to take on my own - but if you have any easier sub-tasks I would be glad.

**Comment by osdiab** [comment]
@golergka me neither 😅 but I made one contribution before and I think the one I made is pretty close, just need to make the remaining tests pass. If you wanna give patching up my outstanding PR a go feel free and I’ll be happy to advise, but if not it’ll probably be later this week or early next for me.

**Comment by tbf-siteimprove** [comment]
What is the status of this?

I'm currently in the same situation that I would like to specify the full name of the enum independently from the table its being used in. When I change the name of the enum via a migration script, the next migration generation will generate a script, which renames it back.

**Comment by osdiab** [comment]
@tbf-siteimprove my PR has been ready for a long time but just hasn't been reviewed or merged - looks like @imnotjames is starting to actively maintain typeorm now so im crossing my fingers that it'll be merged sometime.
