### ISSUE TITLE
Can I implement below query using querybuilder/ find() method?  WITH Employee_CTE (EmployeeNumber, Title) AS (SELECT NationalIDNumber,         JobTitle  FROM   HumanResources.Employee) Please advise.

### ISSUE THREAD

**Issue by AkshayPanchal-004** [typeorm/typeorm#5484]
**Issue type:**

[ =] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Ginden** [comment]
No, you can't. https://github.com/typeorm/typeorm/issues/1116

**Comment by AkshayPanchal-004** [comment]
Is there any way that I can use to implement these functionality in typeorm?

**Comment by Ginden** [comment]
Unfortunely, you can't, unless you contribute to TypeORM itself. It probably shouldn't be too hard.

**Comment by AkshayPanchal-004** [comment]
Thank you @Ginden for your time and advice.
Will you please advice me how can I contribute to TypeORM repository. Is there any code rules which I need to follow for my contribution.

**Comment by Ginden** [comment]
@AkshayPanchal-004 This was implemented in `0.3` version.
