### ISSUE TITLE
repo.save throwing UpdateValuesMissingError: Cannot perform update query because update values are not defined

### ISSUE THREAD

**Issue by jtushman** [typeorm/typeorm#5489]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi friends I am having a weird behavior trying to call save:

Consider the following:

```typescript
  const repo = getRepository(NewAssignmentNotification)
  const notification = new NewAssignmentNotification()
  const owner = await customer.owner
  notification.recipient = owner
  notification.newCustomerAssignment = customer
  notification.account = await owner.account
  notification.createdAt = now()
  console.log(JSON.stringify(notification, null, 2));
  try{
    await repo.save(notification)
  }catch (e) {
    console.log(e)
  }
```

With that we get the exception:

```
UpdateValuesMissingError: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.
```

The Entity looks like so ...

```typescript
@InterfaceType({ description: `a timely message to display to a user of quala` })
@Entity({ orderBy: { createdAt: 'DESC' }, synchronize: true })
@TableInheritance({ column: { type: 'varchar', name: 'type' } })
export class Notification {
  @Field(() => ID)
  @PrimaryGeneratedColumn('uuid')
  id: string

  @Field()
  @Column({ nullable: false })
  type: string

  @Field(() => User)
  @ManyToOne(() => User, { lazy: true, nullable: false })
  recipient: Lazy<User>

  @Field()
  @CreateDateColumn()
  createdAt: Date

  @Field()
  @Column({ nullable: true })
  dismissedAt: Date
}
```

and 

```typescript
@ObjectType({ implements: Notification })
@ChildEntity()
export class NewAssignmentNotification extends Notification {
  @Field(() => Customer)
  @ManyToOne(() => Customer, { lazy: true })
  @JoinTable()
  newCustomerAssignment: Lazy<Customer>
}

```
-----
Might be similar to: https://github.com/typeorm/typeorm/issues/4501

**Comment by snolangps** [comment]
I could be wrong here, but you have ```  @Field()
  @Column({ nullable: false })
  type: string```, wouldn't that mean in your `const notification = new NewAssignmentNotification()` should have a `notification.type` property set before save also?

**Comment by jtushman** [comment]
I would think that my STI (Single Table Inheritance) would handle that (and it fact it does for many other of my notification types)

```
@TableInheritance({ column: { type: 'varchar', name: 'type' } })
```

**Comment by snolangps** [comment]
@jtushman but which one takes presetance? Meaning does the STI go before or after the actual Model's column description? I haven't used STI's often, but from what i see you're setting `nullable: false` on the model... have you tried it with adding `notification.type = 'someType'` just to test the theory?

**Comment by andre-g-barbosa** [comment]
Hey @snolangps, 
I'm helping @jtushman look into this at the moment; Adding notification.type did not seem to fix the issue. Normally, the field in automatically filled in by the TableInheritance annotation

**Comment by mtaylor769** [comment]
I am having this issue as well. Subscribing for answers. 

Here is the stacktrace I think is relevant:
`at UpdateQueryBuilder.createUpdateExpression (~/myproject/api/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:429:19)` 

I thought that perhaps passing a spread operator would "break up" the object into k/v tokens, but TS doesn't like it.

**Comment by jtushman** [comment]
so i solved this for myself -- and plan going to close the issue.

The issue for me was that I was passing a object graph where one of the entities was not yet saved, causing a weird behavior.

I don't think there is much TypeOrm can do here -- expect potenitally make a better error message

**Comment by ufku** [comment]
In my case this happened while trying to update a **readonly** dateCreated field, which was the only field that changed.

The value was detected as changed but the field was omitted because of the readonly flag which resulted in an empty value set.

**Comment by feyton** [comment]
In my case I was trying to save the related object without setting `cascade: true` on the `one-to-one`. After adding the cascade property all things were resolved on my end.

**Comment by afarah1** [comment]
In my case I had saved the entity, but did not use the return of `save`...

```typescript
@Entity
export class Target {
  ...
}

@Entity
export class Source {
  ...
  @ManyToOne(type => Target)
  target: Target;
}
```

```typescript
await DataSource.manager.save(targets);
await DataSource.manager.save(sources); // fails
```

The first save returns `Target[]`. Although `targets` have been saved, TypeORM only knows that if you use the returned `Target[]` objects as the `target` field of the `sources` (the `target` field of each `Source` entity must be updated with the respective returned `Target`)...
