### ISSUE TITLE
Hide passwords in logs.

### ISSUE THREAD

**Issue by ericwooley** [typeorm/typeorm#5497]
**Issue type:**

[X] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I am developing a basic auth flow with registration. I turned on query logging and noticed this:
```
query: INSERT INTO "user"("email", "password") VALUES ($1, $2) RETURNING "id" -- PARAMETERS: ["bob@gmail.com","$2b$16$UE1eOvgVr8/34k0etG6Bc.YRmjswkfe5tl/FaKTpVrs4NRoUdiKry"]
```
Is there any way to hide the password hash in the logs?

Full reference code
-------------------
user.ts
```ts
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  BaseEntity,
  Unique,
  Index
} from 'typeorm'
import { IsEmail, Length, Matches } from 'class-validator'
import * as bcrypt from 'bcrypt'

@Entity()
@Unique('email', ['email'])
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  @Index()
  @IsEmail()
  email: string

  @Column({ select: false })
  password: string

  public setPassword(pw: string) {
    return new Promise((resolve, reject) => {
      bcrypt.hash(pw, 10000, (err, hashPw) => {
        if (err) return reject(err)
        this.password = hashPw
        resolve(true)
      })
    })
  }

  public checkPassword(pw: string) {
    return new Promise((resolve, reject) => {
      bcrypt.compare(this.password, pw, (err, same) => {
        if (err) return reject(err)
        return resolve(same)
      })
    })
  }
}

export class ValidationUser extends User {
  async toUser() {
    const user = new User()
    user.email = this.email
    await user.setPassword(this.password)
    return user
  }
  @Matches(/^(?=.*[\w])(?=.*[\W])[\w\W]{8,}$/, {
    message:
      'password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, and one number.'
  })
  password: string
}

```

register.ts
```ts
import { Request, Response, NextFunction } from 'express'
import { ValidationUser, User } from '../../entity/User'
import { validate } from 'class-validator'
import { Problem } from '../../middleware/problem'

export async function register(
  req: Request,
  res: Response,
  next: NextFunction
) {
  const { email, password } = req.body as User
  const potentialUser = await User.findOne({
    where: { email: email }
  })
  if (potentialUser) {
    sendSuccess(res)
    return next(null)
  }

  const validationUser = new ValidationUser()
  validationUser.email = email
  validationUser.password = password
  const errors = await validate(validationUser)
  if (errors.length) {
    return next(
      new Problem(400, {
        title: 'Invalid user attributes',
        type: 'InvalidUserAttributes',
        errors: errors.map(e => e.toString())
      })
    )
  }

  if (!errors.length) {
    const user = await validationUser.toUser()
    await user.save()
    sendSuccess(res)
    return next(null)
  }
}

function sendSuccess(res: Response) {
  res.statusCode = 200
  res.setHeader('Content-Type', 'application/json')
  res.end(
    JSON.stringify({
      message:
        'Registration successful. Check your email for further instructions.'
    })
  )
}

```

**Comment by davedray** [comment]
Look at [Using A Custom Logger](https://github.com/typeorm/typeorm/blob/master/docs/logging.md#using-custom-logger)

You can extend whichever logger, and override the `logQuery` method, in your version, you inspect your query, see if it has "password" in it, if so, figure out which placeholder is being used for it, and then replace the parameter that is being mapped to that placeholder with whatever you want.  This isn't tested, but something like this should work:

    import AdvancedCosoleLogger from 'typeorm/logger/AdvancedConsoleLogger'
    import {LoggerOptions} from "typeorm/logger/LoggerOptions";
    import {QueryRunner} from "typeorm/query-runner/QueryRunner";

    class PasswordHidingLogger extends AdvancedConsoleLogger {
        private regex: RegExp;
        constructor(private options?: LoggerOptions) {
            super(options);
            this.regex =  = new RegExp(/(\(.*\)).*(\(.*\))/gm); // get two groups of text between parenthesis
        }

        /**
         * Logs query and parameters used in it.
         */
        logQuery(query: string, parameters?: any[], queryRunner?: QueryRunner): any {
            params = [...parameters];
            // If the query contains the word password
            if (query.indexOf('password') !== -1) {
                // split with our regex -- ["INSERT INTO "user"", "("email", "password")", "($1, $2)", ""]
                const [,columns, placeholders] = query.split(regex);
                // get the index of "password" columns -- 1
                const colIndex = columns.split(",").map(s => s.replace(/[ \"\(\)]/g, '')).findIndex(c => c === 'password');
               if (colIndex !== -1) {
                   // get the placeholder numbers -- ["1", "2"]
                   const placeholderNumbers = placeholders.split(",").map(s => s.replace(/[\$\(\) ]/g, ''));
                   if (placeholderNumbers.length - 1 >= colIndex) {
                       // get the placeholder number -- 2
                       const placeholderNumber = parseInt([placeholderNumbers[colIndex]);
                       if (!isNan(placeholderNumber)) {
                           // replace the appropriate index of params with a bunch of *
                           params[placeholderNumber - 1] = '********';
                       }
                   }               
                }
            }
            return super.logQuery(query, params, queryRunner);
        }
    }


Or if you don't need it so generic, you could simply do:
    
    const params = [...parameters];
    if (query === 'INSERT INTO "user"("email", "password") VALUES ($1, $2) RETURNING "id"') {
        params[1] = '********';
    }
    return super.logQuery(query, params, queryRunner);

**Comment by ericwooley** [comment]
Ah, good advice. I suppose I will have to do something like that.

I was hoping there was something I was missing, like a decorator.

```ts
@logHidden()
password:string
```

I'm a little surprised to find that there aren't a lot of people asking this question. It makes me wonder how many people make the mistake of logging passwords, though if they are keeping all the logs of the queries, they probably aren't keeping them for very long.

Anyways, thanks for the advice and demo code!
