### ISSUE TITLE
Relationships creating additional column

### ISSUE THREAD

**Issue by jas777** [typeorm/typeorm#5499]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest` **@nestjs/typeorm**
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
When creating the schema, TypeORM creates additional column that should not be created. The entity has property `creator` which is a relationship so I'd expect it to create `creatorId`, but it creates `creator` AND `creatorId`. When I'm trying to save the entity it throws `null value in column \"creator\" violates not-null constraint` 

The `CategoryEntity` which I have problem with: https://hatebin.com/juohdlqhyq
The `UserEntity` which has relationship with category: https://hatebin.com/qzvpykmtgg
And the category service - https://hatebin.com/iidgqqfeqw **line 76 most likely**
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by zhawzid** [comment]
try to 
`71: await this.categoryRepository.create({ ...data, creatorId: user.id});`

and
```
77: return {
            ...category,
            creator: user.toResponseObject(false)
        };

```
I always define the foreign key field within the entity and provide 

example:

```
@Column({
    type: 'int',
    nullable: false,
    name: 'idUser',
  })
  idUser: number;

@ManyToOne(
    () => User,
    user => user.scripts,
    {
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
    },
  )
  @JoinColumn({ name: 'idUser' })
  user: User;



```

**Comment by jas777** [comment]
> try to
> `71: await this.categoryRepository.create({ ...data, creatorId: user.id});`
> 
> and
> 
> ```
> 77: return {
>             ...category,
>             creator: user.toResponseObject(false)
>         };
> ```
> 
> I always define the foreign key field within the entity and provide
> 
> example:
> 
> ```
> @Column({
>     type: 'int',
>     nullable: false,
>     name: 'idUser',
> })
> idUser: number;
> 
> @ManyToOne(
>     () => User,
>     user => user.scripts,
>     {
>       onDelete: 'CASCADE',
>       onUpdate: 'CASCADE',
>     },
> )
> @JoinColumn({ name: 'idUser' })
> user: User;
> ```

nope, still errors and creates the "creator" column :/

**Comment by jas777** [comment]
Turns out it was TS' failure and it compiled 2 file versions into 1 somehow
