### ISSUE TITLE
npm version number mismatch vs CHANGELOG

### ISSUE THREAD

**Issue by felipesabino** [typeorm/typeorm#550]
- `typeorm` package on npm has `0.11.0` version (apparently the current stable release) but there is no mention of it on [CHANGELOG](https://github.com/typeorm/typeorm/blob/55a2503a03b7d5eb2e985b7539d2919f9a0cbbca/CHANGELOG.md)

```
$npm show typeorm@0.* version
typeorm@0.0.1 '0.0.1'
typeorm@0.0.2 '0.0.2'
typeorm@0.0.3 '0.0.3'
typeorm@0.0.4 '0.0.4'
typeorm@0.0.5 '0.0.5'
typeorm@0.0.6 '0.0.6'
typeorm@0.0.7 '0.0.7'
typeorm@0.0.8 '0.0.8'
typeorm@0.0.9 '0.0.9'
typeorm@0.0.10 '0.0.10'
typeorm@0.0.11 '0.0.11'
```

- `npm` latest version is currently `0.1.0-alpha.9` but [CHANGELOG](https://github.com/typeorm/typeorm/blob/55a2503a03b7d5eb2e985b7539d2919f9a0cbbca/CHANGELOG.md) has no mention of `alpha.9`, is the latest version on npm always the one documented and published?

**Comment by pleerock** [comment]
> typeorm package on npm has 0.11.0 version (apparently the current stable release) but there is no mention of it on CHANGELOG

right the latest mention is about `0.0.10`. `0.0.11` has a hotfix as I remember, which should have mentioned but looks like we forget about it.

` CHANGELOG has no mention of 0.1.0-alpha.9` but CHANGELOG has no mention about `0.1.0` which includes changes across all alphas
