### ISSUE TITLE
React-Native sqlcipher option

### ISSUE THREAD

**Issue by Sarran2003** [typeorm/typeorm#5506]
Looking for help to enable sqlcipher option for react-native driver. Looks like now we have sqlcipher option only for the type sqllite.

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there a way to enable this option in react-native or is there a plan to include in feature to integrate with react-native-sqlcipher-storage. Any help would be appreciated. Thanks.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
