### ISSUE TITLE
Azure CosmosDB Support

### ISSUE THREAD

**Issue by ghost** [typeorm/typeorm#5510]
Any plan to support cosmosdb? Maybe it is possible to reuse some of https://github.com/abouroubi/azure-database/tree/feature/cosmosdb to implement this new feature.

**Comment by DenzoNL** [comment]
+1, would love to see Cosmos DB natively supported by TypeORM, so I can use it in conjunction with NestJS and [nestjs/azure-func-http](https://github.com/nestjs/azure-func-http) :)

**Comment by goulash1971** [comment]
+1, was intending to use TypeOrm on a project but will probably switch to Mongoose ... I prefer TypeOrm for a number of reasons but wanting to use CosmosDB (ideally with the MongoDB driver) would be happy to contribute to help

**Comment by Kartik2016** [comment]
Hi! Has anyone started working on this?

**Comment by amanganiello90** [comment]
I suppose that now there aren't developers working on its

**Comment by Kartik2016** [comment]
@amanganiello90 Alright. Is there any other solution that you are using?

**Comment by amanganiello90** [comment]
You could configure your cosmosDB instance as MongoDB using its driver. In this way you can use typeorm MongoDB connector. However, CosmosDB can use different configuration driver (mssql, mysql, cassandra etc),  and so it is considered as that. Instead, to use a "pure" cosmsdb instance, for now that isn't a typeorm developemt (it's the scope of this issue)

**Comment by Matzu89** [comment]
Is this still being considered as potential function?

**Comment by ToshioMagic** [comment]
+1

**Comment by Ginden** [comment]
> Is this still being considered as potential function?

New drivers aren't planned, but PRs will be accepted.

**Comment by elbasan** [comment]
I guess no implementation is planned for cosmos?

**Comment by tn-motorq** [comment]
Is there any ongoing plan for integrating cosmos db into typeorm? Would benefit thousands !

**Comment by agentg2007** [comment]
+1

**Comment by mifransaleem** [comment]
Just set the `ssl: true` in the DataSource and it will connect with the instance.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
