### ISSUE TITLE
Synchronise fails for @ViewEntity() on Postgres

### ISSUE THREAD

**Issue by alexmantaut** [typeorm/typeorm#5515]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.22` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have a repository with several entities and a view that uses the `@ViewEntity()` annotation.

When using the synchronise option, the first time running the process it runs ok (it generates the view and the view works), but the second time I try to run the process typeorm tries to drop the view multiple times and it fails with an error message.

I looked for similar issues and they recommended using synchronise false on the `@ViewEntity` decorator, but this did not seem to make a difference for me.

I started debugging into the typeorm code to better understand the issue, and it seems that the query for the view stored the database does not seem to be detected by typeorm to match the view from the entity metadata (I can provide with the different results if necessary)

Backtracking from there it seems that this query:
```
SELECT "t".*, "v"."check_option" FROM "typeorm_metadata" "t" INNER JOIN "information_schema"."views" "v" ON "v"."table_schema" = "t"."schema" AND "v"."table_name" = "t"."name" WHERE "t"."type" = 'VIEW' 
```

returns the same view in many cases, but with different values (see [view-query.txt](https://github.com/typeorm/typeorm/files/4196786/view-query.txt))

Am I doing something wrong? Is there any workaround around this issue while still using synchronise?

Let me know if more information is necessary

Thanks in advance

Error Log:
```
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'typeorm_metadata'
PlatformTools.ts:228
query: SELECT * FROM current_schema()
PlatformTools.ts:228
query: SELECT "t".*, "v"."check_option" FROM "typeorm_metadata" "t" INNER JOIN "information_schema"."views" "v" ON "v"."table_schema" = "t"."schema" AND "v"."table_name" = "t"."name" WHERE "t"."type" = 'VIEW' 
PlatformTools.ts:228
query: SELECT * FROM current_schema()
PlatformTools.ts:228
query: SELECT * FROM current_schema()
PlatformTools.ts:228
query: DELETE FROM "typeorm_metadata" WHERE "type" = 'VIEW' AND "schema" = $1 AND "name" = $2 -- PARAMETERS: ["public","sample_point_last_sample"]
PlatformTools.ts:228
query: DROP VIEW "sample_point_last_sample"
PlatformTools.ts:228
query: SELECT * FROM current_schema()
PlatformTools.ts:228
query: SELECT * FROM current_schema()
PlatformTools.ts:228
query: DELETE FROM "typeorm_metadata" WHERE "type" = 'VIEW' AND "schema" = $1 AND "name" = $2 -- PARAMETERS: ["public","sample_point_last_sample"]
PlatformTools.ts:228
query: DROP VIEW "sample_point_last_sample"
PlatformTools.ts:228
query failed: DROP VIEW "sample_point_last_sample"
PlatformTools.ts:232
error:
PlatformTools.ts:232
Error: view "sample_point_last_sample" does not exist
PlatformTools.ts:232
query: ROLLBACK
PlatformTools.ts:228
Test program uncaught exception: QueryFailedError: view "sample_point_last_sample" does not exist
    at new QueryFailedError (/home/alexm/projects/farmbot_be_v2/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/home/alexm/projects/farmbot_be_v2/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/home/alexm/projects/farmbot_be_v2/node_modules/pg/lib/query.js:145:17)
    at Connection.connectedErrorMessageHandler (/home/alexm/projects/farmbot_be_v2/node_modules/pg/lib/client.js:214:17)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at Socket.<anonymous> (/home/alexm/projects/farmbot_be_v2/node_modules/pg/lib/connection.js:134:12)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:287:12)
```

My view:
```
@ViewEntity({ 
  expression: (connection: Connection) => connection.createQueryBuilder()
    .select("sample.id", "id")
    .addSelect("sample.date", "date")
    .addSelect("sample.data", "data")
    .addSelect("sample.condition", "condition")
    .addSelect("sample.processingStatus", "processing_status")
    .addSelect("sample.samplePointId", "sample_point_id")
    .from(Sample, "sample")
    .where(qb => {
        const subQuery = qb.subQuery()
          .select("max_date_sample.sample_point_id, MAX(max_date_sample.date)")
          .from(Sample, "max_date_sample")
          .where("max_date_sample.sample_point_id IS NOT NULL")
          .groupBy("max_date_sample.sample_point_id")
          .getQuery();
        return `(sample.sample_point_id, sample.date) IN ${subQuery}`;
    })
})
export class SamplePointLastSample {

  @ViewColumn()
  public id: number;

  @ViewColumn()
  public date: Date;

  @ViewColumn()
  public data?: JsonKeyValue;

  @ViewColumn()
  public condition: SampleCondition = SampleCondition.OK;

  @ViewColumn()
  public processingStatus: SampleProcessingStatus = SampleProcessingStatus.PROCESSED;

  // For querying without joining FK
  @ViewColumn()
  public samplePointId: number;

  @ManyToOne(() => SamplePoint, { nullable: true })
  public samplePoint?: Promise<SamplePoint>;
}
```

**Comment by jagabs** [comment]
+1

**Comment by alexmantaut** [comment]
Thanks for the reply @jagabs.

In my case the error message dissapeared after some big changes I made in the db in the past, but couldn't point exactly what fixed it...

Maybe I dropped the view and removed it from typeorm_metadata and that fixed it...

In any case, closing the issue.

**Comment by joaquindiazs** [comment]
Why is closed this issue?. any workaround for avoid synchronize the entityviews?

**Comment by jacobgoh101** [comment]
This is still happening today.....

**Comment by ericdesa** [comment]
@jacobgoh101 keep in mind that the synchronize mode is only for your development environnements, so it should not be a major issue.

When it occurs, you can :
- remove the views from your database manually
- clear the `typeorm_metadata` table
- restart your app

**Comment by bushev** [comment]
Guys, I think it's still a problem.

It makes really hard to develop with a live reload and `sync=true`. I have to remove views and then restart the node.js app after every change.

**Comment by ericdesa** [comment]
@bushev can you confirm that the `typeorm_metadata` table managed by typeorm is empty before restarting your app ?
In my case, this was the source of the problem : removing the views without clearing this table was creating duplicate entries.

**Comment by bushev** [comment]
Hey @ericdesa, yeah, cleaning the `typeorm_metadata` table helps!

**Comment by hmarcelodn-ae** [comment]
Hey guys, any solution on this that does not involve the typeorm_metadata table?

**Comment by Hareloo** [comment]
This is happening to me too and even when clearing typeorm_metadata it still happens.
Seems like TypeORM tries to drop the same view twice and obviously fails...

**Comment by bendadaniel** [comment]
remove typeorm_metadata records fixed problem
