### ISSUE TITLE
Leftjoin and WHERE clause on joined table

### ISSUE THREAD

**Issue by popemann** [typeorm/typeorm#5519]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.18` (or put your version here)

Hello!

My question is related to applying a where condition on a joined table, where it will filter the rows in the main table, but also in the joined table. I will explain it better in the example below.

I have the following query:
```ts		
return this.profRepository.createQueryBuilder('professor')
	.select(['professor', 'professor.firstName', 'professor.lastName', 'roles', 'department'])
	.leftJoin('professor.roles', 'roles')
	.leftJoin('professor.department', 'department')
	.leftJoin('professor.committee', 'committee')
	.where('roles.id = :id', { id: RolesEnum.PROFESSOR })
	.getMany();
```

Now, this me return a result like this (I only show one object in the array, for the example sake): 
```json    
{
        "userId": 100012,
        "email": "commission_stand_in@mail.com",
        "firstName": "commission_stand_in",
        "lastName": "commission_stand_in",
        "roles": [
            {
                "id": 1,
                "type": "PROFESSOR",
                "basic": true
            }
        ],
        "department": null
    }
```

It works fine, it filters the professors based on the roles, but the problem is that I don't want the "where" clause to filter also the roles, but only the users. So I only want that the returned Professors have the given role, but the object that is returned also contain the other roles that he has.

A work-around I was trying is this:
```ts
return this.profRepository.createQueryBuilder('professor')
         .select(['professor', 'professor.firstName', 'professor.lastName', 'rolesToRetrieve', 'department'])
	.leftJoin('professor.roles', 'roles')
	.leftJoin('professor.roles', 'rolesToRetrieve')
	.leftJoin('professor.department', 'department')
	.leftJoin('professor.committee', 'committee')
	.where('roles.id = :id', { id: RolesEnum.PROFESSOR })
	.getMany();
```

To add another select with a different alias and use this one for the select function. This will return the expect result, like this: 
```json    
{
        "userId": 100012,
        "email": "commission_stand_in@mail.com",
        "firstName": "commission_stand_in",
        "lastName": "commission_stand_in",
        "roles": [
            {
                "id": 7,
                "type": "COMMISSION_STAND_IN",
                "basic": false
            },
            {
                "id": 1,
                "type": "PROFESSOR",
                "basic": true
            }
        ],
        "department": null
    }
```

I guess this is not really ok to do and not so efficient and I was wondering how could i manage to do it in a more clean way.

Thanks for help. :D

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
