### ISSUE TITLE
save does not return generated id if object to save contains a many to one relationship with an undefined id

### ISSUE THREAD

**Issue by shusson** [typeorm/typeorm#5520]
**Issue type:**

[X] bug report

**Database system/driver:**

[X] `postgres`

**TypeORM version:**

[X] `0.2.22`

**Steps to reproduce or a small repository showing the problem:**

```typescript
@Entity()
class Bean {
    @PrimaryGeneratedColumn("uuid") 
    readonly id: string;
    
    @Column()
    name: string

    @ManyToOne(() => Friend)
    friend?: Friend;
}


const green = new Bean();
green.name = "green";
const x = await getRepository(Bean).save(green);
// {id: "4a602d92-19f3-4c2f-93e5-922a4d907a75",  name: "green" }

const red = new Bean();
red.name = "red";
red.friend = {id: undefined} as Friend; 
const y = await getRepository(Bean).save(red);
// {name: "red" }
```

I would expect the id is always returned.

**Comment by Overfacto** [comment]
well, on second `red.friend` would be `{ id : undefined }`.

you have to delete key property which has undefined as value.

try to

```

const red = new Bean();
red.name = "red";
red.friend = {id: undefined} as Friend; 

delete red.friend.id;

const y = await getRepository(Bean).save(red);

```

**Comment by shusson** [comment]
@Overfacto why should deleting `red.friend.id` have any affect on `red.id`? They are not directly related and it's not like TypeORM is returning an error or no properties (e.g it returns the `name`).

**Comment by Overfacto** [comment]
@shusson In general the fields that has value as undefined is not sent to server. 
no any affectuon between ‘red.friend.id’ and ‘red.id’, but undefined field would be problem

**Comment by Overfacto** [comment]
@shusson  Could I help you ? try to below codes

```
const green = new Bean();
green.name = "green";
const x = await getRepository(Bean).save(green);
// {id: "4a602d92-19f3-4c2f-93e5-922a4d907a75",  name: "green" }

const red = new Bean();
red.name = "red";
red.friend = {id: undefined} as Friend; 

const beanRepo = getRepository(Bean);
const correctedRed = beanRepo.create(red);
const y = await beanRepo.save(red);
// { id : 1, name: "red" }
```

**Comment by alvesl** [comment]
+1 - can this be merged?
