### ISSUE TITLE
[MongoDB] Error while connecting

### ISSUE THREAD

**Issue by german-bortoli** [typeorm/typeorm#5527]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.22`

**Steps to reproduce or a small repository showing the problem:**

**MongoDB version:**

 - DB: 4.0.16
 - NodejS Driver: 3.5.3

**Connection Configuration**

```
  const connection = await createConnection({
    type: "mongodb",
    host: '127.0.0.1',
    port: 27017,
    database: "test_db",
    username: 'sample_username',
    password: 'gLT(6DM%]8$5b?m6Hs@qM'
    entities: ["src/entities/*.entity.ts"],
    migrations: ["src/migrations/*.ts"],
  });
```

I also tried using `useNewUrlParser` but without any success.

**Error**

When I run the application I am getting the following error

> UnhandledPromiseRejectionWarning: MongoParseError: Incomplete key value pair for option
> at parseQueryString (/appl/node_modules/mongodb/lib/core/uri_parser.js:406:13)

I did some debug on the uri_parser file and got this parsed object.

`[Object: null prototype] { 'm6Hs@127.0.0.1:27017/test_db': '' }`

**Comment by german-bortoli** [comment]
Going to close this issue because it is related to the mongodb driver.

The problem is the question mark on the password, somehow it throws an error on parsed password.

Already reported this issue on their JIRA https://jira.mongodb.org/browse/NODE-2461

**Comment by Karnith** [comment]
for others that land here, using encodeURIComponent() wrapper for username and password values.

username: encodeURIComponent('sample_username')
password: encodeURIComponent('gLT(6DM%]8$5b?m6Hs@qM')
