### ISSUE TITLE
Cannot Create Connection without TypeScript Freaking Out

### ISSUE THREAD

**Issue by nhubbard** [typeorm/typeorm#553]
Hi all,
I'm creating a web app where I combine the (awesome, may I add) `routing-controllers` with TypeORM. While attempting to create a connection, I receive a wonderful error message for SublimeLinter's TypeScript linter:
```
Argument of type '{ driver:{ type: "mysql"; host: string; port: number; username: string; password: string; database: string; } }' is not assignable to parameter of type 'ConnectionOptions'.
  Type '{ driver: { type: "mysql"; host: string; port: number; username: string; password: string; database: string; } }' is not assignable to type 'MongoConnectionOptions'.
    Property 'type' is missing in type '{ driver: { type: "mysql"; host: string; port: number; username: string; password: string; database: string; } }'.
```
I cannot seem to figure out what could be causing this. Would someone be able to help me, or just point me in the right direction?
Thanks!
(My code is below. It is in a \@Get class decorator.)
```javascript
		createConnection({
			driver: {
				type: "mysql",
				host: "localhost",
				port: 3306,
				username: "root",
				password: "root",
				database: "openhealth"
			},
			entities: [PatientEntity],
			autoSchemaSync: true
		}).then(c => {
			return c.find();
		}).catch(error => {
			return error;
		});
```
P.S. If there is a way to use a single connection multiple times, that would be great to know.

**Comment by pleerock** [comment]
are you using latest alpha versions? If yes then try to:

```ts
createConnection({
				type: "mysql",
				host: "localhost",
				port: 3306,
				username: "root",
				password: "root",
				database: "openhealth",
			entities: [PatientEntity],
			autoSchemaSync: true
		})
```

**Comment by nhubbard** [comment]
@pleerock That worked! Thank you. Before I close this, is there a way to reuse a connection multiple times in the same file? I'm making a REST API and would prefer to not recreate the wheel five times to do similar queries.

**Comment by pleerock** [comment]
you create connection only once during app initialization. Later you can call `getConnection()` from anywhere in your app to get the connection and perform operations with it

**Comment by nhubbard** [comment]
Thanks!

**Comment by goodbomb** [comment]
Hi, I'm getting the same error and I've done exactly what you suggested.

```
const options = {
    type: config.db.type,
    host: config.db.host,
    port: config.db.port,
    username: config.db.username,
    password: config.db.password,
    database: config.db.database,
    entities: [
        CharacterEntity
    ],
    autoSchemaSync: true
};

createConnection(options);
```

This is the error I'm seeing:

```
Argument of type '{ type: string; host: string; port: string | number; username: string; password: string; database...' is not assignable to parameter of type 'ConnectionOptions'.
```

Any help would be appreciated.

**Comment by pleerock** [comment]
@goodbomb `autoSchemaSync` is called `synchronize` in newer versions

**Comment by goodbomb** [comment]
Thanks @pleerock. That solves the second issue, but I'm still getting the first error:

```
Argument of type '{ type: string; host: string; port: string | number; username: string; password: string; database...' is not assignable to parameter of type 'ConnectionOptions'.
```

**Comment by pleerock** [comment]
because of `type`. Type is not a string in connection options, its a string literal type with specific values. You need to do following:

```
const options = {
    type: config.db.type as DatabaseType,
    host: config.db.host,
    port: config.db.port,
    username: config.db.username,
    password: config.db.password,
    database: config.db.database,
    entities: [
        MyEntity
    ],
    synchronize: true
};

createConnection(options);
```

Also make a consideration if you really want to store a database type a configuration, since most probably it does not make any sense to you.

**Comment by goodbomb** [comment]
That still didn't do the trick, but replacing `config.db.type` with `'postgres` did the trick. Thanks for the insight!

**Comment by pleerock** [comment]
its not about typescript issues actually, you just need to get closer to typescript type system, in particle about string literal types. Glad that you solved your problem.

**Comment by otroboe** [comment]
Hello ! I still have this issue, and I'm not sure how to fix it. I'm quite new with TS, so it's not obvious for me.

My code:
```javascript
const ormConfig: ConnectionOptions = {
  type: process.env.TYPEORM_CONNECTION as DatabaseType,
  host: process.env.TYPEORM_HOST,
  port: process.env.TEST_DB_PORT,
  username: process.env.TEST_DB_USERNAME,
  password: process.env.TEST_DB_PASSWORD,
  database: process.env.TEST_DB_DATABASE,
  entities: [
    path.join(process.cwd(), process.env.TYPEORM_ENTITIES),
  ],
  synchronize: true,
};
```

And I have this message:
```
Type '{ type: "mysql" | "mariadb" | "postgres" | "sqlite" | "mssql" | "oracle" | "websql" | "cordova" |...' is not assignable to type 'ConnectionOptions'.
  Type '{ type: "mysql" | "mariadb" | "postgres" | "sqlite" | "mssql" | "oracle" | "websql" | "cordova" |...' is not assignable to type 'MongoConnectionOptions'.
    Types of property 'type' are incompatible.
      Type '"mysql" | "mariadb" | "postgres" | "sqlite" | "mssql" | "oracle" | "websql" | "cordova" | "sqljs"...' is not assignable to type '"mongodb"'.
        Type '"mysql"' is not assignable to type '"mongodb"'.
```

**Comment by pleerock** [comment]
I mentioned few times that its pointless to store "database type" in env variables. Don't do that.

**Comment by otroboe** [comment]
Ok thank you ! I thought I tried it before, but this is working now :)

```
const ormConfig: ConnectionOptions = {
  type: 'mysql',
  host: process.env.TYPEORM_HOST,
  port: parseInt(process.env.TEST_DB_PORT, 10),
  username: process.env.TEST_DB_USERNAME,
  password: process.env.TEST_DB_PASSWORD,
  database: process.env.TEST_DB_DATABASE,
  entities: [
    path.join(process.cwd(), process.env.TYPEORM_ENTITIES),
  ],
  synchronize: true,
};
```

**Comment by hobord** [comment]
Then this ORM is not a database abstraction layer...
You can't change the database without change the code.
Usually, the docker container using the env variables for the configurations (db connection for example)...
So then if it does not support the env variable then we must rebuild the docker images...
It is really painful and useless.

**Comment by Kononnable** [comment]
Typeorm does support passing connection options from env variables.
https://github.com/typeorm/typeorm/blob/master/src/connection/options-reader/ConnectionOptionsEnvReader.ts
Changing database driver is completely different story - because most of the times you will need to change the code, so rebuilding image will still be necessary.

**Comment by pleerock** [comment]
> Then this ORM is not a database abstraction layer...

database abstraction generally is pointless because you never do that in reality but you loose much of database functionality.

**Comment by im4aLL** [comment]
```type: any;``` will do the trick!

**Comment by burakgavaskargo** [comment]
You can use with `type: process.env.CONNECTION as 'postgres',`
