### ISSUE TITLE
One-To-One Relation with Versioned Entity

### ISSUE THREAD

**Issue by thomaschaaf** [typeorm/typeorm#5532]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following entities: User, Order & Address.

A user has a current Address (One-To-One Relation), an Order has an address (One-To-One Relation but versioned) something is sent to and an address can change over time. If a user changes their address for future orders this means the new address should be used. However the old order was still sent to the address.

```
@Entity()
export class Address {
  @VersionColumn()
  @PrimaryGeneratedColumn()
  public id!: number;

  @Column()
  public address!: string; // for simplicity sake this is one column
}
```

```
@Entity()
export class User {
  @PrimaryGeneratedColumn()
  public id!: number;

  @OneToOne((type) => Address)
  @JoinColumn()
  public address!: Address;
}
```

```
@Entity()
export class Order {
  @PrimaryGeneratedColumn()
  public id!: number;

  @OneToOne((type) => Address)
  @JoinColumn()
  public address!: Address;

  public addressVersion!: number;
}
```

As far as my understanding that I would have to manually set addressVersion and there is no way to reference the entry by the combination of addressId and addressVersion

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
