### ISSUE TITLE
How to keep-alive(use mysql)?

### ISSUE THREAD

**Issue by WangPengJu** [typeorm/typeorm#554]
Long time no operation， The next operation will be slow, It takes about 10000 milliseconds.
![qq 20170618172124](https://user-images.githubusercontent.com/9954852/27259660-99148c02-544a-11e7-9674-bd05210ad47d.png)

**Comment by WangPengJu** [comment]
mysql set:
![qq 20170618172628](https://user-images.githubusercontent.com/9954852/27259678-4de245a2-544b-11e7-98a5-92c271b381a4.png)

**Comment by WangPengJu** [comment]
version:   "typeorm": "0.1.0-alpha.10"

**Comment by pleerock** [comment]
I do not understand what is the problem. typeorm uses connection pool so your connections aren't closed. @NoNameProvided do you know about this problem?

**Comment by NoNameProvided** [comment]
@pleerock I haven't tested it, just showed it's a valid report if the issue exists.

**Comment by pleerock** [comment]
okay thanks) For some reason author closed his issue
