### ISSUE TITLE
Does TypeORM support ORDER BY FIELD

### ISSUE THREAD

**Issue by prameetc** [typeorm/typeorm#5544]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I would love to know if `ORDER BY FIELD` is supported in TypeORM, I would like to convert the below query to typeorm syntax

```
SELECT * FROM f where f.id IN (2, 3, 1)
ORDER BY FIELD(f.id, 2, 3, 1);
```

**Comment by ChristianMurphy** [comment]
it's in the documentation https://typeorm.io/#/select-query-builder/adding-order-by-expression

**Comment by davidfrtala** [comment]
> it's in the documentation https://typeorm.io/#/select-query-builder/adding-order-by-expression

@ChristianMurphy No, it's not.

We need `FIELD()` function in `.orderBy()` builder function. 
https://stackoverflow.com/a/5090679/3042366

This function has a great benefit when using GraphQL Dataloader, where you need achieve the exact same keys order as the db result

https://github.com/graphql/dataloader/issues/66

**Comment by ChristianMurphy** [comment]
@davidfrtala yes, it does, `orderBy` can include a function

```
createQueryBuilder("user")
    .orderBy("FIELD(id, 5,4,3,1,6)")
```

**Comment by davidfrtala** [comment]
@ChristianMurphy no, it really doesn't !!

This is just a workaround, that I have to use

```javascript
createQueryBuilder('user')
      .whereInIds(ids)
      .orderBy(`FIELD (id, ${ids.join(',')})`)
      .getMany()
```

But eventually, my `ids` aren't sanitized as other parameters, leaving to a potentiol risk of SQL attack.
Also, it appends `ASC` at the end of a order query. As you can see in the resulting query

```
query: SELECT * FROM `user` WHERE `id` IN (?, ?) ORDER BY FIELD (`id`, 5,6) ASC -- PARAMETERS: [5,6]
```

Which really isn't a solution

**Comment by ChristianMurphy** [comment]
@prameetc relax

The original question was

> I would love to know if `ORDER BY FIELD` is supported in TypeORM

The answer is yes.
Is the solution optimal, maybe not, but it is supported.

> eventually, my ids aren't sanitized as other parameters

If you want the `FIELD` parameters parameterized, that is also possible.
See this example from the test cases https://github.com/typeorm/typeorm/blob/82b06d0a59ae368233c00b32330d7f87787a64cd/test/functional/spatial/postgres/spatial-postgres.ts#L210-L216

Again, not optimal syntax, but it is supported.

**Comment by davidfrtala** [comment]
Allright. Seems acceptable
