### ISSUE TITLE
update and delete static methods should throw if given Id is incorrect

### ISSUE THREAD

**Issue by artoodeeto** [typeorm/typeorm#5549]
**Issue type:**

[X] question
[] bug report
[X] feature request
[] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have these code in my codebase that I think would be cleaner if some of static methods throws an error.

like:

```ts
const { id } = req.params;
    const { title, body } = req.body;
    try {
      await PostModel.findOneOrFail(id);
      await PostModel.update(id, { title, body });
      res.status(200).json({
        meta: {},
        payload: {
          message: 'success'
        }
      });
    } catch (error) {
      res.status(404).json({ error });
    }
```

```ts
const { id } = req.params;
    try {
      await User.findOneOrFail(id);
      await User.delete(id);
      res.status(200).json({
        payload: {
          status: 'success'
        }
      });
    } catch (error) {
      res.status(404).json({
        error
      });
    }
```

those `findOneOrFail` can be omitted if delete and update methods throws an error if supplied ID can't be located or not in database. I know that in the database level there's no error but it would be nice if this is implemented.

**Comment by imnotjames** [comment]
You can check the result of the delete.  It has the rows affected.
