### ISSUE TITLE
Relations limit and offset

### ISSUE THREAD

**Issue by mattia-lau** [typeorm/typeorm#5553]
**Issue type:**
[x] question

**Database system/driver:**
[x ] `mssql`

**TypeORM version:**
[ x] `latest`

**Steps to reproduce or a small repository showing the problem:**

how to set the comments limit and offset by using the following code or any suggestion??
```
const store= await this.storeRepository.findOne(id, {
    relations: ['comments', 'comments.user']
 });
```

**Comment by artoodeeto** [comment]
@mattia-lau Hello, Have you tried doing the inverse? Finding the comments where user id = ? with limit and skip? property? I'm not sure if that's right but that's what I would do.

**Comment by mattia-lau** [comment]
> @mattia-lau Hello, Have you tried doing the inverse? Finding the comments where user id = ? with limit and skip? property? I'm not sure if that's right but that's what I would do.

thank you for the reply. the  findOne api is not providing take and skip function. 
and i dont know what is inverse.
can you provide the simple code for me?

**Comment by artoodeeto** [comment]
@mattia-lau ohh yea. findOne doesn't have a skip property it would be redundant.

maybe you could.

```
commentsRepo.find({ relations: ["user"], where: [{ userId: id }], skip: 1, take: 5 })
```
something like that?

if I'm wrong you could try query builder:

```ts
await getConnection()
    .createQueryBuilder()
    .select("comments")
    .from(Comment, "comment")
    .where("comment.userId = :id", { id: 1 })
    .limit(10)
    .offset(10)
    .getMany();
```
I haven't used query builder but just check the syntax on the documentation I might be wrong. hope it helps. :smile:
