### ISSUE TITLE
question: How to put brackets on from field

### ISSUE THREAD

**Issue by Veath** [typeorm/typeorm#5554]
**Issue type:**

[x] question

**Database system/driver:**
[x] `mysql` / `mariadb`
**TypeORM version:**

[x] `latest`
**Steps to reproduce or a small repository showing the problem:**
sql error: 1054 - Unknown column 'function.triggerId' in 'on clause', Time: 0.001000s
```js
    const db = this.functionRepository
      .createQueryBuilder('function')
      .addFrom(Env, 'env')
      .andWhere('env.func_id = function.id')
      .leftJoinAndSelect('function.trigger', 'trigger')
      .getMany()

```

typerom how to put brackets on from field

**Similar problem**：https://stackoverflow.com/questions/4065985/mysql-unknown-column-in-on-clause

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
