### ISSUE TITLE
caching duration limit

### ISSUE THREAD

**Issue by Yasukity** [typeorm/typeorm#5555]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] 0.2.18

**Steps to reproduce or a small repository showing the problem:**

I'm just trying to use cache with typeorm, where I'm wondering if cache duration is configurable to the extent you want.
Judging from source code, it looks like there is not limitation on it.
Is it possible to keep cache for, say 1day(1000 x 3600 x 24ms)?
If so is there any concern by keeping cache for such a long time?

Thanks in advance.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Ginden** [comment]
> If so is there any concern by keeping cache for such a long time?

You can get outdated results, that's all.

**Comment by Yasukity** [comment]
@Ginden 
thank you for answering.
Do you mean we can keep cache for 1 day, but it doesn't make sense?

**Comment by Ginden** [comment]
For most apps it won't make sense, but I don't know your business requirements.
