### ISSUE TITLE
Unable to get select: false working in PrimaryColumn

### ISSUE THREAD

**Issue by clarkey** [typeorm/typeorm#5556]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.22` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am trying to use `select: false` in `@PrimaryColumn` to prevent the primary key id being selected in any queries but it doesn't seem work. The column 'id' is still selected.

```ts
// vip.entity.ts
import { Column, Entity, PrimaryColumn } from 'typeorm';

@Entity()
export class Vip {
  @PrimaryColumn({
    generated: true,
    select: false,
  })
  id: number;

  @Column()
  uuid: string;

  @Column({ default: false })
  enabled: boolean;

  @Column()
  address: string;

  @Column()
  type: string;

  @Column()
  entity: string;

  @Column()
  ndb: string;

  @Column()
  balancer: string;
}
```

I am using this Entity in NestJS as below...

```ts
// vips.service.ts
import { Repository } from 'typeorm';

import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';

import { Vip } from './vip.entity';

@Injectable()
export class VipsService {
  constructor(
    @InjectRepository(Vip)
    private readonly vipsRepository: Repository<Vip>,
  ) {}

  findAll(): Promise<Vip[]> {
    return this.vipsRepository.find();
  }

  findOne(uuid: string): Promise<Vip> {
    return this.vipsRepository.findOne({
      where: {
        uuid,
      },
    });
  }

  async remove(id: string): Promise<void> {
    await this.vipsRepository.delete(id);
  }
}
```

Both `findAll()` and `findOne(uuid)` return the `id` column.

**Comment by Kononnable** [comment]
Primary keys will always be selected - they're crucial to orm internal logic(operating on entity later on). We could remove `select` from `PrimaryColumn`, `GeneratedPrimaryColumn` options though.

**Comment by ddsultan** [comment]
A workaround (or even a solution) I have found is with [@Exclude](https://github.com/typestack/class-transformer#skipping-specific-properties) from [class-transformer](https://github.com/typestack/class-transformer). At first glance it is similar to DTO design pattern. Just in case anyone is struggling (like me)
