### ISSUE TITLE
Parametized query wont work

### ISSUE THREAD

**Issue by badcoder28** [typeorm/typeorm#556]
Hi!

Im using [typescript-express-example ](https://github.com/typeorm/typescript-express-example) template and i was successfully connected my application to my **MySQL** database.

Now i am working with [entityManager.query](https://typeorm.github.io/entity-manager.html#api.entityManager.query) to insert, select etc.. some data.

Here is my errors when running this:

```
const result = await getEntityManager().query('SELECT * FROM tbl_1 WHERE name = :name;', [ p_name ])

Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to
your MySQL server version for the right syntax to use near ':name' at line 1
```

Another error is when running this:

```
const result = await getEntityManager().query('SELECT * FROM tbl_1 WHERE name = ` + 'some_name' + `;')

Error: ER_BAD_FIELD_ERROR: Unknown column 'some_name' in 'where clause'
```

But when using a direct plain text:

`const result = await getEntityManager().query('SELECT * FROM tbl_1 WHERE name = 'some_name';')`

It works by this way. 

**Any idea how to resolve this errors?**

**Comment by pleerock** [comment]
When using `query` method use underlying [driver escaping mechanism](https://github.com/mysqljs/mysql#escaping-query-values). For mysql:

```ts
await getEntityManager().query('SELECT * FROM tbl_1 WHERE name = ?', [ p_name ])
```

**Comment by badcoder28** [comment]
@pleerock  thanks for helping again but why does  :param wont work? According to your comment [here](https://github.com/typeorm/typeorm/issues/235#issuecomment-290665959)

**Comment by pleerock** [comment]
maybe i confused it with different driver. as i told it driver-specific thing

**Comment by badcoder28** [comment]
Well, that's fine then, i got it working now thanks a lot!

**Comment by avbentem** [comment]
...but it seems `escapeQueryWithParameters` already takes care of translating a common `:param` into, e.g., `$1`, `@1`,  `name` or `?`, depending the database dialect?

https://github.com/typeorm/typeorm/search?q=escapeQueryWithParameters seems to show all dialects use the same line to find the common `:name` placeholders (with `\b` to match whole words only):

```ts
const keys = Object.keys(parameters).map(parameter => "(:" + parameter + "\\b)").join("|");
```

**Comment by ekifox** [comment]
What about arrays?

`.query('SELECT * FORM test WHERE id IN ?', [[1,2,4]]`

**Comment by anodynos** [comment]
> What about arrays?
> `.query('SELECT * FROM test WHERE id IN ?', [[1,2,4]]`

Apparently, this works (in Postgres): 
```
  .query('SELECT * FROM test WHERE id = ANY($1)', [[1,2,4]]
```   

Source: https://github.com/brianc/node-postgres/issues/1452#issuecomment-329434219

**Comment by edencorbin** [comment]
Had similar issues and needed to use another format to handle ILIKE thought I would share in case it helps any TypeOrm (ers) 
`await entityManager.query(`SELECT id FROM ${this.configService.getDatabaseName()}.public.MY_DATA WHERE tag ILIKE '%%' || $1 || '%%'`, [search]);` This did the trick

**Comment by quezak** [comment]
The trick with `connection.driver.escapeQueryWithParameters(...)` was really nice.
However: I see that now it has a third required parameter `nativeParameters: ObjectLiteral`. Does anyone know what should I put in there?

Alternatively, is there any other clean way to properly escape query parameters when using a raw query (not `QueryBuilder`)?

**Comment by thematrixdev** [comment]
> When using `query` method use underlying [driver escaping mechanism](https://github.com/mysqljs/mysql#escaping-query-values). For mysql:
> 
> ```ts
> await getEntityManager().query('SELECT * FROM tbl_1 WHERE name = ?', [ p_name ])
> ```

Excuse me but I am not sure if I should reply on this issue.
May I know what placeholder should I use for MSSQL query string?
I have tried "?", "??", "%s", all of them does not work.
I don't want to use "$1", "$2", since the number of parameter is variable.

Thanks.

**Comment by cooljeffro** [comment]
If you're using mysql, you can pass queryFormat in your configuration options:

```
{
  type: 'mysql',
  host: 'localhost',
  port: 3306,
  ...
  extra: {
    queryFormat: function(query, values) {
      if (!values) return query;
      return query.replace(/\:(\w+)/g, (txt, key) => {
        if (values.hasOwnProperty(key))
          return this.escape(values[key]);
        return txt;
      });
    }
  }
```

https://github.com/mysqljs/mysql#custom-format

**Comment by ippeiukai** [comment]
Based on comments above (https://github.com/typeorm/typeorm/issues/556#issuecomment-317459125 and https://github.com/typeorm/typeorm/issues/556#issuecomment-556042689), we now use the following utility in migrations:
```TS
const queryWithParams = (
   queryRunner: QueryRunner,
   sql: string,
   params: ObjectLiteral
 ): ReturnType<QueryRunner['query']> =>
   queryRunner.query(...queryRunner.connection.driver.escapeQueryWithParameters(sql, params, {}));
```
Thanks!

**Comment by QuanTran91** [comment]
I got an error when running this code:
await queryRunner.query('GRANT ALL PRIVILEGES ON  ?.* To ?@? ;', [dbName, dbUser, host]);
Turnout, the query automatically append sing quote (') in dbName which result in MySQL syntax error.
