### ISSUE TITLE
How to share an entity with many table name.

### ISSUE THREAD

**Issue by UrielCh** [typeorm/typeorm#5560]
**Issue type:**
[X] question
**TypeORM version:**
[X] `latest`

Hi have to deal with some huge data, and I want do group those data by a key (customer key for example)

```typescript
@Entity()
export class CustomerData {
    @PrimaryColumn({ type: "bigint" })
    dataId: number;
    @Column()
    clientId: string;
    @Column()
    raw: string;
}
```

I want to store my data in a table named `CustomerData-${clientId}` to limit the size of my tables.
and eventually later dispatch my table in multiple SQL server.

I found an issue that looks like mine, but the answer is not clear for me.
#4654

a simple
```
    const hits = await connection
      .getRepository(CustomerData)
      .createQueryBuilder()
      .tablename(`CustomerData-${clientId}`) // <--- do not exists
      .select('raw')
      .whereInIds([ids...])
      .getRawMany();


      await connection.manager.save(toSave, {tablename: `CustomerData-${clientId}`});

```
should be enough, but a createQueryBuilder do not accept table name.

----

If typeOrm cans not deal with that logic, I can still use SqL partitioning, but thst feature is engine dependent.

**Comment by imnotjames** [comment]
Try passing a function to the entity `table` option.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
