### ISSUE TITLE
setting up a one to many relationship for a self referencing table

### ISSUE THREAD

**Issue by mhcomp** [typeorm/typeorm#5562]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

typeorm => ^0.2.22
@nestjs/typeorm => ^6.3.3

**Steps to reproduce or a small repository showing the problem:**

First of all I created a repository for reproduction, you can find it [here](https://github.com/mhcomp/setting-up-a-one-to-many-relationship-for-a-self-referencing-table/tree/master/setting-up-a-one-to-many-relationship-for-a-self-referencing-table)

- [entity design](https://github.com/mhcomp/setting-up-a-one-to-many-relationship-for-a-self-referencing-table/blob/master/setting-up-a-one-to-many-relationship-for-a-self-referencing-table/src/project.entity.ts)

- [repository](https://github.com/mhcomp/setting-up-a-one-to-many-relationship-for-a-self-referencing-table/blob/master/setting-up-a-one-to-many-relationship-for-a-self-referencing-table/src/projects.repository.ts)

- [connection configuration](https://github.com/mhcomp/setting-up-a-one-to-many-relationship-for-a-self-referencing-table/blob/master/setting-up-a-one-to-many-relationship-for-a-self-referencing-table/src/app.module.ts)

- [reproducing errors](https://github.com/mhcomp/setting-up-a-one-to-many-relationship-for-a-self-referencing-table/blob/master/setting-up-a-one-to-many-relationship-for-a-self-referencing-table/src/main.ts)

---

I have a `Project` entity with a non-autogenerated id field and a successor field. This successor is the project that follows next. But maybe there is no following project so this might be null.

```ts
@Entity()
export class Project extends BaseEntity {
  @PrimaryColumn({ unique: true })
  public id: string;
    
  @OneToMany(() => Project, project => project.id, { nullable: true })
  public successorId?: string;
}
```

When creating a new project via

```ts
public createProject(id: string, successorId?: string): Promise<Project> {
  const project: Project = new Project();
  project.id = id;
  project.successorId = successorId;
  return project.save();
}
```

there are multiple cases I have to take care for.

- Passing in an id that already exists:
  This will not throw an error. It just overrides the existing entity.

- Passing in `undefined` for the `successorId`:
  The code works fine then but it does not create a `successorId` column with `null` then. The column simply does not exist in the database.

- Passing in the same id for `id` and `successorId` (this should be possible):
  TypeORM throws the error 
 
> TypeError: Cannot read property 'joinColumns' of undefined

- Passing in a `successorId` of another existing project:
  I'm getting the same error as above

- Passing in a `successorId` of a project that doesn't exist:
  I'm getting the same error as above

I also tried this

```ts
@OneToMany(() => Project, project => project.successorId, { nullable: true })
@Column()
public successorId?: string;
```

but whenever I want to call the `createProject` method I'm getting this error

> QueryFailedError: null value in column "successorId" violates not-null
 constraint

and this

```ts
@OneToMany(() => Project, project => project.successorId, { nullable: true })
public successorId?: string;
```

but then I'm getting this error

> TypeError: relatedEntities.forEach is not a function

So how can I fix that? I think my entity design seems to be wrong. Basically it should be

- One project might have one successor
- A project can be the successor of many projects

Would be awesome if someone could help!

**Comment by clintonb** [comment]
This _closed_ ticket is a top result on Google. The solution is at https://stackoverflow.com/a/60412809/592820.
