### ISSUE TITLE
Error in altering table with queryRunner.query in migration

### ISSUE THREAD

**Issue by akshayr96** [typeorm/typeorm#5563]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

I tried to write a migration to migrate column_name of type varchar to varchar(255). The following code in the migrations returns the error '"Incorrect syntax near '-'"

```ts
  await queryRunner.query( `ALTER TABLE ${databaseName}.table_name ALTER COLUMN "column_name" varchar(255) NULL`)
```
the query that is run by typeorm visible in the error object is 

```
  ALTER TABLE DB_Name.table_name ALTER COLUMN "column_name" VARCHAR(255) NULL
```

Also, If I remove the double quotes around the column name as follows, I get the error "Incorrect Syntax near column_name"

```ts
  await queryRunner.query( `ALTER TABLE ${databaseName}.table_name ALTER COLUMN column_name varchar(255) NULL`)
```

finally, I took the query and ran it directly in MSSQL and it works fine

**Comment by imnotjames** [comment]
If you used the SQL Server studio - it does some magic to fix some queries.  I'd suggest quoting all database names / table names / etc.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
