### ISSUE TITLE
dropUniqueConstraint seems not to work

### ISSUE THREAD

**Issue by davran-siv** [typeorm/typeorm#5568]
**Issue type:**

[x] question
[x] bug report

**Database system/driver:**
[x] `postgres`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

I'm trying to add a unique constraint.

`queryRunner.createUniqueConstraint` works as expected.

But `queryRunner.dropUniqueConstraint` throws `error: error: constraint "undefined" of relation "user" does not exist.`

Here is my migration

```ts
import { MigrationInterface, QueryRunner, TableUnique } from 'typeorm'

export class UpdateUserTable1582288403747 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.createUniqueConstraint('user', new TableUnique({ columnNames: ['email'] }))
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.dropUniqueConstraint('user', new TableUnique({ columnNames: ['email'] }))
  }

}
```

**Comment by matheusalbino** [comment]
It's like when do you need to use `dropForeingKeys`, these functions drop based on the generated name. If you don't have generated a name for unique constraints or foreign keys, you need another way to drop these cases.

I make these scripts to solve the necessity of my project, and the new unique constraints and foreign keys created on the project have a name to don't need this more. And names on these cases help to identify query errors.

See bellow my helper functions:
```ts
export async function dropForeignKeys(queryRunner: QueryRunner, tableName: string, columnNames: string[]) {
  const table = await queryRunner.getTable(tableName);

  for (const foreignKey of table.foreignKeys) {
    for (const columnName of columnNames) {
      if (foreignKey.columnNames.includes(columnName)) {
        await queryRunner.dropForeignKey(tableName, foreignKey.name);
      }
    }
  }
}

export async function dropUniqueConstraints(queryRunner: QueryRunner, tableName: string, columnNames: string[]) {
  const table = await queryRunner.getTable(tableName);

  for (const uniqueConstraint of table.uniques) {
    for (const columnName of columnNames) {
      if (uniqueConstraint.columnNames.includes(columnName)) {
        await queryRunner.dropUniqueConstraint(tableName, uniqueConstraint.name);
      }
    }
  }
}

```

**Comment by imnotjames** [comment]
yeah, you can't create a new one - it has to know that it exists, too.
