### ISSUE TITLE
MSSQL Connection to Specific DB Engine

### ISSUE THREAD

**Issue by mitchell44** [typeorm/typeorm#557]
Hello,

Just updated from 0.1.0-Alpha.4 to 0.1.0-Alpha.17 and since that upgrade I've been having issues connection to a specific MS SQL DB Engine.  Seem to be getting no where with my troubleshooting.

I was able to specify on ``host`` where the ``DBENGINE`` name is, since I have more than one instance of MS SQL Server installed, It seems I need to specify it.

This is the connection I had before, which no longer seems to work:
```
type: "mssql",
host: "localhost\DBENGINE",
port: "3306",
username: "root",
password: "root,
database: "TEST",
```
Thanks!

**Comment by pleerock** [comment]
I have updated mssql package support to 4.x.x, did you update mssql version? Most probably you have issues because of new mssql version, can you checkout their documentation if its something breaking in 4.x.x ?

**Comment by mitchell44** [comment]
I have updated to mssql to 4.0.4, checked the updated v4 docs, as well as the breaking changes, other than changing the name from Connection to ConnectionPool, there doesnt seem like anything has changed.

**Comment by pleerock** [comment]
hmmm strange there were not any changes that could affect this functionality. try each version between 0.1.0-Alpha.4 and 0.1.0-Alpha.17 and find the first version that breaks for you

**Comment by mitchell44** [comment]
Can you please tell me the alpha version you switched the mssql driver from 3.X.X to 4.X.X?

**Comment by pleerock** [comment]
somewhere around `0.1.0-alpha.8 - 0.1.0-alpha.9`

**Comment by mitchell44** [comment]
So downgraded back to 0.1.0-alpha.4, everything worked, updated to alpha.5 and it seems to break my createConnection string.

Currently on mssql 3.3.0.

Everything worked whenever I moved back to 0.1.0-alpha.4.

Here is my connection options that worked for .4 and not .5-.8
```
      driver: {
          type: process.env.DB_DIALECT,
          host: process.env.DB_HOST,
          port: process.env.DB_PORT,
          username: process.env.DB_USERNAME,
          password: process.env.DB_PASSWORD,
          database: process.env.DB_NAME
      },
      logging: {
          logOnlyFailedQueries: true
      },
      autoSchemaSync: true,
      entities: [ __dirname + '/entities/*{.js,.ts}' ],
      migrations: [ __dirname + '/migrations/*{.js,.ts}' ],
      subscribers: [__dirname + '/subscribers/*{.js,.ts}'],
      cli: {
        migrationsDir: __dirname + '/migrations',
        entitiesDir: __dirname + '/entities',
        subscribersDir: __dirname + '/subscribers'
      }
```

I did see an issue where you mentioned to rework the connection like it is listed below, unfortunately that did not work either.

```
      
          type: process.env.DB_DIALECT,
          host: process.env.DB_HOST,
          port: process.env.DB_PORT,
          username: process.env.DB_USERNAME,
          password: process.env.DB_PASSWORD,
          database: process.env.DB_NAME      
      logging: {
          logOnlyFailedQueries: true
      },
      autoSchemaSync: true,
      entities: [ __dirname + '/entities/*{.js,.ts}' ],
      migrations: [ __dirname + '/migrations/*{.js,.ts}' ],
      subscribers: [__dirname + '/subscribers/*{.js,.ts}'],
      cli: {
        migrationsDir: __dirname + '/migrations',
        entitiesDir: __dirname + '/entities',
        subscribersDir: __dirname + '/subscribers'
      }
```

The error I am getting is:

```
error TS2322: Type '{ driver: { type: any; host: any; port: any; username: any; password: any; database: any; }; logg...' is not assignable to type 'ConnectionOptions'.
  Type '{ driver: { type: any; host: any; port: any; username: any; password: any; database: any; }; logg...' is not assignable to type 'MongoConnectionOptions'.
    Property 'type' is missing in type '{ driver: { type: any; host: any; port: any; username: any; password: any; database: any; }; logg...'.
```

**Comment by DavidPMacNeil** [comment]
I'm getting this issue as well. I'd like to incorporate FK & cascades which should be working with mssql from the later releases as well.

**Comment by DavidPMacNeil** [comment]
It looks like the changes affected dynamic loading of values for connection. Where before I could get all values from .env, now I have to manually specify a couple of them.

Example:
```
createConnection({
        type: 'mssql', // Used to be process.env.DB_DIALECT
        host: process.env.DB_HOST || 'localhost\\MSSQLSERVER',
        port: 1433, // Used to be process.env.DB_PORT
        username: process.env.DB_USERNAME || 'db_user',
        password: process.env.DB_PASSWORD || 'db_password',
        database: process.env.DB_NAME || 'TEST',
        logging: {
            logOnlyFailedQueries: true
        },
        autoSchemaSync: true,
        entities: [ __dirname + '/entities/*{.js,.ts}' ],
        migrations: [ __dirname + '/migrations/*{.js,.ts}' ],
        subscribers: [__dirname + '/subscribers/*{.js,.ts}'],
        cli: {
          migrationsDir: __dirname + '/migrations',
          entitiesDir: __dirname + '/entities',
          subscribersDir: __dirname + '/subscribers'
        }
      }).then(async connection => { ... }
```

Any chance we could work on allowing dynamic loading of values for connections and columns. I'd like to be able to package my application to be used for multiple DB engines, and not lock it into one.

**Comment by pleerock** [comment]
Wait, Im a bit confused. What is this issue about? What is a problem? 

If problem is this:

```ts
error TS2322: Type '{ driver: { type: any; host: any; port: any; username: any; password: any; database: any; }; logg...' is not assignable to type 'ConnectionOptions'.
  Type '{ driver: { type: any; host: any; port: any; username: any; password: any; database: any; }; logg...' is not assignable to type 'MongoConnectionOptions'.
    Property 'type' is missing in type '{ driver: { type: any; host: any; port: any; username: any; password: any; database: any; }; logg...'.
```

then its because you are using `process.env.DB_DIALECT` - in "type" you should specify what database type are you using not as a simple string, but as special literal string type, .e.g. "mssq". Otherwise you have to cast things to "any".

> Any chance we could work on allowing dynamic loading of values for connections and columns. I'd like to be able to package my application to be used for multiple DB engines, and not lock it into one.

not sure if I understood you. Do you want to have multiple connections to be loaded from environment vars, or what?

**Comment by DavidPMacNeil** [comment]
Yes, before driver was removed from options, specifying the dialect through .env was fine. So, you are saying setting the env variable to ```<any>process.env.DB_DIALECT``` can solve that issue?

I don't mean multiple connections to multiple DB's at the same time, although one to Web SQL + local DB engine could be quite useful. What I am talking about is deploying a node Application which uses TypeORM, in a way that it can easily be configured for any of the supported DB engines. For the columns, for example, if it is set to be a string, ```'nvarchar'``` will work fine for mssql, but if I try to use the same column on postgres will it just fail? 

Thanks

**Comment by pleerock** [comment]
> <any>process.env.DB_DIALECT can solve that issue?

yeah or maybe cast whole connection if needed. But I still suggest to not store this var in env. Simply set it to "mssql" if you are using mssql. Don't do things you don't _really_ need.

> For the columns, for example, if it is set to be a string, 'nvarchar' will work fine for mssql, but if I try to use the same column on postgres will it just fail?

right, thats a price of having all database supported types. If you don't like it - you have two choices: you can not use specific types, and left it simply `@Column() str: string`; or you can create two separate models - one for mssql another for postgres.

But in practice there is almost 0% cases people _really_ need it.

If you want to have multiple connections you simply need to use ormconfig.json or yml - store connections in file which is more convenient way to do.

**Comment by pleerock** [comment]
@mitchell44 what is your issue right now?

**Comment by mitchell44** [comment]
@pleerock I've updated to alpha.23 and everything seems to be working fine, So all is good from my end. Thanks you.

**Comment by developernaidu** [comment]
Error during Mssql Data Source initialization ConnectionError: Failed to connect to 172.30.4.55:1433 - 38050000:error:0A00014D:SSL routines:tls_process_key_exchange:legacy sigalg disallowed or unsupported:c:\ws\deps\openssl\openssl\ssl\statem\statem_clnt.c:2263:

    at connectListener (C:\vscode\sample-op-reporting\node_modules\mssql\lib\tedious\connection-pool.js:70:17)
    at Connection.onConnect (C:\vscode\sample-op-reporting\node_modules\tedious\src\connection.ts:1725:9)
    at Object.onceWrapper (node:events:629:26)
    at Connection.emit (node:events:514:28)
    at Connection.emit (C:\vscode\sample-op-reporting\node_modules\tedious\src\connection.ts:1868:18)
    at Connection.socketError (C:\vscode\sample-op-reporting\node_modules\tedious\src\connection.ts:2189:12)
    at C:\vscode\sample-op-reporting\node_modules\tedious\src\connection.ts:3169:25
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ESOCKET',
  originalError: ConnectionError: Failed to connect to 172.30.4.55:1433 - 38050000:error:0A00014D:SSL routines:tls_process_key_exchange:legacy sigalg disallowed or unsupported:c:\ws\deps\openssl\openssl\ssl\statem\statem_clnt.c:2263:

      at Connection.socketError (C:\vscode\sample-op-reporting\node_modules\tedious\src\connection.ts:2189:28)
      at C:\vscode\sample-op-reporting\node_modules\tedious\src\connection.ts:3169:25
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'ESOCKET',
    isTransient: undefined
  }
}

**Comment by developernaidu** [comment]
i am getting this error to connect MSSQL
