### ISSUE TITLE
Migrations with Separate Entity Definition

### ISSUE THREAD

**Issue by pedropinheiro75** [typeorm/typeorm#5576]
Before I would like to thank you for the great job done here. 

**Issue type:**

[X] question
[?] bug report

**Database system/driver:**

[X] `postgres`

**TypeORM version:**

[X] `latest`

**Issue body:**

I am trying to [update my database](https://typeorm.io/#/migrations) using the entities with [separate entity definition](https://typeorm.io/#/separating-entity-definition).

The database isn't updated either with the option `synchronize = true` or with the command:

> ts-node ./node_modules/typeorm/cli.js migration:generate -n CreateDatabase

which generates an empty migration file.

What am I forgetting?

**Steps to reproduce or a small repository showing the problem:**

> ormconfig.json

``` json
{
  "type": "postgres",
  "host": "localhost",
  "port": 5432,
  "username": "postgres",
  "password": "secret",
  "database": "app",
  "entities": ["src/**/entities/*.entity.ts"],
  "migrations": ["src/database/migrations/*.ts"],
  "cli": {
    "migrationsDir": "src/database/migrations"
  },
  "synchronize": true
}
```

> topic.entity.ts

```ts
export class Topic {
  title: string
}

```

> topic.schema.ts

```ts
import { EntitySchema, EntitySchemaColumnOptions } from 'typeorm'
import { Topic} from '../topic.entity'

export const TopicSchema = new EntitySchema<Topic>({
  name: 'topics',
  target: Topic,

  columns: {
    title: {
      name: 'title',
      type: 'text',
      nullable: true,
    } as EntitySchemaColumnOptions,
  },
})

```

**Comment by kyle-mccarthy** [comment]
In your ormconfig.json file, the entities field should have your `TopicSchema` rather than your `Topic`. Basically, when using `EntitySchema`s you want to treat them as if they were entities created with the `@Entity` decorator.

**Comment by pedropinheiro75** [comment]
You're right. It worked. 
Thanks @kyle-mccarthy.
