### ISSUE TITLE
Connect to redis cluster with TLS enabled

### ISSUE THREAD

**Issue by thellimist** [typeorm/typeorm#5577]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
    cache: {
      type: "redis",
      options: {
        host: process.env.REDIS_HOST,
        port: process.env.REDIS_PORT,
        password: process.env.REDIS_PASSWORD,
      },
      duration: 1000 * 3, // 3 seconds
    },
```

The following does not work on a redis cluster with TLS enabled. Is there a way to achieved this?

**Comment by DMeechan** [comment]
@thellimist have you tried using [ioredis](https://github.com/luin/ioredis#tls-options) with the `tls: {}` setting?

I haven't tried this myself but came across [this example](https://github.com/luin/ioredis/issues/664#issuecomment-410324534) from ammohand.

I think this is what the equivalent for TypeORM looks like:

```javascript
{
  cache: {
    type: "ioredis/cluster",
    options: {
      startupNodes: [
        {
          host: "clustercfg.xxxxxencr.rqeqka.euw1.cache.amazonaws.com",
          port: "6379",
        },
      ],
      options: {
        tls: {},
        // these other options are from the TypeORM docs example
        // on connecting to a cluster using ioredis:
        scaleReads: "all",
        clusterRetryStrategy: function (times) {
          return null;
        },
        redisOptions: {
          maxRetriesPerRequest: 1,
        },
      },
    },
  },
  // other connnection options...
};
```

**Comment by thellimist** [comment]
I did not. I'm using `const redis = require('redis');` package. I currently disable TypeORM cache'ing. Would prefer to use only a single package for redis.

**Comment by goktugyil** [comment]
I needed to add this:

```
        cache: {
            type: 'redis',
            options: {
                username: process.env.REDIS_USERNAME,
                host: process.env.REDIS_HOST,
                port: process.env.REDIS_PORT,
                password: process.env.REDIS_PASSWORD,
                tls: process.env.REDIS_TLS == 'true' ? true : false,
            },
            duration: 1000 * 3, // 3 seconds
        },
```
