### ISSUE TITLE
Provide driver option for react-native

### ISSUE THREAD

**Issue by likern** [typeorm/typeorm#5584]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

## Support custom drivers for React Native
I've found several critical bugs in https://github.com/andpor/react-native-sqlite-storage [[1](https://github.com/typeorm/typeorm/issues/5564), [2](https://github.com/andpor/react-native-sqlite-storage/issues/410)] and [in Android SQL API itself](https://stackoverflow.com/questions/20911760/android-how-to-query-sqlitedatabase-with-non-string-selection-args/23159664).
To solve issues quickly I had to create my own fork https://www.npmjs.com/package/@breeffy/mobbly.

## Mobbly advantages

1. Backwards compatible with react-native-sqlite-storage (it's a fork)
2. Uses https://github.com/requery/sqlite-android which solves [issue with Android SQL API](https://stackoverflow.com/questions/20911760/android-how-to-query-sqlitedatabase-with-non-string-selection-args/23159664).
3. Uses bundled sqlite version - you need to worry only about one version of SQLite and no need to support nuances and differences between different SQLite versions provided by different Android versions.
4. Support of modern versions (now it is SQLite 3.31.0, while react-native-sqlite-storage only has 3.8.x)
5. Support wide range of extensions out-of-the-box, while default Android SQLite doesn't support extensions
6. Fixes some critical bugs with incorrect results of SQL queries - my investigation and analysis could be found here https://github.com/andpor/react-native-sqlite-storage/issues/410
7. I'm extensively using TypeORM myself, so there is more chances to discover and fix bugs in typeorm-react-native.

## Proposition
I propose to add **driver** option for React Native driver to have ability to provide custom driver, instead of directly importing only **react-native-sqlite-storage**
```typescript
this.sqlite = require("react-native-sqlite-storage");
```

It's the only option because metro bundler which is used instead of webpack by React Native **doesn't support dynamic imports**. It is not possible to require module like this
```
let moduleName = "@breeffy/mobbly"
this.sqlite = require(moduleName)
```
If try to require multiple modules using direct import
```
if (condition) {
  this.sqlite = require("react-native-sqlite-storage")
} else {
  this.sqlite = require("@breeffy/mobbly")
}
```
metro bundler **will still bundle both modules** (but these drivers are expected to substitue each other and shouldn't be used together).

Also this approach leads to name collisions (because of how React Native imports native modules):
```java
import org.pgsqlite.SQLitePlugin;
import com.breeffy.mobbly.SQLitePlugin;
... later ...
new SQLitePlugin(), // from react-native-sqlite-storage
new SQLitePlugin(), // from mobbly
````

But if **provide driver directly** as option to **createConnection** - this approach should work.
TypeORM could provide minimal interface to which drivers should comply with.

**Comment by imnotjames** [comment]
This should probably just be a separate driver.  However, looking a bit at this - it doesn't seem like there's been much traction with the fork.

If you'd like to make this happen via a PR or related please feel free to open a PR & we'll review it.  

However, I'll be closing out this issue as we won't be moving forward with it directly.

**Comment by LaGregance** [comment]
I'm strongly interested by your driver since the new typeorm version support the driver param. But your npm repository isn't exists anymore. Is there any other place I can find your driver ?
Thanks.

**Comment by likern** [comment]
> I'm strongly interested by your driver since the new typeorm version support the driver param. But your npm repository isn't exists anymore. Is there any other place I can find your driver ? Thanks.

It's not supported anymore.

I recommend using https://github.com/ospfranco/react-native-quick-sqlite. It's better.
