### ISSUE TITLE
How to use orUpdate to implement such SQL statements (b=b+1)

### ISSUE THREAD

**Issue by shengxq** [typeorm/typeorm#5588]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.22` (or put your version here)

INSERT INTO aaa (a, b)
VALUES (1, 2) ON DUPLICATE KEY UPDATE b = b + 1

请问这样的sql语句,怎么用orUpdate实现
How to use orUpdate to implement such SQL statements

**Comment by artoodeeto** [comment]
So what you're trying to achieve here is. You want to update if an insert is not possible because of some constraints or if the key is already in the database?

Have you checked [save method](https://typeorm.io/#/repository-api) from repo-api or entity manager?
