### ISSUE TITLE
how to use multiple join statements for query builder which are generated dynamically?

### ISSUE THREAD

**Issue by Yasukity** [typeorm/typeorm#5590]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18`

**Steps to reproduce or a small repository showing the problem:**

I'm trying to write multiple join statements with querybuilder.
Join statements are to be generated dynamically, hence the number of them is sometimes 1, and sometimes 3 and so on.
With general use of join methods, I'm wondering it might not be possible to achieve this goal.
Do we have alternatives for this purpose?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by artoodeeto** [comment]
@Yasukity hello can you post some code so and what do you want to achieve. Just a snippet will do. thanks.

**Comment by Yasukity** [comment]
I'm sorry for late responding @artoodeeto 
below is what I would like to do:
`
    await getConnection()
     .createQueryBuilder(table, "alias")
     .select("*")
     .innerJoin()
     .innerJoin()
     if(condition) { // want to achieve something like this
       .innerJoin()
     }
     ...
`
here I would like to call innerJoin() 3 times when condition is true, otherwise 2 times.

**Comment by artoodeeto** [comment]
@Yasukity cool man but I'm sure it's not allowed. You have to rework your logic on that one. I dont think there's something conditional joins at a database level. You can try and make a raw query. You can also check this one how they do it in raw sql. [LINK](https://stackoverflow.com/questions/1255492/conditional-join-in-mysql)

**Comment by JClackett** [comment]
this is possible, just make a variable for the query object:

```
const query = await getConnection()
   .createQueryBuilder(table, "alias")
   .select("*")
   .innerJoin()
   .innerJoin()

if (condition) {
	query.innerJoin()
}

// later on

const data = await query.getMany() // or whatever
```

**Comment by artoodeeto** [comment]
@Yasukity heyy my dude @JClackett helped out and I think this will work. Why didnt I think of this. lols I was solving this kind of problem in Rails a week ago. lools thanks man JC

**Comment by Yasukity** [comment]
@JClackett 
Thank you for sharing the solution, which is something I've been expecting.
And also thank you @artoodeeto for coordinating things:)
