### ISSUE TITLE
How to test BeforeInsert with a mocked Repository

### ISSUE THREAD

**Issue by devniel** [typeorm/typeorm#5593]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi, I'm trying to check that the method decorated with @BeforeInsert in my User entity is called, but with a mocked repository it's not working because it seems that @BeforeInsert it's called when doing the actual insertion in the database, so maybe I need to mock one lower layer. What do you think ? (actually I'm trying to do this with nestjs).

**Comment by ChristianMurphy** [comment]
see https://github.com/typeorm/typeorm/issues/1267 for the general discussion on testing

**Comment by devniel** [comment]
I think it's kind of tricky, because I will need to play with the listeners used by the [Broadcaster](https://github.com/typeorm/typeorm/blob/dd7339588473f80814c0ef74a8320eadf6589193/src/subscriber/Broadcaster.ts) and the metadata, is there a function to get the metadata directly from the class without a connection to a DB ?

**Comment by artoodeeto** [comment]
@devniel  we have the same problem. My work around is query after the hooks and check the result. I know its more work. :cry:

**Comment by devniel** [comment]
@artoodeeto I was able to get it 😁, I have created a testing module to make it easy to integrate in new tests https://github.com/devniel/nestjs-typeorm-testing, don't hesitate to contribute if you want.

**Comment by artoodeeto** [comment]
@devniel thanks man. This works even though im not using nestjs?

**Comment by devniel** [comment]
@artoodeeto I have updated the module so it can be used in non-nestjs projects. there is an example here https://github.com/devniel/example-typeorm-testing.

**Comment by artoodeeto** [comment]
@devniel you are my hero. much love man! :heart:

**Comment by bhishp** [comment]
The way I approached this is to just call the beforeInsert function on an instance of the entity directly in a test file and then test the object shape after calling the function. E.g.

```
// the entity
export class Meta {
  @Column('varchar', { name: 'META_QUALITY_CD', nullable: true, length: 50 })
  metaQualityCd!: string | null;
  
  @Column
   ...

  @BeforeInsert()
  generateInsertMeta() {
    const now = new Date(new Date().toUTCString());
    this.metaQualityCd = null;
    this.metaActionCd = MetaActionCD.Insert;
    this.metaCreatedDttm = now;
    this.metaCreatorNm = WEBAPP_USER_NAME;
    this.metaChangedDttm = now;
    this.metaChangedByNm = WEBAPP_USER_NAME;
  }
}
```

The test

```
describe('MetaEntity', () => {
  describe('beforeInsert', () => {
    it('should set meta fields as expected', () => {
      const meta = new Meta();
      MockDate.set('2020-01-22');
      const now = new Date();

      const expected: Partial<Meta> = {
        metaQualityCd: null,
        metaActionCd: MetaActionCD.Insert,
        metaCreatedDttm: now,
        metaCreatorNm: WEBAPP_USER_NAME,
        metaChangedDttm: now,
        metaChangedByNm: WEBAPP_USER_NAME,
      };

      // just call the BeforeInsert function directly (it is simply an instance function) and then assert the instance shape
      meta.generateInsertMeta();

      expect(meta).toEqual(expected);
    });
  });
});
```

Not sure if this will cover all cases but IMO it should be sufficient just to test the method like this rather than needing to involve the rest of TypeORM at all (by mocking typeorm connection all you are doing really is testing typeORMs behaviour for ensuring that the decorators are called as expected?)

**Comment by bhishp** [comment]
I had a go with playing with mocks to see if something like that could be achieved and got _something_ working in the end but I think it was more of a interesting exercise than something I'm actually going to keep in our code as it feels a little bit hacky

```ts
// inside test.ts

interface ListnerMockMap {
  BeforeInsert?: string;
  BeforeUpdate?: string;
}

jest.mock('typeorm', () => {
  // we have to define the map within the mock function because we can't access anything outside of the mock (ReferenceError: Cannot access 'x' before initialization)
  const listenerMap: ListnerMockMap = {};

  return {
    Column: jest.fn(),

    // We mock the decorator functions to track the function name each decorator is assigned too (in reality these should be lists, rather than a single string as you could decorate multiple methods)
    BeforeInsert: jest.fn(() => (_: any, fnName: string) => {
      listenerMap.BeforeInsert = fnName;
    }),

    BeforeUpdate: jest.fn(() => (_: any, fnName: string) => {
      listenerMap.BeforeUpdate = fnName;
    }),

    // the hacky bit, we modify the the shape of the typeorm module to access our map within the test file
    listenerMap,
  };
});


import * as typeorm from 'typeorm';
// We take the map exported above but the compiler will complain because listenerMap is not a valid export from 'typeorm'
// @ts-ignore
const { listenerMap } = typeorm;

...


it('should call the correct BeforeInsert method', () => {
  const entity = new Entity();
  const beforeInsertMethodNm = listenerMap.BeforeInsert!;
  (meta[beforeInsertMethodNm as keyof Entity] as Function)();
  expect(entity).toEqual(modifiedEntity);
});
```
