### ISSUE TITLE
Type safety when using query builder

### ISSUE THREAD

**Issue by pdashford** [typeorm/typeorm#5594]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When using the query builder and using join operator's would it be possible that you can get the intellisence to show the field names etc, how a large complex database and have to try and remember all the relevant field names and joins.

**Comment by imnotjames** [comment]
We do some amount but because you can set the aliases yourself it's not really possible to represent that with types while allowing flexibility.
