### ISSUE TITLE
how to update specified Field after query all rows option

### ISSUE THREAD

**Issue by wowtrxqn** [typeorm/typeorm#5596]
**Issue type:**

[ ] question

**Database system/driver:**

[ ] `oracle`

**TypeORM version:**

[ ] `latest`

**Steps to reproduce or a small repository showing the problem:**
what i want is updateing the specified filed .
ex:
my select rows return 
[
{title:'first record',flag:'N'},
{title:'seconf record',flag:'N'},
{title:'thirdrecord',flag:'N'},
]

so i want to update flag to 'Y' from all those query back,
how to do?

**Comment by artoodeeto** [comment]
have you tried?

```ts
await getConnection()
    .createQueryBuilder()
    .update(Post)
    .set({ 
        flag: "Y", 
    })
    .where("flag = :flagNewVal", { flagNewVal: 'N' })
    .execute();
```

**Comment by wowtrxqn** [comment]
> have you tried?
> 
> ```ts
> await getConnection()
>     .createQueryBuilder()
>     .update(Post)
>     .set({ 
>         flag: "Y", 
>     })
>     .where("flag = :flagNewVal", { flagNewVal: 'N' })
>     .execute();
> ```

thanks，it work

**Comment by artoodeeto** [comment]
I gotchu! close this if you don't have any issues. :smile:
