### ISSUE TITLE
Is it valid to omit "type" variable from typeFunction (in relation definition) arguments?

### ISSUE THREAD

**Issue by Ishidall** [typeorm/typeorm#5597]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

=====

Hi, I'm wondering if the argument "type" can be omitted from typeFunction arguments.

In the [doc](https://typeorm.io/#/relations/cascades), all of the relations are defined like below.

```ts
import {Entity, PrimaryGeneratedColumn, Column, ManyToMany} from "typeorm";
import {Question} from "./Question";

@Entity()
export class Category {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToMany(type => Question, question => question.categories)
    questions: Question[];

}
```

And using linter like ESLint, "type => Question" 's "type" is complained as an unused variable.

So I'm thinking of declaring relations like below.

```ts
@ManyToOne(
  () => SomeType, // <- type replaced with ()
  someType => someType.relatedEntities
)
```

As relation decorators are declared as below, I assume that "type" variable declaration is unnecessary, but without confidence.

```ts
export declare function ManyToOne<T>(typeFunctionOrTarget: string | ((type?: any) => ObjectType<T>), options?: RelationOptions): Function;
```

Sorry if it's already documented somewhere, though I couldn't find it.

Thanks in advance!

**Comment by khusaeriz** [comment]
i think its ok to omit type variable, it's just for make it easier to read the code

**Comment by imnotjames** [comment]
Answered.  Closing.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
