### ISSUE TITLE
Always getting error guessing column type when trying to use cli app with typeorm

### ISSUE THREAD

**Issue by idchlife** [typeorm/typeorm#560]
ColumnTypeUndefinedError: Column type for PlayerLog#message is not defined or cannot be 
     guessed. Try to implicitly provide a column type to @Column decorator.

I'm getting those errors about many columns. I don't quiet understand what is happening here.
Every time I fill one hole - another column cannot be guessed. Of course explicitly defining every time will be a huge time and energy waste, since one of the benefits of typeorm - it's ability to get typescript types for database types.

Version 0.11

When using it with routing-controllers - everything is fine.

**Comment by idchlife** [comment]
Closed.

Forgot to import reflect-metadata 🤦‍♂️

**Comment by saptaksengupta** [comment]
I have imported reflect-metadata in my main.ts file but still getting the same error. can you please help me up like how should i import it properly.

**Comment by Eileen0917** [comment]
Hi @saptaksengupta ,

I have same problem.
Did you solve it now?
Can you tell me how should I import it properly?

Thanks!

**Comment by gaurav341** [comment]
@Column() must set a type,like  @Column('text',{nullable:true})
