### ISSUE TITLE
Error connacting to Hana instance/ Error in Driver/Pool?

### ISSUE THREAD

**Issue by mathiasmaerker** [typeorm/typeorm#5602]
**Issue type:**

[x ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `sap`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hey all, I have a question/bugreport about the Sap Driver. Did the driver actually work ever on any Hana instance? I can't connect to any Hana Instance at all and I think the problem relates to the npm module `hdb-pool`. This module seems to ignore additional properties which are as of now mandatory like `encryption`etc. See [issue](https://github.com/ckyycc/hdb-pool/issues/2) 

A minimal example would be any Hana Database hosted on Sap Cloud Platform. I have no Problems connecting with the standard Hana Client `@sap/hana-client` but trying to connect with `hdb-pool or typeorm` does not work at all with the same settings I use for Hana-client. My guess is that the encryption flag is missing/not passed on to the hana-client and therefore no connection is created

Could anybody confirm?

Best regards
Mathias

**Comment by pleerock** [comment]
@Szbuli can you please help here?

**Comment by Szbuli** [comment]
I have contacted the hdb-pool author a while ago, and thought that the fix would be out much faster.

I have created a pull request in hdb-pool, if you can, please apply a patch with the changes in the pull request [(pull-request)](https://github.com/ckyycc/hdb-pool/pull/3)

**Comment by Szbuli** [comment]
FYI, you will also need to use the "ca" param for the certificate.

**Comment by mathiasmaerker** [comment]
Hi @Szbuli, 
first of many thanks for your help and engagement 👍 

I evaluated a litte more and here are my findings:

+ some parameters are ignored like `validateCertificate` they never seems to be passed on to the driver or `hdb-pool`
+ what is the difference between `ca and cert`? in standard Hana driver I pass the params like:
 ```  
const params = {
    serverNode: `${credentials.host}:${credentials.port}`,
    encrypt: true,
    sslValidateCertificate: true,
    sslTrustStore: credentials.certificate,
    sslCryptoProvider: 'openssl',
    uid: 'system',
    pwd: 'pwd!'
  }
```
How would you do it with typeorm sap driver? And maybe name the things like in the driver?

Otherwise it does work sometimes, but sometimes not, I can't really figure out why it is working at times and then again not, somehow there is a timeout fired by `Request.js` even thou the connection is established and has no error, nor sure why that is, I try to evaluate it a little more but generally I think this is the right direction..

If you could provide me with the settings for the ConnectionOption that would be great!

Regards
Mathias

**Comment by Szbuli** [comment]
I am pretty sure the connection cannot be established without the encrypt flag. You can provide any extra parameter in the "extra" object. Those will be passed to the driver as well. 

I hope in the next few days a new hdb-pool version will be released, and every parameter will be passed to the hana-client.

**Comment by Szbuli** [comment]
There is a default timeout in the pool, maybe try to increase it.

**Comment by Szbuli** [comment]
The new version of hdb-pool is released, please have a try with that!

**Comment by mathiasmaerker** [comment]
Hi @Szbuli, thanks a lot it now does work but only if I use the `extra: {}` property of typeorm. According to the documentation that property should/will be deprecated? SO maybe all the options should go into `SapConnectionOptions`? But for the time being I am very happy about the speed and support and that it does work. 🙇 So I think this issue can be closed.

**Comment by pleerock** [comment]
@Szbuli right now I have issue with connection to hana... If I remove this line from SapDriver: ` if (this.options.database) dbParams.databaseName = this.options.database;` - it works. I'm trying to understand why I have this problem and `hdb-pool` doesn't seem to have this option (databaseName) in their docs

**Comment by derickmr** [comment]
Hey @mathiasmaerker,

I am facing a similar issue. There is no error when creating the connection, but is returns me a Request timeout when save() method from connection manager. Can you share your solution please?

**Comment by mathiasmaerker** [comment]
Hi @derickmr about what solution do you talk exactly? Do you have problems connecting to Hana or saving an entity?

**Comment by mathiasmaerker** [comment]
@derickmr what you can do is take a look here [here](https://github.com/mathiasmaerker/typeorm-hana-performance-issue) you need a `default-env.json` with the correct values, please check the documentation of `@sap/xsenv` package. But this repo works, if you need additional assistance, ping me.

Regards Mathias

**Comment by derickmr** [comment]
Hello @mathiasmaerker,

I followed your repo as an example to the Hana connection and I was able to make it work. Thanks a lot for your inputs and help!

Regards, Derick

**Comment by stefania-santimbrean** [comment]
Hello @mathiasmaerker , @derickmr ,

Are you working with an HDI container service instance of HANA Cloud or HANA Service? I'm also seeing the same error, too.

Regards,
Stefania

**Comment by mathiasmaerker** [comment]
Yes I am working with HDI Container Service, it is basically the same, here is my config options

```javascript
 public getConnectionOptions(): ConnectionOptions {
    const hdiCredentials = serviceCredentials({ name: process.env.CONNECTION_SERVICE_NAME }) as HdiCredentials

    return {
      name: 'hdi_shared',
      type: 'sap',
      host: hdiCredentials.host,
      port: parseInt(hdiCredentials.port),
      username: hdiCredentials.user,
      password: hdiCredentials.password,
      logging: process.env.DB_LOG_LEVEL as LoggerOptions,
      synchronize: false,
      encrypt: true,
      extra: {
        sslValidateCertificate: true,
        sslTrustStore: hdiCredentials.certificate,
        sslCryptoProvider: 'openssl',
      },
      schema: hdiCredentials.schema,
      // dropSchema: true,
      entities: [LearningHistory, LearningPlan, Curriculum, Item, Offering, Label, Enrolement, User],
    }
  }
```

The main difference here is what kind of service plan you use, in case it is `hsi-shared` you can't use typeorm schema/entity creation, you have to do it via `@sap/hdi-deploy`. 
Hope it helps otherwise ping me.

Regards

**Comment by stefania-santimbrean** [comment]
Hello @mathiasmaerker ,

Thanks so much for the quick response and the config. I'm still getting timeout, but I am using `hdi-shared` plan so this might be the problem. I was expecting at least an error telling me no table found given the circumstances, but it's just timing out.

Do you mean that I can't create a migration for HANA and have to use `@sap/hdi-deploy` instead?

Is the typeorm schema/entity creation working with a service plan `schema` ?

Thank you so much,
Regards,
Stefania

**Comment by mathiasmaerker** [comment]
Hi @stefania-santimbrean service plan schema will work for entity creation etc. but check your project for given requirements, e.g. some SAP Solutions require you to use hdi-shared (Analytics Cloud f.e.). 
can you please check the dependency `@sap/hana-client` what version are you using? for me only version `2.5.111` does the job, not sure why, on windows at least all higher versions don't work, but I didn't have time to evaluate

**Comment by stefania-santimbrean** [comment]
Hello @mathiasmaerker , could you also tell me what version of `hdb-pool` are you using?

**Comment by mathiasmaerker** [comment]
@stefania-santimbrean `  "hdb-pool": "0.1.6",`

**Comment by Alamink** [comment]
Hello Mathias @mathiasmaerker ,
I am trying to connect to HANA DB via typeorm and it does not work for me.
Currently, I have HDI container to connect. 
I am able to connect via native sap hana client with same setting ( host, pass, user,port ..etc)
but with typeorm I get time_out issue. 

Thank you,
Alamin

**Comment by mathiasmaerker** [comment]
@Alamink, sorry with the info provided I am not able to help you any further.. Did you check the previous answers?

**Comment by Alamink** [comment]
Thank you @mathiasmaerker for you reply.
So, I am doing very simple app, following this [https://typeorm.io/example-with-express](url) tutorial.
When I run the app, and reach to one of the endpoint "example '/users'". I see the following error:
`*******@C02GX4XXQ6LT user % node src/app.js
Application is up and running
Data Source has been initialized!
query failed: SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName" FROM "MYHANAAPP_HDI_MYHANAAPP_DB_DEPLOYER_79"."user" "User"
error: Error: Request timeout. Request info: (id: 0, creation time: 1662319554980)
    at Request._fireTimeout (/Users/***path***/user/node_modules/hdb-pool/lib/Request.js:114:17)
    at Timeout.<anonymous> (/Users/***Path***/user/node_modules/hdb-pool/lib/Request.js:92:43)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Request timeout. Request info: (id: 0, creation time: 1662319554980)
    at Request._fireTimeout (/Users/***Path***/user/node_modules/hdb-pool/lib/Request.js:114:17)
    at Timeout.<anonymous> (/Users/***Path***/user/node_modules/hdb-pool/lib/Request.js:92:43)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)`

***Path*** = the path of my project

**Comment by mathiasmaerker** [comment]
@Alamink di you have a repo where I could potentially check the issue? otherwise it is difficult to help you. What Kind of service plan are you using in cloudfoundry?

**Comment by luizcarlospedrosogomes** [comment]
news?
