### ISSUE TITLE
0.2.24: beforeUpdate typehints are misleading

### ISSUE THREAD

**Issue by loganyott** [typeorm/typeorm#5607]
**Issue type:**
I'm not sure which one this falls under based on the intention of the code
[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

I have an entity that uses a materialized path.
```ts
@Entity()
@Tree('materialized-path')
export class MyEntity {
  customID: number

  @TreeParent()
  @JoinColumn({ referencedColumnName: 'customID' })
  parent: MyEntity;

  @TreeChildren()
  children: MyEntity[];

  // Added by materialized-path tree, we add it here for type hinting
    readonly mpath: string;
}
```

I was using a Subscriber with `beforeInsert` and `beforeUpdate` to handle some "legacy" code that didn't use the built-in materialized tree feature of typeorm.

Previously, I had a check in `beforeUpdate` like this:
```ts
async beforeUpdate(event: UpdateEvent<MyEntity>) {
  if (!event.entity) {
    return; // No applicable update
  }
}
```
I had some tests that verified this was fired on insert where I would see an empty `entity`. Subsequent updates had the proper parameters though.

With 0.2.24, this is now firing on entity creation with `{ mpath: '1.' }`. So this raises two questions for me
1. I should have asked earlier about the empty `beforeUpdate` fires. Is it intentional that `beforeUpdate` fires on a database insert?
2. The fix in this version was to provide the update changset and not the entire entity. Is that intentional as well?

Here's the relevant change that I _think_ is causing this new behavior: 
https://github.com/typeorm/typeorm/issues/4947

I'm totally fine with the new behavior but for clarity, I think we should at least change the typehint of the `UpdateEvent` to `entity: Partial<Entity>`

**Comment by imnotjames** [comment]
This has been completed in #7783 to fix the type
