### ISSUE TITLE
How do you user `save` method as partial udpate?

### ISSUE THREAD

**Issue by artoodeeto** [typeorm/typeorm#5608]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[X] `0.x.x` ("0.2.22")

**Steps to reproduce or a small repository showing the problem:**

I'm trying to update an entity but when I submit partial data it will do an insert which defeats its purpose. I do it like this.

```ts
private async updateUser(req: ISecureRequest, res: Response): Promise<void> {
    const { id } = req.params;
    const userBody = req.body;
    const entityManager = getManager();
    try {
      const user: User = await User.findOneOrFail(id);
      const updatedUser = User.create({...user, ...userBody });
      res.json({
        meta: {},
        payload: {
          user: await entityManager.save(updatedUser)
        }
      });
    } catch (error) {
      res.status(404).json({
        error
      });
    }
  }
```

`userBody` has only `username` and `password` so I'm trying to update those properties but when I try to update it will throw an error `"message": "Field 'email' doesn't have a default value"`,  and on my entity user I set the email like so:

```ts
@Column({ unique: true, type: 'varchar', length: 50 })
  @IsEmail()
  @IsNotEmpty()
  email!: string;
```
but it should be skipped because, on the documentation, it says that if an entity exists it will update and if not it will insert and yet if the property has a validation it won't be skipped this looks like a bug to me but I'm not sure so I'm asking a question.

**Comment by imnotjames** [comment]
Does the created user entity have an ID?  It's hard to see if this is a bug or not - looks more like a general support request.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
