### ISSUE TITLE
Postgres driver doesn't return any value after upgrading to 0.1.0-alpha.11

### ISSUE THREAD

**Issue by NoNameProvided** [typeorm/typeorm#561]
In one project I had TypeORM with the version `0.1.0-alpha.8`, I have updated it to `0.1.0-alpha.18` and after the update, TypeORM cannot find or query any value. 

Simple calls like `await this.repository.find();` returns empty responses however  there is data in the database. The breaking change itself should had happened between `0.1.0-alpha.8` and `0.1.0-alpha.10`. ( I have downgraded and had the issue in every release between `0.1.0-alpha.10` and `0.1.0-alpha.18`, I could not get `0.1.0-alpha.9` running.) 

Logging the SQL queries shows TypeORM generates the correct SQL queries. (Copy-pasting and running them in [Postico](https://eggerapps.at/postico/) proves the queries are valid and they returns value.)

The issue happens somewhere at the level of the driver.  Simply TypeORM will always reply with an empty array.

TypeORM itself can read from the database tho. Stepping through the bootstrap of the server shows it reads the schema and available tables successfully and other data from the database, it only fails to read entities.

So during bootstrap I see that `result.rows` is populated with data in _PostgresQueryRunner.ts_, however it always empty when calling any `find*` or `QueryBuilder` functions.

When running a query, I can see in the result that  the requested `fields` are computed and available as an array of objects in `result.fields`like:

```json
{
  "name":"category_createdAt",
  "tableID":35239,
  "columnID":1,
  "dataTypeID":1114,
  "dataTypeSize":8,
  "dataTypeModifier":-1,
  "format":"text"
}
```

Any idea what can cause this? It seems a proper sql query is passed but nothing returns. Anyone else experience the same issue?

**Comment by pleerock** [comment]
all tests are passing for postgres its impossible that it do not return value because almost each test would fail in this case. Can you try test this issue in empty project with latest typeorm version?

**Comment by NoNameProvided** [comment]
Ok, so epic fail from my side. However we should highlight this in the docs as this is due to a breaking change! Starting from one of the updates since `0.1.0-alpha.8` (I dont know which), TypeORM will create your tables at `dbname/connection-name/table-name` instead of `dbname/table-name`. So since the default connection name is `default` after upgrading, new tables are created at `db/default/xy` while the old tables with the old data will be left at `db/xy`

@pleerock do we now which version introduced this? Or just lets add this to the breaking changes section of 0.1.0?

**Comment by pleerock** [comment]
wait looks like it was incident change. Where shall they be created by orm? In "default", or as beforein db/xy ?

**Comment by NoNameProvided** [comment]
I think it's boils down to personal preference, I have no issues with having them organized into "folders".

> TypeORM will create your tables at dbname/connection-name/table-name instead of dbname/table-name.

Just tested this a little more and actually then name of the connection doesn't matter, tables always get created in the `default` folder

**Comment by infedelcastro** [comment]
`[PostgressConnectionOptions](https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresConnectionOptions.ts) claims that the default for `schemaName` is public, however, that doesn't appear to be the case as of `0.1.0-alpha.19`. Once I set `schemaName: "public"` in my connection options the connection was acting as it was before updating.

**Comment by pleerock** [comment]
@infedelcastro sorry can you explain what do you mean in details? I didn't understand what you mean

**Comment by pleerock** [comment]
@NoNameProvided can you please investigate more on this question? We need to do something that will be user-friendly, I don't want force them to use schema if they usually don't want doing that. What other orms do? What native pg does?

**Comment by infedelcastro** [comment]
@pleerock the comment above the declaration of `schemaName` on [line 46](https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresConnectionOptions.ts#L46) of `PostgressConnectionOptions` states that the default schema is `public`, which use to be accurate when I started using typeorm a few weeks ago with `0.1.0-alpha.3`. However, [line 729](https://github.com/typeorm/typeorm/blob/92411f80392f2d88a79e189e057753c7805e4011/src/driver/postgres/PostgresQueryRunner.ts#L729) of `PostgresQueryRunner` is setting the default to `default` which changed the behavior of my application. At first, I thought my data had been erased, but really it was just connecting to a different schema. `default` may be the better default schema, but at minimum, that comment is now dangerously out of date. I don't know what the default was before the alpha, but I imagine this may have to be listed as a breaking change.

**Comment by pleerock** [comment]
It was accident change actually. Now we simply need to figure out what is correct name for default schema - should it be "public" or "default"? How do people do in postgres community? Anyone knows?

**Comment by infedelcastro** [comment]
In the postgress course I'm watching on postgress, `public` was the name of the only schema in his example database. Unfortunately I don't have a large exposure to postgress but my limited experience suggests that `public` is a fine default schema.

**Comment by infedelcastro** [comment]
[Section 5.7.2](https://www.postgresql.org/docs/9.1/static/ddl-schemas.html) of the postgress documentation on schema's says that when not specified, `public` is the default schema. So, I think that is strong evidence that `public` should be the default.

**Comment by pleerock** [comment]
Okay I made "public" as default schema in `0.1.0-alpha.22`

**Comment by NoNameProvided** [comment]
Damn, my last few days was pretty busy and I have no time to check on this. It seems I am late to this party. :( Anyway I throw my thoughts here.

I am personally fine with making the `public` schema the default while it stays easily configurable. However one important question was not raised here. In every Postgres database the public schema is accessible by every user. This leads to security issues, so I haven't seen any bigger development company who were using the public schema for their projects. 

While access to the `public` schema can be revoked after user creation, it's considered an error prone thing to do. 

The reasoning behind this from the Postgres docs:

> If you do not create any schemas then all users access the public schema implicitly. This simulates the situation where schemas are not available at all. This setup is mainly recommended when there is only a single user or a few cooperating users in a database. This setup also allows smooth transition from the non-schema-aware world.

So it's a good approach to keep differences low between storage engines in TpyeORM, but I think it's not a good approach for Postgres users.

So since we are in alpha I would vote to break the update one more time :P and start to use a schema by default. (The `default` name is fine for me.)

**Comment by IRCraziestTaxi** [comment]
@pleerock I'm using alpha-32 and schemaName isn't working for me. I created my database using alpha-10, so its schema is "default". Now, however, it wants to use "public", so I tried to set schemaName: "default" in createConnection, but it doesn't appear to be working. Am I missing a step?

**Comment by pleerock** [comment]
@IRCraziestTaxi together with @AlexMesser we aren't able to reproduce your issue. Can you please re-check everything again? If there is still issue on you can you create a simple PR with a test that reproduce this issue?

**Comment by IRCraziestTaxi** [comment]
@pleerock Interesting... I just created a small sample project to attempt to reproduce the issue and I cannot. schemaName works as expected. I will retrace my steps when I can get back to my project this afternoon.

**Comment by IRCraziestTaxi** [comment]
@pleerock I just tried again and it works with no issue. I'm not sure what I did wrong before.

**Comment by pleerock** [comment]
okay, then I'll close it
