### ISSUE TITLE
RANDOM() on joins and skip/take

### ISSUE THREAD

**Issue by devadomas** [typeorm/typeorm#5612]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

QueryFailedError occurs when building query to fetch results with take/skip and join properties.
Example:
```
const users = await User.createQueryBuilder('user')
            .where(where)
            .take(filter.take || 0)
            .orderBy('RANDOM()')
            .leftJoinAndSelect('user.university', 'university')
            .leftJoinAndSelect('user.course', 'course')
            .getMany();
```

Throws error: `QueryFailedError: for SELECT DISTINCT, ORDER BY expressions must appear in select list`.
Once skip/take or joins removed, everything functions as intended.

**Comment by devadomas** [comment]
Sorted by changing take to limit.

**Comment by rtman** [comment]
I found this fix as well, but the docs say:

```
Set's LIMIT - maximum number of rows to be selected. NOTE that it may not work as you expect if you are using joins. If you want to implement pagination, and you are having join in your query, then use instead take method instead.
```
Is there a better way?

**Comment by muriIo** [comment]
For future visitors chasing a solution for this issue, check this out.
The main problem with using 'take()' and 'orderBy('RANDOM()')' is how Postgres will return the rows of the SELECT. Changing to 'limit()' will **only** work if you are not setting joins with **one-to-many** relations. If you are using joins one-to-many relations, 'limit()' will not work as expected, cutting off many rows from the result.
**This is the solution we found in case of using joins one-to-many:**

```
const users = await User.createQueryBuilder('user')
            **_.addSelect('RANDOM()', 'random')_**
            .where(where)
            .take(filter.take || 0)
            **_.orderBy('random')_**
            .leftJoinAndSelect('user.messages', 'message')
            .getMany();
```

In this case, we added a select with 'RANDOM()' in it and giving random as alias for it and using the alias on orderBy expression to avoid the error **QueryFailedError: for SELECT DISTINCT, ORDER BY expressions must appear in select list**.

**Version typeorm => 0.2.41**

I hope this helps someone.

**Comment by nnamdiogbu** [comment]
@muriIo  

Didn't work well for me. "Take()" ended up cutting rows too, so I was getting less records than expected.

```
    const categories = await AppDataSource.getRepository(Categories)
      .createQueryBuilder('categories')
      .addSelect('RANDOM()', 'random')
      .take(maxLimit)
      .orderBy('random')
      .leftJoinAndSelect('categories.userConn', 'u', 'u.userId is not null')
      .getMany();
```

Mine is a many to many relationship with a separate join table to join the two entities. That is, there's a one to many relation from each of the entities to the join table, which in turn has a many to one relation with the two entities
