### ISSUE TITLE
Help to write code with SQL version

### ISSUE THREAD

**Issue by Paul75** [typeorm/typeorm#5617]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello,

I have difficult to write in the repository the SQL to TypeOrm.

My code SQL is  : 

```
SELECT
            d.id AS domicilie_id,
            d.numero AS domicilie_numero,
            d.nom AS domicilie_nom,
            d.prenom AS domicilie_prenom
          FROM domicilie d
          LEFT JOIN
            (
              SELECT domicilie_id, MAX(`timestamp`) AS date_dernier_passage
              FROM passage
              GROUP BY domicilie_id
            ) t
          ON t.domicilie_id= d.id
          WHERE t.date_dernier_passage < SUBDATE(CURRENT_DATE, INTERVAL 3 MONTH)
          AND d.status_id <> 1;
```

When I can wrote it ?

I test with  : 

```
return this.createQueryBuilder('domicilie')
            .innerJoin('domicilie.status', 's')
            .leftJoin('domicilie.passages', 'p', 'domicilie.id = p.domicilie_id')
            .where(
                'p.`timestamp` > SUBDATE(CURRENT_DATE, INTERVAL 3 MONTH)'
            )
            .andWhere('s.code <> :status', { status: '3M' }) // correspond : d.status_id <> 1
            .andWhere('domicilie.isDisabled = :isDisabled', {
                isDisabled: false,
            })
            .printSql()
            .getMany();
```

But not same query ...

Thanks for help

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
