### ISSUE TITLE
Support for Locks during update

### ISSUE THREAD

**Issue by iacapuca** [typeorm/typeorm#5618]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Will typeorm provide any support to locks during updates? So far I was able to find out that we are able to call locks during selects, but none during updates.
So, what's the usual way of dealing with it? Create a version field and implement locking myself during beforeUpdate hook?

**Comment by imnotjames** [comment]
Aside from a transaction then starting an update you cannot use any database locks in the update statement in all dialects of SQL we support.  As such, no, it won't support locks natively as the underlying databases do not support this.

You can, however, start a transaction and then select with a lock against the table in the query - then perform your update.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
