### ISSUE TITLE
MySQL column type: Medium/Long Text

### ISSUE THREAD

**Issue by brookshi** [typeorm/typeorm#562]
Hi, does TypeORM support Medium/Long Text column data type for MySQL, Seem it only support Text when I add column with type 'text' or 'json'.

**Comment by pleerock** [comment]
what typeorm version are you using?

**Comment by brookshi** [comment]
I'm using 0.0.9.

**Comment by pleerock** [comment]
Medium/Long Text is supported only in latest 0.1.0-alpha versions.

**Comment by brookshi** [comment]
Great, Thanks.
