### ISSUE TITLE
Add schema name to the table path for Oracle driver

### ISSUE THREAD

**Issue by mrcatlait** [typeorm/typeorm#5621]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Entity metadata doesn't have schema name in tablePath for Oracle driver:

https://github.com/typeorm/typeorm/blob/b99b4ad869cbf482ae9a5558acf64084157cbedd/src/metadata/EntityMetadata.ts#L850-L868

As a result it is possible to query tables only with public synonym.
Could OracleDriver be added to the list of drivers which support schema name in tablePath?

**Comment by pirouet** [comment]
Hi,

I have pushed a fix through under #5805 for this

**Comment by lipeavelar** [comment]
I'm facing this issue, any updates about this?

**Comment by pirouet** [comment]
@lipeavelar Not sure how long it takes but I have a Pull Request (https://github.com/typeorm/typeorm/pull/6133) to add it back in waiting

**Comment by lipeavelar** [comment]
I think this issue should be closed, since https://github.com/typeorm/typeorm/pull/6673 should solve it

**Comment by pirouet** [comment]
Yep, agreed but I can't close it myself :(
