### ISSUE TITLE
Migration file for TypeORM Tree 

### ISSUE THREAD

**Issue by HunterJS-bit** [typeorm/typeorm#5622]
**Issue type:**

[ X] question

**Database system/driver:**

[ X] `Postgres`

**TypeORM version:**

[ ] `latest`

Hi guys I'm trying to use TypeOrm Tree, following Tree example from **https://github.com/typeorm/typeorm/blob/master/docs/tree-entities.md**
But my Question is how can I create migration file based on Materialized Path Tree, and is it ok to use Materialized Path Tree instead of Closure table since I need to see updating of the parent node

**Comment by legenda008** [comment]
Answered it here:
https://stackoverflow.com/questions/60545992/typeorm-tree-solution-for-migrations
Closing task
