### ISSUE TITLE
Question: How to reuse a query / share where clauses?

### ISSUE THREAD

**Issue by JClackett** [typeorm/typeorm#5624]
**Issue type:**
[x] question

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x] `latest`

Hello!

I'm trying to run a few queries which share common where clauses/joins, I thought i could do something like this:

```ts
const query = Booking.createQueryBuilder("booking")
	.where("booking.spaceId = :spaceId", { spaceId: space.id })
	.andWhere("booking.admin = FALSE")
	.andWhere("booking.date BETWEEN :begin AND :end", {
		begin,
		end,
	})

const totalBookings = await query.getCount()

const totalCancelled = await query
	.andWhere("booking.cancelled = TRUE")
	.getCount()

const totalTrial = await query
	.andWhere("booking.trial = TRUE")
	.getCount()

```

But it seems that by the time it runs the totalTrial query it's combined all the previous queries, i assume this is because i'm "mutating" the original query. I've tried using getQuery()/getSql()/subQuery(), but i dont really know how to use those and cant find anything in the docs about sharing queries. So my question is: what is the best way to do what im trying to do?

**Comment by Ishidall** [comment]
+1

**Comment by sumiranphq** [comment]
+1

**Comment by imnotjames** [comment]
This is not currently possible - your best bet would be to create a helper function that creates a new query builder with your desired extra options.

**Comment by JClackett** [comment]
@imnotjames Thanks for taking the time to respond to all these issues, really appreciate it 👍

**Comment by imnotjames** [comment]
I'm doin' my best!  There's about 1800 left to get through.

And for other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by CrazyOptimist** [comment]
> This is not currently possible - your best bet would be to create a helper function that creates a new query builder with your desired extra options.

Thanks!

**Comment by knownamenow** [comment]
use `clone()` example like below

```js
const totalBookings = await query.clone().getCount()

const totalCancelled = await query.clone()
	.andWhere("booking.cancelled = TRUE")
	.getCount()

const totalTrial = await query.clone()
	.andWhere("booking.trial = TRUE")
	.getCount()
```

**Comment by HaiAlison** [comment]
> @JClackett use `clone()` example like below
> 
> ```js
> const totalBookings = await query.clone().getCount()
> 
> const totalCancelled = await query.clone()
> 	.andWhere("booking.cancelled = TRUE")
> 	.getCount()
> 
> const totalTrial = await query.clone()
> 	.andWhere("booking.trial = TRUE")
> 	.getCount()
> ```

it's worked, thank you so much.
