### ISSUE TITLE
Question: Querying JSON columns in MySQL?

### ISSUE THREAD

**Issue by kscerbiakas** [typeorm/typeorm#5626]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a table where there is a json column. How to query that json column by its property?
Doing it raw would be something like. It works for me. But is there a better way?:

```
this.repo.query('SELECT some-column->"$.email_verification.token" as `token`  FROM `user` WHERE some-column->"$.email_verification.token" = "some-token";');
```

**Comment by jiangqizheng** [comment]
Try this
`this.model.find({where: {head: Raw(() => `head -> '$.city' = 'Hangzhou'`)}});`

**Comment by kscerbiakas** [comment]
Thanks! @jiangqizheng

**Comment by zohaib055** [comment]
> Try this
> `this.model.find({where: {head: Raw(() => `head -> '$.city' = 'Hangzhou'`)}});`

not working
