### ISSUE TITLE
column decorator option transformer and find operator Between are incompatible

### ISSUE THREAD

**Issue by wenkanglin** [typeorm/typeorm#5636]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm use column decorator transformer option(https://github.com/typeorm/typeorm/blob/master/docs/decorator-reference.md#column) to transformer timestamp. But when use it together with Bewteen(https://github.com/typeorm/typeorm/blob/master/docs/find-options.md), it will cause error:

```
Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
```

If I don't use one of them, it will be ok.

```ts
// entity.ts

const timestampTransformer = {
  to: (value: number) => Math.floor(value / 1000),
  from: (value: number) => value * 1000
}

export class TestEntity {
  @column({
    type: 'int',
    transformer: timestampTransformer
  })
  time: number
}
```

```ts
import { Between } from 'typeorm'

repository.find({
  time: Between(1583468620518, 1583555008843)
})
```

**Comment by hong-duc** [comment]
I have the same problem, and I fix it with type checking before doing anything.
```js
const timestampTransformer = {
  to: (value: number) => {
    if(value is number) {
       return Math.floor(value / 1000)
    }

    return value
  },
  from: (value: number) => {
    if(value is number) {
        return value * 1000
    }

    return value
  }
}
```

The reason is that typeorm will always call transform regardless of what you pass in, and when you pass in find operator the value will be that find operator, and you must return it so thing could go normal

**Comment by wenkanglin** [comment]
@hong-duc What's your meaning is that when I use Between operator, the transformer value will be [number, number] time range, it's not a number type?

**Comment by hong-duc** [comment]
@wenkanglin no it will be `FindOperator`

**Comment by wenkanglin** [comment]
@hong-duc thx, it works if I add type check.
Maybe it's not a bug, just the type checking isn't stated on the document. So I  closed the issue now.

**Comment by generalpiston** [comment]
@pleerock or @wenkanglin  can you re-open this? This should at least be called out in the docs.
