### ISSUE TITLE
Same enum type created twice

### ISSUE THREAD

**Issue by swymmwys** [typeorm/typeorm#5648]
**Issue type:**

[x] bug report

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x] `latest`

**Steps to reproduce**
Create two entities with enum property column of the same type.
Run migration generate.
See the result query:
![image](https://user-images.githubusercontent.com/17503250/76213796-8187fa00-621c-11ea-9692-5aad15209c41.png)

**Comment by PonyLux** [comment]
Hi there,

Get the same issue here.
Even if I'm using and `abstract` class that embed the enum.
Example below: 
`import { DEFAULT_LOCALE, Locale } from '../enums/Locales';
import { PrimaryGeneratedColumn, Column } from 'typeorm';

export abstract class Translation {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    type: 'enum',
    enum: Locale,
    default: DEFAULT_LOCALE
  })
  locale: Locale;

  @Column()
  name: string;
}

import { Entity, ManyToOne } from 'typeorm';
import { Family } from './family.entity';
import { Translation } from '../../translations/types/Translation';
import { Translation as TranslationEntity } from '../../translations/entities/translation.entity';

@Entity('family_translation')
export class FamilyTranslationEntity extends TranslationEntity implements Translation<Family> {
    @ManyToOne(type => Family, base => base.translations)
    base: Family;
}

import { Entity, ManyToOne } from 'typeorm';
import { Genus } from './genus.entity';
import { Translation } from '../../translations/types/Translation';
import { Translation as TranslationEntity } from '../../translations/entities/translation.entity';

@Entity('genus_translation')
export class GenusTranslationEntity extends TranslationEntity implements Translation<Genus> {
    @ManyToOne(type => Genus, base => base.translations)
    base: Genus;
}
`

As generated enum I get in migration same result as Swymmwys:
`
        await queryRunner.query(`CREATE TYPE "genus_translation_locale_enum" AS ENUM('fr-fr', 'en-en')`, undefined);
        await queryRunner.query(`CREATE TYPE "family_translation_locale_enum" AS ENUM('fr-fr', 'en-en')`, undefined);
`

**Comment by DScheglov** [comment]
Workaround until issue is not resolved:

1. Create manual migration with enum-type definition
2. Create custom Column with type `enum` and correspondent enum-type name.
3. Use custom Column to declare entity.

**./src/migration/1612465268299-Enums.ts**
```ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class Enums1612465268299 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TYPE "traffic_light_enum" AS ENUM('RED', 'YELLOW', 'GREEN')
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP TYPE "traffic_light_enum"
        `);
    }
}
```

**./src/columns.ts**
```ts
import { Column, ColumnOptions } from 'typeorm';

const TrafficLightColumn = (options?: ColumnOptions) =>
  Column({ ...options, type: 'enum', enumName: 'traffic_light_enum' });

**./src/entity/TrafficEvent.ts"
```ts
import { Entity, PrimaryGeneratedColumn } from 'typeorm';

export enum TrafficLightEnum {
  RED = 'RED',
  YELLOW = 'YELLOW',
  GREEN = 'GREEN'
}

@Entity()
export class TrafficEvent {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @TrafficLightColumn()
  trafficLight: TrafficLightEnum;
}
```

Yes, we need to sync enums manually but it is better then to have duplicated types or even broken migrations.

**Comment by DScheglov** [comment]
Workaround until issue is not resolved:

1. Create manual migration with enum-type definition
2. Create custom Column with type enum and correspondent enum-type name.
3. Use custom Column to declare entity.

**./src/migration/1612465268299-Enums.ts**

```ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class Enums1612465268299 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TYPE "traffic_light_enum" AS ENUM('RED', 'YELLOW', 'GREEN')
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP TYPE "traffic_light_enum"
        `);
    }
}
```

**./src/columns.ts**

```ts
import { Column, ColumnOptions } from 'typeorm';

export const TrafficLightColumn = (options?: ColumnOptions) =>
  Column({ ...options, type: 'enum', enumName: 'traffic_light_enum' });
```

**./src/entity/TrafficEvent.ts**

```ts
import { Entity, PrimaryGeneratedColumn } from 'typeorm';
import { TrafficLightColumn } from '../columns';

export enum TrafficLightEnum {
  RED = 'RED',
  YELLOW = 'YELLOW',
  GREEN = 'GREEN'
}

@Entity()
export class TrafficEvent {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @TrafficLightColumn()
  trafficLight: TrafficLightEnum;
}
```
Yes, we need to sync enums manually but it is better then to have duplicated types or even broken migrations.

**Comment by homj** [comment]
Has this really been fixed? I'm currently facing this bug on 0.2.32 and also on 0.2.36 with the same enums used across different entities.

**Comment by paulo-guimaraes** [comment]
In my case, the problem was about the order of entities was loaded. If **someClassA** is loaded after **someClassB** the error will appear since the *Enum* where not even created/loaded. Respecting the order of loading I could have added the *Enum* many times as I wanted.

*some-class-a.model.ts*
```ts
export enum EnumMyNominativeArticle {
    der = 'der',
    die = 'die',
    das = 'das'
}

@Entity(})
export class SomeClassA {
    
    @PrimaryGeneratedColumn()
    id?: number;

    @Column({
        type: 'enum',
        enum: EnumMyNominativeArticle ,
        default: EnumMyNominativeArticle.der
    })
   article: EnumMyNominativeArticle;
}
```
*some-class-b.model.ts*
```ts
@Entity(})
export class SomeClassB {
    
    @PrimaryGeneratedColumn()
    id?: number;

    @Column({
        type: 'enum',
        enum: EnumMyNominativeArticle ,
        default: EnumMyNominativeArticle.der
    })
   article: EnumMyNominativeArticle;
}
```

**Comment by amperry** [comment]
This doesn't seem to be fixed as of 0.3.9 

I'm manually having to adjust generated migrations that reference a reused enum as a new type is recreated for each referencing @Column.

I can understand if this was caused by the logic to generate the enum name but this happens even if I specify the a shared "enumName" in each @Column usage.

I feel that specifying a unique name should be the fix. Surely there should be some kind of check against existing enum name tokens during the generation script?

**Comment by rizedr** [comment]
@DScheglov regarding [your workaround](https://github.com/typeorm/typeorm/issues/5648#issuecomment-773567855), this results in a migration generation error:
```
columns changed in "ticket". updating: status
Error during migration generation:
TypeError: Cannot read properties of undefined (reading 'length')
```

Probably might be because this was already a defined Column within my entity?
```
  @Column({
    type: 'enum',
    enum: TicketStatus,
    default: TicketStatus.new,
    enumName: 'ticket_status_enum',
  })
  status: TicketStatus;
```
And I have tried to use your workaround after a while -- trying to reuse TicketStatus enum to have a log table of ticket changes.

**Comment by DScheglov** [comment]
> @DScheglov regarding [your workaround](https://github.com/typeorm/typeorm/issues/5648#issuecomment-773567855), this results in a migration generation error:

Hey, @rizedr 

Unfortunatelly `typeorm` is very unstable library. Try some old version of the one. As instance workaround was tested with `0.2.30`.
Currently considering `typeorm` uses decorators and `reflect-metadata` it makes sense to use some other ORM, with all respect to developers of `typeorm`

**Comment by rbideau** [comment]
This is also a real blocker for us.

Our current workaround is to have a script that parse the migration with regex and wrap CREATE/ALTER/DROP statement on enum with `DO $$ BEGIN ${statement} EXCEPTION WHEN dependent_objects_still_exist THEN null; END $$;`

Here is the [gist of the full script](https://gist.github.com/rbideau/711e77240e30c178da76e8953b6fd15f)

**Comment by lifenautjoe** [comment]
Hi, as of September 2023, the same issue persists, not sure why the issue was closed.

**Comment by ciphrd** [comment]
Issue still there

**Comment by nodegin** [comment]
it have been almost 4 years and this issue closed without a fix

**Comment by artursudnik** [comment]
wow... seriously?

**Comment by phosmium** [comment]
Not fixed

**Comment by david-pivonka** [comment]
Yes, not yet fixed

**Comment by jcapogna** [comment]
This is still very not fixed. If you use an enum in N entities, the migrations will have N creations for that enum type, even if the enum is unchanged.

**Comment by douglas-pires** [comment]
In my case, the solution was removing `enumName` from the `@Column` decorator and let TypeORM decide. Not the perfect solution, but hope it helps someone.

**Comment by dimitraz** [comment]
I don't have `enumName` name defined and I'm still getting this problem when using the same enum across multiple entities

**Comment by jzhao-30** [comment]
Still has the problem now, it's 2025 bro

**Comment by lookto** [comment]
A workaround that worked for me was to move the enum to a seperate file and not have it in the same file as at least one of the entities which its used by.  No `enumName` needed.

This might be because of how module resolution works - TypeORM likely processes entity files in a certain order, and having the enum co-located with one entity may cause circular dependency or loading order issues.

**Comment by jcapogna** [comment]
> A workaround that worked for me was to move the enum to a seperate file and not have it in the same file as at least one of the entities which its used by. No `enumName` needed.
> 
> This might be because of how module resolution works - TypeORM likely processes entity files in a certain order, and having the enum co-located with one entity may cause circular dependency or loading order issues.

This workaround didn't work for me. 

1) I've had my enum in a separate file from my 4 entities that use it. I still get the migrations duplicated 4 times. 

2) I tried taking the enumName off and it split the enum into 4 separate definitions, which is not what I want.
