### ISSUE TITLE
Shorthand for passing name to Column & JoinColumn

### ISSUE THREAD

**Issue by glennreyes** [typeorm/typeorm#5649]
**Is your feature request related to a problem? Please describe.**

If `name` is the only property I need to define, I have to pass an object with the `name` property:

```js
@Column({ name: 'user_id' })
```

**Describe the solution you'd like**

If `name` is the only property I need to define, I can pass `name` as a string directly:

```js
@Column('user_id')
```

**Additional context**

It's similar to what's possible with Entity:
```js
@Entity('users')
```

**Comment by imnotjames** [comment]
This won't work.  That notation is already used for types.
