### ISSUE TITLE
VS Code: Cannot find module 'typeorm' with 0.2.24

### ISSUE THREAD

**Issue by alvincrespo** [typeorm/typeorm#5650]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**Install TypeORM**

```
yarn add typeorm (should install latest 0.2.24)
```

**Configure TypeScript**

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictPropertyInitialization": false,
    "moduleResolution": "node"
  }
}
```

**Import TypeORM to create connection**

Note: You will get a "Cannot find module 'typeorm'" error. When downgrading to 0.2.22, everything works as expected.

My current package.json:

```
{
  "name": "backend",
  "version": "1.0.0",
  "engines": {
    "node": "12.x"
  },
  "scripts": {
    "dev": "TS_NODE_TRANSPILE_ONLY=true nodemon -e ts --exec \"ts-node -r dotenv/config  -r ./index.ts\""
  },
  "dependencies": {
    "apollo-datasource": "^0.7.0",
    "apollo-datasource-rest": "^0.8.0",
    "apollo-link": "^1.2.13",
    "apollo-link-http": "^1.5.16",
    "apollo-server": "^2.11.0",
    "cross-env": "5.0.5",
    "dotenv": "^8.2.0",
    "graphql": "^14.6.0",
    "pg": "^7.18.2",
    "reflect-metadata": "^0.1.13",
    "type-graphql": "^0.17.6",
    "typeorm": "^0.2.24"
  },
  "devDependencies": {
    "nodemon": "^2.0.2",
    "ts-node": "^8.6.2",
    "typescript": "^3.8.3"
  }
}

```

**Comment by riyadshauk** [comment]
I have the same/similar problem, but on 0.2.25, and also on 0.2.22...

**Comment by imnotjames** [comment]
Cannot replicate this issue

**Comment by imnotjames** [comment]
If you're still having this issue please let us know - as we can't replicate I'll be closing this issue.

**Comment by lucasdantaas** [comment]
src/database/database.providers.ts:1:34 - error TS2307: Cannot find module 'typeorm' or its corresponding type declarations.

1 import { createConnection } from 'typeorm';


como eu corrigo
