### ISSUE TITLE
Error: No metadata for "[object Object]" was found  (@EventSubscriber)

### ISSUE THREAD

**Issue by ak99372** [typeorm/typeorm#5654]
**Issue type:**
[x] bug report
**Database system/driver:**
[x] `postgres`
**TypeORM version:**
[x] `latest`

I have an event subscriber and I'm trying to get the Metadata for the entity being updated:
```
@EventSubscriber()
export class OrmSubscriber implements EntitySubscriberInterface {
	beforeUpdate(event: UpdateEvent<any>) {
                 event.connection.getMetadata(event.databaseEntity);
                 event.connection.getMetadata(event.entity)
	}
}

```
However for both entity and databaseEntity I get:

**Error: No metadata for "[object Object]" was found.**

Shouldn't both of these entities be valid entities and/or is there another way to get metadata for event entity?

**Comment by seawatts** [comment]
@ak99372 did you find the issue here?
