### ISSUE TITLE
Postgres: migration:generate drops and recreates all FKs continuously

### ISSUE THREAD

**Issue by SeWaS** [typeorm/typeorm#5655]
**Issue type:**

[X] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello 👋
It seems that after upgrading typeORM from version `0.2.22` to version `0.2.24` in my project the cli command `migration:generate -n migrationName` drops all FKs and regenerates them again, even when running the command multiple times without changing relations, entites, etc.

Maybe 7157cb393b76bfb9152234e4aea428d0d615e5d9 and issue #5119 relate to this?
I'm not so deep into the typeORM code at the moment but the added check `(tableForeignKey.referencedTableName === metadataForeignKey.referencedTablePath)` in line 795 seems to always return `false`...

**Comment by imnotjames** [comment]
I'm not seeing this any longer.  Is this still an issue?

**Comment by SeWaS** [comment]
Yes, can be closed! Haven't seen it in later versions  🎉
Thanks for your work!
