### ISSUE TITLE
fuzzy query can‘t setParams

### ISSUE THREAD

**Issue by lanweifeng** [typeorm/typeorm#5658]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I want to query a result by '...LIKE...' sql.
now, i have three rows in my user table.
|user_id | user_name|
|  ----  | ----  |
|admin|	admin|
|ceshi|	lly|
|lanker|	lan|

I try this 
```ts
        const param = 'ad';
        getManager().createQueryBuilder(User, 'user')
        .where('user.userName LIKE "%:param%"')
        .setParameters({
          param
        })
        .getRawMany();
```
and this
```ts
       const param = 'ad';
       getManager().createQueryBuilder(User, 'user')
        .where('user.userName LIKE "%:param%"', { param })
        .getRawMany();
```
got the same sql(in typeorm log console):
```sql
SELECT `user`.`user_id` AS `user_user_id`, `user`.`user_name` AS `user_user_name`
 FROM `user` `user` 
WHERE `user`.`user_name` 
LIKE "%?%" -- PARAMETERS: ["ad"]
```
I got a empty result! But there should be a record like 
|user_user_id|user_user_name|
|  ----  | ----  |
|admin|	admin|

the SQL is correct when I run this sql in navicat...

so change my code like this
```ts
       getManager().createQueryBuilder(User, 'user')
        .where('user.userName LIKE "%ad%"')
        .getRawMany();
```
not setParams...
and i got correct result 
|user_user_id|user_user_name|
|  ----  | ----  |
|admin|	admin|

Is my  code error? What should I do? Thank you for you help me !

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by lanweifeng** [comment]
ok， now i reslove it
try
```ts
.where('user.userName LIKE :param', { param: `%${param}%` })
```
or
```ts
import { Like } from 'typeorm';
.where({ userName: Like(`%${param}%`) })
```

**Comment by deweve** [comment]
It worked for me as well but if there is an explanation on why it is not possible to do this request in the first format
