### ISSUE TITLE
Documentation inconsistency

### ISSUE THREAD

**Issue by maximelafarie** [typeorm/typeorm#5665]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In the documentation located here: https://typeorm.io/#/relations/what-are-relations

We get the following relation types:

> Relations helps you to work with related entities easily. There are several types of relations:
>
> - one-to-one using @OneToOne
> - many-to-one using @ManyToOne
> - one-to-many using @OneToMany
> - many-to-many using @ManyToMany

But if we focus on these two:

> - many-to-one using @ManyToOne
> - one-to-many using @OneToMany

They both redirect to https://typeorm.io/#/many-to-one-one-to-many-relations/ .

For me, `@ManyToOne` is different than `@OneToMany` or am I missing something?

It's a bit confusing and need explanations in both cases (if they are the same thing or different).

**Comment by wederer** [comment]
https://typeorm.io/#/many-to-one-one-to-many-relations/ explains both concepts. For each `@ManyToOne` relationship in a entity you need a corresponding `@OneToMany` relationship in another entity.
