### ISSUE TITLE
Foreign key gets deleted when new object is inserted

### ISSUE THREAD

**Issue by auryn31** [typeorm/typeorm#5667]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24` 

**Steps to reproduce or a small repository showing the problem:**

    To answer those questions you need to put "x" inside the square brackets, for example:
    [ ] `mysql`
    [x] `postgres`

   I am have a foreign key in a table. When i update my object, the foreign key gets deleted and the subelements are getting new inserted.
Can someone see the issue here?

My code is:

```ts
@Entity()
@ObjectType()
export class Test {
  @PrimaryColumn()
  @Field()
  id: string;

  @OneToMany(
    type => Subelement,
    sub => sub.test,
    { cascade: true }
  )
  @JoinColumn()
  @Field(() => [Subelement], { nullable: true })
  subelements: Subelement[];
}

@Entity({synchronize: false})
@ObjectType()
export class Subelement {
  @PrimaryGeneratedColumn()
  @Field()
  id: number;

  @Column()
  @Field()
  name: string;

  @ManyToOne(
    type => Test,
    test => test.subelements
  )
  @JoinColumn()
  test: Test;
}


// To save

connection.getRepository(Test).save(testObject);
```

**Comment by auryn31** [comment]
It seems like you have to load first the parent and add the dependencies and save the parent object with all the sub dependencies. Not only the new one. If you add only the new ones, the old objects get the dependency removed. Am I right?

**Comment by sandeshgb** [comment]
`const user = {
            name: 'Sam',
            photos: [
                { file: 'file_13',},
                { file: 'file_14'}
            ]
        };
        return await this.repository.save(data);`
The above code inserts data in both user and photos table. But now when I try to add new photo by providing user's id, it doesn't work.

Case failed:
`const user = {
            id: 1,
            name: 'Sam',
            photos: [
                { file: 'file_15'}
            ]
        };
        return await this.repository.save(data);`

**Comment by auryn31** [comment]
@sandeshgb what is your output?

i had to load the user first, so you would add a photo with:

```
const user = { id: 1, name: 'Sam', photos: [ { file: 'file_13',}, { file: 'file_14'}, { file: 'file_15'} ] }; 
return await this.repository.save(data);
```

**Comment by sandeshgb** [comment]
It tried to update my photos table, but it should be an insert query.
It gave me query error userId undefined in update clause

**Comment by auryn31** [comment]
You can use save to update
if you want to update single params you can give the params to update and the id into the update query

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
