### ISSUE TITLE
Listeners aren't called on .save() for MongoDB

### ISSUE THREAD

**Issue by joemckie** [typeorm/typeorm#5668]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Save an entity to MongoDB by calling `save` with a plain object. Listeners won't be called.

**Comment by imnotjames** [comment]
Duplicate of #4080
