### ISSUE TITLE
Repository.merge() overwrites JSON[B] fields in PostgreSQL

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#567]
Hello there!

I've found another issue when using JSON[B] columns in PostgreSQL with TypeORM.

In my application, I have these lines:

```typescript
user = this.usersRepository.merge(user, request.data.body);
await this.usersRepository.persist(user);
```

The purpose of this code block is to apply data from the request body to the existing entity and then to save it. This is a part of "update" operation in my API.

The problem is that `Repository.merge()` overwrites object properties in my entity instead of recursively merging them. This leads to a serious data loss, because I want to update only partial data with `PATCH` requests instead of replacing the data entirely.

**Comment by bartlomiej-korpus** [comment]
I would say this is probably by design, this is a single field. You would be probably better using embeddeds for this purpose

**Comment by pleerock** [comment]
Yeah this is out of orm scope. Even your column is json, its just regular value as other column values.  Don't think we should merge your values. For somebody it may become unexpected behaviour.
