### ISSUE TITLE
get fields schema of entity for schema parsing/validation?

### ISSUE THREAD

**Issue by darrenjennings** [typeorm/typeorm#5674]
**Issue type:**

[x] question

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[x] `^0.2.21` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Was curious if there is a way or even if you know of any library that can transform entities into schemas for parsing. The application would be a frontend form generator or a schema validator for a cli so that users can validate input before submitting to an endpoint or otherwise.

```ts
export class User extends BaseEntity {
  @IsOptional({ groups: [UPDATE] })
  @IsNotEmpty({ groups: [CREATE] })
  @IsString({ always: true })
  @MaxLength(255, { always: true })
  @IsEmail({ require_tld: false }, { always: true })
  @Column({ type: 'text', nullable: false, unique: true })
  email: string

  @Column()
  password: string

  @JoinColumn({name: 'org_id'})
  @ManyToOne(
    type => Organization,
    o => o.users,
    {
      nullable: true,
      cascade: true,
      onDelete: 'CASCADE'
    })
  org?: Organization
}
```

```ts
console.log(User.schema()) // or whatever means of fetching the schema
{
  fields: [
    {
      id: {
        "auto": true, // indicates autogenerated
        "required": false,
        "max_length": 255,
        "type": "text",
        "uuid": true
        // etc.
      },
      password: {
        "required": true, // or array of groups
        "type": "text"
      },
      org_id: {
        required: false
      }
    }
  ]
}
```

**Comment by imnotjames** [comment]
You can get the metadata from the connection via `connection.getMetadata(User)`.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
