### ISSUE TITLE
Avoiding Duplicate Keys with OneToOne Linked List

### ISSUE THREAD

**Issue by douglance** [typeorm/typeorm#5675]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

## Question

Let's say I have a linked list of this entity:

```
@Entity()
export class Object extends AbstractEntity {
    @OneToOne(
        _ => Claim,
        c => c.id,
    )
    @JoinColumn()
    parent?: Claim;
}
```

And I want to move an entity up or down the chain. 

How would I do so without running into issues with duplicate keys?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
