### ISSUE TITLE
Adjacency list tree questions

### ISSUE THREAD

**Issue by fullofcaffeine** [typeorm/typeorm#5678]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi!

I'm implementing an adjacency list tree and I have some questions:

1) From what I saw, the helper methods exposed by the `TreeRepository` are not avaible for adjacency list trees, right? If so, why?
2) Since I'm using PostgreSQL, I'd like to use a `WITH [RECURSIVE]` query (as described [here](https://www.slideshare.net/billkarwin/models-for-hierarchical-data)) to query my recursive entities. How could I do that with TypeORM? From what I see, the `QueryBuilder`  does not support it, and if I use raw queries, it doesn't return the entities, but raw data.
3) And not entirely related to the problem, but curious: Can the `TreeRepository` be used with AR-like entities?

Thanks!

**Comment by fullofcaffeine** [comment]
Alright, found the answers for question #1 and #3, here: https://github.com/typeorm/typeorm/issues/2540.

I'd still like to know if there's an actual official way of querying `WITH [...]` without having to use a raw query, any hints?

**Comment by tafelito** [comment]
@fullofcaffeine have you ever find a way to do a recursive view like you mentioned in `2`?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
