### ISSUE TITLE
How to use operator OR in repository

### ISSUE THREAD

**Issue by ihello-world** [typeorm/typeorm#5681]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Current typeorm supported:
```userRepository.find({
  where: [
    { firstName: "Timber", lastName: "Saw" },
    { firstName: "Stan", lastName: "Lee" }
  ]
});
```
```
SELECT * FROM "user" WHERE ("firstName" = 'Timber' AND "lastName" = 'Saw') OR ("firstName" = 'Stan' AND "lastName" = 'Lee')
```

I Need: 
```
SELECT * FROM "user" WHERE ("email" = 'test' OR "full_name" = 'test') AND status=1)
```
with repository
Hope that any one can help me
Many Thanks!

**Comment by ant45de** [comment]
I think you should use the QueryBuilder here. In my opinion finds are made for non complex queries, your query could be easily implemented using the QueryBuilder with `orWhere.` A basic example can be found here: https://typeorm.io/#/select-query-builder/adding-where-expression
