### ISSUE TITLE
Unable to connect to the database. Error: EACCES: permission denied

### ISSUE THREAD

**Issue by z008hy** [typeorm/typeorm#5682]
**Issue type:**

[ ] bug report

**Database system/driver:**
[ ] `mysql` / `mariadb`

**TypeORM version:**
[ ] `0.2.24` 

**Steps to reproduce or a small repository showing the problem:**

when i use it to connect mysql. 
I find that it seems to be scanning my global files.

![image](https://user-images.githubusercontent.com/20768496/76684661-b9da6e80-6648-11ea-89f2-b97b38155f07.png)

'/Library/Application Support/Apple/AssetCache/Data'  
Not my project file

My project directory is at '/Users/xxxx/xxx/xxx/xxx/project'

I'm confused about it

**Comment by z008hy** [comment]
I found the cause of the problem. because I use a Absolute path for 'entities'.

**Comment by guillaumeLamanda** [comment]
I had the same issue, thanks @z008hy.  

More details : 
I use webpack to bundle my backend and typeorm with Postgres.

My error was 
`failed to init Error: EACCES: permission denied, scandir '/Library/Apple/System/Library/Extensions/RemoteVirtualInterface.kext/Contents/_CodeSignature/CodeResource` 

**The solution**  
In my connection options, I changed 
```
{
  // ...
  entities: ["./**/*.entities.ts"]
}
```  
to  
{
  // ...
  entities: [
    UserEntity,
    AuthEntity,
    // ...
  ]
}
```
