### ISSUE TITLE
An eager relationship skips children relationships 

### ISSUE THREAD

**Issue by satanTime** [typeorm/typeorm#5684]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
If a relation is eager there's no way to fetch its children.
Please check related PR and its test.
```ts
const user = await connection.getRepository(User).findOne(userAdmin.id, {
  relations: [
    "company", // <-- eager relation.
    "company.admin", // <-- can't be loaded without the fix.
    "company.staff", // <-- can't be loaded without the fix.
    "company.staff.company", // <-- can't be loaded without the fix.
    "company.staff.company.admin", // <-- can't be loaded without the fix.
  ],
});
```

**Comment by satanTime** [comment]
Hi @pleerock, @Kononnable, could you review and provide your feedback?

**Comment by satanTime** [comment]
Hi, any update on this?

**Comment by satanTime** [comment]
Hi there, any update?

**Comment by satanTime** [comment]
Hi @dhritzkiv, could you review?

**Comment by dhritzkiv** [comment]
Hi @satanTime, I'm not a maintainer on this repo (so can't review/merge), and I don't use eager relations in my applications, so I wouldn't know where to start with reviewing your PR.

But, your PR looks good, and it comes with the right tests, so great! I'm sure the maintainers will review it in due time.

One tip for your PRs: I find it helps to split the test + code fixes into separate commits, with the tests commit coming first, so it's easy to checkout just the test commit and verify that it does indeed fail, and it's not a false positive fix.

**Comment by satanTime** [comment]
Hi @dhritzkiv,

thanks for the info and for the suggestion, I'm updating my PRs.

Hi @pleerock, any chance you have time for a review?

**Comment by satanTime** [comment]
Hi @pleerock, any news? I need this fix for out prod.

**Comment by satanTime** [comment]
Hi @pleerock, any update when you might have time for a review?

**Comment by satanTime** [comment]
Hi @pleerock, any change you can give here a feedback? It's the 3rd month the issue has been waiting for it.

**Comment by satanTime** [comment]
Hi @pleerock, any update?

**Comment by sacha67** [comment]
Hello,

Any news about this fix ? Just stumbled on this bug on typeorm@0.2.25.

**Comment by satanTime** [comment]
I would glad to hear any feedback, however, they prefer silence.

**Comment by satanTime** [comment]
Hey @tomasreimers @pleerock, might you provide feedback?

**Comment by imnotjames** [comment]
Apologies for not having seen this.  There's now 1900 issues and while I've gotten to about 200 of them to close them - that still leaves a large number unanswered. :)

I'm slowly getting through PRs - but there's quite the backlog. I'll make sure to take a look at yours as well.

**Comment by satanTime** [comment]
Hi @imnotjames,

thanks for the info. Sure, take your time, I'll be leaving here a comment once a month until we solve it.

**Comment by satanTime** [comment]
Hi there, happy new year and happy coding!

Ping, @imnotjames and @pleerock.

Please take a look when you have time.
I also added a docker instructions to run oracle tests locally.

**Comment by satanTime** [comment]
Hi @imnotjames and @pleerock, just a friendly reminder, please take a look when you have time.

Thanks.

**Comment by satanTime** [comment]
Hi @pleerock, might you take a look at the related PR when you have time?

Thanks in advance!
