### ISSUE TITLE
QueryFailedError: Error: Incorrect syntax near the keyword 'RESTRICT'.

### ISSUE THREAD

**Issue by satanTime** [typeorm/typeorm#5686]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**
unclear which one.

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
https://travis-ci.org/github/typeorm/typeorm/jobs/662544306?utm_medium=notification&utm_source=github_status
if to change code to `onDelete: "RESTRICT",` then we get the error.
```
1) github issues > #5684 eager relation skips children relations
       "before all" hook for "should select children of an eager relation":
     QueryFailedError: Error: Incorrect syntax near the keyword 'RESTRICT'.
```

**Comment by imnotjames** [comment]
Don't understand the issue you're having.  CI is working as expected, here.

For general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
