### ISSUE TITLE
RelationId is too slow

### ISSUE THREAD

**Issue by satanTime** [typeorm/typeorm#5691]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
`@RelationId()` is too slow on big amount of related records (1k+ rows), see test in the PR.

**Comment by satanTime** [comment]
Hi @pleerock, @Kononnable, could you review and provide your feedback?

**Comment by satanTime** [comment]
Hi, any update on this?

**Comment by satanTime** [comment]
Hi there, any update?

**Comment by satanTime** [comment]
Hi @dhritzkiv, could you review?

**Comment by satanTime** [comment]
Hi @pleerock, any news? I need this fix for out prod.

**Comment by dhritzkiv** [comment]
Btw, if you need this sooner than later, you can point at your own version of Typeorm in a Git repo:

npm install git://github.com/YOURGITUSERNAME/typeorm.git#BRANCH_OR_COMMIT_HASH --save

**Comment by satanTime** [comment]
thanks, I'll try, not sure if it helps with packages where typeorm is a dependency.

**Comment by satanTime** [comment]
Unfortunately it doesn't work because it requires a build:
> ENOENT: no such file or directory, chmod '/Users/michael/projects/amc/backend/node_modules/typeorm/cli.js'

I could do a fork of the repo and so on, but I think the better way to be to add the solution to the main package.

**Comment by satanTime** [comment]
closing based on the comment https://github.com/typeorm/typeorm/pull/5692

**Comment by satanTime** [comment]
I would like to bring this topic back, because there is no interface for 3rd-party plugins in typeorm.

**Comment by satanTime** [comment]
ping @pleerock, might you check this comment: https://github.com/typeorm/typeorm/pull/5692#issuecomment-767077537.

thank you in advance.!

**Comment by satanTime** [comment]
Hi @imnotjames and @pleerock, just a friendly reminder, please take a look when you have time.

Thanks.

**Comment by nebkat** [comment]
@satanTime Unfortunately they have not been very active lately but spamming them will not help. If your issue is important enough people should upvote it and eventually that will get it attention.

**Comment by satanTime** [comment]
@nebkat, if it only was like that, for example, there is another issue with enough upvotes, but the same effect. Therefore, I simply post friendly reminders time to time.

**Comment by nebkat** [comment]
By your logic I might ask if even the issues with a large amount of upvotes are not getting attention what makes you think your one will? Pleerock is currently busy with other commitments. I say this in your own interest - if his inbox is full of hundreds of mentions he may as well have no mentions because he will just ignore everything. If you need something critical you should use your own fork for now.

**Comment by satanTime** [comment]
That is exactly why I remind them time to time about the issues.
