### ISSUE TITLE
No possibility to set database column name with ViewColumn.

### ISSUE THREAD

**Issue by KamilKot95** [typeorm/typeorm#5708]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**Comment by joey-lucky** [comment]
+1

**Comment by dsbert** [comment]
Running into this issue as well.
