### ISSUE TITLE
`yarn audit` returns error because of dependency `mkdirp`

### ISSUE THREAD

**Issue by drublic** [typeorm/typeorm#5709]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
The module [`mkdirp`](https://www.npmjs.com/package/mkdirp) uses `minimist` as a dependency. This returns an error when running `yarn audit`:

![Screenshot 2020-03-18 at 13 49 25](https://user-images.githubusercontent.com/502487/76962322-4e7dee80-691f-11ea-932f-a2d1c353a0cd.png)

It would be fantastic to update `mkdirp` to the latest version if possible.

**Comment by vymarkov** [comment]
👍

**Comment by urdeveloper** [comment]
#5748

**Comment by drublic** [comment]
Since the PR was merged I will close this issue.
