### ISSUE TITLE
Heroku Support

### ISSUE THREAD

**Issue by benbayard** [typeorm/typeorm#571]
Hey! I love the product, recently went to testing a deploy and ran in to an issue.

It appears that heroku does not accept a username and password in its postgres connection library. As a result, it should not be supplied in the connection string.

I tried simply not setting username and password, but unfortunately I get an error: 
```
Driver option (username) is not set. Please set it to perform connection to the database.
```

I was wondering what the best course of action might be? Thank you! 

Heroku docs: https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js

**Comment by NoNameProvided** [comment]
We aren using Typeorm with heroku, tomorrow I will write down the details

**Comment by benbayard** [comment]
Thank you! I can use the credentials by hand but they rotate randomly, so I'm not sure if it is safe to use those. I'm really interested in your solution!

**Comment by pleerock** [comment]
> It appears that heroku does not accept a username and password in its postgres connection library. 

are you sure about it? Then what authentification mechanizm they use? I know people already used typeorm with heroku and they didn't have such problems.

**Comment by NoNameProvided** [comment]
> Thank you! I can use the credentials by hand but they rotate randomly, so I'm not sure if it is safe to use those. I'm really interested in your solution!

You need to use provided environment variable. (Which will be switched when Heroku changes the credentials for you.) You can use the `pg-connection-string` library for this.

```ts
import * as PostgressConnectionStringParser from 'pg-connection-string';

const connectionOptions = PostgressConnectionStringParser.parse(process.env.DATABASE_URL);


return createConnection(<ConnectionOptions>{
  driver: {
    type: process.env.TYPEORM_DRIVER_TYPE,
    host: connectionOptions.host,
    port: connectionOptions.port || 5432,
    username: connectionOptions.user,
    password: connectionOptions.password,
    database: connectionOptions.database,
  },
  entities: [...this.entities],
  subscribers: [...this.subscribers],
}).catch(error => console.log(error));
```

**Comment by benbayard** [comment]
Amazing solution, thank you!

**Comment by Juanmabs22** [comment]
Other way is:

    import { createConnection, ConnectionOptions } from "typeorm";

    createConnection(<ConnectionOptions>{
        type: "postgres",
    
        // We need add the extra SSL to use heroku on localhost
        extra: {
            ssl: true,
        },
    
        // Change the next line to use the Heroku postgresql from other environment like localhost, remenber that heroku changes this data periodically for security reasons
        url: process.env.DATABASE_URL || "postgres://user:pass@domain:5432/database", 

        entities: [ EntityA ],
        subscribers: [],
        synchronize: true,
    }).catch(error => console.log(error));

[Thanks to Issue 425](https://github.com/typeorm/typeorm/issues/425)

_Hope this helps, I use it to try on my localhost before publish on Heroku_

**Comment by felipecassiors** [comment]
This is how I do:

```javascript
// ormconfig.js

const type = process.env.TYPEORM_TYPE || 'postgres';
const username = process.env.TYPEORM_USERNAME || 'user';
const password = process.env.TYPEORM_PASSWORD || 'pass';
const host = process.env.TYPEORM_HOST || 'db';
const port = parseInt(process.env.TYPEORM_PORT, 10) || 5432;
const database = process.env.TYPEORM_DATABASE || 'data';

module.exports = {
  type,
  url:
    process.env.DATABASE_URL ||
    `${type}://${username}:${password}@${host}:${port}/${database}`,
  entities: [
    process.env.NODE_ENV === 'test'
      ? 'src/**/*.entity.ts'
      : 'dist/**/*.entity.js',
  ],
  synchronize: true,
};
```

**Comment by ownedbypeli** [comment]
Sorry can someone explain me what everything i need to do to get that working?

Also i am pretty new to Typescript and i am setting up my first project with typeorm which should be able to connect to the heroku postgresdb.

I've looked trough some docs but somehow i cant combine everything :/

**Comment by ownedbypeli** [comment]
Also, I don't understand what process.env.DATABASE_URL should be.

**Comment by felipecassiors** [comment]
@ownedbypeli Heroku exposes the environment variable DATABASE_URL to connect in the Postgres, `process.env.DATABASE_URL` is how you access it in `.ts` or `.js` files.

**Comment by ownedbypeli** [comment]
And how do i setup this this env variable? what should the value be @felipecassiors

**Comment by dannytlake** [comment]
@ownedbypeli read this from top to bottom: https://devcenter.heroku.com/articles/heroku-postgresql
