### ISSUE TITLE
How do I increase connectionLimit?

### ISSUE THREAD

**Issue by goktugyil** [typeorm/typeorm#5711]
How do I increase connectionLimit?

I tried this in ormconfig.js, didn't work:
```
        },
        extra: {
            connectionLimit: 150
        }
    },
```

Database is only opening 9 connections atm. using postgresql

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
