### ISSUE TITLE
Can "PRAGMA foreign_keys=OFF" SQLite statement be used inside a migration?

### ISSUE THREAD

**Issue by minicatsCB** [typeorm/typeorm#5712]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] `0.2.18`

**Steps to reproduce or a small repository showing the problem:**
I have a table named `country` and a table named `workflow`. I want to remove one of the columns, named `name`, of `country` but `workflow` references `country` through this column.

Playing with DB Browser for SQLite I could remove the column successfully with these statements:
```sql
PRAGMA foreign_keys=OFF;
CREATE TEMPORARY TABLE country_backup(id, createdAt, updatedAt, enabled, codeIso2);
INSERT INTO country_backup SELECT id, createdAt, updatedAt, enabled, codeIso2 FROM country;
DROP TABLE country;
CREATE TABLE country(id, createdAt, updatedAt, enabled, codeIso2);
INSERT INTO country SELECT id, createdAt, updatedAt, enabled, codeIso2 FROM country_backup;
DROP TABLE country_backup;
PRAGMA foreign_keys=ON;
```
Which I used in a TypeORM migration like this:
```typescript
...
public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query("PRAGMA foreign_keys=OFF");
    await queryRunner.query("CREATE TEMPORARY TABLE country_backup(id, createdAt, updatedAt, enabled, codeIso2)");
    await queryRunner.query("INSERT INTO country_backup SELECT id, createdAt, updatedAt, enabled, codeIso2 FROM country");
    await queryRunner.query("DROP TABLE country");
    await queryRunner.query("CREATE TABLE country(id, createdAt, updatedAt, enabled, codeIso2)");
    await queryRunner.query("INSERT INTO country SELECT id, createdAt, updatedAt, enabled, codeIso2 FROM country_backup");
    await queryRunner.query("DROP TABLE country_backup");
    await queryRunner.query("PRAGMA foreign_keys=ON");
}
...
```
 But I get this error:
```plaintext
Error during migration run:
QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
    at new QueryFailedError (/.../api/src/error/QueryFailedError.ts:9:9)
    at Statement.handler (/.../src/driver/sqlite/SqliteQueryRunner.ts:53:26)
    at Statement.replacement (/.../api/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.replacement (/.../api/node_modules/sqlite3/lib/trace.js:19:31) {
  message: 'SQLITE_CONSTRAINT: FOREIGN KEY constraint failed',
  errno: 19,
  code: 'SQLITE_CONSTRAINT',
  name: 'QueryFailedError',
  query: 'DROP TABLE country',
  parameters: []
}
```
Why did it work in DB Browser for SQLite but not with TypeORM? It's like it ignored the PRAGMA statement.

Based on [this](https://www.sqlite.org/lang_altertable.html), I tried with both `PRAGMA foreign_keys` and `PRAGMA legacy_alter_table` (setting them OFF and ON (before any action) and ON and OFF (after any action), respectively).

I tried using the PRAGMA's both inside the `up()` function and outside it. Outside it means I put the statements before and after `await typeOrmConnection.runMigrations()` in my `main.ts` file, like `await typeOrmConnection.query("PRAGMA foreign_keys=OFF")`.

**Comment by imnotjames** [comment]
It works here - not sure what the difference is.  We use this in our CI.

---

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by nyholmjan** [comment]
> It works here - not sure what the difference is. We use this in our CI.
> 
> For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

Sorry for answering on a closed topic, but someone else might end up here and I wanted to note that it should not work unless the migrations are run with the transaction set to false, because the PRAGMA foreign_keys is a no-op when queried within a transaction and the TypeORM migrations are transactional by default.
