### ISSUE TITLE
Foreign keys only exist when manually added

### ISSUE THREAD

**Issue by rostgoat** [typeorm/typeorm#5713]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.22` (or put your version here)

I've noticed that in order for me to see FKs in my database I have to manually add them during my API calls. Let me explain with an example

There are two entities: `Posts` and `Posts Likes`

They share a `One-to-one` relationship.

The `Post` is created first and once it is created it can be `liked` which means that a FK relationship is "supposed" occur where the `like_id` would become an FK in the `Posts` table and the `post_id` would become an FK in the `Likes` table.

The only way I have so far managed to do this is by **manually** assigning the foreign keys when my `Like` is `POSTed`. See code below: 

```
async like(data: Partial<LikesDTO>): Promise<Likes> {
        // extract data from request
        const {user_uid, post_uid} = data;

        // grab user by passed uid
        const user = await this.userService.findOneByUID(user_uid);

        // grab post by passed uid
        const post = await this.postrService.findOne(post_uid);

        // data to save to db for new like
        const likeArgs = {
            post_liked: true,
            liked_at: Date.now(),
        }

        // create object with new like props
        const newLike = await this.likesRepository.create(likeArgs);

        // verify user is valid
        if (user.uid === user_uid) {
            // grab related user and assign to user object of like
            newLike.user = user; // RIGHT HERE IS WHERE THE FK ASSIGNMENT OCCURS
            } else {
                throw new Error("Invalid user!")
        }

        // verify post is valid
        if (post.uid === post_uid) {
            // grab related user and assign to user object of like
            newLike.post = post; // RIGHT HERE IS WHERE THE FK ASSIGNMENT OCCURS
        } 

        // save changes
        await this.likesRepository.save(newLike);
        // return new like
        return toLikeDto(newLike);
      }
```

**likes.entity.ts**
```
  /**
   * Likes Entity
   */
  @Entity('likes')
  export class Likes {
    @PrimaryGeneratedColumn('uuid') like_id: string;
    @Column({ type: 'varchar', nullable: false, unique: true }) uid: string;
    @Column({ type: "date" }) liked_at: Date;
    @Column({ type: "boolean" }) post_liked: Boolean;
  
    @OneToOne(type => Post)
    @JoinColumn({ name: 'post_id'})
    post: Post

    @OneToOne(type => User)
    @JoinColumn({ name: 'user_id'})
    user: User

    @BeforeInsert() async generateUID() {
      this.uid = uuid();
      this.liked_at = new Date();
    }
  }
```

**post.entity.ts**
```
/**
 * Post Entity
 */
@Entity('posts')
export class Post {
  @PrimaryGeneratedColumn('uuid') post_id: string;
  @Column({ type: 'varchar', nullable: false, unique: true }) uid: string;
  @Column('text') title: string;
  @Column('text') sub_title: string;
  @Column('text') content: string;
  @ManyToOne(
    type => User,
    user => user.posts,
    {
      cascade: true,
    },
  )
  @JoinColumn({ name: 'user_id'})
  user: User;

  @OneToMany(
    type => Comment,
    comment => comment.post,
    {
      cascade: true,
    },
  )
  @JoinColumn({ name: 'comment_id'})
  comments: Comment[];

  @OneToOne(type => Photo, {
    cascade: true,
  })
  @JoinColumn({ name: 'photo_id'})
  photo: Photo


  @BeforeInsert() async generateUID() {
    this.uid = uuid();
  }
  
  constructor(title?: string, content?: string) {
    this.title = title || '';
    this.content = content || '';
  }
}
```

I have tried specifying bi-directional relationship between `Posts` and `Likes` as specified in the [docs](https://github.com/typeorm/typeorm/blob/master/docs/one-to-one-relations.md) but that does not seem to work.

Furthermore, if I do a `find` on `Posts` where `likes` are part of the `relations`, it simply returns `null` for `like` object

```
  /**
   * Find all posts 
   */
  async findAll(): Promise<Post[]> {
    return await this.postRepository.find({select: ['uid', 'title', 'sub_title', 'content'], relations: ['photo', 'like']});
  }
```
![Screenshot from 2020-03-18 11-21-28](https://user-images.githubusercontent.com/22672124/76993882-cb529d80-690a-11ea-8b4e-3dd5dc425842.png)

**My Question: Why is this happening? is this expected behavior where I have to manually provide FKs?**

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
