### ISSUE TITLE
.update() still not skipping null 

### ISSUE THREAD

**Issue by stephanoparaskeva** [typeorm/typeorm#5721]
**Issue type:**

[ x] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

# Code
```JavaScript
const categoryRepo = getRepository(Category);
const categoryBody: categoryObject = { title, description };
const editedCategory: UpdateResult = await categoryRepo.update(categoryId, categoryBody);
```
# req.body 
```JavaScript
{
	"description": "timber"
}
```
## Desctructuring Title and Description, both added to update(), title is ```undefined```, this should be skipped.

# Model
```JavaScript
import {
  Entity,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  PrimaryGeneratedColumn,
  Unique,
} from 'typeorm';

@Entity('categories')
@Unique(['title'])
export class Category {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('varchar', { length: 255 })
  title: string;

  @Column({ nullable: true })
  description: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
```
# Error
```JavaScript
"err": {
    "message": "null value in column \"title\" violates not-null constraint",
    "name": "QueryFailedError",
    "length": 250,
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (236, null, three four, 2020-03-19 01:30:28.077516, 2020-03-19 17:43:12.961479).",
    "schema": "public",
    "table": "categories",
    "column": "title",
    "file": "execMain.c",
    "line": "1965",
    "routine": "ExecConstraints",
    "query": "UPDATE \"categories\" SET \"title\" = $2, \"description\" = $3, \"updatedAt\" = CURRENT_TIMESTAMP WHERE \"id\" IN ($1)",
    "parameters": [
      "236",
      null,
      "three four"
    ]
  }
```

**Comment by stephanoparaskeva** [comment]
Closing, issue with code not typeorm, spreading in ```title: undefined```

**Comment by artoodeeto** [comment]
do you have a workaround on this issue bro? I have the same issue and it's holding me back. I wish they could fix bugs and some issues first before adding a new feature. smh.

**Comment by stephanoparaskeva** [comment]
> do you have a workaround on this issue bro? I have the same issue and it's holding me back. I wish they could fix bugs and some issues first before adding a new feature. smh.

No worries man, I got you.
```JavaScript
import { EntityRepository, Repository, createQueryBuilder } from 'typeorm';
import { Category } from './category.entity';
import { removeUndefined, throwNotFoundIfFalsy } from '../../lib/utilities/common_utils';

@EntityRepository(Category)
export class CustCategory extends Repository<Category> {
  patchOrThrow = async (id: string, entity: any) => {
    throwNotFoundIfFalsy(Number(id));

    const sanitisedEntity = removeUndefined(entity);
    const res = await createQueryBuilder()
      .update(Category)
      .set(sanitisedEntity)
      .where('id = :id', { id })
      .returning('*')
      .execute();

    throwNotFoundIfFalsy(res.affected);
    return res.raw[0];
  };
}

```

and the imported functions are as follows:

```JavaScript
export const throwNotFoundIfFalsy = (value?: any): void => {
  if (!value) {
    throw new NotFound();
  }
};

export const removeUndefined = (obj: object) =>
  Object.entries(obj).reduce((acc: object, curr: any[]) => {
    if (curr[1]) {
      return { ...acc, [curr[0]]: curr[1] };
    }
    return acc;
  }, {});

```

NotFound is imported from NPM package ```http-errors```
And you have to import this as a custom repository e.g
```JavaScript
import { getCustomRepository } from 'typeorm';
import { CustCategory } from './category.repository';

const patchCategoryById = async (data: CategoryType, categoryId: string) => {
  const categoryRepo = getCustomRepository(CustCategory);
  const editedCategory = await categoryRepo.patchOrThrow(categoryId, data);
  return editedCategory;
};
```

**Comment by artoodeeto** [comment]
Eyyy bro. I skipped your solution because you are using the `update` method and It won't trigger the `before` hooks. So I have this solution, just wanted to share,

Instead of merging it with the js destructuring, you need to merge it with `Object.assign` so the `TYPE` will be the same.

```
try {
      const user: User = await User.findOneOrFail(id);
      Object.assign(user, { ...req.body });
      await user.save();
      res.json({
        meta: {},
        payload: {
          ...req.body
        }
      });
    } catch (error) {
      logger.error(error);
      res.status(404).json({
        error
      });
    }
```

**Comment by stephanoparaskeva** [comment]
> Eyyy bro. I skipped your solution because you are using the `update` method and It won't trigger the `before` hooks. So I have this solution, just wanted to share,
> 
> Instead of merging it with the js destructuring, you need to merge it with `Object.assign` so the `TYPE` will be the same.
> 
> ```
> try {
>       const user: User = await User.findOneOrFail(id);
>       Object.assign(user, { ...req.body });
>       await user.save();
>       res.json({
>         meta: {},
>         payload: {
>           ...req.body
>         }
>       });
>     } catch (error) {
>       logger.error(error);
>       res.status(404).json({
>         error
>       });
>     }
> ```

Hey man, when you say 'merge it with' what is 'it' in this context?
What do you mean by 'the TYPE will be the same', type of what?
And 'update wont trigger before hooks', what before hooks are you talking about here?

Also, I try not to just spread in req.body as it is potentially dangerous from a security standpoint to just pass in the whole request body to my back-end.

**Comment by artoodeeto** [comment]
> Hey man, when you say 'merge it with' what is 'it' in this context?
> What do you mean by 'the TYPE will be the same', type of what?

what I mean by this is using a regular js object to merge or update the entity like this.

```
const user = await User.find(1) // returns {id:1, username: 'foo', email: 'f@g.com'}
// req.body returns { email: 'bar@g.com' }
// I was doing it like this.
const updatedUser = { ...user,  ... req.body } <---- this is where the User type is lost.
await User.save(updatedUser)
```

so I have to update it like this.:
```
const user = await User.find(1) // returns {id:1, username: 'foo', email: 'f@g.com'}
Object.assign(user, { ...req.body });
await user.save() // <-- this will update and skips null
```

> And 'update wont trigger before hooks', what before hooks are you talking about here?

Im taking about this [subscriber and listeners](https://typeorm.io/#/decorator-reference/subscriber-and-listener-decorators)

I'm using the `@BeforeUpdate` hook when a user updates their password I need to hash it again.

```
@BeforeUpdate()
private foobar() {
// code will be invoke before updating
}
```


> Also, I try not to just spread in req.body as it is potentially dangerous from a security standpoint to just pass in the whole request body to my back-end.

damn bro I'm just doing it like this because I was thinking regardless if they try to make sql injection itll be transposed to a string. what do you think?

**Comment by rosulg** [comment]
One workaround to make `update()` skip the undefined property is to delete the unwanted property in the `@BeforeUpdate`hook.

Example:

```ts
@Entity('user')
class User {

@Column()
password:string;

 @BeforeInsert()
  async hashPassword() {
    // ...
  }

  @BeforeUpdate()
  async onPasswordUpdate() {
    if (this.password) {
      await this.hashPassword();
    } else {
      // Delete property so it's not updated
      delete this.password;
    }
  }

}
```

**Comment by imnotjames** [comment]
This isn't an issue - you're telling `update` to set a null-ish value and that's what it's doing.

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
