### ISSUE TITLE
table are not being created when starting server with outDir

### ISSUE THREAD

**Issue by sptGabriel** [typeorm/typeorm#5724]
**Issue type:**

[ x] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Basically I have a server node in the docker, and I'm using outDir in my tsconfig and so I'm not able to configure it correctly and I can't find the reason why I am not creating the tables
I used a docker-compose logs and my server is running normally and my postgres too

I tried to check my base and:
```
emasa_base => \ d
Did not find any relations.
```

ormconfig.json

```
{
  "type": "postgres",
  "host": "db",
  "port": 5432,
  "username": "spirit",
  "password": "emasa",
  "database": "emasa_base",
  "synchronize": true,
  "logging": false,
  "entities": ["./dist/**/*.entity{.ts,.js}"],
  "migrations": ["./dist/**/migration/**/*.ts"],
  "subscribers": ["./dist/**/subscriber/**/*.ts"],
  "cli": {
    "entitiesDir": "./dist/**/entity",
    "migrationsDir": "./dist/**/migration",
    "subscribersDir": "./dist/**/subscriber"
  }
}
```

my docker file:

```
FROM node as builder
WORKDIR usr/app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn run build

#stage 2
FROM node
WORKDIR usr/app
COPY package*.json ./
RUN yarn install --production

COPY --from=builder /usr/app/dist ./dist

COPY ormconfig.json .
COPY .env . 

expose 4000
CMD node dist/src/index.js
```

my structure folder:

![image](https://user-images.githubusercontent.com/58380116/77134977-3b1a7280-6a48-11ea-8692-c504ea00d07b.png)

**Comment by Marcus-Rise** [comment]
Did you solve your problem? I have the same issue with mongodb
