### ISSUE TITLE
migration:create ignores config file passed via --config

### ISSUE THREAD

**Issue by glennreyes** [typeorm/typeorm#5727]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Init

```js
typeorm init --mysql
```

2. Create a `.env` file

```env
TYPEORM_URL=mysql://root@localhost
```

3. Create migration and pass `ormconfig.json`

```sh
typeorm migration:create -n User --config ormconfig.json
```

4. Result: Migration file is created in project root although explicitly specified a config file

Expected: Migration file is created in `src/migration` as specified in `ormconfig.json`

**Comment by imnotjames** [comment]
Cannot replicate.  Is this still an issue?

**Comment by glennreyes** [comment]
@imnotjames Closing this for now since I don't have any ressources to re-check this. I'll just leave following link for reference:

https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#which-configuration-file-is-used-by-typeorm
