### ISSUE TITLE
Error generating migration for a new table with composite foreign key as a primary key

### ISSUE THREAD

**Issue by golergka** [typeorm/typeorm#5729]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.22`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

1. Create the following schema with previous migrations (no problems there):

```ts
export enum UserLoginMethod {
    DeviceId = "device_id",
    Facebook = "facebook",
    Bot = "bot"
}

@Entity()
// We have to create a composite index for it to be a target of a foregn key
@Index("user_login_method", ["id", "loginMethod"], { unique: true })
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        type: "enum",
        enum: UserLoginMethod
    })
    loginMethod: UserLoginMethod;

}
```

2. Create a new entity:

```ts
@Entity()
export class UserDeviceId {

    @OneToOne(type => User, { primary: true })
    @JoinColumn([
        { name: "userId", referencedColumnName: "id" },
        { name: "userLoginMethod", referencedColumnName: "loginMethod"}
    ])
    user: User;

    @Column({ unique: true })
    @Index()
    deviceId: string;
}
```

3. Try to generate a new migration:

```
typeorm migration:generate -n UserDeviceId
```

**Expected result:**

A new migration is created, with a new table that uses a composite foreign key as a primary column.

**Actual result:**

```
Error during migration generation:
TypeError: Cannot read property 'map' of undefined
    at PostgresQueryRunner.createEnumTypeSql (/usr/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:2398:38)
    at PostgresQueryRunner.<anonymous> (/usr/lib/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:420:69)        at step (/usr/lib/node_modules/typeorm/node_modules/tslib/tslib.js:136:27)
    at Object.next (/usr/lib/node_modules/typeorm/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/usr/lib/node_modules/typeorm/node_modules/tslib/tslib.js:107:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by golergka** [comment]
Updated from 0.2.22 to 0.2.24, bug still persists.

**Comment by golergka** [comment]
So, it seems that it's failing here:

https://github.com/typeorm/typeorm/blob/4ed79c9cf9ad0f1e51930159dfdab8c1e8549339/src/driver/postgres/PostgresQueryRunner.ts#L318

While trying to create an up migration for a new enum. But it's not a new enum! It should use the same enum that was created before.

I digged the code that checks if enum exists already, and found this:

https://github.com/typeorm/typeorm/blob/4ed79c9cf9ad0f1e51930159dfdab8c1e8549339/src/driver/postgres/PostgresQueryRunner.ts#L1829

Apparently, table name is included in the generated enum name - so, although it's the same enum type on both columns, TypeORM tries to create a new type for each table that uses this enum.

If I understood all that correctly (and it's very possible that I didn't), that seems like a very strange design choice and defeats the whole purpose of user-defined data types.

**Comment by golergka** [comment]
Found a workaround!

In the code that decides how an enum should be named, there is mention that I could specify the enum name explicitly:

https://github.com/typeorm/typeorm/blob/4ed79c9cf9ad0f1e51930159dfdab8c1e8549339/src/driver/postgres/PostgresQueryRunner.ts#L1992-L2000

So, I put it into my user entity (just in case, although the name stayed the same):

```ts
@Entity()
// We have to create a composite index for it to be a target of a foregn key
@Index("user_login_method", ["id", "loginMethod"], { unique: true })
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        type: "enum",
        enum: UserLoginMethod,
        enumName: "user_loginmethod_enum"
    })
    loginMethod: UserLoginMethod;
```

And then into my new table, too:

```ts
@Entity()
export class UserDeviceId {

    @Column({
        type: "enum",
        enum: UserLoginMethod,
        enumName: "user_loginmethod_enum"
    })
    userLoginMethod: UserLoginMethod;

    @OneToOne(type => User, { primary: true })
    @JoinColumn([
        { name: "userId", referencedColumnName: "id" },
        { name: "userLoginMethod", referencedColumnName: "loginMethod" }
    ])
    user: User;

    @Column({ unique: true })
    @Index()
    deviceId: string;
}
```

And now it uses the same type name for both.

**Comment by AlexMesser** [comment]
You can use `enumName` property for this case.

```ts
@Column({
    type: "enum",
    enumName: "loginMethodEnum",
    enum: UserLoginMethod
})
loginMethod: UserLoginMethod;
```
