### ISSUE TITLE
Truncate table with typeorm

### ISSUE THREAD

**Issue by gcmatheusj** [typeorm/typeorm#5732]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

Hello everyone, i'm looking for a simple example show me how to truncate all table using typeorm before each test with jest. Can you help me? Thanks guys!

**Comment by imnotjames** [comment]
Maybe `queryRunner.query('TRUNCATE TABLE foo')`?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by luatnd** [comment]
I use:
```
@Injectable()
export class UserGrowthService {
  constructor(
    @InjectRepository(UserGrowthEntity)
    private userGrowthRepository: Repository<UserGrowthEntity>,
  ) {}

  async truncate(): Promise<void> {
    return await this.userGrowthRepository.clear();
  }
}
```
