### ISSUE TITLE
Mysql - Datetime - Timestamp - Timezone issues

### ISSUE THREAD

**Issue by FredericLatour** [typeorm/typeorm#5735]
Introduction
------------
This article will provide my results testing Timezone matters for various nodejs libraries/drivers when MySql does not hold datetime in UTC.

One could argue that it is certainly way better to store all dates in UTC (especially because UTC is DST independant) however there maybe a couple of reason not having dates in UTC:
* a legacy database with multiple apps where timezone considerations were not taken into account (and that's indeed why I've done this work)
* because one would prefer to manipulate date in its own timezone when directly using a query tool.

Because I was struggling with timezone and because the documentation does often leaves to be desired, 
I decided to to some testing with the following libraries:
* mikroorm
* mariadb connector
* mysql
* typeorm

### The setup
* a separate Mysql server witht timezone configured to '+05:00'
* a table that hold both a DATETIME column and a TIMESTAMP column
* a separate server with a node application running the test. This server local time is GMT+1 based.

### What I'm testing
* I'm retrieving an existing record that holds both a DATETIME and a TIMESTAMP column and see what I get and if it sounds coherent.
* I insert a record using the same date for both the DATETIME and TIMESTAMP and retrieve back the record and see what I get

### notes
Having Mysql timezone configured to '+05:00' basically means that all dates in Mysql are GMT+5 based. 
This is examplified by the fact that CURRENT_TIMESTAMP will return a GMT+5 date.

In mysql, we can store date and time in DATETIME column and TIMESTAMP columns.
DATETIME does not hold any timezone information. Therefore you have to know what you are doing by convention.  
TIMESTAMP Will store dates in UTC and will display using whatever timezone is currently configured.  
Initialising both type of columns with CURRENT_TIMESTAMP will display the exact same date. However, because TIMESTAMP are stored in UTC, 
if you change MySql current timezone, TIMESTAMP columns will display their DATETIME value according to the new timezone while DATETIME columns are left unchaged.

### Mysql Configuration

<table>
  <thead>
    <tr>
      <th class="col0">UTC_TIMESTAMP()</th>
      <th class="col1">CURRENT_TIMESTAMP()</th>
      <th class="col2">@@system_time_zone</th>
      <th class="col3">@@time_zone</th>
      <th class="col4">@@GLOBAL.time_zone</th>
      <th class="col5">@@SESSION.time_zone</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="col0">2020-03-20 23:32:11</td>
      <td class="col1">2020-03-21 04:32:11</td>
      <td class="col2">CET</td>
      <td class="col3">+05:00</td>
      <td class="col4">SYSTEM</td>
      <td class="col5">+05:00</td>
    </tr>
  </tbody>
</table>

  
  
Retrieving an existing record - Connection timezone configured to '+05:00'
-------------------------------------------------------------------------
  
<table>
  <thead>
    <tr>
      <th>
        MySql TimeZone: +05:00<br>
        Nodejs env Timezone: CET
      </th>
      <th colspan=2>mikroorm<br>Cx timezone: +05:00</th>
      <th colspan=2>mariadb<br>Cx timezone: +05:00</th>
      <th colspan=2>mysql<br>Cx timezone: +05:00</th>
      <th colspan=2>typeorm<br>Cx timezone: +05:00</th>
    </tr>
    <tr>
      <th></th>
      <th>DateTimeColumn</th>
      <th>TimeStampColumn</th>
      <th>DateTimeColumn</th>
      <th>TimeStampColumn</th>
      <th>DateTimeColumn</th>
      <th>TimeStampColumn</th>
      <th>DateTimeColumn</th>
      <th>TimeStampColumn</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>As Displayed In MySql</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 11:11:11</td>
    </tr>
    <tr>
      <td>Date.toString()</td>
      <td>2020-03-17 11:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 03:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 03:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 03:11:11 GMT+0100 &nbsp;</td>
    </tr>
    <tr>
      <td>Date.toUTCString()</td>
      <td>2020-03-17 10:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 02:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 02:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 02:11:11 GMT</td>
    </tr>
  </tbody>
</table>

## Analysis
First of all, I would expect the exact same result for both DATETIME and TIMESTAMP column. The fact that MySql store TIMESTAMP values as UTC internally should not affect the expected result.
Therefore I'm expecting the following results for both columns:

<table>
  <tbody>
    <tr>
      <td>As Displayed In MySql</td>
      <td>2020-03-17 11:11:11</td>
    </tr>
    <tr>
      <td>Date.toString()</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
    </tr>
    <tr>
      <td>Date.toUTCString()</td>
      <td>2020-03-17 06:11:11 GMT</td>
    </tr>
  </tbody>
</table>

#### mariadb, mysql and typeorm
They have the same results and seem to use the same approach. I suppose that typeorm relies on the driver.
The DATETIME column is handled properly and I get the expected results.
The TIMESTAMP column gives wrong results Not sure what it does because there is a 4 hours shift.

#### mikroorm
Has it's own approach here.  
Contrary to other libraries, TIMESTAMP provides the expected values here.  
On the other hand DATETIME column provides wrong result. It seems to be handled as if the value was in the timezone of the running node app (that's pure hypothesis, would need to change the running timezone to confirm)

mikroorm only - Retrieving an existing record - timezone configured to '+05:00' - ForceUtcTimezone: true
--------------------------------------------------------------------------------------------------------
  
<table>
  <thead>
    <tr>
      <th>
        MySql TimeZone: +05:00<br>
        Nodejs env Timezone: CET
      </th>
      <th colspan=2>mikroorm<br>Cx timezone: +05:00<br>ForceUtcTimezone: true</th>
    </tr>
    <tr>
      <th></th>
      <th>DateTimeColumn</th>
      <th>TimeStampColumn</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>As Displayed In MySql</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 11:11:11</td>
    </tr>
    <tr>
      <td>Date.toString()</td>
      <td>2020-03-17 12:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 08:11:11 GMT+0100 &nbsp;</td>
    </tr>
    <tr>
      <td>Date.toUTCString()</td>
      <td>2020-03-17 11:11:11 GMT</td>
      <td>2020-03-17 07:11:11 GMT</td>
    </tr>
  </tbody>
</table>
  
  
  
Inserting a record with the following date: new Date('2020-03-17T07:11:11')
---------------------------------------------------------------------------
  
<table>
  <thead>
    <tr>
      <th>
        MySql TimeZone: +05:00<br>
        Nodejs env Timezone: CET
      </th>
      <th colspan=2>mikroorm<br>Cx timezone: +05:00</th>
      <th colspan=2>mariadb<br>Cx timezone: +05:00</th>
      <th colspan=2>mysql<br>Cx timezone: +05:00</th>
      <th colspan=2>typeorm<br>Cx timezone: +05:00</th>
    </tr>
    <tr>
      <th></th>
      <th>DateTimeColumn</th>
      <th>TimeStampColumn</th>
      <th>DateTimeColumn</th>
      <th>TimeStampColumn</th>
      <th>DateTimeColumn</th>
      <th>TimeStampColumn</th>
      <th>DateTimeColumn</th>
      <th>TimeStampColumn</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>As Displayed In MySql</td>
      <td>2020-03-17 07:11:11</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 15:11:11</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 15:11:11</td>
      <td>2020-03-17 11:11:11</td>
      <td>2020-03-17 15:11:11</td>
    </tr>
    <tr>
      <td>Date.toString()</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
    </tr>
    <tr>
      <td>Date.toUTCString()</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
      <td>2020-03-17 06:11:11 GMT</td>
    </tr>
  </tbody>
</table>

## Analysis
In that scenario, I insert a record in the database with respective libraries and use for both DATETIME and TIMESTAMP column the following value: new Date('2020-03-17T07:11:11').  
The node application being in a GMT+1 timezone, and considering how javascript date work, I'm expecting the following results for both columns:  

<table>
  <tbody>
    <tr>
      <td>As Displayed In MySql</td>
      <td>2020-03-17 11:11:11</td>
    </tr>
    <tr>
      <td>Date.toString()</td>
      <td>2020-03-17 07:11:11 GMT+0100 &nbsp;</td>
    </tr>
    <tr>
      <td>Date.toUTCString()</td>
      <td>2020-03-17 06:11:11 GMT</td>
    </tr>
  </tbody>
</table>

#### mariadb, mysql and typeorm
Once again, those libs have the same results.  
The DATETIME column provides the expected results as far as I am concerned.  
The TIMESTAMP column gives wrong results.  

#### mikroorm
Has it's own approach here.  
Again as opposed to the other libraries, TIMESTAMP provides the expected values here.  
On the other hand DATETIME column provides wrong result. It looks like for DATETIME column, it will store the local time for the running node app.  

Conclusion
----------
I am by no mean an expert. Do not hesitate to comment, and correct me for whatever.  
As far as I am concerned, I feel like all libraries tested have it wrong in a way or another but one may disagree and prove me wrong.

#### mikroorm
It has it right for TIMESTAMP column using connection driver timezone.  
On the other hand I find their choice for DATETIME columns quite weird. Mikroorm considers DATETIME column value as local timezone date
 (local to the running application) unless you set forceUtcTimezone to true, in which case DATETIME column values will be considered utc dates.
 This is not consistent with the fact that CURRENT_TIMESTAMP as the default value of a DATETIME column will provide current MySql timezone date.

#### mariadb, mysql and typeorm
They got it rigt for the DATETIME column.  
TIMESTAMP handling is completely wrong in my mind.  
DATETIME column is stored as is by mysql. It is therefore a matter of convention. However, TIMESTAMP value is stored in UTC. Therefore there shouldn't be any amiguity regarding its value.

I would appreciate any comments, correction, whatever.

**Comment by jp928** [comment]
Why this is closed?

**Comment by scr4bble** [comment]
Seems like it was closed by the author. @jp928 feel free to open a new issue - we are also having problem with timezone handling in TypeORM (MySQL connection).

**Comment by FredericLatour** [comment]
Hi,
I closed the post because I was wrong.
Typeorm relies on the underlying database driver for timezone management and works properly.
