### ISSUE TITLE
TypeORM cli does not seem seem to understand absolue paths

### ISSUE THREAD

**Issue by tristan957** [typeorm/typeorm#5742]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

TypeORM seems to not understand absolute paths, at least in regard to migrations. Below is output from a migration generation command:

```
/myma-store/server $ TYPEORM_HOST=mariadb TYPEORM_PORT=3306 TYPEORM_USERNAME=root TYPEORM_PASSWORD=yasskin TYPEORM_DATABASE=MYMAStore ./node_modules/.bin/typeorm migration:generate -f ormconfig.js 
-n Helo2
/myma-store/server/src/migration
[ '/myma-store/server/src/migration/*{.ts, .js}' ]
{
  type: 'mariadb',
  host: 'mariadb',
  port: '3306',
  database: 'MYMAStore',
  username: 'root',
  password: 'yasskin',
  synchronize: false,
  entities: [ '/myma-store/server/src/**/*.entity{.ts,.js}' ],
  subscribers: [ '/myma-store/server/src/**/*.subscriber{.ts,.js}' ],
  migrationsRun: true,
  migrationsTableName: 'migration',
  migrations: [ '/myma-store/server/src/migration/*{.ts, .js}' ],
  cli: { migrationsDir: '/myma-store/server/src/migration' }
}
Migration /myma-store/server//myma-store/server/src/migration/1584935706081-Helo2.ts has been generated successfully.
```

This is extremely unexpected behavior. It is concatenating my current path, or maybe it is the path of the ormconfig.js, to an absolute path. The print outs above are me trying to debug what the heck was going on.

`cli.migrationsDir` is causing the issue.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
This should be corrected as of the latest release.

**Comment by tristan957** [comment]
Thanks @imnotjames 😄
