### ISSUE TITLE
Error in SapDriver `loadDependencies` when running in test environment 

### ISSUE THREAD

**Issue by mathiasmaerker** [typeorm/typeorm#5744]
**Issue type:**

[x ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x ] `sap`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So i am not sure if this is really a typeorm problem or  a jest issue. I just noticed when trying to connect t o a Sap Hana Database while running a test
```
import { createConnection } from 'typeorm'
import 'reflect-metadata'

describe('testing the server', () => {
  let application: Application

  beforeAll(async () => {
    const options = await hanaConnectionOptions()
    const connection = await createConnection(options)
    console.log(connection)
  })
```
So what happens is that in SapDriver line 149 `this.loadDependencies()` when requiring `hdb-pool` it returns an empty object and therefor fails later when registering an error handler `                this.client.eventEmitter.on("poolError", poolErrorHandler);` because eventEmitter is undefined

Could you be so kind and give me some insights if this relates to jest or typeorm?

Thanks a lot

**Comment by elsbrock** [comment]
This relates to the way the driver loads its library - you can find an report in the jest issues. There is also a workaround available, add the following line to your jest config:

```ts
// fix jest loading native node module
// hana client relies on process.env.DBCAPI_API_DLL to load DBCAPI
// see node_modules/@sap/hana-client/lib/index.js#L38-54
require("@sap/hana-client");``
