### ISSUE TITLE
Bug in find() 

### ISSUE THREAD

**Issue by stcursi** [typeorm/typeorm#5749]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.22` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi to everyone I want to report this behaviour when I do a simple find on my table:

   const allExperience = await experienceRepository.find({
                select: ["id", "name", "partecipantNumber", "startTime", "endTime", "emailInfo", "emailPre", "emailPost", "emailRecensione", "tappe", "note"]
            });

If I retrieve data specifying every column in my query I receive an error like these: 

I cannot find the column Experience.experienceId in Experience table. When as you can see I've never asked for that field. 

If I ask it in this way: 

   const allExperience = await experienceRepository.find({
       
            });

Everything goes well. 

Why ? Am I missing something ?

**Comment by imnotjames** [comment]
Looks like an environment issue.  Without entity definitions it's hard to replicate.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
