### ISSUE TITLE
Why doesn't this api leftJoinAndSelect work in SQLite?

### ISSUE THREAD

**Issue by bs32g1038** [typeorm/typeorm#575]
I use the following code, but it didn't seem to be working normally.
```
let query = commentRepository
      .createQueryBuilder('comments')
      .leftJoinAndSelect('comments.article_id', 'article')
      .getMany()
```
excute above code , the result is :
`[{
  "id": 1,
  "nick_name": "1",
  "email": "1",
  "content": "1",
  "article_id": {
    "_id": 1,
    "title": "11"
  }
}]`
In my opinion,  the article_id should be replaced by string-"article".
Can you tell me why I met this problem? Thank you!

**Comment by pleerock** [comment]
can you show me your entity? Your Comment particularly

**Comment by bs32g1038** [comment]
well! I list the entity classes. @pleerock 

> entity/article.ts

`import {
    Entity,
    Column,
    PrimaryGeneratedColumn,
    CreateDateColumn,
    UpdateDateColumn,
    OneToMany,
    JoinColumn
} from "typeorm";
import { Comment } from './comment';


`
@Entity()
export class Article {

    @PrimaryGeneratedColumn()
    _id: number;

    @Column({
        nullable: false
    })
    title: string;

    @Column()
    img_url: string;

    @Column()
    category: string;

    @Column()
    summary: string;

    @Column("text")
    content: string;

    @Column({
        default: 0
    })
    visit_count: number;

    @Column({
        default: 0
    })
    comment_count: number;

    @Column({
        default: false
    })
    is_deleted: boolean;

    @Column({
        default: true
    })
    is_pushlied: boolean;

    @CreateDateColumn({
        nullable: true
    })
    create_at: Date;

    @UpdateDateColumn({
        nullable: true
    })
    update_at: Date;

    @Column({
        default: true
    })
    is_html: boolean;

    @OneToMany(type => Comment, Comment => Comment.article_id)
    comments: Comment[];

}`


> entity/comment.ts

 `import {
    Column,
    CreateDateColumn,
    Entity,
    JoinColumn,
    OneToOne,
    PrimaryGeneratedColumn
} from 'typeorm';
import { Article } from './article'
`
`
@Entity()
export class Comment {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        nullable: false
    })
    nick_name: string;

    @Column({
        nullable: false
    })
    email: string;

    @Column({
        nullable: false
    })
    content: string;

    @Column({
        default: ''
    })
    reply: string;

    @OneToOne(type => Article, Article => Article._id)
    @JoinColumn({
        name: 'article_id'
    })
    article_id: number;

    @CreateDateColumn()
    create_at: Date;

    @Column({
        default: true
    })
    pass: boolean;

    @Column()
    identity: number;

}`

> Additional 

the db config code :

` db: {
    driver: {
      type: 'sqlite',
      database: path.resolve(__dirname, '../../database.sqlite'),
    },
    entities: [
      path.resolve(__dirname, "../entity/*.js")
    ],
    autoSchemaSync: true,
  }
`

**Comment by pleerock** [comment]
Thats not how relations are working. Relations are **objects**.

```ts
@OneToOne(type => Article, Article => Article._id)
@JoinColumn({
    name: 'article_id'
})
article_id: number;
```

MUST BE:

```ts
@OneToOne(type => Article, Article => Article._id)
@JoinColumn({ name: 'article_id' })
article: Article;
```

then you can access its id simply: `comment.article.id`

**Comment by pleerock** [comment]
Let me know if you still have questions.
