### ISSUE TITLE
Bad Type using generic for a specific value

### ISSUE THREAD

**Issue by vschoener** [typeorm/typeorm#5755]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So I created a settings table, with 3 columns, `id`, `name:string` and `values:json`.

In the code, the entity looks like this:
```ts
@Entity()
export class Settings<T extends LiteralObject> extends BaseEntity {
  constructor(episode: Partial<Settings<T>>) {
    super();

    Object.assign(this, episode);
  }

  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    unique: true
  })
  name: string;

  @Column({
    type: 'json'
  })
  values: T
}
```

As you've seen, the value is just a generic extending object basically. 

I created a service over this entity to get or upsert the data in the DB:
```ts
import { InjectRepository } from '@nestjs/typeorm';
import { ObjectLiteral, QueryFailedError, Repository } from 'typeorm';
import { Settings } from './entity/settings.entity';
import { UNIQUE_VIOLATION_CODE_ERROR } from '../constants/postgres.constant';

export class SettingsService<T extends ObjectLiteral> {
  constructor(
    @InjectRepository(Settings)
    private readonly settingsRepository: Repository<Settings<T>>,
  ) {}

  public async getSetting(name: string): Promise<Settings<T>> {
    return this.settingsRepository.findOne({
      name,
    });
  }

  public async createOrUpdate(name: string, values: T): Promise<Settings<T>> {
    const settings = new Settings<T>({
      name,
      values,
    });

    try {
      return await settings.save();
    } catch (err) {
      if (
        !(
          err.constructor === QueryFailedError &&
          err.code === UNIQUE_VIOLATION_CODE_ERROR
        )
      ) {
        throw err;
      }
    }

    /**
     * This error is ignored for now, I don't get how to fix the type here...
     * TS2322: Type 'T' is not assignable to type 'T extends (infer U)[] ?
     *  QueryDeepPartialEntity<U>[] :
     *  T extends readonly (infer U)[] ?
     *    readonly QueryDeepPartialEntity<U>[] :
     *    (() => string) | QueryDeepPartialEntity<T>'.
     */
    await this.settingsRepository.update(
      {
        name,
      },
      // @ts-ignore
      { values: settings.values },
    );

    return this.settingsRepository.findOne({ name });
  }
}


```

And Finally, when I inject this service in my other service, it looks like this:
```ts
import { Inject } from '@nestjs/common';
import { SettingsService } from '../shared/settings/settings.service';
import { ItunesSettingsType } from './types/itunes-settings.type';

export class ItunesService {
  private settingName = 'itunes';

  constructor(
    @Inject(SettingsService) private readonly settings: SettingsService<ItunesSettingsType>
  ) {}

  public async getSettings() {
    return this.settings.getSetting(this.settingName);
  }

  public async createOrUpdate(settings: ItunesSettingsType) {
    return this.settings.createOrUpdate(this.settingName, settings);
  }
}
```

That way, I can type the values using the Generic. Problem is when I use the update call, I get this error that I really can't understand this time: 
```
Type 'ObjectLiteral' is not assignable to type 'T extends (infer U)[] ? QueryDeepPartialEntity<U>[] : T extends readonly (infer U)[] ? readonly QueryDeepPartialEntity<U>[] : (() => string) | QueryDeepPartialEntity<T>'. 
```

I know it's TS/type issue but it might be related to your type as well.

So why the type doesn't match over my values using Generic and extending an object? From my understanding, it should be.

Here is my repo on the right branch if you want to take a look/clone it and test the behavior. If your remove the // ts-ignore you will get the error.
Otherwise, the code and logic works as expected.

https://github.com/vschoener/vincelivemix/blob/TECH-add_itunes_settings/src/shared/settings/settings.service.ts

I understand the type of the value are incompatible but I'm bit lacking on this one to figure out. (maybe I should post this on stackoverflow, let me know

**Comment by imnotjames** [comment]
For questions or general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
