### ISSUE TITLE
cli-highlight dependency somehow breaks electron prod build

### ISSUE THREAD

**Issue by cooperfrench95** [typeorm/typeorm#5757]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Create electron project using [this](https://github.com/nklayman/vue-cli-plugin-electron-builder)
2. `npm i typeorm`
3. `npm run electron:build`
4. cd into dist_electron folder and run created app image (or whatever exe or dmg thing it creates on windows/mac)
5. Get the following error

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: chalk_1.default.Instance is not a constructor
    at Object.<anonymous> (/tmp/.mount_molteoj6HNLv/resources/app.asar/node_modules/cli-highlight/dist/theme.js:12:13)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/tmp/.mount_molteoj6HNLv/resources/app.asar/node_modules/cli-highlight/dist/index.js:19:15)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
```

**Comment by rsmylski** [comment]
I'm getting the same error, but it's not an electron build, it's just a custom build with typeorm 0.2.20. The odd thing is that I only get this error on our dev server, It runs just fine on my local mac.

**Comment by rsmylski** [comment]
I noticed the issue was which version of cli-highlight ended up getting installed. My local has 2.1.1, which requires chalk: ^2.3.0. However, on the server, it was using 2.1.4, which requires chalk: ^3.0.0, which contains some breaking functionality.

**Comment by cooperfrench95** [comment]
I also have that version, which is a dependency of vue cli.

**Comment by rathboma** [comment]
Same issue here. Similar set up with electron

**Comment by rathboma** [comment]
This is caused by the chalk lib changing it's API. If you force a lower version in your package.json you can work around it.

**Comment by cooperfrench95** [comment]
That did not work for me. How are you forcing the lower version exactly?

**Comment by nkprince007** [comment]
@rathboma could you please post your `package.json` here?

**Comment by cooperfrench95** [comment]
I have a reproduction link here: https://github.com/cooperfrench95/typeorm-issue

**Comment by cooperfrench95** [comment]
I found a solution.

```bash
rm -rf node_modules/
rm -rf dist_electron/
rm package-lock.json
```

Edit your package.json adding the following:
```javascript
"resolutions": {
  "**/cli-highlight": "2.1.4",
  "**/chalk": "3.0.0"
}
```

Then `yarn` and `yarn run electron:build` and it runs.
