### ISSUE TITLE
TYPEORM_SYNCHRONIZE not working

### ISSUE THREAD

**Issue by alvinfebriando** [typeorm/typeorm#5758]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

TYPEORM_SYNCHRONIZE = false still sync to database after application started. I used .env with this configuration

TYPEORM_SYNCHRONIZE = false
TYPEORM_LOGGING = true
TYPEORM_ENTITIES = build/entities/*.js
TYPEORM_ENTITIES_DIR = src/entities
TYPEORM_MIGRATIONS = build/migrations/*.js
TYPEORM_MIGRATIONS_DIR = src/migrations
TYPEORM_MIGRATIONS_RUN = false

Initially i want to use migration but its failed because table already exist, i figured that typeorm automatically sync entities to database even though i set its value to false

**Comment by Stilborg** [comment]
@alvinfebriando I think you have the same problem as I have: https://github.com/typeorm/typeorm/issues/5697

**Comment by alvinfebriando** [comment]
It's turn out that it's just my fault. I pass the connection option to createConnection so my .env conf is not working. So I just delete the option and now it's working
