### ISSUE TITLE
createConnections for different database with their own type is failed

### ISSUE THREAD

**Issue by Yasukity** [typeorm/typeorm#5759]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[* ] `mssql`
[* ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[* ] `0.2.18`

**Steps to reproduce or a small repository showing the problem:**
I'm trying to create multiple connections using ormconfig.js where there is two configurations like these:

module.exports = [
  {
    name: 'default',
    type: 'mysql',
    host: process.env.PORT1,
    database: default_db,
    ..
  },
  {
    name: 'second_con',
    type: 'mssql',
    host: process.env.PORT2,
    database: second_db,
    ..
  }
]

in application code, I'm writing the following code to create connections:
await createConnections()

when building the app, I got this kind of error:
 DataTypeNotSupportedError: Data type "xml" in "table.field" is not supported by "mysql" database.                                       
     at new DataTypeNotSupportedError (/***/DataTypeNotSupportedError.ts:9:9)                  
     at /***/EntityMetadataValidator.ts:83:27                                       
     at Array.forEach (<anonymous>)                                                                                                              
     at EntityMetadataValidator.validate (/***/EntityMetadataValidator.ts:80:36)    
     at /***/EntityMetadataValidator.ts:44:56                                       
     at Array.forEach (<anonymous>)                                                                                                              
     at EntityMetadataValidator.validateMany (/***/EntityMetadataValidator.ts:44:25)
     at Connection.buildMetadatas (/***/Connection.ts:521:33)                             
     at Connection.<anonymous> (/***/Connection.ts:190:18)                                
     at step (/***/tslib.js:136:27) {                                                 
   name: 'DataTypeNotSupportedError',                                                                                                            
   message: 'Data type "xml" in "table.field" is not supported by "mysql" database.'                                                     
 }   

for the table for which this error occurs, I'm specifying database option as second_db for @Entity decorator.
This error happens because this table is regarded as mysql hence mysql does't support xml type.

What I don't get is that:
1. why does typeorm try to use mysql instead of mssql
2. Is there any way to create multiple connections and connect them even if they are with different type(int this case, mysql/mssql)

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by imnotjames** [comment]
(But I think the answer might be to use entity schemas)
