### ISSUE TITLE
EntityMetadataNotFound

### ISSUE THREAD

**Issue by YSOUZAS** [typeorm/typeorm#576]
I've been using version 0.1.0-alpha.8 but when I switched to version 0.1.0-alpha.19, my entity does not work anymore, I'm using mssql in the azure

```ts
import { Entity, Column, Index, PrimaryGeneratedColumn, PrimaryColumn } from "typeorm";

@Entity()
export class Person {
  @PrimaryColumn("text", { generated: true })
  PersonId: string;
  @Column("string")
  personToken: string;
  @Column("string")
  firstName: string;
  @Column("string")
  lastName: string;
}
```

**Comment by pleerock** [comment]
sounds like something impossible. Are you sure its about upgrade? Can you downgrade and check? Can you show your ormconfig or connection options? Usually you have such error when your entities are not connected properly in connection options (paths are wrong or something)

p.s. please format your code properly.

**Comment by YSOUZAS** [comment]
Yes, I went back to the previous version and returned to normal operation.





```
import "reflect-metadata";
import { createConnection, ConnectionOptions, Connection, getConnection } from "typeorm";
import { Person } from "./entities/Person";

const options: ConnectionOptions = {
  type: 'mssql',
  host: '*************',
  username: '**********',
  password: '***********',
  database: '************',
  extra: { options: { encrypt: true } },
  logging: {
    logFailedQueryError: true,
    logQueries: true,
    logSchemaCreation: true,
    logOnlyFailedQueries: true
  },
  autoSchemaSync: false,
  entities: [Person]
};

export class OrmDatabase {
  getConnection(): Promise<Connection> {
    return new Promise<Connection>((resolve, reject) => {
      try {
        return resolve(getConnection());
      } catch (e) {
        createConnection(options).then(connection => {
          return resolve(connection);
        }, () => {
          return reject
        })
      }
    })
  }
}


 src
├─ database
│   └── entities
│      └── Person.ts
│      
└─ repositories
│   └── PersonRepository.ts

**Comment by pleerock** [comment]
**please format your code properly, use \`\`\`ts to do that.**

Sounds like something impossible. This is something your environment specific. What error do you have?

**Comment by YSOUZAS** [comment]
this is the error, just happened when i changed to new version
```js
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): EntityMetadataNotFound: No metadata for "Person" was found.

**Comment by pleerock** [comment]
I have no ideas about this issue so I have to ask you to setup a sample git repository with a smallest possible reproduction of this problem.

**Comment by YSOUZAS** [comment]
well, i don't know why, but when i did a new code using mssql in 4.0.4 version with typeorm 0.1.0-alpha.20, worked, but however this is the repository
https://github.com/YSOUZAS/Issue-TypeOrm-576,
thanks for you support, you have been done a great job.

**Comment by pleerock** [comment]
Sorry I can't allow myself to spend time debugging what you did. You structured something wrong thats why you probably have problems. Please try to reproduce your issue from scratch and reopen issue.

**Comment by foxundermoon** [comment]
i also meet the exception.
