### ISSUE TITLE
Help defining special OneToMany relation through a junction/joining table

### ISSUE THREAD

**Issue by papaiatis** [typeorm/typeorm#5760]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm trying to model three tables:

```
Comments (id, body)
Attachments (id, url)
CommentAttachments (commentId, attachmentId)
```

A comment can have many attachments but an attachment could only belong to a single comment or no comment at all. 

When I retrieve comments I'd like to auto-populate all the associated attachments as well, and this is what I'm struggling to define correctly.

This is what I have so far:

**Comment.ts**
```
@Entity({ name: "comments" })
export class Comment {
  @PrimaryGeneratedColumn("uuid")
  id!: string;

  @Column({ name: "body", type: String, nullable: true })
  body!: string | null;

  // ???
  // attachments: Attachment[];
}
```

**Attachment.ts**
```
@Entity({ name: "attachments" })
export class Attachment {
  @PrimaryGeneratedColumn("uuid")
  id!: string;

  @Column({ name: "url", type: String })
  url!: string;
}
```

**CommentAttachment.ts**
```
@Entity({ name: "comment_attachments" })
export class CommentAttachment {
  @PrimaryColumn({ name: "comment_id", type: "uuid" })
  commentId!: string;

  @OneToOne(() => Comment)
  @JoinColumn({ name: "comment_id" })
  comment!: Comment;

  @PrimaryColumn({ name: "attachment_id", type: "uuid" })
  attachmentId!: string;

  @OneToOne(() => Attachment)
  @JoinColumn({ name: "attachment_id" })
  attachment!: Attachment;
}
```

What I'd like to have is this:

```
const comments = await this.commentRepository.find({ relations: ["attachments"] });
console.log(comments);
/*
  [
    {
      id: "id1",
      body: "some comment",
      attachments: [
        {
          id: "attid1",
          url: "some url"
        }
      ]
    }
  ]
*/
```
Is this possible to do with properly defined entities only?

I'd like to keep the joining table if possible and not introducing an optional `commentId` column in `Attachment` table.

**Comment by ganshiqingyuan** [comment]
you should use @ManyToMany in comments and CommentAttachment.   isn`t it?

**Comment by papaiatis** [comment]
@ganshiqingyuan I think it's not a Many-to-Many relation since an Attachment could only belong to one Comment.

**Comment by ganshiqingyuan** [comment]
> @ganshiqingyuan I think it's not a Many-to-Many relation since an Attachment could only belong to one Comment.

sorry，this should be @ManyToOne. the commentId in Attachment table you don`t need the table CommentAttachments

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
