### ISSUE TITLE
Better Typescript integration in ormconfig?

### ISSUE THREAD

**Issue by brandonchinn178** [typeorm/typeorm#5763]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Question / Feature Request**

Moved from https://github.com/nestjs/typeorm/issues/372

Not sure whether this is a TypeORM thing, or a NestJS thing, or a NestJS/TypeORM integration thing, so I'm making an issue here. Hopefully it can get triaged in the right place, or at least provide a place for people to find in a web search.

Came across this error when configuring NestJS and TypeORM: https://stackoverflow.com/questions/59435293/typeorm-entity-in-nestjs-cannot-use-import-statement-outside-a-module

I would like to use `.ts` migration files, discovering `*.entity.ts` files when using the `typeorm` CLI (as documented by TypeORM, e.g. `"typeorm": "ts-node node_modules/typeorm/cli.js"` in `package.json`), but when running `nest start`, it errors saying that it's trying to load in the Typescript files as Javascript.

```js
// ormconfig.js
{
  ...
  entities: ['**/*.entity.ts'],
  migrations: [migration/*.ts],
}
```

but if I change these to `.js` and run `rm -rf dist`, running `typeorm migration:show` shows no migrations, because I haven't built anything yet. I would like to generate migrations without needing to build anything.

My current solution is to do the following in `package.json`:
```json
{
  "scripts": {
    "typeorm": "TS_NODE=true ts-node node_modules/typeorm/cli.js",
  },
}
```

and then in `ormconfig.js` do:
```js
const IS_TS_NODE = !!process.env.TS_NODE
{
  entities: [IS_TS_NODE ? '**/*.entity.ts' : 'dist/**/*.entity.js'],
  migrations: [IS_TS_NODE ? 'migration/*.ts' : 'dist/migration/*.js'],
}
```

which is... less than ideal.

It would be nice to have either better documentation on how to do this or some better way to specify this type of configuration, which I imagine is a commonly desired configuration.

**Comment by bduff9** [comment]
Yes, I also ran into this exact issue, though it was not clear at all where it was coming from until I removed all the pieces and added them back one by one.  In my case, trying to run a GQL server on serverless framework.  Would love some documentation or something to help future devs pulling their hair out over this issue.

**Comment by robbymichael1** [comment]
I have the same problem. I'm using this way: I set the migrations folders under ./dist/database/migrations/*.js, so I have to build the application, to generate the files in dist folder, after all I can run migration:run. Working, but... 
Someone to help?

**Comment by imnotjames** [comment]
Option 1: Load the entities explicitly and include them in the array.
Option 2: These are [globs](https://npmjs.com/package/glob) so you can use `path.join(__dirname, "migration/*{.ts,.js}")` or similar to match either if they exist.

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
