### ISSUE TITLE
Create, update, and bind one-to-many entities in single db call?

### ISSUE THREAD

**Issue by rhlsthrm** [typeorm/typeorm#5765]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

In the documentation, it's referred to that the [update query builder](https://typeorm.io/#/update-query-builder) and the [relational query builder](https://typeorm.io/#/relational-query-builder) are the most database efficient ways to update entities and create relations. My question is, is it possible to create a new entity and bind it as a relation while updating the original entity all at once? For example, this is how I would do it with normal entities/repositories:

```ts
Entity()
export class Nest {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column("integer")
  numberOfBirds!: number;
  
  @OneToMany(
    (type: any) => Bird,
    (bird: Bird) => bird.nest,
    { cascade: true },
  )
  birds!: Bird[];
}

export class Bird {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column("text")
  color!: string;
  
  @ManyToOne(
    (type: any) => Nest,
    (nest: Nest) => nest.birds,
  )
  nest!: Nest;
}

// inside app logic somewhere:
async function addBirdToNest(nestId: number, color: string) {
  const nest = await this.nestRepository.findOne(nestId);
  const bird = new Bird();
  bird.color = color;
  nest.birds.push(bird);
  await this.nestRepository.save(bird);
}
```

Is there a more performant way to write this query with query builders? Is there any benchmark for what the performance improvement would be?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
