### ISSUE TITLE
Ionic Offline Storage Support

### ISSUE THREAD

**Issue by chrux** [typeorm/typeorm#5769]
Can I use TypeORM with Ionic Offline Storage, https://ionicframework.com/docs/enterprise/offline-storage? If not, how Can I contribute to add drivers?, I would like to be able to use it.

**Comment by imnotjames** [comment]
Unfortunately, we don't natively support that - if you'd like to contibute as a driver you can start working on it similar to the existing cordova driver.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by oweitman** [comment]
If you want to use typeorm in ionic together with SQLite, then this is possible with the capacitor SQLite plugin.
SQLite is supported for android and ios 
For development also saving data in the browser is possible, but needs additional scripts and configuration

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
