### ISSUE TITLE
Impossible to execute the Quick Start

### ISSUE THREAD

**Issue by afontange** [typeorm/typeorm#577]
Hi everybody,

I would like to test typeorm with MySQL 2.13.0 on Visual code studio. The version used is 0.1.0-alpha.19. I have copied your following example 

```ts
import "reflect-metadata";
import {createConnection} from "typeorm";
import {Photo} from "./entity/Photo";

createConnection({
    driver: {
        type: "mysql",
        host: "localhost",
        port: 3306,
        username: "root",
        password: "admin",
        database: "test"
    },
    entities: [
        Photo
    ],
    autoSchemaSync: true,
}).then(connection => {
    // here you can start to work with your entities
}).catch(error => console.log(error));
```
and I have the following message error 

file: 'file:///d%3A/sandbox/nest-test/src/tests/orm/app.ts'
severity: 'Erreur'
message: 'Argument of type '{ driver: { type: "mysql"; host: string; port: number; username: string; password: string; databa...' is not assignable to parameter of type 'ConnectionOptions'.
  Type '{ driver: { type: "mysql"; host: string; port: number; username: string; password: string; databa...' is not assignable to type '**MongoConnectionOptions**'.
    Property 'type' is missing in type '{ driver: { type: "mysql"; host: string; port: number; username: string; password: string; databa...'.'
at: '20,18'
source: 'ts'

I have try to use connectionOptions 

import "reflect-metadata";
import {createConnection} from "typeorm";
import {Photo} from "./entity/Photo";
import {MysqlConnectionOptions} from "../../../node_modules/typeorm/driver/mysql/MysqlConnectionOptions.js";

const connectionOptions: MysqlConnectionOptions = {
    driver: {
        type: "mysql",
        host: "localhost",
        port: 3306,
        username: "root",
        password: "admin",
        database: "test"
    },
    entities: [Photo],
    autoSchemaSync: true
};

and I have the following message

file: 'file:///d%3A/sandbox/nest-test/src/tests/orm/app.ts'
severity: 'Erreur'
message: 'Type '{ driver: { type: "mysql"; host: string; port: number; username: string; password: string; databa...' **is not assignable to type 'MysqlConnectionOptions**'.
  Property 'type' is missing in type '{ driver: { type: "mysql"; host: string; port: number; username: string; password: string; databa...'.'
at: '7,7'
source: 'ts'

I don't understand why it is checking connectionOptions from MongoDb and not MySQL. If there is somebody who can give me an indication, I will be happy.

Thanks in advance.

**Comment by pleerock** [comment]
Can you please try to extract "driver" section into connection options this way:

```ts
createConnection({
        type: "mysql",
        host: "localhost",
        port: 3306,
        username: "root",
        password: "admin",
        database: "test",
    entities: [
        Photo
    ],
    autoSchemaSync: true,
}).then(connection => {
    // here you can start to work with your entities
}).catch(error => console.log(error));
```

**Comment by afontange** [comment]
Thanks for your quick answer : without "driver" the error disappeared. I will continue to evaluate typeorm next week-end. I have another question : is there a way to define unique keys?

**Comment by pleerock** [comment]
yes you can create `@Index({ unique: true })`, you can put index to class and create composite indices, or you can put in on columns. Also you can mark column as unique: `@Column({ unqiue: true })`

**Comment by pleerock** [comment]
I'll close it - let me know if you will still have issues with it.

**Comment by messerbill** [comment]
hi, after updating i recieve the same error...

```
services/database.connection.ts(13,22): error TS2345: Argument of type '{ driver: { type: "mysql"; host: string; port: number; username: string; password: string; databa...' is not assignable to parameter of type 'ConnectionOptions'.
  Type '{ driver: { type: "mysql"; host: string; port: number; username: string; password: string; databa...' is not assignable to type 'MongoConnectionOptions'.
    Property 'type' is missing in type '{ driver: { type: "mysql"; host: string; port: number; username: string; password: string; databa...'.
```

my connectionOptions:

```
{
                  type: "mysql",
                  host: "localhost",
                  port: 3306,
                  username: "root",
                  password: "",
                  database: "myDatabase",
                  entities: [
                      Match
                  ],
                  migrations: [
                      __dirname + "/migrations/*.js"
                  ],
                  cli: {
                      migrationsDir: __dirname + "/migrations",
                      entitiesDir: __dirname + "/models",
                  },
                  autoSchemaSync: true,
              }).then(connection => {
                  DatabaseConnection.connection = connection
                  DatabaseConnection.connection.runMigrations()
                  
              }).catch(error => {
                //console.log(error)
                console.log("WARNING: Database error or warning occured")
              })
```

my IDE tells nothing about error but after trying to compile it fails.

best regards messerbill

**Comment by JoshGlazebrook** [comment]
Is this an issue of the docs being out of date? I also ran into this.

**Comment by pleerock** [comment]
actually latest alpha versions overall are much more stable then 0.0.11 version, so I recommend to use it instead. Some of the docs are out of date unfortunately, I'll fix it once I get more free time (or anyone can help me ;))
