### ISSUE TITLE
neither with postgres not mysql a async foreach(doSomeStuffinRepository) works because pooling issues

### ISSUE THREAD

**Issue by sebsonjura** [typeorm/typeorm#5773]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x`  0.2.24

**Steps to reproduce or a small repository showing the problem:**

add migration 

do something along the lines of

```js
        await originalUnits.forEach(async unit => {
            let lookupUnit = unit
            cnt++
            lookupUnit = await lookupUnit;
            console.log(lookupUnit.id)
            const connection = getConnection();
            const learnUnitRepository = await connection.getRepository(MyUnit);
            const newUnit = await learnUnitRepository.findByIds([lookupUnit.id]);
            console.log('cnt', newUnit)
        });
```

Observations: Mysql and postgres do have problems with connection limits/pooling. 

* setting a  limit in mysql did not work
* There are open tickets for both of them 

Am I doing something wrong? I want to update the n-m relationships for about 1000 Units and a 6K Keywords. Is that not possible? What is the correct way of doing this? How many read and write queries can I do with one typeorm connection? 10? What does happen in cases where I have a 'sleep' in my environment and pools need to be revitalised? 

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [x] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
`forEach` is not automatically a `Promise.all`

`map` + `Promise.all` might get you what you need.

```
        await Promise.all(originalUnits.map(async unit => {
            let lookupUnit = unit
            cnt++
            lookupUnit = await lookupUnit;
            console.log(lookupUnit.id)
            const connection = getConnection();
            const learnUnitRepository = await connection.getRepository(MyUnit);
            const newUnit = await learnUnitRepository.findByIds([lookupUnit.id]);
            console.log('cnt', newUnit)
        }));
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
