### ISSUE TITLE
MsSql + bigint - wrong validation being used by tedious?

### ISSUE THREAD

**Issue by tyler-brandt** [typeorm/typeorm#5777]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.22` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have defined an entity like so:
```
@Entity()
export class Employee extends BaseEntity {
  @PrimaryColumn('bigint')
  id: number;
....
```

when I try to save an employee I receive this error 

```
query failed: SELECT "Employee"."id" AS "Employee_id", ... FROM "employee" "Employee" WHERE "Employee"."id" IN (@0) -- PARAMETERS: [4382863930]
error: RequestError: Validation failed for parameter '0'. Value must be between -2147483648 and 2147483647, inclusive.
```

I have manually checked the mssql database using azure data studio and can confirm that the column is a bigint, and any queries I run manually there (copy/pasting the query generated by typeorm) succeed.

**Comment by dvantage** [comment]
bigint is not a number. If the bigint field type is specified in the database then return string.

**Comment by imnotjames** [comment]
This was more or less answered - not much that can be done here as that's just how `tedious` interprets things.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
