### ISSUE TITLE
Potential error with queryBuilder

### ISSUE THREAD

**Issue by sinclairnick** [typeorm/typeorm#5778]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

As far as I am aware, the two following code snippets are equivalent:

```ts
// (a)
const query = createQueryBuilder()
          .select('*')
          .from(Brand, 'brand')
          .where(`UPPER(name) = UPPER(:name)`, { name });
```

```ts
// (b)
const query = getRepository(Brand)
          .createQueryBuilder('brand')
          .where(`UPPER(name) = UPPER(:name)`, { name });
```
```ts
// for both
...
await query.getOne();
```

however only (b) works as expected, whereas (a) returns undefined. Let me know if I've misunderstood, otherwise consider this a bug report

**Comment by imnotjames** [comment]
Lacking a lot of info here - but what if you get the SQL for both of these?  Via `getSql()`.

For questions, support, debugging, etc, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
