### ISSUE TITLE
Use entityManager or Repository for bulk insert 

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#578]
Is it better to use a transaction from `entityManager` when doing bulk insert?
I notice that this one is slow when inserting hundreds of rows:
 
````
this.ormRepository.persist(rows)
````
But using  a transaction feels faster:

````
await this.entityManager.transaction(async entityManager => {
        await entityManager.persist(rows)
 })
````
Or are they just the same?

**Comment by NoNameProvided** [comment]
> But using a transaction feels faster

Some basic benchmark from you would help to backup your claim with data, without it, when @pleerock reads this, will probably ask you for it.

**Comment by pleerock** [comment]
If you saving a single object you should not use transaction. If you are saving multiple objects and you need transaction to make sure to revert everything is something went wrong. With your first example transaction is created for each row you are persisting thats why its slower. Its something I'll fix soon - if array of entities is passed is should use a single transaction.

**Comment by pawan-saxena-srijan** [comment]
@pleerock have we added it already  ? ; if not i can try to contribute.
