### ISSUE TITLE
[Q] Variables types in relations

### ISSUE THREAD

**Issue by borabaloglu** [typeorm/typeorm#5784]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi all. I assign relations like this:

```typescript
  @OneToOne(type => Credentials)
  @JoinColumn({ name: 'credentials_id' })
  credentials: Credentials;

  @OneToOne(type => Credentials)
  @JoinColumn({ name: 'username', referencedColumnName: 'username' })
  username: string;
```

Is it a bad practice to assign type "string" instead of "Credentials" to username? This code is implemented like that because I have to create a Credentials object every time for CRUD operations. For example: 

When I assign type string:
```typescript
async findOneByUsername(username: string): Promise<User> {
  const user = await this.userRepository.findOne({ username });

  if (!user) {
    throw new Error('not found');
  }

  return user;
}
```

When I assign type Credentials:
```typescript
async findOneByUsername(username: string): Promise<User> {
  const credentials = new Credentials();
  credentials.username = username;

  const user = await this.userRepository.findOne({ username: credentials });

  if (!user) {
    throw new Error('not found');
  }

  return user;
}
```

First, namings seem bad in "username: credentials", second there is extra 2 lines for creating credentials and assigning username. I can create a constructor in Credentials entity but there will be still an object created am I right?

I am not familiar with OOP and this is my first typescript project. It has to be written in typescript so I am trying to learning it :) So forgive me if I am asking a stupid question.

Waiting for your replies, thanks!

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
