### ISSUE TITLE
No migrations pending (NestJS application)

### ISSUE THREAD

**Issue by dh627** [typeorm/typeorm#5788]
**Issue type:**

[X ] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I created a new Nest application, and am trying to migrate some tables. Inside the application, i've not really done much other than configure my ormconfig.json file (so the application is very bare & untouched):

`{
    "type": "mysql",
    "host": "localhost",
    "port": 8889,
    "username": "root",
    "password": "root",
    "database": "activity_logger",
    "entities": ["__dirname + '../**/*.entity.{js,ts}"],
    "migrations": ["__dirname + '../**/*.{js,ts}"],
    "synchronize": true,
    "cli": {
        "entitiesDir": "src/entity",
        "migrationsDir": "src/migrations"
    }
}`

My application successfully connects to the database, and when I run the command to create a migration file, it successfully creates one.

However, if I try to run that migration, it tells me that 'no migrations are pending' and I really have no idea why. Can anyone help? I've looked through other issues where people have had this same problem, but nothing suggested helped me.

**Comment by talesmgodois** [comment]
Same is happening to me. Can you paste your database configuration file?

**Comment by jpbamberg1993** [comment]
Are you generating your migrations?
Do your compiled migrations, i.e. .js files, live in the specified directory? `"migrations": ["__dirname + '../**/*.{js,ts}"]`
My config has this:
```
  migrations: [
    "dist/src/migration/*.js"
  ],
```
I have to run 
```
$ npm run typeorm -- migration:generate -n NameOfMigration
$ npm run build // this will compile the ts migrations into .js in the dist dir
$ npm run typeorm -- migration:run
```

**Comment by imnotjames** [comment]
It's difficult to tell if this is a nest issue, an environment issue, or an actual TypeORM issue.  As such, I'm gonna consider this closer to a question and request for support.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by lfernando-silva** [comment]
When I added some jest globals, it changed the build output and, then, the folder structure. So I was getting the same error by the path change.

Update the `migrations` path solved my problem.

**Comment by septiadwihyani** [comment]
I had to try this https://wanago.io/2022/07/25/api-nestjs-database-migrations-typeorm/ and it was work! Maybe u can try this one

**Comment by trungnguyen592** [comment]
I try this migrations: ['dist/src/migrations/**/*{.ts,.js}'], its works
