### ISSUE TITLE
Mongo DB support still Experimental?

### ISSUE THREAD

**Issue by meganoob1337** [typeorm/typeorm#5791]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

In the Documentation the Mongodb support is marked as Experimental - is this still the case or is it a documentation issue?
We are preparing to use it in Production and the experimental annotation makes us question if it would be the right choice, although it is currently working properly.
Could you maybe supply me with some information as to when mongodb support is going to be "non-experimental" 

Would be much appreciated ! Thank you alot :)

**Comment by larsdecker** [comment]
We also use TypeORM together with nestJS. For us it works also well. But in some cases there are small issues.

The general support for mongodb could be better. The main focus of project seems to be as a Wrapper for SQL Databases.  But there exists no real alternatives for the same comfort.

**Comment by meganoob1337** [comment]
Yeah for us it works well also, but our client seems to bother that its listed under "experimental support" thats why i would like some clarification about it, as it would be a hassle to migrate to postgres or something else :D

**Comment by imnotjames** [comment]
`mongodb` will be experimental until we split the drivers out and someone takes up maintenance of the driver more seriously.
