### ISSUE TITLE
onDelete "Cascade" is not working

### ISSUE THREAD

**Issue by sebinq** [typeorm/typeorm#5795]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am not able to make `onDelete: Cascade` working correctly in my project.

So I've got two entity models:

```ts
@Entity()
export class SomeVideo extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @IsNotEmpty()
  @IsString()
  @MaxLength(50, { always: true })
  @Column({ length: 50 })
  name: string;

 
  @IsNotEmpty()
  @ManyToOne(() => File, { onDelete: 'CASCADE' })
  video: File;
}

@Entity()
export class File extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ length: 128, unique: true })
  name: string;

  @Column({ length: 10 })
  ext: string;

  @Column({ length: 25 })
  mime: string;

  @Column({ length: 128 })
  hash: string;

  @AfterRemove()
  deleteFromFilesystem() {
    console.log("Am I here?"); // never
  }
}
```

When I look at created DB schema, I can see that ON DELETE CASCADE property was created for specified column: `CONSTRAINT `FK_c51fac13e86ccf440209dc48974` FOREIGN KEY (`videoId`) REFERENCES `file` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION`

But whenever I try to delete SomeVideo, relevant File record is not deleted from my Database.

Can anyone help me to make it work correctly?

Thank you so much!

**Comment by KennyDurand** [comment]
`ON DELETE` works the reverse way: with your code, if a `File` is deleted, the associated `SomeVideo` will be deleted.

Bear in mind as well that `ON DELETE CASCADE` is a database trigger, and is completely unrelated to TypeORM listeners: it won't trigger the `AfterRemove` event from TypeORM.

**Comment by sebinq** [comment]
@KennyDurand hmm now it feels right, thanks! So if I would like to delete File whenever SomeVideo is deleted, then my only option is to add that logic into server's endpoint, right?

**Comment by KennyDurand** [comment]
I guess File is a generic entity and you can't add the inverse side of the `file` relationship in `File` (like `file.someVideo`) ?

If you can add `file.someVideo` as a `OneToMany` you can add the `cascade: true` option to automatically insert/update/delete videos.
Otherwise, yes deleting it in your endpoint seems to be the way to go.

**Comment by sebinq** [comment]
I have many entities which are in relationship with File so I think File would get a bit verbose after 4. or fifth reversal relationship.
