### ISSUE TITLE
relationships with enums

### ISSUE THREAD

**Issue by architect254** [typeorm/typeorm#5796]
**Issue type:**

[ *] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ *] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ *] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>
is there a way i can use an enum of enititea inside a relationship (one to many).
i have a scenario where i have a group with many members,there are different types of members.

how can i store the different types of members entities in a one to many relationship inside the group entity

**Comment by carlocorradini** [comment]
Can you provide an example?

I think what you are looking for is an enum colum type.

You are using PostregSQL so it's supported.

Look at the example below(from  [TypeORM Docs](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#enum-column-type) ):

```typescript
export enum UserRole {
    ADMIN = "admin",
    EDITOR = "editor",
    GHOST = "ghost"
}

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        type: "enum",
        enum: UserRole,
        default: UserRole.GHOST
    })
    role: UserRole

}
```

Add all your supported caregories in an Enum in the file that describe the entity where you use it.

You can export (! Not default export) the enum if you want.

Hope It helps:blush:

**Comment by imnotjames** [comment]
Looks like this was answered so I'll be closing it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
