### ISSUE TITLE
error when running typeorm with nestjs

### ISSUE THREAD

**Issue by architect254** [typeorm/typeorm#5798]
**Issue type:**

[ ] question
[ *] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[* ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[* ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>
got the following error on running my nestjs application

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'array ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',' at line 1

**Comment by imnotjames** [comment]
Do you have example code?

**Comment by imnotjames** [comment]
Without an example this is very difficult to replicate & correct the issue. 

If you do end up getting a good replication up and running please open a new issue so we can correct the problem as soon as possible!
