### ISSUE TITLE
.save() after overwriting one-to-many relationship does not remove non-included entities

### ISSUE THREAD

**Issue by brandon-leapyear** [typeorm/typeorm#5799]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

We have the following entities:
```ts
class User {
  @PrimaryGeneratedColumn(..)
  id: number

  @OneToMany(() => GroupMember, (groupMember) => groupMember.user, { cascade: true })
  groupMemberships: GroupMember[]
}

class Group {
  @PrimaryGeneratedColumn(..)
  id: number

  @OneToMany(() => GroupMember, (groupMember) => groupMember.group, { cascade: true })
  userMembers: GroupMember[]
}

class GroupMember {
  @PrimaryGeneratedColumn(..)
  id: number

  @ManyToOne(() => Group, (group) => group.userMembers)
  group: Group

  @ManyToOne(() => User, (user) => user.groupMemberships)
  user: User
}
```
Ignore the fact that it's redundant and we could just specify a many-to-many relation between users/groups. Simplifying our code a bit, we're trying to run

```ts
const setGroups = async (userId, groupNames) => {
  const user = await userRepo.findOneOrFail(userId)
  const groups = await groupRepo.find({ name: In(groupNames) })

  user.groupMemberships = groups.map((group) => {
    const groupMember = new GroupMember()
    groupMember.group = group
    groupMember.user = user
    return groupMember
  })

  await userRepo.save(user)
}
```

Aside from the fact that this function tries to re-create group memberships when setting a user to the same groups twice, we're also seeing the behavior:
```ts
await setGroups(user.id, ['group1'])
await setGroups(user.id, ['group2'])

await getGroups(user.id) // ['group1', 'group2']
```

My understanding was that whatever `groupMemberships` is set to, typeorm will do the necessary INSERT/DELETE queries to get the database to match the state here. I can't find any documentation related to this, so feel free to point me to any relevant documentation if this is intended behavior.

Related? https://github.com/typeorm/typeorm/issues/3095

**Comment by david-golightly-leapyear** [comment]
I think this might also be related: https://github.com/typeorm/typeorm/issues/3938

**Comment by brandon-leapyear** [comment]
Ok even after converting to use ManyToMany, this doesn't work:
```ts
  async setGroupsForUser(userId: number, groups: string[]): Promise<User> {
    const user = await this.userRepository.findOneOrFail(userId)

    const groupEntities =
      // SQL 'In([])' throws an error, so we need to explicitly handle this case
      groups.length > 0
        ? await this.groupRepository.find({
            name: In(groups),
          })
        : []

    if (groupEntities.length !== groups.length) {
      const missingGroups = _.difference(groups, _.map(groupEntities, 'name'))
      throw new Error('Non-existent groups: ' + missingGroups.join(', '))
    }

    user.groups = groupEntities

    return this.userRepository.save(user)
  }
```

```ts
@Entity('user', { schema: 'public' })
export class User {
  @PrimaryGeneratedColumn({
    type: 'integer',
    name: 'id',
  })
  id: number

  ...

  @ManyToMany(
    () => Group,
    (group: Group) => group.members
  )
  groups: Group[]
}
```
```ts
@Entity('group', { schema: 'public' })
export class Group {
  @PrimaryGeneratedColumn({
    type: 'integer',
    name: 'id',
  })
  id: number

  ...

  @ManyToMany(
    () => User,
    (user: User) => user.groups
  )
  @JoinTable({
    name: 'group_member',
    joinColumn: {
      name: 'group',
      referencedColumnName: 'id',
    },
    inverseJoinColumn: {
      name: 'user',
      referencedColumnName: 'id',
    },
  })
  members: User[]
}
```
the error happens even if I specify `{ cascade: true }` in either side of the relation

**Comment by brandon-leapyear** [comment]
UPDATE: never mind, we're trying to migrate an existing database schema that we have, so we set `synchronize` to false, but it turns out that our `id` columns are of type `integer`, while the foreign key columns are of type `bigint`, e.g. `user.id` is `integer`, but `group_member.user` is `bigint`. This was causing some sort of lookup miss.
