### ISSUE TITLE
OneToMany with where clause?

### ISSUE THREAD

**Issue by joshuamking** [typeorm/typeorm#580]
So I have two entities that are relevant for this. They are `Organization` and `Group`

```
@Entity()
export class Organization extends EntityModel {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @OneToMany(type => Group, group => group.organization, { cascadeInsert: true, cascadeUpdate: true })
    groups: Group[];
}
```

```
@Entity()
export class Group extends EntityModel {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToOne(type => Group, group => group.subgroups, { cascadeUpdate: true })
    @JoinColumn()
    parent: Group;

    @OneToMany(type => Group, group => group.parent, { cascadeInsert: true, cascadeUpdate: true })
    subgroups: Group[];

    @ManyToOne(type => Organization, organization => organization.groups, { cascadeUpdate: true, onDelete: "SET NULL" })
    @JoinColumn()
    organization: Organization;
}
```

And this works great! But my issue here is that I am trying to do something that MAY not be supported. Let me know if I've just missed the functionality. If the functionality does not exist then I guess this is a feature request.. 

I have it set up so that a `Group` can contain many `Group`s and each `Group` can have a parent which is a `Group` as well. So I want all groups to have an `Organization` but an organization should only have an array of groups that have that `Organization` as their `Organization`, but **NOT** have any parent group. Does this make sense? 

<hr>

In other words, I have the following:

`Organization`
<table>
<tr><th>id</th><th>name</th></tr>
<tr><td>1</td><td>Org 1</td></tr>
<tr><td>2</td><td>Org 2</td></tr>
</table>

`Group`
<table>
<tr><th>id</th><th>name</th><th>parentId</th><th>organizationId</th></tr>
<tr><td>1</td><td>Group 1</td><td>NULL</td><td>1</td></tr>
<tr><td>2</td><td>Group 2</td><td>1</td><td>1</td></tr>
<tr><td>3</td><td>Group 3</td><td>NULL</td><td>2</td></tr>
<tr><td>4</td><td>Group 4</td><td>NULL</td><td>2</td></tr>
</table>
</body>
</html>

<hr>

When I execute the following:
```
Organization
.createQueryBuilder("organization")
.leftJoinAndSelect("organization.groups", "groups")
.getMany()
.then(organizations => {
      // Do stuff with organizations here
      // organizations should contain 2 values

      // organizations[0] will be "Org 1" 
      // organizations[0].group will contain "Group 1" and "Group 2" but I want it to only contain "Group 1"

      // organizations[1] will be "Org 2"
      // organizations[1].group will contain "Group 3" and "Group 4" as desired
});
```

Maybe that makes more sense. :)

So how could I achieve this? Basically I need to be able to create a `where` clause on the `inverseSide` of `OneToMany`

**Comment by pleerock** [comment]
probably first you should ask yourself how to achieve that using sql. How do you do that using sql?

**Comment by joshuamking** [comment]
Okay, well I would do something like this:

```
SELECT * FROM "group" WHERE "organizationId" = 1 AND "parentId" IS NULL;
```

**Comment by joshuamking** [comment]
So I have this:

```
Organization
.createQueryBuilder("organization")
.where("organization.id = :id")
.setParameters(req.params)
.leftJoinAndSelect("organization.groups", "group", "group.parent is null")
.getOne()
```

And it works great. But it would be nice, and I think it makes sense to be able to specify something like that in the model. Am I wrong in this paradigm? Thanks

**Comment by pleerock** [comment]
your query is correct. If you want to have this in model then simply create a method in it with the code you provided.

**Comment by joshuamking** [comment]
Okay well this will work then I guess. Not perfect, but manageable. Thanks
