### ISSUE TITLE
Repository: Increment Multiple Fields by the Same Value

### ISSUE THREAD

**Issue by ctilley83** [typeorm/typeorm#5802]
**Issue type:**

[X] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.24

**Steps to reproduce or a small repository showing the problem:**

I'm working with Repository API to increment the value of a field.  I need to increment multiple column's by the same value. I can increment a single column by the following.

```await productManager.increment(Product, { id: receipt.product.id}, "qty_on_hand", receipt.qty_received);```

Currently ```propertyPath``` only takes a string to update a single field.  Is there a way it could also take an array of strings if you are incrementing multiple columns by the same value similar to the following?

```await productManager.increment(Product, { id: receipt.product.id}, ["qty_on_hand", "qty_available", "qty_received"], receipt.qty_received);```

This would allow me to increment multiple columns with a single statement instead of duplicating ```increment``` 3 times

**Comment by prodoxx** [comment]
Is this available?

**Comment by imnotjames** [comment]
Only one can be done.  If you'd like to do this, you'd need to use the query builder.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
