### ISSUE TITLE
Find constraint violation entity field name

### ISSUE THREAD

**Issue by carlocorradini** [typeorm/typeorm#5806]
**Issue type:**

[ X ] question
[ ] bug report
[ X ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following User Entity:
```typescript
@Entity('user')
export default class User {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({unique: true})
  username!: string;

  @Column({unique: true})
  email!: string;

  @Column()
  name!: string;
}
```

and the following add method in a Controller:

```typescript
public static add(req: Request, res: Response): void {
    const user: User = req.app.locals.user;

    getRepository(User)
      .save(user)
      .then((_user) => {
        res.send(`Added User with id ${_user.id}`);
      })
      .catch((ex) => {
        const NOT_UNIQUE_FIELDS[????] = ?????????
        res.send(`Cannot add User due to not unique fields: ${JSON.stringify(NOT_UNIQUE_FIELDS)}`);
      });
  }
```

If I try to add two users that are exactly the same:
**TypeORM can retrieve an array of not unique fields found instead of a constraint violation message like: _duplicate key value violates unique constraint UQ_78a916df40e02a9deb1c4b75edb_
since I can't find the field it belongs to???**
This can be really helpful in error messages.
Let's take [class-validator](https://github.com/typestack/class-validator) error messages as an example.
Thanks

**Comment by carlocorradini** [comment]
I made a possible solution but I think it's good to implement this programmatically with an array or set of unique fields that belongs to an Entity.
Here is my idea:
```ts
public static async isUniqueOrFail(user: User): Promise<boolean> {
    interface Duplicate {
      field: any;
      value?: string;
      message?: string;
    }

    return new Promise((resolve, reject) => {
      getRepository(User)
        .findOne({
          where: [{ id: user.id }, { username: user.username }, { email: user.email }],
        })
        .then((_user) => {
          const fields = new Set<Duplicate>();

          if (user.id === _user?.id) {
            fields.add({ field: 'id', value: user.id });
          }
          if (user.username === _user?.username) {
            fields.add({ field: 'username', value: user.username });
          }
          if (user.email === _user?.email) {
            fields.add({ field: 'email', value: user.email });
          }

          if (fields.size === 0) resolve(true);
          else reject(new DuplicateError(fields));
        });
    });
  }
```

And use it like:
```ts
public static add(req: Request, res: Response): void {
    const user: User = req.app.locals?.user;

    getRepository(User)
      .isUniqueOrFail(user)
     .save(user)
     .then((_user) => {
        res.send(`Added User with id ${_user.id}`);
      })
     .catch((ex) => {
        // All instanceof check OR ex.name check
        // ex.fields is for example only
        res.json(JSON.stringify(ex.fields));
      });
  }
```

This can be a nice feature.
What do you think?
Thanks in advance

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
