### ISSUE TITLE
Transaction not rolling back on error

### ISSUE THREAD

**Issue by DeciusAntiochus** [typeorm/typeorm#5811]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a route I go into with a set of 'bags', which have to be updated separately in MySQL ; if one error raises on one update (i.e one bag is already used), I'd like to rollback the transaction.

However, I've been fighting since a few hours as, as bags are saved in Promise.all, the ones which are not used (i.e. valid) are updated in the end, and not rolled back....

It seems transaction is not working at all ; what is doing this piece of code is simply saving bags until it finds a bag which can not be saved, then raises the error, but does not rollback...

I've tried to use a transactionalEntityManager approach as well.

```static associateBags = async (req: Request, res: Response) => {
    const { bags, order } = req.body;

    const queryRunner = getConnection().createQueryRunner();
    await queryRunner.connect();
    await queryRunner.startTransaction();

    try {
      let neworder: Order = await queryRunner.manager.findOneOrFail(
        Order,
        order.id.toString()
      );

      await Promise.all(
        bags.map(async (bag: Bag) => {
          let newbag: Bag = await queryRunner.manager.findOneOrFail(
            Bag,
            bag.id.toString()
          );
          if (newbag.order) {
            throw new Error('Sac déjà associé autre part!');
          } else {
            newbag.order = neworder;
            newbag.status = 2;
            await queryRunner.manager.save(newbag);
          }
        })
      );

      neworder.status = 2;
      await queryRunner.manager.save(neworder);

      await queryRunner.commitTransaction();

      res.status(204).send();
    } catch (e) {
      console.log(e);
      await queryRunner.rollbackTransaction();
      res.status(500).send(e);
    } finally {
      await queryRunner.release();
    }
  };
```

**Comment by DeciusAntiochus** [comment]
I found the solution, might be useful for anyone : when using transaction, you **mustn't mix up save and find queries with the transaction manager.** Otherwise, i suppose mysql doesn't know what to rollback, therefore it just commits everything.

**Comment by ejose19** [comment]
This is not a bug, as it's clearly stated many times (and bolded) on https://github.com/typeorm/typeorm/blob/master/docs/transactions.md

**Comment by DeciusAntiochus** [comment]
> This is not a bug, as it's clearly stated many times (and bolded) on https://github.com/typeorm/typeorm/blob/master/docs/transactions.md
> 
> Also, if you're using transaction mode like serializable or repeatable read, don't use the repository manager or you risk getting different results. To avoid any risk, it's better to always use the transaction manager, you can get all your repository methods from there.

I read about 20 times this file, and what is written is the following : 

> All operations MUST be executed using the provided transactional entity manager.

But in fact we shouldn't, if using other operations on database than save,  transaction rollback is broken (?). I had to use the repository manager in order to have a correct rollback.

The following worked : 

```
static associateBags = async (req: Request, res: Response) => {
    const { bags, order } = req.body;

    const queryRunner = getConnection().createQueryRunner();
    await queryRunner.connect();
    await queryRunner.startTransaction();

    try {
      let neworder: Order = await getConnection()
        .getRepository(Order)
        .findOneOrFail(order.id.toString());

      await Promise.all(
        bags.map(async (bag: Bag) => {
          let newbag: Bag = await getConnection()
            .getRepository(Bag)
            .findOneOrFail(bag.id.toString());
          if (newbag.order) {
            throw new Error('Sac déjà associé autre part!');
          } else {
            newbag.order = neworder;
            newbag.status = 2;
            await queryRunner.manager.save(newbag);
          }
        })
      );

      neworder.status = 2;
      await queryRunner.manager.save(neworder);

      await queryRunner.commitTransaction();

      res.status(204).send();
    } catch (e) {
      await queryRunner.rollbackTransaction();
      res.status(500).send(e.message);
    } finally {
      await queryRunner.release();
    }
  };
```

**Comment by ejose19** [comment]
Ok, managed to reproduce what you're saying. But this error is related with using Promise.all like that, you can even remove the .commitTransaction() and the transaction will still get commited. Here's what's happening behind scenes:

All promises start at the same time, you have .findOneOrFail / throw / .save() on each promise which can cause the entire promise to fail, leading to the catch (e) block where you have the .rollbackTransaction, the issue is that rollbackTransaction is executing BEFORE the other promises have finished, leading to the queryRunner.manager.save(newbag); execute OUTSIDE the transaction (and with default being auto-commit, changes are persistent)

My recommendation, don't use Promise.all for things as sensitive as a transaction, even with queryRunner having a check to see if the transaction hasn't ended yet, many queries executing at the same time could lead to race conditions where it still wouldn't be of help. The other option would be to properly wrap the function inside the bags.map to be a proper promise (using resolve, reject) so that the catch block is not reached until all operations have finished, but honestly I'd rather stick with a trusty for (const bag of bags) loop

**Comment by ejose19** [comment]
Sample code for anyone interested in reproducing:
```bash
npm init -y
npm i typescript ts-node typeorm reflect-metadata pg # can be mysql as well
npx typeorm init
```
replace index.ts content with this

```ts
import "reflect-metadata";
import { createConnection } from "typeorm";
import { User } from "./entity/User";

createConnection().then(async connection => {
  connection;
  // await User.insert({ firstName: "a", lastName: "b", age: 30 }); // Use this insert to  first populate
  console.log(await User.find());
  const queryRunner = connection.createQueryRunner();
  await queryRunner.connect();
  await queryRunner.startTransaction();

  try {
    const newUser = await queryRunner.manager.getRepository(User).findOne(1);

    await Promise.all(
      [1, 2, 3].map(async x => {
        const newX = await User.findOne(1);

        if (x === 2) {
          throw "will end transaction";
        }

        newX.firstName = newUser.firstName;
        newX.age = newX.age * 2;
        console.log(x);
        await queryRunner.manager.save(newX);
        console.log(`${x} finished saving`);
      })
    );

    console.log("ok");
  } catch (error) {
    console.log(error);
    await queryRunner.rollbackTransaction();
    console.log("transaction ended");
  } finally {
    await queryRunner.release();
  }
});
```

Add extends BaseEntity to entity/User.ts, dom to lib array in tsconfig.json and adjust ormconfig to your database. Launch the db, populate the first user and then you will get this

```ts
> ts-node src/index.ts

[ User { id: 1, firstName: 'a', lastName: 'b', age: 6000 } ]
1
3
will end transaction
transaction ended
1 finished saving
3 finished saving
```

And on postgres side
```
2020-04-05 23:01:42.850 UTC [206] LOG:  statement: START TRANSACTION
2020-04-05 23:01:42.852 UTC [206] LOG:  execute <unnamed>: SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User"."age" AS "User_age" FROM "user" "User" WHERE "User"."id" IN ($1)
2020-04-05 23:01:42.852 UTC [206] DETAIL:  parameters: $1 = '1'
2020-04-05 23:01:42.856 UTC [208] LOG:  execute <unnamed>: SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User"."age" AS "User_age" FROM "user" "User" WHERE "User"."id" IN ($1)
2020-04-05 23:01:42.856 UTC [208] DETAIL:  parameters: $1 = '1'
2020-04-05 23:01:42.856 UTC [207] LOG:  execute <unnamed>: SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User"."age" AS "User_age" FROM "user" "User" WHERE "User"."id" IN ($1)
2020-04-05 23:01:42.856 UTC [207] DETAIL:  parameters: $1 = '1'
2020-04-05 23:01:42.857 UTC [209] LOG:  execute <unnamed>: SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User"."age" AS "User_age" FROM "user" "User" WHERE "User"."id" IN ($1)
2020-04-05 23:01:42.857 UTC [209] DETAIL:  parameters: $1 = '1'
2020-04-05 23:01:42.858 UTC [206] LOG:  execute <unnamed>: SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User"."age" AS "User_age" FROM "user" "User" WHERE "User"."id" IN ($1)
2020-04-05 23:01:42.858 UTC [206] DETAIL:  parameters: $1 = '1'
2020-04-05 23:01:42.859 UTC [206] LOG:  execute <unnamed>: SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User"."age" AS "User_age" FROM "user" "User" WHERE "User"."id" IN ($1)
2020-04-05 23:01:42.859 UTC [206] DETAIL:  parameters: $1 = '1'
2020-04-05 23:01:42.863 UTC [206] LOG:  statement: ROLLBACK
2020-04-05 23:01:42.863 UTC [206] LOG:  execute <unnamed>: UPDATE "user" SET "age" = $2 WHERE "id" IN ($1)
2020-04-05 23:01:42.863 UTC [206] DETAIL:  parameters: $1 = '1', $2 = '12000'
2020-04-05 23:01:42.865 UTC [206] LOG:  execute <unnamed>: UPDATE "user" SET "age" = $2 WHERE "id" IN ($1)
2020-04-05 23:01:42.865 UTC [206] DETAIL:  parameters: $1 = '1', $2 = '12000'
```

**Comment by imnotjames** [comment]
This is outside the scope of typeorm. We cannot prevent this from failing in this way because of how you are calling the `save`s
