### ISSUE TITLE
How to add the same item twice to a many-to-many table?

### ISSUE THREAD

**Issue by LexSerest** [typeorm/typeorm#5812]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi. How to add the same item twice to a many-to-many table?

example: 
```ts
class User {
    @PrimaryGeneratedColumn()
    id: number;

    @ManyToMany(type => Element, {eager: true, cascade: true})
    @JoinTable()
    elems: Element[];
} 

class Element {
    @PrimaryGeneratedColumn()
    id: number;
   @Column();
    img: string;
} 
```

```ts
let elem1 = new Element();
elem1.img = 'data';
await getManager().save(Element, elem1);

let user1= new User();
user.elems = [elem1, elem1];
await getManager().save(User, user);
```

```ts
let user = await getManager().findOne(User, 1);
console.log(user); // {id:1 , elems: [<only one elem>]}
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
