### ISSUE TITLE
How to find all entities with a certain value in its array element?

### ISSUE THREAD

**Issue by triaton** [typeorm/typeorm#5815]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

My entity contains an array element with enum type.<br>
I have to find all entities with a certain enum value contained in its array element.

Like this.
```ts
enum AccessoryType {
  Patio = 'PATIO',
  DriveWay = 'DRIVE_WAY',
  ...
}

enum MaterialType {
  Granite = 'GRANITE',
  BlueStone = 'BLUE_STONE',
  NaturalStone = 'NATURAL_STONE',
  ...
}

@Injectable()
class IdeaEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  url: string;

  @Column({ type: 'enum', enum: AccessoryType })
  accessoryType: AccessoryType;

  @ApiProperty({ enum: MaterialType, isArray: true })
  @Column({
    type: 'enum',
    enum: MaterialType,
    array: true,
  })
  materialTypes: MaterialType[];
}

function myQueryFunction(accessoryType: AccessoryType, materialTypes: MaterialType[], skip: number, take: number): Promise<IdeaEntity[]> {
  ...

  return ideaRepository.find({
    where: {
      accessoryType: accessoryType,
      materialTypes: {
        contains: materialTypes
      }
    }, skip, take
  });
  ...
}
```
Or at least (with single value provided):
```ts
where: {
  ...
  materialTypes: {
    contains: MaterialType.Granite
  }
  ...
}
```
Is there a way to use typeorm function to achieve this?

**Comment by bhsiaoNFLX** [comment]
Someone posted this workaround: https://github.com/typeorm/typeorm/issues/4023#issuecomment-529486022

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
