### ISSUE TITLE
typeorm droping then adding the same column

### ISSUE THREAD

**Issue by kayisse** [typeorm/typeorm#5818]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24` 

**Steps to reproduce or a small repository showing the problem:**

## Bug Report

each time i start the server typeorm drop some columns and adding them back and it wont start untill i cleare all the table.

## Input Code

```ts
import { Entity, Column, PrimaryGeneratedColumn, BeforeInsert } from 'typeorm';
@Entity('user')
export class UserEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text')
  firstName: string;

  @Column('text')
  lastName: string;

  @Column({
    type: 'text',
    unique: true,
  })
  username: string;

  @Column('text')
  password: string;
  
}
```
## Current behavior

query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'typeorm_metadata'
query: ALTER TABLE "user" DROP CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb"
query: ALTER TABLE "user" DROP COLUMN "username"
query: ALTER TABLE "user" DROP COLUMN "password"
query: ALTER TABLE "user" ADD "username" text NOT NULL
query failed: ALTER TABLE "user" ADD "username" text NOT NULL
error: error: la colonne « username » contient des valeurs NULL

**Comment by AlexMesser** [comment]
This was fixed and released. Please update your TypeORM version to the latest and reopen this issue if the error persists.
