### ISSUE TITLE
How do you specify values when using QueryBuilder's insert()?

### ISSUE THREAD

**Issue by tjme** [typeorm/typeorm#582]
Can't find from the documentation how to specify values to be inserted, and insert() takes no parameter(s).

**Comment by pleerock** [comment]
since `0.1.0-alpha.20` you can do it following way:

```ts
const user = new User();
user.name = "Alex Messer";

await connection.createQueryBuilder()
    .insert()
    .into(User)
    .values(user)
    .execute();
```

or 

```ts
await connection.createQueryBuilder()
    .insert()
    .into(User)
    .values({
        name: "Alex Messer"
    })
    .execute();
```

or

```ts
        await connection
            .getRepository(User)
            .createQueryBuilder("user")
            .insert()
            .values({ name: "Alex Messer" })
            .execute();
```

corresponding test is [here](https://github.com/typeorm/typeorm/blob/61fb5892026a1f4e25cec57de328124d88268389/test/functional/query-builder/insert/query-builder-insert.ts#L20)

**Comment by tjme** [comment]
Many thanks! Option 1 worked for me.

**Comment by Banashek** [comment]
was this removed between `0.1.0-alpha.20` and `0.1.0-apha.33`? I can't seem to get a querybuilder insert to work.

**Comment by Banashek** [comment]
nevermind I had to restart vscode after installing the updated dependency
