### ISSUE TITLE
Dealing with Date times with Postgres in prod and Sqllite for tests.

### ISSUE THREAD

**Issue by davidals** [typeorm/typeorm#5820]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
My production database is Postgresql, I want to write integration tests using In-Memory SQL Lite.
The problem is that there are some entities using Datetimes. Postgres supports `type: 'timestamp'` which is not supported in SqlLite, instead it should have ` type: 'datetime'` which is not supported on PostgreSql.

How can I test on Sqllite without having to change the production code?
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by derSoerrn95** [comment]
Hi, 
you could do the following:

```
const dateType = DB_TYPE === 'postgres' ? 'timestamp' : 'datetime';

@Entity()
export class YourEntity {

  @PrimaryColumn()
  id: number;

  @Column({type: dateType})
  yourDateField: Date;

}
```

Hope it helps

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
