### ISSUE TITLE
[Nest] 487576 [TypeOrmModule] Unable to connect to the database. Retrying (9)...

### ISSUE THREAD

**Issue by RKatarine** [typeorm/typeorm#5822]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi! I have problem with connection to database. On first server application start without erorrs and don't have problems with connection to db. On the second server I have error 'Unable to connect to the database'. On second server I can check connection in manager DB, and it works. What can go wrong?

**Comment by RKatarine** [comment]
This issue was caused by node.js version. With node.js 10.19.0 my app work, but with node.js v 12.x.x - not.

**Comment by AcodeWang** [comment]
Same issue here. works well with node v10.x.x, but can not connect to db from node.js v12.x.x

**Comment by imnotjames** [comment]
Is this still an issue with the latest 0.2.27?

**Comment by AcodeWang** [comment]
@imnotjames 
I just test typeorm 0.2.27 with different node version :

- [x] for "success"  
- [ ]  for "failed"

Node :

- [x] node10.22.1
- [ ] node12.18.4
- [ ] node14.13.0

I got the connection error below :
(node:28254) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)\

[Nest] 28254   - 09/30/2020, 12:11:15 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +15ms
ConnectionError: Failed to connect to 192.168.1.206:1433 - 140273182316416:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1942:
    at Connection.<anonymous> (/home/user/Desktop/vm/project/node_modules/mssql/lib/tedious/connection-pool.js:68:17)
    at Object.onceWrapper (events.js:421:26)
    at Connection.emit (events.js:314:20)
    at Connection.socketError (/home/user/Desktop/vm/project/node_modules/tedious/lib/connection.js:1290:12)
    at Socket.<anonymous> (/home/user/Desktop/vm/project/node_modules/tedious/lib/connection.js:1125:14)
    at Socket.emit (events.js:326:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by imnotjames** [comment]
What's your package. json like for dependency versions

**Comment by AcodeWang** [comment]
@imnotjames 
For me, I am testing it with a Nest.js project

You find my package.json 

{
  "name": "project",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^7.0.0",
    "@nestjs/config": "^0.5.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/platform-express": "^7.0.0",
    "@nestjs/typeorm": "^7.1.0",
    "class-transformer": "^0.3.1",
    "class-validator": "^0.12.2",
    "mssql": "^6.2.1",
    "mysql": "^2.18.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.5.4",
    "typeorm": "^0.2.27"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.0.0",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.0.0",
    "@types/express": "^4.17.3",
    "@types/jest": "25.2.3",
    "@types/node": "^13.9.1",
    "@types/supertest": "^2.0.8",
    "@typescript-eslint/eslint-plugin": "3.0.2",
    "@typescript-eslint/parser": "3.0.2",
    "eslint": "7.1.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-import": "^2.20.1",
    "jest": "26.0.1",
    "prettier": "^1.19.1",
    "supertest": "^4.0.2",
    "ts-jest": "26.1.0",
    "ts-loader": "^6.2.1",
    "ts-node": "^8.6.2",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^3.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}


And here is the code for the DB connection : 

```
import { TypeOrmModule } from '@nestjs/typeorm';

    TypeOrmModule.forRootAsync({
      useFactory: () => ({
        type: <any>String(process.env.DATABASE_TYPE) || 'mssql',
        host: String(process.env.DATABASE_HOST),
        port: Number(process.env.DATABASE_PORT),
        database: String(process.env.DATABASE_DB),
        logging: true,
        // username: 'Administrator',
        // password: 'Suite410',
        // domain: 'WIN-VGJ6OKKRB0K',
        username: String(process.env.DATABASE_USERNAME),
        password: String(process.env.DATABASE_PASSWORD),
        domain: String(process.env.DATABASE_DOMAIN),
        // extra: {
        //   trustedConnection: true,
        //   useUTC: true,
        // },
        entities: ['dist/**/*.entity{.ts,.js}'],
        // synchronize: true,
      }),
    }),
```

**Comment by imnotjames** [comment]
We're using the same version and aren't seeing any issues. I believe this is an issue with the underlying mssql module or below.  You'll need to open an issue there, instead.

Is your mssql server using TLS?  If not you'll want to pass `encrypt: false`


This looks very similar to https://github.com/tediousjs/node-mssql/issues/1053 . Are you using a very old version of SQL Server?  Newer versions of node dropped support for TLS 1.0 which old mssql servers only support.

**Comment by AcodeWang** [comment]
Yes, I am connecting to an outdated SQL Server (2008 R2)

This could be where the issue from. And the `encrypt` option does not help.

It is exact the same with the linked Issue. I think the solution is keep using Node.js v10 for this project.

Thanks again for the support. 😄

**Comment by imnotjames** [comment]
You can also try `--tls-min-v1.0` when running node

https://github.com/nodejs/node/issues/27384

**Comment by imnotjames** [comment]
Given that this isn't an issue with TypeORM I'll be closing the issue.

However, for other questions or help debugging, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by ilaipi** [comment]
> You can also try `--tls-min-v1.0` when running node
> 
> [nodejs/node#27384](https://github.com/nodejs/node/issues/27384)

```sh
node --tls-min-v1.0 app.js
```

this worked for me (node 14.15.1),

thanks very much @imnotjames

**Comment by ayaanqui** [comment]
I was facing a similar problem and using the `mysql2` module helped me. 

```
$ npm install mysql2 --save
$ npm uninstall mysql --save
```

**Comment by DongQinglin** [comment]
For me, it is An Error that the entity directory is fasle.
```
     entities: [__dirname + '/**/entity/*.entity{.ts,.js}'], 
```
Change the directory and You can see it works.

**Comment by AmirMustafa** [comment]
Team, I am anyone facing connection issue with Data source way (TypeORM 0.3)

**src/db/data-source.ts**

`import {
  TypeOrmModuleAsyncOptions,
  TypeOrmModuleOptions,
} from '@nestjs/typeorm';

// import { Tag } from '@app/tag/tag.entity';
import { DataSource, DataSourceOptions } from 'typeorm';

export const dataSourceOptions: DataSourceOptions = {
  migrationsTableName: 'migrations',
  type: 'postgres',
  host: process.env.HOST,
  port: +process.env.PORT,
  username: process.env.USERNAME,
  password: process.env.PASSWORD,
  database: process.env.DATABASE,
  migrations: [__dirname + '\\migrations\\**\\*{.ts,.js}'],

  // entities: [Tag],
  // entities: [__dirname + '/**/*.entity{.ts,.js}'],
  // migrations: [__dirname + '/../database/migrations/*{.ts,.js}'],
  //   cli: {
  //     migrationsDir: __dirname + '/../database/migrations',
  //   },
  // extra: {
  //   charset: 'utf8mb4_unicode_ci',
  // },
  logging: true,
  synchronize: false,
};

const dataSource = new DataSource(dataSourceOptions);
export default dataSource;`

app.module.ts

`
import { forwardRef, Module } from '@nestjs/common';
import { dataSourceOptions } from '@app/db/data-source';
import { AppController } from '@app/app.controller';
import { AppService } from '@app/app.service';
import { TagModule } from '@app/tag/tag.module';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigModule, ConfigService } from '@nestjs/config';
// import { Tag } from './tag/tag.entity';

@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    TypeOrmModule.forRootAsync(dataSourceOptions),
    // forwardRef(() => TagModule),
    // TagModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

`

Nest JS is crashing. Please help me.

**Comment by AmirMustafa** [comment]
<img width="1440" alt="Screenshot 2022-11-27 at 8 27 53 PM" src="https://user-images.githubusercontent.com/15896579/204141899-5deb4701-2f14-43c8-a673-b671faa4f2d4.png">

<img width="1440" alt="Screenshot 2022-11-27 at 8 28 09 PM" src="https://user-images.githubusercontent.com/15896579/204141909-938bb558-f5ff-44f3-9f5f-d301dc15bad8.png">

<img width="1440" alt="Screenshot 2022-11-27 at 8 28 16 PM" src="https://user-images.githubusercontent.com/15896579/204141920-0e6856b2-d567-4027-8667-0312c6c71df2.png">

Please help me fix this issue.

**Comment by damaris-cabanas** [comment]
I am new to docker and I am running into the following problem while trying to run docker-compose
![image](https://user-images.githubusercontent.com/117166814/226115079-a9a3253a-464e-4e8f-aa47-82fc040dd2c4.png)

**Comment by ngxuanhieu97** [comment]
Have you ever checked the setting of `.env` file to connect your database ?

**Comment by cloverink** [comment]
let try with `DATABASE_HOST='host.docker.internal'`

**Comment by MansourWolou** [comment]
facing the same issue

**Comment by valentinesamuel** [comment]
@cloverink solution worked for me

**Comment by RamChhabra21** [comment]
> For me, it is An Error that the entity directory is fasle.
> 
> ```
>      entities: [__dirname + '/**/entity/*.entity{.ts,.js}'], 
> ```
> 
> Change the directory and You can see it works.

this worked for me , thanks

**Comment by harveyconnor** [comment]
For me the entities were in a nest folder so I had to resolve the path
```ts
entities: [path.resolve(__dirname, '/../**/*.entity{.ts,.js}')],
```
