### ISSUE TITLE
Custom constraint names for @Check decorator

### ISSUE THREAD

**Issue by GrayStrider** [typeorm/typeorm#5827]
**Issue type:**

[ ] question
[ ] bug report
[ x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I would like to catch these errors and give appropriate error messages, but since the constraint names are random, I have no way to discern one from the other, except for parsing the error message body, which is far from ideal.
Applies to `@Unique` decorator as well.

**Comment by amirh715** [comment]
I can't believe I don't have this option. Any updates?!

**Comment by iamjoeker** [comment]
You can pass the desired name of the constraint as the first parameter to `@Check`. https://github.com/typeorm/typeorm/blob/6f6bdbd2b760ab3ca56013c4789ddc8f72c63dc6/src/decorator/Check.ts#L11

**Comment by amirh715** [comment]
Yes I realized that. How about FKs? They're as important as Check constraints. @iamjoeker

**Comment by iamjoeker** [comment]
> Yes I realized that. How about FKs? They're as important as Check constraints. @iamjoeker

There is not currently any support for providing a name for a foreign key constraint in the decorator. The names of the constraints are not random. By default they include a SHA1 hash of combined member columns. This allows the migration builder to determine whether the constraint has changed based on the entity definitions. There are two options I can recommend to address your use case.

1. Use `getMetadata` on the connection or entity manager to obtain the entity's metadata. This contains a `foreignKeys` property which is an array of [ForeignKeyMetadata](https://github.com/typeorm/typeorm/blob/master/src/metadata/ForeignKeyMetadata.ts) objects which contains the name of the foreign key as well as the columns and tables used in the constraint.
2. Use a custom naming strategy to provide foreign key names that you prefer. Create a class that extends [DefaultNamingStrategy](https://github.com/typeorm/typeorm/blob/master/src/naming-strategy/DefaultNamingStrategy.ts) and override the `foreignKeyName` method. Pass an instance of your custom naming strategy in the `nameStrategy` property of your TypeORM options. Here is what that method looks like for the default naming strategy https://github.com/typeorm/typeorm/blob/c23c88802cee33e377bc2ce85ed9aa2e6e1c14c8/src/naming-strategy/DefaultNamingStrategy.ts#L83-L91
