### ISSUE TITLE
Windows Authentication for TypeORM gives Connection error: Login failed for user ''

### ISSUE THREAD

**Issue by jeppe89** [typeorm/typeorm#5830]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am trying to connect to a MS SQL Server 2014 with Windows Authentication, but I am getting this error: **ConnectionError: Login failed for user ''**. I have looked at a similar issue #1660 , but I can't figure out the solution from that thread.

I have installed the _mssql_ and _msnodesqlv8_ packages to connect with Windows Authentication as described [here](https://github.com/tediousjs/node-mssql#microsoft--contributors-node-v8-driver-for-nodejs-for-sql-server).

What I am trying to do with TypeORM, which results in the connection error described above:
```ts
import "reflect-metadata";
import { createConnection } from "typeorm";
 
const sqlDriver = require("mssql/msnodesqlv8");

(async () => {
    await createConnection({
        type: "mssql",
        host: "<host>",
        database: "<database>",
        extra: {
            driver: sqlDriver,
            options: {
                trustedConnection: true
            }
        }
    });
})();
```
It works fine if I try to connect with the mssql package and without TypeORM:
```ts 
const sql = require("mssql");
const sqlDriver = require("mssql/msnodesqlv8");

(async () => {
    const config = {
        server: "<host>",
        database: "<database>",
        driver: sqlDriver,
        options: {
            trustedConnection: true
        }
    });
    sql.connect(config).then(() => console.log("connected"));
})();
```
This also works:<br>
Editing the protype function _loadDependencies_ in _node_modules/typeorm/driver/sqlserver/SqlServerDriver.js_:
```ts 
SqlServerDriver.prototype.loadDependencies() = function () {
    try {
        // this.mssql = PlatformTools_1.PlatformTools.load("mssql");
        this.mssql = PlatformTools_1.PlatformTools.load("mssql/msnodesqlv8");
    } catch (e) { // todo: better error for browser env
        throw new DriverPackageNotInstalledError_1.DriverPackageNotInstalledError("SQL Server", "mssql");
    }
}
```

Is there a way to fix this without needing to edit the prototype function _loadDependencies_?

**Comment by onlyreynaldo** [comment]
Thanks, I've been looking for a way to connect using windows authentication.

My code was the next one I got to connect to the bank. At least I didn't make the mistake. Before that I had edited the _SqlServerDriver.js_ file as you did. 

**_src/database/index.ts_**
```typescript
import { createConnection } from 'typeorm';

createConnection();
```

**_ormconfig.json_**
```json
{
  "type": "mssql",
  "host": "<host>",
  "database": "<database>",
  "extra": {
    "driver": "msnodesqlv8",
    "options": {
      "trustedConnection": true
    }
  }
}
```

**_src/server.ts_**
```typescript

import 'reflect-metadata';

import express from 'express';
import routes from './routes';

import './database';

const app = express();

app.use(express.json());
app.use(routes);

app.listen(3333, () => {
  console.log('🚀 Server started on port 3333!');
});
```

**Comment by bredar** [comment]
We are also using this workaround. Not a good solutions, I hope some fix is coming.

**Comment by imnotjames** [comment]
> Thanks, I've been looking for a way to connect using windows authentication.
> 
> My code was the next one I got to connect to the bank. At least I didn't make the mistake. Before that I had edited the _SqlServerDriver.js_ file as you did.
> 
> **_src/database/index.ts_**
> 
> ```ts
> import { createConnection } from 'typeorm';
> 
> createConnection();
> ```
> 
> **_ormconfig.json_**
> 
> ```json
> {
>   "type": "mssql",
>   "host": "<host>",
>   "database": "<database>",
>   "extra": {
>     "driver": "msnodesqlv8",
>     "options": {
>       "trustedConnection": true
>     }
>   }
> }
> ```
> 
> **_src/server.ts_**
> 
> ```ts
> import 'reflect-metadata';
> 
> import express from 'express';
> import routes from './routes';
> 
> import './database';
> 
> const app = express();
> 
> app.use(express.json());
> app.use(routes);
> 
> app.listen(3333, () => {
>   console.log('🚀 Server started on port 3333!');
> });
> ```

Looks like this solves the issues.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by MAST1999** [comment]
The solution here and in #1660 didn't work for me.
Just for the record I also had this problem but I managed to fix it by configuring the connection differently.
```
{
  "type": "mssql",
  "host": "localhost",
  "database": "<database>",
  "username": "<username>",
  "password": "<password>",
  "port": 1435,
  "extra": {
    "validateConnection": false,
    "trustServerCertificate": true
  },
  "synchronize": false,
  "logging": false,
  "entities": ["src/entity/**/*.ts"],
  "migrations": ["src/migration/**/*.ts"],
  "subscribers": ["src/subscriber/**/*.ts"],
  "cli": {
    "entitiesDir": "src/entity",
    "migrationsDir": "src/migration",
    "subscribersDir": "src/subscriber"
  }
}
```
The important part being the `extra` option.
You also need to open the TCP/IP port and enable the SQL Browser for this to work. You can also set the port for the TCP/IP in the SQL Server 2019 Configuration Manager.
![Screenshot 2021-08-06 165236_LI](https://user-images.githubusercontent.com/48868969/128512081-92ea5c82-8f0a-4a58-8ed8-595acd92613a.jpg)
![Screenshot 2021-08-06 165612_LI](https://user-images.githubusercontent.com/48868969/128512147-a795159c-032b-43a5-a1a3-035c306173d5.jpg)


Hope this helps someone.
