### ISSUE TITLE
Access the internal db connection used by typeorm driver to try out mongodb features unimplemented by typrorm

### ISSUE THREAD

**Issue by e-desouza** [typeorm/typeorm#5831]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'd like to try things like commit/transaction/dropCollections etc reusing the same mongodb connection made by TyprORM. One way it to actually implement those changes in TypeORM (https://github.com/typeorm/typeorm/blob/master/src/driver/mongodb/MongoQueryRunner.ts) and send in a pull req but I have an immediate need for these capabilities and want to access the db connection created using the native mongo-driver. I will push those into TypeORM eventually as PRs.

**Example** : https://mongodb.github.io/node-mongodb-native/api-generated/db.html#collections and  ```db.dropCollection``` ( specifically)

**Comment by lucas-wade** [comment]
Is this possible. I would like to use the mongo gridFS.

**Comment by imnotjames** [comment]
You can access it by hitting up the `(connection.driver as MongoDriver).mongodb` but this is more or less unsupported.

---

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
