### ISSUE TITLE
DataTypeNotSupportedError: Data type "Address" in "User.address" is not supported by "sqlite" database.

### ISSUE THREAD

**Issue by Roaders** [typeorm/typeorm#5835]
**Issue type:**

[x ] question
[] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

0.2.24

**Steps to reproduce or a small repository showing the problem:**

Sample Repo

https://github.com/Roaders/nest-getting-started/tree/one2one

I have been unable to get table joins working in typeorm. The issue is demonstrated in the linked repo.

I have a user entity:

```typescript
import { Entity, PrimaryGeneratedColumn, Column, OneToOne } from "typeorm";
import { Address } from "./address.entity";

@Entity()
export class User{

    @PrimaryGeneratedColumn()
    public id: number;

    @Column()
    public name: string;

    @Column()
    public age: number;

    @Column()
    @OneToOne(type => Address)
    public address: Address;
}
```

And when I try to start mey nest app I get:

```
[Nest] 13984   - 04/09/2020, 8:12:24 AM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +45ms
DataTypeNotSupportedError: Data type "Address" in "User.address" is not supported by "sqlite" database.
    at new DataTypeNotSupportedError (D:\dev\nest-getting-started\node_modules\typeorm\error\DataTypeNotSupportedError.js:7:28)
    at D:\dev\nest-getting-started\node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:74:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (D:\dev\nest-getting-started\node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:71:36)
    at D:\dev\nest-getting-started\node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:42:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (D:\dev\nest-getting-started\node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:42:25)
    at Connection.buildMetadatas (D:\dev\nest-getting-started\node_modules\typeorm\connection\Connection.js:497:33)
    at Connection.<anonymous> (D:\dev\nest-getting-started\node_modules\typeorm\connection\Connection.js:127:30)
    at step (D:\dev\nest-getting-started\node_modules\tslib\tslib.js:136:27)
```

I have `reflect-metadata` imported at the top of my entry file and I have 
```
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
```
in my tsconfig (I can see the generated metadata in the js files so reflection definitely not an issue).

What am I doing wrong?

Thanks

**Comment by Roaders** [comment]
I tried this with MySql as well and got exactly the same issue.

**Comment by JZLeung** [comment]
try to delete the `dist` dir, and restart the server.

**Comment by imnotjames** [comment]
You might want to drop the `@Column` on the `address` property.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
