### ISSUE TITLE
Access Active Record Class with String

### ISSUE THREAD

**Issue by totalard** [typeorm/typeorm#5836]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am Using Active Record Feature of Typeorm..
If I have String of Name equal to Active Record Entity Name... How I access the Active Record Class/Entity to Query dB..

Eg.. Entity A is Active Record Entity..

I have "A"..  ///String Not Class

How can I Access A.find().   

Please Somebody Help...

**Comment by rodion-arr** [comment]
You can use [dynamic imports](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports)

```javascript
const entityName = 'A';
const path = `./path_to_entities/${entityName}`;
const entity = await import(path);
```

**Comment by imnotjames** [comment]
This isn't a TypeORM question directly. 

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
