### ISSUE TITLE
How Set Active Record DB Connection From Context

### ISSUE THREAD

**Issue by totalard** [typeorm/typeorm#5837]
**Issue type:**

[X ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am very confused that.. I am using Typeorm in Multi DB Environment. dB is Selected Using some Header Token.. So When I Use Active Record Patten..Everyone I have to use 

`Entity.useConnection(connection);`
To set the connection to the Active Record.

It's it possible to get Connection to active record from request Context at every Request..

For this purpose.. I have extended BaseEntity.. and still not working...

Somebody Help

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
