### ISSUE TITLE
QueryBuilder syntax error at or near \")\"

### ISSUE THREAD

**Issue by gius80** [typeorm/typeorm#5839]
**Issue type:**

[ ] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have three entities,  Car, Dealer and User entity.

They are connected with this kind of relationship:

Car  (0,n) <--> (1) Dealer (1) <--> (1) User

(Car have one dealer, dealers can have 0 or multiple cars, dealer & user are in a oneToOne relation)

I'm using Query Builder in order to work with queries and relations, but sometimes QB generates syntax error.

For example fails because **QB add round bracket** at the end of the query:

```
 const query = this.carRepository
      .createQueryBuilder('car')
      .leftJoinAndSelect('car.dealer', 'dealer')
      .leftJoinAndSelect('dealer.user', 'user')
      .where('user.id = :id)', {
      id: 'MY_ID'
    }).getMany()
```
```
   "exception": {
          "message": "syntax error at or near \")\"",
          "name": "QueryFailedError",
          "length": 92,
          "severity": "ERROR",
          "code": "42601",
          "position": "2497",
          "file": "scan.l",
          "line": "1149",
          "routine": "scanner_yyerror",
          "query": "[...]  WHERE \"user\".\"id\" = $1)",
          "parameters": [
            "9c71aba5-5a97-429f-aaec-6085b8bacb73"
          ]
```

This one works without problems...

```
 const query = this.carRepository
      .createQueryBuilder('car')
      .leftJoinAndSelect('car.dealer', 'dealer')
      .leftJoinAndSelect('dealer.user', 'user')
     .where('user.status IN (:...status)', {
      status: ['ACTIVE', 'SUSPENDED']
    }).getMany()
```

Any ideas?

**Comment by gius80** [comment]
Sorry, I found out that I had a syntax error in my query

**Comment by alexandremulina** [comment]
I got the same error

**Comment by imnotjames** [comment]
> I got the same error

Then please open a new issue with information on how to reproduce this.
