### ISSUE TITLE
Wheres in Many to Many tables with Find Syntax

### ISSUE THREAD

**Issue by cole-robertson** [typeorm/typeorm#5840]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

I am having a similar issue to https://stackoverflow.com/questions/50327383/typeorm-many-to-many-where-clause-on-join-table

https://github.com/typeorm/typeorm/issues/2135

I want to filter my many to many table based on if entity is_deleted column = 0. I can't seem to find a way to do this with the Find syntax. I know I can use the query builder, but I wish not to since it is less strict and clear to me. This is a very common thing to want to do, so I think I might be missing something, but I can't seem to find any way to accomplish this.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
