### ISSUE TITLE
How to only updates the @UpdateDateColumn in Entity

### ISSUE THREAD

**Issue by hiep-dinh** [typeorm/typeorm#5843]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there any way that only updates the @UpdateDateColumn in Entity? I see TypeORM ignore this filed in computeDiffColumns() function.
`
@Entity()
export class Post {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({nullable: false})
    title: string;

    @CreateDateColumn({name: 'created_at', nullable: true})
    createdAt: Date;

    @UpdateDateColumn({name: 'updated_at', nullable: true})
    updatedAt: Date;
}
`

**Comment by tjhiggins** [comment]
+1

**Comment by imnotjames** [comment]
> +1
> 
> Our workaround
> `` transactionalEntityManager.query(`UPDATE "<table_name>" SET updated_at = NOW() where id = '${<id>}'`); ``

You should be using parameters for this.

**Comment by estani** [comment]
I found imo a better way from the repository:
```js
repository.update({id: entity.id}, {});
```
Just provide the primary keys to the first parameter and an empty changeSet as the second.
