### ISSUE TITLE
MariaDb updated affected undefined

### ISSUE THREAD

**Issue by cosinus84** [typeorm/typeorm#5849]
On MariaDb affected is undefined but there is a value of affectedRows on raw object:
`UpdateResult {
  generatedMaps: [],
  raw: OkPacket {
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '(Rows matched: 1  Changed: 1  Warnings: 0',
    protocol41: true,
    changedRows: 1
  }
}`

**Comment by imnotjames** [comment]
Duplicate of #2415
