### ISSUE TITLE
bad date 

### ISSUE THREAD

**Issue by imejiasoft** [typeorm/typeorm#5850]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>
hi, my date is '2020-04-08T06:39:00.000' when i get data typeorm shows me '2020-04-08T10:39:00.000Z' i dont know why if in my database is correct

**Comment by Stelage** [comment]
Hi, 

I think that's because TypeORM use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard in order to display dates.   

So, your date is displayed as UTC date.

**Comment by imejiasoft** [comment]
> Hi,
> 
> I think that's because TypeORM use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard in order to display dates.
> 
> So, your date is displayed as UTC date.

how can i solve it?

**Comment by Stelage** [comment]
Apply your locale on the returned date and it should be enough ;)

**Comment by imejiasoft** [comment]
> Apply your locale on the returned date and it should be enough ;)

mmm i use QueryBuilder how can i do it?
because i dont see any option

**Comment by halain** [comment]
I solved the same problem in the ormconfig.json

`"timezone": "Z",`

**Comment by imejiasoft** [comment]
it didnt work

**Comment by imejiasoft** [comment]
> I solved the same problem in the ormconfig.json
> 
> `"timezone": "Z",`

it didnt work :(

**Comment by imnotjames** [comment]
For questions and support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
