### ISSUE TITLE
Cannot save/update other objects of the same entity inside @AfterInsert hook

### ISSUE THREAD

**Issue by velociraptor111** [typeorm/typeorm#5858]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have an `@AfterInsert` trigger being setup in my model entity. 

Inside the function, when I try to query another object (different id) of the same entity and try to update one of its attribute, the changes is not being saved in the database. 

For example,

```ts
@AfterInsert()
async afterInsert(){
...
const objId = 10
const obj = await connection.getRepository(Post).findOne(objId)
obj.answerCount = 100 
// This line will not actually save it to the database
await connection.getRepository(post).save(obj)

const sameObj = await connection.getRepository(Post).findOne(objId)

// This line will actually print the UPDATED VALUES! but when I check the database, 
// this attribute is actually not updated
console.log(sameObj.answerCount)

// If I uncomment the following line, it will fail the current process. But, interestingly,
// the attribute from before is updated in the database
// throw Error("error")
}
```

After further debugging, I found that if I try to update a different entity in the function, it would do so normally just fine. The only problem is that if I try to update or manipulate any entity of the current entity where the HOOK is defined, it will not update properly in the database.

Also, if I terminate the function before it completes, using `throw new Error(..)` I am able to see the updated values in the database.

It makes me think that there is some sort of process happening after the function ends which reverts the current table to a previous state (?)

**Comment by jamemackson** [comment]
@velociraptor111 did you ever find a solution to this that allows you to create a record related to the record just inserted?

**Comment by velociraptor111** [comment]
Yes, turns out there was something else that was causing this issue in my code. I am still unable to know what the real problem is but after creating a separate test environment and scraping things to bare minimum, I was able to slowly build on top of it and it works normally just fine
