### ISSUE TITLE
How to implement TypeORM in a Web Worker

### ISSUE THREAD

**Issue by saleemepoch** [typeorm/typeorm#5860]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `nativescript`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[^0.2.24] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am working on a NativeScript App and I have managed to get the Worker API working perfectly, in that I send a message from the main thread, the worker receives the message, does a bunch of things and posts a message back to the main thread.

However, as soon as I use a TypeORM instance, nothing comes out of the worker - no postMessage and no console.log, and no exception is thrown, except when I do this:

```
import { getConnection } from "typeorm/browser";
const connection = getConnection().isConnected;
```

The worker throws an exception: 
**Uncaught ConnectionNotFoundError: Connection "default" was not found.**

Has anyone managed to implement this inside a Web Worker successfully?

Here is how I have set up the worker in my project:

https://github.com/NativeScript/worker-loader

**Comment by imnotjames** [comment]
You have to `createConnection` and manage it yourself in the browser context.

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
