### ISSUE TITLE
How to use TypeORM with hot-reloading without running into entity class comparison problems?

### ISSUE THREAD

**Issue by RobbieGM** [typeorm/typeorm#5876]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
When using TypeORM with Next.js, server-side hot-reloading is used by default and is convenient, except for one thing: Every time a hot reload occurs, the code is re-run which results in making rebuilding the entity classes so they are not the "same" as the old versions which are remembered by TypeORM (they don't have referential equality). This leads to `EntityMetadataNotFound` errors when TypeORM compares the new `User` entity to the old `User` entity and finds that they do not match. You can see more on this issue here: https://stackoverflow.com/questions/60677582/entitymetadatanotfound-no-metadata-for-businessapplication-was-found. To fix this I decided to make a new connection on each hot reload like this:
```ts
/**
 * Database manager class
 */
class Database {
  private connectionManager: ConnectionManager;

  /**
   * Keeps track of whether this Database instance remembers making a new connection. If it doesn't,
   * and an existing connection was found anyway, that means that the module was hot-reloaded.
   */
  private hasCreatedConnection = false;

  constructor() {
    this.connectionManager = getConnectionManager();
  }

  private async getConnection(): Promise<Connection> {
    const DEFAULT_CONNECTION_NAME = 'default';
    const currentConnection = this.connectionManager.has(DEFAULT_CONNECTION_NAME)
      ? this.connectionManager.get(DEFAULT_CONNECTION_NAME)
      : undefined;
    // if connection exists but we don't remember creating it, it's because of hot reloading
    // and that means a new connection needs to be created, or else entity metadata won't match
    // from the old session.
    // https://stackoverflow.com/questions/60677582/entitymetadatanotfound-no-metadata-for-businessapplication-was-found
    if (currentConnection && !this.hasCreatedConnection) {
      console.debug('recreating connection due to hot reloading');
      if (currentConnection.isConnected) {
        await currentConnection.close();
      }
      console.debug('done closing, making new connection..');
      return this.createConnectionWithName(DEFAULT_CONNECTION_NAME);
    }
    if (currentConnection) {
      if (!currentConnection.isConnected) {
        return currentConnection.connect();
      } else return currentConnection;
    } else {
      return this.createConnectionWithName(DEFAULT_CONNECTION_NAME);
    }
  }

  private createConnectionWithName(name: string): Promise<Connection> {
    this.hasCreatedConnection = true;
    return createConnection({
      name,
      type: 'postgres',
      url: process.env.DATABASE_URL,
      synchronize: true,
      entities: [Business, Qualification, Customer, BaseOffer, ProductOffer, ServiceOffer]
    });
  }

  public getManager(): Promise<EntityManager> {
    return this.getConnection().then(conn => conn.manager);
  }
}
```
Unfortunately, making a connection to the database is *incredibly* slow (~10 seconds) (and this may be an issue of its own), so every API call now takes a very long time. How do you recommend fixing this?

**Comment by RobbieGM** [comment]
Nevermind, the problem fixed itself (the problem of each database connection taking a super long time). I might reopen this issue if it comes back though.

**Comment by jmaister** [comment]
I am having this problem using TypeORM with Next.js.

    RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?
        at new RepositoryNotFoundError (C:\workspace\fcputbol\node_modules\typeorm\error\RepositoryNotFoundError.js:11:28)
        at EntityManager.getRepository (C:\workspace\fcputbol\node_modules\typeorm\entity-manager\EntityManager.js:660:19)
        at Connection.getRepository (C:\workspace\fcputbol\node_modules\typeorm\connection\Connection.js:343:29)
        at findUser (C:\workspace\fcputbol\.next\server\static\development\pages\teams.js:1040:29)
        at async getServerSideProps (C:\workspace\fcputbol\.next\server\static\development\pages\teams.js:3165:14)
        at async Object.renderToHTML (C:\workspace\fcputbol\node_modules\next\dist\next-server\server\render.js:341:24)
        at async DevServer.renderToHTMLWithComponents (C:\workspace\fcputbol\node_modules\next\dist\next-server\server\next-server.js:651:26)
        at async DevServer.renderToHTML (C:\workspace\fcputbol\node_modules\next\dist\next-server\server\next-server.js:798:28)
        at async DevServer.renderToHTML (C:\workspace\fcputbol\node_modules\next\dist\server\next-dev-server.js:19:539)
        at async DevServer.render (C:\workspace\fcputbol\node_modules\next\dist\next-server\server\next-server.js:540:22)
        at async Object.fn (C:\workspace\fcputbol\node_modules\next\dist\next-server\server\next-server.js:390:17)
        at async Router.execute (C:\workspace\fcputbol\node_modules\next\dist\next-server\server\router.js:134:32)
        at async DevServer.run (C:\workspace\fcputbol\node_modules\next\dist\next-server\server\next-server.js:505:29)
        at async DevServer.handleRequest (C:\workspace\fcputbol\node_modules\next\dist\next-server\server\next-server.js:149:20) {
      name: 'RepositoryNotFoundError',
      message: 'No repository for "User" was found. Looks like this entity is not registered in current "default" connection?'
    }

Using that database.ts class did fix this problem?
How do you initialize the database? Is it initialized on every request ?

**Comment by RobbieGM** [comment]
Using the code I showed earlier, the database is not synchronized on each request but rather on each hot reload (and once when npm dev is first started). It looks like the problems you're having are slightly different from the ones I was having, so idk if the above code will work for you. @jmaister

**Comment by jmaister** [comment]
Thanks @RobbieGM, the code worked for me, I just needed to add the imports...

**Comment by krzysztofwolski** [comment]
@RobbieGM Thank you! I've been pulling hair out of my head because the error was pointing at not registered entities.

Short implementation which I use with my next.js app:
```
import { getConnection, createConnection } from 'typeorm';
import { Registration } from '../xxx/entities/Registration.entity';

let connectionCreated = false;

export async function getOrCreateConnection() {
  // Seems that typeorm is not handling properly database connection and devserver reloading
  // If server reloaded, we are forcing it to close old connection and open new one
  try {
    const currentConnection = await getConnection();
    if (connectionCreated) {
      return currentConnection;
    }
    await currentConnection.close();
  } catch (e) {
    // ignore connection error
  }
  connectionCreated = true;
  return await createConnection({
    name: 'default',
    type: 'sqlite',
    database: 'dev.db',
    entities: [Registration],
    synchronize: true,
    logging: false,
  });
}

```
