### ISSUE TITLE
@Check does not work

### ISSUE THREAD

**Issue by lueenavarro** [typeorm/typeorm#5904]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

@Check decorator does not work. I adds nothing to the entity.

```
import { Check, Column, Entity, PrimaryColumn } from 'typeorm';

@Entity({ name: 'sp_term' })
@Check(`spTermId = 1`)
export class SpTerm {
  @PrimaryColumn({ type: 'int', default: () => `1`, nullable: false })
  spTermId: number;

  @Column()
  retailPrice: number;

  @Column()
  sellingPrice1: number;

  @Column()
  sellingPrice2: number;

  @Column()
  sellingPrice3: number;

  @Column()
  sellingPrice4: number;
}
```

I am creating a table that should have one row only. So I used @check to make sure that only one row exists.

However I can still add other rows with spTermId of 2 and when I checked the create code of the table.

```
CREATE TABLE `sp_term` (
	`spTermId` INT(11) NOT NULL DEFAULT '1',
	`retailPrice` INT(11) NOT NULL,
	`sellingPrice1` INT(11) NOT NULL,
	`sellingPrice2` INT(11) NOT NULL,
	`sellingPrice3` INT(11) NOT NULL,
	`sellingPrice4` INT(11) NOT NULL,
	PRIMARY KEY (`spTermId`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
```

As you can see there's no anything about the check constraint.

**Comment by iamjoeker** [comment]
According to the documentation, the `Check` decorator is not supported for MySQL. https://typeorm.io/#decorator-reference/check

**Comment by Bast1onCZ** [comment]
`Check` constraint is supported by mariadb from version 10.2.1 (see: https://mariadb.com/kb/en/constraint/).

Could someone add it to typeorm please? :)
