### ISSUE TITLE
How to run migrations without cli

### ISSUE THREAD

**Issue by baleksandr48** [typeorm/typeorm#5907]
**Issue type:**
[ ] question
[ ] bug report
[ *] feature request
[ ] documentation issue

I have config in env and must create ormconfig.json file every time when want to run migrations and remove after. Maybe it would be good idea to add possibility to run migrations from js code and pass config in code?

**Comment by regevbr** [comment]
I have the same issue - my config is generated using code with dependency injection and I need to run the migration from code.
The solution is pretty easy - splitting the logic from https://github.com/typeorm/typeorm/blob/master/src/commands/MigrationGenerateCommand.ts into a separate function that can get the connection as a parameter.
My current (and working solution) is to copy the logic from the class I mentioned and provide my own connection

**Comment by baleksandr48** [comment]
@regevbr, wow, sounds good, thank you. Could you give short example how to use it? I can't find this class in `node_modules/typeorm`, so how do you execute it?

**Comment by regevbr** [comment]
it is under node_modules/typeorm/commands/MigrationGenerateCommand.js
But you can't really use it now, so I just copied the relevant sections (hideous I know...)

This is the class I created if you really want to take a look but there is really nothing there
```ts

@injectable()
export class MigrationGenerator extends IMigrationGenerator {
  private readonly logger: ILogger;

  constructor(private readonly connectionProvider: IConnectionProvider, loggerFactory: ILoggerFactory) {
    super();
    this.logger = loggerFactory.getLogger(`Migration Generator`);
  }

  public async isOutOfSync(): Promise<boolean> {
    const connection = await this.connectionProvider.getConnection();
    const sqlInMemory = await connection.driver.createSchemaBuilder().log();
    return sqlInMemory.upQueries.length > 0;
  }

  // https://github.com/typeorm/typeorm/issues/5907
  // https://github.com/typeorm/typeorm/blob/master/src/commands/MigrationGenerateCommand.ts
  public async generateMigrations(): Promise<void> {
    const connection = await this.connectionProvider.getConnection();
    const name = `autoGeneratedMigration`;
    const timestamp = new Date().getTime();
    const file = path.join(__dirname, `..`, `migrations`, `${timestamp}-${name}.ts`);
    const sqlInMemory = await connection.driver.createSchemaBuilder().log();
    const upQueries: string[] = [];
    const downQueries: string[] = [];
    sqlInMemory.upQueries.forEach((upQuery) => {
      upQueries.push(
        `        await queryRunner.query("` +
          upQuery.query.replace(new RegExp(`"`, `g`), `\\"`) +
          `", ` +
          JSON.stringify(upQuery.parameters) +
          `);`
      );
    });
    sqlInMemory.downQueries.forEach((downQuery) => {
      downQueries.push(
        `        await queryRunner.query("` +
          downQuery.query.replace(new RegExp(`"`, `g`), `\\"`) +
          `", ` +
          JSON.stringify(downQuery.parameters) +
          `);`
      );
    });
    if (upQueries.length) {
      const fileContent = getTemplate(name, timestamp, upQueries, downQueries.reverse());
      await fs.promises.writeFile(file, fileContent, `utf-8`);
      this.logger.debug(`Migrations created at ${file}`);
    } else {
      this.logger.debug(`No migrations needed`);
    }
  }
}

const getTemplate = (name: string, timestamp: number, upQueries: string[], downQueries: string[]): string => {
  const migrationName = `${name}${timestamp}`;

  return `import { MigrationInterface, QueryRunner } from "typeorm";

// eslint-disable-next-line @typescript-eslint/class-name-casing
export class ${migrationName} implements MigrationInterface {
  name = '${migrationName}'

  public async up(queryRunner: QueryRunner): Promise<void> {
${upQueries.join(`
`)}
    }

  public async down(queryRunner: QueryRunner): Promise<void> {
${downQueries.join(`
`)}
    }
}
`;
};
```

**Comment by moltar** [comment]
It is actually much more simple. The connection object has a `runMigrations` method:

```ts
await connection.runMigrations()
```

**Comment by regevbr** [comment]
Oh sorry i was talking about generating migrations nit running them, you arw correct. I will open a new issue

**Comment by leonardfactory** [comment]
I should point out that `ormconfig.ts` may be provided as normal TypeScript file (just be sure to use `ts-node`), and it can export a Promise, like 

```ts
async function getConnectionOptions() {
  // You can instantiate DI container here
}
module.exports = getConnectionOptions();
```

**Comment by imnotjames** [comment]
Sounds like this is taken care of!

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
