### ISSUE TITLE
Metadata reflection on circular dependency causes error by referencing class before it's defined in webpack

### ISSUE THREAD

**Issue by RobbieGM** [typeorm/typeorm#5908]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi,
I know this problem is not TypeORM's fault but I figured people who use TypeORM may have run into it at one time or another, especially if using webpack server-side such as with Next.js, as is the case here.

TypeScript always applies decorator metadata right after the class definition, so when you have a circular dependency it has to generate code like this (not exact):
```typescript
// User.ts
import {Post} from "./Post.ts";
class User {
  posts: Post[];
}
Reflect.defineMetadata("design:type", Post, User.prototype, "posts");

// Post.ts
import {User} from "./User.ts";
class Post {
  author: User;
}
Reflect.defineMetadata("design:type", User, Post.prototype, "author");
```
Notice how when webpack concatenates these files together when bundling, whichever file/class comes first will reference the other before it's defined. This has been discussed in the TypeScript issue [here](https://github.com/Microsoft/TypeScript/issues/18080).
What's really weird though is the fact that this only happens in production mode. In development mode, the modules are packed in a way that `Post` would be referred to as `__WEBPACK_IMPORT_BLAH__['Post']` so that error doesn't happen, which is very strange. The webpack config can be found in [this question describing the same problem](https://stackoverflow.com/questions/61297622/typescript-metadata-reflection-references-other-classes-before-they-are-defined). Could someone help me figure out how to configure webpack in the right way here so it works with TypeORM? Thanks.

**Comment by jmaister** [comment]
Another question regarding this issue, event that it does not fail to me.
Should all the classes be defined in the same file to avoid circular dependencies?

**Comment by RobbieGM** [comment]
@jmaister No you shouldn't have to do that.
