### ISSUE TITLE
'Relation "photos.url" was not found, please check if it is correct and really exist in your entity.

### ISSUE THREAD

**Issue by t-heu** [typeorm/typeorm#5912]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.24` (or put your version here)

FindRelationsNotFoundError: Relation "photos.url" was not found, please check if it is correct and really exist in your entity

if I call only `relations: ["photos"]` it brings all the data but I just want "url"

```
const users = await repoUser.find({
    select: ['email', 'username'],
    relations: ["photos", "photos.url"],
})
```

Entitys
- Photo
```
@Entity()
export class Photo {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  url: string;

  @ManyToOne(type => User, user => user.photos)
  user: User;
}
```
- User
```
@Entity('User')
export class User {
    @PrimaryGeneratedColumn('uuid')
    id: string

    @Column()
    username: string;

    @Column()
    email: string;

    @Column()
    password: string;

    @CreateDateColumn({ type: 'timestamp' })
    createdAt: Date;

    @UpdateDateColumn({ type: 'timestamp' })
    updatedAt: Date;

    @OneToMany(type => Photo, photo => photo.user)
    photos: Photo[];

    @BeforeInsert()
    async hashPassword(): Promise<void> {
      const hash = await bcrypt.hash(this.password, 8)
      this.password = hash
    }
}
```

**Comment by dev-cardenas** [comment]
Same error

**Comment by matheusleandroo** [comment]
Same error here too

**Comment by GitVijayDv** [comment]
Not resolved…still

**Comment by imnotjames** [comment]
`relations` is just for specifying what relations you'd like to join. `photos.url` is not a relation.  Try `select` instead.

If you'd like to request a new feature please open a new issue with an explicit request and desired API

**Comment by kodunmi** [comment]
Still same error
