### ISSUE TITLE
How to add uuid as default value using migrations  at the MySQL

### ISSUE THREAD

**Issue by maiaraborges** [typeorm/typeorm#5928]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.24` (or put your version here)

How could I add uuid_generate_v4() as a default value using typeorm migrations

```
import { MigrationInterface, QueryRunner, Table } from 'typeorm';

export default class CreateAppointments1587431673525
  implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'appointments',
        columns: [
          {
            name: 'id',
            type: 'varchar',
            isPrimary: true,
            generationStrategy: 'uuid',
            default: 'uuid_generate_v4()',
          },
        ],
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('appointments');
  }
}

```
errno: 1064,
sql: 'CREATE TABLE `appointments` (`id` varchar(36) NOT NULL DEFAULT uuid_generate_v4(), `provider` varchar(255) NOT NULL, `date` timestamp NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB',
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by jeffaribeiro** [comment]
@maiaraborges, this solution works for me:

`public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'anexo',
        columns: [
          {
            name: 'id',
            type: 'varchar',
            isPrimary: true,
            generationStrategy: 'uuid',
          },
          {
            name: 'descricao',
            type: 'varchar',
            isNullable: false,
          },
          {
            name: 'urlAnexo',
            type: 'varchar',
            isNullable: false,
          },
        ],
      }),
    );
  }`

**Comment by imnotjames** [comment]
Looks like this was answered.  Closing out.
