### ISSUE TITLE
How to use InsertQueryBuilder with entity ids instead of entities for insertion?

### ISSUE THREAD

**Issue by fchu** [typeorm/typeorm#5930]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, I have a question about how to correctly use the `InsertQueryBuilder` when the thing I want to insert has non-nullable foreign keys on another table. Specifically I see the documentation for both `InsertQueryBuilder` and `RelationQueryBuilder` but I am not sure how to use them in combination?

Example:
- `User` table
- `Post` table
- `Like` table, which has 1:n relations to both `User` and `Post` via userId and postId.

I would like to create a new `Link` given a `userId` and a `postId`. Which of  `InsertQueryBuilder` and `RelationQueryBuilder` should I use?

`InsertQueryBuilder` seems to require the full entity in its `value([...])` method, and doesn't allow entity ids. On the flip side `RelationQueryBuilder` allows updating or resetting relations, but not creating objects with foreign keys.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
