### ISSUE TITLE
GENERATE ALWAYS AS in MySQL is not implemented

### ISSUE THREAD

**Issue by tadejgolobic** [typeorm/typeorm#5932]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I believe that implementation of https://github.com/typeorm/typeorm/issues/1377 this issue has not been complete. I know about ```asExpression``` in ```Column``` decorator, however, this decorator should support more options. For example, on that issue, request was to add support for ```GENERATED ALWAYS AS```, apparently, support was added just for ```AS```
https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html

From the source code, specifically, from https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlQueryRunner.ts#L1660 I can see, that there is no option to have ```GENERATED ALWAYS``` before ```AS``` keyword. Is this something that you can improve? Also, if you need help regarding this, I can check this and prepare solution.

But I would also like to know, why didn't you try to implement this in the first case?

**Comment by vedyakov** [comment]
> AS may be preceded by GENERATED ALWAYS to make the generated nature of the column more explicit. 
https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html

This keyword is for clarification only
