### ISSUE TITLE
Get entity table name through class instance of it

### ISSUE THREAD

**Issue by JasonMan34** [typeorm/typeorm#5934]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I need to access the table name of an entity through a class instance of it. So for example:

```ts
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

@Entity('USERS' )
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;
}

const user = new User();

console.log(user.getTableName()) // 'USERS'
```

How would I go about doing this?

**Comment by Vandell63** [comment]
Hey, you got to easy way
`getManager().getRepository(User).metadata.tableName`
OR
extends the User class with the `BaseEntity` from typeorm and do 
`user.getRepository().metadata.tableName`

**Comment by JasonMan34** [comment]
Thank you! I'm not using Active Record so I went with the first option, worked like a charm :)

**Comment by Vandell63** [comment]
@JasonMan34 im happy that it help you 👍

**Comment by runninghare** [comment]
Using getRepository() requires you having a connection. There is actually a static way that you can retrieve the entire Entity metadata from your entity class.

`
import { getMetadataArgsStorage } from 'typeorm';

public findTableFromDecorator(tableClass): string {
   const table = getMetadataArgsStorage().tables.find(t => t.target === tableClass);
   return table?.name
}
`
