### ISSUE TITLE
Typeorm Nest.js warning on circular dependency

### ISSUE THREAD

**Issue by mr-gri3ves** [typeorm/typeorm#5941]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[x] `0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I've installed typeorm with npm like in this tutorial https://docs.nestjs.com/techniques/database,
but after running I receive such warnings of circular dependencies
```
(node:11305) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11305) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:11305) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:11305) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
```
I only added ormconfig.json
```
{
  "type": "mongodb",
  "host": "localhost",
  "port": 3979,
  "database": "something",
  "entities": ["dist/**/*.entity{.ts,.js}"],
  "useUnifiedTopology": true,
  "synchronize": true
}
```
And added to imports in app.module.ts
```
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { TypeOrmModule } from '@nestjs/typeorm';

@Module({
  imports: [
    TypeOrmModule.forRoot()
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {
}
```
How to resolve this warnings??

**Comment by imnotjames** [comment]
That looks like an issue with the nest TypeORM module - not TypeORM itself.

**Comment by imnotjames** [comment]
Going to close this as it seems unrelated to TypeORM itself
