### ISSUE TITLE
Failed to parse SourceMap: ...node/modules/typeorm/browser...

### ISSUE THREAD

**Issue by scottboyd-ai** [typeorm/typeorm#5942]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.24` (or put your version here)

On every page loaded in my application bundled with webpack, I get a large number of warnings in the Chrome dev console saying "DevTools failed to parse SourceMap: webpack:///node_modules/typeorm/browser/...". The warning continues with things like "index.js.map", "connection/ConnectionManager.js.map" and many more. There are probably close to 100 or more of these warnings.

My webpack config includes the FilterWarningsPlugin which is currently excluding mongodb, mssql, mysql, mysql2 and many other systems as recommended by the FAQ page. However, even after adding typeorm to the warnings filter, I still receive these errors.

Is there a way to prevent these warnings from appearing?

**Comment by imnotjames** [comment]
:thinking: We don't generate sourcemaps.  Maybe we should, but not really related to this issue.

We also don't control your webpack config so it's up to you to make the changes that work best for you.

Perhaps you can get help at the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
