### ISSUE TITLE
'pool.autostart' is not a valid option for mssql driver

### ISSUE THREAD

**Issue by dsbert** [typeorm/typeorm#5946]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

There are actually two issues here but the second one supersedes the first one.

According to the [docs](https://typeorm.io/#/connection-options/mssql-connection-options), `pool.autostart` is an option for `mssql` connections which accepts a `boolean` value. However, the code has this with a `number` type as shown [here](https://github.com/typeorm/typeorm/blob/master/src/driver/sqlserver/SqlServerConnectionOptions.ts#L85).

However, none of that actually matters because as far as I can tell, there is no `pool.autostart` option for `mssql`.

[mssql docs](https://github.com/tediousjs/node-mssql#configuration-1)

[tedious docs](http://tediousjs.github.io/tedious/api-connection.html#function_newConnection)

[tarn docs](https://github.com/vincit/tarn.js/#usage)

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
> However, none of that actually matters because as far as I can tell, there is no pool.autostart option for mssql.

:laughing:

**Comment by imnotjames** [comment]
Doesn't look like it's used either.
