### ISSUE TITLE
repeats a line of migration each time i generate a new migration

### ISSUE THREAD

**Issue by AbdessalemLetaief** [typeorm/typeorm#5948]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
i work on NestJs 7, when i try to create a column with type 'double' following the documentation like so 
```
export class Tax extends AbstractEntity {
    @Column("double",{ nullable: false })
    value: number;

    @OneToMany(() => Order, order => order.tax)
    order: Order;

}
```

**Also using type:''double'' like so generates the same problem**
```
@Column({type:''double''})
value: number;
```
i do the migration and create the table it works fine, but the problem is each time i generate another migration it always add's the same line even when i generate an empty migration, this is the line
```
export class SomeMigration1587738372307 implements MigrationInterface {
    name = 'SomeMigration1587738372307'

        await queryRunner.query("ALTER TABLE `tax` CHANGE `value` `value` double NOT NULL", undefined);

    }

    public async down(queryRunner: QueryRunner): Promise<void> {

        await queryRunner.query("ALTER TABLE `tax` CHANGE `value` `value` double(22) NOT NULL", undefined);
    }}
```

now i have multiple columns with double type and each new migration contains a lot of lines like that one, and it causes problems if i ever try to revert a migration.

**Comment by purmonen** [comment]
I have the same problem, and it turns out that specifying a precision on a double is invalid sql syntax so it can't be solved by @Column("double",{ nullable: false, precision: 22 }).

**Comment by purmonen** [comment]
This problem got automatically solved when I upgrade mysql from version 5.7 to 8.0.20.

**Comment by odanado** [comment]
This problem is due to the fact that `NUMERIC_SCALE` in a double type column is `null`.
MysqlDriver gets the fullType here, `column.precision` is `22`, `column.scale` is `null`, so it generates an illegal query, `double(22)`.
https://github.com/typeorm/typeorm/blob/c5143aab08a04e96aebb55996ed7683d48542bbd/src%2Fdriver%2Fmysql%2FMysqlDriver.ts#L663

**Comment by AlexMesser** [comment]
I've tested it and it looks like this was already fixed. Please update your TypeORM version to the latest and reopen this issue if the error persists.
