### ISSUE TITLE
How to make an entire child tree as a flat list within an entity field?

### ISSUE THREAD

**Issue by jeffreyschultz** [typeorm/typeorm#5952]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an group structure that is hierarchical and used to determine access to documents. A Group is basically a node within an organizational structure, and Groups can contain other Groups. The rule is that if a parent Group has access to a document, then every Group under that Group has access as well. Currently, this Group is modeled as a tree within the database. The Document object needs to have a relation within it that is basically a flat list of Groups that have access to the Document. The reason for this is the usage of @nestjsx/crud, which has some authorization capability that can use a relation of an entity to determine access. The User entity has a relation to their Group, so the @nestjsx/crud authorization code makes sure that the User's Group shows up in the Documents list of allowed Groups.

I was hoping this could be done solely within the entity itself, and not have to write any custom repository code, because I am not sure how to interface it with the authorization code at this time. It would take having to override some stuff, I would imagine, which is fine if that's what I have to do.

I think I have explained myself well enough, but I will go ahead and drop in some pseudo entities.

```ts
class User {
    @PrimaryGeneratedColumn({name: 'id'})
    id: number;

    @Column()
    name: string;

    @ManyToOne(() => Group)
    @JoinColumn({ name: 'group_id', referencedColumnName: 'id' })
    group: Group;
}

class Group {
    @PrimaryGeneratedColumn({name: 'id'})
    id: number;

    @Column()
    name: string;

    @ManyToOne(() => Group)
    @JoinColumn({ name: 'parent_id', referencedColumnName: 'id' })
    parent: Group;

    @OneToMany(() => Group, $ => $.parent)
    children: Group;
}

class Document {
    @PrimaryGeneratedColumn({name: 'id'})
    id: number;

    @Column()
    name: string;

    @ManyToOne(() => Group)
    @JoinColumn({ name: 'group_id', referencedColumnName: 'id })
    group: Group;

    groups: Group[] // <-- This needs to be the entire Group tree for Group above with all of its children.
}
```

**Comment by imnotjames** [comment]
You can always create a custom attribute that flattens it.  This is part of typescript, not typeorm.

```
class Foo {
  get bar() { return whatevr_code_you_need }
}
```

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers! @
