### ISSUE TITLE
View entities getManyAndCout() bug

### ISSUE THREAD

**Issue by jagabs** [typeorm/typeorm#5957]
**Issue type:**

[x ] question
[ x] bug report

**Database system/driver:**

[ x] `postgres`

**TypeORM version:**

[ x] `@next`

**Steps to reproduce or a small repository showing the problem:**

I create a view entity..
and i used createQueryBuilder.select().getManyAndCount()

query failed: SELECT COUNT(DISTINCT()) as "cnt" FROM "vw_all_inventory" "vw" WHERE "vw"."tenantid" = $1 AND "vw"."branchid" IN ($2)

it seems "DISTINCT" is applied and its empty.

**Comment by jagabs** [comment]
add @PrimaryColumn()

**Comment by xtrinch** [comment]
Primary column doesn't help for me. Still empty.

**Comment by gabrieledarrigo** [comment]
> Or better explanation: Replace @ViewColumn with @PrimaryColumn

Please, can you explain in detail why this is necessary?
