### ISSUE TITLE
syncronize: Oracle ORA-02275: such a referential constraint already exists in the table

### ISSUE THREAD

**Issue by matzmz** [typeorm/typeorm#5958]
This is the scenario:
**FOO** is the current schema. In this schema I've the table **QC_CONTAINER**. This table has a one-to-many relation with a table **BAR.CONTAINER** belonging to **BAR** schema.
User *FOO* has all required privileges to query and reference **BAR.CONTAINER**. 
For simplicy i've also created a synonym in **FOO** called **CONTAINER** that point to **BAR.CONTAINER**

This scenario is modeled with two entities:
-  Container (syncronize: false)
-  QCContainer (syncronize: true)

The first time I run the application (the schema is empty, the object which exists only, is the synonym I manually created) it starts and create QCContainer .

If i restart the application, i get the following error:
```
query failed: ALTER TABLE "QC_CONTAINER" ADD CONSTRAINT "FK_9dabe9427d3e3c1e3f419cf5f21" FOREIGN KEY ("CONTAINER_FK") REFERENCES "CONTAINER" ("CONTAINER_ID")
PlatformTools.ts:232
error:
PlatformTools.ts:232
Error: ORA-02275: such a referential constraint already exists in the table
```
I've debugged the code and the problem seems to happen in the function **loadTables** of Oracle QueryRunner driver. ([link to code](https://github.com/typeorm/typeorm/blob/e92c743fb54fc404658fcaf2254861b6aa63bd98/src/driver/oracle/OracleQueryRunner.ts#L1169))

**foreignKeysSql** query filters all constraints that are not owned by current user schema owner (in this case **FOO**).

```
"REF_COL"."OWNER" = "C"."R_OWNER"
```

The constraint exists, but get filtered from the query so typeorm try to re-create it throwing the  error which I reported

**Comment by imnotjames** [comment]
This should be fixed in the next release.  This can be confirmed in the latest dev build - `0.2.38-dev.22676a0`
