### ISSUE TITLE
Foreign key column created has quotes (i.e. "userId" instead of userId)

### ISSUE THREAD

**Issue by jpbamberg1993** [typeorm/typeorm#5966]
**Issue type:**

[x] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

user.entity.ts
```ts
@Entity()
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  // more columns removed for brevity 

 @OneToMany(
    type => Task,
    task => task.user,
    { eager: true },
  )
  tasks: Task[];
}
```

task.entity.ts
```ts
@Entity()
export class Task extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;
  
  // more columns removed for brevity

    @ManyToOne(
    type => User,
    user => user.tasks,
    { eager: false },
  )
  user: User;
}
```

In my DB the column created has quotes around it "userId" where as I would just expect it to be userId.

Why are there quotes?
Is this something you would be willing to change.
It's weird to have a totally different column format.

**Comment by moltar** [comment]
Are you saying the actual column name in the DB has quotes or the create statement has quotes?

I have not seen this happen on any version. Please include more code in repro.

Post your connection settings too.

Are you using a custom naming scheme?

**Comment by jpbamberg1993** [comment]
The actual column name, in the database, has quotes around it.
I am not using a custom naming scheme.
Version `"typeorm": "^0.2.24"`
```ts
// typeorm.config.ts
import { TypeOrmModuleOptions } from '@nestjs/typeorm';

export const typeOrmConfig: TypeOrmModuleOptions = {
  type: 'postgres',
  host: 'localhost',
  port: 5432,
  database: 'taskmanagement',
  entities: [__dirname + '/../**/*.entity.{js,ts}'],
  synchronize: true, // * In production this should be false
};
```

```ts
// user.entity.ts
import {
  BaseEntity,
  Column,
  Entity,
  OneToMany,
  PrimaryGeneratedColumn,
  Unique,
} from 'typeorm';
import * as bcrypt from 'bcrypt';
import { Task } from '../tasks/task.entity';

@Entity()
@Unique(['username'])
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  username: string;

  @Column()
  password: string;

  @Column()
  salt: string;

  @OneToMany(
    type => Task,
    task => task.user,
    { eager: true },
  )
  tasks: Task[];

  async validatePassword(password: string): Promise<boolean> {
    const hash = await bcrypt.hash(password, this.salt);
    return hash === this.password;
  }
}
```

```ts
// task.entity.ts
import {
  BaseEntity,
  Column,
  Entity,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { TaskStatus } from './task-status.enum';
import { User } from '../auth/user.entity';

@Entity()
export class Task extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column()
  description: string;

  @Column()
  status: TaskStatus;

  @ManyToOne(
    type => User,
    user => user.tasks,
    { eager: false },
  )
  user: User;
}
```

Here is the [repo](https://github.com/jpbamberg1993/nestjs-task-management)

**Comment by imnotjames** [comment]
I cannot replicate.

Because column names must be lowercase or quoted, psql will display these with quotes, but the column itself will not actually have them.

It also means if you write any queries you MUST escape the column name.

If you don't like this you can use lowercase column names.
