### ISSUE TITLE
"Id" is automagically appended to field name of ManyToOne foreign key in database

### ISSUE THREAD

**Issue by tjme** [typeorm/typeorm#597]
Is there a way to avoid the appending, so the relation name is the same as the database field name?

e.g.:
@ManyToOne(type => Contact)
contactId: number;

Results in a field name of contactIdId !

**Comment by pleerock** [comment]
your relation is incorrect itself, it shall be:

```ts
@manytoone(type => Contact)
contact: Contact;
```

**Comment by tjme** [comment]
Thank you, I should have known that!
