### ISSUE TITLE
Implementation of moving and removing of nodes? 

### ISSUE THREAD

**Issue by SebastianLeuters** [typeorm/typeorm#5974]
Do you have any updates of the implementation of moving and removing existing nodes?

look at:
https://github.com/typeorm/typeorm/blob/e92c743fb54fc404658fcaf2254861b6aa63bd98/src/repository/TreeRepository.ts#L13

**Comment by imnotjames** [comment]
No updates.  Please feel free to open open any PRs or a more actionable issue.
