### ISSUE TITLE
Entity Listeners

### ISSUE THREAD

**Issue by bhavikpatel7023** [typeorm/typeorm#5978]
**Issue type:**
question

**TypeORM version:**
0.2.24

[
<img width="498" alt="Screen Shot 2020-04-30 at 2 53 56 PM" src="https://user-images.githubusercontent.com/13928055/80748145-794c8c80-8af2-11ea-89fe-b21a25520f2e.png">
<img width="631" alt="Screen Shot 2020-04-30 at 2 53 33 PM" src="https://user-images.githubusercontent.com/13928055/80748150-7a7db980-8af2-11ea-9226-034012f8b245.png">
<img width="830" alt="Screen Shot 2020-04-30 at 2 53 18 PM" src="https://user-images.githubusercontent.com/13928055/80748151-7b165000-8af2-11ea-9dce-4c1f0e45d8ed.png">
](url)

I would like to call the validate method beforeInsert and beforeUpdate, it works if I go with ActiveRecord but not working with DataMapper.

**Comment by kateile** [comment]
@bhavikpatel7023 why don't you paste code. I want to help you somehow but I am too lazy to type what I see in those pic and run tests for it.

**Comment by bhavikpatel7023** [comment]
https://github.com/bhavikpatel7023/Hapi-with-TypeORM/blob/master/src/entity/User.ts

https://github.com/bhavikpatel7023/Hapi-with-TypeORM/blob/master/src/controller/user.ts

https://github.com/bhavikpatel7023/Hapi-with-TypeORM/blob/master/src/repository/userRepository.ts

**Comment by bhavikpatel7023** [comment]
@kateile Any update, please?

**Comment by kateile** [comment]
@bhavikpatel7023 I sent pull request. I think that should fix. If you have further question don't hesitate. [https://github.com/bhavikpatel7023/Hapi-with-TypeORM/pull/1](https://github.com/bhavikpatel7023/Hapi-with-TypeORM/pull/1)

**Comment by bhavikpatel7023** [comment]
Thanks for your time. Sure, I will check it.
