### ISSUE TITLE
Way to Specifiy QueryBuilder Type?

### ISSUE THREAD

**Issue by mitchell44** [typeorm/typeorm#598]
Hi,

I am trying to dynamically build update and delete queries using the QueryBuilder and wondering if there is a way to build using the UpdateQueryBuilder and not the SelectQueryBuilder for where and andWhere methods.

Working example of an update:
```
const result = await getEntityManager()
                .getRepository(Customer)
                .createQueryBuilder("customer")
                .update(customer)
                .where('customer.CustomerID LIKE \'%%\'')
                .andWhere('customer.CustomerName LIKE \'%TEST%\'')
                .andWhere('customer.Email LIKE \'%%\'')
                .andWhere('customer.PhoneNumber1 LIKE \'%%\'')
                .andWhere('customer.PhoneNumber2 LIKE \'%%\'')
                .andWhere('customer.PhoneNumber3 LIKE \'%%\'')
                .execute(); // Gives us an Update query
```

What I am attempting to do, but is forcing the ```where``` and ```andWhere``` clauses to automatically go to SelectQueryBuilder.

```
const repo = await getEntityManager().getRepository(Customer);
const updateCustomer = await repo.createQueryBuilder('customer');
let updatedItems = await updateCustomer.update(customer);

                // Iterate through the fields, building the query
                for (let i = 0 ; i < customerFields.length; i++) {
                    // The first field needs to be the where clause
                    if (i === 0) {
                      // Builds query the same way as hard coded,
                      // but are SelectQuerBuilder and not UpdateQueryBuilder therefore throws an error
                       updatedItems += await updateCustomer
                                    .where(QueryDataBuilder('customer', customerFields[i], requestParameters[i]));

                    // The rest need to be and wheres
                    } else {
                      updatedItems +=  await updateCustomer
                                    .andWhere(QueryDataBuilder('customer', customerFields[i], requestParameters[i]));
                    }
                }

await updateItems.execute(); // Does not work due to updateItems try to be assigned 2 different types


```

Any help would be greatly appreciated!

**Comment by pleerock** [comment]
I didn't understand the request. Why are you putting `await` everywhere even where its not needed? What is `QueryDataBuilder` here? Why do you do `updatedItems += ` ? What does it mean? You do something totally wrong.

**Comment by mitchell44** [comment]
Apologies on the ```awaits```, don`t mind them, I was just trying something earlier and copy and pasted the code over as is.

```QueryDataBuilder``` is just a custom function, all it does is dynamically build the query. We know this is not the issues, because it works for ```.getMany()``` because it generates the SelectQueryBuilder select query but not the UpdateQueryBuilder.

So in the case of ```'customer.CustomerID LIKE \'%%\''``` the QueryDataBuilder allows us to pre-define the columns of the entity (ex ```customer```) and the fields (ex ```CustomerID```) we are wanting to build the query for such as ```CustomerID``` and they are just stored in an array and iterated through, in the example above the array is ```customerFields```.

So for an example:
We have ```.createQueryBuilder('customer');```

If we have 2 arrays:
```customerField[0] = "CustomerID" ```
and
```requestParameters[0] = "testCustomer"```

The query data builder basically allows us to take it from hard coded to values and allow us to just change the arrays.

Typical where clause:
```.where('customer.CustomerID LIKE \'%%\'')```
QueryDataBuilder where clause
``` .where(QueryDataBuilder('customer', customerFields[0], requestParameters[0]));```

For ```updatedItems``` I am trying to concatenate the QueryBuilder into 1 statement again since ours is built by iterating through an array of items, which changes between size depending on the entity object as opposed to inline. We are just trying to save time by creating queries dynmically instead of inline to maximize code reuse so we don`t have to keep copying and pasting many different variations and can just implement this instead.

Thanks you for your time pleerock, it is greatly appreciated!

**Comment by pleerock** [comment]
can you provide a simpler example of your problem? BTW you don't need to rewrite query builder, you can do simply:

```ts
const repo = await getEntityManager().getRepository(Customer);
const qb = await repo.createQueryBuilder('customer').update(customer);

for (...) {
    qb.where(...)
}

const results = await qb.getMany();
```

**Comment by mitchell44** [comment]
Ah, so I figured based on your example what I was doing wrong, so thank you! It turns out I was assigning a variable the wrong way, and caused issues

Ill show you what I was doing for sake of closure.

This does work what you showed:
```
const repo = await getEntityManager().getRepository(Customer);
const qb = await repo.createQueryBuilder('customer').update(customer); // Of type UpdateQueryBuilder

for (...) {
    qb.where(...) // Of type UpdateQueryBuilder
}

const results = await qb.execute(); // Executes a UPDATE statement
```
What I was doing which is just 1 change of code, which was messing things up was:
```
const repo = await getEntityManager().getRepository(Customer);
const qb = await repo.createQueryBuilder('customer')
qb.update(customer); // <--- My Mistake
// Of type UpdateQueryBuilder, did not assign it a variable, this was the mistake.

for (...) {
    qb.where(...) // Of type SelectQueryBuilder
}

const results = await qb.execute(); // Executes a SELECT statement instead of an UPDATE statement
```


So what is happening, which I was trying to show earlier but was overly complicated was, but is similar in this situation that due to the last QueryBuilder being a SelectQueryBuilder and not UpdateQueryBuilder, the last statement, which were where clauses, were actually overwriting the ```qb.update()``` since it was not assigned a variable and built on from there.

**Comment by SafalTammewar** [comment]
what to writes in for loop i want to bind where condition on based upon request params
