### ISSUE TITLE
Save ManyToMany in cascade (ER_NO_DEFAULT_FOR_FIELD)

### ISSUE THREAD

**Issue by shindiogo** [typeorm/typeorm#5985]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[x] `0.2.19`

Hi all,
Im trying to create a relation ManyToMany and save as cascade.

**My schema:**
![image](https://user-images.githubusercontent.com/14137669/80799595-2c72bf80-8b9f-11ea-9b7f-9c70a78a2cf9.png)

**And my entities:**

```
@Entity(`global_education_area`)
export class EducationArea {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  @MaxLength(45)
  description: string;

  @ManyToMany(type => EducationDegree, { cascade: true, eager: true })
  @JoinTable({
      name: 'global_education',
      joinColumn: { name: 'id_area', referencedColumnName: 'id' },
      inverseJoinColumn: { name: 'id_degree', referencedColumnName: 'id'},
  })
  degrees: EducationDegree[];
}
```
and 

```
@Entity(`global_education_degree`)
export class EducationDegree {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  @MaxLength(45)
  description: string;
}
```

Problem:

When im tring to save the entity i got the error: 
![image](https://user-images.githubusercontent.com/14137669/80799940-15809d00-8ba0-11ea-85fd-a25a1f2fd54a.png)

This is my entity im trying to save:
![image](https://user-images.githubusercontent.com/14137669/80800017-4660d200-8ba0-11ea-9fac-64618a57c59d.png)

Please, someone have a suggest to solve this problem? This already worked before.

**Comment by luisgarciaalanis** [comment]
I am seeing this problem as well.
It seems that TypeOrm does not like the custom Junction table. If I do not register the entity it works, but I loose the ability to have other columns.

Can you try removing the Junction table from the entities and see if it saves? do not remove it from the database, just from the registration.

**Comment by YES-Lee** [comment]
> I am seeing this problem as well.
> It seems that TypeOrm does not like the custom Junction table. If I do not register the entity it works, but I loose the ability to have other columns.
> 
> Can you try removing the Junction table from the entities and see if it saves? do not remove it from the database, just from the registration.

I tried to remove Junction table registration. It works for save, but doesn't work for update and query because of the default joinColumn name is camalCase, but my column name is underline-styled.

**Comment by shindiogo** [comment]
Hi. @luisgarciaalanis , @YES-Lee ,

This problem is not solved. Use this workaround proposal: 
https://github.com/typeorm/typeorm/issues/3938#issuecomment-670452021
It works. Im using it.

;)

**Comment by YES-Lee** [comment]
Thanks, @shindiogo , Now I maintained the relationship manually.

**Comment by shindiogo** [comment]
This issue was solved!

Check the solution here
https://github.com/typeorm/typeorm/issues/3938#issuecomment-801552622

Thanks everyone.
