### ISSUE TITLE
【bug？？？】createQueryBuilder cache 

### ISSUE THREAD

**Issue by RajanZhan** [typeorm/typeorm#5987]
**Issue type:**

[ ] question
[ *] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[* ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ *] `0.x.x` (^0.2.24)

**Steps to reproduce or a small repository showing the problem:**
mycode:
```ts  
let goodsRepos = getRepository(Goods);
let  result = await goodsRepos.createQueryBuilder("goods")
            .leftJoinAndSelect("goods.cat","category")
            .skip(psize * (page - 1) )
            .take(psize)
            .where({
                status: 1,
            })
           .cache(10000)
            .getManyAndCount()
 ```
the problem is : when I call cache function like " .cache(10000)" ,everything is ok. but  the count of result is always 0 when I call like this " .cache("cache_id".10000)". 
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`
    Also, please format your code properly (by taking code blocks into ```ts  let a = aa ```)
--!>

**Comment by kateile** [comment]
Why don't you format your code properly. Also this could relate to #5983

**Comment by RajanZhan** [comment]
@kateile  thanks for answer,code was formated.

**Comment by kateile** [comment]
@RajanZhan  #5983 please read this issue I think there some resemblance. I have provided workaround in comment

**Comment by RajanZhan** [comment]
@kateile okay ,thanks ,I change the code like this and it is okay.
code :
```ts
.cache({
id:"the id key",
milliseconds:1000
})
```

**Comment by kateile** [comment]
@RajanZhan And remember to use different cache id each time. You may also need this at some point `await connection.queryResultCache.remove([cache_id]);`
Read the docs carefully.

**Comment by RajanZhan** [comment]
@kateile  thanks ,I know ,cache id is changed  when args of function changed

**Comment by kateile** [comment]
good luck

**Comment by RajanZhan** [comment]
@kateile   love typeorm

**Comment by imnotjames** [comment]
Looks like this was resolved.
