### ISSUE TITLE
Count returns incorrect results for multiple primary keys

### ISSUE THREAD

**Issue by dsbert** [typeorm/typeorm#5989]
When using an entity with multiple primary keys, `count()` can return an incorrect result. 

The current behavior of count with primary keys is to `concat` the two keys together and then count the distinct result of that. If the primary keys are of the same data type and can contain the same values, this will result in an incorrect count. See below for an example.

There are other reasons why the current method of `concat` is not desirable, particular regarding performance as it causes indexes to be ignored.

Some related issues

- #5314 
- #4550
- #2535

**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The following example incorrectly returns a count of `1` when there are `2` records

```ts
@Entity()
export class MyEntity {
	@PrimaryColumn()
	field1: number;

	@PrimaryColumn()
	field2: number;
}
```

```js
{
	field1: 11,
	field2: 101
	// concat(field1, field2) = '11101'
},
{
	field1: 1,
	field2: 1101
	// concat(field1, field2) = '11101'
},
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
@dsbert can you confirm that #6870 fixes the issues you're seeing?

**Comment by dsbert** [comment]
@imnotjames I'll look for some time this weekend to confirm.
