### ISSUE TITLE
MongoEntityManager findByIds

### ISSUE THREAD

**Issue by Karnith** [typeorm/typeorm#5994]
expected functionality: when array of objectID strings are passed to findByIds method it should return array of return items from db.

actual behavior: when array of objectID strings are passed to finByIds method an empty array is returned.

mongodb version: 3.5.7
typeorm version: 0.2.24

https://github.com/typeorm/typeorm/blob/e92c743fb54fc404658fcaf2254861b6aa63bd98/src/entity-manager/MongoEntityManager.ts#L146

This prototype seems to be broken. when an objectID hex string is passed to it, rather than an objectID object, the return is id[metadata.objectIdColumn!.propertyName];

the correct return should be new objectIdInstance(id); so that the objectID string is converted to objectID object and passed to createEntityCursor.

**Comment by Karnith** [comment]
better yet would be to remove the if condition and just return (id instanceof objectIdInstance) ? id : new objectIdInstance(id);

this would simplify line 143 https://github.com/typeorm/typeorm/blob/e92c743fb54fc404658fcaf2254861b6aa63bd98/src/entity-manager/MongoEntityManager.ts#L143

**Comment by oussaki** [comment]
@karnit i had to do this 

```
const objectIdInstance = PlatformTools.load("mongodb").ObjectID;
  new objectIdInstance(id)
```
to get it work
