### ISSUE TITLE
Why repository findOne method are returning plain objects?

### ISSUE THREAD

**Issue by thomazmz** [typeorm/typeorm#5996]
**Issue type:**

[x] question

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `0.2.24` 

**Steps to reproduce or a small repository showing the problem:**

Hi everyone! 

I recently realised that when I separate my entity definition from my model class and use the respective repository some methods as `findOne` are returning plain objects instead of model class instances. I would like to know if this is the expected behavior or if I'm losing something on my implementation. 

The following code reproduce the described circunstance:

```ts

import { EntitySchema, createConnection } from 'typeorm'

class Nameable {
  id: number
  name: string
}

const NameableSchema = new EntitySchema<Nameable>({
  name: 'nameable', 
  columns: { 
    id: { type: Number, primary: true, generated: 'increment' },
    name: { type: String }
  }
})

createConnection({
  type: "postgres",
  host: "localhost",
  port: 5432,
  username: "logbook",
  password: "logbook",
  database: "logbook",
  entities: [ NameableSchema ], 
  synchronize: true 
})
.then(databaseConnection => databaseConnection.getRepository<Nameable>(NameableSchema))
.then(nameableRepository => nameableRepository.findOne({ where: { id: 1 }}))
.then(findedNameable => console.log(findedNameable))

```

In this case, considering that I have a persisted tuple in my database which id value is equal to 1, `console.log(findedNameable)` is printing out the following:
```
{ id: 1, name: 'NameableName' }
```

However, I was expecting something like that:
```
Nameable { id: 1, name: 'NameableName' }
```

I have done some tests using decorators in my model class and, for what I could see, in this case, all the instances returned by the repository methods were instances from my correspondent model class. 

What happens is that I really would like o keep my entity definitions separated from my models, so I have not considered to use decorators to solve this problem yet. 

Also, there is nothing in the documentation pointing out that having a separated entity definition would interfere in repository classes behavior.

**Comment by fan-tom** [comment]
I never used such schema separation, but looking only on your code, I cannot understand how typeorm shoult realize that instance of `Nameable` class must be created from POJO? This class mentioned only on type level (`EntitySchema<Nameable>` and `getRepository<Nameable>`), and this means nothing in js, as you know I suppose.

**Comment by fan-tom** [comment]
After looking to typeorm sources I can suppose that you need to pass `target: Nameable` to your schema definition to create such link

**Comment by thomazmz** [comment]
Thank you for your quick answer, @fan-tom! Also thanks for checking it against the source code. 

Your suggested approach indeed solved the problem. But when passing `options.target` as a parameter I also had to call `getRepository<Nameable>('nameable')` and not `getRepository<Nameable>(NameableSchema)`. Which is weird, because for what I could understand from the documentation, the last would be the correct call. 

However, It is curious for me that currently, for any EntitySchema to understand what kind of object it is expected to map to, we need to reference the desired type (class or interface) as a parameter in `options.target`

From my perspective, calling the constructor with `Nameable` as the desired generic type, would be enough information for the EntitySchema to behavior properly. The following example would be in accordance to it:

```ts
const NameableSchema = new EntitySchema<Nameable>({ 
   // Whatever options you want. No need to any target key.
})
```

Also, if you want your EntitySchema not to be mapped to any specific class at all and only "map" to a plain object, them you simply would not specify any generic parameter when calling the EntitySchema constructor . The following example would be in accordance to it: 

```ts
const NameableSchema = new EntitySchema({ 
   // Whatever options you want.
 })
```

Those described behaviors were what I was expecting when I checked the [documentation](https://typeorm.io/#/separating-entity-definition) for independent entity schemas definitions. The last example of the link literally suggest that the returned object would be properly typed without any `properties.target` parameter being passed.

From my perspective, thinking about the way it is implemented now,  I could not understand why would we need to specify any generic parameter and **also** repeat the desired mapping type in an `option.target`. I would say it looks redundant.

**Comment by fan-tom** [comment]
> But when passing options.target as a parameter I also had to call getRepository<Nameable>('nameable') and not  getRepository<Nameable>(NameableSchema)

Why you decided that you cannot call `getRepository<Nameable>(NameableSchema)`?
>From my perspective, calling the constructor with Nameable as the desired generic type, would be enough information for the EntitySchema to behavior properly.

Js doesn't work this way. Types are entirely erased and only used for type check purposes, they don't affect code generation at all, as you may suggest coming from other statically typed language (such as Java, C#, C++ or Kotlin, where type system and, especially, parametric polymorphism(generics) are not built on top of dynamically typed language and can be taken into account on code generation phase). TypeORM needs to know what type map raw values to, but it cannot know it from type parameters, because to create an instance of class you need to call class constructor (which is just function), but to call function you need to have it somewhere as _value_ (when you pass `target`, you do exactly this), but type parameters only refers to _type_ of instances returned, it cannot be used on _value_ level.

From the documentation you provided
```
import {EntitySchema} from "typeorm";

export interface Category {
    id: number;
    name: string;
}

export const CategoryEntity = new EntitySchema<Category>({
    name: "category",
    columns: {
        id: {
            type: Number,
            primary: true,
            generated: true
        },
        name: {
            type: String
        }
    }
});
```
Here we specify only _interface_ as type argument, and interfaces, unlike classes, not exist in runtime at all, so you get plain old java script object but ttypescript will check that it's shape satisfy interface requirements, no more.

**Comment by thomazmz** [comment]
I got your point about type and JavaScript in runtime. Thanks.

I'm getting the following when calling `getRepository<Nameable>(NameableSchema)`

```
RepositoryNotFoundError: No repository for "nameable" was found. Looks like this entity is not registered in current "default" connection?
    at new RepositoryNotFoundError (/Users/thomaz/Workspace/logbook-api-ts/src/error/RepositoryNotFoundError.ts:10:9)
    at EntityManager.getRepository (/Users/thomaz/Workspace/logbook-api-ts/src/entity-manager/EntityManager.ts:1194:19)
    at Connection.getRepository (/Users/thomaz/Workspace/logbook-api-ts/src/connection/Connection.ts:341:29)
    at /Users/thomaz/Workspace/logbook-api-ts/src/playground/entityTest.ts:34:48
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'RepositoryNotFoundError',
  message: 'No repository for "nameable" was found. Looks like this entity is not registered in current "default" connection?'
}

```

**Comment by fan-tom** [comment]
Seem that in this case you need to specify `tableName` explicitly, this example works
```
import { EntitySchema, createConnection } from 'typeorm'

class Nameable {
  id!: number
  name!: string
}

const NameableSchema = new EntitySchema<Nameable>({
  name: Nameable.name,
  tableName: 'nameable',
  target: Nameable,
  columns: {
    id: { type: Number, primary: true, generated: 'increment' },
    name: { type: String }
  }
});

createConnection({
  name: 'logbook',
  type: "postgres",
    host: "localhost",
    port: 5432,
    username: "test",
    password: "test",
    database: "logbook",
    entities: [ NameableSchema ],
    synchronize: false // I have created table manually so disable autocreate
  })
    .then(databaseConnection => databaseConnection.getRepository<Nameable>(NameableSchema))
    .then(nameableRepository => nameableRepository.findOne({ where: { id: 1 }}))
    .then(findedNameable => console.log(`Found nameable: ${findedNameable instanceof Nameable}, ${JSON.stringify(findedNameable)}`));
```
With inserted object `{id: 1, name: 'foo'}` gives
`Found nameable: true, {"id":1,"name":"foo"}`, as you wish.

**Comment by thomazmz** [comment]
Actually having assigning Nameable.name to the options object worked fine. 

```
const NameableEntity = new EntitySchema<Nameable>({
  name: Nameable.name, // or 'Nameable'
  target: Nameable,
  columns: { 
    id: { type: Number, primary: true, generated: 'increment' },
    name: { type: String }
  }
})

**Comment by alvarosaavedra** [comment]
Hi, I have the same problem:
```typescript
import {Product} from "./Product";

export class Order {
    constructor(public id: number|null, public productos: Product[]) {
    }

    get total(): number {
        return this.productos.reduce((total, producto)=> producto.precio, 0)
    }
}
```
```typescript
export const OrderEntity: EntitySchema<Order> = new EntitySchema<Order>({
    name: Order.name,
    tableName: 'order',
    target: Order,
    columns: {
        id: {
            type: Number,
            primary: true,
            generated: true
        },

    },
    relations: {
        productos: {
            type: "many-to-many",
            target: Product.name,
            joinTable: true,
            eager: true
        }
    }
})
```

```typescript
const repo = getRepository<Order>(OrderEntity)
const order = await repo.findOneOrFail(1)
expect(order).to.be.a("Order")
````

`AssertionError: expected { Object (id, productos) } to be an order`

Version: 0.2.25
