### ISSUE TITLE
How can I use the built-in postgres `earthdistance` extension instead of PostGIS in TypeORM?

### ISSUE THREAD

**Issue by RobbieGM** [typeorm/typeorm#5998]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'm wondering how to use the earthdistance module when the `earth` data type is not supported as a column type in postgres according to [the docs](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#column-types-for-postgres). I could use PostGIS but I'd rather not because I would have to install it on every machine, including the production environment.

**Comment by imnotjames** [comment]
Probably `Raw`

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
