### ISSUE TITLE
Deploy TypeOrm In Digital ocean

### ISSUE THREAD

**Issue by Sharukhs** [typeorm/typeorm#6000]
Hi,

Developed my project in node,exprees,typeorm. How I can deploy my project in the digital ocean.

Thank You.

**Comment by imnotjames** [comment]
I think this is outside the scope of TypeORM.  Maybe digitalocean has some answers on their community?

For example, https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
