### ISSUE TITLE
0.3.0 release date?

### ISSUE THREAD

**Issue by abdullah2993** [typeorm/typeorm#6004]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

Any tentitive dates for `0.3.0` release?

**Comment by surajrana52** [comment]
Only god @pleerock can tell.

**Comment by osdiab** [comment]
Especially given that there's already a 0.4.0 release roadmap before 0.3.0 has come out. #3251

**Comment by osdiab** [comment]
I'm curious - what's holding it back so far?

**Comment by imnotjames** [comment]
It'll be when it's ready - I've been trying to pull bits in back to master where it's BC.
