### ISSUE TITLE
Typeorm creates new record instead of updating

### ISSUE THREAD

**Issue by eugene-chernyshenko** [typeorm/typeorm#6009]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

According to the documentation (https://github.com/typeorm/typeorm/blob/master/docs/example-with-express.md) I can update existing model with these code

```
app.put("/users/:id", async function(req: Request, res: Response) {
        const user = await userRepository.findOne(req.params.id);
        userRepository.merge(user, req.body);
        const results = await userRepository.save(user);
        return res.send(results);
    });
```

So if I specify an id in the request wich is PrimaryGeneratedColumn I get new record instead of updating existing model or getting an exception that it is restricted to update an id

```
curl -s http://localhost:8080/1 -X PUT -d '{"foo":"bar"}' -H 'content-type: application/json' | jq .
{
  "some": {
    "id": 1,
    "foo": "bar"
  }
}

curl -s http://localhost:8080/1 -X PUT -d '{"foo":"bar","id":"100"}' -H 'content-type: application/json' | jq .
{
  "some": {
    "id": 2,
    "foo": "bar"
  }
}
```

**Comment by manhhungptit** [comment]
You don't need to update **id** since it's primary column

**Comment by eugene-chernyshenko** [comment]
> You don't need to update id since it's primary column

I understand it

You should update your docs with something like

```
if (user === undefined) {
  throw new NotFoundException()
}
```

**Comment by mmartinson** [comment]
@eugene-chernyshenko 

https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md#submit-pr

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
