### ISSUE TITLE
Typeorm is adding "_rid" to my relation name

### ISSUE THREAD

**Issue by carlosaldaravi** [typeorm/typeorm#6012]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>
Hello! My project has no errors, i'm getting data from postman but when i try to post something, i'm getting an error. Typeorm is adding "_rid" to my relations.

<pre><code>
Controller.ts
@Post()
  create(
    @Body() createStudentDto: CreateStudentDto,
    @GetUser() user: User,
  ): Promise<void> {
    return this._studentService.createStudent(createStudentDto, user);
  }
</pre></code>
<pre><code>
Service.ts
  createStudent(createStudentDto: CreateStudentDto, user: User): Promise<void> {
    return this._studentRepository.createStudent(createStudentDto, user);
  }
</pre></code>

<pre><code>
Repository.ts
async createStudent(
    createStudentDto: CreateStudentDto,
    user: User,
  ): Promise<void> {
    const foundUser = await User.findOne(user.id);
    foundUser.details = createStudentDto.details;
    foundUser.sports = createStudentDto.sports;
    foundUser.level = createStudentDto.level;
    foundUser.calendar = createStudentDto.calendar;
    foundUser.save();
  }
</pre></code>

<pre><code>
import {
  BaseEntity,
  Entity,
  PrimaryGeneratedColumn,
  Column,
  OneToOne,
  JoinTable,
  ManyToMany,
  JoinColumn,
  CreateDateColumn,
  UpdateDateColumn,
  OneToMany,
  ManyToOne,
} from 'typeorm';
import { UserDetails } from './user.details.entity';
import { Role } from '../role/role.entity';
import { status } from '../../shared/entity-status.enum';
import { UserCalendar } from '../calendar/user-calendar.entity';
import { Language } from '../language/language.entity';
import { Target } from '../target/target.entity';
import { StudentTarget } from './student/student-target.entity';
import { Course } from '../course/course.entity';
import { Sport } from '../sport/sport.entity';
import { Level } from '../level/level.entity';

@Entity('users')
export class User extends BaseEntity {
  @PrimaryGeneratedColumn('increment')
  id: number;

  @Column({ type: 'varchar', unique: true })
  email: string;

  @Column({ type: 'varchar' })
  password: string;

  @OneToOne(type => UserDetails, { cascade: true })
  @JoinColumn({ name: 'detail_id' })
  details: UserDetails;

  @ManyToMany(type => Role)
  @JoinTable({ name: 'user_roles' })
  roles: Role[];

  @ManyToMany(type => Language)
  @JoinTable({ name: 'user_languages' })
  languages: Language[];

  @ManyToMany(type => Target)
  @JoinTable({
    name: 'student_targets',
    joinColumn: { name: 'student_id', referencedColumnName: 'id' },
    inverseJoinColumn: { name: 'target_id', referencedColumnName: 'id' },
  })
  targets!: Target[];

  @ManyToMany(type => Course)
  @JoinTable({
    name: 'course_students',
    joinColumn: { name: 'student_id', referencedColumnName: 'id' },
    inverseJoinColumn: { name: 'course_id', referencedColumnName: 'id' },
  })
  studentCourses!: Course[];

  @ManyToMany(type => Course)
  @JoinTable({
    name: 'course_instructors',
    joinColumn: { name: 'instructor_id', referencedColumnName: 'id' },
    inverseJoinColumn: { name: 'course_id', referencedColumnName: 'id' },
  })
  instrucorCourses!: Course[];

  @ManyToMany(type => Sport)
  @JoinTable({
    name: 'user_sports',
    joinColumn: { name: 'user_id', referencedColumnName: 'id' },
    inverseJoinColumn: { name: 'sport_id', referencedColumnName: 'id' },
  })
  sports!: Sport[];

  @OneToMany(
    type => StudentTarget,
    studentTarget => studentTarget.validatedBy,
  )
  studentTargetValidations: StudentTarget[];

  @OneToMany(
    type => UserCalendar,
    calendar => calendar.user,
  )
  calendar: UserCalendar[];

  @ManyToOne(
    type => Level,
    level => level.users,
    { cascade: true },
  )
  @JoinColumn({ name: 'level_id' })
  level: Level;

  @Column({ type: 'varchar', default: status.ACTIVE, length: 8 })
  status: status;

  @CreateDateColumn({ type: 'timestamp', name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamp', name: 'updated_at' })
  updatedAt: Date;
}
</pre></code>

![image](https://user-images.githubusercontent.com/58824896/81058867-a1136a00-8ecf-11ea-8d15-53e11b0cd0cd.png)

<pre><code>
For Tooling issues:
- Nest version: 7.1.4
- Node version: 12.16.3
- npm version: 6.14.4
- Platform:  macOS Catalina
</pre></code>

**Comment by manojchandrashekar** [comment]
In this file:

```
Repository.ts
async createStudent(
    createStudentDto: CreateStudentDto,
    user: User,
  ): Promise {
    const foundUser = await User.findOne(user.id);
    foundUser.details = createStudentDto.details;
    foundUser.sports = createStudentDto.sports;
    foundUser.level = createStudentDto.level;
    foundUser.calendar = createStudentDto.calendar;
    foundUser.save();
  }
```
Instead of `foundUser.save()`, can you try changing it to `User.save(foundUser)`?

**Comment by JoseAlbertoDev** [comment]
This happended to me. Check if you have an entity for student_targets, a model. That was my problem, I had an entity with the same name that I assigned to JoinTable annotation.

**Comment by carlosaldaravi** [comment]
@JoseAlbertoDev yeah, I have it, but I need to have it to create custom columns in student_targets entity.

**Comment by JoseAlbertoDev** [comment]
If I remember well, you should change your code to:

Entity **students_targets**:
@ManyToOne(type => Student, students_targets => student.students_targets)
student: Student;

@ManyToOne(type => Target, students_targets => target.students_targets)
target: Target;

Entity **target**:
@OneToMany(type => StudentsTargets, students_targets => students_targets.target)
students_targets: StudentsTargets[];

Entity **student**:
@OneToMany(type => StudentsTargets, students_targets => students_targets.student)
students_targets: StudentsTargets[];

You can read about this here:
https://github.com/typeorm/typeorm/blob/master/docs/many-to-many-relations.md#many-to-many-relations-with-custom-properties

**Comment by carlosaldaravi** [comment]
Yeah, this is how i did the first time but with this code i wasn't able to join to student.targets because students are related with student_targets instead of targets. So i changed my code as i showed. But if this is the only way to do it with custom columns, i'm going to revert my code again. Thank you man!
