### ISSUE TITLE
Returning type of added object

### ISSUE THREAD

**Issue by armantaherian** [typeorm/typeorm#6013]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an entity, like this:
```ts
@Entity()
export class File {

  @ObjectIdColumn()
  id: ObjectID;

  @Column()
  name: string;

  @Column()
  size: number;
}
```

And then, when I add something:
```ts
const inputFile = { ...req.body }; // comes from express request
const fileRepository = getManager().getRepository(File);
const newFile = fileRepository.create(inputFile);
const savedFile = await fileRepository.save(newFile);
```
And the result:
```ts
console.log(savedFile);

/*
  File {
    name: 'filename.png',
    size: 207235,
    id: 5eb0ff30e1d36cf45ffc33e1,
  }
*/
```

Everything looks fine till now, but, when I want to get something from the object, the unpleasant error would happen:
```js
console.log(savedFile.id) // Property 'id' does not exist on type 'File[]'.ts(2339)
```

**Comment by imnotjames** [comment]
Cannot replicate this issue.

Perhaps you need more generalized support?  Please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
