### ISSUE TITLE
Load all in relation where one meets requirement

### ISSUE THREAD

**Issue by JohnnyBlomgren** [typeorm/typeorm#6014]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

I have three entities:

Match
```
@Entity()
export class Match {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @OneToMany(
    type => MatchParticipant,
    participant => participant.match,
    { eager: true },
  )
  participants: MatchParticipant[];
```

MatchParticipant:
```
@Entity()
export class MatchParticipant {
  @PrimaryGeneratedColumn('increment')
  id: number;

  @ManyToOne(type => User, { eager: true })
  user: User;

  @ManyToOne(type => Match)
  match: Match;
}
```

And User:

```
@Entity()
export class User {
  @PrimaryGeneratedColumn('increment')
  id: string;
}
```

A Match has multiple MatchParticipants and each MatchParticipant has a reference to a User.

I want to load a Match with all participants where one of the participants "userId" equals an id. Is tthis possible with the EntityManager? I know I can load all participants and its users (actually they are automatically added through eager property) and I have managed to load only the participant with the passed id. But not all participants where at least one has the passed id.

Also do note that I am a newbie when it comes to SQL and such and I believe a "subquery" of sorts is one way to go. But I love the entity API and would simply know if there's a way to do it that way (or any other suggested way)

Thanks in advance!

EDIT:

Using the query builder I manage to (as mentioned) load all matches but not including all match participants:

```
matchRepository
      .createQueryBuilder('match')
      .leftJoinAndSelect('match.participants', 'participants')
      .leftJoinAndSelect('participants.user', 'user')
      .where('user.id=:id')
      .setParameter('id', id)
      .getMany();
```

EDIT 2:

I don't know if this is 100% correct but this SQL query seems to give me somewhat what I'm after. How would one continue to convert this to typeORM's query-builder or entity manager:

```
select * from match match 
join (select p."matchId" from public.match_participant p 
	  where p."userId" = 1) selfMatch on (selfMatch."matchId" = match.id)
join match_participant mp on (mp."matchId" = match.id)
left join public.user u on mp."userId" = u.id
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
