### ISSUE TITLE
Support Larger Data sizes for simple-json in MySQL

### ISSUE THREAD

**Issue by k-pindev-j** [typeorm/typeorm#6017]
**Issue type:**

[ ] question
[ ] bug report
[ x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ 0.2.24 ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

@Column('simple-json') stores internally on MySQL as TEXT. We ran into the problem of TEXT not being large enough for the data we were saving in the column. We want this to be LONGTEXT and still be able to utilize the serialization of simple-json type. Setting the type to LONGTEXT in the DB for a simple-json column also causes the migration script to drop the column:
```
await queryRunner.query("ALTER TABLE `results` DROP COLUMN `rawData`", undefined);
await queryRunner.query("ALTER TABLE `results` ADD `rawData` text NULL", undefined);
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by kjordan-pindev** [comment]
To pinpoint this, we see in the [MySQL driver](https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlDriver.ts#L552) the default is text: 
```
} else if (column.type === "simple-array" || column.type === "simple-json") {
      return "text";
}
```

**Comment by kjordan-pindev** [comment]
An idea I had as a potential solution to this could be the addition of a new column type such as long-simple-json. An alternative could be providing size options with the typeorm specific columns, simple-array & simple-json.
```
+++ b/src/driver/mysql/MysqlDriver.ts
@@ -461,7 +461,7 @@ export class MysqlDriver implements Driver {
         } else if (columnMetadata.type === "simple-array") {
             return DateUtils.simpleArrayToString(value);

-        } else if (columnMetadata.type === "simple-json") {
+        } else if (columnMetadata.type === "simple-json" || columnMetadata.type === "long-simple-json") {
             return DateUtils.simpleJsonToString(value);

         } else if (columnMetadata.type === "enum" || columnMetadata.type === "simple-enum") {
@@ -499,7 +499,7 @@ export class MysqlDriver implements Driver {
         } else if (columnMetadata.type === "simple-array") {
             value = DateUtils.stringToSimpleArray(value);

-        } else if (columnMetadata.type === "simple-json") {
+        } else if (columnMetadata.type === "simple-json" || columnMetadata.type === "long-simple-json") {
             value = DateUtils.stringToSimpleJson(value);

         } else if ((columnMetadata.type === "enum" || columnMetadata.type === "simple-enum")
@@ -552,6 +552,9 @@ export class MysqlDriver implements Driver {
         } else if (column.type === "simple-array" || column.type === "simple-json") {
             return "text";

+        } else if (column.type === "long-simple-json") {
+            return "longtext";
+
         } else if (column.type === "simple-enum") {
             return "enum";

diff --git a/src/driver/types/ColumnTypes.ts b/src/driver/types/ColumnTypes.ts
index 3569bedd..9c70b588 100644
--- a/src/driver/types/ColumnTypes.ts
+++ b/src/driver/types/ColumnTypes.ts
@@ -88,6 +88,7 @@ export type SimpleColumnType =
     // |"string" // typeorm-specific, automatically mapped to varchar depend on platform

     |"simple-json" // typeorm-specific, automatically mapped to string
+    |"long-simple-json" //  typeorm-specific, mysql, automatically mapped to string stored as longtext

     |"simple-enum" // typeorm-specific, automatically mapped to string```

**Comment by imnotjames** [comment]
I think matching `simple-array` and `simple-json` with the way `json` works for MariaDB could be reasonable - using `longtext` by default.

**Comment by AlexMesser** [comment]
https://github.com/typeorm/typeorm/pull/6152#issuecomment-640115629
