### ISSUE TITLE
"ReferenceError: Cannot access 'Entity' before initialization" when running migrations

### ISSUE THREAD

**Issue by JakeSidSmith** [typeorm/typeorm#6018]
**Issue type:**

[x] question
[x] bug report?
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

Getting the following error when trying to add relations and then generate migrations:

```shell
Error during migration generation:
ReferenceError: Cannot access 'B' before initialization
```

Even with this incredibly simple example (classes in the same file):

```ts
@Entity()
export class A extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  public id!: string;

  @OneToOne(
    () => B,
    b => b.a
  )
  public b!: B;
}

@Entity()
export class B extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  public id!: string;

  @OneToOne(
    () => A,
    a => a.b
  )
  @JoinColumn()
  public a!: A;
}
```

This code compiles ~and runs~ fine, I just cannot run migrations for it.

Edit: I get the same error when starting my server.

My orm config is something like:

```ts
import { ConnectionOptions } from 'typeorm';

import * as entities from './entities';

export const ORM_CONFIG: ConnectionOptions = {
  type: 'postgres',
  url: process.env.DATABASE_URL,
  entities: Object.values(entities),
  logging: true,
};
```

I had to import my entities because I haven't yet been able to get typeorm to pick them up at all when using paths; for example, `./entities/**/*.ts`.

And here's my tsconfig:

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "pretty": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "jsx": "react",
    "target": "es6",
    "moduleResolution": "node",
    "typeRoots": ["./node_modules/@types/", "./@types/"]
  },
  "include": ["./src/", "./@types/"]
}
```

**Comment by JakeSidSmith** [comment]
Update: same error with:

```ts
entities: [path.resolve(__dirname, './entities.ts')],
```

**Comment by JakeSidSmith** [comment]
Okay, this now appears to work if I put the entities into separate modules and change my orm config to:

```ts
import * as fs from 'fs';
import * as path from 'path';
import { ConnectionOptions } from 'typeorm';

const ENTITIES_DIR = path.resolve(__dirname, 'entities');

const entities = fs
  .readdirSync(ENTITIES_DIR)
  .map(file => path.resolve(ENTITIES_DIR, file));

export const ORM_CONFIG: ConnectionOptions = {
  type: 'postgres',
  url: process.env.DATABASE_URL,
  entities,
  logging: true,
};
```

But this isn't ideal. Can I not have my entities in the same file?

**Comment by JakeSidSmith** [comment]
I'll take that as a no...

**Comment by chriseling** [comment]
I have them in separate files and am running into the same problem just by having

`import { A } from "./entities"`

**Comment by JakeSidSmith** [comment]
@chriseling are you using TypeScript? I'd suggest playing with the `target` and `module` configs. I believe you'll need to be targeting at least ES6, and it may not work with certain modules.

**Comment by chriseling** [comment]
Yes, I'm using typescript.  Yea that might be what's happening.  I'm running it under Next.js and it requires "module": "esnext", "target": "es5",

**Comment by cacabo** [comment]
@chriseling any resolution on this? I'm stuck with the same problem.

**Comment by cacabo** [comment]
Ooh solution exists! https://github.com/typeorm/typeorm/issues/4190

**Comment by m4tta** [comment]
@chriseling Did you ever figure out how to get entities to load with typeorm and next.js?

**Comment by cacabo** [comment]
@m4tta in certain cases of circular dependencies it just doesn't work well. I've found more success and saved headaches splitting projects of this nature into having a dedicated API and a Next.js frontend.

**Comment by doraeru** [comment]
Change the target of the tsconfig file from es6 to es5.

**Comment by mmahalwy** [comment]
@cacabo seems like im running into the same problem here too :)

**Comment by bujoralexandru** [comment]
Same issue here, using typeorm with nextjs, both latest as we speak.
![image](https://user-images.githubusercontent.com/17970235/136476383-44295db6-b99d-4c43-bf98-5acc350fac73.png)

**Comment by piotr-cz** [comment]
I had this issue when I was importing related entities from `index.ts` file which contains re-exports.
Importing related entities from their own files fixed the problem.

**Comment by mkhib** [comment]
For anyone who encountered this issue, `import { Relation } from 'typeorm'` then wrap you entity with Relation
Like `Relation<Entity>`

**Comment by orangekjc** [comment]
Should i use `Relation<Entity[]>` or `Relation<Entity>[]` does it make any difference?

**Comment by abd30590** [comment]
If someone run into this problem, and after checking out all relations and nothing wrong (you already uses Relation<YourEntity> with all your relations)
, then you need to check if you have any Entity Listeners such as 
@AfterLoad
@BeforeInsert
@AfterInsert
@BeforeUpdate
@AfterUpdate
@BeforeRemove
@AfterRemove
@BeforeSoftRemove
@AfterSoftRemove
@BeforeRecover
@AfterRecover
that may reference any other entity
Unfortunately, I have spent 2 days to figure it out  :(
and the strange thing is that the code is running fine, but that's only was for typeorm migration !!
