### ISSUE TITLE
how catch db error from typeORM

### ISSUE THREAD

**Issue by stamuser60** [typeorm/typeorm#6020]
**Issue type:**
[X ] question=

**Database system/driver:**
[ X] `mssql`

**TypeORM version:**
[ X] `latest`

hii,
I started working with typeORM a while ago and encountered a problem.
I have a table called 'alert' that contains a column called ID which is a unique column.
When I try to insert to the DB a row with an ID that already exists in the table, the row does not enter the table but my code gets no error, it thinks that  everything is fine. And am looking for a way to catch the error.
Meanwhile, I tried:

const result = getConnection().manager.save(alert)
      .catch((err: any) => {
        switch (err.code) {
          case 'ER_DUP_ENTRY':
            console.log('boom');
            break;
        }
      });

But it didn't work, I'd be happy to some advise

**Comment by fan-tom** [comment]
From doc in EntityManager.d.ts sources
```
    /**
     * Saves all given entities in the database.
     * If entities do not exist in the database then inserts, otherwise updates.
     */
    save<Entity>(entity: Entity, options?: SaveOptions): Promise<Entity>;
```
So, it works as expected, I suppose

**Comment by manhhungptit** [comment]
.save() method return a promise, so your code should work. I suppose your error come from these lines:
```
switch (err.code) {
case 'ER_DUP_ENTRY':
console.log('boom');
break;
}
```
Can you provide the error message you get?

**Comment by stamuser60** [comment]
> .save() method return a promise, so your code should work. I suppose your error come from these lines:
> 
> ```
> switch (err.code) {
> case 'ER_DUP_ENTRY':
> console.log('boom');
> break;
> }
> ```
> 
> Can you provide the error message you get?

the code is working,
if the db is down it well rise an error, but if the constaint is the problem no error will occur.

**Comment by fan-tom** [comment]
> When I try to insert to the DB a row with an ID that already exists in the table, the row does not enter the table but my code gets no error, it thinks that everything is fine. And am looking for a way to catch the error.

There is no error in this case, `save` works as expected, you give it an instance of model with specified id (which is primary key, I suppose), it tries to `insert` this object, and, if insert fails, it performs `update`, as described in comment. If you want to get error in such case, you need to explicitly request for "insert or fail" behavior, using `myRepo.insert(instance)`, for example:
```
     * Inserts a given entity into the database.
     * Unlike save method executes a primitive operation without cascades, relations and other operations included.
     * Executes fast and efficient INSERT query.
     * Does not check if entity exist in the database, so query will fail if duplicate entity is being inserted.
     */
    insert(entity: QueryDeepPartialEntity<Entity> | (QueryDeepPartialEntity<Entity>[])): Promise<InsertResult>;
```

**Comment by stamuser60** [comment]
> > When I try to insert to the DB a row with an ID that already exists in the table, the row does not enter the table but my code gets no error, it thinks that everything is fine. And am looking for a way to catch the error.
> 
> There is no error in this case, `save` works as expected, you give it an instance of model with specified id (which is primary key, I suppose), it tries to `insert` this object, and, if insert fails, it performs `update`, as described in comment. If you want to get error in such case, you need to explicitly request for "insert or fail" behavior, using `myRepoOrEntityManager.insert(instance)`, for example:
> 
> ```
>      * Inserts a given entity into the database.
>      * Unlike save method executes a primitive operation without cascades, relations and other operations included.
>      * Executes fast and efficient INSERT query.
>      * Does not check if entity exist in the database, so query will fail if duplicate entity is being inserted.
>      */
>     insert(entity: QueryDeepPartialEntity<Entity> | (QueryDeepPartialEntity<Entity>[])): Promise<InsertResult>;
> ```

omg it worked!!
thank you very mach!!

**Comment by imnotjames** [comment]
Sounds like you're all set!

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
