### ISSUE TITLE
andWhere Returning Full Array of Relation, not Filtering

### ISSUE THREAD

**Issue by shellac85** [typeorm/typeorm#6026]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi I have a Membership - Customer Relationship. I want to return The User whose Memberhsip is the customerId. However, Its returning all the Users Memberships and not just one. Can anyone help where I am going wrong:

Example that is not working: 
```
if (!searchAllOvcUsers) {
        query
          .innerJoinAndSelect('Membership', 'membership', '"membership"."userId" = "user"."id"')
          .innerJoinAndSelect('Customer', 'customer', '"membership"."customerId" = "customer"."id"')
          .andWhere('membership.active');
        if (!searchAllCustomerUsers) {
          query
            .andWhere(new Brackets((qb) => {
              qb.orWhere('"membership"."customerId" = :customerId', { customerId: input.searchUserType });
            }));
        }
      }
    }
```

This is returning full array even though input.searchUserType has a value.

This however is working:
```
    if (customer) {
      query
        .innerJoinAndSelect('Membership', 'membership', '"membership"."userId" = "user"."id"')
        .innerJoinAndSelect('Customer', 'customer', '"membership"."customerId" = "customer"."id"')
        .andWhere('"membership"."customerId" = :customerId', { customerId: customer.id })
        .andWhere('membership.active');
    }
```

Any ideas greatly appreciated.

**Comment by innomatics** [comment]
Does it make a difference if you use `.where` for the first condition and `.andWhere` only for subsequent conditions?

**Comment by shellac85** [comment]
No unfortunately not. Its still returning the full array for some reason. Not sure why one is working but the other is not.

**Comment by shellac85** [comment]
These are the two relations. I still cant work this out. It doesn't work even if I hard code a value into input.searchUserType.

``` @Field(_type => Membership)
  @OneToMany(_type => Membership, membership => membership.customer, { lazy: true })
  public memberships: Lazy<Membership[]>;
```

```   @Field(_type => Customer)
  @ManyToOne(_type => Customer, relation => relation.memberships, { lazy: true })
  public customer: Lazy<Customer>;
```

Anyone any idea?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
