### ISSUE TITLE
How do you perform updates using Active Record with a where clause?

### ISSUE THREAD

**Issue by jaequery** [typeorm/typeorm#6029]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi, how do you update a record with a where clause using Active Record method? I've tried this and a number of combinations to no avail, please help.

```ts
await User.createQueryBuilder().where({ firstName: 'test'}).update({ lastName: 'test'});
```

This return error of: 

Type 'UpdateQueryBuilder<User>' is missing the following properties from type 'User': id, email, password, firstName, ...

Can someone please help?

Thanks.

**Comment by BTOdell** [comment]
Did you forget to call `execute()` at the end?

`await User.createQueryBuilder().where({ firstName: 'test'}).update({ lastName: 'test'}).execute();`

Also, this expression will not produce a `User` object but an 'UpdateResult' so you can determine how many rows were affected, etc.

**Comment by jaequery** [comment]
```
await User.createQueryBuilder().where({ firstName: 'jae'}).update({ lastName: 'query'}).execute();
```
produces error:
```
query failed: UPDATE "user" SET "last_name" = $2 WHERE User.firstName = $1 -- PARAMETERS: ["some","guy"]
error: error: syntax error at or near "."
```

**Comment by BTOdell** [comment]
The official docs for using QueryBuilder to create UPDATE queries is here: https://github.com/typeorm/typeorm/blob/master/docs/update-query-builder.md

Although that seems to be using the Data Mapper pattern instead of Active Record, so you probably can't just copy and modify from that example.

Try putting the `where` call after the `update` call and make sure your database is up-to-date with your `User` entity. It doesn't seem to be transforming the `firstName` column to `first_name` in the where clause.

**Comment by jaequery** [comment]
hey, so this worked, thx. but having an action like update() before where() is going to take me some time to get used to. 

```
await User.createQueryBuilder().update({ lastName: 'query'}).where({ firstName: 'jae' }).execute();
```

now, how would you do the same in AR without using createQueryBuilder()?

**Comment by BTOdell** [comment]
There is an `update` function directly in the `BaseEntity` class for Active Record.
So you could even do something like this:
```ts
await User.update({
    firstName: "jae"
}, {
    lastName: "query"
});
```

Another way, is to use the `find*` functions to load a single User (or multiple Users), then modify the user(s), and finally call the `save` function to write them to the database:
```ts
const user = await User.findOne({
    where: {
        firstName: "jae"
    }
});
if (user != null) {
    user.lastName = "query";
    await user.save();
}
```

Although I think that way is quite verbose for what you're trying to do, but it's more flexible (in a way).

**Comment by jaequery** [comment]
i'm looking to achieve something like this:

this should remove all users :
```
User.find({..}).remove();
```

this should remove just single user:
```
User.findOne({id}).remove();
```

is it even a possibility for TypeORM's AR to work in this fashion?

i think we will need a layer not just for a base entity but a base for a set of entities. does TypeORM offer such an abstraction?

**Comment by imnotjames** [comment]
TypeORM does not offer that functionality at this time, and it's not in the roadmap. 

Original issue seems to be answered.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
