### ISSUE TITLE
How to use custom methods in "where" in Query Builder

### ISSUE THREAD

**Issue by yupengcheng** [typeorm/typeorm#6035]
**Issue type:**

[ *] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[* ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[* ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I want to use a custom method in "where", but I can't get the variables. Can you help me?
I don't know how to get the variable "kr_sport_buy.id"。

`  function testFun(data){
      return data > 10;
    }
    
    const query = await getConnection('lottry')
    .createQueryBuilder(kr_sport_buy, 'kr_sport_buy')
    .where(`${testFun('kr_sport_buy.id')}`)
    .execute();`

**Comment by imnotjames** [comment]
`where` takes in a string which is sent over to the server for execution.  It has to return a valid SQL string.

For your specific example:

```
const query = await getConnection('lottry')
  .createQueryBuilder(kr_sport_buy, 'kr_sport_buy')
  .where(`kr_sport_buy.id > 10`)
  .execute();
```

---


For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
