### ISSUE TITLE
how can I filter some data by Many2Many relation, 

### ISSUE THREAD

**Issue by p2227** [typeorm/typeorm#6036]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

* here is my relation
```
import {Entity, PrimaryGeneratedColumn, Column} from "typeorm";

@Entity()
export class Category {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

}
```

----

```
import {Entity, PrimaryGeneratedColumn, Column, ManyToMany, JoinTable} from "typeorm";
import {Category} from "./Category";

@Entity()
export class Question {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    title: string;

    @ManyToMany(type => Category)
    @JoinTable()
    categories: Category[];

}
```

* here is my data:

```
question:
id title
1  A
2  B

Category 
id name
1 a
2 b


question_category
questionId  categoryId
1                 1
1                 2
```

------

if I use 

```
.createQueryBuilder("question")
innerJoinAndSelect('question.categories', 'categories', 'categories.id = :id' , { id: 1})
```

 I only get

```
[{
 id: 1,
 title: 'A',
 categories:[{ id: 1, name:'a' }]
}]

```
how can I get

```
[{
 id: 1,
 title: 'A',
 categories:[{ id: 1, name:'a' }, { id: 2, name:'b' }]
}]
```

**Comment by MihkelBaranov** [comment]
Had a similar issue and resolved it temporarily by adding a left join after the inner join

Something like this
```
.innerJoinAndSelect('question.categories', 'category', 'category.id = :id' , { id: 1})
.leftJoinAndSelect('question.categories', 'categories')
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
