### ISSUE TITLE
Exception handling in Oracle connections

### ISSUE THREAD

**Issue by AbdulazizHQ** [typeorm/typeorm#6037]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`createConnection` to Oracle instances always resolves and returns a connection and does not throw an error

    const createConnection = require('typeorm').createConnection
    createConnection({
        name: "oracle",
        type: "oracle",
        host: "invalidHost",
        username: "invalidUser",
        password: "invalidPassword",
        sid: "invalidSID",
        connectString: "invalidConnectionString",
        logging: false
    }).then(function(conn) {
        console.log('Connected') // This section is executed instead of throwing an error
    }).catch(function(err) {
        console.log(err) // It should throw an error
    });

**Comment by cjbj** [comment]
The default oracledb [`poolMin`](https://oracle.github.io/node-oracledb/doc/api.html#propdbpoolmin) is 0, meaning no connections are created when the pool is started.  Therefore no credential validation is performed until the first time a connection is obtained from the pool to execute some SQL; this will cause a connection to the DB to be established.   If you want pool creation to fail on invalid credentials, then `poolMin` will need to be increased >= 1.

**Comment by imnotjames** [comment]
Looks like this isn't a bug.  Closing.  If you'd like to request a change as a feature please open a new issue with a feature request.
