### ISSUE TITLE
Postgresql UUID Default value missing on initial migration generation.

### ISSUE THREAD

**Issue by Flash619** [typeorm/typeorm#6039]
**Issue type:**

[ ] question
[ X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

Create a basic entity with a primary generated column of the UUID type.

```ts
@Entity('tenant')
export class Tenant {
  @PrimaryGeneratedColumn({ name: 'tenant_id', type: 'uuid' })
  id: string;

  @CreateDateColumn({ name: 'created_on', type: 'timestamp' })
  createdOn: Date;
}
```

Generate a migration.

```
typeorm migration:generate -n "test"
```

View the contents of the migration .ts file. Note that `tenant_id` has the `NOT NULL` attribute, with no sequence or default value.

```ts
export class test1589086562460 implements MigrationInterface {
    name = 'test1589086562460'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tenant" ("tenant_id" uuid NOT NULL, "name" text NOT NULL, "url_name" text NOT NULL, "status" character NOT NULL, "created_on" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4e7cb4e84f82aa7842a0bafc673" PRIMARY KEY ("tenant_id"))`, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "tenant"`, undefined);
    }

}
```

Run the migration, generate a second migration.

```
typeorm migration:run test
typeorm migration:generate -n second-test
```

Review the contents of the `second-test` migration .ts file. Note the `CREATE SEQUENCE` query followed by the `ALTER TABLE` query. At this point we have made no change to our entity, however we have pending database changes that were not included on the initial migration.

```ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class secondTest1589086875150 implements MigrationInterface {
    name = 'secondTest1589086875150'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE SEQUENCE "tenant_tenant_id_seq" OWNED BY "tenant"."tenant_id"`, undefined);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "tenant_id" SET DEFAULT nextval('tenant_tenant_id_seq')`, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "tenant_id" DROP DEFAULT`, undefined);
        await queryRunner.query(`DROP SEQUENCE "tenant_tenant_id_seq"`, undefined);
    }

}

```

It is my belief that the second migration should be empty as no changes have been made to any entities after the first migration.

**Comment by iamolegga** [comment]
I created migration this way:
- using `@PrimaryColumn('uuid')` decorator
- generate migration, manually add to it `DEFAULT uuid_generate_v4()` to proper column
- apply migration
- then changed `PrimaryColumn` back to `PrimaryGeneratedColumn`

after that no any updates were found with `migration:generate`

**Comment by repodevs** [comment]
Instead of using

```
@PrimaryGeneratedColumn({ name: 'tenant_id', type: 'uuid' })
```

you should change to

```
@PrimaryGeneratedColumn('uuid', { name: 'tenant_id' })
```

this is will auto create `"tenant_id" uuid NOT NULL DEFAULT uuid_generate_v4()` instead of `"tenant_id" uuid NOT NULL`.
