### ISSUE TITLE
How I can join only one column

### ISSUE THREAD

**Issue by Spoki4** [typeorm/typeorm#604]
For example I had 2 tables with relation 1:1:
Offer doesn't have reference to lot:

| id | name | created_at |
|---|--------|-------------|
| 1  | offer1 |  2017-07-01 |

Lot has reference to offer:

| id | name | offer_id | created_at |
|---|--------|-------|------------|
| 1  | lot1   |     1    |2017-07-10 |

I need query from offer table with lot created date:

| id | name | created_at | lot_created_at |
|---|--------|-------------| --------------- |
| 1  | offer1 |  2017-07-01 | 2017-07-10 |

How I can do it? Join full table and select? How? I tried `leftJoinAndMapOne("lot", "lot", "lot", "offer.id = lot.offer_id")` and later `select("offer.*, lot.createdAt as offer.lotCreatedAt")`

```typescript
@Entity()
export class Offer  {
    @PrimaryGeneratedColumn({name: "id", type: "int"})
    id: number

    @Column({name: "name", type: "string"})
    name: string

    @Column({name: "created_at", type: "datetime"})
    createdAt: Date

    lotCreateAt: Date
}

@Entity()
export class Lot {
    @PrimaryGeneratedColumn({name: "id", type: "int"})
    id: number

    @Column({name: "name", type: "string"})
    name: string

    @OneToOne(type => Offer)
    @JoinColumn({name: "offer_id"})
    offer: Offer

    @Column({name: "created_at", type: "datetime"})
    createdAt: Date
}

const query = connection.getRepository(Offer)
                    .createQueryBuilder("offer")
                    .leftJoinAndMapOne("lot", "lot", "lot", "offer.id = lot.offer_id")
                    .select("offer.*, lot.createdAt as offer.lotCreatedAt")
                    .setLimit(50)
                    .setOffset(offset)


```

**Comment by Spoki4** [comment]
Hm, I thought, maybe a subquery can help here?

**Comment by pleerock** [comment]
`leftJoinAndMapOne` should work there, and you don't need a select. Selected data will be mapped into specified properly. Also don't use `setLimit` because it cuts out data if you use joins. Something like this should work:

```ts

const query = connection.getRepository(Offer)
                    .createQueryBuilder("offer")
                    .leftJoinAndMapOne("offer.order", Order, "order", "offer.id = order.offer_id")
                    .setOffset(offset)
```

**Comment by Spoki4** [comment]
Nice, it's works fine

**Comment by ezamelczyk** [comment]
But it maps the whole row from Order table to offer.order. What if I want to map only one column from joined table?

**Comment by dadepra** [comment]
HI @ezamelczyk do you have found solutions for this case? I have the same issue that is get and map just on column from joined table to one property into main query entity.

**Comment by pleerock** [comment]
Im going to deprecate `leftJoinAndMapOne` in the future versions of query builder, so I won't recommend use it anymore. Its not flexible as you can see. Instead you should execute a separate query and map results into entity on your own.

**Comment by Jumptidus** [comment]
> But it maps the whole row from Order table to offer.order. What if I want to map only one column from joined table?
`const query = connection.getRepository(Offer)
                    .createQueryBuilder("offer")
                    .leftJoinAndMapOne("offer.order", Order, "order", "offer.id = order.offer_id")
.select(['offer','order.name'])
                    .setOffset(offset)`
