### ISSUE TITLE
Oracle date type does not return time

### ISSUE THREAD

**Issue by JasonMan34** [typeorm/typeorm#6040]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

As the title suggests, using `@Column('date')` with an Oracle driver returns the date value only from the database, omitting the time portion of it

I am currently using `@Column('timestamp')` to get around this issue but this means my database and ORM are differently structured. If I ever synchronize other services using the db might break

**Comment by imnotjames** [comment]
According to the oracle docs

https://docs.oracle.com/cd/B19306_01/olap.102/b14346/dml_datatypes005.htm

`DATE` does not include times so this is working as expected.
