### ISSUE TITLE
Compiler issue on Linux but not Mac or Docker

### ISSUE THREAD

**Issue by joshghent** [typeorm/typeorm#6043]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
//src/controllers/endpoint.ts
public static async getAll(req: Request, res: Response) {
		const thirtySecondsAgo = moment().utc().subtract(30, 'seconds').format('YYYY-MM-DD HH:mm:ss.SSSSSS');
		const entityManager = getManager();
		const endpoints = await entityManager.findAndCount(Endpoint,
			{
				where: [
					{ last_checked: null },
					{ last_checked: MoreThanOrEqual(thirtySecondsAgo) }
				]
			});
		res.json(endpoints);
	}


// src/models/Endpoint.ts
import { Entity, Column } from "typeorm";
import BaseModel from "./BaseModel";

@Entity({ name: 'endpoints' })
export class Endpoint extends BaseModel {
	@Column({ type: 'varchar' })
	user_id: string;

	@Column({ type: 'varchar' })
	name: string;
	@Column({ type: 'varchar' })
	url: string;
}
```

2. Attempt to compile on an Ubuntu or Linux system. - `tsc`
3. Observe error of `No overload matches this call.`

Weirdly my code compiles on my Macbook and in a Docker container with Node 13-alpine. But it doesn't work when pushed to Github actions or Heroku. I've attempted to use the entity directly e.g., `const newRecord = new Endpoint(record); await Endpoint.save(newRecord)` etc.

I've been attempting to fix and search for solutions to this issue but to no avail. When using the entity directly it errored saying Cannot find property 'save' on Endpoint etc.

I'm incredibly confused by this one as it works perfectly locally and in Docker. Thanks in advance!

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
