### ISSUE TITLE
Slack group invitation link is dead

### ISSUE THREAD

**Issue by yiblet** [typeorm/typeorm#6053]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

the [link in the support documentation](https://github.com/typeorm/typeorm/blob/master/docs/support.md) is dead. Side note, Is the slack group even used anymore?

**Comment by imnotjames** [comment]
@pleerock same issue seen here.  I'd open a PR to create a new slack link or remove it but I'm not in it so I can't verify if it's active or not.

I opened PR #6447
