### ISSUE TITLE
Where are the docs for ActiveRecord implementation?

### ISSUE THREAD

**Issue by jaequery** [typeorm/typeorm#6057]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

Hey all, I've been trying to find some sort of docs for ActiveRecord usage in TypeORM but having no luck.

I'm trying to do basic stuff like how to do an update and add where clauses, etc... 
I feel as if this is a very different approach to ActiveRecord from what I'm used to.

For instance, none of these seem to work, and i just find it odd they aren't designed in a manner that is consistent with other ActiveRecords out there

```
// i just assumed this would work out of the box but it doesn't
const user = await User.findOne(id);
await user.update({ lastName: 'test' }); 

// even tried:
await user.save( { data: { lastName: 'test' } }); 
```

using createQueryBuilder also errors:
```
await User.createQueryBuilder().where({ firstName: 'jae' }).update({ lastName: 'query'}).execute();
```

query failed: UPDATE "user" SET "last_name" = $2 WHERE User.firstName = $1 -- PARAMETERS: ["jae","query"]
error: error: syntax error at or near "."

**Comment by karladler** [comment]
It's true the docs for active records could be really improved, but once you get the concept it's very similar to data mapper.

can you try this?

```
const user = await User.findOne(id);
user.lastName = 'test';
await user.save()
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
