### ISSUE TITLE
Date timezone issue : Need to save and retrieve date in UTC(at least save them in UTC) 

### ISSUE THREAD

**Issue by Kannas24** [typeorm/typeorm#6059]
**Issue type:**

[ x] bug report
[ x] question

**Database system/driver:**

[ x] `mssql`

**TypeORM version:**

`0.2.24`

**Steps to reproduce or a small repository showing the problem:**

**MSSQL server timezome** : UTC
**TypeOrm app timezone** : IST (+5:30)
**ISSUE** : app always sends date to SQL in IST but retrieves(after converting that to UTC) it in UTC.
Ex. app saved 14 May 2020 13:55 PM IST
      app retrieved it as 14 May 2020 8:25 AM UTC

Why? Am I missing anything here or this requires both typeorm app and server to be in UTC time zone ?

**Question:** Does typorm takes database and server app(with typeorm installed) local timezones into consideration while saving and retrieving dates to/from the database respectively ?

**If yes**, can I override it and always save and retrieve my dates in UTC(or at least save) with typeorm ?

**if no**, then may be I'm doing something wrong and need some help to correct it.

**Reasons why I want that**

1. I've multiple client apps(window/web/mobile/data analytic tools/powerBI) that are communicating to the database (one of them is using typeorm + NestJs). So, to make dates conversion consistent I need them to be in one timezone always not matter who has added that record to the database and who is fetching it from there.

2. All other database consumer apps are sending me dates in UTC and this Nodejs + NestJs + TypeOrm is the new addition to the stack and I can't afford it to send dates in local timezone. 

3. If I move my database server from timezone +5:30 to -2 then there shouldn't be problem with the the old data (considering data is stored in UTC timezone)

...there are other reasons too

**This is how I have configured my column**

```
  @Column({ name: 'date_col', type: 'datetime' }) // I've tried timestamp too
  dateCol: Date;

```

**This is how I'm assigning date to it**

`new Date(moment.utc().format()) // gives : 2020-05-13T20:54:18.000Z`

**Comment by imnotjames** [comment]
Set `useUTC` in the connection options for mssql - should help with this.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
