### ISSUE TITLE
should I use the alpha branch?

### ISSUE THREAD

**Issue by mbriggs** [typeorm/typeorm#606]
sort of a weird question, but you guys seem well into 0.1 development at this point. If I am using typeorm for the first time today, should I use stable or master?

**Comment by pleerock** [comment]
`master`. There are some features broken in 0.1.0 (like class/single table inheritance, cascades), but they were not properly worked in 0.0.x too. In other way 0.1.0 is better because there are tons of new features and bugfixes already.
