### ISSUE TITLE
Entity Inheritance: don't add parent columns in the child table

### ISSUE THREAD

**Issue by alumni** [typeorm/typeorm#6064]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In the [concrete inheritance example](https://github.com/typeorm/typeorm/blob/master/docs/entity-inheritance.md), we have:
```ts
abstract class Content;
class Photo extends Content;
class Question extends Content;
class Post extends Content;
```

However, in the database, this will add all columns of the class `Content` to the tables of the three children.

I would like to have a table for `Content` with its own columns and a `type` column + one table for each child that only contains the primary key of the parent and only the columns of the child. This would be similar to how other ORM frameworks work (e.g. Django) and would facilitate migrations from existing data models.

So the expectation would be the following 4 tables:

- `Content` (`id`, `title`, `description`, `type`)
- `Photo` (`id`, `size`)
- `Question` (`id`, `answersCount`)
- `Post` (`id`, `viewCount`)

Is there an easy way to achieve this?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
