### ISSUE TITLE
Writes to the database are queued?

### ISSUE THREAD

**Issue by MikeGriffinReborn** [typeorm/typeorm#6065]
From my testing through a repository it appears that writes are queued and not done in real-time. 

In other words this call where meta is a Repository ...

**await this.meta.save({ name: 'lastCheckpoint', value: eventNumber });**

does not happen in real-time, upon return from the await the "eventNumber" is not in the database, it is merely queued up to write to the database and will happen at a later time.

Am I correct? This is exactly what I am seeing on postgreSQL

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
