### ISSUE TITLE
Proper way to mock/stub getConnection?

### ISSUE THREAD

**Issue by zawadzkip** [typeorm/typeorm#6069]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `^0.2.24`

**Steps to reproduce or a small repository showing the problem:**

I have a healthcheck api that I am using to check the app status, as well as if the DB is connected.

```
import { Request, Response } from 'express';
import { getConnection } from 'typeorm';

/**
 * Used for checking application health status
 */
class HealthController {
  public getHealthCheck = async (req: Request, res: Response): Promise<Response> =>
  {
    try {
      const dbConnection = getConnection();
      if (!dbConnection.isConnected) {
        throw Error("Db connection failed");
      }
      return res.status(200).json({
        ok: true,
        message: 'Application Running',
        dbConnection: dbConnection.isConnected,
        status: 'UP',
      });
    } catch (ex) {
      return res.status(500).json({
        ok: false,
        message: ex,
        status: 'APP FAILURE',
      });
    }

  }

}

export { HealthController };
```

I'm using `supertest` to run api requests against my server.

The server being passed into super test is as follows.
```
import * as compression from 'compression';
import * as express from 'express';
import * as helmet from 'helmet';
import * as morgan from 'morgan';

import { healthRouter } from '../routes/health.routes';
const server = express();

// setup routing
server.use(healthRouter);
// Setup middleware
server.use(helmet());
server.use(morgan('short'));
server.use(compression());
server.use(express.json());
server.use(express.urlencoded({ extended: false }));
export { server };
```

I'm trying to mock the `getConnection` function so I can force it to return false and true for the different test cases I want to cover.

Any ideas on how to do this? Currently using jest & sinon in my app.

**Comment by thomasdc** [comment]
Does [this documentation](https://jestjs.io/docs/en/mock-functions.html#mock-implementations) help you?

**Comment by zawadzkip** [comment]
@thomasdc It helped me towards the answer.

I ended up having to do something like this. Hopefully this helps someone in the future.
```
import { mocked } from 'ts-jest/utils';
import { getConnection, Connection } from 'typeorm';
jest.mock('typeorm');

const mockedGetConnection = mocked(getConnection, true);
// inside the test case
    mockedGetConnection.mockImplementation(() => ({
      isConnected: true,
    }) as Connection);
...

```
