### ISSUE TITLE
Does @CreateDateColumn use mysql 'NOW()' or 'new Date()' from node?

### ISSUE THREAD

**Issue by darrenrahnemoon** [typeorm/typeorm#6070]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Does typeorm use `NOW()` or `new Date()` when using the column decorator `@CreateDateColumn`? I dove into the code. Couldn't find a reference to confirm the case.

**Comment by witoong623** [comment]
typeorm uses `CURRENT_TIMESTAMP(6)` for mysql. [reference](https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlDriver.ts#L235)
