### ISSUE TITLE
UnhandledPromiseRejectionWarning: QueryFailedError: column reference "name" is ambiguous

### ISSUE THREAD

**Issue by dominikzogg** [typeorm/typeorm#6071]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

Create Entity `One` with a property `name`, create entity `Many` with a property `name`, create a relation between as they are named.

Create a createQueryBuilder with `leftJoinAndSelect('o.manies', 'm')` and run `getMany()`

This will lead the following error:

`UnhandledPromiseRejectionWarning: QueryFailedError: column reference "name" is ambiguous`

Doctrine handles this by using `as`with o.name as name_1, m.name as name_2 and map the result to to the related properties.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
We should be doing that.  Can you create a Reproducible example?

**Comment by dominikzogg** [comment]
https://github.com/chubbyphp/petstore-express/blob/master/src/Repository/PetRepository.ts#L17
https://github.com/chubbyphp/petstore-express/blob/master/src/Model/Pet.ts#L18
https://github.com/chubbyphp/petstore-express/blob/master/src/Model/Vaccination.ts#L11

Will have to test it, no idea if its fixed in the meanwhile

**Comment by dominikzogg** [comment]
@imnotjames it's still the same with `0.2.28`

**Comment by sroze** [comment]
This issue is a duplicate of #4902. There is a known workaround described in https://github.com/typeorm/typeorm/issues/4902#issuecomment-542080781.

**Comment by dominikzogg** [comment]
@sroze thanks for mentioning
