### ISSUE TITLE
Decimal value change when saving object using typeorm

### ISSUE THREAD

**Issue by NekioExp** [typeorm/typeorm#6072]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
export class ActDiscountEntity implements ActDiscountInterface {
  @PrimaryGeneratedColumn({ name: 'id' })
  id: number;
 
  @Column({ name: 'actId', nullable: false })
  actId: number;
 
  @Column({ name: 'discountId', nullable: false })
  discountId: number;
 
  @Column({ name: 'amount', nullable: true, default: 0, type: 'money' })
  amount: number;
 
  @Column({ name: 'legacy_idt', nullable: true })
  legacy_idt: string;
}
```
I create a new object to be stored in my BD, with the following code:
```
await this.orm.getRepository(ActDiscountEntity).save(ActDiscountToSave);
```
This is the object before saving it in the database:
 
```
{ id: 0,
actId: 805563,
discountId: 77014,
amount: 11.29,
legacy_idt: null }
```
But when I look up the object in my database its amount is 11,2899 and all other fields are correct.
 
If I use a query created by a sql file to insert the data, this saves the amount correctly (11.29).
```
await transactionalEntityManager.query(INSERT_INTO_ACTDISCOUNT, [
          ActDiscountToSave.actId,
          ActDiscountToSave.discountId,
          ActDiscountToSave.amount,
          ActDiscountToSave.legacy_idt
        ]);
```
 
For this reason I think it's a typeorm error, this error only applies to this object and I didn't get another example like this one. Any idea how to solve this without a raw query?

**Comment by imnotjames** [comment]
This is a JavaScript issue - not a typeorm issue.  You're representing money with floating point math.

https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

As such, I'm closing out this issue.
