### ISSUE TITLE
how get JoinColumn value

### ISSUE THREAD

**Issue by martinop** [typeorm/typeorm#6073]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

 I have this entity:

 ```ts
 @Entity()
 export class UserPick {
   @PrimaryGeneratedColumn()
  id: number;

  @Column({ default: new Date()})
  @CreateDateColumn()
  createdAt: Date;

  @ManyToOne(type => Match)
  @JoinColumn()
  match: Match;

  @ManyToOne(type => Participant)
  @JoinColumn()
  participant: Participant;

  @ManyToOne(type => User, user => user.picks)
  user: User;

  @ManyToMany(type => Enhancer)
  @JoinTable()
  enhancers: Enhancer[];
 }
```

And this query:

```js

   repository
    .createQueryBuilder('pick')
    .innerJoin('pick.match', 'match')
    .leftJoinAndSelect("pick.enhancers", "enhancers")
    .where('pick.user = :userId', { userId })
    .andWhere('match.round = :roundId', { roundId })
    .addSelect('pick.participant')
    .getMany();
```

How can I get the value of "participant" JoinColumn without join?

.execute() won't work because of the left join.

**Comment by zerooverture** [comment]
I need this, too

**Comment by zerooverture** [comment]
I found a solution
https://typeorm.io/#/relations-faq/how-to-use-relation-id-without-joining-relation

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
