### ISSUE TITLE
Where can I find the complete Migrations API?

### ISSUE THREAD

**Issue by twigs67** [typeorm/typeorm#6074]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

The documentation on the migrations API seems a little light. I'm trying to create a 'created' '& 'updated' column upon table creation, but I can't find the documentation that says how to do this? 

Is it typically advised to just write raw queries when using migrations tables? 

Thanks

```
  await queryRunner.createTable(new Table({
            name: 'tableName',
            columns: [
                {
                    name: 'id',
                    type: 'int',
                    isPrimary: true,
                },
        
                {
                    name: 'created',
                    type: 'datetime',
                },
                {
                    name: 'updated',
                    type: 'datetime',
                },

            ],
        }), true);
```

**Comment by imnotjames** [comment]
You'll need to take a look at the query runner for this.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
