### ISSUE TITLE
website null

### ISSUE THREAD

**Issue by Arc-zlz** [typeorm/typeorm#6076]
![Y1}U}423222RSG%1U0A3AU6](https://user-images.githubusercontent.com/26889461/82125834-3faa9f80-97db-11ea-8686-2ec0e80cbf74.png)

**Comment by hkyq** [comment]
You should show some console logs.

But from your screenshot, it looks like your browser is failing to load the raw github data from `raw.githubusercontent.com`. Sometimes this domain is blocked by network administrators. Does this url work for you? https://raw.githubusercontent.com/typeorm/typeorm/master/docs/caching.md

**Comment by Arc-zlz** [comment]
> 您应该显示一些控制台日志。
> 
> 但是，从截图中，您的浏览器似乎无法从 加载原始 github 数据。有时，网络管理员会阻止此域。此 URL 是否适用于您？https://raw.githubusercontent.com/typeorm/typeorm/master/docs/caching.md`raw.githubusercontent.com`

thank you,

**Comment by hkyq** [comment]
Well its just a website block. You can use something like a VPN to bypass it, but that is outside the scope of this issue.

**Comment by hkyq** [comment]
Ah, seems to be blocked in China? https://en.greatfire.org/raw.github.com

**Comment by Arc-zlz** [comment]
thank you
