### ISSUE TITLE
Null Datetime returns date of 1970-01-01

### ISSUE THREAD

**Issue by jessequinn** [typeorm/typeorm#6078]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

    "@nestjs/typeorm": "^7.0.0",
    "typeorm": "^0.2.24",

**Steps to reproduce or a small repository showing the problem:**

```
  private _programStart: Date | null;

  ...

  @Column('datetime', { name: 'program_start', nullable: true, default: null })
  get programStart(): string | null {
    if (typeof this._programStart.getMonth === 'function') {
      return this._programStart.toISOString();
    } else {
      return null;
    }
  }

  set programStart(programStart: string) {
    this._programStart = new Date(programStart);
  }
```
The code above will return a date of `1970-01-01` when `programStart` is null in the database.

**Comment by pablo-abc** [comment]
Hey! This has nothing to do with TypeORM. It's more about the behaviour of the Date constructor in JavaScript. So your issue is on this line:

```
this._programStart = new Date(programStart);
```

If you try `new Date(null)` on the node console you'll see it always returns `1970-01-01`.

**Comment by imnotjames** [comment]
Yup, this is in your code.  


For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
