### ISSUE TITLE
I'm wondering, is there is possibility to enable lazy loading with populating joined entities id? Like they would be in db

### ISSUE THREAD

**Issue by idchlife** [typeorm/typeorm#608]
I'm always using queries with joins to get particularly joined column.

But it will be a lot easier to do this:

```typescript
const author = await this.entityManager.findOneById(Author, product.author);
```

instead of this:

```typescript
const p = await this.entityManager
  .createQueryBuilder(Product, "p")
  .where("p.id = :id", { id: product.id })
  .leftJoinAndSelect("p.author", "author", "author.id = p.author")
  .getOne();

const author = p.author;
```

Or I am mistaken and there is already such functionality somewhere?

**Comment by NoNameProvided** [comment]
By default relations are promises on your entity. (You may need to update the entities to reflect this.) If you want to use them in your app only then you can do: 

```ts
const product = await this.entityManager.findOneById(Product, 3);
await product.author;
// do whatever you want with your author
```

However if you want to stringify them and sending them down to the client, it wont work, because their actual representation will be this after transformation.

```ts
{
  // product's properties
  __HAS_AUTHOR__: true
  __AUTHOR__:{ /* your author entity. */ }
}
```

**Comment by idchlife** [comment]
Well, working with subentity with await on backedn is good enough for me. Thank you!

**Comment by idchlife** [comment]
@NoNameProvided I will reopen this issue, since I cannot use functionality you mentioned.

These both methods do not work for me:

```typescript
await product.author;

const author = await product.author;
```

Author is undefined, there is no even field author in entity before and after trying to load it. Am I doing something wrong?

Maybe it's tied to specific typeorm version? I have 0.0.11

**Comment by NoNameProvided** [comment]
Do you have the correct relations? It should look like this:

```ts
// on the Product entity
@ManyToOne(type => Author, async author => author.products)
@JoinColumn()
public author: Promise<Author>;
```

```ts
// on the Author entity
@OneToMany(type => Product, product => product.author)
public products: Promise<Product[]>;
```

**Comment by idchlife** [comment]
Oh, I get it now. Thank you. It should have preparations for this kind of functionality:

1) side with join column can be gathered through promise.
2) type callback should be async
3) type of column where join column is present should be Promise<Entity>

Is it present in the documentation? I think it's worth mentioning there. I think I can update it for this functionality.

**Comment by pleerock** [comment]
wait wait orginally @idchlife was talking about regular relations, but @NoNameProvided answered him how to do things using lazy relations. Relation become "lazy" when you make its type `Promise`. There are both good and bad points about lazy relations.

> type callback should be async

NO! IT SHOULD NOT. `async product => product.author` should be simply `product => product.author`.

-----

In `0.1.0-alpha.30` I published right now you can load non-lazy relations this way:

```ts
await connection.getRepository(Post).findOne({
       relations: ["author", "categories"]
});
```

**Comment by idchlife** [comment]
Wow, very convenient way to load relations with simple find methods!

**Comment by NoNameProvided** [comment]
@pleerock 

> NO! IT SHOULD NOT. async product => product.author should be simply product => product.author.

Hmm it returns a promise when I using lazy relations. When using lazy relations I can use them this way right? I did it because tslint complains about it if I don't set them `async`

```bash
functions that return promises must be async (promise-function-async)
  25 |   public sum: number;
  26 | 
> 27 |   @ManyToOne(type => User, user => user.ordersAsUser)
     |                           ^
  28 |   public user: User;
  29 | 
  30 |   @OneToMany(type => Appointment, entity => entity.order)
```

**Comment by pleerock** [comment]
> Hmm it returns a promise when I using lazy relations. 

right and why it have to be marked as `async`? Probably some strange tslint configuration is enabled for you. In reality you don't need it

**Comment by NoNameProvided** [comment]
> In reality you don't need it 

We does, to encourage usage of async function for team members. Anyway, it's not a bug, just a not favored way of defining layz relations right? So technically we can use it, we just need to remove it if we dont want to make a relation lazy anymore.

**Comment by pleerock** [comment]
yeah use it if you need it and it works for you

**Comment by idchlife** [comment]
@NoNameProvided hey, I'm trying to accomplish thingy with lazy loading with await and stumbled upon problem when assigning Product.author = new Author() (or existing) will result in error that there should be promise assigned but not Author itself.
How did you solve this issue?

**Comment by pleerock** [comment]
right you need to do:

```ts
product.author = Promise.resolve(new Author() /*or existing*/));
```

As I told earlier lazy relations are very specific and there are good and bad points about them.
