### ISSUE TITLE
Custom precision on CreateDateColumn and UpdateDateColumn

### ISSUE THREAD

**Issue by sanlyx** [typeorm/typeorm#609]
MySQL 5.6 and later releases provide support for fractional timestamps via the `DATETIME(1)` to `DATETIME(6)` column types. It would be nice for TypeORM to support them on CreateDateColumn and UpdateDateColumn decorators:

```ts
@CreateDateColumn('datetime(6)')  // does not work because default has to be CURRENT_TIMESTAMP(6) instead of CURRENT_TIMESTAMP
createdAt: Date;
```

**Comment by pleerock** [comment]
as of `0.1.0-alpha.29` created date and updated date use `datetime(6)` as data types.

**Comment by ruimgoncalves** [comment]
This breaks support for MySql 5.5 when creating a table since this version does not support specifying precision for DateTime or Timestamp types.

**Comment by daggett206** [comment]
the same problem for mysql 5.5
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)\' at line 1'
`

**Comment by svicalifornia** [comment]
@pleerock Reopen this issue and fix for MySQL 5.5.

**Comment by pleerock** [comment]
in latest `@next` you are able to do following:

```ts
@CreateDateColumn({ precision: 4 /* or any other */, default: () => "CURRENT_TIMESTAMP" })
```

To make this functionality to work on old mysql versions.

**Comment by svicalifornia** [comment]
@pleerock This issue was reopened because the addition of precision caused MySQL 5.5 to fail when creating a table. Since this has now been closed twice, perhaps someone should open a new issue for the MySQL 5.5 compatibility problem.

@ruimgoncalves or @daggett206 Would either of you like to open a new issue for the MySQL 5.5 precision problem?

**Comment by svicalifornia** [comment]
@pleerock Sorry, I'm trying to understand how you have resolved the MySQL 5.5 issue raised by @ruimgoncalves or @daggett206 above.

Last July, you said that the new default for CreateDateColumn and UpdateDateColumn to `DATETIME(6)`. Then they posted that MySQL 5.5 doesn't support any precision for `DATETIME`:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)\' at line 1'
```

If you have fixed this, does that mean that you changed the default from `DATETIME(6)` back to simply `DATETIME` with no precision?

**Comment by AlexMesser** [comment]
@svicalifornia in 5.7 we create `DATETIME` with precision of `6` to make it more accurate. For backward compatibility with 5.5 I add in `typeorm@0.2.0-alpha.42` support for `precision: null` which means that `DATETIME` column will be created without any precision.

```typescript
@CreateDateColumn({ precision: null, type: "timestamp", default: () => "CURRENT_TIMESTAMP" })
createDate: Date;
```

**Comment by agborkowski** [comment]
each time when i run schema:sync, log sqls, type orm is generating same updates
![screen shot 2018-08-29 at 10 55 56](https://user-images.githubusercontent.com/170557/44777172-2b8fbc00-ab7a-11e8-942f-ac31aa6aa96d.png)

little bit different for migration
![screen shot 2018-08-29 at 10 57 19](https://user-images.githubusercontent.com/170557/44777261-73aede80-ab7a-11e8-8d07-05b6cde05667.png)

dbtype:mariadb i tried drop database, recovery from classes and still same diffs ;( for default entities
````

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;
}
```

**Comment by AmirNamdar** [comment]
> @svicalifornia in 5.7 we create `DATETIME` with precision of `6` to make it more accurate. For backward compatibility with 5.5 I add in `typeorm@0.2.0-alpha.42` support for `precision: null` which means that `DATETIME` or another date type column will be created without any precision.
> 
> ```ts
> @CreateDateColumn({ precision: null, type: "timestamp", default: () => "CURRENT_TIMESTAMP" })
> createDate: Date;
> ```

Hi Alex
while your soultion fixed the problem for `CreateDateColumn`,  `UpdateDateColumn` still suffers from the same problem.

I have used it like so:
`    @UpdateDateColumn({ precision: null, type: "timestamp", default: () => "CURRENT_TIMESTAMP" })
    createdAt: Date;`

Am I missing something or this is still an issue?
Thanks

**Comment by kelly-tock** [comment]
I am on mariadb 5.5.5, am only able to use the query builder directly to get this column working. I am unable to just say something like 

```
User.create(....).save()
```
as I will get an error like this:

```
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Oct 07 2020 07:32:35 GMT-0500 (Central Daylight Time), Wed Oct 07 2020 07:32:35 ' at line 1
```

tried the above workarounds as well.

**Comment by gabbrieu** [comment]
How can I set precision null nowadays with EntitySchema? The field currently is accepting only number and undefined, not null. I can do `precision: null as any` but it's a workaround, not the best solution.

Also, the updatedAt field with `default: () => 'CURRENT_TIMESTAMP'` is generating CURRENT_TIMESTAMP(6), but the createdAt field not.
