### ISSUE TITLE
Is it possible to pass LIKE operation to FindOptions as JSON?

### ISSUE THREAD

**Issue by jaequery** [typeorm/typeorm#6091]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to pass in FindOpts to perform a Like query, preferably like this but i can't:

```
const opts = {
  where: {
    name:  { like: "%j%" }
  }
}
this.userRepository.find(opts);
```

i know you can use "Like":
```
import {Like} from "typeorm";
this.someRepository.find({ name: Like("%j%") })
```

but, i want the like query to be passed in as a plain JSON.
anyone know if there's a way?

**Comment by imnotjames** [comment]
This is not currently possible but might be in the next minor release (0.3.0)
