### ISSUE TITLE
typeorm-model-shim missing @ViewEntity and @ViewColumn decorators

### ISSUE THREAD

**Issue by cduff** [typeorm/typeorm#6093]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**typeorm-model-shim** is missing functions for **@ViewEntity** and **@ViewColumn** which causes build errors when using the shim with a model with view entities.

**Comment by paulKabira** [comment]
Also missing, `@DeletedDateColumn()`.

**Comment by Silventino** [comment]
This is simple to resolve, I'll make a PR.
