### ISSUE TITLE
Could not find a declaration file for module 'custom-module'

### ISSUE THREAD

**Issue by alvarocantador** [typeorm/typeorm#6094]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a repository with some custom declaration types for dependencies that do not have one, in my case: [nanomatch](https://www.npmjs.com/package/nanomatch).

When I run: 

`ts-node ./node_modules/.bin/typeorm migration:generate -d src/migration "-n" "NewMigration"`

It throws:

```
error TS7016: Could not find a declaration file for module 'nanomatch'. '/Users/alvaro/workspace/.../node_modules/nanomatch/index.js' implicitly has an 'any' type.
  Try `npm install @types/nanomatch` if it exists or add a new declaration (.d.ts) file containing `declare module 'nanomatch';`

2 import nanomatch from 'nanomatch';
```

tsconfig.json:

```ts
{
  ...,
  "include": ["src/**/*.ts", "src/**/*.d.ts"],
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "dist"
  }
}

```

src/types/nanomatch/index.d.ts:

```ts
  declare module 'nanomatch';
```

There is something that am I missing?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by rehouven** [comment]
Had the same problem.
see: https://stackoverflow.com/questions/51610583/ts-node-ignores-d-ts-files-while-tsc-successfully-compiles-the-project
