### ISSUE TITLE
[Question] How to manage relationships with entity media and various entity

### ISSUE THREAD

**Issue by zecka** [typeorm/typeorm#6097]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi, I'm stuck on a basic problem...

I don't know how to manage relationships with media and various entity

In my project i have a "media" entity which can be related to different entities. 
Entity User:
- Avatar
Entity Event
- Poster
- Gallery

.... And maybe many more later.

How to create the relationship between a media and a user or an event?

**My first idea** is to create relation only on other entity, like below
**For user:** 
avatar: Relation OneToOne
**for Event**
poster: relation OneToOne
gallery: relation OneToMany

But with this data model it will be difficult to retrieve media that are not linked to any entity (I need it to clean up and make a cron job that removes unused media).

**My second ideas** is to have another entity like MediaRelation with 4 columns
- EntityID
- MediaID
- EntityName
- EntityField

Which data model is usually used to manage media entities, how do you advise me to proceed ?

**Comment by rodriguex** [comment]
Hi @zecka, i've been with the same issue. But in my case, i have the product table, which will be related with person and business entities, but in the same field. did you get it? 

Did you have any progress on this issue by yourself?

**Comment by zecka** [comment]
For the moment I haven't found a satisfactory solution. I've stuck to my first solution.  I will come back published here if I find a better solution.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
