### ISSUE TITLE
Cordova Sqlite & WebSql Support

### ISSUE THREAD

**Issue by BradyLiles** [typeorm/typeorm#61]
I'd like to see some support to use this in Hybrid Mobile Apps with Cordova & Angular2. 
I've forked this repository and will be working on a branch of this to support Sqlite on an IOS/Android environment and WebSql so we can support these features. I can definitely see something like this being widely used in the Hybrid Mobile App environment.

I absolutely love the library you've created here. Awesome idea how to create an ORM in Typescript.

**Comment by pleerock** [comment]
Thats sounds great. Love this idea, excited to see new drivers implementation

**Comment by pleerock** [comment]
@BradyLiles Hi, I have abstracted TypeORM from the node platform. Now it can be run in the browser too. I have created a basic websql driver (just copy of sqllite driver, needs deeper implementation of websql-specific problems). Take a look at this example [here](https://github.com/typeorm/browser-example).

**Comment by pleerock** [comment]
closing it because similar issue already exist in #548
