### ISSUE TITLE
Exact match EntitySchema<T> with T

### ISSUE THREAD

**Issue by pbn4** [typeorm/typeorm#6101]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is there a way to ensure exact matching of columns defined in EntitySchema<T> with properties of T?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
