### ISSUE TITLE
How to set 'comment' for 'table' ?

### ISSUE THREAD

**Issue by liu2080019** [typeorm/typeorm#6102]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How to set 'comment' for 'table' ?

**Comment by imnotjames** [comment]
Only column comments are currently supported.

**Comment by imnotjames** [comment]
As this was a question and not a more fleshed out feature request I'll be closing it out.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by Val-istar-Guo** [comment]
Will it be supported in the future？

**Comment by xerxes235** [comment]
+1
