### ISSUE TITLE
Typeorm/browser cannot be compiled since version 0.2.25

### ISSUE THREAD

**Issue by clfhhc** [typeorm/typeorm#6110]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.25`

**Steps to reproduce or a small repository showing the problem:**
I have been using Typeorm and Sqljs with Nextjs. I have to [transpile module](https://github.com/Project-Setup/github_sql_pwa/blob/typeorm-0.2.25/next.config.js#L4) `typeorm/browser` at build time to generate static HTML files. This had been working until Typeorm upgraded to 0.2.25.

Here's the example repo: https://github.com/Project-Setup/github_sql_pwa/tree/typeorm-0.2.25
To reproduce:
1. git clone the repo
2. set up node environment
    ```sh
    nvm install; nvm use; npm install
    ```
3. build pages
    ```sh
    npm run build
    ```

an error will come out:
```
Creating an optimized production build  

Failed to compile.

./node_modules/typeorm/browser/driver/DriverFactory.js
Attempted import error: 'AuroraDataApiPostgresDriver' is not exported from './postgres/PostgresDriver'.


> Build error occurred
Error: > Build failed because of webpack errors
```

Reverting Typeorm to 0.2.24 will fix the issue.

I think the issue lies in typescript declaration file `node_modules/typeorm/browser/driver/postgres/PostgresDriver.d.ts`. It may have a problem exporting multiple classes under the current setup, but I wasn't sure.

**Comment by SanchezSobrino** [comment]
Same error; just upgraded to 0.2.25 and cannot compile anymore.

**Comment by chriswep** [comment]
i made a PR to fix this: https://github.com/typeorm/typeorm/pull/6117

@pleerock this issue makes all browser-builds fail on 0.2.25, maybe you want to consider a hot fix release for this.

**Comment by cHewN** [comment]
I am still getting this error:

`Failed to compile.

D:/project/xyz/node_modules/typeorm/browser/driver/DriverFactory.js
Attempted import error: 'AuroraDataApiPostgresDriver' is not exported from './postgres/PostgresDriver'.`

I am on the latest version (yarn add typeorm@latest => "typeorm": "^0.2.25").
Package.json version inside my node_modules typeorm folder:
`{
  "name": "typeorm",
  "private": false,
  "version": "0.2.25",`

**Comment by chriswep** [comment]
> I am still getting this error:
> 
> I am on the latest version (yarn add typeorm@latest => "typeorm": "^0.2.25").

That's still the version with the error. Unfortunately typeorm hasn't released a new version yet.

**Comment by cHewN** [comment]
> > I am still getting this error:
> > I am on the latest version (yarn add typeorm@latest => "typeorm": "^0.2.25").
> 
> That's still the version with the error. Unfortunately typeorm hasn't released a new version yet.

Ah yes I see now in the related #6117 there is a patch that can be applied for now. Thanks for your help!
