### ISSUE TITLE
How to setup typeorm connection with oracle on aws lambda

### ISSUE THREAD

**Issue by amitmoondra** [typeorm/typeorm#6112]
we are using nodejs api on aws lambda.
But not able to get oracle db connection working in lambda
We have successfuly connected mssql and postres.
But we now need to connect oracle db.
Pleas guide us to do so, so it works on aws lambda

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
