### ISSUE TITLE
Fast Relation Id for many to many

### ISSUE THREAD

**Issue by chungchi300** [typeorm/typeorm#6120]
**Issue type:**

[ * ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[* ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ *] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```javascript
@Entity()
export default class Bid {
  @PrimaryGeneratedColumn()
  id: number;
    @ManyToOne(
    type => User,
    user => user.pendingBids,
    {
      nullable: false,
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
    },
  )
  user: User;
  @ApiModelProperty()
  @RelationId((self: PendingBid) => self.user)
  @Column({ nullable: false })
  userId: number;
}
```

for 8000 Bid,  await this.repo.find(); take 6seconds, but this.repo.createQueryBuilder().getRawMany(); just take 0.2seconds. Does it has a method for querying it fastly using the find()?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
