### ISSUE TITLE
QueryFailedError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"

### ISSUE THREAD

**Issue by zgababa** [typeorm/typeorm#6125]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello, 

I'm having this error ` QueryFailedError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"` when I run tests on the CI, it's happens one time in two.

Here my configuration : 
![image](https://user-images.githubusercontent.com/3789044/82797049-cebc5500-9e76-11ea-9a02-3995ef2955da.png)

I have already seen this issue https://github.com/typeorm/typeorm/issues/777, but it's closed and it seems resolved. 

Thanks for any help !

**Comment by zgababa** [comment]
I think, it's because Jest run tests in parallel, so as I have `synchronise:true`, typeorm creates two tables in the same time, and I receive the error `pg_type_typname_nsp_index`

**Comment by zgababa** [comment]
For the posterity, I run tests in sequential to fix this issue, with `jest --runInBand`

**Comment by FelipeRaulino** [comment]
> For the posterity, I run tests in sequential to fix this issue, with `jest --runInBand`

Damn, I spent too much time with that problem for not understanding the default behavior of jest. Thanks, it solved here.
