### ISSUE TITLE
cannot addselect specific element from join table without id

### ISSUE THREAD

**Issue by cyan-kinesin** [typeorm/typeorm#6129]
**Issue type:**
[v] question

**Database system/driver:**
[v] `mysql` / `mariadb`

**TypeORM version:**
[x] `7.0.0` (or put your version here)

How can I select join table specific element without id ?

example when app user has reviews

```ts

const reviews = repository.createQueryBuilder('review')
    .addSelect([ 'appUser.name' ])
    .leftJoin('review.appUser', 'appUser')
    .skip(0)
    .take(10)
    .getMany();

console.log(reviews[0].appUser); // null

```

but with app user id add selection, review has app user.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
