### ISSUE TITLE
@Column and @CreateDateColumn have different default precision

### ISSUE THREAD

**Issue by yokomotod** [typeorm/typeorm#6130]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
class EntityA {
  @Column()
  readonly dateTimeColumn!: Date;

  @CreateDateColumn()
  readonly createdAt: Date;
 }
```

`typeorm migration:create -n CreateEntityA`

It creates `DATETIME` (= `DATETIME(0)` ) for `dateTimeColumn` and `DATETIME(6)` for `createdAt`.

Is this intended difference ?

Perhaps, caused by this difference:
https://github.com/typeorm/typeorm/blob/0.2.25/src/driver/mysql/MysqlDriver.ts#L234
https://github.com/typeorm/typeorm/blob/0.2.25/src/driver/mysql/MysqlDriver.ts#L279

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
:thinking: Is it causing problems to have this difference?  I don't know if there's explicitly a good reason for the difference but given it's set now we probably shouldn't change it right now.

To chat about it and discuss it check out the slack.

**Comment by yokomotod** [comment]
@imnotjames thank you for your response.

No big problem, just I want to unify `DATETIME` precision on my db and hoped these default are same.
