### ISSUE TITLE
How to Set typeorm connection pool size in Nestjs? (MySQL)

### ISSUE THREAD

**Issue by sjlee1125** [typeorm/typeorm#6136]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I saw this link _https://stackoverflow.com/questions/46843248/create-connection-pool-typeorm_

This article explained
```ts 
"extra": {
  "connectionLimit": 5
}
```

But I thought that this is just max limit of connection instead of creating connection pool in advance

How can I create typeorm(mysql) connection pool in Nestjs?

**Comment by kauandotnet** [comment]
I use @nestjs/config, 

```typescript
function typeormModuleOptions(): TypeOrmModuleOptions {
...
retryAttempts: 5, // I'll use as connectionLimit
retryDelay: 300, // ms
...
}
```

**Comment by imnotjames** [comment]
`connectionLimit` sets the  maximum size of the connection pool.  There's no option to artificially inflate the size of the connection pool when the connections are not in use.
