### ISSUE TITLE
Questions around cascades and soft deletes

### ISSUE THREAD

**Issue by maclockard** [typeorm/typeorm#6139]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Question**
I have a couple questions around relation cascades that are not answered by the [documentation](https://typeorm.io/#/relations/relation-options).

1. What's the difference between setting `cascade: "remove"` and  setting `onDelete: "CASCADE"`?
2. Does setting `onDelete: "CASCADE"` cause soft deletes to cascade as well? or can that only be specified using the `cascade` option.
3. Does `cascade: "recover"` mean that recovering a soft deleted object will cascade the recovery?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
