### ISSUE TITLE
Query failed - aws lambda + postgres + typeOrm

### ISSUE THREAD

**Issue by AlexSun98** [typeorm/typeorm#6148]
**Environment:**
postgres: 7.4.1
typeorm: 0.2.19

**Description**
I set connection pool size to 1 and executed two identical select queries. The first one was okay, but the second one failed.  Does anyone experience this issue? This error doesn't occurs on every call. A bit strange.

**Comment by AlexSun98** [comment]
it turned out that's the same error mentioned in https://github.com/typeorm/typeorm/issues/5112

**Comment by AlexSun98** [comment]
Error details: "release called on client which has already been released to the pool"
![image](https://user-images.githubusercontent.com/21162558/83369667-79e18700-a400-11ea-870a-19766478b616.png)

Did anyone find a good solution to resolve this problem?

**Comment by imnotjames** [comment]
Duplicate of #5112
