### ISSUE TITLE
Cannot read property 'isValid' of undefined

### ISSUE THREAD

**Issue by Lectem** [typeorm/typeorm#6155]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

When I try to use static functions of ObjectID, I'm getting TypeError: Cannot read property 'isValid' of undefined.

Otherwise it seems the `ObjectID` type can be used just fine.

My code:

```ts
import { ObjectID, MongoEntityManager, DeleteResult, DeleteWriteOpResultObject } from 'typeorm';


    async getOne(id: string|ObjectID): Promise<Project> {
        if (!ObjectId.isValid(id)) {
            throw new BadRequestException('Invalid project id');
        }
        // ...
    }
````

The generated `.js`:

```js

    async getOne(id) {
        if (!typeorm_2.ObjectID.isValid(id)) {
            throw new common_1.BadRequestException('Invalid project id');
        }
        // ...
    }
``` 

With the debugger attached, I can see that there is no ObjectID attribute in `typeorm_2`.
I also tried to import directly from `typeorm/driver/mongodb/typings`, and I have the same issue.

**Comment by anrolmar** [comment]
I have the same issue.

**Comment by imnotjames** [comment]
You'd need to import it from mongo - not from our typings.  We just declare the class, we don't provide it.

Alternatively, you can do:

```
(connection.driver as MongoDriver).mongodb.ObjectID.isValid(id)
```
