### ISSUE TITLE
ReferenceError: Cannot access 'BrandEntity before initialization

### ISSUE THREAD

**Issue by olaven** [typeorm/typeorm#6159]
**Issue type:**

[X] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

When trying to read brands (`BrandEntity`) I am getting the following error: 
```
ReferenceError: Cannot access 'BrandEntity' before initializatio
```

```ts
import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    BaseEntity,
    ManyToOne,
    PrimaryColumn,
    JoinColumn,
    VersionColumn, OneToMany
} from "typeorm";
import {UserEntity} from "./UserEntity";
import {ResponseEntity} from "./ResponseEntity";

@Entity()
export class BrandEntity {

    @PrimaryColumn()
    id: string; 

    @Column({
        length: 150
    })
    name: string;

    @ManyToOne(type => UserEntity)
    owner: UserEntity;

    @OneToMany(type => ResponseEntity, (response: ResponseEntity) => response.brand, {
        //cascadeInsert: true,
        //cascadeUpdate: true,
        //cascadeRemove: true
        cascade: true
    })
    responses: ResponseEntity[]
}
```
```ts
import {Entity, PrimaryGeneratedColumn, Column, BaseEntity, ManyToOne} from "typeorm";
import {BrandEntity} from "./BrandEntity";

@Entity()
export class ResponseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        length: 1000,
        nullable: false
    })
    text: string;

    @Column({
        nullable: false
    })
    emotion: 'sad' | 'neutral' | 'happy';


    @ManyToOne(type => BrandEntity, brand => brand.responses, {
        eager: true
    })
    brand: BrandEntity;
}
```
Relevant config: 
```
{
    "name": "development",
    "type": "postgres",
    "host": "localhost",
    "username": "postgres",
    "password": "postgres",
    "database": "local",
    "synchronize": true,
    "logging": true,
    "entities": [
      "./src/server/entities/**.ts"
    ],
    "migrations": [
      "./src/server/migrations/**.ts"
    ],
    "dropSchema": true
  }
```

Is there something wrong with my relationship? Otherwise, I believe this is a bug. Any thoughts are greatly appreciated! 

Olav

**Comment by grbspltt** [comment]
might not be related but you forgot the second function parameter to @ManyToOne in your BrandEntity class.

```ts
    @ManyToOne(type => UserEntity) // <--- 2nd function here
    owner: UserEntity;
```

**Comment by olaven** [comment]
@grbspltt It was sadly not related, but I have updated. Thanks!

**Comment by m4tta** [comment]
Are you still running into this issue? Did you happen to be using next.js? I am currently suffering through this now.

**Comment by olaven** [comment]
@m4tta I ended up ditching Typeorm and going for "raw SQL" with `node-pg` instead.
Never looked back 😄

**Comment by imnotjames** [comment]
Seems like this is a configuration issue with next.js and how it approaches module definitions.  That's closer to a support question than an actionable issue on our part.

For questions similar to this, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by cdbattags** [comment]
Were you ever able to figure this out? I'm getting the same issue.

**Comment by h666t** [comment]
I have a similar problem and maybe it will help you. check all your relations and change them as follows.
```
// use string instead of function
// @ManyToOne(() => BlogSystemUser, (user) => user.blogs)
    @ManyToOne('BlogSystemUser', 'blogs')
```

**Comment by h666t** [comment]
> Were you ever able to figure this out? I'm getting the same issue.

I have a similar problem and maybe it will help you. check all your relations and change them as follows.
```
// use string instead of function
// @ManyToOne(() => BlogSystemUser, (user) => user.blogs)
   @ManyToOne('BlogSystemUser', 'blogs')
```

**Comment by themilkman** [comment]
I also had `Uncaught ReferenceError: can't access lexical declaration 'MyModelName' before initialization` errors when introducing a new relation. Although it was quite analog to the existing ones I could not figure out how to resolve (even tried rearranging imports, code etc to try to understand it). The way @h666t mentions works for me and I use it now but neither do I understand why this happens nor do I think the String solution is the "nicest way".
