### ISSUE TITLE
Is it okay to call getRepository() every function call?

### ISSUE THREAD

**Issue by mehtamanan** [typeorm/typeorm#6163]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Are there any caveats of calling getRepository() often?

```
class XService {
    private repository = getRepository(X)

    async function getX(id) { return this.repository.findOneOrFail({ id }) };
}

// OR

class XService {
    async function getX(id) { return getRepository(X).findOneOrFail({ id }) };
}
```

**Comment by Ginden** [comment]
> Are there any caveats of calling getRepository() often?

Not really, it's simple factory function.
