### ISSUE TITLE
Set column position/order in addColumn

### ISSUE THREAD

**Issue by diogodomanski** [typeorm/typeorm#6167]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25`

I have a migration file, which adds a new column to a table:

```ts
await queryRunner.addColumn("user_user", new TableColumn({
    name: "subscriber_id",
    type: "char",
    length: "36",
    isNullable: true,    
}));
```
After the migration is executed, the `subscriber_id` column is added correctly to `user_user` table, however at the end of columns list.

I wonder if there is a way to set the position of the new column (as MySQL allows us, with the modifiers 'FIRST` and `AFTER`).

I know that I can achieve that by calling 
```ts
queryRunner.query("ALTER TABLE ADD COLUMN `subscriber_id` CHAR(36) DEFAULT NUL AFTER `id`");
```
But I prefer using migration API instead of executing a harcoded SQL string.

**Comment by m-toyoda** [comment]
Is there no working around?

**Comment by ivanguimam** [comment]
Same ploblem

**Comment by pishguy** [comment]
+1

**Comment by hope-himalaya-ahuja** [comment]
is this feature added or not?

**Comment by nolawnchairs** [comment]
+100

**Comment by rcaceiro** [comment]
+1, please

**Comment by gferr-menezes** [comment]
+1

**Comment by felipe-gustavo** [comment]
Are some update about this feature??

**Comment by matthew-inamdar** [comment]
Would love to see this implemented!

**Comment by netojose** [comment]
+1

**Comment by williamisraelmt** [comment]
+1

**Comment by gisheri** [comment]
+1

**Comment by bizprat** [comment]
Any update?

**Comment by AlexMesser** [comment]
Duplicate of #541

**Comment by ridbay** [comment]
Has this been implemented?
I really need it

**Comment by orafaribeiro** [comment]
+1

**Comment by rabo-of-fincra** [comment]
+1 This feature is strongly needed

**Comment by GiulioWecove** [comment]
Why is this closed?

**Comment by edson-k** [comment]
+1
