### ISSUE TITLE
How to query certain columns and put data into entities  using relations? Or is there any other way?

### ISSUE THREAD

**Issue by Ryan2128** [typeorm/typeorm#6171]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

What i want get is not all columns but the columns i want dynamically with my code ? Is there any way ? 

For example, the following code:
```ts
this.articleRepository
      .createQueryBuilder('article')
      .leftJoinAndSelect('article.articleTags', 'article_tag')
      .leftJoinAndSelect('article.articleCategory', 'article_category')
      .leftJoinAndSelect('article.articleSeries', 'article_series')
      .leftJoinAndSelect('article_tag.tag', 'tag')
      .leftJoinAndSelect('article_category.category', 'category')
      .leftJoinAndSelect('article_series.series', 'series')
      .getMany()
```

The result:
![image](https://user-images.githubusercontent.com/33176053/83383729-4874b580-a418-11ea-8476-69a6e6206691.png)

I donot want get some columns, such as `article.effective`, `articleTags.createTime`, `articleTags.createTime` and so on, and i donot want to use `select: false` on the property of entity, i want get columns dynamically.

Can u help me ?

**Comment by Ryan2128** [comment]
@pleerock    How can I achieve this effect ? Can u help me ? Thanks.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
