### ISSUE TITLE
Saving with relations sets foreign key to null, why?

### ISSUE THREAD

**Issue by zhangyy91** [typeorm/typeorm#6176]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have two entities, Product and KeyValue as follows
```
import { Entity, PrimaryGeneratedColumn, Column, PrimaryColumn, ManyToOne, OneToMany } from "typeorm";

@Entity()
export class Product {
    @PrimaryGeneratedColumn()
    id: number;
    @OneToMany(type => KeyValue, keyvalue => keyvalue.product)
    keyvalues: KeyValue[];
}

@Entity()
export class KeyValue {
    @PrimaryColumn()
    productId: number;
    @PrimaryColumn()
    key: string;
    @Column()
    value: string;
    @ManyToOne(type => Product, product => product.keyvalues)
    product: Product;
}
```

```
import "reflect-metadata";
import { createConnection } from "typeorm";
import { Product, KeyValue } from "./entity/Product";

createConnection().then(async connection => {
    let product = new Product();
    let keyvalue = new KeyValue();
    keyvalue.productId = product.id = 1;
    keyvalue.key = 'key';
    keyvalue.value = 'value';
    await connection.manager.save(product);
    await connection.manager.save(keyvalue);

    product = await connection.manager.findOne(Product, 1, { relations: ['keyvalues'] });
     // this line causes the error
    await connection.manager.save(product);
}).catch(error => console.log(error));
```

When I try to save a product with relations fetched using the above code, I got "Column 'productId' cannot be null" error. The detailed SQL and error the as follows:

```
query: SELECT `Product`.`id` AS `Product_id` FROM `product` `Product` WHERE `Product`.`id` IN (?) -- PARAMETERS: [1]
query: SELECT `key_value`.`productId` AS `productId`, `key_value`.`key` AS `key` FROM `key_value` `key_value` WHERE ((`key_value`.`productId` = ?)) -- PARAMETERS: [1]
query: START TRANSACTION
query: UPDATE `key_value` SET `productId` = ? WHERE `productId` = ? AND `key` = ? -- PARAMETERS: [1,1,"key"]
query: UPDATE `key_value` SET `productId` = ? WHERE `productId` = ? AND `key` = ? -- PARAMETERS: [null,1,"key"]
query failed: UPDATE `key_value` SET `productId` = ? WHERE `productId` = ? AND `key` = ? -- PARAMETERS: [null,1,"key"]
error: Error: Column 'productId' cannot be null
```

In line 4, it sets productId of KeyValue to 1. Then in line 5, it trys to set productId to NULL, but productId is also one of the composite keys in KeyValue, so it fails. 

WHY? WHY to set the foreign key to NULL? WHY to set the foreign key twice with different values? This MUST be a BUG.

**Comment by zhangyy91** [comment]
OK, no developer cares about this issue. With so many open issues, I think this TypeORM may be far from production-ready. So goodbye, I will move to another ORM.

**Comment by haraldev01** [comment]
cannot believe this is still an issue... Completely unusable, tried for hours to make an update method but it failed every. single. time. because of this. How this ORM is somehow recommended in the NestJs documentation as the first thing you see when you go to the "databases" page is beyond me... Moving to Prisma...

**Comment by sashap8** [comment]
In my experience, this issue is caused by missing relations in the initial load of the entity that is being updated. I'll explain my situation and how I fixed it in case it helps someone.

In my case the issue was that my Typeorm model A had a one-to-many relationship with entity B which in turn had a one-to-many relationship with entity C. There was also an optional one-to-many relationship between A and C.

Loading relations like:

`
relations: {
        b: {
          c: true,
        },
 }
 `
 
Caused the foreign key to try to be set to NULL. But loading the entity through entity A directly worked:

`
relations: {
        b: {
          c: true,
        },
        c: true
 }
 `

**Comment by itinance** [comment]
Having a One2Many relation with {eager:true} doesn't prevent that TypeORM erases related columns and set them to NULL on a later save

    @ManyToOne(() => NewsEntity, (entity) => entity.articles, { eager: true })

We started to remove all fk-relations in typeorm to prevent such issues. It's really dangerous to rely on it.

**Comment by Chiyo-no-sake** [comment]
Just in case anyone stumbles upon this in 2025, I found out that if you try to save plain objects it behaves as stated in the issue, when in reality it is required to create a new instance of the entity class (explicitly with `new Product()`) and assign all properties manually or via Object.assign.
In this way, it works
