### ISSUE TITLE
softRemove does not trigger BeforeRemove/AfterRemove

### ISSUE THREAD

**Issue by benediktvolke** [typeorm/typeorm#6179]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25`

**Steps to reproduce or a small repository showing the problem:**

`repository.softRemove` does not trigger `BeforeRemove `or `AfterRemove`.

```ts
@Entity()
export class Entity {
     ....

     @BeforeRemove()
     beforeRemove() {
         console.log('BeforeRemove');
     }

     @AfterRemove()
     afterRemove() {
         console.log('AfterRemove');
     }
}
```

```ts
const entities = await repository.find();
const entitiesAfterSoftRemove = await repository.softRemove(entities);
```

**Comment by alexbuicescu** [comment]
I'm also experiencing this in postgres. `beforeUpdate` and `afterUpdate` are called instead of `beforeRemove` and `afterRemove`

**Comment by juan91** [comment]
I'm also experiencing this in MongoDB

**Comment by grptx** [comment]
it's because the softRemove perform an UPDATE query on the @DeleteDateColumn column.
so the only workaround  i found is to search the softdeleted row in the @AfterUpdate and analize the deletedcolumn:
```
    //Documents.ts entity
    @AfterUpdate()
    async updateHistory() {
        try {
            const updated: Documents = await Documents.findOne({
                where: {
                    id: this.id,
                },
                withDeleted: true,
            });
            let action: DocumentsHistoryLogActions = DocumentsHistoryLogActions.UPDATED;
            if (updated && updated.deletedAt !== null) {
                action = DocumentsHistoryLogActions.DELETED;
            }
            await Utils.addDocumentHistoryLog(this, action);
        } catch (e) {
            logger.error(e.message);
        }
    }
```

**Comment by wsmd** [comment]
Another possibly related issue i'm facing is while `softRemove` does actually trigger the `beforeUpdate` method of a custom subscriber, `event.updatedColumns` always seem to be an empty array in that case. Unless I'm missing something, I'd expect the "deleted at" column to be included in the `event.updateColumns` when calling `softRemove()`.

I'm using postgres 13 and `typeorm@0.2.31`

```ts
@Entity()
export class User extends BaseEntity {
  @DeleteDateColumn({ name: 'deleted_at' })
  deletedAt: Date | null;
}

@EventSubscriber()
export class UserSubscriber implements EntitySubscriberInterface<User> {
  listenTo() {
    return User;
  }

  beforeUpdate(event: UpdateEvent<User>) {
    console.log(event.updatedColumns); // outputs `[]` when calling softRemove
  }
}
```

**Comment by mossa-Sammer** [comment]
any update on this ?

**Comment by joelcollyer** [comment]
Just confirming that this is also a Bug in our project as well (MySQL and SQLite).

We are trying to use subscribers to track user interactions. In this case a "deletedBy" user relationship.

**Observed Behaviour**

 - `.softDelete()` triggers `beforeUpdate`, but there's no information in the `event` to indicate that it's a soft delete/remove.
 - `beforeRemove` and `afterRemove` events are not triggered by `.softDelete`

**Expected Behaviour**
`.softRemove` and `.softDelete` should trigger the `beforeRemove` and `afterRemove` events in subscribers.

**Comment by eder-ig** [comment]
The only way to run @BeforeRemove is using manage.remove().
But the same after running @BeforeRemove permanently deletes the record from the database.
That was my experience with mariadb 10.4

`@BeforeRemove()
  console.log('OOoo')
  delete() {
    this.deleted_by = jwtDecodeToken(ap['authorization']).nome
  }`

`return await this.userRepository.remove(userToRemove);`

**Comment by aleksey-tk** [comment]
Confirming this as a bug. Any update from maintainer please?

**Comment by spotykatch** [comment]
Working on this [PR](https://github.com/typeorm/typeorm/pull/8403). As it's a breaking change, it would not be released soon. And it's not ready. Waiting for a review.
For now you can use `afterUpdate` like so.
```ts
afterUpdate(event: UpdateEvent) {
  const { quertRunner: { data: { action } } } = event;
  if (action === "soft-remove") {
    // do soft-remove stuff
  }
}
```
```ts
await repository.softRemove(entity, { data: { action: "soft-remove" } });
```
It's not a bug as soft-remove does not remove anything. If it should be a `remove` then what is `recover`?

**Comment by aleksey-tk** [comment]
Unfortunately your solution doesn't work for me. I need to send some info when an object is soft deleted, so for now i am achieving differently.

I find it strange but it works:

`async afterUpdate(event: UpdateEvent<any>) {
    const resource = await event.manager.findOneOrFail(
      ResourceEntity,
      event.entity.id,
    )
    
    if (!event.entity.deleted_at && resource.deleted_at) {
      this.eventEmitter.emit(...)
    }
  }`
