### ISSUE TITLE
leftJoinAndMapOne how do use subquery

### ISSUE THREAD

**Issue by icemanpro** [typeorm/typeorm#6183]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
 const bb= await getRepository(Ticket).createQueryBuilder("ticket")
  .where("ticket.serviceProviderId=:sp",{sp:serviceProviderId})
      .andWhere("ticket.status=:status",{status:orderStatusType.ticketFinish})
         .leftJoinAndMapOne("ticket.lastCallback",subQuery=>{
        return subQuery.select().from(Callback,"callback")
      },"callback1","`callback1`.ticketId=`ticket`.id and `callback1`.id=2")
      .getManyAndCount();
 ```

```ts 
 const aa= await getRepository(Ticket).createQueryBuilder("ticket")
      .where("ticket.serviceProviderId=:sp",{sp:serviceProviderId})
      .andWhere("ticket.status=:status",{status:orderStatusType.ticketFinish})
      .leftJoinAndMapOne("ticket.lastCallback","ticket.callbacks","callback",
        "callback.id=2")
      .getManyAndCount();
 ```

why aa have lastCallback,but the bb haven't ?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
