### ISSUE TITLE
count() stopped working on 0.2.25

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#6188]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

We have been running TypeORM version 0.2.22. When npm updated to 0.2.25 we started seeing the following error:

```
at /app/node_modules/typeorm/query-builder/QueryBuilder.js:599:35
	EntityColumnNotFound: No entity column "collectionId" was found.
    at step (/app/node_modules/tslib/tslib.js:141:27)
    at /app/node_modules/typeorm/query-builder/QueryBuilder.js:596:42
    at new EntityColumnNotFound (/app/node_modules/typeorm/error/EntityColumnNotFound.js:10:28)
	Error: "No entity column \"collectionId\" was found."
```

**From** 

`const total = await this.conn.getRepository(Scuba).count({collectionId});`

Downgrading back to 0.2.22 resolved the issues

**Working Test Query:**
`SELECT count("collectionId") from scuba where "collectionId" = ${collectionId}`

**Comment by pleerock** [comment]
please enable logging and show what SQL before and after

**Comment by njam** [comment]
Just mentioning we experienced a similar problem when upgrading typeorm from 0.2.24 to 0.2.25. The reason was that we used a column name in a where condition that didn't exist on the table. It seems 0.2.24 silently ignored this, and 0.2.25 gives an error.

**Comment by SloCompTech** [comment]
Same issues just showed up. I have column in database, but it still gives me an error
```
(node:26987) UnhandledPromiseRejectionWarning: EntityColumnNotFound: No entity column "authRef.expireAt" was found.
    at new EntityColumnNotFound (/.../node_modules/typeorm/error/EntityColumnNotFound.js:10:28)
    at /.../node_modules/typeorm/query-builder/QueryBuilder.js:599:35
    at Array.map (<anonymous>)
    at /.../node_modules/typeorm/query-builder/QueryBuilder.js:596:42
    at Array.map (<anonymous>)
    at SelectQueryBuilder.QueryBuilder.computeWhereParameter (/.../node_modules/typeorm/query-builder/QueryBuilder.js:594:40)
    at SelectQueryBuilder.where (/.../node_modules/typeorm/query-builder/SelectQueryBuilder.js:305:30)
    at Function.FindOptionsUtils.applyOptionsToQueryBuilder (/..../node_modules/typeorm/find-options/FindOptionsUtils.js:84:16)
    at Function.FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder (..../node_modules/typeorm/find-options/FindOptionsUtils.js:59:25)
    at EntityManager.<anonymous> (/..../node_modules/typeorm/entity-manager/EntityManager.js:473:75)
(node:26987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26987) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SloCompTech** [comment]
If anyone needs quick solution:
- You can't use relations columns in where with find function
- use query builder instead

**Comment by MessiasLima** [comment]
I am facing the same problem with `findAndCount`

**Comment by pleerock** [comment]
I think answer for this issue is given - you are trying to use columns that are not defined in your entity. @rightisleft in your case you need to add `collectionId` column into your entity.
