### ISSUE TITLE
Neo4J Support

### ISSUE THREAD

**Issue by taylor009** [typeorm/typeorm#6190]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

I'm sure if there is already something in the works or not. I would like support for Neo4j. 
If there isn't anything in the works or there is I can or will like to contribute in any way.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by adam-cowley** [comment]
To continue the discussion we were having on the Slack channel, @pleerock's opinion is that Neo4j wouldn't work well with the current ORM design.  On the surface _most_ things would work, but there would be some headaches around how we could make querying and persistence work.

From the outside it looks like I'd need to implement classes for connection options, the driver, a query runner and an entity manager - converting the DSL into Cypher to read/write.

Ideally, any integration should be seamless - switching `type: "mysql"` to `type: "neo4j"` should provide basic functionality.  For relationships with properties, maybe we'd need a `@RelationshipEntity` decorator.

The other option would be to create a separate library.  If this is the best option, are there elements of TypeORM that I could lean on?  

I'm a fan of the library so it would be nice to contribute.  If it's not possible, we can just close the issue and explore other options.

@taylor009, @ev-dev, @tgroutars I'd love to hear your thoughts.

**Comment by tgroutars** [comment]
@adam-cowley great thoughts!
Right now I'm toying with the idea of creating a library that would cover our own needs at work. Waiting for a library to be mature enough to be open sourced and used in production might take too long, so we'll probably do our own thing for now. 

Happy to contribute to an open source project in parallel if you start one, though. 

Ideally the api would be heavily inspired from typeorm. 

Some other thoughts regarding the design: we have a graphql api and it would be pretty awesome to be able to make a single query to the database for each queries. neo4j-graphql-js does just that but (1) you have to define your graphql schema first, and I'm not a fan of defining "models" like that, (2) there's not a 1/1 mapping between our schema and the db, some things are internal and should never be exposed to the client, (3) it doesn't help in writing custom queries, the graphql api is not the only layer that can interacts with the db, so we'd still have to write custome cypher queries a lot, and (4) we need to have control of authorization for each node that we expose to the graphql api. 

So there are 2 features that would be pretty helpful for us:
- the ability to easily eager load exactly what we need
- for authorization, it would be neat to not need a round trip to the db to validate every node. Ex if someone is trying to read a document, I need to know if they're on the team that owns the project of that document. Ideally this wouldn't require to query the db in the resolver, so we need a way to easily include what we need in the base query. The solution I'm seeing right now is to define computed properties on models that would actually add a subquery when you're trying to read them. It shouldn't be included by default so we'd need a way to specify which ones we need when querying it too 

Hope that makes sense, it's a bit early and I'm on my phone 😅

**Comment by rhuankarlus** [comment]
up

**Comment by Jacse** [comment]
@tgroutars did you guys roll your own closed-source lib in the end?

**Comment by adam-cowley** [comment]
I started experimenting on an independent library a few months ago - it doesn't have the advantage of switching between db providers but was relatively easy to iterate on.  I paused the work due to an apparent lack of interest.

https://github.com/adam-cowley/neode-ogm

Test implementation here: https://github.com/adam-cowley/neode-ogm-test

The challenge is mapping Neo4j terms into those used by relational databases.  How do you map an entity to a relationship in a `@OneToMany` etc.

So here's a question, is the ability to switch between database providers important?

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
