### ISSUE TITLE
Pulling changes from 'next' branch

### ISSUE THREAD

**Issue by narlack** [typeorm/typeorm#6193]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello!

Can you give some information about pulling of changes from version next to latest?

I'm very interested for the feature 'setFindOptions' to QueryBuilder.

**Comment by imnotjames** [comment]
I've been backporting a number of features from `next` to `master` but there's no timeline for that change to get pulled in.

**Comment by imnotjames** [comment]
I've been backporting a number of features from `next` to `master` but there's no timeline for that change to get pulled in.
