### ISSUE TITLE
feature: fake migrations for existing tables

### ISSUE THREAD

**Issue by rubiin** [typeorm/typeorm#6195]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

it would be great to  fake migrations something like https://docs.djangoproject.com/en/1.11/ref/django-admin/#cmdoption-migrate-fake  .

**Comment by rubiin** [comment]
@pleerock this can come in handy

**Comment by rubiin** [comment]
heres a workaround i did

```js
import "reflect-metadata";
import {createConnection, MigrationExecutor} from "typeorm";


createConnection().then(async connection => {
    const mig = new MigrationExecutor(connection);
    await mig.showMigrations();
    const migrations = await mig.getAllMigrations();
    for (let migration of migrations)
    {
        await mig.insertMigration(migration);
    }

}).catch(error => console.log(error));


```

**Comment by rubiin** [comment]
revised version:


import 'reflect-metadata';
import { createConnection, MigrationExecutor } from 'typeorm';
import config from './config';
import { join } from 'path';

createConnection({
	type: 'postgres',
	host: config.db.host,
	port: config.db.port,
	username: config.db.username,
	password: config.db.password,
	database: config.db.database,
	entities: [join(__dirname, 'entities/*{.ts,.js}')],
	logging: 'all',
	migrationsTableName: 'nest_migration',
	logger: 'advanced-console',
	migrations: [join(__dirname, 'migrations/**/*{.ts,.js}')],
	cli: {
		migrationsDir: join('src', 'migrations'),
	},
})
	.then(async connection => {
		const mig = new MigrationExecutor(connection);
		await connection.manager.query(
			` CREATE TABLE IF NOT EXISTS "nest_migration" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_d8a054ea06850edd968e06c00e4" PRIMARY KEY ("id"))`,
		);
		const migrations = await mig.getAllMigrations();

		console.log(migrations);

		for (let migration of migrations) {
			//	await mig.insertMigration(migration);

			await connection.manager.query(
				` INSERT INTO "nest_migration"("timestamp", "name") VALUES ($1, $2) `,
				[migration.timestamp, migration.name],
			);
		}
	})
	.catch(error => console.log(error));

**Comment by rubiin** [comment]
@pleerock can we dosomething like this with the cli. i find it a good addition

**Comment by Pipeliner** [comment]
@rubiin was something like this  feature implemented?

**Comment by rubiin** [comment]
Sadly no. I have to moveon to MikroOrm due to so many things

**Comment by Pipeliner** [comment]
Could you please reopen this issue then?

**Comment by rubiin** [comment]
@ahmedosama94 You can go ahead. This issue has not been picked up. But make sure they are willing to add it first though
