### ISSUE TITLE
Query builder with getRawMany returns count column as string

### ISSUE THREAD

**Issue by jamg44** [typeorm/typeorm#6196]
**Issue type:**

[ ] question
[ ] bug report
[* ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ *] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[* ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Ussing query builder with getRawMany returns aggregated count column as a string.

```js
      const countByWorker = await Ticket.createQueryBuilder()
        .select(['worker_id', 'status', 'count(*) as count'])
        .groupBy('worker_id, status')
        .getRawMany();
```

Is retuning this:

```js
[
  RowDataPacket { worker_id: 0, status: 'OK', count: '27217' },
  RowDataPacket { worker_id: 0, status: 'TOEXTRACT', count: '743' },
  RowDataPacket { worker_id: 1, status: 'KO', count: '1' },
  RowDataPacket { worker_id: 1, status: 'OK', count: '2' }
]
```

It would be expected 'count' column to be typeof number.

Thanks
Javier

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by hengkx** [comment]
any progress?

**Comment by Nicholas-Westley** [comment]
I am experiencing using postgres so it is not limited to mysql / mariadb

**Comment by nebkat** [comment]
`getRawMany()` does not perform any processing on the result from the driver, so not really sure what we can do here. The long term solution is that the query builder will support more features and `getRawMany()` won't be required.

**Comment by 1valdis** [comment]
It works as expected because result of `count()` can be bigger than `Number.MAX_SAFE_INTEGER`. So I'd rather expect count to be of type `bigint`.

**Comment by lukzard** [comment]
Had the same "issue". Which isn't an issue of typeorm. I assume that count(*) returns a data type specific to the database that is not directly convertible to javascript's numeric data type. Example if the db return bigint, then javascript will mark it as string. 

Simple solution is to cast to integer or int in SQL context. I.e., in your example:

`const countByWorker = await Ticket.createQueryBuilder()
        .select(['worker_id', 'status', 'count(*)::int as count'])
        .groupBy('worker_id, status')
        .getRawMany();`

::int is a short form of cast in postgres; adapt whatever is the way to cast in your db

**Comment by bladx** [comment]
@lukzard solution seems really what I was looking for .
But For some reason this does not work with MySQL casting.
I tried the following:
`query
      .addSelect("CAST('3' AS UNSIGNED)")
      .addSelect("CAST('foo' AS UNSIGNED)")`
And here is my result:
`"CAST('3' AS UNSIGNED)": "3",
  "CAST('foo' AS UNSIGNED)": "0",`
So as you can see the string "foo" is well cast ton int 0 but JSON still displays it as a string.

**Comment by lukzard** [comment]
think cast() in mysql does something bit different; see convert()

https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_convert, make sure you convert to the numeric datatype you wish; i.e. integer, double, float, etc. but then that is also translatable in javascript's "numeric" data type, w/o converting it to string given limitations of the numeric data type. @1valdis provided a more precise answer for what to look at when understanding the numeric datatype under javascript.

**Comment by lukzard** [comment]
also, why did you cast '3' and not 3 like this - 

`
query .addSelect("CAST(3 AS UNSIGNED)")\
`

whatever is in .addSelect("") executes directly in SQL context, so you should write it as you would in your db queries.

**Comment by bladx** [comment]
Thanks for the help, but I also tried `CONVERT()` and it did not work neither.

But I still found something interesting.
`.addSelect("33", "foo")` is converted to MySQL: `SELECT 33 AS "foo"` (so 33 as a number not a quoted string).
But for some reason, typeorm returns: `RowDataPacket { foo: '33' }`.
when using createQueryBuilder().getRawOne().

Am I missing something?

**Comment by lukzard** [comment]
mysql> SELECT 1 - 2;
        -> -1
mysql> SELECT CAST(1 - 2 AS UNSIGNED);
        -> 18446744073709551615
mysql> SELECT CAST(CAST(1 - 2 AS UNSIGNED) AS SIGNED);
        -> -1

have you seen this in the mysql docs?

**Comment by bladx** [comment]
This seems pretty logic to me.
But this is a MySQL behaviour (between SIGNED and UNSIGNED correspondance).

The issue here is that the exact sample code from their documentation (https://typeorm.io/#/select-query-builder/getting-values-using-querybuilder) is not working as expected:
```
const photosSums = await getRepository(User)
    .createQueryBuilder("user")
    .select("user.id")
    .addSelect("SUM(user.photosCount)", "sum")
    .groupBy("user.id")
    .getRawMany();

// result will be like this: [{ id: 1, sum: 25 }, { id: 2, sum: 13 }, ...]
```
I get: `[{ id: 1, sum: '25' }, { id: 2, sum: '13' }, ...]` instead.
Using typeorm `v0.2.31` and MySQL `v5.7.25`.

**Comment by bladx** [comment]
I upgraded to MySQL `v8.0.19` and still getting this issue.
Also I noticed we get the same issue with `MONTH()` and `YEAR()` functions.
I believe this is the case for all MySQL native functions that return a number.

**Comment by lukzard** [comment]
> I upgraded to MySQL `v8.0.19` and still getting this issue.
> Also I noticed we get the same issue with `MONTH()` and `YEAR()` functions.
> I believe this is the case for all MySQL native functions that return a number.

try casting that mysql data type to all numeric types available in mysql, and see which one are interpreted by javascript as number (or otherwise worded, which mysql data types fit into javascript's data types)... 

example from similar observations in postgres -
```
select 1::bigint as x; results in {... x: '1' ...}
select 1::numeric as x; results in {... x: '1' ...}
select 1::decimal as x; results in {... x: '1' ...}
**select 1::int as x; results in {... x: 1 ...}**
select 1::float as x; results in {... x: '1' ...}
**select 1::double precision as x; results in {... x: 1 ...}**
```

if that does not work, then i guess it has to do with how the driver used by typeorm converts data types in between the two technologies, i.e. the database system mysql and the runtime environment of the javascript language nodejs/webkit or whatever sits behind

**Comment by imnotjames** [comment]
This is entirely on the upstream MySQL driver.

For `getRawMany()` we don't coerce anything to a number - so you're seeing what the upstream driver is returning.

In these cases the driver is somehow deciding that these are strings - likely because the underlying RowDataPacket from the server is not hinting it with the correct number type because it can't.

This is not an issue with TypeORM as far as I can tell.

**Comment by WonDongGyun** [comment]
Hello. This happened to me while using mysql. Mysql's CONVERT, CAST still returned the string to me. So I solved the problem using @Transform. I hope it will help others who face this problem.



This code example is the result of using mysql's CAST or CONVERT.
```typescript
		const findTechnician = await this.createQueryBuilder("t")
			.select([
				"t",
				"technicianItem",
				"technicianConcept",
				"concept",
				"item",
				"technicianLike"
			])
			.addSelect(
				`CAST(CASE WHEN technicianLike.like_count IS NULL THEN 0 
				      ELSE technicianLike.like_count 
					  END AS SIGNED INTEGER)`,
				"t_likeCount"
			)
			.leftJoin("t.technicianItem", "technicianItem")
			.leftJoin("t.technicianConcept", "technicianConcept")
			.leftJoin("technicianConcept.concept", "concept")
			.leftJoin("technicianItem.item", "item")
			.leftJoin(
				`(${likeCountQuery.getQuery()})`,
				"technicianLike",
				"technicianLike.technicianId = t.technicianId"
			);

// return like_count = "0"
```


This code example is the result of using @Transform

```typescript
@Entity("technician")
export class Technician extends BaseModel {

...

	@Column("int", { select: false })
	@Transform(({ value }) => parseInt(value))
	likeCount: number;

...

}
```


```typescript
		const findTechnician = await this.createQueryBuilder("t")
			.select([
				"t",
				"technicianItem",
				"technicianConcept",
				"concept",
				"item",
				"technicianLike"
			])
			.addSelect(
				`CASE WHEN technicianLike.like_count IS NULL THEN 0 
				      ELSE technicianLike.like_count 
					  END`,
				"t_likeCount"
			)
			.leftJoin("t.technicianItem", "technicianItem")
			.leftJoin("t.technicianConcept", "technicianConcept")
			.leftJoin("technicianConcept.concept", "concept")
			.leftJoin("technicianItem.item", "item")
			.leftJoin(
				`(${likeCountQuery.getQuery()})`,
				"technicianLike",
				"technicianLike.technicianId = t.technicianId"
			);

// return like_count = 0
```
