### ISSUE TITLE
How can i change the transaction option when i save using BaseEntity

### ISSUE THREAD

**Issue by rickydj** [typeorm/typeorm#6197]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9`

Hi people, i want to know how i can change the SaveOptions inside BaseEntity model, i tried putting it as decorator using @SaveOptions inside the model but this didn't work, i've read the source code about BaseEntity but i didnt see anything that i could use to deactivate transactions during save, this is because the cordova plugin for sqlite doesn't use transactions, and i feel that i cant save or update, even remove info from the database by this issue

Thanks for your help

**Comment by fstn** [comment]
Did you find a solution? I would like to do the same thing

**Comment by imnotjames** [comment]
Last I read, cordova silently ignores transactions.

If that's not the case Please comment on #4075 and I'll remove them.

There's no feature to prevent this in the active record pattern.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
