### ISSUE TITLE
What is the best way to create and feed tables at first run in production?

### ISSUE THREAD

**Issue by Kolisium** [typeorm/typeorm#6198]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25`

**Steps to reproduce or a small repository showing the problem:**

I would like to know what is the best way to create the database tables in production when the app run for the first time on the device, in debug mode I use```synchronize: true``` but in production I cannot use this config.

Another point, I need to feed some tables with data in the newly created bank and this is done only once, how can I do this?

If it is possible to provide an example I will be very grateful!

**Comment by rubiin** [comment]
you can feed data through migration. First generate the migration and as the last query inside the query up, you can do the insertion

**Comment by imnotjames** [comment]
You can even have multiple sets of migrations that migrate in different ways!  If the migrations are in a different directory you can specify them from the TypeORM command line & load only the seeding migrations to run - or even prevent them from saving persistence so you always run the seeds (like for tests)

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
