### ISSUE TITLE
Feature Request: Flexibility in Foreign Key names

### ISSUE THREAD

**Issue by DavidPMacNeil** [typeorm/typeorm#620]
This may only affect string type column id's on MSSQL right now, but tables are expected to be expressed as follows:

```
@Entity()
class Cat {
    @PrimaryColumn()
    id: number;
}
```

Whereas, if we have a table defined like:

```
@Entity()
class Dog {
    @PrimaryColumn('nvarchar')
    DogID: string;
}
```

We run into a few problems. Right now, it seems that it is always expecting the primary key to be named ```id```. And to reference it in a way like:

```
// New
@Entity()
class Cat {
    @PrimaryColumn()
    id: number;

    @Column('nvarchar)
    dogDogID: string; // Need to do this to allow the Foreign Key to work

    @ManyToOne(type => Dog, Dog.cats)
    dog: Dog;
}

// New
@Entity()
class Dog {
    @PrimaryColumn('nvarchar')
    DogID: string;

    @OneToMany(type => Cat, Cat.dog)
    cats: Cat[];
}
```

Ideally in the cat entity, we could simply use ```DogID```, rather than having to insert new values infront of it.

**Comment by pleerock** [comment]
I don't understand what is your issue? Do you have some error? Isn't schema built for you? Or what? I added test I don't understand what is your issue? Do you have some error? Isn't schema built for you? Or what? I added [test](https://github.com/typeorm/typeorm/commit/565b1a4ce25a9df8cb18377e1c9abfa7f8a0aec2) that makes exactly what you wrote and it works fine. Please concretize your issue.

**Comment by DavidPMacNeil** [comment]
I Will attach screenshots to show what I mean. I wrote a cat and dog just like yours. 
[Here are the screenshots](http://imgur.com/a/JUf6c)

As you can see, removing the explicit naming for the FK column still gives me a FK name of `dogDogID`. I'd like my FK to simply be named and accessed as `DogID`.

**Comment by pleerock** [comment]
Okay so as I understood the problem is that you want to have `DogID` column name instead of `dogDogID` ?

**Comment by DavidPMacNeil** [comment]
Yes exactly.

**Comment by pleerock** [comment]
Its not possible to specify custom fk column name at the moment and I don't plan such feature in the near future. Currently it creates foreign keys based on the column name and name of the referenced column which is logically correct

**Comment by pleerock** [comment]
What you should really do is to change name of your `DogID`. It should be just `id`. That will make your model logically correct and database schema logically correct as well.

**Comment by DavidPMacNeil** [comment]
I understand why you have Foreign Keys the way they currently are working. But what about scenarios where tables have multiple ids? Composite keys, or a master table referencing 2+ child tables where comparisons must be made to multiple ID fields that cannot be all named ID.

**Comment by pleerock** [comment]
its not named by `"ID"`, as I told it uses column name + referenced column name. For example if you have property `cat` that referenced two columns: `name` and `title` in the `Cat` entity it will create two columns in the `Dog` with following column names: `catName` and `catTitle`. Everything is logically correct.

**Comment by hisamu** [comment]
> What you should really do is to change name of your DogID. It should be just id. That will make your model logically correct and database schema logically correct as well.

IMHO the database shouldn't be changed to suit how a library works. If you're using a legacy database or have a strict company standard as my case, then the library becomes unsuitable.

@pleerock as for you not planning it in the near future: would you be open to someone else implementing it or you just don't think it's of value for the lib?

**Comment by pleerock** [comment]
I just remembered use different name. Try this:

```ts
@ManyToOne(...)
@JoinColumn({ name: "DOGID" })
```

**Comment by DavidPMacNeil** [comment]
@pleerock Yes this works great, thank you!
