### ISSUE TITLE
When performing asyncronous batches of inserts auto-increment value isn't always used

### ISSUE THREAD

**Issue by ThomasRedstone** [typeorm/typeorm#6200]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[0.2.25] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I am processing a large amount of data in a CSV, my plan is to batch it into 100 rows per insert, and every 100 batches, pause until they're done, my code is here:
https://gist.github.com/ThomasRedstone/74bdf3be8c56dc2039940f3db835a93f

In my query log, the failure happens for this insert:
```
query failed: INSERT INTO `locations`(`id`, `country`, `longitude`, `latitude`, `postcode`) VALUES (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?), (DEFAULT, ?, ?, ?, ?) .... -- PARAMETERS: [101,"gb","-2.106246","57.146930","AB101RJ",101,"gb","-2.105923","57.146987","AB101RL",101,"gb","-2.107189","57.147136","AB101RN",101,"gb","-2.107751","57.147297","AB101RP",101,"gb","-2.109419","57.146712","AB101RQ",101,"gb","-2.109121","57.146613","AB101RR",101,"gb","-2.107771","57.145925","AB101RS",101,"gb","-2.110525","57.146567","AB101RT","gb","-2.115272","57.142566","AB101RU","gb","-2.118452","57.142412","AB101RW","gb","-2.107657","57.146491","AB101RX","gb","-2.106541","57.146032","AB101RY","gb","-2.108823","57.144074","AB101SA","gb","-2.109513","57.144996","AB101SB","gb","-2.109073","57.144810","AB101SD","gb","-2.111662","57.145506","AB101SE"
```

As you can see, for the first few row, it's trying to specify an ID to insert, but after a while, it reverts to using the DEFAULT, as it should.

If I disable the `if` statement at line 51 and 58, it all works, but does mean I'm not processing the batches in the way I want (it makes in synchronous).

**Comment by imnotjames** [comment]
I don't think this is an issue with typeorm, bit with your code.

If you disagree please reopen the issue and explain what typeorm isn't doing as expected.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
