### ISSUE TITLE
Multiple connection - entry is created in DEFAULT database always

### ISSUE THREAD

**Issue by khanakia** [typeorm/typeorm#6205]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have the below code and it's working but when I save the record it get saved in DEFAULT database always even I have mentioned the database name in the decorator as you can see in example.

**Data should save in "kookjs" db but it is saving in 'default' db**

```
import { createConnections } from "typeorm";
import {Entity, BaseEntity, PrimaryGeneratedColumn, Column} from "typeorm";

@Entity({database: 'kookjs'})
class Book extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;
}

const main = async () => {
  await createConnections([
    {
      name: "default",
      type: "postgres",
      host: 'localhost',
      port: 5432,
      username: "postgres",
      password: "root",
      database: "jeoga",
      synchronize: true,
      logging: false,
      entities: [Book] 
    },
    {
      name: "second",
      type: "mysql",
      host: 'localhost',
      port: 3306,
      username: "root",
      password: "root",
      database: "kookjs",
      synchronize: true,
      logging: false,
      entities: [Book]      
    }
  ]);

  const book = new Book()
  book.name = "Test"
  await book.save()
  console.log('Saved')
}

main()
```

**Comment by ZBAGI** [comment]
Have you tried [`Book.useConnection(...)`](https://github.com/typeorm/typeorm/blob/70938017ff17dc21e4a98512479b3645a78665e5/src/repository/BaseEntity.ts#L91) ?

**Comment by khanakia** [comment]
I just tried it works
```
  Book.useConnection(getConnection('second'))
  const book = new Book()
  book.name = "Test"
  await book.save()
```

But why do I need to specify **use connection** everytime? As I already mentioned the database name in the decorator?

```
@Entity({database: 'kookjs'})
class Book extends BaseEntity {
 ....
}
``

**Comment by ZBAGI** [comment]
`database` is just to specify database within connection not the connection itself.
You don't need to specify it every time, just set it up after `createConnections` once.
Unless you want to jump back and forward between connections, then there is no other way then switching it with `useConnection`.

**Comment by khanakia** [comment]
Ok, thanks for the help :).

**Comment by khanakia** [comment]
Do you mean by use ```Book.useConnection(getConnection('second'))``` after the createConnection function ?

**Comment by ZBAGI** [comment]
Yes, `Book.useConnection` sets static property, so you don't need to call it every time you query.
