### ISSUE TITLE
JavaScript `undefined` anchor links on https://typeorm.io

### ISSUE THREAD

**Issue by mikemaccana** [typeorm/typeorm#6207]
This is an issue with https://typeorm.io (the site). I don't know the repo where those docs are maintained, so reporting it here.

**Issue type:**

[*] bug report

**Steps to reproduce or a small repository showing the problem:**

Visit `https://typeorm.io/` and search for `many-to-many`.

Click the '#' on '# Creating a many-to-one / one-to-many relation'

![image](https://user-images.githubusercontent.com/172594/83880415-0066d300-a737-11ea-9c2d-d006b7dfc442.png)

Get `https://typeorm.io/#undefined/creating-a-many-to-one--one-to-many-relation`

Note the `undefined` above. Obviously the link doesn't work.

**Comment by imnotjames** [comment]
Interesting - looks like that's https://github.com/typeorm/typeorm.github.io/blob/master/script/component/MarkdownReader.js#L54 there

**Comment by imnotjames** [comment]
You should open this issue against the typeorm docs website repo instead
