### ISSUE TITLE
MongoDB - Like() statement not retrieving results.

### ISSUE THREAD

**Issue by oussaki** [typeorm/typeorm#6208]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm just having a simple table with a column() name:string

and i just want to perform a simple Like query on my MongoDb table

Bellow my code :

`var res = await getRepository(StoreModel).find({
            name: Like('%Djo%')
        });

        console.log(res)
        
//Tried this too
        return this.repo.find({where:{ name : Like('%Djo%')} })`

**Comment by imnotjames** [comment]
Pretty sure find operators aren't supported on mongo.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by hamza-saqib** [comment]
@oussaki faced the same issue, but i regex and it worked fine:

```
const query: any = {};

    if (search) {
      query.name = { $regex: search, $options: 'i' }; // Case-insensitive regex
    }

    const [data, total] = await this.deviceRepository.findAndCount({
      where: query,
      skip,
      take: limit,
      order: { createdAt: order },
    });
```
