### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN | connect db with docker 

### ISSUE THREAD

**Issue by bluuesz** [typeorm/typeorm#6212]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So, I have the following problem when performing the migration of my bank in a container to which it connects on my server and in another container.

![image](https://user-images.githubusercontent.com/51493181/83936360-5cfada00-a799-11ea-9576-34ad32dc8dbe.png)
where I pass my host as the name of my service in db. The connection occurs normally and without errors, but after creating the migration and trying to run it up

_Yes, I know I gave a show there but it is just for example, I have this error when running migrations every time but the connection occurs._

I have this ormconfig.json: 
```json  
  {
    "name": "development",
    "type": "postgres",
    "host": "db", 
    "port": 5432,
    "username": "root",
    "password": "dev123",
    "database": "school",
    "synchronize": true,
    "logging": false,
    "entities": [
      "/src/models/**/*.ts"
    ],
    "migrations": [
      "./src/database/migrations/*.ts"
    ],
    "cli": {
      "migrationsDir": "src/database/migrations"
    }
  },
```
this is my docker-compose: 
![image](https://user-images.githubusercontent.com/51493181/83936399-bc58ea00-a799-11ea-968f-203c721744e1.png)

The way I found him was whenever I went up to the container to get his IP and pass it to my host. But this is very annoying and does not help other people who are developing the application.

How to avoid this error, to pass only the name of my docker service on the ormconfig host?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by bluuesz** [comment]
Okay, I did it. I was not copying my ormconfig.json to my container

**Comment by trsp400** [comment]
> Okay, I did it. I was not copying my ormconfig.json to my container

You diti it in oy Dockerfile? I'm having the same problem when running migrations. I'm using typeorm, postgres and docker-compsoe

**Comment by EvandroMonteiro** [comment]
Hi guys, I'm having the same problem but I can't solve it. Can you show me your configuration?

**Comment by jpSimkins** [comment]
I'm not using `ormconfig.json` and just using `.env`. This is still happening. Really do not want to have to use 2 separate `ormconfig.json`. Is this going to be something to fix or is this something we just have to deal with? I'd rather not have to change the app just to get migrations working.

**Comment by mbuvi-dev** [comment]
# same issue

--- running a docker container i get the  error.
So i had to restart the docker container and the hosted application worked. 
Is there a permanent solution since is a container aging and the DNS disconnect
