### ISSUE TITLE
Resolver: Cannot return null for non-nullable field User.id

### ISSUE THREAD

**Issue by sptGabriel** [typeorm/typeorm#6220]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello I have a problem in my typeorm using dependency injection basically when I can't find an email everything is ok, but when the email already exists it is not returning my error:

```
if (user) {
  console.log('if');
  return { message: 'user already exists' };
}
```
i get this error on graphql:

`"message": "Cannot return null for non-nullable field User.id.",`

//// enter image description here ////

my service:

```
@Service()
export class UserService {
  constructor(
    @InjectRepository(User)
    private userRep: Repository<User>,
  ) {}

  async findOrCreate(data: Partial<User>): Promise<Partial<User> | Object> {
    let user = await this.userRep.findOne({ where: { email: data.email } });
    if (user) {
      console.log('if');
      return { message: 'user already exists' };
    }
    console.log('without if');
    data.password = await bcrypt.hash(data.password, 12);
    user = await this.userRep.save({
      ...data,
    });
    return user;
  }
}
```
my resolver:

```
  //create User Mutaton
  @Mutation(() => User)
  async register(
    @Arg('data')
    data: RegisterInput,
  ): Promise<User | Object> {
    const user = this.userService.findOrCreate(data);
    console.log(user);
    return user;
  }
```

and this is my inputtype:

```
@InputType()
export class RegisterInput {
  @Field()
  @IsEmail({}, { message: 'Invalid email' })
  email: string;

  @Field()
  @Length(1, 255)
  name: string;

  @Field()
  password: string;
}
```

error img:

![image](https://user-images.githubusercontent.com/58380116/83956994-009bc700-a83a-11ea-9b6b-6d0ea79fd4ce.png)

**Comment by DouglasGabr** [comment]
You are trying to return `{ message: 'user already exists' }` in a resolver that expects to return an `User`.
If need to either return the existing user, or throw an error and let the client handle it

**Comment by imnotjames** [comment]
This is unrelated to TypeORM

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by Neeraj3045** [comment]
Same issue occures!
