### ISSUE TITLE
Oracle driver not detecting COMPATIBLE

### ISSUE THREAD

**Issue by dpmallinger** [typeorm/typeorm#6229]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

src/driver/oracle/OracleDriver.ts:
```
     /**
         * Max length allowed by Oracle for aliases.
         * @see https://docs.oracle.com/database/121/SQLRF/sql_elements008.htm#SQLRF51129
         * > The following list of rules applies to both quoted and nonquoted identifiers unless otherwise indicated
         * > Names must be from 1 to 30 bytes long with these exceptions:
         * > [...]
         *
         * Since Oracle 12.2 (with a compatible driver/client), the limit has been set to 128.
         * @see https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/Database-Object-Names-and-Qualifiers.html
         *
         * > If COMPATIBLE is set to a value of 12.2 or higher, then names must be from 1 to 128 bytes long with these exceptions
         */
        this.maxAliasLength = 30;
```

The alias max length is hard coded to 30.  Since I am using the most up to date oracle client and I am connecting to a 19c server I should be able to have longer aliases.  I cannot find any code that is detecting the COMPATIBLE level or the connection and updating the max alias length accordingly nor can I find an override configuration option.

**Comment by wfpena** [comment]
Any update on this?

**Comment by imnotjames** [comment]
We don't support multiple versions of oracle so we instead are using the earliest supported's limitations for compatibility.

Oracle 12 has that limit.

This probably won't change unless someone wants to refactor the Oracle driver.
