### ISSUE TITLE
MongoDB: Auto generated primary ID does not return in model

### ISSUE THREAD

**Issue by shlomiassaf** [typeorm/typeorm#623]
Hi,

When creating an instance of a model with an auto generated primary id that ID will not return when querying the model.

example:
```ts
@PrimaryColumn("int", { generated: true })
  id: number;
```

or 
```ts
  @PrimaryGeneratedColumn()
  id: number;
```

**Comment by pleerock** [comment]
Hi,

since there are no tests how to use mongodb yet, refer to [tests](https://github.com/typeorm/typeorm/tree/master/test/functional/mongodb/basic).

In mongodb you should use `@ObjectIdColumn` instead of `@PrimaryColumn`:

```ts

@Entity()
export class Post {

    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    title: string;

    @Column()
    text: string;

    // @Column(() => Counters)
    // counters: Counters;

}
```

**Comment by pleerock** [comment]
I hope I answered your question.
