### ISSUE TITLE
this.subQuery is not a function when inserting to mySQL server with repository.save()

### ISSUE THREAD

**Issue by D3RPSTROYER** [typeorm/typeorm#6230]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts 
async function insertContact(req: Request, res: Response) {
    try {
        console.log(`Recieved Contact from ${req.ip}`);
        const tmp = new Contact()
        tmp.email = req.body.email;
        tmp.name = req.body.name;
        tmp.message = req.body.message
        await contactRepository.save(tmp);
        res.json({ message: "Success", data: req.body }).status(200);
    } catch (e) {
        console.log(e);
        res.json({ message: e }).status(500);
    }
} 
```
I am using type ORM with an express server to act as a backend.
whenever I use this code it returns the error `this.subQuery` is not a function. would this be a problem with the installation or an issue?

I'd be happy to provide my code if need be

**Comment by D3RPSTROYER** [comment]
`async function insertContact(req: Request, res: Response) {
    try {
        console.log(`Recieved Contact from ${req.ip}`);
        const tmp = new Contact()
        tmp.email = req.body.email;
        tmp.name = req.body.name;
        tmp.message = req.body.message
        await contactRepository.save(tmp);
        res.json({ message: "Success", data: req.body }).status(200);
    } catch (e) {
        console.log(e);
        res.json({ message: e }).status(500);
    }
}`

is the correct code

**Comment by D3RPSTROYER** [comment]
the code doesnt seem to be formatting properly, i don't know how to fix this

**Comment by D3RPSTROYER** [comment]
nvm i did a stupid

**Comment by aardvarkk** [comment]
For others in the future, I ran into this problem when I had weird interactions between TypeScript and compiled JS. I was trying to run the seeding with `ts-node`, but my TypeORM definitions were loading the entities from compiled .js files. I changed the call to `seed` to use regular `node` and continued to use my compiled .js entities and then everything seemed to work fine.

**Comment by dbrody** [comment]
For me the issue was not updating my typeorm config to include all the migration entities in the `entities:[]` config property. After I properly updated it, using `ts-node` worked just fine.

**Comment by mkonicek** [comment]
> For me the issue was not updating my typeorm config to include all the migration entities in the entities:[] config property.

This was exactly the issue. Thank you so much!

I'm using `"typeorm": "^0.2.25"`.

**Comment by Juraj-Masiar** [comment]
Those of you using `EntityManager` in a transaction, make sure to pass the Entity as first parameter, not Repository. Stupid mistake on my part, but I can't believe TypeScript didn't complained about it:
```
await entityManager.delete(WebOptionsRepository, {account_uuid: uuid});  // wrong, it needs WebOptionsEntity
```

**Comment by fadeevab** [comment]
In my case, the issue was not updating my typeorm config (`TYPEORM_ENTITIES` environment variable stored in `.env` file) to the new entities' location after changing a directory structure.

For example, if you store entities in your custom directory structure like this:
```
src/entity/user.ts
src/entity/photo.ts
```

Then you should update the config like this:
```bash
TYPEORM_ENTITIES=**/entity/*.ts
```

**Comment by scott-kicklaunch** [comment]
Seems like a pretty uninformative error message if it can mean all these things. I hope there's a thread about improving the output so threads like this can be about each problem.
