### ISSUE TITLE
How to set UNIQUE constraint on @JoinTable?

### ISSUE THREAD

**Issue by wlsdud2194** [typeorm/typeorm#6232]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I use `@JoinTable` decorater and I want to create UNIQUE constraint on two JoinTable column, `fk_question_id`, `fk_question_id`.

```javascript
@Entity()
class Question {
    ....

    @ManyToMany(type => Tag, tag => tag.questions)
    @JoinTable({
         name: 'question_tags',
         joinColumn: {
             name: 'fk_question_id',
         },
         inverseJoinColumn: {
             name: 'fk_tag_id',
         },
     })
     public tags: Tag[];
}
```

like this one
![image](https://user-images.githubusercontent.com/38432821/84118329-ce72ab00-aa6d-11ea-88f0-8caed40604f9.png)

Is there any way to resolve?

**Comment by wlsdud2194** [comment]
I created `question_tags` entity class  to resolve this issue 

like this code:
```javascript
@Entity({
  name: 'question_tags',
  synchronize: false,
})
@Unique(['fk_question_id', 'fk_tag_id'])
class QuestionTags {
...
}
```

**Comment by hsharghi** [comment]
A join table can have two columns (`fk_question_id` and `fk_tag_id`) and none of them are primary column, but an Entity should have a primary column, and it causes problem with your workaround.

**Comment by tobyhinloopen** [comment]
> an Entity should have a primary column, and it causes problem with your workaround.

@hsharghi what kind of problems? Why must there be a primary key?

**Comment by hsharghi** [comment]
> > an Entity should have a primary column, and it causes problem with your workaround.
> 
> @hsharghi what kind of problems? Why must there be a primary key?

ORM can't create tables without primary key,

```
Uncaught (in promise) MissingPrimaryColumnError: Entity "QuestionTags" does not have a primary column. 
Primary column is required to have in all your entities. 
Use @PrimaryColumn decorator to add a primary column to your entity.
```

**Comment by wlsdud2194** [comment]
@hajekj14 If I have created primary key, Can I solve this problem?
