### ISSUE TITLE
relation not work for react native

### ISSUE THREAD

**Issue by CodingByJerez** [typeorm/typeorm#6233]
**Issue type:**

[ ] `question`
[*] `bug report`
[ ] `feature request`
[ ] `documentation issue`

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[*] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**TypeORM version:**
[*] `sqlite` (react-native-sqlite-storage)

```js
@Entity()
export class Test1Entity{

    @PrimaryGeneratedColumn()
    public id!:number;

    @Column({type: 'varchar'})
    public label!:string;

    @OneToOne(() => Test2Entity, {cascade: true})
    @JoinColumn()
    public relation!:Test2Entity;

}
```

```js
@Entity()
export class Test2Entity{

    @PrimaryGeneratedColumn()
    public id!:number;

    @Column({type: 'varchar'})
    public label!:string;

}
```

```js
    try{
        const test2Entity = new Test2Entity();
        test2Entity.label = 'label2';

        const test1Entity = new Test1Entity();
        test1Entity.label = 'label1';
        test1Entity.relation = test2Entity;

        const r = await getConnection().manager.save(test1Entity);

    }catch(e){

        console.log(e); // return msg: Right-hand side of 'instanceof' is not an object

    }
```
***relation not work @JoinColumn() return error:***

```
TypeError: Right-hand side of 'instanceof' is not an object
    at Function.OrmUtils.mergeDeep (OrmUtils.js:81)
    at Subject.js:208
    at Array.reduce (<anonymous>)
    at Subject.createValueSetAndPopChangeMap (Subject.js:165)
    at SubjectExecutor.js:270
    at Array.forEach (<anonymous>)
    at SubjectExecutor.<anonymous> (SubjectExecutor.js:257)
    at step (tslib.js:141)
    at Object.next (tslib.js:122)
    at tslib.js:115
```

If anyone knows a solution to this problem thank you in advance :)
because I did not find any solution other than changing DB for realm :(

**Comment by hesyifei** [comment]
Maybe this is related to #6142?

**Comment by Thomascogez** [comment]
Hey @hesyifei, is it possible to explain how did you manage to fix that problem, I'm currently facing the same problem

**Comment by hesyifei** [comment]
> Hey @hesyifei, is it possible to explain how did you manage to fix that problem, I'm currently facing the same problem

I built a fresh copy from master and replaced the typeorm folder in node_modules with that new folder.

**Comment by Thomascogez** [comment]
thank for the answer @hesyifei , I was able to resolve this by using @next version (Be aware if your are using this version relations has some changes )

**Comment by imnotjames** [comment]
Sounds like you're all set here - I'll be closing this as having been resolved but please feel free to reach out if it's still an issue!
