### ISSUE TITLE
AbstractWriteableRepository

### ISSUE THREAD

**Issue by xenoterracide** [typeorm/typeorm#6234]
In the DDD pattern [CQRS](martinfowler.com/bliki/CQRS.html) it is possible, even likely that your read database app may not be the same as your write database app. Also, when doing reads I prefer to write custom named methods, to avoid exposing internals of typeorm to the domain model. That said I do not feel the same way about writes and would prefer to keep the signatures of typeorm. To this extent would it be possible to introduce a class in between `AbstractRepository` and `Repository` that exposes write methods only?

**Comment by imnotjames** [comment]
Not likely in the roadmap.
