### ISSUE TITLE
What is the proper type of a nullable lazy relation?

### ISSUE THREAD

**Issue by ldiqual** [typeorm/typeorm#6236]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This is a general question regarding lazy relations. I understand that they're experimental / on the verge of being deprecated or completely rewritten, however I'd like to annotate my entities as close to the current behavior to catch bugs down the road.

Let's assume the following entities:

```
@Entity()
class Company extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string
}

@Entity()
class User extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string

  @ManyToOne('Company', { nullable: true, lazy: true })
  company!: Promise<Company> | null
}
```

Let's assume that `User` might or might not belong to a `Company`. What should be the exact type of the `User.company` property?

According to my tests, I'm guessing it could be anything in:
 - `Promise<Company|undefined>`, because I'm getting `undefined` for a null relation with `User.findOne(...)`
 - `Promise<Company>|null`, because I'm getting `null` when setting `user.company = null && user.save()`
 - It's unclear whether it should be `Promise<Company>|null` or `Promise<Company|null>`, especially for assignment purposes.

My best guess at the moment is that `Promise<Company|undefined>|null` is closest to how typeorm currently works. Is that correct?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
