### ISSUE TITLE
Add support for `GENERATED ALWAYS AS` in PostgreSQL

### ISSUE THREAD

**Issue by kyranet** [typeorm/typeorm#6242]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Reference: https://www.postgresql.org/docs/12/ddl-generated-columns.html
`CREATE TABLE` reference: https://www.postgresql.org/docs/12/sql-createtable.html

Where `constraint_name` contains the following syntax:

```sql
GENERATED ALWAYS AS ( generation_expr ) STORED
```

I looked for the code that was implemented with #1377, turning out to be an `asExpression`, however, this is not used anywhere in the postgres driver.

**Comment by coyotte508** [comment]
The code for the mysql driver and the postgresql driver could be the same, if `GENERATED ALWAYS` was added in the mysql driver code.

Relevant lines:
- 1600 in AuroraDataApiQueryRunner.ts
- 1660 in MysqlQueryRunner.ts

**Comment by yunyu** [comment]
@coyotte508 Would you be able to submit your change as a PR? Thanks!

**Comment by coyotte508** [comment]
@yunyu Unfortunately there's a part missing - the synchronization, where we need to get the table info from postgres to find if the `GENERATED AS` is already there - and if not, add it.

I didn't find how to do that with the postgres language, so I gave up.

**Comment by Migushthe2nd** [comment]
This PR seems to implement this feature: https://github.com/typeorm/typeorm/pull/6469

**Comment by AlexMesser** [comment]
implemented in #6469
