### ISSUE TITLE
Avoid cordova from remove tables on pre-populated database

### ISSUE THREAD

**Issue by rickydj** [typeorm/typeorm#6244]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.9`

Hi, i have an issue using cordova-sqlite-ext, and extended version of cordova-sqlite-store plugin with the option to use prepopulated databases, i use it with an ionic 3 application because i want to maintan a pre-populted database to avoid reading files like large JSON to import parameters, list and stuff like that, i already used this method but this is slow and locks the app during update

I've tried this configuration

`  DB = {
      type: "cordova",
      database: "teleapp.db",
      location: "default",
      synchronize: true, // La base de datos ya viene precargada
      logging: [
        "error",
        "query", //Quitar en produccion
        "schema", //Quitar en produccion
     //   "warn",
     //   "info",
     //   "log",
      ],
      //logger: "simple-console",
      cache: false,
      extra: {
        androidDatabaseProvider: "system",
        androidLockWorkaround: 1,
        createFromLocation: 1 // Precarga la base de datos
      },
      entities: MODELS,
      subscribers: SUBSCRIBERS,
    };`

as you see, i have the option 'createFromLocation' which imports all data to the recently created database, and i put the'synchronize' option to false, just to avoid a reconstruction, but checking logs, i see that typeorm removes all tables from database an recreate it once it starts a recently installed version of my app, i saw this:

OPEN database: teleapp.db
OPEN database: teleapp.db - OK
query:  PRAGMA foreign_keys = OFF;
query:  BEGIN TRANSACTION
query:  SELECT 'DROP TABLE "' || name || '";' as query FROM "sqlite_master" WHERE "type" = 'table' AND "name" != 'sqlite_sequence'  <===AVOID THIS
query:  DROP TABLE "Tipo_segmento";
query:  DROP TABLE "Listas";
query:  DROP TABLE "Parametros";
query:  DROP TABLE "Direcciones";
query:  DROP TABLE "Unidades";
query:  DROP TABLE "Clientes";
query:  DROP TABLE "Solicitudes";
query:  DROP TABLE "Comentarios";
query:  DROP TABLE "Zonificacion";
query:  DROP TABLE "Servicios";
query:  DROP TABLE "Geopos";
query:  DROP TABLE "Estados";
query:  DROP TABLE "Mantenimiento";
query:  DROP TABLE "DetalleCotizacion";
query:  DROP TABLE "Elementos";
query:  DROP TABLE "Cotizaciones";
query:  DROP TABLE "documentos";
query:  DROP TABLE "Encargados";
query:  DROP TABLE "encuestas";
query:  DROP TABLE "android_metadata";
query:  COMMIT
query:  PRAGMA foreign_keys = ON;

like you see, the system just after a fresh start, removes all database tables an recreate it, how can i avoid this behavior?

Thanks for your help

**Comment by Thomascogez** [comment]
@rickydj, I think removing synchronized: true could be your solution.

**Comment by imnotjames** [comment]
Did removing that help?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
