### ISSUE TITLE
queryBuilder.getOneOrFail

### ISSUE THREAD

**Issue by xenoterracide** [typeorm/typeorm#6246]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**TypeORM version:**
```
> yarn list typeorm                        # service-graph -> feature/RS2-1053-deliverables-product-resolver $ !
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ typeorm@0.2.25
✨  Done in 1.17s.
```
**Steps to reproduce or a small repository showing the problem:**

I just want to be able to write

```ts
    this.createQueryBuilder('a')...getOneOrFail()
```
so my more complex query can behave the same way with the same exception type as a simpler query.

**Comment by imnotjames** [comment]
This seems like a good idea!  I'll take a look :D

**Comment by imnotjames** [comment]
PR ready to go.  :)  Waiting on tests.

**Comment by gabeodessru** [comment]
How come this got closed?  I'd love to see this added ❤️
