### ISSUE TITLE
Automatically register services in the container

### ISSUE THREAD

**Issue by bsitruk** [typeorm/typeorm#625]
Hi !

If I understand well, the `ConnectionManager` is automatically registered to the [`defaultContainer`](https://github.com/typeorm/typeorm/blob/95164dcbbdb8b23b7e4399d92dd13affa4f6d8ac/src/container.ts#L22) when the [`getConnectionManager`](https://github.com/typeorm/typeorm/blob/f5cf34c290a13bf538a5d44bccd11f9ec2303c84/src/index.ts#L134) method is called.

What if it was the same for [`getConnection`](https://github.com/typeorm/typeorm/blob/f5cf34c290a13bf538a5d44bccd11f9ec2303c84/src/index.ts#L170) and [`getEntityManager`](https://github.com/typeorm/typeorm/blob/f5cf34c290a13bf538a5d44bccd11f9ec2303c84/src/index.ts#L178) etc...

But I don't know when those methods are called. The idea would be to register the services to the container, when available.

So that we won't need to use the DI decorators `@OrmConnection, @EntityManager` to inject those in our services.

What do you think ?
If it's ok, I would like to make a PR, would be easier if you could provide me some more infos I'd need.

**Comment by pleerock** [comment]
Sorry I didn't get the point of this request
