### ISSUE TITLE
Relational Hooks

### ISSUE THREAD

**Issue by michaeldever** [typeorm/typeorm#6250]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi there,

A quick question, I've read the documentation but can't find an example, nor find any concrete example on search.

I have two entities:

* User
* Team

A user can belong to many teams, and a team can have many users. I would like to keep an audit log of when users are added/removed on a team.

Is there any way I can use a hook/subscriber to capture such events and use these to record the audit in another table?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
