### ISSUE TITLE
Supports autoLoadEntities option

### ISSUE THREAD

**Issue by lugavin** [typeorm/typeorm#6252]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

 The configuration file of .env or ormconfig.env supports [TYPEORM_AUTO_LOAD_ENTITIES](https://docs.nestjs.com/techniques/database#auto-load-entities) option.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
As #2358 is moving away from path based entity loading I think this won't be a likely feature built into TypeORM - mostly because.. where would it auto-load them from exactly?
