### ISSUE TITLE
How to filter relation items?

### ISSUE THREAD

**Issue by captain328** [typeorm/typeorm#6254]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24`

**Steps to reproduce or a small repository showing the problem:**

I have got an event notification service in my project. The entities look like this.
```ts
@Entity('event')
class Event {
    @Column()
    message: string;

    @Column()
    readAt: Date;

    @ManyToOne(() => User, user => user.events)
    user: User;
}

@Entity('user')
class User {
    @PrimaryGeneratedColumn()
    id: string;

    @Column()
    email: string;

    @Column()
    fullName: string;

    @OneToMany(() => Event, event => event.user)
    events: Event[];
}
```
I have to find all the users and their events but only the unread ones. (An event is regarded as unread if the `readAt` field is `null`).

This is what I have tried.
```ts
...
constructor(@InjectRepository(User) private usersRepository: Repository<User>) { }
...
const users = await this.usersRepository.createQueryBuilder('user')
   .leftJoinAndSelect('user.events', 'events')
   .where('events.readAt is null')
   .getMany();
...
```
With this query, everything works fine but there is one issue.

User objects with no-unread-events are not returned.

I expected user objects with `events: []` if there aren't any unread events.

Is it an expected behavior from the typeorm design or is there a way to achieve my goal?

Thanks in advance.

**Comment by nugz1012** [comment]
@captain328 You need to change the leftJoinAndSelect to the below and drop the where clause. See if that fixes it.

`leftJoinAndSelect('user.events', 'events', 'events.readAt is null')`

**Comment by captain328** [comment]
It works. Thank you.
