### ISSUE TITLE
Multiple Many To Many Relationship

### ISSUE THREAD

**Issue by ChrisLegaxy** [typeorm/typeorm#6260]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello everyone, I'm quite new to TypeORM. It may sound like a dumb question but bear with me.

I'm developing a backend for a video streaming system.

So I'm facing 3 many to many relationships, which I don't know how to work through it. 

The following schema:

![image](https://user-images.githubusercontent.com/34526718/84674691-7ba95f80-af55-11ea-9f6d-bcd4368c7cb3.png)

*Note*: Crew refers to Actors, Producers, Directors, Writers, etc.

Explanation:
1. A movie can have many crews, each crew will act/direct/produce on many movies
2. Each crew may have more than one role in the movie (Ex. Chris Evans can be both Writer & Actor in Avenger)
3. The crew's role varies based on movies. (Ex. Chris Evans can be Producer & Director instead in Avenger End Game)

I've tried the following:

```ts
@Entity()
export class Movie {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @ManyToMany((type) => Crew, (crew) => crew.movies)
  @JoinTable()
  crews: Crew[];

  @ManyToMany((type) => Role, (role) => role.movies)
  @JoinTable()
  roles: Role[];
}

@Entity()
export class Crew {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @ManyToMany((type) => Movie, (movie) => movie.crews)
  movies: Movie[]
}

@Entity()
export class Role {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  role: string;

  @ManyToMany((type) => Movie, (movie) => movie.roles)
  movies: Movie[];
}
```

It creates 2 tables for me instead **movie_crew** & **movie_role** 

The JSON I got from the relation above:

```ts
movie {
  title: ""
  description: "",
  crews: [],
  roles: []
}
```

What I got back doesn't seem to connect, crews & roles are different arrays and not related in anyway.

Questions:
1. Am I doing it correctly regarding my database schema?
2. Am I doing it correctly by specifying the above in my entity?

Expectations:
1. I want to be able to insert data in a way like the following:

```
| movie_id | crew_id | role_id |
|----------|---------|---------|
| 1        | 1       | 1       |
| 1        | 1       | 3       |
| 2        | 1       | 2       |
| 2        | 1       | 4       |
```

2. I want to query data in JSON like the following:

Format:
```ts
movie {
  title: ""
  description: "",
  crews: [
    {
      name: "",
      roles: [
        {
          role: "",
          // may have more fields
        },
      ]
    },
  ]
},
```

Sample: 
```ts
movie {
  title: "Avenger",
  description: "Unite",
  crews: [
    {
      name: "Chris Evans",
      roles: [
        {
          role: "Actor",
        },
        {
          role: "Writer"
        }
      ]
    },
    {
      name: "Robert Downey, Jr.",
      roles: [
        {
          role: "Actor"
        }
      ]
    }
  ]
},
movie {
  title: "Avenger End Game",
  description: "Finale",
  crews: [
    {
      name: "Chris Evans",
      role: [
        {
          role: "Producer"
        },
        {
          role: "Director"
        }
      ]
    },
    {
      name: "Robert Downey, Jr.",
      role: [
        {
          role: "Writer"
        }
      ]
    }
  ]
} 
```
Kindly look into this. I apologize for the inconvenience.

Thank you,

Chris

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
