### ISSUE TITLE
this.driver.connect is not a function when connecting to mySQL database from angular

### ISSUE THREAD

**Issue by d3rpp** [typeorm/typeorm#6261]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Clone this REPO, (happy to provide access)
[Repo](https://github.com/D3RPSTROYER/SAS)
2. Install node packages
`npm i`
3. run `ng serve` to open the dev server

4. look in the browser console and you should see this
```
TypeError: "this.driver.connect is not a function"
    connect Connection.js:109
    step tslib.es6.js:100
    verb tslib.es6.js:81
    __awaiter tslib.es6.js:74
    ZoneAwarePromise Angular
    __awaiter tslib.es6.js:70
    connect Connection.js:101
    createConnection index.js:178
    step tslib.es6.js:100
    verb tslib.es6.js:81
    __awaiter tslib.es6.js:74
    ZoneAwarePromise Angular
    __awaiter tslib.es6.js:70
    createConnection index.js:163
    init database.service.ts:47
    __awaiter tslib.es6.js:74
    ZoneAwarePromise Angular
    __awaiter tslib.es6.js:70
    init main.js:490
    AppModule app.module.ts:44
    AppModule_Factory main.js:387
    Angular 20
database.service.ts:62:14
```
`database.service.ts` runs the init function which runs the `createConnection()` function of typeorm which looks like this:
```ts
async init() {
    con = await createConnection({
      type: 'mysql',
      database: 'SAS',
      username: 'admin',
      password: '***********', // Changed for security reasons
      entities: [
        Account
      ],
      port: 3306,
      synchronize: true,
      logging: false
    }).then(connection => {
      console.log('MYSQL CONNECTION ESTABLISHED')
      accountRepository = connection.getRepository(Account);
    }).catch((e) => {
      console.log(e); // LOGGING OUT ERROR
    });
  }
```
I have the `reflect-metadata` package enables globally as it is imported in `main.ts` the entry point of the program. if there is a stupid error here that I'm not seeing, please help. ill be happy to provide any more code if need be

edit: fixed link to repo

**Comment by imnotjames** [comment]
You cannot connect to MySQL via the browser.  This is not possible at this time as there are no MySQL NPM packages that work in the browser's context.  This is a limitation of browsers & the implemented security model - not TypeORM.

See https://github.com/typeorm/typeorm/blob/650b71665bdf197b1b216f39456cf8aeef4149ed/src/platform/BrowserDisabledDriversDummy.template#L62
