### ISSUE TITLE
find with relations returns soft-deleted entities

### ISSUE THREAD

**Issue by Ollie1700** [typeorm/typeorm#6265]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Apologies for opening an issue for this, it seems like I am probably missing something very obvious but essentially the issue is that soft-deleted entities are being returned as part of relations.

Example:

Say we have "User" and "Post" - user has many posts

1. `const userWithPosts = await userRepo.findOne(1, { relations: [ 'posts' ] })`
2. `userWithPosts.posts` will contain all posts, even ones that have been deleted

Am I missing something obvious here? This functionality works as expected when not using relations (e.g. in the above example, `postRepo.find()` would only return non-deleted items) but when using relations I am running into this issue.

**Comment by Ollie1700** [comment]
This behaviour is still a blocker for me at the moment. I'm wondering if anyone knows if it is intended, and if so what is the workaround? Or if it is known to be a bug I can look to make a PR for this one if someone can point me in the right direction.

Thanks again, I know your team must be very busy.

**Comment by andreimc** [comment]
@Ollie1700 we are seeing the same thing

**Comment by yorickdevries** [comment]
Same as  #5838

**Comment by chenfanggm** [comment]
Same here.

**Comment by nshCore** [comment]
@Ollie1700 is the field you use the @DeleteDateColumn() named 'deletedAt'?

Anything else wont work.

**Comment by chenfanggm** [comment]
> @Ollie1700 @chenfanggm is the field you use the @DeleteDateColumn() named 'deletedAt'?
> 
> Anything else wont work.

Yea, I have named the @DeleteDateColumn() as `deletedAt`.
`@ObjectType()
export abstract class BaseEntity extends TypeormBaseEntity {
  @Field()
  @CreateDateColumn({ type: 'timestamp with time zone' })
  createdAt: Date;

  @Field()
  @UpdateDateColumn({ type: 'timestamp with time zone' })
  updatedAt: Date;

  @Field()
  @DeleteDateColumn({ type: 'timestamp with time zone' })
  deletedAt: Date;
}`

`
const post = await Post.findOne(id, {
    relations: [
      'creator',
      'category',
      'tags',
      'threads',
      'threads.creator',
      'threads.replies',
      'threads.replies.creator',
      'threads.replies.replyToUser',
    ],
    order: {
      updatedAt: 'DESC',
    },
  });
`

Even my `thead` is softDeleted, but it still come back as result for the query.

Thanks.

**Comment by jgaudet** [comment]
Wouldn't a simpler workaround to just directly filter the deleted relations directly after fetching rather than introducing this complicated workaround? Ideally this bug will be fixed at some point and the number of deleted items will probably not be huge.

**Comment by marcinja** [comment]
I'm seeing a similar issue and also am using a column named `deletedAt

**Comment by riskidan** [comment]
Seeing the same problem

**Comment by KevinArce98** [comment]
Same problem, some solution?

**Comment by nebkat** [comment]
This is simply because the functionality is not implemented. The code that normally adds the filter for deleted items is here, and it does so for the main entity in the query only, not for the relations:

https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/query-builder/QueryBuilder.ts#L663-L672

It makes sense to filter out deleted One-to-Many/Many-to-Many relations, but it might not be the expected default behavior for a One-to-One/Many-to-One relation. If a user's "profile" has been deleted, you might still expect the relation to be loaded, especially if `user.profile` can't be `null`.

If someone wants to implement an option for this you can send in a PR and link to this issue, it shouldn't be too difficult. Start with `SelectQueryBuilder` and `QueryBuilder`.

---

BTW, please avoid commenting just to say you have the problem. The original issue has described what is wrong, unless you have something useful to add just 👍 it.

**Comment by klaaz0r** [comment]
What is the status of this? Seems like a fundamental feature to have would like to work on it but is anyone already fixing this?

**Comment by nebkat** [comment]
I am not aware of anyone working on this, you can submit a PR if you want.

**Comment by jdniels** [comment]
Seeing the same problem

**Comment by lorenzosignoretti** [comment]
I know the issue has been closed, but I think the behaviour has remained the same even in 0.2.31

**Comment by matgott** [comment]
I'm having the same issue...I have created_at, updated_at and deleted_at columns on my entities, but the problem still exists.

**Comment by klaaz0r** [comment]
@lorenzosignoretti exactly the same ting happening for me, it can be related with the skip/limit I also include maybe?

**Comment by mossa-Sammer** [comment]
any update on this issue??

**Comment by mossa-Sammer** [comment]
it's not working neither using find options nor query builder, it's frustrating that I need to write a query with 6 joins manually :(

**Comment by mossa-Sammer** [comment]
worked for me when using query builder, and placing the withDeleted fucntion at the top like this
```
orderRepo
      .createQueryBuilder('order')
      .withDeleted()
      .innerJoin('order.kitchen', 'kitchen')
      .innerJoin('order.user', 'user')
      .innerJoin('order.orderStatus', 'orderStatus')
      .leftJoin('order.orderStatusLogs', 'orderStatusLogs')
      .innerJoinAndSelect('order.orderItems', 'orderItems')
      .leftJoinAndSelect('orderItems.foodListing', 'foodListing')
      .where('order.order_id = :orderId', { orderId })
      .getOne();
      ```

**Comment by xerxes235** [comment]
in most cases, you have to use **innerJoinAndSelect** instead of **leftJoinAndSelect**.

**Comment by tuananhlai** [comment]
Is there any workaround for this issue? It seems weird that such a basic feature is missing.

**Comment by EdsonRCJ** [comment]
Is there any update for this issue ? I'm facing the same.

**Comment by kevin4dhd** [comment]
any solution? :/

**Comment by osellas** [comment]
Same here 😬

**Comment by amiralammohawk** [comment]
same
