### ISSUE TITLE
Snyk finding within cli-highlight dependency

### ISSUE THREAD

**Issue by ionicpanda** [typeorm/typeorm#6267]
**Issue type:**
[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Snyk is reporting that within cli-highlight's dependency tree there is an arbitrary code execution finding. 

https://snyk.io/vuln/SNYK-JS-THENIFY-571690

I haven't taken a deeper dive to see if TypeORM is vulnerable via the dependency chain. I just thought it would be a good idea to get an issue out for more people to take a look at the dependency finding.

**Comment by ionicpanda** [comment]
The indirect dependency thenify has removed the eval function within the code and has a new npm package version 3.3.1. Upgrading thenify to 3.3.1 should take care of any chance this vulnerability could affect your project.

**Comment by imnotjames** [comment]
We updated depends as of the latest release.

Let me know if this is still an issue as of 0.2.27
