### ISSUE TITLE
import of other entities is undefined during typeorm commands

### ISSUE THREAD

**Issue by aounleonardo** [typeorm/typeorm#6271]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.24`

**Steps to reproduce or a small repository showing the problem:**
_NB: I am using TypeGraphQL in combination with TypeORM, that shouldn't be an issue but only to explain the other decorators._
I have an entity file node.js that exports a function `node` which creates an abstract class that all of my entities will extend with a given parameter:
```ts
// in node.ts
import { Field, ID, InterfaceType, ObjectType } from "type-graphql";
import { BaseEntity, BeforeInsert, Column, Index, PrimaryColumn } from "typeorm";
import { generateIdOfNodeType, getNodeTypeFromId } from "../utils/ids";

@InterfaceType({ isAbstract: true })
export abstract class Node extends BaseEntity {
    @Field((type) => ID)
    id: string;

    @Field()
    createdAt: Date;

    @Field()
    updatedAt: Date;

    public static async findOne(id: any): Promise<Node> {
        const NodeType = getNodeTypeFromId(id);
        return await NodeType.findOne(id);
    }

    public static compare = (first: Node, second: Node) => {
        return first.id.localeCompare(second.id);
    };
}

export function node(schemaName: string) {
    @ObjectType({ isAbstract: true })
    abstract class Ent extends BaseEntity implements Node {
        @PrimaryColumn()
        id: string;

        @Index()
        @Column({ type: "timestamp with time zone", default: () => "CURRENT_TIMESTAMP" })
        createdAt: Date;

        @Column({ type: "timestamp with time zone", default: () => "CURRENT_TIMESTAMP" })
        updatedAt: Date;

        @BeforeInsert()
        private generateId() {
            this.id = generateIdOfNodeType(schemaName);
        }

        /* other static and instance methods */
    }
    return Ent;
}
```

```ts
// in some entity like group.ts
import { Field, ObjectType } from "type-graphql";
import { Column, Entity, Index, JoinTable, ManyToMany } from "typeorm";
import { node, Node } from "./node";
import { Relationship } from "./relationship";
import { User } from "./user";

console.log({Node, node})

@ObjectType({ implements: Node })
@Entity()
export class Group extends node("Group") {
    @Index()
    @Column()
    targetId: string;

    @Field({ nullable: true })
    @Column({ nullable: true })
    name: string;

    @ManyToMany(
        (type) => User,
        (user) => user.groups,
        { cascade: true, onDelete: "CASCADE" },
    )
    @JoinTable()
    members: User[];

    /* static and instance methods */
}
```

If I run the server with ts-node everything works fine and I don't have any Typescript errors. Also, the console.log({Node, node}) prints non-null values.

However, if I try running anything with the typeorm cli, in any of these methods:
- `NODE_ENV=production ./node_modules/.bin/ts-node ./node_modules/.bin/typeorm schema:log`
- `NODE_ENV=production ./node_modules/.bin/ts-node ./node_modules/typeorm/cli.js schema:log`
- `tsc && NODE_ENV=production ./node_modules/.bin/typeorm schema:log`

I get an error that node is not a function, and the print statement shows me undefined for both Node and node. I tried importing utility functions from other directories at the root level and they existed, but unfortunately not in the case of other entities. 

I can't find why imports are behaving differently if I run the code through an entry point than if I do it through the typeorm cli?

**Comment by imnotjames** [comment]
Is this still an issue?
