### ISSUE TITLE
[Question] Creating identifying one-to-one relationships

### ISSUE THREAD

**Issue by Dr-Phone** [typeorm/typeorm#6275]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
In the examples, one-to-one relationship between Profile and User entities uses a separate foreign key.  However, I want to use the primary key of the User entity as the foreign key. I tried the following: 

```ts
import {Entity, PrimaryGeneratedColumn, Column, OneToOne, JoinColumn} from "typeorm";

@Entity()
export class Profile {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    gender: string;

    @Column()
    photo: string;

}


@Entity()
export class User {

    @PrimaryColumn()
    id: number;

    @Column()
    name: string;

    @OneToOne(type => Profile)
    @JoinColumn( {"name": "id"} )
    profile: Profile;   // don't want to create separate profileId

}
```

but this gives the error: `QueryFailedError: column "id" appears twice in unique constraint`

any ideas about how to fix it would be appreciated.

**Comment by imnotjames** [comment]
Hi there!  For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
