### ISSUE TITLE
Mysql/Mariadb database service shutdown when connection refused or typeorm internal errors on Amazon EC2 instance

### ISSUE THREAD

**Issue by Ibcs16** [typeorm/typeorm#6277]
**Issue type:**

[ ] question
[X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

my ormconfig is configured as follow:

```
module.exports = {
  "synchronize": false,
  "type": process.env.DB_TYPE,
  "host": process.env.DB_MYSQL_HOST,
  "port": process.env.DB_MYSQL_PORT,
  "username": process.env.DB_MYSQL_USER,
  "password": process.env.DB_MYSQL_PWD,
  "database": process.env.DB_MYSQL_NAME,
  "entities": [
    `${process.env.DB_ENTITIES_PATH}`
  ],
  "migrations": [
    `${process.env.DB_MIGRATIONS_PATH}`
  ],
  "cli": {
    "migrationsDir": "./src/shared/infra/typeorm/migrations"
  },
}
```

When I try to run migrations with wrong credentials, I get ECONNREFUSED and immediately mariadb server stops working, having to be restarted again. Same goes for internal errors  like ER_DUPLICATE_FIELDNAME. 
The thing is, it only happened with me when using an EC2 Amazon instance, but everything works just fine with docker containerized server like in DigitalOcean.
What could that be, and any possible solutions?

**Comment by imnotjames** [comment]
Sounds like a problem with your environment, not typeorm.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
