### ISSUE TITLE
Many-to-one on primary key

### ISSUE THREAD

**Issue by Zendor18** [typeorm/typeorm#6278]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have two entities:
```typescript
@Entity('cast')
export class Cat {
  @PrimaryGeneratedColumn()
  cat_id: number;

  @JoinColumn({ name: 'owner_id' })
  @ManyToOne(() => Owner, (owner) => owner.owner_id)
  owner_id: Owner;
}

@Entity('owners')
export class Owner {
  @PrimaryColumn('uuid')
  owner_id: string;

  @Column()
  description: string;

  @Column()
  datetime: Date;
}

```

How can i add **OneToMany** decorator properly, so i can have result like this
(list of **Cat** entities which have **owner_id** = **owner.owner_id**):

```javascript
const response = await ownerRepo.find(...);

response // 
[
{ 
  owner_id: 'aaa',
  description: 'hello',
  datetime: 'iso string',
  cats: [
    {
      cat_id: 1,
      owner_id: 'aaa',
    },
    {
      cat_id: 2,
      owner_id: 'aaa',
    },
  ]
}
]
```

**Comment by imnotjames** [comment]
You would define a `OneToMany` on the owner field & when querying for the owner you pass the `relation` options as described [in the documentation on these kinds of relationships](https://github.com/typeorm/typeorm/blob/master/docs/many-to-one-one-to-many-relations.md)

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
