### ISSUE TITLE
Time Column result error

### ISSUE THREAD

**Issue by MerlChen** [typeorm/typeorm#6279]
**Issue type:**

[×] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[×] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[×] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

## `Question`
> When i insert a records into database. after that i query this records,I found this record time column is differece to database records.

### My column setting
```
  // 创建时间
  @CreateDateColumn()
  createTime: string;

  // 最后一次修改时间
  @UpdateDateColumn()
  updateTime: string;
```

### Database records
![image](https://user-images.githubusercontent.com/23546308/85086672-dd93ee80-b20d-11ea-98d9-c0da292b1dd3.png)

### ormconfig
![image](https://user-images.githubusercontent.com/23546308/85086883-85a9b780-b20e-11ea-82d8-2dca4d658676.png)

### Query result
![image](https://user-images.githubusercontent.com/23546308/85086529-724a1c80-b20d-11ea-9644-615d039070ec.png)

## Hope to
> I want to know how to fix that.

## Thanks for typeorm team provide a good typescript orm to us. I'm a chinese developer,english is not very well.I holp you can understand me. Thanks again. Mua~

**Comment by imnotjames** [comment]
The values in the database look to be UTC+8 & the times fetched are supposed to be UTC.

You've actually set this by defining the `timezone` in the connection options.  If you want exactly what's in the database, define `Z` or `local` or omit the timezone entirely.

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
