### ISSUE TITLE
Problens with migrations in Sap hana.

### ISSUE THREAD

**Issue by Eduardo555** [typeorm/typeorm#6282]
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `Sap Hana`
**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello, I'm having trouble running a new migration to the sap hana database, my migration remains empty and I run the run command, and I get an error

`MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".
`
the typeorm support migrations to sap hana?

**Comment by Carnevali** [comment]
> **Issue type:**
> 
> [ ] question
> [ ] bug report
> [x ] feature request
> [ ] documentation issue
> 
> **Database system/driver:**
> 
> [ ] `cordova`
> [ ] `mongodb`
> [ ] `mssql`
> [ ] `mysql` / `mariadb`
> [ ] `oracle`
> [ ] `postgres`
> [ ] `cockroachdb`
> [ ] `sqlite`
> [ ] `sqljs`
> [ ] `react-native`
> [ ] `expo`
> [x] `Sap Hana`
> **TypeORM version:**
> 
> [x ] `latest`
> [ ] `@next`
> [ ] `0.x.x` (or put your version here)
> 
> Hello, I'm having trouble running a new migration to the sap hana database, my migration remains empty and I run the run command, and I get an error
> 
> `MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg". `
> the typeorm support migrations to sap hana?

I had the same problem with MySQL. Did you define "type" in your ormconfig.json file?

**Comment by Eduardo555** [comment]
hey, it really works, but now i have another problem, when i perform the migrations i get relationship errors in entities with many to many.

```
   // Ligacoes.
    @ManyToMany(type => Usuario)
    @JoinTable()
    envolvidos: Usuario[];
```

This is an example of my code, it should generate a table with the name 'Involved', in this case many to many between the table 'Users' and 'Timesheets', do I need to change something in the entities to work in this mode?

Detail, if I use the synchronize function, I am successful.

**Comment by Carnevali** [comment]
Hey Eduardo. I'm glad of having helped you. As far as I noticed your last error, sounds weird it works with synchronization flag activated only. Have a look into this link and see if it will help you: https://github.com/typeorm/typeorm/issues/2652
In this case, I realized that the guy created the relationship in both entities. Do you have the same scenario?

For example:

import { Entity, Column, ManyToMany, JoinColumn } from "typeorm";
import { EntityBase } from "./Abstract/EntityBase";
import { Permission } from "./Permission";

@Entity({ name: "role" })
export class Role extends EntityBase {
	@Column({ name: "name", type: "varchar", length: 20, nullable: false })
	name: string;

	@Column({ name: "description", type: "varchar", length: 50, nullable: true })
	description: string;

	@ManyToMany(type => Permission, permissions => permissions.roles)
	@JoinColumn()
	permissions: Permission[];
}

import { Entity, Column, ManyToMany } from "typeorm";
import { EntityBase } from "./Abstract/EntityBase";
import { Role } from "./Role";

@Entity({ name: "permission" })
export class Permission extends EntityBase {
	@Column({ name: "name", type: "varchar", length: 20, nullable: false })
	name: string;
	@Column({ name: "description", type: "varchar", length: 50, nullable: true })
	description: string;
	@ManyToMany(type => Role, roles => roles.permissions)
	roles: Role[];
}

I didn't see your entire code, however, for your scenario, the Users entity should be Permission and the Timesheets entity should be Role (or vice-versa).

I hope I've been clear.

**Comment by imnotjames** [comment]
Looks like much of this has been resolved.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
