### ISSUE TITLE
Add many to many relation failing

### ISSUE THREAD

**Issue by cvh23** [typeorm/typeorm#6283]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.25`

**Steps to reproduce or a small repository showing the problem:**

I've exactly the problem, which is described here:
:point_right: https://stackoverflow.com/questions/61545689/add-many-to-many-relation-failing :point_left:

Any solutions or hints?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
