### ISSUE TITLE
support .cjs extension for orm config

### ISSUE THREAD

**Issue by dpickett** [typeorm/typeorm#6284]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I will have a pull request forthcoming for this. Need the issue # to write a test

**Comment by imnotjames** [comment]
Seems like this was merged in and we're good to close it, yeah?

**Comment by dpickett** [comment]
yes confirmed. Thanks! I'm closing this now.
