### ISSUE TITLE
Question. Get minimum column value from related entity

### ISSUE THREAD

**Issue by 2rv** [typeorm/typeorm#6286]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello. Please, help me. I cant find information about how do this. 
I have got this code. It load all products with all relations. One of relations is product item. In product item entity I have got price column.

How I can get minimal product item price without get in my response array of product items?

```
const { skip, take } = pagination;

    const query = this.createQueryBuilder('product');

    query.where('product.shop = :id AND product.blocked = FALSE', {
      id: shop.id,
    });

    if (skip) {
      query.offset(Number(skip));
    }

    if (take) {
      query.limit(Number(take));
    }

    query.leftJoin('product.info', 'info');
    query.leftJoin('product.avatar', 'avatar');
    query.leftJoin('product.image', 'image');

    // load product items
    query.leftJoin('product.productItem', 'item');

    query.select([
      'product.id',
      'product.path',
      'info.name',
      'info.description',
      'info.info',
      'info.lang',
      'avatar.path',
      'avatar.type',
      'image.type',
      'image.path',

      'item.price'
    ]);

    const [list, amount] = await query.getManyAndCount();
```

Now i have got:
```
"productItem": [
        {
          "price": 1000
        },
        {
          "price": 500
        },
        {
          "price": 300
        },
        {
          "price": 2000
        },
        {
          "price": 3000
        }
      ]
    },
```

But I need:

```
"minItemPrice: 300
```

**Comment by 2rv** [comment]
help

**Comment by UnsolvedCypher** [comment]
See the answer here: https://stackoverflow.com/questions/54250232/typeorm-select-max-with-specific-column

**Comment by 2rv** [comment]
> See the answer here: https://stackoverflow.com/questions/54250232/typeorm-select-max-with-specific-column

In example used case without join column. This is not what I need at all

**Comment by imnotjames** [comment]
Hi there!  For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
