### ISSUE TITLE
Complement shim.js : Is there any problem adding @Unique to shim ?

### ISSUE THREAD

**Issue by Overfacto** [typeorm/typeorm#6288]
I've error on Angular 9 with TypeORM shim, and it is resolved with manually @Unique empty patch. 

If when I add @Unique and something decorator empty function, will this be problem?

**Issue type:**
[x] feature request

**TypeORM version:**
[x] `latest`

**Comment by imnotjames** [comment]
You'll need to elaborate on your problem and what feature you're looking for - I'm not sure I understand what you'd like as a new behavior.

**Comment by imnotjames** [comment]
Duplicate of #5920
