### ISSUE TITLE
Using complex conditions for queries

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#629]
Hello!

I've naively tried to use this code today, but it appears not-working:

```typescript
repository.count({
  user: user.id,
  createdAt: {
    '>=': startDate.toString(),
    '<=': endDate.toString()
  }
});
```

I'm trying to count number of entities created between two dates.

Is it possible to use "complex" conditions with TypeORM, or do I need to use QueryBuilder for this?

Are you planning to introduce such functionality?

Thank you!

**Comment by pleerock** [comment]
SQL is very dynamic and its hard to cover all such "complex" features. Maybe we will have it in the deep future, we just need a good design proposal and cover all those "complex conditions". For now use `QueryBuilder`.

**Comment by pleerock** [comment]
I'll close it for now. We'll need a new issue with deep proposal on what conditions should be covered and how.
