### ISSUE TITLE
Are mapped hstore values supported?

### ISSUE THREAD

**Issue by axos88** [typeorm/typeorm#6290]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Can TypeORM support mapped hstore types? Such as something along the lines:

```
  export enum BalanceTypes {
    CREDIT = 'credit',
    BONUS = 'bonus'
  }

@Entity()
export class UserProfile extends BaseEntity {
  [...]
  
  @Column('hstore', { default: 'credit => 0, bonus => 0', hstoreType: 'object', nullable: false })
  balances: { [key in BalanceTypes]: number }

  }
```

Not that the balances expects a structure with values deserialized to numbers, not a strings, but if only strings are possible currently, that would be a step forward as well.

**Comment by imnotjames** [comment]
Only json & JSONB is supported.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
