### ISSUE TITLE
Variable reference == for models

### ISSUE THREAD

**Issue by azukaar** [typeorm/typeorm#6291]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

The '===' comparison used for models matching seems to be causing a lot of issues, one of them that wasted so much time to find out, is TS' indirection that seems to loose some reference... I honestly have no idea how it is possible, but basically this work perfectly:

```ts 
/* istanbul ignore next */
export const getDatabase = async (): Promise<Connection> => {
  try {
    const tryExisting = getConnectionManager().get('default');
    if (!isUndef(tryExisting) && tryExisting.isConnected) return tryExisting;
  } catch (e) {}

  try {
    return await createConnection({
      ...config.get('Database'),
      type: 'postgres',
      synchronize: true,
      ssl: {
        rejectUnauthorized: false,
      },
      logging: false,
      entities: [Profile, Account],
      migrations: [__dirname + '/src/migration/**/*.ts'],
      subscribers: [__dirname + '/src/subscriber/**/*.ts'],
    });
  } catch (e) {
    logger.fatal(e);
    throw new AppError(ERDB001);
  }
};
```

Whereas this version gives me the error `Entity metadata for Account#user was not found. Check if you specified a correct entity object and if it's connected in the connection options.` when trying to link Account to User.

```ts 

const entities = [Profile, Account];

/* istanbul ignore next */
export const getDatabase = async (): Promise<Connection> => {
  try {
    const tryExisting = getConnectionManager().get('default');
    if (!isUndef(tryExisting) && tryExisting.isConnected) return tryExisting;
  } catch (e) {}

  try {
    return await createConnection({
      ...config.get('Database'),
      type: 'postgres',
      synchronize: true,
      ssl: {
        rejectUnauthorized: false,
      },
      logging: false,
      entities,
      migrations: [__dirname + '/src/migration/**/*.ts'],
      subscribers: [__dirname + '/src/subscriber/**/*.ts'],
    });
  } catch (e) {
    logger.fatal(e);
    throw new AppError(ERDB001);
  }
};
```

**Comment by imnotjames** [comment]
Do you have a repo that reproduces this issue?

**Comment by imnotjames** [comment]
Without much info to go on for reproducing, I'll be closing it out.  Looks related to #5676
