### ISSUE TITLE
OracleDB 11 not compatible with FETCH

### ISSUE THREAD

**Issue by joselicht90** [typeorm/typeorm#6296]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1.Install oracle database 11.2

2. Create a query using Entity.findOne()

3.The query that is created contains FETCH instruction wich is not supported until oracle database 12

Is there anyway to tell typeorm that the version or oracle db is 11 so it build the query in another way?

**Comment by imnotjames** [comment]
TypeORM only supports Oracle 12+ at this time.  I've tested this a few different ways, there's a lot that's not working with oracle 11
