### ISSUE TITLE
Cannot set property 'exports' of undefined using Sqj.js

### ISSUE THREAD

**Issue by amura11** [typeorm/typeorm#6297]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm trying to get TypeORM working with Sql.js 1.3.0 inside Electron as part of the renderer but I'm running into an error I don't know how to handle. It looks like Sql.js is loading properly but an error is being thrown from `SqljsDriver`: "TypeError: Cannot set property 'exports' of undefined". I'm not sure if this is a bug in TypeORM or just a configuration issue.

My setup is as follows:

**WebPack Config**
```
module.exports = {
    entry: {main: './main.ts'},
    output: {/*Removed for brevity*/},
    target: 'electron-renderer',
    module: {/*Removed for brevity*/},
    plugins: [
        /*Other plugins removed for brevity*/
        new Webpack.NormalModuleReplacementPlugin(/typeorm$/, function (result) {
            result.request = result.request.replace(/typeorm/, "typeorm/browser");
        }),
        new Webpack.ProvidePlugin({
            'window.SQL': 'sql.js/dist/sql-wasm.js'
        }),
        new CopyPlguin({
            patterns: [
                {from: './node_modules/sql.js/dist/sql-wasm.wasm'}
            ]
        })
    ]
}
```

**Main File**

```
const connectionConfig: ConnectionOptions = {
    type: "sqljs",
    location: "test.db",
    entities: [MyEntity],
    logging: ['query', 'schema']
};

async function Main() {
    const connection: Connection = await createConnection(connectionConfig);
}

Main().catch(console.error);
```

**Comment by amura11** [comment]
After investigating this a little more it appears this is an issue with SqlJs. I've opened a case to them to find out if it's actually a bug or just a configuration issue on my part.

**Comment by dominic-simplan** [comment]
And here is the according sql.js ticket: https://github.com/sql-js/sql.js/issues/406
