### ISSUE TITLE
Decorators erroring out generating migrations

### ISSUE THREAD

**Issue by Asduveneck** [typeorm/typeorm#6298]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

  When I run a migration, I encounter the error: `Experimental support for decorators is a feature that is subject to change... Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.` And then the migrations are not generated.

In my `tsconfig.db.json`  compiler options, I have set `emitDecoratorMetadata` and `experimentalDecorators` to be `true`, and my `lib` includes `es2017` and `ES6`. 

Wthin my entity file I wish to migrate, I encounter errors with the class and every single column:

```ts
@Entity()
class Company extends Details {
  @PrimaryGeneratedColumn()
  companyId: number;

  @OneToMany(
    type => Person,
    person => person.company,
  )
  persons: Person[];

  @OneToMany(
    type => Job,
    job => job.company,
  )
  jobs: Job[];

  @Column({ type: 'varchar', length: 100 })
  name: string;

  @Column({ nullable: true })
  careerUrl: string;

  @Column({ type: 'json', nullable: true })
  otherUrl: any; // {name: url: }
}

export default Company;

```

As a heads up, I generated a migration as `npm run migrate:generate Company`, where that command is defined as:

```js
"migrate:generate": "ts-node ./node_modules/typeorm/cli.js migration:generate --config ./ormconfig.ts --connection  --name",
```

I'm new to TypeORM and setting up projects in general, so I'm not sure where else to go or what else to include. I tried joining the [slack group for TypeORM](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md) but the link is broken. 

I've looked into:
  * the docs within github. 
  * [Github 5103](https://github.com/typeorm/typeorm/issues/5103)
  * [StackOverflow: Experimental Decorators warning](https://stackoverflow.com/questions/38271273/experimental-decorators-warning-in-typescript-compilation) and I adjusted my VSCode setting there too, so it could be a directory structure

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by Asduveneck** [comment]
I decided to ask on S.O. because this may in fact be a configuration issue. I noticed that when I have one class per file, one-to-many and many-to-one relationships create a circular dependency...

**Comment by imnotjames** [comment]
This seems like an issue with your environment, not a bug in typeorm itself.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
