### ISSUE TITLE
Joining entities while querying with a custom join table

### ISSUE THREAD

**Issue by TomDolidon** [typeorm/typeorm#6303]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.24` 

So basically i have two table with a custom join table between :

 ```
@Entity()
export class A {
 
  @Column()
  column1A: string;

  @Column()
  column2A: string;

  ...

}


 ```

 ```
@Entity()
export class B {
 
  @Column()
  column1B: string;

  @Column()
  column2B: string;

   ...

}
 ```

 ```
@Entity()
export class A_B {

    @ManyToOne(type => A)
    public a: A;

    @ManyToOne(type => B)
    public b: B;
 
   @Column()
   column1AB: string

   ...

}
 ```

Is it possible to have an outpout like this using query builder or find (Array of A each containing array of B) ?

 ```
[
  {
    column1A : ... ,
    column2A : ... ,
    b : [
      {
        column1B : ... ,
        column2B : ... ,
        ...
      },
      {
      ...
      }
    ]
  },
  { ... },
   ...
]
 ```

**Comment by imnotjames** [comment]
You need to set up a many to many and set the join table as `A_B`>

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
