### ISSUE TITLE
Could transformer function get the current row as an argument?

### ISSUE THREAD

**Issue by fatihky** [typeorm/typeorm#6305]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Sometimes our value transformers fail and I can't see failed row. May the `transformer.from` function get the current row as third argument? What do you think about this?

**Comment by imnotjames** [comment]
Duplicate of #3978
