### ISSUE TITLE
Environment variable to set SSL cerificate for CLI 

### ISSUE THREAD

**Issue by can-kayacan** [typeorm/typeorm#6307]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi, thank you for all the great efforts.

I have a qusetion. We are using the typeorm migrations through CLI tool. We need to set the SSL certificate for the CLI. Is there an environment variable to set it? All I could find was this:
```
TYPEORM_DRIVER_EXTRA='{"ssl":true}'
```

I know that it is doable inside Javascript with a config like this, however I would like to keep our command line tool.
```
export const typeOrmConfig: PostgresConnectionOptions = {
  type: 'postgres',
  url: '...',
  ssl: !isDevelopment()
    ? {
        rejectUnauthorized: true,
        ca: fs
          .readFileSync(join(os.homedir(), '/.aws/rds.pem'))
          .toString(),
      }
    : null,
};
```

**Comment by can-kayacan** [comment]
OK, it seems like TYPEORM_DRIVER_EXTRA is also accepting the ssl json. 
```
TYPEORM_DRIVER_EXTRA='{"ssl": { rejectUnauthorized: true, ca: "..." }}'
```

Problem should be solved :)

**Comment by chriszrc** [comment]
@can-kayacan Yes, typeorm is accepting the json, but it's not letting me read the ssl cert from a file with ` cert: fs.readFileSync("<the cert path>")`. I have to actually embed the cert string. Which is error prone, since copy/paste will blow away the required newlines. Any way to make this work with reading the cert contents from a file?

**Comment by HaaLeo** [comment]
I found a workaround using nodejs' [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#node_extra_ca_certsfile).
When you set this variable you can just set `ssl: true` in your typeorm config and you neither have to read the ca during runtime nor pass the ca itself in the environment variable.
