### ISSUE TITLE
Two many to one relationships that share a primary foreign key on the same entity: Only one column created

### ISSUE THREAD

**Issue by iruizmar** [typeorm/typeorm#6310]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Having two different entities whose primary key is a foreign key to the same different entity (BasicUser and Merchant have a primary foreign key to User), if you have a fourth entity (Transaction) which has one ManyToOne relationships to each of the aforementioned entities, only one column is created.

The two entities which share primary foreign keys are defined like this:

```typescript
@Entity()
export class BasicUser {

  @OneToOne(() => User, {primary: true, cascade: ['insert', 'update']})
  @JoinColumn()
  user: User;

  @Column({default: false})
  emailValidated: boolean;

  @Column({unique: true})
  document: string;

  @Column({type: 'enum', enum: DocumentTypeDto, default: DocumentTypeDto.dni})
  documentType: string;

  @Column({unique: true, nullable: true})
  card: string;

  @Column({default: 0})
  balance: number;

  @OneToMany(() => Transaction, transaction => transaction.client)
  transactions: Transaction[];
}
```

and

```typescript
@Entity()
export class Merchant {
  @OneToOne(() => User, {primary: true, cascade: ['insert', 'update']})
  @JoinColumn()
  user: User;

  @ManyToOne(() => Shop)
  shop: Shop

  @OneToMany(() => Transaction, transaction => transaction.merchant)
  transactions: Transaction[];
}
```
and the entity which has the ManyToOne relationships is defined like:

```typescript
@Entity()
export class Transaction {
  @PrimaryColumn('uuid')
  id: string;

  @Column()
  amount: number;

  @Column()
  discount: number;

  @ManyToOne(() => Shop, shop => shop.id)
  shop: Shop;

  @ManyToOne(() => BasicUser, basicUser => basicUser.user)
  client: BasicUser;

  @ManyToOne(() => Merchant, merchant => merchant.user)
  merchant: Merchant;
}
```

As you can see in the screenshot, only merchant's relationship is created on the generated table:
![imagen](https://user-images.githubusercontent.com/11753209/85751952-4813c580-b70b-11ea-90ce-874bf9471234.png)

**Comment by imnotjames** [comment]
You're missing the return relationship in basic user. 

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by iruizmar** [comment]
What do you mean? Last Basic User's property isn't it?

`  @OneToMany(() => Transaction, transaction => transaction.client)
  transactions: Transaction[];`

**Comment by imnotjames** [comment]
What I meant was: the inverse relationship defined in the Transaction model for `client` is incorrect and might be causing issues here.

Current:
```
@​ManyToOne​(​(​)​ ​=>​ ​BasicUser​,​ ​basicUser​ ​=>​ ​basicUser​.​user​)​
  ​client​: ​BasicUser​;
```


Correct:
```
@​ManyToOne​(​(​)​ ​=>​ ​BasicUser​,​ ​basicUser​ ​=>​ ​basicUser​.​transactions)​
  ​client​: ​BasicUser​;​
```
