### ISSUE TITLE
unable to use the ROW_NUMBER() function to return row_number in postgres

### ISSUE THREAD

**Issue by alex-r89** [typeorm/typeorm#6311]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,

I am struggling to work out how to return the row_number from the [ROW_NUMBER()](https://www.postgresqltutorial.com/postgresql-row_number/) function using typeorm. I am not too sure if this is a missing feature or if I am just getting the syntax wrong. I marked as both feature request and question to reflect this.

I have the following entity:
```ts
@ObjectType()
@Entity()
export class Photo extends BaseEntity {
  @Field(() => ID)
  @PrimaryGeneratedColumn()
  id: number

  @Field()
  @Column('text')
  name: string

  @Field()
  @Column('int', { default: 0 })
  like_count: number
}
```

I essentially want to order the pictures by like_count, however I also want to "rank" the photos. EG, the first photo returned is rank 1, second is rank 2, etc etc. I can do this via the PostgreSQL ROW_NUMBER Function, like so:
```sql
select *, ROW_NUMBER () OVER (ORDER BY like_count desc) from "photo" p 
```
This returns rows with a row_number column as expected:

| id  | name | like_count | row_number
| ------------- | ------------- | ------------- | ------------- |
| 1  | Zebra  | 29  | 1  |
| 2 | Dog  | 23  | 2  |
| 3 | Cat  | 9  | 3  |

However, when running the following with `createQueryBuilder`, no row_number is returned:

```ts
await getConnection()
      .createQueryBuilder()
      .select('photo')
      .addSelect('ROW_NUMBER () OVER (ORDER BY "like_count" DESC)')
      .from(Photo, 'photo')
      .getMany()
```

| id  | name | like_count |
| ------------- | ------------- | ------------- |
| 1  | Zebra  | 29  |
| 2 | Dog  | 23  |
| 3 | Cat  | 9  |

An important thing to note though is that if I use `getRawMany()` instead of `getMany()`, then row_number **is** returned. Therefore, the `createQueryBuilder` I have created is working in postgres.

Does anyone know if`getRawMany()` is the only way to return row_number in postgres? My only other thought was to add something to the Photo entity, but I dont think there is any field/column/generated decorator for the value of the PostgreSQL ROW_NUMBER Function?

Any advice would be greatly appreciated!
Thanks

**Comment by imnotjames** [comment]
You'll either need to use `getRawMany` or #296
