### ISSUE TITLE
Cannot create a OneToOne relationship

### ISSUE THREAD

**Issue by expelliamus** [typeorm/typeorm#6320]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm using `Typeorm` and I'm trying to create a `OneToOne` relationship between two entities: `Project` and `Resource`.
For doing so I did:

```
    import { Entity, Column, PrimaryGeneratedColumn, OneToMany, OneToOne, JoinColumn, PrimaryColumn } from 'typeorm';
    import { Customer } from './customer';

    @Entity()
    export class Project {
        @PrimaryGeneratedColumn()
        public id!: number;
    
        @Column({ nullable: false })
        public name!: string;
    
        @Column({ nullable: true })
        public description!: string;
        
        @PrimaryColumn({ nullable: false })
        public customer_id!: number;
    
        @OneToOne(() => Customer)
        @JoinColumn({ name: 'customer_id' })
        public customer!: Customer;
    
        @Column({ default: false })
        public deleted: boolean = false;
    }
```

then I have `Resource` entity:
```
    import { Entity, Column, PrimaryGeneratedColumn, OneToOne, JoinColumn, PrimaryColumn } from 'typeorm';
    import { Project } from './project';
    
    @Entity()
    export class Resource {
        @PrimaryGeneratedColumn()
        public id!: number;
    
        @Column({ nullable: false })
        public name!: string;
    
        @Column()
        public description: string = "";
    
        @Column()
        public deleted: boolean = false;
    
        @PrimaryColumn({ nullable: false })
        public project_id!: number;
    
        @OneToOne(() => Project)
        @JoinColumn({ name: 'project_id' })
        public project!: Project;
    }
```

Essentially a `Resource` can be associated to one `Project`, so I've defined the `OneToOne` decorator above the `project` property of `Resource`, and then, I've also defined a column called `project_id`, I need this columns for my `API` design.

Usually Typeorm create the `projectId` column, so I've specified with `name` property: `project_id`, the problem's that I got:

> message: "ER_DUP_FIELDNAME: Duplicate column name 'project_id'",
  code: 'ER_DUP_FIELDNAME',
  errno: 1060,
  sqlMessage: "Duplicate column name 'project_id'",
  sqlState: '42S21',
  index: 0,
  sql: 'CREATE UNIQUE INDEX `REL_1c2e17cbbe9905b63f1f870679` ON `resource` (`project_id`, `project_id`)',
  name: 'QueryFailedError',
  query: 'CREATE UNIQUE INDEX `REL_1c2e17cbbe9905b63f1f870679` ON `resource` (`project_id`, `project_id`)',
  parameters: []
}

I was able to fix this using: 

    @JoinColumn({ name: 'project_id', referencedColumnName: 'id' })

but I don't understand why in the first setup this didn't worked 'cause I did exactly the same for `Project` entity, in particular linking the `Customer` table and it works.

Also, I'm not sure that this is correct, these are the constraints created:

[![enter image description here][1]][1]

and this is the ER so far:

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/2adN0.jpg
  [2]: https://i.stack.imgur.com/ACKIv.jpg

**Comment by imnotjames** [comment]
Could be a problem related to #1668 

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
