### ISSUE TITLE
How to Conditionally Build a Query?

### ISSUE THREAD

**Issue by gb53smith** [typeorm/typeorm#6322]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] ^0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am working on my wine cellar database again. I want to search for wines matching color, grape, winery, country.
For example, this code finds matching color and grape columns.
```
            const wineSelection = await getRepository(Winecellar)
                .createQueryBuilder("wine")
                .where("wine.Colour = :Colour", { Colour: colour })
                .andWhere("wine.Grape = :Grape", { Grape: grape })
                .orderBy("wine.Vintage", "ASC")
                .getRawMany();
```
I want to skip a column if my search form submits a field with the keyword "any". With TypeORM it looks like I have create 16 different queries ,one for the possible combination of fields with the "any" keyword.
Is there a better workaround for this problem? There must be another way to build a query?
(Using Python I was able to create the SQL query, conditionally, and then submit it to the database engine.)

**Comment by vicbyte** [comment]
You can just save intermediate queryBuilder and modify it conditionally like:

`const qb = getRepository(Winecellar)
                .createQueryBuilder("wine")
                .orderBy("wine.Vintage", "ASC");

if (colour !== 'any') {
  qb.andWhere("wine.Colour = :Colour", { Colour: colour });
}
if (grape !== 'any') {
  qb.andWhere("wine.Grape = :Grape", { Grape: grape });
}

const wineSelection = await qb.getRawMany();`

**Comment by gb53smith** [comment]
Thanks vicbyte, great solution.  I was surprised that multiple .andWhere statements could be used without a preceding .were statement.  createQueryBuilder works out by replacing the first .andWhere with a WHERE followed by AND for the rest in the SQL command.
