### ISSUE TITLE
softRemove DeleteDateColumn is null at Susbscriber's AfterUpdate method

### ISSUE THREAD

**Issue by aykutcan** [typeorm/typeorm#6327]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Problem**

``softRemove()`` method triggers ``afterUpdate()`` without specified ``@DeleteDateColumn``

I cant access deleted_at column to detect deletion of that entity and remove it from elasticsearch

**Steps to reproduce or a small repository showing the problem:**

Create User Entity with DeleteDateColumn decorator

```ts 

@Entity({ name: 'users' })
export class User {

...

    @Index('users.deleted_at')
    @DeleteDateColumn({ name: 'deleted_at' })
    deleted_at: Date;

...

}
 ```

Create UserSubscriber
```ts 
@EventSubscriber()
export class UserSubscriber implements EntitySubscriberInterface<User> {
    listenTo() {
        return User;
    }

    afterUpdate(event: UpdateEvent<User>): any {
        console.log(`AFTER UPDATE: `, event.entity);
    }

}


 ```

Trigger softRemove on an entity
```ts 
    let user = await userRepository.findOne(5);
    await userRepository.softRemove(user);
 ```

**What it should do**

Return removed entity with deleted_at column filled

**What it does**

Return entity with null deleted_at column

**Comment by cantoute** [comment]
+1: same with sqlite

**Comment by lucasbemol** [comment]
+1: same with postgresql

**Comment by spotykatch** [comment]
Could that be a bug? https://github.com/typeorm/typeorm/issues/6349#issuecomment-907799685

**Comment by spotykatch** [comment]
So, we've got a bug here, I guess, but that still does not solve the problem. The function should return isDeleteColumn or there should be a function for softRemove.
https://github.com/typeorm/typeorm/blob/a868078f8f4f63cc8d81a63e098d639ed12c6608/src/query-builder/ReturningResultsEntityUpdator.ts#L193

**Comment by spotykatch** [comment]
And the last one. 
https://github.com/typeorm/typeorm/blob/a868078f8f4f63cc8d81a63e098d639ed12c6608/src/persistence/SubjectExecutor.ts#L738
Must be

```JS
// update soft-removed entity properties
if (this.softRemoveSubjects.length)
    this.updateSpecialColumnsInInsertedAndUpdatedEntities(this.softRemoveSubjects);

// update recovered entity properties
if (this.recoverSubjects.length)
    this.updateSpecialColumnsInInsertedAndUpdatedEntities(this.recoverSubjects);
```
Works here https://replit.com/@spotykatch/Typeorm-6327-issue for SQLite with Manager. Didn't test for others.

**Comment by sofiamicrobio** [comment]
+1 here

**Comment by spotykatch** [comment]
The pr is been sent. But I don't have much experience with it. First CircleCI builds for cockroach failed due to timeout. Merge with the new version of typeorm passed the tests. But merge doesn't seem to be included in the pr. If you can help me with it, I would be very grateful.
