### ISSUE TITLE
feature request: use debug package for logging

### ISSUE THREAD

**Issue by NoNameProvided** [typeorm/typeorm#633]
With #505 closed, log messages are highlighted in the terminal which is awesome, however it cannot work when using a custom logger function. The reason we use custom logger is to control an universal way of what we log in different environments.

The package we use is `debug` used both by Express & Koa for logging. The idea is to specify different name spaces in the `DEBUG` environment variable on startup to select what to log. 

An example: `typeorm:*,-typeorm:query`. This would log every message from TypeORM except the ones when written on queries. (These are listed here: [src/logger/Logger.ts#L73-L92](https://github.com/typeorm/typeorm/blob/master/src/logger/Logger.ts#L73-L92) )

To achieve this the following have to be done:
- use `debug` package for logging
- do not return when no logging options are present
- remove old way of specifying logging options (via `LoggerOptions`)

Things worth to discuss: 
- console.log calls in cli commands, I left them untouched, I think there is no benefit filtering them. When someone runs a command she/he wants to see the output. 
- where to add this in the docs

**Comment by pleerock** [comment]
Ive left comments in PR regarding to this issue.
