### ISSUE TITLE
boilerplate?!

### ISSUE THREAD

**Issue by vrg-success** [typeorm/typeorm#6330]
**Issue type:**

[] question
[ ] bug report
[x] feature request
[ ] documentation issue

Hi, I detect that I need every time import getRepository and my entity to work with database, it's looking not bad, but if project will be big, it looks like boilerplate shit, I think will be cool when I just import entity with all function of getRepository methods. But now I need create a file with export all repositories ```export getRepository(UsersEntity)```, it's again not bad, but why do I need create more files?

**Comment by imnotjames** [comment]
Sounds like you want the active record pattern. That's supported by typeorm already.
