### ISSUE TITLE
createQueryBuilder sets variables where there should be none

### ISSUE THREAD

**Issue by electather** [typeorm/typeorm#6331]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

using the following code generates a faulty query:

```typescript 
    const qb = this._thirdPartyRepository
      .createQueryBuilder('tpi')
      .select('SUM(tpi.full_amount)', 'totalValue')
      .addSelect('COUNT(*)', 'count')
      .addSelect('tpi.start_date::date', 'day')
      .groupBy('tpi.start_date::date')
      .orderBy('tpi.start_date::date')
      .where('tpi.full_amount > :min', {
        min: 0,
      });
    if (user.role !== RoleType.ADMIN) {
      qb.andWhere('tpi.creator_id = :id', {
        id: user.id,
      });
    } else if (options.userId) {
      qb.andWhere('tpi.creator_id = :id', {
        id: options.userId,
      });
    }
    if (options.startDateMin) {
      qb.andWhere('tpi.start_date >= :date', {
        date: options.startDateMin,
      });
    }
    if (options.startDateMax) {
      qb.andWhere('tpi.start_date <= :date', {
        date: options.startDateMin,
      });
    }
    const rawResult = await qb.getRawMany();
```

which generates:
 
```sql
SELECT SUM(tpi.full_amount) AS "totalValue", 
       Count(*)             AS "count", 
       tpi.start_date :$ 1  AS "day" 
FROM   "third-party-insurance" "tpi" 
WHERE  tpi.full_amount > $2 
       AND tpi.start_date >= $3 
GROUP  BY tpi.start_date :$ 4 
ORDER  BY tpi.start_date :$ 5 ASC -- PARAMETERS: ["2020-06-21T00:00:00.000Z",0,"2020-06-21T00:00:00.000Z","2020-06-21T00:00:00.000Z","2020-06-21T00:00:00.000Z"] 
```
this only happens if i try to set `startDateMin` variable, without it the query runs fine and works perfectly

**Comment by imnotjames** [comment]
Use two different variable names for `date` - the same variables can be reused multiple times and this often causes issues.

For otherquestions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
