### ISSUE TITLE
How can I use multiple databases in a single connection in PostgreSQL

### ISSUE THREAD

**Issue by zhiyuanzhang-unai** [typeorm/typeorm#6333]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In this document: https://orkhan.gitbook.io/typeorm/docs/multiple-connections.
It states that "Using multiple databases in a single connection" "this feature is supported only in mysql and mssql databases".
Any reason it won't support Postgresql? Is it because of the Postgressql limitation? Or just didn't have time implementing this feature on Postgres?

I am working on a project which will deal with multiple databases in a postgres instance. I am trying to avoid creating multiple connections (30+ connections). It would be better that I can specify the database name in the entity class and reuse the same connection.

**Comment by guiaramos** [comment]
Please check this comment might help you: https://github.com/typeorm/typeorm/issues/5308#issuecomment-652887398

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
