### ISSUE TITLE
[question] Fetching non-eager fields within a class

### ISSUE THREAD

**Issue by yorickdevries** [typeorm/typeorm#6339]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

What is the correct/most neat way to fetch non-eager fields from inside a class? What I do now is, but this is a bit extensive as I have to specify User 4 times:

```ts
  async getUser(): Promise<User> {
    return (
      await CurrentClass.findOneOrFail(this.id, {
        relations: ["user"],
      })
    ).user!;
  }
 ```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
