### ISSUE TITLE
How can I create an embedded geolocation index with mongodb?

### ISSUE THREAD

**Issue by Ibcs16** [typeorm/typeorm#6341]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[X ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have to create an index as follows:
```
db.address.createIndex( { "location": "2dsphere"} )
```
I tried doing so with decorator @Index like this

```
@Entity('orders')
@Index('addressIndex', ['address.location'])
export default class Order {
  @Column(() => Address)
  address: Address;
  // where address has a location attribute with type and coordinates
}
```

So how can I achieve that with typeorm??

**Comment by imnotjames** [comment]
I don't think this is supported in mongodb natively.  You'll need to check out our support channels for workarounds.  There are a number of issues on this repo regarding TypeORM & mongodb not handling indices.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
