### ISSUE TITLE
[React-native], Load an external database

### ISSUE THREAD

**Issue by Thomascogez** [typeorm/typeorm#6345]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

    I'm currently trying to load an sqlite database that I download before instanciate typeorm, I was previously using a database 
   packaged with the apk (in ~www/db.db), but know I want to load the database from an external folder. I take a look at the 
   react-native-sqlite-storage doc and saw this

   ```js
       3.SQLite.openDatabase({name : "testDB", createFromLocation : "/data/mydbfile.sqlite"}, okCallback,errorCallback);
       // if your folder is not in app bundle but in app sandbox i.e. downloaded from some remote location.
   ```
   The thing, is that typeorm force you to put the **location** options.
   One more thing, this is how i'm loading my database for the moment : 
   ```ts
    createConnection({
    type: 'react-native',
    location: 'default',
    database: 'db.db',
    extra: {
      createFromLocation: '~www/db.db',
    },
    logging: __DEV__ ? ['error', 'info', 'query', 'schema', 'warn'] : [],
    entities: [...],
  })
   ```
  If anyone has a solution i'll take it

**Comment by Thomascogez** [comment]
Found a solution (tested in production), I will make a pr when I have some time

**Comment by cristian-milea** [comment]
> Found a solution (tested in production), I will make a pr when I have some time

Care to give more information on your solution, please?

**Comment by Thomascogez** [comment]
if you wanna see the changes here https://github.com/Thomascogez/typeorm/tree/rn_load_external_db. Hit me up if you want an example

**Comment by cristian-milea** [comment]
> if you wanna see the changes here https://github.com/Thomascogez/typeorm/tree/rn_load_external_db. Hit me up if you want an example
Thanks, You can write the example, maybe somebody else is looking for this in the future :)

**Comment by imnotjames** [comment]
Sounds like you've got this figured out.  I can't quite find exactly what changes you made that help with this but please feel free to open a PR or if there's a more defined issue you're seeing please feel to open a new issue for this.

**Comment by sandro-salles** [comment]
@Thomascogez hey man! Nice to know you've made it.... can you please send and example or point to this solution???

Thank you so much!

**Comment by Thomascogez** [comment]
@sandro-salles, I was able to fix this by using the @ next version and doing those changes https://github.com/Thomascogez/typeorm/commit/6b346f4604a02bfa2da01635dd4cae9a2a1d840c. Then i use the createFromLocation options (has i show on my initial post). I would try to get example if you can't achieve this but I don't have access to my working code anymore.
