### ISSUE TITLE
Mysql typeorm doesn't correct parse null value into sql query 

### ISSUE THREAD

**Issue by odykyi** [typeorm/typeorm#6346]
**Issue type:**

[ ] question
[+] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[+] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[+] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
This code 
```javascript 

 return this.repository.find({
      where: {
        user: null,
      },
      relations: ['profile', 'profile.company'],
  });

```
converts to(sql):

```... WHERE user = null```

should be(sql): 

```... WHERE user IS NULL```

**Comment by imnotjames** [comment]
Use the `IsNull()` `FindOperator`.
