### ISSUE TITLE
Subscribers and softRemove

### ISSUE THREAD

**Issue by bianchi** [typeorm/typeorm#6349]
**Issue type:**

[X] question
[X] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a LogSubscriber and I'm using the softRemove feature. When softRemove() is called afterRemove is not triggered (I think it should have an afterSoftRemove decorator). I figured out that softRemove triggers update because deleted data column have been changed (That happens). So I tried do identify if the delete data column have changed its value to know if it was a "real" update or a soft remove operation, but it always show the same value:

`
beforeUpdate(event: UpdateEvent<any>): Promise<any> | void {
		console.log(event.databaseEntity.deleted_at);
		console.log(event.entity.deleted_at);
	}
	
afterUpdate(event: UpdateEvent<any>): Promise<any> | void {
        	console.log(event.databaseEntity.deleted_at);
		console.log(event.entity.deleted_at);
}
`

Results in:
`
2020-07-03T20:03:27.168Z
2020-07-03T20:03:27.168Z
2020-07-03T20:03:27.168Z
2020-07-03T20:03:27.168Z

`

Am I missing something?

**Comment by bianchi** [comment]
> I figured out that softRemove triggers update because deleted data column have been changed (That happens)

To be clear, the trigger to update happens but event.updatedColumns does not show the delete data column

**Comment by bianchi** [comment]
Any help?

**Comment by holm** [comment]
It seems the softRemove and softRecover have just copy/pasted the columns logic from the update event, which really doesn't make much sense. The problem is clear to see here: https://github.com/typeorm/typeorm/blob/master/src/persistence/SubjectExecutor.ts#L216

I think it would be much better to have separate events for soft remove and recover, rather than try to reuse the update events. The current subscribers have no way to understand if an update, a soft remove or recover happened, and I would guess this is more likely the cause of bugs or confusion.

**Comment by leoatrenew** [comment]
This has been probably done before but just in case, not yet, below is the work around that I did. (while waiting for the solution),
1. In the call to **softRemove**, I added a data in the **SaveOptions** parameter.
`this.repo.softRemove(entity, {data: { deleted: true } });`
2. Then in the subscriber, I checked the data in the **beforeUpdate** method. (depending on the need, can also be done in **afterUpdate**). I used this data to determine whether the operation was a delete/remove.
`if (event.queryRunner.data.deleted) {
    // extra delete logic
}`

**Comment by spotykatch** [comment]
It seems, that the updated_at column returned to the subscriber unchanged either.

**Comment by spotykatch** [comment]
The bug might be here.
https://github.com/typeorm/typeorm/blob/a868078f8f4f63cc8d81a63e098d639ed12c6608/src/query-builder/SoftDeleteQueryBuilder.ts#L79
We are calling getUpdationReturningColumns(), which returns only update and version columns.

**Comment by meodemsao** [comment]
@spotykatch i'm using version 0.2.45 and afterSoftRemove alway return entity is undefine
Can you let me know this commit stable in any version ?

**Comment by spotykatch** [comment]
> @spotykatch i'm using version 0.2.45 and afterSoftRemove alway return entity is undefine

I can't reproduce that. [[Sandbox]](https://codesandbox.io/s/interesting-banach-hgw4kj?file=/src/app.subscriber.ts)
Maybe you should create an issue and give us some code?
