### ISSUE TITLE
Specifying relations to support legacy database

### ISSUE THREAD

**Issue by truewt** [typeorm/typeorm#635]
Hi,

I'm rewriting data-related part of an older application which was created for non-SPA environment with dynamic pages (MVC app with some AJAX parts) approach. I chose to rewrite API with TS & Node.js because of decorators and all the things that make code easily readable. However, I wanted to reconstruct database with entities in typeorm, so in case that application is bootstrapped from zero (without existing DB), the database doesn't need any script to be run in order to initialize it. Database which I'm using is MySQL. To achieve that I need to retain the whole structure of fields in tables, but there must be also defined some foreign keys and other things which are needed to preserve relations. I already rewrote current tables into entities, but the part with relations seems a bit impossible to do for me at the moment. I tried to use `@ManyToOne` decorator for defining foreign key in one table, but I always get another field in table which doesn't have correct name. Here is the example:

We have two entities - User and Post. User can create zero or more posts, but post is always created by a single user. So we should have the following two tables:

- user - user_id (PK), name, username, password, email
- post - post_id (PK), title, content, publish_date, user_id (FK)

So we would specify both models as:
```
@Entity()
export class User {

  @PrimaryGeneratedColumn()
  user_id: number;

  @Column({ length: 255 })
  name: string;

  @Column({ length: 20, unique: true })
  @Index()
  username: string;

  @Column({ length: 128 })
  password: string;

  @Column({ length: 255, unique: true })
  email: string;

}
```

```
@Entity()
export class Post {

  @PrimaryGeneratedColumn()
  post_id: number;

  @Column({ length: 255 })
  @Index()
  title: string;

  @Column("text")
  content: string;

  @Column("date")
  publish_date: Date;

  @Column("int")
  user_id: number;

}
```

As stated above, I need to retain user_id in Post entity to support the existing state of database entries. I tried to add `@ManyToOne` decorator to Post's user_id as ...

```
@Column("int")
@ManyToOne(() => User)
user_id: number;
```

But that didn't work well, because then I got the following structure of table:

- post - post_id (PK), title, content, publish_date, user_id, **userUserId (FK)**

So the problem here is that the foreign key is always being inserted at the end of table and has specific naming strategy which isn't ok in my case. So my question here it is - do I have to handle my case manually and run database init script in case of a new environment, or I am missing something and there actually is a way to support such cases?

Any answer/recommendation will be highly appreciated. Thanks in advance!

**Comment by pleerock** [comment]
relations should always be objects. To specify a custom referenced column name try this apporach:

```ts
@ManyToOne(() => User)
@JoinColumn({ name: "user_id" })
user: User;
```

**Comment by pleerock** [comment]
> If I understand correctly, this lazy is not executed until object (actually promise) returned in results is not awaited?

right

> Do I have to specify referencedName in @JoinColumn if it's same as name?

you specify `referencedName` only if you need it. If you don't it by default referenced to entity primary keys.

> and assign it ID I already know

yes you can update by simply assign an id

**Comment by truewt** [comment]
Thanks! :)
