### ISSUE TITLE
upgrading XML parser library

### ISSUE THREAD

**Issue by amitguptagwl** [typeorm/typeorm#6353]
As we're currently using xml2js v0.4.17, I wanted to suggest using [fast-xml-parser](https://github.com/NaturalIntelligence/fast-xml-parser) due to performance;

file size | fxp 3.0 validator (rps) | fxp 3.0 parser (rps) | xml2js 0.4.19 (rps)
-- | -- | -- | --
1.5k | 16581.06758 | 14032.09323 | 4615.930805
1.5m | 14918.47793 | 13.23366098 | 5.90682005
13m | 1.834479235 | 1.135582008 | -1
1.3k with CDATA | 30583.35319 | 43160.52342 | 8398.556349
1.3m with CDATA | 27.29266471 | 52.68877009 | 7.966000795
1.6k with cdata,prolog,doctype | 27690.26082 | 41433.98547 | 7872.399268
98m | 0.08473858148 | 0.2600104004 | -1

-1 indicates the error.

**Comment by imnotjames** [comment]
Hi there!  Given that we're only using the `xml2js` during startup I think at this time it's safe that we'll continue using it even with the possible performance issues.  However, if we ever do run into performance problems in the future we'll keep you in mind!
