### ISSUE TITLE
Cannot import SelectQueryBuilder

### ISSUE THREAD

**Issue by IRCraziestTaxi** [typeorm/typeorm#636]
Since many functions have been moved from QueryBuilder to SelectQueryBuilder, I have run into an issue since SelectQueryBuilder is not exported from typeorm's index. The problem is that I store a reference to a QueryBuilder which needs to be able to call SelectQueryBuilder functions at different times. When those functions were a part of QueryBuilder, it was not an issue; now, since I cannot import SelectQueryBuilder, my code is broken with the latest version of TypeORM.

**Comment by pleerock** [comment]
fixed and will be released in `0.1.0-alpha.32`
