### ISSUE TITLE
Include "select: false" fields in call to "find" without having to select every single column

### ISSUE THREAD

**Issue by gkovalechyn** [typeorm/typeorm#6362]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have an object with a field that can be pretty large and for that reason I don't want to include it in queries and be returned most of the time.

Selecting the field when calling `findOne` like this does work and all the fields plus the selected field is returned:
```ts
public findOfferById(id: string, options?: FindOfferOptions): Promise<Offer | undefined> {
  const findOneOptions: FindOneOptions<Offer> = {
    relations: [],
    select: []
  };

  if (options) {
    if (options.withProducts) {
      findOneOptions.relations.push("products");
    }

    if (options.withComments) {
      findOneOptions.relations.push("comments");
    }

    if (options.withSeller) {
      findOneOptions.relations.push("seller");
    }

    if (options.withImages) {
      findOneOptions.relations.push("images");
    }

    if (options.withDescription) {
      findOneOptions.select.push("description");
    }
  }

  return this.repository.findOne(id, findOneOptions);
}
```

But trying to return multiple records like this with `find` does not have the same behavior, only returning the selected field:
```ts
    const options: FindManyOptions<Offer> = {
      where: {
        sellerId: user.id
      },
      relations: [],
      select: []
    };

    if (query.withImages) {
      options.relations.push("images");
    }

    if (query.withProducts) {
      options.relations.push("products");
    }

    if (!query.includeInactive) {
      const where = options.where as FindConditions<Offer>;
      where.isActive = true;
    }

    if (query.withDescription) {
      options.select.push("description");
    }

    const offers = await this.repository.find(options);
```

Is there a way I can also select that field without having to also select all of the fields in the entity?

**Comment by imnotjames** [comment]
There's currently no way to get around selecting fields explicitly if you select at least one field.
