### ISSUE TITLE
[question] Mutate query in before hook (multi-tenant security)

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#6365]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x] `0.2.7` (or put your version here)

I have a multi-tenant database, with a table containing multiple tenant data, segregated by a tenantId.

I want to enforce security at the SQL Level. Can I use subscriptions to mutate / block SQL from running that does not have a tenantId filter? Or is this possible in a different way?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
