### ISSUE TITLE
Transactions on ActiveRecord

### ISSUE THREAD

**Issue by iagocc** [typeorm/typeorm#6368]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

Hello everyone, I would like to propose a transaction ability for ActiveRecord entities.

For example, I have Dataset and Record as BaseEntity.
```typescript
    await getManager().transaction(async tx => {
      dataset.name = req.body.name
      dataset.labels = req.body.labels.split(',')
      dataset.records = [] as Record[]

      const stream = new Readable()
      stream.push(file.data)
      stream.push(null)

      stream.pipe(csvParser()).on('data', async data => {
        console.log(data)
        const row = JSON.stringify(data)
        const record = new Record()
        record.content = row
        record.dataset = dataset
        record.label = ''
        dataset.records.push(record)
        await tx.save(record)
      })

      tx.save(dataset)
```
But unfortunately, I received:
``
QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.
``
I guess this is because of:
> The most important restriction when working in an transaction is, to ALWAYS use the provided instance of entity manager - transactionalEntityManager in this example. If you'll use global manager (from getManager or manager from connection) you'll have problems. You also cannot use classes which use global manager or connection to execute their queries. All operations MUST be executed using the provided transactional entity manager.
From [Documentation](https://typeorm.io/#/transactions)

**Comment by IRoninCoder** [comment]
Why is this a feature? shouldn't it be working since `tx` is in the scope of the transaction. I have a similar problem and like to understand a bit more.

**Comment by Hypher** [comment]
I don't get it. Your example does not use ActiveRecord since you use `tx.save(entity)` and not `record.save()` or `dataset.save()`.

Plus it seems you are using a TransactionManager (tx) in a callback (on 'data') which runs after the transaction is over, probably explaining the error message. `await` your pipe data and it should work.

But sure, the issue title "Transactions on ActiveRecord" is a feature request. This issue should be closed and a proper issue related to ActiveRecord inside transactions should be created. Like using `entity.save({transaction:txmanager})` for example.

**Comment by imnotjames** [comment]
> I don't get it. Your example does not use ActiveRecord since you use `tx.save(entity)` and not `record.save()` or `dataset.save()`.
> 
> Plus it seems you are using a TransactionManager (tx) in a callback (on 'data') which runs after the transaction is over, probably explaining the error message. `await` your pipe data and it should work.
> 
> But sure, the issue title "Transactions on ActiveRecord" is a feature request. This issue should be closed and a proper issue related to ActiveRecord inside transactions should be created. Like using `entity.save({transaction:txmanager})` for example.

Agreed.  Actual issue above is that you aren't `await`ing `stream.pipe()`. 

I'm going to close this.  Anyone that would like it as an actual feature please open a new issue with a proposal or two on how you think it could work.
