### ISSUE TITLE
Custom repository is not respecting the underlying transaction

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#637]
Hello!

I'm witnessing a problem when custom repository, retrieved from transactional entity manager is not respecting the transaction.

Here's the sample code:

```typescript
this.connection.entityManager.transaction(entityManager => {
  const repository = entityManager.getCustomRepository(FooRepository);
  const foo = new Foo();
  repository.persist(foo); // Database call is done outside of the transaction!
});
```

**Comment by pleerock** [comment]
what if you put await before `repository.persist(foo); ` ?

**Comment by slavafomin** [comment]
Actually, it was just a sample extracted from more complex code. The promises are handled correctly in my real code, there are no ignored promises or something.

**Comment by pleerock** [comment]
then I'll check it, maybe there is a bug.

**Comment by pleerock** [comment]
I added test that asserts fact that entity manager in transaction is the same as in custom repository - it means everything works as expected. Problem is most probably on your side, please create a minimal reproduction of this problem and I'll test it and make sure you are on the latest version of typeorm.

**Comment by pleerock** [comment]
also, make sure you aren't using `connection.manager` anywhere inside transaction. Or your problem is that you are using outdated version of typeorm.

**Comment by slavafomin** [comment]
Thank you for looking into this and for your suggestions. I will try to investigate further on my side. I'm using TypeORM `0.0.11`. This a latest version, right?

**Comment by pleerock** [comment]
no, the latest is `0.1.0-alpha.32`

**Comment by slavafomin** [comment]
I mean latest stable version. I'm using TypeORM for production application.

**Comment by slavafomin** [comment]
However, `0.0.x` also can't be considered stable. Should I switch to `0.1` alpha?

**Comment by pleerock** [comment]
right. switch to latest version.

**Comment by slavafomin** [comment]
Thanks, I will try to do so. Any upgrade issues I should be aware of?

**Comment by pleerock** [comment]
refer to changelog, info about most notable changes you can find there. There are lot of things changed.

**Comment by slavafomin** [comment]
By the way, @pleerock is it safe to use `this.manager` inside of repository? Transaction-wise I mean.

**Comment by pleerock** [comment]
there are two kind of repositories and managers: global and transaction-specific. 

Global are:
* connection.manager, 
* connection.getRepository,
* connection.manager.getRepository

transaction specific are:
* transaction(manager => manager),
* transaction(manager => manager.getRepository)

Depend on what repository you are asking

**Comment by slavafomin** [comment]
I meant something like this:

```postgresql

const connection = await createConnection({
  type: 'postgres'
});

await connection.transaction(async entityManger => {

  const repository = entityManger.getCustomRepository(UsersRepository);

  // Will this query be executed inside of the transaction?
  await repository.manager.query('…');

});
```

**Comment by pleerock** [comment]
yeah it should, try to do:

````ts

await connection.transaction(async entityManger => {

  const repository = entityManger.getCustomRepository(UsersRepository);

  // Will this query be executed inside of the transaction?
  console.log(repository.manager === entityManager); // should return you true

});
```

**Comment by slavafomin** [comment]
Yes, thank you. I've implemented some tests for this inside of my project and everything is working correctly in `0.1.0-alpha.32` :+1:

**Comment by eddievagabond** [comment]
@pleerock I hate to open this again, But I am having an issue where transactions are not rolling back in this way. I am using Postgres on typeorm 0.2.17. For instance:

```
public async createAssociateUser(associateUser: AssociateUserCreateRequest) {
  return await this._connection.transaction(async entityManager => {
      const _associateRepository = await entityManager.getCustomRepository(AssociateRepository);
      const _userRepository = await entityManager.getCustomRepository(UserRepository);

      console.log('===============',_userRepository.manager === entityManager); // returns true
      console.log('===============',_associateRepository.manager === entityManager); // returns true
     // fail here
     const createdUser = await _userRepository.createUser(user);

    // console says the transaction rolled back but the row is still inserted into database
}
```

Console output abbreviated 
```console
query: START TRANSACTION
=============== true LOG FROM ABOVE
=============== true LOG FROM ABOVE
query: INSERT INTO "user"("id", "email", "first_name", "last_name", "password","is_activated", "is_enabled", "invitation_token", "reset_password_token", "created_on", "updated_on") VALUES (DEFAULT, $1, $2, $3, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) -- PARAMETERS: ["test@test.com","FIRST","LAST"]

query: INSERT INTO "associate"("id", "user_id", "location_id", "is_checkin",  "created_on", "updated_on") VALUES (DEFAULT, DEFAULT, DEFAULT, $1, $2, $3, $4, $5, DEFAULT, DEFAULT) -- PARAMETERS: [1,1,1,1,1]
query: ROLLBACK
```

**Comment by eddievagabond** [comment]
Please disregard the above. I made a mistake in my custom repository. I was using getConnection(Entity<T>) this the constructor of my repository instead of using this after extending via Repository<T>.
