### ISSUE TITLE
Queries executed outside the transaction

### ISSUE THREAD

**Issue by fstn** [typeorm/typeorm#6373]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

By Using createQueryBuilder, my code is executed outside my current transaction and can't read uncommited data

Could you explain to me why this is executed inside my transaction

    let candidatInMyTx: CandidateFileEntity = await  candidateService.getRepo().manager
    .query("SELECT * FROM \"candidate_files\" \"candidateFile\" WHERE \"candidateFile\".\"candidateId\" IN ($1)",[c1.id])

Generated query:

        SELECT * FROM "candidate_files" "candidateFile" WHERE "candidateFile"."candidateId" IN ($1) -- PARAMETERS: ["f20a984d-3018-4cef-a5b6-a6c3c2480728"]

and this is executed outside (so return nothing) it works if I do a commit before:

            let candidatOutsideMyTx: CandidateFileEntity =
            await candidateService.getRepo().manager.createQueryBuilder()
            .relation(CandidateEntity,'candidateFile')
            .of(c1).loadOne()

This code is wrapped with
  
      runner = getManager().connection.createQueryRunner()
      transaction = await runner.startTransaction()
      entityManager = runner.manager
       candidateFilesService.getRepo().manager = entityManager

Generated query:

                  SELECT "candidateFile"."version" AS "candidateFile_version", "candidateFile"."updated_at" AS "candidateFile_updated_at", "candidateFile"."created_at" AS "candidateFile_created_at", "candidateFile"."id" AS "candidateFile_id", "candidateFile"."status" AS "candidateFile_status", "candidateFile"."candidateId" AS "candidateFile_candidateId" FROM "candidate_files" "candidateFile" WHERE "candidateFile"."candidateId" IN ($1) -- PARAMETERS: ["f20a984d-3018-4cef-a5b6-a6c3c2480728"]

Why using the manager inside the Repository execute the query outside the transaction?

Do I have a way to log the queries with the transaction id?

**Comment by imnotjames** [comment]
You have to work using the same query runner to use the same transaction.
