### ISSUE TITLE
How to use onDelete: "CASCADE" with @OneToOne relationship?

### ISSUE THREAD

**Issue by theChaiyakorn** [typeorm/typeorm#6374]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Here is my code.

**User Entity**
```
export class User extends BaseEntity {
  ...

  @OneToOne(
    (type) => Profile,
    (profile) => profile.user,
    { eager: true, cascade: true, onDelete: "CASCADE" }
  )
  @JoinColumn()
  profile: Profile;

  ...
},
```

**Profile Entity**
```
export class Profile extends BaseEntity {
  ...

  @OneToOne(
    (type) => User,
    (user) => user.profile,
    { onDelete: "CASCADE" }
  )
  user: User;

  ...
}
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
What is the issue you're having?

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
