### ISSUE TITLE
ormconfig.js doesn't work with two set of options in it

### ISSUE THREAD

**Issue by denissabramovs** [typeorm/typeorm#6378]
Config for .js is not working with two configs in it as with json example above it.
https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#using-ormconfigjs
So basically this is not working:
```
module.exports = [
  {
    "name": "admin-api",
    "type": process.env.TYPEORM_CONNECTION,
    "host": process.env.TYPEORM_HOST,
    "port": process.env.TYPEORM_PORT,
    "username": process.env.TYPEORM_USERNAME,
    "password": process.env.TYPEORM_PASSWORD,
    "database": process.env.TYPEORM_DATABASE,
    "migrationsTableName": process.env.TYPEORM_ADMIN_API_MIGRATIONS_TABLE_NAME,
    "migrations": [
      process.env.TYPEORM_ADMIN_API_MIGRATIONS_DIR
    ]
  },
  {
    "name": "tenants-api",
    "type": process.env.TYPEORM_CONNECTION,
    "host": process.env.TYPEORM_HOST,
    "port": process.env.TYPEORM_PORT,
    "username": process.env.TYPEORM_USERNAME,
    "password": process.env.TYPEORM_PASSWORD,
    "database": process.env.TYPEORM_DATABASE,
    "migrationsTableName": process.env.TYPEORM_TENANTS_API_MIGRATIONS_TABLE_NAME,
    "migrations": [
      process.env.TYPEORM_TENANTS_API_MIGRATIONS_DIR
    ]
  }
];
```

**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[^0.2.25] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [] `mysql`
    [x] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by denissabramovs** [comment]
`./node_modules/.bin/ts-node ./node_modules/.bin/typeorm -c admin-api migration:run`

**Comment by denissabramovs** [comment]
```
Error during migration run:
Error: Cannot find connection admin-api because its not defined in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/var/local/dashboards/src/connection/ConnectionOptionsReader.ts:54:19)
    at step (/var/local/dashboards/node_modules/tslib/tslib.js:141:27)
    at Object.next (/var/local/dashboards/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/var/local/dashboards/node_modules/tslib/tslib.js:112:62)

```

**Comment by imnotjames** [comment]
I think that because of how you're calling TypeORM there it's possible that it is not actually retrieving the `js` file in question.

What if you specify the path to the config file via the `--config` option?

**Comment by denissabramovs** [comment]
Isn't it looking by default both .json and .js?

**Comment by imnotjames** [comment]
If you have two files it will only load one

**Comment by denissabramovs** [comment]
And if it is only .js? Then it should load it, right?

**Comment by denissabramovs** [comment]
That's how it is in docs, it is by default looking for .json or .js
I could be wrong, it was long ago, but i think it was like that.

**Comment by denissabramovs** [comment]
https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#using-ormconfigjs here is nothing about specifying some options.

```
Sometimes, you may want to use multiple configurations using different formats. When calling getConnectionOptions() or attempting to use createConnection() without the connection options, Typeorm will attempt to load the configurations, in this order:

From the environment variables. Typeorm will attempt to load the .env file using dotEnv if it exists. If the environment variables TYPEORM_CONNECTION or TYPEORM_URL are set, Typeorm will use this method.
From the ormconfig.env.
From the other ormconfig.[format] files, in this order: [js, ts, json, yml, yaml, xml].
```

**Comment by denissabramovs** [comment]
so it should read from .js anyway and only then from .json

**Comment by denissabramovs** [comment]
or i'm wrong :\

**Comment by imnotjames** [comment]
I don't think you're wrong per se - I think the documentation isn't clear.

Here it will iterate through the items and find the first which is an existing config -- https://github.com/typeorm/typeorm/blob/master/src/connection/ConnectionOptionsReader.ts#L92
