### ISSUE TITLE
Remove orphaned entities from a relation?

### ISSUE THREAD

**Issue by RobbieGM** [typeorm/typeorm#6382]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a one-to-many relation and I would like to delete rows from the many side of the relationship rather than unlinking them by setting their foreign key to null (the default behavior), leaving them orphaned. I saw [a PR](https://github.com/typeorm/typeorm/pull/1665) for this feature but it was rejected. Is there a way to do this, or any plans to support it in the future?

I would like to be able to do something like this:
```ts
@Entity()
@TableInheritance({ column: { name: 'type', type: 'text' } })
export default class Geolocation {
  @PrimaryGeneratedColumn()
  id!: number;

  @IsGeoJSONPoint
  @Column('geography')
  point!: Point;
}

@ChildEntity('business')
export default class BusinessGeolocation extends Geolocation {
  @ManyToOne(type => Business, business => business.geolocations, { onDelete: 'CASCADE' })
  business!: Business;
}


@Entity()
export default class Business {
  @PrimaryGeneratedColumn()
  id!: number;

  // I would like to remove orphaned business geolocations
  @OneToMany(type => BusinessGeolocation, businessGeolocation => businessGeolocation.business, { cascade: true })
  geolocations!: BusinessGeolocation[];
}

// somewhere in the API...

const business = new Business();
business.geolocations = [{ type: 'Point', coordinates: [3, 5] }, { type: 'Point', coordinates: [8, 2] }];
await manager.save(business);
business.geolocations = [{ type: 'Point', coordinates: [6, -3] }]; // I want all the old geolocation rows to be deleted here
await manager.save(business);
```

**Comment by vieweg** [comment]
I have a same question!

**Comment by majorhayes** [comment]
I'm trying to do the same thing.

**Comment by savolkov** [comment]
#1286

**Comment by ml1nk** [comment]
Related: #2467

**Comment by tobiaskraus** [comment]
There was another [PR](https://github.com/typeorm/typeorm/pull/7105) which was merged on Jan 12th 2021, which fixes this.

This feature is available since TypeORM version [0.2.30](https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md#0230-2021-01-12):

> ## 0.2.30 (2021-01-12)
>
> ### Features
>
> * relations: Orphaned row action (#7105) (efc2837)

You should be able to achieve what you want by:

```ts
@ChildEntity('business')
export default class BusinessGeolocation extends Geolocation {
  @ManyToOne(
    type => Business, business => business.geolocations, {
      onDelete: 'CASCADE',
      orphanedRowAction: "delete" // NEW
    })
  business!: Business;
}
```

**Comment by kareemarafa** [comment]
Awesome I've just used it
`
@Column()
  modelId: string;
  @ManyToOne(() => Model, (model: Model) => model.modelSpecs, {
    primary: true,
    onDelete: "CASCADE",
    orphanedRowAction: 'delete'
  })
  @JoinColumn({ name: "modelId" })
  model: Model;
`

**Comment by phil294** [comment]
I think this can be closed now @RobbieGM
