### ISSUE TITLE
TypeORM Release Schedule?

### ISSUE THREAD

**Issue by pirouet** [typeorm/typeorm#6383]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Just a question to ask what the release schedule is like for TypeORM? Is it ad-hoc or is there somewhere that shows what to expect? 

There is an issue - selfishly - that I need fix and waiting on my merge request being accepted that is stopping me from deploying in a Production environment

Thanks,
Michael

**Comment by 0xCAP** [comment]
I think you should really take a look at: [this](https://github.com/typeorm/typeorm/issues/3267)

**Comment by imnotjames** [comment]
I think your PR got merged in or closed - either way -- for bugfixes and non-backwards compatible breaks it's kinda.. as needed.  For larger-term it's "when it's ready" :) Hope that helps!

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
