### ISSUE TITLE
Parse connection string when password contains slash "/"

### ISSUE THREAD

**Issue by karladler** [typeorm/typeorm#6385]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Having a slash in the DB password will break the connection string parsing.

This could be avoided searching for the last slash in[ this line ](https://github.com/typeorm/typeorm/blob/master/src/driver/DriverUtils.ts#L69)instead of the second one.
But I'm not sure what else could break here.

Anyways it's probably more reliable to utilize the `new URL(connectionString)` [constructor](https://nodejs.org/api/url.html) from node here. Also this would throw if there is a slash in the password, so I'm not sure if it's actually allowed at all to have a slash in a postgres password, or if the limitation comes here from the connection string parser.

```ts 
const secondSlash = preBase.indexOf("/");  // remove
const secondSlash = preBase.lastIndexOf("/");  // add
```

**Comment by RobbieGM** [comment]
Just make sure to URL-encode your password. `/` becomes `%2F`.

**Comment by imnotjames** [comment]
We really do want to use the `URL` constructor!  Unfortunately, we have a number of users that pull in TypeORM for browser-based projects.  Not to fear, though! I'm hoping we can work around that in the near future :)  Once we can verify as part of CI that we aren't breaking the browser we can be a bit more adventurous - and that's before we even start getting into splitting up the drivers from core!

And @RobbieGM is right - escape the `/` and you're good to go!

```javascript
console.log((new URL('postgres:foo:bar%2Fbar@baz/hello')).password);
// logs `bar/bar`

console.log((new URL('postgres:foo:bar/bar@baz/hello')).password);
// Throws an error!
```

What's even worse is that in a browser context..

```javascript
console.log((new URL('postgres:foo:bar/bar@baz/hello')).password);
// Emits an empty string for password & puts everything into the pathname!
```
