### ISSUE TITLE
Unable to run migration using Docker Postgres (ENOTFOUND)

### ISSUE THREAD

**Issue by medeiroshudson** [typeorm/typeorm#6387]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Im unable to run any migration using docker-compose + postgres setup. Giving the error:

`PS C:\_dev\RM_EletroMec\backend> npx typeorm migration:run
Error during migration run:
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'postgres'
}`

docker-compose.yml:

`version: "3"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - database
    networks:
      - default

  database:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rm_eletromec"
      PGDATA: /tmp
      TZ: "GMT-3"
      PGTZ: "GMT-3"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/rm_eletromec?sslmode=disable
    depends_on:
      - database
    networks:
      - default
`

ormconfig.json:

`{
  "type": "postgres",
  "host": "database",
  "port": 5432,
  "username": "postgres",
  "password": "postgres",
  "database": "rm_eletromec",
  "entities": ["src/app/models/*.ts"],
  "migrations": ["src/database/migrations/*.ts"],
  "cli": { "migrationsDir": "src/database/migrations/" }
}`

`OBS: On app startup, i'm sucessfully connecting with database`

**Comment by asomethings** [comment]
You'll have to execute command inside the container since 'postges' will only be available inside docker containers. 

If you want to connect it outside of the container, you should change DATABASE_URL to `postgres://postgres:postgres@127.0.0.1:5432/rm_eletromec?sslmode=disable`
