### ISSUE TITLE
Class table inheritance error: column "…" of relation "…" does not exist

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#639]
Hello!

I'm trying to use class table inheritance with the existing schema.

My entities are defined this way:

```typescript
@Entity('products')
@TableInheritance('class-table')
@DiscriminatorColumn({ name: 'type', type: 'string'})
export class Product {

  @PrimaryGeneratedColumn()
  id?: number;

  @Column()
  sku?: string;

  // …

}
```

```typescript
@ClassEntityChild('products_periodic')
@DiscriminatorValue('periodic')
export class PeriodicProduct extends Product {

  @Column()
  duration?: string;

  // …

}
```

My schema is defined like this:

```sql
--------------
-- PRODUCTS --
--------------

-- SEQUENCE --
CREATE SEQUENCE seq_products_id;

-- TABLE --
CREATE TABLE products (

  -- COLUMNS --
  id                integer  NOT NULL DEFAULT nextval('seq_products_id'::regclass),
  sku               text,

  -- PRIMARY KEY --
  CONSTRAINT pk_products
  PRIMARY KEY (id)

);

-- SEQUENCE OWNER --
ALTER SEQUENCE seq_products_id OWNED BY products.id;


------------------------
-- PRODUCTS: PERIODIC --
------------------------

-- TABLE --
CREATE TABLE products_periodic (

  -- COLUMNS --
  id                       integer  NOT NULL,
  duration                 text     NOT NULL,

  -- PRIMARY KEY --
  CONSTRAINT pk_products_periodic
  PRIMARY KEY (id),

  -- FOREIGN KEYS --
  CONSTRAINT fk_products_periodic_id
  FOREIGN KEY (id)
  REFERENCES products
  ON DELETE CASCADE

);
```

TypeORM throws this error when I'm trying to persist a child entity:

- `column "productsId" of relation "products_periodic" does not exist`.

It looks like TypeORM expects my column to be named `productsId` (however it's named just `id`).

**How do I tell it what actual column name to use?**

---

I'm also using this naming strategy:

```typescript
@NamingStrategy()
export class SnakeCaseNamingStrategy extends DefaultNamingStrategy implements NamingStrategyInterface {
  columnName (propertyName: string, customName: string): string {
    return customName ? customName : snakeCase(propertyName);
  }
}
```

However, it looks like it's not respected in this matter, because TypeORM is looking for `productsId` instead of `products_id`.

---

Thank you!

**Comment by pleerock** [comment]
`naming strategy` is undocumented and unfinished functionality, thats why avoid using it yet.

Same I can say about single and class table inheritance patterns - there are lot of problems around them which at the moment hard to fix.

**Comment by slavafomin** [comment]
Sorry to hear that @pleerock. We are using predefined database schema, so we can't integrate TypeORM without using the naming strategy. However, our implementation of naming strategy works fine for our use-case. This was the only problem I've encountered with it.

Actually, we've invested a lot of resources in using TypeORM in our new project, so I'm really interested in overcoming these limitations. Could you please advise me on how to handle table inheritance problem with TypeORM in most effective and supported (stable) way? We have a couple of entities, which will greatly benefit from being split among several tables/classes. For example, we have a `financial operation`, which could take a lot of different forms. Right now we have at least four child classes for it. How do we tackle it?

And once again, thank you for your time, your efforts are very highly appreciated! :+1:

**Comment by pleerock** [comment]
you can simulate what single/class-table inheritance do with regular inheritance (e.g. `A extends B`), with embeds and with just regular columns and relations. It will be better and more stable way of doing things

**Comment by slavafomin** [comment]
I'm not sure I've completely understood your suggestion. Could you please provide a simple example?

For example, I have this schema:

```sql
--------------------------
-- FINANCIAL OPERATIONS --
--------------------------

-- SEQUENCE --
CREATE SEQUENCE seq_financial_operations_id;

-- TABLE --
CREATE TABLE financial_operations (

  -- COLUMNS --
  id          integer  NOT NULL DEFAULT nextval('seq_financial_operations_id'::regclass),
  account_id  integer  NOT NULL,
  type        text,
  amount      numeric (15, 4),
  created_at  timestamp with time zone  NOT NULL DEFAULT now(),
  comment     text,

  -- PRIMARY KEY --
  CONSTRAINT pk_financial_operations
  PRIMARY KEY (id),

  -- FOREIGN KEYS --
  CONSTRAINT fk_financial_operations_account_id
  FOREIGN KEY (account_id)
  REFERENCES accounts
  ON DELETE CASCADE

);

-- SEQUENCE OWNER --
ALTER SEQUENCE seq_financial_operations_id OWNED BY financial_operations.id;


------------------------------------
-- FINANCIAL OPERATIONS: EXTERNAL --
------------------------------------

-- TABLE --
CREATE TABLE financial_operations_external (

  -- COLUMNS --
  id              integer  NOT NULL,
  provider        text     NOT NULL,
  number          text,
  account_number  text,

  -- PRIMARY KEY --
  CONSTRAINT pk_financial_operations_external
  PRIMARY KEY (id),

  -- FOREIGN KEYS --
  CONSTRAINT fk_financial_operations_external_id
  FOREIGN KEY (id)
  REFERENCES financial_operations
  ON DELETE CASCADE

);
```

How should my classes look like? Or do I need to change the schema as well? (I would rather not though)

**Comment by pleerock** [comment]
Try to figure it out. Simply create entities with columns and setup relations. Checkout examples and tests about embeds - maybe this functionality will help you

**Comment by pleerock** [comment]
Class table inheritance support will be completely dropped in 0.2.0 due to complexity and value it brings. There are no plans to add CTI support in the near future as well. You can still use single table inheritance, concrete table inheritance or inheritance via embeddeds
