### ISSUE TITLE
Not Connecting to MariaDB CommonJS error

### ISSUE THREAD

**Issue by 0x1mastermind** [typeorm/typeorm#6394]
**Issue type:**

[] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**DatabaseConnector.ts**
```js
export class DatabaseConnector {

    /**
     * Initializes the Database Connection
     */
    static async init() {
        console.log("Intializing Database Connection")
        console.log(`The dirname variable contains: ${__dirname}`)

        // Intializes the connection object, creating some conenction
        connection = await createConnection({
            type: "mariadb",
            host: Config.db_host || "localhost",
            port: Config.db_port || 3306,
            username: Config.db_user || "root",
            password: Config.db_pass || "",
            database: Config.db_name || "testdb",
            entities: [
                __dirname + "/Entities/*.js"
            ],
            synchronize: Config.db_sync || true,
            logging: Config.db_logging || false,
        })

        // Check if we're connected to database
        if (!connection.isConnected) {
            console.log("Ocurred an error when connecting to database!");
            // Exit the entire application because without an database there's no application
            exit(1);
        }
    }


    /**
     * Returns the database connection object
     */
    static async getConnection() {
        return await connection;
    }
}
```

**app.ts**

```js
import { CommandManager } from "./controllers/CommandManager"
import { Client } from "discord.js"
import { ConfigManager } from "./config/ConfigManager"
import { DatabaseConnector } from "./controllers/DatabaseConnector"

// Intialization of Managers
CommandManager.init();
ConfigManager.init();
DatabaseConnector.init();


// Const Objects
const client = new Client();
const config = ConfigManager.get_config();
const connection = DatabaseConnector.getConnection();

// More Code ....
```

ERROR: 

```
import { createConnection } from "typeorm";
         ^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'typeorm' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'typeorm';
const { createConnection } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:162:24)
```

```json
{
    "compilerOptions": {

        "target": "ESNext", 
        "module": "ESNext"
// More Below
}
} 
```

**Comment by 0x1mastermind** [comment]
?

**Comment by PaDreyer** [comment]
I think that maybe your Import in DatabaseConnector.ts is wrong

**Comment by riyadshauk** [comment]
I have the same problem.

**Comment by riyadshauk** [comment]
I got it (my related problem of my server codebase not running with the current TypeORM setup) working. To get it working, I did the following:
1. Take a look at https://github.com/typeorm/typeorm#quick-start , then do: `npx typeorm init --name typeorm-example-demo --database sqlite # use sqlite just to avoid additional DB setup/config`.
2. Replace my `tsconfig.json` with `typeorm-example-demo/tsconfig.json`.
3. Remove `"type": "module"` from my `package.json` (since `typeorm-example-demo/package.json` doesn't have it).
4. Rather than transpiling to JavaScript and using `ESNext`, simply `npm install ts-node`.
5. Modify the `"start": "node --es-module-specifier-resolution=node ./transpiled-entry-file.js` script to a simple `npx ts-node ./typescript-entry-file.ts`.
6. Run `npm start`, and it works (I get past this problem, at least on my codebase).

**Comment by imnotjames** [comment]
This isn't a TypeORM issue, this is an environment configuration issue.

For support of that nature, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
