### ISSUE TITLE
Issue in generic repository when extending BaseEntity and using getRepository

### ISSUE THREAD

**Issue by jeromeSH26** [typeorm/typeorm#6400]
Hi,

I have an issue in typescript when  creating a generic repo.
I want to enforce typing by enforcing the TEntity generic type to extend BaseEntity as follows :
```

@EntityRepository()
export class ClsGEntitiesRepository<TEntity extends BaseEntity> {
	private _dbConnection: Connection;
	private _entity: TEntity;

	constructor(entity: TEntity,  dbConnection: Connection) {
		this._dbConnection = dbConnection;
		this._entity = entity;
	}

```

However, when trying to use the getRepository, typescript is complaining when passing the Entity as the parameter of this function

error : **Type 'BaseEntity' is not assignable to type 'string | Function | (new () => TEntity) | EntitySchema<TEntity>'.**

```
const rootQuery = this._dbConnection
			.getRepository<TEntity>(this._entity)  <--error 
			.createQueryBuilder()

```

This is quite annoying, as I need to pass a string, which represents the name of the Entity (which is a class) as a workaround.

The weird thing is that if I use this method in a non generic class, it works fine. As you can see below the entity "TestEntity" is extending BaseEntity and I can use it in the getRepo with no issue

```
@Entity({
	name: "testentity",
})
export class TestEntity extends BaseEntity implements ITestEntity {
	@PrimaryColumn({
		type: "uuid",
		nullable: false,
	})
	resourceId: string;
	@Column({
		type: "float",
		nullable: true,
		default: 0.0,
	})
	value: number;
}


	const a = dbConnection
	.getRepository<TestEntity>(TestEntity) <--no error
	.createQueryBuilder()

```

What am I missing here ?

**Comment by tripodsgames** [comment]
Have you tried using getCustomRepository?
https://github.com/typeorm/typeorm/blob/master/docs/custom-repository.md

**Comment by jeromeSH26** [comment]
@tripodsgames
Thks for the information but I found a solution using  ObjectType when defining the entity in parameter:

```
@EntityRepository()
export class ClsGEntitiesRepository<
	TEntity extends BaseEntity
> extends Repository<TEntity> {
	private _dbConnection: Connection;
	private _entityName: string;
	private _entity: ObjectType<TEntity>; <--this fixed the issue

	constructor(entity: ObjectType<TEntity>, dbConnection: Connection) {
		super();
		this._dbConnection = dbConnection;
		this._entity = entity;
		this._entityName = this._dbConnection.getMetadata(this._entity).name;
	}
}

//example of usage
const TestEntityRepository = new ClsGEntitiesRepository<TestEntity>(
		TestEntity,
		getConnection()
	);

```

However now I have another problem, with types
I have created an Entity implementing an interface.
BUT, I can not straight save an object of this interface in the entity, I have to cast it first and then can insert it.
I do not understand why TypeScript is complaining as the entity is implementing the interface.

To reproduce the error

```
import { BaseEntity, Column, Entity, PrimaryColumn } from "typeorm";

interface ITest {
	id: string;
	val: number;
}

@Entity({
	name: "theentity",
})
class TheEntity extends BaseEntity implements ITest {
	@PrimaryColumn({
		type: "character varying",
		nullable: false,
		default: "def",
	})
	id: string;

	@Column({
		type: "bigint",
		nullable: true,
	})
	val: number;
}

const record: ITest = {
		id: "id1",
		val: 2,
	};

const records: ITest[] = [record];

// TheEntity.save(records); <--complains

TheEntity.save(records as TheEntity[]); <--not complains and inserting fine in the table

```

**Comment by imnotjames** [comment]
Looks like this has been resolved!

**Comment by odravison** [comment]
Hey, guys!
I know this is a closed issue but I think that is the perfect issue to get this information.
Can anyone of you help me to figured out how to do some of this here:

![image](https://user-images.githubusercontent.com/7316524/130540895-6d07e4ae-8ae7-486f-9347-4cddefc07cf0.png)

What I'm trying to do is a service that contains all crud operations using a entity type that extends `BaseEntity`.
But only I can reach this few methods from `BaseEntity` and I don't know why.

The goals is to reduce code in services.

Can anyone help me with this?
