### ISSUE TITLE
Does TypeORM have a way to perform bulk updates?

### ISSUE THREAD

**Issue by jaequery** [typeorm/typeorm#6403]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Does TypeORM have a way to perform bulk updates?

I'd like to update multiple records at a time, like repository.update([item1, item2, item3]). Is this possible without resorting to createQueryBuilder()?

**Comment by rubiin** [comment]
I have left a comment on your latest. please close this one
