### ISSUE TITLE
How to apply a 'where' condition without selecting the column?

### ISSUE THREAD

**Issue by codgician** [typeorm/typeorm#641]
Hi, there!

I'd like to achieve something like:
``` sql
SELECT id, problemid, title FROM problem WHERE title LIKE %keyword% OR description LIKE %keyword%
```
And I tried using the following code with TypeORM:
``` typescript
const searchResult = await problemRepository
                            .createQueryBuilder('problem')
                            .select([
                              'problem.id',
                              'problem.problemid',
                              'problem.title',
                            ])
                            .having(`problem.title LIKE '%${query}%'`)
                            .orHaving(`problem.description LIKE '%${query}%'`)
                            .orderBy('problem.problemid', 'ASC')
                            .getMany();
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(searchResult);
    });
  });
```

However it fails to run, saying "ER_BAD_FIELD_ERROR: Unknown column 'problem.description' in 'having clause'".

Since the "description" is often large, I am not willing to response this to my customers.  I'm wondering the right way to achieve that.

I really appreciate your help and thanks for your amazing project.

**Comment by pleerock** [comment]
if you want same sql as you posted you must use `where` instead of `having`. You are using having and not selecting data - its expected behaviour - same wont work with sql.

**Comment by codgician** [comment]
@pleerock Thanks dude!

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by codgician** [comment]
@pleerock Thanks dude!

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by codgician** [comment]
@pleerock Thanks dude!

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by codgician** [comment]
@pleerock Thanks dude!

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by codgician** [comment]
@pleerock Thanks dude!

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
