### ISSUE TITLE
TypeORM bulk updates

### ISSUE THREAD

**Issue by jayrella** [typeorm/typeorm#6411]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[x] postgres
[ ] cockroachdb
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

TypeORM version:

[x] latest
[ ] @next
[] 0.2.11

I have an entity with student and their marks. I have to update the marks for each student.

``ID(PK) --- StudentID --- Mark1 --- Mark2``
``101. ---------    1  -------  20 -----  30``
``102. ---------   2 ------- 30  -----  50``
``103. ---------   3  ------- 35  -----  30``
``104. ---------   4 ------- 70  -----  90``

Below are the latest values to be updated

 ``[{ studentID:1, Mark1:20, Mark2:25},{ studentID:2, Mark1:35, Mark2:55},{ studentID:3, Mark1:45, Mark2:65}]``

So what is the efficient way to bulk Update?

**Comment by rubiin** [comment]
you can use upsert method. For that try using querybuilder and so something like this
```
 await transactionalEntityManager
        .createQueryBuilder()
        .insert()
        .into(your model)
        .values(your-values-array)
        .onConflict(
          `("idx") DO UPDATE SET "Mark2" = excluded."Mark2"
        )
        .execute();

```

**Comment by rubiin** [comment]
for questions , you can join slack

**Comment by imnotjames** [comment]
What rubiin said - 

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
