### ISSUE TITLE
One-to-one relation with entity schema

### ISSUE THREAD

**Issue by ghost** [typeorm/typeorm#6419]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

## I have the following schemas:

```json
{
  "name": "org",
  "columns": {
    "id": {
      "primary": true,
      "type": "int",
      "generated": true,
      "unsigned": true
    },
    "org_type_id": {
      "type": "int"
    }
  },
  "relations": {
    "org_type": {
      "target": "org_type",
      "type": "one-to-one"
    }
  }
}
```
and

```json

{
  "name": "org_type",
  "columns": {
      "id": {
          "primary": true,
          "type": "int"
      },
      "name": {
          "type": "varchar",
          "length": 255,
          "nullable": true,
          "default": null
      },
  },
  "relations": {
    "org": {
      "target": "org",
      "type": "one-to-one"
    }
  }
}

```
Trying to join the tables:

```js

      const organization = await connection
      .getRepository('org')
      .createQueryBuilder('org')
      .innerJoinAndSelect('org_type', 'org_type', 'org_type.id = org.org_type_id')
      .where('org.org_type_id IN (:ids)', { ids: [1, 2] })
      .andWhere('org.id = :id', { id })
      .orWhere('org.id = :parent_org_id', { parent_org_id: parentOrgId })
      .getOne();
```

But get results from the org table and no joined data from the org_type table
Thanks in advance!

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
