### ISSUE TITLE
Role management issue.

### ISSUE THREAD

**Issue by ArtGurianov** [typeorm/typeorm#6425]
[x ] question
[x ] `postgres`
[x ] `latest`

Hi Guys. Would someone please recommend me, what is the best (or possible) way to save new user conditionally to different repository based on his role?

The best option would be something like:
```
async register(data) {
user = await userRepo.save(data.email, data.password, data.roleName)
savedEntityRole = await client.somehowDynamicallyAccessRepoByRoleName(data.roleName).save(user.id)
```

I really don't want to do it like so:
```
async register(data) {
    user = await userRepo.save(data.email, data.password, data.role)

    if (data.role === 'customer') {
        await client.getRepository(Customer).save(user.id)
    } else if (data.role === 'distributor') {
        await client.getRepository(Distriburor).save(user.id)
    } else if (...) {
        ...
    } else if (....) {
        ...
    } else if (...) {...}
}
```

**Comment by imnotjames** [comment]
Hi there!  For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
