### ISSUE TITLE
AfterInsert use dababase function (Postgresql)

### ISSUE THREAD

**Issue by dobicz** [typeorm/typeorm#6437]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.24` 

I have an entity with two fields, content: type text and contentTSV type: tsvector, contentTSV is populate with content value tsvector.

How to use AfeterInsert for convert the content value to tsvector and populate field contentTSV?

**Comment by imnotjames** [comment]
I don't think you need to do `@AfterInsert` - you'd want to update before performing the insert.

Before you insert you can assign the data from the `content` field into the `contentTSV` field.
