### ISSUE TITLE
DriverPackageNotInstalledError: SQLite package has not been found installed. Electron, only in MacOS production builds

### ISSUE THREAD

**Issue by rathboma** [typeorm/typeorm#6439]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I make an electron app called [Beekeeper Studio](https://github.com/beekeeper-studio/beekeeper-studio), and we've been using typeorm successfully for 6 months.

This last release we started using typeorm not just in the renderer (front end) code, but also in the background code (main electron process). The code for both front and backends is built with webpack and babel.

This works fine during development, and works fine in our Windows and Linux production builds.

Weirdly, for MacOS production builds it does NOT work and produces the familiar error [DriverPackageNotInstalledError: SQLite package has not been found installed](https://github.com/beekeeper-studio/beekeeper-studio/issues/249)

We're totally at a loss as to why this only happens on MacOS. I've confirmed that the sqlite packages are in the `node_modules` folder. You can see our [webpack config here](https://github.com/beekeeper-studio/beekeeper-studio/blob/master/vue.config.js).

I've posted an issue on [vue-cli-electron-builder also](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/914), just hoping someone understands why this happens.

### Reproducing

Here's the DMG file with the issue: https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v1.6.4/Beekeeper-Studio-1.6.4.dmg

You can run it from the terminal to see the problem:

`/Applications/Beekeeper\ Studio.app/Content/MacOS/Beekeeper\ Studio`

Any thought or things we can try would be appreciated.

Matthew

**Comment by rathboma** [comment]
I figured it out. The TypeORM error was a red herring. It was a Mac notarization issue. Here's my one line fix:

https://github.com/beekeeper-studio/beekeeper-studio/commit/691357bda09121b01efe72419244821f468fe551

If anyone else has this issue, hope this helps, good luck!

**Comment by DerekRein** [comment]
@rathboma This was the exact fix for the same issue. Thank you for sharing!
