### ISSUE TITLE
How can I extend generic function in AbstractRepository using FindConditions<T>?

### ISSUE THREAD

**Issue by peterkimzz** [typeorm/typeorm#6443]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'd like to make base abstract entity and repository, and almost inheritance of AbstractRepository function works good.

But, some AbstractRepository function using `FindConditions<T>` throws type compatible error.

```ts
// entities/index.ts
interface IRootEntity {
  id: number
  uuid: string
  created_at: Date
  updated_at: Date
  deleted_at: Date
}
export abstract class RootEntity implements IRootEntity {
  @PrimaryGeneratedColumn()
  id!: number

  @Column()
  uuid!: string

  @CreateDateColumn()
  created_at!: Date

  @UpdateDateColumn({ onUpdate: 'CURRENT_TIMESTAMP(6)' })
  updated_at!: Date

  @DeleteDateColumn()
  deleted_at!: Date
}

// repositories/index.ts
export abstract class RootRepository<T extends RootEntity> extends AbstractRepository<T> {

  // OK, but I don't think it is not a good solution because it is not type safety :(
  public async UpdateByUuid(uuid: string, schema: QueryDeepPartiaEntity<T>) {
    return this.repository
        .createQueryBuilder()
        .update(schema)
        .where('uuid = :uuid', { uuid })
        .execute()
  }

  // ERROR: first parameter of `update()` is the issue. Compiler said `uuid: string` type is not compatible in FindConditions<T>
  public async UpdateByUuid(uuid: string, schema: QueryDeepPartiaEntity<T>) {
    return this.repository.update({ uuid }, schema)
  }
}
```

**Comment by imnotjames** [comment]
Try `return this.repository.update({ where: { uuid } }, schema)`

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
