### ISSUE TITLE
Sync migration tools from oracle to Microsoft SQL Server

### ISSUE THREAD

**Issue by nimai123** [typeorm/typeorm#6445]
We can use SSMA to migrate Oracle to SQL Server on-premise but I am unaware which tools I can use to maintain the sync for 20 TB huge database.

Can anyone help me out here?

Thanks in advance.

**Comment by imnotjames** [comment]
I don't think this is related to TypeORM. Perhaps look into Kafka Connect.

**Comment by nimai123** [comment]
Can you direct me towards that root or link maybe?

**Comment by imnotjames** [comment]
Here's a blog post that might help you do what you want https://www.confluent.io/blog/no-more-silos-how-to-integrate-your-databases-with-apache-kafka-and-cdc/
