### ISSUE TITLE
No repository was found.

### ISSUE THREAD

**Issue by samueldurantes** [typeorm/typeorm#6446]
Every time I try to create a Postgres record using Typeorm, it returns this:
```json
{
  "error": "No repository for \"User\" was found. Looks like this entity is not registered in current \"default\" connection?"
}
```
I configure using environment variables, would this cause this type of error?

**Comment by imnotjames** [comment]
It sounds like you aren't defining where the entities should be loaded from.

What environment variables are you setting?

If you can't share the environment variables, maybe try making a minimal example that reproduces the issue that you can share?

**Comment by grbspltt** [comment]
I have been running into this lately, but usually if I have a request come in right as the application is starting up.  Any request a second or two later will succeed.

**Comment by samueldurantes** [comment]
I use these settings
```
TYPEORM_CONNECTION=postgres
TYPEORM_HOST=localhost
TYPEORM_PORT=5432
TYPEORM_USERNAME=postgres
TYPEORM_PASSWORD=postgres
TYPEORM_DATABASE=postgres
TYPEORM_MIGRATIONS=core/database/migrations/*.ts
TYPEORM_MIGRATIONS_DIR=core/database/migrations
```

**Comment by grbspltt** [comment]
Do you have this set in env variables? Check docs: [Using environment variables](https://typeorm.io/#using-ormconfig/using-environment-variables)

`TYPEORM_ENTITIES = entity/*.js,modules/**/entity/*.js`

Or this may go into ormconfig file

**Comment by samueldurantes** [comment]
I set the variable `TYPEORM_ENTITIES=core/entity/**/*.ts`, and the error persisted...

**Comment by imnotjames** [comment]
Is the source available anywhere of what you're working on? 

I also believe that the value of the environment variable should be from the current working directory - where you're running this from.

**Comment by samueldurantes** [comment]
https://github.com/akaryos/api/tree/ts

**Comment by imnotjames** [comment]
I checked out the repository and was able to run it from the root via `npm run dev` with the `.env` containing as follows

```
TYPEORM_CONNECTION=sqlite
TYPEORM_DATABASE=./sqlite.db
TYPEORM_MIGRATIONS=core/database/migrations/*.ts
TYPEORM_MIGRATIONS_DIR=core/database/migrations
TYPEORM_ENTITIES=core/entity/**/*.ts
```

**Comment by imnotjames** [comment]
Ah, because your directory to the entities is not `core/entity`, the following will work:

```
TYPEORM_ENTITIES=core/model/**/*.ts
```

Cheers!

**Comment by samueldurantes** [comment]
Were you able to create the record in the database?

**Comment by imnotjames** [comment]
All I did was a `curl -X POST 127.0.0.1:8080/users` - It ended up with an error `{"error":"No entity column \"where\" was found."}`
