### ISSUE TITLE
how to check if db is out of sync for CI

### ISSUE THREAD

**Issue by darrenjennings** [typeorm/typeorm#6449]
**Issue type:**

[x] question

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[ ] `0.2.21` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

What is the best way to check if the db is out of sync? For example, if a pull request adds or changes the schema, then they should provide a migration file. We would like to automate this check by making sure that there will be no out of sync entities merged in. Should we just check exit code of `yarn typeorm schema:log | grep "schema is up to date"`?

**Comment by imnotjames** [comment]
Schema log is your best bet 

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
