### ISSUE TITLE
TypeORM Subscriber AfterInsert Can't Find Record

### ISSUE THREAD

**Issue by tvl83** [typeorm/typeorm#6450]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a few Entities `Action`, and `GPKAsset` 

### Action.ts
```typescript
export class Action extends BaseEntity {

	@PrimaryGeneratedColumn()
	id: number;

REMOVED COLUMNS AND OTHER RELATIONSHIPS TO REDUCE CLUTTER

	@ManyToMany(() => GPKAsset, gpkAsset => gpkAsset.actions)
	gpkAssets: GPKAsset[];
```

### GPKAsset.ts
```typescript
@Entity("gpk_assets")
export class GPKAsset extends BaseEntity {

	@PrimaryGeneratedColumn()
	id: number;

	@Index()
	@Column()
	contract: string;

REMOVED COLUMNS AND OTHER RELATIONSHIPS TO REDUCE CLUTTER

	@ManyToMany(() => Action, action => action.gpkAssets)
	@JoinTable({name:'gpkassets_actions'})
	actions: Action[];
```

### ActionSubscriber.ts
```typescript

@EventSubscriber()
export class ActionSubscriber implements EntitySubscriberInterface<Action> {
	listenTo() {
		return Action;
	}

	async afterInsert(event: InsertEvent<Action>): Promise<Promise<any> | void> {

		let action: Action = event.entity;
		switch (event.entity.contract) {
			case 'simpleassets:createlog':
				let gpkAsset: GPKAsset | null = new GPKAsset();
				gpkAsset = await gpkassetManager.createGPKAssetFromAction(action);
				await actionManager.addRelationAccount(action);
				if (gpkAsset !== null) {
				     await actionManager.addRelationGPKAsset(action, gpkAsset))
				}
				break;
			case 'simpleassets:transfer':
				await gpkassetManager.transferGPKAssetOwnership(action);
				break;
			default:
		}
	}
}
```

In the `ActionSubscriber.ts` I would like to perform certain things based on the contract column as you can see above. 

The problem I am encountering is on `await actionManager.addRelationAccount(action);` it is throwing exceptions saying that the record doesn't exist in actions. This is quite confusing because I have the id of the action and this is the `afterInsert` event. 

I am guessing either I am doing something very wrong or it's some sort of race condition, or it's a bug? 

Any guidance would be greatly appreciated. 

Thank you

**Comment by tvl83** [comment]
I put the same code in an @AfterInsert function and the same thing happens. It cannot find that record to create a relationship. It seems like this method triggers slightly before it's actually committed to the db.

**Comment by hawkeng** [comment]
Having the same issue, the logs show that all the queries are being executed under the same transaction, that's why the record is not found. The question is how to tell the subscriber to execute the command **after** the record was effectively persisted?

![image](https://user-images.githubusercontent.com/5926102/90321950-fff76f00-df13-11ea-8ef7-34eecedbc298.png)


![image](https://user-images.githubusercontent.com/5926102/90321946-f4a44380-df13-11ea-8daa-b376e477303d.png)

**Comment by mfasanya** [comment]
Looks like this is still an issue. We publish to a redis instance, then read from redis and lookup by the id.

Sometimes because it hasn't been committed our redis listener will get undefined when doing a findById.

We don't have access to the entityManager as it is in a background worker. Surely there needs to be a way to publish an event after the record is actually inserted?

**Comment by AlexMesser** [comment]
you must use the same `entityManager` from `event`. https://github.com/typeorm/typeorm/issues/3563#issuecomment-460054971

**Comment by DanielMat97** [comment]
hi, i´m solved error `async afterInsert(event: InsertEvent<Users>): Promise<void> {
    Logger.debug('EVENT-DISPATCH AFTER INSERT USER', event.entity.id);
    try {
      event.connection.transaction(async (trxEntityManager) => {
        await trxEntityManager.save(event.entity);
        await this.usersAssociateService.createUserAssociate(event.entity);
      });
    } catch (error) {
      throw new DatabaseError('Error creating user associate', error.message);
    }
  }`

**Comment by taoliujun** [comment]
Doc say `Note: Do not make any database calls within a listener, opt for [subscribers](https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md#what-is-a-subscriber) instead.`
