### ISSUE TITLE
MongoQueryRunner.databaseConnection is declared with a wrong type

### ISSUE THREAD

**Issue by justin-lau** [typeorm/typeorm#6453]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`MongoQueryRunner.databaseConnection` has the type `Db` while it should actually be `MongoClient`.

Where `databaseConnection` is defined in [src/driver/mongodb/MongoQueryRunner.ts](https://github.com/typeorm/typeorm/blob/9abab82/src/driver/mongodb/MongoQueryRunner.ts#L103-L116):
```ts
    /**
     * Real database connection from a connection pool used to perform queries.
     */
    databaseConnection: Db;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    constructor(connection: Connection, databaseConnection: Db) {
        this.connection = connection;
        this.databaseConnection = databaseConnection;
        this.broadcaster = new Broadcaster(this);
    }
```

Where it is created in [src/driver/mongodb/MongoDriver.ts](https://github.com/typeorm/typeorm/blob/9abab82/src/driver/mongodb/MongoDriver.ts#L219-L235):
```ts
    connect(): Promise<void> {
        return new Promise<void>((ok, fail) => {
            this.mongodb.MongoClient.connect(
                this.buildConnectionUrl(),
                this.buildConnectionOptions(),
                (err: any, client: any) => {
                    if (err) return fail(err);

                    this.queryRunner = new MongoQueryRunner(this.connection, client);
                    ObjectUtils.assign(this.queryRunner, { manager: this.connection.manager });
                    ok();
                });
        });
    }
```

Reference to `mongodb.MongoClient.connect`:
https://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html#~connectCallback

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
I noticed this too!  Very frustrating for typing.
