### ISSUE TITLE
Problem with migrations execution and transactions

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#646]
Hello!

I have a migration which first executes SQL-queries from a file and then creates and persists couple of entities. When I execute these two operations separately, it works correctly. But when I'm trying to do this in one go, I'm getting an error.

Please consider the code below:

```typescript
export class Migration1493717870000 implements MigrationInterface {

  public async up (queryRunner: QueryRunner, connection: Connection): Promise<any> {

    await MigrationHelper.executeSqlFile(__dirname + '/up.pgsql', queryRunner);

    const product = new Product();
    product.title = 'Some Nice Product';
    await connection.entityManager.persist(product);

  }

}
```

```typescript
export class MigrationHelper {
  public static async executeSqlFile (filePath: string, queryRunner: QueryRunner): Promise<void> {
    const sql = await this.readFile(filePath);
    await queryRunner.query(sql);
  }
}
```

The error is this: `relation "products" does not exist`.

My guess is that two different transactions are used for these two operations. I've tried to introduce some manual transaction management, but it's not working either. When I'm trying to do `queryRunner.beginTransaction()`, I'm getting an error: `Transaction already started for the given connection, commit current transaction before starting a new one.`. However, when I try to do `queryRunner.commitTransaction()`, I'm getting `Transaction is not started yet, start transaction before committing or rolling it back.`, which is kinda controversial.

I think the correct solution would be to use the same transaction, that is created for migration initially, however, how do I use it with `connection.entityManager`?

Thank you!

**Comment by pleerock** [comment]
Migration is wrapped into transaction already, you should not create any new transactions. Your problem is that you are using `connection.entityManager`. You you should not use it. Instead `up` provides you `entityManager` that you must use instead (its a different instance of EntityManager used special for current query runner) 

```ts
async up (queryRunner: QueryRunner, connection: Connection, entityManager: EntityManager): Promise<any> 
```

Note that in latest (0.1.0-alpha.33) signature of `up` has changed and now is:

```ts
async up (queryRunner: QueryRunner): Promise<any> 
```

and connection and *isolated entity manager* can be accessed via:

```ts
queryRunner.connection
queryRunner.manager
```

**Comment by slavafomin** [comment]
I see, thanks!

**Comment by slavafomin** [comment]
I've refactored my code to look like this:

```typescript
public async up (queryRunner: QueryRunner): Promise<any> {
  await queryRunner.query(`CREATE TABLE users …`);

  const user = new User();
  await queryRunner.connection.manager.save(user);

}
```

But I'm getting the same error: `error: relation "users" does not exist`.

I'm using `typeorm@^0.1.0-alpha.32`.

Also, there is no `queryRunner.manager` property (at least in version `32`).

**Comment by slavafomin** [comment]
And here's the minimum sample you can use to reproduce the issue:

```typescript
public async up (queryRunner: QueryRunner): Promise<any> {

  // Both works OK.
  await queryRunner.query('CREATE TABLE apples (id SERIAL, variety TEXT)');
  await queryRunner.query('INSERT INTO apples (variety) VALUES (\'Braeburn\')');

  // Throws: error: relation "apples" does not exist
  await queryRunner.connection.query('INSERT INTO apples (variety) VALUES (\'Cortland\')');

}
```

**Comment by pleerock** [comment]
again DONT use `connection.manager`. I'll release `0.1.0-alpha.33` later this week, it has `queryRunner.manager`

**Comment by llwt** [comment]
Can confirm updating to `alpha.33` and using `queryRunner.manager` fixes the issue!

**Comment by pleerock** [comment]
@llwt thank you for confirmation. I think this issue can be closed now
