### ISSUE TITLE
select only passed entity columns through level condition

### ISSUE THREAD

**Issue by aristocr2t** [typeorm/typeorm#6461]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to suggest a feature:

I need to select only passed entity columns through level condition (`entity[column].selectLevel >= findOptions.selectLevel`):

```
// selectLevel can be `undefined` or `unsigned int`
@Entity()
class User {
  @Column('varchar', { selectLevel: 2 })
  name!: string;

  @Column('varchar', { selectLevel: 1 })
  birthdate!: string;

  @Column('varchar', { selectLevel: 0 })
  password!: string;
}

// get short user data:
const userList = await connection.manager.find(User, { selectLevel: 2 }); // [{ id: 1, name: 'Andrew' }]

// get user with profile data:
const user = await connection.manager.findOne(User, { selectLevel: 1 }); // { id: 1, name: 'Andrew', birthdate: '1990-01-01' }

// get private data:
const _user = await connection.manager.findOne(User, { selectLevel: 0 }); // { id: 1, name: 'Andrew', birthdate: '1990-01-01', password: 'oops...' }

```

in `ormconfig.ts`:
```
export = {
  ...someConfig,
  defaultSelectLevel: 1,
}
```

**Comment by aristocr2t** [comment]
or use bitwise strategy, to select more efficiently (`entity[column].selectLevel & findOptions.selectLevel > 0`):
```
@Entity()
class User {
  @Column('varchar', { selectLevel: 0b100 })
  name!: string;

  @Column('varchar', { selectLevel: 0b010 })
  phone!: string;

  @Column('varchar', { selectLevel: 0b001 })
  birthdate!: string;

  @Column('varchar', { selectLevel: 0b000 })
  password!: string;
}
const user = await connection.manager.findOne(User, { selectLevel: 0b001 | 0b100 });
```

**Comment by imnotjames** [comment]
Both of these are very confusing features that were aren't likely to implement.

We provide multiple mechanisms already which implement this (`select: false` + specifying fields you'd like returned back.)

Should you need something more in depth there are projects such as `class-transformer` to accomplish it.

Unless you're planning to implement this, I don't think it makes sense on the roadmap.
