### ISSUE TITLE
Transaction Rollback on Custom Repository Failing

### ISSUE THREAD

**Issue by shravanhariharan2** [typeorm/typeorm#6466]
**Issue type:**

[] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The transactions I'm using on a custom repository don't seem to rollback operations properly (i.e. nothing is being rolled back). The below code inserts two of the same objects into a database under a transaction, The table has a unique field restriction, meaning the second custom repository call will fail. To my understanding, the expected behavior should be that the entire transaction is rolled back and no objects are inserted into the database in the end.

```
const user = await getConnection().transaction(async entityManager => {
      const newUser = await entityManager.getCustomRepository(UserRepository).createUser(userRequest);
      const newUser2 = await entityManager.getCustomRepository(UserRepository).createUser(userRequest);
      return newUser;
    });
return user;
``` 

However, the first user is still inserted into the database.

The database operation logs created by TypeORM show that the transaction is being rolled back, but the first inserted user still exists in the database. 

Any idea what is happening? 

Logs:
![image](https://user-images.githubusercontent.com/33337209/88493593-cc55a480-cf66-11ea-9409-811281700502.png)

![image](https://user-images.githubusercontent.com/33337209/88493557-987a7f00-cf66-11ea-83dc-ed3feffb0d63.png)

**Comment by shravanhariharan2** [comment]
#1521

**Comment by ChandruCR** [comment]
@shravanhariharan2
did you find any solution for this?

**Comment by ChandruCR** [comment]
I am using below workaround for now.

```javascript
export default class Database {
  private static connection: Connection
  private static transactionalQueryRunner: QueryRunner

  public static async connect(): Promise<void> {
    if (!Database.connection.isConnected) {
      Database.connection = await Database.connection.connect()
    } else {
      Database.connection = await createConnection(connectionOptions)
    }
  }

  public static getEntityManager(): EntityManager {
    if (Database.transactionalQueryRunner && !Database.transactionalQueryRunner.isReleased) {
      return Database.transactionalQueryRunner.manager
    }
      return Database.connection.manager
  }

  public static async transaction(method): Promise<void> {
    if (!Database.transactionalQueryRunner?.isReleased) {
      Database.transactionalQueryRunner = Database.connection.createQueryRunner()
      await Database.transactionalQueryRunner.connect()
      await Database.transactionalQueryRunner.startTransaction()
      try {
        await method.apply(this)
        await Database.transactionalQueryRunner.commitTransaction()
      } catch (error) {
        await Database.transactionalQueryRunner.rollbackTransaction()
        throw error
      } finally {
        await Database.transactionalQueryRunner.release()
      }
    } else {
      await method.apply(this)
    }
  }
}

await Database.transaction(() => {
  const userRepository = Database.getEntityManager().getCustomRepository(UserRepository)
  const orderRepository = Database.getEntityManager().getCustomRepository(OrderRepository)
  await userRepository.save({})
  await orderRepository.save({}) 
})
```

[Reference](https://typeorm.io/#/transactions/using-queryrunner-to-create-and-control-state-of-single-database-connection)

**Comment by shravanhariharan2** [comment]
@ChandruCR nope, still no solution. I tried your workaround too and transaction rollbacks still aren't working for me.

Even with this simple query:

```
const queryRunner = this.manager.connection.createQueryRunner();
queryRunner.connect();
queryRunner.startTransaction();
const newUser = await this.repository.create(user).save();
queryRunner.rollbackTransaction();
return newUser;
```
the rollback isn't happening properly. Any thoughts why?

**Comment by ChandruCR** [comment]
@shravanhariharan2 
```javascript
const newUser = await this.repository.create(user).save()
```

Is repository being created from entity manager of the query runner?

**Comment by shravanhariharan2** [comment]
@ChandruCR
 
The `this.repository` refers to the `protected readonly repository: Repository<Entity>;` from `AbstractRepository<Entity>` that my custom `UserRepository` extends. The above call is made within `UserRepository`.

Even when I use `Database.getEntityManager.getCustomRepository(UserRepository)`, the db operation of inserting the user doesn't get rolled back, even though rollback displays in the logs.

However, when I do a raw query:
```
const queryRunner = this.manager.connection.createQueryRunner();
queryRunner.connect();
queryRunner.startTransaction();
await queryRunner.manager.query(<raw query>)
queryRunner.rollbackTransaction();
return newUser;
```
then it rolls back fine.

**Comment by ChandruCR** [comment]
@shravanhariharan2 
Based on what you have mentioned above.

Your repository instance is not created using entity manager from query runner.

If your code is in UserRepository class then this.repository would be using global entitymanager and not from query runner because repository instance was created before starting transaction.

**Comment by asdrian44** [comment]
someone know to use custom repository with injection in constructor in nestJs ?

**Comment by ChandruCR** [comment]
@shravanhariharan2 
I am not sure what below line does in your code snippet
```javascript
const newUser = await queryRunner.manager.getRepository(User).create(user).save();
```

I don't think it has anything to do with when connection is created. at least not for my case.
Below codes works for me. This is a method inside UserRepository.

```javascript
public async test() {
  const queryRunner = this.manager.connection.createQueryRunner();
  await queryRunner.connect();
  await queryRunner.startTransaction();
  const newUser = await queryRunner.manager.getCustomRepository(UserRepository).save({
    email: "email@email.com",
  })
  // await queryRunner.commitTransaction()
  await queryRunner.rollbackTransaction();
  console.log(newUser) // this displays result as expected but database is not committed.
}
```

**Comment by shravanhariharan2** [comment]
So the problem turned out to be that

`await repository.create(entity).save()`

doesn't work under a transaction, regardless of what kind of repository it is (custom or not). To my understanding, this is probably because `repository.create(entity)` returns `BaseEntity`, and `BaseEntity.save()` under the hood calls `getRepository().save(entity)` - a repository not under the query runner or transactional entity manager (see [BaseEntity.ts](https://github.com/typeorm/typeorm/blob/master/src/repository/BaseEntity.ts))

If I do:
```
const entity = repository.create(entity)
await repository.save(entity)
```
in separate calls, regardless of custom/not custom repository, it'll work properly.

Thanks @ChandruCR for your help

**Comment by divmgl** [comment]
Just ran into this. Can confirm that the `Entity` does not keep track of the manager that created it. Seems like a straightforward fix, no? Keep a reference to the creating manager and if it's not available then fallback to the global.
