### ISSUE TITLE
Standalone connection with mysql using typeorm

### ISSUE THREAD

**Issue by bohrasankalp** [typeorm/typeorm#647]
I am trying to create the connection with MySQL using node js with TypeORM. I am expecting to create a standalone connection so I get information about connection as well.

```js
//connection.ts
import {ConnectionManager} from 'typeorm';
import {Photo} from '../entity/Photo';

const c = new ConnectionManager();

export const connection = c.create({
    type          : "mysql",
    host          : "localhost",
    port          : 3306,
    username      : "root",
    password      : "sony",
    database      : "dummy",
    entities      : [
        Photo
    ],
    autoSchemaSync: true,
});

//controller.ts
let photos = connection.getRepository(Photo).find();
console.log(photos);
```

I am getting error repository not found or sometimes connection not found. How would I get information about the connection if it is successful or fails? Do I create pool connection as well?
Even I am getting an error for async and await also.

**Comment by pleerock** [comment]
typeorm setups connection pool for you. You can use a single connection from connection pool if you need that.

> I am getting error repository not found or sometimes connection not found

you do something wrong. Post your code and I'll try to help.

Generally you don't need to use `ConnectionManager`. Calling `createConnection` should be enough for everyone.

**Comment by pleerock** [comment]
typeorm setups connection pool for you. You can use a single connection from connection pool if you need that.

> I am getting error repository not found or sometimes connection not found

you do something wrong. Post your code and I'll try to help.

Generally you don't need to use `ConnectionManager`. Calling `createConnection` should be enough for everyone.

**Comment by bohrasankalp** [comment]
This is the same sample I am trying to implement. Exactly same snippet. I want to log console and files on safe connection and failure as well. So I want it separate to file or some structured way, Give sample if I could have it, along with proper promises.

**Comment by pleerock** [comment]
Talking simple don't do what you are doing. You DONT need to use `ConnectionManager` and store connection on your own. Its already done by ORM. 

Simply call `await createConnection()` once in your app bootstrap and the use `getConnection` (non async) anywhere you need connection in your app.

**Comment by bohrasankalp** [comment]
@pleerock, I tried the same way but I think connection couldn't setup. This time error is `ConnectionNotFoundError ` Do we have a sample of standalone connection, where the connection is separated to file and I use it along with models at several places?

**Comment by pleerock** [comment]
can you please show me your ormconfig.json content and code you are running using `createConnection` ?

**Comment by bohrasankalp** [comment]
I am directly  passing json in createConnection()

**Comment by pleerock** [comment]
then please create a sample git repository with minimal reproduction of this problem and I'll debug it.
