### ISSUE TITLE
How can i insert a entitiy with a relation just passing the relation id?

### ISSUE THREAD

**Issue by uduDudu** [typeorm/typeorm#6472]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following 

```ts

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column()
  username: string;

  @Column()
  password: string;

  @Column()
  is_restaurant_owner: boolean;

  @Column()
  phone: string;

  @CreateDateColumn()
  created_at: Date;

  @UpdateDateColumn()
  updated_at: Date;
}
```

```ts

@Entity()
export class Client {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  rating: number;

   @OneToOne((type) => User)
   @JoinColumn()
   user: User;
}
```

To pass the client user i would have to do things like

```ts
let client = new Client()
client.user.id = "user-id-example" 
```

is there a way of just passing the id of a existing user and typeorm create it? like

```ts
let client = new Client()
client.user_id = "user-id-example"
```

**Comment by timothyvanderaerden** [comment]
You could do the following:

```ts
const user = new User();
user.id = 1;
client.user = user;

// Or if you use a constructor
client.user = new User(user-id-example);
// And then in your User entity define the constructor
@Entity()
export class User {
  // Your columns
  constructor(id?: number) {
    this.id = id;
  }
}
```

**Comment by uduDudu** [comment]
Thanks for helping, i will join the slack
