### ISSUE TITLE
Question on the best way to handle Prices using TypeORM

### ISSUE THREAD

**Issue by NatoNathan** [typeorm/typeorm#6473]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

So I'm new to TypeORM, and I was planing to use the `money` Data type found in `postgres` for my price and cost fields, like so
```ts
@Entity()
export class SalesOrder {
	@PrimaryGeneratedColumn('uuid')
	id: string;
        . . .
	@Column({ type: 'money' })
	totalPrice: number;
}
```
for my app/API, I would like to keep as much precision as much as posable. I was wondering how TypeORM would handle this and how I could use ValueTransformer's to ensure that totalPrice was cast like so ` SELECT totalPrice::numeric::decimal` or ` SELECT totalPrice::decimal::numeric` if needed.
also, this may not be the best way to handle Prices using TypeORM if so please let me know. like should I just use `decimal` and not bother with `money` or will javascript's number type make this point mute?

**Comment by imnotjames** [comment]
I'd go with money but be careful with number type.  It's floating point.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
