### ISSUE TITLE
Inserting on @ManyToMany relationship

### ISSUE THREAD

**Issue by wsporto** [typeorm/typeorm#648]
I have one @ManyToMany relationship between Playlist and Song and populated the database as the following:

Playlist1: [Song1, Song2, Song3]
Playlist2: [Song1]

Now i want to insert Song2 on the Playlist2, whithout loading all the songs.

  
```
      let playlist2 = await Playlist.findOneById(2);
        let song2 = await Song.findOneById(2);
        if(playlist2 && song2) {
            playlist2.songs = [song2];
            await Playlist.save(playlist2);
        }
```

After i run the code above, it removes the Song1 from Playlist2. On issue #593, @pleerock suggested removing the initialization from the relations ( e.g. songs: Song[] =[]; replace to songs: Song[];), but that dont seem to work.

```
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity, ManyToMany, JoinTable } from 'typeorm';
import { Song } from './Song';

@Entity()
export class Tracklist {

    constructor(name:string) {
        this.name = name;
    }
    
    @PrimaryGeneratedColumn()
    id: number;
   
    @Column()
    name: string;

    @ManyToMany(type => Song, song => song.tracklists, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    @JoinTable({name: "tracklist_song"})
    songs: Song[];
}
```

```
import { Entity, PrimaryGeneratedColumn, Column, ManyToMany, BaseEntity } from 'typeorm';
import { Playlist } from './Playlist';

@Entity()
export class Song extends BaseEntity {

    constructor(name:string) {
        super();
        this.name = name;
    }

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToMany(type => Playlist, playlist => playlist.songs, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    playlists: Playlist[];

}
```

I created one minimal project that reproduces that issue [here](https://github.com/wsporto/typeorm-many-to-many).

**Comment by pleerock** [comment]
> After i run the code above, it removes the Song1 from Playlist2

that is expected behaviour. You had `[Song1]`. Now you did `[Song2]`. ORM thinks you removed `[Song1]` because its missing in the array. Otherwise there is no way for ORM to determine if you removed something or not. If you want to change many-to-many relations you must load it.

**Comment by FreakTheMighty** [comment]
@pleerock is there a more efficient way to add a relation? Loading all relations could be expensive and seems unnecessary if all you want to do is add a row to the join table.

**Comment by FreakTheMighty** [comment]
Nevermind, I found these docs

```
import {getConnection} from "typeorm";

await getConnection()
    .createQueryBuilder()
    .relation(Post, "categories")
    .of(post)
    .add(category);
```

**Comment by mrnagydavid** [comment]
https://github.com/typeorm/typeorm/blob/master/docs/relational-query-builder.md

**Comment by NaturesProphet** [comment]
very helpfull thanks

**Comment by JaosnHsieh** [comment]
> Nevermind, I found these docs
> 
> ```
> import {getConnection} from "typeorm";
> 
> await getConnection()
>     .createQueryBuilder()
>     .relation(Post, "categories")
>     .of(post)
>     .add(category);
> ```

add limit(1) to it doesn't work.


```javascript

 await getConnection()
     .createQueryBuilder()
     .limit(1)
     .relation(Post, "categories")
     .of(post)
     .add(category);
 ```



```
```javascript
      "pg": "^7.3.0",
      "typeorm": "0.2.25"
```

**Comment by smitbarmase** [comment]
@wsporto You can also use the push method, to prevent overwriting.
```js
import {getRepository} from "typeorm";

const postRepository = getRepository(Post);
const post = await postRepository.findOne(1, { relations: ["categories"] });
post.categories.push(category);
await postRepository.save(post);
```

Read more about it here: [Working with Relations](https://orkhan.gitbook.io/typeorm/docs/relational-query-builder) 😊

**Comment by kfrajtak** [comment]
Having a join table defined as 
```
@ManyToMany(() => User)
  @JoinTable({
    name: "m_user_group_membership",
    joinColumns: [
      {
        name: "idUserGroup",
        referencedColumnName: "id"
      }
    ],
    inverseJoinColumns: [
      {
        name: "idUser",
        referencedColumnName: "id"
      }
    ]
  })
  users: User[];
```
and no extra settings, the INSERT fails because TypeORM is adding two extra columns (`userId`, `groupId`) which do not exist in the table and I don't know where they came from:
```
INSERT INTO `m_user_group_membership`(`idUserGroup`, `idUser`, `userId`, `groupId`) VALUES (1, '105', DEFAULT, DEFAULT)
```

**Comment by ertankara** [comment]
How do I insert multiple records? With these examples I can only insert one row at a time. Is it possible to insert multiple records for the owning side?

**Comment by dmj619** [comment]
> Nevermind, I found these docs
> 
> ```
> import {getConnection} from "typeorm";
> 
> await getConnection()
>     .createQueryBuilder()
>     .relation(Post, "categories")
>     .of(post)
>     .add(category);
> ```

I suppose that 'of(post)'  'post' it's the object post where you are inserting category?
I'm trying to:
 ```
const gradoRepository = getRepository('grado');
....
await gradoRepository.createQueryBuilder("grado")
                .relation(Asignatura,"asignaturasGrados").of(grado).add(asignaturaAux)
 ```

but i get error [#331](https://github.com/typeorm/typeorm/issues/331) :

QueryFailedError: Field 'grado_id' doesn't have a default value

**Comment by QUDUSKUNLE** [comment]
I'm having this issue with a Many-to-Many relation, the data is saved in the `order` entity but not in both the `joint table` and `voucher` entity. What could have been the problem? Kindly help. Here are both entity declarations.

**Comment by samlovescoding** [comment]
Is there still no way to do this without the query builder?

**Comment by ShJavokhir** [comment]
Still no solution :( ?

**Comment by HabitGit** [comment]
I found one way, but i'm not sure about it's the best solution.

**Comment by HabitGit** [comment]
I found one way, but i'm not sure about it's the best solution.
```ts
func addSong(playlistId: number, song: Song) {
    const playlist: Playlist = await this.findOne({
        relations: { songs: true },
        where: { id: playlistId },
    });
return this.save({
        ...playlist,
        songs: [...playlist!.songs, song],
    });
};
```
the point is to find a playlist
then insert existing songs
then add your
