### ISSUE TITLE
Full text search with WHERE LIKE within related entity

### ISSUE THREAD

**Issue by martinsotirov** [typeorm/typeorm#6481]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have two entities - Vendor and Review joined by a one-to-many relationship and I'm trying to filter my reviews by vendor.

I can successfully filter them by vendor ID like so:

```
reviewsRepository.find({ where: [{ vendor: { id: search.vendorId } }] })
```

...but for some reason I cannot use Like() and search within the vendor name:

```
reviewsRepository.find({ where: [{ vendor: { name: Like(`%${search.vendorName}%`) } }] })
```

... so I have to resort to first getting all matching vendors and using their IDs within the Review `where` params:

```
const vendors = await vendorsRepo.find({ name: Like(`%${search.vendorName}%`) })
reviewsRepository.find({ where: [{ vendor: { id: In(vendors.map(vendor => vendor.id) } }] })
```

Any ideas about what I might be doing wrong?

**Comment by rubiin** [comment]
you can that with querybuilder.
for reference
https://stackoverflow.com/questions/47814537/how-to-perform-a-like-query-typeorm

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
