### ISSUE TITLE
How to fix could not find array type for data type text[] error

### ISSUE THREAD

**Issue by TharakaSl** [typeorm/typeorm#6484]
**Issue type:**
[ ] question

**Database system/driver:**
[ ] `postgres`

**TypeORM version:**

[ ] `latest`

**Steps to reproduce or a small repository showing the problem:**

I have tried following to find item in a array 
```
import {Any} from "typeorm";

const loadedPosts = await connection.getRepository(Post).find({
    countries: Any(["Sri Lanka", "Nepal"])
});
```
but I am getting this error [QueryFailedError] could not find array type for data type text[]

my entity column define like this
```
@IsNotEmpty()
@Column("text", {array: true})
 public countries: string[];
```

**Comment by elle86a** [comment]
@TharakaSl need to have an **array of text on database** , can create like this one :

```
CREATE TABLE table_name (
    schedule        text[]
);
```

**Comment by ccioloca** [comment]
Well ... on the entity it states the type. Why would someone manually create a table? 

Also I am having the same issue. The entity as per documentation it looks fine, but when I am doing a where EX:  
`.where('volunteer.experience = ANY(:param)', {
        param: 'Central lines',
      })`   I get  QueryFailedError: could not find array type for data type text[]

**Comment by khiner** [comment]
I'm seeing this too. `text[]` type field and an array of strings passed to `Any` in a `where` causes "could not find array type for data type text[]" error, since (it looks like?) typeorm is redundantly trying to convert an array into an array.

**Comment by Ginden** [comment]
@khiner Please provide fulll example where such behaviour occurs.
