### ISSUE TITLE
Question. Pls help! Get minimum column value from related entity

### ISSUE THREAD

**Issue by 2rv** [typeorm/typeorm#6487]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hello. Please, help me. I cant find information about how do this. 
I have got this code. It load all products with all relations. One of relations is product item. In product item entity I have got price column.

How I can get minimal product item price without get in my response array of product items?

```
const { skip, take } = pagination;

    const query = this.createQueryBuilder('product');

    query.where('product.shop = :id AND product.blocked = FALSE', {
      id: shop.id,
    });

    if (skip) {
      query.offset(Number(skip));
    }

    if (take) {
      query.limit(Number(take));
    }

    query.leftJoin('product.info', 'info');
    query.leftJoin('product.avatar', 'avatar');

    // load product items
    query.leftJoin('product.productItem', 'item');

    query.select([
      'product.id',
      'product.path',
      'info.name',
      'info.description',
      'info.info',
      'info.lang',
      'avatar.path',
      'avatar.type',

      'item.price'
    ]);

    const [list, amount] = await query.getManyAndCount();
```

Now i have got:
```
{
	"list": [
		{
			"id": 3,
			"path": "admin-product-2",
			"order": 1,
			"shop": {
				"id": 1
			},
			"info": [
				{
					"name": "Admin Name ;)",
					"description": "Shorty",
					"info": "",
					"lang": "RU"
				}
			],
			"avatar": null,
			"productItem": [
				{
					"price": 1000
				},
				{
					"price": 500
				},
				{
					"price": 300
				},
				{
					"price": 2000
				},
				{
					"price": 3000
				}
			]
		}
	]
}
........
```

But I need:

```

{
	"list": [
		{
			"id": 3,
			"path": "admin-product-2",
			"order": 1,
			"shop": {
				"id": 1
			},
			"info": [
				{
					"name": "Admin Name ;)",
					"description": "Shorty",
					"info": "",
					"lang": "RU"
				}
			],
			"avatar": null,
                         "minProductItemPrice": 300
		}
	]
}

```

I am ready to pay a reward for the decision

**Comment by arnas** [comment]
Well you need to do something like this https://stackoverflow.com/a/19417993. In typeorm you can write subquery in join. Here is an example https://github.com/typeorm/typeorm/issues/457#issuecomment-361411051.

**Comment by imnotjames** [comment]
Hi there!  For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check https://typeorm.io/#/support - cheers!
