### ISSUE TITLE
Request: Support for Time info in Oracle Date column, to match Oracle SQL Documentation

### ISSUE THREAD

**Issue by Tai-Iro** [typeorm/typeorm#6489]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Unlike most varieties of SQL databases, the `date` type in Oracle SQL can store the time of day, as seen in the documentation here: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Data-Types.html#GUID-5405B652-C30E-4F4F-9D33-9A4CB2110F1B

> For each DATE value, Oracle stores the following information: year, month, day, **hour, minute, and second.**  

However, the Oracle driver always excludes the time information, as seen here: https://github.com/typeorm/typeorm/blob/1c52ccf15062d84f100f099a874a70dab7a9bd8e/src/driver/oracle/OracleDriver.ts#L366-L369

This seems like it should be a fairly simple change. Maybe like this would work:
```typescript
return () => `TO_DATE('${DateUtils.mixedDateToDatetimeString(value)}', 'YYYY-MM-DD HH:MM:SS')`;
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
Wouldn't that make the date type in Oracle different from every other type?

**Comment by imnotjames** [comment]
Yeah, it would.  This is a very intentional choice.  While the `DATE` type in Oracle may support time, `date` in typeorm does not.

Cheers!
