### ISSUE TITLE
Unique index on MongoDB doesn't get created

### ISSUE THREAD

**Issue by Masterrg** [typeorm/typeorm#649]
Using the ```@Index({unique: true}) ``` decorator on a MongoDB "Column" successfully creates an index BUT doesn't make it unique.

Example Entity:
```ts
export class User {
    @ObjectIdColumn()
    id: string;

    @Column()
    name: string;

    @Column()
    @Index({unique: true})
    email: string;
}
```

**Comment by pleerock** [comment]
fix will be released in `0.1.0-alpha.33`
