### ISSUE TITLE
Postgres synchronize fails

### ISSUE THREAD

**Issue by insanebaba** [typeorm/typeorm#6490]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
- set **synchronize** as true in _ormconfig.json_
- use node version 10.22.0
- use script _tsnd --clear --debug  --respawn src/index.ts_ 

Exception recieved 
```bash
(node:28613) UnhandledPromiseRejectionWarning: TypeError: value.split is not a function
    at PostgresDriver.lowerDefaultValueIfNecessary (/mnt/c/Users/<username>/projects/<project_home>/src/driver/postgres/PostgresDriver.ts:854:22)
    at /mnt/c/Users/<username>/projects/<project_home>/src/driver/postgres/PostgresDriver.ts:838:54
    at Array.filter (<anonymous>)
    at PostgresDriver.findChangedColumns (/mnt/c/Users/<username>/projects/<project_home>/src/driver/postgres/PostgresDriver.ts:827:32)
    at RdbmsSchemaBuilder.<anonymous> (/mnt/c/Users/<username>/projects/<project_home>/src/schema-builder/RdbmsSchemaBuilder.ts:516:59)
    at step (/mnt/c/Users/<username>/projects/<project_home>/node_modules/tslib/tslib.js:141:27)
    at Object.next (/mnt/c/Users/<username>/projects/<project_home>/node_modules/tslib/tslib.js:122:57)
    at /mnt/c/Users/<username>/projects/<project_home>/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/mnt/c/Users/<username>/projects/<project_home>/node_modules/tslib/tslib.js:111:16)
(node:28613) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:28613) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[DEBUG] 00:43:33 Child exited with code 0

```

**Comment by max10rogerio** [comment]
This problem is because in `postgres`, the default need one of types `string` or `undefined`.

> **Wrong**

```ts
@Column({ name: "alterar_senha", default: () => true })
 alterarSenha: boolean;
```

> **Passed**
```ts
@Column({ name: "alterar_senha", default: "true" })
 alterarSenha: boolean;
```

Function error:
https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L897

**Comment by insanebaba** [comment]
I solved it by replacing all "default" values from arrow function 
```
@Column({ name: "alterar_senha", default: () => "something" })
 alterarSenha: String;
```
to constant value

```
@Column({ name: "alterar_senha", default: "something" })
 alterarSenha: String;
```

I did this for all value types(bool,string,number)

**Comment by ORESoftware** [comment]
This is something typescript should be able to catch..please fix that.
It's either a string, or a function arity 0 that returns a string.

**Comment by onwaterapp** [comment]
@UpdateDateColumn({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })

throws same error
