### ISSUE TITLE
Array relations are not deleted

### ISSUE THREAD

**Issue by renehauck** [typeorm/typeorm#6492]
**Issue type:**

[x ] question
[? ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi,

I have the following structure and am surprised that an array (in this case a many:many relation) does not delete the referenced array element. Am I doing something wrong or is this a bug?

**Steps to reproduce or a small repository showing the problem:**

I have a TodoItemEntity which can contain several TagEntities.
```ts
@Entity({ name: 'todo_item' })
export class TodoItemEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @ManyToMany(() => TagEntity, (tag) => tag.todoItems,{cascade:true})
  @JoinTable()
  tags!: TagEntity[];
}
```

```ts
@Entity({ name: 'tag' })
export class TagEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  name!: string;

  @ManyToMany((): ObjectType<TodoItemEntity> => TodoItemEntity, (td) => td.tags)
  todoItems!: TodoItemEntity[];
}
```

Now I execute this code:

```ts
let todoItem=new TodoItemEntity();
    const oldTag= new TagEntity()
    oldTag.name="Old"
    todoItem.tags =[oldTag];
    await this.todoItemRepository.save(todoItem);

    todoItem = await this.todoItemRepository.findOne(todoItem.id);
    const newTag= new TagEntity()
    newTag.name="New"
    todoItem.tags =[newTag];
    await this.todoItemRepository.save(todoItem);
```
This works, but now I still have the old entry in the database

![image](https://user-images.githubusercontent.com/3898144/88900075-2e582780-d24f-11ea-904d-c13a83c90cc6.png)

Many thanks for the work

**Comment by timothyvanderaerden** [comment]
Seems to be a duplicate of #1351

**Comment by renehauck** [comment]
yes sorry
