### ISSUE TITLE
How can I use TypeORM with better-sqlite3

### ISSUE THREAD

**Issue by daniel-dia** [typeorm/typeorm#6494]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

on the official [documentation][1], there is a section for better-sqlite3.

I already installed by `typeorm@latest` and `typeorm@next` but there is no options for better-sqlite3 yet.

If i try to force initialize it, i got the following error

>MissingDriverError: Wrong driver: "better-sqlite3" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".

  [1]: https://typeorm.io/#/connection-options/better-sqlite3-connection-options

What am I missing?

**Comment by imnotjames** [comment]
Currently `v0.2.25` does not have `better-sqlite3` - the next release of TypeORM will.

**Comment by imnotjames** [comment]
We have support for `better-sqlite3` now!  Cheers
