### ISSUE TITLE
MongoDB Inserting an Array of Embedded Documents

### ISSUE THREAD

**Issue by johnwick2614** [typeorm/typeorm#6495]
**Issue type:**

[ ] question
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[*] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

my entity file.

```
import { Entity, ObjectIdColumn, Column, Unique, CreateDateColumn, UpdateDateColumn, ObjectID } from "typeorm";
import { Length, IsNotEmpty } from "class-validator";

@Entity()
@Unique(["orderNumber"])
export class Orders {
  @ObjectIdColumn()
  id: ObjectID;
  @Column()
  @Length(4, 10)
  orderNumber: string;

  @Column(type => Product)
  product: Product;

  @Column()
  @Length(1, 50)
  totalAmount: string;

  @ObjectIdColumn()
  dealerId: string;

  @ObjectIdColumn()
  employeeid: ObjectID;

  @Column()
  @CreateDateColumn()
  createdAt: Date;

  @Column()
  @UpdateDateColumn()
  updatedAt: Date;
  order: Product;
}
export class Product {
  @Column()
  name: string;
  @Column()
  quantity: number;
  @Column()
  productAmount: boolean;
}
```

while inserting data with https://orkhan.gitbook.io/typeorm/docs/mongodb#defining-subdocuments-embed-documents
example I am getting error that UnhandledPromiseRejectionWarning: RepositoryNotFoundError: No repository for "Product" was found. Looks like this entity is not registered in current "default" connection?

and if add Entity() at Product Class, It gives me error that you should Assign a PrimaryColoum. and when I add primary It insert null data into Database.

I am new to nodejs. It will be more helpful to learn from seniors.

**Comment by imnotjames** [comment]
You have an extra order product.  I can't replicate the issue you're having, though.

Perhaps you need to define Product as an embedded entity.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
