### ISSUE TITLE
Full in-memory Typeorm (for unit testing purposes)

### ISSUE THREAD

**Issue by oguimbal** [typeorm/typeorm#6496]
**Issue type:**

- [x] question
- [x] documentation issue

**Database system/driver:**
- [x] `postgres`

Hi, I developped for our needs [pg-mem, an in-memory version](https://github.com/oguimbal/pg-mem) of postgres.
It works well with Typeorm, and allows to emulate Typeorm running on a clean in-memory database (useful to run unit tests, for instance).

The result turned out to be quite useful for us, and I wanted to share it... is there any way to be mentioned somewhere in your docs ?

[Example of usage with Typeorm](https://github.com/oguimbal/pg-mem/blob/6dc3ee599c5d03609c46365828a70d65265dd741/samples/typeorm/joins.ts#L37-L53)

Here is a small in-memory [playground](https://oguimbal.github.io/pg-mem-playground/) if you want to test pg-mem.

**(edit)** pg-mem only implements PG syntax,  but it should be compatible with other providers for most queries, and I could implement other DBs one day.

Thanks :)

**Comment by imnotjames** [comment]
Very neat! I can see a lot of work went into this.

Unfortunately, we need to place effort in our documentation elsewhere, so this won't be included.
