### ISSUE TITLE
How to set AUTO_INCREMENT on Typeorm PrimaryGeneratedColumn?

### ISSUE THREAD

**Issue by juststartmeteor** [typeorm/typeorm#6497]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

As MySQL has AUTO_INCREMENT on id (primary key) column, so id can be start from, e.g, 100 by set AUTO_INCREMENT = 100. How to implement it on typeorm PrimaryGeneratedColumn?

**Comment by rubiin** [comment]
As per the docs, `@PrimaryGeneratedColumn() creates a primary column which value will be automatically generated with an auto-increment value. It will create int column with auto-increment/serial/sequence (depend on the database). You don't have to manually assign its value before save - value will be automatically generated` . There is a mention of `depend on the database`. Also I have used postgres and mssql but havent encountered it. So maybe a db restriction or something
