### ISSUE TITLE
.save does not type check

### ISSUE THREAD

**Issue by shayan-kousha** [typeorm/typeorm#6498]
**Issue type:**

[ ] question
[ X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.22`

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>
when saving an object into db using the `.save` function it does not type check.
code to reproduce
```
const testObject: OtherEntity = new OtherEntity()
await getConnection().getRepository(MainEntity). save(testObject)
```
the save statement doesn't fail even though testObject is not the type of MainEntity.

**Comment by imnotjames** [comment]
This is expected because the `save` expects a type of deep partial.
