### ISSUE TITLE
Request to make Connection#buildMetadatas public

### ISSUE THREAD

**Issue by glen-84** [typeorm/typeorm#6500]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Would you accept a PR to make `Connection#buildMetadatas` public? (it's currently protected)

I'd like to call this method to build the metadata, without actually connecting to the database. This metadata is useful for generating things like GraphQL input types.

The code is something like this:

```ts
const connection = getConnectionManager().create(await getConnectionOptions("default"));

connection.buildMetadatas(); // <-- currently a protected method.
```

**Comment by imnotjames** [comment]
We currently don't support connections without connecting and increasing the surface area of our APIs, exposing this kind of thing is a large maintenance overhead and creates a foot-gun.

If you'd like to call an unsupported and internal API you can extend connection and make it public in your class.
