### ISSUE TITLE
Wrong date filtering MSSQL

### ISSUE THREAD

**Issue by jrvidotti** [typeorm/typeorm#6502]
**Issue type:**
[?] bug report

**Database system/driver:**
[x] `mssql`

**TypeORM version:**
[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

I am facing some issues with dates between TypeORM and MSSQL. Don't know if is TZ ou SQL driver issue. I am trying to filter records created today (08/02/2020) but TypeORM sends to database yesterday date (08/01/2020). Am I doing something wrong?

```ts
import { createConnections, getRepository, MoreThan } from 'typeorm'
import { SmsSaida } from '../src/orm/entities/campanhas/SmsSaida'

async function main() {
  await createConnections()

  let smsRepo = getRepository(SmsSaida)
  let hoje = new Date()
  hoje = new Date(hoje.getFullYear(), hoje.getMonth(), hoje.getDate())
  console.log(hoje.toString())
  let sms = await smsRepo.find({ where: { dataCriacao: MoreThan(hoje) } })
  console.log(sms.length)
}

main()
```

Outputs:
```
Sun Aug 02 2020 00:00:00 GMT-0400 (Amazon Standard Time)
query: SELECT "SmsSaida"."id" AS "SmsSaida_id", "SmsSaida"."codigoPessoa" AS "SmsSaida_codigoPessoa", "SmsSaida"."telefone" AS "SmsSaida_telefone", "SmsSaida"."mensagem" AS "SmsSaida_mensagem", "SmsSaida"."dataEnvio" AS "SmsSaida_dataEnvio", "SmsSaida"."respostaSms" AS "SmsSaida_respostaSms", "SmsSaida"."statusMensagem" AS "SmsSaida_statusMensagem", "SmsSaida"."dataCriacao" AS "SmsSaida_dataCriacao", "SmsSaida"."dataAlteracao" AS "SmsSaida_dataAlteracao", "SmsSaida"."campanhaId" AS "SmsSaida_campanhaId" 
FROM "sms_saida" "SmsSaida" 
WHERE "SmsSaida"."dataCriacao" > @0 -- PARAMETERS: ["2020-08-02T04:00:00.000Z"]
91
```

SQL Server Profiler trace
```
exec sp_executesql @statement=N'SELECT "SmsSaida"."id" AS "SmsSaida_id", "SmsSaida"."codigoPessoa" AS "SmsSaida_codigoPessoa", "SmsSaida"."telefone" AS "SmsSaida_telefone", "SmsSaida"."mensagem" AS "SmsSaida_mensagem", "SmsSaida"."dataEnvio" AS "SmsSaida_dataEnvio", "SmsSaida"."respostaSms" AS "SmsSaida_respostaSms", "SmsSaida"."statusMensagem" AS "SmsSaida_statusMensagem", "SmsSaida"."dataCriacao" AS "SmsSaida_dataCriacao", "SmsSaida"."dataAlteracao" AS "SmsSaida_dataAlteracao", "SmsSaida"."campanhaId" AS "SmsSaida_campanhaId" 
FROM "sms_saida" "SmsSaida" 
WHERE "SmsSaida"."campanhaId" = @0 AND "SmsSaida"."dataCriacao" > @1',
@params=N'@0 int, @1 datetime',@0=9,@1='2020-08-01 00:00:00'
```

**Comment by jrvidotti** [comment]
PS: I was using options.useUTC = false. Switching to true, the problem is solved.

**Comment by jrvidotti** [comment]
Just figure out what's happening. It's a Tedious driver error solved in 8.0. But TypeORM seems to use an old version of mssql and tedious. 

https://github.com/tediousjs/tedious/issues/1018

What can I do?

**Comment by rubiin** [comment]
is the pblm solved?

**Comment by jrvidotti** [comment]
Nope... just workarounds, threating dates for EVERY insert and update.

**Comment by imnotjames** [comment]
> TypeORM seems to use an old version of mssql and tedious.

TypeORM does not specify any versions of peer dependencies.

I really want to get peer dependencies set up, but haven't yet.  However, I've seen this issue as well in our tests.

Are there breaking changes between the mssql and tedious versions?

**Comment by imnotjames** [comment]
Given that this isn't a TypeORM issue but is a upstream TDS library issue I'm going to close it out.  Upgrade to use the newer version.
