### ISSUE TITLE
AuroraDataApiPostgresDriver is not exported from "./postgres/PostgresDriver"

### ISSUE THREAD

**Issue by ilanolkies** [typeorm/typeorm#6503]
**Issue type:**

- [x] bug report

**Database system/driver:**

- [x] `sqljs`

**TypeORM version:**

- [x] `latest`

**Steps to reproduce or a small repository showing the problem:**

I installed a library in React.js that uses `typeorm` (https://github.com/uport-project/daf). This suite works fine in other enviornments but in the browser I get

<img width="1040" alt="Screen Shot 2020-08-03 at 00 21 53" src="https://user-images.githubusercontent.com/36084092/89143078-b70ce700-d51f-11ea-8aac-8669cc473faf.png">

Commenting the line in `/node_modules/typeorm/browser/driver/DriverFactory.js` works fine.

<img width="595" alt="Screen Shot 2020-08-03 at 00 22 24" src="https://user-images.githubusercontent.com/36084092/89143118-d3108880-d51f-11ea-91d5-1013250f1e13.png">

**Comment by mroeling** [comment]
Confirmed in typeorm 0.2.25

**Comment by xdrago1** [comment]
Yes that is still an issue here. also on 0.2.25

**Comment by ilanolkies** [comment]
This was with 0.2.25

**Comment by ilanolkies** [comment]
It is not fixed as far as I tested

**Comment by jonathanloos** [comment]
I can confirm that this issue is persisting.

**Comment by imnotjames** [comment]
This should be fixed now.
