### ISSUE TITLE
Generated uuids are not safe

### ISSUE THREAD

**Issue by AlbertoFdzM** [typeorm/typeorm#6504]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[X] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The current code to generate a `uuid` is not safe and can cause duplicates easily.
https://github.com/typeorm/typeorm/blob/master/src/util/RandomGenerator.ts#L146-L154

I've got duplicates for a production environment by doing a high amount of inserts in a short period of time.
```
@Entity('foo')
class Foo {
  @PrimaryGeneratedColumn('uuid')
  public uuid: string;
}
```

```json
{
  "code": "ER_DUP_ENTRY",
  "errno": 1062,
  "sqlState": "23000",
  "sqlMessage": "Duplicate entry 'a83d2934-ef24-400c-8257-0322addc708f' for key 'IDX_e397df309913431733224537f9'",
  "name": "QueryFailedError",
  "query": "INSERT INTO `foo`(`uuid`) VALUES (?)",
  "parameters": [
    "a83d2934-ef24-400c-8257-0322addc708f"
  ]
}
```

---

Consider the use of https://github.com/uuidjs/uuid

**Comment by imnotjames** [comment]
Egads, yeah, we might want to mess with that some. 

Biggest reason why it's the way it is - because of supporting browser as well as node.

Really hoping we can get a good browser webpack set up going soon to better handle things like node APIs & polyfilling them in the browser.
