### ISSUE TITLE
Query stream feature/support to OracleDB

### ISSUE THREAD

**Issue by calebeaires** [typeorm/typeorm#6505]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**
[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

OracleDB nodejs dialect has support to [streaming by a very simple sintaxe](https://oracle.github.io/node-oracledb/doc/api.html#querystream). It works very well on the ReadStream node flow. Here is how it looks like:

`queryStream(String sql [, Object bindParams, [Object options]]);`

May you consider to add this support to TypeOrm?

**Comment by imnotjames** [comment]
Is this similar to the postgres syntax?

**Comment by calebeaires** [comment]
Quite similar... 

```javascript

const stream = await connection.queryStream(`SELECT employees_name FROM employees`);

stream.on('error', function (error) {
  // handle any error...
});

stream.on('data', function (data) {
  // handle data row...
});

stream.on('end', function () {
  // all data has been fetched...
  stream.destroy();  // the stream should be closed when it has been finished
});

stream.on('close', function () {
  // can now close connection...  (Note: do not close connections on 'end')
});

stream.on('metadata', function (metadata) {
  // access metadata of query
});

// listen to any other standard stream events...

```

**Comment by ozknemoy** [comment]
would be great to have this for oracle driver

**Comment by schambersnh** [comment]
agreed! we would love this as well
