### ISSUE TITLE
"[" must introduce explicitly-specified array dimensions. Array of objects.

### ISSUE THREAD

**Issue by blindibrasil** [typeorm/typeorm#6507]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.24` 

**Steps to reproduce or a small repository showing the problem:**

Hello I'm trying to create an array of objects but I'm not getting it and it always presents the following error:
'"[" must introduce explicitly-specified array dimensions.',

Sending via API:

```
{
	"available_times": [
		{
			"day": "Thursday",
			"minHour": 18,
			"maxHour": 20
		},
		{
			"day": "Friday",
			"minHour": 17,
			"maxHour": 22
		}
	]
}
```

```ts 
interface IAvailableTimes {
  day: string;
  minHour: number;
  maxHour: number;
}
 @Column('jsonb', { array: true, nullable: true })
  available_times: IAvailableTimes[];
 ```

receiving the error

```
message: 'malformed array literal: "[{"day":"Thursday","minHour":18,"maxHour":20},{"day":"Friday","minHour":17,"maxHour":22}]"',
  name: 'QueryFailedError',
  length: 232,
  severity: 'ERROR',
  code: '22P02',
  detail: '"[" must introduce explicitly-specified array dimensions.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'arrayfuncs.c',
  line: '270',
  routine: 'array_in',
  query: 'INSERT INTO "schedules"("id", "user_id", "available_times", "created_at", "updated_at") VALUES (DEFAULT, $1, $2, DEFAULT, DEFAULT) RETURNING "id", "created_at", "updated_at"',
  parameters: [
    '29912757-94c6-4709-8b58-37777d80d69a',
    '[{"day":"Thursday","minHour":18,"maxHour":20},{"day":"Friday","minHour":17,"maxHour":22}]'
  ]
}
```

Thank you in advance for your help.

**Comment by blindibrasil** [comment]
RESOLVED.
I had this error, because I was sending elements that were not part of a JSON which was causing conflict in Postgres.
If anyone has this same error comment below so I can try to help.

**Comment by shuhaib-inunity** [comment]
@blindibrasil  could do explain how you solved the issue .. because iam suffering with the same error

**Comment by sabinbogati1** [comment]
This is how i fixed this issue
No need to add array: true parameter

`  @Column('jsonb', {
    nullable: true,
  })
  variety: MenuItemVariety[];`
