### ISSUE TITLE
Table_id_seq already exist in Postgres with connection option autoSchemaSync=true

### ISSUE THREAD

**Issue by sayedcsekuet** [typeorm/typeorm#651]
For an existing database table that has already table_id_seq getting exception `table_id_seq already exist` on calling function "changeColumn" in `src/driver/postgres/PostgresQueryRunner.ts` with connection option "autoSchemaSync=true". So is it possible to create sequence if not exist. 
Steps as follows:-
- Create an entity with Annotation 
- Insert data to the table
- Delete the data from table, at this stage table is empty
- Try to connect to database, getting exception.

**Comment by pleerock** [comment]
Im not able to reproduce this issue. Can you please provide more details?

> For an existing database table that has already table_id_seq

what do you mean by "existing database table"? Is this database table create by TypeORM?

> Create an entity with Annotation

is your first step starts with empty database?

**Comment by pleerock** [comment]
@iz-iznogood I think you have fix it already, am I right?

**Comment by iz-iznogood** [comment]
Yes, sorry I did not see this issue. It can be closed
