### ISSUE TITLE
ManyToMany w/ custom Mapping Object & Recursive Entities

### ISSUE THREAD

**Issue by nickrichardson-presto** [typeorm/typeorm#6513]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So I have 2 entities `Item` & `Group`

An `Item` can have multiple "sub groups"

A `Group` can have multiple "sub items"

A `Group`'s "sub item" can have a "sub group" as well. There can be any order and they can be repeated.  
(We will NOT however get into a position with infinite loops)

I need to create this recursive relationship in TypeORM but I'm unsure how to do it properly. I assume I need a ManyToMany but it gets complicated because I need to know which is the parent and which is the child. I've tried the following and it doesn't seem work right when adding an Item to a Group

```
class Item {
   {...}

   @ManyToMany(type => Group, group => group.items)
   @JoinTable()
   groups: Group[];
}

class Group {
   {...}
   
   @ManyToMany(type => Item, item => item.groups)
   @JoinTable()
   items: Item[];
}
```

I've also tried the following, hoping I could get the child groups or items as just an array of ID's (b/c that would work perfect as well. I can rebuild the tree on the UI).

```
class Item {
   {...}

   @OneToMany(type => ItemToGroup, itemToGroup => itemToGroup.item)
    itemToGroup: ItemToGroup[];
}

class Group {
   {...}
   
   @OneToMany(type => ItemToGroup, itemToGroup => itemToGroup.group)
    itemToGroup: ItemToGroup[];
}

class MenuItemToModifierGroup {
    {...}
  
    @ManyToOne(type => Group, group => group.itemToGroup)
    group: Group;

    @ManyToOne(type => Item, item => item.itemToGroup)
    item: Item;
}
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
