### ISSUE TITLE
Is a typeorm @ViewEntity the same as postgres virtual table? 

### ISSUE THREAD

**Issue by velociraptor111** [typeorm/typeorm#6518]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Is a typeorm @ViewEntity the same as postgres virtual table?

**Comment by imnotjames** [comment]
Per the documentation ( https://typeorm.io/#/view-entities ) -

> View entity is a class that maps to a database view.

A view is a type of virtual table.
