### ISSUE TITLE
Bulk insert fails in SAP Hana driver

### ISSUE THREAD

**Issue by mathiasmaerker** [typeorm/typeorm#6519]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] sap hana
**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi all,
when trying to insert multiple rows into a single entity I get the following error:
![image](https://user-images.githubusercontent.com/4051929/89383937-a3b77280-d6fd-11ea-85d5-5f3f5a47f015.png)

```javascript
@Entity({ name: 'p4c_labels' })
export class Label {
  @PrimaryColumn()
  locale: string
  @PrimaryColumn()
  labelId: string
  @Column()
  labelValue: string
  @Column()
  entityId: string
  @Column()
  active: boolean
}
```
Insert coding

```javascript
      return repo
        .createQueryBuilder()
        .insert()
        .into(Label, ['locale', 'labelId', 'labelValue', 'entityId', 'active'])
        .values([
          { locale: 'de', labelId: 'id1', labelValue: 'bla bla bla', entityId: 'ITEM', active: true },
          { locale: 'en', labelId: 'id1', labelValue: 'bla bla bla', entityId: 'ITEM', active: true },
        ])
        .execute()
```
We wanted to use `repo.save()` but for whatever reason it is extremely slow. Saving around 5k entries takes about 20 minutes. Is there any way to check why it is taking so long? Some debug setting?

Regards

Mathias

**Comment by mathiasmaerker** [comment]
So I think we can close this issue, it seems that Hana is not capable of multi row inserts :(

**Comment by imnotjames** [comment]
This probably should be handled in the query runner for SAP :\
