### ISSUE TITLE
GetMany returns less entities then the number on GetCount

### ISSUE THREAD

**Issue by DavideCarvalho** [typeorm/typeorm#6522]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

As you can see in the image below, the query returns 2 entities, but the count is 3

![image](https://user-images.githubusercontent.com/15630886/89430838-8c847f00-d715-11ea-8d5f-8c21466c5307.png)

logging the queries, I see that the count query is being written like this:

```sql
SELECT COUNT(DISTINCT(CONCAT(`coursetaken`.`user_id`, `coursetaken`.`course_id`))) as "cnt" FROM `course_taken` `coursetaken`
```

while the entity query is this:

```
SELECT `coursetaken`.`createdAt` AS `coursetaken_createdAt`, `coursetaken`.`updatedAt` AS `coursetaken_updatedAt`, `coursetaken`.`version` AS `coursetaken_version`, `coursetaken`.`course_start_date` AS `coursetaken_course_start_date`, `coursetaken`.`course_complete_date` AS `coursetaken_course_complete_date`, `coursetaken`.`status` AS `coursetaken_status`, `coursetaken`.`completion` AS `coursetaken_completion`, `coursetaken`.`user_id` AS `coursetaken_user_id`, `coursetaken`.`course_id` AS `coursetaken_course_id`, `coursetaken`.`current_lesson_id` AS `coursetaken_current_lesson_id`, `coursetaken`.`current_part_id` AS `coursetaken_current_part_id`, `coursetaken`.`current_test_id` AS `coursetaken_current_test_id` FROM `course_taken` `coursetaken` GROUP BY `coursetaken`.`user_id`
```

**Comment by imnotjames** [comment]
This looks like it's working as expected - you're grouping by the `user_id` but getting a count of the `user_id` / `course_id` combinations.  If you removed the `GROUP BY` it would be correct.

**Comment by imnotjames** [comment]
This seems to be less of a bug and more of a support request or question.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
