### ISSUE TITLE
Slack Link on Support page is disabled

### ISSUE THREAD

**Issue by btilford** [typeorm/typeorm#6523]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[X] documentation issue

The link to join the TypeORM Slack on https://typeorm.io/#/support no longer works.

**Comment by imnotjames** [comment]
Well that's frustrating.  Just updated the darn thing.  I wonder if they set the TTL much lower or something?

**Comment by imnotjames** [comment]
"This link doesn't expire" per slack

https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g

**Comment by btilford** [comment]
> "This link doesn't expire" per slack
> 
> https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g

That one did work.

**Comment by imnotjames** [comment]
Great.  The PR I opened should fix that link.  Sorry about that!  I'd only updated it for the readme.
