### ISSUE TITLE
save method executing update query when it shouldn't do anything

### ISSUE THREAD

**Issue by JasonMan34** [typeorm/typeorm#6525]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following entity in TypeORM:
```typescript
@Entity('USERS')
class User {
  @PrimaryColumn('varchar2', { name: 'FULL_NAME', length: 100 })
  fullName!: string;

  @Column('timestamp', { name: 'BIRTHDAY' })
  birthday!: Date;
}
```

And the following piece of code:
```typescript
const repo = getRepository(User);
const me = await repo.findOne("Jason Earl");
const todayString = new Date().toISOString();

me.birthday = new Date(todayString);
await repo.save(me); // Performs an UPDATE query to the db, as expected
await repo.save(me); // Performs an UPDATE query to the db, even though nothing changed
```

This is problematic as we have DB triggers for updates, and it messes things up when an update is called without any real changes

**Comment by imnotjames** [comment]
Looks like you aren't reloading the entity between saves - if you pass the option `{reload: true}` to your save does the same thing happen?

**Comment by JasonMan34** [comment]
For anyone else experiencing this odd behavior - The reason was inconsistency between the database and JS date precision.  
As I mentioned [here](https://github.com/typeorm/typeorm/issues/6040), there is currently no support for the Oracle `DATE` type, so I had to use `timestamp` despite the column not being defined as such.

As a result TypeORM expected the DB column to hold the date up to (at least) millisecond precision, but Oracle `DATE` only holds up to seconds.  
My solution was to recursively iterate over all nested date types before saving an entity and setting their milliseconds to 0
