### ISSUE TITLE
CLI commands fail when my entities include custom validation decorators

### ISSUE THREAD

**Issue by martinsotirov** [typeorm/typeorm#6526]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I use the Typeorm CLI via ts-node like so
```
node --require ts-node/register ./node_modules/typeorm/cli.js
```

My Typeorm entity has a static method for conversion from a DTO and my DTO uses custom class-validator decorators as described in the [class-validator manual](https://github.com/typestack/class-validator#custom-validation-decorators).

```
export function VendorExists() {
  return function(object: Object, propertyName: string) {
    registerDecorator({
      name: 'vendorExists',
      target: object.constructor,
      propertyName: propertyName,
      validator: {
        async validate(vendorId: any, args: ValidationArguments) {
          const vendorsRepo = getRepository(VendorEntity)
          const vendor = await vendorsRepo.findOne(vendorId)
          return vendor instanceof VendorEntity
        },
        defaultMessage(validationArguments?: ValidationArguments): string {
          return 'Vendor does not exist'
        },
      },
    })
  }
}
```

Every time I try to generate or run a migration, I get this error:

```
TypeError: vendors_validators_1.VendorExists is not a function
```

Which means whenever I use the Typeorm CLI I have to temporarily comment out all of my custom class-validator decorators.

**Comment by imnotjames** [comment]
Do you have a repository that exhibits this behavior?

**Comment by martinsotirov** [comment]
No, because it's a private customer project but funny enough the CLI stopped throwing this TypeError at some point. I didn't have to change my code but I probably updated some package in the whole build chain which resolved the problem.

**Comment by Mery042** [comment]
Hello, I have the same issue today with a custom decorator. It seems that the import of decorator remains "undefined" when it's being compiled by ts-node (used in typeorm-ts-node-commonjs CLI). It's very strange because it occurs only with custom decorators which involves database fetching in it. For example, this issue appears with my "AlreadyExists" decorator which queries the database with a Repository.

I am in great need of answers for this behavior because I use the typeorm-ts-node-commonjs CLI to run migrations in initContainers step of my Kubernetes deployment.

Thanks in advance.

**Comment by j040p3d20** [comment]
https://stackoverflow.com/questions/76155221/using-typeorm-cli-with-yarn-berry-and-ts-path-aliases/77996086#77996086
