### ISSUE TITLE
[DOCS] Inverted decorators in "Adjacency list" example

### ISSUE THREAD

**Issue by manuelnucci** [typeorm/typeorm#6527]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The decorators used in the "[Adjacency list](https://typeorm.io/#/entities/adjacency-list)" could possibly be inverted.

Here's the example as I think is correct:

```
import {Entity, Column, PrimaryGeneratedColumn, ManyToOne, OneToMany} from "typeorm";

@Entity()
export class Category {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column()
    description: string;

    @ManyToOne(type => Category, category => category.children) // <-- each child has only one parent
    parent: Category;

    @OneToMany(type => Category, category => category.parent) // <-- each parent has one or more children
    children: Category[];
}
```

**Comment by manuelnucci** [comment]
**Update** 

It seems that only [this](https://typeorm.io/#/entities/adjacency-list) example was outdate. The one that I found [here](https://typeorm.io/#/tree-entities/adjacency-list) is correct, as I proposed initially.

Therefore, the first link should be updated to mimic the second one.

**Comment by imnotjames** [comment]
Pull requests always welcome!
