### ISSUE TITLE
Feature Request: Custom naming of FK for composite keys

### ISSUE THREAD

**Issue by DavidPMacNeil** [typeorm/typeorm#653]
For a single FK `@JoinColumn{{ name: 'abc' })` works great. If however a composite key is referenced it will go back to `tableNamePK1`, `tableNamePK2`, etc. 

I'm not sure what would be the best design for something like this. Perhaps a new decorator, JoinColumns, where multiple PK names could be specified like: `@JoinColumns({ name: 'pk1', name: 'pk2 })` , or maybe JoinColumn could be expanded to accept an array of PK names `@JoinColumn({ name: ['pk1', 'pk2'] })`

**Comment by pleerock** [comment]
try:

```ts
@JoinColumn{[
   { name: 'abc', referencedColumn: "pk1" },
   { name: 'dce', referencedColumn: "pk2" },
])
```

note, you must specify referencedColumns

**Comment by DavidPMacNeil** [comment]
Yes, this worked, thank you.

`referencedColumn` is `referencedColumnName` though.
