### ISSUE TITLE
SQL Row_Number() function in Where Clause returning string

### ISSUE THREAD

**Issue by alex-r89** [typeorm/typeorm#6534]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25`

**Steps to reproduce or a small repository showing the problem:**

Hi,

I am struggling with getting a subquery to return the correct data, however I believe I am fairly close to the solution so was wondering if someone with more knowledge could assist:

I am trying to select the row_number with a where clause (much like is being asked [here](https://stackoverflow.com/questions/1466963/sql-row-number-function-in-where-clause)). For those unsure, row_number assigns a sequential integer to each row in a result set.

I have a working solution, however for some reason the response is just a string of the values:

## Solution
```js
   const photo = await getConnection()
      .createQueryBuilder()
      .select('photo')
      .from((subQuery) => {
        return subQuery
          .select('photo', 'photo')
          .addSelect('ROW_NUMBER () OVER (ORDER BY "vote_count") as "rank"')
          .from(Photo, 'photo')
      }, 'photo')
      .where(`photo_id = ${id}`)
      .getRawOne()
```

The value I get back here is:

```
 {
  photo: '(3,catPic.jpg,https://url.com/catPic.jpg,UK,"A description for cat pic",30,2,2)'
}
```

This data is correct, and the "rank is correct (the final 2 is the rank which is correct because this photo has the 2nd most number of votes) however for some reason its a string.

Could anyone advise on this?

Thanks

EDIT: Just to update, I do have this working via raw SQL:

```sql
SELECT * FROM    (
select * ,ROW_NUMBER () OVER (ORDER BY vote_count desc) AS rank
 FROM    "photo" s2 
) q
where id = 3
```

**Comment by alex-r89** [comment]
Sorry to post again but I have worked this out for anyone who runs into this same issue:

```js
    const server = await getConnection()
      .createQueryBuilder()
      .select('*')
      .from((subQuery) => {
        return subQuery
          .select('*')
          .addSelect('ROW_NUMBER () OVER (ORDER BY "vote_count" DESC) as "rank"')
          .from(Photo, 'photo')
      }, 'q')
      .where(`id = ${id}`)
      .getRawOne()
```

A question I have though: Is it a bad idea to use `*` in a `.select` for any reason?

**Comment by imnotjames** [comment]
It should be fine to select all columns like that.

However, you might want to add the row number select as:

`.addSelect('ROW_NUMBER () OVER (ORDER BY "vote_count" DESC)', 'rank')`

There's a second parameter to name the column.  If you do that you may not have to `select('*')`

**Comment by alex-r89** [comment]
> It should be fine to select all columns like that.
> 
> However, you might want to add the row number select as:
> 
> `.addSelect('ROW_NUMBER () OVER (ORDER BY "vote_count" DESC)', 'rank')`
> 
> There's a second parameter to name the column. If you do that you may not have to `select('*')`

That works. Thanks very much
