### ISSUE TITLE
Question about save method and transactions.

### ISSUE THREAD

**Issue by Pobx** [typeorm/typeorm#6536]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I have a question about Transaction and save method. What is difference of both ?. I read documentation about save method and they said normally save method is enable transactions. Transaction Section in example i see save method use inside transaction method(callback-style). it's make very confuse about both things. Please someone explain it to me. Thank you

**Comment by imnotjames** [comment]
`save` method saves a model to the underlying datastore.

Transactions create a transaction where - depending on the database and the transaction type - changes are queued up on the database side until you commit the transaction.

**Comment by Pobx** [comment]
Thank a lot for your information.
