### ISSUE TITLE
Error When Connecting to Postgresql on GCP Using SSL

### ISSUE THREAD

**Issue by inmogr** [typeorm/typeorm#6537]
**Issue type:**

[ ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have created a Postgresql instance on GCP and enabled SSL, I'm able to connect to the instance using command line just fine however getting error when trying to connect using TypeORM on NodeJS running on localhost (haven't deployed yet, just in case this info helps)

```
const options = {
    type: "postgres",
    host: "IP_ADDRESS",
    port: 5432,
    username: "USERNAME",
    password: "PASSWORD",
    database: "DATABASE_NAME",
    schema: "SCHEMA_NAME",
    logging: false,
    synchronize: false,
    dropSchema: false,
    extra: {
        ssl: "verify-ca",
    },
    ssl: {
        ca: `-----BEGIN CERTIFICATE-----
THE CERTIFICATE DOWNLOADED FROM GCP
-----END CERTIFICATE-----`,
        cert: `-----BEGIN CERTIFICATE-----
THE CERTIFICATE DOWNLOADED FROM GCP
-----END CERTIFICATE-----`,
        key: `-----BEGIN RSA PRIVATE KEY-----
THE CERTIFICATE DOWNLOADED FROM GCP
-----END RSA PRIVATE KEY-----`,
    },
};

```

then getting the following error
```
[Error: root certificate file "/Users/USERNAME/.postgresql/root.crt" does not exist
Either provide the file or change sslmode to disable server certificate verification.
]
```

well since this is a code that should be deployed later on somewhere on cloud surely i'm not expecting to use local path!

can anyone help me here TYPEORM should use the certificate provided in the options

**Comment by sukhrajghuman** [comment]
Also having the same issue, have you had any luck figuring it out? @inmogr

**Comment by inmogr** [comment]
@sukhrajghuman not yet, looking forward for some help

**Comment by inmogr** [comment]
@sukhrajghuman any advice please?

**Comment by sukhrajghuman** [comment]
I realized my error was slightly different to yours, and I tried the following and it was working for me

```
ssl: {
        ca: fs.readFileSync('./ca.pem')
        cert: fs.readFileSync('./cert.pem'),
        key: fs.readFileSync('./key.pem'),
    },
```

I also ended using the cloud proxy instead, it was easier to set up IMO.

This reference may also help:
https://node-postgres.com/features/ssl

**Comment by imnotjames** [comment]
The issue is that you're passing `ssl` in `extra`.

That's overriding the `ssl` set in the connection options so you're not actually passing your certificates to the underlying postgres driver.

---

For other questions or support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by leaveittogod0123** [comment]
I encountered the same issue. 
In my case, I took a detour 'cloud sql proxy' https://cloud.google.com/sql/docs/mysql/sql-proxy
