### ISSUE TITLE
Mock transactionentity manager with jest

### ISSUE THREAD

**Issue by rubiin** [typeorm/typeorm#6546]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```js
	await getManager().transaction(async transactionalEntityManager => {
				const userId = await transactionalEntityManager
					.getRepository(UserType)
					.save({
						user_type: dto.user_type,
						description: dto.description,
						created_by: userRequesting.idx,
					});

				const incomingPermissions = await getManager()
					.getRepository(Permission)
					.find({
						where: { idx: In(dto.permission) },
						select: ['id', 'base_name'],
					});

				console.log('incoming ', incomingPermissions);

				const permissionBulkAdd = [];

				for (const element of incomingPermissions) {
					const permission = new PermissionUserType();
					permission.idx = element.idx;
					permission.userType = userId;
					permission.base_name = element.base_name;
					permission.permission = element;
					permissionBulkAdd.push(permission);
				}

				await transactionalEntityManager
					.getRepository(PermissionUserType)
					.save(permissionBulkAdd);
			});
			return { statusCode: 200, message: 'User type Added' };
		}
```

I have to mock transactionentity manager but do not know how to for this snippet. I am using jest for testing

**Comment by imnotjames** [comment]
We're tracking documentation issues for this in #5308 

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
