### ISSUE TITLE
Dynamic entity reference

### ISSUE THREAD

**Issue by NaumovEvgeniy** [typeorm/typeorm#6547]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an entity which should to have reference to different entities in the runtime. For example. 

_That's entity which has dynamic reference:_

    @Entity()
    export class Node<E extends Ex> {
		@PrimaryColumn()
		public nodeId?: number;

		@ManyToOne<E>(
		 	() => E, // HERE IS AN ERROR (I KNOW WHY, BUT IDEOLOGICALLY IT MIGHT BE THE BEST SOLUTION)
	 		e => e.id,
		)
		@JoinColumn({
			name: 'ex_node_id',
		})
		public exNode?: E;
   	 }

_That's base entity for exNode_

    export abstract class Ex {
    	@PrimaryColumn()
    	public id?: number;
    }

_Here is example reference entity_

    @Entity()
    export class Resource extends Ex {
    	// here some fields
    }

**I want to use this entities like this:**
`getRepository(Node<Resource>).findOne(1)`

Is to possible to use dynamic reference? I hope yes :) Thanks.

**Comment by hcesar** [comment]
You could try a function that returns a class:

```
function getNode<E>(relation) {
     return class{ 
@ManyToOne(
	 	() => relation,
 		e => e.id,
	)
	@JoinColumn({
		name: 'ex_node_id',
	})
	public exNode?: E;
     }
}
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
