### ISSUE TITLE
Find options JSON serialization

### ISSUE THREAD

**Issue by marcomag89** [typeorm/typeorm#6548]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

is there a way to serialize this query with operator function in json in order to send it to a rest service?
eg:
`{ name: Not("negate me") }` to ` {"name": {"$not": "negate me" }}`

**Comment by imnotjames** [comment]
No.  It may be eventually, but not currently.  You'd have to translate it yourself.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
