### ISSUE TITLE
Docs completely broken?

### ISSUE THREAD

**Issue by stevemarksd** [typeorm/typeorm#6551]
All pages on https://typeorm.io/  render `Found a typo and want to contribute to the documentation? Edit this page on Github!`

Slack link is broken: https://typeorm.slack.com/join/shared_invite/enQtNDQ1MzA3MDA5MTExLTUxNTZhM2Q4NDNhMjMzNjQ2NGM1ZjI1ZGRkNjJjYzI4OTZjMGYyYTc0MzAxYTdjMWE3ZDIxOWUzZTdlM2QxNTY#/ `This link is no longer active`

**Comment by stevemarksd** [comment]
docs seem fixed today - slack link still broken

**Comment by imnotjames** [comment]
Slack link should be fixed
