### ISSUE TITLE
How to SET PostgreSQL runtime configuration variables safely without transaction

### ISSUE THREAD

**Issue by nosteiner** [typeorm/typeorm#6555]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'd like to set postgres runtime variables for example: 

```SET app.config_a = 'a'```
Id like to make that configuration in a context of query execution but without using transaction and ```SET LOCAL```, and most important make it safe, so that when other app user send a request to the server the configuration will be sync with the authenticated app user triggered the query.

What is the recommended way to do it? usually I prefer using BaseEntity API.

I'd like to have something like this: 
```
--- project.service.ts
   import { getConnection } from 'typeorm';

   async findOneById(id: number): Promise<Project> {
----> Something like: getConnection().query(`SET app.config = $1;`, [thisUserConfig])
        return await Project.findOne({ id });
    }
```

**Comment by nosteiner** [comment]
The solution is to use `QueryRunner`, the relevant documentation added on #7351

**Comment by petmat** [comment]
Can you please clarify how `QueryRunner` is the solution? I don't see anything in the documentation about how to use `SET`.
