### ISSUE TITLE
Using multiple connections with env vars

### ISSUE THREAD

**Issue by SEdilson** [typeorm/typeorm#6556]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I want to use multiple databases o my app but I'm using env vars to configure connections. Is there a way to multiple connections using env vars?

**Comment by imnotjames** [comment]
You'd have to manually create the connections and map your custom environment variables to the connections.
