### ISSUE TITLE
Migration does not pick up change from @PrimaryColumn('uuid') to @PrimaryGeneratedColumn('uuid')

### ISSUE THREAD

**Issue by ekzyis** [typeorm/typeorm#6559]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When changing the column from `@PrimaryColumn('uuid')` to `@PrimaryGeneratedColumn('uuid')` the change is not picked up by `typeorm migration:generate`.

Minimal reproduction repository: https://github.com/ekzyis/typeorm-migration-bug

Notice that in src/migration there is no SQL query which adds the DEFAULT `uuid_generate_v4()` for the "id" column:

```
$> cat src/migration/*
```
```ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class uuidPrimarycolumn1597323504633 implements MigrationInterface {
    name = 'uuidPrimarycolumn1597323504633'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "age" integer NOT NULL, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "user"`);
    }

}
import {MigrationInterface, QueryRunner} from "typeorm";

export class addColumn1597324084864 implements MigrationInterface {
    name = 'addColumn1597324084864'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" ADD "test" character varying NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "test"`);
    }

}
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by joel31415** [comment]
I've run into the same issue: https://github.com/typeorm/typeorm/issues/5898
