### ISSUE TITLE
Ordering by the COUNT of a relation

### ISSUE THREAD

**Issue by sekaru** [typeorm/typeorm#6561]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm a bit confused by how to order my data by the COUNT of a relation. If I have a post with likes:

```
@Entity()
class Post {
  @OneToMany('PlaceLike', 'place', { cascade: true, eager: true })
  likes: PlaceLike[]
}
```

How do I ORDER BY the number of Likes a Post has? There seems to be a few undocumented/deprecated ways like `@RelationCount` and `loadRelationCountAndMap` but they don't really work. Any ideas?

**Comment by thomasdissert** [comment]
I'm currently facing the same problem on a postgres.

My Query looks more or less like this:

```
const sql = await connection
      .getRepository(PlatformUsers)
      .createQueryBuilder('platformUsers')
      .loadRelationCountAndMap('platformUsers.userLikesCount', 'platformUsers.userLikes')
      .execute();
```

which results in 

```
SELECT "platformUsers"."id" AS "platformUsers_id", "platformUsers"."name" AS "platformUsers_name" FROM "public"."platform_users" "platformUsers"
```

So this is exactly the same as when I comment out the `loadRelationCountAndMap` method. There is neither an error nor a sql clause added by that.

**Comment by thomasdissert** [comment]
Ok, so I've actually found a workaround which is quite straight forward:

```
const sql = await connection
      .getRepository(PlatformUsers)
      .createQueryBuilder('platformUsers')
      .select('platformUsers.id')
      .addSelect('COUNT(userLikes.id) as userLikesCount')
      .leftJoin('platformUsers.userLikes', 'userLikes')
      .groupBy('platformUsers.id')
      .orderBy('userLikesCount', 'DESC')
      .execute();
```

**Comment by sekaru** [comment]
Thanks @thomasdissert I was doing the join first which confused me too. That actually works great but in my case it would be good to have those `likes` come in on the entity. Obviously right now to get the like count they're being grouped so only one like comes back with a SELECT - I wondered if there's a simple way to then ungroup the likes?

**Comment by thomasdissert** [comment]
> Thanks @thomasdissert I was doing the join first which confused me too. That actually works great but in my case it would be good to have those `likes` come in on the entity. Obviously right now to get the like count they're being grouped so only one like comes back with a SELECT - I wondered if there's a simple way to then ungroup the likes?

You should be able to accomplish that by using `json_agg('likes')`, not sure though

**Comment by nangongmo** [comment]
@sekaru
 just 
```
this.createQueryBuilder('a')
                .select('a.id')
                .addSelect((subQuery) => {
                    return subQuery
                        .select('COUNT(c.id)', 'count')
                        .from(Comment, 'c')
                        .where('c.article.id = a.id');
                }, 'count')
                .orderBy('count', 'DESC')
                .loadRelationCountAndMap('a.comment_count', 'a.comments')
```
both has orderBy and Count

**Comment by aboveyunhai** [comment]
> @sekaru
> just
> 
> ```
> this.createQueryBuilder('a')
>                 .select('a.id')
>                 .addSelect((subQuery) => {
>                     return subQuery
>                         .select('COUNT(c.id)', 'count')
>                         .from(Comment, 'c')
>                         .where('c.article.id = a.id');
>                 }, 'count')
>                 .orderBy('count', 'DESC')
>                 .loadRelationCountAndMap('a.comment_count', 'a.comments')
> ```
> 
> both has orderBy and Count

wouldn't this cause querying Comment twice unnecessarily ? one from `addSelect` and one from `load relation`?
I felt like it may cause performance issue. Correct me if I'm wrong

**Comment by kakasoo** [comment]
I agree with you. There is a problem here. LoadRelationCountAndMap is mapped, but does not work properly when sorted, and addSelect is not mapped, but can be sorted. Eventually, there is a problem of having to use both.

```typescript
query
    .loadRelationCountAndMap('user.itemCount', 'user.items', 'itemCount') // mapped, but can't be sorted.
    .addSelect((qb) => {
        return qb.select('COUNT(item.id)', 'count').from(ItemEntity, 'item'); // can't be mapped, but can be sorted. ( getMany )
    }, 'count')
    .orderBy('count', 'DESC');
```
I hope that it help other people.

**Comment by evgenyidf** [comment]
> 

Right, works for 'order by' but not for 'where'

**Comment by khalidsheet** [comment]
I know this might be a late response 
but this one helped me solve the problem

```typescript
return await customerRepo
    .createQueryBuilder("user")
    .leftJoinAndSelect("user.purchases", "purchase")
    .where("user.deletedAt is null")
    .groupBy("user.id")
    .orderBy("COUNT(purchase.id)", "DESC")
    .getMany();
```

Now I have a list of customers ordered by their purchases count.
