### ISSUE TITLE
Mocking Connection results in "Error: TS2590"

### ISSUE THREAD

**Issue by JeremyLoy** [typeorm/typeorm#6562]
https://github.com/marchaos/jest-mock-extended/issues/36

**Comment by imnotjames** [comment]
I don't think this is something we can really control - if you have a specific suggestion, happy to hear it.  This seems to be a problem with the mechanisms that the library uses to mock out functionality.

If there's a more actionable outcome from this, let us know, but to be frank I've never used that and don't have the slightest idea on where to start with what could have gone wrong there.

As such, I'm going to be closing this out - but don't take that at us not wanting to hear more (I've subscribed to the linked issue!).  Instead, given the amount of requests we need something a bit more actionable.
