### ISSUE TITLE
MySql for Expo compatibility

### ISSUE THREAD

**Issue by eduardoalba0** [typeorm/typeorm#6563]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`Im readed the documentation of lib, and i saw that Expo version have support with sqlite, but not find nothing about compatibility for Mysql for react-native (expo) im trying to do this but without succes... is that compatible withExpo?`

**Comment by imnotjames** [comment]
There's no MySQL module that works on the browser.  As such, you cannot use the MySQL driver in react native / other browser based contexts
