### ISSUE TITLE
What's the best practice to remove Seller with many Products (> 20k rows)? Remove freezes process to death.

### ISSUE THREAD

**Issue by idchlife** [typeorm/typeorm#657]
I was kinda oblivious when writing one remove of parent entity :D (Seller)
I also wrote cascadeRemove on Product entity, so it will be removed along with Seller, but I guess typeorm just tries to load every subentity into memory and then dies with error "foreign key constraints - so I also misused cascadeRemove apparently).

I think the best way to just execute plain sql for deletion in this case?

**Comment by pleerock** [comment]
simply do: 

```ts
await connection.createQueryBuilder()
.delete()
.from("many_to_many_table_name", "postCategories")
.where("postCategories.many_to_many_table_name.column1 = :value", { value: 1 })
.execute();
```
