### ISSUE TITLE
pool.errorHandler

### ISSUE THREAD

**Issue by normanmanulife** [typeorm/typeorm#6570]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `typeorm@0.2.24` 

I registered errorHandler, but from errorHandler, how to I forcibly close the connection? And would connection pool auto respawn a new one? (I tried manaully kill from database side MSSQL, via TSQL KILL / SQL Management Studio. I actually observed typeorm can auto-respawn)
The motivation is, if some external event (prod incidents i am still investigating) render my connectons in typeorm connection pool to some faulty state (Half dead but not quite), I want the ability to reconnect.

```
import { Inject } from '@nestjs/common';
import { TypeOrmOptionsFactory, TypeOrmModuleOptions } from '@nestjs/typeorm';
import { SomeLoggingService } from '... logger.service';
import { DatabaseSettings } from '... /database-settings.model';
import { ConfigModule } from '... /config.module';

export class TypeOrmOptions implements TypeOrmOptionsFactory {
  constructor(
    @Inject(SomeLoggingService)
    private readonly mylogger : SomeLoggingService,
  ) {}

  onError(error: any)
  {
    this.mylogger.error(`ORM onError: ${error.message}`, error.stack);

    // **QUESTION HERE:** close the connection? (Would pool auto re-spawn a new one after?)
  }

  createTypeOrmOptions(): TypeOrmModuleOptions {
    const settings = ConfigModule.retrieveSetting<DatabaseSettings>(
      DatabaseSettings,
      'database',
    );
    return {
      type: 'mssql',
      host: settings.hostUrl,
      port: settings.port,
      username: settings.username,
      password: settings.password,
      database: settings.databaseName,
      keepConnectionAlive: false,
      synchronize: false, // IMPORTANT: please DO NOT set this = true: will clear data whenever app start
      entities: [__dirname + '/../../../business/entities/*{.ts,.js}'],
      logger: this.customLoggerService,
      name: settings.connectionName,
      logging: settings.logging,
      pool : {
        min : settings.poolMinSize,
        max: settings.poolMaxSize,
        errorHandler : this.onError
      },
      options: Object.assign({}, dbOptions),
    };
  }
}

```

Reference:
autoReconnect option: https://github.com/typeorm/typeorm/issues/6569

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
