### ISSUE TITLE
Could not find array type for data type text[]

### ISSUE THREAD

**Issue by zefexdeveloper** [typeorm/typeorm#6572]
Hi guys. I'm trying to create a column that will go an array of tags, for example:

```js
@Column('text', { array: true })
tags!: string[]
```

Everything is working fine, I can easily add new entries but the problem comes when trying to retrieve by tags.

`.find({ services: Any(['fast']) })`

This is giving me an error saying:

> QueryFailedError: could not find array type for data type text[]

I tried to create the query using raw SQL that way:

`.createQueryBuilder().where(':tag = ANY(tags)', { tag: 'fast' }).getOne()`

It only works that way so I'm wondering, why the first version using the built in `Any` isn't working? I can't find anything on the documentation and every issue one GitHub is closed without answers.

Thank you very much

**Comment by thadeucity** [comment]
Did you found the solution?
