### ISSUE TITLE
typeorm migration:generate command not work for last version ts-node and typescript

### ISSUE THREAD

**Issue by thinksource** [typeorm/typeorm#6597]
[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[* ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

build a entity fold with some entity, and using example ormconfig.json like:

```
{
   "type": "mysql",
   "host": "localhost",
   "port": 3306,
   "username": "admin",
   "password": "password",
   "database": "test",
   "synchronize": true,
   "logging": false,
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}
``` 
and then run 
```
ts-node ./node_modules/typeorm/cli.js "migration:generate" "-n" "init"
```
then there is error:

```
/mnt/c/workgit/orm/src/entity/Contact.ts:10
import { Entity, Column, ManyToOne, PrimaryGeneratedColumn } from "typeorm";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1167:16)
    at Module._compile (internal/modules/cjs/loader.js:1215:27)
    at Module.m._compile (/mnt/c/workgit/orm/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/mnt/c/workgit/orm/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Function.PlatformTools.load (/mnt/c/workgit/orm/src/platform/PlatformTools.ts:137:28)
```
this error happens when I upgrade my package.json devDependencies:
from
```
      "ts-node": "3.3.0",
      "typescript": "^3.3.3333"
```
to 

```
      "ts-node": "8.10.2",
      "typescript": "3.9.7"
```

**Comment by gitaumoses4** [comment]
Hey. 
For this, you will need to ensure your `tsconfig.json` has `module = commonjs`
```
{
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

**Comment by imnotjames** [comment]
This seems like a problem outside of TypeORM.

Instead, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by CanKattwinkel** [comment]
Had the same situation, this mislead me into thinking my ts-node call was wrong. In the end I just had a wrong import in one of the entities (`typeorm/browser` instead of  `typeorm`) that got autogenerated. 

Ensuring that all imports are from `typeorm` **fixed** it for me.
