### ISSUE TITLE
typeorm many to many relation / one side with composite keys

### ISSUE THREAD

**Issue by sptGabriel** [typeorm/typeorm#6598]
**Issue type:**

[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x  ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

My products table has a primary key composed of a serial + the product id,

I would like to know if in my relationship many to many I can use only one key of these primary keys

is it possible to define this in typeorm?

In other words, use only a primary key of a composite key in a many to many relationship

**Employees:**

```

@Entity({ name: 'employees' })
@Index(['matricula'], { unique: true })
export default class Employee {
  constructor(firstName: string, lastName: string) {
    this.firstName = firstName;
    this.lastName = lastName;
  }
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'matricula', nullable: false })
  matricula: string;

  @Column({ name: 'first_name', nullable: false })
  firstName: string;

  @Column({ name: 'last_name', nullable: false })
  lastName: string;

  @Column()
  departament_id: string;

  @ManyToMany(type => Products)
  @JoinTable({ name: 'employees_has_products' })
  products: Products[];

  //departament relations
  @OneToOne(
    () => Departament,
    (departament: Departament) => departament.manager,
  )
  @ManyToOne(
    () => Departament,
    (departament: Departament) => departament.employees,
  )
  @JoinColumn({ name: 'departament_id' })
  departament: Departament;

  //user relations
  @OneToOne(() => User, (user: User) => user.employee, {
    cascade: ['insert'],
  })
  user: User;

  //equipament relations
  @OneToMany(type => Equipament, equipament => equipament.employees)
  equipaments: Equipament[];

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @CreateDateColumn({ name: 'updated_at' })
  UpdatedAt: Date;
}
```

**Products:**

```
@Entity({ name: 'products' })
export default class Products {
  @PrimaryGeneratedColumn()
  serial_number: string;

  @ManyToOne(type => Product, product => product.products, { primary: true })
  @JoinColumn({ name: 'product_id' })
  product: Product;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @CreateDateColumn({ name: 'updated_at' })
  UpdatedAt: Date;
}
```

**Comment by imnotjames** [comment]
Yes, this is possible.

For other questions or more information, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
