### ISSUE TITLE
[Feature Request] better-sqlite3 support

### ISSUE THREAD

**Issue by Floffah** [typeorm/typeorm#6599]
**Issue type:**

- [ ] bug report
- [x] feature request
- [ ] documentation issue

**Database system/driver:**

- [ ] `cordova`
- [ ] `mongodb`
- [ ] `mssql`
- [ ] `mysql` / `mariadb`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `cockroachdb`
- [x] `sqlite`
- [ ] `sqljs`
- [ ] `react-native`
- [ ] `expo`

**TypeORM version:**

- [x] `latest`
- [ ] `@next`
- [ ] `0.x.x` (or put your version here)

**Feature request:**
I would like for there to be support for better-sqlite3 as well as sqlite3 as research proves it is way faster

**Comment by imnotjames** [comment]
The `sqlite3` module is the sqlite driver.  `better-sqlite3` is included as a driver as well and will be available with the next release.

**Comment by Floffah** [comment]
yea the benchmarks for better-sqlite3 are much better i cant wait for that release

**Comment by Floffah** [comment]
do you know when this will be released

**Comment by imnotjames** [comment]
It's unclear when another minor release will be cut.  Probably within the next few months, judging by the previous cadence.

**Comment by Floffah** [comment]
ah ok thank you anyway
