### ISSUE TITLE
Schema generation fails silently when @PrimaryColumn is ommitted

### ISSUE THREAD

**Issue by timwhit** [typeorm/typeorm#66]
I have the following working entity:

``` @Table('address')
export class AddressDbSchema implements AddressDTO {
    @PrimaryColumn()
    public _id?: string;
    @Column()
    public address1: string;
    @Column()
    public address2?: string;
    @Column()
    public city: string;
    @Column()
    public state: string;
    @Column()
    public zip: string;
    @Column()
    public country: string;
}
```

Here's the calling code:

``` @injectable()
export class AddressRepositoryImplDb implements AddressRepository {
    private addressRepository: Repository<AddressDbSchema>;

    constructor() {
        this.connect().then(async connection => {
            this.addressRepository = connection.getRepository(AddressDbSchema);
        });
    }

    public async findAll(): Promise<Array<AddressDTO>> {
        return await this.addressRepository.find();
    }

    public async create(addressDTO: AddressDTO): Promise<AddressDTO> {
        return await this.addressRepository.persist(addressDTO);
    }

    public async update(addressDTO: AddressDTO): Promise<AddressDTO> {
        return await this.addressRepository.persist(addressDTO);
    }

    public async find(id: string): Promise<AddressDTO> {
        return await this.addressRepository.findOneById(id);
    }

    private connect(): Promise<Connection> {
        return createConnection({
            driver: {
                type: 'sqlite',
                storage: 'tmp/sqlitedb.db'
            },
            logging: {
                logQueries: true,
                logSchemaCreation: true
            },
            autoSchemaSync: true,
            entities: [
                AddressDbSchema
            ]
        });
    }
}
```

If I modify the entity to look like this, schema generation fails, but I get no error messages.

``` @Table('address')
export class AddressDbSchema implements AddressDTO {
    @Column()
    public _id?: string;
    @Column()
    public address1: string;
    @Column()
    public address2?: string;
    @Column()
    public city: string;
    @Column()
    public state: string;
    @Column()
    public zip: string;
    @Column()
    public country: string;
}
```

**Comment by pleerock** [comment]
it should give an error because its impossible to create an entity without primary column. Is with primary column everything works okay?

**Comment by timwhit** [comment]
Yes, when I add `@PrimaryColumn` to the entity it works fine. When I replace it with `@Column`, I see no errors in the console.

A couple questions:

1. Is there a reason that an entity must have a `@PrimaryColumn`? I don't know of any databases with this requirement. When modeling existing database schemas, this could cause issues.
1. Do you have any idea why I'm not seeing an error output in this scenario? Are you able to replicate?

**Comment by pleerock** [comment]
> Is there a reason that an entity must have a @PrimaryColumn? I don't know of any databases with this requirement. When modeling existing database schemas, this could cause issues.

its not a database requirement. its orm requirement. without knowing about primary column its impossible to perform some major operations orms does, such as for example, to find if entity needs to be updated or inserted on persistence. as I know some other orms makes this restrictions too

> Do you have any idea why I'm not seeing an error output in this scenario? Are you able to replicate?

No, I have that check, but don't know why its not working in your case. Its not a big issue thats why I'll check it later. But anyway you have no choice - you have to use primarycolumn using this orm

**Comment by 19majkel94** [comment]
@timwhit If `createConnection` is a promise, isn't it rejected on error? Maybe you forgot to `catch()` it and log error on console?

**Comment by timwhit** [comment]
Thanks.

I updated the connection code and I'm getting the error now.

```
        this.connect().then(async connection => {
            this.addressRepository = connection.getRepository(AddressDbSchema);
        }).catch(err => logger.error('Cannot connect to database', err));
```

I would request that the examples on the README include this as I basically just copied the examples and none of them include `catch`.

**Comment by pleerock** [comment]
sure readme should be updated, good catch

**Comment by 19majkel94** [comment]
> I would request that the examples on the README include this as I basically just copied the examples and none of them include catch.

Catching a promise is just as obvious as node.js API callback pattern:
```typescript
callAsyncFunction(parameter, function (err, res) {
    if (err) {
        return handleError(err);
    }
    doSomething();
});
```
Promise in a certain sense may be treated as a wrapper about callback pattern, so instead doing:
```typescript
this.connect().then((err, connection) => {
    if (err) {
        return handleError(err);
    }
    this.addressRepository = connection.getRepository(AddressDbSchema);
});
```
You receive err in `.catch()` - exactly like try-catch in synchronous programing:
```typescript
this.connect()
.then(connection => {
    this.addressRepository = connection.getRepository(AddressDbSchema);
})
.catch(err => {
    handleError(err);
});
```
With async-await:
```typescript
try {
   const connection = await this.connect();
   ...
} catch (err) {
   handleError(err);
}
```
But like documenting throwing error, @pleerock can write info that it rejects promise on error in one of the examples.

**Comment by pleerock** [comment]
added to readme docs `catch` to examples

**Comment by timwhit** [comment]
Thank you!
