### ISSUE TITLE
Specifying a RETURNING or OUTPUT clause with QueryBuilder

### ISSUE THREAD

**Issue by tjme** [typeorm/typeorm#660]
Is there a way to explicitly specify a PostgreSQL RETURNING (or MSSQL OUTPUT) clause for INSERT and UPDATE queries, using QueryBuilder in TypeORM version 0.1.0?
I note it is mentioned in #361, but that is for EntityManager and appears to be implicitly generated.

**Comment by pleerock** [comment]
explicitly there is no way at the moment. But theoretically we can do that via `InsertQueryBuilder` by adding `returning` method. But it will work only in postgres and mssql. Its easy feature to implement, if you want feel free to contribute.

**Comment by tjme** [comment]
I've had a go at drafting some simple changes as below (please also see attached zip for more details).
They may be wrong, and there's no parameter checking or error reporting!

Note also that it seems that PostgreSQL and MSSQL support the clause for DELETE as well.

Add to QueryExpressionMap.ts (perhaps after valuesSet):
    returning: string = "";

In each of DeleteQueryBuilder.ts, InsertQueryBuilder.ts and UpdateQueryBuilder.ts, add:
import {SqlServerDriver} from "../driver/sqlserver/SqlServerDriver";
import {PostgresDriver} from "../driver/postgres/PostgresDriver";
...
    returning(returning: string): this {
        this.expressionMap.returning = returning;
        return this;
...
and replace existing return statement with (e.g. for insert):
        if (this.expressionMap.returning !== "" && this.connection.driver instanceof PostgresDriver) {
            return `INSERT INTO ${tableName}(${columnNames}) VALUES ${values} RETURNING ${this.expressionMap.returning}`;
        } else if (this.expressionMap.returning !== "" && this.connection.driver instanceof SqlServerDriver) {
            return `INSERT INTO ${tableName}(${columnNames}) OUTPUT ${this.expressionMap.returning} VALUES ${values}`;
        } else {
            return `INSERT INTO ${tableName}(${columnNames}) VALUES ${values}`;
        }

[TypeORM-Returning.zip](https://github.com/typeorm/typeorm/files/1149287/TypeORM-Returning.zip)

**Comment by pleerock** [comment]
zip? OMG dude its github, you should publish your code in git repos! Also please format your code properly, its very hard to read what you wrote. Yeah you need to do something like what you wrote, but try to remove duplication of "INSERT INTO" statement. Simply create 4 blocks of code - insert, output, values, returning. You are on the right way so start creating a pull request.

**Comment by pleerock** [comment]
thanks to @tjme this new feature will be released in `0.1.0-alpha.33`
