### ISSUE TITLE
Recursively Load Relations

### ISSUE THREAD

**Issue by yonilerner** [typeorm/typeorm#661]
I have some nested structure in the following form:
```javascript
{
    node: {
      id: 1
      value: 'value',
      edges: [
         {
            id: 1,
            node: {
             id: 2,...
          }, ...
      ]
}
```
In the database they are stored in two tables, `node` and `edge`, respectively.

A `node` row looks like:
```
id | value
1  | someValue
2  | someOtherValue
```

An `edge` row looks like:
```
id | from_node_id | to_node_id
1  | 1            | 2
```

How would I get TypeOrm to recursively load the entire tree (starts from a `node`.`id`, and stops fetching when there is no `edge` such that `edge`.`from_node_id`=`node`.`id`)?

Thanks!

**Comment by pleerock** [comment]
how would you express that in SQL? If you will have sql for your task you can execute it via typeorm and get desired results

**Comment by yonilerner** [comment]
@pleerock 

Well its something like:

```sql
SELECT * FROM node AS from_node
INNER JOIN edge ON edge.from_node_id=from_node.id
INNER JOIN node AS to_node ON to_node.id=edge.to_node_id
WHERE from_node.id=1
```
and do that recursively for `from_node`.`id` until no rows are returned. Is there an easy way to set up a relation to do that, or do I have to just do the single `INNER JOIN` and keep calling it recursively like I would do in plain SQL?

**Comment by pleerock** [comment]
so you wanna say you would do such request:

```sql
SELECT * FROM node AS from_node
INNER JOIN edge ON edge.from_node_id=from_node.id
INNER JOIN node AS to_node ON to_node.id=edge.to_node_id
....
WHERE from_node.id=1
```

Because in reality you won't. First number of allowed joins is limited you can only do near 64 joins depend on database. Second its inefficient to use more then few joins. You probably need to re-think your database model. Try to use `@ClosureEntity` and TreeRepository - I think that would help you.

**Comment by yonilerner** [comment]
Will do, thanks
