### ISSUE TITLE
Changes in model are not being detected when generating migration

### ISSUE THREAD

**Issue by rubiin** [typeorm/typeorm#6611]
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I am using typeorm with nestjs. when I try change the entities and run  `npm run typeorm:generate` .The initial migration is generated instead of the migration file with alter queries for the respective changes

**Comment by imnotjames** [comment]
This is closer to a support request than a bug report.

Perhaps you are running against an in-memory database?  Or you aren't running the migrations after generating them.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
