### ISSUE TITLE
Bind parameters on oracle procedure

### ISSUE THREAD

**Issue by nildes** [typeorm/typeorm#6618]
**Issue type:**

[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[X] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

How to use typeorm to call a procedure with in and out parameters on oracle? I've tried to do this way but got this error: 

**Error: NJS-044: bind object must contain one of the following keys: "dir", "type", "maxSize", or "val"**

    public async findOne(one: string) {
        try {
            const connection = await getConnection()
            const sql: string = `
            begin
            procedure(:p0, :p1, :p2, :p3, :p4, :p5);
            end;
           `;

    const result: any = await connection.query(sql,[
        { dir: oracledb.BIND_IN, type: oracledb.STRING, value: one },
        { dir: oracledb.BIND_OUT, type: oracledb.CURSOR },
        { dir: oracledb.BIND_OUT, type: oracledb.CURSOR },
        { dir: oracledb.BIND_OUT, type: oracledb.CURSOR },
        { dir: oracledb.BIND_OUT, type: oracledb.STRING },
        { dir: oracledb.BIND_OUT, type: oracledb.STRING },
     ]
    );
        return Promise.resolve()
    } catch (reason) {
        return Promise.reject(reason);
    }
    }

**Comment by wfpena** [comment]
In the line: `{ dir: oracledb.BIND_IN, type: oracledb.STRING, value: one },` you put the name of the property as `value` it should be `val`.

There is no `value` property inside the `BindParameter` interface.

**Comment by imnotjames** [comment]
Looks like a typo in the source.  I'll be closing this as it seems to not be a problem with TypeORM.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by LucasSaib** [comment]
aconteceu o msm comigo não consegui resolver  type orm com oracle não é nada confiável.
