### ISSUE TITLE
[Question] How to do a query by super class?

### ISSUE THREAD

**Issue by mariliagb** [typeorm/typeorm#6619]
**Issue type:**

[x] `Question`

**Database system/driver:**

[x] `mssql`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

I have a system with entities like Todos, Projects, Documents and other features will come. All these features have an owner -  a relationship with User. I would like to load all features related with a certain User. What is the best way to do this? I'm from a Java background and for this example I'd have an abstract entity like BaseEntity with the relationship with User, then I could do criteria queries like "from BaseEntity b where b.user =...". How can I load all BaseEntities with TypeORM? This seems a simple example but more things in commom for this BaseEntity will come.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
