### ISSUE TITLE
Updating an entity without selecting beforehand.

### ISSUE THREAD

**Issue by crystalbyte** [typeorm/typeorm#662]
Hi there,

is there a way to update an entity without fetching it beforehand?

Regards

**Comment by yonilerner** [comment]
Just instantiate an instance of the model class and make sure it has a primary key, and then persist it.

Example:
```javascript
@Entity()
class Person {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  name: string
}

const person = new Person()
person.id = 1
person.name = 'Yoni'
await entityManager.getRepository(Person).persist(person) // value is essentially upserted

**Comment by crystalbyte** [comment]
Beautiful, thank you :)

**Comment by pleerock** [comment]
note you shall use `save` instead of `persist` method because `persist` is deprecated in latest versions.

**Comment by crystalbyte** [comment]
Thanks for the update.

**Comment by aseerkt** [comment]
I want to increment the value of column `comment_count` without fetching it beforehand. Is it possible?
```ts
await Post.update({ id: postId }, { commentCount:  { /* How to deal with this section */ } } );
```
