### ISSUE TITLE
My query works in DBeaver but I get 'could not determine data type of parameter $1' in typeorm querybuilder

### ISSUE THREAD

**Issue by binaryninja01** [typeorm/typeorm#6645]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi, I'm hitting postgresql with a GET query and I need query builder to bypass each value if it's null and not represented, so I've written the code below: 

```
    const transactionDetails = await this.transactionRepository
      .createQueryBuilder('transactions')
      .where(':app IS NULL OR transactions.app = :app', { app: data.app })
      .andWhere(':user_id IS NULL OR transactions.user_id = :user_id', { user_id: data.user_id })
      .andWhere(':start_date IS NULL OR created_at >= :start_date', { start_date: start_date })
      .andWhere(':end_date IS NULL OR created_at < :end_date', { end_date: end_date })
      .skip(data.skip)
      .take(data.max_result)
      .getMany()
```
but for some reason I'm getting the error below: 

`QueryFailedError: could not determine data type of parameter $1`

the fact is I tried the same query in postgresql shell and DBeaver and I got response, so the problem is somehow related to typeorm query builder, I was wondering if you could help me fix it.

**Comment by imnotjames** [comment]
Is `data.app` NULL or `undefined`? Pretty sure this is a problem with your query itself, not with TypeORM.

Perhaps try out `getQueryAndParameters()` and inspect what it is that's being generated & what's being passed.  If any of those are `undefined` and not `NULL` it could be causing issues.

For support and questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
