### ISSUE TITLE
bug: find In 

### ISSUE THREAD

**Issue by mjpcasey** [typeorm/typeorm#6646]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.19` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
  
    [x] `mysql`
    [ ] `postgres`

--!>

  Bug:   In a surprisingly serious bug, the local pressure test "this.find({id: In(array)})" is fine, but occasionally In a production environment, this code will come up with a result that is completely different from the id In array. And the result of this error is basically repeatable in my production environment. And there are only a few hundred pieces of data in the table, a few hundred concurrent

**Comment by imnotjames** [comment]
Without a way to replicate the issue I'm not sure we can do much. Can you help with creating a replication of this issue we can run in an isolated repository?

**Comment by imnotjames** [comment]
Going to close this for now but if you do manage to get a reproducible example ready to go we can reopen it and continue investigation.
