### ISSUE TITLE
QueryBuilder: CASE statement in orderBy when using join not supported

### ISSUE THREAD

**Issue by traysa** [typeorm/typeorm#6648]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.21` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I like to use a `leftjoin` and `orderby` with the typeorm querybuilder. The `orderby` has a more complex construct using a `case` statement.

Like this:

```ts
await DomainIssue.createQueryBuilder("di")
  .leftJoinAndSelect("di.occurrences", "dio")
  .where("di.domain = :domain")
  .take(mostSevereIssuesCount)
  .orderBy("di.severity", "DESC")
  .addOrderBy(`(CASE WHEN di.issuetype IN ('${criticalIssueMetaList.map(s => s.key).join("','")}') THEN 1 ELSE 0 END)`, "DESC")
  .addOrderBy("di.occurrencesCount", "DESC")
  .addOrderBy("di.id")
  .setParameter("domain", this.domain)
  .getManyAndCount()

```

This results into the following query: 
```sql
SELECT DISTINCT
  "distinctAlias"."di_id" as "ids_di_id",
  "distinctAlias"."di_severity", ,
  "distinctAlias"."di_occurrences_count",
  "distinctAlias"."di_id"
FROM (
  select
  	"di"."id" AS "di_id",
  	"di"."domain" AS "di_domain",
  	"di"."issuetype" AS "di_issuetype",
  	"di"."severity" AS "di_severity",
  	"di"."occurrences_count" AS "di_occurrences_count",
  	"dio"."id" AS "dio_id",
  	"dio"."occurrence_id" AS "dio_occurrence_id",
  	"dio"."domain_issue_id" AS "dio_domain_issue_id"
  FROM "domain_data"."domain_issue" "di"
  LEFT JOIN "domain_data"."domain_issue_occurrence" "dio" ON "dio"."domain_issue_id"="di"."id"
  WHERE "di"."domain" = $1
) "distinctAlias"
ORDER BY 
  "distinctAlias"."di_severity" DESC,
  (CASE WHEN issuetype IN ('foo1','foo2','foo3') THEN 1 ELSE 0 END) DESC,
  "distinctAlias"."di_occurrences_count" DESC,
  "distinctAlias"."di_id" ASC,
  "di_id" ASC
LIMIT 5
```

It seems that the more complex `orderby` is not supported.

**Comment by traysa** [comment]
Found a workaround here: https://github.com/typeorm/typeorm/issues/3167

I moved the CASE statement from the `addOrderBy` to a `addSelect` and then refer in the `addOrderBy` to the alias:

```
.addSelect(`CASE WHEN d.issuetype IN ('${criticalIssueMetaList.map(s => s.key).join("','")}') THEN 1 ELSE 0 END`, "_critical_issue")
...
.addOrderBy("_critical_issue", "DESC")
```
The alias name is case insensitive.

**Comment by imnotjames** [comment]
There's an injection risk in your select.  I suggest using parameters.

I think you found a good solution, and will be closing this out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by darrylmabini** [comment]
@imnotjames how to prevent the injection risk in the select? Is there a way to add a placeholder in `addSelect()`?

**Comment by darrylmabini** [comment]
It doesn't work with pagination with `skip()` and `take()`

**Comment by Huzaifaak1** [comment]
> It doesn't work with pagination with `skip()` and `take()`

Yes. Instead, try to use  ` .limit(take).offset(skip)`.
