### ISSUE TITLE
Run native MongoDB queries

### ISSUE THREAD

**Issue by makislav** [typeorm/typeorm#665]
Hello,

I am trying to use typeorm in my current project. As I only want to run one mongo db connection in my application I would like to know if it's also possible to run raw mongodb queries. 

(some of my queries are quite db intense and I don't need mapping in those cases)

Unfortunately connection.query() can't be used as it throws an error (Executing SQL query is not supported by MongoDB driver.).

Regards

**Comment by pleerock** [comment]
yes you can run whatever you want. All methods are available via [MongoRepository](https://github.com/pleerock/typeorm/blob/555cd69f46ae68d4686ba4a8e07a8d77a1ee3aad/src/repository/MongoRepository.ts#L56-L55) Example:

```ts
const postRepository = connection.getMongoRepository(Post);
// you can use mongodb-specific methods
// for example postRepository.find({ ... })
```

Can you please provide example of what you want to execute?

**Comment by makislav** [comment]
hello @pleerock,

I am working on a points-of-interest finder, this is an example query:

```ts
let query = {
            $and: [
                {
                    locationIndex: {$geoWithin: {$centerSphere: [[request.longitude, request.latitude], radius]}},
                },
                {
                    category: "restaurant"
                }
            ]
        };
```

**Comment by pleerock** [comment]
is it `find` query? Can you try running this:

```ts
const postRepository = connection.getMongoRepository(Post);
const results = await postRepository.find({ 
    where: {
$and: [
                {
                    locationIndex: {$geoWithin: {$centerSphere: [[request.longitude, request.latitude], radius]}},
                },
                {
                    category: "restaurant"
                }
            ]
     }
 });
```

**Comment by pleerock** [comment]
any updates?

**Comment by makislav** [comment]
Sorry for the delayed answer, it's not working it seems.

Small example:
User.ts
```ts
@Entity()
export class User {

    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    name: string;

    @Column("string")
    @Index({unique: true})
    email: string;
}
```

Test
```ts
let repository = connection.getMongoRepository(User);
let user = await repository.find(
        {
            where: {
                $and: [
                    {
                        name: "myname",
                    },
                    {
                        email: "your@mail.com"
                    }
                ]
            }
        }
);
```

Error:(100, 13) TS2345:Argument of type '{ where: { $and: ({ name: string; } | { email: string; })[]; }; }' is not assignable to parameter of type 'FindManyOptions<User> | Partial<User>'.
  Type '{ where: { $and: ({ name: string; } | { email: string; })[]; }; }' has no properties in common with type 'Partial<User>'.

The error regarding the previous example looks similar: The query has no properties in common with type 'Partial<Location>'

**Comment by pleerock** [comment]
this small ts compiler error is fixed and will be released in `0.1.0-alpha.33`

**Comment by makislav** [comment]
thank you very much, i really appreciate that!

**Comment by phil294** [comment]
@makislav How did you realize distinct queries with TypeORM?

**Comment by Abdullah8006** [comment]
@pleerock I wanted to paginate the subdocuments and was trying to use $slice operator but I do not see any way we can use it in typeorm. Do you have any idea how we can use $slice?
