### ISSUE TITLE
Fix / remove Documentation RE: "Roadmap"

### ISSUE THREAD

**Issue by peter-donovan** [typeorm/typeorm#6653]
**Issue type:**
[ ] bug report
[ ] feature request
[X] documentation issue

**Steps to reproduce or a small repository showing the problem:**
Visit https://typeorm.io/#/roadmap and view the "# Note on 1.0.0 release" content:

The documentation for the **Roadmap** currently states that "We are planning to release a final stable 1.0.0 version somewhere in Autumn 2018."

It is currently September 1, 2020 and since TypeORM follows semantic versioning, I assume that there is no **stable and official** `1.0.0` release in the near future.

I am merely pointing out what is essentially a "typo" at this point.

**Proposed fixes**:
1. Remove this portion of the documentation temporarily
2. Update the intended **stable** release date.

**Comment by pleerock** [comment]
You are absolutely right. We need to update docs.

**Comment by gtpan77** [comment]
#6818

**Comment by gtpan77** [comment]
@pleerock close this issue

**Comment by pleerock** [comment]
thank @gtpan77 !
