### ISSUE TITLE
[oracle] database in @Entity works in select, but not in create

### ISSUE THREAD

**Issue by liudonghua123** [typeorm/typeorm#6661]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I try to use typeorm for my oracle database, and I need to use another user's table `USR_YX.T_YX_PC`, and I do have releated privileges, the current database connection user is `USR_YX_STATISTICS`. So I write a demo entity like this.

```ts
import {Entity, PrimaryColumn, PrimaryGeneratedColumn, Column, BaseEntity} from "typeorm";

@Entity({name:'T_YX_PC',database:'USR_YX'})
export class PC extends BaseEntity {
//...
}
```

And then it will create `USR_YX_STATISTICS.T_YX_PC` table, but select `USR_YX.T_YX_PC` table.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by wfpena** [comment]
I think for oracle it would make more sense to use the `schema` property inside the `@Entity` annotation in this case no? Like this:


```
@Entity({name:'T_YX_PC',schema:'USR_YX'})
export class PC extends BaseEntity {
//...
}
```


And even so this is related to another issue (that is still open):  #5621 

There is the pull request [#6133](https://github.com/typeorm/typeorm/pull/6133) that fixes pretty much the same issue you have. Although this pull request actually solves using the `schema` property

**Comment by pirouet** [comment]
Hi, #6133 had some issues so I re-raised with #6673 that is now merged to master branch (no release for it yet). I think the oracle driver assumed that the tables would all be within the user's own schema therefore the schema is not necessarily needed then, however - and in my opinion best practice, would be to always specify it.

Hope this helps!
