### ISSUE TITLE
Case in where clause 

### ISSUE THREAD

**Issue by imashishsharma** [typeorm/typeorm#6662]
I'm using nestjs and typeorm in my application. I have a requirement to filter products by currency and price range.

Product can have different variants and each variant can have multiple prices. Each price is a combination of price and currency

My product range filter master data is something like

```
export const productPriceRangeMap: Map<string, number[]> = new Map([
  ['PLN', [5, 30]],
  ['EUR', [2,10]],
]);
for PLN currency, price ranges will be like 
low --> 0,5; medium --> 5,30; high --> 30+
```

So my requirement is like
```
Suppose a product has 3 variant A,B,C. 
A has two prices 1. USD 3, 2. PLN 20, 
B has two prices 1. USD 10,2. PLN 200, 
C has two prices 1. EUR 5, 2. GBP 30 
```

Now If I select Medium as price range, so only variant A should be returned if we are considering only PLN. And if consider PLN and EUR, variant A and C should be returned from the filter.
I have tried condition where clauses but that would be a hardcoding, I can support multiple currencies and many products which can then have many variants. Hence looking to a more generic query. Please help.

Thanks
[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Comment by rubiin** [comment]
Go with query builder on this one as it offers more flexibility for cases

**Comment by imnotjames** [comment]
You definitely need to use query builder for more complex queries.  It's doable there.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
