### ISSUE TITLE
Error using enum column type: column is of type content_status_enum but expression is of type character varying

### ISSUE THREAD

**Issue by ffxsam** [typeorm/typeorm#6667]
**Issue type:**

[X] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[X] `aurora-data-api-pg`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Following the example here:
https://github.com/typeorm/typeorm/blob/master/docs/entities.md#enum-column-type

I get this error when I run my test script:
```
BadRequestException: ERROR: column "status" is of type content_status_enum but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
```

Relevant models:

```ts
 export enum PhotoStatus {
  WORKING = 'WORKING',
  DONE = 'DONE'
}

@Entity()
@TableInheritance({ column: { type: 'varchar', name: 'type' } })
export class Content {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column()
  description: string;
}

export class Photo extends Content {
  @Column()
  size: string;

  @Column({
    type: 'enum',
    enum: PhotoStatus,
    default: PhotoStatus.WORKING,
  })
  status: PhotoStatus;
}
```

When trying to set the field via the following code, it throws the aforementioned error.

```ts
  const photo = new Photo();
  photo.title = 'Wow';
  photo.description = 'Last photo';
  photo.size = 'huge';
  photo.status = PhotoStatus.DONE;
  await connection.manager.save(photo);
```

**Comment by ffxsam** [comment]
This also occurs with uuid fields:

```ts
@Column({
  type: 'uuid'
})
fileUuid: string;
```

Trying to set the `fileUuid` column and save results in:
```
BadRequestException: ERROR: column "fileUuid" is of type uuid but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
```

**Comment by ffxsam** [comment]
I don't see how these tests are any different from my code:
https://github.com/typeorm/typeorm/blob/22414510f9c4f69cb0e48b8c2fce1b4910353d6b/test/functional/database-schema/simple-enums/enums.ts

I did modify my code to use repositories though, but I still get the same error.

```ts
import 'reflect-metadata';
import { createConnection } from 'typeorm';
import { Photo, PhotoStatus } from './entity/Photo';

(async function () {
  const connection = await createConnection();
  const repository = connection.getRepository(Photo);
  const photo = new Photo();

  photo.title = 'Photo Name';
  photo.description = 'Pic of a lake';
  photo.size = 'huge';
  photo.status = PhotoStatus.DONE;

  try {
    await repository.save(photo);
  } catch (e) {
    console.error(e);
  }
})();
```

**Comment by ffxsam** [comment]
@ArsenyYankovsky Ahh! This is an issue with the Aurora Data API Postgres driver.

**Comment by imnotjames** [comment]
this seems to be an upstream issue.  closing.
