### ISSUE TITLE
TypeError: where is not a function

### ISSUE THREAD

**Issue by messerbill** [typeorm/typeorm#667]
Hi me again,
the "whereInIds()" method seems not to be working correctly.

```
let userRepository = DatabaseConnection.connection.getRepository(User)
let users = await userRepository.createQueryBuilder("user").whereInIds(userIds).getMany()
```
this produces:

`(node:12984) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: where is not a function`

am i doing a mistake at my side or is it a bug of typeorm itself?

`tsc -v` 
> Version 2.4.1

i am using typeorm version `0.1.0-alpha.26`

Thanks a lot and greetings,
Messerbill

**Comment by pleerock** [comment]
there is a [test](https://github.com/typeorm/typeorm/blob/ef2417f1c95d3144e5b445f0098a84d7b8449515/test/github-issues/594/issue-594.ts#L24-L23) that checks `whereInIds` it works fine. Can you provide a smallest possible repo with reproduction of this problem?

**Comment by messerbill** [comment]
i will create one today or tomorrow, thanks for the fast response

**Comment by martinschleiss** [comment]
Just in case somebody stumbles upon the same issue: Make sure the ```userIds``` array has at least one element.
