### ISSUE TITLE
QueryBuilder fails to recognize different query parameters with prepared statements

### ISSUE THREAD

**Issue by InsOpDe** [typeorm/typeorm#6682]
**Issue type:**

[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
const query = idisAuditRepository
			.createQueryBuilder()
			.select("ad_table")
			.where("ad_table = :ad_table", {
				ad_table: "INSERTED"
			})
			.andWhere("ad_table = :ad_table", {
				ad_table: "UPDATE"
			})
console.log(query.printSql())
/** 
* prints
* SELECT ad_table FROM "AUDIT" "IdisAuditModel" WHERE ad_table = @0 AND ad_table = @1 -- PARAMETERS: ["UPDATE","UPDATE"]
*/
```

But should be `... ["INSERTED","UPDATE"]`

it boils down to the json-keys being the same: `ad_table` which is reflected with
```ts
query.getParameters()
/**
* prints
* { ad_table: 'UPDATE' }
*/
```

Is this intended?

And btw is there no better way to debug queries but to write a custom function for it?
```ts
const debugQuery = <Entity>(query: SelectQueryBuilder<Entity>): string => {
	let [select, parameters] = query.getQueryAndParameters()
	for (const index in parameters) {
		if (parameters.hasOwnProperty(index)) {
			const value = parameters[index]
			select = select.replace(`@${index}`, `\`${value}\``)
		}
	}
	return select
}
```

**Comment by imnotjames** [comment]
This is indeed intended - at this time, the query builder has a global scope for parameters, and in the docs that is defined as a shortcut for `where` & `setParameter`.

You'll need to use different parameters until we can do a backwards compatibility to change this.
