### ISSUE TITLE
Unable to set Collate Property

### ISSUE THREAD

**Issue by smartge3k** [typeorm/typeorm#6686]
**Issue type:**

[ ] bug report

**Database system/driver:**

[ ] `mssql`

**TypeORM version:**

[ ] `latest`

I am trying to add a column to the current table in the migration files and setting Collation. 
`await queryRunner.query('ALTER TABLE "me" ADD COLUMN "id" VARCHAR COLLATE  utf8mb4_bin  DEFAULT NULL ');
`
I get the following error
`ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"me" ADD COLUMN "id" VARCHAR SET COLLATE  utf8mb4_bin  DEFAULT NULL' at line 1`

Since I am migrating from Laravel migration files, the following is the line in those files.
`$table->string('id')->nullable()->collation('utf8mb4_bin');`

**Comment by imnotjames** [comment]
The correct SQL syntax for MSSQL is:

```
ALTER TABLE "me" ADD "id" VARCHAR COLLATE utf8mb4_bin DEFAULT NULL
```

Note that I omitted `COLUMN`

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
