### ISSUE TITLE
Loading hdb-pool in SapDriver but expecting in @sap/hdb-pool in PlatformTools

### ISSUE THREAD

**Issue by sickmartian** [typeorm/typeorm#6697]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `sap`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Since MR #6630 released with 0.2.26 trying to use HANA with `hdb-pool` won't work, it tries to load it as 'hdb-pool' but the case before calling the require checks for @sap/hdb-pool instead.

**Comment by imnotjames** [comment]
:grimacing: You're right.  We don't have SAP Hana running in CI (yet) so we didn't catch that.

**Comment by sickmartian** [comment]
> The case should just be `hdb-pool`, right?
Yes, I think so (I'm a bit late it seems 😅)

Thanks a lot for the effort.
