### ISSUE TITLE
MaxListenersExceededWarning occurs while testing with jest

### ISSUE THREAD

**Issue by kaito3desuyo** [typeorm/typeorm#6699]
**Issue type:**

[ * ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ * ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ * ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

After updating typeorm to 0.2.26, I'm getting a lot of title errors when testing with jest. It does not occur at >=0.2.25.

```
$ node --trace-warnings node_modules/.bin/jest -i --config ./test/jest-e2e.js
```

```
(node:9509) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at Client.addListener (events.js:406:10)
    at Client.once (events.js:437:8)
    at PostgresQueryRunner.<anonymous> (/home/hoge-api/src/driver/postgres/PostgresQueryRunner.ts:174:36)
    at step (/home/hoge-api/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/hoge-api/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/home/hoge-api/node_modules/tslib/tslib.js:107:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I'm using NestJS 7.4.4 as the api framework, but this issue is only caused by different versions of TypeORM.
The jest version is 26.4.2, the ts-jest version is 26.3.0, and the supertest version is 4.0.2.

**Comment by imnotjames** [comment]
Related to #6262 ?

**Comment by proutek** [comment]
Same here. My NestJS app now reports this warning during startup after upgrade to 0.2.26.

**Comment by imnotjames** [comment]
Are you using the Postgres pooling?

**Comment by kaito3desuyo** [comment]
Unfortunately, repositories are complex and not easy to duplicate.
However, I was able to confirm that the error disappeared by commenting out line 173 of `node_modules/typeorm/driver/postgres/PostgresQueryRunner.js` .
Therefore, it became clear that the changes made in PR #6262 have an effect.

```
PostgresQueryRunner.prototype.query = function (query, parameters) {
        var _this = this;
        if (this.isReleased)
            throw new QueryRunnerAlreadyReleasedError_1.QueryRunnerAlreadyReleasedError();
        return new Promise(function (ok, fail) { return tslib_1.__awaiter(_this, void 0, void 0, function () {
            var databaseConnection_1, queryStartTime_1, onError_1, err_1;
            var _this = this;
            return tslib_1.__generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        _a.trys.push([0, 2, , 3]);
                        return [4 /*yield*/, this.connect()];
                    case 1:
                        databaseConnection_1 = _a.sent();
                        this.driver.connection.logger.logQuery(query, parameters, this);
                        queryStartTime_1 = +new Date();
                        onError_1 = function (err) {
                            _this.release(err);
                        };
                        databaseConnection_1.once("error", onError_1);  // <-- Comment out here
                        databaseConnection_1.query(query, parameters, function (err, result) {
                            databaseConnection_1.removeListener("error", onError_1);
                            // log slow queries if maxQueryExecution time is set
                            var maxQueryExecutionTime = _this.driver.connection.options.maxQueryExecutionTime;
                            var queryEndTime = +new Date();
                            var queryExecutionTime = queryEndTime - queryStartTime_1;
                            if (maxQueryExecutionTime && queryExecutionTime > maxQueryExecutionTime)
                                _this.driver.connection.logger.logQuerySlow(queryExecutionTime, query, parameters, _this);
                            if (err) {
                                _this.driver.connection.logger.logQueryError(err, query, parameters, _this);
                                fail(new QueryFailedError_1.QueryFailedError(query, parameters, err));
                            }
                            else {
                                switch (result.command) {
                                    case "DELETE":
                                    case "UPDATE":
                                        // for UPDATE and DELETE query additionally return number of affected rows
                                        ok([result.rows, result.rowCount]);
                                        break;
                                    default:
                                        ok(result.rows);
                                }
                            }
                        });
                        return [3 /*break*/, 3];
                    case 2:
                        err_1 = _a.sent();
                        fail(err_1);
                        return [3 /*break*/, 3];
                    case 3: return [2 /*return*/];
                }
            });
        }); });
    };
```

**Comment by imnotjames** [comment]
Yeah - given that the stack trace directly points at it - can see that is the line that's the problem.  Removing that line isn't going to work - it was intentionally included to prevent another issue we were having - where errors were being ignored pre-query.

Unfortunately, I cannot replicate this locally - so without a working replication through either a repository (or enough information to build a repository) it's a lot harder to debug this further.

A repository or some other means of replicating the issue could answer the following questions, but without that...

What postgres version are you using?
What node postgres client are you installing?
How are you connecting?
What's your ORMConfig like?
Are you using the pooling features?
When are you seeing this error?
Is it only during testing? If so, are you mocking out something somewhere?
Is it possible this is something to do with nest and not with typeorm?

**Comment by kaito3desuyo** [comment]
* What postgres version are you using?‘
PostgreSQL 12.3 hosted by Docker.

* What node postgres client are you installing?
I'm sorry, I'm not a native English speaker, so I can't get the point.
If it refers to the Node.js pg module, the version is 8.3.3.

* How are you connecting?
API and DB are launched in the same network using docker-compose.
@nestjs/typeorm is installed in the API, and it connects to the DB through this. (and using same method in testing)

* What's your ORMConfig like?
It is the code of the setting part that works the same as ormconfig.json.
```
const ORM_CONFIG: TypeOrmModuleOptions = {
    type: 'postgres',
    url: process.env.DATABASE_URL,
    entities: [join(__dirname, '..', '..', 'libs', '**', '*.model.{ts,js}')],
    migrations: [
        join(
            __dirname,
            '..',
            '..',
            '..',
            'db',
            'migrations',
            '**',
            '*.{ts,js}',
        ),
    ],
    cli: {
        migrationsDir: 'db/migrations',
    },
    synchronize: false,
    logging: true,
    namingStrategy: new TypeOrmNamingStrategy(),
    // migrationsRun: true,
};
```
DATABASE_URL is set by docker-compose.yml as follows.
```
DATABASE_URL: postgresql://postgres:password@development-db/something_development
```

* Are you using the pooling features?
I haven't changed the DB settings manually, but please let me know if there is a way to check this just in case.

* When are you seeing this error?
I think it's time to start the e2e test and access to the DB.

* Is it only during testing? If so, are you mocking out something somewhere?
That's right. However, the e2e test does not mocking. Everything is actually connected to the DB and tested.

* Is it possible this is something to do with nest and not with typeorm?
I am investigating by fixing the version of nestjs, but when I return to v0.2.25, it works normally and it occurs again in v0.2.26, so I think nestjs is not very involved.

**Comment by kaito3desuyo** [comment]
I'm trying to create a repository for reproduction

**Comment by proutek** [comment]
I'm not sure if it will help but when I set 
**synchronize: false,**
in my orm config. This warning stops popping.

**Comment by imnotjames** [comment]
Looking through the code and thinking through it a bit -

Every single query we bind the listener to release on an error.  This is a bit weird because it means we end up binding this handler multiple times - especially if multiple queries fire off at the same time.  By default, 10 concurrent connections. That's could be why I didn't see this.

We could instead bind that listener when a new connection is made - in the `QueryRunner.connect` - and only set it up once.

**Comment by kaito3desuyo** [comment]
I was able to reproduce it. The repository is below.
https://github.com/kaito3desuyo/typeorm-test

The direct cause seems to be "multiple queries are hit within the same transaction".
In the above reproduction, the same transaction processing is performed using typeorm-transactional-cls-hooked, but it was confirmed that the same phenomenon occurs even if the following is written.

```
@Get()
async getUsers() {
  await getManager().transaction(async transactionalEntityManager => {
    const result = Promise.all(
      [...Array(100)].map(() =>
        transactionalEntityManager
          .getRepository(UserModel)
          .createQueryBuilder()
          .getMany(),
      ),
    );
  });
  return 'done';
}
```

If they weren't in the same transaction, this didn't happen whether they were executed 100 times or 1000 times.

**Comment by imnotjames** [comment]
Awesome!  I was able to use this to create a test for this.  I'll try to get that up, a fix against it, and in a PR today :)

**Comment by imnotjames** [comment]
Here's the test I wrote using your repository and example.  Thanks for the help on this!

```javascript
import {closeTestingConnections, createTestingConnections, reloadTestingDatabases} from "../../utils/test-utils";
import {Connection} from "../../../src/connection/Connection";
import {expect} from 'chai';

describe("github issues > #6699 MaxListenersExceededWarning occurs on Postgres", () => {

    let connections: Connection[];
    before(async () => connections = await createTestingConnections({
        entities: [],
        enabledDrivers: ["postgres"]
    }));
    beforeEach(() => reloadTestingDatabases(connections));
    after(() => closeTestingConnections(connections));

    it("queries in a transaction do not cause an EventEmitter memory leak", () => Promise.all(connections.map(async connection => {
        await connection.transaction(async manager => {
            const queryPromises = [...Array(10)].map(
                () => manager.query('SELECT pg_sleep(0.0001)')
            );

            const pgConnection = await manager.queryRunner!.connect();

            expect(pgConnection.listenerCount('error')).to.equal(1);

            // Wait for all of the queries to finish and drain the backlog
            await Promise.all(queryPromises);
        });
    })));

});
```

**Comment by kaito3desuyo** [comment]
Thanks for the quick fix!
