### ISSUE TITLE
index.js Unexpected token using node

### ISSUE THREAD

**Issue by klezalaise** [typeorm/typeorm#67]
Hello,

My program transpile correctly with tsc but I can't run it with node because of an issue with index.js in typeorm lib.

> node_modules/typeorm/index.js:106
> function getConnection(connectionName = "default") {
>                                       ^
> 
> SyntaxError: Unexpected token =
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:387:25)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Function.Module.runMain (module.js:447:10)
>     at startup (node.js:148:18)

And its returning the same thing using node index.js
In my package.json
"typeorm": "0.0.2-alpha.69"
"reflect-metadata": "^0.1.8"

tsconfig.json

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true,
        "moduleResolution": "node",
        "experimentalDecorators": true
    },"exclude": [
    "typings",
    "node_modules"
  ]
}
```
npm version 3.8.6
node version v5.12.0

I don't know if there is something I am missing or is that a real issue ?

**Comment by pleerock** [comment]
please install latest version of node

**Comment by klezalaise** [comment]
I upgrade to v7.0.0 but I get a new error : 

> /node_modules/typeorm/metadata/types/ColumnTypes.js:64
>         return type.name.toLowerCase();
>                    ^
> 
> TypeError: Cannot read property 'name' of undefined
>     at Function.typeToString (/home/grevin/nba_prono/node_modules/typeorm/metadata/types/ColumnTypes.js:64:20)
>     at /home/grevin/nba_prono/node_modules/typeorm/decorator/columns/PrimaryGeneratedColumn.js:13:57
>     at DecoratePropertyWithoutDescriptor (/home/grevin/nba_prono/node_modules/reflect-metadata/Reflect.js:555:13)
>     at Object.decorate (/home/grevin/nba_prono/node_modules/reflect-metadata/Reflect.js:108:20)
>     at __decorate (/home/grevin/nba_prono/models/Match.js:4:92)
>     at /home/grevin/nba_prono/models/Match.js:12:5
>     at Object.<anonymous> (/home/grevin/nba_prono/models/Match.js:31:2)
>     at Module._compile (module.js:573:32)
>     at Object.Module._extensions..js (module.js:582:10)
>     at Module.load (module.js:490:32)
>

**Comment by pleerock** [comment]
can you provide sources for other files too? did you add `import "reflect-metadata";` in your app's main file?

**Comment by klezalaise** [comment]
```
import * as http from "http";
import express = require("express");
import {teamMap} from "./models/Team";
import  "reflect-metadata";
import {createConnection} from "typeorm";
import {Match} from "./models/Match";


const hello : string = "Hello";

const app: express.Application = express();

createConnection({
    driver: {
        type: "sqlite",
        database: "nba_prono"
    },
    entities: [
        Match
    ],
    autoSchemaSync: true,
}).then(connection => {
    
    const celtics = teamMap['Celtics'];
    const warriors = teamMap['Warriors'];
    let match = new Match();
    match.away =  celtics.name;
    match.home = warriors.name;
    match.winner = warriors.name;
    match.date = new Date();

    let matchRepository = connection.getRepository (Match);
    matchRepository.persist(match);

    // here you can start to work with your entities
});


app.get("/api/v1/teams", (request: express.Request, response: express.Response) => {
    response.json(teamMap);
});

app.get("/api/v1/teams/:name",(request:express.Request, response: express.Response)=>{
    const name = request.params('name');
    response.json(teamMap[name]);
});



console.log(hello);


const server: http.Server = app.listen(3000);
```

it's the main file.

**Comment by pleerock** [comment]
You also need to set `"emitDecoratorMetadata": true` in your tsconfig.json file

**Comment by klezalaise** [comment]
That's was it. Thank you for your help :)

**Comment by pleerock** [comment]
don't forget to star the project ;)

**Comment by klezalaise** [comment]
Hundredth start is for me :)

**Comment by dgreene1** [comment]
My solution was different. I had to point to the post-transplantation files. See here:
https://github.com/typeorm/typeorm/issues/3629#issuecomment-516067546
