### ISSUE TITLE
how can I use EntityManager to complete this sql 

### ISSUE THREAD

**Issue by Erchoc** [typeorm/typeorm#6706]
> SELECT * FROM `user` WHERE `name` = 'yangxj' AND `start_time` BETWEEN 'a1' TO 'b1' OR `end_time` BETWEEN 'a2' TO 'b2';

plese help me，I think typeorm entityManager could not do this.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
