### ISSUE TITLE
Partial select returns 'undefined' when primary key is not selected.

### ISSUE THREAD

**Issue by codgician** [typeorm/typeorm#672]
I have created an entity like:
``` typescript
@Entity
export class Problem {

  @PrimaryGeneratedColumn()
  public id: number;

  @Column('varchar')
  public description: string;

}
```
And I tried to select description without selcting id:
``` typescript
const problem = await problemRepository
          .createQueryBuilder('problem')
          .select([
              'problem.description',
          ])
          .where(`id = ${id}`)
          .getOne();
```

It generates the correct SQL query, **which could be successfully executed in mysql client with expected results**:

``` sql
SELECT `problem`.`description` AS `problem_description` FROM `problem` `problem` WHERE `problem`.`id` = 1
```
But problem is still undefined afterwards.

``` typescript
typeof(problem) === 'undefined' //true
```

 However, if I select 'problem.id' at the same time everything goes right. 

I am wondering where I've done wrong. Appreciate any help.

**Comment by pleerock** [comment]
You must select primary key, there are lot of things bind on it. I'll think what we should do if user does not select primary key. If you wan't select it then better if you get raw results
