### ISSUE TITLE
Passing findOneOrFail(undefined) will not throw an error, it returns the current table's first entry.

### ISSUE THREAD

**Issue by paroczigergo** [typeorm/typeorm#6728]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[ x] `0.2.25`

**Steps to reproduce or a small repository showing the problem:**

Passing undefined value as id will not throw an error, it returns the current table's first entry.
`repository.findOneOrFail(id)`

Expectation:
It should throws an exception, and should not return db value.

**Comment by imnotjames** [comment]
This is a breaking change which is ideally gonna happen in the next minor release

**Comment by imnotjames** [comment]
Duplicate of #2990

**Comment by wanghq** [comment]
Seems this problem still exists. Can anyone confirm?

**Comment by ashrafatef** [comment]
any updates because it still exist

**Comment by JJBocanegra** [comment]
How is this still an issue in nearly 2025 is beyond my mind
