### ISSUE TITLE
Find Options combine together will ignore some of them

### ISSUE THREAD

**Issue by thinksource** [typeorm/typeorm#6732]
according to: https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#advanced-options
Together Basic options and Advanced options will ignore the Advanced options.
Like my case, I search relations and first_name like "%test%" and the result will ignore first_name conditions

[X] bug report
[X] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I and table Person in database with first_name and some relations with other tables.

I find I can do query:

```
const result = await prep.find({first_name: Like("%out%")})
```

I can also do query:

```
const result = await prep.find({relations: ['user','belong_organization']})
```

But When I query:

```
const result = await prep.find({first_name: Like("%out%"), relations: ['user','belong_organization']})
```

I expect fist_name and relations condition together.

**Comment by imnotjames** [comment]
It needs to be `where` if you want to include `relations`.  The problem is we can't change it without severely breaking backwards compatibility.
