### ISSUE TITLE
Cannot set property 'exports' of undefined

### ISSUE THREAD

**Issue by rishabbhattacharyya** [typeorm/typeorm#6733]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[X] `0.2.25` (or put your version here)

typeorm running with the latest sql.js driver gives error in the SqljsDriver file.

TypeError: Cannot set property 'exports' of undefined
    at index.js:106
    at new Promise (<anonymous>)
    at n.r [as sqlite] (index.js:106)
    at n.<anonymous> (SqljsDriver.js:273)
    at tslib.es6.js:99
    at Object.next (tslib.es6.js:80)
    at tslib.es6.js:73
    at new Promise (<anonymous>)
    at Object.o (tslib.es6.js:69)
    at n.createDatabaseConnectionWithImport (SqljsDriver.js:263)

**Comment by imnotjames** [comment]
Do you have a repository or sample where this can be reproduced?

**Comment by imnotjames** [comment]
Pretty sure this is an issue with sql.js - I cannot replicate it locally and without a means of replicating we can't confirm it's actually a problem with TypeORM or not.

To note - here's the issue in the sql.js repo that relates to this https://github.com/sql-js/sql.js/issues/406
