### ISSUE TITLE
DataTypeNotSupportedError: Data type "timestamptz" in "Item.createDateTime" is not supported by "mysql" database

### ISSUE THREAD

**Issue by NextZeus** [typeorm/typeorm#6736]
**Issue type:**

[x] bug report

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[] `mssql`
[x] `mysql^2.18.1` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[x] `0.2.26` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

# Code

```
# app.module.ts

TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        type: 'mysql',
        host: configService.get<string>('TYPEORM_DATABASE_HOST'),
        port: +configService.get<number>('TYPEORM_DATABASE_PORT'),
        username: configService.get<string>('TYPEORM_DATABASE_USERNAME'),
        password: configService.get<string>('TYPEORM_DATABASE_PASSWORD'),
        database: configService.get<string>('TYPEORM_DATABASE_NAME'),
        entities: [__dirname + '/**/*.entity{.ts,.js}'],
        synchronize: true,
      }),
      inject: [ConfigService],
}),

# .env.development
TYPEORM_DATABASE_HOST=localhost
TYPEORM_DATABASE_PORT=3306
TYPEORM_DATABASE_USERNAME=root
TYPEORM_DATABASE_PASSWORD=123456
TYPEORM_DATABASE_NAME=demodb


# user.entity.ts
import { Entity, PrimaryGeneratedColumn, Column, PrimaryColumn } from "typeorm";

@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstname: string;

    @Column()
    lastname: string;

    @Column()
    username: string;

    @Column()
    password: string;

    @Column({ default: true })
    isActive: boolean;
}

# user.module.ts
@Module({
    imports: [TypeOrmModule.forFeature([User])],
    exports: [TypeOrmModule],
})

```

I searched 'timestamptz', it occured in postgres driver, 
[ColumnTypes.ts](https://github.com/typeorm/typeorm/blob/43a7386719280a11cfd0495748189799bc51b7d6/src/driver/types/ColumnTypes.ts)

i cannot understand why the problem came out when i used mysql driver. 
when i changed to postgres driver type, everything is fine.

ps:

i tried use 

```
TypeOrmModule.forRoot({
      type: 'mysql',
      host: 'localhost',
      port: 3306,
      username: 'root',
      password: '123456',
      database: 'nestjsdb',
      autoLoadEntities: true,
      synchronize: true,
    }),
```
this works.

[code here](https://github.com/NextZeus/hellonestjs)

**Comment by imnotjames** [comment]
This looks more related to nestjs and the modules there than typeorm.  If you can replicate this with just typeorm please open a new issue with more information.


For general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
