### ISSUE TITLE
0.2.26 brakes browser builds (by node-only PlatformTools refactoring commit)

### ISSUE THREAD

**Issue by chriswep** [typeorm/typeorm#6739]
**Issue type:**
[x] bug report

**Database system/driver:**
all / browser-builds

**TypeORM version:**
[x] `0.2.26`

**Steps to reproduce or a small repository showing the problem:**
Building a project with TypeORM 0.2.26 with webpack for a browser target leads to multiple errors, the following is just just an excerpt (with duplicates removed):
```
WARNING in ../node_modules/typeorm/browser/connection/ConnectionOptionsReader.js 114:45-64
Critical dependency: the request of a dependency is an expression

WARNING in ../node_modules/typeorm/browser/util/DirectoryExportedClassesLoader.js 38:38-78
Critical dependency: the request of a dependency is an expression

Module not found: Error: Can't resolve 'path'

Module not found: Error: Can't resolve 'stream'

Module not found: Error: Can't resolve 'fs'

Module not found: Error: Can't resolve 'timers'
```

I could track this down to this commit:
https://github.com/typeorm/typeorm/commit/490ad0d424e674de5be38b0c3bc83b9a14a383a5

I reverted this commit locally and could then successfully use 0.2.26 with this modification in a browser Webpack build. 

I guess that https://github.com/typeorm/typeorm/pull/6630 didn't take browser builds into account for its refactoring. On a quick look those errors (and the code changes in the pull request) do look like node-only stuff.

I suggest reverting the commit/PR @pleerock.

**Comment by pleerock** [comment]
adding @imnotjames

**Comment by imnotjames** [comment]
Removing that commit also causes issues with some webpack issues - this was intended to improve that case because most of those modules were being pulled in via a mechanism that did not allow for static analysis.  Tree shaking would drop them, and couldn't tell that we needed them in others.

Weren't we able to build a browser build for that release, though?  I think we don't use webpack - we use grunt and a variety of other tools.

@chriswep  do you have a webpack config that I can use which exhibits this error?

**Comment by chriswep** [comment]
@imnotjames i'm using angular which generates a config via its devkit. i guess this is where it pulls the configs from: https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_angular/src/webpack/configs

i would expect the issue to show up if you create a simple angular project (with typeorm imported at some place in the code) and `ng build` it. I'm using TypeScript 4.

maybe i'm missing something here, but seeing that the compiler has a code path to `require('fs')` (using the browser entry point), it makes sense to me that it fails. 

i can see that typeorms way of handling both node and browser needs refactoring (i had a fair bit of working around issues here as well). however it looks like this needs a more thorough approach? thats why i suggested to revert the attempt until there is a working solution - unless there is an easy fix for this of course.

**Comment by pleerock** [comment]
if changes in 0.2.26 fix other issues, and that's the only way to fix them, we don't have to revert them. Most people use webpack as it is, but Angular uses it the ugly way. Probably we should find a fix on typeorm+angular - why there is an issue and how to resolve it.

**Comment by chriswep** [comment]
@pleerock i get your point, however i'm not sure i agree that breaking existing projects in a patch release is the best path to a solution. 

At this point i'm also not sure if this is really related to Angular but rather to browser targets in general. @imnotjames did you successfully use this for a webpack build with a browser target? It pulls in several node-only dependencies, so i would expect this to only build and run successfully for node targets.

**Comment by chriswep** [comment]
ok, i just made a quick test via https://github.com/juristr/webpack-typescript-starter, imported typeorm in `main.ts` and did `npm run build`. It shows (most of) the same errors. So it seems to be unrelated to both Angular and my project setup but rather affect browser targets in general @pleerock @imnotjames ?

**Comment by imnotjames** [comment]
I can replicate as well.  I think the issue was hidden by the platform tools change - the dummy drivers that get injected for browser aren't being for sqlite3 and bettersqlite3.

I sure hope there's a case where we can eventually split up the project some so the drivers can be installed separately  - negating the need for hacks.

**Comment by imnotjames** [comment]
@chriswep I have a few changes in #6743 - not sure if this helps or not but per testing it seemed to get things working a lot better with the starter you included!

**Comment by chriswep** [comment]
Thanks @imnotjames, that looks helpful. However I am using SQLite in a browser context in a Hybrid App (via Cordova/capacitor, most electron apps would be affected as well I guess). Can a similar more finegrained approach be used that doesn't exclude the whole driver?

**Comment by pleerock** [comment]
Thanks @imnotjames @chriswep . I'll release a new version in a few days.

**Comment by imnotjames** [comment]
SQLite is explicitly the wrapper of the node sqlite extension.  This extension is not available in the browser context.

**Comment by chriswep** [comment]
@imnotjames some of the issues still remain:
```
WARNING in /Volumes/Users/chris/code/forks/typeorm/build/package/browser/connection/ConnectionOptionsReader.js 113:45-64
Critical dependency: the request of a dependency is an expression

WARNING in /Volumes/Users/chris/code/forks/typeorm/build/package/browser/connection/ConnectionOptionsReader.js 119:45-64
Critical dependency: the request of a dependency is an expression

WARNING in /Volumes/Users/chris/code/forks/typeorm/build/package/browser/connection/ConnectionOptionsReader.js 125:44-63
Critical dependency: the request of a dependency is an expression

WARNING in ../node_modules/typeorm/node_modules/sax/lib/sax.js
Module not found: Error: Can't resolve 'stream' in '/Volumes/Users/chris/code/emmaus/emmono/node_modules/typeorm/node_modules/sax/lib'
```

And the following errors:
```
ERROR in ../node_modules/typeorm/node_modules/app-root-path/browser-shim.js
Module not found: Error: Can't resolve 'path' in '/Volumes/Users/chris/code/emmaus/emmono/node_modules/typeorm/node_modules/app-root-path'

ERROR in ../node_modules/typeorm/node_modules/xml2js/lib/parser.js
Module not found: Error: Can't resolve 'timers' in '/Volumes/Users/chris/code/emmaus/emmono/node_modules/typeorm/node_modules/xml2js/lib'
```

Those still hint to node-stuff being loaded. All those messages are related to the PlatformTools refactoring.

**Comment by imnotjames** [comment]
That's odd - I wasn't seeing any of those in my testing using the repository you'd sent me.

Is there any way we can automate this kind of check?  Again, a minimal replication would help us build tests to automatically validate that no changes break this.  At the moment, that doesn't seem to reliably exist.  ):

**Comment by imnotjames** [comment]
@pleerock to solve this I see two easy approaches

1: Isolate ANYTHING that can be a problem for browsers under `PlatformTools`. Uglier code for the case of non-browser but clearer as to the browser cases
2: Use the `package.json` `browser` option to replace the files that are offending to the browser build with dummy versions - similarily to the drivers.  Clearer for non-browser but less clear as to the case with browser.

I'd prefer option 2 as it's clearer what files are doing things that the browser doesn't like - good to know for the eventual split of a browser package :)

Thoughts?

**Comment by chriswep** [comment]
i also see the warnings in the testing repository. i created simple connection via `createConnection({ type: "sqlite", name: "memory", database: ":memory:" });` in `main.ts` - so maybe you have to do something like that so that something significant gets actually bundled by webpack.

i managed to make it build by telling webpack to include a polyfill for node-path. however my build now a few hundred kB bigger, including full versions of xmlbuilder, js-yaml, sax, esprima ... i think this is related to the webpack warning `Critical dependency: the request of a dependency is an expression` - it looks like it has to pull in everything if a dep is required in an expression like that. It makes sense to me that this should be avoided (see https://github.com/webpack/webpack/issues/196#issuecomment-71917456).

Concerning the option: I actually started the approach with the browser entry in `package.json`. Its a hack though. And it breaks every second typeorm release (hello again). i would think that fixing/refactoring the dependency-as-expression thing would solve the immediate issue here wouldn't it? `ConnectionOptionsReader` can't really be replace by a dummy i suppose, `ConnectionOptionsXmlReader` might be but this could also be used in a browser build.

I think the proper way forward would be to separate core and drivers / plugins. A new driver shouldn't have to update (or even affect) various core files.

**Comment by imnotjames** [comment]
The XML reader should not work at all in a browser build.  It uses the platform tools read function that's been stubbed to throw an exception.

That's true on the connections option reader in some cases - we'd have to have the browser stub drop the calls to files instead.

And the thing is - that's why I'm trying to reliably  replicate this - if we can we can create a test for it and prevent the issue on every release.

**Comment by imnotjames** [comment]
> I think the proper way forward would be to separate core and drivers / plugins. A new driver shouldn't have to update (or even affect) various core files.

Agreed, but we are a long ways off.

I wonder if we could use webpack to create a bundle for browsers (instead of gulp) that omits the unintended modules, aliases things, etc - and which we could use to detect cases like this?

**Comment by imnotjames** [comment]
> i also see the warnings in the testing repository. i created simple connection via createConnection({ type: "sqlite", name: "memory", database: ":memory:" }); in main.ts - so maybe you have to do something like that so that something significant gets actually bundled by webpack.

I saw the warnings but not the errors - didn't realize the warnings were a problem, just the errors.

**Comment by imnotjames** [comment]
> ConnectionOptionsReader can't really be replace by a dummy

Why can't it be replaced by a dummy?  It does not work in the context of a browser.  It does effectively nothing.

**Comment by imnotjames** [comment]
Does https://github.com/typeorm/typeorm/pull/6763 help the issue you're seeing?

**Comment by chriswep** [comment]
thanks @imnotjames - https://github.com/typeorm/typeorm/pull/6763 seems to do it. no more warnings/errors.

**Comment by husseinm** [comment]
I am still having an issue on the latest 0.2.27 just released.

I made sure to:

**Comment by imnotjames** [comment]
Sounds like metro isn't recognizing the browser file replacements?

Can you open this as a new issue?  This issue was specifically for webpack - metro works differently, doesn't it?

**Comment by chriswep** [comment]
> Sounds like metro isn't recognizing the browser file replacements?

It's either that and/or the fact that the react-native driver uses Platform-Tools to load the driver dependency. E.g. the expo driver does this by passing the dependency on connection. 

However if metro would use the browser entry points from `package.json` it would load `BrowserPlatformTools` which should also throw an error on `.load`, but a different one. So the react-native driver needs to be refactored in any case i assume.

**Comment by imnotjames** [comment]
Sure - but the fact it's calling the non-browser version means it's loading the wrong set of modules anyway.

For the very specific issue - See #6814  

Please open a new issue if the issues with metro persist.  There's a number of other places we use `PlatformTools` that should be replaced.

**Comment by husseinm** [comment]
Thanks, @imnotjames - I have gone ahead and filed a report #6839
