### ISSUE TITLE
beforeInsert not being triggered

### ISSUE THREAD

**Issue by mogusbi** [typeorm/typeorm#674]
Pretty much what the title says, a method in a model decorated with `@beforeInsert` isn't being triggered, causing a not-null constraint error to get triggered (that not null field should be getting populated by that beforeInsert method).

A repo with this issue can be found here: https://github.com/mogusbi/typedi-error

```typescript
// user.model.ts

import {BeforeInsert, Column, Entity} from 'typeorm';
import {encryptionService} from '../../services/encryption';
import {BaseEntity} from '../base-entity';

@Entity()
export class User extends BaseEntity {
  @Column() public answer: string;
  @Column() public dob: Date;
  @Column({
    unique: true
  }) public emailAddress: string;
  @Column() public firstName: string;
  @Column() public password: string;
  @Column() public salt: string;
  @Column() public surname: string;
  @Column({
    unique: true
  }) public username: string;

  @BeforeInsert()
  public encrypt (): Promise<string> {
    return this.generateSalt()
      .then(
        () => this.hashAnswer()
      )
      .then(
        () => this.hashPassword()
      );
  }

  public generateSalt (): Promise<string> {
    return encryptionService
      .genSalt()
      .then(
        (salt: string) => this.salt = salt
      )
  }

  public hashAnswer (): Promise<string> {
    return encryptionService
      .hash(this.answer, this.salt)
      .then(
        (hash: string) => this.answer = hash
      );
  }

  public hashPassword (): Promise<string> {
    return encryptionService
      .hash(this.password, this.salt)
      .then(
        (hash: string) => this.password = hash
      );
  }
}
```

```typescript
// user.controller.ts

import {Body, HttpCode, JsonController, Post} from 'routing-controllers';
import {IUser, User, UserService} from '../../entities/user';

@JsonController('/user')
export class UserController {
  constructor (
    private userService: UserService
  ) {}

  @Post()
  @HttpCode(201)
  public httpPost (
    @Body({
      required: true
    }) props: IUser
  ): Promise<User> {
    return this.userService.create(props);
  }
}
```

and an example POST request

```json
{
	"answer": "Test",
	"dob": "1990-07-10T00:00:00+00:00",
	"emailAddress": "email@example.com",
	"firstName": "Mo",
	"password": "SuperSecurePassword",
	"surname": "Gusbi",
	"username": "mo.gusbi"
}
```

error being returned:

```json
{
  "name": "error",
  "message": "null value in column \"salt\" violates not-null constraint",
  "stack": "error: null value in column \"salt\" violates not-null constraint\n    at Connection.parseE (/Users/mo/Repos/typedi-error/node_modules/pg/lib/connection.js:567:11)\n    at Connection.parseMessage (/Users/mo/Repos/typedi-error/node_modules/pg/lib/connection.js:391:17)\n    at Socket.<anonymous> (/Users/mo/Repos/typedi-error/node_modules/pg/lib/connection.js:129:22)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:548:20)",
  "length": 334,
  "severity": "ERROR",
  "code": "23502",
  "detail": "Failing row contains (47a52ba1-369e-4733-94c0-74c624a5c839, 2017-07-16 19:50:20.3, 2017-07-16 19:50:20.3, 1, Test, 1991-01-25 00:00:00, me@mogusbi.co.uk, Mo, Password1!, null, Gusbi, mo.gusbi).",
  "schema": "public",
  "table": "user",
  "column": "salt",
  "file": "execMain.c",
  "line": "1732",
  "routine": "ExecConstraints"
}
```

**Comment by lednhatkhanh** [comment]
This is a big error, I can't hash my password using the subscribers, please fix it asap

**Comment by mrkmg** [comment]
Also getting this issue. Using the newest 0.1.0 release.

**Comment by mmiszy** [comment]
@mogusbi  I think this is definitely a bug, but there's a simple workaround. The problem is that you're calling `persist` on an object literal like you do here in [src/entities/user/user.service.ts#L14](https://github.com/mogusbi/typedi-error/blob/master/src/entities/user/user.service.ts#L14)

```
return this.repository.persist(props);
```

Instead, create a model instance first and save it:
```
const instance = this.repository.create(props);
return this.repository.persist(instance);
```

**Comment by pleerock** [comment]
Of course it will not work on object literals, because it calls entity method on entity you pass to it. If your entity is not instance of particular class with method (thus does not have this method) then how not exist method can be called?

Guys if someone face this issue please create a new issue with concrete reproduction of the problem, because I cannot reproduce this error anyhow.

**Comment by FreakTheMighty** [comment]
@pleerock for what its worth, for me the confusion arises from the fact that TypeScript annotations make it appear that you're working with an instance. In the example above `props: IUser`, props appears to be of type `IUser`, but instead you have to create a new object and reapply the props.

**Comment by rationalthinker1** [comment]
You have to instantiate the Entity and assign the attributes to it and then save.
```
async create(attributes: object) {
        let entity: object = new this.entity();
        entity = Object.assign(entity, attributes);

        return this.repository.save(entity);
    }
```

**Comment by Kaminto** [comment]
> You have to instantiate the Entity and assign the attributes to it and then save.
> 
> ```ts
> async create(attributes: DeepPartial<T>) {
>     const entity = Object.assign(new User(), attributes);
>     return this.repository.save(entity);
> }
> ```

this works just fine

**Comment by krychuq1** [comment]
You can also use class-transformer
```
async create(attributes: DeepPartial<T>) {
    const entity = plainToClass(User, attributes);
    return this.repository.save(entity);
}
```

**Comment by goonerify** [comment]
Be careful when assigning an entity object this way because it could break your validations.

You may have to add some hooks to your entity to ensure validation of the datatypes takes place if you have some validations. You could use the `validateOrReject` method from `class-validator` to do that

```  
  @BeforeInsert()
  @BeforeUpdate()
  async validate() {
    await validateOrReject(this);
  }
```

**Comment by vsharan** [comment]
> You have to instantiate the Entity and assign the attributes to it and then save.
> 
> ```ts
> async create(attributes: DeepPartial<T>) {
>     const entity = Object.assign(new User(), attributes);
>     return this.repository.save(entity);
> }
> ```

This was a life saver for me. Thanks @rationalthinker1

**Comment by vikrambhatla** [comment]
> You have to instantiate the Entity and assign the attributes to it and then save.
> 
> ```ts
> async create(attributes: DeepPartial<T>) {
>     const entity = Object.assign(new User(), attributes);
>     return this.repository.save(entity);
> }
> ```

works for me as well saved my day :)

**Comment by sai-gmbh** [comment]
`typeorm` provides this.repository.create() does the same thing as Object.assign(new User(), attributes);

**Comment by dcsm8** [comment]
> typeorm provides this.repository.create() method which does the same thing as Object.assign(new User(), attributes);

You're right, that worked for me.

``` javascript
const attributes = {
   username,
   email,
   password
};

const entity = repository.create(attributes);
await repository.save(entity);
```
