### ISSUE TITLE
No dateStrings option for SQLite Db

### ISSUE THREAD

**Issue by yarostbaklajana** [typeorm/typeorm#6740]
**Issue type:**

Property dateStrings is not recognizable in the SqliteConnectionOptions.d.ts typing;

Version of typeORM is  "^0.2.26";

Can this property be added to SQL connection options?

[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
You can pass this in `extra`
