### ISSUE TITLE
TypeORM Attempts to create tables that already exist

### ISSUE THREAD

**Issue by derSoerrn95** [typeorm/typeorm#6744]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When you are using the `schema`-field in the `@Entity` annotation and enable synchronize TypeORM trys to create existing entities.

For example given following Entity:

```ts
@Entity({schema: 'TEST', name: 'TEST_ENTITY', synchronize: true})
export class TestEntity {

  @PrimaryColumn({name: 'ID', type: 'number'})
  id: number;

  @Column({name: 'QUANTITY'})
  quantity: number;
}
```

When TypeORM checks for existing tables it uses following query:

```sql
SELECT "C"."CONSTRAINT_NAME",
       "C"."CONSTRAINT_TYPE",
       "C"."TABLE_NAME",
       "COL"."COLUMN_NAME",
       "C"."SEARCH_CONDITION"
FROM "USER_CONSTRAINTS" "C"
         INNER JOIN "USER_CONS_COLUMNS" "COL" ON "COL"."OWNER" = "C"."OWNER"
    AND "COL"."CONSTRAINT_NAME" = "C"."CONSTRAINT_NAME"
WHERE "C"."TABLE_NAME"
    IN ('TEST.TEST_ENTITY')
  AND "C"."CONSTRAINT_TYPE" IN ('C', 'U', 'P')
  AND "C"."GENERATED" = 'USER NAME'
```

As you can see it is looking for 'TEST.TEST_ENTITY' although the TABLE_NAME column only contain 'TEST_ENTITY' so TEST_ENTITY won't be selected.

**Comment by biels** [comment]
The same happens with PostgreSQL. It tries to recreate tables and it even complains when applying {nullable: false} "column "columnName" contains null values" when there isn't a single null value in the table.

**Comment by imnotjames** [comment]
Is there another field where the schema is defined in that table?

**Comment by imnotjames** [comment]
This should be fixed in the next release.  This can be confirmed in the latest dev build - `0.2.38-dev.22676a0`
