### ISSUE TITLE
Querying an existing controller

### ISSUE THREAD

**Issue by alex5207** [typeorm/typeorm#6750]
**Issue type:**

[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `6.14.4`

**Steps to reproduce or a small repository showing the problem:**

Problem: I am creating a new controller and I want to re-use the logic of an existing one. How can I do this without re-writing the logic in the new controller as well? Example of existing controller is given below.

Note: I want to use the output of this in a join with another query.

*Existing controller:*
```import { Get, Controller, Query } from '@nestjs/common';
import { getRepository } from "typeorm";
import { Transaction } from '../Transaction/transaction.entity';
import { Deposit } from '../Deposit/deposit.entity';
import { Person} from '../Students/student.entity';


@Controller('balances')
export class BalanceController {

  @Get()
  public async findAll(@Query() query): Promise<Object> {
      const deposit = await getRepository(Deposit)
      .createQueryBuilder('deposit')
      .select('deposit.owner "owner", SUM(deposit.value) "totalDeposits"')
      .groupBy('deposit.owner')
      .getSql()

      const transaction = await getRepository(Transaction)
      .createQueryBuilder('transaction')
      .select('transaction.owner "owner", SUM(transaction.value) "totalTransaction"')
      .groupBy('transaction.owner')
      .getSql()

      // Use two above sql statements to create a final query
      const balance = await getRepository(Person)
        .createQueryBuilder('person')
        .leftJoin('(' + deposit + ')', 'deposit', 'person.id=deposit.owner')
        .leftJoin('(' + transaction+ ')', 'transaction', 'person.id=transaction.owner')
        .select('person.id, person.firstName, person.lastName, IFNULL(deposit.totalDeposits, 0) - 
             IFNULL(transaction.totalTransactions, 0) "balance"')
        .getRawMany()

      return balance;
  }
}`
```
Can I use TypeOrm query features to leverage this controller in a totally different query?

**Comment by germangamboa95** [comment]
This has nothing to do with TypeORM. 
If you want to extract logic using repositories make a custom repo with the queries you want to call as methods and then it can be used across your codebase 
https://typeorm.io/#/custom-repository

**Comment by imnotjames** [comment]
I'd agree - I think this has more to do with the application you're writing than TypeORM - if you have a more concrete feature request, though, we can discuss it and reopen the issue!
