### ISSUE TITLE
Junction tables not generated for ManyToMany relation.

### ISSUE THREAD

**Issue by crystalbyte** [typeorm/typeorm#676]
Hi there,

I have a rather simple many to many relationship in my project, some properties have been removed for brevity:

```
@Entity()
export class Item {

    @PrimaryGeneratedColumn()
    public id: number;
    
    @JoinColumn()
    @ManyToMany(type => Location, location => location.items)
    public locations: Location[];
}
```
and
```
@Entity()
export class Location {

    @PrimaryGeneratedColumn()
    public id: number;

    @Column({ length: 128 })
    public name: string;
    
    @JoinColumn()
    @ManyToMany(type => Item, item => item.locations, { 
        cascadeInsert: true,
        cascadeUpdate: true
    })
    public items: Item[];
}
```
Unfortunately no junction table is being generated, it seems the properties in question are simply being ignored as the SQL debug output shows.

```
executing query: START TRANSACTION
executing query: CREATE TABLE `location` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(128) NOT NULL, `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)) ENGINE=InnoDB
executing query: CREATE TABLE `item` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(128) NOT NULL, `description` varchar(512) NOT NULL, `price` int(11) NOT NULL, `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)) ENGINE=InnoDB
executing query: CREATE TABLE `tag` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(255) NOT NULL, `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)) ENGINE=InnoDB
executing query: COMMIT
```

Platform: Windows 10
Database: MariaDB
Version: typeorm@0.1.0-alpha.31

**Comment by pleerock** [comment]
for many-to-many you should use `@JoinTable` instead of `@JoinColumn` - and only on one side (owner side), e.g.:

```ts
@Entity()
export class Location {

    @PrimaryGeneratedColumn()
    public id: number;

    @Column({ length: 128 })
    public name: string;
    
    @ManyToMany(type => Item, item => item.locations, { 
        cascadeInsert: true,
        cascadeUpdate: true
    })
    @JoinTable()
    public items: Item[];
}
```

**Comment by crystalbyte** [comment]
Thanks for pointing me to the right direction, the junction table is now being generated.

**Comment by raghav196** [comment]
@pleerock 

I'm also facing this issue of junction table not getting generated for ManyToMay relation. And I'm using `@JoinTable()` decorator.

`import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, ManyToMany, JoinTable } from 'typeorm';
import { Role } from '../role/role.entity';

@Entity('users')
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'uuid' })
  remoteId: string;

  @Column({ type: 'varchar', length: 255, nullable: false })
  name: string;

  @Column({ type: 'varchar', length: 3, nullable: false })
  countryCode: string;

  @Column({ type: 'varchar', length: 15, nullable: false })
  phone: string;

  @Column({ type: 'varchar', length: 255, nullable: false })
  email: string;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date;

  @ManyToMany(type => Role, role => role.users, {
    eager: true,
    nullable: false
  })
  @JoinTable()
  roles: Role[]
}`

and 

`import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, ManyToMany, JoinTable } from 'typeorm';
import { User } from '../user/user.entity';

@Entity('roles')
export class Role {
  @PrimaryGeneratedColumn({ type: 'integer' })
  id: number;

  @Column({ type: 'integer' })
  remoteId: number;

  @Column({ type: 'varchar' })
  role: string;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date;

  @ManyToMany(type => User, user => user.roles)
  users: User[]

}
`
I'm using **postgres** on MacOSX.

I'm unable to figure out what can be the issue.
