### ISSUE TITLE
Entities needed for Stored Procedures

### ISSUE THREAD

**Issue by danrald** [typeorm/typeorm#6762]
I don't know if this is an issue as much as it is a question. 
I have a query that I'm running:

await getConnection().query("select * from somefunction($1)",[someparameter ])

and I want the result set to get incorperated into a typeorm entity.
Is there a way to do this?

Thanks,
Dan

**Comment by imnotjames** [comment]
Perhaps a [ViewEntity](https://github.com/typeorm/typeorm/blob/master/docs/view-entities.md)?

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
