### ISSUE TITLE
query or Query builder with getRawMany returns json column results wrapped with extra quotes (not parsed)

### ISSUE THREAD

**Issue by royzi-lemonade** [typeorm/typeorm#6766]
**Issue type:**

[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
When trying to execute raw query on table which includes JSON column, it seems that the results return are padded with extra quotes. For example: `repo.findOne(1)` returns:
```js
{
  data: [
    { relation: 'child', last_name: 'Bee', first_name: 'Blair' },
    { relation: 'spouse', last_name: 'Zee', first_name: 'Jane' }
  ]
}
```
while executing `repo.query('SELECT * from table_name')`
```js
RowDataPacket {
  data: '[{"relation": "child", "last_name": "Bee", "first_name": "Blair"}, {"relation": "spouse", "last_name": "Zee", "first_name": "Jane"}]',
}
```
`data` column is `json` (rest list of columns is removed for brevity)
The result of the above needs to be `JSON.parsed` while the regular `find`ers already handle it.
Is this the expected behavior? 
Thanks

**Comment by imnotjames** [comment]
`repo.query` doesn't have the context to know this is a json field.  If you want it to parse you'll need to use a query builder instead of a raw query - or you'll need to parse it yourself.

Unfortunately, at this time we don't have any mechanism to run the ORM against a raw query yet.

**Comment by imnotjames** [comment]
Try using the query builder instead.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
