### ISSUE TITLE
LeftJoinAndSelect is not working when using SubQueryFactory

### ISSUE THREAD

**Issue by AvaognTheme** [typeorm/typeorm#6767]
**Issue type:**
- [x] documentation issue
- [x] bug report

**Database system/driver:**
- [x] `mysql` / `mariadb`

**TypeORM version:**
- [x] `latest 0.2.26`

## What is the proper way to create the following query?
```sql
SELECT user.*, photos.*
FROM user
LEFT JOIN 
    (SELECT * FROM user_photos ORDER BY updatedAt LIMIT 5) AS photos
    ON user.id = photos.userId
```

## The best I have tried using `SubQueryFactory`

```ts
const result = await userRepo
      .createQueryBuilder('user')
      .leftJoinAndSelect(
        qb => qb
          .select()
          .from(UserPhotos, 'p')
          .orderBy({ 'p.updatedAt': 'ASC' })
          .limit(5),
        'photos'
      )
      .getMany()
```
This code generated this query *(SIMPLIFIED)*
```sql
SELECT user.*, photos.* 
FROM user
LEFT JOIN
    (SELECT * FROM `user_photos` `p` ORDER BY p.updatedAt ASC LIMIT 5) AS photos
    --- 🤨 where is ON clause?
```
# Where is the `ON` clause 🤨?
You can see that everything is ok until the `ON` clause. When I don't use `SubQueryFactory` everything is ok.

## Not using `SubQueryFactory` (IS NOT A SOLUTION) 
```ts
const result = await userRepo
      .createQueryBuilder('user')
      .leftJoinAndSelect('user.photos', 'photos')
      .getMany()
```
`ON` is right there
```sql
SELECT user.*, photos.* 
FROM user
LEFT JOIN `user_photos` `photos` 
    ON photos.userId = user.id --- see?
```

**Comment by vishal38-isharani** [comment]
Yes I'm facing the same issue. Only difference is i'm using postgres as database provide.

**Comment by imnotjames** [comment]
using the `SubQueryFactory` option does not automatically create the `on` clause as the condition as it cannot know what the underlying query's alias is that you're trying to join with.  It doesn't have the context afforded by the metadata of `.leftJoinAndSelect('user.photos', 'photos')` because of how it's been written.

Instead, you have to explicitly define the condition.  In your case:

```typescript
const result = await userRepo
      .createQueryBuilder('user')
      .leftJoinAndSelect(
        qb => qb
          .select()
          .from(UserPhotos, 'p')
          .orderBy({ 'p.updatedAt': 'ASC' })
          .limit(5),
        'photos',
        'photos.userId = user.id'
      )
      .getMany()
```

**Comment by vishal38-isharani** [comment]
@imnotjames this is working as intended, but when I get raw query result using getRawOne() it's giving the joined data but when I use getOne() it's returning blank data for that column.
I even tried to use leftJoinAndMapOne but it's still not working.
https://github.com/typeorm/typeorm/issues/5637#issuecomment-699087519

**Comment by imnotjames** [comment]
If you get the sql that's a separate issue which is unrelated to this one as far as I can tell.

**Comment by germanomni** [comment]
any updates ?

**Comment by nikelborm** [comment]
This issue is still actual. I was faced with the same problem.

**Comment by Besmerch123** [comment]
Look like no updates.

**Comment by auragit** [comment]
+1

**Comment by itstrung** [comment]
Any update on this please? Thank you.
