### ISSUE TITLE
typeorm inserts _ into explicit column name when name contains a number

### ISSUE THREAD

**Issue by finnigantime** [typeorm/typeorm#6769]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.26`

**Steps to reproduce or a small repository showing the problem:**

code (add to an entity):
```
  @Column({ name: 'small_logo_s3' })
  smallLogoS3URL?: string;
```

expected: When querying the entity, typeorm honors the explicit column name (`small_logo_s3`).
actual: Typeorm inserts an _ into the column name. There is no way I can actually query my column.

<img width="931" alt="Screen Shot 2020-09-23 at 2 06 33 PM" src="https://user-images.githubusercontent.com/1305608/94070046-68086300-fda6-11ea-847a-e05e014d7b7b.png">

**Comment by imnotjames** [comment]
Unfortunately, I am unable to replicate this behavior.  Do you have a repository that exhibits this which can be shared?

---

The test I created is as such

`entity/Record.ts`

```typescript
import { Entity, PrimaryColumn, Column } from "../../../../src";

@Entity()
export class Record {
    @PrimaryColumn()
    id: number;

    @Column({ name: 'test_a1'})
    testA1: string;
}
```

`issue-6769.ts`

```typescript
import {
    createTestingConnections,
    closeTestingConnections,
    reloadTestingDatabases,
} from "../../utils/test-utils";
import {Connection} from "../../../src/connection/Connection";
import {expect} from "chai";
import {Record} from './entity/Record';

describe("github issues > #6769 inserts _ into explicit column name when name contains a number", () => {
    let connections: Connection[];

    before(async () => {
        return connections = await createTestingConnections({
            entities: [Record]
        });
    });
    beforeEach(async () => await reloadTestingDatabases(connections));
    after(async () => await closeTestingConnections(connections));

    it("should not insert an underscore", () => Promise.all(connections.map(async connection => {
        const metadata = connection.getMetadata(Record);

        expect(metadata.columns[1].databaseName).to.be.equal('test_a1');
    })));
});
```

**Comment by finnigantime** [comment]
You're right, I cannot repro outside of our repository either.

I didn't realize it, but our repository is using a `CustomNamingStrategy` in the ormconfig. Sorry for the false alarm. Closing this issue.

**Comment by imnotjames** [comment]
No worries! Good luck on figuring it out.

You can always check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
