### ISSUE TITLE
Implementing nested OneToMany/ManyToOne relations

### ISSUE THREAD

**Issue by renatarussar** [typeorm/typeorm#6770]
**Issue type:**

[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello, I'm trying to implement two levels of OneToMany (and ManyToOne) relations.
I made a `Cart` that has multiple `CartItems`, that is working.

```
@Entity()
export class Cart extends BaseEntity {

  @PrimaryColumn()
  uuid: string;

  @OneToMany(
    () => CartItem,
    (cartItem: CartItem) => cartItem.cart,
    { eager: true, cascade: true }
  )
  items: CartItem[];
}

@Entity()
export class CartItem extends BaseEntity {
  @ManyToOne(
    () => Cart,
    (cart: Cart) => cart.items,
    { primary: true, onDelete: 'CASCADE' }
  )
  cart: Cart;

  @Column({ primary: true })
  sku: number;
}
```

Now I need to add multiple `KitItems` to a `CartItem`.
This is what I'm trying:
```
@Entity()
export class Cart extends BaseEntity {

  @PrimaryColumn()
  uuid: string;

  @OneToMany(
    () => CartItem,
    (cartItem: CartItem) => cartItem.cart,
    { eager: true, cascade: true }
  )
  items: CartItem[];
}

@Entity()
export class CartItem extends BaseEntity {
  @ManyToOne(
    () => Cart,
    (cart: Cart) => cart.items,
    { primary: true, onDelete: 'CASCADE' }
  )
  cart: Cart;

  @Column({ primary: true })
  sku: number;

  @OneToMany(
    () => KitItem,
    (kitItem: KitItem) => kitItem.kit,
    { eager: true, cascade: true }
  )
  kitItems: KitItem[];
}

@Entity()
export class KitItem extends BaseEntity {
  @ManyToOne(() => CartItem, { primary: true, onDelete: 'CASCADE' })
  kit: CartItem;

  @Column({ primary: true })
  sku: number;
}
```

This is the migration scripts I'm getting for the new table `KitItem`:
```
CREATE TABLE "kit_item" ("sku" integer NOT NULL, "kitSku" integer NOT NULL, CONSTRAINT "PK_48d5b6311b9baf2b0f09c282f44" PRIMARY KEY ("sku", "kitSku"))

ALTER TABLE "kit_item" ADD CONSTRAINT "FK_0784595cb302a202e72bc52b72e" FOREIGN KEY ("kitSku") REFERENCES "cart_item"("sku") ON DELETE CASCADE ON UPDATE NO ACTION`
```

However I get the error `QueryFailedError: there is no unique constraint matching given keys for referenced table "cart_item"` since it's not creating the KitItem FK associated with the correct CartItem PK.

How should I do this?
I tried adding the `@JoinColumn` on the KitItem like this
```
  @ManyToOne(() => CartItem, { primary: true, onDelete: 'CASCADE' })
  @JoinColumn([
    { referencedColumnName: 'cart' },
    { referencedColumnName: 'sku' }
  ])
  kit: CartItem;
```

but then I get the error `Error: Referenced column cart was not found in entity CartItem`
I also tried changing it to
```
  @ManyToOne(() => CartItem, { primary: true, onDelete: 'CASCADE' })
  @JoinColumn([
    { referencedColumnName: 'cartUuid' },
    { referencedColumnName: 'sku' }
  ])
  kit: CartItem;
```
but it doesn't recognize the cartUuid column either.

The only way to make the migration generation work was removing the OneToMany relation from CartItem->KitItems[] and thus making the ManyToOne KitItem->CartItem unilateral, which generated the correct FK/PK relationship:
```
ALTER TABLE "kit_item" ADD CONSTRAINT "FK_aadb6c36453081f655aeaf2e966" FOREIGN KEY ("kitSku", "kitCart") REFERENCES "cart_item"("sku","cartUuid") ON DELETE CASCADE ON UPDATE NO ACTION`)
```

However, I can't make it unilateral because I need to eager load all of the CartItems and its KitItems from a Cart entity.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
You're creating an invalid PK by setting just the many to one as PK.  I think there's some references you need to set up.

In general, this is something that requires support, not a GitHub issue.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
