### ISSUE TITLE
In operator parameter handling

### ISSUE THREAD

**Issue by tantra-anthony** [typeorm/typeorm#6771]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

With any repository, passing an empty array inside an `In` operator will result in the SQL query `IN ()`, which will throw an error. This behaviour also exists in operators that accept multiple values like `Any`.
```
repository.find({
  column: In([])
})
```

Not sure if this responsibility should be passed to the library to handle or not, but this can also be fixed just by checking whether the array passed to the operator has a non-zero length.

**Comment by imnotjames** [comment]
Some SQL dialects allow this, others don't, right?

I think the issue for implementing it to work on dialects that don't allow it is that generated query is undefined behavior - in theory it should never pass, right?  Or should it ALWAYS pass?  If it should never pass should it generate a query that we know is going to not pass?  Like false = true? Feels kinda hacky.

So maybe it should throw some sort of exception in this case? (Which it does when the execution is attempted, right?)

**Comment by tantra-anthony** [comment]
@imnotjames yes that is correct, although it threw an error, it seems that the error is thrown after, instead of during building the query itself.

This is why I asked whether the responsibility should be passed to the ORM to handle this instead or not. 

Although after you mentioned that behaviours differ across SQL dialects (I've tested this using MySQL and Postgres especially), I'm more leaning towards the current behaviour.

**Comment by imnotjames** [comment]
I think that we could throw an exception in the query builder in this case.  In the future it's likely that the query builder is where the SQL dialects will be handled (it's where they are now) - so we could prevent building the invalid SQL in that case and throw a more useful error.

**Comment by tantra-anthony** [comment]
Will do, closing this issue now since this can just be easily handled by checking whether the array passed is empty or not.
