### ISSUE TITLE
PrimaryGeneratedColumn('uuid') or Generated('uuid') not creating value

### ISSUE THREAD

**Issue by bwermes** [typeorm/typeorm#6773]
**Issue type:**
I have created an entity with the following properties: 

```import { Column, Entity, PrimaryColumn, OneToMany,ManyToOne, OneToOne, PrimaryGeneratedColumn, BaseEntity } from "typeorm";

@Entity('test')
export class test extends BaseEntity{
@PrimaryGeneratedColumn('uuid')
test: string
   
public constructor(init?: Partial<test>) {
super();
Object.assign(this, init);
}}
```

When attempting 

```
const tst: test = new test();
return await test.save(tst);
```
I would expect the entry to be created in MSSQL. However I get the following as a return: 

```query failed: DECLARE @OutputTable TABLE ("test" uniqueidentifier);
INSERT INTO "test"("test") OUTPUT INSERTED."test" INTO @OutputTable VALUES (DEFAULT);
SELECT * FROM @OutputTable
error: RequestError: Cannot insert the value NULL into column 'test', table 'mydb.dbo.test'; column does not allow nulls. INSERT fails.
```

My MSSQL "test" table is:
```
+-------------+--------------+----------------------------+
|                     test
+-------------+--------------+----------------------------+
| test |  varchar(255)              |            PRIMARY KEY         |
+-------------+--------------+----------------------------+
```

[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[X] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Create a table in MSSQL with a single column. Datatype: varchar(255).
2. Create entity in Node decorate with PrimaryGeneratedColumn('uuid')
3. Attempt to insert record.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by bwermes** [comment]
To also confirm, I have verified that the functionality works on a MySQL database and have also tested with another MSSQL database configured the same way. Same result occurs.

Are there any properties that need to be specified in the table configuration or column configuration in MSSQL that are not needed in MySQL?

Also should note, I am not having Typeorm generate my scheme, nor am I using `synchronize`

**Comment by coyoteecd** [comment]
@bwermes Your MSSQL test table contains a varchar column. Read up on how to define a GUID PK in MSSQL and configure it accordingly. For MSSQL, TypeORM relies on the database server to generate the value, and your table does not do that. Start here: https://docs.microsoft.com/en-us/sql/t-sql/data-types/uniqueidentifier-transact-sql

Do not confuse with MySQL, which does **not** support UUID columns in the database. For MySQL, it is TypeORM that generates these values for you, so it appears to work with varchar columns.

@imnotjames I think you can close this, doesn't look like a bug
