### ISSUE TITLE
Hana driver can not be loaded in latest typeorm

### ISSUE THREAD

**Issue by mathiasmaerker** [typeorm/typeorm#6775]
**Issue type:**

[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `SAP HANA`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I just updated typeorm to `0.2.26` and all of a sudden the Hana Dirver can't load anymore error message ist `Failed to connect to Database, reason: SAP Hana package has not been found installed. Try to install it: npm install hdb-pool --save` 

`hdb-pool`is installed and `0.2.25`works like a charm

**Comment by imnotjames** [comment]
I believe this will be fixed in the next release for TypeORM - https://github.com/typeorm/typeorm/pull/6700

**Comment by imnotjames** [comment]
This should be fixed in 0.2.27 - has it been?

**Comment by mathiasmaerker** [comment]
Just checked, it working again, thanks a lot!
