### ISSUE TITLE
@BeforeInsert / @BeforeUpdate function blocks all database calls when the connectionpool was temporarily full

### ISSUE THREAD

**Issue by yorickdevries** [typeorm/typeorm#6779]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In my production environment there is sometimes more load and queries are being queued to be processed later (as expected). However, I observed that once the connections of the connection pool become available again, the queries in the queue are not run anymore and the connections stay asleep. the only remedy in that case is rebooting the server, which causes everything to work again.

I discovered that the `@BeforeInsert` / `@BeforeUpdate` function I use for validating my database entries trigger this behavior. In that function I perform some asynchronous database queries as well to ensure validity, similar to https://github.com/typeorm/typeorm/issues/913 ). Perhaps when this check takes too long the system blocks? Removing the `@BeforeInsert` / `@BeforeUpdate` decorators cause the block not to happen.

As this bug only occurs at heavy load, I made a mockup repository which triggers this bug, so one could reproduce this behavior. you can find it at: https://github.com/yorickdevries/typeorm-before-bug . The code in this repo keeps on creating/updating users until a queue of a certain length arises and then stops creation/updating. I observe that after stopping creating/updating users the connections finish their queries and go to sleep mode. The queue remains full and no new queries are processed at all anymore, and the mysql driver also indicates that there are no free connections available.

The behavior is similar to https://github.com/mysqljs/mysql/issues/1771 , but I could not reproduce it without the TypeORM `@BeforeInsert` / `@BeforeUpdate` decorators.

See also the screenshot below:
![image](https://user-images.githubusercontent.com/23526707/94166589-c8250500-fe8b-11ea-88c1-dfbd97ecdcc9.png)
This is what you can reproduce with the code in the repository.

The `userEntity` I made for this repo is shown here as well:

```ts
import {
  Entity,
  Column,
  BaseEntity,
  BeforeInsert,
  BeforeUpdate,
  PrimaryGeneratedColumn,
  getConnection,
} from "typeorm";

@Entity()
export default class UserEntity extends BaseEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  firstName: string;
  @Column()
  lastName: string;

  constructor(firstName: string, lastName: string) {
    super();
    this.firstName = firstName;
    this.lastName = lastName;
  }

  @BeforeInsert()
  @BeforeUpdate()
  async beforeFunction(): Promise<void> {
    await UserEntity.findOne();
    console.log("Running before Insert/update");
    return;
  }

  static async getRandomUser(): Promise<UserEntity | undefined> {
    const connection = getConnection();
    const randomUser = connection
      .createQueryBuilder(this, "user")
      .orderBy("RAND()")
      .limit(1)
      .getOne();
    return randomUser;
  }
}
```

**Comment by KCFindstr** [comment]
Any update on this? I'm encountering the same issue which makes the before/after hooks almost unusable.

**Comment by pleerock** [comment]
See explanation here #8497
