### ISSUE TITLE
Are yargonaut and figlet required at run-time?

### ISSUE THREAD

**Issue by neuoy** [typeorm/typeorm#678]
I believe you could move the yargonaut dependency to devDependencies, which will avoid bringing the  3Mo figlet package to production servers.

**Comment by pleerock** [comment]
No, we cannot because CLI uses it. But you need CLI on production as well.

**Comment by neuoy** [comment]
Oh, ok, you know better than I, I'm only starting to use it. Thanks for the quick answer.

**Comment by Kononnable** [comment]
We plan to split typeorm to smaller packages. It would help with that issue since cli and it dependencies won't be needed in lambda environment.
However since it's not a trivial task we don't really have a clear timeline when it will be implemented.

Related issue: #2479
