### ISSUE TITLE
typeorm cli migrate:run port issue getting "config.options.port" property must be of  type number.

### ISSUE THREAD

**Issue by GLakshmiSravanthi** [typeorm/typeorm#6781]
**Issue type:**

[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

While running the `yarn ts-node  ./node_modules/typeorm/cli.js migration:run` facing error 
We are using .env file, which has the typeORM configuration. 

![error](https://user-images.githubusercontent.com/67416683/94231110-fb65a380-ff20-11ea-9539-ac0302f90fe8.PNG)

Configarations we placed
```

TYPEORM_CONNECTION=mssql
TYPEORM_HOST=localhost
TYPEORM_PORT=1443
TYPEORM_USERNAME=XXXX
TYPEORM_PASSWORD=XXXX
TYPEORM_DATABASE=test
TYPEORM_SYNCHRONIZE=false
TYPEORM_LOGGING=error
TYPEORM_LOGGER=advanced-console

```

this our script file from here we are running db.migrate
![image](https://user-images.githubusercontent.com/67416683/94239596-ac733a80-ff2f-11ea-9b70-4647326df516.png)

Solutions we tried

[ * ] This is our folder structure placed `.env` file and `ormconfig.json` are in same folder but when we are running migrations command it is taking .env file not ormconfig.json 
![image](https://user-images.githubusercontent.com/67416683/94238037-5d2c0a80-ff2d-11ea-8e46-d41972730bb9.png)

[ * ] We tried to giving `yarn ts-node  ./node_modules/typeorm/cli.js migration:run -f ormconfig.json` but we are unable to compile
![image](https://user-images.githubusercontent.com/67416683/94238495-1ab6fd80-ff2e-11ea-8790-a1852f7137eb.png)

[ * ] But by renaming the .env file we are able to compile the command `yarn ts-node  ./node_modules/typeorm/cli.js migration:run -f ormconfig.json` 
![image](https://user-images.githubusercontent.com/67416683/94238869-944eeb80-ff2e-11ea-901f-aae474270a7e.png)

[ * ] We tried pass our .env file as configuration, it results the same error 
![image](https://user-images.githubusercontent.com/67416683/94239117-f1e33800-ff2e-11ea-9688-dbc5fca44ff0.png)

[ * ] Checked in the typeorm git repo in that `ConnectionOptionsEnvReader()` is reading the env variables and in that port is read from `port: PlatformTools.getEnvVariable("TYPEORM_PORT"),` .  `getEnvVariables is returning a string`. 
Which may be causing the issue ? 
Please help

Thankyou For advance

**Comment by imnotjames** [comment]
Yeah - looks like that's the case - it doesn't coerce the port to a number when pulling from env to a string.

Pull requests welcome :) But we'd need to double check that none of the drivers actually EXPECT a string port.

**Comment by imnotjames** [comment]
As a temporary workaround, are you able to omit the port environment variable? Or stick with the `ormconfig.json`? The default should be 1443

**Comment by GLakshmiSravanthi** [comment]
thankyou we resolved the problem
