### ISSUE TITLE
website is requesting a file that doesnt exsist

### ISSUE THREAD

**Issue by abdoreact** [typeorm/typeorm#6783]
so i tried going to the docs but i received a blank page, i checked the console and noticed this error GET https://unpkg.com/vue-i18n@9.0.0-beta.3/dist/vue-i18n.js net::ERR_ABORTED 404
your requesting the wrong file, the file has to be https://unpkg.com/vue-i18n@9.0.0-beta.3/dist/vue-i18n.cjs.js please fix this.

**Comment by KarimDaghari** [comment]
You can always submit a PR here (https://github.com/typeorm/typeorm.github.io). Otherwise there's always the docs folder (https://github.com/typeorm/typeorm/tree/master/docs)

**Comment by abdoreact** [comment]
thanks!

**Comment by imnotjames** [comment]
Given this is unrelated to the core typeorm library I'll be closing it - but please feel free opening an issue against the website's repo or any pull requests.
