### ISSUE TITLE
select subQuery SUM Field not get

### ISSUE THREAD

**Issue by nshusr** [typeorm/typeorm#6784]
``` javascript
let siteQb = createQueryBuilder(Site, 'site')
      .leftJoinAndSelect('site.siteIntroInfos', 'siteIntroInfo')
      .leftJoinAndSelect('site.area', 'area')
      .leftJoinAndMapMany('site.total', qb => {
        return qb.from(SiteTotal, 'siteTotal')
          .leftJoinAndSelect('siteTotal.site', 'totalSite')
          .addSelect('SUM(siteTotal.totalPrice)', 'totalPrice')
          .addSelect('SUM(siteTotal.totalUsageTime)', 'totalUsageTime')
          .addSelect('SUM(siteTotal.totalOrderNumber)', 'totalOrderNumber')
      }, 'totalAll', 'totalAll.totalSite_id = site.id')
      .where(whereBuilder)
      .orderBy({
        'site.id': 'ASC'
      })
```

not get select totalPrice, totalUsageTime, totalOrderNumber  in leftJoinAndMapMany

**Issue type: BUG**
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
What sql is this generating, and what do you expect?

**Comment by nshusr** [comment]
@imnotjames expect is response
```
[
  {}
]
```

**Comment by imnotjames** [comment]
Could you fetch the sql that's generated as well?  `getSql` should accomplish that via https://github.com/typeorm/typeorm/blob/master/docs/select-query-builder.md#getting-the-generated-query

I have a feeling this is not correctly selecting the data.  The reason for that is that `leftJoinAndMapMany` does not select the data out from the join unless it's part of the entities.

I don't think the code as requested could generate the expected results - and I think the generated SQL will help you get towards the right direction there.

**Comment by nshusr** [comment]
thank you.

I can get data using getRawMany, but getMany always does not merge my custom attributes in subQuery.

**Comment by imnotjames** [comment]
This is closer to a question than a big report from what I can see.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
