### ISSUE TITLE
how to update the column which decorator has been set update:false

### ISSUE THREAD

**Issue by wxyer** [typeorm/typeorm#6789]
**Issue type:**
how to update the column which decorator has been set update:false

[ ] bug report
[ x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

```
@Column({ type: 'simple-json', nullable: true, update: false })
  BaseData: DataAbstractEntity | null;
```
  most of time i don't need update the column
  how  can i update the column when i need update under some conditions, is there any methods like 'addselect'?

**Comment by germangamboa95** [comment]
In this case what you want to do is use `insert()` rather than `save()`
 ```javascript
    /**
     * Inserts a given entity into the database.
     * Unlike save method executes a primitive operation without cascades, relations and other operations included.
     * Executes fast and efficient INSERT query.
     * Does not check if entity exist in the database, so query will fail if duplicate entity is being inserted.
     * You can execute bulk inserts using this method.
     */
  insert<Entity>(target: ObjectType<Entity> | EntitySchema<Entity> | string, entity: QueryDeepPartialEntity<Entity> | (QueryDeepPartialEntity<Entity>[])): Promise<InsertResult>;
```

**Comment by imnotjames** [comment]
Why do you want to update the column when you set update to false?  What's the use case? 

Asking as that will help determine the best approach to your issue

**Comment by wxyer** [comment]
> Why do you want to update the column when you set update to false? What's the use case?
> 
> Asking as that will help determine the best approach to your issue

i update the entire entity usually，so worry about the column can be dirty updating,i will update these two columns specifically， and now  when i update the entire entity ,i use 'reflect' to delete those columns

**Comment by imnotjames** [comment]
Does it actually send them over when you haven't changed them?

If you want to be explicit in when you update these columns, perhaps make them private on the model and add a setter function for setting them?

**Comment by wxyer** [comment]
> Does it actually send them over when you haven't changed them?
> 
> If you want to be explicit in when you update these columns, perhaps make them private on the model and add a setter function for setting them? Instead of disabling updates.
> 
> The point of `update: false` is to explicitly prevent updates from occurring - so if you do end up finding a way to update them that means typeorm has a bug where it's failing to prevent the update.

ok i get your idea thank you

**Comment by imnotjames** [comment]
Another approach could be working with the `BeforeUpdate` hook but that's a bit hackier.  The slack might be a better place to dig into either path.

As far as I know - Dynamically setting that `update` flag (or any column metadata) is not on the near term roadmap.
