### ISSUE TITLE
Question on update query

### ISSUE THREAD

**Issue by jjude** [typeorm/typeorm#679]
May be this has to do with my understanding of Javascript. Still let me ask.

```
const siteDetails = {name:"hello", type:1};

const result = await dbConnection
      .getRepository(Site)
      .createQueryBuilder("site")
      .update(siteDetails)
      .where("site.id = :siteId and site.owner = :ownerId", { siteId, ownerId: userId })
      .execute();
```

This raises the following error:

```
Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify inserted values.
```
However, if I do 

```
const result = await dbConnection
      .getRepository(Site)
      .createQueryBuilder("site")
      .update({name:"hello", type:1})
      .where("site.id = :siteId and site.owner = :ownerId", { siteId, ownerId: userId })
      .execute();
```

it works. How do I pass update values in a variable?

**Comment by pleerock** [comment]
no, its the same. I don't know what problem you have but this code is identical, please recheck everything once again.

**Comment by pleerock** [comment]
any updates?

**Comment by peterhoneder** [comment]
just one note where just this error can come along: the object passed in to set() or something similar in query builder to set the attributes to be updated in update or inserted in insert needs to be instanceof Object. In my case graphql objects returned from apollo server where not instanceof Object, which makes passing them directly on to TypeORM fail (you can Object.assign them e.g. to solve it).

**Comment by intsco** [comment]
In my case, the object I was trying to pass to query builder didn't have a prototype.
I solved the issue the following way
```const group = await connection.createQueryBuilder()
        .update(GroupModel)
        // .set({shortName: groupDetails.shortName})
        .set(groupDetails)
        .set({...groupDetails})
        .where('id = :id', { id: groupId })
        .execute();```
