### ISSUE TITLE
Question about cascades

### ISSUE THREAD

**Issue by vladwulf** [typeorm/typeorm#6791]
Hey guys,

I was not sure where to put so I've created this issue.
I'd like to know if there is a performance hit doing something like this.

```javascript
const parent = new ParentEntity();
const newChild = new ChildEntity();

parent.children = [...parent.children, newChild];
```
versus 

```javascript
const parent = new ParentEntity();
const newChild = new ChildEntity();

newChild.parent = parent;
```

When I use the first approach does the ORM intelligently avoid to reassign the same entity if it has already been assigned?

Thanks!

**Comment by imnotjames** [comment]
Try it and see?

First version you'll have to load all of the children - as long as you've done that it shouldn't have much impact in either case in the generated SQL.

**Comment by imnotjames** [comment]
Hope this helped you out.  If you find that there's a difference please feel free to open another issue detailing it as a bug report.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
