### ISSUE TITLE
Ionic 5 poor performance when browser is set as mobile device

### ISSUE THREAD

**Issue by bolivir** [typeorm/typeorm#6794]
**Issue type:**

[ X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[X ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Simple DB setup with one entity, when the database is set to synchronize and then run in the browser (Set chrome as mobile device) the startup performance is slow and takes a while before the first screen will show up. The weird thing is that for my feeling this issue only occurs on chrome when its set as a mobile device ....

Already tried the solution given here, otherwise i get an qa is not a function error.
https://github.com/typeorm/typeorm/issues/6131

**Comment by imnotjames** [comment]
Is it that you're fetching the sql.js library?

This doesn't sound like a problem with TypeORM, exactly - but do you have a way to replicate this issue?

**Comment by bolivir** [comment]
Its not the fetching part, the app starts with a console log of sync db which takes so long to start/complete

I just downgraded my ionic 5 projects angular version to 9, now it runs fine in chrome with sql.js 1.1.0 and typeorm 0.2.21.
Will see if i can provide a example project with this issue.

**Comment by imnotjames** [comment]
Check out sql.js 1.3.2 & use wasm per https://github.com/typeorm/ionic-example/pull/38

If it's taking a while, try using the wasm but if you can't use it -- it's not going to be fast.

**Comment by imnotjames** [comment]
I'll be closing this issue out but if you can create a reproducible example we can reopen the issue and continue investigation.
