### ISSUE TITLE
ER_DUP_ENTRY, when readd the unique index when the unique row already deleted

### ISSUE THREAD

**Issue by Rionardo** [typeorm/typeorm#6798]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

- Create Unique index using QueryRunner
- Add Row to DB
- delete the row from DB
- Add same row again in DB 
- QueryFailedError: ER_DUP_ENTRY: Duplicate entry --- for key ----

```
      await queryRunner.connect();
      await queryRunner.startTransaction();
      .....
      balanceFlow.user_id = id;
      balanceFlow.amount = amount;
      balanceFlow.ref_code = refCode;
      balanceFlow.ref_id = refId;
      balanceFlow.ref_type = refType;

      await balanceRepo.insertData(balanceFlow);
      await queryRunner.commitTransaction();
```
   
![image](https://user-images.githubusercontent.com/41901530/94513706-a0e28500-0249-11eb-839d-dd97b1bd1e49.png)

**Comment by imnotjames** [comment]
In one you're using the query runner in a transaction and in the other you're using a separate repository which isn't in the transaction (I'm assuming.)

This means the transaction hasn't landed & the record still technically exists.

**Comment by Rionardo** [comment]
@imnotjames no, actually it's part of queryRunner, actually it's a class i'm using 
```
  constructor(entityManager: EntityManager) {
    this.entityManager = entityManager;
  }
```
something like this,
```
    const queryRunner = getConnection().createQueryRunner();
    await queryRunner.connect();
    await queryRunner.startTransaction();
    const entityManager = queryRunner.manager;

    const balanceRepo = new SellerBalanceFlowRepository(entityManager);
```
this is how i pass the query runner manager

**Comment by Rionardo** [comment]
ah sorry @imnotjames it's my mistake i just realized i've almost 2 typical tables, with same unique id i forgot to delete that data
