### ISSUE TITLE
How can I incr/decr a value?

### ISSUE THREAD

**Issue by ruiming** [typeorm/typeorm#680]
How can I increase a value by one in one step? Seems that `updateById` can not do this. Can I do that by using queryBuider? Thanks.

**Comment by pleerock** [comment]
you simply load an object, increase its property and save object, e.g. 

```ts
const post = await repository.findOneById(1);
post.counter++;
await repository.save(post);
```

**Comment by ruiming** [comment]
@pleerock Would't it result in dirty write in some situation?

**Comment by pleerock** [comment]
alternatively you can use QueryBuilder to run update query:

```ts
        await connection.createQueryBuilder()
            .update(User)
            .set({ counter: () => "counter + 1")
            .execute();
```

See example [here](https://github.com/pleerock/typeorm/blob/c5edd3956a5ab0f82d269ed6b2e8bc9922327af5/test/functional/query-builder/update/query-builder-update.ts#L52-L52).

Or you can simply run sql query using `connection.query` method.

**Comment by ruiming** [comment]
This is what I want. Thanks.

**Comment by tomoat** [comment]
@pleerock 
```
 .set({ counter: () => "counter + 1"})
```

**Comment by pleerock** [comment]
?

**Comment by tomoat** [comment]
@pleerock  
There is a symbol missing in your code ```}```

**Comment by pleerock** [comment]
@tomoat ah thank you

**Comment by hellokvn** [comment]
> you simply load an object, increase its property and save object, e.g.
> 
> ```ts
> const post = await repository.findOneById(1);
> post.counter++;
> await repository.save(post);
> ```

Running save() is a bit huge for just updating a single property. If you do it by repository you should use update() instead of save(), it's simply faster because update() doesn't update the whole column.

```ts
const post = await repository.findOneById(id);
await repository.update(id, { counter: post.counter +  1 });
> ```

**Comment by haroonKhan-10p** [comment]
In my case I don't want to check if the record exists and just want to icrement/decrement a value given I have an id of the record. The above approaches don't take that into account.

**Comment by haroonKhan-10p** [comment]
For bulk you'd do:
```ts
const repo = getRepository(Feed);
  return repo
    .createQueryBuilder('feeds')
    .update(Feed)
    .whereInIds(feedIds)
    .set({ viewCount: () => 'viewCount + 1' })
    .execute();
```

**Comment by shobhit-ec11** [comment]
how can i make this variable by introducing x. Please let me know

const repo = getRepository(Feed);
let x = 10;
  return repo
    .createQueryBuilder('feeds')
    .update(Feed)
    .whereInIds(feedIds)
    .set({ viewCount: () => 'viewCount + x' })
    .execute();

**Comment by hellokvn** [comment]
> how can i make this variable by introducing x. Please let me know
> 
> const repo = getRepository(Feed);
> let x = 10;
> return repo
> .createQueryBuilder('feeds')
> .update(Feed)
> .whereInIds(feedIds)
> .set({ viewCount: () => 'viewCount + x' })
> .execute();
> It will not work this way what is the correct method

```ts
const repo = getRepository(Feed);
let x = 10;
return repo
.createQueryBuilder('feeds')
.update(Feed)
.whereInIds(feedIds)
.set({ viewCount: () => `viewCount + ${x}` })
.execute();
```

**Comment by shobhit-ec11** [comment]
> > how can i make this variable by introducing x. Please let me know
> > const repo = getRepository(Feed);
> > let x = 10;
> > return repo
> > .createQueryBuilder('feeds')
> > .update(Feed)
> > .whereInIds(feedIds)
> > .set({ viewCount: () => 'viewCount + x' })
> > .execute();
> > It will not work this way what is the correct method
> 
> ```ts
> const repo = getRepository(Feed);
> let x = 10;
> return repo
> .createQueryBuilder('feeds')
> .update(Feed)
> .whereInIds(feedIds)
> .set({ viewCount: () => `viewCount + ${x}` })
> .execute();
> ```

Thanks this is working , how can i achieve something like this:--
I want to set the value to be max value for the parameter if it crosses the threshold
.set({ viewCount: () => `viewCount + ${x} > MAX_VALUE ? MAX_VALUE :  viewCount + ${x}` })

**Comment by falahati** [comment]
This allows for SQL injection tho if the value of `x` is user-provided.
I am new to typeorm, but I think this might be safer:
```typescript
const repo = getRepository(Feed);
let x = 10;
return repo
    .createQueryBuilder('feeds')
    .update(Feed)
    .whereInIds(feedIds)
    .set({ viewCount: () => 'viewCount + :x' })
    .setParameter("x", x)
    .execute();
```

**Comment by CemYil03** [comment]
> > you simply load an object, increase its property and save object, e.g.
> > ```ts
> > const post = await repository.findOneById(1);
> > post.counter++;
> > await repository.save(post);
> > ```
> 
> Running save() is a bit huge for just updating a single property. If you do it by repository you should use update() instead of save(), it's simply faster because update() doesn't update the whole column.
> 
> ```ts
> const post = await repository.findOneById(id);
> await repository.update(id, { counter: post.counter + 1 });
> ```

Why the negative feedback to this answer?

**Comment by falahati** [comment]
@CemYil03,
well, both save and update are susceptible to overwrite problems which you might have to fix by optimistic or pessimistic locking depending on the situation. But a direct increase on the counter in a single query does not have this problem as the database itself takes care of the locking and queueing of the queries required to update that row.

**Comment by vitorbertolucci** [comment]
@falahati @CemYil03 I believe it would be safe to use `.update()` in the following way:

`await repository.update(id, { counter: () => 'counter + 1' });`

**Comment by MuhametSmaili** [comment]
In the documentation you can check for increment/ decrement value, check [here](https://github.com/typeorm/typeorm/blob/master/docs/repository-api.md#:~:text=increment%20%2D%20Increments%20some%20column%20by%20provided%20value%20of%20entities%20that%20match%20given%20options.)

**Comment by juanjodev02** [comment]
> > > you simply load an object, increase its property and save object, e.g.
> > > ```ts
> > > const post = await repository.findOneById(1);
> > > post.counter++;
> > > await repository.save(post);
> > > ```
> > 
> > 
> > Running save() is a bit huge for just updating a single property. If you do it by repository you should use update() instead of save(), it's simply faster because update() doesn't update the whole column.
> > ```ts
> > const post = await repository.findOneById(id);
> > await repository.update(id, { counter: post.counter + 1 });
> > ```
> 
> Why the negative feedback to this answer?

Because in a data-intensive application, the in-memory post.counter value may not be te real database value (if another process change the column value, the in memory value will be outdated), so if you use this in-memory value to update the column, you will have unreal data.

**Comment by gokturktopar** [comment]
You can also use built-in typeorm function. It's like

`  await connection.manager.increment(
                        Post, 
                        { id: 2 }, 
                        "totalView",
                        1,
                    )`

`  await connection.manager.increment(
                        entity,
                     condition,
                        field name,
                        increment rate
                    )`

**Comment by ChrisCho-H** [comment]
> you simply load an object, increase its property and save object, e.g.
> 
> ```ts
> const post = await repository.findOneById(1);
> post.counter++;
> await repository.save(post);
> ```

It might be an irrelevant for this issue but I've got just wondering by this comment(which can cause dirty write), if the situation is you must 'select and then update using instance's field', using `select for update` would work for it?
