### ISSUE TITLE
i get many issue when update new version =(

### ISSUE THREAD

**Issue by khangvu07031996** [typeorm/typeorm#6808]
**Issue type:**

[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
I'm sorry to hear that.  What issues are you having?

**Comment by imnotjames** [comment]
Unfortunately, without much information to go on we can't replicate the issues you're seeing.

Please open a new issue with a more descriptive title & information on what the problem is and how to replicate it.
