### ISSUE TITLE
Bug in new release I am greeting issue while making build.

### ISSUE THREAD

**Issue by niteshtripathi1234** [typeorm/typeorm#6809]
BUG
node_modules/typeorm/connection/Connection.d.ts(89,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/connection/Connection.d.ts(95,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/connection/ConnectionOptionsReader.d.ts(55,19): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/connection/ConnectionOptionsReader.d.ts(59,19): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/connection/ConnectionOptionsReader.d.ts(63,19): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/entity-manager/MongoEntityManager.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/find-options/FindOperator.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/find-options/FindOperator.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/find-options/FindOperator.d.ts(36,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/find-options/FindOperator.d.ts(40,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/find-options/FindOperator.d.ts(44,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/Alias.d.ts(18,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/Alias.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/Alias.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/Alias.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/JoinAttribute.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/JoinAttribute.d.ts(43,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/JoinAttribute.d.ts(47,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/JoinAttribute.d.ts(54,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/JoinAttribute.d.ts(62,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/JoinAttribute.d.ts(71,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/JoinAttribute.d.ts(76,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/JoinAttribute.d.ts(80,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/JoinAttribute.d.ts(81,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/JoinAttribute.d.ts(82,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/QueryBuilder.d.ts(48,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/QueryExpressionMap.d.ts(236,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/QueryExpressionMap.d.ts(263,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-count/RelationCountAttribute.d.ts(24,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-count/RelationCountAttribute.d.ts(31,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-count/RelationCountAttribute.d.ts(39,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-count/RelationCountAttribute.d.ts(40,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-count/RelationCountAttribute.d.ts(46,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-count/RelationCountAttribute.d.ts(51,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-count/RelationCountAttribute.d.ts(52,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-id/RelationIdAttribute.d.ts(31,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-id/RelationIdAttribute.d.ts(38,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-id/RelationIdAttribute.d.ts(46,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-id/RelationIdAttribute.d.ts(52,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-id/RelationIdAttribute.d.ts(56,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-id/RelationIdAttribute.d.ts(61,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-id/RelationIdAttribute.d.ts(62,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/query-builder/relation-id/RelationIdAttribute.d.ts(63,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/repository/AbstractRepository.d.ts(23,19): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/repository/AbstractRepository.d.ts(28,19): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/repository/BaseEntity.d.ts(63,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/repository/Repository.d.ts(42,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/typeorm/schema-builder/table/Table.d.ts(54,9): error TS1086: An accessor cannot be declared in an ambient context.
I am getting this issue with the latest version. Please resolve it as soon as possible.

**Comment by imnotjames** [comment]
Hi there - looks like you're using typescript - what version?

**Comment by niteshtripathi1234** [comment]
Hi Typeorm/Typeorm
Current i am using  "typescript": "3.5.3 .

**Comment by imnotjames** [comment]
Ok - looks like we have to downgrade to Typescript 3.6 to maintain compatibility with 3.3+ - as there was a breaking change introduced in 3.7 that tanks compatibility with lots of things.

**Comment by niteshtripathi1234** [comment]
Please let me know once it Typescript version downgrade so, that i will try
at my end.

**Comment by imnotjames** [comment]
This should be fixed as of 0.2.28

**Comment by niteshtripathi1234** [comment]
Thanks for short this issue on very short notice.
