### ISSUE TITLE
TypeORM 0.2.27 doesn't connect to react-native-sqlite-storage driver (Error: DriverPackageNotInstalledError: React-Native package has not been found installed)

### ISSUE THREAD

**Issue by oleksandr-dziuban** [typeorm/typeorm#6811]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

TypeORM v0.2.27 doesn't connect to react-native-sqlite-storage driver.
Error is shown: 
``DriverPackageNotInstalledError: React-Native package has not been found installed. Try to install it: npm install react-native-sqlite-storage --save``

TypeORM v0.2.24 works fine. TypeORM v0.2.26 cannot be used with react-native as it has broken browser environment issues fixed in v0.2.27.
``react-native-sqlite-storage`` is installed correctly. Used v4.0.0 and v5.0.0.

Looks like the same issue as Hana driver.

**Comment by imnotjames** [comment]
Different issue from hana - this did need to use `require` instead of `PlatformTools.load` in the `ReactNativeDriver`

**Comment by imnotjames** [comment]
Can you check if #6814 fixes your issue?

**Comment by oleksandr-dziuban** [comment]
> #6814

Will do, one moment

**Comment by oleksandr-dziuban** [comment]
@imnotjames It's working perfectly now, thanks a lot! What do you think how soon community could deploy 0.2.28 with this fix?

**Comment by imnotjames** [comment]
There's a few other related fixes we will probably be trying to get in for 0.2.29 :)

**Comment by oleksandr-dziuban** [comment]
> There's a few other related fixes we will probably be trying to get in for 0.2.29 - no exact ETA but definitely before the end of October! Hopefully much sooner than that.

Ok, thanks a lot
