### ISSUE TITLE
Cannot find namespace 'ZenObservable'.

### ISSUE THREAD

**Issue by lucaslacerdacl** [typeorm/typeorm#6817]
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[X] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When trigger build in my node API I receive this error:

node_modules/typeorm/observer/QueryObserver.d.ts:20:27 - error TS2503: Cannot find namespace 'ZenObservable'.
20     subscriptionObserver: ZenObservable.SubscriptionObserver<any>;

I already try to install de dependency, but the error persists.

**Comment by pleerock** [comment]
we probably need to migrate from `zen-observable` to `zen-observable-ts`. Your issue should be fixed if you manually install its typings `npm i @types/zen-observable`

**Comment by pleerock** [comment]
I've replaced `zen-observable` to `zen-observable-ts`. Check if that works (in `0.3.0-rc.21`).

**Comment by lucaslacerdacl** [comment]
Still with error.
Here is the log after install zen-observable-ts and @types/zen-observable:

[10:45:45] Starting 'compile'...
node_modules/typeorm/observer/QueryObserver.d.ts:3:8 - error TS1259: Module '".../node_modules/@types/zen-observable/index"' can only be default-imported using the 'esModuleInterop' flag

3 import Observable from "zen-observable";
         ~~~~~~~~~~

  node_modules/@types/zen-observable/index.d.ts:69:1
    69 export = Observable;
       ~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

**Comment by lucaslacerdacl** [comment]
Any update? My API is blocked because this issues.
