### ISSUE TITLE
ts-node throwing RepositoryNotFoundError

### ISSUE THREAD

**Issue by zackarychapple** [typeorm/typeorm#682]
Here is the example repo. https://github.com/zackarychapple/flagger

When I am starting the server with nodemon everything initializes correctly however when seed tries to run it bombs out with the below error.  I tried several paths for mapping to my entities however it seems none of them pick up.  Any thoughts?

```
(node:99829) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RepositoryNotFoundError: No repository for "FlagsEntity" was found. Looks like this entity is not registered in current "default" connection?
(node:99829) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by apologetics** [comment]
```
entities: [
        // any entity file under src/modules
        __dirname + '/*.entity.ts'
],
```

I can't find any `*.entity.ts` in the folder where this file (flags.database.config.ts) exists. It cannot grab your entities if the files they live in do not match the pattern you've specified.

**Comment by pleerock** [comment]
first, you don't need `TypeOrmDatabaseService` extra wrapper - typeorm already has everything you do and you just create extra redundant layer. Second, better if you'll use single ormconfig.json file and store your connection settings there. Third, create connection in your app bootstrap file, in a place like `server.ts`.

And regarding your problem - as @apologetics told you the problem in `__dirname + '/*.entity.ts'` - it does not point to any file, make sure your path are really point to entities.

**Comment by zackarychapple** [comment]
@apologetics you're right. The globber was not matching what I expected. `__dirname + '/../*/*.entity.ts'` is what got it to work for me.  Thank you for your help.

**Comment by zackarychapple** [comment]
@pleerock thank you for the notes, I will go through and simplify per your instructions.

**Comment by chriszrc** [comment]
I also had the same  `No repository for ... in current "default" connection` and it worked fine for development (running with nodemon), but failed after tsc compilation running under node. I had to change:

```
entities: [
          __dirname + '/../**/**.entity.ts'
 ],
```

to:

```
entities: [
          __dirname + '/../**/**.entity{.ts,.js}'
 ],
```

I see a reference to this in the typeorm docs, is this the prescribed way for dealing with entities in typescript? (https://typeorm.github.io/connection.html#creating-connection)

**Comment by pleerock** [comment]
no, it depends how you run your app. If you are running via `ts-node` then you can use ".ts" files as entities. If you aren't using `ts-node` then you must specify ".js" files. And you need to make sure to specify proper output directory (if you are using outDir tsc option) to ensure paths to your generated js files are correct.

**Comment by chriszrc** [comment]
Ok, thanks for clarifying, yes I use ts-node, but only during development (hence it worked running locally with nodemon). As a new typeorm user, this wasn't immediately evident to me from the docs, but I just started using ts-node, so maybe it's just a noob issue-

**Comment by apologetics** [comment]
@chriszrc Prove me wrong but I think it worked when I totally omitted the file extension and simply wrote
```
entities: [
    `${__dirname}/**/*.entity`,
]
```

**Comment by FriOne** [comment]
@pleerock could you explain how to make the same with .env config? I mean the `__dirname`

**Comment by pleerock** [comment]
its not possible. With .env it read files from your app root (where you have package.json), otherwise you must use absolute path (e.g. /etc/user/....)

**Comment by priestine** [comment]
@FriOne IMHO, it's incorrect to put path to the files containing entity classes in environment variables. It's not the kind of data that requires secrecy or changing from machine to machine. The other side of the medal is that your configuration object for database connection is sensitive. What I would do it put the database connection config object right in the code without outsourcing it to JSON or whatever, and only mark sentitive fields to be environmental. To me, this will give you the most in terms of control and freedom. Something like:

```
createConnection.then((c) => {
  user: process.env.DB_USER || 'root',
  password: process.env.DB_PASSWORD || '12345',
  entities: [
    `${__dirname}/**/*.entity`,
  ],
  // ...
});
```

**NOTE**: If you use Docker and official images, you can use straightforward env variables adopted by the owner of the DB image, like *MYSQL_DATABASE_NAME*.

**Comment by ahaw** [comment]
For me the easies and most suitable way (I'm bundling entities) was using explicit entities in create connection object

```
import {User} from '../auth/user.entity';
import {FacebookProvider} from '../auth/facebook/facebook-provider.entity';
import {GoogleProvider} from '../auth/google/google-provider.entity';
import {EmailAndPasswordProvider} from '../auth/email-and-password/email-and-password-provider.entity';
export const databaseProviders = [
    {
        provide: 'DbConnectionToken',
        useFactory: async () =>
            await createConnection({
                type: 'mssql',
                host: 'localhost',
                port: 1433,
                username: 'sa',
                password: 'TargeT54',
                database: 'HRates',
                schema: 'HRatesDev',
                synchronize: true,
                logging: false,
                cache: false,
                entities: [ User, FacebookProvider, GoogleProvider, EmailAndPasswordProvider],
            }),
    },
];
```

**Comment by ewrfedf** [comment]
just import and use your Entity in the bootstrap ts file
like
 `    console.log("Koa application is "+Entity.toString());
`

**Comment by dynarizkihabibah** [comment]
i found error it says that ``` cannot find name __dirname ``` what is that means?

**Comment by mymmoonoa** [comment]
Finally I can use official `npm run start:dev` and `npm run build > cd dist > node main`
after change the ormconfig.js
```
"entities": [
    __dirname + '/../**/**.entity.js'
 ],
```

**Comment by Glennsingh44** [comment]
I initially i have the same error but "entities": [
      "dist/**/*.entity.js"
  ],

**Comment by vifattahi** [comment]
It worked for me:

`const connectionOptions: ConnectionOptions = {
    name: `default`,
    type: `mysql`,
    port: 3306,
    synchronize: true,
    logging: true,
    host: `localhost`,
    username: `username`,
    database: `database`,
    password: ``,
    entities: [
        __dirname + '/entity/*{.ts,.js}'
    ]
}
createConnection(connectionOptions).then(async connection => {...})`

**Comment by sgentile** [comment]
unfortunately ts-node isn't production quality, so basically it forces everyone back to transpiling the code using tsc - which also effected some patterns with type-graphql .  Just a heads up.

**Comment by Matzu89** [comment]
@sgentile That's exactly what I did after a lot of hassling with nodemon and ts-node-dev. With ts-node-dev, somehow the repositories are not connecting, making it unusable.
Right now I use nodemon for watching, and then build with tsc to run node dist/index. Far from ideal..
