### ISSUE TITLE
Single Table Inheritance, promote base entity to child type

### ISSUE THREAD

**Issue by hitech95** [typeorm/typeorm#6826]
**Issue type:**

[ ] bug report
[ ] feature request
[X] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Lets say that I have a Single Table Inheritance, the column type is varchar (in the linked example below is of type int). https://github.com/typeorm/typeorm/blob/master/docs/entity-inheritance.md#single-table-inheritance

I have a similar case but my enum is mapped to a string instead of a integer:
https://github.com/typeorm/typeorm/tree/master/test/github-issues/184

I have a "simple" Content (Parent Entity) that have to become a Photo, how can I do that?
Keep in mind that Content is already stored in the DB and should be promoted.

I've tried to alter its type property but TypeORM seems to override it:
```
// Promote to photo type
myContent.type = ContentType.PHOTO;
myContent.save();
```

**Comment by imnotjames** [comment]
I don't believe it's possible at this time.

If you really want to do this, you'll need to drop down to the querybuilder.

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
