### ISSUE TITLE
Cascade not behaving as expected during update, child object delete attempted

### ISSUE THREAD

**Issue by arimus** [typeorm/typeorm#683]
TypeORM version: 0.1.0-alpha.32

Here are my example classes:

```javascript
@Entity()
export class User {

  @PrimaryGeneratedColumn()
  id?: number;

  @OneToOne(type => Location, location => location.user, {
    nullable: true,
    cascadeAll: true
  })
  @JoinColumn({
    name: 'locationId'
  })
  location?: Location;
}
```

```javascript
@Entity()
export class Location {
  @PrimaryGeneratedColumn()
  id?: number;

  @Column({
    length: '128',
    nullable: true
  })
  name?: string;

  @OneToOne(type => User, user => user.location, {
    nullable: true
  })
  user?: User;
}
```

I make changes to the user.location property on a loaded user object and then persist the user class, expecting the location updates to cascade:

```javascript
this.getEntityManager().getRepository(User).persist(user).then((oo) => {});
```

Which results in a delete being called (presumably to delete the old location and then create a new one to associate?)

> DELETE FROM `location` WHERE `id`=? -- PARAMETERS: [1]

However, as you can see from above, the user own the relationship and the location relation isn't removed first. This results in:

> ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`public`.`user`, CONSTRAINT `fk_974a227a147ad9c2fc91304adc4` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`))

In any case, a delete should never occur in the first place. An update should occur on the location object. It doesn't appear to be doing this. I reduced the problem and changed it such that all I do is load up the user object with the relation and then persist it unchanged...same issue:

> debug: executing query: START TRANSACTION
debug: executing query: UPDATE `user` SET `locationId`=?, `updatedAt`=?, `version`=?  WHERE `id`=? -- PARAMETERS: [1,"2017-07-19T06:37:23.314Z",4,2]
debug: executing query: DELETE FROM `location` WHERE `id`=? -- PARAMETERS: [1]
error: query failed: DELETE FROM `location` WHERE `id`=? -- PARAMETERS: [1]
debug: executing query: ROLLBACK
error: JwtAuthPlugin(): update user: failed Error: ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`schema`.`user`, CONSTRAINT `fk_974a227a147ad9c2fc91304adc4` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`))
    at Query.Sequence._packetToError (/Users/arimus/workspace/new/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/arimus/workspace/new/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/arimus/workspace/new/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/arimus/workspace/new/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/arimus/workspace/new/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/arimus/workspace/new/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/Users/arimus/workspace/new/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/Users/arimus/workspace/new/node_modules/mysql/lib/Connection.js:208:25)
    at MysqlQueryRunner.<anonymous> (/Users/arimus/workspace/new/src/driver/mysql/MysqlQueryRunner.ts:160:32)
    at step (/Users/arimus/workspace/new/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:32:23)
    at Object.next (/Users/arimus/workspace/new/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:53)
    at fulfilled (/Users/arimus/workspace/new/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:4:58)
    at propagateAslWrapper (/Users/arimus/workspace/new/node_modules/async-listener/index.js:421:23)
    at /Users/arimus/workspace/new/node_modules/async-listener/glue.js:188:31
    at /Users/arimus/workspace/new/node_modules/async-listener/index.js:458:70
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

I may be missing something silly, but pretty sure this wasn't an issue in previous versions.

**Note:** if I set only to cascadeUpdate, things appear to behave better (no delete attempted). However, I do want cascade inserts and deletes to occur when users are created / deleted.

**Comment by arimus** [comment]
Anyone have additional information on this problem? Is this a known bug, can you spot an issue that I didn't resolve above in moving to a newer version of typeorm, or...? The alternatives are pretty cumbersome and I'm not familiar enough with the codebase to poke at the cascading behavior.

Any assistance would be greatly appreciated.

**Comment by pleerock** [comment]
I recommend not to use cascades for now if you faced bugs. Cascades are very complex and I'll return to fixing them once I get free of other tasks.

**Comment by pleerock** [comment]
alternative is very simple - just iterate all objects you need to remove and call `manager.remove` method on them

**Comment by arimus** [comment]
Yeah, I've started going through the lengthy code and the tests that deal with cascades. And yes, the alternative isn't difficult, just more work refactoring code that was previously working. Poking around to see what I see. Thanks.

**Comment by pleerock** [comment]
sorry about that, I'll return to cascades once I finish with other tasks. Cascades and persistment  need huge refactoring and it will take few month of work which I can't afford at the moment

**Comment by arimus** [comment]
No worries. I appreciate all the hard work you put into this already. I'm sure everyone does.

I'm taking a look now and hopefully I'll find a reasonable stop gap to getting some of the basic use cases for cascading updates / deletes working. Will update with my results or lack thereof if I give up ;)

**Comment by arimus** [comment]
So a little bit of progress. I was able to at least partially resolve the issue with cascade updates triggering deletes. It seems that it was likely due to some ordering of operations in processing subject operations.

This change to remove the Promise.all() call and await each cascade remove/update builder call, and process things serially, seemed to do the trick. I noticed some out-of-order comments in tracing to pinpoint this. p.s. It'd be exceedingly helpful to have a second logger for non-SQL queries tracing and debugging.

From the tests I saw, this also seems to confirm that the issue I reported only occurs when cascadeUpdate is used in conjunction with cascadeDelete. Also, it may also be required to have the inverse side relation defined to experience this issue (not confirmed).

Here's the code change:

```
--- a/src/persistence/SubjectBuilder.ts
+++ b/src/persistence/SubjectBuilder.ts
@@ -106,9 +108,9 @@ export class SubjectBuilder<Entity extends ObjectLiteral> {
         // here we also find operate subjects which relations should be updated
         // these relations usually are "update from inverse side" operations
         const operateSubjectsWithDatabaseEntities = this.operateSubjects.filter(subject => subject.hasDatabaseEntity);
-        await Promise.all(operateSubjectsWithDatabaseEntities.map(subject => {
-            return this.buildCascadeRemovedAndRelationUpdateOperateSubjects(subject);
-        }));
+        operateSubjectsWithDatabaseEntities.map(async subject => {
+            await this.buildCascadeRemovedAndRelationUpdateOperateSubjects(subject);
+        });
```

This however led to a different test failing (one a cascade remove). However, I believe that the previous code may have led to a false positive test result here.

```
1) github issues > #151 joinAndSelect can't find entity from inverse side of relation should cascade remove successfully with uni-directional relation:
     AssertionError: expected { id: 1, name: 'post category' } to be empty
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)
      at Assertion.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:280:43)
      at Assertion.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at Object.<anonymous> (test/github-issues/151/issue-151.ts:87:37)
      at step (build/compiled/test/github-issues/151/issue-151.js:32:23)
      at Object.next (build/compiled/test/github-issues/151/issue-151.js:13:53)
      at fulfilled (build/compiled/test/github-issues/151/issue-151.js:4:58)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:208:7)
```

Thoughts? In any case, I'll keep digging to see if I can resolve the new test failure and shoot over a pull request when I do.

**Comment by arimus** [comment]
And I must be tired. My problem has the same potential issue and it's not as deterministic as I was shooting for. Have an alternate solution I'll be posting soon. Still trying to determine if I can get the remove() function to behave first.

**Comment by pleerock** [comment]
I have completely refactored persistance system and fixed all problems with cascades I have seen. Please try a new version (npm i typeorm@next) and let me know if your issue is not resolved in new versions too.

**Comment by arimus** [comment]
Thanks! I'll take a look.
