### ISSUE TITLE
[0.2.27] Regression: CLI migration:create fails with "TypeError: Cannot read property 'startsWith' of undefined"

### ISSUE THREAD

**Issue by constb** [typeorm/typeorm#6831]
**Issue type:**

[*] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Run (with `TYPEORM_MIGRATIONS_DIR=src/migrations` in `.env`):
```node --require ts-node/register ./node_modules/typeorm/cli.js -- migration:create -n SomeName```
Or even:
```TYPEORM_MIGRATIONS_DIR=src/migrations node --require ts-node/register ./node_modules/typeorm/cli.js -- migration:create -n SomeName```

Neither works. Only if I specify `-d` migration dir argument explicitly, it would create that migration.

Complete error output follows:

```
$ npm run typeorm -- migration:create -n SomeName

> xxx@0.0.1 typeorm /…/xxx
> node --require ts-node/register ./node_modules/typeorm/cli.js "migration:create" "-n" "SomeName"

Error during migration creation:
TypeError: Cannot read property 'startsWith' of undefined
    at Object.<anonymous> (/.../node_modules/.pnpm/typeorm@0.2.27/src/commands/MigrationCreateCommand.ts:62:37)
    at step (/.../node_modules/.pnpm/tslib@1.13.0/node_modules/tslib/tslib.js:141:27)
    at Object.throw (/.../node_modules/.pnpm/tslib@1.13.0/node_modules/tslib/tslib.js:122:57)
    at rejected (/.../node_modules/.pnpm/tslib@1.13.0/node_modules/tslib/tslib.js:113:69)
 ERROR  Command failed with exit code 1.
```

**Comment by imnotjames** [comment]
Issue is that while we're saying the variable directory is a string.. it's not.  It's possibly undefined - and via some edge cases it may remain undefined.

**Comment by imnotjames** [comment]
Ah, there's no verbosity or debug logger for these.  That's a bummer.
