### ISSUE TITLE
User doesn't get authenticated properly (MongoDB - buildConnectionUrl)

### ISSUE THREAD

**Issue by Masterrg** [typeorm/typeorm#684]
**Used MongoDB Version:** 3.4
**Problem:** The user doesn't get authenticated properly.

**File: typeorm/driver/mongodb/MongoDriver.js**
```js
MongoDriver.prototype.buildConnectionUrl = function () {
        if (this.options.url)
            return this.options.url;
        return "mongodb://" + (this.options.host || "127.0.0.1") + ":" + (this.options.port || "27017") + "/" + this.options.database;
    };
```

The created URL seems to be wrong, the correct version should be 
```js
(this.options.username != null) ? "mongodb://" + this.options.username + ":" + this.options.password + "@" + (this.options.host || "127.0.0.1") + ":" + (this.options.port || "27017") + "/" + this.options.database : "mongodb://" + this.options.username + ":" + this.options.password + "@" + (this.options.host || "127.0.0.1") + ":" + (this.options.port || "27017") + "/" + this.options.database;
```
_(In case the username is null the "authentication part" in the URL won't get added)_

**Reference:** https://docs.mongodb.com/manual/reference/connection-string/

**Comment by pleerock** [comment]
are you able to send a PR?

**Comment by Masterrg** [comment]
Not these days, maybe on saturday/sunday but i can't promise it yet :/

**Comment by newkillerbeast2017** [comment]
@Masterrg any update on this? Can we use mongodb with auth enabled in typeorm?

**Comment by webstrap** [comment]
For me authentication is working with Mongo 3.4, maybe try to add to the options

"authSource": "admin"

**Comment by championswimmer** [comment]
I have checked with a new mongodb instance and a basic example and it worked (using @webstrap's suggestion) . Please reopen if problem still persists
