### ISSUE TITLE
Feature Request: ORDER BY NULLS (FIRST | LAST)

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#685]
Hello!

I would propose to implement a `NULLS FIRST/LAST` option for `ORDER BY` clause.

In query builder it could looks like this:

`queryBuilder.orderBy('date', 'DESC', 'LAST');`

With `FindOptions` it could look like this:

```typescript
orderBy: {
  'entity.date': ['DESC', 'LAST']
}
```

**Comment by pleerock** [comment]
what are supported databases?

**Comment by pleerock** [comment]
Will be released in `0.1.0-alpha.38`

**Comment by slavafomin** [comment]
Cool, thanks! I'm working solely with PostgreSQL these days, so I can't really tell about other databases.

**Comment by victorschinaider** [comment]
It not works at SQL SERVER.

**Comment by havenchyk** [comment]
@victorschinaider please, create another issue with more details

**Comment by Jamie452** [comment]
Was this implemented for find options? Struggling to find an example.

**Comment by Creatium** [comment]
Any solution to this for MySQL? "NULLS LAST|FIRST" does not work for MySQL, so need another way.
