### ISSUE TITLE
problem with executing a sub query in from-expression (using different query builder)

### ISSUE THREAD

**Issue by dgbrokaw** [typeorm/typeorm#686]
Hi,

I am attempting to update to version `alpha.31` at least. I am using postgres.

In version 31 I experience a problem where queries that are structured like this test case: "should execute sub query in from expression (using different query builder)" (from "query builder > sub-query") do not correctly get the sub query. What happens is that, for example, the query will read "SELECT column-name FROM," at which point the query is over with nothing in the from-expression when there should be the sub query.

I ran typeorm's sub query tests for the postgres driver (`alpha.32`), and the test mentioned above that I expected to fail did not. I tried `alpha.32` in my project, and I did not encounter this error because upon starting my server I got another, different error. My question is, do we know if there was a fix for the problem I've described above in version 32? If so, I may be able to spend my time fixing this new bug. Otherwise, I could go for 31 and try to fix the bug I've described.

Thanks.

**Comment by pleerock** [comment]
I don't remember anything change in version 32 regarding to subqueries. But I may be wrong. And I didn't understand what exactly issue in. Can you please provide more details with concrete examples?

**Comment by dgbrokaw** [comment]
Sorry, I will try to update soon. Please leave the issue up for now.

**Comment by pleerock** [comment]
Any updates?

**Comment by pleerock** [comment]
I made docs [on how to use subqueries](https://github.com/typeorm/typeorm/blob/master/docs/query-builder.md#using-subqueries). Please update typeorm to latest version, follow docs and create a new issue with detailed explanation what is your issue if you'll still have it
