### ISSUE TITLE
Support array parameter in Raw (FindOperator)

### ISSUE THREAD

**Issue by tychota** [typeorm/typeorm#6860]
## Issue type

[ ] bug report
[x] feature request
[ ] documentation issue

## Database system/driver

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

## TypeORM version

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

### Problem

I want to be able to do the following query:

```sql
SELECT * FROM event_store.events 
WHERE event_store.get_stream_category(stream_name) = 'User'
AND event_store.get_stream_cardinal_id(stream_name) IN (
 '00000000-0000-4000-0000-000000000001',
 '00000000-0000-4000-0000-000000000002'
);
```

>Explanation:
> Given a stream_name: `User-00000000-0000-4000-0000-11111111111+11111111-1111-4111-1111-111111111111`
> `event_store.get_stream_category(stream)` returns `User`
> `event_store.get_stream_cardinal_id(stream)` returns `00000000-0000-4000-0000-11111111111`

Right now, I do

```ts
this.eventsRepository.find({
  where: {
    streamName: Raw((columnAlias) => {
      return `event_store.get_stream_category(${columnAlias}) = '${category}' AND event_store.get_stream_cardinal_id(${columnAlias}) IN ('${cardinalIds.map(id => `'${id}'`).join(", "}')`;
    }),
  },
  order: { inStreamPosition: 'ASC' },
});
```

Thank to the just merged PR (by @temnov98) (awesome work by the way 🥳) I can do

```ts
this.eventsRepository.find({
  where: {
    streamName: Raw((columnAlias) => {
      return `event_store.get_stream_category(${columnAlias}) = :category AND event_store.get_stream_cardinal_id(${columnAlias}) IN (:?)`;
    }, [:category, ?]),
  },
  order: { inStreamPosition: 'ASC' },
});
```
But I don't think that works for the `IN` statement

### Proposed solution

I think the perfect API for me would be:

```ts
this.eventsRepository.find({
  where: {
    streamName: Raw((columnAlias) => {
      return `event_store.get_stream_category(${columnAlias}) = :category AND event_store.get_stream_cardinal_id(${columnAlias}) IN :cardinalIds`;
    }, [category, cardinalIds]),
  },
  order: { inStreamPosition: 'ASC' },
});
```

And having TypeORM parsing it to `(elem[1], elem[2], ...)`
Like done here

https://github.com/temnov98/typeorm/blob/8966839bbaece5663be3473f09713be64559b00e/src/query-builder/QueryBuilder.ts#L889-L893

### Questions

- @pleerock: would the contribution be valuable for TypeOrm? Would you accept a PR (first contribution)? 
- @temnov98: if we agree to go this way, can you help me if I need help?
- is the join method secure enough? It is used in IN operator but how does it present SQL injection?

**Comment by temnov98** [comment]
@tychota You can use next syntax for your goals:

```
const result1 = await connection.getRepository(Post).find({
    likes: Raw((columnAlias) => `${columnAlias} IN (:...values)`, { values: [2, 3, 6] }),
});
```

**Comment by tychota** [comment]
Oh? nice, I didn't find that in document nor in the test. Let me then contribute by adding a test for this case.

**Comment by temnov98** [comment]
> Oh? nice, I didn't find that in document nor in the test. Let me then contribute by adding a test for this case.

Let's. It will be useful:)

**Comment by tychota** [comment]
Here you are: https://github.com/typeorm/typeorm/pull/6863
