### ISSUE TITLE
null union types don't seemed to be captured when using an Entity 

### ISSUE THREAD

**Issue by JamesLMilner** [typeorm/typeorm#6861]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] 0.2.25

**Steps to reproduce or a small repository showing the problem:**

## Current behavior

Let's say I have a User Entity with a `test` property which is a `string | null`:
![image](https://user-images.githubusercontent.com/8822075/95224426-92204300-07f2-11eb-9cb0-925856867245.png)

When you go to use this property it seems to type it to `string`:
![image](https://user-images.githubusercontent.com/8822075/95224397-892f7180-07f2-11eb-82c7-f0cd08c69095.png)

## Input Code

```ts

@Entity()
export class User {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({ nullable: true })
    test: string | null;
}
```

```ts

        user.test;

```

## Expected behavior

Property with union null types to possibly be null.

## Possible Solution

For Tooling issues:
- Node version: v12.18.3
- Platform:  Linux

Others:
I'm using VSCode
</code></pre>

**Comment by ardyfeb** [comment]
This is not typeorm related issue, i have same behavior on non typeorm project
![Screenshot_20201010_013448](https://user-images.githubusercontent.com/30074366/95620450-66bf8180-0a9a-11eb-9346-638d63dac724.png)
![Screenshot_20201010_013622](https://user-images.githubusercontent.com/30074366/95620457-6b843580-0a9a-11eb-9d45-4efbbf0ff9a5.png)

**Comment by imnotjames** [comment]
Ok - looks like that answered the question :) Not a bug.  Might be something to look into with vscode or by setting `strictNullChecks`.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
