### ISSUE TITLE
Silent failure in createDatabase and dropDatabase with postgres

### ISSUE THREAD

**Issue by manu-unter** [typeorm/typeorm#6867]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. Connect to a database server using `type: 'postgres'` and `database: 'postgres'`
2. Use `await queryRunner.createDatabase('my-database')` to set up a database

Expected result: The `my-database` database exists afterwards
Actual result: The method did nothing, as can be seen in the plain [`Promise.resolve()` in the QueryRunner implementation](https://github.com/typeorm/typeorm/blob/0280cdc451c35ef73c830eb1191c95d34f6ce06e/src/driver/postgres/PostgresQueryRunner.ts#L288-L302)

The same goes for `dropDatabase`

Why isn't this implemented? It looks like a technical limitation is what keeps this driver from being able to offer that functionality; In such a case, however, I would expect TypeORM to throw an exception instead to let the caller know that this won't work instead of acting as if we just happily created a database.

This silent failure just cost my colleague and me a few hours of debugging and it would have been as easy as:
```
throw new Error('`createDatabase` is not supported with the "postgres" driver - please use a manual query instead')
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by JulianG16** [comment]
Can confirm the issue @manu-unter describes

**Comment by imnotjames** [comment]
`next` has `NotImplementedError` - perhaps we can backport that here.

**Comment by imnotjames** [comment]
(PRs welcome to make that happen :smile: )

**Comment by imnotjames** [comment]
You're also welcome to add actual support to create and drop databases to driver
