### ISSUE TITLE
migrations not running

### ISSUE THREAD

**Issue by messerbill** [typeorm/typeorm#687]
hi,
my migrations are not running anymore. I executed the last migrate ~4 weeks ago, and afterwards i updated typeorm. That's why i noticed the behaviour not until now.

ormconfig.env:

```
TYPEORM_CONNECTION = mysql
TYPEORM_HOST = localhost
TYPEORM_PORT = 3306
TYPEORM_USERNAME = root
TYPEORM_PASSWORD = 
TYPEORM_DATABASE = typeormtable
TYPEORM_AUTO_SCHEMA_SYNC = true
TYPEORM_ENTITIES = models/*.js
TYPEORM_SUBSCRIBERS = 
TYPEORM_MIGRATIONS = migrations/*.js
TYPEORM_ENTITIES_DIR = models
TYPEORM_MIGRATIONS_DIR = migrations
TYPEORM_SUBSCRIBERS_DIR = 
```

I am using `"typeorm": "0.1.0-alpha.26"` and running TypeScript Version `2.4.1`

The migrations are neither executed on startup, nor by executing `typeorm migrations:run` -> the cl command results in:
>no migrations pending

There are also no entries added into the migrations-table.

Greetings,
Messerbill

**Comment by pleerock** [comment]
can you please update typeorm version to latest one and check if it still reproduce?

**Comment by messerbill** [comment]
i am now using `"typeorm":"latest"` and `npm update` updated to:
```
+-- @types/node@8.0.14
`-- typeorm@0.1.0-alpha.32  invalid
```
executing `typeorm migrations:run` out off the root directory of the project returns still `No migrations are pending`

**Comment by pleerock** [comment]
can you try to use `ormconfig.json` instead of env variables?

**Comment by messerbill** [comment]
it is working with ormconfig.json, thanks! but i'd really like to use .env variables - will this be fixed soon?

**Comment by pleerock** [comment]
I just checked it with ENV as well and it works:

```ts
TYPEORM_CONNECTION = mysql
TYPEORM_HOST = localhost
TYPEORM_PORT = 3306
TYPEORM_USERNAME = test
TYPEORM_PASSWORD = test
TYPEORM_DATABASE = test
TYPEORM_AUTO_SCHEMA_SYNC = true
TYPEORM_ENTITIES = "src/entity/*.js"
TYPEORM_SUBSCRIBERS = "src/subscriber/*.js"
TYPEORM_MIGRATIONS = "src/migration/*.js"
TYPEORM_ENTITIES_DIR = "src/entity"
TYPEORM_MIGRATIONS_DIR = "src/migration"
TYPEORM_SUBSCRIBERS_DIR = "src/subscriber"
```

result:

```bash
0 migrations are already loaded in the database.
1 migrations were found in the source code.
1 migrations are new migrations that needs to be executed.
Migration first1499098343783 has been executed successfully.
```

On latest typeorm version. Please check if you define things right in your env variables.

**Comment by pleerock** [comment]
Closing as no answer from reporter
