### ISSUE TITLE
allow pass a variable on listeners

### ISSUE THREAD

**Issue by techo207** [typeorm/typeorm#6874]
**Issue type:**

[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
 I have @AfterLoad() @AfterInsert() @AfterUpdate() @BeforeRemove() which call the same method but i need to pass a string

here is a example

```ts 
	@AfterLoad('a') @AfterInsert('b') @AfterUpdate('c') @BeforeRemove('d')
	something(name: string) {
		console.log( name);
	}
```

**Comment by imnotjames** [comment]
You just want to denote which is which?   In that case it's probably best for separate functions that call another function.

This feels like a very specific use case that's not fit for typeorm core & I suggest checking out or community support channels.

Check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
