### ISSUE TITLE
Undefined entity on RemoveEvent

### ISSUE THREAD

**Issue by Damian710** [typeorm/typeorm#6876]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a subscriber listening to insert and remove events. The entity on the RemoveEvent is always undefined. 
How can I get access to the removed entity on a RemoveEvent?

```import { Resource } from '@app/automatic-data-entities';
import { Injectable } from '@nestjs/common';
import {
  Connection,
  EntitySubscriberInterface,
  EventSubscriber,
  InsertEvent,
  RemoveEvent,
} from 'typeorm';
import { StorageService } from '../../storage/storage/storage.service';

@Injectable()
@EventSubscriber()
export class ResourceSubscriber implements EntitySubscriberInterface<Resource> {
  constructor(connection: Connection, private storageService: StorageService) {
    connection.subscribers.push(this);
  }

  listenTo() {
    return Resource;
  }

  afterInsert(event: InsertEvent<Resource>) {
    const resource: Resource = event.entity; // <- is defined
    this.storageService.addStorage(resource.organizationId, resource.size);
  }

  afterRemove(event: RemoveEvent<Resource>) {
    console.log('event.databaseEntity', event.entity); // <- is undefined
  }
}
```

**Comment by null-commit** [comment]
I also have this problem

**Comment by null-commit** [comment]
Er, er, It's solved for me. I used the wrong method [repo.delete] , when I used [repo.remove] , then I got right event entity.

**Comment by Damian710** [comment]
yes I also used the wrong method thank you

**Comment by taoliujun** [comment]
> Er, er, It's solved for me. I used the wrong method [repo.delete] , when I used [repo.remove] , then I got right event entity.

Even so, entity returns the deleted data, but its primary key id is undefined。
