### ISSUE TITLE
 Error using repository.update

### ISSUE THREAD

**Issue by alanscordoba** [typeorm/typeorm#6877]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

      let pid = tabla.id

      return await this.Repository.update(
          {predeterminado: false},
          {predeterminado: true, id: Not(pid)})

The above throws the following error: The expected type comes from property 'id' which is declared here on type 'QueryDeepPartialEntity <AliquotasIva>'

If I do it with Query Builder, it works fine.

      let pid = tabla.id

      return await this.Repository
      .createQueryBuilder()
      .update(AlicuotasIva)
      .set({predeterminado: false})
      .where("id != :pid",{pid})
      .andWhere("predeterminado = 1")
      .execute();

**Comment by imnotjames** [comment]
This looks like a question or a request for support, and not as much of a bug.

Please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
