### ISSUE TITLE
I cannot import the typescript entities while it is in the doc

### ISSUE THREAD

**Issue by devistar** [typeorm/typeorm#6882]
**Issue type:**

[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `^0.2.26` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In the documentation, it says that you can register typescript entities but when I do it it doesn't work.

![](https://i.imgur.com/4ARx5iS.png)

![](https://i.imgur.com/Sk9j38s.png)

![](https://i.imgur.com/QAEOUnS.png)

On the other hand, when I include the js entities from the dist directory, it works.

![](https://i.imgur.com/BNEWygK.png)

**Comment by imnotjames** [comment]
This is a question for the community support channels - we've seen this a few times and it's usually the environment.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
