### ISSUE TITLE
Documentation to portuguese

### ISSUE THREAD

**Issue by ThiagoFelippi** [typeorm/typeorm#6883]
## Documentation to portuguese
I was seeing documentation, I'm brazilian and typeorm is most popular here too. In documentation have only english and chinese version. If you'd like I can translate a part of documentation to portuguese.

[ ] bug report
[ ] feature request
[x] documentation issue

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Comment by imnotjames** [comment]
If you'd like to translate it, that'd be welcome!

We could potentially link to it, even!  But I don't know if we can host an official version of the documentation that's in a language other than English and Chinese - maintaining it long-term is quite a lot of work - especially for non-native speakers, like the maintainers of this project. :)

**Comment by ThiagoFelippi** [comment]
Ok, thanks! I'll translate but slowly, if result be good I send for you.
Thanks for attention!

**Comment by imnotjames** [comment]
You can always reach us in the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g)
