### ISSUE TITLE
Entity decorator orderBy produces ORDER BY title undefined, id undefined

### ISSUE THREAD

**Issue by valeriy-devpronet** [typeorm/typeorm#689]
This decorator does not work
https://github.com/typeorm/typeorm/blob/master/sample/sample30-default-order-by/entity/Post.ts#L6

typeorm v 0.0.11

**Comment by pleerock** [comment]
Try it in latest version please

**Comment by pleerock** [comment]
It must work in latest version, let me know if its not.
