### ISSUE TITLE
Inappropiate migration generated for 'float'

### ISSUE THREAD

**Issue by yaniv51** [typeorm/typeorm#6893]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,  
I'm using Typeorm and I'm facing an inappropiate migration generated for each 'float' property on each entity.
For example:

```
@Entity()
export class SomeEntity{
	@PrimaryGeneratedColumn()
	id: number;

	@Column()
	date: Date;

	@Column({ type: 'float', default: 0})
	data1: number;

	@Column({ type: 'float', default: 0 })
	data2: number;

	@Column({ type: 'float', default: 0 })
	data3: number;
}
```

  
While calling migration:generate, the query looks like:

```
await queryRunner.query("CREATE TABLE `some_entity` (`id` int NOT NULL AUTO_INCREMENT, `date` datetime NOT NULL, `data1` float NOT NULL DEFAULT 0, `data2` float NOT NULL DEFAULT 0, `data3` float NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB");
```

After running this migration file, I've noticed that for each generated migration, I'm getting inappropiate migrations for data1,data2,data3:

Up:

```
await queryRunner.query("ALTER TABLE `some_entity` CHANGE `data1` `data1` float NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `some_entity` CHANGE `data2` `data2` float NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `some_entity` CHANGE `data3 `data3` float NOT NULL DEFAULT 0");
```

Down:

```
await queryRunner.query("ALTER TABLE `some_entity` CHANGE `data1` `data1` float(12) NOT NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `some_entity` CHANGE `data2` `data2` float(12) NOT NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `some_entity` CHANGE `data3` `data3` float(12) NOT NULL DEFAULT '0'");
```

  
  After some digging, I found that MYSQL driver retuning a precision of 12 for each float (MysqlQueryRunner -> loadTables):

```
{
  "TABLE_CATALOG": "def",
  "TABLE_SCHEMA": "mydb",
  "TABLE_NAME": "some_entity",
  "COLUMN_NAME": "data1",
  "ORDINAL_POSITION": "5",
  "COLUMN_DEFAULT": "0",
  "IS_NULLABLE": "NO",
  **"DATA_TYPE": "float",**
  "CHARACTER_MAXIMUM_LENGTH": null,
  "CHARACTER_OCTET_LENGTH": null,
  **"NUMERIC_PRECISION": "12",**
  "NUMERIC_SCALE": null,
  "DATETIME_PRECISION": null,
  "CHARACTER_SET_NAME": null,
  "COLLATION_NAME": null,
  "COLUMN_TYPE": "float",
  "COLUMN_KEY": "",
  "EXTRA": "",
  "PRIVILEGES": "select,insert,update,references",
  "COLUMN_COMMENT": "",
  "GENERATION_EXPRESSION": ""
}
```

After loading this data, MysqlDriver -> findChangedColumns return this column as changed (probably because precision).

While runnig migration with RdbmsSchemaBuilder -> executeSchemaSyncOperationsInProperOrder -> updateExistColumns, current column('oldTableColumn') is set with precision of 12, while new column ('newTableColumnOptions') is set with precision  of undefined.

For overcome it, I have to change the entity settings to:

```
@Column({ type: 'float', default: 0, precision: 12})
```

Which is fine to do so, but it might be possible to set a default precision of 12 for mysql (5.7) or set this as a notice in your documentation.

Another migration issue is while using:

```
@Column({ default: null })
	date: Date;
```

It is also creating a migration for each generation. For fixing that, I have to set: 

```
@Column({ nullable: true })
	date: Date;
```

And the migration is seems to be fine.

**Comment by imnotjames** [comment]
I've updated the description to fix the formatting of your code blocks.  No idea what was up with 'em

**Comment by AlexMesser** [comment]
I've tested it and it looks like this was already fixed. Please update your TypeORM version to the latest and reopen this issue if the error persists.
