### ISSUE TITLE
"Unknown argument" error using TypeORM CLI

### ISSUE THREAD

**Issue by drtyh2o** [typeorm/typeorm#6896]
**Issue type:**
This used to work until recently:
```sh
node --require ts-node/register ../node_modules/typeorm/cli.js query "select count(*) from users" 
typeorm query

Executes given SQL query on a default connection. Specify connection name to run
query on a specific connection.

Options:
  -h, --help        Show help                                          [boolean]
  -c, --connection  Name of the connection on which to run a query.
                                                            [default: "default"]
  -f, --config      Name of the file with connection configuration.
                                                          [default: "ormconfig"]
  -v, --version     Show version number                                [boolean]

Unknown argument: select count(*) from metrics
```
Now, `--` must be used to avoid this error which is problematic when trying to run this via yarn/npm scripts.
```sh
node --require ts-node/register ../node_modules/typeorm/cli.js query -- "select count(*) from users" 
Running query: select count(*) from users
Query has been executed. Result:
[
  {
    "count": 104
  }
]
```

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by imnotjames** [comment]
Why is that a problem for yarn / npm scripts?

Looks like this behavior changes in `0.2.27` - that's when we updated `yargs`.

**Comment by imnotjames** [comment]
https://github.com/yargs/yargs/blob/master/CHANGELOG.md#-breaking-changes-3

> do not allow additional positionals in strict mode

Apparently we're using strict mode which I did not know.

**Comment by drtyh2o** [comment]
> Why is that a problem for yarn / npm scripts?

We call scripts from other scripts and `yarn` in particular doesn't pass the `--` through properly. I see you have a fix in process; looking forward to it. Thanks @imnotjames
