### ISSUE TITLE
Relation OneToMany involving instances of different Models

### ISSUE THREAD

**Issue by littlebacklash** [typeorm/typeorm#6897]
Hello!! I'm facing a weird (or not so much) scenario working with an existing database. I have a model which has a relation OneToMany with other Model. The particular case is that this last model can be one or another. Let's use an example to clarify it better:
There's a table in the db named "house" and two other tables named "person" and "person_without_doc" ... those could be imagined as a subclass of a generic Person entity (but it's not the case).
Then there is a third table "house_members", which represents the relation between the house and a person (or person without doc), and whose fields are: 
id
id_member
type (P or PWD)

this type field defines if the id_member belongs to person table or the other one.
My question would be how could I model this in order to get the member of a particular House entity ... i have read several cases but neither of them is similar to this one. I tried to use an additional fixed value in @joinColumn decorator but it seems not to work
Please advice!
Thanks

[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by littlebacklash** [comment]
you think I didn't do it before asking here? ... Haven´t found anything
