### ISSUE TITLE
Integration with Inversify

### ISSUE THREAD

**Issue by Shepless** [typeorm/typeorm#69]
Hi, firstly thanks for creating such an awesome project!

I am trying to integrate TypeOrm with Inversify IoC, I am using the `useContainer()` method but I am really struggling to get my head around how to setup a connection and make it injectable. I know there are good integrations with typedi, however typedi is missing some key features that I need so it's not a viable approach for my use case. Here is what I have tried:

``` js
@injectable()
class Orm {

    @inject("Provider<Connection>")
    private connectionProvider: interfaces.Provider<Connection>;

    private connection: Connection; 

    async init() {
        this.connection = await this.connectionProvider();
    }
}

let kernel = new Kernel();
useContainer(kernel);

kernel.bind<interfaces.Provider<Connection>>("Provider<Connection>").toProvider<Connection>((context) => {
    return () => {
        return createConnection({
            driver: {
                type: 'sqlite',
                storage: 'foo.sqlite'
            },
            entities: [
                __dirname + '/entities/*.js'
            ],
            autoSchemaSync: true
        });
    };
});

kernel.bind<ConnectionManager>(ConnectionManager).to(ConnectionManager);
kernel.bind<Orm>(Orm).to(Orm);

let orm = kernel.get<Orm>(Orm);
orm.init().then(() => console.log('DONE')).catch((e) => console.log(e));
```

The result is the catch handler triggers with the error: `Missing required @injectable annotation in: ConnectionManager.`

Is it possible to hook up the ConnectionManager to Inversify and make it injectable? Am I missing something obvious and stupid here?

**Comment by pleerock** [comment]
its actually better to ask inversify what to do in cases when you integrate with other libraries which does not have their annotation set. Maybe you do something wrong? May because you are setting `kernel.bind<ConnectionManager>(ConnectionManager).to(ConnectionManager);` it causes such error and you should not set it? As I mentioned if you are missing some feature in typedi you can propose it there and lets discuss if this can be implemented there.

**Comment by dreamersp** [comment]
At WonderBits we made a skeleton TS backend( with users, roles, permissions and OAuth tokens) using typeorm and Inversify and ended up using the singleton of a DB provider class that checks if a local db connection on itself is set or not to create a new connection or just return the previously set one. This is a kind of Factory/Provider pattern into an IoC injection pattern.
We were messing up with createConnection() returning a Promise and not being sure how to handle an unique connection with Inversify's Provider pattern so we ended up doing the aforementioned.

```
import ConfigProvider from './ConfigProvider';
import { injectable, inject } from 'inversify';
import { Connection, createConnection } from 'typeorm';

@injectable()
export default class DatabaseProvider {
  public db: Connection;

  constructor(@inject(ConfigProvider) private configProvider: ConfigProvider) {
  }

  getDBConnection(): Promise<Connection> {
    return Promise.resolve()
      .then(()=> {
        if (!this.db) {
          let config: any = this.configProvider.config;
          return createConnection({
            driver: {
              type: config.dialect,
              host: config.host,
              port: config.port,
              database: config.database,
              username: config.username,
              password: config.password
            },
            entities: [
              __dirname + '/../modules/**/*.model.ts'
            ],
            autoSchemaSync: true,
          });
        }
      })
      .then((db) => {
        if (!this.db && db) {
          this.db = db;
        }
        return this.db;
      })
      .catch((e) => {
        console.log('ERROR: ' + JSON.stringify(e));
        throw e; // Propagate the error
      })
  }
}
```

And then in the main server class we waits for getDBConnection() before instantiating the context class that depends on the DB provider. It isn't the cleaner way but we were forced by the asynchronous nature of createConnection() and our still incomplete control of Inversify and wanted to get a fast glimpse of typeorm working with our structure.
Anyway I agree with @pleerock that this shall be a question to make in Inversify context.

**Comment by Shepless** [comment]
@dreamersp Thanks for sharing. Interestingly, I have basically ended up with the same approach.

I think there are two issues here then:

1) The async nature of `createConnection()` doesn't appear to play nice with DI in general, is it possible for a synchronous version?

2) Asking the Inversify people how to hook up TypeOrm correctly to their container implementation.

**Comment by remojansen** [comment]
Hi guys. I'm the author of InversifyJS. Inversify allows you to inject an asynchronous factory (AKA provider). Providers are designed to inject objects with an asynchronous nature (e.g db clients).

A Provider is just a function that returns a promise:

    () => Promise<T>

In the next release (InversifyJS 3.0) we are going to improve the way providers work: https://github.com/inversify/InversifyJS/issues/418

I will try my best to document the integration with TypeORM :wink:

**Comment by pleerock** [comment]
[here](http://stackoverflow.com/questions/40880447/how-to-inject-an-asynchronous-dependency-in-inversify) @remojansen gave answer how to use typeorm with inversify
