### ISSUE TITLE
Repository find Raw query expect 1 arguments, but got 2

### ISSUE THREAD

**Issue by kiaisoft-aiad** [typeorm/typeorm#6904]
**Issue type:**

[ ] bug report
[ ] feature request
[X ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ X] `latest`
[ ] `@next`
[X ] `0.2.28`

Issue type:
I tried to query using repository find Raw. The doc specifies that there is a second paramter passed to Raw to prevent SQL injection: 

```
import {Raw} from "typeorm"; 

const loadedPosts = await connection.getRepository(Post).find({
    currentDate: Raw(alias =>`${alias} > ":date"`, { date: "2020-10-06" })
});
```
However Raw function import from typeorm only has 1 parameter
```
export declare function Raw<T>(value: string | ((columnAlias: string) => string)): FindOperator<any>;
```
either there seems to be inconsistency here or i'm using an outdated version of typeorm.

**Comment by imnotjames** [comment]
This will be released in the next patch release of TypeORM - we're going to be bumping that soon

**Comment by ddsultan** [comment]
> This will be released in the next patch release of TypeORM - we're going to be bumping that soon

Is it resolved or is there any workarounds? 

Thanks
