### ISSUE TITLE
DeleteDateColumn was removed from next version?

### ISSUE THREAD

**Issue by hendrixroa** [typeorm/typeorm#6905]
**Issue type:**

[ X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[X ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

- Did you remove the DeleteDateColumn from next version?, when I try to import DeleteDateColumn I receive these errors: 

`Module '"../../node_modules/typeorm"' has no exported member 'DeleteDateColumn'`

- How I can fix it or how I can create a pull request to fix that?

**Comment by imnotjames** [comment]
I still see it - and it's still in the source https://github.com/typeorm/typeorm/blob/088afa0e11bc71e62d9181d8856967b10e3d9636/src/index.ts#L34

Can you check to see if it's in the version you've fetched?

**Comment by hendrixroa** [comment]
The current next version, 0.3.0-alpha.24. Check the built in node_modules, the decorator disappeared 
![Uploading Screen Shot 2020-10-17 at 8.59.28 AM.png…]()

**Comment by imnotjames** [comment]
The alphas are old.  The latest of that branch is 0.3.0 rc21
