### ISSUE TITLE
Throwing error when trying to insert a row with an existing id

### ISSUE THREAD

**Issue by kavinvin** [typeorm/typeorm#691]
Is there's a way to disable auto-update when trying to insert a row that already exist in the database? It's quite dangerous when using `.persist` without knowing whether it'll insert or update the row as it can override some data accidentally. I know that I can firstly check if a certain id is already exist and then throw an error manually in that case, but it also cost one more trivial query. I personally don't have  any problem with that solution though. But I'm looking forward that TypeORM will support this in the future.

**Comment by pleerock** [comment]
Too specific requirement. `persist` (e.g. `save` in latest versions) simply updates your model if it already exist, and inserts a new record if its not. I don't think it needs such option. If you want to insert entity if it not exist only (and prevent updating) then simply check if its not exist before calling `persist`/`save` method.
