### ISSUE TITLE
How to select data from left join table, two unrelated tables? 

### ISSUE THREAD

**Issue by golubvladimir** [typeorm/typeorm#6912]
**Issue type:**

[ ] bug report
[ ] feature request
[*] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[*] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Documentation: https://github.com/typeorm/typeorm/blob/master/docs/select-query-builder.md#joining-any-entity-or-table

I have tow entities: Users and Settings tables.

```
@Entity()
export class Users {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string
}
```
```
@Entity()
export class Settings {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;
}
```
Relation One-to-One.

How to select data from Settings table ?
```
        return this.usersRepository
            .createQueryBuilder("users")
            .leftJoinAndSelect(Settings, 'settings', 'users.settingID = settings.id')
            .select(['users.id', 'users.name', 'settings.id', 'settings.name'])
            .getMany();
```

Now I don't get data from Settings table, only users table.

**Comment by imnotjames** [comment]
Try `getRawMany`.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
