### ISSUE TITLE
Typescript error TS6133: 'queryRunner' is declared but its value is never read

### ISSUE THREAD

**Issue by PetrShchukin** [typeorm/typeorm#6915]
**Issue type:**

[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. Add a migration
2. Make sure that in tsconfig.json there is "noUnusedParameters": true
3. Triy to compile

Expected behavior:
Build should be successful 

Current behavior:
An error shows up: error TS6133: 'queryRunner' is declared but its value is never read.

**Comment by imnotjames** [comment]
You need to include more information.  You're generating a migration?  What does it look like?

What do you expect it to look like?

**Comment by PetrShchukin** [comment]
Sorry, so the problem is with a typescript project where in tsconfig.json there is a line "noUnusedParameters": true, (no unused parameters) and with folder /src/migraions/ where we store all our migrations. I create a migration, a migration looks like this
```
import {MigrationInterface, QueryRunner} from "typeorm";

export class test1602868871740 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
```
When I try to compile the project I'm getting an error "'queryRunner' is declared but its value is never read" because obviously queryRunner in migrations is not used. Saying in advance using "exclude" in tsconfig.json makes no difference.

**Comment by imnotjames** [comment]
That migration does nothing - so the fact that you're receiving a compilation error is a good thing there.  You may have generated a migration with no changes needed.

The migration generation templates are not very complex - they're effectively string replace templates - so they can't do a whole lot.

**Comment by PetrShchukin** [comment]
So, you mean it's up to the developer clean the migration? If I delete queryRunner variable won't I break something, will I?

**Comment by imnotjames** [comment]
If you aren't using it, it won't break anything.  However, like I said - the migration you generated there does nothing anyway so there's not much to break :)

**Comment by PetrShchukin** [comment]
Thanks 👍
