### ISSUE TITLE
Closed connections in typeorm are not removed and cause heap out of memory error in a multi-tenant application.

### ISSUE THREAD

**Issue by svijaykoushik** [typeorm/typeorm#6917]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16`

**Steps to reproduce or a small repository showing the problem:**

Hi,
I am working on a rest api application on node js with multi tenant architecture. Each tenant has a separate DB and the host DB contains the details of every tenant.

Whenever a request hits our application,  the tenant is identified from the request URL, a new connection to the tenant DB is created and the request is served appropriately. When the requested process is completed the connection is closed.

Here is the pseudo code of my implementation
```ts
import { createConnection } from 'typeorm';

async function connect(tenant) {
    return await createConnection({
        name: uniqueConnectionName, // a unique string generated every time a new connection is needed
        type: 'mysql',
        host: tenant.db_host_url,
        port: tenant.db_host_port,
        username: tenant.db_username,
        password: tenant.db_password,
        database: tenant.db_name,
        entities: ['path/to/tenant/entities/*{.ts,.js}'],
        logging: false,
    });
}

async function serveRequest(request) {
    const connection = await connect(request.tenant);
    .
    .
    .
    do process
    .
    .
    .
    await connection.close();
}
```
The problem is that, the closed connections are never removed and they linger in the `getConnectionManager().connections` array. And over time the connections array grows so much that it causes a Heap out of memory error and the application crashes. I've looked throughout the documents but I could not find a way to remove the closed connections. As a temporary solution I restart the app at  specific intervals. Someone please look into this issue and provide me a solution. Thanks

**Comment by imnotjames** [comment]
> Someone please look into this issue and provide me a solution. Thanks

If you're opening and closing them constantly, create the connection yourself:

```
        const connection = new Connection(options);
```

**Comment by edilson** [comment]
I'm having the same issue, here is the code I'm using to create a connection:

```
import { createConnection, createConnections } from 'typeorm';

createConnections().then(connection => console.log(connection));
createConnection({
  type: 'mongodb',
  name: 'mongo',
  url: process.env.MONGODB_URL as string,
  useUnifiedTopology: true,
  useNewUrlParser: true,
  entities: [
    `${process.cwd()}/build/modules/**/infra/typeorm/schemas/*{.js,.ts}`,
  ],
});
```

ormconfig.json

```
[
  {
    "name": "default",
    "type": "postgres",
    "host": "localhost",
    "port": 5432,
    "username": "postgres",
    "password": "postgres",
    "database": "riderize",
    "logging": ["error"],
    "entities": [
      "./src/modules/**/infra/typeorm/entities/*.ts"
    ],
    "migrations": [
      "./src/shared/database/migrations/*.{ts, js}"
    ],
    "cli": {
      "migrationsDir": "./src/shared/database/migrations"
    }
  },
  {
    "name": "mongo",
    "type": "mongodb",
    "host": "localhost",
    "port": 27017,
    "database": "Riderize-production",
    "useUnifiedTopology": true,
    "entities": ["src/modules/**/infra/typeorm/schemas/*.ts"]
  }
]
```

The ormconfig is only used at dev env, in other envs I use env vars to connect.
