### ISSUE TITLE
Database identity insert with @PrimaryGeneratedColumn and MS SQL Server

### ISSUE THREAD

**Issue by sky-c** [typeorm/typeorm#6918]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.28` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

We have an typeorm entity established and are using the PrimaryGeneratedColumn to reference an identity key column in our MS SQL Server database like so:

```
export class Group implements IGroup {

    @PrimaryGeneratedColumn( {type:"int", name:"ID" } ) 
    id!: number;
```
As mentioned the id column is an identity PK column in SQL Server.  We have synchronize set to **false**.

When a new entity is saved, the id column value appears to be defaulting to the SQL Server calculated identity value.  This is our desired behavior.  However, we have not been able to find this specific behavior documented anywhere.  So the question is, ***can we assume that this is the intended behavior and it will be supported moving forward?***  Since we are relying on this behavior, we would like to confirm it won't change in a future release.

**Comment by imnotjames** [comment]
The default is that it uses the generated identity value however MSSQL handles it.  There's a PR open to ALLOW you to insert something else ( #6199 ) but it will not change this default behavior.
