### ISSUE TITLE
typeorm with javascript example

### ISSUE THREAD

**Issue by kotapatikk** [typeorm/typeorm#692]
i tried to implement given same in typeorm javascript example with oracledb.

getting below issue after changed to let const too.

const post = new Post();
    post.title = "Control flow based type analysis";
    post.text = "TypeScript 2.0 implements a control flow-based type analysis for local variables and parameters.";
    post.categories = [new Category(0, "TypeScript"), new Category(0, "Programming")];

    const postRepository = connection.getRepository(Post);

 

connection -->[object Object]
Error:  TypeError: Post is not a constructor
    at C:\Work-Soft\NodeTest\myapp\routes\select.js:22:16

**Comment by pleerock** [comment]
How did you define a schema?

**Comment by kotapatikk** [comment]
Thanks a lot for quickly response.

I have another issue to breaking my head.

C:\Work-Soft\TypeScriptTest>node --version
v6.11.1

C:\Work-Soft\TypeScriptTest>npm --version
5.3.0

C:\Work-Soft\TypeScriptTest>tsc --version
Version 2.4.2

import {Entity,PrimaryColumn,Column} from "typeorm";
@Entity()
export class Employee{
    @PrimaryColumn("number",{generated:true})
    id:number;

    @Column({type:"varchar2"})
    name:string;

   // @OneToOne(type => EmployeeMetadata, metadata => metadata.emp)
   // @JoinColumn()
  //  metadata: EmployeeMetadata|null;
}



import {EntityRepository} from "typeorm";
import {AbstractRepository} from "../node_modules/typeorm/repository/AbstractRepository";
import {Employee} from "./Employee";


@EntityRepository(Employee)
export class EmployeeRepository extends AbstractRepository<Employee>{
    findEmployee(){
        return this.createQueryBuilder("employee").getOne();
    }
    save(){
        return this.manager.persist(Employee);
    }
}


import "reflect-metadata";
import {createConnection, ConnectionOptions} from "typeorm";
import {Employee} from "./Employee";
import {EmployeeRepository} from "./EmployeeRepository";

const options: ConnectionOptions = {
    "type": "oracle",
    "host": "localhost",
    "username": "CC",
    "port" :1522,
    "password": "XX",
    "database": "XX",
    "sid": "orcl",
    logging: {
        logQueries: true,
        logFailedQueryError: false,
        logSchemaCreation: true
    },
    autoSchemaSync: true//,
    //entities: [__dirname + "/{*.ts,*.js}"]
};

createConnection(options).then(async connection => {    
console.log("connection ---------->"+connection);

console.log("employeee ----->"+Employee);


console.log("repo ----->"+EmployeeRepository);


console.log("                         ------------------                 "+ connection.getRepository(Employee));


    //let employeeRepository = connection.getCustomRepository(EmployeeRepository);

    //console.log("emps ---------->"+employeeRepository);

    // console.log("employeeRepository ---------->"+employeeRepository.create());

   // let emps = employeeRepository.manager.getRepository("employee").find();

    //console.log("emps ---------->"+emps);

  // const employees = await 
}, error => console.log("Cannot connect: ", error));



Issue is --  

(node:6692) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RepositoryNotFoundError: No repository for "Employee" was found. Looks like this entity is not registered in current "
default" connection?

Please help on to retrieve the data from employee table.?

**Comment by pleerock** [comment]
PLEASE FORMAT CODE PROPERLY BEFORE POSING A MESSAGE.

Are you sure you included your `Employee` entity in the connection configuration?

**Comment by kotapatikk** [comment]
Hi Pleerock

i added Employee entity connection configuration . Even though i added EmployeeRepository too.
See the above comment code too

**Comment by pleerock** [comment]
sorry I won't waste my time figuring out what you wrote there. See my message about formatting code above.

**Comment by shodhan** [comment]
hi 
was just wondering if you resolved this , i ran into similar issue while trying to do this in javascript
