### ISSUE TITLE
Column does not exist

### ISSUE THREAD

**Issue by yousss** [typeorm/typeorm#6930]
**Issue type:**

[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ 6.1.3 ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

i have created two tables, course and major with many to many relationship and when i update a table via its relations, it gives me error as below.

```
export class Course extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;
    @ManyToMany(
    type => Degree,
    major=> major.courses,
    { cascade: true },
  )
  @JoinTable()
  majors: Major[];
}
}
```

```
export class Major extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

   @ManyToMany(() => Course, course => course.majors)
    courses: Course[]
   
} 
```

this.repository.update(id,data);

```
QueryFailedError: column "courseId" of relation "course" does not exist [0]     at new QueryFailedError (D:\Learning\school\schoolApi\node_modules\typeorm\error\QueryFailedError.js:11:28) [0]     at Query.callback (D:\Learning\school\schoolApi\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:176:38) [0]     at Query.handleError (D:\Learning\school\schoolApi\node_modules\pg\lib\query.js:145:17) [0]     at Connection.connectedErrorMessageHandler (D:\Learning\school\schoolApi\node_modules\pg\lib\client.js:214:17) [0]     at Connection.emit (events.js:198:13) [0]     at Socket.<anonymous> (D:\Learning\school\schoolApi\node_modules\pg\lib\connection.js:134:12) [0]     at Socket.emit (events.js:198:13) [0]     at addChunk (_stream_readable.js:288:12) [0]     at readableAddChunk (_stream_readable.js:269:11) [0]     at Socket.Readable.push (_stream_readable.js:224:10)
```

**Comment by imnotjames** [comment]
Hey there, I moved your subject line into your message itself. It was very long and not descriptive of a problem.

We need more information to determine what this is - as right now I cannot determine if it's actually a bug or not.

Perhaps a Reproducible example would help?

**Comment by imnotjames** [comment]
Your `@ManyToMany` is incorrect.  It's `type => Degree,` instead of `type => Major` which is causing the issue.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
