### ISSUE TITLE
Suggestion: query shortener for logger

### ISSUE THREAD

**Issue by osdiab** [typeorm/typeorm#6935]
**Issue type:**

[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

This may be out of scope of TypeORM, but I find that the outputted queries from TypeORM logs tend to be very long due to the enumeration of very large numbers of explicitly enumerated columns, to the point where logging services my company uses just straight up truncate or erase them, which makes debugging harder; and that I generally don't need that level of detail 95% of the time. It would be cool if TypeORM could optionally support outputting shortened queries to error/slow query logs/custom loggers, for example by just replacing long column lists with `...`, that are just more readable when debugging.

that said it can be done manually by parsing the AST of these queries and editing them yourself after the fact, at least for some of the supported db drivers; but i bet this would be generally useful, so wondering if it would be out of scope for including alongside TypeORM itself as opposed to an external package.

**Comment by imnotjames** [comment]
Thanks for the suggestion!

Unfortunately, I am pretty sure this should be done outside of TypeORM as it's very specific to your use case.  The logs for queries are for debugging & other similar tasks.  In many cases those fields are very important for folks for their debugging purposes.

Also, Given the various platforms we have to support we can't bring in a SQL parser to after the fact parse the SQL & hide the fields.  Feel free to make the custom logger open source, though!  I'm sure others could benefit from it.
