### ISSUE TITLE
 Binding when using Oracle native query

### ISSUE THREAD

**Issue by kangmandoo** [typeorm/typeorm#6938]
**Issue type:**

[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.28`

When using Oracle, how to do binding in raw query?

I tried using the same method as mysql, but I got an error
`await getConnection().query("SELECT * FROM TEST WHERE ID = ?", ['test_01']);`
`(node:21284) UnhandledPromiseRejectionWarning: QueryFailedError: ORA-01036: illegal variable name/number`

Queries without bindings work fine.
`await getConnection().query("SELECT * FROM TEST WHERE ID = 'test_01'");`

**Comment by kdi-1** [comment]
In Oracle you should use colon sign ```:``` for parameter. 
Working query is ```await getConnection().query("SELECT * FROM TEST WHERE ID = :id", ['test_01']);```

**Comment by kangmandoo** [comment]
@kdi-1 thank you for the answer. It helped a lot.
