### ISSUE TITLE
Querybuilder like wildcard not wworking

### ISSUE THREAD

**Issue by imperiale-tech** [typeorm/typeorm#6939]
**Issue type:**

[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[x ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

**Code**
```
this.connection.getRepository(Order).createQueryBuilder('order')
                .innerJoinAndSelect('order.user', 'user')
                .where('order.id LIKE  :search', { search:  `%${spp.getSearch()}%` })
                .orWhere('user.firstName LIKE :search', { search: `%${spp.getSearch()}%` })
                .orWhere('user.lastName LIKE :search', { search: `%${spp.getSearch()}%` })
                .orWhere('user.email LIKE :search', { search:  `%${spp.getSearch()}%` })
                .distinct(true)
                .skip(spp.getRowIndex())
                .take(spp.getPageSize())
                .setParameter("search", spp.getSearch())
                .orderBy('order.created','DESC')
                .getMany();
```

**Logs**

```
SELECT DISTINCT `order`.`id` AS `order_id`, `order`.`tip` AS `order_tip`, `order`.`organizationId` AS `order_organizationId`, `order`.`userId` AS `order_userId`, `order`.`discount` AS `order_discount`, `order`.`paymentId` AS `order_paymentId`, `order`.`created` AS `order_created`, `order`.`settled` AS `order_settled`, `user`.`id` AS `user_id`, `user`.`firstName` AS `user_firstName`, `user`.`lastName` AS `user_lastName`, `user`.`email` AS `user_email`, `user`.`phone` AS `user_phone`, `user`.`cognitoId` AS `user_cognitoId`, `user`.`roleId` AS `user_roleId`, `user`.`organizationId` AS `user_organizationId`, `user`.`pinCode` AS `user_pinCode`, `user`.`active` AS `user_active` FROM `order` `order` INNER JOIN `user` `user` ON `user`.`id`=`order`.`userId` WHERE `order`.`id` LIKE  ? OR `user`.`firstName` LIKE ? OR `user`.`lastName` LIKE ? OR `user`.`email` LIKE ? ORDER BY `order`.`created` DESC -- PARAMETERS: ["t","t","t","t"]
```

**Comment by imnotjames** [comment]
You cannot reuse parameter names.  They are all global to the entire querybuilder.

**Comment by imperiale-tech** [comment]
> You cannot reuse parameter names. They are all global to the entire querybuilder.

How should I structure the query builder to do like '%t%' ?

**Comment by imnotjames** [comment]
The parameter names are the issue

```
   .where('order.id LIKE  :searchOrder', { searchOrder:  `%${spp.getSearch()}%` })
                .orWhere('user.firstName LIKE :searchFirst', { searchFirst: `%${spp.getSearch()}%` })
        
```

Change the name - because at the bottom you did `setParameter` and made it just `"t"`

**Comment by imperiale-tech** [comment]
OMG, been coding for too long. Last question by setting the parameter { searchFirst: `%${spp.getSearch()}%` } , would typeorm escape any illegal characters from spp.getSearch() ?

**Comment by imnotjames** [comment]
TypeORM sends the data separately - so you can't get SQL injection.  However, it does not escape the wildcard sequences.

Glad to be if help, and glad this isn't a bug.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
