### ISSUE TITLE
Unused vars

### ISSUE THREAD

**Issue by wkrueger** [typeorm/typeorm#694]
I just pasted the src folder inside another test project (thats plain wrong, of course) and got a dozen of unused vars errors. From a quick look, it seems there's no unused var check neither on tsconfig.json nor on tslint. Isn't a good idea to enable that? IMHO it catches lots of errors.

**Comment by pleerock** [comment]
Yeah we can do that. Feel free to send PR. But this time checkout full repo code please.

**Comment by pleerock** [comment]
I added `noUnusedLocals` option to ts config. I think thats enough for now. Feel free to add other suggestions as well.
