### ISSUE TITLE
postgres: Inappropiate migration generated for 'default: null'

### ISSUE THREAD

**Issue by brahn** [typeorm/typeorm#6950]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.28`

**Steps to reproduce or a small repository showing the problem:**

This issue appears very similar to https://github.com/typeorm/typeorm/issues/5509 but for postgres.

Minimal entity declaration:
```ts
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class Foo {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  requiredString: string;

  @Column({ type: "text", nullable: true })
  optionalString: string | null;

  @Column({ type: "text", nullable: true, default: null })
  optionalStringWithExplicitDefault: string | null;
}

```

Even after syncing the schema, generating a migration still results in the lines

```ts
// from `up` method
await queryRunner.query(`ALTER TABLE "foo" ALTER COLUMN "optionalstringwithexplicitdefault" SET DEFAULT null`);

// in `down` method
await queryRunner.query(`ALTER TABLE "foo" ALTER COLUMN "optionalstringwithexplicitdefault" DROP DEFAULT`);
```

Expected behavior: the migration should not include these lines.

**Comment by vegerot** [comment]
@brahn I have the same issue.  Looking at https://github.com/typeorm/typeorm/issues/150#issuecomment-272158658 , it appears as a temporary workaround we can do 

```TS
@Column({ type: "text", nullable: true, default: () => "NULL" })
```

Let me know if this works for you

**Comment by brahn** [comment]
@vegerot that doesn't seem to have changed anything for me -- thanks for the suggestion, though!

**Comment by vegerot** [comment]
Sorry to hear that.  Me neither.  Hopefully we can get a response from a maintainer soon

**Comment by IAL32** [comment]
Having the same weird behavior, same TypeORM setup and version

**Comment by vegerot** [comment]
To be more specific, when you generate multiple new migrations, each time the case of `null` gets flipped.

For example, at first it will say

```SQL
query: ALTER TABLE "air_refuels" ALTER COLUMN "missionId" SET DEFAULT null
```

then after I run that migration, and gen a new one, the next migration will say

```SQL
query: ALTER TABLE "air_refuels" ALTER COLUMN "missionId" SET DEFAULT NULL
```

After you run the next migration, generating yet another migration produces

```SQL
query: ALTER TABLE "air_refuels" ALTER COLUMN "missionId" SET DEFAULT null
```

I don't think @brahn noticed this when writing the issue.

This certainly seems like a TypeORM bug.  Please let me know what I can do to help resolve it
