### ISSUE TITLE
Extending an entity class does not use postgres inherit feature

### ISSUE THREAD

**Issue by VanWeapon** [typeorm/typeorm#6953]
**Issue type:**

[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Postgresql has a feature called inherited tables, where you can use the following SQL syntax to mark tables as a parent/child relationship, where the child table will inherit all fields of the parent
```sql
CREATE TABLE hardware (name, serial_number);
CREATE TABLE computer (operating_system)
INHERITS (hardware);
```
The result, as per psql docs is below: 
> The optional INHERITS clause specifies a list of tables from which the new table automatically inherits all columns. Parent tables can be plain tables or foreign tables.
> Use of INHERITS creates a persistent relationship between the new child table and its parent table(s). Schema modifications to the parent(s) normally propagate to children as well, **and by default the data of the child table is included in scans of the parent(s).**

I would expect that when extending a class in an Entity, that the above functionality is used, or can at least be toggled with some setting. However instead, the result is that the table columns on child tables are brute-forced into the migration queries. 

```typescript
@Entity('hardware')
export class Hardware {
  @Column() name: string;
  @Column() serial_number: string;
}

@Entity('computer')
export class Computer extends Hardware {
  @Column() operating_system: string;
}
```
If you use the above code to create the entities, you will not be able to select Computer records when querying the Hardware table, however, if INHERITS is used, then you would be able to select Computer records from the Hardware table.

**Comment by imnotjames** [comment]
We don't support this feature on Postgres & currently are trying to limit the amount of functionality that exists for just one specific driver.  Is this feature supported across multiple databases?

**Comment by VanWeapon** [comment]
As far as I can tell postgres is the only one with this feature out of the box, but it is a pretty powerful one and needed for my use case.

One-to-one isn't the same, because that will result in a duplication of records with different unique identifiers, and quickly becomes unmanageable after several layers of inheritance (eg hardware > server > Linux server > centos server)

**Comment by VanWeapon** [comment]
Just another note, the only thing that needs to be done to add this feature, is to add an extra "ALTER TABLE" query as part of migrations when this needs to happen
For the above example, a migration needs an extra SQL statement at the end: 
```sql
ALTER TABLE computer inhertis hardware;
```
Per the postgres docs you can call 'alter table ... inherits' on an existing table so long as the child table already has the fields of the parent. Since typeorm migrations are doing this now, you can just add the alter table line at the very end of the migration queryRunner.
I've tested this by writing the migrations manually and then inserting/getting records after the database has been updated, postgres handles subsequent queries as expected, the typeorm entity/repository manager code should not need to change to suit the new table structure.

**Comment by VanWeapon** [comment]
Upon further testing, the Foreign Key constraint on inherited tables in a blocking limitation on Postgres side not Typeorm side. 
I will revert to using Single Table Inheritance instead of Concrete Inheritance as a workaround

**Comment by khialb32** [comment]
I think you can add foreign key constraint on the inherited tables separately.
Another thing you would try is to use single table inheritance on the orm level, but alter the migrations to use postgres inheritance power.
I still think that single table inheritance with table partioning and costume constraints based on the type is a good option.
