### ISSUE TITLE
pass properties via object in constructor

### ISSUE THREAD

**Issue by MartinMuzatko** [typeorm/typeorm#6961]
**Issue type:**

[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest` (0.2.28)
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi!

I would like to be able to construct an instance of an entity by passing plain objects as first argument.
**Example:**

``` ts
@Entity()
export class User {

    constructor(attrs?: User) {
        attrs && Object.assign(this, attrs)
    }
    // ...columns
}

```

later when creating the user:

``` ts
const user = new User({
    firstName: 'Test',
})
```

this would align with real world use cases, where I just want to pass a json body from a rest api request to the database, without manually setting all properties.

![image](https://user-images.githubusercontent.com/2950505/96892249-c0a44c00-1489-11eb-9498-37f0e0b00920.png)

but this immediately leads to a few downsides.

1. I would need to define all columns as optional that are also nullable
2. I would need to define an interface for both the required properties when instantiating and for retrieving existing ones, because while an autogenerated `id` column is not required to be set in the constructor, it will always be there when retrieving the model. 

Thanks for your input!

**Comment by imnotjames** [comment]
This is more a typescript problem than a TypeORM issue.  Perhaps something like `constructor(attrs?: Partial<User>)` for the typing?

For 1, maybe setting the default as null?
For 2, maybe `Partial<User>`?

For questions and other general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by MartinMuzatko** [comment]
So.. Did I understand correctly that there is no wish from the TypeOrm team to integrate this as a feature?

**Comment by chevsunpower** [comment]
There's no need to integrate this. TypeORM merely annotates your entity classes. It doesn't have an opinion about how you instantiate your entities. The `Partial<Entity>` solution worked great for us.

**Comment by renansilva15** [comment]
What about this approach:
```ts
export interface RestaurantEntityProps extends DefaultEntityProps {
  name: string;
  slug: string;
  distanceLimit: string;
  imageUrl: string;
  isOpen?: boolean;
}

@Entity({ name: 'restaurants' })
export class RestaurantEntity extends DefaultEntity {
  @Column({ name: 'nm' })
  private _name: string;

  @Column({ name: 'slug' })
  private _slug: string;

  @Column({ name: 'distance_limit' })
  private _distanceLimit: string;

  @Column({ name: 'image_url' })
  private _imageUrl: string;

  @Column({ name: 'is_open' })
  private _isOpen: boolean;

  constructor(props: RestaurantEntityProps) {
    super({
      id: props?.id,
      createdAt: props?.createdAt,
      updatedAt: props?.updatedAt,
    });
    this._name = props?.name;
    this._slug = props?.slug;
    this._distanceLimit = props?.distanceLimit;
    this._imageUrl = props?.imageUrl;
    this._isOpen = props?.isOpen ?? false;
  }

  public get name(): string {
    return this._name;
  }

  public get slug(): string {
    return this._slug;
  }

  public get distanceLimit(): string {
    return this._distanceLimit;
  }

  public get imageUrl(): string {
    return this._imageUrl;
  }

  public get isOpen(): boolean {
    return this._isOpen;
  }
}

```
I needed to use props with `?` operator. I really don't know what are the problems that might come using this.
