### ISSUE TITLE
getRepository cannot use NOW() on timestamp field, but timestamptz works

### ISSUE THREAD

**Issue by chorsnell** [typeorm/typeorm#6962]
**Issue type:** Bug

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25`

**Steps to reproduce or a small repository showing the problem:**

```
@Entity("reservations")
export class Reservation {
  @PrimaryGeneratedColumn()
  @Property()
  id: number;

  @Column({ type: "timestamp", nullable: true })
  @Property()
  checkinAt: string;

  @Column({ type: "timestamptz", nullable: true })
  @Property()
  checkinAt2: string;
}
```

I am trying to update the `checkinAt` field. Note: this is NOT a `UpdateDateColumn` field, as I want this to only update at a specific point in the process. There are other fields too (not in this repro) that get updated as well.

I was updating this via:
```
this.connection.getRepository(Reservation).update({ id: reservationId }, { checkinAt: "now()" });
```
...which worked fine until I refactored the field from `timestamptz` to `timestamp`.

Now with query logging turned on, the `now()` gets turned to null, which causes the following https://github.com/typeorm/typeorm/issues/1015
```
log -- UPDATE "reservations" SET "checkinAt" = $2, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = $1 -- PARAMETERS: [2508,null]
error: invalid input syntax for type timestamp: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN"
```

If I run the raw query directly its fine
```
UPDATE "reservations" SET "checkinAt" = NOW(), "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 2508
```

Typeorm seems to be thinking its an invalid value and stripping it from the query.

Why would the lack of time zone on this field cause this issue? Anything I put in there, eg `CURRENT_TIMESTAMP` etc causes the same issue.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by chorsnell** [comment]
In case anyone else runs into this it works if I do
```
this.connection.getRepository(Reservation).update({ id: reservationId }, { checkinAt: () => "now()" });
```
or via querybuilder
```
this.connection
      .createQueryBuilder()
      .update(Reservation)
      .set({ checkinAt: () => "now()" })
      .where("id = :id", { id: reservationId })
      .execute();
```

The difference being using `{ checkinAt: () => "now()" }` instead of ` { checkinAt: "now()" }`

Still not entirely sure why its effected by time zones though 😕

**Comment by bocajji** [comment]
@chorsnell Thank you. You saved me a lot of hair pulling. This work around helped me also.

**Comment by nebkat** [comment]
`() => "NOW()"` is for inserting raw SQL. If you do use a string it will be inserted as a string. Just be careful to properly escape the input if you are using this method with external inputs.
