### ISSUE TITLE
Raw query with json columns (Postgres)

### ISSUE THREAD

**Issue by brunosiqueira** [typeorm/typeorm#698]
Folks, I am trying to build a query like this

  ```
  let query = `SELECT "incident".* FROM "incident" "incident"  
     WHERE incidents::jsonb @> '[{"name":$1}]' ORDER BY "incident"."id" ASC`;

    const results: any = await repository.query(query, ['Briga']);
```
I want to add the value of the json as a parameter, but I am getting an error

`error during executing query:error: invalid input syntax for type json
`

The final query I want is this one:
```
SELECT "incident".* 
FROM "incident" "incident" WHERE incidents::jsonb @> '[{"name":"briga"}]' 
ORDER BY "incident"."id" ASC
```

I searched in the documentation how to parametrize queries with json fields but could not find anything. Could you help me?

**Comment by pleerock** [comment]
`repository.query` calls underlying `pg` package's query method and uses its parameters syntax. Refer to `pg` package how to resolve your problem. But in my opinion you should do: 
`incidents::jsonb @> $1` and set to parameter the whole json.

**Comment by brunosiqueira** [comment]
@pleerock the problem is that, when the parameter is applied to the query, the double quotes are escaped. Eg: "[{\"name\":\"Briga\"}]"].
This invalidates the parameter comparison and I receive no results from the query. I am looking if there is a way to force the parameter to be wrapped with single quotes and skip double quote escaping.

**Comment by brunosiqueira** [comment]
Perfect, @pleerock! It worked!

**Comment by iamdeit** [comment]
@pleerock @brunosiqueira This saved me! It was hard to find an example similar to this one. Thank you.
