### ISSUE TITLE
sqlite bulk insert is slow

### ISSUE THREAD

**Issue by nooblyf** [typeorm/typeorm#6984]
### What was unclear or otherwise insufficient?

So, I'm trying to insert 100 million rows in my sqlite database file and I saw it in the [transactions](https://typeorm.io/#/transactions/using-queryrunner-to-create-and-control-state-of-single-database-connection) page that to insert that amount of data you need to use QueryRunner to create a transaction.

What I did was that I started a transaction and then started a `for` loop and logged every value of i so that I can see it's speed and I saw that I was getting ~1 million rows inserted in about 30 mins but that would take ~50 hours to do 100 million rows.

I saw in sqlite docs [here](https://www.sqlite.org/faq.html#q19) that it can easily do 50,000 or more INSERT statements per second on an average desktop computer.

Am I missing something?
Is it because of Node.js? or  Is there any other way to do bulk insert?

[EDIT]: After inserting 5 million rows I'm now getting 300 inserts per second.

### Recommended Fix

I don't know

### Additional Context

Here is my code:

I'm doing many to many bulk insert where I select random trackId and playlistId and create a relationship between them.
```ts
import { getConnection, getRepository } from "typeorm"
import { Playlist } from "../entity/Playlist"
import { Track } from "../entity/Track"
import { selectRandomNumber as selectRandomId } from "./arrayMethods"

const playlistRepo = getRepository(Playlist)
const trackRepo = getRepository(Track)
const allPlaylists = await playlistRepo.find()
const allTracks = await trackRepo.find()

const playlistIdArray: number[] = allPlaylists.map(p => p.playlistId)
const trackIdArray: number[] = allTracks.map(t => t.trackId)

const connection = getConnection()
const queryRunner = connection.createQueryRunner()

try {
  await queryRunner.startTransaction()

  for (let i = 1; i <= 100_000_000; i++) {
    const randomPlaylistId = selectRandomId(playlistIdArray)
    const randomTrackId = selectRandomId(trackIdArray)

    const randomPlaylist = await playlistRepo.findOne({
      where: { playlistId: randomPlaylistId },
      relations: ["tracks"],
    })
    const randomTrack = await trackRepo.findOne({ where: { trackId: randomTrackId } })
    randomPlaylist.tracks.push(randomTrack)

    await queryRunner.manager.save(randomPlaylist)

    console.log(i, "relation(s) created")
  }
} catch (error) {
  // rollback changes on error
  await queryRunner.rollbackTransaction()
} finally {
  await queryRunner.commitTransaction()

  // release the manually created query runner
  await queryRunner.release()
}
```

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [x] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by kgajowy** [comment]
@nooblyf what was the reason?

**Comment by nooblyf** [comment]
@kgajowy  couldn't figure out, i'm guessing using raw sql with a shell script would be way to go if you want to seed large amounts of data

**Comment by kgajowy** [comment]
@nooblyf in general TypeORM is slow in that matter. I usually implement such inserts with `.query` instead with additional chunking (within a single transaction) if there are some parameters to be provided.
