### ISSUE TITLE
"typeorm query -c" returns help instead of running the query

### ISSUE THREAD

**Issue by prokopsimek** [typeorm/typeorm#6987]
## Issue Description

`typeorm query` does not work correctly in version `0.2.28`

### Expected Behavior

typeorm `v0.2.25`

The query is executed on a given connection.

Command:
`yarn ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js query 'DROP DATABASE IF EXISTS dxse_data_consumer_idp_dev' -c IDP`

Expected result: 
```
Running query: DROP DATABASE IF EXISTS dxse_data_consumer_idp_dev
```

### Actual Behavior

typeorm `v0.2.28`

Command:
`yarn ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js query 'DROP DATABASE IF EXISTS dxse_data_consumer_idp_dev' -c IDP`

Current result: 
```
cli.js query

Executes given SQL query on a default connection. Specify connection name to run
query on a specific connection.

Options:
  -h, --help        Show help                                          [boolean]
  -c, --connection  Name of the connection on which to run a query.
                                                            [default: "default"]
  -f, --config      Name of the file with connection configuration.
                                                          [default: "ormconfig"]
  -v, --version     Show version number                                [boolean]

Unknown argument: DROP DATABASE IF EXISTS dxse_data_consumer_idp_dev
```

### Steps to Reproduce

1. I am running typeorm with `ts-node` and via `yarn` to avoid installing `typeorm` globally.
2. Command: `yarn ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js query 'DROP DATABASE IF EXISTS dxse_data_consumer_idp_dev' -c IDP`

I have updated typeorm from `v0.2.25` to `v0.2.28`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.2.0 | 
| Typescript version  | v4.0.2 | 
| TypeORM version     | v0.2.28 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
I'll try to find out in what version the bug occurred. (reverting v to 0.2.26 and version by version to the newest)
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

  👋 Have a great day and thank you for the `typeorm`!

**Comment by prokopsimek** [comment]
- `v0.2.26` ✅
- `v0.2.26` ❌

**Comment by prokopsimek** [comment]
I was looking for a bug in `typeorm` source code and I didn't find out anything that could cause the problem.

There was a huge upgrade of dependencies like [`yargs`](https://github.com/typeorm/typeorm/compare/0.2.26...0.2.27#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R132) or others. 

Can you help me to identify the root cause? Thanks!

**Comment by imnotjames** [comment]
Is this related possibly to #6986 ?

**Comment by imnotjames** [comment]
Is this still a problem with the latest `master` branch?

**Comment by Ginden** [comment]
Closing - no response from issue reporter.
