### ISSUE TITLE
I can't insert related table field

### ISSUE THREAD

**Issue by alanscordoba** [typeorm/typeorm#6992]
- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [X] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

These are my tables:

```
@Entity('personas')
export class Personas {

    @PrimaryGeneratedColumn()
    @IsNumber()
    id: number;

    @Column({type:"varchar",length:100})
    @IsNotEmpty()
    nombre: string;
    
    @OneToMany(type => Contactos, contactos => contactos.idpersona, {cascade: true})
    contactos : Contactos[] 
}
@Entity('contactos')
export class Contactos {

  @PrimaryGeneratedColumn()
  @IsNumber()
  id: number;

  @Column()
  @IsNotEmpty()
  idpersona: number;
  @ManyToOne(type => Personas, {
  })
  @JoinColumn({name: "idpersona"})
  persona: string;

  @Column({type:"varchar",length:100})
  nombre: string;

  @Column({type:"varchar",length:11})
  telefono: string;
   
}
```

This is the body of the query to add the records:

```
{
    "nombre":"TestPersona",
    "contactos":[{      
                "nombre":"TestContacto",
                "telefono": "123456789"}
                ]
}
```

This is the error: [ExceptionsHandler] Field 'idpersona' doesn't have a default value.

It is assumed that the field idPersona in Contacts, should be inserted automatically. What am I doing wrong?. From already thank you very much.`

**Comment by alanscordoba** [comment]
Could you solve it? I have a similar problem but using Mysql.

**Comment by imnotjames** [comment]
That error message isn't coming from anything within TypeORM that I can find.  I don't think your issue is with TypeORM.  If you can replicate this with just TypeORM and not the web framework you're operating with please re-openm this issue.
