### ISSUE TITLE
migration:run should create table "migrations" if one does not exist

### ISSUE THREAD

**Issue by hirikarate** [typeorm/typeorm#6994]
### The Problem

When a new developer pulls the codebase and wants to deploy a local database instance, the steps are:

1. `typeorm schema:sync` to create table schemas
2. `typeorm migration:run` to apply migrations

But step (2) fails with error:
```
query failed: INSERT INTO "migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1604140311975,"FreshSeeds1604140311975"]
error: error: relation "migrations" does not exist
```

### The Solution

`migration:run` should create table "migrations" if one does not exist

### Additional Context

typeorm: 0.2.28
pg: 8.3.3 (Postgresql driver)

**Comment by hirikarate** [comment]
I found that the error comes from another reason. Closing this issue!
Thank you!

**Comment by aburkut** [comment]
Hey @hirikarate. What was the reason? I faced the same issue.
