### ISSUE TITLE
Cascade deleting works incorrect

### ISSUE THREAD

**Issue by 19majkel94** [typeorm/typeorm#70]
There is a small problem with cascade deleting.

I have an entity `Chart` with one to many relation:
```typescript
@OneToMany(_type => ChartRow, row => row.chart, { cascadeAll: true })
public rows: ChartRow[]
```
The problem is when I try to remove this entity, I got constraint fails because the related entity are deleted after the main entity:
```
executing query: START TRANSACTION                                                                                                                                                         
executing query: DELETE FROM chart WHERE id=? -- PARAMETERS: [6]                                                                                                                           
executing query: DELETE FROM chart_row WHERE id=? -- PARAMETERS: [8]                                                                                                                       
executing query: DELETE FROM chart_row WHERE id=? -- PARAMETERS: [9]                                                                                                                       
executing query: DELETE FROM chart_row WHERE id=? -- PARAMETERS: [10]                                                                                                                      
query failed: DELETE FROM chart WHERE id=? -- PARAMETERS: [6]                                                                                                                              
error during executing query:Error: ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`typeorm`.`chart_row`, CONSTRAINT `fk_79c9460c3e56c4b2119
675883d8` FOREIGN KEY (`chart`) REFERENCES `chart` (`id`))                                                                                                                                 
executing query: ROLLBACK                                        
```
So I tried to do cascade delete by database and added `onDelete: "CASCADE"`:
```typescript
@OneToMany(_type => ChartRow, row => row.chart, { cascadeAll: true, onDelete: "CASCADE" })
```
But the schema sync didn't create the DDL alter table - it still have `ON DELETE RESTRICT` which don't let me to delete this entity with the same error.

I can do the workaround and delete it manually:
```typescript
await Promise.all(chart.rows.map(row => this.chartRowRepository.remove(row)));
```
But it's not a point of using a relation db and ORM 😉

**Comment by pleerock** [comment]
> But the schema sync didn't create the DDL alter table - it still have ON DELETE RESTRICT which don't let me to delete this entity with the same error.

its a bug right now, it sets it only during creation, I need to fix it.

> cascade remove is not working

grhhh yeah this should be fixed after I refactor persistance mechanism. Im doing it right now on a separate branch, pretty complicated task

**Comment by 19majkel94** [comment]
Oh ok, I will do the workaround for now until you fix it.

The same problem is when updating one to many relation - if I have array of x objects in my relation property `chart.rows` and I replace them with new ones (`chart.rows = [row1, row2, row3]`), the ORM doesn't delete old ones but only add new ones.

**Comment by pleerock** [comment]
I noticed one thing:

```typescript
@OneToMany(_type => ChartRow, row => row.chart, { cascadeAll: true, onDelete: "CASCADE" })
```
`onDelete: "CASCADE"` should be set on inverse side, .e.g. on `@ManyToOne` side.

I havent tested this on master brach, but I did it my own branch and it works. My own branch contains changes for the next version of typeorm.

**Comment by 19majkel94** [comment]
I changed it to:
```typescript
class ChartRow {
    @ManyToOne(_type => Chart, chart => chart.rows, { nullable: false , onDelete: "CASCADE"})
    public chart: Chart;
}
```
But the migration didn't altered the fk and it's still `ONDELETE: Restrict`. I'm using the `0.0.2-alpha.70` version so maybe your new persistence mechanism works better :wink:

**Comment by pleerock** [comment]
`But the migration didn't altered the fk and it's still ONDELETE: Restrict`

There still a bug I need to fix - ONDELETE works only when first time schema is build, on schema updates it does not work - something I need to fix

**Comment by stonecold123** [comment]
It doesn't work on first time either, at lease in my case. I tried deleting the tables and rebuilding the schema with `{ cascadeAll: true, onDelete: "CASCADE" }` on `ManyToOne` side, but it's still  `ONDELETE: Restrict`.

**Comment by pleerock** [comment]
@stonecold123 please open a new issue with description and your examples
