### ISSUE TITLE
Export error types for checks on the outside

### ISSUE THREAD

**Issue by Agreon** [typeorm/typeorm#7000]
### The Problem

We use NestJS with the TypeOrm integration and try to catch TypeOrm errors with a NestJs-Filter. Unfortunatley only the `QueryFailedError` is exported from the TypeOrm-Library. This stops us from being able to check something like `error instanceOf EntityNotFoundError`. Worse, we cannot specify this error as part of the `Catch` clause from NestJS.

### The Solution

Export all errrors. 

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Definitely! This could be related to #3479 as well - to simplify catching TypeORM errors

**Comment by Agreon** [comment]
@imnotjames PR is ready ;)

**Comment by pirtleshell** [comment]
I'm just going to toss this here in case anyone else ends up here before that PR is merged.

even though they aren't available from the main package, you are able to import typeorm's specific error types directly from `typeorm/error`:
```ts
import { EntityNotFoundError } from 'typeorm/error/EntityNotFoundError';
```
