### ISSUE TITLE
Apache Ignite Support

### ISSUE THREAD

**Issue by nichenqin-treelab** [typeorm/typeorm#7003]
Here is the apache ignite docs: https://ignite.apache.org/docs/latest/

I have created a fork and implemented the main feature of driver and query runner

Hoping for more discuss! 😀

**Comment by anuj-kosambi** [comment]
Hi, 
Instead of implementing specific drive of Apache Ignite 
Can't we support odbc drive implementation which can support wide range of databases 

https://ignite.apache.org/docs/latest/SQL/ODBC/odbc-driver
https://github.com/markdirish/node-odbc

**Comment by jmls** [comment]
any movement on this - really need a odbc driver for a number of datasources

**Comment by emmalouiselane** [comment]
Its a good question - ODBC support would make a number of things easier - is this on the roadmap?

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
