### ISSUE TITLE
find() and query() don't return the same even when the logged query is the same

### ISSUE THREAD

**Issue by adrianwix** [typeorm/typeorm#7017]
## Issue Description
I have User (Many to Many) Role (Many to One) Tenant relationship. I want to get the role of a user for one tenant (If there is any).
```ts
const roles = await roleRepository
                .createQueryBuilder('role')
                .select('*')
                .leftJoin('role.users', 'users', 'users.id = :userId', {
                    userId: user.id,
                })
                .andWhere('"role"."tenantId" = :tenantId', {
                    tenantId: tenant.id,
                })
                .getMany()
```
Produces the SQL
```sql
SELECT *
FROM "role" "role"
LEFT JOIN "role_users_user" "role_users" ON "role_users"."roleId"="role"."id"
LEFT JOIN "user" "users" ON "users"."id"="role_users"."userId"
AND ("users"."id" = $1)
WHERE "role"."tenantId" = $2 -- PARAMETERS: [275,358]
```

And returns and empty array. But If I execute the same query using the repository.query() method.

```ts
const roles = await roleRepository.query(
                `SELECT *
                FROM "role" "role"
                         LEFT JOIN "role_users_user" "role_users" ON "role_users"."roleId" = "role"."id"
                         LEFT JOIN
                     "user" "users" ON "users"."id" = "role_users"."userId" AND ("users"."id" = $1)
                WHERE "role"."tenantId" = $2`,
                [user.id, tenant.id]
            )
```
I get a valid response
```ts
roles [
      {
        id: 275,
        name: 'AUTH',
        tenantId: 358,
        roleId: 462,
        userId: 275,
        organizationName: 'Tenant',
        firstName: 'John',
        lastName: 'Doe',
        email: 'test@email.com',
        password: 'password1234',
        resetPasswordToken: null,
        confirmed: false,
        subscribed: false,
        privacyPolicy: true,
        termOfUse: true
      }
    ]
```

### Expected Behavior

It should return an array of roles

### Actual Behavior
It's returning an empty array

```
// include the output in code tags like these!
```

### Steps to Reproduce
I will work on getting a way to reproduce this in a small demo. The Uni and Work is killing me right now

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Windows 10      |
| Node.js version     | v12.16.1 | 
| Typescript version  | v4.0.5 | 
| TypeORM version     | v0.2.28| 

### Additional Context

I am using TypeORM with Nestjs

"@nestjs-modules/mailer": "^1.5.1",
"@nestjs/common": "^7.4.4",
"@nestjs/config": "^0.5.0",
"@nestjs/core": "^7.4.4",
"@nestjs/jwt": "^7.1.0",
"@nestjs/passport": "^7.1.0",
"@nestjs/platform-express": "^7.4.4",
"@nestjs/swagger": "^4.6.0",
"@nestjs/typeorm": "^7.1.3",

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by nebkat** [comment]
Have you tried without the `select('*')`, or with `select('role.*')` and/or `select('users.*')`?

**Comment by imnotjames** [comment]
Stale, mostly a support question, probably answered.

Closing.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
