### ISSUE TITLE
Doesn't remove `default` connection when close the connection.

### ISSUE THREAD

**Issue by zhaoyi0113** [typeorm/typeorm#7028]
## Issue Description

I use `const connection = createConnection(param)` method to create a postgresql connection and later I call `connection.close()` to close this connection. 
The next time when I call `const connection = createConnection(param)` I get an error:

```
 [AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.]
```
It seems that when I close the connection it doesn't remove the `default` from connection manager. 
I understand that I can use `connection.connect()` method to reconnect but I need to use a different credential for the connection. The credential is changed every few minutes.

### Expected Behavior

I would expect it removes the default connection when all connections are closed. Otherwise, I can't create a new connection.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v12.16.2 | 
| Typescript version  | v3.9.7 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ x] No, I don't have the time and I wouldn't even know how to start.

**Comment by main-kun** [comment]
Ran into the same problem

**Comment by elovin** [comment]
also happens with mariadb

**Comment by cjnoname** [comment]
any updates on this one?

**Comment by cheerfyt** [comment]
better-sqlite3 driver with same problem

**Comment by imnotjames** [comment]
The connection manager does not remove connections.

If you want to use the `ConnectionManager` - which is what `createConnection` is doing you'll need to get the default connection again and reopen it.

If you want to manage your own connections do not use `createConnection` and instead use the `Connection` object directly.
