### ISSUE TITLE
Missing connection options for MongoDB

### ISSUE THREAD

**Issue by rklos** [typeorm/typeorm#7037]
### What was unclear or otherwise insufficient?

[Documentation](https://github.com/typeorm/typeorm/blame/master/docs/connection-options.md#L365) about MongoDB connection options does not have any info about `username` nor `password` properties that are used by `MongoDriver` for creating connection URL ([MongoDriver.ts#L441](https://github.com/typeorm/typeorm/blob/master/src/driver/mongodb/MongoDriver.ts#L441)). Also, there is no information about cutting off `auth` property from configuration object that is passed through `MongoDriver` module ([MongoDriver.ts#L190](https://github.com/typeorm/typeorm/blob/master/src/driver/mongodb/MongoDriver.ts#L190)).

### Recommended Fix

Add info about `username` and `password` properties.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
It looks like this is a documentation issue - you can start by forking the repository - up near the top right of the github UI, then cloning your fork, making changes to the documentation file using your editor of choice, then opening a pull request against this repository.
