### ISSUE TITLE
Docs translation to brazilian portuguese

### ISSUE THREAD

**Issue by vitorcodesalittle** [typeorm/typeorm#7039]
Are there any efforts of the community to translate documentation to brazilian portuguese?
I'm willing to contribute to on going efforts, or start a PR for this specific translation.
I'd follow the chinese translation scheme, creating a folder with markdown files.

### Are you willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
I suggest a community-driven approach to translations - as we can barely manage to keep up with the Chinese translation of documentation.  If you create a separate repository for BR docs, perhaps we can link to it?

**Comment by vitorcodesalittle** [comment]
For brazilian portuguese,  in browser translation tools are good enough (in my opinion). sorry for ghosting!
