### ISSUE TITLE
Bug: Table alias in WHERE clause is not quoted in PostgreSQL

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#704]
Hey @pleerock! I was migrating to the alpha version of TypeORM, as you've suggested and I've stumbled upon this problem almost immediately with the first query.

Consider this example:

```typescript
const user = await usersRepository.findOne({ email: 'john@example.com' });
```

The call above generates this SQL:

```sql
SELECT "User"."id" AS "User_id" FROM "users" "User" WHERE User.email=$1
```

The problem is with this part: `WHERE User.email=$1`.

Firstly, PostgreSQL requires case-sensitive identifiers to be quoted, secondly, the `USER` is a reserved keyword and is therefore should also be quoted.

So, the correct query should look like this:

```sql
SELECT "User"."id" AS "User_id" FROM "users" "User" WHERE "User".email=$1
```

By the way, can't we just always quote all the identifiers (i.e. table names, column names, aliases, etc)? I think this will prevent such problems in it's roots.

@pleerock is there any workarounds I can use to overcome this problem? I'm afraid my work is stuck, because of this problem, and we are already behind schedule on this project that we work on.

I'm also afraid the codebase of TypeORM is so vast and complex for me to quickly dive into it, so I won't be able to help with coding right away (but I will try to get familiar with it).

Thank you!

**Comment by slavafomin** [comment]
After further investigation, it looks like this workaround works correctly:

```typescript
const user = await usersRepository.findOne({
  where: {
    email: 'john@example.com'
  },
  join: {
    alias: 'entity'
  }
});
```

> However, it looks weird that `alias` property is specified under `join` property, however, I'm not using any joins at all. Maybe we should move it one layer higher (directly to `FindOneOptions`)?

By the way, is it possible to specify default alias used in query on a per-entity basis? Maybe through some decorator?

I can see that TypeORM fetches alias this way: `FindOptionsUtils.extractFindOneOptionsAlias(optionsOrConditions) || metadata.name`, but I'm not sure how it gets to the `metadata.name`. Is it just the name of the class? Can I override it somehow?

Is it possible to use naming strategy for this purpose?

Thanks!

**Comment by pleerock** [comment]
are you sure you have "email" column in user Entity? Can you please show me your user entity? I just wrote test that makes same what you did and it escapes user keyword properly:

```sql
SELECT "User"."id" AS "User_id", "User"."email" AS "User_email" FROM "user" "User" WHERE "User"."email"=$1 -- PARAMETERS: ["john@example.com"]
```

**Comment by slavafomin** [comment]
Yes, there is a chance that `email` column was commented out (I'm in the middle of refactoring). But nevertheless, the error is misleading. Maybe we should throw an error if user tries to use undefined column in query conditions? Also, it looks unexpected, that defined column is properly escaped and undefined is not. Maybe we should escape all fields, regardless of their definition state? I think this edge case should be taken into consideration, because it's very easy to forget to define a column. It would be great if TypeORM would point it out early on (fail fast).

**Comment by pleerock** [comment]
> it's very easy to forget to define a column

no defined column - no work with it. Its the same if you forget to define your entity or simply forget to run your app. Its required to defined it if you want to use it in orm.

escaping is not a trivial thing - it already works very very very magically, in a bad meaning TBH. But there is no choice. I don't think we can (and should) escape columns with what database stores, because there is no such information (database column names) stored anywhere except for defined columns (via @Column decorator).

**Comment by slavafomin** [comment]
Shouldn't we prevent user from shooting himself in the leg? Or at least notify him about it?

I think why Angular 2 is great is because it has a very meaningful error messages with explanations for common pitfalls. This is a good developer experience and it helps with adoption.

**Comment by pleerock** [comment]
yeah we need better error reporting for sure, probably good if we create a list of errors we should provide users and when
