### ISSUE TITLE
Feat: Mark migrations as marked

### ISSUE THREAD

**Issue by rubiin** [typeorm/typeorm#7045]
### The Problem

One of the missing features I noticed was the feature to mark certain migrations as executed.
Mikro-orm as well as most popular orms has this feature. I think it can come in handy, when you are working with an existing database.

### The Solution

Its not a solution but more of a workaround but here is what I am doing
```
import { join } from 'path';
import 'reflect-metadata';
import { createConnection, MigrationExecutor } from 'typeorm';
import config from './config';

createConnection({
	type: 'postgres',
	host: config.db.host,
	port: config.db.port,
	username: config.db.username,
	password: config.db.password,
	database: config.db.database,
	entities: [join(__dirname, 'entities/*{.ts,.js}')],
	logging: 'all',
	migrationsTableName: 'nest_migration',
	logger: 'advanced-console',
	migrations: [join(__dirname, 'migrations/**/*{.ts,.js}')],
	cli: {
		migrationsDir: join('src', 'migrations'),
	},
})
	.then(async connection => {
		const mig = new MigrationExecutor(connection);

		await connection.manager.query(
			' CREATE TABLE IF NOT EXISTS "nest_migration" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL, "name" varchar NOT NULL, CONSTRAINT "PK_d8a054ea06850edd968e06c00e4" PRIMARY KEY ("id"))',
		);
		const migrations = await mig.getAllMigrations();

		console.warn(migrations);

		for (const migration of migrations) {
			//	await mig.insertMigration(migration);

			// eslint-disable-next-line no-await-in-loop
			await connection.manager.query(
				' INSERT INTO "nest_migration"("timestamp", "name") VALUES ($1, $2) ',
				[migration.timestamp, migration.name],
			);
		}
	})
	.catch(error => console.warn(error));

```

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nebkat** [comment]
This already appears to exist? https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/migration/MigrationExecutor.ts#L339

**Comment by rubiin** [comment]
> createMigrationsTableIfNotExist

Suppose I have an existing database and I created an  initial migration. Now this migration does not need to be ran as the database tables are already there, but we need to mark this as ran. This scenerio is not covered. It a well known feature of orms like django orm and mikro-orm also supports this from recent version

**Comment by rubiin** [comment]
For now i have this workaround,

```
import { join } from 'path';
import 'reflect-metadata';
import { createConnection, MigrationExecutor } from 'typeorm';
import config from './config';

createConnection({
	type: 'postgres',
	host: config.db.host,
	port: config.db.port,
	username: config.db.username,
	password: config.db.password,
	database: config.db.database,
	entities: [join(__dirname, 'entities/*{.ts,.js}')],
	logging: 'all',
	migrationsTableName: 'nest_migration',
	logger: 'advanced-console',
	migrations: [join(__dirname, 'migrations/**/*{.ts,.js}')],
	cli: {
		migrationsDir: join('src', 'migrations'),
	},
})
	.then(async connection => {
		const mig = new MigrationExecutor(connection);

		await connection.manager.query(
			` CREATE TABLE IF NOT EXISTS "nest_migration" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_d8a054ea06850edd968e06c00e4" PRIMARY KEY ("id"))`,
		);
		const migrations = await mig.getAllMigrations();

		console.warn(migrations);
		/* eslint-disable no-await-in-loop */
		for (const migration of migrations) {
			//	await mig.insertMigration(migration);

			await connection.manager.query(
				` INSERT INTO "nest_migration"("timestamp", "name") VALUES ($1, $2) `,
				[migration.timestamp, migration.name],
			);
		}
	})
	.catch(error => console.warn(error));



```

**Comment by wodka** [comment]
another case would be after executing schema:sync to also mark all migrations as being run.
