### ISSUE TITLE
createConnection close api without throw error.

### ISSUE THREAD

**Issue by lucaslacerdacl** [typeorm/typeorm#7048]
### Expected Behavior

create a connection with postgres database.

### Actual Behavior

Without make any change in database connection, the api, suddenly, exit and the code pass through the createConnection method.

### Steps to Reproduce

```typescript
require('dotenv').config();

import 'reflect-metadata';

import * as Server from './server';
import * as entities from './database';

import { Connection, createConnection } from 'typeorm';
import { DataConfig, getConfigs } from './configurations';

console.log(`Running enviroment ${process.env.NODE_ENV}`);

const initDatabase = async (dataConfig: DataConfig): Promise<Connection> => {
  try {
    const connection = await createConnection({
      type: 'postgres',
      host: dataConfig.host,
      port: dataConfig.port,
      username: dataConfig.username,
      password: dataConfig.password,
      database: dataConfig.database,
      entities: Object.keys(entities).map(key => entities[key]),
      logging: false,
    });

    return connection;
  } catch (err) {
    console.error('Error connection database: ', err.message);
    throw err;
  }
};

const start = async () => {
  try {
    const configs = getConfigs();
    console.log('Get configs successfully.');

    await initDatabase(configs.dataConfig);
    console.log('Database connected successfully.');

    const server = await Server.init(configs);
    await server.start();
    console.log('Server running at:', server.info.uri);
  } catch (err) {
    console.error('(1) Error starting server: ', err.message);
    throw err;
  }
};

start()
  .then(() => {
    console.log('Ready to receive requests!');
  })
  .catch(err => {
    console.error('(2) Error starting server: ', err);
    process.exit(1);
  });

```

### My Environment

"dependencies": {
    "pg": "^7.18.2",
    "typeorm": "^0.3.0-alpha.24",
    "node": "13.10.1",
  },
  "devDependencies": {
    "@types/dotenv": "^8.2.0",
    "@types/node": "^13.9.0",
    "@types/pg": "^7.14.4",
    "typescript": "^3.8.3",
  }

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by WoH** [comment]
Seems to be related to a specific (range) of pg / pg-connection-string. I was able to upgrade pg and that seemingly resolved the issue.

**Comment by arnold-j-rimmer** [comment]
I had the same problem with typeorm and postgres. The culprit was "pg" package (v7.12.1), issue solved by updating to v8.x (8.3.3 in my case).

**Comment by rtang03** [comment]
I have same problem recently. And, upgrade to "pg": "8.3.3", "typeorm": "0.2.25", works for me.

**Comment by lucaslacerdacl** [comment]
In some cases you will need to reinstall the pg dependency.

For `yarn`, After run the follow command it works just fine:
```shell
yarn remove pg; yarn add pg;
```

**Comment by alexisvisco** [comment]
Same problem but nothing works for me, however it appear only in a containerized environment

**Comment by adavis26** [comment]
Can confirm this was an issue with typeorm v0.2.25 and pg v7, upgraded to pg 8 and worked. 

run `npm i pg@^8`

**Comment by minjayoung88** [comment]
> 이것이 typeorm v0.2.25 및 pg v7의 문제였으며 pg 8로 업그레이드되어 작동했음을 확인할 수 있습니다.
> 
> 운영`npm i pg@^8`

thank you very much

**Comment by rmcwilliam** [comment]
Thanks!
