### ISSUE TITLE
Add change log to new releases

### ISSUE THREAD

**Issue by gfborges** [typeorm/typeorm#7049]
### What was unclear or otherwise insufficient?

I was exploring the issue and realized that the version i am using at work (0.24)   is the latest and really would like to know the new features / bug fixes of the newer versions

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

Hey, and really would like strart contributing to the project, do you recommend any issue or diretory to start 
 reading ?

**Comment by michaelbromley** [comment]
> really would like to know the new features / bug fixes of the newer versions

The Changelog lists all new features & fixes in each version: https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md

> Hey, and really would like strart contributing to the project, do you recommend any issue or diretory to start
reading ?

There is a detailed guide here: https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md

**Comment by imnotjames** [comment]
Looks like that was more or less answered so I'll be closing the issue!
