### ISSUE TITLE
Specifying environment-specific options in ormconfig.json

### ISSUE THREAD

**Issue by BrainMaestro** [typeorm/typeorm#705]
The docs say it should be possible to have multiple connection options that differ by environment. The correct option would be used based on the value of `process.env.NODE_ENV`. However, it does not work this way for me. The first `default` connection is always selected regardless of the environment type. I inspected the [code that retrieves connection options](https://github.com/typeorm/typeorm/blob/master/src/connection/ConnectionOptionsReader.ts#L46-L53) if none are passed into the `createConnection` function, and there doesn't seem to be any reference to env values there. Am I missing something? 

Thanks.

**Comment by pleerock** [comment]
the doc is outdated unfortunately. Its not supported anymore. Reason - people usually don't do what this functionality supposed to do (storing both dev and prod configuration in one file)

**Comment by BrainMaestro** [comment]
Okay thanks

**Comment by ramden** [comment]
So there is no possiblity anymore to have seperate environments for ormconfig.json? How to do it then?

**Comment by pleerock** [comment]
replace file manually for production, or use env variables.
