### ISSUE TITLE
Typeorm creates the database, Nullable is set to true and false, and all the tables created are NOT NULL

### ISSUE THREAD

**Issue by cxbb666** [typeorm/typeorm#7061]
Typeorm creates the database, Nullable is set to true and false, and all the tables created are NOT NULL

**Comment by nebkat** [comment]
Can you please provide some more information, including a fully working example of the code that causes this to occur?

**Comment by cxbb666** [comment]
Dist removed and re-run. I don't know if this is a bug or something

**Comment by nebkat** [comment]
Is the problem fixed for you? You can close the issue if it is. If not please provide sample code.
