### ISSUE TITLE
Cannot add relations on findTrees method on tree repository

### ISSUE THREAD

**Issue by abbbel2** [typeorm/typeorm#7062]
********* wanted to add something like this *********
const manager = getManager();
let trees: User[] = await manager.getTreeRepository(User).findTrees({relations: ["posts"]});

**Comment by nebkat** [comment]
This is not currently supported, although it wouldn't necessarily be too difficult to add. There might be reasons why this is restricted, perhaps for simplicity. If you would like to add this you can take a look at what happens in `EntityManager.find()` and try replicate it in `TreeRepository.findTrees()`, or more specifically inside `findDescendantsTree()`.

**Comment by abbbel2** [comment]
Thanks @nebkat for the information, i have built a custom repository that satisfies my needs.
