### ISSUE TITLE
ChildEntity type relationship produces unexpected results

### ISSUE THREAD

**Issue by aaronmallen** [typeorm/typeorm#7065]
## Issue Description
Given the following entities:

```typescript
@Entity()
@TableInheritance({ column: { type: 'varchar', name: 'type' } })
class ContactEntity {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  userId: number

  @Column()
  @Index({ unique: true })
  protected value: string
}

@ChildEntity('email')
class EmailEntity extends ContactEntity {
  public get address(): string {
    return this.value
  }

  public set address(value: string) {
    this.value = value
  }

  @ManyToOne(type => UserEntity, user => user.emails)
  user: UserEntity
}


@ChildEntity('phone')
class PhoneEntity extends ContactEntity {
  public get number(): string {
    return this.value
  }

  public set number(value: string) {
    this.value = value
  }

  @ManyToOne(type => UserEntity, user => user.phones)
  user: UserEntity
}

@Entity()
class UserEntity {
  @PrimaryGeneratedColumn()
  id: number

  @OneToMany(type => EmailEntity, email => email.user, { cascade: true, eager: true, onDelete: 'CASCADE' })
  emails: EmailEntity[]

  @OneToMany(type => PhoneEntity, phone => phone.user, { cascade: true, eager: true, onDelete: 'CASCADE'})
  phones: PhoneEntity[]
}

```

unexpected results are returned in the `UserEntity#phones` and `UserEntity#emails` relationships.
  
### Expected Behavior

Given a persisted `UserEntity` with an `id` of `1` and one persisted `PhoneEntity` and one persisted `EmailEntity` I would expect the logic:

```typescript
createConnection(...)
  .then(async connection => {
    let user = await userRepo.findOne(1)
    console.log(user)
  })
  .catch(console.error)
```

to generate query:

```SQL
SELECT 
  "UserEntity"."id" AS "UserEntity_id", 
  "UserEntity_emails"."id" AS "UserEntity_emails_id", 
  "UserEntity_emails"."userId" AS "UserEntity_emails_userId",
  "UserEntity_emails"."value" AS "UserEntity_emails_value", 
  "UserEntity_emails"."type" AS "UserEntity_emails_type",
  "UserEntity_phones"."id" AS "UserEntity_phones_id", 
  "UserEntity_phones"."userId" AS "UserEntity_phones_userId", 
  "UserEntity_phones"."value" AS "UserEntity_phones_value", 
  "UserEntity_phones"."type" AS "UserEntity_phones_type" 
FROM "UserEntity" 
LEFT JOIN "ContactEntity" "UserEntity_emails" 
  ON "UserEntity_emails"."userId"="UserEntity"."id" AND "UserEntity_emails"."type" = "email"
LEFT JOIN "ContactEntity" "UserEntity_phones"
  ON "UserEntity_phones"."userId"="UserEntity"."id" AND "UserEntity_emails"."type" = "phone"
WHERE "UserEntity"."id" IN ($1)
```

and output:

```javascript
{
  id: 1,
  emails: [ 
    { 
      id: 1,
      userId: 1,
      value: 'hello@example.com' 
    } 
  ],
  phones: [
    {
      id: 2,
      userId: 1,
      value: '+1 (123) 456-7890'
    }
  ]
}
```

### Actual Behavior

query:

```SQL
SELECT 
  "UserEntity"."id" AS "UserEntity_id", 
  "UserEntity_emails"."id" AS "UserEntity_emails_id", 
  "UserEntity_emails"."userId" AS "UserEntity_emails_userId",
  "UserEntity_emails"."value" AS "UserEntity_emails_value", 
  "UserEntity_emails"."type" AS "UserEntity_emails_type",
  "UserEntity_phones"."id" AS "UserEntity_phones_id", 
  "UserEntity_phones"."userId" AS "UserEntity_phones_userId", 
  "UserEntity_phones"."value" AS "UserEntity_phones_value", 
  "UserEntity_phones"."type" AS "UserEntity_phones_type" 
FROM "UserEntity" 
LEFT JOIN "ContactEntity" "UserEntity_emails" 
  ON "UserEntity_emails"."userId"="UserEntity"."id"  
LEFT JOIN "ContactEntity" "UserEntity_phones"
  ON "UserEntity_phones"."userId"="UserEntity"."id" 
WHERE "UserEntity"."id" IN ($1)
```

output: 

```javascript
{
  id: 1,
  emails: [ 
    { 
      id: 1,
      userId: 1,
      value: 'hello@example.com' 
    },
    {
      id: 2,
      userId: 1,
      value: '+1 (123) 456-7890'
    } 
  ],
  phones: [
    { 
      id: 1,
      userId: 1,
      value: 'hello@example.com' 
    },
    {
      id: 2,
      userId: 1,
      value: '+1 (123) 456-7890'
    }
  ]
}
```
The entity types are ignored and both `emails` and `phones` are matching objects.

### Steps to Reproduce

1. Follow the entity schema outlined above
2. Query an entity with described data

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v15.2.0 | 
| Typescript version  | v4.0.5 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nebkat** [comment]
Joins don't currently support child entities/discriminator values.

Something similar to

https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/query-builder/QueryBuilder.ts#L674-L681

must be added in

https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/query-builder/SelectQueryBuilder.ts#L1476

**Comment by yohannpoli** [comment]
Already known issue https://github.com/typeorm/typeorm/issues/3181.

How can we help to fix this bug?

**Comment by nebkat** [comment]
I have described the necessary changes above: an additional condition must be added to entity joins in `createJoinExpression()` similar to how it is done for the main entity in the query.
