### ISSUE TITLE
Changing column names in closure table crashes the query

### ISSUE THREAD

**Issue by alexey2baranov** [typeorm/typeorm#7069]
## Changing column names in closure tree breaks the query

if I add this naming strategy to connectionOptions, then produced sql brokes as below. The point hire is that query params are 'DEFAULT', 'DEFAULT' instead of  128, 128 for eg.

```ts
      namingStrategy: new class extends DefaultNamingStrategy {
        columnName(propertyName: string, customName: string, embeddedPrefixes: string[]): string {
          switch (propertyName){
            case 'id_ancestor':
              return 'ancestor'
            case 'id_descendant':
              return 'descendant'
            default:
              return super.columnName(propertyName, customName, embeddedPrefixes);
          }
        }
      }
```

### Expected Behavior

```sql
INSERT INTO "users_closure"("ancestor", "descendant") VALUES ($1, $2) [128, 128]
```

### Actual Behavior

```sql
INSERT INTO "users_closure"("ancestor", "descendant") VALUES (DEFAULT, DEFAULT) []
```

### Steps to Reproduce

1. add naming strategy
2. run getManager.save(user)

or

1. git clone https://github.com/alexey2baranov/kopnik-node
2. git checkout  issue-type-orm-naming-strategy
3. cp default.env .env.test
4. npm test

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v15.0.1 | 
| Typescript version  | ts-node v9.0|
| TypeORM version     |  v0.2.25|

### Additional Context

This issue is related to my prev issue https://github.com/typeorm/typeorm/issues/7068. I'm just trying to run TypeORM over legacy data. To do this I need to rename default column name id_ancesstor to ancesstor and id_descandant to descandant. I use naming strategy for this. Unfortunately after adding naming strategy the sql loses params.

### Relevant Database Driver(s)

- [ x] `postgres`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ x] Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by nebkat** [comment]
Seems like a good idea, you could start by making a copy of this:

https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/metadata-builder/EntityMetadataBuilder.ts#L434

to around here:

https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/metadata-builder/ClosureJunctionEntityMetadataBuilder.ts#L51

**Comment by nebkat** [comment]
This is just a direct result of your previous issue #7068, ancestor/descendant are hardcoded currently so changing column name doesn't help. I propose you close this and focus discussion on other issue.
