### ISSUE TITLE
[Bug] Argument of type '"User"' is not assignable to parameter of type 'TableSchema'

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#707]
Hi, i have a very simple migration, yet TS complains in VSCode and in CLI.

```ts
import {Connection, EntityManager, MigrationInterface, QueryRunner} from 'typeorm';

export class User1501098268249 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<any> {
      await queryRunner.addColumn('User', {
        type: 'string',
        name: 'role',
        isNullable: false,
      });
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
      await queryRunner.dropColumn('User', {
        name: 'role',
      });
    }
}
```
Here's how it looks in VSCode window:
![image](https://user-images.githubusercontent.com/9698639/28641348-85f04dea-7214-11e7-93d5-28c5a9192a59.png)

And here's how it does in CLI:
![image](https://user-images.githubusercontent.com/9698639/28641374-99a5649c-7214-11e7-9941-8a4dc0dd3eb3.png)

**Comment by luchillo17** [comment]
Seems the Type definitions are broken, or am i doing it wrong?

**Comment by luchillo17** [comment]
Had to resort to casting to `any` type, and yet i have issues with the `type` property, anyone has an example with `addColumn`?:
```ts
export class User1501098268249 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<any> {
      await queryRunner.addColumn('user' as any, {
        type: String,
        name: 'role',
        isNullable: false,
      } as any);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
      await queryRunner.dropColumn('user' as any, {
        name: 'role',
      } as any);
    }
}
```

**Comment by pleerock** [comment]
those queryRunner methods are not ready for user-using yet, so I can't guarantee you user-friendly for them yet. It requires you `TableSchema` object which you should create, or better load using other query runner methods.

**Comment by pleerock** [comment]
I'll close this issue because at the moment there is nothing to do here. Once I get to migrations I'll create more simplified api to work with migrations. Currently, you have to figure out query runner methods or use raw sql queries to update your database schema.

**Comment by luchillo17** [comment]
Understood, looking forward to this as well ass auto-generated migrations in Postgres.
