### ISSUE TITLE
How to use SUM() with getMany()

### ISSUE THREAD

**Issue by 007AMAN007** [typeorm/typeorm#7072]
await getConnection()
      .getRepository(Robot_Ads)
      .createQueryBuilder('Robot_Ads')
      .leftJoinAndMapMany(
        'Robot_Ads.robotSessionScraperDatas',
        Robot_Session_Scraper_Data,
        'Robot_Session_Scraper_Data',
        '"Robot_Session_Scraper_Data"."adIDAdID" = "Robot_Ads"."Ad_ID"'
      )
      .leftJoinAndMapOne(
        'Robot_Session_Scraper_Data.robotSession',
        Robot_Session_data,
        'Robot_Session_data',
        '"Robot_Session_data"."id" = "Robot_Session_Scraper_Data"."sessionIDId"'
      )
      .select([
        'Robot_Ads.Ad_ID',
        'Robot_Ads.Ad_Binary',
        'Robot_Session_Scraper_Data.id',
        'Robot_Session_Scraper_Data.Impression',
        'Robot_Session_data.id',
        'Robot_Session_data.Session_Device',
        'Robot_Session_data.Session_Geolocation',
        'SUM(Robot_Session_Scraper_Data.Impression) as summmm'
      ])
      .groupBy("Robot_Ads.Ad_ID")
      .addGroupBy("Robot_Session_Scraper_Data.id")
      .addGroupBy("Robot_Session_data.id")
      .orderBy('Robot_Ads.Ad_ID', 'DESC')
      .getMany();

In this query, it return the data without "summmm".

Entities are like that

import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  OneToOne,
  JoinColumn,
  ManyToOne,
} from "typeorm";
import { Robot_Session_Scraper_Data } from "./Robot_Session_Scraper_Data";

export enum AdTypeEnum {
  IMAGE = "Image",
  VIDEO = "Video",
  GIF = "GIF",
}

@Entity()
export class Robot_Ads {
  @PrimaryGeneratedColumn()
  Ad_ID!: number;
  @Column()
  Ad_creative_source_url!: string;
  @Column({
    type: "enum",
    enum: AdTypeEnum,
  })
  Ad_type_Id!: string;
  @Column()
  Ad_Binary!: string;
  robotSessionScraperDatas!: Robot_Session_Scraper_Data[];
  summmm!:number;
}

import { Entity, PrimaryGeneratedColumn, Column, OneToOne, JoinColumn, PrimaryColumn, ManyToOne } from "typeorm";
import { Robot_Session_data } from "./Robot_Session_data"
import { Robot_Ads } from "./Robot_Ads"
import { Robot_Offers } from "./Robot_Offers"
import { Robot_Ad_Text } from "./Robot_Ad_Text"

export enum ZoneTypeEnum {
  FirstPageHeaderDesktop = "Header ​(First page)_Desktop_928X244",
  FirstPageHeaderMobile = "Header ​(First page)_Mobile_300X100",
  HeaderVideoPageDesktop = "Header (Video page)_Desktop_928X244",
  HeaderVideoPageMobile = "Header (Video page)_Mobile_300X100",
  HeaderCategoryPageDesktop = "Header (category page)_Desktop_928X244",
  HeaderCategoryPageMobile = "Header (category page)_Mobile_300X100",
  HeaderBestPageDesktop = "Header (Best page)_Desktop_928X244",
  HeaderBestPageMobile = "Header (Best page)_Mobile_300X100",
  FooterFirstPageDesktop = "Footer (First page)_Desktop_928X244",
  FooterFirstPageMobile = "Footer (First page)_Mobile_300X100",
  FooterVideoPageDesktop = "Footer (Video page)_Desktop_928X244",
  FooterVideoPageMobile = "Footer (Video page)_Mobile_300X100",
  FooterCategoryPageDesktop = "Footer (category page)_Desktop_928X244",
  FooterCategoryPageMobile = "Footer (category page)_Mobile_300X100",
  FooterBestPageDesktop = "Footer (Best page)_Desktop_928X244",
  FooterBestPageMobile = "Footer (Best page)_Mobile_300X100",
  SideUpperDesktop = "Side (upper)_Desktop_338X235",
  SideUpperMobile = "Side (upper)_Mobile_300X100",
  SideSecondDesktop = "Side (second)_Desktop_338X235",
  SideSecondMobile = "Side (second)_Mobile_300X100",
  NativeFirstPageDesktop = "Native (First page)_Desktop_16X9",
  NativeFirstPageMobile = "Native (First page)_Mobile_16X9",
  NativeVideoPageDesktop = "Native (Video page)_Desktop_16X9",
  NativeVideoPageMobile = "Native (Video page)_Mobile_16X9",
  NativeCategoryPageDesktop = "Native (category page)_Desktop_16X9",
  NativeCategoryPageMobile = "Native (category page)_Mobile_16X9",
  NativeBestPageDesktop = "Native (Best page)_Desktop_16X9",
  NativeBestPageMobile = "Native (Best page)_Mobile_16X9",
  NativeInnerVideoPageMobile = "Native (Video page)_Mobile _300X100"
}

@Entity()
export class Robot_Session_Scraper_Data {
  @PrimaryGeneratedColumn()
  id!: number;
  @ManyToOne(type => Robot_Session_data, { nullable: false })
  @JoinColumn()
  Session_ID!: number;
  @Column({
    type: "enum",
    enum: ZoneTypeEnum
  })
  Zone_ID!: string;
  @ManyToOne(type => Robot_Offers, { nullable: false })
  @JoinColumn()
  offer_id!: number;
  @ManyToOne(type => Robot_Ads, { nullable: false })
  @JoinColumn()
  Ad_ID!: number;
  @ManyToOne(type => Robot_Ad_Text, { nullable: true })
  @JoinColumn()
  Ad_text_ID!: number;
  @Column()
  Impression!: number;
  @Column()
  Category!: string;
  @Column()
  Ad_creative_link_url!: string;
  robotSession!: Robot_Session_data;
}

import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

enum SessionOSEnum {
    WINDOWS = "Windows",
    ANDROID = "Android",
    IOS = "iOS",
    MACOS = "macOS",
    WINDOWSPHONE = "Windows Phone",
    OTHER = "other"
}

export enum SessionDeviceEnum {
    DESKTOP = "desktop",
    MOBILE = "mobile",
    TABLET = "tablet",
    OTHER = "other",
}

@Entity()
export class Robot_Session_data {
    @PrimaryGeneratedColumn()
    id!: number;
    @Column({ type: 'timestamp' })
    Session_start!: Date;
    @Column({ type: 'timestamp', default: null, nullable: true })
    Session_end!: Date;
    @Column()
    user_IP_address!: string;
    @Column()
    User_Agent_Header!: string;
    @Column()
    Accept_Language_Header!: string;
    @Column({
        type: "enum",
        enum: SessionOSEnum
    })
    Session_OS!: string;
    @Column({
        type: "enum",
        enum: SessionDeviceEnum
    })
    Session_Device!: string;
    @Column()
    Session_Browser!: string;
    @Column()
    Session_Geolocation!: string;
    @Column()
    Session_Carrier!: string;
    @Column()
    Session_Browser_language!: string;
}

**Comment by nebkat** [comment]
You should wrap your code blocks in:

```
    ```typescript
    code here
    ```
```

**Comment by 007AMAN007** [comment]
Hi @nebkat 

```await getConnection()
.getRepository(Robot_Ads)
.createQueryBuilder('Robot_Ads')
.leftJoinAndMapMany(
'Robot_Ads.robotSessionScraperDatas',
Robot_Session_Scraper_Data,
'Robot_Session_Scraper_Data',
'"Robot_Session_Scraper_Data"."adIDAdID" = "Robot_Ads"."Ad_ID"'
)
.leftJoinAndMapOne(
'Robot_Session_Scraper_Data.robotSession',
Robot_Session_data,
'Robot_Session_data',
'"Robot_Session_data"."id" = "Robot_Session_Scraper_Data"."sessionIDId"'
)
.select([
'Robot_Ads.Ad_ID',
'Robot_Ads.Ad_Binary',
'Robot_Session_Scraper_Data.id',
'Robot_Session_Scraper_Data.Impression',
'Robot_Session_data.id',
'Robot_Session_data.Session_Device',
'Robot_Session_data.Session_Geolocation',
'SUM(Robot_Session_Scraper_Data.Impression) as summmm'
])
.groupBy("Robot_Ads.Ad_ID")
.addGroupBy("Robot_Session_Scraper_Data.id")
.addGroupBy("Robot_Session_data.id")
.orderBy('Robot_Ads.Ad_ID', 'DESC')
.getMany();
```
In this query, it return the data without "summmm".

Entities are like that

```@entity()
export class Robot_Ads {
@PrimaryGeneratedColumn()
Ad_ID!: number;
@column()
Ad_creative_source_url!: string;
@column({
type: "enum",
enum: AdTypeEnum,
})
Ad_type_Id!: string;
@column()
Ad_Binary!: string;
robotSessionScraperDatas!: Robot_Session_Scraper_Data[];
summmm!:number;
}```
```@entity()
export class Robot_Session_Scraper_Data {
@PrimaryGeneratedColumn()
id!: number;
@manytoone(type => Robot_Session_data, { nullable: false })
@JoinColumn()
Session_ID!: number;
@column({
type: "enum",
enum: ZoneTypeEnum
})
Zone_ID!: string;
@manytoone(type => Robot_Offers, { nullable: false })
@JoinColumn()
offer_id!: number;
@manytoone(type => Robot_Ads, { nullable: false })
@JoinColumn()
Ad_ID!: number;
@manytoone(type => Robot_Ad_Text, { nullable: true })
@JoinColumn()
Ad_text_ID!: number;
@column()
Impression!: number;
@column()
Category!: string;
@column()
Ad_creative_link_url!: string;
robotSession!: Robot_Session_data;
}```

```@entity()
export class Robot_Session_data {
@PrimaryGeneratedColumn()
id!: number;
@column({ type: 'timestamp' })
Session_start!: Date;
@column({ type: 'timestamp', default: null, nullable: true })
Session_end!: Date;
@column()
user_IP_address!: string;
@column()
User_Agent_Header!: string;
@column()
Accept_Language_Header!: string;
@column({
type: "enum",
enum: SessionOSEnum
})
Session_OS!: string;
@column({
type: "enum",
enum: SessionDeviceEnum
})
Session_Device!: string;
@column()
Session_Browser!: string;
@column()
Session_Geolocation!: string;
@column()
Session_Carrier!: string;
@column()
Session_Browser_language!: string;
}```

**Comment by nebkat** [comment]
Hi @007AMAN007, it would also really help if you could format your code so that it is more readable. It is possible to edit your original pull request text, so fix it there and remove the new comment.

**Comment by imnotjames** [comment]
You must use `getRawMany` if you aren't retrieving an entity.  `SUM()` is an aggregate and not part of your entity definition.

**Comment by JeremyBernier** [comment]
> You must use `getRawMany` if you aren't retrieving an entity. `SUM()` is an aggregate and not part of your entity definition.

Can we fix that? Seems like terrible design choice
