### ISSUE TITLE
Scylladb Support

### ISSUE THREAD

**Issue by jahangirahmad** [typeorm/typeorm#7074]
Could you please add Scylladb to the list of the supported databases?

**Comment by nebkat** [comment]
You are free to start adding support and open a pull request. If you take a look at https://github.com/typeorm/typeorm/tree/master/src/driver you might find some similar drivers, it should not be too difficult if you can copy paste these. If you run into issues you can open a draft pull request and perhaps someone will be in a better position to help you then.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
