### ISSUE TITLE
Is there a way I can use Group By and Count with Type Orm Repository

### ISSUE THREAD

**Issue by minhsangqn** [typeorm/typeorm#7081]
QUERYBUILDERR:

```
const res = await this.jobViewsRepository.createQueryBuilder('jobViews')           
    .addSelect("COUNT(jobViews.user_id) AS jobViews_total_count" )
    .leftJoinAndSelect(Jobs, "jobs", "jobs.id = jobViews.job_id")
    .where("jobs.user_id != :id", { id: user_id })        
    .groupBy("jobViews.job_id")**
    .orderBy('jobViews_total_count', 'DESC')**
    .limit(limit)
    .offset(offset)           
    .getRawMany();
```
FINDOPTION:

```
 const result = await this.jobViewsRepository.find({
        relations: ["jobs"],
        loadEagerRelations: true,  
        order: { id: "DESC" },
        skip: offset,
        take: limit,
    }
    );
```
DATABSE: mysql same question with: https://stackoverflow.com/questions/63157900/is-there-a-way-i-can-use-group-by-and-count-with-type-orm-repository 
but it has no answer

**Comment by nebkat** [comment]
This is not currently possible using the Repository.find(). Internally this uses query builder, so if the query builder works you can continue to use it.

**Comment by minhsangqn** [comment]
ORM with 1k4 Issuse can't do this which is too disappointing for this ORM @@

**Comment by minhsangqn** [comment]
> This is not currently possible using the Repository.find(). Internally this uses query builder, so if the query builder works you can continue to use it.

ORM with 1k4 Issuse can't do this which is too disappointing for this ORMORM with 1k4 Issuse can't do this which is too disappointing for this ORM

**Comment by minhsangqn** [comment]
> This is not currently possible using the Repository.find(). Internally this uses query builder, so if the query builder works you can continue to use it.

ORM with 1k4 Issuse can't do this which is too disappointing for this ORM

**Comment by minhsangqn** [comment]
@eugene-manuilov

**Comment by nebkat** [comment]
@minhsangqn For all the issues that this ORM may have, it actually _can_ do this. There are too many possible query combinations to support all of them in `Repository`, and there is nothing wrong with using `QueryBuilder`. Why do you need to use `Repository.find()`?

**Comment by minhsangqn** [comment]
> @minhsangqn Đối với tất cả các vấn đề mà ORM này có thể gặp phải, nó thực sự _có thể_ làm được điều này. Có quá nhiều tổ hợp truy vấn có thể có để hỗ trợ tất cả chúng `Repository`và không có gì sai khi sử dụng `QueryBuilder`. Tại sao bạn cần sử dụng `Repository.find()`?

Its syntax is clearer and easier on the eyes as the code I hope its syntax is queryable in {}

**Comment by minhsangqn** [comment]
> @minhsangqn For all the issues that this ORM may have, it actually _can_ do this. There are too many possible query combinations to support all of them in `Repository`, and there is nothing wrong with using `QueryBuilder`. Why do you need to use `Repository.find()`?

When I want multiple conditions I can declare in one object but for queryBuilder it is dark andwhere or in leftJoin I have to use many leftJoin, I don't like this.

**Comment by minhsangqn** [comment]
![Screenshot from 2020-11-19 09-54-50](https://user-images.githubusercontent.com/31920328/99615040-4d243900-2a4d-11eb-8458-4b31c75dc45d.png)


> @minhsangqn For all the issues that this ORM may have, it actually _can_ do this. There are too many possible query combinations to support all of them in `Repository`, and there is nothing wrong with using `QueryBuilder`. Why do you need to use `Repository.find()`?

![Screenshot from 2020-11-19 09-54-50](https://user-images.githubusercontent.com/31920328/99615066-557c7400-2a4d-11eb-9ae3-104404aa2cc5.png)
For example, if I want to join a table with many cases here, I cannot because the conditon passed is a string not an object

**Comment by nebkat** [comment]
> Its syntax is clearer and easier on the eyes as the code I hope its syntax is queryable in {}

I understand, and I too prefer to use Repository, but it's simply not possible to support all edge cases. Without much context here I might also suggest that you hold a `jobViews` counter in your `jobs` entity, rather than aggregating on the `jobViews` table. I presume you are storing additional information about each job view?

> For example, if I want to join a table with many cases here, I cannot because the conditon passed is a string not an object

`condition` is optional here. If you do not pass a condition it will correctly choose one for this relation, no string needed.

That said it is true that it would be nice if this could work with an object. If that is something you would like you can make a feature request submission specifically for that.

**Comment by minhsangqn** [comment]
> > Cú pháp của nó rõ ràng hơn và dễ nhìn hơn vì mã mà tôi hy vọng rằng cú pháp của nó có thể truy vấn được trong {}
> 
> Tôi hiểu và tôi cũng thích sử dụng Kho lưu trữ hơn, nhưng không thể hỗ trợ tất cả các trường hợp cạnh. Nếu không có nhiều ngữ cảnh ở đây, tôi cũng có thể đề nghị bạn giữ một bộ `jobViews`đếm trong `jobs`thực thể của mình , thay vì tổng hợp trên `jobViews`bàn. Tôi cho rằng bạn đang lưu trữ thông tin bổ sung về từng chế độ xem công việc?
> 
> > Ví dụ: nếu tôi muốn tham gia một bảng có nhiều trường hợp ở đây, tôi không thể vì điều kiện được truyền là một chuỗi không phải là một đối tượng
> 
> `condition`là tùy chọn ở đây. Nếu bạn không vượt qua một điều kiện, nó sẽ chọn chính xác một điều kiện cho mối quan hệ này, không cần chuỗi.
> 
> Điều đó nói rằng đúng là sẽ rất tuyệt nếu điều này có thể hoạt động với một đối tượng. Nếu đó là điều bạn muốn, bạn có thể gửi yêu cầu tính năng cụ thể cho điều đó.

Thank you I don't like the typeOrm this is the project maintain otherwise I would never want to use it

**Comment by minhsangqn** [comment]
> > Its syntax is clearer and easier on the eyes as the code I hope its syntax is queryable in {}
> 
> I understand, and I too prefer to use Repository, but it's simply not possible to support all edge cases. Without much context here I might also suggest that you hold a `jobViews` counter in your `jobs` entity, rather than aggregating on the `jobViews` table. I presume you are storing additional information about each job view?
> 
> > For example, if I want to join a table with many cases here, I cannot because the conditon passed is a string not an object
> 
> `condition` is optional here. If you do not pass a condition it will correctly choose one for this relation, no string needed.
> 
> That said it is true that it would be nice if this could work with an object. If that is something you would like you can make a feature request submission specifically for that.

How can I groupBy in leftJoinAndSelect
![Screenshot from 2020-11-19 10-17-39](https://user-images.githubusercontent.com/31920328/99617040-fe789e00-2a50-11eb-8851-58e8e78016e9.png)

**Comment by nebkat** [comment]
Perhaps you could post your target SQL query? Is the commented out `groupBy()` not working? It's difficult to say without more information. Perhaps `.groupBy('maker_code.maker_code')`?

**Comment by minhsangqn** [comment]
> Có lẽ bạn có thể đăng truy vấn SQL mục tiêu của mình? Đã nhận xét ra `groupBy()`không hoạt động? Thật khó để nói nếu không có thêm thông tin. Có lẽ `.groupBy('maker_code.maker_code')`?

```
  [
OrderEntity {
    order_no: '001-20201118-00006',
    create_date: 2020-11-18T04:54:58.000Z,
    order_date: 2020-10-02T00:00:00.000Z,
    orderer_role: RoleEntity {
      role_id: '05',
      role_name: 'AGENCY',
      description: 'AGENCY'
    },
    maker_code: MakerEntity {
      maker_id: 'b55b69eb-3990-430a-9191-a20bb51e11a7',
      maker_code: '002',
      maker_name: 'カカーテンじゅうたん王国',
      elapsedTime: '08:00:00',
      delivery_calendar_url: './assets/pdf/katenhanbai.pdf',
      email: 'sangvm1@yopmail.com'
    }
  },
  OrderEntity {
    order_no: '001-20201118-00008',
    create_date: 2020-11-18T04:54:58.000Z,
    order_date: 2020-01-12T00:00:00.000Z,
    orderer_role: RoleEntity {
      role_id: '04',
      role_name: 'OFFICE',
      description: 'OFFICE'
    },
    maker_code: MakerEntity {
      maker_id: 'b55b69eb-3990-430a-9191-a20bb51e11a7',
      maker_code: '002',
      maker_name: 'カカーテンじゅうたん王国',
      elapsedTime: '08:00:00',
      delivery_calendar_url: './assets/pdf/katenhanbai.pdf',
      email: 'sangvm1@yopmail.com'
    }
  },
{
OrderEntity {
    order_no: '001-20201118-00009',
    create_date: 2020-11-18T04:54:58.000Z,
    order_date: 2020-01-12T00:00:00.000Z,
    orderer_role: RoleEntity {
      role_id: '04',
      role_name: 'OFFICE',
      description: 'OFFICE'
    },
    maker_code: MakerEntity {
      maker_id: 'b55b69eb-3990-430a-9191-a20bb51e11a7',
      maker_code: '002',
      maker_name: 'カカーテンじゅうたん王国',
      elapsedTime: '08:00:00',
      delivery_calendar_url: './assets/pdf/katenhanbai.pdf',
      email: 'sangvm1@yopmail.com'
    }
}]
```
I have an order table every order has a maker_code how can I groupBy it
![Screenshot from 2020-11-19 10-35-32](https://user-images.githubusercontent.com/31920328/99617947-fae61680-2a52-11eb-8f1f-f9b075379bbc.png)

**Comment by nebkat** [comment]
As I said `groupBy('order.maker_code')` should work, does it not?

**Comment by minhsangqn** [comment]
> As I said `groupBy('order.maker_code')` should work, does it not?

I tried it but it failed so I just cmt code it again
![Screenshot from 2020-11-19 10-42-14](https://user-images.githubusercontent.com/31920328/99618459-e8b8a800-2a53-11eb-8739-b5d819dba1be.png)

**Comment by nebkat** [comment]
This looks like a problem with your database configuration, not with TypeORM. If you do `.getQuery()` you can see exactly which query it is running. Try to run this manually on your database (in a terminal) and find a query that works for you.

You can search elsewhere for the "only_full_group_by" mode.
