### ISSUE TITLE
The highlight.js Is the 9. X version prompt：`Version 9 of Highlight.js has reached EOL and is no longer supported. Please upgrade to version 10.`

### ISSUE THREAD

**Issue by ZQun** [typeorm/typeorm#7090]
## Issue Description
Hello,

The highlight.js Is the 9. X version prompt：`Version 9 of Highlight.js has reached EOL and is no longer supported. Please upgrade to version 10.`

Because the dependent "cli highlight" in typeorm: "2.1.4" is not updated to 10. X

https://github.com/highlightjs/highlight.js/issues/2877

**Comment by matyo91** [comment]
Got the same display. It seems that [cli-highlight 2.14"](https://github.com/felixfbecker/cli-highlight/blob/master/package.json ) is not up to date with version 10.

**Comment by ZQun** [comment]
> Got the same display. It seems that [cli-highlight 2.14](https://github.com/felixfbecker/cli-highlight/blob/master/package.json) is not up to date with version 10.

Yeah, because of the 9.x introduced by `cli-highlight 2.14`, and there has been no upgrade version for a long time

**Comment by nebkat** [comment]
https://github.com/felixfbecker/cli-highlight/issues/100

**Comment by cloakedch** [comment]
I would go one step further and alter `typeorm` so that `highlight.js` is only an optional dependency (I don't care about any console highlights, especially not in production).

**Comment by felixfbecker** [comment]
This should be fixed with https://github.com/felixfbecker/cli-highlight/releases/tag/v2.1.6. Since it's not a major release, you should be able to upgrade to that without any new release of `typeorm` needed.

**Comment by ZQun** [comment]
> This should be fixed with https://github.com/felixfbecker/cli-highlight/releases/tag/v2.1.6. Since it's not a major release, you should be able to upgrade to that without any new release of `typeorm` needed.

Yes, it has been resolved, thank you!

**Comment by LuZhenJie1999** [comment]
Hi, I would like to know what the specific instructions of 'npm deprecate' are? I am using "npm deprecate highlight.js@"<10.0.0" "critical bug fixed in v10.0.0" ", but it reports some errors. Thank you very much!
