### ISSUE TITLE
PrimaryGeneratedColumn does not work

### ISSUE THREAD

**Issue by Bluebang** [typeorm/typeorm#7097]
## Issue Description
@PrimaryGeneratedColumn() does not work.only UUID type works.

### Expected Behavior

save success.

### Actual Behavior

inserted a data with ID 0 and print these error message.
```
Error: Cannot update entity because entity id is not set in the entity.
```
and this error will be reported after executing the data with ID 0.It seems to be caused by this abnormal data, which can be ignored
```
QueryFailedError: ER_DUP_ENTRY: Duplicate entry '0' for key 'PRIMARY' 
```

### Steps to Reproduce

there is my entity:
```JavaScript
@Entity()
export class Spm {
    @PrimaryGeneratedColumn()
    //@PrimaryGeneratedColumn("uuid") //The UUID type works
    id: number;
    @Column()
    type: string;
    @Column()
    userId: number;
    @Column()
    phaseId: number;
    @CreateDateColumn()
    atCreated: Date;
}
```
and when i execute save.

```javascript
let entity = new Spm();
entity.type="info";
entity.userId=1;
entity.phaseId=2;
this.connection.getRepository(Spm).save(entity);//Error: Cannot update entity because entity id is not set in the entity.
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | MacOS 10.15.4 (19E287)         |
| Node.js version     | v10.15.3 | 
| @nestjs/typeorm version  | v^7.1.5| 
| Typescript version  | v^3.7.4 | 
| TypeORM version     | v^0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by dmitrif** [comment]
| Dependency | Version |
|-----------------|--|
|Operating System	|  Ubuntu 20.04 |
| Node.js version | v14.15.1 |
| Typescript version | v^4.1.2 |
| TypeORM version	| v^0.2.29 |

Works for me! Here is the entity:

```
@Entity('user')
export class UserEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  email!: string;

  @Column()
  password!: string;
}
```

**Comment by Bluebang** [comment]
The same code is worked under windows. Is it the environment?

**Comment by Bluebang** [comment]
> Dependency	Version
> Operating System	Ubuntu 20.04
> Node.js version	v14.15.1
> Typescript version	v^4.1.2
> TypeORM version	v^0.2.29
> Works for me! Here is the entity:
> 
> ```
> @Entity('user')
> export class UserEntity {
>   @PrimaryGeneratedColumn()
>   id!: number;
> 
>   @Column()
>   email!: string;
> 
>   @Column()
>   password!: string;
> }
> ```

tks @dmitrif ，I think it should be the running environment, but I don't know where it is

**Comment by nebkat** [comment]
The problem is likely here:

https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/driver/mysql/MysqlDriver.ts#L710-L730

Perhaps `resultId` is not being returned correctly?

**Comment by Bluebang** [comment]
@nebkat hi nebkat, The problem is likely here:the 127 line.

> https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/query-builder/ReturningResultsEntityUpdator.ts#L119-L130

Do you know how it happened? Code should be OK, the same code I can run normally in Windows system, but there is a problem under MacOS system. I can't find a solution.😢😢

**Comment by Bluebang** [comment]
> @Bluebang did you find a solution to your issue ? I'm facing the same at the moment.
> I cannot figure out what is the real issue here

My problem is the database version, you use 5.7 or above to try.

**Comment by jinsankim** [comment]
I've also faced this issue.

**Comment by GKyomen** [comment]
Same issue here. Don't know how to check database version or even if I could change it, as it's not mine.

**Comment by morteza-mortezai** [comment]
same issue form me
Typeorm : 0.3.15
mongodb : 5.2
nest js

**Comment by fawizzy** [comment]
Facing same issue here
