### ISSUE TITLE
column default is ignored

### ISSUE THREAD

**Issue by yossibeck** [typeorm/typeorm#7098]
### Expected Behavior
Defining a column with a default value should take that value on insert new and put it in the column

### Actual Behavior
puts ```DEFAULT``` value - since there's no default value in the db, it throws an error

```
query: START TRANSACTION
query: INSERT INTO "public"."FamilyAccounts"("createdAt", "updatedAt", "name") VALUES ($1, $2, DEFAULT) RETURNING "id", "createdAt", "updatedAt", "name" -- PARAMETERS: ["2020-11-22T20:50:20.187Z","2020-11-22T20:50:20.187Z"]
query failed: INSERT INTO "public"."FamilyAccounts"("createdAt", "updatedAt", "name") VALUES ($1, $2, DEFAULT) RETURNING "id", "createdAt", "updatedAt", "name" -- PARAMETERS: ["2020-11-22T20:50:20.187Z","2020-11-22T20:50:20.187Z"]
```

### Steps to Reproduce
1. Define entity FamilyAccount
2. Define a default value for name
3. Create an instance of FamiltyAccount
4. set all properties but NOT for name
5. Save

```typescript
@Index("FamilyAccounts_pkey", ["id"], { unique: true })
@Entity("FamilyAccounts", { schema: "public" })
export class FamilyAccount extends extends BaseEntity {
    @PrimaryGeneratedColumn({ type: "integer", name: "id" })
    id: number;

    @CreateDateColumn({ name: "createdAt" })
    createdAt: Date;
  
    @UpdateDateColumn({ name: "updatedAt" })
    updatedAt: Date;

    @Column("character varying", { name: "name", nullable: true, length: 255, default: "'test 123'" })
    name: string | null;

    @OneToMany(() => UserInFamilyAccount, userInFamily => userInFamily.familyAccount)
    userInFamilyAccounts: [];
}

// then try to create the family account:
  let fa = FamilyAccount.create();
  fa.createdAt = fa.updatedAt = new Date();
  fa = await fa.save();
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v12.0.0| 
| Typescript version  | v3.9.7 | 
| TypeORM version     | v0.2.26 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by yossibeck** [comment]
btw, I also tried these:
```
deafult: () => "'test 123'"
```
```
deafult: () => 'test 123'
```
```
deafult: 'test 123'
```
all fail with the same result

**Comment by nebkat** [comment]
The `default` property on a column is meant to set the default in the database, which leads to this issue when you use your own table without synchronizing. We could add an `explicitDefault: boolean` property to `ColumnOptions` or something similar to `InsertQueryBuilder`, but until then the current behaviour isn't technically a bug.

**Comment by yossibeck** [comment]
thanks, will create a PR for it

**Comment by Ayomide-Daniel** [comment]
> thanks, will create a PR for it

Hi @yossibeck! 👋 

Did you eventually get it fixed? If yes, please, how?
