### ISSUE TITLE
ManyToOne relation with custom column name

### ISSUE THREAD

**Issue by WalterLeinert** [typeorm/typeorm#71]
I'm trying to get setup an example for my mysql-db with real customer data (and tables). 
Two simple tables called artikel and kollektion have a simple may-to.one relation (many articles may be part of one collection).

`

@Table("artikel")
export class Artikel {

    @PrimaryColumn("int", { generated: true })
    @Column({name: "artikel_id"})
    id: number;

    @Column({name: "artikel_nummer"})
    nummer: string;

    @Column({name: "artikel_name"})
    name: string;

    @Column({name: "artikel_extrabarcode"})
    extrabarcode: string;

    @Column({name: "artikel_saison"})
    saison: string;

    @ManyToOne(type => Kollektion, { cascadeAll: true })
    @Column("int", {name: "id_kollektion"})
    kollektion: Kollektion;
}

@Table("kollektion")
export class Kollektion {

    @PrimaryColumn("int", { generated: true })
    @Column({name: "kollektion_id"})
    id: number;

    @Column({name: "kollektion_name"})
    name: string;
}

`

In Table Artikel the FK column to table kollektion is named 'id_kollektion' and not 'artikel'.
I tried to specify the different column as shown above by adding a '@Column("int", {name: "id_kollektion"})' but when executing a persist I get the following error:
`
...
executing query: START TRANSACTION                                                                                    
executing query: INSERT INTO artikel(artikel_nummer, artikel_name, artikel_saison, id_kollektion, kollektion) VALUES (
?,?,?,?,?) -- PARAMETERS: ["SNB-001","Snowboard WL","winter-2016",{"name":"Burton 2016"},null]                        
executing query: INSERT INTO kollektion(kollektion_name) VALUES (?) -- PARAMETERS: ["Burton 2016"]                    
query failed: INSERT INTO artikel(artikel_nummer, artikel_name, artikel_saison, id_kollektion, kollektion) VALUES (?,?
,?,?,?) -- PARAMETERS: ["SNB-001","Snowboard WL","winter-2016",{"name":"Burton 2016"},null]                           
executing query: ROLLBACK                                                                                             
Cannot save. Error:  { Error: ER_BAD_FIELD_ERROR: Unknown column 'kollektion' in 'field list'    
...
`

Seems that there is no support for specifying a custom column name.
I think this would be a necessary feature for accessing existing database schemas.

Regards,
Walter

**Comment by pleerock** [comment]
Hi, custom column names are currently experimental feature, is working but has bugs. Its not a priority right now, there are multiple other tasks with higher priorities that Im current working on. This is **definitely** will be resolved, but I can't take care about it right now. If you don't want to wait, feel free to contribute.

**Comment by pleerock** [comment]
You have error in your example:

```typescript
    @PrimaryColumn("int", { generated: true })
    @Column({ name: "kollektion_id" })
    id: number;
```

should be simply:

```typescript
    @PrimaryColumn("int", { generated: true, name: "kollektion_id" })
    id: number;
```

**Comment by pleerock** [comment]
there are other errors as well. Here is correct code:

```typescript
@Table("artikel")
export class Artikel {

    @PrimaryColumn("int", { generated: true, name: "artikel_id" })
    id: number;

    @Column({ name: "artikel_nummer" })
    nummer: string;

    @Column({ name: "artikel_name" })
    name: string;

    @Column({ name: "artikel_extrabarcode" })
    extrabarcode: string;

    @Column({ name: "artikel_saison" })
    saison: string;

    @ManyToOne(type => Kollektion, { cascadeAll: true })
    @JoinColumn({ name: "id_kollektion" })
    kollektion: Kollektion;

}

@Table("kollektion")
export class Kollektion {

    @PrimaryColumn("int", { generated: true, name: "kollektion_id" })
    id: number;

    @Column({ name: "kollektion_name" })
    name: string;

}
```

**Comment by pleerock** [comment]
if with newly changed entities it still will not work try to test it with `npm i typeorm@next`

**Comment by WalterLeinert** [comment]
Hi pleerock,
Thank you for your corrections and hints. I will retest the issue and close it if it works as expected.

Regards, Walter
