### ISSUE TITLE
Load data from junction table

### ISSUE THREAD

**Issue by NoNameProvided** [typeorm/typeorm#710]
Do we have any way other than using raw sql query to load data from a junction table? What I want to do is simply check for the existence of the specified`id`. 

My use-case: it's a junction table for likes and I want to check if an user has liked an article. So the query I want to use

```sql
SELECT * FROM "article_likes_user" WHERE "articleId" = :articleId AND "userId" = :userId
```

**Comment by pleerock** [comment]
There is no at the moment. But I plan to implement such functions in the `RelationQueryBuilder` in the future. Something like this:

```ts
const isUserLiked = await connection.createQueryBuilder(Article)
     .relation("likedUsers")
     .has(user)
     .execute();
```

You can implement it on your own if you want

**Comment by pleerock** [comment]
Relational query builder functionality is implemented in latest version, you can find docs on site.

**Comment by QoVoQ** [comment]
Sorry, is this feature still working in? I can't find the method `.has` in [RelationQueryBuilder.ts](https://github.com/typeorm/typeorm/blob/master/src/query-builder/RelationQueryBuilder.ts)
