### ISSUE TITLE
SQL Server error when requesting additional returning columns

### ISSUE THREAD

**Issue by nebkat** [typeorm/typeorm#7100]
## Issue Description
#5361 changed the way SQL Server uses `OUTPUT` in `INSERT`/`UPDATE` queries, causing an error if additional columns are requested using `InsertQueryBuilder.returning()`.

### Expected Behavior

```typescript
connection.createQueryBuilder(Post, 'post')
    .insert()
    .values({ title: "TITLE" })
    .returning(["text"])
    .execute();

connection.createQueryBuilder(Post, 'post')
    .update()
    .set({ title: "TITLE" })
    .returning(["text"])
    .execute();
```

Should both execute without error and return additional column "text".

### Actual Behavior

```sql
DECLARE @OutputTable TABLE ("id" int);

INSERT INTO "post"("title", "text") OUTPUT INSERTED."text", INSERTED."id" INTO @OutputTable VALUES (@0, @1);

SELECT * FROM @OutputTable
```

`QueryFailedError: Error: Column name or number of supplied values does not match table definition.`

```sql
UPDATE "post" SET "title" = @1 OUTPUT INSERTED."text" INTO @OutputTable WHERE "id" IN (@0)
```

`QueryFailedError: Error: Must declare the table variable "@OutputTable".`

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [x] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
So the way to resolve this would be to take the fields that are in the `returning` and create the output table with that.

However, there are cases where the `returning` is a string.  In that case.. not sure what we can do.

**Comment by imnotjames** [comment]
I almost think you're right & that PR should be reverted for now - and if people have triggers + want to use returning, tough luck.

Unless there's an easier way to declare a table dynamically but I can't remember how to do that.  I'll do some quick investigation.

**Comment by sgarner** [comment]
> I almost think you're right & that PR should be reverted for now - and if people have triggers + want to use returning, tough luck.

To be clear, the original PR fixed an issue where TypeORM was completely unusable with MSSQL tables having triggers. It wasn't only if the `returning` feature was used.

I wasn't even aware that the `returning` feature on QueryBuilder, existed - it's not mentioned anywhere in the docs.

So I would suggest that reverting the fix is an overreaction. But there is certainly a bug here, the output table logic needs to respect the custom `returning` fields. This should be possible to resolve, I will try to find time to look at it soon.

**Comment by imnotjames** [comment]
> > I almost think you're right & that PR should be reverted for now - and if people have triggers + want to use returning, tough luck.
> 
> To be clear, the original PR fixed an issue where TypeORM was completely unusable with MSSQL tables having triggers. It wasn't only if the `returning` feature was used.

Oh, dang!  Okay.  Thankfully, we'd have seen this is the code was entirely reverted.  We have CI for SQL Server running.
> 
> I wasn't even aware that the `returning` feature on QueryBuilder, existed - it's not mentioned anywhere in the docs.

No worries.  I'm looking to add tests that confirm the behavior works as expected so we don't see a regression like this for returning.

> 
> So I would suggest that reverting the fix is an overreaction. But there is certainly a bug here, the output table logic needs to respect the custom `returning` fields. This should be possible to resolve, I will try to find time to look at it soon.

Sure!  If you've got time, awesome.  I'll be clear in this issue if I get time to look at it and fix it.

**Comment by imnotjames** [comment]
I have a possible fix in place.  However, `returning` will only work when metadata is available.

**Comment by sgarner** [comment]
Awesome, thanks for fixing this @imnotjames ❤️
