### ISSUE TITLE
OneToOne relationships not creating column ids

### ISSUE THREAD

**Issue by stephtea** [typeorm/typeorm#7102]
### Issue Description
OneToOne relationships not creating relationship columns

### Expected Behavior
Foreign key columns to be created per [documentation](https://github.com/typeorm/typeorm/blob/master/docs/one-to-one-relations.md). I tried different ways, but it doesn't seem to work. Below is a simple example.

### Actual Behavior

```typescript
        await queryRunner.query(`CREATE TABLE "a" ("id" SERIAL NOT NULL, CONSTRAINT "PK_2202fa80e03dfdac2f685c43ee4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "b" ("id" SERIAL NOT NULL, CONSTRAINT "PK_88835795171b73b5aea9ffb7b6c" PRIMARY KEY ("id"))`);
```

```
+-------------+--------------+----------------------------+
|                        a                          |
+-------------+--------------+----------------------------+
| id          | int(11)      | PRIMARY KEY AUTO_INCREMENT |
+-------------+--------------+----------------------------+

+-------------+--------------+----------------------------+
|                          b                           |
+-------------+--------------+----------------------------+
| id          | int(11)      | PRIMARY KEY AUTO_INCREMENT |
+-------------+--------------+----------------------------+
```

### Steps to Reproduce

```typescript

@Entity()
export class A {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToOne(() => B, (b) => b.a)
  @JoinTable()
  b: B;
}

@Entity()
export class B {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToOne(() => A, (a) => a.b)
  a: A;
}


```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |Windows 10|
| Node.js version     | v12.18.4 | 
| Typescript version  | v4.0.3 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

**Comment by stephtea** [comment]
A simpler example:

```typescript
@Entity()
export class B {
  @PrimaryGeneratedColumn()
  id: number;
}

@Entity()
export class A {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToOne(() => B)
  @JoinTable()
  b: B;
}
```

results in:
```typescript
        await queryRunner.query(`CREATE TABLE "b" ("id" SERIAL NOT NULL, CONSTRAINT "PK_88835795171b73b5aea9ffb7b6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "a" ("id" SERIAL NOT NULL, CONSTRAINT "PK_2202fa80e03dfdac2f685c43ee4" PRIMARY KEY ("id"))`);

```

**Comment by nebkat** [comment]
Please read carefully, the documentation shows `@JoinColumn()` not `@JoinTable()` 😉

**Comment by stephtea** [comment]
> Please read carefully, the documentation shows `@JoinColumn()` not `@JoinTable()` 😉

@nebkat thank you! I'm glad it was on my end.  I suggest to rename the decorator `@DoTheThing()` ;)
