### ISSUE TITLE
PostgreSQL sequence identifier length error

### ISSUE THREAD

**Issue by matthewberryman** [typeorm/typeorm#7106]
### Expected Behaviour

Generated sequence name should be < `NAMEDATALEN` bytes, where `NAMEDATALEN`=64 by default.

### Actual Behaviour

There is no check in https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/driver/postgres/PostgresQueryRunner.ts#L2055 or https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/driver/postgres/PostgresQueryRunner.ts#L2058 that the generated sequence length fits in the default limit for identifiers. A second schema sync will throw an unhandled error, e.g.:
```
Error during schema synchronization:
QueryFailedError: relation "soil_classification_order_sub_orders_soilclassificationordersub" does not exist
    at new QueryFailedError (/Users/matthew/code/CBB/Nepal/API/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/Users/matthew/code/CBB/Nepal/API/src/driver/postgres/PostgresQueryRunner.ts:220:30)
    at Query.handleError (/Users/matthew/code/CBB/Nepal/API/node_modules/pg/lib/query.js:139:19)
    at Client._handleErrorMessage (/Users/matthew/code/CBB/Nepal/API/node_modules/pg/lib/client.js:326:17)
    at Connection.emit (node:events:329:20)
    at Connection.EventEmitter.emit (node:domain:467:12)
    at /Users/matthew/code/CBB/Nepal/API/node_modules/pg/lib/connection.js:109:12
    at Parser.parse (/Users/matthew/code/CBB/Nepal/API/node_modules/pg-protocol/src/parser.ts:102:9)
    at TLSSocket.<anonymous> (/Users/matthew/code/CBB/Nepal/API/node_modules/pg-protocol/src/index.ts:7:48)
    at TLSSocket.emit (node:events:329:20) {
  length: 161,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'namespace.c',
  line: '423',
  routine: 'RangeVarGetRelidExtended',
  query: `ALTER TABLE "soil_classification_order_sub_orders" ALTER COLUMN "SoilClassificationOrderSubOrdersID" SET DEFAULT nextval('soil_classification_order_sub_orders_SoilClassificationOrderSubOrdersID_seq')`,
  parameters: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nepal@1.0.0 schema:sync: `ts-node ./node_modules/typeorm/cli.js schema:sync`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nepal@1.0.0 schema:sync script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matthew/.npm/_logs/2020-11-24T22_40_17_327Z-debug.log
```

This is similar to 
https://github.com/typeorm/typeorm/issues/3118 
but for sequence names, not column aliases. 

### Steps to Reproduce

1. Define an entity with a PrimaryGeneratedColumn where `${tableName}_${columnName}_seq` is longer than 63 bytes.
2. Schema sync twice.

```typescript
@Entity()
export class SoilClassificationOrderSubOrders {
    @PrimaryGeneratedColumn() 
    SoilClassificationOrderSubOrdersID: number;
    @OneToOne(type => SoilClassificationOrders) @JoinColumn({name: 'SoilClassificationOrderID'})
    SoilClassificationOrderID: SoilClassificationOrders;

    @OneToOne(type => SoilClassificationSubOrders) @JoinColumn({name: 'SoilClassificationSubOrderID'})
    SoilClassificationSubOrderID: SoilClassificationSubOrders;

    @Column()
    ValidFrom: Date;
}

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| macOS    |      11.1 beta    |
| Node.js version     | v15.2.1 | 
| Typescript version  | v4.0.2 | 
| TypeORM version     | v0.2.29 | 

### Additional Context

https://www.postgresql.org/docs/13/limits.html

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nebkat** [comment]
Both sequences and column aliases are restricted by `NAMEDATALEN` right?

This is a problem that also exists in Oracle, which is limited to 32 characters for identifiers.

Really there needs to be a global solution for shortening identifiers, either through the naming strategy where users could do a more advanced truncation (e.g. remove vowels first, shorten common phrases) or a common hashing system.

**Comment by matthewberryman** [comment]
Yes all identifiers are restricted, in the case of PostgreSQL this is by NAMEDATALEN.

There is a global solution introduced in https://github.com/typeorm/typeorm/pull/3514 where table names and column aliases are checked (although imperfectly in corner cases #7107) and shortened by a [function](https://github.com/typeorm/typeorm/blob/c4a36da62593469436b074873eba186f0f8b990d/src/util/StringUtils.ts#L76) with some options / you could always change it. For reference Oracle (older versions) are 30 bytes, not 32 characters. https://docs.oracle.com/database/121/SQLRF/sql_elements008.htm#SQLRF51129

Reading through the code a bit more, only PostgreSQL and CockroachDB drivers create sequences and suffer from this bug. I will submit a bug fix (ignoring #7107) for those.

**Comment by nebkat** [comment]
Ah I see, I was aware of that function but didn't know there was a `StringUtils.shorten()` before the hashing that was introduced in #5227. Unfortunately it still isn't applied in all circumstances, so some work is needed there anyway.

Ideally we could reintroduce `shorten()` along with the suggestion of having an alias map, as per https://github.com/typeorm/typeorm/pull/5227#issuecomment-568044039. There might be some differentiation between permanent identifiers like the sequence name, and temporary aliases per query.

Either way quick fix sounds like a good idea for now.

**Comment by vuki656** [comment]
Related to #2661

**Comment by matthewberryman** [comment]
On further investigation it's a little bit more tricky, and way more specific, than I first thought. The problem first starts when TypeORM uses the default PostgreSQL sequence name. PostgreSQL is smart enough to truncate, however it uses its own, different algorithm again to `StringUtils.shorten()`. I have no idea if CockroachDB suffers from the same issue, or how it resolves with without more research but I will look into it, as it's the only other TypeORM driver where a sequence name is generated.
