### ISSUE TITLE
Soft deleted docs still being pulled in Mongodb

### ISSUE THREAD

**Issue by mak-pun** [typeorm/typeorm#7113]
### Expected Behavior

As described in the document TypeORM will only pull "non-deleted" entities from the database.

### Actual Behavior

TypeORM still pulls "non-deleted" entities from the database.

This is the output from findAllConfigurations method.
```
[
    {
        "_id": "5fbfdf1388c68eaa23ff0d40",
        "createdAt": "2020-11-26T17:00:03.111Z",
        "updatedAt": "2020-11-26T17:00:40.637Z",
        "deletedAt": "2020-11-26T17:00:40.637Z",
        "exchange": {
            "className": "KuCoin",
            "sandboxMode": false,
            "id": "kucoin",
            "symbol": "ADA/USDT",
            "credentials": {
                "apiKey": "ddd",
                "secret": "abc"
            }
        },
        "bot": {
            "name": "test5",
            "className": "SmartGridBot",
            "extraSettings": {
                "startZone": 1,
                "endZone": 111,
                "initialCapital": 111,
                "numberOfZones": 111
            }
        }
    }
]
```

### Steps to Reproduce

1. Add a document. The document will have a deletedAt field with a value of null. 
2. Delete document with softRemove.
3. Fetch the collection the document deleted still shows up.

```typescript

// Repositiory

@EntityRepository(Configuration)
export class ConfigurationRepository extends MongoRepository<Configuration> {

  async findAllConfigurations(): Promise<Configuration[]> {
    const configurations = await this.find()
    return configurations
  }

  async deleteConfiguration(
    configuration: Configuration
  ): Promise<ObjectID> {
    await this.softRemove(configuration)
    return configuration._id
  }
}

// Entity

@Entity()
export class Configuration extends BaseEntity {
  @ObjectIdColumn()
  _id: ObjectID;

  @Column(type => Exchange)
  exchange: Exchange;

  @Column(type => Bot)
  bot: Bot;

  @VersionColumn()
  __v?: number

  @CreateDateColumn()
  createdAt?: Date

  @UpdateDateColumn()
  updatedAt?: Date

  @DeleteDateColumn()
  deletedAt?: Date
}

```

### My Environment

| Dependency          | Version  |
Operating System    macOS Mojave Version 10.14.6
Node.js version    v14.15.1
Typescript version 
├─┬ @nestjs/cli@7.5.3
│ └── typescript@4.0.5 
└── typescript@4.1.2 
TypeORM version 
└── typeorm@0.2.29 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by arnabrahman** [comment]
This is still open :(
