### ISSUE TITLE
Using IN operator with mssql returns only one row

### ISSUE THREAD

**Issue by rubiin** [typeorm/typeorm#7123]
When using IN operator followed by an array of unique data, the result is only a single row.

for example
```
const idxArray = [1,2,3,4]
const result = await getConnection().query(`select * from Users where id in (@0),[idxArray])`

```
I had no such issues with postgres may be limited to mssql driver. Also if run the below query, it returns the expected result
```
const result = await getConnection().query(`select * from Users where id in (1,2,3,4)`

```

**Comment by nebkat** [comment]
This query goes directly to the driver, which it seems doesn't support array parameters. You can use the TypeORM parameter system which will deal with arrays by converting it to `@0, @1, @2, @3` or similar.

**Comment by rubiin** [comment]
> This query goes directly to the driver, which it seems doesn't support array parameters. You can use the TypeORM parameter system which will deal with arrays by converting it to `@0, @1, @2, @3` or similar.

can you provide me a snippet  @nebkat

**Comment by nebkat** [comment]
`where({id: In(idxArray)})`

**Comment by rubiin** [comment]
I actually need to use raw query

**Comment by nebkat** [comment]
If you are using the raw query then it's not really relevant to TypeORM. The parameter system that we have control over is in the query builder. Using direct queries just goes straight to the driver, without any processing.

**Comment by imnotjames** [comment]
You can also use `:....` syntax.

```
Raw(`foo in :...bar`, { bar: [ 1,2,3 ] })
````

This is closer to a support question though.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
