### ISSUE TITLE
error on existing MySQL database after upgrading to 0.2.29

### ISSUE THREAD

**Issue by Sprechen** [typeorm/typeorm#7124]
## Issue Description
I'm currently using TypeORM version 0.2.25 and today I migrated to the latest 0.2.29 version.

However, I am not able to running my application with the latest version.

I'm using MySQL as database, and the database is already populated with tables and entries created with the current version of the application (using the TypeORM entities).

### Expected Behavior

My app should work as expected, correctly update the database if an entities structure is changed and synchronizing the entities.

### Actual Behavior

On startup, when TypeORM is init and the entities are synchronizing with the database tables, I have the following error:

```
 QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'client' already exists
```

If I create a new empty database, the first time no error were thrown and the application start up correctly. If I stop and restart again the app, the same error is thrown.

Downgrading to the 0.2.25 version solve my problem.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  MacOS 10.15.7       |
| Node.js version     | v12.18.3 | 
| Typescript version  | v3.7.5 | 
| TypeORM version     | v0.2.25 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

**Comment by Ginden** [comment]
I'm closing this on assumption that problem was solved.
