### ISSUE TITLE
please add lucid ORM query builder to TypeORM

### ISSUE THREAD

**Issue by webafra** [typeorm/typeorm#7125]
hello.
I have a suggestion to make the query easier.
Please pay attention to the following codes.

These samples are taken from the Lucid package.

select query :
```
const users = await User
  .query() // 👈now have access to all query builder methods
  .where('country_code', 'IN')
  .orWhereNull('country_code')
```

select and save query:
```
const user = await User.findOrFail(1)
user.last_login_at = DateTime.local() // Luxon dateTime is used

await user.save()
```

Most importantly, load relationships in a simple way:
```
const users = await User.query().with('posts')
```

```
const users = await User.query().withCount('posts')
```

```
const users = await User.query().withCount('posts', (query) => {
  query.where('isPublished', true)
})
```

and more ...
https://preview.adonisjs.com/guides/model-relations/introduction

please add this feature to TypeORM .

thanks.

**Comment by nebkat** [comment]
@webafra this is really just a question of the specific syntax used in the ORM. We can't change the syntax entirely because it will completely break support for existing users. If there are specific features you would like added you can submit proposals or pull requests, but a huge change like this unfortunately won't be possible.

**Comment by webafra** [comment]
@nebkat : A good change is always good :)

You can consider a separate section such as a queryBuilder that supports this mode.

I have a bit of a problem loading relationships conditionally, and that's why I made such an offer.
For example, if we want to use such code conditionally, can you help me? :

```
async testChats(filter) {

    let filterObject = {
      relations: ["chatgroup", "sender"],
      take: 2
    };

    if (filter.search) {
      if(typeof filter.search == "number") {
        filterObject['where'] = {
          id: filter.search
        }
      } else {
        filterObject['where'] = {
          name: filter.search
        }
      }
    }
    if (filter.status) {
      if(filter.status == "published") {
        filterObject['where'] = {
          status: 'published'
        }
      } else if(filter.status == "draft"){
        filterObject['where'] = {
          name: 'draft'
        }
      }
    }

    return  await this.chatsEntity.find(filterObject);
    console.log('chats is:', chats);
  }

```

this code very easy on Lucid ORM :)

**Comment by nebkat** [comment]
@webafra `find()` is only a convenience method, in the background it uses the [`SelectQueryBuilder`](https://typeorm.io/#/select-query-builder). Typically you would use something in the form of:

```ts
qb = this.chatsEntity.createQueryBuilder("chat");
if (filter.search)
    if (typeof filter.search == "number")
        qb.where({id: filter.search})
```

> A good change is always good :)
> You can consider a separate section such as a queryBuilder that supports this mode.

There has to be a very clear benefit in order to warrant completely changing the API. Managing multiple types of query builder would end up being very counterproductive.

**Comment by webafra** [comment]
> @webafra `find()` is only a convenience method, in the background it uses the [`SelectQueryBuilder`](https://typeorm.io/#/select-query-builder). Typically you would use something in the form of:
> 
> ```ts
> qb = this.chatsEntity.createQueryBuilder("chat");
> if (filter.search)
>     if (typeof filter.search == "number")
>         qb.where({id: filter.search})
> ```
> 
> > A good change is always good :)
> > You can consider a separate section such as a queryBuilder that supports this mode.
> 
> There has to be a very clear benefit in order to warrant completely changing the API. Managing multiple types of query builder would end up being very counterproductive.

Yes, I know this, but in this case,Eager loading does not work!

Can you add a method similar to Lucid methods ( .with('posts') Or .withCount('posts') ) to this section so that you do not need to use a join?

This method is really great.
Without Eager loading, queries become really heavy.

**Comment by rubiin** [comment]
the current syntax is easier to use, I don't think adding a new syntax will do any better rather create confusion

**Comment by nebkat** [comment]
I wasn't aware eager relations weren't loaded with query builder. If that is something you can require why not open a pull request with the necessary changes?

**Comment by webafra** [comment]
@nebkat Because I think this request has already been registered.
I think wrong?

Is it possible to use Eggerloading inside?
Do you want me to include this feature in a new application?

**Comment by nebkat** [comment]
If you would like to have eager loading in the query builder you can open up a new issue specifically for this, or implement it and submit a pull request.

I have understood your request but we need to have discussions about your specific proposal in its own issue so that we can properly gather feedback.

**Comment by imnotjames** [comment]
We aren't going to be using a separate ORM to implement TypeORM.

However, if there's a specific request or feature beyond that please feel free to open a new issue.
