### ISSUE TITLE
Migrations and Save

### ISSUE THREAD

**Issue by HimorriveL** [typeorm/typeorm#7126]
Issue type:
[x] bug report

Database system/driver:
[x] postgres

TypeORM version:
[x] 0.2.29

I have this code to create Migration:

`import` { MigrationInterface, QueryRunner, Table,TableColumn,TableForeignKey } from 'typeorm';

const table_name ='users';

export default class CreateUsers1606504267835
  implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: table_name,
        columns: [
          {
            name: 'id',
            type: 'uuid',
            isPrimary: true,
            generationStrategy: 'uuid',
            default: 'uuid_generate_v4()',
          },
          {
            name: 'ativo',
            type: 'boolean',
            default: 'true'
          },
          {
            name: 'cpf',
            type: 'varchar',
          },
          {
            name: 'rg',
            type: 'varchar',
          },
          {
            name: 'nome',
            type: 'varchar',
          },
          {
            name: 'ctps',
            type: 'varchar',
          },
          {
            name: 'senha',
            type: 'varchar',
          },
          {
            name: 'telefone',
            type: 'varchar',
          },
          {
            name: 'celular',
            type: 'varchar',
          },
          {
            name: 'cargo',
            type: 'varchar',
          },
          {
            name: 'salario',
            type: 'numeric(19,2)',
          },
          {
            name: 'created_at',
            type: 'timestamp',
            default: 'now()',
          },
          {
            name: 'updated_at',
            type: 'timestamp',
            default: 'now()',
          },
        ],
      }),
    `);`

    await queryRunner.addColumn(
      table_name,
      new TableColumn({
        name: 'stores_id',
        type: 'uuid',
        isNullable: true,
      }),
    );
    await queryRunner.createForeignKey(
      table_name,
      new TableForeignKey({
        name: 'UserStore',
        columnNames: ['stores_id'],
        referencedColumnNames: ['id'],
        referencedTableName: 'stores',
        onDelete: 'SET NULL',
        onUpdate: 'CASCADE'
      }),
    );

  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropForeignKey(
      table_name,
      'UserStore',
    );
    await queryRunner.dropColumn(table_name, 'stores_id');
    await queryRunner.dropTable(table_name);
  }

}`

in postbird have this code:

UserStore | FOREIGN KEY (stores_id) REFERENCES stores(id) | Delete

when I try request "getRepository().save(user);"
got this error:
"column \"store_id\" of relation \"users\" does not exist"

**Comment by nebkat** [comment]
Please note that this is not a general support forum. You can use [StackOverflow](http://stackoverflow.com) or the community [Slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) for questions. Also if you are making submissions here please make sure that your code is placed within code blocks so that it is readable.

**Comment by HimorriveL** [comment]
I did on ode blocks, but only 1/3 turn readable.
I Think its a bug, only because that I put here.

**Comment by nebkat** [comment]
You can read more about formatting here https://guides.github.com/features/mastering-markdown/

**Comment by HimorriveL** [comment]
yes nemkat I found yesterday,  I did wrong, my apologies
