### ISSUE TITLE
nvarchar columns are not detecting in Database

### ISSUE THREAD

**Issue by GLakshmiSravanthi** [typeorm/typeorm#7131]
### Issue Description

`nvarchar` columns was not detecting in database. when `schem:log` or `migration:generate` command is run the related columns were showing that there are changes in the nvarchar columns but there are no changes in the columns. 

**EXAMPLE** 

I have `Template Entity` with columns `name` , `description` and `card with type nvarchar with length max`

![image](https://user-images.githubusercontent.com/67416683/100749325-8a53d800-340a-11eb-8d2a-92448fa723d8.png)

For this I generated migration file with command `migration:generate` and run migration with command `migration:run` the tables were created in Database.

![image](https://user-images.githubusercontent.com/67416683/100750788-89bc4100-340c-11eb-90f9-ea427f4a5fce.png)

After this I wrote another Entity `UserToken`  with columns  `name` and `token` for this I generated migration file.

![image](https://user-images.githubusercontent.com/67416683/100759158-4ff03800-3416-11eb-88f2-29a34825ddcd.png)

There are no changes in the template entity, but card column in template table is dropped and add again. These were not happened for the other columns only for the `nvarchar type columns` .

### Steps to Reproduce

1. Write a entity having a column type nvarchar and length Max  
2. Run migration:genenrate command.
3. Run migration:run command make sure that the table is created in database.
4. Write another entity and run migration:genenrate or schema:log command  will show that there are changes in nvarchar column.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v12.18.3 | 
| Typescript version  | ^3.9.7 | 
| TypeORM version     | ^0.2.26 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [x] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by GLakshmiSravanthi** [comment]
it's my mistake i kept length as `Max` but it should be as `MAX` . After replacing lengths problem is solved

**Comment by stavalfi** [comment]
> it's my mistake i kept length as `Max` but it should be as `MAX` . After replacing lengths problem is solved

it fixed different bug as well:
when creating migrations with typeorm and one of the colums is nvarchar (or varchar) with size==='max' (small letters), it recreate the migrations over and ove ragain
