### ISSUE TITLE
Declare Driver Dependencies in package.json

### ISSUE THREAD

**Issue by brandon-leapyear** [typeorm/typeorm#7135]
## Issue Description

Yarn v2 uses Plug-n-Play, which means that it's starting to enforce packages needing to declare their dependencies. `typeorm` breaks because `pg` is declared as a dev dependency, but it's required at runtime.

https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L956
https://github.com/typeorm/typeorm/blob/master/src/platform/PlatformTools.ts#L78

The workaround is to add the following to `.yarnrc.yml`:
```yaml
packageExtensions:
  'typeorm@*':
    peerDependencies:
      'pg': '*'
```

But the better solution would be to list `pg` (and anything else typeorm needs to require) as a `peerDependency`.

### Expected Behavior

Running `yarn node dist/main.js` works, after compiling my typescript code using typeorm.

### Actual Behavior

Running our NestJS server gives us

```
[Nest] 2260   - 2020-12-02 1:34:48 AM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +4ms
DriverPackageNotInstalledError: Postgres package has not been found installed. Try to install it: npm install pg --save
    at new DriverPackageNotInstalledError (/root/src/~/.yarn_cache/typeorm-npm-0.2.29-c30de22860-c70f986138.zip/node_modules/typeorm/error/DriverPackageNotInstalledError.js:10:28)
    at PostgresDriver.loadDependencies (/root/src/~/.yarn_cache/typeorm-npm-0.2.29-c30de22860-c70f986138.zip/node_modules/typeorm/driver/postgres/PostgresDriver.js:966:19)
    at new PostgresDriver (/root/src/~/.yarn_cache/typeorm-npm-0.2.29-c30de22860-c70f986138.zip/node_modules/typeorm/driver/postgres/PostgresDriver.js:202:14)
    at DriverFactory.create (/root/src/~/.yarn_cache/typeorm-npm-0.2.29-c30de22860-c70f986138.zip/node_modules/typeorm/driver/DriverFactory.js:35:24)
    at new Connection (/root/src/~/.yarn_cache/typeorm-npm-0.2.29-c30de22860-c70f986138.zip/node_modules/typeorm/connection/Connection.js:53:59)
    at ConnectionManager.create (/root/src/~/.yarn_cache/typeorm-npm-0.2.29-c30de22860-c70f986138.zip/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at Object.<anonymous> (/root/src/~/.yarn_cache/typeorm-npm-0.2.29-c30de22860-c70f986138.zip/node_modules/typeorm/index.js:195:66)
    at step (/root/src/~/.yarn_cache/tslib-npm-1.14.1-102499115e-f44fe7f216.zip/node_modules/tslib/tslib.js:141:27)
    at Object.next (/root/src/~/.yarn_cache/tslib-npm-1.14.1-102499115e-f44fe7f216.zip/node_modules/tslib/tslib.js:122:57)
    at /root/src/~/.yarn_cache/tslib-npm-1.14.1-102499115e-f44fe7f216.zip/node_modules/tslib/tslib.js:115:75
```

### Steps to Reproduce

1. Use Yarn v2
2. Run project using typeorm

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | vX.Y.ZZZ | 
| Typescript version  | vX.Y.ZZZ | 
| TypeORM version     | vX.Y.ZZZ | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by liveFreeOrCode** [comment]
Yes please.  This is also a struggle with `aurora-data-api-pg`.  And I can get the above workaround to work for this driver unfortunately.  If anyone has any tips, I'm all ears


```
$ yarn typeorm migration:generate -n Test
Error during migration generation:
Error: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: /home/matt/dev/activations/packages/prescriptions-database/node_modules/typeorm-aurora-data-api-driver
Rejected candidate: /home/matt/dev/activations/packages/prescriptions-database/node_modules/typeorm-aurora-data-api-driver
Rejected candidate: /home/matt/dev/activations/packages/prescriptions-database/node_modules/typeorm-aurora-data-api-driver.js
Rejected candidate: /home/matt/dev/activations/packages/prescriptions-database/node_modules/typeorm-aurora-data-api-driver.json
Rejected candidate: /home/matt/dev/activations/packages/prescriptions-database/node_modules/typeorm-aurora-data-api-driver.node

Require stack:
- /home/matt/dev/activations/.yarn/$$virtual/typeorm-virtual-cf6d3857ce/0/cache/typeorm-npm-0.2.30-e06bbb99aa-172dfdb792.zip/node_modules/typeorm/platform/PlatformTools.js
- /home/matt/dev/activations/.yarn/$$virtual/typeorm-virtual-cf6d3857ce/0/cache/typeorm-npm-0.2.30-e06bbb99aa-172dfdb792.zip/node_modules/typeorm/driver/sqlserver/SqlServerDriver.js
- /home/matt/dev/activations/.yarn/$$virtual/typeorm-virtual-cf6d3857ce/0/cache/typeorm-npm-0.2.30-e06bbb99aa-172dfdb792.zip/node_modules/typeorm/migration/MigrationExecutor.js
- /home/matt/dev/activations/.yarn/$$virtual/typeorm-virtual-cf6d3857ce/0/cache/typeorm-npm-0.2.30-e06bbb99aa-172dfdb792.zip/node_modules/typeorm/connection/Connection.js
- /home/matt/dev/activations/.yarn/$$virtual/typeorm-virtual-cf6d3857ce/0/cache/typeorm-npm-0.2.30-e06bbb99aa-172dfdb792.zip/node_modules/typeorm/connection/ConnectionManager.js
- /home/matt/dev/activations/.yarn/$$virtual/typeorm-virtual-cf6d3857ce/0/cache/typeorm-npm-0.2.30-e06bbb99aa-172dfdb792.zip/node_modules/typeorm/index.js
- /home/matt/dev/activations/.yarn/$$virtual/typeorm-virtual-cf6d3857ce/0/cache/typeorm-npm-0.2.30-e06bbb99aa-172dfdb792.zip/node_modules/typeorm/commands/SchemaSyncCommand.js
- /home/matt/dev/activations/.yarn/$$virtual/typeorm-virtual-cf6d3857ce/0/cache/typeorm-npm-0.2.30-e06bbb99aa-172dfdb792.zip/node_modules/typeorm/cli.js
```

**Comment by kevin-lindsay-1** [comment]
I'm trying to find a workaround to this issue, but as it stands it's going to prevent me from being able to use `pnp`.

**Comment by brandon-leapyear** [comment]
Does the packageExtensions workaround above not work for you?

**Comment by kevin-lindsay-1** [comment]
My specific issue closer to what @liveFreeOrCode was experiencing, which is that I use `ts-node` like this from the docs: https://typeorm.io/#/migrations/running-and-reverting-migrations.

The issue I'm having is that I can't run `typeorm/cli.js` because it's in the cache, not in `node_modules`.

**Comment by kevin-lindsay-1** [comment]
I figured it out. My config for using typeorm's generation commands with yarn v2 looks like the following:
```
ts-node $(yarn bin typeorm) migration:run
```

**Comment by kevin-lindsay-1** [comment]
https://github.com/typeorm/typeorm/pull/7540

**Comment by KlausNie** [comment]
I had the same issue with `sqlite3` and `mongodb`. The workaround works for those as well!

**Comment by vjpr** [comment]
For pnpm crew:

_.pnpmfile.cjs_

```
  if (pkg.name === 'typeorm') {
    pkg.dependencies = {
      'pg': '*',
    }
  }
```

**Comment by imnotjames** [comment]
If we added this into the base typeorm package you'd be installing postgres and MySQL and sqlite and Hana and....

Unless I'm missing something here.

**Comment by kevin-lindsay-1** [comment]
@imnotjames I use PnP currently with both mysql and postgres and don't get any errors at runtime, as long as I explicitly declare the database driver package as a dependency in my application.

As for listing the type of dependencies, I'm pretty sure that Yarn v2 would expect the database driver(s) listed as `optionalDependencies`, not `peerDependencies`. `peer` would mean "always required by the app, but you need to bring it yourself", which isn't the case for the db drivers.

My +1 to this issue was in regards to the CLI working with PnP, because by default it references `node_modules`, which stops being used when using PnP.

**Comment by imnotjames** [comment]
Can you open a new issue in that case that's more specific towards Yarn pnp and the CLI?

**Comment by brandon-leapyear** [comment]
@imnotjames can you explain why this issue should be closed? typeorm still
doesnt list pg as an optionalDependency (you're right in that it shouldnt
be a peerDependency because you only want one driver, not all of them), and
I think this issue should stay open for just that part (and potentially
another issue for the cli)

**Comment by imnotjames** [comment]
`optionalDependencies` are also installed unless you request not to install optional.

We cannot use them for this or again everyone will install everything any time they install typeorm.

**Comment by brandon-leapyear** [comment]
I see. Can there at least be documentation for using typeorm with yarn 2,
then? I'll open a ticket in yarn for this.

**Comment by kevin-lindsay-1** [comment]
I question what yarn would even be able to really do without some kind of workflow change.

As described, optional dependencies are basically opt-out, so this "expected" behavior would be opt-in, right? Doesn't that mean you'd have to specifically state you want to install it, like with a normal `yarn add`?

What's the difference between an optional opt-in dependency and a completely different module?

**Comment by merceyz** [comment]
This is what optional peer dependencies is for https://yarnpkg.com/configuration/manifest#peerDependenciesMeta

**Comment by imnotjames** [comment]
The way to really fix this is to split the drivers packages.

That way, you install the drivers you need explicitly, then those drivers have explicit dependencies.

There's a few potential paths for that to happen - one of which is the rewrite experiment pleerock is doing.

**Comment by imnotjames** [comment]
> This is exactly what optional peer dependencies is for, all the driver packages should be declared as such so the package manager knows that it can't hoist typeorm away from the drivers. This isn't a PnP issue, it's a problem with `node_modules` as well https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies.
> 
> https://yarnpkg.com/configuration/manifest#peerDependenciesMeta
> https://pnpm.io/package_json#peerdependenciesmeta
> https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

Okay - so peer dependencies meta?  Can you open a PR with those changes?
