### ISSUE TITLE
Cannot read property 'joinColumns' of undefined

### ISSUE THREAD

**Issue by Bezlepkin** [typeorm/typeorm#7149]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] cordova
[ ] mongodb
[ ] mssql
[x ] mysql / mariadb
[ ] oracle
[] postgres
[ ] cockroachdb
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

**TypeORM version:**

[ ] latest
[ ] @next
[x] 0.2.29

**Steps to reproduce or a small repository showing the problem:**
I have two entities. "Page" and "Location". "Page" can have many "Location" (OneToMany). A " Location "can only have one"Page".
I need to get one record from the main table and all from the relate one.

PageEntity:
```
@Entity('page')
export class PageEntity {
  @PrimaryGeneratedColumn()
  id: number

  @Column('int', { default: 11 })
  user_id: number

  @OneToMany(() => LocationEntity, (location: LocationEntity) => { location.page })
  @JoinColumn({name: 'id'})
  location: LocationEntity[];
}
```

LocationEntity
```
@Entity('location')
export class LocationEntity {
  @PrimaryGeneratedColumn()
  id: number

  @Column({ type: 'enum', enum: entityType })
  entity_type: string

  @Column('int', { width: 11 })
  entity_id: number

  @ManyToOne(() => PageEntity, (page: PageEntity) => page.location)
  @JoinColumn({name: 'entity_id'})
  page: PageEntity;
}
```

PageService (method)
```
async getPage(id: string, user: UserEntity): Promise<PageRO> {
    return await this.pageRepository.createQueryBuilder('p')
    .leftJoinAndSelect('p.location', 'pl')
    .where('p.id = :id', {id: id})
    .getOne();
}
```

I get an error: TypeError: **Cannot read property 'joinColumns' of undefined**

**Comment by federicocoraglodino** [comment]
I have the same issue.

**Comment by federicocoraglodino** [comment]
I was able to fix this issue. You should try something like this:


```
@Entity('page')
export class PageEntity {
  @PrimaryGeneratedColumn()
  id: number

  @Column('int', { default: 11 })
  user_id: number

  @OneToMany(
   () => LocationEntity, location => { location.page })
  location: LocationEntity[];
}
```
```
@Entity('location')
export class LocationEntity {
....
  @ManyToOne(() => PageEntity, page => page.id)
  @JoinColumn({name: 'entity_id', referencedColumnName: 'id'})
  page: PageEntity;
 ....
}
```
@Bezlepkin Try the code above
