### ISSUE TITLE
Connecting to the database synchronously

### ISSUE THREAD

**Issue by BrainMaestro** [typeorm/typeorm#715]
Is it possible to connect to the database synchronously? For my app, there's no issue with the current asynchronous method, but I'm running into weird timing issues. I wouldn't want my app to run at all if the database is not ready, because it wouldn't make sense. Also, I would like to create a connection once and reuse it in separate places, but this doesn't seem to be officially supported.

The error message I get with the tests ```RepositoryNotFoundError: No repository for "Material" was found. Looks like this entity is not registered in current "default" connection?```

**Comment by pleerock** [comment]
> Is it possible to connect to the database synchronously? 

no, it does not make sense 

> I'm running into weird timing issues

you simply need to figure out your problems and get know how to properly handle all async processes in node apps

> Also, I would like to create a connection once and reuse it in separate places, but this doesn't seem to be officially supported.

you can create a `QueryRunner` which holds a single database connection and use it across the app. Use `connection.createQueryRunner()` for this purpose. And remember to release it once you done with it (using queryRunner.release method)

> RepositoryNotFoundError: No repository for "Material" was found. Looks like this entity is not registered in current "default" connection?

did you register your entity in "entity" section of connection config?

**Comment by BrainMaestro** [comment]
Yes the entity is registered. That error only occurs when running tests. For some reason it is not able to get a repository even though it's using the exact same connection options

To create a `QueryRunner`, I'll still need the connection which defeats the purpose.

You say it doesn't make sense to connect synchronously, can you say why? The database is critical to the application, so there shouldn't be a scenario where the app is running but the connection is not ready. At least that's what I think. Ideally, the connection is setup once at app startup. Why should it be synchronous then?

**Comment by pleerock** [comment]
> Yes the entity is registered. That error only occurs when running tests. For some reason it is not able to get a repository even though it's using the exact same connection options

how do you run them? check entity paths, maybe some configuration changes. debug to find a problem. The problem exactly in loading entities

> To create a QueryRunner, I'll still need the connection which defeats the purpose.

what do you call "connection" here? real database connections are only in query runners.

> Ideally, the connection is setup once at app startup.

right typeorm setups you connection pool once at app startup. it does not need to be synchronous to work this way.

**Comment by NoNameProvided** [comment]
> Yes the entity is registered.  

You have to register them from the **very same** path. Details here https://github.com/typeorm/typeorm/issues/420#issuecomment-307219380

**Comment by BrainMaestro** [comment]
@NoNameProvided looks like it's related. Thanks
