### ISSUE TITLE
Improve Tree Entities feature set (adding update and remove logic)

### ISSUE THREAD

**Issue by mateussilva92** [typeorm/typeorm#7155]
### The Problem

So, the **Tree Entities** are missing a lot of functionality. Namely they have not logic for update nor delete. Meaning that if make changes between the relation of the entities the changes are not reflected in the database.
This happens for any of the tree approach we use (closure table, nested sets and materialized paths).

### The Solution

Implement all the logic to update and delete any changes to the tree structure. This will require creating at least some functions for updating and, in the case of the **nested sets**, one for deleting in the tree subject executors.

This will also require additional changes to the main subject executor to allow the execution of updates for the **nested sets** in series instead of parallel like the other updates are done. The main reason for this change is that we need need to make sure that the changes are done one by one since a change in the tree could also affect other entities in the tree that are not directly connected and if we multiple updates at once it will screw things up.

Those are the two main changes.

### Additional Context

For additional context I would like to add some points for things might have changed or are just not introduced with this new feature.
- The closure junction table is now supporting the cascades on delete on all RDBMS except mssql, for mssql I added custom logic to have the same behaviour.
- Enable onDelete option for TreeParent in all RDBMS except for mssql because of [error 1785](https://support.microsoft.com/en-us/help/321843/error-message-1785-occurs-when-you-create-a-foreign-key-constraint-tha).
- In this development I did not add support for **composite keys** for the **closure table** model;
- **IMPORTANT**: This development also prevents the creation of more than one root entity for **nested sets** but throwing an error, I'm not sure that's the correct approach to take or if we should leave that responsibility to the user (that may cause problems with the update logic in case the user does not protect is code from multi root entities).

_Note:_
This feature will also fix issue #193, #2032, #2418, #3691, #3988, #4174, #4353, #5268 and #6118.
This feature is duplicated by #3556 for updating materialized-path tree repositories.

### Relevant Database Driver(s)

I'm not sure about which databases support Tree Entities, you guys can probably help me here.

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by duong-le** [comment]
Will this also closes #193?

**Comment by mateussilva92** [comment]
> Will this also close #193?

It will, adding it to the closing list, thanks.

**Comment by LuizHonorato** [comment]
Any prevision? This is a good feature!
