### ISSUE TITLE
ESM support in cli

### ISSUE THREAD

**Issue by zeakd** [typeorm/typeorm#7159]
### The Problem

**node 14** is now officially support ESM module, and **ts-node** is trying to support esm too. 

https://nodejs.org/api/esm.html
https://github.com/TypeStrong/ts-node/issues/1007

ESM module needs to set `"type": "module"` in package.json, but this option break typeorm cli because typeorm use `require` to import ts files 

https://github.com/typeorm/typeorm/blob/master/src/connection/ConnectionOptionsReader.ts#L110
https://github.com/typeorm/typeorm/blob/master/src/util/DirectoryExportedClassesLoader.ts#L41

### The Solution

use `import()` instead of `require()`
maybe package compiling environment needs to update.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nebkat** [comment]
All instances of `require()` could be replaced with a function in `PlatformTools` so that when the switch from `require()` to `import()` is made it is a single line change, or can be made version dependent. For now though we support all the way down to Node v10 so this change can't yet be made.

**Comment by cspotcode** [comment]
Here is how mocha supports both `require()` hooks and ESM hooks.
https://github.com/mochajs/mocha/blob/273dbbbf4c21debded604c2094591bdbcbed7705/lib/esm-utils.js#L11-L28

It's important for mocha to attempt `require()` first, in case there's a custom `require.extensions` hook installed.  It detects a special node error and switches to `import()`.

As far as I know, `import()` does not support `require.extensions`, so it's not true that you can use `import()` everywhere and get CommonJS support for free.  You still need to attempt `require()`.

Having said that, if you experiment and find out that I'm wrong, please let me know.  Perhaps my information is out-of-date.

**Comment by zeakd** [comment]
@cspotcode It looks good. can typeorm use this fallback in PlatformTools?

**Comment by cspotcode** [comment]
Do you have more context?  What is the goal?

**Comment by cspotcode** [comment]
Disregard my last comment; I thought this was in a different issue.

Are you asking if typeorm can use the same technique as mocha?  I think so yes.  But I don't know anything about platformtools, so I don't know what it tries to do.

**Comment by zeakd** [comment]
@cspotcode oh right sorry. i thought you are in typeorm

I'll try mocha way and maybe can make pr next week or new year

**Comment by glen-84** [comment]
> 
> 
> Here is how mocha supports both `require()` hooks and ESM hooks.
> https://github.com/mochajs/mocha/blob/273dbbbf4c21debded604c2094591bdbcbed7705/lib/esm-utils.js#L11-L28
> 
> It's important for mocha to attempt `require()` first, in case there's a custom `require.extensions` hook installed. It detects a special node error and switches to `import()`.
> 
> As far as I know, `import()` does not support `require.extensions`, so it's not true that you can use `import()` everywhere and get CommonJS support for free. You still need to attempt `require()`.
> 
> Having said that, if you experiment and find out that I'm wrong, please let me know. Perhaps my information is out-of-date.

@cspotcode,

`require.extensions` has been deprecated since Node.js v0.10.6 – is it really necessary to support that?

I think you could just [detect the package type](https://github.com/cfware/get-package-type) and conditionally use import or require.

**Comment by cspotcode** [comment]
`require.extensions` is essentially the `transformSource` hook for CommonJS.  It also affects resolution, so it's a little bit of the `resolve` hook too.

The age of its deprecation is brought up a lot.  I understand why, but it's the only way to do certain things.  If you want to do the equivalent of `transformSource` for CommonJS, you need to use `require.extensions`.

**Comment by glen-84** [comment]
@cspotcode,

I see. What type of libraries/projects are using `transformSource` / how common is its use?

Perhaps the best option would be to use `import` by default, and have an opt-out for those who may rely on the behaviour of `require.extensions`.

**Comment by cspotcode** [comment]
To get a sense for all the different `require.extensions` module loaders out there:
https://www.npmjs.com/package/interpret
The list above is extensive, so it will include some loaders that do not make much sense and some that do.

The big ones are things like ts-node, @babel/register, @swc/register, stuff like that.

**Comment by redplant3d** [comment]
Can you at least include a flag to configure this easily?

**Comment by GerkinDev** [comment]
https://github.com/typeorm/typeorm/blob/749511d981f6b9a1a08113b23e8779a91cda78f8/src/connection/ConnectionOptionsReader.ts#L111
For this one, a dynamic import can be AFAICT a drop-in replacement, since it is already in an async context and auto-support of cjs is induced by one of the possible extensions. It would worth to add support to `.mjs` extension though once migrating to ESM.
In one of my programs, I use ts-node to load `ts` files on the fly imported via dynamic imports. I don't remember where did I saw the piece of doc talking about this behavior but this is possible in cjs (not sure for ESM interop though).

https://github.com/typeorm/typeorm/blob/749511d981f6b9a1a08113b23e8779a91cda78f8/src/util/DirectoryExportedClassesLoader.ts#L36-L41
This one is a bit trickier since this method is called in multiple places, some of them being in a sync context.

I think I'm gonna fork and try to tweak a bit.

**Comment by Ginden** [comment]
About:

```
type Relation<T> = T;
```

I would suggest using `propertyName: T | null` in general for relations - it's possible that relation wasn't loaded.
