### ISSUE TITLE
TS1206 when decorate  separate function by @Transaction()

### ISSUE THREAD

**Issue by alexey2baranov** [typeorm/typeorm#7164]
### Expected Behavior

if would like to decorate any funciton (for example express route handler) by `@Transaction` decorator
```ts
@Transaction()
async function updateForemanRequest(req: Request, res: Response, @TransactionManager() em: EntityManager) {
   // code executed in transaction
}
```
### Actual Behavior
If I do this , I get TS1206 error Decorator are not valid hire

```
TS1206 error Decorator are not valid hire
```

### Steps to Reproduce
1. Write any function
2. Decorate it by @Transaction decorator

```typescript
@Transaction()
async function updateForemanRequest(req: Request, res: Response, @TransactionManager() em: EntityManager) {
   // code executed in transaction
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   linux       |
| Node.js version     | v15.0.1 |
| Typescript version  | v4.0.5 | 
| TypeORM version     | v0.2.29|

### Additional Context

I'm writing express application. Some of it's route handler should be executed into transaction. Each route handler is separate function. I want to decorate them by @Transaction()

### Relevant Database Driver(s)

  - [ ] `cockroachdb`
  - [ ] `cordova`
  - [ ] `expo`

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nebkat** [comment]
This is a TypeScript/decorators issue, nothing we can do here

**Comment by imnotjames** [comment]
This isn't a TypeORM issue.
