### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by ssslambda** [typeorm/typeorm#7169]
### The Problem

No stable release

### The Solution

Stable release, of course

### Considered Alternatives

I don't think there any alternatives for this case

### Additional Context

The only thing i would to did is to ask, but there not too much options, only Slack which i don't like (any many people don't), so first is suggestion about GitHub Disscusions, this repo really needed it yesterday.

Next, my question is... When TypeOrm become stable? 1.0? I know it is ready for production and all, but latest pined issues from 2018 is sounds bad to me, i need answers...

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nebkat** [comment]
The version number does not necessarily imply that it is not currently "stable", it just means that from version to version there may be some breaking changes, which is necessary as the project grows.

I also do not like Slack but it is the platform that is currently active, and general discussion should go there.

In terms of general progress, you can go to the issues page and read the "Future of TypeORM" issue. While I would also like to see more progress, this sort of post is completely useless. The 1.4k issues are indeed a problem, but adding one more will not help things.

If you'd like to help you can consider donating or contributing bug fixes and new features.
