### ISSUE TITLE
[Question] Subscriber Events using QueryBuilder Update

### ISSUE THREAD

**Issue by mitchell44** [typeorm/typeorm#717]
Hi,

Wondering if it is expected functionality for a subscriber, such as ``afterUpdate`` to be triggered on a Repository ``.save()`` method, but not to be triggered on a QueryBuilder ``.update()`` method?

Thanks!

**Comment by pleerock** [comment]
Yes. There are LOT OF THINGS HAPPENING in `save` method. 
QueryBuilder's `.update()` method is simple - it just updates entity within a single sql query. We can't afford same overhead as we do in `save` method.

**Comment by mitchell44** [comment]
Okay, thanks for the info.

 I am needing to use the ```afterUpdate``` subscriber, so I will need to use ```.save()```.

Is there anything I can use in the ```SaveOptions``` to allow ```where``` clauses and such, as I am using this for an update API endpoint, and it seems ```save()``` by default if there is nothing matching what is in the table, it will create a new one, and I only want it to update one or many records depending on the parameters passed in, and not create any new ones.

Thanks again.

**Comment by pleerock** [comment]
no there is no way to update by some property using `save` method. `save` method simply updates a single model. I suggest you to call manually methods you call in your subscribers for such specific use cases.

**Comment by mitchell44** [comment]
Do you think the ```.update()``` method work from Repository any better than the .```save()``` method in my case?

**Comment by pleerock** [comment]
I don't know your case. `update` within query builder should be used if you want to:

* make update based on special where statement
* make bulk update
* make it the fastest way

I assume you are using update within query builder because you want to achieve one or more of those three goals. Because otherwise you can use simply `save` method

**Comment by mitchell44** [comment]
Okay, thanks for the help.

Would there ever by any consideration into adding subscribers to querybuilder methods so that could also utilize those functions?

**Comment by pleerock** [comment]
I'll think about it.

**Comment by pleerock** [comment]
Closing as this is already implemented in `@next`.
