### ISSUE TITLE
Question: would it be valid to implement an extra option on find/findOne methods?

### ISSUE THREAD

**Issue by vcapretz** [typeorm/typeorm#718]
I mean, currently I have to use query builder to select just a few columns from my table, using the find methods on a specific repository returns all columns.

I think it would be nice to have a key on "options" for specifying the columns that I wish to select. 

Any thoughts?

**Comment by pleerock** [comment]
can you please provide code snippets on what you do right now and how you would like to do

**Comment by vcapretz** [comment]
currently if I run 
`const user = await userRepository.findOne({username: 'username'});`, I'll get one user with all the columns that this table has, if I wanted just one column, I would have to do:
```js
const user = await userRepository
     .createQueryBuilder('row')
     .select('row.username')
     .where('row.username = :name', {name: 'username})
     .getOne();
``` 

and I thought that if I used the options object on `findOne`, I could run something like this: 
`const user = await userRepository.findOne({username: 'username'}, {select: 'username'});`

**Comment by pleerock** [comment]
Okay this is a new feature and can be easily implemented as addition to `FindOptions`:

```ts
const user = await userRepository.findOne({
    select: ["username", "email", "photo"],
    where: {
        username: "Vitor Capretz"
    }
});
```

This is easy feature to implement, just take a look how `FindOneOptions` is used in the code. Let me know if you are interested in implementing it.

**Comment by BrainMaestro** [comment]
Hey @pleerock, if no one has picked this up, I would be interested in implementing it

**Comment by pleerock** [comment]
@BrainMaestro yes sure
