### ISSUE TITLE
Duplicate Primary key error on softRemove - many to many when row already deleted

### ISSUE THREAD

**Issue by TFByrd** [typeorm/typeorm#7182]
## Issue Description

If I softDelete a row within a relationship and then softRemove a entity with it's relations and a row in that relation has already been deleted it will throw a duplicate key error.

``softRemove(entityWithRelations)`` works fine if none of the related entities have been deleted

### Expected Behavior

To ignore any rows that have already been deleted

### Actual Behavior

Throws duplicate primary key error 
```
Duplicate entry 'postId-categoryId' for key 'PRIMARY'
```

### Steps to Reproduce

```typescript
class Category {
   @ManytoMany(
     (type) => Post,
     (Post) => Post.categories,
     { onDelete: 'cascade' } 
    )
    posts: Posts[]
}

class Post {
  @ManyToMany(
     (type) => Category,
     (Category) => Category.posts,
     { cascade: true } 
  )
  @JoinTable({ name: 'post_category' })
  categories: Category[]
}

let post = await postRepo.save()
const category = await categoryRepo.save({ posts: [post] })

await categoryRepo.softDelete(category.id)
post = await postRepo.findOneOrFail(post.id, { relations: ['categories'] }) 
await postRepo.softRemove(post)
// Throws duplicate primary key error 
// Duplicate entry 'postId-categoryId' for key 'PRIMARY' 
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      Windows    |
| Node.js version     | v12.16.1 | 
| Typescript version  | v3.7.5| 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by TFByrd** [comment]
You can clone this repo and you'll see the error in the console when you run it
[Reproducible Repo](https://github.com/TFByrd/typeorm_softRemove)

**Comment by TFByrd** [comment]
[Repo to Reproduce](https://github.com/TFByrd/typeorm_issue_7182)
Clone, npm I, npm run. the above repo to reproduce

**Comment by paulorsbrito** [comment]
Why whis was closed? What's the conclusions?

I"m facing this right now, except that i'm trying to save an entity (I bet `soft` operations is actually save operations). I can see that `save` first try to load all records from the relation, but ignores the softdeletes one, thus causing the PK error.
