### ISSUE TITLE
Postgres date column gets time added and converted using time zone

### ISSUE THREAD

**Issue by some-user123** [typeorm/typeorm#7184]
### Expected Behavior

I have a column of type "date" in Postgres (named "date").
 
If I SELECT this column in psql, the result shows simply a date, e.g.
```
    date
------------
 2020-12-12
(1 row)
```

If I use query builder to execute the same query and get the raw result, I'd expect the property "date" to be the exact same string `"2020-12-12"`.

### Actual Behavior

In fact I get a Date object:

```
query: SELECT d.date FROM "datetest" "d"
{ date: 2020-12-11T23:00:00.000Z }
```

1. That's not a date but date and time.
2. It's time zone converted. :-(

I understand that this the time zone issue could be solved by adding "with time zone" to timestamps etc. (cf. https://github.com/typeorm/typeorm/issues/2220#issuecomment-392315652). However "date with time zone" is not available in Postgres.

### Steps to Reproduce

```
# CREATE TABLE datetest (date date);
# INSERT INTO datetest (date) VALUES ('2020-12-12');
# SELECT date FROM datetest;
    date
------------
 2020-12-12
(1 row)
```

```typescript
import 'reflect-metadata'
import { createConnection } from 'typeorm'

createConnection({
  type: 'postgres',
  // ...
  logging: true,
})
  .then((connection) => {
    connection
      .createQueryBuilder()
      .select('d.date')
      .from('datetest', 'd')
      .getRawOne()
      .then((res) => {
        console.log(res)
      })
  })
  .catch((error) => console.log(error))
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Node.js version     | v14.5.0 | 
| Typescript version  | v4.1.2 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by Kristi47** [comment]
I think this is a high priority issue and needs to be solved.
Until that is fixed what's  how can I overcome this? 
I have an auto generated created_at column set as timestamptz but I want to group by date? How can I do that? 
Using raw query will not fix this

select created_at::date from users => will return a timezone aware date object

**Comment by falvees** [comment]
Managed to solve? how?
