### ISSUE TITLE
TypeORM fails with serverless-bundle

### ISSUE THREAD

**Issue by bduff9** [typeorm/typeorm#7186]
## Issue Description

I have a working serverless project deployed to Lambda, using [serverless-plugin-typescript](https://github.com/prisma-labs/serverless-plugin-typescript) to compile my typescript.  For a couple of reasons, especially bundle size (38Mb vs. 5Mb) I am trying to use [serverless-bundle](https://github.com/AnomalyInnovations/serverless-bundle) instead.

Making the necessary changes for this (installing serverless-bundle, updating tsconfig) causes the ormconfig.js file to not be found: `Failure: No connection options were found in any orm configuration files.`  It would seem typeorm is looking for this file in a different location, but cannot figure out where after trying various places in the output bundle.

I know I can load in a config through the env (not ideal but fine for right now since I have only one connection) so tried that and then it gets past this error but can never find the entities so fails: `No repository for \"MovieItem\" was found. Looks like this entity is not registered in current \"default\" connection?`

I don't see anyone on this repo or the serverless-bundle one using these together so unsure what I am missing or if there is a bug.  I am starting here since the errors I get are from typeorm, though I realize this could be a serverless-bundle issue since that is what starts this.  Primarily hoping someone could help point me in the direction of the cause so I can then address (here or there as appropriate).

My repo is [here](https://github.com/bduff9/movies-be) (`main` branch is working, `serverless-bundle` branch is the non-working one).

### Expected Behavior

I would expect my serverless function to continue working as it does with the serverless-plugin-typescript plugin.

### Actual Behavior

Included above in description.

### Steps to Reproduce

1. Clone repo locally, run `npm run setup`, then run `sls offline`
2. Go to `http://localhost:4000/local/graphql` to run the GQL Playground
3. Logs will show ormconfig not found error.
4. Uncomment TYPEORM env vars in serverless.yml and re-run `sls offline`.  Now, running any query in the playground shows the entity not found error.

I will note that I have confirmed this is not specific to serverless offline.  I get the same errors in lambda when I deploy, with the only exception being a slightly different error message on the missing ormconfig: `Cannot find module '/var/task/ormconfig.js'`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     MacOS Big Sur     |
| Node.js version     | v12.18.3 |
| Typescript version  | v4.1.3 |
| TypeORM version     | v0.2.29 |

### Additional Context

Nothing I can think of.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by danjsillva** [comment]
I have the same issue with Serverless and TypeORM. I suspect it is related to the fact that serverless-bundle concatenates all files into a single file making the `entities` path invalid. Anyway, following here...

**Comment by ifdouglas** [comment]
I think I my issue is the same.
I'm using nextjs + typeorm, deploying to Vercel and always get this:
<img width="671" alt="Screen Shot 2021-02-14 at 17 07 32" src="https://user-images.githubusercontent.com/69310124/107887766-290ab380-6ee7-11eb-8147-76995b46933e.png">

**Comment by bduff9** [comment]
@ifdouglas what's the actual error you get though?  There's a larger issue that TypeORM cannot currently be used at all with NextJS, so I would be surprised if this works locally for you. I also tried this recently using NextJS and Vercel, and ran into the issue so had to have one Vercel app for the NextJS frontend and one for my GQL backend.  There are a couple existing issues on this out there already, including this one: https://github.com/vercel/next.js/discussions/12254

Hope this helps!

**Comment by imnotjames** [comment]
My suggestion: Don't use an `ormconfig.js` if you're doing any sort of bundling.

The way we resolve the `ormconfig` is expecting a standard nodejs environment.

Instead, either `createConnection` yourself or create connection objects & manage the connection yourself.
