### ISSUE TITLE
Only run sync if table doesn't exist

### ISSUE THREAD

**Issue by ORESoftware** [typeorm/typeorm#7190]
## Feature Description
Only run sync if table doesn't exist, aka no ALTER statements, just create/insert.

### The Problem

The problem is we don't want to accidentally override tables in prod etc.  With this new mode, for each table, we only run a create, we never modify any existing tables, in short. 

For objects other than tables, that is TBD.

### The Solution

add another field to config:

```
 "synchronize": true,
 "createTablesOnly": true,
```

### Considered Alternatives
N/A

### Relevant Database Driver(s)
All

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
If you don't want to override tables in production you should use explicit migrations, shouldn't you?
