### ISSUE TITLE
Enable discussions in this repo

### ISSUE THREAD

**Issue by Telluu** [typeorm/typeorm#7201]
## Feature Description
Enable discussions so people can ask questions, share ideas etc. 

Discussions is the space for your community to have conversations, ask questions and post answers without opening issues.
### The Problem
The discussions in this repo are disabled. It would be a great way to ask questions and maybe even share ideas for people that don't want to set up Slack account and already have a GitHub account.

### The Solution
Go to repo settings and
1. On GitHub, navigate to the main page of the repository.
2. Under your repository name, click  Settings.
3. Under "Features", click Set up discussions.

### Additional Context
https://docs.github.com/en/free-pro-team@latest/discussions/quickstart

**Comment by imnotjames** [comment]
We might in the future but we won't be at this exact moment in time.
