### ISSUE TITLE
Support please mysql on duplicate key DO SOMETHING

### ISSUE THREAD

**Issue by AdventureGunter** [typeorm/typeorm#7204]
Please, your name consists "ORM" do this support through it, not through the ebaniy query builder, Ty, god bless  you

**Comment by imnotjames** [comment]
Hi there!  I am guessing you meant a swear word there in Russian.

We support this through the query builder because it's easily expressible through that.  It's not as easily expressible elsewhere.

If you're doing a `.save()` you'll need to handle this yourself in-application.
