### ISSUE TITLE
Could I custom a driver implementation  and register or replace it use typeorm api?

### ISSUE THREAD

**Issue by kurten** [typeorm/typeorm#7211]
### The Problem

For now, driver must implemented in typeorm. For some case, I want to custom driver implementation and replace that in typeorm driver map.

### The Solution
Maybe could change [DriverFactory](https://github.com/typeorm/typeorm/blob/master/src/driver/DriverFactory.ts#L29), drivers in a map and we can use an open method like register to set or replace driver.

### Relevant Database Driver(s)
- [ ] `add custom driver feature`

### Are you willing to resolve this issue by submitting a Pull Request?
- [ ] No, I don't have the time, although I believe I could do it if I had the time...

**Comment by Edgar-P-yan** [comment]
How about monkey-patching the `.create` method of `DriverFactory` class? :smiley: 
Though, i think that there should be some really good reason to do so, because usually the available drivers already do all the work that's needed :)

**Comment by kurten** [comment]
> As a rapid solution, how about monkey-patching the `.create` method of `DriverFactory` class? 😃
> Though, i think that there should be some really good reasons to do so, because usually the available drivers already do all the work that's needed :)

Well, we will design a mysql driver over grpc on serverless case. For developers, just use typeorm with no change.

**Comment by imnotjames** [comment]
duplicate of #2479
