### ISSUE TITLE
leftJoinAndSelect doesn't return array for ManyToOne / OneToMany

### ISSUE THREAD

**Issue by kkoomen** [typeorm/typeorm#7213]
Hi, I am having a `Post` entity and `PostFile` entity like so:

`Post`

```
@Entity('posts')
export class Post {
  @PrimaryGeneratedColumn({ unsigned: true })
  id: number;

  @Column({
    type: 'int',
    name: 'user_id',
    nullable: true,
    unsigned: true,
  })
  userId: number | null;

  @OneToMany(() => PostFile, (postFile) => postFile.post, { eager: true })
  attachments: PostFile[];
}
```

`PostFile`

```typescript
@Entity('post_files')
export class PostFile {
  @PrimaryGeneratedColumn({ unsigned: true })
  id: number;

  @Column({
    type: 'varchar',
    length: 255,
    name: 'file_path',
  })
  filePath: string; 

  @Column({
    type: 'int',
    name: 'post_id',
    nullable: true,
    unsigned: true,
  })
  postId: number | null;

  @ManyToOne(() => Post, (post) => post.attachments, { cascade: true, onDelete: CASCADE })
  @JoinColumn({ name: 'post_id' })
  post: Post;
}
```

Then I am running the following query:

```typescript
const post = await getRepository(Post)
  .createQueryBuilder('posts')
  .select('posts.*')
  .leftJoinAndSelect('posts.attachments', 'attachments')
  .where('posts.id = :id', { id: 209 })
  .getRawMany();
```

and the result is this:

```
[
  RowDataPacket {
    attachments_id: 150,
    attachments_file_path: 'https://via.placeholder.com/150',
    id: 209,
  }
]
```

but this is not correct. The result its attachments should be an array:

```
[
  RowDataPacket {
    attachments: [
      {
        id: 150,
        file_path: 'https://via.placeholder.com/150',
      }
    ]
    id: 209,
  }
]
```

Is this a bug? Or am I doing something wrong?

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | MacOS Big Sur 11.0.1 (20B29) |
| Node.js version     | v14.13.1 | 
| Typescript version  | v3.7.4 | 
| TypeORM version     | 0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by msabo1** [comment]
As you are using `getRawMany` I would say this is desired behaviour. `getRawMany` is used when you don't want query result to be mapped into existing entity and returns what SQL query returns mapped to an object. As SQL doesn't know for nesting and always return "flat object" it is mapped that way.
From [docs](https://typeorm.io/#/select-query-builder/getting-values-using-querybuilder)
`There are two types of results you can get using select query builder: entities or raw results. Most of the time, you need to select real entities from your database, for example, users. For this purpose, you use getOne and getMany. But sometimes you need to select some specific data, let's say the sum of all user photos. This data is not an entity, it's called raw data. To get raw data, you use getRawOne and getRawMany.`
So if you want nested variant you should use`getMany` instaed of `getRawMany` if there is no other reason (that is not show in this example you provided) to use it.

**Comment by kkoomen** [comment]
@msabo1 Okay, thanks for clarifying. I'll close it for now then.

**Comment by quannv** [comment]
I got the same problem when use the getOne()

```
 const item = this.tourrepository.createQueryBuilder('tours')
            .leftJoinAndSelect("tours.images", "image")
            .where({ id: id })
            .getOne();
```

and I check console log, the query will return  flat data, images can not be an Array, 
Please advise

**Comment by msabo1** [comment]
Try to use `leftJoinAndMapMany` istead of `leftJoinAndSelect`
