### ISSUE TITLE
How can I select `array_agg` in `typeorm` with `postgresql`?

### ISSUE THREAD

**Issue by zhaoyi0113** [typeorm/typeorm#7215]
I am using typeorm(0.2.29) in typescript project to connect to postresql 11. I have below query in sql which gives me expected results:

select "customerUuid", array_agg("siteUuid") from "SiteCustomer" where "customerUuid" in ('id1', 'id2') group by "customerUuid";

but when I use typeorm, it always returns empty array:

     queryRunner.manager.getRepository(SiteCustomer).
          .createQueryBuilder()
          .select('"customerUuid", array_agg("siteUuid")')
          .where('"customerUuid" IN (:customerUuids)', { customerUuids: customerUuids})
          .groupBy('"customerUuid"')
          .getMany();
how can I make typeorm work with array_agg in postgresql?

I have tried to use this `where`: `.where('"customerUuid" IN (:customerUuids)', { customerUuids: customerUuids})` but still not able to get the data.

**Comment by zieglar** [comment]
use `.select('customerUuid').addSelect('array_agg("siteUuid")')`

**Comment by Edgar-P-yan** [comment]
```ts
interface AggregatedSiteCustumer { ... }

queryRunner.manager.getRepository(SiteCustomer).
      .createQueryBuilder()
      .select([
            '"customerUuid" as "customerUuid"',
            // It's better to specify an alias explicitly, because the default one 
            // s implicit and may be unexpected
            'array_agg("siteUuid") as "aggregatedSiteUuids"', 
      ])
      // Note the triple-dot in :...
      .where('"customerUuid" IN (:...customerUuids)', { customerUuids: customerUuids})
      .groupBy('"customerUuid"')
      // .getMany() returns actual entities, instances of SiteCustomer,
      // in this case that is not what you need, because the result of the
      // query does not match the SiteCustomer class. Instead you can
      // use .getRawMany() which will return raw objects. Also, specifying
      // return type by hand-written interface (AggregatedSiteCustumer) when
      // using .getRawMany() is considered as best practice
      .getRawMany<AggregatedSiteCustumer>(); 
```

Also, i think the label `bug` is incorrect here, because TypeORM by now does not focus on database-specific features like `array_agg`.

Hope this helps :)

**Comment by zhaoyi0113** [comment]
Yes, change to `getRawMany` works. Thanks.
