### ISSUE TITLE
Generated migration misses column type on postgres

### ISSUE THREAD

**Issue by Seiikatsu** [typeorm/typeorm#7216]
## Issue Description
I have a project where i support multiple database systems (MySQL/MariaDB, PostgreSQL, SQLite). I use the migration API provided by typeorm to create my tables without writing any sql. It seems like there is a incompability if you create generated uuid columns. The migration works with MySQL/MariaDB and SQLite, but not with PostgreSQL. I had to use the type 'varchar' here, as MySQL/MariaDB and SQLite does not support the Type 'uuid' like PostgreSQL does.

### Expected Behavior
I would expect that typeorm generates valid SQL for all three systems.

### Actual Behavior
Typeorm generates working sql statements for MySQL / MariaDB and SQLite but not for PostgreSQL.
It fails with the message:
`syntax error at or near "NOT"`.

The generated SQL looks like this:
`CREATE TABLE "id_missing_type" ("id" NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_48515b889097ba57785db15f74d" PRIMARY KEY ("id"))`

It is obvious that the type for the column is missing.

### Steps to Reproduce
I created a repository to reproduce this issue: https://github.com/Seiikatsu/typeorm_missing_column_type_on_migration

Basically this column definition will fail:
`
new TableColumn({
	name: 'id',
	type: 'varchar',
	isPrimary: true,
	isGenerated: true,
	generationStrategy: 'uuid',
})
`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  5.9.14-arch1-1 |
| Node.js version     | v15.4.0 |
| TypeORM version     | v0.2.29 |

### Additional Context

I already looked into the code of typeorm and the problem seems to be in the implementation of PostgresQueryRunner#buildCreateColumnSql. As "this.connection.driver.createFullType(column);" is never called.
I don't know the internals of typeorm and therefore don't know why it is only called for non-generated columns or uuid columns.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Edgar-P-yan** [comment]
I think it does not work with postgres, because when you specify `{isGenerated: true, generationStrategy: 'uuid'}` typeorm assumes that the default value should be calculated with postgreses uuid_generate_v4() function, which returns uuid, not varchar. So when you set {type: 'varchar'} TypeORM gets confused :sweat_smile:  

In my opinion, the automatic migration code generation is somewhat useful only for development, because the algorithm for now is not clever enough to write such sql, that will be optimal, safe and without the risk of data loss. 
Also, it is technically impossible to generate such sql code that will work on all databases for 100%, as databases differ, so if you really want to go with sql generation, here is a workaround that may be helpful:

```ts
new TableColumn({
  name: 'id',
  type: isPostgres ? 'uuid' : 'varchar', // take the isPostgres from configuration
  isPrimary: true,
  isGenerated: true,
  generationStrategy: 'uuid'
})
```

I think this is the only way to go. Hope it helped :smile:

**Comment by Seiikatsu** [comment]
So either way I would need to remove the 'isGenerated' flag and rely on TypeORM to generate my PK's or make my migrations database specific. As I need to support multiple databases systems, I would like to not deal with any sql / database specific code. That's why I choose TypeORM in the first place.

Anyway this column table would work for all database types:
```
new TableColumn({
  name: 'id',
  type: 'varchar',
  isPrimary: true,
})
```
With that i would rely on `@PrimaryGeneratedColumn('uuid')` to generate my id. From what I've read in the docs, TypeORM will generate the uuid before a new entity is inserted in the database (even tho I am to stupid right now to find the page again). This does not happen, the generated SQL will look like this:
`INSERT INTO "post"("id") VALUES (DEFAULT) RETURNING "id"`.

I know this is not a support forum or anything like this, but it seems like there are general issues with uuid's in TypeORM.

**Comment by Edgar-P-yan** [comment]
One of the main advantages of UUIDs over auto-incrementing integers is that you can know the ID before even creating a record, so if TypeORM generated UUIDs on its own then developers would not be able to take advantage of UUID. Though, you can still set up a BeforeInsert hook (or Subscriptions, look what fits your needs better) where you generate a UUID and assign it to the `id` field.

Hope this helps :)
