### ISSUE TITLE
"Invalid regular expression: invalid group specifier name" error when passing options to repository or entity manager methods

### ISSUE THREAD

**Issue by sdserage** [typeorm/typeorm#7219]
## Issue Description
Using `expo-sqlite` as my driver for a React-Native Expo project. All methods of `createConnection().getRepository(ENTITY)`, `createConnection().createEntityManager()`, `getManager()`,  and `getRepository(ENTITY)` error with `Unhandled promise rejection: SyntaxError: Invalid regular expression: invalid group specifier name` if an options object is supplied to them.

Fails:
```typescript
const USERS = await connection.getRepository(User).find({ where: { name: 'Johnny Test' }});
console.log( USERS) // Throws error
```

Works:
```typescript
const USERS = await connection.getRepository(User).find();
console.log(USERS) // Successfully grabs a list of available users with my db
```

Obviously any data mutation type methods all fail as it is required to pass in options. I'm assuming that this could be an error with `expo-sqlite` itself but I can't find any similar issues anywhere. I'm new to TypeScript and React-Native so I apologize in advance if I'm not including enough data.

### Expected Behavior
```typescript
const connection = await createConnection({
    database: 'my.db',
    driver: require('expo-sqlite'),
    entities: [User]
    name: 'my.db.name',
    synchronize: true,
    type: 'expo',
});

const userRepo = connection.getRepository(User);
const user = await userRepo.findOne(1); // Finds user with id 1
await userRepo.save({ ...user, name: 'bob' }); // Changes the user with id 1's name to 'bob'
```

### Actual Behavior
```typescript
const connection = await createConnection({
    database: 'my.db',
    driver: require('expo-sqlite'),
    entities: [User]
    name: 'my.db.name',
    synchronize: true,
    type: 'expo',
});

const userRepo = connection.getRepository(User);
const user = await userRepo.findOne(1);
// Throws '[Unhandled promise rejection: SyntaxError: Invalid regular expression: invalid group specifier name]'
await userRepo.save({ ...user, name: 'bob' });
// Also throws '[Unhandled promise rejection: SyntaxError: Invalid regular expression: invalid group specifier name]'
```

### Steps to Reproduce

1. Set up expo project
2. `npm i -s typeorm reflect-metadata expo-sqlite`
3. Set up a connection:
```typescript
createConnection({
    database: 'my.db',
    driver: require('expo-sqlite'),
    entities: [User]
    name: 'my.db.name',
    synchronize: true,
    type: 'expo',
});
```
4. Use the described methods from above.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.8.0 |
| Typescript version  | v4.1.3 | 
| TypeORM version     | v0.2.29 |

### Additional Context

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Expo SQLite version  | v8.5.0 |

### Relevant Database Driver(s)
- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [x] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by Vluf** [comment]
Duplicate of https://github.com/typeorm/typeorm/issues/7026

**Comment by sdserage** [comment]
> Duplicate of #7026

@Vluf I'm new to submitting issues on open source projects, should I close my issue then? It looks like the bug is the same.

**Comment by vuki656** [comment]
@sdserage If its the same bug it would be good to close this one to reduce clutter.

**Comment by sdserage** [comment]
Closing duplicate issue.
