### ISSUE TITLE
Use "INSERT...RETURNING" in MariaDB.

### ISSUE THREAD

**Issue by come25136** [typeorm/typeorm#7235]
### The Problem

I want to use "INSERT...RETURNING" in MariaDB.
It can't be used with the current TypeORM.
https://mariadb.com/kb/en/insertreturning/

### The Solution

I want to get the primary id of the affected INSERT query using "ON DUPLICATE KEY".

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
What version is this available from?

**Comment by nix6839** [comment]
> INSERT ... RETURNING was added in MariaDB 10.5.0, and returns a resultset of the inserted rows.

From [Official document](https://mariadb.com/kb/en/insertreturning/)

**Comment by pleerock** [comment]
If underlying driver (e.g. mysql package that is used for mariadb) support this - feature is relatively easy to implement. Feel free to contribute
