### ISSUE TITLE
Error: Cannot build query because main alias is not set (call qb#from method)

### ISSUE THREAD

**Issue by pirouet** [typeorm/typeorm#7237]
## Issue Description

Performing some changes to the Oracle Driver to support packages and during test runs, I cam receiving the below exception but I cannot for the life of me see why. 

  1) custom cache provider
       should cache results with custom id and duration supplied:
     Error: Cannot build query because main alias is not set (call qb#from method)
      at SelectQueryBuilder.createSelectExpression (src/query-builder/SelectQueryBuilder.ts:1380:19)

Query being run is using the query builder with the following command:

```
        const users1 = await connection
            .createQueryBuilder(User, "users") 
            .where("users.isAdmin = :isAdmin", { isAdmin: false })
            .skip(1)
            .take(5)
            .cache("user_admins", 2000)
            .orderBy("users.id")
            .getMany();
        expect(users1.length).to.be.equal(1);
```

User class is simple and does not have a lot in it:

```
import {Entity} from "../../../../src/decorator/entity/Entity";
import {PrimaryGeneratedColumn} from "../../../../src/decorator/columns/PrimaryGeneratedColumn";
import {Column} from "../../../../src/decorator/columns/Column";

@Entity({
    name: "USERS",
})
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    isAdmin: boolean;

}
```

### Expected Behaviour

Expected behaviour is that the SQL query is constructed correctly

### Actual Behaviour

Exception being thrown is suggesting that an alias has not been set

```
Error: Cannot build query because main alias is not set (call qb#from method)
      at SelectQueryBuilder.createSelectExpression (src/query-builder/SelectQueryBuilder.ts:1380:19)
      at SelectQueryBuilder.getQuery (src/query-builder/SelectQueryBuilder.ts:56:21)
      at SelectQueryBuilder.QueryBuilder.getQueryAndParameters (src/query-builder/QueryBuilder.ts:408:28)
      at SelectQueryBuilder.<anonymous> (src/query-builder/SelectQueryBuilder.ts:2043:40)
```

### Steps to Reproduce

Use code found @ https://github.com/clouudsoftware/typeorm/tree/refactor/oracle-driver

npm run test on Oracle

1.
2.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Mac OS X         |
| Node.js version     | v14.15.3 | 
| Typescript version  | v4.1.3 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [x] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by pirouet** [comment]
Never mind, found the issue - it was my own fault :) 

Happy New Year folks!

**Comment by AlvinStefanus** [comment]
You need to explain what causes this and how to fix this. We people have the same problem as you and we do not know how to solve it. Please share.

**Comment by OSA413** [comment]
I'll leave a hint here that moved me from this error to another:

I changed
```
query.select(`"name"`)
        query.from(qb => {
```
to
```
query.select(qb => {
            qb.select(entry, "name");
```

Thought my problem may not look like OP's but this is the only place I found a somewhat related discussion about it.

**Comment by SemeaTech** [comment]
Pessoas de 2024 que estejam usando TypeORM com Nestjs e estejam com o mesmo problema, eu resolvi buscando a minha entidade antes de chamar o createQueryBuilder e passando o alias para ele também:

```js
const result = await connection
      .getRepository(Bands)
      .createQueryBuilder("bands")
      .where("bands.styles = :style", { style })
      .getRawMany();
```

O retorno da consulta será a instância da sua entidade
