### ISSUE TITLE
typeorm always drop and create columns with names Address and Location

### ISSUE THREAD

**Issue by foaudkajj** [typeorm/typeorm#7238]
## **Update**

I figured out that the problem is not related to renaming. I have removed the mentioned columns and add new one. The problem still exists.

```
query: SELECT * FROM "SiparisBotu"."INFORMATION_SCHEMA"."TABLES" WHERE "TABLE_NAME" = 'typeorm_metadata' AND "TABLE_SCHEMA" = SCHEMA_NAME()
query: ALTER TABLE "telegram_user" DROP COLUMN "TestColumn"
query: ALTER TABLE "telegram_user" ADD "TestColumn" nvarchar(30)
query: COMMIT
```

```
    @Column({ length: 30, nullable: true })
    TestColumn?: string;
```

## Issue Description

I am using the version **^0.2.29** of _typeorm_. I have a _Product_ class with _Location_ and _Address_ feilds. In my ormconfig.json file, _synchronize_ is true. I am using nestjs and whenever I run the app typeorm drop and adds the mentioned tow columns. As a result, I lose my data inside them.
Here is my _ormconfig.json_ file.
```
{
    "type": "mssql",
    "host": "........",
    "port": 1433,
    "username": "....",
    "password": ".......",
    "database": ".......",
    "synchronize": true,
    "logging": true,
    "entities": [
        "dist/**/*.js"
    ]
}
```
This is the class file.

```
import { Entity, Column, PrimaryColumn, OneToMany } from "typeorm";
import { Order } from "./Order";
import { Product } from "./Product";

@Entity()
export class TelegramUser {

    @PrimaryColumn()
    Id: number;

    @Column({ length: 30, nullable: true })
    Username?: string;

    @Column({ length: 30, nullable: true })
    FirstName?: string;

    @Column({ length: 30, nullable: true })
    LastName?: string;

    @Column({ length: 30, nullable: true })
    PhoneNumber?: string;

    @Column({ type: 'text', nullable: true })
    SelectedProducts?: string;

    @Column({ type: 'text', nullable: true })
    OrderDetails?: string;

    @Column({ length: 2000, nullable: true })
    Address?: string;             // The columns which is being drop and added everytime

    @Column({ length: 3000, nullable: true })
    Location?: string;             // The columns which is being drop and added everytime
    
    @OneToMany(() => Order, order => order.user, { nullable: true })
    Orders?: Promise<Order[]>;
    @OneToMany(() => Product, product => product.user, { nullable: true })
    Products?: Promise<Product[]>;
}
```

### Expected Behavior

Columns shouldn't be recreated every time.

### Actual Behavior

Columns are recreated after each application start and the data inside them are becoming null.

```
query: SELECT * FROM "SiparisBotu"."INFORMATION_SCHEMA"."TABLES" WHERE "TABLE_NAME" = 'typeorm_metadata' AND "TABLE_SCHEMA" = SCHEMA_NAME()
query: ALTER TABLE "telegram_user" DROP COLUMN "Address"
query: ALTER TABLE "telegram_user" DROP COLUMN "Location"
query: ALTER TABLE "telegram_user" ADD "Address" nvarchar(2000)
query: ALTER TABLE "telegram_user" ADD "Location" nvarchar(3000)
query: COMMIT
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Windows 10 Pro     |
| Node.js version     | v15.5.0 | 
| Typescript version  | ^4.0.5 | 
| TypeORM version     | ^0.2.29 | 

### Relevant Database Driver(s)

- [x] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nebkat** [comment]
Could it have something to do with the length of the columns? That is the only thing unique about `Address`/`Location`.

**Comment by foaudkajj** [comment]
I tried every possible thing. But, nothing worked.

**Comment by lflfm** [comment]
it shouldn't drop and create columns ever... so much danger for loss of data.
It should alter tables instead and, in cases an alter won't do; it should do the alter table by rename procedure (create table newshape etc; insert into new select stuff from old; drop old; alter newshape rename to old;)

**Comment by imnotjames** [comment]
TypeORM currently does no alters - only drop and recreate.  That's because synchronize is meant for testing purposes and that was the simplest to make it exactly migrate during testing.

**Comment by ctilley83** [comment]
> TypeORM currently does not alter for columns - only drop and recreate. That's because synchronize is meant for testing purposes and that was the simplest to make it exactly migrate during testing.

The behavior I'm seeing is that typeorm is dropping and recreating the column even if nothing has changed in the entity.  I didn't have this problem until I switched to mariadb. It should only perform the migration once after you alter/create a new column, not every time you restart the dev server as it's doing now.  I believe this is a bug for this specific database type in my case.
