### ISSUE TITLE
Not add new when using the method create and after that use all save

### ISSUE THREAD

**Issue by dominhnhien1997** [typeorm/typeorm#7243]
I use the create method to create a new object, then wait for the results to return and call the save method to save it to the database. But when I used it this way the save method failed but didn't send me an announcement. After I remove create and just use save, they work properly. I honestly don't understand why this is happening
My Code 
`const customer: Customer = await this.customerRepository.create({
        username,
        password,
        email,
        phone,
        provider_name,
        active: 0,
      });
      await this.customerRepository.save(customer);`

And then I fix it as follows
` const customer: Customer = await this.customerRepository.save({
        username,
        password,
        email,
        phone,
        provider_name,
        active: 0,
  });`
Thank you

**Comment by nebkat** [comment]
`create()` shouldn't be `await`ed, it returns the result instantly.

Please use the community [Slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) for general support questions!

**Comment by dominhnhien1997** [comment]
Dear @nebkat 
In fact, if I run it locally, this error doesn't happen. But when closed as docker, this error occurs

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
