### ISSUE TITLE
Postgres driver not using port from config

### ISSUE THREAD

**Issue by StickNitro** [typeorm/typeorm#725]
Hi, I have an application that will be deployed to the Google Cloud and use the Cloud SQL Postgres server.  I am trying to connect to this instance on my local machine to test everything before deploying but am unable to connect as the `port` specified in config is not being used.

My JSON config is:

`{
    "typeorm": {
        "name": "default",
        "type": "postgres",
        "host": "127.0.0.1",
        "port": 5433,
        "username": "MyStrengthCoach",
        "password": "*******",
        "database": "MyStrengthCoach"
    }
}`

I have a local instance of Postgres installed on my machine using port 5432, and I am trying to connect through the Google Cloud proxy which is listening on 5433.

When I run my application it always connects to my local instance and complains that a database does not exist. Can anyone advise what I am doing wrong?

**Comment by pleerock** [comment]
have you figure out solution for your issue? Because its totally not typeorm issue. TypeORM connects to a given port, I just checked it - run my postgres on different port and connect using typeorm to it. Im closing this issue. If you still have issues I need something concrete from you.
