### ISSUE TITLE
QueryRunner blocks all other transactions

### ISSUE THREAD

**Issue by adonisdoda** [typeorm/typeorm#7260]
## Issue Description

QueryRunner blocks my application when I request more than one connections for the same users, or when I stress with many users.
After this my application not receive more connections

 _Query runner already released. Cannot run queries anymore._ 

### Actual Behavior

I have an apllication with DDD layer, my app service layers use like this template
`
try {

            const { idUser} = req.params;

            await this.Uow.OpenConnection()

            let response = await this.EventService.SetFavorite(idUser);

            await this.Uow.Commit()

            return HttpResponse.Successfully(res, 200, { userId: idUser, eventId: idEvent, favorited: response })
        } catch (ex) {

            await this.Uow.Rollback()

            return HttpResponse.Error(res, ex?.message, ex?.codeEx, ex?.error)
        } finally {
            await this.Uow.CloseConnection()
        }`

Its work good, but I have one problem when I stress apllication...When I send many connections(GET or POST, open or not transactions) I get this error _Query runner already released. Cannot run queries anymore._ and simply blocks my application for others request(All requests after this, response 500 code).

I not understand because it behaves like that, since the I release all transactions in CloseConnection()...

Sometimes when the same user makes more than one connection then the application also has this behavior(And here is my problem)

My UOW instance make this, like docs -> 

`    

    async OpenConnection(): Promise<void> {

        const connection = getConnection();

        this.uow = connection.createQueryRunner();

        await this.uow.connect();

    }

    async CloseConnection(): Promise<void> {
        this.uow.release()
    }

    async EnableTransaction(): Promise<void> {
        await this.uow.startTransaction()
    }

    async Commit(): Promise<void> {
        if (this.uow?.isTransactionActive) {
            await this.uow.commitTransaction()
        }
    }

    async Rollback(): Promise<void> {
        if (this.uow?.isTransactionActive) {
            await this.uow.rollbackTransaction()
        }
    }

    async NotifyOperation(type: ENotifyType): Promise<void> {
        if (type == ENotifyType.write) {

            if (this.uow?.isTransactionActive === false) {
                await this.EnableTransaction()
            }

        }
    }

    `

**_Obs: Look, I create NotifyOperations for EnableTransaction ever when write opertions and call in all repositorys and him have the logic if need enable or not._**

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.
- [X] No, I wouldn't even know how to start.

**Comment by adonisdoda** [comment]
I discover my problem...QueryRunner not close connection, so users be connected and hit maxConnection database...How I close this connections when transactions end?

**Comment by adonisdoda** [comment]
I discover the real problem rs , when I instance a new QueryRunner a new connection is established after I released this connection is not closed and stay open with the database...It`s a big problem because when new users connect,ever new connections is stablished and hit the database...
And when I close queryRunner him close all the connections(stoping all other users )
I believe that typeOrm should close these connections in iddle after a certain time, or allow us to close connections one by one

**Comment by lybrus** [comment]
When are you creating `this.Uow` object? If it single object for all connections - you rewrite `uow` instance in `this.uow = connection.createQueryRunner();`

**Comment by adonisdoda** [comment]
Yeah, I realized that I'm rewrite this istance and create many connections with the database...
I'm test using a single instance(Creating `this.uow = connection.createQueryRunner();` in one single time ) and have problems when many users trying make requests..
Other question, when called `release()` this connections not close, continues in iddle connection with database

**Comment by lybrus** [comment]
You shouldn't want it =) Use transactions, active record or data mapper as described in documentation.

**Comment by lybrus** [comment]
@adonisdoda close this issue, please, if you don't need it.
