### ISSUE TITLE
fix: adapt the default TypeORM container behaviour for TypeDI 0.9.1 

### ISSUE THREAD

**Issue by NoNameProvided** [typeorm/typeorm#7267]
## Issue Description

Up until now when TypeDI found an unknown type it blindly attempted to create an instance of it. This behavior has been changed in 0.9.0 and now a `ServiceNotFoundError` is thrown. This new behavior conflicts with TypeORM expectations about TypeDI so the container handling logic needs updating.

### Expected Behavior

TypeORM understands the new behavior of TypeDI and handles errors accordingly. I see that the logic is in `src/container.ts` Two updates are needed, first the `fallback` option can be removed as TypeDI will raise an error instead of returning nothing if cannot initialize the requested resource. Second, we need to decide how to handle the new behavior of TypeDI. I see multiple options here:

- set the `fallbackOnErrors` to true by default
- or we need to register all TypeORM classes which can be injected before setting up the container (this adds a hard dependency on TypeDI in TypeORM

### Actual Behavior

TypeORM throws multiple `ServiceNotFoundError`s on startup. 

### Steps to Reproduce

The related issue has been reported on [typestack/typedi#173](https://github.com/typestack/typedi/issues/173).

```typescript
import { Container } from 'typedi';
import {  useContainer } from 'typeorm';

....
useContainer(Container);
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.5.0 | 
| Typescript version  | 4.1.3 | 
| TypeORM version     |0.2.29 | 

### Additional Context

n/a

### Relevant Database Driver(s)

none

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ShinteiMai** [comment]
Having the same problem, after updating to TypeDI 0.9.1 this error showed up when I'm compiling my typescript project. I'm downgrading my TypeDI to 0.8.0 to make this work

**Comment by glen-84** [comment]
@pleerock @AlexMesser – Are you able to provide input here? This is blocking updates to typedi.

**Comment by NoNameProvided** [comment]
In the meantime can someone verify that using `fallbackOnErrors` make things work?
```ts
import { createConnection, useContainer } from 'typeorm';
import { Container } from 'typedi';

useContainer(Container, { fallbackOnErrors: true } );
```

 I am not using TypeDI with TypeORM currently, so I cannot check.

**Comment by NoNameProvided** [comment]
I have released `typeorm-typedi-extensions@0.4.1` which allows setting a different container for TypeDI (check readme), however, I don't think this should solve all the errors. 

For that, all services which throw an error should be pre-registered. Can we get a list of those falling services? This way there is no need for modification in TypeORM.

**Comment by glen-84** [comment]
@NoNameProvided,

I've installed `typeorm-typedi-extensions@0.4.1` along with `typedi@0.10.0`, and I'm not seeing any errors. Please keep in mind that my application is in the very early stages of development, so there's not a lot of code yet. I'll let you know if and when I encounter any issues.

Thanks!

**Comment by NoNameProvided** [comment]
Thanks for the feedback! Anyone who is registered to this issue, please test and report back any failing services.

**Comment by ivan-abdulin** [comment]
Fixes the issue for me. Props to @NoNameProvided for his fix.
I've created a minimal test repo that verifies that 0.4.1 version solves the issue.
https://github.com/ivan-abdulin/typeorm-7267

**Comment by NoNameProvided** [comment]
Thanks for the feedback! I will go ahead and close this as solved.
