### ISSUE TITLE
typeorm returns first entity with findOne if undefined is given as the ID

### ISSUE THREAD

**Issue by fafamnzm** [typeorm/typeorm#7288]
## Issue Description

`using getManager().findOne(Entity, undefined)` or `Entity.findOne(undefined)` {when the Entity extends BaseEntity} will return the first entity

### Expected Behavior

When we query to find one entity using its Id, we expect to have an entity in return if and only if the Id match is found in the database and have `null` or `undefined` or `[]` an empty array or something to show that nothing was found

### Actual Behavior

when undefined is given as an Id, typeorm returns the first entity. This is extremely problematic ecpecially when  we query on a related entity using relationId and if nothing is saved, we expect to have null, but we get the first recorded entity in the corresponding table. 

And we cannot use `relation[]`  in graphql when we try to query on Types

```
// include the output in code tags like these!
```

### Steps to Reproduce

Create a User entity and an Account entity which extend BaseEntity and they should have a one to one relation. extend BaseEntity in order to be able to check the `User.findOne()`

Then create a User entity and try to query on Account using `Account.findOne(user.accountId)`

Or in general run `getManager.findOne(Userundefined)` or `getManager.findOne(User, null)`

you should see the first entity saved in the table while you expect to have a result indicating no such entity was found!

this is an issue with TypeORM and not postgres in general as the following line will result in an error before execution as it throws error if undefined is given instead of a valid uuid or a number depending on you id Type

```
select * from users where id = 'undefined'
select * from users where id = undefined
select * from users where id = 'null'
select * from users where id = null
```

1.
2.

```typescript
// insert code here
// first create a user then run
const user = await User.findOne(undefined)
console.log({user}) 
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    WIndown 10      |
| Node.js version     | v12.18.4 | 
| Typescript version  | v^4.1.2 | 
| TypeORM version     | v^0.2.29 | 
| pg version     |v^8.5.1|

### Additional Context

we need a validator for the undefined or a valid uuid and number type to fix it temporarily and dig deeper since I do not know what is going on under the hood of typeorm!

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ x ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ x ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by msabo1** [comment]
As `findOne` has multiple overloads, and it is possible to call `findOne(id)` but also `findOne(options)` for example. The actual check if what is passed is id is done by following code:
```typescript
const passedId = typeof idOrOptionsOrConditions === "string" || typeof idOrOptionsOrConditions === "number" || (idOrOptionsOrConditions as any) instanceof Date;
```
So if you pass `undefined` this will evaluate to `false` and you are not actually passing an id.

To bypass this you can use something like this:
```typescript
Account.findOne({where: {id: user.accountId}})
```

**Comment by fafamnzm** [comment]
thank you for your response. I thought it was like mongoose where ```findById(id)``` is the same as ```findOne({_id:id}) ```

This is an extremely dangerous bug! If it was not in development and in production, it could cost a well known company millions of dollars
I think we all can agree that 
```findOne()``` should return null or invalid input errors not exposing the first entity in db
there has to be a check for null and undefined in the validation

**Comment by msabo1** [comment]
I wouldn't consider this as bug. `fineOne` is not `findById` and as I said it has multiple overloads. It is exactly what I would expect it to be, a method like "regular" `find` but more efficient if you know there is going to be only one result. As most probably you want to search by id and it is most common situation, it is added as one option to avoid boilerplate code. Knowing that, passing `undefined` and `null` is something like gray area and you shouldn't just assume what is going to happen, you need to investigate it, but I personally would try to avoid situation where that values are passed and use something like I suggested before regardless of what is actually happening.
This is my personal opinion and I am not member of Typeorm team so don't consider this as official opinion.

**Comment by Kalhama** [comment]
This issue is duplicate and it's been already fixed in typeorm:next

Duplicate Issue: https://github.com/typeorm/typeorm/issues/2500
PR: https://github.com/typeorm/typeorm/pull/5905

---

It's good to see this being fixed. We stumbled onto this once during application security testing before production couple of years back. I think I did some digging and found similar issue to this where it was stated it was a feature rather than a bug after that I always used findOneOrFail.

It could have caused a production level security issue for us and probably is causing security issues for others.

**Comment by fafamnzm** [comment]
Thank you for your response and explanation and pointing out the duplication

**Comment by vmuresanu** [comment]
@Kalhama it's 2024 and unfortunately it still hasn't been fixed even though the issue is closed. Check the comment section - https://github.com/typeorm/typeorm/issues/2500#issuecomment-1953066829

**Comment by KGMIT** [comment]
Please fix this issue.

**Comment by SouhailXedits** [comment]
@fafamnzm Its's 2025, issue is closed but still facing the same problem!

**Comment by vmuresanu** [comment]
@SouhailXedits try to use with Equal

```typescript
import { Equal } from 'typeorm';

const result = await this._manager.findOne(StatusEntity, {
    where: { id: Equal(id) },
});
```
