### ISSUE TITLE
getRawOne returns RowDataPacket even if table is empty

### ISSUE THREAD

**Issue by musou1500** [typeorm/typeorm#7300]
## Issue Description

`selectQueryBuilder.getRawOne` returns `RowDataPacket { cnt: null }` if table is empty and selection includes MySQL function(such as `sum`).

### Expected Behavior

I expect `selectQueryBuilder.getRawOne` returns `null` or `undefined` in such situation.

### Actual Behavior

`selectQueryBuilder.getRawOne` returns `RowDataPacket { cnt: null }`.

```
// include the output in code tags like these!
```

### Steps to Reproduce

try following code.
I expect `getRawOne` returns null if `count` table is empty, but it returns `RowDataPacket { cnt: null }`.

```typescript
@Entity()
export class Count {
  @PrimaryGeneratedColumn()
  id: number;
}

// RowDataPacket { cnt: null }
console.log(
  await conn
    .getRepository(Count)
    .createQueryBuilder()
    .select(["sum(id) as cnt"])
    .getRawOne()
);
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  macOS 11.0.1        |
| Node.js version     | v14.15.3 | 
| Typescript version  | v4.1.3 | 
| TypeORM version     | v0.2.29 | 

### Additional Context

`selectQueryBuilder.getRawMany` behaves similarly in same situation.
it returns an array includes one element with `RowDataPacket { cnt: null }`.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
`getRawOne` returns the raw data from the underlying driver.  This is expected because it's what MySQL returns.
