### ISSUE TITLE
Reflect renaming of decorator in documentation

### ISSUE THREAD

**Issue by Sauermann** [typeorm/typeorm#7304]
### What was unclear or otherwise insufficient?

According to
https://github.com/typeorm/typeorm/blob/aea27866fdadfef9655362bb1ded749c054b97e3/CHANGELOG.md#L799
`@TransactionEntityManager` has been renamed.

This fact should be reflected in these two locations:
https://github.com/typeorm/typeorm/blob/7f7e4d53119506bdbb86999606707cd740859fe7/src/decorator/transaction/Transaction.ts#L13
https://github.com/typeorm/typeorm/blob/7f7e4d53119506bdbb86999606707cd740859fe7/src/decorator/transaction/Transaction.ts#L46

### Recommended Fix

Rename `@TransactionEntityManager` to `@TransactionManager` in the two indicated locations.

### Are you willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time, and I know how to start.

**Comment by Itsaadarsh** [comment]
Hello there @Sauermann , Thanks for pointing it out I'll start working on this issue right away.
