### ISSUE TITLE
Better docs?

### ISSUE THREAD

**Issue by Sparklytical** [typeorm/typeorm#7311]
## Feature Description
Better documentation on typeorm.io website.

### The Problem

The current framework that is getting used in website is rather lack luster. Has no light dark mode, no searching.

### The Solution

Shifting the docs to use Docusaurus - https://v2.docusaurus.io/

### Considered Alternatives

1. Gitbook (but it got lots of features in paid version)

### Additional Context

One can easily implement searching in it through Algolia, since it uses React, customizing every part of it is possible.

**Comment by Sparklytical** [comment]
https://sparklytical.gitbook.io/typeorm

I did this in gitbook for my convenience.

**Comment by imnotjames** [comment]
Thanks for the suggestion.

There's a number of other documentation issues open - some which also suggest search, and etc.  As such I'll be closing this one out.
