### ISSUE TITLE
Can't use better-sqlite3 on ManjaroLinux

### ISSUE THREAD

**Issue by evandikt** [typeorm/typeorm#7314]
## Issue Description

Hello everyone,

Here is my "bug", I develop my project on 2 different pc, one under linux and one under windows.

Under windows everything works as it should, under linux `typeorm` doesn't want to take the module `better-sqlite3`.

In my node_modules i got the build file :

![image](https://user-images.githubusercontent.com/10628316/105721140-8a60e780-5f24-11eb-86ab-ec9010080f54.png)

### Expected Behavior

Work with `better-sqlite3`

### Actual Behavior

( After a `yarn install` obviously )
```
(node:212472) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install better-sqlite3 --save
``` 

```typescript
   const options: ConnectionOptions = {
      type: "better-sqlite3",
      database: path.join(CWD, 'database', 'database.db'),
      // logging: true,
      dropSchema: true, // false on prod ...
      entities: [],
      migrations: []
    };

    this._connection = await createConnection(options);
```

### My Environment

Config
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.2.1
DISTRIB_CODENAME=Nibia
DISTRIB_DESCRIPTION="Manjaro Linux"
```
hostnamectl
```
         Icon name: computer-laptop
           Chassis: laptop
  Operating System: Manjaro Linux
            Kernel: Linux 5.9.16-1-MANJARO
      Architecture: x86-64
```
```
npm -v
6.14.10
```
```
node -v
v14.15.4
```

Deps
```
  "devDependencies": {
    "@types/body-parser": "^1.19.0",
    "@types/debug": "^4.1.5",
    "@types/express": "^4.17.11",
    "@types/node": "^14.14.20",
    "@types/yargs": "^15.0.12",
    "nodemon": "^2.0.7",
    "pkg": "^4.4.9",
    "ts-node": "^9.1.1",
    "typescript": "^4.1.3"
  },
  "dependencies": {
    "better-sqlite3": "^7.1.2",
    "body-parser": "^1.19.0",
    "debug": "^4.3.1",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "joi": "^17.3.0",
    "reflect-metadata": "^0.1.13",
    "tsyringe": "^4.4.0",
    "typeorm": "^0.2.30"
  },
```

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [x] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Are you trying to share the same binary between windows and linux?

I'm not having any issues with linux and bettersqlite3.

This seems like a local issue rather than one with TypeORM.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
