### ISSUE TITLE
auto increment start from 1 for each table 

### ISSUE THREAD

**Issue by hatemragab** [typeorm/typeorm#7319]
auto increment start from 1 for each table  
how to make autoincrement start from last id not from start like laravel do 
thanks

**Comment by alanpcs** [comment]
I would suggest to use an UUID in this case instead. 
auto increment IDs are meant to start from 1 for each table.

**Comment by nebkat** [comment]
Auto increment is entirely implemented by the SQL driver, but what exactly do you mean by "last id"?

**Comment by hatemragab** [comment]
In laravel when insert new user in users tabe it wi be with id 1 and second with id 2 what if in posts tabe if insert new post in posts table it will start from last id (2) and first post will be with id 3 because last id in users table is 2

**Comment by hood** [comment]
> In laravel when insert new user in users tabe it wi be with id 1 and second with id 2 what if in posts tabe if insert new post in posts table it will start from last id (2) and first post will be with id 3 because last id in users table is 2

I call bullshit on this.

**Comment by nebkat** [comment]
I don't think that is a good implementation - what happens if two IDs accidentally overlap? If you want that sort of behaviour you should have an `ids` table with an auto increment column and a one-to-one relation netween all other entities that need a unique id.
