### ISSUE TITLE
Insert / update entity

### ISSUE THREAD

**Issue by popovicidinu** [typeorm/typeorm#732]
Hi. 

First all of thanks for the great work on this project. I really like it.

I have a short question about the insert/update mechanism of the ORM. For the following function it says:

```
 /**
     * Saves a given entity in the database.
     * If entity does not exist in the database then inserts, otherwise updates.
     */
    save(entity: Entity, options?: SaveOptions): Promise<Entity>;
```

How does this work internally? Because for some reason, in my environment i'm always getting "duplicate entry key... " error, as it tries to insert every time, instead of update.

**Comment by pleerock** [comment]
When you save your entity it check if entity already exist in the database by your entity primary keys.
If it exists - it updates it. If it does not exist it inserts a new row. Provide a small code snippet of what you are doing and maybe I can help you

**Comment by popovicidinu** [comment]
I was under the impression checks are done in a slightly more complex way (similar to the Unit of Work from Doctrine). I'm working on an API with Nest framework + TypeORM that is used by a mobile app built with Ionic (Angular 2). 

The objects are defined in the same way in both apps, so I thought I could send a JSON with my object from one side, and persist it / update it on the other side. 

As an example: 

**1. Person entity** 
```
@Entity()
export class Person {
    @PrimaryGeneratedColumn('increment', {type: 'int', name: 'id'})
    private _id: number;

    @Column({name: 'first_name'})
    private _first_name: string;

    @Column({name: 'last_name'})
    private _last_name: string;

    @Column({name: 'email', unique: true} )
    private _email: string;

    @CreateDateColumn({name: 'created_at'})
    private _created_at: Date;

    @UpdateDateColumn({name: 'updated_at'})
    private _updated_at: Date;

    @ManyToMany(type => Skill, skill => skill.persons, {
        cascadeUpdate: true
    })
    @JoinTable({'name': 'person_skills'})
    private _skills: Skill[];
```

**2. Skill entity**

```

@Entity()
export class Skill {
    @PrimaryGeneratedColumn('increment', {type: 'int', name: 'id'})
    _id: number;

    @Column({ name: 'name', unique: true})
    _name: string;

    @ManyToMany(type => Person, person => person.skills, {
        cascadeUpdate: true // allow to update an album on photo save
    })
    _persons: Person[];
```

I have an API function that makes a PUT for a person JSON. The JSON looks like this: 

```
{
	"person": {
		"_id" : 1,
		"_first_name": "John",
		"_last_name": "Doe",
		"_email": "john.doe@email.com",
		"_skills": [
			{
				"_id": 1,
				"_name": "Ionic"		
			}
		]
	}
}
```

Interestingly enough, if I don't have the _id for both, it should try to run INSERT, right? And if they are present, it should UPDATE? 

I included the primary key in the JSON now (the "ID"), but I'm now facing another error: [ExceptionsHandler] Cannot read property 'joinColumns' of undefined.

**Comment by pleerock** [comment]
I can ask why do you mark your entity properties as `private`?

**Comment by pleerock** [comment]
> [ExceptionsHandler] Cannot read property 'joinColumns' of undefined.

can I get more info? On what line this error?

**Comment by popovicidinu** [comment]
I picked that up from other programming languages I'd say, because I prefer using get/set like this (C# style). I also think there's a tutorial on TypeScript about public/private/protected class members. ( https://www.typescriptlang.org/docs/handbook/classes.html )

```

    get first_name(): string {
        return this._first_name;
    }

    set first_name(value: string) {
        this._first_name = value;
    }

    get last_name(): string {
        return this._last_name;
    }

    set last_name(value: string) {
        this._last_name = value;
    }
``` 

The full output is: 

``` 
[Nest] 42536   - 2017-8-3 17:19:54   [ExceptionsHandler] Cannot read property 'joinColumns' of undefined
TypeError: Cannot read property 'joinColumns' of undefined
    at RelationIdLoader.<anonymous> (/Users/iulian/Development/GitzioApi/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:83:116)
    at step (/Users/iulian/Development/GitzioApi/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:32:23)
    at Object.next (/Users/iulian/Development/GitzioApi/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:13:53)
    at /Users/iulian/Development/GitzioApi/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/iulian/Development/GitzioApi/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:3:12)
    at /Users/iulian/Development/GitzioApi/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:55:93
    at Array.map (native)
    at RelationIdLoader.<anonymous> (/Users/iulian/Development/GitzioApi/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:55:54)
    at step (/Users/iulian/Development/GitzioApi/node_modules/typeorm/query-builder/relation-id/RelationIdLoader.js:32:23)

```

**Comment by pleerock** [comment]
Getters and setters aren't created because someone prefers such code style or someone likes to write extra code. You don't need java-style getter/setters for each property in TypeScript because there is a way to create getter/setters for any property any time. 

You have this error because second parameter in relation decorator must point inverse relation:

```ts
    @ManyToMany(type => Skill, skill => skill.persons, {
        cascadeUpdate: true
    })
```

Must be:

```ts
    @ManyToMany(type => Skill, skill => skill._persons, {
        cascadeUpdate: true
    })
```

I strongly recommend you to revisit your creating models approach.

**Comment by popovicidinu** [comment]
@pleerock Thanks. It seems to be working now, indeed. 

In terms of the getter/setter technique, as I said, I followed tutorials on TS for ES6, and it seems a lot of people are using / recommending this. Perhaps I'm mistaken. But I understand that the relation decorator wants the name of the field, and not the return from the getter.  

Thanks for the help!!

**Comment by pleerock** [comment]
> I followed tutorials on TS for ES6, and it seems a lot of people are using / recommending this

looks like tutorials/people don't know what they are doing.
