### ISSUE TITLE
Multiple update queryBuilder, success in PgAdmin4 but not in typeorm

### ISSUE THREAD

**Issue by jackykwandesign** [typeorm/typeorm#7320]
## Issue Description

Same query, work in PgAdmin4 but not in typeorm

### Expected Behavior
They should provide same result, or any other method that can do multiple updates are welcome

### Actual Behavior
Same query but different result, error occur in typeorm but not in PgAdmin4 

### Steps to Reproduce
This is my entity
```
@Entity()
export class EthTransaction extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({unique:true})
  txid: string;

  @Column()
  blockHeight: number;

  @Column()
  coin: string;

  @Column()
  fromAddress: string;

  @Column()
  toAddress: string;

  @Column()
  value: string;

  @Column({default:"new"})
  webhookStatus:string;

  @CreateDateColumn()
  createAt: Date;

  @UpdateDateColumn()
  updateAt: Date;
}
```
This is actually db
![eth_transaction_db](https://user-images.githubusercontent.com/46065771/105936550-dd56ae00-608e-11eb-953a-9d86bbcdd408.png)

I try to do multiple records update with single query, which update webhookStatus by an array of txid
I first try with typeorm
```
const queryBuilder = await getConnection()
.createQueryBuilder()
.update(EthTransaction)
.set({ webhookStatus: status })
.where("txid IN (:txids)", {txids:txids})
.execute()
```

It give me a query like this
```
queryBuilder [
  'UPDATE "eth_transaction" SET "webhookStatus" = $1, "updateAt" = CURRENT_TIMESTAMP WHERE "txid" IN ($2)',
  [
    'pending',
    [
      '0x8bef57e3ee1b35e4a02286fc4a21ddd8392f8e215685e275b9b65f4aac6a2219',
      '0x1074e795c79d7f2ffb749252421a61f69bab14cc80eed43e45ca89ac7c684a49'
    ]
  ]
]
```

And error comes
```
error QueryFailedError: could not determine data type of parameter $1
    at new QueryFailedError (/home/project/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at PostgresQueryRunner.<anonymous> (/home/project/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:247:31)
    at step (/home/project/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.throw (/home/project/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at rejected (/home/project/node_modules/typeorm/node_modules/tslib/tslib.js:113:69)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  length: 111,
  severity: 'ERROR',
  code: '42P18',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1469',
  routine: 'exec_parse_message',
  query: 'UPDATE "eth_transaction" SET "webhookStatus" = $2, "updateAt" = CURRENT_TIMESTAMP WHERE "txid" IN ($2)',
  parameters: [
    'pending',
    [
      '0x8bef57e3ee1b35e4a02286fc4a21ddd8392f8e215685e275b9b65f4aac6a2219',
      '0x1074e795c79d7f2ffb749252421a61f69bab14cc80eed43e45ca89ac7c684a49'
    ]
  ]
}
```

But when i do the same query in PgAdmin 4, it pass and did the job
```
UPDATE "eth_transaction" SET "webhookStatus" = 'pending', "updateAt" = CURRENT_TIMESTAMP WHERE "txid" IN ('0x8bef57e3ee1b35e4a02286fc4a21ddd8392f8e215685e275b9b65f4aac6a2219', '0x1074e795c79d7f2ffb749252421a61f69bab14cc80eed43e45ca89ac7c684a49');
```

### My Environment

```
Ubuntu 20.04
nodejs v12.19.0
typescript
nestjs 7.5.1
@nestjs/typeorm": "^7.1.5
typeorm": "^0.2.30
typescript": "^4.0.5
@typescript-eslint/eslint-plugin": "^4.6.1
@typescript-eslint/parser": "^4.6.1
```

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by jackykwandesign** [comment]
I found that, this should be the under laying driver issue of node-postgres

https://github.com/brianc/node-postgres/wiki/FAQ#11-how-do-i-build-a-where-foo-in--query-to-find-rows-matching-an-array-of-values

Also some discussion in here
https://stackoverflow.com/questions/10720420/node-postgres-how-to-execute-where-col-in-dynamic-value-list-query

The problem is, when we use IN statement, 
```
SELECT * FROM stooges WHERE name IN ($1),[dataArray]
```
the driver don't know how to parse the array objects into format of 
```
SELECT * FROM stooges WHERE name IN ($1, $2, $3)", ['larry', 'curly', 'moe'])
```
Some sample query on the above DB
```
const txids =     [
    '0x8bef57e3ee1b35e4a02286fc4a21ddd8392f8e215685e275b9b65f4aac6a2219',
    '0x1074e795c79d7f2ffb749252421a61f69bab14cc80eed43e45ca89ac7c684a49'
  ]
const res = await getConnection().query(`SELECT * from "eth_transaction" WHERE txid = ANY ($1);`,[txids]);
console.log("res", res)

const res2 = await getConnection().query(`SELECT * from "eth_transaction" WHERE txid IN ($1);`,[txids]);
console.log("res2", res2)
```
Result: 
```
res [
  {
    id: 666,
    txid: '0x8bef57e3ee1b35e4a02286fc4a21ddd8392f8e215685e275b9b65f4aac6a2219',
    blockHeight: 11730707,
    coin: 'USDT',
    value: '19500000000',
    fromAddress: '0xeC94c62A6CA7e0F47Da4E2cD63D8207266e8Ef7E',
    toAddress: '0x96Fd96cE6f736666b5E453C48cc97D5643358285',
    createAt: 2021-01-26T11:23:57.803Z,
    updateAt: 2021-01-27T03:02:35.620Z,
    webhookStatus: 'new'
  }
]
res2 []
```
I use the raw query with ANY to kill the task, and i think querybuilder will also able to do this as well, will test later

**Comment by jackykwandesign** [comment]
Raw query is working, only queryBuilder is not working
Also i replace the IN with ANY for the array-parsing issue of node-postgres

```
            const res = await getConnection().query(`UPDATE "eth_transaction" SET "webhookStatus" = $1, "updateAt" = CURRENT_TIMESTAMP WHERE txid = ANY ($2);`,[status, txids]);
            console.log("res", res)

res [ [], 1 ]
```

**Comment by asomethings** [comment]
```typescript
const queryBuilder = await getConnection()
  .createQueryBuilder()
  .update(EthTransaction)
  .set({ webhookStatus: status })
  .where("txid IN (:...txids)", {txids:txids})
  .execute()
```
You are trying to send array as an "array". You have to make it unpack through typeorm. Above example should work as expected.

**Comment by jackykwandesign** [comment]
> ```ts
> const queryBuilder = await getConnection()
>   .createQueryBuilder()
>   .update(EthTransaction)
>   .set({ webhookStatus: status })
>   .where("txid IN (:...txids)", {txids:txids})
>   .execute()
> ```
> 
> You are trying to send array as an "array". You have to make it unpack through typeorm. Above example should work as expected.

Thanks for you reply, you are correct. But i do think we need to add this in doc, for how to use array in Querybuilder and example for multiple updates with single query, or i just miss it ?

**Comment by asomethings** [comment]
@jackykwandesign It's actually in the [doc](https://typeorm.io/#select-query-builder/using-parameters-to-escape-data) although it's select but still it's an query builder so I think people will think it's compatible

**Comment by jackykwandesign** [comment]
> @jackykwandesign It's actually in the [doc](https://typeorm.io/#select-query-builder/using-parameters-to-escape-data) although it's select but still it's an query builder so I think people will think it's compatible

Thanks for your reminder
