### ISSUE TITLE
Not able save data using Repository

### ISSUE THREAD

**Issue by santu-git** [typeorm/typeorm#733]
When I am using `import "reflect-metadata";` as per your document I am getting following error.
Unexpected value 'LoginPage' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@component annotation.

When I am removing `import "reflect-metadata";`
Uncaught (in promise): [object SQLError]

```
Ionic Framework: 3.5.3
Ionic App Scripts: 2.0.2
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 7.8.0
```

**Comment by pleerock** [comment]
You must add this line into your backend (node) startpoint, not frontend.

**Comment by santu-git** [comment]
@pleerock
I could not get your point. can you please explain little bit.

**Comment by pleerock** [comment]
your issue is not typeorm related. Please ask ionic community on how to integrate typeorm with ionic. Error you provided is angular-related, why do you post here angular-related errors?
