### ISSUE TITLE
execution query time?!

### ISSUE THREAD

**Issue by n0byk** [typeorm/typeorm#7335]
Hi 4 all!
think its a good idea to get execution query time

**Comment by FlxAlbroscheit** [comment]
Maybe not exactly what you requested, but one could track the approximate execution time via a simple:
```
const start = Date.now();
// Execution of your TypeoORM query
const end = Date.now();
const executionTime = end - start;
```

**Comment by tomasstrejcek** [comment]
@FlxAlbroscheit thats just plain wrong :)
tldr using Date is inaccurate

@n0byk 
since node v8 we have https://nodejs.org/api/perf_hooks.html
some simple tutorial: https://blog.abelotech.com/posts/measure-execution-time-nodejs-javascript

```js
var start = new Date()
var hrstart = process.hrtime()
var simulateTime = 5

setTimeout(function (argument) {
  // execution time simulated with setTimeout function
  var end = new Date() - start,
    hrend = process.hrtime(hrstart)

  console.info('Execution time: %dms', end)
  console.info('Execution time (hr): %ds %dms', hrend[0], hrend[1] / 1000000)
}, simulateTime)
```

```
Execution time: 7ms
Execution time (hr): 0s 6.858948ms

Execution time: 6ms
Execution time (hr): 0s 6.285195ms
```

for quick dirty debugging `console.time(label)` and `console.timeEnd(label)` is also okay

**Comment by nuranaskarov** [comment]
```ts
console.time('getCars');
// query
console.time('getCars');
```

**Comment by nuranaskarov** [comment]
```ts
console.time('getCars');
// query
console.timeEnd('getCars');
```

**Comment by nuranaskarov** [comment]
```ts
console.time('cars');
const cars = await carsRepository.find({})
console.timeEnd('cars');
```

**Comment by alumni** [comment]
@dberardo-com It's the time needed for the library to execute a query (measured using JS Dates), it will not include the BeforeQuery/AfterQuery events or deserialization (which may or may not happen after that). You can check the implementation in `<Driver>QueryRunner.query` where `<Driver>` is the driver that you are using.
