### ISSUE TITLE
Can't resolve mongodb

### ISSUE THREAD

**Issue by vincaslt** [typeorm/typeorm#734]
I am trying to write a common files package for my 3 projects, and in it I want to have typeorm entities. In one of them, when I start my app I get: 
```
./~/language-exchange-commons/~/typeorm/entity-manager/MongoEntityManager.js
Module not found: Can't resolve 'mongodb' in 'C:\Users\Vincas\Desktop\language-exchange\web-main\node_modules\language-exchange-commons\node_modules\typeorm\entity-manager'
```

If I try to run common-files project, It runs successfully, but in the other project It doesn't. The thing is, that project does not even do anything with typeorm, it only imports it's entities, but doesn't connect to a database, and certainly not mongodb.

This is the code if it makes any clearer: https://github.com/vincaslt/language-exchange/tree/EnvFix

**Comment by pleerock** [comment]
make sure you have installed `mongodb` in node modules in a project where you execute typeorm

**Comment by vincaslt** [comment]
But why? I don't use it, and other projects that use the same common project, start just fine...

**Comment by vincaslt** [comment]
Worth mentioning probably, that the project in question is a front-end project, and is being transpiled with webpack ts-loader. I don't do connection to database, and I'm pretty sure I don't even use entities, but it so happens that those entities are in scope, as in, are a property of object, whose properties are being used.

Entities.UserModel is the interface that I use, but Entities.User is the entity itself.

**Comment by vincaslt** [comment]
Ok, so the problem was that it was being loaded in browser environment, restructuring solved the problem.
