### ISSUE TITLE
Establish a connection to MYSQL DB using Microsoft azure access token. 

### ISSUE THREAD

**Issue by PraveenMp** [typeorm/typeorm#7340]
### The Problem
Hi,

We don't have the option of connecting DB using the access token.  Azure provides a pretty cool library for receiving the access token using different ways of Azure Active Directory Authentication. (here https://www.npmjs.com/package/@azure/identity)
it's good to have a feature and currently supported by another library (tedious https://github.com/tediousjs/tedious).

Are there any plans to release this feature with typeorm.  

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [x] `sqljs`
- [x] `sqlserver`

**Comment by AlexMesser** [comment]
implemented in #7477

**Comment by PParamashiva** [comment]
@AlexMesser Cool.. Thank you Bro :)
