### ISSUE TITLE
Add hidden classes to the index.ts to allow its usage

### ISSUE THREAD

**Issue by Corus84** [typeorm/typeorm#7345]
## Feature Description
Add hidden classes to the index.ts to allow its usage

### Issue type:
[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

### The Problem
I'm extending the SelectQueryBuilder in my project to create a custom query builder and add extra behavior to the joins and selects. All was going well and I see very useful typeorm classes like JoinAttribute or QueryBuilderUtils (as an example). The problem is these classes and others have not been added to the index.ts and I can't use them.

Is there a reason for it?

### The Solution
Add missing classes to the index.ts file of the project to allow its usage.

### Considered Alternatives
Import them using complete reference path, ie:
import { Alias } from 'typeorm/query-builder/Alias';
import { JoinAttribute } from 'typeorm/query-builder/JoinAttribute';

### Are you willing to resolve this issue by submitting a Pull Request?
- [X] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

I can do it because it's just add the references to the classes in the index.ts, but I think I can't just simply add all the classes. Maybe a discussion must be done first to decide the list of "exportable" clases. Or maybe we can just add all the classes.

Greetings.

**Comment by imnotjames** [comment]
We export loads of the classes already.  If you need some, add them.  This isn't really an actionable issue, though.  We don't export everything because many of the classes are for internal representations of data.
