### ISSUE TITLE
Add parent class for all errors

### ISSUE THREAD

**Issue by silveoj** [typeorm/typeorm#7348]
Is there possibility/sense to add one parent class for all errors?

Now all errors extend standard JS `Error`
https://github.com/typeorm/typeorm/tree/master/src/error
`export class EntityColumnNotFound extends Error {`

I see it `export class EntityColumnNotFound extends MyParentError {` and then `export class MyParentError extends Error {`

It will handy to catch/filter/detect errors from DB. And do something, for example show one common message for users about DB error, without any details.

For example, Sequelize has `DatabaseError` class https://sequelize.org/master/class/lib/errors/database-error.js~DatabaseError.html

Thanks.

**Comment by hood** [comment]
I could implement this easily if I get the green light from a maintainer. Let's wait and see.
