### ISSUE TITLE
Find filtered by Date seems to aggregate results

### ISSUE THREAD

**Issue by jonathanhublo** [typeorm/typeorm#7353]
## Issue Description

Hi,

So I have this request:

```typescript
// Those are Luxon dates
const dateMin = DateTime.local().minus({ minutes: nbMinutes }).toJSDate()
const dateMax = DateTime.local().toJSDate()

await getRepository(Model).find({
    where: {
      x: someId,
      createdAt: Between(dateMin, dateMax),
    },
  })
```

Logging the SQL request produce something like that:

```sql
SELECT "Model"."id"        AS "Model_id",
       "Model"."x"         AS "Model_x",
       "Model"."y"         AS "Model_y",
       "Model"."createdAt" AS "Model_createdAt",
       "Model"."updatedAt" AS "Model_updatedAt"
FROM "model" "Model"
WHERE "Model"."x" = $1
  AND "Model"."createdAt" BETWEEN $2 AND $3 -- PARAMETERS: [153,"2021-02-08T09:59:28.426Z","2021-02-08T10:09:28.427Z"]
```

### Expected Behavior

It should return all the elements corresponding to the request.
Running the SQL directly returns all the elements.

### Actual Behavior

It always returns 1 element.
I'm running my tests so I know there are more (I actually insert 100 elements).

### Steps to Reproduce

The above should be enough with this model:

```typescript
import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm'

@Entity('model')
export class Model {
  @PrimaryGeneratedColumn()
  id!: number

  @Column({ name: 'x' })
  x!: number

  @Column({ name: 'y' })
  y!: number

  @CreateDateColumn({ type: 'timestamp' })
  createdAt!: Date

  @UpdateDateColumn({ type: 'timestamp' })
  updatedAt!: Date
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | OSX  11.2 |
| Node.js version     | v14.15.4 |
| Typescript version  | v4.1.3 |
| TypeORM version     | v0.2.30 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by mvanveen82** [comment]
I have the same issue, but with a {type: 'date'} column. Postgres returns only 1 row through Typeorm. It does not matter if I use a repository or the querybuilder. The only way I do get more results if I use entityManager.query, however it is a pain to cast to entities and defeats the purpose of a orm.

OSX 11.1
Node 15.6.0
Typescript 3.4.5
Nestjs 7.4.4
Typeorm 0.2.28

**Comment by mvanveen82** [comment]
Through Gitter someone helped me find my problem. As I had the visitdate as a primary column, It took only the first match of the query, as there should be only one, it being a primary column.
Making the ManyToOne primary aswell solved my issue

**Comment by imnotjames** [comment]
I cannot replicate this issue with the provided information.

Please create either a unit test that exhibits this issue or a repository with exact information on how to replicate.

Once you do so please reopen the issue.
