### ISSUE TITLE
auto delete table data when i have two same table name 

### ISSUE THREAD

**Issue by zhiyongsun** [typeorm/typeorm#7359]
## Issue Description
I found when i debug my new project . 
i got two some table name 
typeorm would create a table will two tables columns  and delete original table's data ( i saw it with navicat for mysql)
version: 0.2.30

### Actual Behavior

```
// include the output in code tags like these!
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.15.1| 
| Typescript version  | 3.9.7| 
| TypeORM version     |0.2.30 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
This is incredibly vague as to what's happening.

If you mean that the `synchronize` development helper creates new columns and deletes old columns - yes, that's indeed what it does and how it works.

This needs more information if you think it's actually a bug.  If you add more information such as how to replicate the problem please re-open this issue.
