### ISSUE TITLE
ClosureEntity should set (composite) primary/unique key in the closure table 

### ISSUE THREAD

**Issue by mdziekon** [typeorm/typeorm#736]
TypeORM Version: "0.1.0-alpha.33"

When working with closure tables, each "path" from one node to another should occur only once - there should be only one direct connection between A (parent) and B (child) in the database. This can be achieved with both Unique composite key and Primary composite key (which is also unique in most DBs) set on both ``ancestor`` and ``descendant``.

It appears that TypeORM does not create this sort of key, which allows us to create duplicated paths (and in result may lead to broken graphs).

In case this is left intentional (but I highly doubt there's a usecase for that), please add this as an option, as currently there's no way to control that thing except for custom written post-schema-sync scripts.

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.41`. You can try it via `npm i typeorm@next`.
