### ISSUE TITLE
When found error is impossible!

### ISSUE THREAD

**Issue by webafra** [typeorm/typeorm#7365]
hi.

When found error is impossible!

![image](https://user-images.githubusercontent.com/8689072/107616275-fd779700-6c62-11eb-9fb1-0126802da1a7.png)

Unfortunately, TypeOrm is very poor at displaying errors.
For example, in the image below, ‌ error is very vague:
1- Which table is this error related to?
2. Which column of the table is this error related to?

If the number of tables is large, finding this error will be catastrophic.

Please help me how to find this error.
Thanks

**Comment by leleofg** [comment]
how did this error occur? explain with more details and if possible show steps to reproduce

**Comment by webafra** [comment]
@leleofg : The project is done as a team and after updating the project and adding database files, this error occurred.

Now I do not know which file the error is from.

**Comment by imnotjames** [comment]
>  1- Which table is this error related to?

We don't really know - this is an error from the database

>  2. Which column of the table is this error related to?

Again, we don't know.  This error is generated from MySQL and then surfaced up.  The index is listed there, you can look that up in your database.

**Comment by imnotjames** [comment]
We can't change much about how your error handling works, but the index listed there is very likely unique in your database.  But the error is from the server, and the handler is yours.
