### ISSUE TITLE
Quoted parameters don't work

### ISSUE THREAD

**Issue by ptrkcsk** [typeorm/typeorm#7368]
## Issue Description

The docs for [Advanced Find Options](https://typeorm.io/#/find-options/advanced-options) specify how to parameterize a raw find statement:

> If you need to provide user input, you should not include the user input directly in your query as this may create a SQL injection vulnerability. Instead, you can use the second argument of the `Raw` function to provide a list of parameters to bind to the query.
>
> ```ts
> import {Raw} from "typeorm";
> 
> const loadedPosts = await connection.getRepository(Post).find({
>     currentDate: Raw(alias =>`${alias} > ':date'`, { date: "2020-10-06" })
> });
> ```

In the example above, `':date'` (surrounded with quotes) does not work, but `:date` (not surrounded with quotes) does.

I'm not sure if this an error in the documentation or a bug in TypeORM.

### Expected Behavior

I expect parameterized raw SQL statement to work as described in the docs.

### Actual Behavior

Parameter interpolation does not work as described in the docs:

```
QueryFailedError: bind message supplies 1 parameters, but prepared statement "" requires 0
    at new QueryFailedError (/Users/patrikcsak/Dev/typeorm-point/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/Users/patrikcsak/Dev/typeorm-point/src/driver/postgres/PostgresQueryRunner.ts:228:19)
    at step (/Users/patrikcsak/Dev/typeorm-point/node_modules/tslib/tslib.js:141:27)
    at Object.throw (/Users/patrikcsak/Dev/typeorm-point/node_modules/tslib/tslib.js:122:57)
    at rejected (/Users/patrikcsak/Dev/typeorm-point/node_modules/tslib/tslib.js:113:69)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  length: 137,
  severity: 'ERROR',
  code: '08P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1544',
  routine: 'exec_bind_message',
  query: `SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User"."age" AS "User_age" FROM "user" "User" WHERE "User"."firstName" = '$1' LIMIT 1`,
  parameters: [ 'Timber' ]
}
```

### Steps to Reproduce

1. Clone [this repo](https://github.com/ptrkcsk/typeorm-raw-find), which is a simple TypeORM project created with `typeorm init`
1. Follow instructions in the repo's readme

### My Environment

| Dependency          | Version       |
| ---                 | ---           |
| Operating System    | macOS 11.2.1  |
| Node.js version     | v15.8.0       | 
| Typescript version  | v3.3.3333     |
| TypeORM version     | v0.2.31       |

### Relevant Database Driver(s)

- [x] `postgres`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by imnotjames** [comment]
that's an issue in the docs.

**Comment by almahdi-chihaoui** [comment]
is this issue fixed?

**Comment by imnotjames** [comment]
I updated the docs to not have an incorrect statement, so yes.
