### ISSUE TITLE
rowCount is not returned for INSERT queries in Postgres

### ISSUE THREAD

**Issue by yunyu** [typeorm/typeorm#7369]
## Issue Description

  The `rowCount` is not returned for INSERT queries under `PostgresQueryRunner`

### Expected Behavior

`rowCount` should be returned for INSERT queries, like https://node-postgres.com/api/result (see https://github.com/brianc/node-postgres/issues/121#issuecomment-5001936)

### Actual Behavior

`rowCount` is not returned if the command is `INSERT`: https://github.com/typeorm/typeorm/blob/5a3f9ff3d6ff5ec1bf704c836bef5a7529ff7f5a/src/driver/postgres/PostgresQueryRunner.ts#L217

### Steps to Reproduce

Suppose you want to upsert into a table that has a single unique primary key `pk`:

```ts
const insertResult = await connection.query(`INSERT INTO my_table VALUES($1) ON CONFLICT DO NOTHING`, [pk]);
```

It is impossible to tell whether or not there was a conflict and the row was successfully inserted.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Debian 10 |
| Node.js version     | v14.15.5 | 
| Typescript version  | v4.1.3 | 
| TypeORM version     | v0.2.31 | 

### Additional Context

N/A

### Relevant Database Driver(s)

- [x] `postgres`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] No, I don't have the time, although I believe I could do it if I had the time...

**Comment by imnotjames** [comment]
`queryRunner.query` has a new option to get back a structured response.  If you use that you will get back the row count in that structured response.

In the future this will probably become the default return value from `queryRunner.query`.

**Comment by Yuval-Peled** [comment]
@imnotjames Thanks for the response. I looked at `typeorm.io` and could not find the API documentation for `queryRunner.query` to see how to use the new option. I also tried looking at the Typescript definitions but could not see where it was. Could you kindly point me to the documentation for this new feature? Thanks

**Comment by imnotjames** [comment]
It's not live yet.  It will be in the next release.

**Comment by Yuval-Peled** [comment]
@imnotjames Thanks for the quick response. After it is merged, where will the documentation be? I must have missed the "raw query" documentation at `typeorm.io`, but I really can't find it. 
Thank you
