### ISSUE TITLE
UpdateResult#affected always returning undefined in SQLite

### ISSUE THREAD

**Issue by sangwoo-98** [typeorm/typeorm#7374]
## Issue Description

`UpdateResult.affected` is always returning `undefined` when used with SQLite In-memory database.
While unit-testing service code, it worked fine with MySQL and returned the exact number of affected rows after executing UPDATE query.   

But my unit test codes use SQLite instead of MySQL, and when using SQLite, `UpdateResult` is always returning `undefined`, although the columns on the table are actually updated.

### Expected Behavior

`UpdateResult#affected` should return exact number of affected rows after executing UPDATE query.

### Actual Behavior

Always returns `undefined`.

### Steps to Reproduce

On this case, there is `users` table, containg `user_id` as PK, `name`, `email`, and `password` columns. `UserUpdateDto` is made to partially have `name` and `email` field.   

The service method is as below.

```ts
async updateUserInfo(userId: number, dto: UserUpdateDto): Promise<BasicMessageDto> {
    const result = await this.userRepository
      .createQueryBuilder()
      .update('users', { ...dto })
      .where('user_id = :userId', { userId })
      .execute();
    console.log(result.affected);
    if (result.affected !== 0) {
      return new BasicMessageDto('Updated Successfully.');
    } else throw new NotFoundException();
  }
```

* As I mentioned above, the above method works perfectly fine when used with MySQL.   
  But it doesn't work when I use SQLite database. Below is my ormconfig for creating connection   
  to SQLite memory database.

```ts
type Entity = Function | string | EntitySchema<any>;

export async function createMemoryDB(entities: Entity[]) {
  return createConnection({
    type: 'sqlite',
    database: ':memory:',
    entities,
    logging: false,
    synchronize: true,
  });
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | MacOS Big Sur 11.2|
| Node.js version     | v14.15.4| 
| Typescript version  | v4.0.5| 
| TypeORM version     | v0.2.31| 

### Additional Context

N/A

### Relevant Database Driver(s)

- [X] `sqlite`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [X] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sangwoo-98** [comment]
I just confirmed that `DeleteResult` is also having the same issue as `UpdateResult` when used with SQLite in-memory database.

**Comment by coyoteecd** [comment]
@sangwoo-98 If you're looking for a place to fix this in a PR, the code processing the raw query result is here: https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/query-builder/UpdateQueryBuilder.ts#L105-L119

You can look at the "raw" property and see if the SQLLite driver returns the number of affected rows there, and add an elseif statement to have it copied to the updateResult.affected, as it is done with other drivers. I see the DeleteQueryBuilder does have something, see https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/query-builder/DeleteQueryBuilder.ts#L88-L90.

[I am not a maintainer, just thought to provide guidance so you can submit a PR]

**Comment by sangwoo-98** [comment]
@coyoteecd Great! I'll try to take a look at it as soon as I have some extra time :)

**Comment by sangwoo-98** [comment]
Well I spent 4 hours into it, couldn't fix it :(
For the research I did about better-sqlite3, it seemed quite better than sqlite, and using better-sqlite3 instead of sqlite did fix this issue.

For people who are viewing this in the future, I think the only way is to use better-sqlite3. (Until someone fixes this issue..)
