### ISSUE TITLE
Does not resolve correct column name with @JoinColumn

### ISSUE THREAD

**Issue by JamesParkDev** [typeorm/typeorm#7379]
## Issue Description

if you have a column let's say "user_id" while using @Column({ name: "user_id" })

and you have other table like photos and you want to reference user_id you get 
"Error: Referenced column user_id was not found in entity User"

I'm pretty sure it tries to find the column by property name. It should also try finding it by declared value from @Column
decorator

### Expected Behavior

If it does not fiend property it should look from decorator values..

### Actual Behavior

It says:
```
Error: Referenced column user_id was not found in entity User" even though the column exists
```

### Steps to Reproduce

Create user table like:
```typescript
@Column({ name: "user_id" })
public userId;
```

create another table trying to reference it 
```typescript
 @Column({ name: "user_id", type: "uuid", nullable: false })
 public userId: string;

 @JoinColumn({
      { name: "user_id", referencedColumnName: "user_id" },
  })
public user: User
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      win10    |
| Node.js version     | v14.15.0 | 
| Typescript version  | v4.0.5 | 
| TypeORM version     | v0.2.31 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `maraidb`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by msabo1** [comment]
If you want to create relation you should use relation decorators. You should read [docs](https://typeorm.io/#/relations) but basically what you need to do if you want, for instance, one-to-many relation
```typescript
class User{
@Column({ name: "user_id" })
  public userId;
}

class Photo{
  @Column({ name: "user_id", type: "uuid", nullable: false })
   public userId: string;

  @ManyToOne((type) => User)
  @JoinColumn({
      { name: "user_id", referencedColumnName: "user_id" },
  })
  public user: User
}
```

**Comment by JamesParkDev** [comment]
> If you want to create relation you should use relation decorators. You should read [docs](https://typeorm.io/#/relations) but basically what you need to do if you want, for instance, one-to-many relation
> 
> ```ts
> class User{
> @Column({ name: "user_id" })
>   public userId;
> }
> 
> class Photo{
>   @Column({ name: "user_id", type: "uuid", nullable: false })
>    public userId: string;
> 
>   @ManyToOne((type) => User)
>   @JoinColumn({
>       { name: "user_id", referencedColumnName: "user_id" },
>   })
>   public user: User
> }
> ```

Thank you for your reply. This does not function at all for me I found a solution that works.

used "userId" in my referencedColumnName
```typescript
  @ManyToOne((type) => User)
  @JoinColumn({
      { name: "user_id", referencedColumnName: "userId" },
  })
  public user: User
```

and in other tables I have

```typescript
  @Column({ name: "user_id" })
  public userId;
```

only doing `userId` works for me. Even though it should also work with column name

**Comment by msabo1** [comment]
Yeah, it is poorly documented and option name is misleading.
This is actual [implementation](https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/decorator/options/JoinColumnOptions.ts#L4)
```typescript
/**
 * Describes join column options.
 */
export interface JoinColumnOptions {

    /**
     * Name of the column.
     */
    name?: string;

    /**
     * Name of the column in the entity to which this column is referenced.
     */
    referencedColumnName?: string; // TODO rename to referencedColumn

}
```
And only from that comment it is clear (sort of :smile:) that you actually need to pass class property key.

**Comment by JamesParkDev** [comment]
> Yeah, it is poorly documented and option name is misleading.
> This is actual [implementation](https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/decorator/options/JoinColumnOptions.ts#L4)
> 
> ```ts
> /**
>  * Describes join column options.
>  */
> export interface JoinColumnOptions {
> 
>     /**
>      * Name of the column.
>      */
>     name?: string;
> 
>     /**
>      * Name of the column in the entity to which this column is referenced.
>      */
>     referencedColumnName?: string; // TODO rename to referencedColumn
> 
> }
> ```
> 
> And only from that comment it is clear (sort of 😄) that you actually need to pass class property key.

Yup, that makes way more sense! I thought that was the case while looking at code, but did not want to gamble on it

**Comment by JamesParkDev** [comment]
This is not a bug. Just not clear by the name.

**Comment by Woodz** [comment]
The naming is a bug. It should be `referencedPropertyName` since it refers to the entity property name

**Comment by clintonb** [comment]
I just encountered this issue. Further adding to the confusion is the fact that `name` expects a _column_ name while `referencedColumnName` expects an entity property name.
