### ISSUE TITLE
select: false doesn`t work on "...repository.save"

### ISSUE THREAD

**Issue by LeoDalcegio** [typeorm/typeorm#7382]
## Issue Description
Added @Column({ select: false }) to a column in user entity but it still returns when calling userRepository.save().

We are using NestJS, the repository is injected via dependency injection.

```js constructor(
@InjectRepository(User)
private readonly userRepository: Repository<User>,
```

```js
@Column({ select: false })
password: string;

@Column({ select: false })
salt: string;
```
```js
const user = this.userRepository.create({
        email,
        username,
        salt,
        isVerified: false,
        password: hashedPassword,
      });

const userToReturn: User = await this.userRepository.save(user);

return userToReturn;
```

### Expected Behavior

{ select: false } fields to not be returned.

### Actual Behavior

{ select: false } fields are being returned.

### Steps to Reproduce

1. Add @Column({ select: false }) to a column
2. Create a instance of the entity and save it.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Linux - Kubuntu 20.04  |
| Node.js version     | v14.15.3 | 
| Typescript version  | v4.1.4 | 
| TypeORM version     | v0.2.31 |

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by atyapin** [comment]
Duplicate [https://github.com/typeorm/typeorm/issues/4591](https://github.com/typeorm/typeorm/issues/4591)
