### ISSUE TITLE
TypeOrm does not run migration while creating a new connection. 

### ISSUE THREAD

**Issue by vihangmi10** [typeorm/typeorm#7388]
## Issue Description
On creating a new schema and creating a new connection for the new schema typeorm does not run migration. migrationRun flag is set to true.
### Expected Behavior
Must run migration and create a table in the new schema.

### Actual Behavior
Creates a new schema and creates a migration table in the new schema but does not create entity table. When there is migration file generated to create new table.
```
// include the output in code tags like these!
```
tenantOrm.config.ts 
```
import { join } from 'path';
import { User } from './entities/user.entity';

const TenantOrm = {
  type: 'postgres',
  host: process.env.DB_HOST,
  port: parseInt(process.env.DB_PORT),
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  synchronize: false,
  migrationsRun: true,
  entities: [User],
  migrations: [join(__dirname, '../db-tenant/migrations/**/*{.ts,.js}',)],
  cli: {
    migrationsDir: '/src/db-tenant/migrations'
  }
}
export = TenantOrm;
```
user.entity.ts 
```
import { BaseEntity, Column, Entity, PrimaryColumn, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @PrimaryColumn('uuid')
  publicId: string;

  @Column()
  firstName: string;

  @Column()
  lastName: string;
}
```
auth.service.ts 
```
import { Injectable, InternalServerErrorException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createConnection, getConnection } from 'typeorm';
import TenantOrm = require('../config/tenantOrm.config');

@Injectable()
export class AuthService {
  constructor(
    private configService: ConfigService,
  ){}

  async createTenantSchema(tenantName: string): Promise<void> {
    try {
      const connection = await getConnection();
      connection.manager.query(`CREATE SCHEMA IF NOT EXISTS ${tenantName}`)
      await connection.close();
      const tenantConnection = await createConnection({
        ...TenantOrm,
        name: tenantName,
        type: 'postgres',
        schema: tenantName
      });
      await tenantConnection.close();
    }  catch(error) {
      throw new InternalServerErrorException(`Failed to connect to database. Error --- ${error}`);
    }


  }
}
```

### Steps to Reproduce

Minimum reproduction repository is 
```
https://github.com/vihangmi10/multi-tenancy-nestjs
```
To run the code : 
```
npm install 
```
```
docker-compose up -d 
```
```
npm run start:dev
```
Database connection details
```
host: localhost
port: 5432
database: postgres
username: postgres
password: pass123
```
app runs on localhost:3000
Make a GET request call to the url
```
http://localhost:3000/auth?tenant=abc
```

### My Environment

NestJS v7.1.2

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Mac OS X Big Sur 11.2.1         |
| Node.js version     | v13.13.0 | 
| Typescript version  | v4.0.5 | 
| TypeORM version     | v0.2.31 | 
| Nestjs | v7.1.2|

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Seems like it can't find any migrations which looks very much like an issue with your local environment.

You've got an extra comma in `join`.  Maybe related.  I suggest inspecting the final path & confirming it's correct.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
