### ISSUE TITLE
[Bug?] RelationQueryBuilder.findOne parameter documented but not implemented?

### ISSUE THREAD

**Issue by kevin-lindsay-1** [typeorm/typeorm#7389]
## Issue Description

Trying to use relational query builder to load a given entity by ID (I just prefer the syntax).

### Expected Behavior

Based on the docs, when I provide an ID into loadOne, it looks like it should be looking up a relation by that ID.

```ts
// category has 3 posts, [1, 2, 3]

const existingLicenses = await entityManager
  .createQueryBuilder()
  .relation(Category, 'posts')
  .of(Post)
  .loadOne(4); // expect undefined
```

### Actual Behavior

 Instead, it just seems to return the first related entity, not the one by id.

```ts
// category has 3 posts, [1, 2, 3]

const existingLicenses = await entityManager
  .createQueryBuilder()
  .relation(Category, 'posts')
  .of(Post)
  .loadOne(4); // 1?
```

### Steps to Reproduce

This looks to be an intended use case, but maybe the feature was removed in development, or was planned and documented as such, but accidentally left unimplemented?

```ts
/**
* Loads a single entity (relational) from the relation.
* You can also provide id of relational entity to filter by.
*/
async loadOne<T = any>(): Promise<T|undefined> {
  return this.loadMany<T>().then(results => results[0]);
}
```

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, and I could probably figure it out, but I ain't worked on this before.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by coldek** [comment]
Still having this issue. Any pull request to actually implement this?
