### ISSUE TITLE
Loading entities with environment variable TYPEORM_ENTITIES (ES6 ES7 + Webpack + Babel)

### ISSUE THREAD

**Issue by hammadzz** [typeorm/typeorm#739]
This is me using typeorm on the server side (NODE JS)

I am able to create a connection using the config object:
```javascript
import {Parking} from './entity/Parking'
const connection = await typeorm.createConnection({
			type: "postgres",
			host: "localhost",
			port: 5432,
			username: "exampleuser",
			password: "examplepass",
			database: "exampledb",
			entities: [
			 	Parking
		        ],
			autoSchemaSync: true
		})
```

Now I want to use environment variables and load all entities from the src/entity folder. I have set the   TYPEORM_ENTITIES variable to ./src/entity/*.js which breaks because obviously the code is es6. 

So I added an entry point to web pack for the entities folder. Successfully got web pack transpiling it and putting it into .webpack folder. Then set TYPEORM_ENTITIES to .webpack/src/entity/*.js but they aren't being loaded into entity manager.

What is the path relative to?

**Comment by hammadzz** [comment]
@pleerock maybe you would be able to help.

**Comment by pleerock** [comment]
you don't really need webpack.

> which breaks because obviously the code is es6.

then simply set "es5" in ts compile options
