### ISSUE TITLE
Query Builder

### ISSUE THREAD

**Issue by ArthurQR98** [typeorm/typeorm#7392]
I want to know how to get the query of a table, a column of type enum its data. For example 
![photo_2021-02-18_12-35-33](https://user-images.githubusercontent.com/46725242/108434586-e8c47180-7215-11eb-8a64-91178e474f60.jpg)
I need those values.

**Comment by nathan815** [comment]
You'll need to run a raw query to get it. Something like

```
const type = manager.query("SHOW COLUMNS FROM table WHERE Field = 'type_employee'")[0]['Type'];
// type == enum('..','..')
// parse type string to extract the values
```

Consider creating a separate table for employee type instead of having it as an enum column, since you're wanting to query the values.

**Comment by nathan815** [comment]
This seems unrelated to TypeORM. 

But you'll need to run a raw query to get it. Something like

```
const type = manager.query("SHOW COLUMNS FROM table WHERE Field = 'type_employee'")[0]['Type'];
// type == enum('..','..')
// parse type string to extract the values
```

**Comment by ArthurQR98** [comment]
Yes friend, I already solved it.
