### ISSUE TITLE
TypeORM connection error

### ISSUE THREAD

**Issue by allan2coder** [typeorm/typeorm#7397]
Issue type:

- [x] question
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

TypeORM version:

- [x] latest
- [ ] @next
- [ ] 0.x.x (or put your version here)

Steps to reproduce or a small repository showing the problem:

Entity is following:
```
@Entity()
export class TUser {
    // @PrimaryGeneratedColumn("increment", { type: "bigint" } )
    @PrimaryColumn({type: "bigint"})
    id: number;
}
```
My question is, how to solve this problem:
```
query: 'ALTER TABLE `t_user` CHANGE `id` `id` bigint NOT NULL'
```

Id type must be bigint

**Comment by Itsaadarsh** [comment]
Hello there @allan2coder , 

While creating your typeORM connection add this configuration in your config file
```
`bigNumberStrings: false`
```
![image](https://user-images.githubusercontent.com/54549066/108584515-043f9180-7368-11eb-8cc3-963c8ef353ee.png)

And if you are using typescript then you just need to add `id: bigint` as typescript supports bigint type.
```
@PrimaryGeneratedColumn({type: 'bigint'})
id: bigint;
```
Hope this helps.

**Comment by allan2coder** [comment]
@Itsaadarsh awsome, thx!
