### ISSUE TITLE
PrimaryGeneratedColumn does not set isGenerated to true when exists on parent entity

### ISSUE THREAD

**Issue by eyalhakim** [typeorm/typeorm#740]
Describing normal Typescript inheritance and not one of single table/class inheritance.

This is happening due to recent changes in the auto-generated functionality made on the 25th of July.
The problem is that the "build" function of EntityMetadataBuilder calls the "findGenerated" function on MetadataArgsStorage and only passes the current entity metadata without the entire inheritance tree.

Didn't know what was the best way to fix this.

**Comment by eyalhakim** [comment]
@pleerock I think this one is a major

**Comment by pleerock** [comment]
you are right this bug was introduced by latest generation strategy changes and this is a major issue.

**Comment by pleerock** [comment]
fix will be released in `0.1.0-alpha.34`

**Comment by eyalhakim** [comment]
great! thank you!
