### ISSUE TITLE
Passing authPlugins from TypeOrm into Mysql2

### ISSUE THREAD

**Issue by awcchungster** [typeorm/typeorm#7404]
### Expected Behavior

I can leverage mysql2 client in Node to access a RDS database on AWS with IAM authentication. 

### Actual Behavior

Passing the fields in is failing.

### Steps to Reproduce

const AWS = require("aws-sdk");

import {createConnection} from "typeorm";
const logger = require('../models/logging')

var signer = new AWS.RDS.Signer({
  // configure options
  region: process.env.AWS_REGION,
  username: process.env.MYSQL_DB_USER,
  hostname: process.env.MYSQL_DB_HOST,
  port: 3306
});

let db
//Database connection
exports.connectToDatabase = () => {

    // define RDS IAM connection
    aws_connection = () => {
        return {
            connectionLimit: 10,
            host     : process.env.MYSQL_DB_HOST,
            user     : process.env.MYSQL_DB_USER,
            password : signer.getAuthToken(),
            database : process.env.MYSQL_DB_NAME,
            ssl: 'Amazon RDS',
            enableKeepAlive: true,
            keepAliveInitialDelay: 5000,
            authPlugins: {
                mysql_clear_password: () => {
                    // console.log('mysql_clear_password plugin init');
                    return () => {
                        // console.log('mysql_clear_password plugin get data');
                        return new Promise((accept, reject) => {   
                            signer.getAuthToken((err, token) => {
                                if (err)
                                    return reject(err)
                                return accept(token)
                            })
                        })
                    }
                }
            }
        }
    }

    // define standard connection
    standard_connection = () => {
        return {
            type: "mysql",
            connectionLimit: 10,
            host     : process.env.MYSQL_DB_HOST,
            user     : process.env.MYSQL_DB_USER,
            password : process.env.MYSQL_DB_PASS,
            database : process.env.MYSQL_DB_NAME,
            enableKeepAlive: true,
            keepAliveInitialDelay: 5000,
            entities: [
                "../../cocatalyst_db2/entities/*.js"
            ],
            synchronize: true,
            logging: false
        }
    }
    
    db = createConnection((process.env.NODE_ENV === 'production') ? aws_connection() : standard_connection());
    logger.info("Database Connected")

### My Environment

I am migrating from a independently object relationship managed RDS databased to one administered by typeORM. As part of the enterprise security, we have IAM authenticator set up. Is there a way the typeORM can pass the auth plug in function into mysql2 client?

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.15.5|
| Typescript version  | v4.1.5 |
| TypeORM version     | v0.2.31|

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Pass the fields in as `extra`
