### ISSUE TITLE
condition to enable where

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#7405]
## Feature Description
support a condition(boolean or function returns boolean or Promise resolved to boolean) to control whether the where clause should be append to the query. It is flow way to compose dynamic where query.

### The Problem

query has an optional where
```ts
 const result1 = await OrderS1Item.createQueryBuilder('I')
      .innerJoin('I.order', 'O', `O.state = '${OrderState.CREATED}'`)
      .andWhere('I.materialId = :materialId', { materialId })
      .andWhere('(:excludeOrderId IS NULL OR I.orderId <> :excludeOrderId)', { excludeOrderId }) // <-- this line is not good
      .select('SUM(I.preAmount)', 'amount')
      .getRawOne();
```

### The Solution

```ts
 const result1 = await OrderS1Item.createQueryBuilder('I')
      .innerJoin('I.order', 'O', `O.state = '${OrderState.CREATED}'`)
      .andWhere('I.materialId = :materialId', { materialId })
      .andWhere('I.orderId <> :excludeOrderId', { excludeOrderId }, () => !_.isEmpty(excludeOrderId)) // <-- the last param decides the where is enabled or not
      .select('SUM(I.preAmount)', 'amount')
      .getRawOne();
```

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by AlexMesser** [comment]
This is redundant. We can't continue extending query builder functionality to fit all user demands. You can simply use if statement to do same without any changes in the codebase.
