### ISSUE TITLE
Column selection in .where() method is not being case sensitive

### ISSUE THREAD

**Issue by rajshrimohanks** [typeorm/typeorm#741]
Consider the following code:
```typescript
await User.getRepository()
        .createQueryBuilder('user')
        .innerJoinAndSelect('user.organizationRoles', 'organizationRoles')
        .where('user.uniqueIdentifier=:userEmail')
        .setParameter('userEmail', 'abc@abc.com')
        .getOne();
```
The `organizationRoles` selector in `innerJoinAndSelect()` works perfectly fine, but the `uniqueIdentifier` selector in `where()` gives me an error saying `error: column role.uniqueidentifier does not exist`.

However, when I change the code to:
```typescript
await User.getRepository()
        .createQueryBuilder('user')
        .innerJoinAndSelect('user.organizationRoles', 'organizationRoles')
        .where('user."uniqueIdentifier"=:userEmail')
        .setParameter('userEmail', 'abc@abc.com')
        .getOne();
```
(note double quotes in `where()` method) it works perfectly.

I understand that Postgres requires quotes when using mixed-case words. I checked the query generated and I noticed that quotes where added by default for `SELECT` clause in the statement but the `WHERE` clause doesn't have quotes added.

I'm not sure if this is intended to be so or if it's a bug, but I think methods should have consistent case behaviour.

Thanks for a great library!

---
**Database:** PostgreSQL
**TypeORM version:** 0.1.0-alpha.33

**Comment by pleerock** [comment]
it should be escaped. Can you show me your entity?

**Comment by rajshrimohanks** [comment]
@pleerock This would be it.
```typescript
@Entity()
export class User extends EntityBase {

  static readonly ENTITY_TYPE= 'User';

  @Column({ nullable: false })
  firstName: string;

  @Column({ nullable: false })
  lastName: string;

  @Column({ nullable: false, unique: false })
  email: string;

  @ManyToMany(type => Organization, organization => organization.users, {
    cascadeInsert: true,
    cascadeUpdate: true
  })
  organizations: Organization[];

  @ManyToMany(type => OrganizationRole, orgRole => orgRole.users, {
    cascadeInsert: true,
    cascadeUpdate: true
  })
  organizationRoles: OrganizationRole[];

  static make(userParams: UserParams): User {
    let user = new User();
    user.firstName = userParams.firstName;
    user.lastName = userParams.lastName;
    user.email = userParams.email;
    user.organizations = [];
    user.organizationRoles = [];
    return user;
  }

  static getRepository(): Repository<User> {
    return getEntityManager().getRepository(User);
  }
}

interface UserParams {
  firstName: string;
  lastName: string;
  email: string;
  isVerified: boolean;
}
```

**Comment by pleerock** [comment]
But where is your `uniqueIdentifier` column?

**Comment by rajshrimohanks** [comment]
Oh sorry. I edited it to `email`. Here is the original:
```typescript
@Entity()
export class User extends EntityBase {

  static readonly ENTITY_TYPE= 'User';

  @Column({ nullable: false })
  firstName: string;

  @Column({ nullable: false })
  lastName: string;

  @Column({ nullable: false, unique: true })
  uniqueIdentifier: string;

  @ManyToMany(type => Organization, organization => organization.users, {
    cascadeInsert: true,
    cascadeUpdate: true
  })
  organizations: Organization[];

  @ManyToMany(type => OrganizationRole, orgRole => orgRole.users, {
    cascadeInsert: true,
    cascadeUpdate: true
  })
  organizationRoles: OrganizationRole[];

  static make(userParams: UserParams): User {
    let user = new User();
    user.firstName = userParams.firstName;
    user.lastName = userParams.lastName;
    user.uniqueIdentifier = userParams.uniqueIdentifier;
    user.organizations = [];
    user.organizationRoles = [];
    return user;
  }

  static getRepository(): Repository<User> {
    return getEntityManager().getRepository(User);
  }
}

interface UserParams {
  firstName: string;
  lastName: string;
  uniqueIdentifier: string;
  isVerified: boolean;
}
```

**Comment by pleerock** [comment]
nothing unusual. We have tests which cover such scenario. Can you please create a simple git repository with minimal reproduction of the problem?

**Comment by rajshrimohanks** [comment]
@pleerock I'm sorry. I guess there's a misunderstanding. There is no "problem". I just wanted to point out that the `where()` method requires double quotes to escape the capitalization whereas `innerJoinAndSelect()` does not. One method requiring case handling and the other not in the same method chain makes it a bit weird. There is no other problem. You can close this issue if it is the intended behaviour. Thanks.

**Comment by pleerock** [comment]
> where() method requires double quotes to escape the capitalization whereas innerJoinAndSelect() does not.

actually it does not require double quotes even if your column is capitalized. If its a column then you should not manually add double quotes at all. Thats why I ask you to create sample git repo with reproduction of this problem to see if its a bug or not, because I cannot reproduce it.

**Comment by rajshrimohanks** [comment]
@pleerock Oh is that so? I'm travelling right now, I'll whip up a sample as soon as I get access to my machine.

**Comment by rajshrimohanks** [comment]
@pleerock Please close this issue. I realized I was being stupid and using the code wrong. There is no bug. :cold_sweat: :mask:

**Comment by marvinroger** [comment]
@pleerock I do have the same issue with `0.2.0-alpha.13` and Postgres:

```js
const wallets = await this.walletRepository
  .createQueryBuilder('wallet')
  .where('wallet.userId IN (:users)', { users: userIds })
  .getMany()
```

```
postgres_1   | 2018-01-07 21:04:58.486 UTC [133] ERROR:  column wallet.userid does not exist at character 350
postgres_1   | 2018-01-07 21:04:58.486 UTC [133] HINT:  Perhaps you meant to reference the column "wallet.userId".
postgres_1   | 2018-01-07 21:04:58.486 UTC [133] STATEMENT:  SELECT "wallet"."id" AS "wallet_id", "wallet"."uuid" AS "wallet_uuid", "wallet"."creationDate" AS "wallet_creationDate", "wallet"."updateDate" AS "wallet_updateDate", "wallet"."name" AS "wallet_name", "wallet"."currency" AS "wallet_currency", "wallet"."deleted" AS "wallet_deleted", "wallet"."userId" AS "wallet_userId" FROM "wallet" "wallet" WHERE wallet.userId IN ($1)
```

Replacing by `.where('wallet."userId" IN (:users)', { users: userIds })` fixes the issue

**Comment by pleerock** [comment]
try `wallet.user` - in query builder you work with relation properties, not database columns if you want proper escaping

**Comment by marvinroger** [comment]
So, what's the difference with https://github.com/typeorm/typeorm/issues/1239#issuecomment-347074706 ?

**Comment by pleerock** [comment]
Both approach work - query builder works with anything valid selected by sql query (like some column for example authorId) and entity relations and entity columns. But it escapes only entity relations and entity columns he is aware of. Selecting "authorId" works as well even when you don't have such column defined, but I guess in case of #1239 author simply uses different database (mysql for example) and its case insensitive, so he does not really need escaping. In your case you need escaping since you are using postgres and its always a better practice to use your entity property names for columns and relations.

**Comment by marvinroger** [comment]
Alright, thanks a lot @pleerock :) maybe this should be mentioned in the docs.
