### ISSUE TITLE
[bug] Typeorm findOne(FindOneOptions) return type is Promise<Entity> not Promise<Entity | undefined>

### ISSUE THREAD

**Issue by wzhkobe2408** [typeorm/typeorm#7412]
## Issue Description
The return type of findOne function is not expected to be Promise<Entity>

### Expected Behavior

```typescript
const entity = await entityRepo.findOne({ id });
```

**entity type should be Entity | undefined**

### Actual Behavior

```typescript
const entity = await entityRepo.findOne({ id });
```

**vscode or webstorm tell me entity's type is Entity**

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    MacOS Catalina10.15.4   |
| Node.js version     | v12.18.1
| Typescript version  | v3.9.9|
| TypeORM version     | v0.2.31 |
| @nestjs/typeorm |  v7.1.5  |
| mysql | 2.18.1 |

### Relevant Database Driver(s)
- [ ] `mysql`

**Comment by paulintrognon** [comment]
Why did you closed that issue? I am having the same problem and would like to know how to fix it please...

**Comment by usman-web-dev** [comment]
@paulintrognon man you saved my hours. I was almost going to choose Sequelize due to this error. I can't explain how your EDIT helped me.

### Thanks again.

**Comment by Ishidall** [comment]
@paulintrognon 
You are savior of my hours. Totally didn't expect Nest CLI generates tsconfig with `strictNullChecks: false` .
