### ISSUE TITLE
Unexpected return from query builder

### ISSUE THREAD

**Issue by edilson** [typeorm/typeorm#7413]
| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.4 | 
| Typescript version  | v3.9.6 | 
| TypeORM version     | v0.2.31 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

I'm using the query builder with a window function and I'm receiving an unexpected return:

Here is the code I'm performing: 

```
const subscriptionsFound = await this.ormRepository
      .createQueryBuilder('user_challenge')
      .addSelect(rankQuery, 'user_challenge_classification')
      .leftJoinAndSelect(
        'user_challenge.user',
        'user',
        'user.id = user_challenge.user_id'
      )
      .leftJoinAndSelect(
        'user.profile',
        'user.profile',
        'user.profile.user_id = user_challenge.user_id'
      )
      .where('user_challenge.challenge_id = :challenge_id', { challenge_id })
      .skip((page - 1) * offset)
      .take(offset)
      .getMany();

    return subscriptionsFound;
```

The code with the window function:

```
`rank() OVER(PARTITION BY challenge_id ORDER BY total_distance DESC NULLS LAST)`;
```

When I run the code with query builder it does return ordered by total_distance but when I get the query generated and run it on any db admin it gives the expected result. With the query builder when I remove the relations it returns the correct response. Another weird behavior is that when I use the pagination on query builder from the second page it doesn't return the sequence. Looks like it is recalculated as if it was handling another type of data.

**Comment by imnotjames** [comment]
Use `getRawMany()` if you don't want it to try to map to an entity

**Comment by edilson** [comment]
@imnotjames to solve this problem I used the limit with offset, instead of skip and take. Now it brings me the wished results.
