### ISSUE TITLE
Add 'orphanedRowAction' option to EntitySchema

### ISSUE THREAD

**Issue by oscar-v0** [typeorm/typeorm#7417]
## Feature Description

The 'orphanedRowAction' property was recently added to RelationOptions thanks to @nebkat (#7105). However, this option is still missing for EntitySchemaRelationOptions. Can this be added?

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

I've never contributed to open source but it seems like a simple addition.

**Comment by JamieWritesCode** [comment]
Seems like a simple oversight when the original change was made. I'll try and take a look at this soon if no one more qualified is interested in taking the lead. Unfortunately, it seems as though those of us using separated Entities don't get a lot of love at the moment.
