### ISSUE TITLE
Inject NestJs "injectable" classes into custom repositories

### ISSUE THREAD

**Issue by ssharma674** [typeorm/typeorm#7426]
## Feature Description

We'd like the ability to inject NestJs classes into repositories.

The project I work is built on NestJS and uses TypeORM in the persistence layer. We like extending the base repository class to add any custom queries to a Repository. For example we might have something like 

```
@EntityRepository(FarmData)
export class FarmDataRepository extends Repository<FarmData> {
  /** custom query */
  myComplicatedAggregationQuery(): Promise<Data>{

       ///// .....

```
We would like to be able inject "injectable" NestJS classes to the repository. Something like 

`constructor(@Inject(UsageData) private usageData) { super(); }`

### The Problem
The injection behavior is unpredictable.

Since typeOrm is outside of NestJs, using "@inject" for "@injectable" classes gives unpredictable results. Sometimes a random typeOrm class instance is injected and at other times nothing is injected (i.e. usageData might be undefined).

### The Solution
We would like more seamless operations between NestJs and TypeORM. Being able to use the @inject decorator or something as simple as that would go a long way.

### Considered Alternatives
Wrapping the repository in another class.

This would probably work, but semantically it seems clunky since we'd like to keep the 'is-a' relationship intact between a Repository and let's say a FarmDataRepository in accordance with OOP principles. Also, we'd like to reserve the use of a wrapper for a different purpose to meet internal design requirements.

### Relevant Database Driver(s)
This issue is independent of database drivers, but for the record, we're using postgres drivers.

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Wouldn't this require including nest as a dependency?

If so, that's a non-starter.

**Comment by Edgar-P-yan** [comment]
**Repositories are not services**. In repositories you are supposed to only implement the access to databases or other data sources. All the other logic should be separated to services. This is a form of decoupling. If you really think that you need your repositories to access services then probably something wrong is going on with the architecture.

In any case, i think that this kind of issues should be posted not to TypeORM, but to https://github.com/nestjs/typeorm .
