### ISSUE TITLE
future ConnectionOptions and ormconfig breaking changes

### ISSUE THREAD

**Issue by pleerock** [typeorm/typeorm#7427]
## Changes in ConnectionOptions

* `ConnectionOptions` will be renamed to `DataSourceOptions`, as well as everything else currently named as `Connection*` will be `DataSource*`. This breaking change will be described in another issue, in this issue we'll continue call things as they are right now.

* `ConnectionOptions` will become generic (`ConnectionOptions<Entities>`) to provide a better type-safety in other areas

* `entities: string[]`, `subscribers: string[]`, `migrations: string[]` option signatures will be removed and functionality of loading entities/subscribers/migrations based on directory will be removed. Only direct entity/subscriber/migration class/any const references can be specified. Motivation of this change:

   * moving forward we plan to be more type-safe and be aware of entities connection have registered (for example to be able to provide a compiler error when you do `connection.getRepository(NotExistEntity)`). It's not possible to have a proper type-safe behaviour with dynamically loaded js files
   
   * there are many problems with dynamically loaded js files running under different environments (with ts-node paths should load `.ts` from source directory, without ts-node paths should load `.js` files from output directory; another example - if we remove ts file, js file persist in the entity directory, and it will lead to changes not being applied to the database, until you manually remove file from the output directory)

This change means we'll only be able to specify entities by explicitly have them referenced in the code, e.g.:

```ts
import { User } from "./entity/User"
import { Post } from "./entity/Post"
import { Category } from "./entity/Category"
import { Photo } from "./entity/Photo"

export const connection = createConnection({
   // ...
   entities: [
      User,
      Post,
      Category,
      Photo
   ]
})
```

Many of you can say its worse and too verbose, however new approach has incredibly valuable benefits.
Old approach is more convenient, however downsides are:

* it can be super confusing for people who aren't aware about it's caveats 
* it doesn't have a type-safety features
* we simply can't scale our capabilities this way

And don't forget you can structure the code the way you prefer, for example:

```ts
// entity/index.ts
export * from "./User"
export * from "./Post"
export * from "./Category"
export * from "./Photo"

// connection.ts
import * as entities from "./entity"

export const connection = createConnection({
   // ...
   entities: entities
})
```

or 

```ts
// entity/index.ts
export const Entities = [
      User,
      Post,
      Category,
      Photo
]

// connection.ts
import { Entities } from "./entity"

export const connection = createConnection({
   // ...
   entities: Entities
})
```

## `ormconfig` deprecation

Currently we support `ormconfig` in a following formats: `["env", "js", "cjs", "ts", "json", "yml", "yaml", "xml"]`. In the future version we plan to remove `ormconfig` support.

* we will remove `yml` and `xml` because these formats aren't popular and their removal is going to simplify codebase and reduce TypeORM package size.

* we will remove `env` support as we can see from different issues in this repo - current implementation is imperfect and we always have to change the code under specific user demands. For example using env it's not possible to create and manage multiple connections, users always have a demand for specific connection option properties, etc.

* and finally we'll remove all other formats as well, because we remove `ormconfig` support. Reason:

  *  since entities now can only be declared as references in the code we can't use `json` format anymore. It means we can only declare connection options in the code
  * since we can only declare connection options in the code, it doesn't make much sense to have a separate js/ts file for only connection options, we can directly pass connection options into the createConnection function
  * it means source file where we create a connection is enough to have, it also means we can treat this file as a new `ormconfig`
  * reason why we still need something like `ormconfig` is a CLI. In CLI commands we need to know about connection options because using different CLI commands we can execute queries, run schema sync, etc.
  * in order to specify connection options to CLI, now we'll need to specify a source file with exported connection instance, for example `typeorm migration:generate --config ./app/connection.ts`
  * by default CLI command will take a **default** exported connection instance. If there are many connections and specific connection should be used, it can be achieved by for example `typeorm migration:generate --config ./app/connection.ts --connection secondConnection`
  * there is no convention for source code file with connection - it can be in any file and any directory, because of that CLI can't automatically pickup connection file (unlike with ormconfig)
  * in order to simplify CLI usage, we can have a property in the `package.json` like `"typeormConnection": "./src/app/connection.ts"` - it simplifies CLI usage

**Comment by TylorS** [comment]
This all sounds good, but it'd be amazing if we could add support for asynchronously loaded configurations. The use case of loading credentials from something like a secrets manager is probably the only thing that's too hard today

**Comment by Ginden** [comment]
> This all sounds good, but it'd be amazing if we could add support for asynchronously loaded configurations.

Support for asynchronously loaded configuration is assumed by default - ESM modules are supported and Node 14.8 introduced top-level await. 

So you will be able to do:

```ts
export default createConnection({
   password: await secretsManager.get('password'),
})
```

**Comment by kajal-clinch** [comment]
This doc is helpful, this needs to be mention on https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md

**Comment by kajalj3098** [comment]
This doc is helpful, this needs to be mention on https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md

**Comment by kajalj3098** [comment]
and more docs like this will be helpful for such major BREAKING changes explanation @pleerock

**Comment by alumni** [comment]
Reopening for discussing what's left of this.
