### ISSUE TITLE
bug: subscriber afterXY functions should be called after the transaction is commited

### ISSUE THREAD

**Issue by NoNameProvided** [typeorm/typeorm#743]
**Description:** After trying to update to the latest release we have experienced failing queries which just worked fine before. 

**Observed behaviour:** The reason for this seems to be that TypeORM will wait until the `afterXY` subscriber calls finish before committing the transaction. (This works fine when no other query has been made in the subscriber, but it causes the transaction to fail and rollback when the subscriber try to execute queries. 

**Expected behaviour:** TypeORM should `COMMIT` the transaction before calling the subscriber's `afterXY` functions.

**Comment by NoNameProvided** [comment]
An ugly hack for now is to return early from the subscriber function and  push the db operation to the end of the queue via: 

```ts
global.setTimeout(async () => {
          const customEntity = await existingCache.cache.options.getterFn(id);
          existingCache.cache.set(id, customEntity);
        }, 0);
```

**Comment by pleerock** [comment]
> TypeORM should COMMIT the transaction before calling the subscriber's afterXY functions.

no. What queries are you executing in your subscribers? You must use entity manager provided by subscribers to execute all queries you do there

**Comment by pleerock** [comment]
If you still have issues or want to discuss something - let me know.

**Comment by Cactucs** [comment]
I think I have same issue as mentioned above. 

Imagine following use-case: I have an app where users can be awarded a badge. When they recieve I want to send a push-notification to them. 
So I create a subscriber with `afterInsert` and `afterUpdate` methods. But typeorm notifies me of insert, but at that point when I do a `SELECT` in the db, it's not yet "connected" with the user (my real use-case is that I have one more entity between user and badge - I do `manager.save([somethingBetween, badge])`). My subscriber method is called when `INSERT` query is run, but before additional `UPDATE` query is called where relationship with the user is added. (In my code it's in one `manager.save` call but typeorm splits it into multiple queries probably to handle the dependencies).

Proposed solutions: 
- call method on subscriber after transaction ends
- call `afterInsert` after the `UPDATE` query, which adds the relationship

I hope it's understandable.

**Comment by pleerock** [comment]
> call afterInsert after the UPDATE query, which adds the relationship

all "after" events are called after all queries are executed in terms of a single `save` call, please check if you really have this issue and provide more details if you do. Also, its better if you check it in `next` version since there are important changes in subscriber I made recently there

**Comment by yvisbeek** [comment]
Found a workaround for this. You can commit the transaction you are currently in but you then have to immediately open a new transaction after which typeorm will close a then empty transaction I think. You can try it like this: 

event.queryRunner.commitTransaction(); // Commit transaction, to make it available in DB
event.queryRunner.startTransaction(); // Start new transaction for TypeOrm to commit after afterInsert

**Comment by incompletude** [comment]
news on this? same problem.
