### ISSUE TITLE
Number field set to zero violates null constraint.

### ISSUE THREAD

**Issue by matthewvcarey1** [typeorm/typeorm#7431]
If you have an entity that start like this:

@Entity()
@Check(`"low_value" >= 0 AND "low_value" <= 99`)
@Check(`"high_value" > 0 AND "high_value" <= 99`)
@Unique(['low_value', 'high_value', 'unit', 'organization'])
export class AgeRange extends BaseEntity {
    @PrimaryGeneratedColumn('uuid')
    public id!: string

    @Column({ nullable: false })
    public name?: string

    @Column({ nullable: false })
    public high_value!: number

    @Column({ nullable: false })
    public low_value!: number
    
 If the low_value (a number) is set to 0 an error 
Error: null value in column "low_value" of relation "age_range" violates not-null constraint
   
I know that 0 is a false in javascript but it is a valid number that may well be stored in a number field. It is different from null or undefined that I don't want in this field.

Either there is something very wrong here or I am misusing Typeorm in some way, I hope it is the latter.

**Comment by matthewvcarey1** [comment]
I found that this works so it is more of a documentation issue:
@Column({ type: 'int', nullable: false, default: 0 })
    public high_value!: number
    @Column({ type: 'int', nullable: false, default: 0 })
    public low_value!: number

**Comment by imnotjames** [comment]
What database are you using here?

**Comment by imnotjames** [comment]
I created a test case that tries to replicate this.  No luck!

https://github.com/imnotjames/typeorm/commit/b6801338efbf09ea259cdcac1ca7c13163f69f1b

Without a means to replicate this I'll be closing this issue out - but if you can include more information that allows us to replicate it please reopen the issue & we'll continue working through it!
