### ISSUE TITLE
Persist is overwriting the not loaded relationships

### ISSUE THREAD

**Issue by brunosiqueira** [typeorm/typeorm#744]
I created a one to many relationship between two of my models:

Organization:
```
@Entity()
export class Organization {
  @PrimaryColumn('uuid')
  @IsUUID('4')
  id: string;

  @Column('string', { nullable: false })
  name: string;

  @OneToMany((type) => PersonOrganization, (personOrganization) => personOrganization.organization,
    { cascadeInsert: false, cascadeUpdate: false })
  personOrganizations: PersonOrganization[] = [];
}
```
And PersonOrganization:
```
@Entity()
export class PersonOrganization {
  @PrimaryColumn('uuid')
  @IsUUID('4')
  id: string;

  @Column('string', { nullable: true })
  matricula: string;

  @ManyToOne((type) => Organization, (organization) => organization.personOrganizations,
    { cascadeAll: false, nullable: false, onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'organization_id' })
  organization: Organization;

  @ManyToOne((type) => Person, (person) => person.personOrganizations,
    { cascadeAll: false, nullable: false, onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'person_id' })
  person: Person;
}
```

I want to retrieve Organization from the database, update with some new values and persist it afterwards. With no cascade and no associated model.

When I retrieve one organization model from the db though findOneById() I get this:

```
Organization {
  personOrganizations: [],
  id: '0c3a1312-8f71-445e-bc93-f8e2e64af792',
  name: 'E.M.MARTIM DE SÁ Atualizado',
  createdAt: 2017-06-01T17:16:51.811Z,
  updatedAt: 2017-06-02T17:16:51.000Z }
```
The object brings personOrganizations empty, even though there are records associated in the person_organization table. The problem starts when I try to persist the Organization. It updates organization and tries to set organization_id in all the associated personOrganization records as null. Which generates a constraint error.

If I delete from the object the atribute personOrganization then it works properly:
```
    repository
      .findOneById(params.id)
      .then((organization: Organization) => {
        delete organization.personOrganizations;
        return repository.persist(merge(organization, body));
      });
```
But how can I do this in the correct way?

**Comment by pleerock** [comment]
```ts
  personOrganizations: PersonOrganization[] = [];
```

remove initialization (`= [];`) from your model. Since after you load your model and it has intialized property orm thinks you removed all items from your relation and removes them.

**Comment by avermeulen** [comment]
This quirky! I ran into the same problem. I will stop initializing collections in Entity Class. It's clearly not something one should be doing. I was very happy to find this post though!

**Comment by pleerock** [comment]
Yeah its quirky and I would like to avoid such behaviour, but there is no other way I came up at the moment.
