### ISSUE TITLE
Compilation error while trying to create a new migration

### ISSUE THREAD

**Issue by caiotracera** [typeorm/typeorm#7443]
## Issue Description
When I run `yarn typeorm migration:create -n CreateUsers` to generate a new Migration, I got Compilation error in `ormconfig.js`.

### Expected Behavior
Should create a new migration file inside `./src/shared/infra/typeorm/migrations/`.

### Actual Behavior
The migration file is created, but in the root folder, not the designated one.

```
yarn typeorm migration:create -n CreateUsers
yarn run v1.22.5
$ ts-node-dev -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:create -n CreateUsers
[INFO] 22:31:58 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.2)
Compilation error in /home/troyfalcon/www/traveler/server/ormconfig.js
Migration 1614648718646-CreateUsers.ts has been generated successfully.
Done in 1.80s.

```

### Steps to Reproduce

1. `ormconfig.js` file:

```js
require('dotenv/config')

module.exports = [
  {
    name: 'default',
    type: 'postgres',
    host: process.env.POSTGRES_HOST,
    port: 5432,
    username: process.env.POSTGRES_USER,
    password: process.env.POSTGRES_PASS,
    database: process.env.POSTGRES_NAME,
    entities: [
      './src/modules/**/infra/typeorm/entities/*.ts'
    ],
    migrations: [
      './src/shared/infra/typeorm/migrations/*.ts'
    ],
    cli: {
      migrationsDir: './src/shared/infra/typeorm/migrations',
    },
  },
  {
    name: 'mongo',
    type: 'mongodb',
    host: process.env.MONGO_HOST,
    port: 27017,
    database: process.env.MONGO_NAME,
    useUnifiedTopology: true,
    entities: [
      './src/modules/**/infra/typeorm/schemas/*.ts'
    ]
  }
];
```

2. Run `yarn typeorm migration:create -n CreateUsers`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Kubuntu 20.04 |
| Node.js version     | v14.15.4 |
| Typescript version  | v4.2.2 | 
| TypeORM version     | v0.2.31 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
This seems like a local environment issue, not an issue with typeorm.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
