### ISSUE TITLE
Run all pending migrations but when one of them failed, the previous applied migration not revert (not atomic)

### ISSUE THREAD

**Issue by wildansupernova** [typeorm/typeorm#7458]
## Issue Description
I want to make runMigrations(), run all pending migrations either with rollback transaction (combined) or reverting when one of pending migration failed to run. So it is easy to revert applied pending migration without running manually undoLastMIgration.

### Expected Behavior
Reverting or rollback transcation when one of pending migrations failed

### Actual Behavior
I go through the typeorm code and found that there is already using transaction when running runMIgrations but somehow if there is A and B pendingMIgration and then when runnning sequentially [A,B] and then B failed and then A still applied not reverting or rollback.

### Steps to Reproduce
I create repo for this https://github.com/wildansupernova/typeorm-migrations-atomic-problem
1. You can create database and config the name of the database in migration.ts
2. There is already 2 migrations in there created by me. 
3. For example I create table `sdasd` and then run the migration.ts with ts-node. MIgration A success applied but B failed. After that A still intact in the database not reverting/rollback

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Ubuntu 20.04      |
| Node.js version     | v12.20.1 | 
| Typescript version  | v3.9.9 | 
| TypeORM version     | v0.2.31 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Val-istar-Guo** [comment]
https://github.com/typeorm/typeorm/issues/7367

**Comment by imnotjames** [comment]
> #7367

Unrelated.

Set the migration transaction type to `all`.

**Comment by artzyziv** [comment]
Some problem here.

@imnotjames how to set migration transaction type?

In my case, transaction variable in MigrationExecutor is "all", and queryRunner.rollbackTransaction() executed without error in executePendingMigrations method, but changes in mysql database still not rollback when migration throw error.

Is there anything I missing?

Thanks a lot!

**Comment by imnotjames** [comment]
So - reading the MySQL documentation

https://dev.mysql.com/doc/refman/8.0/en/atomic-ddl.html

> DDL statements, atomic or otherwise, implicitly end any transaction that is active in the current session, as if you had done a COMMIT before executing the statement. This means that DDL statements cannot be performed within another transaction, within transaction control statements such as START TRANSACTION ... COMMIT, or combined with other statements within the same transaction. 

So - if that documentation is to be believed - DDL changes in MySQL cannot be wrapped in transactions.  We should probably throw an error when you try to using MySQL.
