### ISSUE TITLE
Avoiding SQLITE_BUSY

### ISSUE THREAD

**Issue by Deilan** [typeorm/typeorm#746]
How can one avoid `SQLITE_BUSY` error while using `typeorm` along with `sqlite3`?

**Comment by pleerock** [comment]
Why do you have this error? Im not sure your error is related to typeorm

**Comment by Deilan** [comment]
@pleerock One has this error in case when one tries to write to `sqlite3` db simultaneously within several simultaneously incoming requests (Node, express, etc.). If one of the requests has been started, but not yet finished, and then the second has been started too, the database will respond with `SQLITE_BUSY` error. Even if there are several different typeorm's connections are being utilized for that. I think it would be great to have a workflow to avoid that implemented out-of-the-box in typeorm, so the developers using `typeorm` doesn't have to reinvent the wheel each time.

**Comment by pleerock** [comment]
Okay I think we can try to implement this

**Comment by pleerock** [comment]
So, back to this issue. How to implement it in typeorm? Can you give me a hints?

**Comment by pleerock** [comment]
I'll close it until someone suggest something real.

**Comment by Deilan** [comment]
@pleerock No one will even look into it while it's closed.

**Comment by pleerock** [comment]
Only those who encounter this problem need its solving and those users definitely can find this issue and continue discussion. I have to close hardly resolvable issues because its pain to maintain lot of opened github issues, less issues to maintain -> faster and more effective it will be done.

**Comment by natew** [comment]
Realize I can get it really easily just by running lots of inserts. I'll try setting up a test case for this.

**Comment by davilopez90** [comment]
Is there any advance on this issue? I'm running into this problem right now.
For now, the only solution I found, is to try every writing on database "N" times (if I catch a QueryErrorFailed: Sqlite Database locked I try it again in a finite loop until it gets to write).

But I think it should be a better solution for this.

**Comment by shirshak55** [comment]
if there are multiple node process then this issue come back . Is there no easy solution so weird :(?
