### ISSUE TITLE
Feedback: HasManyThrough and better documentation is the bottleneck for this library to become standard

### ISSUE THREAD

**Issue by mmahalwy** [typeorm/typeorm#7464]
## Feature Description
- Add HasManyThrough
- Better documentation (I can help!)

### The Problem
I spent a number of days laying the land on the different ORMs. In my mind, there are 2 major blockers for this library to become the de facto solution when it comes to ORM (this or Prisma)

**Add HasManyThrough**
This has been debated thoroughly in other issues but I do think this is a huge blocker for folks coming from ActiveRecord. HasManyThroughs are pretty standard and accepted in the Rails world. This library requires some hand-written efforts with query builder (took me a few tries / hours to get it to work)

**Better documentation**
This is a part where the community should step up, including myself, but the documentation is thin and lacking. There are some major dos/donts that aren't called out (forgetting `Promise` with association due to typescript inferring). 

### The Solution
- HMT: implement it!
- Docs: suggest to the community how folks could help. Or a complete docs overhaul. type-graphql has a great website and docs: https://typegraphql.com/

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?
Docs, yes. HMT, I don't know where to start

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Fabiencdp** [comment]
Hi, HasManyThrough exist in some way : you can use @manyToMany with @JoinTable decorators to achieve that behavior ? Is that what your looking for ? Also you don't need to create the middle entity with this solution.

I totally agree about the documentation.
Also, sometimes it's hard to understand what happen with the datamaper. despite everything, typeorm is really powerful !

**Comment by mmahalwy** [comment]
@Fabiencdp most use cases for has many through is to add columns to the joining model.

**Comment by Fabiencdp** [comment]
@mmahalwy, not sure to understand. 

This kind of relation should be possible using @ManyToMany + @JoinTable 
![image](https://user-images.githubusercontent.com/6182473/112110462-359fbd00-8bb3-11eb-92bc-72a39dc50fb7.png)

With something like this https://typeorm.io/#/decorator-reference/jointable

**Comment by mmahalwy** [comment]
@Fabiencdp see: https://typeorm.io/#/many-to-many-relations/many-to-many-relations-with-custom-properties. You have to define the entity yourself, but there is no decorator to support category -> posts. That's has many through

**Comment by imnotjames** [comment]
If you don't care about the middle entity and just want a many-to-many through another table then yes @Fabiencdp has the right idea.  I don't think duplicate functionality is preventing adoption of typeorm.

Regarding the other note, there's loads of other open issues about our documentation that're actionable.  This issue isn't.

Please feel free to help improving the documentation.

**Comment by alea12** [comment]
@mmahalwy Having a similar issue here. `@JoinTable` is not an option for me, since I want to include specific fields in the middle table. In @Fabiencdp 's example, the junction table seems to have `appointmentDate` field, but I can't find how to achieve that with `@JoinTable` decorator options.

> This library requires some hand-written efforts with query builder

Is it possible for you to kindly provide me with ideas on how to implement HMT in query builder?
