### ISSUE TITLE
Cannot return null for non-nullable field User.password

### ISSUE THREAD

**Issue by lucafregoso** [typeorm/typeorm#7465]
## Issue Description

I created a User Model, with the Column password:
```
 @Field(() => String)
  @Column({
    default: "",
    select: false,
    transformer: new EncryptionTransformer({
      key: 'e41c966f21f9e1577802463f8924e6a3fe3e9751f201304213b2f845d8841d61',
      algorithm: 'aes-256-cbc',
      ivLength: 16,
      iv: 'ff5ac19190424b1d88f9419ef949ae56'
    }),
    type: "varchar",
  })
  password: string;
```

but if I query indicating also password in the attributes 
```
query {
  user(id: "1") {
    id
    firstname
    lastname
    password
  }
}
```

I receive the error "Cannot return null for non-nullable field User.password" instead of the result without password

### Expected Behavior

```
{
  "data": {
    "user": {
      "id": "1",
      "firstname": "FirstName",
      "lastname": "LastName"
    }
  }
}
```

### Actual Behavior

```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field User.password.",
      "locations": [
        {
          "line": 6,
          "column": 5
        }
      ],
      "path": [
        "user",
        "password"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field User.password.",
            "    at completeValue (node_modules/graphql/execution/execute.js:568:13)",
            "    at node_modules/graphql/execution/execute.js:500:16",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at async Promise.all (index 3)",
            "    at async Promise.all (index 0)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

### Steps to Reproduce

```typescript
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column } from 'typeorm';
import { ObjectType, Field, ID } from 'type-graphql';
import { EncryptionTransformer } from 'typeorm-encrypted';


@ObjectType()
@Entity()
export class User extends BaseEntity {
  @Field(() => ID)
  @PrimaryGeneratedColumn()
  id: string;

  @Field(() => String)
  @Column()
  firstname: string;

  @Field(() => String)
  @Column()
  lastname: string;

  @Field(() => String)
  @Column({
    unique: true
  })
  nickname: string;

  @Field(() => String)
  @Column({
    unique: true
  })
  email: string;

  @Field(() => String)
  @Column({
    default: "",
    select: false,
    transformer: new EncryptionTransformer({
      key: 'e41c966f21f9e1577802463f8924e6a3fe3e9751f201304213b2f845d8841d61',
      algorithm: 'aes-256-cbc',
      ivLength: 16,
      iv: 'ff5ac19190424b1d88f9419ef949ae56'
    }),
    type: "varchar",
  })
  password: string;
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v13.8.0 | 
| Typescript version  | v3.8.3  | 
| TypeORM version     | v0.2.24| 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by JipSterk** [comment]
I think its because of [```select: false```](https://github.com/typeorm/typeorm/blob/master/docs/select-query-builder.md#hidden-columns). Maybe you could try the example provided?

**Comment by imnotjames** [comment]
This doesn't seem to be related to typeorm.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
