### ISSUE TITLE
can we call oracle pl/sql stored procedure in typeorm

### ISSUE THREAD

**Issue by rajuaddalaOracle** [typeorm/typeorm#7466]
### Actual Behavior

```
// include the output in code tags like these!
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | vX.Y.ZZZ | 
| Typescript version  | vX.Y.ZZZ | 
| TypeORM version     | vX.Y.ZZZ | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
No.

If you'd like a feature request please create a more detailed issue which describes the feature you'd like.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by rajuaddalaOracle** [comment]
Thanks.
I was able to use connection directly and call PL/SQL.


    async.autoInject({
      updateScores: (next) => {
        const callSql = `
        BEGIN
          account_scores.create_or_merge_scores(:1, :2, :3);
        END;
       `;
        const params = [
          {dir: oracledb.BIND_IN, type: oracledb.STRING, val: criteriaSetId},
          {dir: oracledb.BIND_OUT, type: oracledb.STRING},
          {dir: oracledb.BIND_OUT, type: oracledb.STRING},
        ];
        this.getOracleDbMediumService().callSqlStoredProc(callSql, params, (err, results) => {
          this.logCalculationMessage('Done updating score changes', logData);
          if (err) {
            next(err);
          } else {
            const [plSqlStatus, plSqlAppErrorStatus] = results;
            this.logCalculationMessage(plSqlStatus, logData);
            const errorFromSQL = (plSqlAppErrorStatus !== 'OK') ? plSqlAppErrorStatus : null;
            next(errorFromSQL);
          }
        });
      },
      
      
      
     callSqlStoredProc(proc, params, callback) {
    (async () => {
      let results;
      try {
        const connection = await OracleDbConnection.getConnection(this.connectionName);
        // TODO replace with rawQuery after we enhance rawQuery to handle pl/sql
        results = await connection.query(proc, params);
      } catch (err) {
        await this._handleError(err);
        return void callback(err, null);
      }
      callback(null, results);
    })();
  }
