### ISSUE TITLE
printSql doesn't work

### ISSUE THREAD

**Issue by mimoid-prog** [typeorm/typeorm#7468]
## Issue Description
Using `.printSql()` in query builder doesn't log the query.  Apparently it used to work [https://github.com/typeorm/typeorm/issues/1331](https://github.com/typeorm/typeorm/issues/1331) but now it doesn't.
The only way to see the queries is to set `logging: true` which is not good beacause it logs all queries.

### Expected Behavior
Logged query in the console.

### Actual Behavior
It prints empty line. 

### Steps to Reproduce
```
  const users = await userRepo
    .createQueryBuilder("user")
    .printSql()
    .getMany();
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Windows 10  |
| Node.js version     | v14.9.0 | 
| Typescript version  | v^4.1.3 | 
| TypeORM version     | v^0.2.31 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by aardvarkk** [comment]
Yeah, this caught me. I didn't see the output so I stepped into printSql to see what it was doing and found that the logger only logs anything if logging is set to "all", true, or "query", at which point the query would have been logged out anyway (along with every other query), so there's no point in trying to run printSql at that point!

**Comment by dmshvetsov** [comment]
> Yeah, this caught me. I didn't see the output so I stepped into printSql to see what it was doing and found that the logger only logs anything if logging is set to "all", true, or "query", at which point the query would have been logged out anyway (along with every other query), so there's no point in trying to run printSql at that point!

isn't setting `logging: ['all']` or `logging: ['query']` makes queries to be logged to the console even if you do not use `printSql`?

**Comment by aardvarkk** [comment]
Yes -- that's what I was trying to say. I could only make `printSql` work by enabling llogging "all", true, or "query". But once you do that, *all* queries are logged (even ones you didn't ask to `printSql` for), so it's kind of useless.

**Comment by imnotjames** [comment]
`getQueryAndParameters` and then log it out as you'd like?  I feel like `printSql` should be deprecated...

**Comment by imnotjames** [comment]
This logs it out even if it hasn't been executed as if you had to the query logger.

This is working as intended.
