### ISSUE TITLE
Row Level Security -- setting configuration parameters (ie session variables) in findOptions, and using .*?QueryBuilder

### ISSUE THREAD

**Issue by qwertey6** [typeorm/typeorm#7472]
## Feature Description

This issue is a feature request for (and a PR which implements) a way to set custom configuration parameters (ie session variables) when executing find* queries using the EntityManager, as well as a lower level interface for accomplishing the same end using the existing *QueryBuilder/s.

I already have a PR which implements this. I am creating this GH issue to get an issue number to reference in my implementation, to properly submit the PR for review.

### The Problem

Our current state:

To enforce RBAC and organization-based user-isolation in our product, our team has created an elaborate *partial* implementation of `EntityManager` which figures out how to join tables to determine which `organization` any other object belongs to. If an object and a user belong to the same organization, then we can action on this entity. Otherwise, this entity should be hidden to this user. This joining looks like `comment.postId => post.id, post.organizationId => organization.id`. 

Motivation:

This solution has worked for now, but now we need a full implementation of `EntityManager`, to support all of the find*, update, delete, softDelete, etc etc methods.

We found the implementation for this full custom `EntityManager` to be a massive overhaul, and realized that if we could leverage postgresql's built in `Row Level Security` features, we could create a far more secure system with much less effort. Our problem then, was that typeorm did not support setting custom configuration parameters (ie session variables) in postgres.

We find the lack of wrappers/ a DSL for defining custom row level security policies acceptable (it would be a simple migration we would have to hand craft, and this is okay), so we have not approached this feature in typeorm.

### The Solution

This solution requires minor changes in a few key places. First let's touch on the dev-facing interfaces.
FindOneOptions.ts: an additional option
```typescript
...
    /**
     * An object containing session variables to use for this query. This will set `transaction` to true to prevent session variables bleeding across queries.
     * This can be used to help implement row level security for application users.
     */
    sessionVariables?: {[variableName: string]: ObjectLiteral};
...
```

QueryBuilder then needs a way to set this, so we created a method `setSessionVariables(...)` (same param type as the type above)

Finally, QueryRunner then needs a way to run this query (and big emphasis on _SAFELY_ running this query, as we do not want simultaneous queries with different session vars to overwrite each other's vars). We accomplish this by:
* forcing the use of a transaction if specifying sessionVariables, and;
* If running a query with session variables set, first start the transaction (if one isn't started yet), THEN set any session vars, finally only THEN do we execute the query.

### Considered Alternatives

For my team's internal approach, we tried to override certain usages of QueryRunner, and the different .*?QueryBuilder/s, but this solution was too hacky and unstable. A better approach was to contribute here 🙂 

### Additional Context

What are configuration parameters (session variables)?
https://www.postgresql.org/docs/current/functions-admin.html
https://www.postgresql.org/docs/current/sql-set.html

What is row level security (RLS)?
https://www.postgresql.org/docs/current/ddl-rowsecurity.html
https://www.postgresql.org/docs/current/sql-createpolicy.html

This feature has already been requested before (sometimes with a feature request for a DSL for specifying policies, sometimes without):
https://github.com/typeorm/typeorm/issues/5857
https://github.com/typeorm/typeorm/issues/3290. (for mssql, whereas this PR is focussed on postgresql, although the solution can be extended for other DBMS's (unfortunately out of scope for my company's use case))

### Relevant Database Driver(s)

- [x] `postgres`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [x] **_I have already implemented and unit tested this new feature._**

**Comment by qwertey6** [comment]
We ended up implementing configuration parameters outside of typeorm, as a separate layer which handles acquiring/releasing and QueryRunners  from the pool and setting/unsetting their session variables.

**Comment by briandiephuis** [comment]
@qwertey6 Could you maybe share a bit more about your setup? How can you set variables for the query-runners that TypeORM will use outside of TypeORM (scoped to the current request)?

**Comment by L-U-C-K-Y** [comment]
@qwertey6 I would also be interested in how you solved this issue without creating sessions all the time.
