### ISSUE TITLE
FindOne not adding Limit 1 to query

### ISSUE THREAD

**Issue by robinjhuang** [typeorm/typeorm#7481]
I believe there have been previous issues raised for this, and then a [PR merged](https://github.com/typeorm/typeorm/pull/3014) to fix it. 

Now it is broken again. Shouldn't this line be

```
if (passedId) { 
    findOptions = {
        ...(findOptions || {}),
        take: 1,
    };
}

```

https://github.com/typeorm/typeorm/blob/3d876c61fafc815e429c68f4f4e1ab79e47c7b9c/src/entity-manager/EntityManager.ts#L787

I can put up a PR if this is a real issue.

**Comment by imnotjames** [comment]
I don't think so.  If an ID hasn't been passed we use `take` to apply a limit.  Otherwise we assume that what's been passed is a PK.

Related commit that introduced the change: https://github.com/typeorm/typeorm/pull/5293/commits/ccaa74196f7f7341abc66ef0da821ca71e61112a
