### ISSUE TITLE
TSLint: Shadowed name: 'U'(no-shadowed-variable)

### ISSUE THREAD

**Issue by Deviad** [typeorm/typeorm#7488]
Hello,
I am getting the error in the title with TS 4+.

https://github.com/typeorm/typeorm/blob/3d876c61fafc815e429c68f4f4e1ab79e47c7b9c/src/common/DeepPartial.ts#L7

Thanks.

**Comment by kevin-lindsay-1** [comment]
You should be using `@typescript-eslint`. IIRC tslint has been dead for a few years.

**Comment by kevin-lindsay-1** [comment]
Your issue is that you've defined something twice, and it's not going to hurt anything, but it's bad form, due to bad code readability.

https://eslint.org/docs/rules/no-shadow

**Comment by imnotjames** [comment]
Given that it's not a breaking change and we don't check our code against tslint or this rule I'm closing this issue.

If you believe we should be applying that rule please open a new issue.
