### ISSUE TITLE
Fix deprecation warnings for highlight.js v10.7

### ISSUE THREAD

**Issue by SerhiiBulakh** [typeorm/typeorm#7489]
![typeorm](https://user-images.githubusercontent.com/46135982/111993727-a09fb400-8b1f-11eb-9e3c-97de44327dc2.PNG)

**Comment by loriswit** [comment]
This seems to be caused by [cli-highlight](https://github.com/felixfbecker/cli-highlight/blob/d9613c9c5cbe8a0acb29faad2af934114d96d1ba/src/index.ts#L97).

**Comment by SerhiiBulakh** [comment]
> This seems to be caused by [cli-highlight](https://github.com/felixfbecker/cli-highlight/blob/d9613c9c5cbe8a0acb29faad2af934114d96d1ba/src/index.ts#L97).

yes, you are right)

**Comment by dylvaz** [comment]
So what exactly is the fix for this rn? I saw @loriswit made a PR to fix this, but I'm getting tired of seeing these console log statements 😅

**Comment by loriswit** [comment]
@dylvaz Right now, you could temporarily downgrade your local installation of highligh.js as a workaround:
```bash
npm i highlight.js@10.6 --no-save
```
Then once the fix for cli-highlight is released, simply run:
```bash
npm update
```
