### ISSUE TITLE
Change connections param from array to object

### ISSUE THREAD

**Issue by chiaramaya** [typeorm/typeorm#7492]
## Feature Description

Good morning,
I think to improve the performance with multiple connections you could change the _connections_ param in _ConnectionManager_ from array to object with key is the _name_ connection

### The Problem

I use typeorm with a lot of multiple connections and the _getConnection_ isn't very performant.

### The Solution (js)

`this.connections = {}`

when create a connection:

`this.connections['nameConnection'] = Connection`

the result will be (for example with _default_ connection and _log_ connection):

`this.connections = {
  default: Connection,
  log: Connection,
}`

when use for example get connection the performance it will be better (there is anymore find):

`return this.connections[nameConnection]`

### Additional Context

no additional context

### Relevant Database Driver(s)

all driver

### Are you willing to resolve this issue by submitting a Pull Request?

no, I never used typescript

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

Thank you so much
Chiara

**Comment by kevin-lindsay-1** [comment]
This would be a breaking change, but it's hard to argue against the potential performance increase of a map lookup vs an array search.
