### ISSUE TITLE
highlight.js 10.7.0 Deprecated issue - typeorm@0.2.31, cli-highlight@^2.1.10

### ISSUE THREAD

**Issue by justinlevi** [typeorm/typeorm#7494]
## Issue Description

Seeing the following error when running my code 

```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```

### Expected Behavior

I expect no warnings or errors to be thrown. 

### Actual Behavior

The error above. 

### Steps to Reproduce

```
    "typeorm": "^0.2.31",
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Mac Latest OS         |
| Node.js version     | 15.11 | 
| Typescript version  | ^4.2.3 | 
| TypeORM version     | 0.2.31 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [x] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by phillipplum** [comment]
See: https://github.com/typeorm/typeorm/issues/7489

**Comment by loriswit** [comment]
This has been fixed: felixfbecker/cli-highlight#127

**Comment by dylvaz** [comment]
thanks a million @loriswit

**Comment by kevin-lindsay-1** [comment]
@justinlevi can you close this issue if you're good?
