### ISSUE TITLE
Need option for Mysql's full text search

### ISSUE THREAD

**Issue by AegoYu** [typeorm/typeorm#750]
There seems no option for me to generate a column with fulltext index.

**Comment by pleerock** [comment]
can you provide sql code examples in what queries and what you expect to be included?

**Comment by pleerock** [comment]
One thing is probably to be able to set `fulltext: true` in `@Index` decorator which will create following sql query:

```sql
CREATE FULLTEXT INDEX name ON table
```

Where else?

**Comment by pleerock** [comment]
Why did you close this?

**Comment by KrisJordan** [comment]
Would agree with the utility of an option in the @Index decorator for indicating a FULLTEXT index and encourage reopening unless there is another recommended solution.

**Comment by jcudzich** [comment]
@pleerock What about fulltext option in `@Index` decorator?

**Comment by AlexMesser** [comment]
`SPATIAL` and `FULLTEXT` index types introduced in `typeorm@0.2.0-alpha.45`. You can try it via `npm i typeorm@next`.

Example: 

```typescript
@Entity()
@Index(["name"], { fulltext: true })
@Index(["point"], { spatial: true })
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column("point")
    point: string;
}
```
