### ISSUE TITLE
ueryBuilder: bug of  `select`  with relation

### ISSUE THREAD

**Issue by shiyiya** [typeorm/typeorm#7500]
## Issue Description

```ts

 this.UserRepository.createQueryBuilder('u')
  .select(['u', 'f.id']) // Although there are many fans, it only returns the first one
 .leftJoin('u.fans', 'f') //
.getMany();

```

### Expected Behavior
return all fans id
```
 {
    id:1,
    fans: [{id:1},{id:2} , .....]
  }
```

### Actual Behavior

**only return the first fans id .**
only one ~~
```
 {
    id:1,
    fans: [{id:1}]
  }
```

### Steps to Reproduce

```typescript
@Entity()
class User {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @OneToMany(() => Fans, (f) => f.follow)
  fans?: Fans[];
}

@Entity()
class Fans {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ManyToOne(() => User, (u) => u.fans)
  follow?: User[];
}


 this.UserRepository.createQueryBuilder('u')
 .leftJoin('u.fans', 'f')
  .select(['u', 'f.id'])
.getMany();

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v12.16.3 | 
| Typescript version  | typescript@4.2.3| 
| TypeORM version     | typeorm@0.2.31 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by omidh28** [comment]
@shiyiya Did you try `leftJoinAndSelect` instead?

**Comment by shiyiya** [comment]
@omidh28 That will find out the whole `fans` , not just the ID field

**Comment by iamstormcoder** [comment]
@shiyiya you have incorrectly used relation decorators here. Instead of ManyToOne/OneToMany you need to use ManyToMany here and JoinTable in one of the entities.
```
@Entity()
class User {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ManyToMany(() => Fans, (f) => f.follow)
  @JoinTable()
  fans?: Fans[];
}

@Entity()
class Fans {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ManyToMany(() => User, (u) => u.fans)
  follow?: User[];
}
```

**Comment by shiyiya** [comment]
I'm sorry, the above is an example I wrote casually, which is actually `one to many`

@iamstormcoder @omidh28 

```
@Entity()
class Post extends BaseEntity{
  @OneToMany(() => Rate, (Rate) => Rate.bindPost)
  rate?: Rate[];
}

@Entity()
export default class Rate extends _BaseEntity {
  @Column({ type: 'tinyint' })
  rate: number;

  @ManyToOne(() => Post, (post) => post.rate , {
    onDelete: 'SET NULL',
  })
  bindPost: Post;
}


this.PostRepository.createQueryBuilder('p').select(['p','a.rate']) .leftJoin('p.rate', 'a')
```

![image](https://user-images.githubusercontent.com/34017352/115981186-a415d780-a5c4-11eb-9b70-d21d31d2c0ac.png)

![image](https://user-images.githubusercontent.com/34017352/115981217-da535700-a5c4-11eb-9930-4503b67932a1.png)

**Comment by shiyiya** [comment]
it's work.

add select `a.id`

`this.PostRepository.createQueryBuilder('p').select(['p','a.rate','a.id']) .leftJoin('p.rate', 'a')`
