### ISSUE TITLE
Where Not IN array

### ISSUE THREAD

**Issue by hamzamumtaz007** [typeorm/typeorm#7503]
Can someone please suggest an inverse of IN, i have an array of Id's which i want to exclude from the result. Currently i have found an IN query which includes the values in array only:

const posts = await manager.createQueryBuilder(Post, "post")
    .where("post.authorId IN (:...authors)", { authors: [3, 7, 9] })
    .orderBy("post.createDate")
    .getMany();

I need something which excludes the id's from array in final result

**Comment by Cerwym** [comment]
You can combine an operator with another. To get the inverse of IN, use NOT.

i.e `.where("post.authorId NOT IN (:...authors)", { authors: [3, 7, 9] })`

**Comment by hamzamumtaz007** [comment]
I have tried this but it doesn't work

**Comment by kevin-lindsay-1** [comment]
```ts
import { In, Not } from 'typeorm';
const posts = await manager.find(Post, {
  where: [
    {
      authorId: Not(In(authorIds))
    }
  ],
  order: {
    createDate: 'ASC'
  }
})
```

@hamzamumtaz007  Does this work?

**Comment by imnotjames** [comment]
It should - if it doesn't please open a bug report.

**Comment by hamzamumtaz007** [comment]
@kevin-lindsay-1 @imnotjames thanks for the help, i figured out a solution.

**Comment by AaronMBMorse** [comment]
@hamzamumtaz007 What was your solution? I am running into the same issue with Not(In(Array))
