### ISSUE TITLE
Change `@Entity({name: ''})` to lowercase/uppercase based on db type

### ISSUE THREAD

**Issue by aruan-cuenca-emasoftware** [typeorm/typeorm#7504]
### What was unclear or otherwise insufficient?
Change `@Entity({name: ''})` property to lowercase/uppercase based on db type

### Additional Context
**TL;DR:** I need to use an uppercase entity name on `@Entity({name: ''})` when my default database connection type is Oracle and lowercase when it's Postgres.

Hi there! I'm using TypeORM with NestJS and I have a doubt about the `@Entity` decorator. I adopted the asynchronous way to configure TypeORM (`TypeORMModule.forRootAsync()`) to fetch the database configs from another service. These configurations lead to an Oracle database connection or a Postgres database connection. When using Oracle, I need the `@Entity({name: ''})` to be uppercase and when using Postgres, it should be lowercase. Is there a way to do it? Thank you!

### Relevant Database Driver(s)
- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [x] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by aruan-cuenca-emasoftware** [comment]
Also, would it be possible to replicate this behaviour on the `@Column()` decorator?

**Comment by imnotjames** [comment]
If you need to do different definitions for different databases you'll probably have to use separate entity schemas https://typeorm.io/#/separating-entity-definition

Generally, though, this isn't a feature provided by TypeORM.
