### ISSUE TITLE
Less strict checking of ID:s in save() - number vs string

### ISSUE THREAD

**Issue by attesaarela** [typeorm/typeorm#7510]
### The Problem

Many people are using TypeORM with all kinds of frameworks which aren't strictly typescript. It seems that for example in JSON parsing, integer ID:s in complex data structures can be mistakenly converted to string.

This causes annoying problems with save() where it for instance tries to insert duplicate rows in ManyToMany relations, not recognizing that the row already exists. 

While this is strictly speaking a problem of incorrect usage of TypeORM, I'm proposing a solution which would make TypeORM easier to use.

### The Solution

When the user tries to save() an entity, TypeORM proceeds to check which rows already exist in the database (For example in persistence/subject-builder/ManyToManySubjectBuilder.ts)

When checking for which rows already exist in database (OrmUtils.ts : compareIds), if the user's data structure contains ID:s of type string which should really be integers, could we try parsing the strings into integers, and if the user's data structure contains integers in string format which match integer ID:s that already exist in the database, could we return "true" in OrmUtils.ts : compare2Objects ?

At least in SQL databases, I don't see how this could break anything, since the ID:s in an SQL database will certainly have a clearly defined type anyway. Therefore there is no reasonable use case where someone would want SQL database persistence to distinguish between string and integer ID:s for example.

Note: I don't have MongoDB expertise, the only thing I can imagine could go wrong with this is if somebody wants MongoDB persistence to distinguish between string and integer ID:s of the same value for some reason.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by kevin-lindsay-1** [comment]
I don't want typeorm to attempt to parse an integer from a value when I give it a string.

This sounds like you could simply do `findByIds(idsAsStrings.map(id => parseInt(id))`.

**Comment by attesaarela** [comment]
Yes, it is possible for the user to handle it of course. I ended up writing a function like this for handling id : s in nested data structures parsed from JSON before saving to TypeORM:

`function convertIdsToNumeric(obj) {
    if ((obj == null) || (typeof(obj) !== "object")) {
        return obj
    }

    if (Array.isArray(obj)) {
        for (var k = 0 ; k < obj.length ; k++) {
            obj[k] = convertIdsToNumeric(obj[k])
        }
        return obj
    } else {
        var keys = Object.keys(obj)
        for (var k = 0 ; k < keys.length ; k++) {
            obj[keys[k]] = convertIdsToNumeric(obj[keys[k]])
        }
        if (("id" in obj) && (typeof(obj["id"]) === "string")) {
            obj["id"] = parseInt(obj["id"])
        }
    }

    return obj
}`

(Note that it's only ID : s that require this kind of processing, with fields other than id : s TypeORM seems to already work the way a not-uber-careful user might expect, and accepts integer values given as string for fields that are integers in SQL database!)

**Comment by kevin-lindsay-1** [comment]
> TypeORM seems to already work the way a not-uber-careful user might expect, and accepts integer values given as string for fields that are integers in SQL database!

That's likely your flavor of SQL doing that, not TypeORM.

**Comment by imnotjames** [comment]
TypeORM shouldn't be changing up types like this.  If you need this you should try to `parseInt` the data.
