### ISSUE TITLE
How to do batch insert using the query builder syntax along with nested entities?

### ISSUE THREAD

**Issue by jasonlimantoro** [typeorm/typeorm#7513]
### What was unclear or otherwise insufficient?

How to do batch insert using the query builder syntax?
Currently I have the following syntax:

```ts
const tagRepository = connection.getRepository(Tag);
const [tag1, tag2, tag3] = await tagRepository.find({ take: 3 });
await connection
	.createQueryBuilder()
	.insert()
	.into(Post)
	.values([
		{
			title: "First post",
			tags: [tag1, tag2, tag3],
		},
		{
			title: "Second post",
			tags: [tag1, tag3],
		},
	])
	.execute();
```
It does create the whole Post entities, however the tags are not associated.
### Recommended Fix

The tags should be associated.

### Additional Context

`Post` and `Tags` have many-to-many relationships, set up using the `ManyToMany` decorator.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by kevin-lindsay-1** [comment]
`Insert` doesn't handle relations, last I checked.

I recommend using a transaction to create all the child entities, inserting the parent entity, and then using `.save(Parent)` to easily sync them all up. I recommend using `insert` before `save` so that you can fail rather than accidentally update a record.

**Comment by kevin-lindsay-1** [comment]
If you want to batch them, I recommend creating a `map` of async functions for each Parent entity, and using `Promise.all(promises)` to execute them all at once.

**Comment by imnotjames** [comment]
That's correct - the insert query builder is much simpler in how it operates.  By design it does not do relations like this.
