### ISSUE TITLE
Unable to use file path for loading entities and Entity Load Order

### ISSUE THREAD

**Issue by thxmike** [typeorm/typeorm#7516]
## Issue Description
Error when using TypeORM, and Typescript with folder path

### Expected Behavior
As reported here
https://stackoverflow.com/questions/66735359/error-when-using-typeorm-and-typescript-with-folder-path
Entities should load without error. 
Currently when using the following tsconfig
```
{
  "compilerOptions": {
    "target": "ES2020",
    "module":"ES2020",
    "esModuleInterop": true,
    "moduleResolution": "node",
    "strict": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "outDir": "bin",
    "types": ["node"],
    "typeRoots": ["../node_modules/@types"],
    "sourceMap": true
  },
  "include": ["**/*.ts"],
  "exclude": ["tests", "node_modules", "lib", "bin", "dist"]
}
```
and package.json
```
{
  "name": "test-api",
  "version": "0.0.12",
  "description": "...",
  "license": "ISC",
  "author": "Me",
  "main": "server.js",
  "type": "module",
  "scripts": {
    "start": "node bin/server.js",
    "build": "npm i && tsc",
    "lint": "./node_modules/.bin/eslint --ignore-path .gitignore .",
    "test": "echo \"Error: currently no test specified\""
  },
  "dependencies": {
    "express": "^4.17.1",
    "mssql": "^6.3.1",
    "reflect-metadata": "^0.1.13",
    "syswide-cas": "^5.3.0",
    "typeorm": "^0.2.31",
    "uuid-mongodb": "^2.4.2"
  },
  "devDependencies": {
    "@types/node": "^14.14.35"
  }
}

```
I get the following error when loading the entities with a string file path - `${process.cwd()}/bin/models/entities/*.js`

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ...\Projects\orders-api\bin\models\entities\Address.js
require() of ES modules is not supported.
require() of ...\Projects\orders-api\bin\models\entities\Address.js from ...\Projects\orders-api\node_modules\typeorm\util\DirectoryExportedClassesLoader.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename Address.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ...
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
Instead rename Address.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\mrivera\Projects\orders-api\package.json.

```
I have tried different combinations of the tsconfig.json but no change. 

I load my connection options as follows

```
return createConnection({
    name: "default",
    type: "mssql",
    host: this._server,
    username: this._user_name,
    password: this._password,
    database: this._database,
    extra: true,
    options: {
        isolation: "READ_UNCOMMITTED",
    },
    entities: [
        `${this._entity_path}/entities/*.js`
    ],
})
```
Here is an example of one of the entities I use
```

import { Column, Entity, Index, OneToMany, PrimaryGeneratedColumn } from 'typeorm';

import { Patient } from './Patient.js';
import { PatientNextOfKin } from './PatientNextOfKin.js';

@Index("PK__Address__3213E83F7240D5FD", ["id"], { unique: true })
@Entity("Address", { schema: "Orders" })
export class Address {
  @PrimaryGeneratedColumn({ type: "int", name: "id" })
  id!: number;

  @Column("nvarchar", { name: "line", length: 500 })
  line!: string;

  @Column("nvarchar", { name: "line2", length: 100 })
  line2!: string;

  @Column("nvarchar", { name: "city", length: 100 })
  city!: string;

  @Column("nvarchar", { name: "state", length: 2 })
  state!: string;

  @Column("nvarchar", { name: "zip", length: 10 })
  zip!: string;

  @OneToMany(() => Patient, (patient) => patient.address)
  patients!: Patient[];

  @OneToMany(
    () => PatientNextOfKin,
    (patientNextOfKin) => patientNextOfKin.address
  )
  patientNextOfKins!: PatientNextOfKin[];
  
}
```

I do not use a ormconfig.json since I cannot persist this data in my repo as these configuration values are load during runtime.

### Steps to Reproduce
tsc
node ..\bin\server.js


### Additional Context

As a work around, I collect each entity in an array and pass it into the connection options. However, I run into another issue which the runtime is unable to load the entities in the correct order which results in another runtime error

> file:///C:/Users/.../Projects/my-api/bin/models/entities/entity1.js:29 __metadata("design:type", Entity2) ^
> 
> ReferenceError: Cannot access 'Entity2' before initialization at file:///C:/Users/.../Projects/my-api/bin/models/entities/entity1.js:29:31 at ModuleJob.run (internal/modules/esm/module_job.js:152:23) at async Loader.import (internal/modules/esm/loader.js:166:24) at async Object.loadESM (internal/process/esm_loader.js:68:5)
>  and is documented here. 

https://stackoverflow.com/questions/66715166/referenceerror-with-typeorm-entity-and-onetomany

### Relevant Database Driver(s)
mssql
### Are you willing to resolve this issue by submitting a Pull Request?

Yes if I knew where to look.

<!--
  Remember that first-time contributors are welcome! 🙌
-->

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.


<!--
  👋 Have a great day and thank you for the bug report!
-->

**Comment by kevin-lindsay-1** [comment]
I transpile my ts to a `./build/` folder, and i keep my entities in `./src/db/entities/`.


Here's my config for entities which works fine:
```ts
createConnection({
  entities: ['build/db/entities/*.js']
})

**Comment by thxmike** [comment]
Yes, in my post, I transpile to the bin directory, the "this._entity_path" variable includes bin in the path. i.e. bin/models/entities. This can be see in the error messages

**Comment by chetrit** [comment]
Same problem here, with an hybrid codebase (js/ts), this problem seems inevitable when updating ts-node to versions 10.x, I don't have any problem with ts-node 9.1.1 though.

**Comment by ChibiBlasphem** [comment]
This is pretty much problematic for any app which is on node 14 and higher and for which the runtime is fully modular.

**Comment by cx690** [comment]
I meet the same problem,and I regist classes by this way.
```js

import path from 'path';
import { fileURLToPath } from 'url';
import { createConnection } from 'typeorm';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const js_files = fs.readdirSync(path.resolve(__dirname, './entities')).filter((f) => {
    return f.endsWith('.js') || f.endsWith('.ts');
});//find all js or ts in entities dir

function* importSth() {
    for (const f of js_files) {
        yield import('./entities/' + f).then((res) => Object.values(res));//import all of them classes
    }
}
const entities = (await Promise.all([...importSth()])).flat();
createConnection({
        type: 'mysql',
        database: 'index',
        username: 'root', 
        password: '123456', 
        host: 'localhost', 
        entities, //regist
})
```

**Comment by justin-echternach** [comment]
try ... "allowSyntheticDefaultImports": true, in tsconfig.json

**Comment by justin-echternach** [comment]
Try adding "allowSyntheticDefaultImports": true, to tsconfig.json

**Comment by Blopaa** [comment]
same problem here using `await import()` and in the imported file is a `getRepository`
