### ISSUE TITLE
TypeORM deleting index with mssql even when synchronize: false 

### ISSUE THREAD

**Issue by andregavaschumann** [typeorm/typeorm#7520]
### Expected Behavior

I expected that wroted index by hand wont drop when synchronize: false  declaration on model, but its beeing deleted every time app start when ormconfig.json synchronize: true

### Actual Behavior

Index beeing droped when app start even with declaration of this shouldnt syncronize

my model:
```
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';

import {
  ITicketModel,
  ETicketType,
  EBaseStatus,
} from '../domain/models/ticket.model';

@Index(["original_id" ])
@Entity('tickets')
@Index("SK01_clients", { synchronize: false })

export class Ticket implements ITicketModel {
  @PrimaryGeneratedColumn()
  id: string;

  @Column()
  original_id: number;

  @Column({ length: 4000 })
  subject: string;

  @Column({ nullable: true })
  justification: string;

  @Column()
  type: ETicketType;

  @Column({ nullable: true })
  category: string;

  @Column()
  status: string;

  @Column()
  base_status: EBaseStatus;

  @Column()
  created_date: string;

  @Column({ nullable: true })
  owner_id: string;

  @Column({ nullable: true })
  owner_team_id: string;

  @Column()
  severity_gut: number | null;

  @Column()
  urgency_gut: number | null;

  @Column()
  trend_gut: number | null;

  @Column('bit')
  resolved_in_first_call: boolean;

  @Column({ nullable: true })
  assigned_in: string;

  @Column({ nullable: true })
  resolved_in: string;

  @CreateDateColumn()
  created_at: string;

  @UpdateDateColumn()
  updated_at: string;
}
```
ormconfig.json
```
[
  {
    "name": "default",
    "type": "mssql",
    "host": "*************",
    "port": ********,
    "password": "*********",
    "username": "********",
    "logging": false,
    "database": "********",
    "useUnifiedTopology": true,
    "entities": ["./dist/modules/**/entities/*.entity{.ts,.js}"],
    "synchronize": true,
    "requestTimeout": 60000,
    "connectionTimeout": 60000
  }
]
```

package.json:
```
{
  "name": "movidesk-api-integration",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest --passWithNoTests --silent --noStackTrace --runInBand --forceExit",
    "test:staged": "yarn test",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --forceExit",
    "test:ci": "yarn test -- --coverage && yarn test:e2e"
  },
  "dependencies": {
    "@nestjs/common": "^7.5.1",
    "@nestjs/config": "^0.6.3",
    "@nestjs/core": "^7.5.1",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/schedule": "^0.4.1",
    "@nestjs/typeorm": "^7.1.5",
    "class-transformer": "^0.3.1",
    "config": "^3.3.4",
    "dotenv": "^8.2.0",
    "ioredis": "^4.19.2",
    "mongodb": "^3.6.3",
    "mssql": "^6.3.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.3",
    "sworm": "^3.8.0",
    "typeorm": "^0.2.31",
    "uuidv4": "^6.2.5"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^7.5.1",
    "@types/cron": "^1.7.2",
    "@types/dotenv": "^8.2.0",
    "@types/express": "^4.17.8",
    "@types/ioredis": "^4.17.8",
    "@types/jest": "^26.0.15",
    "@types/mongodb": "^3.6.3",
    "@types/node": "^14.14.6",
    "@types/redis": "^2.8.28",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.6.1",
    "@typescript-eslint/parser": "^4.6.1",
    "eslint": "^7.12.1",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-prettier": "^3.1.4",
    "git-commit-msg-linter": "^3.0.0",
    "husky": "^4.3.0",
    "jest": "^26.6.3",
    "lint-staged": "^10.5.1",
    "prettier": "^2.1.2",
    "supertest": "^6.0.0",
    "ts-jest": "^26.4.3",
    "ts-loader": "^8.0.8",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.0.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Steps to Reproduce

1. create app with the same version and dependencies
2. create app using nesjs, typeorm and mssql
3. Create index by hand
4. execute app

### My Environment
Ubuntu 20.04
Node
NestJs
MSSQL

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [X] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by kevin-lindsay-1** [comment]
You have `synchronize: true` in your ormconfig.

**Comment by andregavaschumann** [comment]
Yes, I have, but according to documentation when I create a index in model and set synchronize: false to it, it must not be droped by defaul even all the application has models synchronized with my database, or I'm wrong?

**Comment by kevin-lindsay-1** [comment]
I recommend the following:

1. Don't set `synchronize: true` anywhere, in any applications. You should only be using that if you're developing locally as far as I'm aware, and I don't even use that.
2. Set a location for migrations, and have the main service managing the database automatically run the migrations. I don't connect multiple applications to my databases, but theoretically you could have them all try to migrate when they start.

**Comment by imnotjames** [comment]
`synchronize` is not an option for `@Index`

**Comment by kjleitz** [comment]
@imnotjames @kevin-lindsay-1

1. Actually, this _is_ an option for `Index`, and has been for at least 5 years. It is not present in `IndexOptions`; it's a unicorn in one of the function signatures.
2. This option for `Index` is in the TypeORM documentation, and has been for at least 5 years as well.
3. I am also encountering this same issue despite my application being `synchronize: false` across the board, so it has nothing to do with the application being set to `synchronize: true`.

See https://github.com/typeorm/typeorm/issues/7487 (and specifically my comment here: https://github.com/typeorm/typeorm/issues/7487#issuecomment-1557557822)

I think this issue should either be reopened or marked as a duplicate of https://github.com/typeorm/typeorm/issues/7487, or that one marked as a duplicate of this.
