### ISSUE TITLE
Error in calculating distance from latitude and longitude

### ISSUE THREAD

**Issue by hamzamumtaz007** [typeorm/typeorm#7528]
I am facing an issue i am using type orm raw query to calculate distance based on latitude and longitude. My code is as follow

```
const business = await this.readyUserRepository.query('SELECT Round(111.045* DEGREES(ACOS(COS(RADIANS(' + user[0].lat + '))* COS(RADIANS(lat))* COS(RADIANS(' + user[0].lng + ') - RADIANS(`lng`))+ SIN(RADIANS(' + user[0].lat + '))* SIN(RADIANS(lat)))) AS distance from readyuser');
```

here user[0].lat and user[0].lng are the coordinates for user which is the pivot in this case. When i run the query it says there is some error in your query.

**Comment by kevin-lindsay-1** [comment]
Can you format your code _as code_ via ` ```ts ` and `` ` ``, respectively?

Additionally, it may be easier to use string interpolation via:
```ts
repository.query(`SELECT Round(...${user[0].lat}...)`)
```

There's also vscode extensions that let you color-code your comments via tags like:
```ts
repository.query(/* sql */`SELECT ... FROM 'table'`)
```

As it pertains to your actual problem, I'd need to know more about your issue. Your version, database flavor, etc.

It's hard to help you if I have very little information to go off and I can't read your code.

**Comment by imnotjames** [comment]
> here user[0].lat and user[0].lng are the coordinates for user which is the pivot in this case. When i run the query it says there is some error in your query.

Without the query I can't say for sure what your issue is but for one thing you shouldn't be doing string interpolation for this.  Instead, you should be using query parameters.

```
const business = await this.readyUserRepository.query(
    'SELECT Round(111.045* DEGREES(ACOS(COS(RADIANS(?))* COS(RADIANS(lat))* COS(RADIANS(?) - RADIANS(`lng`))+ SIN(RADIANS(?))* SIN(RADIANS(lat)))) AS distance from readyuser',
    [ ser[0].lat, users[0].lng, users[0].lat ]
);
```

**Comment by imnotjames** [comment]
However, because this is a user crafted query I don't think this is an issue with TypeORM but the query you've crafted.  As such, I'm closing this issue out.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
