### ISSUE TITLE
Unidirectional ManyToOne onto Entity with composite keys?

### ISSUE THREAD

**Issue by SamuelMarks** [typeorm/typeorm#753]
How do I create a one-way relation, where each `Album` has 0–∞ `photo`s, but there is no [efficient] way to get 'parent' `album` starting from `photo`?

```
@Entity()
export class Photo {
    @PrimaryColumn()
    name: string;

    @PrimaryColumn()
    filename: string;

    @Column({length: 25})
    description: string;
}
```

```
@Entity()
export class Album {
    @PrimaryColumn()
    name: number;

    @Column()
    name: string;

    // Or was it `OneToMany`?
    @ManyToOne(type => Photo, photo => photo.albums,
               { cascadeInsert: true, cascadeUpdate: true }
    )
    @JoinTable()
    photos: Photo[];
}
```

Related: https://github.com/typeorm/typeorm/issues/58; https://github.com/typeorm/typeorm/issues/476

Thanks for all suggestions

**Comment by pleerock** [comment]
What you need is uni-directional one-to-many. However there is no support of uni-directional one-to-many relations yet. You can only create uni-directional many-to-one.

You do it all wrong. First many-to-one is not array. Its `one`. Second `@JoinTable` is used only for many-to-many relations. You should change your code this way:

```ts
@Entity()
export class Photo {
    @PrimaryColumn()
    name: string;

    @PrimaryColumn()
    filename: string;

    @Column({length: 25})
    description: string;

    @ManyToOne(type => Album, album => album.photos)
    album: Album;
}

@Entity()
export class Album {
    @PrimaryColumn()
    name: number;

    @Column()
    name: string;

    @OneToMany(type => Photo, photo => photo.album)
    photos: Photo[];
}
```

**Comment by SamuelMarks** [comment]
Thanks, but that created a relation on the photo table, so now they're associated:
```
              Table "public.photo"
   Column    |         Type          | Modifiers 
-------------+-----------------------+-----------
 name        | character varying     | not null
 filename    | character varying     | not null
 description | character varying(25) | not null
 albumName   | integer               | 
Indexes:
    "photo_pkey" PRIMARY KEY, btree (name, filename)
Foreign-key constraints:
    "fk_8d514e905b702cc91ad586f4ad2" FOREIGN KEY ("albumName") REFERENCES album(name)
```

```
          Table "public.album"
 Column |       Type        | Modifiers 
--------+-------------------+-----------
 name   | integer           | not null
 desc   | character varying | not null
Indexes:
    "album_pkey" PRIMARY KEY, btree (name)
Referenced by:
    TABLE "photo" CONSTRAINT "fk_8d514e905b702cc91ad586f4ad2" FOREIGN KEY ("albumName") REFERENCES album(name)
```

Removing from `class Photo`:
```
@ManyToOne(type => Album, album => album.photos)
album: Album;
```

Changing `class Album` to:
```
@OneToMany(type => Photo, photo => photo.name)
photos: Photo[];
```

Did compile without error, but it's unclear that this can work at all, especially with `photo => photo.name` 😞 …

Suggestions?

**Comment by pleerock** [comment]
wait, wait, what do you mean by:

```
Removing from class Photo:

@ManyToOne(type => Album, album => album.photos)
album: Album;
```

I told you - you cannot have one-to-many relation without many-to-one side. YOU CANNOT REMOVE THIS SIDE.

**Comment by SamuelMarks** [comment]
Is there any way to have a one sided relation in TypeORM?

So each album can have many photos. But you can't go from photo to album.

**Comment by pleerock** [comment]
as you told you cant have one-to-many relation without having many-to-one in typeorm yet. Just create a bidirectional relation - thats all.

**Comment by SamuelMarks** [comment]
Okay, well I'll be moving away from TypeORM until this support is implemented.

BTW: I have expanded my simple framework to support TypeORM now—in addition to [Waterline](https://github.com/balderdashy/waterline)—here at: [restify-orm-framework](https://github.com/SamuelMarks/restify-orm-framework).

PS: Will add support for another ORM in the next day or so.
PPS: All ORMs work side-by-side, so no harm down.

**Comment by pleerock** [comment]
> Okay, well I'll be moving away from TypeORM until this support is implemented.

strange decision, but okay =)

**Comment by Markvandersteen** [comment]
Is this something that's already implemented? Would be nice...

**Comment by hitallow** [comment]
Is this something that's already implemented? is really good feature.

**Comment by EJMason** [comment]
Hey there! I was able to make this work.[ Looking here in the docs](https://typeorm.io/#/many-to-one-one-to-many-relations) it says: 

>  If you want to use @<span></span>OneToMany, @<span></span>ManyToOne is required. However, the inverse is not required: If you only care about the @<span></span>ManyToOne relationship, you can define it without having @<span></span>OneToMany on the related entity.

So the way I got it it work was this:


``` javascript
@Entity()
export class StudentEntity {

    @ManyToOne(() => TeacherEntity)
    @JoinColumn([{ name: 'teacher_id', referencedColumnName: 'id' }])
    teacher: TeacherEntity
}
```

In a nutshell, it is defined very similar to a 1 to 1 relationship. In the ManyToOne decorator it only has 1 parameter instead of 2. You also add the JoinColumn as the second decorator. For my case I needed to add:

1. The name of the foreign key in my StudentEntity table.

2. The name of the id on the TeacherEntity table.  

I just tested this with typeorm version 0.2.25

**Comment by wjhurley** [comment]
In case anyone ever runs into issues with relationships to tables with composite primary keys, I thought I would share this:
```ts
@Entity()
export class InventoryItem {
    @ManyToOne(() => ShippingDetail)
    @JoinColumn([
        { name: 'trackingNumber', referencedColumnName: 'trackingNumber' },
        { name: 'ticketNumber', referencedColumnName: 'ticketNumber' },
    ])
    public tracking: ShippingDetail;
}
```

**Comment by josemadev** [comment]
@wjhurley and oneToMany relation with composite pks, its posible?

**Comment by wjhurley** [comment]
> @wjhurley and oneToMany relation with composite pks, its posible?

@josemadev I'm sure it's possible, but I haven't had to do it myself, so I couldn't tell you how to achieve that.

**Comment by motawy-citrus** [comment]
I realise that it's being closed but I'm facing the same issue.
I'm using `typeorm: 0.3.6` 
I tried the solution proposed by @wjhurley and it works for the creation of the relation or migrations, but then upon usage I have this error: `null value in column "template_version" of relation "brand_page" violates not-null constraint`.

Declared the relationship as above:
```ts
@Entity({ name: 'brand_page' })
export class BrandPageEntity {
  @ManyToOne(() => TemplateEntity)
  @JoinColumn([
    { name: 'template_id', referencedColumnName: 'id' },
    { name: 'template_version', referencedColumnName: 'version' },
  ])
  template_id: string;

  @Column({ type: 'int', default: 1 })
  template_version: number;
}
```

So the column `template_version` becomes null for some reason just before being saved on the DB. 
This use case it's a simple creation of the resource.

Am I doing something wrong?
