### ISSUE TITLE
yml config is broken

### ISSUE THREAD

**Issue by lev-kuznetsov** [typeorm/typeorm#7531]
## Issue Description

`ormconfig.yml` configuration no longer works, unable to find the default connection.

### Expected Behavior
Should load the config

### Actual Behavior

This is my ormconfig.yml:

```yml
default:
  type: better-sqlite3
  database: any4-test-db
  synchronize: true
```
and I see this when I start my app:
```
[2021-04-03T02:02:43.585Z] FATAL: any4/api/19956 on flying-dutchman.local: Cannot find connection default because its not defined in any orm configuration files.
    Error: Cannot find connection default because its not defined in any orm configuration files.
        at ConnectionOptionsReader.<anonymous> (/Users/levkuznetsov/Documents/webstorm/any4/api/node_modules/typeorm/connection/ConnectionOptionsReader.js:56:35)
        at step (/Users/levkuznetsov/Documents/webstorm/any4/api/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
        at Object.next (/Users/levkuznetsov/Documents/webstorm/any4/api/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
        at fulfilled (/Users/levkuznetsov/Documents/webstorm/any4/api/node_modules/typeorm/node_modules/tslib/tslib.js:114:62)
        at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

This is the connection initiating code:

```ts
export default Promise.resolve()
  .then(async () => createConnection(merge(await getConnectionOptions(), {entities: ['node_modules/@any4/model/src/entities/*.js']})))
  .catch(async error => {
    captureException(error)
    log.fatal(error)
    await flush(error)
    process.exit(-1)
  })
```

### Steps to Reproduce

see above

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   OSX       |
| Node.js version     | v15.13.0 | 
| Typescript version  | v4.2.3 | 
| TypeORM version     | v0.2.32 | 

### Additional Context

It appears that js-yaml returns an array at the top level now, at least that's where I see the divergence between what the code is expecting.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by PierreBeucher** [comment]
Same issue here.

**Comment by janpe** [comment]
Same here

**Comment by Troublor** [comment]
Same here. 

I did a quick inspection on the code and found there seem to be a bug in [`ConnectionOptionsYmlReader`](https://github.com/typeorm/typeorm/blob/beea2e1e4429d13d7864ebc23aa6e58fa01647ea/src/connection/options-reader/ConnectionOptionsYmlReader.ts#L21), where `js-yaml`.`loadAll` is used. 
`loadAll` returns an array instead of an object, which is inconsistent with the assumption [afterwards](https://github.com/typeorm/typeorm/blob/beea2e1e4429d13d7864ebc23aa6e58fa01647ea/src/connection/options-reader/ConnectionOptionsYmlReader.ts#L27) when interpreting the yaml-parsed payload.

**Comment by imnotjames** [comment]
Hi folks!  I've fixed this in the master branch.  You can always test against that to confirm it's fixed.  I was able to confirm it locally working & updated some tests.  Whenever a new release is made it should be fixed.
