### ISSUE TITLE
RethinkDB Support

### ISSUE THREAD

**Issue by ThaDaVos** [typeorm/typeorm#7533]
### The Problem

There seems to be no driver/support for the RethinkDB - it has amazing RealTime data properties which could benefit a lot of projects but I would wish to have such typed syntax as TypeORM offers to work with it.

ps: currently looking on how to code my own integration between the two.

### The Solutions

1. Make it easier to extend TypeORMs supported drivers.
2. Add a build-in option to use RethinkDB

### Considered Alternatives

Monkey patching my own implementation (not really friendly when coding in Typescript)

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`
- [x] `rethinkdb` (new)

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
