### ISSUE TITLE
Support ability to pass custom driver option through TypeORM

### ISSUE THREAD

**Issue by jn-deque** [typeorm/typeorm#7544]
### The Problem

It would be helpful if TypeORM had a mechanism to pass custom options to the underling driver when creating a connection. 

For example, `mysql2` supports the `compress: true` option to enable connection-level compression, but I could not find a way to configure that in TypeORM (no luck with the idea presented in #4661). To prove it works in `mysql2` I was able to enable compression when creating a raw connection:
```
    const mysql2Conn = await mysql2.createConnection({
        "host": "localhost",
        "port": 3306,
        "user": "my_user",
        "password": "some_pass",
        "database": "my_db",
        "compress": true
    });

    mysql2Conn.query('SHOW SESSION STATUS LIKE "Compression"', function(err, results) {

        // prints: "mysql2 compression= ON"
        console.log('mysql2 compression=', results[0].Value);
    });
```

But a similar strategy in TypeORM does not work:
```
    const typeormConn = await createConnection({
        "type": "mysql",
        "host": "localhost",
        "port": 3306,
        "username": "my_user",
        "password": "some_pass",
        "database": "my_db",
        "synchronize": false,
        "migrationsRun": false,
        "compress": true
     } as any);

     const typeormCompress = await typeormConn.query('SHOW SESSION STATUS LIKE "Compression"');

     // prints: "typeorm compression= OFF"
     console.log('typeorm compression=', typeormCompress[0].Value);
```

### The Solution

I'm not sure about the ideal syntax or method signature but maybe something like the following to differentiate between officially support options and then custom option pass-through:
```
    const typeormConn = await createConnection({
        "type": "mysql",
        "host": "localhost",
        "port": 3306,
        "username": "my_user",
        "password": "some_pass",
        "database": "my_db",
        "synchronize": false,
        "migrationsRun": false,
     }, 
     { 
         // custom options for the driver
        "compress": true 
     });
```

### Additional Context

I would also be beneficial to support option passing via the traditional connection string syntax, like so:
```
   const typeormConn = await createConnection({
        "type": "mysql",
        "url": "mysql://my_user:some_pass@localhost:3306/my_db?compress=true",
        "migrationsRun": false,
        "synchronize": false
    });
```

### Relevant Database Driver(s)

Note: tested on `mysql2` but presumably would benefit all database drivers with custom options.

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

Coming from a Java/Hibernate background I applaud the TypeORM team for making this great library.

**Comment by vitorbertolucci** [comment]
I would like to add that typeorm's type `ConnectionOptions` considers `MysqlConnectionOptions`, but does not include mysql2 options, like `decimalNumbers: boolean`, for instance. The documentation says we could use mysql2 package instead of mysql, so it would be nice to include these options.

**Comment by imnotjames** [comment]
Pass extra options not explicitly defined via the `extra` parameter

https://typeorm.io/#/connection-options
