### ISSUE TITLE
The documentation site will not load due to a missing dependency: https://unpkg.com/vue-i18n@9.1.1/dist/vue-i18n.js 

### ISSUE THREAD

**Issue by nkgentile** [typeorm/typeorm#7546]
### Expected Behavior

Read the documentation

### Actual Behavior

The page is blank, and in the console there is the following error:

```
Error] Failed to load resource: the server responded with a status of 404 () (vue-i18n.js, line 0)
[Error] Refused to execute https://unpkg.com/vue-i18n/dist/vue-i18n.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
[Error] ReferenceError: Can't find variable: VueI18n
Global Code (index.js:8)
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | vX.Y.ZZZ | 
| Typescript version  | vX.Y.ZZZ | 
| TypeORM version     | vX.Y.ZZZ | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by angelxmoreno** [comment]
this was reported on https://github.com/typeorm/typeorm.github.io/issues/44

Please use https://typeorm.netlify.app/#/ as an alternative as mentioned by @smitpatelx

**Comment by angelxmoreno** [comment]
seems to be up now. this should be closed.

**Comment by jcrben** [comment]
@AlexMesser please close
