### ISSUE TITLE
join tables transformed to snake_case ("relation \"challenge_category\" does not exist")

### ISSUE THREAD

**Issue by mrklika** [typeorm/typeorm#7547]
Hello, I have 2 tables:

challenge:

```
@Field(() => ChallengeCategory)
@ManyToOne(() => ChallengeCategory, (category) => category.challenges)
challengeCategory: ChallengeCategory;
```

and challengeCategory:
```
@Field(() => [ Challenge ])
@OneToMany(() => Challenge, challenge => challenge.challengeCategory)
challenges: Challenge[];
```

When I try to:
`Challenge.find({ relations: [ 'challengeCategory' ] });`

I get:
"relation \"challenge_category\" does not exist"

In detailed err desc I can see:
LEFT JOIN \"challenge_category\"

It seems like it is automatically transformed from challengeCategory to challenge_category ( am not using any custom naming strategy...) Have you any idea what couls be wrong? Thanks! :)

**Comment by mrklika** [comment]
UPDATE: had to explicitly add @Entity({ name: 'challengeCategory' }) to entity decorator...

any idea how to make it automatically? From snake_cace to camelCase

**Comment by kevin-lindsay-1** [comment]
I think the issue is that you're explicitly adding the `@field` decorator when you don't need to.

**Comment by imnotjames** [comment]
You have to explicitly define the name if you don't want the defaults.
