### ISSUE TITLE
Unique Index and soft delete

### ISSUE THREAD

**Issue by kb05** [typeorm/typeorm#7549]
## Feature Description
Allow softDelete and unique constraint.
### The Problem
I have the following problem, I have an entity with the soft delete enabled and I want to add a restriction that will only enforce the non-deleted fields, e.g. duplicate email.

The problem is that the SQL engines (in my case mariadb), allow multiple entries in those fields that have a null value, that it to say, if I create a unique index for the ``` email```  and ``` deletedAt``` fields the db can storage multiples entries of  because NULL is not considered as a duplicated value:

| email      | deletedAt |
| ----------- | ----------- |
| user-1@test.com      | [NULL]       |
| user-1@test.com      | [NULL]       |
| user-2@test.com      | [NULL]       |
| user-2@test.com      | [NULL]       |

### The Solution
There are various options:

In my opinion the easiest solution would be that you can set the default deletedAtValue, and in the softDelete operations this value will be used to compare which fields are deleted, for example 
[NO_ZERO_DATE](https://mariadb.com/kb/en/datetime/), typeorm currently uses the default value for setting but not when comparing whether it has been deleted (always compares it to null, ```IS NULL```).

Another option could be create a decorator like ```IsEnabledField``` similar to ```DeleteDateColumn``` but set the value ```true|1``` on not deleted entities and ```[NULL]``` on deleted entities, this would cause that  the index take effect on active records and not on deleted records.

One more option could be create a virtual field that use the deletedAtField, like:
```
  @Column({
        asExpression  : "if(deletedAt IS NULL, 1, NULL)",
        generatedType : "VIRTUAL",
    })
    IsEnabledField : boolean;
```
and this way almost worked for me, but there is a bug that causes virtual fields to be constantly rebuilt on migrations: https://github.com/typeorm/typeorm/issues/4669 .

### Considered Alternatives

The way I'm getting around it is to override my entity's ```softRemove``` and ```recover``` method so that it also set a value to an additional field called ```activeEntity```, but it's a very messy and inconsistent solution.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [X] `mysql/mariadb`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [X] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

I am a bit stuck on this feature, can you think of a better or different alternative that would help me solve this problem?

**Comment by fervailanti** [comment]
Same here! Any workaround?

**Comment by jamesalways** [comment]
+1

**Comment by bri06** [comment]
+1

**Comment by ertankara** [comment]
It seems like you are solving a simple problem with a complex solution.

First of all, unique index doesn't work on `NULL` values and that is a SQL spec. Good thing that your DBMS implements it.

The other issue is, adding a unique index on email alone would solve your problem, and your queries would be still FAST without indexing with `deletedAt` column. If you desperately in need of indexing them together because of a "solution" you've implemented before. Then I'd suggest you use a unique index on email field alone, and a BTREE index on both email and deletedAt fields.

**Comment by kb05** [comment]
Hi @ertankara.

It's a integrity problem, not a performance problem.

If you create a unique index for just the email (and no more else) field you have the next problem:

``` 
1 - A user is created with the email: user-1@test.com.
2 - The user with the email: user-1@test.com is soft deleted (deletedAt field seted).
3 - The user with the email: user-1@test.com can not sign up again on the platform because the email is already inserted previously.
```

The email is just to simplify the example, but there are many entities where this behavior have not been sense, maybe a upload file, a report or something similar.

The objective is to create a data structure in which deleted items can be duplicated but active items cannot be duplicated.

**Comment by mortezaPRK** [comment]
If you want to handle this in DB, you need to use conditional indexing. I don't think Mysql/MariaDB has conditional indexing, [but Postgresql has it](https://www.postgresql.org/docs/current/indexes-partial.html) :)

If you can change your DB, consider this.

using multi-column indexing for these cases is not efficient at all and will make trouble soon :)

The only option I can think of, is to store soft-deleted records in another table (using database trigger)

**Comment by kb05** [comment]
Hi @mortezaPRK.

The approachto to have an additional table with the deleted entities is interesting, and could be a valid option to any database, but the support should be provided by the orm,  because change some functions related with the softdeleted entities like find with the "withDelete" option and the recover method.

However, there are two problems to be considered:
1. Requires many changes in the library (migrations, queries with deleted entities, transactions or triggers when the record has been deleted).
2. Using this approach active entity can not be attached to a deleted entity and with the deleted_at  field this is possible, this may not be a bad thing, but it is necessary think about it because could have undesirable effects on the app.

On the other hand, this approach:
1. Could be use in any database engine.
2. Solve the problem of indexing by deleted_at and the main table would be lighter and faster.

**Comment by imnotjames** [comment]
This isn't something we can resolve because you're asking for an impossible scenario:

* you want it to be unique
* you want to have soft-delete.

Because of how the database enforces uniqueness, unless you use the conditional features like was said above you're out of luck.  It's a database / data modeling problem, not a big in typeorm.

**Comment by marneborn** [comment]
In postgres, at least, this is possible with unique index
```
CREATE UNIQUE INDEX users_unique_email ON users (email) WHERE ("deletedAt" IS NOT NULL);
```

**Comment by peralva** [comment]
A simple solution would be for the index to consider only active records:

```
@Index(
    [ 'email' ],
    {
        unique: true,
        where: 'deletedAt IS NULL',
    }
)
```

**Comment by abeeb-ola** [comment]
> A simple solution would be for the index to consider only active records:
> 
> ```
> @Index(
>     [ 'email' ],
>     {
>         unique: true,
>         where: 'deletedAt IS NULL',
>     }
> )
> ```

Hi @peralva, has this always existed in TypeORM? We use a sort of hacky solution that has worked so far but isn't so easy to understand for someone seeing it for the first time. I'm wondering if this solution is something fairly recent?
