### ISSUE TITLE
saving an entity having a many-to-one relationship is exiting the application. (TypeORM and sql server)

### ISSUE THREAD

**Issue by Rachana-Kavva-by** [typeorm/typeorm#7562]
Issue type:
[] question
[] documentation issue

Database system/driver:
[*] SQL SERVER

TypeORM version:
[*] latest

Steps to reproduce or a small repository showing the problem:

I have two entities with Many to One relation (Client - Subscriber) like below.

```
@Entity()
export class Client extends Base {
@PrimaryGeneratedColumn()
public id: number;

@ManyToOne(type => Subscriber, subscriber => subscriber.clients)
subscriber: Subscriber;   
}
```

```
@Entity()
export class Subscriber extends Base {
@PrimaryGeneratedColumn()
public id: number;

@OneToMany(type => Client, client => client.subscriber)
clients: Client[];
}
```

**I'm trying to save a record to Client by using below code,**

```
let subscriber = await this.connection.getRepository(Subscriber).createQueryBuilder()
                    .select("subscriber")
                    .from(Subscriber, "subscriber")
                    .where("subscriber.name = :name", { name: 'test'})
                    .getOne();
```

**I'm get a record from above query,** 

```
let client= new Client();
                client.number= 1;
                client.subscriber = subscriber.id
result = await this.connection.getRepository(Client).save(client);
```

After executing the code, the application is exiting without even returning an exception or error.
Can anyone please help here?

**Comment by imnotjames** [comment]
This doesn't seem to be an issue with typeorm.


For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
