### ISSUE TITLE
Can't bind more than 65536 parameters with pg-connection

### ISSUE THREAD

**Issue by bnjbvr** [typeorm/typeorm#7565]
## Issue Description

Using the postgresql database, try to insert enough lines so that there are 65536 parameters to bind.

### Expected Behavior

Either there's a dynamic error signaling me that it's too many parameters to bind at once, or it Just Works.

### Actual Behavior

The number of bound parameters seem to be wrapped in the int16 space, because `pg-connection` that's used under the hood only puts an int16 when serializing the bind message. As a matter of fact, postgres receives an invalid number of parameters compared to the number of parameters formats, and throws:

> bind message supplies 4800 parameters, but prepared statement "" requires 70336

### Steps to Reproduce

From the example code generated with `typeorm init --name project --database postgres`, update the code of the index.js like this:

```typescript
createConnection().then(async connection => {
    console.log("Inserting a new user into the database...");
    let users = [];
    let numUsers = (65535/3) | 0; // works (3 features per user => numUsers*3 <= 65535)
    numUsers += 1; // doesn't work anymore! More than 65535 features.
    for (let i = 0; i < numUsers; i++) {
        const user = new User();
        user.firstName = "Timber";
        user.lastName = "Saw";
        user.age = 25;
        users.push(user);
    }
    await connection.manager.save(users);
    console.log("saved new users");

    console.log("Loading users from the database...");
    users = await connection.manager.find(User);
    console.log("Loaded users: ", users.length);

    console.log("Here you can setup and run express/koa/any other framework.");

}).catch(error => console.log(error));
```

then `yarn start` it, then observe the failure.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Ubuntu 20.04.2 LTS        |
| Node.js version     | v12.16.3 | 
| Typescript version  | v4.0.3 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

Thanks for making typeorm, it's great!

**Comment by DDevil97** [comment]
This doesn't seems to be a TypeORM issue, even NHibernate throws that error, if i recall correcty, it's a limitation of PostgreSQL itself [(see this)](https://www.postgresql.org/docs/13/protocol-message-formats.html)

**Comment by bnjbvr** [comment]
Indeed, the protocol only allows for u16_max (65536) bound parameters. What I was suggesting in the first issue is that either typeorm throws when trying to bind more than this number of parameters, so as to not silently swallow the u16 wrapping, or that it breaks the operation (insertion, deletion, update, etc.) in batches of u16_max / (number of operations * number of features), so it does the right thing under the hood.

Just causing a silent error is subpar and leads to situations very hard to debug, like this one.

**Comment by DDevil97** [comment]
Yes is hard to debug and extra annoying. Breaking the operations in batches of 65535 seems good, don't know how difficult would it be. At least throwing an exception would be better than the current behavior.

**Comment by imnotjames** [comment]
This sounds like an issue with the underlying module, doesn't it?

If the underlying module isn't properly telling TypeORM that there's an error it's very difficult to  know that something has gone wrong here.

**Comment by imnotjames** [comment]
This is an issue to open with pg upstream.  Until it's an error we can handle, not much to do here.
