### ISSUE TITLE
[BUG] findDescendants function not working properly

### ISSUE THREAD

**Issue by Kainar01** [typeorm/typeorm#7571]
## Issue Description
When I call findDescendants function on 'materialized-path' tree, it returns all elements in the table.  I tried to call createDescendantsQueryBuilder as well, but the same issue.
### Expected Behavior
It should have returned only descendants of element that I have passed

### Actual Behavior

```
// include the output in code tags like these!

@Entity()
@Tree('materialized-path')
export class CheatingCategory {
  @PrimaryGeneratedColumn()
  public id: number;

  @Column({ type: "varchar", unique: true })
  public name: string;

  @Column({ type: "varchar", nullable: true })
  public icon?: string;

  @Column({ type: "text", nullable: true })
  public description?: string;

  @Column({ type: "int", default: 0 })
  public score: number;

  @TreeParent()
  public category?: CheatingCategory;

  @TreeChildren()
  public subCategories: CheatingCategory[];

  @OneToMany(() => Cheating, (cheating) => cheating.category, { cascade: true })
  public cheatings: Cheating[];
}
repository = connection.getTreeRepository(
      CheatingCategory
    );
const category = await repository.findOne({
        name: cheatingCategoryName,
      });
const categories = await repository.createDescendantsQueryBuilder("cheatingCategory", "cheatingCategoryClosure", category)
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | vX.Y.ZZZ | 
| Typescript version  | vX.Y.ZZZ | 
| TypeORM version     | vX.Y.ZZZ | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imkks** [comment]
Did you find a workaround for this issue? I am facing the same issue apparently
