### ISSUE TITLE
CockroachDB Geography Type

### ISSUE THREAD

**Issue by JosephChotard** [typeorm/typeorm#7573]
## Feature Description

TypeORM should support the GEOGRAPHY and GEOMETRY type as it does for Postgres. (it is supported by cockroachDB: https://www.cockroachlabs.com/docs/v20.2/spatial-data.html)

### The Problem

TypeORM doesn't support the GEOGRAPHY type for CockroachDB

### The Solution

Add the type to the supported types

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [X] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [X] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

Thank you!

**Comment by imnotjames** [comment]
What version did crdb start supporting this

**Comment by JosephChotard** [comment]
> What version did crdb start supporting this

I believe it first came out in  version 20.2

**Comment by simplenotezy** [comment]
Should be fixed here: https://github.com/typeorm/typeorm/pull/9128
