### ISSUE TITLE
Relations - OneToMany / ManyToOne return null

### ISSUE THREAD

**Issue by WesleyIsr4** [typeorm/typeorm#7578]
Issue type:

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[x] postgres
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

TypeORM version:

[x] latest
[ ] @next
[ ] 0.x.x (or put your version here)

Steps to reproduce or a small repository showing the problem:

```
@Entity('tasks')
class Tasks {
  @PrimaryGeneratedColumn('uuid')
  id: string;
  @Column()
  title: string;
  @Column({
    type: 'varchar',
  })
  status: tasksStatus;
  @Column()
  description: string;
  @ManyToOne(type => User, user => User, { eager: true })
  user: User;
  @CreateDateColumn()
  created_at: Date;
  @UpdateDateColumn()
  updated_at: Date;
}
```
```
Users
@Entity('users')
class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;
  @Column()
  name: string;
  @Column({
    unique: true,
  })
  email: string;
  @Column()
  password: string;
  @OneToMany(type => Tasks, tasks => Tasks)
  tasks: Tasks[];
  @CreateDateColumn()
  created_at: Date;
  @UpdateDateColumn()
  updated_at: Date;
}
```
```
TasksRepository.ts
public async findAll(): Promise<Tasks[]> {
    return this.ormRepository.find({
      relations: ['user'],
    });
  }
```
```
UserRepository.ts
public async findByAll(): Promise<User[]> {
    return this.ormRepository.find({
      relations: ['tasks'],
    });
  }
```
When I go to list the users or tasks, it returns null
```
[
  {
    "id": "06b9c9d7-1a87-4f36-b325-96af538791b3",
    "name": "Wesleyisrael",
    "email": "wesley.teste2@email.com",
    "password": "$2a$08$Q9Ef07JW//f2gvcRWABNNePrQ3DXnheU8zsWVWSXnz.xwAfx6EiLO",
    "created_at": "2021-04-17T20:26:15.400Z",
    "updated_at": "2021-04-17T20:26:15.400Z",
    "tasks": []
  }
]
```

**Comment by ndeamador** [comment]
I am no expert myself, but shouldn't the definition of the populated fields be different?

```
  @ManyToOne(type => User, user => **user.taskS**, { eager: true })
  user: User;  
  
   @OneToMany(type => Task, task => **task.user**)
  task**S**: Task[];
```
  
  
Note I have changed Task to singular for clarity to differentiate it from 'taskS', plural, which would be the array field within the user entity.

So, each Task has a task.user (singular) column, and each user has a user.taskS (plural) column with an array of tasks.

**Comment by silentrobi** [comment]
Your @ManyToOne and @OneToMany relations have problem. Try to change it as follows,
```
@ManyToOne(type => User, user => user.tasks, { eager: true })
user: User;

@OneToMany(type => Task, task => task.user)
tasks: Task[];
```
Change your class name from **Tasks** to **Task**

**Comment by imnotjames** [comment]
pretty sure your question has been answered.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
