### ISSUE TITLE
When trying to set field nullable, it doesn't make it nullable [PG]

### ISSUE THREAD

**Issue by mentos1386** [typeorm/typeorm#759]
I found [here](https://github.com/typeorm/typeorm/blob/master/src/decorator/options/ColumnCommonOptions.ts#L28-L31) that i can provide `nullable: bolean` inside an options when creating column to make it nullable. But it doesn't work when im trying to create this table:

```ts
@Entity()
export class Post {

  constructor() {
    this.id = uuid();
  }

  @PrimaryColumn('uuid')
  id: string;

  @Column('text')
  content: string;

  @Column({ nullable: true })
  previewUrl?: string;

  @Column({ nullable: true })
  previewImage?: string;

  ...
}
```

When it creates a table in Postgres, it looks like this:

```sql
create table post
(
	id uuid not null constraint post_pkey primary key,
	content text not null,
	"previewUrl" varchar not null,
	"previewImage" varchar not null,
        ...
);
```

Creating new item with null value throws `QueryFailedError: null value in column "previewUrl" violates not-null constraint`

**Comment by felipesabino** [comment]
@mentos1386 This was [solved on gitter](https://gitter.im/typeorm/typeorm?at=598f2b822723db8d5e99d1d1) as being a database configuration issue, so I am assuming the issue can be closed, right?

**Comment by mentos1386** [comment]
@felipesabino Yeah, typeorm works as intended. It's probably an issue with my Postgres defaulting to `NOT NULL` when default should be `NULL`. I'll report when i find real issue.

**Comment by mentos1386** [comment]
After it creates a table without `NOT NULL` it then updates a table and sets `NOT NULL`. [Console Log](https://gist.github.com/mentos1386/5d9ad41f197768eda202478f534f4c82#file-typeorm-nullable-sql-L24-L28)

**Comment by pleerock** [comment]
please close issue if its not typeorm related issue

**Comment by mentos1386** [comment]
@pleerock, it is typeorm issue. First it creates table correctly:
```sql
creating a new table: post
executing query: CREATE TABLE "post" ("id" uuid NOT NULL, "content" text NOT NULL, "previewUrl" character varying, "previewImage" character varying, "previewTitle" character varying, "previewDescription" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "characterId" integer, PRIMARY KEY("id"))
```
But then it updates it and sets to `NOT NULL`:
```sql
columns changed in post. updating: previewUrl, previewImage, previewTitle, previewDescription
executing query: ALTER TABLE "post" ALTER COLUMN "previewUrl" SET NOT NULL
executing query: ALTER TABLE "post" ALTER COLUMN "previewImage" SET NOT NULL
executing query: ALTER TABLE "post" ALTER COLUMN "previewTitle" SET NOT NULL
executing query: ALTER TABLE "post" ALTER COLUMN "previewDescription" SET NOT NULL
```

Whole console log is [here](gist.github.com/mentos1386/5d9ad41f197768eda202478f534f4c82)

**Comment by pleerock** [comment]
> But then it updates it and sets to NOT NULL

what do you call "then" ? You are sure you don't have duplicated entities? Including entities in your output directory (if you setup outdir in tsconfig then remove directory)

**Comment by mentos1386** [comment]
@pleerock sorry for taking your time. It was a typo issue.

**Comment by 3dos** [comment]
Hi, I'm currently facing the exact same issue. At first, TypeORM altered the table to have the ability to have null values on a boolean, now it tries to sync again with 'SET NOT NULL'

CLI log

```
query: ALTER TABLE "event" ALTER COLUMN "validated" SET DEFAULT null
query: ALTER TABLE "event" ALTER COLUMN "validated" SET NOT NULL
```

First line is right but the second one

Definition of said field in my entity:
```
  @Column({ default: null, nullable: true })
  validated: boolean
```

I'm using PostgreSQL 11

I have no clue what is causing this behavior. I tried changing nullable to false outputing the same results and switching back to true with the same problem. I run the latest version of TypeORM

**Comment by ruslanguns** [comment]
@3dos I am having exact the same issue. After when sync is true, on changes and reloads it drops the nulled and set to NOT NULL.

**Comment by arnnis** [comment]
I managed to fix it by adding entity classes in `createConnection`  instead of `src/entity/**/*.ts`

**Comment by ryekerjh** [comment]
Just in case someone else pops into this thread having this issue using Docker, I found that after I altered my `@Column()` value to be `nullable: true`, I had to completely spin down Docker (`docker-compose down`) and then rebuild the entire instance (`docker-compose up --build`) in order for the Postgres DB in my container to recognize that I had changed the constraints on the Column. Hope this helps someone!

**Comment by piguyinthesky** [comment]
If there's anyone here compiling with `tsc`, I found that deleting the `dist` folder and rebuilding also did the trick.

**Comment by gitDylanHub** [comment]
Reading this [article](https://stackoverflow.com/questions/64635617/how-to-set-a-nullable-database-field-to-null-with-typeorm). I think the true issue is related to setting what the Database type is, not the code.  To make your entities type-safe you can use union types to account for a string and null.  

After using the Union type, I would then suggest explicitly setting the type for the database.  Otherwise, the null won't apply because it doesn't know what to set it to.   Quite possibly the reason for the "not null" updating the value. 

For Example: 
```javascript
@Entity()
export class Post {

  @Column({ 
    nullable: true,
    type: 'text',
  })
  previewUrl?: string | null;

}
```

**Comment by gitDylanHub** [comment]
> Reading this [article](https://stackoverflow.com/questions/64635617/how-to-set-a-nullable-database-field-to-null-with-typeorm). I think the true issue is related to setting what the Database type is, not the code. To make your entities type-safe you can use union types to account for a string and null.
> 
> After using the Union type, I would then suggest explicitly setting the type for the database. Otherwise, the null won't apply because it doesn't know what to set it to. Quite possibly the reason for the "not null" updating the value.
> 
> For Example:
> 
> ```js
> @Entity()
> export class Post {
> 
>   @Column({ 
>     nullable: true,
>     type: 'text',
>   })
>   previewUrl?: string | null;
> 
> }
> ```

https://github.com/typeorm/typeorm/issues/2567

**Comment by arrudacaio** [comment]
I would like to thank @ryekerjh for your comment, helped me a lot.
