### ISSUE TITLE
QueryFailedError: type "serial" does not exist on schema sync

### ISSUE THREAD

**Issue by MaikelH** [typeorm/typeorm#760]
**Problem**
When autosync is enabled the schema is synced correctly on the first run, when the application is restarted it will fail with the following error.

```
QueryFailedError: type "serial" does not exist
```

The following entity was used.
```typeorm
@Entity()
class testEntity {
    @PrimaryGeneratedColumn()
    public sourceInventoryId: number;

    @Column({ type: "serial" })
    public testColumn: number;
}
```
**Possible cause**
It tries to execute the following query `ALTER TABLE "test_entity" ALTER COLUMN "sourceInventoryId" TYPE serial`. This fails because `serial` is not supported in `ALTER COLUMN` statements. 

**Possible solution**
Check the current type of the column, if it is already integer with a sequence don't try to change it. If it already exists, the only solution is to delete the column (don't think this is something we want) or to fail with an exception.

Another solution is not to support `serial` like types on `Column` decorators. This then can be solved by introducing a `GeneratedColumn` decorator similar to `PrimaryGeneratedColumn` (which already does not support a `serial` type).

---
**database:** postgres 9.6
**typeorm version:** 0.1.0-alpha.34
**typescript:** 2.4.2

**Comment by pleerock** [comment]
> Another solution is not to support serial like types on Column decorators. This then can be solved by introducing a GeneratedColumn decorator similar to PrimaryGeneratedColumn (which already does not support a serial type).

Yeah I think `serial` should not be supported this way.

> GeneratedColumn

There is a possibility to set Generated + Column, not primary:

```ts
@Column()
@Generated("uuid")
uuid: string;
```

**Comment by MaikelH** [comment]
> Yeah I think serial should not be supported this way.

Okay, what would be the best way to remove the serial type from the supported column types? Removing it directly from the supported columns could break some things. 

> There is a possibility to set Generated + Column, not primary:

Okay, that is nice. Apparently I missed this in the documentation somewhere.

Removing the serial types will remove the ability to set it to a specific type of serial (i.e. `smallserial` or `bigserial`). An option would be to add an optional `type` parameter to the `Generated()` decorator.

**Comment by pleerock** [comment]
> Okay, that is nice. Apparently I missed this in the documentation somewhere.

its new and undocumented feature yet

> Okay, what would be the best way to remove the serial type from the supported column types? 

Probably you need to search in project "serial" keyword and remove from all appropriate places

> Removing it directly from the supported columns could break some things.

I don't think so...
