### ISSUE TITLE
cascade save fails when retried - null value in column of relation

### ISSUE THREAD

**Issue by mitsos1os** [typeorm/typeorm#7603]
## Issue Description
We are using two related Entities with Relation OneToMany / ManyToOne between them and cascade enable on one side of the relation. When firstly creating the parent -> child entity athrough the relation, it completes successfully.

However when re-running the same code, it fails with an error of `null` value in parent column of relation, while according to the docs it should initially save and then update the entity on subsequent calls.

Specifically:

**Company**
```typescript
/**
 * Base company information
 */
@Entity()
export class Company {
  @PrimaryGeneratedColumn()
  id!: number;

  @IsString()
  @Column()
  name!: string;
 
  @IsOptional()
  @Column({ nullable: true })
  description?: string;
 
  @OneToMany(() => CompanyAddress, (companyAddress) => companyAddress.company, {
    cascade: true,
  })
  addresses?: CompanyAddress[];
 }
```

**Company Address**
```typescript
@Entity()
export class CompanyAddress  {
  @PrimaryGeneratedColumn()
  id!: number;
 
  @IsOptional()
  @IsString()
  @Column({ nullable: true })
  street?: string;
 
  @IsOptional()
  @IsString()
  @Column({ nullable: true })
  city?: string;
 
  @IsOptional()
  @IsString()
  @Column({ nullable: true })
  country?: string;
 
  @ApiHideProperty()
  @ManyToOne(() => Company, (company) => company.addresses, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  company!: Company;
}
```
**Test Code**
```typescript
const test = () => {
	const company = new Company();
	company.id = 2;
	company.name = 'Test Company';

	const address1 = new CompanyAddress();
	address1.street = 'Some street';
	address.city = 'Volos';
	address.country = 'Greece';

	company.addresses = [address1];
	companyRepo.save(company)
	    .then((res) => {
	      console.log(res);
	    })
	    .catch((err) => {
	      console.error(err);
	    });
	  
}
  
```

### Expected Behavior

I would expect for the next calls to complete (updating or not the changed fields), successfully. It seems  a bit non-intuitive but imagine that this would be the same code executing when sending the same PATCH request on an API which should be successful. This is the same code run that reproduces the scenario

### Actual Behavior

Running this the first time completes successfully. On next calls it fails with the following error:
```
QueryFailedError: null value in column "companyId" of relation "company_address" violates not-null constraint
```
The error about **not-null constratint** is because I do not allow `NULL` values in the company by setting the `nullable: false` option in the relation. The problem is that the referencing column is not set

### Steps to Reproduce

1. `test()`
2. `test()`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Linux      |
| Node.js version     | v14.16.1 | 
| Typescript version  | v4.2.4 | 
| TypeORM version     | v0.2.32 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by jcrben** [comment]
@mitsos1os where is `orphanedRowAction` actually documented? nothing comes up at https://www.google.com/search?hl=en&q=site%3Ahttps%3A%2F%2Ftypeorm.io%20orphanedRowAction

@AlexMesser maybe `orphanedRowAction` could default to delete to save people trouble...

**Comment by mitsos1os** [comment]
@jcrben it is documented here : https://typeorm.io/#/relations/relation-options 😀
I agree with the suggested default behavior since leaving orphaned rows with the way Typeorm works is a bit counter intuitive
