### ISSUE TITLE
MongoDB: w, j, wtimeout and fsync options is deprecated (mongodb: 3.6.x)

### ISSUE THREAD

**Issue by caiocltm** [typeorm/typeorm#7604]
## Documentation Issue

MongoDB: **w**, **j**, **wtimeout** and **fsync** options is deprecated (mongodb: 3.6.x)

### What was unclear or otherwise insufficient?

The options **w**, **j**, **wtimeout** and **fsync** is no longer part of [MongoClient](http://mongodb.github.io/node-mongodb-native/3.6/api/MongoClient.html) options since 3.6.x. We should use the **writeConcern** instead.

### Recommended Fix

I don't know if has other files we should update, but I think that has only these two files described below:

 * Interface of [MongoConnectionOptions](https://github.com/typeorm/typeorm/blob/f85f436f51fb000cd9959b44e8d7a79bf0cd10ab/src/driver/mongodb/MongoConnectionOptions.ts#L8).
 
 * Property of [validOptionsNames](https://github.com/typeorm/typeorm/blob/f85f436f51fb000cd9959b44e8d7a79bf0cd10ab/src/driver/mongodb/MongoDriver.ts#L141) in MongoDriver class, adding the new option, to enable the right parse of the connection options sent to the MongoDB driver.

Please let me know if have other files, I appreciate 👍🏻 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [X] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
I've added `writeConcern` but we currently support mongo driver version 3.5 so we can't remove the others.
