### ISSUE TITLE
Separate paths for entity, migrations and subscribers.

### ISSUE THREAD

**Issue by LWJerri** [typeorm/typeorm#7627]
## Feature Description

A split entity, migration, and subscribers path for TypeScript and JavaScript.

### The Problem

Hello. Recently I start use TypeORM for my TypeScript project and faced a very popular problem. When I try to build my project, he crashes, because TypeORM can't correctly define the path to my Entities, Migrations, and Subscribers. I'm used google to find answers to my problem, but all answers didn't work for me.

UPD: I'm use `.env` TypeORM config for my project.

### The Solution

I'm proposing to make changes in TypeORM configs:

**New config keys:**

-   `buildType` - Available `ts` and `js`.
-   `entitiesTS` - Path to entities for TypeScript (`buildType` set to `ts`).
-   `migrationsTS` - Path to migrations (`buildType` set to `ts`).
-   `subscribersTS` - Path to subscribers (`buildType` set to `ts`).
-   `entitiesDirTS` - Path to entities for TypeScript (`buildType` set to `ts`).
-   `migrationsDirTS` - Path to migrations (`buildType` set to `ts`).
-   `subscribersDirTS` - Path to subscribers (`buildType` set to `ts`).

-   `entitiesJS` - Path to entities for TypeScript (`buildType` set to `js`).
-   `migrationsJS` - Path to migrations (`buildType` set to `js`).
-   `subscribersJS` - Path to subscribers (`buildType` set to `js`).
-   `entitiesDirJS` - Path to entities for TypeScript (`buildType` set to `js`).
-   `migrationsDirJS` - Path to migrations (`buildType` set to `js`).
-   `subscribersDirJS` - Path to subscribers (`buildType` set to `js`).

**Remove config keys:**

-   `entities`, `migrations`, `subscribers`, `entitiesDir`, `magrationsDir`, `subscribersDir`

The developer himself will be able to set what type he needs and, depending on the type, TypeORM will refer to the path `entitiesTS` or` entitiesJS`.

### Relevant Database Driver(s)

-   [ ] `nativescript`
-   [ ] `aurora-data-api`
-   [ ] `aurora-data-api-pg`
-   [ ] `better-sqlite3`
-   [ ] `cockroachdb`
-   [ ] `cordova`
-   [ ] `expo`
-   [ ] `mongodb`
-   [ ] `mysql`
-   [ ] `oracle`
-   [x] `postgres`
-   [ ] `react-native`
-   [ ] `sap`
-   [ ] `sqlite`
-   [ ] `sqlite-abstract`
-   [ ] `sqljs`
-   [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

-   [ ] Yes, I have the time, and I know how to start.
-   [x] Yes, I have the time, but I don't know how to start. I would need guidance.
-   [ ] No, I don't have the time, although I believe I could do it if I had the time...
-   [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
I'm really not a fan of this. It's too specific to your exact situation.

I suggest importing them and passing the entities, migrations, etc, directly into your connection.

Or, there's nothing stopping you from making your `ormconfig` be a JavaScript file which reads these configuration values for you, choosing the right things and then passing the correct paths in based on build type.

If you need more advanced logic you'll really need to write much of that yourself.
