### ISSUE TITLE
Foreign Key is Null

### ISSUE THREAD

**Issue by yulric** [typeorm/typeorm#763]
Hi there,
I'm trying to debug an issue in my application where the foreign key field for a row is being set to null when the parent object is being saved. The models are very complex so it's hard to create a test case but essentially they look like this,

```
class ParentEntity {
    childEntitites: Array<ChildEntity>
}

class ChildEntity {
    parentEntity: ParentEntity
}
````

Assume that all the relevant decorators have been set and it's a ManyToOne relationship. There are no cascade options set on the Parent and Child entities. When I save the ParentEntity the parentEntity field gets set to null.

It looks like this line of code,
https://github.com/typeorm/typeorm/blob/0.0.11/src/persistence/SubjectOperationExecutor.ts#L734

is what's doing it. Would you know why?

Thanks

**Comment by yulric** [comment]
I was able to get a repo going that reproduces the issue,
https://github.com/yulric/typeorm-foreign-key-null

**Comment by pleerock** [comment]
@yulric I would ask you to update orm to latest version and check your issue

**Comment by pleerock** [comment]
@yulric any updates on your issue?

**Comment by yulric** [comment]
Hi pleerock,
Sorry for the late response. I haven't seen if this issue is in the latest version of typeorm but I found out that it isn't actually an issue but more a feature of typeorm. 

When a parent has an array of child objects that can be cascaded, but the parent object is persisted such that only some of the child objects that are currently in the db are in the parent object that is being persisted, typeorm automatically sets the foreign key for those missing child objects in the db to null.

I made a fork of typeorm and added a new option in the ManyToOne decorator called dereferenceRelation which stops this from hapenning. The fork is here https://github.com/yulric/typeorm/tree/foreign-key-null-fix

Let me know if you need more information

**Comment by pleerock** [comment]
> When a parent has an array of child objects that can be cascaded, but the parent object is persisted such that only some of the child objects that are currently in the db are in the parent object that is being persisted, typeorm automatically sets the foreign key for those missing child objects in the db to null.

When typeorm sees your array empty, it thinks you removed everything from your relation, that's why it sets it to null. The solution is do not initialize arrays in your model. When your relation is `undefined` it does not remove anything from it. 

If you face this issue then probably its better to change your approaches and some design, im sure all your problems are solvable alternative way.

Having to maintain your own fork isn't effective. There are lot of new awesome changes in the latest release you are missing.

**Comment by yulric** [comment]
In our app we were having problems where NodeJS would run out of memory because we were  loading too many child relations from the db which is why we switched to loading only what is needed into the child array resulting in the above problem. I'm not really sure how to fix the problem without my fork unfortunately. Any ideas?

PS I would love to upgrade to the new version :)

**Comment by pleerock** [comment]
As I understand you don't want to load everything from relation, but at the same time you want to update it. For this purpose there is a [relation query builder functionality](http://typeorm.io/#/relational-query-builder). I suggest you to create a new project using new version and try to solve issues you currently have using this functionality on a simple examples.

**Comment by yulric** [comment]
I will try that, thanks

**Comment by pleerock** [comment]
I'll close this issue. Feel free to continue discussion or open new issues if you faced them.
