### ISSUE TITLE
Unable to use URL in ioredis cache options

### ISSUE THREAD

**Issue by JoeCap08055** [typeorm/typeorm#7631]
## Issue Description
According to the ioredis [docs](https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options), the following connection options are equivalent within the `cache {}` block:

1.
 ```javascript
cache {
   type: "ioredis",
   options {
      port: 1234,
      host: "myhost",
      db: 1
   }
}
```

2.
```javascript
cache {
   type: "ioredis",
   port: 1234,
   options {
      host: "myhost",
      db: 1
   }
}
```
3.
```javascript
cache {
   type: "ioredis",
   port: "redis://myhost:1234/1"
}
```

### Expected Behavior

All three config options above produce the same result, which is an ioredis query cache connected to `myhost` on port `1234`, database index `1`

### Actual Behavior

Option 1 succeeds.
Option 2 ignores `port` and only uses the values inside the `options` block, using the ioredis default port 6379. Connection fails.
Option 3 ignores `port` and attempts to connect to `localhost:6379`, and fails.

### Steps to Reproduce

Try each of the listed cache configs in your `ormconfig.js`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.16.1 | 
| Typescript version  | v3.9.9 | 
| TypeORM version     | v0.2.32 | 
| ioredis version | v4.27.2 |

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `ioredis`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

I've made a fix & tested locally. Just need guidance with the pull request.

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by JoeCap08055** [comment]
I have a pull request ready to submit, but I don't have permission to push my branch

**Comment by goktugyil** [comment]
Does this only work in ioredis?
What about normal redis?
