### ISSUE TITLE
How to use aliases in query builder

### ISSUE THREAD

**Issue by adnan-kamili** [typeorm/typeorm#764]
I am trying to build the following query using query builder:

`SELECT count("activation"."id") AS activations, DATE("activation"."createdAt") AS "activationDate" FROM "activation" WHERE "activation"."tenantId" = $1 AND activationDate BETWEEN $2 AND $3 GROUP BY activationDate`

In querybuilder couldn't figure out how to set  alias for more than one column, so made it part of query:

```javascript
const queryBuilder = this.activationRepository.createQueryBuilder("activation");
queryBuilder.select("count(activation.id) AS activations, DATE(activation.createdAt)", "activationDate");
queryBuilder.where("activation.tenantId = :tenantId", { tenantId: ctx.state.user.tenantId });
queryBuilder.andWhere("activationDate BETWEEN :startDate AND :endDate", { startDate, endDate });
queryBuilder.groupBy("activationDate");
const activationsData = await queryBuilder.getMany();
```
In logs I see the correct query is generated but the it fails with error:

`Error: column "activationdate" does not exist
`

I am not chaining because some parts are inside if statements.

**Comment by pleerock** [comment]
If you are using your aliases you need to escape them by yourself, e.g. your where should look this way:

```ts
queryBuilder.andWhere(`"activationDate" BETWEEN :startDate AND :endDate`)
```

**Comment by adnan-kamili** [comment]
I escaped them but it still fails:

`Error: column "activationDate" does not exist`

**Comment by pleerock** [comment]
Try to create and run raw sql first (maybe even using your database lookup program) then try to create same query using query builder.

**Comment by abec** [comment]
Just FYI you can't use aliases in WHERE clauses like this because WHERE clauses are executed before the SELECT. See https://stackoverflow.com/questions/356675/using-an-alias-in-a-where-clause.
