### ISSUE TITLE
feature: add the connectName to the Entity decorator

### ISSUE THREAD

**Issue by cjfff** [typeorm/typeorm#7659]
## Feature Description

In my project;

Table Models used different connections and each other connection will connect the different databases.

So, I saw the [document](https://typeorm.io/#/connection-api) and found some ways to solve the problem.

Like this;

1.  Use the getRepository
```ts
const blogRepository = getRepository(Blog, "secondary-connection"); // define the connection which i want
```
2. Use the getConnectionManager
```ts
const defaultConnection = getConnectionManager().get("default");
const manager = defaultConnection. manager;
const user = await entityManager.findOne(User, 1);
```
3. Use the getEntityManager
```ts
const manager = getEntityManager();
const user = await entityManager.findOne(User, 1);
```

### The Problem and The Solution

I think it can add an additional property in Entity Decorator to solve its elegantly.

Like this 

```ts
@Entity({ name: "user", connectionName: 'xxxx' })
class User extends BaseEntity {}
```

And the getMetadataArgsStorage can store the name of the connection.

When the getRepository be used the connection name should use in the **getConnection** 

```ts
export class BaseEntity extends SuperEntity {
  /**
   * Gets current entity's Repository.
   */
  static getRepository<T extends BaseEntity>(
    this: ObjectType<T>
  ): Repository<T> {
    const target = getMetadataArgsStorage().tables.find(
      (item) => item === (this as any)
    ) as CustomTableMetadataArgs;
    const connectionName = target?.connectionName ?? "default";

    const connection: Connection =
      (this as any).usedConnection || getConnection(connectionName);
    return connection.getRepository<T>(this);
  }
}

```

Now I define a custom decorator to collect the connectionName and rewrote the BaseEntity in my project.

The Decorator likes this. But I think It can solve other people's problems. so the feature becomes the official code to the project has significance.

```ts
import { getMetadataArgsStorage } from "typeorm";
import { TableMetadataArgs } from "typeorm/metadata-args/TableMetadataArgs";
import { IDatabasename } from "../config";

export type CustomTableMetadataArgs = TableMetadataArgs & {
  connectionName: string;
};

export function ConnectionDecorator(name: IDatabasename): ClassDecorator {
  return function (target) {
    const metaTarget = getMetadataArgsStorage().tables.find(
      (item) => item.target === target
    ) as CustomTableMetadataArgs;

    metaTarget.connectionName = name;
  };
}

```

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
You should - in theory - be able to associate an entity with multiple connections.

This is done by registering the entity explicitly with the connection in the connection's `Entity` parameter.
