### ISSUE TITLE
Sorting in pagination bug

### ISSUE THREAD

**Issue by SlavikStinskyi** [typeorm/typeorm#7668]
## Issue Description
Find incorrect behavior in pagination with sorting in executeEntitiesAndRawResults() function.
Use nestjs framework with nestjs crud module. it have pagination. In my project i have main entity "project" with relation table one to many "project statuses" by each user. I need sort in project by last updated date in project statuses. in result have less projects than expected.

### Expected Behavior
in limitation 20 items and sorting by updatedAt in relation table view all 20 items. When count of items more than 20 items.
```
SELECT DISTINCT `distinctAlias`.`Project_id` as "ids_Project_id"
FROM (
    SELECT `Project`.`id` AS `Project_id`, `projectStatus`.`updatedAt` AS `projectStatus_updatedAt`
    FROM `project` `Project`
        LEFT JOIN `project_status` `projectStatus` ON `projectStatus`.`projectId`=`Project`.`id`
    WHERE (`Project`.`status` = 'active')
) `distinctAlias`
ORDER BY `distinctAlias`.`projectStatus_updatedAt` DESC, `distinctAlias`.`Project_id` ASC  LIMIT 11 OFFSET 0;
```
| ids_Project_id    |
| ---     |
| 305 |
| 302 |
| 252 |
| 301 |
| 299 |
| 297 |
| 296 |
| 294 |
| 293 |
| 292 |
| 290 |

### Actual Behavior
In file SelectQueryBuilder function executeEntitiesAndRawResults()  in line 1973 have distinct select primary columns. But in 1974 line adding sort column from subqueries. It leads to duplicate primary columns value.

```
SELECT DISTINCT `distinctAlias`.`Project_id` as "ids_Project_id"
FROM (
    SELECT `Project`.`id` AS `Project_id`, `projectStatus`.`updatedAt` AS `projectStatus_updatedAt`
    FROM `project` `Project`
        LEFT JOIN `project_status` `projectStatus` ON `projectStatus`.`projectId`=`Project`.`id`
    WHERE (`Project`.`status` = 'active')
) `distinctAlias`
ORDER BY `distinctAlias`.`projectStatus_updatedAt` DESC, `distinctAlias`.`Project_id` ASC  LIMIT 11 OFFSET 0;
```

|  `ids_Project_id`    |   `projectStatus_updatedAt`    |
| ---                 | ---      |
|  305 | 2021-05-19 12:07:40.472594 |
|  305 | 2021-05-19 12:07:40.441336 |
|  305 | 2021-05-19 12:07:40.428497 |
|  305 | 2021-05-19 12:07:40.164552 |
|  302 | 2021-05-17 18:07:52.000000 |
|  252 | 2021-05-17 11:24:30.000000 |
|  302 | 2021-05-16 06:11:24.922917 |
|  302 | 2021-05-16 06:11:24.911108 |
|  302 | 2021-05-16 06:11:24.857663 |
|  301 | 2021-05-16 06:11:24.537737 |
|  301 | 2021-05-16 06:11:24.503977 |

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Ubuntu 20.04     |
| Node.js version     | v14.17.0 | 
| Typescript version  | v3.6.3 | 
| TypeORM version     | 0.2.32 |
| nestjs/core     | ^6.7.2 |
| nestjsx/crud     | ^4.6.2 |
| nestjsx/crud-typeorm     |^4.6.2 |

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by TrejGun** [comment]
you have to use skip/take instead of offset/limit

**Comment by SlavikStinskyi** [comment]
> you have to use skip/take instead of offset/limit

Explain pliase

**Comment by TrejGun** [comment]
`There are 2 ways of how you can apply a limit/offset in TypeORM: skip/take for entities and offset/limit if you want to limit the raw result coming from SQL before TypeORM is processing it. Basically, as soon as you start having any kind of JOIN in your query, use skip/take for pagination purpose. Was a bit hard to find out the exact meaning, even though a part of this was documented.`

**Comment by imnotjames** [comment]
This was answered.
