### ISSUE TITLE
combined use(NOT,LIKE,AND)

### ISSUE THREAD

**Issue by duanyuanping** [typeorm/typeorm#7669]
How to use typeorm api to achieve the following SQL functions?
`SELECT * FROM user WHERE name NOT LIKE '%AAA%' AND name NOT LIKE '%BBB%' AND name NOT LIKE '%CCC%';`

**Comment by AlexMesser** [comment]
you can use [QueryBuilder](https://typeorm.io/#/select-query-builder) or [FindOptions](https://typeorm.io/#/find-options). Please use StackOverflow to ask questions.
