### ISSUE TITLE
'No such column' when updating entity that has many-to-many relation

### ISSUE THREAD

**Issue by paulvandenburg** [typeorm/typeorm#7670]
## Issue Description
When using the `EntityManager.update()` to update an entity with a many-to-many relation it throws a weird error.

### Expected Behavior
Allow updating an entity with many to many relations, or show a clear error point developers to the correct solution.
`EntityManager.save()` does work, so if it is intentional that the `update()` doesn't work, I'd like to get pointed in that direction.

### Actual Behavior
The underlying SQL created e.g. for entity "Business" creates a query of `UPDATE business SET <other cols>, businessId = $?`, but that `businessId` comes out of nowhere since the primary key is simply `id`.

The error message is something like `<db engine>: no such column: businessId`

### Steps to Reproduce
I've tested it with both `SQLite` and `postgresql`.
I've created a test case demonstrating the issue, see PR: #7671

### My Environment
Not really relevant, see PR based on master.

### Relevant Database Driver(s)
- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [x] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by paulvandenburg** [comment]
See PR for test case.

This issue is a follow up to #1987, where no solution was made nor a test script was added.

**Comment by AlexMesser** [comment]
based on your PR:

1. You must specify `ManyToMany()` decorator only at one side of relation, not on both sides.
2. Repository `update()` method executes a primitive operation without cascades, relations and other operations included. You must use `save()` method instead.

**Comment by duong-le** [comment]
@AlexMesser did you mean `JoinTable()` decorator only at one side of relation?

**Comment by AlexMesser** [comment]
@duong-le yes, corrected. Thank you.
