### ISSUE TITLE
[UX] UpdateQueryBuilder should not allow update queries without a where clause.

### ISSUE THREAD

**Issue by pedrolcn** [typeorm/typeorm#7672]
## Feature Description
This is mostly an improvement around the UX of `UpdateQueryBuilder`.
`UpdateQueryBuilder` should not allow the user to call `.execute()` if the query does not have a `WHERE` clause (it can have an empty where clause, but the user has to explicitly state so).

### The Problem
As of today `UpdateQueryBuilder` allows you to call `.execute()` without specifying a `WHERE` clause (which could be done 
 by calling `.where(...)`). It is very easy to simply forget to call the `.where()` method. This is a footgun which should not be allowed. 

### The Solution
Create a new class `UpdateQueryBuilderWithoutWhereClause` which would be returned by `QueryBuilder.prototype.update`. This class would be mostly identical to the current implementation of `UpdateQueryBuilder`, except that it would have the following implementation of the execute method:

```typescript
class UpdateQueryBuilderWithoutWhereClause<Entity> extends QueryBuilder<Entity> {
    // ...
    public execute(): never {
        throw new Error(
            'Executing an update query without a where clause is not allowed. If you would like to execute an ' +
            'update without a where clause please explicitly state so by calling `.where()` without any arguments')
    }
    // ...
}
```

And all of the `WhereExpression` methods would instead of returning an instance of `UpdateQueryBuilderWithoutWhereClause` would return an instance of `UpdateQueryBuilder`. This way it the compiler can prevent us from forgetting to specify our update`s WHERE clause.

There would be some problems around the `WhereExpression` interface as it states that its methods should return `this` and it is being proposed that they return an instance of a different class.

This could also be applied to `DeleteQueryBuilder`.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
You're free to wrap typeorm to add this functionality but it's outside the scope of typeorm to do this.

You can also subscribe to events and throw an error if something without a where is being attempted.

If you forget a where clause I'm sorry, but we can't really prevent that without making the API very cumbersome.
