### ISSUE TITLE
[MongoDB] Properties not defined in entity are not fetched

### ISSUE THREAD

**Issue by vlourme** [typeorm/typeorm#7673]
## Issue Description
Properties that are not defined in the Schema/Entity but that are in a document are not fetched.

### Expected Behavior
It should fetch all values (if `select` is not specified) even non-defined properties are MongoDB can be schemaless.

### Actual Behavior
Let's admit I have this Entity
```ts
@Entity()
export class Customer extends BaseEntity {
  @ObjectIdColumn()
  id: ObjectID;
}
```

Now, let's admit I have a document in the `customer` collection with these values: 
```json
{
  "_id": "...",
  "name": "John Doe"
}
```

Now when I fetch the document:
```ts
const customers = return await Customer.find({
  take: 20
});
```

The response will be
```json
[
  {
    "_id": "..."
  }
]
```

If I add the `name` property to the entity (like that: `@Column() name: string`). Then It works, but in the actual structure of the application, the schema needs to be dynamic (the user can choose and create custom fields/property).

### Steps to Reproduce
See actual behavior.

### My Environment
| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    MacOS Big Sur 11.3.1 on MacBook Pro M1      |
| Node.js version     | v14.17.0 | 
| Typescript version  | v4.0.2 | 
| TypeORM version     | v0.2.26 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
MongoDB might be schemaless but typeorm most definitely has a schema and follows it.  This is by design.

The same applies to SQL, it won't retrieve items from the database if they aren't defined in the schema.
