### ISSUE TITLE
@Transaction() with multiple @TransactionRepository() starts one transaction per query

### ISSUE THREAD

**Issue by vitorbertolucci** [typeorm/typeorm#7679]
## Issue Description

When using a method decorated with @Transaction() and it's arguments decorated with @TransactionRepository(), typeorm starts a new transaction for each query that is called.

### Expected Behavior

To run all queries within the same transaction

### Actual Behavior

A new transaction is being started for each query

### Steps to Reproduce

I have two custom repositories, one is called UsuarioRepository and the other one is called TransacaoRepository (this is portuguese for User and Transaction respectively). I created a class called TransactionTransactionsRepository in which I have a method called redeemBonusBalance, that starts a transaction that manipulates both my custom repositories, as you can see below:

```typescript
import { Transaction, TransactionRepository } from 'typeorm';

import Usuario from '../entities/Usuario';
import UsuarioRepository from './usuarioRepository';
import TransacaoRepository from './transacaoRepository';

export default class TransactionTransactionsRepository {
  @Transaction()
  public async redeemBonusBalance(
    user: Usuario,

    @TransactionRepository()
    usuarioRepository?: UsuarioRepository,

    @TransactionRepository()
    transacaoRepository?: TransacaoRepository,
  ) {
    if (!usuarioRepository || !transacaoRepository) {
      throw new Error('Repositories not found');
    }

    const updatedUser = await usuarioRepository.findByIdOrFail(user.Id);

    const redeemable = Math.floor(Number(updatedUser.SaldoBonus));

    if (redeemable < 1) {
      throw new  Error(
        "You don't have enough balance.",
      );
    }

    updatedUser.Saldo = Number(updatedUser.Saldo) + redeemable;
    updatedUser.SaldoBonus = Number(updatedUser.SaldoBonus) - redeemable;

    await usuarioRepository.save(updatedUser);

    await transacaoRepository.create({
      IdUsuario: user.Id,
      IdTipoTransacao: 1,
      TipoOperacao: 1,
      Quantidade: redeemable,
    });

    return redeemable;
  }
}

```

I set up a minimal reproducible example at: https://codepen.io/vitorbertolucci/project/editor/ZRxpvQ

When I run method redeemBonusBalance I see the following logs:

```
query: START TRANSACTION
query: SELECT `Usuario`.`Id` AS `Usuario_Id`, `Usuario`.`Saldo` AS `Usuario_Saldo`, `Usuario`.`SaldoBonus` AS `Usuario_SaldoBonus` FROM `Usuario` `Usuario` WHERE ( `Usuario`.`Id` = ? ) LIMIT 1 -- PARAMETERS: [13]
query: START TRANSACTION
query: UPDATE `Usuario` SET `Saldo` = ?, `SaldoBonus` = ? WHERE `Id` IN (?) -- PARAMETERS: [2,0,13]
query: COMMIT
query: START TRANSACTION
query: INSERT INTO `Transacao`(`Id`, `IdUsuario`, `IdTipoTransacao`, `TipoOperacao`, `Quantidade` ) VALUES (DEFAULT, ?, ?, ?, ?) -- PARAMETERS: [13,7,0,1]
query: SELECT `Transacao`.`Id` AS `Transacao_Id` FROM `Transacao` `Transacao` WHERE `Transacao`.`Id` = ? -- PARAMETERS: [177731]
query: COMMIT
query: COMMIT
```

As you can see, there are 3 transactions being started and commited, which is exactly the number of queries I'm running, meaning there is one transaction per query.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Ubuntu 16.04  |
| Node.js version     | v14.17.0 | 
| Typescript version  | v4.2.4 | 
| TypeORM version     | v0.2.32 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [X] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [X] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

Is there something I'm doing wrong or is it an actual bug? The documentation about transactions is not very clear, so I'm not sure that's how it's supposed to be used.

**Comment by vitorbertolucci** [comment]
After a lot more testing, it turns out that the problem is that my custom repositories are using an orm repository from global getRepository, so they have their own manager to run queries with. I tried modifying my custom repositories to extend AbstractRepository but then I was no longer able to @inject() them with tsyringe container because tsyringe cannot call getCustomRepository to register a global token. It would take a lot of rework in my codebase to get it all working with tsyringe and typeorm just so I could use custom repositories in my transactions, so it's not worth it. I ended up keeping my custom repositories structure and simply not using them with transactions.

I will just close this issue rather than erasing it because someone may find it helpful.

**Comment by otavioomota** [comment]
@vitorbertolucci I´m having the same problem that you had, Do you have any update about that ?

**Comment by vitorbertolucci** [comment]
> @vitorbertolucci I´m having the same problem that you had, Do you have any update about that ?

No, I am still in the situation I described in my previous comment. Whenever I need to use a transaction, I run all queries in the manager it returns, like this:

```await getConnection().transaction(async (transaction) => {
  await transaction.find(Entity,{})
}) ```
