### ISSUE TITLE
Can't use null values in Repository.save/Repository.update

### ISSUE THREAD

**Issue by BeLi4L** [typeorm/typeorm#7685]
### Expected Behavior

This should compile in TypeScript:

```ts
entityManager.getRepository(SomeEntity)
  .save({
    id: 123,
    someField: null
  })
```

```ts
entityManager.getRepository(SomeEntity)
  .update(123, {
    someField: null
  })
```

### Actual Behavior

I have the following TS errors:

- Using `save()`: 
  ```
  Type 'null' is not assignable to type 'DeepPartial<number | undefined>'.ts(2769)
  ```
- Using `update()`:
  ```
  Type 'null' is not assignable to type '(() => string) | QueryDeepPartialEntity<number | undefined>'.ts(2322)
  ```

### Steps to Reproduce

Try to compile the following code:

```ts
import { PrimaryGeneratedColumn, Column, Entity } from 'typeorm'

@Entity()
class SomeEntity {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  someField: number
}

entityManager.getRepository(SomeEntity)
  .save({
    id: 123,
    someField: null
  })

entityManager.getRepository(SomeEntity)
  .update(123, {
    someField: null
  })
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Ubuntu      |
| Node.js version     | 14.17.0 | 
| Typescript version  | 4.2.4 | 
| TypeORM version     | 0.2.32 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by pkuczynski** [comment]
Why don't you use `undefined`?

**Comment by PauloRSF** [comment]
> This should compile in TypeScript:

I believe it actually shouldn't. Since `someField`'s type is `number`, you can't assign `null` to it. Although, if you want to make it null on postgres (with `@Column({ nullable: true })`), you can assign `undefined` or just omit it.

**Comment by BeLi4L** [comment]
> I believe it actually shouldn't. Since `someField`'s type is `number`, you can't assign `null` to it. Although, if you want to make it null on postgres (with `@Column({ nullable: true })`), you can assign `undefined` or just omit it.

Oops I meant `number | null` yes ;)


> Why don't you use `undefined`?

You mean I should simply replace `null` with `undefined` and that:

```ts
entityManager.getRepository(SomeEntity)
  .save({
    id: 123,
    someField: undefined
  })
```

would set `someField` to `NULL` in database?

**Comment by AlexMesser** [comment]
* `someField` must have `{ nullable: true }` option
* `someFiled` must be of type `number | null`
* `someField: undefined` will be ignored on save/update and `someField: null` will set `NULL` in to database column.

**Comment by imnotjames** [comment]
This is user error with typescript more than anything.  Working as intended & not a bug.  Make the type ` | null` in the entity and you'll be good to go.
