### ISSUE TITLE
options.instanceName is not a type under SqlServerConnectionOptions definition

### ISSUE THREAD

**Issue by paulochoi** [typeorm/typeorm#7686]
## Issue Description

Type "options.instanceName" is missing from SqlServerConnectionOptions and it is throwing a typescript error as the property is not declared within the definition file.

### Expected Behavior

I should be able to add an instanceName property to the options object without a typescript error.

### Actual Behavior
Error:
`The expected type comes from property 'options' which is declared here on  SqlServerConnectionOptions`

### Steps to Reproduce
Create an ormconfig.ts file with a SqlServerConnectionOptions type
```typescript
import { SqlServerConnectionOptions } from 'typeorm/driver/sqlserver/SqlServerConnectionOptions'

const config: SqlServerConnectionOptions = {
  options: {
    ...,
    instanceName: 'test'
  }
}

```

### My Environment
Windows 10
Node.js version | 14.16.0
Typescript version | 4.3.2
TypeORM version | 0.2.32

### Relevant Database Driver(s)
- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [x] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
This can be passed in `extra`
