### ISSUE TITLE
Option to disable logging of `PRAGMA` queries

### ISSUE THREAD

**Issue by Deilan** [typeorm/typeorm#769]
Feature request: implement an option to disable logging of `PRAGMA` queries, which make up a large part of the traffic in SQLite. Wherein logging of the regular CRUD queries should remain active, so `logQueries: false` is not an option in that case. Also, I'd say they should be muted by default, but could be enabled by the option to be implemented.

**Comment by pleerock** [comment]
But PRAMA queries is used only in schema synchronization as I remember. It means you won't have PRAGMA queries once you get system into the production or after a first run. Right?

**Comment by Deilan** [comment]
I'm not sure whether it should be displayed all the time by design or not. But I may definitely say that I see a lot of pragma queries on every single request on using `typeorm` against `sqlite3` database.

**Comment by pleerock** [comment]
can you please provide a sample what queries you see on each request?

**Comment by pleerock** [comment]
Any updates?

**Comment by Deilan** [comment]
@pleerock Take a look at https://github.com/Deilan/typeorm-issue-769.

In this very simple case we have the following:
```
executing query: SELECT * FROM sqlite_master WHERE type = 'table' AND name IN ('first_entities', 'second_entities')
executing query: BEGIN TRANSACTION
creating a new table: first_entities
executing query: CREATE TABLE "first_entities" ("number" integer NOT NULL PRIMARY KEY AUTOINCREMENT)
creating a new table: second_entities
executing query: CREATE TABLE "second_entities" ("number" integer NOT NULL PRIMARY KEY AUTOINCREMENT)
creating a foreign keys: fk_10d004705c0171a2f22a54d8645
executing query: CREATE TABLE "temporary_second_entities" ("number" integer NOT NULL PRIMARY KEY AUTOINCREMENT, FOREIGN KEY("number") REFERENCES "first_entities"("number"))
executing query: INSERT INTO "temporary_second_entities"("number") SELECT "number" FROM "second_entities"
executing query: DROP TABLE "second_entities"
executing query: ALTER TABLE "temporary_second_entities" RENAME TO "second_entities"
executing query: COMMIT
executing query: SELECT "secondEntity"."number" AS "secondEntity_number" FROM "second_entities" "secondEntity"
executing query: SELECT * FROM sqlite_master WHERE type = 'table' AND name IN ('first_entities', 'second_entities')
executing query: PRAGMA table_info("first_entities")
executing query: PRAGMA index_list("first_entities")
executing query: PRAGMA foreign_key_list("first_entities")
executing query: PRAGMA table_info("second_entities")
executing query: PRAGMA index_list("second_entities")
executing query: PRAGMA foreign_key_list("second_entities")
executing query: BEGIN TRANSACTION
executing query: COMMIT
executing query: SELECT "secondEntity"."number" AS "secondEntity_number" FROM "second_entities" "secondEntity"
executing query: SELECT * FROM sqlite_master WHERE type = 'table' AND name IN ('first_entities', 'second_entities')
executing query: PRAGMA table_info("first_entities")
executing query: PRAGMA index_list("first_entities")
executing query: PRAGMA foreign_key_list("first_entities")
executing query: PRAGMA table_info("second_entities")
executing query: PRAGMA index_list("second_entities")
executing query: PRAGMA foreign_key_list("second_entities")
executing query: BEGIN TRANSACTION
executing query: COMMIT
executing query: SELECT "secondEntity"."number" AS "secondEntity_number" FROM "second_entities" "secondEntity"
```

In a more complex queries there's lots and lots of PRAGMAs.

**Comment by Deilan** [comment]
@pleerock Also why there are transactions commiting all the time if there's even no writing?

**Comment by pleerock** [comment]
Those queries are executing **during schema synchronization**, which means you won't have them on production (maybe only once when you deploy and first time run the app with schema sync enabled).

In development they also are executed only when you update something in schema. Schema synchronization in sqlite is the most complex because of limitations sqlite has. So I don't see any point to exclude PRAGMA queries, but don't exclude queries like "create a temporary table", "select all data from old table", "copy all data into temporary table", "remove old table" which are hapenning on any table stuff change. If you'll suggest to exclude both you won't have any sql queries outputed during schema synchronization in sqlite

**Comment by pleerock** [comment]
Let me know if you disagree with me, Im closing this for now

**Comment by maximelafarie** [comment]
> Let me know if you disagree with me, Im closing this for now

I disagree with you, because it can show sensitive data in logs 😕 

![image](https://user-images.githubusercontent.com/5319267/232714249-b2735506-9569-4fba-994b-733b16bdd802.png)

**Comment by pleerock** [comment]
feel like an edge case, in such edge cases you can implement a custom logger and skip the logs starting from "PRAGMA".

**Comment by maximelafarie** [comment]
> feels like an edge case, in such edge cases you can implement a custom logger and skip the logs starting from "PRAGMA".

I just found a cool workaround I hadn't thought of: the `verbose` option. So I put `verbose: () => { }` in the TypeORM configuration object.

Have a great day! 👍
