### ISSUE TITLE
How to get merged data from two column into one relational column with eager = true

### ISSUE THREAD

**Issue by aamirpinger** [typeorm/typeorm#7699]
**I have a question**

```
@Entity({ name: 'usersTable' })
export class User extends BaseEntity {
  @PrimaryGeneratedColumn('uuid', { name: 'col_userId' })
  userId!: string;

  @Column('varchar', { name: 'col_firstName' })
  firstName: string;

  @OneToMany(() => Friend, friend => friend.friendUser, { eager: true })
  myFriends: Friend[];
}


@Entity({ name: 'friendsTable' })
export class Friend extends BaseEntity {
  @PrimaryGeneratedColumn('uuid', { name: 'col_userId' })
  friendId!: string;

  @ManyToOne(() => User, user => user.userId)
  @JoinColumn({ name: 'col_friendUserId' })
  friendUser: User;

  @ManyToOne(() => User, user => user.userId)
  @JoinColumn({ name: 'col_invitedBy' })
  invitedBy: User;
}
```

I want to use find method on User with eager that returns me myFriends having all the records from friendsTable that has my userId in friendUser OR invitedBy, is it possible? How?

**More details**
User table got many users

Friends table got entries of those whom I invited to be my friend. In this case my user Id will be in invitedBy column and the userId I invited will be in friendUser column.

But this Friends table will also have entries where I am invited by other users to be their friend. In this case the same friends table will have my Id in friendUser and the person who invited me id will by in invitedBy Column.

This shows my user id can be in any of these two columns, friendUser or invitedBy  and to my friend Id can again be in any of these columns.

I need to get a user record that eager all my friends no matter if my userId is in invitedBy column or they friendUser column.

**Comment by aamirpinger** [comment]
@pleerock can you help? If it is not possible using find method, how can we do it using query builder. I tried using leftJoinAndSelect but it links to one column on ON clause but I need two conditions in own clause?

**Comment by imnotjames** [comment]
This seems more like a request for general help.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
