### ISSUE TITLE
breaking change introduced in 0.2.33: DriverUtils.buildColumnAlias not available anymore

### ISSUE THREAD

**Issue by homj** [typeorm/typeorm#7705]
## Issue Description
With PR #7509 the `buildColumnAlias` method in `DriverUtils` was renamed to `buildAlias`. The change was released with Version 0.2.33. Other packages, like `nestjs-query` rely on this method and now fail due to the naming change.
As `DriverUtils` are a publicly accessible API, the `buildColumnAlias` method should still be available when the release only resulted in a fix version (bump from 0.2.32 to 0.2.33)

### Expected Behavior
The method should be available under the name `buildColumnAlias`, since fix version bumps should not introduce breaking changes.

### Actual Behavior
The method cannot be accessed with the name `buildColumnAlias`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  alpine  |
| Node.js version     | v14.17.0 |
| Typescript version  | v4.1.5 |
| TypeORM version     | v0.2.33 |

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

**Comment by pleerock** [comment]
Thank you for the report. 

> As DriverUtils are a publicly accessible API, the buildColumnAlias method should still be available when the release only resulted in a fix version (bump from 0.2.32 to 0.2.33)

well, it's used internally and we assume everything we use internally that is not documented or purposely was created for users is free for such changes. I would suggest `nestjs-query` package to avoid using such APIs if possible.

But since potentially break people code, we can publish a new version with `buildColumnAlias` method added back as deprecated.

**Comment by AlexMesser** [comment]
I created a PR #7706 . Can you please check if the following changes would fix the problem?

**Comment by homj** [comment]
thanks for the fast response!

@AlexMesser yes, I think PR #7706 would be sufficient to fix this issue.

**Comment by pleerock** [comment]
Fixed in `0.2.34`
