### ISSUE TITLE
Conditionally unique constraint in PostgreSQL

### ISSUE THREAD

**Issue by Azamatjon** [typeorm/typeorm#7709]
### What was unclear or otherwise insufficient?

I was trying to create conditional Unique constraint with TypeORM:

```
CREATE UNIQUE INDEX unique_user_idx ON user(name) WHERE (key is NOT IN(conditional_col_b));
```

Here I have an entity:
```
@Entity({ name: 'user' })
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column()
    key: string;

    @Column()
    conditionalColB: string;
}
```

For creating Unique constraint I used to add decorator `@Unique(['col_a', 'col_b'])` before the entity. But for conditional I have no idea :(

Could anyone help me?

### Relevant Database Driver(s)

- [x] `postgres`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Azamatjon** [comment]
Could someone help?

**Comment by imnotjames** [comment]
You'll have to manually define it in migrations, as this isn't a feature supported by many databases and is not currently supported by TypeORM.

**Comment by mortezaPRK** [comment]
you should use `@Index` on your entity

```typescript
@Entity({ name: 'user' })
@Index(["name"], {unique: true}, "WHERE (key is NOT IN(conditional_col_b));")
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column()
    key: string;

    @Column()
    conditionalColB: string;
}
```

**Comment by Azamatjon** [comment]
@mortezaPRK Thank you for the answer so much, that is an answer I was looking for...
There I've modified slightly:
```
@Index('idx_booking_cancel_booking_id_stay_date', ['bookingId', 'stayDate'], {
	unique: true,
	where: 'deleted_at IS NULL'
})
```
