### ISSUE TITLE
PostgreSQL - Repository find lock mode for_no_key_update is not being added to query

### ISSUE THREAD

**Issue by ykovalenko-gentech** [typeorm/typeorm#7717]
## Issue Description
When using lock mode for_no_key_update in find method like this:
`repository.find({ lock: { mode: 'for_no_key_update' } })`
Output query does not have lock.

The reason is missing  'for_no_key_update' check in FindOptionsUtils.ts https://github.com/typeorm/typeorm/blob/beea2e1e4429d13d7864ebc23aa6e58fa01647ea/src/find-options/FindOptionsUtils.ts#L184

### Expected Behavior

In case of pg driver, I expect adding ` FOR NO KEY UPDATE` to the end of `SELECT ...`, same as using lock method for QueryBuilder.

### Actual Behavior

Lock is not added because of skipping it on repository level and missing on query builder error.
So resulting query is simple select.

```

```

### Steps to Reproduce

1. Set lock mode for_no_key_update in find method of repository

```typescript
`repository.find({ lock: { mode: 'for_no_key_update' } })`
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14 | 
| Typescript version  | v4.1 | 
| TypeORM version     | v0.2.32 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by herenickname** [comment]
Up
