### ISSUE TITLE
not  able to connect with MS SQL Server

### ISSUE THREAD

**Issue by jigskpatel** [typeorm/typeorm#7726]
## Issue Description

I am trying to connect with MS Sql Server, but I am getting following connection error.
`Failed to connect to cloudapp.net:14345 - self signed certificate +1525ms`

### Actual Behavior

```
// include the output in code tags like these!
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
import { createConnection } from 'typeorm';
import { SavedSearch } from '../entities/saved-search.entity';

export const databaseProviders = [
    {
        provide: 'DATABASE_CONNECTION',
        useFactory: async () => await createConnection({
            type: 'mssql',
            host: 'cloudapp.net',
            port: 14345,
            username: '',
            password: '',
            database: '',
            entities: [
                SavedSearch
            ],
            synchronize: true,
        }),
    },
];

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |        Windows 10  |
| Node.js version     | v14.17.0 | 
| Typescript version  | v4.2.3 | 
| TypeORM version     | v0.2.34 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [x] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by YazeedLoonat** [comment]
To add onto what is here, I ran into this when I upped the version of the mssql package to 7.1.0 where they introduced some additional checks around self signing certs.

namely the two flags:  `validateConnection` and `trustServerCertificate`
which is what is causing this issue I think

**Comment by YazeedLoonat** [comment]
@jigskpatel I'm not sure if this will always work or if it will help, but I did get a work around by adding
```
"extra": {
      "validateConnection": false,
      "trustServerCertificate": true
}
```

to my ormconfig.json

**Comment by berlinjunker** [comment]
> @jigskpatel I'm not sure if this will always work or if it will help, but I did get a work around by adding
> 
> ```
> "extra": {
>       "validateConnection": false,
>       "trustServerCertificate": true
> }
> ```
> 
> to my ormconfig.json

same issue here. Your workaround solves it for me as well. I used this, as we are using .env as ormConf:

`
TYPEORM_DRIVER_EXTRA='{ "validateConnection": false, "trustServerCertificate": true }'
`

**Comment by jigskpatel** [comment]
@YazeedLoonat  @berlinjunker   It's working for me. Thanks for you help. :)
