### ISSUE TITLE
Boolean type always false in .save command

### ISSUE THREAD

**Issue by matheuspereiradev** [typeorm/typeorm#7729]
### Expected Behavior

convert 'true' to true when the column is boolean

### Actual Behavior

the insert always insert false in a column boolean beacause the multer upload

### Steps to Reproduce

1. First is the code of entity, see the column isPrivate is a boolean field and in database is a tinyint
2. I think when the request do upload with the multer the field isPrivate recieve the value -> 'true'  not -> true and when go save to database always save with "0"
3. to resolve temporally this a do  ```ormRepository.create(text,isPrivate:Boolean(isPrivate));```

```typescript
@Entity("tb_ticket_interaction")
class Interaction{

    @PrimaryGenaratedColumn()
    readonly id:number;

    @Column()
    text:string;

    @Column()
    isPrivate:boolean;
}
```

```typescript
 route.post('/',multerUploadFile.single('file'),(request,response)=>{
               const {text,isPrivate} = request.body;
               ormRepository = getRepository(Interaction)
               const interaction = ormRepository.create(text,isPrivate);

               await ormRepository.save(interaction);
})
```

### My Environment

Multer, React, NextJS

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    windows10      |
| Node.js version     | v14.15.0 | 
| Typescript version  | v4.3.2 | 
| TypeORM version     | v0.2.32 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by matheuspereiradev** [comment]
actually Boolean(isPrivate) solution doesn't work isPrivate:isPrivate==='true'

**Comment by imnotjames** [comment]
This doesn't seem to be a typeorm issue directly.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
