### ISSUE TITLE
@PrimaryGeneratedColumn not returning auto generated id from oracle database.

### ISSUE THREAD

**Issue by vitorveiga** [typeorm/typeorm#773]
Hi, i want to persist the following entity in an ORACLE database:

@Entity('DRMS_T_TEG_TEST')
export class Test {

    @PrimaryGeneratedColumn()
    ID_TEST: number;

    @Column({nullable: false})
    ID_TENANT: number;

    @Column({nullable: false})
    NAME: string;

    @Column()
    DESCRIPTION: string;

    @Column({nullable: false})
    EVENT_TYPE: EventType;

    @Column({nullable: false})
    CREATED_BY: string;

    @Column({nullable: false})
    MODIFIED_BY: string;

    @Column('timestamp')
    CREATED_DATE: Date;

    @Column('timestamp')
    MODIFIED_DATE: Date;
}

This entity is correctly persisted, but there not returning value for ID_TEST (PrimaryGeneratedColumn).

Generated Query:
`executing query: declare lastId number; begin INSERT INTO "DRMS_T_TEG_TEST" ("ID_TENANT", "NAME", "EVENT_TYPE", "CREATED_BY", "MODIFIED_BY") VALUES (:ID_TENANT, :NAME, :EVENT_TYPE, :CREATED_BY, :MODIFIED_BY) returning "ID_TEST" into lastId; dbms_output.enable; dbms_output.put_line(lastId); dbms_output.get_line(:ln, :st); end; -- PARAMETERS: [1,"test16","SS","lopes","lopes",{"dir":3003,"type":2001,"maxSize":32767},{"dir":3003,"type":2002}]`
`executing query: COMMIT`

I'am using version  "typeorm": "0.1.0-alpha.34".

Code:
`
            const test = EntityFactory.createTest(payload.body);

            const repo = getConnectionManager().get().getRepository(Test);

            await repo.persist(test);

            console.log(`${test.ID_TEST}`) // > undefined
`
Any ideas?

**Comment by pleerock** [comment]
I think its a bug introduced in latest versions. You should not have this bug in versions lower then `0.1.0-alpha.20`. It has always been problematic to test oracle. PR is accepted for this issue.

**Comment by vitorveiga** [comment]
I recently change to 0.1.0-alpha.32 and works fine. I will try to submit a PR to fix this issue.

Thanks

**Comment by bmackiewicz** [comment]
which last version of typeorm return good lastId in oracle, because i have 0.1.12 and i can't get last insert id ?
When i install 0.1.0-alpha.32 i recive last insert id, changes from 0.1.0-alpha.32 there are't available in 0.1.12 ?

**Comment by pleerock** [comment]
Maybe something was broken in that period. Oracle support is completely rewritten and we are planning to release it in `@next` branch soon. @AlexMesser can you please provide estimates on when oracle support will be available in `@next` ?

**Comment by AlexMesser** [comment]
fixed and released in `typeorm@0.2.0-alpha.23`. You can try it via `npm i typeorm@next`.
