### ISSUE TITLE
TypeError: value.toUpperCase

### ISSUE THREAD

**Issue by jinpy666** [typeorm/typeorm#7730]
When Default value is not a string, a method that does not exist is called

![image](https://user-images.githubusercontent.com/5868671/121478449-9b098a00-c9fb-11eb-8951-68859de297d7.png)

![image](https://user-images.githubusercontent.com/5868671/121478412-9349e580-c9fb-11eb-9180-2647041438a1.png)
![image](https://user-images.githubusercontent.com/5868671/121478518-b2487780-c9fb-11eb-9ae5-ca599bca7fa6.png)

https://github.com/typeorm/typeorm/blob/ff28aad27958ef7763a305982f70caeb611f2448/src/driver/mysql/MysqlDriver.ts#L946

**Comment by imnotjames** [comment]
Functions are used for `Raw` defaults passed directly into the database.  They must always return strings.  If we want to make it handle this case we should probably cast to a string.

**Comment by Mnigos** [comment]
I got same issue now
![image](https://user-images.githubusercontent.com/56691628/148107791-55279b4e-63a2-47c2-8820-f38b2fdc174c.png)

**Comment by Shivam327** [comment]
> I got same issue now ![image](https://user-images.githubusercontent.com/56691628/148107791-55279b4e-63a2-47c2-8820-f38b2fdc174c.png)

Does Your Issue Got Solved ?? IF yes how?

**Comment by Mnigos** [comment]
I update package and now it works.

**Comment by Mnigos** [comment]
Or not still got that error hah
![image](https://user-images.githubusercontent.com/56691628/150639081-484a26a9-9160-4446-acdd-c6fed0627784.png)

**Comment by Mnigos** [comment]
I got that error while trying to connect to db

**Comment by Shivam327** [comment]
> I got that error while trying to connect to db

Delete Your Dist folder...it worked for me.The issue is in Dist Folder

**Comment by Mnigos** [comment]
so I set `synchronize` option to false and now connection works well but when i try to use any endpoint with db i got error 

`relation [entity] does not exist`

**Comment by spearsharp** [comment]
it doesn't work if i delete dist and restart it.

**Comment by kevinjames95** [comment]
use create instead of generate . it works

**Comment by DES-Destry** [comment]
> > I got that error while trying to connect to db
> 
> Delete Your Dist folder...it worked for me.The issue is in Dist Folder

This error also occurred in CLI: `npm run typeorm migration:generate -c seed -- -n SomeSeed`;
Part of package.json: `"typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js --config ./src/database/typeorm.config.ts",`

<img width="1050" alt="Screen Shot 2022-04-26 at 5 04 50 PM" src="https://user-images.githubusercontent.com/50075282/165287336-a2d2a977-6c39-49d7-ab3e-eb16d5a146e4.png">

**Comment by leanne707** [comment]
Try `default: 1` instead of `default: () => 1`

**Comment by gabe2code** [comment]
The error in regards to the default values, we should use direct values instead of functions... 
**default: new Date()** :heavy_check_mark: 
**default: () => new Date()** :x:

**Comment by linh-ph** [comment]
> Or not still got that error hah ![image](https://user-images.githubusercontent.com/56691628/150639081-484a26a9-9160-4446-acdd-c6fed0627784.png)

Hi I got same issue, have you got it fixed yet. I try connect with postgres in using nx repo
![error_postgres](https://user-images.githubusercontent.com/55178748/226240748-1fd4e978-1f68-4f9d-9b53-3dad053ddcf9.jpg)

**Comment by igordonin** [comment]
> > I got that error while trying to connect to db
> 
> Delete Your Dist folder...it worked for me.The issue is in Dist Folder

worked for me too

**Comment by Gregory-Han** [comment]
default: () => 'boy' <= Good
default: 'boy' <= Very Good (Only raw value)

default: () => 'NOW()' <= Very Good    &. default: () => 'CURRENT_TIMESTAMP' <= Very Good for other's compability
default: ''NOW()' <= Poor (It's a string)

But, It's not related above error.
