### ISSUE TITLE
Auto-generated columns and defaults are not generated when creating a new entity instance

### ISSUE THREAD

**Issue by obadakhalili** [typeorm/typeorm#7732]
## Issue Description

TypeORM is erroring out because the ID field is set to `null`. Which is expected, but what is not is TypeORM not auto-generating the ID field, the creation date field, nor setting the defaults for some fields.

### Expected Behavior

TypeORM should auto-generate the ID field how specified, creation date field, and set the defaults for the appropriate fields.

### Actual Behavior

TypeORM isn't auto-generating the ID field, creation date field, and is not setting the defaults.

```
QueryFailedError: null value in column "user_uuid" of relation "transblog_user" violates not-null constraint
    at new QueryFailedError (D:\transblog\node_modules\typeorm\error\QueryFailedError.js:12:28)
    at PostgresQueryRunner.<anonymous> (D:\transblog\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:248:31)
    at step (D:\transblog\node_modules\tslib\tslib.js:143:27)
    at Object.throw (D:\transblog\node_modules\tslib\tslib.js:124:57)
    at rejected (D:\transblog\node_modules\tslib\tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  length: 414,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (null, obkha, ob@kha.com, Red!1234                                                        ..., Ob, Kha, Palestinian, null, null, 0, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'd:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\executor\\execmain.c',
  line: '1953',
  routine: 'ExecConstraints',
  query: 'INSERT INTO "transblog_user"("user_uuid", "created_at", "username", "email", "user_password", "first_name", "last_name", "nationality", "dob", 
"bio", "translation_points") VALUES (DEFAULT, DEFAULT, $1, $2, $3, $4, $5, $6, DEFAULT, DEFAULT, DEFAULT) RETURNING "user_uuid", "created_at", "translation_points"',
  parameters: [ 'obkha', 'ob@kha.com', 'Red!1234', 'Ob', 'Kha', 'Palestinian' ]
}
```

### Steps to Reproduce

Simply create and try to save/insert an entity instance that expects an ID, which is configured to be auto-generated through TypeORM.

[Reproduction](https://github.com/obadakhalili/transblog/blob/feature-signup-route/packages/api/src/user/user.service.ts)

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Win64       |
| Node.js version     | v16.2.0 | 
| Typescript version  | v4.2.3| 
| TypeORM version     | v0.2.34| 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Are you explicitly setting the field to null rather than undefined?  Have you tried undefined?

Can you include example entities that exhibit this?

**Comment by MaEdAlpha** [comment]
Having the same issue. Any solutions out there?
