### ISSUE TITLE
repository.find() with select relations, getting column does not exist 

### ISSUE THREAD

**Issue by andrei9669** [typeorm/typeorm#7733]
## Issue Description

While using repo.find(), I add a relation and then select only that relation, I get this error
```
(node:9064) UnhandledPromiseRejectionWarning: QueryFailedError: column User.userId does not exist
    at new QueryFailedError (F:\projects\Personal\TypeOrmTest\src\error\QueryFailedError.ts:11:9)
    at PostgresQueryRunner.<anonymous> (F:\projects\Personal\TypeOrmTest\src\driver\postgres\PostgresQueryRunner.ts:228:19)
    at step (F:\projects\Personal\TypeOrmTest\node_modules\tslib\tslib.js:143:27)
    at Object.throw (F:\projects\Personal\TypeOrmTest\node_modules\tslib\tslib.js:124:57)
    at rejected (F:\projects\Personal\TypeOrmTest\node_modules\tslib\tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not
 handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (r
ejection id: 1)
(node:9064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

````
### Expected Behavior

I expect to get array of objects with only clients field.

### Actual Behavior

TypeOrm creates a query like this and I get error because "User"."userId" doesn't exist.
my guess is that it should have been "User_User__clients"."userId" or something like that.
```sql
SELECT "User__clients"."id"   AS "User__clients_id",
       "User__clients"."name" AS "User__clients_name",
       "User"."userId"
FROM "public"."user" "User"
         LEFT JOIN "public"."client_users_user" "User_User__clients"
                   ON "User_User__clients"."userId" = "User"."id"
         LEFT JOIN "public"."client" "User__clients"
                   ON "User__clients"."id" = "User_User__clients"."clientId"
WHERE "User"."id" = $1
```

### Steps to Reproduce

1. clone this repo: https://github.com/andrei9669/typeorm-select-with-relations.git
2. run `npm install`
3. if you have docker then run `docker-compose up` if not, then create postgres db and fill the ormconfig.json
4. run `npm start`
5. open `http://localhost:3000/users`
6. in the console, you will see the error.

```typescript
// client.entity.ts
@Entity('client', { schema: 'public' })
export class Client {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('text')
  name: string;

  @ManyToMany(() => User, (user) => user.clients)
  users: User[];
}

// user.entity.ts
@Entity('user', { schema: 'public' })
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('text')
  name: string;

  @ManyToMany(() => Client, (client) => client.users)
  @JoinTable({ name: 'client_users_user' })
  clients: Client[];
}

// UserController.ts
export class UserController {

  private userRepository = getRepository(User);

  async all(request: Request, response: Response, next: NextFunction) {
    const {id} = await this.userRepository.findOne()
    return this.userRepository.find({
      select: ['clients'],
      where: {id},
      relations: ['clients'],
    });
  }
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Edition: Windows 10 Pro; Version: 21H1; OS build: 19043.1023 |
| Node.js version     | v14.16.0  | 
| Typescript version  | v3.3.3333| 
| TypeORM version     | v0.2.34 | 

### Additional Context

none

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
the `select` `findOption` currently only works with properties on the main alias.

Definitely something we should be fixing, though..

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
