### ISSUE TITLE
changelog for Version 0.2.34 is missing in CHANGELOG.md

### ISSUE THREAD

**Issue by Kr0san89** [typeorm/typeorm#7740]
### CHANGELOG.md

The CHANGELOG.md is missing the changes for Version 0.2.34

### Recommended Fix

Please provide the changes for Version 0.2.34

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [X] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by pleerock** [comment]
fixed, thank you
