### ISSUE TITLE
PostgreSQL - Adding a custom decorator for the tstzrange type

### ISSUE THREAD

**Issue by H6LS1S** [typeorm/typeorm#7747]
## Feature Description
Adding a custom decorator for the range type, similar to CreateDateColumn, etc. This solution has been working for me for about a year, it solves a couple of common problems, namely:
- Transforming an array of dates into a special range format
- Special transformation for null value `null -> ['-infinity', 'infinity']`
 
### The Problem
The problem is that this self-written decorator, written following the example of decorators from this repository, wanders with me from project to project. Although for me this is a fairly common case of storing a dates in this type

### The Solution
The solution requires some refinement and testing, since I did not consider compatibility with other databases and types tzrange and etc.

```ts
import { ColumnOptions, Column, FindOperator } from 'typeorm';

export function RangeColumn<T>(options?: ColumnOptions): PropertyDecorator {
  return function (target: unknown, propertyKey: string | symbol) {
    const transformer = {
      to: (value: number[] | FindOperator<T>): string | string[] | FindOperator<T> => {
        if (value instanceof FindOperator) return value;
        if (options.type === 'tstzrange' && !value) return "['-infinity', 'infinity']";
        return JSON.stringify(value);
      },
      from: (value: string) => {
        try {
          return JSON.parse(value);
        } catch {
          return null;
        }
      },
    };

    Column({ transformer, ...options })(target, propertyKey);
  };
}

```

Usage
```ts

@Entity('foo')
export class FooEntity extends BaseEntity {
   ...

  @Type(() => Date)
  @ApiProperty({ type: () => [Date], example: [new Date(), new Date()] })
  @RangeColumn({ type: 'tstzrange', nullable: true })
  public readonly period?: [Date, Date];

   ...
}

```

### Relevant Database Driver(s)
- [x] `postgres`

### Are you willing to resolve this issue by submitting a Pull Request?
- [x] Yes, I have the time, and I know how to start.

**Comment by Ginden** [comment]
I would suggest using defining custom type for that.

```typescript
class DatabaseRange<T = unknown> {
    static readonly defaultUpperBound = 'infinity';
    static readonly defaultLowerBound = '-infinity';
    static readonly validationFunction: (v: T) => boolean = () => true;
    public from: T;
    public to: T;
    public openness: '()' | ' []' | '(]' | '[)'
}

class TsTzRange<Date | 'Infinity' | '-Infinity'> {}
```

We use ranges extensively and it's quite hard to use them right.
