### ISSUE TITLE
cordova-sqlite-storage iosDatabaseLocation parameter is not being honored

### ISSUE THREAD

**Issue by Cure4Life** [typeorm/typeorm#7751]
## Issue Description
The cordova-sqlite-storage plugin has an alternative parameter for iOS database location - iosDatabaseLocation - but it is not recognized by typeORM and  when trying to use it the following error is returned: 
`Error: Driver option (location) is not set`

If I try to use the values as described in the cordova-sqlite-storage docs for the typeORM 'location' parameter:
`Error: Valid iOS database location could not be determined in openDatabase call`

From cordova-sqlite-storage docs: 
```
To specify a different location (affects iOS/macOS only):
var db = window.sqlitePlugin.openDatabase({name: 'my.db', iosDatabaseLocation: 'Library'}, successcb, errorcb);

where the iosDatabaseLocation option may be set to one of the following choices:

default: Library/LocalDatabase subdirectory - NOT visible to iTunes and NOT backed up by iCloud
Library: Library subdirectory - backed up by iCloud, NOT visible to iTunes
Documents: Documents subdirectory - visible to iTunes and backed up by iCloud
```

### Expected Behavior

Either passing one of the three iOS only options to typeORM's 'location' parameter or have typeORM be able to recognize 'iosDatabaseLocation' and pass accordingly.

### Actual Behavior
Apparently, only the 'location' parameter can be used and only with the value of 'default', which means we cannot specify the location we want the database to reside, even though cordova-sqlite-storage allows it.

```
Error: Valid iOS database location could not be determined in openDatabase call
```

### Steps to Reproduce

1. Try using 'Library' or 'Documents' as the 'location' value, or try replacing 'location' with 'isoDatabaseLocation' as per the cordova-sqlite-storage docs

```
const typeorm = require("typeorm");
typeorm.createConnection({
	"type": "cordova",
	"synchronize": true,
	"location": "Documents", // Error: Valid iOS database location could not be determined in openDatabase call
	"logging": true,
	"logger": "simple-console",
	"database": "database.db",
	"entities": [
		require('./entity/Post')
	]
}).then(....)
```

```
const typeorm = require("typeorm");
typeorm.createConnection({
	"type": "cordova",
	"synchronize": true,
	"iosDatabaseLocation": "Documents", //  Error: Driver option (location) is not set
	"logging": true,
	"logger": "simple-console",
	"database": "database.db",
	"entities": [
		require('./entity/Post')
	]
}).then(....)
```

### My Environment

Testing typeORM in a Quasar framework with Vue. Very preliminary and not even close to an actual working product but wanted to start with the database aspect.

### Additional Context

None that I can think of - really wanted to play around with the different location options that are available for iOS

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [x] `cordova`  - specifically cordova-sqlite-storage
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

Any suggestions to get this working is appreciated but I believe this is something that has not been implemented in typeORM.

Thank you

**Comment by imnotjames** [comment]
This needs to be passed through `extra`, doesn't it?

You can always add this via a PR but I think the `extra` field accomplishes this.

**Comment by Cure4Life** [comment]
@imnotjames In my trials, passing in the extra param resulted in both `location` and `iosDatabaseLocation` being passed which resulted in an error from cordova-sqlite-storage  stating that both cannot be passed at the same time. It needs to be one or the other but there is no way I found to achieve that since `location` is required by TypeORM and its value cannot be anything other than `default`
