### ISSUE TITLE
Unable to use composite key as a foreign key

### ISSUE THREAD

**Issue by haris-syed** [typeorm/typeorm#7757]
## Issue Description
I have the following entity:
```ts
@Entity()
@Unique(['name'])
export class Bot {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ nullable: false })
  name!: string;

  @OneToMany(() => Intent, (intent) => intent.bot, { eager: true })
  intents!: Intent[];
}
```
I have another entity that has a many-to-one relation with the above entity and it uses the above entities foreign key as part of its composite primary key.
```ts
@Entity()
export class Intent {
  @PrimaryColumn()
  name!: string;

  @PrimaryColumn()
  botId!: string;

  @OneToMany(() => IntentExample, (example) => example.intent, {
    eager: true,
    cascade: true,
  })
  examples!: IntentExample[];

  @ManyToOne(() => Bot, (bot) => bot.intents, {
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'botId', referencedColumnName: 'id' })
  bot!: Bot;
}
```
Then i have another entity which has a many-to-one relation with the above entity.
```ts
@Entity()
export class IntentExample {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column()
  text!: string;

  @ManyToOne(() => Intent, (intent) => intent.examples, {
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  })
  @JoinColumn([
     { name: 'intentName', referencedColumnName: 'name' },
     { name: 'botId', referencedColumnName: 'botId' },
   ])
  intent!: Intent;
}
```

### Expected Behavior
This should create the proper schema in the DB

### Actual Behavior

I get an error on app startup:
```
[Nest] 282131   - 06/17/2021, 7:39:51 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +86ms
QueryFailedError: foreign key constraint "FK_f6482a1876bee78f417ef6584b8" cannot be implemented
    at new QueryFailedError (/home/haris/Desktop/minitron/server/node_modules/typeorm/error/QueryFailedError.js:12:28)
    at PostgresQueryRunner.<anonymous> (/home/haris/Desktop/minitron/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:248:31)
    at step (/home/haris/Desktop/minitron/server/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/home/haris/Desktop/minitron/server/node_modules/tslib/tslib.js:124:57)
    at rejected (/home/haris/Desktop/minitron/server/node_modules/tslib/tslib.js:115:69)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Steps to Reproduce

1. Create the above entities in a typeorm project
2. Start the app

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Fedora 34     |
| Node.js version     | v16.3.0 | 
| Typescript version  | v4.3.2 | 
| TypeORM version     | v0.2.34 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by affanshahid** [comment]
I am having the same issue

**Comment by MoosaSaadat** [comment]
Facing the same issue!

**Comment by imnotjames** [comment]
What query is being generated?

**Comment by haris-syed** [comment]
Ok so the issue was solved by adding @Column({ type: 'uuid' }) on the botId property in the "Intent" entity. So the Intent Entity would become:
```ts
@Entity()
export class Intent {
  @PrimaryColumn()
  name!: string;

  @PrimaryColumn()
  @Column({ type: 'uuid' }) //this fixed the issue
  botId!: string;

  @OneToMany(() => IntentExample, (example) => example.intent, {
    eager: true,
    cascade: true,
  })
  examples!: IntentExample[];

  @ManyToOne(() => Bot, (bot) => bot.intents, {
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'botId', referencedColumnName: 'id' })
  bot!: Bot;
}
```
@imnotjames thanks for pointing me in the right direction. Looking at the query gave me a helpful hint :)
