### ISSUE TITLE
Issue with runMigration and MigrationExecutor

### ISSUE THREAD

**Issue by GabrielPadureanu** [typeorm/typeorm#7758]
Trying to get run pending migrations, but I can't get them properly. The array of migrations is currently empty. None of the actions below result in any migration showing up.
![image](https://user-images.githubusercontent.com/72932961/122423125-5bf8ad00-cf96-11eb-9810-ac3b8cc28cc2.png)
![image](https://user-images.githubusercontent.com/72932961/122422928-37043a00-cf96-11eb-977c-ab51f5208da3.png)
![image](https://user-images.githubusercontent.com/72932961/122423245-73d03100-cf96-11eb-88f0-89e20d6deed7.png)

ormconfig.json contains the following:
![image](https://user-images.githubusercontent.com/72932961/122423526-a37f3900-cf96-11eb-9553-c004a323de1a.png)

**Comment by imnotjames** [comment]
Looks like it can't find your migrations.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
