### ISSUE TITLE
QueryRunnerProviderAlreadyReleasedError for Transaction

### ISSUE THREAD

**Issue by guanhongtan** [typeorm/typeorm#776]
Hi,
I'm using typeorm 0.0.11 version. I got below error message when running a transaction. It seems when I was trying to persist to a second table, the database connection is closed:

In propse trade, fail in 2nd persit[2017-08-18 14:14:57.577] - INFO - In propse trade, fail in 2nd persit (my error log).

QueryRunnerProviderAlreadyReleasedError: Database connection provided by a query runner was already released, cannot continue to use its querying methods anymore  (This is error message).

The database driver I'm using is mysql. Do we have to implement the connection pool for mysql for this to work?

Here is partial code:

     this.db.entityManager.transaction(async transactionalEntityManager => {
                            transactionalEntityManager.persist(table1)
                            .then((result) => {

                                console.log('successful in 1st persist');
                                let sAction: SAction = new SAction();
                
                                sActionId.Id = result.sId;
                                sActionId.stateId = TS.TRIED;
         
                                transactionalEntityManager.persist(sAction)
                                .then((result) => {
                                    console.log('successful in 2nd persist');
                                  })
                              .catch((err) => {
                                    console.log('fail in 2nd persit');
                                    return reject(err);
                                });
                           })
                           .catch((err) => {
                                return reject(err);                              
                            });

**Comment by pleerock** [comment]
You simply not awaiting promises inside your transaction. Try to change your code to:
```ts
 this.db.entityManager.transaction(async transactionalEntityManager => {
                        return transactionalEntityManager.persist(table1)
                        .then((result) => {

                            console.log('successful in 1st persist');
                            let sAction: SAction = new SAction();
            
                            sActionId.Id = result.sId;
                            sActionId.stateId = TS.TRIED;
     
                            return transactionalEntityManager.persist(sAction)
                            .then((result) => {
                                console.log('successful in 2nd persist');
                              })
                          .catch((err) => {
                                console.log('fail in 2nd persit');
                                return reject(err);
                            });
                       })
                       .catch((err) => {
                            return reject(err);                              
                        }); 
```

**Comment by pleerock** [comment]
I think this can be closed

**Comment by erald14** [comment]
@pleerock  helpful thanks
