### ISSUE TITLE
Is there a way to get entity's columns keys?

### ISSUE THREAD

**Issue by suhaotian** [typeorm/typeorm#7763]
## Feature Description
```ts
@Entity()
class User {
  @Column()
  username: string;

  @Column({ nullable: true })
  email?: string;

  // ...many others entity
}
```
I want get all of the columns name of the entity like email and username... etc. 
### The Problem
Is there a way to get entity's columns keys? It will be very helpful to select fields. 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Yes, you can access the entity metadata off of the connection.

This is more of a question than a request for a new feature. 

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by suhaotian** [comment]
Thank you. It works:
```ts

const fieldsOfUser = Object.keys(
   getConnection().getRepository(User).metadata.propertiesMap,
)
```
