### ISSUE TITLE
Entity.save does not trigger @BeforeUpdate

### ISSUE THREAD

**Issue by dmitrif** [typeorm/typeorm#7766]
## Issue Description
When an entity has `@BeforeUpdate` it is not triggered on save.

Entity:
```
  @BeforeUpdate()
  hashNewPassword = async (): Promise<void> => {
    if (this.id && this.newPassword) {
      this.password = await hash(this.newPassword);
    }
  };
```

Invocation:
```
    const user = await User.findOne({
      where: { id: userId },
    });
    ...
    user.newPassword = req.body.newPassword;
    await user.save();

```

### Expected Behavior
- `@BeforeUpdate` should fire

### Actual Behavior
- `@BeforeUpdate` is never called

### Steps to Reproduce
Attempt to select an entity and then save it with a beforeUpdate.

### My Environment
| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Debian 10     |
| Node.js version     | v14.15.1 | 
| Typescript version  | v4.1.2| 
| TypeORM version     | v0.2.34 | 

### Additional Context
N/A

### Relevant Database Driver(s)
- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
What happens if you declare the function as a function instead of a property?

**Comment by dmitrif** [comment]
@imnotjames Hi there! 

```
  @BeforeUpdate()
  async hashNewPassword(): Promise<void> {
    console.log('hashing new password');
    if (this.id && this.newPassword) {
      this.password = await hash(this.newPassword);
    }
  }
```

Also does not trigger.

**Comment by imnotjames** [comment]
Just to confirm - it's writing to the database?

**Comment by dmitrif** [comment]
@imnotjames You are onto something. It doesn't when a non column property gets updated.

Does not trigger an update:
```
    user.newPassword = req.body.newPassword;
    await user.save();
```

Triggers update:
```
    user.newPassword = req.body.newPassword;
    user.password = '123123';
    await user.save();
```

In this case the entity def abridged is:
```
  @Column()
  password!: string;

  newPassword: string | undefined;
```

Is this expected?

**Comment by imnotjames** [comment]
`save` is smart about things.  It won't hit the database if there weren't changes.

Instead of a hook for this case why not a function you explicitly call which does the hashing?

**Comment by dmitrif** [comment]
That approach will work for sure. Was attempting to make it an indirect operation to ensure some additional safety that if someone was attempting to update the entity with a new password that it would be guaranteed to be properly hashed.

But, it's not entirely critical either :) 

Thanks a lot, @imnotjames !
