### ISSUE TITLE
ConnectionError using mssql package version 7.1.x

### ISSUE THREAD

**Issue by AcidSlide-Octal** [typeorm/typeorm#7769]
## Issue Description
Runtime error when using mssql package 7.1.x (7.1.3 is the current latest as of 20210620)
**ConnectionError: Failed to connect to localhost:1433 - self signed certificate**

### Expected Behavior
No correction error
Please note this is/was working in mssql package 6.3.x (with the last version at 6.3.2)

### Actual Behavior
```
ConnectionError: Failed to connect to localhost:1433 - self signed certificate
    at <project_folder>/node_modules/mssql/lib/tedious/connection-pool.js:71:17
    at Connection.onConnect (<project_folder>/node_modules/tedious/lib/connection.js:1027:9)
    at Object.onceWrapper (events.js:421:26)
    at Connection.emit (events.js:314:20)
    at Connection.emit (<project_folder>/node_modules/tedious/lib/connection.js:1055:18)
    at Connection.socketError (<project_folder>/node_modules/tedious/lib/connection.js:1653:12)
    at Socket.<anonymous> (<project_folder>/node_modules/tedious/lib/connection.js:1417:14)

```

### Steps to Reproduce
1. Install 'npm install mssql@latest'
2. Run application

### My Environment
OS Version     : macOS Big Sur
NodeJS Version : v12.20.1
NPM Version    : 7.18.1 
Typescript: 4.3.4

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [X] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Mssql now throws an error because of self signed certificates.  I'm sure there's an option you can pass to `extra` to bypass this but we won't be updating typeorm to ignore certificate errors.

**Comment by zoubeihua** [comment]
问下这个问题解决了吗？ 我也报这样的错

**Comment by aixiamomo** [comment]
version: 0.2.x
```
export const connectionSQlServerOpts: ConnectionOptions = {
  name: 'xx',
  type: 'mssql',

  host: 'xx',
  port: 433,
  database: 'xx',
  username: 'xx',
  password: 'xx',

  entities: [
    Model
  ],
  synchronize: true,
  extra: {
    trustServerCertificate: true
  }
}
```

version: 0.3.x
```
export const AppDataSource = new DataSource({
  type: "mssql",
  host: "xxx",
  port: 433,
  username: "xx",
  password: "xx",
  database: "xx",
  synchronize: true,
  logging: false,
  entities: [User],
  migrations: [],
  subscribers: [],
  extra: {
    trustServerCertificate: true,
  }
})

```
