### ISSUE TITLE
Postgres (pg) dependency @^7.0.0 throws error

### ISSUE THREAD

**Issue by benbayard** [typeorm/typeorm#777]
There was an error connection to the database
      duplicate key value violates unique constraint "pg_type_typname_nsp_index"
```js
      { autoSchemaSync: true,
        database: 'dinosaur_testing',
        host: 'localhost',
        password: 'potato',
        port: 5432,
        type: 'postgres',
        username: 'bbayard',
        entities: 
         [ { [Function: User] from: [Function] },
           [Function: ForgotPassword] ],
        logging: false,
        name: '1503094092464' }
```

**Comment by pleerock** [comment]
do you have this error only with `7.0.0` ? What about older versions?

**Comment by benbayard** [comment]
Only version 7. Version 6 works fine.

**Comment by lovio** [comment]
I also encounter this error in some case.

**Comment by pleerock** [comment]
Use version 6 for now. I'll upgrade version to 7 soon and will fix this issue

**Comment by pleerock** [comment]
Checked with `7.3.0` version and it works fine. Please check it again, maybe 7 version you used was buggy.

**Comment by pleerock** [comment]
I'll close it. Please let me know if `7.3.0` does not work for you

**Comment by benbayard** [comment]
Thanks @pleerock I'll try tonight!

**Comment by phaalonso** [comment]
I'm having this error in `8.0`
