### ISSUE TITLE
Add a method to rollback a transaction within a callback

### ISSUE THREAD

**Issue by antoine-pous** [typeorm/typeorm#7778]
## Feature Description
Add a way to rollback a transaction callback even if all queries are ok

### The Problem
Currently we can rollback a transaction only by throwing an error inside the callback, maybe by rejecting a new promise, but not tested. This behavior is incredibly frustrating, because we can have to rollback a transaction for many reasons, not forcibly related to an SQL error

### The Solution
Allowing to return `entityManager.rollbackTransaction()` from the callback to specify what to do even if there's no throwed error.

```ts
getConnection().manager.transaction(async (m: EntityManager) => {
  const data: DataEntity = await ...
  if(shouldFail) {
    return m.rollbackTransaction()
})
```

### Considered Alternatives
I've not tested but maybe we can do
```ts
getConnection().manager.transaction(async (m: EntityManager) => {
  return new Promise((resolve, reject) => {
    const data: DataEntity = await ...
    if(shouldFail) {
      return reject()
    }
    return resolve() 
  }
})
```
But IMO, this kind of usage is not really usefull and a way to explicitly rollback should be implemented for a better code readability.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
The intent of the `connection.transaction` and `manager.transaction` is to manage the entirety of the transaction.

Should you want to rollback a transaction the way it works is via throwing an exception.

If you want more control over the transaction & how it works you need to use the `queryRunner` directly.

```
const queryRunner = getConnection().createQueryRunner();

const data: DataEntity = await ...
if(shouldFail) {
  queryRunner.rollbackTransaction()
} else {
  queryRunner.commitTransaction()
}
```

**Comment by antoine-pous** [comment]
Throwing must remain an exception based on unintended errors. We must be able to simply reject the transaction promise without throwing, like promise rejection was designed for.
