### ISSUE TITLE
Repository.clear() generates incorrect sql for Oracle

### ISSUE THREAD

**Issue by tsraza** [typeorm/typeorm#7779]
## Issue Description

The generated sql for the `clear()` method does not work in Oracle.

### Expected Behavior

There needs to be quotation marks around both the schema and table name, or none at all.

`truncate table "SCHEMA"."TABLE_NAME"`

### Actual Behavior

`truncate table "SCHEMA.TABLE_NAME"`

```
truncate table "SCHEMA.TABLE_NAME"
Error report -
ORA-00942: table or view does not exist
00942. 00000 -  "table or view does not exist"
*Cause:    
*Action:
```

### Steps to Reproduce

```typescript
import "reflect-metadata";
import { createConnection, Entity, PrimaryColumn } from "typeorm";

@Entity('TEST_USER')
export class User {
    @PrimaryColumn()
    username: string;
}

createConnection({
    type: "oracle",
    username: "",
    password: "",
    schema: "", // only errors when the schema is explicitly provided
    connectString: "",
    synchronize: true,
    logging: true,
    entities: [User],
}).then(async connection => {
    await connection.manager.getRepository(User).clear()
}).catch(error => console.log(error));
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.17.0 | 
| Typescript version  | v3.3.3333 | 
| TypeORM version     | v0.2.34 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [x] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by tsraza** [comment]
`.delete({})` accomplishes the desired effect

**Comment by imnotjames** [comment]
It's probably calling `clearTable` and passing both the schema and table name.

```
    async clearTable(tableName: string): Promise<void> {
        await this.query(`TRUNCATE TABLE "${tableName}"`);
    }
```

It probably needs to call `buildTableName` which.. unfortunately throws away the schema.

That's probably what `.delete()` does.
