### ISSUE TITLE
Is using LIKE and ILIKE safe from SQL injection?

### ISSUE THREAD

**Issue by serendipity1004** [typeorm/typeorm#7784]
```
import {ILike} from "typeorm";

const loadedPosts = await connection.getRepository(Post).find({
    title: ILike("%out #%")
});
```

above code is what I have copied from the example.

if I say replace ILike('%out #%') with ILike('${name}%') is it safe from SQL injection? If not, how do I make it safe in same syntax?

**Comment by imnotjames** [comment]
Both of these should be safe from injection, yes.  They're included as a separate parameter.

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
