### ISSUE TITLE
max of varchar(max) or varbinary(max) causing alter drop column and alter add column on orm restart. 

### ISSUE THREAD

**Issue by scooleo** [typeorm/typeorm#7795]
## Issue Description

When max is used as the length for varchar / nvarchar / varbinary it causes the column to be dropped and recreated on every restart of my project that uses TypeORM. The problem with this behaviour is that any data that existed in the column is also dropped on the drop and create of the column.

This does not happen with any other data type that I am using.

### Actual Behavior

```
//This is what is happening.
query: SELECT * FROM "mydatabase"."INFORMATION_SCHEMA"."TABLES" WHERE "TABLE_NAME" = 'typeorm_metadata' AND "TABLE_SCHEMA" = SCHEMA_NAME()
query: ALTER TABLE "invoice" DROP COLUMN "someting"
query: ALTER TABLE "invoice" ADD "someting" varchar(max)
query: COMMIT
server started on http://localhost:4000/graphql
```

### Steps to Reproduce

1. This problem happens when connecting to Microsoft Azure SQL Server. 
I am using  
"mssql": "^6.0.1", 
"typeorm": "^0.2.11"
"@types/express": "^4.16.0",
"express": "^4.16.4",
"apollo-server-express": "^2.11.0"
 in my package.json

```typescript

// Invoice.ts

import {
  Entity,
  Column,
  BaseEntity,
} from "typeorm";
import { ObjectType, Field, ID, } from "type-graphql";

@ObjectType() 
@Entity() 

export class Invoice extends BaseEntity {
/////The problem is in this file here!!
  @Field({ nullable: true })
  @Column({ type: "varchar", length: "max", nullable: true }) //max causes drop and add of column on restart
  // @Column({ type: "text", nullable: true }) //works but is getting deprecated
  someting?: string;

}

//resolver.ts
import { Invoice } from "./Invoice";

@Resolver(Invoice)
export class InvoiceResolver {

  @Query(() => [Invoice]) 
  async Invoice() {
    return Invoice.find();
  }
}

//invoiceResponse.ts
import { ObjectType, Field } from "type-graphql";
import { Invoice } from "./Invoice";
@ObjectType()
export class InvoiceResponse {
  @Field()
  invoice: Invoice
}

//InvoiceInput.ts
import { Field, InputType, Int } from "type-graphql";

@InputType()
export class InvoiceInput {
  @Field({ nullable: true })
  someting?: string;
}


//createSchema.ts   //place in modules dir 
import { buildSchema } from "type-graphql";

export const createSchema = () =>
  buildSchema({
    resolvers: [__dirname + "/../modules/*/*.ts"],
  });

//index.ts
//connect to Azure SQL server --spin up a free azure account for testing

import { SqlServerConnectionOptions } from "typeorm/driver/sqlserver/SqlServerConnectionOptions";
import express from "express";
import { createSchema } from "./createSchema";
import { ApolloServer } from "apollo-server-express";

const schema = await createSchema();

  const apolloServer = new ApolloServer({
    schema,
  });

const main = async () => {
  const mainConfig: SqlServerConnectionOptions = {
    type: "mssql",
    host: process.env.TYPEORM_HOST,
    username: process.env.TYPEORM_USERNAME,
    password: process.env.TYPEORM_PASSWORD,
    database: process.env.TYPEORM_DATABASE,
    entities: ["dist/entity/**/*"],
    migrations: ["dist/migration/**/*"],
    migrationsTableName: undefined,
    subscribers: ["dist/subscriber/**/*"],
    synchronize: true,  
/* can  set synchronize: false to stop the problem happening but this will bite me at some stage later when I set to true */
    logging: true,
    options: {
      encrypt: true,
      enableArithAbort: true,
    },
  };

const app = express();
apolloServer.applyMiddleware({ app });
const server = createServer(app);
server.listen(process.env.PORT || 4000, () => {
console.log("server started on http://localhost:4000/graphql");
});
main().catch((err) => console.error(err));
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Mac OS / Ubuntu /WebApp Service         |
| Node.js version     |v14.15.4| 
| Typescript version  | typescript@4.2.4 | 
| TypeORM version     |typeorm@0.2.24| 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [X] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [X] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

I am happy to contribute $ to the project to get this one fixed.

Thank you in advance!

**Comment by scooleo** [comment]
OK - so l looked at the driver and it is implemented as MAX not max!

This now works with MAX

export class Invoice extends BaseEntity {

  @Field({ nullable: true })
  @Column({ type: "varchar", length: "MAX", nullable: true })
  // @Column({ type: "text", nullable: true })
  someting?: string;

}

**Comment by scooleo** [comment]
This bug can be closed!!

**Comment by scooleo** [comment]
Implemented as MAX not max - non issue once I looked at the driver!

**Comment by 1mehdifaraji** [comment]
I still get an error with length property :

```typescript
  @Column({ type: "varchar", length: "MAX", nullable: true })
  desc?: string;
```

Here is the error message :

```typescript
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'MAX) NULL,
```

**Comment by avmesquita** [comment]
> I still get an error with length property :
> 
> ```ts
>   @Column({ type: "varchar", length: "MAX", nullable: true })
>   desc?: string;
> ```
> 
> Here is the error message :
> 
> ```ts
> sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'MAX) NULL,
> ```

MAX is used to MS SQL Server (Azure SQL) only.
For Mysql, try to use 'longtext', without length property. I use it to save files in base64 format.

**Comment by fdikmen** [comment]
My suggested solution is this:

If you want to store very long texts, you can use text type:
`@Column({ type: "text", nullable: true })`

If you want to define a character-limited varchar column, you must specify the length with a number:
`@Column({ type: "varchar", length: 255, nullable: true })`
