### ISSUE TITLE
Custom foreign key name ignored in following migrations

### ISSUE THREAD

**Issue by clementguillot** [typeorm/typeorm#7802]
## Issue Description

When a foreign key is created using migration API with a custom name, the next generated migration deletes and recreates the FK with the default naming convention (FK_sha1).

### Expected Behavior

When running `typeorm migration:generate -n MyNewMigration` after we have successfuly applied our first migration, we should have the ouput
`No changes in database schema were found - cannot generate a migration.`

### Actual Behavior

A second migration is created even if we do not change our entities.
`Migration ./migrations/1624608379416-MyNewMigration.ts has been generated successfully.`

### Steps to Reproduce

1. Consider the two following entites:

```ts
@Entity('users')
export class User extends CoreEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @OneToMany(() => Company, (company) => company.createdBy)
  createdCompanies: Company[];
}
```

```ts
@Entity('companies')
export class Company {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => User, (user) => user.createdCompanies, {
    cascade: true,
    nullable: false,
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'createByUserId', referencedColumnName: 'id' })
  createdBy: User;
}
```
2. We create the Company entity with the following migration using API:
```ts
export class CreateCompanySchema1624547033107 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // skip user creation
    await queryRunner.createTable(
      new Table({
        name: 'companies',
        columns: [
          {
            name: 'id',
            type: 'varchar',
            isPrimary: true,
            generationStrategy: 'uuid',
            isNullable: false,
          },
          {
            name: 'createByUserId',
            type: 'varchar',
            length: '36',
            isNullable: false,
          },
        ],
      })
    );
    await queryRunner.createForeignKey(
      'companies',
      new TableForeignKey({
        name: 'FK_companies_users_id', // we use a custom FK name
        columnNames: ['createByUserId'],
        referencedColumnNames: ['id'],
        referencedTableName: 'users',
        onDelete: 'CASCADE',
        onUpdate: 'NO ACTION',
      })
    );
  }
...
```
3. Run CLI `typeorm migration:generate -n MyNewMigration`
4. A new migration is created with the following code:

```typescript
import {MigrationInterface, QueryRunner} from "typeorm";

export class MyNewMigration1624608379416 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `companies` DROP FOREIGN KEY `FK_companies_users_id`");
        await queryRunner.query("ALTER TABLE `companies` ADD CONSTRAINT `FK_fd4de3c61697c124dfb0f37b159` FOREIGN KEY (`createByUserId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `companies` DROP FOREIGN KEY `FK_fd4de3c61697c124dfb0f37b159`");
        await queryRunner.query("ALTER TABLE `companies` ADD CONSTRAINT `FK_companies_users_id` FOREIGN KEY (`createByUserId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   WSL Ubuntu       |
| Node.js version     | v14.17.1 |
| Typescript version  | v4.2.4 | 
| TypeORM version     | v0.2.34 |

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [X] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [X] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
If you want this to work with the automatic migration generation you'll need to set up the naming strategy - and there's a separate issue for that already.

As such, this is working as intended.  We don't have any way of tying that foreign key back in the automated schema builder
