### ISSUE TITLE
failure when using composite camelCased table name in @Entity() decorator 

### ISSUE THREAD

**Issue by Goldziher** [typeorm/typeorm#7808]
## Issue Description

I am migrating a large legacy database which has some weird table naming conventions. When I declare an entity like this:

```
@Entity('bbl_coachesComment')
export class LegacyCoachComment extends BaseEntity {...}
```

and I run my tests, which use synchronize(), the table "bbl_coachesComment" is created correctly, but then there is a failure because typeorm apparently is apparently using all lowercase:

```
    query failed: CREATE TABLE `bbl_coachesComment` (`lastModifiedDate` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `id` int NOT NULL, `team_id` int NOT NULL, `game_id` int NOT NULL, `coach_id` int NOT NULL, `commentText` text NOT NULL, INDEX `IDX_4ee3e6a7ce4ba34b92ce38ed93` (`lastModifiedDate`), PRIMARY KEY (`id`)) ENGINE=InnoDB

      at Function.Object.<anonymous>.PlatformTools.logError (packages/backend/src/platform/PlatformTools.ts:231:17)

  console.log
    error: Error: ER_NO_SUCH_TABLE: Table 'bbl_legacy_test.bbl_coachescomment' doesn't exist
```

If I change the name of the table like so: "bbl_coaches_comment", everything works correctly.
### Expected Behavior

TypeORM uses whatever table name given to it, as long as it is valid.

### Actual Behavior

```
// include the output in code tags like these!
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | vX.Y.ZZZ | 
| Typescript version  | vX.Y.ZZZ | 
| TypeORM version     | vX.Y.ZZZ | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Can you include the query that is attempted that fails because it's lowercase?  According to the log you presented, the failing query is:

```
    query failed: CREATE TABLE `bbl_coachesComment` (`lastModifiedDate` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `id` int NOT NULL, `team_id` int NOT NULL, `game_id` int NOT NULL, `coach_id` int NOT NULL, `commentText` text NOT NULL, INDEX `IDX_4ee3e6a7ce4ba34b92ce38ed93` (`lastModifiedDate`), PRIMARY KEY (`id`)) ENGINE=InnoDB
```

In which case it's the correct case & is working as expected.

**Comment by pleerock** [comment]
@imnotjames yes, I was thinking the same - error has a proper table name. I'm going to close this issue since there is no response in 22 days. @Goldziher if you still have this issue - create a new issue, provide more details and format it properly. Thanks.

**Comment by Goldziher** [comment]
Hi guys. Sorry for not being available. This is still failing - as I mentioned in the OP - when the name is in camelCase it fails, and I have to use lower case.

**Comment by imnotjames** [comment]
I have tested this with MySQL and cannot replicate.
