### ISSUE TITLE
Document CLI options and commands

### ISSUE THREAD

**Issue by crutchcorn** [typeorm/typeorm#781]
There is currently no portion of the [documentation](https://typeorm.github.io/) that covers the CLI tool or the configuration of this tool.

**Comment by crutchcorn** [comment]
[Seems like there was already an outline planned](https://github.com/typeorm/typeorm/blob/master/docs/using-cli.md). That being said, there was not much work done into it and I feel should be expanded out

**Comment by pleerock** [comment]
right something to be done

**Comment by pleerock** [comment]
I updated CLI docs. It will be improved more in the future.
