### ISSUE TITLE
v0.2.33 breaks Postgres jsonb compatibility with sync

### ISSUE THREAD

**Issue by jastend** [typeorm/typeorm#7810]
## Issue Description

I recently upgraded my typeorm dependency inside a NestJS application from version 0.2.31 to 0.2.34. Starting with version 0.2.33 (also occuring in v0.2.34) on bootup I receive the following errors:

```
[Nest] 7488   - 06/29/2021, 10:15:02 AM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +94ms
TypeError: Cannot read property 'substring' of undefined
    at PostgresDriver.defaultEqual (/workspace/node_modules/typeorm/driver/postgres/PostgresDriver.js:789:63)
    at /workspace/node_modules/typeorm/driver/postgres/PostgresDriver.js:913:56
    at Array.filter (<anonymous>)
    at PostgresDriver.findChangedColumns (/workspace/node_modules/typeorm/driver/postgres/PostgresDriver.js:902:32)
    at /workspace/node_modules/typeorm/schema-builder/RdbmsSchemaBuilder.js:1111:84
    at step (/workspace/node_modules/tslib/tslib.js:143:27)
    at Object.next (/workspace/node_modules/tslib/tslib.js:124:57)
    at step (/workspace/node_modules/tslib/tslib.js:128:143)
    at Object.next (/workspace/node_modules/tslib/tslib.js:124:57)
    at /workspace/node_modules/tslib/tslib.js:117:75
[Nest] 7488   - 06/29/2021, 10:15:02 AM   [ExceptionHandler] Cannot read property 'substring' of undefined +0ms
TypeError: Cannot read property 'substring' of undefined
    at PostgresDriver.defaultEqual (/workspace/node_modules/typeorm/driver/postgres/PostgresDriver.js:789:63)
    at /workspace/node_modules/typeorm/driver/postgres/PostgresDriver.js:913:56
    at Array.filter (<anonymous>)
    at PostgresDriver.findChangedColumns (/workspace/node_modules/typeorm/driver/postgres/PostgresDriver.js:902:32)
    at /workspace/node_modules/typeorm/schema-builder/RdbmsSchemaBuilder.js:1111:84
    at step (/workspace/node_modules/tslib/tslib.js:143:27)
    at Object.next (/workspace/node_modules/tslib/tslib.js:124:57)
    at step (/workspace/node_modules/tslib/tslib.js:128:143)
    at Object.next (/workspace/node_modules/tslib/tslib.js:124:57)
    at /workspace/node_modules/tslib/tslib.js:117:75
```

After some debugging, I pinned this down to having having `syncrhonize: true` turned on in the TypeORM settings (for dev purposes) and having a column with type `jsonb`

```
@Entity()
export class Job {
    @ApiProperty()
    @Column({ type: 'jsonb', default: null })
    parameters: () => [];
}
```

### Expected Behavior

On application boot, have TypeORM sync the Postgres database tables with the provided entities that contain a jsonb column.

### Actual Behavior

Sync will fail when evaluating the following method:

```
/**
* Compares "default" value of the column.
* Postgres sorts json values before it is saved, so in that case a deep comparison has to be performed to see if has changed.
*/
PostgresDriver.prototype.defaultEqual = function (columnMetadata, tableColumn) {
    if (Array("json", "jsonb").indexOf(columnMetadata.type) >= 0
        && typeof columnMetadata.default !== "function"
        && columnMetadata.default !== undefined) {
        var columnDefault = columnMetadata.default;
        if (typeof columnDefault !== "object") {
            columnDefault = JSON.parse(columnMetadata.default);
        }
        var tableDefault = JSON.parse(tableColumn.default.substring(1, tableColumn.default.length - 1));
        return OrmUtils_1.OrmUtils.deepCompare(columnDefault, tableDefault);
    }
    else {
        var columnDefault = this.lowerDefaultValueIfNecessary(this.normalizeDefault(columnMetadata));
        return (columnDefault === tableColumn.default);
    }
};
```

### Steps to Reproduce

1. Add an entity with a column that has the following properties: `@Column({ type: 'jsonb', default: null })`
2. Run the TypeORM sync

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Ubuntu 20.04       |
| Node.js version     | v14.17.0 | 
| Typescript version  | v4.3.4 | 
| TypeORM version     | v0.2.33 | 
| NestJS version     | v7.6.18 | 
| NestJS TypeORM version     | v7.1.5 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Caused by ##7650
