### ISSUE TITLE
Schema:sync/log doesn't work for table change (add/remove/change field)

### ISSUE THREAD

**Issue by Tony-Truand** [typeorm/typeorm#7812]
## Issue Description
0.2.33 doesn't sync/log table alternation but does creation

### Expected Behavior

0.2.32 does work like it should

### Actual Behavior

Downloaded the actual typescript sample.
npm i
npm i mssql // Server is mssql
updating ormconfig to match database 
- needed to add   
  "options": {
    "trustServerCertificate": true
  },  
- changing tables name for Post / Category to avoid altering my actual database

```
{
  "type": "mssql",
  "host": "hostname",
  "database": "dbname",
  "username": "username",
  "password": "password",
  "domain": "domain",
  "schema": "dbo",
  "synchronize": true,
  "logging": false,
  "options": {
    "trustServerCertificate": true
  },  
  "entities": [
    "src/entity/*.js"
  ],
  "subscribers": [
    "src/subscriber/*.js"
  ],
  "migrations": [
    "src/migration/*.js"
  ],
  "cli": {
    "entitiesDir": "src/entity",
    "migrationsDir": "src/migration",
    "subscribersDir": "src/subscriber"
  }
}
```
```typescript
@Entity({
    name: 'sample_cate',
})

@Entity({
    name: 'sample_post',
})
```

### Steps to Reproduce

1. npm run typeorm schema:sync ✔️
2. add column "newField" to table Category
3. npm run typeorm schema:log  ❌

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Window    | v10.0.17763.1935    |
| Node.js version     | v15.8.0 | 
| Typescript version  | v3.9.10 | 
| TypeORM version     | v0.2.34 | 
| MSSQL version | 7.1.3 |

### Additional Context

mssql driver version needs options configuration about trustServerCertificate
```
  "options": {
    "trustServerCertificate": true
  },  
```

![2021-06-29 16_40_10-Category ts - typescript-example - Visual Studio Code](https://user-images.githubusercontent.com/7480192/123820579-fa700100-d8fa-11eb-9469-70a30646e404.png)

1. npm run typeorm "schema:sync" =>✔️
2. adding new field =>✔️
3. asking to show log or sync =>❌

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [x] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
This should be fixed in the next release.  This can be confirmed in the latest dev build - `0.2.38-dev.22676a0`
