### ISSUE TITLE
queryBuilder fails when using LENGTH keyword in orderBy with leftJoin and take

### ISSUE THREAD

**Issue by mimoid-prog** [typeorm/typeorm#7822]
## Issue Description
When you use LENGTH keyword inside `orderBy` method with `leftJoin` and `take` methods then it throws an error:
`"LENGTH(u" alias was not found. Maybe you forgot to join it?`
This is some weird behaviour that I cannot explain.

### Expected Behavior
To not throw an error and to return results.

### Actual Behavior

```
    const sortedUsers = userRepo
      .createQueryBuilder("u")
      .leftJoinAndSelect("u.permissions", "p")
      .take(2)
      .orderBy("LENGTH(u.email)", "DESC")
      .getMany();
```

When you only remove `.leftJoinAndSelect("u.permissions", "p")` then it works.
When you only remove `.take(2)` then it works.
Also when you remove only `LENGTH` keyword then it works with both of them.
But when you use both of them and `LENGTH` keyword as in the example above then it throws an error:
`"LENGTH(u" alias was not found. Maybe you forgot to join it?`

### Steps to reproduce
https://github.com/mimoid-prog/typeorm-length-bug
Install dependencies and npm start

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows 10       |
| Node.js version     | v14.16.0 | 
| Typescript version  | v4.1.3 | 
| TypeORM version     | v0.2.31 | 

### Relevant Database Driver(s)

- [x] `postgres`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
The alias replacement is not that smart - it searches for the `.` and splits.

To better support this.. hmm... Not sure.

Perhaps a better regex to search for fields but.. not sure how to not get false positives on that.

**Comment by mimoid-prog** [comment]
@imnotjames But why is the alias working correctly when I don't use `take` or `leftJoin`? Only the combination of those two throws the error

**Comment by imnotjames** [comment]
> @imnotjames But why is the alias working correctly when I don't use `take` or `leftJoin`? Only the combination of those two throws the error

What does the TS look like with that?

**Comment by mimoid-prog** [comment]
@imnotjames You mean how the query looks like? Exactly the same as the code example in my main post. But when I remove `.take(2)` or `.leftJoinAndSelect("u.permissions", "p")` from the query, then it starts to work. Results are sorted by it's length and the error is not thrown.
It looks like typeorm doesn't understand the `LENGTH(u.email)` alias only when you use `take` and `leftJoin` together, but when you use only one of them then alias works.

**Comment by imnotjames** [comment]
So to clarify, it's:

```
    const sortedUsers = userRepo
      .createQueryBuilder("u")
      .orderBy("LENGTH(u.email)", "DESC")
      .getMany();
```

That works, while the original bit doesn't.  Right?

**Comment by mimoid-prog** [comment]
@imnotjames Exactly. I created a [simple repo with examples](https://github.com/mimoid-prog/typeorm-length-bug/blob/main/src/app.ts) demonstrating this issue

**Comment by juliengbt** [comment]
Hi!

I've gotten the error some weeks ago and I found a workaround if you're interested : 

```typescript
const users4 = await userRepo
    .createQueryBuilder("u")
    .addSelect("LENGTH(u.name)", "nameLength")
    .leftJoinAndSelect("u.pets", "p")
    .orderBy("nameLength", "DESC")
    .take(2)
    .getMany()
```

Using LENGTH in addSelect and ordering by the alias doesn't throw any error.

**Comment by mimoid-prog** [comment]
@juliengbt Thanks, your workaround works! But I needed to change the alias name because I got another error  `column distinctAlias.namelength does not exist`. It looks like Typeorm doesn't like camel case either 😄
