### ISSUE TITLE
MigrationsRun in createConnection gives: unexpected token 'export'

### ISSUE THREAD

**Issue by Pixelatex** [typeorm/typeorm#7827]
## Issue Description

My create connection has the "migrationsRun" set to true because I want my migrations to run every time the app starts.
 Yet it errors out.

The culprit is this line: 

### Expected Behavior

The migrations should run without errros.

### Actual Behavior

My create connection has the "migrationsRun" set to true because I want my migrations to run every time the app starts.
 Yet it errors out.
However this throws an error `SyntaxError: Unexpected token 'export'`

Coming from `node_modules/typeorm/browser/migration/Migration.js:16` 

The culprit is this line:  `export { Migration };`

### Steps to Reproduce

1. Normal setup
2.

```typescript
    import { createConnection } from 'typeorm'

    await createConnection({
      type: 'mssql',
      host: DATABASE_HOST,
      port: 1433,
      username: DATABASE_USER,
      password: DATABASE_PASS,
      database: DATABASE_NAME,
      entities: [__dirname + '/entity/*.{ts,js}'],
      synchronize: false,
      stream: true,
      options: {
        encrypt: true,
      },
      logging: true,
      migrations: ['./**/migration/*.{ts,js}'],
      migrationsRun: true,
    })
      .then(() => {
        console.log('DB connection has been established successfully.')
      })
      .catch((error) => {
        console.error('Unable to connect to the database:', error)
      })
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v15.14.0 | 
| Typescript version  | v4.2.3 |
| TypeORM version     | v0.2.32 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [*] `mssql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [*] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
This seems like an issue with your environment, not TypeORM.

We don't interpret your code - all we do is use `require`.

**Comment by Pixelatex** [comment]
Yeah, seems like all it needed was to run node as node -r esm to make it work!
