### ISSUE TITLE
[Feat] Start using GitFlow workflow for version control

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#784]
Consider start using the GitFlow workflow for versioning?

Here's a few things it would solve:

- It would keep master at a release version, meaning people could actually install from git with npm in case they wanted to test the next release without waiting for the npm upload.
- It would auto-tag your versions (depending on the tool you use for gitflow, GitKraken works great and when finishing a release it will tag your release/hotfix).
- Tags are important to differentiate where the previous version ends and the next version begins, for example, since there's no tags for alpha versions in this repo, i cannot make a diff between 2 alpha versions to check what changed, and CHANGELOG.md don't have alpha version changes.
- Branching and merging guidelines of GitFlow methodology helps keep versions under control when working with big teams, and this repo surely has many contributors.

I do it all the time at work, it's becoming a version control standard in my humble opinion, and it makes the version history more readable.

Any thoughts about this?

**Comment by pleerock** [comment]
Now, when 0.1.0 is released we'll start doing following: 

* `master` will keep things in current release version, e.g. `0.1.x`
* `0.2.0` changes will go into separate branch called `0.2.0`
* to install `0.2.0-alpha.x` you'll need to do `npm i typeorm@next`

**Comment by luchillo17** [comment]
So branch `0.2.0` will be next release branch?, that's somewhat an improvement, but it's still not GitFlow methodology.

According to GitFlow, you should keep all releases on `master`, and rely on git tags to mark each release final commit, all changes towards next release are made in `develop` branch, hopefully through feature branches or bugfix ones.

When a release is almost ready you create a `release` branch & polish the new version in it, then merge that branch in both `develop` & `master`, while tagging the master side as the release version number it represents.

This is still a simplified explanation, but it's a start, do you think it's too much hassle? Maybe this explanation with graphics will help you get the hang of it: https://datasift.github.io/gitflow/IntroducingGitFlow.html

**Comment by pleerock** [comment]
We can rename `0.2.0` into `development` or `next`

**Comment by luchillo17** [comment]
Develop is good, then when the repo is ready for next release, be it `0.1.2` or `0.2.0` you create a release branch (most of the time named `release/x.x.x` with `x` being a number) where to polish before pushing to master.

Btw saw you put the tags to good use, nice.
