### ISSUE TITLE
Running migrations inside a docker container fails

### ISSUE THREAD

**Issue by Pixelatex** [typeorm/typeorm#7840]
## Issue Description

Setting  "migrationsRun" as true in your config works to run migrations on startup.. but not in a docker environment.

### Expected Behavior

Migrations should run... but they don't!

### Actual Behavior
The following error occurs:

```
Unable to connect to the database: TypeError: Cannot read property 'driver' of undefined

at new MigrationExecutor (/app/node_modules/typeorm/browser/migration/MigrationExecutor.js:27:39)

at class_1.get (/app/node_modules/typeorm/container.js:15:51)

at Object.getFromContainer (/app/node_modules/typeorm/container.js:49:29)

at /app/node_modules/typeorm/connection/ConnectionMetadataBuilder.js:31:87

at Array.map (<anonymous>)

at ConnectionMetadataBuilder.buildMigrations (/app/node_modules/typeorm/connection/ConnectionMetadataBuilder.js:31:36)

at Connection.buildMetadatas (/app/node_modules/typeorm/connection/Connection.js:518:52)

at Connection.<anonymous> (/app/node_modules/typeorm/connection/Connection.js:128:30)

at step (/app/node_modules/tslib/tslib.js:143:27)

at Object.next (/app/node_modules/tslib/tslib.js:124:57)
```

--> Looking at the typeorm file in question, the variable 'connection' is actually undefined. Indicating that somehow, the global connection variable is lost when running in docker.

### Steps to Reproduce
1. Standard typeorm setup
2. Create some migrations to be run
3. set migrations: [.. path to migrations] in the config file
4. set migrationsRun to true in the config file
5. Run your code as a docker and see it fail

Included my dockerfile for reference:

```
###
# Build stage
###
FROM node:16-alpine AS build
RUN mkdir -p /app
ENV PORT 80

WORKDIR /app

COPY package.json yarn.lock /app/
RUN yarn

COPY . .
RUN yarn build
EXPOSE 80
###
# Exec Stage
###
FROM node:16-alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY --from=build /app/dist ./dist
CMD ["yarn", "start"]
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v16 | 
| Typescript version  | v4.23 | 
| TypeORM version     | v0.2.32| 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [*]  `mssql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [*] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
This doesn't look like an issue with typeorm.  Instead, it seems to be an issue with your environment.  That makes this a support request.

---

For questions or general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
