### ISSUE TITLE
Docs: Add examples of queries executed in Find Options - Basic Options.

### ISSUE THREAD

**Issue by juanoliveira82** [typeorm/typeorm#7843]
### What was unclear or otherwise insufficient?

In the "Find Options" documentation, the [Advanced Options](https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#advanced-options) have examples of which query will be performed by TypeORM, but the [Basic Options](https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#basic-options) don't have these examples.

[Find Options documentation](https://github.com/typeorm/typeorm/blob/master/docs/find-options.md).

### Recommended Fix

I think these examples would be a great help in understanding what these operations do. Therefore, they could be added in the Basic Options section.

I had a hard time understanding how _relations_ and _join_ work, and maybe other people reading the documentation have some questions too.

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by pleerock** [comment]
We can improve documentation by adding query examples. Feel free to contribute!

**Comment by Harukisatoh** [comment]
I created this PR #7994  with the proposed changes. Let me know if there is something wrong with the examples or something that could be improved.

**Comment by pleerock** [comment]
@Harukisatoh thanks!
