### ISSUE TITLE
Analog $with in yii2 

### ISSUE THREAD

**Issue by golubvladimir** [typeorm/typeorm#7846]
### The Problem

Make anolog function $with in yii2, which makes two query without join in sql.
Make requests faster.

https://www.yiiframework.com/doc/api/2.0/yii-db-activequerytrait#with()-detail

**Comment by imnotjames** [comment]
As far as I understand it, it's fetching relations to the query.

We have that feature - `relations` in `findoptions` and the `leftJoinAndSelect` with the Query builder.

**Comment by golubvladimir** [comment]
@imnotjames 

Does this do two queries too?

[https://stackoverflow.com/questions/25600048/what-is-the-difference-between-with-and-joinwith-in-yii2-and-when-to-use-them](https://stackoverflow.com/questions/25600048/what-is-the-difference-between-with-and-joinwith-in-yii2-and-when-to-use-them)

**Comment by golubvladimir** [comment]
@imnotjames 

```
    const query = this.articles
        .createQueryBuilder('art')
        .select('title')
        .leftJoinAndSelect(
            AuthorsEntity,
            'aut',
            'aut.id = art.author_id'
        ).getQuery();

    return query;
```

transform to 

```
SELECT `aut`.`id` AS `aut_id`, `aut`.`name` AS `aut_name`, title FROM `articles` `art` LEFT JOIN `authors` `aut` ON `aut`.`id` = `art`.`author_id`
```
