### ISSUE TITLE
entity path help. Not syncing entities

### ISSUE THREAD

**Issue by kylesmyth** [typeorm/typeorm#786]
As the title says. Having problems getting this to work. I have tried both using the ormconfig, manually creating the options object and the typeorm schema:sync utility.

I'm assuming that my path is incorrect. Is there any way to debug this?

> 

ormconfig.json
````
[
    {
      "name": "default",
        "type": "mysql",
        "host": "localhost",
        "port": 3306,
        "username": "root",
        "password": "xxx",
      "database": "xxx",
      "autoSchemaSync": true,
      "entities": [
        "dist/models/*.js"
      ],
      "cli": {
        "entitiesDir": "dist/models"
      }
    }
  ]
````
tsconfig.json
````
{
    "compilerOptions": {
      "target": "es6",
      "module": "commonjs",
      "outDir": "dist",
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true
    },
    "include": [
      "src/**/*.ts"
    ],
    "exclude": [
      "node_modules"
    ]
  }
````

**Comment by pleerock** [comment]
But how I can help you? Just make sure `"dist/models/*.js"` is correct and files really exist

**Comment by kylesmyth** [comment]
The path appears to be correct and there is an entity there. 
Is there a way to debug the sync? The only message I receive is:
"Schema syncronization finished successfully."
Am I able to see what it has tried / sync?

**Comment by pleerock** [comment]
maybe you'll try to checkout [this demo repo](https://github.com/typeorm/typescript-example) and try from scratch?

**Comment by mypmj** [comment]
@kylesmyth 
Can you please try  
"entities": [
        Company 
      ],
and remove below "cli" options  
      "cli": {
        "entitiesDir": "dist/models"
      }
I think that your model path is not correct.

**Comment by kylesmyth** [comment]
Thanks for your help guys. I found my issue:

`**export** Class Company {`
