### ISSUE TITLE
Transforming value into undefined does fall back to initial value

### ISSUE THREAD

**Issue by pkuczynski** [typeorm/typeorm#7865]
## Issue Description

Defining transformer which converts `null` into undefined does not seem to work. Example:

```
@Column({
        nullable: true,
        transformer: {
            to: (value: unknown) => value,
            from: (value: unknown) => value === null ? undefined : value
        }
})
data: number
```

### Expected Behavior

When `data` is `null` it should be transformed into `undefined`

### Actual Behavior

`data` remains `null`

### Relevant Database Driver(s)

- [x] `postgres`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by krisalay** [comment]
@pkuczynski This does not seem a bug to me. I tried with the same transformer and the null value get transformed to `undefined`. Whereas if there is no transformer, then `null` is returned.

TypeORM version: 0.2.34
NestJS version: 7.6.15

**Comment by imnotjames** [comment]
I can't replicate either.

If you think this is actually a bug, though, please create a test case that we can add which exhibits the issue.

Once you do, reopen the issue :)
