### ISSUE TITLE
Add json database support

### ISSUE THREAD

**Issue by distributev** [typeorm/typeorm#7866]
## Feature Description

Add low.db database support in addition to the existing databases which are supported.

Initially I opened this in the Strapi's repository but I now believe that it's more suitable to open this here.

### The Problem

Currently many projects use SQLLite during development, prototyping and testing because it is lighter than the alternatives like MySQL, Postgress, Oracle, etc. Your project already supports SQLLite so this is good.

In the "light database" idea even lighter then SQLLite are "plain text" databases, for instance JSON based databases like

https://github.com/typicode/lowdb
https://github.com/typicode/json-server

I believe that, once added, most of these projects will start to use lowdb instead of SQLLite

The benefit would be that, for users which will need this, the database will be stored in a plain json file like a db.json which means it will be easy to add to source control the data also in addition with the app code and the app configurations. Adding to source control data stored in a classical database like MySQL is more difficult.

https://github.com/strapi/strapi/issues/8326

**Comment by imnotjames** [comment]
It doesn't seem like either of those support any sort of SQL - is that the case?

**Comment by sawirricardo** [comment]
any news with this?

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
