### ISSUE TITLE
I don't use createQueryBuilder with Entity, created by EntityManager.create ?

### ISSUE THREAD

**Issue by golubvladimir** [typeorm/typeorm#7874]
### Expected Behavior

I have result of union query. I want to create new entity, insert result to it and use all typeorm functionality.

### Actual Behavior

createQueryBuilder doesn't work.

```
src/app.service.ts:48:15 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(entityTarget: (qb: SelectQueryBuilder<any>) => SelectQueryBuilder<any>, aliasName: string): SelectQueryBuilder<unknown>', gave the following error.
    Argument of type 'TableUnion' is not assignable to parameter of type '(qb: SelectQueryBuilder<any>) => SelectQueryBuilder<any>'.
      Type 'TableUnion' provides no match for the signature '(qb: SelectQueryBuilder<any>): SelectQueryBuilder<any>'.
  Overload 2 of 2, '(entityTarget: EntityTarget<unknown>, aliasName: string): SelectQueryBuilder<unknown>', gave the following error.
    Argument of type 'TableUnion' is not assignable to parameter of type 'EntityTarget<unknown>'.
      Type 'TableUnion' is missing the following properties from type '{ type: unknown; name: string; }': type, name

48         .from(createdEntity, 'cE')
```

### Steps to Reproduce

```typescript
@Injectable({ scope: Scope.REQUEST })
export class AppService {

  constructor(
      @Inject(REQUEST)
      private request: Request,

      @InjectRepository(ArticlesEntity)
      private readonly articles: Repository<ArticlesEntity>,

      @InjectRepository(TagsEntity)
      private readonly tags: Repository<TagsEntity>,

      @InjectRepository(TableUnion)
      private readonly tableUnion: Repository<TableUnion>
  ) {}

  async getHello() {
    const entityManager = getManager();
    const connection = getConnection();

    const tableUn = this.tableUnion.createQueryBuilder('tu')
        .select(['id', 'description'])
        .getQuery();

    const tableTg = this.tags.createQueryBuilder('tg')
        .select(['id', 'name'])
        .getQuery();

    const tags = await entityManager.query(`${ tableUn } UNION ${ tableTg }`);

    const createdEntity = entityManager.create(TableUnion, tags);

    const result = await connection.createQueryBuilder()
        .from(createdEntity, 'cE')
        .getRawMany();

    return result;
  }
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Wndows     |
| Node.js version     | v14.16.1 | 
| Typescript version  | v4.3.5 | 
| TypeORM version     | v0.2.34 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [X] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [X] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
This is a support request rather than a bug report.

For support or questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
