### ISSUE TITLE
 Docs: Use case for migrations?

### ISSUE THREAD

**Issue by bcherny** [typeorm/typeorm#788]
Since entities (ie. `@Entities` in code) are the source of truth, and can be synced to the DB schema with `typeorm schema:sync`, what is the use case for manually running migrations?

Are migrations and `schema:sync` meant to be used together for different use cases? Or is it one or the other, depending on your risk tolerance? Or am I totally missing the point here?

**Comment by pleerock** [comment]
on production you may want more control. Schema sync can simply drop your exist data, in migrations you can write code which prevents it. For example first you copy exist data into new table then delete column with all data.

**Comment by bcherny** [comment]
Thanks for the quick response @pleerock.

Would you avoid using schema sync in production, and stick to just migrations? It would be nice if there there was a "safe" mode for schema sync, which threw on destructive changes and suggested the user create a migration instead.

**Comment by pleerock** [comment]
you can run `typeorm schema:log` to see what sql queries `schema:sync` will execute. On production you can use it before running schema:sync. You run it and check and analyze what sql queries orm will execute. If you are okay with all queries and sure it wont hard your database you run schema:sync. If you aren't okay with changes you can create a migration and write sql code manually to make schema updation as your production needs

**Comment by bcherny** [comment]
Excellent - thanks for the explanation @pleerock. Great work with TypeORM. Scheme syncing (and everything else about it) is a pleasure to use.
