### ISSUE TITLE
Is this support read / write replication ?

### ISSUE THREAD

**Issue by DivXPro** [typeorm/typeorm#789]
Is typeorm support read / write replication ?

**Comment by pleerock** [comment]
Can you explain what read/write replication features you are expecting from typeorm?

**Comment by DivXPro** [comment]
I have 2 instances of database, slave instance sync data from master.
I wish read data from slave instance, and create update on the master.
Just like sequelizejs did

**Comment by pleerock** [comment]
What database are you using?

**Comment by pleerock** [comment]
Added in `0.1.0-alpha.36`. See docs [here](https://github.com/typeorm/typeorm/blob/master/docs/connection.md#replication).

**Comment by govorov** [comment]
@pleerock seems like documentation related replication has been dissapeared. btw, is there master/slave read/write separation for Postgres?

**Comment by pleerock** [comment]
@govorov documentation moved [here](http://typeorm.io/#/multiple-connections/replication).

Replication is supported by mysql, postgres and sql server databases

**Comment by anuj-c-gortnm** [comment]
typeorm postgres master slave replication is not synchronous.
how to solve this issue

**Comment by AndrewSouthpaw** [comment]
@anuj-c-gortnm primary-follower replication for systems like MySQL and Postgres are fundamentally asynchronous. It's not a problem with TypeORM. You can either opt for a DB system that doesn't use replication, or develop ways to [read your writes](https://docs.oracle.com/cd/E17076_05/html/gsg_db_rep/C/rywc.html).

**Comment by Jakhongiirr** [comment]
hi, where is the documentation for replication, can't find it from typeorm.io @pleerock
