### ISSUE TITLE
SQL syntax error occurs by typeorm insert of multiple rows into table for sap (HANA) database

### ISSUE THREAD

**Issue by niels-schmitt** [typeorm/typeorm#7899]
### Expected Behavior

Two new records have been created in table `"<HANA_SCHEMA>"."photo"`.

### Actual Behavior

An error occurs at typeorm database operation. No records have been created on database. Server console output:
```
[Nest] 1032  - 07/13/2021, 8:27:38 AM   ERROR [ExceptionsHandler] sql syntax error: incorrect syntax near ",": line 1 col 48 (at pos 48)
Error: sql syntax error: incorrect syntax near ",": line 1 col 48 (at pos 48)
    at SapQueryRunner.<anonymous> (/home/niels/sap/issues/typeorm-hana-insert-multiple-rows/src/driver/sap/SapQueryRunner.ts:193:53)
    at step (/home/niels/sap/issues/typeorm-hana-insert-multiple-rows/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/niels/sap/issues/typeorm-hana-insert-multiple-rows/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/niels/sap/issues/typeorm-hana-insert-multiple-rows/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Steps to Reproduce

Prepare:
1. Clone repository https://github.com/niels-schmitt/typeorm-hana-insert-multiple-rows.
2. `npm install`
3. Get a running HANA instance, and credentials for user <HANA_USER> with authorization `CREATE ANY` on schema <HANA_SCHEMA>.
4. `cp template.env .env`
5. In file `.env` enter values for: `HANA_HOST`, `HANA_PORT`, `HANA_USER`, `HANA_PASSWORD`, `HANA_SCHEMA`

Reproduce Issue:
```shell
npm run start
```
```shell
curl -w'\n' -X POST -H 'Content-Type: application/json' -d '["Flower","Tree"]' localhost:3000/photos
```
or
```shell
curl -w'\n' -X POST -H 'Content-Type: application/json' -d '["Flower","Tree"]' localhost:3000/photosByQueryBuilder
```

### My Environment

| Dependency          | Version        |
| ---                 | ---            |
| Operating System    | Ubuntu 20.04.2 |
| Node.js version     | v14.17.2       | 
| Typescript version  | @4.3.5         | 
| TypeORM version     | @0.2.34        | 
| @nestjs/core        | @8.0.2         |
| @nestjs/typeorm     | @8.0.1         |
| @sap/hana-client    | @2.9.23        |
| hdb-pool            | @0.1.6         |

### Additional Context

Root cause seems to be that an incorrect SQL is created:
```sql
INSERT INTO "photo"("id", "name") VALUES (?, ?), (?, ?)
```
Correct SQL would be:
```sql
INSERT INTO "photo"("id", "name") VALUES ((?, ?), (?, ?))
```
The executed SQL is logged to the console in case of POST for `/photosByQueryBuilder`.

POST for `/photos` executes
```typescript
await this.photoRepository.manager.insert(Photo, photos);
```
POST for `/photosByQueryBuilder` executes
```typescript
await this.photoRepository
  .createQueryBuilder()
  .insert()
  .into(Photo)
  .values(photos)
  .execute();
```
The issues occurs for both variants.

#### The issue does not occur in case only one record is inserted:
```shell
curl -w'\n' -X POST -H 'Content-Type: application/json' -d '["Flower"]' localhost:3000/photos
```
or
```shell
curl -w'\n' -X POST -H 'Content-Type: application/json' -d '["Tree"]' localhost:3000/photosByQueryBuilder
```
For verification, read all records by
```shell
curl -w'\n' localhost:3000/photos
```

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [x] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

Thanks for your help & kind regards
Niels Schmitt

**Comment by imnotjames** [comment]
Just to clarify - that's not standard SQL, is it?

Can you link to the SAP Hana documentation that describes this syntax

**Comment by imnotjames** [comment]
[Here's the SAP Hana documentation for Insert for reference](https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/20f7f70975191014a76da70c9181720e.html).  It does not describe this syntax.

If that's the case then we need to disable multiple-value inserts for SAP Hana.

**Comment by niels-schmitt** [comment]
You are right. Since SQL-92 the standard syntax is:
```sql
INSERT INTO "photo"("id", "name") VALUES (?, ?), (?, ?)
```
For reference check following Sections in http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt:
- 7.2 ` <table value constructor>` (p. 176)
- 7.10 `<query expression>` (p. 196)
- 13.8 `<insert statement>` (p. 388)

This syntax seems not to be supported by SAP HANA according to latest SAP HANA SQL Reference Guide for SAP HANA Platform [2.0 SPS 05](https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.05/en-US/20f7f70975191014a76da70c9181720e.html), and SAP HANA Cloud, SAP HANA Database SQL Reference Guide [QRC 2/2021](https://help.sap.com/viewer/c1d3f60099654ecfb3fe36ac93c121bb/2021_2_QRC/en-US/20f7f70975191014a76da70c9181720e.html). As well from my understanding, HANA seems not to support any standard-deviating syntax based on the VALUES keyword that would help here. **Particularly, my proposal in Additional Context of this Issue does not work.** (Somehow I tricked myself, sorry for that.)

However, following syntax should have equivalent semantic, and is actually supported:
```sql
INSERT INTO "photo"("id", "name")
SELECT ?, ? FROM dummy UNION ALL
SELECT ?, ? FROM dummy;
```
Concrete example:
```sql
INSERT INTO "photo"("id", "name")
SELECT '1993a3eb-6664-4676-b759-304c9cac7201', 'Flower' FROM dummy UNION ALL
SELECT '1993a3eb-6664-4676-b759-304c9cac7202', 'Tree' FROM dummy UNION ALL
SELECT '1993a3eb-6664-4676-b759-304c9cac7203', 'Forest' FROM dummy;
```

I cannot judge, whether this makes sense to be generated by typeorm in case of the mentioned database operations:
```typescript
await this.photoRepository.manager.insert(Photo, photos);
```
```typescript
await this.photoRepository
  .createQueryBuilder()
  .insert()
  .into(Photo)
  .values(photos)
  .execute();
```

**Comment by imnotjames** [comment]
We do something similar for Oracle.

I think that's possible for Hana.

**Comment by niels-schmitt** [comment]
Hi James,
Thank you, this is great to hear!!
We are looking forward to a solution and will definitely use it.
Kind regards,
Niels

**Comment by pleerock** [comment]
Looks like a nice feature to implement. This is opened for contributions!

**Comment by michal-majer** [comment]
The issue occurs again.
Values expression should be the same as for oracle.

Line 459 should modified as follows
`        // add VALUES expression
        if (valuesExpression) {
            if (
                (this.connection.driver.options.type === "oracle" || this.connection.driver.options.type === "sap") &&
                this.getValueSets().length > 1
            ) {
                query += ` ${valuesExpression}`
            } else {
                query += ` VALUES ${valuesExpression}`
            }`

**Comment by philipphaeusle** [comment]
Yes, i can confirm.
Not working anymore since v0.3.0
