### ISSUE TITLE
Default enum value not being saved in postgres

### ISSUE THREAD

**Issue by nbrady-techempower** [typeorm/typeorm#7900]
## Issue Description

When creating the initial schema, the default value of an enum isn't being saved.

### Expected Behavior

Default value should appear

### Actual Behavior

```
export enum Status {
  Activated = 'activated',
  Deactivated = 'deactivated'
}

...

  @Column({
    type: 'enum',
    enum: Status,
    default: Status.Activated
  })
  status: Status;
```

The status field is created with the Status user type, but nothing appears in the default value field.
### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.16-alpine | 
| Typescript version  | v4.2.3 | 
| TypeORM version     | v0.2.34 | 
| NestJS version     | v7.6.15 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by AlexMesser** [comment]
We have a test confirming this functionality is working: [entity](https://github.com/typeorm/typeorm/blob/ad0262a116e5366b562e70a1bbc60246add78d83/test/github-issues/7647/entity/TaskNotification.ts#L16) and [test](https://github.com/typeorm/typeorm/blob/ad0262a116e5366b562e70a1bbc60246add78d83/test/github-issues/7647/issue-7647.ts#L22). Here is the output generated by this test:

```sql
query: START TRANSACTION
query: SELECT * FROM current_schema()
query: SELECT * FROM current_database()
query: SELECT "table_schema", "table_name" FROM "information_schema"."tables" WHERE ("table_schema" = 'public' AND "table_name" = 'taskNotifications')
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'typeorm_metadata'
query: SELECT * FROM current_schema()
query: SELECT "n"."nspname", "t"."typname" FROM "pg_type" "t" INNER JOIN "pg_namespace" "n" ON "n"."oid" = "t"."typnamespace" WHERE "n"."nspname" = current_schema() AND "t"."typname" = 'taskNotifications_type_enum'
query: CREATE TYPE "taskNotifications_type_enum" AS ENUM('activated', 'deactivated')
query: CREATE TABLE "taskNotifications" ("id" integer NOT NULL, "type" "taskNotifications_type_enum" NOT NULL DEFAULT 'activated', CONSTRAINT "PK_bf03149248aee7c64532028321e" PRIMARY KEY ("id"))
query: COMMIT
```

As you can see `default` is being set. Can you please provide more info on how to reproduce your issue or submit a PR with a failing test confirming your issue.
