### ISSUE TITLE
Join with column named by AS

### ISSUE THREAD

**Issue by golubvladimir** [typeorm/typeorm#7904]
## Issue Description

I have column name by AS - `.addSelect('82 AS author_id')`
I want to use it in leftJoin

### Expected Behavior

It will work

### Actual Behavior

I have error: 
`ER_BAD_FIELD_ERROR: Unknown column 'author_id' in 'on clause'`

### Steps to Reproduce

```typescript
        let query2 = this.AnalyticsER
          .createQueryBuilder('a')
          .addSelect('82 AS author_id')
          .leftJoin(
            newsCategoryEntity,
            'newsCategory',
            'newsCategory.id = a.author_id'
          )
```
### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [x] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
This is a MySQL problem, not a TypeORM problem.

You'll need to instead do

```
        let query2 = this.AnalyticsER
          .createQueryBuilder('a')
          .addSelect('82 AS author_id')
          .leftJoin(
            newsCategoryEntity,
            'newsCategory',
            'newsCategory.id = a.author_id'
          )
```

Or

```
        let query2 = this.AnalyticsER
          .createQueryBuilder('a')
          .setParameter('author_id', 82)
          .addSelect(':author_id AS author_id')
          .leftJoin(
            newsCategoryEntity,
            'newsCategory',
            'newsCategory.id = :author_id'
          )
```

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
