### ISSUE TITLE
Add support for mongodb driver v4

### ISSUE THREAD

**Issue by ferenckv** [typeorm/typeorm#7907]
## Issue Description
Exactly in [this commit](https://github.com/mongodb/node-mongodb-native/commit/a2d78b22b28ae649fa2c4e28294a3a03c446373e#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L2) mongodb stopped exporting a Cursor object. 

Because of that, every reference to `ParentCursor.Prototype` in `MongoEntityManager ` ([like here](https://github.com/typeorm/typeorm/blob/master/src/entity-manager/MongoEntityManager.ts#L691)) is failing with error "Cannot read property 'prototype' of undefined".

### Expected Behavior
No error expected.

### Actual Behavior
Error "Cannot read property 'prototype' of undefined"

```
TypeError: Cannot read property 'prototype' of undefined
    at FindCursor.cursor.toArray (/entity-manager/MongoEntityManager.ts:679:37)
    at MongoEntityManager.<anonymous> (/entity-manager/MongoEntityManager.ts:97:23)
    at step (/node_modules/tslib/tslib.js:143:27)
    at Object.next (/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Steps to Reproduce

1. Add typeorm dependency
2. Add mongodb v4 dependency.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Ubuntu 18.04 on wsl2  |
| Node.js version     | v14.17.0 | 
| Typescript version  | v4.0.8 | 
| TypeORM version     | v0.2.34 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Currently, TypeORM is only compatible with mongo node v3.

**Comment by pleerock** [comment]
Looks like we need to upgrade dependency and fix all related issues. This issue is opened for contributions!

**Comment by imnotjames** [comment]
> Looks like we need to upgrade dependency and fix all related issues. This issue is opened for contributions!

The API has changed enough that it will cause breakages downstream.  For now we should pin it to 3 in the peer, I think.

**Comment by dvantage** [comment]
Guys, a lot of time has passed since the release of the 4th version of the driver, full support is needed

**Comment by MatheusMeloAntiquera** [comment]
> Guys, a lot of time has passed since the release of the 4th version of the driver, full support is needed

I will try to fix my PR soon

**Comment by arnabrahman** [comment]
This version update is a necessity. Mongodb is force migrating to v5 in mid feb 2022.

**Comment by Shayan-To** [comment]
Any updates on this? Any time window when this will be available?

**Comment by mr-short** [comment]
Still no update? I'm starting to think TypeORM isn't the best for MongoDB if it's not well supported

**Comment by MatheusMeloAntiquera** [comment]
> Still no update? I'm starting to think TypeORM isn't the best for MongoDB if it's not well supported

I'll try to finish this weekend, I hope this time work it 🤞

**Comment by MatheusMeloAntiquera** [comment]
A new pull request was created, waiting for the someone review's https://github.com/typeorm/typeorm/pull/9450

**Comment by nash-md** [comment]
Is there any update on this?

**Comment by nathanmacfarlane** [comment]
Any updates?

**Comment by RamanSB** [comment]
Come on guys, this is really bad.

I'm using MongoDB in my NodeJS project, Atlas allows v4^ only, Type ORM doesn't support that version.

**Comment by joker349** [comment]
People want to use MongoDb so they are not restricted with type-checking of SQL Db and then they search for schema validation solution to implement in code - something baked right into SQL Db. How funny 😂

**Comment by andynunes** [comment]
> People want to use MongoDb so they are not restricted with type-checking of SQL Db and then they search for schema validation solution to implement in code - something baked right into SQL Db. How funny 😂

If you think that's the only or main reason people want to use MongoDB, then you're simply uninformed.
