### ISSUE TITLE
Please add repository find option order by RANDOM()

### ISSUE THREAD

**Issue by nanotexnolagiya** [typeorm/typeorm#7912]
### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by krisalay** [comment]
@nanotexnolagiya Can u plz describe this new feature in few sentences?

**Comment by pleerock** [comment]
We need a good proposal for this feature request including all different possible scenarios for order-by in find options. Closing until someone provide a properly formatted and described proposal.

**Comment by John-H-Smith** [comment]
How to use it?

**Comment by John-H-Smith** [comment]
@pleerock  How to use it?
