### ISSUE TITLE
typeorm custom repository does not work “Cannot read property 'findOne' of undefined” when using extends Repository<>

### ISSUE THREAD

**Issue by orlandoji** [typeorm/typeorm#7920]
I want to use custom repository using extends Repository<>.

When I use custom repository using extends Repository<>, error of "Cannot read property 'findOne' of undefined" is occurred.

custom repository

`@EntityRepository(UserEntity)
export class AuthRepository extends Repository<UserEntity> {
  private user
  findByEmail(email: string) {
   return  this.findOne(email)
  }

}`

**Comment by angeldelacruzdev** [comment]
Sí estás dentro del repositorio sería:

this.find({where:{email: email }}) o this.find({where:{ email }})

**Comment by orlandoji** [comment]
> 
> 
> Sí estás dentro del repositorio sería:
> 
> this.find({where:{email: email }}) o this.find({where:{ email }})

hola sin importar la sintaxis dentro de findOne, el error que marca es ` Cannot read property 'findOne' of undefined` gracias por tomarte el tiempo de responder

**Comment by mimoid-prog** [comment]
@angeldelacruzdev @orlandoji Why the heck are you writing in spanish?

**Comment by pleerock** [comment]
It's not clear from your description what leads to this error. Please submit a PR with a failing test proofing your issue. Closing.

**Comment by angeldelacruzdev** [comment]
@mimoid-prog I imagine how you answered the comment that way you are as a person.
