### ISSUE TITLE
[Question] I have to get host, port, pass etc. from env variables and I really need migrations - is there another way to run migrations without using ormconfig.json?

### ISSUE THREAD

**Issue by rychkog** [typeorm/typeorm#793]
One of the option would be to have a ormconfig.js and not only a json one. In this cause (with .js file) users will have an access to the process.env

**Comment by rychkog** [comment]
One of the option would be to have a ormconfig.js and not only a json one

**Comment by pleerock** [comment]
its supported. See [here](https://github.com/typeorm/typeorm/blob/master/docs/connection.md#loading-from-ormconfigjs).

**Comment by rychkog** [comment]
Thanks, @pleerock! I haven't spotted that location ...

**Comment by pleerock** [comment]
Its a new documentation for latest version. I'll update website documentation soon
