### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by MerlinB** [typeorm/typeorm#7930]
My application requires fixes you have made in one of the recent, yet unreleased commits. Could you create a new release containing the most recent commits?

**Comment by imnotjames** [comment]
We'll release when we release.

We don't have a set schedule for releases at this time.

**Comment by pleerock** [comment]
I can do a release if needed, @imnotjames do you think there is something more we need to merge before next release?

**Comment by MerlinB** [comment]
Thank you, I managed to pack my own release with the relevant commit cherry-picked as a workaround for now.
