### ISSUE TITLE
How to use or modify database?Thank!  entityManager.options.database = 'otherDB';

### ISSUE THREAD

**Issue by luzhihg** [typeorm/typeorm#7937]
const entityManager = getConnection();
entityManager.options.database = 'otherDB';

Error:
How to use or modify database?Thank!

**Comment by pleerock** [comment]
Database is set per connection options. If you want to connect to a different database, you need to create a new connection with new connection options and specify new database name. Depend of what you want to achieve, if you want to execute query against different database, in query builder you can create a query and specify a different database name. 

Please use our slack channel for questions!
