### ISSUE TITLE
 TypeError: Cannot read property 'Database' of undefined

### ISSUE THREAD

**Issue by jotyy** [typeorm/typeorm#7944]
Issue type:

[x] question

Database system/driver:

[ x ] sqljs

TypeORM version:

[ x ] @next

Steps to reproduce or a small repository showing the problem:

createConnection({
  type: "sqljs",
  location: "test", 
  autoSave: true,
  entities: [
      User
  ],
  logging: ['query', 'schema'],
  synchronize: true
})Issue type:

[x] question

Database system/driver:

[ x ] sqljs

TypeORM version:

[ x ] @latest

Steps to reproduce or a small repository showing the problem:

```
createConnection({
  type: "sqljs",
  location: "test", 
  autoSave: true,
  entities: [
      User
  ],
  logging: ['query', 'schema'],
  synchronize: true
})
```

Error stack:
```
Uncaught (in promise) TypeError: Cannot read property 'Database' of undefined
    at SqljsDriver2.<anonymous> (SqljsDriver.ts:251)
    at step (tslib.es6.js:102)
    at Object.next (tslib.es6.js:83)
    at tslib.es6.js:76
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:72)
    at SqljsDriver2.createDatabaseConnectionWithImport (SqljsDriver.ts:249)
    at SqljsDriver2.<anonymous> (SqljsDriver.ts:129)
    at step (tslib.es6.js:102)
    at Object.next (tslib.es6.js:83)
```

I'm using Vite&Electron, so I want to know what should I do to use sql.js like webpack?

**Comment by imnotjames** [comment]
I can't replicate.  Can you create a repository that exhibits this issue?

**Comment by ajmas** [comment]
I am running into the same issues. Looking at the code, it would suggest that `this.sqlite` is undefined, but not sure why.

Looking at this code and the fact I am running in a browser points to `windows.SQL` being undefined, which is indeed the case for me. I just need to see where it should be defined in the first place:

```js
SqljsDriver.prototype.loadDependencies = function () {
        if (PlatformTools.type === "browser") {
            this.sqlite = window.SQL;
        }
        else {
            try {
                this.sqlite = PlatformTools.load("sql.js");
            }
            catch (e) {
                throw new DriverPackageNotInstalledError("sql.js", "sql.js");
            }
        }
    };
```
