### ISSUE TITLE
The mysql database field order is inconsistent with the entity class during the table building

### ISSUE THREAD

**Issue by king-one** [typeorm/typeorm#7947]
**Here is my code**

```
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
import { BaseEntity } from '../base.entity';
@Entity({ name: 'company' })
export class Company extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;
  @Column({ length: 36 })
  name: string;
  @Column({ length: 100 })
  area: string;
  @Column({ length: 36 })
  legal_person: string;
  @Column({ length: 11 })
  mobile: string;
  @Column({ length: 250 })
  profile: string;
}
```

```
export abstract class BaseEntity {
  @CreateDateColumn()
  create_time: Date;
  @UpdateDateColumn()
  update_time: Date;
}
```
**Database screenshot**

![image](https://user-images.githubusercontent.com/20457964/126771390-f33b269c-1ada-48f2-9961-11bab1cd0825.png)

**It looks like there is no sort rule，so it is tired to see tables with eyes.  Can anyone tell me how to set this order ? Thanks!**

**Comment by pleerock** [comment]
Can you please enable `logging: true` in connection options and show initial create table output?

**Comment by king-one** [comment]
> Can you please enable `logging: true` in connection options and show initial create table output?

### I found  the reason
Here is the log when the table created
![image](https://user-images.githubusercontent.com/20457964/126923544-96d3a3e4-e0f3-46cb-b49b-e7c07c87781e.png)

After I  modifying anyone field in my entity class,  it will  drop the field and append new one at last, so  the order of  fields 
is inconsistent with the entity class  most of time
![image](https://user-images.githubusercontent.com/20457964/126923673-e0ccc19e-1fc5-4073-82b6-8a2f8637471b.png)

### My expectations ：
1.Fileds of  baseEntity  is behind of  subclass when create table
2.Modifying options of fields is just modify， the sequence of fields always same as entity class  

I think it will be more friendly， thanks！

**Comment by pleerock** [comment]
TypeORM doesn't control the order of the columns in the database. And it won't because of the trickiness of this issue.
You didn't specify what rdbms you are using, but here is example [answer for postgres](https://stackoverflow.com/a/285740).
