### ISSUE TITLE
@Column decorator overwrites @PrimaryColumn decorator

### ISSUE THREAD

**Issue by TheProgrammer21** [typeorm/typeorm#7958]
## Issue Description

```
@Entity()
export class SiteEditor extends BaseEntity {

  // other code

  @PrimaryColumn()
  @Column({
    length: 20
  })
  editor: string;

}
```

### Expected Behavior
The column "editor" should be a primary key, even if both, @PrimaryColumn and @Column decorator are specified. 

### Actual Behavior

The column "editor" is no primary key when the @Column decorator is added to the property.

### Steps to Reproduce

1. Create an Entity with any property.
2. Add the @PrimaryColumn decorator.
3. Execute the script and look at the result in the database.
4. Add the @Column decorator for the same property.
5. Execute the script and look at the result in the database.

### My Environment

MSSQL driver

| Dependency          | Version  |
| Node.js version     | 14.17.1 | 
| Typescript version  | 4.3.5 | 
| TypeORM version     | 0.2.34 |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | yes|

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

## Solution until fixed:
Add the "primary: true" property to the @Column decorator options:

```
@Entity()
export class SiteEditor extends BaseEntity {

  // other code

  @PrimaryColumn()
  @Column({
    length: 20,
    primary: true
  })
  editor: string;

}
```

**Comment by AlexMesser** [comment]
You must specify either `@PrimaryColumn({ length: 20 })` or `@Column({ length: 20, primary: true })`, but not both.

**Comment by TheProgrammer21** [comment]
> You must specify either `@PrimaryColumn({ length: 20 })` or `@Column({ length: 20, primary: true })`, but not both.

My bad, I did not know that @PrimaryColumn takes those options!
Thanks!
