### ISSUE TITLE
Repository.findOne() cannot select by foreign key with DeepPartial

### ISSUE THREAD

**Issue by jwclark** [typeorm/typeorm#796]
Now that Repository.findOne() requires a deep partial, it's not possible to query on a foreign key. For example, if you were to find a photo with name "my photo" by author with id 1, you could previously make the following query

photoRepository.findOne({ name: "my photo", author: 1 });

Now that findOne expects a deep partial, author must be look like an Author type. So to get it to build, you have to change the query to something like the following:

photoRepository.findOne({ name: "my photo", author: { id: 1 } });

The query tries to find a photo with an author column value of '{ id: 1 }' instead of the actual value in the Photo table, which is '1'

This was reproduced on Postgres running typeorm version 0.1.0-alpha.35

**Comment by pleerock** [comment]
It was working before not be design. It worked before only because column names match (author was called author in the database). Right now column for author is called "authorId" and probably by old way you should do photoRepository.findOne({ name: "my photo", authorId: 1 });

To fix your issue I recommend you to add a new column called "authorId" and it will fix your issue. "authorId" will be automatically picked up by relation since they both have same name

**Comment by llwt** [comment]
@pleerock I just ran into this myself and find it a bit confusing. If the current design is to add a new column for the id of the relation rather than using the relation, what is the reasoning behind using `DeepPartial<Entity>` as the type for `.findOne(conditions?)`?

**Comment by pleerock** [comment]
> If the current design is to add a new column for the id of the relation rather than using the relation, what is the reasoning behind using 

I don't see relation there.. DeepPartial is simply to keep it kinda type-safe. Find method never was suppose to work with database columns. Database columns are known only internally by orm. It was always suppose to work with your entity properties

**Comment by llwt** [comment]
I guess my question is more why `DeepPartial<entity>` instead of just `Partial<Entity>`?

**Comment by pleerock** [comment]
There are lot of deep stuff under the hood...

Right now I think `DeepPartial` is not used somehow, but it probably must be used for embeddded functionality. If lets say you have a column inside embedded class inside entity then your query probably must look like this way:

```ts
find({  counter: { likes: 1 } })
```

But this functionality is not implemented yet. Something we totally need to finish there

**Comment by llwt** [comment]
Thanks for the clarification.

**Comment by snaquaye** [comment]
@pleerock so if i use the `@JoinColumn` decorator to rename the field in the database to say `author`, would I be able to do something like `photoRepository.findOne({ name: "my photo", author: 1 });`.

Thanks

**Comment by pleerock** [comment]
@snaquaye you will still need to use property names instead of database column names in findOne options.
