### ISSUE TITLE
Running tests: DriverPackageNotInstalledError: SAP Hana package has not been found installed. Try to install it: npm install hdb-pool --save

### ISSUE THREAD

**Issue by lusatiro** [typeorm/typeorm#7964]
### Getting error when trying to run tests

`DriverPackageNotInstalledError: SAP Hana package has not been found installed. Try to install it: npm install hdb-pool --save`

The package is there.

### Additional Context

I am running all the databases inside docker.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by imnotjames** [comment]
Do you have a repository which exhibits this?

**Comment by imnotjames** [comment]
You can remove SAP from your ormconfig.

**Comment by imnotjames** [comment]
Also yay for mongo transactions.  Happy to chat about this on slack or elsewhere.
