### ISSUE TITLE
Id column changed not respecting name attribute

### ISSUE THREAD

**Issue by DinnerChoice** [typeorm/typeorm#797]
I am trying to join a table to another table, and in the SQL query "foreign key" is changed incorrectly
```javascript
@Entity() export class contact {
    @PrimaryGeneratedColumn() id: number;
    @Column() first_name: string;
    @OneToMany(type => contact__communication, cc => cc.contact)
     communications: contact__communication[];
}

@Entity() export class contact__communication {
    @PrimaryGeneratedColumn() id: number;
    @Column("int") contact_id: number;
    @Column("int") type_id: number;
    @Column() val: string;

    @ManyToOne(type => contact, c => c.communications)
    contact : contact;
}
````

that will generate a sql string of:  
````SQL
   SELECT
    `contact`.`id` AS `contact_id`,
    `contact`.`first_name` AS `contact_first_name`,
    `cc`.`id` AS `cc_id`,
    `cc`.`contact_id` AS `cc_contact_id`,
    `cc`.`type_id` AS `cc_type_id`,
    `cc`.`val` AS `cc_val`,
    `cc`.`contactId` AS `cc_contactId`               <----  THIS LINE
FROM
    `contact` `contact`
INNER JOIN `contact__communication` `cc` ON
    `cc`.`contactId` = `contact`.`id` AND `cc`.`contactId` = `contact`.`id`
````

The foreign key is converted from "contact_id" to "contactId" .    If I change the line to have a name:
````javascript
    @Column("int", {name: 'contact_id') contact_id: number;
````
there is no effect.   But
````javascript
    @Column("int", {name: 'contact__id') contact_id: number;
````

will change the foreign key to "contact__id".  

Is this behavior a bug?     I could change my scheme to match if required.

**Comment by pleerock** [comment]
sounds like a bug in a naming strategy

**Comment by Ostrzy** [comment]
I looked closer at this issue and I think it is not really a bug. In provided sql both `contact_id` and `contactId` are selected and the reason for that is that `contactId` is guessed from `@ManyToOne(type => contact`.

@DinnerChoice What I think you should do is adding `@JoinColumn({ name: "contact_id" })` just below `@ManyToOne` - it will tell TypeORM that `contact_id` column is the actual foreign key for `contact` relation and it would not have to guess.

**Comment by pleerock** [comment]
@Ostrzy is 100% correct
