### ISSUE TITLE
Add DeleteOptions for delete() method

### ISSUE THREAD

**Issue by michaelsogos** [typeorm/typeorm#7972]
Dear all,

Using version 0.2.34.

Do you think is possible to add a DeleteOptions like RemoveOptions in order to play with chunk size and other options?
In docs you say _"Optional RemoveOptions can be passed as parameter for remove and delete."_ but seems to not be true 😄.

**Comment by pleerock** [comment]
> In docs you say 

copy/paste issue...

> Do you think is possible to add a DeleteOptions like RemoveOptions in order to play with chunk size and other options?

no, DeleteOptions is used for `delete` operation which uses `DeleteQueryBuilder`. Purpose of  `DeleteQueryBuilder` is to build and execute only one query. If you want something more complex, use `remove` method instead.
