### ISSUE TITLE
feat: Adding relations option to findTrees()

### ISSUE THREAD

**Issue by TheProgrammer21** [typeorm/typeorm#7974]
## Feature Description
Adding functionality to load relations in TreeRepositories.

### The Problem
When loading a tree in TypeORM there is no possibility of loading relations of the tree entities. 

### The Solution
Adding a relations option to the findTrees() function like it already exists for find() or findOne() in non TreeRepositories. 

### Considered Alternatives
A workaround would be to manually write raw queries with JOINs and execute those.

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | yes            |
| `aurora-data-api-pg` | yes            |
| `better-sqlite3`     | yes            |
| `cockroachdb`        | yes            |
| `cordova`            | yes            |
| `expo`               | yes            |
| `mongodb`            | yes            |
| `mysql`              | yes            |
| `nativescript`       | yes            |
| `oracle`             | yes            |
| `postgres`           | yes            |
| `react-native`       | yes            |
| `sap`                | yes            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | yes            |
| `sqljs`              | yes            |
| `sqlserver`          | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by TheProgrammer21** [comment]
I have a problem with my unit tests: They always pass, even if they should not.

```
import "reflect-metadata";
import { expect } from "chai";
import { Connection } from "../../../src";
import { closeTestingConnections, createTestingConnections, reloadTestingDatabases } from "../../utils/test-utils";
import { Category } from "./entity/Category";
import { Site } from "./entity/Site";

describe("github issues > #7974 Adding relations option to findTrees()", () => {

  let connections: Connection[];
  before(async () => connections = await createTestingConnections({
    entities: [__dirname + "/entity/*{.js,.ts}"],
    schemaCreate: true,
    dropSchema: true,
    enabledDrivers: ["mssql"]
  }));

  beforeEach(() => reloadTestingDatabases(connections));
  after(() => closeTestingConnections(connections));

  it("github issues > #7974 should return tree with sites relation", () => Promise.all(connections.map(async connection => {
    
    ...

    let x = await connection.getTreeRepository(Category).findTrees({ relations: ["sites"] });

    expect.fail("test to fail");

  })));

});
```


This is the output on the console: 
```

> mocha --file ./build/compiled/test/utils/test-setup.js --bail --recursive --timeout 60000 ./build/compiled/test "--grep=github issues > #7974"



  github issues > #7974 Adding relations option to findTrees()
    √ github issues > #7974 should return tree with sites relation


  1 passing (66ms)
```

I also don't see any console.log() outputs.

Does anyone have an idea? I did stick to the recommended testing template: https://github.com/TheProgrammer21/typeorm/blob/master/DEVELOPER.md#running-tests-locally

**Comment by TheProgrammer21** [comment]
I was able to aggregate the problem: The connections array is empty. Im now debugging..

**Comment by imnotjames** [comment]
You need to set up an ormconfig for it.  See the example used by circleci

**Comment by TheProgrammer21** [comment]
> You need to set up an ormconfig for it. See the example used by circleci

Ah I see.. I didn't run all DBMS but they were not skipped in the ormconfig. Probably something that could be mentioned in the development guide.
