### ISSUE TITLE
Module '"typeorm"' has no exported member 'WhereExpression'.

### ISSUE THREAD

**Issue by antonku** [typeorm/typeorm#7975]
### Expected Behavior

Typeorm exports `WhereExpression`

### Actual Behavior

Typeorm 0.2.34 exports `WhereExpression`
Typeorm 0.2.35 does not export `WhereExpression`

So it appears to be a breaking change (at least in typings)

### Steps to Reproduce

1. Import `WhereExpression` from Typeorm 0.2.35
2. Try to compile Typescript
3. See error `Module '"typeorm"' has no exported member 'WhereExpression'.`

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by antonku** [comment]
Looks like the root cause is that `WhereExpression` was renamed to `WhereExpressionBuilder` in https://github.com/typeorm/typeorm/commit/e922f353d34c604238c19d3fa4abc1fdad549e11#diff-2dd5e69a1e67aaf22416147cc9f2cf365b1813006f87147aba08f5dd9178bc3a

**Comment by imnotjames** [comment]
😫 we really shouldn't be exporting literally everything..

I'll make a deprecated alias for where expression
