### ISSUE TITLE
[QueryBuilder] Security concern with orderBy

### ISSUE THREAD

**Issue by mickaelmesdocteurs** [typeorm/typeorm#7978]
## Issue Description
Using the QueryBuilder, the orderBy method can be used to extract information from the database.
This might not be considered as an issue because nothing failled, there is no error, and the sql syntax is ok.
How should we prevent those kind of injections ?

### Steps to Reproduce
```typescript
const injection = 'CASE WHEN EXISTS(SELECT id FROM User WHERE lastname="Doe") THEN Post_id ELSE Post_title END';
return await this.postRepository.createQueryBuilder()
  .orderBy(injection, 'ASC')
  .limit(20)
  .skip(0)
  .getMany()
```

| Dependency          | Version  |
| ---                 | ---      |
| TypeORM version     | 0.2.32  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | maybe            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | maybe            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | maybe            |
| `sqlite-abstract`    | maybe            |
| `sqljs`              | maybe            |
| `sqlserver`          | maybe            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
Unfortunately, this is a feature that is relied upon by many users.  They need to include extra non-column data as part of the query orderBy

You can prevent this by restricting user input to a subset of known safe strings.
