### ISSUE TITLE
Need more information Basic Options query document

### ISSUE THREAD

**Issue by lifez** [typeorm/typeorm#7983]
### What was unclear or otherwise insufficient?

Link: https://typeorm.io/#/find-options/basic-options

<img width="880" alt="Screen Shot 2021-07-30 at 11 54 26" src="https://user-images.githubusercontent.com/2588927/127602371-3af3a5c4-c8fd-47e3-8354-3086cff13d20.png">

As the image above. When I first saw this expression. I assume that we can make a query to `profile.username` even `username` is not a primary key of `Profile` Table

### Recommended Fix

Add more context on how `User` and `Profile` has a relation with each other

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.

**Comment by imnotjames** [comment]
It's dependent on the type of relationship.

This does work in 0.2.35

**Comment by lifez** [comment]
@imnotjames Ohhhh. I used 0.2.32 thank you for your information.
