### ISSUE TITLE
How to only select relations_table in many to many, and two relation in one entity?

### ISSUE THREAD

**Issue by Fengjing95** [typeorm/typeorm#7985]
## description

I have a `User` entity, and it's have a property `follows`. typeof follows is `User[]`, so I declare a follows in the User entity

code（abbreviation） : UserEntity↓↓↓

```typescript
export class User {
  @PrimaryGeneratedColumn()
  id: number;
  
  // .....
  
  @ManyToMany(() => User, user => user.id)
  @JoinTable()
  follows: User[];
}
```

now, I want to select user's follow and paging, so I use innerJoin, take and skip
```typescript
.createQueryBuilder('user')
.innerJoinAndSelect('user.follows', 'follows')
.where('user.id = :id', { id: userId })
.skip(pageSize * (current - 1))
.take(pageSize)
.getMany();
```

but the result is one User and all users it follow, I found that skip and take restrict user entity rather than follows.

Is my operation wrong? Ask for help

**Comment by blazmrak** [comment]
Your query has where('user.id = :id'). Remove that and you will get the result.

**Comment by blazmrak** [comment]
If you want to see followers than you should not query the users table, but the follow table (the inbetween table). 

`
.createQueryBuilder('follow')
.innerJoinAndSelect('follow.follower', 'follower')
.where('follow.followed.id = :id', { id: userId })
.skip(pageSize * (current - 1))
.take(pageSize)
.getMany();
`
