### ISSUE TITLE
[Help] Many warning messages about the source map appear in the Electron console

### ISSUE THREAD

**Issue by ysfscream** [typeorm/typeorm#7986]
Hi all, I'm recently using SQLite and TypeORM to refactor the database of my Electron application, but I found that when debugging the application, Electron's console has a lot of warning messages about the source map and cannot load the map file resulting in 404.

![image](https://user-images.githubusercontent.com/21299158/127617148-178bfeb4-f6fb-4e42-b689-0e70566813b7.png)

This is strange and I'd like to know why this is happening and how to fix it, apparently, it doesn't make sense for me to disable the JavaScript source map in the console settings.

Thanks to create the amazing ORM library! Best regards!

**Comment by imnotjames** [comment]
This seems to be a local configuration issue, not a typeorm bug.

For questions or other general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
