### ISSUE TITLE
How to query or in a and clause with repository?

### ISSUE THREAD

**Issue by pvhuy84** [typeorm/typeorm#7987]
How can I query like this:

```
repository.find({
  where: {
   and: [
    { name: 'smith' },
    { or: [{ gender: 'male'  }, { age: 12 }] }
  ]
 }
})
```

thanks!

**Comment by blazmrak** [comment]
RTFM: https://typeorm.io/#/find-options

```JavaScript
repository.find({
  where: [
    { name: 'smith' },
    { gender: 'male' , age: 12 }
  ]
})
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
