### ISSUE TITLE
sqlite: "database" path should be created (mkdirp?)

### ISSUE THREAD

**Issue by stahlstift** [typeorm/typeorm#799]
### Given

```
# Example ormconfig.json
[
  {
    "name": "default",
    "type": "sqlite",
    "database": "./data/path/with/lot/sub/dirs/example.sq3",
    "autoSchemaSync": true,
    "entities": [
      "src/Model/*.js"
    ]
  }
]
```

### My expection
The whole path "./data/path/with/lot/sub/dirs/" should be created

### Result
Error: SQLITE_CANTOPEN: unable to open database file

### Question
Bug? Should I fix this and make a pull request?
I would fix this after #798

**Comment by pleerock** [comment]
This change will be released in 0.1.2
