### ISSUE TITLE
Datetime column altered on restart

### ISSUE THREAD

**Issue by lazaroofarrill** [typeorm/typeorm#7990]
### Expected Behavior
Same problem as issue #2333

Created column with type date, also tried timestamp. Expected to

### Actual Behavior

Colum with type Date is getting dropped and created after every restart in sync mode.

```
query ALTER TABLE `database`.`user` DROP COLUMN `lastLoggedOut`
query: ALTER TABLE `database`.`user` ADD `lastLoggedOut` timestamp(6) NULL
```

### Steps to Reproduce

```
@Entity()
export class User extends DefaultEntity implements ContactEntity {

    @Column('timestamp', { precision: 6, nullable: true })
    public lastLoggedOut?: Date
}

```

### My Environment

Ubuntu 21.04
MySQL 8.0.26
Node.js version v14.17.0
typescript@4.3.5
typeorm@0.2.35
@nestjs/core@7.6.18

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
Can you please create github repository with a minimal reproduction code? Or you can create a PR with a failing test if you wish.

**Comment by lazaroofarrill** [comment]
Deleting the dist folder solved the problem, thanks.
