### ISSUE TITLE
Already has Active Connection Error on refreshing page !

### ISSUE THREAD

**Issue by Abhay2132** [typeorm/typeorm#7999]
### Issue Description
When I run "createConnection" first time it works properly and give me the data record from database. But when I runs the code again it gives me AlreadyhasActiveConnectionError

### Expected Behavior

The database operation should run same as first time 

### Actual Behavior
```typescript
AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.
    at new AlreadyHasActiveConnectionError (/storage/emulated/0/ts/src/error/AlreadyHasActiveConnectionError.ts:8:9)
    at ConnectionManager.create (/storage/emulated/0/ts/src/connection/ConnectionManager.ts:57:23)
    at Object.<anonymous> (/storage/emulated/0/ts/src/index.ts:230:35)
    at step (/storage/emulated/0/ts/node_modules/tslib/tslib.js:143:27)
    at Object.next (/storage/emulated/0/ts/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/storage/emulated/0/ts/node_modules/tslib/tslib.js:114:62)
```

### Steps to Reproduce

1. Connect the localhost:5000/db/r routes for first time ( record will be shown properly )
2. Connect to same route ( or refresh the page ) second time ( error logged in terminal ) no response.

```typescript
My route handler ( app.ts )

/* imports */
app.get("/db/r", async (req, res, next) => {
    let data = await tom.r();
    console.log("Loaded users: ", data);
    res.json(data);
})
```
```typescript
My "TypeORM manager" (tom.ts)
import "reflect-metadata";
import {createConnection} from "typeorm";
import { User } from "./../../entity/User";

export class Tom {
    ch(cb) {
        return new Promise(res => {
            createConnection().then(conn => cb (conn, res)).catch(error => console.log(error));
        })
    }
    async r(q = {}) {
        return this.ch(async (conn, res) => {
            let repo = conn.getRepository(User);
            let users = await repo.find();
            res(users)
        })
    }
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Linux     |
| Node.js version     |  14.15.4 | 
| Typescript version  | 3.3.3333  | 
| TypeORM version     | 0.2.34 | 

### Additional Context

For complete code u can clone it from
<code>
https://github.com/Abhay2132/ts
</code>
Then run <code> npm i </code>.
And install typescript, ts-node and nodemon globally...
Then run <code> npm run dev </code>
Plzzz help me...

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `postgres`           | yes           |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.

**Comment by Abhay2132** [comment]
Update the <code> tom.ts -> ch</code> method like this 👍 

```typescript
ch(cb) {
  return new Promise(async res => {
    let cm = getConnectionManager();
    if (cm.has("default")) cb(cm.get("default"), res);
      else createConnection().then(conn => cb(conn, res)).catch(error => console.log("Error at cc : " + error));
  })
}
```

**Comment by imnotjames** [comment]
For questions and general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by Jogiter** [comment]
> Update the ` tom.ts -> ch` method like this 👍
> 
> ```ts
> ch(cb) {
>   return new Promise(async res => {
>     let cm = getConnectionManager();
>     if (cm.has("default")) cb(cm.get("default"), res);
>       else createConnection().then(conn => cb(conn, res)).catch(error => console.log("Error at cc : " + error));
>   })
> }
> ```

Thanks!  same error like [#592](https://github.com/typeorm/typeorm/issues/592). fixed the issue
