### ISSUE TITLE
Persisting Empty Array Fails

### ISSUE THREAD

**Issue by caffinatedmonkey** [typeorm/typeorm#80]
If the following code is run.

    const db = await createConnection({...})
    let myStuff: MyEntity[] = [];
    db.entityManager.persist(myStuff);

The following error is thrown:

    TypeError: Cannot read property 'constructor' of undefined

[It comes from this line not checking if the array is empty.](https://github.com/typeorm/typeorm/blob/master/src/entity-manager/EntityManager.ts#L73). Is this a bug? Should there should be a more useful error message.

Workaround:

    if (myStuff.length != 0) {
        db.entityManager.persist(myStuff);
    }

This ORM is awesome by the way.

**Comment by pleerock** [comment]
Yeap its a bug. Correct behaviour is to "do nothing" if array is empty. I'll fix it later.

> This ORM is awesome by the way.

Thank you. Please star a project if you like it 💯

**Comment by pleerock** [comment]
this is fixed and will be released in next typeorm version
