### ISSUE TITLE
ManyToMany. Relation table with custom columns

### ISSUE THREAD

**Issue by CocaColaBear** [typeorm/typeorm#800]
Hi. I'm stack on implement this: http://sqlfiddle.com/#!17/8507e/5
I need to add custom fields, like 'expires' in example, to relation table. Then, I want to get an account with his roles using:
`account.roles;`

My entities:

```
@Entity()
export default class Account {
	@Column({
		length: 128
	})
	email: string;

	@ManyToMany(type => Role)
	roles: Role[] = [];
}

@Entity()
export default class Role {
	@Column({
		length: 50
	})
	name: string;
}
```

Anyone can help?

**Comment by 19majkel94** [comment]
You have to replace ManyToMany relation with two OneToMany relations to new intermediate entity which has field "expires" 😉

**Comment by minostro** [comment]
I am trying to accomplish something similar:

```
Order
| id | amount | total_items |
|----+--------+-------------|
|    |        |             |

LineItem
| id | quantity | amount | order_id | product_id |
|----+----------+--------+----------+------------|
|    |          |        |          |            |

Product
| id | price | name |
|----+-------+------|
|    |       |      |

```
I followed @19majkel94 suggestion (or at least I think I did that) and I defined the following entities:

```typescript
@Entity()
export class Order {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    total: number;

    @OneToMany(type => LineItem, lineItem => lineItem.order)
    lineItems: LineItem[];
}

@Entity()
export class LineItem {

    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(type => Order, order => order.lineItems)
    order: Order;

    @ManyToOne(type => Product)
    product: Product;
}
```
The `Product` entity does not know about `LineItem` because there is no reason for it to know so far (at the application level). This code generated the right tables in my database schema. I do have a question when creating an `Order` though. I am doing the following:

```typescript
        await getManager().transaction(async manager => {
            const order : Order = new Order();
            order.total = 100;
            await manager.save(order);

            const product = await manager.findOneById(Product, 1);
            const lineItem = new LineItem();
            lineItem.order = order;
            lineItem.product = product;

            manager.save(lineItem);
            return manager.save(order);
        });
```
Is this the right wait to create an `order` with some `line items`? or there is a better way (new to typescript and typeorm) to do it?

**Comment by charMstr** [comment]
> I am trying to accomplish something similar:
> 
> ```
> Order
> | id | amount | total_items |
> |----+--------+-------------|
> |    |        |             |
> 
> LineItem
> | id | quantity | amount | order_id | product_id |
> |----+----------+--------+----------+------------|
> |    |          |        |          |            |
> 
> Product
> | id | price | name |
> |----+-------+------|
> |    |       |      |
> ```
> 
> I followed @19majkel94 suggestion (or at least I think I did that) and I defined the following entities:
> 
> ```ts
> @Entity()
> export class Order {
> 
>     @PrimaryGeneratedColumn()
>     id: number;
> 
>     @Column()
>     total: number;
> 
>     @OneToMany(type => LineItem, lineItem => lineItem.order)
>     lineItems: LineItem[];
> }
> 
> @Entity()
> export class LineItem {
> 
>     @PrimaryGeneratedColumn()
>     id: number;
> 
>     @ManyToOne(type => Order, order => order.lineItems)
>     order: Order;
> 
>     @ManyToOne(type => Product)
>     product: Product;
> }
> ```
> 
> The `Product` entity does not know about `LineItem` because there is no reason for it to know so far (at the application level). This code generated the right tables in my database schema. I do have a question when creating an `Order` though. I am doing the following:
> 
> ```ts
>         await getManager().transaction(async manager => {
>             const order : Order = new Order();
>             order.total = 100;
>             await manager.save(order);
> 
>             const product = await manager.findOneById(Product, 1);
>             const lineItem = new LineItem();
>             lineItem.order = order;
>             lineItem.product = product;
> 
>             manager.save(lineItem);
>             return manager.save(order);
>         });
> ```
> 
> Is this the right wait to create an `order` with some `line items`? or there is a better way (new to typescript and typeorm) to do it?

i think what @MichalLytek tried to explain, is that you should do something like this (to take the first example, much shorter):

```
@Entity()
export default class Account {
	@Column({
		length: 128
	})
	email: string;

        //This probably isn't required anymore, unless you want a bidirectional relationship?
	//@ManyToMany(type => Role)
	//roles: Role[] = [];
}

@Entity()
export class Intermediary { //would be the intermediary class, it has field expires

    @PrimaryGeneratedColumn()
    id: number;

    @Column()    //extra column added here
    expires: number;
    
    @OneToMany(type = Account)
    account: Account[];

    @OneToMany(type => Role)
    role: Role[];
}

@Entity()
export default class Role {
	@Column({
		length: 50
	})
	name: string;
}
```

So yep, there is a third entity.
