### ISSUE TITLE
Deprecated Get connections from ConnectionManager

### ISSUE THREAD

**Issue by pc3b3r** [typeorm/typeorm#8003]
## Issue Description

Related to #7839.  It's deprecating `get connections` without a specific reason. 

We are creating multiple connections at runtime and after a while we must iterate over all connections, without having a reference to all of them so it's really needed.

As a plus `Object.values(<Map>)` returns always an empty array https://github.com/typeorm/typeorm/blob/f7eb46dee0766581b6b182724051746e5d8d1b8b/src/connection/ConnectionManager.ts#L17

### Expected Behavior

ConnectionManager.connections should return the list of active connections

### Actual Behavior

Returns an empty array

### Steps to Reproduce

```typescript
await createConnections(connections)
console.log(getConnectionManager().connections)
```

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
The entirety of the connection manager is deprecated.   As such, having a location where there's a central repository of connections in a list is deprecated.

**Comment by pleerock** [comment]
@imnotjames created #8010 for that
