### ISSUE TITLE
createConnection throws ORA-12505 after TypeORM upgrade from 0.2.34 to 0.2.36

### ISSUE THREAD

**Issue by hvqzao** [typeorm/typeorm#8006]
## Issue Description

An attempt to createConnection using `type: 'oracle'` on TypeORM 0.2.36 throws fatal error:
```
Error: ORA-12505: TNS:listener does not currently know of SID given in connect descriptor
```
Reverting to TypeORM 0.2.34 resolves the issue.
When switching to `type: 'postgres'` using TypeORM 0.2.36, connection to database is established.

### Expected Behavior

createConnection with `type: 'oracle'` should establish connection.

### Actual Behavior

createConnection with `type: 'oracle'` crashes with error:
```
Error: ORA-12505: TNS:listener does not currently know of SID given in connect descriptor
```

### Steps to Reproduce

```
import 'reflect-metadata'
import { createConnection, Connection } from 'typeorm'

async function connect(): Promise<Connection> {
  let connection: Connection = null
  connection = await createConnection({
    type: 'oracle',
    username: '...',
    password: '...',
    host: '...',
    port: '...'
    sid: '...'
    // rest of configuration
    // entities, logging: false, synchronize: true, migrations: [], migrationsRun: false
  })
}
connect()
```

### My Environment

```
    "dotenv": "10.0.0",
    "express": "^4.17.1",
    "oracledb": "5.2.0",
    "pg": "8.7.1",
    "reflect-metadata": "^0.1.13",
    "typeorm": "0.2.36",
    "typescript": "4.3.5"
```

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  RHEL 7  |
| Node.js version     | v14.17.0  | 
| Typescript version  | 4.3.5 | 
| TypeORM version     | 0.2.36  | 
| Oracle driver     | oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64 |

### Additional Context

N/A

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | yes            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
Are you passing the service name instead of the SID?

**Comment by hvqzao** [comment]
Yes, it is indeed service name. Until now it worked fine. Do you know how can I define service name in createConnection options?

**Comment by imnotjames** [comment]
We always supported `SID`, not `Service Name`.

I'll add support for a `Service Name` to the connection options.
