### ISSUE TITLE
can't find sourcemap file

### ISSUE THREAD

**Issue by binvb** [typeorm/typeorm#8009]
## Issue Description
i used typeorm in electron application, but it console a lot of warning about failed to load typeorm SourceMap, e.g.
```
DevTools failed to load SourceMap: Could not parse content for https://***/Contents/Resources/app/node_modules/typeorm/connection/Connection.js.map: Unexpected token < in JSON at position 0
``` 
and then i found typeorm file are relate to sourcemap file in last line, e.g.
```
//  node_modules/typeorm/index.js
//# sourceMappingURL=index.js.map
```

### Expected Behavior
don't generate sourcemap

### Actual Behavior

```
// include the output in code tags like these!
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.15.2  | 
| Typescript version  | x.y.zzz  | 
| TypeORM version     | 0.2.36  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by binvb** [comment]
i don't konw if npm package need's sourcemap.but i assume if people needs sourcemap they should set it in application package stage.

**Comment by pleerock** [comment]
Issue you have is not related to TypeORM. Your assumptions about sourcemaps wrong. NPM packages must have them.
