### ISSUE TITLE
Option to remove database name from migrations

### ISSUE THREAD

**Issue by dotMortis** [typeorm/typeorm#8012]
## Feature Description

Two weeks ago, the name of the database was added to the migration queries.

### The Problem

Unfortunately, this does not work for us. We have several systems with different database names (Dev, Staging, Production).
We urgently need an option to disable this behavior.

### The Solution

The function needs an option to ignore the database name.

MysqlQueryRunner.ts
```typescript
  /**
   * Escapes given table or view path.
   */
  protected escapePath(target: Table|View|string): string {
      const { database, tableName } = this.driver.parseTableName(target);

      if (database) {
          return `\`${database}\`.\`${tableName}\``;
      }

      return `\`${tableName}\``;
  }
```

### Relevant Database Driver(s)

Every driver with this behaviour

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by csxcode** [comment]
Yes, I am experimenting this problem too

**Comment by pleerock** [comment]
> Two weeks ago, the name of the database was added to the migration queries.

would be great if you find the change set, PR, and ping author of the PR.

**Comment by Haruki-Mortis** [comment]
Sry, I don't know how to link the PR properly.

PR: https://github.com/typeorm/typeorm/pull/7950
@imnotjames

**Comment by jmazurpl** [comment]
Same here

**Comment by imnotjames** [comment]
The outcome from this was not an intentional change.  I've got a PR that's mostly got it fixed but it requires some more work when it comes to MSSQL.

**Comment by Dr-NULL** [comment]
I have this problem too. Normally I use three databases form every project, one for developing, other for testing, and finally another one for production. Before this change, I was simply changes the database name in my `ormconfig.json` and execute all migrations for the database specified in the json file. But now, **I must change the database name** in all migrations before to execute all.

**Comment by martinsantibanez** [comment]
Hi @imnotjames , thanks for the fix.
Is there a release date planned for this? I've noticed that it wasn't on 0.2.37

Thanks

**Comment by Dr-NULL** [comment]
I'm expecting a lot for this update too.
