### ISSUE TITLE
Support object instances in migrations list

### ISSUE THREAD

**Issue by guscastro** [typeorm/typeorm#802]
Essentially what I would like to do is dependency inject database migrations, so allowing object instances that implement `MigrationInterface` would make the following possible:
```
migrations: [
  context.resolve<PerformAMigration2808718439522>()
]
```
Migration names could still be retrieved with `this.constructor.name` in this case.

Keen to hear what you think.

Thanks

**Comment by pleerock** [comment]
Migrations are created using container. If you setup for example container with typedi you can then inject dependencies. Example with typedi:

```ts
// before creating connection somewhere like in app.ts
import {Container} from "typedi";
import {useContainer} from "typeorm";

useContainer(Container);
```

Then this will work:

```ts
import {Service} from "typedi";

@Service()
export class SomeMigration implements MigrationInterface {

    constructor(private userService: UserService, 
                         private passwordManager: PasswordManager) {
    }

}
```

If you don't use typedi then simply provide factory function to `useContainer` method
