### ISSUE TITLE
Update node js supported versions

### ISSUE THREAD

**Issue by houssemFat** [typeorm/typeorm#8029]
### Wrong node js supported version 
According to the documentation, typeorm supports nodejs starting from 4 and above.  Since the latest version [`0.2.36` ](https://github.com/typeorm/typeorm/releases/tag/0.2.36) this is no more the case. This release uses a new version of [`yargs`](https://github.com/typeorm/typeorm/commit/b797781a22db5b51c8f1f46be720a97a7d82420d) which support only node 12.

File in repository : [supported-platforms](https://github.com/typeorm/typeorm/blob/master/docs/supported-platforms.md)
Doc file [supported-platforms/nodejs](https://typeorm.io/#/supported-platforms/nodejs)

### Recommended Fix
Update supported-platforms page to node 12 or indicate the yargs dependencies.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.

**Comment by imnotjames** [comment]
We've not been confirming anything other than node 12+ - at the time when the docs were written this might have been the case but we follow in-support node versions.

**Comment by houssemFat** [comment]
@imnotjames thank you for your quick response. 
So `TypeORM was tested on Node.js version 4 and above.` is outdated ?

**Comment by imnotjames** [comment]
Well.. it **was** but definitely no longer is.

It's tested on node 12+.

**Comment by imnotjames** [comment]
If you've already started a PR would be great.  If not, I'll try to get to it sometime in the near future.

**Comment by houssemFat** [comment]
Ok thank you . 
Fine I will start a PR.
