### ISSUE TITLE
New Transaction for each migration step

### ISSUE THREAD

**Issue by wodka** [typeorm/typeorm#8032]
## Feature Description

each migration step should run as it's own transaction

### The Problem

with cockroachdb it is not possible to modify data within the same transaction of a structure change.

### The Solution

Therefor right now I am doing a strange workaround of manually commiting the transaction for each migration and then creating a new transaction.

```typescript
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.commitTransaction()

        await queryRunner.startTransaction()
        await queryRunner.query(`ALTER TABLE ...`);
        await queryRunner.commitTransaction()

        await queryRunner.startTransaction()
    }
```

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | yes            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  No, I don’t have the time, but I can support (using donations) development.
 - ✅  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
Isn't this already possible?

By setting `migrationsTransactionMode` to `each` or `none`

**Comment by wodka** [comment]
that is the perfect setting!

then perhaps just to update the documentation. Perhaps a little note to https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md for cockroach and the config itself to https://github.com/typeorm/typeorm/blob/master/docs/migrations.md?

If yes I would prepare some text notes
