### ISSUE TITLE
Create Migrations in specific folder / Hook to modify folder

### ISSUE THREAD

**Issue by wodka** [typeorm/typeorm#8033]
## Feature Description

allow creation of migration files in subfolders of migration dir. Like YYYY/MM

### The Problem

All migrations are created in the migrationDir

```
  "cli": {
    "migrationsDir": "src/migrations"
  }
```

### The Solution

I am thinking of 2 options:

#### Option 1

```json
{
  "cli": {
    "migrationsDir": "src/migrations",
    "migrationSubFolder": "YYYY/MM"
  }
}
```

#### Option 2 (only for js / inline config)

```js
module.export = {
  cli: {
    migrationsDir: "src/migrations",
   migrationSubFolder: () => {
      return 'name/of/sub/folder'
    }
  }
}
```

### Considered Alternatives

currently we are moving the files manually - not optimal

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | yes            |
| `aurora-data-api-pg` | yes            |
| `better-sqlite3`     | yes            |
| `cockroachdb`        | yes            |
| `cordova`            | yes            |
| `expo`               | yes            |
| `mongodb`            | yes            |
| `mysql`              | yes            |
| `nativescript`       | yes            |
| `oracle`             | yes            |
| `postgres`           | yes            |
| `react-native`       | yes            |
| `sap`                | yes            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | yes            |
| `sqljs`              | yes            |
| `sqlserver`          | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  No, I don’t have the time, but I can support (using donations) development.
 - ✅  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
I don't fully understand.  Why not set the migrations directory `src/migrations/YYYY/MM`

**Comment by wodka** [comment]
@imnotjames then we would need to change the directory every month.

- src/migrations/2021/03 _4 migrations_
- src/migrations/2021/05 _10 migrations_
- src/migrations/2021/06 _1 migration_
- src/migrations/2021/07 _30 migrations_
- ...

**Comment by imnotjames** [comment]
Wouldn't you need to anyway?  You'd just be setting the `subfolder` to a month instead of a dir.

Why not Something like this?

```
module.export = {
  cli: {
    migrationsDir: path.join("src/migrations", year, month),
  }
}
```

**Comment by wodka** [comment]
^^ well that is a really good solution!

I will now switch to this as it provides exactly what I am looking for.

thank you

**Comment by pleerock** [comment]
There is one inconvenience with provided solution - if you have generated migration let's say on 31 of December, and on next day somebody pull the codebase and run migrations - nothing will be executed. Same situation if you have migrations for several months and you decide to make a new server deploy - migrations won't be executed properly.

**Comment by imnotjames** [comment]
Doesn't the CLI migrationsDir only affect the output location of migrations?  I'll have to double check..

**Comment by wodka** [comment]
probably the configuration is incomplete @pleerock - this works flawlessly for me:

```ts
module.export = {
  cli: {
    migrationsDir: path.join("src/migrations", year, month),
  },
  migrations: [
    "src/migrations/**/*.ts"
  ],
}
```
