### ISSUE TITLE
value.toUpperCase is not a function

### ISSUE THREAD

**Issue by ShaharyarMaroof** [typeorm/typeorm#8035]
## Issue Description
When typeorm starts, it throws the following error `value.toUpperCase is not a function` in PostGresDriver.ts

### Expected Behavior
It should start the server and properly synchronize the schema to the database.

### Actual Behavior
server crashes when running npm start.

Screenshot of error
![Screenshot 2021-08-05 at 2 18 45 PM](https://user-images.githubusercontent.com/10959027/128326167-0abdf2c7-31a0-402e-81ad-620c200e58cc.png)

### Steps to Reproduce
1. I'm using number, string, datetime, jsonb and Array in my db schemas with `@Column` and `@ViewColumn` decorator

```typescript
@Column
column_name: number

@ViewColumn
list: Array<MyType>
```

### My Environment
NodeJS/Express

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     mac     |
| Node.js version     | 16.6.1 | 
| Typescript version  | 4.1.3  | 
| TypeORM version     | 0.2.36  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
Cannot replicate.  Can you include more information that helps with replicating this issue?  Perhaps a failing test case?

**Comment by ShaharyarMaroof** [comment]
I'm still tyring to debug which schema is causing this. but as soon as I rollback to 0.2.29 everything starts working.

**Comment by imnotjames** [comment]
I would look for anything which returns a default from a function.

**Comment by ShaharyarMaroof** [comment]
Okay, I'll take a look, if I don't find anything I'll close this issue. Thanks for the quick reply!

**Comment by ShaharyarMaroof** [comment]
After cleaning my modules and reinstalling typeorm, this issue goes away. But now I run into another issue with `materialized view schemas` I have. I've tried v.0.2.33, v0.2.36 and v0.2.39. 

This happens whenever I try to sync the schema with the database, but I can see the materialized view in pgAdmin.

![image](https://user-images.githubusercontent.com/10959027/128336470-7fdc7685-8a7c-4dea-9592-a1d2f5028594.png)

**Comment by imnotjames** [comment]
`v0.2.39` :thinking: 

Not sure what version that is.

I am going to need more info.  Your redaction method doesn't completely obscure everything but I don't really have it in me to reverse engineer anything here.

You're going to need to include more information & some way to replicate that problem.  Seems like a separate problem from the one described within this issue, though.

**Comment by ShaharyarMaroof** [comment]
I'll close this issue then, and log another issue with more details.

**Comment by Nicoowr** [comment]
For anyone stumbling on this, I had the same problem because I had this:
```
  @Column("boolean", {
    default: () => false, // don't put a function here, set the value instead
    name: "contains_customs_duties",
  })
  containsCustomsDuties: boolean;
```

**Comment by ValTashkov** [comment]
> For anyone stumbling on this, I had the same problem because I had this:
> 
> ```
>   @Column("boolean", {
>     default: () => false, // don't put a function here, set the value instead
>     name: "contains_customs_duties",
>   })
>   containsCustomsDuties: boolean;
> ```

Same issue here.  The issue came from the Github Copilot that suggested it
