### ISSUE TITLE
Add support for ENUMs for cockroachdb

### ISSUE THREAD

**Issue by rafiss** [typeorm/typeorm#8039]
## Feature Description

CockroachDB supports enums very similarly to how Postgres does. The TypeORM driver for CockroachDB should recognize that.

### The Problem

Currently, TypeORM does not recognize enum as a supported type for CockroachDB, so this feature is not available to users.

### The Solution

Support enums for CockroachDB just as they are for Postgres. See https://github.com/typeorm/typeorm/commit/43e52c57903fa9c86c947f3c8fc45c718ee4f2e1 for initial PG enum support as well as the current code.

### Considered Alternatives

Use string constants,

### Additional Context

This was requested on the cockroachdb repo here: https://github.com/cockroachdb/cockroach/issues/68368

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | yes            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
If you want to contribute to this feature - you need to take a look how other drivers implement `enums` and do it similar.

**Comment by supanadit** [comment]
yeah it should be similar to how enum works in postgresql

**Comment by simplenotezy** [comment]
Should be fixed here: https://github.com/typeorm/typeorm/pull/9128
