### ISSUE TITLE
Queries being executed outside transaction

### ISSUE THREAD

**Issue by yonilerner** [typeorm/typeorm#804]
Current version: `0.1.0-alpha.33`

The problem Im having is that certain queries that are being run with an EntityManager that is transacting arent being run in the transaction.

This is how Im creating the entity manager:
```
const entityManager = connection.createQueryRunner().manager
```

Then, in some part of the code, I write:
```
entityManager.queryRunner.startTransaction()
```
(I use `entityManager` instead of the `queryRunner` just for convenience. `entityManager.queryRunner` is referring to the query runner from `createQueryRunner`).

Now, if I run pretty much any query like `entityManager.findOne(...)` or `entityManager.save(...)`, it works just fine. But, if I do either `entityManager.clear(Entity)` or `entityManager.query('DELETE FROM table')`, those queries are being run outside the transaction, meaning they are taking effect even after I rollback.

Example:

In this case, the transaction is properly rolled back (nothing is deleted):
```
await entityManager.queryRunner.startTransaction()
const item = await entityManager.findOne(Entity, {query...})
await entityManager.remove(item)
await entityManager.queryRunner.rollbackTransaction()
```
However, in this case, the query appears to be run outside of the transaction (everything is deleted):
```
await entityManager.queryRunner.startTransaction()
await entityManager.clear(Entity)
await entityManager.queryRunner.rollbackTransaction()
```

Am I doing something wrong?

**Comment by yonilerner** [comment]
This also seems to work as expected:
```
await entityManager.queryRunner.startTransaction()
await entityManager.createQueryBuilder(Entity, 'e')
                .delete()
                .execute()
await entityManager.queryRunner.rollbackTransaction()
```

**Comment by pleerock** [comment]
Clear calls `TRUNCATE` inside. In mysql `TRUNCATE` calls `COMMIT` imminently. It means you cannot rollback this action. See [here](https://stackoverflow.com/a/5972738/925151).

`entityManager.query('DELETE FROM table')` works as expected, I added tests to confirm it, please check them.

**Comment by yonilerner** [comment]
Thanks for explaining! Im not sure how I decided that `entityManager.query` was broken, but clearly its not.
