### ISSUE TITLE
Add notWhere, andNotWhere methods to WhereExpressionBuilder interface

### ISSUE THREAD

**Issue by akaNightmare** [typeorm/typeorm#8042]
## Feature Description
Hello, it would be useful if `notWhere`, `andNotWhere` methods will be added to the query builder.

### The Problem
Sometimes need to add smth like `andWhere('NOT (first_name = "John" AND last_name = "Doe")')`, I know that can be transformed like `andWhere('first_name <> "John" AND last_name <> "Doe"')` but the conditions can be much more difficult and wrapped to `new Brackets()` and in this way I have to manually transform all conditions.

### The Solution
Just add those two methods to `WhereExpressionBuilder` interface.

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | yes            |
| `aurora-data-api-pg` | yes            |
| `better-sqlite3`     | yes            |
| `cockroachdb`        | yes            |
| `cordova`            | yes            |
| `expo`               | yes            |
| `mongodb`            | yes            |
| `mysql`              | yes            |
| `nativescript`       | yes            |
| `oracle`             | yes            |
| `postgres`           | yes            |
| `react-native`       | yes            |
| `sap`                | yes            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | yes            |
| `sqljs`              | yes            |
| `sqlserver`          | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
I'm sorry I don't think we should add these kind of methods to `QueryBuilder`. `QueryBuilder` is already heavy enough and has many redundant methods in it. Please consider patching QueryBuilder for your needs.
