### ISSUE TITLE
Brackets not adding brackets on 0.2.36

### ISSUE THREAD

**Issue by Nenillo** [typeorm/typeorm#8043]
I'm using the query builder and I have a condition similar to this one:

```typescript
query.andWhere(
  new Brackets(qb =>
    qb.where('o.description ilike :searchText OR o.name ilike :searchText', { searchText: `%${searchText}%` }),
  ),
)
```

After upgrading to 0.2.36 this code is not wrapping the provided SQL in brackets.

It fails on 0.2.35, works when rolling back to 0.2.34

**Comment by imnotjames** [comment]
This happens when you pass `Brackets` a single item.  Looks to be a regression.
