### ISSUE TITLE
Insert fails if PrimaryGeneratedColumn has value

### ISSUE THREAD

**Issue by awn70** [typeorm/typeorm#8045]
## Issue Description
When you try to insert an entity with `repo.insert( entity )` and the entity's `PrimaryGeneratedColumn` column has a value the operation fails, because typeorm tries to insert the value.
(The column has a value because the entity is a clone of an existing one.)

### Expected Behavior

Typeorm ignores the value and returns the new generated value. (typeorm 0.2.34)

### Actual Behavior

Insert fails if the PK value already exists.

```
Violation of PRIMARY KEY constraint 'TTT_PK'. Cannot insert duplicate key in object ...
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 12.20.2  |
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.36  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by drjamesj** [comment]
Please post the relevant sample code to reproduce the issue.

**Comment by imnotjames** [comment]
Isn't this the expected result because you're telling TypeORM to do something & it is?

**Comment by imnotjames** [comment]
I do believe that this was done to fix another issue - so if you're telling TypeORM to insert a value then it's going to attempt to do so.  The fact that it was ignoring this before was a bug.

**Comment by pleerock** [comment]
As I remember - if database allows you to do so - TypeORM is able to insert your value provided to the generated column. We need a minimal reproduction (and test if possible) to understand why it doesn't work in your case.

**Comment by awn70** [comment]
I've noticed the change after upgrading to version 0.2.36. The only thing I need to know is the designated behavior. Should typeorm try to insert a value into an column annotated with `PrimaryGeneratedColumn` or not? If it should do it then everything is fine and an old bug was fixed.
