### ISSUE TITLE
Time Zone is not working probably 

### ISSUE THREAD

**Issue by Abdullah3553** [typeorm/typeorm#8049]
## Issue Description
when i store a @CreateDateColumn() in a sql database , when i check the time stamp in the database using phpmyadmin , the date and time is stored exactly like it should be but , when i use find method iside the service, the returned time stampe is totally wrong, it's late 2 hours or so ...  

### Expected Behavior
the time stamp is returned exactly like how it's actually stored 

### Actual Behavior

the time stamp is late 2 hours or so 

output
```
"id": 1,
"creationDate": "2021-08-06T23:33:02.120Z",
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v16.4.2
  | 
| Typescript version  |  typescript@4.3.5
  | 
| TypeORM version     | typeorm@0.2.34
  | 

### Additional Context
:p

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | YES YES YES        |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 -  ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
because the server you are running (I guess your computer) isn't in UTC, and the date is transformed into your local time. Make sure to store your dates in UTC and on your server side also have it in UTC, and when you return date back to the clients you can apply their timezone to have their time on their devices.

Please use TypeORM's slack channel or StackOverflow to ask these kind of questions.
