### ISSUE TITLE
Sqlite in undefined state when hot reloading in capacitor app in Android Studio

### ISSUE THREAD

**Issue by ajmas** [typeorm/typeorm#8056]
### Expected Behavior

Currently developing a Capacitor app using SQLiteConnection. During development time if I make a code modification, then I expect the database connection to either currently exist and be reusable or an closed and be openable, such that we can continue without needing to do a hard restart of the app.

### Actual Behavior

If do a code change that requires a hot code change, then I end up with the following output:

```
(index):230 native CapacitorSQLite.createConnection (#102445183)
(index):204 result CapacitorSQLite.createConnection (#102445183)
error Error: CreateConnection: Connection turbodega already exists
    at Object.cap.fromNative ((index):428)
    at <anonymous>:1:18
```

### Steps to Reproduce

```
   import { CapacitorSQLite, SQLiteConnection } from '@capacitor-community/sqlite';
   import { createConnection } from 'typeorm';

    const sqliteConnection = new SQLiteConnection(CapacitorSQLite);

    const connection = await createConnection({
      name: 'mainConnection',
      type: 'capacitor',
      driver: sqliteConnection,
      database: 'myDatabase',
      logging: ['error', 'query', 'schema'],
      synchronize: true,
      entities: Entities
    });
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      Android 11 in Android Studio emulator    |
| Node.js version     | 14.15.1  | 
| Typescript version  | 3.3.3333  | 
| TypeORM version     | 0.2.36 | 

### Additional Context

Prior to using typeorm, I was using @capcitor-community/sqlite directly and ran into the same issue. The developer suggested adding the following code to deal with the issue:

```
let database;
try {
      // Check Connections Consistency
      ret= await this._sqlite.checkConnectionsConsistency();
      if(!ret.result) {
         database = await sqlite.createConnection(connectionName);
      } else {
         database = await sqlite.retrieveConnection(connectionName);
      }
} catch (error) {
      throw new Error(' your message ');
}
```

We could probably add the same logic to the driver in typeorm?

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
The error message you're showing is that the global createConnection is being called twice with the same name.

Either check if the TypeORM connection of that name already exists or manage connections yourself by using the connection constructor.

**Comment by imnotjames** [comment]
And If you want to make that change to the capacitor driver, PRs are accepted!  But it won't fix the problem described in this issue.

**Comment by ajmas** [comment]
I'll try out the suggested usage change on my side, to validate
