### ISSUE TITLE
Database Connection information is lost on `connect()` call in the PostgresDriver

### ISSUE THREAD

**Issue by Agreon** [typeorm/typeorm#8057]
### Expected Behavior

We pass our connection information into typeorm in form of a URL. This information should be parsed correctly and applied to the database driver.

### Actual Behavior

The database information is lost. Tables, that are created from migrations are not found in the specified catalouge..

### Steps to Reproduce

Actually, this bug was introduced in #7742, when `DriverUtils.buildDriverOptions` was only added to the constructor of the `PostgresDriver`, but not the `connect` function where the option object is reassigned.

 Exact line: https://github.com/typeorm/typeorm/blob/5a3767f58f6ef355b01cf6e92342401a051a369c/src/driver/postgres/PostgresDriver.ts#L304

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Ubuntu        |
| Node.js version     | 14.16.1  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.36  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes           |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

Maybe other drivers are affected as well.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
Good catch.  Should just remove the assignment from `connect` I think.

**Comment by Agreon** [comment]
If that's possible. I thought it might make problems if the options are altered after the constructor was called. But i guess that should not happen anyways.

**Comment by Agreon** [comment]
I just found this is also occurring in `SqlServerDriver`, `OracleDriver`, `SapDriver` and `CockRoachDriver`.

**Comment by imnotjames** [comment]
If that's happening now then it's a very, very bad idea.  Much of our code assumes that the options are read-only.
