### ISSUE TITLE
Creating a foreign key for a composite key

### ISSUE THREAD

**Issue by dorukokan** [typeorm/typeorm#806]
Hi, I've been trying to create a foreign key, but could not find out how to do it properly. My entities are as the following:

    @Entity()
    export class LocationName {
       @PrimaryColumn('string')
       locationNameSpace: LocationNameSpace;

       @PrimaryColumn('string')
       name: string;

       @Column('string')
       description: string;
    }

    @Entity()
    export class LocationNameTranslation {

      @ManyToOne(type => LocationName, locationName => (locationName))
      sourceLocationName:LocationName;

      @ManyToOne(type => LocationName, locationName => (locationName))
      targetLocationName:LocationName;
    }

However, I'm getting the following error:
"Cannot automatically determine a referenced column of the "LocationName", because it has multiple primary columns. Try to specify a referenced column explicitly." Checked the examples but could not find any similar. What is the correct way to define a foreign key for a composite primary key? Checked the examples but could not see a similar one...

**Comment by pleerock** [comment]
what typeorm version are you using?

**Comment by dorukokan** [comment]
I'm using the following:
"typeorm": "0.0.8",
"typeorm-routing-controllers-extensions": "0.0.6"

**Comment by pleerock** [comment]
ohh very old version. Composite foreign key support was added in the latest 0.1.0-alpha versions. Please consider upgrade your typeorm version

**Comment by pleerock** [comment]
This must work in latest versions. Please let me know if its not.
