### ISSUE TITLE
cockroach db probs

### ISSUE THREAD

**Issue by kakarot-dev** [typeorm/typeorm#8060]
## Issue Description
`Wrong driver: "undefined" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "better-sqlite3", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".`
this is the error i get when i try to login with the options

```
/* eslint-disable no-undef */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const text = require('./dist/bot/struct/text');

const cert = text.default(`${process.cwd()}/certs/root.crt`, require)
module.export = {
   type: "cockroachdb",
   url: "postgresql://<link>",
   host: "<db>.cockroachlabs.cloud",
   port: 26257,
   username: "<username>",
   password: "<password>",
   database: "<db>",
   synchronize: true,
   logging: false,
   extra: {
      ssl: {
         ca: cert
      }
   }
}
```

### Expected Behavior
i expected it to connect to cockroachdb

### Steps to Reproduce
i have shard the link above

### My Environment
linux, nodejs version 16.6

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.6.0  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.36  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | yes            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

**Comment by kakarot-dev** [comment]
can i be given a example how to connecto to a cockroach db??

examples are so outdated

**Comment by imnotjames** [comment]
Your ORM config is not loading as expected - hence the `undefined` message.

**Comment by kakarot-dev** [comment]
it is being loaded

**Comment by kakarot-dev** [comment]
still, would it be possible to get a example??
the example repos are from 2017, and the ts version is outdated

**Comment by kakarot-dev** [comment]
I will try the file tomorrow, and report back

**Comment by imnotjames** [comment]
I included your config in your post instead of linking it.

**Comment by imnotjames** [comment]
I just looked again at your config - you have a typo

```diff
/* eslint-disable no-undef */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const text = require('./dist/bot/struct/text');

const cert = text.default(`${process.cwd()}/certs/root.crt`, require)
- module.export = {
+ module.exports = {
   type: "cockroachdb",
   url: "postgresql://<link>",
   host: "<db>.cockroachlabs.cloud",
   port: 26257,
   username: "<username>",
   password: "<password>",
   database: "<db>",
   synchronize: true,
   logging: false,
   extra: {
      ssl: {
         ca: cert
      }
   }
}
```

**Comment by imnotjames** [comment]
Either way, at this time I can't replicate your issue.  It looks to not be a problem with TypeORM but an issue with how you've configured your environment.

---

For questions / general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by kakarot-dev** [comment]
Ty I’ll fix the typo then try it again

Else I’ll try the example given

As for the slack community, I joined although I got no response

**Comment by kakarot-dev** [comment]
> in the example you posted it should also only be one option:
> 
> ```
>    type: "cockroachdb",
>    url: "postgresql://<link>", // probably remove this
>    host: "<db>.cockroachlabs.cloud",
> ```
> 
> Working ormconfig.ts file:
> 
> ```ts
> import { ConnectionOptions } from 'typeorm'
> 
> const config: ConnectionOptions = {
>   'cli': {
>     'migrationsDir': 'src/migrations',
>   },
>   'database': 'defaultdb',
>   'entities': ['src/**/*.entity.ts'],
>   'host': 'localhost',
>   'migrations': ['src/migrations/**/*.ts'],
>   'migrationsTableName': 'nest_migrations',
>   'migrationsTransactionMode': 'each',
>   'password': 'root',
>   'port': 26257,
>   'synchronize': false,
>   'type': 'cockroachdb',
>   'username': 'root',
> }
> 
> export default config
> ```

@wodka i removed it and the current issue is fixed, but now a new issue appeared saying
`codeParamsRoutingFailed: missing cluster name in connection string`
the current settings are same, i just removed the "url" from it.
any idea why this is happening

**Comment by wodka** [comment]
@kakarot-dev I would assume because the ssl config is not there

**Comment by wodka** [comment]
@kakarot-dev please move those questions to slack
