### ISSUE TITLE
Error in persisting dates in 0.1.0-alpha.35

### ISSUE THREAD

**Issue by OysteinAmundsen** [typeorm/typeorm#807]
I've tried to upgrade from typeorm v0.0.11 to v0.1.0-alpha.35, but ran into an issue.

Consider the following 

### model:

    @Entity()
    export class Tournament {
      @PrimaryGeneratedColumn()
      id: number;

      @Column({ unique: true, length: 200 })
      name: string;

      @Column()
      startDate: Date;

      @Column()
      endDate: Date;
    }

### Controller:

    @Service()
    @JsonController('/tournaments')
    export class TournamentController {
        private repository: Repository<Tournament>;
        private conn: Connection;

        constructor() {
            this.repository = getConnectionManager().get();.getRepository(Tournament);
        }

        @Post()
        create( @Body() tournament: Tournament) {
            return this.repository.persist(tournament);
        }
    }

### POST Payload

    {
      "id": null,
      "name": "Some name",
      "startDate": "2017-08-28T00:00:00.000Z",
      "endDate": "2017-08-31T23:59:59.999Z"
    }

### typeorm v0.0.11

    INSERT INTO `tournament`(
      `name`, 
      `startDate`, 
      `endDate`
    ) VALUES (
      "Some name",
      "2017-08-28 00:00:00",
      "2017-08-31 23:59:59"
    )

### typeorm v0.1.0-alpha.35

    INSERT INTO `tournament`(
      `id`, 
      `name`, 
      `startDate`, 
      `endDate`
    ) VALUES (
      null,
      "Some name",
      "2017-08-28T00:00:00.000Z",
      "2017-08-31T23:59:59.999Z"
    ) 

I don't know if this is a bug in v0.0.11 for reconstructing the date value from a UTC date to a MySQL compliant date value, or if it's a bug in v0.1.0 for not reconstructing it. I'm creating the date values using momentJS, and I'm trying to keep all my dates in UTC only. As it seems MySQL does not care much for zulu marks in dates and will throw if found.

I guess I can work around this by manipulating the payload before I post it to my controller, but I guess I'm wondering if this change in functionality is by design or by mistake. ;-)

**Comment by pleerock** [comment]
Can you explain me what is the problem with new date format? Doesn't mysql understand it? The difference between 0.0.11 vs 0.1.0 is millisecond support. I think that's why date format has changed. But isn't it correct? I need to understand exact problem this new format cause for you

**Comment by OysteinAmundsen** [comment]
Sorry about not posting the actual error message:
```
ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2017-08-28T00:00:00.000Z' for column 'startDate' at row 1
```

An example of a similar issue can be found [here](https://dba.stackexchange.com/questions/48704/mysql-5-6-datetime-incorrect-datetime-value-2013-08-25t1700000000-with-er#answer-48745), which also links to the [mysql documentation](http://dev.mysql.com/doc/refman/5.6/en/date-and-time-literals.html) explaining legal date values in more detail.

I hope this provides enough information for you. :-)

**Comment by pleerock** [comment]
Its a bug. Its stopped working with date strings (you send via http string and not real date objects). Fix will be released in next alpha version

**Comment by kimcuong060498** [comment]
The same issue on 0.2.17 version.
