### ISSUE TITLE
Add relation options to all tree queries (missing ones)

### ISSUE THREAD

**Issue by spiotr12** [typeorm/typeorm#8076]
## Feature Description

Add relation options to all tree queries (missing ones)

### The Problem

[This PR](https://github.com/typeorm/typeorm/pull/7981#issuecomment-898186470) did introduce a `FindTreeOptions` to some of the find* methods. However there are 3 methods that did not got these options: 
- findDescendants
- findAncestors
- findAncestorsTree

### The Solution

Could this be also added?

### Additional Context

So then used tree repository and finding ancestors, descendants in flat or tree structure, the relations are loaded as well (or selected to be loaded)

### Relevant Database Driver(s)

I think it relates to repository - not to a specific driver

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by TheProgrammer21** [comment]
I just implemented this issue - pull request comes in a minute.
