### ISSUE TITLE
Diversions on SQL generated for CreateDateColumn on query Builder and Entity.create()

### ISSUE THREAD

**Issue by andreluizpd** [typeorm/typeorm#8083]
## Issue Description
Hello, I'm having some issues with the generated SQL on Entity.create(), I'm using postgresql and typescript.

Right now I have a simple entity: 
```javascript
import { Field, ObjectType } from 'type-graphql';
import {
  BaseEntity,
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

@ObjectType()
@Entity()
export class Post extends BaseEntity {
  @Field()
  @PrimaryGeneratedColumn()
  id!: number;

  @Field(() => String)
  @CreateDateColumn()
  createdAt = Date;

  @Field(() => String)
  @UpdateDateColumn()
  updatedAt = Date;

  @Field()
  @Column()
  title!: string;
}
```

But when I try to create an item like this:

```javascript
Post.create({ title: "This is a title" }).save();
```

The SQL returns with an error:
```sql
query: INSERT INTO "post"("createdAt", "updatedAt", "title") VALUES (Sat Aug 14 2021 15:09:17 GMT-0300 (Brasilia Standard Time), Sat Aug 14 2021 15:09:17 GMT-0300 (Brasilia Standard Time), $1) RETURNING "id", "createdAt", "updatedAt" -- PARAMETERS: ["Teste de titulo 3"]
query failed: INSERT INTO "post"("createdAt", "updatedAt", "title") VALUES (Sat Aug 14 2021 15:09:17 GMT-0300 (Brasilia Standard Time), Sat Aug 14 2021 15:09:17 GMT-0300 (Brasilia Standard Time), $1) RETURNING "id", "createdAt", "updatedAt" -- PARAMETERS: ["Teste de titulo 3"]
error: error: syntax error at or near "Aug"
```

One way to solve the issue was to use a query builder like this:
```javascript
await getConnection()
      .createQueryBuilder()
      .insert()
      .into(Post)
      .values({
        title: "This is a title",
      })
      .returning('*')
      .execute();
```

with the returning sql being:
```sql
query: INSERT INTO "post"("createdAt", "updatedAt", "title") VALUES (DEFAULT, DEFAULT, $1) RETURNING * -- PARAMETERS: ["Teste de titulo 3"]
```

Which works.

Am I doing something wrong?

### Expected Behavior

The use of Entity.create should return a SQL statement like this: 
```sql
query: INSERT INTO "post"("createdAt", "updatedAt", "title") VALUES (DEFAULT, DEFAULT, $1) RETURNING * -- PARAMETERS: ["Teste de titulo 3"]
```

### Actual Behavior

Right now the SQL generated by Entity.crete is this:

```sql
query: INSERT INTO "post"("createdAt", "updatedAt", "title") VALUES (Sat Aug 14 2021 15:09:17 GMT-0300 (Brasilia Standard Time), Sat Aug 14 2021 15:09:17 GMT-0300 (Brasilia Standard Time), $1) RETURNING "id", "createdAt", "updatedAt" -- PARAMETERS: ["Teste de titulo 3"]
query failed: INSERT INTO "post"("createdAt", "updatedAt", "title") VALUES (Sat Aug 14 2021 15:09:17 GMT-0300 (Brasilia Standard Time), Sat Aug 14 2021 15:09:17 GMT-0300 (Brasilia Standard Time), $1) RETURNING "id", "createdAt", "updatedAt" -- PARAMETERS: ["Teste de titulo 3"]
error: error: syntax error at or near "Aug"
```

### Steps to Reproduce

You can follow the issue description

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Ubuntu WSL         |
| Node.js version     | v16.4.2  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.37  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
Can you create a test case that exhibits this issue?

**Comment by andreluizpd** [comment]
> Can you create a test case that exhibits this issue?

Hello @imnotjames, I'm really sorry but I don't think I understand the question. The way the error occurs is when the posts.create is called.

**Comment by imnotjames** [comment]
We have tests that use this and aren't seeing this issue.  

Create a unit test which exhibits this problem so someone like myself can see this problem in action.

Check out the DEVELOPERS.md file for info

**Comment by imnotjames** [comment]
Actually, I see your issue.  

```
created = Date
```

Passing a function as a value will cause the result to be inserted directly without escaping for an `insert`.

You're assigning the function `Date` which returns a `Date` object.  That's converted to a string.

Instead use

```
created: Date
```

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by andreluizpd** [comment]
Thank you for the answer and sorry for the inconvenience

**Comment by imnotjames** [comment]
> Thank you for the answer and sorry for the inconvenience

No worries!  Just happy it's not a new regression or something sketchy :)
