### ISSUE TITLE
Creating Databases using typeorm

### ISSUE THREAD

**Issue by omidnavi** [typeorm/typeorm#809]
Hi
I wanted to create a schema if it does not exists , So is this possible with typeorm ?
e.g is there anyway to make "database" optional in Connection object ? as I Know the mysql driver can handle this connection I'm not sure about others. And is there any way to have "custom queries" like "CREATE DATABASE IF NOT EXISTS" or making a function for this ?

Can u help me modifying this ?

**Comment by pleerock** [comment]
yeah to run a custom query you can use `connection.query` method:

```ts
connection.query("CREATE DATABASE IF NOT EXISTS");
```

**Comment by omidnavi** [comment]
Thanks this can do the job , but are you planning to add this feature (opening connections without specifying database ) so this can be done with a simple function like other functions  ?

**Comment by pleerock** [comment]
Yeah I'll think how to fix this issue

**Comment by AlexMesser** [comment]
You can now open connections without specifying database in SQL Server and MySql. Dynamic database creation also supported. [Using multiple databases in a single connection](https://github.com/typeorm/typeorm/blob/master/docs/using-multiple-databases.md#using-multiple-databases-in-a-single-connection). This feature will be released in `0.1.0-alpha.48`

**Comment by evenfrost** [comment]
@AlexMesser is it supported for Postgres?

**Comment by edevil** [comment]
@pleerock @AlexMesser This is currently not supported with Postgres, right?

**Comment by NSExceptional** [comment]
I am also using Postgres and would like to know. Bump

**Comment by XBeg9** [comment]
Any news to get this done for Postgres?

**Comment by basicBrogrammer** [comment]
It would be nice if there was something like rails' `rails db:setup` or `rails db:create db:migrate`

**Comment by sebilasse** [comment]
Postgres support would be so nice.

**Comment by fr3fou** [comment]
I haven't managed to get this working with MariaDB. Any progress on this?

**Comment by jalooc** [comment]
Actually, it'd be awesome if the migrations script, instead of failing on `ER_BAD_DB_ERROR` (non-existent DB) just created DB with that name. It'd automate some infrastructure jobs very nicely.

**Comment by ilakshmikanthp** [comment]
Any update on the hasDatabase() implementation for postgresql??

**Comment by fullofcaffeine** [comment]
+1 could we get a script to create the database?

**Comment by tcd** [comment]
Does anyone have a good solution for this?

**Comment by ivawzh** [comment]
@tcd I have created a tiny library to create and drop databases. 
The only dependency of the library is `pg` which is also required by TypeORM anyway.

See here for details doc https://github.com/ivawzh/pg-god#with-typeorm

**Comment by alete89** [comment]
I'm a bit confused. `database` is mandatory in order to create a new `connection`. How would I run `connection.query('create database')` if I need a database from the beggining. 😕

**Comment by mrnateriver** [comment]
In case of PostgreSQL you can use default databases for initial bootstrapping: `postgres`, `template0` and `template1`. That is - simply use them for connection, do your deployment work and then reconnect to the newly created DB.

Granted, there are scenarios when this DBs can be unavailable, but those are unlikely.

**Comment by YEMEAC** [comment]
add the possibility to create the DB running a migration please

**Comment by RomanSolianik** [comment]
we still don`t have a sulution.. Ruby on  Rails's `rake db:create` and `rake db:drop` works perfect almost from the beginning of rails

**Comment by Tada5hi** [comment]
You can also use [https://www.npmjs.com/package/typeorm-extension](typeorm-extension) package, to `create` or `drop` the database specified for the connection, for nearly all database driver.
The package alsoo parses the extra parameter `charset` and `characterSet` of the extra parameter (ENV: TYPEORM_DRIVER_EXTRA)
```typescript
import {getConnectionOptions} from "typeorm";
import {createDatabase} from "typeorm-extension";

(async () => {
    const connectionOptions = await getConnectionOptions();

    await createDatabase(connectionOptions, {ifNotExist: true});
   
    await dropDatabase(connectionOptions, {ifExist: true});

    process.exit(0);
})();
````
You can also provide the `charset` and `characterSet` as second parameter to the `createDatabase()` function.
F.e 
- postgres
`createDatabase(connectionOptions, {ifNotExist: true, characterSet: "UTF8"});`
- mysql
`createDatabase(connectionOptions, {ifNotExist: true, charset: "utf8mb4_general_ci", characterSet: "utf8mb4"});`

If you have any questions or concerns feel free to contact me or contribute to the codebase on github :)

**Comment by mostafa-hz** [comment]
> You can also use https://www.npmjs.com/package/typeorm-extension package, to `create` or `drop` the database specified for the connection, for nearly all database driver. The package also parses the extra parameter `charset` and `characterSet` of the extra parameter (ENV: TYPEORM_DRIVER_EXTRA)
> 
> ```ts
> import {createDatabase} from "typeorm-extension";
> 
> (async () => {
>     await createDatabase({ifNotExist: true});
>    
>     await dropDatabase({ifExist: true});
> 
>     process.exit(0);
> })();
> ```
> 
> You can also provide the `charset` and `characterSet` as properties for the first parameter to the `createDatabase()` function. F.e
> 
> * postgres
> 
> ```ts
> createDatabase({ifNotExist: true, characterSet: "UTF8"});
> ```
> 
> * mysql
> 
> ```ts
> createDatabase({ifNotExist: true, charset: "utf8mb4_general_ci", characterSet: "utf8mb4"});
> ```
> 
> If you have any questions or concerns feel free to contact me or contribute to the codebase on github https://github.com/Tada5hi/typeorm-extension/issues :)

Be careful about using this library on production, any unwanted changes in the library can wipe out your database!

**Comment by rafaelsiqueira** [comment]
> Be careful about using this library on production, any unwanted changes in the library can wipe out your database!
Agree, but... you also should avoid using a database user with this kind of power in production... At most, the database users in production should be able to insert/select/update.

**Comment by tada5hi** [comment]
> > You can also use https://www.npmjs.com/package/typeorm-extension package, to `create` or `drop` the database specified for the connection, for nearly all database driver. The package also parses the extra parameter `charset` and `characterSet` of the extra parameter (ENV: TYPEORM_DRIVER_EXTRA)
> 
> > 
> 
> > ```ts
> 
> > import {createDatabase} from "typeorm-extension";
> 
> > 
> 
> > (async () => {
> 
> >     await createDatabase({ifNotExist: true});
> 
> >    
> 
> >     await dropDatabase({ifExist: true});
> 
> > 
> 
> >     process.exit(0);
> 
> > })();
> 
> > ```
> 
> > 
> 
> > You can also provide the `charset` and `characterSet` as properties for the first parameter to the `createDatabase()` function. F.e
> 
> > 
> 
> > * postgres
> 
> > 
> 
> > ```ts
> 
> > createDatabase({ifNotExist: true, characterSet: "UTF8"});
> 
> > ```
> 
> > 
> 
> > * mysql
> 
> > 
> 
> > ```ts
> 
> > createDatabase({ifNotExist: true, charset: "utf8mb4_general_ci", characterSet: "utf8mb4"});
> 
> > ```
> 
> > 
> 
> > If you have any questions or concerns feel free to contact me or contribute to the codebase on github https://github.com/Tada5hi/typeorm-extension/issues :)
> 
> 
> 
> Be careful about using this library on production, any unwanted changes in the library can wipe out your database!

This can happen literally with any open source library, even with this one 😅. To be safe check file changes on upgrading to a new version of any library you use.

**Comment by EbolaNerd** [comment]
Not having this feature in TypeORM especially annoying when using docker. With Sequelize you simply execute **npx sequelize db:create && npx sequelize db:migrate** as part of the deploy/startup routine.

**Comment by hassanmehdi98** [comment]
Why is this issue closed? such a nice feature to have, it would help automate the new environment deployments.

**Comment by tada5hi** [comment]
Donnu,but you can use: https://github.com/tada5hi/typeorm-extension
