### ISSUE TITLE
`SqlServerConnectionOptions` interface is missing property `options.trustServerCertificate`

### ISSUE THREAD

**Issue by doubliez** [typeorm/typeorm#8093]
### Expected Behavior

The [`SqlServerConnectionOptions`](https://github.com/typeorm/typeorm/blob/0.2.37/src/driver/sqlserver/SqlServerConnectionOptions.ts#L115) interface should accept `options.trustServerCertificate` (boolean) which is a valid connection option in node-mssql.

### Actual Behavior

The interface doesn't have this property so I need to specify a custom type or bypass type checking on the `options` object.

### Steps to Reproduce

The following code won't compile because `trustServerCertificate` is an unknown property.

```typescript
import { createConnection } from 'typeorm';

createConnection({
    type: 'mssql',
    options: {
        trustServerCertificate: true
    }
});
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 14.17.5  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.37  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
Couldn't hurt to add this but you can pass the option in `extra`

**Comment by doubliez** [comment]
Right, it looks like `options` and `extra` are used the same way then? The only difference is that `extra` is not typed.

A lot (most?) of the connection options are already typed in the `options` object, for example `encrypt` is there, which is closely related to `trustServerCertificate`. So it makes sense to add it :)

For now I'll use the `extra` field to pass that, it works fine indeed.

**Comment by imnotjames** [comment]
I believe it wasn't there because we only handled the old mssql node library.

**Comment by Aksh-Bansal-dev** [comment]
I would like to work on this issue but I am not sure how to do it.
