### ISSUE TITLE
Issue building PostgreSQL array in query

### ISSUE THREAD

**Issue by martinlehoux** [typeorm/typeorm#8094]
## Issue Description

Hello there! I think I encountered an issue while using PostgreSQL array field

### Expected Behavior

Imagine a simple table
```
   Column   |                Type                | Collation | Nullable |      Default       
------------+------------------------------------+-----------+----------+--------------------
 id         | uuid                               |           | not null | uuid_generate_v4()
 days       | date[]                             |           | not null | 
```
With some data in it
```
                  id                  |          days           
--------------------------------------+-------------------------
 236d9921-76ca-4b6a-bae7-022ea17734db | {2021-08-16,2021-08-17}
 f019b863-433c-42ad-af83-adbf85e8af67 | {2021-08-14}
(2 rows)
```
Created from the following Entity
```ts
@Entity()
export class MyEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('date', { array: true })
  days: Date[];
}
```

Given an array of days, I want to find any entity that has at least a day in this array:
```ts
const days = ['2021-08-15'];
const query = repository
      .createQueryBuilder('my_entity')
      .andWhere(`my_entity.days && '{:...days}'`, { days })
```

I expect to build this query (which works in psql)
```
select * from my_entity where days && '{2021-08-15}';
```

### Actual Behavior

It looks like the spread operator is interpreted by TypeORM, but then values are not interpolated:

```
console.log(query.getQueryAndParameters());
[
      `SELECT ... FROM "my_entity" WHERE "my_entity"."days" && '{$1}'`,
      [ '2021-08-15' ]
]


console.log(query.getSql());
SELECT ... FROM "my_entity" WHERE "my_entity"."days" && '{$1}'
```

### Steps to Reproduce

> See ExpectedBehavior

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Ubuntu 21.04      |
| Node.js version     | 14.17.3  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.37  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
This is not a bug.

> It looks like the spread operator is interpreted by TypeORM, but then values are not interpolated:

Interpolation is not what we do here.  We use parameterized queries.

https://node-postgres.com/features/queries

> If you are passing parameters to your queries you will want to avoid string concatenating parameters into the query text directly. This can (and often does) lead to sql injection vulnerabilities. node-postgres supports parameterized queries, passing your query text unaltered as well as your parameters to the PostgreSQL server where the parameters are safely substituted into the query with battle-tested parameter substitution code within the server itself.

This would be closer to what you want:

```
const days = ['2021-08-15'];
const query = repository
      .createQueryBuilder('my_entity')
      .andWhere(`my_entity.days && :days`, { days })
```

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
