### ISSUE TITLE
Migration run says: table exists - But not exists really

### ISSUE THREAD

**Issue by wisi-treinta** [typeorm/typeorm#8098]
## Issue Description

Hi guys, I need help with the command typeorm migration:run. When I run my migrations created, some tables not working because the error says, **_ER_TABLESPACE_EXISTS: Tablespace '`my-space`.`my-table`' exists_** ... but on my db that table not exists.

### Expected Behavior
I think that command should recognize really created tables on DB.

### Actual Behavior

The migrations not complete successfully.

- My application was created with nestjs and typescript
- On my package.json I have some scripts to help run the commands easier.
- My DB was created with docker.
- The typeorm version "^0.2.36".
- Personal lib to import some constants related to names.

<img width="854" alt="Captura de Pantalla 2021-08-18 a la(s) 10 18 18 p  m" src="https://user-images.githubusercontent.com/86269744/130002242-5efba2f5-5f8e-482e-93fe-b70220c1b8d9.png">
<img width="963" alt="Captura de Pantalla 2021-08-18 a la(s) 10 13 19 p  m" src="https://user-images.githubusercontent.com/86269744/130001791-c9f1067a-6155-42e3-a000-4df95859853c.png">
<img width="963" alt="Captura de Pantalla 2021-08-18 a la(s) 10 14 07 p  m" src="https://user-images.githubusercontent.com/86269744/130001851-6251598a-f2f6-4e7f-a755-1ca0e9032c3a.png">
<img width="843" alt="Captura de Pantalla 2021-08-18 a la(s) 10 20 17 p  m" src="https://user-images.githubusercontent.com/86269744/130002423-66106dac-b60e-4fb5-98dd-ed3f502c8ec8.png">
<img width="843" alt="Captura de Pantalla 2021-08-18 a la(s) 10 23 23 p  m" src="https://user-images.githubusercontent.com/86269744/130002686-7b2dae35-573d-4e9a-8fa6-f9b2365d4752.png">
<img width="843" alt="Captura de Pantalla 2021-08-18 a la(s) 10 24 05 p  m" src="https://user-images.githubusercontent.com/86269744/130002751-1f6cbcee-a228-48f8-9cc9-77afa75e5a4a.png">
<img width="843" alt="Captura de Pantalla 2021-08-18 a la(s) 10 24 36 p  m" src="https://user-images.githubusercontent.com/86269744/130002783-71d3edf2-f61b-4e01-bcd2-0b3f74052b71.png">
<img width="843" alt="Captura de Pantalla 2021-08-18 a la(s) 10 25 34 p  m" src="https://user-images.githubusercontent.com/86269744/130002856-09bf8ffc-683d-4c3a-b6ef-eecc81de1329.png">
<img width="843" alt="Captura de Pantalla 2021-08-18 a la(s) 10 26 00 p  m" src="https://user-images.githubusercontent.com/86269744/130002885-7ad39b1e-17a5-41ce-8eb2-6816034eb784.png">
<img width="843" alt="Captura de Pantalla 2021-08-18 a la(s) 10 26 16 p  m" src="https://user-images.githubusercontent.com/86269744/130002902-d4470f5e-3c8e-4367-8fee-742ae2d8c8a2.png">

**Comment by imnotjames** [comment]
This seems like a support request rather than a bug report.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
