### ISSUE TITLE
Unique Columns

### ISSUE THREAD

**Issue by caffinatedmonkey** [typeorm/typeorm#81]
The documentation for [`persist()`](https://typeorm.github.io/entity-manager.html#api.entityManager.persist) says:

> Persists (saves) all given entities in the database. If entities do not exist in the database then inserts, otherwise updates.

If I have:

```
@Table("departments")
export class Department {
	@PrimaryGeneratedColumn()
	id: number;

	// This column is unique. 
	@Column()
	identifier: string;

	// ...
}

```

and schema:

```
CREATE TABLE departments (
	id          INTEGER PRIMARY KEY AUTOINCREMENT,
	identifier  TEXT NOCASE,
	-- ...
	UNIQUE(identifier)
);
```

then `connection.entityManager.persist(department)` fails, throwing an error, due to the unique constraint being violated.

**Comment by pleerock** [comment]
sorry but I didn't understand what is a problem here?

**Comment by caffinatedmonkey** [comment]
My bad, what I meant to say was: If I create and persist two department objects:

    let dept1 = new Department();
    dept1.identifier = "1020";
    // set other properties ...
    db.entityManager.persist(dept1);

    let dept2 = new Department();
    dept2.identifier = "1020";
    // set other properties ...
    db.entityManager.persist(dept2);

the second persist should update `dept1` but it doesn't. It's probably because `dept1 != dept2`. My bad.

This isn't an issue. I need to stop late night coding.
