### ISSUE TITLE
Postgres migration generator fails to detect changes on 0.2.37

### ISSUE THREAD

**Issue by salieri** [typeorm/typeorm#8102]
### Expected Behavior
`typeorm migration:generate -n name` should generate migration files

### Actual Behavior
`typeorm migration:generate -n name` does not generate migration files and outputs:

```
No changes in database schema were found - cannot generate a migration. To create a new empty migration use "typeorm migration:create" command" instead.
```

*Uneducated guess of cause:*

There seems to be a mismatch in the values returned by `RdbmsSchemaBuilder.getTablePath()`. In some cases with `postgres` driver, the function returns the table path with schema (e.g. `public.my_table`), in other cases it's returned without (e.g. `my_table`). This prevents changes in entities from being detected.

For example:
https://github.com/typeorm/typeorm/blob/master/src/schema-builder/RdbmsSchemaBuilder.ts#L493

### Steps to Reproduce

You can reproduce this bug by cloning the following repository and following the steps in its README:
https://github.com/salieri/typeorm-generator-bug

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  MacOS 11.5        |
| Node.js version     | 14.17.0  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.37  | 
| Pg version | 8.7.1 |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by haggholm** [comment]
This has been happening for some time. We’ve had to pin the TypeORM version in one project to 0.32.2.

**Comment by salieri** [comment]
Probably duplicate of #7867

**Comment by imnotjames** [comment]
This should be fixed in the next release.  This can be confirmed in the latest dev build - `0.2.38-dev.22676a0`
