### ISSUE TITLE
Using queryBuilder with 2D arrays generates wrong SQL query

### ISSUE THREAD

**Issue by unreadable** [typeorm/typeorm#8108]
### What was unclear or otherwise insufficient?

I'm trying to perform a conditional UPDATE query based on a 2D array that should look like this:

`UPDATE table_name SET head = 0  WHERE head = 1 AND (val1, val2) IN (('?', '?'), ('?', '?'), ('?', '?'));`

This is what I got so far but it seems to generate wrong SQL query:

```
            .createQueryBuilder()
            .update(Entity)
            .set({ head: false })
            .where('is_head = 1 AND (val1, val2) IN (:...ids)', { ids: [[5,6], [7, 9]] })
```

Couldn't really find something helpful in the docs, is this actually possible with the mysql2 driver?

**Comment by tzahush** [comment]
Can you explain exactly what are you trying to query and how?

What type of database?
What type of column?
What is the condition you are looking to achieve?

Thanks.
