### ISSUE TITLE
Migrations generation incorrect on Oracle when connection's schema is not equal to user's schema

### ISSUE THREAD

**Issue by adetante** [typeorm/typeorm#8109]
### Actual Behavior

With Oracle, schema generation is incorrect when the configuration uses a different schema than the user's.
For example, FOREIGN KEYS are not generated with this kind of configuration:

```js
{
  type: 'oracle',
  port: 1521,
  username: 'MY_USER',
  password: '******',
  entities: [ /* ... */],
  migrationsRun: true,
  synchronize: false,
  schema: 'MY_SCHEMA',
  connectString: '***:1521/***',
  cli: {
    migrationsDir: 'migrations',
  },
  migrations: ['dist/migrations/*.js'],
};
```
### Analyze

With the configuration described above, the generation of FOREIGN KEYS is not done because [of this line]( https://github.com/typeorm/typeorm/blob/master/src/schema-builder/RdbmsSchemaBuilder.ts#L684): 

```ts
protected async createForeignKeys(): Promise<void> {
  for (const metadata of this.entityToSyncMetadatas) {
    const table = this.queryRunner.loadedTables.find(table => this.getTablePath(table) === this.getTablePath(metadata));
    if (!table)
      continue;
```

The table is not found, because `metadata` has a table name prefixed by schema name, but `this.getTablePath(table)` returns the table's name without schema.

This seems to be related to [this piece of code](https://github.com/typeorm/typeorm/blob/master/src/schema-builder/table/Table.ts#L327): is it normal that in this line the schema is ignored?
### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | yes            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
This should be fixed in the next release.  This can be confirmed in the latest dev build - `0.2.38-dev.22676a0`
