### ISSUE TITLE
[Bug] Compiling and Package breaks in new clone

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#811]
Hi, just cloned the project to test a few changes, but before that i tried compiling, and also packaging and none of those worked, here's the command i ran:
```sh
yarn && yarn setup:config && yarn compile
```

That installs all deps with yarn, create the base `ormconfig.json` and should compile with TSC, however the result is this:
![image](https://user-images.githubusercontent.com/9698639/29883062-adde897c-8d74-11e7-9181-e6396d4dc5d8.png)

I think it's complaining by typings, same happens with `npm run package` equivalent:
![image](https://user-images.githubusercontent.com/9698639/29884047-c4bc46a4-8d77-11e7-9862-21dafa075397.png)

However i've also cloned the package as a SubModule to my project and when i import directly from `src` folder i get many other issues which makes me think i have to wait until i can package.

**Comment by luchillo17** [comment]
Ok so it does package, it just complains for typings, but the thing is that using it from SubModule gives this:
![image](https://user-images.githubusercontent.com/9698639/29885181-86983cc6-8d7b-11e7-9a4a-506d7a794779.png)
It's like if it couldn't detect the parent `pg` install, i'll try with npm link and installing `pg` in the SubModule itself.

**Comment by luchillo17** [comment]
Ok with npm link inside the SubModule works fine, which means i have to keep using `npm package`, at least as SubModule i can commit the specific `commit`, work in changes and test in my project those changes.

**Comment by pleerock** [comment]
@Ostrzy do you think your PR fixes this issue?

**Comment by Ostrzy** [comment]
@pleerock I believe so - I had exactly the same errors regarding `decorator/Index.ts` and `MongoEntityManager.ts`. First commit in my PR fixed them for me.

**Comment by pleerock** [comment]
@luchillo17 can you please check it and close it if you fixed it

**Comment by luchillo17** [comment]
TSC errors are gone, but Package got's a new one:
![image](https://user-images.githubusercontent.com/9698639/30005725-5102d4be-90ae-11e7-8635-3249f2ad9199.png)

**Comment by luchillo17** [comment]
Using `src` directly gives a lot less errors but still some:
![image](https://user-images.githubusercontent.com/9698639/30005765-5e443cc0-90af-11e7-89a3-fc052ca55049.png)

**Comment by pleerock** [comment]
Regarding to first error, then its strange since there is a `getOwnMetadata` method `Reflect` class of `reflect-metadata` package. Can you tell me what `reflect-metadata` package version you have installed in your node_modules?

Regarding to second error - its webpack-related, right? I don't know why you need webpack on the backend. Yes you are right, `pg` and all other dynamically loaded dependencies cannot be installed if you don't need them. Probably you need to configure your webpack to ignore those dependencies.

**Comment by luchillo17** [comment]
Since first one is from inside TypeORM, i'm using the one that get's installed by your `package.json`, so my lock file says `0.1.10`.

The second one i guess is Webpack not traducing the `require('pg')` inside the `loadDependencies` function in `PostgresDriver.ts`, even after having `pg` installed in both TypeORM and in my project.

The actual error log is this:
![image](https://user-images.githubusercontent.com/9698639/30026365-36055fb2-9142-11e7-91d6-79eee4b8d380.png)

As for why webpack? Well, mostly because Webpack context and TypeScript in the server side code.

**Comment by pleerock** [comment]
I have `reflect-metadata@^0.1.10` installed and there is `function getOwnMetadata(metadataKey: any, target: Object): any;` line in `standalone.d.ts` so please debug why do you have this compiler error.

For your webpack issue I don't know how to help you, it does not look like there is an issue with typeorm

**Comment by luchillo17** [comment]
The funny thing is that when just compiling with `tsc` it works ok, however it shows that warning when `packaging` the app (it still works as expected though).

**Comment by pleerock** [comment]
Okay thats an issue. Ive pushed a fix
