### ISSUE TITLE
Slack Invite has Expired

### ISSUE THREAD

**Issue by imnotjames** [typeorm/typeorm#8114]
### What was unclear or otherwise insufficient?

The slack link has expired ): What a shame.

Add a new one or find a way to make a permanent one?

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
I created a new invite link & can update the docs with it

https://join.slack.com/t/typeorm/shared_invite/zt-uu12ljeb-OH_0086I379fUDApYJHNuw

**Comment by pleerock** [comment]
I updated this link to never expire. However, there is still a limitation for 2000 users to join.
