### ISSUE TITLE
[Question] Cancel updating/removing an Entity in @beforeRemove/@beforeUpdate. Use same transaction for other queries.

### ISSUE THREAD

**Issue by mattmeye** [typeorm/typeorm#812]
Hi,

i have two questions: 

- how can I stop silently updating or removing an entity by using @beforeUpdate @beforeRemove - (eg. by returning false in the functions, or call event.cancel() ?)

- how can I use the same transaction in events for another queries

my idea:

`
    @AbstractEntity()
    export class ArchiveModel {

        @PrimaryColumn('uuid')
        id: string

        @PrimaryColumn('int')
        version: number

        @Column()
        createdAt: Date

        @Column({ nullable: true })
        updatedAt: Date

        @Column({ nullable: true })
        deletedAt: Date

        @BeforeInsert()
        beforeInsert(event: InsertEvent<ArchiveModel>) {
            if (!event.entity.id) {
                event.entity.id = uuid()
                event.entity.version = 1
                event.entity.createdAt = new Date()
            }
        }

        @BeforeUpdate()
        beforeUpdate(event: UpdateEvent<ArchiveModel>) {
            // stop updating original entity

            // begin transaction

            // only update updatedAt attribute in original entity
            event.databaseEntity.updatedAt = new Date()

            // increase version (optimistic concurrency ?)
            event.entity.version = event.databaseEntity.version + 1

            // remove old updated at information
            event.entity.updatedAt = null
            event.manager.save(event.entity)

            // end transaction
        }

        @BeforeRemove()
        beforeRemove(event: UpdateEvent<ArchiveModel>) {
            // stop removing original entity

            // only update deletetAt in original entity
            event.entity.deletedAt = new Date()
        }
    }`

**Comment by pleerock** [comment]
> how can I stop silently updating or removing an entity by using @beforeupdate @beforeremove - (eg. by returning false in the functions, or call event.cancel() ?)

you can't. And I don't think you'll even be able to do it, don't think its a good idea.

> how can I use the same transaction in events for another queries

subscribers accept event object which holds instance of queryRunner/entityManager. Use that instance to perform all queries inside subscribers/listeners

**Comment by pleerock** [comment]
I hope I answered your question.
