### ISSUE TITLE
DeleteResult not implemented for SQLite3

### ISSUE THREAD

**Issue by jdeg** [typeorm/typeorm#8120]
## Issue Description
I'm having issues with Repository.delete, it successfully removes the entity from the database but it always returns an emtpy value. 

### Expected Behavior

{ raw: [ {id: 1} ], affected: 1 }

### Actual Behavior

// (success or not)

```
query: DELETE FROM "project" WHERE "id" IN (?) -- PARAMETERS: [19]
DeleteResult { raw: [], affected: undefined }
```

### Steps to Reproduce

```typescript
await getRepository(MyRepo).delete(id);
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  macOS Catalina    |
| Node.js version     | v14.15.0  | 
| Typescript version  | typescript@4.1.6  | 
| TypeORM version     | typeorm@0.2.37  | 

### Additional Context

This is a Electron App, I'm using 
- vue-cli-plugin-electron-builder
- sqlite3

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ No, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Paulao80** [comment]
I have the same problem
