### ISSUE TITLE
Default values in mongodb no work

### ISSUE THREAD

**Issue by kaname-png** [typeorm/typeorm#8129]
## Issue Description
When creating a document with mongodb the default values do not work, the value remains as null in the document.

### Expected Behavior

A document with its corresponding default values.

### Actual Behavior

```json
{
  "_id": {
    "$oid": "6129ab8e0685ce7c189e05e3"
  },
  "guild_id": "a",
  "locale": null,
  "prefix": null,
  "version": null
}
```

### Steps to Reproduce

1. Create an entity.
2. Create a column
3. Assign the option `default` to the column options
4. See the document in database.

```typescript
// Entity
import { Entity, ObjectIdColumn, ObjectID, Column, VersionColumn, getMongoRepository } from 'typeorm';

enum Locales {
  ES = 'es-410',
  EN = 'en-us',
}

@Entity({ name: 'settings' })
export class SettingsEntity {
  @ObjectIdColumn()
  _id!: ObjectID;

  @Column('string')
  guild_id!: string;

  @Column('enum', { default: Locales.ES })
  locale!: Locales;

  @Column('string', { default: () => '!' })
  prefix!: string;

  @VersionColumn()
  version!: number;
}

// Code
const repo = getMongoRepository(SettingsEntity);
repo.save(repo.create({ guild_id: 'a' }));
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Windows        |
| Node.js version     | 16.6.1  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.37  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | yes            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✔️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by tzahush** [comment]
Judging by the documentation from https://typeorm.io/#/entities

> default: string - Adds database-level column's DEFAULT value.

I am not a MongoDB Expert but I think there is no 'database-level' default value, therefor I guess its more of a feature request rather then a bug..

**Comment by kaname-png** [comment]
It is still a bug because that property is required in the database, and it may be something not at the database level but it can be at the Typeorm level.

**Comment by tzahush** [comment]
What I am saying is that it is not a bug, but is a feature request.
It is definitely intended to only work on Relationship Databases.

btw under "Are you willing to resolve this issue by submitting a Pull Request?"
You didn't mark any option, please fill that in, thanks.

**Comment by kaname-png** [comment]
@tzahush 

I didn't check that option because I don't know how to implement it in the typeorm code.
