### ISSUE TITLE
sortBy RAND()

### ISSUE THREAD

**Issue by vincentbouillart** [typeorm/typeorm#813]
Hi,
Is it possible use the RAND function ?
i want to use in sql ORDER BY RAND()

When i use addOrderBy('RAND()')

got :  Error: ER_BAD_FIELD_ERROR: Unknown column 'distinctAlias.RAND()_undefined' in 'field list'

**Comment by pleerock** [comment]
Can you provide a complete code example? I checked following and it works:

```ts
        const posts = await connection.createQueryBuilder(Post, "post")
            .orderBy("RAND()")
            .getMany();
```

**Comment by pleerock** [comment]
Closing it because i cannot reproduce it, please update typeorm to latest version and check this issue once again and let me know if you still have this issue.
