### ISSUE TITLE
TreeRepository findDescendants to have pagination capabilities (skip,take)

### ISSUE THREAD

**Issue by y-nk** [typeorm/typeorm#8133]
### The Problem

When calling findDescendants, the [doc](https://orkhan.gitbook.io/typeorm/docs/tree-entities) states:

> findDescendants - Gets all children (descendants) of the given entity. Returns them all in a flat array.

If there's 1 million children, it seems there may be an issue here (not to mention the findDescendantsTree)

### The Solution

Add a `FindOptions<T>` such as: `findDescendants<T>(root: T, options: FindOptions<T>)` so that we can pass `{ skip: number, take: number }`

### Considered Alternatives

Not using the tree repository, and build a query by myself with a joint according to the TreeEntity strategy, but if we arrive at this point i'm wondering why use TreeRepository at all (no blame, just that it's not a suitable alternative that's all).

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by daegiri** [comment]
Any progress made on this feature? I really need this for my projects.

**Comment by y-nk** [comment]
looking at the time of original ticket, i'm.sad to say it looks like it's not going to happen @daegiri - best of luck
