### ISSUE TITLE
How to do a "database per user" separation on typeorm-express node server

### ISSUE THREAD

**Issue by tr0p5** [typeorm/typeorm#814]
Hello, I'm new to typeorm and would like to know if there is an example of this kind of feature working. Or any kind of direction is helpfull.

The problem is that I cannot wrap my mind around the soultions out there. I have a connection where I will find users db information, then typeorm should create a connection to that db and use it only for that user.

How should I proceed? where should I separate and create the connections. My server works for a single connection, how should I deal with the connection pool and secure that connection to a single user?

Appreciate the help, an thanks for the good work.

My server so far:

>createConnection(options).then(async connection => {
>    const app = express();
    app.use(helmet());
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: false }));
    app.use(cors());
    app.use(logger("dev"));
    AppRoutes.forEach(route => {
        app[route.method](route.path, (request: Request, response: Response, next: Function) => {
            route.action(request, response)
                .then(() => next)
                .catch(err => next(err));
        });
    });
    app.use(express.static('public'));
    app.listen(1434);
    console.log("Express application is up and running on port 1434");
}).catch(error => console.log("TypeORM connection error: ", error));

**Comment by pleerock** [comment]
I didn't understand what exact question is. You are saying you want to create a "separate connection for a user". What do you call "user"? Database user or user who make request or whom?

**Comment by tr0p5** [comment]
By user I mean a validated request with a compatible name in the main database.
I want to make the server able to connect to some secundary dynamic database after the server validate some request info. I wish to do that by creating a connection with variable options on the fly and store the connection open for some time. Is something like this possible?

Thanks for the quick feedback. :)

**Comment by pleerock** [comment]
if you want to connect to multiple different databases or even same databases but with multiple database users then you have to create multiple connections:

```ts
const user1Connection = await createConnection({
    user: "user1",
    ....
});
const user2Connection = await createConnection({
    user: "user2",
    ....
});
...
```

**Comment by tr0p5** [comment]
Thanks... I think I got it.
