### ISSUE TITLE
find() throws error while using mongodb

### ISSUE THREAD

**Issue by KrishnaMoorthy12** [typeorm/typeorm#8146]
## Issue Description

While using **MongoDB**, the `repository.find()` method throws 
```sh 
TypeError: Cannot read property 'prototype' of undefined
```

I found this workaround on StackOverflow:
```typescript 
this.userRepository.createCursor(this.userRepository.find()).toArray();
```
But `createCursor` does not exist on type `Repository`

### Note:

I did a little bit of digging and debugging and figured that it works as expected with version `3.6.11` of MongoDB driver, so I think this must be because of some breaking change introduced with version 4.x

### Expected Behavior

It should find and return all the documents(rows) in the collection(table) as an array.

### Actual Behavior

Error:
```sh
[Nest] 15017  - 08/30/2021, 5:32:47 PM   ERROR [ExceptionsHandler] Cannot read property 'prototype' of undefined
TypeError: Cannot read property 'prototype' of undefined
    at FindCursor.cursor.toArray (/home/krish/github/nest-garbage/src/entity-manager/MongoEntityManager.ts:707:37)
    at MongoEntityManager.<anonymous> (/home/krish/github/nest-garbage/src/entity-manager/MongoEntityManager.ts:97:23)
    at step (/home/krish/github/nest-garbage/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/krish/github/nest-garbage/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/krish/github/nest-garbage/node_modules/typeorm/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to Reproduce

I encountered this bug while using it with nestjs. It might not be possible for me to provide a minimal reproduction repo, but I'm only learning TypeORM as well as Nest JS, so what I'm working on is mostly minimal. 

Repo link: https://github.com/KrishnaMoorthy12/nest-garbage

Breakpoint (enclosed by **):
```typescript
@Injectable()
export class UserService {
  constructor(
    @InjectRepository(User)
    private readonly userRepo: Repository<User>,
  ) {}

  getAllUsers() {
    **return this.userRepo.find();**
  }
}
```

I will try to put together an MCVE if you still want it (Please leave a comment without closing the issue).

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    GNU/ Linux      |
| Node.js version     |  16.7.0  |
| Typescript version  | 4.3.5  |
| TypeORM version     | 0.2.37  | 
| MongoDB driver   | **4.1.1** |
| mongod version |  4.4.6 |
| Nest JS version   | 8.1.1 |
| nestjs/typeorm version | 8.0.2 |

By mongod, I mean Mongo DB server.

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | **yes**            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

Read the note above for more details regarding the database driver.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

(I'm not entirely sure if I can help, I go to college and I will try my best at my leisure time)

**Comment by JoshWilliams92** [comment]
This is definitely a bug. A temporary work around is to uninstall mongodb and then run npm install mongodb@3

**Comment by JoshWilliams92** [comment]
For the record, when I create a typeORM project via the CLI and select MongoDB, the default version is 3.0.7. Installing MongoDB in a Nest Application will install to the latest version 4.1. When I install MongoDB in the TypeORM project specifying this version I get the following error output in the console:
node_modules/@types/whatwg-url/ts3.9/index.d.ts:155:54 - error TS2694: Namespace 'NodeJS' has no exported member 'TypedArray'.

155 export function percentDecode(buffer: Extract<NodeJS.TypedArray, ArrayLike<number>>): Buffer;
                                                         ~~~~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! typeorm-typescript-mongo-example@0.0.1 start: `tsc && node src/index.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the typeorm-typescript-mongo-example@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Josh\AppData\Roaming\npm-cache\_logs\2021-09-04T19_03_22_999Z-debug.log

**Comment by malegender** [comment]
https://github.com/typeorm/typeorm/blob/0.2.37/src/entity-manager/MongoEntityManager.ts#L687
https://github.com/typeorm/typeorm/blob/02f0bce19d0a55186e815fa5bb2c3d11c2231e5f/src/platform/PlatformTools.ts#L48
`ParentCursor ` is `undefined`, because it return `require("mongodb")` without property `Cursor` in mongodb v. 4
Typeorm use mongodb v.3(it works)
https://github.com/typeorm/typeorm/blob/master/package.json#L98

**Comment by Corky3892** [comment]
Ok getting late here but these workarounds bother me so gone fishing for a fix.

We can easily trace the root of the issue in TypeORM to https://github.com/typeorm/typeorm/blob/master/src/entity-manager/MongoEntityManager.ts line 686.

```Typescript
...
protected applyEntityTransformationToCursor<Entity>(metadata: EntityMetadata, cursor: Cursor<Entity> | AggregationCursor<Entity>) {
        const ParentCursor = PlatformTools.load("mongodb").Cursor; // This is returning undefined using mongodb driver 4+
        const queryRunner = this.mongoQueryRunner;
        cursor.toArray = function (callback?: MongoCallback<Entity[]>) {

...
```

If we compare the mongodb src files in version 3.7 https://github.com/mongodb/node-mongodb-native/blob/3.7/index.js versus 4.2 https://github.com/mongodb/node-mongodb-native/blob/main/src/index.ts (aside from the obvious that the driver has gone TS native). It becomes clear that mongodb 4.2 does not export a "Cursor".

Hacking away at this line inside my node_modules/typeorm/entity-manager/MongoEntityManager "fixes" the issue. Presumably something similar is happening in the repository.

```typescript
var ParentCursor = PlatformTools_1.PlatformTools.load("mongodb").Cursor

// Becomes

var ParentCursor = PlatformTools_1.PlatformTools.load("mongodb").Cursor || PlatformTools_1.PlatformTools.load("mongodb").FindCursor;
```

I'll try and take deeper look at this later in the week and maybe open a pull request.

**Comment by douglas-bernardo** [comment]
> Ok getting late here but these workarounds bother me so gone fishing for a fix.
> 
> We can easily trace the root of the issue in TypeORM to https://github.com/typeorm/typeorm/blob/master/src/entity-manager/MongoEntityManager.ts line 686.
> 
> ```ts
> ...
> protected applyEntityTransformationToCursor<Entity>(metadata: EntityMetadata, cursor: Cursor<Entity> | AggregationCursor<Entity>) {
>         const ParentCursor = PlatformTools.load("mongodb").Cursor; // This is returning undefined using mongodb driver 4+
>         const queryRunner = this.mongoQueryRunner;
>         cursor.toArray = function (callback?: MongoCallback<Entity[]>) {
> 
> ...
> ```
> 
> If we compare the mongodb src files in version 3.7 https://github.com/mongodb/node-mongodb-native/blob/3.7/index.js versus 4.2 https://github.com/mongodb/node-mongodb-native/blob/main/src/index.ts (aside from the obvious that the driver has gone TS native). It becomes clear that mongodb 4.2 does not export a "Cursor".
> 
> Hacking away at this line inside my node_modules/typeorm/entity-manager/MongoEntityManager "fixes" the issue. Presumably something similar is happening in the repository.
> 
> ```ts
> var ParentCursor = PlatformTools_1.PlatformTools.load("mongodb").Cursor
> 
> // Becomes
> 
> var ParentCursor = PlatformTools_1.PlatformTools.load("mongodb").Cursor || PlatformTools_1.PlatformTools.load("mongodb").FindCursor;
> ```
> 
> I'll try and take deeper look at this later in the week and maybe open a pull request.

Oh man thank's!

**Comment by Corky3892** [comment]
Ok pull request is in: https://github.com/typeorm/typeorm/pull/8412

**Comment by loagencydev** [comment]
Looks like this issue is still happening in `4.2.2`!

```
"stacktrace": [
            "TypeError: Cannot read properties of undefined (reading 'prototype')",
            "    at FindCursor.cursor.toArray (/app/src/entity-manager/MongoEntityManager.ts:704:37)",
            "    at MongoEntityManager.<anonymous> (/app/src/entity-manager/MongoEntityManager.ts:119:20)",
            "    at step (/app/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)",
            "    at Object.next (/app/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)",
            "    at fulfilled (/app/node_modules/typeorm/node_modules/tslib/tslib.js:114:62)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
```

the part that causing the issue:

```
const [schemas, count] = await this.schemaRepository.findAndCount({
			skip || 0,
			take || 0,
		});
```

**Comment by matthew-plusprogramming** [comment]
Also getting this error with mongo `4.2.2`

```ts
return User.findOne({ where: { email } }).then(user => {});
```

```
TypeError: Cannot read property 'prototype' of undefined
    at FindCursor.cursor.toArray (/home/matthew-plusprogramming/WorkingSync/typescript-graphql-server-template/src/entity-manager/MongoEntityManager.ts:704:37)
    at MongoEntityManager.<anonymous> (/home/matthew-plusprogramming/WorkingSync/typescript-graphql-server-template/src/entity-manager/MongoEntityManager.ts:189:46)
    at step (/home/matthew-plusprogramming/WorkingSync/typescript-graphql-server-template/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/matthew-plusprogramming/WorkingSync/typescript-graphql-server-template/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/matthew-plusprogramming/WorkingSync/typescript-graphql-server-template/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by donkey-donkey** [comment]
thanks for the work. is there any update?

**Comment by Corky3892** [comment]
> thanks for the work. is there any update?

I should be able to take a fresh look here next week. What I can tell you without looking at all is that while I was testing the 'fix' for #8412 is that your MongoDB version and mongo driver version are co-dependent. If you are running MongoDB 3 you still need the driver version 3.7. If you are running MongoDB 4 then you should be able to use the driver version 4.2.

**Comment by Jmallone** [comment]
@Corky3892 Thanks 

> If you are running MongoDB 3 you still need the driver version 3.7. If you are running MongoDB 4 then you should be able to use the driver version 4.2.

This works for me :smile:

**Comment by danielehrhardt** [comment]
Any Update here?

**Comment by KrishnaMoorthy12** [comment]
> Any Update here?

Yes, https://github.com/typeorm/typeorm/pull/8412
This was fixed last February, but I haven't tried it. 
Release notes: https://github.com/typeorm/typeorm/releases/tag/0.2.42

**Comment by danielehrhardt** [comment]
> > Any Update here?
> 
> Yes, https://github.com/typeorm/typeorm/pull/8412
> This was fixed last February, but I haven't tried it. 
> Release notes: https://github.com/typeorm/typeorm/releases/tag/0.2.42

Then close the issue.

**Comment by Media-library641** [comment]
> Ok pull request is in: [#8412](https://github.com/typeorm/typeorm/pull/8412)





https://thermonuclear-nehemiah.github.io/Q5BARA7R/
