### ISSUE TITLE
Revert deprecation of InsertQueryBuilder.onConflict

### ISSUE THREAD

**Issue by botre** [typeorm/typeorm#8168]
### The Problem

InsertQueryBuilder.onConflict has been marked as deprecated.

There is a comment telling to "Use orIgnore or orUpdate".

The deprecated method (signature `onConflict(statement: string)`) is much more flexible, since you have full control over the statement, whereas the alternative methods are rather constrained (you can choose which columns you'd like to update on conflict but not HOW to update those columns).

Columns should be updatable in multiple ways on conflict: concatenation, incrementation, interpolation, etc...
This is possible with onConflict. Unfortunately, this isn't possible with the current implementations of orIgnore and orUpdate.

### The Solution

Revert the deprecation.

### Alternative solutions

- The `orIgnore` and `orUpdate` could be refactored to be more flexible

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.

**Comment by enniogonzalez** [comment]
@botre any update on this?

**Comment by pleerock** [comment]
in order to resolve this issue we must ask author of these changes about the motivation and suggest alternative solution.

**Comment by wanton7** [comment]
Both `onConflict` and `orUpdate` seem to be deprecated, what should I use instead?

**Comment by karladler** [comment]
> Both `onConflict` and `orUpdate` seem to be deprecated, what should I use instead?

In my understanding only the function taking an object as argument is deprecated, while the version with this signature is supposed to work:

> orUpdate(overwrite: string[], conflictTarget?: string | string[]): this;

**Comment by Ginden** [comment]
I think it's related to WebStorm/Intelij IDEA bug - if one function/method signature is deprecated, WebStorm will mark all as deprecated.

**Comment by pleerock** [comment]
if so, I suggest to find and ping the author of these changes - ask the motivation of these changes and propose a new & better solution.

**Comment by eysi09** [comment]
@botre, did you make any progress here? 

I'm bumping into the exact same issue where I need to revert to using the deprecated `onConflict` function because the new `orUpdate` function is too limited (I need to use a `WHERE` clause with the `DO UPDATE SET` statement).
