### ISSUE TITLE
New Snake Case Implementation introduced in 0.2.37 Breaks Table Name (in my case Fail2Ban)

### ISSUE THREAD

**Issue by meganoob1337** [typeorm/typeorm#8173]
## Issue Description
The new SnakeCase Converter Function introduced in 0.2.37 is a Breaking Change

### Expected Behavior
Our Entity "Fail2Ban" expects the Table "fail2_ban" to be created ( as its written in our migration and our database schema to date)

### Actual Behavior
"Fail2Ban" gets converted to "fail2ban" and thus breaking our application as the migration created fail2_ban but the application searches for fail2ban

### Steps to Reproduce

Create an Entity Fail2Ban in v0.2.24 and add a migration,
update to v0.2.37
Application Breaks 

### Additional Context

see commit https://github.com/typeorm/typeorm/commit/eb680f99b74c335556d23016264fcf1ea6ce1d6f

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

We are staying at 0.2.24 for the time beeing

**Comment by fkammer** [comment]
We ran into the same issue migrating from `0.2.31` to `0.2.37`.

I don't understand how this was released as a patch version. Changing a function used for table name generation obviously has a great potential of breaking existing installations.

**Comment by meganoob1337** [comment]
I just checked out the Master to see if i can fix it, it seems it got fixed with: https://github.com/typeorm/typeorm/pull/8111
It is not Released yet, but in .38 it should be fixed as i can see it @fkammer
