### ISSUE TITLE
SelectQueryBuilder Parse Error

### ISSUE THREAD

**Issue by dghg** [typeorm/typeorm#8176]
## Issue Description
Parse Error when using `SelectQueryBuilder.andWhere`
### Expected Behavior

Execute SQL normally.

### Actual Behavior

```
QueryFailedError: column "lorem" does not exist
```

I used the "lorem" as a value of where cluase , not key.
### Steps to Reproduce

1. Execution of SelectQueryBuilder.getXX() function ( This works well )
```
const qb = repository.createQueryBuilder("alias");
...
...
qb.andWhere('alias.id = 3');
qb.getMany();
```

2. Execution of SelectQueryBuilder.getXX() function ( This isnt working. )
```
const qb = repository.createQueryBuilder("alias");
...
...
qb.andWhere('alias.name = lorem');
qb.getMany();
```

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Mac     |
| Node.js version     | 12.18.4  | 
| Typescript version  | 4.4.2  | 
| TypeORM version     | 0.2.37  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by carlocorradini** [comment]
@dghg can you post the full query and the *alias* entity?

**Comment by dghg** [comment]
@carlocorradini 

1. Entity
```
class Entity {
  @Column(..)
	id: number;
  @Column(..)
  title: string;
}
```

2. QueyBuilder
```
const qb = this.repo.createQueryBuilder('ent');
```

3. Full Query ( work properly )

```
qb = qb.andWhere('account.id = 3');
console.log(qb.getSql());
return await qb.getMany();
```

4. Full Query ( do not work properly )
```
qb = qb.andWhere('account.title = rawstring');
console.log(qb.getSql());

return await qb.getMany();
```

4 throws `QueryFailedError: column "rawstring" does not exist` error

Is it just my syntax error? i don't use parameterized value but raw string. but it work properly in integer value...

**Comment by carlocorradini** [comment]
Try this:
```const result = await qb.andWhere(`account.title = 'rawstring'`).getMany();```
Note the usate of ' in combination with `

**Comment by carlocorradini** [comment]
@dghg It worked?
