### ISSUE TITLE
Developed a helper library, in the compilation level, for the next version

### ISSUE THREAD

**Issue by samchon** [typeorm/typeorm#8184]
https://github.com/samchon/safe-typeorm

I've awaited next version of the `typeorm` for many years, and I can't wait no more.

So I've decided to implement the next version by myself. I'd wanted to contribute to this `typeorm` after the next version implementation has been completed, but it was not possible by critical change on the relationship definition like `Has.OneToMany` or `Belongs.ManyToOne`. Therefore, I've published the next version as a helper library of this `typeorm`.

Name of the helper library is [safe-typeorm](https://github.com/samchon/safe-typeorm) and this helper library makes below things possible. 

  - When writing SQL query,
    - Errors would be detected in the **compilation** level
    - **Auto Completion** would be provided
    - **Type Hint** would be supported
  - You can implement **App-join** very conveniently
  - When **SELECT**ing for **JSON** conversion
    - **App-Join** with the related entities would be automatically done
    - Exact JSON **type** would be automatically **deduced**
    - The **performance** would be **automatically tuned**
  - When **INSERT**ing records
    - Sequence of tables would be automatically sorted by analyzing dependencies
    - The **performance** would be **automatically tuned**

As I've mentioned, I couldn't send any PR to this `typeorm` because of critical change on the relationship definition. However, if you can endure the change, upper features be all possible. Therefore, I want to ask to the `typeorm` developers to accept the change or not. If you accept, `typeorm` will complete the next version. Otherwise reject, the [safe-typeorm](https://github.com/samchon/safe-typeorm) would be left as helper library.

![Safe Query Builder](https://raw.githubusercontent.com/samchon/safe-typeorm/master/assets/demonstrations/safe-query-builder.gif)

**Comment by samchon** [comment]
Anyone who knows an issue that referencing next version upgrade of `typeorm`? 

I forgot the issue number, therefore mis-linked to wrong issue number.

**Comment by ganshiqingyuan** [comment]
#3267  ？

**Comment by samchon** [comment]
@ganshiqingyuan Miss linked

**Comment by samchon** [comment]
> #3267 ？

Miss linked

**Comment by samchon** [comment]
> #3251 ？

@ganshiqingyuan miss linked
