### ISSUE TITLE
Since version 0.2.32 I have "No changes in database schema were found - cannot generate a migration"

### ISSUE THREAD

**Issue by alex-kovalchuk** [typeorm/typeorm#8200]
### Expected Behavior

Generate a new migration when I change entities.

### Actual Behavior

Since version 0.2.32 I have "No changes in database schema were found - cannot generate a migration" when I execute the command "migration:generate".

### Steps to Reproduce

1. Change typeorm version to 0.2.32, 0.2.33 or 0.2.37 (latest)
2. Run "migration:generate"

Result: "No changes in database schema were found...."

*Then*

1. Change typeorm version to 0.2.31 or 0.2.25
2. Run "migration:generate"

Result: "Migration /..../migrations/1632002157691-Test.ts has been generated successfully"

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Debian 10         |
| Node.js version     | 14.17.4  | 
| Typescript version  | 4.4.3  | 
| TypeORM version     | 0.2.32  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `postgres`           | yes            |

**Comment by imnotjames** [comment]
This should be fixed in the latest release. (`0.2.38`)
