### ISSUE TITLE
Server side SQL.js support especially for Electron's main process

### ISSUE THREAD

**Issue by kaorun343** [typeorm/typeorm#8201]
### The Problem

Using SQLite3 on Electron's main process is so stressful.
It's well known that the sqlite3 package contains native modules, so we need to rebuild it for Electron, which we have to prepare for it by installing some libraries.

I know TypeORM supports SQL.js but the current implementation only supports to use it on web browser.

### The Solution

It makes me happy to use SQL.js on server side.

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | yes            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
Are you sure it only supports it in the browser?  We run tests against sqljs in the CI which isn't a browser.

**Comment by kaorun343** [comment]
Oh, I see. Thanks for your reply!
https://github.com/typeorm/typeorm/blob/master/src/driver/sqljs/SqljsConnectionOptions.ts#L36-L40
