### ISSUE TITLE
Timescale DB Support

### ISSUE THREAD

**Issue by all2pie** [typeorm/typeorm#8202]
## Feature Description

Please add support for Timescale db.

If it is already supported then please add it in the documentation.

Is is currently supported by sequelize: 

[Timescale Db](https://docs.timescale.com/timescaledb/latest/quick-start/node/#prerequisites)

### Relevant Database Driver

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by iam4x** [comment]
TimescaleDB is just an extension of PostgreSQL which is already supported by TypeORM.
Just follow the docs for PostgreSQL :+1:

**Comment by all2pie** [comment]
@iam4x I know that and i have successfully connected to it but i do not use migrations so i need someway to create _hyper-tables_ and also it would be good to have support for Timescale function, but i can do raw queries for that so that wont be an issue.

**Comment by paltaa** [comment]
You can create hypertables in typeOrm:

import { MigrationInterface, QueryRunner } from 'typeorm';

```
export class TradesInit1640705305983 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS trades(
            id              serial,
            mongo_id        varchar(24) NOT NULL,
            date            TIMESTAMPTZ NOT NULL,
            symbol          varchar(30) NOT NULL,
            price           BIGINT NOT NULL,
            amount          BIGINT NOT NULL,
            total_cost      BIGINT NOT NULL
        );`);
    await queryRunner.query(
      `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;`,
    );
    await queryRunner.query(`SELECT create_hypertable('trades', 'date');`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE trades;`);
    await queryRunner.query(`DROP EXTENSION timescaledb;`);
  }
}

```

**Comment by danfield73** [comment]
What I think we need is Hypertable options available at the Entity level.

Perhaps a simple option within Entity to mark as a hypertable... we'd also need to consider other options (Compression, Partitioning options etc).

Hyperfunction could be implemented as SQL with queryRunner for now - open to look at other implementation options.

**Comment by Nosfistis** [comment]
I guess hypertables can only be resolved with custom queries.

**Comment by matte0080** [comment]
> I guess hypertables can only be resolved with custom queries.

Can you give me an example?

**Comment by matte0080** [comment]
Some news about this issue/request?

**Comment by wiatrM** [comment]
Any updates? It would be great to add this to TypeORM

**Comment by treecon** [comment]
Any updates? @akindo is right about the primary key issue. Working with both TypORM and TimescaleDB seems like a serious hassle. It would be great if TypeORM could provide support for Hypertables.

**Comment by ianzonja** [comment]
Here is an example that worked for me:

**Comment by tqthuan17** [comment]
any updates?

**Comment by tgirotto** [comment]
I have managed to add a composite primary key by 

1) adding the @PrimaryColumn decorator to two different properties: grid_id and created_at

``````

2) adding a manual query to the generated migration that creates the hypertable

```
export class AddingEntitiesToPostgres1722863691413 implements MigrationInterface {
  name = 'AddingEntitiesToPostgres1722863691413';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE TABLE "grid_forecast_snapshot_1_h" ("created_at" TIMESTAMP NOT NULL, "grid_id" integer NOT NULL, "grid_name" character varying, "organization_id" integer, "organization_name" character varying, "updated_at" TIMESTAMP NOT NULL, "period_start" TIMESTAMP NOT NULL, "solar_yield_kwh" double precision, "consumption_kwh" double precision, CONSTRAINT "PK_29f61f5cfe8dc2cbd15eceda457" PRIMARY KEY ("created_at", "grid_id"))');
    await queryRunner.query('SELECT create_hypertable(\'grid_forecast_snapshot_1_h\',\'created_at\');');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "grid_forecast_snapshot_1_h"');
    //   cannot drop hypertable
  }

}

```
3) adding an index to the entity with the same name as the index a hypertable

```
@Index('grid_energy_snapshot_15_min_created_at_idx', [ 'created_at' ])
```

At the end of the process, the typeorm command to generate migrations seems to give no result, which means that the code and the db schema are aligned again.

**Comment by Nathaniael** [comment]
Any updates ? even limited find where support would be really appreciated

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests or work on additional extensions at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.

**Comment by danstarns** [comment]
Hey all, 


@all2pie @paltaa @danfield73 @akindo @Nosfistis @matte0080 @wiatrM @treecon @thuantruong-kite and community...

TimescaleDB open-sourced our early access for our TypeORM integration: 

* https://github.com/timescale/timescaledb-ts

The repo and its published npm packages give you a solution for working with TimescaleDB and TypeORM, along with SQL generation and other tooling to make integrating with the ecosystem seamless.

The best way to get started is to follow our guides:

1. [Getting Started](https://github.com/timescale/timescaledb-ts/blob/main/docs/guides/getting-started.md)
2. [Working with Energy Data](https://github.com/timescale/timescaledb-ts/blob/main/docs/guides/energy-data.md)
3. [Working with Candlesticks](https://github.com/timescale/timescaledb-ts/blob/main/docs/guides/candlesticks.md)

```bash
npm i typeorm @timescaledb/typeorm
```

```diff
import { Entity, Column } from "typeorm";
+ import { Hypertable, TimeColumn } from "@timescalets/typeorm";

@Entity('metrics')
+ @Hypertable({})
export class DeviceMetric {
+ @TimeColumn()
  timestamp!: Date;

  @Column()
  device_id!: string;

  @Column()
  temperature!: number;
}
```

If you are looking for more in-depth examples then follow the two examples we maintain in our source code:

1. [TypeORM Example](https://github.com/timescale/timescaledb-ts/tree/main/examples/node-typeorm)
2. [Sequelize Example](https://github.com/timescale/timescaledb-ts/blob/main/examples/node-sequelize/README.md)

This is an early access release - we’d love your feedback and support!
