### ISSUE TITLE
LessThan(0) fails for decimal numbers

### ISSUE THREAD

**Issue by sjsalonen** [typeorm/typeorm#8203]
## Issue Description

I'm trying to query for negative `amount` values from a Postgres database using TypeORM's `LessThan` FindOperator, but I'm getting a  QueryFailedError, despite using it just like in the documentation. I use these operators for other columns (like dates) and they work just fine, I only get this error with this and other columns of the same type.

`LessThanOrEqual(-1)` fails as well.

`amount` is a non-nullable `numeric(13,4)` column.

To me, based on the docs, this seems like a bug, but it could be something I just don't understand

### Expected Behavior

Expected for the query to return rows that have a negative `amount`

### Actual Behavior

```
QueryFailedError: invalid input syntax for type numeric: "[object Object]"
```

### Steps to Reproduce

This part of the code is where the error comes from

```typescript
const rows = await manager.find(thisEntity, {
    relations: Relations,
    where: { amount: LessThan(0) },
  })
```

Here is that column in the `thisEntity`

```typescript
const decimalStringTransformer: GenericValueTransformer<string | null, number | null> = {
  from: value => {
    return typeof value === 'string' ? parseFloat(value) : null
  },
  to: value => (isDefined(value) ? value.toString() : null),
}

const moneyDbColumn = {
  type: 'decimal',
  precision: 13,
  scale: 4,
  transformer: decimalStringTransformer,
}

@Column(moneyDbColumn)
amount: number
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.7.0  | 
| Typescript version  | 4.4.3  | 
| TypeORM version     | 0.2.35  | 

Tested with TypeORM 0.2.37 as well, same results

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by ticklepoke** [comment]
Hey, did you manage to find a fix for this since you closed it?

**Comment by gyzo** [comment]
@sjsalonen Looks like it still doesn't work. Why did you close it?
