### ISSUE TITLE
@AfterInsert() hides @WebSocketServer() server variable in NestJS 

### ISSUE THREAD

**Issue by JotaStar** [typeorm/typeorm#8206]
## Issue Description

The @WebSocketServer() server: Socket; variable is hidden inside @AfterInsert() subscriber functions

### Expected Behavior

Access to the socket variable in order to emit the new entity generated.

### Actual Behavior

Socket variable defined in class returns undefined ONLY INSIDE decorators of listeners

```
Cannot read property 'emit' of null TypeError: Cannot read property 'emit' of null
```

### Steps to Reproduce

```typescript

import { UseGuards } from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';
import { WebSocketGateway, ConnectedSocket, OnGatewayConnection, OnGatewayDisconnect, OnGatewayInit, WebSocketServer } from '@nestjs/websockets';
import { IBase } from '@shared/interfaces/entities';

import { Socket } from 'socket.io';
import { AfterInsert, BeforeInsert, EventSubscriber, InsertEvent } from 'typeorm';

@EventSubscriber()
@UseGuards(AuthGuard('jwt'))
@WebSocketGateway({
  cors: {
    credentials: true,
    origin: 'http://localhost:4200'
  }
})

export class AppGateway implements OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect {

  @WebSocketServer() server: Socket;

  constructor() {
    console.log('New Instance Of AppGateway');
  }

  afterInit() {
    console.log(this.server); // EXISTS!
  }

  handleConnection(@ConnectedSocket() client: Socket, ...args: any[]) {
    console.log('SOCKET: ' + client.handshake.address);
    console.log('SOCKET: ' + client.handshake.url);
    client.emit('connected', 'CONNECTED');
  }

  handleDisconnect(@ConnectedSocket() client: Socket) {
    console.log(`SOCKET: DISCONNECTED ${client.id}`);
  }

  @AfterInsert()
  afterInsert(event: InsertEvent<IBase>) {
    console.log(`AFTER INSERTED: `, event.entity);

    this.server.emit('newEntity', ['newEntity', event]); // this.server IS UNDEFINED
  }

  @BeforeInsert()
  beforeInsert(event: InsertEvent<IBase>) {
    console.log(`BEFORE ActivityLog INSERTED: `, event.entity);
  }

}
```

### My Environment

Node: v14.17.5
Typescript: 4.3.5
TypeORM: tested in 0.2.37 and 0.3.0-alpha.24
NestJS: 8.0

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ No, I don’t have the time, but I can support (using donations) development.

**Comment by spotykatch** [comment]
Can you please give us your ormconfig.json?
If you're using `"subscribers"` param in your ormconfig.json, then this class is used by Typeorm and Nest separately. Then the error you get is from the Typeorm instance. Typeorm doesn't know about Nest decorators.
I think you'll have to separate this class to getaway, service, and subscriber. 
You can use subscribers like that.
```ts
import { Injectable } from '@nestjs/common';
import { AppService } from 'src/order/order.service';
import { Connection, EntitySubscriberInterface, InsertEvent } from 'typeorm';

@Injectable()
export class AppSubscriber implements EntitySubscriberInterface {
  constructor(
    private readonly connection: Connection,
    private readonly service: AppService,
  ) {
    this.connection.subscribers.push(this);
  }

  // @AtrerInser is not needed
  async afterInsert(event: InsertEvent<BankAction>) {
    await this.service.doStuff({});
  }
}
```
You'll need to delete `"subscribers": "[path/to/yor/subscribers{.ts,.js}]"`
I guess `Socket` can be injected in service. Don't really know.

**Comment by Ginden** [comment]
This is because TypeORM instatiates second instance of `AppGateway` class.

[FAQ documents how to use custom DI containers with TypeORM](https://github.com/typeorm/typeorm/blob/3a694dd3e99699e7284709c53967a5dfcb1e1806/docs/faq.md#how-to-use-typeorm-with-a-dependency-injection-tool).
