### ISSUE TITLE
Typeorm does not pick up entity on migrations creation in nx workspace 

### ISSUE THREAD

**Issue by CodingSpiderFox** [typeorm/typeorm#8216]
## Issue Description
When running `npm run migration:create -- -n CreateUserTable` in the root folder of the nx workspace I created, the `CREATE TABLE` query in the resulting migration typscript file is missing
### Expected Behavior

The migration typescript contains all necessary queries based on the given entities

### Actual Behavior
The resulting typescript file looks like this

```
import {MigrationInterface, QueryRunner} from "typeorm";

export class CreateUserTable1632675564864 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
```

### Steps to Reproduce

Clone the sample repo I made: https://github.com/CodingSpiderFox/nx-typescript-typeorm-boilerplate

1. run `npm install` in the root of the repo
2. run `npm run migration:create -- -n CreateUserTable` in the root of the repo

### My Environment

| Operating System    | ElementaryOS | 6
| Node.js version     | v16.9.1 | 
| Typescript version  | typescript@4.3.5  | 
| TypeORM version     | typeorm@0.2.37 | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | not tried           |
| `aurora-data-api-pg` | not tried            |
| `better-sqlite3`     | not tried            |
| `cockroachdb`        | not tried            |
| `cordova`            | not tried            |
| `expo`               | not tried            |
| `mongodb`            | not tried            |
| `mysql`              | not tried            |
| `nativescript`       | not tried            |
| `oracle`             | not tried            |
| `postgres`           | yes            |
| `react-native`       | not tried            |
| `sap`                | not tried            |
| `sqlite`             | not tried            |
| `sqlite-abstract`    | not tried            |
| `sqljs`              | not tried            |
| `sqlserver`          | not tried            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 -  ✅ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by CodingSpiderFox** [comment]
OK it seems like I need to call npm run migration:**generate** -- -n CreateUserTable instead of npm run migration:**create** -- -n CreateUserTable.

**Comment by dmastag** [comment]
@CodingSpiderFox this saved me.

After I cloned at your Repo and tried, I finally could replicate it on my own Repo
So many thanks
