### ISSUE TITLE
Migrations do not run properly on application startup

### ISSUE THREAD

**Issue by CodingSpiderFox** [typeorm/typeorm#8219]
## Issue Description
When running my backend app, the startup fails with the error message:

```
[Nest] 35520  - 09/27/2021, 8:26:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
/home/user/WebstormProjects/nx-typescript-typeorm-boilerplate/apps/boilerplate-backend/src/app/entities/base-entity.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at /home/user/WebstormProjects/nx-typescript-typeorm-boilerplate/src/util/DirectoryExportedClassesLoader.ts:41:22
    at Array.map (<anonymous>)

```
### Expected Behavior

The app starts successfully and runs the migrations

### Actual Behavior
The above error message appears

### Steps to Reproduce

1. Clone the sample repo I made: `git clone https://github.com/CodingSpiderFox/nx-typescript-typeorm-boilerplate && git checkout eb6463b1ec2062069f306a0efd3904c1de2d211f`
2. run `npm install`
3. run `docker-compose up -d` to start posgres and adminer
4. run `npx nx run boilerplate-backend:serve`
### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   ElementaryOS       | 6
| Node.js version     | 16.9.1  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | typeorm@0.2.37  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | not tried            |
| `aurora-data-api-pg` | not tried            |
| `better-sqlite3`     | not tried            |
| `cockroachdb`        | not tried            |
| `cordova`            | not tried            |
| `expo`               | not tried            |
| `mongodb`            | not tried            |
| `mysql`              | not tried            |
| `nativescript`       | not tried            |
| `oracle`             | not tried            |
| `postgres`           | yes            |
| `react-native`       | not tried            |
| `sap`                | not tried            |
| `sqlite`             | not tried            |
| `sqlite-abstract`    | not tried            |
| `sqljs`              | not tried            |
| `sqlserver`          | not tried            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by lexuzieel** [comment]
Hi 👋 Looks like the root of this problem is that the usage of `import` statements is not allowed (only `require()`):

```
SyntaxError: Cannot use import statement outside a module
```

Since this causes the error (in `apps/boilerplate-backend/src/app/entities/base-entity.entity.ts`):

```ts
import {
  PrimaryGeneratedColumn,
  Column,
  UpdateDateColumn,
  CreateDateColumn,
} from 'typeorm'
```

Therefore I think this is not a problem with typeorm but a configuration of your project.
Do you use babel transpiler? You seem to have almost empty `babel.config.json` in the root of your project.

I see that you are using [nx](https://nx.dev) which I have no experience with, but maybe there are instructions of how to set up babel for nx specifically?

**Comment by seriwb** [comment]
It happened to me too.
Try changing "esnext" to "commonjs"

https://github.com/CodingSpiderFox/nx-typescript-typeorm-boilerplate/blob/eb6463b1ec2062069f306a0efd3904c1de2d211f/tsconfig.base.json#L15

**Comment by CodingSpiderFox** [comment]
@seriwb thanks for the suggestion :) I tried it but it didn't help (did another `npm install && nx run boilerplate-backend:build && nx run boilerplate-backend:server` after changing it but the same error persists.

@typeORM devs: I also find the error message confusing: `[Nest] 35520  - 09/27/2021, 8:26:11 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...`

The actual problem seems to be the loading of the entity classes but not the connection to the DB.

**Comment by CodingSpiderFox** [comment]
@lexuzieel : Thanks for the hint :)

As I'm not familiar with typescript, I wonder what babel even really does when using typescript. Googling for babel told me that it's a JS compiler. Why do I need it when I already use typescript which has it's on transpiler?

**Comment by imnotjames** [comment]
Pretty certain this isn't a problem with TypeORM, but your configuration of typescript and your project.  If you find otherwise, please reopen this issue with more information.

For questions and general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
