### ISSUE TITLE
sql.js

### ISSUE THREAD

**Issue by makamekm** [typeorm/typeorm#822]
Does it work with sql.js?

**Comment by pleerock** [comment]
No, it does not. However it should be easy to add this database support as well.

**Comment by daniel-lang** [comment]
Might be another candidate for the sqlite abstraction, right? I can probably add it, if you want to have a driver for it

**Comment by pleerock** [comment]
Right. It would be great

**Comment by makamekm** [comment]
It's better than sqlite3. See https://github.com/mapbox/node-sqlite3/issues/866
