### ISSUE TITLE
Closing TypeORM Connection closes the Pool for Oracle DB

### ISSUE THREAD

**Issue by vs4vijay** [typeorm/typeorm#8222]
## Issue Description

Closing TypeORM Connection closes the Pool instead of Releasing connection back to the pool. I have noticed this behavior as well as checked the code. 

So "connection" object from class "[Connection](https://github.com/typeorm/typeorm/blob/0.2.34/src/connection/Connection.ts)" has method [close()](https://github.com/typeorm/typeorm/blob/0.2.34/src/connection/Connection.ts#L224) which calls `await this.driver.disconnect()` method from class [OracleDriver](https://github.com/typeorm/typeorm/blob/0.2.34/src/driver/oracle/OracleDriver.ts) which internally calls `await this.closePool(this.master)` [method](https://github.com/typeorm/typeorm/blob/0.2.34/src/driver/oracle/OracleDriver.ts#L743) which typically closes the Pool using oracledb node driver.

### Expected Behavior

As per my understanding, either of following 2 cases should happen when closing the connection:
- Connection should be released back to the pool (see [release](https://github.com/typeorm/typeorm/blob/0.2.34/src/driver/oracle/OracleQueryRunner.ts#L96) method in QueryRunner)
- Some conditions in TypeORM code where it check weather a Pool is being used or not, If not used, then close the pool itself.

Any further DB call using getManager or getRepository should succeed.

### Actual Behavior

TypeORM Closes the connection pool, and any DB call after closing the connection is not entertained. i.e. any DB operations using getManager or getRepository fails.

### Steps to Reproduce

1. Obtain Connection using extra options:
```typescript
        const options = {
              <required db host, credentials etc>,
              extra: {
                    enableStatistics: true,  // For New oracledb driver version
                   _enableStats: true,       // For Older oracledb driver version
              }
        };
        const connectionManager = getConnectionManager();
        const connection = connectionManager.has('default')
            ? connectionManager.get('default')
            : await createConnection(options);
```

2. Close the connection.
```typescript
connection.close()
```

3. Either Monitor from Oracle Monitor Session UI or Following:
```typescript

 setInterval(() => {
     console.log('--- connections', require('oracledb').getPool()._logStats());
}, 1000);

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows 10   |
| NodeJS version     | 14.15.5  | 
| Typescript version  | 4.3.5 |
| TypeORM version     | 0.2.34  | 
| OracleDB Driver version     | 5.1.0  | 
| TypeDI version     | 0.10.0  | 
| TypeORM-TypeDI-Extention version     | 0.4.1  | 

### Relevant Database Driver(s)

Only tried with Oracle

| DB Type              | Reproducible  |
| ---                  | ---           |
| `oracle`             | yes |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
> Connection should be released back to the pool (see release method in QueryRunner)

That's the `QueryRunner`.  You're not closing the underlying connection used by TypeORM.  You're closing the TypeORM connection object, thus closing all connections to Oracle.

In this situation, closing the pool makes sense, doesn't it?

**Comment by vs4vijay** [comment]
@imnotjames - It's always best practice to close the DB resources once your work is done. In my case, I am doing some asynchronous work (BullMQ Worker), During the processing, I utilize getRepository() and perform some operation, once that async. work is done, I should close the DB connection so that this connection gets released to pool and some other workers, or API can use it?

Frameworks in all other languages provides a way to close the db connection, e.g. in Java, we always put finally block and close the connection once that work is done. If typeorm does different then it portrays the wrong info. that closing db connection closes the whole pool. 

What do you suggest here, what an async job/worker should do with connection once it has finished processing.

**Comment by imnotjames** [comment]
The TypeORM `Cojnection` object is a logical way to connect to the database.  It's not the connection handle.  The TypeORM connection will interact with the underlying driver.

If you want to close the connection you just have to reconnect with `connect()` again.  Thing is, you'll be closing the pool if the driver utilizes pools.

However, in cases like using the repository, the `QueryRunner` used by that will retrieve a database handle from the underlying driver, use it, and then return it to the connection.   This is managed by the repository.

Please read and follow the documentation, as it should help you in using the library.
