### ISSUE TITLE
Inserting into jsonb[] column in postgres

### ISSUE THREAD

**Issue by AleksandrShepelev** [typeorm/typeorm#8223]
## Issue Description

If I have jsonb[] column in my db, and I cannot find a way to insert array of json objects using typeorm.

underlying table:

create table t(
    col jsonb[] not null
)

### Expected Behavior

Expected insert query to this table to be performed without errors

### Actual Behavior

ERROR: malformed array literal

### Steps to Reproduce

1. create table with jsonb[] column
2. create entity describing this column
3.  try to insert whatever

```typescript

class T {
  @Column( 'jsonb', { name: 'col' })
  col: any[];
}
// (also tried with array = true option, same result)

async connection => {
        let tRepo = connection.getRepository(T);
        const t = new T();
        t.col = [{'a': 1, 'b': 2}];
        await tRepo.save(t);
 }

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 12.22.1  | 
| Typescript version  | 4.0.3  | 
| TypeORM version     | 0.2.37  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
Did you try explicitly setting `array: false`? TypeScript reflection metadata decorates your object with [`Array` type](https://www.typescriptlang.org/play?strictPropertyInitialization=false&importHelpers=true#code/MYewdgzgLgBAwiANgVwLZhgXhmZjEwCGERYAngNwBQVwixJAKjAN5UwwACCK6AFDADkAKwjgARoIA0rHIVQBTAFxDQiQTAC+ASnYw1KwuQDaAXWqagA) and TypeORM interprets it as Postgres array.

**Comment by Ginden** [comment]
Closing due to no response.

**Comment by chingan-tsc** [comment]
I am having the same issue on v0.3.15 and have tried both ` array: false`  and `array: true` to no avail
