### ISSUE TITLE
remove database/schema name from  generated migrations

### ISSUE THREAD

**Issue by kristian1995** [typeorm/typeorm#8232]
## Issue Description
Hi im creating an app where every user have the own database, everything work fine after some issues.
Now my problem is when i generate some migrations with typeorm cli for testing they will be generated with database name in the query...
If i remove it manualy it work fine with all other databases/schemas, when i create new connection all migrations are processed fine ( i use migrationsRun = true).
For moment i can change manualy all query, but how i can generate automaticaly migration without database name there is some option to apply or how can i solve this "problem"? 

Im working with MySql Database

### Expected Behavior
```
  public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`aziende\` ADD \`test\` varchar(255) NOT NULL`);
    }

  public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`aziende\` DROP COLUMN \`test\``);
    }
```

### Actual Behavior
```
  public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`test\`.\`aziende\` ADD \`test\` varchar(255) NOT NULL`);
    }
  public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`test\`.\`aziende\` DROP COLUMN \`test\``);
    }
```

**Comment by imnotjames** [comment]
This should be resolved in 0.2.38
