### ISSUE TITLE
CreateDateColumn is updated when the item is updated

### ISSUE THREAD

**Issue by erald14** [typeorm/typeorm#8242]
## Issue Description
When an item is updated, the created date also changes

### Expected Behavior
Created Date should not change when a item is updated 

### Actual Behavior

<img width="366" alt="Screenshot 2021-10-04 at 11 47 37" src="https://user-images.githubusercontent.com/44317405/135830125-d0064e24-1b58-4498-ba8e-e9f57d588d62.png">

### Steps to Reproduce

1.
2.

```
@CreateDateColumn()
    createdAt: string;
    @UpdateDateColumn()
    updatedAt: string;

```

### My Environment

nest version : "^7.6.17"
typeorm version  "0.2.34"

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 -✅  No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
What is the definition of the table you're working with?

Do you have example code that exhibits this?

**Comment by BenzhaminKim** [comment]
Do you have example code?  @CreateDateColume doesn't update when you update your row.
