### ISSUE TITLE
Cannot query across many-to-many for property when updating the entity relations

### ISSUE THREAD

**Issue by bratello** [typeorm/typeorm#8245]
### Actual Behavior

I have two entities, Field & Device, one field object can be related with many devices and one device can be related with many fields. The update relations operation failed with the mentioned error. The sqlite driver was used for the testing.

```typescript
@Entity()
export class Field {
    @PrimaryGeneratedColumn()
    id: number;

    @ManyToMany(() => Device)
    @JoinTable()
    devices: Device[];
}

@Entity()
export class Device {
    @PrimaryGeneratedColumn()
    id: number;

    @ManyToMany(() => Field, field => field.devices)
    fields: Field[];
}
```
The following tables were created by migrations: field, device, field_devices_device.
```typescript
export class FieldsTable1632832124951 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.createTable(
            new Table({
                name: 'field',
                columns: [
                    {
                        name: 'id',
                        type: 'integer',
                        isPrimary: true,
                        isNullable: false,
                        isGenerated: true,
                        generationStrategy: 'increment',
                    },
                ]
            }),
            false
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(`DROP TABLE field`);
    }
}

export class DevicesTable1632834328945 implements MigrationInterface {
	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.createTable(
            new Table({
                name: 'device',
                columns: [
                	{
                        name: 'id',
                        type: 'integer',
                        isPrimary: true,
                        isNullable: false,
                        isGenerated: true,
                        generationStrategy: 'increment',
                    },
                ]
            }),
            false,
        );
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		queryRunner.query(`DROP TABLE device`);
	}
}

export class FieldsDevicesTable1632862167673 implements MigrationInterface {
	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.createTable(
            new Table({
                name: 'field_devices_device',
                columns: [
                	{
                        name: 'deviceId',
                        type: 'integer',
                        isPrimary: true,
                        isNullable: false,
                    },
                    {
                        name: 'fieldId',
                        type: 'integer',
                        isPrimary: true,
                        isNullable: false,
                    },
                ],
                foreignKeys: [
                    {
                        name: "Devices",
                        columnNames: ["deviceId"],
                        referencedColumnNames: ["id"],
                        referencedTableName: "device",
                        onDelete: "CASCADE",
                        onUpdate: "CASCADE",
                    },
                    {
                        name: "Fields",
                        columnNames: ["fieldId"],
                        referencedColumnNames: ["id"],
                        referencedTableName: "field",
                        onDelete: "CASCADE",
                        onUpdate: "CASCADE",
                    }
                    
                ]
            }),
            false
        );
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		queryRunner.query(`DROP TABLE field_devices_device`);
	}
}
```

### Steps to Reproduce

1. Create entities
2. Create usage code

```typescript
async function test() {
    let field = new Field();
    await fieldsRepository.save(field);

    let device = new Device();
    await devicesRepository.save(device);
    
    field.devices = [device];
    //Failed with the mentioned error
    await fieldsRepository.update(field.id, field); 

    // fieldsRepository.fondOne() method returns relations if I insert relations table record manually
    await getConnection().query("INSERT INTO field_devices_device (deviceId, fieldId) VALUES(?, ?)", [device.id, field.id]);
    await fieldsRepository.fondOne(field.id, { relations: ['devices'] });
}
```
The error happens in QueryBuilder.createPropertyPath() method, in the following part:
```
if (relation.relationType === "one-to-many" || relation.relationType === "many-to-many") {
    // console.log(relation.joinColumns, path, metadata.embeddeds, key);
    throw new Error("Cannot query across " + relation.relationType + " for property " + path);
}
```
Which is bit strange, because the relation was properly configured and basically works for the findOne approach. The embedded metadata is empty, so this type of relation can't be handled by embedded metadata approach.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    OSX      |
| Node.js version     | 14.17.1  |
| Typescript version  | 4.3.5  |
| TypeORM version     | 0.2.37  |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by bratello** [comment]
My excuses, for the updating the relations for the existing entity (already stored in DB), you should use the same repository.save() method instead of update(). I think this ticket might be closed, but please preserve this ticket for the next questions. Thanks.

**Comment by Chen-913** [comment]
I encountered the same problem. Using the `save` method instead of the `update` method made me very confused. The `update` method let me know whether the update was successful through the `affected` field, while the `save` method gave me the feeling of more like an overlay, and I could not extract valid information from the return value of `save` for me to judge.

**Comment by alexandrenolla** [comment]
nothing yet??

**Comment by devkrishnadas** [comment]
any update on this bug ?

**Comment by 5E7EN** [comment]
Using `.save()` is not atomic because you must first `.findOne()` the existing entity.
