### ISSUE TITLE
Question - Joining tables.

### ISSUE THREAD

**Issue by codgician** [typeorm/typeorm#825]
I'm trying to introduce some privilege control to my project. 

First, I have a File entity here. Each file has a owner group, and only members of its owner group can see the file.

``` typescript
@Entity()
export class File {

    @PrimaryGeneratedColumn()
    public id: number;

    @Column('varchar')
    public content: string;

    @Column('int')
    public groupId: number,

}
```

And I have a group_map entity to store the relations between users and groups.

``` typescript
@Entity()
export class GroupMap {

  @PrimaryColumn('int')
  public groupId: number;

  @PrimaryColumn('int')
  public userId: number;

}
```

When a particular user tries to list all the files that he could access, I would like to check whether this user belongs to the owner group of the file.  So to achieve this goal I would like to join the second table ON **File.groupId = groupMap.groupId AND groupMap.userId = :currentUserId (passed in as a parameter)**. 

I'm not sure whether this is possible using relations (or something else?) provided by TypeORM.

Appreciate any help.

**Comment by pleerock** [comment]
so, why dont you use relations?:

```ts
@Entity()
export class File {

    @PrimaryGeneratedColumn()
    public id: number;

    @Column('varchar')
    public content: string;

    @ManyToOne(type => Group) // you told one file has one group, right?
    public group: Group;

}
```

```ts
@Entity()
export class Group {

  @PrimaryColumn('int')
  public id: number;

  @ManyToMany(type => User) // you told each user can have their own groups, right?
  @JoinTable() // or this can be on User side if you want a bi-directional relation 
  public users: User[];

}
```

Now if you need to files with groups owned by a current user:

```ts
const files = await fileRepository.createQueryBuilder("file")
    .innerJoin("file.group", "fileGroup")
    .innerJoin("fileGroup.users", "fileGroupUser", "fileGroupUser.id = :currentUserId")
    .setParameter("currentUserId", currentUserId)
    .getMany();
```

**Comment by codgician** [comment]
Thanks for your solution!
And does that mean when I'm adding a user to a group I'll have to fetch the user instance and then group.users = [UserInstance]?

**Comment by pleerock** [comment]
right

**Comment by codgician** [comment]
Emm, one more question (sorry), is it possible if I want to add another column "privilege" into the mapping table? Like a member of a group can either be a common user or a group administrator? Thanks. 🌹

**Comment by pleerock** [comment]
in many-to-many table? If yes, then no, its not possible. You can too create entity and add there 3 columns with proper relations.

**Comment by codgician** [comment]
You mean I can create a standalone entity "GroupMap" and put two ManyToOne relationships inside, like:
``` typescript

@Entity()
export class GroupMap {

  @ManyToOne(type => Group)
  @JoinColumn()
  public group: Group;

  @ManyToOne(type => User)
  @JoinColumn()
  public user: User;

  @Column('int')
  public privilege: number;

}
```

Thanks.

**Comment by pleerock** [comment]
Yes,  right

**Comment by codgician** [comment]
So is it possible to create index on user and group as well (perhaps a stupid question)?

**Comment by pleerock** [comment]
You can use `@Index` decorator if you want to create index.

**Comment by codgician** [comment]
Solved. Thanks for your help.

**Comment by ruslanchek** [comment]
How to create records at this case? When DTO has UserObject?
