### ISSUE TITLE
[Bug] Docker-Compose up fails to run

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#826]
Just installed docker & composer on Ubuntu 17.04, ran `docker-compose up` as per `DEVELOPER.md` guide and here's the output:
![image](https://user-images.githubusercontent.com/9698639/30076854-e1821382-923f-11e7-9420-0714d561c16d.png)

**Comment by pleerock** [comment]
image is too small and I cant recognize what is there. Maybe you just copy/paste from console?

**Comment by luchillo17** [comment]
Sorry, it's because i tried to copy-paste the one i pasted in Gitter, let me update it.

**Comment by luchillo17** [comment]
Btw just as i put in Gitter, i tried the `hello-world` example and it worked fine so i don't think it's docker not running, what OS are you in? i'm in Ubuntu 17.04, might it be that Docker get's installed on different location on linux? or maybe the Docker version?

**Comment by pleerock** [comment]
im on mac. You definitely have issues with your docker installation or running.  As I already told you in gitter try to check everything - check if docker is running, check if you installed everything correctly, try to google this error in docker community/github

**Comment by luchillo17** [comment]
OMG i'm such a derp, seems in linux i need to use `sudo`.

**Comment by luchillo17** [comment]
Ok now it has issues with my local installation blocking the postgres port `5432`, is there a way to tell docker to pick another one?

**Comment by pleerock** [comment]
yes you can change `docker-compose.yml` file where you can change `5432`, but make sure not to commit this file because you'll change ports of all us too.

**Comment by luchillo17** [comment]
Had to stop my service, anyway, it works, however before my fix this shows:
![image](https://user-images.githubusercontent.com/9698639/30095025-83f1bf82-9295-11e7-876e-0fc62eeec01a.png)
Which shouldn't since it's brand new installed, right? after fix 1 this shows:
![image](https://user-images.githubusercontent.com/9698639/30095194-ad208ea0-9296-11e7-83cb-fccf16ec867a.png)
Since there's less tests it means the test stops when first error shows up?

**Comment by pleerock** [comment]
> Had to stop my service, anyway, it works, however before my fix this shows:

hmm I should not show you this. All tests are passing on my local and CI as well. Try to rerun them again without your fixes

**Comment by luchillo17** [comment]
Made a local reset to the head of this repo instead of the fork, and this time this shows:
![image](https://user-images.githubusercontent.com/9698639/30108239-2ff58490-92c7-11e7-88e7-ff8c8bb26a40.png)
The number of tests passing went lower...

**Comment by pleerock** [comment]
Some tests fail **sometimes** like this one because it missed `order by`. I added order by in last commit - try re-run tests again

**Comment by luchillo17** [comment]
I'm getting an error when using `npm i` twice (shouldn't):
![image](https://user-images.githubusercontent.com/9698639/30144915-c3aec390-9353-11e7-981d-b8937aa21000.png)

**Comment by pleerock** [comment]
This issue is not related to typeorm

**Comment by luchillo17** [comment]
Isn't? i can make `npm i` all the times i want in my other projects and it doesn't break like this.
Maybe not TypeORM per se, but just the SqLite deps?

**Comment by pleerock** [comment]
When I make same things I dont have such error. Maybe error with sqlite you have is your environment specific

**Comment by luchillo17** [comment]
It seems it's an SqLite3 issue or one of it's deps: https://github.com/mapbox/node-sqlite3/issues/612
Can i skip SqLite3 tests for now?

**Comment by pleerock** [comment]
maybe you just downgrade sqlite version?

**Comment by luchillo17** [comment]
To which one?

**Comment by pleerock** [comment]
to skip sqlite set `skip: true` in ormconfig

**Comment by luchillo17** [comment]
That will skip it in tests as well?

**Comment by luchillo17** [comment]
Ok getting closer, skipping SqLite now goes through 391 tests, but breaks in MySql:
![image](https://user-images.githubusercontent.com/9698639/30192616-2138a5f2-940e-11e7-9684-00ee7d067492.png)

**Comment by pleerock** [comment]
strange that it get passed on CI and my local machine and does not pass on yours. My timezone is +5. I don't know what is CI timezone, but Im sure its not equal to mine. Maybe its even 0.

**Comment by luchillo17** [comment]
As i said, that's the only thing i can think of, skipping those 2 does show code coverage, so almost there to starting point to start making PR's.

**Comment by luchillo17** [comment]
I've logged to the docker server for postgres and indeed it have GTM 0, which may be why local time has 5 hours earlier while the saved one get's the later time.

**Comment by luchillo17** [comment]
@pleerock Have you checked what TimeZone has your PC compared to the TimeZone with the `docker-compose up` service?

**Comment by pleerock** [comment]
as I told I have GTM -5 on my local and uses that and its cannot be true that ci/cd has same timezone

**Comment by luchillo17** [comment]
I meant to say if your PC has same timezone between terminal and the `docker-compose` containers, can you check that?

In my PC timezone is GTM -5 while default timezone for Postgres container is UTC.

**Comment by AlexMesser** [comment]
@luchillo17 I made some fixes, pull and recheck these tests. **AlexMesser** is my github nickname, **Zotov Dmitry** is my local git credentials.

**Comment by luchillo17** [comment]
@AlexMesser Dude works like a charm, thanks man, now to fight `Lazy-Relations` issues.
