### ISSUE TITLE
memory leak since 0.2.35

### ISSUE THREAD

**Issue by chriswep** [typeorm/typeorm#8267]
After updating typeorm from 0.2.34 my server started running quickly out of memory, at a rate of about 1Gig every few seconds. this happens with all versions >= 0.2.35, downgrading to 0.2.34 is fine. I tried to research what might be the cause however 0.2.35 introduced quite a number of changes, so i'm a bit lost here. Just shooting in the blue, https://github.com/typeorm/typeorm/commit/f43d56110fd41c23d80e32021adf4ade7648ce97#diff-3008128203dc904e0890ee2cb2ab47080b93ea391288f4acb8f0ecbf3c2dde8a looks like it potentially could be related to what is happening, just guessing.

Anyone else is seeing something similar? What change in 0.2.35 could be responsible?

**Comment by imnotjames** [comment]
If you think it's that commit, revert it and test without it.

Do you have a reproducible example of this?

**Comment by chriswep** [comment]
i can't reproduce it in my dev environment. I tried to put load on it with similar queries / data however the result objects don't even appear in the dump. the commit was just a guess since it's about how objects are created.. compiling different versions of typeorm by guessing and testing them on production is more like a last resort. i thought maybe somebody has seen something similar or has an idea where to look.

**Comment by mmyoji** [comment]
I encountered the same issue. 

Upgrading from v0.2.34 to v0.2.35, our project CI test starts failing due to out of memory.
We use PostgreSQL and just need this commit https://github.com/typeorm/typeorm/commit/5cf368a23fa78b9e97dd12b54616f17b8431ffee.
Then I forked this project, checkout the commit, prepare built version of package, ran the test, and the memory leak happened again.

So the problem commit(s) might be in https://github.com/typeorm/typeorm/compare/0.2.34...5cf368a23fa78b9e97dd12b54616f17b8431ffee.

As @chriswep says, https://github.com/typeorm/typeorm/commit/f43d56110fd41c23d80e32021adf4ade7648ce97#diff-3008128203dc904e0890ee2cb2ab47080b93ea391288f4acb8f0ecbf3c2dde8a could cause the memory leak.

I just let you know this although I haven't investigated this issue deeply.

**Comment by chriswep** [comment]
@mmyoji thanks for the info. could you try reversing the commit and try if that fixes it? i haven't gotten around to it yet since i've settled on 0.2.34 for now.

**Comment by hugo-marello-nutrien** [comment]
Just wanted to say that we got the same problem using version >=0.2.35 and postgresql.

**Comment by jeromeSH26** [comment]
maybe could help, but I'm facing memory leak issue when using cache (redis option). 

when running the following query without cash, no issue, the memory is going up to 2 GB, but when applying the cache (with true or with options) memory is reaching more than 4Gbs, this making node crashing.

```
const dbCache = {
    type: "redis",
    duration: 100000, 
    options: {
      host,
      port:,
    },
    ignoreErrors: false,
  };
```


```
 const HRepo = new HRepository();

  const relations = magoRepo.repository.metadata.relations.map(
    (rel) => rel.propertyName
  );
  const mags = await HRepo.repository.find({
    skip: 0,
    take: 500000,
    where: undefined,
    relations,
    withDeleted: true,
    cache: false, <-- no crash
  });
```


 ```
  const mags = await HRepo.repository.find({
    skip: 0,
    take: 500000,
    where: undefined,
    relations,
    withDeleted: true,
    cache: true, <--crash
  });
```


```
  const mags = await HRepo.repository.find({
    skip: 0,
    take: 500000,
    where: undefined,
    relations,
    withDeleted: true,
     cache: {
      id: "HQ",
      milliseconds: 20000,
    } <-- crash also
  });
```

**Comment by pleerock** [comment]
Can someone confirm if reverting these changes 100% fixes the issue?  If I'll have at least two confirmations - I'll revert that PR. Thanks.

**Comment by pleerock** [comment]
@chriswep are you able to provide something reproducible? I would like to fix the issue if it really exists.

**Comment by chriswep** [comment]
> @chriswep are you able to provide something reproducible? I would like to fix the issue if it really exists.

@pleerock Unfortunately the issue only happens in production. I failed to pinpoint it to something specific other than confirming that its indeed TypeORM query results filling up memory (see heapdumps above).

Any suggestions on how to get to the bottom of this?

**Comment by chriswep** [comment]
so i did some additional tests:
- upgrade to 0.2.41 => memory leak
- current master with 3d6c5dae76ad0e0640650058ae58fe0addda2ae6 and f43d56110fd41c23d80e32021adf4ade7648ce97 reverted => memory leak
- 0.2.34 => fine

so the entitySkipConstructor thing doesn't seem to be related to this. also, the issue is still there in the current master.

**Comment by chriswep** [comment]
tried to go through commits between 0.2.34 and 0.2.35, looking for anything creating objects esp. related to query results. Basically fishing in the dark here since my insight into what's going on is very limited in a lot of cases. 

8937fd209ef6bb9fd9f44e81a3678c62bf34ce8d looks promising. i can do a test with the last commit before that tomorrow.

**Comment by chriswep** [comment]
ok, i found the responsible commit by brute force divide and conquer: e7e887a582cce66bd21044472f4a5288894650c9

@pleerock the memory leak is caused by the code added in the commit above. as i suspected its related to relations. Can you see what's going on looking at the code? Guessing from the commit message it might be causing an infinite looping eager loading of relations? I checked my code, if have no circular eager-loop in there.

**Comment by pleerock** [comment]
@chriswep can you comment code lines one by one to check what line exactly caused this issue? I would start with comment outing this:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/1753397/154516227-aaff5dc6-9ea1-4ee5-b207-3c999e3023f5.png">

**Comment by chriswep** [comment]
hmm, looking at the code i wonder if that will work? From what i see it changes the order of execution in several `find*` methods in the same way, i.e. it puts `joinEagerRelations` after `FindOptionsUtils.apply*` methods (the code you mentioned is not added but moved). Also, it almost completely swaps out the code for `joinEagerRelations`. So all changes are related from what i see, i.e. as far as i understand the code if i revert one line i have to revert the others as well so that the code overall still makes sense. Or am i missing something @pleerock ?

**Comment by chriswep** [comment]
one thing that looks suspicious to me is that the recursive call of `applyRelationsRecursively` in `src/find-options/FindOptionsUtils.ts` is not at the end of the method anymore, i.e. the change puts `this.joinEagerRelations` after the recursive call: https://github.com/typeorm/typeorm/commit/e7e887a582cce66bd21044472f4a5288894650c9#diff-b1d369543bb184df5326b405715092e9bae2f73fb2c7e069cd36fd9c2bf37105L259

this "feels" like a bug, without understanding the internals.

**Comment by pleerock** [comment]
Regarding to internal implementation of `joinEagerRelations` was completely changed (not by me) what what I originally was written. You either need to debug a bit more to find out problematic place or provide me a minimal reproduction code which I can test. I don't see any problems with a given PR, not sure what I miss.

**Comment by chriswep** [comment]
ok, i went through each change. if i revert the change in the `find` method in `EntityManager.ts` the issue goes away.

code that causes memory to go out of bounds in seconds:
```typescript
async find<Entity>(entityClass: EntityTarget<Entity>, optionsOrConditions?: FindManyOptions<Entity>|FindConditions<Entity>): Promise<Entity[]> {
         const metadata = this.connection.getMetadata(entityClass);
         const qb = this.createQueryBuilder<Entity>(entityClass as any, FindOptionsUtils.extractFindManyOptionsAlias(optionsOrConditions) || metadata.name);
         FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder(qb, optionsOrConditions);

         if (!FindOptionsUtils.isFindManyOptions(optionsOrConditions) || optionsOrConditions.loadEagerRelations !== false)
             FindOptionsUtils.joinEagerRelations(qb, qb.alias, metadata);

         return qb.getMany();
     }
```

reverted code, issue goes away: 
```typescript
async find<Entity>(entityClass: EntityTarget<Entity>, optionsOrConditions?: FindManyOptions<Entity>|FindConditions<Entity>): Promise<Entity[]> {
         const metadata = this.connection.getMetadata(entityClass);
         const qb = this.createQueryBuilder<Entity>(entityClass as any, FindOptionsUtils.extractFindManyOptionsAlias(optionsOrConditions) || metadata.name);

         if (!FindOptionsUtils.isFindManyOptions(optionsOrConditions) || optionsOrConditions.loadEagerRelations !== false)
             FindOptionsUtils.joinEagerRelations(qb, qb.alias, metadata);

         return FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder(qb, optionsOrConditions).getMany();
     }
```

since the changes in `findAndCount` and `findOne` are similar, i suspect that they cause a similar issue, however the `find` method is much more used.

**Comment by pleerock** [comment]
and what happens if you remove these lines:

```ts
         if (!FindOptionsUtils.isFindManyOptions(optionsOrConditions) || optionsOrConditions.loadEagerRelations !== false)
             FindOptionsUtils.joinEagerRelations(qb, qb.alias, metadata);
```

**Comment by chriswep** [comment]
with the mentioned lines removed the memory does not go up:

```typescript
async find<Entity>(entityClass: EntityTarget<Entity>, optionsOrConditions?: FindManyOptions<Entity>|FindConditions<Entity>): Promise<Entity[]> {
         const metadata = this.connection.getMetadata(entityClass);
         const qb = this.createQueryBuilder<Entity>(entityClass as any, FindOptionsUtils.extractFindManyOptionsAlias(optionsOrConditions) || metadata.name);
         FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder(qb, optionsOrConditions);

         // if (!FindOptionsUtils.isFindManyOptions(optionsOrConditions) || optionsOrConditions.loadEagerRelations !== false)
         //    FindOptionsUtils.joinEagerRelations(qb, qb.alias, metadata);

         return qb.getMany();
}
```

However those lines were not added in the commit. Also, relations data seems to be missing from the returned data (as expected when removing those lines).

**Comment by chriswep** [comment]
do you have a suggestion how to proceed with this? to summarise: the `find` method before the referenced commit works without issue and also correctly returns the eager relations. With the changed code, memory goes through the roof on our production server. 

The difference is in the changed order of execution of `FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder` and `FindOptionsUtils.joinEagerRelations`. The former is quite complex and does many things, among others causes a call to `joinEagerRelations` on its own under certain circumstances. It's difficult/impossible to me to understand exactly what the effect of the change is internally. However it seems apparent to me that the changed order of execution can have unintended side effects.

@pleerock i see that the `find*` methods in the 0.3.0 branch are completely re-written. I wonder if the issue will be resolved then anyway? When would you expect 0.3.0 to become ready for usage?

**Comment by pleerock** [comment]
@chriswep you are asking me to fix something that I don't see. The issue you have looks weird. It's not possible for me to understand the problem from code change difference you pointed. The only way I see I can help is a minimal reproduction example from you where I can see and understand the problem.

> @pleerock i see that the find* methods in the 0.3.0 branch are completely re-written. I wonder if the issue will be resolved then anyway?

they are not re-written, just interface has changed and new features were added. You can try this version and see if it works for you.

> When would you expect 0.3.0 to become ready for usage?

In March it will be merged into master and released with a final 0.3.0 version.

**Comment by chriswep** [comment]
i now kind of resolved the issue for me. Since https://github.com/typeorm/typeorm/pull/5685 enables the eager loading of child relations, the issue was more or less hidden in versions before that. In my code i call `find()` for an entity class that has eager child relations. In this case the code didn't rely on those child relations so it didn't matter that they were not loading before. With 0.2.43, if run this `find()` request with `loadEagerRelations: false`, the server runs fine.

What eventually filled up the memory were two columns with long text that were repeated by the multiple joins. Obviously my eager-loading configuration can and should be refactored. Also, the new `relationLoadStrategy: "query"` in 0.3.0 will help here. However one might still consider memory usage to be an area worth improving on. Maybe it would be a possibility to not load redundant data into memory on the returned rows? Just guessing here, don't know if that would be even under the control of TypeOrm or only the underlying driver. All things considered, `relationLoadStrategy: "query"` seems to be the solution to all of this.

Since performance of relations is already tracked in https://github.com/typeorm/typeorm/issues/3857 i close this issue here.

**Comment by pleerock** [comment]
Great to hear you found a resolution.
