### ISSUE TITLE
Why does insert bring a select query and how to avoid it

### ISSUE THREAD

**Issue by Mllions-c** [typeorm/typeorm#8279]
1、Why does insert bring a select query and how to avoid it
2、This query has only a primary key，no shard key ,So there is a performance problem

i am very anxious to get the answer, thanks

**Comment by aamirpinger** [comment]
Did you try the .save() method with Save Option reload: false?

**Comment by AlexMesser** [comment]
As mentioned above, you can disable additional query by using `.save({ reload: false })` option.

From the docs:

* reload: boolean - Flag to determine whether the entity that is being persisted should be reloaded during the persistence operation. It will work only on databases which does not support RETURNING / OUTPUT statement. Enabled by default.
