### ISSUE TITLE
Can not inherit Select Query Builder

### ISSUE THREAD

**Issue by lukasdietrich93** [typeorm/typeorm#829]
We used an "extended" Query Builder, that inherited your SelectQueryBuilder (which was "QueryBuilder" all the way back). As you recently changed the return types of a few functions (e.g. select) within your SelectQueryBuilder.ts from "this" to "SelectQueryBuilder<Entity>" we can not inherit it anymore.

Are there any future plans on changing that back so the methods of that Query Builder can be inherited?

**Comment by pleerock** [comment]
Right now you can transform query builder from one type to another. There are several query builder types:

* InsertQueryBuilder
* UpdateQueryBuilder
* DeleteQueryBuilder
* SelectQueryBuilder

each has its own methods, and you can easily switch between query builder types, for example:

```ts
createQueryRunner("post") // returns you SelectQueryBuilder

// but lets say you want to use update query instead. You can do:
createQueryRunner("post")
   .update() // returns you UpdateQueryBuilder

// to make it possible update return signature is (): UpdateQueryBuilder<Entity> {
// if we change it to this, then update will still return us SelectQueryBuilder
// same with all other methods - delete, insert and select
// because if you create update query builder and wanna switch it to select
// using select() method if do "this" in return type we still will have UpdateQueryBuilder

```

I don't think its possible for `select` method to return `this` anymore.

**Comment by pleerock** [comment]
Feel free to continue discussion if you have something to add.

**Comment by lukasdietrich93** [comment]
We have some helper functions in our Extended Query Builder like "addPaging", but are stuck to the old version of typeorm because we can not inherit it anymore. What do you suggest, e.g. some kind of Mixins?

**Comment by pleerock** [comment]
I don't know what you are doing and why to suggest something. My suggestion for now is - don't extend query builder. Create a separate class which will use query builder instead of creating its extending version.
