### ISSUE TITLE
No error names since v0.2.35

### ISSUE THREAD

**Issue by Benwick91** [typeorm/typeorm#8294]
### What was unclear or otherwise insufficient?

Since version 0.2.35 I can't get the error name from e.g. my EntityNotFound errors. The name is missing and my error messages, which are tracked by the specific error name, fails.

### Recommended Fix

Adds back the error names or why are they not used any more?

### Additional Context

I am get the error from the exception property of my GraphQL Request error.

**Comment by kirintwn** [comment]
The name property for `EntityNotFoundError` was changed from `EntityNotFound` to `EntityNotFoundError` due to the PR https://github.com/typeorm/typeorm/pull/6909.
This is not documented at all though.

**Comment by Ginden** [comment]
No response from author, fix was provided.
