### ISSUE TITLE
Issue with column name in ManyToOne relation

### ISSUE THREAD

**Issue by iz-iznogood** [typeorm/typeorm#832]
Hello, 

first of all let me say that this is an amazing ORM, great piece of engineering.

I am evaluating it and found an issue, not sure if it is a bug.
I setup an OneToMany relation and I tried to declare the foreign key using the relation id decorator, but it did not work. The schema is created as usual but the names are not as expected.

I am attaching a test project, that reproduces the issue with the latest code
[testorm.zip](https://github.com/typeorm/typeorm/files/1281402/testorm.zip)

**Comment by pleerock** [comment]
Don't forget to start projects if you like them 😉 

> I setup an OneToMany relation

setuping relation already creates a foreign key

> relation id decorator

relation id decorator has different purpose, its not related to foreign keys somehow

> names are not as expected.

what names are you talking about? Column names? What names do you have and how do you want to change them?

Please provide formatted code snippets when answered my questions.l

**Comment by ckalogeropoulos** [comment]
Ok thanks for the prompt reply. (project starred already)
What I want is a way to name the column in the foreign key relation.

The person entity is 
`@Entity("Persons")
export class Author {

    @PrimaryGeneratedColumn()
    Id: number;

    @Column()
    Name: string;

    @OneToMany(type => Photo, photo => photo.Author) // Note: we will create author property in the Photo class below
    Photos: Photo[];

    @OneToMany(type => Photo, photo => photo.Reviewer) // Note: we will create author property in the Photo class below
    ReviewedPhotos: Photo[];
}`

and the photo entity is 

`@Entity("Photos")
@TableInheritance("class-table")
@DiscriminatorColumn({ name: "Type", type: "nvarchar" })
export class Photo {

    @PrimaryGeneratedColumn()
    Id: number;

    @Column({
        length: 800,
        nullable: false
    })
    Name: string;

    @Column("text")
    Description: string;

    @Column()
    Filename: string;

    @Column({
        type: "int",
        nullable: false,
        default: 0
    })
    Views: number;

    @Column({
        default: false
    })
    IsPublished: boolean;

    @ManyToOne(type => Author, author => author.Photos, {
        onDelete: "CASCADE"
    })
    Author: Author;

    @RelationId((photo: Photo) => photo.Author)
    AuthorId: number;

    @ManyToOne(type => Author, author => author.ReviewedPhotos)
    Reviewer: Author;

    @RelationId((photo: Photo) => photo.Reviewer)
    ReviewerId: number;    
}`

The AuthorId column is created as 'authorId' - camelcase. I know that I can override the naming convention interface but I would prefer if I can override the column name for the foreign key field as it works using the @Column decorator in other fields

**Comment by iz-iznogood** [comment]
Thanks for the prompt reply. (project starred already).

What I want is to be able to change the field name of the foreign key in a relation as it works for normal fields (using the @Column decorator)

Now I have  the person entity 

`@Entity("Persons")
export class Author {

    @PrimaryGeneratedColumn()
    Id: number;

    @Column()
    Name: string;

    @OneToMany(type => Photo, photo => photo.Author) // Note: we will create author property in the Photo class below
    Photos: Photo[];

    @OneToMany(type => Photo, photo => photo.Reviewer) // Note: we will create author property in the Photo class below
    ReviewedPhotos: Photo[];
}`

and the photo entity

`@Entity("Photos")
@TableInheritance("class-table")
@DiscriminatorColumn({ name: "Type", type: "nvarchar" })
export class Photo {

    @PrimaryGeneratedColumn()
    Id: number;

    @Column({
        length: 800,
        nullable: false
    })
    Name: string;

    @Column("text")
    Description: string;

    @Column()
    Filename: string;

    @Column({
        type: "int",
        nullable: false,
        default: 0
    })
    Views: number;

    @Column({
        default: false
    })
    IsPublished: boolean;

    @ManyToOne(type => Author, author => author.Photos, {
        onDelete: "CASCADE"
    })
    Author: Author;

    @RelationId((photo: Photo) => photo.Author)
    AuthorId: number;

    @ManyToOne(type => Author, author => author.ReviewedPhotos)
    Reviewer: Author;

    @RelationId((photo: Photo) => photo.Reviewer)
    ReviewerId: number;    
}`

how can I override the naming of AuthorId and ReviewerId ? Now they are created as authorId and reviewerId. I know that I can reimplement  the NamingConvention interface but I would prefer to do it the same way as other fields using @Column or something else

**Comment by pleerock** [comment]
first, I dont recommend to use table-inheritance. Its not stable yet.

If you want to change relation's column name in the database you must use `@JoinColumn` decorator:

```ts
    @ManyToOne(type => Author, author => author.Photos, {
        onDelete: "CASCADE"
    })
    @JoinColumn({ name: "authorId" })
    Author: Author;
```

You don't need `@RelationId` decorator for this purpose.

**Comment by iz-iznogood** [comment]
Works perfect, thank you !!!!

**Comment by errawn** [comment]
thanks!

> first, I dont recommend to use table-inheritance. Its not stable yet.
> 
> If you want to change relation's column name in the database you must use `@JoinColumn` decorator:
> 
> ```ts
>     @ManyToOne(type => Author, author => author.Photos, {
>         onDelete: "CASCADE"
>     })
>     @JoinColumn({ name: "authorId" })
>     Author: Author;
> ```
> 
> You don't need `@RelationId` decorator for this purpose.

**Comment by gajananfc** [comment]
In this case how I'll be applying the query for autherId?
