### ISSUE TITLE
Multiple discrete where clauses in a scope share the same map for variable names.

### ISSUE THREAD

**Issue by matthewvcarey1** [typeorm/typeorm#8327]
## Issue Description
This bug verges on an irritating feature

If you are using typeorm programatically to construct a querybuilder query with several where clauses in the scope, each where (andWhere or orWhere) clause shares the same variable map of names -> values
### Expected Behavior
I would expect later variable assignment not to overwrite earlier variable assignment in a different where clause.
### Actual Behavior
Later use of the same variable names in separate where scope clauses overwrites earlier assignments.

### Steps to Reproduce
We have a postgres database and it has a table User with email, given_name and family_name attributes
There are some records in the db
We  have an array of CreateUserInput objects that contain the same contents as exists on the db.
When we query with the following function only one duplicate record will be found despite there being many in the array. 

```typescript
async function checkForExistingUsers(
    manager: EntityManager,
    inputs: CreateUserInput[]
): Promise<User[]> {
    const scope = manager.createQueryBuilder(User, 'User')

    for (let i = 0, len = inputs.length; i < len; i++) {
        const ob = inputs[i]
        scope.orWhere(
                new Brackets((qb) => {
                    qb.where(
                        `User.email = :email AND User.given_name = :given_name AND User.family_name = :family_name`,
                        {
                             email: ob.email,
                             given_name: ob.given_name,
                             family_name: ob.family_name,
                        }
                    )
                })
            ) 
     }
     return await scope.getMany()
 }
 ```
 When we inspect the db query all the variables passed will be from the final set of query variables set.

I would expect each separate where clause to have a separate namespace attached to the map variable name values.
### My Environment

| Dependency          | Version  |
| graphql              | 15.5.3     |
| Operating System    |  Ubuntu 21.10       |
| Node.js version     | v15.13.0 | 
| Typescript version  | typescript@4.2.4 | 
| TypeORM version     | typeorm@0.2.31 | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by matthewvcarey1** [comment]
I would love to be able to fix it myself but I don't have the skills at present.

**Comment by matthewvcarey1** [comment]
The following is a work around that lets me work but probably consigns me to some sort of typescript hell.
```typescript
async function checkForExistingUsers(
    manager: EntityManager,
    inputs: CreateUserInput[]
): Promise<User[]> {
    const scope = manager.createQueryBuilder(User, 'User')

    for (let i = 0, len = inputs.length; i < len; i++) {
        const ob = inputs[i]
           // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const searchParameters: any = {}
            searchParameters[`email${i}`] = ob.email
            searchParameters[`given_name${i}`] = ob.givenName
            searchParameters[`family_name${i}`] = ob.familyName
            scope.orWhere(
                new Brackets((qb) => {
                    qb.where(
                        `User.email = :email${i} AND User.given_name = :given_name${i} AND User.family_name = :family_name${i}`,
                        searchParameters
                    )
                })
           )        
     }
     return await scope.getMany()
 }

**Comment by matthewvcarey1** [comment]
Looking at the existing code in typeorm
```
  orWhere(where: Brackets|string|((qb: this) => string)|ObjectLiteral|ObjectLiteral[], parameters?: ObjectLiteral): this {
        this.expressionMap.wheres.push({ type: "or", condition: this.getWhereCondition(where) });
        if (parameters) this.setParameters(parameters);
        return this;
    }
 ```
 The problem might be reconciling the string passed that references the parameters with any namespace that you had injected into the ```this.setParameters(parameters)```
 
 I suppose we could at a pinch find the '= :somename' string  transform it to '= :namespace-somename'

**Comment by spotykatch** [comment]
What does `scope.getQuery()` return?

**Comment by matthewvcarey1** [comment]
Do you mean in the existing bad case?:
It does not tell me very much as it does not list the parameter values, however if I tail the postgres output I do get them.
```
SELECT "User"."created_at" AS "User_created_at", "User"."updated_at" AS "User_updated_at", "User"."deleted_at" AS "User_deleted_at", "User"."status" AS "User_status", "User"."user_id" AS "User_user_id", "User"."given_name" AS "User_given_name", "User"."family_name" AS "User_family_name", "User"."username" AS "User_username", "User"."email" AS "User_email", "User"."phone" AS "User_phone", "User"."date_of_birth" AS "User_date_of_birth", "User"."gender" AS "User_gender", "User"."avatar" AS "User_avatar", "User"."primary" AS "User_primary", "User"."alternate_email" AS "User_alternate_email", "User"."alternate_phone" AS "User_alternate_phone", "User"."myOrganizationOrganizationId" AS "User_myOrganizationOrganizationId" FROM "user" "User" WHERE ("User"."email" = :email AND "User"."given_name" = :given_name AND "User"."family_name" = :family_name) OR ("User"."email" = :email AND "User"."given_name" = :given_name AND "User"."family_name" = :family_name) OR ("User"."email" = :email AND "User"."given_name" = :given_name AND "User"."family_name" = :family_name) OR ("User"."phone" = :phone AND "User"."given_name" = :given_name AND "User"."family_name" = :family_name)
```

**Comment by matthewvcarey1** [comment]
My evil work around gives me this:
```
SELECT "User"."created_at" AS "User_created_at", "User"."updated_at" AS "User_updated_at", "User"."deleted_at" AS "User_deleted_at", "User"."status" AS "User_status", "User"."user_id" AS "User_user_id", "User"."given_name" AS "User_given_name", "User"."family_name" AS "User_family_name", "User"."username" AS "User_username", "User"."email" AS "User_email", "User"."phone" AS "User_phone", "User"."date_of_birth" AS "User_date_of_birth", "User"."gender" AS "User_gender", "User"."avatar" AS "User_avatar", "User"."primary" AS "User_primary", "User"."alternate_email" AS "User_alternate_email", "User"."alternate_phone" AS "User_alternate_phone", "User"."myOrganizationOrganizationId" AS "User_myOrganizationOrganizationId" FROM "user" "User" WHERE ("User"."email" = :email0 AND "User"."given_name" = :given_name0 AND "User"."family_name" = :family_name0) OR ("User"."email" = :email1 AND "User"."given_name" = :given_name1 AND "User"."family_name" = :family_name1) OR ("User"."email" = :email2 AND "User"."given_name" = :given_name2 AND "User"."family_name" = :family_name2) OR ("User"."phone" = :phone3 AND "User"."given_name" = :given_name3 AND "User"."family_name" = :family_name3)
```

**Comment by spotykatch** [comment]
Wow! Is there 3 same where clause?
```sql
SELECT
    "User"."created_at" AS "User_created_at",
    "User"."updated_at" AS "User_updated_at",
    "User"."deleted_at" AS "User_deleted_at",
    "User"."status" AS "User_status",
    "User"."user_id" AS "User_user_id",
    "User"."given_name" AS "User_given_name",
    "User"."family_name" AS "User_family_name",
    "User"."username" AS "User_username",
    "User"."email" AS "User_email",
    "User"."phone" AS "User_phone",
    "User"."date_of_birth" AS "User_date_of_birth",
    "User"."gender" AS "User_gender",
    "User"."avatar" AS "User_avatar",
    "User"."primary" AS "User_primary",
    "User"."alternate_email" AS "User_alternate_email",
    "User"."alternate_phone" AS "User_alternate_phone",
    "User"."myOrganizationOrganizationId" AS "User_myOrganizationOrganizationId"
FROM "user" "User"
WHERE
(
    "User"."email" = :email
    AND "User"."given_name" = :given_name
    AND "User"."family_name" = :family_name
)
OR
(
    "User"."email" = :email
    AND "User"."given_name" = :given_name
    AND "User"."family_name" = :family_name
)
OR
(
    "User"."email" = :email
    AND "User"."given_name" = :given_name
    AND "User"."family_name" = :family_name
)
OR
(
    "User"."phone" = :phone
    AND "User"."given_name" = :given_name
    AND "User"."family_name" = :family_name
)
```

**Comment by matthewvcarey1** [comment]
Yes that is what happens, and the map uses the last one that you set, of course.

**Comment by spotykatch** [comment]
Are the values that you get in the query are the first ones or the last ones?

**Comment by matthewvcarey1** [comment]
The last values are the values that are passed.

**Comment by matthewvcarey1** [comment]
I think that if this behaviour was at least documented it might at least give users of the library the heads up. I can see looking at the typeorm code that it is tricky to fix this cleanly. And some library users might actually be relying on this behaviour.

**Comment by spotykatch** [comment]
Can you, please, give def of `CreateUserInput` for the tests.

**Comment by matthewvcarey1** [comment]
For your purposes it is just an array of Users

**Comment by spotykatch** [comment]
I will think in writing, so you can skip all that stuff. Just need something like a diary) I'll do that in this post. Editing it.
So, for some reason, `getWhereCondition` in `QueryBuilder` is called twice.
`console.log(where instanceof Brackets)` returns `true` for the first one and `false` for the second.
`console.log(typeof where === "string");` returns `false` for the first one and `true` for the second.
So the string is sent on the second iteration. Iteration of what?)))
`console.log("where", where);` in `where(...)` of `SelectQueryBuilder` is called, while we didn't call it.
So this guy is rewriting our code. But why?

**Comment by matthewvcarey1** [comment]
I do appreciate your efforts

**Comment by spotykatch** [comment]
Do my edits are sent to your email? Sorry if it's so. Just don't want to forget what I was thinking of.
Also, I was thinking of why can't you do a simple select if `CreateUserInput` is equal to the data that you have in your database? Is it like a duplicate finder? If so, can you do it like so?
```sql
SELECT
    email, given_name, family_name, COUNT(*)
FROM
    users
GROUP BY
    email, given_name, family_name
HAVING 
    COUNT(*) > 1
```
And then delete `count - 1` rows

**Comment by matthewvcarey1** [comment]
We were trying to have a API were we allow client to submit up to 50 records and in the case of any error the whole input is rejected and a report that helps the user fix the input is returned as error. To keep their sanity the client gets a report of all the records that fail validation, or are repeats or already exist. etc.

**Comment by matthewvcarey1** [comment]
I was trying here to replace method that did a query per item and replace it with one query over the whole input set.

**Comment by pleerock** [comment]
It is by design. There is no `scopes` in `.where` statements. There is a single query and array of parameters without any additional scopes. You need to do something like:

```ts
qb.where(
    `User.email = :email${i} AND User.given_name = :given_name${i} AND User.family_name = :family_name${i}`,
    {
         ["email" + i]: ob.email,
         ["given_name" + i]: ob.given_name,
         ["family_name" + i]: ob.family_name,
    }
)
```

**Comment by matthewvcarey1** [comment]
Can this design feature be more explicitly documented?

**Comment by matthewvcarey1** [comment]
But thanks to everyone for looking into this for me.

**Comment by spotykatch** [comment]
> Can this design feature be more explicitly documented?
You can do it)) I think you do understand this problem like nobody else.

**Comment by matthewvcarey1** [comment]
:^)
