### ISSUE TITLE
Unique Index Schema update issue

### ISSUE THREAD

**Issue by iz-iznogood** [typeorm/typeorm#833]
Adding a Unique index using the Index decorator works great
If you remove the decorator then the index is not dropped.

The problem happens when the decorator is on the entity or the column(s) and it only happens for unique indexes. Non unique are dropped fine
I use MSSQL and I traced the issue on this query 

`SELECT TABLE_NAME = t.name, INDEX_NAME = ind.name, IndexId = ind.index_id, ColumnId = ic.index_column_id, COLUMN_NAME = col.name, ind.*, ic.*, col.* FROM sys.indexes ind INNER JOIN sys.index_columns ic ON ind.object_id = ic.object_id and ind.index_id = ic.index_id INNER JOIN sys.columns col ON ic.object_id = col.object_id and ic.column_id = col.column_id INNER JOIN sys.tables t ON ind.object_id = t.object_id WHERE ind.is_primary_key = 0 AND ind.is_unique = 0 AND ind.is_unique_constraint = 0 AND t.is_ms_shipped = 0 ORDER BY t.name, ind.name, ind.index_id, ic.index_column_id`

that excludes unique indexes.

**Comment by pleerock** [comment]
Released in `0.1.0-alpha.40`
