### ISSUE TITLE
Error in migration generation. No connection Options were gound

### ISSUE THREAD

**Issue by pepefeliblu** [typeorm/typeorm#8330]
## Issue Description

While trying to execute `npx typeorm migration:generate -n migrationName` 

### Expected Behavior

`npx typeorm migration:generate` should generate the migration. 

### Actual Behavior

Nothing I get the described error.

```
Error during migration generation:
Error: No connection options were found in any orm configuration files.
```

### Steps to Reproduce

I was following [this tutorial](https://anjith-p.medium.com/typeorm-database-migrations-in-nestjs-apps-ace923edf1bf) with minor adjustments.  

1. I'm not using a JSON at root folder for ormconfig. I've renamed it and placed it within my src. 
2. All paths are clear and I'm able to use `npx typeorm migration:create` without an issue

### My Environment

NestJS and Node

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   MacOS - BigSurOS       |
| Node.js version     | 16.4.0 | 
| Typescript version  | 4.1.12 | 
| TypeORM version     | 0.2.32 | 

### Additional Context

Not other than `migration:create` works and `migration:generate` doesn't

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅  No, I don’t have the time and I’m okay to wait for the community/maintainers to resolve this issue.

**Comment by Ginden** [comment]
Working as intended.

If your `ormconfig` isn't in root folder, you need to specify `-f` option:

```bash
npx typeorm migration:generate -f dist/ormconfig.js
```
