### ISSUE TITLE
Multiple MySQL hosts (managed by Percona)

### ISSUE THREAD

**Issue by nabilnaffar** [typeorm/typeorm#835]
How can i configure typeORM to work with multiple MySQL instances?
In mysql node module i would configure it as:
```
{
        cluster_config: {
            removeNodeErrorCount: 2,
            restoreNodeTimeout: 5000
        },
        connection_config: {
            hosts: 'HOST1:PORT,HOST2:PORT,HOST3:PORT',
            user: 'user',
            password: 'pass',
            database: 'db'
        }
}
```

**Comment by pleerock** [comment]
Can you please send me a link to where node mysql package supports `hosts` option, because I can't see it in [connection options](https://github.com/mysqljs/mysql#connection-options)

**Comment by nabilnaffar** [comment]
My mistake mate, there is no 'hosts' configuration, we're actually parsing it and adding each host to the pool cluster manually.
Does typeORM has createPoolCluster method which I can add hosts to it as in mysql?
[https://github.com/mysqljs/mysql#poolcluster-options](url)

**Comment by pleerock** [comment]
Do you add them all as slaves? What about master?

**Comment by nabilnaffar** [comment]
By default, connection is picked by round robin, and it's configurable by [poolcluster-options](https://github.com/mysqljs/mysql#poolcluster-options)
I found this configuration to work for me in typeORM:
**createConnections([{host: 'host1'...}, {host: 'host2'...},...])**
but i couldn't find how to configure  **removeNodeErrorCount** and **restoreNodeTimeout**

**Comment by pleerock** [comment]
yeah you can use `createConnections([{host: 'host1'...}, {host: 'host2'...},...])` but you also need to use each connection by name `getConnection("name")` and work with it individually. 

There are also replication settings you can use (since `0.1.0-alpha.36`). See docs [here](https://github.com/typeorm/typeorm/blob/master/docs/connection.md#replication).

**Comment by nabilnaffar** [comment]
What happens when connection to master fails? is there a retry amount config? or restore master connection timeout?
p.s. your library awesome! I really liked it and hope to contribute to it

**Comment by pleerock** [comment]
In `0.1.0-alpha.37` I added those options as well, can you please check and confirm if they work fine for you?:

```js
    "replication": {
      "master": {
        "host": "localhost",
        "port": 3306,
        "username": "test",
        "password": "test",
        "database": "test"
      },
      "slaves": [
        {
          "host": "localhost",
          "port": 3306,
          "username": "test",
          "password": "test",
          "database": "test"
        },
        {
          "host": "localhost",
          "port": 3306,
          "username": "test",
          "password": "test",
          "database": "test"
        }
      ],
     "canRetry": true,
     "removeNodeErrorCount": 5,
     "restoreNodeTimeout": 0
    },
```

**Comment by pleerock** [comment]
I hope they did.

**Comment by nabilnaffar** [comment]
Took me a while to verify, but it works! Thanks
