### ISSUE TITLE
Typeorm seems to freeze completely

### ISSUE THREAD

**Issue by scholz-timo** [typeorm/typeorm#8350]
## Issue Description

After running some queries getManyAndCount() queries using the query builder with a "slave" query runner, the code will just freeze instead of returning the expected the result

### Expected Behavior

It should not freeze during the 10th run

### Actual Behavior

It freezes after 9 runs, during the 10th run

### Steps to Reproduce

```typescript
import "reflect-metadata";
import { Connection } from "../../../src";
import { closeTestingConnections, createTestingConnections } from "../../utils/test-utils";
import { Setting } from "./entity/Setting";

describe("github issues > #NO", () => {

	let connections: Connection[];

	before(async () => connections = await createTestingConnections({
        enabledDrivers: ['mysql'],
        entities: [Setting],
		schemaCreate: true,
		dropSchema: true
	}));

	after(() => closeTestingConnections(connections));

	function insertSimpleTestData(connection: Connection) {
        const settingRepo = connection.getRepository(Setting);

        const setting = settingRepo.create({
            value: "test"
        });

		return settingRepo.save(setting);
	}

	// important: must not use Promise.all! parallel execution against different drivers would mess up the counter within the SettingSubscriber!

	it("Should not fail after the tenth creation", async () => {
		for(const connection of connections) {
			await insertSimpleTestData(connection);

            const settingRepo = connection.getRepository(Setting);

            for (let i = 0; i <= 10; i++) {
                console.log("Runner no: ", i);
                await settingRepo.createQueryBuilder('sr', connection.createQueryRunner('slave')).getManyAndCount();
            }
        }
	});

});
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Dockerized system, running on MacOS         |
| Node.js version     | 14.17.6  | 
| Typescript version  | 4.4.3   | 
| TypeORM version     | latest development branch | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                       | ---           |
| `aurora-data-api`       | unkown            |
| `aurora-data-api-pg` | unkown            |
| `better-sqlite3`     | unkown            |
| `cockroachdb`        | unkown            |
| `cordova`            | unkown            |
| `expo`               | unkown            |
| `mongodb`            | unkown            |
| `mysql`              | yes            |
| `nativescript`       | unkown            |
| `oracle`             | unkown            |
| `postgres`           | unkown            |
| `react-native`       | unkown            |
| `sap`                | unkown            |
| `sqlite`             | unkown            |
| `sqlite-abstract`    | unkown            |
| `sqljs`              | unkown            |
| `sqlserver`          | unkown            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by scholz-timo** [comment]
Bug is in: src/query-builder/SelectQueryBuilder::executeEntitiesAndRawResults.

Need help to enable breakpoints for further investigation.

**Comment by scholz-timo** [comment]
Seems to be an issue with the mysql driver: 
Call stack ends up in MysqlDriver::obtainMasterConnection()
Wich in turn then calls this.pool.getConnection(...) which in turn does not resolve

**Comment by scholz-timo** [comment]
Waiting for verification, if someone else agrees, this issue can be moved to

https://github.com/mysqljs/mysql

and

https://github.com/sidorares/node-mysql2

**Comment by zacksinclair** [comment]
Randomly happened across this issue. 

You're creating connections w/o releasing them and thus saturating the 10 connection pool. Typeorm is waiting for you to release a connection so that there's a new one to use. This is not a typeorm bug, its an implementation error.

e.g.
```
const queryRunner = connection.createQueryRunner()

// await running some queries w/ the queryRunner

quertyRunner.release()
```

**Comment by scholz-timo** [comment]
Ahh, thanks 👍
