### ISSUE TITLE
This Method throw "Cyclic dependency" Error and does not consider the full entity type

### ISSUE THREAD

**Issue by mduvernon** [typeorm/typeorm#8358]
Consider that you have an Entity named Category from one Domain which have another relation @ManyToOne => Category form another domain, This method throw "Cyclic dependency" Error 

https://github.com/typeorm/typeorm/blob/1f558b18042c28cd60315259e1d8a9ce5a8188b5/src/persistence/SubjectTopoligicalSorter.ts#L177

**Comment by jaiminTH** [comment]
@mduvernon Hello 
Did you find any solution for this issue?
