### ISSUE TITLE
@ViewEntity is not working with SQLite database 

### ISSUE THREAD

**Issue by TechieTaher** [typeorm/typeorm#8362]
@ViewEntity is not working with SQLite database 

## Feature Description
ViewEntity should take view name which is already present in database like entity.

### The Problem
```
@ViewEntity({
  expression: `
      SELECT "Clients"."Name" AS "Name",
             "Bills"."CreateDate" AS "CreateDate",
             "Bills"."Total" AS "Total"
  FROM     "Bills" "Bills"
  INNER JOIN "Clients" "Clients" ON "Bills"."ClientId" = "Clients"."ClientId"
                    `,
})
export class vSaleBill {
  @ViewColumn()
  Name: string;

  @ViewColumn()
  CreateDate: Date;
  @ViewColumn()
  Total: number;
}

```
when i try to get data from this view it returns that vSaleBill is not available when in database with same name view is present.

### The Solution
A solution is to provide entity like feature in which view name is given and it access that view and return the result.

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
To select from view defined externally, you can just decorate entity with:

`@ViewEntity({ synchronize: false, name: 'view_name_in_database' })`

Is that what you meant?

**Comment by Ginden** [comment]
Closing issue due to lack of response.
