### ISSUE TITLE
error: cannot query across one-to-many for property members

### ISSUE THREAD

**Issue by eurydice76** [typeorm/typeorm#8363]
I am new with `typeorm` and I face trouble with a `OneToMany` relationship. I have a `Person` entity which contains a `@OnetoMany` relationship to a `Member` entity and a `@ManyToOne` relationship to a `Fare` entity. I can post a new `Person` without problem but I get an error when I update an existing `Person` with the following body:

`{"firstName":"john","lastName":"doe","fareId": 1}
`
The error is the following:

`(node:699940) UnhandledPromiseRejectionWarning: Error: Cannot query across one-to-many for property members
`
Here is my Person entity:

```
import { Entity, Column, ManyToOne, OneToMany, PrimaryGeneratedColumn } from "typeorm";

import { Fare, Member } from "./";

@Entity()
export class Person {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        unique: false,
        nullable: false
    })
    firstName: string;

    @Column({
        unique: false,
        nullable: false
    })
    lastName: string;

    @Column({
        unique: false,
        nullable: true
    })
    address: string;

    @Column({
        unique: false,
        nullable: true
    })
    phone: string;

    @Column({
        unique: false,
        nullable: true
    })
    email: string;

    @OneToMany(() => Member, member => member.person)
    members: Member[];

    @ManyToOne(() => Fare, fare => fare.persons)
    fare: Fare
}

```
Here is the update part of my controller:

```
router.put('/persons/:id', async (req: Request, res: Response) => {
    const id = +req['params']['id'];
    const person = await this._personService.readOne(id);
    if (!person) {
        res.status(400).send('Person not found')
    }

    const { lastName, firstName, address, email, phone, fareId } = req['body'];
    if (fareId) {
        const fare = await this._fareService.readOne(fareId);
        if (!fare) {
            res.status(400).send('Fare not found')
        } else {
            person.fare = fare;
        }
    }

    person.lastName = lastName ? lastName : person.lastName;
    person.firstName = firstName ? firstName : person.firstName;
    person.address = address ? address : person.address;
    person.email = email ? email : person.email;
    person.phone = phone ? phone : person.phone;

    const updatedPerson = await this._personService.update(person,id);
    res.send(updatedPerson);
});

```
and here is the update part of my Person service:

```
public update = async (person: Person, id: number) => {
    const updatedPerson = await this._personRepository.update(id, person);
    return updatedPerson;
}

```
would you know what is wrong with my code ?

**Comment by imnotjames** [comment]
This is not supported at this time - we need `EXISTS` queries & we don't have those yet

**Comment by eurydice76** [comment]
Thanks for the quick answer. So, there is no way to pass around that problem ? Should I consider to change of ORM ?

**Comment by iJhefe** [comment]
> Thanks for the quick answer. So, there is no way to pass around that problem ? Should I consider to change of ORM ?

You can declare a RelationId column fireId to find by fareId directly. In this case your entity used to be like:

```
export class Person {
   // ... entity

   @RelationId((person: Person) => person.fare) // @RelationId is experimental and optional here.
   @Column('integer')
   fireId: number;

   @ManyToOne(() => Fare, fare => fare.persons)
    fare: Fare
}
``` 

so you can find for "fareId" instead of "fare: { id }"

for more complex queries you should use query builder.

**Comment by eurydice76** [comment]
many thanks for the hint. I will give a try with relationId.

**Comment by Mitch-i** [comment]
> Thanks for the quick answer. So, there is no way to pass around that problem ? Should I consider to change of ORM ?

to which ORM you switched?
