### ISSUE TITLE
Add "remove connection" functionality to ConnectionManager class

### ISSUE THREAD

**Issue by shaunek** [typeorm/typeorm#8365]
### The Problem

Apps that are required to use automatically rotating database credentials have memory leaks if they use `ConnectionManager` to create/manage their connections. For example, my company's infrastructure involves rotating credentials every few hours, and when new credentials are discovered our apps need to create a new connection with those credentials and close the old connection. However, there is no way to remove an old, closed (and unneeded!) connection object from the `ConnectionManager`. Even though we are able to close the connections, over time the list of connections in the `ConnectionManager` will grow and it will hold on to dozens or hundreds or thousands of old and unusable connection references. I would consider this an unnecessary memory leak.

(Before there was a hacky way to manage the number of connections held in the `ConnectionManager.connections` array because it was `public` and we could just update that array (hacky, I know), but as of v0.2.35 the `ConnectionManager` class was modified in a way that makes it impossible for client code to manage the `ConnectionManager.connectionMap` collection since it was made strictly `private`. We can't even extend the ConnectionManager to add the desired functionality.)

### The Solution

Add a `remove` method to `ConnectionManager` so that applications can easily remove unneeded connections. Perhaps something like this
```
    remove(connectionName: string): void {
        // check if such connection is registered
        const existConnection = this.connectionMap.get(connectionName);
        if (existConnection) {
            // if connection is registered and its not closed then throw an error
            if (existConnection.isConnected)
                throw new CannotRemoveActiveConnectionError(connectionName || "default");
        }

        this.connectionMap.delete(connectionName);
    }
```
The `CannotRemoveActiveConnectionError` would be a new class with a custom message.

### Considered Alternatives

1. Client code can copy/replicate the ConnectionManager class in their own application
2. Client code is able to access the private `ConnectionManager.connectionMap` using an unsavory technique that is not type-safe and relies on the dynamic nature javascript runtime 👎 Here is an example:

```
// eslint-disable-next-line dot-notation
const connectionMap: Map<string, Connection> = getConnectionManager()['connectionMap'];
connectionMap.delete(connectionName);
```

### Additional Context

I am aware of #7428 which states that in the future the `ConnectionManager` will be deprecated, however, I am unsure if or when that will happen. Additionally, if it is only deprecated and not removed it would still be useful to have this "remove connection" functionality in place for clients that are unable to immediately move to the new functionality.

### Relevant Database Driver(s)

This feature request isn't specific to any particular driver.

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
Closing since we don't plan to support `ConnectionManager` in the future.
