### ISSUE TITLE
Add support for Postgres GENERATED ALWAYS AS IDENTITY

### ISSUE THREAD

**Issue by drtyh2o** [typeorm/typeorm#8370]
### The Problem

A recent feature added Postgres support for identity columns `{ generated: 'identity' }` which will generate columns using `GENERATED BY DEFAULT AS IDENTITY`. It would be great to support the option to generate columns using `GENERATED ALWAYS AS IDENTITY`.

### The Solution

We currently use `{ insert: false }`  column option so that Typeorm won't include the identity column in the INSERT statements for some _existing_ tables we have whose identity column was previously created with `GENERATED ALWAYS AS IDENTITY`.

It would be nice to be able to have Typeorm use `GENERATE ALWAYS AS IDENTITY` or `GENERATE BY DEFAULT AS IDENTITY` based on some option. The `insert` option is not included in `TableColumnOptions` so that would not appear to be useful as a solution for conditionally generating the proper migration code. 

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by leoromanovsky** [comment]
We're on the same wavelength @drtyh2o - mentioned this the other day in TypeORM's Slack and seems like there is support from the Maintainer to go in this direction: https://typeorm.slack.com/archives/CCTEVJC8G/p1636621370078900

How did you create and manage your tables with an `identity` before the feature was added?

**Comment by drtyh2o** [comment]
> How did you create and manage your tables with an `identity` before the feature was added?

We used `generated: ‘increment’` and modified the migration manually. It was super tedious (especially on subsequent migrations as typeorm always wanted to change it back). The new `generated: ‘identity’` is a huge improvement. The ability to optionally use GENERATED ALWAYS AS IDENTITY would be most welcome. 

Feel free to expand and use this issue (or close it in favor of a new one) should you decide to pursue a contribution.
