### ISSUE TITLE
When inserting an array with TypeORM, the order of id that comes out as result

### ISSUE THREAD

**Issue by JaehyeonLim** [typeorm/typeorm#8374]
### What was unclear or otherwise insufficient?
When inserting an array with TypeORM, the order of id that comes out as result?

working on inserting arrays using INSERT.
I'm going to do another task using the IDs that came out as a result of insert.
At this time, the IDs that come out as a result of insert come out in the order of array when insert?

```ts
// customRepository.ts
insertArr(nameArr : {name : string}[]){
    reuturn this.createQueryBuilder()
    .insert()
    .into(customTable)
    .values(nameArr)
    .execute()
}
```

```ts
// service.ts

        const connection = getConnection();
        const repository = connection.getCustomRepository('customRepository')
        const arr = [{name : 'first'},{name : 'second'}]


        const result =
          await repository.insertArr(
            arr
          );

        console.log('result : ', result);
        //Does this result come out in the order of insert?
```

### Recommended Fix
Tell me the order of result.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
Order of results from `returning` clauses is undefined for most of databases.

SQL Server documentation claims that results are returned according to physical table layout (so basically random if you have UUID keys, but ordered if you have `int` primary key).
