### ISSUE TITLE
Is there small project with all deps for error reproduction

### ISSUE THREAD

**Issue by rluvaton** [typeorm/typeorm#8379]
I think this would be really helpful when submitting bugs to have a project with as little as possible dependencies and `docker-compose` for each DB so recreating the issue will be much easier

Or [typeorm/typescript-example](https://github.com/typeorm/typescript-example) is enough for that when creating reproduction (just `docker-compose` is missing)?

**Comment by pleerock** [comment]
Usually people have a concrete issue on a concrete db. And usually it's enough to provide reproduction on a single database. People who want more usually want to apply fix. In this case they need to checkout TypeORM code, which already has all dbs in its docker-compose. 

So I don't think we need to complicate typeorm/typescript-example repo.
