### ISSUE TITLE
softDelete does not work with @BeforeRemove trigger

### ISSUE THREAD

**Issue by eder-ig** [typeorm/typeorm#8386]
## Issue Description
The @BeforeRemove trigger is not executed using the repository.softRemove() function.
Instead, it is only executed using the repository.remove() function which, when executed, deletes the record from the database.

### Expected Behavior
It makes no sense to perform a soft delete record and then delete it from the database. Ideally, the @BeforeRemove trigger could be executed upon execution of the repository.softRemove() or repository.softDelete() method allowing execution of the trigger and preservation of the changed record.

### Actual Behavior

```
// include the output in code tags like these!
Re: there is no output error on the console
```

### Steps to Reproduce

1. Create project using the command "typeorm init --name api --database mysql --express"
2. Create audit classes, user model that extends audit
3. Create the user controller
4. Configure route to access function
5. Insert a record in the table for testing

6. Delete the record using softDelete. (The expected behavior is that the deleted_at and deleted_by fields are filled and the record remains stored in the database)

```typescript
// insert code here

// Soft Delete Classs
import { BeforeInsert, BeforeRemove, BeforeUpdate, Column, CreateDateColumn, DeleteDateColumn, UpdateDateColumn } from "typeorm";
// import { ap } from "..";
// import { jwtDecodeToken } from "../helper/jwtDecodeToken";

export class Audit {
  @Column({ length: 60, type: String, nullable: true })
  created_by?: string;

  @CreateDateColumn()
  created_at?: Date;

  @Column({ length: 60, type: String, nullable: true })
  updated_by?: string;

  @UpdateDateColumn()
  updated_at?: Date;

  @Column({ length: 60, type: String, nullable: true })
  deleted_by?: string;

  @DeleteDateColumn()
  deleted_at?: Date;

  @BeforeInsert()
  insert() {
    // this.created_by = jwtDecodeToken(ap['authorization']).name
    this.created_by = 'User'
  }
  @BeforeUpdate()
  update() {
    // this.updated_by = jwtDecodeToken(ap['authorization']).name
    this.updated_by = 'User'
  }
  @BeforeRemove()
  console.log('Test')
  delete() {
    // this.deleted_by = jwtDecodeToken(ap['authorization']).name
    this.deleted_by = 'User'
  }
}


// User Classs
import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";
import { Audit } from './Audit ';

@Entity()
export class User extends Audit {

  @PrimaryGeneratedColumn()
  id?: number;

  @Column()
  name?: string;

}


// Control function invoked by express
import { NextFunction, Request, Response } from "express";
import { getRepository } from "typeorm";
import { User } from "../entity/User";

export class UserController {


  async remove(request: Request, _response: Response, next: NextFunction) {
    let userToRemove: any = await this.userRepository.findOne(request.params.id);

    return await this.userRepository.softRemove(userToRemove);
  }
}

// Router
import { UserController } from "../controller/UserController";

export default [
  {
      method: "delete",
      route: "/users/:id",
      controller: UserController,
      action: "remove"
  }
]


```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.17.5  | 
| Typescript version  | 4.4.4  | 
| TypeORM version     | 0.2.37  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              |  yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ No, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by spotykatch** [comment]
If I'm not misstaken, `softRemove` triggers `@BeforeUpdate`.
For your cases you can try to use subscribers. I guess this should work, but I'm not realty sure.
```ts
await this.userRepository.softRemove(userToRemove, { data: { action: 'soft-remove' } });
```
```ts
afterUpdate(event: UpdateEvent<Audit>): void {
  const { entity, queryRunner: { data: { action } } } = event;
  if ( action === 'soft-remove') {
    entity.deleted_by = 'User';
  }
}
```

**Comment by alanscordoba** [comment]
The solution worked wonders, thanks.

**Comment by spotykatch** [comment]
I think the bug label can be removed and the issue can be closed.

**Comment by eder-ig** [comment]
https://github.com/typeorm/typeorm/issues/8398

OK, considering the above proposal, I will close the issue.
Thanks
