### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Darren-Gannon** [typeorm/typeorm#8392]
### What was unclear or otherwise insufficient?

The slack link in [typeorm/CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/32865190a909f9f0d571d3b6caa535dbf636bf6a/CONTRIBUTING.md) is dead

> You can ask on Slack

redirects to this [Error Page](https://typeorm.slack.com/join/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g#/shared-invite-legacy/error) on Slack.

### Recommended Fix

1. Refresh Link
2. Remove Link

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
@pleerock Can you have a look at this?

**Comment by AlexMesser** [comment]
fixed.
