### ISSUE TITLE
Default value went wrong with the added single quotes ' ' 

### ISSUE THREAD

**Issue by devamin** [typeorm/typeorm#8411]
## Issue Description
If we add a default value, `'defaultValue'` the two single quotes are added by default, causing some issues in some cases
### Expected Behavior

Let the user manage the quotes when creating the default value

### Actual Behavior

Query failure, this is one of the e.g
```
// include the output in code tags like these!
QueryFailedError: BLOB, TEXT, GEOMETRY or JSON column 'location' can't have a default value
```

### Steps to Reproduce

1. the code : 
```typescript
  @Index({spatial:true})
  @Column({
    type: "geometry",
    spatialFeatureType: "Point",
    srid: 4326, 
    default:"(POINT(0,0))"
  })
  location?: Geometry
```
2. the generated SQL query : 
```sql
ALTER TABLE `Profile` CHANGE `location` `location` geometry NOT NULL DEFAULT '(POINT(0,0))'
```

mysql ref : https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 14.17.6 | 
| Typescript version  | 4.4.4 | 
| TypeORM version     | 0.2.41  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 -  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by spotykatch** [comment]
Try this one
```ts
default: () => "(POINT(0,0))"
```

**Comment by devamin** [comment]
Thanks, it works.
