### ISSUE TITLE
[Feat] Make TDD first citizen

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#842]
TDD would allow for a better development approach than just testing each time manually, it's tiresome to have to go to terminal and run test command each time, have you looked at [gulp-mocha-tdd](https://www.npmjs.com/package/gulp-mocha-tdd)?

**Comment by pleerock** [comment]
`gulp-mocha-tdd` looks something not so popular, are you sure you provided a proper package? I don't understand meaning of this request

**Comment by luchillo17** [comment]
`gulp-mocha-tdd` was the first one i saw in search results, dunno if popular or not, but it's an example.

Mainly what I've seen with current testing flow is that you have to run test manually each time, if we use TDD, the project should support a way to watch for file changes and run tests, basically watch functionality.

Also i've seen no feat or way to debug tests aside from logging all over the place.

**Comment by pleerock** [comment]
> Mainly what I've seen with current testing flow is that you have to run test manually each time, if we use TDD, the project should support a way to watch for file changes and run tests, basically watch functionality.

we use tdd and we use mocha and all libraries need for tdd. If you want to run tests on each change then I think its a bad idea because re-running all tests each time means you will wait for 5 minutes for all tests to run after each change. Its not an option.

**Comment by luchillo17** [comment]
What about focused tests? that's an option on the unpopular library linked.

**Comment by pleerock** [comment]
you can run focused test using your IDE or simply by putting `it.only` or `describe.only` on any test you would like to run

**Comment by luchillo17** [comment]
Ok now think about focused tests + watch feature, now it makes sense.
