### ISSUE TITLE
Caching with Redis broken with Redis v4

### ISSUE THREAD

**Issue by aardvarkk** [typeorm/typeorm#8420]
## Issue Description

I receive the error "The client is closed" when running a cached query via Redis.

The trouble is that the new version (v4) of the Redis npm package does **not automatically connect anymore**. See [here for the migration guide](https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md). I think basically all that would need to change is to call `connect()` after `createClient()`, but I'm not sure what that would do if somebody was using v3 of Redis.

I tried passing `legacyMode: true` as an option via TypeORM's config, but I believe the autoconnect is still gone even in legacy mode.

### Actual Behavior

```
// include the output in code tags like these!
```

The cache should function correctly via Redis.

### Steps to Reproduce

1. Set up query caching to use Redis, with Redis npm package version >= 4
2. The connection fails

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  | 
| Typescript version  | x.y.zzz  | 
| TypeORM version     | x.y.zzz  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by aardvarkk** [comment]
I've written up a PR that fixes this for me in my local environment. Basically we just need to do two things to get it working:

- Call `connect()` on the client
- Pass `legacyMode: true` in the client options so that the existing code doesn't have to change

Ideally, `RedisQueryResultCache.ts` would be split up/rewritten into various implementations, since there's better Promise support from both `ioredis` and `node-redis` now, but this seems like an easy stop-gap solution that should maintain compatibility with existing code.

**Comment by itrcz** [comment]
we should call connect not just in v4. more then eq 4 should work better.

**Comment by gineika** [comment]
It's still broken? Latest versions.

Error: The client is closed

```
await dataSource.initialize()
await dataSource.queryResultCache?.connect() // not connected
```

This works:
```
await dataSource.initialize()
// @ts-ignore
await dataSource.queryResultCache?.client.connect() // connected, but "client" is a "protected" prop
```

**Comment by SamuelGaona** [comment]
> workaround:
> 
> ```
> const connection = await createConnection({
>     //.....
>     cache: {
>         type: "redis",
>         options: {
>             url: process.env.REDIS_URL,
>             legacyMode: true,
>         },
>     },
> })
> connection.queryResultCache.client.connect()
> ```

Not working for me :(

**Comment by SamuelGaona** [comment]
Nevermind, forget about node-redis, use ioredis.
