### ISSUE TITLE
The use of createQueryBuilder cannot trigger the triggering of the transformer in the entity

### ISSUE THREAD

**Issue by warriorBrian** [typeorm/typeorm#8421]
## Issue Description

Cannot trigger the transformer in the entity using the query statement

```ts
// typeorm service

await this.articleRepository.createQueryBuilder('article')
      .select(['article.id', 'article.title AS article_title', 'article.introduction', 'article.banner'])
      .orderBy({ 'article.createdAt': 'DESC', 'article.id': 'DESC' })
      .getRawMany();
```

```ts
@Column({
    transformer: {
      to(value: any): any {
        if (value == '' || value == null) return '';
        return JSON.stringify(value);
      },
      from(value: any): any {

       // Will not trigger in the query

        if (value == null || value == '') return [];
        return JSON.parse(value);
      }
    }
  })
  introduction: string;
```

In the query statement, the from method in the entity cannot be triggered.

### Expected Behavior

In the query, the from method in the transformer in the entity cannot be triggered. You need to use from to perform the from conversion. I changed the use of the find method, for example: `this.articleRepoistory.find()`, which can trigger the from method

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Node.js version     | 14.16.1  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.2.41  | 

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
Working as intended - it's called `getRawMany` for a reason.
