### ISSUE TITLE
The save() method always insert into a one-to-one relationship entity

### ISSUE THREAD

**Issue by JeesooHaa** [typeorm/typeorm#8422]
### Expected Behavior

When using `save()`, if the data is already in a one-to-one relationship entity, it should either be an update, not an insert, or do nothing.

### Actual Behavior

```bash
ER_DUP_ENTRY: Duplicate entry 'test' for key 'PRIMARY'
```
```sql
SELECT `User`.`documentId` AS `documentId` FROM `User` `User` WHERE ((`User`.`documentId` = ?)) -- PARAMETERS: ["test"]
INSERT INTO `User`(`documentId`, `data`) VALUES (?, ?) -- PARAMETERS: ["test","{\"script\":\"text\"}"]
```
If `save()` on data that already exists, a duplicate entry error occurs.
Because, the sql query always executes an INSERT on relationship entity.
INSERT query is executed even if the data has not changed.

### Steps to Reproduce

```typescript
// document entity
@Entity('Document')
export class Document {
  @PrimaryColumn('varchar', { length: 120 })
  public id: string;

  @OneToOne(
    () => User,
    (user: User) => user.document,
    {
      cascade: true,
      eager: true,
    },
  )
  public user: User;
}
```
```typescript
// user entity 
@Entity('User')
export class User {
  @PrimaryColumn('varchar', { length: 120 })
  public documentId: string;

  @Column('json')
  public data: object;

  @OneToOne(
    () => Document,
    (document: Document) => document.user,
    {
      onDelete: 'CASCADE',
    },
  )
  @JoinColumn({ name: 'documentId', referencedColumnName: 'id' })
  public document: Document;
}
```
```typescript
// same data save script
async saveDocument() {
  const repository = getRepository(Document);
  const document = { id: 'test', user: { documentId: 'test', data: { script: 'text' } } };

  await repository.save(document);
  await repository.save(document); // ER_DUP_ENTRY: Duplicate entry 'test' for key 'PRIMARY', Error with User entity
}
```
```typescript
// new data save script
async saveDocument() {
  const repository = getRepository(Document);
  const document = { id: 'test', user: { documentId: 'test', data: { script: 'text' } } };
  const document2 = { id: 'test', user: { documentId: 'test', data: { script: 'text2' } } };

  await repository.save(document);
  await repository.save(document2); // ER_DUP_ENTRY: Duplicate entry 'test' for key 'PRIMARY', Error with User entity
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  macOS 11.6   |
| Node.js version     | 14.17.1  | 
| Typescript version  | 3.9.10  | 
| TypeORM version     | 0.2.21   | 
| NestJS  | 6.14.2 |

### Additional Context

The same problem occurs when `documentId` is `Column` rather than a `PrimaryColumn`.
Changing the CASCADE option does not solve the problem.
When only `Document` use `save()`, it works without any problem.

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - :heavy_multiplication_x: Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - :white_check_mark: No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by spotykatch** [comment]
Guess, you forgot `await`
```ts
await repository.save(document);
```

**Comment by JeesooHaa** [comment]
I've confused you by omitting `await`. I'm sorry. But even using `await` doesn't work the way I want it to.

**Comment by spotykatch** [comment]
Try to `@JoinColumn` in the `Document` entity.

**Comment by JeesooHaa** [comment]
Solved this by using `primary` option.

```typescript
@Entity('User')
export class User {
  @Column('json')
  public data: object;

  @OneToOne(
    () => Document,
    (document: Document) => document.user,
    {
      primary: true, 
      onDelete: 'CASCADE',
    },
  )
  @JoinColumn({ name: 'documentId', referencedColumnName: 'id' })
  public document: Document;
}
```
