### ISSUE TITLE
pg - parameter save was number return string

### ISSUE THREAD

**Issue by pedromesmer** [typeorm/typeorm#8423]
## pg - parameter save was number return string

typeorm v ^0.2.38

guys, I noticed that when fetching data from a table saved as number ('decimal') the value is returned as a string.

to solve it, I used a transformer on the entity like this:

`
  @Column('decimal', {
    transformer: {
      to(value) {
        return value;
      },
      from(value) {
        return parseFloat(value);
      },
    },
  })
  value: number;
`

is there any way to get this data or use the transformer? 

-----

pessoal, uma notei que ao buscar os dados de uma tabela salvos como number ('decimal') o valor é retornado como string.

para resolver, usei um transformer na entity assim:

`
  @Column('decimal', {
    transformer: {
      to(value) {
        return value;
      },
      from(value) {
        return parseFloat(value);
      },
    },
  })
  value: number;
`

tem alguma forma de pegar esse dado nem usar o transformer?

**Comment by Ginden** [comment]
Question is unclear.

> is there any way to get this data or use the transformer?

TypeORM automatically use transformer.
