### ISSUE TITLE
Insert fails with nullable properties.

### ISSUE THREAD

**Issue by bruno-lopes** [typeorm/typeorm#8435]
## Issue Description
I'm using SQLite with TypeORM. Currently, I'm not able to save objects with nullable properties like this:

```
  @Column('text', {nullable: true})
  name: string;
``` 

### Expected Behavior

I would expect the object to be saved in database.

### Actual Behavior

I get the following error:
```
ERROR Error: Uncaught (in promise): TypeError: can't define property "name": Object is not extensible
13745/ColumnMetadata</ColumnMetadata.prototype.setEntityValue@http://localhost:8100/vendor.js:455666:17
```

I can see in the logs the insert:

```
query:  INSERT INTO "aEntity"("id", "property1", "name", "property2", "property3", "property4", "property5", "property6", "property7", "property8") VALUES (?, ?, NULL, ?, ?, ?, ?, ?, ?, ?) -- PARAMETERS: [37,"property1Value","property2Value","property3Value","property4Value","property5Value","property6Value","property7Value","property8Value"]
```
The property name has the value NULL (and it is correct), but the insert fails.

### Steps to Reproduce

1. Mark a property with nullable ColumnOption
2. Try to save the object

```typescript
  @Column('text', {nullable: true})
  name: string;

----

create(aEntity: AEntity): AEntity{
    let newEntity: AEntity = aEntity;
    this.entitiesStorageService.ready().then(async (connection: Connection) => {
      newEntity = await getRepository(AEntity).save(newEntity);
    });
    return newEntity;
  }
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Linux Mint 20.2      |
| Node.js version     | v16.10.0  | 
| Typescript version  | 4.2.4  | 
| TypeORM version     | 0.2.41  | 

### Additional Context

If I remove the nullable option, and set a value to the property, the entity is saved correctly.

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | yes           |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by mittche** [comment]
Don't know may be @Column('text', { nullable: true, default: null })
Or shorten
@Column('text', { default: null })
@Column({ type: 'text', default: null })

**Comment by mittche** [comment]
nullable = true is by default or not?

**Comment by bruno-lopes** [comment]
@mittche  thanks for your response. It was my fault, I'm using NgRx and I'm passing some props to an action. In the effect I was trying to save one of those props, but in NgRx props must be immutable, so I had the described problem.

After using Object.assign to copy the properties to another Object, I was able to save it.

Now, the entity code is as follow:

```
  @Column({type: String, nullable: true})
  name?: string | undefined;
```

The default is nullable = false.

I'm closing the issue, since it was my fault.
