### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ownColumns')

### ISSUE THREAD

**Issue by NenadJovicic** [typeorm/typeorm#8437]
## Issue Description

I started to build small project using NestJS and TypeORM, but I have a problem which I am not sure why it is caused.
This is the [link](https://github.com/NenadJovicic/nest-raspored) to project. 
I don't see anything missing in my entities, but when I start app with `docker-compose up`, I see error `TypeError: Cannot read properties of undefined (reading 'ownColumns')`
Can you check did I made any mistake with models? Because I followed everything from your documentation how they should be defined.

### Expected Behavior

App is up and running without any errors in terminal.

### Actual Behavior

```shell
vip-raspored-be | TypeError: Cannot read properties of undefined (reading 'ownColumns')
vip-raspored-be |     at /home/app/src/metadata-builder/EntityMetadataBuilder.ts:372:64
vip-raspored-be |     at Array.map (<anonymous>)
vip-raspored-be |     at EntityMetadataBuilder.computeEntityMetadataStep1 (/home/app/src/metadata-builder/EntityMetadataBuilder.ts:368:14)
vip-raspored-be |     at /home/app/src/metadata-builder/EntityMetadataBuilder.ts:113:45
vip-raspored-be |     at Array.forEach (<anonymous>)
vip-raspored-be |     at EntityMetadataBuilder.build (/home/app/src/metadata-builder/EntityMetadataBuilder.ts:113:14)
vip-raspored-be |     at ConnectionMetadataBuilder.buildEntityMetadatas (/home/app/src/connection/ConnectionMetadataBuilder.ts:65:111)
vip-raspored-be |     at Connection.buildMetadatas (/home/app/src/connection/Connection.ts:510:59)
vip-raspored-be |     at Connection.<anonymous> (/home/app/src/connection/Connection.ts:186:18)
vip-raspored-be |     at step (/home/app/node_modules/tslib/tslib.js:143:27)

```

### Steps to Reproduce

1. Clone project
2. Run `npm i`
3. Run `docker-compose up --build`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.13.0  | 
| Typescript version  | 4.4.4  | 
| TypeORM version     | 0.2.38  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | YES            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by NenadJovicic** [comment]
After playing around with my entities and testing out which one is causing the problem, I found out it is this one
```typescript
import { ChildEntity, Column, Entity, ManyToOne, PrimaryGeneratedColumn, TableInheritance } from 'typeorm';
import { Karton } from './karton.entity';
import { User } from './user.entity';

export enum TipIzvestaja {
  ULAZNI = 'ulazni',
  IZLAZNI = 'izlazni',
  TRENEROV = 'trenerov',
  KONTROLNI = 'kontrolni',
}
@Entity()
@TableInheritance({ column: { type: 'enum', name: 'tipIzvestaja', enum: TipIzvestaja } })
export class IzvestajBase {
  @PrimaryGeneratedColumn()
  id?: number;

  @Column()
  datum: Date;

  @Column({ length: 1000, type: 'text' })
  uvodniTekst: string;

  @Column({ length: 3000, type: 'text' })
  objektivniNalaz: string;

  @ManyToOne(() => User)
  kreator: User;

  @ManyToOne(() => Karton)
  karton: any;
}

@ChildEntity(TipIzvestaja.ULAZNI)
export class UlazniIzvestaj {
  @Column({ nullable: false, length: 250, type: 'varchar' })
  dijagnoza: string;

  @ManyToOne(() => User)
  pacijent: User;
}
```

I forgot to extend `IzvestajBase` class in child class

**Comment by BartoszTrading** [comment]
For future readers, can also happen when you forget register abstract entity in entities :)

**Comment by Bui-Thanh-Liem** [comment]
JoinTable
