### ISSUE TITLE
Limit 0 incorrect working

### ISSUE THREAD

**Issue by andranikarakelyan** [typeorm/typeorm#8439]
When in Query builder I pass `limit( 0 )`, in final query to database typeorm not generating` LIMIT 0` expression. I think in [this method](https://github.com/typeorm/typeorm/blob/54cf66082afe2ec80319a36a3c618ff097acd4eb/src/query-builder/SelectQueryBuilder.ts#L1629) all `if ( limit )` conditions should be changed to `typeof limit === 'number' && limit > 0`

**Comment by briceruzand** [comment]
Same #4883 I think
