### ISSUE TITLE
null values on nested embedded types (changed from alpha.37 to alpha.38)

### ISSUE THREAD

**Issue by Urigo** [typeorm/typeorm#845]
I have an embedded inside embedded type:
```
@Entity()
export class Business {

  @PrimaryGeneratedColumn()
  public id: number;

 ........

  @Column((type) => TaxBusinessInformation)
  public tax?: TaxBusinessInformation;
}

export class WithholdingTax {

  @Column()
  public amount: string;

  @Column()
  public expiryDate: string;
}
export class TaxBusinessInformation {

  @Column()
  public id: string;

  @Column('simple-array')
  public businessType: [BusinessType];

  @Column((type) => WithholdingTax)
  public withholdingTax?: WithholdingTax;
}
```

After updating to alpha 38 from alpha 37 (the only change), inserting a new business with it's withholdingTax results in:
```
Error:  { QueryFailedError: column "taxTaxWithholdingTaxAmount" contains null values
    at new QueryFailedError (/Users/urigoldshtein/Downloads/typescript-example-master/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query.callback (/Users/urigoldshtein/Downloads/typescript-example-master/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:38)
    at Query.handleError (/Users/urigoldshtein/Downloads/typescript-example-master/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/Users/urigoldshtein/Downloads/typescript-example-master/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.<anonymous> (/Users/urigoldshtein/Downloads/typescript-example-master/node_modules/pg/lib/connection.js:118:12)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
  name: 'QueryFailedError',
  length: 165,
  severity: 'ERROR',
  code: '23502',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'business',
  column: 'taxTaxWithholdingTaxAmount',
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '4189',
  routine: 'ATRewriteTable',
  query: 'ALTER TABLE "business" ADD "taxTaxWithholdingTaxAmount" character varying NOT NULL',
  parameters: [] }
```

My understanding was that because of the `?` on both nested types, it is suppose to be ok to have null values (and it worked before the update).
The DB is Postgres.
Thank you for your amazing work!

**Comment by Urigo** [comment]
I found another bug with embedded entities, maybe related maybe not:

My entity has two fields from the same type:
```
  @Column((type) => classC)
  public fieldA?: classC;

  @Column((type) => classC)
  public fieldB?: classC;
```

When I create an instance of the entity with a new database (creating table), I get the following error message:
```
Error:  { QueryFailedError: column "receiverOriginalBankDataReceiverOriginalBankDataTransferDataOri" specified more than once
    at new QueryFailedError (/Users/urigoldshtein/Downloads/typescript-example-master/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query.callback (/Users/urigoldshtein/Downloads/typescript-example-master/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:38)
    at Query.handleError (/Users/urigoldshtein/Downloads/typescript-example-master/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/Users/urigoldshtein/Downloads/typescript-example-master/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.<anonymous> (/Users/urigoldshtein/Downloads/typescript-example-master/node_modules/pg/lib/connection.js:118:12)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
  name: 'QueryFailedError',
  length: 161,
  severity: 'ERROR',
  code: '42701',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '1491',
  routine: 'MergeAttributes',
  query: 'CREATE TABLE "transaction" ("id" SERIAL NOT NULL, "amountSent" numeric(18,5), "amountReceived" numeric(18,5), "expectedAmount" numeric(18,5), "arrivedAtReceiver" TIMESTAMP, "sentFromSender" TIMESTAMP, "expectedArrival" TIMESTAMP, "currency" character varying NOT NULL, "country" character varying NOT NULL, "transactionKind" character varying NOT NULL, "relatedTransactionFeesReceiverId" integer, "relatedTransactionFeesSenderId" integer, "senderId" integer, "receiverId" integer, "taxId" integer, "senderOriginalBankDataId" character varying, "senderOriginalBankDataDescription" character varying, "senderOriginalBankDataSenderOriginalBankDataTransferDataOriginname" character varying, "senderOriginalBankDataSenderOriginalBankDataTransferDataOriginaccount" character varying, "receiverOriginalBankDataId" character varying, "receiverOriginalBankDataDescription" character varying, "receiverOriginalBankDataReceiverOriginalBankDataTransferDataOriginname" character varying, "receiverOriginalBankDataReceiverOriginalBankDataTransferDataOriginaccount" character varying, PRIMARY KEY("id"))',
  parameters: [] }

```

**Comment by pleerock** [comment]
> After updating to alpha 38 from alpha 37 (the only change), inserting a new business with it's withholdingTax results in:

are you sure? I made only small change there which should not affect this functionality

> My understanding was that because of the ? on both nested types, it is suppose to be ok to have null values

No, "?" is not reflected anyhow runtime, so its not possible to determine if it can be nullable or not based on it. All columns are always nullable: false by default, which means they all are required. If you want to change this behaviour you set `nullable: true` on a column:

```ts
@Column({ nullable: true })
a: string;
```

Also I need a short example how do you fill your models with data to reproduce issue. 

Regarding to second issue, can you please create a separate issue with complete description, complete models and how to reproduce this issue. What do you mean by "new database"? Is it separate connection with its own database or what?

**Comment by Urigo** [comment]
@pleerock yes, I've made sure that this was the only change...
I reverted it back to 37 and it worked like a charm, then back again to 38 and the same thing.

I will create an example of the creation and a new issue tomorrow, but for your question what is a new database - I've just dropped all the tables and created them again.

**Comment by Urigo** [comment]
@pleerock so just to make sure, if I want it to be nullable, I can't put it on the field itself but just on all the subfields?
```
  @Column((type) => WithholdingTax)
  public withholdingTax?: WithholdingTax;
```

**Comment by pleerock** [comment]
> if I want it to be nullable, I can't put it on the field itself but just on all the subfields? 

Each column you want to be nullable you mark as nullable. Im talking about column, not embed column like in your example. Following:

```ts
@Column((type) => WithholdingTax)
  public withholdingTax?: WithholdingTax;
``` 

does not produce any column in the database and cannot be nullable or not nullable. Only its columns are created in the database and each column defines if they are nullable or not.

**Comment by Urigo** [comment]
@pleerock ok I get it now!

about the other issue, I think that the reason might be that the generated field name is too long and being cut out....

Because the error specified the field name `receiverOriginalBankDataReceiverOriginalBankDataTransferDataOri`
Which is the start of two fields being generated (also taken from the error):
`receiverOriginalBankDataReceiverOriginalBankDataTransferDataOriginname`
and
`receiverOriginalBankDataReceiverOriginalBankDataTransferDataOriginaccount`

is there a limit for creating field names?  is it something new with the new versions?

**Comment by pleerock** [comment]
ohhh that looks really long. I don't really recommend you to use such long names. Maybe you simplify your object graph and shorten column names? I really smells bad now.

Each database has limitations on alias name length and column name length, maybe you have problems because of those limitations.

**Comment by Urigo** [comment]
wierd though that it works on alpha 37 and not on 38....
might be worth adding a test case for it?

**Comment by pleerock** [comment]
There are lot of tests regarding to embeds already... Not sure how it should look like because I dont understand what was changed between 37 and 38 that caused you such issue. You can contribute with test btw.

**Comment by Urigo** [comment]
yes will start doing that.
In the meantime, I figured the issues and was able to update so closing for now and will add some tests, even just for the sake of documentation in a couple of days

**Comment by pleerock** [comment]
You can define your own name for columns using `name` property - this way you can create a shorter column name.
