### ISSUE TITLE
Can not create indexes of materialized views

### ISSUE THREAD

**Issue by jeromeSH26** [typeorm/typeorm#8459]
running last release of typeorm.

Adding` @Index() `to a[ @ViewColumn()](url) of a materialized view doesn't create the index. has to create it manually

```
@ViewEntity({
  name: "vw_all_articles",
  expression: sqlExpression,
  materialized: true,
})
class AllArticlesView implements TALLArticlesWiew {
  @Index("idxAllArticleVW_Article_id", {
    unique: true,
  })
  @ViewColumn()
  article_id: IArticles["id"];
}
```

Can see that the materialized view is well created but not the index.
![image](https://user-images.githubusercontent.com/51024915/146051261-3aa7c5b9-a08d-4f3f-8e87-0ea0e456c2ea.png)

**Comment by sgronblo** [comment]
It also doesn't seem to work when adding the `@Index` to a `@ViewEntity` either
