### ISSUE TITLE
Add support for CockroachDB

### ISSUE THREAD

**Issue by xeoneux** [typeorm/typeorm#846]
Is there support for CockroachDB planned?

**Comment by pleerock** [comment]
According to [this docs](https://www.cockroachlabs.com/docs/stable/build-a-nodejs-app-with-cockroachdb.html) cockroachdb works with `pg` driver, and TypeORM uses exactly this driver which means it should support CockroachDB as well.

**Comment by knocte** [comment]
Has someone tested this? Just to be sure.

**Comment by knocte** [comment]
(Dupe https://github.com/typeorm/typeorm/issues/1040 has more info.)
