### ISSUE TITLE
NestJS/PostgresQL: "Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated value"

### ISSUE THREAD

**Issue by Arkady-Skvortsov** [typeorm/typeorm#8470]
## Issue Description
Hi guys, so, I want to do register my user in big widget, but... I don't know what happening when I try to "create new user" if I don't have and exception; Earlier - I didn't seen something like that: "Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated value"; I have a NestJS(♥) and PostgresQL for that; 

### Expected Behavior
Create a new user, if I don't have an any exception

### Actual Behavior
"Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated value"

```
// include the output in code tags like these!
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
```

### My Environment
NestJS/Nodejs

| Operating System  Windows  |    10      |
| Node.js version     | 16.13.0  | 
| Typescript version  | 4.5.2  | 
| TypeORM version     | 0.2.41  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.     
[README.md](https://github.com/typeorm/typeorm/files/7739462/README.md)

**Comment by Ginden** [comment]
@Arkady-Skvortsov Can you provide failing code (or close issue if you resolved it)?

**Comment by yoni333** [comment]
you probably pass undefine or null value....
if you use the repository update method - this method know how to handle partial object ( that represent partial db row)/
i got the same error message - when i passed undefined...  console.log the object before you pass it to the update method...
