### ISSUE TITLE
Update jsprim to 1.4.2

### ISSUE THREAD

**Issue by erkinalp** [typeorm/typeorm#8480]
### Steps to Reproduce

None required. TypeORM depends on jsprim 1.4.1, which depends on a vulnerable version of json-schema.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 -  ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by stim371** [comment]
Thanks for reporting. This was resolved in https://github.com/typeorm/typeorm/commit/97e1dc17e8a858c7d92a2072329f77ba98fb06b9
