### ISSUE TITLE
OneToMany, ManyToMany missing some RelationOptions

### ISSUE THREAD

**Issue by dlindenkreuz** [typeorm/typeorm#849]
From all relation decorators, `@OneToMany` and `@ManyToMany` seem to be missing a full RelationOptions object. At least it should be possible to make `@OneToMany` `nullable` and `primary`.

This functionality seems to have vanished in this commit related to #151: https://github.com/typeorm/typeorm/commit/11817adc2e48c0bb56d6cc8a7870db4a58b7c93b#diff-21e67927993f10e8f4f981ccb8becdaf

**Comment by dlindenkreuz** [comment]
Possible workaround using a type assertion:

```typescript
@OneToMany(type => Module, module => module.rooms, { nullable: false } as RelationOptions)
myColumn: Module
```

**Comment by pleerock** [comment]
> @OneToMany(type => Module, module => module.rooms, { nullable: false } as RelationOptions)
myColumn: Module

it simply does not affect anything. `nullable: false` means it will set `NOT NULL` to column it creates. Both `OneToMany` and `ManyToMany` do not create any column.

**Comment by dlindenkreuz** [comment]
lol yeah thanks, makes sense! I mixed up `@ManyToOne` and `@OneToMany`. 😬
