### ISSUE TITLE
Column option insert: false, update: false

### ISSUE THREAD

**Issue by apezel** [typeorm/typeorm#85]
JPA provides a column option {insert: false, update: false} that allows to exclude the column from insert and update statements, respectively.
It would be nice to add this feature to typeorm : can be really useful with columns updated internally in the database.
Also this feature may be a first step towards columns defined as formulas (ex: subselect)
I can contribute.

By the way, thank for your work on typeorm. Javascript was missing an ORM of this quality !

**Comment by pleerock** [comment]
Hi, what are use cases for `insert: false` but `update: true` ? question is obliviously then how to insert the data?

**Comment by apezel** [comment]
the goal is to map a column whose data is provided by the DB itself. For example by a trigger.
Another use case would be a formula like hibernate does : 

```javascript
@Column("select count(*) from my_table")
```
But this is another topic.

**Comment by apezel** [comment]
Sorry i misunderstood the question. You're right, insert:false and update: true doesn't seem to have a real use case. Maybe a single annotation persist: true|false would be more relevant ?

**Comment by pleerock** [comment]
if so, then what should `persist: false` do? block both inserts and updates? looks pointless, why do you need a column where you cant insert or update anything?

**Comment by apezel** [comment]
Because the data may be provided by a trigger in the db. In this case the data may be selected but not updated.

**Comment by pleerock** [comment]
if this is a real-world case and people need it, we can add it. in this case its better to add `insert: boolean; update: boolean;` rather then `persist: boolean`. It would be great if you can contribute, however currently Im refactoring code and there are lot of breaking changes of exist code, so even if you do it right now (until I finish) your changes may not be so helpful and can bring only conflicts. So its better to do it later (once I finish what I currently do). If you want to contribute it will be great if you can contribute on any other area too.

**Comment by apezel** [comment]
Ok, the question now is : how typeorm should behave after persist ? Should it select the column value form db (assuming that it may have be updated during save), leave it null or keep last provided value ?

**Comment by pleerock** [comment]
do you mean how it should behave after persist with insert: false or update: false? For insert: false I think it should simply insert null (plus column must be nullable). And during update: false it simply should ignore this field and don't update it. I see value in update: false, but to be honest I almost don't see value in insert: false

**Comment by apezel** [comment]
I think column tagged with insert|update: false should be totally ignored from statement. I suppose inserting NULL may cause side effects.
But as i think about it, setting insert|update: false on a column could result in incoherences. My first idea was to allow the mapping of a column populated by a trigger. But in this case, if i load an entity, modify it then save it, the resulting entity may not reflect the data in the database because there's no re-select after save, i guess. And that's not what i expect.
JPA use insert|update: false to allow to map a field more than once. That's a different use case wich, i think, is not needed in typeorm.
Actually, what i'm looking for would be better implemented by a new decorator.

For example : 
```javascript
@CalculatedColumn("column name | procedure call | subselect")
field:type
```
CalculatedColumn : 
- is ignored by default during schema generation, this behavior could be configured with an option
- is **always** ignored during insert and update
- the value of the field is reselected after a presist

**Comment by pleerock** [comment]
we need to think more about proposal and design on this feature. 

* you told *the value of the field is reselected after a presist* - does it mean value will be reselected and saved into db in this table's column?
* what type of data this calculated field can store?
* CalculatedColumn's value is updated after each insert and update, correct? Can this be controlled?
* what `"column name | procedure call | subselect"` is exactly? is it procedure call or subselect?
* if its a procedure call then it should be a simple string - a name of the procedure?
* if its a subselect then what I think we can specify a class here which will return a data using query builder?
* let take some simple and real world example of this feature

**Comment by apezel** [comment]
> you told the value of the field is reselected after a presist - does it mean value will be reselected and saved into db in this table's column?

Value may need a re-select after an update or an insert because the value of the cell may have changed. But field value is never persisted into the db

> what type of data this calculated field can store?

I guess the same types that a standard @Column can store

> CalculatedColumn's value is updated after each insert and update, correct? Can this be controlled?

Re-select could be an option. Something like that.
```javascript
@CalculatedColulmn("myColumnName", {selectAfterEntityPersist: true})
```

> what "column name | procedure call | subselect" is exactly? is it procedure call or subselect?

May be : 
- a column name -> case of a cell updated by a trigger. For example a sequence.
- a call to a ~~procedure~~ function
```javascript
@CalculatedColulmn("sayHelloTo('world')")
helloMessage:string
```
Generate : 
```sql
select id, sayHelloTo('world') as helloMessage from ...
```

- a subselect
```javascript
@CalculatedColulmn("(select count(*) from another_table)")
countFromOtherTable:number
```
* function and subselect is more difficult to handle correctly because they may use references to current request * For example : 

```javascript
@Column()
userName:string;
@CalculatedColulmn("(select sum(a.price) from another_table a where a.username = this.userName")
```

> if its a procedure call then it should be a simple string - a name of the procedure?

Procedure call doesn't make sense. I made a mistake. It should only support function call.

> if its a subselect then what I think we can specify a class here which will return a data using query builder?

Yes, could be better than raw sql. Do you mean a class function that takes a QueryBuilder in input and perform the subselect ?

**Comment by pleerock** [comment]
> a column name -> case of a cell updated by a trigger. For example a sequence.

doesnt make lot of sense for me.

> a call to a function

> a subselect

how do we determine if given string is a function call or subselect? Can be reliably assert it?

> function and subselect is more difficult to handle correctly because they may use references to current request * 

ohh this mades things quite complicated

> Yes, could be better than raw sql. Do you mean a class function that takes a QueryBuilder in input and perform the subselect ?

yes we can support both features I think. raw sql queries + function that maybe returns query builder + class that implements some interface and its implemented method returns maybe query builder. 

another question is: do we  always put these calculated columns function calls and subqueries into list of additional selects of the main query? If yes, then do every database supports subqueries in selects? And how it will affect pagination problems (limit may not work correctly?)

**Comment by pleerock** [comment]
@apezel any further thoughts on this issue?

**Comment by szkumorowski** [comment]
@pleerock 
I think update: false is quite important as this case show up in real scenarios when field should be never changed after initialize, for example: createdAt date, relation id and any other value based on business logic

**Comment by pleerock** [comment]
For `update: false` we already have a `readonly: true` option. For insertion... Not sure if we must to add one another flag... From your use case probably disabling insertion will lead to disabling updation as well. Then maybe it shall be controlled by some validation rules, not by ORM? `update: false` (`readonly: true` now) has much more use cases.

**Comment by szkumorowski** [comment]
If I understand correctly, the readonly means insert could set value, but update not ?

**Comment by szkumorowski** [comment]
Then I think it solves the problem, with insert: false - the before/after insert trigger will override the value if this is database responsibilty.

Thank you

**Comment by ciber96** [comment]
Hi, any updates on this feature?

**Comment by thalysonalexr** [comment]
after a long time looking for this I found the solution, thanks author!

**Comment by AAhsanSiddiqui123** [comment]
i am using 0.3.20 typeORM latest version in 2024 but i am not able to use  insert:false in Column decorator like this(  @Column('citext', { name: 'slug', nullable: true, insert: false })) 

according to the below commit i should be able to do that 
**adds an option to control whether columns are inserted by default #4035**

i want to insert only specific column not all column with default value i have permission structure in database witch is not allow me inset column other than some specific column
