### ISSUE TITLE
My entity is not recognized

### ISSUE THREAD

**Issue by lev-kuznetsov** [typeorm/typeorm#850]
For whatever reason when I open the connection it seems to be ignoring one of the classes I list as an entity. Here's how I create my connection:

```
createConnection({
  type: 'sqlite',
  database: 'test',
  storage: 'test.db'
  synchronize: true,
  entities: [
    Item,
    Dataset,
    Block,
    Dimension,
    Project
  ]
})
```
Out of these, the `Project` is not found, when I try to create a repository for project I get this:

```
No repository for "Project" was found. Looks like this entity is not registered in current "default" connection?
```
The test.db file is created and browsing that I see tables for the other entities but not Project. This is the entity:

```
@Entity()
export class Project {
  @PrimaryGeneratedColumn()
  id: number

  @Column({unique: true})
  name: string

  @OneToMany(type => Item, item => item.project, {lazy: true})
  items: Item[]
}
```
One thing that's different about Project is that it's part of this package. The other entities are part of a different package @any4/model

![DB screenshot](http://i68.tinypic.com/oia9vs.png)

**Comment by pleerock** [comment]
> One thing that's different about Project is that it's part of this package. 

what do you mean by "it's part of this package"? And what is "different package" then?

This is absolutely working feature and I can't even imagine bug that can bring problem you are describing.  Please check everything on your side once again, make sure you setup reflect-metadata properly and all required tsconfig options and try again. If you stuck create a sample git repo with minimal code required to reproduce your problem

**Comment by lev-kuznetsov** [comment]
I've created an npm package with some entities that I tend to reuse in another package. This package is here: [@any4/model](https://www.npmjs.com/package/@any4/model). Then I created another project where I intend to use them and which also includes some other entities. I've uploaded source here: [my api project](https://github.com/lev-kuznetsov/any4api) The entities from the model project show up in the database but not the entity from the current project where I create the connection.

**Comment by pleerock** [comment]
Im sorry but I wont spend my time figuring out what is going on in your projects. If you create a minimal possible reproduction example which I can checkout and setup in one click I'll take a look on it.

**Comment by lev-kuznetsov** [comment]
Hi; apologies as I was away for a few days; I think I have a minimum project reproducing the issue here: https://github.com/lev-kuznetsov/typeorm-bug

**Comment by pleerock** [comment]
First, tsc fails when I try to compile your project:

```
Umeds-MBP-2:typeorm-bug pleerock$ tsc
test/connection-test.ts(7,32): error TS2339: Property 'getRepository' does not exist on type 'void'.
test/connection-test.ts(12,32): error TS2339: Property 'getRepository' does not exist on type 'void'.
```

Second, I don't understand why do you do it this way with createConnection: `export default createConnection`. 

I didn't run your test but used connection itself and it seems working fine:

```ts

export default createConnection({
  type: 'sqlite',
  database: 'any4.db',
  synchronize: true,
  entities: [Project, Item, Dataset, Block, Dimension]
}).then(connection => {
  const projectRepository = connection.getRepository(Project);
  console.log("Connection has established: ", projectRepository);
}).catch(error => console.log(error));
```

Result:

```
typeorm-bug pleerock$ node ./src/connection.js
Connection has established:  Repository {
  manager:
   EntityManager {
     repositories: [ [Circular] ],
     connection:
      Connection {
        isConnected: true,
        migrations: [],
        subscribers: [],
        entityMetadatas: [Array],
        name: 'default',
        options: [Object],
        logger: [Object],
        driver: [Object],
        manager: [Circular],
        namingStrategy: DefaultNamingStrategy {},
        queryResultCache: undefined } },
  metadata:
   EntityMetadata {
     childEntityMetadatas: [],
     tableType: 'regular',
     isJunction: false,
     ownColumns: [ [Object] ],
     ownRelations: [],
     relations: [],
     columns: [ [Object] ],
     relationIds: [],
     relationCounts: [],
     indices: [],
     foreignKeys: [],
     embeddeds: [],
     listeners: [],
     generatedColumns: [ [Object] ],
     primaryColumns: [ [Object] ],
     parentIdColumns: [],
     oneToOneRelations: [],
     ownerOneToOneRelations: [],
     oneToManyRelations: [],
     manyToOneRelations: [],
     manyToManyRelations: [],
     ownerManyToManyRelations: [],
     relationsWithJoinColumns: [],
     lazyRelationsWrapper: LazyRelationsWrapper { connection: [Object] },
     parentClosureEntityMetadata: undefined,
     target: [Function: Project],
     engine: undefined,
     givenTableName: undefined,
     skipSync: false,
     targetName: 'Project',
     tableNameWithoutPrefix: 'project',
     tableName: 'project',
     name: 'Project',
     isClassTableChild: false,
     isSingleTableChild: false,
     isEmbeddable: false,
     isClosureJunction: false,
     isClosure: false,
     isAbstract: false,
     isRegular: true,
     orderBy: undefined,
     inheritanceType: undefined,
     discriminatorValue: 'Project',
     treeParentRelation: undefined,
     treeChildrenRelation: undefined,
     hasMultiplePrimaryKeys: false,
     createDateColumn: undefined,
     updateDateColumn: undefined,
     versionColumn: undefined,
     discriminatorColumn: undefined,
     treeLevelColumn: undefined,
     objectIdColumn: undefined,
     propertiesMap: { id: 'id' },
     hasNonNullableRelations: false },
  queryRunner: undefined }
```

**Comment by pleerock** [comment]
closing as no answer from author.

**Comment by danursin** [comment]
Most common reason for this error is missing @Entity annotation on your entity model classes.

**Comment by lev-kuznetsov** [comment]
My problem here was circular dependencies in my files

**Comment by zaksesti-ns8** [comment]
I guess OP figured it out but I'm having the same problem and it would be nice to know what caused it. Works when running the app but fails to find the Entity when creating the repository in a test. (Jest).

**Comment by Evilart86** [comment]
I had the similar problem. It turned out that I call getRepositore earlier than my database get connected.
Try to check this debugger. It helped me

**Comment by lipsumar** [comment]
For me the issue was circular dependency. I solved it by applying the technique described here: https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de

not super happy with it, but it works
