### ISSUE TITLE
connection-api falsely imports getEntityManager instead of getManager

### ISSUE THREAD

**Issue by saeidjoker** [typeorm/typeorm#8505]
### What was unclear or otherwise insufficient?

In connection-api, there's a usage of getEntityManager, but it should be changed to getManager

### Recommended Fix

PR#8504

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment]
fixed in #8504
