### ISSUE TITLE
Feature request: Join on Postgres JSONB functions

### ISSUE THREAD

**Issue by peacechen** [typeorm/typeorm#8516]
## Feature Description

I have an array of IDs in a Postgres JSONB field that I need to join the secondary table on. Due to PG limitations such as inability to pass set-returning functions to Joins, I need to create a temporary table by Joining `jsonb_array_elements_text`.

TypeORM expects the first parameter of a Join method to be a table name. Passing in a JSONB method causes that to be wrapped in quotes, which expectedly fails. See below for code snippets.

### The Problem

```
    queryBuilder
      .innerJoin("jsonb_array_elements_text(tableA.fields->'scIds')", "scid", "true")
      .addSelect("tableB.fields->>'number'", "container_number")
      .innerJoin(
        TableB,
        "tableB",
        "scid::uuid = tableB.id"
      )
      .orderBy("container_number", "ASC");
```

The desired SQL output is
```
SELECT ...
FROM "public"."tableA" "tableA" 
INNER JOIN jsonb_array_elements_text(tableA.fields->'scIds') scids on true 
INNER JOIN "public"."tableB" on scids::uuid = tableB.id
WHERE ... (conditions)
```

TypeORM expects a model name on Join methods which puts quotes around `jsonb_array_elements_text` and splits on `.`, resulting in:
```
INNER JOIN  "jsonb_array_elements_text(tableA"."fields->'scIds')"
```

### The Solution

Two potential feature adds:

1. Detect `json*` in the first Join arg and don't wrap it in quotes.
2. Add new methods such as `rawInnerJoin` and `rawLeftJoin` that use the first arg as-is without parsing.

### Considered Alternatives

We crafted a subquery on the IDs array but it is VERY slow (8-10 seconds vs sub-second).

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
> I have an array of IDs in a Postgres JSONB field that I need to join the secondary table on. Due to PG limitations such as inability to pass set-returning functions to Joins

Postgres can join on such fields.

```sql
WITH table_1 AS (
    SELECT 5 "foo", '[1, 4, 9, 16, 25]'::json bar
), table_2 AS (
    SELECT i FROM generate_series(0, 30) z(i)
)
SELECT * FROM table_1
INNER JOIN table_2 ON table_2.i IN (SELECT v::int FROM json_array_elements_text(bar) t(v))
```

**Comment by peacechen** [comment]
Thanks @Ginden. That's some nifty PG SQL. 

Are the values passed to `generate_series` IDs from table_2? Those values aren't known ahead of time. 

Would you mind sharing a snippet of how the TypeORM would look?

**Comment by Ginden** [comment]
@peacechen I used [CTE](https://www.postgresql.org/docs/14/queries-with.html) for short snippet purposes.

Query built using query builder can look like (I didn't test it):

```ts
    queryBuilder
      .addSelect("tableB.fields->>'number'", "container_number")
      .innerJoin(
        TableB,
        "tableB",
        "tableB.id IN (SELECT v::uuid FROM json_array_elements_text(tableA"."fields->'scIds') t(v))"
      )
      .orderBy("container_number", "ASC");
```

Also, there is following overload for `innerJoin` method:

```
    innerJoin(subQueryFactory: (qb: SelectQueryBuilder<any>) => SelectQueryBuilder<any>, alias: string, condition?: string, parameters?: ObjectLiteral): this;
```

So you can join against subquery.

**Comment by peacechen** [comment]
You're a genius @Ginden !

The query works well and has decent performance at around 4 sec on our dataset.

Another question if you don't mind: what does the `t(v)` method do?  `json_array_elements_text` takes a single argument so I'm confused by that syntax.

**Comment by Ginden** [comment]
>  what does the t(v) method do?

It isn't a method - it defines alias `t` with single column named `v`.

**Comment by peacechen** [comment]
That's an interesting syntax for aliases. I've only used old-school `AS` for that.

Your method works respectably and will tide us over for the time being. However performance is noticeably slower than joining on `jsonb_array_elements_text` (4 sec vs sub-second). Must be a built-in optimization of PG.

It would still be a valuable feature to be able to Join `jsonb_array_elements_text`, both from a performance and readability standpoint.

**Comment by Ginden** [comment]
> However performance is noticeably slower than joining on jsonb_array_elements_text (4 sec vs sub-second). Must be a built-in optimization of PG.

Check query plan or use subquery.

**Comment by Ginden** [comment]
I'm closing this issue - it seems to be out of scope for ORM to implement this unusual pattern, and there are workarounds.

**Comment by kiran-concertina1** [comment]
https://written9.github.io/Nk0AjnhT2s0my8VYZqMWwN/



Behold this explanation
