### ISSUE TITLE
Support For Old SQL Server (SQL Server 2018 R2)

### ISSUE THREAD

**Issue by Metazhoa** [typeorm/typeorm#8517]
## Feature Description
SQL Syntax Support For `SQL Server 2018 R2`

### The Problem
calling
``` 
Users.find({skip: skip, take: take, order:{id:"ASC"}}); 
```
causing error `Invalid usage of the option NEXT in the FETCH statement`

### The Solution

for example, i want to query user id, username and password from table `users`
then my statement would be like
```
SELECT 
     users.id, users.username, 
     users.password 
FROM users 
WHERE users.username = 'mikey'
```
then to use skip and limit for these statement i add `ROW_NUMBER()` function from SQL Server.
so the statement would look like this
```
SELECT 
     users.id,
     users.username, 
     users.password, 
-->  ROW_NUMBER() OVER (ORDER BY users.id) AS Seq,
FROM users
```
running these statement will output like this
```
id | username  | password   | Seq |
--------------------------------------
 1 | crow      | somepass1  | 1
 3 | mike      | somepass2  | 2
 5 | jason     | somepass3  | 3
 4 | allison   | somepass4  | 4
 7 | brewr     | somepass5  | 5
 6 | reqeui    | somepass6  | 6
```
now to create skip and limit outputs from sql, i just query the result of the pevious query like
```
SELECT 
     users.id, 
     users.username, 
     users.password 
FROM(
	// (Main Query) Real Query Begin //
	SELECT 
	     users.id,
	     users.username, 
	     users.password, 
  		 ROW_NUMBER() OVER (ORDER BY users.id) AS Seq
  	// (Main Query) Real Query End //
	)users
WHERE Seq BETWEEN 1 AND 8
```

now to run query and complete data presentation using typeORM Entity
code below is only for example by using `JOIN` inside the main query, you can also use any Operation inside Main Query
```
let db_version = "2018R2"
let skip = 0
let take = 5
var query = ""
let tableName = Users.getRepository().metadata.tableName
if(filterUser != undefined) {
	var query = `${tableName}.name LIKE "%${filterUser}%"`
	if(filterGroup != undefined) {
		query = query + ` AND ${tableName}.groupId = ${filterGroup}`
	}
} else {
	if(filterGroup != undefined) {
		query = `${tableName}.groupId = ${filterGroup}`
	}
}
let connection = getConnection()
// Check if Current Connection is using MS SQL Server
if(connection.options.type == "mssql" && db_version == "2018R2") {
	take = take + skip
	skip = skip + 1
	if(query.length > 2) query = " WHERE " + query
	let users = await Users.query(`
	SELECT 
		"Users"."id", 
		"Users"."name", 
		"Users"."username",
		"Users"."password", 
		"Users"."groupId", 
		"Users__group_id", 
		"Users__group_name"
	FROM (
		SELECT 
			"Users"."id", 
			"Users"."name",
			"users"."username", 
			"Users"."password", 
			"Users"."groupId", 
			"Users__group"."id" AS "Users__group_id", 
			"Users__group"."name" AS "Users__group_name",
			ROW_NUMBER() OVER (ORDER BY "users"."id") AS Seq
		FROM "users" "Users"
		LEFT JOIN "user_groups" "Users__group" 
		ON "Users__group"."id" = "Users"."groupId"
		${query}
	)"Users"
	WHERE Seq BETWEEN ${skip} AND ${take}`)

	users = await users.map((user:any) => {
		return {
			id:user.id , 
			name:user.name,
			username:user.username,
			password:user.password,
			groupId: user.groupId,
			group: {
				id: user.Users__group_id,
				name:user.Users__group_name,
			}
		}
	})
	return await Users.getRepository().create(users)
} else { 
	// If Not MSSQL and DB Version is not 2018R2
	Users.find({skip: skip, take: take, order:{id:"ASC"}, where:query, relations: ["group"]}); 
}
```
the output will be like
```
[
  {
    id: 1,
    name: 'auther cruz',
    username: 'mikailea',
    password: 'rnS8b1oR1uDnmXlGo89vcv$10$MX3yL0TGEc.2rnS8b1oR1uDnmXlGo89vcvI',
    groupId: 2,
    group: {
    	id: 2,
    	name:'Owner',
    }
  },
  {
    id: 4,
    name: 'Mike Axel',
    username: 'Reangealrea',
    password: 'rnS8b1oR1uDnmXlGo89vcv$10$MX3yL0TGEc.2rnS8b1oR1uDnmXlGo89vcvI',
    groupId: 2,
    group: {
    	id: 2,
    	name:'Owner',
    }
  },
  {
    id: 5,
    name: 'Arrachnid Pasto',
    username: 'arealkrea',
    password: '$2b$10$MX3yL0TGEc.2rnS8b1oR1uDnmXlGo89vcvIdUkVGWKM0jUj5Z7ea.',
    groupId: 2,
    group: {
    	id: 2,
    	name:'Owner',
    }
  },
  {
    id: 6,
    name: 'adrachan Auler',
    username: 'namstefa',
    password: '$2b$10$lZkhDfDlo4UgrTNrcDL4kuI3qVZg6gCHlo8pM7D0QAkq4dgC5Rqd.',
    groupId: 2,
    group: {
    	id: 2,
    	name:'Owner',
    }
  },
  {
    id: 7,
    name: 'Roer Eraver',
    username: 'wegneras',
    password: '$2b$10$DxbaEhx3i6.sHp3TP/qyZuPXszmXoDxVkTr2ZeTlXXj8nari2N7uy',
    groupId: 2,
    group: {
    	id: 2,
    	name:'Owner',
    }
  }
]
```

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | yes           |

### Are you willing to resolve this issue by submitting a Pull Request?

 -  ✖️Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment]
I can't find `SQL Server 2018 R2` version in [SQL Server versions](https://sqlserverbuilds.blogspot.com/). Did you mean `SQL Server 2008 R2`? If yes, its EOL is 2019 and adding support for EOL version does not make sense.
