### ISSUE TITLE
Unclear where TypeORM looks for ormconfig files and why it's not configurable

### ISSUE THREAD

**Issue by martinsik** [typeorm/typeorm#8546]
### What was unclear or otherwise insufficient?

I think it's not very well documented where TypeORM looks for `ormconfig` files. There's the following document [using-ormconfig.md](https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md) that says:

> You only need to create a ormconfig.[format] file in the root directory of your application (near package.json), put your configuration there and in your app call createConnection() ...

But what is meant by "your application"? Is it the entry point of the application or is it the script (file) that called `getConnectionOptions()`? From what I've tried it looks like TypeORM starts looking from the package root containing the file that invoked `getConnectionOptions()` function which is problematic in a use-case where I have a shared package that calls `getConnectionOptions()`. In this case TypeORM expects the `ormconfig` file to be in the shared package root (?) which doesn't make sense.

I don't understand why I can't configure the base directory from where TypeORM will be looking for config files because it looks like `ConnectionOptionsReader` does [support that](https://github.com/typeorm/typeorm/blob/master/src/connection/ConnectionOptionsReader.ts#L20-L25) but I wasn't able to find any way to pass it any options because with `getConnectionOptions()` I can only set `connectionName`.

### Recommended Fix

It should be more clarly explained in what directories and why TypeORM looks for `ormconfig` files and what's the connection between `getConnectionOptions()` call and the directories it searches.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.
 - ✅ None

**Comment by mickaelmesdocteurs** [comment]
I guess explanation could be more clear yes, but you should only have one `package.json`
> the root directory of your application (near package.json)

Also you actually can put your configuration file wherever you want and pass the content on the module loading :

```js
// file `ormconfig.ts`
const config: any = {
    host: "localhost",
    port: 3306,
    username: "test",
    password: "test",
    database: "test",
    logging: true,
    synchronize: true,
    entities: [
        "entity/*.js"
    ],
    subscribers: [
        "subscriber/*.js"
    ],
    entitySchemas: [
        "schema/*.json"
    ],
    migrations: [
        "migration/*.js"
    ],
    cli: {
        entitiesDir: "entity",
        migrationsDir: "migration",
        subscribersDir: "subscriber"
    }
};

export = config;
```

```js
import * as ormconfig from '../configs/custom-path/ormconfig';

@Module({
  imports: [
    TypeOrmModule.forRoot(ormconfig),
  ],
  //...
})
```

**Comment by AlexMesser** [comment]
`ormconfig` support was deprecated in `0.3.0` and will be completely removed in `0.4.0`. So this issue is no longer relevant.

**Comment by timur-gilauri** [comment]
I wonder why do they put such a significant changes into minor updates.. So the code I was writing is not working any more. It is a breaking change, isn't it?
