### ISSUE TITLE
Preload function doesn't load soft-deleted entities

### ISSUE THREAD

**Issue by Anxium** [typeorm/typeorm#8548]
## Issue Description
When i want to preload a soft deleted entity (entities with deleted_at field not null), it returns undefined.
I'm using it to update my entity, so i have a condition in order to throw an error if the preloaded entity is empty.

### Expected Behavior
I expect that the preload function returns the entity even if the entity is soft deleted.
OR
Add a parameter that allow us to load soft deleted entities

### Actual Behavior
The preload function doesn't load the soft deleted entities  and then it returns undefined.

My code:
```typescript
console.log({ id });
const project = await queryRunner.manager.preload(Project, {
        id,
        ...projectDto,
 });

console.log({ project });
if (!project) {
   throw new NotFoundException(`Project with id "${id}" not found`);
}
```
The logs:
```
{ id: '85c6d6c2-e279-4993-a0bb-53dafdaed5f2' }
{ project: undefined }
Error: Project with id "85c6d6c2-e279-4993-a0bb-53dafdaed5f2" not found
```
My entity (exported as json from my db):
```json
[
	{
		"id": "85c6d6c2-e279-4993-a0bb-53dafdaed5f2",
		"name": "Oxygen",
		"created_at": "2022-01-20 09:10:04.531245+00",
		"created_by": null,
		"updated_at": "2022-01-20 09:10:04.531245+00",
		"updated_by": null,
		"deleted_at": "2022-01-20 09:10:04.53+00",
		"deleted_by": null,
		...
	}
]
```

### Steps to Reproduce
1. Create an entity with deleted_at not null in your database
2. Try to preload it

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  macOs 12.1
| Node.js version     | 16.13.1 
| Typescript version  | 4.5.4 
| TypeORM version     | 0.2.41
| @nestjs/typeorm     | 7.1.5

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | x            |
| `aurora-data-api-pg` | x            |
| `better-sqlite3`     | x            |
| `cockroachdb`        | x            |
| `cordova`            | x            |
| `expo`               | x            |
| `mongodb`            | x            |
| `mysql`              | x            |
| `nativescript`       | x            |
| `oracle`             | x            |
| `postgres`           | yes            |
| `react-native`       | x            |
| `sap`                | x            |
| `sqlite`             | x            |
| `sqlite-abstract`    | x            |
| `sqljs`              | x            |
| `sqlserver`          | x            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
Looks like a question. Just load it using `.find` method in combination with `withDeleted` option.

**Comment by Anxium** [comment]
Indeed, sorry for the wrong tag.

Based on the pull request in which this issue was mentioned, do you recommend not using the "soft delete" feature and doing a custom implementation in our project ? 

Because the fact that the preload function will not load the soft-deleted entities is not specified in the doc, it can leads to some issues or maybe a duplicate of this issue, what is a waste of time. Then, can I suggest to add it in the doc ?

Thanks for you response !

**Comment by pleerock** [comment]
> Based on the pull request in which this issue was mentioned, do you recommend not using the "soft delete" feature and doing a custom implementation in our project ?

use it until it satisfy your needs. If it becomes a bottleneck and you miss some features - you can go with your own implementation.

> Because the fact that the preload function will not load the soft-deleted entities is not specified in the doc, it can leads to some issues or maybe a duplicate of this issue, what is a waste of time. Then, can I suggest to add it in the doc ?

I'm not sure about future of `preload` method. Better to use `find` to load entity. May I know your use cases (simplified) of `preload` method and why you use it instead of using `find`?

**Comment by Anxium** [comment]
> May I know your use cases (simplified) of preload method and why you use it instead of using find?

I'm using it to load the entity and all its relations, and replace the data in one-time. It seemed faster than find and replace. 
But the work-around I did, is what you answered, i'm using a find with `withDeleted: true` now
