### ISSUE TITLE
Query via SQL.

### ISSUE THREAD

**Issue by Chetan11-dev** [typeorm/typeorm#8551]
You are the ones who can answer it so, I ask here this boolean question.
Q) Is the Sql query passed to the database via REST like so.
   GET http://postgress....

**Comment by Ginden** [comment]
@Chetan11-dev This question is incomprehensible. Please clarify what do you mean.

**Comment by Ginden** [comment]
Closing due to no answer.

**Comment by Chetan11-dev** [comment]
Which protocol is used to connect to database HTTP or something like UDP/Websocket
