### ISSUE TITLE
Compilation with ES6 target

### ISSUE THREAD

**Issue by spalt08** [typeorm/typeorm#8562]
Hey!

I was wondering if there is any specific reason for building the source code for the ES5 target?

The source code contains a lot of classes, async/await and others ES6 features which are supported since 2017 (node v7.10.1). It looks like almost all production files are stuffed with polyfills.

Have you checked if it affects the overall performance in a modern node runtime? It makes more sense to use the ES6 target for the `tsc`

**Comment by Ginden** [comment]
There already exists PR for that - https://github.com/typeorm/typeorm/pull/7967

**Comment by Ginden** [comment]
@spalt08 It's not about creating new PR, it's about merging it.
