### ISSUE TITLE
Use typeorm, how to reconnect when we have password rotation?

### ISSUE THREAD

**Issue by wangxia337** [typeorm/typeorm#8563]
We are using typeorm to connect postgres for now, we want change database password every three months, so how to make the connection pool can use new password automatically?

**Comment by AlexMesser** [comment]
For questions / general support, please check out our [Slack channel](https://join.slack.com/t/typeorm/shared_invite/zt-uu12ljeb-OH_0086I379fUDApYJHNuw), [StackOverflow](https://stackoverflow.com/questions/tagged/typeorm) or check [TypeORM's documentation](https://typeorm.io).
