### ISSUE TITLE
The test issue-863 fails sometimes

### ISSUE THREAD

**Issue by JasonMan34** [typeorm/typeorm#8567]
## Issue Description
Test `issue-863.ts` fails sometimes, even if the PR doesn't change anything related to it
This is most easily noticeable in [this PR](https://github.com/typeorm/typeorm/pull/8550), which only fixes a typo in the docs, but still failed a test for:
```
github issues > #863 indices > create schema
       "before all" hook in "github issues > #863 indices > create schema":
     AlreadyHasActiveConnectionError: Cannot create a new connection named "sqlite", because connection with such name already exist and it now has an active connection session.
```
### Expected Behavior
Existing tests should always pass

### Actual Behavior
Test `issue-863.ts` fails sometimes

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
Thanks for the report and thanks @TheNoim for the fix!
