### ISSUE TITLE
Soft remove calls entity subscriber with empty updatedColumns array

### ISSUE THREAD

**Issue by Ahmad-RW** [typeorm/typeorm#8569]
## Issue Description
Apologies if this is a duplicate and if my english is not great. 
I'm not sure if it's a bug or intended behavior, but it seems that special columns such as updated at and created at don't show up in `event.updatedColumns` in event subscribers. However if `softDelete` is called, the event subscriber will be called with `event.updatedColumns` as an empty array.
### Expected Behavior
since `softRemove` is an update query. I'm expecting my event subscriber to show my deleted at column in `event.updateColumns`.
It makes more sense to me that we get that information in the event subscriber because otherwise we don't know from the event subscriber that a soft remove had happened.

### Actual Behavior

Given the below snippet, if you execute `user.softRemove` the log in `beforeUpdate` function will give an empty array. 
```typescript
@Entity()
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    age: number;

    @DeleteDateColumn()
    deletedAt : Date

    @UpdateDateColumn()
    updatedAt : Date

}

@EventSubscriber()
export class UserSubscriber implements EntitySubscriberInterface<User> {
  listenTo() {
    return User;
  }

beforeUpdate(event: UpdateEvent<User>): void {
    const { updatedColumns, entity } = event;
    console.log(updatedColumns.map((v)=>v.propertyName)) // []
  }
}

```

### Steps to Reproduce

1. Define an event subscriber's `beforeUpdate` function on an entity
2. call `entity.softRemove`
3. you'll get `event.updateColumns` as an empty array where it should show the deleted at column

```typescript
createConnection().then(async connection => {
    const user = new User();
    user.firstName = "Timber";
    user.lastName = "Saw";
    user.age = 25;
    await connection.manager.save(user);
    console.log("Saved a new user with id: " + user.id);

    
    const userFromDb = await User.findOne(user.id)
    await userFromDb.softRemove()

}).catch(error => console.log(error));
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    windows 10      |
| Node.js version     |14.17.1 | 
| Typescript version  | 4.4.3 | 
| TypeORM version     | 0.2.41 | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes|
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ahmad-RW** [comment]
@Ginden Can you kindly triage this? I'd love to contribute to TypeORM.

**Comment by Ginden** [comment]
@Ahmad-RW AFAIR there is already PR/issue for that.
