### ISSUE TITLE
Memory leak when using getOne in queryBuilder

### ISSUE THREAD

**Issue by thangtv611** [typeorm/typeorm#8570]
## Issue Description
I want to get the latest item with updatedAt sort by DESC. Im use the code like this:
```
this.customerRepository.createQueryBuilder().sort('updatedAt', 'DESC').getOne();
```

### Expected Behavior

No memory leak.

### Actual Behavior

I watch Monitor (on MacOS) and Memory of my application grow so fast. From 300MB to 1.5GB, sometime it grow to ~2GB.

```
// include the output in code tags like these!
```

### Steps to Reproduce

1. Refactor the code using .getOne() in chain and observer the result of memory.

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | MacOS |
| Node.js version     | v12.22.7  | 
| Typescript version  | 4.2.3  | 
| TypeORM version     | 0.2.40  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 -  ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
Can you provide reproduction repository?

**Comment by thangtv611** [comment]
> Can you provide reproduction repository?

Sorry it's private repository

**Comment by Ginden** [comment]
@thangtv611 I'm asking for repository built to display bug, not your production code.

**Comment by Ginden** [comment]
No response, closing.

**Comment by stewartmcgown** [comment]
I have no specific cause ironed out yet, but I've just migrated from the v0.3.0-RC branch to 0.3.4 and I'm seeing constant GC failures and crashes.
