### ISSUE TITLE
MongoDB - save an array of subdocuments

### ISSUE THREAD

**Issue by kryz81** [typeorm/typeorm#8575]
## Issue Description

```
class Photo {
 @Column()
 url: string;

 @Column()
 added: string;
}


@Entity({ name: 'vehicles' })
class Vehicle {
  @ObjectIdColumn({ name: '_id' })
  id: ObjectID;

  @Column()
  name: string;

  @Column(() => Photo)
  photos: Photo[];
}

const vehicle = this.create({name: "...", photos: []});
this.save<Vehicle>(vehicle);
```

### Expected Behavior

```{id: "...", name: "...", photos: []}```

### Actual Behavior

`{id: "...", name: "...", photos: {url: [], added: []}}`

Adding {array: true} to the @Column mapping doesn't help 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | yes            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by RadotJar** [comment]
What was the outcome here @kryz81 ?
