### ISSUE TITLE
GUID in MSSQL

### ISSUE THREAD

**Issue by YSOUZAS** [typeorm/typeorm#858]
Is possible to use GUID in mssql?

something like this

```ts
import {Entity, Column, PrimaryColumn} from "typeorm";

@Entity()
export class Photo {

    @PrimaryColumn("GUID", { generated: true })
    id: number;

    @Column()
    name: string;

    @Column()
    description: string;

    @Column()
    filename: string;

    @Column()
    views: number;

    @Column()
    isPublished: boolean;
}
```

i

**Comment by pleerock** [comment]
Not yet. However there is own uuid generation functionality you can use:

```ts
@Entity()
export class Post {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    @Generated("uuid")
    uuid: string;

}
```

**Comment by iz-iznogood** [comment]
Hi,

@pleerock Can we discuss on what remains to be implemented ? 

I would like to give it a try if I can. I  saw a few issues on the column creation that I can handle and I need to check that the generation logic is ok.

Thanks

**Comment by pleerock** [comment]
I think better if @AlexMesser will implement it since he implemented all other uuid types

**Comment by pleerock** [comment]
However if you have a time and wish to implement something similar there are tons of tasks I can provide 😆

**Comment by AlexMesser** [comment]
UUID in SQLServer now having `uniqueidentifier` data type and uses `NEWSEQUENTIALID()` function to generate id string. Definition is the same as in other drivers, e.g. `@PrimaryGeneratedColumn("uuid")` or `@Generated("uuid")`. We don't use separate `GUID` type, because GUID is only Microsoft's implementation of the UUID standard.

**Comment by pleerock** [comment]
released in `0.1.0-alpha.48`

**Comment by iz-iznogood** [comment]
@AlexMesser  thank you !!!!!

**Comment by iz-iznogood** [comment]
Hi this change broke the schema update since the defaultValue and isGenerated comparisons fail
I will provide a short fix,shortly
