### ISSUE TITLE
postgres table type bigint return string when query.

### ISSUE THREAD

**Issue by Blankll** [typeorm/typeorm#8583]
## Issue Description
in Postgres, when column type is bigint, and entity also defined the type as number in typescript, but still got string.

### Expected Behavior
query result for bigint return as a number instead of a string

### Actual Behavior
a string giving in the result object

### Steps to Reproduce
I created a simple sample to startup pg and express: https://github.com/Blankll/express-ts

I followed the example with express totural:https://typeorm.io/#/example-with-express, and create the user table which contains an bigint type
```sql

CREATE TABLE public.users (
      id serial CONSTRAINT user_id_pk PRIMARY KEY,
      firstName VARCHAR(255),
      lastName VARCHAR(255),
      batchid bigint,
      created timestamp without time zone NOT NULL DEFAULT current_timestamp,
      updated timestamp without time zone NOT NULL DEFAULT current_timestamp
);
```
and entity:
```ts
import {Entity, Column, PrimaryGeneratedColumn} from "typeorm";

@Entity('users', { schema: 'public' })
export class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column('bigint', { name: 'batchid' })
    public batchId?: number;
}
```
but when query the users it return batchId as string instead of number
```ts
// create typeorm connection
createConnection().then(connection => {
  const userRepository = connection.getRepository(User);

  // create and setup express app
  const app = express();
  app.use(express.json());

  // register routes

  app.get("/users", async function(req: Request, res: Response) {
    const users = await userRepository.find();
    res.json(users);
  });

  console.log('service start at 3000')
  // start express server
  app.listen(3000);
});
```
response:
```bash
curl http://localhost:3000/users

[{"id":1,"firstName":"aan","lastName":"row","batchId":"1643356158342"}]%
```
with simplest ts express typeorm sample:

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |        macos11.6.1  |
| Node.js version     | v16.13.2  | 
| Typescript version  | typescript@4.5.5  | 
| TypeORM version     | typeorm@0.2.41 | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
This is working as expected.

JavaScript numbers can't represent accurately integers larger than [`9007199254740991`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) (2^53).

Eg.
```js
(Number.MAX_SAFE_INTEGER + 2) === (Number.MAX_SAFE_INTEGER + 1)
```

Therefore, `pg` stringifies them as strings.

To override this behaviour you can [define custom type parser in `pg` package](https://github.com/brianc/node-pg-types) or specify custom transformer.

It would be reasonable to expose such option in connection options though.

**Comment by tsapko3628** [comment]
Why don't TypeORM use js biting for this?
