### ISSUE TITLE
Upsert expects unique constraint for `OneToOne` columns which imply uniqueness already

### ISSUE THREAD

**Issue by futpib** [typeorm/typeorm#8587]
I get this error:
```
An upsert requires conditions that have a unique constraint but none was found for conflict properties: original_response_id
```
For code like this:
```typescript
import TypeORM from 'typeorm';
import { Response } from './response';

@TypeORM.Entity()
export class Archive {
	@TypeORM.PrimaryGeneratedColumn('uuid')
		id!: string;

	@TypeORM.OneToOne(() => Response, response => response.id)
	@TypeORM.JoinColumn()
		originalResponse!: Response;
}
```

```typescript
		await this._archiveRepository.upsert(archive, [ 'original_response_id' ]);
```

I also tried changing `'original_response_id'` to `'original_response'` or `'originalResponse'` and it did not help.

This is the line where error is thrown:
https://github.com/typeorm/typeorm/blob/26581d0264268045496b43f7a0f338eb9f2b70cc/src/entity-manager/EntityManager.ts#L509-L511

**Comment by mostafa-hz** [comment]
I also have the same problem, here's my entity:

```ts
@Entity()
@Unique(['code', 'shop'])
export class ProductEntity {
  @Column({ type: String })
  code!: string;

  @ManyToOne(() => ShopEntity, { nullable: false, onDelete: 'CASCADE', onUpdate: 'CASCADE' })
  @JoinColumn()
  shop?: ShopEntity;
}
```

and when I try to upsert data:
```ts
await em.upsert(ProductEntity, chunk, { conflictPaths: ['code', 'shop'] });
```

I get the same error:
> error:  TypeORMError: An upsert requires conditions that have a unique constraint but none was found for conflict properties: shop, code

**Comment by mostafa-hz** [comment]
### Solution
If I change `shop` to `shop.id` it will work!

https://github.com/typeorm/typeorm/blob/26581d0264268045496b43f7a0f338eb9f2b70cc/src/entity-manager/EntityManager.ts#L506

in the code above it checks for `col.propertyPath` which in my case was `shop.id`.

I'm not sure if it is expected behavior.
@joeflateau shouldn't `col.propertyPath` replaced with `col.propertyName` or `col.propertyAliasName`?

**Comment by mostafa-hz** [comment]
> @futpib Does `@OneToMany` actually create the unique constraint? if not, then it can't be used as a conflict path.

@joeflateau it does, actually, it is a regular relation with a unique constraint but I'm not sure if it is being reflected in `uniqueColumnConstraints`

**Comment by joeflateau** [comment]
@mostafa-hz okay cool, thank you

**Comment by joeflateau** [comment]
@futpib I've found the metadata for the one-to-many's unique indices. I have a fix in testing now

**Comment by ravindra887** [comment]
> ### Solution
> If I change `shop` to `shop.id` it will work!
> 
> https://github.com/typeorm/typeorm/blob/26581d0264268045496b43f7a0f338eb9f2b70cc/src/entity-manager/EntityManager.ts#L506
> 
> in the code above it checks for `col.propertyPath` which in my case was `shop.id`.
> 
> I'm not sure if it is expected behavior. @joeflateau shouldn't `col.propertyPath` replaced with `col.propertyName` or `col.propertyAliasName`?

worked thanks
