### ISSUE TITLE
Throw error when entity is not found

### ISSUE THREAD

**Issue by AxeemHaider** [typeorm/typeorm#8588]
Right now if entity not found it return `undefined` but I want typeorm through error when entity not found how can I config it.
Not finding anything in docs

### What was unclear or otherwise insufficient?
How to config to throw error when entity not found.

**Comment by dylanlee082** [comment]
This already exists in the documentation right? 
Copy/Paste from Docs 
Below, # Getting values using QueryBuilder

getOneOrFail will get a single result from the database, but if no result exists it will throw an EntityNotFoundError:

```
const timber = await getRepository(User)
    .createQueryBuilder("user")
    .where("user.id = :id OR user.name = :name", { id: 1, name: "Timber" })
    .getOneOrFail();
```

**Comment by Ginden** [comment]
I must have missed that one, closing.
