### ISSUE TITLE
typeorm 0.2.40 broke findOne with operator

### ISSUE THREAD

**Issue by brandon-leapyear** [typeorm/typeorm#8600]
## Issue Description

The following typechecks on typeorm 0.2.38, but breaks on typeorm 0.2.41. I suspect it's due to #5710, which was released in 0.2.40.
```ts
repository.findOne({
  where: {
    foreignKey: 1,
    enum: In([MyEnum.A]),
  },
})
```
The error message in 0.2.41 complains about `foreignKey`: `Type 'number' is not assignable to type 'FindCondition<ForeignKeyEntity> | undefined'.`. Removing the `In(...)` operator makes it work again, so the `foreignKey` error is a bit of a red herring.

### Expected Behavior

It should typecheck

### Actual Behavior

It fails

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   MacOS 10.15       |
| Node.js version     | 16.11.1 |
| Typescript version  | 4.3.3 |
| TypeORM version     | 0.2.41 |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by brandon-leapyear** [comment]
Update: can verify that the `T | ...` part is what's causing the breakage. Removing it from my local copy of typeorm causes it to typecheck again.

Indeed, reverting `FindConditions.ts` back to before #5710 and adding `T |` to `FindConditions` causes it to break again.

**Comment by Ginden** [comment]
Version `0.2` isn't supported anymore.
