### ISSUE TITLE
normalizeType function issue

### ISSUE THREAD

**Issue by iz-iznogood** [typeorm/typeorm#861]
Hi,

I checked on how typeorm decides on the proper datatype for common javascript types
For example if column.type == String then it translates to nvarchar (mssql) or character varying (postgres) etc
This is good when we work with entities for metadata. But creates an issue regarding entity schemas. If we use json for that then the comparison fails since column.type == "string" is false etc.
I see that for some drivers (and for Number datatype) you have expander the check to include this case
e.g. sqlite 
`        if (column.type === Number || column.type === "int") {
            return "integer";
`
mysql
`        if (column.type === Number || column.type === "integer") {
            return "int";
`

I propose that there should be some string aliases for the common types to allow the json case to work
For example "string", "integer", "boolean", "date" with case insensitive comparison.
I believe it is mandatory to have real cross database support, unless I miss something

If you agree I can send some patches and tests for this change.

Thanks

**Comment by pleerock** [comment]
Actually `column.type === Number` is needed because `Number` here is reflection of property type, e.g.:

```ts
@Column()
sum: number;
```

This `number` is translated into JavaScript `Number` type which then we translate into concrete types. 

So, what Im thinking is that json does not need those abstract types, and users can set exact type they really need, like varchar, int, text, etc.

**Comment by iz-iznogood** [comment]
Hi,

I understand your POV but I beg to differ. What I propose is a simple enhancement of what already exist. 
All normalizeType methods have an else clause so that anyone can pass whatever specific type he wants. So this case is covered in all scenarios (decorators, js objects, json files). But in the later case we miss the generic functionality that is present in all other cases.
For instance I wanted to declare a boolean datatype. In the ts classes case I had just to add the field and the ORM converted it to bit column for mssql, etc This did not work for the json objects, I had to set it to bit manually, thus killing the abstraction. 
Also most users will want to use the same schema for different connections (imagine also the replication case) so common type aliases for at least string, boolean, integer and date are (IMHO) mandatory.
I could also add float, double, datetime etc but lets stay for the common js datatypes.

So in code instead of 
`       
 } else if (column.type === String) {
return "nvarchar";
` 
I propose

`
        } else if (column.type === String || (typeof(column.type) === "string" && column.type.toLowerCase() === "string") {
            return "nvarchar";
`
same for other types. This does not break anything and is symmetrical to all cases

What do you say ?

**Comment by pleerock** [comment]
Its discussion about ORM design. Yeah we can support both generic and specific column types, but I was thinking only to support specific column types. But this thinking can be changed.

But I would like to warn you that TypeORM goal is not to make a perfect abstraction over databases. If we think we can add some awesome specific database feature we do it and avoid "perfect abstraction"

**Comment by iz-iznogood** [comment]
Yes I understand, but what I propose is not to change the behavior, just to make it even in all cases.

So even if you have a super feature that needs specific datatypes, how are you going to handle it since in the decorators case (which is the most common) you have the option to use common types ? (which is also the common case, I hardly believe that most developers override the e.g. string JavaScript type, they just let the Orm decide it for them). 
In this case either you make a breaking change in the design by making type property in decorator mandatory (and not e.g. string, something DB specific like nvarchar) or you add checks in your code to forbid common types for that feature or you just don't implement the feature at all.

I hope you see my POV and if you agree I can give this a try. 
I can live without this but I believe it would be nice to have it

**Comment by pleerock** [comment]
Im not 100% sure about this change, but I think you can create a PR for this feature.

**Comment by iz-iznogood** [comment]
Won't implement since there is no agreement on how do this

**Comment by br0wn** [comment]
> but I was thinking only to support specific column types

@pleerock Could you elaborate why is that? Isn't it more convenient for developers to have common interface (types) with clearly defined and documented way how it maps to specific database types (like [doctrine has](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#mapping-matrix)), but to be able to define specific type manually if needed ?

I ran into trouble where I want to have different database types for different environments (of same code), but I have a table that has a blob field (or JSON for that matter).. I'm forced to either chose one database type, or to make my own type converter that will return correct type based on database type provided.

**Comment by pleerock** [comment]
Early versions of typeorm had common types just like doctrine currently has. Then we got dozen of issues that we do not support native type x, y, z, etc. (just like doctrine does). Then we decided then its better to support all database-specific types rather then limited set of types. More flexibility and features over almost always useless cross-database supporting. Make all types supported by all databases common is a big pain and nearly impossible.

**Comment by br0wn** [comment]
> Then we got dozen of issues that we do not support native type x, y, z, etc. (just like doctrine does)

Doctrine provides a way to [specify a custom type](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/custom-mapping-types.html) mapping so when needed one can add custom map to support native type. Would you be open to implement something like this in the future?

**Comment by pleerock** [comment]
You probably did not get my message, we do not do like doctrine because we want to avoid doing [this](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/custom-mapping-types.html) and instead we support all database custom types out of the box which makes it complex to have a "generic types" are you requesting.

**Comment by iz-iznogood** [comment]
Hi all,

IMHO this can be implemented as an optional mapping. It would be extremely useful in any cases and not block anything.
For example I have implemented a breeze.js - typeorm adapter and I can only use this for SQL Server otherwise I would need to create and maintain custom mappings for all supported databases.

Thanks,
CK

**Comment by pleerock** [comment]
We have to understand that we **cannot** map each type, we shall separate real and "generic" types clean and understandable way to prevent user confusion. It means we should create a good design proposal.
