### ISSUE TITLE
Cannot access the website

### ISSUE THREAD

**Issue by niraj-khatiwada** [typeorm/typeorm#8611]
I'm not able to access the website since few hours. Below is an screenshot showing errors from console.
![image](https://user-images.githubusercontent.com/51436631/152758748-a64d21e8-4db5-45e5-a574-71e40c5875f2.png)

**Comment by Enfield1234** [comment]
Same, but you can use this one: https://typeorm.biunav.com/en/

**Comment by niraj-khatiwada** [comment]
> Same, but you can use this one: https://typeorm.biunav.com/en/

Thanks for this. Appreciate it.

**Comment by Ginden** [comment]
Yes, it is down.

 #8610
