### ISSUE TITLE
Upsert conflictPath option doesn't recognize relation fields properly 

### ISSUE THREAD

**Issue by mostafa-hz** [typeorm/typeorm#8617]
> I also have the same problem, here's my entity:
> 
> ```ts
> @Entity()
> @Unique(['code', 'shop'])
> export class ProductEntity {
>   @Column({ type: String })
>   code!: string;
> 
>   @ManyToOne(() => ShopEntity, { nullable: false, onDelete: 'CASCADE', onUpdate: 'CASCADE' })
>   @JoinColumn()
>   shop?: ShopEntity;
> }
> ```
> 
> and when I try to upsert data:
> 
> ```ts
> await em.upsert(ProductEntity, chunk, { conflictPaths: ['code', 'shop'] });
> ```
> 
> I get the same error:
> 
> > error:  TypeORMError: An upsert requires conditions that have a unique constraint but none was found for conflict properties: shop, code

@mostafa-hz this is a separate issue, please create a second issue for your problem here

_Originally posted by @joeflateau in https://github.com/typeorm/typeorm/issues/8587#issuecomment-1033923943_

**Comment by mostafa-hz** [comment]
since #8618 is merged, this issue is not valid anymore

**Comment by Robert-Rendell-THE** [comment]
For anyone that wants typing, I did this:

const conflictPaths: (keyof MyEntity)[] = ['columnA', 'columnB']
const opts: UpsertOptions<MyEntity> = { conflictPaths };
myEntityRepo.upsert({ ... }, opts)

**Comment by vfa-thangld** [comment]
It still does not work for me
Entity
`
@Entity('histories')
export class HistoriesEntity {
  @Column({ name: 'data' })
  data: string;

  @ManyToOne(() => UsersEntity, {
    onDelete: 'RESTRICT',
    onUpdate: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'userId', referencedColumnName: 'id' })
  user: UsersEntity;
}
`
Then I try to upsert data
`
await this.historiesRepo.upsert({ data, user: { id: userId } }, { conflictPaths: ['user.id'] });
`
I trying to replace `user.id` to `userId` then get the error `Property "userId" was not found`

**Comment by joeflateau** [comment]
@vfa-thangld JoinColumn doesn't help here. you need to declare the actual userId column. something like this below.

```
@Column({ unique: true, nullable: false })
userId!: string;
```
