### ISSUE TITLE
Serious issue on index creation for relation joined column (referencedColumn - propertyPath)

### ISSUE THREAD

**Issue by iz-iznogood** [typeorm/typeorm#863]
Hi I have a serious issue regarding indices and relations and I would appreciate some assistance.

I have a normal one to many relation between 2 entities. 
Table B contains column AId that references table A.Id (primary key)
This is normal, but then I created an index on column AId.

The RelationJoinColumnBuilder created the relation and set the referencedColumn of AId to be A.Id
Then this referencedColumn participates on the propertyPath building (ColumnMetadata.buildPropertyPath) which concatenates the property names for the column and it's referencedColumn (this seems a bit weird). This results in a path Id.AId which is wrong.

Since the IndexMetadata tries to build the index by finding the columns on the table based on the propertyPath, this fails.

I am not sure how referencedColumn and propertyPath are used in the ORM. I believe that the error is on ColumnMetadata.buildPropertyPath, referenced column should not participate in the path. 
But again I am not sure.

I would need some assistance on that, it is rather serious and it is a blocker for me.

Thank you

**Comment by pleerock** [comment]
Can you please provide a short code example?

**Comment by iz-iznogood** [comment]
Sure, I send you my example directly.

`
import {
    Entity, Column,
    PrimaryColumn, PrimaryGeneratedColumn,
    ManyToOne, OneToMany, JoinColumn
} from "../typeorm-master/src/index";

import DomainTypeGroup from "./domainTypeGroup";
import DomainTypeEnumValue from "./domainTypeEnumValue";

@Entity("DomainTypes")
class DomainType {

    @PrimaryColumn({
        length: 36
    })
    Id: string;

    @Column({
        length: 50,
        unique: true,
        nullable: false
    })
    UniqueId: string;

    @Column({
        length: 20,
        nullable: false,
        default: "Business"
    })
    Flag: string;

    @Column({
        nullable: false,
        length: 30,
        unique: true
    })
    Code: string;

    @Column({
        nullable: false,
        length: 150
    })
    LocalizedDescriptionKey: string;

    @Column({
        nullable: false,
        length: 20,
        default: "DataValue"
    })
    Category: string;

    @Column({
        nullable: false,
        length: 20
    })
    DataType: string;

    @Column({
        nullable: false,
        type: "int",
        default: 0
    })
    Size: number;

    @Column({
        nullable: false,
        length: 36
    })
    DomainTypeGroupId: string;

    @ManyToOne(type => DomainTypeGroup, domainTypeGroup => domainTypeGroup.DomainTypes, {
        nullable: false
    })
    @JoinColumn({
        name: "DomainTypeGroupId"
    })
    DomainTypeGroup: DomainTypeGroup;

    @OneToMany(type => DomainTypeEnumValue, domainTypeEnumValue => domainTypeEnumValue.DomainType)
    DomainTypeEnumValues: DomainTypeEnumValue[];

}

export default DomainType;


import {
    Entity, Column,
    PrimaryColumn, PrimaryGeneratedColumn,
    OneToMany
} from "../typeorm-master/src/index";

import DomainType from "./domainType";

@Entity("DomainTypeGroups")
class DomainTypeGroup {

    @PrimaryColumn({
        length: 36
    })
    Id: string;

    @Column({
        length: 50,
        unique: true,
        nullable: false
    })
    UniqueId: string;

    @Column({
        length: 20,
        nullable: false,
        default: "Business"
    })
    Flag: string;

    @Column({
        nullable: false,
        length: 30,
        unique: true
    })
    Code: string;

    @Column({
        nullable: false,
        length: 150
    })
    Description: string;

    @OneToMany(type => DomainType, domainType => domainType.DomainTypeGroup)
    DomainTypes: DomainType[];

}

export default DomainTypeGroup;

import {
    Entity, Column,
    PrimaryColumn, PrimaryGeneratedColumn,
    ManyToOne, JoinColumn, Index
} from "../typeorm-master/src/index";

import DomainType from "./domainType";

@Entity("DomainTypeEnumValues")
@Index("IDX_UNQ_DomainTypeId_Value", type => [type.DomainTypeId/* , type.Value*/], { unique: true })
class DomainTypeEnumValue /* extends SchemaEntity */ {

    @PrimaryColumn({
        length: 36
    })
    Id: string;

    @Column({
        length: 50,
        unique: true,
        nullable: false
    })
    UniqueId: string;

    @Column({
        length: 20,
        nullable: false,
        default: "Business"
    })
    Flag: string;

    @Column({
        nullable: false,
        length: 36
    })
    DomainTypeId: string;

    @Column({
        nullable: false,
        length: 30
    })
    Value: string;

    @Column({
        nullable: false,
        length: 150
    })
    LocalizedDescriptionKey: string;

    @Column({
        type: "int",
        nullable: false,
        default: 1
    })
    OrderNo: number;

    @ManyToOne(type => DomainType, domainType => domainType.DomainTypeEnumValues, {
        nullable: false,
        onDelete: "CASCADE"
    })
    @JoinColumn({
        name: "DomainTypeId"
    })
    DomainType: DomainType;

}

export default DomainTypeEnumValue;

import "reflect-metadata";
import {createConnection, getEntityManager, getConnection} from "./typeorm-master/src/index";

import { MetadataManager } from "./metadataManager";

import DomainTypeGroup from "./entities/domainTypeGroup";
import DomainType from "./entities/domainType";
import DomainTypeEnumValue from "./entities/domainTypeEnumValue";

createConnection({
    type: "mssql",
    port:  1433,
    username: "test",
    password: "test",
    database: "test",
    entities: [
        DomainTypeGroup,
        DomainType,
        DomainTypeEnumValue
    ],
    autoSchemaSync: true,
    logging: ["query"]
}).then(async (connection) => {

    console.log("DONE");

}).catch(error => {

    console.log(error);

});
`

As you can see the main function is nothing special.
I hope I didn't do  something stupid in the entity definition 

Thank you

**Comment by pleerock** [comment]
Can you please provide small example next time with only properties that really affect the issue 🙏  I didn't completely understood the issue here. As I understood this does not work for you:

```ts
@Index("IDX_UNQ_DomainTypeId_Value", type => [type.DomainTypeId/* , type.Value*/], { unique: true })
class DomainTypeEnumValue /* extends SchemaEntity */ {

    @PrimaryColumn({
        length: 36
    })
    Id: string;

    @Column({
        nullable: false,
        length: 36
    })
    DomainTypeId: string;

    @ManyToOne(type => DomainType, domainType => domainType.DomainTypeEnumValues, {
        nullable: false,
        onDelete: "CASCADE"
    })
    @JoinColumn({
        name: "DomainTypeId"
    })
    DomainType: DomainType;

}
```

right? If yes then I'll try to reproduce this issue in a test and see what is going on

**Comment by iz-iznogood** [comment]
Sorry for that.
Would you prefer that I send you the test ?

**Comment by pleerock** [comment]
Yes it would be great, minimal reproduction as possible

**Comment by iz-iznogood** [comment]
Hi, I added a simple test that reproduces it.
I am trying it on MSSQL but I believe it is the same in all DB's.

Please take a look

Thanks

**Comment by pleerock** [comment]
It was a bug and fixed it, thx for report and test

**Comment by iz-iznogood** [comment]
Thank you !!!!
Would it be possible to explain why we need the property path set for virtual columns ?
Since I am touching code, it would be useful to understand this case.
For embedded entities it is clear, we need the path. But for virtual it is not.
Maybe a small example ....

**Comment by pleerock** [comment]
its a bit hard to explain but I'll try.

We need to build column property path because of two reasons:
* embeddeds, for example "post.counters.likes"
* referenced in relations columns, for example "post.category.id"

When we create a relation it defines a new column (lets say categoryId) and marks it as virtual.
Virtual means this column exist in the database but does not exist in entity defined by user.
This column has propertyPath equal to "category.id".

But when we create a relation and a column called exactly the same as relation suppose to create a column (we create a categoryId column inside our entity) orm does not create any extra column, thus does not mark anything as virtual. And such column propertyPath is just like any other column's property paths are - its equal to simply "categoryId".

Its really hard to explain, I wish to show you this process in a debug mode...
