### ISSUE TITLE
Coloumns are not creating in MYSQL Database

### ISSUE THREAD

**Issue by imhari213** [typeorm/typeorm#864]
`My` code is running successfully but  **all columns** in **entity** file are not creating in mysql table i dont know why? but remaining table columns are creating successfully.

```ts
@Entity("product_skus")
export class ProductSku{
    @PrimaryGeneratedColumn({name:"id"})
    id:number;

    @JoinColumn({name:"products_id"})
    @ManyToOne(type=>Product)
    products_id:Product;


    @Column({name:"active"})
    active:boolean;

    @Column({
        name:"name",
        length:128
    })
    name:string;

    @JoinColumn({name:"user_billings"})
    @ManyToOne(type=>UserBilling)
    user_billings:UserBilling;

}
```

**From above entity only user_billings field is creating in db and no any other column is creating**

**Comment by pleerock** [comment]
what do you call `remaining table columns` ? Do you have `synchronize` option set to true in your connection options? did you try to run `typeorm schema:sync` command?

**Comment by imhari213** [comment]
yes solved.Thank you
