### ISSUE TITLE
Multicolumn index problem when upgrading from 0.0.11 to 0.1.0 alpha releases

### ISSUE THREAD

**Issue by OysteinAmundsen** [typeorm/typeorm#865]
I maintain a medium size system running on typeorm 0.0.11. Each time I try to upgrade from 0.0.11 to a new alpha release, I get this error, and my database is destroyed afterwards:

```
columns dropped in gymnast: club
executing query:  ALTER TABLE `gymnast` DROP `club`
query failed:  ALTER TABLE `gymnast` DROP `club`
error:  { Error: ER_DUP_ENTRY: Duplicate entry 'Boy 1' for key 'gymnast_club_name'
    at Query.Sequence._packetToError (.\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (.\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (.\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (.\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (.\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (.\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    --------------------
    at Protocol._enqueue (.\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at PoolConnection.query (.\node_modules\mysql\lib\Connection.js:208:25)
    at MysqlQueryRunner.<anonymous> (.\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:198:44)
    at step (.\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:32:23)
    at Object.next (.\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:13:53)
    at fulfilled (.\node_modules\typeorm\driver\mysql\MysqlQueryRunner.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlMessage: 'Duplicate entry \'Boy 1\' for key \'gymnast_club_name\'',
  sqlState: '23000',
  index: 0,
  sql: 'ALTER TABLE `gymnast` DROP `club`' }
executing query:  ROLLBACK
```

This is the entity in question:

    @Entity()
    @Index('gymnast_club_name', (gymnast: Gymnast) => [gymnast.name, gymnast.club], { unique: true })
    export class Gymnast {
      @PrimaryGeneratedColumn()
      id: number;

      @Column({ length: 100 })
      name: string;

      @ManyToOne(type => Club, club => club.gymnasts, { nullable: false })
      club: Club;
    }

There's no recover, I need to drop my database and rebuild from scratch.

From what I can read, it removes the reference to `club` in the `ManyToOne` relation (probably to rebuild using some magic), but this leaves the Index broken as there are possibly many `name`s which are perceived as duplicates without the `club` property.

**Comment by pleerock** [comment]
There are tons of changes between `0.1.0` and `0.0.11` so now its really hard to say what caused this issue. One of the biggest change in schema naming is how many to many tables are named and how join columns are named. Before join column named as `club` but now its called as `club + referenced column name`, for example `clubId`. I can only suggest you to manually fix all those issues - generate a new database schema with new version, and make corresponding changes in old schema. Start from removing all indices from your old schema

**Comment by OysteinAmundsen** [comment]
Thanks for replying. So you are basically saying that migration from 0.0.11 to 0.1.0 is impossible, unless I compare old and new database, and create some kind of sql script with differences to run before I start my server?

**Comment by pleerock** [comment]
Differences between 0.0.11 and 0.1.0 are huge and yes, in most of cases you'll need to manually correct your database if you already have data in there.

**Comment by apiel** [comment]
What do you mean by manually correct the database? I also updated from 0.0.8 to 0.1.0-alpha.41
and now I get error on all my foreign keys:
error occurred: { QueryFailedError: column u.idProgramIdProgram does not exist

actually u.idProgramIdProgram should be u.idProgram

So why there is this prefix idProgram. You suggest to update our database, but in which way?
Is not a way to instead update our mapping? it would make much more sense, I dont really want to change my data structure.

**Comment by pleerock** [comment]
> You suggest to update our database, but in which way?

for example rename your column from `idProgram ` to `idProgramIdProgram`, or you can set `@JoinColumn({ name: "idProgram" })` if you want to use old name.

> So why there is this prefix idProgram

There is a prefix because now join column name is built from "propertyName + referenced column name", for example:

```ts
export class Category {
@PrimaryGeneratedColumn()
id: number;
```

```ts
export class Post {
@ManyToOne(type => Category)
category: Category;
```

before (in 0.0.x) was creating a `category: int` column inside post table.
Now (in 0.1.0) it creates `categoryId: int` column inside post table.
Why? Because now orm supports relation with multiple primary keys, for example:

```ts
export class Category {
@PrimaryColumn()
id: number;
@PrimaryColumn()
name: number;
```

```ts
export class Post {
@ManyToOne(type => Category)
category: Category;
```

In this example relation will create two columns inside `Post` table: `categoryId` and `categoryName` which reference to `Category` and both its primary columns. 

There are technical reasons behind all those changes.

**Comment by apiel** [comment]
ok, thank you, I will give a try and again congratulation for this awesome library.

**Comment by OysteinAmundsen** [comment]
It's a bit difficult for me to run a script before I start my server.
The entire system is built around docker, and the only way to reach my database docker container is through the application server docker container, which is again hidden behind an nginx docker container.
All of which is deployed via travis to docker-cloud on git push. Completely automatic in other words. I find it hard to sneak in a script somewhere...

It's great that I can name my `JoinTable`s, but it would be equally great if I could name my other relations as well. That way I could prevent the upgrade from dropping my `club` column and replacing it with a `clubId`. I think that's all that's required for me to upgrade smoothly.

**Comment by pleerock** [comment]
I don't understand how your infrastructure is related to your problem. Simply import your db to your local, apply changes there and import changed db again into the production if its so complicated on your production.

> It's great that I can name my JoinTable

yes you can do that by `@JoinTable({ name: "..." })`

**Comment by OysteinAmundsen** [comment]
No you misunderstand. The ManyToMany relation issue will solve itself by using `@JoinTable({name: 'oldDbName'})`. 
The other problem is the columns derived from `@ManyToOne` and `@OneToOne`.

For those parts where a `@JoinColumn` can be applied, the problem solves itself, as I can set a name for the column as input to the `@JoinColumn` decorator. But for those parts where this is not applicable, they will be renamed from `propertyName` to `propertyName + 'Id'`. 

I would like to set a column name for these as well.

**Comment by OysteinAmundsen** [comment]
Nevermind. :-) `@JoinColumn` can be put all places where I have a `@ManyToOne` relation, and `@OneToOne` requires `@JoinColumn` on one of the sides. So problem solved. Thank you for pointing me in the right direction.

**Comment by apiel** [comment]
column name + referenced column only happen on joined column not the other column of the entities. Yesterday I managed to migrate from 0.0.8 to 0.1.0 alpha by using @JoinTable({ name: "..." }), even if it took me hours... good luck ;-)
