### ISSUE TITLE
Error: ERR_UNSUPPORTED_ESM_URL_SCHEME for new release on run

### ISSUE THREAD

**Issue by CantisW** [typeorm/typeorm#8651]
## Issue Description

Using the new Typeorm release does not work as expected as it keeps giving a `ERR_UNSUPPORTED_ESM_URL_SCHEME` error.

### Expected Behavior

TypeOrm should run as intended.

### Actual Behavior

TypeOrm tries to connect to the ormconfig database, then before it can get any further, errors.

The project was created using `npx typeorm init --name MyProject --database postgres --module esm`

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:371:5)
    at defaultResolve (node:internal/modules/esm/resolve:1032:11)
    at C:\Users\user\Desktop\random-coding-projects\ProjectFiles\JS\discord-economy-bot-typescript\MyProject\node_modules\ts-node\src\esm.ts:129:23
    at Generator.next (<anonymous>)
    at C:\Users\user\Desktop\random-coding-projects\ProjectFiles\JS\discord-economy-bot-typescript\MyProject\node_modules\ts-node\dist\esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\user\Desktop\random-coding-projects\ProjectFiles\JS\discord-economy-bot-typescript\MyProject\node_modules\ts-node\dist\esm.js:4:12)
    at defer (C:\user\user\Desktop\random-coding-projects\ProjectFiles\JS\discord-economy-bot-typescript\MyProject\node_modules\ts-node\src\esm.ts:128:30)
    at C:\Users\user\Desktop\random-coding-projects\ProjectFiles\JS\discord-economy-bot-typescript\MyProject\node_modules\ts-node\src\esm.ts:137:14
    at Generator.next (<anonymous>) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

### Steps to Reproduce

1. Run `npx typeorm init --name MyProject --database postgres --module esm`
2. Setup ormconfig.json as normal
3. Run the project (`node start`)

### My Environment

| Dependency          | ts-node, TypeScript, Typeorm, pg,  reflect-metadata  |
| ---                 | ---      |
| Operating System    | Windows 10         |
| Node.js version     | v17.3.0  | 
| Typescript version  | 4.5.5  | 
| TypeORM version     | 0.2.42  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by giladgd** [comment]
@CantisW @pleerock I've tried reproducing it on both macOS and Windows 11 but this issue didn't occur to me.
Running `npx typeorm init --name MyProject --database postgres --module esm` produces a valid project, running `npm start` in the newly generated folder works properly.

**Comment by CantisW** [comment]
Super strange. The issue makes Typeorm completely unusable on ESM projects, but it still works fine on non-ESM projects.

Turning on logging gives
```query: SELECT * FROM current_schema()```
showing that it's doing something.

If this is only an issue affecting me, do you guys potentially have any suggestions on what to do to work around this issue?

**Comment by giladgd** [comment]
@pleerock @CantisW After some more rigorous testing on Windows I found the problem that you're experiencing, though not through the generated project.
It appears to be specific to ESM projects running on Windows, and it doesn't happen with every configuration which made it harder for me to replicate.
I've opened #8669 to fix this issue.
