### ISSUE TITLE
Version 0.2.42 crashes everything

### ISSUE THREAD

**Issue by tada5hi** [typeorm/typeorm#8655]
No driver is found anymore, and 0.2.42 is now force installed by npm, because it fixes security issues....

**Comment by tada5hi** [comment]
got it force reverted to 0.2.41.

**Comment by memlucky71** [comment]
@tada5hi Needs adding extra tests?

**Comment by pleerock** [comment]
Detailed description could really help...

**Comment by tada5hi** [comment]
@memlucky71 @pleerock I think 0.2.43 should address and fix the issue. Sorry, for the poor description yesterday and the missing response, but i was working yesterday for the University (Development of a Federated Learning Architecture in Germany) and was pretty busy there yesterday and i was simultaneously
 updating dependencies for a software component, which is part of the global architecture ^^. It still was just the local development environment, but it made a bit resetless.
