### ISSUE TITLE
How to resolve 'No repository found for @entityname' while using typeorm for Ionic 5. I am using SQLite for database with plugin- cordova-sqlite-storage 

### ISSUE THREAD

**Issue by usersimran** [typeorm/typeorm#8662]
Code setup to create connection
<img width="562" alt="Screenshot 2022-02-18 at 10 45 10 AM" src="https://user-images.githubusercontent.com/7920301/154622021-695554bd-a1a3-4579-b13e-669a832bad9e.png">

Save Data
<img width="870" alt="Screenshot 2022-02-18 at 10 48 11 AM" src="https://user-images.githubusercontent.com/7920301/154622251-f03726d3-6abc-4f41-a9c3-1c009966ab0e.png">

**Comment by AlexMesser** [comment]
For questions / general support, please check out our [Slack channel](https://join.slack.com/t/typeorm/shared_invite/zt-uu12ljeb-OH_0086I379fUDApYJHNuw), [StackOverflow](https://stackoverflow.com/questions/tagged/typeorm) or check [TypeORM's documentation](https://typeorm.io).
