### ISSUE TITLE
result of `findAndCount` is wrong when apply `skip` and `take` option

### ISSUE THREAD

**Issue by YuhangGe** [typeorm/typeorm#867]
bellow test case failed

````js
        const userRepository = connection.getRepository(User);
        const users = new Array(5).fill(0).map((n, i) => {
            const user = new User();
            user.username = `User_${i}`;
            return user;
        });
        await userRepository.save(users);
        const [ foundUsers, totalCount ] = await userRepository.findAndCount({
            skip: 1,
            take: 2
        });
        expect(foundUsers).to.have.lengthOf(2); 
````

the output is:

`AssertionError: expected [ Array(5) ] to have a length of 2 but got 5`

**Comment by pleerock** [comment]
`count` does not return number of selected users - it has different purpose. If you want to get number of selected users just use `foundUsers.length`. Count returns you number of all users you have queries (including where and other conditions) and IGNORES skip/take you set. This allows you to create a proper pagination/infinite scroll/etc knowing where is your limit of users.

**Comment by YuhangGe** [comment]
@pleerock yeah, I know. 

I found this problem just when I want to use findAndCount to make pagination search. I just call findAndCount without any `where` conditions. But it ignore my `skip` and `take` parameters, and the generated SQL has no `LIMIT`.

I checked the source code and guess it's a logic bug, so I have submit a pr #868 , please see if it's really a logic bug.

**Comment by pleerock** [comment]
@YuhangGe please read my comment once again. Count MUST ignore `skip` and `take` params, its by design. Your test MUST look this way:

```ts
 const userRepository = connection.getRepository(User);
        const users = new Array(5).fill(0).map((n, i) => {
            const user = new User();
            user.username = `User_${i}`;
            return user;
        });
        await userRepository.save(users);
        const [ foundUsers, totalCount ] = await userRepository.findAndCount({
            skip: 1,
            take: 2
        });
        expect(foundUsers).to.have.lengthOf(5);  // CORRECT is 5, NOT 2. If you want to get "2" use foundUsers.length instead
```

**Comment by pleerock** [comment]
Hmm you made same in your test. Probably I misunderstood you, let me see your PR in details

**Comment by YuhangGe** [comment]
@pleerock okey. so what about bellow case:

````js
const userRepository = connection.getRepository(User);
        const users = new Array(5).fill(0).map((n, i) => {
            const user = new User();
            user.username = `User_${i}`;
            return user;
        });
        await userRepository.save(users);
        const foundUsers = await userRepository.find({
            skip: 1,
            take: 2
        });
        expect(foundUsers.length).to.equal(2)
````

the output is: `AssertionError: expected 5 to equal 2`

**Comment by YuhangGe** [comment]
@pleerock actually both `find` and `findAndCount` have same problem

**Comment by pleerock** [comment]
Sorry, stupid me. Looks like I misunderstood your issue - i thought you have issue with count and not  users count. Let me merge your PR and take a look on issue more closely
