### ISSUE TITLE
TypeORM and Parcel 2

### ISSUE THREAD

**Issue by andrewvmail** [typeorm/typeorm#8689]
## Issue Description

Latest version of TypeORM does not play well with Parcel 2

### Expected Behavior

Can build using Parcel 2

### Actual Behavior

```
Uncaught TypeError: Cannot destructure property 'ConnectionOptionsReader' of '_indexJsDefault.default' as it is undefined.
    at Object.dmLkU../index.js (index.2d3ace14.js:47854:9)
    at newRequire (index.2d3ace14.js:71:24)
    at localRequire (index.2d3ace14.js:84:35)
    at Object.ign3V.@swc/helpers (index.2d3ace14.js:45833:16)
    at newRequire (index.2d3ace14.js:71:24)
    at localRequire (index.2d3ace14.js:84:35)
    at Object.4aBH6.typeorm/browser (index.2d3ace14.js:524:17)
    at newRequire (index.2d3ace14.js:71:24)
    at index.2d3ace14.js:122:5
    at index.2d3ace14.js:145:3
dmLkU../index.js @ index.mjs:3
newRequire @ index.2d3ace14.js:71
localRequire @ index.2d3ace14.js:84
ign3V.@swc/helpers @ Category.ts:1
newRequire @ index.2d3ace14.js:71
localRequire @ index.2d3ace14.js:84
4aBH6.typeorm/browser @ index.tsx:3
newRequire @ index.2d3ace14.js:71
(anonymous) @ index.2d3ace14.js:122
(anonymous) @ index.2d3ace14.js:145
```

### Steps to Reproduce

1.
2.

```typescript
// insert code here
# using latest typeorm ^0.2.43
git clone git@github.com:andrewvmail/typeorm-parcel-2-bug.git
git checkout b96d5651035d04db134837679d4cb9f7ce5cde7b
yarn
yarn start # see console for error logs

# using 0.2.25
git checkout main
yarn
yarn start # console shows now errors
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 15.14.0  | 
| Typescript version  | 4.5.5  | 
| TypeORM version     | 0.2.43  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | yes            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
This issue was fixed by #8688 and new version will be published later this week.

**Comment by pleerock** [comment]
Fixed in `0.2.44`

**Comment by andrewvmail** [comment]
@pleerock It's still giving with ```0.2.44```
```
index.mjs:3 Uncaught TypeError: Cannot destructure property 'ConnectionOptionsReader' of '_indexJsDefault.default' as it is undefined.
```

**Comment by mkilp** [comment]
@pleerock I actually seem to be having the same issue with webpack and using typeorm in the serverless framework.

**Comment by pleerock** [comment]
please create a new issue with more details and ask @giladgd to help
