### ISSUE TITLE
Question - Deep joining

### ISSUE THREAD

**Issue by shotor** [typeorm/typeorm#869]
Is the following possible with 1 query?

I have the following relationship:

`User` 1-* `Account` 1-* `Expense` *-1 `Project`

I'm trying to get all the projects a certain user has made expenses for through any of their accounts.

I can get as far as getting the expenses for each account:

```
    const user = await this.repo
      .createQueryBuilder('user')
      .innerJoinAndSelect('user.accounts', 'accounts')
      .leftJoinAndSelect('accounts.expenses', 'expenses')
      // next line breaks
      .leftJoinAndSelect('accounts.expenses.projects', 'projects')
      .where('user.id=:user_id')
      .setParameter('user_id', id)
      .getOne()
```

I've tried multiple variations of the breaking line - but I'm not sure if it's even possible what I'm trying to do.

**Comment by pleerock** [comment]
Try this way:

```ts
const user = await this.repo
      .createQueryBuilder('user')
      .innerJoinAndSelect('user.accounts', 'accounts')
      .leftJoinAndSelect('accounts.expenses', 'expenses')
      .leftJoinAndSelect('expenses.projects', 'projects')
      .where('user.id=:user_id')
      .setParameter('user_id', id)
      .getOne()
```

**Comment by shotor** [comment]
That gives me the following error:
```
Error: Relation with property path projects in entity was not found.
```
But it got me thinking, `Expense` is a `ManyToOne`. So it's correct that it doesn't have a `projects` property, it simply has `project` (confirmed by looking at my code). Changing `projects` from plural to singular fixed the problem.

Question: Can you infinitely join relationships like this?

**Comment by pleerock** [comment]
Yeah but you are limiting by number of joins your database support (for example mysql can support max 64 joins, etc.)

**Comment by arpitadas09** [comment]
I got the same error.

Error: Relation with property path People in entity was not found.Below is my query.I am trying to get center details selecting two tables(centers and People)

 getCenterDetail(centerId: number) {
const centerDetailQuery = getManager();
        return getManager()
        .getRepository(Centers)
        .createQueryBuilder('centersrow')
        .select(['centersrow.id', 'centersrow.name', 'centersrow.url',
        'centersrow.description'])
        .addSelect('People.tamuedupersonofficialname', 'directorName')
        .leftJoinAndSelect('centersrow.Peoples', 'People')
        .where('centersrow.id = :id', { id: centerId } )
        .andWhere('Peoples.uid = centersrow.directorUid')
        .getOne();

can someone help me with this? Ask me, if any further information required.
