### ISSUE TITLE
Interpolation for INTERVAL not working 

### ISSUE THREAD

**Issue by MoSattler** [typeorm/typeorm#8697]
## Issue Description

Interpolation for INTERVAL not working properly. This works fine
```typescript
query.andWhere(
  "session.created BETWEEN NOW() - INTERVAL '60 MINUTES' AND NOW()"
);
```

But this does not
```typescript
query.andWhere(
  "session.created BETWEEN NOW() - INTERVAL ':minutes MINUTES' AND NOW()",
  { minutes: 60 }
);
```

The error message is:
> bind message supplies 1 parameters, but prepared statement \"\" requires 0"

### Expected Behavior

Both cases above should be equivalent.

### Actual Behavior

I get an error message
> bind message supplies 1 parameters, but prepared statement \"\" requires 0"

```
// include the output in code tags like these!
```

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by av** [comment]
Just in case someone else like me finds it.

One other way that allows avoiding multiplication:
```typescript
query.andWhere(
  "entity.updated_at > NOW() - :maxAge::INTERVAL",
 { maxAge: '1 day' },
)
```

Tested with TypeORM v0.2.43, pg v8.7.1

**Comment by AnLuoRidge** [comment]
> Just in case someone else like me finds it.
> 
> One other way that allows avoiding multiplication:
> 
> ```ts
> query.andWhere(
>   "entity.updated_at > NOW() - :maxAge::INTERVAL",
>  { maxAge: '1 day' },
> )
> ```
> 
> Tested with TypeORM v0.2.43, pg v8.7.1

Thank you so much! I was using `INTERVAL :minutes` but it won't work. Didn't realise we can use another way of typecasting.
