### ISSUE TITLE
Suggestion: Utilize Dynamic Properties and Mapped Types

### ISSUE THREAD

**Issue by errorx666** [typeorm/typeorm#87]
These PRs were recently merged to TypeScript, and I think they give us some powerful options for typing.

[Static types for dynamically named properties](https://github.com/Microsoft/TypeScript/pull/11929)

[Mapped types](https://github.com/Microsoft/TypeScript/pull/12114)

For example, they could be used [here](https://github.com/typeorm/typeorm/blob/1c403fd1078daeb35acb2abb7209230162a0fc23/src/entity-manager/BaseEntityManager.ts#L174-L184) to declare `plainObject` as a `Partial<Entity>`, thereby performing type-checking on the anonymous object passed to `entityManager.create`.

**Comment by pleerock** [comment]
these are amazing new features and I 😍 them. But I guess they will not be backward compatible because of multiple new keyword, so its better to integrate them once they are finally released.

**Comment by rightisleft** [comment]
https://github.com/Microsoft/TypeScript/pull/11929 is indeed super exciting!

**Comment by pleerock** [comment]
yeah agree 👍

**Comment by pleerock** [comment]
recent typescript version features already were implemented in typeorm as much as it could have
