### ISSUE TITLE
Nullable columns should be optional in generated typings

### ISSUE THREAD

**Issue by 1nVitr0** [typeorm/typeorm#8703]
## Issue Description

Nullable columns / fields are not optional in generated type. This creates issues when using the type in other contexts where all nullable columns will have to be defined as `null`.

### Expected Behavior

```
// Account.ts

@Entity("account", { database: "listing" })
export class Account extends BaseEntity {
  @Column("int", { primary: true, name: "id" })
  id: number;

  @Column("varchar", { name: "name", nullable: true, length: 45 })
  name: string | null;

  @Column("int", { name: "marketid", nullable: true })
  marketid: number | null;
}
```

should generate corresponsing `Account.d.ts`:

```
export declare class Account extends BaseEntity {
    id: number;
    name?: string | null;
    marketid?: number | null;
}
```

### Actual Behavior

Instead it generates:

```
export declare class Account extends BaseEntity {
    id: number;
    name: string | null;
    marketid: number | null;
}
```

### Steps to Reproduce

1. Create a typeorm TypeScript project
2. Create an Entity with nullable columns
3. Build the project and inspect `*.d.ts` files

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Ubuntu 21.04 |
| Node.js version     |  v16.12.0  | 
| Typescript version  |  4.5.4 | 
| TypeORM version     | 0.2.44  | 

### Relevant Database Driver(s)

I dont't think the issue is database specific.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
This is Typescript issue, and out of scope for TypeORM.
