### ISSUE TITLE
[Website] Search Feature

### ISSUE THREAD

**Issue by BlackBearFTW** [typeorm/typeorm#8704]
Could a search feature be added to the website, its kind of annoying to have to scroll through all the documentation just to find that one paragraph you need.

A good example of a search feature would be on the https://docs.nestjs.com/ website

**Comment by benediktms** [comment]
There is discussion about this on https://github.com/typeorm/typeorm/issues/6964

**Comment by AlexMesser** [comment]
Search was added in [this PR](https://github.com/typeorm/typeorm.github.io/pull/54).
