### ISSUE TITLE
Add full join

### ISSUE THREAD

**Issue by notiv-nt** [typeorm/typeorm#8719]
### The Problem

Can we add `.fullJoin` method to `SelectQueryBuilder` ?

### The Solution

```
import { SelectQueryBuilder } from 'typeorm/query-builder/SelectQueryBuilder';

SelectQueryBuilder.prototype.fullJoin = function(entityOrProperty, alias, condition, parameters) {
  this.join('FULL', entityOrProperty, alias, condition, parameters);
  return this;
};
```

### Considered Alternatives

For now, I have to patch this manually :(

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no           |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes           |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no           |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

A few lines of code. If nobody minds I can make a PR

 - ✅ Yes, I have the time, and I know how to start.

**Comment by Ginden** [comment]
This page claims [it doesn't work on MySQL](https://www.sql-workbench.eu/dbms_comparison.html). Add check for driver and it should be OK.

**Comment by pleerock** [comment]
I'll close this PR for now because I don't see much of value adding this feature. If we see users came up to this feature proposal and suggest motivated reasons behind this feature - we will consider reopening it.

**Comment by Tului2020** [comment]
please add fullJoin :)

**Comment by MrRedBobr** [comment]
We need a "fullJoin"

**Comment by john-hu** [comment]
Please add the `fullJoin` function. Thanks!

**Comment by hastom** [comment]
+ 1 for full join

**Comment by thanh-do-clv** [comment]
please add full join

**Comment by notiv-nt** [comment]
@pleerock mb time to add this feature ?

**Comment by thecurious1-sudo** [comment]
We need fullJoin :) Please add it
