### ISSUE TITLE
Module not found DateUtils

### ISSUE THREAD

**Issue by matthewpflueger** [typeorm/typeorm#8727]
## Issue Description
After upgrading to 0.2.45 from 0.2.41 I get an error bundling my project (with esbuild) for node:

```shell
✘ [ERROR] Could not resolve "typeorm/util/DateUtils"

    ../utilities/lib/db.ts:14:26:
      14 │ import { DateUtils } from 'typeorm/util/DateUtils'
         ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./util/DateUtils" was not found on the file system:

    ../../node_modules/typeorm/package.json:28:16:
      28 │       "import": "./*"
         ╵                 ~~~~~
```

This issue start with 0.2.42 though.

### Expected Behavior

I expect esbuild to find DateUtils when bundling. It seems to me that esbuild gets confused by the import strategy introduced by the esm support in #8536. There is a similar issue #8656 for StringUtils (fix in #8660). Or perhaps this is a regression as indicated in this comment: https://github.com/typeorm/typeorm/issues/8656#issuecomment-1050326500

### Actual Behavior

My esbuild bundle fails with above error in 0.2.45 but not in 0.2.41.

My esbuild configuration is:

```javascript
// NOTE: Most of the externals are the various databases that TypeORM supports...
const external = [
  '@sap/hana-client',
  'amqp-connection-manager',
  'amqplib',
  'aws-sdk',
  'better-sqlite3',
  'fsevents',
  'ioredis',
  'mongodb',
  'hdb-pool',
  'mssql',
  'mysql',
  'mysql2',
  'oracledb',
  'pg',
  'pg-native',
  'pg-query-stream',
  'react-native-sqlite-storage',
  'redis',
  'sql.js',
  'sqlite3',
  'typeorm-aurora-data-api-driver',
]

require('esbuild')
  .build({
    // entry point of compiled Typescript project
    entryPoints: ['./dist/lib/index.js'],
    external,
    bundle: true,
    platform: 'node',
    minifyWhitespace: true,
    outfile: './bundled.js',
  })
  .catch(() => process.exit(1))
```

### Steps to Reproduce

Start a new TypeORM (version 0.2.42 or up) project with Typescript. Bundle with esbuild the output of the Typescript compilation (compiled into CommonJS for usage in node).

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 14  | 
| Typescript version  | 4.6.2  | 
| TypeORM version     | 0.2.45  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | no            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
adding @giladgd

**Comment by giladgd** [comment]
@matthewpflueger Because the compiled TypeScript files are in ESM syntax before you pass them on to esbuild, esbuild treats `import` syntax in these files as ESM imports (like node does), and importing a file without the `.js` extension in ESM is invalid, thus you have to explicitly import `.js` files. (change your code in `../utilities/lib/db.ts:14` to import `"typeorm/util/DateUtils.js"`)

You can also instead make sure the code you pass to esbuild is using CommonJS syntax instead of ESM syntax before you pass it on to esbuild. (change `"module"` in `tsconfig.json` to `"commonjs"`)
