### ISSUE TITLE
Non-integer numbers always returned as string with postgres

### ISSUE THREAD

**Issue by shotor** [typeorm/typeorm#873]
Using `postgres`, when I retrieve a non-integer number from the database it's always returned as string instead of a number. If I use `mysql` and `decimal` it does correctly return number. Am I doing something wrong?

Sample code:
```
import 'reflect-metadata'
import { Entity, PrimaryColumn, Column, createConnection } from 'typeorm'

@Entity()
export class NBlank {
  @PrimaryColumn()
  id: number
  @Column()
  name: string
  @Column()
  n_blank: number
}

@Entity()
export class NNumeric {
  @PrimaryColumn()
  id: number
  @Column()
  name: string
  @Column({ type: 'numeric' })
  n_numeric: number
}

@Entity()
export class NDecimal {
  @PrimaryColumn()
  id: number
  @Column()
  name: string
  @Column({ type: 'decimal' })
  n_decimal: number
}

createConnection({
  type: 'postgres',
  host: 'localhost',
  port: 5432,
  username: 'postgres',
  password: '',
  database: "test",
  entities: [
      NBlank,
      NNumeric,
      NDecimal
  ],
  autoSchemaSync: true,
}).then(async connection => {
  
  const blank = new NBlank()
  blank.id = 1
  blank.name = 'blank'
  blank.n_blank = 12 // must be integer
  await connection.manager.save(blank);
  const blanks = await connection.manager.find(NBlank)
  console.log(typeof blanks[0].n_blank) // number

  const numeric = new NNumeric()
  numeric.id = 4
  numeric.name = 'blank'
  numeric.n_numeric = 12.65
  await connection.manager.save(numeric);
  const numerics = await connection.manager.find(NNumeric)
  console.log(typeof numerics[0].n_numeric) // string
  
  const decimal = new NDecimal()
  decimal.id = 1
  decimal.name = 'blank'
  decimal.n_decimal = 12.65
  await connection.manager.save(decimal);
  const decimals = await connection.manager.find(NDecimal)
  console.log(typeof decimals[0].n_decimal) // string

}).catch(error => console.log(error));
```

**Comment by pleerock** [comment]
If some type looks numeric but uses string instead of number, it means it cannot store its number in a regular javascript's "number" type because of length limitations javascript number has. That's why string is used instead of number.

**Comment by shotor** [comment]
The number I used in the sample is `12.65`. And I encountered this in my own app on the number `0`. Does that mean `postgres` is returning the number as a larger number than it should be?

**Comment by pleerock** [comment]
> The number I used in the sample is 12.65:

right, but it could be longer number, right? It cant be number for a short number and string for a long number, right?

> Does that mean postgres is returning the number as a larger number than it should be?

Fair question, however I don't remember that I make any operations with numeric type over what underlying driver does. So, I think you shall ask your question to [pg](https://github.com/brianc/node-postgres/) why they use strings for "numeric" type

**Comment by shotor** [comment]
> right, but it could be longer number, right? It cant be number for a short number and string for a long number, right?

Ah, I see you're point. It's a safeguard.

> Fair question, however I don't remember that I make any operations with numeric type over what underlying driver does. So, I think you shall ask your question to pg why they use strings for "numeric" type

Thanks for pointing me to the right direction - I found this handy table in their issue list:

```
smallint:         parseInt()
integer:          parseInt()
bigint:           string
decimal:          string
numeric:          string
real:             parseFloat()
double precision: parseFloat()
smallserial:      parseInt()
serial:           parseInt()
bigserial:        string
```

Unfortunately the precision (6 and 15 decimal digits) for `real` and `double` don't satisfy my use case.

Is there a way to define a parser for all numeric types? The `pg-types` project talks about `setParser` but I'm not sure if we can do anything like this with `typeorm`:
https://github.com/brianc/node-pg-types/
```
var types = require('pg').types
types.setTypeParser(20, function(val) {
  return parseInt(val)
})
```

The only way I know to fix it, without changing database technology, is to do something like this:
```
  @AfterLoad() _convertNumerics() {
    // 64 bits truncated to 53 is fine in my case
    this.expenses = parseFloat(this.expenses as any)
  }
```

**Comment by pleerock** [comment]
There is no "official" way to do what you want. Probably the way you do is okay for your use case and you can continue to use it.

**Comment by shotor** [comment]
From: https://github.com/typeorm/typeorm/issues/289
```
pg.types.setTypeParser(1700, (v:any) => parseFloat(v))
```
Works for now. Will follow the referenced issue. Thanks!

**Comment by john20xdoe** [comment]
Sharing a transformer we use:
```
/// ColumnNumericTransformer
export class ColumnNumericTransformer {
  to(data: number): number {
    return data;
  }
  from(data: string): number {
    return parseFloat(data);
  }
}
```

in entity:
```
 @Column('numeric', {
    precision: 7,
    scale: 2,
    transformer: new ColumnNumericTransformer(),
  })
  public myNumericColumn: number;
```

**Comment by saoudrizwan** [comment]
For anyone wondering how to use @john20xdoe's transformer with `nullable` columns:
```typescript
function isNullOrUndefined<T>(obj: T | null | undefined): obj is null | undefined {
	return typeof obj === "undefined" || obj === null
}
```

```typescript
import { ValueTransformer } from "typeorm"
import { isNullOrUndefined } from "../../utils/utils"

export class ColumnNumericTransformer implements ValueTransformer {
	to(data?: number | null): number | null {
		if (!isNullOrUndefined(data)) {
			return data
		}
		return null
	}

	from(data?: string | null): number | null {
		if (!isNullOrUndefined(data)) {
			const res = parseFloat(data)
			if (isNaN(res)) {
				return null
			} else {
				return res
			}
		}
		return null
	}
}
```

Postgres can't store `undefined`. You can either store the value or `null`, and retrieve the value or `null`. When you create a new object with nullable columns undefined, then typeorm stores `null` in these columns.

**Comment by mmalafaia** [comment]
> > right, but it could be longer number, right? It cant be number for a short number and string for a long number, right?
> 
> Ah, I see your point. It's a safeguard.
> 
> > Fair question, however I don't remember that I make any operations with numeric type over what underlying driver does. So, I think you shall ask your question to pg why they use strings for "numeric" type
> 
> Thanks for pointing me to the right direction - I found this handy table in their issue list:
> 
> ```
> smallint:         parseInt()
> integer:          parseInt()
> bigint:           string
> decimal:          string
> numeric:          string
> real:             parseFloat()
> double precision: parseFloat()
> smallserial:      parseInt()
> serial:           parseInt()
> bigserial:        string
> ```
> 
> Unfortunately the precision (6 and 15 decimal digits) for `real` and `double` don't satisfy my use case.
> 
> Is there a way to define a parser for all numeric types? The `pg-types` project talks about `setParser` but I'm not sure if we can do anything like this with `typeorm`:
> https://github.com/brianc/node-pg-types/
> 
> ```
> var types = require('pg').types
> types.setTypeParser(20, function(val) {
>   return parseInt(val)
> })
> ```
> 
> The only way I know to fix it, without changing database technology, is to do something like this:
> 
> ```
>   @AfterLoad() _convertNumerics() {
>     // 64 bits truncated to 53 is fine in my case
>     this.expenses = parseFloat(this.expenses as any)
>   }
> ```

Thanks, helped me a lot.

**Comment by Alex0881** [comment]
Good day. I have in Entity

@Column({
    type: 'decimal',
    precision: 12,
    scale: 2,
    default: 0,
    transformer: new ColumnNumericTransformer(),
  })
  rating: number;

And i have

export class ColumnNumericTransformer {
  to(data: number): number {
    return data;
  }
  from(data: string): number {
    return parseFloat(data);
  }
}

When i make query with select i get a number in this column. It's ok.
When i make update

 const updatedVotedForUser = await qRunner.manager
        .createQueryBuilder()
        .update(UserEntity)
        .set({
          rating: () => 'rating + :deltaValue',
        })
        .where('id = :id', {
          id: votedForUserId,
        })
        .setParameter('deltaValue', deltaValue)
        .returning('rating')
        .execute();

it translates into UPDATE "t_users" SET "rating" = rating + $1, "version" = "version" + 1 WHERE "id" = $2 RETURNING rating 

and i have rating as string.

How to correct this situation ?

**Comment by Emanuel-Palestino** [comment]
I set the ```supportBigNumbers: false``` property in the DataSource options and I get correct number type in all queries result.

**Comment by Emanuel-Palestino** [comment]
Sorry @anmolp-plateron , the ```supportBigNumbers: false``` is only for mysql db.

**Comment by valtinhonf** [comment]
Hi everybody. Sorry by my poor english, but i have the same problem with typeorm + postgres, but in cases of mapped entities, is possible to use _transformers_ , but in some cases of not mapped entities i am unable do this. The way I can solve this is perhaps the craziest, is with a _*loop for*_ assigning to a new object. This is necessary for my, because a reports with inner joins and more, where i don't have a mapped entity. In case of number returning as string is difficult to order, for example.

I don't know if I was clear. Some one to help-me?

**Comment by apipornvideos** [comment]
or if you are doing query builder like me do this

```typescript
const data = await this.sitemapTable
      .createQueryBuilder('t')
      .where('t.generated = false')
      .select([
        't.url AS url',
        'cast(t.priority as smallint) AS priority', // convert to smallint
        't.changefreq AS changefreq',
        't.updated_at AS lastmod',
        't.id AS id',
      ])
      .getRawMany();
      
```
