### ISSUE TITLE
Typeorm creating new transactions by using .create({...}).save()

### ISSUE THREAD

**Issue by pmsfc** [typeorm/typeorm#8739]
## Issue Description

When using transactions with postgres, typeorm is creating intermediate transactions if we use .create() before saving while using the entity manager.

### Expected Behavior

```typescript
import {getManager} from "typeorm";
await getManager().transaction(async transactionalEntityManager => {
    await transactionalEntityManager.save(users);
    await transactionalEntityManager.save(photos);
    await transactionalEntityManager
      .getRepository(Cars)
      .create({
        ...properties
      })
      .save();
});
```

All this operations should run inside a single transaction.

### Actual Behavior

Typeorm is creating new transactions everytime we use .create before save. If we move the object inside the save({...properties}), then it works as expected.

In our use case, this is what happens:

```SQL
START TRANSACTION
SELECT 
INSERT INTO 
START TRANSACTION
INSERT INTO
COMMIT
SELECT DISTINCT 
SELECT 
START TRANSACTION
INSERT  INTO
COMMIT
COMMIT
```
### Steps to Reproduce

1.
Start a transaction with
```typescript
import {getManager} from "typeorm";
await getManager().transaction(async transactionalEntityManager => {

});
```

2.
Perform this operations inside the transaction.
```typescript 
await transactionalEntityManager.save(users);
await transactionalEntityManager.save(photos);
await transactionalEntityManager
  .getRepository(Cars)
  .create({
    ...properties
  })
  .save();
```

3.
Move the object from the .create to the save. It should now work as expected and use a single transaction.
```typescript 
await transactionalEntityManager.save(users);
await transactionalEntityManager.save(photos);
await transactionalEntityManager
  .getRepository(Cars)
  .save({
    ...properties
  });
```

### My Environment
| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 14.17.5 | 
| Typescript version  | 4.4.3 | 
| TypeORM version     | 0.2.45 |

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `postgres`           | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?
 - ✖️ Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pmsfc** [comment]
After some investigation I noticed that the issue is that I was creating the entity, and that entity extended the baseEntity thus having the Active Record .save() that was running outside the transaction.
It's very easy to fall into this if you start with Active Record and change to Data mapper while you forget to remove the the base entity.
No issue with Typeorm, just user error I'll close this.

**Comment by dberardo-com** [comment]
i believe i am facing a similar issue but i am not calling create() at any moment ... from your example i could not get what was generating the issue in the first place, could you provide more details perhaps ?

**Comment by sgarner** [comment]
Please check that you are using transactions correctly:

https://typeorm.io/docs/advanced-topics/transactions

> The most important restriction when working in a transaction is to ALWAYS use the provided instance of entity manager - `transactionalEntityManager` in this example. **DO NOT USE GLOBAL ENTITY MANAGER.** All operations MUST be executed using the provided transactional entity manager.
