### ISSUE TITLE
Bug in default migration value for timestamp fields (Postgresql)

### ISSUE THREAD

**Issue by walisoncm** [typeorm/typeorm#8744]
In the entity I have this code:
```ts
@Entity()
export class Person {

    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({ name: 'created_at', default: 'CURRENT_TIMESTAMP' })
    createdAt: Date;

}
```

In migration there is this script:
```ts
public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "person" ALTER COLUMN "created_at" SET DEFAULT now()`);
}
```

When run migration is this error:
```
invalid input syntax for type timestamp: "Fri Mar 11 2022 12:30:56 GMT-0300 (Horário Padrão de Brasília)"
```

The query value is:
```sql
ALTER TABLE "country" ALTER COLUMN "created_at" SET DEFAULT 'Fri Mar 11 2022 12:30:56 GMT-0300 (Horário Padrão de Brasília)'
```

**Comment by iJhefe** [comment]
**this is not a Typeorm error**, its migration is written wrong, because the default value is invalid, it should be "CURRENT_TIMESTAMP".

You can use the Typeorm framework to create migrations, in your case, import `TableColumn` and set the type and default value to "CURRENT_TIMESTAMP".

**Comment by walisoncm** [comment]
> **this is not a Typeorm error**, its migration is written wrong, because the default value is invalid, it should be "CURRENT_TIMESTAMP".
> 
> You can use the Typeorm framework to create migrations, in your case, import `TableColumn` and set the type and default value to "CURRENT_TIMESTAMP".

My migration is generated by typeorm:
```
npm run typeorm migration:generate -- -n nameMigration
```

In my entity I write CURRENT_TIMESTAMP, but in the migration it generated now()

**Comment by alkihis** [comment]
Hi,
Your ` @Column({ name: 'created_at', default: 'CURRENT_TIMESTAMP' })` is wrong :)

You should write instead:
```ts
 @Column({ name: 'created_at', default: () => 'now()' })
```
