### ISSUE TITLE
Request to improve the RepositoryNotFoundError message

### ISSUE THREAD

**Issue by plutownium** [typeorm/typeorm#8756]
## Feature Description

Modify RepositoryNotFoundError to say *where* the repository was not found.

### The Problem

Currently, RepositoryNotFoundError says, for example:

RepositoryNotFoundError: No repository for "FailedLoginEntity" was found. Looks like this entity is not registered in current "default" connection?

I know for a fact this has been caused at least 3x for me by failing to register the entity in a module. like this:

```
@Module({
    imports: [
        HttpModule,
        ConfigModule.forRoot({
            ignoreEnvFile: environment.production,
        }),
        TypeOrmModule.forRoot({
            type: 'postgres',
            host: process.env.DB_HOST,
            port: +process.env.DB_PORT || 5432,
            username: process.env.DB_USERNAME,
            password: process.env.DB_PASSWORD,
            database: process.env.DB_DATABASE,
            entities: [
                ProfileEntity,
                UserProfileRelationEntity,
                ProfileRoleEntity,
                UserEntity,
                PasswordResetTokenEntity,
                RefreshTokenEntity,
            ],
            synchronize: true,
        }),
        TypeOrmModule.forFeature([
            ProfileEntity,

            UserEntity,
            PasswordResetTokenEntity,
            RefreshTokenEntity,
        ]),
    ],
    controllers: [ProfilesSvcController],
    providers: [ProfilesService, UserProfileRelationService, ProfileRolesService],
    exports: [ProfilesService, UserProfileRelationService],
})
```

Maybe it's more technically challenging that I imagine, but why can't the error direct me to *where* the entity is not registered?

### The Solution

When the error is detected, typeORM can look at places the given entity is being used. Maybe look up one or two levels of of directories and down and see if the entity could be registered in a related file.

Maybe I'm naive and this is a lot harder than I think it is.

### Considered Alternatives

Could the error message simply say in the stack trace which file the error is coming from? Here's mine:

```
profiles-svc_1           |     at RepositoryNotFoundError.TypeORMError [as constructor] (/app/src/error/TypeORMError.ts:7:9)
profiles-svc_1           |     at new RepositoryNotFoundError (/app/src/error/RepositoryNotFoundError.ts:10:9)
profiles-svc_1           |     at EntityManager.getRepository (/app/src/entity-manager/EntityManager.ts:987:19)
profiles-svc_1           |     at Connection.getRepository (/app/src/connection/Connection.ts:339:29)
profiles-svc_1           |     at InstanceWrapper.useFactory [as metatype] (/app/node_modules/@nestjs/typeorm/dist/typeorm.providers.js:17:30)
profiles-svc_1           |     at Injector.instantiateClass (/app/node_modules/@nestjs/core/injector/injector.js:304:55)
profiles-svc_1           |     at callback (/app/node_modules/@nestjs/core/injector/injector.js:48:41)
profiles-svc_1           |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
profiles-svc_1           |     at Injector.resolveConstructorParams (/app/node_modules/@nestjs/core/injector/injector.js:124:24)
profiles-svc_1           |     at Injector.loadInstance (/app/node_modules/@nestjs/core/injector/injector.js:52:9)
profiles-svc_1           |     at Injector.loadProvider (/app/node_modules/@nestjs/core/injector/injector.js:74:9)
profiles-svc_1           |     at Injector.lookupComponentInImports (/app/node_modules/@nestjs/core/injector/injector.js:236:17)
profiles-svc_1           |     at Injector.lookupComponentInParentModules (/app/node_modules/@nestjs/core/injector/injector.js:200:33)
profiles-svc_1           |     at Injector.resolveComponentInstance (/app/node_modules/@nestjs/core/injector/injector.js:157:33)
profiles-svc_1           |     at resolveParam (/app/node_modules/@nestjs/core/injector/injector.js:108:38)
profiles-svc_1           |     at async Promise.all (index 3)
```
I see no clues.

### Additional Context

You could cut down on users' development time significantly if the change is easy to make. Cost/benefit analysis is required of course.

### Relevant Database Driver(s)

I have no idea which databases this affects, Ive only used Postgres.

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
the way we load entities has changed in `0.3.0`, so there is no `RepositoryNotFoundError` anymore.
