### ISSUE TITLE
0.3.0: Transaction withRepository does not contain custom methods

### ISSUE THREAD

**Issue by Q16solver** [typeorm/typeorm#8759]
## Issue Description

I had defined a custom function through extending:

![image](https://user-images.githubusercontent.com/50786287/158995515-f888712d-2f52-4274-9158-486b780dbd3b.png)

But I cannot use it in transactions, I think this wasn't intended

![image](https://user-images.githubusercontent.com/50786287/158995321-e5e9af1d-cd19-4ca1-8aec-0f6191cc4acc.png)

The code seems like it just calls the original constructor which is probably why, I'm not quite sure if there's a good way to fix this

![image](https://user-images.githubusercontent.com/50786287/158995859-36dd27a9-51d8-4d3c-b086-b1fd2f79416a.png)

### Expected Behavior

Transactional entity manager should have access to custom extended functions

### Actual Behavior

Transactional entity manager only has access to builtin functions

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  | 
| Typescript version  | x.y.zzz  | 
| TypeORM version     | x.y.zzz  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅ No, I don’t have the time, but I can support (using donations) development. 5$
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
fixed by #8764

**Comment by Q16solver** [comment]
@pleerock Confirmed this is fixed in 0.3.1, donated 👍
