### ISSUE TITLE
How to select appropriate column from join table?

### ISSUE THREAD

**Issue by appwudo** [typeorm/typeorm#876]
I would like to remove some column from my result, in order to get rid of the user details. I tried with  .select(['uad.*', 'ua.*', 'u.name']) but doesn't work. How should I do?

```
    const query = db.getRepository(UserActivityDo)
        .createQueryBuilder('uad')
        .innerJoinAndSelect('uad.idUserActivity', 'ua')
        .innerJoinAndSelect('ua.idUser', 'u')
        // .select(['uad.*', 'ua.*', 'u.name'])
        .where(`ua.idUser IN (${userIds.join(',')})`)       
        .orderBy('uad.created', 'DESC');

```

This is the result I get from the previous query. How can I only keep the user.name of the user relation?

```
[
            {
                "idUserActivityDo": 10,
                "description": "",
                "created": "2017-09-11T22:13:15.327Z",
                "idUserActivity": {
                    "idUserActivity": 21,
                    "activityName": "lolololol",
                    "i18n": "en_US",
                    "created": "2017-09-11T22:11:27.855Z",
                    "idUser": {
                        "idUser": 41,
                        "email": "ooooo@ooooo.com",
                        "hashedPassword": "$2a$10$gf3m/6FP/a/8V.Q7K",
                        "salt": "$2a$10$55SB/gk0.",
                        "name": "jgfhfhfhfhfj",
                        "created": "2017-09-10T16:10:36.861Z",
                        "pushToken": "ExponentPushToken[ssffsdfds]"
                    }
                }
            },
            {
                "idUserActivityDo": 9,
                "description": "",
                "created": "2017-09-11T22:13:04.320Z",
                "idUserActivity": {
                    "idUserActivity": 21,
                    "activityName": "lolololol",
                    "i18n": "en_US",
                    "created": "2017-09-11T22:11:27.855Z",
                    "idUser": {
                        "idUser": 40,
                        "email": "world@ooooo.com",
                        "hashedPassword": "$2a$10$gf3m/6FP/a/8V.Q7K",
                        "salt": "$2a$10$55SB/gk0.",
                        "name": "jgfhfhfhfhfj",
                        "created": "2017-09-10T16:10:36.861Z",
                        "pushToken": "ExponentPushToken[ssffsdfds]"
                    }
                }
            },
            {
                "idUserActivityDo": 8,
                "description": "",
                "created": "2017-09-11T22:08:12.452Z",
                "idUserActivity": {
                    "idUserActivity": 12,
                    "activityName": "fffgghgf",
                    "i18n": "en_US",
                    "created": "2017-09-10T19:01:41.373Z",
                    "idUser": {
                        "idUser": 42,
                        "email": "helo@ooooo.com",
                        "hashedPassword": "$2a$10$gf3m/6FP/a/8V.Q7K",
                        "salt": "$2a$10$55SB/gk0.",
                        "name": "jgfhfhfhfhfj",
                        "created": "2017-09-10T16:10:36.861Z",
                        "pushToken": "ExponentPushToken[ssffsdfds]"
                    }
                }
            },...
```

**Comment by varHarrie** [comment]
```typescript
const query = db.getRepository(UserActivityDo)
        .select(['uad', 'ua', 'u.name'])
        .createQueryBuilder('uad')
        .innerJoinAndSelect('uad.idUserActivity', 'ua')
        .innerJoinAndSelect('ua.idUser', 'u')
        .where(`ua.idUser IN (${userIds.join(',')})`)       
        .orderBy('uad.created', 'DESC')
```
Replace `innerJoinAndSelect` with `innerJoin`

**Comment by appwudo** [comment]
Ah yes, after upgrading to the last version of typeORM it is finally working ;-) thanks

**Comment by kwehrle** [comment]
Hi, this is not working for me (using V 0.2.7). 

1. the select cannot be the first after getRepository() (VSCode is throwing an error)
2. With the select I only get the values from the Inquriy-Table (inq) and not the values from the joined Table DocUnitType (dut).
3. The generated SQL-Statement seems to be correct and executed in the database works fine: SELECT "inq"."id" AS "inq_id", "inq"."bsnr" AS "inq_bsnr", "inq"."dt" AS "inq_dt", "inq"."status" AS "inq_status", "dut"."name" AS "dut_name", "dut"."id" AS "dut_id"
FROM "mdat"."inquiry" "inq"
  INNER JOIN "def"."doc_unit_type" "dut" ON "inq"."doc_unit_type_id" = "dut"."id" WHERE "inq"."participant_id" = $1 ORDER BY "inq"."dt" DESC -- PARAMETERS: ["6d964e85-a6b2-4a1b-b3c2-8b49074f6082"]`

What is going wrong?

```
await db.getRepository(Inquiry)
			.createQueryBuilder('inq')
			.innerJoin(DocUnitType, 'dut', 'inq.docUnitTypeID = dut.ID')
			.select(['inq.ID','inq.dt','inq.status','inq.bsnr','dut.name'])
			.where('inq.participantID = :partID', { partID })
			.orderBy('inq.dt', 'DESC')
			.getMany();
```

**Comment by timothyvanderaerden** [comment]
@kwehrle not sure if you are still looking for the answer. But you should use addSelect in this case.

```javascript
await db.getRepository(Inquiry)
	.createQueryBuilder('inq')
	.innerJoin(DocUnitType, 'dut', 'inq.docUnitTypeID = dut.ID')
        .select(['inq.ID','inq.dt','inq.status','inq.bsnr'])
	.addSelect('dut.name')
	.where('inq.participantID = :partID', { partID })
	.orderBy('inq.dt', 'DESC')
	.getMany();
```

**Comment by kongbt** [comment]
I always get the undefined value of the variable id_port when I call this function but other values still exist. Please help me
thanks!
async getAvaiableMobile(_amount:number,_type:string):Promise<any>{         
        return this.repository.createQueryBuilder("mobile_list")            
            .select("mobile_list")
            .addSelect("portussd.id_port")
            .innerJoinAndSelect(sms_portussd, "portussd", "mobile_list.mobile = portussd.mobile")
            .where("need_amount - charg_amount >= :amount", {amount:_amount})
            .andWhere("portussd.status=:status1",{status1:1})
            .orderBy("need_amount - charg_amount","DESC")
            .addOrderBy("portussd.last_update", "DESC")   
            .getOne();
    }

**Comment by OLDIN** [comment]
A have same problem.
Version: _0.2.22_
DB: _postgresql_

My code:
```
const result = await this._orderCfRepo.createQueryBuilder('ocf')
      .select('ocf')
      .addSelect('cf.id')
      .addSelect('cf.type')
      .innerJoin(CustomField, 'cf', 'cf.id = ocf.customFieldId')
      .getOne();
```

Generated SQL:
```
SELECT
"ocf"."deletedAt" AS "ocf_deletedAt",
"ocf"."inputValue" AS "ocf_inputValue",
"ocf"."customFieldId" AS "ocf_customFieldId",
"ocf"."orderId" AS "ocf_orderId",
"ocf"."customFieldItemId" AS "ocf_customFieldItemId", 
"cf"."id" AS "cf_id", 
"cf"."type" AS "cf_type"
FROM "orderCFItem" "ocf"
INNER JOIN "customField" "cf" ON "cf"."id" = "ocf"."customFieldId"
```

Expected:
```
OrderCFItem {
  deletedAt: null,
  inputValue: '380454635552',
  customFieldId: 1,
  orderId: 80,
  customFieldItemId: null
  customField: CustomField {
    id: 1
    type: 'list'
  }
}
```


But in console:
```
OrderCFItem {
  deletedAt: null,
  inputValue: '380454635552',
  customFieldId: 1,
  orderId: 80,
  customFieldItemId: null
}
```

**Comment by OLDIN** [comment]
only works if replaced:

```.innerJoin(CustomField, 'cf', 'cf.id = ocf.customFieldId')```

at

```.innerJoin('ocf.customField', 'cf', 'cf.id = ocf.customFieldId')```

**Comment by elle86a** [comment]
@OLDIN i think you not have added the relations in the entity.
The 'cf.id = ocf.customFieldId' is a join where not needed if have the relation upset

**Comment by OLDIN** [comment]
@elle86a no, the first argument must be a string instead an entity (no need to focus on the third argument).

**Comment by RocaManuel** [comment]
i think what elle86a says is that if you create the relation in the Entity you will have a field that is the relation for ex:

@ManyToMany(..)
@JoinColumn(...)
field_name: Entity;

so the first argument is the "field_name" that represents that relation (and where you will display it) if i'm not wrong or if i didn't miss understood

**Comment by vinitkantrod** [comment]
> @kwehrle not sure if you are still looking for the answer. But you should use addSelect in this case.
> 
> ```js
> await db.getRepository(Inquiry)
> 	.createQueryBuilder('inq')
> 	.innerJoin(DocUnitType, 'dut', 'inq.docUnitTypeID = dut.ID')
>         .select(['inq.ID','inq.dt','inq.status','inq.bsnr'])
> 	.addSelect('dut.name')
> 	.where('inq.participantID = :partID', { partID })
> 	.orderBy('inq.dt', 'DESC')
> 	.getMany();
> ```

I am getting error in `Select disctinct` query which typeorm calls by default for innerjoin and count. 

This is my query
```const query = getRepository(ProductListing)
      .createQueryBuilder('productListing')
      .innerJoin('productListing.sellerProduct', 'sellerProduct',
        'sellerProduct.deletedToken = :token',
        { token: application.NOT_APPLICABLE })
        .select([
          'productListing.label',
          'productListing.pricing_type',
          'productListing.selling_price',
          'productListing.status',
          'productListing.start_date',
          'productListing.end_date',
          'sellerProduct.spin']).skip(0).take(10).getManyAndCount();
```
