### ISSUE TITLE
docs: Connection section is gone

### ISSUE THREAD

**Issue by nc7s** [typeorm/typeorm#8763]
### What was unclear or otherwise insufficient?

The entire Connection section is gone in the docs. https://typeorm.io/#/connection says 404 not found.

The 0.3.0 release commit 3b8a031ece508820651a3a8f99f9cbf87319812c seems to clear out `docs/connection*.md` (https://github.com/typeorm/typeorm/commit/3b8a031ece508820651a3a8f99f9cbf87319812c#diff-fa278555fb65669e549c2535e467267ec7e7f1964493db9a311c49c9843db276).

Its description didn't seem to tell why.

https://github.com/typeorm/typeorm/pull/8616 says `Connection` is deprecated in favor of `DataSource`,
but its doc doesn't seem to appear.

### Recommended Fix

Add it back? It's deprecated, not removed.

Also, add docs of `DataSource`.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
> Add it back? It's deprecated, not removed.

No. No need to confuse new users. We only need documentation for non-deprecated features.

**Comment by bnoctis** [comment]
Reasonable. But removing the old without the new in place did, at least, confuse me, hence this issue. Had to dig into the code for connection (or *DataSource*) options.

Happy to help, but not very familiar around as just starting to use it.

**Comment by glen-84** [comment]
@pleerock,

1. Has support for `.env` files been dropped? Do we need to use something like [dotenv](https://github.com/motdotla/dotenv) directly?
2. Could you please provide an example of configuring entities/migrations using "entity references"? Do you have to import every entity individually?

**Comment by pleerock** [comment]
@glen-84  

> Has support for .env files been dropped? Do we need to use something like [dotenv](https://github.com/motdotla/dotenv) directly?

yes

> Could you please provide an example of configuring entities/migrations using "entity references"? Do you have to import every entity individually?

yes, you have to import every entity individually. Two main reasons behind this decision:

1. when you import every entity individually you don't have issues like old compiled entities left in `outDir` directory that are still in there and being loaded - this is super confusing issue for newcomer users
2. having entity references explicitly defined opens ability to make type-safer repositories and manager (future features)
