### ISSUE TITLE
[0.3] Datasource not set on entities when using path in entities datasource options

### ISSUE THREAD

**Issue by niranjan94** [typeorm/typeorm#8768]
## Issue Description

When globs are specified in `entities` of `DataSource` options like the following, `entity.useDataSource()` is not automatically called as expected on the entities and as a result the error `Error: DataSource is not set for this entity.` is thrown when trying to perform operations with the entity (Active Record pattern)

```
const dataSource = new DataSource({
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "root",
    password: "admin",
    database: "test",
    synchronize: true,
    entities: [__dirname + "/entity/*.{js,ts}"],
})
```

### Expected Behavior

The operations performed on the entities should succeed.

### Actual Behavior

The error `Error: DataSource is not set for this entity.` is thrown when trying to perform operations with the entity (Active Record pattern)

```
Error: DataSource is not set for this entity.
```

### Steps to Reproduce

This sample should be able to reproduce the issue.
https://github.com/typeorm/typeorm/tree/master/sample/sample11-all-types-entity

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    MacOS Montery 12.3      |
| Node.js version     | v16.13.0  | 
| Typescript version  | 4.6.2  | 
| TypeORM version     | 0.3.1  | 

### Additional Context

Looking at https://github.com/typeorm/typeorm/blob/d61f857ce9447a25d074810759fd5c4aad9a08e3/src/data-source/DataSource.ts#L631-L678 , it seems like the array of paths/globs is never resolved into the respective classes anywhere here. As a result this bit is never run https://github.com/typeorm/typeorm/blob/d61f857ce9447a25d074810759fd5c4aad9a08e3/src/data-source/DataSource.ts#L674-L676 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by danielschwartz4** [comment]
You may need to change "database: "test"," to "url: "test","
