### ISSUE TITLE
How to set Current time stamp as default value

### ISSUE THREAD

**Issue by imhari213** [typeorm/typeorm#877]
How to set Current time stamp as default value

**Comment by pleerock** [comment]
How do you do it in your database using sql? I guess its something like:

```ts
@Column({ type: "timestamp", default: () => "CURRENT_TIMESTAMP"))
time: string;
```

`() => ` syntax for `default` allows to use SQL expressions.

**Comment by imhari213** [comment]
THANK YOU :)

**Comment by roeehershko** [comment]
For the copy paste lovers like me:
```
    @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP'})
```

**Comment by armanfatahi** [comment]
There is something else you need to consider:

CURRENT_TIMESTAMP should be used with `timestamp with time zone`:

```
  @Column('timestamp with time zone', { nullable: false, default: () => 'CURRENT_TIMESTAMP' })  
  created: Date;
```

Unless the Postgres converts the value to the timezone _AGAIN_ which will cause some trouble later on.

**Comment by billyjov** [comment]
> How do you do it in your database using sql? I guess its something like:
> 
> ```ts
> @Column({ type: "timestamp", default: () => "CURRENT_TIMESTAMP"))
> time: string;
> ```
> 
> `() => ` syntax for `default` allows to use SQL expressions.

@pleerock i get an error trying to use an SQL statement with the syntax: 

```
default: () => 'DATE_ADD(NOW(), INTERVAL 2 HOUR)',

```

not working as expected and typeorm throw an error: 

```
 errno: 1064,
  sqlMessage:
   'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'DATE_ADD(NOW(), INTERVAL 2 HOUR)\' at line 1',
  sqlState: '42000',
  index: 0,
  sql:
   'ALTER TABLE `dueDate` CHANGE `dueDate` `dueDate` timestamp NOT NULL DEFAULT DATE_ADD(NOW(), INTERVAL 2 HOUR)' }
```
PS. i use mysql with the latest typorm version.

**Comment by jdnichollsc** [comment]
Other option could be this:
```
@CreateDateColumn({ type: 'timestamp without time zone', default: 'NOW()' })
createdAt: Date

@UpdateDateColumn({ type: 'timestamp without time zone', onUpdate: 'NOW()', nullable: true })
updatedAt: Date
```
What do you think?

**Comment by baublet** [comment]
FYI, for those looking as of Tuesday, February 2, 2021, for some reason TypeORM converts `default: () => "CURRENT_TIMESTAMP"` to `now()` when using postgres 9.6. This meant that TypeORM generates new migrations changing their default type from `now()` to `CURRENT_TIMESTAMP` every time you try to generate new migrations.

The fix for us was to use this instead:

```ts
@Column({ type: "timestamp", default: () => "now()"))
time: string;
```

**Comment by xiongsongsong** [comment]
In MySQL 8:
```
@Column('date', { default: () => '(CURRENT_DATE)' })
last_date: Date;
``

**Comment by ahsanjamal10p** [comment]
Can we use a Javascript function in the default instead of a SQL expression? For scenarios like calculating the year based on some current date conditions.

**Comment by seltsamonkel** [comment]
For postgres I first created a migration with
```
@Column('date', { default: () => 'CURRENT_DATE::text::date' })
last_date: Date;
```
This created the column in postgres as `default ((CURRENT_DATE))`, then I changed the code to
```
@Column('date', { default: () => '((CURRENT_DATE))' })
last_date: Date;
```
With this change, the TypeORM generated default and the default on postgres are both `((CURRENT_DATE))`, so no migrations are created afterward.

**Comment by NateFerrero** [comment]
When creating a table on Postgres, I didn't need to use `() => ` to get an expression default:

```TypeScript
await queryRunner.createTable(
  new Table({
  name: 'my-table',
  columns: [
    {
      name: "status",
      default: "'created'", // constant default
      type: "text"
    },
    {
      name: "created_at",
      type: "timestamp(0) without time zone",
      default: 'now()' // expression default
    }
  ]
  }),
  true, true, true
)
```

**Comment by PRossetti** [comment]
You can do 
```
@Column({ type: "timestamp", default: () => "now()" })
time: Date;
```

Have in mind this is not the same as doing:
```
@Column({ type: "timestamp", default: "now()" })
time: Date;
```

This last option in my case at least throw error in CI because it wasn't doing what it looks, so try going with the first alternative I mentioned.

**Comment by abu18saud** [comment]
using () => 'CURRENT_TIMESTAMP' with add 2 years by nestjs?
