### ISSUE TITLE
Treat JSON(B) Field as "simple-json" in SQLite

### ISSUE THREAD

**Issue by H4kor** [typeorm/typeorm#8770]
## Feature Description

Allow usage of the types "json" and "jsonb" with SQLite. This would allow using SQLite in local development and testing while targeting postgres in deployments.

### The Problem

Cannot use sqlite when using any fields with "json" or "jsonb" fields

### The Solution

Treat "json" and "jsonb" the same way as "simple-json" when using a sqlite backend

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | yes            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | yes            |
| `sqlite-abstract` | yes            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
trying to "fit" different types is quite problematic because it leads to different design questions and further user issues because of compromises we are going to choose. Consider runtime-checks in your implementation, for example:

```ts
@Column({
  type: process.env.mode === "sqlite" ? "simple-json" : "json"
})
```

and of course you can make it look better by extracting values in a globally exported `const`.
