### ISSUE TITLE
cli options not part of DataSourceOptions type

### ISSUE THREAD

**Issue by vdhpieter** [typeorm/typeorm#8783]
### Expected Behavior

There is a clear way documented to set CLI options such as entity directory.

### Actual Behavior

All the documentation mentions adding this to the `DataSourceOptions`
```
cli: {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
```

But the type won't allow it

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  MacOS 12.3 |
| Node.js version     | 16.5.0  | 
| Typescript version  | 4.6.2  | 
| TypeORM version     | 0.3.2  | 

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Oatelaus** [comment]
@vdhpieter I came across this as I'm setting up TypeORM currently https://github.com/typeorm/typeorm/issues/8762#issuecomment-1072557441

I think this relates. Sorry if not.

**Comment by pleerock** [comment]
`cli` option was removed as it was answered in https://github.com/typeorm/typeorm/issues/8762#issuecomment-1072557441 . Now you need to specify path to exported data source definition in your code using `-d` option.

If you are willing to contribute - we need to update the CLI documentation.

**Comment by gavin-c-tcg** [comment]
how to custome migrationsDir ???

**Comment by pleerock** [comment]
Closing, see #8810 for more details.
