### ISSUE TITLE
New find select object api should support false values as expected

### ISSUE THREAD

**Issue by cduff** [typeorm/typeorm#8796]
### The Problem

As per https://typeorm.io/#/find-options/basic-options, `typeorm` now supports syntax like:

``` typescript
userRepository.find({
    select: {
        firstName: true,
        lastName: true,
    },
})
```

However, if you change one of the values to `false`, like:

``` typescript
userRepository.find({
    select: {
        firstName: true,
        lastName: false, // note false
    },
})
```

Then it makes no difference. `lastName` is still selected which does not seem intuitive.

However, if the value is specified as `undefined` then the field will not be selected:

``` typescript
userRepository.find({
    select: {
        firstName: true,
        lastName: undefined, // note undefined
    },
})
```

It would be great if `false` was handled intuitively so that simple boolean conditions can be specified for conditional selection.

Note that the `relations` option has a similar interface and it does handle `false` values as expected.

### The Solution

Could be simple as changing the following line:

https://github.com/typeorm/typeorm/blob/68a5c230776f6ad4e3ee7adea5ad4ecdce033c7e/src/query-builder/SelectQueryBuilder.ts#L3586

to:

```typescript
if (!select[key]) continue;
```

???

### Considered Alternatives

`undefined` can be specified instead of `false` but this complicates code for conditional selects.

The `select` implementation is also inconsistent with the `relations` implementation which does handle `false` values as expected.

### Additional Context

The new `select` and `relations` API was recently released in https://github.com/typeorm/typeorm/releases/tag/0.3.0.

### Relevant Database Driver(s)

n/a

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
I suggest to simply do it as:

```ts
 if (select[key] === undefined || select[key] === false) continue 
```

and add test for this change. Simply to contribute.
