### ISSUE TITLE
Performance issue with replacePropertyNames RegExp not fixed

### ISSUE THREAD

**Issue by djflex68** [typeorm/typeorm#8797]
## Issue Description

#4760 should have fixed severe performance issues due to a massively called RegExp at the beginning of the method. But the commit that fixed that was reverted, so that the bottleneck is still here, even with latest version.

### Expected Behavior

The fix should be available in current release.

### Actual Behavior

The fix is not in current release, nor in master branch :)

Also related to #3857

**Comment by AlexMesser** [comment]
#4760 was not reverted since #7269 was not merged. If you look at [QueryBuilder.ts](https://github.com/typeorm/typeorm/blob/22570f51f384c932e82b7b7807e9c68c179f16ba/src/query-builder/QueryBuilder.ts#L704) you can see that all changes are in place.
