### ISSUE TITLE
Export EntitySchema 

### ISSUE THREAD

**Issue by iz-iznogood** [typeorm/typeorm#880]
Hi, 

I work with dynamic schema a lot and would be very helpful to have the type available for code completion.
Is it possible to add it to index.js ?

Thanks

**Comment by pleerock** [comment]
what is `index.js` where it will be and what it will contain? And how its related to code completion and what code completion are you talking about? Its not in typescript as I understood, but where? in json or javascript?

**Comment by iz-iznogood** [comment]
Sorry, my bad. I meant index.ts

**Comment by pleerock** [comment]
ahh I thought completely different thing. Yes sure add it
