### ISSUE TITLE
Add new extensions in README.md

### ISSUE THREAD

**Issue by imjuni** [typeorm/typeorm#8808]
### What was unclear or otherwise insufficient?

I wan't add my extension [erdia](https://www.npmjs.com/package/erdia). erdia create er diagram and entity table docuemnt using by html or markdown format. er diagram using by [mermaid.js](https://mermaid-js.github.io) and html document using by [bulma](https://bulma.io/)

### Recommended Fix

```
* ER Diagram generator - [typeorm-uml](https://github.com/eugene-manuilov/typeorm-uml/)
* another ER Diagram generator - [erdia](https://www.npmjs.com/package/erdia) <-- add this line
```

### Are you willing to resolve this issue by submitting a Pull Request?
I can create pull-request

**Comment by pleerock** [comment]
you should upgrade your extension to support 0.3.0 version of TypeORM (where ormconfig support was deprecated and its going to completely removed in 0.4.0). 0.2.0 is no longer maintained.

**Comment by imjuni** [comment]
@pleerock Hi,

I did update [erdia](https://github.com/typeorm/typeorm/pull/8841) that can support dataSource 0.3.0 version. And I create [pull-request](https://github.com/typeorm/typeorm/pull/8841).

Thank you for your feedback!

**Comment by pleerock** [comment]
Merged! Thank you!

**Comment by imjuni** [comment]
@pleerock Thank you!
