### ISSUE TITLE
Can't run typeorm-ts-node-commonjs CLI script in docker node container

### ISSUE THREAD

**Issue by cduff** [typeorm/typeorm#8818]
### Expected Behavior

Should be able to run CLI commands from within docker containers.

### Actual Behavior

My CI/CD pipeline now fails to run the `typeorm migration:run` command with the following error:

``` shell
/usr/bin/env: 'node --require ts-node/register': No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

### Steps to Reproduce

Create a Dockerfile with the following content and try to build it:

``` dockerfile
FROM node:16.14.2
WORKDIR /usr/src/app
RUN echo "{\"dependencies\":{\"typeorm\":\"0.3.4\"},\"scripts\":{\"typeorm\":\"typeorm-ts-node-commonjs\"}}" > package.json
RUN npm i
RUN npm run typeorm
```

### My Environment

windows 10
node 16.14.2
docker desktop 4.6.1

### Additional Context

https://github.com/typeorm/typeorm/pull/8776

### Relevant Database Driver(s)

n/a

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
maybe you do not have `ts-node` installed?

**Comment by alt-art** [comment]
I have the same problem

**Comment by CarlSwann326** [comment]
Same on CI :(

**Comment by giladgd** [comment]
I've opened PR #8821 to fix this issue

**Comment by cduff** [comment]
> maybe you do not have `ts-node` installed?

@pleerock the result is the same if `ts-node` is installed. For example the Dockerfile below now includes `ts-node` and yields the same result. 

``` dockerfile
FROM node:16.14.2
WORKDIR /usr/src/app
RUN echo "{\"dependencies\":{\"ts-node\":\"10.7.0\",\"typeorm\":\"0.3.4\"},\"scripts\":{\"typeorm\":\"typeorm-ts-node-commonjs\"}}" > package.json
RUN npm i
RUN npm run typeorm
```

As mentioned by @giladgd in https://github.com/typeorm/typeorm/pull/8821 the issue is caused by incompatibility of shebang parameters across various linux distros.
