### ISSUE TITLE
[question] join-across-multiple-junction-tables

### ISSUE THREAD

**Issue by YuhangGe** [typeorm/typeorm#882]
Does typeorm support join across multiple junction tables? Just like:

https://stackoverflow.com/questions/25880539/join-across-multiple-junction-tables-with-sequelize

````js
User.findAll({
  include: [
    {
      model: Team, 
      include: [
        Folder
      ]  
    }
  ]
});
````

**Comment by pleerock** [comment]
Im not familiar with sequelize so much, but if you want three-level joins you can do following:

```ts
createQueryBuilder("user")
      .leftJoinAndSelect("user.photos", "photo")
      .leftJoinAndSelect("photo.tags", "tag");
```

It gives you users, their photos and tags of those photos.

**Comment by YuhangGe** [comment]
@pleerock yes, it works! thanks.
