### ISSUE TITLE
Support new UUID type in MariaDB 10.7

### ISSUE THREAD

**Issue by viktorandreevichmorozov** [typeorm/typeorm#8832]
## Feature Description
[https://mariadb.com/kb/en/uuid-data-type/](https://mariadb.com/kb/en/uuid-data-type/)
MariaDB starting with 10.7 supports UUID datatype.
INSERT/SELECT just like varchar, but stored in 128-bit wich is better for indexes.
Can you, please, provide ORM support for this type?
 
### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Thomas-1985** [comment]
+1

**Comment by viktorandreevichmorozov** [comment]
It would be nice to have support for IPv6 type too https://mariadb.com/kb/en/inet6/
