### ISSUE TITLE
Dayjs can't be used on types involved in find options

### ISSUE THREAD

**Issue by acuthbert** [typeorm/typeorm#8834]
### Expected Behavior

Using a where clause in a find would work for types with Dayjs typed properties. (This works in version 0.2)

### Actual Behavior

We get the error: 

```
(property) myProperty?: boolean | FindOperator<any> | FindOptionsWhere<MyEntity> | FindOptionsWhere<MyEntity>[] | EqualOperator<...>
Type 'Auction' is not assignable to type 'boolean | FindOperator<any> | FindOptionsWhere<MyEntity> | FindOptionsWhere<MyEntity>[] | EqualOperator<...>'.
  Type 'Auction' is not assignable to type 'FindOptionsWhere<MyEntity>'.
    Types of property 'startDate' are incompatible.
      Type 'Dayjs' is not assignable to type 'boolean | FindOperator<any> | FindOptionsWhere<Dayjs> | FindOptionsWhere<Dayjs>[] | EqualOperator<Dayjs>'.
        Type 'Dayjs' is not assignable to type 'FindOptionsWhere<Dayjs>'.
          Types of property 'clone' are incompatible.
            Type '() => Dayjs' is not assignable to type 'never'.ts(2322)
```

### Steps to Reproduce

1. Create an entity with Dayjs property
2. Add a transformer to convert dates to Dayjs

```typescript
this.repos.findMany({
    where: { myProperty: searchValue },
});
```

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Ubuntu 20        |
| Node.js version     | v14.16.0| 
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.3.4  | 

### Additional Context

![image](https://user-images.githubusercontent.com/408400/161095296-42b1223f-2a98-4522-9d12-641712a8e0d2.png)

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
Please provide more code to pinpoint an issue.

**Comment by namhtpyn** [comment]
![image](https://user-images.githubusercontent.com/16488178/161873207-bafa2a59-246a-4e31-b2e1-6070565937bd.png)
v0.3 you have to use Equal when comparing object
