### ISSUE TITLE
Bug in FindOperator

### ISSUE THREAD

**Issue by BackSlash-sys** [typeorm/typeorm#8848]
```typescript
    let query: FindManyOptions<Message> & { where: { id?: any; }; } = {
        order: { id: "DESC" },
        take: limit,
        where: { channel_id },
        relations: ["author" ,"attachments"]
    };

    if (after) query.where.id = MoreThan(after);
    else if (before) query.where.id = LessThan(before);

    const messages = await Message.find(query);
```

### My Error

  parameters: [
    '959761023978566408',
    FindOperator {
      _type: 'lessThan',
      _value: '960475467062779551',
      _useParameter: true,
      _multipleParameters: false,
      _getSql: undefined,
      _objectLiteralParameters: undefined
    }
  ],
  driverError: Error: Unknown column '_type' in 'where clause'

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16..14.0  | 
| Typescript version  | 4.5.5  | 
| TypeORM version     |  0.2.37  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by augustozanetti** [comment]
Hi! 
Did you try to set where object? 

```
if (after) 
  Object.assign(query.where, { id:  MoreThan(after)})
```

**Comment by pleerock** [comment]
it's  not clear purpose of ` & { where: { id?: any; }; }` and how it considered as typeorm bug.

**Comment by MichealPearce** [comment]
> it's not clear purpose of ` & { where: { id?: any; }; }` and how it considered as typeorm bug.

> driverError: Error: Unknown column '_type' in 'where clause'

Based on the error provided it looks like it's trying to query column names based on the `FindOperator` properties.

` & { where: { id?: any; }; }` is there to tell typescript the `query.where` property actually does exist. Otherwise TS would complain about `query.where` possibly being undefined at these lines.

```
if (after) query.where.id = MoreThan(after);
    else if (before) query.where.id = LessThan(before);
```

I don't believe they were saying it's apart of the issue.
