### ISSUE TITLE
Typescript swears when using `In` operator with enums

### ISSUE THREAD

**Issue by strayiker** [typeorm/typeorm#8856]
### Expected Behavior

`In` operator should work with enums.

### Actual Behavior

```typescript
async update<T extends QueryDeepPartialEntity<Entity>>(criteria: FindOptionsWhere<Entity>, entity: T);
```
```typescript
update(
  {
    id,
    status: In([Status.CREATED, Status.ACCEPTED]),
  },
  {
    status: Status.DECLINED,
  },
);
```

Statement above lead to next error

```

Type 'FindOperator<Status.CREATED | Status.ACCEPTED>' is not assignable to type 'Status | FindOperator<Status.CREATED> | FindOperator<Status.ACCEPTED> | ... 5 more ... | undefined'.
  Type 'FindOperator<Status.CREATED | Status.ACCEPTED>' is not assignable to type 'FindOperator<Status.CREATED>'.
    Type 'Status.CREATED | Status.ACCEPTED' is not assignable to type 'Status.CREATED'.
      Type 'Status.ACCEPTED' is not assignable to type 'Status.CREATED'.
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     MacOS     |
| Node.js version     | 14.17.3  | 
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.3.5  | 

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by HatemSat** [comment]
Seems like the same issue when using Equal operator with an enum typed parameter (used to work on v0.2.45)
```js
function findUser(employeeType: EmployeeType) {
  repo.findOne({ where: { employeeType: Equal(employeeType) } });
}
```
```
Type 'EqualOperator<EmployeeType>' is not assignable to type 'EmployeeType | FindOperator<EmployeeType.MANAGER> | FindOperator<EmployeeType.DEVELOPER>'.
  Type 'EqualOperator<EmployeeType>' is not assignable to type 'FindOperator<EmployeeType.DEVELOPER>'.
    Types of property 'value' are incompatible.
      Type 'EmployeeType' is not assignable to type 'EmployeeType.DEVELOPER'.
        Type 'EmployeeType.MANAGER' is not assignable to type 'EmployeeType.DEVELOPER'.ts(2322)
```

**Comment by strayiker** [comment]
Working as expected in [0.3.12](https://github.com/typeorm/typeorm/releases/tag/0.3.12)
