### ISSUE TITLE
migration:generate not including all columns for multi-column @Index()

### ISSUE THREAD

**Issue by mrsimb** [typeorm/typeorm#8859]
## Issue Description
migration:generate produces invalid code for multi-column `@Index`

### Expected Behavior

migration:generate generates following code:
```typescript
await queryRunner.query(`CREATE UNIQUE INDEX "unique_name_per_one_Tracker" ON "tracker_data" ("name", "trackerId") WHERE "deletedAt" IS NULL`);
```
This creates multi-column index on "name", "trackerId" columns

### Actual Behavior

migration:generate generates following code:
```typescript
await queryRunner.query(`CREATE UNIQUE INDEX "unique_name_per_one_Tracker" ON "tracker_data" ("name") WHERE "deletedAt" IS NULL`);
```
This creates index on "name" column - which is not what i wanted

### Steps to Reproduce

1. Define entities from example below
2. Run typeorm migration:generate

Example entities:
```typescript
@Entity()
export class Object {
  @OneToMany(() => ObjectEntry, (entry) => entry.object)
  entries!: ObjectEntry[]
}

@Entity()
export class ObjectEntry {
  @DeleteDateColumn({ type: 'timestamptz' })
  deletedAt?: Date;

  @Column()
  @Index('unique_key_per_Object', ['key', 'objectId'], { // notice there are 2 columns: key, objectId
    unique: true,
    where: '"deletedAt" IS NULL',
  })
  key!: string;

  @Column()
  value!: string;

  @ManyToOne(() => Object, (object) => object.entries)
  object!: Object;
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     MacOS 11.6     |
| Node.js version     | 16.14.2  | 
| Typescript version  | 4.4.4  | 
| TypeORM version     | 0.2.41  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment]
You should put `@Index()` definition on `@Entity()` level. See [the docs](https://typeorm.io/indices#indices-with-multiple-columns).

**Comment by Ginden** [comment]
@AlexMesser Though, I think it's possible to forbid this kind of bug by typing `@Index` decorator.
