### ISSUE TITLE
Creating a new migration issue

### ISSUE THREAD

**Issue by adetorodev** [typeorm/typeorm#8860]
## Documentation Issue
After creating my entities Post. Just only one entity which is the Post.ts. I want to make migration and I got an error that does not seem clear to me. I follow the document in doing this. No migration file was created as specified by the doc.

This is my config file

```
import { DataSource } from "typeorm";
import { Post } from "./entities/Post";

export const pgDataSource = new DataSource({
    type: "postgres",
    host: "localhost",
    port: 5432,
    username: "postgres",
    password: "ezeka",
    database: "postMikro",
    synchronize: true,
    entities: [Post],
    migrations: [/*...*/],
    migrationsTableName: "custom_migration_table",
  });
```
And the index file which is my global app

```
import "reflect-metadata";
import { pgDataSource } from "./pgconnection";

const main = async () => {
  const DataPg = pgDataSource;

  DataPg.initialize();
};

main();
```

### What was unclear or otherwise insufficient?
After running the migration using the command
`typeorm migration:create -n PostRefactoring` 
I got this error:
`Not enough non-option arguments: got 0, need at least 1`
I also try using this command as specified in migration CLI doc
`npm run typeorm migration:run`
I got this error:
`Missing required argument: dataSource`
Lastly tried this:
`npm run typeorm migration:generate -- -n postmigration`
With this error:
`Not enough non-option arguments: got 0, need at least 1`

My question is; Is the doc unclear? Or I am missing something but I don't really think I am because I did all things according to the doc.

### Additional Context
I did this with the sample project, sample32, still no migration file was created. The amazing thing was that `npm start` connected the app to the database. The same thing with sample1

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by trival** [comment]
i had the same issue today. I think that since the 0.3 versions the `-n` parameter is gone and instead you just append the path to the migration after the command, like so: 

```
npm run typeorm migration:generate -d <path/to/datasource> path/to/migrations/<migration-name>
```

or with dummy example data

```
npm run typeorm migration:generate -d src/data-source.js src/migrations/ChangeUserNameField
```

the docs unfortunately still mix up 0.2 and 0.3 behavior in many places. Anyways, I am still figuring this out myself, far from optimal, but this is may be a hint in the right direction...

**Comment by cvrchinmay** [comment]
I am also facing the same issue.

**Comment by hardboiled** [comment]
My migration gets generated, but they don't show up as pending, and running them is a no-op.

Is there any step to get the app to detect the migrations? I don't remember having issues when I last used this a year and a half ago, but this is a new setup.

```bash
$ yarn typeorm migration:generate src/db/migrations/AddFemaDefinition
yarn run v1.22.18
> typeorm-ts-node-commonjs -d ./src/data-source.ts migration:generate src/db/migrations/AddFemaDefinition
Migration ../src/db/migrations/AddFemaDefinition.ts has been generated successfully.
✨  Done in 2.64s.
$ yarn typeorm migration:show
yarn run v1.22.18
> typeorm-ts-node-commonjs -d ./src/data-source.ts migration:show
✨  Done in 2.61s.
$ yarn typeorm migration:run
yarn run v1.22.18
> typeorm-ts-node-commonjs -d ./src/data-source.ts migration:run
query: SELECT VERSION() AS `version`
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'app' AND `TABLE_NAME` = 'migrations'
query: SELECT * FROM `app`.`migrations` `migrations` ORDER BY `id` DESC
No migrations are pending
✨  Done in 2.80s.
```

**Comment by hardboiled** [comment]
FYI, I got the migration to run. I think it might have been bad path selectors, but hard to tell.

Here are my configs in case anyone is interested.

```ts
// src/data-source.ts
import 'reflect-metadata'
import { DataSource } from 'typeorm'

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(`${process.env.DB_PORT || 3306}`),
  username: process.env.DB_USER || 'root',
  password: process.env.DB_PASSWORD || 'default',
  database: process.env.DB_NAME || 'test',
  synchronize: true,
  logging: false,
  entities: ['src/**/*.entity.ts'],
  migrations: ['src/db/migrations/*.ts'],
  subscribers: [],
})
```

`package.json`
```json
{
  "devDependencies": {
    "@tsconfig/node16": "^1.0.2",
    "@types/express": "^4.17.13",
    "@types/node": "^17.0.23",
    "@typescript-eslint/eslint-plugin": "^5.18.0",
    "@typescript-eslint/parser": "^5.18.0",
    "eslint": "^8.13.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-jest": "^26.1.4",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.5.1",
    "prettier": "^2.6.2",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.3"
  },
  "type":"commonjs",
  "dependencies": {
    "express": "^4.17.3",
    "mysql2": "^2.3.3",
    "reflect-metadata": "^0.1.13",
    "typeorm": "^0.3.6"
  },
  "license": "MIT",
  "scripts": {
    "lint": "eslint --cache \"src/**/*.ts\"",
    "lint:fix": "eslint --cache --fix \"src/**/*.ts\"",
    "start": "ts-node src/index.ts",
    "typeorm": "typeorm-ts-node-commonjs -d ./src/data-source.ts"
  }
}
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es6",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "outDir": "dist",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "include": [
    "src"
  ]
}
```

**Comment by muriloux** [comment]
> i had the same issue today. I think that since the 0.3 versions the `-n` parameter is gone and instead you just append the path to the migration after the command, like so:
> 
> ```
> npm run typeorm migration:generate -d <path/to/datasource> path/to/migrations/<migration-name>
> ```
> 
> or with dummy example data
> 
> ```
> npm run typeorm migration:generate -d src/data-source.js src/migrations/ChangeUserNameField
> ```
> 
> the docs unfortunately still mix up 0.2 and 0.3 behavior in many places. Anyways, I am still figuring this out myself, far from optimal, but this is may be a hint in the right direction...

Worked. This will do for now, while no official fixes. Thanks.

**Comment by juniorduff** [comment]
I fix this problem this way

![image](https://user-images.githubusercontent.com/23487781/164733466-f8099116-4777-475a-a3ca-5789cb48166c.png)
First we need to remove the option -d dist/datasource.js  in your script 

![image](https://user-images.githubusercontent.com/23487781/164733623-0c3b93e7-8fb7-46d3-9a17-e01eff823e3d.png)

then  you need to  do the command with entire path
![image](https://user-images.githubusercontent.com/23487781/164733784-67d696a1-2de8-49e5-877b-557be023a0d6.png)


![image](https://user-images.githubusercontent.com/23487781/164733830-594f40ea-1dcd-43ca-b412-e5523951e43f.png)

**Comment by bombillazo** [comment]
Docs should be updated ASAP to show the `-n` flag is no longer valid and the path is required by the command. The CLI specifies this but _all_ available documentation on TypeORM I've found online still references the -n flag which is very confusing for first-timers figuring out migrations.

**Comment by hidemydreams** [comment]
When I am running this: `typeorm migration:generate path/to/migrations/PostRefactoring -d path/to/datasource.ts`

I am getting this: 
![image](https://user-images.githubusercontent.com/48909485/170670481-e7a51c54-7e47-4205-9df5-44177ded3d00.png)

Maybe someone knows how to get around this? Thanks!

**Comment by myknbani** [comment]
@hidemydreams you need to run it via `ts-node`

```json
{
  "typeorm": "ts-node -P tsconfig.json ./node_modules/typeorm/cli.js",
  "seed": "ts-node ./database/seed.ts",
  "migrate:gen": "pnpm typeorm migration:generate -d datasource.ts -p",
}
```

Also the output wil say `Migration /some/path/backend/database/migrations/AddTable.ts has been generated successfully.`, but the filename actually has a timestamp 😅.  The `migrationsDir` option needs to be resurrected. 😭

**Comment by rakestto** [comment]
You can solve it putting `$npm_config_name` at the end of the migrations filepath like this:

````
"db:generate:migrations": "npm run build:dev && npm run typeorm migration:generate ./src/infra/database/migrations/$npm_config_name",
````

If you write at the end of the filepath $npm_config_<some-parameter-name>, then you can run the script like this:

`npm run db:generate:migrations --some-parameter-name=<the-name>`


In my case npm run db:generate:migrations --name=migrationName

**Comment by evilhalba** [comment]
Hi guys, i have just added this into my package.json scripts,
 ` "typeorm": "ts-node-dev -r tsconfig-paths/register  ./node_modules/typeorm/cli.js --dataSource ./src/shared/infra/typeorm/data-source.ts",`

and when i run on CMD the command `npm run typeorm migration:create "src/shared/infra/typeorm/migrations/AddUserPasswordField"`(that is my migrations path)

i know that isn't the best way but worked!

And to run the migrations i just put to run my application with this code on index.ts `AppDataSource.initialize();`

**Comment by SemajDraw** [comment]
Why was the -n flag removed in the first place? This seems like a regression and leaves the command to generate a migration open to interpretation and unnecessarily verbose. It seems to me it would be far more logical to keep the -n flag and configure the dataSource and migrations directory in the TypeORM config, while allowing their locations to be manually overridden if necessary on a per command basis.

**Comment by LittleKunzi** [comment]
i run this command，it worked： `yarn typeorm migration:create ./src/migration/CoffeeRefactor`

**Comment by razr001** [comment]
package.json

**Comment by razr001** [comment]
My configs
### package.json
```
"scripts": {
   "typeorm": "typeorm-ts-node-commonjs migration:generate ./migrations -d ./data-source.ts"
}
```
### data-source.ts
```
import { DataSource } from 'typeorm'

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: "127.0.0.1",
  port: 3306,
  username: 'root',
  password: 'pwd',
  database: 'test',
  synchronize: false,
  logging: false,
  entities: ['src/entity/*.ts'],
  subscribers: [],
})
```
```
npm run typeorm
```

**Comment by poojachakrawarti** [comment]
> I fix this problem this way
> 
> ![image](https://user-images.githubusercontent.com/23487781/164733466-f8099116-4777-475a-a3ca-5789cb48166c.png) First we need to remove the option -d dist/datasource.js in your script
> 
> ![image](https://user-images.githubusercontent.com/23487781/164733623-0c3b93e7-8fb7-46d3-9a17-e01eff823e3d.png)
> 
> then you need to do the command with entire path ![image](https://user-images.githubusercontent.com/23487781/164733784-67d696a1-2de8-49e5-877b-557be023a0d6.png)
> 
> ![image](https://user-images.githubusercontent.com/23487781/164733830-594f40ea-1dcd-43ca-b412-e5523951e43f.png)

what is datasource.js

**Comment by bidossessi** [comment]
This is how I got it to work locally:

```js
# datasource.ts
entities =
  process.env.NODE_ENV === 'dev'
    ? ['src/persistence/models/*.model.ts']
    : ['dist/persistence/models/*.model.js']

const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST,
  port: parseInt(process.env.DB_PORT!, 10),
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  logging: process.env.DB_LOGGING === 'true',
  synchronize: false,
  migrationsRun: true,
  entities,
  migrations,
  subscribers,
})
```

```json
# package.json
  "scripts": {
    "migrate:generate": "NODE_ENV=dev DB_LOGGING=true typeorm-ts-node-commonjs -d ./src/persistence/datasource.ts migration:generate",
    "migrate:create": "NODE_ENV=dev DB_LOGGIN=true typeorm-ts-node-commonjs migration:create",
    "migrate:up": "NODE_ENV=dev DB_LOGGIN=true typeorm-ts-node-commonjs migration:up",
    "migrate:down": "NODE_ENV=dev DB_LOGGIN=true typeorm-ts-node-commonjs migration:down",
  },
```

Then I do 
```sh
$ yarn migrate:create src/persistence/migrations/someMig
Migration /path/to/src/persistence/migrations/1677489064917-someMig.ts has been generated successfully.
```

**Comment by adetorodev** [comment]
A pull request has been made that address this issue. The documentation has been updated.

**Comment by Filip1986** [comment]
For those trying this in windows:
`"migration:create:unix": "typeorm migration:create ./src/migrations/$npm_config_name"`
`"migration:create:win": "typeorm migration:create ./src/migrations/%npm_config_name%"`
Run
`npm run migration:create:win --name=MyMigration`
