### ISSUE TITLE
Add support for DuckDb?

### ISSUE THREAD

**Issue by chriszrc** [typeorm/typeorm#8861]
## Feature Description
Add support for duckdb, which seems to be pretty close to sqlite - https://duckdb.org/docs/api/nodejs/overview

### The Problem
We need an embeddable db for our projects, but Sqlite has a frustrating lack of certain features (full joins, etc), and DuckDb seems to be the perfect replacement

### The Solution
I'm guessing that this should be fairly easy as the api is similar to the sqlite api?

### Considered Alternatives
n/a

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | yes            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?
Maybe? I just need to know where to start...

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.

**Comment by iku000888** [comment]
with AI coding might be interesting to vibe code this and see where it goes

```
⏺ Now I'll create a comprehensive plan for implementing DuckDB support in TypeORM.
  ⎿  ☐ Research @duckdb/node-api package structure and connection patterns
     ☐ Study PostgreSQL and SQLite drivers for implementation patterns
     ☐ Create DuckDBConnectionOptions interface with database path and configuration options
     ☐ Create DuckDBDriver class implementing Driver interface with connection management
     ☐ Create DuckDBQueryRunner for SQL execution and transaction handling
     ☐ Map DuckDB data types to TypeORM column types including advanced analytics types
     ☐ Add 'duckdb' to DatabaseType enum and update DataSourceOptions
     ☐ Add DuckDB case to DriverFactory for driver instantiation
     ☐ Add DuckDB-specific schema operations and SQL generation
     ☐ Create comprehensive test suite for DuckDB driver functionality
     ☐ Implement support for DuckDB's advanced features (arrays, structs, spatial types)
     ☐ Add DuckDB driver documentation and usage examples

⏺ DuckDB Support Implementation Plan

  Overview

  Add a new database driver for DuckDB to TypeORM, leveraging the @duckdb/node-api package. DuckDB is an embeddable analytical database that offers advanced SQL features beyond SQLite.

  Implementation Strategy

  Phase 1: Core Infrastructure (High Priority)

  1. Research DuckDB API - Study @duckdb/node-api connection patterns and query execution
  2. Study Existing Drivers - Examine PostgreSQL (for SQL compliance) and SQLite (for embedded patterns) drivers
  3. Connection Options - Define DuckDBConnectionOptions interface for database path and configuration
  4. Driver Class - Implement DuckDBDriver with connection management and type system
  5. Query Runner - Create DuckDBQueryRunner for SQL execution and transactions

  Phase 2: Integration (Medium Priority)

  6. Data Type Mapping - Map DuckDB types (including arrays, structs, JSON) to TypeORM columns
  7. Core Type Updates - Add "duckdb" to DatabaseType enum and DataSourceOptions
  8. Driver Factory - Update DriverFactory to instantiate DuckDB drivers
  9. Schema Operations - Implement DDL operations and SQL dialect handling
  10. Testing - Create comprehensive test suite

  Phase 3: Advanced Features (Low Priority)

  10. Advanced Analytics - Support for DuckDB's complex types and spatial data
  11. Documentation - Usage examples and migration guides

  Technical Approach

  Architecture Pattern: Follow PostgreSQL driver structure (SQL standard compliance) with SQLite-style connection handling (file-based database).

  Key Differentiators:
  - Parameter binding: $1, $2 style (PostgreSQL-like)
  - Advanced data types: ARRAY, STRUCT, MAP, JSON
  - Full SQL compliance including window functions and CTEs
  - Spatial data support (PostGIS compatibility)

  File Structure:
  src/driver/duckdb/
  ├── DuckDBConnectionOptions.ts
  ├── DuckDBDriver.ts
  └── DuckDBQueryRunner.ts

  This plan addresses the GitHub issue's core request while providing a robust foundation for DuckDB's advanced analytics capabilities.

```
