### ISSUE TITLE
Updated relations in subscriber for m2m relation is always empty

### ISSUE THREAD

**Issue by icewind** [typeorm/typeorm#888]
Hi.
I have a simple subscriber like this
```TypeScript
@EventSubscriber()
export class GeneralSubscriber implements EntitySubscriberInterface<any> {
    public async afterUpdate(event: UpdateEvent<any>) {
        console.log('Updated', event.entity, event.updatedColumns, event.updatedRelations);
    }
}
```
And it works fine for column update or one2one relation but not getting called at all for m2m relations.

```TypeScript
const model = await repository.findOneById(1);
model.name = 'New name';
await repository.persist(model); // This works. Subscriber method gets called with proper data

const client = await clientRepository.findOneById(2);
model.clients.push(client);
await repository.persist(model); // Subscriber method not gets called at all
```
Second example saving all fine. But subscriber is simply ignoring it. Even if I mix update for simple field and m2m relation, `event.updatedRelations` is always empty

**Comment by icewind** [comment]
Found in code of `Subject.ts`
```TypeScript
 /**
    * Difference columns of the owning one-to-one and many-to-one columns.
    */
    protected computeDiffRelationalColumns(/*todo: updatesByRelations: UpdateByRelationOperation[], */): void {
```
That is really sad... Is there any way to get all updated relations? And what was the reason to do it like this?

**Comment by pleerock** [comment]
because `beforeUpdate`/`afterUpdate` are called when actual SQL `UPDATE` query is executed. In this case your entity is not updated at all, it just inserts data into separate table.

I'm planning to rethink and write subscribers functionality in the future, and maybe I'll change this behaviour as well.

**Comment by icewind** [comment]
What does it means `your entity is not updated at all`? It work as expected and entity comes updated in the listener if I'm updating it with some plain value.

```TypeScript
const client = await clientRepository.findOneById(2);
model.title = 'Some new title';
model.clients.push(client);
await repository.persist(model);
```

```Typescript
public async afterUpdate(event: UpdateEvent<any>) {
    console.log('Updated', event.entity, event.updatedColumns, event.updatedRelations);
}
```
`event.entity` is correct with all my attached clients. But even if entity itself is actual, `updatedRelations` is empty.

**Comment by pleerock** [comment]
> your entity is not updated at all

not updated at all in the database. many-to-many table is touched, not your entity table. As I told you update triggers only when ORM executes `UPDATE` sql query on your entity's table.

**Comment by jatinkatyal13** [comment]
@pleerock is there any update on the implementation? I'm stuck on a similar scenario, if not is there any other way you'll recommend?

**Comment by Tajcore** [comment]
Has this been implemented as yet?

**Comment by Hareloo** [comment]
Anything new on this?
I looked into the code a bit and this seems to have been implemented somewhat using RelationIds(?) but I'm not sure if I understand it and I couldn't get it to work properly no matter what I did...

**Comment by vanpho93** [comment]
This is my workaround. Cannot find anything better. If you pass enough to `data`, you can get it back`

```
        return this.connection
            .getRepository(Entity)
            .save(updatedEntity, { data: { note: 'pass anything you want' } })
```

```
    public listenTo() {
        return 'use_your_joint_table_name';
    }

    public afterInsert(event: InsertEvent<T>) {
        // eslint-disable-next-line no-console
        console.log('afterInsert', event.queryRunner.data);
    }

    public afterRemove(event: RemoveEvent<T>) {
        // eslint-disable-next-line no-console
        console.log('afterRemove', event.queryRunner.data);
    }
```

**Comment by uranderu** [comment]
> This is my workaround. Cannot find anything better. If you pass enough to `data`, you can get process on hooks
> 
> ```ts
>         return this.connection
>             .getRepository(Entity)
>             .save(updatedEntity, { data: { note: 'pass anything you want' } })
> ```
> 
> ```ts
>     public listenTo() {
>         return 'use_your_joint_table_name';
>     }
> 
>     public afterInsert(event: InsertEvent<T>) {
>         // eslint-disable-next-line no-console
>         console.log('afterInsert', event.queryRunner.data);
>     }
> 
>     public afterRemove(event: RemoveEvent<T>) {
>         // eslint-disable-next-line no-console
>         console.log('afterRemove', event.queryRunner.data);
>     }
> ```

Hi, I am trying this and although this works great for "afterRemove" my "event.entity" is empty in "afterInsert". I am using the .save method but I can't get it to show something. Do you have the same issue?

**Comment by uranderu** [comment]
> @uranderu event.entity is empty, that's expected, I meant you should add that into `data` so you can handle that.
> 
> ```
> public afterInsert(event: InsertEvent<T>) {
>         // eslint-disable-next-line no-console
>         console.log('afterInsert', event.queryRunner.data);
>     }
> ```
> 
> FYI, I don't use this after all.

Hi, thanks for your answer. But how is this expected? I see in the query logs that it inserts into the join table but I can't access the variables used. While with the remove I have those available through the "event.entityId" object.
