### ISSUE TITLE
CannotExecuteNotConnectedError when running migration on Postgres

### ISSUE THREAD

**Issue by assapir** [typeorm/typeorm#8885]
## Issue Description

When trying to run a migration on Postgres DB, the migrations fail to run with `CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/home/assaf/Code/private/f3tw/src/data-source/DataSource.ts:284:19)
    at Object.handler (/home/assaf/Code/private/f3tw/src/commands/MigrationRunCommand.ts:73:46)`

### Expected Behavior

All migrations should run as expected.

### Actual Behavior

No migrations are running, and an error is thrown:
```shell
> typeorm-ts-node-esm -d src/data-source.ts "migration:run"

query: SELECT * FROM current_schema()
typeorm-ts-node-esm migration:run

Runs all pending migrations.

Options:
  -h, --help         Show help                                         [boolean]
  -d, --dataSource   Path to the file where your DataSource instance is defined.
                                                                      [required]
  -t, --transaction  Indicates if transaction should be used or not for
                     migration run. Enabled by default.     [default: "default"]
  -v, --version      Show version number                               [boolean]

CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/home/assaf/Code/private/f3tw/src/data-source/DataSource.ts:284:19)
    at Object.handler (/home/assaf/Code/private/f3tw/src/commands/MigrationRunCommand.ts:73:46)
```

### Steps to Reproduce

1. Create a migration
2. try to run it with `npm run typeorm migration:run` 

my `datasource`: 
```typescript
import "reflect-metadata";
import { DataSource } from "typeorm";

export const TestAppDataSource = new DataSource({
  type: "postgres",
  host: "localhost",
  port: 5432,
  username: "postgres",
  password: "test",
  database: "postgres",
  logging: process.env.NODE_ENV !== "production",
  entities: ["src/entity/*.{js,ts}"],
  migrations: ["src/migration/*.{ts, ts}"],
});
```
From looking at the code in `src/commands/MigrationRunCommand.ts` it seems like it does call
[await dataSource.initialize()](https://github.com/typeorm/typeorm/blob/1197d1d61cb664b52ab38d26f7473fd5f1476ba5/src/commands/MigrationRunCommand.ts#L44-L45) so I have no idea where that problem is coming from.

### My Environment

~Might be related to the fact that I am using npm workspace and running inside one of the projects?~
It does work when using `typeorm-ts-node-commonjs` but not `typeorm-ts-node-esm`

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Arch linux       |
| Node.js version     | 17.8.0  | 
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.3.5  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by walesonn** [comment]
Try change this "migrations: ["src/migration/*.{ts, ts}"]" for this "migrations: [<nameYoursMigrationhere>]" and execute what happen's ? I'm sorry my English is horrorible

**Comment by igortrinidad** [comment]
Same issue here @assapir , if you find a solution please share with us 🙏

**Comment by igortrinidad** [comment]
I didn't found a solution @assapir but i could finally run the migrations.

Isn't the best solution ever but at least we could go to sleep without this exception on mind lol 😆 

`
import dbCreateConnection from "./dbCreateConnection"
import AppDataSource from "./AppDataSource"

export default ( async () => {
  await dbCreateConnection()
  await AppDataSource.runMigrations()
})()
`

**Comment by girishsuri15** [comment]
++ Same Issue

**Comment by memo-567** [comment]
Same here with YunoHost Misskey:

```
typeorm migration:run

Runs all pending migrations.
 
Options:
   -h, --help         Show help                                         [boolean]
   -d, --dataSource   Path to the file where your DataSource instance is defined.
                                                                       [required]
   -t, --transaction  Indicates if transaction should be used or not for
                      migration run. Enabled by default.     [default: "default"]
   -v, --version      Show version number                               [boolean]
 
 CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
     at DataSource.destroy (/var/www/misskey/packages/backend/node_modules/typeorm/data-source/DataSource.js:169:19)
     at Object.handler (/var/www/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:67:34)
 error Command failed with exit code 1.
```

**Comment by smio102** [comment]
same issue with misskey migrations.

**Comment by tdnghia98** [comment]
I have the same problem. However creating new table using queryRunner runs fine

```typescript 
public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "city" ("id" SERIAL NOT NULL, "postCode" character varying NOT NULL, "communeCode" character varying NOT NULL, "communeLabel" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "city"`);
    }
```

Only when using Enitity objects I have this issue

```typescript
public async up(queryRunner: QueryRunner): Promise<void> {
    const manager = AppDataSource.manager;

    const repository = manager.getRepository(City);
    await repository.save(
      allCities['default'].map((rawCity) => {
        const city = new City();
        city.postCode = rawCity.codePostal;
        city.communeCode = rawCity.codeCommune;
        city.communeLabel = rawCity.nomCommune;
        city.name = rawCity.libelleAcheminement;
        return city;
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const manager = AppDataSource.manager;

    const repository = manager.getRepository(City);
    repository.clear();
  }
```

**Comment by kareemarafa** [comment]
Same issue

**Comment by nicholasoxford** [comment]
Same issue

**Comment by aftabaig** [comment]
I had to revert back `typeorm` to previous version to make it work

**Comment by lucasgama335** [comment]
Same issue

**Comment by nicholasoxford** [comment]
@aftabaig are you saying typeorm 0.2.*?

**Comment by aftabaig** [comment]
> @aftabaig are you saying typeorm 0.2.*?

Yes `^0.2.45` to be exact

**Comment by lucasgama335** [comment]
> ## Issue Description
> When trying to run a migration on Postgres DB, the migrations fail to run with `CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established. at DataSource.destroy (/home/assaf/Code/private/f3tw/src/data-source/DataSource.ts:284:19) at Object.handler (/home/assaf/Code/private/f3tw/src/commands/MigrationRunCommand.ts:73:46)`
> 
> ### Expected Behavior
> All migrations should run as expected.
> 
> ### Actual Behavior
> No migrations are running, and an error is thrown:
> 
> ```shell
> > typeorm-ts-node-esm -d src/data-source.ts "migration:run"
> 
> query: SELECT * FROM current_schema()
> typeorm-ts-node-esm migration:run
> 
> Runs all pending migrations.
> 
> Options:
>   -h, --help         Show help                                         [boolean]
>   -d, --dataSource   Path to the file where your DataSource instance is defined.
>                                                                       [required]
>   -t, --transaction  Indicates if transaction should be used or not for
>                      migration run. Enabled by default.     [default: "default"]
>   -v, --version      Show version number                               [boolean]
> 
> CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
>     at DataSource.destroy (/home/assaf/Code/private/f3tw/src/data-source/DataSource.ts:284:19)
>     at Object.handler (/home/assaf/Code/private/f3tw/src/commands/MigrationRunCommand.ts:73:46)
> ```
> 
> ### Steps to Reproduce
> 1. Create a migration
> 2. try to run it with `npm run typeorm migration:run`
> 
> my `datasource`:
> 
> ```ts
> import "reflect-metadata";
> import { DataSource } from "typeorm";
> 
> export const TestAppDataSource = new DataSource({
>   type: "postgres",
>   host: "localhost",
>   port: 5432,
>   username: "postgres",
>   password: "test",
>   database: "postgres",
>   logging: process.env.NODE_ENV !== "production",
>   entities: ["src/entity/*.{js,ts}"],
>   migrations: ["src/migration/*.{ts, ts}"],
> });
> ```
> 
> From looking at the code in `src/commands/MigrationRunCommand.ts` it seems like it does call [await dataSource.initialize()](https://github.com/typeorm/typeorm/blob/1197d1d61cb664b52ab38d26f7473fd5f1476ba5/src/commands/MigrationRunCommand.ts#L44-L45) so I have no idea where that problem is coming from.
> 
> ### My Environment
> ~Might be related to the fact that I am using npm workspace and running inside one of the projects?~ It does work when using `typeorm-ts-node-commonjs` but not `typeorm-ts-node-esm`
> 
> Dependency	Version
> Operating System	Arch linux
> Node.js version	17.8.0
> Typescript version	4.6.3
> TypeORM version	0.3.5
> ### Additional Context
> ### Relevant Database Driver(s)
> DB Type	Reproducible
> `aurora-mysql`	no
> `aurora-postgres`	no
> `better-sqlite3`	no
> `cockroachdb`	no
> `cordova`	no
> `expo`	no
> `mongodb`	no
> `mysql`	no
> `nativescript`	no
> `oracle`	no
> `postgres`	yes
> `react-native`	no
> `sap`	no
> `sqlite`	no
> `sqlite-abstract`	no
> `sqljs`	no
> `sqlserver`	no
> ### Are you willing to resolve this issue by submitting a Pull Request?
> * ✖️ Yes, I have the time, and I know how to start.
> * ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
> * ✖️ No, I don’t have the time, but I can support (using donations) development.
> * ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

I found the problem. import dotenv into your file containing dataSource

> ```ts
> import "reflect-metadata";
> import "dotenv/config";
> import { DataSource } from "typeorm";
> 
> export const TestAppDataSource = new DataSource({
>   type: "postgres",
>   host: "localhost",
>   port: 5432,
>   username: "postgres",
>   password: "test",
>   database: "postgres",
>   logging: process.env.NODE_ENV !== "production",
>   entities: ["src/entity/*.{js,ts}"],
>   migrations: ["src/migration/*.{ts, ts}"],
> });
> ```

**Comment by Johann150** [comment]
I found today that this error may be because of another completely unrelated error. I added a `console.log` in `node_modules/typeorm/commands/MigrationRunCommand.js` suggested by lucasgama335, but instead I logged the error in the catch statement and found that I had accidentally used a `require` in an ecmascript module.

**Comment by acSpock** [comment]
I recommend everyone first attempt what lucasgama335 did and add a `console.log(err)` in the catch block of the `node_modules/typeorm/commands/MigrationRunCommand.js` on line 65. For me, my issue was I was technically still connected in datagrip to an external DB through an ssh tunnel that was bound to the same local port as my typeorm connection and I was getting an auth error that wasn't surfacing.

```
error: password authentication failed for user "my-local-db"
```

**Comment by christian-1609** [comment]
@acSpock; Hi, How do you manage to connect using ssh tunnel? could you help me with information?

**Comment by asdfisdffdg** [comment]
i had the same issue setting up misskey. i resolved it by upgrading from postgresql 10 to 13.

**Comment by BlueWhaleKo** [comment]
After doing some research, I figured out that the error message comes from the [line](https://github.com/typeorm/typeorm/blob/1197d1d61cb664b52ab38d26f7473fd5f1476ba5/src/commands/MigrationRunCommand.ts#L34) which loads exported DataSource instance from given path. 


```typescript
  async handler(args: yargs.Arguments) {
      let dataSource: DataSource | undefined = undefined
      try {
          dataSource = await CommandUtils.loadDataSource(
              path.resolve(process.cwd(), args.dataSource as string),
          )
```

In my case, the problem was that the target database was not initialized.
```
error: database "development" does not exist
    at Parser.parseErrorMessage (/Users/doghyungko/Documents/git-projects/coxwave/showcase/.yarn/cache/pg-protocol-npm-1.5.0-390f8d9ed8-b839d12caf.zip/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/doghyungko/Documents/git-projects/coxwave/showcase/.yarn/cache/pg-protocol-npm-1.5.0-390f8d9ed8-b839d12caf.zip/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/doghyungko/Documents/git-projects/coxwave/showcase/.yarn/cache/pg-protocol-npm-1.5.0-390f8d9ed8-b839d12caf.zip/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/doghyungko/Documents/git-projects/coxwave/showcase/.yarn/cache/pg-protocol-npm-1.5.0-390f8d9ed8-b839d12caf.zip/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
```
---

@assapir 
You're absolutely right. The command fails before it reaches the initialize function.

> From looking at the code in src/commands/MigrationRunCommand.ts it seems like it does call
[await dataSource.initialize()](https://github.com/typeorm/typeorm/blob/1197d1d61cb664b52ab38d26f7473fd5f1476ba5/src/commands/MigrationRunCommand.ts#L44-L45) so I have no idea where that problem is coming from.

You'll be able to figure out the error message if you manually add some error printing commands to the catch scope.

**Comment by shohelrrrana** [comment]
i had the same issue

**Comment by bregoh** [comment]
Guys, if you ever face migration issues. Latest TypeOrm version failed to emphasize the current changes on the documentation.

`<npx | yarn> <typeorm-ts-node-commonjs | typeorm-ts-node-esm> <migration command> -d <path_to_your_datasource>`

for example:

`yarn typeorm-ts-node-esm migration:generate <migration_path> -d src/data-source.ts`

or 

`npx typeorm-ts-node-esm migration:run -d src/data-source.ts`


for reference: https://typeorm.io/migrations#running-and-reverting-migrations 
<img width="789" alt="Screenshot 2022-05-18 at 12 44 15" src="https://user-images.githubusercontent.com/48225427/168979699-f792ce6e-b509-41ab-b7ce-46bce2f4d02b.png">
<img width="423" alt="Screenshot 2022-05-18 at 12 44 42" src="https://user-images.githubusercontent.com/48225427/168979711-1f8aa3f9-0ea3-40d3-b85d-0a3e0b8bd6f3.png">

**Comment by lukasfehling** [comment]
I had the same issue today and after some debugging like @acSpock told us I finally got an error message that helped me figuring out what seems to be the problem.

Including console.log(err) didn't helped but commenting the dataSource.destroy() method out I got the espected result and an error:
![image](https://user-images.githubusercontent.com/56871540/169651923-dc7ef286-d17e-4fba-844f-f9be1ccc3de9.png)

I then found this article that solved my problems (Seems like I just had to define a password for connecting to an mysql database...)
https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

Hope that helps some of you.

**Comment by Valeronlol** [comment]
check [this](https://github.com/Valeronlol/typeorm-migrations-example), it might helps.

**Comment by Lujo5** [comment]
This error is very misleading, you would believe that something is wrong with database credentials or connection options, but in my case, it was due to additional `"paths"` defined in my `tsconfig.json` file.

The solution was to install `ts-node`  and `tsconfig-paths` packages and add this config to the `tsconfig.json`:
```
{
  "compilerOptions": {
    ...
    "paths": {
      "@modules": [
        "src/modules"
      ],
      ...
  },
  "ts-node": {
    "require": [
      "tsconfig-paths/register"
    ]
  }
}
```

**Comment by gillepsi-swyftx** [comment]
This gist reproduces the issue:

https://gist.github.com/gillepsi-swyftx/d595a281ec08c019ea12abbfa20ea058

Most of the CLI commands currently run `dataSource.destroy()` in a `catch {}` block when an error occurs during the command ([see here](https://github.com/gillepsi-swyftx/typeorm/blob/506133e2179529bf3add2b0b982613835d321af6/src/commands/MigrationRunCommand.ts#L73)). This call to `destroy()` is throwing, which masks the underlying issue. The error caught in the `catch {}` block should be logged regardless of whether `destroy()` throws. I'll follow up with a PR to address this.

**Comment by gillepsi-swyftx** [comment]
Raised https://github.com/typeorm/typeorm/pull/9135 to move the log entry above the call to `dataSource.destroy()`.

**Comment by rgembalik** [comment]
After a couple of hours of investigation I also came to this conclusion: If you see the error below after writing some migrations:
  ```
  CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established
  ```
  and it even shows when running `typeorm migration:show`

  then you probably have problem with connection  **or your migration code!**. 
  
  Unfortunately, typeorm (or typeorm cli, or anything related) **hides all compilation errors from migrations**. The best way to learn what is wrong with your migration is to run:
  ```
  npx ts-node
  import { MIGRATION_CLASS_NAME } from './src/migration/MIGRATION_FILENAME'
  MIGRATION_CLASS_NAME
  ```
This will show you actual errors in the code syntax and will help you solve them. In my case, it was just a typo in a variable name, but cli always reported `CannotExecuteNotConnectedError`, so I spent way too long time digging into my connectivity params.

**Comment by CaCaBlocker** [comment]
same here today, 😥

**Comment by forrestwilkins** [comment]
Updating TypeORM from `^0.3.6` to `^0.3.12` resolved the issue for me. I was seeing the `Cannot execute operation on "default"` error because I hadn't yet added a new entity to my datasource config. I was able to see what the actual error was after updating to the latest version.
