### ISSUE TITLE
Trino Support

### ISSUE THREAD

**Issue by xyb** [typeorm/typeorm#8886]
## Feature Description

Add support for Trino. Multiple OLAP (or OLTP, but not recommended officially) data sources can be accessed simultaneously through trino.

### The Problem

[Trino](https://github.com/trinodb/trino) is a distributed SQL query engine designed to query large data sets distributed over one or more heterogeneous data sources. My team uses both TypeORM and Trino in our projects, and if we could access Trino through TypeORM, the code would be cleaner and easier to migrate between databases. Trino is also very popular and it's worth to support it.

### The Solution

I think adding support for the recommended library [presto-client-node](https://github.com/tagomoris/presto-client-node) from [the official website](https://trino.io/resources.html#libraries) is probably the most straightforward way to do this.

### Considered Alternatives

n/a

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
We do not have in plans to support new DBMSes. If you want to sponsor the development, [contact me ](https://typeorm.io/support) via email. If you want to contribute and implement new driver by your own - feel free to contribute.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
