### ISSUE TITLE
ManyToMany relations save throws "Violation of PRIMARY KEY constraint" when a property from combined primary key from relation entity is an other relation property

### ISSUE THREAD

**Issue by christian-forgacs** [typeorm/typeorm#8892]
## Issue Description

While saving an entity with ManyToMany relation the first save works great. But if I change the ManyToMany relation children, the exception `Violation of PRIMARY KEY constraint 'PK_c83e17466322282074e0360a96e'. Cannot insert duplicate key in object 'dbo.city_zips_zip'. The duplicate key value is (de, 60311, 41a3433e-f36b-1410-84db-00668d135ea6)` throws.

For testing I remove the constraint in the relation table...

In the query log I can see, that you first insert all relations and after inserting you remove all relations. I guess the order is wrong.

```mssql
INSERT INTO "city_zips_zip"("zipCountryCode", "zipCode", "cityId") VALUES (@0, @1, @2), (@3, @4, @5) -- PARAMETERS: [{"value":"de","type":"nvarchar","params":["2"]},{"value":"60311","type":"nvarchar","params":[]},{"value":"41A3433E-F36B-1410-84DB-00668D135EA6","type":"uniqueidentifier","params":[]},{"value":"de","type":"nvarchar","params":["2"]},{"value":"35781","type":"nvarchar","params":[]},{"value":"41A3433E-F36B-1410-84DB-00668D135EA6","type":"uniqueidentifier","params":[]}]

DELETE FROM "city_zips_zip" WHERE (("cityId" = @0 AND "zipCountryCode" = @1 AND "zipCode" = @2) OR ("cityId" = @3 AND "zipCountryCode" = @4 AND "zipCode" = @5)) -- PARAMETERS: ["41A3433E-F36B-1410-84DB-00668D135EA6","de","35781","41A3433E-F36B-1410-84DB-00668D135EA6","de","60311"]
```

### Expected Behavior

Excepted on sync for ManyToMany I want to only remove relations they aren't in the new array and only insert new relations.

### Actual Behavior

At the moment the save method throws an exception, that an insert in relation table can't execute because a violation on primary key constraint because you insert before delete all relations.

### Steps to Reproduce

Create 2 entities:

```typescript

@Entity()
export class City {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  caption: string;

  @RelationId('zips')
  zipCodes: string[];

  @ManyToMany(() => Zip, zip => zip.cities, {
    cascade: true,
  })
  @JoinTable()
  zips: Zip[];
}

Entity()
export class Country {
  @PrimaryColumn({ length: 2 })
  code: string;

  @Column()
  caption: string;

  @OneToMany(() => Zip, zip => zip.country)
  zips: Zip[];
}

@Entity()
export class Zip {
  @RelationId('country')
  @PrimaryColumn({ length: 2 })
  countryCode: string;

  @ManyToOne(() => Country, country => country.zips, {
      createForeignKeyConstraints: true,
  })
  @JoinColumn({ name: 'countryCode' })
  country: Country;

  @PrimaryColumn()
  code: string;

  @RelationId('cities')
  cityIds: string[];

  @ManyToMany(() => City, city => city.zips)
  @JoinTable({ name: 'city_zips_zip' })
  cities: City[];
}

```

Execute following: 

```typescript

await connection.getRepository(Country).save({
  code: 'de',
  caption: 'Germany',
});

// create works great 
const city = await connection.getRepository(City).save({
  id: 'INSERT_ID_OF_TEST_CITY_HERE',
  caption: 'Test city',
  zips: [
    {
      countryCode: 'de',
      code: '60311',
    },
    {
      countryCode: 'de',
      code: '35781',
    },
  ],
}, {
  reload: true,
});

// but if we update the relations the exception throws

await connection.getRepository(City).save({
  id: city.id,
  zips: [
    {
      countryCode: 'de',
      code: '60311',
    },
  ],
});

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Linux in Docker |
| Node.js version     | v14.19.1  |
| Typescript version  | 4.3.5  |
| TypeORM version     | 0.3.6  |

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | yes            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by christian-forgacs** [comment]
I guess the problem is in https://github.com/typeorm/typeorm/blob/0418ebcaf6835dfffe3c3db1f66d20bfe3e5b09d/src/persistence/EntityPersistExecutor.ts#L148 

The https://github.com/typeorm/typeorm/blob/0418ebcaf6835dfffe3c3db1f66d20bfe3e5b09d/src/persistence/subject-builder/ManyToManySubjectBuilder.ts#L14 first build the new relations and after this the buildForAllRemoval function remove the relations. But the correct order is first to remove all relations and add the new after delete.

**Comment by christian-forgacs** [comment]
I can reproduce this issue but also with a test. I push it into my fork:

https://github.com/christian-forgacs/typeorm/commit/c49e8e1a0165e1385643a5b206ea207daabdc3c6

The problem is, that in our project we use a combined primary key in the zip entity. The "countryCode" is the primary key from an other entity (Country). On Friday I doesn't test if this is the problem but it is.

I write two cases for this test:

1. The country code is only a primary column in zip entity > works great
2. The country code is a relation id and primary column in zip entity > test failed with  `Violation of PRIMARY KEY constraint` with mssql, or `Duplicate entry 'c69c614e-565d-424a-b541-1df48cf69d7e-de-54321' for key 'PRIMARY'` with mysql, or `SQLITE_CONSTRAINT: UNIQUE constraint failed: city_zips_zip.cityWithCountryRelationId, city_zips_zip.zipWithCountryRelationCountryCode, city_zips_zip.zipWithCountryRelationCode` with sqlite

Also we found one strange think...

https://github.com/typeorm/typeorm/blob/0418ebcaf6835dfffe3c3db1f66d20bfe3e5b09d/src/persistence/subject-builder/ManyToManySubjectBuilder.ts#L74-77

In this comment written "we use unshift" but on line 77 is push used. But if I change the push to an unshift it doesn't work too.

**Comment by christian-forgacs** [comment]
I found the difference between this two save calls:

![image](https://user-images.githubusercontent.com/15897007/164010559-38430500-d641-4ac1-98d5-234670da755b.png)

The first output is with the successfully test I've added without the combined primary key with a relation to an other entity.

The second output is with the combined primary key of a related entity.

Because in the second test the countryCode is an object instead of the string, typeorm insert instead of update / delete the entries.

**Comment by christian-forgacs** [comment]
After my last testing with this issue i realize, that if I fetch already stored data from database, typeorm returns the same wrong structure of the RelationId property from insert.

![image](https://user-images.githubusercontent.com/15897007/164222048-6b42a90b-0419-4eee-b593-77f4e77a237e.png)

So I think the issue isn't from save action, its the general select handling in combination with RelationId and PrimaryColumn.

**Comment by christian-forgacs** [comment]
The issue is here:

https://github.com/typeorm/typeorm/blob/master/src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts#L594

If a entity has a primary key that is also a relation (in my example countryCode -> Country property code), this condition doesn't catch this case.

**Comment by christian-forgacs** [comment]
Can be close if pull request #8959 is merged.

**Comment by paraskapoorMM** [comment]
After I upgraded my project dependency typeorm from 0.3.6 to 0.3.7

I am facing an issue with the save method. It throws an error of Duplicate data in case of updating records.

I have checked the change logs for 0.3.7 and edited my installed dependency to removed your change for `!column.isPrimary` check. Now it works fine.

Kindly assist me, as due to this issue, I am not able to update the dependency on the server.

cc: @pleerock @christian-forgacs

**Comment by christian-forgacs** [comment]
@paraskapoorMM it's interesting.. the update solve the issue in our project and didn't lead to any new problem 😕 @pleerock do you have any idea?

**Comment by christian-forgacs** [comment]
@paraskapoorMM which database are you using?

**Comment by paraskapoorMM** [comment]
We are using MySQL

**Comment by konradkalemba** [comment]
I'm also getting this error on TypeORM 0.3.7 + MySQL setup.

```Error: Duplicate entry '3-2' for key 'role_permissions_permission.PRIMARY'```

@paraskapoorMM Your suggestion of removing `!column.isPrimary` check didn't work for me. :/

**Comment by paraskapoorMM** [comment]
@konradkalemba 
Kindly share some examples or snippets to check.

**Comment by konradkalemba** [comment]
@paraskapoorMM Sorry for bothering you, guys. After deeper investigation I found that the way of passing only permissions' ids is the problem in my case:
```ts  
return await this.rolesRepository.save(
    ...restRoleCreateInput,
    permissions: permissionIds.map(permissionId => ({ id: permissionId })),
);
```

When passing "full" entities everything works correctly. I wrongly thought this is related to this issue, because on previous versions (<0.3.0) it worked fine with PostgreSQL.

**Comment by christian-forgacs** [comment]
@konradkalemba can you try to use version 0.3.6? This change released in version 0.3.7

**Comment by TurningTide** [comment]
> @paraskapoorMM Sorry for bothering you, guys. After deeper investigation I found that the way of passing only permissions' ids is the problem in my case:
> 
> ```ts
> return await this.rolesRepository.save(
>     ...restRoleCreateInput,
>     permissions: permissionIds.map(permissionId => ({ id: permissionId })),
> );
> ```
> 
> When passing "full" entities everything works correctly. I wrongly thought this is related to this issue, because on previous versions (<0.3.0) it worked fine with PostgreSQL.

reached this issue with exact same problem. 0.3.7.
saving M2M entity with `repo.save({id: item.id, manyItems: item.manyItems})` SOMETIMES causes duplicate entry error on junction table. I've never been able to reproduce this case intentionally cuz it's always happens randomly.

your comment saved my life!

**Comment by Cthulhu-tech** [comment]
> > @paraskapoorMMИзвините за беспокойство, ребята. После более глубокого исследования я обнаружил, что в моем случае проблема заключается в передаче только идентификаторов разрешений:
> > ```ts
> > return await this.rolesRepository.save(
> >     ...restRoleCreateInput,
> >     permissions: permissionIds.map(permissionId => ({ id: permissionId })),
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > При передаче "полных" сущностей все работает корректно. Я ошибочно думал, что это связано с этой проблемой, потому что в предыдущих версиях (<0.3.0) он нормально работал с PostgreSQL.
> 
> достиг этой проблемы с точно такой же проблемой. 0.3.7. сохранение объекта M2M с `repo.save({id: item.id, manyItems: item.manyItems})`ИНОГДА вызывает ошибку дублирования записи в соединительной таблице. Я никогда не мог намеренно воспроизвести этот случай, потому что это всегда происходит случайно.
> 
> Ваш комментарий спас мне жизнь!

did you manage to solve this problem?

**Comment by andrewhamili** [comment]
[https://github.com/andrewhamili/sample-many-to-many](url)

Please refer to the repository link included here. I would like to know how to disable using productId and resourceId as a Primary key. The goal is to map one product for multiple resources. instead of 1 product, 1 resource.
