### ISSUE TITLE
Error:Trying to transpile with Ionic

### ISSUE THREAD

**Issue by jondediego** [typeorm/typeorm#890]
Hi,
I am trying to user typeorm for an Ionic App  using a SQLite database. But I  am getting some errors when transpiling from typescript. 
`[21:33:55]  typescript: .../Suez/Aquamobile/node_modules/typeorm/driver/mongodb/MongoConnectionOptions.d.ts, line: 45
            Cannot find name 'Buffer'.

      L44:  readonly sslCA?: string[] | Buffer[];
      L46:   * String or buffer containing the certificate we wish to present

[21:33:55]  typescript: .../Suez/Aquamobile/node_modules/typeorm/driver/mongodb/MongoConnectionOptions.d.ts, line: 50
            Cannot find name 'Buffer'.

      L49:  readonly sslCert?: string | Buffer;
      L51:   * String or buffer containing the certificate private key we wish to present

[21:33:55]  typescript: .../Suez/Aquamobile/node_modules/typeorm/driver/mongodb/MongoConnectionOptions.d.ts, line: 55
            Cannot find name 'Buffer'.

      L54:  readonly sslKey?: string | Buffer;
      L56:   * String or buffer containing the certificate password`

And many more simmilar errors in mongodb driver.
 I have node/types dependency installed. Here is my package.json:

`{
  "name": "AquaMobile",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/sqlite": "^4.2.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic/storage": "2.0.1",
    "@types/node": "^8.0.28",
    "cordova-android": "^6.2.3",
    "cordova-plugin-console": "^1.0.5",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-sqlite-storage": "^2.0.4",
    "ionic-angular": "3.6.0",
    "ionic-orm-2": "0.0.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "typeorm": "0.1.0-alpha.42",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "2.1.4",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {},
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {}
    },
    "platforms": [
      "android"
    ]
  }
}
`
Am I missing some dependency?

**Comment by pleerock** [comment]
I think this question is to @daniel-lang

**Comment by daniel-lang** [comment]
For some reason you have to add
```
"typeRoots": [
   "node_modules/@types"
]
```
to your `tsconfig.json`. This should be the default behaviour but when running `ionic build` or `ionic serve` the compiler doesn't know where to look for the typings.

**Comment by jondediego** [comment]
Thanks, 
Now it is building properly. However when I try to run project on android emulator there is an error when creating connection between orm and database.

> 09-15 11:28:42.600 3096-3096/io.ionic.starter D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 748 : Error:Error: Database location or iosDatabaseLocation setting is now mandatory in openDatabase call.
09-15 11:28:42.600 3096-3096/io.ionic.starter I/chromium: [INFO:CONSOLE(748)] "Error:Error: Database location or iosDatabaseLocation setting is now mandatory in openDatabase call.", source: file:///android_asset/www/build/main.js (748)
This is the way I am creating connection:
`     return createConnection({
            type: "cordova",
            database: AppSettings.DB_NAME,
            entities: [
                User
            ],
            autoSchemaSync: true//OJO quitar para producción
        }).then(async connection => {
            this.general.addLog('BBDD conectada con ORM');
            this.connection = connection;
        }).catch(error => {
            this.general.addLog('Error:' + error);
        });`
The cordova sqlite plugin I am using on my ionic project is 
        "cordova-sqlite-storage": "^2.0.4",
and 
        "@ionic-native/sqlite": "^4.2.1",
Which version of cordova-sqlite plugin should I use?
Should I open a new issue for this question?

**Comment by daniel-lang** [comment]
Interesting, that you are able to compile with no error even though your `createConnection` call is missing an option. It should be
```ts
return createConnection({
   type: "cordova",
   database: AppSettings.DB_NAME,
   location: "default", // this is missing
   entities: [ User ],
   autoSchemaSync: true //OJO quitar para producción
}).then(async connection => {
   this.general.addLog('BBDD conectada con ORM');
   this.connection = connection;
}).catch(error => { this.general.addLog('Error:' + error); });
```

where `location` is one of the options from the [cordova-sqlite-plugin](https://github.com/litehelpers/Cordova-sqlite-storage#opening-a-database).

@pleerock I will add a check to the driver so that a nicer error is generated. But still in my experience it doesn't compile with a missing option.

**Comment by sunfeng90** [comment]
> For some reason you have to add
> 
> ```
> "typeRoots": [
>    "node_modules/@types"
> ]
> ```
> 
> to your `tsconfig.json`. This should be the default behaviour but when running `ionic build` or `ionic serve` the compiler doesn't know where to look for the typings.

Thanks, it worked for me!
