### ISSUE TITLE
Array parameters not always escaped in postgres with array operators

### ISSUE THREAD

**Issue by shiro** [typeorm/typeorm#8913]
## Issue Description

**Edit:** It seems to work when replacing `:...tags` with `:tags` for some reason. If this is intended behaviour please close this issue. (and, if possible, provide an explanation for future readers)

<hr />

Array parameters are not always properly expanded for Postgres, such as when the `<@` operator is used ([operator docs](https://www.postgresql.org/docs/current/functions-array.html)).

### Expected Behavior

Should escape array parameters as usual.

### Actual Behavior

Produces an invalid query due to not escaping the array, see output below.

### Steps to Reproduce

1. Use a `Raw` where clause, attempting to filter entries by an array field - accepting the ones where the array is a superset of the array provided as a parameter
2. Observe the query failing

```typescript
const tags = [/*some string array*/];

const [results, resultsLength] = await repo.findAndCount({
    where: {
        tags: Raw((alias) => `(:...tags) <@ ${alias}`, {tags}),
    },
});
```

case 1: array with 1 element - `tags = ["a"]`:
```
error: malformed array literal: "a"
```

case 2: array with 2 or more elements - `tags = ["a", "b"]`:
```
operator does not exist: record <@ text[]
```
casting it to `text[]` results in:
```
cannot cast type record to text[]
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Arch Linux   |
| Node.js version     | 16.13  | 
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.3.6  | 

### Additional Context

Tested using `Raw` but probably occurs in other queries where the `<@` operator is used with array parameters.

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
Working as expected - `:...` syntax expands your array, so it becomes:

```
('a', 'b') @> alias
````

Postgres interprets it as record or tuple, depending on context.

To achieve your goal, use syntax:

```
    where: {
        tags: Raw((alias) => `(:tags)::text[] <@ ${alias}`, {tags}),
    },
```

You can also use `ArrayOverlaps` operator introduced in `0.3` version.
