### ISSUE TITLE
Add Yandex Database

### ISSUE THREAD

**Issue by OSA413** [typeorm/typeorm#8916]
## Feature Description

Add YDB as a supported DB.

### The Problem

I was excited about YDBs source code release under an open license and wanted to check if it is possible to use it comfortably in the existing (for migration from MS SQL) or future projects. I've tried to search the readme and issues of this repository but found no mentions of YDB.

### The Solution

It looks like the only SDK they have for is this one:
https://github.com/ydb-platform/ydb-nodejs-sdk

I've found only one ORM for the DB that was released recently (and is in development, no license at this moment).
https://github.com/goshander/ydb-orm

### Additional Context

Yandex have recently [released the source code of their Database under the Apache 2.0 license](https://github.com/ydb-platform/ydb).

### Are you willing to resolve this issue by submitting a Pull Request?
 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
We do not have plans to support new databases. If you are interested in contributions - feel free.
