### ISSUE TITLE
Entity with deletedAt causing overrides whole query

### ISSUE THREAD

**Issue by roninhack** [typeorm/typeorm#8921]
Hi,

In Entity if there is deletedAt column it is overriding initial query like ; 
find({where:{myColumn:myValue}})
its turning with override this one for sending to mongodb;
{"$where":"this.deletedAt==null"}

deletedAt override whole query , actually its should be optional , users can arrange by itself for own queries.

**Comment by Ginden** [comment]
@roninhack Please provide minimal reproduction case and use issue template.
