### ISSUE TITLE
Typeorm config not loading without any error

### ISSUE THREAD

**Issue by LonguCodes** [typeorm/typeorm#8929]
## Issue Description

When trying to use the cli using `ts-node node_modules/typeorm/cli.js` the config file is not loaded.  After debugging i've encountered this error `ormconfig.ts(7,13): error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.`

The problem is I had to go through the library code with console logs, the error was not shown

### Expected Behavior

Config file is loaded and there is an error about it.

### Actual Behavior

Config file is completly ignored without any error

### Steps to Reproduce

1. Install typeorm@0.2.44 and ts-node
2. Create ormconfig.ts with any options (eg. migrations dir  or a console log at the beggining)
3. Run any  typeorm command (eq try to create or run migrations) 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Fedora linux 34 (5.16.18) |
| Node.js version     | 14.15.1  | 
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.2.44  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - :heavy_multiplication_x:  Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - :white_check_mark:  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by LonguCodes** [comment]
Also, the same situation goes for this error `ormconfig.ts(3,1): error TS1203: Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.`

**Comment by rakesh-avegenXpear** [comment]
Try:-

yarn typeorm

Or

node ./node_modules/.bin/typeorm
