### ISSUE TITLE
Proper way to Delete Object w/ relation

### ISSUE THREAD

**Issue by puttputt** [typeorm/typeorm#893]
What is the proper way to delete an object, but also delete the foreign key?

Right now I have:
```
@Entity()
export class Location {

    @PrimaryGeneratedColumn()
    id : number;

    @OneToOne(type => Address, {
        cascadeRemove: true,
        cascadeInsert: true
    })
    @JoinColumn()
    address : Address;

}
```

And trying to delete the Address like:
```
public async deleteForLocation(locationId : number, id : number) : Promise<any> {
        const locationRepository = getEntityManager().getRepository(Location);

        let location = await locationRepository.findOneById(locationId);
        if(!location) {
            throw boom.notFound('Location Not Found');
        }

        location.address = null;

        let result = await locationRepository.persist(location);
        
        return result;
    }

```

The error I receive is: Cannot read property \'joinColumns\' of undefined

Which I assume is because I do not load the entire Location object (no relations are included).

what is the proper way to delete the object? Do I have to build a query for every relation?

**Comment by pleerock** [comment]
There are several issues right now with cascades, please remove them and try again. If you want to completely remove address as well simply call `remove` on it for now:

```ts
        let location = await locationRepository.findOneById(locationId);
        if(!location) {
            throw boom.notFound('Location Not Found');
        }
        location.address = null;
        await manager.remove(location.address); // or addressRepository.remove
        let result = await locationRepository.persist(location);
        
```

**Comment by puttputt** [comment]
Thanks @pleerock. I have resolved my issue but I narrowed down the bug.

It looks like the issue was that I had an additional column on Location like this:
```
OneToMany(type => RegistrationType, registrationType => registrationType.location)
    @JoinColumn()
    registrationType : RegistrationType[];
```

But forgot to add the proper ManyToOne relationship on the RegistrationType object.

**Comment by AlexanderPershin** [comment]
> There are several issues right now with cascades, please remove them and try again. If you want to completely remove address as well simply call `remove` on it for now:
> 
> ```ts
>         let location = await locationRepository.findOneById(locationId);
>         if(!location) {
>             throw boom.notFound('Location Not Found');
>         }
>         location.address = null;
>         await manager.remove(location.address); // or addressRepository.remove
>         let result = await locationRepository.persist(location);
>         
> ```

Did as you say, and got an error "Error: Cannot query across one-to-many for property "
