### ISSUE TITLE
Compilation bug. Using `@JoinColumn` crashes application.

### ISSUE THREAD

**Issue by Stanys-dev** [typeorm/typeorm#8931]
## Issue Description
Using `@JoinColumn` crashes application.

### Expected Behavior

TypeORM should work without crashing application

### Actual Behavior

App crashes after adding `@JoinColumn()`

Error:
```
node_modules/typeorm/browser/index.js:3
import "reflect-metadata";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (src/modules/domains/view-item/view-item.entity.ts:6:1)
```

Entity:
```Typescript
import { Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm'
import { Column } from '../../common/in-memory-db/dataAccess.annotations'
import { ViewEntity } from '../view/view.entity'
import { ApiProperty } from '@nestjs/swagger'
import { DeviceInfoEntity } from '../device-info/device-info.entity'
import { JoinColumn } from 'typeorm/browser'

@Entity({
  name: 'view_item',
})
export class ViewItemEntity {
  @PrimaryGeneratedColumn()
  @ApiProperty({ example: '1', type: 'string' })
  id!: string

  @ManyToOne(() => ViewEntity, (view) => view.items, { onDelete: 'CASCADE' })
  @ApiProperty({ type: () => ViewEntity, required: true })
  view!: ViewEntity

  @Column({ type: 'varchar', length: 50 })
  @ApiProperty({ example: '1', type: 'string' })
  deviceId!: string

  @ManyToOne(() => DeviceInfoEntity, {
    onDelete: 'CASCADE',
  })
  @JoinColumn()
  @ApiProperty({ type: () => DeviceInfoEntity, required: true })
  device!: DeviceInfoEntity

  constructor(viewItem: Partial<ViewItemEntity>) {
    Object.assign(this, viewItem)
  }
}
```

### Steps to Reproduce

I only added `@JoinColumn()`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Ubuntu    | 20.04.4 LTS         | 
| Node.js version     | v16.14.2  |
| Typescript version  | 4.5.4 | 
| TypeORM version     |0.2.41  | 
| TypeORM version     |0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
> import { JoinColumn } from 'typeorm/browser'

This is issue. Replace it with `'typeorm'`.
