### ISSUE TITLE
Support Databricks as Data Source Option

### ISSUE THREAD

**Issue by ben-wang** [typeorm/typeorm#8932]
## Feature Description
Support Databricks as data source option
### The Problem

Currently, can not use TypeORM for Databricks 

### The Solution

It'll be great if TypeORM supports Databricks as data source

### Considered Alternatives

None

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |
| 'databricks'   |yes           |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
Currently, TypeORM authors [don't implement new drivers](https://github.com/typeorm/typeorm/issues/8886#issuecomment-1098047627). Feel free to open PR for that.

**Comment by jdbodyfelt** [comment]
Any more motion on this ticket? We're doing a lakehouse migration and our API currently uses TypeORM.

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
