### ISSUE TITLE
TypeORM returns empty result when using Nestjs

### ISSUE THREAD

**Issue by volunux** [typeorm/typeorm#8942]
I am suspecting Nestjs is the problem and I am very unhappy about this problem and development.

I have been given an assignment to develop a simple application. I can attest that without the use of Nestjs, everything works perfectly and I didn't have any problem.

Anytime I send a request, The logging from TypeOrm shows the correct SQL query being executed but the result is either null or undefined or an empty array.

I tried it from the SQL console and everything seems to be fine and the result is returned like I expected. I run an application I developed with express.js and everything seems to work perfectly.

My problem is with Nestjs, No result is returned but the correct query is executed.

I don't know how to reproduce the issue with Nestjs because I have to upload the whole repository given the fact it is structured according to Nestjs guidelines.

**Comment by Ginden** [comment]
Reproduction repository can be provided by [Github Gist](https://gist.github.com/) or as normal Github repository.

Though, questions related to `@nestjs/typeorm` should be asked on their Discord.

**Comment by volunux** [comment]
I am feeling completely down and sick because of this problem. However I created a repository because of this and I want to point the most important folders are database, model which contains all entities.

I don't know why this is not working. Somebody please help.

**Comment by Ginden** [comment]
@volunux I can't provide assistance on this repository - it contains 10071 lines of code and 26 packages not included in `package.json`. 

Usually, sensible reproduction of error can be provided in less than 5 files.

**Comment by AlexMesser** [comment]
Hope you have resolved your issue. If no, please open a new issue using our issue template and provide a **MINIMAL** reproduction example.
