### ISSUE TITLE
Cannot find name 'process' error when building NestJS for production after downgrading to typeorm@0.2

### ISSUE THREAD

**Issue by dominicarrojado** [typeorm/typeorm#8951]
## Issue Description

"Cannot find name 'process'" error when building NestJS for production after downgrading to typeorm@0.2

### Expected Behavior

I should not receive this error since that error does not occur if I install the latest `typeorm`.

### Actual Behavior

"Cannot find name 'process'" error when building NestJS for production after downgrading to typeorm@0.2

```
Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
```

### Steps to Reproduce

1. Clone [this repo](https://github.com/dominicarrojado/nestjs-postgres-boilerplate)
2. Make sure you have installed yarn and docker w/ docker compose is running in the background
3. Run `yarn docker-compose:prod:build-only`
4. You'll get the error

You can check the error from GitHub action job [here](https://github.com/dominicarrojado/nestjs-postgres-boilerplate/runs/6224253202?check_suite_focus=true) as well.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.14.2-alpine  | 
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.2.45  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment]
We no longer support 0.2.* versions.
