### ISSUE TITLE
Issue with FindOne repository method

### ISSUE THREAD

**Issue by cdominguezg** [typeorm/typeorm#8954]
## Issue Description
I am trying to access to the findOne method of the repository, but it tell me the FindOneOptions are not compatible.
### Expected Behavior
Return the entity, as ocurrs in the < 0.3 versions

### Actual Behavior
It tell me the following error:

```
Type '{ email: string; }' is not assignable to type 'FindOptionsWhere<Customer> | FindOptionsWhere<Customer>[] | undefined'.   Types of property 'email' are incompatible.     Type 'string' is not assignable to type 'boolean | FindOperator<any> | FindOptionsWhere<CustomerEmail> | FindOptionsWhere<CustomerEmail>[] | EqualOperator<...> | undefined'.
```

### Steps to Reproduce

1. Add a generic class for TypeOrmRepository.
2. Make an implementation with of this repository, using an Aggregate Root as <T>

#### TypeOrmRepository<T>
```typescript
export abstract class TypeOrmRepository<T extends AggregateRoot> {
    constructor(private _client: Promise<DataSource>) {
    }

    protected abstract entitySchema(): EntityTarget<T>;

    protected client(): Promise<DataSource> {
        return this._client;
    }

    protected async repository(): Promise<Repository<T>> {
        return (await this.client()).getRepository(this.entitySchema());
    }

    protected async persist(aggregateRoot: T): Promise<void> {
        const repository = await this.repository();
        await repository.save(aggregateRoot as any);
    }
}
```

#### TypeOrmCustomerRepository
```typescript
export class TypeOrmCustomerRepository extends TypeOrmRepository<Customer> implements CustomerRepository {
    protected entitySchema(): EntityTarget<Customer> {
        return CustomerSchema;
    }

    delete(email: CustomerEmail): Promise<void> {
        return Promise.resolve(undefined);
    }

    async getCustomer(email: CustomerEmail): Promise<Nullable<Customer>> {
        const repository = await this.repository();
        return await repository.findOne({
            where: {
                email: email.value
            }
        });
    }

    list(): Promise<Customer[]> {
        return Promise.resolve([]);
    }

    save(customer: Customer): Promise<void> {
        return Promise.resolve(undefined);
    }

}
```

#### CustomerSchema
```typescript
@Entity({
    name: "Customer",
})
export class CustomerSchema {
    @Column({
        type: "string",
        length: 255,
        nullable: false,
        primary: true,
        transformer: ValueObjectTransformer(CustomerEmail)
    })
    // @ts-ignore
    public email: string;

    @Column({
        type: "varchar",
        length: 255,
        nullable: false,
        primary: true,
        transformer: ValueObjectTransformer(CustomerName)
    })
    // @ts-ignore
    public name: CustomerName;

    @Column({
        type: "varchar",
        length: 255,
        nullable: false,
        primary: true,
        transformer: ValueObjectTransformer(CustomerPassword)
    })
    // @ts-ignore
    public password: CustomerPassword

    @Column({
        type: "date",
        length: 255,
        nullable: false,
        primary: true,
        transformer: ValueObjectTransformer(CustomerBirthday)
    })
    // @ts-ignore
    public customerBirthday: CustomerBirthday

}

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Windows 10     |
| Node.js version     |  14.17.4 | 
| Typescript version  | 4.6.4  | 
| TypeORM version     | 0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
Use `EqualOperator`.

**Comment by nbdn** [comment]
@Ginden please re-open the issue, if you try to use the `EqualOperator` in the example given above, it doesn't work at all.

**Comment by rbruels** [comment]
@Ginden That's a pretty lame reply given this is a breaking change in TypeORM 0.3. It's not a bug (the paucity of migration documentation sure is), but providing an example takes only a second of time.

@cdominguezg — in TypeORM 0.3, find*() have all changed significantly. Positive changes I think. But in your code, you'll need to change:

```
return await repository.findOne({
    where: {
        email: email.value
    }
});
```

to something like:

```
return await repository.findOne({
    where: {
        email: Equal(email.value)
    }
});
```

`Equal` is a Find Option provided here: [https://orkhan.gitbook.io/typeorm/docs/find-options#advanced-options](https://orkhan.gitbook.io/typeorm/docs/find-options#advanced-options).

I'm not personally sure why the operators are required on certain Find operations or not -- I just know this helped me clear the type errors by explicitly specifying the operator.

@nbdn If that didn't work for you, then that sounds like a bigger bug, worth filing.

**Comment by hidayetmm** [comment]
You can try using exported type from 'typeorm' like this:

```
return await repository.findOne({
    where: {
        email: email.value as FindOptionsWhere<Customer>
    }
});
```

**Comment by p-fedyukovich** [comment]
> @Ginden That's a pretty lame reply given this is a breaking change in TypeORM 0.3. It's not a bug (the paucity of migration documentation sure is), but providing an example takes only a second of time.
> 
> @cdominguezg — in TypeORM 0.3, find*() have all changed significantly. Positive changes I think. But in your code, you'll need to change:
> 
> ```
> return await repository.findOne({
>     where: {
>         email: email.value
>     }
> });
> ```
> 
> to something like:
> 
> ```
> return await repository.findOne({
>     where: {
>         email: Equal(email.value)
>     }
> });
> ```
> 
> `Equal` is a Find Option provided here: https://orkhan.gitbook.io/typeorm/docs/find-options#advanced-options.
> 
> I'm not personally sure why the operators are required on certain Find operations or not -- I just know this helped me clear the type errors by explicitly specifying the operator.
> 
> @nbdn If that didn't work for you, then that sounds like a bigger bug, worth filing.

Thanks for reply, but it still doesn't work

**Comment by celiabayet** [comment]
Hello, can we re-open this issue ? It still doesn't work :(

**Comment by abdelhalim97** [comment]
Hello guys
u either use 
findOne({ where: { id } })
or 
findOneBy({id})
both works for me but why cant we use findOne({ id  }) ? sounds weird

**Comment by hosseinSafari** [comment]
This doesn't work for me either :(
Please open this issue. thanks

**Comment by dhanushka365** [comment]
Instead of using findOne, try to use findOneBy as bellow this works for me

```
import {Repository,FindOptionsWhere} from 'typeorm'

async createAccount({email, password,role}:CreateAccountInput): Promise<[boolean ,string?]>{
        try {
            const exists = await this.users.findOneBy({ email:email } as FindOptionsWhere<User>);

            if (exists) {
                return [false, 'There is a user with that email already'];
            }

            await this.users.save(this.users.create({email , password, role}));
            return[true];
        }catch (e) {
         return [false,"Couldn't create account"];
     }
    }
```

**Comment by DevGuilhermeSv** [comment]
i have same problem.

**Comment by finkos45** [comment]
dhanushka365 your solution work for me thanks
 const exists = await this.users.findOneBy({ email:email } as FindOptionsWhere<User>);

**Comment by ktalebian** [comment]
having to do `as FindOptionsWhere` is not a solution - that's just tricking TS not to warn. This typing error needs to be fixed please!

**Comment by vis97c** [comment]
@Ginden This is still an issue an not giving any details about the root of the issue isn't helpful

**Comment by siamFernanda** [comment]
> Instead of using findOne, try to use findOneBy as bellow this works for me
> 
> ```
> import {Repository,FindOptionsWhere} from 'typeorm'
> 
> async createAccount({email, password,role}:CreateAccountInput): Promise<[boolean ,string?]>{
>         try {
>             const exists = await this.users.findOneBy({ email:email } as FindOptionsWhere<User>);
> 
>             if (exists) {
>                 return [false, 'There is a user with that email already'];
>             }
> 
>             await this.users.save(this.users.create({email , password, role}));
>             return[true];
>         }catch (e) {
>          return [false,"Couldn't create account"];
>      }
>     }
> ```

The problem is that findOneBy doesn't accept additional parameters for searching related data :/
