### ISSUE TITLE
TypeORM 0.3.6 doesn't have cli.migrationsDir property to specify path for migration:run

### ISSUE THREAD

**Issue by vincevalstro** [typeorm/typeorm#8964]
## Issue Description

Lost cli.migrationsDir property on the datasource / connection object in the transition from 0.2.46 to 0.3.6, so the TypeORM CLI tool does not know where to look for migrations.. claims there are no migrations to run when there is a folder full of migrations that is specified in the migrations property on the datasource object

### Expected Behavior

Migrations in the migrations folder are ran.

### Actual Behavior

No migrations are ran

```bash
query: SELECT * FROM current_schema()
query: SHOW server_version;
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
No migrations are pending
```

### Steps to Reproduce

1. create a datasource file
2. note how you can't add the cli.migrationsDir option to the datasource object
3. specify the path to that datasource file in your `typeorm --dataSource=./src/config/datasource.js migration:run`
4. note how no migrations are picked up from the migrations folder

```typescript
const dataSourceOptions: Partial<DataSourceOptions> = {
  type: 'postgres',
  ...pgConn,
  /**
   * The synchronization and migrations will happen in the typeorm cli
   */
  synchronize: false,
  migrationsRun: false,
  logging: true,
  logger: 'simple-console',
  entities,
  /**
   * The migration files will be outputted in the specified PATH_TO_SVC
   */
  migrations: [`${migrationsPath}${withGlob ? '/*{.ts,.js}' : ''}`]
};
```

used to be able to have the additional property

```typescript
cli: {
    migrationsDir: `${migrationsPath}`
  }
```

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `postgres`        | yes |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by vincevalstro** [comment]
Saw this; 
- https://github.com/typeorm/typeorm/pull/8896/files

Hoped that this would work:
```sh
typeorm migration:run ./src/migrations/1651515354420-initialMigration.js --dataSource=./src/config/datasource.js
```

but `migration: run` doesn't seem to have a parameter of path like the `migration: generate` does

**Comment by vincevalstro** [comment]
Actually
```js
migrations: [`${migrationsPath}/*{.ts,.js}`]
```
was good enough, its just my `migrationsPath` didn't point to the correct folder, 

sorry for the inconvenience

**Comment by Anjaa84** [comment]
What is the current implementation for this issue now.
