### ISSUE TITLE
Create Postgres index with COALESCE over multiple columns

### ISSUE THREAD

**Issue by bonejon** [typeorm/typeorm#8965]
## Feature Description
Given I have a table that has a primary and alternate key of the same data type I wish to be able to use a COALESCE against an index to return data in a performant way.

### The Problem
Given the following table defintion: 
CREATE TABLE IF NOT EXISTS "schema"."table"
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "alt_id" uuid
-- 	...
-- 	more columns
-- 	...
    CONSTRAINT "PK" PRIMARY KEY (id),
)

I would like to be able to run the following statement:
SELECT * FROM "schema"."table" WHERE COALESCE("alt_id", "id") = '165e9898-a403-4aca-a614-9c91befb8112';

Even with the following index this query is resulting in a full table scan. Postgres is very picky on indexes.
CREATE INDEX "PK_IDX" ON "schema"."table" ("id", "alt_id");

### The Solution
The solution is to define the following index to match the statement:
CREATE INDEX "IDX_ALT_PK" ON "schema"."table" (COALESCE("alt_id", "id"));

I am not able to create such an index using TypeORM as it validates the columns. I have two propositions:

1. Allow an option on the index definition to disable the validation of columns
2. A new kind of attribute / index definition that allows the user to provide the definition of the index yet allow TypeORM to manage the name (etc..)

### Considered Alternatives

The only alternative I can think of would be to manually add the statement to the migrations generated.

### Additional Context

TypeORM is awesome !! 

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by kemenesbalazs** [comment]
+1

**Comment by Ginden** [comment]
Duplicate: https://github.com/typeorm/typeorm/issues/2561
