### ISSUE TITLE
Is it possible to set nvarchar(MAX) ?

### ISSUE THREAD

**Issue by iz-iznogood** [typeorm/typeorm#897]
Hi, how can I configure nvarchar(max) in mssql ?

**Comment by pleerock** [comment]
Good question. Actually it should be:

```ts
@Column({ type: "nvarchar" length: "MAX" })
```

But Im not sure if it will work since as I remember we convert length to number later on.
If it won't work then we'll need to change some logic and convert it to string instead of number everywhere. We need a single format (or number or string) because we make comparing down the road.

**Comment by iz-iznogood** [comment]
Yes, I also checked that you never take into account the column size for finding changed columns.
These should be fixed together since they are related.

We should change the length property to string and fix all comparisons.
We should change the TableSchema.findChangedColumns to use length to compare only datatypes that size matters.
Now it is the time to move a part of TableSchema.findChangedColumns into the driver (the actual comparison part) since the datatype names are different in each database engine and we are going to use that so that we know if a datatype supports the length attribute.

@pleerock  Is it ok if I try this ? do you agree with the approach ?

**Comment by pleerock** [comment]
Yes, I was thinking about it too. Im not satisfied with current implementation of `findChangedColumns` as well. Lets do this 👍

**Comment by iz-iznogood** [comment]
Hi, I have changed the length property in ColumnMetadata and ColumnSchema to be number | string and it seems to work fine.

However I need to add some validations on whether the column type supports length - size.
I see that you have this 

`
export type WithLengthColumnType = "int" // mysql, postgres, mssql, oracle, sqlite
    |"tinyint" // mysql, mssql, sqlite
    |"smallint" // mysql, postgres, mssql, oracle, sqlite
    |"mediumint" // mysql, sqlite
    |"bigint" // mysql, postgres, mssql, sqlite
    |"character varying" // postgres
    |"varying character" // sqlite
    |"nvarchar" // mssql
    |"character" // mysql, postgres, sqlite
    |"native character" // sqlite
    |"varchar" // mysql, postgres, mssql, sqlite
    |"char" // mysql, postgres, mssql, oracle
    |"nchar" // mssql, oracle, sqlite
    |"varchar2" // oracle
    |"nvarchar2" // oracle, sqlite
    |"binary" // mssql
    |"varbinary"; // mssql

`

This however does not emit any runtime type information so that I can validate if a Datatype supports length at runtime. 
What I need is a method columnTypeSupportsLength(column: ColumnType): boolean.
I can write a switch case statement but I would prefer to reuse the same data srtucture for the method and the declarations.

So the only thing I found that works is :
`
const WithLengthColumnTypeObj = {
    "int": "", // mysql, postgres, mssql, oracle, sqlite
    "tinyint": "", // mysql, mssql, sqlite
    "smallint": "", // mysql, postgres, mssql, oracle, sqlite
    "mediumint": "", // mysql, sqlite
    "bigint": "", // mysql, postgres, mssql, sqlite
    "character varying": "", // postgres
    "varying character": "", // sqlite
    "nvarchar": "", // mssql
    "character": "", // mysql, postgres, sqlite
    "native character": "", // sqlite
    "varchar": "", // mysql, postgres, mssql, sqlite
    "char": "", // mysql, postgres, mssql, oracle
    "nchar": "", // mssql, oracle, sqlite
    "varchar2": "", // oracle
    "nvarchar2": "", // oracle, sqlite
    "binary": "", // mssql
    "varbinary": "" // mssql    
};

export type WithLengthColumnType = keyof typeof WithLengthColumnTypeObj;

export function columnTypeSupportsLength(column: ColumnType): boolean {
    return WithLengthColumnTypeObj.hasOwnProperty(column.toString());
}
`

this is the only way that I can make keyof work so I created a fake object and used it both ways.
So later at the EntityMetadataVallidator I can do 

`
if (column.length && !columnTypeSupportsLength(normalizedColumn))
                    throw new Error(`Column ${column.propertyName} of Entity ${entityMetadata.name} does not support length property.`);

`

I would like a better approach on the declaration of WithLengthColumnType. Can you please suggest what kind of approach would you prefer ?

I need this to be agreed before I start refactoring the findChangedColumns since it will touch a number of places and I want to minimize the impact as much as possible

Thanks

**Comment by pleerock** [comment]
I dont understand why do you need all that keyof stuff? Simply make `WithLengthColumnTypeObj` string array and define it in the drivers (make them driver-specific) and they use them where you need. Alternative is to create a method in driver like `columnTypeSupportsLength` and use it.

I used your naming however we definitely need better names. Also don't forget format your messages 😆

**Comment by iz-iznogood** [comment]
Hi,

you already have this code in place
`
export type WithLengthColumnType = "int" // mysql, postgres, mssql, oracle, sqlite
|"tinyint" // mysql, mssql, sqlite
.
this datatype declares a union string type for all datatypes that support length.
The only way I could reuse this and have this configuration in one place was to use this trick with keyof stuff. 
Personally I do not like this kind of declarations, I would use an enum or something else. But it is there now and I thought about reusing it. 
Anyways, now I understood how to like it and I will do it that way.

Thanks

**Comment by pleerock** [comment]
Ah I completely forget about it, but why do you need it? I don't really like the idea of what I did with `WithLengthColumnType` so much TBH and even was thinking to remove that functionality 

BTW to format code use triple ` + language name, like this: ```ts
and finish it with triple backslash again, you probably know it...
