### ISSUE TITLE
DataTypeNotSupportedError: Data type "json" in "xxx" is not supported by "sqlite" database.

### ISSUE THREAD

**Issue by Kolesar** [typeorm/typeorm#8972]
Hi All,

The latest version of SQLite supports `json` type https://www.sqlite.org/json1.html, but in the TypeORM business logic no. Do you have any plan to update it based on the last SQLite version?

https://github.com/typeorm/typeorm/blob/master/src/driver/types/ColumnTypes.ts#L188

https://github.com/typeorm/typeorm/blob/master/src/driver/sqlite-abstract/AbstractSqliteDriver.ts#L128

I need this for e2e testing. By removing this constraint, I will be able to add all my e2e tests very easily without any workaround.

`timestamp` type is supported by SQLite as well.

**Comment by Ginden** [comment]
It should be quite simple, but we probably need someone to go through all SQLite drives and check which ones were updated, which weren't etc.

Feel free to do it yourself and open PR.

**Comment by diabl0** [comment]
Any progress on this issue? Also being being blocked by this :(

**Comment by nikeee** [comment]
Any workaround? Use varchar in the meantime?
