### ISSUE TITLE
In global Middleware request - > params {} is empty!!

### ISSUE THREAD

**Issue by qq1147050160** [typeorm/typeorm#8974]
"typeorm": "^0.3.6"

API: /api/v1/bug/:id

POST /api/v1/bug/123

I found that when using global middleware, request - > params {} is empty. I don't think it meets the expectation. The other case is normal: @UseBefore(MyGlobalMiddleware) params { id: 123 }

demo:

@Middleware({ type: 'after' })
export class MyGlobalMiddleware implements ExpressMiddlewareInterface {

  use(request: Request, response: Response, next?: (err?: unknown) => unknown) {
    console.log(request) -> params {}
  }
}

**Comment by AlexMesser** [comment]
How it is related to typeorm?

**Comment by Ginden** [comment]
Closing - no code related to TypeORM here. If you think that's a mistake, feel free to reopen.
