### ISSUE TITLE
how to convert sql to querybuilder(select nested , group_concat, group_by,count)

### ISSUE THREAD

**Issue by ngoclam98y** [typeorm/typeorm#8990]
SELECT GROUP_CONCAT(cnt) cnt
FROM (
    SELECT COUNT(*) cnt
    FROM clients
   GROUP BY date_format(createdAt,'%m/%d/%Y')
) q

**Comment by AlexMesser** [comment]
For questions / general support, please check out our [Slack channel](https://join.slack.com/t/typeorm/shared_invite/zt-uu12ljeb-OH_0086I379fUDApYJHNuw), [StackOverflow](https://stackoverflow.com/questions/tagged/typeorm) or check [TypeORM's documentation](https://typeorm.io).
