### ISSUE TITLE
Compilation bug. Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Stanys-dev** [typeorm/typeorm#8995]
## Issue Description

When trying to run compiled application, my app crashes

### Expected Behavior

App should work properly.

### Actual Behavior

When trying to run compiled application, my app crashes. I get an error:

```js
/home/stanysan/Desktop/server/backend/src/modules/common/exceptions-handler/exception-log.entity.ts:1
import { Entity, PrimaryGeneratedColumn } from 'typeorm'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/stanysan/Desktop/server/backend/node_modules/typeorm/util/ImportUtils.js:29:52
    at step (/home/stanysan/Desktop/server/backend/node_modules/tslib/tslib.js:143:27)

```

### Steps to Reproduce

Just create an entity:
```ts
import { Entity, PrimaryGeneratedColumn } from 'typeorm'
import { Column } from '../in-memory-db/dataAccess.annotations'

@Entity({
  name: 'exception_log',
})
export class ExceptionLogEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string

  @Column({ type: 'int', nullable: false, default: 500 })
  code!: number

  @Column({
    type: 'timestamp without time zone',
    nullable: false,
    default: () => 'CURRENT_TIMESTAMP',
  })
  timestamp!: Date

  @Column({ type: 'varchar', nullable: false, default: '' })
  stack!: string

  @Column({
    type: 'varchar',
    nullable: true,
  })
  name?: string

  @Column({
    type: 'varchar',
    nullable: true,
  })
  message?: string

  @Column({
    type: 'varchar',
    nullable: true,
  })
  path?: string

  @Column({
    type: 'varchar',
    nullable: true,
  })
  method?: string

  @Column({
    type: 'boolean',
    nullable: false,
    default: false,
  })
  uncaughtException?: boolean

  @Column({
    type: 'boolean',
    nullable: false,
    default: false,
  })
  unhandledRejection?: boolean
  @Column({
    type: 'boolean',
    nullable: false,
    default: false,
  })
  appRestarted?: boolean

  constructor(entity: Partial<ExceptionLogEntity>) {
    Object.assign(this, entity)
  }
}
```

and try to launch compiled application

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Ubuntu    | 20.04.4 LTS         | 
| Node.js version     | v16.14.2  |
| Typescript version  | 4.6.4 | 
| TypeORM version     |0.2.45  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
You have badly configured ts-node, ts.config or Node. It's unrelated to TypeORM.
