### ISSUE TITLE
create a site 

### ISSUE THREAD

**Issue by pleerock** [typeorm/typeorm#9]
this project needs separate site with good documentation and navigation over it

**Comment by infloop** [comment]
Hi. I can help. Can we discuss it somewhere. VK, Telegram?

**Comment by pleerock** [comment]
Hey, do you have a skype? If yes send your login to my [email](https://github.com/pleerock/typeorm/blob/master/package.json#L10)

**Comment by pleerock** [comment]
If you dont use skype I think we can create a slack for typeorm

**Comment by pleerock** [comment]
okay I I have created both slack team and a gitter room, you can join there / or chat me a private message. But best if you have a skype, I'am always available there
