### ISSUE TITLE
Have connection available inside the Entity

### ISSUE THREAD

**Issue by raducostea** [typeorm/typeorm#90]
It is possible to have the connection available inside an Entity? So i can add some custom functions to the entities?

For example:
```
@Table()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    test() {
        // Return all values with name = 'test'
    }
}
```

and then execute
```
photo = new Photo();
let photos = photo.test();

```

Great package btw!

**Comment by pleerock** [comment]
no. entities should be dummy models, you should not put such logic there. Use separate classes (services) for this purpose.

**Comment by raducostea** [comment]
Thanks @pleerock
