### ISSUE TITLE
@UpdateDateColumn does not update on upsert

### ISSUE THREAD

**Issue by udaya2899** [typeorm/typeorm#9015]
## Issue Description
@UpdateDateColumn column updates when using `save` or `update` method but not on `upsert` method 

### Expected Behavior
@UpdateDateColumn should update automatically with the current timestamp even if using `upsert` method

### Actual Behavior
@UpdateDateColumn does not update with the current timestamp if using upsert. It works only with `update` method

```
await this.ormRepository.update(customerEntity.customerId, customerEntity);
```

### Steps to Reproduce

1. Create a special column as follows:
```typescript
@UpdateDateColumn()
updatedAt: Date;
```
2. Try to update the entity containing the column using upsert.

### My Environment

| Dependency          | Version  |
| "nestjs/typeorm"              | "^8.0.0"      |
| Operating System |linux          |
| Node.js version     | 16.13.0  | 
| Typescript version  | 4.5.5 | 
| TypeORM version     | 0.2.38  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by zevstravitz** [comment]
I wonder if this should be a flag instead of being automatically applied.

I'd argue that automatically updating an UpdateDate column is indeed the right behavior, but might lead to breaking changes so adding a flag might be a good intermediate?

**Comment by udaya2899** [comment]
Thanks for the PR. I see this as the expected behavior. However, the maintainers of this project might have a different opinion as well. Would love to hear them. If this is how it's done on `update` but not on `upsert` then it's merely a miss so this fix seems logical.

**Comment by tomschreck** [comment]
I'm experiencing the exact same issue.  We code our repositories to use `upsert` as the means of writing data to a table.  Every entity has a `created_at` and `updated_at` columns.  When the record is first created (on INSERT), the `created_at` and `updated_at` columns are getting populated.  However, subsequent updates to the same record are not modifying the `updated_at` column.  

If these columns are getting populated on the `INSERT` side of the `upsert` equation, then it stands to reason that `updated_at` should also be getting updated on the `UPDATE` side of the `upsert`.

This issue is over a year old.  Has there been any updates on getting this fixed?
