### ISSUE TITLE
Is it possible to create advanced json fields with interface?

### ISSUE THREAD

**Issue by pie6k** [typeorm/typeorm#903]
Lets say I want entity that has single field that has nested shape. It'd be kept in database as json.

Is it possible to manage it with type-orm by setting some interface to an field?

Example would be:
We have `Task` entity that can have very complex recursion rules. It's too complex to create separated field for every attribute of it.

**Comment by pie6k** [comment]
I've found it. It's called `@Embedded` - https://typeorm.github.io/tables-and-columns.html#embeddables

**Comment by pleerock** [comment]
@pie6k if you are using latest typeorm version its better if you refer [this documentation](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#embedded-columns)

**Comment by pie6k** [comment]
@pleerock ok, thanks

**Comment by serg06** [comment]
Updated documentation link: https://typeorm.io/#/embedded-entities
