### ISSUE TITLE
Generated columns with Typorm in PostgreSQL

### ISSUE THREAD

**Issue by GisCat** [typeorm/typeorm#9038]
I want to generate a column with typeorm but it's not working, I am using PostgreSQL and I followed this article, it's said that is supported by typeorm https://wanago.io/2021/11/29/generated-columns-postgresql-typeorm/

this is an example:

 ```
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
@Entity()
class User {
  @PrimaryGeneratedColumn()
  public id: number;
 
  @Column()
  public firstName: string;
 
  @Column()
  public lastName: string;
 
  @Column({
    generatedType: 'STORED',
    asExpression: `'firstName' || ' ' || 'lastName'`
  })
  fullName: string;
}
```
any idea how to do it ?

**Comment by strongpauly** [comment]
We have a similar column, but with a nullable requirement for all name fields.  We got it to work with this definition:
```typescript
@Column({
        nullable: true,
        type: 'varchar',
        generatedType: 'STORED',
        asExpression: /*sql*/ `
    CASE WHEN "firstName" IS NULL AND "lastName" IS NULL
        THEN NULL
    WHEN "firstName" IS NULL
        THEN "lastName"
    WHEN "lastName" IS NULL
        THEN "firstName"
    ELSE
        "firstName" || ' ' || "lastName"
    END`
    })
```

**Comment by GisCat** [comment]
Thank you, I found I was using an old version of Typeorm (@0.2.28) and the feature was supported in postgres in the version @0.2.42
