### ISSUE TITLE
Using closure tables without @TreeLevelColumn will always fail on insert

### ISSUE THREAD

**Issue by martinschleiss** [typeorm/typeorm#904]
Hi,

the issue can be seen on the following line:
https://github.com/typeorm/typeorm/blob/51caf9fe30462ab44eacab69dbff1a4882bfd1f1/src/driver/postgres/PostgresQueryRunner.ts#L315

There should be a check using `hasLevel` otherwise you'll get the following error on insert:

> QueryFailedError: column "level" does not exist

Other functions which call `insertIntoClosureTable` probably have to be updated as well because they dependent on the returned number.

**Comment by martinschleiss** [comment]
Looking at all database drivers, the issue seems to exist everywhere.

**Comment by pleerock** [comment]
Are you able to send a PR?

**Comment by martinschleiss** [comment]
Is submitted
