### ISSUE TITLE
how can i use SUM() add condition?

### ISSUE THREAD

**Issue by ykxhzfj** [typeorm/typeorm#9045]
i want to use SUM() add condition, for example, 
`repo.createQueryBuilder('user)
.select('user.id as id)
.addSelect('SUM(where sex=male, age)', 'age')
.addSelect('SUM(where sex=female, age)', 'age')
.getRawMany();
`
i want to get result as follows:
id ,  sum(male's age), sum(female's age)
what should i write

**Comment by AlexMesser** [comment]
see this issue #673.

Also for questions / general support, please check out our [Slack channel](https://join.slack.com/t/typeorm/shared_invite/zt-uu12ljeb-OH_0086I379fUDApYJHNuw), [StackOverflow](https://stackoverflow.com/questions/tagged/typeorm) or check [TypeORM's documentation](https://typeorm.io).
