### ISSUE TITLE
Are ManyToMany and OneToMany relations nullable by default?

### ISSUE THREAD

**Issue by willyfwonka** [typeorm/typeorm#9048]
Issue type:

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[x] postgres
[ ] cockroachdb
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

TypeORM version:

[ ] latest
[ ] @next
[x] 0.2 (or put your version here)

```js
@Entity()
class Person {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToMany(() => Car, (c) => c.person)
  cars: Car[];
  
  @ManyToMany(() => Person, (p) => p.friends)
  @JoinTable()
  friends: Person[];
}

@Entity()
class Car {
  @PrimaryGeneratedColumn()
  id: number;
  
  @Column()
  model: string;
  
  @ManyToOne(() => Person, p.cars)
  @JoinColumn()
  person: Person;
}
```

So let's say I have two entities like the above, should I explicitly put the option `{ nullable: true }` to `ManyToMany` and `OneToMany` columns? Are those two relation types nullable by default since they represent an Entity array and let's say a `Person` entity may never have a `Car` or a `Friend` which will return an empty array, which may be a falsy value but it is not `null` at the end of the day.

**Comment by danyonedwards** [comment]
We are also facing the same issue where an `@OneToMany` with `{nullable: true}` is returning an empty array when entities don't exist instead of returning `null`

**Comment by willyfwonka** [comment]
I am not sure but line `93` in file `src/metadata/ColumnMetadata.ts` indicates that `isNullable` (which is `nullable` as an argument) is `false` by default. I think this piece of information resolves this issue.
