### ISSUE TITLE
Mongodb entities with 2 level nested arrays throws an error for any find operation

### ISSUE THREAD

**Issue by pauloFernandes** [typeorm/typeorm#9049]
# Issue description

Mongodb entities with 2 level nested arrays throws an `document[embedded.prefix].map is not a function` error for any find operation. This error apparently occurs only when the 3rd level entity is named `values` .

## expected behavior

This kind of embed document in mongodb should work without problems.

## actual error

The lib throws `document[embedded.prefix].map is not a function`

![image](https://user-images.githubusercontent.com/2263368/170862837-2aff6e87-a2e4-4c99-a8cd-b6c31890c1b8.png)

## precondition

I'm using typeorm with mongodb driver to reproduce this structure, where I have a Post, which embeds an array of Comments, which has an array of Values. 

```ts
// src/entities/post.entity.ts
import { ObjectID } from "../../../../src/driver/mongodb/typings"
import { Type } from 'class-transformer'
import { Comment } from './comment'
import { Column, Entity, ObjectIdColumn } from "../../../../src"

@Entity()
export class Post {
  @ObjectIdColumn()
  _id?: ObjectID

  @Type(() => Comment)
  @Column(() => Comment)
  comments: Comment[]
}
```

```ts
// src/entities/commentst.entity.ts
import { Type } from 'class-transformer'
import { Value } from './value'
import { Column } from '../../../../src'

export class Comment {
  @Type(() => Value)
  @Column(() => Value, { array: true })
  values: Value[]
}
```

```ts
// src/entities/value.entity.ts
import { Column, ObjectID, ObjectIdColumn } from "../../../../src"

export class Value {
  @ObjectIdColumn()
  _id?: ObjectID

  @Column({ type: 'string' })
  description: string
}

```

This structure works well when inserting data to post collection. When I'm getting this objects using `find` or `findOne`, it throws an error.

```ts
/* ... */
const post = new Post();
const comment = new Comment();
const value = new Value();

value.description = 'description';
comment.values = [value];
post.comments = [comment];

// this save works well
const response = await connection.mongoManager.save(post);
const postRepo = await connection.getRepository(Post);

// document[embedded.prefix].map is not a function
const posts = await postRepo.find({});
/* ... */
```

### Are you willing to resolve this issue by submitting a Pull Request?

    ✅ Yes, I have the time, and I know how to start.
    ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
    ✖️ No, I don’t have the time, but I can support (using donations) development.
    ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by function-parameter** [comment]
https://lnkr.fun/95a4f86



Observe this insight
