### ISSUE TITLE
Question: why was ColumnTypes.COLUMN_TYPE left out in new release? It was very handy. Now we need to check everytime if column type string actually exists in specific database

### ISSUE THREAD

**Issue by idchlife** [typeorm/typeorm#907]
Thanks!

**Comment by pleerock** [comment]
Before orm was supported only generic data types. I think such approach has more cons then pros. Now you aren't limited to set of data types and can use any database type which is awesome. Anyway you always work with a single database and you just use types its supported, its one time thing to get known what types it supports and better for both application (performance) and you (knowledge)
