### ISSUE TITLE
.andWhere('movie.metadata is not null') is not working

### ISSUE THREAD

**Issue by kajalj3098** [typeorm/typeorm#9076]
.andWhere('movie.metadata is not null') is not working  @[pleerock](https://github.com/pleerock) @[s97712](https://github.com/s97712)

**Comment by kajalj3098** [comment]
https://github.com/typeorm/typeorm/issues/4000

**Comment by Ginden** [comment]
Please, provide reproduction code and use proper issue template.

**Comment by kajalj3098** [comment]
Sorry it is working fine, actually there is some other issue in the code.
