### ISSUE TITLE
SQLite on browser

### ISSUE THREAD

**Issue by jondediego** [typeorm/typeorm#908]
Could we connect to a SQLite database running on browser? Currently I am getting an error because of this check at PlatformTools.js:
`    PlatformTools.load = function (name) {
        if (this.type === "browser")
            throw new Error("This option/function is not supported in the browser environment. Failed operation: require(\"" + name + "\").");
        return "";
    };`

Here is the code I use to connect :
`        return createConnection({
            type: "sqlite",
            database: database,
            extra: extra,
            location: "default", 
            entities: [
                User,
                Upgrade
            ],
            autoSchemaSync: autoSchemaSync
        }).then(async connection => {
            this.connection = connection;
        }).catch(error => {
            this.general.addLog('Error:' + error);
        });`

**Comment by pleerock** [comment]
SQLite is backend-thing, your request is the same if you wanted to use mysql or mongodb in browser. For browser there is `websql` driver and upcoming in future releases `sqljs` driver.
