### ISSUE TITLE
OR Operator

### ISSUE THREAD

**Issue by Alvaro948** [typeorm/typeorm#9081]
## Issue Description

Since at least versión 0.3.6, and according to the [documentation](https://typeorm.io/find-options), "OR" operator seems to be failing

```typescript
repository.find({
    where: [{ node: Equal(node.id) }, { node: IsNull() }]
}); // Does not work, generates empty where clause
```

```typescript
repository.find({
    where: [{ node: Equal(node.id) } }]
}); // Does not work either, generates empty where clause
```

But this works fine

```typescript
repository.find({
    where: { node: Equal(node.id) } 
});
```

### Expected Behavior

The example provided in the documentation should work

### Actual Behavior

The previous examples generate this SQL query

```sql
SELECT
  `RankEntity`.`id` AS `RankEntity_id`,
  `RankEntity`.`name` AS `RankEntity_name`,
  `RankEntity`.`node` AS `RankEntity_node`
FROM `ranks` `RankEntity`
WHERE ()
```

### Steps to Reproduce

1. Use the provided code snipets

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Mac OS         |
| Node.js version     | 16.13.0  | 
| Typescript version  | 4.7.3 | 
| TypeORM version     | 0.3.6 | 

### Additional Context

No additional context

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by stouch** [comment]
I'm experiencing the same :  
```{
        relations: ['organization'],
        where: [
          { organization: { id: IsNull() } },
          { organization: { id: organizationId } },
        ]
      }```

neither

```{
        relations: ['organization'],
        where: [
          { organization: IsNull() },
          { organization: { id: organizationId } },
        ]
      }```

**Comment by Alvaro948P4Q** [comment]
I belive this is not the OR operator, in fact is a bad usage and the bug reported here https://github.com/typeorm/typeorm/issues/8890

The correct way would be:

```ts
repository.find({
    where: [{ node: { id: Equal(node.id) }}, { node: IsNull() }]
});
```
