### ISSUE TITLE
beforeUpdate / afterUpdate does not work if only a relation changes

### ISSUE THREAD

**Issue by jbjhjm** [typeorm/typeorm#9090]
## Issue Description

I tracked down a issue with a EntitySubscriber not being called.
Turns out that the *Update events will only fire if there actually was a change on the entity's own data fields.
If it was saved with the only changes being within a relation (e.g. a UserEntity that has been assigned to a new UserGroup),
typeOrm will think nothing has been changed and will not call the beforeUpdate / afterUpdate hooks.

### Expected Behavior

subscribers should be called, even if the only changes were within a relation.

This one goes to @pleerock : 
Do you agree that this should is a bug that should be corrected, or is this wanted behavior for some reason?

### My Environment

Right now still using 0.2.37 running on node 14.17.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by spotykatch** [comment]
Can you please provide some code or even a sandbox (that is better)? That sounds like a real badass bug and a lot of work to do if it's not fixed.

**Comment by jbjhjm** [comment]
Created a test 

```ts
@Entity()
export class Category {
    @PrimaryGeneratedColumn()
    id: number;
    @Column()
    name: string;
    @OneToMany(type => Post, post => post.category)
    posts: Post[];
}

@Entity()
export class Post {
    @PrimaryGeneratedColumn()
    id: number;
    @Column()
    title: string;
    @ManyToOne(type => Category, { eager: true })
    category: Category[];
}

@EventSubscriber()
export class MockSubscriber implements EntitySubscriberInterface {
	calledData: any[] = [];
	count = 0;	
	reset() {
		this.calledData = [];
		this.count = 0;
	}	
	listenTo() {
		return Category;
	}	
	afterUpdate(event: UpdateEvent<any>): void {
		this.count++;
		this.calledData.push(event.queryRunner.data);
	}
}

describe("entity subscriber > subscriber on relation update", () => {
	let connections: Connection[];

	before(async () => connections = await createTestingConnections({
		entities: [ Category, Post ],
		subscribers: [ MockSubscriber ],
		dropSchema: true,
		schemaCreate: true,
		enabledDrivers: [ "mariadb" ] // should happen with all drivers, just had only mariadb easily available
	}));

	beforeEach(() => {
		for (const connection of connections) {
		    (connection.subscribers[0] as MockSubscriber).reset();
		}
	});
	after(() => closeTestingConnections(connections));

	it("subscriber is called on relation update", async () => {
		const connection = connections[0];
		const subscriber = connection.subscribers[0] as MockSubscriber;		

		// prepare
		const category = new Category();
		const post1 = new Post();
		category.name = "test category";
		post1.title = "Test post";
		category.posts = [post1];
		const persistedCat = await connection.manager.save(category);

		// now run the update that should trigger the afterUpdate subscriber
		const post2 = new Post();
		post2.title = "Additional post";
		persistedCat.posts.push(post2);	

		// persistedCat.name = "Other title"; // when uncommenting the name update, change will be detected + subscriber will be called
		await connection.manager.save(persistedCat);

		// fails because subscriber has not been called
		expect(subscriber.count).to.be.eql(1);
		
	});

});


```

**Comment by spotykatch** [comment]
I've made some changes to the tests. I guess it should look like that
```ts
// category.ts
@ManyToMany(type => Post, post => post.category, { cascade: true }) // ManyToMany as we have arrays on both sides
@JoinTable() // Should be on one of the sides as we have ManyToMany relation
posts: Post[];

// post.ts
@ManyToMany(type => Category, category => category.post, { eager: true, onDelete: "CASCADE" }) // ManyToMany as we have arrays on both sides
category: Category[];
```
but tests are still failing
Seems like I've missed something

**Comment by pleerock** [comment]
`beforeUpdate` / `afterUpdate` are called only for changed columns, not relations. It is by design. If we want to implement the proposed functionality we'll have to bring multiple new queries for each relation in the entity which is not desired by users.

**Comment by jbjhjm** [comment]
I see, thx for clarifying @pleerock. 
Will search for a different way of implementing the functionality that I require.

**Comment by mahmoudzeyada** [comment]
any workaround to this

**Comment by jbjhjm** [comment]
@mahmoudzeyada not by now. I plan to use a customized repository class to handle this.
However this is currently blocked by the weak custom repository implementation. See here for details:
https://github.com/typeorm/typeorm/issues/9312

**Comment by jbjhjm** [comment]
as Pleerock stated above this is intended behavior and won't be implemented. Also there's no simple solution to implement this feature.

**Comment by SnowingFox** [comment]
> `beforeUpdate` / `afterUpdate` are called only for changed columns, not relations. It is by design. If we want to implement the proposed functionality we'll have to bring multiple new queries for each relation in the entity which is not desired by users.

so why not give a option for user to decide whether turn it on? 😅

**Comment by Jrockbritto** [comment]
> any workaround to this

Probably too late to help you, but I've managed to trigger it simply by updating the updated_at column manually:

const updatedRecord= this.repository.create({...dataToUpdate, updatedAt: new Date()})


await this.repository.save(updatedRecord)

something like this.

**Comment by GGlielmi** [comment]
A possible but verbose solution is to use a separate entity for join table

**Comment by Emmytobs** [comment]
Still didn't work for me: https://github.com/typeorm/typeorm/issues/9090#issuecomment-1965670354

I'm only seeing the `updated_at` column.

**Comment by spotykatch** [comment]
> Still didn't work for me: [#9090 (comment)](https://github.com/typeorm/typeorm/issues/9090#issuecomment-1965670354)
> 
> I'm only seeing the `updated_at` column.


> `beforeUpdate` / `afterUpdate` are called only for changed columns, not relations. It is by design. If we want to implement the proposed functionality we'll have to bring multiple new queries for each relation in the entity which is not desired by users.
