### ISSUE TITLE
Add support for ioredis v5

### ISSUE THREAD

**Issue by VygantasVoltasIT** [typeorm/typeorm#9092]
## Feature Description

It would be nice to have a possibility to upgrade ioredis into version 5

### The Problem

Two months ago ioredis v5 was released and until now I cannot update to v5 since typeorm only supports v4

### The Solution

Add support for ioredis v5

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    |  yes           |
| `aurora-postgres` | yes            |
| `better-sqlite3`  | yes            |
| `cockroachdb`     | yes            |
| `cordova`         | yes            |
| `expo`            | yes            |
| `mongodb`         | yes            |
| `mysql`           | yes            |
| `nativescript`    | yes            |
| `oracle`          | yes            |
| `postgres`        | yes            |
| `react-native`    | yes            |
| `sap`             | yes            |
| `spanner`         | yes            |
| `sqlite`          | yes            |
| `sqlite-abstract` | yes            |
| `sqljs`           | yes            |
| `sqlserver`       | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by mdwekat** [comment]
Facing the same issue
