### ISSUE TITLE
Typeorm global where clause

### ISSUE THREAD

**Issue by sampaiorafael** [typeorm/typeorm#9099]
in my database, all tables have a boolean column "active" which is used to know if the row should be returned or not on the query.

As we use TypeORM as our back-end ORM, Is it possible to have a global statement/clause that is "concatenated" on every query made by TypeORM, like:

WHERE column.active = true

So, like this, the rows with the column active with 0 as a value, don't return on TypeORM queries during the main application flow, instead of rewriting it on every queryBuilder or repositories premade queries like "find" or "findOrfail" where we dont even write anything.

Need to be in TypeORM because it should be returned on manual queries on sgbd and things like this
We use postgre as SGBD
Typeorm v0.2.24

Thank you!!!

**Comment by Ginden** [comment]
Duplicate: https://github.com/typeorm/typeorm/issues/1601
