### ISSUE TITLE
Question: How does Version column works ? Is it compatible with rowversion on MSSQL ?

### ISSUE THREAD

**Issue by iz-iznogood** [typeorm/typeorm#910]
Hi, I would like to use optimistic concurrency checking. How can I set it up ?
Is the version column updated by TORM or it expects the RDBMS to update it ? 
Is it used in update and delete (?) statements to check concurrency or I would have to implement this somehow ?

I saw that it is mapped to int for mssql. 
Will this work if I use rowversion for datatype and map it to an int ?
Is it cross db compatible ?

Thanks !!!!

**Comment by pleerock** [comment]
Its updated by typeorm as I remember. Take a look [these tests](https://github.com/pleerock/typeorm/blob/f919ded6733efee00c71bfe4e558c61aba3c5c07/test/functional/query-builder/locking/query-builder-locking.ts#L143) for an example.

**Comment by iz-iznogood** [comment]
Ok, I will take a look,

thanks
