### ISSUE TITLE
SQLjs 'cannot commit - no transaction is active'

### ISSUE THREAD

**Issue by Ainias** [typeorm/typeorm#9100]
## Issue Description

When autosave is used with sqljs and localforage, sometimes there is an error with the message `'cannot commit - no transaction is active`. As far as I can tell, it happens when two or more write-requests are made at the same time. Both start, then the first one ends, the autosave is called. The autosave exports the sqljs-database, which closes the transaction silently. Then the second one ends and tries to close the connection, which is not open anymore. Therefore the error is thrown.
Potentially can this resolve in an unwanted state. If I try to save A & B in separate repositories and B has a dependency C, which must also be saved, then it can happen, that A & B are saved, then the DB is exported, tries to save C, but there is an error in C, such that it tries to rollback the transaction containing B & C. But there is no transaction anymore, which means that the changes in B are saved, but not the one in C and therefore the data is not correct.

### Expected Behavior

Call autosave only when no transaction is active in order to not run into errors

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          | Linux
| Browser     | Brave/Chrome    | 
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.3.5  | 
| sql.js | 1.7.0 |
| localforage | 1.10.0

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | yes            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by BARNZ** [comment]
Running into the same problem as well ever since upgrading to the latest version of TypeORM.

Triggered in my case by simply calling `await Entity.save(...)` when using `sql.js` driver with `autosave` as mentioned above.

![image](https://user-images.githubusercontent.com/2202345/173772929-fc30f943-8c0c-414c-9ba8-6b4eaf8d2f55.png)
