### ISSUE TITLE
"find" issue after add DateColumn to entity

### ISSUE THREAD

**Issue by MrSaeedNasiri** [typeorm/typeorm#9102]
### Expected Behavior

Expected to find user account
```typescript
const user = await AppDataSource.manager.findOneBy(User, {
  name: "name",
});
const account = await AppDataSource.manager.findOneBy(Account, {
  user: user,
});
```

### Actual Behavior

before adding CreateDateColumn / UpdateDateColumn to entity ( User, Account ) everything work fine.

```
// after add this to User and Account Entity 

  @CreateDateColumn({ type: "timestamptz" })
  created_at!: Date;

  @UpdateDateColumn({ type: "timestamptz" })
  updated_at!: Date;
```
### Result after adding DateColumn to Entity

1. User found correctly
2. Account not found any result

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    Windows 11      |
| Node.js version     | 16.15.0  | 
| Typescript version  | 4.6.3 | 
| TypeORM version     | 0.3.6 | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by spotykatch** [comment]
Tested it with only one date column in `where` and it seems like a bug with dates that depends on database you're using. Have seen some issues here. Insert date !== select date.

On the other hand, I guess you should not use find like that.
```ts
const account = await AppDataSource.manager.findOneBy(Account, {
  user: { id: user.id },
});
```
If you have a unique id, you do not need to search for something else.

**Comment by spotykatch** [comment]
As you checked "Yes, I have the time, but I don't know how to start. I would need guidance." you can start a draft by just making a test that fails. I will support it. @pleerock is also into this. Please, give me a reply, course I have to start a draft by myself if you don't.
