### ISSUE TITLE
No business logic has been written for RecoverEvent and SoftRemoveEvent

### ISSUE THREAD

**Issue by gmmkmtgk** [typeorm/typeorm#9108]
No business logic has been written for RecoverEvent and SoftRemoveEvent

You can see for insertevent everthing is mentioned 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/51493190/173535141-79409890-6eb7-41a8-816e-c0ac7551bf49.png">

but for RecoverEvent  nothing is their 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/51493190/173535331-3bbd4443-e724-4375-878e-69bcf7526d63.png">

I came to know about that when I imported it 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/51493190/173535791-97cee1cd-ff44-46ce-9eeb-d277cffb6a62.png">

**Comment by gmmkmtgk** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/51493190/173536033-36f6e275-760a-45b9-894b-8c63ba272d0f.png">
InsertEvent, RemoveEvent, UpdateEvent was not giving that problem

**Comment by spotykatch** [comment]
Seems like re-export in src/index.ts is missing. Maybe it was found redundant after pr with soft-remove and recover subscribers was merged and no docs were changed.
You can use `RemoveEvent` instead. It's the same. Both `RecoverEvent` and `SoftRemoveEvent` are just extending it.

**Comment by spotykatch** [comment]
Made a pr to fix it. I cant't test it due to my location. I've tested this issue locally, but all the test are running forever. So I'm not sure it will be accepted.
