### ISSUE TITLE
[Bug] Yargs migrations:generate flags get crossed

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#911]
Using the command `typeorm migrations:generate -n initialMigration --connection "osgroup-innova" -d src/migrations/ -cf ormconfig.json` generates errors, due to the `-cf` being taken by `yargs` as a flag for connections, in connections i get the following connection name `[ 'osgroup-innova', true]` which is taking in account the `c` in `-cf`, here's the log of the args in the generate command:
![image](https://user-images.githubusercontent.com/9698639/30603634-c304f106-9d2d-11e7-8f7e-5ae363eacf14.png)

To illustrate the point here's the same command without `-cf` part:
![image](https://user-images.githubusercontent.com/9698639/30603719-02cdf526-9d2e-11e7-81e9-0c1d382c2f36.png)

**Comment by luchillo17** [comment]
If i recall correctly you indeed can use alias of 1 char, however yargs takes the `-cf` as 2 flags and also as the `cf` command, that's why it's being taken in account for both the flag and the config file.

**Comment by luchillo17** [comment]
You think?:
https://github.com/typeorm/typeorm/blob/master/gulpfile.ts#L22
https://github.com/typeorm/typeorm/blob/master/src/commands/MigrationGenerateCommand.ts#L17-L36

Those are 2 examples of yargs on `TypeORM`'s code, `yargs` is all over the `TypeORM`'s code.

**Comment by pleerock** [comment]
ahhh sorry I confused yargs with facebook's yarn 😖 

Looks like problem is in `cf` which overlaps with simply `c`. Probably we need to remove `cf` and instead use a long name `config`

**Comment by luchillo17** [comment]
The issue is with the alias, maybe change the alias to `-f` for file to avoid overlapping.

**Comment by luchillo17** [comment]
Actually why don't you try putting the option as the full word and the alias as the shorthand form, like:
```ts
yargs
    .option("connection", {
        alias: "c",
        default: "default",
        describe: "Name of the connection on which run a query."
    })
```

It might make a difference in the way `yargs` detects the args.

**Comment by pleerock** [comment]
this is fixed, you can use `f` flag instead
