### ISSUE TITLE
repository.Find() never resolves promise with expo-sqlite

### ISSUE THREAD

**Issue by ROODAY** [typeorm/typeorm#9113]
## Issue Description

I'm using typeorm in a React Native Expo app, using the expo-sqlite backend (created with the default expo-go template). When I try to call repository.find() to load all entries from the database, nothing happens. Adding some log statements revealed that the promise for find() never resolved.

### Expected Behavior

`await repository.find()` would return an array of whatever is in the database, including an empty array if nothing is there.

### Actual Behavior

When await repository.find() is called, nothing happens (app doesn't freeze, but the promise never resolves).

Here are some relevant code snippets (`import "reflect-metadata"` is called at the top of App.tsx before other imports, and tsconfig.json includes both `experimentalDecorators` and `emitDecoratorMetadata` set to true.):

First I have a storage layer class with the following code:
```typescript
import StorageLayer from "../StorageLayer";
import { DataSource, Repository } from 'typeorm/browser';

import Task from "../../../entities/Task";

export class SQLiteStorageLayer implements StorageLayer {
  private taskRepository: Repository<Task>;

  constructor(dataSource: DataSource) {
    this.taskRepository = dataSource.getRepository(Task);
  }

  async addTask(task: Task): Promise<void> {
    await this.taskRepository.save(task);
  }

  async getAllTasks(): Promise<Task[]> {
    return await this.taskRepository.find();
  }

  async getTaskById(id: string): Promise<Task | null> {
    return await this.taskRepository.findOneBy({ id: id });
  }

  async updateTask(task: Task): Promise<void> {
    await this.taskRepository.save(task);
  }

  async deleteTaskById(id: string): Promise<void> {
    await this.taskRepository.delete({ id: id });
  }
}


const SQLiteStorageLayerFactory = async (): Promise<SQLiteStorageLayer> => {
  const dataSource = new DataSource({
    database: "prioTasks",
    driver: require('expo-sqlite'),
    entities: [
      Task
    ],
    synchronize: true,
    type: "expo",
  })
  dataSource.initialize();
  return new SQLiteStorageLayer(dataSource);
}

export default SQLiteStorageLayerFactory;
```

App.tsx looks like this:
```typescript
export default function App() {
  const isLoadingComplete = useCachedResources();
  const colorScheme = useColorScheme();
  const [storageLayer, setStorageLayer] = useState<StorageLayer | undefined>()

  useEffect(() => {
    const connectToStorageLayer = async () => {
      const storageLayer = await SQLiteStorageLayerFactory();
      setStorageLayer(storageLayer);
    }

    connectToStorageLayer();
  }, []);

  if (!isLoadingComplete) {
    return null;
  } else {
    return (
      <SafeAreaProvider>
        <StorageLayerContext.Provider value={storageLayer}>
          <Navigation colorScheme={colorScheme} />
          <StatusBar />
        </StorageLayerContext.Provider>
      </SafeAreaProvider>
    );
  }
}
```

Then in the main screen that is loaded first upon app start, there is this function:
```typescript
const loadTasks = async () => {
    setLoading(true);
    const tasks = await storageLayer?.getAllTasks();
    if (tasks !== undefined) {
      setTasks(tasks);
    }
    setLoading(false);
  }
```

### Steps to Reproduce

1. Init an expo project with `expo init my-project`
2. Install typeorm following the readme here
3. Create a class to abstract calls to the typeorm repository
4. Try calling `await repository.find()`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Windows 10       |
| Node.js version     | 16.14.0  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.3.6  | 
| React Native version |0.64.3|

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | yes            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by ROODAY** [comment]
I was able to get it to work, I think the main issue was that I didn't have the [patch](https://github.com/typeorm/expo-example/tree/master/patches) from the expo-example. Can this please be added to the documentation? It wasn't clear for someone new to typeorm/patches in general that this was required.

**Comment by allandiego** [comment]
You can use main tree, there are a commit to fix the infinite loop
https://github.com/typeorm/typeorm/pull/8984
