### ISSUE TITLE
applying aliases in select statement doesn't return the column

### ISSUE THREAD

**Issue by ctfrancia** [typeorm/typeorm#9114]
I haven't been able to find a solution that works for me yet. Whenever I try to apply an alias to a column the column in question is omitted in the return value, all other fields are returned as expected and I've tried various different ways.
```typescript
export class LeadsData {
  constructor(
    @InjectRepository(LeadsData, 'db-conn')
    private readonly leadsDataRepo: Repository<LeadsData>
    ) {}

    public async getData(lead: number): Promise<any> {
      const q = await this.leadsDataRepo
        .createQueryBuilder('leads-data')
        .select('leads-data.user', 'updatedByUser')
        .where('leads-data.lead = :lead', { lead })
        .getMany()

      console.log(q)
      return q
    }
}
```

this generates the following sql query:
```sql
SELECT `leads-data`.`user` AS 'updateByUser' FROM `leads-data` `leads-data` WHERE `leads-data`.`lead` = ?
```

when taking the raw query and running it against the database the correct data is returned and the column is aliased correctly.

however, when going through the ORM the resulting payload from the query is `[]`

from what I've read in the [docs](https://typeorm.io/select-query-builder#getting-values-using-querybuilder) this should work

**Comment by ctfrancia** [comment]
I have to maintain the data source injected or NestJS can't resolve the dependency

**Comment by lhousaine** [comment]
As you want to select just specific fields with alias, the return data is not an entity, but instead it's a raw data, so to resolve the issue you should use getRawMany() instead of getMany().
You can read more about this by referring to in the official documentation :
[https://typeorm.io/select-query-builder#getting-raw-results](https://typeorm.io/select-query-builder#getting-raw-results)

**Comment by ctfrancia** [comment]
Yea I had to modify that to use `getRawMany()` but the problem with this is that I have to apply additional logic to:
```typescript
export class LeadsData {
  constructor(
    @InjectRepository(LeadsData, 'db-conn')
    private readonly leadsDataRepo: Repository<LeadsData>
    ) {}

    public async getData(lead: number): Promise<any> {
      const raw = await this.leadsDataRepo
        .createQueryBuilder('leads-data')
        .select('leads-data.user', 'updatedByUser')
        .where('leads-data.lead = :lead', { lead })
        .getRawMany()

      return JSON.parse(JSON.stringify(raw).replaceAll('leads-data_', ''))
    }
}
```

it works but it would be nicer if there was some internal logic or option for this.
