### ISSUE TITLE
mongodb support directConnection

### ISSUE THREAD

**Issue by Liiked** [typeorm/typeorm#9116]
### The Problem

The company DevOps configurated the mongodb replica in only one member mode, set primary member host with "localhost:27017" which cause `MongoServerSelectionError: Server selection timed out after 30000 ms` error in mongodb.

If I just use `mongodb` package with `directConnection=true`, it works fine.

### The Solution

Add `directConnection` in `validOptionNames`.

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | yes |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by fatihaziz** [comment]
Hello, i want to follow up this issue here:
https://github.com/typeorm/typeorm/issues/10023

Thank you
