### ISSUE TITLE
When using "findOneOrFail" or "findOne", TypeORM runs a preselect query and adds unnecessary fields to query.

### ISSUE THREAD

**Issue by roku-on-it** [typeorm/typeorm#9126]
## Issue Description
When using Active Record for querying an entity and its relation using the `relation` option in `FindOneOptions` options TypeORM adds an extra id filter (` WHERE ( ("User"."id" = $1) )  AND ( "User"."id" IN ($2) )`) to generated query while id is already in the query, and runs a preselect query. This only happens when using methods like `findOne` or `findOneOrFail`. Using the `find` method the query works as expected and doesn't run a preselect query.
### Expected Behavior

I expect TypeORM to generate a query like this when I query with an Active Record model.
```sql
query: SELECT "User"."id" AS "User_id",
       "User"."email" AS "User_email",
       "User"."deletedAt" AS "User_deletedAt",
       "User__User_settings"."id" AS "User__User_settings_id",
       "User__User_settings"."theme" AS "User__User_settings_theme" 
FROM "user" "User"
         LEFT JOIN "settings" "User__User_settings" ON "User__User_settings"."id" = "User"."id"
WHERE (("User"."id" = $1))
  AND ("User"."deletedAt" IS NULL) -- PARAMETERS: ["5bc723c4-53bf-4a42-99b2-ecd226b4ba49"]
```

### Actual Behavior
```sql
query: SELECT DISTINCT "distinctAlias"."User_id" AS "ids_User_id"
FROM (SELECT "User"."id" AS "User_id",
 "User"."email"AS "User_email",
 "User__User_settings"."id"AS "User__User_settings_id",
 "User__User_settings"."theme" AS "User__User_settings_theme"
  FROM "user" "User"
   LEFT JOIN "settings" "User__User_settings" ON "User__User_settings"."id" = "User"."id"
  WHERE (("User"."id" = $1))
AND ("User"."deletedAt" IS NULL)) "distinctAlias"
ORDER BY "User_id" ASC
LIMIT 1 -- PARAMETERS: ["5bc723c4-53bf-4a42-99b2-ecd226b4ba49"]

query: SELECT "User"."id" AS "User_id",
       "User"."deletedAt" AS "User_deletedAt",
       "User"."email" AS "User_email",
       "User__User_settings"."id" AS "User__User_settings_id",
       "User__User_settings"."theme" AS "User__User_settings_theme"
FROM "user" "User"
         LEFT JOIN "settings" "User__User_settings" ON "User__User_settings"."id" = "User"."id"
WHERE (("User"."id" = $1))
  AND ("User"."deletedAt" IS NULL)
  AND ("User"."id" IN ($2)) -- PARAMETERS: ["5bc723c4-53bf-4a42-99b2-ecd226b4ba49","5bc723c4-53bf-4a42-99b2-ecd226b4ba49"]
```
### Steps to Reproduce

1. Run a select query using the Active Record model
2. Enable query logging in config.
3. Check the console to see the generated query

Example query
```typescript
User.findOneOrFail({
  where: { id: '5bc723c4-53bf-4a42-99b2-ecd226b4ba49' },
  relations: {
  settings: true,
  },
});
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 11 |
| Node.js version     | v16.15.1| 
| Typescript version  | 4.7.3| 
| TypeORM version     | 0.3.6| 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by ikonst** [comment]
To end up making two queries, these two conditions have to hold:
1. A query with a limit ("take") and/or offset ("skip"), **and**
2. A query with 1+ joins.

In your case (as well as mine), you're making a limit query because you do `findOne` and you add a relation (the user settings) so you join.

The reason TypeORM does it, is for the generalized case, when you query your main table over something that's not a primary key, and your relation might be one-to-many. They're concerned that e.g. a query that wants 2 users will end up with 4 rows (because of the one-to-many nature of the relationship) and wouldn't get a consistent result.

I would imagine there's a better way to address that (e.g. [DISTINCT ON](https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT) in Postgres), but regardless, TypeORM would do well to avoid doing this extra query when

1. querying on a primary key, **and**
2. joining on all primary keys

which in my case (and I assume your case) is true.

**Comment by roku-on-it** [comment]
Thanks, that makes sense.
