### ISSUE TITLE
Is it possible to validate model before save?

### ISSUE THREAD

**Issue by pie6k** [typeorm/typeorm#913]
Let's consider basic example: user has email address. 

Would it be possible at typeorm level to validate that email is correct before field is saved to the database? 

Formally - email is normal string, but in very specific format. It would be useful in many cases like emails, passwords length etc, additional json fields shape checks etc.

**Comment by pleerock** [comment]
general validation isn't part of this library. Use [class-validator](https://github.com/pleerock/class-validator) for your purpose.

**Comment by crutchcorn** [comment]
Using class validator, is there a way to run a pre-save function for an entity in TypeORM? (say, to run the validation for class validator)

**Comment by crutchcorn** [comment]
@pleerock not wanting to open a new issue, but my question is relevant once more as I'm continuing converting code from a mongoose project to TypeORM. Is there a way to run a function before saving a model?

**Comment by pleerock** [comment]
what about [listeners and subscribers](http://typeorm.io/#/listeners-and-subscribers)?

**Comment by crutchcorn** [comment]
That seems to be exactly what I need, thanks!

**Comment by nahue086** [comment]
This is an old issue, but for anyone who is still wondering how to implement this, here goes a small hint.

```javascript
import {
  Entity, PrimaryGeneratedColumn, Column, BaseEntity, BeforeInsert, BeforeUpdate,
} from 'typeorm';
import { validateOrReject, IsDefined } from 'class-validator';

@Entity()
export class Category extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  public id: string;

  @Column({ nullable: false })
  @IsDefined()
  public name: string;

  // HOOKS
  @BeforeInsert()
  @BeforeUpdate()
  async validate() {
    await validateOrReject(this);
  }
}

```

**Comment by yorickdevries** [comment]
> 
> 
> This is an old issue, but for anyone who is still wondering how to implement this, here goes a small hint.
> 
> ```js
> import {
>   Entity, PrimaryGeneratedColumn, Column, BaseEntity, BeforeInsert, BeforeUpdate,
> } from 'typeorm';
> import { validateOrReject, IsDefined } from 'class-validator';
> 
> @Entity()
> export class Category extends BaseEntity {
>   @PrimaryGeneratedColumn('uuid')
>   public id: string;
> 
>   @Column({ nullable: false })
>   @IsDefined()
>   public name: string;
> 
>   // HOOKS
>   @BeforeInsert()
>   @BeforeUpdate()
>   async validate() {
>     await validateOrReject(this);
>   }
> }
> ```

You don't have to make validate an async function. TypeORM awaits the function before continuing:
This works just as fine:
```
  @BeforeInsert()
  @BeforeUpdate()
  private validate(): Promise<void> {
    return validateOrReject(this);
  }
```

**Comment by adwiens** [comment]
> You don't have to make an async function of validate. TypeORM awaits the function before continuing

Async/await is just syntactic sugar around Promise. The async function implicitly returns Promise<void>. Both ways work because TypeORM awaits the returned Promise before continuing.

**Comment by cesar-pinheiro** [comment]
> > OK. The class-validator library works very well.
> > I just don't know what the "nullable" argument of the "@Column" property is for, and it doesn't work?
> > I did the test with "@Column ({nullable: false})" and it didn't work.
> > ```js
> > import {
> >   Entity, PrimaryGeneratedColumn, Column
> > } from 'typeorm';
> > 
> > @Entity()
> > export class Category extends BaseEntity {
> >   @PrimaryGeneratedColumn('uuid')
> >   public id: string;
> > 
> >   @Column({ nullable: false })
> >   public name: string;
> > 
> > }
> > ```

#

**Comment by lusatiro** [comment]
@cesar-pinheiro, have you solved this issue?

**Comment by percy507** [comment]
> This is an old issue, but for anyone who is still wondering how to implement this, here goes a small hint.
> 
> ```js
> import {
>   Entity, PrimaryGeneratedColumn, Column, BaseEntity, BeforeInsert, BeforeUpdate,
> } from 'typeorm';
> import { validateOrReject, IsDefined } from 'class-validator';
> 
> @Entity()
> export class Category extends BaseEntity {
>   @PrimaryGeneratedColumn('uuid')
>   public id: string;
> 
>   @Column({ nullable: false })
>   @IsDefined()
>   public name: string;
> 
>   // HOOKS
>   @BeforeInsert()
>   @BeforeUpdate()
>   async validate() {
>     await validateOrReject(this);
>   }
> }
> ```

Is this code forget to handle exception?
If validate failed,  I use `try...catch` to throw error.

**Comment by bitpickle** [comment]
For those still looking for a way to do this validation, just add the following code to your main.ts file:

`app.useGlobalPipes(new ValidationPipe());`

So it is not necessary to use hooks, just add decorators to fields. The method mentioned above, for some reason, did not work for me
