### ISSUE TITLE
TypeORM makes an extra database request for each repository.save method call

### ISSUE THREAD

**Issue by zfeed** [typeorm/typeorm#9130]
### Expected Behavior

TypeORM should make in memory difference comparing when saving an entity

### Actual Behavior

When client code calls `repository.save(entity)` method - TypeORM, under the hood, makes an extra query to a database in order to load the same entity and compare it with the being saved one. 

Problems:
1. It makes an extra database request for each save method call
2. It doesn't guaranty that update statement won't be executed when database's entity state is the same as the being saved entity has

### Steps to Reproduce

1. Enable logging in order to see executed queries or put `debugger` [here](https://github.com/typeorm/typeorm/blob/master/src/persistence/SubjectDatabaseEntityLoader.ts#L118)
2. Try to save an entity

```typescript
    const postRepository =  DataSource.manager.getRepository(Post);

    const post = await postRepository.findOneByOrFail({ id: 1 });

    await postRepository.save(post);
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      macOS    |
| Node.js version     | 16.13.2  | 
| Typescript version  | 4.7.4  | 
| TypeORM version     | 0.3.5  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | yes            |
| `aurora-postgres` | yes            |
| `better-sqlite3`  | yes            |
| `cockroachdb`     | yes            |
| `cordova`         | yes            |
| `expo`            | yes            |
| `mongodb`         | yes            |
| `mysql`           | yes            |
| `nativescript`    | yes            |
| `oracle`          | yes            |
| `postgres`        | yes            |
| `react-native`    | yes            |
| `sap`             | yes            |
| `spanner`         | yes            |
| `sqlite`          | yes            |
| `sqlite-abstract` | yes            |
| `sqljs`           | yes            |
| `sqlserver`       | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅  Yes, I have the time, and I know how to start.
 - ✖️  Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment]
This is by design. You can use `manager.insert()` to avoid additional queries.
