### ISSUE TITLE
Error during migration run

### ISSUE THREAD

**Issue by tghpereira** [typeorm/typeorm#9131]
## Issue Description
Cli command shows error when running migrations, dataSource is not recognized in the directory passed by in the -d parameter
```bash
npm run typeorm -- -d ./src/shared/infra/index.ts migration:run
````

Config package.json -> typeorm
```bash
"typeorm": "ts-node-dev -r tsconfig-paths/register ./node_modules/typeorm/cli.js",
````

### Expected Behavior
run and roll back migrations

### Actual Behavior
Terminal output
```bash
PS C:\Users\tghpe\Desktop\gat> npm run typeorm -- -d ./src/shared/infra/index.ts migration:run
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> econsig-gateway@1.0.0 typeorm
> ts-node-dev -r tsconfig-paths/register ./node_modules/typeorm/cli.js "-d" "./src/shared/infra/index.ts" "migration:run"

[INFO] 22:40:31 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.7.4)
Compilation error in C:\Users\tghpe\Desktop\gat\src\shared\infra\index.ts
Error during migration run:
Error: Unable to open file: "C:\Users\tghpe\Desktop\gat\src\shared\infra\index.ts". Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Function.loadDataSource (C:\Users\tghpe\Desktop\gat\src\commands\CommandUtils.ts:22:19)
    at Object.handler (C:\Users\tghpe\Desktop\gat\src\commands\MigrationRunCommand.ts:34:26)
```

### Steps to Reproduce

1 - Simple project, latest version on npm or yarn.
2 - Create Migrations and try to run
```typescript
// example code TS is not needed, just create migrations and try to run them
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    windowns      |
| Node.js version     | v16.15.1  | 
| Typescript version  | 4.3.5  | 
| TypeORM version     | 0.3.6  | 

### Additional Context
No contextual addition required

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | yes            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Wandang** [comment]
I was able to fix this problem by upgrading my ts-node package from 10.4.0 to 10.8.1
