### ISSUE TITLE
getRepostory function is  deprecated

### ISSUE THREAD

**Issue by zeydduran** [typeorm/typeorm#9148]
https://github.com/typeorm/typeorm/blob/ec23922da745fde7c1e7e353777327f40fbaca28/src/commands/InitCommand.ts#L380

**Comment by Stene3** [comment]
With a new DataSource as a connection configuration, use this one instead:

```
datasource.getRepository(Model)
```

**Comment by AlexMesser** [comment]
* `getManager()`, `getMongoManager()`, `getSqljsManager()`, `getRepository()`, `getTreeRepository()`, `getMongoRepository()`, `createQueryBuilder()`
  are all deprecated now. Use globally accessible data source instead:

```ts
export const myDataSource = new DataSource({ /*...*/ })
export const Manager = myDataSource.manager
export const UserRepository = myDataSource.getRepository(UserEntity)
export const PhotoRepository = myDataSource.getRepository(PhotoEntity)
// ...
```
