### ISSUE TITLE
TypeORM with oracledb works with Node.js but not React.js

### ISSUE THREAD

**Issue by GuilhermeLouli** [typeorm/typeorm#9156]
### Expected Behavior
I am trying to create a simple CRUD using React.js with Oracle Database and TypeORM. The objective is to simple execute **npm start** and get a **AppDataSource.query()** to show some data in the console

### Actual Behavior
If I execute the code using only node: **node src/typeORM/test2.js** it works, if I go to Postman I can make requests and get data from the database but when I execute **npm start** it gives me the following error in the chrome browser:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at EntityManagerFactory.create (EntityManagerFactory.ts:15:1)
    at DataSource.createEntityManager (DataSource.ts:600:1)
    at new DataSource (DataSource.ts:139:1)
    at ./src/typeORM/data-source.js (data-source.js:4:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/typeORM/test1.js (data-source.js:29:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
```

### Steps to Reproduce

1. Start a sample React.js project using **npx create-react-app react-demo --use-npm**
2. Run npm install typeorm
3. Run npm install oracledb
4. Download **instantclient-basic** (used version: 21.3.0) from https://www.oracle.com/br/database/technologies/instant-client/winx64-64-downloads.html
5. At **node_modules/oracledb/build/release** paste everything from extracted **instantclient-basic** folder
6. Add following import to App.js:
```node
import { CONSULTING } from './typeORM/test1.js';
```
7. Add below files inside a **src/typeORM** folder

**DATA-SOURCE**
```node
// data-source.js
import { DataSource } from "typeorm"

export const AppDataSource = new DataSource({
  type: "oracle",
  host: "example",
  port: 1521,
  //driver: "expo",
  username: "example",
  password: "example",
  serviceName: "example",
  synchronize: true,
  logging: false,
  entities: [],
  migrations: [],
  subscribers: []
});

export async function initDatabaseConnection() {
  try {
    if (!AppDataSource.isInitialized) {
      await AppDataSource.initialize();
      console.log('AppDataSource connection initialized');
    }
  }
  catch (error) { console.log(' Could NOT initialize AppDataSource\n', error) }
}

initDatabaseConnection();
```

**TEST1**
```node
 // test1.js
import { AppDataSource } from "./data-source.js";

export async function CONSULTING(table, fieldPK, pk) {
  let data;
  console.log(table, fieldPK, pk)
  await new Promise(async resolve => {
    let queryString = "SELECT * FROM " + table;
    if (fieldPK !== "") queryString = queryString + " WHERE  " + fieldPK + " = " + pk

    await AppDataSource.query(queryString)
      .then(result => data = result)
      .then(async () => resolve(await data))
      .catch(err => { console.log('CATCH EXCEPTION: ' + err) })
  })
  return data;
}

```

**TEST2**
```node
// test2.js
import * as Connect from './test1.js'
import express from 'express'

const server = express();
server.use(express.json());

server.use((req, res, next) => {
  console.log("URL CALL : " + req.url);
  return next();
});

server.get('/tables/:table', async (req, res) => {
  const { table } = req.params;
  const fieldPK = "";
  const pk = "";
  return res.json(await Connect.CONSULTING(table, fieldPK, pk));
});

server.get('/tables/:table/:fieldPK/:pk', async (req, res) => {
  const table = req.params['table'];
  let fieldPK = req.params['fieldPK'];

  if (isNaN(fieldPK) === true) fieldPK = "";

  let pk = req.params['pk'];
  if (isNaN(pk) === true) pk = "";

  return res.json(await Connect.CONSULTING(table, fieldPK, pk));
});

server.listen(3030);

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   x64       |
| Node.js version     | 16.14.2  | 
| Express.js version     | 4.18.1  | 
| React.js version     | 18.1.0  | 
| Typescript version  | 4.7.3  | 
| TypeORM version     | 0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | yes            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
and you are importing `data-source.js` in your react project I guess?

**Comment by GuilhermeLouli** [comment]
Yes

**Comment by pleerock** [comment]
you should not import node-platform code in browser environment. I wouldn't work.
