### ISSUE TITLE
findOneBy returns an while it should return null

### ISSUE THREAD

**Issue by imsamdez** [typeorm/typeorm#9160]
## Issue Description
I know this issue has been asked [here](https://github.com/typeorm/typeorm/issues/2500) but I'm still confused.
Also, the description of `findOneBy` says ` If entity was not found in the database - returns null.`.
But still, it keeps returning an element... why?! When is it supposed to return null if it returns always an element.

### Expected Behavior
Should return null

### Actual Behavior
Return a element (i guess it's the first one of the database)

### Steps to Reproduce

1. Use `findOneBy` with an id at null
2. Will return the first

```typescript
    const evolution = await this.evolutionRepository.findOneBy({
      uid: evolutionId, // when evolutionId is null, return an element
    });
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     MacOS     |
| Node.js version     | 16.13.1  | 
| Typescript version  | 4.7.4  | 
| TypeORM version     | 0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

**Comment by pleerock** [comment]
since 0.3.0 following expression:

```ts
const evolution = await this.evolutionRepository.findOneBy({
      uid: null
});
```

equals to (and it was since 0.2.x):

```ts
const evolution = await this.evolutionRepository.findOneBy({
      uid: undefined
});
```

and equals to:

```ts
const evolution = await this.evolutionRepository.findOneBy({
});
```

which returns you first raw because you didn't specify the criteria. 

So, `FindOptions` skips `null` and `undefined` properties and this is by design, in order to allow to build dynamic queries like:


```ts
const evolution = await this.evolutionRepository.findOneBy({
   name: request.query.name ? request.query.name : undefined, // okay let's skip it if user didn't specify
   age: request.query.age ? request.query.age : undefined, // okay let's skip it if user didn't specify it etc.
});
```

**Comment by pleerock** [comment]
Just think what SQL a following usage should build?:

```ts
const evolution = await this.evolutionRepository.findOneBy({
      uid: null
});
```

**Comment by imsamdez** [comment]
> Just think what SQL a following usage should build?:
> 
> ```ts
> const evolution = await this.evolutionRepository.findOneBy({
>       uid: null
> });
> ```

I would go for `SELECT * FROM evolution WHERE uid = null;` which leads into no results when executed on my mysql client.

**Comment by matheusgrandi** [comment]
Hey guys, I'm facing the same issue understanding the concept. There's any way to avoid the function to return the first element when sending an `undefined` and return null? For example:

`  async findByEmail(email: string): Promise<User> {
    const user = await this.repository.findOne({ where: { email: email } });
    return user;
  }`

**Comment by pleerock** [comment]
@imsamdez as changelog states, `.findOneBy({
      uid: null
})` leading to `WHERE uid = null` SQL was dropped to make it more transparent what SQL is executed. To achieve same behavior now you must use:

```ts
.findOneBy({
      uid: IsNull()
})
```

So, to achieve what you want basically you can do:

```ts
.findOneBy({
      uid: evolutionId ? evolutionId : IsNull()
})
```

**BUT** think twice before doing it. What is the point to hit database and execute pointless `SELECT * FROM evolution WHERE uid = null` query when you already know that it won't return you any data. It's a bad practice and obviously bad code / implementation. Prevent that on a code level, e.g.:

```ts
const evolution = evolutionId !== null ? await this.evolutionRepository.findOneBy({
      uid: evolutionId
}) : null;
```

**Comment by imsamdez** [comment]
Actually the way you tricked with ternary can be a good way 😉

Thanks for taking time to answer, closing this.

**Comment by matheusgrandi** [comment]
> Imagine the situation where some sensitive data is being returned from the database because a malicious entity requested data with a null property.
> 
> Some of my past codebases rely on the old logic so I doesn't have to worry about that kind of attack. Now I understand the logic behind the new way, but boy do I have some refactoring to do if I were to update TypeORM in my other projects.

I totally agree!

I managed to solve this in my case using ternary operator:

```typescript 
    const user =
      email !== (undefined || null)
        ? await this.repository.findOneBy({ email })
        : null;
```
