### ISSUE TITLE
How to change "mpath" field name of materialized-path tree in typeorm?

### ISSUE THREAD

**Issue by CaioWF** [typeorm/typeorm#9162]
Hi, I hope you are well.

Is there any way to change the name of the "mpath" column that is automatically generated when using the materialized-path tree structure on typeorm?

**Comment by mguida22** [comment]
Hi @CaioWF, you should be able to change the naming via overriding the default [naming strategy](https://github.com/typeorm/typeorm/blob/master/src/naming-strategy/NamingStrategyInterface.ts#L173) when creating your [data source](https://typeorm.io/data-source-options#common-data-source-options)
