### ISSUE TITLE
How to delete an entity which have many to many relationship.

### ISSUE THREAD

**Issue by MOIN-AKHTAR** [typeorm/typeorm#9169]
Hello i have a scnerio inwhich as a user i can follow anyone and i may have followers.
```
@ManyToMany(() => User, (user) => user.followers, { cascade: true })
  @JoinTable()
  following: User[];

  @ManyToMany(() => User, (user) => user.following)
  followers: User[];
```
Now when i'm deleting user than i'm getting "update or delete on table \"user\" violates foreign key constraint \"FK_a89f5a432c1edcd03a3b6555321\" on table \"user_following_user\""
How i can resolve this error that if i delete user i shouldn't face this error?

**Comment by christian-forgacs** [comment]
Try to use the `onDelete: 'CASCADE'` property in ManyToMany decorator.

**Comment by AlexMesser** [comment]
Please refer to the docs - [#Relations](https://typeorm.io/relations).
