### ISSUE TITLE
[Question] findByIds with another field

### ISSUE THREAD

**Issue by Porquepix** [typeorm/typeorm#917]
Hello everyone :)

After some researches I do not find an answer to my question. Thus, I post here.

Is it possible to use  SQL `IN` in where clause of a query or an equivalent of `findByIds` with another field than id ?

For instance, I have Users that have an email. I want to load users where their emails match an email in a list.
In SQL that will look something like that : 
`SELECT * FROM users WHERE email IN ('aa@aa.aa', 'bb@bb.bb');`

Thanks.

**Comment by pleerock** [comment]
Hi, 

yes for your purpose you need to use `QueryBuilder`:

```ts
const users = await manager.createQueryBuilder(User, "user")  // manager can be repository or connection objects too
    .where("user.email IN (:emails)", { emails: [...] })
    .getMany();
```

**Comment by Porquepix** [comment]
Ok thanks a lot :+1:
