### ISSUE TITLE
relation "typeorm_metadata" does not exist while creating a view in migration 

### ISSUE THREAD

**Issue by julianpoemp** [typeorm/typeorm#9173]
## Issue Description

This issue is probably related to [4923](https://github.com/typeorm/typeorm/issues/4923), pull request [4956](https://github.com/typeorm/typeorm/pull/4956) doesn't seem to work here.

### Expected Behavior

I try to implement a migration that creates views for postgres. Before that migration another migration installs all tables successfully (fresh installation). I'm running the migrations manually using the typeorm-cli.

I'm using the following code to create a view (just for testing before implementing the real query):

````typescript
 console.log(`Create view...`);
    await queryRunner.createView(new View({
      name: 'tool_view',
      materialized: false,
      expression: (connection: DataSource) => {
        return connection.createQueryBuilder(ToolEntity, 'tool').select('*');
      }
    }));
````

It should create a view that just represents the same table as "tool".

### Actual Behavior

I get the following error message:

````
QueryFailedError: relation "typeorm_metadata" does not exist
    at PostgresQueryRunner.query (/snapshot/project/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryRunner.executeQueries (/snapshot/project/node_modules/typeorm/query-runner/BaseQueryRunner.js:421:13)
    at async PostgresQueryRunner.createView (/snapshot/project/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:475:9) {
  query: 'INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)',
  parameters: [
    'public',
    'VIEW',
    'test_view',
    'SELECT * FROM "tool" "tool"'
  ],
  driverError: error: relation "typeorm_metadata" does not exist
      at Parser.parseErrorMessage (/snapshot/project/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/snapshot/project/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/snapshot/project/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/snapshot/project/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:527:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 115,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '13',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1384',
    routine: 'parserOpenTable'
  },
  length: 115,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '13',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1384',
  routine: 'parserOpenTable'
}
````

### Steps to Reproduce

1. Create a Datasource connection for PostgreSQL
2. Create a migration and implement code that creates any view.
3. Run the migration using the typeorm -cli.

### Possible solution

Create "typeorm_metadata" automatically next to "typeorm_migrations" table. That would ensure that the typeorm_metadata table exists.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System           | MacOS  12.4  |
| Node.js version        |  v16.15.0 |
| Typescript version   |  v4.7.3 |
| TypeORM version    |  v.0.3.7 |
| Postgres   |  v14.2 |

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 -  ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by satanshiro** [comment]
this is actually still happening to me not sure if i'm doing anything wrong, working with local postgres, creating a view in code then runnning migration creation it keeps on adding an insert to typeorm metadata but fails again with 
QueryFailedError: relation "typeorm_metadata" does not exist 
on latest 0.3.11

**Comment by itinance** [comment]
got the same with typeorm version 0.3.15.
How to fix that?

**Comment by itinance** [comment]
Okay, here we go: https://github.com/typeorm/typeorm/issues/4923

**Comment by KiwiKilian** [comment]
I first had the same problem with `0.3.20` but it was a wrong configuration on the server. Be sure to configure your `TYPEORM_ENTITIES` or `entities` in `ormconfig.ts` accordingly. I wasn't including the views, only the entities. Proper value for my case:
```
TYPEORM_ENTITIES=src/**/*.{entity,view}.ts
```
