### ISSUE TITLE
Connection pool max

### ISSUE THREAD

**Issue by lazarid** [typeorm/typeorm#9177]
### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
- [x]  - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by alfonsogarza** [comment]
I'm running into issues with my pool size, is solution to set `max` in extras in the config?

**Comment by AlexMesser** [comment]
Please use the issue template describing what issue you have.
