### ISSUE TITLE
config typeorm to Connect {

### ISSUE THREAD

**Issue by kongnakornna** [typeorm/typeorm#9179]
config typeorm to Connect {
  type: 'mysql',
  host: 'localhost',
  port: 3308,
  username: 'root',
  password: 'root',
  database: 'demodb',
  entities: [ 'src/entities/*{.ts,.js}', 'src/modules/user/entities/*{.ts,.js}' ],
  migrations: [ 'src/migration/*{.ts,.js}' ],
  subscribers: [ 'src/subscriber/*{.ts,.js}' ],
  cli: {
    entitiesDir: [
      'src/entities/*{.ts,.js}',
      'src/modules/user/entities/*{.ts,.js}'
    ],
    migrationsDir: 'src/migrations/*{.ts,.js}',
    subscribersDir: 'src/subscribers/*{.ts,.js}'
  },
  logging: false,
  synchronize: false
node_redis: Warning: Redis server does not require a password, but a password was supplied.
isConnection true
{"level":30,"time":1657020819916,"pid":25656,"hostname":"kongnakorn01","msg":"Server listening at http://127.0.0.1:8002"}
App is running at port 8001 on undefined mode at Tue Jul 05 2022 18:33:39 GMT+0700 (Indochina Time)
{"level":30,"time":1657020822156,"pid":25656,"hostname":"kongnakorn01","reqId":"req-1","req":{"method":"GET","url":"/demo/user/list","hostname":"127.0.0.1:8002","remoteAddress":"127.0.0.1","remotePort":58040},"msg":"incoming request"}
randomint 086564
{"level":50,"time":1657020822163,"pid":25656,"hostname":"kongnakorn01","reqId":"req-1","req":{"method":"GET","url":"/demo/user/list","hostname":"127.0.0.1:8002","remoteAddress":"127.0.0.1","remotePort":58040},"res":{"statusCode":500},"err":{"type":"TypeError","message":"Cannot read property 'replace' of undefined","stack":"TypeError: Cannot read property 'replace' of undefined\n    at D:\\UwAmp\\www\\aDEV\\fastify_api\\src\\modules\\user\\controllers\\usercontroller.ts:57:30\n    at step (D:\\UwAmp\\www\\aDEV\\fastify_api\\src\\modules\\user\\controllers\\usercontroller.ts:33:23)\n    at Object.next (D:\\UwAmp\\www\\aDEV\\fastify_api\\src\\modules\\user\\controllers\\usercontroller.ts:14:53)\n    at D:\\UwAmp\\www\\aDEV\\fastify_api\\src\\modules\\user\\controllers\\usercontroller.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (D:\\UwAmp\\www\\aDEV\\fastify_api\\src\\modules\\user\\controllers\\usercontroller.ts:4:12)\n    at Object.<anonymous> 
(D:\\UwAmp\\www\\aDEV\\fastify_api\\src\\modules\\user\\controllers\\usercontroller.ts:45:69)\n    at preHandlerCallback (D:\\UwAmp\\www\\aDEV\\fastify_api\\node_modules\\fastify\\lib\\handleRequest.js:126:28)\n    at preValidationCallback (D:\\UwAmp\\www\\aDEV\\fastify_api\\node_modules\\fastify\\lib\\handleRequest.js:109:5)\n    at handler (D:\\UwAmp\\www\\aDEV\\fastify_api\\node_modules\\fastify\\lib\\handleRequest.js:72:7)"},"msg":"Cannot read property 'replace' of undefined"} 
{"level":30,"time":1657020822176,"pid":25656,"hostname":"kongnakorn01","reqId":"req-1","res":{"statusCode":500},"responseTime":18.17069999873638,"msg":"request completed"}

_Originally posted by @kongnakornna in https://github.com/typeorm/typeorm/issues/6612#issuecomment-1174955903_

**Comment by AlexMesser** [comment]
Please use the issue template.
