### ISSUE TITLE
How to specity the join columns in @JoinTable() directive

### ISSUE THREAD

**Issue by SuheylZ** [typeorm/typeorm#9184]
i have the following tables in postgres

users
userid: int, PK
name: string
age: int

department
departmentid: int, PK
name: string

department_user
userid: int, FK
departmentid: int, FK

This is how I declared the entity classes
```
@Entity({
  name: 'user'
})
export class User {
  @Column({ type: 'int4' })
  @PrimaryColumn()
  userid: number

  @Column({name: 'name', type: 'varchar', length: 30})
  name: string

  @Column({name: 'age', type: 'int2'})
  age: number

  @ManyToMany(() => Department, (department)=> department.users)
  @JoinTable({
    name: 'department_user'
  })
  departments: Department[]
}

@Entity({ name: 'department' })
export class Department {

  @Column({ type: 'int2' })
  @PrimaryColumn()
  departmentid: number

  @Column({type: 'varchar', length: 50})
  title: string

  @Column({type:'text'})
  notes: string

  @ManyToMany(() => User, (user)=> user.departments)
  @JoinTable({ name: 'department_user' })
  users: User[]  
}
```

On Executing, the TypeORM creates two columns in the join table 
userUserId and departmentDepartmentId

how can I instruct typeORM to use the existing column and not create new columns? I tried looking for this in documentation but could not find any example. using joinColumns always gives runtime error such as "userUserId" is null or could not find "userid" column etc

**Comment by AlexMesser** [comment]
you can specify custom column names in `referencedColumnName` property. See [@JoinTable()](https://typeorm.io/decorator-reference#jointable).
