### ISSUE TITLE
Expo, Sqlite -- not able to set `PRAGMA foreign_keys = true` when using DataSource `synchronize: false`

### ISSUE THREAD

**Issue by DLawla** [typeorm/typeorm#9206]
## Issue Description
I've noticed that the latest typeorm version + sqlite expo driver won't allow setting PRAGMA foreign_keys when `synchronize: false` is set when initializing the `DataSource`. However, foreign_keys can be assigned when using `synchronize: true`.

I am using the [expo example](https://github.com/typeorm/expo-example).

I have observed this in our app resulting in CASCADE DELETE's not functioning.

I assume this is a bug and not expected behavior.

### Expected Behavior

Using the following from the demo:

```
const dataSource = new DataSource({
   database: "test19",
      driver: require('expo-sqlite'),
      entities: [
         Category,
          Author,
          Post
      ],
      synchronize: false, // <--------------- culprit?
      type: "expo",
})
```

```
  async runDemo() {
    const source = await this.connect();

    console.log("PRAGMA FK:")
    console.log(await source.query("PRAGMA foreign_keys = true"));
    console.log(await source.query("PRAGMA foreign_keys"));
```

I would expect to see `PRAGMA foreign_keys` return `1`. However this is the output:

```
PRAGMA FK:
Array []
Array [
  Object {
    "foreign_keys": 0,
  },
]
```

I can confirm that if I set `synchronize: true`, and reload the app, I receive the following console output:
```
PRAGMA FK:
Array []
Array [
  Object {
    "foreign_keys": 1,
  },
]
```

### Steps to Reproduce

1. Clone the [expo example](https://github.com/typeorm/expo-example).
2. Add the following to `runDemo()`:
```
    console.log(await source.query("PRAGMA foreign_keys = true"));
    console.log(await source.query("PRAGMA foreign_keys"));
```
3. Toggle the DataSource `synchronize` attribute between `false` and `true`
4. Observe the `PRAGMA foreign_keys` output not being changeable when `PRAGMA foreign_keys = true` using `synchronize: false`

### My Environment
 [expo example](https://github.com/typeorm/expo-example).

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | yes            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | yes            |
| `sqlite-abstract` | yes            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?
 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by DLawla** [comment]
@mlecoq -- as another expo & typeorm user -- have you encountered this issue when setting up foreign keys, and for example, cascade deletions?

**Comment by mlecoq** [comment]
@DLawla

I think it’s a matter of how pragma is set (It's a matter of level)

As as matter of fact, if I add the following line:

```
await source.createQueryRunner().afterMigration();
console.log(await source.query('PRAGMA foreign_keys'));
```

I have 
```
"foreign_keys": 1,
```

**Comment by mlecoq** [comment]
A better way to do it 

```
    const source = await this.connect();

    const queryRunner = source.createQueryRunner();
    const connection = await queryRunner.connect();

    await new Promise((ok, fail) => {
      connection.exec([{sql: 'PRAGMA foreign_keys = ON', args: []}], false, (err: Error) =>
        err ? fail(err) : ok(true),
      );
    });

    console.log(await source.query('PRAGMA foreign_keys'));
```

**Comment by DLawla** [comment]
@mlecoq [mlecoq](https://github.com/mlecoq) You're a legend. That works! My cascade deletes are now working as advertised. Hopefully someone else finds this just as helpful. 
I'll close this issue.
