### ISSUE TITLE
[Postgres] `simple-enum` column should generate the same name if the two table shares the same type

### ISSUE THREAD

**Issue by stevefan1999-personal** [typeorm/typeorm#9207]
## Issue Description

Ditto to title

### Expected Behavior

The database objects are manifested successfully

### Actual Behavior

This is an example code to replicate the issue (workaround also included)

```ts
export enum ObjectType {
  Foo = 'foo',
}

@Entity({ name: 'object' })
export class Object {
  @PrimaryColumn()
  id: string

  @PrimaryColumn({
    enum: ObjectType,
    // enumName: 'object_type',
    type: 'simple-enum',
  })
  type: ObjectType
}

@Entity({ name: 'typed_object' })
class TypedObject {
  @PrimaryColumn()
  id: string

  @Column({
    default: ObjectType.Foo,
    enum: ObjectType,
    // enumName: 'object_type',
    type: 'simple-enum',
  })
  @Check(`"type" = '${ObjectType.Foo}'`)
  type: ObjectType = type

  @ManyToOne(() => Object, {
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
    orphanedRowAction: 'delete',
  })
  @JoinColumn([
    {
      name: 'id',
      referencedColumnName: 'id',
    },
    {
      name: 'type',
      referencedColumnName: 'type',
    },
  ])
  parent: Object
}
```

Here's one of the SQL it generates.
```
CREATE TYPE "public"."object_type_enum" AS ENUM ('foo')
CREATE TABLE "object"
(
    "id"       character varying           NOT NULL,
    "type"     "public"."object_type_enum" NOT NULL,
    CONSTRAINT "PK_df30d18c6c83f6472d308b79a25" PRIMARY KEY ("id", "type")
)
CREATE TYPE "public"."typed_object_type_enum" AS ENUM ('foo')
CREATE TABLE "typed_object"
(
    "id"    character varying         NOT NULL,
    "type"  "public"."typed_object_type_enum" NOT NULL DEFAULT 'foo',
    CONSTRAINT "CHK_4c350947e190695c83dae0480f" CHECK ("type" = 'foo'),
    CONSTRAINT "PK_f22c68b170f92f8fe6a0c09c75a" PRIMARY KEY ("id")
)
ALTER TABLE "typed_object"
    ADD CONSTRAINT "FK_b94ab51c8e0eb42080b588be944" FOREIGN KEY ("id", "type") REFERENCES "object" ("id", "type") ON DELETE CASCADE ON UPDATE CASCADE
```

The error:
```
[2022-07-16 18:17:20] [42804] ERROR: foreign key constraint "FK_b94ab51c8e0eb42080b588be944" cannot be implemented
[2022-07-16 18:17:20] Detail: Key columns "type" and "type" are of incompatible types: typed_object_type_enum and object_type_enum.

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Not related     |
| Node.js version     |  Not related | 
| Typescript version  |  Not related | 
| TypeORM version     |  0.3.7| 

### Additional Context

As you can see the workaround is to simply change `enumName` manually to a uniquely identifiable symbol, however **this has to be done on entity-to-entity basis**. All the other databases do not exhibit a similar situation (or perhaps yet), that means **without using `enumName` workaround all other databases would pass schema creation as of right now**. This is probably because `simple-enum` resolves to `enum` in Postgres, while all other databases use `varchar` as text-based enum emulation. This is weird so I would like to report. 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `postgres`        | yes            |
| All others       | probably |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ No, I don’t have the time, but I can support (using donations) development.

**Comment by AlexMesser** [comment]
1. `simple-enum` is kinda hack for the databases that don't have native `enum` type support. You don't need to use it in posgres since pg has native `enum` support.
2. TypeORM always generates an unique enum name for each table whether you use the same enum or different ones.
3. `enumName` introdused precisely in order to share the same enum name between multiple entities.

So, in this case using a `enumName` is the right way to go.

**Comment by pkuczynski** [comment]
Using `enumName` does not work for me. See https://github.com/typeorm/typeorm/issues/9233#issuecomment-1216733169

**Comment by ivanstanev** [comment]
@AlexMesser conceptually yes, but it doesn't work - as mentioned here and in #9233 using `enumName` causes TypeORM to generate pointless migrations every time that rename the enum, create the exact same one, apply it, and delete the old one. The only solution currently is to **not** use `enumName`
