### ISSUE TITLE
Relations not working with different Foreign Key name instead of `id` 

### ISSUE THREAD

**Issue by abrar-whizpool** [typeorm/typeorm#9226]
## Issue Description

consider the below mentioned code  :

This is a firstEntity
```
@Entity()
export class FirstEntity extends baseEntity {
  @PrimaryGeneratedColumn()
  firstEntityId: number;

  @Column()
  firstEntityName: string;
}
```
This is a second Entity
```
@Entity()
export class secondEntity extends baseEntity {
  @PrimaryGeneratedColumn()
  secondEntityId: number;

  @Column()
  className: string;

  @ManyToOne(() => FirstEntity)
  firstEntity: FirstEntity;
  @Column()
  firstEntityId: FirstEntity['firstEntityId'];
}
```
when these two entities are initialized. it will give the error for the `secondEntity` for @column() `firstEntityId`
```
@Column()
  firstEntityId: FirstEntity['firstEntityId'];
```
as its not getting the primary key `firstEntityId` from `firstEntity` but when we use primary key name as `id` instead of `firstEntityId` it's working fine . In entities  relation can't be used if the name of the foreign key is not `id`

The Error 🐛  is 

```
[Nest] 6529  - 21/07/2022, 14:51:28   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
DataTypeNotSupportedError: Data type "Object" in "secondEntity.firstEntityId" is not supported by "postgres" database.
```
### Expected Behavior

The relation between two tables must be working , even if foreign key is any thing else instead of `id` like `primaryId`,`userId` etc

### Actual Behavior

The relation between two tables are not working, if foreign key is any thing else instead of `id` like `primaryId`,`userId` etc

### Steps to Reproduce

1. create two entities `firstEntity` and `secondEntity`
2. In firstEntity use anything else as primary key instead of `id` like `primaryId`,`userId` etc
3. create a relation between  `firstEntity` and `secondEntity` 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  mac 10.15.7   |
| Node.js version     | 16.16.0  | 
| Typescript version  | 4.5.5  | 
| TypeORM version     | 8.0.3  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by yura2100** [comment]
Check [@JoinColumn](https://orkhan.gitbook.io/typeorm/docs/relations#joincolumn-options) decorator. It is used for such cases

**Comment by abrar-whizpool** [comment]
@9031  tried it but it changes the Name of column in db

**Comment by abrar-whizpool** [comment]
@9031 tried it but it changes the Name of column in db

**Comment by abrar-whizpool** [comment]
@9031 tried it but it changes the Name of column in db

**Comment by yura2100** [comment]
Please provide a reproduction with `@JoinColunn()` decorator. I don't understand how it may change something in DB

**Comment by rasyhad** [comment]
Not sure if you solved this problem but like @yura2100  said, check [@JoinColumn](https://typeorm.io/relations#joincolumn-options)

You can specify the reference column that you want that is not `id`. In your case, you are using `firstEntityId`

**Comment by AlexMesser** [comment]
closing as answered.
