### ISSUE TITLE
Array parameter on groupBy.

### ISSUE THREAD

**Issue by wirekang** [typeorm/typeorm#9240]
## Feature Description
It would be great if `groupBy` in `SelectQueryBuilder` receives array just like `select` method.

### The Problem
When you have to build query like `..GROUP BY a,b,c,d ...`, you should repeat `addGroupBy` 4 times.

```
  .groupBy(a)
  .addGroupBy(b)
  .addGroupBy(c)
  .addGroupBy(d)
```

### The Solution
In case of `select`, You can select multiple columns at once.

```
 .select([a,b,c,d])
```

If `groupBy` receives array too,

```
  .groupBy([a,b,c,d])
```
it increases code consistency.

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
I had to revert these changes because CI failed because of them. Please create a new PR with tests successfully passing. Thank you.
