### ISSUE TITLE
PlatformTools : Webpack doesn't find MySQL package

### ISSUE THREAD

**Issue by benjamin-vauchel-webrivage** [typeorm/typeorm#925]
It seems the dynamic require of MySQL package in PlatformTools l.33 doesn't work with Webpack.
It compiles but doesn't work.

Here the error I got : 

```
  name: 'DriverPackageNotInstalledError',
  message: 'Mysql package has not been found installed. Try to install it: npm install mysql --save' 
```

In the compiled JS, I got : 

```javascript
PlatformTools.load = function (name) {
        // if name is not absolute or relative, then try to load package from the node_modules of the directory we are currenly in
        // this is useful when we are using typeorm package globally installed and it accesses drivers
        // that are not installed globally
        try {
            return !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }());
        }
        catch (err) {
            if (!path.isAbsolute(name) && name.substr(0, 2) !== "./" && name.substr(0, 3) !== "../") {
                return !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }());
            }
            throw err;
        }
    };
```

But if I replace the dynamic require `return require(name);` by `return require('mysql');` in PlatformTools.js it works fine.

```javascript
PlatformTools.load = function (name) {
        // if name is not absolute or relative, then try to load package from the node_modules of the directory we are currenly in
        // this is useful when we are using typeorm package globally installed and it accesses drivers
        // that are not installed globally
        try {
            switch (name) {
                case 'mysql':
                    return require('mysql');
                default:
                    return require(name);
            }
        }
        catch (err) {
            if (!path.isAbsolute(name) && name.substr(0, 2) !== "./" && name.substr(0, 3) !== "../") {
                return require(path.resolve(process.cwd() + "/node_modules/" + name));
            }
            throw err;
        }
    };
```

Any idea of what goes wrong ?

**Comment by pleerock** [comment]
why do you use webpack? I don't really understand why people use webpack on the backend

**Comment by pankajku** [comment]
I ran into the same issue. I am trying to use typeorm in an AWS lambda function and use serverless framework for deployment. Serveless uses webpack to bundle all files before uploading to an S3 bucket.

I modified my local copy of PlatformTools.js as suggested by @benjamin-vauchel-webrivage and that resolved the issue. Of course, it is not a proper fix.

**Comment by pleerock** [comment]
> Serveless uses webpack to bundle all files

does it bundle into a single file? If yes then Im not sure if node app will work properly then only if it does not resolve magically all circular dependencies

> I modified my local copy of PlatformTools.js as suggested by @benjamin-vauchel-webrivage and that resolved the issue. Of course, it is not a proper fix.

So webpack does not support dynamic imports like `return require(name);` ? I don't believe in it because it such a common use cases, and especially now, when there is dynamic es8 `import` function that suppose to load dynamic things. Im sure there is some solution in webpack

**Comment by benjamin-vauchel-webrivage** [comment]
@pleerock You were right, webpack was not necessary. Forgives a JS beginner ! :)
@pankajku I also use typeorm with serverless and even if the tutorial encourages to use serverless-webpack you can simply write JS or TS. ;)

> So webpack does not support dynamic imports like return require(name); ?

It **almost** supports, I found this on webpack doc : 

> Context refers to a require with an expression such as require('./locale/' + name + '.json'). When encountering such an expression, webpack infers the directory ('./locale/') and a regular expression (/^.*\.json$/). Since the name is not known at compile time, **webpack includes every file as module in the bundle**.

**Comment by mcaubrey** [comment]
2021 here, I'm having this problem as well.

When you create a new typescript project with the Serverless framework, it installs everything with webpack by default.

Is there any way to get this working?

**Comment by 50bbx** [comment]
2022, having the same issue here. Is there any permanent and not hacky solution to this?
