### ISSUE TITLE
MongoDB - FindOne / Find doesn't work with @DeleteDateColumn()

### ISSUE THREAD

**Issue by crossinghoods** [typeorm/typeorm#9250]
## Issue Description
Find, FindBy, FindOne, FindOneBy all do not work properly when @DeleteDateColumn() is used 

DB: MongoDB
Typescript 4.7.4
Typeorm 0.3.7

Create a few entries with different names, try to find 1 entry by using
await VenueSVG.find({ where: { name: "test-7" } });
await VenueSVG.findOne( { name: "test-7" } );

### Expected Behavior
Should result in getting entries where name == "test-7"

### Actual Behavior
- Returns the 1st entry when using findOne()
- Returns all entries when using find()

### Steps to Reproduce
`export class VenueSVG extends BaseEntity {
  @ObjectIdColumn()
  id!: ObjectID;

  @Column()
  name!: string;

 @DeleteDateColumn()
 deletedDate!: Date;
}
`
1. Create a few entries i.e. "test-1", "test-2" etc.
2. Use the find methods await VenueSVG.find({ where: { name: "test-7" } }); Or await VenueSVG.findOne( { name: "test-7" } );

**Comment by roseline124** [comment]
I've been through same issue. I'll try this job! 
If you need to work with DeleteDateColumn right now,  you can do like this

```
VenueSvg.findOne({where: { name: "test-7"}, withDeleted: true})
```
