### ISSUE TITLE
Migration generate tool always try to recreate my FK definitions

### ISSUE THREAD

**Issue by renansmoreira** [typeorm/typeorm#9256]
## Issue Description
TypeORM is trying to recreate my FK definitions from a already existing database.

### Expected Behavior
I expect TypeORM to detected the already existing foreign key and do not try to recreate it.

### Actual Behavior
I'm migrating my current migration tool to TypeORM migrations using an already existing database. With the current database, I have some foreign keys that are always recreated by TypeORM when I ask it to generate a new migration and this is a blocker issue because every time I'll get a redundant change to apply in my database.
An important thing to note is that this bug doesn't happen for every FK, just some of them are affected.

Please refer to "Steps to Reproduce" section for code sample.

### Steps to Reproduce
I made a [fresh repo to show the issue](https://github.com/renansmoreira/typeorm-mapping-test).

1. Clone the repo;
2. Follow `README.md` instructions

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Ubuntu 22.04 LTS and macOS Monterey 12.3.1 |
| Node.js version     | 14.17.0  | 
| Typescript version  | 6.14.13  | 
| TypeORM version     | 0.3.7  | 

### Additional Context

N/A

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by needim** [comment]
had same issue on mysql driver

**Comment by itseramin** [comment]
Same issue.

**Comment by gustavosizilio** [comment]
Same here... any news?

**Comment by gustavosizilio** [comment]
In my case, the problem was that I was using this mapping:

```
@ManyToOne(() => DataSource, (dataSource) => dataSource.dataSyncReports)
  @JoinColumn([
    {
      name: 'data_source_id',
      referencedColumnName: 'id',
      foreignKeyConstraintName: 'data_sync_report_data_source_id_foreign',
    },
  ])
  dataSource: DataSource;
```

And  I didn't explicitly add the dataSourceId field in the same class.

```
  @Column('integer', { name: 'data_source_id', nullable: false })
  dataSourceId: number;
```


After adding the field and mapping it... the foreign generation went out

**Comment by renansmoreira** [comment]
>Same here... any news?

Not really, I just discovered that TypeORM only maps constraints using `alter table xxx add constraint` for Postgres, but if you add them together with `create table` + `constraint` in the column definition, for example, it'll ask to recreate using exactly the same configuration and I have no idea why. That's a trick to reduce schema introspection output but sometimes even using the `alter table` it asks to recreate again over and over again, even if you apply the suggested change :slightly_frowning_face: 

For now I'm just ignoring the result and keeping what's relevant for me

**Comment by 2ndr9** [comment]
In TypeORM, automatic indexing seems to be applied to relationships such as @OneToOne. Therefore, if you attach an @Index to an @Entity, TypeORM will attempt to create a duplicate index. As a result, it's necessary to remove the @Index from the @Entity.
Additionally, TypeORM tends to create indexes for relationships like @OneToOne not as CREATE UNIQUE INDEX but as CONSTRAINT within the CREATE TABLE statement. Therefore, it's necessary to modify the initial.sql file.
By implementing these changes, migration generate tool no longer try to recrete FK.

This is an example of fix.
https://github.com/renansmoreira/typeorm-mapping-test/pull/1
