### ISSUE TITLE
Is Cassandra database can be integrated with Type ORM in Nest JS 

### ISSUE THREAD

**Issue by emmanuel-wilson-neudesic** [typeorm/typeorm#9258]
I want to use the Cassandra database with TypeORM in Nest Js. I have tried to use [nestjs-express-cassandra](https://github.com/ifaim/nestjs-express-cassandra) but there is no such functionality as One to Many, Many to One. So can I integrate TypeOrm with the Cassandra database?

**Comment by Ginden** [comment]
No, Cassandra is not supported - https://github.com/typeorm/typeorm/issues/1626
