### ISSUE TITLE
[Feature Request] disable cache when redis is down

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#926]
if I using a redis server to cache queries, when redis is down the typeorm will crash immediately.

```
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
```

it should be auto disable cache and auto retry later

**Comment by pleerock** [comment]
I don't think it should work this way. If you enabled cache and configure redis then your redis must be up and working. And I dont see real world scenarios when users redis will be "sometimes enabled" or "sometimes disabled"

**Comment by Diluka** [comment]
this is about server availability and crisis control.
remote services could be unavailable sometimes. maybe network issue or service update. those foreseeable exceptions should be handled. for now, redis unavailable makes typeorm crashed further crashes the whole server. makes server unstable. 

the cache is temporary storage. It allows the server to handle the business faster. But without it, the server should also be able to work properly, and not completely collapse.
When use `spring-data-redis` to cache, we can overload the serialization and deserialization methods to prevent redis errors caused by the problem.

**At least, the cache options should export an API for developers to register there own implementations to handle cache server offline exception.**
so that could increase the server's availability.

**Comment by pleerock** [comment]
This explanation makes sense, but we need to think how API for this shall look like

**Comment by scvgoe** [comment]
I agree with @Diluka's opinion.

I think we should be able to override redis error handler.

**Comment by scvgoe** [comment]
Actually, I want to ignore all cache stuff errors.

```typescript
    /**
     * Loads raw results from the database.
     */
    protected async loadRawResults(queryRunner: QueryRunner) {
        const [sql, parameters] = this.getQueryAndParameters();
        const queryId = sql + " -- PARAMETERS: " + JSON.stringify(parameters);
        const cacheOptions = typeof this.connection.options.cache === "object" ? this.connection.options.cache : {};
        let savedQueryResultCacheOptions: QueryResultCacheOptions | undefined = undefined;
        if (this.connection.queryResultCache && (this.expressionMap.cache || cacheOptions.alwaysEnabled)) {
            try {
                savedQueryResultCacheOptions = await this.connection.queryResultCache.getFromCache({
                    identifier: this.expressionMap.cacheId,
                    query: queryId,
                    duration: this.expressionMap.cacheDuration || cacheOptions.duration || 1000
                }, queryRunner);
                if (savedQueryResultCacheOptions && !this.connection.queryResultCache.isExpired(savedQueryResultCacheOptions))
                    return JSON.parse(savedQueryResultCacheOptions.result);
            } catch { }
        }

        const results = await queryRunner.query(sql, parameters);

        if (this.connection.queryResultCache && (this.expressionMap.cache || cacheOptions.alwaysEnabled)) {
            try {
                await this.connection.queryResultCache.storeInCache({
                    identifier: this.expressionMap.cacheId,
                    query: queryId,
                    time: new Date().getTime(),
                    duration: this.expressionMap.cacheDuration || cacheOptions.duration || 1000,
                    result: JSON.stringify(results)
                }, savedQueryResultCacheOptions, queryRunner);
            } catch { }
        }

        return results;
    }    
```

**Comment by gouroujo** [comment]
Hello,
This issue is really a very nice improvement to the current behaviour.
I'm facing the same problem with the option `enableOfflineQueue` set to false for a high velocity throughput.
The request I made to the database is very lightweight, but also very frequent (ETL system) so the cache is only here to reduce the number of request. If there is more miss than it should be (for example if there is a network failure with redis) I don't want to queue my request neither wait for the network neither I want to fail it due to the cache unavailability.

In my opinion, the actual behaviour should be the default (as it the most common use case) but you should provide an API option to ignore cache failure.

cheers,
Jo

**Comment by hunglee** [comment]
Any update about this issue?
