### ISSUE TITLE
How to save a many to one relation?

### ISSUE THREAD

**Issue by ekkirizki** [typeorm/typeorm#9260]
what if i have 1 table like this, what should i do? i confused btw. sorry for my bad english 🙏
![image](https://user-images.githubusercontent.com/33188067/182786115-10abf58d-0400-445e-9346-50db37653220.png)

**Comment by AlexMesser** [comment]
For questions / general support, please check out our [Slack channel](https://join.slack.com/t/typeorm/shared_invite/zt-uu12ljeb-OH_0086I379fUDApYJHNuw), [StackOverflow](https://stackoverflow.com/questions/tagged/typeorm) or check [TypeORM's documentation](https://typeorm.io).
