### ISSUE TITLE
queryRunner.getTable() fails if Foreign Key is set in target table.

### ISSUE THREAD

**Issue by idenisovs** [typeorm/typeorm#9266]
## Issue Description

I try to run the simple data migration script, just like that

```typescript 
public async up(queryRunner: QueryRunner): Promise<void> {
    const registrationTable = await queryRunner.getTable('registration');
}
```

It fails with TypeError message: `Cannot read properties of undefined (reading 'name')`

DDL of `registration` table:

```sql
CREATE TABLE registration (
    id        INTEGER  PRIMARY KEY AUTOINCREMENT,
    time      DATETIME NOT NULL ON CONFLICT ROLLBACK,
    client_id INTEGER  REFERENCES test1 (id) ON DELETE CASCADE NOT NULL ON CONFLICT ROLLBACK
);
```

DDL of `test1` table:

```sql
CREATE TABLE test1 (
    id    INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
    fname TEXT    UNIQUE ON CONFLICT ROLLBACK
);
```

In case if I remove the Foreign Key constraint from table `registration` then everything is ok!

### Expected Behavior

The queryRunner should return the Table object.

### Actual Behavior

The queryRunner fails with following message:

```
TypeError: Cannot read properties of undefined (reading 'name')
at /home/xxxxxProjects/xxxxxx/backend/node_modules/typeorm/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts:1553:46
    at Array.map (<anonymous>)
    at /home/xxxxxx/Projects/xxxxxx/backend/node_modules/typeorm/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts:1527:64
    at async Promise.all (index 0)
    at async SqliteQueryRunner.getTable (/home/xxxxxx/Projects/xxxxxx/backend/node_modules/src/query-runner/BaseQueryRunner.ts:143:29)
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Ubuntu 22.04     |
| Node.js version     | v16.15.0 | 
| Typescript version  | 4.7.4  | 
| TypeORM version     | 0.3.7  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | yes            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by stonedMoose** [comment]
We have the same problem, is there a roadmap for fixing this or a known workaround ?

**Comment by TokiDEV** [comment]
Would love to see a fix, this problem arises when I try to upgrade my typeorm version... :cry:

**Comment by GP4cK** [comment]
I did a bit of digging, the problem comes from the way the FK is declared in your code / parsed in typeorm's code.
As you can see in the code below, the regex used starts with `CONSTRAINT ...`. But you don't have this in your code so the FK mapping is never found.
https://github.com/typeorm/typeorm/blob/58fc08840a4a64ca1935391f4709a784c3f0b373/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts#L1523-L1539
