### ISSUE TITLE
Entity save() method doesn't update updated_at if nothing else changed

### ISSUE THREAD

**Issue by Thomas-1985** [typeorm/typeorm#9276]
## Issue Description

We have a model where the @UpdateDateColumn() decorator is set

```
Entity('users')
export class User {

  @BeforeUpdate()
  CreateUUID?() {
    if (this.uuid === undefined || this.uuid === "") {
      this.uuid = Helpers.generateUUID()
    }
  }

  @Column()
  @Generated("uuid")
  uuid?: string = Helpers.generateUUID()

  @PrimaryGeneratedColumn()
  id?: number;

  @Column({nullable: true})
  @IsOptional()
  @IsPositive()
  customer_number: number;

  @UpdateDateColumn({type: "timestamp"})
  @IsOptional()
  updated_at?: Date;
}

```

I want to call `save()` on my entity without any changes to the entity itself to just trigger the `updated_at`. This however doesn't work, the attribute is not changed in the database.

### Expected Behavior

The entity should be updated so that the `updated_at` attribute changes

### Actual Behavior

The entity is not updated

### Steps to Reproduce

1. Create an entity class like above
2. Run `save()` without any changes to the entity itself

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Windows        |
| Node.js version     | 16.15.1  | 
| Typescript version  | 4.7.3  | 
| TypeORM version     | 0.3.5  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by dkarkar92** [comment]
> I want to call save() on my entity without any changes to the entity itself to just trigger the updated_at

This does not seem like a bug. What you want is a feature request. 

Triggering `updated_at` changes on a `save` with no actual record changes is bad. I can't really think of a reason you'd intentionally want to do that.

**Comment by swa-bilkim** [comment]
Hi !

I am also interested on a way to refresh the update date. In my case, my entity is used by SQL view and this date is used to filter some results. When a user update the entity, even if the values of it didn't changed, we need to know it has been updated recently.

Would it be possible to implement an option to force this column to be updated ? Or does one of you have an idea of any workaround ?

**Comment by Thomas-1985** [comment]
I had to implement a workaround (in my user service) like this
```
export default class UserService {
...
  static async update (user: User): Promise<User> {
    user.updated_at = new Date();
    return await UserService.save(user);
  }
...
}
```

Then i can just call this without any payload and it will update the `updated_at` attribute
