### ISSUE TITLE
MySQL crashing

### ISSUE THREAD

**Issue by LeonardoDB** [typeorm/typeorm#9279]
Hello, I'm using nestjs with typeorm: "^0.3.6", and I'm load testing my application and I noticed that after a certain number of requests the typeorm with mysql is crashing when it starts a transaction, this is problematic since it it no longer works.

![image](https://user-images.githubusercontent.com/33195732/184145415-fc1dbb35-db36-4d8c-b44a-53722c86f442.png)

**Comment by Ginden** [comment]
@LeonardoDB Please provide more information. Preferably, minimum reproduction case.
