### ISSUE TITLE
Unable to pass parameters using the Clone API

### ISSUE THREAD

**Issue by zq0904** [typeorm/typeorm#9283]
## Issue Description
Unable to pass parameters using the Clone API
```ts
  const qbBase = await connection
    .getRepository(AppFramework)
    .createQueryBuilder('appFramework')
  const res = await qbBase.clone().where('appFramework.id = :appFrameworkId', { appFrameworkId: 6 }) // Parameters cannot be set after Clone
```
### Expected Behavior
  appFrameworkId Should be 6
### Actual Behavior
Error: QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':appFrameworkId 

### My Environment

"typeorm": "^0.2.41"

node v12.22.0

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by zq0904** [comment]
Currently I can only use.setParameters({appFrameworkId: 6}) before Clone.
But I don't think it's a good idea
```ts
  const qbBase = await connection
    .getRepository(AppFramework)
    .createQueryBuilder('appFramework')
    .setParameters({ appFrameworkId: 6 })
    
  const res = qbBase.clone().where('appFramework.id = :appFrameworkId')
```

**Comment by Ginden** [comment]
> "typeorm": "^0.2.41"

TypeORM 0.2 is not supported anymore.

**Comment by zq0904** [comment]
> ```ts
> qbBase
> ```

The latest version of "Typeorm ": "^0.3.7" is still not supported
