### ISSUE TITLE
@Entity() Error: Syntax not yet supported

### ISSUE THREAD

**Issue by khteh** [typeorm/typeorm#9285]
## Issue Description
Both Data Mapper and Active Record patterns show the same error.
### Actual Behavior

```
build/index.d.ts → build/index.d.ts...
[!] (plugin dts) Error: Syntax not yet supported

  1 | import { Entity, Column } from "typeorm"
  2 | import { EntityBase } from "./EntityBase"
> 3 | declare @Entity()
    | ^^^^^^^
  4 | class Student extends EntityBase {
  5 |     @Column()
  6 |     public firstName: string
Domain/Entities/Student.ts
Error: Syntax not yet supported

  1 | import { Entity, Column } from "typeorm"
  2 | import { EntityBase } from "./EntityBase"
> 3 | declare @Entity()
    | ^^^^^^^
  4 | class Student extends EntityBase {
  5 |     @Column()
  6 |     public firstName: string
    at Transformer.convertStatement (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1248:19)
    at new Transformer (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1177:18)
    at convert (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1168:25)
    at Object.transform (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1484:31)
    at transformFile (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1588:50)
    at Object.transform (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1601:24)
    at /usr/src/Node.JSRestAPI/node_modules/rollup/dist/shared/rollup.js:22826:37

npm ERR! Lifecycle script `rollup` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: core@1.0.0 
npm ERR!   at location: /usr/src/Node.JSRestAPI/src/core 
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: core@1.0.0 
npm ERR!   at location: /usr/src/Node.JSRestAPI/src/core 
```

### Steps to Reproduce

1.
2.

`EntityBase.ts`:
```
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity } from "typeorm"
@Entity()
export abstract class EntityBase extends BaseEntity {
    @PrimaryGeneratedColumn()
    public id: number
    @Column()
    public created: Date
    @Column()
    public modified: Date
    constructor() {
        super();
        this.created = new Date();
    }
}
```
`Student.ts`:
```
import { Entity, Column } from "typeorm"
import { EntityBase } from "./EntityBase"
import { Teacher } from "./Teacher"
@Entity()
export class Student extends EntityBase {
    @Column()
    public firstName: string

    @Column()
    public lastName: string

    @Column({ unique: true })
    public email: string

    @Column()
    public isSuspended: boolean

    @ManyToMany(() => Teacher)
    @JoinTable()
    public teacher: Teacher[]

    constructor(first: string, last: string, email: string, isSuspended?: boolean) {
        super();
        this.firstName = first;
        this.lastName = last;
        this.email = email;
        this.isSuspended = isSuspended ?? false;
        this.teacher = [];
    }
}
```
### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Ubuntu 22.04         |
| Node.js version     | v18.7.0 | 
| Typescript version  | 4.7.4 | 
| TypeORM version     | 0.3.7  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ No, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
This is not related to TypeORM - it's TypeScript misuse. You can't `declare` class and decorate it.

**Comment by khteh** [comment]
Sorry, I don't understand. I do according to https://github.com/typeorm/typeorm What's wrong with my code? What do you mean "misuse"?
```
import { Entity, PrimaryGeneratedColumn, Column } from "typeorm"

@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    firstName: string

    @Column()
    lastName: string

    @Column()
    age: number
}
```

**Comment by khteh** [comment]
How to declare the many-to-many relationship table between 2 classes?
