### ISSUE TITLE
parameters are not set on subqueries when executing the main query

### ISSUE THREAD

**Issue by NoNameProvided** [typeorm/typeorm#929]
The `.where('innerRecipe.deleted = :deleted', { deleted: false })` syntax doesnt work on sub queries, they must be set via `setParameters` in the main query. 

I dont know if this is a bug or a feature, so I report it.

**Comment by pleerock** [comment]
Can you provide a more complete code sample? (or better failing test in a PR which I can quickly fix then)

**Comment by NoNameProvided** [comment]
Added a PR for this with the failing use-case.

The example code: 
```ts
const queryBuilder = connection.manager.createQueryBuilder(TestEntity, "testEntity");

const subQuery = queryBuilder
  .subQuery()
  .from(TestEntity, "innerTestEntity")
  .select(["id"])
  .where("innerTestEntity.id = :innerId", { innerId: 1 });

const mainQuery = queryBuilder
  .select("testEntity")
  .where(`testEntity.id IN ${subQuery.getQuery()}`);
  // .setParameters({innerId: 1}); // this would make it work, but subqueries should set their own parameters on execution
```

This would generate the following query: 

```sql
SELECT "testEntity"."id" AS "testEntity_id", "testEntity"."name" AS "testEntity_name" 
FROM "test_entity" "testEntity" WHERE "testEntity"."id" 
IN (SELECT id FROM "test_entity" "innerTestEntity" WHERE "innerTestEntity"."id" = :innerId)
```

**Comment by pleerock** [comment]
done. will be released in next version

**Comment by NoNameProvided** [comment]
Thanks

**Comment by chriszrc** [comment]
Are subqueries so new that they haven't made it to the documentation yet? Also, are subqueries only supported in the where clause, or can you create queries with an outer and inner query?

https://www.google.com/search?q=subquery+site%3Ahttps%3A%2F%2Ftypeorm.github.io%2F&oq=subquery+site%3Ahttps%3A%2F%2Ftypeorm.github.io%2F

**Comment by pleerock** [comment]
If you are looking for the latest documentation see [here](https://github.com/typeorm/typeorm/tree/master/docs). See about [subqueries here](https://github.com/typeorm/typeorm/blob/master/docs/query-builder.md#using-subqueries). Once 0.1.0 final is close to release I'll finish docs and upload into website

**Comment by vance** [comment]
that subqueries link is dead 🔢

**Comment by pleerock** [comment]
Ive updated link. Also new docs are available on site now (select query builder section).

**Comment by joelgon** [comment]
I had a similar problem today, I made a subquery using my custom repository, the query didn't seem to work, using getQuery it was where('paramter = :paramter') but I found that getQuery doesn't return the query with the values ​​passed, in the end I found that getOne and getMany apparently only return the entity, as I used the subquery to create a new column I needed to use getRawOne or getRawMany
![Screenshot_20211114_190712](https://user-images.githubusercontent.com/18372364/141700483-42da8d71-252f-4a2b-a759-e3e9e300eaa8.png)

**Comment by NoNameProvided** [comment]
This is a 4-year-old ticket. Generally, you are always better off creating a new issue and linking back to the old one for reference than necromancing old issues.
