### ISSUE TITLE
No way to create unique null index Postgres

### ISSUE THREAD

**Issue by arnmishra** [typeorm/typeorm#9295]
### The Problem

There is currently no support (that I've found) to create unique null indices i.e. those that exist in Postgres. Specifically, thinking of an index like `CREATE UNIQUE INDEX i_nulltest ON nulltest ((x IS NULL)) WHERE x IS NULL;` like from https://www.enterprisedb.com/postgres-tutorials/postgresql-unique-constraint-null-allowing-only-one-null. I need to create an index like that and have no way of adding an index of that format.

### The Solution

The solution might be creating complex `@Index` decorators. Something like:
`@Index([{field: 'Field1', isNull: False, field: 'Field2', isNull: True}])` => 
`CREATE UNIQUE INDEX index ON table ("Field1", ("Field2" IS NULL))`

### Relevant Database Driver(s)

I know its relevant to postgres, not sure about the others

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

Normally would be happy to contribute but unfortunately it's a busy time

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
You can do:

```ts
@Index(['foo', 'bar'], {unique: true, where: '"foo" IS NULL'})
```

**Comment by arnmishra** [comment]
Adding `'"foo" IS NULL` in the where clause doesn't do the same thing as adding `"foo" IS NULL` in the conditional expression.

From what I understand,

`CREATE UNIQUE INDEX index ON BAR (foo) WHERE foo IS NULL;` -> this creates a unique index on all foo values but only considers rows where foo is null. However, postgres' default action is to allow multiple NULL values even with a unique index (its unique for non-null values) so this would still allow you to insert 2 entries into `BAR` where `foo IS NULL`.

`CREATE UNIQUE INDEX index ON BAR (foo IS NULL);` -> this overcomes the default action to only allow 1 null entry for foo in `BAR`. So if you try to insert 2 entries into `BAR` where `foo IS NULL`, it would violate the unique constraint.

I'm trying to achieve the 2nd option instead of the first. The example you gave handles the first option instead I believe.

**Comment by Ginden** [comment]
@arnmishra As workaround, I recommend adding additional column, add `Check()` and two indexes.

For example:

```
@Check("alwaysZero" = 0)
@Index(['alwaysZero'], {unique: true, where: '"foo" IS NULL'})
@Index(['foo'], {unique: true, where: '"foo" IS NOT NULL'})
class Foo {
   @Column('smallint', {default: 0})
   alwaysZero = 0;
   
   @Column({nullable: true})
   foo: string;
}

> Indices on arbitrary expressions aren't planned

Postgres 15 will add support this natively, though: https://blog.rustprooflabs.com/2022/07/postgres-15-unique-improvement-with-null
