### ISSUE TITLE
Error: Index contains column that is missing in the entity - @Index isn't using column name from @Column

### ISSUE THREAD

**Issue by chriszrc** [typeorm/typeorm#930]
With an entity like this:

```
@Entity()
@Index(["country","iso3","region","name","rei_name"], { unique: true })
export class BurdenRegion implements Region {

    @PrimaryColumn()
    @Column({ length: 56 })
    country?: string;

    @PrimaryColumn()
    @Column({ length: 6})
    iso3?: string;

    @PrimaryColumn()
    @Column({ length: 12})
    region?: string;

    @PrimaryColumn()
    @Column({ length: 56})
    name?: string;

    @PrimaryColumn()
    @Column({name:"rei_name",length: 5})
    reiName?: string;
}
```

I get the following error:

`Index contains column that is missing in the entity: rei_name`

I want rei_name to be called reiName in the entity, so I added the column name property

`@Column({name:"rei_name",length: 5})`

But it's not being used. If I change the @Index to use the entity name like this:

`@Index(["country","iso3","region","name","reiName"], { unique: true })`

I get another error:

`error: column BurdenRegion.reiName does not exist`

So I'm not sure how to configure this properly?

**Comment by pleerock** [comment]
Actually `BurdenRegion.reiName` is correct one since Index decorator expects property names, not database column names. Adding indices expert - mr. @iz-iznogood

**Comment by iz-iznogood** [comment]
Hi all

this is the proper declaration, it works like a charm

```ts
@Entity()
@Index(["country", "iso3", "region", "name", "reiName"], { unique: true })
export class BurdenRegion /* implements Region */ {

  @PrimaryColumn({ length: 56 })
  country?: string;

  @PrimaryColumn({ length: 6 })
  iso3?: string;

  @PrimaryColumn({ length: 12 })
  region?: string;

  @PrimaryColumn({ length: 56 })
  name?: string;

  @PrimaryColumn({ name: "rei_name", length: 5 })
  reiName?: string;
}

```

**Comment by iz-iznogood** [comment]
I believe this issue can be resolved

**Comment by chriszrc** [comment]
Hmm, I did try that, see the initial post:

> If I change the @index to use the entity name like this:
> @Index(["country","iso3","region","name","reiName"], { unique: true })
> 
> I get another error:
> 
> error: column BurdenRegion.reiName does not exist
> 

And in the meantime, I did just change the column name to "rei" so that all the naming could be the same (so now more special name in `  @PrimaryColumn({ name: "rei_name",`), and everything just works great now. I could put together a small example if the source of this error isn't obvious-

**Comment by iz-iznogood** [comment]
So that I can understand, does it work or not ? Because you say 

> and everything just works great now

But in your initial example you used **Column** and **PrimaryColumn** decorators on the same property which duplicated columns (I am not really sure what else it did to metadata) and I only used **PrimaryColumn** which is the correct thing to do.

Also I used the latest version

Anyways in my case all works great.
If you have an example that it does not work please post it

Thanks

**Comment by chriszrc** [comment]
Hi, well I changed in the database the column `rei_name` go just `rei`, so now the db column has the same name as the entity column, which is also now renamed to `rei`, and now it just all work. Oh, I didn't catch the the change to just PrimaryColumn, I will try that as well, thanks!!
