### ISSUE TITLE
UpdateQueryBuilder<Entity>

### ISSUE THREAD

**Issue by nguyendev97** [typeorm/typeorm#9325]
Hello, I have an issue  when building in Nestjs `UpdateQueryBuilder<Entity>;`

![image](https://user-images.githubusercontent.com/110370494/186881759-fb81ff8b-117d-4ae9-9f81-ceb2e085ea8a.png)

**Comment by jschirrmacher** [comment]
I can confirm

**Comment by baijii** [comment]
Same here. Also with Nestjs. Typescript 4.8.2, TypeORM 0.3.7
Downgrading TS to 4.7.3 again did not the trick for me and I don't know why. Should definitely not being closed. Or at least a link to the other issue / PR / workaround…

**Comment by Morl99** [comment]
@nguyendev97 we also face this issue, can you explain why you closed this issue? Maybe we can reopen it?
If not, we should recreate it.
