### ISSUE TITLE
Migrations CLI fail with error: TypeError: dataSourceFileExports is not iterable

### ISSUE THREAD

**Issue by bobsingor** [typeorm/typeorm#9327]
### Steps to Reproduce

I am following the documentation and installing typeORM with the command:
`npx typeorm init --name MyProject --database postgres`

running migrations with this command:
`yarn typeorm migration:show -d ./src/data-source.ts`

will fail with the error: 
`TypeError: dataSourceFileExports is not iterable
    at Function.loadDataSource (/Users/GitHub/MyProject/src/commands/CommandUtils.ts:37:34)
    at async Object.handler (/Users/GitHub/MyProject/src/commands/MigrationShowCommand.ts:27:26)`

data-source.ts looks like this:

```typescript
import "reflect-metadata"
import { DataSource } from "typeorm"
import { User } from "./entity/User"

export const AppDataSource = new DataSource({
    type: "postgres",
    host: "localhost",
    port: 5432,
    username: "test",
    password: "test",
    database: "test",
    synchronize: true,
    logging: false,
    entities: [User],
    migrations: [],
    subscribers: [],
})

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      MacOS    |
| Node.js version     | v18.8.0  | 
| Typescript version  | 4.5.2  | 
| TypeORM version     | 0.3.8  | 

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by bobsingor** [comment]
It looks like that dataSourceFileExports needs to be an object:
https://github.com/typeorm/typeorm/blob/68e8f2289487ad21c18fb7b93754788a02199ee4/src/commands/CommandUtils.ts#L27-L34

And here we are trying to iterate an object what is not allowed
https://github.com/typeorm/typeorm/blob/68e8f2289487ad21c18fb7b93754788a02199ee4/src/commands/CommandUtils.ts#L37

Here it says iterating over object is not allowed:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/is_not_iterable#iterating_over_object_properties

**Comment by danielroccha** [comment]
+1

**Comment by d-michail** [comment]
I am also experiencing the same problem!

**Comment by IzaqueNunes** [comment]
+1

**Comment by emboh** [comment]
I got the same error message. I've migrated from v8 to v9 and have the same problem when using cli command.

**Comment by danielroccha** [comment]
Hi Guys, until now I Just fix this problem doing a downgrade to 0.3.4. Hope can help you during this moment.

**Comment by backnight** [comment]
Downgrade to 0.3.4 temporarily solved the issue on my side.

Also, don't forget to **force the version** "0.3.4" and not set it like "^0.3.4" because in that case, it will be the buggy 0.3.8 version that will be installed ;)

**Comment by marciovalim** [comment]
Thanks, fixed for me

**Comment by boclairtemgoua** [comment]
Downgrade to 0.3.7 solved the issue on my side (temporary solution).

Also, don't forget to force the version "0.3.7" in package.json and not set it like "^0.3.7" because in that case, it will be the buggy 0.3.8 version that will be installed ;)

**Comment by fghbittencourt** [comment]
+ 1

**Comment by Fasunle** [comment]
I also downgraded from version 0.3.8 to 0.3.7. I think the bug is still present but the conversation was closed in #9329 by @bobsingor. Please help us review this.

**Comment by pleerock** [comment]
`0.3.9` contains the fix now.

**Comment by Fasunle** [comment]
> `0.3.9` contains the fix now.

Thank you so much for your hard work.
