### ISSUE TITLE
websql: after error creating table, `temporay_foo` table is not deleted

### ISSUE THREAD

**Issue by hgoebl** [typeorm/typeorm#933]
Tried to use unsupported data type (`char` instead of `character`).

Table creation first time aborted with error "data type not supported" when creating temporary_foo table.

After I fixed the problem in my code, further processing of schema sync stopped due to "table temporary_foo already exists".

I suppose schema-sync should better drop temporary table after error.

**Comment by hgoebl** [comment]
Is there a test harness for type="websql" connections running in browser? I haven't found any.

*Some more findings:*

Seems like schema-sync always tries to recreate tables. When doing this, the INSERT INTO … SELECT causes an SQL error, because it's missing column names. In my log, it looks like this:
```
executing query:  CREATE TABLE "temporary_employee" ("id" varchar(16) NOT NULL, "lastName" varchar(40) NOT NULL, "firstName" varchar(40) NOT NULL, "gender" smallint NOT NULL, "abbr" varchar(8), "teaches" boolean NOT NULL, "emailAddress" varchar(60), "mobilePhone" varchar(20), "landlinePhone" varchar(20), "others" varchar(255), "privacyFlags" integer NOT NULL DEFAULT 0, "schoolId" varchar(16), PRIMARY KEY(id))
```
Next log entry:
```
executing query:  INSERT INTO "temporary_employee"() SELECT  FROM "employee"
```

```
SQLError = {
code: 5,
message: "could not prepare statement (1 near ")": syntax error)"
}
```

How to reproduce:
1. connect to WebSQL database with `autoSchemaSync: true` => no error, db is created fine.
2. reload web-application with same param => error after above log.

I'll use 'autoSchemaSync: !localStorage.schemaCreated' as a workaround. Would like to help you, but I'm still quite new to this stuff.

BTW: is there a table `sqlite_master` in WebSQL? Seems a bit strange to me. And could be the reason why typeORM always wants to recreate tables. I'd really like to know how schema-sync internally works…

**Comment by pleerock** [comment]
TypeORM wants to recreate tables because there is no ALTER statements support in sqlite/websql at all. Each time when something in entity was changed it creates a new table, copy everything from old table into a new table and removes old table. There is no other way to alter tables somehow in sqlite/websql.

What you are saying looks like a bug. I didn't checked websql functionality for a while. Unfortunately there are no tests for websql driver because of its browser-specifics. But we can do that for sure. Are you seriously planning to use it? The reason why ask is because websql is kinda experimental feature in TypeORM because of the following issues with it:

* not popular. Maybe you are the first one who tried it, Im not sure
* websql is not supported by all browsers and there are no plans to support, because...
* websql is deprecated web standard, unfortunately 
* there are really strange things in its implementation, at least in chrome where I checked it. It looked like modified by google sqlite version just like in android

If you still have a plans to use it, we can work together to improve websql support in TypeORM.

**Comment by hgoebl** [comment]
Thanks @pleerock.
I'm not really planning to use WebSQL. I'm going to use SQLite with electron and Cordova-SQLite-Plugin in Ionic app. I'm just using WebSQL because I haven't managed to have a setup with electron and native node module SQLite. It's causing trouble, because `electron-rebuild` doesn't work as expected, so I tried to use WebSQL just to proceed with "real" features. So please don't waste time on WebSQL. I had to tweak a lot and include `types: [node]` because typeORM includes MongoDB drivers which heavily depend on node `Buffer` and the like. I also tried to divide core typeORM code from drivers, so one can include only used drivers, but the typeORM code is too interlacing for that and I think it would be a lot of work to split up the code.

Another thing: SQLite in Android is able to "ALTER TABLE ...". Are you sure SQLite lacks this feature? And I still ask myself why typeORM tries to recreate schema when there is absolutely no change in schema. Could you please point me to the file where schema-change is (wrongly) detected? I'd like to step through with debugger, maybe I find something relevant for non-WebSQL drivers…

**Comment by pleerock** [comment]
> And I still ask myself why typeORM tries to recreate schema when there is absolutely no change in schema. 

this looks like a bug

> Could you please point me to the file where schema-change is (wrongly) detected? 

Everything schema sync related starts with [RdbmsSchemaBuilder](https://github.com/pleerock/typeorm/blob/99dfeb7647cc4f1659116ca5c263be5ec9eb9290/src/schema-builder/RdbmsSchemaBuilder.ts) 

> I had to tweak a lot and include types: [node] because typeORM includes MongoDB drivers which heavily depend on node Buffer and the like

This is discussed in @daniel-lang 

btw @daniel-lang we need to do something here, looks like ionic users have a bad experience working with typeorm, we need to fix that

**Comment by daniel-lang** [comment]
Adding
```json
"typeRoots": [
   "node_modules/@types"
]
```
to `tsconfig.json` is the only option for now. But I'm trying to find a way to improve the experience.

**Comment by pleerock** [comment]
@daniel-lang problem with following approach (as I told earlier) that this approach works only with non-typescript written libraries. If some library written in typescript you'll need to include them in typeRoots as well if you are using it in the project, for example:

```
"typeRoots": [
   "node_modules/@types",
   "node_modules/reflect-metadata"
]
```

otherwise compiler will complain. This is very non obvious for users and without explanation to them they will have hard-to-guess-reason issues

**Comment by MaximBalaganskiy** [comment]
The whole bunch of code in WebsqlQueryRunner related to getting tables is commented out. This seems to be the reason for failing synchronisation. What was the reason for turning it off?

WebSql is useful during dev so that an app successfully runs in browser mode.

**Comment by pleerock** [comment]
Because of multiple websql limitations. We'll think how to fix those issues in the future versions. Also we are waiting sqljs to be completely implemented, it should become a better alternative to websql.

**Comment by davidmpaz** [comment]
Hi,

I am facing same issue here. Being an Ionic user, every time the page load I get the error too.

Same situation as @hgoebl, I am only using it on development. Real usage will be cordova-sqlite. I tried to catch the `SQLError` in many places in my app but no success.

My stack trace:
```
ERROR Error: Uncaught (in promise): QueryFailedError: [object SQLError]
QueryFailedError: [object SQLError]
    at new QueryFailedError (QueryFailedError.js:25)
    at WebsqlQueryRunner.js:176
    at new QueryFailedError (QueryFailedError.js:25)
    at WebsqlQueryRunner.js:176
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:4140)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at <anonymous>
```
For me the problem would be solved if i could somehow catch and ignore the error. Currently error seems lost in the stack trace somewhere in angular, never gets up to me, at least  have failed to catch it.

Only reference to my code in trace is: 

`platformBrowserDynamic().bootstrapModule(AppModule);` 

which is actually my entry point and from there can not catch the error.

Is there a way to register some custom error handler into `WebsqlQueryRunner.js` for example? So I can decide whether re-throw error or just ignore it? I know is not nice but would do the trick for me.

Hopefully `sqljs` could be used any soon. For development it is faster than using the emulator.

Thanks in advance,
David

**Comment by daniel-lang** [comment]
@davidmpaz Synchronizing your database is still not fully supported in websql, so will get sql errors because wrong queries are generated. I would suggest you use `sqljs` as it works in the browser and supports synchronization.

**Comment by davidmpaz** [comment]
Hi @daniel-lang ,

thanks for the hint! I tried to use sql.js but I am getting an error. From trace, i see this:
[`this.sqlite = window.SQL;`](https://github.com/typeorm/typeorm/blob/0.1.10/src/driver/sqljs/SqljsDriver.ts#L207) 
is not initializing properly. In my chrome `Window.SQL` is undefined. I am missing the place where this SQL is initialized.

I tried also to import `sql.js` with no success.

```
Error: Uncaught (in promise): TypeError: Cannot read property 'Database' of undefined
TypeError: Cannot read property 'Database' of undefined
    at SqljsDriver.createDatabaseConnectionWithImport (http://localhost:8100/build/vendor.js:74801:55)
    at SqljsDriver.load (http://localhost:8100/build/vendor.js:74697:29)
    at SqljsDriver.createDatabaseConnection (http://localhost:8100/build/vendor.js:74787:25)
    at SqljsDriver.<anonymous> (http://localhost:8100/build/vendor.js:74638:51)
    at step (http://localhost:8100/build/vendor.js:74599:23)
    at Object.next (http://localhost:8100/build/vendor.js:74580:53)
    at http://localhost:8100/build/vendor.js:74574:71
    at new t (http://localhost:8100/build/polyfills.js:3:15044)
    at __awaiter (http://localhost:8100/build/vendor.js:74570:12)
    at SqljsDriver.connect (http://localhost:8100/build/vendor.js:74632:16)
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at c (http://localhost:8100/build/polyfills.js:3:13221)
    at http://localhost:8100/build/polyfills.js:3:14067
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4500:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
    at o (http://localhost:8100/build/polyfills.js:3:2203)
    at XMLHttpRequest.invoke (http://localhost:8100/build/polyfills.js:3:10985)
```
My configuration to initialize database is:
```typescript
if (isBrowser(this.platform)) {
    dbOptions = {
        type: 'sqljs',
        autoSave: true,
        location: 'products',
    } as SqljsConnectionOptions;
}

return createConnection(Object.assign(dbOptions, {
    entities: this.getModelsToLoad(),
    synchronize: true,
    logging: true,
}));
```

Any idea on what should I do?

Thanks in advance,
David

**Comment by davidmpaz** [comment]
Solution to previous problem was to add the `sql.js` file into `index.html` and load library outside of typescript.

Now I am getting `FOREIGN KEY constraint failed` errors on application reload, but I guess it is related to my models definitions.

Thanks!

**Comment by ptea** [comment]
@davidmpaz I try to use sqlite with TypeORM. Did you solve the `FOREIGN KEY constraint failed` error? The old to be replaced table cannot be dropped while having foreign key constraints on other tables.

**Comment by pleerock** [comment]
@ptea try to install `next` (npm i typeorm@next)

**Comment by davidmpaz** [comment]
@ptea as stated, use `typeorm@next` the issue dealing with `FOREIGN KEY constraint failed` error with sqlite is this:  #1530

**Comment by ptea** [comment]
@pleerock `next` partly solved my problem, the startup doesn't fail now. But, changing the model by adding a column still fails.
@davidmpaz Issue #1530 is closed but I still get the error in `0.2.0-alpha.28`. I would rather TypeORM not to drop my tables when a simple `ALTER TABLE deck ADD description varchar;` could solve the model change.

**Comment by davidmpaz** [comment]
I am not sure whether I am right or not. Hope some more experienced member clarify this to you. But I am afraid that your scenario is a fit for migrations. Take a look on how migrations works

**Comment by daniel-lang** [comment]
@ptea How are you adding your column? With a migration or by synching your entities?

**Comment by ptea** [comment]
@daniel-lang With synching turned on. I haven't used migration yet. My workaround is either deleting the db-file or migrating with an external tool.

**Comment by pleerock** [comment]
@ptea please provide a reproduction repository with `sqlite` database used and I'll take a look on your issue.

**Comment by pleerock** [comment]
as discussed in #1923 we drop websql support in favour of sql.js
