### ISSUE TITLE
Typeorm CLI not usable - Running CLI returns: TypeError: dataSourceFileExports is not iterable

### ISSUE THREAD

**Issue by Kyle1297** [typeorm/typeorm#9330]
### Expected Behavior

To be able to easily run and generate migrations via typeorm CLI.

### Actual Behavior

```
// include the output in code tags like these!
```

```
➜  typeorm-bug git:(master) ✗ npm run typeorm:migrate

> typeorm-bug@1.0.0 typeorm:migrate
> typeorm-ts-node-commonjs migration:run --dataSource ./typeorm.config.ts

Error during migration run:
TypeError: dataSourceFileExports is not iterable
    at Function.loadDataSource (~/typeorm-bug/src/commands/CommandUtils.ts:37:34)
    at async Object.handler (~/typeorm-bug/src/commands/MigrationRunCommand.ts:42:26)
```

```
➜  typeorm-bug git:(master) ✗ npm run typeorm:generate --name=Testing                          

> typeorm-bug@1.0.0 typeorm:generate
> typeorm-ts-node-commonjs migration:generate ./src/migration/$npm_config_name --dataSource ./typeorm.config.ts

Error during migration generation:
TypeError: dataSourceFileExports is not iterable
    at Function.loadDataSource (~/typeorm-bug/src/commands/CommandUtils.ts:37:34)
    at async Object.handler (~/typeorm-bug/src/commands/MigrationGenerateCommand.ts:73:26)
```

### Steps to Reproduce

Repo available here: https://github.com/Kyle1297/typeorm-bug.git

1. Run `npm i` command
2. Run `npm start` command
3. Run `npm run typeorm:migrate` and `npm run typeorm:generate --name=Testing` commands to observe errors

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     macOS Monterey 12.5.1     |
| Node.js version     | x.y.zzz  |  16.13.1
| Typescript version  | x.y.zzz  | 4.5.2
| TypeORM version     | x.y.zzz  | 0.3.8

### Additional Context

This also occurs across multiple 3+ typeorm versions + in a Node 16 docker container running NestJS as well. For this bug, I removed all this extra stuff to create this minimal, reproducible example. 

I previously was working with typeorm version 0.2.31 and things were all good.

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 -  ✅  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by rbnayax** [comment]
This bug was introduced in #8917 where they used (accidentally in my opinion) (`for...of`) [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of]instead of (`for...in`)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in]
