### ISSUE TITLE
ormconfig.json file not valid

### ISSUE THREAD

**Issue by checkwoodson** [typeorm/typeorm#9338]
配置了ormconfifg.json是无效的。
![image](https://user-images.githubusercontent.com/33786022/187649179-95cc37ad-f326-43dd-8253-ac6e560d0174.png)

插件是安装好了，现在的唯一方案是只能在TypeormModule.forroot()中插入配置

**Comment by Abhishek-thakur1** [comment]
The following should work:
`import { ConnectionOptions } from 'typeorm';
export default {
  type: 'mysql',
  host: 'localhost',
  port: 3306,
  username: 'root',
  password: 'root',
  entities: ['dist/**/*.entity{.ts,.js}'],
  synchronize: true,
} as ConnectionOptions;`

**Comment by Ginden** [comment]
Please, fill this issue in English.

**Comment by checkwoodson** [comment]
Use ormconfig.json to import into the nestjs project is prompted not to support the driver, the error reported on the figure shown
