### ISSUE TITLE
"bigNumberStrings:false" is not works for postgres

### ISSUE THREAD

**Issue by frogeater1** [typeorm/typeorm#9341]
## Feature Description
"bigNumberStrings:false" is not works for postgres
### The Problem
it seems to only support mysql and  I need postgres suport 

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?
 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by danmana** [comment]
Added a PR to enable the equivalent version for the Postgres driver.

Note: the pg driver does not use the same mechanism as the MySQL one. Notably, only `bigint` numbers can be parsed by setting `parseInt8: true`
