### ISSUE TITLE
queryBuilder keeps ignoring some explicitly selected columns in both .select() and .insert().values()

### ISSUE THREAD

**Issue by Shassk** [typeorm/typeorm#9348]
## Issue Description
TypeORM queryBuilder ignores some fields explicitly set when generating .insert().values(...) query or returning values from a query with .select/.addSelect. Especially it's a big problem for foreign keys. Possibly related to those fields being mostly `bigint`.

### Expected Behavior
Used entity:
```
@Entity('clientInfo')
export class ClientInfoEntity {
    @PrimaryColumn()
    id?: number;
    @ManyToOne(() => ClientEntity, (client) => client.id, {
        onDelete: 'CASCADE',
    })
    @JoinColumn({ name: 'clientId', referencedColumnName: 'id' }) // client.id is bigint
    client?: ClientEntity;

    @ManyToOne(() => DataFieldEntity, (dataField) => dataField.id, {
        cascade:true,
        eager:true,
    })
    @JoinColumn({ name: 'dataFieldId', referencedColumnName: 'id' })
    dataField?: DataFieldEntity;
    @Column()
    dataFieldId?: DataFieldEntity['id'];

    @Column({ nullable: true })
    value?: string;
}
```
Select query builder:
```
await getRepository('clientInfo')
    .createQueryBuilder(clientInfo)
    .select('clientInfo.id', 'id')
    .addSelect(`clientInfo.clientId`, `clientId`)
    .getMany()
```
Expected data:
```
[
  { id: 35, dataFieldId: 1, value: 'test', clientId: null },
  { id: 32, dataFieldId: 1, value: 'test', clientId: null },
  { id: 36, dataFieldId: 5, value: '380114455667', clientId: null }
  { id: 33, dataFieldId: 5, value: '380111122334', clientId: '34' }
]
```
Insert or update query builder:
```
getConnection()
    .createQueryBuilder()
    .insert()
    .into('clientInfo')
    .values(docs) // docs = expected output from above with 4 fields
    .getQuery()
```
Expected generated query:
```
INSERT INTO "clientInfo"("id", "dataFieldId", "value", "clientId") VALUES ($1, $2, $3, $4), ($5, $6, $7, $8), ($9, $10, $11, $12), ($13, $14, $15, $16) ON CONFLICT ( "id" ) DO UPDATE SET "dataFieldId" = EXCLUDED."dataFieldId", "value" = EXCLUDED."value", "clientId" = EXCLUDED."clientId"
```

### Actual Behavior

Actually received data from the select query, clientId is missing:
```
[
  { id: 35, dataFieldId: 1, value: 'test' },
  { id: 32, dataFieldId: 1, value: 'test' },
  { id: 36, dataFieldId: 5, value: '380114455667' }
  { id: 33, dataFieldId: 5, value: '380111122334' }
]
```
Generated insert or update query, clientId is just ignored:
```
INSERT INTO "clientInfo"("id", "dataFieldId", "value", "clientId") VALUES ($1, $2, $3, DEFAULT), ($4, $5, $6, DEFAULT), ($7, $8, $9, DEFAULT), ($10, $11, $12, DEFAULT) ON CONFLICT ( "id" ) DO UPDATE SET "dataFieldId" = EXCLUDED."dataFieldId", "value" = EXCLUDED."value", "clientId" = EXCLUDED."clientId"`
```
### Steps to Reproduce

Entity, queries and data as above.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 8.1 x64  |
| Node.js version     | 16.14.0  | 
| Typescript version  | 4.7.4  | 
| TypeORM version     | 0.2.45  | 

### Additional Context

While first issue can be somewhat bypassed by using .getRawMany() instead the second one has no other alternatives but to use raw SQL query instead.
### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Ginden** [comment]
You need to declare `clientId` column explicitly:

```
@Column()
clientId: ...
```

**Comment by dannybster** [comment]
Agreed; this leaves me in a position of hand cranking SQL queries by manipulating strings.
