### ISSUE TITLE
Quickstart documentation is not up to date

### ISSUE THREAD

**Issue by gintsgints** [typeorm/typeorm#935]
It says @PrimaryColumn("int", { generated: true })
But shouldn't it be like @PrimaryGeneratedColumn() ?

**Comment by gintsgints** [comment]
Actually you have that second variant in readme. But first one gives error:

Argument of type '{ generated: boolean; }' is not assignable to parameter of type 'ColumnOptions'.
  Object literal may only specify known properties, and 'generated' does not exist in type 'ColumnOptions'.

**Comment by NoNameProvided** [comment]
This has been asked several times. @pleerock answer is

> You are right, docs are outdated. Currently website's docs are for 0.0.11. Im planning to update website docs once 0.1.0 final version is released. Expect this somewhere in the end of October, beginning of November. New docs will be based on this [directory](https://github.com/typeorm/typeorm/tree/master/docs).

**Comment by pleerock** [comment]
@gintsgints yeah sorry about that, I'll release 0.1.0 and publish a new documentation next month I believe

**Comment by gintsgints** [comment]
I am ready to test it out afterwards :)
