### ISSUE TITLE
[Question]: Negate support to Brackets

### ISSUE THREAD

**Issue by iz-iznogood** [typeorm/typeorm#937]
Hi how can I negate an expression created using Brackets ?
Or how can I negate an expression in general (without wrapping it into "NOT ( " + expressionString + ")"

 Thanks

**Comment by pleerock** [comment]
Only using string probably. Such a small string peaces in conditions of SQL query arent well covered by ORM. If you want to suggest something then it must be a detailed proposal for all possible operators
