### ISSUE TITLE
The column option 《transformer》 affects the result of the query condition generation

### ISSUE THREAD

**Issue by pwfyhao** [typeorm/typeorm#9381]
typeorm version:  0.3.9;

before code:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/36838341/190854220-57476099-f994-409d-b2f9-0a5b9cc7b55c.png">
<img width="617" alt="image" src="https://user-images.githubusercontent.com/36838341/190854258-c57e44cf-01ca-404a-bbd9-0bce137fe486.png">
result:
![image](https://user-images.githubusercontent.com/36838341/190854280-7d0db002-154d-41e7-b01a-8c066b040a52.png)

current:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/36838341/190854306-a8b3f02b-2a36-4d15-9543-e621d3083561.png">
result:
![image](https://user-images.githubusercontent.com/36838341/190854327-2e0db370-64b8-4206-b598-8dc536a61047.png)

Is this a feature or a BUG!!!

**Comment by ertl** [comment]
same problem here with typeorm 0.3.10.

It looks like all find-option operators are affected.

@pwfyhao did you found a workaround for this problem?
