### ISSUE TITLE
Question: persist entity declaring if it is update or insert

### ISSUE THREAD

**Issue by iz-iznogood** [typeorm/typeorm#942]
Hi, 

I checked that the persist and save methods try to either insert or update the entity by reloading the data from the DB.
In my case however I already have a snapshot of what the user sees in the client and I want to apply the operation he chose. For example:

1. the user decides to insert a new entity. I want to send it to db without querying to check if it exists. I saw that if the key is autogenerated you check if the value exists in order to decide on the operation. In my case I do not rely on the primary key but keep the action (insert, update, delete) in another attribute. Since I use autogenerated ids it is not a problem now but might be in the future.

2. the user updates an entity. I already have the "old" db values and I want to use them to create the update statement (with the modified values) and in case the entity is changed I will use optimistic concurrency to catch possible errors. I do not want to rely on the id to decide what the operation is.

To be clear I use a disconnected model and I want to playback the user operations exactly and use optimistic concurrency to check for errors.
I saw an update method in entity manager but no insert method. Is there a reason for this ?
Also the update still reloads from db. Would it be possible to skip this ?

Thanks

**Comment by pleerock** [comment]
yeah I was planning to change `update` method. Right now its very rough and temporary implementation that uses `save` method. We need to create updateQueryBuilder and use it instead. Same, we can create insert method and do same there - insert a new entity using insertQueryBuilder. You can make these changes

**Comment by iz-iznogood** [comment]
I just used the InsertQueryBuilder & UpdateQueryBuilder and they are beautiful.
Works like a charm.

I will do the changed you proposed however and send a PR.

Thanks

**Comment by pleerock** [comment]
I made changes to `update` method I was talking about
