### ISSUE TITLE
connection.getRepository(RepositoryName) thrown TypeError: Cannot add property 0, object is not extensible

### ISSUE THREAD

**Issue by harishajdarevic** [typeorm/typeorm#944]
Hello, 

I have weird issue. I don't know is problem on my or 'typeorm' side. 

I have following methods

**connectToDatabase() **
```
export function connectToDatabase(): Promise<Connection> {
    // If connection exist return promise of existing connection
    if (getConnectionManager().has('bimcontentmanager')) {
        return new Promise<Connection>((resolve) => resolve(getConnectionManager().get('bimcontentmanager')));
    }
    
    return getConnectionManager().create(ConnectionSettings).connect();
}
```

When application starts I run connectToDatabase() once and that method is in database.service.ts in Angular 2 application where I have @Injectable() databaseService with one attribute **behaviourSubject()**

```
@Injectable()
export class DatabaseService {
    databaseSubject: BehaviorSubject<Connection> = new BehaviorSubject(undefined);
}
```

What happens next. When I call method **connectToDatabase()** it returns Promise<Connection> which I resolve on a next way:

```
Observable.fromPromise(connectToDatabase())
                .map((connection) => {
                    this.databaseService.databaseSubject.next(connection); // **in database service in behaviourSubject I push the connection**
                });
```

So, where is the problem and what is weird. 

When I want to access my connection I do the following:

`const conn: Connection = this.databaseService.databaseSubject.getValue();`
and when I do 
`**console.log(conn)**` I get the following:

[link to photo](http://i.prntscr.com/me5DHGfTRPObKINUv_PrvA.png)

and when I do:

`conn.getRepository(Users)` I'm getting following error:

`effects.es5.js:270 Error: TypeError: Cannot add property 0, object is not extensible`
Here is full error stack-trace:
[Errors](http://i.prntscr.com/PM07qgMHTpmzpQswHGra9g.png)

But, what works for me?

If I do the following:

```
connectToDatabase().then(connection => {
  console.log(connection);
  connection.getRepository(Users);
});
```

**above example works** but weird is that the output of console.log(connection) is the same in above piece of code and when I get connection value from behaviorSubject().

Any advice, tip or help will be appreciated.

Thanks

**Comment by pleerock** [comment]
Its hard for me to understand your problem. Can you provide a short and complete example without using any third-party dependency (like angular and rxjs)?

**Comment by harishajdarevic** [comment]
@pleerock 

It is difficult to provide short and complete example in this case.

Basically what I achieved with above example is that I create connection and connect to database only once when application start and I store that Connection not Promise<Connection>.

So when I have Connection stored in one variable I expect that I can simply access to all methods of connection like connection.getRepository() and etc. 

But, it seems how there are some problems and I'm still struggling with that.

Thanks

**Comment by pleerock** [comment]
Yeah you should be able to do so. I don't believe that there are issues with orm, thats why Im asking to create a minimal example without extra dependencies. Without it showing a real problem I cannot help you.

**Comment by harishajdarevic** [comment]
@pleerock Problem is probably related to this 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_define_property_object_not_extensible

When I call
`Object.isExtensible(this.databaseService.databaseSubject.getValue())`

I'm getting false.

**Comment by harishajdarevic** [comment]
There was problem with ngrx-store-freeze package not related to typeorm. 

Can be closed. 

Everything works well now.
