### ISSUE TITLE
findOne({where: {id: null}}) returns the first item in the database

### ISSUE THREAD

**Issue by Sid-Turner-Ellis** [typeorm/typeorm#9446]
## Issue Description
-findOne where ID is null returns the first item in the database instead of null

### Expected Behavior
- If we try to find the record labelled with an id of null, the return should be null instead of the first item in the database

### Actual Behavior
- The first value in the database is returned

### Steps to Reproduce
- Run this with your own entity and see the first item logged to the console instead of null
```
    const item = await dataSource.getRepository(UserEntity).findOne({
      where: {
        id: null as any,
      },
    });
    console.log(item); // returns the first item

```
### My Environment

| Dependency          | Version  |
| Operating System    |   Mac os   |
| Node.js version     | 14  
| Typescript version  | 4.8.2
| TypeORM version     | 0.3.8

### Relevant Database Driver(s)
sqlite

### Are you willing to resolve this issue by submitting a Pull Request?
 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by iJhefe** [comment]
dup #9316

**Comment by pleerock** [comment]
Closing as duplicate.
