### ISSUE TITLE
No changes in database schema were found, when simple-enum is changed

### ISSUE THREAD

**Issue by ertl** [typeorm/typeorm#9457]
## Issue Description

When I change a value or add/remove one of the enum object given to the simple-enum tag. No changes in for the database schema where found.

### Expected Behavior

A migration is generated.

### Steps to Reproduce

1. change the enum and run migration:generate

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v16.17.1  | 
| Typescript version  | 4.7.2  | 
| TypeORM version     | 0.3.10  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by flmuel** [comment]
Same problem here, this is really annoying...

**Comment by Vista1nik** [comment]
Have same issue but with SQLite. Any workarounds?

Migration command won't change `CHECK "column_name" IN ('enum_val_1','enum_val_2,'enum_val_3')` to include updated enum values in scheme of column with "simple-enum" type.

**Comment by ertl** [comment]
Not so far. I had corrected the migration by hand. Fortunately, I havn't had many changes in enums so far.
