### ISSUE TITLE
Feature or documentation: how to add multiple "where conditions" on the same property with FindOptionsWhere ?

### ISSUE THREAD

**Issue by dawadam** [typeorm/typeorm#9466]
### What was unclear or otherwise insufficient?

How to add multiple "where conditions" on the same property with FindOptionsWhere ?

Exemple :

```
const whereCondition: FindOptionsWhere<EntityExemple> = {}

whereCondition.time = MoreThanOrEqual(from)
whereCondition.time = MoreThan(from2)
whereCondition.time = LessThan(to)

await repositoryEntityExemple.find({ where: whereCondition })
```
_ps : I know Between, but it's convenient for me, because not exclusive._

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by iJhefe** [comment]
it should be
```typescript
const whereCondition: FindOptionsWhere<EntityExemple>[] = [];
whereCondition.push({ time: MoreThanOrEqual(from) })
whereCondition.push({ time:  MoreThan(from2) })
whereCondition.push({ time: LessThan(to) })

await repositoryEntityExemple.find({ where: whereCondition })
```

or simply:

```typescript
const whereCondition: FindOptionsWhere<EntityExemple>[] = [
{ time: MoreThanOrEqual(from) },
{ time:  MoreThan(from2) },
{ time: LessThan(to) }
];

await repositoryEntityExemple.find({ where: whereCondition })
```

at docs:

https://github.com/typeorm/typeorm/blob/master/docs/find-options.md
https://github.com/typeorm/typeorm/blob/cdabaa30287d357c0ae994209e573f97f92dad22/docs/find-options.md#L105-L120

**Comment by dawadam** [comment]
This method make _OR_ condition, not _AND_ condition.

**Comment by mrtsven** [comment]
I would also like to know if it's possible to make AND conditions.

**Comment by iJhefe** [comment]
@dawadam what about #9489 ?
