### ISSUE TITLE
EntityManager#save always considers a Postgres array-type field to have changed

### ISSUE THREAD

**Issue by robinsummerhill** [typeorm/typeorm#948]
When using the User entity below (with an array-type field `permission`), the permissions field is always considered to be 'different' by Subject#computeDiffColumns and so is included in the update every time the entity is saved.

```javascript
@Entity('users')
export class User extends BaseEntity {

  @PrimaryGeneratedColumn('uuid')
  id: string;

  ...

  @Column('text', {isArray: true})
  permissions: string[];
  ...
}

```

Expected behaviour:
Array-type fields should diff'ed correctly.

**Comment by robinsummerhill** [comment]
As an aside, what is the rational behind reading the DB state of an instance, diff'ing with the in-memory state and then updating the differences? A complete save would be simpler and only require one DB hit. No?

If you require a partial update of an entity then you can use the 'update' methods (when they are implemented fully and don't just do a 'save').

**Comment by pleerock** [comment]
once I refactor `update` it will be very simple - it will just execute update on whatever you pass him. `save` method is much more complicated and it executes lot of small features orm has (subscribers, listeners, versioning, cascades, relation handle, etc.). Query will be required anyway in `save` method.

Regarding to your issue, it looks like a bug

**Comment by pleerock** [comment]
Thank you for your advices, your points does make sense and I'll think more about how to improve persistence process once I'll start refactoring it.

Issue with arrays difference will persist until that. The there 3 options how to resolve this issue:

* stay with current design and make JSON.stringify on both arrays and check strings
* stay with current design and simply ignore array - update it always when it presents
* rethink current design and always update no matter if something is changed or not, just like you suggested

**Comment by pleerock** [comment]
Okay, so after deeper investigation I came up to the second option:

> stay with current design and simply ignore array - update it always when it presents

Regarding to what you suggested - always update entities no matter if something is changed or not - it has more cons then pros. It looks okay for a simple object, but once cascades are in the game - there will be update query on each object saved by cascades no matter if they are really updated or not. This is not effective. So I decided to left current persistence system as it is. Regarding original issue with arrays, for now I don't have solution other then update arrays always, but maybe some new idea will came up in the future.

**Comment by ashleyww93** [comment]
This should not be an issue if TypeORM was as good as we all hoped it would be.

However, since it IS an issue (even if the people maintaining it don't believe us), if you change your database column to be jsonb type you'll find that it works as you would expect.

Here is what we had before:

```
    @Column('text', { array: true })
    @Field(() => [String], { nullable: true })
    tags!: string[];
```

And this is what we changed it to:

```
    @Column('jsonb', { default: '[]' })
    @Field(() => [String])
    tags!: string[];
```
