### ISSUE TITLE
Add Yandex Data Base driver 

### ISSUE THREAD

**Issue by alexey-marochkin** [typeorm/typeorm#9484]
It would be great to add support of open source [DataBase from Yandex company](https://ydb.tech).

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
