### ISSUE TITLE
Column options -> asExpression (excess NOT NULL or NULL options in SQL statement)

### ISSUE THREAD

**Issue by EvaldasMin** [typeorm/typeorm#9485]
## Issue Description
When parsing column decorator to SQL statement NOT NULL or NULL operators are always included in the statement no matter whether nullable column option was used or not.
Problem occurs when column decorator options also includes generated column expression, then when trying to create column from SQL statement exception is received.
Column for which exception is received:
```
@Column({
    type: "double",
    generatedType: "VIRTUAL",
    asExpression: "CASE WHEN `priceforapack` = 1 THEN `price` WHEN `priceforapack` =  0 THEN `price` * `quantity` ELSE 0 END",
    comment: "Amount",
})
amount: number;
```
### Expected Behavior

Expected SQL statement such as (this SQL statement does not include NOT NULL or NULL operators at all, so it is executed by MySQL without any exceptions):
```
ALTER TABLE `shopping_list_items` ADD `amount` double AS (CASE WHEN `priceforapack` = 1 THEN `price` WHEN `priceforapack` =  0 THEN `price` * `quantity` ELSE 0 END) VIRTUAL COMMENT 'Amount'
```

### Actual Behavior

Exception received:
```
code: 'ER_PARSE_ERROR',
errno: 1064,
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NOT NULL COMMENT 'Amount'' at line 1",
sqlState: '42000',
index: 0,
sql: "ALTER TABLE `shopping_list_items` ADD `amount` double AS (CASE WHEN `priceforapack` = 1 THEN `price` WHEN `priceforapack` =  0 THEN `price` * `quantity` ELSE 0 END) VIRTUAL NOT NULL COMMENT 'Amount'"
```

### Steps to Reproduce

```typescript
@Entity()
export class ShoppingListItems {
    @PrimaryGeneratedColumn({
        comment: 'Object ID'
    })
    @Column({
        type: "double",
        comment: "Quantity",
        nullable: false
    })
    quantity: number;
    @Column({
        type: "double",
        comment: "Price",
        nullable: false,
        default: 0
    })
    price: number;
    @Column({
        type: "boolean",
        comment: "Price for a pack",
        nullable: false,
        default: false
    })
    priceforapack: boolean;
    @Column({
        type: "double",
        generatedType: "VIRTUAL",
        asExpression: "CASE WHEN `priceforapack` = 1 THEN `price` WHEN `priceforapack` =  0 THEN `price` * `quantity` ELSE 0 END",
        comment: "Amount",
    })
    amount: number;
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 11 Pro 22621.674 |
| Node.js version     | 16.18.0 | 
| Typescript version  | 4.8.4  | 
| TypeORM version     | 0.3.10  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `mysql`           | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by kim00425** [comment]
same issue in mariaDB

**Comment by kim00425** [comment]
do you set driver type 'mysql'? if you set mysql you have to change to mariadb.
type: 'mariadb'

var isMariaDb = this.driver.options.type === "mariadb";
        if (isMariaDb && column.asExpression && ["VIRTUAL", "STORED"].includes((column.generatedType || "VIRTUAL"))) {
            // do nothing - MariaDB does not support NULL/NOT NULL expressions for VIRTUAL columns and STORED columns
        }

**Comment by EvaldasMin** [comment]
@kim00425 You are right, driver was set to 'mysql', when I changed it to 'mariadb' problem was gone.
Thanks for your help, I'm closing this issue.
