### ISSUE TITLE
ConnectionOptions does not allow variable assigned to type

### ISSUE THREAD

**Issue by vrachels** [typeorm/typeorm#949]
```
src/db.ts(14,39): error TS2352: Type '{ type: string; host: string; port: number; username: string; password: string; database: string;...' cannot be converted to type 'ConnectionOptions'.
  Type '{ type: string; host: string; port: number; username: string; password: string; database: string;...' is not comparable to type 'CordovaConnectionOptions'.
    Types of property 'type' are incompatible.
      Type 'string' is not comparable to type '"cordova"'.
```

Where I am trying to pass in the connection options.   ie:
```
const opts: ConnectionOptions = {
   type: wConfig.type,
   host: wConfig.host,
   ...
```

FWIW, I am actually trying to create a Postgres connection in this case.  Not sure why it chose to report cordova as the type   The Postgres config isn't directly exposed, either

my workaround:
```
const opts: ConnectionOptions = {
   type: 'postgres',
   host: wConfig.host,
   ...
};
(opts.type as any) = wConfig.type;
```

I'm not using any specific features of postgres, so any db connection as configured should be fine, and would/should not require code modification.

**Comment by pleerock** [comment]
You pass a string into `type`, but it expects a `string literal type`. You simply pass a wrong type there. If you really need to pass type in a variable, then cast it:

```ts
const opts: ConnectionOptions = {
   type: wConfig.type as DatabaseType,
   host: wConfig.host,
   ...
```

**Comment by vrachels** [comment]
DatabaseType does not seem to be exported for external use.  Am I missing something?

**Comment by pleerock** [comment]
yeah, I cant add it to external, you can use full path for now. Also you can do:

```
   type: wConfig.type as "postgres"
```

but it does not make sense because if you have a type stored inside a variable then it suppose to be other then postgres too

**Comment by pleerock** [comment]
I added export for DatabaseType, this change will be released in `0.1.1`

**Comment by localnet** [comment]
> You pass a string into type, but it expects a string literal type. You simply pass a wrong type there. If you really need to pass type in a variable, then cast it:
```typescript
const opts: ConnectionOptions = {
    type: wConfig.type as DatabaseType,
    host: wConfig.host,
    ...
```

With this code:
```typescript
this.typeormConnection = getConnectionManager().create({
    database: process.env.TYPEORM_DATABASE,
    entities: [`${this.modelPath}/*.js`],
    host: process.env.TYPEORM_HOST,
    password: process.env.TYPEORM_PASSWORD,
    port: Number(process.env.TYPEORM_PORT),
    type: process.env.TYPEORM_TYPE as DatabaseType,
    username: process.env.TYPEORM_USERNAME,
});
```
I am getting this error:
> source/database/connection.ts(16,64): error TS2345: Argument of type '{ database: string | undefined; entities: string[]; host: string | undefined; password: string | ...' is not assignable to parameter of type 'ConnectionOptions'.
  Type '{ database: string | undefined; entities: string[]; host: string | undefined; password: string | ...' is not assignable to type 'SqljsConnectionOptions'.
    Types of property 'type' are incompatible.
      Type 'DatabaseType' is not assignable to type '"sqljs"'.
        Type '"mysql"' is not assignable to type '"sqljs"'.

**Comment by pleerock** [comment]
Guys, just use the database you are really using, its pointless to set a type from the configuration because each type has its own specifics, you cannot practically really have it dynamic.

**Comment by billybarnum** [comment]
There are lots of use cases for wanting a variable for the database type ... for tools, or testing, or for that matter apps that need to connect to more than one type of database are pretty common.

I recognize this issue isn't exactly a show-stopper, but it got in my way too, and I had to write some ugly code to work around it. 

And dismissing the request as "pointless" is offensive. :-(

**Comment by emirhg** [comment]
The Issue is marked as Closed but seems to be persistent 

@ typeorm 0.2.15
´´´
const database: ConnectionOptions = {
  type: process.env.TYPEORM_CONNECTION as DatabaseType,
  host: process.env.TYPEORM_HOST || 'localhost',
  port: Number(process.env.TYPEORM_PORT) || 3306,
  name: 'default',
  username: process.env.TYPEORM_USERNAME,
  password: process.env.TYPEORM_PASSWORD, 
  database: process.env.TYPEORM_DATABASE,
  synchronize: Boolean(process.env.TYPEORM_SYNCHRONIZE) || true,
  logging: false,
  entityPrefix: process.env.TYPEORM_ENTITY_PREFIX,
  connectTimeout: 30000,
  entities: [
    OAuth2Token,
    User,
    Role,
    Permission,
    Client,
  ],
};
´´´

Throws error:

´´´
 error TS2322: Type '{ type: DatabaseType; host: string; port: number; name: string; username: string; password: string; database: string; synchronize: true; logging: false; entityPrefix: string; connectTimeout: number; entities: (typeof Permission | ... 3 more ... | typeof OAuth2Token)[]; }' is not assignable to type 'ConnectionOptions'.
  Type '{ type: DatabaseType; host: string; port: number; name: string; username: string; password: string; database: string; synchronize: true; logging: false; entityPrefix: string; connectTimeout: number; entities: (typeof Permission | ... 3 more ... | typeof OAuth2Token)[]; }' is not assignable to type 'MysqlConnectionOptions'.
    Types of property 'type' are incompatible.
      Type 'DatabaseType' is not assignable to type '"mysql" | "mariadb"'.
        Type '"postgres"' is not assignable to type '"mysql" | "mariadb"'.

15 const database: ConnectionOptions = {

´´´

**Comment by proutek** [comment]
This one works for me but it's ugly. You can add more types in switch section.

```
      useFactory: (configService: ConfigService) => {
        let type;
        switch (configService.DB_TYPE) {
          case "mysql": type = "mysql"; break;
          case "postgres": type = "postgres"; break;
          default: type = "postgres";
        }
        return ({
          retryAttempts: 5,
          retryDelay: 1000,
          keepConnectionAlive: true,
          type,
          host: configService.DB_HOST,
          port: configService.DB_PORT,
          username: configService.DB_USER,
          password: configService.DB_PASS,
          database: configService.DB_DATABASE,
          entities: [__dirname + '/**/*.entity{.ts,.js}'],
          synchronize: configService.DB_SYNC,
        })
      },
```

**Comment by thiagoaos** [comment]
@proutek thx. But is this the only "dynamic" solution?

**Comment by dugajean** [comment]
> Guys, just use the database you are really using, its pointless to set a type from the configuration because each type has its own specifics, you cannot practically really have it dynamic.

?? 

Or maybe allow your code to be testable and a little more dynamic?

**Comment by JavierMendozaGomez** [comment]
This is what it worked for me in typescript 
import {ConnectionOptions, DatabaseType} from 'typeorm';
```
import {ConnectionOptions, DatabaseType} from 'typeorm';

const postgresDatabase: DatabaseType = 'postgres';
const baseConfig = {
    host: DB_HOST,
    port: DB_PORT,
    password: DB_PASSWORD,
    database: DB_NAME,
    synchronize: false,
	logging: false,
	type: postgresDatabase,
    entities: [ConcertsEntitySchema]
};
```

**Comment by christhegrand** [comment]
```type: 'postgres' as const``` should also work.

**Comment by im4aLL** [comment]
I had to put ```type: any;```

**Comment by gentunian** [comment]
> `type: 'postgres' as const` should also work.

this is actually how to solved it. Thanks! I did have a more complex scenario:

```typescript
  TypeOrmModule.forRootAsync({
    imports: [ConfigModule.forFeature(postgresConfig)],
    useFactory: (config: ConfigType<typeof postgresConfig>) => ({
      ...config,
      // the following are specific TypeORM settings that's
      // why they are not included in `platformPostgres` config
      database: 'platform',
      synchronize: false,
      autoLoadEntities: true,
    }),
    inject: [postgresConfig.KEY],
  }),
```

I was struggling a lot, tried a workarounds. Setting `as const` worked like a charm:
```typescript
export default registerAs('postgres', () => ({
  host: getEnv<string>('PG_HOST', 'localhost'),
  port: parseInt(getEnv<string>('PG_PORT', '5432')),
  username: getEnv<string>('PG_USERNAME', 'postgres'),
  password: getEnv<string>('PG_PASSWORD'),
  type: 'postgres' as const,
}));
```

Alternatively, you can import the actual options you use for the connection:

```typescript
import type { PostgresConnectionOptions } from 'typeorm/driver/postgres/PostgresConnectionOptions';
import { registerAs } from '@nestjs/config';
import { getEnv } from '@utils/utility-types-and-functions';

export default registerAs(
  'postgres',
  (): PostgresConnectionOptions => ({
    host: getEnv<string>('PG_HOST', 'localhost'),
    port: parseInt(getEnv<string>('PG_PORT', '5432')),
    username: getEnv<string>('PG_USERNAME', 'postgres'),
    password: getEnv<string>('PG_PASSWORD'),
    type: 'postgres',
  }),
);

```

Data source options are one of:

```typescript
export type DataSourceOptions = MysqlConnectionOptions | PostgresConnectionOptions | CockroachConnectionOptions |
SqliteConnectionOptions | SqlServerConnectionOptions | SapConnectionOptions | OracleConnectionOptions |
CordovaConnectionOptions | NativescriptConnectionOptions | ReactNativeConnectionOptions | SqljsConnectionOptions |
MongoConnectionOptions | AuroraMysqlConnectionOptions | AuroraPostgresConnectionOptions | ExpoConnectionOptions |
BetterSqlite3ConnectionOptions | CapacitorConnectionOptions | SpannerConnectionOptions;
```

**Comment by alumni** [comment]
For me, recent versions of TypeScript are already treating string literals as constant types, so I don't need the const assertion at all 🤷‍♂ I'm using `@tsconfig/nodeXX` (just switched from 20 to 22), with minimal changes.

I don't remember when TS started to do this, but it's been a few years I think. TS type inference got a lot better lately, so you shouldn't have to resort to this. Unless you have a compiler option that makes you do it?
