### ISSUE TITLE
Invalid equality check of metadata objects

### ISSUE THREAD

**Issue by Crotalus** [typeorm/typeorm#95]
When searching for metadata for a specific metaobject this comparison is made:
`metadata.target === target`

https://github.com/typeorm/typeorm/blob/master/src/metadata-args/collection/EntityMetadataCollection.ts#L14
https://github.com/typeorm/typeorm/blob/master/src/metadata-args/collection/EntityMetadataCollection.ts#L18

Problem is that it fails to match against the same entity but included later in another file, I guess they aren't equal in the javascript object sense due to being separate objects in memory?

When changing the comparison to `metadata.target.toString() === target.toString()` it works as expected. I don't know if that's the optimal solution though.

**Comment by pleerock** [comment]
no, its source code is correct. Probably you have something wrong setup in your code. It expects class/function type, and each one has its own instance. Provide your minimal code lets see where the issue is

**Comment by mohyt** [comment]
@Crotalus : Do you have working code for this? I am also hitting same issue.
