### ISSUE TITLE
Length for float column type throws error : Column X of Entity Y does not support length property

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#950]
I just updated typeorm from "0.1.0-alpha.34" to "0.1.0-alpha.49"  and this part suddenly isn't working:

````
@Entity()
class Event{
   @Column({type:'float',length:'10,6'})
   latitude:number;
}
````
It throws this error :
````
 Error: Column longitude of Entity Event does not support length property.
````
What should I use for the length of float column type?

**Comment by pleerock** [comment]
adding @iz-iznogood author of this changes

**Comment by iz-iznogood** [comment]
Hi @stonecold123  what db are you using ?

**Comment by iz-iznogood** [comment]
Also this is the correct syntax, 

  @Column({ type: "float", precision: 10, scale: 6 })
  latitude: number;

I checked it on MySQL and works fine. Other DB's dont support arbitrary precision on floats

**Comment by stonecold123** [comment]
@iz-iznogood 
I used mariadb. I'll try your suggestion. Thanks.

**Comment by iz-iznogood** [comment]
Hi @stonecold123  have you tried it ?
Does it work for you ?

Thanks

**Comment by stonecold123** [comment]
Thanks! it works!
