### ISSUE TITLE
Two table, no relations, how to join?

### ISSUE THREAD

**Issue by fanzkday** [typeorm/typeorm#951]
For example:
```
@Entity()
class Address {

  @Column()
  public id: number;

  @Column()
  public address: string;

}
```
```
@Entity()
class User {

  @Column()
  public id: number;

  @Column()
  public addressId: number;

}
```
```
this.rep.createQueryBuilder('user')
      .leftJoinAndSelect('xxx.xxx', 'xxx', 'inner join address on user.addressId = address.id')
      .getOne();
```

Sql result:
```
...
LEFT JOIN `xxx` `xxx` ON ...
AND
INNER JOIN inner join address on user.addressId = address.id
...
```
More than a ` AND`!

**Comment by pleerock** [comment]
```ts
this.rep.createQueryBuilder('user')
      .leftJoinAndSelect(Address, 'address', 'user.addressId = address.id')
      .getOne();
```

**Comment by fanzkday** [comment]
```
this.rep.createQueryBuilder('user')
      .innerJoinAndSelect('user.visits', 'visit')
      .innerJoinAndSelect(PaymentHistory, 'history', 'visit.id = history.instanceId and history.type = 1')
      .where('user.id = :userId', { userId: id })
      .getOne();
```
But, the result,  `user.history` is not exist. In fact, there is data in the database.

**Comment by pleerock** [comment]
If you don't have a relation it wont be there. Try this:

this.rep.createQueryBuilder('user')
      .innerJoinAndSelect('user.visits', 'visit')
      .innerJoinAndMap("user.history", PaymentHistory, 'history', 'visit.id = history.instanceId and history.type = 1')
      .where('user.id = :userId', { userId: id })
      .getOne();

**Comment by fanzkday** [comment]
I am sorry, I forgot to tell you, the `typeorm` version I used was `0.0.11`.
```
Property 'innerJoinAndMap' does not exist on type 'QueryBuilder<User>
```

**Comment by fanzkday** [comment]
Thanks. It worked. I used `innerJoinAndMapOne`.

**Comment by kkoomen** [comment]
>```js
>this.rep.createQueryBuilder('user')
>      .leftJoinAndSelect(Address, 'address', 'user.addressId = address.id')
>      .getOne();
>```

@pleerock How can this be done _inside_ the entity?

**Comment by 5E7EN** [comment]
@kkoomen have you made any success in this issue? I'm having the same problem where it's only returning the actually entity used for `rep`, without any other data included/selected...

The actual SQL it's executing is correct (and works fine when done manually, returning everything I need), but it's just not including data from the other tables in the result.

**Comment by ozknemoy** [comment]
> @kkoomen have you made any success in this issue? I'm having the same problem where it's only returning the actually entity used for `rep`, without any other data included/selected...
> 
> The actual SQL it's executing is correct (and works fine when done manually, returning everything I need), but it's just not including data from the other tables in the result.

leftJoinAndMapOne should help

**Comment by Alonso-Pablo** [comment]
Query Builder:
```js
    const favorites = await this.favoritesRepo.createQueryBuilder('favorite')
      .where('favorite.user_id = :token', { token })
      .leftJoinAndMapOne('favorite.item', 'favorite.item_id', 'items')
      .select(['favorite.id'])
      .addSelect([
        'items.title',
        'items.description',
        'items.price',
        'items.stock',
      ])
      .leftJoinAndMapOne(
        'items.photos',
        PhotosEntity,
        'photos',
        'favorite.item_id = photos.subject_id and photos.subject_type = :item',
        {item: 'item'}
      )


    return paginate<Favorite>(favorites, options)
```
  
Output  (GET):
```json
    //...
    {
      "id": 32,
      "item": {
        "title": "Foo",
        "description": "Buzz",
        "price": 250.99,
        "stock": 10,
        "photos": {
          "id": 2,
          "createdAt": "2021-12-04T04:55:02.408Z",
          "url": "https://images.unsplash.com/photo-1633114128729-0a8dc13406b9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
          "width": 324,
          "height": 281,
          "size": 42,
          "entityId": 18,
          "entityType": "item",
          "redirectUrl": "https://facebook.com/"
        }
      }
    },
    //...
```
    
    Expected Output:
```json
//...
        {
      "id": 32,
      "item": {
        "title": "Foo",
        "description": "Buzz",
        "price": 250.99,
        "stock": 10,
        "photos": {
          "url": "https://images.unsplash.com/photo-1633114128729-0a8dc13406b9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
        }
      }
    },
//...
```
    
Any suggestions or changes that I should make to make the output as expected? 🤔 
```js
      .leftJoinAndMapOne(
        'items.image',
        PhotosEntity,
        'photos',
        'favorite.item_id = photos.subject_id and photos.subject_type = :item',
        {item: 'item'}
      )
      .addSelect('photos.url')
```
I tried with `.select ()` or `.addSelect ()` but it doesn't filter columns from `photos`.

**Comment by amanrawat07** [comment]
> @kkoomen have you made any success in this issue? I'm having the same problem where it's only returning the actually entity used for `rep`, without any other data included/selected...
> 
> The actual SQL it's executing is correct (and works fine when done manually, returning everything I need), but it's just not including data from the other tables in the result.

Hi @kkoomen  have you been able to resolve the issue?

**Comment by Alonso-Pablo** [comment]
> Query Builder:
> 
> ```js
>     const favorites = await this.favoritesRepo.createQueryBuilder('favorite')
>       .where('favorite.user_id = :token', { token })
>       .leftJoinAndMapOne('favorite.item', 'favorite.item_id', 'items')
>       .select(['favorite.id'])
>       .addSelect([
>         'items.title',
>         'items.description',
>         'items.price',
>         'items.stock',
>       ])
>       .leftJoinAndMapOne(
>         'items.photos',
>         PhotosEntity,
>         'photos',
>         'favorite.item_id = photos.subject_id and photos.subject_type = :item',
>         {item: 'item'}
>       )
> 
> 
>     return paginate<Favorite>(favorites, options)
> ```
> 
> Output (GET):
> 
> ```json
>     //...
>     {
>       "id": 32,
>       "item": {
>         "title": "Foo",
>         "description": "Buzz",
>         "price": 250.99,
>         "stock": 10,
>         "photos": {
>           "id": 2,
>           "createdAt": "2021-12-04T04:55:02.408Z",
>           "url": "https://images.unsplash.com/photo-1633114128729-0a8dc13406b9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
>           "width": 324,
>           "height": 281,
>           "size": 42,
>           "entityId": 18,
>           "entityType": "item",
>           "redirectUrl": "https://facebook.com/"
>         }
>       }
>     },
>     //...
> ```
> 
> ```
> Expected Output:
> ```
> 
> ```json
> //...
>         {
>       "id": 32,
>       "item": {
>         "title": "Foo",
>         "description": "Buzz",
>         "price": 250.99,
>         "stock": 10,
>         "photos": {
>           "url": "https://images.unsplash.com/photo-1633114128729-0a8dc13406b9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
>         }
>       }
>     },
> //...
> ```
> 
> Any suggestions or changes that I should make to make the output as expected? thinking
> 
> ```js
>       .leftJoinAndMapOne(
>         'items.image',
>         PhotosEntity,
>         'photos',
>         'favorite.item_id = photos.subject_id and photos.subject_type = :item',
>         {item: 'item'}
>       )
>       .addSelect('photos.url')
> ```
> 
> I tried with `.select ()` or `.addSelect ()` but it doesn't filter columns from `photos`.

I already resolved it:

```js
const favorites = await this.favoritesRepo.createQueryBuilder('favorite')
      .where('favorite.user_id = :token', { token })
      .leftJoinAndMapOne('favorite.item', 'favorite.item_id', 'items')
      .leftJoinAndMapOne(
        'items.photos',
        PhotosEntity,
        'photos',
        'favorite.item_id = photos.subject_id and photos.subject_type = :item',
        {item: 'item'}
      )
      .select(['favorite.id'])
      .addSelect([
        'items.title',
        'items.description',
        'items.price',
        'items.stock',
        'photos.url',
      ])
```

**Comment by raheel-butt** [comment]
> If you don't have a relation it wont be there. Try this:
> 
> ```ts
> this.rep.createQueryBuilder('user')
>       .innerJoinAndSelect('user.visits', 'visit')
>       .innerJoinAndMap("user.history", PaymentHistory, 'history', 'visit.id = history.instanceId and history.type = 1')
>       .where('user.id = :userId', { userId: id })
>       .getOne();
> ```

Works for me Thank you

**Comment by yuvall-cyera** [comment]
But all of the map functions are not really good in some cases that you need to join two tables only for the filters, but you don't need all the mapped data
For example, inner join on TableA.x=TableB.y where TableB.z=1, but get only TableA's columns
If I use map functions, I get also TableB's columns which is inefficient

**Comment by tonganh** [comment]
@schrodingersca8   
I think you can try the code below :
`this.rep.createQueryBuilder('user')
      .leftJoinAndMapOne('user.address',Address, 'address', 'user.addressId = address.id')
      .getOne();`

**Comment by skl-songkiat** [comment]
> > ```js
> > this.rep.createQueryBuilder('user')
> >      .leftJoinAndSelect(Address, 'address', 'user.addressId = address.id')
> >      .getOne();
> > ```
> 
> @pleerock How can this be done _inside_ the entity?

this is work me, for people want to join table without set relation entity

**Comment by MassimilianoOreto** [comment]
> > > ```js
> > > this.rep.createQueryBuilder('user')
> > >      .leftJoinAndSelect(Address, 'address', 'user.addressId = address.id')
> > >      .getOne();
> > > ```
> > 
> > 
> > @pleerock How can this be done _inside_ the entity?
> 
> this is work me, for people want to join table without set relation entity

This solution not working for me. Related entity doesn't appear on result. Only if i do leftjoinandmap works...

**Comment by InsHomePgup** [comment]
> > Query Builder:
> > ```js
> >     const favorites = await this.favoritesRepo.createQueryBuilder('favorite')
> >       .where('favorite.user_id = :token', { token })
> >       .leftJoinAndMapOne('favorite.item', 'favorite.item_id', 'items')
> >       .select(['favorite.id'])
> >       .addSelect([
> >         'items.title',
> >         'items.description',
> >         'items.price',
> >         'items.stock',
> >       ])
> >       .leftJoinAndMapOne(
> >         'items.photos',
> >         PhotosEntity,
> >         'photos',
> >         'favorite.item_id = photos.subject_id and photos.subject_type = :item',
> >         {item: 'item'}
> >       )
> > 
> > 
> >     return paginate<Favorite>(favorites, options)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Output (GET):
> > ```json
> >     //...
> >     {
> >       "id": 32,
> >       "item": {
> >         "title": "Foo",
> >         "description": "Buzz",
> >         "price": 250.99,
> >         "stock": 10,
> >         "photos": {
> >           "id": 2,
> >           "createdAt": "2021-12-04T04:55:02.408Z",
> >           "url": "https://images.unsplash.com/photo-1633114128729-0a8dc13406b9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
> >           "width": 324,
> >           "height": 281,
> >           "size": 42,
> >           "entityId": 18,
> >           "entityType": "item",
> >           "redirectUrl": "https://facebook.com/"
> >         }
> >       }
> >     },
> >     //...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Expected Output:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```json
> > //...
> >         {
> >       "id": 32,
> >       "item": {
> >         "title": "Foo",
> >         "description": "Buzz",
> >         "price": 250.99,
> >         "stock": 10,
> >         "photos": {
> >           "url": "https://images.unsplash.com/photo-1633114128729-0a8dc13406b9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
> >         }
> >       }
> >     },
> > //...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any suggestions or changes that I should make to make the output as expected? thinking
> > ```js
> >       .leftJoinAndMapOne(
> >         'items.image',
> >         PhotosEntity,
> >         'photos',
> >         'favorite.item_id = photos.subject_id and photos.subject_type = :item',
> >         {item: 'item'}
> >       )
> >       .addSelect('photos.url')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried with `.select ()` or `.addSelect ()` but it doesn't filter columns from `photos`.
> 
> I already resolved it:
> 
> ```js
> const favorites = await this.favoritesRepo.createQueryBuilder('favorite')
>       .where('favorite.user_id = :token', { token })
>       .leftJoinAndMapOne('favorite.item', 'favorite.item_id', 'items')
>       .leftJoinAndMapOne(
>         'items.photos',
>         PhotosEntity,
>         'photos',
>         'favorite.item_id = photos.subject_id and photos.subject_type = :item',
>         {item: 'item'}
>       )
>       .select(['favorite.id'])
>       .addSelect([
>         'items.title',
>         'items.description',
>         'items.price',
>         'items.stock',
>         'photos.url',
>       ])
> ```

I'm trying query two tables that A.userId = B.id;
By follow the typeorm.io

<img width="709" alt="image" src="https://github.com/typeorm/typeorm/assets/47906083/d175f4f5-4855-4581-95a7-21a602fbf142">


this.AEntity.createQueryBuilder("A").leftJoinAndSelect(BEntity,"B","B.id = A.userId").getMany()

!!!! It is not working.
leftJoinAndSelect is useless.

I'm get only A table fileds without B table.

Then , i'm use leftJoinAndMapOne

```
.leftJoinAndMapOne("A.userInfo",BEntity,"userInfo","A.userId = B.id")

paramsOne: mapToProperty
paramsTwo: Entity
paramsThree: alias
paramsFour:condition

```

It works ! The query result is right.

Thank you!
