### ISSUE TITLE
Can't pass MongoRepository.find where condition due to typings

### ISSUE THREAD

**Issue by ayuvlasenko** [typeorm/typeorm#9518]
## Issue Description

Hi, everyone! Thank you for your job)

I encoutered an issue. `MongoFindOneOptions` has wrong `where` typings, so I can't pass `ObjectLiteral` to `find` method.
Maybe I'm doing something wrong.

### Expected Behavior

Pass `ObjectLiteral` in `where` condition without errors:
```typescript
return this.repository.find({
    where: { someId: { $in: ["id1", "id2"] } },
});
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/77232221/199498121-4676b7da-545f-4526-ae23-975d40d20c14.png)

```
Type '{ someId: { $in: string[]; }; }' is not assignable to type '((FindOptionsWhere<T> | FindOptionsWhere<T>[]) & (ObjectLiteral | FindOptionsWhere<T> | FindOptionsWhere<...>[])) | undefined'.
  Type '{ someId: { $in: string[]; }; }' is not assignable to type 'undefined'.ts(2322)
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Ubuntu 20     |
| Node.js version     | 16.17.0  | 
| Typescript version  | 4.7.4  | 
| TypeORM version     | 0.3.10  | 

### Additional Context

If I change `MongoFindOneOptions` from this:

```typescript
import { FindOneOptions } from "../FindOneOptions"
import { ObjectLiteral } from "../../common/ObjectLiteral"

/**
 * Defines a special criteria to find specific entity.
 */
export type MongoFindOneOptions<Entity = any> = FindOneOptions<Entity> & {
    /**
     * Simple condition that should be applied to match entities.
     */
    where?: ObjectLiteral
}
```

to this:

```typescript
import { FindOneOptions } from "../FindOneOptions"
import { ObjectLiteral } from "../../common/ObjectLiteral"

/**
 * Defines a special criteria to find specific entity.
 */
export type MongoFindOneOptions<Entity = any> = Omit<FindOneOptions<Entity>, "where"> & {
    /**
     * Simple condition that should be applied to match entities.
     */
    where?: FindOneOptions<Entity>["where"] | ObjectLiteral;
};
```

The problem is gone:

![image](https://user-images.githubusercontent.com/77232221/199502434-8870a003-7850-47ca-8992-9aacfb97bb90.png)

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `mongodb`         | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by thematan** [comment]
It seems to me that your fix is the right way to go.
The intersection types collide.
Because of the stricter type checking for RDBMS update action.

I haven't found a test for simple 'update' for mongo. 
The tests focus around more RDBMS methods like 'save'.
I would suggest to add one [probably here](https://github.com/typeorm/typeorm/blob/master/test/functional/mongodb/basic/repository-actions/mongodb-repository-actions.ts) (Try to find place where they test 'update' using an IDE), and [go for a pull request](https://github.com/typeorm/typeorm/blob/85fa9c6e7df1a0e3ba8c95d64d9b2a6ab464e0e0/CONTRIBUTING.md#submit-pr)

**Comment by svonian** [comment]
same issue, would be great to have a fix

**Comment by GitHubCloud** [comment]
same issue, looking forward to fix
