### ISSUE TITLE
SchemaBuilder: Inconsistency of primary keys

### ISSUE THREAD

**Issue by daniel-lang** [typeorm/typeorm#952]
Follow up to #946 with another problem.

When a primary key is added to a table [`RdbmsSchemaBuilder.updatePrimaryKeys()`](https://github.com/typeorm/typeorm/blob/master/src/schema-builder/RdbmsSchemaBuilder.ts#L362) adds it to the primary key array but leaves out the `isPrimary` flag on the column itself.
This causes the primary key to not be created in Sqlite since [there](https://github.com/typeorm/typeorm/blob/master/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts#L691) the flag is checked instead of the `primaryKeys` array.

@pleerock you mentioned, that you want to refactor the code. What is your idea for this?

**Comment by iz-iznogood** [comment]
Hi, I believe that it is enough to change the Table.addPrimaryKeys method.
This is the place that the schema builder adds the primary key to the table, so if the related column is also updated there it will work for all drivers.

**Comment by daniel-lang** [comment]
Sure, that would be the easiest option

**Comment by daniel-lang** [comment]
I will change the method
