### ISSUE TITLE
Prevent processing of undefined or null in where clause condition

### ISSUE THREAD

**Issue by j1i-ian** [typeorm/typeorm#9527]
### Expected Behavior

Exception Throw when where condition has invalid empty json value.

### Actual Behavior

Randomy first column return.

```typescript
// include the output in code tags like these!
const itShouldBeThrewError = await repository.findOne({ id: null as any });
const althoughItReturnedOnOrFailMethod = await repository.findOneOrFail({ id: null as any });
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v16.14.2  |
| Typescript version  | 4.8.2  |
| TypeORM version     | 0.3.4  |

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | yes            |
| `aurora-postgres` | yes            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
   - we have troubled with this problem. When orFail methods (like findOrFail) are implemented, then expected more secure and faster error-detective actions, but not.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

## Proposals

I think it is so severe issue for stable coding, so we can take ways whatever for solving this problem.

1. If legacy is problem, provide option on datasource for enable/disbale
2. or implement throwing error by OrFail suffix conditionally.

I cannot understand why you don't update for throwing error on `~OrFail` methods.

if you have no time, should I create a PR? I have a time and willing for solving this problem.

## See duplicated issue, but it looks like dead

#2500

**Comment by iJhefe** [comment]
see #9487

**Comment by pleerock** [comment]
Closing as duplicate.
