### ISSUE TITLE
In the old version, Huawei PRAGMA table_xinfo is incompatible 

### ISSUE THREAD

**Issue by hanhui6145** [typeorm/typeorm#9528]
## Issue Description
I'm very sorry, my English is poor, I try to describe it clearly.

Device Information：
Device: Huawei MHA-AL00
Version: 2.0.0.150(C00E150R1P3) GPU Turbo
HarmonyOS Version: 2.0.0

On this device, SQLite PRAGMA table_xinfo can't get any columns correctly, but I can get columns using PRAGMA table_info.

Code Location: typeorm/browser/driver/sqlite-abstract/AbstractSqliteQueryRunner.js:895
```
this.loadPragmaRecords(tablePath, `table_xinfo`)
```
to
```
this.loadPragmaRecords(tablePath, `table_info`)
```
### Actual Behavior

```
// include the output in code tags like these!
```

### Steps to Reproduce

1.
```javascript
this._source = new DataSource({
	type: "react-native",
	location: "default",
	database: "treeroot",
	logging: ['error', 'query'],
	synchronize: true,
	migrations: [],
	entities: [
		FanSchema,
		FailCodeSchema,
		FaultOrderSchema,
		RegularCheckOrderSchema,
		RegularCheckOrderItemSchema,
		FileSchema
	]
});

const source = await this._source.initialize().catch(err => console.log("sqlite init error：", err));
``` 
2. After initialization is started on the device, exit the application and reenter

```typescript
// insert code here
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.17.0  | 
| TypeORM version     | 0.3.10  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | yes            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment]
https://github.com/typeorm/typeorm/pull/9729#issuecomment-1419401577
