### ISSUE TITLE
Common Table Expression / `WITH` Clause

### ISSUE THREAD

**Issue by 67726e** [typeorm/typeorm#9539]
Hello,

This is more a question than an issue, but how can I build a CTE (with) with TypeORM ? Is there a built in feature to do this, or should I use the raw sql query builder ?

Thanks.

See Also: https://github.com/typeorm/typeorm/issues/1116

**Comment by danurwijayanto** [comment]
At type orm documentation have this, but i still failed to implement it. 

https://typeorm.io/select-query-builder#common-table-expressions

Error output is : Property 'addCommonTableExpression' does not exist on type 'SelectQueryBuilder

**Comment by AlexMesser** [comment]
@67726e see the docs - https://typeorm.io/select-query-builder#common-table-expressions

@danurwijayanto CTEs are supported starting from version `3.3.0`.

**Comment by 67726e** [comment]
@AlexMesser - For what it's worth - the "Common table expressions" heading does not exist in the navigation at the start of the documentation page. Looks like it should, as the preceding "Querying Deleted rows" does exist.
![image](https://user-images.githubusercontent.com/543788/207085888-614003be-2cbe-4fed-a124-fd972ae08e49.png)

**Comment by Endunry** [comment]
I want to add to this question by asking if its possible to do recursive CTEs with the query-builder?
