### ISSUE TITLE
Questions about mysql8

### ISSUE THREAD

**Issue by beclass** [typeorm/typeorm#9542]
Please ask if json supports mysql8
 @Column({ comment: 'name' })
  name: json;

**Comment by AlexMesser** [comment]
For questions / general support, please check out our [Slack channel](https://join.slack.com/t/typeorm/shared_invite/zt-uu12ljeb-OH_0086I379fUDApYJHNuw), [StackOverflow](https://stackoverflow.com/questions/tagged/typeorm) or check [TypeORM's documentation](https://typeorm.io).
