### ISSUE TITLE
Ionic prod flag

### ISSUE THREAD

**Issue by bolivir** [typeorm/typeorm#958]
Hi guys, 

i noticed a problem when running typeorm with ionic3.
I saw that the cordova driver is merged, it is working fine.

But if i run the project with the --prod flag command it cannot find the repository's anymore.
This probaly has something to do with the minify it does then.

**Comment by daniel-lang** [comment]
Hey,
thanks for pointing that out. We are still working on the Ionic support.
After playing with the production build for a few hours I'm not sure, that's something that we can fix.
My conclusion is, that webpack together with the minification remove the class decorator `Entity`.
Therefore it's no longer recognised.
So far I haven't found a way to keep it.
It also seems like without the `--prod` flag everything is generated correctly and the entity class get's marked as used.

**Comment by daniel-lang** [comment]
One interesting thing to note: I tested it with a complex set of entities where two tables have a relationship with themselves. For those two classes webpack generates the following line which is missing from the other classes:
```js
s = a = r([Object(i.Entity)("menu_item")], s);
```
which is the translation of the `@Entity("menu_item")` decorator

**Comment by bolivir** [comment]
Hey Daniel, 

Thanks for the response. What i noticed is that everything works fine as long as you dont use the --prod flag.
If i run it with --aot --minifycss, everything works fine. I can even run it with the --minifyjs flag but then i need to name my entity (@Entity("user")) otherwise it will break.

I did some research about the flags, and what i noticed is that if you use the --optimizejs flag it will break. Unfortunately i didnt have the time to fully look into the optimizejs flag and dont know what it does exactly.

For now im just running it with the following flags : --aot --minifycss --minifyjs

**Comment by daniel-lang** [comment]
Interesting, `--optimizejs` uses a special [webpack loader by angular](https://github.com/angular/devkit/tree/master/packages/angular_devkit/build_optimizer). But looking at the README it only says
> Angular decorators, property decorators and constructor parameters are removed, while leaving non-Angular ones intact

But good to know, that `--aot --minifycss --minifyjs` works. The only problem with that is, that is doesn't enable Angular's production mode. So you would have to call `enableProdMode()` yourself.

**Comment by bolivir** [comment]
Just tried it out, if im in browser i need to call `enableProdMode() `. But as soon as i run `ionic cordova run android --aot --minifycss` it looks like it already does the `enableProdMode()` call. Tested it by removing the   line for `enableProdMode()` en it works with and without that line.

**Comment by pleerock** [comment]
I don't use ionic and cant tell anything about it, however this problem tells me something...

I assume in production it minifies javascript, and during minification it changes class names, .e.g. `Post` entity will become `A`. It maybe unacceptable for ORM. First question is, does it do minification in prod mode? If answer is yes, then second question is - does it use [ugiflyjs](http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin)? If yes, then are you able to change a webpack config to add some uglifyjs config? If yes, then can you try to disable `mangle` in config? e.g. set `mangle: false`

**Comment by daniel-lang** [comment]
@pleerock Yes, Ionic does use uglify but the problem isn't the mangle since adding the table name to the decorator like `@Entity('post')` should be enough.

@bolivir can you update your project to `@ionic/app-scripts@3.0.0` ([blog](http://blog.ionic.io/updates-for-all-ionic-angular-3-7-and-more/)) because with that version `ionic cordova run android --prod` and `ionic build --prod` works for me

**Comment by daniel-lang** [comment]
@pleerock can you close this issue?
@bolivir, if it does not work for you, reopen it. But in every example I have it works.

**Comment by pleerock** [comment]
lets wait what author will answer and if everything works no him after ionic version update

**Comment by bolivir** [comment]
Hi,

Sorry for the late reaction but im currently a week on vacation. On monday i will try the solution above to verify if the app script update will work.
Thank you for looking into this issue Daniel.

**Comment by bolivir** [comment]
Hi Daniel,
I just tested it by updating to `@ionic/app-scripts@3.0.0` and it seems to work fine now when running it with the production flag.
Thanks again for looking into this issue.

**Comment by daniel-lang** [comment]
No problem
