### ISSUE TITLE
Questions - about BaseEntity and toJSON

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#959]
I have a few questions.
1. What is BaseEntity for? Should my entities extend from  it?
2. How can I get a pure JSON **without** any inheritance and method, and it can properly deal with other entities? Sometimes need a tree and sometimes needn't.
3. Any other ways to serialize entities?

**Comment by pleerock** [comment]
> What is BaseEntity for? Should my entities extend from it?

only if you don't want to use Repository, EntityManager and want to try alternative, active-record apporach. See [docs here](https://github.com/typeorm/typeorm/blob/master/docs/active-record-data-mapper.md).

Its not clear what do you call "pure json  any inheritance and method" , especially its "inheritance" part. 

Same not clear about serialization. Simply call JSON.stringify(model) if you want to perform serialization

**Comment by Diluka** [comment]
In `TypeORM`, allows  an Entity inherits  another. Like `Student` and `Teacher` both can inherit from `Person`.

e.g.
```ts
export class Person {
    name:string
}

export class Stutent extends Person {
}

export class Teacher extends Person {
}
```

But an instance of `Student` or `Teacher` doesn't have an own property `name`.

Using `JSON.stringify` is the last part of serialization. Before this, sometimes need some pre-procedures, like omit fields, translate codes, etc. And all those don't change the entity itself. At this time, if there has `toJSON` on `BaseEntity` to generate a POJO from entity will be helpful.
BTW, `JSON.stringify` doesn't exclude private fields. 

`TypeORM` already knows which field is column. If I implement the `toJSON` myself, I need get the `columnMetadatas` and traversal all the properties, also need to deal with other entities on relationships. 

Wandering the `toJSON` like this.
```ts
type IncludeExclude = string | { [key: string]: IncludeExclude | IncludeExclude[] };

interface Options {
    include?:IncludeExclude|IncludeExclude[]
    exclude?:IncludeExclude|IncludeExclude[]
}

class BaseEntity {
    toJSON(options?:Options):any
}


book.toJSON({
    include:[
        "category" : "name",
        "author": ["name","gender"]
    ],
    exclude: "id"
})
```

**Comment by pleerock** [comment]
what you are talking about is not responsibility of orm. You need to use [class-transformer](https://github.com/pleerock/class-transformer) library for this purpose.

**Comment by Diluka** [comment]
Acknowledged, I'm trying to use class-transformer.
I come up with 2 questions pleerock/class-transformer#94 and pleerock/class-transformer#95

**Comment by renehauck** [comment]
old, but cloneDeep from lodash works best for me

https://lodash.com/docs/4.17.15#cloneDeep

**Comment by angelxmoreno** [comment]
I have an example base on @pleerock suggestion to use class-transformers.

### Issues
1. `jwt` is a calculated value so when sending a User entity to the front-end, I want that field to show when stringifying. 
2. I do not want the password property to show when stringifying.

### Solution
1. create `AppBaseEntity` with a `toJSON` method that makes use of class-transformer's `classToPlain`
2. decorate my User entity class to expose the getter method
3. decorate my User entity to exclude y password property

code:
```ts
import {BaseEntity} from "typeorm";
import {classToPlain} from "class-transformer";

export default abstract class AppBaseEntity extends BaseEntity {
    toJSON(): {} {
        return classToPlain(this);
    }
}


import {Exclude, Expose} from 'class-transformer';
import AppBaseEntity from "../AppBaseEntity";

type JwtPayload = { userId: number, email: string };

@Entity()
export class User extends AppBaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({nullable: false})
    name: string;

    @Column({nullable: false})
    email: string;

    @Column()
    @Exclude()
    password: string;

    @CreateDateColumn()
    created: Date;

    @UpdateDateColumn()
    modified: Date;

    @DeleteDateColumn()
    deleted: Date;

    @Expose()
    get jwt(): string {
        return jsonwebtoken.sign(
            {userId: this.id, email: this.email},
            process.env.SECURIT_SALT,
            {expiresIn: "1h"}
        );
    }
}

```

Now that I think about it, this implementation makes room for exposing virtual fields in the plain object version of my entities. @pleerock do you foresee issues with the above implementation ?

**Comment by iamsaumya** [comment]
For an use case that wants to exclude the `password` or any such field from select queries. This is an indigenous solution.  

```js
@Entity()
export class User extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({nullable: false})
    name: string;

    @Column({select: false}) // adding this works. 
    password: string;

}
```
