### ISSUE TITLE
[BUG]: Connection refused for localhost

### ISSUE THREAD

**Issue by m-salman-afzal** [typeorm/typeorm#9592]
### Issue description

While making connection to mysql via typeorm, with localhost in host, it does not connect.

### Expected Behavior

`localhost` in the **host** option should be able to connect to mysql database. Currently, only writing `127.0.0.1` makes it connect to mysql.

### Actual Behavior

localhost should be able to connect to 127.0.0.1 but for some reason, it is going to `::1` which is **IPv6** for localhost

### Steps to reproduce

Use `localhost` in **host** options for `DataSourceOptions`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |WSL 2 from MS Store in W11|
| Node.js version     | 18.12.1|
| Typescript version  | 4.9.3|
| TypeORM version     | 0.3.11|

### Additional Context

NA

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment]
It is not a TypeORM issue. Check the `hosts` file on your machine.

**Comment by sscaff1** [comment]
I was having the same issue. For those who happen upon this thread:

`sudo vi /etc/hosts`

And comment out the line that says:

`::1 localhost`

I'm using an M1 Mac.

**Comment by ImAbhishekTomar** [comment]
This is my host file and I have removed::1 but my connection still not working.

**Error**
```
[Nest] 56003  - 01/03/2024, 12:02:37 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: getaddrinfo ENOTFOUND "localhost",
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
```

**Host**
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```
