### ISSUE TITLE
Can persist JSON cannot Parse JSON

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#96]
I have an VO[] that gets persisted to postgres.

```
@Column(ColumnTypes.JSON, {nullable: true})
weights: VO[];
```

The field value in the database is:
`[{"documentId":140,"topicId":24,"weight":0.25},{"documentId":140,"topicId":24,"weight":0.25},{"documentId":140,"topicId":26,"weight":0.25},{"documentId":140,"topicId":27,"weight":0.25}]`

When i try and read that out of the database, it calls:
PostgresDriver.ts => prepareHydratedValue

and calls JSON.parse(value)

This results in:
`Unexpected token o in JSON at position 1
`
Why is the field value in the database not stringified?

**Comment by rightisleft** [comment]
My editor is showing the following when i jump into the node_module

http://imgur.com/U7MVhJG

**Comment by rightisleft** [comment]
The Postgres logs actually look good. The problem is that when it hits the JSON.parse rehydrate method, its already a JS object.

-----
LOG:  statement: START TRANSACTION
LOG:  execute <unnamed>: INSERT INTO "dto_report"("docTopicsDistributions", "burnInRate", "optimization", "numIteration", "isLensed", "numberOfTopics", "lens", "source", "createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)  RETURNING "id"
DETAIL:  parameters: $1 = '[{"documentId":140,"topicId":24,"weight":0.25},{"documentId":140,"topicId":24,"weight":0.25},{"documentId":140,"topicId":26,"weight":0.25},{"documentId":140,"topicId":27,"weight":0.25}]', $2 = '0.74', $3 = 'f', $4 = '1000', $5 = 't', $6 = '30', $7 = NULL, $8 = '1', $9 = '2016-11-20 20:33:49'
LOG:  execute <unnamed>: UPDATE "dto_topic" SET "report"=$1  WHERE "id"=$2
DETAIL:  parameters: $1 = '13', $2 = '24'
LOG:  execute <unnamed>: UPDATE "dto_topic" SET "report"=$1  WHERE "id"=$2
DETAIL:  parameters: $1 = '13', $2 = '25'
LOG:  execute <unnamed>: UPDATE "dto_topic" SET "report"=$1  WHERE "id"=$2
DETAIL:  parameters: $1 = '13', $2 = '27'
LOG:  execute <unnamed>: UPDATE "dto_topic" SET "report"=$1  WHERE "id"=$2
DETAIL:  parameters: $1 = '13', $2 = '26'
LOG:  statement: COMMIT
-----

**Comment by rightisleft** [comment]
This does not root cause the issue, but bypasses the symptom.

In transpiled PostgresDriver.js

```
    prepareHydratedValue(value, columnOrColumnType) {
        const type = columnOrColumnType instanceof ColumnMetadata_1.ColumnMetadata ? columnOrColumnType.type : columnOrColumnType;
        switch (type) {
            case ColumnTypes_1.ColumnTypes.BOOLEAN:
                return value ? true : false;
            case ColumnTypes_1.ColumnTypes.DATE:
                if (value instanceof Date)
                    return value;
                return moment(value, "YYYY-MM-DD").toDate();
            case ColumnTypes_1.ColumnTypes.TIME:
                return moment(value, "HH:mm:ss").toDate();
            case ColumnTypes_1.ColumnTypes.DATETIME:
                if (value instanceof Date)
                    return value;
                return moment(value, "YYYY-MM-DD HH:mm:ss").toDate();
            case ColumnTypes_1.ColumnTypes.JSON:
				if(typeof stringValue == 'string')
				{
					return JSON.parse(value);
				} else {
					return value;
				}
            case ColumnTypes_1.ColumnTypes.SIMPLE_ARRAY:
                return value.split(",");
        }
        return value;
    }
```

**Comment by pleerock** [comment]
create a PR with your changes + add tests and we will merge it

**Comment by rightisleft** [comment]
@pleerock My tests are failing with the change and i cant get mariadb working on my local build

**Comment by pleerock** [comment]
do tests work **without your changes**?

**Comment by rightisleft** [comment]
I think i have some unrelated build issues. MariaSQL and Oracle seem to fail when doing npm install - therefor i wont be able to properly run / test / package the repo

**Comment by rightisleft** [comment]
Definitely unrelated - needed to follow the OracleDB install docs at: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx

**Comment by rightisleft** [comment]
This is the output for `gulp tests`:

➜  typeorm git:(master) ✗ gulp tests
[11:09:14] Requiring external module ts-node/register
[11:09:17] Using gulpfile ~/projects/typeorm/gulpfile.ts
[11:09:17] Starting 'tests'...
[11:09:17] Starting 'tslint'...
[11:09:21] Finished 'tslint' after 4.55 s
[11:09:21] Starting 'coveragePre'...
[11:09:22] Finished 'coveragePre' after 14 ms
[11:09:22] Starting 'coveragePost'...


  0 passing (2ms)

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
[11:09:22] Finished 'coveragePost' after 119 ms
[11:09:22] Starting 'coverageRemap'...
[11:09:22] Finished 'coverageRemap' after 19 ms
[11:09:22] Finished 'tests' after 4.71 s

**Comment by rightisleft** [comment]
It seems your gulp task does not run tsc. By running tsc prior to gulp tests i get tests running correctly.

-- This is from typeorm/typeorm MASTER

```
➜  typeorm git:(master) ✗ tsc

63     sameDay?: CalendarSpecVal;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/moment/moment.d.ts(63,5): error TS2411: Property 'sameDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.


64     nextDay?: CalendarSpecVal;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/moment/moment.d.ts(64,5): error TS2411: Property 'nextDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.


65     lastDay?: CalendarSpecVal;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/moment/moment.d.ts(65,5): error TS2411: Property 'lastDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.


66     nextWeek?: CalendarSpecVal;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/moment/moment.d.ts(66,5): error TS2411: Property 'nextWeek' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.


67     lastWeek?: CalendarSpecVal;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/moment/moment.d.ts(67,5): error TS2411: Property 'lastWeek' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.


68     sameElse?: CalendarSpecVal;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/moment/moment.d.ts(68,5): error TS2411: Property 'sameElse' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

➜  typeorm git:(a35bbac) ✗ gulp tests
[11:19:08] Requiring external module ts-node/register
[11:19:12] Using gulpfile ~/projects/typeorm/gulpfile.ts
[11:19:12] Starting 'tests'...
[11:19:12] Starting 'tslint'...
[11:19:16] Finished 'tslint' after 4.31 s
[11:19:16] Starting 'coveragePre'...
[11:19:17] Finished 'coveragePre' after 899 ms
[11:19:17] Starting 'coveragePost'...


  indices > basic unique index test
    1) "before all" hook
    2) "after all" hook


  0 passing (319ms)
  2 failing

  1) indices > basic unique index test "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:3307
      at Object.exports._errnoException (util.js:1036:11)
      at exports._exceptionWithHostPort (util.js:1059:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
      --------------------
      at Protocol._enqueue (node_modules/mysql/lib/protocol/Protocol.js:141:48)
      at Protocol.handshake (node_modules/mysql/lib/protocol/Protocol.js:52:41)
      at PoolConnection.connect (node_modules/mysql/lib/Connection.js:136:18)
      at Pool.getConnection (node_modules/mysql/lib/Pool.js:48:16)
      at Promise (build/compiled/src/driver/mysql/MysqlDriver.js:9:13060)
      at MysqlDriver.retrieveDatabaseConnection (build/compiled/src/driver/mysql/MysqlDriver.js:9:12986)
      at MysqlDriver.<anonymous> (build/compiled/src/driver/mysql/MysqlDriver.js:9:7215)
      at next (native)
      at build/compiled/src/driver/mysql/MysqlDriver.js:9:1422
      at __awaiter (build/compiled/src/driver/mysql/MysqlDriver.js:9:327)

  2) indices > basic unique index test "after all" hook:
     TypeError: Cannot read property 'map' of undefined
      at Object.closeConnections (test/utils/test-utils.ts:24:35)
      at Context.after (test/functional/indices/basic-unique-index-test/basic-unique-index-test.ts:15:17)




stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: 2 tests failed.
```

**Comment by pleerock** [comment]
you can run tests without oracle and maria (I think you can do it in test-utils.ts).
The most important is to run tests under mysql, postgres and sqlite. Mariadb is same as mysql so tests for it should always pass if they are passing for mysql. Oracle is a pain. You can skip it. Also you can skip mssql if you have a mac like me.

**Comment by rightisleft** [comment]
When running test locally - limited to Postgres only - both Master && my branch pass.

I get silent runtime bugs when importing the modified code into my branch.

**Comment by pleerock** [comment]
and why do you have them?

**Comment by rightisleft** [comment]
Prior to modifications,

I have an VO[] that gets persisted to postgres.

```
@Column(ColumnTypes.JSON, {nullable: true})
weights: VO[];
```

The field value in the database is:
`[{"documentId":140,"topicId":24,"weight":0.25},{"documentId":140,"topicId":24,"weight":0.25},{"documentId":140,"topicId":26,"weight":0.25},{"documentId":140,"topicId":27,"weight":0.25}]`

After modifications all entries are NULL

**Comment by rightisleft** [comment]
i would limit the issue to the reproducible steps at the top of the thread

**Comment by pleerock** [comment]
fixed, will be available in next typeorm released
