### ISSUE TITLE
Greater/less conditions in "where" clausule of Entity Manager

### ISSUE THREAD

**Issue by mzygmunt** [typeorm/typeorm#960]
Is there a way to add greater/less conditions in "where" clausule of find/findOne of Entity Manager? Eg. check if "initAt < createdAt" or "DATE_SUB(NOW(), INTERVAL 1 DAY ) < createdAt"? I know that's possible in QueryBuildrer but in find/FindOne?

**Comment by pleerock** [comment]
No, its not possible via find/findOne. find* methods are only for trivial queries, if you need something complex use QueryBuilder. QueryBuilder allows to do flexible queries in a readable way (unlike find method if it had all kindof ">" statements)

**Comment by Dharita** [comment]
// get a list of Orders having delivery date greater than the current timestamp.

```
await queryRunner.manager.find(Orders, {
                where: { delivery_date: MoreThan(new Date().getTime()) }
});
```
or more examples refer: [https://github.com/typeorm/typeorm/blob/master/docs/find-options.md#advanced-options]

**Comment by moshenskyDV** [comment]
@chokshidharita small correction to your answer (`new Date` should be in brackets), please update the answer:

```MoreThan((new Date()).getTime())```
