### ISSUE TITLE
[DOCS]: Unable to see documentation on website

### ISSUE THREAD

**Issue by noobd3v** [typeorm/typeorm#9608]
### What was unclear or otherwise insufficient?

<img width="883" alt="image" src="https://user-images.githubusercontent.com/13329441/206473502-57e3862b-307f-43c5-a195-c8d09be90559.png">

### Recommended Fix

<img width="883" alt="image" src="https://user-images.githubusercontent.com/13329441/206473549-09f019fa-6393-464b-b55a-a0ba163ca22d.png">

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by noobd3v** [comment]
incase need console errors. 
<img width="921" alt="image" src="https://user-images.githubusercontent.com/13329441/206677749-ed87ecc7-fbad-472b-9240-49dcbbf00cd9.png">

**Comment by pleerock** [comment]
try to open the github link in the error. Does it work for you? Because it seems the data from the github isn't loaded for you.

**Comment by anandsharma-i** [comment]
hi,
facing same issue. not able to see the docs, but on github everything is accessible. please fix.

**Comment by noobd3v** [comment]
> try to open the github link in the error. Does it work for you? Because it seems the data from the github isn't loaded for you.

Git hub link in the error was working.

typeorm.io seems to working right now. @anandsharma-i  Is it working for you also now?

**Comment by anandsharma-i** [comment]
Yes working for me. 

> > try to open the github link in the error. Does it work for you? Because it seems the data from the github isn't loaded for you.
> 
> Git hub link in the error was working.
> 
> typeorm.io seems to be working now. @anandsharma-i Is it working for you also?

Yes working for me @noobd3v
