### ISSUE TITLE
Load configs from a default .env file.

### ISSUE THREAD

**Issue by erickponce** [typeorm/typeorm#961]
Config loader could try do load a .env file if a ormconfig.env file is not present.

**Comment by mzygmunt** [comment]
I think reading env variables by TypeORM directly from specified ormconfig.env is unnecesary. In addition current solution forces the use of 2 separate files: ormconfig.env and .env, while we using dotenv in main project. If someone wants to define environment variables likes TypeORM connection's settings, it will add dotenv to the main project and define it in "global" .env.

**Comment by erickponce** [comment]
mzygmunt, I completely agree, main dotenv approach is sufficient.

**Comment by pleerock** [comment]
Okay, I think this can be implemented. Its pretty easy feature to implement

**Comment by erickponce** [comment]
https://github.com/typeorm/typeorm/pull/981
