### ISSUE TITLE
Foreign key is undefined when loading using find or querybuilder.

### ISSUE THREAD

**Issue by alessandrojcm** [typeorm/typeorm#964]
Hello, I have the following entities defined:

```typescript
@Entity('pieces')
export class PieceEntity {

  @PrimaryColumn('nvarchar')
  id: string

  @Column('nvarchar', {nullable: false})  
  description: string

  @Column('date', {nullable: false})
  lastMaintenance: Date

  @Column('date', {nullable: false})
  nextMaintenance: Date

  @Column('bit', {nullable: false})
  damaged: boolean

  @CreateDateColumn()
  created: Date

  @UpdateDateColumn()
  updated: Date
  
  @ManyToOne(type => EquipmentEntity, equipment => equipment.pieces)
  @JoinColumn({name: 'equipmentId'})
  equipmentId: EquipmentEntity
}

@Entity('equipment')
export class EquipmentEntity {

  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column('nvarchar', {nullable: false})
  description: string

  @CreateDateColumn()
  created: Date

  @UpdateDateColumn()
  updated: Date

  @OneToMany(type => PieceEntity, piece => piece.equipmentId, {
    eager: true
  })
  pieces: PieceEntity[]
}

```

I checked the database and the rows are inserted correctly, though I'm having problems loading them.
I tried this, as suggested in the docs:
``` typescript
connection.getRepository(EquipmentEntity).createQueryBuilder('equipment');
    .leftJoinAndSelect('equipment.pieces', 'pieces')         
    .getManyAndCount()
```
Equipment loads fine, with its array of pieces. But the `equipmentId` (foreign key) in each `PieceEntity` instance is undefined.

Since I'm using eager loading I tried using find like this:
```typescript
connection.getRepository(EquipmentEntity)
    .findAndCount({skip: from, take: quantity})
```

But the result is the same: `equipmentId` is undefined. What I'm I doing wrong?

PD: In the my application code, each attribute in the entity classes is initialized as `undefined`, that because of [json2typescript](https://www.npmjs.com/package/json2typescript). Don't know if it has anything to do with it.

**Comment by luchillo17** [comment]
I think eager loading is a new feature still in WIP, i don't have a project in which to test, why not try to create a test for it?

**Comment by luchillo17** [comment]
After tracking where it breaks, seems this lines are the start, i'm trying to narrow where it breaks (very likely the lazy-wrapper?): [src/persistence/SubjectBuilder.ts#L272-L277](https://github.com/typeorm/typeorm/blob/master/src/persistence/SubjectBuilder.ts#L272-L277)

**Comment by alessandrojcm** [comment]
The thing is the problem persists even with eager loading disabled. So either I'm doing something wrong or it is a bug, I think is the former.

**Comment by alessandrojcm** [comment]
Solved by making the following modification to `PieceEntity`:

```typescript
  @ManyToOne(type => EquipmentEntity)
  equipment: EquipmentEntity

  @RelationId((piece: PieceEntity) => piece.equipment)
  equipmentId: string
```

Eager loading is disabled, entities are loaded using QueryBuilder.

**Comment by luchillo17** [comment]
Wait you wanted the entity itself or just the Id? the initial issue was you were using the property for the entity with the same name as the join column name.

**Comment by alessandrojcm** [comment]
> Wait you wanted the entity itself or just the Id?
Just the id.
>the initial issue was you were using the property for the entity with the same name as the join column >name.
Yeah? I thought it had to do with the properties initialized with `undefined`, as required by (json2typescript)[https://www.npmjs.com/package/json2typescript].

**Comment by luchillo17** [comment]
At which part of your api are you using `json2typescript`? for me it makes sense if you use it in the consuming side, but in the api?

**Comment by alessandrojcm** [comment]
It's because I'm working with a GraphQL API, and I need to convert from the plain objects sent from the client. At least that's the solution I came up with.

**Comment by luchillo17** [comment]
I'm also using a GraphQL api with Apollo, and i haven't yet the need to convert, maybe my use case is too simple?

**Comment by alessandrojcm** [comment]
Well, my use case isn't that complex (your usual add/modify/delete/get one/get many). How are you storing the objects received in the mutation resolver with TypeORM? Don't they have to be an instance of the class decorated with `@Entity`?

**Comment by luchillo17** [comment]
For create maybe:
```ts
 const controlPlace = new ControlPlace()
    Object.assign(controlPlace, data)
    return connection
      .manager
      .save(controlPlace)
```
However if you want to update or delete:
```ts
const { id, ...control } = data
    return connection
      .manager
      .updateById(ControlPlace, id, control)
      .then(() => true)

// Delete
return connection
      .manager
      .removeById(ControlPlace, data.id)
      .then(() => true)
```
I guess you can imagine data coming from the resolver params.

**Comment by alessandrojcm** [comment]
Oh, I see. I guess I have some refactoring to do. Thanks!

**Comment by luchillo17** [comment]
So in create you saving one line with that `json2typescript`, but that line goes into an import, so in my eyes that's unnecessary.

**Comment by alessandrojcm** [comment]
Yeah, you're right. And also you have to add a bunch of decorators to the class's properties. Well, this happens when you don't read the JavaScript Standard Library.

**Comment by luchillo17** [comment]
What do you mean with the "JavaScript Standard Library"?

**Comment by alessandrojcm** [comment]
You know, the bunch of built in functions and methods JavaScript comes with (like `Object.assign()`, `Array.filter()` and so on).

**Comment by luchillo17** [comment]
What about the relations? i'm using `lazy-relations` which means i have to assign them like this:
```ts
const control = new Control()
control.createdBy = Promise.resolve(user);
```
Which totally breaks my use of `Object.assign()` and forces me to make bunch of `if`'s and assign with `Promise.resolve()`, maybe using an array and a `forEach` with property names.

Is `json2typescript` able to deal with such cases?

**Comment by alessandrojcm** [comment]
Mmmm... Maybe, `json2typescript` allows you to define custom converters (custom ways to handle the serialization/deserialization of your data). So maybe you can define a converter that takes an argument (say a `string`), and returns a `Promise<string>

**Comment by luchillo17** [comment]
Ugh look what i had to do to allow mutations:
```ts
  createRoute(
    root: any,
    { relations, ...data }: Route & RelationArgs,
    { connection, user }: TypeORMContext,
  ) {

    const route = new Route();
    Object.assign(route, data)
    route.createdBy = route.updatedBy = Promise.resolve(user);
    Object.entries(relations)
      .forEach(([key, id]) => {
        const property = key.replace('Id', '')
        route[property] = Promise.resolve({ id })
      })
    return connection
      .manager
      .save(route)
```
Had to pass each id through a forEach to map it to a promise, using an string replace to remove the id field, ugly.

**Comment by alessandrojcm** [comment]
Yeah, that's pretty ugly. What's the `Route` class definition? Maybe `json2typescript` can help you.

**Comment by luchillo17** [comment]
Check my GraphQL one, idk if i should expect the objects or just the ids, since i don't have the `@RelationId` thing on, i need to make those ID's into objects before passing them to the `save` function:
```graphql
type Route {
  id: ID!
  name: String!
  value: String!
  isActive: Boolean!

  shippings: [Shipping!]
  trackings: [Tracking!]
  routeLines: [RouteLine!]
  from: City!
  to: City!
  client: Client!
  organization: Organization!
  createdBy: User!
  updatedBy: User!
  # Version of entity item, updated on update
  version: Int

  # Auto-generated at insert
  createdAt: String!

  # Auto-updated at insert & update
  updatedAt: String!
```
So here's the GraphQL mutation definition:
```graphql
input RouteRelationIds {
  fromId: ID!
  toId: ID!
  clientId: ID!
  organizationId: ID!
}

extend type Mutation {
  createRoute(
    name: String!
    value: String!
    relations: RouteRelationIds!
  ): Route
  updateRoute(
    id: ID!
    name: String
    value: String
    isActive: Boolean
  ): Boolean
  deleteRoute(
    id: ID!
  ): Boolean
}
```

How do you allow mutations with relations in your case?

**Comment by luchillo17** [comment]
I tried by using the `@RelationId` thing to try and allow to create a new entity with its ids, but seems it only works for querying the ids, made an issue for it: https://github.com/typeorm/typeorm/issues/997

**Comment by alessandrojcm** [comment]
It has nothing to do with the GraphQL schema (or the `RelationId` decorator). Let me show you an excerpt from my app of how I deal with relations:

Take these entities:

```typescript
@JsonObject // This is from json2typescript, refer to its docs for more info.
@Entity('equipment')
export class EquipmentEntity {

  @PrimaryGeneratedColumn('uuid')
  @JsonProperty('id', String, true) // Same with this.
  id: string = undefined // It's undefined, because json2typescript does not work otherwise.

  @Column('nvarchar', {nullable: false})
  @JsonProperty('description', String, true)
  description: string = undefined

  @JsonProperty('pieces', [PieceEntity], true)
  @OneToMany(type => PieceEntity, piece => piece.equipment)
  @ValidateNested()
  pieces: PieceEntity[] = undefined
}

@JsonObject
@Entity('pieces')
export class PieceEntity {

  @PrimaryColumn('nvarchar')
  @JsonProperty('id', String, true)
  id: string = undefined

  @Column('nvarchar', {nullable: false})
  @IsNotEmpty()
  @JsonProperty('description', String, true)
  description: string = undefined

  @ManyToOne(type => EquipmentEntity)
  equipment: EquipmentEntity

  @JsonProperty('equipment', EquipmentEntity, true)
  @RelationId((piece: PieceEntity) => piece.equipment) // This is just for loading the foreign key to this 
                                                                                        // attribute.
  equipmentId: string = undefined
}
```

Just a simple one to many/many to one relation, nothing new here.

The GraphQL schema is as follows:

```
type Piece {
    id: String!
    description: String!
    # Attribute for the foreign key.
    equipmentId: String!   
}

type Equipment {
    id: String
    description: String
    # Entities from the relation.
    pieces: [Piece]
}
```

So, when your client sends a mutation, you receive a plain `JSON` like object like this:
```javascript
{
    id: undefined, // because it's auto generated
    description: 'I am an equipment',
   pieces: [{
    id: '1234',
   description: 'I am a piece',
   equipmentId: undefined // because it gets assigned by the ORM.
   }]
}
```

So, in the resolver, I use `json2typescript` to transform that plain object into a `EquipmentEntity` instance. The `pieces` array of the plain object also gets transformed into an array with instances of `PieceEntity`. Now I can just save those entities in the database normally, no need of `Object.assign()` or other tricks.

**Comment by luchillo17** [comment]
Yep, except one thing, i'm using `LazyRelations`, which forces me to wrap every relation object with a `Promise.resolve(...)`.

You trying to eager load everything while i'm still trying to keep it modular, that difference is why i need to map all relation ids to wrap it in both object and promise, i want to only pass the ids, not the full object of the relation.

**Comment by alessandrojcm** [comment]
I see. Well, I haven't use lazy loading, so I don't really know what to do in that case. Maybe you could define a `json2typescript` custom converter. Which takes and `id` from the plain object and returns a `Promise.resolve(id)`. But, like I said, I really don't know.

**Comment by luchillo17** [comment]
Nah, i think it would be actually more hassle with all the extra decorators.

**Comment by alessandrojcm** [comment]
Yeah, I get you. If your project is somewhat advanced it would be a hassle to add the decorators to all the existing classes.

**Comment by luchillo17** [comment]
Even if it's not, my code is like extra 6 lines of code per resolver (most of the time are 3 resolvers), while `json2typescript` would be like 1 extra line per decorator (at best) * 1 decorator per Entity column * each Entity in project + 1 entity per resolver + 1 line per Entity, so making the math:

3 Entities with 10 columns each:
JS: 3 (entities) * 3 (resolvers/entity) * 6 (lines/resolver) = 54 lines.
json2typescript: 1 (line at best) * 10 (cols/entity) * 3 (entities) + 1 (line/resolver) * 3 (resolver/entity) * 3 (entitiy) + 1 (line/entity) * 3 (entity) = 42

With only 3 entities it seems better, but we took the ideals, 1 line per column for `json2typescript`, with this formula you can see the more entities & columns per entity you have, the better my solution looks from line numbers.

Also mine is just a simple general solution, while `json2typescript` is more complex because it depends on the column type and function.

**Comment by alessandrojcm** [comment]
In terms of line numbers, sure. But that's not the only way to measure code quality. Anyway, my project it's to advanced to switch now; next time I'll take a look to your approach.

**Comment by luchillo17** [comment]
Indeed, i actually think the api shouldn't need to pass the values to TypeORM wrapped in `Promise`'s even if it's a `Lazy-Relation`, in theory they could check if the value passed to the `save` or `persist` function is a promise or an object and then deal with each case as necessary.

**Comment by alessandrojcm** [comment]
Well, that's uncharted territory for me. But it makes sense. We'd have to know why it is designed that way, tho.

**Comment by brunolmalafaia** [comment]
Ok but @luchillo17 what about just return the id of foreign key when using "find"? It is not clear for me if it is possible or not.

**Comment by luchillo17** [comment]
@alessandrojcm Checking if Promise is as simple as
`if (variable instanceof Promise) {}`

@brunolmalafaia Sorry my dude, been away from this project for way too much to answer with confidence.
