### ISSUE TITLE
Question - Why order option is object not array?

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#965]
definition is [here](https://github.com/typeorm/typeorm/blob/master/src/find-options/FindOneOptions.ts#L31)

```ts
    /**
     * Order, in which entities should be ordered.
     */
    order?: { [P in keyof Entity]?: "ASC"|"DESC" };
```

As we know, in sql, `ORDER BY a,b` is not equal to `ORDER BY b,a`. The `option.order` is an `object`. How can it guarantee order?

**Comment by pleerock** [comment]
Yes, order will be guarantee depend on order of property in the object

**Comment by Diluka** [comment]
I made a litter test. The order in JavaScript will not change. But if I save it to database as `JSON` in MySQL, it changes into alphabet order. 

May we could have it in two forms `object` like now or `array`

**Comment by pleerock** [comment]
Can I have some examples? What do you mean by "But if I save it to database as JSON" ?

**Comment by Diluka** [comment]
```sql
create table json_test
(
	id int auto_increment
		primary key,
	json json null
)
;

INSERT INTO test.json_test (json) VALUES ('{"b": 2, "a": 1}');

SELECT * FROM json_test;

# {"a": 1, "b": 2}
```

**Comment by pleerock** [comment]
But how is it related to ORDER?!

**Comment by Diluka** [comment]
`JSON` outside of `javascript` may be reordered, I just worried about if I save the `order option` into database or somewhere, where I load it again, will it be the same?

If `TypeORM` not going to implement an array like order option for alternative, I will handle it myself.

BTW, if I want to `ORDER BY RAND()`, I can't use this option. I read the implementation, it takes keys as only alias, doesn't analyze if is a `sql function`. Will it be enhanced someday?

**Comment by pleerock** [comment]
> JSON outside of javascript may be reordered, I just worried about if I save the order option into database or somewhere, where I load it again, will it be the same?

please don't confuse things. You was talking about ORDER BY IN SELECT QUERIES, now you switched talk to some order of inserted values in a json. I think its something database-related, not something typeorm handles.

> If TypeORM not going to implement an array like order option for alternative, I will handle it myself.

what are you suggestions? I still don't understand your issue and requirement because you confused me

> BTW, if I want to ORDER BY RAND(), I can't use this option.

You can, there is even a test for this use case:

```ts
        const posts = await connection.createQueryBuilder(Post, "post")
            .orderBy("RAND()")
            .getMany();
```

**Comment by Diluka** [comment]
My point is the order of properties of an object will change, if the object come from outside of `nodejs`.

Like I mentioned before, the property order of object load from database changed. So I can't use it to do `order by`.

I tried on the latest `nodejs`, the property order is the order I created it, but some says it **can't** be guaranteed.

> 4.3.3 Object
> 
> An object is a member of the type Object. **It is an unordered collection of properties** each of which contains a primitive value, object, or function. A function stored in a property of an object is called a method.

https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

### conclusion
1. outside of `nodejs` depends on where and how, the order can't be guaranteed.
2. inside of `nodejs`, despite we both found the order is guaranteed, but it still risky.

**Comment by pleerock** [comment]
I still do not understand your point. `order by` is used to order selected values, not column value of the selected values, e.g. json in your case. If you have json inserted and its order is different then what you have in the database when you select it - it how underlying driver / database / maybe even node itself work. Why are you talking about `order by` in selection expression then?

**Comment by Diluka** [comment]
2 parts
1. `TypeORM` use `object` to generate `order by` clause
2.  the order of `keys` of `object` in `javascript` is not  guaranteed by ECMAScript Specification

I want to `{"b":"ASC","a":"ASC"}` to generate `ORDER BY b,a`, but no one can promise it will not be `ORDER BY a,b`.

I pass this `object` directly to `TypeORM` is OK for now. But what about the future changes in `JavaScript`? Or load this `object` from database. 

If the order of this `object` changes, the `order by` clause changes and the result changes.

If we use `array`, the order is guaranteed.

**Comment by pleerock** [comment]
> the order of keys of object in javascript is not guaranteed by ECMAScript Specification

right the order is not guaranteed by ECMAScript Specification, however all implementations make this in order of insertion of the properties in the object.

> But what about the future changes in JavaScript? 

something that is hardly to be in the near future. There are methods like Object.keys which give you keys in a specific order. And order right now is order of inserted properties, so I don't really think it will be changed.

So we are talking about non-exist problem.

**Comment by Diluka** [comment]
I understand you. 

I did not express my question clearly. In my program, the order of object properties sometimes can not be guaranteed. So I want to it can accept array.

Like this #1021
The option can still have object but also array. 
If you don't like it. Just close it.

**Comment by pleerock** [comment]
Sorry but I don't want to complicate things with another approach of the same solution. Plus this approach isn't really clean and obvious. Instead, if objects does not work for, I suggest you to simply call `addOrderBy` manually. 

> In my program, the order of object properties sometimes can not be guaranteed. 

can you show me a real case how it cannot be guaranteed for you?

**Comment by Diluka** [comment]
save option to database, keys order will change, used for to remember user settings

**Comment by Diluka** [comment]
I thought about it. There always has another way to solve problems. I can save as `array` and transform into `object` to pass to `TypeORM`. In my program, I can always use array until pass to `TypeORM`.

OK, you can close both.

**Comment by pleerock** [comment]
> I thought about it. There always has another way to solve problems.

yes but this one isn't really clear, its just a mess that may be useful only for few people with such specific use cases. I don't think its worth adding functionality to ORM

> save option to database, keys order will change, used for to remember user settings

then solution may be for not to store it in json format, but just like a string.

**Comment by kenberkeley** [comment]
Prefer

```js
// Babelrc style:
[
  ['b', 'ASC'],
  ['a', 'ASC']
]

// or lodash/orderBy style:
[
  ['b', 'a'],
  ['ASC', 'ASC']
]
```
