### ISSUE TITLE
[BUG]: Multiple 'where' conditions with overlapping var names leads to unexpected issues

### ISSUE THREAD

**Issue by joescherping** [typeorm/typeorm#9650]
### Issue description

If you have multiple 'where' conditions and they use the same var name, unexpected behavior

### Expected Behavior

I tried
```
let query = this.appRepository.createQueryBuilder('app')
  .select(fieldIds)
  .where(`"LoanAmount" >= :value`, { value: 700000 })
  .andWhere(`"LoanAmount" <= :value`, { value: 1000000 });
```
And I expected it to generate a Postgres query that treated those as two different values (even though I put in the same var name)

### Actual Behavior

Instead, it produced this postgres query
```
SELECT "LoanAmount" FROM "application_warehouse" "app" WHERE "LoanAmount" >= :value AND "LoanAmount" <= :value
```
So it was using the same value for both `:value`

### Steps to reproduce

Use multiple 'where' clauses which refer to a value of the same name, like this one:
```
let query = this.appRepository.createQueryBuilder('app')
  .select(fieldIds)
  .where(`"LoanAmount" >= :value`, { value: 700000 })
  .andWhere(`"LoanAmount" <= :value`, { value: 1000000 });
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 8.x  |
| Typescript version  | 4.1.5  |
| TypeORM version     | 0.2.34  |

### Additional Context

Maybe it should check the names of variable used in the query, and then if there are naming conflicts, generate different names for them. I don't know if that is the best solution but that's what comes to mind.

Let me know if you are aligned on that and I could potentially implement it and do a pull request.

Thanks

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by AlexMesser** [comment]
This is expected behavior. There is no need to complicate the functionality if we can just use different parameter names.
