### ISSUE TITLE
[FEATURE]: add official options to create or update slug by title!

### ISSUE THREAD

**Issue by siamahnaf198** [typeorm/typeorm#9654]
### Feature Description

Slug is needed to beatify frontend `URL`. So that frontend developer wants to get a slug field from backend on almost every entity. If the project is blog project, then slug must be important field for designing database. For creating slug, we have to check if already exist then append something else bla bla. I actually want to tell that, as `id` is an identity of a database document, like this slug also is a big identity of a database document. If we get a built-in solution for creating, updating slug with unique options, we will be glad to use typeorom.

Now we faced very difficulties to create a subscriber to check slug already exist and then have to create or update bla bla. So, we are requesting to typeorm to add official support to create, update a unique slug. Here we are getting many built-in decorator like - `PrimaryGeneratedColumn`,  `Generated`, `CreateDateColumn`, `UpdateDateColumn` etc. Just we want one more that is `Slug`

### The Solution

We can get a slug decorator for creating slug, like something-

```
@Slug("title")
slug: string;
 @Column({ type: "text", nullable: false })
title: string;
```

### Considered Alternatives

No alternatives

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment]
We are not planning to introduce a new decorators for application-specific use cases.
