### ISSUE TITLE
[FEATURE]: Add "JsonContains" operator

### ISSUE THREAD

**Issue by dzvyagin** [typeorm/typeorm#9664]
### Feature Description

The PostgreSQL database was found to be searching in a column with the type "Json" or "Jsonb". Now, in order to search with typeorm, you need to create a queryBuilder and describe the query with the passed parameters.

### The Solution

The postgreSQL operator "@>" can be used to solve the json column search problem. To conveniently abstract from the use of the postgreSQL statement, the plan is to create a findOperator "JsonContains" to help solve the json search problem.

```TypeScript
this.repo.find({
    where: { id: In(ids), address: JsonContains({ city: { id: 12 } }) },
});
```

### Considered Alternatives

One alternative is to create a query builder and describe the sql query in it.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by AlexMesser** [comment]
implemented in #9665

**Comment by gabbrieu** [comment]
Any news to implementation for mysql too?

**Comment by sahilkul95** [comment]
Any news here?

**Comment by GaussianWonder** [comment]
You can also do this instead with a query builder:

```ts
type JsonExtract<
  Column extends string,
  Path extends string,
> = `JSON_EXTRACT(${Column}, "$.${Path}")`;

export function jsonExtract<Column extends string, Path extends string>(
  column: Column,
  path: Path,
): JsonExtract<Column, Path> {
  return `JSON_EXTRACT(${column}, "$.${path}")`;
}
```

```ts
const example = await this.dataSource
    .createQueryBuilder('a')
    .where(`${jsonExtract('a.column', 'key')} = :value`, { value: 'value' })
```

**Comment by myvzar** [comment]
For MySQL I use: 

```ts
import { Raw } from 'typeorm';

export function JsonArrayContains(value: string | string[]) {
  return Raw((alias) => `JSON_CONTAINS(${alias}, :value)`, {
    value: JSON.stringify(value),
  });
}
```

usage:

```ts

this.repository.find({
  where: {
    offices: JsonArrayContains('some')
  }
});

```
