### ISSUE TITLE
Closing a NestJS app with multiple datasources

### ISSUE THREAD

**Issue by DenisaHalmaghi** [typeorm/typeorm#9672]
### Issue description

Closing a NestJS app with multiple datasources throws an error when trying to destroy other datasources than the first one

### Expected Behavior

The app to be closed successfully

### Actual Behavior

An error si thrown:

```ts
UnknownElementException [Error]: Nest could not find DataSource element (this provider does not exist in the current context)
    at InstanceLinksHost.get ([path]/node_modules/@nestjs/core/injector/instance-links-host.js:24:19)
    at ModuleRef.find ([path]/node_modules/@nestjs/core/injector/abstract-instance-resolver.js:8:60)
    at ModuleRef.get ([path]/node_modules/@nestjs/core/injector/module.js:349:28)
    at TypeOrmCoreModule.<anonymous> ([path]/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:117:47)
    at Generator.next (<anonymous>)
    at [path]/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:20:71
    at new Promise (<anonymous>)
    at __awaiter ([path]/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:16:12)
    at TypeOrmCoreModule.onApplicationShutdown ([path]/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:116:16)
    at callAppShutdownHook ([path]/node_modules/@nestjs/core/hooks/on-app-shutdown.hook.js:51:35)
```

### Steps to reproduce

Very minimal steps to reproduce. 
Note: `useFactory` is necessary because the app has a config module that's being used, but I removed it for the purposes of showcasing the real issue.

1. Install NestJs and TypeOrm

2. Database Module
```ts
@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      imports: [],
      useFactory: () => {
        return {
          type: 'postgres',
          host: '127.0.0.1',
          port: 5432,
          username: 'postgres',
          password: '',
          database: 'postgres',
          synchronize: false,
          logging: false,
          entities: [],
        };
      },
    }),
    TypeOrmModule.forRootAsync({
      imports: [],
      name: 'secondary',
      useFactory: () => {
        return {
          type: 'postgres',
          host: '127.0.0.1',
          port: 5432,
          username: 'postgres',
          password: '',
          database: 'postgres2',
          synchronize: false,
          logging: false,
          entities: [],
        };
      },
    }),
  ],
})
export class DatabaseModule {}
```

3. App module
```ts
@Module({
  imports: [DatabaseModule],
  providers: [],
  controllers: [],
})
export class LightAppModule {}
```

4. Bootstrap app
```ts
async function bootstrap() {
  const context = await NestFactory.createApplicationContext(LightAppModule);

  context.close();
}

bootstrap();
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | macOS   |
| Node.js version     |18.12.1 |
| Typescript version  | 4.9.4  |
| TypeORM version     | 0.3.11  |
| Nestjs version     | 9.2.1 |

### Additional Context

The first Datasource is destroyed successfully. 
When it tries to get the reference to the second datasource to then destroy it, it cannot be found (maybe because it somehow references the same one).

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by sinkhaha** [comment]
It seems that the problem is Nest.js, not typeorm

**Comment by rubber-bird** [comment]
You might want to address this issue [here](https://github.com/nestjs/typeorm) . As Modules are wrapper for typeorm used in Nestjs. The error caused after onApplicationShutdown hook in Nestjs

**Comment by mridang** [comment]
I'm having the same issue but when the test suits are torn down. I'm new to NestJS and Typeorm - is there any way for me to get around this while there's a patch for this issue? Any help is appreciated. 🙏🏼

**Comment by Vikash-novo** [comment]
You have to pass the same name under `useFactory`.

`TypeOrmModule.forRootAsync({
      imports: [],
      name: 'secondary',
      useFactory: () => {
        return {
          ...,
          name: 'secondary'
        };
      },
    }),`
    
  The reason of this problem is `getConnectionToken` function which uses for getting connection by name from options.

**Comment by yurilongaray** [comment]
I have the same issue here... Any updates so far?

**Comment by sinhpn92** [comment]
> re-written solution.
> 
> Wirte same `name` property to `useFactory` and `forRootAsync` object
> 
> eg.
> 
> ```ts
> TypeOrmModule.forRootAsync({
> 	imports: [],
> 	name: 'secondary', // this
> 	useFactory: () => ({
> 		...anything,
> 		name: 'secondary' // this
> 	})
> });
> ```

Thanks. I solved my issue.

**Comment by gigi** [comment]
@sinhpn92 @opnay 
Thanks!
`name` is deprecated now for useFactory. Do you know the alternatives?

**Comment by sshevlyagin** [comment]
Name is deprecated, but that's still the thing that fixed it for me when using `TypeOrmOptionsFactory`

```
export class DbConfigServiceTest implements TypeOrmOptionsFactory {
    createTypeOrmOptions(): TypeOrmModuleOptions {
        return {
            type: 'sqlite',
            database: ':memory:',
            entities: [],
            synchronize: true,
            name: 'dbConnection1',
        };
    }
}
```
