### ISSUE TITLE
@types/node missing from package.json

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#97]
When cloning the repo - the @types/node library is missing

**Comment by pleerock** [comment]
its not missing https://github.com/typeorm/typeorm/blob/master/package.json#L62

**Comment by rightisleft** [comment]
odd - i'm getting node import errors on require

**Comment by pleerock** [comment]
did you fix it?

**Comment by pleerock** [comment]
feel free to reopen it if you still have something to add here
