### ISSUE TITLE
Mongo Bad Sort Specification

### ISSUE THREAD

**Issue by RyanQuackenbush** [typeorm/typeorm#970]
Might be missing something simple here, but with the Mongo driver if I do:

`someRepo.find({ where: {...}, order: {name: 'ASC'})`

I get a 'Mongo Error: bad sort specification'. If I try to do the sort the Mongo way (not in line with the type def):

`someRepo.find({ where: {...}, order: {name: 1})`

I get a `order[key].toLowerCase is not a function` error (as expected since the options are expecting 'ASC' or 'DESC').

I also tried a raw object query:

`someRepo.find({ where: {$query:{...}, $orderby: {name: 1}})`

Which does not error, but does not sort / order the results regardless if it's a 1 or -1.

It seems like 'ASC' / 'DESC' is not converted to 1, -1 for Mongo queries under the hood?

**Comment by pleerock** [comment]
What orm version are you using? I cannot reproduce this issue. See my test that confirms it.

**Comment by RyanQuackenbush** [comment]
Was on 0.1.0-alpha.33 from `yarn add typeorm` when I posted. I updated (v0.1.0 now) and it seems to be resolved. Appreciate the response.
