### ISSUE TITLE
https://typeorm.io/ is not loading

### ISSUE THREAD

**Issue by shajanjp** [typeorm/typeorm#9705]
### What was unclear or otherwise insufficient?

https://typeorm.io/ is not loading properly.

### Recommended Fix

Fix the homepage.

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Siddhesh1992** [comment]
same issue browsing through documentation. clicking through menus nothing seems to work
``https://typeorm.io/embedded-entities`` 
getting 
Found a typo and want to contribute to the documentation? Edit this page on Github!

**Comment by rubber-bird** [comment]
What exactly is not working?

**Comment by Deepak22448** [comment]
only side navigation loads up and nothing else is visible on site.

**Comment by AlexMesser** [comment]
Works for me. 

@shajanjp, @Siddhesh1992, @Deepak22448 Can you check it through some VPN service to make sure it's not blocked on your side?

**Comment by Deepak22448** [comment]
@AlexMesser thanks a lot , it works with VPN.

**Comment by AlexMesser** [comment]
BTW, a quick googling shows that [GitHub content domain blocked in India](https://timesofindia.indiatimes.com/gadgets-news/github-content-domain-blocked-for-these-indian-users-reports/articleshow/96687992.cms).

Closing as there is no problem from our side.

**Comment by shvamabps** [comment]
Can't typeorm change the hosting? So that everyone can have access to the product properly without installing third-party applications like VPN.
