### ISSUE TITLE
 Reasons for fixing left join in repository queries

### ISSUE THREAD

**Issue by eric-byun** [typeorm/typeorm#9708]
### Issue description

fixing left join on create query from repository

### Expected Behavior

https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts#L3873

It is fixing left join.

i made a query from repository
```javascript
fooRepository.find({
  relations: {
   bar: true,
 }
});
```

I expected the query below.
```sql
select * from foo join bar;
```

But the query below was executed.
```sql
select * from foo left join bar;
```

That is the result what i don't want. I found the above code to be the problem.
Why is fixing left join?

I want set the joinType in Entity like this 
`@OneToMany(() => foo, (foo) => foo.bar, { joinType: 'inner' })`..
Please tell me reason..

### Actual Behavior

```sql
select * from foo left join bar;
```

### Steps to reproduce

It is fixing to `left`

https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts#L3873

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  |
| Typescript version  | x.y.zzz  |
| TypeORM version     | x.y.zzz  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by iJhefe** [comment]
what do you think about #9710 behavior ?

**Comment by pleerock** [comment]
> Please tell me reason..

because other users can suppose opposite, e.g. the following code:

```ts
fooRepository.find({
  relations: {
   bar: true,
 }
});
```

to be executed as:

```ts
select * from foo left join bar;
```

And unlike the current implementation, it won't be possible to customize the behavior. So, current behavior makes more sense.

> @OneToMany(() => foo, (foo) => foo.bar, { joinType: 'inner' })

This solution doesn't make sense, because it's inflexible. Once you'll need more dynamic behavior at some place in your app - you'll endup writing your application.

As I mentioned in #9710 you can achieve it the following way:

```ts
const users = await manager.find(User, {
   relations: {
    posts: true,
  },
  where: {
    posts: Not(IsNull())
  }
})
```
