### ISSUE TITLE
[Bug] UpdateById broken due to wrong operation?

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#971]
So here's the entity code:
```ts
@Entity('MON_CONTROL_PLACE', {
  orderBy: {
    name: 'ASC',
    id: 'DESC',
  },
} as any)
export class ControlPlace {
  @PrimaryGeneratedColumn({
    // name: 'MON_CONTROL_PLACE_ID',
  })
  id: number

  @Column({
    nullable: false,
    unique: true,
  })
  name: string

  // Relations
  @OneToMany(
    (type) => RouteLine,
    (routeLine) => routeLine.controlPlace,
  )
  routeLines: Promise<RouteLine[]>

  @CreateDateColumn()
  createdAt: Date

  @UpdateDateColumn()
  updatedAt: Date

  @VersionColumn()
  version: number
}
```
Here's the relation code:
```ts
@Entity('MON_ROUTE_LINE', {
  orderBy: {
    id: 'DESC',
  },
} as any)
export class RouteLine {
  @PrimaryGeneratedColumn({
    name: 'MON_ROUTE_LINE_ID',
  })
  id: number

  @Column('real', {
    default: 0,
  })
  kms: number

  @Column('time without time zone', {
    nullable: false,
  })
  horas: Date

  // Relations
  @ManyToOne(
    (type) => Route,
    (route) => route.routeLines,
    { nullable: false },
  )
  @JoinColumn({
    // name: 'MON_ROUTE_ID',
  })
  route: Promise<Route>

  @ManyToOne(
    (type) => ControlPlace,
    (controlPlace) => controlPlace.routeLines,
    { nullable: false },
  )
  @JoinColumn({
    // name: 'MON_CONTROL_PLACE_ID',
  })
  controlPlace: Promise<ControlPlace>

  @CreateDateColumn()
  createdAt: Date

  @UpdateDateColumn()
  updatedAt: Date

  @VersionColumn()
  version: number
}
```
And here's the error:
![image](https://user-images.githubusercontent.com/9698639/31058827-233f6894-a6c0-11e7-9131-940daf931efe.png)

**Comment by luchillo17** [comment]
@pleerock It seems same for `deleteById`.

Also i tought i fixed this in #853 but your comment about not escaping made me revert that part:
https://github.com/typeorm/typeorm/pull/853/files/97caf1e60ad10fdf58c995b721dbf35d1a78adf1#diff-d7a4c1b1f7f4e70045299ac1a6b69a8d

**Comment by luchillo17** [comment]
After tracking where it breaks, seems this lines are the start, i'm trying to narrow where it breaks (very likely the lazy-wrapper?): [src/persistence/SubjectBuilder.ts#L272-L277](https://github.com/typeorm/typeorm/blob/master/src/persistence/SubjectBuilder.ts#L272-L277)

**Comment by luchillo17** [comment]
Next level to narrow down is [src/query-builder/SelectQueryBuilder.ts#L1397-L1405](https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts#L1397-L1405)

**Comment by luchillo17** [comment]
F*(k, i'm such a derp, `name` in the default `orderBy` args of the entity doesn't exist in the entity, at least i'm the only one who spent half a day on this.

**Comment by luchillo17** [comment]
So **please ignore the above**, this is the issue at hand, the query is:
```ts
return connection
      .manager
      .updateById(ControlPlace, data.id, data)
```
However the result is:
![image](https://user-images.githubusercontent.com/9698639/31060872-50e95258-a6e0-11e7-9df2-efd057d0edb8.png)

You can see it tries to select and then **`insert`** when it should be an **`update`**.

**Comment by luchillo17** [comment]
So `updateById` selects the entity, overrides the partial entity values passed, then calls to `EntityManager` 's `save()` method, which i think doesn't make any distinction about how to save.

**Comment by luchillo17** [comment]
Found the issue, if i don't remove the id from the partial entity it breaks, had to do this:
```ts
const { id, ...control } = data
    return connection
      .manager
      .updateById(ControlPlace, id, control)
      .then(() => true)
```
@pleerock Is that normal behavior?

**Comment by pleerock** [comment]
`update` and `updateById` will be refactored and improved soon, it must use `UpdateQueryBuilder` instead of using repository's find and save as it does now

**Comment by pleerock** [comment]
I refactored `update` and `updateById` - now they are using update query builder - this is how they should work from the beginning. Please check latest updates in 0.1.1 once it gets released

**Comment by luchillo17** [comment]
The refactor changes are in docs?

**Comment by pleerock** [comment]
no, changes are in internal implementation, there is no changes in public api

**Comment by luchillo17** [comment]
So i still have to extract the id of the instance before updating?, or does it accepts now the id in object?

**Comment by pleerock** [comment]
It simply generate UPDATE query based on given `conditions`, in case of updateById based on the provided `id`.

**Comment by luchillo17** [comment]
What i meant was if i can stop the need of deleting the id of the object i'm gonna save, from this:
```ts
const { id, ...control } = data
    return connection
      .manager
      .updateById(ControlPlace, id, control)
      .then(() => true)
```
To this:
```ts
return connection
      .manager
      .updateById(ControlPlace, data.id, data)
      .then(() => true)
```
Note how in second one i don't do destructuring.

**Comment by pleerock** [comment]
it shall work, please test it.

**Comment by luchillo17** [comment]
For some reason it says that certain relation cannot be null, which in theory should already have a value in database since is an update, seems like if i don't extract the `id` out of `data` then it doesn't take it as a partial.

**Comment by vance** [comment]
it works if you only provide relations as an `id`. If you include a real entity instance, it may break _even though_ the data for the column with null constraint is already saved.

**Comment by luchillo17** [comment]
I was not trying any relation id, i'm talking about the entity itself, i have to extract the `id` out or it will not take it as a partial.

**Comment by vance** [comment]
ok, misunderstanding. By "extract" you mean omit or remove.... Perhaps these are two different issues then (but I bet at the core it is related as it iterates through relations).

**Comment by luchillo17** [comment]
By extract i meant put it in a variable, then delete it from the object, in https://github.com/typeorm/typeorm/issues/971#issuecomment-337460995 i do it by destructuring, but the same can be achieved by:
```ts
    const id = data.id
    delete data.id    //  <---- Here's where we delete

    return connection
      .manager
      .updateById(ControlPlace, id, data)
      .then(() => true)
```
