### ISSUE TITLE
Support mysql2 3.x

### ISSUE THREAD

**Issue by cduff** [typeorm/typeorm#9714]
### Issue description

typeorm peerDependencies doesn't support latest mysql2 3.x

### Expected Behavior

https://typeorm.io/#installation says

> you can install `mysql2` instead as well

`mysql2` recently released version 3.x which I'd expect to be able to use.

### Actual Behavior

`npm install` results in errors:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: typeorm@0.3.11
npm ERR! Found: mysql2@3.0.1
npm ERR! node_modules/mysql2
npm ERR!   mysql2@"3.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional mysql2@"^2.2.5" from typeorm@0.3.11
npm ERR! node_modules/typeorm
npm ERR!   typeorm@"0.3.11" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: mysql2@2.3.3
npm ERR! node_modules/mysql2
npm ERR!   peerOptional mysql2@"^2.2.5" from typeorm@0.3.11
npm ERR!   node_modules/typeorm
npm ERR!     typeorm@"0.3.11" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
...
```

### Steps to reproduce

Try running `npm install` with the following dependencies specified:

``` json
{
  "mysql2": "3.0.1",
  "typeorm": "0.3.11"
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 11 Pro |
| Node.js version     | 18.13.0  |
| Typescript version  | 4.9.4  |
| TypeORM version     | 0.3.11  |

### Additional Context

If I run `npm install --legacy-peer-deps` then my app/typeorm appears to run fine.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Chen-913** [comment]
Same problem

**Comment by michalSagi1** [comment]
Same problem here!
```
    "mysql2": "^3.0.1",
    "typeorm": "^0.3.11",
```

The error: conflict between "mysql2" and "typeorm" (which requires mysql2 v2.X)
![image](https://user-images.githubusercontent.com/102920178/216024258-fdb836a5-faf4-4b6b-b541-c9539adc4c79.png)

**Comment by leoander01** [comment]
This is because typeorm has not updated the `mysql2` dependency to support the v3.x version. This will probably be fixed in the next update.
