### ISSUE TITLE
[Enhancement]: RowVersion column

### ISSUE THREAD

**Issue by iz-iznogood** [typeorm/typeorm#973]
Hi,

I need optimistic concurrency with the version column generated from db.
I have asked before and this is not supported. I checked the code and it is definitely doable. 
I can give this a try but I would like to check with you how would you prefer the parameterization to go.
I can create a new decorator or expand the existing (like @Version(isDbGenerated: boolean ...)
Also I can expand the existing isVersion property on the metadata by making it an enum or add a new one.

Adding a new set of options - decorator will be clearer I believe.

@pleerock,  @AlexMesser any preferences or thoughts ?

**Comment by pleerock** [comment]
Can you please provide an overview how it will be implementation, what are benefits and drawbacks?

**Comment by iz-iznogood** [comment]
Hi,

I will start with the benefits and drawbacks

We need this since not everyone uses solely TORM for data access. In many cases records are also updated using stored procedures, triggers or even raw sql statements. We need to track there changes and use them for optimistic concurrency since they are closest to the actual datasource. Using these system columns is the only way that guarantees than no data change goes undetected.

The drawback is that not all RDBMS support this. Some dont really need this (sqlite) but in cases it is not supported the code should throw error for unsupported configuration.

I will come back with the proposed changes shortly

Thanks

**Comment by iz-iznogood** [comment]
I checked the code and I see that the main changes shound be around SubjectOperationExecutor and SelectQueryBuilder

The SubjectOperationExecutor prepares the data for saving and the QueryBuilder uses the column value for optimistic concurrency checks.

What I propose is a change in the VersionColumn decorator to pass an optional parameter type: "local" | "db". This parameter is pushed to the ColumMetadataArgs and then to ColumnMetadata
The "local" value keeps the behaviour as it is now.
The "db' value just excludes the column from SubjectOperationExecutor since it will be updated in the database automatically.
We will also need a Database Column type map for the "db" generated case because there are specific datatypes per RDBMS that provide this functionality (e.g rowversion, timestamp) and are different from the int data type that we use now for Version columns.

The QueryBuilder will not need any changes I believe.
Also I will need to add a parameter to EntitySchemaColumn to provide the same functionality when we use EntitySchemas.

Please provide feedback. If you like this I can work on that asap

Thanks

**Comment by pleerock** [comment]
@iz-iznogood are you still with us?)

**Comment by pleerock** [comment]
I have refactored how persistence works. Now version and create/update columns are only set on a database-side and separate query is executed to  for drivers not supporting returning/output to get version/create/update and other column values after save method call. You can test it in `npm i typeorm@next`

**Comment by iz-iznogood** [comment]
Hey @pleerock  I am here, but right now I am implementing - finishing the client side part of an application (I use TORM on the server).I plan to return to server side in a couple weeks at most, so I will start contributing again to TORM.

I will check the code and see how this is implemented and come back with any comments - questions I might have.

Thanks

**Comment by binki** [comment]
Hello,

I am also interested in this feature. I would like to be able to have `.save()` throw an error if the value of a `@VersionColumn` changed between when I loaded the entity and the `UPDATE` runs. In scenarios where there is low contention, this would let me safely use the type-safe `.find()` and `.save()` APIs and do my conditional checks on the entity’s properties in TypeScript instead of needing to use `QueryBuilder` to write a conditional `UPDATE` manually. If the change would be rejected by the optimistic concurrency check, I could just retry the whole `.find()`, edit+check, `.save()` sequence and it will eventually succeed.

Were you still working on it, @iz-iznogood?

I am currently planning to check if `@EventSubscriber` is sufficient for me to implement this in my own code outside of typeorm.
