### ISSUE TITLE
How to convert the below query into a format suitable for userRepository.find() API 

### ISSUE THREAD

**Issue by Rstar1998** [typeorm/typeorm#9733]
### What was unclear or otherwise insufficient?

I have a query like this : 

```
select * from analytics.temp t where t.company_id = 'xyz' AND t.aff_id = 'xyz' AND t.lay_type =  'xyz' AND (t.email = 'abc' OR t.mobile =  'afc' )

```
 Now how do I convert the below query into a format suitable for userRepository.find() API.
I have seen this stackoverflow post [https://stackoverflow.com/questions/71783696/typeorm-find-where-conditions-and-or-chaining] but it doesn't have solution for  the format suitable for userRepository.find()

### Recommended Fix

NA

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by AlexMesser** [comment]
For questions / general support, please check out our [Slack channel](https://join.slack.com/t/typeorm/shared_invite/zt-uu12ljeb-OH_0086I379fUDApYJHNuw), [StackOverflow](https://stackoverflow.com/questions/tagged/typeorm) or check [TypeORM's documentation](https://typeorm.io).
