### ISSUE TITLE
TypeORM types in v0.3.x no longer support FindOperators on enums

### ISSUE THREAD

**Issue by hfhchan-plb** [typeorm/typeorm#9745]
### Issue description

TypeORM v0.3.x no longer supports FindOperators on enums

### Expected Behavior

TypeORM v0.3.x should support FindOperators on enums.

### Actual Behavior

The error
```
Type 'FindOperator<Status>' is not assignable to type 'FindOperator<Status.CONFIRMED>'.
```
appears.

### Steps to reproduce

```ts
enum Status{ CONFIRMED = 'confirmed', PENDING = 'pending', BLOCKED = 'blocked'}

// somewhere else
repo.findBy({ status: Any([Status.CONFIRMED, Status.PENDING]) }
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Typescript version  | 4.7.4  |
| TypeORM version     | 0.3.11 |

### Additional Context

This error occurs because `status` is getting typed as `Status | FindOperator<Status.CONFIRMED> | FindOperator<Status.PENDING> ...` instead of `Status | FindOperator<Status>`.

This used to work in v0.2.x.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by rahulgi** [comment]
I think this can be closed as of https://github.com/typeorm/typeorm/pull/9607 which got released in [0.3.12](https://github.com/typeorm/typeorm/releases/tag/0.3.12)
