### ISSUE TITLE
Add support for pg-native driver

### ISSUE THREAD

**Issue by Nopik** [typeorm/typeorm#975]
pg-native (https://github.com/brianc/node-pg-native) offers high-performance PostgreSQL connectivity.

**Comment by pleerock** [comment]
This looks easy to implement. Are you able to contribute? Do you know what are major API differences between `pg` and `pg-native` ?

**Comment by Nopik** [comment]
According to https://node-postgres.com/features/native they should be pretty normalized, maybe with some exception on subtle edge cases. 

Also, the whole implementation seems to consist of using

```
const { Client, Pool } = require('pg').native
```

instead of

```
const { Client, Pool } = require('pg')
```

So, in this project maybe you will want to create `postgres-native` driver (99.99% identical to `postgres`) or something like that. Maybe just `native: true` option passed to postgres driver.

I would be OK to provide few lines worth of PR, sadly not for bigger development - especially that my knowledge of typeorm internals is next to nonexistent.

**Comment by Nopik** [comment]
And indeed, when I added `.native` in https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L583, I got `pg-native not found` error (being printed to console) and `this.postgres` was `null`. When I installed the `pg-native` and restarted my app, the basic queries were seemingly OK. I mean, I could log in/out of the database + execute some basic queries to display initial screen. Didn't do any deeper tests.

**Comment by pleerock** [comment]
Can you check a bit deeply then? If it works then we can simply check `pg-native` is installed and use `.native` instead, inside PostgresDriver. And that can be a few lines PR.

**Comment by pleerock** [comment]
This will be released in 0.1.1. Please check it once its released.

**Comment by Nopik** [comment]
We've upgraded all our apps to pg-native + typeorm@0.1.1, and it seem to work fine - no drawback detected.

**Comment by krzkaczor** [comment]
@Nopik Have you benchmarked `pg-native` vs `pg`? I wonder if there is any real world gain by using native driver.

**Comment by Nopik** [comment]
@krzkaczor I haven't done any meaningful benchmarks. You might find this useful, though: https://magic.io/blog/asyncpg-1m-rows-from-postgres-to-python/
