### ISSUE TITLE
0.1.0 final is going to be released 

### ISSUE THREAD

**Issue by pleerock** [typeorm/typeorm#977]
Hey guys, Im going to release `0.1.0` tomorrow. I have updated a website and documentation. I wanted to ask everybody who can [review everything there](http://typeorm.io). Also need to do a grammar check, Im sure you'll find lot of mistakes there.

Thank you!

**Comment by luchillo17** [comment]
Wow new docs, nice.

**Comment by shousper** [comment]
New website looks great!

Strongly suggest closing off [this issue about timestamps](https://github.com/typeorm/typeorm/issues/838) before release though. Kind of looks like it should already be closed??

**Comment by shousper** [comment]
Some broken links on this page: http://typeorm.io/#/connection-options -- I think just the "Learn more about <blah>" links need updating as they point to `.md` files at the moment.

**Comment by pleerock** [comment]
@shousper thank you. Are you able to create PRs for all issues are you able to resolve by yourself? Its really easy, you can edit page directly from the website (link on the bottom of each page)

**Comment by shousper** [comment]
@pleerock Submitted a PR for the link fixes, but the others you might wanna look at ;)

**Comment by rajshrimohanks** [comment]
@pleerock Man, I was off for 3 weeks and so much has happened. The new website looks fantastic. Kudos! :)

**Comment by pleerock** [comment]
Ive made a final `0.1.0 ` release and published links in reddit. Please upvote and left some comments there if you are a reddit users!

**Comment by NoNameProvided** [comment]
You should send it to Hacker News as well. With the “Show HN: ... “ format.

**Comment by pleerock** [comment]
Upvote [this one.](https://www.reddit.com/r/programming/comments/759gal/typeorm_010_is_released_besides_mysql_postgresql/) Some a****** downvoted it.

**Comment by rajshrimohanks** [comment]
I'm going to create a Reddit account just to upvote this. 👍

**Comment by jcudzich** [comment]
Good job @pleerock, do not worry about haters! Keep it up!!!
I voted up on your reddit post.

**Comment by pleerock** [comment]
@jcudzich thanks 😆
