### ISSUE TITLE
Support for Microsoft Azure SQL Edge databases

### ISSUE THREAD

**Issue by sbleon** [typeorm/typeorm#9783]
### Feature Description

I want to try working on the TypeORM code, but I can't run SQL Server on my ARM-based machine (even in Docker). Azure SQL Edge is a good alternative, and largely compatible with SQL Server, but the TypeORM test suite doesn't pass with Edge because Edge doesn't support types column types (because it depends on CLR).

### The Solution

I have a couple of ideas. I'm not sure which would be best.

1. Add a platform test to `SqlServerDriver` that allows it to determine if the current database supports spatial types, then adapt the test suite and entity definitions (e.g. mssql/entity/Post) to check for the results of the test and skip spatial columns defs and tests if the database doesn't support it.
2. Add a new driver and other infrastructure for Edge that is distinct from (but could inherit from) the existing SQL Server code.

My inclination is towards option 1, because it seems like a relatively small difference between SQL Server and SQL Edge, but I'm not sure if it's possible to conditionally define columns in the entity.

### Considered Alternatives

If I comment out the spatial stuff, I can get a good chunk of the test suite passing. This might get me far enough to be able to work on TypeORM a little bit.

Test results with SQL Edge (as far as I've gotten):
  972 passing (3m)
  21 pending
  1 failing

### Additional Context

On one of our projects, we use TypeORM with SQL Server  (in production) and with Azure SQL Edge (in development). Despite the database platform difference, this works well for us, as TypeORM works very nicely with Azure SQL Edge (assuming we don't try to use any SQL Server-specific features that Azure SQL Edge doesn't support).

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [X] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by sbleon** [comment]
If we can get this figured out, I am planning to work on https://github.com/typeorm/typeorm/issues/8646

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.

**Comment by sbleon** [comment]
Thanks for looking at this @stim371 !

We're no longer using Azure SQL Edge because MS improved the compatibility of their SQL Server images, and we're back to running SQL Server for local dev (albeit in AMD64 arch w/ emulation for us Mac folks).
