### ISSUE TITLE
`QueryFailedError: function uuid_generate_v4() does not exist` even though extension is installed

### ISSUE THREAD

**Issue by leonvisscher** [typeorm/typeorm#9787]
### Issue description

I am using the `@PrimaryGeneratedColumn('uuid')` decorator with my postgres db, but still get the `QueryFailedError: function uuid_generate_v4() does not exist` error even though extension is installed (`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`)

### Expected Behavior

No error

### Actual Behavior

Error

### Steps to reproduce

Connect to my postgresql db that has the "uuid-ossp" extension installed and define an entity that has the `@PrimaryGeneratedColumn('uuid')` field.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 18.10.0  |
| Typescript version  | 4.9.4  |
| TypeORM version     | 0.3.12  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by leonvisscher** [comment]
I had installed the "uuid-ossp" extension in a separate "extensions" schema and this gave the error. When installing the extension in the default (public) schema, it worked.

**Comment by emmanuel39hanks** [comment]
In case anyone is still encountering this issue, here are two solutions:

The first solution involves enabling the uuid-ossp extension in your PostgreSQL database. Use the following SQL command:


`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`

For the second solution, use the @BeforeInsert() decorator from TypeORM and the uuid npm package. Change your ID from @PrimaryGeneratedColumn('uuid') to simply @PrimaryColumn(). Then, append to the end of your entity class:

```
@BeforeInsert()
generateUuid() {
  if (!this.id) {
    this.id = uuidv4();
  }
}
```

This ensures that a UUID is generated from your application using the uuid package.
