### ISSUE TITLE
Postgres connection promise resolves despite no connection, later fails when trying to operate on db

### ISSUE THREAD

**Issue by zakhenry** [typeorm/typeorm#98]
Back into working with this wonderful library, thanks!

I've switched to postgres, and so far so good, but I just ran into an issue where I'm trying to gracefully handle a connection error when the database is has not been started, however I notice that due to pooling the postgres driver does not immediately attempt a connection meaning that connection succeeds despite there being no database.

Attempting to do something with the connection eg `await connection.driver.createQueryRunner();` causes `Error: connect ECONNREFUSED 127.0.0.1:5432` to be thrown, but oddly I can't catch it?

**Comment by zakhenry** [comment]
*might* be related to this issue with pg https://github.com/brianc/node-postgres/issues/1142

**Comment by zakhenry** [comment]
Ok, more investigation, looks like it's an issue with `pg`:

Adding a whole bunch of debug:
```ts
retrieveDatabaseConnection() {
        if (this.pool) {
            return new Promise((ok, fail) => {
                try {
                  this.pool.connect((err, connection, release) => {

                    if (err) {
                      console.log('ERRR', err, connection);
                      return fail(err);
                    }
                    console.log('ok!');
                    let dbConnection = this.databaseConnectionPool.find(dbConnection => dbConnection.connection === connection);
                    if (!dbConnection) {
                      dbConnection = {
                        id: this.databaseConnectionPool.length,
                        connection: connection,
                        isTransactionActive: false
                      };
                      this.databaseConnectionPool.push(dbConnection);
                    }
                    dbConnection.releaseCallback = () => {
                      if (dbConnection) {
                        this.databaseConnectionPool.splice(this.databaseConnectionPool.indexOf(dbConnection), 1);
                      }
                      release();
                      return Promise.resolve();
                    };
                    ok(dbConnection);
                  }).catch((e) => {
                      console.log('caught in chain', e);
                  });
                } catch (e){
                    console.log('caught', e);
                }
            }).catch((e) => {
                console.log('caught promise', e);
            });
        }
        if (this.databaseConnection)
            return Promise.resolve(this.databaseConnection);
        throw new ConnectionIsNotSetError_1.ConnectionIsNotSetError("postgres");
    }
```

Results in 
```
[server] ERRR { Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 } null

[server] Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
```

The first log being the expected failure and the second being the uncaught exception. Note none of the promise `catch`es ever logged...

**Comment by pleerock** [comment]
did you fix it? can we close it?

**Comment by zakhenry** [comment]
Hey, nope, I was about to work around it temporarily by setting connection pooling to false, but that's not an ideal long term solution. I think either the upstream project (node-postgres) needs to be fixed or maybe there can be a manual workaround in typeorm to handle pooling directly. I'll pick this up later this week to see if I can come up with a fix somewhere appropriate to get pooling working for typeorm with pg

**Comment by charmander** [comment]
Should have been fixed by brianc/node-pg-pool#31. Upgrade to pg-pool@1.6 (or downgrade to 1.4).

**Comment by jarinwhite** [comment]
I am seeing this same issue when using the mysql driver, so I don't think it's necessarily unique to pg. usePool: false fixes the problem, but again not an ideal solution.

**Comment by pleerock** [comment]
would be great if someone will create a repo where this issue can be clearly reproduced

**Comment by pleerock** [comment]
closing as there is no answer from op
