### ISSUE TITLE
Bad migration generation with geometry on Postgis

### ISSUE THREAD

**Issue by kevin-lot** [typeorm/typeorm#9835]
### Issue description

Bad migration generation with GeometryCollection on Postgres 14 Postgis 3.2

### Expected Behavior

With typeorm 0.3.11 `ALTER TABLE "layer" ALTER COLUMN "geom" TYPE geometry(GEOMETRY ,4326)`

### Actual Behavior

With typeorm 0.3.12 `ALTER TABLE "layer" ALTER COLUMN "geom" TYPE geometry(GeometryCollection,4326)`

### Steps to reproduce

With TypeOrm 0.3.12

To match the new typescript definition.

```
SpatialColumnOptions.d.ts
spatialFeatureType?: Geometry["type"];

GeoJsonTypes.d.ts
export type Geometry = Point | LineString | Polygon | MultiPoint | MultiLineString | MultiPolygon | GeometryCollection;
```

We have to change 
```
@Column('geometry', { nullable: true, spatialFeatureType: 'Geometry', srid: 4326, transformer: layerGeomTransformer })
```
to
```
@Column('geometry', { nullable: true, spatialFeatureType: 'GeometryCollection', srid: 4326, transformer: layerGeomTransformer })
```

With this update, a migrate file is generated with `ALTER TABLE "layer" ALTER COLUMN "geom" TYPE geometry(GeometryCollection,4326)`

But in Postgres 14 this line returns: `ERROR:  syntax error at or near "GeometryCollection"`

I think the issue is located here: https://github.com/typeorm/typeorm/blob/58fc08840a4a64ca1935391f4709a784c3f0b373/src/driver/postgres/PostgresDriver.ts#L1136

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Linux        |
| Node.js version     | 16.19.0  |
| Typescript version  | 4.9.5  |
| TypeORM version     | 0.3.12  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Fabiencdp** [comment]
The problem seems to come from @Column types : 

```
    // NOK Type error
    // Argument of type 'string' is not assignable to parameter of type '(type?: any) => Function'.
    @Column('geometry', { nullable: true, spatialFeatureType: 'Geometry', srid: 4326, transformer: undefined })
    
    // OK
    @Column({ type: 'geometry', nullable: true, spatialFeatureType: 'Geometry', srid: 4326, transformer: undefined })
```

Using option with `type: 'geometry'` is valid.
