### ISSUE TITLE
mssql peer dep not updated

### ISSUE THREAD

**Issue by ddbtrmatic** [typeorm/typeorm#9839]
### Issue description

mssql devDependency was updated, but not the peerDependency

### Expected Behavior

Expect peerDependency to align with devDependency

### Actual Behavior

devDependency is `^9.1.1` but peerDependency remains `^7.3.0`

https://github.com/typeorm/typeorm/pull/9763

### Steps to reproduce

https://github.com/typeorm/typeorm/blob/master/package.json

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | x.y.zzz  |
| Typescript version  | x.y.zzz  |
| TypeORM version     | x.y.zzz  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [X] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by mderriey** [comment]
We're also interested in this, as the downstream `tedious` dependency of the `mssql` is fairly old and doesn't seem to use `@azure/identity` for AAD auth.

**Comment by mikec-tw** [comment]
BUMP ^ , this is causing vulnerability warnings for us from other packages affected by this issue.

**Comment by ddbtrmatic** [comment]
The work-around we are using

```
// package.json

  "overrides":{
    "typeorm": {
      "mssql": "$mssql"
    }
  }
```
