### ISSUE TITLE
Documentation: Connection options page has broken links

### ISSUE THREAD

**Issue by shousper** [typeorm/typeorm#988]
Related to #977

Page: http://typeorm.io/#/connection-options
Description: Most of the "Learn more about <blah>" links are still pointing to relative `.md` files. Maybe just needs some updates.

**Comment by shousper** [comment]
Actually it looks like there may be more broken links about. The [`@Index` page](http://typeorm.io/#/decorator-reference/index) also has broken "Learn more about" links.

**Comment by daniel-lang** [comment]
Thanks again, for pointing out, that the links don't work. I guess you can close this issue.
