### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined on Node 6.9.1

### ISSUE THREAD

**Issue by bcherny** [typeorm/typeorm#99]
Solutions from https://github.com/typeorm/typeorm/issues/51 and https://github.com/typeorm/typeorm/issues/35 did not work for me.

- Node: 6.9.1
- TypeORM: 0.0.2-alpha.70
- PG: 6.1.0

Code below:

```ts
import { Column, PrimaryColumn, Table } from 'typeorm'

@Table()
export class Business {

  @PrimaryColumn('text')
  id: string

  @Column('text')
  name: string

  @Column('text')
  image_url: string

  @Column('float')
  lat: number

  @Column('float')
  lng: number

  @Column('float')
  rating: number

  @Column('text')
  url: string

  @Column('text')
  source: string
}
```

**Comment by pleerock** [comment]
do you have same issue as #52 ? If you have this error on `type.name.toLowerCase()` line, then 

```typescript
 "emitDecoratorMetadata": true,
 "experimentalDecorators": true,
```

is 100% solution to this problem. Make sure your compiler uses tsconfig where these options are

**Comment by bcherny** [comment]
Thanks for the quick response!

As I said, I read through both issue and no solutions (including that one) seemed to work.

I am running TypeScript via tsc via npm scripts:

```json
{
  "scripts": {
    "build:sources": "tsc -p ./tsconfig.json"
  }
}
```

**Comment by pleerock** [comment]
did you include `import "reflect-metadata"` in the top of your main file before create a connection?

**Comment by bcherny** [comment]
Yes.

**Comment by pleerock** [comment]
can you provide a full log of your error?

**Comment by rightisleft** [comment]
after the change to tsconfig ensure all transpiled .js files are cleaned out

**Comment by pleerock** [comment]
@bcherny have you succeed with your issue?

**Comment by pleerock** [comment]
feel free to reopen it if you still have something to add here

**Comment by bcherny** [comment]
I ended up using pg, since my application just issued a few queries. Will reopen if I run into this again.
