### ISSUE TITLE
Documentation: @Index behaviour

### ISSUE THREAD

**Issue by shousper** [typeorm/typeorm#990]
Related to #977 

Pages: http://typeorm.io/#/entities/column-options and http://typeorm.io/#/decorator-reference/index
Description: The first [entities page](http://typeorm.io/#/entities) describes the [`@Column` decorator](http://typeorm.io/#/entities/column-options) option `unique` as being the same as putting `@Index` on a field. However, (I'm assuming) you need to specify `@Index({ unique: true })` to get the same behavior. This isn't particularly clear on the entities page and could maybe be clearer on the decorator reference page. It would be good if all the decorators on the decorator reference page could document all their options, similar to the first one you've got for `@Entity`, even if that means adding a "no options" item for decorators without any options. Just my 2 cents on that one though.

**Comment by pleerock** [comment]
its not the same, you are right. Its creating a unique constraint, but index.
