### ISSUE TITLE
JSON Datatype doesnt create JSON_Validation check constraint in mariadb

### ISSUE THREAD

**Issue by C0kkie** [typeorm/typeorm#9903]
### Issue description

If you use json datatype, it wouldn't create a json check validation which is supported since few mariadb version

### Expected Behavior

Automatically create check constraint 

### Actual Behavior

check constraint doesnt get created

### Steps to reproduce

```
@Entity("test")
export class Test extends BaseEntity {
    @PrimaryGeneratedColumn({ unsigned: true })
    id: number;

    @Column("json")
    title: string | null;
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Windows     |
| Node.js version     | 18.13.1  |
| Typescript version  | 5.0.x  |
| TypeORM version     | 0.3.12  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time, but I can support (using donations) development.

**Comment by smith-xyz** [comment]
@C0kkie testing locally, but interestingly I could get mariadb to create the the column by way of the alias and automatically create the constraint (since mariadb will). What is actually interesting is that typeorm was able to run an insert of bad json without receiving an error that it failed the constraint.

I think this may potentially relate to a bigger discussion because check constraints are supported now for both mysql and mariadb: https://github.com/typeorm/typeorm/issues/4148

Here is a log of SQL from my test
```bash
query: SELECT VERSION() AS `version`
query: SELECT * FROM `INFORMATION_SCHEMA`.`SCHEMATA` WHERE `SCHEMA_NAME` = 'test'
query: START TRANSACTION
query: SELECT concat('DROP VIEW IF EXISTS `', table_schema, '`.`', table_name, '`') AS `query` FROM `INFORMATION_SCHEMA`.`VIEWS` WHERE `TABLE_SCHEMA` = 'test'
query: SET FOREIGN_KEY_CHECKS = 0;
query: SELECT concat('DROP TABLE IF EXISTS `', table_schema, '`.`', table_name, '`') AS `query` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA` = 'test'
query: DROP TABLE IF EXISTS `test`.`user`
query: SET FOREIGN_KEY_CHECKS = 1;
query: COMMIT
query: START TRANSACTION
query: SELECT DATABASE() AS `db_name`
query: SELECT `TABLE_SCHEMA`, `TABLE_NAME` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA` = 'test' AND `TABLE_NAME` = 'user'
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'test' AND `TABLE_NAME` = 'typeorm_metadata'
query: CREATE TABLE `user` (`id` int NOT NULL AUTO_INCREMENT, `jsonData` json NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB
query: COMMIT
query: SELECT * FROM `INFORMATION_SCHEMA`.`SCHEMATA` WHERE `SCHEMA_NAME` = 'test'
query: START TRANSACTION
query: SELECT concat('DROP VIEW IF EXISTS `', table_schema, '`.`', table_name, '`') AS `query` FROM `INFORMATION_SCHEMA`.`VIEWS` WHERE `TABLE_SCHEMA` = 'test'
query: SET FOREIGN_KEY_CHECKS = 0;
query: SELECT concat('DROP TABLE IF EXISTS `', table_schema, '`.`', table_name, '`') AS `query` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA` = 'test'
query: DROP TABLE IF EXISTS `test`.`user`
query: SET FOREIGN_KEY_CHECKS = 1;
query: COMMIT
query: START TRANSACTION
query: SELECT DATABASE() AS `db_name`
query: SELECT `TABLE_SCHEMA`, `TABLE_NAME` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA` = 'test' AND `TABLE_NAME` = 'user'
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'test' AND `TABLE_NAME` = 'typeorm_metadata'
query: CREATE TABLE `user` (`id` int NOT NULL AUTO_INCREMENT, `jsonData` json NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB
query: COMMIT
query: START TRANSACTION
query: INSERT INTO `user`(`id`, `jsonData`) VALUES (DEFAULT, ?) RETURNING `id` -- PARAMETERS: ["\"{\\\"firstName\\\":\\\"Quality\\\",\\\"lastName\\\":\\\"Tester\\\"}\""]
query: COMMIT
query: SELECT `User`.`id` AS `User_id`, `User`.`jsonData` AS `User_jsonData` FROM `user` `User` WHERE (`User`.`id` = ?) LIMIT 1 -- PARAMETERS: [1]
query: START TRANSACTION
query: INSERT INTO `user`(`id`, `jsonData`) VALUES (DEFAULT, ?) RETURNING `id` -- PARAMETERS: ["\"{ bad_: true }\""]
query: COMMIT
```

**Comment by C0kkie** [comment]
I am a bit confused :D So does it work or? @smith-xyz

**Comment by smith-xyz** [comment]
@C0kkie sorry about that, summary: it works, column type is longtext and the constraint is created - I just don't think it works as I would like it to. When executing the insert with save(entity), it seems to always provide a valid json string (I think the value is always passed to JSON.stringify(), even though the value itself was not valid json. 

Just curious your thoughts on that. Not sure what your use case is. The constraint will be there but the orm itself will prevent it from breaking the constraint unless providing the sql.

**Comment by C0kkie** [comment]
@smith-xyz i think there will be still a usecase if someone will insert a value manually for example
