### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by jstafford74** [typeorm/typeorm#9911]
The website is down, [typeorm.io](https://typeorm.io/). 

Looking at network tab this is an error:

Request URL: https://unpkg.com/vue@2/dist/vue.min.js
Request Method: GET
Status Code: 520

**Comment by astrot1988** [comment]
still not working

**Comment by jimaek** [comment]
Consider switching to jsDelivr, a multi-CDN under active development https://cdn.jsdelivr.net/npm/vue@2/dist/vue.min.js

**Comment by pleerock** [comment]
Seems to be up again
