### ISSUE TITLE
Not able to see anything on website

### ISSUE THREAD

**Issue by shvamabps** [typeorm/typeorm#9918]
### What was unclear or otherwise insufficient?

![image](https://user-images.githubusercontent.com/37547983/230293021-3c041e69-c363-4c6c-9283-fcfd31fe6b0a.png)
No content 

### Recommended Fix

Maybe re deploy the website?

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by shvamabps** [comment]
@mojodna  @drnic  @dpickett  @lukaszklis

**Comment by lukaszklis** [comment]
Hey @shvamabps, there is no point in pinging randomly picked contributors who may not being directly involved in maintenance of this open-source project. You have earlier stated that "I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue", therefor please let people who _can_ do anything about the issue you posted take action whenever they have time to do so.

The only thing I can suggest for now is -- whenever you have trouble accessing documentation on the website, you can always check the documentation in the repository itself - the website serves contents of the _docs_ folder. 👉 https://github.com/typeorm/typeorm/blob/master/docs/data-source-options.md

**Comment by AlexMesser** [comment]
see #9705
