### ISSUE TITLE
DataSource.initalize() hangs on connection to Mongo

### ISSUE THREAD

**Issue by robertmain** [typeorm/typeorm#9922]
### Issue description

When connecting to an instance of MongoDB, TypeORM hangs

### Expected Behavior

I expected the code to run and my `.then()` block to be called

### Actual Behavior

The code just hangs, neither then `.then()` nor the `.catch()` block are called.

### Steps to reproduce

```typescript
new DataSource({
  type: 'mongodb',
  url: 'mongodb://127.0.0.1',
}).initialize()
.then((ds) => {
  console.log("Connected to MongoDB", ds.isInitialized);
})
.catch((error) => {
  console.log("Error connecting to MongoDB", error);
});
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Ubuntu       |
| Node.js version     | 14  |
| Typescript version  | 4.9.3 |
| TypeORM version     | 0.3.13  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [X] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by robertmain** [comment]
Looks like the issue is a peer dependency issue. Downgrading to mongo@4.15 fixes it for me. Upgrading again to 5.x breaks things again...

**Comment by dmitrye** [comment]
@robertmain typeorm now supports 5.x.x version of MongoDB. You should try it again and see if it resolves your hanging issue. My setup was hanging as well before they fixed it and I had downgraded to 4.x.x to address it as well.

**Comment by robertmain** [comment]
Yep. All fixed now! Thanks everyone!
