### ISSUE TITLE
typeorm 调用save方法时， 返回的model的主键id多了个0

### ISSUE THREAD

**Issue by HQHC** [typeorm/typeorm#9939]
### Issue description

typeorm 调用save方法时， 返回的model的主键id多了个0

### Expected Behavior

预期正常数据库id

### Actual Behavior

实际正常数据库id + 0

### Steps to reproduce

typeorm  ^0.3.11  版本调用save方法 然后取id

### My Environment

typeorm  ^0.3.11 

### Additional Context

midway框架

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by pleerock** [comment]
Sorry, I don't understand.
