### ISSUE TITLE
How to perform search operations on Mapping table which is automatically created in many-many relationship

### ISSUE THREAD

**Issue by imhari213** [typeorm/typeorm#995]
i want to perform search operation on regular_product_sku_maapper table which is automatically created by typeorm while establishing many-many relationship between regular_consumption table & product_sku table

**Comment by pleerock** [comment]
Depend on your task, in most cases you don't really need to work with tables created by many-to-many relation.

But if you really need, you can specify a table name in QueryBuilder:

```ts
const results = await connection.createQueryBuilder()
    .select()
    .from("regular_product_sku_maapper", "sku_mapper")
    .where("...")
    .getRawMany();
```

**Comment by imhari213** [comment]
Thanks,I will try it and get you back.
