### ISSUE TITLE
date column is unintentionally generated when not provided

### ISSUE THREAD

**Issue by Creatium** [typeorm/typeorm#9966]
### Issue description

Using update() method to update entity and not providing a date field, it gets generated by ORM, even though both nullable and default 'null' are set

### Expected Behavior

I would expect unprovided values to not be set by TypeORM if no such conditions are set by me.

### Actual Behavior

Date field value gets generated by TypeORM with current date and gets updated inside table.

### Steps to reproduce

The issue appears when trying to update entity.  I have a column that gets Date only when one of other columns is updated. When I manually check that fields are not updated, I do not provide Date field. But still during an update, TypeORM generates a new Date value with current date.

This is my entity:
```
@Column({
      nullable: true,
      default: null,
      transformer: {
         to(value) {
            return value ? new Date(value) : null;
         },
         from(value) {
            return value ? new Date(value) : null;
         },
      },
   })
   updatedAt: Date;
```

I am sending this command:

`await repository.update({ id: entityId }, { someOtherColumn: 'someValue' });
`

And then TypeORM updates both "someOtherColumn" and "updatedAt".

What am I missing? I also tried setting updatedAt to "Date | null". I also tried leaving column decorator completely empty. Still date is generated.

The issue seems to only appear in production. Running 1:1 same versions of packages in both environments and same databases.

Here is a very similar issue reported by other person: https://stackoverflow.com/questions/76048896/typeorm-is-overwriting-my-createat-date-even-when-i-am-not-using-createdatecolum

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Ubuntu     |
| Typescript version  | 4.9.5  |
| TypeORM version     | 0.3.11  |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by spotykatch** [comment]
It will be hard to reproduce. What else do you use in your project, and why don't you want to use `@UpdateDateColumn`?
