### ISSUE TITLE
[Bug] `RelationId` with `LazyRelation` doesn't allow to set the id directly when prefetched

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm#997]
So using the `@RelationId` decorator allows us to get the ids of the relation, even Lazy ones, i hoped we could just use them to create the entity without having to wrap them in a promise, this use case is very common when creating from a client, where you have a select box for allowed relation items, and you already have their id when you submit the request.

Currently in order to allow creation of an Entity i'm forced to do it like this (FYI this is a resolver for GraphQL server):
```ts
const mutations = {
  createRoute(
    root: any,
    { relations, ...data }: Route & RelationArgs,
    { connection, user }: TypeORMContext,
  ) {
    const route = new Route();
    Object.assign(route, data)
    route.createdBy = route.updatedBy = Promise.resolve(user);
    Object.entries(relations)
      .forEach(([ key, id ]) => {
        const property = key.replace('Id', '')
        route[ property ] = Promise.resolve({ id })
      })

    return connection
      .manager
      .save(route)
  },
  updateRoute(
    root: any,
    { id, relations, ...route }: Route & RelationArgs,
    { connection, user }: TypeORMContext,
  ) {
    route.updatedBy = Promise.resolve(user);
    Object.entries(relations)
      .forEach(([ key, relationId ]) => {
        const property = key.replace('Id', '')
        route[ property ] = Promise.resolve({ id: relationId })
      })
    return connection
      .manager
      .updateById(Route, id, route)
      .then(() => true)
  },
}
```
Please check that i have to loop through all relations, remove the `Id` part of the property name, then wrap with a resolved promise and an object containing the actual id that was passed.

Isn't there a better, less verbose way around this if i already have the relations ids that the library requests for non-nullable relations?

**Comment by pleerock** [comment]
can you please provide a shorter and more concrete code for me to review? Without graphql specifics and dynamic transformations? So I can quickly understand what is the issue in?

**Comment by luchillo17** [comment]
Ok, lets say the client already has the `id`s for the relations, to save them i would have to wrap them in an object and additional to that in a promise, even if i already have such ids.

Maybe something like this:
```ts
@Entity()
export class Post {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  title: string

  @Column()
  message: string

  // Relations
  @OneToMany(
    (type) => Comment,
    (comment) => comment.post,
  )
  comments: Promise<Comment[]>
}

@Entity()
export class Comment {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  message: string

  @RelationId((comment: Comment) => comment.post,)
  postId: number

  @ManyToOne(
    (type) => Post,
    (post) => post.comments,
    { nullable: false },
  )
  post: Promise<Post>
}
```
Now try saving a comment with the id of an already existing post without using this:
```ts
const postId = 1 // Example, could be any, comes from client
const comment = new Comment()
comment.post = Promise.resolve({ id: postId }) // Don't do this, i already have the id for the relation
connection.manager
    .save(comment)
```

The idea is to not `promise.resolve` the relation since i already have the id of it, should be able to use `comment.postId = postId`, but that's not the case because `RelationId` is just for queries to be able to see the relation id and that's all.

**Comment by pleerock** [comment]
Okay, so you want to be able to save a relation by only using `postId`. Its not possible because `@RelationId` is not working for saving. Maybe this will be changed in the future, but right now its not working this way. But you can implement it other way:

```ts
@Entity()
export class Comment {
  @PrimaryGeneratedColumn()
  id: number

  @Column()
  message: string

  @Column({ nullable: true })
  postId: number

  @ManyToOne(
    (type) => Post,
    (post) => post.comments,
    { nullable: false },
  )
  post: Promise<Post>;
}
```

And it will work as you expect.

**Comment by luchillo17** [comment]
I can't believe i didn't thought about that, i'll try and let you know.

**Comment by luchillo17** [comment]
@pleerock Dude works like a charm, don't need to wrap the relations in promises with ids any more, however i'm a bit worried how will it play on the migration creation command, which one does it take as priority, the `postId` column, thus generating only the column? or the `post` column, thus also generating the foreign key sql?

**Comment by pleerock** [comment]
it should work fine. There is no `post` column, even if you don't add `postId` column `post` relation always creates a column named `postId`.

**Comment by luchillo17** [comment]
Yeah, `postId` column should be created no matter what, but what about the foreign key constraint, that is what i meant.

**Comment by pleerock** [comment]
it will be created as well since you have a relation, just check that

**Comment by luchillo17** [comment]
So it's like they overlap and no matter which one get's taken last it will create all properties, right?, anyway this works like a charm, thanks.
