### ISSUE TITLE
EventSubscriber beforeInsert, afterInsert missing data for junctionTables

### ISSUE THREAD

**Issue by Ainias** [typeorm/typeorm#9974]
### Issue description

The EventSubscriber's beforeInsert, afterInser, methods are called for junction tables. But there is no way to get the data that is inserted 

### Expected Behavior

When a many-to-many-relationship is inserted, the EventSubscriber's functions are called. Inside this functions there shuld be a way to get the data that is inserted or removed. Normally this would be via the `entityId`  object like in `beforeRemove` and `afterRemove`. But in the case of a junction-table this is not defined and `entity` is undefined. 

I'm working on a synchronisation-library that has a mysql-server-database and a sqljs-client one. The basic idea is to execute the query locally, send the query to the server together with a `last executed`-timestamp and execute the query there again with only selecting the changed entities since the `last executed`-timestamp. For this every model has an `updatedAt` column, which is compared at database-level. 

The `updatedAt` column is updated through an EventSubscriber.
if a Many-to-Many relation is updated, the EventSubscriber for the saving entity is not called, as described in https://github.com/typeorm/typeorm/issues/412 which is fine. I want to get the two entities of the relation that is saved in the junctionTable, that triggers the EventSubscriber's function and update the `updatedAt` manually from the EventSubscriber for those two. But alas the referenced primary keys are not accessible inside the EventSubscriber's function. From the metadata send inside the event I can get the corresponding EntityClasses and Tables inside the database, but not the entities.

### Actual Behavior

The values should be somehow accessible inside the EventSubscriber's functions. Prefferably via the `entity` or `entityId` object.

### Steps to reproduce

1. Add an EventSubscriber which listen to all models
2. Change and save a many-to-many relation with a junction table
3. event.entity inside the EventSubscriber's beforeInsert and afterInsert functions for the junction table is undefined and there is no way of getting the saving data

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Linux        |
| Node.js version     | 16.20.0  |
| Typescript version  | 4.6.3  |
| TypeORM version     |  0.3.14 (because of https://github.com/typeorm/typeorm/issues/9959 not 0.3.15) |

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by spotykatch** [comment]
Please provide some code. English is cool, but `typescript` is better.


As you selected `Yes, I have the time, but I don't know how to start. I would need guidance.`
If you create some tests like [it is described here](https://github.com/spotykatch/typeorm/blob/master/DEVELOPER.md), that would be nice. You can also start your pr like a draft.

Subscribers are called by [Broadcaster](https://github.com/typeorm/typeorm/blob/master/src/subscriber/Broadcaster.ts) and all the stuff is stored inside `metadata` which is mutated inside [SubjectExecutor](https://github.com/typeorm/typeorm/blob/master/src/persistence/SubjectExecutor.ts). You will also should think about 'CASCADE' stuff, which is a pain in the :heart:

**Comment by Ainias** [comment]
Thanks @spotykatch for the infos. 
I've created a pull-request with the changes. It was surprisingly easy as the Subject has already every information that is needed and it is working with cascading. Although if new entities are saved, the IDs for those are undefined inside `beforeInsert` as they don't exists in the database yet. But this is nothing we can change

**Comment by Ainias** [comment]
This is fixed with https://github.com/typeorm/typeorm/pull/10540
