### ISSUE TITLE
websql version option issue

### ISSUE THREAD

**Issue by dmitri-wm** [typeorm/typeorm#998]
Thanks for great job, it's the only orm I see to use together with ionic app.

But having issue with websql.
```
import { Injectable } from "@angular/core";
import { Department } from "../models/department";
import { createConnection } from "typeorm";

createConnection({
      type: "websql",
      database: "app",
      version: 1,
      description: 'app',
      size: 100,
      entities: [
        Department
      ],
})

```

Getting error: 'Failed to execute 'openDatabase' on 'Window': unable to open database, version mismatch, '1' does not match the currentVersion of '1.0' '

If I change in options versions from 1 to '1.0' 

Getting error: 
Argument of type '{ type: "websql"; database: string; version: string; description: string; size: number; entities:...' is not assignable to parameter of type 'ConnectionOptions'. Type '{ type: "websql"; database: string; version: string; description: string; size: number; entities:...' is not assignable to type 'WebSqlConnectionOptions'. Types of property 'version' are incompatible. Type 'string' is not assignable to type 'number'.

But if I change at 

typeorm/driver/websql/WebSqlConnectionOptions.d.ts:17

from 
    readonly version: number;
to
    readonly version: string;

Looks like it works nicely :)

I can create PR for this.

**Comment by daniel-lang** [comment]
You are right, the version "number" should be a string.
A tip: I would recommend using the `cordova` sqlite driver in ionic since websql is deprecated as a standard. You can check out [typeorm/ionic-example](https://github.com/typeorm/ionic-example)
