### ISSUE TITLE
orderBy broken by 0.3.15

### ISSUE THREAD

**Issue by Naymi** [typeorm/typeorm#9986]
### Issue description

orderBy broken by 0.3.15

### Expected Behavior

SELECT "user"."id" AS "user_id", "user"."name" AS "user_name" FROM "user" "user" ORDER BY "user_name" DESC NULLS LAST

### Actual Behavior

SELECT "user"."id" AS "user_id", "user"."name" AS "user_name" FROM "user" "user" ORDER BY "user_name" [object Object]

### Steps to reproduce

https://codesandbox.io/p/sandbox/lucid-knuth-v7dl6x
/index.ts

### My Environment

in sandbox

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by pleerock** [comment]
yes, you can use dev version for now (check the latest dev version on npm).
