### ISSUE TITLE
Create table comment

### ISSUE THREAD

**Issue by yuntian001** [typeorm/typeorm#9991]
### Feature Description

You can use entities to create table comments

### The Solution

@Entity({commint:'user table'})

### Considered Alternatives

You can use entities to create table comments

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by spotykatch** [comment]
`scr/decorator/Entity.ts` it definitely starts here

**Comment by sinkhaha** [comment]
I have also encountered this issue, I have already submitted a pr.
